### ISSUE TITLE
freecoursesguru.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100013]
**Issue URL (Ads/Annoyance)**:  `https://freecoursesguru.com/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141653997-cde4f49e-4e56-4ded-81e7-cda7c2f9d6a0.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
