### ISSUE TITLE
Google Shopping filter not working anymore

### ISSUE THREAD

**Issue by YoshiTabletopGamer** [AdguardTeam/AdguardFilters#100003]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
The filter at https://github.com/AdguardTeam/AdguardFilters/blob/6ce883a2272aa39966a65c0cf30eaafa9976ba43/EnglishFilter/sections/css_extended.txt#L442

which is intended to block ads in the Google Shopping section, stopped working.

I have attached a screenshot of a Google Shopping search for "smartphone". I highlighted the ads with a red rectangle.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/88633614/141652527-99cf691c-4768-4a67-8ab3-8130b688e586.png)
</details><br/>

***System configuration***

Information                            | Value
---                                    | ---
Browser:                               | Firefox 94.0.1
Filters enabled:                       | Built-in uBlock Filters (uBlock filters, uBlock filters – Badware risks, uBlock filters – Privacy, uBlock filters – Resource abuse, uBlock filters – Unbreak), Adguard Base, EasyList, EasyPrivacy, Online Malicious URL Blocklist, Peter Lowe's Ad and tracking server list, spa, por: AdGuard Spanish/Portuguese
Content Blocker                        | Ublock Origin 1.38.6

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by piquark6046** [comment]
On Firefox with AdGuard Browser Extension, the mentioned rule works well.

**Comment by YoshiTabletopGamer** [comment]
> 
> 
> It seems that the mentioned rule works well on Firefox with AdGuard Browser Extension.

I have made a new Firefox browser profile, and I figured out the filter does not work because there's no `div` with `eid` attribute

**Comment by YoshiTabletopGamer** [comment]
Can you share the DOM of the `div` that matches the following part `div[eid][data-async-context]`?

**Comment by YoshiTabletopGamer** [comment]
For me, there's the corresponding div with the class `sh-sr__shop-result-group` directly inside the div with id `rso`

**Comment by piquark6046** [comment]
@YoshiTabletopGamer 
Here you are.

<details>
<summary>Screenshot</summary>

![Screenshot](https://user-images.githubusercontent.com/37463155/141665940-2577af7c-d4f0-4fef-aa49-bd126a122096.png)

</details>

**Comment by YoshiTabletopGamer** [comment]
Is the `id` always equal to `rso`? I have tested and I determined that depending on the IP address, the `class`, `eid` and `data-async-context` attributes are missing. Only the `rso` `id` remains in the other IP (`<div id="rso">`)

**Comment by YoshiTabletopGamer** [comment]
google.*#?##rso > .sh-sr__shop-result-group[data-hveid]:has(> div[class] > div[class] > .sh-sp__plain) works for me

**Comment by Alex-302** [comment]
Need sample link.

**Comment by YoshiTabletopGamer** [comment]
`https://www.google.com/search?q=smartphone&tbm=shop`

**Comment by YoshiTabletopGamer** [comment]
https://github.com/AdguardTeam/AdguardFilters/blob/79e11b4782f9a16b78a9e79ed66d0e9bbda6d052/EnglishFilter/sections/css_extended.txt#L469

had already fixed this for me

**Comment by Alex-302** [comment]
Checked with NL IP - that element is hidden.
