### ISSUE TITLE
computingforgeeks.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#100002]
[https://computingforgeeks.com/zorin-os-vs-elementary-os-which-one-to-choose/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://computingforgeeks.com/zorin-os-vs-elementary-os-which-one-to-choose/)

![leftovers](https://user-images.githubusercontent.com/35470489/141652301-9ad98f33-af9b-4786-99fe-530d46821175.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
This is uBO's issue. The necessary rule exists in EasyList - `##.ezoic-ad`

**Comment by Alex-302** [comment]
Reported them.
