### ISSUE TITLE
telecomtalk.info

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100008]
**Issue URL (Ads/Annoyance)**:  `https://telecomtalk.info/airtel-black-plan-that-offers-broadband-dth/472108/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141653096-67eae813-9012-4d19-bb41-2153d525abc0.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

**Comment by zloyden** [comment]
What's wrong?
