### ISSUE TITLE
www.stepsize.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100076]
**Issue URL (Ads/Annoyance)**:  `https://www.stepsize.com/blog/how-to-refactor-code-in-visual-studio-code`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141672908-49ab0d58-49c6-4a14-b890-d0388ee08b5c.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
