### ISSUE TITLE
youla.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#100197]
Рекламные вставки в разделе 'Похожих объявлений', под основным объявлением.

<details><summary>Screenshot:</summary>

![2021 11 15-1](https://user-images.githubusercontent.com/17948007/141790976-c01896d8-3b75-48d9-9807-85b647ccb668.png)
</details>

`youla.ru##[data-test-component='ProductOrAdCard']:has([data-test-component='AdvertisementCard'])`

[https://youla.ru/sankt-peterburg/kompyutery/komplektuyushchie/zhiestkii-disk-st1000dx0011cm162sshd-6163f339d0746d1e18060967](https://href.li/?https://youla.ru/sankt-peterburg/kompyutery/komplektuyushchie/zhiestkii-disk-st1000dx0011cm162sshd-6163f339d0746d1e18060967)
<br>

 Система | Фильтры | Антитрекинг
---------- | ---------- | ----------
 AdGuard v3.6.13 | Базовый AdGuard &nbsp; &nbsp; &nbsp; &nbsp; Русский | Стандарт
 FireFox v78.13 ESR | Счётчиков и аналитики &nbsp; &nbsp; &nbsp; &nbsp; Отслеживания по URL | +Блокировка WebRTC
 Win7SP1 | Виджетов социальных сетей &nbsp; &nbsp; &nbsp; &nbsp; Раздражителей | +Удаление параметров отслеживания

**Comment by XX-J** [comment]
С моим правилом пустое место от рекламных блоков собирается справа, в единую колонку. С Вашим же - пустые блоки остаются разбросаны по всему разделу 'Похожих объявлений', что не столь привлекательно...

**Comment by XX-J** [comment]
**1**. В поиске, наверху плашка - остаток от рекламы.

<details><summary>Screenshot:</summary>

![2022 02 12-1](https://user-images.githubusercontent.com/17948007/153729550-bd80c276-17ec-4335-9ad0-bb64c5396b8b.png)
</details>

`youla.ru##main section > div:nth-child(1)`

___________________________________________________

 **2**. Правила скрывающие рекламные плашки в поисковой выдаче портят динамическую прогрузку и выгрузку этой выдачи. Она становится как бы "рваной" (см. видео).

<details><summary>Как сейчас:</summary>

https://user-images.githubusercontent.com/17948007/153729348-ea14e713-1e73-4c28-a500-a49a621e7978.mp4
</details>

 Если внести в исключения следующие два правила из Русского фильтра:
```
youla.ru#?#div[data-test-component="ProductOrAdCard"]:has(> span):not(:has(div))
youla.ru##div[data-test-component="ProductOrAdCard"] > span[class*=" "]
```
, то на пустых от рекламы местах останутся просто серовато-белые прямоугольники без рекламы, но зато поисковая выдача, при прокрутке, НЕ будет "рваться" и проматываться в конец (см. видео).

<details><summary>Как должно быть:</summary>

https://user-images.githubusercontent.com/17948007/153730179-5051a2f8-7f58-456c-909e-80c8d74c7662.mp4
</details>

[https://youla.ru/sankt-peterburg?q=ZTE A6 Lite](https://href.li/?https://youla.ru/sankt-peterburg?q=ZTE%20A6%20Lite)
<br>

 Система | Фильтры | Антитрекинг
---------- | ---------- | ----------
 AdGuard v3.6.17 | Базовый AdGuard &nbsp; &nbsp; &nbsp; &nbsp; Русский | Стандарт
 FireFox v78.13 ESR | Счётчиков и аналитики &nbsp; &nbsp; &nbsp; &nbsp; Отслеживания по URL | +Блокировка WebRTC
 Win7SP1 | Виджетов социальных сетей &nbsp; &nbsp; &nbsp; &nbsp; Раздражителей | +Удаление параметров отслеживания

**Comment by XX-J** [comment]
@Sergey-Lyapin - глянь...

**Comment by Sergey-Lyapin** [comment]
@XX-J Проверь через пару часов, должно стать нормально.

**Comment by XX-J** [comment]
Стало нормально, но правило `youla.ru##.kRNTcS` думаю скоро "протухнет". Вместо него лучше использовать `youla.ru##main section > div:empty`.

**Comment by XX-J** [comment]
@Sergey-Lyapin, как я предполагал, так и случилось:

>  ...правило `youla.ru##.kRNTcS` думаю скоро "протухнет". Вместо него лучше использовать `youla.ru##main section > div:empty`.
