### ISSUE TITLE
www.deccanherald.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100107]
**Issue URL (Ads/Annoyance)**:  `https://www.deccanherald.com/national/india-s-last-minute-coal-defence-at-cop26-hid-role-of-china-us-1050579.html`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141681007-8e6405ab-0601-4a20-ade1-b9aa642be3a1.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

**Comment by zloyden** [comment]
Not an annoyance.
