### ISSUE TITLE
gotxx.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#100103]
https://www.gotxx.com/hot-web-series/day-2-day-s01-e01-cliff-movies-original-erotic-hindi-web-series/

Seeing ad block message & pop-ups on this page. Checked with AG extension for Chrome

**Comment by Nzzyme** [comment]
Hi, still seeing a adblock message on AG extension for Chrome on Windows.
https://www.gotxx.com/hot-web-series/peeche-se-s01-e02-rabbit-hindi-bgrade-adult-hot-web-series/
https://prnt.sc/21twvkn

Can you please check?

**Comment by Yuki2718** [comment]
> Can you please check?

Fixed.

@Alex-302 @BlazDT @zloyden @Sergey-Lyapin @stanislav-atr
Can you please check anti-popup filter? abort-on-stack-trace doesn't work on Ext v3. This script causes that: `https://www.gotxx.com/wp-content/litespeed/js/e787e28d4d9e60ba019a9eda0e884088.js?ver=84088`

**Comment by Yuki2718** [comment]
I thought abort-on-property-read with Stack parameter worked but was wrong, temp replaced by prevent-window-open but this requires unnecessarily more clicks.

**Comment by Alex-302** [comment]
@Yuki2718 Why not to block `||gotxx.com/wp-content/litespeed/js/e787e28d4d9e60ba019a9eda0e884088.js`? It seems this works.

**Comment by Alex-302** [comment]
> abort-on-stack-trace doesn't work on Ext v3.

Publick 4.0 beta is here
https://chrome.google.com/webstore/detail/adguard-adblocker-beta/gfggjaccafhcbfogfkogggoepomehbjl

**Comment by AdamWr** [comment]
If I'm not wrong, issue with "more clicks" can be also fixed by this rule:
```
gotxx.com#%#//scriptlet("json-prune", "*", "openTargetBlank")
```

**Comment by Yuki2718** [comment]
> If I'm not wrong, issue with "more clicks" can be also fixed by this rule:
> 
> ```
> gotxx.com#%#//scriptlet("json-prune", "*", "openTargetBlank")
> ```

Working, added: https://github.com/AdguardTeam/AdguardFilters/commit/9ec3d265c98385f7e71fe1ad7c030b0e3610aeff
