### ISSUE TITLE
News in google now may be temporary stopped

### ISSUE THREAD

**Issue by twrbo** [AdguardTeam/AdguardFilters#100167]
Sometimes opening a link may happen this condition, too. 

![Screenshot_20211115-123905](https://user-images.githubusercontent.com/24449805/141723966-979224cb-0b6b-4120-96dc-c947335fed2e.png)
![Screenshot_20211115-124014](https://user-images.githubusercontent.com/24449805/141723970-ea838f6a-c331-4c62-a88b-76492aacecfa.png)

**Comment by Alex-302** [comment]
Related to https://github.com/AdguardTeam/AdguardFilters/issues/100168 Please look answer here.
