### ISSUE TITLE
www.alphr.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100199]
**Issue URL (Ads/Annoyance)**:  `https://www.alphr.com/mass-unsubscribe-youtube/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141791801-62ed7c41-334d-4b61-b349-21c0ec1ca9e6.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

**Comment by zloyden** [comment]
Not a share.
