### ISSUE TITLE
adultmult.tv

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#1001]
Антиадблок на сайте.

https://a.disquscdn.com/uploads/mediaembed/images/2860/2327/original.jpg

**Comment by Alex-302** [comment]
добавил
@@||adultmult.ru/advert.js

**Comment by vozersky** [comment]
@Alex-302  посмотри плиз

снова скрипт:

![original](https://cloud.githubusercontent.com/assets/17472907/18395158/feddfc7a-76c5-11e6-937a-2b5e50bab437.jpg)


повторил с хромовским экстеншеном beta, стандартный набор фильров

**Comment by Alex-302** [comment]
Не повторяется.
