### ISSUE TITLE
www.aignes.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100213]
**Issue URL (Ads/Annoyance)**:  `https://www.aignes.com/deadlink.htm`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141805743-1dc6788f-c340-4edb-853c-6426d11fe1a6.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

**Comment by zloyden** [comment]
The website has low visitors.
