### ISSUE TITLE
Awarding the best AdGuard contributors in 2021

### ISSUE THREAD

**Issue by el-termikael** [AdguardTeam/AdguardFilters#100207]
Hello, @Yuki2718 and @piquark6046! 

My name is Helen, I'm a content manager at AdGuard. Currently we’re preparing a blog post about the most active community contributors of the year, and you undoubtedly deserve a spot there. Congratulations and big thanks for your help!

Please contact me at e.ter-mikaelyan@adguard.com to discuss the best way to send you our special gift bag and other details.

**Comment by ameshkov** [comment]
Closing since this is a one-time notification.
