### ISSUE TITLE
www.theandroidportal.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100201]
**Issue URL (Ads/Annoyance)**:  `https://www.theandroidportal.com/unsubscribe-from-all-youtube-channels/`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141792091-88206fcc-10f6-4a07-808a-9497f6422c78.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

**Comment by zloyden** [comment]
Not an ad.
