### ISSUE TITLE
www.thewindowsclub.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100200]
**Issue URL (Ads/Annoyance)**:  `https://www.thewindowsclub.com/how-to-unsubscribe-from-all-your-youtube-channels-at-once`

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/141792059-d1d8d07c-dd01-4d6b-8f75-ca1fb68bb4b6.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

**Comment by gork7777** [comment]
These are not share buttons.
