### ISSUE TITLE
www.file-upload.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100395]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);;
- [X] Filters were updated before reproduced an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.14

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) is used?

Chrome

### Which device is used?

Desktop

### Where did you encounter the problem?

`https://www.file-upload.com/ev3cncmjy1cu`

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/142204491-b1da691d-9a63-4514-b492-49a72347afde.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
They have a server-side check.
