### ISSUE TITLE
Bypass

### ISSUE THREAD

**Issue by FinderID** [AdguardTeam/AdguardFilters#100422]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

https://1shortlink.com/api/v1/full-pages?api_key=cab1700e53ac3a2e1584425a5aad8c3cf3b050aa&url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xOEwzTmMyOXhocGY4MnpGTVZmVWRIc0hWOUU1WG10M3ovdmlldz91c3A9c2hhcmluZw==&type=2

### Proposed solution

please bypass the short link, thanks :)

**Comment by FinderID** [comment]
https://1shortlink.com/api/v1/full-pages?api_key=cab1700e53ac3a2e1584425a5aad8c3cf3b050aa&url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xOEwzTmMyOXhocGY4MnpGTVZmVWRIc0hWOUU1WG10M3ovdmlldz91c3A9c2hhcmluZw==&type=2

**Comment by FinderID** [comment]
https://1shortlink.com/api/v1/full-pages?api_key=cab1700e53ac3a2e1584425a5aad8c3cf3b050aa&url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xaGJqMDJBY2dFbXBjSnI1bEhXUGVuN2V6dUJtSFNnWEcvdmlldz91c3A9c2hhcmluZw==&type=2

**Comment by Andy-Kl** [comment]
you could try this extensions for that: Skip Redirect

https://addons.mozilla.org/de/firefox/addon/skip-redirect/
https://chrome.google.com/webstore/detail/skip-redirect/jaoafjdoijdconemdmodhbfpianehlon

**Comment by FinderID** [comment]
thanks @Andy-Kl
