### ISSUE TITLE
How can I make this rule general?

### ISSUE THREAD

**Issue by furt555nv** [AdguardTeam/AdguardFilters#100483]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

I see the recommended news widget provided by Disqus on many sites and forums. So I created a general rule that will work on all sites but I'm not sure if it's correct.
Is the rule safe or does it need to be replaced by another rule?

<details>
 <summary>Screenshot</summary>
 
![d1](https://user-images.githubusercontent.com/89068379/142446136-5458eadb-e0e2-4417-be0b-8d5d04541049.png)

</details>

<details>
 <summary>My rule</summary>
 
![12we](https://user-images.githubusercontent.com/89068379/142447913-4a0b79be-c1bd-4086-86e3-b0d0446bdbbe.png)

</details>

### Proposed solution

`||disqus.com/recommendations.js`

### Additional information

`https://www.brandeating.com/2021/11/kfc-introduces-new-quick-pick-up-as-faster-alternative-to-drive-thru.html`

**Comment by Yuki2718** [comment]
Yes, the rule is correct and should work on all sites unless the path varies for some reason or there's another allow rule.

**Comment by furt555nv** [comment]
@Yuki2718 OK, got it. Thanks for your help

**Comment by Yuki2718** [comment]
You're welcome!
