### ISSUE TITLE
hackr.io

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100536]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.14

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://hackr.io/blog/python-programming-language`

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/142597522-26263d6e-2e83-4ad6-b521-523ebb7dd898.png)

</details><br/>

<details><summary>System configuration:</summary>

![image](https://user-images.githubusercontent.com/76880977/141497551-099fafbf-933f-44c7-956a-f88fc1bcb5d5.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by chirag127** [comment]
Why Invalid tag is added to this issue?

**Comment by zloyden** [comment]
Not an ad or an annoyance, removed share.

> Why Invalid tag is added to this issue?

Idk, you should ask @Alex-302.

**Comment by zloyden** [comment]
Of course.
```
hackr.io#?#.right-column > .post-wrapper:has(> .post-head > p > strong:contains(Disclosure:))
```

**Comment by Alex-302** [comment]
> Why Invalid tag is added to this issue?

Because some reports has screenshot of settings instead of issue. 
In any case we check all opened issues without exception.

**Comment by neer9** [comment]
> Because some reports has screenshot of settings instead of issue.

some reports had screenshot of settings inaddition of issue?
