### ISSUE TITLE
briefly.co.za

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100638]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.14

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://briefly.co.za/34793-here-a-list-difficult-degree-south-africa.html`

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/142685953-ce3f11d7-0a4d-4644-8ded-dbbf280270d7.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Do not post screenshot of report. Use provided list.
