### ISSUE TITLE
www.pmindiaun.org

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100717]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.14

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`http://www.pmindiaun.org/pages_id_10.html`

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/142739015-f8ae0fc9-3e45-4012-83dd-f204dfd126c6.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
The website has low visitors.

**Comment by chirag127** [comment]
@jellizaveta 

Which tool are using to find the monthly visitors?

**Comment by jellizaveta** [comment]
@chirag127 
I use **VStat 2** browser extension, [**a.pr-cy.ru**](https://pr-cy.ru/) website and if resource contains social networks, I can check social media following.

**Comment by chirag127** [comment]
> @chirag127 I use **VStat 2** browser extension, [**a.pr-cy.ru**](https://pr-cy.ru/) website and if resource contains social networks, I can check social media following.

Hmm.. Vstat2 browser extension seems good, so I will not make report if i see the visitors are less.
