### ISSUE TITLE
www.fluentu.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100738]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.14

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://www.fluentu.com/blog/educator-english/conversation-questions-for-the-esl-classroom/`

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/142743994-d9e6a960-cb13-4ea6-9a70-cde02d0f2acc.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
It's link to their product.

**Comment by chirag127** [comment]
> It's link to their product.

well it's a blog and a click bait looking annoying self promotion, i think that it comes in self promotion in annoyance.
