### ISSUE TITLE
blog.treering.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100739]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.14

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://blog.treering.com/48-yearbook-questions-guaranteed-to-get-teachers-to-open-up-during-interviews/`

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/142743856-ba8aaabf-58c4-441e-a420-b55389dddbd3.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
We don't hide newsletters buttons if they located in header or footer.
