### ISSUE TITLE
AdGuard Desktop Client Loads Advertisements During Sleep Mac 10.13

### ISSUE THREAD

**Issue by jimmysofat6864** [AdguardTeam/AdguardFilters#100752]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.5.1.928

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Desktop

### Where is the problem encountered?

www.spotify.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Social Blocking List, Web Annoyances Ultralist, Peter Lowe's Blocklist, Adblock Warning Removal List, Online Malicious URL Blocklist, Spam404, Fanboy's Enhanced Tracking List, I don't care about cookies, NoCoin Filter List, Polish Anti-Annoying Special Supplement, Dandelion Sprout's Nordic Filters, Dandelion Sprout's Annoyances List, Legitimate URL Shortener

### Add your comment and screenshots

Advertisements get through when MacBook is in sleep. On High Sierra 10.13. To reproduce this issue, open spotify then leave mac in sleep for some time. When waking from sleep, the ads leak through and ads remain until spotify is quit then open again. 

![Screen Shot 2021-11-04 at 5 22 42 PM](https://user-images.githubusercontent.com/69532417/142744910-1008f20a-17d2-492b-88d5-bbb7eb685402.png)
![Screen Shot 2021-11-04 at 5 23 00 PM](https://user-images.githubusercontent.com/69532417/142744913-670dd4e7-9deb-4855-8366-0d79618cd135.png)
![Screen Shot 2021-11-04 at 5 25 11 PM](https://user-images.githubusercontent.com/69532417/142744914-e12ca4d7-6e98-4ef0-89b8-9a673037f0f7.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardForMac #994](https://github.com/AdguardTeam/AdguardForMac/issues/994) via [**ZenHub**](https://www.zenhub.com/)
