### ISSUE TITLE
css-tricks.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100841]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.14

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://css-tricks.com/snippets/html/autocomplete-off/`

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/142804655-74c70846-d1a8-4410-adec-8d8bea3a76d9.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
It doesn't look like an ad.
There should be comments in this place and it's displayed correctly on my end.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/144624954-d07728de-e401-4182-b46f-404bc293d0bc.png)

</details>
