### ISSUE TITLE
crankyseven-k.com (N: uBlock Origin) (T: Ads)

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#100932]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBO 1.38.7rc1 + IDCAC 3.3.4

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://crankyseven-k.com/kaiseki-ka/1134

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Japanese filter, EasyList Lithuania, Adblock List for Finland, Frellwit's Swedish Filter, Dandelion Sprout's Nordic Filters, Dandelion Sprout's Annoyances List

### Add your comment and screenshots

1. An external(?) casino floaty ad in the lower left, and 2 placeholders. I propose for AdGuard Japanese:
```
crankyseven-k.com##.afc_popup
crankyseven-k.com###keni_toc
crankyseven-k.com##div[id^=zucksad]
```

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/22780683/142954797-5639046d-6b72-4277-8fcf-f97d0cbd9515.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
> crankyseven-k.com##div[id^=zucksad]

Blocked by `||zucks.net.zimg.jp^$third-party`
