### ISSUE TITLE
qiita.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#100995]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.14

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`https//qiita.com/takeshisakuma/items/5a61e6eac123d28602fb`

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/143034856-85a7140a-b5a7-4d71-849e-6a7bce6bb1dd.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by Yuki2718** [comment]
The placeholder in SS can not be fixed. And what Annoyances? No description of filters enabled and no SS for them.

**Comment by Yuki2718** [comment]
I don't see any Annoyances with Annoyances filters enabled.

**Comment by chirag127** [comment]
> no SS for them.

Well Alex don't like the SS. So I stopped using ss and only fill the default template.



> 

Well the place holder seems to be annoyance to me. But seems like it can be fixed as you say.
