### ISSUE TITLE
venmo.com - missed facebook share button

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#1010]
> When logged into venmo.com there are three social buttons on the right side of the page: Facebook Like, Facebook Share, and Tweet. With Adguard enabled, the icons for Facebook Like and Tweet are blocked, but Facebook Share is not blocked. This occurs on both iOS and OS X (iOS must use the desktop site, but the issue is still present).

**Comment by Alex-302** [comment]
I can't register there without US phone number. SMS does not come.

**Comment by ameshkov** [comment]
Try this:
http://receivesmsonline.com/

**Comment by Alex-302** [comment]
Services like this didn't receive sms from this site. Maybe it have the black list.
