### ISSUE TITLE
w2.notificacaoconta.com

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdguardFilters#101142]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0 nightly 25

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

other(specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

w2.notificacaoconta.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Spanish/Portuguese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Self-destruction of third-party cookies, Block WebRTC, Hide your Referrer from third-parties (specify in comment below, if used custom value), Hide your User-Agent (specify in comment below, if used custom value)

### Add your comment and screenshots

-w2.notificacaoconta.com
-https://w2.notificacaoconta.com/81ed19f6-4d54-11ec-8b41-de1c14642009

The site are trying to get through with the Banco Do Brasil( bank

(Site used to attempt to steal bank details or credit / debit card falsifying the identity of Caixa Econômica Federal)

![Screenshot_20211124-153008_Samsung Internet](https://user-images.githubusercontent.com/16819380/143294895-d72ead75-6a08-4c03-88c3-989d01216f43.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by chirag127** [comment]
Which browser are you using?

**Comment by eduardoaddad** [comment]
Samsung Internet

**Comment by DandelionSprout** [comment]
Seems like the bank scammers used a quick-throwaway domain, to the point where not even [SecurityTrails](https://securitytrails.com/domain/notificacaoconta.com/dns) have any info on who was behind it.
