### ISSUE TITLE
www.reuters.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#101137]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.14

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`https:/www.reuters.com/markets/commodities/china-has-upper-hand-us-asks-beijing-release-oil-reserves-global-times-2021-11-24/`

### What filters do you have enabled?

AdGuard Base filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/143277183-7d01ffd0-5729-428d-a787-041842cfee54.png)

![image](https://user-images.githubusercontent.com/76880977/143277291-012783f5-911e-46a8-8143-28e41250ac7b.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
I propose `reuters.com##div[class^=leaderboard__container___]`

**Comment by AdamWr** [comment]
https://github.com/easylist/easylist/commit/0602360e4ec6370f72eeed25c85ff8d4ccc9fbe8#diff-d95e1ad0368a5fb3bacb89fc7f209b9fa33a9974d9d2cf4b9a98903b7aa356a2R2414
