### ISSUE TITLE
Fingerprinting domains

### ISSUE THREAD

**Issue by rndmUsr678** [AdguardTeam/AdguardFilters#101119]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Some fingerprinting domains are not included in the AdGuard Spyware Filter

### Proposed solution

This GitHub repository contains a big database of domains associated with Fingerprinting (https://github.com/uiowa-irl/FP-Inspector/blob/master/Data/fingerprinting_domains.json), I propose investigating whether they should be added to the Spyware Filter or not.

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/145058235-154dfae0-fbd2-4e6a-a659-de9d84501a66.png)
Not sure aboun 14k non-checked domains.
