### ISSUE TITLE
www.timesnownews.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#101136]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.14

### What type of problem have you encountered?

Social media buttons — share, like, tweet, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://www.timesnownews.com/india/article/india-cannot-have-normal-relationship-with-china-until-everything-is-resolved-foreign-secretary-hv-shringla/834865`

### What filters do you have enabled?

AdGuard Base filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/143276481-90a9a9d5-af3f-48ad-81a0-66e9eab70900.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by gork7777** [comment]
Cannot reproduce

**Comment by chirag127** [comment]
> Cannot reproduce

Url was wrong, there was a typo.
