### ISSUE TITLE
new link bypass needed or social filter

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardFilters#101264]
@Wendys-corp commented on [Mon Nov 15 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1886)

im using chrome 
everything auto updates
it does not link bypass

https://social-unlock.com/5ZHmn

---

@Birbber commented on [Mon Nov 22 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1886#issuecomment-975231262)

@Wendys-corp Hi! Sorry for the late reply. Could you add more details on your request? Is something not working on this webpage or should it be blocked?

---

@krystian3w commented on [Tue Nov 23 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1886#issuecomment-976598313)

It ask to add auto-click (or other workaround like use `set-constant`) in 4 social buttons used as social wall.

So you can move this by "zenhub" into "AdGuardFilters". Maybe filter  writer found safest solution.

IMO this wall is poor, badly check needed actions like "subscribe channels" - possible click on link by right click and immediately/instantly close opened tabs and page after 2 seconds accept activity as correct.

**Comment by Alex-302** [comment]
Without pressing the first 4 buttons `Unlock content` button opens https://drive.google.com/drive/folders/1M9wcyJwvyNDQfFjlmR1OSGhxk1OkgtQG

**Comment by Alex-302** [comment]
@Wendys-corp

**Comment by krystian3w** [comment]
On my side without JavaScript rule last button is disabled and controlled by JavaScript on page (after bad unlock (CSS rule only) open fake url like twitter instead google drive).
