### ISSUE TITLE
www.rugbypass.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#101206]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.14

### What type of problem have you encountered?

Missed ads or ad leftovers, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://www.rugbypass.com/news/bid-revision-leaves-england-australia-usa-set-to-host-world-cup-world-rugby/`

### What filters do you have enabled?

AdGuard Base filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/143454383-574ffb28-3140-4126-9437-9c6f70644859.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
I propose `##.main-header-ad`
