### ISSUE TITLE
AdGuard interferes with the Голосовой ввод для ВКонтакте extension for Chrome

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#10134]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: AdGuard is blocking the [Голосовой ввод для ВКонтакте](https://chrome.google.com/webstore/detail/vkcom-voice-input/akkdpnmniomdbpccajmbfnmadgmpkfdf/related?hl=ru) extesion.

* **Current behavior**: 

It doesn't react on voice

[//]: # (Substitute this line with a description of the problem)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/35185109-7f0b0fc2-fe07-11e7-88a2-00036377c284.png)

</details><br/>

* **Expected behaviour**: 

See the screenshot

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/35185144-22dfe618-fe08-11e7-9c87-c4bf0553f6be.png)

</details><br/>

***Steps to reproduce the problem***:

1. Install the extension
2. Go to vk.com
3. Try to use the extension.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:** English, Rusian, Social media, Spyware, Annoyances, Russian, Safari

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | macOS High Sierra
Browser:                               | Chrome
AdGuard version:                       | 1.5.3
AdGuard DNS:                           | None 
Helpdesk ID (if exists):               | 1733444

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by zebrum** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #2111](https://github.com/AdguardTeam/AdguardForWindows/issues/2111) via [**ZenHub**](https://www.zenhub.com/)
