### ISSUE TITLE
AdGuard DNS not blocking ads in Yanosik app

### ISSUE THREAD

**Issue by InteRadek** [AdguardTeam/AdguardFilters#101491]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

dns.adguard.com

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=pl.neptis.yanosik.mobi.android

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

1. For the last few years I was using AdAway to block ads on my rooted smartphones. Now I'm switching to use AdGuard DNS solution. Although your DNS is very good at blocking ads in Android apps, it is not blocking ads in Yanosik app. Yanosik is a GPS navigation mobile app with functionality to report radars, police checks, road accidents etc. It is similar to Waze and is used mainly by Poles.
I identified that ads are downloaded from mobi.yanosik.pl domain. After blocking this domain manually, all application's functionality is working perfectly fine, but ads are not showing any more. I'm using the app several times a week. The domain is also present in Steven Black ads blocking hosts file: https://github.com/StevenBlack/hosts/blob/master/hosts . Can you please add mobi.yanosik.pl to your DNS list?

2. Screenshots
<details><summary>Yanosik reporting screen (with ads):</summary>

![Yanosik_reporting_with_ads](https://user-images.githubusercontent.com/12056416/143780429-a29c367a-de64-4a77-8783-9e5aa9422d4f.png)

</details>

<details><summary>Yanosik reporting screen (ads blocked)::</summary>

![Yanosik_reporting_ads_blocked](https://user-images.githubusercontent.com/12056416/143780491-50028cf8-2d46-4a55-9ab4-2fb4c794608a.png)

</details>

<details><summary>Yanosik navigation screen (with ads):</summary>

![Yanosik_navi_with_ads](https://user-images.githubusercontent.com/12056416/143780525-b4e8e4fc-7cde-49f1-9b6d-8178adf21f06.png)

</details>

<details><summary>Yanosik navigation screen (ads blocked):</summary>

![Yanosik_navi_ads_blocked](https://user-images.githubusercontent.com/12056416/143780574-34fec0e5-3e8f-4ca2-af98-461b63c06542.png)

</details>

<details><summary>AdAway DNS domains used by Yanosik (mobi.yanosik.pl domains is blocked):</summary>

![AdAway_DNS_list_Yanosik](https://user-images.githubusercontent.com/12056416/143780693-f45ed18d-9654-4158-8f28-45de9038b7b4.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
Try this:

https://github.com/StevenBlack/hosts/issues/1799

**Comment by AdamWr** [comment]
Hello,
As far as I can see, a rule to block `mobi.yanosik.pl` has been added 7 days ago - https://github.com/AdguardTeam/AdguardFilters/commit/8a968245ffc9dd22e814a8ae9da00e259bde35df#diff-090f08571a235e0ea9c59551bc8f9f885d554e75a071c84d4cc91b22c2604974
This rule is also in the AdGuard DNS filter https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt, so it should be already blocked by AdGuard DNS.
Could you please check it again?

**Comment by InteRadek** [comment]
I opened a support ticket for this issue a month ago (# 550220). Recently they asked me to create a ticket here as well.
I cleared the cache of the Yanosik application and now the ads are no longer showing, so ads blocking is working, but the rest of the functionality is working fine. Thank you.
