### ISSUE TITLE
zwei-euro.com anti adblock

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#101482]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.13

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.zwei-euro.com/uebersicht/

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, Filter unblocking search ads and self-promotion

### Add your comment and screenshots

1. Anti adb

2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="700" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/143700912-d642f740-5952-4cad-8727-31f4f6a38992.PNG">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
AdBlock detection paywall.
