### ISSUE TITLE
[Android] Sport1 app doesn't work

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#1015]
https://play.google.com/store/apps/details?id=sport1.mobile.android.apps&hl=de

The app does not load the content. It says there is a connection error.

We were not able to reproduce, here are HTTP request logs: KYC-763-90804

**Comment by Alex-302** [comment]
You should test with customer's filters, and filtering mode(VPN/Proxy, and DNS filtering on/off).
Added to German filter:
```
@@||ad.71i.de/global_js/AppConfig/Sport1de/android.json
```
I'm waiting for user's reply.

**Comment by vbagirov** [comment]
No proxy mode, no DNS filtering. Problem above is gone, but now app recognizes the adblocker and tells me to switch it off. Otherwise it won't start the app:
http://screencast.com/t/EkjpsGM2U8T

possible to do anything?

**Comment by Alex-302** [comment]
It works correctly on my device with user's filters.

**Comment by evgeniy-ADG** [comment]
>The Sport1.fm app doesn't start properly. It tells me with a landing
page to switch my adblocker off. I cannot use the app until I do so.

Log here: 1105236
Radio doesn't start if Adguard is enabled.

<details>
"enabledFilterIds" : [ 2, 3, 4, 6, 11 ], SPEEDY, SSL is on

**Comment by Alex-302** [comment]
@evgeniy-ADG это тот же юзер что и выше?

**Comment by Alex-302** [comment]
И спроси, зависит ли от фильтров(как без них), и от фильтрации HTTPS.
