### ISSUE TITLE
Adguard cannot block m-indicator Android app ads

### ISSUE THREAD

**Issue by pushkargogte** [AdguardTeam/AdguardFilters#101531]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.4

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

m-indicator

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track header

### Add your comment and screenshots

Adguard VPN cannot block m-indicator Android app ads but Blokada 5 VPN does block it.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
What is not blocked?

**Comment by pushkargogte** [comment]
![Screenshot_2021-12-08-05-35-53-87_aeb0ebc324083679b8394bd89c3a8fe3](https://user-images.githubusercontent.com/16486468/145125143-e4761f95-abdf-48b0-885f-8113ce427d8e.jpg)

This adscreen at exit is shown while exiting the app using Adguard but while using Blockada the app will exit without showing the ads screen

**Comment by Alex-302** [comment]
I don't see this window when exit.
This app? https://play.google.com/store/apps/details?id=com.mobond.mindicator
Please secord a video.

**Comment by pushkargogte** [comment]
The ads are blocked by Blokada. Yes the app you mentioned.

I'm sending you the video on telegram

**Comment by pushkargogte** [comment]
Alex check your telegram message

**Comment by Alex-302** [comment]
Also please clear cache before cheking. They do not show popup everytime even without ad blocker.

**Comment by pushkargogte** [comment]
Please check the latest video, the issue Exists on my phone even with your instructions.

**Comment by Alex-302** [comment]
I don't know why. We block the same domains.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #4057](https://github.com/AdguardTeam/AdguardForAndroid/issues/4057) via [**ZenHub**](https://www.zenhub.com/)

**Comment by pushkargogte** [comment]
Actually adguard app says that it's https certificate is not accepted by the m-indicator app

-----
Regards,
Pushkar Gogte
________________________________

**Comment by Alex-302** [comment]
Do not enable HTTPS filtering for this app. As I see, Blokada does not use HTTPS filtering, and blocks domains.

**Comment by Alex-302** [comment]
Fixed.
