### ISSUE TITLE
tc.tradetracker.net

### ISSUE THREAD

**Issue by notDavid** [AdguardTeam/AdguardFilters#101540]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Please consider adding `tc.tradetracker.net` to the “Tracking protection filter’, seems to be used for shopping analytics:

```
$ curl -sLI 'https://www.vergelijkmondkapjes.nl/go/hulpmiddelenwereld/' | grep -i Location
location: https://tc.tradetracker.net/?c=7459&m=12&a=379268&u=%2Fmedische-hulpmiddelen%2Fmondkapjes%2Fmedische-mondkapjes
location: https://www.hulpmiddelwereld.nl/medische-hulpmiddelen/mondkapjes/medische-mondkapjes?utm_source=tradetracker&affiliate=379268
```

### Proposed solution

```
||tc.tradetracker.net^
```

### Additional information

Found on: `https://www.vergelijkmondkapjes.nl/go/hulpmiddelenwereld/`

**Comment by Alex-302** [comment]
Cannot reproduce. Also it seems this and similar domains are not working
![image](https://user-images.githubusercontent.com/8361299/145052914-376fd125-4331-4595-a1e8-e0dc1761ec3b.png)

**Comment by notDavid** [comment]
@Alex-302 Thanks, did you test with only the AdGuard `Tracking protection filter` ?

If yes, then i will test again. Perhaps the domain was added…

**Comment by Alex-302** [comment]
Hm. Checked again, added.
