### ISSUE TITLE
Echobox not removed

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardFilters#101669]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0.67 nightly

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

clicking a link to open on browser (chrome)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, Spyware, EasyPrivacy, Annoyances, Greek AdBlock Filter, Fanboy's Annoyances, Warning Removal, I don't care about cookies, Prebake, Anti-Adblock Killer, ClearURLs for uBo

### Add your comment and screenshots

although there's the line $removeparam=Echobox in the fiter (https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt),
for example in the link: https://www.news247.gr/koinonia/thessaloniki-dolofonise-ti-gynaika-toy-kai-pige-sto-tmima-gia-na-paradothei.9442242.html#Echobox=1638139876 echobox wasn't removed, maybe because of the hashtag? 

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Hello,
`location.hash` cannot be removed by `$removeparam` modifier.
Probably in the future, the scriptlet to remove a `location.hash` will be added - https://github.com/AdguardTeam/Scriptlets/issues/135
