### ISSUE TITLE
LINE (Android)

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#101664]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

Nightly v4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=jp.naver.line.android

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

||uts-front.line-apps.com^
||nelo2-col.linecorp.com^

<details><summary>Screenshot :</summary>

![Screenshot_20211130-191136408](https://user-images.githubusercontent.com/87330832/144028488-6f8dcf88-b11c-483e-b8a3-cc28cd8fe375.jpg)

</details>

<details><summary>Screenshot :</summary>

![Screenshot_20211130-191520341](https://user-images.githubusercontent.com/87330832/144028544-3b030116-6151-4d2d-a89d-4e3b0809694a.jpg)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@SASUKE0721 Hi. Did you check this app when domains are blocked?

**Comment by SASUKE0721** [comment]
I have been using the line by blocking these two domains for about 5 months, but no bugs have occurred.

**Comment by Alex-302** [comment]
Ok.
