### ISSUE TITLE
Grammarly tracking  (Chrome Adon)

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#101653]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

Nightly v4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen/related

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

||f-log-editor.grammarly.io^

||gnar-grammarly-com^

gnar-grammarly-com is a tracker.
sauce
https://confection.io/trackers/gnar-grammarly-com/

<details><summary>Screenshot :</summary>

![キャプチャ](https://user-images.githubusercontent.com/87330832/143993355-224e9268-e17f-43f3-a5a2-7b19d42e4d12.PNG)
>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by SASUKE0721** [comment]
I'm sorry, I quoted from the domain part of "confection.io", so there is a mistake in the domain.
||gnar-grammarly-com^   ❌
||gnar.grammarly.com^    ⭕

**Comment by Alex-302** [comment]
Ok.
