### ISSUE TITLE
15min.lt

### ISSUE THREAD

**Issue by iibett** [AdguardTeam/AdguardFilters#101752]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

3.6.16

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

15min.lt

### What filters do you have enabled?

AdGuard Tracking Protection filter

### Add your comment and screenshots

Remove

```
@@||google-analytics.com/gtm/js?id=$domain=15min.lt
@@||google-analytics.com/analytics.js$domain=15min.lt
```

They were added because of this https://github.com/AdguardTeam/AdguardFilters/issues/48215 issue but i did some testing and as far as i know this whitelisting is unnecessary because it doesn't cause any problems.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Done.
