### ISSUE TITLE
ニュースダイジェスト (Android)

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#101903]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

Nightly v4.0

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=jp.newsdigest

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

||api.ads.newsdigest.jp^

<details><summary>Screenshot N:</summary>

![Screenshot_20211203-123844448](https://user-images.githubusercontent.com/87330832/144541213-001f4467-c667-4c72-bfa3-aca05f48b04b.jpg)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please show screenshots of ads in your reports. Log is not so interesting.

**Comment by SASUKE0721** [comment]
<details><summary>Screenshot N:</summary>

![Screenshot_20211209-233807098](https://user-images.githubusercontent.com/87330832/145416757-d8b3d95a-1490-4b46-ae32-f338feee87ac.jpg)


</details>

<details><summary>Screenshot N:</summary>

![Screenshot_20211209-233821924](https://user-images.githubusercontent.com/87330832/145416785-3ba9b9d5-e3e5-46db-abd1-e2a75da0228f.jpg)

</details>

<details><summary>Screenshot N:</summary>

![Screenshot_20211209-233847976](https://user-images.githubusercontent.com/87330832/145416835-6c9c2715-f20f-4114-af3d-d54209f780ad.jpg)


</details>

<details><summary>Screenshot N:</summary>

![Screenshot_20211209-233853805](https://user-images.githubusercontent.com/87330832/145416860-9ed19a85-aba8-4f07-88db-57ca5908ed76.jpg)


</details>
