### ISSUE TITLE
Googleplay store beacon domain

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#101907]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

Nightly v4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.apkmirror.com/apk/google-inc/google-play-store/

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

||beacons4.gvt2.com^

<details><summary>Screenshot :</summary>

![Screenshot_20211203-162426678](https://user-images.githubusercontent.com/87330832/144562456-bf6888ce-ddec-473b-826a-6016b2f9097b.jpg)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Is not it blocked by `||gvt2.com^` from Base/Easylist filter?

**Comment by SASUKE0721** [comment]
It seems that my terminal was causing a bug. 
 It was blocked.
