### ISSUE TITLE
mediafire.com [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#101975]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.39.2

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

http://www.mediafire.com/file/gvue57mgphlc2em/Titanic_20th_Ann._Scans.rar/file

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Social Blocking List, Peter Lowe's Blocklist, Online Malicious URL Blocklist, Spam404

### Add your comment and screenshots

1. Please check the pop-up seen when clicking on the 'Download' button

http://www.mediafire.com/file/gvue57mgphlc2em/Titanic_20th_Ann._Scans.rar/file

2. Screenshots: https://prnt.sc/21occq6

Using uBlock Origin on Edge with the above filters.

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Not reproduced. If you can still reproduce, please try this rule:
`mediafire.com#%#//scriptlet('remove-class', 'popsok', 'a#downloadButton')`
