### ISSUE TITLE
Microsoft Solitaire Collection

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#10205]
***Description***:
* **MS Store Page**:
https://www.microsoft.com/en-us/store/p/microsoft-solitaire-collection/9wzdncrfhwd2

* **Current behaviour**: 

When WFP driver is enabled, the app will either fail to open or report a "Cannot connect to the cloud" error. 

* **Expected behaviour**: 

Should work fine.

***Steps to reproduce the problem***:

1. Open the app with WFP driver enabled.
2. The app will either fail to load with a black screen or show a "Cannot connect to cloud" error.

***Debug log***
~3:19pm
[debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/1649773/debug.txt)

***System configuration***

**Filters:**
English, Russian, Social media, Spyware

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 Fall Creators Update (Ver 1709 Build 16299)
Browser:                               | App Issue - Not Applicable
AdGuard version:                       | 6.2.437.2171
Filters enabled:                       | English, Russian, Social media, Spyware
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Block 3rd-party cookies (30), Block Browser Location API, Remove X-Client-Data Header, Send DNT Header, Remove Referrer from 3rd-Party Requests, Hide User Agent, Hide IP (209.141.53.254), Block 3rd-Party Authorization
Helpdesk ID (if exists):               | 1197207 (original), 1680890 (repro)

**Comment by Alex-302** [comment]
@AdamWr do you have Win10?

**Comment by AdamWr** [comment]
Yes, I have.

**Comment by Alex-302** [comment]
@AdamWr thanks.
@akmLaVx please try to disable all filters and stealth mode

**Comment by akmLaVx** [comment]
@Alex-302 Will do.

**Comment by Alex-302** [comment]
@akmLaVx any news?
