### ISSUE TITLE
news.itsfoss.com

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#102196]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.4

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://news.itsfoss.com/cutefishos-intro/

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

1. <comment> There are ads lefotovers (white spaces) in most post i opened in the site

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot_20211207-020838_Chrome](https://user-images.githubusercontent.com/46019727/144915023-aa4fd717-4d8c-43cd-ade5-383b0bddd3bb.jpg)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
I propose `itsfoss.com##.entry-content > aside`
