### ISSUE TITLE
aphim.co [Anti-Adblock Script]

### ISSUE THREAD

**Issue by LaxusiC** [AdguardTeam/AdguardFilters#10221]
Popup appear when you pressed play button

Screenshot:

![screenshot_1](https://user-images.githubusercontent.com/9650215/35195065-6d28415a-fef0-11e7-9eb2-d17fcbc32c3e.png)

Filters used: ABPVN, Annoyances, English, Peter Lowe's, Malware Domain

**Comment by BlazDT** [comment]
Not reproduced, please check @AdamWr.

**Comment by AdamWr** [comment]
Fixed.
