### ISSUE TITLE
New nsfw filter from my privacy dns

### ISSUE THREAD

**Issue by spirillen** [AdguardTeam/AdguardFilters#102222]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

As we are hunting for adware/spyware etc, then one of the "places" we are using are NSFW sites, as a bi product we build and maintain the [Porn Records project](https://mypdns.org/my-privacy-dns/porn-records) (The master)

### Proposed solution

We have today setup the script to also generate 2 lists for ad-blockers

1. Ordinary Adult mainstream sites
2. A very strict one for which users should be prepared to maintain there own whitelist as there are no mercy, if the domain hosts a significant amount of porn, well it is on this list.
    As example to this is `*.bp.blogspot.com` the fact is, this is among the biggest porn CDN's

### Additional information

To build and host the active only records we have fully integrated the well known `clefspeare13/pornhosts` with our previously mentioned Porn Records, as announce a long time ago, but the process have been speeded up do to Github's take down of https://github.com/clefspeare13/pornhosts

The lists we hope is fulfilling the requirement to be useful within AdGuardHome should be located at:

- https://mypdns.org/clefspeare13/pornhosts/-/blob/master/download_here/ad_blockers/ad_blockers.filter
- https://mypdns.org/clefspeare13/pornhosts/-/blob/master/download_here/strict/ad_blockers/ad_blockers.strict

**Tip**: for downloading these files you replace `/blob/` in the urls with `/raw/`

I'm looking forward some useful replies if the lists actually is useful to you, they are lacking some, improvements.

--------------------
PM: @Yuki2718 this is a part of what My Privacy DNS is about

**Comment by Yuki2718** [comment]
If I understand correctly, it should probably be moved to FiltersRegistry.

**Comment by spirillen** [comment]
Seems right @Yuki2718 :+1:

**Comment by spirillen** [comment]
Issue moved to https://github.com/AdguardTeam/FiltersRegistry/issues/554
