### ISSUE TITLE
z.pornsexer.porn

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#102299]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.0.64

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://z.pornsexer.porn/videos/49090/busty-teacher-knows-that-blowjob-and-fucking-could-motivate-her-students-to-study-way-better/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

[screenshot](https://i.imgur.com/kEf9FQG.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by neer9** [comment]
Why closed?

**Comment by Alex-302** [comment]
Because 1500 opened issues, and more than 500 issues are useless.

**Comment by neer9** [comment]
But this is useful.

**Comment by Alex-302** [comment]
No.
