### ISSUE TITLE
imap.mail.ru

### ISSUE THREAD

**Issue by LordMerlin** [AdguardTeam/AdguardFilters#102260]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

AdGuardHome Version:  v0.106.3

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome, Microsoft Edge, Opera, Yandex Browser

### Which device do you use?

Desktop

### Where is the problem encountered?

imap.mail.ru

### What filters do you have enabled?

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment>
Перестала приходить почта, сделал nslookup на сервер AdGuard Home, возвращает 0.0.0.0

2. Screenshots
<details><summary>Screenshot 1:</summary>

![snap_screen_20211207150852](https://user-images.githubusercontent.com/2853937/145026538-d054a62d-03f7-4573-b0a5-c1efa717523a.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
По cname блокировался.
