### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by hyder365** [AdguardTeam/AdguardFilters#102308]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

0.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

tinder.com

### What filters do you have enabled?

AdGuard Mobile Ads filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track header

### Add your comment and screenshots

1. <comment>

The desktop version of tinder.com does not fully load (once logged in) with the domain "etl.tindersparks.com" blocked.

https://github.com/AdguardTeam/AdguardFilters/blob/4a34be51937ecd45ff4724348c2e569970446454/MobileFilter/sections/specific_app.txt#L756-L757

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by r-a-y** [comment]
You mention that you're using this on desktop. Can you check to see if the mobile version of Tinder works?

That ad filter is for their mobile list. You probably shouldn't be using their mobile list on desktop.

**Comment by hyder365** [comment]
I don't have access to the mobile version right now to test. I've been using this list for many months and that domain was just (re?)added in the last few days. I made an issue upstream as you suggested, thanks.

**Comment by hyder365** [comment]
Git blame shows that line was added a long time ago, so I think the real issue may be elsewhere. I'll open a new bug report if I can figure it out. =
