### ISSUE TITLE
zentrum-der-gesundheit.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#102303]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.13

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.zentrum-der-gesundheit.de/rezepte/suppen/cremesuppen/lauchsuppe

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, Filter unblocking search ads and self-promotion

### Add your comment and screenshots

Newsletter overlay after ~ 30 Seconds

<details><summary>Screenshot 1:</summary>

<img width="607" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/145074646-b0ae3771-96e0-4636-8583-f13811aae561.PNG">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by JobcenterTycoon** [comment]
@Alex-302 ads are back

**Comment by Alex-302** [comment]
ok

**Comment by JobcenterTycoon** [comment]
@Alex-302 ads are not fully blocked like on this article `https://www.zentrum-der-gesundheit.de/rezepte/suppen/cremesuppen/lauchsuppe` (scroll a bit down to see)

**Comment by Alex-302** [comment]
fixed
