### ISSUE TITLE
Google Now - ads in articles

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#10244]
### Description:

AdGuard doesn't block ads in articles if you view them in Google Now

 <details> <summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/15856304/35210277-3caabb92-ff5a-11e7-976c-e148f1086429.png)

</details>

### STR: 

open an article like it's explained here https://www.tomsguide.com/us/google-feed-faq,news-25496.html

### User ID: **1414154**
We have a HAR log if you need it

### Environment

- OS: Android 8.1.0
- AdGuard: 2.10.176
- HTTPS: On, Whitelist, User
- Subscriptions: "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Mobile Ads filter"
- DNS: Off
- Filtering: local VPN, HQ
- User filter: "@@||tpc.googlesyndication.com\n@@||app-measurement.com$app=com.google.android.gms"
-

**Comment by Alex-302** [comment]
Can't reproduce. Also I can't find this banner in HAR.
@AdamWr please check on your device.

**Comment by AdamWr** [comment]
I can't reproduce it.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
this rule in user filter it wide
`@@||tpc.googlesyndication.com`
User can try to disable it.
