### ISSUE TITLE
Apps blocked incorrectly

### ISSUE THREAD

**Issue by Lurchus** [AdguardTeam/AdguardFilters#102544]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0 nightly 27 (68)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

Multiple applications

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, Online Malicious URL Blocklist, NoCoin Filter List

### Add your comment and screenshots

I have multiple apps that are being incorrectly blocked by adguard.

Apps such as: Hive, Investing.com, MyVodafone (the veryme rewards part of the app), Twitter (images and videos are being blocked from tweets), Instagram (images are not loading) to name a few.

if I disable adguard these apps start working.

Hive controls my heating, when I go in to the app, more often than not, it is not able to refresh to the updated view of my heating controls, with the app constantly showing ‘updating’.

investing.com app hangs on the splash screen or fails to refresh the market data or the custom watchlist I have created.

On the MyVodafone app there’s a veryme rewards tab, when clicked on an error message appears saying ‘Sorry, there’s been an error while loading page, please try again’.

For Twitter and Instagram, both work for a little while and then suddenly it stops loading images or videos, either like it’s constantly buffering or a black square appears where an image/video should be.

For all of the above, if I disable adguard and go in to the above apps, they suddenly start working again and I have to leave switched off whilst I use these apps, however it then means none of the ads are being blocked,

I am using Adguard for Android on a Samsung Galaxy S9 Plus and I regularly refresh my filters and update the app when a new release becomes available.I do not have https filtering on any of the apps.

The problem seems to be getting worse compared to previously, but I’ve been unable to find a fix besides disabling adguard.

Are there any settings i can try?

Let me know if any further information is needed.

Thanks,

L

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. Sorry for the late reply.
Please try to reset settings. Maybe you enabled HTTPS filtering in Apps Management for these apps(they cannot be filtered as browser and do not trust to foreing HTTPS certificate).
