### ISSUE TITLE
porndoe.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#102678]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.0.64

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://porndoe.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

[screenshot](https://i.imgur.com/ggAfT5g.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by Yuki2718** [comment]
What's in the SS is out-of-scope, but there's popunder

**Comment by neer9** [comment]
Can you please tell me user filter?

**Comment by Yuki2718** [comment]
Maybe tomorrwo, late night here.

**Comment by Yuki2718** [comment]
> Can you please tell me user filter?

porndoe.com#$#.age-blur-popup { display: none!important; }
porndoe.com#$#body { overflow: auto!important; }

I *personally* hope you fully understand answering these takes our time and thus asked only for those which you really need. There' other ones waiting our fix.
