### ISSUE TITLE
I still can see ads on techpowerup.com

### ISSUE THREAD

**Issue by PCUser2021** [AdguardTeam/AdguardFilters#102642]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

AdGuard AdBlocker 3.6.16

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.techpowerup.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard French filter, AdGuard Russian filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdGuard Experimental filter, EasyList, EasyList China, EasyList Hebrew, EasyList Italy, Liste AR, Liste FR, ROList, Greek AdBlock Filter, Fanboy's Annoyances, Web Annoyances Ultralist, Peter Lowe's Blocklist, Adblock Warning Removal List, Online Malicious URL Blocklist, Spam404, RU AdList - Counters, ChinaList+EasyList, CJX's Annoyances List, Adblock-Persian list, xinggsf, KAD - Anti-Scam, Iranian filter, road-block, NoCoin Filter List, Dandelion Sprout's Annoyances List

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by PCUser2021** [comment]
Now the fix you did on TPU broke the site completely!

**Comment by Alex-302** [comment]
They change ads immediately after our fixes.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardExtra #282](https://github.com/AdguardTeam/AdGuardExtra/issues/282) via [**ZenHub**](https://www.zenhub.com/)
