### ISSUE TITLE
yts.me

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#10272]
***Description***:
* **Current behaviour**: 

Has a cryptocurrency miner that is not detectable with AdGuard.

* **Expected behaviour**: 

Should be detected by AdGuard.

***Steps to reproduce the problem***:

Just visit the site.

***System configuration***

Not Applicable

**Comment by Alex-302** [comment]
I can't reproduce. Please upload HAR
https://toolbox.googleapps.com/apps/har_analyzer/?lang=en
