### ISSUE TITLE
Ms edge android

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#102719]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.4

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

Microsoft Edge

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

1. <comment> can't login to Microsoft account for sync

2. Screenshots

![Screenshot_20211211-030909_Edge](https://user-images.githubusercontent.com/46019727/145641653-5c2c4302-c198-4c41-abad-718ba3806157.jpg)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Probably a temporary issue.
