### ISSUE TITLE
Naver Whale (Android)

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#102762]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

App
https://play.google.com/store/apps/details?id=com.naver.whale

Naver Whale will not block ads unless you turn on https filtering.

### Proposed solution

Turn on Naver Whale's https filtering from the beginning.

### Additional information

</details>

<details><summary>Screenshot :</summary>

![Screenshot_20211209-220518934](https://user-images.githubusercontent.com/87330832/145670825-baae3a5f-0553-4077-bf6a-5b21fcfeca9f.jpg)

</details>

**Comment by piquark6046** [comment]
@zloyden Cloud you please transfer it?

**Comment by zloyden** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #4058](https://github.com/AdguardTeam/AdguardForAndroid/issues/4058) via [**ZenHub**](https://www.zenhub.com/)
