### ISSUE TITLE
网易云音乐 (Android)

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#102788]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

Nightly v4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://music.163.com/m/download

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

||clientlog*.music.163.com^

<details><summary>Screenshot N:</summary>

![Screenshot_20211211-214603539](https://user-images.githubusercontent.com/87330832/145677012-97c43029-c82f-4065-9ca9-5c630eed3aab.jpg)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I'm not sure that this is a tracker.
According to this https://github.com/nondanee/UnblockNeteaseMusic/issues/263#issuecomment-538674517 and if I understand correctly, it's better not to block this.
