### ISSUE TITLE
qiita.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#102791]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

Version 3.6.16

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://qiita.com/plumfield56/items/ac4c0b289b5fe36e3b37

### What filters do you have enabled?

AdGuard Base filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

[screenshot](https://i.imgur.com/Cj2ZHqA.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by Yuki2718** [comment]
Enable Japanese filters

**Comment by chirag127** [comment]
Why added invalid?

**Comment by Yuki2718** [comment]
> Why added invalid?

Cannot reproduce is also fine, but Japnese site issues are assumed to happen with JPF enabled.

**Comment by chirag127** [comment]
> > Why added invalid?
> 
> Cannot reproduce is also fine, but Japnese site issues are assumed to happen with JPF enabled.

Well I can reproduce with my configuration.
