### ISSUE TITLE
SimplyElizabethOlsen.com - Embedded YouTube videos blocked (AdGuard Base filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#102809]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.16.4.30 (XUL)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other(specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://simplyelizabetholsen.com/

### What filters do you have enabled?

AdGuard Base filter

### Affected site:
`https://simplyelizabetholsen.com/`

### Issue:
Embedded YouTube videos blocked.

### Screenshot:
![filterissue-simplyelizabetholsen](https://user-images.githubusercontent.com/9382674/145680020-7fa084bc-fbe8-43d1-8946-39dfb7e9d710.jpg)

### Problem filter:
* **AdGuard Base filter**

### Problem rule:
`##iframe[width="300"][height="250"]`

### Possible fix:
```
- foxsports.com.au,wakeboardingmag.com,cbssports.com,thoughtcatalog.com,webmd.com,gamespot.com,windowscentral.com,tvguide.com,sfgate.com,afterellen.com,boston.com,calgarysun.com,cattime.com,celebuzz.com,chowhound.com,cnet.com,comingsoon.net,computershopper.com,ctnow.com,cycleworld.com,edmunds.com,everydayhealth.com,metacritic.com,msn.com,popphoto.com,popsci.com,ranker.com,saveur.com,sportingnews.com,tv.com,washingtonpost.com#@#iframe[width="300"][height="250"]

+ foxsports.com.au,wakeboardingmag.com,cbssports.com,thoughtcatalog.com,webmd.com,gamespot.com,windowscentral.com,tvguide.com,sfgate.com,afterellen.com,boston.com,calgarysun.com,cattime.com,celebuzz.com,chowhound.com,cnet.com,comingsoon.net,computershopper.com,ctnow.com,cycleworld.com,edmunds.com,everydayhealth.com,metacritic.com,msn.com,popphoto.com,popsci.com,ranker.com,saveur.com,sportingnews.com,tv.com,washingtonpost.com,simplyelizabetholsen.com#@#iframe[width="300"][height="250"]
```

### Temporary fix:
`simplyelizabetholsen.com#@#iframe[width="300"][height="250"]`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.4.2.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
Fanboy social blocking list can add:

```
simplyelizabetholsen.com##div.side.widget_text:nth-of-type(8)
simplyelizabetholsen.com##div.side.widget_text:nth-of-type(6)
```

EasyList can add:

`simplyelizabetholsen.com##div.side.widget_text:nth-of-type(1)`

fyi @khrin / @ryanbr  / @montza

**Comment by THEtomaso** [comment]
> EasyList can add:
> 
> `simplyelizabetholsen.com##div.side.widget_text:nth-of-type(1)`

That's not a particularly good idea.
All fansites have those ad widgets in their sidebar (thousands of sites), at totally different css paths.
They're not always at the top though, so `:nth-of-type(1)` might very well break something, after the next site update.
At the moment, this seems like a better choice (for AdGuard / uBO):
`simplyelizabetholsen.com###sidebar > div.widget_text.side:has-text(Ads)`
..but like I pointed out, it would be pretty pointless, regardlessly.
