### ISSUE TITLE
www.amateurest.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#103068]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.0.64

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.amateurest.com/videos/8307/would-you-like-to-cum-all-over-my-nylon-pantyhose/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

[screenshot](https://i.imgur.com/VsPt3nF.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by neer9** [comment]
Why closed? Don't close my issues just because there are 1900 issue open.

**Comment by Alex-302** [comment]
You posting just tons of porn farms. No one with ad blockers visit them.

**Comment by neer9** [comment]
Will you reopen the issues of the sites witch have more than 30000 visitors
per month if I do the work of checking the same?

**Comment by Alex-302** [comment]
No. In any case they and many others will not be processed. No one visit them and no need to add useless rules to filters. Same with hundreds of Chirag's reports. But these porn sites are extra-low-level priority.
