### ISSUE TITLE
www.melonstube.com

### ISSUE THREAD

**Issue by neer9** [AdguardTeam/AdguardFilters#103043]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.0.64

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.melonstube.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

[screenshot](https://i.imgur.com/MigNnLp.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by iam-py-test** [comment]
Age confirmation prompts exist for a reason - to prevent children from accidentally going to one of those sites - and therefore are out of scope of a normal annoyances list. You will have to find a specialized list for that purpose

**Comment by chirag127** [comment]
Can you please tell me user filter?

**Comment by neer9** [comment]
Can you please tell me user filter?

**Comment by iam-py-test** [comment]
> Can you please tell me user filter?

No idea if you are talking to me or @AdamWr
I have no idea what the needed filters are and can't investigate NSFW websites
Try using DevTools to find the element and then create a comedic filter (website.com##[selector]):
![image](https://user-images.githubusercontent.com/84232764/146051910-1c65790f-f0c2-4da4-be10-7991e0859607.png)

**Comment by neer9** [comment]
> > Can you please tell me user filter?
> 
> No idea if you are talking to me or @AdamWr I have no idea what the needed filters are and can't investigate NSFW websites Try using DevTools to find the element and then create a comedic filter (website.com##[selector]): ![image](https://user-images.githubusercontent.com/84232764/146051910-1c65790f-f0c2-4da4-be10-7991e0859607.png)

Well, anyone can tell me the filters and I will be very grateful to him.

**Comment by iam-py-test** [comment]
> Well, anyone can tell me the filters and I will be very grateful to him. And I will also try to make them by myself.

Based on little research, scriptlets may be needed as removing the prompt means all the pictures remain blurred. 
This is probably one instance where the time/effort isn't worth the result - it is only 1 click to accept

**Comment by neer9** [comment]
> > Well, anyone can tell me the filters and I will be very grateful to him. And I will also try to make them by myself.
> 
> Based on little research, scriptlets may be needed as removing the prompt means all the pictures remain blurred. This is probably one instance where the time/effort isn't worth the result - it is only 1 click to accept

Well I managed to remove the blur found that the page is not scrolling. 

Actually, I use the site in incognito, that's makes it quite annoying for me to do it every time I open the site.

**Comment by iam-py-test** [comment]
> https://github.com/chirag127/adblock/commit/5d68054947f149a4d655623997f73f1ce4c5e656

Well, looks like you found a fix
