### ISSUE TITLE
https://thuvienphapluat.vn/ - Firefox extension - False positive - 'Login with Google' button blocked

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdguardFilters#10304]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Firefox browser extension - 'Login with Google' button in the login box near the top right of the page is blocked. 'Login with Facebook' appears correctly.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22385284/35253977-d2af68ca-001a-11e8-8bb6-fee420130dc8.png)

* **Expected behaviour**: 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22385284/35253857-1ac2d0c6-001a-11e8-95d5-369759baeb49.png)

</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  Windows 10
Operating system version (Android/iOS) | ?
Browser:                               | Firefox
AdGuard version:                       | 2.8.5
Filters enabled:                       | English, Spyware, Social, Annoyance, ABPVN
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't reproduce.
@AdamWr please check on your end.

**Comment by AdamWr** [comment]
Fixed.
