### ISSUE TITLE
zdf.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#103325]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.13

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.zdf.de/

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, Filter unblocking search ads and self-promotion

### Add your comment and screenshots

The site shows a error because the cookie banner is blocked. This error can be blocked too without breakage

<details><summary>Screenshot 1:</summary>

<img width="432" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/146260275-50eccbbb-2a90-42aa-8734-32e6cf3afef8.PNG">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reproduced. It is auto-clicked by JS rule.

**Comment by JobcenterTycoon** [comment]
can confirm its fixed
