### ISSUE TITLE
t3n.de breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#103460]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.13

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://t3n.de

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, Filter unblocking search ads and self-promotion

### Add your comment and screenshots

Cookie banner can’t be accepted but its needed to see the site

<details><summary>Screenshot 1:</summary>

<img width="407" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/146432309-8084d5fe-7643-4faa-a95b-d93d91aabfd0.PNG">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Morku** [comment]
@AdamWr 
Can you please fix the Adplaceholder, too? Thank you.
https://t3n.de/news/schrems-nyob-facebook-fuehrt-daten-in-usa-ab-dsgvo-1439211/

<details><summary>Screenshot-1:</summary>

![t3](https://user-images.githubusercontent.com/6276915/146842753-61183d7a-6e66-40ee-a999-f2f49028b311.png)


</details><br/>

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
