### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#103457]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.4

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://dropgalaxy.com/684g3ebsoga0

### What filters do you have enabled?

---AdGuard filters---

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

![Screenshot_20211217-004145_Chrome](https://user-images.githubusercontent.com/46019727/146429862-c2fa9340-d789-4c01-839e-9fb74f3fbf9c.jpg)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Bhooty** [comment]
Bump

**Comment by Alex-302** [comment]
I can download IPTV_Smarters_Pro_v3.1.5_Premium_Mod_Apk___sHash_.apk without issues.

**Comment by Bhooty** [comment]
![10810808-7136-4542-8E83-667253393C65](https://user-images.githubusercontent.com/46019727/153607094-ef6276a5-c04d-47b3-b3fa-fc0328d608db.png)
