### ISSUE TITLE
Tracking scripts

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#103510]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.13

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

stoic.ai monkeylearn.com atlaslane.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, Filter unblocking search ads and self-promotion

### Add your comment and screenshots

On `stoic.ai/main` many requests coming from `anti-adblock.herokuapp.com` with tracking like google analytics. Also 1x1 tracking pixel coming from `https://www.google.ie/pagead/1p-user-list/*` with data in the URL like screen size, java on/off, IDs, ... Also Dataunlocker coming from `https://cdn.cindicator.com/1a228998-1343-44b8-ab52-8d1c79ff8582/` on `app.stoic.ai`

On `monkeylearn.com` the dataunlocker script coming from `https://d33wubrfki0l68.cloudfront.net/bundles/fea98b35863059fab67b20ccbd995188452b1214.js` (stable)

On `atlaslane.com` the dataunlocker script coming from `https://gistcdn.githack.com/trever/9c61486a3dde2f03d5af3b2ec1888fa7/raw/d8e99d03b350c51055dd02c5e42b2c271394bc15/gisty4.js`

On `unstoppabledomains.com` the dataunlocker script coming from `
https://unstoppabledomains.com/static/js/dataunlocker-prod.js`

on `tragonesymazmorras.com` the dataunlocker script coming from `https://www.tragonesymazmorras.com/prox_data_g.js`

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
> Dataunlocker coming from

What is wrong with it?

**Comment by JobcenterTycoon** [comment]
It import tracking
