### ISSUE TITLE
interia.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#10366]
**Site Sample** | 
------------------|
http://www.interia.pl

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.437.2171**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Adblock detect on player @AdamWr 

<details><summary><b>Screenshot:</b></summary>

![snipaste_2018-01-24_14-57-00](https://user-images.githubusercontent.com/9846948/35335931-3b8b8b42-0117-11e8-9cea-52244711aeae.png)
![snipaste_2018-01-24_14-57-20](https://user-images.githubusercontent.com/9846948/35335932-3bae5a3c-0117-11e8-9658-2d60afcb7b79.png)

</details><br/>

**Comment by AdamWr** [comment]
Naprawione w polskiej liście.
