### ISSUE TITLE
`googleads.github.io` ads

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#103793]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

n/a

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

n/a

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

http://cablenews.i-cable.com/ci/news/article/37/781903 --> https://googleads.github.io/videojs-ima/node_modules/videojs-contrib-ads/dist/videojs.ads.min.js

```
https://googleads.github.io/videojs-ima/node_modules/videojs-contrib-ads/dist/videojs.ads.min.js
https://googleads.github.io/videojs-ima/dist/videojs.ima.js
```

```
||googleads.github.io^
or
||googleads.github.io^$third-party
```

### Privacy

- [X] I agree to follow this condition

**Comment by Yuki2718** [comment]
Fixed by https://github.com/easylist/easylist/commit/187f6b990f8de42fd23ff6fd3831408a7e84eedc
