### ISSUE TITLE
Chinese `www.zhihu.com` tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#103755]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

n/a

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.zhihu.com/

### What filters do you have enabled?

AdGuard URL Tracking filter

### Add your comment and screenshots

https://www.zhihu.com/question/265309145/answer/294683314 --> `https://www.zhihu.com/search?q=%E5%9B%9B%E5%B0%8F%E9%BE%99&search_source=Entity&hybrid_search_source=Entity&hybrid_search_extra=%7B%22sourceType%22%3A%22answer%22%2C%22sourceId%22%3A296590860%7D`

```
||zhihu.com^$removeparam=search_source
||zhihu.com^$removeparam=hybrid_search_source
||zhihu.com^$removeparam=hybrid_search_extra
```

### Privacy

- [X] I agree to follow this condition

**Comment by iam-py-test** [comment]
Just by the way, `||zhihu.com^$removeparam=search_source` causes issues with search results. The other two don't seem to
