### ISSUE TITLE
com.innologica.inoreader

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#10387]
https://play.google.com/store/apps/details?id=com.innologica.inoreader

### Expected behavior
No ads

### Actual behavior
Ads

<details><summary>Screenshot:</summary>

![screenshot_2018-01-24-08-44-18](https://user-images.githubusercontent.com/33634917/35354686-81779a9c-0153-11e8-9283-67d54d4a6a0c.png)

</details>

### Customer ID 
1737902

### Your environment
* Adguard version: Unknown, presumably 2.10.176
* Adguard filtering mode: VPN, HQ method, HTTPS filtering on
* Device model: Unknown, no logs sent
* Operating system and version: Unknown, no logs sent
* Rooted or not?: Unknown
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: Unknown

**Comment by Alex-302** [comment]
Hi
Please describe where can we find ads.
Which Android version?

**Comment by TWOODEE** [comment]
Hello the ad was found in the Inoreader Android app.

AdGuard version 2.10.176
Device: LG Stylo 3
Android 7.0
Non rooted device
No other apps that can start VPN anti virus cleaners etc

**Comment by Alex-302** [comment]
I can't reproduce without AdGuard.
@AdamWr @BlazDT please check with/without https filtering

**Comment by TWOODEE** [comment]
HTTPS filtering was already enabled so I disabled it and still see the ad.
Here is a link to the website (the ad is located near the bottom of the
website). I've also included a screenshot of the ad.

**Comment by TWOODEE** [comment]
Here is a link to the website:
https://www.androidcentral.com/best-puzzle-games-android

**Comment by AdamWr** [comment]
Fixed ads on the website -https://github.com/AdguardTeam/AdguardFilters/commit/032132b6034e151bd74ecb7a42991037f3b0af7b but I'm not sure if we can hide these ads if you open article directly in app.
Update will be available in 2-3 hours.

**Comment by TWOODEE** [comment]
This is the only ad I've come across since purchasing your product so I'm
really impressed! Thank you for your help
