### ISSUE TITLE
[nsfw] www.spankwire.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#10428]
**Site Sample** | 
------------------|
https://www.spankwire.com/Caitlin-FitzGerald-Lizzy-Caplan-Betsy-Brandt-Masters-of-Sex-2014-s2e1/video16066592/

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.437.2171**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Player adleftover overlay

### Fix:
```
spankwire.com##.vjs-inplayer-overlay
```

<details><summary><b>Screenshot:</b></summary>

![snipaste_2018-01-25_12-42-11](https://user-images.githubusercontent.com/9846948/35386672-2fe9291e-01cd-11e8-953d-d76564dfca29.png)

</details><br/>

**Comment by AdamWr** [comment]
Added.
Thank you.
