### ISSUE TITLE
Chinese `bilibili` tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#104307]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

n/a

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.bilibili.com/video/BV1R34y1R7ps/

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

https://www.bilibili.com/video/BV1R34y1R7ps/ --> https://api.bilibili.com/x/player/online/total?aid=934529384&cid=454387327&bvid=BV12M4y1P7ML&ts=54676440

You can check the streaming viewer numbers for the same video at this URL:
`https://api.bilibili.com/x/player/online/total?aid=934529384&cid=454387327&bvid=BV12M4y1P7ML&ts=54676440`

`https://api.bilibili.com/x/player/online/total?aid={video's aid ID}&cid={video's cid ID}&bvid={video's bvid ID}&ts={what part of the video you are watching at the moment}`

It will automatically refresh every few seconds, and no `Cookie` is needed to get the content, so...~

```
||api.bilibili.com/x/player/online/total$removeparam=ts
||api.bilibili.com/x/player/online/total$cookie
```

### Privacy

- [X] I agree to follow this condition

**Comment by c2xusnpq6** [comment]
One more, https://www.bilibili.com/video/BV1R34y1R7ps/ --> https://upos-hz-mirrorakam.akamaized.net/upgcxcode/76/95/452019576/452019576-1-30080.m4s?hdnts=exp=1640301325~hmac=502507765248beb5fa12c923763fc9a1643307b6a6b24de274d8f6a8cffbe956&mid=1108298144&bvc=vod&orderid=0,1&agrr=0&bw=328804&logo=80000000

```
||akamaized.$removeparam=uparams
||akamaized.$removeparam=upsig
||akamaized.$removeparam=platform
||akamaized.$removeparam=trid
||akamaized.$removeparam=oi
||akamaized.$removeparam=os
||akamaized.$removeparam=gen
||akamaized.$removeparam=deadline
||akamaized.$removeparam=nbs
||akamaized.$removeparam=uipk
||akamaized.$removeparam=e

or

upgcxcode$removeparam=uparams
upgcxcode$removeparam=upsig
upgcxcode$removeparam=platform
upgcxcode$removeparam=trid
upgcxcode$removeparam=oi
upgcxcode$removeparam=os
upgcxcode$removeparam=gen
upgcxcode$removeparam=deadline
upgcxcode$removeparam=nbs
upgcxcode$removeparam=uipk
upgcxcode$removeparam=e
```

**Comment by Alex-302** [comment]
Not sure about all these parameters. Please show values, which similar to real.
