### ISSUE TITLE
doxxxindians.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#10459]
**Site**: http://www.doxxxindians.com/main.php?g=34&hl=en

**Issue**: Please remove the highighted empty ad window that is shown in the screenshot.

**Screenshot**: http://prntscr.com/i5tv1w

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
Not reproduced, hid other ad left-over at bottom.

@AdamWr

**Comment by AdamWr** [comment]
Fixed.
