### ISSUE TITLE
eliteindianporn.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#10460]
**Site**: http://www.eliteindianporn.com/

**Issue**: Please remove the highighted empty ad window that is shown in the screenshot. Pop-up also seen

**Screenshot**: http://prntscr.com/i5tvh8

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
Popup and ad window not reproduced.

@AdamWr

**Comment by AdamWr** [comment]
Fixed.
