### ISSUE TITLE
Some Cosmetic Filters

### ISSUE THREAD

**Issue by blogmangit** [AdguardTeam/AdguardFilters#104688]
Hi there Adguard Team,

I have created some cosmetic filters that targets mainly google amp pages. It block certain elements like empty placeholders, install app banners, ad widgets etc.

I am attaching the link to the filter here plz consider this to add in your respective filters.

https://raw.githubusercontent.com/blogmangit/Cosmetic-Filters/main/cosmetic%20filters.txt

Regards.

**Comment by Alex-302** [comment]
Hi. Better just report sites, or make pull requests. It is not simple to check unsorted rules.
