### ISSUE TITLE
fastindianporn.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#10467]
**Site**: http://www.fastindianporn.com

**Issue**: Please remove the highighted empty ad that is shown in the screenshot. 

**Screenshot**: http://prntscr.com/i5vbi1

Pop-up also seen.

Also seeing empty ad banners on this page: http://www.fastindianporn.com/real.php?link=hi/video/indian-bhabhi-35419/

Screenshot: http://prntscr.com/i5vhub

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
Ad window not reproduced.

@AdamWr

**Comment by AdamWr** [comment]
I can't reproduce it.
