### ISSUE TITLE
firstpost.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#104676]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.17

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.firstpost.com/health/indias-omicron-tally-at-422-6987-covid-19-infections-162-deaths-registered-in-24-hours-10236211.html

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, Filter unblocking search ads and self-promotion

### Add your comment and screenshots

1. they fake a few article tags and put ads inside. The tags are part of the text thats why i reported here

2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="329" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/147418133-b5bdc403-a625-48fc-9a05-c67bbc575838.PNG">
<img width="934" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/147418163-58897ef9-0a95-474b-8796-1cfcd7ee129e.PNG">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
*uBlock Filters* has, for comparison:
```
firstpost.com##+js(remove-attr, href, .t-out-span [href*="utm_source"], stay)
firstpost.com##+js(remove-attr, src, .t-out-span [src*=".gif"], stay)
```

I am not sure how easily they could be converted to AdGuard syntax, however.
