### ISSUE TITLE
longindiantube.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#10461]
**Site**: http://www.longindiantube.com/

**Issue**: Please remove the highighted empty ad window that is shown in the screenshot. Pop-up also seen

**Screenshot**: http://prntscr.com/i5typl

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
Added rules for bottom left-over and popup, window not reproduced.

@AdamWr

**Comment by AdamWr** [comment]
I can't reproduce it, but added rule for ad leftover next to video player and for crypto miner (found it on another website).
