### ISSUE TITLE
chrome.google.com (N: None in particular) (T: Dangerous site)

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#104631]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBO 1.39.3rc1 + IDCAC 3.3.5

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://chrome.google.com/webstore/search/adblock?_category=extensions

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. In light of `https://github.com/AdguardTeam/AdguardFilters/issues/104151` and `https://github.com/AdguardTeam/AdguardFilters/issues/104398`, and the guaranteed disaster of Manifest V3, it's time to escalate the whole *"Try to make Chrome's extension store vetting team less useless and borderline corrupt"* fight to the next level. I therefore propose adding these entries to AdGuard Base:
```
! https://chrome.google.com/webstore/detail/total-adblock-ad-blocker/gekdekpbfehejjiecgonmgmepbdnaggp
||totaladblocker.com^$all
! https://chrome.google.com/webstore/detail/ublock-free-ad-blocker/epcnnfbjfcgphgdmggkamkmgojdagdnn
||ublock.org^$all
! https://chrome.google.com/webstore/detail/der-werbeblocker-adblock/jgpangedefoljhpijicpcbgcecpfjokn
||derwerbeblocker.com^$all
! https://chrome.google.com/webstore/detail/adlock-adblocker-privacy/aemffjkmgcepimloclpkecifcnipnodh
||adlock.com^$all
! https://chrome.google.com/webstore/detail/adblocker-genius-pro/jdiegbdfmhkofahlnojgddehhelfmadj
||djamol.com^$all
! https://chrome.google.com/webstore/detail/ultrablock-privacy-protec/ijnodnmgpgmgaajhagolfiemmmamfcgb
||ultrablock.org^$all
! https://chrome.google.com/webstore/detail/adblock-unicorn/ldjhogknogpdklogdocbicnlpljekejl
||adblock-unicorn.com^$all
! https://github.com/DandelionSprout/adfilt/blob/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt#L323-L354 ("AdGuard for Windows/Mac" only)
chrome.google.com#?#.webstore-test-wall-tile:has-text(www.ublock.org)
chrome.google.com#?#.webstore-test-wall-tile:has-text(uBlock Plus Adblocker)
chrome.google.com#?#.webstore-test-wall-tile:has-text(Adblocker for )
chrome.google.com#?#.webstore-test-wall-tile:has-text(Adblocker Plus)
chrome.google.com#?#.webstore-test-wall-tile:has-text(Adblocker Genesis Plus)
chrome.google.com#?#.webstore-test-wall-tile:has-text(Adblocker HARDLINE)
chrome.google.com#?#.webstore-test-wall-tile:has-text(uBlock Pro)
chrome.google.com#?#.webstore-test-wall-tile:has-text(ADZbuzz uBlock)
chrome.google.com#?#.webstore-test-wall-tile:has-text(Adblocker DEFENSE)
chrome.google.com#?#.webstore-test-wall-tile:has-text(Adblocker Professional)
chrome.google.com#?#.webstore-test-wall-tile:has-text(Adblocker CRM)
chrome.google.com#?#.webstore-test-wall-tile:has-text(uBlocker)
chrome.google.com#?#.webstore-test-wall-tile:has-text(AdFilter)
chrome.google.com#?#.webstore-test-wall-tile:has-text(AdBlock Inc.)
chrome.google.com#?#.webstore-test-wall-tile:has-text(Adblocker Genius PRO)
chrome.google.com#?#.webstore-test-wall-tile:has-text(Easy AdBlock)
chrome.google.com#?#.webstore-test-wall-tile:has-text(radventsolutions)
chrome.google.com#?#.webstore-test-wall-tile:has-text( & AdBlock)
chrome.google.com#?#.webstore-test-wall-tile:has-text(Adblock for WebSites)
chrome.google.com#?#.webstore-test-wall-tile:has-text(ADBlock)
chrome.google.com#?#.webstore-test-wall-tile:has-text(Adblocker.Global)
chrome.google.com#?#.webstore-test-wall-tile:has-text(/best ?ad ?block/i)
chrome.google.com#?#.webstore-test-wall-tile:has-text(/(^| )1 ?adblock/i)
chrome.google.com#?#.webstore-test-wall-tile:has-text(Adbear)
chrome.google.com#?#.webstore-test-wall-tile:has-text(Adresist)
chrome.google.com#?#.webstore-test-wall-tile:has-text(otih-oith.us.to)
chrome.google.com#?#.webstore-test-wall-tile:has-text(/Adblock adblock/i)
chrome.google.com#?#.webstore-test-wall-tile:has-text(/Adblock Origin/i)
||adblock.biz^$all
||the1adblocker.com^$all
||otih-oith.us.to^$all
```

Many of these entries are already present in *Dandelion Sprout's Annoyances List*, but I figured it'd be a good idea to add them to AdGuard Base too, which has ≥1,000 times more users.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/22780683/147411310-e45f9b38-a884-477f-bc7d-eed8b0778e30.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by iam-py-test** [comment]
Don't forget `https://chrome.google.com/webstore/detail/zeta-adblock/okfdbakkmcdmbmfnjeiifakgjgdfhddf?hl=en-US` which is just a ripoff of uBlock Origin 
Proof: `https://github.com/iam-py-test/investigations/blob/b8cfa82cd1f6554479d898720b074565a9c9c4ea/2021/11/13/1.md#extension-dump`

**Comment by iam-py-test** [comment]
@DandelionSprout as per https://github.com/uBlockOrigin/uBlock-issues/issues/1586, maybe https://chrome.google.com/webstore/detail/adblock-max-ad-blocker/ggdpplfehdighdpleoegjefnpefgpgfh

**Comment by Alex-302** [comment]
If these extensions are dangerous, just report them to Google. Users without adblockers will see these extensions in any case.

**Comment by DandelionSprout** [comment]
I thought people in the adblocker community believed that Chrome were extremely slow and/or bad at removing problematic adblockers?

**Comment by iam-py-test** [comment]
Google _is_ slower than a glacier. Some of those (i.e. _uBlock_) have been on the store for years and despite abuse reports have survived.

**Comment by Alex-302** [comment]
ok

**Comment by iam-py-test** [comment]
> ok

Thanks
