### ISSUE TITLE
I want to be a contributor to the project.

### ISSUE THREAD

**Issue by blogmangit** [AdguardTeam/AdguardFilters#104694]
Please help me so that I can become an authorized contributor to the project.

**Comment by gork7777** [comment]
You need to learn GitHub and create your filters. You can read this: [How to create your own ad filters](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters)

**Comment by blogmangit** [comment]
> You need to learn GitHub and create your filters. You can read this: [How to create your own ad filters](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters)

Thanks will do learn
