### ISSUE TITLE
Adblock Warning message on site; nl.hardware.info

### ISSUE THREAD

**Issue by gvanosch12** [AdguardTeam/AdguardFilters#10469]
Hello Everyone,

Can you please add a filterrule to the dutch filterlist or annoyance filterlist wich removes this yellow adblock Warning message on the site: nl.hardware.info

Thanks.

Geert Van Osch

![schermopname 19](https://user-images.githubusercontent.com/19804873/35439453-0ac542e8-029b-11e8-8ac9-dc450727eb9b.png)

**Comment by BlazDT** [comment]
Not reproduced. Please use reporting tool, thank you.

https://reports.adguard.com/new_issue.html

**Comment by gvanosch12** [comment]
@Alex-302 
Can you please help to add the right filterrule to the Dutch Filterlist or Annoyance Filterlist  for the site: https://nl.hardware.info   to remove the yellow adblock warning screen on this site
Thanks.
Geert Van Osch

**Comment by gvanosch12** [comment]
@AdamWr 

Adam,can you please help to reproduce and add a filter rule to the dutch filterlist or annoyance filterlist wich removes the adblock warning screen on the site; https://nl.hardware.info

Thanks.

Geert Van Osch

**Comment by gvanosch12** [comment]
@AdamWr 
Adam,sorry for this comment,i saw that you were unable to reproduce,i hope @Alex-302  will able to reproduce

**Comment by gvanosch12** [comment]
@seanl-adg 
Sean,can you please help to reproduce this issue

**Comment by Alex-302** [comment]
try this
```
nl.hardware.info#$#.sitearea > div[style*="background: rgb(255, 229, 77);"][style*="display: block !important; visibility: visible !important;"] { position: absolute!important; left: -3000px!important; }
```

**Comment by gvanosch12** [comment]
Hi Alex,

Unforteanally the code did not work,thanks for your dedication,i hope there is a solution to fix this issue

**Comment by Alex-302** [comment]
Show banner's code, please.

**Comment by gvanosch12** [comment]
nl.hardware.info#$#.sitearea > div[style*="background: rgb(255, 229, 77);"][style*="display: block !important; visibility: visible !important;"] { position: absolute!important; left: -3000px!important; }

**Comment by Alex-302** [comment]
No, this is my rule:)
I need this
http://imagizer.imageshack.com/img924/4481/oe1kYO.jpg

**Comment by gvanosch12** [comment]
I hope this is the right information you need

![schermopname 22](https://user-images.githubusercontent.com/19804873/35675225-918ed11c-0747-11e8-8de5-99064e75ce70.png)

**Comment by Alex-302** [comment]
check this
`nl.hardware.info#$#.sitearea > div[style*="background: rgb(255, 229, 77);"] { position: absolute!important; left: -3000px!important; }`
if it does not work, add test rule
`nl.hardware.info#$#.sitearea > div { position: absolute!important; left: -3000px!important; }``
this rule must hide page content.

**Comment by gvanosch12** [comment]
First rule doesn;t work,second test rule comes on this site(see sreenshot0
![schermopname 23](https://user-images.githubusercontent.com/19804873/35675884-04b09c78-074a-11e8-89c6-5893b241eb2a.png)

**Comment by Alex-302** [comment]
no, don't search it)
Add it to user filter

**Comment by gvanosch12** [comment]
Yes! works Alex,thanks very much for the help and guidance
