### ISSUE TITLE
https://apkcrusher.com/here-wego-offline-maps-gps.html

### ISSUE THREAD

**Issue by dino775** [AdguardTeam/AdguardFilters#10477]
When the customer follows this particular link https://apkcrusher.com/here-wego-offline-maps-gps.html he receives a message 'It looks like you are using an ad blocker'. I was able to reproduce this issue. Screenshot below:

Screenshot:
https://prntscr.com/i5wwmw

**Comment by BlazDT** [comment]
Not reproduced, please list the filters, thank you.
