### ISSUE TITLE
wowindianporn.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#10471]
**Site**: http://www.wowindianporn.com/

**Issue**: 

1. Pop-up seen on the page.
2. Remove empty ad banner as seen in the screenshot.

**Screenshot**: http://prntscr.com/i5vog2

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
Fixed and handled in another request.
