### ISSUE TITLE
Paramount + blocked by AdGuard DNS

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#104881]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

AdGuard Default DNS

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.paramountplus.com/intl/

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

1. I have been running Adguard DNS on my router for quite some time and enjoying it, so first - thank you!  Also wanted to let you know about an issue.  Ran into an issue with Paramount Plus on my Apple TV.  I am a paid Paramount Plus subscriber, yet even so, the app would not actually stream anything if I was using Adguard DNS.  Once I changed the DNS server on my Apple TV to not blocking, it worked fine.  Not sure what’s going on with Paramount Plus.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/15856304/147540932-70693571-bce2-4fd0-a968-8cb209f22ba4.png)

</details>

<details><summary>Screenshot N:</summary>

![image](https://user-images.githubusercontent.com/15856304/147540932-70693571-bce2-4fd0-a968-8cb209f22ba4.png)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@Eugene-Savenko Not reproduced.
![image](https://user-images.githubusercontent.com/8361299/147741268-c39d549c-61a7-4732-b524-88c6cf77c5c8.png)

**Comment by Alex-302** [comment]
Please record HAR file with DNS(disable all other ad blockers).

**Comment by TyrantWorm** [comment]
Hi, I don’t know what HAR file is, but I am the one who reported this issue to your team.  To clarify a couple things:
— yes, as you found out, the website itself loads no problem. 
— however, playing a video using their service does not work and produces an error (attached).
— I believe there is either free content on the platform OR a free tier - these are ad supported.  I would not expect these to work with Ad Guard, obviously.
— I have the premium, ad-free version of the service and still experience no video.

I found this Reddit thread where lots of other people have the same issue with Pi Hole and have tried to figure out what needs to be white listed:  https://www.reddit.com/r/pihole/comments/lxnjdg/paramountplus_pihole_whitelist/

Looks like either `cbsinteractive.hb.omtrdc.net` Or `saa.cbsi.com` Worked for some people there.  Again, I think a lot of that discussion is around the free, ad-supported version, so you will see lots of trackers and ad servers being talked about.

![413A6732-364C-4BCF-AFC8-0F4380842A49](https://user-images.githubusercontent.com/96779176/147754978-a2cc793e-9581-4876-81a1-eec5a9f075b1.jpeg)

**Comment by Alex-302** [comment]
@TyrantWorm Hi. We do not block that domains. Probably caused by blocking some others.
Please provide download link of this app.

**Comment by TyrantWorm** [comment]
Here’s the iOS version:  https://apps.apple.com/us/app/paramount/id530168168

I wouldn’t know how to provide you a link to the AppleTV store app, and I don’t have Android.  But in any case, all of the apps are called the name of the service - Paramount+ - so I’m sure it would be readily findable in the US anyway.  Not sure it’s available globally.

**Comment by Eugene-Savenko** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/105222

**Comment by Eugene-Savenko** [comment]
+ 1 report from AdGuard for Windows user, helpdesk ID 567706.

**Comment by Alex-302** [comment]
@TyrantWorm Hi. Cannot be fixed, because app fails when general ad and tracking domains are blocked:
```
pubads.g.doubleclick.net
pagead2.googlesyndication.com
dpm.demdex.net
```
on iOS this is impossible to unblock domains for specific app only:(
You can try AdGuard non-filtered DNS + DNS filter, and add that domains in whitelist.

**Comment by TyrantWorm** [comment]
Does it attempt to reach out to those domains even with premium account?  I expected it to do so with ad-supported free tier but hoped it wouldn’t need to do so with premium.  Thank you for trying!

**Comment by Alex-302** [comment]
I am not sure. Ususally tracking is not disabled even for super-plus-premium accounts. Ads may be disabled by parameters in advertising config, which loaded from advertising domain(which is blocked) and parsed by app/player(on desktop or Android sometimes we can change ad settings and disable ads).
