### ISSUE TITLE
weather channel app (ios)

### ISSUE THREAD

**Issue by hitechtalk69** [AdguardTeam/AdguardFilters#104920]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.3.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

the weather channel app (ios)

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

dont know if this would qualify for sure because it says perfomance monitoring but it is used for analytics.

the url in dns log is: ||eum-orange-saas.instana.io^

their website page: https://www.instana.com/docs/website_monitoring/faq/

link to app: https://apps.apple.com/us/app/weather-the-weather-channel/id295646461

### Privacy

- [X] I agree to follow this condition

**Comment by hitechtalk69** [comment]
@Alex-302

**Comment by hitechtalk69** [comment]
it looks like this is a for sure logger: https://www.ibm.com/docs/en/obi/current?topic=using-instana

**Comment by hitechtalk69** [comment]
@Alex-302

**Comment by Alex-302** [comment]
It is used by devs, not for marketing etc.

**Comment by hitechtalk69** [comment]
EUM Analytics provides data for the following event types: Browser Requests Event Data Browser Sessions Event Data Mobile Requests Event Data Mobile Sessions Event Data

**Comment by hitechtalk69** [comment]
https://docs.appdynamics.com/display/PRO44/EUM+Data

**Comment by hitechtalk69** [comment]
that specific url is used for logging

**Comment by hitechtalk69** [comment]
@Alex-302
