### ISSUE TITLE
rentenberatung-aktuell.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#105061]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.17

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://rentenberatung-aktuell.de/krankenversicherung/krankengeld/198-kein-krankengeldanspruch-aufgrund-familienversicherung-ueber-ehefrau.html

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, Filter unblocking search ads and self-promotion

### Add your comment and screenshots

Website is broken because the cookie banner is blocked
<img width="610" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/147700607-ac7c4dd7-896d-4f77-b607-d519dcb36447.PNG">

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
No visitors.
