### ISSUE TITLE
thewindowsclub.com [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#10518]
**Site**: http://www.thewindowsclub.com/appymouse-mouse-pointer-tablets

**Issue**: Please remove the adblock message seen on the page. You may need to wait for few seconds until it shows up.

**Screenshot**: http://prntscr.com/i6acny

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
Not reproduced. Please check @AdamWr

**Comment by AdamWr** [comment]
I can't reproduce it.
