### ISSUE TITLE
dosgamezone.com anti adblock

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#105382]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.17

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://dosgamezone.com/game/color-revolution-7493.html

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, Filter unblocking search ads and self-promotion

### Add your comment and screenshots

When i try to download a game i get only a small text file in a .zip with anti adblock notice

The in browser game says it "Your browser is preventing Color Revolution from loading. This is usually caused by ad blockers." but its not working on firefox with disabled adblock either (blank screen). I not tested on chrome

<img width="538" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/147876029-44ebb7b2-4820-47fa-adae-ee46cd88cac1.PNG">
<img width="373" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/147876418-6f071a6b-be79-4d91-87d7-557618a3a856.PNG">

They checking `dosgamezone.com/ads/banner1.gif` for both anti adb (in browser game & download)

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
*uBlock Filters* has `@@||dosgamezone.com^$image,~third-party` for comparison, most likely for good reason.

**Comment by Alex-302** [comment]
Cannot reproduce, I can download.
@AdguardTeam/filters-maintainers Please take a look.

**Comment by JobcenterTycoon** [comment]
Can really nobody reproduce this issue?

**Comment by AdamWr** [comment]
Could you please check this rule:
```
@@||dosgamezone.com/ads/banner1.gif
```

**Comment by JobcenterTycoon** [comment]
it works

**Comment by AdamWr** [comment]
Added, thank you for your reply.
