### ISSUE TITLE
AdGuard DNS blocks MMS downloads on (at least) Android T-Mobile

### ISSUE THREAD

**Issue by hydraulix93** [AdguardTeam/AdguardFilters#105480]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

N/A

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

Not sure - T-Mobile MMS download endpoint

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

1. <comment>

On an android device on the T-Mobile network, using AdGuard DNS makes it impossible to download MMS messages. 

</comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [x] I agree to follow this condition

**Comment by hydraulix93** [comment]
bump

**Comment by Alex-302** [comment]
Who uses MMS in the 21st century? :)

Could you please check with AdGuard "non-filtered" DNS?

**Comment by hydraulix93** [comment]
...everyone in a multi-platform messaging group? iMessage/Google Messages users contacting friends with the other platform? 

Do you have a link to where I can contact that group? 

Thanks

**Comment by Alex-302** [comment]
> Do you have a link to where I can contact that group?

Sorry, not understood. Which group?
Please test with AdGuard "non-filtered" DNS(`94.140.14.140`). I guess MMS is not blocked, but broken just by custom DNS.
