### ISSUE TITLE
community.us.playstation.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#1055]
Broken when Fanboys Enchanced Tracking list is enabled (and Russian is disabled -- btw why does it fix that?).

Links becomes not-clickable in this case.

Caused by blocking
http://metrics.us.playstation.com/b/ss/*

Link to a page with broken links:
http://community.us.playstation.com/t5/UNCHARTED-4-A-Thief-s-End/bd-p/96478

**Comment by Alex-302** [comment]
I don't see this request
http://metrics.us.playstation.com/b/ss/*
Links are clickable.
on your link.
Checked with Eng, Spy, Social and Experimental filters.

**Comment by ameshkov** [comment]
Use Fanboys Enchanced Tracking  and Safari

**Comment by Alex-302** [comment]
No difference.
There is no request metrics.us.playstation.com in developer tools.
