### ISSUE TITLE
Как глобально применить фильтр $replace для всех сайтов ?

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#105549]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Сабж.

Как глобально применить фильтр $replace для всех сайтов ? Различные попытки манипуляций с данным фильтром ни к чему не привели. Он срабатывает лишь как довесок к определённому домену.

### Proposed solution

-

### Additional information

-

**Comment by Alex-302** [comment]
Просто не указывайте адрес. По аналогии с этим:
`$replace=/aaaaaaa/bbbbbbb/`
Главное, чтобы регулярные выражения были корректными. Можно отлаживать на https://regex101.com/

**Comment by Baltazar500** [comment]
>Просто не указывайте адрес. По аналогии с этим:
>$replace=/aaaaaaa/bbbbbbb/

А я по ваше у так не пробовал  ? Я же выше писал "Различные попытки манипуляций с данным фильтром ни к чему не привели. Он срабатывает лишь как довесок к определённому домену." Предложенный вами вариант я в самом начале и применил. Но мловил обломинго. Потом попробовал разные комбинации, но не прокатило. Работает только с доменом. Простая замена без всяких регекспов. 

>closed

Оикрывайте назад

**Comment by Alex-302** [comment]
Неизвестно, что вы пробовали. Опишите по шагам.

**Comment by Baltazar500** [comment]
>Неизвестно, что вы пробовали. Опишите по шагам.

Фильтр 

>www.google.com$replace=/www.reddit.com/old.reddit.com/

успешно работает в гугле. Фильтр

>$replace=/www.reddit.com/old.reddit.com/

в гугле, равно как и где-то ещё не работает.

**Comment by Alex-302** [comment]
Покажите пример заменяемого текста, как он выглядит в страницах.

**Comment by Alex-302** [comment]
Попробуйте так
`http$replace=/www.reddit.com/111.reddit.com/`

**Comment by Baltazar500** [comment]
>```http$replace=/old.reddit.com/111.reddit.com/```

Этот фильтр сработал. А почему первый не срабатывает ? Ведь он по логике корректный.

**Comment by Baltazar500** [comment]
Спасибо за помощь.

**Comment by Alex-302** [comment]
> Этот фильтр сработал. А почему первый не срабатывает ? Ведь он по логике корректный.

Без пути - некорректный. Защита от "дурака")

**Comment by Baltazar500** [comment]
>Без пути(хоть какого-то уточнения, т.к. правило может много чего сломать) - некорректный. Защита от "дурака")

0_o

Но вы же в самом начале предложили именно этот вариант

>```$replace=/aaaaaaa/bbbbbbb/```

на грабли которого я и сам изначально встал (из-за чего и завёл issue). Или я что-то неправильно понял ? В любом случае, этот момент стоит отобразить в документации. По крайней мере поиском ни одного ```"http$"`` примера я не обнаружил (равно как и его описания).

**Comment by Alex-302** [comment]
Да, надо описать. Просто без адреса давно не использовал этот тип правил.
