### ISSUE TITLE
ouo.io [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#10553]
**Site**: http://ouo.io/IDzpT

**Issue**: Please remove the pop-up after the count down timer reaches zero.

**Screenshot**: N/A

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
Not reproduced-

**Comment by AdamWr** [comment]
Fixed.
