### ISSUE TITLE
[Android] Missed ad in Weather & Clock Widget Android

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1056]
https://play.google.com/store/apps/details?id=com.devexpert.weather&hl=en
1. https://www.dropbox.com/s/haja59a7ifp0xci/Screenshot_2015-12-06-12-27-09.png?dl=0
2. http://snag.gy/PGqef.jpg

[debug.txt](https://github.com/AdguardTeam/ExperimentalFilter/files/53937/debug.txt)

EGJ-170-29635
QCS-594-59805

**Comment by Alex-302** [comment]
Странно Это ж гугловая реклама вроде. Что происходит если на треугольник на баннере нажать? Должно название системы отобразиться.

**Comment by evgeniy-ADG** [comment]
AdChoice или как ее там, фейсбуковая она. Если хорошенько нажать на треугольник, открывается фейсбук :)

**Comment by evgeniy-ADG** [comment]
@Alex-302 Adchoice не блокируются?

**Comment by Alex-302** [comment]
пока не будет поддержки HTTPS - нет. Но уже вроде работают над ней.
А на устройстве вход в фейсбук выполнен?

**Comment by Alex-302** [comment]
пока закрываю

**Comment by Alex-302** [comment]
C альфа-версией чисто.

**Comment by evgeniy-ADG** [comment]
Еще одна жалоба на приложение, у нас не повторилось, запросили логи HTTP.

Проблема возникает (в виде черного пустого баннера) почти сразу после открытия приложения, примерно через 1-2 секунды. 
![image](https://cloud.githubusercontent.com/assets/15856304/15432568/75f95bae-1eb7-11e6-9503-78edd8fbda7e.png)

TICKET ID
ROR-509-89432
