### ISSUE TITLE
com.chimbori.hermitcrab

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#10584]
***Description***:
* **Current behaviour**: 

Displays ads in Preview Pane when creating a lite app through the browser.

<details><summary>Screenshot:</summary>

![screenshot_2018-01-28-15-32-04](https://user-images.githubusercontent.com/33634917/35482617-92213a2a-0440-11e8-9038-2f6841968a28.png)

</details><br/>

* **Expected behaviour**: 

Should not display ads.

***Steps to reproduce the problem***:

1. Open the main app (Hermit Lite Apps) and attempt to create a Lite App of any site. The ticket author was using https://www.flashback.org/aktuella-amnen
2. The ads will be displayed in a preview pane when creating a lite app.
3. The user also reports that the ads are also displayed within the lite app, but everything worked fine on my end.

Ads will display regardless of "Ad & Malware blocker" option status.

***System configuration***

**Filters:**

English, Spyware, Filter unblocking useful ads, Mobile Ads filter

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 5.0
Browser:                               | Not Applicable
AdGuard version:                       | 2.10.176
Filters enabled:                       | English, Spyware, Filter unblocking useful ads, Mobile Ads filter
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default Mode)
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | Original: 1738828 Reproduction: 1691619

**Comment by Alex-302** [comment]
I can't create an app using url. Need more detailed description.

**Comment by alpfrog** [comment]
This issue is seen in "Hermit • Lite Apps Browser"

https://play.google.com/store/apps/details?id=com.chimbori.hermitcrab

I followed the following steps:
* Open Hermit
* Press the plus sign
* Choose the CREATE YOUR OWN tab
* Enter https://www.flashback.org
* If the on-screen keyboard is not open, click the text box again, and confirm the entry via the keyboard
* Create the lite app
* Open the created app
* In the site's (not the app's) hamburger menu, choose Aktuella ämnen

I see ads on the forum when I access it through Hermit, but not when I browse it in Chrome or the webview from Google search. I have https and all apps enabled. Example URL where I see ads: https://www.flashback.org/aktuella-amnen

I have the following rule in User Filter:
||flashback.org/img/banners/

**Comment by Alex-302** [comment]
Hi
This rule from Eng filter was triggered on my end
```
.org/ads/
```

**Comment by alpfrog** [comment]
I can see that rule triggering when I go to the URL in Chrome, but when I use Hermit, I only see a couple of status processed rows for static.flashback.org. I reinstalled AdGuard and set the logging level to Record everything, and then opened the Hermit app to a page with ads. Would that log be helpful?

**Comment by Alex-302** [comment]
> I only see a couple of status processed rows for static.flashback.org

only domains, not full URLs? Please make screenshot of HTTPS settings.

**Comment by alpfrog** [comment]
Yes, I only see domains logged when using Hermit. This is true also for another https site.

Settings screenshots:
https://i.imgur.com/jJh0msW.png
https://i.imgur.com/gA83o9O.png
https://i.imgur.com/jOTOSxs.png
https://i.imgur.com/5ETe4jb.png

Is Hermit one of those Nougat+ apps, that can't be filtered by AdGuard?

**Comment by Alex-302** [comment]
HTTPS filtering for the apps in Nougat is not full without root access. Onlu whole domains can be blocked in this case.

**Comment by alpfrog** [comment]
I'm rooted, so it's still weird AdGuard doesn't work.

**Comment by Alex-302** [comment]
Ok. You can try to move AdGuard' certeficate to the system storage using `Move Certs` app
https://play.google.com/store/apps/details?id=com.nutomic.zertman

**Comment by alpfrog** [comment]
I don't think Move Certs works on Nougat either. At least it didn't for me. But I finally understood the issue and managed to get the certificate into the system store using this Magisk module: https://github.com/NVISO-BE/MagiskTrustUserCerts. Now filtering works.

**Comment by alpfrog** [comment]
It should be stated more clearly that AdGuard doesn't have full functionality on Android 7.0+

**Comment by Alex-302** [comment]
AdGuard will be able to move certs on rooted Android 6+ in 2.11
