### ISSUE TITLE
.mdl-snackbar - framework components should not be blocked

### ISSUE THREAD

**Issue by Serubin** [AdguardTeam/AdguardFilters#10589]
***Description***:
Framework components should not be blocked on a global basis. Rather they should be blocked on a site to site basis as it may block legitimate uses of components. 

Specifically **mdl-snackbar** should not be blocked as it has legitimate uses as per the Google Material Design Standard.

**Comment by Alex-302** [comment]
@Serubin We need example.

**Comment by Serubin** [comment]
This is a framework element within https://getmdl.io/components/index.html#snackbar-section. It's used in applications such as https://messenger.klinkerapps.com/ or https://pulse.serubin.net.
