### ISSUE TITLE
[MacOS] Не кликабельны ссылки на www.ntv.ru при первой загрузке сайта

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1059]
Пользвователь открыл http://www.ntv.ru/novosti/, хотел нажать сюда - http://take.ms/eNeoq 
Сcылка была не кликабельна, отключил Adguard, перезагрузил страницу и все заработало. Потом снова включил Adguard, перезагрузил - работает. Такое ощущение, что подвисание происходит в момент первой загрузки страницы, когда она не попала в кеш браузера.

У нас сложность -повторилась- в Сафари (в Хроме не воспроизводится).

**Comment by Alex-302** [comment]
Расширение или программа?

**Comment by evgeniy-ADG** [comment]
Программа.

**Comment by Alex-302** [comment]
А не смотрели, какой-то определённый фильтр ломает, или с выключенными фильтрами тоже?
