### ISSUE TITLE
com.yahoo.mobile.client.android.mail & com.yahoo.mobile.client.android.fantasyfootball

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#10591]
***Description***:
* **Current behaviour**: 

Show "Sponsored" ads

<details><summary>Screenshots:</summary>

![screenshot_20180127-144923](https://user-images.githubusercontent.com/33634917/35484812-37f195e0-045e-11e8-98e1-7b958011e211.png)

![screenshot_20180127-144809](https://user-images.githubusercontent.com/33634917/35484842-c9bbfbfa-045e-11e8-8761-b4d88f52fd6c.png)
</details><br/>

* **Expected behaviour**: 

No ads

***Steps to reproduce the problem***:

MAIL
1. Login into the mail
2. Ads will be visible as "Sponsored" content

FANTASY
1. Ads will be visible in the Dashboard, between individual matches

***System configuration***

**Filters:**
"English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Experimental filter", "Mobile Ads filter", "Simplified domain names filter"

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 7.0
Browser:                               | N/A
AdGuard version:                       | 2.10.176
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Experimental filter", "Mobile Ads filter", "Simplified domain names filter"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | Off
AdGuard DNS:                           | Default
Helpdesk ID (if exists):               | 1669281

**Comment by Alex-302** [comment]
These ads can't be blocked without HTTPS filtering. In addition, on Android 7 SSL certeficate must be moved to the system storage(root access is required).

**Comment by Alex-302** [comment]
Not reproduced.
I need HAR files recorded with enabled HTTPS filtering on Android 5.
