### ISSUE TITLE
ukrinform.ua

### ISSUE THREAD

**Issue by PoRtvine** [AdguardTeam/AdguardFilters#10624]
Incorrectly removed content 

https://www.ukrinform.ua/info/uatv.html

![image](http://i.piccy.info/i9/ff59930c3c0dce928444d4a42178d5f2/1517222984/187275/1217029/Bezymiannyi.png)
I can’t play videos.
/*##iframe:not([src]):not([id="adguard-assistant-dialog"]):not([style*="translate3d"]):style(position: absolute!important; left: -3000px!important;)*/
***System configuration***
Win 10 Pro x64
**Filters:**
Adguard Base Filters in uBO 1.14.25

**Comment by Alex-302** [comment]
Fixed.
