### ISSUE TITLE
Ads are not blocked in Firefox ESR 52.5.3 (32-bit)

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#10635]
![image](https://user-images.githubusercontent.com/15856304/35515274-67c14438-0511-11e8-9491-c863abfa2ed2.png)

@Alex-302 do you know why this happens? **_AdGuard extension 2.8_**, the customer states it no longer works after the recent update of the extension. Filters are: English, Russian, Social media widgets, and Spyware. Screenshots of the filtering log:

[log.zip](https://github.com/AdguardTeam/AdguardFilters/files/1673903/log.zip)

**Comment by ameshkov** [comment]
@evgeniy-ADG а ты уверен что это реальная реклама от ВК, а не малварью вставленное?

**Comment by ameshkov** [comment]
Выглядит странновато, ставлю на малварь

**Comment by evgeniy-ADG** [comment]
Говорят, что не малварь. Там всем проверили и ничего не нашли.

**Comment by AlexWolf77** [comment]
Верно, проверил чем мог (drweb, kaspersky, adwcleaner, постоянно установлен avast). Не панацея, конечно, но чем ещё проверять-то?)
Как уже писал, реклама есть не только в ВК, но и на других сайтах (не на всех).

**Comment by AlexWolf77** [comment]
Если что надо проверить - без проблем, попробую, отпишусь.
Что делал - чистил кэш браузера, искал вирусы и малварь, сносил и ставил заново расширение adguard, пробовал добавлять adguard dns. AdGuard for Windows не пробовал ставить.

**Comment by Alex-302** [comment]
@AlexWolf77 проверьте в IE и чистом браузере без расширений.
Ну и попробуйту удалить и установить Адгард заново.

**Comment by thelight5** [comment]
Попробуйте скачать портативную версию браузера Firefox ESR, например с сайта comss последнюю версию данного браузера 52.6.0 либо поищите свою версию, и уже в чистом браузере c чистым профилем поставить расширение Adguard и посмотреть как это будет работать. 
Так же в самом браузере, где у вас проблема, я бы посмотрел нет ли ничего лишнего в настройках сети, поиграв с настройками прокси - без прокси, использовать системные настройки прокси и т.д

**Comment by evgeniy-ADG** [comment]
@Alex-302 это расширение

**Comment by Alex-302** [comment]
@evgeniy-ADG ну тогда переустановить расширение, и в портативном браузере проверить, как написали выше.

**Comment by AlexWolf77** [comment]
1. Запустил Firefox ESR 52.6.0 portable, добавил плагин - рекламы нет (с отключенным плагином реклама появляется, понятно).
2. Почистил ещё раз кэш FireFox (который не portable), после чего удалил его. Вручную удалил все папки, в имени которых есть mozilla. Перезагрузка, установка FF 52.6.0, добавление плагина и... реклама на месте.
3. Настройка сети в обеих версиях FF одинакова - использовать системные настройки прокси. Вообще, прокси не используется.

Если комп чист от вирусов/malware, то где копать?

**Comment by thelight5** [comment]
Запустите Windows в безопасном режиме с поддержкой сетевых драйверов. Для этого во время загрузки системы до появления анимации Windows нажимайте часто клавишу F8. Проверьте как там работает браузер.

**Comment by Alex-302** [comment]
если что, могу удалённо глянуть

**Comment by AlexWolf77** [comment]
thelight5, в безопасном то же самое - плагин включен (и вроде даже что-то фильтрует, т.к. на его пиктограмме та или иная цифра), но реклама на месте.
Alex-302, комп рабочий, доступ никак не предоставить. Всё, что можно, я посмотрю.

Интересно то, что перестало работать в лучших традициях "Вчера всё работало, а сегодня с утра - уже нет, но я ничего не трогал" ) Причём только в одном браузере.

**Comment by thelight5** [comment]
@AlexWolf77 Закройте браузер, если открыт. Нажмите Win +R (Пуск - Выполнить) и введите firefox.exe -P . Создайте новый профиль, указав другую директорию отличную от текущего расположения профиля, например создайте папку на диске C и укажите ее. Выберите новый профиль из списка  и нажмите "Запуск Firefox". Поставьте расширение и проверьте работает ли в таком случае.
Можно еще попробовать переустановить браузер, но в другую директорию. Пока только такие мысли)

**Comment by Alex-302** [comment]
@AlexWolf77 а код баннера можете показать?

**Comment by AlexWolf77** [comment]
Alex-302, в меру своего понимания... Если что не так, скажите, как именно сделать
https://cloud.mail.ru/public/KwdR/kRXXjJ7eL

thelight5, ага, попробую.

**Comment by Alex-302** [comment]
@AlexWolf77 а остался профиль, с которым не работает? Хотелось бы взглянуть на него(только его нужно предварительно вычистить от личной информации и паролей)

**Comment by AlexWolf77** [comment]
[Alex-302](https://github.com/Alex-302), да, профиль есть. https://cloud.mail.ru/public/L4wL/vqvk5cf12
Это профиль скорее всего после очередной переустановки FF, так что много "мусора" там ещё не накопилось, а пароли и закладки удалил из него.

**Comment by Alex-302** [comment]
Спасибо, глянем.
