### ISSUE TITLE
[nsfw] clipcake.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#10647]
**Site Sample** | 
------------------|
http://www.clipcake.com/videos/140457/sex-in-the-russian-way-vintage-xlx/

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.437.2171**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Player adleftover overlay

<details><summary><b>Screenshot:</b></summary>

![snipaste_2018-01-29_20-25-31](https://user-images.githubusercontent.com/9846948/35529906-b79df25a-0532-11e8-91f9-fdf9b44cb994.png)

![snipaste_2018-01-29_20-27-31](https://user-images.githubusercontent.com/9846948/35529942-df14f84c-0532-11e8-9963-d094f1e2c4c0.png)

</details><br/>

**Comment by BlazDT** [comment]
Not reproduced. Please check @AdamWr

**Comment by AdamWr** [comment]
I can't reproduce it.
