### ISSUE TITLE
checkadblock.ru - Not fully blocked

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#10646]
https://checkadblock.ru

[adguard_logs_2.10.176_2801_2304.zip](https://github.com/AdguardTeam/AdguardFilters/files/1674892/adguard_logs_2.10.176_2801_2304.zip)

<details><summary>Screenshot:</summary>

![screen shot 2018-01-29 at 9 10 00 pm](https://user-images.githubusercontent.com/27292111/35529155-d85e1988-0538-11e8-801c-fe24bac16a9d.png)

</details><br/>

***System configuration***

Information                            | Value
---                                    | ---
Operating system:                      | Android 7.1.1 (sdk=25)
Browser:                               | Yandex/Chrome
AdGuard version:                       | 2.10.176
Filters enabled:                       | [ "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter", "Schacks Adblock Plus liste" ]
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | None
Helpdesk ID:               | 1696216

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by ameshkov** [comment]
Нужно сбросить данные у AdGuard, явно что-то не так с настройками

**Comment by Nazer92** [comment]
Добрый вечер.  Сбрасывал удалял и ставил по новой.  Все равно настройки были те же. Почистил все папки кешы и прочее установил без интернета активизировал, гугл 100% защитил яндекс пропустил яндекс метрику. В общем проблема решена.

**Comment by Nazer92** [comment]
Upd.
 яндекс метрику начал блочить когда выключил стандартное расширение Yandex access. С включенным расширением не блочит.Так что за яндекс это мой и браузера грехи. Спасибо за помощь.

**Comment by ameshkov** [comment]
Простите за задержку с ответом!

> яндекс метрику начал блочить когда выключил стандартное расширение Yandex access. С включенным расширением не блочит.Так что за яндекс это мой и браузера грехи. Спасибо за помощь.

Это на самом деле интересная находка, по ходу ЯБраузер таким макаром может обходить блокировку.
