### ISSUE TITLE
q2.be

### ISSUE THREAD

**Issue by JohnyP36** [AdguardTeam/AdguardFilters#106507]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

none

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

q2.be

### What filters do you have enabled?

AdGuard Dutch filter, EasyList, EasyList Dutch, EasyPrivacy, Fanboy's Enhanced Tracking List

### Add your comment and screenshots

https://github.com/AdguardTeam/AdguardFilters/blob/f9f04aee90a230b5b61252a2f5233b510979b909/DutchFilter/sections/specific.txt#L85

`q2.be` doesn't exist anymore. 
Also see: https://github.com/AdguardTeam/AdguardFilters/issues/106505

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Need steps to reproduce.

**Comment by JohnyP36** [comment]
Search for `q2.be` on google and you will notice that q2 redirects you to `vtm.be`. 
Also read `https://nl.wikipedia.org/wiki/Q2` *(dutch)*. It says that since 2020 q2 doesn't exist anymore but is now under vtm.be

**Comment by Alex-302** [comment]
Ah, got it:) 
Removed.
