### ISSUE TITLE
q2.be

### ISSUE THREAD

**Issue by JohnyP36** [AdguardTeam/AdguardFilters#106505]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

none

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

q2.be

### What filters do you have enabled?

AdGuard Dutch filter

### Add your comment and screenshots

https://github.com/AdguardTeam/AdguardFilters/blob/df12c176448e5895cf5435f6a4fb01b171dd48f0/DutchFilter/sections/antiadblock.txt#L74
https://github.com/AdguardTeam/AdguardFilters/blob/df12c176448e5895cf5435f6a4fb01b171dd48f0/DutchFilter/sections/antiadblock.txt#L76

This domain (`q2.be`) redirects to `vtm.be` and could thus be removed. 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/106505
