### ISSUE TITLE
[Windows] outlook.com false positive (Adguard Mobile Filters)

### ISSUE THREAD

**Issue by supervirus5** [AdguardTeam/AdguardFilters#10651]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: It seems that whenever I enable "Adguard Mobile filter" in uBlock Origin It seems to block the email header in outlook.com (will explain with screenshots)
* **Current behavior**: 
<details><summary>Screenshot:</summary>

![filter_enabled](https://i.imgur.com/UIYQLJN.png)
</details><br/>

* **Expected behavior**: 
<details><summary>Screenshot:</summary>

![filter_disabled](https://i.imgur.com/8y2fpxA.png)
</details><br/>

***Steps to reproduce the problem***:
1 - install uBlockOrigin extension.
2 - add Adguard mobile filters and enable it.
3 - rip email headers in outlook.com

***System configuration***

**Filters:**
Adguard Mobile Filters

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 64 Bit - Latest Update
Operating system version (Android/iOS) | NONE
Browser:                               | Google Chrome Latest Version
AdGuard version:                       | Latest (did a manual update to verify)
Filters enabled:                       | (Adguard Mobile Filters)
AdGuard mode (Android only):           | NONE
Filtering quality (Android only):      | NONE
HTTPS filtering (Android only):        | NONE
Simplified filters (iOS only)          | NONE
AdGuard DNS:                           | NONE
Stealth mode options (Windows only)    | Nope
Helpdesk ID (if exists):               | Nope

**Comment by Alex-302** [comment]
I can't log in my outlook account.
@AdamWr @BlazDT please take a look.

**Comment by BlazDT** [comment]
Changed problematic rule, so it will hide the ad and shouldn't cause this problem.
