### ISSUE TITLE
Unable to fully block adjust.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#10676]
> I have adjust.com blocked. However, recently I noticed that traffic still slips through. Here, I have a link that will redirect to app.adjust.com and then to a final destination. It registers a block in DNS query logs, but the redirect still goes through. I’ve tried it three times.

Try this link on an iPhone: http://email.myvegas.com/wf/click?upn=NZmOWqeYHjMPrlN8SKDGDxo51yDwQqz8DxUx5tUBHTm6t-2BTxePhtTJqm4QXv9yFTrFyA1Du75AvaqrW5uRnq-2FDyzDNZSR-2Bra46RTch9whidolkJVr-2BZTeAmJjj76PLjknTs53ALoGXlf3sPdyE8sn-2FhHLjM-2FfBfIh1eB84HvMlo-3D_0gtljzxWNBjooeX1onJbc1HH-2FoLPKW-2FdpFmC6lmncjHAiml45brVqw-2Bb-2BESulwIIKHxZv0ouUO58GE4i0fFKEOJATHPOfNXiA1SyFwinZx-2B-2BYEF3VgBhbLJgKN0zelN0zwTm8mMV-2FwDpehi9k2TSPLM6QZUabH6-2BNx-2B70jqzlmo7z1VhId-2B6FzwQzZeLo9-2B0ouP6Hy8WnO4cnCuwbNbn6-2Fi-2BwLAiMEzaLYJJ8l2NYiA8mNjKJ3dGK17LRzZPS0Bkl-2FmmyELDB3lL1gwe-2BLV6Ot1VTXvWHhBgD-2FfMr-2ButzEmTWm0lragp9qwRJiSArvW9FrmVFlRpDsoFFvdggU5HWdscb783Lf2KHWfOktLAysU-3D

ID: 1742881

**Comment by Alex-302** [comment]
Use `||app.adjust.com^$empty,important`
