### ISSUE TITLE
Пара вопросов по созданию своих правил...

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#10698]
1. Могу ли я заблокировать .cTest только в том случае если внутри него находятся определенные теги классы и прочее?
К примеру так не блокировать:
`<div class="cTest">123213213<a>123213213</a></div>`
А если так:
`<div class="cTest">123213213</div>`
тогда блокировать.

2. Могу ли я перейти на уровень вверх? К примеру если это переход на уровень ниже .cTest + .cTest то есть ли способ двигатся в обратную сторону?

3. Есть ли способ заблокировать по ширине, высоте если она не задана через html и через css?
![image](https://monosnap.com/file/ZwSNp55Hkewd9YJVz2tPsHu3URjQUN.png)

4. Есть ли способ использовать свои правила через Adguard DNS?

5. Возможно ли блокировать по тексту `<a>Текст1</a>`?

**Comment by Alex-302** [comment]
Да. Всё можно сделать, используя расширенный CSS
https://kb.adguard.com/ru/general/how-to-create-your-own-ad-filters#%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-css-%D1%81%D0%B5%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D1%8B

**Comment by Smorvel** [comment]
@Alex-302 Пасиб! Сейчас буду читать.. Если не лень, напиши маленькие примеры по каждому из пунктов.. И что на счет пункта 4?
Ну и собственно тему можно закрывать.

**Comment by Alex-302** [comment]
1. Если блокирующее правило - `site.ru##.cTest`, то исключение должно быть с точно таким же селектором - `site.ru#@#.cTest`
для `site.ru##.cTest[-ext-has="td > span"]` - `site.ru#@#.cTest[-ext-has="td > span"]`
4. DNS может только сопоставлять IP и доменные имена. Самый негибкий способ) Зато не требует никаких ресурсов на клиентском устройстве.
6. Не совсем понял. Обычные правила сокрытия и с расширенным CSS можно использовать.

**Comment by Smorvel** [comment]
@Alex-302 
\1. Тогда как мне заблокировать пустой .cTest и сделать что бы он не блокировался если в нем что то есть? Это невозможно?

\3. Ну я имею ввиду вот что:
`.cTest[-ext-has="td > span"][-ext-contains="texttest"]`
или же так:
`.cTest[-ext-has="td > span[-ext-contains="texttest"]"]`
Пробовал оба способа, вроде не работает.

**Comment by Alex-302** [comment]
1. `##.cTest:empty`
3. Попробуй
.cTest:has(td > span):contains(texttest)

**Comment by Smorvel** [comment]
1. Спасибо, тоже интересный вариант.. но я неправильно задал вопрос)
Мне нужно было узнать как блокировать .cTest если внутри "td" находится только "a" ##.cTest[-ext-has="td > a"] но если кроме "a" там еще и "span" тогда блокировать не нужно. 
2. От части работает.. contains работает с .cTest а нужно что бы работал с :has.. продолжу экспериментировать, может что и получится)

**Comment by Alex-302** [comment]
1. Такого нельзя сделать. Можешь здесь пожелание оставить(желательно по-английски)
https://github.com/AdguardTeam/ExtendedCss/issues
2, Можно так: `.cTest:has(td > span:contains(texttest))`

**Comment by Smorvel** [comment]
Ок, можно закрывать :)
