### ISSUE TITLE
unblock remind.me

### ISSUE THREAD

**Issue by CarstenG2** [AdguardTeam/AdguardFilters#107162]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

v0.106.2

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, Chrome, Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.remind.me/

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

1. remind.me is a Portal for Changing Power/Gas-Providers commonly used in Germany.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It is blocked by one of upstream filters. Asked author(EasyPrivacy) about it.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #875](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/875) via [**ZenHub**](https://www.zenhub.com/)
