### ISSUE TITLE
questionable ad domain imdb (ios)

### ISSUE THREAD

**Issue by hitechtalk69** [AdguardTeam/AdguardFilters#107167]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.3.1

### What type of problem have you encountered?

Missed ads or ad leftovers, Missed analytics or tracker

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

imdb (ios)

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

hi i was was wondering if mads.amazon.com is a ad domain it is being contacted in the imdb app.

https://apps.apple.com/us/app/imdb-movies-tv-shows/id342792525

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. I found information that blocking this domain will break the Amazon app.
