### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [AdguardTeam/AdguardFilters#10715]
![2018-01-31-seriale i filmy online na zyczenie kanaly tv - wejdz i ogladaj na player pl](https://user-images.githubusercontent.com/5884000/35621890-3b9e2936-0686-11e8-9454-392882add220.png)

cookie

list `Adguard Base Filters` concludes with `Polskie filtry ciasteczkowe`
https://github.com/MajkiIT/polish-ads-filter/tree/master/cookies_filters

<details><summary>my settings</summary>

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.28
Nano Defender 13.28
Chrome 64.0.3282.119

</details>

**Comment by hawkeye116477** [comment]
This is just not needed anymore -> `@@||player.pl^$generichide`
