### ISSUE TITLE
AdGuard URL Tracking filter does not strip Google search URLs

### ISSUE THREAD

**Issue by wefalltomorrow** [AdguardTeam/AdguardFilters#107123]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Ublock Origin

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.google.com.au/search?q=adguard+url+tracking&sxsrf=AOaemvJwGKWytEcUqVPlZ7LkIshlftYvpQ%3A1642497807565&ved=0ahUKEwjgvPSS_br1AhUEIbcAHbdJDCQQ4dUDCA0&uact=5&oq=adguard+url+tracking&sclient=gws-wiz

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

Using this filter with Ublock Origin on Firefox, everything up to date. As you can see with the URL above, it's just filled with garbage sadly. I used to have a userscript to strip Google URLs like above, but it hasn't been updated in years and is broken. Having this filter strip this URL nonsense would be great.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
This is just a timestamp of previous search (https://twitter.com/phillmoore/status/1169846359509233664)
You can remove it by `||google.$removeparam=sxsrf `

**Comment by wefalltomorrow** [comment]
> This is just a timestamp of previous search (https://twitter.com/phillmoore/status/1169846359509233664)
> You can remove it by `||google.$removeparam=sxsrf `

Thanks, I had to use "||google.$removeparam=ved " as well for the URL to be mostly clean.
