### ISSUE TITLE
healthproductsbenefit.com

### ISSUE THREAD

**Issue by hitechtalk69** [AdguardTeam/AdguardFilters#107170]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

4.3.1

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.healthproductsbenefit.com/Auth/Login?ReturnUrl=%2F

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

hi i don't know if netdna.bootstrapcdn.com is a tracker or not?

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. Not a tracker.
