### ISSUE TITLE
closermag.fr blocked by Web Annoyances Ultralist

### ISSUE THREAD

**Issue by AdSlayer** [AdguardTeam/AdguardFilters#107396]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.6

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.closermag.fr/people/affaire-jean-jacques-bourdin-sa-femme-anne-nivat-provoque-un-gros-malaise-dans-c-a-vous-1492589

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard French filter, AdGuard Annoyances filter, EasyList, Liste FR, Fanboy's Annoyances, Fanboy's Social Blocking List, Web Annoyances Ultralist, Fanboy's Anti-Facebook List, I don't care about cookies, EasyList Cookie List

### Add your comment and screenshots

1. <comment>The web site page is void when the Web Annoyances Ultralist is enabled.

2. Screenshots
<details><summary>Screenshot 1: List of filters</summary>

![Screenshot_2022-01-19-22-19-43-072_com adguard android](https://user-images.githubusercontent.com/97131319/150217448-153cf225-eaea-4097-8e8f-98d3d826fd54.jpg)
</details>

<details><summary>Screenshot 2: Page void</summary>
![Screenshot_2022-01-19-22-37-51-482_com android chrome](https://user-images.githubusercontent.com/97131319/150218820-dad901fd-8f4e-486e-998a-3bf02b655f5c.jpg)

</details>

</comment>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@yourduskquibbles For mobile site: `closermag.fr#@#.smartbanner` (hidden `BODY`)
