### ISSUE TITLE
snapchat (ios)

### ISSUE THREAD

**Issue by hitechtalk69** [AdguardTeam/AdguardFilters#107581]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.3.2 (923)

### What type of problem have you encountered?

Missed ads or ad leftovers, Missed analytics or tracker

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

snapchat (ios)

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

hi i found a ad url used by apple when opening snapchat.

||proxy-skadnetwork.apple.com^

![E3BB1C4E-86CC-48BC-A322-A7EC5EF36251](https://user-images.githubusercontent.com/96637039/150466878-56ca5658-be5a-466b-b485-6a5bd2302371.jpeg)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not sure about it.
