### ISSUE TITLE
Blaklader

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#107716]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.16.4.30 (XUL)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other(specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

blaklader.*

### What filters do you have enabled?

AdGuard Tracking Protection filter, AdGuard Annoyances filter

### Affected sites:
```
https://www.blaklader.at/
https://www.blaklader.be/
https://www.blaklader.ca/
https://www.blaklader.com/
https://www.blaklader.cz/
https://www.blaklader.de/
https://www.blaklader.dk/
https://www.blaklader.ee/
https://www.blaklader.es/
https://www.blaklader.fi/
https://www.blaklader.fr/
https://www.blaklader.ie/
https://www.blaklader.it/
https://www.blaklader.nl/
https://www.blaklader.no/
https://www.blaklader.pl/
https://www.blaklader.se/
https://www.blaklader.uk/
```

### Issue:
Some elements are hidden, until the cookie terms have been accepted.
However, the cookie terms can't be accepted, because they're blocked!

### Examples:
```
https://www.blaklader.ca/en/
https://www.blaklader.com/en/
```

### Screenshot:

![filterissue-blaklader](https://user-images.githubusercontent.com/9382674/150605300-77fa3bad-253d-4261-9a4e-a47e29b5f1a9.jpg)

### Problem filters / rules:
* **AdGuard Annoyances filter**
`###onetrust-consent-sdk`
`||cookielaw.org^$third-party`

* **AdGuard Tracking Protection filter**
`||googletagmanager.com/gtm.js$third-party`

### Possible fix (uBO Legacy compatible):
```
blaklader.*#@##onetrust-consent-sdk
@@||cookielaw.org^$third-party,domain=blaklader.at|blaklader.be|blaklader.ca|blaklader.com|blaklader.cz|blaklader.de|blaklader.dk|blaklader.ee|blaklader.es|blaklader.fi|blaklader.fr|blaklader.ie|blaklader.it|blaklader.nl|blaklader.no|blaklader.pl|blaklader.se|blaklader.uk
@@||googletagmanager.com/gtm.js$domain=blaklader.at|blaklader.be|blaklader.ca|blaklader.com|blaklader.cz|blaklader.de|blaklader.dk|blaklader.ee|blaklader.es|blaklader.fi|blaklader.fr|blaklader.ie|blaklader.it|blaklader.nl|blaklader.no|blaklader.pl|blaklader.se|blaklader.uk
```

### Note:
The issue seems to be partially browser-dependent.
More info here:
https://github.com/uBlockOrigin/uAssets/issues/11422#issuecomment-1018916867

### Other Problem filters:
* ~~**EasyList Cookie List** / **Fanboy's Annoyance List** / **EasyPrivacy** https://github.com/easylist/easylist/issues/10565/~~ _(FIXED)_
~~`##.optanon-show-settings`
`###onetrust-banner-sdk`
`###onetrust-consent-sdk`
`/gtm.js`
`||googletagmanager.com^`~~

* **hpHosts - Ad and Tracking servers only** _(DISCONTINUED)_
`googletagmanager.com`
`www.googletagmanager.com`

* ~~**I don't care about cookies** _(NOTIFIED)_~~ _(FIXED)_
~~`~msn.com,~eurogamer.net,~rtlxl.nl,~zdf.de,~crfashionbook.com,~rockpapershotgun.com,~zdnet.com,~mensjournal.com,~cbsnews.com,~cbslocal.com,~assetstore.unity.com,~gmx.com,~gmx.es,~gmx.fr,~gmx.co.uk,~mail.com,~kruidvat.nl,~kruidvat.be,~trekpleister.nl,~tvn24.pl,~popsugar.co.uk,~rte.ie,~tunein.com,~oe24.at,~sika.com,~merkurmarkt.at,~boomerang-tv.pl,~cnbc.com,~1001spiele.de,~dhl.de,~sport.pl,~reisetopia.de,~mtvuutiset.fi,~billa.at,~aerztezeitung.de,~okazii.ro###onetrust-consent-sdk`~~

* **Peter Lowe's Ad and tracking server list**
`googletagmanager.com`

* ~~**uBlock filters - Privacy** https://github.com/uBlockOrigin/uAssets/issues/11422/~~ _(FIXED)_
~~`||googletagmanager.com/gtm.js$script,redirect=google-analytics.com/analytics.js`~~

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.4.4 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
AdGuard Tracking Protection filter can more wide use redirect resources.

Adguard Annoyance may need add exeption + pure js rule to auto accept in supported addons/apps.

**Comment by Alex-302** [comment]
Cannot find thet message. Please show direct link with screenshot.

**Comment by THEtomaso** [comment]
I've already posted direct links in the first post, under "**Examples**".
There's also a screenshot right below!

**Comment by Alex-302** [comment]
Ok, I see. Better make big screenshots.
