### ISSUE TITLE
Videos on golem.de incorrectly blocked by AdGuard German filter

### ISSUE THREAD

**Issue by d4k0** [AdguardTeam/AdguardFilters#107940]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

2.0.34.40

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.golem.de/news/xbox-cloud-gaming-wenn-ich-gross-bin-moechte-ich-gerne-netflix-werden-2201-162506.html

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, Online Malicious URL Blocklist

### Add your comment and screenshots

1. Comment
- **Current behaviour:**

Videos on golem play only sound (no image) when the AdGuard German filter is active (I'm using the optimized version in uBlock Origin, but the normal version has the same problem). Works fine when the filter is inactive.

- **Expected behaviour:**

Video plays visibly in the video player

- **Steps to reproduce the problem:**

Go to [this article](https://www.golem.de/news/xbox-cloud-gaming-wenn-ich-gross-bin-moechte-ich-gerne-netflix-werden-2201-162506.html), make sure the AdGuard German filter is active, and start the video.

- **Probable cause:**

It seems that the following rule is causing the problem as uBlock Origin's network monitor says that it blocks something:

`||damoh.*.de^$xmlhttprequest,domain=desired.de|giga.de|golem.de|pcgames.de|spieletipps.de|stern.de|t-online.de|vox.de|wetter.de`

If I deactivate the rule in uBlock Origin (using `@@`), the video plays just fine.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![2022-01-23_17-53-23](https://user-images.githubusercontent.com/10982825/150689123-2c6a3826-56d3-4b02-9fe4-ea9aa5e5ece3.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It seems something is wrong with player in Firefox.
In Chrome everything is fine, in FF - player does not work
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/151594117-90bd78d1-bde6-425e-afbf-4950ba7794c2.png)

</details>
