### ISSUE TITLE
developer.helpscout.com

### ISSUE THREAD

**Issue by lol768** [AdguardTeam/AdguardFilters#107957]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

2.1.7.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://developer.helpscout.com/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

```
![Adblock Plus 2.0]
! Checksum: e9/7vPR/02DEn0Idc/ZGpQ
! Title: AdGuard Annoyances filter
! Description: Blocks irritating elements on web pages including cookie notices, third-party widgets and in-page pop-ups.
! Version: 2.1.7.0
! TimeUpdated: 2022-01-20T20:30:36+00:00
! Expires: 4 days (update frequency)
! Homepage: https://github.com/AdguardTeam/AdGuardFilters
! License: https://github.com/AdguardTeam/AdguardFilters/blob/master/LICENSE
```

Rule:

```
||helpscout.net^$third-party
```

This isn't an annoyance, it's a support tool. You can use it for sending emails/starting live chat sessions to get help on a website.

It's not a feedback tool either a la Hotjar... in some cases it's the _only_ support avenue a website has. Do we really want to block that?

![image](https://user-images.githubusercontent.com/2552726/150698194-2dbff03b-377b-46f5-94a7-b3668fbf96d2.png)

### Privacy

- [X] I agree to follow this condition

**Comment by lol768** [comment]
Collateral damage from e86d9b10b2651c67ff062105d1c50b05ca8e4d4a ref #81772 ?

**Comment by lol768** [comment]
See also 107370

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/107959
