### ISSUE TITLE
[Android] Ads in Textra app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1080]
https://play.google.com/store/apps/details?id=com.textra&hl=en

http logs [debug.txt](https://github.com/AdguardTeam/ExperimentalFilter/files/59364/debug.txt)
![image](https://cloud.githubusercontent.com/assets/15856304/11743560/2867934e-a011-11e5-8589-2ea71f77ee14.png)

EYG-502-90103

**Comment by Alex-302** [comment]
It isn't looks like HTTP log. I don't see GET requests.
Does it repeated with disabled network and cleared cache?

**Comment by evgeniy-ADG** [comment]
Just found com.textra in pref.net.exclusions

**Comment by evgeniy-ADG** [comment]
Может, это все потому, что программа в исключениях? тут снова о этой проблеме пишут. дайте знать, пожалуйста.

**Comment by Alex-302** [comment]
Возможно. Там какая-то проблема с MMS.
OFJ-215-48318

@ameshkov Не исправляли ещё эту проблему?
```
Hello, I'm reporting MMS does not send correctly when ad guard is enabled with app ad blocking enabled.
the messaging app I'm using is Textra .
Thank you
```

**Comment by Alex-302** [comment]
evgeniy-ADG пусть опишут как повторить проблему. С смс всё норм, только ммс не отправляются?(или что с ними за проблема?)

**Comment by evgeniy-ADG** [comment]
вопрос исклюительно в рекламе, в ее наличии :) таск как раз по этому поводу.

**Comment by Alex-302** [comment]
Приложение ж не просто так исключили. Можешь уточнить у юзера из OFJ-215-48318 в чём конкретно была проблема, и как её повторить?
В любом случае, фейсбучную adchoises не заблокировать, пока не будет поддержки HTTPS.

**Comment by Bohdan-SUP** [comment]
More logs here - FRS-674-77236

**Comment by ameshkov** [comment]
Чуваки, если не исключать это приложение, то начинаются проблемы с MMS.

**Comment by ameshkov** [comment]
Временное решение: юзер может убрать это приложение вручную, отредактировав pref.net.exclusions.

**Comment by evgeniy-ADG** [comment]
> I did as you said, textra works fine and the ads disappeared. Thank you! :-)
> I will let you know if any problems will occur in the future so you may consider remove textra from that list as default. 
>
