### ISSUE TITLE
Fake Brazilian bank website

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdguardFilters#108571]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.9 nightly 7

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://ston-app.com/login/login.php?prog=0.238600398466418 and https://apps.validar-acesso.com/bc354730-80a5-11ec-ab5a-de1d701f700c

### What filters do you have enabled?

AdGuard Base filter, AdGuard Spanish/Portuguese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track header, Disable cache for third-party requests, Block WebRTC, Hide your User-Agent (specify in comment below, if used custom value)

### Add your comment and screenshots

The fake website to get account details and account security code.

1- Stone
Official site: [https://conta.stone.com.br/login](https://conta.stone.com.br/login)
Fake website:  [https://ston-app.com/login/invalido.php](https://ston-app.com/login/invalido.php) or [https://ston-app.com/](https://ston-app.com/)
![Captura de Tela (217)](https://user-images.githubusercontent.com/16819380/151642366-b3898b12-db4f-4840-a9e1-1de377539431.png)

2- Banco do Brasil 
Official site: https://www.bancobrasil.com.br or https://www.bancobrasil.com.br
Fake website: https://apps.validar-acesso.com/bc354730-80a5-11ec-ab5a-de1d701f700c
![Screenshot_20220128-225145_Samsung Internet](https://user-images.githubusercontent.com/16819380/151642748-d271484f-7db9-41f6-b703-af4a532ca27a.jpg)
![Captura de Tela (218)](https://user-images.githubusercontent.com/16819380/151642762-562f742d-4006-4d5c-bf08-a9c187418e0c.png)

### Privacy

- [X] I agree to follow this condition

**Comment by eduardoaddad** [comment]
@DandelionSprout , @Alex-302

**Comment by NaylyaM** [comment]
Blocked.

**Comment by eduardoaddad** [comment]
> Blocked.

Fake from Stone Bank website is still active 

![Screenshot_20220202-075702_Samsung Internet.jpg](https://user-images.githubusercontent.com/16819380/152141005-33d79613-8a5b-45b4-b448-3c5f2d88cce1.jpg)
