### ISSUE TITLE
Microsoft Office (Android)

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#108775]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

Nightly v4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.microsoft.office.officehubrow

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

||self.events.data.microsoft.com^

<details><summary>Screenshot:</summary>

![Screenshot_20220131-012048925](https://user-images.githubusercontent.com/87330832/151708101-bd8e88b5-eb5c-4d9b-b045-62dd9d25acf6.jpg)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by TPS** [comment]
@Alex-302 This breaks sync (autocomplete, files, &c) across _all_ Microsoft products.  Search GitHub for `self.events.data.microsoft.com` for _many_ complaints @ similar blocklists.  Could you revert? 🙇🏾‍♂️

IMHO, those who really want it can add it themselves & deal w/ the sync problems themselves.

**Comment by TPS** [comment]
Also, this was previously reverted in https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/825 for the same reason, IIUC.

**Comment by Alex-302** [comment]
Damn. Removed.

**Comment by TPS** [comment]
Thanks!  Is there a process by which this sort of thing can be avoided?  Maybe a list of rejected filters & reasons that can be consulted before we open requests?
