### ISSUE TITLE
[NSFW] sxyprn.*

### ISSUE THREAD

**Issue by BottledSoda** [AdguardTeam/AdguardFilters#108925]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS, AdGuard for iOS

### AdGuard version

4.3.1(919)

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

`sxyprn. net` / `sxyprn. com`

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, AdGuard Social Media filter, EasyPrivacy

### Add your comment and screenshots

https://github.com/AdguardTeam/AdguardFilters/issues/96886 https://github.com/AdguardTeam/AdguardFilters/issues/87580
Please try adding a rule / rules for blocking as many third-party connections for `sxyprn.*` and please add additional anti-popup filters.
(AG Pro / Premium on iOS 15+ seemingly have advanced blocking features)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Added `.net`
