### ISSUE TITLE
9am.ro

### ISSUE THREAD

**Issue by BottledSoda** [AdguardTeam/AdguardFilters#109057]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.17

### What type of problem have you encountered?

AdGuard gets detected on a website, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://www.9am.ro/stiri/Politica/354877/Ionut-Stroe-In-acest-moment-PNRR-nu-poate-fi-modificat-9-4-din-PIB-pentru-pensii-suficient-si-pentru-cresteri.html`

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

Are:
```
9am.ro##.optanon-show-settings
9am.ro##[class="endOfArticleItems"]
```
good filters?

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
> 9am.ro##[class="endOfArticleItems"]

Blocks too much.

Fixed annoyances, anti adblock in player, ad leftovers.
