### ISSUE TITLE
com.whatsapp

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#10901]
***Description***:
* **Current behaviour**: 

Refuses to work with protection enabled.
HTTPS filtering is disabled.
App is correctly given access to the internet through AdGuard's App Management menu.

* **Expected behaviour**: 

Should work.

***Steps to reproduce the problem***:

1. Try to log in to application with protection enabled.

***System configuration***

**Debug logs**
[debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/1691469/debug.txt)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 6.0.1
Browser:                               | Not applicable
AdGuard version:                       | 2.10.176
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Russian filter", "Mobile Ads filter"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-speed
HTTPS filtering (Android only):        | Off
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 1748717

**Comment by Alex-302** [comment]
does it work with disabled filters?

**Comment by BlazDT** [comment]
Not reproduced on my Android 7.1.1

**Comment by BlazDT** [comment]
@akmLaVx 
Is it still reproduced?

**Comment by akmLaVx** [comment]
Nope, we've got nothing; the customer is silent.
