### ISSUE TITLE
rossmann.de breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#109135]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.17

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.rossmann.de/de/tier-winston-nature-mit-ente-und-huhn/p/4305615592855

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, Filter unblocking search ads and self-promotion

### Add your comment and screenshots

I can't write reviews

<details>
<summary> Screenshot: </summary>

<img width="571" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/152212301-721f3763-8e8f-4862-852a-55c516223be0.PNG">

</details>

Whitelisting `mpsnare.iesnare.com/snare.js` works for me (redirect will not work, i already tested it it breaks the publishbutton)

### Privacy

- [X] I agree to follow this condition

**Comment by JobcenterTycoon** [comment]
@Alex-302 

the issue still persist. Whitelisting `mpsnare.iesnare.com/snare.js` works. Its a big site with millions of visititors per month

**Comment by AdamWr** [comment]
Fixed.
