### ISSUE TITLE
AdGuard DNS and AdGuard for Android not able to filter ads for SSG

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardFilters#109103]
@tosouravbhor commented on [Tue Jan 25 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4097)

I have set up AdGuard for DNS and AdGuard for Android to block the Ads traffic to be loaded in SSG, but I fail to block ads every time. The default filters are not enough to detect and block the advertisements. Please resolve it ASAP.

---

@Chinaski1 commented on [Tue Jan 25 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4097#issuecomment-1021188504)

Hello there!

Please describe your issue in more detail. Which `SSG` are we talking about?

---

@tosouravbhor commented on [Tue Jan 25 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4097#issuecomment-1021191046)

SSG or Step Set Go is an Indian fitness tracking app. It does have advertisements inside to which users get rewarded for the actions they ask us to take through in-app video ads. The ads themselves are very annoying, and being a premium member of AdGuard, I expect them to be blocked completely. 

---

@Chinaski1 commented on [Mon Jan 31 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4097#issuecomment-1025502728)

Could you please provide a link to the application?

But usually, if you find a missed ad, it is advisable to [send a report](https://kb.adguard.com/en/technical-support/reporting-tool#Android) to the filter developers. They will review your complaint and block the missed ads.

---

@tosouravbhor commented on [Mon Jan 31 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4097#issuecomment-1025601129)

Here is the link for the app, https://play.google.com/store/apps/details?id=com.pepkit.ssg and the website for the same to learn more is here, https://www.stepsetgo.com/

**Comment by Sergey-Lyapin** [comment]
Hello @tosouravbhor
This app doesn't available in my country, I tried APK but it didn't work.
Could you reproduce the issue and send here a screenshot of AdGuard's filtering log? (filter it by app's name)

**Comment by tosouravbhor** [comment]
![Screenshot_20220302-232258](https://user-images.githubusercontent.com/75004469/156553210-179e8545-1809-4b0e-a378-a05c4d80b7bd.jpg)
![Screenshot_20220302-232306](https://user-images.githubusercontent.com/75004469/156553217-7c23b8d7-29cb-4585-ac6a-2fd6779f779b.jpg)
![Screenshot_20220302-232645](https://user-images.githubusercontent.com/75004469/156553219-3e9d544b-6254-4e32-ac59-44a00ee4db89.jpg)

**Comment by Alex-302** [comment]
I see nothing suspicious. Maybe ads loaded from the main domain.

**Comment by tosouravbhor** [comment]
Nothing suspicious I want to see the content of apps and not just ads, and that is what I believe AdGuard should ideally do.

**Comment by infinitewaveparticle** [comment]
@tosouravbhor Alex302 wasn't referring to your activity as suspicious; he was saying that there's nothing obvious loading the ads which means the app is likely loading ads from the same servers that it's loading its regular content from. To fix this you'll need to root your phone so you can use https filtering for all your apps.
