### ISSUE TITLE
powerclicks.xyz

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#109375]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.7.0.1094

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://powerclicks.xyz/P7w6J

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

countdown on step 2 seemingly freezes when out-of-focus

### Privacy

- [X] I agree to follow this condition

**Comment by BottledSoda** [comment]
oh, and possibly some sort of disappearing popup

**Comment by BottledSoda** [comment]
and popMagic
