### ISSUE TITLE
sleazyneasy.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#10946]
**Site**: https://www.sleazyneasy.com/videos/1125029/huge-cock-hard-fucking-carolina-sweets-shaved-pussy/

**Issue**: Please remove the ad left over text and empty ad banner at the bottom of the page.

**Screenshot**: http://prntscr.com/i9kogm

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
Fixed, alongside mobile site and data miner.

**Comment by Nzzyme** [comment]
Thanks! Can you also remove this element ("X") see on the video player.
http://prntscr.com/id36cb

Thanks

**Comment by Alex-302** [comment]
fixed

**Comment by Nzzyme** [comment]
Now, I am seeing an ad on the player
Site: https://www.sleazyneasy.com/videos/102402/wtf-you-have-never-seen-anything-as-sick-as-this/
Screenshot: http://prntscr.com/ids67m

Also seeing the string "Ad" on this page
Site: https://www.sleazyneasy.com/
Screenshot: http://prntscr.com/ids9hr

**Comment by BlazDT** [comment]
Fixed.

**Comment by nirboren** [comment]
It looks like there has been a mistake with this commit classifying Spark as miner or Ad provider.

Spark is NOT a miner, nor an Ad provider. It's a SAAS that provides a platform to improve the user video experience and provides video previews, video thumbnails, video suggestions and more.
Check http://holaspark.com

With regards to the Ad complain above,  Spark DOES NOT stream any Ad. Ads come directly from the publishers.

The commit you did blocked the entire Spark infrastructure (servers and player): https://github.com/AdguardTeam/AdguardFilters/commit/5e06f9818115d83c707c2355dc1ad18dbc1044ca

+||player.h-cdn.com/loader.js?customer=
+||zagent*.h-cdn.com^$third-party

Can you please remove the above 2 lines from the list?

**Comment by ameshkov** [comment]
@BlazDT @Alex-302 guys, blocking a CDN is simply wrong, plz fix it.

**Comment by Alex-302** [comment]
removed
```||player.h-cdn.com/loader.js?customer=
||zagent*.h-cdn.com^$third-party```

**Comment by Nzzyme** [comment]
Hi, can you check this link

https://www.sleazyneasy.com/videos/1551009/sharon-gets-her-big-ass-penetrated/

After the entire video has completed, seeing a "X" symbol on the video player.

http://prntscr.com/ihhhvf

**Comment by BlazDT** [comment]
After ad hidden.

**Comment by Nzzyme** [comment]
Seeing pop-ups when clicking on the player. Can you please check?

**Comment by BlazDT** [comment]
Not reproduced, which exact link did you try?

**Comment by Nzzyme** [comment]
Checked again and still see pop-up. Try moving the slider on the video player

https://www.sleazyneasy.com/videos/1092549/arabian-babe-got-her-tight-wet-pussy-bang-in-different-positions/


Screenshot: http://prntscr.com/okrjmt
