### ISSUE TITLE
Нет кнопок на http://forum.na-svyazi.ru/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1095]
При включенной программе, нет кнопки Редактировать на http://forum.na-svyazi.ru/?showtopic=2221238&st=0&p=15466640#entry15466640

вкл
![image](https://cloud.githubusercontent.com/assets/15856304/11766742/5e314960-a19d-11e5-9249-56914e27cc1f.png)

выкл
![image](https://cloud.githubusercontent.com/assets/15856304/11766739/4ce2aff0-a19d-11e5-8db5-943a68af3c62.png)

фильтры
![image](https://cloud.githubusercontent.com/assets/15856304/11766744/6f102102-a19d-11e5-85a3-c0228d533288.png)
JUF-989-44977

**Comment by Alex-302** [comment]
У меня этой кнопки нет. Наверное нужно проявлять активность на форуме.
Запросите удалённый доступ, или попросите сделать скрин кода этой кнопки.

**Comment by drugoisport** [comment]
Готов предоставить удаленный доступ

**Comment by drugoisport** [comment]
Можно через телеграмм связаться
@drugoisport_RAUL

**Comment by evgeniy-ADG** [comment]
@Alex-302 у клиента проблема осталась, готов предоставить удаленный доступ.

**Comment by Alex-302** [comment]
ок, кидай ID и пароль, подключусь

**Comment by drugoisport** [comment]
Запустил тимвьювер, ид и пароль отправил на почту

**Comment by Alex-302** [comment]
@drugoisport 
не вижу. Можно прямо сюда. Подключусь - удалю

**Comment by drugoisport** [comment]
id 653 732 345
пароль 9829

**Comment by drugoisport** [comment]
сейчас обновлю

**Comment by Alex-302** [comment]
Исправлено

**Comment by drugoisport** [comment]
ура!

**Comment by drugoisport** [comment]
опять поломалось редактирование

**Comment by evgeniy-ADG** [comment]
@Alex-302 снова сломалось, говорят. готовы на ТВ.

**Comment by Alex-302** [comment]
В понедельник в любое время.

**Comment by Alex-302** [comment]
На пробу
```
forum.na-svyazi.ru$@$td[height="70"][align="center"]
или
forum.na-svyazi.ru#@##userlinks
или
@@||forum.na-svyazi.ru^$content
```

**Comment by drugoisport** [comment]
ок


>Пятница, 16 декабря 2016, 23:13 +03:00 от Alex <notifications@github.com>:
>
>В понедельник в любое время.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением, Сергей Семенов
тел. 8(8352) 44-22-30

**Comment by drugoisport** [comment]
не прокатило


>Пятница, 16 декабря 2016, 23:15 +03:00 от Alex <notifications@github.com>:
>
>На пробу
>forum.na-svyazi.ru$@$td[height="70"][align="center"]
или
forum.na-svyazi.ru#@##userlinks
или
@@||forum.na-svyazi.ru^$content
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением, Сергей Семенов
тел. 8(8352) 44-22-30

**Comment by Alex-302** [comment]
Тогда нужен удалённый доступ или аккаунт, с которым можно повторить.

**Comment by drugoisport** [comment]
был в отъезде, в пятницу в 22.00 удобно?


>Суббота, 17 декабря 2016, 1:14 +03:00 от Сергей Семенов <polosat1y@mail.ru>:
>
>не прокатило
>
>
>>Пятница, 16 декабря 2016, 23:15 +03:00 от Alex < notifications@github.com >:
>>
>>На пробу
>>forum.na-svyazi.ru$@$td[height="70"][align="center"]
или
forum.na-svyazi.ru#@##userlinks
или
@@||forum.na-svyazi.ru^$content
>>—
>>You are receiving this because you were mentioned.
>>Reply to this email directly,  view it on GitHub , or  mute the thread .
>
>
>С уважением, Сергей Семенов
>тел.  8(8352) 44-22-30


С уважением, Сергей Семенов
тел. 8(8352) 44-22-30

**Comment by Alex-302** [comment]
> в пятницу в 22.00

не очень. Лучше днём или в другой день.
Не пробовали определить какой фильтр приводит к проблеме?

**Comment by drugoisport** [comment]
С Новым Годом ))
Разобрался, проблема не в adguard, а в анти-баннере KIS.

**Comment by Alex-302** [comment]
ну что ж вы так) Надо было без Адгарда проверить.
