### ISSUE TITLE
[Android] Yahoo Fantasy Football

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1096]
Missed ad
![image](https://cloud.githubusercontent.com/assets/15856304/11767032/458dd7e2-a1a8-11e5-95d9-ef32a1a1b2c8.png)
HTTP log [debug (2).txt](https://github.com/AdguardTeam/ExperimentalFilter/files/60452/debug.2.txt)
  "enabledFilterIds" : [ 2, 3, 5, 11 ],
  "filteringQuality" : "FULL",

LER-222-12413

**Comment by Alex-302** [comment]
Нужна ссылка на приложение и описание как добраться до баннера.
Нашёл только Yahoo Fantasy Sports, но баннера не увидел.

**Comment by evgeniy-ADG** [comment]
https://play.google.com/store/apps/details?id=com.yahoo.mobile.client.android.fantasyfootball&hl=en

Да, это оно. В его логах ничего такого не видно?

**Comment by Alex-302** [comment]
Видно кучу заблокированного. Но реклама может и с их домена грузиться, либо быть встроенной.
