### ISSUE TITLE
Strange ad on Goggle Chrome NewTab page

### ISSUE THREAD

**Issue by Himitsu1990** [AdguardTeam/AdguardFilters#110302]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.8

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

chrome://newtab

### What filters do you have enabled?

AdGuard Base filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Experimental filter, EasyList China, EasyList Czech and Slovak, EasyList Italy, EasyList Lithuania, Liste AR, Icelandic ABP List, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Dandelion Sprout's Nordic Filters

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track header

### Add your comment and screenshots

1. At Google Chrome v98.0.4758.82 new tab (Yes, "chrome://newtab" is a correct URL) page, there is now an annoying ad. If I look page code the is a strange block "ntp-middle-slot-promo" that i can't block. 

<details><summary>Screenshot:</summary>
https://user-images.githubusercontent.com/68761515/153743660-640ec3e4-614c-4565-8dc9-ef55c315f1ee.png
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Himitsu1990** [comment]
What rule should I create in AdGuard to try to block "ntp-middle-slot-promo" on new tab?

**Comment by Alex-302** [comment]
@Himitsu1990 I don't see that button.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/153866253-dc9c886b-8e98-422c-9caf-8c2eb37b6e97.png)

</details>

Please test in user rules:
`||google.com/async/newtab_promos`
