### ISSUE TITLE
May be able to uncomment ||amazon.*$removeparam=ref

### ISSUE THREAD

**Issue by Gitoffthelawn** [AdguardTeam/AdguardFilters#110571]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

-

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://smile.amazon.com

### What filters do you have enabled?

AdGuard URL Tracking filter

### Add your comment and screenshots

In the file `https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt`, the following filter is commented out because it reportedly "breaks adding article to basket when viewing all offers":  
  
`
||amazon.*$removeparam=ref
`

I tested this filter, and I did not experience this issue.  Thus, it's possible this filter can be uncommented.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@BlazDT Please take a look.

**Comment by BlazDT** [comment]
Currently it seems to work on the article I experienced the issue before, will uncomment and check later again

**Comment by BlazDT** [comment]
Had the previous whitelist still in rules, therefore it was working. I added the whitelist rule. When more issues appear with the block rule, have to disable again.
