### ISSUE TITLE
freecodecamp.org tracking

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#110697]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.17

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.freecodecamp.org/news/the-react-cheatsheet/

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, Filter unblocking search ads and self-promotion

### Add your comment and screenshots

<img width="513" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/154355255-c812839f-1b4d-45f1-b8be-830d10fb70fb.PNG">

There is tracking on their site from `da.ta.un.lo.ck.er` which is unblocked. The proxy enpoint (tracking sub domain) get fast changed after it gets blocked and they use a proxy (cloudflare) to hide the tracking sub domain from Adguard CNAME so the solution https://github.com/AdguardTeam/cname-trackers not working

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not sure about CNAME, probably just a proxy. Do you remember previous domain?
