### ISSUE TITLE
[feature] [new] new twitter popup blocking viewing posts to block

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardFilters#111044]
@hacknorris-aka-penguin commented on [Tue Feb 15 2022](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1981)

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

twitter recently updated their webapp blocking viewing profiles without account (like this ↓ )
![image](https://user-images.githubusercontent.com/97974194/154137644-398db8e4-c5c4-4a96-91c7-288b4f4be86a.png)

it happens after 2 minutes or scrolling fast thru 10 posts.

### Proposed Solution

adding new default rules to adguard default list of annoyances and hiding this popup while allowing wieving full profile without account

### Alternatives Considered
alternatively? probably visually hiding this popup but blocking scrolling if not possible to stop this

---

@hacknorris-aka-penguin commented on [Tue Feb 15 2022](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1981#issuecomment-1040728463)

if something - this screenshot is not an ad here but my old account which got suspended because i sweared at someone (and no im not gonna delete posts). and yes it also blocks me from visiting my profile :'D did this in incognito

anyways - who would advertise muted account? lol

**Comment by BlazDT** [comment]
Please check these rules:

`twitter.com#?##layers > div[class] > div[class]:has(> div[class] div[role="button"] > div[dir="auto"] > span > span:contains(ookies))`
```
twitter.com#?#div[role="dialog"] div[role="group"]:has(> div[data-testid="sheetDialog"])
twitter.com#$#html { overflow: visible !important; }
```

First rule is for cookies, for me they did not break something (but I am not a heavy twitter user).

**Comment by hacknorris-aka-penguin** [comment]
not that i want. everything works fine at me on my mobile (fritter wrapper). i can view. im just saying about adding it to one of preinstalled lists...

**Comment by BlazDT** [comment]
I posted the rules for you to test and check if anything is broken. If nothing is broken, they get added to Annoyances filter.

**Comment by hacknorris-aka-penguin** [comment]
works very correctly as for a user (i use firefox as i said). scrolled to the bottom finally without having to open my mobile (to use wrapper which was using their api to fetch posts). finally. FINALLY. yes i think you can add but i didnt tested neither in chrome, opera, edge or safari sadly...

**Comment by BlazDT** [comment]
Just checked again and it is not possible to add as it breaks "follow" button when not logged in. So only added cookie rule.
