### ISSUE TITLE
legitimate videos served by firework are getting blocked

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#111021]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard Content Blocker, AdGuard DNS, AdGuard for Android, AdGuard for iOS, AdGuard for Mac, AdGuard for Safari, AdGuard for Windows

### AdGuard version

4.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, Chrome, Safari, Microsoft Edge, Opera, Yandex Browser

### Which device do you use?

Desktop

### Where is the problem encountered?

https://in.sugarcosmetics.com/

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

https://firework.com/us/ is a video-streaming platform. It provides some advertising features and probably that's why their domain ended up in the filter lists. However, it is also used for serving legitimate videos, and currently, we're breaking this.

Example: https://in.sugarcosmetics.com/

There's a "Sugar Streaming" block there that is blocked when AdGuard (or AdGuard DNS) is used:
![image](https://user-images.githubusercontent.com/5947035/154862943-23316ef7-c772-4be4-8c6b-17fc86498255.png)

It seems that the problem is in blocking these three domains: 
```
asset.fwcdn2.com
fireworkapi.com
asset.fireworktv.com
```

Also, it seems that they have separate domains for tracking and advertising purposes: `fwpixel.com`, `fireworkanalytics.com` and `fireworkadservices.com`.

Please check the information above, if you can confirm it, we should unblock domains that serve normal video content.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Reported to Easylist.

**Comment by ameshkov** [comment]
@Alex-302 can we at least temporarily have exclusions for this?

**Comment by Alex-302** [comment]
Yes.

**Comment by ryanbr** [comment]
This ad video service masquerading as a fake social network, there is more cases where they are used as invideo ads, than anything legit which is why its blocked

**Comment by ameshkov** [comment]
> This ad video service masquerading as a fake social network, there is more cases where they are used as invideo ads, than anything legit which is why its blocked

Could you please share some examples? The content I am seeing on that website seems legitimate, is it not possible to distinguish the cases?

**Comment by ryanbr** [comment]
A bit late here but, `https://www.bthirteen.in/kehne-ko-humsafar-hai-season-3-trailer-review/`  Just an an firework ad slideshow at the bottom, and on the frontpage of `https://wordandsole.com/`  They use the same domains among to host, I don't think they see any difference between semi-legit vs ad slideshows which is why it remains blocked

**Comment by ameshkov** [comment]
@ryanbr 

Hmm, okay, I see, they have some Taboola/Outbrain vibe.

It seems that legit e-commerce examples use this URL to load content: `||fireworkapi.com/embed/v2/playlists/` (the content there looks like it was uploaded by the publisher).
While these Taboole-vibe ones use this `||fireworkapi.com/embed/v2/publisher_clients/`

@Alex-302 let's start slow and have that single rule, for now. If there're more reports on them, we'll extend the list

**Comment by Alex-302** [comment]
Done.

**Comment by SyedSan1** [comment]
> A bit late here but, `https://www.bthirteen.in/kehne-ko-humsafar-hai-season-3-trailer-review/` Just an an firework ad slideshow at the bottom, and on the frontpage of `https://wordandsole.com/` They use the same domains among to host, I don't think they see any difference between semi-legit vs ad slideshows which is why it remains blocked

Hi **@ryanbr** 
In the past, there was no clear separation but as I shared before we have separated content CDN from ad CDN. As we recommended, we are happy to work with you guys to ensure that ads get blocked but the content should be allowed. So many websites are getting impacted with blanket block on content. 
It would really help if we can work together to update the easylist filter.

**Comment by ameshkov** [comment]
@SyedSan1 could you please explain what is the separation?

**Comment by SyedSan1** [comment]
fwcdn2 is for content only.
this is the ads one - http://fireworkadservices.com/

**Comment by ameshkov** [comment]
Ah, okay, so I got it right in the beginning then.

**Comment by TalKaz** [comment]
@ameshkov yes, you got it right.
One domain that we are using for content is still blocked: fwpub1.com
`<script async="" src="//asset.fwpub1.com/js/storyblock.js"></script>`
example can be found in this [page](https://whatstrending.com/alec-mapa-talks-about-how-to-celebrate-valentines-day-with-a-very-sordid-wedding/).
Can you help with unblocking this domain as well?
and in addition assist with getting this whitelisted in Easylist?

**Comment by ameshkov** [comment]
@TalKaz

We don't do whitelisting and we cannot assist with that. There's a separate Easylist repo and I suppose you need to convince @ryanbr that the domains in question aren't used for advertising purposes.

From what I saw there're some cases when your system is used primarily for serving publisher's content and that's why we're trying to be careful and not break these cases. There're also some other cases when the purpose of that block is not clear and can be categorized as advertising or an annoyance, and your last example falls there.

@Alex-302 Anyways, `asset.fwpub1.com` seems to be the same CDN as the other `asset.*` domains, shouldn't be blocked in the base filter.

**Comment by ameshkov** [comment]
@TalKaz regarding this last example, could you please explain the logic of the publisher? Why did they placed that block there and where does the content for it come from?

**Comment by ameshkov** [comment]
@TalKaz please correct me if I am wrong, just trying to understand this better: the publisher either uploads videos themselves or chooses to simply show some "trending" content (which is like embedding TikTok to their page). And those that opt to embed trending content would like visitors to engage with it so that they stayed on the page longer.

**Comment by TalKaz** [comment]
@ameshkov - that is correct. you got it right. they have an inventory for videos they found to be "trending".

**Comment by ameshkov** [comment]
@TalKaz got it, thank you.

Here's the usual policy in such cases:

1. Base filter is for blocking ads only and this content is not an ad.
2. This "trending" type of widgets we usually categorize as an "annoyance" since it distracts the user from the page's content and is not directly relevant to it. We usually add them to the "Annoyances" filter which some users opt to enable (it's not a default list, though).
3. The e-commerce widget is a part of the page's content and shouldn't be touched by any AdGuard filter.

If you could provide a way to differentiate e-commerce cases from others, we could just follow the policy. If there's no way to do that, we'll have to decide what to do with the annoyances filter. It can be either block all / unblock on a per-site basis or vice-versa.

**Comment by SyedSan1** [comment]
Hi @ameshkov 

Majority of our partners fall into the e-commerce category. They all should have their own content and should be using the fwcdn2. Thank you for unblocking this.

fwpub1 link that you categorize as "annoyance" is typically the type of content on TikTok or IG. Not sure if you saw the announcement from YouTube but they are also looking to launch shoppable short videos this year.
We totally understand if you'd like to filter this out. The challenge is that as a video tech provider, we don't always know how a partner will start using the tech. If it help, we can find ways for you to identify the "annoyance".
Please let us know how we can help you identify content, annoyance and ads correctly. Thank you.

**Comment by SyedSan1** [comment]
@ryanbr 
We can perhaps take similar approach as Andrey/ AdGuard. We can help you identify content vs. annoyance vs. ads. You can unblock the content and block the ads/ annoyance, so that customers don't have bad experience? 
Can you please help open up the Easylist issue we reported earlier [here](https://github.com/easylist/easylist/issues/9588)?

**Comment by ameshkov** [comment]
> fwpub1 link that you categorize as "annoyance"

Ah, okay, I got it. Note, that we don't actually block that domain. As I understand, it does not matter from which CDN the code comes anyway.

> If it help, we can find ways for you to identify the "annoyance".

If there was an easy way to prevent showing certain "channels" (trending for instance), it would be ideal and we could flexibly choose what to block depending on the lists' policies.

**Comment by ryanbr** [comment]
Even if there a separate category, then every firework embed will be classed as annoyance and not advert. Why class it as an advert when it'll be blocked, when you can adjust the url "as an annoyance" to get around it.

**Comment by ameshkov** [comment]
@ryanbr 

> Even if there a separate category, then every firework embed will be classed as annoyance and not advert. Why class it as an advert when it'll be blocked, when you can adjust the url "as an annoyance" to get around it.

Here's what I am seeing so far:
1. The Firework's videos by themselves don't count as adverts, they don't lead to some outside advertiser (they can be rather annoying though, see point 3).
2. There are advertising videos that are mixed into the feed which can be successfully blocked by blocking one ad domain.
3. Some of the Firework's videos can be counted as an "annoyance", but currently, there's no easy way to distinguish them from relevant videos run by the website itself (like in this issue description).

AdGuard is already blocking adverts and letting widgets with relevant videos work.

Ideally, we would like to handle all three cases properly (block ads, block annoyances for people that choose to use that filter, keep normal videos).

**Comment by SyedSan1** [comment]
@ryanbr 
The above is correct summary from @ameshkov 
1) Our video content by themselves are not ads. This is where the industry is headed. I worked at Samsung prior to this role, and videos are considered a 5G use case. We expect every website, app, car dashboard to adopt videos in near future.
2) We separated ad domain for ads to help with blocking. 
3) If there is anything that you categorize as 'annoyance', we can work with you to help with blocking.

All we ask is to not block content because that results in bad experience for many of our customers and end users.
Please let us know.
