### ISSUE TITLE
AdGuard Regex list blocking domain required for Azure

### ISSUE THREAD

**Issue by BillTrovalds** [AdguardTeam/AdguardFilters#111344]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

AdGuard Home Version:  v0.107.3

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/RiskyUsersBlade

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. Was getting an error in AAD. Checked the logs and Adgaurd regex list was blocking the following domain: main.iam.ad.ext.azure.com
2. Whitelisting the domain resolved the issue

3. Screenshots
<details><summary>Screenshot 1:</summary>

![azure_error_agh](https://user-images.githubusercontent.com/23534392/155612740-9863e92e-6a82-4807-bedc-ee2f63dddf99.png)

</details>

<details><summary>Screenshot N:</summary>

</details>
#109470

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Not seeing any regex rule in the thread you linked, only element hiding rules.
