### ISSUE TITLE
sonicfoundry.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#11190]
***Description***:
* **Current behaviour**: 

Blocked by AdGuard Family Protection DNS
* **Expected behaviour**: 

Site is safe, shouldn't be blocked

***Steps to reproduce the problem***:

Visit the site w/AdGuard Family Protection DNS turned on

***System configuration***

**Filters:**
English, Russian, Spyware, Adblock Warning Removal List, Mobile Ads

Information                            | Value
---                                    | ---
Operating system:                      | Windows 8.1 x64
Browser:                               | Chrome 64.0.3282.140
AdGuard version:                       | 6.2.437.2171
Filters enabled:                       | English, Russian, Spyware, Adblock Warning Removal List, Mobile Ads
AdGuard DNS:                           | Family Protection
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | 1752685

**Comment by Alex-302** [comment]
not reproduced
