### ISSUE TITLE
[android] gReader

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#112]
Does not block ads in gReader

**Comment by evgeniy-ADG** [comment]
@Alex-302 

https://github.com/AdguardTeam/ExperimentalFilter/issues/112
https://play.google.com/store/apps/details?id=com.noinnion.android.greader.reader&hl=en

белая строка от рекламы, она убирается?
http://prntscr.com/b191c9

**Comment by ameshkov** [comment]
@evgeniy-ADG слушай, а если хттпс-фильтрацию отключить, будет она?

**Comment by Alex-302** [comment]
Без фильтрации HTTPS он никуда не делся. Не понятно, что с ними делать.

**Comment by vgavrish** [comment]
@Alex-302 
сейчас тот же вопрос) можно както убрать?
лог https://yadi.sk/i/gE0NiMpv33Akzs
время 9-43

**Comment by Alex-302** [comment]
Да пробовал, не выходит. Наверное какой-то костыль нужен для борьбы с такими остатками(а может универсального средства и нет)
