### ISSUE TITLE
www.flightradar24.com

### ISSUE THREAD

**Issue by DesertBear** [AdguardTeam/AdguardFilters#112173]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin (1.41.8), AdGuard Annoyances filter (2.1.11.52)

### What type of problem have you encountered?

Website or app doesn't work properly, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.flightradar24.com

### What filters do you have enabled?

AdGuard Annoyances filter, EasyList, EasyPrivacy, Peter Lowe's Blocklist

### Add your comment and screenshots

When accessing the website and clicking on an aircraft to get further details, because the cookie consent popup is blocked by the AdGuard Annoyances filter, the bottom of the details panel on the left (that contains further details/options) remains cut off.

When the filter is disabled in uBlock Origin and the cookie warning dialogue boxes dismissed, the details panel on the left appears correctly.  See below screenshots.

The issue it due to the following filter rules:

```
Filter       flightradar24.com##.important-banner--cookies
Filter list  AdGuard Annoyances 
Context      www.flightradar24.com
Type         dom
URL          https://www.flightradar24.com/UAE431/2b0da713
```

```
Filter       flightradar24.com##body div.fc-consent-root
Filter list  AdGuard Annoyances 
Context      www.flightradar24.com
Type         dom
URL          https://www.flightradar24.com/UAE431/2b0da713
```

```
Filter       flightradar24.com##body:style(overflow: visible !important;)
Filter list  AdGuard Annoyances 
Context      www.flightradar24.com
Type         dom
URL          https://www.flightradar24.com/UAE431/2b0da713
```

2. Screenshots
<details>Screenshot 1 – AdGuard Annoyances Filter Enabled (failed condition):</summary>

![untitled 01](https://user-images.githubusercontent.com/27423064/157047738-9a7619a3-ade2-4668-b1f3-eb6cda988a2a.jpg)

</details>

<details>Screenshot 2 – AdGuard Annoyances Filter Disabled (cookie dialogues visible):</summary>

![untitled 02](https://user-images.githubusercontent.com/27423064/157047761-63c41ea3-6130-4fc4-8e62-d339e348059d.jpg)

</details>

<details>Screenshot 3 – AdGuard Annoyances Filter Disabled and Cookie Dialogues Dismissed (details panel on the left is correct):</summary>

![untitled 03](https://user-images.githubusercontent.com/27423064/157047785-2c42e273-858e-4011-844c-e66168fbb86b.jpg)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Could you please check, if it works correctly when you add this rule:
```
flightradar24.com##+js(remove-class, has-banner, body.has-banner, stay)
```
 to "My filters"?

**Comment by DesertBear** [comment]
It appears to work correctly after adding that rule.  Thanks.

**Comment by AdamWr** [comment]
Okay, I have added this rule.
Filters update should be available now.

Thank you for your reply.
