### ISSUE TITLE
AdGuard for macOS blocks the iOS DirectTV Now app

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#11237]
***Description***:
* **Current behaviour**: 

The app's trafic is blocked by AdGuard for Mac working in HTTP Proxy mode. The network is configured as follows: iOS device (where this app is used) connected to iMac w/AdGuard working in HTTP Proxy mode.

The app: https://itunes.apple.com/us/app/directv-now/id1136238277?mt=8

* **Expected behaviour**: 

Shouldn't be blocked

***Steps to reproduce the problem***:

1. On a macOS device, run AdGuard as an outbound HTTP proxy
2. Configure the iOS device to proxy to internet through AdGuard on macOS device
3. Try to run the app

***System configuration***

**Logs:**
[adamsa_logs.zip](https://github.com/AdguardTeam/AdguardFilters/files/1707209/adamsa_logs.zip)

**Filters:**
English, Spyware, Social media, Annoyances, Mobile Ads, Safari, EasyList, EasyPrivacy, Fanboy's Annoyances, Adblock Warning Removal List, Anti - Adblock Killer | Reek, Fanboy Anti-Facebook List, Malware Domains, Spam404

Information                            | Value
---                                    | ---
Operating system:                      | iOS 11 (app host)  + macOS 10.13 (proxy host)
Browser:                               | N/A
AdGuard version:                       | 1.5.3 (macOS)
Filters enabled:                       | English, Spyware, Social media, Annoyances, Mobile Ads, Safari, EasyList, EasyPrivacy, Fanboy's Annoyances, Adblock Warning Removal List, Anti - Adblock Killer | Reek, Fanboy Anti-Facebook List, Malware Domains, Spam404
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 1747535

**Comment by evgeniy-ADG** [comment]
Let me know to which repro it should be moved to, AdGuard for macOS is running in the local proxy mode and this somehow blocks the DirectTV Now app.

**Comment by akmLaVx** [comment]
User has been notified.

**Comment by Alex-302** [comment]
If user does not see blocked requests, I don't need logs.  Try to disable all AdGuard extensions.
Could you check it on you end?
