### ISSUE TITLE
OKCupid app for iOS doesn't work with custom DNS

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#11231]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

> Today I changed the DNS on my router to the default AdGuard DNS. Afterwards, I tried using the OkCupid app on my iPhone and it told me that I didn’t have any network connection. I switched my phone from WiFi to cellular data and the app started working immediately. My phone is an iPhone 6S. My router is an ASUS RT-AC68P. I am including a screenshot from my phone showing what the OkCupid app said, and also a screenshot of the router’s admin GUI.

https://itunes.apple.com/us/app/okcupid-dating/id338701294?mt=8

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/35965787-a5c0f0c0-0cc4-11e8-8939-a1bb296ab327.png)

</details><br/>

***System configuration***

**Filters:** n/a

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | iOS, ASUS RT-AC68P
Operating system version (Android/iOS) | n/a
Browser:                               | n/a
AdGuard version:                       | n/a
Filters enabled:                       | m/a
Simplified filters (iOS only)          | n/a
AdGuard DNS:                           | Default
Helpdesk ID (if exists):               | 1755121

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by andreapx** [comment]
I see that this issue has been closed, but I still have this problem on Android (I've setup AdGuard DNS family protection on my router)

**Comment by Alex-302** [comment]
@andreapx could you disable this DNS on the router, setup it on iOS device and show blocked DNS requests? I can't install this app.

**Comment by andreapx** [comment]
Hi Alex,
I've an Android smartphone and I can't find the app on the Play Store.
I also use this filter with "Blokada", but unfortunately it doesn't have logs :(

**Comment by Alex-302** [comment]
>  I still have this problem on Android

but what is it?) Maybe I don't understand you)

**Comment by Alex-302** [comment]
But how can you reproduce it if you can't install this app?)

@Eugene-Savenko @zebrum could you, please, try to install this app?

**Comment by andreapx** [comment]
Wait wait, I think that there's been a misunderstanding.
I'm using the app OkCupid on an Android (8.1) smartphone.
Using the AdGuard family protection DNS on my router, the app OkCupid doesn't work.
On my smartphone I also use the app "Blokada" that has the option to use the AdGuard DNS and even with this option (using mobile data, not my home router WiFi) the app OkCupid doesn't work.
Unfortunately Blokada doesn't provide any log.
Using mobile data and with Blokada disabled, OkCupid works without any problem.
Andrea

**Comment by zebrum** [comment]
@andreapx I'm a little confused here what platform we are discussing. Please provide the link to the OkCupid app in play market.

**Comment by andreapx** [comment]
The app is this one: https://play.google.com/store/apps/details?id=com.okcupid.okcupid

**Comment by Alex-302** [comment]
@andreapx so Android + DNS(default or  family?) on the router?

**Comment by andreapx** [comment]
@Alex-302  correct, Android with DNS family on the router

**Comment by zebrum** [comment]
the problem is that for some reason I can't register in the app ) I'll try with VPN maybe.

**Comment by Alex-302** [comment]
Also can't register in the app.

**Comment by andreapx** [comment]
Why has the bug been closed? The problem persist.

**Comment by Alex-302** [comment]
Could you please create test account? We can't register.
