### ISSUE TITLE
Gravity.com

### ISSUE THREAD

**Issue by carlhancock** [AdguardTeam/AdguardFilters#112382]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS, AdGuard for Mac, AdGuard for Safari

### AdGuard version

4.3.3

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

gravity.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Annoyances filter

### Add your comment and screenshots

<comment>Please remove Gravity.com from AdGuardFilters.  In a prior life and under different ownership Gravity.com was acquired by AOL who eventually became Yahoo Ad Tech. However they no longer own the domain and it is no longer used for anything related to advertising, ad tech, tracking or analytics.  We purchased the domain name and plan on using it for our business.

We are trying to get it removed from any adblocker related lists before doing so.  Glad to provide more details confirming that we acquired this domain name.  But if you visit it in your browser you'll see it now redirects to our Gravity Forms product and is no longer owned by Yahoo Ad Tech.

The domain is currently included here:

https://github.com/AdguardTeam/AdguardFilters/blob/2c80da4070e9c7bfa7cc29274ed49cb7b7d5eb08/SpywareFilter/sections/specific.txt

Line 1402 where this rule exists:

||gravity.com^*/beacons/

I'd like to request that it be removed as it is under new ownership and is not being used for anything related to what AdGuard is designed to block.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Ok, looks like it's true)

**Comment by carlhancock** [comment]
Awesome thanks Alex!
