### ISSUE TITLE
chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/viewer.html

### ISSUE THREAD

**Issue by sunafterrainwm** [AdguardTeam/AdguardFilters#112350]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.17

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/viewer.html

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, Filter unblocking search ads and self-promotion

### What Stealth Mode options do you have enabled?

Send Do-Not-Track header

### Add your comment and screenshots

1. extension is https://chrome.google.com/webstore/detail/efaidnbmnnnibpcajpcglclefindmkaj
2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/59136112/157419287-d247fe96-b603-4737-8eb9-d86811dcf47c.png)

</details>

### Privacy

- [x] I agree to follow this condition

**Comment by Alex-302** [comment]
Need steps to reproduce. Not sure if AdGuard can break another extenstions, browser does not allow this.
