### ISSUE TITLE
Youtube share UI wrong blocking

### ISSUE THREAD

**Issue by zhenjie1999** [AdguardTeam/AdguardFilters#112359]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

adguard 7.9.1

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.youtube.com/watch?v=z4TVnbuy4Lw

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Japanese filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

I also reported to adguard windows github section
https://github.com/AdguardTeam/AdguardForWindows/issues/4157
adguard setting export file
[20220309_082043_adg_settings_7.9.3869.0.zip](https://github.com/AdguardTeam/AdguardFilters/files/8214537/20220309_082043_adg_settings_7.9.3869.0.zip)

![Screenshot 2022-03-09 082023](https://user-images.githubusercontent.com/75268245/157439207-d0a9fc8e-f8e9-4761-9f3d-78cf5010d40f.png)
![Screenshot 2022-03-09 081950](https://user-images.githubusercontent.com/75268245/157439212-43b2d627-658a-43fa-b13c-09d3a8fe12f6.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please disable AdGuard Social Media filter if you want to use social share buttons.
