### ISSUE TITLE
[Android] Missed ads in Аквариум рыбы Fish Live

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1124]
https://play.google.com/store/apps/details?id=com.baileyz.aquarium&hl=ru

HTTP requests [debug (3).txt](https://github.com/AdguardTeam/ExperimentalFilter/files/65730/debug.3.txt)

![image](https://cloud.githubusercontent.com/assets/15856304/11877113/e589979a-a4f5-11e5-8d3a-d032c7235431.png)
FRH-311-40911

**Comment by Alex-302** [comment]
Добавил
||doodlemobile.com/feature_server/fullScreen/get.php
пусть отпишется, не сломалось ли чего.

**Comment by evgeniy-ADG** [comment]
Спросил, ждём ответ.
