### ISSUE TITLE
canyoublockit.com cant use google translate bc adguard block its js

### ISSUE THREAD

**Issue by Karmylr** [AdguardTeam/AdguardFilters#112516]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.9.1 (build 3869, CL 1.9.43)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

canyoublockit.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>
![image](https://user-images.githubusercontent.com/69903376/157795094-9c0e2040-e18d-4947-9736-c7753ac84b04.png)

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
