### ISSUE TITLE
NYTimes articles vanish after a second

### ISSUE THREAD

**Issue by Wabrzezno** [AdguardTeam/AdguardFilters#112530]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlockOrigin 1.41.8

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.nytimes.com/2022/03/10/world/europe/russia-economy-ukraine.html

### What filters do you have enabled?

AdGuard Tracking Protection filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track header, Self-destruction of third-party cookies, Block WebRTC, Block Push API, Block Location API

### Add your comment and screenshots

1. Some (but not all) articles in the New York Times vanish after failing to download <code>https://www.nytimes.com/ads/parakeet.min.js</code>. It is an annoying ad script that makes GDPR/CCPA settings pop up, among other things, but it seems reading (non-live stream at least) articles is impossible without it.
2. I use uBlock Origin, but the problem lies not with uBO itself but the AdGuard Tracking Protection filter list, which blocks the script
3. I use the newest version of Bypass Paywalls Clean, but disabling the extension had no impact on downloading (or vanishing) of article content.
4. I haven't tried disabling cookies on the website yet, though it's unlikely to help given that a few scripts seem to collapse without Parakeet being downloaded. Maybe these scripts can be somehow disabled as well, but I don't know.

5. Screenshots
<details><summary>Screenshot 1 (devtools):</summary>

![image](https://user-images.githubusercontent.com/81221360/157848155-aa1bb103-4583-4eb8-8ca7-f36f13a07431.png)
</details>

<details><summary>Screenshot 2 (devtools):</summary>

![image](https://user-images.githubusercontent.com/81221360/157848311-8d5a2fd4-f073-4420-8d83-3d616bde3ab9.png)
</details>

<details><summary>Screenshot 3 (devtools):</summary>

![image](https://user-images.githubusercontent.com/81221360/157848389-416aa06f-9744-4806-82cc-9a43dedc38e7.png)
</details>

<details><summary>Screenshot 4 (blocked scripts, with parakeet):</summary>

![image](https://user-images.githubusercontent.com/81221360/157848790-21d83515-8144-4d20-9c46-718fc2aa8234.png)
</details>

<details><summary>Screenshot 5 (Parakeet allowed; the article does not vanish):</summary>

![image](https://user-images.githubusercontent.com/81221360/157849419-b64aa007-7bbc-4660-84f8-53c06a0a677b.png)

</details>

### Privacy

- [x] I agree to follow this condition

**Comment by AdamWr** [comment]
It has been fixed few hours ago - https://github.com/AdguardTeam/AdguardFilters/commit/fdc61a715a2d5235822d0c970e0538473ddfb320
Please update filters.
