### ISSUE TITLE
com.facebook.katana

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#11265]
***Description***:
* **Current behaviour**: 

Shows ads.

<details><summary>Ads:</summary>

![screenshot_2018-02-09-00-23-26-853_com facebook katana](https://user-images.githubusercontent.com/33634917/35997533-6f825806-0d22-11e8-98e0-559bc88bb69b.png)
![screenshot_2018-02-09-00-23-34-321_com facebook katana](https://user-images.githubusercontent.com/33634917/35997535-6f9f233c-0d22-11e8-8685-648a106715ba.png)
![screenshot_2018-02-09-00-23-41-993_com facebook katana](https://user-images.githubusercontent.com/33634917/35997536-6fc1c310-0d22-11e8-802d-a43d0819e065.png)

</details><br/>

<details><summary>Filtering Log screenshots:</summary>

![dnsrequestlog 2](https://user-images.githubusercontent.com/33634917/35997571-87d79c04-0d22-11e8-8687-97e17c384405.png)
![dnsrequestlog](https://user-images.githubusercontent.com/33634917/35997572-87f50208-0d22-11e8-84e2-dc2a9679b2d6.png)

</details><br/>

* **Expected behaviour**: 

Should not show ads

***Steps to reproduce the problem***:

Opening Facebook should suffice

***System configuration***

**Filters:**
"English filter", "Spyware filter", "Annoyances filter", "Mobile Ads filter", "Simplified domain names filter"

**Debug logs:**
[dbg.zip](https://github.com/AdguardTeam/AdguardFilters/files/1708750/dbg.zip)

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 7.1.1
Browser:                               | n/a
AdGuard version:                       | 2.10.176
Filters enabled:                       | "English filter", "Spyware filter", "Annoyances filter", "Mobile Ads filter", "Simplified domain names filter"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | Custom DNS: Google Public DNS, 8.8.8.8/8.8.4.4
Helpdesk ID (if exists):               | 1650671

**Comment by Alex-302** [comment]
It is impossible. FB app uses SSL Pinning.
