### ISSUE TITLE
docs.vmware.com

### ISSUE THREAD

**Issue by loyingEcu** [AdguardTeam/AdguardFilters#112615]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.9 nightly19

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://docs.vmware.com/cn/VMware-Workstation-Pro/16.2.3/rn/vmware-workstation-pro-1623-release-notes/index.html#%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82

### What filters do you have enabled?

AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Hide your search queries

### Add your comment and screenshots

||cookielaw.org^$third-party
The above rule in the annoying filter will cause access to docs.vmware.com to be blank 
![1](https://user-images.githubusercontent.com/22834701/157973565-728a872d-7ccf-4fe5-abdd-b51fc842641b.png)

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
