### ISSUE TITLE
veja.abril.com.br

### ISSUE THREAD

**Issue by pintassilgo** [AdguardTeam/AdguardFilters#112767]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.41.8

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://veja.abril.com.br/

### What filters do you have enabled?

AdGuard Spanish/Portuguese filter

### Add your comment and screenshots

1. Comment
The following filter
`abril.com.br##.square`
from `Adguard Spanish/Portuguese Filter` is causing images not to load in this website.

4. Screenshots
<details><summary>Broken images:</summary>

![image](https://user-images.githubusercontent.com/5483864/158074839-80b8fbd2-0bc3-4397-aadf-adbac8b37bee.png)
</details>

<details><summary>Disabling cosmetic filters:</summary>

![image](https://user-images.githubusercontent.com/5483864/158074881-6006781b-e3b1-4b78-ba6a-faeca060b2ba.png)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
