### ISSUE TITLE
forum.release-apk.com

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#112732]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.17

### What type of problem have you encountered?

Website or app doesn't work properly, AdGuard gets detected on a website

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://forum.release-apk.com/viewforum.php?f=26

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, Adblock Warning Removal List, Online Malicious URL Blocklist, NoCoin Filter List

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track header, Self-destruction of third-party cookies, Block WebRTC, Hide your Referrer from third-parties (specify in comment below, if used custom value)

### Add your comment and screenshots

Please visit the following page and login with the provided test credentials:

Username: Testuser12345
Password: Testuser123

You will observe that the page is not showing the contents and instead displays adblock message (see screenshot)
Disabling AdGuard shows the contents of the page.
Please fix

3. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/6959116/158042383-5659f512-b045-4929-aaff-36fb32f7b195.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Not reproduced. Please check @zloyden

**Comment by zloyden** [comment]
I also can't reproduce it.

**Comment by Nzzyme** [comment]
Why was this closed? When you say not reproduced, do you mean it works fine for you? Can you please share a screenshot of the page that you see at your end?

There is a ad block message that I see when AG is enabled.

**Comment by zloyden** [comment]
The issue was closed because, as you can see above, we can't reproduce it on our end.
What filter causes this? Could you leave only AdGuard filters (except AdGuard DNS) without Stealth mode?
