### ISSUE TITLE
[Android] Missed ads in SG BusLeh: With Bus Location!

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1128]
https://play.google.com/store/apps/details?id=originally.us.buses

![image](https://cloud.githubusercontent.com/assets/15856304/11902643/fc91fccc-a5bb-11e5-9684-ef61dc237146.png)
[debug (4).txt](https://github.com/AdguardTeam/ExperimentalFilter/files/66925/debug.4.txt)

This doesn't happen always.. Sometimes the ads are
blocked (just the blank banner displayed) but not always.

ROP-316-41122

**Comment by Alex-302** [comment]
@evgeniy-ADG 
please, send this rule to user for test
```
||by.originally.us/deals/app/banners/$empty
||appload.ingest.crittercism.com^$empty
||api.crittercism.com^$empty
||by.originally.us/busbuzz/v1/endpoints/devices$empty
```
