### ISSUE TITLE
netlify.com

### ISSUE THREAD

**Issue by jayvdb** [AdguardTeam/AdguardFilters#11282]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

The easyprivacy list blocks sites hosted by http://netlify.com .
See https://github.com/easylist/easylist/issues/898 for the upstream issue, which links to two of my sites which are impacted.  I dont know how many sites netlify hosts, but it would be a very big number, in the 100,000s as their website says "Join more than 125,000 developers who love Netlify."

https://github.com/uBlockOrigin/uAssets/issues/1510 is tracking an override to unbreak this.
It looks like Adguard will also need its own override until it is fixed upstream.

Example site which isnt working correctly: https://gci-leaders.netlify.com/

<details><summary>Screenshot:</summary>

![screenshot from 2018-02-09 08-28-01](https://user-images.githubusercontent.com/15092/36007292-63d73074-0d74-11e8-84bb-7b0d15e5bc1c.png)

</details><br/>

* **Expected behaviour**: 

The English i18n strings should be visible.

***Steps to reproduce the problem***:

Go to https://gci-leaders.netlify.com/ .  The i18n strings should be visible.  Instead, the i18n message labels are shown.

***System configuration***

**Filters:**

EasyPrivacy

**Comment by Alex-302** [comment]
Hi
This issue must be fixed in original filter.
Temporary added
```
@@||gci-leaders.netlify.com/i18n/*$domain=netlify.com
```

**Comment by jayvdb** [comment]
That fix only addresses one of the two sites I referred to.  I have about 8 sites on netlify, all broken.  And there are many many more people with other sites hosted on netlify.
