### ISSUE TITLE
Are these rules still needed?

### ISSUE THREAD

**Issue by takanon1china** [AdguardTeam/AdguardFilters#112851]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

I don't know why these rules are still in filters.

```
@@||wp.com/c/*/wp-includes/css
@@||wp.com/c/*/wp-includes/js
@@||wp.com/p/jetpack^
```
You can find the scripts mentioned in this ticket at the following sites.

```
https://tfetimes.com/three-amazing-diy-tech-projects-for-sustainability-lovers/
https://joinhandshake.com/students/whos-hiring/
https://mac-torrent-download.net/everweb-standalone-3-6-1/
```

If EasyList no longer blocks them, AdGuard also should remove them from its filters.

I do not know. Maybe these rules are for third-party filters with aggressive blocking rules.

I use the filtering log very often and it is very disturbing for me to see these rules in the filtering log every time.

Feel free to close this ticket if the rules are still required.

### Proposed solution

-

### Additional information

-

**Comment by Alex-302** [comment]
It seems - no.
https://github.com/AdguardTeam/AdguardFilters/commit/52e0da0b5529073fd7c000b52d72774cccd7cb52
