### ISSUE TITLE
Popup (udemy.com)

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#113008]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard for Windows

### AdGuard version

3.6.17

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.udemy.com/join/login-popup/?locale=en_US&response_type=html&next=https%3A%2F%2Fwww.udemy.com%2Fjoin%2Flogin-popup%2F%3Fskip_suggest%3D1%26locale%3Den_US%26next%3Dhttps%253A%252F%252Fwww.udemy.com%252Flogout%252F%26response_type%3Dhtml

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

When I click login with google, the popup doesn't show up for google login.

### Privacy

- [X] I agree to follow this condition

**Comment by Bhooty** [comment]
:(

**Comment by bogachenko** [comment]
@Yuki2718 `@@||cdn.cookielaw.org^$domain=udemy.com`
