### ISSUE TITLE
Wentronic.* - Broken (AdGuard Annoyances filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#113044]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.16.4.30 (XUL)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other(specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.wentronic.com/
https://www.wentronic.pl/

### What filters do you have enabled?

AdGuard Annoyances filter

### Affected sites:
```
https://www.wentronic.com/
https://www.wentronic.pl/
```

### Issue:
Modal overlay / missing scrollbar / unclickable items

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **AdGuard Annoyances filter**

### Problem rule:
`##.cookie-modal`

### Possible fix:
```
wentronic.*##.overlay-block
wentronic.*#$#body { overflow: auto!important; }
```

### Other problem filters:
* ~~**Easylist Cookie List** / **Fanboy's Annoyance List** https://github.com/easylist/easylist/issues/11322/~~ _(FIXED)_
~~`##.cookie-modal`
`##cookie-modal`~~

* **I don't care about cookies** _(NOTIFIED)_
`~schuurman-schoenen.nl##.js-cookie-modal:not(body):not(html)`

--

### System info:
* OS/version: Windows 10 Pro (x64)
* Browser/version: Pale Moon v29.4.4 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
Safari 15 avanced protection have new environment variable?
