### ISSUE TITLE
Turn off adblocker

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#113418]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

3.6.17

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://movie.unlimitdownloads.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

Asking to turn off adblocker

Can't enter website
https://movie.unlimitdownloads.com/

and

https://toolxox.com/online-downloader.php

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
1 site - 1 report

**Comment by Bhooty** [comment]
> 1 site - 1 report

Oww
Sry in that case
:(

**Comment by Alex-302** [comment]
This time I will fix both sites.
