### ISSUE TITLE
meditationinmoscow.ru

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#11374]
***Description***:
* **Current behaviour**: 

Looks like the site has been hacked and is now sending phishing mail. Needs to be added to phishing shavar.

<details><summary>Screenshot:</summary>

![cpjecefohkodfmdk](https://user-images.githubusercontent.com/33634917/36062578-0ec6392c-0e78-11e8-8cb5-7803f3e58c41.png)

</details><br/>

The link displayed in the image leads to http://meditationinmoscow.ru/wp-includes/images/wlw/center/payment.php?id=m4df6110xrr0cf9j3dmxoe95z551jwz3&mx64a2

***Steps to reproduce the problem***:

1. Follow the link, a phishing payment page will open

***System configuration***

Not applicable here, it's a simple phishing domain

**Comment by zebrum** [comment]
added
