### ISSUE TITLE
redtube.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#11379]
**Site**: https://www.redtube.com/1519724

**Issue**: Please remove the Ad text on the right side and bottom of the page. Also remove the adblock message.

**Screenshot**: http://prntscr.com/icu7py

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.140 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]

**Comment by BlazDT** [comment]
Reproduced the ad links, sadly when hiding it the normal way the video is not playing.

Adblock message not reproduced.

@AdamWr please check.

**Comment by AdamWr** [comment]
I can't reproduce adblock message.

**Comment by Nzzyme** [comment]
I can no longer see the adblock message. Seems the issue was again with the Kaspersky setting

**Comment by Nzzyme** [comment]
Seeing ads on the page:

https://www.redtube.com/918645

Screenshot: http://prntscr.com/mukg91

Issue seen on AG for Chrome extension

**Comment by BlazDT** [comment]
Fixed
