### ISSUE TITLE
Messenger App [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#11395]
**App**: Messenger – Text and Video Chat for Free (Version: 152.0.0.17.94)

**Play Store Link**: https://play.google.com/store/apps/details?id=com.facebook.orca

**Issue**: Ads seen after signing in.

**Screenshot**: http://image.ibb.co/bv24Ln/Screenshot_20180211094402.jpg

**System**:
- Android version: 6.0.1 MMB29M
- MIUI version: MIUI Global 9.2 | Stable [ 9.2.4.0 (MHOMIEK) ]

**AdGuard Version**:
- AdGuard for Android 2.10.176

**Filters**:
English, Spyware, Social Media, Annoyances, Mobile Ads, Simplified domain names, EasyList China, Anti-Adblock Killer-Reek

**AdGuard Settings**:

- No user filter used
- Phishing & Malware Protection: Enabled
- Block ads in all apps: Enabled
- Search ads & self-promotion of sites: Disabled
- DNS Filtering enabled with DNSCrypt (Server: AdGuard DNS)
- HTTPS Filtering: Enabled
- High quality filtering: Enabled
- Filtering mode is Local VPN

**Comment by Alex-302** [comment]
Is your device rooted?

**Comment by Nzzyme** [comment]
It is not rooted.

**Comment by Nzzyme** [comment]
@Alex-302 : Can you let me know as to why was this closed without any fix? I am still seeing ads in this app.

**Comment by Alex-302** [comment]
HTTPS filtering is disabled for this app.
https://github.com/AdguardTeam/AdguardFilters/issues/1915
But you cannot use HTTPS filtering for apps without root access on Android 6+

**Comment by Nzzyme** [comment]
I am not really understanding what you say. HTTPS filtering is enabled in my AdGuard (root certificate is installed into the system and also Firefox browser). The link that you have provided leads to a page where the user is facing issue with receiving FB post updates/WhatsApp Messages, etc. Most of the other replies on that page are in Russian which I did not understand.

Note that I am not facing an issue with FB & WhatsApp. I am able to receive messages and updates in these apps. The issue is only with the official Messenger Android app.

**Comment by Nzzyme** [comment]
@AdamWr Can you please check this issue that I am facing with the Messenger app? I am still seeing ads everyday.

**Comment by Alex-302** [comment]
Please upload web-requests log

**Comment by AdamWr** [comment]
I guess this app is using SSL pinning, so we can't block these ads, like in these apps - https://forum.adguard.com/index.php?threads/apps-where-adguard-for-android-cant-filter-and-or-remove-the-ads-from.25182/

https://github.com/AdguardTeam/AdguardForAndroid/issues/472

I enabled HTTPS filtering for this app and in filtering log I see only these requests:
<details><summary>Screenshots</summary>

![messenger_1](https://user-images.githubusercontent.com/29142494/36380914-4242baec-1584-11e8-8c5f-d01a497f8dbc.png)
![messenger_2 png](https://user-images.githubusercontent.com/29142494/36380915-425ea87e-1584-11e8-9fcf-770ef54f81a5.png)

</details>

**Comment by Nzzyme** [comment]
@Alex-302 : Have sent the full log via app.
@AdamWr : I am running Android 6 and device is not rooted. I again tested by doing a clean install of the Messenger app and saw the filtering log.

https://ibb.co/kY9E5x

I am seeing some more domains in the log. Is the culprit lookaside.facebook.com ?

**Comment by akmLaVx** [comment]
Logs available via userid 1022592

**Comment by Alex-302** [comment]
@Nzzyme please try to block this domain for this app only
![image](https://user-images.githubusercontent.com/8361299/36738415-16a2bc80-1be6-11e8-8d17-f74e71beb3c7.png)

**Comment by Nzzyme** [comment]
Now, when I uninstalled and installed this app again, I see slightly different domains.


http://ibb.co/m9RS0x

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/36754791-bf8a42b0-1c12-11e8-8211-786325bd286d.png)

**Comment by Nzzyme** [comment]
@Alex-302 : I saw the domain "b-graph.facebook.com" later and I blocked that but after blocking that, I am unable to login to the app itself. Blocking graph.facebook.com would also not work.

**Comment by Alex-302** [comment]
So it is impossible without HTTPS filtering. It is impossible on non-rooted Android 6+

**Comment by Nzzyme** [comment]
That is wierd as I thought that all phone traffic would route through AG by creating a VPN. So does that mean that there are some other background connections that the filtering log of AG does not display and AG cannot block?

**Comment by Alex-302** [comment]
AdGuard cannot decrypt HTTPS traffic of the most of apps on Anroid 6+ without root access. 
>  I thought that all phone traffic would route through AG

you're right

**Comment by Nzzyme** [comment]
Has someone logged a Feature Request to get this fixed? Do you have a list of apps that AG does not block ads? I thought it was just a couple of them like FB, Instagram, Messenger, etc but did not know there were many others.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/blob/master/MobileFilter/sections/specific_app.txt
look for `||graph.facebook.com^$app=`

**Comment by Nzzyme** [comment]
Thanks for the list. Is this planned to be fixed in the future?

**Comment by Alex-302** [comment]
It can't be fixed without root access.
