### ISSUE TITLE
solarmovie.watch [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#11419]
**Site**: https://solarmovie.watch/

**Issue**: Pop-up seen on the page.

Also fake links seen on this page: https://solarmovie.watch/2865-cult-of-chucky-free-123movies.html
http://prntscr.com/id5ppb

**Screenshot**: N/A

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
I see no working player.
Please always check the sites which you reporting.

**Comment by Nzzyme** [comment]
I did not post the topic without testing. Why are the screenshots provided then? Doesn't mean the issue does not exist if you are not able to see it.

**Comment by Alex-302** [comment]
I see only fake player without ad blocker

**Comment by Nzzyme** [comment]
There is a player on the page

http://prntscr.com/iegl5d

Request is to remove the fake links as seen here: https://prnt.sc/id5ppb

**Comment by Alex-302** [comment]
ok, added
`||solarmovie.watch/templates/Solar/images/solar_btn_`
