### ISSUE TITLE
online-life.cc

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#1141]
Фоновая реклама на сайте.

**Comment by Alex-302** [comment]
Не повторяется.
Нужен список фильтров.

**Comment by zebrum** [comment]
may i just peopen this thread?
http://www.online-life.cc/12778-vse-shvacheno-man-with-a-plan-2016.html
chrome browser extension ru en spyware annoyances social_media

![screenshot 2017-02-22 14 29 25](https://cloud.githubusercontent.com/assets/23637588/23210537/0e6a92a4-f90f-11e6-9f98-ccf64112bcc3.png)


1.4.0 ru en spyware annoyances social_media
http://www.online-life.cc/12778-vse-shvacheno-man-with-a-plan-2016.html
antiadblocker 

![screenshot 2017-02-22 14 45 49](https://cloud.githubusercontent.com/assets/23637588/23210557/281ce030-f90f-11e6-89e4-edb03ea5d28b.png)

**Comment by Alex-302** [comment]
> may i just peopen this thread?

yes.

Adblock detection is fixed. Ads was not reproduced.
