### ISSUE TITLE
solarmoviegroup.com [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#11421]
**Site**: https://solarmoviegroup.com/movies/tom-of-finland/

**Issue**: Please remove the fake links on the page.

**Screenshot**: http://prntscr.com/id5r8c

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
it has no real visitors
