### ISSUE TITLE
http://d-parfum.ru

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#11425]
***Description***:
* **Current behaviour**: 

Phishing

<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/33634917/36074100-ec210a10-0f43-11e8-8ecc-b21974568acc.PNG)

</details><br/>

* **Expected behaviour**: 

Should be blocked

***Steps to reproduce the problem***:

Just visit the site

***System configuration***

Not applicable here

**Comment by zebrum** [comment]
added
