### ISSUE TITLE
tokyvideo.com

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#114680]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBO 1.42.2 + IDCAC 3.3.8

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.tokyvideo.com/video/lucky-luke-theme

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList Lithuania, I don't care about cookies, Adblock List for Finland, Dandelion Sprout's Nordic Filters, Dandelion Sprout's Annoyances List

### Add your comment and screenshots

1. An ad and a placeholder, with the placeholder being small enough (but with text) that EasyList would've most likely rejected it. I propose:
 ```
tokyvideo.com##div[class^=footer__ads--]
tokyvideo.com##.ads-topbar
```

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/22780683/161790369-71ccd8f2-1cf0-430a-8b59-9a73f14db34a.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
At the moment EL blocks them.
