### ISSUE TITLE
NSFW: rule34.xxx

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#11478]
***Description***:
* **Current behaviour**: 

Makes AdGuard throw multiple errors into the browser console.

<details><summary>Screenshot:</summary>

![adguard_error](https://user-images.githubusercontent.com/33634917/36118656-751d190a-1046-11e8-8869-b881bfc02124.png)

</details><br/>

* **Expected behaviour**: 

Should work fine
***Steps to reproduce the problem***:

Just visit the site, or open the saved page.

***Saved page***
[nothinghere.zip](https://github.com/AdguardTeam/AdguardFilters/files/1717685/nothinghere.zip)

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Windows, unspecified
AdGuard version:                       | 6.2.437.2171
Filters enabled:                       | en, ru, Adblock Warning Removal List, Annoyances, Experimental, Mobile Ads
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | 1248572

**Comment by akmLaVx** [comment]
Customer notes that on his machine, saved webpages do not throw errors. Might be environmental thing, will ask a few more questions.

**Comment by Alex-302** [comment]
bug
https://github.com/AdguardTeam/AdguardForWindows/issues/2110
