### ISSUE TITLE
te-en.com

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#11489]
[http://www.te-en.com/slim-girls-show-off-their-naked-bodies-t450072.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.te-en.com%2Fslim-girls-show-off-their-naked-bodies-t450072.html)

 1. Реклама стороннего сайта: `te-en.com###page-body > center`

 2. Мигающий баннер: `te-en.com###page-body > a`

 3. Остатки от рекламы, идущие через каждое сообщение: `te-en.com##.bg3`

 4. Баннер: `te-en.com###wrap > p:has(a > img)`

<details><summary>Screenshot's:</summary>

![2018 04 07-1](https://user-images.githubusercontent.com/17948007/38460834-c0b313fc-3aca-11e8-9eed-985482e473e8.png)
----------
![2018 04 07-2](https://user-images.githubusercontent.com/17948007/38460836-c893b234-3aca-11e8-8574-aa13b0bc47b7.png)
----------
![2018 04 07-3](https://user-images.githubusercontent.com/17948007/38460838-cefef91c-3aca-11e8-9811-50779be06916.png)
</details>

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.8.6 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by BlazDT** [comment]
@Alex-302 
Any news?
