### ISSUE TITLE
Not working in Safari, and assistant icon shows "paused" state for every page load

### ISSUE THREAD

**Issue by jab** [AdguardTeam/AdguardFilters#114847]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

Application version 2.7.0.1094 release (CL-1.8.276, DNS-1.6.72)

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

on every page

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

AdGuard is not working. I am using Safari. And the AdGuard Safari "assistant" extension shows the "paused" status on its icon for every page I load.

An apparently-related error message incorrectly complains that the root certificate expired:
<img width="1594" alt="Screen Shot 2022-04-06 at 6 30 18 PM" src="https://user-images.githubusercontent.com/64992/162083034-ae07f708-633f-4242-a7b5-23ffe944b5cb.png">

This even happens for [http://neverssl.com](http://neverssl.com) (wat?):
<img width="1594" alt="Screen Shot 2022-04-06 at 6 31 56 PM" src="https://user-images.githubusercontent.com/64992/162083292-0e328ef8-761b-401c-8d33-c8ec2e96dabd.png">

The `*.adguard.com` CA cert that is installed is not expired:
<img width="1138" alt="Screen Shot 2022-04-06 at 6 32 43 PM" src="https://user-images.githubusercontent.com/64992/162083425-592ee8f0-d95d-418f-8063-feaa791e16c9.png">

Any idea what's wrong with the AdGuard setup on this machine?

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@Chinaski1 Please assis.

**Comment by Alex-302** [comment]
@Aydinv13 please read the first message - `Application version 2.7.0.1094 release (CL-1.8.276, DNS-1.6.72)`

**Comment by jab** [comment]
macOS Catalina Version 10.15.7 (19H1824)
Safari Version 15.4 (15613.1.17.1.11, 15613)

It happens on every page load. The reproduction steps are just to (1) load any webpage, (2) observe the "paused" status showed by the AdGuard Safari assistant extension, (3) observe that AdGuard filters aren't working (as in #113732).

**Comment by jab** [comment]
Note there are really two issues here: (1) make AdGuard work again on systems like this and (2) improve the error reporting when something goes wrong. 

The current error reporting is inaccurate and incomplete.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardForMac #1059](https://github.com/AdguardTeam/AdguardForMac/issues/1059) via [**ZenHub**](https://www.zenhub.com/)
