### ISSUE TITLE
com.plurk.android

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#11494]
***Description***:
* **Current behaviour**: 

Shows ads.
<details><summary>Screenshot (ads + filtering log):</summary>

![screenshot_20180210-023141](https://user-images.githubusercontent.com/33634917/36135827-22a48a96-1096-11e8-94ec-db0cf78aa7c8.png)
![screenshot_20180210-023205](https://user-images.githubusercontent.com/33634917/36135828-22c00b22-1096-11e8-8ad6-50182f74d27c.jpg)

</details><br/>

* **Expected behaviour**: 

Shouldn't show ads.

***Steps to reproduce the problem***:

1. Try to use the app.

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 7.0
Browser:                               | N/A
AdGuard version:                       | 2.10.176
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Japanese filter", "Mobile Ads filter", "EasyList China", "Anti-Adblock Killer | Reek"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default mode)
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 972462

**Comment by Alex-302** [comment]
Please check:
`||graph.facebook.com^$app=com.plurk.android`
