### ISSUE TITLE
Formula 1 Application is broken

### ISSUE THREAD

**Issue by bosaad21** [AdguardTeam/AdguardFilters#115141]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.41

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.softpauer.f1timingapp2014.basic

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, Filter unblocking search ads and self-promotion, Liste AR, I don't care about cookies

### Add your comment and screenshots

1. <comment>

2. Screenshot while AdGuard is on
<details><summary>Screenshot 1:</summary>

![Screenshot_20220410-033603_Formula 1](https://user-images.githubusercontent.com/71277632/162596534-3c516332-8127-4a90-9805-c532d63dca28.jpg)

</details>
AdGuard is off
<details><summary>Screenshot N:</summary>

![Screenshot_20220410-033620_Formula 1](https://user-images.githubusercontent.com/71277632/162596544-e6c9c5fe-44d4-4584-8047-531d101ee9d4.jpg)

</details>
Formula 1 Application isn't working correctly..

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@bosaad21 Hi. Cannot reproduce. Could you please test when groups of filters are disabled?

**Comment by bosaad21** [comment]
Hi, I tried to disable all filters and other settings of AdGuard app and F1 application still not working, will work only after disabling AdGuard vpn network..
See the attached video 


https://user-images.githubusercontent.com/71277632/163074548-ad959b88-0640-4f4c-bf20-7c0f310128fb.mp4

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #4140](https://github.com/AdguardTeam/AdguardForAndroid/issues/4140) via [**ZenHub**](https://www.zenhub.com/)
