### ISSUE TITLE
AdGuard interferes with RingCentral products

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#11528]
We at RingCentral <http://www.ringcentral.com/> have a number of software products that are used by our customers. We use a software for fraud prevention from **iovation**: https://www.iovation.com

Our softwares load JavaScrip from the following URL https://mpsnare.iesnare.com/

It seems that ||iesnare.com^$third-party is listed, is that the reason why iovation library https://mpsnare.iesnare.com/snare.js gets blocked?

Could you please verify this domain and whitelist inside the product.

**Comment by Alex-302** [comment]
Reported to EasyList
https://github.com/easylist/easylist/issues/912

**Comment by Alex-302** [comment]
fixed.

**Comment by ryanbr** [comment]
Quick look at the code, it tracks. https://pastebin.com/Fd3uqWAH

I'm happy to leave it.

**Comment by Alex-302** [comment]
> it tracks

What exactly?
