### ISSUE TITLE
IG Share UTM parameter

### ISSUE THREAD

**Issue by stdedos** [AdguardTeam/AdguardFilters#115389]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

N/A

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.instagram.com/reel/bE9H5u5iUJy/?igshid=MTNkOTdYNTQK

### What filters do you have enabled?

AdGuard URL Tracking filter

### Add your comment and screenshots

Link is getting created using the Share function of the Instagram app on mobile. `igshid` is base64 encoded (ofc anonymized)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
We already have `||instagram.com^$removeparam=igshid`
