### ISSUE TITLE
[iOS] Ads on 24open.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1154]
http://www.24open.ru/auth/register/?backUrl=%2Fmessages%2Fchat%2F1A4F27759735D974%3Fajax%26backUrl%3D%252Fmessages%252Fcontacts%252F%253Fmsbx%253D2

![image](https://cloud.githubusercontent.com/assets/15856304/11973934/0b60123e-a968-11e5-8407-ab601ce8bec2.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.72.44 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.4 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.60 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.23.33 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.82 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.29.8 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.1.69 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.16 Enabled=YES
ID1 Name="EasyList" Version=1.0.48.68 Enabled=YES
ID5 Name="RU AdList" Version=1.0.48.69 Enabled=YES
ID!1 Name="Anti-Adblock Killer | Reek" Version=1.0.1.54 Enabled=YES
ID!2 Name="RU AdList: Counters" Version=1.0.45.29 Enabled=YES
ID!3 Name="RU AdList: BitBlock" Version=1.0.45.55 Enabled=YES

YBB-434-39224

**Comment by Alex-302** [comment]
чисто, лишь пустоты от баннеров(были)
