### ISSUE TITLE
incompatible rule

### ISSUE THREAD

**Issue by jayla-fr** [AdguardTeam/AdguardFilters#115614]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.0.163

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://abpvn.com/ruleChecker/redundantRuleChecker.html

### What filters do you have enabled?

AdGuard Russian filter

### Add your comment and screenshots

The [Redundancy check](https://abpvn.com/ruleChecker/redundantRuleChecker.html) tool says there is an error in the following rule.

**cloud.mail.ru#$?#.w-public__content  > div.b-layout > div.b-layout__col_1_2  { margin-right: auto !important; }**

Maybe it's saying this because the rule is not compatible with Adblock Plus. If the rule is indeed wrong, can you fix it?

<details><summary>Screenshot 1:</summary>

![rdt](https://user-images.githubusercontent.com/103706975/163501454-381fcf0b-43fa-4927-83c7-583e8de37fa5.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Actually, there is unnecessary one white space that I have fixed, but the rule is correct.

**Comment by Alex-302** [comment]
@jayla-fr This checker is for Adblock Plus syntax. The rule `#$?#` - AdGuard's own syntax(extended CSS).

**Comment by jayla-fr** [comment]
@Alex-302 @zloyden 

thanks for your help
