### ISSUE TITLE
Missing text box with AdGuard enabled.

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#11567]
@june8-o commented on [Wed Feb 14 2018](https://github.com/AdguardTeam/AdguardForMac/issues/283)

![ekran resmi 2018-02-14 15 06 31](https://user-images.githubusercontent.com/25007792/36203764-bfbaa58c-1199-11e8-803f-2b7d631938dd.png)

https://www.sanalmarket.com.tr/kweb/registration.do?execution=e1s3

(Field title includes "Ad", this might be the reason)

---

@zebrum commented on [Wed Feb 14 2018](https://github.com/AdguardTeam/AdguardForMac/issues/283#issuecomment-365599924)

Hello!
What is your AdGuard version? What filters do you use? Please try to turn off all filters and check the issue again.

---

@june8-o commented on [Wed Feb 14 2018](https://github.com/AdguardTeam/AdguardForMac/issues/283#issuecomment-365603924)

1.5.3
I found that AdBlock & uBlock polish filter - AdGuard supplement filter causing this. I disabled it and the problem gone.

---

@zebrum commented on [Wed Feb 14 2018](https://github.com/AdguardTeam/AdguardForMac/issues/283#issuecomment-365607721)

Great! So it's not AdGuard for Mac problem. Moved to Filters repo.

**Comment by AdamWr** [comment]
The problem was in  `Adblock & uBlock Polish filter`.
Fixed.

**Comment by june8-o** [comment]
I updated the filter, but the problem continues.

**Comment by AdamWr** [comment]
Update will be available in 2-3 hours.
If you do not want to wait, you can add this rule to user filter:
`sanalmarket.com.tr#@##ad`

**Comment by june8-o** [comment]
Not so important, I can wait. Thanks.
