### ISSUE TITLE
[iOS] iphones.ru 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1157]
![image](https://cloud.githubusercontent.com/assets/15856304/11975310/15f303c0-a975-11e5-8604-bdd8664ccacf.png)

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.72.74 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.10 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.66 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.23.39 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.84 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.29.24 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.1.74 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.17 Enabled=YES
ID1 Name="EasyList" Version=1.0.48.93 Enabled=YES
ID5 Name="RU AdList" Version=1.0.48.94 Enabled=YES
ID1 Name="void.gr" Version=1.0.0.47 Enabled=YES
ID2 Name="Fanboy's Annoyances" Version=1.0.49.4 Enabled=YES
ID3 Name="Fanboy's Social Blocking List" Version=1.0.48.92 Enabled=YES
ID!5 Name="Fanboy's Enhanced Tracking List" Version=1.0.0.98 Enabled=YES
ID 3 Name="hufilter" Version=1.0.0.19 Enabled=YES
ID 5 Name="Schacks Adblock Plus liste" Version=1.0.1.7 Enabled=YES
ID 6 Name="Xfiles" Version=1.0.0.39 Enabled=YES
ID 7 Name="Adblock Warning Removal List" Version=1.0.48.98 Enabled=YES
ID!1 Name="Anti-Adblock Killer | Reek" Version=1.0.1.54 Enabled=YES
ID!2 Name="RU AdList: Counters" Version=1.0.45.54 Enabled=YES
ID!3 Name="RU AdList: BitBlock" Version=1.0.45.80 Enabled=YES
ID!7 Name="Adblock polskie reguЕ‚y cookies" Version=1.0.0.75 Enabled=YES

PQC-349-81554

**Comment by Alex-302** [comment]
У меня этого баннера нет
