### ISSUE TITLE
Adguard iOS block rockstar forum site tested with iPhone and iPad

### ISSUE THREAD

**Issue by zerocolaa39fr** [AdguardTeam/AdguardFilters#11619]
Hello I use iPad Air, iPhone 5s iOS 11.2.5 and Adguard iOS 1.3.3 easyprivacy, english filter

1. open safari app
2. go to https://support.rockstargames.com/hc/en-us
3. Safari iOS show a blank site in private mode and without private mode 

If disable adguard easyprivacy list, then it works
Adguard easyprivacy list blocked websites!!

Please make a universal update for all user.

**Comment by Alex-302** [comment]
Hi
It seems this is a bug
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/957

Please check `@@://*.rockstargames.com^$domain=rockstargames.com`
