### ISSUE TITLE
Помогите, пожалуйста, с составлением пользовательского фильтра

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#116204]
Здравствуйте!
Сайт: ficbook.net
Adguard for android 3.6
Подскажите пожалуйста, как заблокировать следующий элемент? (Чтобы его увидеть, необходимо загрузить какую-то работу на сайт)
Я уже просто не знаю куда писать. Со всеми уже разобрался, а с этим просто никак.

Буду вам премного благодарен!

PS: Это нужно, чтобы подросток не клянчил на них деньги :-) 

![31EE1DF8-B57B-4145-95C3-41410C48B15F](https://user-images.githubusercontent.com/104152812/164484590-ef67d34b-8dc7-4b6d-b248-824d02859221.jpeg)

**Comment by Sergey-Lyapin** [comment]
Добрый день, эти правила должны подойти:
ficbook.net##.fic-premium-actions
ficbook.net##.add-part > button[data-target="#getPremiumModal"]
