### ISSUE TITLE
HÖRZU TV Programm (iOS app)

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#11622]
***Description***:

* **App link**:
https://itunes.apple.com/lu/app/h%C3%B6rzu-tv-programm/id1065503950?mt=8

* **Current behaviour**: 
Displays ads.

<details><summary>Screenshot:</summary>

![image1](https://user-images.githubusercontent.com/33634917/36259404-c874453e-1266-11e8-8e11-9327dbc4efb9.jpg)
</details><br/>

* **Expected behaviour**: 

Shouldn't display ads.

***Steps to reproduce the problem***:

1. Open the app with AdGuard enabled.

***System configuration***

**Logs:**
[bienz.zip](https://github.com/AdguardTeam/AdguardFilters/files/1727829/bienz.zip)
around 23:45

**Filters:**

English, Spyware, Social media, Annoyances, German, Mobile Ads, Safari, Simplified domain names

Information                            | Value
---                                    | ---
Operating system:                      | iOS
Operating system version (Android/iOS) | 11.2.5
Browser:                               | N/A
AdGuard version:                       | 1.3.3.118
Filters enabled:                       | English, Spyware, Social media, Annoyances, German, Mobile Ads, Safari, Simplified domain names
Simplified filters (iOS only)          | On
AdGuard DNS:                           | Default
Helpdesk ID (if exists):               | 1609733

**Comment by Alex-302** [comment]
These ads can be blocked, but only with Facebook.
Add `facebook.com` to black list.
