### ISSUE TITLE
Zedge (ios)

### ISSUE THREAD

**Issue by hitechtalk69** [AdguardTeam/AdguardFilters#116369]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.3.3 (947)

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://apps.apple.com/us/app/zedge-wallpapers/id1086101495

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

||tapresearch.com^

(Analytics company)

there is no subdomains so the main has to be blocked

### Privacy

- [X] I agree to follow this condition

**Comment by seia-soto** [comment]
This shouldn't be added to the list since the website they host is also located at the same domain. Instead of it's better to provide the endpoint for macOS users.
