### ISSUE TITLE
[iOS] missed ad on song5.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1163]
http://song5.ru/text/scratch21-strangers-%D1%87%D1%83%D0%B6%D0%B0%D0%BA%D0%B8-rus

![image](https://cloud.githubusercontent.com/assets/15856304/11993555/0773fb1c-aa3b-11e5-851e-0063ec747246.png)

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.71.78 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.3.92 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.42 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.79 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.28.87 Enabled=YES
ID=6 Name="German filter" Version=1.0.21.90 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.92.88 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.8.59 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.10 Enabled=YES
ID Name="Turkish filter" Version=1.0.0.51 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.1.63 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.13 Enabled=YES
ID 7 Name="Adblock Warning Removal List" Version=1.0.48.15 Enabled=YES
ID!0 Name="Spam404" Version=1.0.1.25 Enabled=YES

VTV-643-35700

**Comment by Alex-302** [comment]
чисто)
