### ISSUE TITLE
stackoverflow cookie annoyance

### ISSUE THREAD

**Issue by hitechtalk69** [AdguardTeam/AdguardFilters#116370]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

1.11.3

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

https://stackoverflow.com/questions/60323665/how-to-authenticate-to-the-firebases-https-iid-googleapis-com-iid-v1batchimp

### What filters do you have enabled?

AdGuard Annoyances filter, Fanboy's Annoyances, I don't care about cookies

### Add your comment and screenshots

https://stackoverflow.com/questions/60323665/how-to-authenticate-to-the-firebases-https-iid-googleapis-com-iid-v1batchimp

cookie annoyance when page is visited

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Cannot reproduce with NL IP. Need screenshot, and, if it possible - HTML code of element.
