### ISSUE TITLE
NSFW pornolomka.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#11630]
***Description***:
* **Current behaviour**: 

Slips through Family Protection DNS

* **Expected behaviour**: 

Should get blocked by Family Protection DNS

***Steps to reproduce the problem***:

Open the site with Family Protection DNS enabled

***System configuration***

n/a
User id 1760682

**Comment by zebrum** [comment]
Our Family DNS depends on WoT ratings. It means that I can't add the site manually. 
What can be done is: go to https://www.mywot.com/en/scorecard/pornolomka.com and rate the domain as not appropriate for children.
