### ISSUE TITLE
AdGuard URL Tracking Protection | https://www.flipkart.com/

### ISSUE THREAD

**Issue by tillcash** [AdguardTeam/AdguardFilters#116479]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.42.4

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.flipkart.com/

### What filters do you have enabled?

AdGuard URL Tracking filter

### Add your comment and screenshots

```
||flipkart.com^$removeparam=_appId
||flipkart.com^$removeparam=_refId
||flipkart.com^$removeparam=affExtParam1
||flipkart.com^$removeparam=affExtParam2
||flipkart.com^$removeparam=affid
||flipkart.com^$removeparam=cid
||flipkart.com^$removeparam=cmpid
||flipkart.com^$removeparam=fm
||flipkart.com^$removeparam=iid
||flipkart.com^$removeparam=lid
||flipkart.com^$removeparam=marketplace
||flipkart.com^$removeparam=otracker
||flipkart.com^$removeparam=otracker1
||flipkart.com^$removeparam=pageUID
||flipkart.com^$removeparam=param
||flipkart.com^$removeparam=pid
||flipkart.com^$removeparam=ppn
||flipkart.com^$removeparam=ppt
||flipkart.com^$removeparam=pwsvid
||flipkart.com^$removeparam=ssid
||flipkart.com^$removeparam=store
```

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Need URLs with real parameters. We cannot just block everything.

**Comment by tillcash** [comment]
- https://www.flipkart.com/toys/party-supplies/balloons-decoration/balloons/shribalaji~brand/pr?rwdoq=dea1app.in&sid=mgl%2Cksc%2Cgcv%2Coam&marketplace=FLIPKART&otracker=product_breadCrumbs_shribalaji+Balloons&hyzlrh=25e199a2533a&bzas=1650875421498&sort=price_asc&p%5B%5D=facets.fulfilled_by%5B%5D%3DFlipkart+Plus&p%5B%5D=facets.discount_range_v1%5B%5D%3D60%25+or+more&affid=admitad&affExtParam1=1522635&affExtParam2=40c18903bc66ec97eab6525650bc9eaf
- https://www.flipkart.com/motorola-g52-coming-soon-store?param=236&pageUID=1650867556421
- https://www.flipkart.com/soundcore-anker-r100-fast-charging-tws-25-hours-playtime-bluetooth-headset/p/itm2054ae279de13?pid=ACCG45FPAVSTFZFW&_refId=PP.2d6db317-b053-444e-98bc-6f34f4443bdd.ACCG45FPAVSTFZFW&_appId=CL
- https://www.flipkart.com/fashion-freak-graphic-print-men-round-neck-white-black-orange-t-shirt/p/itm7321b5f9f1c0b?pid=TSHFV2MMQFNYXXNV&lid=LSTTSHFV2MMQFNYXXNV6DG6W1&marketplace=FLIPKART&sattr%5B%5D=size&st=size&otracker=product_breadCrumbs_Fashion%25252520Freak%25252520Men%27s%25252520T-shirts&affid=adminpais&affExtParam1=62663099cac44611c23b7220&pwsvid=62663099cac44611c23b7220&affid
- https://www.flipkart.com/microtek-smart-em4170-inverter-ac-upto-1-5-ton-170v-275v-voltage-stabilizer/p/itmae6a8cb29db3e?pid=VSTFPMPK2T8KPYTB&_refId=PP.44799593-6bf3-461e-996d-f5f599ce1a55.VSTFPMPK2T8KPYTB&_appId=CL
- https://www.flipkart.com/bombay-shaving-company-charcoal-face-sheet-mask-easy-at-home-skin-restoration-pack-5/p/itmcb49333ecd6b5?pid=FCPFQUYADXZ8AZYB&_refId=PP.fbdce509-8297-49c8-ab31-232f86342c92.FCPFQUYADXZ8AZYB&_appId=CL
- https://www.flipkart.com/onida-1-5-ton-3-star-split-inverter-ac-white/p/itm749d6380036c0?pid=ACNG9MRWUDRE9DWK&lid=LSTACNG9MRWUDRE9DWKUGYJLT&marketplace=FLIPKART&store=j9e%2Fabm%2Fc54&pageUID=1650863909765
- https://www.flipkart.com/realme-techlife-4-in-1-convertible-1-ton-4-star-split-inverter-ac-white/p/itm4154a54922cc5?pid=ACNGB7DJ3NMDHGU4&_refId=PP.d6c42925-7921-4009-8ef1-da675c28a76c.ACNGB7DJ3NMDHGU4&_appId=CL

**Comment by tillcash** [comment]
- https://www.flipkart.com/fastrack-tees-analog-watch-men-women/p/itmf3zhmtf8vxwnz?pid=WATE878GYJR3E8SV&ctx=eyJjYXJkQ29udGV4dCI6eyJhdHRyaWJ1dGVzIjp7InZhbHVlQ2FsbG91dCI6eyJtdWx0aVZhbHVlZEF0dHJpYnV0ZSI6eyJrZXkiOiJ2YWx1ZUNhbGxvdXQiLCJpbmZlcmVuY2VUeXBlIjoiVkFMVUVfQ0FMTE9VVCIsInZhbHVlcyI6WyJKdXN0IOKCuTQ5OSJdLCJ2YWx1ZVR5cGUiOiJNVUxUSV9WQUxVRUQifX0sInRpdGxlIjp7Im11bHRpVmFsdWVkQXR0cmlidXRlIjp7ImtleSI6InRpdGxlIiwiaW5mZXJlbmNlVHlwZSI6IlRJVExFIiwidmFsdWVzIjpbIkZhc3RyYWNrIFdhdGNoIl0sInZhbHVlVHlwZSI6Ik1VTFRJX1ZBTFVFRCJ9fSwiaGVyb1BpZCI6eyJzaW5nbGVWYWx1ZUF0dHJpYnV0ZSI6eyJrZXkiOiJoZXJvUGlkIiwiaW5mZXJlbmNlVHlwZSI6IlBJRCIsInZhbHVlIjoiV0FURTg3OEdZSlIzRThTViIsInZhbHVlVHlwZSI6IlNJTkdMRV9WQUxVRUQifX19fX0%3D&pageUID=1650708925391
- https://www.flipkart.com/toys/party-supplies/balloons-decoration/balloons/shribalaji~brand/pr?rwdoq=dea1app.in&sid=mgl%2Cksc%2Cgcv%2Coam&marketplace=FLIPKART&otracker=product_breadCrumbs_shribalaji+Balloons&hyzlrh=25e199a2533a&bzas=1650875421498&sort=price_asc&p%5B%5D=facets.fulfilled_by%5B%5D%3DFlipkart+Plus&p%5B%5D=facets.discount_range_v1%5B%5D%3D60%25+or+more&affid=admitad&affExtParam1=1522635&affExtParam2=40c18903bc66ec97eab6525650bc9eaf
- https://www.flipkart.com/hayan-impex-electric-beater-hand-held-high-speeds-roasting-appliances-cream-mixer-kitchen-baking-tools-180-w-blender/p/itm5d5ad96b8b734?pid=HBLFV226GVG6BUMU&affid=adminpais&affExtParam1=626378b962ae8f2d9946fd5e&pwsvid=626378b962ae8f2d9946fd5e
- https://www.flipkart.com/muuchstac-skin-lightening-oil-face-wash/p/itmfdbfdnuyjazzg?pid=CBKFDAHRX369923Y&lid=LSTCBKFDAHRX369923YASFNFD&marketplace=FLIPKART&fm=productRecommendation%2Fattach&iid=R%3Aa%3Bp%3AFCWF9RWJGXBYCP6T%3Bpt%3App%3Buid%3A89992859-c47b-11ec-ab56-330a2bdd6931%3B.CBKFDAHRX369923Y&ssid=l1tbnj2wio82ud4w1650879541501&otracker=pp_reco_Frequently%2BBought%2BTogether_1_Frequently%2BBought%2BTogether_CBKFDAHRX369923Y_productRecommendation%2Fattach_1&otracker1=pp_reco_PINNED_productRecommendation%2Fattach_Frequently%2BBought%2BTogether_NA_productCard_cc_1_NA_view-all&cid=CBKFDAHRX369923Y
- https://www.flipkart.com/groomd-body-wash-face-shampoo-conditioner-hair-styling-clay-combo-925g-pack-5/p/itme19a540b7de7c?pid=CBKGCWKJVRGWKGMG&lid=LSTCBKGCWKJVRGWKGMGLKL5MF&marketplace=FLIPKART&fm=productRecommendation%2Fsimilar&iid=R%3As%3Bp%3ACBKFDAHRX369923Y%3Bl%3ALSTCBKFDAHRX369923YASFNFD%3Bpt%3App%3Buid%3A95dccdee-c47b-11ec-9b94-4d1ed434bf96%3B.CBKGCWKJVRGWKGMG&ppt=pp&ppn=pp&ssid=l1tbnj2wio82ud4w1650879541501&otracker=pp_reco_Similar%2BProducts_3_33.productCard.PMU_HORIZONTAL_groomd%2BBody%2BWash%2BFace%2BWash%2BShampoo%2BConditioner%2BHair%2BStyling%2BClay%2BCombo-925g%2B%2528Pack%2Bof%2B5%2529_CBKGCWKJVRGWKGMG_productRecommendation%2Fsimilar_2&otracker1=pp_reco_PINNED_productRecommendation%2Fsimilar_Similar%2BProducts_GRID_productCard_cc_3_NA_view-all&cid=CBKGCWKJVRGWKGMG
