### ISSUE TITLE
Ava (ios)

### ISSUE THREAD

**Issue by hitechtalk69** [AdguardTeam/AdguardFilters#116564]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.3.3 (947)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://apps.apple.com/us/app/ava-credit-building/id1584183782

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

api2.branch.io should be whitelisted it breaks the app from opening

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #943](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/943) via [**ZenHub**](https://www.zenhub.com/)
