### ISSUE TITLE
Online Malicious URL block list issues

### ISSUE THREAD

**Issue by SASUKE0721** [AdguardTeam/AdguardFilters#116567]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

nightly34 (4.0)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://reports.adguard.com/ja/new_issue.html

### What filters do you have enabled?

Online Malicious URL Blocklist

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Self-destruction of third-party cookies, Disable cache for third-party requests, Block WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties (specify in comment below, if used custom value), Hide your User-Agent (specify in comment below, if used custom value), Hide your IP address (specify in comment below, if used custom value)

### Add your comment and screenshots

Words like Adguard and blog will be blocked and the site will be broken.
Example 
blogger.com 
reports.adguard.com/ja/new_issue.html

Screenshot 2 shows the filter on
Screenshot 3 shows filter off

<details><summary>Screenshot1 :</summary>

![Screenshot_20220426-121901348](https://user-images.githubusercontent.com/87330832/165215395-08d76250-283b-44ce-bdf4-6d36b817a076.jpg)

</details>

<details><summary>Screenshot2 :</summary>

![Screenshot_20220426-121923859](https://user-images.githubusercontent.com/87330832/165215443-ac0c5d06-8374-46ad-b91f-1a193f61f945.jpg)

</details>

<details><summary>Screenshot3 :</summary>

![Screenshot_20220426-121929583](https://user-images.githubusercontent.com/87330832/165215573-248f64c4-2959-4872-9dd3-27d0ba911a1b.jpg)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
I suppose this could be reported to https://gitlab.com/curben/urlhaus-filter/-/issues (The owner of Online Malicious URL Blocklist), but its maintainer isn't all that quick to respond to most reports, sadly.
