### ISSUE TITLE
Mobile Ads List blocks Youtube thumbnails

### ISSUE THREAD

**Issue by bbhtt** [AdguardTeam/AdguardFilters#116661]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

None

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

m.youtube.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyPrivacy, Fanboy's Annoyances, Fanboy's Social Blocking List, Peter Lowe's Blocklist, Fanboy's Enhanced Tracking List, Dandelion Sprout's Annoyances List, Legitimate URL Shortener

### Add your comment and screenshots

Using uBlock Origin 1.42.4 with the included AdGuard Mobile Ads List.

https://github.com/AdguardTeam/AdguardFilters/blob/239c1d169f86c9223cb981d9fe6670e9f3f09842/MobileFilter/sections/specific_web.txt#L973 blocks thumbnails from being displayed in the video page.

To reproduce:

1. Directly open a video by pasting a link for example https://m.youtube.com/watch?v=VufDd-QL1c0 and block autoplay otherwise the thumbnail with the play button won't appear.
2. See that the thumbnail is black:

![image](https://user-images.githubusercontent.com/62639087/165441975-1bb984e0-7c1c-486f-8634-4933e0c71729.png)

![image](https://user-images.githubusercontent.com/62639087/165441995-99d8ada5-3ee6-42d6-9720-f820ead8528d.png)

Issue is resolved by adding an exception to that rule in uBlock Origin:

`m.youtube.com#@#.ytp-cued-thumbnail-overlay > div[style*="/sddefault.jpg"]`

Is that filter necessary? I haven't seen any issues and I'm using that exception for months now...

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@Sergey-Lyapin Please take a look. I can't reproduce, maybe you remember what the purpose of https://github.com/AdguardTeam/AdguardFilters/commit/84827d4c2ce35aacefb634f6eb032d05b3e21b1e

**Comment by Alex-302** [comment]
Maybe that rule breaks previews, but I am not sure
https://github.com/AdguardTeam/AdguardFilters/issues/116010#issuecomment-1109309259

**Comment by bbhtt** [comment]
Thank You!
