### ISSUE TITLE
theplatformlaw.blog

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#116614]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

Version 4.0.64

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://theplatformlaw.blog/2022/04/19/the-leaked-final-version-of-the-digital-markets-act-a-summary-in-ten-points/

### What filters do you have enabled?

AdGuard Mobile Ads filter, AdGuard Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

[screenshot](https://i.imgur.com/xS1NfFV.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/165566041-77dbb1a5-b741-48a4-bcea-129964c69473.png)
