### ISSUE TITLE
pkpics.club

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#116606]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

Version 4.0.64

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://pkpics.xyz/?44ff206fce=cktyMWRnbXpHdExLZVViUHJCMnNyMmZkL2loLzA0em5qZ0V4dmNmNWgxTGIwc09PLytHQlN5K2hzV0wzVzJvN3pLeUJibTFZSGlGYlhNSTJZNkYwTEk5dGt0R2dRNG5kTDh4ZzN5Q0FFM3dONUUvOEtNZGhlYzlQa042Z3YramwyMkFPTEI0cDd6bzVxZDNVMDRiV0cxU3VuTGVPcm5hOFdzRlFVZEFUdGFKNnI4N2tUUFlDK1phbldGakhvSTBG

### What filters do you have enabled?

AdGuard Mobile Ads filter, AdGuard Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

> timer annoyance

<details><summary>Screenshots:</summary>

[screenshot](https://i.imgur.com/lffGlmU.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
We don't add rules for timers less than 10 seconds.
