### ISSUE TITLE
[iOS] www.idownloadblog.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1166]
http://www.idownloadblog.com/2015/12/22/mac-outlook-cant-upgrade-your-database-error-outlook-fix/

![image](https://cloud.githubusercontent.com/assets/15856304/11994659/26229676-aa4b-11e5-9438-e55d013594c5.png)

Enabled=YES ID=2 Name="English filter" Version=1.0.73.12 Enabled=YES ID=3 Name="Spyware filter" Version=1.0.4.21 Enabled=YES ID=4 Name="Social media filter" Version=1.0.7.75 Enabled=YES ID Name="Safari Filter" Version=1.0.0.19 Enabled=YES ID1 Name="EasyList" Version=1.0.49.28 Enabled=YES ID2 Name="Fanboy's Annoyances" Version=1.0.49.40 Enabled=YES ID 7 Name="Adblock Warning Removal List" Version=1.0.49.33 Enabled=YES ID 9 Name="Prebake" Version=1.0.1 Enabled=YE

BTA-376-70965
ODD-848-24184
MOT-489-35133
JOX-642-59956
HAB-307-69873
ICD-778-73265
FGE-620-45099

**Comment by Alex-302** [comment]
Added
```
idownloadblog.com#@#.custom-ad
idownloadblog.com#@#.header-ad
```
Please check them.

**Comment by evgeniy-ADG** [comment]
Noticed idownloadblog.com only loads white page when navigating from Shared Links tab in safari (from Twitter t.co shortened url). 
Site was apparently fixed in recent past for a similar issue with blank pages when loading directly on the site

https://kb.adguard.com/staff/index.php?/Tickets/Ticket/View/281025

Could you please check it?

**Comment by Alex-302** [comment]
@evgeniy-ADG 
чо то не пойму - сайт ломается только при открытии с помощью сокращённых ссылок? Примера нет? У вас повтряется?

**Comment by evgeniy-ADG** [comment]
Да, именно так. Я iOS-free, попрошу коллегу посомтреть. Завтра напишем.
