### ISSUE TITLE
new.gdtot.pm

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#116771]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.3.3

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://new.gdtot.pm/file/8081308424

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

https://github.com/AdguardTeam/AdguardFilters/issues/97725

Website domain changed to new.gdtot.pm

can u plz update filters

### Privacy

- [X] I agree to follow this condition

**Comment by Bhooty** [comment]
Sry for writing again :(
They again changed it to gdtot.pl :,(

example:

https://new.gdtot.pl/file/12261021569

**Comment by Alex-302** [comment]
ok
