### ISSUE TITLE
"Super cookie" tracking rules

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardFilters#116829]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Hello,

Is it possible to add rules to block "super cookie" tracking? Here is more information:
https://www.techtarget.com/searchsecurity/definition/supercookie
https://www.techopedia.com/definition/27310/super-cookie
and test tool:
https://supercookie.me

Thank you.
Best regards!

### Proposed solution

Early I tried `/favicon*.*^$empty,important` rule and it works fine, but I'm not sure that this is correct. Thank you.

**Comment by krystian3w** [comment]
Tested in Enhanced Trackers List( https://www.fanboy.co.nz/filters.html) without use `empty` and problem is blank icon on tab.

**Comment by Yuki2718** [comment]
"Supercookie" in the articles is past thing and already addressed by browsers. It doesn't make sense to make a rule for just a demo site generic.

**Comment by krystian3w** [comment]
Not for Firefox, I don't remember opened bug track.

On 5 tests I have 2 duplicates (CC 22 64 04 B6 EF) and 3 repeats (66 54 86 64 C2 76), so test are outdated or Moz://a does not take it seriously even it is made without errors (and errors will be copied by tracking companies).
