### ISSUE TITLE
[iOS] www.macdigger.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1168]
![image](https://cloud.githubusercontent.com/assets/15856304/11995112/a0aa1c2c-aa53-11e5-86e4-99bbd2cdc695.png)

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.73.21 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.23 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.76 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.29.46 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.1.85 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.19 Enabled=YES
ID5 Name="RU AdList" Version=1.0.49.41 Enabled=YES
ID 7 Name="Adblock Warning Removal List" Version=1.0.49.42 Enabled=YES

AER-463-24972

**Comment by Alex-302** [comment]
Чисто
