### ISSUE TITLE
Blocking (some) Duck DNS domains greatly improves phishing protection in Japan

### ISSUE THREAD

**Issue by hirorpt** [AdguardTeam/AdguardFilters#116832]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.7

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

`http://ryorrjhkua[.]duckdns[.]org`

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter

### Add your comment and screenshots

Phishing via SMS abusing Duck DNS have been ongoing in Japan for at least nearly two years [1]. Our observation is that the following regex catches all of this type of scams at the moment.
~~~ 
/^http:\/\/[a-z]{10}\.duckdns/$document,domain=duckdns.org
~~~

It has already been added to uBlock filters – Badware risks (https://github.com/uBlockOrigin/uAssets/commit/a116d701).
I think AdGuard should follow suit.

[1] [Jun 20, 2020](https://twitter.com/NaomiSuzuki_/status/1274325657497907201) -  [Apr 28, 2022](https://twitter.com/NaomiSuzuki_/status/1519496629312790536)

<details><summary>Screenshot 1:</summary>

![Screenshot_1651160676](https://user-images.githubusercontent.com/82331005/165795461-774189d6-5a7f-4d15-94c7-5df2365d78c4.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by hirorpt** [comment]
> Could you please provide sample link

It is collected enormously in this Twitter thread.

> [1] [Jun 20, 2020](https://twitter.com/NaomiSuzuki_/status/1274325657497907201) - [Apr 28, 2022](https://twitter.com/NaomiSuzuki_/status/1519496629312790536)

**Example**

> 04/28 偽日本郵便SMS、iPhone転送先：103.80.134.199(Apple)
00:00- ywvjvihyxj.duckdns[.]org
02:00- yxxxkjwvna.duckdns[.]org
04:00- zhcxmhibpk.duckdns[.]org
06:00- zkazftntrb.duckdns[.]org
08:00- zkylqcpbno.duckdns[.]org
10:00- zmzmmztttu.duckdns[.]org
https://twitter.com/NaomiSuzuki_/status/1519496629312790536

**Public reputation**

Screenshot of Japanese Google search results about duckdns.org

![Screenshot of Japanese Google search results about duckdns.org](https://user-images.githubusercontent.com/82331005/165870188-c44c0795-b461-43c3-b459-c9129bc96843.png)

**Comment by Alex-302** [comment]
Ok, blocked.

**Comment by hirorpt** [comment]
I expected the filter will be a part of AdGuard's phishing and malware protection available only premium app, not the tracking protection filters.
Out of curiosity, what is the reason? Is it due to using regex?

**Comment by Alex-302** [comment]
Yes. Anti-phishing protection can block whole duckdns.org only, or specific subdomains. Also modifiers not supported.

**Comment by Yuki2718** [comment]
But why not Base? Not all user enable TPF.

**Comment by Alex-302** [comment]
I don't even know how big the problem is.

**Comment by Yuki2718** [comment]
Simply put, relatively long-standing and popular SMS scam on Japanese sites. So maybe placing on JPF is fine in this case.

**Comment by Alex-302** [comment]
ok
