### ISSUE TITLE
Origin Trials: Topics API and First "Locally-Executed Decision over Groups" Experiment (FLEDGE) problematic

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardFilters#116830]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Hello,

as you may know Google is added Origin Trials: Topics API and First "Locally-Executed Decision over Groups" Experiment (FLEDGE) in the last version of chromium-base browsers. It is possible to block or suppress somehow via rules?

Thank you.
Best regards.

### Proposed solution

As I recall you already did it something similar for FloC early🙂

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/Scriptlets/issues/214
