### ISSUE TITLE
Whitelisting a website

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#11713]
> Есть рабочий ресурс такого вида rm.sabpek.com:8080/redmine/. AdGuard перенаправляет запросы и получается sabpek.com/redmine, что уже делает его неработоспособным. Сайт в белом списке, но это не помогает. Как-то можно убрать перенаправление?

@Alex-302 как такое правильно исключить?

**Comment by Alex-302** [comment]
У меня не перенаправляет. Какой Адгард? Пусть попробует антитрекинг покрутить в сторону ослабления.

**Comment by evgeniy-ADG** [comment]
@Alex-302 это андроид, ID 1761482

**Comment by Alex-302** [comment]
Вот ведро
![image](https://user-images.githubusercontent.com/8361299/36501363-988b6cec-174f-11e8-9fe4-136ef0dc5baa.png)
у себя потести, может от браузера/прошивки зависит

**Comment by evgeniy-ADG** [comment]
@Alex-302 была похожая штука, там виноват был DNS. Можно как-то в Android версии вайтлистить домены от DNS?

**Comment by geminixandroid** [comment]
Xiaomi redmi note 3 pro, android 6, хром 64.0.3282.137.
Если пробовали в хроме смотреть, то нужно сжатие отключить, иначе форма с логином отобразится, но при входе всё равно перенаправится не правильно.
В Адгард ресурс в белом списке, отключена DNS фильтрация.

**Comment by Alex-302** [comment]
@geminixandroid какой режим - прокси или VPN? Попробуйте переключить.

**Comment by geminixandroid** [comment]
Был VPN, попробовал через публичный прокси - аналогично

**Comment by Alex-302** [comment]
@geminixandroid не, имею в виду режим Адгарда. В расширенных настройках можно выбирать в каком режиме он будет работать - локальный VPN или локальный прокси.

**Comment by geminixandroid** [comment]
@Alex-302, в расширенных настройках поставил локальный http прокси - дал root, аналогично

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #1743](https://github.com/AdguardTeam/AdguardForAndroid/issues/1743) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
@geminixandroid перенесли в репозиторий приложения. Я здесь не помогу.
