### ISSUE TITLE
[Android] Balance BY

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#1171]
https://play.google.com/store/apps/details?id=com.vladyud.balance

Иногда невозможно обновить баланс при включенном Adguard.

**Comment by Alex-302** [comment]
нужен лог http запросов. И время неудачной попытки.
Желательно с выключенными фильтрами проверить

**Comment by Alex-302** [comment]
Не повтоярется.
Лог не нужен, а описание как повторить может поможет.

**Comment by vgavrish** [comment]
Реклама, в разделе "Аккаунты"  . У меня не повторяется
лог 
[debug (31).txt](https://github.com/AdguardTeam/AdguardFilters/files/368432/debug.31.txt)
Время 15:03 Кэш чистили
<details>
![screenshot_27](https://cloud.githubusercontent.com/assets/18548949/16907152/9b4ffe54-4cc9-11e6-96d9-4b3881465e93.jpg)
"enabledFilterIds" : [ 2, 3, 4, 14, 1, 11, 211 ],
  "filteringQuality" : "FULL",
 "versionName" : "2.6.108"
  "proxyMode" : true,
  "proxyPort" : 8080,
  "proxySetupManualMode" : false,
"sslMitmConfiguration" : "{\"appsExceptions\":\"48 apps\",\"mitmList\":\"168 domains\",\"mitmListMode\":\"WHITELIST\"}",

**Comment by Alex-302** [comment]
Разнотипные проблемы мешать в одной задаче не нужно, путаница ж будет.

Гуглореклама у него блокируется судя по логу. Если нажать на значек в правом верхнем углу, можно узнать, какая рекламная система. Пусть сообщит.

**Comment by vgavrish** [comment]
ок, написала

**Comment by vgavrish** [comment]
Пишет, что реклама от Google
![screenshot_39](https://cloud.githubusercontent.com/assets/18548949/17013148/0fa02736-4f25-11e6-9ce3-f1a24e4ddeec.jpg)

**Comment by Alex-302** [comment]
100% должна блокироваться. Может в файерволе натыкал. У него случайно не прокси с ручной настройкой? Ещё может быть что он вручную запускает защиту, и програма успевает подгрузить рекламу. Тогда нужно в настройках дроида остановить приложение и запустить после вкл защиты адгарда.

**Comment by Alex-302** [comment]
У меня даже без фильтрации HTTPS реклама блокируется.
