### ISSUE TITLE
rutracker.org (обслуживание вне очереди, сайт популярный)

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#1172]
http://rutracker.org/forum/index.php

Реклама "вулкана"
Что-то вулкана в последнее время много. Или рекламные сети изменились или кто-то .....

![default](https://cloud.githubusercontent.com/assets/9648798/12001112/c5c87aca-ab03-11e5-8e3c-f76aeb2f37a7.jpg)

**Comment by Alex-302** [comment]
Чисто. Если бы была не заблокированная реклама на этом сайте, уже была бы куча жалоб.

**Comment by ameshkov** [comment]
Может расширения какие-то установлены? Они же теперь советуют кучу разных расширений для обхода блокировки, с ними или без них проверяете?

**Comment by Embos** [comment]
Ты прав, Алекс. Это из кэша браузера она у меня подгрузилась.
Сидел какое-то время с отключенным Adguard.
Никак не могу запомнить эту фишку с кэшем.
Закрывай тему. Извини что отвлек.

**Comment by ameshkov** [comment]
@Alex-302 а заведи нам задачу про автоматический сброс кэша при включении защиты.
Можем что-нибудь простое замутить, типа первые 5 минут после запуска игнорировать кэш. Снимет такие проблемы.

**Comment by Alex-302** [comment]
создал
https://github.com/AdguardTeam/AdguardForWindows/issues/675

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/12009972/2a57a618-ac9a-11e5-9569-e35849594074.png)
NMA-611-88982

**Comment by Alex-302** [comment]
видать настраивали. У меня тоже есть.
добавил
```
||rutracker.org/brand/$image
||rutracker.org/iframe/$subdocument
||rutracker.org/misc/*-240x400
```

**Comment by ameshkov** [comment]
Лучше без $subdocument добавляй, а то в старых версиях не заработает.

**Comment by Alex-302** [comment]
Ок

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/12051215/10f28668-af09-11e5-9d7e-edb8c1c35dee.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.73.53 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.32 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.83 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.29.61 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.23 Enabled=YES

[iOS] BYM-659-35960

**Comment by ameshkov** [comment]
Русский фильтр 1.0.29.65, не могу повторить никак.
@evgeniy-ADG у вас есть кто-нибудь с айфоном/айпадом? Можете глянуть?

**Comment by Bohdan-SUP** [comment]
@Alex-302 cнова появилось
https://i.imgur.com/8WCQKxH.png

**Comment by Bohdan-SUP** [comment]
Фильтры обновил, проблема решена.

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/13884226/c5406986-ed35-11e5-832f-659a1af11739.png)
у меня вот так, обновлений фильтров нет, проверял, все актуальное
