### ISSUE TITLE
www.20min.ch - image slideshow is broken

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#1173]
http://forums.macrumors.com/threads/the-ios-9-content-blocker-thread.1916783/page-109#post-22398715

**Comment by ameshkov** [comment]
English filter
Spyware filter
German filter
Mobile ads filter
Safari filter
EasyList
EasyList Germany
ROList
Easyprivacy
Fanboys Annoyances
Fanboys Enhanced Tracking List
Adblock Warning Removal List
Malware Domains
Prebake
Spam404
Anti-Adblock Killer Reek

**Comment by Alex-302** [comment]
Can't reproduce in Windows and MacOS Safari(with Flash)

**Comment by ameshkov** [comment]
And what about HTML5 video?

**Comment by Alex-302** [comment]
There are no HTML5 on 20min.ch
Disabled Flash, and got the message about blocked Flash.

**Comment by Alex-302** [comment]
It works on iPad

**Comment by ameshkov** [comment]
Please read here:
http://forums.macrumors.com/threads/ios-9-content-blockers-mini-reviews.1918483/page-20#post-22500564

iOS, video is broken with German filter.

**Comment by Alex-302** [comment]
Opened this URL with iPhone user agent in Safari - the slideshow is working.
Filters - Eng, German, Spyware, Social, Experimental.

**Comment by ameshkov** [comment]
Ok then, close this issue.
