### ISSUE TITLE
www.hotnews.ro - video is broken

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#1174]
http://forums.macrumors.com/threads/the-ios-9-content-blocker-thread.1916783/page-109#post-22398715

**Comment by ameshkov** [comment]
English filter
Spyware filter
German filter
Mobile ads filter
Safari filter
EasyList
EasyList Germany
ROList
Easyprivacy
Fanboys Annoyances
Fanboys Enhanced Tracking List
Adblock Warning Removal List
Malware Domains
Prebake
Spam404
Anti-Adblock Killer Reek

**Comment by Alex-302** [comment]
Cant reproduce.
https://github.com/AdguardTeam/ExperimentalFilter/issues/1173
