### ISSUE TITLE
[iOS] login.wi-fi.ru, wi-fi.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#1175]
Реклама на странице 
http://prntscr.com/9i3p2p
http://prntscr.com/9i3pg9

GHX-914-41021

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/ExperimentalFilter/issues/1158

**Comment by Alex-302** [comment]
||cdn.vmet.ro/brandings/*/index.html$subdocument
||static.wi-fi.ru/brandings/rb/
||wi-fi.ru/ad_video/
Передавали эти правила?

**Comment by evgeniy-ADG** [comment]
ДА. "Да, данные правила работают и полностью скрывают рекламу.
Большое спасибо!"

**Comment by evgeniy-ADG** [comment]
Вы добавите в фильтры правила? Продолжают поступать обращения.

**Comment by ameshkov** [comment]
@Alex-302 а теперь есть жалобы, что появилась задержка в 5-7 секунд при входе:
http://forum.ru-board.com/topic.cgi?forum=5&topic=31105&start=3020#3

**Comment by Bohdan-SUP** [comment]
Если отключитесь фильтр RUAdList, после нажатия кнопки "Войти", начинает прокручиваться рекламный ролик.
Логи тут - KOB-761-23270

**Comment by Alex-302** [comment]
В RUAdList нет ничего, что блокирует рекламу в метро, и отсутствует у нас. У него многовато фильтров, пусть попробует выключить RUAdList и EasyList(этот вообще включать не нужно, если включен наш английский)
После отключения пусть попробует добавить
```
||login.wi-fi.ru/ad_video/
||ads.adfox.ru^
```
Второе должно изначально блокироваться. Первое заблокирует видео, запрошенное с adfox.
Если не поможет, то даже не знаю чем помочь. В дроиде чисто, только таймер висит.

@ameshkov 
Таймер в этом скрипте
https://login.wi-fi.ru/brandings/_common/metro-auth.js
ищется по "prepareVideo = function(banner) "
На iOS похоже не поправить, а на Дроиде - только с поддержной HTTPS.

**Comment by ameshkov** [comment]
Второе правило вряд ли нужно, а вот первое может и помочь

**Comment by Alex-302** [comment]
@Bohdan-SUP @evgeniy-ADG 
добавил новых правил в мобильный фильтр, посоветуйте юзерам обновить фильтры

**Comment by Bohdan-SUP** [comment]
Отписали, что все работает как положено.

**Comment by Alex-302** [comment]
атлична-атлична

**Comment by evgeniy-ADG** [comment]
Некорректная блокировка на странице:
https://login.wi-fi.ru/am/UI/Login?org=mac&service=coa&client_mac=5c-ad-cf-11-d8-0f&ForceAuth=true

По сути рекламы не видно, но нужно ждать столько же сколько идёт рекламный ролик.

XNQ-873-58796

Это чинится?

**Comment by evgeniy-ADG** [comment]
Запощщу тут ещё, чтобы не потерять.

Alex-302 commented 40 minutes ago

На iOS мгновенной авторизации как раньше не сделать. Это юзерам желательно в ответ писать. Раньше при блокировке видео перебрасывало на завершающую стадию, а теперь крутится таймер. В iOS его не убрать. Другие блокировщики для iOS тоже не могут(в лучшем случае скроют страницу с таймером, но ждать всё равно придётся)

**Comment by Bohdan-SUP** [comment]
Новые логи с проблемой в тикетах:
RJX-119-86087
ORT-370-98225

**Comment by Alex-302** [comment]
Не забывай нажимать Reopen issue если проблема появляется снова, чтоб не прозевать. Или лучше новую открывай. И метки кроме типа ОС желательно расставлять(Missed ads, и т.д. по необходимости)

Посоветуй пока фильтры вручную обновить, а то эти довольно старые
ID=11 Name="Mobile ads filter" Version=1.0.1.74 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.18 Enabled=YES
добавил пару правил, не знаю, поможет/не поможет....

**Comment by Alex-302** [comment]
С форума отписали, что все чисто.

**Comment by Alex-302** [comment]
Пусть обновления фильтров проверят.

**Comment by evgeniy-ADG** [comment]
Вроде бьі снова пропускаем

http://login.wi-fi.ru/am/UI/Login?rand=c.2M4wb2&org=mac&service=coa&client_mac=f0-f6-1c-64-d0-55&ForceAuth=true
http://prntscr.com/algeip
http://prntscr.com/algem9

**Comment by Alex-302** [comment]
@evgeniy-ADG 
проверить нечем. На дроиде чисто.

**Comment by ameshkov** [comment]
Так давай я айпад притащу тестовый

**Comment by Alex-302** [comment]
@ameshkov 
давай

**Comment by evgeniy-ADG** [comment]
Не нашли рекламы? Тут еще одна жалоба поступила: **1390020**

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.77.32 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.82 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.55 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.31 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.44 Enabled=YES

**Comment by Alex-302** [comment]
А сколько вообще пожаловавшихся?
Мобильный фильтр пусть включают.

**Comment by Alex-302** [comment]
И пусть отпишутся

**Comment by vbagirov** [comment]
@evgeniy-ADG не отписывались пока?

**Comment by evgeniy-ADG** [comment]
1 пожаловавшийся. Написал ему.

**Comment by evgeniy-ADG** [comment]
Снова иногда жалуются. вот так на iOS выглядит:

![image](https://cloud.githubusercontent.com/assets/15856304/22455009/6c18ee66-e792-11e6-8b6f-d75f6006d561.png)

<details>

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.32 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.4 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.20 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.59 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.97 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.45.14 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.4 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.59 Enabled=YES

**Comment by Alex-302** [comment]
> ID=15 Name="Simplified domain names filter" Version=1.0.0.59 Enabled=YES

пусть выключит и проверит снова. Не нужен этот фильтр.

**Comment by evgeniy-ADG** [comment]
ок, сюда его тоже можно? **https://github.com/AdguardTeam/AdguardFilters/issues/3855**

**Comment by Alex-302** [comment]
Нет. Там же видео(скорее всего из-за чрезмерного количества фильтров нужное правило вылетело)

**Comment by dzamyshlyayeva** [comment]
После того, как нажимаешь кнопку "Войти в интернет" система зависает на этом шаге
При отключенном Adguard проблем не возникает.

<details>

![image](https://cloud.githubusercontent.com/assets/23372054/24513115/184f4608-1579-11e7-8ac3-b0a8ea3503ed.png)

</details>

Ticket ID 1144547

**Comment by Alex-302** [comment]
В чате ж обсуждали уже. Жду от пользователей проверки предложенного решения.
У этого тоже можно попросить.
Читать с этого коммента:
https://github.com/AdguardTeam/AdguardFilters/issues/4670#issuecomment-289398844

**Comment by dzamyshlyayeva** [comment]
сейчас спрошу. спасибо
