### ISSUE TITLE
credit karma (ios)

### ISSUE THREAD

**Issue by jordanswrld23** [AdguardTeam/AdguardFilters#117575]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.3.3 (947)

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://apps.apple.com/us/app/credit-karma/id519817714

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

||tags.creditkarma.com^

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Cannot register. Is nothing broken?

**Comment by jordanswrld23** [comment]
nothing is broken. sorry. i forgot to respond to the other comment you left nothing is broken on that app either that was closed earlier

**Comment by Alex-302** [comment]
Ok, added.
