### ISSUE TITLE
SPA, POR Filter: record.pt

### ISSUE THREAD

**Issue by ruiumbelino** [AdguardTeam/AdguardFilters#11750]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
The Spanish/Portuguese filter has some entries with record.xl.pt, instead of record.pt

```
record.xl.pt###ifrPubManchete
record.xl.pt###mrecTop
record.xl.pt##.anuncios_cof
record.xl.pt##a[href^="http://ad-emea.doubleclick.net/"]
jornaldenegocios.pt,record.xl.pt##a[href^="http://ad.doubleclick.net/"]
record.xl.pt##a[href^="http://ad.pt.doubleclick.net/jump/"]
||record.xl.pt/pub/
||record.xl.pt/rec/i/pub
```

Can this be fixed?

**Comment by Alex-302** [comment]
these rules are obsolete. Removed.
