### ISSUE TITLE
extra (ios)

### ISSUE THREAD

**Issue by jordanswrld23** [AdguardTeam/AdguardFilters#117577]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.3.3 (947)

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://apps.apple.com/us/app/extra/id1489550124

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

||track.extra.app^

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld23** [comment]
also i have another filter ||vgs-collect-keeper.apps.verygood.systems^ it was in one of the three apps i posted idk if u can reproduce it

**Comment by Alex-302** [comment]
I hope nothing is broken, because I cannot login to this app.
