### ISSUE TITLE
xfuckonline.com [NSFW] [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#11769]
**Site**: http://xfuckonline.com/r/8027450/Porn-Sex-Couple%3A-Free-Indian-HD-Porn-Video-87/

**Issue**: Please remove the ads as seen in the screenshot.

**Screenshot**: http://prntscr.com/igcnx6

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Done.
