### ISSUE TITLE
felixgerschau.com

### ISSUE THREAD

**Issue by tgamauf** [AdguardTeam/AdguardFilters#117792]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.3

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://felixgerschau.com

### What filters do you have enabled?

AdGuard German filter

### Add your comment and screenshots

1. Website is blocked completely

2. Screenshots
<details><summary>Screenshot 1:</summary>
![IMG_2ABB1A21053A-1](https://user-images.githubusercontent.com/4630030/167143112-8b1b9df0-ec99-4358-86f6-07c5b2da43ca.jpeg)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please send report from AdGuard.
https://kb.adguard.com/en/technical-support/reporting-tool#ios
