### ISSUE TITLE
[iOS] missed frame on m.sports.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1178]
![image](https://cloud.githubusercontent.com/assets/15856304/12002726/53849752-ab10-11e5-8056-1a2876e5b921.png)

http://m.sports.ru/football/1035680926.html
http://prntscr.com/9i4z24

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.71.60 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.3.84 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.35 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.28.75 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.12 Enabled=YES

YFZ-563-29075

**Comment by Alex-302** [comment]
Не повторяется,
