### ISSUE TITLE
Shortlink immediately closed

### ISSUE THREAD

**Issue by terlancenablari** [AdguardTeam/AdguardFilters#117921]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

latest beta version

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://tei.ai/ACRh6pnONE2

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Self-destruction of first-party cookies, Self-destruction of third-party cookies, Disable cache for third-party requests, Block WebRTC, Block Push API, Block Location API

### Add your comment and screenshots

![screenshot-160](https://user-images.githubusercontent.com/81357816/167252810-9a0b54a1-7b13-4d81-80a2-2477d2f87878.png)

### Privacy

- [X] I agree to follow this condition

**Comment by mrrtarlan** [comment]
@Alex-302 is not possible to resolve this issue?

**Comment by AdamWr** [comment]
Could you please describe what exactly is a problem here?

Website works fine on my end. With `AdGuard Annoyances filter` enabled, after a while, I'm automatically redirected to the destination page.
With `AdGuard Annoyances filter` disabled I have to wait and click few times on "continue" button and then I'm redirected to the same page.
