### ISSUE TITLE
Site doesn't work with AG

### ISSUE THREAD

**Issue by terlancenablari** [AdguardTeam/AdguardFilters#117931]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

latest beta

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://link1s.com/ACRqN2HCcJL

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

![screenshot-162](https://user-images.githubusercontent.com/81357816/167256303-b0dbfd19-8372-4768-8ec8-2ddea6286da4.png)

IF i am now wrong, AG URL tracking filter causes this problem.

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Error says DNS returned no domain. Please try to disable DNS protection. Cannot reproduce with AdGuard DNS.

**Comment by terlancenablari** [comment]
> Error says DNS returned no domain. Please try to disable DNS protection. Cannot reproduce with AdGuard DNS.

I was using Cloudflare's secure dns, turned it off and switched to AG DNS, in the result of this the problem has gone. so it means this issue is related to cloudflare's dns. thanks BlazDt

**Comment by BlazDT** [comment]
You are welcome.
