### ISSUE TITLE
www.computingforgeeks.com

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#117995]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.0.161

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://computingforgeeks.com/how-to-install-php-on-arch-linux-and-manjaro/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

Empty spaces in between

![image](https://user-images.githubusercontent.com/46019727/167281533-34b477ed-6aab-4aad-b7cd-35f148713821.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Bhooty** [comment]
bump

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
