### ISSUE TITLE
gputracker.eu

### ISSUE THREAD

**Issue by SW1FT** [AdguardTeam/AdguardFilters#117952]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.42.5b3 (doesn't matter since it's a filter problem)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

gputracker.eu

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

GPUTracker price graphs are being erroneously blocked by the filter: `gputracker.eu##+js(set-constant, can_show_ads, true)` present in [AdGuard Annoyances filterlist](https://github.com/AdguardTeam/AdguardFilters/blob/9fead76854c9dd3585b79fc03d01885d9bdf72e6/AnnoyancesFilter/sections/antiadblock.txt#L1222).

STR:
1. Open https://www.gputracker.eu/en/product/26984/asus-tuf-rtx3080-o10g-v2-gaming-gddr6x-2xhdmi-2-1-
2. Click on "Show price history chart"
3. Observe the fact that the graph does not show

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
