### ISSUE TITLE
instagram.com

### ISSUE THREAD

**Issue by Saikur0n** [AdguardTeam/AdguardFilters#118049]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.9.1

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://instagram.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment> AdGuard's annoyances filter blocks instagram's web popup asking to enable notification in browser on the first login. I think for some people it is useful to see this notification, for example gmail also asks to enable desktop notifications, but the message from gmail isn't hidden.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot 2022-05-08 161649](https://user-images.githubusercontent.com/72514237/167293945-014d9cce-10b5-4e71-9875-8966e3435193.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Works as designed for Annoyamces filter. I do not see that message on Gmail.

**Comment by Saikur0n** [comment]
> Works as designed for Annoyamces filter. I do not see that message on Gmail.

In gmail it is small message on the left side corner when you login first time. Then on instagram it is another adguard's filter that hides this message.
