### ISSUE TITLE
[iOS] video.foxnews.com - player is broken

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1180]
Basically, the video froze at the first frame after pressing the play button. All the videos in foxnews were affected. Such problem didn't occur on iPhone though. Seems like it's exclusive to iPad, even with the same set of filters turned on.

![image](https://cloud.githubusercontent.com/assets/15856304/12002910/d33bed2e-ab15-11e5-8726-1c48b30d39ae.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.73.24 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.26 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.79 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.84 Enabled=NO
ID Name="Mobile ads filter" Version=1.0.1.88 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.20 Enabled=YES
ID1 Name="EasyList" Version=1.0.49.45 Enabled=NO
ID4 Name="EasyList China" Version=1.0.49.66 Enabled=YES
ID8 Name="EasyPrivacy" Version=1.0.47.85 Enabled=NO
ID2 Name="Fanboy's Annoyances" Version=1.0.49.57 Enabled=YES
ID3 Name="Fanboy's Social Blocking List" Version=1.0.49.45 Enabled=YES
ID!5 Name="Fanboy's Enhanced Tracking List" Version=1.0.1 Enabled=YES
ID 7 Name="Adblock Warning Removal List" Version=1.0.49.50 Enabled=YES
ID 9 Name="Prebake" Version=1.0.1 Enabled=YES
ID!1 Name="Anti-Adblock Killer | Reek" Version=1.0.1.55 Enabled=YES

XBV-980-15322

**Comment by Alex-302** [comment]
Не повторяется.
Посоветуй выключать фильтры по одному с конца, с проверкой после каждого выключения, Может удастся найти проблемный.

**Comment by evgeniy-ADG** [comment]
done
