### ISSUE TITLE
[Android] Ads in apps My Stocks Portfolio, TripIt, The Weather Network

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#1182]
https://play.google.com/store/apps/details?id=co.peeksoft.stocks
https://play.google.com/store/apps/details?id=com.tripit&hl=en
https://play.google.com/store/apps/details?id=com.pelmorex.WeatherEyeAndroid&hl=en

Screenshots and HTTP requests log in this ticket: TFQ-271-40774

**Comment by Alex-302** [comment]
For WeatherUnderground added
||imwx.com/mobile/adconfig/$empty

tripit - clean
co.peeksoft.stocks - is clean on my end(only ads placeholder)
pelmorex.WeatherEye - clean too
