### ISSUE TITLE
The description of Dandelion Sprout's Annoyances List should warn about changing websites' appearance

### ISSUE THREAD

**Issue by dave-holland** [AdguardTeam/AdguardFilters#118460]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.8.1.1140 release (CL-1.9.62, DNS-1.7.22)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Desktop

### Where is the problem encountered?

many websites

### What filters do you have enabled?

Dandelion Sprout's Annoyances List

### Add your comment and screenshots

1. Dandelion Sprout's Annoyances List [includes Dandelion Sprout's Website Stretcher](https://github.com/AdguardTeam/AdguardFilters/issues/118103#issuecomment-1123525414), which is a very opnionated list that alters the look of many websites. Most narrow webpages are narrow because it's easier to read, not because "[many websites still think that everyone are using narrow monitors](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Dandelion%20Sprout's%20Website%20Stretcher.txt)". This list shouldn't be embedded in a annoyance filter in the first place. However, if it has to, the description should warn the user that the filter alters websites' looks and may break them.

2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="1624" alt="Xnip2022-05-12_09-35-36" src="https://user-images.githubusercontent.com/90854657/168087668-3cead87b-b21a-432f-80d6-33ac01a8c4bf.png">

With Dandelion Sprout's Annoyances List on, GitHub's profile page slightly broken

</details>

<details><summary>Screenshot 2:</summary>

<img width="1624" alt="Xnip2022-05-12_09-36-09" src="https://user-images.githubusercontent.com/90854657/168087708-90191363-458f-4ad6-be76-1903b21801db.png">

With Dandelion Sprout's Annoyances List off

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
Worth noting:
1) You're in fact the 2nd person this week who've been confused about that sublist being included, which in turn has confused me.
2) Wider article bodies = More text/buttons visible at once before needing to scroll = Less window space wasted. This is especially the case on Wikia and Pixiv.
3) That's not what "Opinionated" means, especially with the theorethically very broad meaning the term "Annoyances" has taken on in the adblock community. "Opinionated" would've been if I started blocking Steven Universe sites in that list or anything like that.

**Comment by Alex-302** [comment]
In fact, there is already a hint of this in the description.
![image](https://user-images.githubusercontent.com/8361299/168295310-b35be31c-6758-48de-b196-cbc2c62536b4.png)

**Comment by DandelionSprout** [comment]
@Alex-302 I get the feeling you're mixing up "Dandelion Sprout's Annoyances List" with "Web Annoyances Ultralist", but thanks anyway. 😅

**Comment by Alex-302** [comment]
Damn)
