### ISSUE TITLE
Title description for filter sections

### ISSUE THREAD

**Issue by RicoHeat** [AdguardTeam/AdguardFilters#118544]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Individual filters sections dont have title description individually.

### Proposed solution

Would make things more esthetically pleasing and easier to manage if each section had the title description example 
! Title: "English Filter - Content Blocker"
Currently whenever manually adding section lists to addons like uBlock it just displays their raw web download address as it's Title.
Just a suggestion. The examples on each section of good and bad filters makes for such great learning tools.. Thanks for the great work and have a great day! 👍

**Comment by Alex-302** [comment]
All metadata already exist
https://filters.adtidy.org/extension/ublock/filters/2_without_easylist.txt
```
![Adblock Plus 2.0]
! Checksum: VrDF49r9JCWAauG3mNsxng
! Title: AdGuard Base filter
! Description: This filter is necessary for quality ad blocking.
! Version: 2.2.30.84
! TimeUpdated: 2022-05-17T09:31:17+00:00
! Expires: 4 days (update frequency)
! Homepage: https://github.com/AdguardTeam/AdGuardFilters
! License: https://github.com/AdguardTeam/AdguardFilters/blob/master/LICENSE
!
```

**Comment by RicoHeat** [comment]
If I only want to use English Filters Adservers?
>! Title: Example

https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/EnglishFilter/sections/adservers.txt

>!
! This section contains the list of third-party advertising networks domains.
! Note, that we only put rules that block full domains here and not URL parts (there's `general_url.txt` for that). Also, it must be domains that are used in a third-party context.
! The rules with hints are at the end of file.

>! Good: ||doubleclick.net^$third-party
! Bad: /banner.jpg (should be in general_url.txt)
! Bad: ||adssubdomain.legitwebsite.com^ (should be in adservers_firstparty.txt)

**Comment by Alex-302** [comment]
It's unlikely that we would duplicate metadata in every file.
