### ISSUE TITLE
mayo (ios)

### ISSUE THREAD

**Issue by jordanswrld23** [AdguardTeam/AdguardFilters#118788]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.0 (954)

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://apps.apple.com/us/app/mayo-clinic/id523220194

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

||tagdelivery.mayoclinic.org^

app works fine with blocked

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld23** [comment]
@Alex-302

**Comment by jordanswrld23** [comment]
@Alex-302

**Comment by Alex-302** [comment]
Hi. I am on vacation.
Please mention me if issues marked as Stale.

**Comment by Alex-302** [comment]
Fixed.
