### ISSUE TITLE
math.semester.ru [Anti-Adblock]

### ISSUE THREAD

**Issue by hant0508** [AdguardTeam/AdguardFilters#11882]
***Description***:

The "next" button is inactive and there's a request to disable ad blocker.

To make the button active you have to whitelist `https://recreativ.ru/rcode.0cd55aeee1.js`. The filter `||recreativ.ru/rcode.*.js$important` from **Adguard Russian Filters** prevents excluding `https://recreativ.ru/rcode.0cd55aeee1.js`.

***Steps to reproduce the problem***:
1. Visit https://math.semestr.ru/gauss/rang.php
2. Click "Далее" ("next") button
![screenshot_2018-02-19 2](https://user-images.githubusercontent.com/28459131/36386776-f69ce8e6-15a7-11e8-91f8-8fc702d71642.png)
3. On this page "next" button is inactive
![screenshot_2018-02-19 1](https://user-images.githubusercontent.com/28459131/36386781-f8d1a64c-15a7-11e8-8f7e-126b142a60fa.png)

***System configuration***

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Debian GNU/Linux
Browser:                               | Firefox 58.0.2
AdGuard version:                       | NOT Adguard: uBlock Origin 1.15.7b3
Filters enabled:                       | Adguard Russian Filters
AdGuard DNS:                           | None

**Comment by hant0508** [comment]
Filter `.adriver.` also breaks the page: https://github.com/uBlockOrigin/uAssets/issues/1571#issuecomment-366771422

**Comment by Alex-302** [comment]
Создавать можно по-русски.

**Comment by hant0508** [comment]
Для uBO проблема по-прежнему актуальна, поскольку `important` там имеет другой приоритет:
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#important

**Comment by Alex-302** [comment]
Подправил для uBO.
