### ISSUE TITLE
Google's usp parameter

### ISSUE THREAD

**Issue by stdedos** [AdguardTeam/AdguardFilters#118978]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

N/A

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://docs.google.com/document/u/0/

### What filters do you have enabled?

AdGuard URL Tracking filter

### Add your comment and screenshots

Clicking "Drive" here

![image](https://user-images.githubusercontent.com/133706/168756816-c7df41d2-4441-44f2-861a-b123af8acf3a.png)

from https://docs.google.com/document/u/0/ leads to https://drive.google.com/u/0?usp=docs_home, which is clear cut tracking

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reproduced. Are the values of this parameter always low-informative(for analytical purposes)?

**Comment by stdedos** [comment]
The issue with this flow is that: 
- parameter stays in view for a very brief time (YMMV with regards to your network connection) 
- the "trick" to open devtools on that "popup tab" does not work because of the way that this "flow" works

**Comment by Alex-302** [comment]
> Everytime I have seen this parameter, it does not appear "mission critical"

Indeed)
I'm not sure if it makes sense to block this parameter.
