### ISSUE TITLE
Stackoverflow (and family) "Share" links mustn't be hidden

### ISSUE THREAD

**Issue by stdedos** [AdguardTeam/AdguardFilters#119133]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

N/A

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

Any https://stackoverflow.com/questions/

### What filters do you have enabled?

AdGuard Social Media filter

### Add your comment and screenshots

From list
```
! Title: AdGuard Social Media filter
```

the `##.js-share-link` (targeting SO?) interferes with this
![image](https://user-images.githubusercontent.com/133706/169079750-521e7be2-6170-47cc-bbd5-bef731a762be.png)

which is super-problematic if you want to link to an answer directly - as there's no other way to get a link to any answer AFAIK

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Hello,
This issue has been fixed 3 days ago - https://github.com/AdguardTeam/AdguardFilters/commit/4f83c65ebd5a5afa1c5ebde97c3bb71ad92d6998
Please update filters and check again.

**Comment by stdedos** [comment]
That's weird 😕 I only saw this behavior happening yesterday; I was sure it was recent.

Apologies 😅
