### ISSUE TITLE
AdGuad Spyware filter is blocking CoMagic 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#11931]
> CoMagic <https://www.comagic.ru/> - сервис оценки эффективности рекламы и повышения конверсии сайта, предлагает клиентам набор инструментов, в частности, коллтрекинг (подмену номера телефона на сайте для каждого посетителя), обратный звонок, онлайн 
> консультант. Чтобы данные инструменты работали, клиентам необходимо 
> добавить на сайт код.
> 
> Один из наших клиентов использует браузерное расширение AdGuard, в частности, фильтр "Фильтр счетчиков и систем аналитики". Оказалось, что при включенном фильтре блокируется скрипт CoMagic, и у клиента не работает ни коллтрекинг, ни обратный звонок, ни онлайн консультант.
> 
> Наш код блокируется, т.к. домен comagic.ru находится в данных списках https://filters.adtidy.org/extension/chromium/filters/15.txt и https://filters.adtidy.org/extension/chromium/filters/3.txt. Не могли бы вы подсказать, почему наш домен попал в данные списки, и к кому обратиться, чтобы исключить его из данных списков, чтобы клиенты могли использовать все возможности продукта?

ID - 1762252

**Comment by Alex-302** [comment]
Нужен пример такого сайта(стороннего).

**Comment by VicktoriaF** [comment]
Вот пример. Как должно работать:
<img width="960" alt="default" src="https://user-images.githubusercontent.com/36657942/36473565-e821bfda-1705-11e8-9ccd-ac1769d7c606.png">
Что получается при включенном расширении AdGuard с фильтром "Фильтр счетчиков и систем аналитики".
<img width="960" alt="default" src="https://user-images.githubusercontent.com/36657942/36473614-1126d082-1706-11e8-8305-138fddd8f079.png">

**Comment by Alex-302** [comment]
Всё верно. Сервис собирает аналитику, поэтому блокируется.
Мы могли бы блокировать только `tracker.comagic.ru`, но при блокировке ломается виджет(в ответ на отправленную аналитику присылается какой-то конфиг, что ли, необходимый для работы.)

**Comment by Alex-302** [comment]
Фильтр аналитики опциональный, так что не вижу большой проблемы.

**Comment by VicktoriaF** [comment]
Т.е. блокировка comagic.ru сделана специально, чтобы при блокировке tracker.comagic.ru не поломать виджет?
И можете подсказать, по какому принципу пополняется этот список https://filters.adtidy.org/extension/chromium/filters/15.txt? Наш клиент не очень понимает, почему блокируют только нас, когда наши конкуренты также собирают статистику, но при этом их скрипты не блокируются.

**Comment by Alex-302** [comment]
> Т.е. блокировка comagic.ru сделана специально, чтобы при блокировке tracker.comagic.ru не поломать виджет?

нет. Если вы причастны к этому сервису, можете передать, чтоб конфигурация передавалась другим способом, чтоб сбор аналитики был отделён(как делает большинство разработчиков).

> Наш клиент не очень понимает, почему блокируют только нас, когда наши конкуренты также собирают статистику, но при этом их скрипты не блокируются.

наверное мы о них не знаем) Сообщите о них, и мы примем меры)

Конкретно из https://filters.adtidy.org/extension/chromium/filters/15.txt правило могу убрать, но из фильтра аналитики пока нет.

**Comment by VicktoriaF** [comment]
> наверное мы о них не знаем) Сообщите о них, и мы примем меры)

Куда сообщить?) Здесь список написать? 

Да, к сервису я причастна, разработчикам вашу рекомендацию передала. 
Если возможно, то уберите правило хотя бы отсюда  https://filters.adtidy.org/extension/chromium/filters/15.txt

**Comment by Alex-302** [comment]
Да сюда можно, или с помощью репортилки https://reports.adguard.com/ru/new_issue.html
> уберите правило хотя бы отсюда

убрал

**Comment by VicktoriaF** [comment]
Спасибо за помощь!

**Comment by ameshkov** [comment]
> Спасибо за помощь! А вот форма эта не самая понятная.

Да можете просто здесь "New Issue" создать.

Вся суть фильтра аналитики -- не дать собирать пользовательские данные сторонним сервисам. Сторонним, в данном контексте, означает домены, отличные от домена сайта, на который заходит пользователь.

Условно, посещаю я example.org, и совершенно не хочу, чтобы данные о моем посещении записывались и анализировались какой-либо еще компанией. Вот примерно такова мотивация пользователей, которые включают этот фильтр.

**Comment by VicktoriaF** [comment]
Добрый день!
Прошу прощения за долгий ответ!
Спасибо за информацию! Я сообщала о других сервисах по почте, общаясь с тех поддержкой. Но пока не вижу их в этом списке https://filters.adtidy.org/extension/chromium/filters/3.txt
По вашему совету создала новый тикет https://github.com/AdguardTeam/AdguardFilters/issues/14853, но не знаю, кого назначить исполнителем и какие теги присвоить заявке.

**Comment by Alex-302** [comment]
ещё не дошла очередь. Сегодня-завтра гляну.
