### ISSUE TITLE
odia.ig.com.br

### ISSUE THREAD

**Issue by pintassilgo** [AdguardTeam/AdguardFilters#119334]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.42.4

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://odia.ig.com.br/esporte/coluna-do-vene/2022/05/6405115-de-pessimo-ambiente-no-ninho-a-processo-de-fritura-relacao-de-diego-alves-com-comissao-escancara-a-falta-de-comando-no-flamengo.html

### What filters do you have enabled?

AdGuard Spanish/Portuguese filter

### Add your comment and screenshots

Without `AdGuard Spanish/Portuguese filter` filter list enabled, things work as expected: article content is automatically expanded with no ad elements.
<details><summary>Screenshot of expected result (filter list disabled):</summary>

![image](https://user-images.githubusercontent.com/5483864/169462062-2da1a25a-04db-4ec2-940e-1f2a5cf34357.png)</details>

With the mentioned filter list enabled, the article content is initially collapsed, and after you click to expand it there are blank elements where ads would be displayed if they aren't blocked.
<details><summary>Screenshot 1 of the issue (filter list enabled)</summary>

![image](https://user-images.githubusercontent.com/5483864/169463162-f109f7f8-09f5-4dbd-8ca2-0c739178f43c.png)</details>
<details><summary>Screenshot 2 of the issue (filter list enabled)</summary>

![image](https://user-images.githubusercontent.com/5483864/169463237-ee696e4d-0a07-4288-abfb-4d89e3293f3c.png)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Actually, it doesn't depend on AdGuard - this is due to the behavior of the site.
