### ISSUE TITLE
price.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#11944]
https://spb.price.ru/kompyuternye-bloki-pitaniya/aerocool-kcas-750m/

 1. Просьба подписаться (для появления - очистить куки): `price.ru##[data-region="bumerang_email"]`
 2. Реклама сторонних товаров под описанием искомого: `price.ru##.b-announce-queries`

<details><summary>Screenshot:</summary>

![spb price ru](https://user-images.githubusercontent.com/17948007/36413283-c22136da-162e-11e8-9871-1855c95362e2.png)
</details>

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.8.5 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
поправил

**Comment by XX-J** [comment]
Баннер в верхней части страницы.

<details><summary>Screenshot:</summary>

![2019 10 24-1](https://user-images.githubusercontent.com/17948007/67507597-e0970900-f697-11e9-9584-1043c40c88de.png)
</details>

[https://spb.price.ru/noutbuki/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://spb.price.ru/noutbuki/)

`price.ru###kontainer-top`

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.3.1
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики
