### ISSUE TITLE
kinogo.co

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#1194]
Реклама фоном.

Плюс плеер не запускается с включенным Адгардом.

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/ExperimentalFilter/issues/1156

**Comment by Alex-302** [comment]
||ripemember.com/js/$third-party

**Comment by Bohdan-SUP** [comment]
Остается пустое место от баннера:
https://i.imgur.com/Wvgvpbw.png

**Comment by Alex-302** [comment]
Проверь обновления. У меня чисто.

**Comment by evgeniy-ADG** [comment]
[линк](http://kinogo.co/5979-snupi-i-meloch-puzataya-v-kino-2015.html)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13144617/56591592-d654-11e5-96f2-6bd211255247.png)

</details>

**Comment by Alex-302** [comment]
добавил
||tromen.ru^$third-party

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/13743016/fb3be57a-e9e7-11e5-840c-9f3839265797.png)

У нас тоже есть, скрин мой.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
всегда нужно прямую ссылку приводить, по любому поводу и без повода, т.к. на главной чисто

Добавил:
```
||float-l.ru^$third-party
```

**Comment by evgeniy-ADG** [comment]
http://kinogo.co/5860-agenty-schit-3-sezon.html
http://prntscr.com/aq1mtm

+ на заднем фоне при клике идет перенаправление

**Comment by Bohdan-SUP** [comment]
Снова реклама снизу:
![image](https://cloud.githubusercontent.com/assets/14153331/15273674/fc5695fc-1aa9-11e6-9f85-6e581b63baff.png)

**Comment by evgeniy-ADG** [comment]
> 
> К сожалению, всё так же. Реклама в плеере появляется при нажатии на кнопку плей.
> Когда включаю экспериментальный фильтр и обновляю страницу, плеер пропадает (использовал браузер опера и microsoft edge) - одинаково и в том и в другом.
> Как выключу этот фильтр плеер возвращается.
> Правил не создавал и проверил их отсутствие перед обращением к вам.
> Скрины прилагаю. Там все фильтры, которые установлены

> Теперь плеер есть. Только реклама осталась
![image](https://cloud.githubusercontent.com/assets/15856304/15672314/a1553be0-2738-11e6-82f5-ed0c895174b9.png)

**Comment by Alex-302** [comment]
Поправил.
При ответе снимайте метку Fixed, иначе проблема может затеряться.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
>Снова реклама снизу:

это не реклама, а инструкция по обходу блокировки

**Comment by Bohdan-SUP** [comment]
@Alex-302 - это ведь Annoyance, нет?

**Comment by Alex-302** [comment]
ну, однажды она пригодится)
Давай пока не будем блокировать. Если будут ещё жаловаться на подобные сообщения - тогда подумаем.
