### ISSUE TITLE
ADGuard for Free

### ISSUE THREAD

**Issue by LezheGao** [AdguardTeam/AdguardFilters#119595]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

There aren't an ADGuard for Free.

### Proposed solution

Add "ADGuard for free"that had less function and change the name of the ADGuard that need to pay to "ADGuard Pro"

### Additional information

@adguard-bot @adguard

**Comment by zloyden** [comment]
It does not relate to AdGuard filters.
However, you can submit your proposal to one of the [appropriate repositories](https://github.com/AdguardTeam).
