### ISSUE TITLE
Shazam can't search when traffic control is enabled in Adguard

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardFilters#119776]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.8

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

Shazam app

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, EasyPrivacy, Online Malicious URL Blocklist

### Add your comment and screenshots

Hi,

I have found this unusual behaviour which is observed on my old Android 8 phone.
See attached picture below.

When traffic control is enabled in Adguard, Shazam assumes it is offline and can't search for tracks.
But as soon as I disable traffic control, Shazam immediately can access it database to identify a track.

I've been using both apps on this phone for a number of years with no issues. Why is this happening now?

Thanks.

https://i120.fastpic.org/big/2022/0525/22/92b5b72299b4f2ccfe35e492a3e85f22.jpg

### Privacy

- [X] I agree to follow this condition

**Comment by jbionic2016** [comment]
Anybody home?

**Comment by jbionic2016** [comment]
Yeah, that's the whole point. My Android 11 tablet doesn't have the problem either, but my old Android 8 smartphone is somehow exposed to the problem

**Comment by BlazDT** [comment]
Then it looks like not a filters issue (likely some I compatibility with older Android). Sadly I cannot test again as I only have that one device. Have to wait for colleague if he can reproduce issue.

**Comment by jbionic2016** [comment]
I don't mind if you duplicate the issue to the Android fork and close it here

**Comment by jbionic2016** [comment]
What actions from my side are required at this point?

**Comment by zloyden** [comment]
I do not have an older Android, but on my Android 11 it works fine.
It looks like this does not related to the filters, will move the task to our Android repo.

**Comment by zloyden** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #4179](https://github.com/AdguardTeam/AdguardForAndroid/issues/4179) via [**ZenHub**](https://www.zenhub.com/)

**Comment by BlazDT** [comment]
Thank you. Android did not show up as target when I hit the transfer button

**Comment by zloyden** [comment]
@BlazDT you are welcome.
