### ISSUE TITLE
How can I block this cookie?

### ISSUE THREAD

**Issue by dcxstq2** [AdguardTeam/AdguardFilters#119855]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

`donanimhaber.com` website seems to have the Google analytic cookie. I tried this `||donanimhaber.com^$cookie=_ga_` rule but it doesn't show up in the filtering log. Rule wrong?

<details>
 <summary>Screenshot</summary>

![resim png-mh](https://user-images.githubusercontent.com/104112959/170302183-dedc21c4-497d-4fd1-8946-fc713d28aa83.png)

</details>

Documentation about the `_ga_` cookie

`https://business.safety.google/adscookies/`

### Proposed solution

-

### Additional information

-

**Comment by AdamWr** [comment]
This rule:
```
$cookie=/^_ga_/
```
should remove/block this cookie and as far as I can see, we had such rule in filters, but for some reason it has been removed - https://github.com/AdguardTeam/AdguardFilters/commit/44452ef88930e15c0fd647fde87ead6480f334ca
As I recall, it was breaking one website (`gigabyte.com`).

@Alex-302 Could we re-add this rule?
I see that exception was re-added - https://github.com/AdguardTeam/AdguardFilters/commit/dda1e5e19bf2d9b7b5cf5fb0c22cb18bf5c7ec75, but rule to block it wasn't.
Was this rule breaking more websites?

**Comment by Alex-302** [comment]
@AdamWr Yes, we can try again)

**Comment by AdamWr** [comment]
Okay, added.
Thank you for your reply.
