### ISSUE TITLE
missed ads (html5 player) - tvnow.de/vox/auto-mobil/

### ISSUE THREAD

**Issue by razzor1984** [AdguardTeam/AdguardFilters#11989]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
If you go to https://www.tvnow.de/vox/auto-mobil/
and start watching videos - all ads will be blocked
* **Current behaviour**: 
If you go to https://www.tvnow.de/vox/auto-mobil/
and start watching videos - the first ads will not be blocked

[//]: # (Substitute this line with a description of the problem)

The first ads arnt blocked, they use some kinde of new Html5 player which uses the new drm function

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>screenshot</summary>

https://imgur.com/a/FFxzW
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

Adguard should block all Ads 

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:
Go to https://www.tvnow.de/vox/auto-mobil/ and start watching the newst Auto-mobile version

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**
Englisch Filter & German Filter & Experimental Filter 
[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                     |windows 10 
Operating system version (Android/iOS)  | 1709
Browser:                               | FF-58.02
AdGuard version:                       |  6.2
Filters enabled:                       |  Englisch/German/Experimental Filter
AdGuard mode (Android only):       | - 
Filtering quality (Android only):     | -
HTTPS filtering (Android only):      | -
Simplified filters (iOS only)         | -
AdGuard DNS:                          | None 
Stealth mode options (Windows only)  | on
Helpdesk ID (if exists):              | -

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
What i found out:  
They use an adaptation of https://github.com/sitexw/BlockAdBlock
https://bilder-a.akamaihd.net/ip/js/ipdvdc/blockadblock.min.js
https://tvnowstatic-a.akamaihd.net/lib/rtli/rtli-js-tracking/build/RTLiVideotracking.min.js
[TVnow-Antiadblock Js scripts unobfuscated.zip]
(https://github.com/AdguardTeam/AdguardFilters/files/1741807/TVnow-Antiadblock.Js.scripts.unobfuscated.zip)

Thirdparty crap which isnt necessary can be blocked(in my optinion)
adform.com
adition.com
bidswitch.net
doubleclick,net
nuggad.bet
smartclip.net
spotxchange.com
svconm.com
technical-service.net
theadex.com
some times - schneevonmorgen

[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Not reproduced with given filter lists and browsers.

@AdamWr please check.

**Comment by razzor1984** [comment]
Enabled Spayware filter - still loading ads during @ video start

**Comment by AdamWr** [comment]
I can't reproduce ads.

**Comment by razzor1984** [comment]
ist the video loading? im not sure if the have a geo block outsid the DACH 
Which filter list are you using?

**Comment by BlazDT** [comment]
We tried the same filters as you listed above. As I'm located in Germany I doubt it is a geo-block.

**Comment by AdamWr** [comment]
I checked it with VPN (German IP), with English and German filter only and video works fine.
I can reproduce ads, if I disable this rule:
```
tvnow.de#%#"use strict";function e(e,t){e.__defineGetter__("responseText",function(){return t}),e.__defineGetter__("response",function(){return t})}function t(t){try{var n=JSON.parse(t.responseText);n.ignoreAd=!0,n.noad=!0,n.geoblocked=!1,n.free=!0,n.blockadeText="0",n.format.enableAd=!1,n.format.hasFreeEpisodes=!0,n.format.isGeoBlocked=!1,e(t,JSON.stringify(n))}catch(e){}}function n(){document.arrive(".button.now-freebutton > input.ng-empty",function(){this&&this.parentNode&&this.parentNode.click()})}var r=window.XMLHttpRequest.prototype.open;window.XMLHttpRequest.prototype.open=function(e,n,o){return n.includes("/v3/movies/")&&this.addEventListener("readystatechange",function(){4===this.readyState&&t(this)},!0),r.apply(this,[].slice.call(arguments))};var o=function(e,t,n){function r(e,t,n){c.addMethod(t,n,e.unbindEvent),c.addMethod(t,n,e.unbindEventWithSelectorOrCallback),c.addMethod(t,n,e.unbindEventWithSelectorAndCallback)}function o(e){e.arrive=d.bindEvent,r(d,e,"unbindArrive"),e.leave=f.bindEvent,r(f,e,"unbindLeave")}if(e.MutationObserver&&"undefined"!=typeof HTMLElement){var i=0,c=function(){var t=HTMLElement.prototype.matches||HTMLElement.prototype.webkitMatchesSelector||HTMLElement.prototype.mozMatchesSelector||HTMLElement.prototype.msMatchesSelector;return{matchesSelector:function(e,n){return e instanceof HTMLElement&&t.call(e,n)},addMethod:function(e,t,n){var r=e[t];e[t]=function(){return n.length==arguments.length?n.apply(this,arguments):"function"==typeof r?r.apply(this,arguments):void 0}},callCallbacks:function(e){for(var t,n=0;t=e[n];n++)t.callback.call(t.elem);},checkChildNodesRecursively:function(e,t,n,r){for(var o,i=0;o=e[i];i++)n(o,t,r)&&r.push({callback:t.callback,elem:o}),o.childNodes.length>0&&c.checkChildNodesRecursively(o.childNodes,t,n,r)},mergeArrays:function(e,t){var n,r={};for(n in e)r[n]=e[n];for(n in t)r[n]=t[n];return r},toElementsArray:function(t){return "undefined"==typeof t||"number"==typeof t.length&&t!==e||(t=[t]),t}}}(),l=function(){var e=function(){this._eventsBucket=[],this._beforeAdding=null,this._beforeRemoving=null};return e.prototype.addEvent=function(e,t,n,r){var o={target:e,selector:t,options:n,callback:r,firedElems:[]};return this._beforeAdding&&this._beforeAdding(o),this._eventsBucket.push(o),o},e.prototype.removeEvent=function(e){for(var t,n=this._eventsBucket.length-1;t=this._eventsBucket[n];n--)e(t)&&(this._beforeRemoving&&this._beforeRemoving(t),this._eventsBucket.splice(n,1));},e.prototype.beforeAdding=function(e){this._beforeAdding=e},e.prototype.beforeRemoving=function(e){this._beforeRemoving=e},e}(),a=function t(r,o){var t=new l(),i=this,a={fireOnAttributesModification:!1};return t.beforeAdding(function(t){var n,c=t.target;t.selector,t.callback,(c===e.document||c===e)&&(c=document.getElementsByTagName("html")[0]),n=new MutationObserver(function(e){o.call(this,e,t)});var l=r(t.options);n.observe(c,l),t.observer=n,t.me=i}),t.beforeRemoving(function(e){e.observer.disconnect()}),this.bindEvent=function(e,n,r){n=c.mergeArrays(a,n);for(var o=c.toElementsArray(this),i=0;i<o.length;i++)t.addEvent(o[i],e,n,r);},this.unbindEvent=function(){var e=c.toElementsArray(this);t.removeEvent(function(t){for(var r=0;r<e.length;r++)if(this===n||t.target===e[r])return!0;return!1})},this.unbindEventWithSelectorOrCallback=function(e){var r,o=c.toElementsArray(this),i=e;r="function"==typeof e?function(e){for(var t=0;t<o.length;t++)if((this===n||e.target===o[t])&&e.callback===i)return!0;return!1}:function(t){for(var r=0;r<o.length;r++)if((this===n||t.target===o[r])&&t.selector===e)return!0;return!1},t.removeEvent(r)},this.unbindEventWithSelectorAndCallback=function(e,r){var o=c.toElementsArray(this);t.removeEvent(function(t){for(var i=0;i<o.length;i++)if((this===n||t.target===o[i])&&t.selector===e&&t.callback===r)return!0;return!1})},this},s=function e(){function e(e){var t={attributes:!1,childList:!0,subtree:!0};return e.fireOnAttributesModification&&(t.attributes=!0),t}function t(e,t){e.forEach(function(e){var n=e.addedNodes,o=e.target,i=[];null!==n&&n.length>0?c.checkChildNodesRecursively(n,t,r,i):"attributes"===e.type&&r(o,t,i)&&i.push({callback:t.callback,elem:node}),c.callCallbacks(i)})}function r(e,t,r){if(c.matchesSelector(e,t.selector)&&(e._id===n&&(e._id=i++),-1==t.firedElems.indexOf(e._id))){if(t.options.onceOnly){if(0!==t.firedElems.length)return;t.me.unbindEventWithSelectorAndCallback.call(t.target,t.selector,t.callback)}t.firedElems.push(e._id),r.push({callback:t.callback,elem:e})}}var o={fireOnAttributesModification:!1,onceOnly:!1,existing:!1};d=new a(e,t);var l=d.bindEvent;return d.bindEvent=function(e,t,n){"undefined"==typeof n?(n=t,t=o):t=c.mergeArrays(o,t);var r=c.toElementsArray(this);if(t.existing){for(var i=[],a=0;a<r.length;a++)for(var s=r[a].querySelectorAll(e),u=0;u<s.length;u++)i.push({callback:n,elem:s[u]});if(t.onceOnly&&i.length)return n.call(i[0].elem);setTimeout(c.callCallbacks,1,i)}l.call(this,e,t,n)},d},u=function e(){function t(e){var t={childList:!0,subtree:!0};return t}function n(e,t){e.forEach(function(e){var n=e.removedNodes,o=(e.target,[]);null!==n&&n.length>0&&c.checkChildNodesRecursively(n,t,r,o),c.callCallbacks(o)})}function r(e,t){return c.matchesSelector(e,t.selector)}var o={};f=new a(t,n);var e=f.bindEvent;return f.bindEvent=function(t,n,r){"undefined"==typeof r?(r=n,n=o):n=c.mergeArrays(o,n),e.call(this,t,n,r)},f},d=new s(),f=new u();t&&o(t.fn),o(HTMLElement.prototype),o(NodeList.prototype),o(HTMLCollection.prototype),o(HTMLDocument.prototype),o(Window.prototype);var h={};return r(d,h,"unbindAllArrive"),r(f,h,"unbindAllLeave"),h}}(window,"undefined"==typeof jQuery?null:jQuery,void 0);document.addEventListener("DOMContentLoaded",n,!1)
```
You can try this rule in user filter, maybe it will help:
`||de-ipd.videoplaza.tv/proxy/distributor/$domain=tvnow.de,important`

**Comment by razzor1984** [comment]
When i am watching - https://www.tvnow.de/vox/auto-mobil/fahrbericht-bmw-x2/player
i see the HRS ads every singel time, like thats the only one which slipes through

**Comment by razzor1984** [comment]
Still getting the HRS ad spot but not every time now its every 3 or fourth attempted

**Comment by razzor1984** [comment]
Here is the ad which is every time loaded 
https://d3e06l1i5qp46d.cloudfront.net/creatives/assets/421dbac1-14c4-4267-8c6d-4a3b400f61e0/a0249e7f-9fda-4006-b91e-fb7fff3a65ab.mp4

**Comment by BlazDT** [comment]
Please try this rule:

||d3e06l1i5qp46d.cloudfront.net^$media,domain=tvnow.de

**Comment by BlazDT** [comment]
@razzor1984 
Did you try the rules yet?
