### ISSUE TITLE
xhamster18.desi

### ISSUE THREAD

**Issue by FaceBookAI** [AdguardTeam/AdguardFilters#119975]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

Version 4.0.64

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://xhamster18.desi/videos/cindy-loarn-moans-through-her-sex-massage-in-public-8058011

### What filters do you have enabled?

AdGuard Mobile Ads filter, AdGuard Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

[screenshot](https://i.imgur.com/XU40dkF.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by FaceBookAI** [comment]
Can't you add this to indian list?

**Comment by BlazDT** [comment]
Did you try that rule? I could only reproduce ads one time on main site xhamster.com

**Comment by FacebookAI** [comment]
Not yet will do at home.

**Comment by BlazDT** [comment]
Reproduced once, modified existing rules.
