### ISSUE TITLE
10 Dead domains (!)

### ISSUE THREAD

**Issue by mrrtarlan** [AdguardTeam/AdguardFilters#119916]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

favorifilm.com
filmihdizlet.com
fullizlefilmizle.com
hdcehennem.com
cilekfilm.com
filmkusu.org
kalitelifilmizle.net
ifilmizle.org
dafflix.com
hdfilmcehenemi.net
erotikfilms.net
filmsokagi.org
full1080pfilmizle.com

### Proposed solution

Remove all rules related to domains

**Comment by dcxstq2** [comment]
`dafflix.net`, `filmkusu.org` and `erotikfilms.net` are not dead. `dafflix` just changed the TLD. The other two still active with different domains. Do not remove the rules for these three websites.
