### ISSUE TITLE
ads.bullionyield.com

### ISSUE THREAD

**Issue by FacebookAI** [AdguardTeam/AdguardFilters#119972]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

Version 4.0.64

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://ads.bullionyield.com/click?id=d3ad6284-13d0-4a36-97a5-9083ec215bc7

### What filters do you have enabled?

AdGuard Mobile Ads filter, AdGuard Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

[screenshot](https://i.imgur.com/ZU4Tt1F.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by Yuki2718** [comment]
Please don't spare yout time on each report, add description and classify correctly.

**Comment by FaceBookAI** [comment]
Does ads a subcategory of annoyance?

**Comment by Yuki2718** [comment]
Ads has a dedicated category of Ads. I meant 
1. Screenshot(s) doesn't tell everything, is this issue incorrect blocking or what?
2. Report only NSFW contents (particularly adult sites and if screenshots include NSFW material) as NSFW.
