### ISSUE TITLE
https://atendimento.digitalclienteltau.com/

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdguardFilters#119994]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0.74

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://atendimento.digitalclienteltau.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Spanish/Portuguese filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track header, Self-destruction of third-party cookies, Disable cache for third-party requests, Block WebRTC, Hide your Referrer from third-parties (specify in comment below, if used custom value), Hide your User-Agent (specify in comment below, if used custom value)

### Add your comment and screenshots

Fake app for Itaú
Fake: https://atendimento.digitalclienteltau.com/
Official website: https://www.itau.com.br/

![Screenshot_20220526-184953_Samsung Internet](https://user-images.githubusercontent.com/16819380/170590217-6285af2d-9d31-499c-b15f-c20f91901d6e.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
> Dangerous site

@Oniqqqq please take a look at this.

**Comment by Oniqqqq** [comment]
Thanks, added to safebrowsing lists.
