### ISSUE TITLE
instagram.com

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardFilters#119930]
@Nzzyme commented on [Thu May 26 2022](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2082)

https://www.instagram.com/p/Cd_cSNJls9g/

Using Edge Browser with AG extension for Edge. No ad/tracking filters applied. Only the "Stealth" mode is applied with the following settings: https://prnt.sc/YZh3D9na8Fym

Still when I reload the page, no videos play on Instagram (logged in). Disabling AG Extension and then reloading the page plays the video. Please fix.
 

---

@Nzzyme commented on [Thu May 26 2022](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2082#issuecomment-1138578729)

I am not sure where should this be posted as it is not related to any filter. Can you please check and move the post to the right section?

**Comment by Alex-302** [comment]
@Nzzyme Is it still actual?

**Comment by Nzzyme** [comment]
Hi @Alex-302 : Yes, 100%. I just checked and still observed the same issue. Did you observe the same issue??

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/172219047-73386b68-d330-4b21-95ec-854103686a74.png)

Reproduced without AdGuard app and extensions, but after logout I can't use FB and Instagram again.
Is the site really broken by AdGuard?

@AdguardTeam/filters-maintainers Please take a look.

**Comment by AdamWr** [comment]
>No ad/tracking filters applied. Only the "Stealth" mode is applied[...]
>Still when I reload the page, no videos play on Instagram (logged in).

What happens if you enable `AdGuard Base filter`?

I can reproduce issue with video if I disable all filter lists and enable Stealth mode, but this issue should be already fixed in Base filter by this rule:
```
@@||scontent*.cdninstagram.com^$stealth
```

**Comment by Nzzyme** [comment]
> > No ad/tracking filters applied. Only the "Stealth" mode is applied[...]
> > Still when I reload the page, no videos play on Instagram (logged in).
> 
> What happens if you enable `AdGuard Base filter`?
> 
> I can reproduce issue with video if I disable all filter lists and enable Stealth mode, but this issue should be already fixed in Base filter by this rule:
> 
> ```
> @@||scontent*.cdninstagram.com^$stealth
> ```

It works with this rule. Can you tell me what does this rule mean? Does it bypass the Stealth mode for that domain?

**Comment by AdamWr** [comment]
Yes, this rule disables Stealth mode for requests from `scontent*.cdninstagram.com`.
