### ISSUE TITLE
Mail.Ru app contains adverts

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardFilters#120046]
@jbionic2016 commented on [Thu May 26 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4176)

Приветствую.

В приложение Mail.ru стала проникать навязчивая реклама банковских карт Тинькофф. Можно её убрать, чтоб не пришлось менять почтовый клиент на новый?

Заранее благодарю.

- **AdGuard version:**
- 3.6.8
 
- **Filtering mode:**
Local VPN

- **Device:**
Lenovo Tab 11
 
- **Operating system and version:**
  Android 11

- **Root access:**
No

Filters enabled:
AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, EasyPrivacy, Online Malicious URL Blocklist

![IMG_20220526_211659](https://user-images.githubusercontent.com/23212486/170551871-00a5562c-1b4b-4f46-9b97-241ce3091903.jpg)

**Comment by Alex-302** [comment]
@jbionic2016 В этом приложении не заблокировать.
Можно использовать яндексное, со сборщиком. В их приложении можно выключить показ рекламы.

**Comment by jbionic2016** [comment]
> Можно использовать яндексное, со сборщиком.

В смысле зарегистрировать другую почту на Яндексе вместо Mail.Ru?

**Comment by Alex-302** [comment]
Не "вместо". У почтовых сервисов есть возможность собирать почту с других сервисов. Мне, например, нравится достаточно продвинутая сортировка яндекс почты, гугловую ей обрабатываю.
Яндексное приложение имеет в настройках пункт для отключения рекламы.
