### ISSUE TITLE
Правило для блокировки считывания размеров экрана(screen resolution,window size, color depth)

### ISSUE THREAD

**Issue by corvo7** [AdguardTeam/AdguardFilters#1204]
Здравствуйте!Возможно ли составить пользовательское правило для блокироания считывания данных или их произвольной подмены?Подобная реализация есть в random-agent-spoofer(https://github.com/dillbyrne/random-agent-spoofer/)

**Comment by Alex-302** [comment]
@ameshkov 
возможно такое реализовать?

**Comment by ameshkov** [comment]
@Alex-302 скорее всего можно, но это потребует времени.
Повесь пока на меня эту задачку. Только пожалуйста не забудь меня в середине недели пнуть, чтобы я посидел с этой задачкой повозился.

**Comment by Alex-302** [comment]
@ameshkov 
напоминаю)

**Comment by corvo7** [comment]
Тут даже не блокировка,а скрипт-иньекция с произвольными значениями свойств экрана.Было бы хорошо.

**Comment by Alex-302** [comment]
@ameshkov напоминаю ещё раз через год)

**Comment by ameshkov** [comment]
Время то как летит.

Можно вот так:
```
#%#Object.defineProperty(window.screen, 'width', { get: function() { return 1024; } });
#%#Object.defineProperty(window.screen, 'height', { get: function() { return 768; } });
```

В целом, может быть полезно вот для этой задачи:
https://github.com/AdguardTeam/AdguardForWindows/issues/114

**Comment by Alex-302** [comment]
@ameshkov может какие-то идеи из расширения из первого сообщения пригодятся? Там вроде постоянно разные разрешения подставляются.

**Comment by ameshkov** [comment]
Да, там раз в 5 минут ротируется, но это несколько опасно, может отображение сайтов ломать.

С другой стороны, там куча полезных вещей для защиты от фингерпринтинга
