### ISSUE TITLE
[Android] приложения Домовой & AppLock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1205]
https://play.google.com/store/apps/details?id=com.otdel.domovoy.aC300
![image](https://cloud.githubusercontent.com/assets/15856304/12032541/022792fa-ae22-11e5-9e10-689c54951d18.png)

https://play.google.com/store/apps/details?id=com.domobile.applockwatcher
![image](https://cloud.githubusercontent.com/assets/15856304/12032547/0ca70f44-ae22-11e5-8a78-bd7f68c3499c.png)

"enabledFilterIds" : [ 2, 3, 4, 5, 10, 1, 11 ],
"environment" : "prod",
"filteringQuality" : "FULL",
HTTP лог здесь: ECD-830-31454

**Comment by Alex-302** [comment]
В логе ничего дельного. Могу удалённо помочь через TeamViewer на компе.

**Comment by evgeniy-ADG** [comment]
Предложить ему? Что писать?

**Comment by Alex-302** [comment]
Да, можно предложить.
Нужно будет установить TeamViewer и Fiddler (https://www.telerik.com/download/fiddler).
Подключившись подскажу как телефон настроить.

**Comment by evgeniy-ADG** [comment]
Предложил, ждём.
