### ISSUE TITLE
Anti-ADB detection found in www.rjno1.com

### ISSUE THREAD

**Issue by AnnAngela** [AdguardTeam/AdguardFilters#120615]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.42.4

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.rjno1.com/

### What filters do you have enabled?

AdGuard Chinese filter

### Add your comment and screenshots

1. In [ChineseFilter/sections/antiadblock.txt#L68](https://github.com/AdguardTeam/AdguardFilters/blob/025a0695589daf77a834a47506303dfb7a6c018f/ChineseFilter/sections/antiadblock.txt#L68), there is a rule setting a constant, but this constant is being used to detect adblocker.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/9762652/171530056-df3a39e4-e4cf-4c0e-81d4-e84cc9381de3.png)

</details>

<details><summary>Screenshot 2:</summary>

![image](https://user-images.githubusercontent.com/9762652/171530123-a5210557-805c-431e-99b9-7b80e57cc414.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
I have removed this rule, filters update should be available in 1-2 hours.
