### ISSUE TITLE
Отслеживающие параметры URL

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardFilters#120892]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

v3.6.7 (41)

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.rbc.ru/technology_and_media/04/06/2022/629b19f99a794774f9190c88?from=from_main_9

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track header

### Add your comment and screenshots

На следующих сайтах
[1](https://www.rbc.ru/technology_and_media/04/06/2022/629b19f99a794774f9190c88?from=from_main_9)
[2](https://www.kommersant.ru/doc/5391741?from=anons)
используются следующие url параметры:
- ?tag=
- ?from=

для seo оптимизации,которые также являются отслеживающими параметрами,которые могут быть использованы для отслеживания активности на данных сайтах из вне!

Цель рапорта: прошу добавить в соответствующую подписку!

<details><summary>Screenshot 1:</summary>

![snapshot_www kommersant ru_1654388970119](https://user-images.githubusercontent.com/34476664/172030644-93cdacdd-dd2c-4055-9dbd-38fca4a67db2.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
`from` точно сомнительно блокировать. Где используется `tag`?
