### ISSUE TITLE
Billetto.* - Blocked page elements (AdGuard Base filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#120943]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.16.4.30 (XUL)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other(specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://billetto.at/
https://billetto.be/
https://billetto.co.uk/
https://billetto.dk/
https://billetto.es/
https://billetto.eu/
https://billetto.fi/
https://billetto.fr/
https://billetto.ie/
https://billetto.it/
https://billetto.nl/
https://billetto.no/
https://billetto.pt/
https://billetto.se/

### What filters do you have enabled?

AdGuard Base filter

### Affected sites:
```
https://billetto.at/
https://billetto.be/
https://billetto.co.uk/
https://billetto.dk/
https://billetto.es/
https://billetto.eu/
https://billetto.fi/
https://billetto.fr/
https://billetto.ie/
https://billetto.it/
https://billetto.nl/
https://billetto.no/
https://billetto.pt/
https://billetto.se/
```

### Issue:
Top banners (which are not ads) are blocked!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **AdGuard Base filter**

### Problem rule:
`##.top-banners`

### Possible fix:
`billetto.*#@#.top-banners`

--

### System info:
* OS/version: Windows 10 Pro (x64)
* Browser/version: Pale Moon v29.4.6 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Thank you, added.
