### ISSUE TITLE
Youtube.com ads are not blocked

### ISSUE THREAD

**Issue by iamiceparticle** [AdguardTeam/AdguardFilters#121014]
### Steps to reproduce

1. Open youtube.com
2. Search for mkbhd channel
3. Go to videos section
4. Play any video
5. for 5 seconds youtube video screen come as black.

### Expected behavior

Youtube video should play. If I disable adguard then ad is displayed for 5 seconds.

### Actual behavior

for 5 seconds youtube video screen come as black.

<details><summary>Screenshot:</summary>

![Screenshot_20220606-062948_Samsung Internet](https://user-images.githubusercontent.com/76210878/172078396-b73c9084-8d6c-4991-aa16-265e87100e07.jpg)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| (e.g. 1.6.10)| latest
| Browser in use:| (Samsung Interner/Yandex Browser)| samsung internet
| Filters enabled in Adguard:| (e.g. English, Annoyances)| default filters
| Device model:| (e.g. Google Pixel)| Galaxy a71
| Operating system and version:| (e.g. Android 7.1.2)| android 12
| Rooted or not? | (Yes/No) | no

**Comment by vozersky** [comment]
@iamiceparticle The thing is, Adguard Content Blocker doesn't support scriptlets, try regular [AdGuard](https://adguard.com/adguard-android/overview.html) instead

**Comment by iamiceparticle** [comment]
@vozersky If adguard content blocker doesn't support script let's then why mkbhd video play fine when I select below additional filters from the filter list?

1. void.gr  
ελληνικά supplement for EasyList
Version 2.0.0.77.

2. Wiltteri  
Finnish supplement list for EasyList
Version 1.0.1.69.

3. ABP Japanese Filters  
日本語
Version 1.0.4.8.
