### ISSUE TITLE
unpkg.com

### ISSUE THREAD

**Issue by tasi788** [AdguardTeam/AdguardFilters#121136]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard for Android, AdGuard for Mac, AdGuard for Windows

### AdGuard version

7.9.1

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://term.ptt.cc/

### What filters do you have enabled?

AdGuard Chinese filter, AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Self-destruction of third-party cookies, Block WebRTC, Block Location API

### Add your comment and screenshots

1. <comment>
> there's many site using `unpkg.com` as js, css CDN.

2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="679" alt="image" src="https://user-images.githubusercontent.com/11913223/172520005-62b20d89-279c-4468-951d-aeb5538d20a4.png">

</details>

<details><summary>Screenshot 2:</summary>

<img width="467" alt="image" src="https://user-images.githubusercontent.com/11913223/172520060-13276931-d5e4-41c2-904c-bfc783dad126.png">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Check the filter update, fixed here https://github.com/easylist/easylistchina/issues/201.

**Comment by tasi788** [comment]
> Check the filter update, fixed here [easylist/easylistchina#201](https://github.com/easylist/easylistchina/issues/201).

but still blocked by `AdGuard DNS filter`, since https://github.com/easylist/easylistchina/issues/201#issuecomment-1149931960 says will be update in 30 minute

**Comment by zloyden** [comment]
> but still blocked by [AdGuard DNS filter](https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt)

I can't confirm it, we also excluded this from our DNS https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/964.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/172801615-25a84b57-8016-4e1b-8821-35c870493d7f.png)

</details><br/>

**Comment by zloyden** [comment]
Ok, glat to hear it.
