### ISSUE TITLE
Booking.com reservation emails

### ISSUE THREAD

**Issue by stdedos** [AdguardTeam/AdguardFilters#121238]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

N/A

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

Booking.com reservation emails

### What filters do you have enabled?

AdGuard URL Tracking filter

### Add your comment and screenshots

"Modify your booking" gives a https://secure.booking.com/myreservations.en-gb.html?aid=000000;bn=0000000000;pincode=0000&;source=conf_email;pbsource=conf_email_modify;pbtrack=email_mainCTA like URL.

"As evident", booking.com uses a lot of `;` as parameter-separators (which I guess that we can do nothing about?)
e.g. "Get the print version" ends up in a https://secure.booking.com/myreservations.en-gb.html?auth_success=1;pbtrack=email_print_btn;pincode=0000;=;bn=0000000000;aid=000000;label=conf_email_print;pbsource=conf_email_modify;source=conf_email URL, which is "maybe non-parseable" by standard semantics

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/URL_API#queries
`;` is not supported

**Comment by stdedos** [comment]
Removing `;source` (as key altogether) still merits handling
