### ISSUE TITLE
ameritrade.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#12137]
***Description***:
* **Current behaviour**: 

Site's interactive elements are blocked. The site freezes midway through loading and becomes absolutely unresponsive.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33634917/36602780-8bff1c08-18c1-11e8-8a85-3feda43e8f1a.png)
</details><br/>

* **Expected behaviour**: 

Site should work without issues.

***Steps to reproduce the problem***:

1. Go to ameritrade.com and log in to your account
2. Enjoy the dead site

***System configuration***

**Filters:**
English, Dutch, Filter unblocking useful ads, Wiltteri

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 Fall Creators Update Build 16299
Browser:                               | Microsoft Edge
AdGuard version:                       | 6.2.437.2171
Filters enabled:                       | English, Dutch, Filter unblocking useful ads, Wiltteri
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Block 3rd-party cookies (30), Disable 3rd-party cache, Block WebRTC, Block Location API, Remove X-Client-Data Header, Hide Search Queries, Send DNT Header
Helpdesk ID (if exists):               | 1766491

**Comment by akmLaVx** [comment]
Multiple other reports also exist: 1102602, 1689302, 1730012

**Comment by BlazDT** [comment]
Can't register there. Also getting redirected to tdameritrade.com

@AdamWr please check.

**Comment by AdamWr** [comment]
I can't register too, so we probably need an account to fix it.

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/HttpsExclusions/issues/63

**Comment by BlazDT** [comment]
@evgeniy-ADG 
Any news about an account?

**Comment by ameshkov** [comment]
Please reopen if there are news about it

**Comment by bug-killer** [comment]
Adguard is now (w/ new version) having major compatibility problems with TD Ameritrade. I also have problems w/ M&T bank website.  Seems the new Adguard version needs work for financial sites.
For TD Ameritrade, I can log onto my account, but clicking on any link or pull down menu item results in the page I'm trying to go to continuously trying to load, with the bottom right of page displaying:  "waiting for local.adguard.com".
I am very frustrated!
David

**Comment by Alex-302** [comment]
@bug-killer please try to disable all filters, extension and stealth mode and check again.

**Comment by Alex-302** [comment]
If it is possible, I can check via TeamViewer.
