### ISSUE TITLE
Filter issue causing problem with and android app

### ISSUE THREAD

**Issue by RVC2020** [AdguardTeam/AdguardFilters#121419]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

dns.adguard.com

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.kaufland.Kaufland&hl=ro&gl=US

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. <comment>
Hello, on my android device I'm using dns.adguard.com as my private DNS, The issue is with a retailer app (kaufland app -package:com.kaufland.Kaufland). Since an update about 3 weeks ago, whenever I try to access the leaflet (the supermarket catalogue) from within the app get a network error. If I revert the phone to my ISP DNS, the app works normal, so I guess it is a bad AdGuard filter. Can you please fix it? Thanks.

https://user-images.githubusercontent.com/75840436/173083326-98640e6a-7519-44c1-bcf6-44c65e5ccd71.mp4

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Fixed for Android app (without DNS protection enabled).
 DNS will take a while.

**Comment by RVC2020** [comment]
@BlazDT @Alex-302, although this is marked as closed, the issue has not been for DNS protection alone. Could you guys please look into it. Thank you.

**Comment by BlazDT** [comment]
Still working fine here.
@AdamWr please check.

**Comment by AdamWr** [comment]
>@AdamWr please check.

Unfortunately, I cannot reproduce it.
Promo offers load correctly on my end (I have checked it with DNS set to AdGuard DNS).

**Comment by xRuffKez** [comment]
I have this domain blocked and neuer had issue with any functions in the Kaufland App.

**Comment by Alex-302** [comment]
@xRuffKez Which domain?

**Comment by xRuffKez** [comment]
@Alex-302 

'''
@@||eum-blue-saas.instana.io^
'''
from List https://raw.githubusercontent.com/kitadai31/AdGuardSDNSFilter_withoutPrivacyFilters/master/Filters/filter.txt

It is allowed because the App was reported here having issues. But i never had issues blocking above mentioned domain in the app nor elsewhere.

**Comment by Alex-302** [comment]
@BlazDT Please test if it works fine when
- eum-blue-saas.instana.io is blocked by regular rules (DNS protection OFF)
- eum-blue-saas.instana.io is blocked by DNS protection (Ad Blocking module is OFF)

**Comment by BlazDT** [comment]
That domain is not requested on my Android.

**Comment by Alex-302** [comment]
Removed from AdguardFilters and from DNS filter.
