### ISSUE TITLE
olx.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [AdguardTeam/AdguardFilters#12143]
![2018-02-23-ogloszenia - sprzedam kupie na olx pl](https://user-images.githubusercontent.com/5884000/36611319-55980564-18d3-11e8-94ee-b9d5b9152893.png)
`https://www.olx.pl/`

click not work

Adguard’s Annoyance List
uBlock filters – Privacy

https://github.com/uBlockOrigin/uAssets/issues/1610

my set
https://gist.github.com/KonoromiHimaries/6d45189eafa4935cb0ed81050db154fc

uBlock Origin 1.15.2
Chrome 64.0.3282.186

**Comment by BlazDT** [comment]
Not reproduced on AdGuard with our Annoyance filter list.

@AdamWr please check.

**Comment by AdamWr** [comment]
It will be fixed in Polish filter list.
