### ISSUE TITLE
Unchecking "Enabled on this site" does not disable the annoyances filters for the site

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardFilters#121425]
@piejanssens commented on [Tue Jun 07 2022](https://github.com/AdguardTeam/AdGuardForSafari/issues/718)

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.11.4
* Environment name and version: Safari 15.5 (17613.2.7.1.8)
* Operating System: macOS 12.4.0
* Filters you use in AdGuard: ads, privacy, annoyances (EasyList Cookie List, I don't care about cookies, AdBlock warning removal list), language-specific (NL)

### Expected Behavior

If I uncheck "Enabled on this site", I expect any AdGuard to no longer affect the site in any way.

### Actual Behavior

Some filters are still being applied. I am certain that this is a bug in AdGuard as I can get the wanted effect by disabling the AdGuard all-together via the "Pause AdGuard for Safari" option.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

---

@Birbber commented on [Wed Jun 08 2022](https://github.com/AdguardTeam/AdGuardForSafari/issues/718#issuecomment-1150112013)

@piejanssens Hi! Could you give an example of the webpage so I could check it on my end?

---

@piejanssens commented on [Wed Jun 08 2022](https://github.com/AdguardTeam/AdGuardForSafari/issues/718#issuecomment-1150120107)

Hi @Birbber,

1. Enable the "I don't care about cookies" annoyance filter.
2. Visit https://www.era.be/nl/te-koop
3. Notice you can't scroll
4. Disable AdGuard on the site
5. Notice you still can't scroll...
7. "Pause AdGuard for Safari"
8. Accept the cookies
9. Notice you can scroll

**Comment by piejanssens** [comment]
@Birbber @Alex-302 
I don't think a site specific whitelist or fix is the correct patch for this. The era.be site was just an example. The issue is in general. 

Btw. same issue on iOS, website whitelisted, yet filters are still being applied:

![image](https://user-images.githubusercontent.com/829098/173770910-5ab98f23-17a1-4afe-89b9-5277a1751339.png)

**Comment by Alex-302** [comment]
@piejanssens Could you please list these sites[next time]? Some generic rules may hide popups, but sometimes scrolling is locked.

**Comment by piejanssens** [comment]
@Alex-302 Isn't my assumption correct to think that if I uncheck "Enable on this site", AdGuard would not be influencing the browsing experience in ANY way and it would behave on that site as if the AdBlock extension is disabled overall?

**Comment by piejanssens** [comment]
Another example: https://www.etsy.com/nl/market/dyson_attachments
Again, it's a cookie annoyance blocker that is breaking the page navigation (scrolling). Whitelisting the site does not sold-be it, disabling AdGuard altogether solves it. 

I have this issue both on desktop (macOS / Safari) as on mobile (iOS / Safari").

**Comment by Alex-302** [comment]
> breaking the page navigation (scrolling

Not reproduced. Please make a screenshot of content blockers in iOS settings.

**Comment by piejanssens** [comment]
![47D05568-42DF-4EE8-B3ED-4C369311E56F](https://user-images.githubusercontent.com/829098/182247851-3b2090fa-50fc-44c1-bc95-df7dee1768e9.png)

**Comment by Alex-302** [comment]
Ok, better write here https://github.com/AdguardTeam/AdguardForiOS/issues
