### ISSUE TITLE
sberbank.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#121576]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.0.181

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://unsub.info.sberbank.ru/backend/member/unsub/код_пользователя_или_отписки

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

 Сбербанк шлёт свой рекламный спам на почту. При переходе по ссылке "Отписаться" открывается пустое окно. При выключении AdGuard'a страница открывается и отписка становится возможной.

 Всему виной правило `||sendsay.ru^$third-party` из Фильтра Раздражителей.

<details><summary>Screenshot'ы:</summary>

![2022 06 12-2](https://user-images.githubusercontent.com/17948007/173208908-4d794f07-df15-4089-bcca-5b04d7b169b9.png)
----------
----------
![2022 06 12-1](https://user-images.githubusercontent.com/17948007/173208914-97cfc547-7100-4b40-8160-3e5883efce1b.png)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Там снизу два скрипта. Попробуй из разблокировать по одному с проверкой. Мне не на чем проверить.

**Comment by XX-J** [comment]
<details><summary>Там ВСЕ ресурсы грузятся из `sendsay.ru`, поэтому итоговая страница пуста:</summary>

![2022 06 14-1](https://user-images.githubusercontent.com/17948007/173539956-39a03e5a-8712-4336-a1dc-266f70d7a4fb.png)
</details>

<details><summary>При отключенном AdGuard'e всё норм:</summary>

![2022 06 12-1](https://user-images.githubusercontent.com/17948007/173208914-97cfc547-7100-4b40-8160-3e5883efce1b.png)
</details>

**Comment by Alex-302** [comment]
Поправил.
