### ISSUE TITLE
FBLight tracking

### ISSUE THREAD

**Issue by stdedos** [AdguardTeam/AdguardFilters#121554]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

N/A

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

FB Light?

### What filters do you have enabled?

AdGuard URL Tracking filter

### Add your comment and screenshots

https://www.facebook.com/groups/5555248820/permalink/10159138985843821/?app=fbl

It's "obvious enough" it's tracking produced from the app that created the share link

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Values are useless for identification or marketing.
