### ISSUE TITLE
https://waterford-news.ie/

### ISSUE THREAD

**Issue by germaloney11** [AdguardTeam/AdguardFilters#121562]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

Private dns

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://waterford-news.ie/

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

1. A blank white screen appears when opening links for the above website. Sometimes it stays on the screen for a few seconds and disappears and other times it just covers the page entirely.

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>
![Screenshot_20220611-203812_Kiwi Browser](https://user-images.githubusercontent.com/17252998/173202450-b90498fe-0492-4ca6-97e5-befce766c0a2.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reproduced.
