### ISSUE TITLE
Failed to load images. (AdBlock Exception)

### ISSUE THREAD

**Issue by hpeop** [AdguardTeam/AdguardFilters#121644]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.0.181

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.inven.co.kr/board/webzine/2097

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. <comment>
Failed to load images. (AdBlock Exception)
2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Pictures shown fine, please provide screenshots.

**Comment by hpeop** [comment]
> Pictures shown fine, please provide screenshots.

![K-077](https://user-images.githubusercontent.com/107382857/173697881-9113f775-7341-4a8c-a840-3df1bc84d4d8.jpg)
![K-078](https://user-images.githubusercontent.com/107382857/173697883-518323e1-6d4b-4205-bb26-ea723debe946.jpg)

**Comment by JobcenterTycoon** [comment]
Force update the filter lists
