### ISSUE TITLE
Blocking ads in the Waze app

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#121846]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

While running a custom DNS server I was able to block all ads in the waze app by blocking any connections from advil.waze.com

^ This should help you block all ads from the app.

I'm currently using your iOS DNS profile & your private DNS servers on Android, would really appreciate it if you could add this to your blocklist.

### Proposed solution

Add advil.waze.com to the SDNS filter

### Additional information

CRM ID: 611235

**Comment by BlazDT** [comment]
In the past that domain seemed to break the app.

https://github.com/StevenBlack/hosts/issues/760

So user has currently no problems at all when it is blocked?

**Comment by Eugene-Savenko** [comment]
It seems that it works fine for them now and others users from [XDA](https://forum.xda-developers.com/t/app-waze-without-ads-or-poi-balloons-or-popup-ads.3575205/) as well

**Comment by BlazDT** [comment]
Added to specific_app.
@Alex-302 is specific_app automatically migrated to DNS filter or do I have to move to adservers?

**Comment by zloyden** [comment]
@BlazDT according to the [configuration file](https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/configuration.json), you should move it to the adservers.

**Comment by zloyden** [comment]
Nvm, I've done it.

**Comment by BlazDT** [comment]
Thank you, that's why I could not find the rule just now.

**Comment by git-anish** [comment]
you guys are legends, amazed at how quickly this was assessed and merged!

I reported this adserver by the way and [I can confirm](https://i.imgur.com/eiDBPlv.jpg) the popup ads on both iOS and Android are being blocked by your DNS servers.

Just bought a monthly sub, thank you!!!
