### ISSUE TITLE
hentaiz.cc

### ISSUE THREAD

**Issue by MeowIce** [AdguardTeam/AdguardFilters#122071]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

AdGuard DNS

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://hentaiz.cc/

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

Screenshots
<details><summary>Screenshot 1:</summary>
https://imgur.com/a/9DyOOv5

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
@Chinaski1 please add site to Family DNS, thank you.

**Comment by Eugene-Savenko** [comment]
`{"blocked": true, "reason":"CATEGORY_BLACKLISTED", "clientTtl":86400000}`
