### ISSUE TITLE
amazon.*

### ISSUE THREAD

**Issue by DesertBear** [AdguardTeam/AdguardFilters#122233]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin (1.42.4); AdGuard Annoyances filter (2.1.23.38)

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.amazon.co.uk/ | https://www.amazon.it/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

Cookie banners have started appearing on Amazon websites, for example on Amazon UK and Amazon Italia websites.

The cookie banners are blocked on the EasyList Cookie list and the Fanboy’s Annoyance list, however they are not blocked on the AdGuard Annoyances list yet.

The below rule appears to block the banners, however this was created just using the uBlock Origin element picker, therefore there may be a better rule to use than this.

```
amazon.*###a-page > .a-declarative
```

Screenshots
<details><summary>Screenshot 1: Amazon.co.uk</summary>

![Screenshot A](https://user-images.githubusercontent.com/27423064/174460570-eadc9c38-86ae-4ac4-9121-968e95df8d80.png)

</details>

<details><summary>Screenshot 2: Amazon.it</summary>

![Screenshot B](https://user-images.githubusercontent.com/27423064/174460572-658addfb-8e03-4f10-9a45-a33187a7ee91.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Hidden by this rule when I check (child element of the mentioned one):
`amazon.nl,amazon.pl,amazon.com.tr,amazon.ca,amazon.co.uk,amazon.de,amazon.es,amazon.fr,amazon.in,amazon.it###sp-cc[action^="/cookieprefs"]`

**Comment by BlazDT** [comment]
@Sergey-Lyapin fixed it.

**Comment by DesertBear** [comment]
It doesn't appear to happen every time when visiting Amazon – it seems sporadic.  Maybe Amazon are A/B testing at the moment.  Perhaps try going to Amazon indirectly via a link from search engine results instead, as it seems more reproducible that way.  I.E.  from:

https://www.startpage.com/sp/search?query=amazon+charger&cat=web&pl=opensearch&language=english


The below rule does appear to prevent the cookie box from appearing so far.

```
amazon.*###sp-cc[action^="/privacyprefs"]
```

It also appears AdGuard Annoyances filter 2.1.23.39 works too, as I was unable to get the cookie dialogue to reappear after refreshing the filter list to that version.

Thanks.
