### ISSUE TITLE
steamgriddb.com

### ISSUE THREAD

**Issue by Visne** [AdguardTeam/AdguardFilters#122234]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.steamgriddb.com/boop

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1. Overzealous filter blocks all notifications, instead of just the Patreon notification I imagine it was intended to block.

<details><summary>Screenshot:</summary>

Both of these notifications get blocked by the `steamgriddb.com##.noty_layout` filter.

![image](https://user-images.githubusercontent.com/39844191/174462274-debb78ed-fbdf-4fb5-8fa7-b65aed692cf3.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Exchanged the rule, but
>  Patreon notification

It's a popup that also blocked.
