### ISSUE TITLE
userscirpt: @match works excessively

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdguardFilters#122337]
@kairi003 commented on [Wed Jun 01 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4181)

### Issue Details

Without wildcards, `@match` as userscript attributes should match the specified pathname exactly, but it will be a forward match.

- **AdGuard version:**
  - v3.6.8 (46)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Galaxy s8 (SCV36)
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No

### Expected Behavior

The following userscript changes the background color of `https://kb.adguard.com/en` only.
In fact, it works that way in Tampermonkey.

```js
// ==UserScript==
// @name         test
// @match        https://kb.adguard.com/en
// ==/UserScript==

document.body.style='background-color:lightcyan';
```

### Actual Behavior

It would also apply to paths that forward match the URL, e.g., `https://kb.adguard.com/en/general/adguard-ad-filters`.
This is the expected behavior for `https://kb.adguard.com/en*`.

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_20220601-163607_Chrome](https://user-images.githubusercontent.com/24368162/171352380-1fa88386-42f2-4de2-bee4-1c7d3476669a.jpg)

</details>

**Comment by zloyden** [comment]
Not related to the filters.

**Comment by zloyden** [comment]
@kairi003 it will be handled here https://github.com/AdguardTeam/CoreLibs/issues/1650.
