### ISSUE TITLE
Random popups appear on `https://hh3dhay.xyz/`

### ISSUE THREAD

**Issue by vhpcdpgl** [AdguardTeam/AdguardFilters#122333]
### Issue URL
Random popups appear on `https://hh3dhay.xyz/`

### Actual behavior
<details><summary>Screenshot 1:</summary>

![ảnh](https://user-images.githubusercontent.com/59459998/174519354-dad643a3-03fa-466a-be6c-c86e259568fb.png)

</details>

**Some random popup domains appear:**
`iwcrrgjmdfnec.com ; iwcrrgjmdfnec.com ;  iqrylajbjcc.com ; yonrvoakmg.com ; xgmkhegdlvrlggu.com ; yonxatuor.com ; helormesqtaqbbx.com ; xxjyysbw.com ; beyadqoycwpkkw.com ; baeigcbsttrf.com ; dlviqmfb.com ; ckhvmkurkifon.com ; xrvatxqe.com ; yonxatuor.com ; lgmfasyrgbsvji.com ; qokvplfqwsdm.com ; juaapcwt.com ; rtysurlsmhhhti.com ; knyyiocvvt.com ; pseekree.com ; tiwhaiph.net ; flwqusootbcq.com ; nafvdkhyhbiw.com ; wmljmscoru.com ; gxrnvnwhawdpuhx.com ; xwmawujupkgsej.com ; hdrtwqddidvk.com ; kfffknqikfjkq.com`

 **The popup domains come from these IPs**
`139.45.197.151 / 139.45.197.152 / 139.45.197.153 / 139.45.197.154`

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Addon in use:| uBlock Origin
| Filters in use:| Adguard Base/EasyList/ABPVN List
| Operating system and version:| Windows 10/Firefox 91.10.0esr (64-bit)

**Comment by vhpcdpgl** [comment]
@maximtop The problem is still not resolved. Please consider it.
Thanks!

**Comment by maximtop** [comment]
@vhpcdpgl sorry I didn't mean to close it

**Comment by AdamWr** [comment]
I have added rules which should fix these popups.
Filters update will be available in 1-2 hours.
