### ISSUE TITLE
dialogdv.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#12234]
[https://dialogdv.ru/category/neubivaemye-telefony/?sort=price&order=asc](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdialogdv.ru%2Fcategory%2Fneubivaemye-telefony%2F%3Fsort%3Dprice%26order%3Dasc)

 1. Баннер-крутилка, мельтешащяя перед глазами - самореклама: `dialogdv.ru##.bxsliderleft_bl`

 2. Раздражающий сторонний виджет, от компании Callibri : `||callibri.ru^$third-party`

<details><summary>Screenshot:</summary>

![dialogdv ru](https://user-images.githubusercontent.com/17948007/36640396-b3fc6f9e-1a2e-11e8-88e7-aca40b6f0fa9.png)
</details>

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.8.5 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Баннер можно оставить.
Виджет заблокировал.
