### ISSUE TITLE
userupload.net [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#12246]
**Site**: https://userupload.net/b8b0bellvzko

**Issue**: Please remove the adblock message as seen in the screenshot.

**Screenshot**: http://prntscr.com/ijhtb3

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
Same with this one as well. Still seeing the adblock message.

**Comment by BlazDT** [comment]
Is this Kaspersky issue again?

**Comment by Nzzyme** [comment]
https://userupload.net/r2qplr3sonin

Probably incorrect blocking on the page. Unable to click on the captcha and solve it. Please check
