### ISSUE TITLE
tnpdf.com [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#12247]
**Site**: https://tnpdf.com/4ugzlqauv10m

**Issue**: Please remove the adblock message as seen in the screenshot.

**Screenshot**: http://prntscr.com/ijhux2

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
I am still seeing the adblock message after clearing the browser cache. Can you please check. Thank you

**Comment by BlazDT** [comment]
Kaspersky issue again?

**Comment by Nzzyme** [comment]
Yes, indeed Kaspersky issue.
