### ISSUE TITLE
incorrect blocking of graphql.anilist.co

### ISSUE THREAD

**Issue by Aderox** [AdguardTeam/AdguardFilters#122400]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

2.0.33.64

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome, Opera

### Which device do you use?

Desktop

### Where is the problem encountered?

graphql.anilist.co

### What filters do you have enabled?

AdGuard French filter

### Add your comment and screenshots

1. Without FRA AdGuard Français enabled the http request work (screen 1)
2. With FRA AdGuard Français enabled (that's the only change, screen 2)

Screen 1: 
![image](https://user-images.githubusercontent.com/57142734/174690813-9ff4c992-94c3-4ba2-933e-67cec31f019a.png)

Screen 2:
![image](https://user-images.githubusercontent.com/57142734/174690832-2f1d2744-761e-46be-b965-9c3443dee6ce.png)

The only change: 
![image](https://user-images.githubusercontent.com/57142734/174690845-ab1cbe55-2ed5-415e-8f58-08d405da30de.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
What exactly is wrong? Every blocked request is visible in console with the same error code.

**Comment by Alex-302** [comment]
Please use this form to report an issue in case of using UBO https://reports.adguard.com/new_issue.html
