### ISSUE TITLE
linksocean.net [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#12249]
**Site**: https://linksocean.net/l78Vs

**Issue**: Please remove the adblock message as seen in the screenshot.

**Screenshot**: http://prntscr.com/ijhxx3

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Not reproduced. Rule in English filter fixes it for me:

`@@/js/ads.js|$script,~third-party,domain=~internethaber.com`

**Comment by AdamWr** [comment]
I can't reproduce it.

**Comment by Nzzyme** [comment]
Kaspersky issue again
