### ISSUE TITLE
pclives.info [Ad block Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#12240]
**Site**: http://www.pclives.info/2011/07/windows-7-windows-vista-and-windows-xp.html

**Issue**: Ad block message seen on the page and it redirects to 

https://www.adworkmedia.com/help/removeAB.php

**Screenshot**: http://prntscr.com/ijh3wf

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
No visitors.
