### ISSUE TITLE
uplod.cc [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#12243]
**Site**: https://uplod.cc/st9yf1m70avk

**Issue**: Please remove the ad block message on the page.

**Screenshot**: http://prntscr.com/ijhkmz

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Not reproduced. English filter contains the rule already when I check:

`@@||uplod.cc/hg/js/advertisement.js`

@AdamWr please check.

**Comment by AdamWr** [comment]
I can't reproduce it.

**Comment by Nzzyme** [comment]
But I can reproduce it. Maybe only shows to certain countries. Can you please try with a proxy? Thanks

**Comment by AdamWr** [comment]
I can reproduce it only if I block this script - `https://uplod.cc/hg/js/advertisement.js`
Do you see this request in AdGuard filtering log?
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/36969755-b5e7ac40-2066-11e8-83a3-fded993cde4f.png)

</details>

**Comment by Nzzyme** [comment]
Yes, I see that.
