### ISSUE TITLE
Avito app broken. Не все изображения отображаются

### ISSUE THREAD

**Issue by Gisborn** [AdguardTeam/AdguardFilters#122409]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

v3.6.8 (46-1.9.62cl)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://app.adjust.com/96cf8hy?deep_link=ru.avito://1/main

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter

### Add your comment and screenshots

1. <Comment> В приложении Авито не все фотографии отображаются в объявлениях
При постановке защиты adguard на паузу - все фотографии отображаются

Имя пакета: com.avito.android
Uid: 10284
Тип: User
Версия: 129.0 (1789)
Целевой SDK: 30
Время установки: 30.03.2021 22:33
Время последнего обновления: 10.06.2022 23:41

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot_2022-06-21-08-11-10-505_com avito android](https://user-images.githubusercontent.com/17904326/174720914-fd1cf454-8be5-4354-9c6b-410c8e228a8e.jpg)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Не повторяется. Проверьте приложение авито следующим образом - выключите все фильтры и оставьте защиту включенной.

**Comment by maxikuzmin** [comment]
@Gisborn enabling DNS filtering or IPv6 traffic bypass fixes the issue. Please let me know the result

**Comment by Gisborn** [comment]
Thank you, now, it works fine
DNS filtering enabling does not matter
I could not find "IPv6 traffic bypass" in AdGuard settings

maybe Avito app was updated and their bug fixed

**Comment by Akashb299** [comment]
Как Разблокировать профиль на АВИТО!?
Авито заблокировали Ваш профиль, досудебная претензия решит Ваш вопрос!
С проблемой блокировки профиля на Авито сталкиваются как новички, так и опытные продавцы. Если Ваш профиль заблокирован, не спешите паниковать. 
Идём законным путём! Что делать, если заблокировали профиль на Авито? Как разблокировать аккаунт и вернуть доступ к вашим объявлениям? Подробнее тут: https://t.me/AvitoUnblock_bot
