### ISSUE TITLE
letshostit.org [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#12257]
**Site**: https://www.letshostit.org/wp-content/uploads/2016/12/uzym5fdkkytt

**Issue**: Please remove the adblock message on the page.

**Screenshot**: http://prntscr.com/ijj9ha

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Looks like fake site, download button reverts back to the same site even without any adblockers. Also not reproduced.

@AdamWr please check.

**Comment by AdamWr** [comment]
I can't reproduce adblock message.

> Looks like fake site

Yes, it looks suspicious.
