### ISSUE TITLE
cutwin.us [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#12258]
**Site**: http://cutwin.us/EoxXZEK

**Issue**: Please remove the adblock message on the page.

**Screenshot**: http://prntscr.com/ijja9o

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 64.0.3282.119 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.4 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Not reproduced, added rule for popup. Mexican site, so Spanish filter should be active.

@AdamWr please check.

**Comment by AdamWr** [comment]
I can't reproduce it.

**Comment by Nzzyme** [comment]
@BlazDT May I ask how did you conclude that this is a Mexican site as I saw all text on this site in English. I also cleared the browsing cache and still saw this. I think it shows the adblock message to only certain countries. Can you check with a proxy?

**Comment by Nzzyme** [comment]
Kaspersky issue. I no longer see the adblock message.
