### ISSUE TITLE
Tracking subdomain on site: `arttimes.vn`

### ISSUE THREAD

**Issue by vhpcdpgl** [AdguardTeam/AdguardFilters#122689]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

v7

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://arttimes.vn/`

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

<comment>

- Tracking subdomain: **`thongke.arttimes.vn`**

- Script: `https://thongke.arttimes.vn/arttimes-analytics/arttimes-analytics.js?ver=20220306`

- Website: `https://arttimes.vn/`

### Privacy

- [X] I agree to follow this condition

**Comment by vhpcdpgl** [comment]
"thongke" is "thống kê" in Vietnamese, which means "statistic".

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/176377560-32cd57e5-9533-49ea-930f-dcde1224ad2e.png)
