### ISSUE TITLE
rutor.org mirrors - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#1227]
Lots of not-blocked third-party requests there

Mirror example: fast-bit.org

**Comment by Alex-302** [comment]
Added
```
||creofive.com^$third-party
.tpm.pw^$third-party
||ad.dumedia.ru^$third-party
||luxup.ru^$third-party
||trafex.net^$third-party
||rbnt.org^$third-party
||earnshill.com/images/$popup 
```

**Comment by ameshkov** [comment]
The issue is here again:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=46010288

**Comment by Alex-302** [comment]
уже чисто, видать фильтры не обновлялись

**Comment by evgeniy-ADG** [comment]
new-rutorg.org
http://prntscr.com/agpqwe

логи PNU-419-78339

**Comment by Alex-302** [comment]
похоже сдохло зеркало. Перекидывает на заглушку о продаже
http://imagizer.imageshack.com/img924/9932/Z7mbP2.png

**Comment by vgavrish** [comment]
При переходе на раздачу на сайте http://mirror-rutor.org перекидывает на другой сайт
+ заходите на раздачу и увидите что вас перекинут на другой сайт с рекламой

[debug (4).txt](https://github.com/AdguardTeam/AdguardFilters/files/441010/debug.4.txt)
[state (38).txt](https://github.com/AdguardTeam/AdguardFilters/files/441011/state.38.txt)
время проблемы 16:24

**Comment by Alex-302** [comment]
Переход вижу, но не понятно что его вызывает. Попроси записать HAR.

**Comment by vgavrish** [comment]
попросила,жду
