### ISSUE TITLE
Tracking subdomain on site: `www.onlinecasino321.com`

### ISSUE THREAD

**Issue by vhpcdpgl** [AdguardTeam/AdguardFilters#122798]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

v7

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://www.onlinecasino321.com/`

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

<comment>

- Tracking subdomain: **`piwik.onlinecasino321.com`**

- Script: `https://piwik.onlinecasino321.com/matomo.js`

- Website: `https://www.onlinecasino321.com/`

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
I presume that trackers are *far* from the biggest problem on an online casino writingbot site; though I admit that I don't specialise in tracker stuff and that the actual AdGuard team would know more about this kind of stuff.

Have you tried turning on AdGuard Tracking Protection and EasyPrivacy in your AdGuard user settings, to see if that blocks the tracker correctly?

**Comment by vhpcdpgl** [comment]
> I presume that trackers are _far_ from the biggest problem on an online casino writingbot site; though I admit that I don't specialise in tracker stuff and that the actual AdGuard team would know more about this kind of stuff.
> 
> Have you tried turning on AdGuard Tracking Protection and EasyPrivacy in your AdGuard user settings, to see if that blocks the tracker correctly?

Hi @DandelionSprout!
I completely agree with you on this.
However, I would personally suggest blocking its trackers with DNS blocking, that way's useful for devices donot use cosmetic rule addons as Adguard, uBlock Origin...
Although this is a site that deals with gambling, it is really just an intermediary to point to other real gambling sites, so I did not suggest that Adguard block it by assigning it's labeled "gambling", maybe it will be useful for tracking real gambling sites.
