### ISSUE TITLE
metrolyrics.com - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#1228]
These ads are present on both mobile and desktop website versions.

You may need to use US VPN to see them.

Amazon Music on these screenshots is an ad (Mobile version of the website).
![image1](https://cloud.githubusercontent.com/assets/5947035/12059268/13e62d06-af69-11e5-8075-4edb921ac044.png)
![image2](https://cloud.githubusercontent.com/assets/5947035/12059270/1ce43b1e-af69-11e5-8651-1aa98174bf69.png)

**Comment by Alex-302** [comment]
It is blocked on my end
http://imagizer.imageshack.com/img911/3121/aK5BQ6.jpg
i see the banner(but not amazon) on this place without filtering.

**Comment by ameshkov** [comment]
Could you please try US VPN?

**Comment by Alex-302** [comment]
@ameshkov 
I tried with US VPN again, and no Amazon banner
![screenshot_2016-01-06-13-58-49](https://cloud.githubusercontent.com/assets/8361299/12141152/330047f2-b47e-11e5-8a55-2900110e8e61.png)
"Play the" - is the ad, and it is blocked

**Comment by ameshkov** [comment]
So we may need the page source code, right?

**Comment by Alex-302** [comment]
Yes
