### ISSUE TITLE
Tracking on mytv.com.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [AdguardTeam/AdguardFilters#122941]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

v7

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

`https://mytv.com.vn/ `

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

<comment>

Tracking script: `https://ipcc-vnp1.vnptmedia.vn/upload/crm/site_button/loader_25_c4f5ee.js?27606715`

Website: `https://mytv.com.vn/ `

### Privacy

- [X] I agree to follow this condition

**Comment by trmdi** [comment]
@zloyden Your commit blocks the chat feature in the My VNPT app.

**Comment by zloyden** [comment]
@trmdi could you provide the name of the app? It's strange that the chat requires the tracker to be allowed to work.

**Comment by trmdi** [comment]
@zloyden https://play.google.com/store/apps/details?id=com.vnp.myvinaphone

But it requires you to have a VN phone number to login.

**Comment by zloyden** [comment]
Try this rule `@@||ipcc-vnp1.vnptmedia.vn^$app=com.vnp.myvinaphone` in the User rules.

**Comment by trmdi** [comment]
> Try this rule `@@||ipcc-vnp1.vnptmedia.vn^$app=com.vnp.myvinaphone` in the User rules.

I know. But that should be removed for DNS users. (adguard-dns.io)

**Comment by zloyden** [comment]
Did it help without DNS?
We don't remove trackers / adservers from AdGuard DNS and you didn't explain the second part of [this](https://github.com/AdguardTeam/AdguardFilters/issues/122941#issuecomment-1365939350).

**Comment by trmdi** [comment]
![Screenshot_2022-12-28-13-49-34-307_com sec android app sbrowser](https://user-images.githubusercontent.com/11857205/209770810-5dd63a5a-fb9a-4391-9d23-92b500fc58d2.jpg)

**Comment by zloyden** [comment]
Looks like not only analytics load from this domain, I removed the rule.
