### ISSUE TITLE
Outlook safelinks can not be resolved. 

### ISSUE THREAD

**Issue by deltaxsingh** [AdguardTeam/AdguardFilters#123096]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

DNS

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://nam12.safelinks.protection.outlook.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

The website does not resolve. 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please show `nslookup nam12.safelinks.protection.outlook.com` output with AdGuard and with another DNS.
