### ISSUE TITLE
com.nest.android compatibility issues

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#12304]
***Description***:
* **Current behaviour**: 

Doesn't work with AdGuard enabled. Disabling HTTPS filtering has no effect.

* **Expected behaviour**: 

Should work.

***Steps to reproduce the problem***:

1. Enable AdGuard protection;
2. Launch the app and try to log in;
3. You'll get nothing.

Excluding the app from HTTPS filtering has no effect.
Completely disabling HTTPS filtering has no effect.

***System configuration***

**Logs:**
Available under 1319407

**Filters:**
"English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Mobile Ads filter"

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 8.0.0
Browser:                               | N/A
AdGuard version:                       | 2.10.176
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Mobile Ads filter"
AdGuard mode (Android only):           | Proxy (manual)
Filtering quality (Android only):      | High-speed
HTTPS filtering (Android only):        | On (Default mode)
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 1319407

**Comment by ameshkov** [comment]
This was discussed a couple of times. Add `nest.com` to HTTPS exclusions. 

The issue will go away in the next Android update.

**Comment by akmLaVx** [comment]
@ameshkov Adding nest.com to HTTPS exclusions did not help, the issue still persists.
Logs available under 1319407. Could you please take a look?

**Comment by ameshkov** [comment]
Oh, my bad, I thought that was about desktop.

@akmLaVx I doubt that this can be easily resolved in proxy+manual mode.

Here are some things to try:

1. Disable AG completely for that app
2. Check how it works in the VPN mode (should be just okay).
3. It also should be okay in the proxy+auto mode

**Comment by akmLaVx** [comment]
1. Doesn't work
2. Works, but the customer is using other VPN apps. He can't switch to local VPN permanently;
3. Device is not rooted

**Comment by ameshkov** [comment]
There's not much we can do from our side -- the app does not support properly support proxies.
