### ISSUE TITLE
domenolog.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#12318]
[http://domenolog.ru/yandex.ru](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fdomenolog.ru%2Fyandex.ru)

 Остатки от рекламы - 1,2: `domenolog.ru##.hidden-print[style]` ; 3-6: `domenolog.ru##div:has(> [id^="yandex_rtb"])`

<details><summary>Screenshot:</summary>

![domenolog ru](https://user-images.githubusercontent.com/17948007/36673390-b69b334e-1b13-11e8-9a71-cc831d5f46ee.png)
</details>

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.8.5 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
поправил
