### ISSUE TITLE
m.blog.daum.net

### ISSUE THREAD

**Issue by Githubmaniak** [AdguardTeam/AdguardFilters#123245]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.0

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://m.blog.daum.net/dltmdal19/16308189, https://namu.wiki/w/굽네치킨

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Japanese filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, Filter unblocking search ads and self-promotion, EasyList, List-KR, YousList

### Add your comment and screenshots

1. <comment>
AdGuard is detected by Kakao TV videos attached to other sites. Below is the HTML tag of the Kakao TV video on the webpage.
<figure
  data-ke-type="video" 
  data-ke-style="alignLeft" 
  data-video-host="kakaotv" 
  data-video-url="https://kakaotv.daum.net/embed/player/clip&#108;&#105;&#110;&#107;/op6_WJCF_Ns%24@my?service=daum_blog" 
  data-video-thumbnail="http://cfs5.flvs.daum.net/files/50/25/21/89/31507274/thumb.jpg" 
  data-video-play-service="daum_blog" 
  data-video-width="640" 
  data-video-height="360">
  <iframe src="https://kakaotv.daum.net/embed/player/clip&#108;&#105;&#110;&#107;/op6_WJCF_Ns%24@my?service=daum_blog" width="640" height="360" frameborder="0" allowfullscreen="true"></iframe>
<figcaption></figcaption>

Same thing happens with namu.wiki.

<iframe class='wiki-media' allowfullscreen='' width='640' height='360' frameborder='0' src='//tv.kakao.com/embed/player/cliplink/381281640' loading='lazy' data-v-e45978b7></iframe>

2. Screenshots
<details><summary>Screenshot 1:</summary>

[![3-E42-A9-DB-AFEA-4-AA9-A1-EB-EA68-B524-C598.png](https://i.postimg.cc/L8M1NMjG/3-E42-A9-DB-AFEA-4-AA9-A1-EB-EA68-B524-C598.png)](https://postimg.cc/0bcjyFWC)

</details>

<details><summary>Screenshot 2:</summary>

[![DEDD16-DD-A10-A-4916-B39-D-24-FCC50619-D3.png](https://i.postimg.cc/7Pd7JzhH/DEDD16-DD-A10-A-4916-B39-D-24-FCC50619-D3.png)](https://postimg.cc/DmQmt81H)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
Did you test with advanced protection of AdGuard for iOS?
@Githubmaniak

**Comment by Githubmaniak** [comment]
> 

Advanced mode was not tested.

**Comment by piquark6046** [comment]
@Githubmaniak Then, please test with advanced protection.

**Comment by Githubmaniak** [comment]
@piquark6046 I'm using the free version, so I can't use the advanced protected mode.

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/123245#issuecomment-1172833081
You can purchase AdGuard for iOS Pro, or transfer to an Android device.

If you can neither, please use the following rules:
```
@@||kakaotv.daum.net/embed/player/image/ads.png$domain=tv.kakao.com|play-tv.kakao.com|kakaotv.daum.net
kakaotv.daum.net,play-tv.kakao.com,tv.kakao.com#@#ins.kakao_ad_area
kakaotv.daum.net,play-tv.kakao.com,tv.kakao.com#@##adBlockPixelTag
kakaotv.daum.net,play-tv.kakao.com,tv.kakao.com#@#.banner_ad
@@||tv.kakao.com/embed/player/image/ads.png$domain=tv.kakao.com|play-tv.kakao.com|kakaotv.daum.net
@@||videoads.kakao.com/adserver/api/v2/vmap$domain=tv.kakao.com|play-tv.kakao.com|kakaotv.daum.net

```

**Comment by piquark6046** [comment]
@Githubmaniak
