### ISSUE TITLE
Scam domain report

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#123435]
Здравствуйте!

Домен [https://dumpishop.ru/](https://dumpishop.ru/?ref=10767) является мошенническим и предназначен для выманивания платёжных данных.

К примеру по следующей ссылке:
https://dumpishop.ru/category/keys

Для вашего удобства создал аккаунт:
Логин/пароль: Scamrrrrrr/1234567

Продаются СКАМ ключи к псевдо валютам (скрин 1). После выбора ранодомного «товара» (http://dumpishop.ru/eshop_show/46) предлагается пополнить баланс (скрин 2). После получения ошибки, переходим во вкладку «пополнения баланса» (скрин 3). И выбираем рандомную платёжную систему (скрин 4). После нажатия на кнопку пополнить, мошеннический сайт просит ввести сумму в рублях (скрин 5). Пусть будет 900. После нажатия на кнопку оплаты, попадаем на мошенническую страницу с просьбой перевести деньги на мобильный номер (скрин 6) и текстом «По просьбам наших пользователей, мы отключили стандартный мерчант QIWI и установили способ пополнения "Прямым переводом".»

Скриншоты:

https://i.ibb.co/GtGZGsj/67-F3-A3-AB-DDFF-46-B2-82-E9-024-EB68-C9-EE7.jpg
https://i.ibb.co/ssbSPTz/AB0-C12-E7-EB8-D-49-FE-9-B9-D-D856-BACE7-E82.jpg
https://i.ibb.co/5cqQ95s/CF613593-897-E-4-A85-85-AC-CC67-BA0-FC1-C2.jpg
https://i.ibb.co/3rrpzWK/07-EAA358-4-ACA-49-FD-942-A-7-F0-A61129745.jpg
https://i.ibb.co/CnwZrnF/56-BB80-CE-75-D2-4332-A225-10-EFD0-E4-B115.jpg
https://i.ibb.co/QDt06vc/97658-FC9-BB4-C-4-F4-C-9-B72-F2166-A9-B50-F6.jpg

Прошу принять меры и заблокировать указанный ресурс.

**Comment by Alex-302** [comment]
@Oniqqqq Please take a look.

**Comment by Oniqqqq** [comment]
Thank you for reporting this. added to safe browsing list
