### ISSUE TITLE
m.search.naver.com

### ISSUE THREAD

**Issue by Githubmaniak** [AdguardTeam/AdguardFilters#123534]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.0

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://m.search.naver.com/search.naver?sm=mtp_hty.top&where=m&query=

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Japanese filter, AdGuard Social Media filter, AdGuard Annoyances filter, Filter unblocking search ads and self-promotion, EasyList, List-KR, YousList

### Add your comment and screenshots

1. If AdGuard is turned on on the NAVER search results page, the layout will be broken, image search will not load results, and some elements will not work, such as advanced search or view more results. Conversely, if you turn off AdGuard completely, it will display normally (font size and rows do not change), and some elements will also work normally.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![F5BF9D8E-846F-4CF5-806E-49F68C379641](https://user-images.githubusercontent.com/103377449/177201530-8bc45621-5d89-4c58-923c-4f770c09c409.jpeg)

</details>

<details><summary>Screenshot 2:</summary>

![9CEAE005-0D23-430A-B42D-241D1FB9D421](https://user-images.githubusercontent.com/103377449/177201581-a71205e3-54b8-432e-899f-5ec10520b7d2.jpeg)

</details>

<details><summary>Screenshot 3:</summary>

![A5927544-747F-4625-8B39-074B3EB3C44A](https://user-images.githubusercontent.com/103377449/177201629-a178c8c9-3c26-48f6-a189-84bb1938f7c8.jpeg)

</details>

<details><summary>Screenshot 4:</summary>

![0E4D4984-DEAC-42ED-BD38-955F533DA44A](https://user-images.githubusercontent.com/103377449/177201661-84b780c1-34b4-4957-a44d-d3a748074c57.jpeg)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
@Githubmaniak 
Fixed. But, I cannot reproduce your font issue.

**Comment by Githubmaniak** [comment]
@piquark6046 There seems to be a problem with the user rule written at https://m.ppomppu.co.kr/new/bbs_view.php?id=freeboard&no=7614838&extref=1 that I was using or there was a conflict with some activated filters.
