### ISSUE TITLE
Tsubasa.im mobile

### ISSUE THREAD

**Issue by exomarty** [AdguardTeam/AdguardFilters#123970]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.0 (954)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://tsubasa.im/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>
After this commit https://github.com/AdguardTeam/AdguardFilters/commit/c64fba7e3b0cb8f25355610c9b6f883544580430
The webpage on mobile reloads for infinite time
On desktop the antiadblock filter works ok 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. It seems it is still working on my device. Please enable AdGuard Chinese filter(do not switch to another app during 60 seconds)

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/178679928-f214f2f4-900e-410a-a1ce-377e151849b5.png)


</details>
