### ISSUE TITLE
The half-transparent annoyance on udn.com isn't hidden in Safari.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardFilters#12400]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
Issue URL: https://udn.com/news/index — Annoyance
Issue Type: Annoyance
Comment:
Screenshot: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/oFFcyZZ.png)
</details><br/>

***Steps to reproduce the problem***:
1. Use Safari with AdGuard Pro's Safari content blocker.
(The annoyance can be hidden by AdGuard for Android.
But the Safari content blocker of AdGuard Pro for iOS is unable to hide it.)

2. Visit https://udn.com/news/index
**Not every page of a news has the half-transparent annoyance.**
You can try to read more different news on udn.com.
Ex:
https://udn.com/news/story/6811/3004600?from=udn-catebreaknews_ch2

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | iOS
Operating system version (Android/iOS) | v11.2.6
Browser:                               | Safari
AdGuard version:                       | AdGuard Pro for iOS beta v2.0.0(140)
Filters enabled:                       | English filter, Spyware filter, Social media filter, Annoyances filter, Safari filter, EasyList China filter, CJX's Annoyance List and NoCoin Filter List
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | ?
HTTPS filtering (Android only):        | ?
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | No
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by lancelot-moon** [comment]
Eh, you solved the half-transparent annoyance in Mobile Ads filter in the past.
I found the rule in Mobile Ads filter.
udn.com##.overlay-container

Because I didn't enable Mobile Ads filter for Safari, the half-transparent annoyance isn't hidden.
udn.com is a news website.
Is it possible that you move the 2 rules from Mobile Ads filter to English filter?
udn.com##.overlay-container
udn.com##.only_mobile.mm-slideout

Thanks.

**Comment by Alex-302** [comment]
No. Please enable mobile filter for this.

**Comment by lancelot-moon** [comment]
They are annoyances.
Or why not put them in annoyances filter?
I have around 40k+ rules for Safari after enabling EasyList China filter.
No quota for Mobile Ads filter.
Mobile Ads filter is also not one of default filters for Safari.

**Comment by Alex-302** [comment]
This is ad leftover.
