### ISSUE TITLE
Appstore:id1602212505 App name:Nays Adguard DNS breakage

### ISSUE THREAD

**Issue by gototheskinny** [AdguardTeam/AdguardFilters#124156]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

Dns

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://apps.apple.com/us/app/nays/id1602212505

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

1. Adguard DNS service breaks Nays(Turkish Finance app) customer support chat service and never connects(I waited for customer support for hours). trust me when I switched back to Google dns I've only waited for 5 minutes. This is a serious problem. For reproducing unfortunately you'll need an account and probably a Turkish citizenship number for signing up. 

2. Screenshots <details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@gototheskinny Hi. I can't read Turkish and register.

You may help us to fix this problem, if you show blocked DNS requests in DNS log(please clear it, reproduce an issue and make screenshots).
