### ISSUE TITLE
Leftovers

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#124193]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.0.181

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://bdnews24.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

![image](https://user-images.githubusercontent.com/46019727/178651305-c855c32c-28ae-41a3-9262-25e15c16e868.png)

The website has some leftover ads
these seems to get blocked in the past but from today the leftovers are there and if I enable easylist filters then they dissapear. Can you please check as if I remember easylist is already included in the adguard filters

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I don't see leftovers on my end.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/178706139-8e3bb206-0572-4a4f-92c6-eb2b91c82add.png)

</details><br/>
