### ISSUE TITLE
[iOS] tjournal.ru - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1241]
![image](https://cloud.githubusercontent.com/assets/15856304/12091422/ae32dfdc-b2ff-11e5-9f3f-19dd7dbd2bd6.png)

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.73.63 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.32 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.87 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.23.60 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.78 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.29.71 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.1.96 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.25 Enabled=YES
ID1 Name="EasyList" Version=1.0.46.60 Enabled=NO
ID5 Name="RU AdList" Version=1.0.46.61 Enabled=NO
ID2 Name="Fanboy's Annoyances" Version=1.0.46.71 Enabled=NO
ID3 Name="Fanboy's Social Blocking List" Version=1.0.46.59 Enabled=NO
ID!5 Name="Fanboy's Enhanced Tracking List" Version=1.0.0.88 Enabled=NO
ID 7 Name="Adblock Warning Removal List" Version=1.0.49.98 Enabled=YES
ID 9 Name="Prebake" Version=1.0.1 Enabled=NO
ID!1 Name="Anti-Adblock Killer | Reek" Version=1.0.1.55 Enabled=YES
ID!2 Name="RU AdList: Counters" Version=1.0.43.21 Enabled=NO
ID!3 Name="RU AdList: BitBlock" Version=1.0.46.49 Enabled=NO

RFY-147-18544

**Comment by Alex-302** [comment]
На айпаде чисто/ Пусть попробует выключить ненужные фильтры, или проверить не включены ли оптимизированные фильтры,
