### ISSUE TITLE
dripemail2.com requires re-evaluation

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#12425]
***Description***:
* **Current behaviour**: 

Blocked as malicious domain.

* **Expected behaviour**: 

Shouldn't be.

* **User's comment (IMPORTANT)**:

Our email domain, dripemail2.com <http://dripemail2.com/>, was tagged as malicious by AdGuard. Unfortunately we recently went under a coordinated spammer attack earlier this month and that has damaged our overall sender reputation. We have since put a stop to these spammers as well as fortified our tools and safeguards to prevent them from getting back into our system. So now we are trying to clean up the mess and fallout that has occurred because of this.

Is it possible to have our domain re-evaluated, as we are not only embarrassed this happened, but we have taken a lot of measures to ensure this doesn’t happen again. I would truly appreciate an opportunity to have our domain re-evaluated.

**Comment by Alex-302** [comment]
Not reproduced.
Btw I can't block/unblock in phishing database.
