### ISSUE TITLE
com.google.android.apps.maps

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#12424]
***Description***:
* **Current behaviour**: 
Somehow blocked by AdGuard. Unable to calculate route to any address.

* **Expected behaviour**: 
Shouldn't be impacted by AdGuard.

***Steps to reproduce the problem***:

1. Enable protection
2. Launch the app and try to calculate route to any location

***Logs***:
Available under user id 1470818.

***System configuration***

**Filters:**

"English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Mobile Ads filter", "hufilter"

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 6.0.1
Browser:                               | N/A
AdGuard version:                       | 2.10.176
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Mobile Ads filter", "hufilter"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 1470818

**Comment by Alex-302** [comment]
@altokarev @vozersky please take a look

**Comment by vozersky** [comment]
can't rep but we have one more complaint about this issue, could you please try? @zebrum

**Comment by zebrum** [comment]
can't reproduce
