### ISSUE TITLE
English Filter - seems to be doubled and have some issues

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardFilters#12448]
I updated my blocking filters using my ios app and now the size is doubled.

The English Filter is the one that causing the issue of more than 50,000 filter! 

Please have a look. Is this normal?

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/27464836/36841360-31eff2fc-1d9c-11e8-9425-f3891a172322.png">

**Comment by Alex-302** [comment]
fixed.
