### ISSUE TITLE
AdGuard reportedly blocks outbound emails on Mac

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#12452]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

> I use Adguard for Mac on 2 computers. I have noticed problems when I send emails to certain recipients (they never receive the email). For example... I just sent email from my home email account (****@he********phis.com) from the Mail app on my Mac (OS 10.13.3) to my other email address @gmail.com. I never received the email at my Gmail account. I then disabled Adguard protection and sent another email and it succeeded. I repeated this a few times. I noticed that when I went to the AdGuard preferences and unchecked "Mail" from the Applications list under "Automatically Filtered Applications", then emails worked again.

* **Current behavior**: 

AdGuard blocks emails

* **Expected behavior**: 

AdGuard does not interfere with macOS Mail app in that way

***Steps to reproduce the problem***:

Outlined in the description

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | macOS 10.13
Browser:                               | n/a
AdGuard version:                       | 1.5.3
Filters enabled:                       | 2, 3, 10
HTTPS filtering:        | On
AdGuard DNS:                           | None 
Helpdesk ID (if exists):               | 1772725 (debug available)

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
What user see in the filtering log? I mean blocked requests after sending email.

**Comment by tjherring** [comment]
I am not sure what you have asked.  Please clarify and I will try to provide the information that you need.

**Comment by Alex-302** [comment]
@tjherring please try to check with disabled filters(in AdGuard settings).

**Comment by tjherring** [comment]
Hi I have disable the filters on adguard for mac for the "Mail" application.  I am able to send email now.  But I would like this resolved so that I won't have to manually select this.
TJ

**Comment by Alex-302** [comment]
@tjherring ok. Please disable filters one-by-one and find which filter causes this issue. After that, open filtering log and reproduce the issue. After that make screenshot of blocked requests
![image](https://user-images.githubusercontent.com/8361299/38381424-677ab0a4-390f-11e8-92ea-5d0f1e1ea6d5.png)
