### ISSUE TITLE
[iOS] [MacOS] iBooks issues 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1246]
http://prntscr.com/9mbqux
the page is blank

ADGuard блокирует iBooks Store При активированной защиты ADGuard, он блокирует магазин iBooks Store на iMac В результате отображается белый экран в магазине. При отключении защиты, магазин корректно работает и возможно покупать книги

BHD-401-43613
HRF-484-35686

**Comment by Alex-302** [comment]
Как туда зайти-то?
