### ISSUE TITLE
AdGuard Family Protection DNS blocks calls on Slack

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#12472]
> I had an issue while using your DNS (which has worked great BTW!) where I was unable to connect on calls made through Slack. I have tried a few times but had to change the DNS and then it immediately went through. How can this be whitelisted?

ID: 1775188

**Comment by Alex-302** [comment]
Not reproduced.
@zebrum @vozersky please take a look/

**Comment by zebrum** [comment]
reproduced

**Comment by Alex-302** [comment]
I see no blocked domains:
 ![image](https://user-images.githubusercontent.com/8361299/37040148-cac98218-2161-11e8-96c7-b2faa73fd240.png)

**Comment by Alex-302** [comment]
Damn. These domains are blocked by parental control module of AG for Windows:
universal.slack-core.com
ca.slack-edge.com
prod.slack.map.fastlylb.net
emoji.slack-edge.com

**Comment by ameshkov** [comment]
Have you unblocked them?

**Comment by Alex-302** [comment]
It seems they are not blocked at the moment.

**Comment by ameshkov** [comment]
Блокируется же Лех:
http://pctrl.adguard.com/check-parental-control?domain=slack-core.com&sensitivity=3

**Comment by ameshkov** [comment]
Разблокировал все
