### ISSUE TITLE
rutracker.org - missed ads on the homepage in Firefox for Android

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#1249]
Source complaint:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=45878452

I've asked user if he has the same issue in other browsers:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=45904571

**Comment by Alex-302** [comment]
It is clean on my phone.

**Comment by ameshkov** [comment]
Still there're some ads in user's case.

I guess we need to see it through remote access.
