### ISSUE TITLE
ads.yieldmo.com

### ISSUE THREAD

**Issue by wrt54g** [AdguardTeam/AdguardFilters#124990]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

0.107.8

### What type of problem have you encountered?

Missed ads or ad leftovers, Missed analytics or tracker

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

ads.yieldmo.com

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

It still connects to this site via optout.aboutads.info
![image](https://user-images.githubusercontent.com/85389871/180086905-3ce58dea-bf1c-4c86-a66f-464878d8e7d5.png)

![image](https://user-images.githubusercontent.com/85389871/180086859-fd6afd64-0b05-4e9a-9af6-c63730baf67f.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It is covered by `||yieldmo.com^`
