### ISSUE TITLE
bbc.co.uk

### ISSUE THREAD

**Issue by DesertBear** [AdguardTeam/AdguardFilters#124932]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin (1.43.0); AdGuard Annoyances filter (2.1.27.2)

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.bbc.co.uk/news/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1. After viewing three BBC News pages, it displays a fullscreen sign in page.  It may not appear for people with IP addresses that are not in the UK, I don't know.  Steps to reproduce:

    **A)** Go to https://www.bbc.co.uk/news/business-62226912

    **B)** Go to https://www.bbc.co.uk/news/technology-62236778

    **C)** Go to https://www.bbc.co.uk/news/science-environment-62234196

    **D)** On the third page, it displays a fullscreen sign in page (see screenshot)

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screesnshot A](https://user-images.githubusercontent.com/27423064/179995478-bfec1cd6-bbd9-4930-ad52-1edccd349dd5.png)

</details>

3. Action
When manually adding the below rule to uBlock Origin, the sign in dialogue no longer appears, however it's not possible to scroll the page anymore.
```
bbc.co.uk##.e34ixc510.ssrcss-veoawf-Overlay
```
When manually adding either of the below rules as well, it's still not possible to scroll the page.
```
bbc.co.uk##html:style(overflow: visible !important;)
```
```
bbc.co.uk##:root:style(overflow-y: visible !important;)
```

4. Details
```
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 91467
  cosmetic: 157934
  scriptlet: 24377
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 55146-76, now
    block-lan: 43-0, 2m
    fanboy-annoyance: 75576-3116, 1m
    ublock-annoyances: 4494-213, 1m
  default: 
    user-filters: 84-0, never
    easylist: 68658-91, 2m
    easyprivacy: 27428-221, 2m
    plowe-0: 3645-781, 1m
    ublock-abuse: 76-0, 1m
    ublock-badware: 4204-92, 1m
    ublock-filters: 32241-487, 1m
    ublock-privacy: 226-12, 1m
    ublock-quick-fixes: 239-9, 1m
    ublock-unbreak: 1834-47, 1m
    urlhaus-1: 5198-0, 1m
filterset (user): [array of 84 redacted]
trustedset: 
  added: [array of 6 redacted]
hostRuleset: 
  added: [array of 20 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 4147 ms
  maxAssetCacheWait: 601 ms

```

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reproduced.
