### ISSUE TITLE
Missing splitted filters for the "Report an issue" form.

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardFilters#125081]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

These new splitted filters are missing for the "Report an issue" form. If the user enables one of them and tries to report a issue, they will not appear in the form. Only the "AdGuard Annoyances" filter appears in the form.

<details><summary>Screenshot</summary>

![Form](https://user-images.githubusercontent.com/35523759/180346872-6c5e98c1-8c2f-44d8-bca1-694902a9c441.png)
</details>

### Proposed solution

Add splitted filters (AdGuard Cookie Notices, Popups, Mobile App Banners, Other Annoyances and Widgets) to "Report an issue" form.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/ReportsWebApp #307](https://github.com/AdguardTeam/ReportsWebApp/issues/307) via [**ZenHub**](https://www.zenhub.com/)
