### ISSUE TITLE
Chrome newtab popup

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardFilters#125156]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.8.1.1140

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

newtab

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Remove X-Client-Data header from HTTP requests, Disable cache for third-party requests, Hide your Referrer from third-parties (specify in comment below, if used custom value), Hide your User-Agent (specify in comment below, if used custom value)

### Add your comment and screenshots

1. Can it be blocked? Also sent to filters@adguard.com saved page. 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/19418601/180585586-ca8f3b68-7a13-456e-a11e-b80b11f15889.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by rakleed** [comment]
.

**Comment by rakleed** [comment]
.

**Comment by Alex-302** [comment]
Если это страница браузера, то не убрать.
