### ISSUE TITLE
tv.gab.com youtube-like ads

### ISSUE THREAD

**Issue by Mennaruuk** [AdguardTeam/AdguardFilters#125247]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.0.204

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://tv.gab.com/channel/ankush012/view/the-smoothie-diet-21-day-rapid-62dc1f90aa6babef2705749d

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, EasyList, EasyPrivacy, Web Annoyances Ultralist

### Add your comment and screenshots

1. gab tv now has ads just like youtube, they keep showing up whether ublock origin is on or off.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/52135169/180644189-09ba0d0e-4635-4eaa-ae87-7448a055caed.png)

</details>

3. [Already fixed by uBlock Origin](https://github.com/uBlockOrigin/uAssets/issues/14037#issuecomment-1186102046)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reproduced.
Please record a HAR file and send it + link of this issue it to `filters@adguard.com`
How to get a HAR file:
https://toolbox.googleapps.com/apps/har_analyzer/
