### ISSUE TITLE
Inclusion of s.youtube.com in your Tracking Protection filter is breaking  in-app history on Youtube's android app!

### ISSUE THREAD

**Issue by p-patra** [AdguardTeam/AdguardFilters#125347]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

None. 

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

Youtube app on android.

### What filters do you have enabled?

AdGuard Tracking Protection filter

### Add your comment and screenshots

1. s,youtube.com is being used by Youtube to sync watch history, By blocking that History sync doesn't work in the app.  

2. Screenshot of the URL blocked. ![image](https://user-images.githubusercontent.com/106650211/180828975-e3a8398e-edda-452f-9050-34c23c619b51.png)

### Privacy

- [X] I agree to follow this condition

**Comment by THEtomaso** [comment]
history ≈ tracking

**Comment by Alex-302** [comment]
We do not block `s.youtube.com` in DNS filter. In TPF we have a fix `@@||s.youtube.com^|`
