### ISSUE TITLE
[iOS] tieba.baidu.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1253]
![image](https://cloud.githubusercontent.com/assets/15856304/12171975/bd0482a4-b502-11e5-9acb-6c85acec77f7.png)

JIC-362-92725

**Comment by Alex-302** [comment]
Don't see this banner. But it is not looks like ad.

**Comment by evgeniy-ADG** [comment]
Two pop-ups at the same time look suspicious anyway.

**Comment by Alex-302** [comment]
I don't see them. Need html code of them.
On my end this site tried to open app store without popups
