### ISSUE TITLE
Caching local content?

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdguardFilters#12548]
Hi,

Not sure if this is the right place to post. This is more of a request than a report.

Could we do something like this:
https://www.ghacks.net/2018/03/02/adblock-extension-introduces-local-content-caching-solution/
Caching some common contents for local delivery? It can come as a subscription that users can choose to enable, rather than hard-coded in the software, to not bloat the software download.

**Comment by Alex-302** [comment]
Not sure if it really useful option. But you can ask in this repository
https://github.com/AdguardTeam/AdguardBrowserExtension
