### ISSUE TITLE
[iOS] ukrainianiphone.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1254]
![image](https://cloud.githubusercontent.com/assets/15856304/12172001/e5d490e8-b502-11e5-8ac5-2cf637d112ec.png)

KDX-439-10423

**Comment by Alex-302** [comment]
Знать бы куда он нажал. У меня не выскакивает.

**Comment by Alex-302** [comment]
на айпаде с упрощенными фильтрами чисто
