### ISSUE TITLE
yottlyscript.com is not a 3rd party tracker

### ISSUE THREAD

**Issue by smikeecz** [AdguardTeam/AdguardFilters#125545]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.0.204

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://moodo.pl/

### What filters do you have enabled?

AdGuard Tracking Protection filter

### Add your comment and screenshots

1. Hello,

I would like to ask if it would be possible to remove from https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/tracking_servers.txt the entry for `||yottlyscript.com^`.

`yottlyscript.com `does not use 3rd party cookies nor is it involved in the advertising system, this script is only used for internal site personalization (i.e. only products of that site are offered on that page).

For example, on the homepage of `https://moodo.pl/` the widget containing personalised products is not visible - please see the screenshot.

If any information needs to be added, feel free to contact me.

Thank you very much for your cooperation

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/32652690/181260372-a2cb9f00-4198-4eb6-b9c5-154a9cbe7c65.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Just disable this filter if personalization using 3p scripts is acceptable for you.
Blocked more analytics here.

**Comment by smikeecz** [comment]
Hello,

this solves the problem only on my side, but we need our Moodo.pl website was working for everyone in the same way - including all banners and products. Personalisation is not using 3party cookie as I described above. This is a very common scenario to use an external service for website personalization, this service is not using 3rd party cookies.

Thanks for your consideration,
Michal

**Comment by Alex-302** [comment]
It can be used with GA.
In any case, this filter is not enabled by default.

**Comment by smikeecz** [comment]
Not sure what you mean by "can be used with GA" - we are using this just for onsite personalization.  Even though this filter is switched off by default, some of our clients made a complaint that the page view is not complete for them and we would like to keep the page always fully visible.

**Comment by Alex-302** [comment]
> Not sure what you mean by "can be used with GA"

https://doc.samba.ai/knowledge-base/web-personalisation-via-javascript-api/?lang=en

**Comment by smikeecz** [comment]
GA is not involved there, only GTM is mentioned as a place where the script can be placed.

**Comment by smikeecz** [comment]
@Alex-302 
filter tracking_servers.txt is defined according
to https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/tracking_servers.txt as "the list of third-party tracking networks
domains". According to https://kb.adguard.com/en/general/adguard-ad-filters#adguard-filters the "Tracking Protection Filter" is "comprehensive
list of various online counters and web analytics tools". Since the script
is used only for onsite personalisation (only products from this specific site
can occur there) with no usage of 3rd party cookies and no connection to any
tracker server network, and it's essential for a basic functionality of the
site, I suppose `yottlyscript.com` doesn't belong to this list.

It's totally product placement (not commercial) tool for e-commerce and this is
not mixing data between couple different websites. Blocking it can have large
impact on ehops’ layout view as same as for example blocking other important
e-commerce addons like product search, saving products in cart or managing products
order on category listing.

Please reconsider your opinion again.

Thank you.
