### ISSUE TITLE
Soundcloud playback stops randomly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#12564]
@danidoedel commented on [Wed Feb 28 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2133)

[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Soundcloud playback stops after few minutes. For example here after 11:30: https://soundcloud.com/monstercat/cotw185?in=monstercat/sets/monstercat-podcast

Couldn't start other tracks as well except a few random tracks. Reloading the page didn't fix the issue. After closing AdGuard completely the track continued playing instantly.

This happens since a few weeks already, but not sure since when exactly.

Maybe that's a filter issue, but I'm not sure that's why I opened the issue here.

I will try to save a log, but it's not too easy to reproduce ;)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  Windows 10 x64
Browser:                               |  Chrome 66.0.3355.0
AdGuard version:                       |  6.2.437.2171
Filters enabled:                       | English, German, Spyware, Annoyance, Social
AdGuard DNS:                           | None
Stealth mode options (Windows only)    |  Hide search queries, send do-not-track header, remove x-client-data, self-destructing third-party cookies (30), disable cache for third-party requests, block webrtc, block location api

---

@ameshkov commented on [Sun Mar 04 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2133#issuecomment-370183782)

Most likely this is a filters issue.

**Comment by BlazDT** [comment]
So far not reproduced.

@danidoedel 
Is the progress bar at the bottom stuck too or is it continuing?

**Comment by danidoedel** [comment]
@BlazDT The progress bar looks like it's playing, but the time stops. Also the symbol at the right shows the loading state.

![image](https://user-images.githubusercontent.com/10995998/37111168-50cf0058-223f-11e8-84b6-bf3b2f7504c0.png)

Happened today at 19:38 again:

[adg_logs_6.3.804.2883_0307_1938.zip](https://github.com/AdguardTeam/AdguardFilters/files/1790451/adg_logs_6.3.804.2883_0307_1938.zip)

**Comment by BlazDT** [comment]
Not seeing anything special there.

Please try one of these rules:

```
@@||soundcloud.com^$jsinject,content
@@||play.google.com/log$domain=google.com
```

**Comment by danidoedel** [comment]
Doesn't seem to change anything... I really don't think that's a filter issue tbh...

**Comment by danidoedel** [comment]
Doesn't seem to be an issue anymore. Whatever it fixed ;)
