### ISSUE TITLE
Stealth mode breaks HCaptcha

### ISSUE THREAD

**Issue by androidacy-user** [AdguardTeam/AdguardFilters#125663]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0 nightly 34

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

Everywhere 

### What filters do you have enabled?

AdGuard Annoyances filter, AdGuard Experimental filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Block WebRTC, Block Location API

### Add your comment and screenshots

Seriously your web reporting tool is awful - URL fields keep deleting and replicating contents on mobile.

Anyway

HCaptcha is broken with stealth mode on. I know the filter required to fix it but not how to add it so here it is:
```
@@||hcaptcha.com$stealth,important
```

Without that HCaptcha challenges don't show at all

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Please post an example URL where it is implemented, thank you.

**Comment by krystian3w** [comment]
> Seriously your web reporting tool is awful - URL fields keep deleting and replicating contents on mobile.

That can by Samsung bug or low end smartphone bug, then try reboot device and fill webform again.

If bug back maybe needed is change smartphone to pure/clean/stock Android or iPhone.

**Comment by krystian3w** [comment]
Not everywhere, static legacy pages e.g. form Greece no use CMS and any anti bot games with "puzzle".

**Comment by Alex-302** [comment]
@androidacy-user Which option of Stealth Mode breaks a site? And which site?
