### ISSUE TITLE
mail.yahoo.com - occasional ads still appearing

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1258]
![image](https://cloud.githubusercontent.com/assets/15856304/12215187/7c76c638-b666-11e5-815d-0301172c1b20.png)

I don't have additional input on what is triggering this issue but on mail.yahoo.com I continue to see ads across two browsers (Safari and Opera) even when Adguard is running. The snapshot is similar to what I have posted earlier (just a different ad). I'm clueless as to what is triggering this - this is happening even after I have cleared all cookies/cache/browsing history from the browser cache. 

GLO-371-89758

**Comment by Alex-302** [comment]
It is clean on my end. Need the filter list(can't find in in GLO-371-89758)

**Comment by evgeniy-ADG** [comment]
At my end it's ok too, but the customer states that those ads appear just occaaaasionally. Here's the information you've requested:

In the "Adguard filters", I have the following enabled
- English filter
- Spyware filter
- German filter
(the filter for useful ads is not enabled)

In the "Easylist"
- Easylist Czech and Slovak
- ROList

I also have one "User filter" with about 10-12 sites. 

Automatically filter applications and filter https are enabled (with about 10 exclusions). 

Yahoo is nowhere in my user filter or https exclusions. The option to use Adguard as a proxy is not enabled.

**Comment by Alex-302** [comment]
Still can't reproduce.
Ask him him TeamViewer

**Comment by evgeniy-ADG** [comment]
Ok.

**Comment by evgeniy-ADG** [comment]
Done. Will keep you updated.
