### ISSUE TITLE
Блокировка раздражающих элементов

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#125801]
Помогите, пожалуйста заблокировать выделенные элементы.

Сайт с проблемой ficbook.net (Книга Фанфиков)

На первом и втором скриншоте «обложка» к любой из работ. Очень раздражают эти картинки.

Для повторения:
Откройте к примеру [эту ссылку](https://ficbook.net/fanfiction/movies_and_tv_series/garri_potter) и вы увидите работы с картинками. Вот эти картинки и надо убрать.

на третьем скриншоте - смайлик в поле ввода комментариев (находится под каждой работой). Раздражает потому как из-за случайного нажатия навязывает улучшение аккаунта.
![A8B92759-378A-485D-97DB-BFCEDB8B161C](https://user-images.githubusercontent.com/110291196/181914268-5e9d2b1d-faaa-4fd4-9720-722d183799c7.jpeg)
![A8F3227F-9981-4C5F-9769-C16193860B19](https://user-images.githubusercontent.com/110291196/181914271-5450f8e3-8977-4df6-a217-c444f0b0e989.jpeg)
![C2EF69D4-3504-4EC0-A2D6-7D469E11FF00](https://user-images.githubusercontent.com/110291196/181914272-0d2b8ad1-19f9-44f0-b0f7-bb7cb49bf4a5.jpeg)

**Comment by Alex-302** [comment]
Здесь описано как это можно сделать
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters
