### ISSUE TITLE
Ошибка при отправке рапорта! / Error sending report

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardFilters#125974]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

v3.6.7 (41)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://reports.adguard.com/ru/new_issue.html?product_type=And&product_version=3.6.8%20(46)&filters=3.4.17.1.14.11.2&android.system_root=false&android.mode=VPN&android.method=High-quality&android.apps_filtering=false&https.filtering=true&dns.enabled=true&dns.servers=System&dns.filters_enabled=true&dns.filters=https%3A%2F%2Ffilters.adtidy.org%2Fandroid%2Ffilters%2F15_optimized.txt&dns.timeout=5000&dns.fallback_enabled=false&browsing_security.enabled=true&browsing_security.statistics_enabled=true&android.version=7.0&stealth.enabled=false&url=https%3A%2F%2Ffuck-videos.xxx%2Fen%2Fc%2Ftall%2F%3Fid%3D4119&browser=Chrome

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

 И так с утра!

![Screenshot_20220801-154719](https://user-images.githubusercontent.com/34476664/182152014-05b87517-5a9d-4903-b14d-845f1cb21bb8.jpg)

</details>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Issue moved to [AdguardTeam/ReportsWebApp #309](https://github.com/AdguardTeam/ReportsWebApp/issues/309) via [**ZenHub**](https://www.zenhub.com/)
