### ISSUE TITLE
Can't log in on http://www.ldproducts.com/customer/account/login

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1261]
![image](https://cloud.githubusercontent.com/assets/15856304/12222012/b791dfc0-b763-11e5-8b60-bcdff640b329.png)
if you disable Adguard and restart the browser:
![image](https://cloud.githubusercontent.com/assets/15856304/12222018/e668f798-b763-11e5-90be-1111c51709c6.png)

Browser IE11 - Windows 10 I'm trying to go LD Products. I can get to the home page with no problems: http://www.ldproducts.com/ Now I go to sign in with my account and I get a: 403 - Forbidden The URL dialog box contains: https://www.ldproducts.com/customer/account/login/ Seems to do this on a BUNCH of links to different pages on the site. I can disable Adguard, and restart IE11 and I can then get to all the pages. Thanks.

(upd - the same situation on chrome and other browsers)

**Comment by Alex-302** [comment]
У меня открывается, но не догружается, без Адгарда так же.
В какой стране он находится?
