### ISSUE TITLE
9to5google.com - Broken website

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#12612]
@Lululalu commented on [Mon Feb 19 2018](https://github.com/AdguardTeam/ContentBlocker/issues/106)

https://9to5google.com 

The floating top of the website is broken.

Samsung Internet 6.4, Android 7.0, Galaxy A5 2017. Adguard with default lists.

---

@vozersky commented on [Mon Feb 19 2018](https://github.com/AdguardTeam/ContentBlocker/issues/106#issuecomment-366754549)

@Lululalu 
![image](https://user-images.githubusercontent.com/17472907/36389755-620305b2-15b1-11e8-9598-6dd0ff8dc72b.png)

like this?

---

@superlex commented on [Sat Mar 03 2018](https://github.com/AdguardTeam/ContentBlocker/issues/106#issuecomment-370159683)

Hi,
@vozersky I confirm the problem. Without content blocker it doesn't occur.

Samsung Internet 6.4.10.5, LineageOS 14.1.

---

@superlex commented on [Sat Mar 03 2018](https://github.com/AdguardTeam/ContentBlocker/issues/106#issuecomment-370170903)

Disabling SocialFilter fixes the issue.
It seems related to 
~9to5google.com,~9to5mac.com,~9to5toys.com,~electrek.co##.header-social

**Comment by BlazDT** [comment]
That rule ##.header-social is not applied due to ~
Also can't reproduce on my Android :(

@AdamWr please check

**Comment by ameshkov** [comment]
Guys, don't forget that this is Samsung Internet + AdGuard CB

**Comment by BlazDT** [comment]
That's what I tried.

**Comment by ameshkov** [comment]
@vozersky are you still able to reproduce it?
https://github.com/AdguardTeam/ContentBlocker/issues/106#issuecomment-366754549

**Comment by vozersky** [comment]
yes, I am

**Comment by AdamWr** [comment]
I can reproduce it only in Samsung Internet + AdGuard CB + Social media filter.
I tried these rules:
`@@||9to5google.com^$generichide`
`@@||9to5google.com^$urlblock`
but it didn't work.

If I add `@@||9to5google.com^$elemhide` or disable Social media filter then it's okay.
I don't have idea what cause this issue.

**Comment by superlex** [comment]
@AdamWr 
I confirm:
1) Yandex Browser (18.1) works well (and I see all social elements on header-social, because of ~, right?). On the contrary with Samsung Internet these elements are hidden, so I think the problem is ~
2) @@||9to5google.com^$elemhide works, thanks

In addition, if I disable social list and I add  ##.header-social to user list it works well on both browser (that is, social elements are removed and there aren't problems).

I hope that can help you.

**Comment by superlex** [comment]
@BlazDT 
It doesn't work for me, sorry.

**Comment by ameshkov** [comment]
It seems that Samsung does not support the `generichide` modifier :(

**Comment by ameshkov** [comment]
Reopened the original issue in the CB repo, we need to figure what exactly is causing it
