### ISSUE TITLE
Ads not blocked

### ISSUE THREAD

**Issue by jakche** [AdguardTeam/AdguardFilters#126157]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

latest as of 03.08.2022 ddmmyyyy

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://bitolanews.mk https://alsat.mk/mk/ https://tera.mk https://republika.mk/ https://fokus.mk/ https://hitportal.com.mk/ https://zenskimagazin.mk https://mkd.mk https://360stepeni.mk https://libertas.mk https://vecer.press https://time.mk

### What filters do you have enabled?

AdGuard Base filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, EasyList, Fanboy's Annoyances, Fanboy's Social Blocking List, Web Annoyances Ultralist, Fanboy's Anti-Facebook List, I don't care about cookies

### Add your comment and screenshots

1. <comment>
These are Macedonian websites (.mk domain) 
Also cookies block doesn't get bypassed.
2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
There is a Macedonian filterlist at https://raw.githubusercontent.com/RandomAdversary/Macedonian-adBlock-Filters/master/Filters that you could try out as a custom filterlist, despite how it was recently [rejected from native AdGuard inclusion](https://github.com/AdguardTeam/FiltersRegistry/issues/354) due to insufficient maintenance.

**Comment by Alex-302** [comment]
Please don't post different sites in the one report(except very similar - one project)
