### ISSUE TITLE
m.search.naver.com

### ISSUE THREAD

**Issue by Githubmaniak** [AdguardTeam/AdguardFilters#126124]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.0(954)

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://m.search.naver.com/search.naver?sm=mtp_hty.top&where=m&query=

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, EasyList, List-KR, YousList

### Add your comment and screenshots

1. <comment>
Powerlinks are not blocked on m.search.naver.com and are presented with a broken layout.
2. Screenshots
<details><summary>Screenshot 1:</summary>

![F995C557-E434-4AAD-A562-64C67DEBEB54](https://user-images.githubusercontent.com/103377449/182541235-57901093-7eff-4faf-b499-787ab741faef.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
@Githubmaniak 
Did you disable all subscribed filters?
I cannot reproduce with AdGuard Browser Extension and Mozilla Firefox Dev.

**Comment by Githubmaniak** [comment]
@piquark6046 Disabling all filters gives the same symptoms.
![75B27E7E-320A-4073-98BD-63B0FF91F447](https://user-images.githubusercontent.com/103377449/182599414-9eb750ac-c256-4be3-9a94-f555e063dec2.png)
![479E7E91-0277-49A9-96B2-26FD5C3C0892](https://user-images.githubusercontent.com/103377449/182599422-4f83442e-47ae-4954-81de-623e3d887183.png)

**Comment by piquark6046** [comment]
@Githubmaniak 
Then, I think that it is a bug of [AdguardTeam/AdguardForiOS](https://github.com/AdguardTeam/AdguardForiOS).

**Comment by Githubmaniak** [comment]
@piquark6046 It seems that NAVER has updated the advertisement, considering that advertisements on other web pages such as daum are blocked.
![2B09840A-60ED-4513-B048-C73176DAE8A9](https://user-images.githubusercontent.com/103377449/182603128-2d5309ab-234d-435f-8b63-cdd0ba56b101.png)

**Comment by Githubmaniak** [comment]
@piquark6046 As a result of reconnecting to NAVER, some ads are not being blocked.

**Comment by piquark6046** [comment]
No.
It has not updated.
<details>
<summary>Screenshots</summary

![Screenshot from 2022-08-03 12-13-39](https://user-images.githubusercontent.com/98787049/182606063-1788cc02-2dac-4540-b7da-1a7a899363e0.png)
![Screenshot from 2022-08-03 12-14-36](https://user-images.githubusercontent.com/98787049/182606085-28f97e27-6c98-4d7b-b8c8-49ff3f7a8e66.png)

Filters: AdGuard Tracking Protection filter, AdGuard URL Tracking, AdGuard Social, AdGuard Annoyances and List-KR 
<details>

**Comment by Githubmaniak** [comment]
@piquark6046 There really seems to be a problem with Adguard for iOS.  I've reset or reinstalled the app, but this time the blocker doesn't work for all webpages.  thank you for the reply.
