### ISSUE TITLE
Вопрос по поводу подписок!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardFilters#126129]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.0.204

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://kb.adguard.com/ru/general/adguard-ad-filters

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Hide your search queries

### Add your comment and screenshots

<comment>
Касательно подписок, что они из собой представляют? Являются ли они частью подписки "Фильтр раздражителей" или же они дополняют её? Нужны они мне или достаточно Фильтра раздражителей?

**Фильтр cookie-уведомлений — блокирует уведомления о файлах cookie на веб-страницах. [Посмотреть правила](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_18_Annoyances_Cookies/filter.txt)
- Фильтр всплывающих окон — блокирует всплывающие окна, не имеющие отношения к функциональности сайта. [Посмотреть правила](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_19_Annoyances_Popups/filter.txt)
- Фильтр баннеров мобильных приложений — блокирует баннеры, рекламирующие мобильные приложения сайтов. [Посмотреть правила](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_20_Annoyances_MobileApp/filter.txt)
- Фильтр виджетов — блокирует виджеты онлайн-ассистентов, чатов службы поддержки и т.п. [Посмотреть правила](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_22_Annoyances_Widgets/filter.txt)
- Фильтр других раздражителей — блокирует элементы на веб-страницах, не включённые в популярные категории раздражителей. [Посмотреть правила](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_21_Annoyances_Other/filter.txt)**

<details>

![mor](https://user-images.githubusercontent.com/34476664/182573148-811f300d-1371-4180-bdb1-dcfa51768755.jpg)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
В [статье](https://adguard.com/ru/blog/new-annoyance-filters.html) можно почитать о новых фильтрах.

> Нужны они мне или достаточно Фильтра раздражителей?

Если достаточно фильтра раздражителей, то включать новые не нужно.

**Comment by Spok1** [comment]
НЕ, ты скажи прямо, они дополняют основную подписку с раздражителями или в ней они присутствуют, просто разбиты на части?

**Comment by zloyden** [comment]
Фильтр раздражителей остался прежним в части правил, но структура поменялась. Теперь он собирается из новых фильтров.
В статье есть ссылка про эти изменения https://github.com/AdguardTeam/AdguardFilters/tree/master/AnnoyancesFilter.

**Comment by Spok1** [comment]
Я видел, однако мне как-то не особо хочется просматривать куча файлов текстовых,чтобы различия найти! Просто скажи,мне нужно их активировать или же нет?

**Comment by zloyden** [comment]
> Если достаточно фильтра раздражителей, то включать новые не нужно.

[Все так и есть:)](https://github.com/AdguardTeam/AdguardFilters/issues/126129#issuecomment-1203714331)

> мне нужно их активировать или же нет?

Только в случае гибкой блокировки без фильтра раздражителей, например, куки уведомлений.

**Comment by Spok1** [comment]
> Только в случае гибкой блокировки без фильтра раздражителей, например, куки уведомлений.

Фильтра раздражителей же уведомления об использовании куки блокирует,разве нет?

**Comment by Spok1** [comment]
> Только в случае гибкой блокировки без фильтра раздражителей, например, куки уведомлений.

Фильтр раздражителей же уведомления об использовании куки блокирует,разве нет?

**Comment by zloyden** [comment]
Блокирует, я описал лишь частичный случай применения нового фильтра. В статье информация есть.

**Comment by Spok1** [comment]
Ладно, я понял,  Фильтр раздражителей разбили на подкатегории. Это я и хотел услышать! 
PS у вас с Алексом проблемы с формулировкой! Что можно сказать за одно предложение, у вас уходит на 10!

**Comment by zloyden** [comment]
> Ладно, я понял, Фильтр раздражителей разбили на подкатегории. Это я и хотел услышать!

https://github.com/AdguardTeam/AdguardFilters/issues/126129#issuecomment-1203714331 об этом и было [сказано здесь](https://github.com/AdguardTeam/AdguardFilters/issues/126129#issuecomment-1203714331), рад что теперь нет вопросов. Статью все же рекомендую почитать (цитата оттуда ниже):
> Теперь во всех приложениях и расширениях блокировщика AdGuard помимо Фильтра раздражителей появятся ещё пять — **его составные части**: Фильтр cookie-уведомлений, Фильтр всплывающих окон, Фильтр баннеров мобильных приложений и другие.
