### ISSUE TITLE
Problems on apkmirror site?

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#12611]
@superlex commented on [Sat Mar 03 2018](https://github.com/AdguardTeam/ContentBlocker/issues/107)

Hi!
Maybe are there problem on apkmirror.com?
I see a lot of blank spaces.

### Steps to reproduce:
1. open Samsung Internet browser
2. go to apkmirror.com

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| 2.1.2 |
| Browser in use:| Samsung Internet 6.4.10.5 |
| Filters enabled in Adguard:| default list - UsefulAdsFilter + AnnoyancesFilter |
| Operating system and version:| LineageOS 14.1 |
| Rooted or not? | No |

---

@ameshkov commented on [Sat Mar 03 2018](https://github.com/AdguardTeam/ContentBlocker/issues/107#issuecomment-370174811)

@Alex-302 could you please take a look?

**Comment by Alex-302** [comment]
they are must be hidden by
```
apkmirror.com##.gooWidget
##.google-ad-square-sidebar
```
I don't know why they are not applied.

**Comment by superlex** [comment]
On Yandex browser it works well, could be related at Samsung Internet?

**Comment by ameshkov** [comment]
> On Yandex browser it works well, could be related to Samsung Internet?

Yes, it might be an issue with Samsung issue indeed.

@Alex-302 could you please check it with Samsung Internet and just a user filter?

**Comment by ameshkov** [comment]
Most likely this is a bug of Samsung, we'll find out more in the CB repo:
https://github.com/AdguardTeam/ContentBlocker/issues/107
