### ISSUE TITLE
RyobiTools.eu - Broken functions (AdGuard Annoyances filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#126737]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.16.4.30 (XUL)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other(specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.ryobitools.eu/

### What filters do you have enabled?

AdGuard Annoyances filter

### Affected site:
`https://www.ryobitools.eu/` (..and all sub domains)

### Issue:
Broken functions, because of a blocked cookie consent which needs to be accepted!

### Example:
`https://uk.ryobitools.eu/`

Move your mouse cursor over the "SHOP BY" button, in the navigation header..
* Expected result: A menu should appear.
* Actual result: Nothing happens!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **AdGuard Annoyances filter**

### Problem rules:
`###onetrust-consent-sdk`
`||cookielaw.org^$third-party`

### Possible fix:
`ryobitools.eu#@##onetrust-consent-sdk`
`@@||cdn.cookielaw.org/scripttemplates/otSDKStub.js$domain=ryobitools.eu`

### Additional fix:
`||ryobitools.eu^*/NewsletterPopup-*$script` (Newsletter popup)

### Other problem filters:
* **Easylist Cookie List** / **Fanboy's Annoyance List** https://github.com/easylist/easylist/issues/12871/
`###onetrust-banner-sdk`
`###onetrust-consent-sdk`

* **I don't care about cookies** _(NOTIFIED)_
`###onetrust-consent-sdk`

--

### System info:
* OS/version: Windows 10 Pro (x64)
* Browser/version: Pale Moon v31.2.0.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.30 (XUL)

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Also added a JS rule for cookies.
