### ISSUE TITLE
thebeliever.net

### ISSUE THREAD

**Issue by wavygecko** [AdguardTeam/AdguardFilters#126790]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

ubo 1.43

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.thebeliever.net/las-marthas/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1. `thebeliever.net##.subscriber-popup-container` newsletter popup (scroll down page a bit)

2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/110956608/183915454-0ce0abc9-f391-4964-a715-e6d000223eaa.png">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by wavygecko** [comment]
also appears on `https://culture.org`

**Comment by wavygecko** [comment]
@Sergey-Lyapin ty! can you update issue labels? :)

**Comment by Sergey-Lyapin** [comment]
@wavygecko done =)
