### ISSUE TITLE
tv.kakao.com

### ISSUE THREAD

**Issue by Githubmaniak** [AdguardTeam/AdguardFilters#126793]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.0(954)

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://tv.kakao.com/m/channel/3990670/cliplink/430058191

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, EasyList, List-KR, YousList

### Add your comment and screenshots

1. <comment>
kakao tv is detecting AdGuard.  It seems that kakao tv's advertisement script has been updated. Videos of Kakao TV attached to other web pages are blocked in the same way.
2. Screenshots
<details><summary>Screenshot 1:</summary>

![02F0AD95-2BBA-4544-BC5A-44AF7A4B56CF](https://user-images.githubusercontent.com/103377449/183920425-57829053-3df6-4456-8a63-81d213a970fa.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
Did you enable advanced protection of AdGuard for iOS?

**Comment by piquark6046** [comment]
Can you add `@@||videoads.kakao.com^` into your DNS user rules?

**Comment by Githubmaniak** [comment]
@piquark6046 For some reason, I couldn't activate Advanced Protected Mode.

**Comment by piquark6046** [comment]
Confirmed.

**Comment by piquark6046** [comment]
@Githubmaniak Please check it out.

**Comment by Githubmaniak** [comment]
@piquark6046 I'm using the free version, so I can't use that setting. Is there any other way other than this?

**Comment by piquark6046** [comment]
@Githubmaniak Please update your filters.

**Comment by Githubmaniak** [comment]
@piquark6046 After the update, the video is not displayed, only a message disallowing ad blocking is displayed.
![6151BE7A-5634-4EAC-8E9A-5703313E8CBB](https://user-images.githubusercontent.com/103377449/184367110-9c8b017d-1450-4925-b115-d26c93e07485.png)

**Comment by piquark6046** [comment]
@Githubmaniak 
Please tell me your subscribed filters.

**Comment by Githubmaniak** [comment]
@piquark6046 It uses the same filter as the first comment.

**Comment by piquark6046** [comment]
I cannot reproduce it without AdGuard for iOS [^1]
[^1]: Because I don't have any Apple device.

@seia-soto Can you verify this?

**Comment by Githubmaniak** [comment]
@piquark6046 The same happens even after resetting all settings.

**Comment by piquark6046** [comment]
I don't have any Apple device.

**Comment by Githubmaniak** [comment]
@piquark6046 Once all the rules are disabled and re-enabled, the video can be played normally.  Thank you so much for the help.

**Comment by piquark6046** [comment]
???????????

**Comment by Githubmaniak** [comment]
@piquark6046 When I tried disabling the rule and re-enabling it again, the video on Kakao TV was displayed and played normally.  It seems like it was a temporary error.
