### ISSUE TITLE
Блокируется пролистывание страницы

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardFilters#126717]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

v3.6.8 (46)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.bbc.com/news/world-us-canada-61084161

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Experimental filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals

### Add your comment and screenshots

<details><summary>Screenshot 1:</summary>

![chrome_screenshot_1660058687176](https://user-images.githubusercontent.com/34476664/183692984-95acb57a-b49f-4aea-8d26-efa881e62414.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Spok1** [comment]
@zloyden

**Comment by Spok1** [comment]
@zloyden,@jellizaveta

**Comment by zloyden** [comment]
Не повторяется с US IP.

**Comment by Spok1** [comment]
@zloyden, а  с украинского?  Подключи команду!
