### ISSUE TITLE
archive.vanityfair.com

### ISSUE THREAD

**Issue by wavygecko** [AdguardTeam/AdguardFilters#126851]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

ubo 1.43

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://archive.vanityfair.com/article/2022/7/1/good-vibrations

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1. On pages that are subscriber-only, the magazine viewer popup does not work. In this case, the sign-in-to-account popup should still display (but remain removed on free articles where the magazine viewer popup *does* work). To do this, we can adjust the existing AdGuard Annoyance filter from
  `archive.vanityfair.com#$#.bnd_subscribe { display: none !important; }`
  to
  `archive.vanityfair.com#$#body.page_shared .bnd_subscribe { display: none !important; }`.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/110956608/184028775-32ee50d4-f1ec-41e8-84da-47ebf3797933.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Just annoying popup is blocked.

**Comment by wavygecko** [comment]
On non-free articles, clicking the viewer does nothing which makes it seem like the page is broken because nothing happens. I think it makes sense to only hide for pages where the viewer works.
