### ISSUE TITLE
Android's Spotify Misbehaves

### ISSUE THREAD

**Issue by PedroHLC** [AdguardTeam/AdguardFilters#126935]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

adguard-dns.io

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.spotify.music

### What filters do you have enabled?

AdGuard DNS filter

##### To reproduce:

1. With my DNS set to `c6-----.d.adguard-dns.com` in Android's settings.

2. Open Spotify on the phone while playing songs on another device, it does not show the current playing song or controls for changing it. It does not download any song.

3. Put something to play on the phone itself, then I don't see any new scrobbles on https://www.last.fm/user/PeHLC (even after songs ends).

##### To temporarily fix it:

4. Changes my DNS to `one.one.one.one` in Android's settings.

5. Restarts Spotify on phone.

6. Songs start to download, songs playing in other machines suddenly appears, past scrobbles are submitted to Last.fm and can be seen in my profile.

##### Other details:

1. I have a cookie in adguard-dns.io that says `user:"32362--"`

2. Searching for Spotify blocked queries in statistics shows nothing in the past 7 days: https://adguard-dns.io/en/dashboard/statistics/query?limit=20&statuses%5B0%5D=REQUEST_BLOCKED&statuses%5B1%5D=RESPONSE_BLOCKED&companies%5B0%5D=spotify&retention=DAYS_7

3. Spotify version is 8.7.54.403

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please test without any rules and filters.
