### ISSUE TITLE
https://www.instagram.com/p/CglXJMUqyFH/

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardFilters#126925]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

v3.6.8 (46)

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.instagram.com/p/CglXJMUqyFH/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter

### Add your comment and screenshots

9
![chrome_screenshot_1660229026405](https://user-images.githubusercontent.com/34476664/184167392-e95dd72b-57f6-4eae-a889-f61a9909f4ee.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Morku** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/123556#issuecomment-1188722616

**Comment by Spok1** [comment]
@Alex-302 , я так понял,что что-то сломается при скрытии?
