### ISSUE TITLE
[iOS] hdrezka.me

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1270]
http://hdrezka.me/series/comedy/2040-kremnievaya-dolina-2016.html
http://imgur.com/68ek910
AVJ-533-96540

**Comment by Alex-302** [comment]
check for updates. It is clean on my end.

**Comment by Alex-302** [comment]
it is clean on iPad

**Comment by Bohdan-SUP** [comment]
http://hdrezka.me/films/foreign/4176-kolco-nibelungov.html
http://prntscr.com/b9f98c

**Comment by Alex-302** [comment]
Повтор.
Для iOS решение только здесь
http://hdrezka.me/noadvert/
ответ - "НЕТ"
