### ISSUE TITLE
online.sberbank.ru

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#12702]
***Description***:
* **Current behaviour**: 

User reports that all scripts present on site are blocked, and whitelisting doesn't help. Cannot login.

* **Expected behaviour**: 

Should work fine.

***Steps to reproduce the problem***:

1. Attempt to log in with AdGuard enabled.

***System configuration***

**Web request logs:**
available under 1780325

**Filters:**

"English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter", "Simplified domain names filter", "ABPVN List", "Adblock-Persian list", "Anti-Adblock Killer | Reek"

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 7.0
Browser:                               | Chrome
AdGuard version:                       | 2.10.176
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter", "Simplified domain names filter", "ABPVN List", "Adblock-Persian list", "Anti-Adblock Killer | Reek"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default mode)
DNS:                           | Google Public DNS (8.8.8.8 / 8.8.4.4)
Helpdesk ID (if exists):               | 1780325

**Comment by Alex-302** [comment]
sberbank.ru is in HTTPS exclusions.
@zebrum @vozersky @altokarev  can you confirm it?

**Comment by Alex-302** [comment]
As I see, it is caused by Persian filter. User can disable it, if it is not used.

**Comment by vozersky** [comment]
not an SB user, soz
but yeah, I suggest to start with disabling 3-rd party filters

**Comment by akmLaVx** [comment]
Fixed by disabling Persian filter.
