### ISSUE TITLE
Ferplast.com - Blocked cookies = no product images

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#12713]
### Affected website:
`Ferplast.com`
Example:
`https://www.ferplast.com/int/cat-supplies.html`

### Issue:
Product images are unable to load as a result of blocked cookies.

### Problem filter:
* Adguard's Annoyance List

### Problem rule:
`/cookiepolicy/*`

### Possible fix:
`@@ferplast.com/js/filoblu/cookiepolicy/jquery.cookie.js`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.8.0 (x64)
- Adblock Extension/version: uBlock Origin v1.15.10

**Comment by AdamWr** [comment]
Thank you, added:
`@@||ferplast.com/js/filoblu/cookiepolicy/jquery.cookie.js`
Update will be available in 2-3 hours.
