### ISSUE TITLE
Incorrect filtering on m.bilibili.com

### ISSUE THREAD

**Issue by JasonHK** [AdguardTeam/AdguardFilters#127192]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.43.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

https://m.bilibili.com/dynamic/686058310439272488

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Japanese filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, EasyList

### Add your comment and screenshots

1. The `m.bilibili.com##.launch-app-btn` rule cause normal content to be filtered.

2. Screenshots
<details><summary>Screenshot 1 (Expected):</summary>

![畫面擷取於 2022-08-15 17 47 11](https://user-images.githubusercontent.com/4410086/184614254-ccd8b2e9-2e26-4bbe-a340-82c71181a683.png)

</details>

<details><summary>Screenshot 2 (Current):</summary>

![畫面擷取於 2022-08-15 17 48 01](https://user-images.githubusercontent.com/4410086/184614311-d963f8a9-6ccf-4ed2-b5d4-db33dc1c48b5.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Yuki2718** [comment]
@ryanbr

**Comment by JasonHK** [comment]
@Yuki2718 Your PR didn't fix the issue, I specifically said it's caused by the rule `m.bilibili.com##.launch-app-btn`. For some reason the site decided to put this class to the main content of a post in some pages.

**Comment by Yuki2718** [comment]
Was mistake, see https://github.com/AdguardTeam/AdguardFilters/commit/fb87daf539f8421705c92211034de0a93eb4a59b

**Comment by Yuki2718** [comment]
And it seems needing a bit more adjust, some buttons are missed.
