### ISSUE TITLE
lenta.ru - Adguard breaks the site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1272]
http://lenta.ru/photo/2016/01/11/village/
http://prntscr.com/9p2q5u

"Дополнение (броузер firefox)
Адрес: http://lib.rl0.ru/adfox/7/adfox.custom.min.js
Время: 01/11/2016 21:49:27
Статус: Запрос заблокирован
Детали запроса:

Запрос отправлен со страницы:
http://lenta.ru/photo/2016/01/11/village/
Запрос заблокирован следующим правилом фильтрации:
/adfox.
"

AET-811-12884

**Comment by Alex-302** [comment]
Пока для пользовательского
```
@@||lib.rl0.ru/adfox/*/adfox.custom.min.js
```
