### ISSUE TITLE
Вопрос.

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardFilters#127242]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

v3.6.8 (46)

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://news.google.com/foryou?hl=ru&gl=UA&ceid=UA%3Aru

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Hide Referrer from third-parties (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests

### Add your comment and screenshots

Мне кажется или этот трекер нужно заблокировать?

<details><summary>Screenshot:</summary>

![Screenshot_20220816-004035](https://user-images.githubusercontent.com/34476664/184723630-c7844149-2bca-4e35-8079-c2cd0812538f.jpg)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Spok1** [comment]
@zloyden

**Comment by Alex-302** [comment]
Не нужно. По крайней мере не в DNS.
