### ISSUE TITLE
Unable to reach Netgear router via NETGEAR Mobile app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#12735]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behavior**: It won't let you connect to the router unless you disable AdGuard PRO or the DNS filtering. The app: https://itunes.apple.com/vn/app/netgear-mobile/id457698895?mt=8

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/37082770-0f307f9e-21f6-11e8-92d5-1ea0c0bafc0b.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/37082776-1924d7fc-21f6-11e8-8939-00e76d735a0f.png)

</details><br/>

***System configuration***

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English Filter" Version=2.0.2.14 Enabled=YES
ID=3 Name="Spyware filter" Version=2.0.0.66 Enabled=YES
ID=4 Name="Social media filter" Version=2.0.0.85 Enabled=YES
ID=14 Name="Annoyances filter" Version=2.0.1.16 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=2.0.0.46 Enabled=YES
ID=12 Name="Safari filter" Version=2.0.0.38 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=2.0.0.44 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=2.0.2.42 Enabled=YES
ID=214 Name="ABPVN List" Version=2.0.0.32 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | iOS
Operating system version (Android/iOS) | iOS 11.2.6
Browser:                               | n/a
AdGuard version:                       | 2.0.0.140
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | Default, DNSCrypt - null
Helpdesk ID (if exists):               | 1542905, contains DNS log files with timestamps

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by bigdargon** [comment]
Thanks!

**Comment by Alex-302** [comment]
Please clear DNS log, reproduce the issue and copy blocked domain names.

**Comment by bigdargon** [comment]
@Alex-302 I have cleaned up the log and emailed the support with the attached image. I found no domain names blocked, including disabling the subscription.

**Comment by Alex-302** [comment]
ok, please record full log(`record everything`)

**Comment by bigdargon** [comment]
@Alex-302 Adguard pro for ios does not have this feature.
![5cf72e1c-0761-4e23-8d50-e900473383c5](https://user-images.githubusercontent.com/10969626/37435085-8255aec6-2814-11e8-9f30-05c6f0086fdf.png)

**Comment by Alex-302** [comment]
Sorry. Please try:
* disable all filters and check again;
* disable/change DNS and check. If the app works in this case, open DNS log, clear it and reproduce the issue. Then open the log, swipe it down to reftesh and make screenshot of blocked domains.

**Comment by bigdargon** [comment]
@Alex-302 I tried with the other DNS but still not logged in router, maybe this is the application bug of iOS. And I tried the app on Android but access to the normal router.

**Comment by Alex-302** [comment]
> the app on Android

with custom DNS?

**Comment by bigdargon** [comment]
Yes! Adguard on Android work with any DNS

**Comment by Alex-302** [comment]
ok. Could you check with another DNS app?

**Comment by bigdargon** [comment]
- Weblock: adblock & proxy by FutureMind https://itunes.apple.com/vn/app/weblock-adblock-proxy/id558818638?mt=8 Working

- AdBlock by FutureMind https://itunes.apple.com/vn/app/adblock/id691121579?mt=8 Working

- Adblock Mobile — best Ad Blocker to block ads by Jennifer Hernandez https://itunes.apple.com/vn/app/adblock-mobile-best-ad-blocker-to-block-ads/id1121734569?mt=8 Not Working

**Comment by bigdargon** [comment]
![62b03202-e37c-4bf9-8734-a9471ad07ca3](https://user-images.githubusercontent.com/10969626/37567609-fcf2bca2-2afb-11e8-9338-5a329467abb3.jpeg)
![bca7a4f5-b6b3-43b7-a342-b850e06b2c6d](https://user-images.githubusercontent.com/10969626/37567610-fd4a6704-2afb-11e8-80d9-c46ff082a56e.jpeg)
![8d0a5b15-b483-42ca-825d-3c3e0812c848](https://user-images.githubusercontent.com/10969626/37567612-fda13160-2afb-11e8-912a-d6f19ce57e7d.png)
![a333f690-d092-492d-ae66-6e255715195f](https://user-images.githubusercontent.com/10969626/37567613-fdf51500-2afb-11e8-9154-257cdac7ba2a.png)
![66216fba-5f77-410b-8a48-b9da7b70f41d](https://user-images.githubusercontent.com/10969626/37567614-fe564190-2afb-11e8-99ca-20c9f3866a1b.jpeg)
![897d0e06-b24e-4692-b659-703743d5abde](https://user-images.githubusercontent.com/10969626/37567615-fec4d330-2afb-11e8-9f58-d551fa65a902.jpeg)

**Comment by Alex-302** [comment]
Try to use your router IP address to login instead of using the routerlogin.com or routerlogin.net.
I recommend to use IP instead of domain name.

**Comment by bigdargon** [comment]
If I use IP to log in using safari then normal, but if using the application then the application uses routerlogin.net or routerlogin.com.

If I use the android application (which uses AdGuard and OpenDNS VPNs) then log in normally, while the application on ios does not log into the router.

Seems like this bug in the netgear app, I will try netgear contact for fixing!

**Comment by Alex-302** [comment]
I think we can't fix it, because user can change router's IP.

**Comment by Alex-302** [comment]
It works only when device uses router's DNS.
