### ISSUE TITLE
bedfordshire-news.co.uk - some links are not responding 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1274]
![image](https://cloud.githubusercontent.com/assets/15856304/12259012/5efbcb1e-b91b-11e5-9137-2af90639a6e4.png)

When you click on Sport, What's on etc, nothing's going on. Disabling Adguard solves the issue.

HTX-440-59674

**Comment by Alex-302** [comment]
added to Spyware
```
@@||bedfordshire-news.co.uk^$content
@@||b.scorecardresearch.com/r?$domain=bedfordshire-news.co.uk
```

**Comment by Alex-302** [comment]
@@||b.scorecardresearch.com/r?$domain=bedfordshire-news.co.uk
@@||bedfordshire-news.co.uk^$content
added to Spyware
