### ISSUE TITLE
Вопрос по поводу подписок

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardFilters#127422]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

v3.6.8 (46)

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

Example.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

Если у меня включена фильтрация dns с подпиской на фильтры,то стоит мне в подписках дополнительно активировать упрощённый фильтр dns,он же фильтр dns в разделе «другое»?

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Особого смысла нет.
