### ISSUE TITLE
error report 错误报告 （Chinese）

### ISSUE THREAD

**Issue by paroc108** [AdguardTeam/AdguardFilters#127564]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.0.204

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.iqiyi.com/v_adyc3o9qpg.html

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Japanese filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies

### Add your comment and screenshots

在打开【AdGuard 恼人广告过滤器（版本： 2.1.30.22 ）】的情况下，爱奇艺网站首页 （https://www.iqiyi.com/） 右侧的推荐视频列表无法根据鼠标的移动响应切换变大。
![爱奇艺首页广告拦截](https://user-images.githubusercontent.com/96353174/185556563-ad36b432-49c0-4301-8dd4-c696c0f8affc.jpg)

如果关闭【AdGuard 恼人广告过滤器】，则网站里的视频的开头广告无法成功拦截（https://www.iqiyi.com/v_adyc3o9qpg.html）
![爱奇艺视频广告](https://user-images.githubusercontent.com/96353174/185556626-bcf0943b-88a1-4ad2-9146-ca388a0e3ad8.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by hacamer** [comment]
使用英文报告问题会更好

**Comment by Alex-302** [comment]
Can't check outside China.
