### ISSUE TITLE
[iOS] www.idownloadblog.com - blank space left after blocking a banner

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1275]
![image](https://cloud.githubusercontent.com/assets/15856304/12259101/edbe9070-b91b-11e5-9018-f716a94d6932.png)

OIX-609-18996

**Comment by Alex-302** [comment]
added to mobile filter
idownloadblog.com##.wptouch-custom-ad

**Comment by Bohdan-SUP** [comment]
Please check again:
![image1](https://cloud.githubusercontent.com/assets/14153331/18433377/de88d842-78ef-11e6-952c-94c21eac8bb1.png)
![image2](https://cloud.githubusercontent.com/assets/14153331/18433379/df6b25d0-78ef-11e6-89ec-86e78e168f6f.png)

**Comment by Alex-302** [comment]
My rule still works.

**Comment by evgeniy-ADG** [comment]
http://www.idownloadblog.com/2016/10/05/apple-issues-a-statement-regarding-sapphire-protection-on-iphone-7-camera-lens/

At the bottom of the page there's a placeholder, please check:
<details>
![image3](https://cloud.githubusercontent.com/assets/15856304/19182223/c7f56e26-8c7a-11e6-8f52-7d9ae7fec668.png)

Application version: 1.0.8.54
Application lifetime: 2016-09-14 01:55:35 +0000

Device: iPhone
Platform: iPhone OS
OS: 10.0.2
ID: BF8A3724-A807-4FCC-BF58-44E6F5D807AA

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.51 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.94 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.33 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.44 Enabled=YES

**Comment by Alex-302** [comment]
Added to Mobile filter
```
idownloadblog.com#@#.header-ad
idownloadblog.com##.wptouch-custom-ad
idownloadblog.com###iDB_Mobile_Below_Content
```
