### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by Michael1297** [AdguardTeam/AdguardFilters#127618]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.10.2

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.youtube.com/c/iXBTgames/about

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter

### Add your comment and screenshots

из-за фильтра счетчиков и систем аналитики не открываются ссылки на сторонние сайты

<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/38764610/185666013-450b3844-aa81-4f0c-9e67-8ed9396bd0aa.png)

</details>

<details><summary>Screenshot 2:</summary>

![image](https://user-images.githubusercontent.com/38764610/185666228-c7119322-d981-4425-9892-8d9591f4190f.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Michael1297** [comment]
похоже что проблему вызывает правило `||youtube.com^$cookie=VISITOR_INFO1_LIVE`

**Comment by BlazDT** [comment]
`@@||youtube.com^$cookie=VISITOR_INFO1_LIVE`

@AdamWr I checked the linked google's cookie policy and I am unsure if we should unblock.

**Comment by AdamWr** [comment]
Sometimes I see similar message with AdGuard disabled, so I'm not sure if it's related to mentioned rule.

**Comment by Alex-302** [comment]
Не повторяется. Фильтры свежие?

**Comment by Michael1297** [comment]
сейчас работает нормально
