### ISSUE TITLE
wolte and  vowifi not work when adguard active

### ISSUE THREAD

**Issue by elween07** [AdguardTeam/AdguardFilters#127655]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.9

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

God know

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

1. <comment>

I use Chunghwa Telecom and Asia Pacific Telecom both of then vowifi not work and sometome event vowifi not work when adguard active, please check that, if need any log please let me know how to get that. my phone is asus zenfone9.  

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #4223](https://github.com/AdguardTeam/AdguardForAndroid/issues/4223) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
@elween07 Hi. Moved your question to https://github.com/AdguardTeam/AdguardForAndroid/issues/4223 Please write in new issue.
