### ISSUE TITLE
[iOS] lifenews.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1276]
![image](https://cloud.githubusercontent.com/assets/15856304/12259727/51ac546a-b920-11e5-897a-db07a856d83c.png)
![image](https://cloud.githubusercontent.com/assets/15856304/12291883/6a839f3e-b9f2-11e5-84cf-aa20532ad2c8.png)

GGM-111-94241
YUZ-837-21103

**Comment by Alex-302** [comment]
не повторяется

**Comment by Alex-302** [comment]
на айпаде тоже чисто
