### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by jmjou** [AdguardTeam/AdguardFilters#127889]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.google.com.tr/intl/tr/ads/publisher/partners/success-stories/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyList, EasyPrivacy, uBO filters

### Add your comment and screenshots

`https://www.google.com.tr/intl/tr/ads/publisher/partners/success-stories/`

<details><summary>Screenshot 1:</summary>

![resim](https://user-images.githubusercontent.com/110184059/186084390-6c7e4edb-5dc4-42a1-b2e3-3c39b834e428.png)

</details>

<details><summary>Screenshot 2:</summary>

![resim](https://user-images.githubusercontent.com/110184059/186084432-7d177876-e5c6-492c-90cc-2fdb25d0ab90.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
