### ISSUE TITLE
zdbb.net

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#1278]
Email links to articles in ExtremeTech.com do not work.

Example link:

http://mailing.enews.extremetech.com/t/1540578/1283851/6425475/66/?e5e2987d=MTU0MDU3OA==&e5e2987d=MTU0MDU3OA==&c73c8e04=ZXh0cmVtZXRlY2g=&4f415564=MTI4Mzg1MQ==&x=0c88fbfb

Whitelisting 'zdbb.net' solves the problem.

QGH-633-17921

**Comment by Alex-302** [comment]
send him these rules
```
@@||emailapi.zdbb.net/subscriptions/$domain=extremetech.com
@@||zdbb.net/*?member_id=$domain=extremetech.com
```

**Comment by Alex-302** [comment]
Any news? I need his reply.

**Comment by evgeniy-ADG** [comment]
Hello,

Adding the 2 rules below to my user filter (and deleting white list entry 
'zdbb.net') yielded the original behavior which means the web page stalled 
and did not load.

Deleting the user rules and restoring white list entry 'zdbb.net' allows 
the page to load and has no obvious side effects. This seems easier and 
more intuitive than the complex user rules that were proposed.

Thanks for your continued attention to this matter.

Regards,
Dave B.

**Comment by evgeniy-ADG** [comment]
@Alex-302 the problem's still there

> The email link provided in the original ticket resolves to:
> 
> www.pcmag.com/article2/0,2817,2498305,00.asp?mailing_id=1554518&mailing=SecurityWatch&mailingID=42EF9D3FA2D058DCF300139BE74AF63A
> 
> Observing the execution mailing.enews.pcmag.com first resolves to zdbb.net
> before going to www.pcmag.com. Whitelisting zdbb.net does not help (did in
> the past); resolution still stalls.
> 
> Curious why the email link will not resolve for you. Just tried it again,
> works fine. Might be a regional thing; you may have to use a US or North
> American proxy.

**Comment by Alex-302** [comment]
I need screenshots of all buttons, which he pressed.

**Comment by evgeniy-ADG** [comment]
@Alex-302 it looks like he won't send us any screenshots, please have a look on his reply (AWE-215-50280). He added some description, maybe it'll help...

**Comment by Alex-302** [comment]
перешлите ему это правило
@@||zdbb.net/r/http://www.pcmag.com
http лога случайно нет?
Желательно бы получить письмо с той ссылкой, я подписался, но ничего не приходит.

**Comment by evgeniy-ADG** [comment]
@Alex-302 

> Hello - the suggested rule did not help. This could have been confirmed at
> your end by clicking (test with) the link supplied in my original ticket.
> Pretty frustrating from a customer perspective.
> 
> What does work is disabling the mobile filter. However, that permits
> undesirable ads on other sites. I have no problem with the Adguard browser
> extension; everything renders perfectly.
> 
> The problem lies with the mobile filter (or rules used within it) on
> Android.
> 
> It is becoming increasingly apparent the support resources at AdGuard can
> not properly diagnose the situation. A variation of the proposed rule was
> presented and rejected in a previous ticket (#QGH-633-17921).
> 
> I understand you may not be able to write rules that block every ad but no
> rule should completely block access to a site unless the site itself is
> malicious. Whatever is triggering the block to Ziff Davis (legitimate)
> sites in the mobile filter should be moved to the experimental filter.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
от него http лог есть? Письмо рассылки переслать отказывается?
Даже не знаю как поправить не имея возможности повторить. Подписался внизу сайта несколько раз - ни одного письма не пришло.

**Comment by Bohdan-SUP** [comment]
HTTPS log - AWE-215-50280
Will ask to forward email.

**Comment by Alex-302** [comment]
Вижу один заблокированный запрос:
```
11:24:54.651 [pool-2-thread-126] DEBUG com.adguard.android.FilteringLog - TCP id0415 GET ads=1 "http://zdbb.net/r/?http%3a%2f%2fwww.pcmag.com%2farticle2%2f0%2c2630%2c2498784%2c00.asp%3fmailing_id%3d1560387%26mailing%3dDailyNews%26mailingID%3d48013C7CD189D1628FB2B1DF3D30481C&mailing_id60387&list٩lynews&member_id99719&engine_id=1&mailing٩lyNews" 0 -1 5ms "null" "Mozilla/5.0 (Linux; Android 4.4.4; Kindle Fire HDX 7 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36 OPR/34.0.2044.98679"
```
Такое правило поможет
```
@@||zdbb.net/r/*pcmag.com*mailing_id
```
Добавил его в фильтр.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
похоже не поможет исключение. Мне наконец пришла их рассылка, и кликнув по Sponsored открывается новая вкладка
