### ISSUE TITLE
[iOS] avito.ru - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1280]
AdGuard для iOS блокирует частные объявления на avito.ru
Здравствуйте! Давно обратил внимание, но только что дошли руки сообщить об ошибке, которая уже на протяжении длительного времени наблюдается на avito.ru с включённым AdGuard для Safari. Он блокирует все частные объявления на страницах выдачи. Прошу устранить это ложно-положительное срабатывание!
![image](https://cloud.githubusercontent.com/assets/15856304/12261368/585eac00-b929-11e5-8d31-bf0850823918.png)

TTL-922-14419

**Comment by Alex-302** [comment]
Не повторяется/

**Comment by Alex-302** [comment]
на айпаде тоже нормально/
пусть попробует повыключать фильтры

**Comment by Bohdan-SUP** [comment]
Выключил лишние фильтры - проблема все еще актуальна.
Логи тут - TTL-922-14419

**Comment by onega** [comment]
У меня на iPad установлены 2 приложения для блокировки рекламы: AdGuard и Антиреклама. В обоих из них домен avito.ru добавлен (для пробы) в белый список. Тем не менее, реклама продолжает по-прежнему блокироваться, в том числе и блок частных объявлений. Если нажимаю на кнопку "перезагрузить без блокирования контента", реклама не блокируется вообще. Со вторым утверждением все очевидно, но как объяснить первое?

**Comment by Alex-302** [comment]
Пользуйтись чем-то одним, иначе не возможно определить виновника. Т.к. больше жалоб нет(только на форуме, но и там два блокировщика), то предполагаю, что проблема с Антирекламой.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
по иосным ложным срабатываниям - сразу уточняйте количество блокировщиков.
