### ISSUE TITLE
issue with adguard annoyances filter in flipkart.com

### ISSUE THREAD

**Issue by venkat2305** [AdguardTeam/AdguardFilters#128072]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

no

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.flipkart.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, EasyList, EasyPrivacy, Fanboy's Annoyances

### Add your comment and screenshots

1. some parts of website are missing

2. Screenshots
without adguard annoyances filter
![image](https://user-images.githubusercontent.com/55329452/186652454-860a7341-0ff9-42be-9087-d4a5c9be1a84.png)

with adguard annoyances filter
![image](https://user-images.githubusercontent.com/55329452/186652557-6fccf356-2d3a-4ae3-8b4c-9998a3cf4910.png)

![image](https://user-images.githubusercontent.com/55329452/186652783-5f365008-0e44-45a3-810b-7d42d88d0c3b.png)

### Privacy

- [X] I agree to follow this condition

**Comment by venkat2305** [comment]
im currently turning this filter of. please let me know if you guys fix this issue.
thanks

**Comment by BlazDT** [comment]
Only seeing ads blocked when I compare your screenshots.

**Comment by jellizaveta** [comment]
The gaps in each column are blocked promotional items. Due to the design of the site assumes line-by-line filling, these gaps cannot be filled with products from the next line. Therefore, these leftovers cannot be fixed because they are part of the site layout. Also, you can disable the `AdGuard Other Annoyances filter` and the gaps will be filled with site suggestions.
