### ISSUE TITLE
thegioididong.com

### ISSUE THREAD

**Issue by trmdi** [AdguardTeam/AdguardFilters#128113]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.9

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other(specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

thegioididong.com

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Protect from DPI

### Add your comment and screenshots

I find that thegioididong.com is already in the list:

https://github.com/AdguardTeam/AdguardFilters/blob/425669ced45729794a5d75e2554b959fb0a7bf2e/EnglishFilter/sections/allowlist_stealth.txt#L26

but it's not in: https://filters.adtidy.org/android/filters/2_optimized.txt

### Privacy

- [X] I agree to follow this condition

**Comment by trmdi** [comment]
@Alex-302 
The same bug with https://www.dienmayxanh.com/

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/a67625ef7e8e7c426137ac16164aa215fd8fa7a7

**Comment by trmdi** [comment]
> [a67625e](https://github.com/AdguardTeam/AdguardFilters/commit/a67625ef7e8e7c426137ac16164aa215fd8fa7a7)

I mean the OPTIMIZED stuff is removing it. Please see Alex's commit.

**Comment by Alex-302** [comment]
ok
