### ISSUE TITLE
eclass.hufs.ac.kr

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#12810]
***Description***:
* **Current behaviour**: 

Domain returns an ERR_CONNECTION_REFUSED error when AdGuard is enabled.

<details><summary>Screenshot:</summary>

![screenshot_2018-03-07-02-27-00](https://user-images.githubusercontent.com/33634917/37153128-67861f3e-22e4-11e8-94a4-c47d47e8f0a0.png)

</details><br/>

* **Expected behaviour**: 

Domain shouldn't refuse connection.

***Steps to reproduce the problem***:

1. Enable the protection;
2. Go to eclass.hufs.ac.kr;
3. Domain will return an ERR_CONNECTION_REFUSED error.

***System configuration***

**Filters:**

"English filter", "Spyware filter", "Social media filter", "Mobile Ads filter", "List-KR"

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 6.0.1
Browser:                               | Samsung
AdGuard version:                       | 2.10.176
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Mobile Ads filter", "List-KR"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | Disabled
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 1778468

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by ameshkov** [comment]
Same issue with AG enabled
