### ISSUE TITLE
Cannot primary click on any links on canyon.com

### ISSUE THREAD

**Issue by nobelharvards** [AdguardTeam/AdguardFilters#128314]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

AdGuard Annoyances filter 2.1.31.24

### What type of problem have you encountered?

Website or app doesn't work properly, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://canyon.com

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

**To reproduce:**
1. Clear cache if previously visited canyon.com.
2. Browse canyon.com with AdGuard Annoyances filter enabled.
3. Try to click on any links with primary click (middle click to open new tab works fine).
4. Should not be able to navigate to any links.

**Workaround:**
1. Disable AdGuard Annoyances filter.
2. Browse canyon.com.
3. Should now be able to see a cookie dialog overlay.
4. Accept cookie dialog.
5. Re-enable AdGuard Annoyances filter.
6. Browse canyon.com.
7. Should now be able to navigate to links with primary click, regardless if AdGuard Annoyances filter is enabled or not.

There seems to be some leftover invisible overlay that does not allow links to be clicked with the primary mouse button if the cookie dialog has not been accepted.

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
