### ISSUE TITLE
valeriewai.com

### ISSUE THREAD

**Issue by wavygecko** [AdguardTeam/AdguardFilters#128467]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

ubo 1.44

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.valeriewai.com/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1. popup

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/110956608/187586631-95cccee2-49c6-44d9-9f40-dd21dc864048.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Too low traffic.

**Comment by wavygecko** [comment]
@Alex-302 I was thinking as generic filter (see https://www.weebly.com/app-center/promote-forms#)

**Comment by wavygecko** [comment]
fixed by https://github.com/AdguardTeam/AdguardFilters/commit/a5aea95ae9613ce36f21ddb3197704ddd5b0de91
