### ISSUE TITLE
[iOS] spiegel.de

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1284]
![image](https://cloud.githubusercontent.com/assets/15856304/12291288/069a8a6c-b9ef-11e5-95a1-e645202f3bc1.png)

when you activate the desktop version ("Zur WWW-Version" at the very top) you get this ad banner.
OTE-655-45196

**Comment by Alex-302** [comment]
This site is clean on my end.

**Comment by Alex-302** [comment]
on iPad it is clean too
