### ISSUE TITLE
Diagnostics Page

### ISSUE THREAD

**Issue by Lucascoco** [AdguardTeam/AdguardFilters#128541]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

v0.107.11

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome, other(specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

i run the Diagnostics page from vaultwarden

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard German filter, AdGuard URL Tracking filter, AdGuard DNS filter

### Add your comment and screenshots

![Image 321](https://user-images.githubusercontent.com/101245521/187724732-1a8de2be-9d17-4c2e-8602-c81fddeb15d5.png)

with adgard as dns Server i cant get server latest, when i take 1.1.1.1 as dns Server, it will go.
What is the problem. THX
D

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please write steps to reproduce.

**Comment by Lucascoco** [comment]
i have a container running vaultwarden.
When i click on the admin page diacnotics, the server have no contakt to the internet, when the dns server ist adgaurd hone.
wenn i set the google dns, i can connect the internet over the Diagnostics page.

**Comment by Alex-302** [comment]
@Lucascoco AdGuard Home? Which upstream DNS and filters?

**Comment by Lucascoco** [comment]
https://dns10.quad9.net/dns-query
1.1.1.1
1.0.0.1

![Image 327](https://user-images.githubusercontent.com/101245521/188796267-ea06fac7-444f-4663-aa6d-0b75c83935de.png)

**Comment by Alex-302** [comment]
It can be broken by any custom filter and foreign quad9 DNS. Check without third-party filters and with AdGuard non-filtered DNS.
