### ISSUE TITLE
[iOS] consequenceofsound.net

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1285]
![image](https://cloud.githubusercontent.com/assets/15856304/12293328/771bf40e-b9fb-11e5-858c-afaf9bdc4cc4.png)

![image](https://cloud.githubusercontent.com/assets/15856304/12293339/80a76df0-b9fb-11e5-855f-53735232ace4.png)

YHQ-726-53325

**Comment by Alex-302** [comment]
Where the ads?

**Comment by evgeniy-ADG** [comment]
Those
![image](https://cloud.githubusercontent.com/assets/15856304/12325340/3f704d98-bad2-11e5-8ea9-c711cdec8f0b.png)

**Comment by Alex-302** [comment]
I don't see this block. This is youк own screenshot?

**Comment by evgeniy-ADG** [comment]
No, it's from the customer, unfortunately, I have no iPhone for testing now.

**Comment by Alex-302** [comment]
Totally clean, with US VPN

**Comment by evgeniy-ADG** [comment]
So I'd ask him to update filters and to try to reproduce it again.
