### ISSUE TITLE
Make cookies_allowlist.txt separate from the AdGuard Annoyances filter in uBlock Origin

### ISSUE THREAD

**Issue by Aftersoftware** [AdguardTeam/AdguardFilters#128624]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Please stop merging https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/Cookies/sections/cookies_allowlist.txt with the AdGuard Annoyances filter used in uBlock Origin, because there is no way to disable those allow-lists. 

They just allow annoying popups appear that otherwise would not.

### Proposed solution

I would suggest separating them into 2 different lists, making the cookies_allowlists.txt filter optional.

**Comment by zloyden** [comment]
Well, some sites do not work properly due to cookie blocking and separate the `cookies_allowlist.txt` from the `AdGuard Annoyances` is not a good idea.
