### ISSUE TITLE
Removal request

### ISSUE THREAD

**Issue by pySilver** [AdguardTeam/AdguardFilters#12870]
https://github.com/AdguardTeam/AdguardFilters/blob/000759df7da8c5564c374d5a51792028ccb4c92d/EnglishFilter/sections/adservers.txt#L75

Hello,

Please remove our company website from this list. We are not ad serving platform and this domain is a corporate website, not a tracking domain.

Thank you.

**Comment by Alex-302** [comment]
@AdamWr do we need this rule?
https://github.com/AdguardTeam/AdguardFilters/commit/5869da566bd594dfaef875439c8d2abf9ac584f7

**Comment by AdamWr** [comment]
I added it, because I found this script on some websites - `http://widget.convertiser.com/convertext.js` and it's the same script like on converti.se - `http://converti.se/static/js/convertext.js`
https://publicwww.com/websites/widget.convertiser.com%2Fconvertext.js/
If I'm not wrong this script changes text to clickable links, so in my opinion it's some kind of ad.

**Comment by pySilver** [comment]
@AdamWr it's a *helper script for bloggers* that are working with our Publishers Network at Convertiser – so they don't need to generate tracking links every time they write a review for a specific product, example: http://www.macademiangirl.com/2017/10/francuski-szyk-czyli-stylizacje-fashion-weeku-paryzu.html

Screen: http://take.ms/wVMUA
Most importantly: It is not something that changes content of a page with irrelevant ads or anything like that. (It's not a in-text ads and it does not track user activity)

We've developed few helpers like this, as an example there is a tracking link generator in a form of chrome plugin: https://chrome.google.com/webstore/detail/convertiser-editor/dlfcemjcmnnpogmjnnafohammmpibmbi?hl=en

Beside this scripts - I didn't understand why our **company website** got listed, that domain does not serve any scripts.

**Comment by AdamWr** [comment]
Ok, I changed it to - `||widget.convertiser.com^$third-party`
