### ISSUE TITLE
baixartorrent.info

### ISSUE THREAD

**Issue by Raavizz** [AdguardTeam/AdguardFilters#12880]
`spa, por: Adguard Spanish/Portuguese`

[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**:  Huge ammount of ads

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![capture_001_09032018_174133](https://user-images.githubusercontent.com/37177644/37218644-5dc5cd9a-23c1-11e8-89c4-be1423ef8af4.png)
![capture_002_09032018_174138](https://user-images.githubusercontent.com/37177644/37218645-5e5fc116-23c1-11e8-8a9e-bdc7e7bde49f.png)

</details><br/>

* **Expected behaviour**: No ads

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![capture_003_09032018_174506](https://user-images.githubusercontent.com/37177644/37218735-a5f8092a-23c1-11e8-99d4-7627db16d055.png)

</details><br/>

***Steps to reproduce the problem***:

Visit http://baixartorrent.info/

***Sample cure***:

```
###text-5
||baixartorrent.info/wp-content/uploads/2016/09/a01b-1.gif
||baixartorrent.info/wp-content/uploads/2016/09/a02b-2.gif
||c1.staticflickr.com/9/8891/28354201992_3559c24d33_o.png
||inglesonlinedojerry.com.br/afiliados/banners/336_1.jpg
||renatoalves.com.br/images/banners/cem-250x250-0.jpg
||renatoalves.com.br/images/banners/cem-250x250-1.jpg
||www.voitto.com.br/img_curso.php/hotmart/formao-master-em-excel-2013-2-0/1-%20160%20x%20600.png
||www.voitto.com.br/img_curso.php/hotmart/formao-master-em-excel-2013-2-0/1-%20250%20x%20250.png
```
***System configuration***

Information                            | Value
---                                    | ---
Operating system:                      | Windows 7 SP1 U 64bit
Operating system version (Android/iOS) | ?
Browser:                               | Firefox 58.0.2 64bit / Opera 51.0 64bit
AdGuard version:                       | uBlock Origin 1.15.11b9

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Filters enabled:                       | uBlock filters
Filters enabled:                       | Adguard Base Filters
Filters enabled:                       | EasyList
Filters enabled:                       | Adguard Spyware Filters
Filters enabled:                       | EasyPrivacy
Filters enabled:                       | Fanboy’s Enhanced Tracking List
Filters enabled:                       | Peter Lowe’s Ad and tracking server list
Filters enabled:                       | EasyPrivacy
Filters enabled:                       | spa, por: Adguard Spanish/Portuguese
Filters enabled:                       | spa: EasyList Spanish
Filters enabled:                       | Adversity
Filters enabled:                       | Blockzilla
Filters enabled:                       | Privacy filters
Filters enabled:                       | uBlock Filters +
Filters enabled:                       | hpHosts’ Ad and tracking servers

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
inglesonlinedojerry.com.br request not reproduced.

**Comment by Raavizz** [comment]
> @BlazDT : inglesonlinedojerry.com.br request not reproduced.

Cannot reproduce, still having it:
`||inglesonlinedojerry.com.br/afiliados/banners/336_1.jpg`

Also it seems you have missed(?), coz still having it:
`||c1.staticflickr.com/9/8891/28354201992_3559c24d33_o.png`

**Comment by BlazDT** [comment]
.br/afiliados/ is blocked by our Spanish filter.
Photoshop picture itself is not blocked, but hidden via #text rule.

**Comment by Raavizz** [comment]
> @BlazDT : .br/afiliados/ is blocked by our Spanish filter.

I already realized.

> @BlazDT : Photoshop picture itself is not blocked, but hidden via #text rule.

Why not blocked?

**Comment by BlazDT** [comment]
Name is too random and it would be a single block rule.

**Comment by Raavizz** [comment]
Well, ok, that's what I thought, but I keep asking, just out of curiosity, I don't want to bother you or to enforce to use any filter you don't want to use (everyone creates filters his own way), but I keep asking, because I wonder why not use a filter like:
- a) `||c1.staticflickr.com/*/*/*_*_o.png`
- b) `||c1.staticflickr.com/*/*/*$image,third-party,domain=baixartorrent.info` 
- c) `||c1.staticflickr.com^$third-party,domain=baixartorrent.info`
- d) `||c1.staticflickr.com^$third-party`

As for c) and d) I didn't analyze deeply the whole website's functionality, just took a quick look at uBO's logger, but saw only a single request, to `c1.staticflickr.com/9/8891/28354201992_3559c24d33_o.png`, so it doesn't seem that using even a filter like c) or d) would break anything (would it?).
