### ISSUE TITLE
 erofishki.net - blocked comments

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1290]
При работающем Адгарде этот сайт, например, прямо сейчас, заканчивается на посте "Большой нежности пост, для мужской аудитории (50 фото)". В тоже время, если Адгард отключить, то помимо баннерного мусора страница будет листаться дальше. То есть на мгновение мелькнёт полоска с зелёным и серыми кружками, и появляются новые сообщения с девками. А при работающем Адгарде баннеров нет, всё отлично, но страница дальше не грузится.

http://prntscr.com/9pmuye
URA-129-74360

**Comment by Alex-302** [comment]
если починить, полезет реклама)
