### ISSUE TITLE
Link-tracking in Google Search results

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardFilters#129108]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Now we have a conversion of links and, as a result, link-tracking in Google search results.

### Proposed solution

To solve this problem, I use a third-party script that looks like deprecated:
https://github.com/Rob--W/dont-track-me-google

Is it possible to add a native solution to the filtering rules or antitracking/stealth modules?🤲🏼

Thank you.
Best regards!

**Comment by Alex-302** [comment]
Not for this repository. If tracking parameters removed by the rules, google shows annoying manual redirection page.
