### ISSUE TITLE
com.disney.datg.videoplatforms.android.watchdc

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#12935]
***Description***:
* **Current behaviour**: 

Mobile Ads filter is preventing the app from playing any videos.

* **Expected behaviour**: 

Mobile Ads filter shouldn't prevent the app from playing videos.

***Steps to reproduce the problem***:

1. Enable protection. Mobile Ads filter must be turned on;
2. Attempt to launch the app;
3. App will fail to load any video.

***System configuration***

**Filters:**

"English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Filter unblocking useful ads", "Experimental filter", "Simplified domain names filter", "Mobile Ads filter"

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 7.1.2
Browser:                               | N/A
AdGuard version:                       | 2.10.176
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Filter unblocking useful ads", "Experimental filter", "Simplified domain names filter", "Mobile Ads filter"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-speed
HTTPS filtering (Android only):        | On (Default mode)
AdGuard DNS:                           | Default, non-DNSCrypt
Helpdesk ID (if exists):               | 1784785

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
VPN not working on my Android and video playback only available in US :(
