### ISSUE TITLE
isnapshot.co [Ad block Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#12942]
**Site**: https://isnapshot.co/

**Issue**: Please remove the ad block message on the page.

**Screenshot**: http://prntscr.com/ipbvtn

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.146 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Not reproduced, unblocked a detection value. Please check after update in 2-3 hours.

**Comment by Nzzyme** [comment]
Looks good now
