### ISSUE TITLE
[iOS] nnm-club.me

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1294]
on iPad, missed ads: 
![image](https://cloud.githubusercontent.com/assets/15856304/12321636/cd72fed0-bab7-11e5-9507-cf17aa34b6b0.png)

on iPhone, the site looks distorted: 
![image](https://cloud.githubusercontent.com/assets/15856304/12321652/e5b546a6-bab7-11e5-95ee-5cdb04d77427.png)

GUJ-661-46031

**Comment by Alex-302** [comment]
Рекламы не вижу. На айфоне починить не могу, т.к. реального устройства нет, а в сафари на маке не меняется формат сайта. Думаю это из-за отсутствия баннера, который подпирал съехавший блок.

**Comment by evgeniy-ADG** [comment]
А вот того блока под меню сайта на первом скрине нет? У пользователя он ей на айпэде.

**Comment by Alex-302** [comment]
Сейчас сайт не открывается, не могу проверить.

**Comment by Alex-302** [comment]
Похоже фильтры старые.

**Comment by evgeniy-ADG** [comment]
Попросил обновиться.
