### ISSUE TITLE
dropgalaxy.com

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#129492]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.22

### What type of problem have you encountered?

Missed ads or ad leftovers, AdGuard gets detected on a website

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://dropgalaxy.com/lkukypm4bdkm

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

Adblock gets detected at the end of the counter
![image](https://user-images.githubusercontent.com/46019727/189607259-6356ed9b-2fe2-4c13-8271-16082befe2ce.png)

and empty spaces at bottom

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Unfortunately, I have not been able to reproduce the anti-adblock
@AdguardTeam/filters-maintainers  could you, please, check

**Comment by Alex-302** [comment]
Same. 
Please do not open issues using the template, use AdGuard feedback menu instead.

**Comment by Bhooty** [comment]
![00DF94BB-7EEB-49FA-945B-1F90AB76CA7C](https://user-images.githubusercontent.com/46019727/189715948-c05d7ee6-cac4-4be4-ab03-cffa2f391465.png)

same on ios safari with adguard app

btw any way to report from mobile app or does it have to be from desktop app?

this prob occurs after clicking free download then again click ling it when it says file ready
Then the new page shows 15sec timer then click create download link then it shows the adblock detected page

if i turn off adguard and go through the same process again then it doesn’t show the adblock detected page :(
