### ISSUE TITLE
tomsguide.com [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#12940]
**Site**: https://www.tomsguide.com/us/chrome-extension-security-problems,news-26082.html

**Issue**: Please remove the ads seen on the page by the provider "Revcontent"

**Screenshot**: http://prntscr.com/ipbegn

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.146 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Not reproduced. Fixed adblock detection value and blocked this old InstartLogic version. Please check after update in 2-3 hours.

**Comment by BlazDT** [comment]
@Nzzyme 
Do you still see the ads now?
