### ISSUE TITLE
tiz-cycling-live.io red overlay

### ISSUE THREAD

**Issue by dc911x** [AdguardTeam/AdguardFilters#129531]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

AdGuard Home DNS server Version: v0.107.11

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://tiz-cycling-live.io/live.php

### What filters do you have enabled?

AdGuard DNS filter, EasyList Dutch

### Add your comment and screenshots

1. Tiz Cycling Live puts an red overlay over the streams after a few seconds.
Lists updated, seems to have happend in the past too: #31481 #74820

2. Screenshots
<details><summary>Screenshot 1:</summary>

![afbeelding](https://user-images.githubusercontent.com/49455017/189712984-3f076a1f-c6b7-4a42-b3c8-85081cf364d4.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
Hi @dc911x

Please enable AdGuard Base filter.

**Comment by dc911x** [comment]
> Hi @dc911x
> 
> Please enable AdGuard Base filter.

I could not find the "AdGuard Base filter" in AdGuard Home but I think it's called AdAway Default Blocklist.
I enabled the list but the the overlay is still active, no idea if this is a caching issue or not.

I rebooted the AdGuard Home dockercontainer (it's running on Home Assistant) but I could not find a flush dns option.

<details><summary>Screenshots:</summary>

![afbeelding](https://user-images.githubusercontent.com/49455017/189729117-0380bf31-4741-47c9-845d-55baead9d211.png)
![afbeelding](https://user-images.githubusercontent.com/49455017/189729564-1d08b29e-7e00-4da6-8e1f-5e1ccc74f44e.png)


</details>

**Comment by Sergey-Lyapin** [comment]
Hello @dc911x
I didn't notice that you use AdGuard DNS only, sorry.
AdGuard Base filter is in the [AdGuard extension](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg).

If you want to continue using only AdGuard home, please add 
`@@||pagead2.googlesyndication.com^`
to custom filterig rules. But this domain wil be unblocked everywhere.
