### ISSUE TITLE
outdoor.adspace.pro

### ISSUE THREAD

**Issue by Miklesp** [AdguardTeam/AdguardFilters#129578]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

Версия 4.1.22

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Yandex Browser

### Which device do you use?

Desktop

### Where is the problem encountered?

https://outdoor.adspace.pro/

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

Hi! My site is an advertising agency in the city of Krasnodar. I have already applied for domain unblocking before adspace.pro and it was done. Now the site is created on a subdomain outdoor.adspace.pro for the development of outdoor advertising. This name also falls under your filters. I ask you to exclude my site from the filters so that AdGuard users do not have problems viewing my site. I am attaching a screenshot of the problem.
![Новый рисунок](https://user-images.githubusercontent.com/113426262/189857173-98ea9af3-3038-4977-bd2e-1e32b5f0e688.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
What is wrong?
