### ISSUE TITLE
soundcloud.com

### ISSUE THREAD

**Issue by wavygecko** [AdguardTeam/AdguardFilters#129623]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.44

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://soundcloud.com/settings/advertising

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

Consent options are blocked on the SoundCloud settings page.

When AdGuard Annoyances list is enabled, a consent options button appears but clicking it does not do anything.

When AdGuard Annoyances list is **disabled**, there is no button and the options appear correctly.

<details><summary>Screenshot with AdGuard Annoyances enabled</summary>

<img width="930" alt="image" src="https://user-images.githubusercontent.com/110956608/189975708-7835efee-f6dd-434a-bf1e-1c10470f2ecf.png">

</details>

<details><summary>Screenshot with AdGuard Annoyances <strong>disabled</strong></summary>

<img width="925" alt="image" src="https://user-images.githubusercontent.com/110956608/189975783-af93b66b-e069-40b1-8f09-78c92b541c11.png">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
I don't see that button without AdGuard.

**Comment by Alex-302** [comment]
I don't see that button without AdGuard.

**Comment by wavygecko** [comment]
@Alex-302 

after looking closer, this filter from `cookies_general.txt‎` is causing the ad settings toggle not to show for me:

```adblock
||onetrust.com^$third-party
```

when I add this filter:

```adblock
@@||onetrust.com^$third-party
```

the settings toggle shows for me.

**Comment by Alex-302** [comment]
Please leave in user rules.
