### ISSUE TITLE
forbes.com

### ISSUE THREAD

**Issue by wavygecko** [AdguardTeam/AdguardFilters#129614]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

ubo 1.44

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.forbes.com/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

there's a leftover space at the top of page

it can be removed with `forbes.com##.main-content--body:style(padding-top: 0 !important;)`

<details><summary>Screenshot 1:</summary>

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/110956608/189943609-69be872f-5f9f-4704-a21b-35b7e3db8ef2.png">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
Hi @wavygecko
This issue was already solved in the AdGuard Base filter.
https://github.com/AdguardTeam/AdguardFilters/issues/106020

**Comment by wavygecko** [comment]
Oh! thank you I didn't see that
