### ISSUE TITLE
[Android] login.wi-fi.ru - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1296]
после наступления 2016 года, программа перестала блокировать рекламу в московском метро. при этом используются последние версии фильтров и программы.  Сегодня проверил, результат почти такой же. Реклама конечно не играет, но картинка с рекламой осталась и нужно подождать какое-то время (серин во вложении). Раньше сразу заходил на "метрошный" портал.

![image](https://cloud.githubusercontent.com/assets/15856304/12324578/42a234f0-bacc-11e5-8882-59f0af76f28a.png)

Установлена посл. бета. EHR-815-80029

**Comment by Alex-302** [comment]
а где, собственно, картинка с рекламой?

**Comment by Alex-302** [comment]
На iOS мгновенной авторизации как раньше не сделать. Это юзерам желательно в ответ писать. Раньше при блокировке видео перебрасывало на завершающую стадию, а теперь крутится таймер.  В iOS его не убрать. Другие блокировщики для iOS тоже не могут(в лучшем случае скроют страницу с таймером, но ждать всё равно придётся)

**Comment by evgeniy-ADG** [comment]
Не могу знать, где картинка, вероятно, черный экран, таймер снизу и выключатель звука имеются в виду.

**Comment by Alex-302** [comment]
Лучше у него уточнить. Некоторые похоже по этой причине в App Store единицы ставят

**Comment by Alex-302** [comment]
а, этож Андроид. Здесь придётся ждать HTTPS, т.к. реклама грузится с https://login.wi-fi.ru , т.е. при авторизации не блокируется. Но правила уже готовы.
Пока закрываю.

**Comment by vgavrish** [comment]
1144648
wi-fi.ru недорезан рекламный блок
"2.8.40",
"enabledFilterIds" : [ 2, 3, 1, 11 ],
"filteringQuality" : "FULL",
логи 
[debug (2).txt](https://github.com/AdguardTeam/AdguardFilters/files/598390/debug.2.txt)

<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20406330/9802c360-ad15-11e6-9540-f9baa182c248.png)

**Comment by Alex-302** [comment]
У нас не повторяется

**Comment by vgavrish** [comment]
> Она повторяется через раз, то есть то она есть,  то её нет... Например сейчас получилось со второго раза, то есть сперва открываем сайт vmet.ro, открывается без рекламы, потом обновляем страницу, открывается окно как  на скрине.
Всё почищено, обновлено, устройство перезагружено.

**Comment by ypetruk** [comment]
Новый комментарий (Ticket ID: 1008494)

Реклама не фильтруется при авторизации, видимо произошло обновление ПО у метрополитена. Раньше всё было отлично.
После включения фильтрации протокола https есть улучшения. В метро
авторизация проходит быстрее, без рекламы.
Где-то с фильтрацией https реклама пропала при авторизации. Где-то просто на даёт загрузиться странице авторизации, отключаешь и всё работает.

**Comment by Alex-302** [comment]
Ничего конкретного. Нужны логи ***запросов*** для каждой ситуации с привязкой по времени.
