### ISSUE TITLE
Rema.no - Blocked objects (AdGuard English filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#12976]
***Description***:
Blocked objects @ rema.no

***URL***:
`https://www.rema.no/`

***Screenshot***:
![rema](https://user-images.githubusercontent.com/9382674/37253514-99364ff2-252a-11e8-986d-0a45c55fabc5.jpg)

***Problem filter***:
AdGuard English filter

***Problem rule***:
`##.top-banners`

***Possible fix***:
`rema.no#@#.top-banners`

--

Operating system: Windows 8.1 Pro (x64)
Browser: Pale Moon v27.8.1 (x64)
Blocker: uBlock Origin v1.15.10

**Comment by BlazDT** [comment]
Thank you, added.
