### ISSUE TITLE
mail.yahoo.com

### ISSUE THREAD

**Issue by briantho** [AdguardTeam/AdguardFilters#129718]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.44.2

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://mail.yahoo.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, EasyList, Fanboy's Annoyances, Fanboy's Social Blocking List

### Add your comment and screenshots

1. <comment>
loading yahoo mail with no filters enabled works fine. whenever i enable adguard base, yahoo mail winds up with emails looking grey (see screenshot). this happens when scrolling down the page when you try to view old emails. with all other filters enabled, except adguard base, page loads normally. I'm using ublock origin on the latest chrome browser running windows 10 
2. Screenshots
with adguard base enabled. 
![image](https://user-images.githubusercontent.com/3977205/190247647-319f479a-4e2c-42d2-b263-6d4a7100d399.png)

with adguard base disabled

![image](https://user-images.githubusercontent.com/3977205/190248824-8eca86f3-d9a6-4764-937e-161e61a75bea.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by briantho** [comment]
nevermind. I figured it out. was a chrome bug

**Comment by briantho** [comment]
sorry for closing and reopening, i though i just solved it, turns out i was wrong. This issue is still happening

**Comment by Alex-302** [comment]
Cannot reproduce. Maybe caused by recent uBO's bug. Please try the latest dev build. Or use AdGuard:)

**Comment by briantho** [comment]
> Cannot reproduce. Maybe caused by recent uBO's bug. Please try the latest dev build. Or use AdGuard:)


Just tried installing the adguard browser extension for firefox, and disabled ublock for testing purposes. Same result. THis happens on firefox as well as chrome. To reproduce, login to yahoo mail and try scrolling to emails from a week ago or longer. Emails that are newer than a week show correctly, emails that are older result in grey bars. Would some logs be helpful? I can't seem to figure out how to export them from the browser extension. Is there something I'm missing?

here is a screenshot of the filtering log

![image](https://user-images.githubusercontent.com/3977205/190790312-c7271027-c127-4ba2-9de1-24bb2a8250ef.png)

**Comment by Alex-302** [comment]
@briantho You can create an exclusion for applied rules using the filtering log. Just click on the line and select Unblock. This will helps you to fing a bad rule. If you will find it - please copy it here.



> try scrolling to emails from a week ago or longer

I don't have such emails. I am not a Yahoo user.

**Comment by briantho** [comment]
mail.yahoo.com#@$#ul[aria-label="Message list"] > li { position: static!important; }

this was added to user rules when i clicked on unblock. I just tested it, yahoo mail seems to be working again. Thanks for your help. let me know once you push this change, and i'll be glad to test it again with my other computers.
