### ISSUE TITLE
https://outlook.termosdeuso.live

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdguardFilters#129806]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.11 nightly 11

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://outlook.termosdeuso.live

### What filters do you have enabled?

AdGuard Base filter, AdGuard Spanish/Portuguese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Social Blocking List, Web Annoyances Ultralist, Online Malicious URL Blocklist

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Block third-party Authorization header, Block WebRTC, Hide Referrer from third-parties (specify in comment below, if used custom value), Hide your User-Agent (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

Fake: https://www.googleadservices.com/pagead/aclk?sa=L&ai=C3seiJpC5XstooZGJBrPArsADp__a3lyH_4PTjAqoqKfonA8QASC7-_keYISV7IXcHaABzavQ-gPIAQmpAt6UwcHeNU0-qAMByANKqgTEAU_Q2dNvWCQ_LtumFUNLEz16PFVhg8cC3HmYEdlxma4KWUfGkvbdLFpKvCC92odSoiBTw9idw1iHRgreOTD1xyzoBBif4axm3JFTnekl_2_OeuLDQv0U_HzVVt10Iu5SkzsX6nGWyfUgPHIgJkxJqY4me8SG8d0nlmJ8PumQhJhze02bPmqEr4puzh2awPAoHoVPQ7QaXlbeJvf4W7Wexg1RGQ0EqMY8Z7YLfyh6tceagXiYGwWU1r3H9HuiISfj4G-RYYTABM-Sru2hAsAFBfoFBgglEAEYAJAGAaAGLoAHm9SvBYgHAZAHAqgHjs4bqAeT2BuoB7oGqAfw2RuoB_LZG6gHpr4bqAfs1RuoB_PRG6gH7NUbqAeW2BuoB8LaG9gHAMAIAdIIBggAEAIYGoAKAZALA5gLAcgLAYAMAeAS_6jY_crtxomjAdgTDg&ae=1&num=1&cid=CAMSeQClSFh3L5xTIDfFt35D8xjVEHFCYXr5NOlTRany4t_BBsFsAp3b7XCD0nSBKDirzhPVamy0H75uzx6gQxh5_rKDAlBAJWTUCf1Tqi6saFbojDtHd_R8dtCePj4ZvH0zHZWyRITLXvztggY2ibrWY9oLm5X8Wcuetvk&sig=AOD64_0L9hd4oCjDoroDTf6-7Fkon2bwsw&ctype=5&client=ca-pub-1169945711933407&adurl=https://www.aseptoray.com/wp-admin/css/assets/ or https://outlook.termosdeuso.live/?session=FTxvo1TGJW30pH6Pk18ANM80ald9o1lrKZs0BeTgW1bQzNM1SiWGW4483ffb25fb51f63b20cfec326b350a5
Official website: https://login.live.com/login.srf

![Captura de Tela (14)](https://user-images.githubusercontent.com/16819380/190422273-e4a52a92-b7d3-40cd-b0b6-b24a2285f1b8.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Need the source of this link.

**Comment by eduardoaddad** [comment]
source: e-mail 
![fake](https://user-images.githubusercontent.com/16819380/190436066-a6dbea69-4327-4880-a490-e7f50dc14a75.png)
@Alex-302

**Comment by Yuki2718** [comment]
> Should/could something like `||outlook.*.live^$doc,domain=~outlook.live` be added? 

Too broad

**Comment by eduardoaddad** [comment]
`.termosdeuso.live` ?

**Comment by Alex-302** [comment]
Better provide the source of https://www.googleadservices.com/ link.
