### ISSUE TITLE
pornicom.com [NSFW] [Ad]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#12999]
**Site**: https://www.pornicom.com/videos/1113794/skyla-noveas-anal-got-screwed-so-fucking-deep/

**Issue**: Please remove the ads seen on the player. Also remove the string "AD" below the player.

**Screenshot**: http://prntscr.com/ipqsa3

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.146 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by Nzzyme** [comment]
https://www.pornicom.com/videos/1263218/bbc-of-12-inch-deep-inside-jennifer-whites-asshole/?utm_source=galore&utm_medium=cpc&utm_campaign=pornicom

Ad text string seen at new places on the page. Please fix

http://prntscr.com/muk2ro

**Comment by BlazDT** [comment]
Fixed

**Comment by Nzzyme** [comment]
https://www.pornicom.com/videos/1333314/sarah-vandella-takes-bbc-balls-deep-cuckold-sessions/

Pop-up seen when clicking on seek bar of player.

**Comment by BlazDT** [comment]
Fixed
