### ISSUE TITLE
www.bricodepot.ro

### ISSUE THREAD

**Issue by mortyam** [AdguardTeam/AdguardFilters#130041]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Ublock Origin with AdGuard Annoyance

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

www.bricodepot.ro

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

After I open the website, a grey window appear.

### Privacy

- [X] I agree to follow this condition

**Comment by mortyam** [comment]
@Sergey-Lyapin On `https://www.bricodepot.ro/` there is still a pop-up. I posted a picture below with the issue. Can be fixed? 

<details><summary>Screenshot :</summary>

 
![image](https://user-images.githubusercontent.com/47023431/192093178-7bf44bdb-1c3e-4aaa-a570-8eb1de14df3d.png)

**Comment by Sergey-Lyapin** [comment]
Hi @mortyam
I can't reproduce the issue with Ublock and AdGuard Annoyances filter enabled only.

**Comment by mortyam** [comment]
@Sergey-Lyapin I used the option "Purge all caches" on Ublock and everything is fine now. Thank you!

**Comment by mortyam** [comment]
@Sergey-Lyapin Sorry to disturb you again but I see that cookie pop-up again. I use Firefox 105.0.2 with Ubock Origin 1.44.4, all filters are up-to-date using "Purge all caches". I asked on ublock github page and they found a fix: add `/gdprcookie/*` as filter, and it worked.
