### ISSUE TITLE
vikiporn.com [NSFW] [Ad]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#13002]
**Site**: https://www.vikiporn.com/videos/1105568/big-tits-lawyer-mom-fucks-her-clien/

**Issue**: Ad seen and player missing.

**Screenshot**: http://prntscr.com/iprbxr

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.146 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by BlazDT** [comment]
Please check the site for popups, couldn't find any.

**Comment by Nzzyme** [comment]
Looks good now

**Comment by BlazDT** [comment]
Thank you.

**Comment by Nzzyme** [comment]
https://www.vikiporn.com/videos/122768/ebony-milf-shares-husbands-bbc-with-whitegirl/

Seeing pop-up when clicking on play on Chrome

**Comment by BlazDT** [comment]
Fixed
