### ISSUE TITLE
upornia.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#13000]
**Site**: https://upornia.com/videos/344365/super-legs-de-tight-skirt-2-inagawa-natsume/

**Issue**: Please remove the string "Advertisement" below the player.

**Screenshot**: http://prntscr.com/ipqyzk

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.146 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by Nzzyme** [comment]
Ad text string seen here
https://upornia.com/videos/963648/best-pornstar-asia-zo-in-amazing-chinese-pov-porn-clip/?promo=16271


http://prntscr.com/o26olf

**Comment by BlazDT** [comment]
Sadly not shown and screenshot does not show for me :(

**Comment by Nzzyme** [comment]
Strange as the screenshots still open for me. Must be geo restriction.

**Comment by Nzzyme** [comment]
or this one?
https://www.hidemyass-freeproxy.com/proxy/en-gb/aHR0cHM6Ly9wcm50LnNjL28yNm9sZg

Can you check?

**Comment by BlazDT** [comment]
Thank you, screenshot via proxy works, dunno what's wrong.
Anyway, I could finally reproduce it, added rule, update available in about 3 hours.

**Comment by Nzzyme** [comment]
https://upornia.com/videos/566297/xafa412-intimate-record-on-1-30-15-11-15-from-chaturbate/?promo=15478

Screenshot: https://prnt.sc/prqruh
https://www.hidemyass-freeproxy.com/proxy/en-in/aHR0cHM6Ly9wcm50LnNjL3BycXJ1aA

Please fix

**Comment by BlazDT** [comment]
Fixed, let's see if they change class name.
