### ISSUE TITLE
Adguard extention for Chrome is blocking Link sharing in Google Photos

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardFilters#130165]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.22

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://photos.google.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyPrivacy, Online Malicious URL Blocklist

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Block WebRTC, Hide Referrer from third-parties (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests

### Add your comment and screenshots

Hi all,

I think this thing happened before, now it's happening again
https://photos.app.goo.gl/u9o655zdtCdar7rK7

Please see the above video I've recorded in order to demonstrate that the link sharing option in Google Photos is gone as soon as I turn on my Adguard extension. The Chrome version is the latest 105.0.5195.127 (Official Build) (64-bit)

I hope this will help to resolve the problem quickly.

Kind regards.

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Please try this rule:

`photos.google.com#@#button[aria-label="Share"]`

@AdamWr imho we should unblock that button (specific rule is hiding it), what do you think?

**Comment by AdamWr** [comment]
It looks like useful button, so I think that we can unblock it.
