### ISSUE TITLE
Incorrect blocking of useful Mailerlite scripts

### ISSUE THREAD

**Issue by AdamKopf** [AdguardTeam/AdguardFilters#130117]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.44.2

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.masterborn.com/masterui

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1. There is a rule in AdGuard Annoyances that prevents displaying of perfectly valid, user-initiated email forms from Mailerlite.

2. Screenshots
<details><summary>Email submit form with filter enabled:</summary>

![image](https://user-images.githubusercontent.com/147478/190984145-9e4a0eae-096c-4764-b9f0-528672e4bcb3.png)

</details>

<details><summary>Problematic filter:</summary>

<img width="999" alt="image" src="https://user-images.githubusercontent.com/147478/190983872-a4bea750-a989-40ec-9be8-735de140be1a.png">

</details>

<details><summary>Email submit form after disabling the filter:</summary>

![image](https://user-images.githubusercontent.com/147478/190984427-e1222a70-aa1e-4f86-b535-395755635a25.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.

**Comment by joehand** [comment]
We are having this issue trying to use MailerLite as well (for email subscription forms). Can we get this filter removed entirely rather than selectively enable sites?

**Comment by AdamWr** [comment]
Email subscription forms (like newsletters, "Sign Up for Our Daily Digest" and other similar things) are intentionally blocked by `AdGuard Annoyances filter`.
In case of `masterborn.com`, it's used to receive a link to their product and it seems that it's the only way to get it, so that's why it has been unblocked.
