### ISSUE TITLE
com.google.android.apps.translate

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#13037]
***Description***:
* **Current behaviour**: 

Two-way translation isn't working when the application is enabled.

* **Expected behaviour**: 

AdGuard shouldn't affect Google Translate at all.

***Steps to reproduce the problem***:

1. Enable protection in AdGuard;
2. Launch the app and try to translate anything;
3. App will fail to translate the user input.

***System configuration & logs***
Logs available under 1722356.

**Filters:**

"English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter"

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 6.0.1
Browser:                               | N/A
AdGuard version:                       | 2.10.176
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | Default
Helpdesk ID (if exists):               | 1722356

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.

**Comment by altokarev** [comment]
On Android 8.1.0 works fine for me.

@akmLaVx Advise the user to turn off HTTPS filtering for this app: https://uploads.adguard.com/up01_rrog9_Image.png

**Comment by akmLaVx** [comment]
User has been notified.

**Comment by akmLaVx** [comment]
No reply.
