### ISSUE TITLE
Я.Погода

### ISSUE THREAD

**Issue by nimoid** [AdguardTeam/AdguardFilters#130386]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3,6,10 (51)

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=ru.yandex.weatherplugin

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals

### Add your comment and screenshots

<details><summary>Screenshot:</summary>

![IMG_20220922_124301](https://user-images.githubusercontent.com/60379617/191717617-6753b8da-314a-4f76-a4a5-a0110740c666.jpg)

</details>

### Privacy

- [x] I agree to follow this condition

**Comment by zloyden** [comment]
It cannot be blocked, otherwise the app will be broken.
You can turn off the ads in the settings - about the app.
