### ISSUE TITLE
b1tv.ro

### ISSUE THREAD

**Issue by sugarfreesweetener** [AdguardTeam/AdguardFilters#130436]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.22

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

other(specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://www.b1tv.ro/`

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, road-block

### Add your comment and screenshots

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/113248817/191836355-b67c8e50-2289-44c9-b52b-238961c08efc.png)

</details>

Browser: Brave

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/74583771c939b956bc0c311bde625d26a833fe69
