### ISSUE TITLE
[Android] spaces.ru missed banner

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1304]
AOI-170-29042

![image](https://cloud.githubusercontent.com/assets/15856304/12348748/ab72eac8-bb72-11e5-8be5-775f9afca50d.png)

http://spaces.ru/lenta/?Link_id=370223

**Comment by Alex-302** [comment]
spaces.ru###page_gpz

**Comment by Bohdan-SUP** [comment]
It's still there:
![screenshot 09-26am](https://cloud.githubusercontent.com/assets/14153331/12529042/a448e4ea-c1b3-11e5-8e10-8b2a3b3cab8e.png)

**Comment by Alex-302** [comment]
spaces.ru$$a[href="http://m.mobiads.ru/"][parent-elements="div"][parent-search-level="1"]

**Comment by Bohdan-SUP** [comment]
Снова есть :(
http://prntscr.com/a01u87

**Comment by Alex-302** [comment]
@Bohdan-SUP 
какой режим фильтрации? С качественным у меня чисто.

**Comment by Bohdan-SUP** [comment]
С качественный режимом вот так:
http://prnt.sc/afhjhe

**Comment by Alex-302** [comment]
"Это норма"(с)

**Comment by evgeniy-ADG** [comment]
В разделе Журнал
![image](https://cloud.githubusercontent.com/assets/15856304/14067849/ad757c30-f477-11e5-9ef6-fcc72e68d3e4.png)
Зона обмена
![image](https://cloud.githubusercontent.com/assets/15856304/14067853/c655c412-f477-11e5-9bdb-7b93deff7386.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
передай
###index_page > div[class][id] > div
вряд ли долго проживёт, они быстро переделывают

**Comment by evgeniy-ADG** [comment]
http://spaces.ru/shared_zone/?link_id=632478&ref=footer

![image](https://cloud.githubusercontent.com/assets/15856304/14428192/b7d47048-0000-11e6-9de6-8eac24180946.png)

**Comment by Bohdan-SUP** [comment]
Now on a Mac as well:
http://spaces.ru/shared_zone/?link_id=1348533&ref=footer
![screen shot 2016-04-18 at 8 19 04 pm](https://cloud.githubusercontent.com/assets/14153331/14612996/d4084396-05a2-11e6-9889-b6960a4d6af6.png)

**Comment by Alex-302** [comment]
обновиться нужно

**Comment by vgavrish** [comment]
Реклама внутри личного кабинета на закладках "Журнал" и "Лента"
<details>
![screenshot_24](https://cloud.githubusercontent.com/assets/18548949/16899260/4f0346aa-4c06-11e6-82b3-759becd9c419.jpg)
</details>

Фильтры: 1,2,3,4,5,11,14

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
spaces.ru##a[href^="http://spaces.ru/services/ads_off/?link_id="] + div[class] > div > div[id^="spac"]
spaces.ru##a[href^="http://spaces.ru/app/close_notify/?link_id="] + div.stnd-block
spaces.ru##a[href^="http://spaces.ru/app/close_notify/?link_id="]
spaces.ru##a[href^="http://spaces.ru/services/ads_off/?link_id="]

```
если что-то лишнее пропадёт - пусть сразу пишет

**Comment by dzamyshlyayeva** [comment]
the issue is back
Ticket ID 1522855
![image](https://cloud.githubusercontent.com/assets/23372054/24074451/a59783b6-0c11-11e7-8204-b87507563fb7.png)

**Comment by Alex-302** [comment]
Ашчув

**Comment by Alex-302** [comment]
Fixed
