### ISSUE TITLE
Missing ads on both IOS and Android app.

### ISSUE THREAD

**Issue by Adstarav** [AdguardTeam/AdguardFilters#130524]
### Prerequisites

- [x] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

AdGuard/AdGuard Pro for iOS v4.4.0

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://apps.apple.com/in/app/realme-link/id1536584786

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### What Stealth Mode options do you have enabled?

Block WebRTC, Block Push API, Block Location API

### Add your comment and screenshots

I am linking the already opened adguard github page that have all the details.
This is a month old thread but now the issue shows up on the "Real Me Link" app AGAIN on both IOS as well as Android.
Please check from the below opened ticket.

https://github.com/AdguardTeam/AdguardFilters/issues/126027

https://github.com/AdguardTeam/AdguardFilters/issues/126027

Thanks

screenshot of the ad appearing.-
![image](https://user-images.githubusercontent.com/114125727/192055146-9d401afc-ba5d-4f23-9590-575b259787ac.png)

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@Adstarav Hello, do you have DSN filtering enabled?

**Comment by Alex-302** [comment]
@Adstarav This ad may me loaded as their useful content(99%), and I am not sure if it can be blocked.

**Comment by Alex-302** [comment]
Is your Android device rooted?

**Comment by Alex-302** [comment]
So any specific request can't be blocked in this app.
