### ISSUE TITLE
[iOS] korrespondent.net

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1305]
Пропущена реклама на странице:
http://korrespondent.net/ukraine/3615242-Roshen-ne-prodam-hlavnye-tezysy-poroshenko
![image](https://cloud.githubusercontent.com/assets/15856304/12348798/254e44be-bb73-11e5-91e2-6bccb6ab7c20.png)
LNK-144-18135

**Comment by Alex-302** [comment]
У меня не повторилось. Можешь у себя проверить?

**Comment by evgeniy-ADG** [comment]
Попросил ребят, проверим.
