### ISSUE TITLE
https://kit.fontawesome.com/ bloqued

### ISSUE THREAD

**Issue by micuit-cuit** [AdguardTeam/AdguardFilters#130619]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [x] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

VIPrivacy

### What type of problem have you encountered?

Social media buttons — share, like, tweet, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://webos-app.000webhostapp.com/

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

https://kit.fontawesome.com/ bloked

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Not blocked as seen in this screenshot:

![image](https://user-images.githubusercontent.com/34266271/192138438-fa26f3b9-020f-4da0-8868-af667a003b4d.png)

Please provide screenshots and a more detailed description what is broken exactly.
