### ISSUE TITLE
next.co.uk

### ISSUE THREAD

**Issue by DesertBear** [AdguardTeam/AdguardFilters#130757]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin (1.44.4); AdGuard Annoyances filter (2.1.34.46)

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.next.co.uk/style/st014336/134019#134019

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1. When visiting the above web page, the "Size Guide" link does not work.  The link is supposed to open the "Size Guide" panel on the right-hand side, but does not when the AdGuard Annoyances filter is enabled in uBlock Origin.  The issue does not occur with the Fanboy’s Annoyance filter list.

The issue appears to be caused due to the below rule:

```
Filter
||cookielaw.org^$3p

Filter list
AdGuard Annoyances
 
Context
www.next.co.uk

Partyness
(3) next.co.uk ⇒ cookielaw.org

Type
script

URL
https://cdn.cookielaw.org/scripttemplates/otSDKStub.js
```

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot A](https://user-images.githubusercontent.com/27423064/192395186-8b41723f-abaf-4aa2-8b34-bf1aa20561c9.png)

</details>

3. Details

```
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 89200
  cosmetic: 92003
  scriptlet: 23881
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 59583-86, 12m
    block-lan: 44-0, 1d.11h
    ublock-annoyances: 4832-159, 1d.11h
  default: 
    user-filters: 93-0, never
    easylist: 62613-108, 1d.11h
    easyprivacy: 30636-1258, 1d.11h
    plowe-0: 3670-865, 1d.11h
    ublock-abuse: 76-0, 1d.11h
    ublock-badware: 4180-105, 1d.11h
    ublock-filters: 32884-499, 1d.11h
    ublock-privacy: 246-1, 1d.11h
    ublock-quick-fixes: 248-5, 10h.34m
    ublock-unbreak: 1859-44, 1d.11h
    urlhaus-1: 7407-0, 10h.45m
filterset (user): [array of 92 redacted]
trustedset: 
  added: [array of 6 redacted]
hostRuleset: 
  added: [array of 20 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1654 ms
  maxAssetCacheWait: 485 ms

```

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please do not post ubo's config here, it is useless for us.

**Comment by Alex-302** [comment]
The issue is not reproduced with AdGuard or UBO.

**Comment by DesertBear** [comment]
You obviously didn't try very hard to reproduce it.  All your staff been conscripted?

I think I'll just avoid using AdGuard.

**Comment by jellizaveta** [comment]
I'm cannot reproduce either with uBlock and AdGuard extensions.

**Comment by Sergey-Lyapin** [comment]
The issue only reproduces if AdGuard Annoyances is enabled at the same time as EasyPrivacy, it can also be solved by exclusion `@@||next.co.uk/static-content/gtm-sdk/gtm.js` for EasyPrivacy. Fixed on our side.
