### ISSUE TITLE
Foreign.txt filter list should be moved to language specific from base filter.

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdguardFilters#130772]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Hi! As a user, i think the [BaseFilter](https://github.com/AdguardTeam/AdguardFilters/tree/master/BaseFilter/sections) is based on the English language. So, i think it is unnecessary for English-only users to have the [foreign](https://github.com/AdguardTeam/AdguardFilters/blob/master/BaseFilter/sections/foreign.txt) filter listed in the [BaseFilter](https://github.com/AdguardTeam/AdguardFilters/tree/master/BaseFilter/sections).

### Proposed solution

[foreign](https://github.com/AdguardTeam/AdguardFilters/blob/master/BaseFilter/sections/foreign.txt) filter should be moved from [BaseFilter](https://github.com/AdguardTeam/AdguardFilters/tree/master/BaseFilter/sections) to [AdguardFilters](https://github.com/AdguardTeam/AdguardFilters) with make a new section `ForeignFilter`. As end user i think it should be in the language specific list and according to the number of filter uses, it will be useful in terms of usage.

**Comment by Alex-302** [comment]
Not a bad idea, maybe we will move that rules to separate rules.
But in any case Base filter has rules for many langs(for example, popular antiadblock rules with a lot of domains).

**Comment by Alex-302** [comment]
We decided to leave it as it is.

**Comment by Alex-302** [comment]
These filters I can enable, when I get an error.

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/d802cbef-6f93-4a78-b3cb-94663a2b175b)
![image](https://github.com/user-attachments/assets/a2b53063-13ff-4433-93fc-c61beaff45ad)


</details>
