### ISSUE TITLE
net.footmercato.mobile

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#13079]
***Description***:
* **Current behaviour**: 

Displays ads between articles.

<details><summary>Screenshot:</summary>

![20180312_214852](https://user-images.githubusercontent.com/33634917/37348675-5d1adc7c-26dd-11e8-9bab-77e3a9d38141.jpg)
</details><br/>

* **Expected behaviour**: 

Should not display ads.

***Steps to reproduce the problem***:

1. Launch app with AdGuard protection enabled.
2. Enjoy the ads!

***System configuration***

**Web Requests Log:**
available under 1076052

**Filters:**

"English filter", "Spyware filter", "Social media filter", "Filter unblocking useful ads", "French filter", "Mobile Ads filter", "Liste FR", "List-KR"

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 8.0.0
Browser:                               | n/a
AdGuard version:                       | 2.10.176
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Filter unblocking useful ads", "French filter", "Mobile Ads filter", "Liste FR", "List-KR"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 1076052

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.
@AdamWr @BlazDT please take a look.

**Comment by AdamWr** [comment]
I can't reproduce it.

**Comment by BlazDT** [comment]
Not reproduced.
