### ISSUE TITLE
flylogio.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#13085]
***Description***:
* **Current behaviour**: 

Enabled Ad Blocking completely kills the site.
Pic 1: AdGuard enabled.
Pic 2: AdGuard disabled.
<details><summary>Screenshot:</summary>

![flylogio_adgon](https://user-images.githubusercontent.com/33634917/37357557-6e817bec-26f1-11e8-86d9-d2fdbb4aab1c.png)
![flylogio_adgoff](https://user-images.githubusercontent.com/33634917/37357578-77d55222-26f1-11e8-86c2-bce413defb21.png)

</details><br/>

* **Expected behaviour**: 

AdGuard shouldn't block the site.

***Steps to reproduce the problem***:

1. Enable the protection
2. Visit the website.

***System configuration***

** User ID & Logs **
1602225

**Filters:**

English, Spyware, Social, Annoyances, Unblock useful ads, Russian, Mobile Ads, Safari

Information                            | Value
---                                    | ---
Operating system:                      | iOS
Operating system version (Android/iOS) | 11.2.6
Browser:                               | Safari
AdGuard version:                       | 2.0.2
Filters enabled:                       | English, Spyware, Social, Annoyances, Unblock useful ads, Russian, Mobile Ads, Safari
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | Default
Helpdesk ID (if exists):               | 1602225

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Not reproduced, please check @AdamWr. Very likely it has some strange body class and therefore it is hidden.

**Comment by AdamWr** [comment]
I can't reproduce it on iOS and Windows.
<details><summary>Screenshot</summary>

![flylogio_com](https://user-images.githubusercontent.com/29142494/37397947-3e3e6134-277d-11e8-8c0d-01d263926523.PNG)

</details>
<br>

Could you please ask user to check this rule:
`@@||flylogio.com^$generichide`

**Comment by akmLaVx** [comment]
User reports that @AdamWr 's suggested fix has resolved the issue.

**Comment by evgeniy-ADG** [comment]
The user got back and reported that it still won't load.

**Comment by AdamWr** [comment]
Unfortunately I still can't reproduce it, but could you please ask user to check:
`@@||flylogio.com^$elemhide`
or
`@@||flylogio.com^$genericblock`

**Comment by akmLaVx** [comment]
Waiting for user to reply.

**Comment by akmLaVx** [comment]
@AdamWr This seems to have helped.
