### ISSUE TITLE
Corehency ?

### ISSUE THREAD

**Issue by Phil353556** [AdguardTeam/AdguardFilters#130824]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

version: v0.107.13

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://app-measurement.com/sdk-exp

### What filters do you have enabled?

AdGuard Base filter, AdGuard DNS filter

### Add your comment and screenshots

1. Why one url is filtered as attended and not the other one, as the base URL is identical?

2. Screenshots
URL filtered and not filtered:
![ksnip_20220927-141027](https://user-images.githubusercontent.com/64729485/192523992-58f973b2-b37e-47c3-8619-4a6d9b9855e6.png)

All list used:
![ksnip_20220927-141454](https://user-images.githubusercontent.com/64729485/192524070-91712ff5-d595-4325-89d3-715f6e65f6b9.png)

Thank you
Phil

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
As far as I understand, there is an answer for this question - https://github.com/AdguardTeam/AdguardForiOS/issues/1942#issuecomment-1042689002

> Seems that some library tries to resolve something that is not domain.
> 
> Since adblock-style rules has auto-conversion for compatibility with regular adblock-style lists, protocol is stripped during parsing and therefore not used during matching. Hosts rules has domain validation, so can't be used too.
> 
> However, regex rules like `/https:/` or `/app-measurement.com/` should work

Another two related questions/issues:
https://github.com/AdguardTeam/AdGuardHome/issues/4301
https://github.com/AdguardTeam/AdguardFilters/issues/109607#issuecomment-1048105349
