### ISSUE TITLE
The annoyance filter breaks reddit home page modal because page scrollbar is forced shown

### ISSUE THREAD

**Issue by mmis1000** [AdguardTeam/AdguardFilters#130974]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.36

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.reddit.com/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1. Open any thread in front page with mouse left click.
2. The modal scrollbar is overlayed by page scrollbar and you can't scroll the page with pointer.
3. Screenshots
<details><summary>Screenshot 1:</summary>

![圖片](https://user-images.githubusercontent.com/2993977/192993670-c5ea7b7a-9f71-4622-952b-a7e01e6508e4.png)

</details>

> originnal issue: https://github.com/webcompat/web-bugs/issues/111538

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@mmis1000 Please check again.
