### ISSUE TITLE
ad-shield site Incorrect Blocking

### ISSUE THREAD

**Issue by NoName926** [AdguardTeam/AdguardFilters#130971]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.11 Beta 2

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.ad-shield.io/ko

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

![2](https://user-images.githubusercontent.com/99063049/192985748-6c708ca7-d0ae-4ce0-bcc0-c66c8093bdb6.png)

There is a script that blocks AdShield ads, so please remove the ||ad-shield.io^ rule from the AdGuard DNS filter.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #1056](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1056) via [**Zenhub**](https://www.zenhub.com/)
