### ISSUE TITLE
[iOS] m.yablyk.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1311]
http://m.yablyk.com/130105-kak-sozdavat-papki-v-tvos-9-2/

![image1](https://cloud.githubusercontent.com/assets/14153331/12376128/80f4f964-bcec-11e5-9ea0-48b1937c2929.PNG)

YOD-211-57386

**Comment by Alex-302** [comment]
не повторилось/ Это реклама google, должна быть заблокирована
Пусть попробует выключить эти фильтры
ID=101 Name="EasyList" Version=1.0.50.74 Enabled=YES

ID=108 Name="EasyList Hebrew" Version=1.0.2.7 Enabled=YES

ID=115 Name="RU AdList" Version=1.0.50.78 Enabled=YES

ID=208 Name="Malware Domains" Version=1.0.50.66 Enabled=YES

ID=210 Name="Spam404" Version=1.0.1.26 Enabled=YES

ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.56 Enabled=YES

ID=212 Name="RU AdList: Counters" Version=1.0.47.35 Enabled=YES

ID=213 Name="RU AdList: BitBlock" Version=1.0.47.61 Enabled=YES

**Comment by Alex-302** [comment]
@Bohdan-SUP 
ну что, не отписался юзер?
