### ISSUE TITLE
chelsea-news.co

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#131121]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.51

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.chelsea-news.co/2022/09/striker-already-in-concrete-negotiations-to-sign-for-chelsea/amp/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Anti-Facebook List

### Add your comment and screenshots

1. <comment>
Empty placeholder at the bottom of the page.
2. Screenshots
<details><summary>Screenshot 1:</summary>

![2022-10-1_12-25-13](https://user-images.githubusercontent.com/29574622/193395958-dc739047-9bc3-434e-9f49-62d62765f49d.PNG)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not an ad. Similar to useful element.
