### ISSUE TITLE
Find a way to use Akamai's malicious domain research & detection

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardFilters#131291]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Akamai has done some research & detection of newly-registered malicious domains @ https://www.akamai.com/blog/security-research/newly-observed-domains-discovered-8-million-malicious-domains.

### Proposed solution

Find a way to use that, either directly or as inspiration, to improve security via AG.

**Comment by DandelionSprout** [comment]
It could be possible to contact https://www.akamai.com/solutions/security/zero-trust-security about access to their database, but those kinds of companies tend to charge bewildering amounts of money for such wishes.

**Comment by TPS** [comment]
That's why I mentioned "as inspiration."  It doesn't look like it'd be impossible (just quite a _lot_ of work) to do what's set forth in the post, especially as AG has its own DNS to gather this type of data from.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/143363
