### ISSUE TITLE
Annoyance filter list probably should block this pop-up

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#13136]
I think Annoyance filter list probably should block this pop-up,

Website: https://blog.bitwarden.com/bitwarden-desktop-app-released-for-windows-macos-and-linux-37de846ea421

Screenshot: http://imgbox.com/iW3XlejO

OS: Windows 10
Browser: Firefox Beta 59
Add-on: uBlock Origin

**Comment by Alex-302** [comment]
ok
