### ISSUE TITLE
Code text on top left of YouTube pages regardless of filters on or off

### ISSUE THREAD

**Issue by Mennaruuk** [AdguardTeam/AdguardFilters#131467]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.19

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.youtube.com/watch?v=T1mj8-NTW0o

### What filters do you have enabled?

Legitimate URL Shortener

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

1. It doesn't matter if filters are turned on or off. There is always code text having to do with app drawer showing up on top left of every YouTube page. There is no option to choose None here in the GitHub post, but Stealth Mode is off, and there are no user rules. I tried element picking, but I can't precisely select the code text.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot 2022-10-05 at 08-38-04 13 DOLLAR TREE hacks that beat AMAZON FAVORITES (save $200)! - YouTube](https://user-images.githubusercontent.com/52135169/194063759-83b8a744-31de-4a79-a73b-e619a361ef1e.png)

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Cannot reproduce on Extension version 4.1.22. That code elements look like the injected CSS. Please check with current filters and extension version, thank you.

![image](https://user-images.githubusercontent.com/34266271/194272521-428c11b3-3930-4abf-8ec6-09f548d5b6d6.png)
