### ISSUE TITLE
admicro.fr

### ISSUE THREAD

**Issue by PapyGeek** [AdguardTeam/AdguardFilters#131408]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

ADblock Ultimate

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://admicro.fr/

### What filters do you have enabled?

---Third-party filters---

### What Stealth Mode options do you have enabled?

Block third-party Authorization header

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>
![admicro](https://user-images.githubusercontent.com/22013375/193868880-75b3153b-76da-4743-b6a8-12bed4a5fb18.jpg)

</details>

<details><summary>Screenshot N:</summary>

</details>
![admicro](https://user-images.githubusercontent.com/22013375/193868941-b3b9197e-c7da-45ce-a6e9-bba124400079.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Works fine, content loads. Your screenshots are the same.
