### ISSUE TITLE
wabetainfo.com (AdBlocker detected)

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardFilters#131677]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

/

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

https://wabetainfo.com

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

Not sure if the page is blocked by the extension too but with 'AdGuard DNS' I can't access the page.

<img width="1270" alt="Bildschirm­foto 2022-10-08 um 11 31 34" src="https://user-images.githubusercontent.com/83946731/194700845-f37e2bf9-e6a3-4940-a392-a45c81d8fc73.png">

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Please enable AdGuard Base Filter.

**Comment by iDjay** [comment]
Using AdGuard DNS only, so I guess there's no way to fix it?
