### ISSUE TITLE
ForceTools-Kepmar.eu - Broken (AdGuard Annoyances filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#131695]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.44.4

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other(specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.forcetools-kepmar.eu/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

ForceTools-Kepmar.eu - Broken (Easylist Cookie List / Fanboy's Annoyance List) [GDPR]

### Affected site:
`https://www.forcetools-kepmar.eu/`

### Issue:
Grey modal overlay / unclickable items.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **AdGuard Annoyances filter**

### Problem rules:

`##.cookie-consent-content`

`~muenchner-bank.de,~vbleos.de,~vrdh.de,~vrbsaale-unstrut.de,~vrbrm.de,~vrblausitz.de,~vrbanksn.de,~vrbanklm.de,~vrbank-westkueste.de,~vrbank-suedoldenburg.de,~vrbank-osnordland.de,~vrbank-oldenburgland.de,~vrbank-hsh.de,~vrbank-enz-plus.de,~vrbank-eg.de,~vrbank-bamberg-forchheim.de,~vrbank-altenburgerland.de,~vr-teilhaberbank.de,~vr-sl-mh.de,~vr-obm.de,~vr-mio.de,~vr-banking-app.de,~vr-bank-westmuensterland.de,~vr-bank-hm.de,~vr-bank-bonn.de,~volksbank-rhein-lippe.de,~volksbank-rhede.de,~volksbank-raiffeisenbank-regensburg-schwandorf.de,~volksbank-mn.de,~voba-rhein-erft-koeln.de,~vbvorpommern.de,~vbsila.de,~skatbank.de,~raiffeisenbank-im-breisgau.de,~raiffeisen-volksbank-aschaffenburg.de,~gestalterbank.de,~fehntjer-voba.de,~eu-banking.de,~litebit.eu,~raiba-ke-oa.de##.cookie-consent:not(body):not(html)`

### Possible fix:

```
forcetools-kepmar.eu#@#.cookie-consent-content
forcetools-kepmar.eu#@#.cookie-consent:not(body):not(html)
```

### Other problem filters:
* **Easylist Cookie List** / **Fanboy's Annoyance List** https://github.com/easylist/easylist/issues/13690/

`##.cookie-consent-content`
`##.cookie-consent-header`
`##div.cookie-consent`

* ~~**Frellwit's Swedish Filter** https://github.com/lassekongo83/Frellwits-filter-lists/issues/144/~~ _(FIXED)_

~~`##.cookie-consent:not(body):not(html)`~~

* **I don't care about cookies** _(NOTIFIED)_

`##.cookie-consent-content`
`##.cookie-consent-header`

--

### System info:
* OS/version: Windows 10 Pro (x64)
* Browser/version: LibreWolf v105.0.3-1 (x64)
* Adblock Extension/version: uBlock Origin v1.44.4

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Setting cookie alone was sadly not enough, they require a site-reload, so clicking on any item works (they reload the page themselves after clicking).

**Comment by THEtomaso** [comment]
> Setting cookie alone was sadly not enough, they require a site-reload, so clicking on any item works (they reload the page themselves after clicking).

Yeah, that seems to be the case if you click "**Accept required**".
But if you click "**Accept all**", the page reloads immediately!
