### ISSUE TITLE
[Android] Periscope app

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#1316]
https://play.google.com/store/apps/details?id=tv.periscope.android&hl=en

При включенном ADguard приложение не получает трансляции и не транслирует само. При этом устройство сильно греется.

https://blog.adguard.com/ru/misc/adguard-for-android-2-1-359.html#comment-2460412465

**Comment by Alex-302** [comment]
Не повторяется. Вряд ли проблема с фильтрами.
