### ISSUE TITLE
edition.cnn.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#131625]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.51

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://edition.cnn.com/travel/amp/vatican-museum-tourist-smashes-statues/index.html

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Anti-Facebook List

### Add your comment and screenshots

 Screenshots
<details><summary>Screenshot 1:</summary>

![2022-10-7_20-52-3](https://user-images.githubusercontent.com/29574622/194583449-434df3e4-8d1a-4456-b5b9-f4744711c3de.PNG)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reproduced. It is blocked by `edition.cnn.com##.AMPAd__component`
Please test in user filter.

**Comment by SeriousHoax** [comment]
> Not reproduced. It is blocked by `edition.cnn.com##.AMPAd__component` Please test in user filter.

It's working fine now. Weird because no filter update happened in between and tested on two browsers before creating the issue. Anyway, thanks. Closing the issue.
