### ISSUE TITLE
devian.tubemate.home

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#13173]
***Description***:

* **Current behaviour**: 

Some of the video files fail to download when AdGuard protection is enabled. Application hangs.

* **Expected behaviour**: 

AdGuard shouldn't affect the program's functionality

***Steps to reproduce the problem***:

1. Try to download any video file with AdGuard enabled

***System configuration***

**Filters:**

"English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter"

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 5.1.1
Browser:                               | N/A
AdGuard version:                       | 2.10.176
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | Speedy
HTTPS filtering (Android only):        | Enabled, whitelist mode
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 1071509

**Comment by Alex-302** [comment]
`Останавливается на 70-80-90%. Скорость закачки -ноль.`
это не из-за фильтров. У меня не повторяется.
