### ISSUE TITLE
 kinesis.eu-west-1.amazonaws.com breaks Daikin A/C

### ISSUE THREAD

**Issue by intrinseca** [AdguardTeam/AdguardFilters#131918]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

0.107.16

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.daikineurope.online.controller

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. The block of `kinesis.eu-west-1.amazonaws.com ` prevents Daikin air conditioning units from communicating with theor cloud service, partially breaking the Onecta app. Adding this as an exception restores functionality. 

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Update available in a few hours for DNS filters. Our DNS servers will take a bit longer to synchronize.
