### ISSUE TITLE
gaybeeg.info

### ISSUE THREAD

**Issue by gototheskinny** [AdguardTeam/AdguardFilters#132021]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.4

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gaybeeg.info/2022/04/02/lawson-james-grant-ducati-quit-jerkin-im-right-here-bareback-photoset-exclusive-2-apr/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard German filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, EasyList, EasyList Germany, EasyPrivacy, Fanboy's Annoyances, Web Annoyances Ultralist, I don't care about cookies

### Add your comment and screenshots

1. Download button stuck at loading not just this vid every vid. disabling adguard solves this issue

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@gototheskinny 
Unfortunately, I cannot reproduce this issue.
Please disable filter lists one by one, if you find which one causes that issue, then please re-enable it, open filterling log, reproduce issue, make a screenshot of filtering log with all blocked requests and upload it here.

**Comment by gototheskinny** [comment]
Ok, let me see.

**Comment by gototheskinny** [comment]
EasyPrivacy list is causing this issue. From now on I'll reset the Adguard app and disable every non-adguard list. Sorry to bother you guys, it's my fault.
