### ISSUE TITLE
[iOS] m.yelp.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1320]
There are ads throughout the page when viewing entries on yelp.com -- they even say "Ad" next to them but Adguard does not block them.

Missed ad on page:
http://m.yelp.com/biz/mall-of-america-bloomington

![image](https://cloud.githubusercontent.com/assets/15856304/12389257/4b1018ac-bde0-11e5-92cf-b4051d9b589c.png)

XNJ-779-59411

**Comment by Alex-302** [comment]
added to mobile filter
m.yelp.com##div[class*="yelp-ad"]

**Comment by Bohdan-SUP** [comment]
Not fixed on desktop version of the website:
![image2](https://cloud.githubusercontent.com/assets/14153331/12528786/1a02e6bc-c1ab-11e5-9612-1d7174074f9f.PNG)
![image1](https://cloud.githubusercontent.com/assets/14153331/12528787/1a06d182-c1ab-11e5-97a7-839e4441e844.PNG)

**Comment by Alex-302** [comment]
I don't see this ad without Adguard. Need the direct url

**Comment by evgeniy-ADG** [comment]
Please check: 
http://www.yelp.com/biz/howards-cafe-san-francisco?page_src=related_bizes

**Comment by Alex-302** [comment]
check this rule:
```
