### ISSUE TITLE
Cookiebot popup is not blocked

### ISSUE THREAD

**Issue by adrianmihalko** [AdguardTeam/AdguardFilters#132157]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

Latest from appstore

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.vatera.hu/konzolok-jatekszoftverek/jatekszoftverek/ps4-playstation4-jatekok/index-c12123.html?qt=1&td=on&q=Knowledge+is+power+Magyar+nyelvű+PS4

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. <comment>
For some reason Cookiebot popup is not blocked. I attach screenshot:

![9903F7E8-C4E4-46E9-9371-7DF907464810](https://user-images.githubusercontent.com/733361/195898371-23701df0-5b86-47ff-84df-ff91ddad324e.png)
![606112B2-E0BD-422C-B565-48A92D0DCCAA](https://user-images.githubusercontent.com/733361/195898401-5ebefcc5-f597-420a-8757-8bf69a509c63.png)

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@adrianmihalko Hi, could you please turn on the AdGuard Annoyances Filter, clear your browser cache and check if the cookie message still appears on this page?

**Comment by adrianmihalko** [comment]
Thanks. It is working now. It is not obvious for first look that “Safari Protection” hides more menu underneath. I would add an arrow or something here to sign that there are more settings here.

**Comment by jellizaveta** [comment]
You're welcome!  I will forward your feedback to the developers.
