### ISSUE TITLE
[iOS] m.fanfiction.net missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1322]
Missed ad on page:
https://m.fanfiction.net/s/10888418/15/
![image](https://cloud.githubusercontent.com/assets/15856304/12391773/c72da91a-bdf2-11e5-9699-dd35c53284c8.png)

QGP-924-62191

**Comment by Alex-302** [comment]
It is Google Ads banner. Don't understand why it is not blocked on his device/
