### ISSUE TITLE
namu.wiki

### ISSUE THREAD

**Issue by Githubmaniak** [AdguardTeam/AdguardFilters#132431]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.4(965)

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://namu.wiki/w/%EC%9D%8C%ED%8C%8C%20%ED%81%AC%EB%9E%98%EC%8B%9C%20%EB%B2%84%EA%B7%B8?from=%EB%BD%81%EC%B0%A1

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, List-KR, YousList

### Add your comment and screenshots

1. <comment>
The embedded player detects AdGuard in the namu.wiki document where Kakao TV's video is attached.
>@@||videoads.kakao.com^
>@@||videoads.kakao.com/adserver/api/v2/vmap$domain=tv.kakao.com|play->tv.kakao.com|kakaotv.daum.net|namu.wiki
>@@||kakaotv.daum.net/embed/player/image/ads.png$domain=tv.kakao.com|play-tv.kakao.com|kakaotv.daum.net|namu.wiki
namu.wiki,kakaotv.daum.net,play-tv.kakao.com,tv.kakao.com#@#ins.kakao_ad_area
namu.wiki,kakaotv.daum.net,play-tv.kakao.com,tv.kakao.com#@##adBlockPixelTag
namu.wiki,kakaotv.daum.net,play-tv.kakao.com,tv.kakao.com#@#.banner_ad
@@||tv.kakao.com/embed/player/image/ads.png$domain=tv.kakao.com|play-tv.kakao.com|kakaotv.daum.net|namu.wiki

Even if you add the above user rules, if you exclude Kakao TV's website, AdGuard is detected and blocked.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![4FE947B4-F034-4680-BB0F-855546BF74FA](https://user-images.githubusercontent.com/103377449/196236384-d08d7a29-40d7-4e78-bc2f-9a53f66116bf.png)

</details>

<details><summary>Screenshot 2:</summary>

![1BB066A5-5C34-464B-9058-4704A19A16B3](https://user-images.githubusercontent.com/103377449/196236461-0a82d930-f0a4-414b-997c-ac1296db7319.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
I cannot reproduce with AdGuard Browser Extension and the following user rules to simulate @Githubmaniak's AdGuard configuration [^1]. 

```adblock
@@||videoads.kakao.com/adserver/api/v*/vmap|$domain=tv.kakao.com|play-tv.kakao.com|kakaotv.daum.net
@@/embed/player/image/ads.png$domain=tv.kakao.com|play-tv.kakao.com|kakaotv.daum.net
@@||tv.kakao.com^$jsinject
/embed/player/image/ads.png$redirect=2x2-transparent.png,domain=tv.kakao.com|play-tv.kakao.com|kakaotv.daum.net,badfilter

```

[^1]: I don't have any Apple device currently. And, @Githubmaniak uses free version of AdGuard for iOS.

**Comment by Alex-302** [comment]
It seems wrong screenshot. No problems on namu.wiki
