### ISSUE TITLE
namu.wiki

### ISSUE THREAD

**Issue by Githubmaniak** [AdguardTeam/AdguardFilters#132580]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS, AdGuard for iOS

### AdGuard version

4.4.4(965)

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://namu.wiki/w/%EB%B9%84%EC%94%A8%EC%B9%B4%EB%93%9C#s-8

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, List-KR, YousList

### Add your comment and screenshots

1. <comment>
Kakao TV's embedded player detects AdGuard.  I added a rule word to solve this, but it still detects except for the main player.  I wonder if it's an iOS-only problem or if it's the same on Android.
2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

![1A27584B-6851-4D57-8E82-E8EF0D19CEF1](https://user-images.githubusercontent.com/103377449/196718659-d1fd120f-afe5-4217-8d1f-a85f96fb830c.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Fixed
