### ISSUE TITLE
Adguard breaks Google Play Music extension functions

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1326]
It simply doesn't upload any music and returns the error: http://prntscr.com/9rq752

Steps to reproduce:
1. Install the extension in Chrome, for instance, [this one](https://chrome.google.com/webstore/detail/google-play-music/icppfcnhkcmnfdhfhphakoifcfokfdhg?hl=en
2. Log in to the service)
3. Go to settings and choose Upload music or just drag and drop
4. See the error;

Tested and reproduced with the basic filters set. The Stealth mode is off.

UDF-273-61522

**Comment by evgeniy-ADG** [comment]
UPD. Code 16: https://productforums.google.com/forum/#!topic/play/kN5SYF94Aj4
 According to the customer, that adding the site address to the list of HTTPS exclusions doesn't help.

**Comment by Alex-302** [comment]
I need remote access.

**Comment by evgeniy-ADG** [comment]
894 557 678
p7vh54

Im kinda ready but let me know

**Comment by Alex-302** [comment]
@evgeniy-ADG 
I'm ready too)

**Comment by evgeniy-ADG** [comment]
ДОВАЙ :)

**Comment by Alex-302** [comment]
Сегодня/завтра постараюсь починить

**Comment by Alex-302** [comment]
Без логина в самом хроме не пускает, делать этого не буду чтоб твои настройки не потёрлись.
Но проблема вроде ясна - из-за подмены сертификата. Проверь плиз с выключенной фильтрацией HTTPS.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
вышли плиз логи адгарда засегодня из programdata(только нужно будет службу остановить)

**Comment by evgeniy-ADG** [comment]
[Logs.zip](https://github.com/AdguardTeam/ExperimentalFilter/files/96586/Logs.zip)
с выключенной фильтрацией HTTPS проверю завтра.

**Comment by evgeniy-ADG** [comment]
@Alex-302  Без фильтрации HTTPs отлично всё работает.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Из логов ничего не понял. Можно будет подключиться как-нибудь?

**Comment by evgeniy-ADG** [comment]
@Alex-302 сегодня в то же время давай

**Comment by Alex-302** [comment]
@evgeniy-ADG 
ок

**Comment by Alex-302** [comment]
@evgeniy-ADG 
ну что, продолжим?:)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
нет новостей?
Я там случайно залогинился)

**Comment by evgeniy-ADG** [comment]
@Alex-302 залогинься, пожалуйста и потестируй у себя, у меня там нет никаких таких настроек, что можно сбить. акк искл-но для плей музыки. так будет быстрее и проще, чем с TeamViewrом.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
а стёр данные для входа:)
Но есть проблема - когда логинился, музыка требовала подтвердить местоположение вводом кредитки, даже с украинским прокси...
Если не сложно - запиши плиз фиддлером сеанс, сохрани и пришли мне. Сделаю правил и пришлю для проверки.

**Comment by evgeniy-ADG** [comment]
окей, вечером попытаюсь, если что - спрошу.

**Comment by evgeniy-ADG** [comment]
[google play music.zip](https://github.com/AdguardTeam/ExperimentalFilter/files/138709/google.play.music.zip)
@Alex-302 если я не о что-то сделал, то дай скажи, пож-та, что жать :) Запустил фидлер, повторил проблему, потом file -> save -> all sessions.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Вроде всё правильно.
Попробуй оба
```
@@||client-channel.google.com^
@@||client-channel.google.com^$document
```

**Comment by Alex-302** [comment]
Ещё можно включить Фиддлер непосредственно перед перетягиванием файла, и сразу после ошибки нажить F12 в Фиддлере. Так меньше мусора будет.

**Comment by evgeniy-ADG** [comment]
сделал с ф12, те правила что-то не помогли
[google play music 2.zip](https://github.com/AdguardTeam/ExperimentalFilter/files/139261/google.play.music.2.zip)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
А вот такие проверь, для начале с первыми
```
@@||login.live.com/oauth
@@||ssw.live.com/UploadData.aspx
```
если помогло - старые выключи оставив эти.

**Comment by evgeniy-ADG** [comment]
@Alex-302  не-а
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13268156/8c7967b0-da89-11e5-99b4-be06bfe69987.png)

**Comment by Alex-302** [comment]
эх, ещё бы глянуть удалённо

**Comment by evgeniy-ADG** [comment]
@Alex-302 

894 557 678
pd388c

**Comment by Alex-302** [comment]
@ameshkov 
пробовали исключить из SSL фильтрации все домены, участвующие в процессе загрузки - всё равно ругается на "невозможность установить безопасное соединние"
Что ещё можно попробовать?

**Comment by ameshkov** [comment]
Слушай, ну вроде больше ничего не может влиять вообще.

Я думаю мы не все домены видим, которые участвуют (может в журнал просто не попадают).
Наверное и с фиддлером тоже будет не все видно, но можно попробовать им отследить.

Еще есть вариант. Так как это расширение, то все запросы можно увидеть на его background page.

Идешь на chrome://extensions, переключаешься в режим разработчика, находишь нужное расширение, открываешь его background page, переключаешься на вкладку Network там.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
попробуем ещё?

**Comment by Alex-302** [comment]
@ameshkov 
помогло только полное исключение доменов из SSL фильтрации
googleapis.com - этот только в расширении был виден, урл авторизации
play.google.com

**Comment by ameshkov** [comment]
А есть какие-то фильтры, которые урлы на googleapis блокируют?

**Comment by Alex-302** [comment]
в счётчиках
```
||googleapis.com/generate_204
```
в английском
```
||storage.googleapis.com/*/bnr*.$domain=datafilehost.com
||imasdk.googleapis.com^$third-party
||googleapis.com/dfh/$image,domain=datafilehost.com
```

**Comment by ameshkov** [comment]
Фигово, значит не стоит его просто так в исключения добавлять

**Comment by Alex-302** [comment]
Пока ждём?

**Comment by evgeniy-ADG** [comment]
> Не могу добавить сервис Google Play Music в исключения AdGuard (не магазин музыки, а сам плеер, расположенный по адресу play.google.com/music. Сам адрес добавляется в белый список, однако значок помощника продолжает отображаться на страницах сервиса. Пробовал блокировать и конкретную страницу этого сервиса и весь сайт play.google.com. Результата никакого. Опять же, не знаю, идет ли фильтрация трафика или это баг самого помощника и фильтрация все-таки отключается. Есть некоторые проблемы с этим сервисом. Периодически вылезает уедомление, что не удалось установить безопасное подключение с сервером и с загрузкой музыки на сервис тоже возникают трудности. Из-за того, что не уверен в AdGuard - не знаю, в чем заключается проблема. То ли эти проблемы, вызванные AdGuard, то ли сам сервис Play Music работает не корректно. Использую десктопную версию AdGuard (6.0.226.1108). Операционная система: Windows 10 Версия Google Chrome: 50.0.2661.102 m (64-bit)

**Comment by Alex-302** [comment]
попробуй это
https://github.com/AdguardTeam/ExperimentalFilter/issues/1326#issuecomment-188886823

**Comment by evgeniy-ADG** [comment]
передал юзеру.

**Comment by Alex-302** [comment]
ну что там?

**Comment by evgeniy-ADG** [comment]
ничего

**Comment by Alex-302** [comment]
Отсутствие помощника - не показатель отсутствия фильтрации. 
После добавления play.google.com в исключения HTTPS домен полностью перестаёт фильтроваться(даже не подменяется сертификат).

@ameshkov что делать будем с этой проблемой?

**Comment by evgeniy-ADG** [comment]
** 1354088 ** another complaint, any news?

**Comment by Alex-302** [comment]
@evgeniy-ADG 
у меня доступа к загрузке музыки нет.
Не помнишь, какие домены исключали когдя я к тебе подключался? 
Исключение HTTPS play.google.com помогает?

**Comment by evgeniy-ADG** [comment]
Не помню, но кастомер выше писал

> о выручило добавление (play.google.com/music) и/или (play.google.com) именно в фильтр https.

**Comment by Alex-302** [comment]
А проверь плиз ещё, именно с play.google.com в исключениях HTTPS, чтоб быть полностью уверенным.

**Comment by zebrum** [comment]
@Alex-302 как дела?

**Comment by evgeniy-ADG** [comment]
@zebrum @Alex-302 @ameshkov we keep receiving complaints, please advise.

**Comment by Alex-302** [comment]
Решение плохое, гугловую рекламу частично разблокирует и может привести в к появлению рекламы в плеерах на сайтах.
На пробу - добавить в исключения HTTPS:
```
googleapis.com
```
