### ISSUE TITLE
Adguard bug report language specific stop you from ctrl click

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/AdguardFilters#132769]
@asaf3023 commented on [Thu Oct 20 2022](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2212)

### Steps to reproduce

1.Turn on Adguard french filter in language specific Filters
2.you cant ctrl, middle left click and open a new tab with the menu on some websites (im trying to ctrl open https://9anime.to )
3. done

### Expected behavior
open a new tab for the link you clicked on

### Actual behavior
it open for maybe a second a tab and closes it really fast

<details><summary>Screenshot:</summary>

 https://youtu.be/YUh7TPDOjHU

</details>

### Customer ID 
 i didnt get a customer id from reporting it through the application but i did get a ticket number my ticket number is 665593

### Your environment

* Environment name and version: (e.g. Firefox 106.0.1 (64 bits))
* Operating system and version: (e.g. Windows 10 Pro, v. 21H1, build 19043.2006, Experience  Windows Feature Experience Pack 120.2212.4180.0)

 i hope you have a good day :)

**Comment by Alex-302** [comment]
Please create a report using AdGuard
https://kb.adguard.com/en/technical-support/reporting-tool
