### ISSUE TITLE
change.org

### ISSUE THREAD

**Issue by kmnvq** [AdguardTeam/AdguardFilters#133026]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.37

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.change.org/account_settings/manage_email

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

**1 - E-mail tracking** - `click.e.change.org`

Steps to reproduce:
Sign up on change.org and check the incoming mail.

<details><summary>screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/197428047-c57ddb5e-7a96-4093-900e-880a740d3aed.png)

</details>

---

**2 - Other trackers**

After login, click on the link below

`https://www.change.org/account_settings/manage_email`

```
change.org/NsLC0Hv5/xhr/api/v2/collector
change.org/api-proxy/-/event_tracker?_csrf=
airbrake.io
```

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
> airbrake.io

As I recall, this is not a tracker and we have an exclusion for our DNS.
