### ISSUE TITLE
[iOS] forums.macrumors.com is distorted

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1330]
Adguard renders forums.macrumors.com almost unreadable.

![image](https://cloud.githubusercontent.com/assets/15856304/12413795/075bb980-be9a-11e5-84a9-30c2609e27cb.png)

IUI-308-63681

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by Bohdan-SUP** [comment]
Ad is not blocked:
![image1](https://cloud.githubusercontent.com/assets/14153331/13372576/9e95edd6-dd51-11e5-8379-08c046c7284b.PNG)

**Comment by evgeniy-ADG** [comment]
@Alex-302

**Comment by Alex-302** [comment]
@evgeniy-ADG 
try this rule
```
##iframe[width="300"][height="250"]
```

**Comment by Alex-302** [comment]
bump

**Comment by worldsdream** [comment]
This is an old thread, but I saw it's open. 

I just checked forums.macrumors.com on my iOS and logged into the forum section, browsed around. There are no ads and everything is visible and correct. 

You can mark this as  resolved!
