### ISSUE TITLE
embed.kijk.nl

### ISSUE THREAD

**Issue by EchoDev** [AdguardTeam/AdguardFilters#133124]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock 1.44.4

### What type of problem have you encountered?

Website or app doesn't work properly, AdGuard gets detected on a website

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://tvblik.nl/hart-van-nederland/23-oktober-2022

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. Visiting sites that have embedded videos from https://embed.kijk.nl (Example: https://tvblik.nl/hart-van-nederland/23-oktober-2022 ) triggers an anti-adblock warning on/from embed.kijk.nl. This anti-adblock warning is not seen when viewing straight from kijk.nl

This is triggered by the rule 

`##.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links:style(display: block !important;)`

Creating an exception as 

`embed.kijk.nl#@#.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links:style(display: block !important;)`

Fixes the issue with no adds. 

3. Screenshots
<details>
![image](https://user-images.githubusercontent.com/3149302/197776657-775da198-5115-40f9-ad2b-82c334615195.png)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
Hello @EchoDev
Please enable AdGuard Dutch filter. The anti-adblock rules for Dutch sites are there.
