### ISSUE TITLE
rebelmouse.com

### ISSUE THREAD

**Issue by macbugs** [AdguardTeam/AdguardFilters#133168]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

not applicable

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other(specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

rebelmouse.com

### What filters do you have enabled?

AdGuard French filter

### Add your comment and screenshots

`cdn.rebelmouse.com` hosts legit business & engineering news sites like:

spectrum.ieee.org (→ spectrum.ieee.org.cdn.rebelmouse.com)
[www.protocol.com](http://www.protocol.com/) (→ [www.protocol.com.cdn.rebelmouse.com](http://www.protocol.com.cdn.rebelmouse.com/))

_["The main domains www.rebelmouse.com and rebelmouse.com occur in easylist-french, adguard-french-filter and lightswitch-ads-tracking. You should submit an issue to these list projects so it gets unblocked there."](https://github.com/EnergizedProtection/block/issues/956#issuecomment-1287659399)_
___
[6 code results in github.com/AdguardTeam](https://github.com/search?q=org%3AAdguardTeam+rebelmouse&type=code)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
This rule is loaded from Liste-FR. @smed79 Could you please take a look?
