### ISSUE TITLE
[Android] AccuWeather app can't update

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1331]
https://play.google.com/store/apps/details?id=com.accuweather.android&hl=en

The firewall blocks the useful apps like accuweather after the last update, this app can't be updated when the firewall is activated. 

NNG-852-68048

**Comment by Alex-302** [comment]
He may try with enabled filtering, protection, and disabled all filters. If it will not work, file the bug

**Comment by Alex-302** [comment]
Не пойму что именно не работает. Обновление погоды или программы?

**Comment by evgeniy-ADG** [comment]
Погода не обновляется, как я понял. Я уточню и дополню.

**Comment by Alex-302** [comment]
желательно чтоб описал где и как.
Если проблема повторится у него, попроси выключить все фильтры и проверить снова. Если не повторится - пусть включает по одному с проверкой. Если и без фильтров будет проблема, то нужно будет открывать баг.

**Comment by evgeniy-ADG** [comment]
Сделаю. Я за ним слежу :) Пока нет ответа.
