### ISSUE TITLE
Block graph.facebook.com in Mercado Libre app

### ISSUE THREAD

**Issue by sdgrs546547Q** [AdguardTeam/AdguardFilters#133298]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.51

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

||graph.facebook.com^$app=com.mercadolibre

### What filters do you have enabled?

AdGuard Mobile Ads filter, AdGuard Spanish/Portuguese filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

Hello! The app of "Mercado Libre" in Android connects every time when you open the app connects to graph.facebook.com to track you and give personalized ads. I think that you can add this rule "||graph.facebook.com^$app=com.mercadolibre" to a filter of AdGuard, like AdGuard for Spanish/Portuguese (because MercadoLibre is a major Latin America company) or AdGuard Tracker Protection. Thanks!

<details><summary>Screenshot 1:</summary>
![IMG_20221026_205939](https://user-images.githubusercontent.com/79816807/198160622-f5e79c9e-a554-4b6d-afd5-9a63607c43f7.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Cannot install the app https://play.google.com/store/apps/details?id=com.mercadolibre

Does the app offer a facebook login?

**Comment by sdgrs546547Q** [comment]
> Cannot install the app https://play.google.com/store/apps/details?id=com.mercadolibre
> 
> Does the app offer a facebook login?

No, the app doesn't offer a Facebook login, only with Email. 
![IMG_20221027_081851](https://user-images.githubusercontent.com/79816807/198270915-a6b102f2-d179-4a90-9443-1589377a48bf.jpg)
![IMG_20221027_081829](https://user-images.githubusercontent.com/79816807/198270926-bb8235aa-28ee-4884-b5ff-8bba4dcb268c.jpg)

**Comment by sdgrs546547Q** [comment]
Also, you can add this rule: "||graph.facebook.com^$app=com.mercadopago.wallet" . Is a similar app of Mercado Libre but it focus on wallet and also doesn't has Facebook login, because it uses the same account of Mercado Libre. Thanks
