### ISSUE TITLE
AdGuard Tracking protection blocks comment counter on welt.de

### ISSUE THREAD

**Issue by SebastianRasch** [AdguardTeam/AdguardFilters#133357]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.9.0.1206

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.welt.de/politik/ausland/article241812759/Ukraine-News-USA-warnen-Russland-vor-Angriffen-auf-ihre-Satelliten.html

### What filters do you have enabled?

AdGuard Tracking Protection filter

### Add your comment and screenshots

1. When AdGuard Tracking Protection is active, the floating comment counter to the left is always 0, not matter how many comments there are.

2. Screenshots
<details><summary>Screenshot 1, Tracking Protection active:</summary>

<img width="1036" alt="Screenshot 2022-10-27 at 20 26 54" src="https://user-images.githubusercontent.com/22617697/198370080-01de86da-ef9d-4d7c-8a77-101f243ea299.png">

</details>

<details><summary>Screenshot 2, Tracking Protection inactive:</summary>

<img width="1045" alt="Screenshot 2022-10-27 at 20 27 57" src="https://user-images.githubusercontent.com/22617697/198370172-4f1955cb-e1f7-406b-8984-78c5e4f2b93f.png">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by SebastianRasch** [comment]
Seems to work now? Maybe the filter was already fixed since I posted this. I'm gonna close this for now, let's hope it stays this way 🙂

**Comment by AdamWr** [comment]
It looks like that it's related to this issue - https://github.com/AdguardTeam/AdguardFilters/issues/133210 and it has been fixed 2 days ago - https://github.com/AdguardTeam/AdguardFilters/commit/1218b9600bf4cf985bfb3ac14e7d711d011e1bd8
