### ISSUE TITLE
Add filter for technologyreview.com

### ISSUE THREAD

**Issue by jxxp9** [AdguardTeam/AdguardFilters#133333]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Hi, I don't know the syntax but here are my filters for that technologyreview.com paywall

```
! 2022-10-27 https://www.technologyreview.com
www.technologyreview.com###piano__pinnedFooter
www.technologyreview.com##.body__pinnedScrollPaywall--2gf0u::after:style(background: unset !important)
www.technologyreview.com##.body__pinnedScrollPaywall--2gf0u:style(overflow: unset !important)
```

Please add them, thanks

### Proposed solution

See above

**Comment by Alex-302** [comment]
Not reproduced. Where do you live and which filters do you use?

For reporting filtering issues please read this: https://kb.adguard.com/en/technical-support/reporting-tool

**Comment by jxxp9** [comment]
Italy, you can try it here https://www.technologyreview.com/2022/10/26/1061636/electric-vehicles-cars-climate-change-transit/ for instance (the page has paywall). I can confirm they work for that page

**Comment by Alex-302** [comment]
Hmm. Still not reproduced.
@AdguardTeam/filters-maintainers Could you please check?

**Comment by BlazDT** [comment]
Tried different articles and VPN, no paywall on my Android with only our filters.

Which filters and product are you using?

**Comment by jxxp9** [comment]
@BlazDT I've all filters enabled (included all cosmetic) + ITA easy list

**Comment by BlazDT** [comment]
Those are way too many filters. Please try only with AdGuard filters.

**Comment by BlazDT** [comment]
Question still stands on which product you are seeing such paywall which no screenshot was provided.

**Comment by AntiAdvert** [comment]
![image](https://user-images.githubusercontent.com/117537631/200918348-e0923e8a-5cab-4430-aaca-4245724f971d.png)
I haven't encountered a paywall, but hmm..

**Comment by jxxp9** [comment]
I'll investigate, closing for now

**Comment by AntiAdvert** [comment]
@jxxp9 Do you have the `AdGuard Annoyances Filter` enabled?

**Comment by jxxp9** [comment]
@AntiAdvert yes
