### ISSUE TITLE
FoxNews.com - Broken video playback (AdGuard English filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#13344]
**Description**:
Video playback is broken at FoxNews.com

**Example**:
`http://www.foxnews.com/politics/2018/03/17/trumps-lawyer-calls-for-russia-probe-to-be-shut-down.html`

**Screenshot**:

![foxnews](https://user-images.githubusercontent.com/9382674/37561547-dd2be190-2a48-11e8-8017-43b26e6e91e7.jpg)

**Problem filter**:
AdGuard English filter

**Problem rule**:
`||global.fncstatic.com/static/*/OutbrainWidgetConnector.js`

**Possible fix**:
`@@fncstatic.com/static/*/OutbrainWidgetConnector.js$domain=foxnews.com`

--

Operating system: Windows 8.1 Pro (x64)
Browser: Pale Moon v27.8.1 (x64)
Blocker: uBlock Origin v1.15.16

**Comment by lakrsrool** [comment]
If I disable EasyPrivacy in uBlock Origin the page loads --- so I would assume if this is all I have to do to get the page to load then EasyPrivacy must be what is interfering.  I've gone ahead and tested another ad-blocker with EasyPrivacy subscription (ABPrime) and the same thing occurs --- that is with EasyPrivacy enabled the page fails to load with EasyPrivacy disabled the page loads without any issue.

Are you saying that you are using the EasyPrivacy 3rd-party subscription and the page still loads for you?

If so what version of EasyPrivacy are you using?

I have had this problem occurring for recent versions of EasyPrivacy.

**Comment by THEtomaso** [comment]
> Are you saying that you are using the EasyPrivacy 3rd-party subscription and the page still loads for you?

Yes

> what version of EasyPrivacy are you using?

201803180106

**Comment by lakrsrool** [comment]
I am using EasyPrivacy Version: 201803171328  (and previous version(s) had the same issue) -- I'm presuming your version goes back far enough that the issue does not exist perhaps.

**Comment by THEtomaso** [comment]
201803180106 is currently the latest version available.
At least when updating from uBO.

**Comment by lakrsrool** [comment]
Okay -- by using just HTML5 and not HTML5 + MSE and if I double-click on the video it WILL play with EasyPrivacy enabled.

Sorry for all the confusion -- apparently this was the problem.

Thanks for all the input.

**Comment by Alex-302** [comment]
fixed
