### ISSUE TITLE
Blitz Application

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdguardFilters#133493]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.11 Nightly 22

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Desktop

### Where is the problem encountered?

\AppData\Local\Programs\Blitz\Blitz.exe

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

Hi, in [Blitz application](https://blitz.gg/download) have ads, so i added the Blitz app to the list of apps filtered with `AdGuard Windows` and it's blocked ads in blitz app, but the blitz app have HUD (Heads Up Display) overlay in-game feature for the games like [League Of Legends](https://support-leagueoflegends.riotgames.com/hc/en-us/articles/360001609327-League-of-Legends-Download-Links-Mac-PC), this is also blocked. (Incorrect-blocking)

<details><summary>Details:</summary>

| Without AdGuard | With AdGuard |
| :---: | :---: |
| ![AD](https://user-images.githubusercontent.com/56846906/198749267-75cfacdb-df83-479a-8ea2-b21fb9b6359e.png) | ![AD2](https://user-images.githubusercontent.com/56846906/198751844-1c9192c5-843a-4877-99ef-adbd3231eca9.png) |
| **Overlay in-game** | **No overlay in-game** |
| ![3](https://user-images.githubusercontent.com/56846906/198749607-51bd1e61-9426-4e20-ba46-8cc8c7024885.png) | ![4](https://user-images.githubusercontent.com/56846906/198749902-9b3ea2a0-2b73-4f33-b61a-6d45e6b6347d.png) |

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Do you have Stealth Mode enabled?

**Comment by jellizaveta** [comment]
Is filtering enabled only for Blitz or for LOL too?

**Comment by jellizaveta** [comment]
Could you please make screenshots of the filtering log of this issue in app?

**Comment by jellizaveta** [comment]
Okay. Thank you for your reply. Yes, please, write the steps for reproducing

**Comment by jellizaveta** [comment]
I was able to repeat the issue. To display layouts you need to remove the application from the list of https filtering. Ads will still be blocked, but nothing will break.
