### ISSUE TITLE
clien.net

### ISSUE THREAD

**Issue by hotdog5785** [AdguardTeam/AdguardFilters#133508]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

newest

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

clien.net

### What filters do you have enabled?

List-KR

### Add your comment and screenshots

최근에 일어났던 댓글 새로고침 오류 필터 업뎃 후 클리앙에서 또 발생 (korean website)

www.clien.net #132468 

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
@hotdog5785 
Can you attach a screenshot and URL?
스크린샷과 URL를 첨부해주실 수 있으시나요?

**Comment by hotdog5785** [comment]
@piquark6046 

![캡처](https://user-images.githubusercontent.com/99060747/198814425-3c9f2555-7e57-4cda-8107-99e77d63c998.JPG)
![캡처2](https://user-images.githubusercontent.com/99060747/198814426-bae3f1a0-b609-4244-9e45-2a678a8e5102.JPG)


https://www.clien.net/service/board/park/17668705?type=recommend

**Comment by hotdog5785** [comment]
@piquark6046 

ios 사파리에서도 테스트 해봤습니다
백그라운드 새로고침 꺼놔서 필터 업뎃 안된 상태에서는 댓글이 보였는데, 방금전 수동으로 최신으로 업뎃하니까 댓글이 사라져버렸네요

![B249EACD-E3C1-4033-A38D-8A74CDCEBC98](https://user-images.githubusercontent.com/99060747/198814675-6178e000-b7bb-4a88-a5a8-b78887075d25.png)
![4E0C0974-B323-4B33-A869-D70ACFB26D05](https://user-images.githubusercontent.com/99060747/198814677-bafb4587-002f-41c4-a318-ae673944a8eb.png)

**Comment by piquark6046** [comment]
@hotdog5785 
The issue is caused by YousList not List-KR.
Please remove YousList or wait until the issue is fixed.
이 이슈는 List-KR이 아닌 YousList에 의해 발생합니다.
YousList를 제거하시거나 이 이슈를 해결하기까지 기다려주세요.

---

CC: @yous

**Comment by yous** [comment]
https://github.com/yous/YousList/commit/b4c4a50e6d4ae684047283a120557544427f6494 커밋에서 문제 되는 규칙 업데이트했습니다.
