### ISSUE TITLE
$network with regex filter issue

### ISSUE THREAD

**Issue by Adguard2586** [AdguardTeam/AdguardFilters#133749]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

My issue is that the app doesnt work with the rules that i usually set in my devices.
First I blocked every port with
/.+/$network
Than I unlocked the ports:
53 80 443 853 3000 5443
With @@*: [port]^$network

But I can t surf for dns problems, what i'm missing?
I'm on an android device with the dedicated vpn to adguard.

Is it possible to create a dynamic filtering with the input closed (or drop)?

### Proposed solution

No solution guessed

**Comment by DandelionSprout** [comment]
It seems that the syntax for `$network` is pretty picky, but I *think* I got these to work by using asterisk wildcarding instead of RegEx:
```
*$network
@@*:53^$network
@@*:80^$network
@@*:443^$network
@@*:853^$network
@@*:3000^$network
@@*:5443^$network
```

**Comment by Adguard2586** [comment]
Sorry but that set of rules does not work. Seems that adguard does not receive the dns request query

**Comment by jellizaveta** [comment]
This rule breaks `@@*:53^$network` the DNS filtering, you can use a regular expression in which you can specify which ports should not be blocked
`/.+:(?!53|433|80|853|3000|5443)[0-9]+/$network`

**Comment by jellizaveta** [comment]
You can use a regular expression with exclusion of the necessary ports 
`/^.+:(?!53|853|3000|5443|443|80)[0-9]{2,6}$/$network`
