### ISSUE TITLE
Unblock https://animevsub.ml

### ISSUE THREAD

**Issue by tachibana-shin** [AdguardTeam/AdguardFilters#133875]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0.75

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://app.animevsub.ml

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, Filter unblocking search ads and self-promotion, KAD - Anti-Scam, Dandelion Sprout's Annoyances List, Legitimate URL Shortener

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Block WebRTC, Block Location API, Mask your IP address (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests

### Add your comment and screenshots

1. This is an open source application download site to watch Anime online
Source code: https://github.com/anime-vsub/app
2. Screenshots
<details><summary>Screenshot 1:</summary>
![Screenshot_2022-11-02-21-51-20](https://user-images.githubusercontent.com/45375496/199525114-c05b25fe-f288-453e-9cf3-58cbebbb0e0d.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
The issue is caused by Dandelion Sprout's Annoyances List, I reported to @DandelionSprout about it.

**Comment by DandelionSprout** [comment]
To the OP in particular: The site should work normally after clicking the "Proceed anyway" button, but I'll make sure to analyse the site for a potential permanent whitelisting.

**Comment by iam-py-test** [comment]
> `https://app.animevsub.ml/`

I'm not getting any resolution for that domain
![image](https://user-images.githubusercontent.com/84232764/199618969-0e5866a1-29ab-460e-a49b-28b44c0e2bc7.png)
https://sitecheck.sucuri.net/results/app.animevsub.ml
![image](https://user-images.githubusercontent.com/84232764/199619169-fe75a172-53e6-4125-ac52-d40d61438ade.png)
![image](https://user-images.githubusercontent.com/84232764/199619262-0de77ff1-8ce0-410a-88ed-e18ac6600e8f.png)

**Comment by DandelionSprout** [comment]
I could've sworn that the domain led to what seemed to be a Vietnamese manga sub team's project page soon after Sergey told me to check it, but now I too seem unable to load the page.

**Comment by iam-py-test** [comment]
> I could've sworn that the domain led to what seemed to be a Vietnamese manga sub team's project page soon after Sergey told me to check it, but now I too seem unable to load the page.

Probably temporary outage. Still strange that there aren't any Google results for it.

**Comment by tachibana-shin** [comment]
> > I could've sworn that the domain led to what seemed to be a Vietnamese manga sub team's project page soon after Sergey told me to check it, but now I too seem unable to load the page.
> 
> Probably temporary outage. Still strange that there aren't any Google results for it & VT didn't even know it existed before today.

oh i am also not reachable i think it is a global problem of the DNS server. in my country vercel.com is also not accessible. strange

**Comment by tachibana-shin** [comment]
> > I could've sworn that the domain led to what seemed to be a Vietnamese manga sub team's project page soon after Sergey told me to check it, but now I too seem unable to load the page.
> 
> Probably temporary outage. Still strange that there aren't any Google results for it & VT didn't even know it existed before today.

I think this is a DNS error i moved the domain to https://app.animevsub.ga please check again

**Comment by tachibana-shin** [comment]
For any content testing request hidden please see its source code here: https://github.com/anime-vsub/anime-vsub.github.io

for the domain animevsub.ml it's weird i checked it all day today but still can't figure out what's causing the outage
