### ISSUE TITLE
Annoyances filter breaks `https://www.androidacy.com/downloads/`

### ISSUE THREAD

**Issue by soredake** [AdguardTeam/AdguardFilters#133858]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.44.4

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.androidacy.com/downloads/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1. How site looks with annoyances filter

2. How it should look

3. This site detects firefox, and shows prompt every time requiring you to press "Continue" in order for site to load, annoyances filter blocks this prompts, and site does not load further

<details><summary>Screenshot 1:</summary>

![изображение](https://user-images.githubusercontent.com/5204968/199435039-fd6dec3c-2f00-4849-85c7-75d8fae4dbcf.png)
</details>

<details><summary>Screenshot 2:</summary>

![изображение](https://user-images.githubusercontent.com/5204968/199435173-54eb3d92-8f31-4242-a8d8-7d8d8ea97e23.png)

</details>

<details><summary>Screenshot 3:</summary>

![Снимок экрана 2022-11-02 100722](https://user-images.githubusercontent.com/5204968/199435545-6a23c584-f8ff-4fdf-9ef1-ce868478e051.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
