### ISSUE TITLE
Neads.co

### ISSUE THREAD

**Issue by noagencyio** [AdguardTeam/AdguardFilters#133960]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://neads.co

### What filters do you have enabled?

AdGuard French filter

### Add your comment and screenshots

Hi,

My domain (neads.co) is banned by "AdGuard Français".
How can i fixed that ?

Thank you guys !

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.

**Comment by noagencyio** [comment]
Sorry, the website is still broken

**Comment by AdamWr** [comment]
Unfortunately, I cannot reproduce it.
Website looks fine on my end with AdGuard + `AdGuard French filter` enabled.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/200283684-9d56b65f-76ea-4ecd-8bd8-b309031f20b4.png)

</details>

What exactly is broken?
Did you update filters?
