### ISSUE TITLE
Ahlsell.* - Sites won't load (Adguard's Annoyances filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#13392]
**Affected sites**:
```
https://www.ahlsell.dk/
https://www.ahlsell.fi/
https://www.ahlsell.no/
https://www.ahlsell.se/
```

**Issue**:
The sites won't load

**Problem filter**:
Adguard's Annoyances filter

**Problem rule**:
`##.accept-cookies`

**Possible fix**:
`ahlsell.*#@#.accept-cookies`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.8.1 (x64)
- Adblock Extension/version: uBlock Origin v1.15.18

**Comment by Alex-302** [comment]
thanks, fixed
