### ISSUE TITLE
getir.com

### ISSUE THREAD

**Issue by kmnvq** [AdguardTeam/AdguardFilters#133961]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.39

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://getir.com/?af_xp=custom&af_force_deeplink=true&pid=partner&is_retargeting=true&shortlink=9zomlh4q&deep_link_value=getir%3A%2F%2F%3Fproduct%3D6328153601287c6994a86783%26ownerService%3D10&c=tr_g10_cpas_doritos_hot_v2

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

Tracking Parameters

```
af_xp: 
af_force_deeplink: 
pid: 
is_retargeting: 
shortlink: 
deep_link_value: 
c: 

```
referrer link:
`livad.gg/r/0BTTKnZ/`

<details><summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/199719469-55258ea2-7bd9-4d65-b6e3-841fb84bdd83.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
@kmnvq
Please let us know it anything breaks.
