### ISSUE TITLE
Can't access any file in TransferNow

### ISSUE THREAD

**Issue by Silejonu** [AdguardTeam/AdguardFilters#134007]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.44.4

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.transfernow.net/dl/202211030hGGJZb5

### What filters do you have enabled?

AdGuard URL Tracking filter

### Add your comment and screenshots

When clicking on a TransferNow link, the URL gets shortened too aggressively and any download link redirects to the error page below.

Example link: https://www.transfernow.net/dl/202211030hGGJZb5 [available until : 2022-11-10 at 8:37 PM (GMT)]

![Screenshot from 2022-11-03 21-41-34](https://user-images.githubusercontent.com/48565914/199829835-bc6b3346-8771-4d13-b89c-5e0d46ae81e7.png)

The filter responsible for this bug is: https://filters.adtidy.org/extension/ublock/filters/17.txt

### Privacy

- [X] I agree to follow this condition

**Comment by Silejonu** [comment]
Other filters also result in the same behaviour. See https://github.com/DandelionSprout/adfilt/issues/678

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
