### ISSUE TITLE
Miners detection

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#13439]
Here will be the list of miners that are not yet detected automatically by AG.

* https://github.com/AdguardTeam/AdguardFilters/issues/13166
* https://s1.nod-key.com/
* sickrage.ca/js/m.js
* https://rembitteh.ru/info/stiralnie-mashini/error/lg/ue/

**Comment by M0UL** [comment]
the miner on this site does not get detected sickrage.ca
add sickrage.ca/js/m.js to the list to block it

**Comment by Alex-302** [comment]
Another one:
https://yesiget.i234.me/%E3%80%8A%E5%A5%BD%E9%86%AB%E7%94%9F%E8%89%AF%E9%86%AB%E4%BB%81%E9%86%AB%E3%80%8Bthe-good-doctor/
```
https://www.freecontent.bid./IbdT.js?ver=4.9.4
https://freecontent.racing./proxy
https://www.freecontent.stream./EIU4DBg5.wasm
```

**Comment by AdamWr** [comment]
It seems that here is not detected too - https://ddmix.net/

`https://pon.ewtuyytdf45.com/worker.js`

**Comment by AdamWr** [comment]
Probably another one:
`https://www.gnrdomimplementation.com/connection.js`
`https://nerohut.com/`

I found it here - `http://hdcast.pw/hls1.php?width=630&height=450&id=nbatv&autoplay=true&strech=exactfit`

**Comment by AdamWr** [comment]
Two more websites:
`http://www.justintvizletir.tv/players/sport.html?id=1295475`
`https://www.fiisports4.com/stream/116122/krylya-sovetov-spartak-moscow-macini-canli-izle`

Mining js is probably loaded from swf file.

`https://pastebin.com/raw/w4yyLvtD`

**Comment by evgeniy-ADG** [comment]
http://www.verdadenlibertad.com/ - another website

<details> <summary> the screenshots <summary>

![sin titulo1](https://user-images.githubusercontent.com/15856304/38506681-38c0bf9e-3c23-11e8-8261-46226590d189.png)


![sin titulo2](https://user-images.githubusercontent.com/15856304/38506693-41fe3636-3c23-11e8-9f2e-8f262902cc7d.png)

<details>

**Comment by Alex-302** [comment]
@evgeniy-ADG not reproduced. Please press Shift+Esc in Chrome and show screenshot.

**Comment by BlazDT** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/15842
Not detected:
skencituer.com

**Comment by AdamWr** [comment]
Similar case like here - https://github.com/AdguardTeam/AdguardFilters/issues/13439#issuecomment-378664567
Watch any stream from this website - `http://sportstream365.com/`

`https://pastebin.com/raw/DVkYZYkV`

**Comment by BlazDT** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/17881

websocket.minexmr.stream
minexmr.stream
