### ISSUE TITLE
nestlenutrition-institute.org

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#134481]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.39

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.nestlenutrition-institute.org/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/117537631/200921073-910cddf8-d58b-461b-bb95-528700cffc26.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
I'm not sure if this popup should be blocked.
