### ISSUE TITLE
Alibaba.com - Broken login (AdGuard English filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#13450]
**Affected page**:
`https://login.alibaba.com/`

**Issue**:
Login element is blocked

**Screenshot**:
![filterissue-alibaba](https://user-images.githubusercontent.com/9382674/37621291-69d2e95e-2bb6-11e8-94fd-07127f00d77e.jpg)

**Problem filter**:
AdGuard English filter

**Problem rule**:
`##iframe[width="100%"][height="250"]`

**Possible fix**:
`alibaba.com#@#iframe[width="100%"][height="250"]`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.8.1 (x64)
- Adblock Extension/version: uBlock Origin v1.15.18

**Comment by Alex-302** [comment]
thanks, fixed.
