### ISSUE TITLE
openrice.com for AdGuard Chinese Suggested new rule

### ISSUE THREAD

**Issue by ICHx** [AdguardTeam/AdguardFilters#134771]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Sponsor cells are not blocked.

### Proposed solution

```
! 2022-11-13 https://www.openrice.com
www.openrice.com##.sponsored-content-cell

```

**Comment by Alex-302** [comment]
Please do not use Feature Request for reporting filtering issues.
I can't find this element on pages.
