### ISSUE TITLE
Dakar Desert Rally (Windows app; the report form didn't accept "Dakar2Game.exe" as a URL)

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#134837]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

Unclear; we can assume the `2022-11-14T00:03:01.988Z` list version

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Desktop

### Where is the problem encountered?

"Dakar Desert Rally" on Steam/EGS, most visibly at the startlines of stages.

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

1. I received an interesting heads-up from [an owner of *Dakar Desert Rally* on PCGamingWiki](https://www.pcgamingwiki.com/wiki/Topic:X6von2hsqay3oswt), who claimed to have encountered ads in hub areas and startlines, but who allegedly found a way to block them. The supposed info was interesting enough that I'm forwarding it near-verbatim without actually having tested it myself, for the purposes of e.g. AdGuard for Windows and AdGuard DNS Filter.

The entries they suggested were:
```
||anzusafeframe.azureedge.net^
||assets.anzuinfra.com^
||caps-server.anzu.io^
||emqx.anzuinfra.com^
||events.anzuinfra.com^
||l1-1.anzu.io^
||logic.anzuinfra.com^
||mgw-2.anzuinfra.com^
```

Other than this, the provided details were somewhat sparse, including if they used any other entries/filters for anything.

3. Screenshots

They had not posted any screenshots at the time of writing.

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Looks like `anzu.io` can be blocked due to they provide ad solutions - added to our filters.
I'm not sure about other domains.
@DandelionSprout I don't have this game. Please specify screenshots with the ads and the list above.
So, what is needed:
1. Update filters in 1-2 hours.
2. Check the game.
3. If you still see ads, let me know which other requests need to be blocked (all or just some from the list below).
```
||anzusafeframe.azureedge.net^
||assets.anzuinfra.com^
||emqx.anzuinfra.com^
||events.anzuinfra.com^
||logic.anzuinfra.com^
||mgw-2.anzuinfra.com^
```

**Comment by DandelionSprout** [comment]
The problem is that I don't own the game. I just forwarded the suggestions of someone who does.

**Comment by zloyden** [comment]
I saw that and thought you can contact with him.
However, it will be better if the original reporter can write about it here.

**Comment by DandelionSprout** [comment]
I think I can indeed contact him, but it'll take up to 24 hours.

**Comment by Aldaviva** [comment]
Hello, I'm the original reporter from PCGamingWiki.

After retesting, I found that the ads in this game are successfully blocked when **either `caps-server.anzu.io` or `l1-1.anzu.io`, or both,**  are blocked.

It seems that blocking the other `*.anzuinfra.com` and `anzusafeframe.azureedge.net` domains are not necessary to block ads in this game.

Here are screenshots showing the effect of blocking `caps-server.anzu.io` and `l1-1.anzu.io`.

|`*.anzu.io` allowed|`*.anzu.io` blocked|
|---|---|
|![with-ads](https://user-images.githubusercontent.com/1417794/201832316-32f67819-02f7-485e-99e5-1881412bbb2b.jpg)|![without-ads](https://user-images.githubusercontent.com/1417794/201832323-e0d1c922-517f-4be7-89c8-31c1ffd1bdaa.jpg)|

The actual online ads being blocked for me were Fidelity and Paramount+. When ads are blocked, you'll see the default offline images built-in to the game installation, which is where the Motul, francetvsport, Saudi Arabia, and Dakar "Dream. Dare. Live It." images are coming from.

Thanks! Let me know if there's anything else I should add.

**Comment by zloyden** [comment]
Hi! Thanks for the detailed response! I glad it helped you :)
