### ISSUE TITLE
soundcloud

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#134884]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.9

### What type of problem have you encountered?

Missed ads or ad leftovers, Missed analytics or tracker

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.soundcloud.android

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

||tracker.samplicio.us^
||s.cdnsynd.com^
||www.pandora.com^$app=com.soundcloud.android (blocks ads)
||ade.googlesyndication.com^$app=com.soundcloud.android

https://play.google.com/store/apps/details?id=com.soundcloud.android

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
I don't see these domains in log.

**Comment by jordanswrld94** [comment]
![Screenshot_20221115_053030_AdGuard](https://user-images.githubusercontent.com/118186787/201909273-6db667da-b8a5-4bb5-857f-05ee9a1c5d36.jpg)
![Screenshot_20221115_053018_AdGuard](https://user-images.githubusercontent.com/118186787/201909282-d83a9e34-0b73-4f68-8af6-6cc28273663b.jpg)
![Screenshot_20221115_053008_AdGuard](https://user-images.githubusercontent.com/118186787/201909286-293e639e-47a6-44c9-b11b-05642c6347f1.jpg)

@Alex-302

**Comment by jordanswrld94** [comment]
pandora domain ads come from

**Comment by jordanswrld94** [comment]
blocking those get rid of the ad. u have to swi0e a couple times on somgs to see it

**Comment by jordanswrld94** [comment]
![Screenshot_20221115_042012_AdGuard](https://user-images.githubusercontent.com/118186787/201917381-518ec684-0d0b-44e9-8a07-f1e5fa802690.jpg)

**Comment by jordanswrld94** [comment]
![Screenshot_20221115_061528_Gallery](https://user-images.githubusercontent.com/118186787/201917545-88817c8c-7692-4c3a-af95-90eae8c22828.jpg)

**Comment by Alex-302** [comment]
Could you please show HTTP request to pandora, not DNS?

**Comment by jordanswrld94** [comment]
my bad i didnt realize it was dns. i don't think it appears as http

**Comment by jordanswrld94** [comment]
blocking the above except pandora still gets rid of ads

**Comment by Alex-302** [comment]
So what exactly blocks ads?

**Comment by jordanswrld94** [comment]
it loaded  ads again.
![Screenshot_20221115_100332_AdGuard](https://user-images.githubusercontent.com/118186787/201967672-b38587b4-0732-44e1-9047-9b6d30ff3403.jpg)
