### ISSUE TITLE
AdGuard Annoyances Filter prohibits me from streaming on skyshowtime.com

### ISSUE THREAD

**Issue by SebastianRasch** [AdguardTeam/AdguardFilters#134983]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.9.0.1206

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.skyshowtime.com/watch/home

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

I guess this will be hard to test for you since the service is only available in some European countries and you need an account to reproduce this. Opening the site works fine but when I try to enter the actual streaming platform (button "Watch on SkyShowtime") I always get this error message:

<details><summary>Screenshot 1:</summary>

![Screenshot 2022-11-15 at 15 41 56](https://user-images.githubusercontent.com/22617697/201948090-36f71f8f-6b83-44c8-bb3a-46775502e25b.png)</details>

Without the "AdGuard Annoyances Filter" it works as expected. They might use some tracker to determine your location and block the service if they can't find it or if you're in a country that is not eligible for the service.

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Could you please trwr this rule, thank you:
@@||cdn-ukwest.onetrust.com^$domain=skyshowtime.com

**Comment by SebastianRasch** [comment]
Yes that does the trick, thanks! Are you gonna add it to the list?

**Comment by BlazDT** [comment]
Added. Do you see any cookie dialogues? Without login and just viewing the site no cookie is shown.
