### ISSUE TITLE
False Positive of Social Annoyance at Immersive Fox

### ISSUE THREAD

**Issue by lcsvcn** [AdguardTeam/AdguardFilters#134966]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.9.0.1206

### What type of problem have you encountered?

Social media buttons — share, like, tweet, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

http://immersive-fox.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Hide your search queries

### Add your comment and screenshots

1. False Positive of Social Annoyance at Immersive Fox
I work at Immersive Fox (http://immersive-fox.com and http://dev.immersive-fox.com) and some filters are blocking a core functionality of our website. We do not have any social annoyances at all, but we do have a share-icon to allow users to share they generated video.

I will create a PR to suggest a fix to allow any class with name share-icon in immersive-fox domain.

2. Screenshots
<details><summary>Social Filter Annoyances Off:</summary>

<img width="274" alt="Screenshot 2022-11-15 at 07 50 43" src="https://user-images.githubusercontent.com/6011385/201905388-b4ff5727-b692-4c72-9ba3-0682e37bc562.png">
</details>
<details><summary>Social Filter Annoyances On:</summary>
<img width="277" alt="Screenshot 2022-11-15 at 07 51 11" src="https://user-images.githubusercontent.com/6011385/201905356-a318d704-27c6-4b7c-81b7-bb3dbb3e9ccd.png">
</details>

<details><summary>Icon Html Code:</summary>
<img width="250" alt="Screenshot 2022-11-15 at 07 51
<img width="858" alt="Screenshot 2022-11-15 at 07 50 35" src="https://user-images.githubusercontent.com/6011385/201905406-f531f65d-2578-4f05-add6-a19b6b49af52.png">
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
@lcsvcn I guess the issue **might** be related to AdGuard Social Media, but I don't see any blocking rules to your site.
First, try this rule `indiegogo.com#@#.share-icon`.
Please share the filter log with the problematic rule. To do this, use the extension, not the app.
Also specify exactly what this element contains.

**Comment by lcsvcn** [comment]
Here is what filter logs shows:

<details><summary>Filter logs complete</summary>
<img width="1344" alt="Screenshot 2022-11-15 at 09 05 33" src="https://user-images.githubusercontent.com/6011385/201915887-a1877d57-da0c-43d4-8108-5ba40f54d798.png">
</details>

<details><summary>Filter log (only modified)</summary>
<img width="1283" alt="Screenshot 2022-11-15 at 09 07 05" src="https://user-images.githubusercontent.com/6011385/201916010-90cf7807-862e-4a5b-b7c0-f8892397ede8.png">

</details>
<details><summary>Filter log (only modified) request details</summary>
<img width="1344" alt="Screenshot 2022-11-15 at 09 05 33" src="https://user-images.githubusercontent.com/6011385/201916185-93c56b7b-d08c-4090-9902-81a0505a4e6c.png">

</details>

Seems like the problematic rule is ~indiegogo.com##.share-icon indeed.

**Comment by zloyden** [comment]
I see. The rule above should help on your end.
Could you also tell me what your element contains?

**Comment by lcsvcn** [comment]
It is only an SVG image with class "share-icon". 

Here is the html code.
`<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" class="share-icon"><circle cx="16" cy="16" r="16" fill="#444954"></circle><path d="M19.5156 17.6813C18.8184 17.6813 18.1958 18.006 17.7908 18.5115L14.6262 16.8943C14.6702 16.7205 14.6937 16.5387 14.6937 16.3516C14.6937 16.089 14.6476 15.8369 14.5631 15.603L17.8901 13.604C18.2939 14.0429 18.8731 14.3187 19.5156 14.3187C20.734 14.3187 21.725 13.3277 21.725 12.1094C21.725 10.891 20.734 9.9 19.5156 9.9C18.2973 9.9 17.3063 10.891 17.3063 12.1094C17.3063 12.3611 17.3487 12.6032 17.4266 12.8289L14.0889 14.8343C13.6861 14.4086 13.1158 14.1422 12.4844 14.1422C11.266 14.1422 10.275 15.1332 10.275 16.3516C10.275 17.5699 11.266 18.5609 12.4844 18.5609C13.1931 18.5609 13.8247 18.2255 14.2291 17.7056L17.3818 19.3168C17.3325 19.4999 17.3063 19.6923 17.3063 19.8906C17.3063 21.109 18.2973 22.1 19.5156 22.1C20.734 22.1 21.725 21.109 21.725 19.8906C21.725 18.6723 20.734 17.6813 19.5156 17.6813ZM19.5156 10.8031C20.2358 10.8031 20.8219 11.3892 20.8219 12.1094C20.8219 12.8296 20.2358 13.4156 19.5156 13.4156C18.7954 13.4156 18.2094 12.8296 18.2094 12.1094C18.2094 11.3892 18.7954 10.8031 19.5156 10.8031ZM12.4844 17.6578C11.7642 17.6578 11.1781 17.0717 11.1781 16.3516C11.1781 15.6314 11.7642 15.0453 12.4844 15.0453C13.2046 15.0453 13.7906 15.6314 13.7906 16.3516C13.7906 17.0717 13.2046 17.6578 12.4844 17.6578ZM19.5156 21.1969C18.7954 21.1969 18.2094 20.6108 18.2094 19.8906C18.2094 19.1704 18.7954 18.5844 19.5156 18.5844C20.2358 18.5844 20.8219 19.1704 20.8219 19.8906C20.8219 20.6108 20.2358 21.1969 19.5156 21.1969Z" fill="white" stroke="white" stroke-width="0.2"></path></svg>`

Why a rule applied for indiegogo.com is being applied on immersive-fox.com website?

**Comment by zloyden** [comment]
Ok, I got it. Fixed, update should be available in 1-2 hours.

> Why a rule applied for indiegogo.com is being applied on immersive-fox.com website?

It's a generic one, which applies to many sites except with those that have `~`.

**Comment by lcsvcn** [comment]
Do you know if uBlock extension uses the same filter list as Adguard? I noticed it was happening for users that have uBlock installed too. So I am wondering if I need to report on some uBlock filter list too.

**Comment by zloyden** [comment]
Probably not, but uBlock Origin also has the filter log and you find out what causes it.
As I recall, some `Fanboys` filters might have the same rule.

**Comment by zloyden** [comment]
Btw, I also let the author of `Fanboys` filters know about it, so you don't need to report there.

**Comment by lcsvcn** [comment]
Awesome, thank you for all the information and the help!
