### ISSUE TITLE
walmart

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#134969]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

4.9

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.walmart.android

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

||drfdisvc.walmart.com^ its blocked in ontent filter list but not dns

https://play.google.com/store/apps/detail
s?id=com.walmart.android

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
||advertising.walmart.com^

forgot this one

**Comment by Alex-302** [comment]
Need screenshot of ads.

**Comment by jordanswrld94** [comment]
sorry there is none. because its blocked by content filter but not dns

**Comment by Alex-302** [comment]
What exactly is blocked by `||advertising.walmart.com^`?

**Comment by jordanswrld94** [comment]
idk. just thought wed add it. no walmart sponsored ads are blocked though.

**Comment by Alex-302** [comment]
> Need screenshot of ads.

**Comment by Alex-302** [comment]
> drfdisvc.walmart.com

is blocked by dns now.
