### ISSUE TITLE
Publish a post not possible

### ISSUE THREAD

**Issue by TomTheThomse** [AdguardTeam/AdguardFilters#135034]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

Version 2.9.0.1206 release

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.apfeltalk.de/community/threads/adguard-und-probleme-mit-der-cookie-banner-akzeptierung.571323/#post-5741080

### What filters do you have enabled?

AdGuard Base filter, AdGuard French filter, AdGuard German filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, EasyList, EasyList Germany, EasyPrivacy, Fanboy's Annoyances, Adblock Warning Removal List, I don't care about cookies

### Add your comment and screenshots

1. <comment>I wrote a reply and it was not possible to post it because the forum reported an error. "Oooops something went wrong. Try again later".
A few days ago I was able to post without any problems.
If I disable AdGuard for this site, I can post without any problems.

2. Screenshots
<details><summary>Screenshot 1:</summary>
![SCR-20221116-cu7](https://user-images.githubusercontent.com/61783194/202125596-c440927f-416c-473e-ae5f-7d760063f140.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Hello,
Could you please add this rule:
```adblock
@@||apfeltalk.de/community/*/?_xfRequestUri=
```
to user rules and then check out if you can publish posts on website?

**Comment by TomTheThomse** [comment]
Thank you Adam, but unfortunately the user rule did not change anything.

**Comment by AdamWr** [comment]
Okay, could you please check out this rule:
```adblock
@@||apfeltalk.de/community/threads/$xmlhttprequest
```

**Comment by TomTheThomse** [comment]
The user rule has triggered some strange behavior when posting. My new post was attached to the old post and the page was reloaded and after that I could not log out of the page because of the error message I mentioned at the beginning.
Furthermore, without my intervention, a new user rule was created: @@||www.apfeltalk.de^$important,document

**Comment by AdamWr** [comment]
That's weird, I have created a test account and was able to publish a test post after adding this rule.
Please try to add all these rules:
```adblock
@@||apfeltalk.de/community/*/?_xfRequestUri=
@@||apfeltalk.de/community/threads/$xmlhttprequest
@@||apfeltalk.de/community/posts/$xmlhttprequest
```
and check again.

**Comment by AdamWr** [comment]
That's weird, I have created a test account and was able to publish a test post after adding this rule.
Please try to add all these rules:
```adblock
@@||apfeltalk.de/community/*/?_xfRequestUri=
@@||apfeltalk.de/community/$xmlhttprequest
```
and check again.

**Comment by TomTheThomse** [comment]
The suggestions in your mail worked.
I was able to post. However, when I tried to click on my user name to log out, the error appeared again. I then left the page and went back to the overview and there I was able to log out.
The important thing for me is that I can post.
Since I am not a specialist, can you please explain to me what these user rules do?

@@||apfeltalk.de/community/* /?_xfRequestUri=
@@||apfeltalk.de/community/threads/$xmlhttprequest
@@||apfeltalk.de/community/posts/$xmlhttprequest

**Comment by AdamWr** [comment]
I think that the latest one:
```adblock
@@||apfeltalk.de/community/$xmlhttprequest
```
should fix all or at least most of the issues.

>Since I am not a specialist, can you please explain to me what these user rules do?

These rules unblock requests from a specific path.
For example, this rule - `@@||apfeltalk.de/community/$xmlhttprequest`
It unblocks all requests from `apfeltalk.de/community/`, but only if type of the request is `xmlhttprequest`.

It looks like that issue occurs only in a specific thread, due to the name of this thread.
There is a rule in `AdGuard Annoyances filter` which blocks all request which contains `-cookie-banner-` and for instance, when someone want to see a reply preview, a request like this `https://www.apfeltalk.de/community/threads/adguard-und-probleme-mit-der-cookie-banner-akzeptierung.571323/reply-preview` is blocked:
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/202146162-af3384f5-446c-437c-9bc4-f4adf43b82b2.png)

</details>

and it causes errors.

I will add:
```adblock
@@||apfeltalk.de/community/$xmlhttprequest
```
it should fixes this issue (filters update will be available in 1-2 hours).

**Comment by TomTheThomse** [comment]
Thank you for your great explanation!
