### ISSUE TITLE
salom.com.tr

### ISSUE THREAD

**Issue by kmnvq** [AdguardTeam/AdguardFilters#135084]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.39

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.salom.com.tr/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyPrivacy

### Add your comment and screenshots

https://www.salom.com.tr/

<details><summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/202328360-aff5c17d-13ec-4035-86c7-f52f02643eaa.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by ramazansancar** [comment]
@kmnvq Add these filters:
```txt
! 2022-11-17 https://www.salom.com.tr
www.salom.com.tr##.hidden-sm.hidden-xs.sol-yapiskan-reklam
www.salom.com.tr##.hidden-sm.hidden-xs.sag-yapiskan-reklam
www.salom.com.tr##[href^="https://www.salom.com.tr/go"]
```
