### ISSUE TITLE
alexa app

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#135135]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.amazon.dee.app

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

||alexa-mobile-analytics-configuration-prod.s3.amazonaws.com^
||kinesis.us-*.amazonaws.com^ (kinesis is used for analytics)

https://play.google.com/store/apps/details?id=com.amazon.dee.app

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
![Uploading Screenshot_20221117_140850_AdGuard.jpg…]()

**Comment by jordanswrld94** [comment]
![Screenshot_20221117_140850_AdGuard](https://user-images.githubusercontent.com/118186787/202549104-35efe284-0955-4505-9015-58213cc33fc0.jpg)
![Screenshot_20221117_140843_AdGuard](https://user-images.githubusercontent.com/118186787/202549109-be7f5937-570d-4fde-b759-4bbb64572b7b.jpg)

**Comment by jordanswrld94** [comment]
what about the kinesis us one? @Alex-302  thats the one i see. im not in eu

**Comment by jordanswrld94** [comment]
||kinesis.us-*.amazonaws.com^

**Comment by Alex-302** [comment]
@jordanswrld94 https://forum.adguard.com/index.php?threads/kinesis-us-east-1-amazonaws-com.27831/

**Comment by jordanswrld94** [comment]
ah i didnt know it was infrastructure service i guess we should remove the eu one then @Alex-302
