### ISSUE TITLE
[iOS] http://casstudio.tv/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1351]
Пропущена реклама на странице:
http://casstudio.tv/

поп-ап и сзади за ним баннер

![image](https://cloud.githubusercontent.com/assets/15856304/12506479/dcb18ab0-c0f7-11e5-84f1-e80477deda2f.png)

YLB-835-50882

**Comment by Alex-302** [comment]
У меня чисто/
