### ISSUE TITLE
List of SCAM sites

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#135144]
https://kreox.ru/
https://soundu.ru/
https://earnu.ru/
https://grenux.ru/
https://frond.ru/
https://jobtx.ru/
https://cometx.ru/
https://autask.ru/
https://laboru.ru/
https://gremp.ru/
https://trando.ru/
https://jabon.ru/
https://ifweb.ru/
https://dexout.ru/
https://adveg.ru/
https://relogy.ru/
https://emplye.ru/
https://textco.ru/
https://fotext.ru/
https://tacka.ru/
https://tasku.ru/
https://workym.ru/
https://trasbn.ru/
https://textm.ru/
https://agern.ru/
https://wolty.ru/
https://textf.ru/
https://worku.ru/
https://transu.ru/
https://textem.ru/
https://setyl.ru/
https://granby.ru/
https://joods.ru/
https://tezod.ru/
https://kampys.ru/
https://flesup.ru/
https://conspy.ru/
https://melse.ru/
https://kavera.ru/
https://wixter.ru/
https://wopex.ru/
https://jaspez.ru/
https://pearx.ru/
https://fyber.ru/
https://trembl.ru/
https://devirs.ru/
https://travix.ru/
https://hlpcash.sbs/
https://mrcash.sbs/
https://tormoney.cfd/
https://cshmoney.cfd/
https://urmoney.cfd/
https://lotmoney.cfd/
https://kfcmoney.cfd/
https://cashag.sbs/
https://bromoney.cfd/
https://agcash.sbs/
https://morcash.cfd/
https://twocash.cfd/
https://cashjob.cfd/
https://isjob.cfd/
https://ltmoney.sbs/
https://2money.icu/
https://4job.cfd/
https://4job.sbs/
https://4money.one/
https://fivmoney.xyz/
https://germoney.xyz/
https://getmoney.sbs/
https://gtcash.cfd/
https://himoney.cfd/
https://mancash.xyz/
https://prvcash.cfd/
https://shlmoney.xyz/
https://sprmoney.xyz/
https://xxlmoney.one/
https://xycash.cfd/
https://xycash.xyz/
https://sprjob.cfd/
https://sprmoney.sbs/
https://sprcash.sbs/
https://colcash.cfd/
https://hgmoney.cfd/
https://hmmoney.cfd/
https://hamoney.cfd/
https://hrdmoney.cfd/
https://omgmoney.cfd/
https://sagmoney.cfd/
https://hitmoney.sbs/
https://xlamoney.xyz/
https://crkmoney.cfd/
https://manmoney.sbs/
https://agamoney.cfd/
https://hommoney.cfd/
https://flimoney.cfd/
https://agmoney.cfd/
https://ftmoney.cfd/
https://magmoney.cfd/
https://gtmoney.cfd/
https://sotmoney.cfd/
https://fatmoney.cfd/
https://sprcash.cfd/
https://sprjob.icu/
https://sprjob.xyz/
https://mgmoney.cfd/
https://sprcash.xyz/
https://sprjob.sbs/
https://sprmoney.cfd/
https://mancash.sbs/
https://cashag.cfd/
https://4cash.sbs/
https://manmoney.cfd/
https://sprcash.icu/
https://mancash.icu/
https://manmoney.icu/
https://mancash.cfd/
https://manjob.cfd/
https://manjob.sbs/
https://cashag.xyz/
https://manjob.icu/
https://manjob.xyz/
https://xycash.icu/
https://gtcash.xyz/
https://xxlmoney.cfd/
https://nermoney.xyz/
https://manmoney.xyz/
https://5money.xyz/
https://xlmoney.sbs/
https://xxlmoney.icu/
https://xxlmoney.sbs/
https://xlmoney.cfd/
https://xlmoney.icu/
https://lvmoney.xyz/
https://hsmoney.xyz/
https://kwmoney.xyz/
https://hlmoney.xyz/
https://bnmoney.xyz/
https://lsmoney.xyz/
https://psmoney.xyz/
https://fstmoney.sbs/
https://himoney.sbs/
https://hitmoney.one/
https://getmoney.cfd/
https://2money.cfd/
https://gtmoney.icu/
https://fstmoney.one/
https://fstmoney.cfd/
https://hitmoney.icu/
https://hitmoney.cfd/
https://2money.sbs/
https://4job.icu/
https://cashag.icu/
https://xycash.sbs/
https://hicash.icu/
https://gtcash.icu/
https://gtcash.sbs/
https://fremoney.xyz/
https://cryptobest.online/
https://cryptogreen.online/
https://cryptonice.online/
https://cryptowell.online/
https://cryptoprimes.online/
https://cryptorain.online/
https://cryptosend.online/
https://cryptoadd.online/
https://cryptoget.online/
https://cryptomixer.online/
https://cryptochan.online/
https://cryptoexch.online/
https://cashobmen.top/
https://izi-changer.top/
https://hot-ex.top/
https://oneween.com/
https://kazvulkan.com/
https://fiesta-pay.online/
https://2022-pay.online/
https://money-pro.net/
https://bio-pay.xyz/
https://kakao-pay.online/
https://m.gvvbxft.eu/
https://ru.gvvbxft.eu/
https://like.gvvbxft.eu/
https://crazy.gvvbxft.eu/
https://m.hks0rhk.eu/
https://ru.hks0rhk.eu/
https://like.hks0rhk.eu/
https://crazy.hks0rhk.eu/
http://wildberrless-you.pw/bank
http://wildberrless-pro.pw/bank
http://wildberrlesspro.pw/bank
http://wildberrlesspro.pw/bank
http://wildberrlesspro.pw/bank
http://wildberrlessmy.pw/bank
http://box-wildberriess.pw/bank
http://wildberriess-best.pw/bank
http://pro-wiidberles.pw/bank
http://boxes-wiidberles.pw/bank
http://prise-wiidberles.pw/bank
https://aksha.online/
https://kaz-finance.online/
http://2prof.fintodayai.skin/
http://bicson.ru/gasprom2/signup/
https://browncharismatic.info/
https://frozensickness.info/
https://glycruipogtidown.ml/
https://economymotorcycle.info/
https://strugglegalaxy.info/
https://minuteserve.info/
https://afishaartistic.ru/
https://satyrtalent.ru/
https://satyr-artists.ru/
https://satyrartists.ru/
https://satyrartistic.ru/
https://satyr-artistic.ru/
https://satyrarts.ru/
https://satyrboard.ru/
https://satyr-talent.ru/
https://dram-ticka.ru/
https://afisha-arts.ru/
https://afishaarts.ru/
https://dram-theatre.online/
https://theatre-ticket.pro/
https://satyroriginale.ru/
https://afisha-estrade.ru/
https://pk.teatr.best/
https://hookah-room.ru/
https://cinemapik.ru/
https://cinemamay.ru/
https://cinemadex.ru/
https://cinema-moonlun.ru/
https://cinema-sferum.ru/
https://glove-cinema.ru/
https://cinema-midas.ru/
https://rb-gos.top/
https://trusted-gos.top/
https://cube-square.ru/
https://education-square.ru/
https://nova-start.ru/
https://nova-study.ru/
https://sucoin.ru/
https://cryptorun.ru/
https://feedcoin.ru/
https://pressbit.ru/
https://sven.guerrero-alma.buzz/
https://joywix.com/
https://hfv84.wuzodyf.cfd/
https://hfv84.bisahix.cfd/
https://isrc2.jyfonuj.cfd/
http://casher-bit.ru/
https://crypto-expert.work/
https://dengi-online.life/
http://youtubereo.top/
http://youtuberki.top/
http://videoytv.buzz/
http://youtuber.team/
http://youtuber.ltd/
http://youtuber.casa/
http://youtuber.run/
http://youtuber.money/
http://youtuber.party/
https://videosilo.xyz/
https://videotld.xyz/
http://cy-video.xyz/
https://videosmm.buzz/
https://videofunds.buzz/
http://world-video.xyz/
https://videosilo.buzz/
https://videoyoutbe.buzz/
http://look-video.xyz/
http://choose-video.xyz/
https://videoslook.xyz/
https://videoslist.xyz/
https://videoshot.buzz/
https://alfachange24.com/
https://exhub24.com/
https://solvertex24.com/
https://nftoption24.com/
http://silence-exchange.org/
https://space-crypt24.com/
https://armchange24.com/
https://bitswap24.ru/
http://clever-exchange.com/
https://cryptodrom24.com/
http://bestcryptochange24.com/
http://blast-money.pro/
https://alfabit24.com/
https://fast-changebit24.com/
https://ramoncash24.com/
http://wm-exchange24.com/
https://solobit24.com/
https://bitcoin-cheats.com/
https://exchange-cheats.com/
https://exchange-hacking.com/
https://bitcoin-rates.top/
https://ransy.ru/
https://loanmortgage.digital/
https://bestchang.site/
https://obmencrypto.site/
https://fexpro.ru/
https://8wr5q.xavaguv.cfd/?ui303c=
https://m.cb63ay.eu/
https://ru.cb63ay.eu/
https://like.cb63ay.eu/
https://crazy.cb63ay.eu/
https://theatre-ticket.pw/
https://white-exchanger.com/
https://onlycrypto-exchange.com/
https://gifts-wildberrless.pw/bank
https://dm.jobs24.ru.com/h/detmir/job/index.html
https://rabota.close24.xyz/h/detmir/job/index.html
https://hamburgerdenunciation.cn/ozonruw/tb.php
https://adversaryinsulation.cn/ozonruw/tb.php
https://accuseallot.cn/ozonruw/tb.php
https://crouchaudit.cn/ozonruw/tb.php
https://dispenseaffirmation.cn/ozonruw/tb.php
https://mostman.cn/ozonruw/tb.php
https://enthusiasmshred.cn/ozonruw/tb.php
https://pillowrevenge.cn/ozonruw/tb.php
https://respondentmerge.cn/ozonruw/tb.php
https://veilinnumerable.cn/ozonruw/tb.php
https://urce.chana-menon.buzz/
https://kivo-love.ru/
https://cinema-4you.ru/
https://cinema-story.ru/
https://cinema-polemer.ru/
https://relax-cinema.ru/
https://cinema-park24.ru/
https://movie-light.ru/
https://movie-kassa.com/
https://cinema-official.ru/

**Comment by DandelionSprout** [comment]
Sure the domains look like scams indeed, but it always look pretty strange when GitHub reporters delete their accounts in less than 24 hours and *while their reports are still being processed*.

**Comment by Oniqqqq** [comment]
added these to safebrowsing list. Thanks!
