### ISSUE TITLE
qlogo.cn and baiducdnimages.com

### ISSUE THREAD

**Issue by Hill-98** [AdguardTeam/AdguardFilters#135257]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.39

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://y.qq.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter

### Add your comment and screenshots

[4918905](https://github.com/AdguardTeam/AdguardFilters/commit/4918905fb2b194d23fd413707c9eba85a79fb2e3)

qlogo.cn and baiducdnimages.com should not be blocked, they are used to load Tencent social software avatars and Baidu pictures respectively.

### Privacy

- [X] I agree to follow this condition

**Comment by mercury233** [comment]
https://thirdqq.qlogo.cn/ is used for QQ avatars, shouldn't be blocked

**Comment by AdamWr** [comment]
Fixed in https://github.com/AdguardTeam/AdguardFilters/commit/c1f2fb227d07dba25d0d1eeb6b68d0fbaaefbc4a
Filters update should be available in 1-2 hours.
