### ISSUE TITLE
outlook.live.com

### ISSUE THREAD

**Issue by cediok** [AdguardTeam/AdguardFilters#135203]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

Version: 2.1.40.2

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://outlook.live.com/mail/inbox

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1.  The filter outlook.live.com##body from the Annoyances list is preventing the Outlook web client from showing the receiver address of any given email.

2. Screenshots

<details><summary>Screenshot N: 1</summary>

![issueADguardAnnoyances](https://user-images.githubusercontent.com/116902683/202771253-12fabb6a-c069-4bae-8349-326f7752d219.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
In fact, I do not see any difference on my end. The rule above cannot block this - the purpose is different.
