### ISSUE TITLE
Please disable Adblock

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#135316]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.9.11

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://t2bot.ru/en/esetkeys/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

![image](https://user-images.githubusercontent.com/46019727/202888918-3b19c0b3-5339-4039-846a-e9b6809c0f4f.png)

website saying please disable adblock

### Privacy

- [X] I agree to follow this condition

**Comment by ilvjyw** [comment]
`t2bot.ru#%#//scriptlet('prevent-setTimeout', '/\.adsbygoogle/')`

**Comment by Alex-302** [comment]
If you report a site, please always enter its name in the title(without HTTP prefix)

**Comment by Bhooty** [comment]
> If you report a site, please always enter its name in the title(without HTTP prefix)

ok sir from next time will follow it

**Comment by Bhooty** [comment]
> `t2bot.ru#%#//scriptlet('prevent-setTimeout', '/\.adsbygoogle/')`

thanks sir worked

**Comment by Bhooty** [comment]
> If you report a site, please always enter its name in the title(without HTTP prefix)

sir i updated adguard but still showing to disable but if I use the rule of @ilvjyw in user rules then it works
