### ISSUE TITLE
found in log

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#135376]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

http://example.com

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

collection.us2.sumologic.com
inbound-analytics.pixlee.com

found these in my log dont know where they came from or which app

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
i do and they are still reachable it looks like

**Comment by zloyden** [comment]
Could you provide a URL to check this?
