### ISSUE TITLE
Amazon Track Your Package Site since version 2.0 blocked

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#13535]
@Basic-income commented on [Wed Mar 21 2018](https://github.com/AdguardTeam/AdguardForiOS/issues/726)

If open amazon site and go to in my account the track your package site or tap this in the email inbox.
Then is the url blocked or not loading this site. 

### Your environment

* Device model and storage size: iPad 9.7
* Operating system and version: iOS 11.2.6
* Browser: Safari
* Mobile internet connection
* EasyPrivacy list only 
* Adguard Pro 2.0.2

Notes: Adguard 1.3.3 with EasyPrivacy list only. No a issue.

**Comment by Basic-income** [comment]
@Alex-302 
Show this video
https://www.amazon.de/gp/help/customer/display.html?nodeId=201910530

**Comment by Alex-302** [comment]
I don't use Amazon, so I can't track nothing)
Please provide example of blocked URL. Is it actual for iOS only or for all platforms?

**Comment by Basic-income** [comment]
@Alex-302 
here a sample url
https://www.amazon.de/gp/r.html?C=49392828ldlf

**Comment by Alex-302** [comment]
It redirects me to the main page.

**Comment by Alex-302** [comment]
Please check:
```
@@||amazon.de/gp/r.html?C=
```

**Comment by Basic-income** [comment]
@Alex-302 

> It redirects me to the main page.
Yes I know. But if used easyprivacy list only. Then this url is blocked. I cannot post the real url from my amazon account. privacy.

But this is a part from the url. Both url are blocked!

**Comment by Alex-302** [comment]
What about this rule?

**Comment by Basic-income** [comment]
good with rule (no problem).

**Comment by Alex-302** [comment]
Thanks. Added.
