### ISSUE TITLE
qlogo.cn

### ISSUE THREAD

**Issue by AXBNG** [AdguardTeam/AdguardFilters#135345]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

AdGuard Home v0.107.18

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

WeChat

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

1. <comment>When qlogo.cn is blocked, in the comment area of WeChat public account, the avatar of the commenter cannot be loaded.
https://github.com/AdguardTeam/AdguardFilters/commit/4918905fb2b194d23fd413707c9eba85a79fb2e3
2. Screenshots
<details><summary>Screenshot 1:</summary>

![1](https://user-images.githubusercontent.com/89022914/202907840-21d3369f-43d3-4ec7-ba35-39ce8504cdfe.jpg)

</details>

<details><summary>Screenshot 2:</summary>

![2](https://user-images.githubusercontent.com/89022914/202907870-480141bc-694f-4dad-b6f4-7f3da8226f16.jpg)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
