### ISSUE TITLE
AdGuard for Windows prevents file downloads within Skype 8.17.0.2

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#13546]
***Description***:
* **Current behaviour**: 

When AdGuard for Windows is running and enabled, the user cannot download any file within Skype 8.17.0.2.

* **Expected behaviour**: 

AdGuard shouldn't affect Skype file download options.

***Steps to reproduce the problem***:

1. Enable AdGuard protection;
2. Try to receive (download) any file in Skype.

***System configuration***

**Filters:**

English, Russian

**Filtering logs**
Available under 1130801.

Information                            | Value
---                                    | ---
Operating system:                      | Windows 7 SP1
Browser:                               | N/A
AdGuard version:                       | 6.2.437.2171
Filters enabled:                       | English, Russian
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Block 3rd-party cookies (30), Block WebRTC, Block Browser Push API, Block Browser Location API, Remove X-Client-Data Header, Hide Search Queries, Send Do Not Track Header, Hide User Agent, Hide IP (209.141.53.254)
Helpdesk ID (if exists):               | 1130801

**Comment by Alex-302** [comment]
We can't reproduce it. Please ask for logs with time stamp.
@AdamWr could you check it on your end?

**Comment by alan-gor** [comment]
https://youtu.be/eIkj2wKrGiQ

**Comment by Alex-302** [comment]
Попробуйте добавить этот домен в исключения в виде
`@@||domain.com^$document`
если не поможет, добавьте домен в исключения HTTPS в настройках Адгарда(вкладка сеть) и перезапустите скайп
https:
```
![image](https://user-images.githubusercontent.com/8361299/37876678-ec449ff8-3058-11e8-853f-a16d4031a07e.png)
```
Дайте знать, если один из вариантов поможет.

**Comment by alan-gor** [comment]
Не помогло.
https://ibb.co/ebkxaS

**Comment by Alex-302** [comment]
`Bypassed` это значит Адгард не заблокировал.
Покажите строку с добавленным исключением HTTPS, может ошибка есть.

**Comment by alan-gor** [comment]
Тем не менее, после выхода из Адгарда, все работает.
https://ibb.co/c914qS

**Comment by Alex-302** [comment]
А если выключить фильтры и антитрекинг(некоторые его опции вероятно могут ломать)?

**Comment by alan-gor** [comment]
Отключение Антибаннера, Антитрекера и Антифишинга на ситуацию не влияет. Помогает только исключение из Фильтруемых приложений - тогда работает.

**Comment by Alex-302** [comment]
Значит проблема глубже.

**Comment by Alex-302** [comment]
Антитрекинг тоже отключали?

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #2156](https://github.com/AdguardTeam/AdguardForWindows/issues/2156) via [**ZenHub**](https://www.zenhub.com/)
