### ISSUE TITLE
github.io

### ISSUE THREAD

**Issue by FlyingWolFox** [AdguardTeam/AdguardFilters#135561]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.45.2

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://aquarchitect.github.io/swift-algorithm-club/Shunting%20Yard/

### What filters do you have enabled?

AdGuard Chinese filter, AdGuard French filter, AdGuard Japanese filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyList, EasyList Germany, EasyPrivacy, Fanboy's Annoyances, Peter Lowe's Blocklist, Official Polish filters for AdBlock, uBlock Origin & AdGuard, I don't care about cookies, EasyList Cookie List

### Add your comment and screenshots

github pages links (github.io) are being blocked universally by the french filter

Example site https://aquarchitect.github.io/swift-algorithm-club/Shunting%20Yard/ : 

![image](https://user-images.githubusercontent.com/49326973/203446806-ab6380d0-aa35-4509-9b7a-aafdf23dc026.png)

Pages that load resources from github are also affected:
https://ryochan7.github.io/ds4windows-site/
![image](https://user-images.githubusercontent.com/49326973/203447186-1bcb0939-bb18-4a8b-9432-723ee87a5d52.png)

### Privacy

- [X] I agree to follow this condition

**Comment by t-fritsch** [comment]
Same here. Quite half the internet is broken now 😅 

![image](https://user-images.githubusercontent.com/10920280/203447854-f9e93016-aafa-4c49-8b2e-dd5cfb8a4e4b.png)

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.

<hr>

@smed79 Could you please take a look?
It seems that it has been added here - https://github.com/easylist/listefr/commit/4ceb8a7b38a10f74eac3546a6521df5caa4b4330#diff-ed13803752993344f0a395c14a947fdc07bf1b7fcbe027591005b9425ce7e7fcR7796

**Comment by FlyingWolFox** [comment]
Fix confirmed, pages are loading normally now. Thank you!

**Comment by t-fritsch** [comment]
Thanks a lot for the quick patch 🙏 

btw PR is on his way on easylist/listefr : https://github.com/easylist/listefr/pull/103

**Comment by smed79** [comment]
False positive, fixed in https://github.com/easylist/listefr/commit/22904e9265a27eba6296ed31dfcc0b6e49d2cc97

Sorry for the inconvenience :pray:
