### ISSUE TITLE
dfm.ru

### ISSUE THREAD

**Issue by PhoenixIndigo** [AdguardTeam/AdguardFilters#135559]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

2.7.0

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Firefox, Chrome, Microsoft Edge, Yandex Browser, other(specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

dfm.ru

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment> Рекламный фрейм при открытии на весь экран. И детектор блокировщика в плеере.
2. >Не повторяется.
Попробуйте полноценный Адгард для Android(основной функционал лицензии не требует)
https://adguard.com/ru/adguard-android/overview.html
AdGuard Content Blocker лишь скармливает браузеру фильтр в понятном ему виде, и что происходит дальше - неизвестно.

@[Alex-302](https://github.com/Alex-302) У вас видимо включены отсутствующие фильтры в AdGuard Content Blocker например собственные или RuAdlist все 3. Я делал скриншоты в Firefox с uBO без RuAdList! Так что исправляйте и тщательно! И настройте сайты на Москву.

3. Screenshots

https://dfm.ru/
<details><summary>Screenshot 1:</summary>

![изображение](https://user-images.githubusercontent.com/107413021/203436060-bacbf3aa-b911-4603-a39f-da27bec59e5a.png)

</details>

https://dfm.ru/mobile
<details><summary>Screenshot 2:</summary>

![изображение](https://user-images.githubusercontent.com/107413021/203436223-d94b0c44-693a-4365-9b24-56d61a5a82cf.png)

</details>

<details><summary>Screenshot 3:</summary>

![изображение](https://user-images.githubusercontent.com/107413021/203436263-03b2c6bc-9065-497a-982c-8dc9defe8e03.png)

</details>

https://rusradio.ru/mobile
<details><summary>Screenshot 4:</summary>

![изображение](https://user-images.githubusercontent.com/107413021/203436352-8ce2b19f-41be-434f-a1af-b66fd61156f8.png)

</details>

<details><summary>Screenshot 5:</summary>

![изображение](https://user-images.githubusercontent.com/107413021/203436406-52147cb8-c782-438e-83d6-0b2db6e0b90d.png)

</details>

https://maximum.ru/mobile/
<details><summary>Screenshot 6:</summary>

![изображение](https://user-images.githubusercontent.com/107413021/203436476-252e6787-a79e-4544-a4f5-01f994ec0fae.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by PhoenixIndigo** [comment]
Также в настольных браузерах ломается плеер расширением https://addons.mozilla.org/ru/firefox/addon/audio-equalizer-wext/ . Так что если плеер сломан удалите это расширение!

**Comment by zloyden** [comment]
Выше у меня повторилось, поправил. Нужно будет проверить обновление фильтров через пару часов.
Лучше пользоваться AdGuard for Android, поскольку AdGuard Content Blocker имеет сильно ограниченный функционал в сравнении с программой.

**Comment by PhoenixIndigo** [comment]
У `AdGuard for Android` вообще ограниченный пробный период работы, плюс нехватало чтобы он интернет блокировал!

**Comment by zloyden** [comment]
Что имеется в виду?

**Comment by zloyden** [comment]
Также добавил их в фильтры.

**Comment by PhoenixIndigo** [comment]
Я всё-таки не понял зачем заблокировали "Оцените 15 треков DFM!" `dfm.ru##._c-l`, которое нужно не только им но и всем, мне что их в каждом `AdGuard Content Blocker` отдельно разблокировывать, плюс в подписку uBO добавить исключение?

**Comment by zloyden** [comment]
Это попап, который заблокирован AdGuard Annoyances.
Его можно выключить или добавить исключение `dfm.ru#@#._c-l`.

**Comment by PhoenixIndigo** [comment]
К сожалению отключается только в полной десктопной версии. А исключение мне в мобиле и без надобности сенкс.
