### ISSUE TITLE
raw.githubusercontent.com

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#135544]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows, Other ad blocker

### AdGuard version

AdGuard for Windows 7.11.1 + uBO 1.45.2

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html

### What filters do you have enabled?

AdGuard Base filter, List-KR

### Add your comment and screenshots

1. I figured I should give a quick headsup that the attempt to add whitelistings in AdGuard Base for `/adservice.` currently aren't working entirely correctly, since uBO would sync List-KR from its own extension settings, instead of while the browser GUI is visiting any of the three `$domain=~` domains.

I see two possible fixes:
*My recommended way:* `@@/adservice.txt?_=` (Appears to work correctly in Dandelion Sprout's Annoyances List.) + potentially `@@||adservice.io^$~third-party`?
*An alternative way:* `@@||githubusercontent.com/*/adservice.` + `@@||github.com/*/adservice.` + `@@||adservice.io^`

3. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/22780683/203341738-437ba74e-03fa-48d2-a907-ddff4cf666a0.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Works fine
![image](https://user-images.githubusercontent.com/8361299/203353740-463de62f-b17b-49f0-a57c-330d0df0dc41.png)

**Comment by DandelionSprout** [comment]
I think you've misunderstood me. It's not the GitHub URL that is the problem. It's the fact that it's loaded from uBlock Origin's settings menu.

**Comment by DandelionSprout** [comment]
https://user-images.githubusercontent.com/22780683/203399245-c36feb7c-e931-4cd1-9a16-4108b54e9777.mp4

**Comment by Yuki2718** [comment]
In theory chrome-scheme is in Trusted sites so this should not happen, tho I certainly had the similar experience.
@piquark6046

**Comment by piquark6046** [comment]
What about change the file names?
For example:
 - `adservice_firstparty.txt` -> `1st_domains.txt`
 - `adservice.txt` -> `3rd_domains.txt`

**Comment by Yuki2718** [comment]
That sounds very safe to me.

**Comment by Yuki2718** [comment]
https://github.com/easylist/easylist/issues/13189

**Comment by piquark6046** [comment]
@ameshkov How about you?
https://github.com/AdguardTeam/AdguardFilters/issues/135544#issuecomment-1326142218

**Comment by ameshkov** [comment]
Makes sense to me

**Comment by piquark6046** [comment]
@ameshkov 
When do you want to apply [the change](https://github.com/AdguardTeam/AdguardFilters/issues/135544#issuecomment-1326142218)?
AdGuard DNS service is affected the change.

**Comment by DandelionSprout** [comment]
>https://github.com/AdguardTeam/AdguardFilters/issues/135544#issuecomment-1326146923

Well pointed out. I've completely forgot why I didn't check 2 days ago whether the entry came from EasyList or not, or why I didn't check which repo I had made that report from 2 months ago in.

**Comment by ameshkov** [comment]
@piquark6046 whenever you want, it just should be three different PRs (here, registry, dns filter) which should be merged simultaneously.

**Comment by piquark6046** [comment]
@ameshkov 
AdGuardFilters and FiltersRegistry repository does not have `adservice_firstparty.txt` or `adservice.txt` stirng.
I have to create new PR in only HostlistsRegistry[^1] because List-KR uses `!#include` syntax.
[^1]: https://github.com/AdguardTeam/HostlistsRegistry/tree/main/filters/regional

**Comment by ameshkov** [comment]
Ah, yeah, you're right.

**Comment by piquark6046** [comment]
@ameshkov Created.

**Comment by Yuki2718** [comment]
Can the EL exception be removed now?

**Comment by piquark6046** [comment]
Probably.

**Comment by Yuki2718** [comment]
@ryanbr
