### ISSUE TITLE
webvisor.com - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1355]
Adguard blocks yandex webvisor service 

Adguard is off http://joxi.ru/YmEKBbncZBnj8A?d=1
Adguard is on http://joxi.ru/vAWX9d3fkBY6ar

MRY-321-62439

**Comment by Alex-302** [comment]
нужен удалённый доступ.
Или пусть сделает следующее:
- выключать фильтры до устранения проблемы;
-  включит проблемный фильтр;
- открыть журнал фильтрации и поставить чекбокс "отображать заблокированное
- повторить проблему и прислать скрины, на которых длинные урлы будут максимально видны

**Comment by vgavrish** [comment]
@Alex-302 
1. При выключенном фильтре Счетчиков и систем аналитики проблема решается.
2. вот скрин сделали:
http://joxi.ru/52angjJtBd1QA0

**Comment by Alex-302** [comment]
@vgavrish 
передай на проверку
```
@@||mc.yandex.ru/webwisor/$domain=metrika.yandex.ru|metrika.yandex.ua
@@||webwisor.com^$domain=metrika.yandex.ru|metrika.yandex.ua 
```

**Comment by vgavrish** [comment]
@Alex-302 
передала. жду ответа

**Comment by vgavrish** [comment]
@Alex-302 
правила работают.

"P.S. К стати, при выключенном фильтре Счетчиков и систем аналитики проблема НЕ всегда решалась."

**Comment by Alex-302** [comment]
А попроси проверить без второго правила, оно похоже, не нужное.

**Comment by vgavrish** [comment]
Написала.

**Comment by vgavrish** [comment]
@Alex-302 
да, с первым правилом все работает

**Comment by Alex-302** [comment]
ок, добавил с аналитику
@@||mc.yandex.ru/webwisor/$domain=metrika.yandex.ru|metrika.yandex.ua
