### ISSUE TITLE
Known issues with stealth mode

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#1356]
| website | what's broken | stealth mode setting |
| --- | --- | --- |
| lostfilm.tv | authorization | block third party cookies |
| privat24.ua | authorization | block third party cookies |
|  |  |  |
|  |  |  |

**Comment by evgeniy-ADG** [comment]
this site is broken too http://plati.ru/
need to check which option affects it. 

> Мне достаточно часто приходится совершать покупки на торговой площадке http://plati.ru/

И до сегодняшнего дня всё было нормально.

Когда я в очередной раз пытался купить товар, то в момент покупки мне
выдавались разные ошибки - типа ваша корзина пуста, товар отсутствует и
т.п. Чего в общем то быть не может.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Не, этот раздел только для сложных случаев, например, когда разблокировать куки можно только вместе с рекламой:)

Оформи плиз отдельной проблемой

**Comment by evgeniy-ADG** [comment]
Аааа. Окей.
