### ISSUE TITLE
[QUESTION] How do I view the page code on my phone?

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#135761]
How do I view the code of a page on my Android phone?

I want to make some rules to remove annoying elements of various sites, but I don't want to disturb the tech support for the thousandth time.

I would be very grateful!

**Comment by Sergey-Lyapin** [comment]
Hello
Please look at this manual:
https://levelup.gitconnected.com/remote-debug-android-device-using-chrome-devtools-e3f5452481d6

And you also can simulate mobile view in your desktop browser:
(right mouse button > inspect > press the button marked on the screenshot)

![shf](https://user-images.githubusercontent.com/18536328/204030646-9ff6185e-474a-43db-b486-ad85c0f24fd4.png)
