### ISSUE TITLE
Ad frames on Flipboard app

### ISSUE THREAD

**Issue by jmarcrose** [AdguardTeam/AdguardFilters#136001]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.51

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

Flipboard app

### What filters do you have enabled?

AdGuard French filter

### Add your comment and screenshots

Ad frames still appear
![Screenshot_20221122-200837_Flipboard](https://user-images.githubusercontent.com/119294426/204249397-8584d03b-0eb8-4a83-93e7-71cb8611aa8d.jpg)
![Screenshot_20221122-210453_Flipboard](https://user-images.githubusercontent.com/119294426/204249403-c172b45e-b21b-4efc-93e6-2f29189fce72.jpg)
![Screenshot_20221122-210604_Flipboard](https://user-images.githubusercontent.com/119294426/204249407-a425ffae-a59e-40bd-83c9-3ad8ff55b9db.jpg)
![Screenshot_20221122-210516_Flipboard](https://user-images.githubusercontent.com/119294426/204249408-39976fbd-6207-43ca-98b9-4c496f4d1b0b.jpg)
![Screenshot_20221122-210548_Flipboard](https://user-images.githubusercontent.com/119294426/204249410-92d0b9d2-d20f-41d6-80fa-f8f79d0bc8dd.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Need download link.

Ad placeholders in apps can't be blocked.

**Comment by jmarcrose** [comment]
Hi,

I don't understand, what do you need exactly ?
What do you mean? Adguard can't definitely block these Ad placeholders ?
.It's a shame, because there are a lot of them, and the reading is as
difficult as with Ads.

Jean-Marc

**Comment by Alex-302** [comment]
> I don't understand, what do you need exactly ?

A link of download page(google store or another).

> Adguard can't definitely block these Ad placeholders ?

In the most apps these placeholders are hardcoded elements of these apps, and cannot be collapsed like ad leftovers on sites. You can try to find ad-free mods of this app. We do not modify apps.

**Comment by jmarcrose** [comment]
Good idea, I'm going to use an Ad-free mod of this app.

Thanks,
Jean-Marc
