### ISSUE TITLE
Remember GitHub username on filter report forms

### ISSUE THREAD

**Issue by WoodpeckerBaby** [AdguardTeam/AdguardFilters#136136]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Having to type GitHub username everytime is a lot of work. 

### Proposed solution

Remember that on the form, either store that in the app config or in a cookie. 

### Additional information

Please simplify the report form and reduce the number of clicks required. The hcapcha should be replaced with Apple's Private Access Tokens where avaliable.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/ReportsWebApp #317](https://github.com/AdguardTeam/ReportsWebApp/issues/317) via [**Zenhub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
Moved to the correct reprository.
