### ISSUE TITLE
Auto-fill active filters on iOS and iPadOS filter report forms

### ISSUE THREAD

**Issue by WoodpeckerBaby** [AdguardTeam/AdguardFilters#136137]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

It's a massive pain to manually type and select used filters on mobile when reporting. This should be automatic like it is on desktop. 

### Proposed solution

Automatically gather this information from the Safari extension if it's enabled. I'm not talking about just the content blockers. I'm refering to the full extension used for reporting and for advanced protection. 

### Additional information

Also, it should remember the github username and use Apple's Private Access Tokens instead of hcapcha.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardForiOS #2084](https://github.com/AdguardTeam/AdguardForiOS/issues/2084) via [**Zenhub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
@WoodpeckerBaby Moved to AdGuard for iOS repository.
But I am not sure if this is possible on iOS.
