### ISSUE TITLE
AdGuard VPN gets detected at the website

### ISSUE THREAD

**Issue by ihurin** [AdguardTeam/AdguardFilters#136225]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

AdGuard VPN 

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

re-store.ru

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Annoyances filter

### Add your comment and screenshots

1. <The website acknowledges the usage of VPN>

2. Screenshots
<details><summary></summary>
<img width="615" alt="Screenshot 2022-11-30 at 16 55 23" src="https://user-images.githubusercontent.com/33690072/204830904-14563dbe-4c1f-4b49-85c8-84c78a4ab9fb.png">

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Блокировщиком это не обойти.
