### ISSUE TITLE
blogtruyen.vn page not working

### ISSUE THREAD

**Issue by tachibana-shin** [AdguardTeam/AdguardFilters#136284]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4 nighify 36

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://m.blogtruyen.vn/c748867/vua-otaku-vua-ngheo-vua-nhat-nhung-co-ban-gai-xinh-dep-giau-co-nay-lai-yeu-toi-moi-la-chuong-31

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Block third-party Authorization header, Block WebRTC, Block Location API

### Add your comment and screenshots

1. The problem will be solved if I add filter `@@||img.datrangsang.net/images^$domain=datrangsang.net`

2. Screenshots
<details><summary>Screenshot 1:</summary>
![image](https://user-images.githubusercontent.com/45375496/204985820-0c652dcf-a38c-4fb5-b968-80328f6e472b.png)

</details>

<details>=
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
We need two screenshots. Please send report using AdGuard's feedback menu.
I don't see requests to img.datrangsang.net

**Comment by tachibana-shin** [comment]
> We need two screenshots. Please send report using AdGuard's feedback menu. I don't see requests to img.datrangsang.net

I reported this issue to the website and they changed their photo hosting domain. it worked again without the filter
