### ISSUE TITLE
zennioptical.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#136254]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other(specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.zenni.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard DNS filter

### Add your comment and screenshots

||pixel.adswizz.com
||pixel.randi.adswizz.com
||zc.adswizz.com

https://www.zennioptical.com

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
||zc.adswizz.com is in audiomack app. sorry.

**Comment by jordanswrld94** [comment]
@zloyden

**Comment by zloyden** [comment]
No problem, but could you show the request as a screenshot from the filtering log?

**Comment by jordanswrld94** [comment]
here u go 
![Screenshot_20221201_090058_Gallery](https://user-images.githubusercontent.com/118186787/205086298-1870ba97-b581-41de-98b4-b25623c02bc1.jpg)
