### ISSUE TITLE
search.brave.com

### ISSUE THREAD

**Issue by CommandGenius** [AdguardTeam/AdguardFilters#136364]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

none

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other(specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://search.brave.com/

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. I'm using Brave Browser

2. Screenshots
<details><summary>Screenshot 1:</summary>

![braveads](https://user-images.githubusercontent.com/83155590/205143877-bd45eafb-9eb4-4b5c-a7ca-24fdc90d4985.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
