### ISSUE TITLE
[iOS] mojim.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1363]
Missed ad on page:
https://mojim.com/cny100111x60x10.htm
![image](https://cloud.githubusercontent.com/assets/15856304/12535712/3904e48a-c295-11e5-8784-41fa2b62bffb.png)
FWX-791-63012

**Comment by Alex-302** [comment]
У меня чисто. Попросите нажать на крестик, чтоб  увидеть название рекламной системы.
Заодно пусть фильтры обновит.
