### ISSUE TITLE
Detecting not detecting Adguard pattern

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#136424]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.4

### What type of problem have you encountered?

Website or app doesn't work properly, AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gaypornhdfree.com/category/gay-porn-hd/page/8/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

Okay so now it’s getting weird the fix sort of worked there is moments of me refreshing the safari tab on my iPhone or retyping in the site that the website does not detect my Adguard when I click a video

but there is moments where it does detect my Adguard and I have to refresh the tab or retype and go to gaypornhdfree.com

Is there a reason this is glitching of a pattern from not detected/detected /not detected/detected 

I kind of would like it work probably and not doing this pattern

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please don't create new reports, reply in your recent.

**Comment by malicerainbow** [comment]
[](https://www.zamzar.com/download.php?uid=d192f9cb40d3c430a20e06c544cd11b-fb508a2642d28ea7&tcs=Z81&fileID=p1gj9fttsnngs5l189f1mlqik74.mp4) 

if you download this small video I made you will see what I’m talking about
