### ISSUE TITLE
Gaypornhdfree is detecting Adguard pro of iOS 

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#136410]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.4

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gaypornhdfree.com/hot-af-nate-rose/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>https://gaypornhdfree.com/hot-af-nate-rose/

2. Screenshots
<details><summary>Screenshot 1:</summary>

![550CE63F-C467-41C1-AF14-650413A0A85F](https://user-images.githubusercontent.com/118444664/205267884-d5126558-b228-4d3d-a762-a4d2cb4bb518.png)

</details>

<details><summary>Screenshot N:</summary>

![47B70A14-08CE-4594-A58A-9CE6B555DB17](https://user-images.githubusercontent.com/118444664/205267930-6c027fe1-818b-42fe-a593-9c3d11762f17.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
fixed here https://github.com/AdguardTeam/AdguardFilters/commit/310d66ab54c193a3c68844372496823c3de05ccc

**Comment by malicerainbow** [comment]
> fixed here [310d66a](https://github.com/AdguardTeam/AdguardFilters/commit/310d66ab54c193a3c68844372496823c3de05ccc)

What do you what am I supposed to do with that put it in custom filters?

**Comment by malicerainbow** [comment]
> fixed here [310d66a](https://github.com/AdguardTeam/AdguardFilters/commit/310d66ab54c193a3c68844372496823c3de05ccc)

How is my issue fixed I have no idea what your talking about

**Comment by malicerainbow** [comment]
My issue is not fixed!!!!!!!!

**Comment by malicerainbow** [comment]
Alex???????
