### ISSUE TITLE
gaypornhdfree.com

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#136416]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.4

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gaypornhdfree.com/hot-af-nate-rose/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>[NSFW] Screenshot 1:</summary>

https://user-images.githubusercontent.com/118444664/205278784-14157e69-7897-416e-8037-5e4631e9a981.png

</details>

<details><summary>Screenshot N:</summary>

</details>

This issue is not fixed!!!!!! I still have no access to this site unless I remove adguard pro of iOS of which I am paying for by the way will someone one please help me 

Alex did not fix the issue at all!!!!!!!

### Privacy

- [X] I agree to follow this condition

**Comment by malicerainbow** [comment]
I am paying for this will someone please help me!!!! No one is helping me

**Comment by zloyden** [comment]
Hi! Could you please describe what exactly is wrong? This site opens fine on my end.

**Comment by malicerainbow** [comment]
> Hi! Could you please describe what exactly is wrong? This site opens fine on my end.

Every time I click a video it won’t play it tells author of video demands you remove adblocker



and Alex close my issue ticket saying it was fixed

**Comment by zloyden** [comment]
I guess it was fixed, but let me check it.

**Comment by malicerainbow** [comment]
> I guess it was fixed, but let me check it.

No it was not 


Also what am I supposed to do with this?

@[Alex-302](https://github.com/AdguardTeam/AdguardFilters/commits?author=Alex-302)
Alex-302 committed 31 minutes ago
1 parent [2ce3937](https://github.com/AdguardTeam/AdguardFilters/commit/2ce39378b757b26c24add7586b2719d39a78587d) commit 310d66ab54c193a3c68844372496823c3de05ccc
Showing 2 changed files with 2 additions and 2 deletions.
Split Unified
    2 
[BaseFilter/sections/antiadblock.txt](https://github.com/AdguardTeam/AdguardFilters/issues/136416#diff-677c1f016aa0fea2bb12b33284039e63cebda46dc3b6774d990dbced675efa8e)
 
 @@ -646,7 +646,7 @@ igay69.com,gourmetscans.net#%#//scriptlet('prevent-setInterval', '+t.css_class.s
 @@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js|$xmlhttprequest,domain=ottverse.com
 ! if DNS filtering enabled and scriptlet does not work
 !+ PLATFORM(ios, ext_android_cb, ext_safari)
 gourmetscans.net,openculture.com##div[id$="-blanket"]
 gaypornhdfree.com,gourmetscans.net,openculture.com##div[id$="-blanket"]
 !
 ! chp_ads_blocker
 ! https://github.com/AdguardTeam/AdguardFilters/issues/94283

**Comment by malicerainbow** [comment]
> I guess it was fixed, but let me check it.

https://github.com/AdguardTeam/AdguardFilters/commit/310d66ab54c193a3c68844372496823c3de05ccc


man I supposed to copy and past something from this onto custom filters 



he did not explain anything all he did is said fix and sent link

**Comment by malicerainbow** [comment]
What am I supposed to use the link for?

like he didn’t give any explanation or instructions or directions all he said is fix and link


What am I supposed to do with that it was not coherent at all!!!!!

**Comment by zloyden** [comment]
I got this. It was actually fixed and the rule above works fine, but you should wait this update and check it in 1-2 hours.
If the problem persists after this time, feel free to write here :)

**Comment by malicerainbow** [comment]
> I got this. It was actually fixed and the rule above works fine, but you should wait this update and check it in 1-2 hours.
> If the problem persists after this time, feel free to write here :)

Wait but you didn’t answer my question am I supposed to do something with the link he sent?

**Comment by zloyden** [comment]
No, you shouldn't do with that link anything. It's just the information to know and that's all.

**Comment by malicerainbow** [comment]
> I got this. It was actually fixed and the rule above works fine, but you should wait this update and check it in 1-2 hours.
> If the problem persists after this time, feel free to write here :)
> By the way, thanks for the detalied explanation!

What are you talking about of update?

I have literally no idea what is going on am I supposed to do something with the link he sent? 

Can you please do more explaining?


What am I supposed to do with the link he sent?

**Comment by malicerainbow** [comment]
> No, you shouldn't do with that link anything. It's just the information to know and that's all.

Okay but how do I get the update?

**Comment by malicerainbow** [comment]
> I got this. It was actually fixed and the rule above works fine, but you should wait this update and check it in 1-2 hours.



but how do I get the update could you please explain instructions on how to get it?

**Comment by zloyden** [comment]
> What am I supposed to do with the link he sent?

Nothing, I've explained it here https://github.com/AdguardTeam/AdguardFilters/issues/136416#issuecomment-1335106904.

> I have literally no idea what is going on am I supposed to do something with the link he sent?

As I said here https://github.com/AdguardTeam/AdguardFilters/issues/136416#issuecomment-1335102125, you should do next:
1. Wait for the update. Usually it takes one or two hours.
2. After this time you open AdGuard for iOS, press on the update button, wait in this window ~ one minute, open the site in Safari.

**Comment by malicerainbow** [comment]
> > What am I supposed to do with the link he sent?
> 
> Nothing, I've explained it here [#136416 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/136416#issuecomment-1335106904).
> 
> > I have literally no idea what is going on am I supposed to do something with the link he sent?
> 
> As I said here [#136416 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/136416#issuecomment-1335102125), you should do next:
> 
> 1. Wait for the update. Usually it takes one or two hours.
> 2. After this time you open AdGuard for iOS, press on the update button, wait in this window ~ one minute, open the site in Safari.

Where is the update button located on the iOS app?

**Comment by zloyden** [comment]
This button is located in the main menu, where you can see the protection switch, in the upper right corner.

**Comment by malicerainbow** [comment]
![6A8603D1-41F5-4499-9842-8F56108D60B5](https://user-images.githubusercontent.com/118444664/205285260-6b2e6936-5945-4d5e-b57d-9610832d61f8.jpeg)


Is that the update button?

**Comment by zloyden** [comment]
Yep, this one. But don't check it right now, please follow my post https://github.com/AdguardTeam/AdguardFilters/issues/136416#issuecomment-1335110449.
Looks like you have some problems with content blockers. Are they all disabled? Please press `Fix it` button.

**Comment by malicerainbow** [comment]
> Yep, this one. But don't check it right now, please follow my post [#136416 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/136416#issuecomment-1335110449).
> Looks like you have some problems with content blockers. Are they all turned off? Please press `Fix it` button.

Fix it button?

**Comment by malicerainbow** [comment]
> Yep, this one. But don't check it right now, please follow my post [#136416 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/136416#issuecomment-1335110449).
> Looks like you have some problems with content blockers. Are they all turned off? Please press `Fix it` button.

Is this bad I was curious what it does and didn’t know if it the update button yet so I pressed it is that bad doing it before the 1-2 hours?

**Comment by malicerainbow** [comment]
> Yep, this one. But don't check it right now, please follow my post [#136416 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/136416#issuecomment-1335110449).
> Looks like you have some problems with content blockers. Are they all turned off? Please press `Fix it` button.

Also are you familiar with Reek developer of anti Adblock killer of which uses your extension of a custom filter

**Comment by malicerainbow** [comment]
> Yep, this one. But don't check it right now, please follow my post [#136416 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/136416#issuecomment-1335110449).
> Looks like you have some problems with content blockers. Are they all turned off? Please press `Fix it` button.

Hello?

**Comment by zloyden** [comment]
> Fix it button?

Yep.

> Is this bad I was curious what it does and didn’t know if it the update button yet so I pressed it is that bad doing it before the 1-2 hours?

Content blockers are part of the AdGuard for iOS. If they disabled, the app can't work normally.
You should turn them on in settings (iOS) - Safari - extensions - you'll see 6 extensions - turn them on.
More information there https://kb.adguard.com/en/ios/safari-web-extension#enabling-adguards-safari-web-extension.

---

All questions about AdGuard for iOS and how it works you can ask support@adguard.com.

**Comment by malicerainbow** [comment]
> > Fix it button?
> 
> Yep.
> 
> > Is this bad I was curious what it does and didn’t know if it the update button yet so I pressed it is that bad doing it before the 1-2 hours?
> 
> Content blockers are the part of the AdGuard for iOS. If they disabled, the app can't work normally. You should turn them on in settings (iOS) - Safari - extensions - you'll see 6 extensions - turn them on. More information there https://kb.adguard.com/en/ios/safari-web-extension#enabling-adguards-safari-web-extension.
> 
> All questions about AdGuard for iOS and how it works you can ask [support@adguard.com](mailto:support@adguard.com).

So in 24 hours if I still can’t gay adult videos on the website without removing adguard because it’s being detected on the site

I can come back here and report it

**Comment by malicerainbow** [comment]
[](https://www.kapwing.com/videos/6389fc91033fd20025137f6b) 

If you click this like you will see what I’m talking about

**Comment by malicerainbow** [comment]
[Detecting and not detecting Adguard ](https://www.kapwing.com/videos/6389fc91033fd20025137f6b)

**Comment by malicerainbow** [comment]
> > Fix it button?
> 
> Yep.
> 
> > Is this bad I was curious what it does and didn’t know if it the update button yet so I pressed it is that bad doing it before the 1-2 hours?
> 
> Content blockers are the part of the AdGuard for iOS. If they disabled, the app can't work normally. You should turn them on in settings (iOS) - Safari - extensions - you'll see 6 extensions - turn them on. More information there https://kb.adguard.com/en/ios/safari-web-extension#enabling-adguards-safari-web-extension.
> 
> All questions about AdGuard for iOS and how it works you can ask [support@adguard.com](mailto:support@adguard.com).

Okay so now it’s getting weird the fix sort of worked there is moments of me refreshing the safari tab on my iPhone or retyping in the site that the website does not detect my Adguard when I click a video

but there is moments where it does detect my Adguard and I have to refresh the tab or retype and go to gaypornhdfree.com

Is there a reason this is glitching of a pattern from not detected/detected /not detected/detected

I kind of would like it work probably and not doing this pattern

**Comment by malicerainbow** [comment]
[If you click this link you will see what I’m talking about ](https://www.kapwing.com/videos/6389fc91033fd20025137f6b)

**Comment by zloyden** [comment]
That's strange. Have your turned on all of the web extensions? Try to clear browser data and open the site.
Unfortunately, I can't reproduce it on my end. @AdguardTeam/filters-maintainers please take a look at this.

**Comment by malicerainbow** [comment]
> That's strange. Have your turned on all of the web extensions? Try to clear browser data and open the site.
> Unfortunately, I can't reproduce it on my end. @AdguardTeam/filters-maintainers please take a look at this.

I have cleared my safari iOS site data and all of the 6 extensions of AdGuard are on 


It’s still happening of once detecting than not detecting but it’s not permanently not detecting please someone fix this!

**Comment by malicerainbow** [comment]
> That's strange. Have your turned on all of the web extensions? Try to clear browser data and open the site.
> Unfortunately, I can't reproduce it on my end. @AdguardTeam/filters-maintainers please take a look at this.

![EAFCECF1-8971-4D19-B11C-363548E66EDA](https://user-images.githubusercontent.com/118444664/205430046-4733c8c0-9c95-4517-9203-df90c94967c5.png)

![F999AEB6-5961-4597-AB83-64EC1AC166BE](https://user-images.githubusercontent.com/118444664/205430058-dc03779c-be02-4ffd-9b79-6ae59f46e4a7.png)

**Comment by malicerainbow** [comment]
> That's strange. Have your turned on all of the web extensions? Try to clear browser data and open the site.
> Unfortunately, I can't reproduce it on my end. @AdguardTeam/filters-maintainers please take a look at this.

![5C0FEA95-785C-40E8-89AD-B8A8B3A94562](https://user-images.githubusercontent.com/118444664/205430330-6dd80754-09ad-4f78-9531-3d43dcd20a00.png)
![F0F5BEC6-ECE0-4275-B1E1-C2DCD745BBF9](https://user-images.githubusercontent.com/118444664/205430333-145db218-8540-44b1-8ddc-d67c76a93d5d.png)

**Comment by malicerainbow** [comment]
> That's strange. Have your turned on all of the web extensions? Try to clear browser data and open the site.
> Unfortunately, I can't reproduce it on my end. @AdguardTeam/filters-maintainers please take a look at this.

![Uploading 3696BE50-9385-40D1-AAAA-5845E24EADCB.png…]()

**Comment by malicerainbow** [comment]
> That's strange. Have your turned on all of the web extensions? Try to clear browser data and open the site.
> Unfortunately, I can't reproduce it on my end. @AdguardTeam/filters-maintainers please take a look at this.

![DD5B6BB1-5FA4-462B-9114-07C1352F7582](https://user-images.githubusercontent.com/118444664/205430367-981d3803-0c98-45d6-906e-871264726881.png)
![84EB93CA-C7E8-4F10-8614-26EDB83E4BB2](https://user-images.githubusercontent.com/118444664/205430370-0219abc0-ef97-4530-bc69-35b77e994ebb.png)

**Comment by malicerainbow** [comment]
> That's strange. Have your turned on all of the web extensions? Try to clear browser data and open the site.
> Unfortunately, I can't reproduce it on my end. @AdguardTeam/filters-maintainers please take a look at this.

I really would like this issue resolved please as I said I am paying for AdGuard I am not using the free version 

![A22BF2C9-0EE5-489A-BB62-A95DDDD18E73](https://user-images.githubusercontent.com/118444664/205430657-253b0fbb-b51f-4842-a922-e0346b01ee84.png)
![831D1A32-E3A0-4AEC-A62C-8E9420B43590](https://user-images.githubusercontent.com/118444664/205430659-92f9849e-50a8-4437-ac9a-d0c8312a1ca7.png)


And I want to keep supporting AdGuard with my yearly but I can’t if it can’t make sure it’s not detected on gaypornhdfree.com every single time!

**Comment by BlazDT** [comment]
Is it always the same url? Is it getting detected when you open the video directly:
https://dood.re/e/yfjo6y6y50lp10fxbtm2dre788axfux

**Comment by malicerainbow** [comment]
> Is it always the same url? Is it getting detected when you open the video directly: https://dood.re/e/yfjo6y6y50lp10fxbtm2dre788axfux

It's weird, I go to the website I mentioned and the ads are gone, but then I click on Video and it takes you to two options for the video. When I click on either option, I do full screen and it loads and does play, but when I try to fast forward the video, it plays perfectly sometimes, but sometimes it times me out and shows the "Publisher does not allow ad blocker while viewing video" screen. Only after doing that a few times does it completely work the whole time.

**Comment by malicerainbow** [comment]
> Is it always the same url? Is it getting detected when you open the video directly:
> https://dood.re/e/yfjo6y6y50lp10fxbtm2dre788axfux

Is anyone still working on this issue please? 

I am on my trial and I do not want to be charged unless this issue can actually be resolved

**Comment by BlazDT** [comment]
Please provide answer to my last post, thank you

**Comment by malicerainbow** [comment]
> Please provide answer to my last post, thank you

By same url do you mean the url of the website or the url with the page saying detecting adblocker? 

And yes when I open video it sometimes automatically pops me out of the video on full screen and into the page with the video taking up the screen of my phone saying publisher does not allow adblocker

**Comment by BlazDT** [comment]
URL with the video.
And with the URL I posted (it is the embedded video on that page)?
Is there a reason why you opened Google in the first place (on the video you uploaded)?

**Comment by malicerainbow** [comment]
> Please provide answer to my last post, thank you

Now it’s not working at all but than again I did uninstall AdGuard could that cause the filter code to not work now at all?

**Comment by malicerainbow** [comment]
> URL with the video.
> And with the URL I posted (it is the embedded video on that page)?
> Is there a reason why you opened Google in the first place (on the video you uploaded)?

**Comment by malicerainbow** [comment]
> URL with the video.
> And with the URL I posted (it is the embedded video on that page)?
> Is there a reason why you opened Google in the first place (on the video you uploaded)?

[Click this](“trim.A986C628-363B-4D15-8474-1E37CEACD77C.mp4”?)

**Comment by malicerainbow** [comment]
> URL with the video.
> And with the URL I posted (it is the embedded video on that page)?
> Is there a reason why you opened Google in the first place (on the video you uploaded)?

[Please click this link!](https://streamable.com/ntx2ka) 



please let me know if your not able to watch the video that visually explains my issue

**Comment by malicerainbow** [comment]
Is no one resolving my issue????

**Comment by malicerainbow** [comment]
> URL with the video.
> And with the URL I posted (it is the embedded video on that page)?
> Is there a reason why you opened Google in the first place (on the video you uploaded)?

Hello are you still working on my issue?

**Comment by malicerainbow** [comment]
> URL with the video.
> And with the URL I posted (it is the embedded video on that page)?
> Is there a reason why you opened Google in the first place (on the video you uploaded)?

Okay so after updating the app after uninstalling it it is back to working now and than but it’s not working every time

**Comment by jellizaveta** [comment]
@malicerainbow Please, try to add this:
`||gaypornhdfree.com/wp-content/uploads/cmdakui` 
to the User Rules. (Safari protection --> User Rules)

**Comment by malicerainbow** [comment]
> @malicerainbow Hello!
> Please, try to add this rule:`||gaypornhdfree.com/wp-content/uploads/cmdakui` to the User Rules. (Safari protection --> User Rules)

Still only working if I refresh the page multiple times

**Comment by malicerainbow** [comment]
> @malicerainbow Hello!
> Please, try to add this rule:`||gaypornhdfree.com/wp-content/uploads/cmdakui` to the User Rules. (Safari protection --> User Rules)

[Please click this link so you can see my issue is still not resolved even with user rules enabled with the user rule code](https://www.kapwing.com/videos/639053625ddec1011bf0ae24) 




Will someone please fix this!!!

**Comment by malicerainbow** [comment]
Will someone please resolve the issue please!

[My issue is still not resolved!](https://www.kapwing.com/videos/639053625ddec1011bf0ae24)

**Comment by jellizaveta** [comment]
Added rules for popup and advertising to the filter. Update should be available in 1-2 hours.

**Comment by malicerainbow** [comment]
> Added rules for popup and advertising to the filter. Update should be available in 1-2 hours.

![86849AEC-587C-48B6-AAE9-39606F78B392](https://user-images.githubusercontent.com/118444664/206231680-6e5d8bdc-6eeb-4505-8239-fa3107ce4085.png)
![1DC3B31C-6B1D-4158-A995-C4D9E3A3FF36](https://user-images.githubusercontent.com/118444664/206231694-7c99fef2-7916-43f4-89b1-77a20b98df9b.png)
![AC957739-83EC-44E1-BABE-0EAD10CF9E20](https://user-images.githubusercontent.com/118444664/206231696-93c9baf2-7653-413f-812f-79ed1e4910e1.png)
![15E327A2-9595-4D03-82EF-8C75E9DB2A4A](https://user-images.githubusercontent.com/118444664/206231700-34fb8f00-7464-4427-b2f9-3c6918a39acd.png)
![8F0EC43F-0E52-4285-A6BC-B58470FF0DCE](https://user-images.githubusercontent.com/118444664/206231701-886cbf78-2ee3-4506-82c6-13b6a246114c.png)
![F43F1E81-48C6-418C-B8CC-DCB891D754D6](https://user-images.githubusercontent.com/118444664/206231705-72399596-ef95-4910-aab7-6239c872d87d.png)
![E32DC5E4-6EEE-4255-90E8-24B0C89393C9](https://user-images.githubusercontent.com/118444664/206231709-f88804b9-4ed5-4f4d-b14c-d15eca4829de.png)
![FE6D7303-F1D6-49DF-9412-8BEF23CB7E45](https://user-images.githubusercontent.com/118444664/206231711-774aed33-1303-48ce-9b53-c8079ea6ade0.png)
![4BB78F06-A122-41E6-935F-443EA7CE104F](https://user-images.githubusercontent.com/118444664/206231716-099c32c8-3eb4-49fd-8416-1a36984b48c9.png)
![2C39B289-30F8-49EE-90C7-4FB33BDEB885](https://user-images.githubusercontent.com/118444664/206231719-1dd10c02-3242-4762-9606-3cc7e846e321.png)
![EFBF0DEE-5FD3-490F-9B4A-E91C870E8F08](https://user-images.githubusercontent.com/118444664/206231721-c8c17405-ef11-4250-a82c-f881c2012e04.png)
![ABC71CDA-7379-4AF9-8A5B-C0139FD7C14B](https://user-images.githubusercontent.com/118444664/206231723-069e8384-4d59-4f21-8db5-2e427d5827af.png)
![50EF2A6A-EE95-4A46-9681-0A6E96F012AE](https://user-images.githubusercontent.com/118444664/206231727-4a9c0a09-d63c-4d1f-a2bb-ee3d0b88602c.png)
![571F20EB-A813-467C-B7AB-A8B992F91E9F](https://user-images.githubusercontent.com/118444664/206231731-3186cf65-315a-4a05-82cc-f62f34e2604f.png)
![9EA19FFC-967E-444D-B9FC-F58AE5BE49DA](https://user-images.githubusercontent.com/118444664/206231732-fcef3724-b24e-412b-92a0-90b0b8766c97.png)
![589A9956-E1E6-48CF-8284-7796DE4A0CA1](https://user-images.githubusercontent.com/118444664/206231739-5d31d99d-4c8a-4904-a115-3deb4aea29bd.png)
![83E7259C-E21B-4DC6-B1A4-4C3ED571BF34](https://user-images.githubusercontent.com/118444664/206231743-4b1a7413-6b59-43db-93e9-2bb0c3295b3f.png)
![F292B310-8A73-4344-AC48-D3067C39BC2F](https://user-images.githubusercontent.com/118444664/206231746-c8958f85-1125-41ee-8f41-2cedcbb0f2c6.png)




This is everything I did just as you all told me and it still only works now and than 

it doesn’t work all the time unless I refresh a couple times the page

**Comment by malicerainbow** [comment]
![29E80FF4-42ED-4EB8-8CFB-E7D3870F1B28](https://user-images.githubusercontent.com/118444664/206232009-11fca75f-4b4d-4e5e-a874-8a898033057c.png)
![57D12C47-C23F-4EDA-B883-0F693CEAF53C](https://user-images.githubusercontent.com/118444664/206232013-e5a4d520-9a6b-4b3d-bc10-efd10ef47f0d.png)
![1E1F1F82-0FB7-4679-9FFB-959CFF236794](https://user-images.githubusercontent.com/118444664/206232018-b82568ef-5b62-4bb5-a193-56bc6d55cb02.png)
![33E59E31-58A9-4EE7-9BA4-0D9C6D5FF8CE](https://user-images.githubusercontent.com/118444664/206232021-8e634586-16f3-419a-9861-5b90f6fe1121.png)
![6805BF13-08C9-4B36-82FC-95AC0C7DA147](https://user-images.githubusercontent.com/118444664/206232024-6930a38c-281a-4ad7-b46e-ae367b53b32e.png)
![668041AE-6C69-44EB-811C-6A4673F61A53](https://user-images.githubusercontent.com/118444664/206232028-43657661-00d5-4e57-9117-015658e5cb10.png)
![DD58583B-A63A-4E63-B457-A33B14F1A2E5](https://user-images.githubusercontent.com/118444664/206232032-32a045c8-4754-4955-a446-df97c9472b06.png)
![61EE1EF6-5F5B-492A-A1FC-94A48CF0D37D](https://user-images.githubusercontent.com/118444664/206232037-926c56c7-c79a-4ea6-b8c6-fa70a9fe1bd0.png)
![C501D433-63C9-4DF3-A4F4-BBF0B672D959](https://user-images.githubusercontent.com/118444664/206232040-747c75c0-40e4-4e8a-a0c6-7a52403c753f.png)
![7F63357E-265C-456A-ACEB-4DC944720AF1](https://user-images.githubusercontent.com/118444664/206232043-8c2cfddf-0617-42ec-9b99-d18f683fe302.png)
![EDA91D76-D4DC-47AD-BADB-D0FFCFD4C5CD](https://user-images.githubusercontent.com/118444664/206232048-5916cee8-cdda-43b9-93e4-14006740ad59.png)
![02BACBF3-EBF3-46E6-85E2-D06757401E23](https://user-images.githubusercontent.com/118444664/206232049-231def99-2527-47a4-b955-4d0121b9c143.png)
![2C1CCDD4-7625-4307-BC81-58C7338C92D9](https://user-images.githubusercontent.com/118444664/206232051-1a10c718-481f-49c8-ad61-737858388442.png)
![6B870481-ACFB-4668-AB4A-7CFC7AEBF697](https://user-images.githubusercontent.com/118444664/206232056-9cf7f77d-5087-47d3-8432-20a90281c199.png)
![A4251392-C61E-4CDE-A7B2-A11250532067](https://user-images.githubusercontent.com/118444664/206232059-23a09327-b5d9-47ea-a211-b1a6d62156d2.png)
![7D18134A-0326-4146-9EDC-263ED51B562D](https://user-images.githubusercontent.com/118444664/206232060-b9ba21c4-242a-4561-825d-086031a17b47.png)
![82215202-08AA-444D-BFB3-57583DDA8633](https://user-images.githubusercontent.com/118444664/206232065-a4bfbf42-c567-4a1f-8669-8fb5492b562a.png)
![5FAFC75C-104C-40C0-9967-A9060AF39F02](https://user-images.githubusercontent.com/118444664/206232068-3e452a54-392e-4581-b5e7-8f98a121519b.png)


This is everything I did as requested and it still only works now and than unless I refresh the page a couple times

**Comment by malicerainbow** [comment]
> Added rules for popup and advertising to the filter. Update should be available in 1-2 hours.

Please do not lose this issue it is not resolved

**Comment by malicerainbow** [comment]
Could someone please take remote access or at least remote screen share of my phone!!!??????

**Comment by malicerainbow** [comment]
> Added rules for popup and advertising to the filter. Update should be available in 1-2 hours.

Could someone please take remote access or at least remote screen share of my phone????!!!!

**Comment by malicerainbow** [comment]
Is someone still working on my issue??? Hello????

**Comment by jellizaveta** [comment]
@malicerainbow  Hi!
Please do not enable all filters in the AdGuard App. Leave only the necessary ones: AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Annoyances filter, AdGuard Social Media filter,AdGuard Tracking Protection filter
Does adblock or popup still appear on the page?

**Comment by jellizaveta** [comment]
@malicerainbow Hi! Does adblock or popup still appear on the page?

**Comment by malicerainbow** [comment]
> @malicerainbow Hi! Does adblock or popup still appear on the page?

Yes it’s still detecting my adblocker!!!!
