### ISSUE TITLE
Sometimes image not loading

### ISSUE THREAD

**Issue by Kieaer** [AdguardTeam/AdguardFilters#136590]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android, AdGuard for Windows

### AdGuard version

Android 3.6.10 (51)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

https://m.cafe.naver.com, https://cafe.naver.com, https://arca.live

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, List-KR

### Add your comment and screenshots

Adguard for Windows and android are all the same issues.
This problem continues with changes to mobile and PC devices.

Not all times.
Image loading failures often occur, and sometimes both PC and Android fail to load CSS, causing web pages to become unrecognizable.

At this time, everything worked fine when the Adguard filtering was turned off.

Most of them load correctly, but sometimes they don't and it doesn't seem to be a problem with the filter list.

Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot_20221204-130810_Firefox_Beta](https://user-images.githubusercontent.com/44261958/205473958-8d1ff39e-b203-4eef-ad1d-9362455c7eb9.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
@Kieaer Do you have a debug log of Adguard?

**Comment by Kieaer** [comment]
@piquark6046 [adg_logs_7.11.4107.0_1206_1558.zip](https://github.com/AdguardTeam/AdguardFilters/files/10163587/adg_logs_7.11.4107.0_1206_1558.zip)

Adguard for Windows debug log.
The tested web page URL is https://cafe.naver.com/fx8300/972030.

**Comment by piquark6046** [comment]
@Kieaer With the log file, please open new issue at [CoreLibs](https://github.com/AdguardTeam/CoreLibs/issues).

**Comment by Kieaer** [comment]
Moved https://github.com/AdguardTeam/CoreLibs/issues/1703
