### ISSUE TITLE
www.dx.com

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#13655]
[www.dx.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://www.dx.com/)

 Верхний баннер: `dx.com###commonHeadBannerPanel`

<details><summary>Screenshot:</summary>

![www dx com](https://user-images.githubusercontent.com/17948007/37805655-9cbf13e0-2e4c-11e8-928b-0bf3ac0b4872.png)
</details>

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.8.5 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
добавил
