### ISSUE TITLE
SCAM

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#136664]
SCAM links

https://www.cloudways.com/en/

https://promotionfitt.com/metacoin/it?utm_source=b32thankyou.blogspot.com&utm_medium=1001&utm_campaign=italy&utm_term=b3/2-reveblueita-metacoin-linkedin&utm_content=metacoin

https://scrypto-pro.com/?p=1243920849814367&ad_id=6304912691943&placement=Facebook_Desktop_Feed&bmjstq11=pwpwmc3&creative_id

https://bkkentweek.com/image-collection/giulia-pozzi

https://tracktrafficopwe.com/nlp/index.php?pid=838&offer_id=4190&sub1=1981517oj5m2t6o117&url_bnm_redirect=https%3A%2F%2Fn.cleantrafficrotate.com%2Fclick

https://12641db02e02.freakylotto.com/prizewheel-fb?ctrack=1670190868.2041509102&traffic=eyJpdiI6Ik9Eb2d3MmxJQVwvbDlaUGtLVmoyTk5BPT0iLCJ2YWx1ZSI6IlwvUzJETWFnbWZDVlNyWWZsalI1U09kb0JYcHlQUnhEVjZOS3ZrM3BaaGFHUlBuMytLVXlKSFhxb09BdWdKZWFCIiwibWFjIjoiMjc0ZmMxMGZmZjU1ZGVjZjhjMjRiZDRhYmY4MzkwMWMxNDU3MmU1Y2ZlZDE0MzhhMjc0NjA2NjRhZjBmMjBhZiJ9&prize=iphone-14&out=eyJpdiI6IlZwdVlDdWFsOXpTeHRhYzh5OE0zMVE9PSIsInZhbHVlIjoiK2RDSUdmXC9md3V0WUhNRjNXZWFxWDR4cm9Pclk1eG9UN29OVURjZitFT2pLeVprZjhSam95TEdzU21pSVBJRkxqSXZtT216d1lFbTZOMHRaaWhMbjRSa3ZhUUgwQ3lqWFJoWmpFZjFjK1E3bGNxUnBiQXJKWHhoSUhvKzlRTDFYclc0ak00RXRDUit5VTVueVk0bVpYTGZlMENPYW5xbzhQYUI2cFBBczlnWDFTcnRUUWplYkl0azdOTVlzZzIxcUE3b1J1UlA2cUlacUk2UDVaTEFFWGY1aDRlSnJyVEJSdHQ4cElQdTlhRVE9IiwibWFjIjoiMTZmYjY0M2JjMWFkM2M0MjU2Y2M2Y2I3MmE0ZDdjZTgxZDdlMTZlNDY0MDYyYzIzMjY3NzBjN2ZmNmYzOGQ3NiJ9

https://in-page-push.net/clicks/fVl28X1bOH6I5sXzCiFjRWeX_oDRWv3L23SoVlxJQT1HUZAb6pVpkqhTSveELD6i8hJLNfnHivrNyKBG_u1m_jJ_XsxFdCECjExQxi-BmEh3qWU_b4nXsw5VFUXxKTgIyoIwuIjPZ4nAsOpyA3FyqEhFso31Nv6_w8FlRtDY3mQbVUQIRVRLIPheSh2gYtZsBbl9CdG12dXIBh54XQrFco4PFKV2JlGxKbJ12m-37C_7nQnIvBcqmSMg6CU4S74JUtPEfXMcU3cCFZToBYpmL6mE-eIqSN-b5S8vgwQQccrogGJWfRum3ZuBWyhskK-9vVYD1JwhFTXG9PQ9SIO15ucwMNeDY_z8sGRx0DiGWJa27Z8ko5pbPPayxHTn0ajgmuG95NgT74RmUqUHtQPMqquhTtLl5nDushFKU199EFcb1Ya5A1sYiGu1EE_obi3WgjxFJGs45vviVA_TmijtujvGnNf0yAwsG3x1htEvmQnNlN4CTd1yprE_m35ik_AlVRRdBKelaB-oRs2QEPOxipRkQW6jEFIa1Hn65_0JMGE76mytc2pyr4To8Sim1CP6ZXEKdaNm1xS3T1_SGFiqDg==?_z=5381241&b=15625814

https://fortunesurvey.top/finance-survey.html?z=4077451&offer_id=2025&var=2243_25596519&ymid=638c910c14faad0001a92905&utm_campaign=2243_25596519&utm_medium=4077451&utm_content=zd_public_v2

https://inoradde.com/4/4292573/?var=4077451&var3=null&ymid=2243_25596519

https://ebaaa.xyz/1837797e66/fed1537d80/?campaign=dGZZc0Nla045ZHlNK3YwMVByYmdqZz09&clicked=1&placementName=ROTATOR&cv=XrdiCdGrGAGdrpCGAGdkkCxCrjANrxGNAdNZikCZCGpCrdCpxdCrdCrCrGCxCZiGZGjAddCCAZx_94409&yxDom=dXByaW1wLmNvbQ==_99fc24843f51da23d36abbfd0ce9aff2&convertedAs=1&refferer=3548950694_aHR0cDovLzU5MzE3NC55bGxpeC5jb20=&realRef=V2JKVlhUc3hPazhFd284YWh5TmpFa1loTGJwbDYxcTdNNTBBL0s4cVMwZz0=&ecpm_choosed=5&capSettings=dXByaW1wLmNvbXwxMDAwMDB8MjR8NjM3Njg=&generic_choosed=4199&redirectInfo=Q1R4cTZBa3dkUkhhdkFQTU9ua3NOQT09

https://1670156627.m-wlmw.com/af.php?hash=XrdiCdGrGAGdrpCGAGdkkCxCrjANrxGNAdNZikCZCGpCrdCpxdCrdCrCrGCxCZiGZGjAddCCAZx_94409&refferer=aHR0cDovLzU5MzE3NC55bGxpeC5jb20=&user_agent=TW96aWxsYS81LjAgKGlQaG9uZTsgQ1BVIGlQaG9uZSBPUyAxNl8xXzEgbGlrZSBNYWMgT1MgWCkgQXBwbGVXZWJLaXQvNjA1LjEuMTUgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzE2LjEgTW9iaWxlLzE1RTE0OCBEdWNrRHVja0dvLzcgU2FmYXJpLzYwNS4xLjE1&capSettings=dXByaW1wLmNvbXwxMDAwMDB8MjR8NjM3Njg=&url78456=aHR0cHM6Ly92Y3Zjdi53b3JsZC9nby5waHA/Z289aHR0cHMlM0ElMkYlMkZnZXQuY29udGVuZm9yZHBob25lLmNvbSUyRnNsJTNGaWQlM0Q2MzIwOTY1ZTBhZjU4ZjNkYzQ0MWI0NWQlMjZwaWQlM0QyMjQzJTI2c3ViMSUzRDMwYWZmQzE2NzAxNTY2MjdhZmZjZjVhMmQxMzM5OTA5YTA2M2E0OTglMjZzdWI1JTNEMjU1OTY1MTkmZG89YzM0MDVhNjAxZmJhZGQzYWIxNzgzOTRiOTUwYzdjNWE=

https://getsurv4you.org/link?z=4870721&var=2243_25596519&ymid=638c9154fb5eb5000121044b

https://easymoneysurvey.space/finance-survey.html?z=4493500&offer_id=2897&var=2243_25596519&ymid=638c91713c251b0001db5952

**Comment by DandelionSprout** [comment]
It still baffles me why or even how that reporter keeps showing up as "ghost", as I'm beginning to wonder whether the reporter has even the faintest knowledge how GitHub works like.

**Comment by Guchcy** [comment]
> It still baffles me why or even how that reporter keeps showing up as "ghost", as I'm beginning to wonder whether the reporter has even the faintest knowledge how GitHub works like.
> 
> Furthermore, they should probably use codewrapping of their very danger-potent links as well.

I just don’t really need a permanent GitHub account. I want to stay anonymous (many reasons). I would like to report it though official tool, but it has no «scam» report title. So I need to do something like this.

**Comment by DandelionSprout** [comment]
It sure sounds like a complicated strategy, though your explananation does make 100% sense.

**Comment by DandelionSprout** [comment]
Regarding the report title, it seems the AdGuard team has been very slow with implementing the "Dangerous site" button from the GitHub report form, on their AdGuard website report form: 
![image](https://user-images.githubusercontent.com/22780683/205665081-9aeef04a-08c1-43cf-83c2-d6725d1f8a91.png)

I've got good contacts in the adblocking community, and would be able to speed up that process, provided I can figure out where the AdGuard team intends for webform changes to be suggested.

**Comment by Oniqqqq** [comment]
thanks! Added to safe browsing list

**Comment by Hvhcycyx** [comment]
> Okay, I think I've suggested it now. The support case number is 692072, if any AdGuard Team members were to be interested about it.

Thanks you again! You had changed internet to a bit better:)
