### ISSUE TITLE
finnkino.fi

### ISSUE THREAD

**Issue by stdedos** [AdguardTeam/AdguardFilters#136718]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

N/A

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

finnkino.fi

### What filters do you have enabled?

AdGuard URL Tracking filter

### Add your comment and screenshots

https://www.finnkino.fi/avatar?utm_source=diIZJYymQX&utm_medium=ufOhU&utm_campaign=RWvSBE#MdNpW&utm_content=OGGsgTuf&sc_src=WEyLy]96428956&sc_lid=431252023&sc_uid=WvHbLFyPhx&sc_llid=02393&sc_customer=920073&submitted=KGzB#submitted5674

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
On my end tracking parameters are stripped.

**Comment by stdedos** [comment]
Oooh ... they are snnnnnnnnnnnnnnneeeeaky. They hid them on the anchor 😓 🤦
