### ISSUE TITLE
Gaypornhdfree 

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#136899]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.4

### What type of problem have you encountered?

Missed ads or ad leftovers, Website or app doesn't work properly, AdGuard gets detected on a website, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gaypornhdfree.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

Please read this if this issue is closed with no responses or comments saying fix of base filter I am canceling my subscription with adguard premium 

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

no one is helping me with my issue and I’m ready to just cancel my subscription!

my issue has been closed even thou it’s not resolved I have to refresh the page multiple times for it to finally not detect my adguard 

and I have had to uninstall reinstall adguard from the app store, I have had to clear history and website data on settings-safari 

I have disabled and re-enabled the adguard 6 content blocker extensions in settings-safari I have clicked the update button and have updated multiple times

I’m getting upset that no one is resolving my issue and my issue has been marked closed I am literally ready to cancel my premium subscription 

man’s now I don’t know if uninstalling or reinstalling has caused this but now it’s not working at all when I refresh the page multiple times

Can someone please take remote access or at least screen share of my phone, there is plenty of screen sharing apps etc that would allow this I just feel more comfortable having someone actually seeing my screen to see what the issue might be 

This is warning close this issue and not even respond on it or show me you fixed it in on base filter and I’m canceling my subscription 

### Privacy

- [X] I agree to follow this condition

**Comment by gototheskinny** [comment]
Hi, this issue is not there for me. Your enabled filters are not enough for what your needs.. Especially for this site. Recently my issues has been ignored as well especially sites like this one. I get the maintainers but full page ads are high enough priority IMO but they ignored. I love this app but of course like everything in life nothing is perfect.

YOU NEED and HAVE TO to enable the advanced protection first and then  u need to enable ANNOYANCE filter!! this filter will solve your problem for sure bc in my end this site works almost perfectly.

**Comment by malicerainbow** [comment]
> Hi, this issue is not there for me. Your enabled filters are not enough for what your needs.. Especially for this site. Recently my issues has been ignored as well especially sites like this one. I get the maintainers but full page ads are high enough priority IMO but they ignored. I love this app but of course like everything in life nothing is perfect.
> 
> YOU NEED and HAVE TO enable the advanced protection first and then u need to enable ANNOYANCE filter!! this filter will solve your problem for sure bc in my end this site works almost perfectly.
> 
> Edit: The easier way to report issues to this repo is in the adguard app. You should go to settings in the adguard app than tap the report issues button it'll redirect to the reporting page of adguard and it's so much more convenient for the reporter and the maintainers.

Wait so your able to watch any of the gay porn videos on gaypornhdfree.com and you don’t need to refresh multiple times or once for you to than be able to watch the video without it detecting your adguard adblocker?

**Comment by malicerainbow** [comment]
> Hi, this issue is not there for me. Your enabled filters are not enough for what your needs.. Especially for this site. Recently my issues has been ignored as well especially sites like this one. I get the maintainers but full page ads are high enough priority IMO but they ignored. I love this app but of course like everything in life nothing is perfect.
> 
> YOU NEED and HAVE TO enable the advanced protection first and then u need to enable ANNOYANCE filter!! this filter will solve your problem for sure bc in my end this site works almost perfectly.
> 
> Edit: The easier way to report issues to this repo is in the adguard app. You should go to settings in the adguard app than tap the report issues button it'll redirect to the reporting page of adguard and it's so much more convenient for the reporter and the maintainers.

![958C810E-3352-4B16-BC59-6EC212E47DCD](https://user-images.githubusercontent.com/118444664/206346871-53d92fff-0755-4f98-af7c-c9a3e20c7497.png)
![EB98BF7E-887B-4EE0-BDD3-C7BF47C18647](https://user-images.githubusercontent.com/118444664/206346875-6f3a1255-4518-4dc0-bad3-daf7cd8b671a.jpeg)
![143AE417-270B-4642-9027-A06951595A06](https://user-images.githubusercontent.com/118444664/206346880-93f4b4a9-911f-4480-ab33-a6ad28d18fc3.png)
![99BD0675-D69C-4260-8E93-64BD25F02C42](https://user-images.githubusercontent.com/118444664/206346886-a6bc2247-4b49-4493-8125-094aac6c0786.png)

**Comment by malicerainbow** [comment]
> Hi, this issue is not there for me. Your enabled filters are not enough for what your needs.. Especially for this site. Recently my issues has been ignored as well especially sites like this one. I get the maintainers but full page ads are high enough priority IMO but they ignored. I love this app but of course like everything in life nothing is perfect.
> 
> YOU NEED and HAVE TO enable the advanced protection first and then u need to enable ANNOYANCE filter!! this filter will solve your problem for sure bc in my end this site works almost perfectly.
> 
> Edit: The easier way to report issues to this repo is in the adguard app. You should go to settings in the adguard app than tap the report issues button it'll redirect to the reporting page of adguard and it's so much more convenient for the reporter and the maintainers.

Would you be willing to do screen share with me so maybe you can direct me of what exactly I need to do of what order?

**Comment by malicerainbow** [comment]
> > > Hi, this issue is not there for me. Your enabled filters are not enough for what your needs.. Especially for this site. Recently my issues has been ignored as well especially sites like this one. I get the maintainers but full page ads are high enough priority IMO but they ignored. I love this app but of course like everything in life nothing is perfect.
> > 
> > 
> > > 
> > 
> > 
> > > YOU NEED and HAVE TO enable the advanced protection first and then u need to enable ANNOYANCE filter!! this filter will solve your problem for sure bc in my end this site works almost perfectly.
> > 
> > 
> > > 
> > 
> > 
> > > Edit: The easier way to report issues to this repo is in the adguard app. You should go to settings in the adguard app than tap the report issues button it'll redirect to the reporting page of adguard and it's so much more convenient for the reporter and the maintainers.
> > 
> > 
> > ![958C810E-3352-4B16-BC59-6EC212E47DCD](https://user-images.githubusercontent.com/118444664/206346871-53d92fff-0755-4f98-af7c-c9a3e20c7497.png)
> > ![EB98BF7E-887B-4EE0-BDD3-C7BF47C18647](https://user-images.githubusercontent.com/118444664/206346875-6f3a1255-4518-4dc0-bad3-daf7cd8b671a.jpeg)
> > ![143AE417-270B-4642-9027-A06951595A06](https://user-images.githubusercontent.com/118444664/206346880-93f4b4a9-911f-4480-ab33-a6ad28d18fc3.png)
> > ![99BD0675-D69C-4260-8E93-64BD25F02C42](https://user-images.githubusercontent.com/118444664/206346886-a6bc2247-4b49-4493-8125-094aac6c0786.png)
> 
> > !https://user-images.githubusercontent.com/51786709/206347326-af85363b-e972-47ea-959a-7de036eb514a.MOV

I’m sorry what we’re you trying to respond with?

**Comment by gototheskinny** [comment]
> > > > Hi, this issue is not there for me. Your enabled filters are not enough for what your needs.. Especially for this site. Recently my issues has been ignored as well especially sites like this one. I get the maintainers but full page ads are high enough priority IMO but they ignored. I love this app but of course like everything in life nothing is perfect.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > YOU NEED and HAVE TO enable the advanced protection first and then u need to enable ANNOYANCE filter!! this filter will solve your problem for sure bc in my end this site works almost perfectly.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Edit: The easier way to report issues to this repo is in the adguard app. You should go to settings in the adguard app than tap the report issues button it'll redirect to the reporting page of adguard and it's so much more convenient for the reporter and the maintainers.
> 
> > > 
> 
> > > 
> 
> > > ![958C810E-3352-4B16-BC59-6EC212E47DCD](https://user-images.githubusercontent.com/118444664/206346871-53d92fff-0755-4f98-af7c-c9a3e20c7497.png)
> 
> > > ![EB98BF7E-887B-4EE0-BDD3-C7BF47C18647](https://user-images.githubusercontent.com/118444664/206346875-6f3a1255-4518-4dc0-bad3-daf7cd8b671a.jpeg)
> 
> > > ![143AE417-270B-4642-9027-A06951595A06](https://user-images.githubusercontent.com/118444664/206346880-93f4b4a9-911f-4480-ab33-a6ad28d18fc3.png)
> 
> > > ![99BD0675-D69C-4260-8E93-64BD25F02C42](https://user-images.githubusercontent.com/118444664/206346886-a6bc2247-4b49-4493-8125-094aac6c0786.png)
> 
> > 
> 
> > > !https://user-images.githubusercontent.com/51786709/206347326-af85363b-e972-47ea-959a-7de036eb514a.MOV
> 
> 
> 
> I’m sorry what we’re you trying to respond with?

Sorry github f.ed up the video here is the proper one
[https://www.veed.io/view/1ed33574-df43-4b29-b5ef-9f0fb2db7b00?sharingWidget=true&panel=share](https://www.veed.io/view/1ed33574-df43-4b29-b5ef-9f0fb2db7b00?sharingWidget=true&panel=share)

**Comment by gototheskinny** [comment]
Simply there is not issues in the filters.
I'm suggesting you to reset the adguard app. Than you enable these filters except the local filters like Turkish or German ones :
![image](https://user-images.githubusercontent.com/51786709/206349778-825a09b2-d4d8-4fcb-9235-800a0931ee3c.png)

Problem solved. You don't need to enable every annoyance filter u just need the adguard main annoyance filter and fanboy annoyance filter

**Comment by Alex-302** [comment]
Don't quote and post porn mages.

**Comment by malicerainbow** [comment]
> Don't quote and post porn mages.

You guys keep telling me to not make new threads yet no one has still responded on this one anymore

**Comment by malicerainbow** [comment]
No one is responding to this thread anymore

**Comment by malicerainbow** [comment]
> Don't quote and post porn mages.

So wait the website gaypornhdfree.com is working for you of not detecting your AdGuard every single time you select a video and play it?
