### ISSUE TITLE
[iOS] iclouddnsbypass.com - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1368]
Пропущена реклама на странице:
https://iclouddnsbypass.com/ru/welcome-to-icloud-freedom-project/

![image](https://cloud.githubusercontent.com/assets/15856304/12535823/ed72b7c8-c298-11e5-8b96-7b4ef5c83c9e.png)
![image](https://cloud.githubusercontent.com/assets/15856304/12535825/f42ba55c-c298-11e5-89d9-b0df127b0c92.png)

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.75.6 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.50 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.6 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.87 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.30.9 Enabled=YES
ID=6 Name="German filter" Version=1.0.22.76 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.30 Enabled=YES
LJN-434-63444

**Comment by Alex-302** [comment]
@evgeniy-ADG 
нужно на реальном девайте проверить. На маке в сафари с расширением чисто.
