### ISSUE TITLE
Website is detecting my adblocker 

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#136937]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.4

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gaypornhdfree.com/angels-unleashed-ricky-diego-with-brock-banks/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

no one is helping me no one and I’m ready to just cancel my subscription with adguard premium will someone please help me!!!!!

it’s now saying no updates found on adguard and now the filter coding isn’t working at all iv refreshed the website 8 times still detect adblocker

No one is helping me!!!!!

### Privacy

- [X] I agree to follow this condition

**Comment by malicerainbow** [comment]
It’s not completed!!!!

stop closing

**Comment by Alex-302** [comment]
I can't reproduce this issue. Please check when all filters are disabled. If no problem - enable one by one with checking.

**Comment by malicerainbow** [comment]
> I can't reproduce this issue. Please check when all filters are disabled. If no problem - enable one by one with checking.

What do you mean you can’t reproduce the issue please explain?

You mean disable all my filters and than go to the site? How will that prove anything the Adblocker would be turned off

enable 1 by 1? You mean the six in settings and than safari extensions? Or do you mean the filters in safari protection on the adguard app?

**Comment by malicerainbow** [comment]
> I can't reproduce this issue. Please check when all filters are disabled. If no problem - enable one by one with checking.

Please continue communication with me!!!

could I please also share my screen with an app please perhaps with Google hangout or something?

I need someone to actually see my phone as I’m doing what I’m told of which order

**Comment by malicerainbow** [comment]
> I can't reproduce this issue. Please check when all filters are disabled. If no problem - enable one by one with checking.

Are you using IOS mobile device? For instance I’m iPhone 7 Plus

Are you using an iPhone when going to the site and are you checking that you can actually watch the videos without the site stopping the video and alerting you that your Adblocker has been detected?

where you have to refresh the page multiple times for it no longer detect?

**Comment by malicerainbow** [comment]
No one is responding to this thread either

and you wonder why I make new issue tickets

**Comment by malicerainbow** [comment]
> I can't reproduce this issue. Please check when all filters are disabled. If no problem - enable one by one with checking.

So wait the website gaypornhdfree.com is working for you of not detecting your AdGuard every single time you select a video and play it?
