### ISSUE TITLE
Not getting updates/website detecting Adblocker every time now

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#136984]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.4

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gaypornhdfree.com/?ref=mygaysites

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>
I have uninstalled and reinstalled the Adguard app multiple times could doing that interfere with getting updates? Or could that cause the base filter that Alex added a new code specifically for gaypornhdfree.com to no longer work? My iPhone is iPhone 7 Plus operating system 15.7.1 safari version 15.7.1

All I know is now if I click the updating button on the adguard app it saids no updates found. And the website is now detecting my adblocker every time no matter how many refreshes of the page I do. Could someone also please tell me what are the exact filters I must have enabled for in safari protection of the app in order for the added code Alex did to work? 

I have set up the six Adguard extensions on settings-safari of Aduard custom-Adguard general-Aduard other-Adguard privacy-Adguard security-Adguard-social 

each one is enabled 

I have gone to gaypornhdfree.com selected the aA icon on the left of the url bar of safari picked manage extensions and made sure adguard was enabled for advanced protection

I also clicked on adguard on the list shown when you click aA and checked to make sure safari protection specifically for that website is enabled

I have went also to setting-safari and selected

delete history and website data I have also selected close tabs afterwards 

I have added the user rule that Alex told me to add I have done everything I believe I was told of the exact order

but just in case could someone please direct me to the steps again of the exact order 

to make sure I have not missed a step or done it in the wrong order

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

If someone could please respond of the exact order of the steps needed for this to work I could implement then immediately 

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
As for me, these two simple filters that Alex added can not be removed permanently by uninstalling the application.

They will come right back with a fresh download of AdGuard Base.

After the message about "no update", try leaving the AdGuard application active for a minute and then only open the browser.

**Comment by BlazDT** [comment]
Did you disable all the other filters as told in initial issue?

**Comment by malicerainbow** [comment]
> Did you disable all the other filters as told in one of your older issues (as told, please do not open several topics about the same issue?

Which filters am I supposed to keep disabled?

**Comment by malicerainbow** [comment]
> As for me, these two simple filters that Alex added can not be removed permanently by uninstalling the application.
> 
> They will come right back with a fresh download of AdGuard Base / Turkish.
> 
> After the message about "no update", try leaving the AdGuard application active for a minute and then only open the browser.

What do you mean download of AdGuard Base / Turkish? 

You mean download as in reinstalling the app from App Store?

**Comment by BlazDT** [comment]
Only having enabled Base filter and Mobile Ads filter enabled.

**Comment by malicerainbow** [comment]
> Only having enabled Base filter and Mobile Ads filter enabled.

What about social widgets and annoyances should I have any of those filters enabled or no?

**Comment by malicerainbow** [comment]
> Only having enabled Base filter and Mobile Ads filter enabled.

![Uploading 17EA4F09-D3BB-4D1E-83A2-E37515B8416C.png…]()

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/136984#issuecomment-1344441740 = yes

https://github.com/AdguardTeam/AdguardFilters/issues/136984#issuecomment-1344546161 = leave open 60 seconds after last gray bar disappear.

**Comment by malicerainbow** [comment]
> [#136984 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/136984#issuecomment-1344441740) = yes
> 
> [#136984 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/136984#issuecomment-1344546161) = leave open AG app 60 seconds after last gray bar disappear. Later disable sections other than Ad Blocking (aka AdGuard Base Filter and AdGuard Mobile Filter) if page still detect AdGuard.
> 
> Turn on Filter lists of annoying items, anti-social media and those for protection privacy only after the adblock detection message disappears, and do it so that 1 subscription per section arrives (Continuing to wait until the last gray bar and 60 seconds to avoid filtering failure). Turning on one by one may allow us to determine what Filter list is malfunctioning with the site - but there is no guarantee that someone will quickly catch what is causing the error in the Filter list.
> 
> At worst scenario, you need technical assistance from the "developers" of the application. Someone maybe can direct you how to write to them (form / e-mail / forum section).

So let me see if I got this exact you want me to reinstall AdGuard app after uninstalling it than you want to keep the app open and wait for the last grey bar update on the bottom of the app to disappear than you want me to enable only  adblocking of base filter and the Mobil filter 
Go back to gaypornhdfree.com 

check to make sure the adblocker is not detected at all ever?

And than this is where I get confuse are you than wanting me to enable each filter but one at a time of where I enable one wait for gray bar to disappear than go to the site see if adblocker gets detected if not go back to app and enable another filter wait for gray bar to disappear than go to site and see if adblocker is detected of a sequence pattern to figure out which filter is causing the site to still sometimes detect the adblocker?


I don’t understand what you mean by this thou 

“and do it so that 1 subscription per section arrives” ?



the (Continuing to wait until the last gray bar and 60 seconds to avoid filtering failure)

is what you mean by when you enable a filter wait 60 seconds and for the grey bar to disappear than go to the site gaypornhdfree.com see if adblocker is detected if not go back to app repeat the process over and over to figure which filter is causing the sometimes error?

am I correct of what you meant Krystian?

And could you answer what you meant by the 1 subscription per section arrives?

**Comment by BlazDT** [comment]
Please try these rules in user filter (each rule is a new line):

```
@@||i.doodcdn.co/ads/ad.js
dood.re,gaypornhdfree.com#@#.skyscraper.ad
dood.re,gaypornhdfree.com#@#.textad
dood.re,gaypornhdfree.com#@#.google-ad
dood.re,gaypornhdfree.com#@#.adsBox
dood.re,gaypornhdfree.com#@#.TextAd
dood.re,gaypornhdfree.com#@#.AdsBox
```

After adding the whole block, please wait for about 1 minute in the same window and then check again. If DNS protection is enabled, please disable.
And as I asked in one of the previous threads, is it working if you open the video directly, example:

https://dood.re/e/8yyos8t9bpw7okmexi9nt116nvy6v7v

**Comment by malicerainbow** [comment]
> Please try these rules in user filter (each rule is a new line):
> 
> ```
> @@||i.doodcdn.co/ads/ad.js
> dood.re,gaypornhdfree.com#@#.skyscraper.ad
> dood.re,gaypornhdfree.com#@#.textad
> dood.re,gaypornhdfree.com#@#.google-ad
> dood.re,gaypornhdfree.com#@#.adsBox
> dood.re,gaypornhdfree.com#@#.TextAd
> dood.re,gaypornhdfree.com#@#.AdsBox
> ```
> 
> After adding the whole block, please wait for about 1 minute in the same window and then check again. If DNS protection is enabled, please disable. And as I asked in one of the previous threads, is it working if you open the video directly, example:
> 
> https://dood.re/e/8yyos8t9bpw7okmexi9nt116nvy6v7v

Nope the video you just sent as a link would not let me fast forward it immediately said detecting adblocker

**Comment by malicerainbow** [comment]
> Please try these rules in user filter (each rule is a new line):
> 
> ```
> @@||i.doodcdn.co/ads/ad.js
> dood.re,gaypornhdfree.com#@#.skyscraper.ad
> dood.re,gaypornhdfree.com#@#.textad
> dood.re,gaypornhdfree.com#@#.google-ad
> dood.re,gaypornhdfree.com#@#.adsBox
> dood.re,gaypornhdfree.com#@#.TextAd
> dood.re,gaypornhdfree.com#@#.AdsBox
> ```
> 
> After adding the whole block, please wait for about 1 minute in the same window and then check again. If DNS protection is enabled, please disable. And as I asked in one of the previous threads, is it working if you open the video directly, example:
> 
> https://dood.re/e/8yyos8t9bpw7okmexi9nt116nvy6v7v

Can you please take remote access or at least we do an app where I can video call you and share my screen!!! So you can direct me?!!! Please!!!

**Comment by BlazDT** [comment]
Please stop double/triple posting. As you now visited the embedded video it is a bit easier to determine cause of adblock message. Have to check on another iOS device.

Is DNS protection enabled or disabled?

**Comment by malicerainbow** [comment]
> Please stop double/triple posting. As you now visited the embedded video it is a bit easier to determine cause of adblock message. Have to check on another iOS device.
> 
> Is DNS protection enabled or disabled?

DNS protection is not enabled, can you please take remote access of my phone by app or at least do zoom or something so I share screen my phone screen and you can direct me!!!! Please!!!!!

**Comment by BlazDT** [comment]
Such thing is not possible for me. I even forced the site to detect my device by blocking the elements and it will not detect me.
On my iPhone and iPad it is not reproducible (even when I disable Advanced protection). When you disable AdGuard completely, is it not detected on that link I posted (dood.re)?
@AdamWr @zloyden can you reproduce on that dood.re iframe page?

**Comment by malicerainbow** [comment]
> Such thing is not possible for me. I even forced the site to detect my device by blocking the elements and it will not detect me.
> On my iPhone and iPad it is not reproducible (even when I disable Advanced protection). When you disable AdGuard completely, is it not detected on that link I posted (dood.re)?
> @AdamWr @zloyden can you reproduce on that dood.re iframe page?

What do you mean disable AdGuard completely?


Also this just makes me sad that it’s working for everyone but me

**Comment by malicerainbow** [comment]
> Such thing is not possible for me. I even forced the site to detect my device by blocking the elements and it will not detect me.
> On my iPhone and iPad it is not reproducible (even when I disable Advanced protection). When you disable AdGuard completely, is it not detected on that link I posted (dood.re)?
> @AdamWr @zloyden can you reproduce on that dood.re iframe page?

I reinstalled the AdGuard app from the App Store, I opened the app where I got terms and condition and checked off the box “I agree to Adguards EULA and privacy policy. I than selected continue of the block ads-block annoyances-and block trackers page of which after continuing each page was taken to the home menu of the app where I got the grey bar message saying “content blockers being updated” and “rules are being converted” than I went to the second icon on the bottom of the app with a shield and a check mark where i was than taken to the protection page of which I selected safari protection and disabled all the filters except AdGuard base filter and AdGuard Mobil ads filter. I than went to gaypornhdfree.com selected a video, tried to play it of which my adblocker was detected, so I then went to the settings gear icon of my iPhone and selected safari- safari extensions and disabled each extension except for general I than went back into the AdGuard app where the grey bar messaged appeared again I waited for it to disappear and than selected the updating button of which it ended with “no updates found” I went back to the settings app and selected safari and deleted the history and website data of safari iOS, I than went back into gaypornhdfree.com selected a video, tried to have it play and my adblocker was once again detected, I went back to the AdGuard app and disabled AdGuard Mobil ads filter, I went back to the home menu and selected updating button of which once again said “no updates found” I than went back into the settings gear icon app and deleted history and website data of safari iOS, than I went back into gaypornhdfree.com selected a video, tried to play it and adblocker was still detected, I than went back to the app selected user rules and added the one Alex told me to
||gaypornhdfree.com/wp-content/uploads/cmdakui
I than waited for the grey bar to disappear first before doing anything else, I than went back to home menu and selected updating button and still no updates were found, I than selected the settings gear icon and deleted history and website data of safari iOS, I went back to gaypornhdfree.com selected a video and tried to play it only to once again have my adblocker detected, I tried multiple times refreshing the page but each time still detected the adblocker, so I than went back to the AdGuard app and re-enabled AdGuard Mobil ads filter, I than went back to home menu and selected the updating button of which for the last time still no updates found, I went back to the settings gear icon and for the last time deleted history and website data, I than went back to gaypornhdfree.com selected a video tried to play it and it didn’t detect my adblocker, so I than tried to play a different one but adblockee was detected, I even tried to than remove the user rule I added

||gaypornhdfree.com/wp-content/uploads/cmdakui

tried to go back to gaypornhdfree.com but still detected my adblocker, tried multiple times and it didn’t work

I don’t even know what to do anymore!!!

**Comment by malicerainbow** [comment]
> Such thing is not possible for me. I even forced the site to detect my device by blocking the elements and it will not detect me.
> On my iPhone and iPad it is not reproducible (even when I disable Advanced protection). When you disable AdGuard completely, is it not detected on that link I posted (dood.re)?
> @AdamWr @zloyden can you reproduce on that dood.re iframe page?

So wait the website gaypornhdfree.com is working for you of not detecting your AdGuard every single time you select a video and play it?

**Comment by malicerainbow** [comment]
> [#136984 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/136984#issuecomment-1344441740) = yes
> 
> [#136984 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/136984#issuecomment-1344546161) = leave open AG app 60 seconds after last gray bar disappear. Later disable sections other than Ad Blocking (aka AdGuard Base Filter and AdGuard Mobile Filter) if page still detect AdGuard.
> 
> Turn on Filter lists of annoying items, anti-social media and those for protection privacy only after the adblock detection message disappears, and do it so that 1 subscription per section arrives (Continuing to wait until the last gray bar and 60 seconds to avoid filtering failure). Turning on one by one may allow us to determine what Filter list is malfunctioning with the site - but there is no guarantee that someone will quickly catch what is causing the error in the Filter list.
> 
> At worst scenario, you need technical assistance from the "developers" of the application. Someone maybe can direct you how to write to them (form / e-mail / forum section).

So wait the website gaypornhdfree.com is working for you of not detecting your AdGuard every single time you select a video and play it?

**Comment by krystian3w** [comment]
It would be useful to check that the site and its iframes do not ban IPs.

In part, this can be ruled out as with disable all AG Protection the message does not disappear.

If it doesn't disappear, you'd have to check if your public IP changes when you activate airplane mode or restart your home router. Finally, use a VPN as long as it is not in a domain blocked for VPN.

**Comment by malicerainbow** [comment]
> It would be useful to check that the site and its iframes do not ban IPs.
> 
> In part, this can be ruled out as with disable all AG Protection the message does should disappear (but back ads/annoyances/tracking).
> 
> If it doesn't disappear, you'd have to check if your public IP changes when you activate airplane mode or restart your home router. Finally, use a VPN as long as it is not in a domain blocked for VPN.
> 
> I'd rather not play around with remote access either.

Could I at least share my screen by zoom or something?

**Comment by AdamWr** [comment]
>@AdamWr `@zloyden` can you reproduce on that dood.re iframe page?

Unfortunately, I cannot reproduce it.

If issue sometimes occurs and sometimes not, then I guess that it might be iOS/Safari related issue where some rules are applied too late and due to this don't work.
For example, similar issue was here - https://github.com/AdguardTeam/AdguardFilters/issues/108226#issuecomment-1098870812 on every other platforms popups were blocked correctly, but on iOS (the same with Safari extension) sometimes were blocked, sometimes not, and it looks like iOS/Safari extensions issue.

**Comment by zloyden** [comment]
> If issue sometimes occurs and sometimes not, then I guess that it might be iOS/Safari related issue where some rules are applied too late and due to this don't work.
For example, similar issue was here - https://github.com/AdguardTeam/AdguardFilters/issues/108226#issuecomment-1098870812 on every other platforms popups were blocked correctly, but on iOS (the same with Safari extension) sometimes were blocked, sometimes not, and it looks like iOS/Safari extensions issue.

I agree with that. Looks like it can be related to https://github.com/AdguardTeam/SafariConverterLib/issues/40 and we can only wait for the fix.

**Comment by malicerainbow** [comment]
but doesn't BlazDT also have and IOS device and was using safari???

**Comment by malicerainbow** [comment]
and he said it was working perfectly on his phone which is an iphone and i believe he
 was using safari

**Comment by malicerainbow** [comment]
> > If issue sometimes occurs and sometimes not, then I guess that it might be iOS/Safari related issue where some rules are applied too late and due to this don't work.
> > For example, similar issue was here - [#108226 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/108226#issuecomment-1098870812) on every other platforms popups were blocked correctly, but on iOS (the same with Safari extension) sometimes were blocked, sometimes not, and it looks like iOS/Safari extensions issue.
> 
> I agree with that. Looks like it can be related to [AdguardTeam/SafariConverterLib#40](https://github.com/AdguardTeam/SafariConverterLib/issues/40) and we can only wait for the fix.

But BlazDit has an iPhone and was using safari I believe and he said it worked perfectly for jim

**Comment by malicerainbow** [comment]
> > @AdamWr `@zloyden` can you reproduce on that dood.re iframe page?
> 
> Unfortunately, I cannot reproduce it.
> 
> If issue sometimes occurs and sometimes not, then I guess that it might be iOS/Safari related issue where some rules are applied too late and due to this don't work. For example, similar issue was here - [#108226 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/108226#issuecomment-1098870812) on every other platforms popups were blocked correctly, but on iOS (the same with Safari extension) sometimes were blocked, sometimes not, and it looks like iOS/Safari extensions issue.

But BlazDT has an iPhone and was using safari I believe which worked perfectly for him!

**Comment by malicerainbow** [comment]
Hello???? Is anyone still working on this for me????

**Comment by malicerainbow** [comment]
> > If issue sometimes occurs and sometimes not, then I guess that it might be iOS/Safari related issue where some rules are applied too late and due to this don't work.
> > For example, similar issue was here - [#108226 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/108226#issuecomment-1098870812) on every other platforms popups were blocked correctly, but on iOS (the same with Safari extension) sometimes were blocked, sometimes not, and it looks like iOS/Safari extensions issue.
> 
> I agree with that. Looks like it can be related to [AdguardTeam/SafariConverterLib#40](https://github.com/AdguardTeam/SafariConverterLib/issues/40) and we can only wait for the fix.

Hello?????

**Comment by malicerainbow** [comment]
> > @AdamWr `@zloyden` can you reproduce on that dood.re iframe page?
> 
> Unfortunately, I cannot reproduce it.
> 
> If issue sometimes occurs and sometimes not, then I guess that it might be iOS/Safari related issue where some rules are applied too late and due to this don't work. For example, similar issue was here - [#108226 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/108226#issuecomment-1098870812) on every other platforms popups were blocked correctly, but on iOS (the same with Safari extension) sometimes were blocked, sometimes not, and it looks like iOS/Safari extensions issue.

Hello??????

**Comment by BlazDT** [comment]
Fixed https://github.com/AdguardTeam/AdguardFilters/issues/137141#issuecomment-1363432480
