### ISSUE TITLE
bitwarden.com

### ISSUE THREAD

**Issue by kmnvq** [AdguardTeam/AdguardFilters#136929]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

uBO-1.45.2

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://bitwarden.com/resources/product-roadmap-newsletter-july-2022/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyPrivacy

### Add your comment and screenshots

E-mail tracking
`https://eventtracking.hubapi.com/events/duration/v1/track/`
<details><summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/206377311-05d216cc-d086-4f7f-9de3-60c13f5d10e3.png)

</details>

---

**Steps to reproduce:**

1-Click on the link below
`https://bitwarden.com/resources/product-roadmap-newsletter-july-2022/`
2-Subscribe to the newsletter.

<details><summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/206376611-b11c9bd5-6b7f-41f9-b896-7f7414bb1c03.png)

</details>

3-Check the confirmation email from Bitwarden.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Blocked
