### ISSUE TITLE
MALWARE REPORT

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#137010]
https://1progs.ru/tenorshare-reiboot-pro-serial-key/

![D98EFACC-3965-4A0C-B945-67C89D674781](https://user-images.githubusercontent.com/120183751/206704734-e869ef04-b464-40bb-9451-60f2456c59b1.jpeg)

https://iowin.net/ru/keygen/?download=true

Virustotal:
https://www.virustotal.com/gui/file/0e9b410433dde4679675ca106b76a2fbef0323f0a56e86a27c9fc82f969d87da/summary

https://www.cocospy.com/blog/ru/how-to-hack-a-phone.html - Suspicious

https://vzlom-vk-online.ru/

https://vzlomsn.tk/hack-vkontakte

https://xn--80adpqfl4azf.me/

https://www.vkvzlom.net/

https://basarunet.org/soft/othersoft/5640-programmy-dlya-vzloma-wi-fi.html

https://1progs.ru/wicrack/ - MALWARE

https://androidvip.net/6065-sms-bomber-antichrist-sms-bomber-antihrist-30-android.html - MALWARE

https://om-tel.com/ - SCAM

https://mobile-tracker.biz/phone-location - SCAM

https://phone-location.org/ - SCAM

http://vipfile.uz/fsfl/WfyBA9yXiQktqxG - MALWARE 

Virustotal:
https://www.virustotal.com/gui/file/d53f7423f9d391b637686ba7e9596858ba4b6fbc46ac3eca02a6e03dcdc20e55/summary

https://vkur1.se/download/ - SCAM + MALWARE

https://whatsms.com/mestopolozhenie-abonenta.html

https://vzlomvk.org/

https://doneto.ru/items_pub_1/kakie_bivayut_osobennosti_api_geolokacii_po_ip_adresu_199 - SCAM

https://online.vzlomvk.social/

https://vzlomvk.social/

**Comment by Alex-302** [comment]
Варез же. На ломанные программы ругается конктретно в этом случае.

**Comment by Alex-302** [comment]
Про вредоносные сайты надо писать на support@adguard.com, а не в раздел фильтров. Никак не связанные сферы.
