### ISSUE TITLE
I don’t even know what to do anymore!!!

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#137092]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.4

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gaypornhdfree.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment> I reinstalled the AdGuard app from the App Store, I opened the app where I got terms and condition and checked off the box “I agree to Adguards EULA and privacy policy. I than selected continue of the block ads-block annoyances-and block trackers page of which after continuing each page was taken to the home menu of the app where I got the grey bar message saying “content blockers being updated” and “rules are being converted” than I went to the second icon on the bottom of the app with a shield and a check mark where i was than taken to the protection page of which I selected safari protection and disabled all the filters except AdGuard base filter and AdGuard Mobil ads filter. I than went to gaypornhdfree.com selected a video, tried to play it of which my adblocker was detected, so I then went to the settings gear icon of my iPhone and selected safari- safari extensions and disabled each extension except for general I than went back into the AdGuard app where the grey bar messaged appeared again I waited for it to disappear and than selected the updating button of which it ended with “no updates found” I went back to the settings app and selected safari and deleted the history and website data of safari iOS, I than went back into gaypornhdfree.com selected a video, tried to have it play and my adblocker was once again detected, I went back to the AdGuard app and disabled AdGuard Mobil ads filter, I went back to the home menu and selected updating button of which once again said “no updates found” I than went back into the settings gear icon app and deleted history and website data of safari iOS, than I went back into gaypornhdfree.com selected a video, tried to play it and adblocker was still detected, I than went back to the app selected user rules and added the one Alex told me to 
||gaypornhdfree.com/wp-content/uploads/cmdakui

I than waited for the grey bar to disappear first before doing anything else, I than went back to home menu and selected updating button and still no updates were found, I than selected the settings gear icon and deleted history and website data of safari iOS, I went back to gaypornhdfree.com selected a video and tried to play it only to once again have my adblocker detected, I tried multiple times refreshing the page but each time still detected the adblocker, so I than went back to the AdGuard app and re-enabled AdGuard Mobil ads filter, I than went back to home menu and selected the updating button of which for the last time still no updates found, I went back to the settings gear icon and for the last time deleted history and website data, I than went back to gaypornhdfree.com selected a video tried to play it and it didn’t detect my adblocker, so I than tried to play a different one but adblockee was detected, I even tried to than remove the user rule I added

||gaypornhdfree.com/wp-content/uploads/cmdakui

tried to go back to gaypornhdfree.com but still detected my adblocker, tried multiple times and it didn’t work 

I don’t even know what to do anymore!!!

3. Screenshots4. 
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Please stop opening new threads and stay in one.

**Comment by malicerainbow** [comment]
> Please stop opening new threads and stay in one.

No one keeps replying in the same thread so this team leaves me no choice
