### ISSUE TITLE
SCAM domains

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#137045]
https://https__github__com.graha.cloud/ - FAKE GitHub

https://spyinst.net/

http://www.insta-tom.eu5.net/

https://vzlomsn.tk/hack-instagram

https://freebitco.in/signup/ - SCAM

https://click-alfabank-ru.ru/ - SCAM

https://frebitcoin.info/ - SCAM advertising

https://freebitco-in.online/ - SCAM

https://www.instapass.zone/

https://instahack.me/

https://vzlomok.pro/

https://www.vzlomon.ru/topic/9-besplatnyy-vzlom-instagram-instagram/

https://antiban.pro/ru/ - SCAM

https://hacking-passwords.com/instagram

https://xn--b1akmej.com/zakazat-instagram/ - SCAM (from some ip address shows fake error page)

http://okvzlom.eu5.net/

https://www.vzlomon.ru/ - SUSPICIOUS

https://tghacker.org/

https://vzlomfb.com/

https://vbtracker.net/

https://wmcentre.net/catalog/steam/accounts-26837

https://limeside.ru/

https://buy-accs.ru/

https://accsmarket.com/ru

https://akitut.net/

https://hackear-cuenta.com/ru/hackear-instagram/

Also I would recommend to BAN next domains (and all their subdomains):
https://ngrok.com/
https://serveo.net/
https://localhost.run/
https://localxpose.io/

They are not malicious but the are ALWAYS abused by some lamers. For example there three phishing tools, that are using this domains to SCAM people.

[One!](https://github.com/htr-tech/nexphisher) -/- [Two!](https://github.com/yezz123/Phisher) -/- [Tree!](https://github.com/Ignitetch/AdvPhishing) 

If you still think that's not enough to block these domains, just use a github search with the [following query: "phishing"](https://github.com/search?q=phishing) . Every second (or even EVERY) phishing tool will use these resources for their atrocities.

As a conclusion, these domains do more harm than good, so I think that you, as a company specializing in privacy and security, should protect your users from such a primitive phishing method as well.

**Comment by Oniqqqq** [comment]
I've checked these domains. Some of them don't look dangerous, but they don't look trustworthy either. If there are complaints from users about incorrect blocking, we will remove domain from the list. Thanks
