### ISSUE TITLE
www.chapmanganato.com

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#137070]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.4

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://chapmanganato.com/manga-fr982452/chapter-6

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

On some manga pages there is a white leftover in the middle

![5F79217A-233D-4143-825C-5C63E627B2AD](https://user-images.githubusercontent.com/46019727/206835985-b063dd3c-bab6-4cd7-8b56-add2f42db158.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Bhooty** [comment]
Just tried now
Still there

![D8BBD88E-9A4A-4ED0-96A5-37AA31C8EA91](https://user-images.githubusercontent.com/46019727/207381346-ef65793e-6933-43e4-81fe-dec4795338e9.png)

**Comment by Alex-302** [comment]
Weird. Please test with Base filter only.

**Comment by Bhooty** [comment]
> Weird. Please test with Base filter only.

Still same sir

if i select the element blocker in safari adguard extension then i get this 

chapmanganato.com##div.body-site:first-child > div.container-chapter-reader:nth-child(3) > div:nth-child(18) > iframe

**Comment by Alex-302** [comment]
Please test(wait a minute after adding):
`chapmanganato.com##div.body-site > div.container-chapter-reader > div[style^="text-align: center; max-width:"]`

**Comment by Bhooty** [comment]
> Please test(wait a minute after adding):
> `chapmanganato.com##.body-site > div.container-chapter-reader > div[style^="text-align: center; max-width:"]`

Yes sir
This seems to have fixed it
Tried on other pages
This fixed the top whitespace for some pages too
Thanks

![10400932-9DA1-4479-A34E-02AF2FF5A3EC](https://user-images.githubusercontent.com/46019727/208136512-9d148c46-0659-4eae-a89a-cb9dfaf23569.png)

**Comment by Bhooty** [comment]
> Please test(wait a minute after adding):
> `chapmanganato.com##.body-site > div.container-chapter-reader > div[style^="text-align: center; max-width:"]`

Sir can you update the filters to add this?

**Comment by Alex-302** [comment]
Ok
