### ISSUE TITLE
I’m going to continue making issue tickets until one of you finally responds back to the ones I had already made or this one 

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#137144]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.4

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gaypornhdfree.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment> Why am I paying for AdGuard with this treatment? I am ready to cancel my subscription 

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by malicerainbow** [comment]
Again you didn’t respond to the question I just asked but you can close my issue

**Comment by BlazDT** [comment]
I left a reply in your other issue

**Comment by malicerainbow** [comment]
> I left a reply in your other issue

No you didn’t I checked and sent a screen shot there is no other replies except the one I made to Kyrstain

**Comment by malicerainbow** [comment]
> I left a reply in your other issue

![0847CD60-7C01-478D-849B-78E6CA6A42E5](https://user-images.githubusercontent.com/118444664/206896471-279a9563-d357-4a1d-8b87-85aa5c4387cd.png)

I am the last reply as of now you sent no reply
