### ISSUE TITLE
com.reddit.frontpage

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#137246]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0 nightly

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.reddit.frontpage

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. Check on a rooted device

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/8361299/207043713-8ec10ccb-4fee-427b-a557-05b1fd6e7d6c.png)
>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I've been investigating it for some time and it looks like it can't be blocked. Otherwise, it breaks the app.
