### ISSUE TITLE
hellporno.com

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardFilters#137396]
@zloyden 
Ничего не изменилось!😐

_Originally posted by @Spok1 in https://github.com/AdguardTeam/AdguardFilters/issues/136527#issuecomment-1346444649_

**Comment by Sergey-Lyapin** [comment]
Реклама не повторилась.
@Alex-302 @jellizaveta проверьте, пожалуйста
https://github.com/AdguardTeam/AdguardFilters/issues/136527

**Comment by jellizaveta** [comment]
Остатки от рекламы не повторились.

**Comment by Spok1** [comment]
@zloyden ,проверь, пожалуйста!

**Comment by zloyden** [comment]
Тоже не повторяется на смартфоне с последним обновлением фильтров.

**Comment by Spok1** [comment]
@maxikuzmin , разберитесь, пожалуйста!
