### ISSUE TITLE
pirotskevesti.rs

### ISSUE THREAD

**Issue by ckojam** [AdguardTeam/AdguardFilters#137493]
Website https://www.pirotskevesti.rs has a popup that adblock has been detected and it cannot be removed until adblock is disabled. 
![Adblock detected](https://user-images.githubusercontent.com/6016734/207575924-c648c00c-e68d-4fa2-89e0-7d6ba524e93c.jpg)

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
By default filters are updated automatically every 24/48 hours, so it will be necessary to update filters manually.
