### ISSUE TITLE
[iOS] BankofAmerica.com - blank space

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1374]
![image](https://cloud.githubusercontent.com/assets/15856304/12536249/7d7a137a-c2a8-11e5-9b73-de73c4fc76e2.png)

GVJ-426-54706

**Comment by Alex-302** [comment]
added to Mobile filter
```
@@||bankofamerica.com/content/images/ContextualSiteGraphics/Marketing/Banners/
```

**Comment by evgeniy-ADG** [comment]
@Alex-302 could you please check it once again? Our customer still experiencing the issue even after updating filters.

**Comment by Bohdan-SUP** [comment]
@Alex-302 Please check again. It's still happening.
