### ISSUE TITLE
Google Maps  redirection for use Taxi (jump into Cabify App)is redirecting using the following endpoint blocked by ADNSGuard

### ISSUE THREAD

**Issue by KashaMalaga** [AdguardTeam/AdguardFilters#137549]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

00

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other(specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://app.adjust.com/t5g2nf?client_id=GOOGLE_MAPS&deep_link=cabify%3A%2F%2Fbook-a-ride%3Fclient_id%3DGOOGLE_MAPS%26deep_link_product_id%3D773e238306f33909b9ee8e0c54503fa4%26dropoff_formatted_address%3DSants%20Estaci%C3%B3%2C%20Espa%C3%B1a%26dropoff_latitude%3D41.3809200%26dropoff_longitude%3D2.1417040%26dropoff_title%3DSants%20Estaci%C3%B3%26eta_seconds%3D120%26fare_currency%3DEUR%26fare_high%3D9.00%26fare_low%3D7.00%26pickup%3Dmy_location&deep_link_product_id=773e238306f33909b9ee8e0c54503fa4&dropoff_formatted_address=Sants%20Estaci%C3%B3%2C%20Espa%C3%B1a&dropoff_latitude=41.3809200&dropoff_longitude=2.1417040&dropoff_title=Sants%20Estaci%C3%B3&eta_seconds=120&fare_currency=EUR&fare_high=9.00&fare_low=7.00&pickup=my_location

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

Not required

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
"[Peter Lowe’s Ad and tracking server list](chrome-extension://cgbcahbpdhpcegmbfconppldiemgcoii/asset-viewer.html?url=plowe-0)" block whole:

`||adjust.com^`

**Comment by Alex-302** [comment]
This domain is also used as a popular tracker. We cannot excude it.
But you can switch to our private DNS https://adguard-dns.io/ and block/unblock any domain.
