### ISSUE TITLE
Vodafone Au visual voicemail not working with native protection 

### ISSUE THREAD

**Issue by Steve2Go** [AdguardTeam/AdguardFilters#137758]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.4(965)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other(specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

Vm.Vodafone.net.au

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

1. Voicemail is broken for Vodafone Australia users using native protection 

Creating a profile manually, excluding Vodafone.net.au in the adguard website and using that instead resolves the issue. Could this same exclusion be applied to native protection?

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@Steve2Go Hi. It is caused by DNS protection, right?
If so, please test with AdGuard non-filtered DNS in _**DNS Protection**_ settings.

**Comment by Steve2Go** [comment]
I believe the issue is that it’s in their dns serves only, and by switching dns it’s no longer resolved, hence the bypass when using a profile works.Switching to any other dns natively causes it to fail.Steve Grigg07 3102 1201tidycal.com/SteveSent from my mobile On 19 Dec 2022, at 11:38 pm, Alex ***@***.***> wrote:﻿
@Steve2Go Hi. It is caused by DNS protection, right?
If so, please test with AdGuard non-filtered DNS in DNS Protection settings.

**Comment by Alex-302** [comment]
> hence the bypass when using a profile works

With AdGaurd DNS?

**Comment by Alex-302** [comment]
@Steve2Go It is strange. Please write to support@adguard.com
You can mention this conversation.
