### ISSUE TITLE
yandex direct on lady.mail.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1378]
https://lady.mail.ru/forum/topic/vyzyvaju_kontraktnyh_upravljajushhih/
![image](https://cloud.githubusercontent.com/assets/15856304/12546445/834da500-c352-11e5-8464-a40ca9e849c4.png)
![image](https://cloud.githubusercontent.com/assets/15856304/12546453/8ce64e5a-c352-11e5-9f06-f52d149a48dc.png)

GXC-161-13017

**Comment by Alex-302** [comment]
сверху не реклама.
Пусть в журнале фильтрации проверит, блокируется ли что либо. Может в списке фильтруемых приложений нет браузера. Ещё пусть в другом проверит.

**Comment by evgeniy-ADG** [comment]
https://lady.mail.ru/forum/topic/vyzyvaju_kontraktnyh_upravljajushhih/
![image](https://cloud.githubusercontent.com/assets/15856304/17662616/6b6c47ba-62ef-11e6-929e-765687cd5fe1.png)

**Comment by Alex-302** [comment]
Не повторяется. Нужно удалённо смотреть.
Напиши в каких браузерах директ, и с прогой или расширением.

**Comment by Alex-302** [comment]
Убрал остатки:
```
lady.mail.ru##.p-mimic
```

**Comment by Darina655** [comment]
Yandex.direct ads on https://lady.mail.ru/forum/ in all the browsers except MS Edge |
Could reproduce.
Screenshot in Chrome:
http://prntscr.com/eneff0
Screenshot in Edge:

**Comment by shurmosha** [comment]
сегодня уже 20-51 а никакого результата от вашей команды по исправлению нет и тишина...вот свежий снимок в опере
![default](https://cloud.githubusercontent.com/assets/17802561/24262371/d9c5d5b4-100a-11e7-99c1-60e34b33815b.PNG)

**Comment by Alex-302** [comment]
да смотрю прямо сейчас

**Comment by Alex-302** [comment]
ща всё будет, через пол часа

**Comment by shurmosha** [comment]
хорошо бы...буим ждать .как узнаем? в обновах фильтров?

**Comment by Alex-302** [comment]
через 15-20 минут можно будет обновиться

**Comment by shurmosha** [comment]
хорошо..к 22-00 обновлюсь и отпишусь

**Comment by shurmosha** [comment]
докладываю
время 22-12
ничего не произошло вот скрин
![default](https://cloud.githubusercontent.com/assets/17802561/24265819/d619e60c-1015-11e7-8701-2386ab1c164b.PNG)

**Comment by Alex-302** [comment]
не доехало видать. Сейчас обновился - реклама пропала.

**Comment by shurmosha** [comment]
пока тихо
![2](https://cloud.githubusercontent.com/assets/17802561/24266308/68b93228-1017-11e7-8052-037214514280.PNG)

**Comment by shurmosha** [comment]
22-59  ничего не изменилось-всё на месте 

уже переустановил агуард-реклама есть

**Comment by shurmosha** [comment]
то ,что писал выше относилось к смартбуку престижио
на ноуте пропала реклама,и на моноблоке-тоже, а на смарте есть.система переустановлена с нуля
версия агуарда на смарте последняя пишет 6,1,314,1628

**Comment by shurmosha** [comment]
спешу обрадовать
переустановил на смарте оперу и все заработало-или совпало

**Comment by Michael23456** [comment]
![image](https://cloud.githubusercontent.com/assets/25711093/24829566/e61c8398-1c7c-11e7-8ac7-a1ad942db423.png)
жалоба от пользователя 1030934
english, spyware, social, annoyances, russian, mobile, Experimental

**Comment by Alex-302** [comment]
Не повторяется. Что в пользовательском фильтре?

**Comment by Michael23456** [comment]
сейчас спросим

**Comment by shurmosha** [comment]
все правила с ледей убрал

**Comment by shurmosha** [comment]
эта реклама не постоянно висит ,а пробивается периодически
перезагрузка -дает на время отдых от неё

**Comment by shurmosha** [comment]
пока только это  # #
[Doc1.docx](https://github.com/AdguardTeam/AdguardFilters/files/907578/Doc1.docx)

**Comment by shurmosha** [comment]
в режиме инкогнито пока только так
[Doc2.docx](https://github.com/AdguardTeam/AdguardFilters/files/907636/Doc2.docx)

**Comment by Michael23456** [comment]
customerID:1030934
User filter почистили, через врема снова появилась даже в инкогнито

**Comment by Darina655** [comment]
http://prntscr.com/euxu5w У пользователя все так же Яндекс.Директ присутствует, у меня воспроизводится данная проблема с базовыми фильтрами и при отсутствии правил в ПФ.

**Comment by Alex-302** [comment]
@Darina655 
> у меня воспроизводится данная проблема

чисто же. Ссылки справа ведут на мейлрушные порталы.
