### ISSUE TITLE
Mail trackers

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#137813]
Hello!
Here is a fragment of HTML code of the letter. Links to trackers from this fragment are not blocked :(

  ```
<style style="box-sizing: border-box;"> #_eoa_div, #_eoa_img { display:none; } @media print{ #_eoa_div { background-image: url('https://wjCjTsezJi.eoapxl.com/wjCjTsezJi/yourmailhere@mail.com/P'); } } div.OutlookMessageHeader, table.moz-email-headers-table, blockquote #_eoa_div, #mailContainerBody #_eoa_div { background-image:url('https://wjCjTsezJi.eoapxl.com/wjCjTsezJi/yourmailhere@mail.com/F') } </style>
<div id="_eoa_div" style="box-sizing: border-box; display: none;"></div>
```

I suggest to add this rule:
`||eoapxl.com^`

Because the part before `eoapxl.com` always different

**Comment by BlazDT** [comment]
Are there also links to visit the site which contains that element (containing the eoapxl.com domain as redirecter)? If yes, blocking the redirect domain breaks stuff for DNS and iOS.

**Comment by Hvtcygyfyguctx** [comment]
Hello!
No. At least I did not find it :)
