### ISSUE TITLE
fairfan.co

### ISSUE THREAD

**Issue by conanwr** [AdguardTeam/AdguardFilters#137832]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.52

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://fairfan.co/collection/harry-potter

### What filters do you have enabled?

AdGuard French filter

### Add your comment and screenshots

1. French filter removes the hbo logo image

2. Screenshots
<details><summary>Screenshot 1:</summary>
![image](https://user-images.githubusercontent.com/103221722/208621240-0c83121f-d5f5-4c0c-97fe-fad5f2f83e81.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
