### ISSUE TITLE
EasyList Polish

### ISSUE THREAD

**Issue by KonoromiHimaries** [AdguardTeam/AdguardFilters#13789]
![2018-02-11-ustawienia adguard](https://user-images.githubusercontent.com/5884000/36069946-fd336d90-0ef1-11e8-97d9-edaf5a6b2697.png)

can you move the list `Adblock Polska` to `other lists` and insert a list `EasyList Polish` in the place of `Adblock Polska` list

```
https://easylist-downloads.adblockplus.org/easylistpolish.txt
https://github.com/easylistpolish/easylistpolish
```

**Comment by Alex-302** [comment]
Sorry, I don't understand the first part. You can write in Polish)

**Comment by KonoromiHimaries** [comment]
@Alex-302

**Comment by Alex-302** [comment]
done. Please wait for changes.

**Comment by Alex-302** [comment]
Not done. It seems this filter is not related with EasyList team.
@AdamWr could you find more details about it?

**Comment by KonoromiHimaries** [comment]
![2018-03-26-known adblock plus subscriptions](https://user-images.githubusercontent.com/5884000/37897329-42e4f05a-30e6-11e8-931e-32770c0b53b3.png)
`https://adblockplus.org/subscriptions`

**Comment by Alex-302** [comment]
ok. Added as new filter. We can't just replace existing filter.
