### ISSUE TITLE
www.parkiet.com

### ISSUE THREAD

**Issue by zPitachu** [AdguardTeam/AdguardFilters#138091]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.52

### What type of problem have you encountered?

Social media buttons — share, like, tweet, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.parkiet.com/gospodarka-krajowa/art23472301-bielecki-pokieruje-rada-gospodarcza-premiera

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyList Italy, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Polish Anti Adblock Filters, Dandelion Sprout's Nordic Filters

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Block third-party Authorization header, Hide Referrer from third-parties (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests

### Add your comment and screenshots

![image](https://user-images.githubusercontent.com/114113339/209169082-731fd64b-7250-481a-a8e7-042ef8ff1208.png)

### Privacy

- [x] I agree to follow this condition

**Comment by Alex-302** [comment]
Too small.
