### ISSUE TITLE
logitech.com

### ISSUE THREAD

**Issue by kmnvq** [AdguardTeam/AdguardFilters#138125]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBO-1.45.2

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.logitech.com/en-gb/products/mice.html

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyList, EasyPrivacy

### Add your comment and screenshots

It only shows up in Chrome.
`qoe-jh.yottaa.net/log-jh`

<details><summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/209245237-5b72c3f6-ea9b-43b7-8523-e7e1a99a239b.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by iam-py-test** [comment]
Used to send visitor/site/session IDs, page category (seems different for search & product pages), and page URL via `navigator.sendBeacon` from Rapid+JS (`https://cdn.yottaa.com/rapid.security.min.7.1.1.js`), so looks like tracking.
EP blocks this via their `$third-party,ping` rule and it doesn't seem to break anything.
Both `hxxpx://www.uline[.]ca/` and `hxxpx://es.uline[.]mx/` use this script too.
