### ISSUE TITLE
tiktok

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#138132]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

||log-boot.tiktokv.com^

shown on first boot before creating a tiktok account in the app

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
also log16-applog-useast5.us.tiktokv.com still isnt being blocked. is it in excluded list or something?

**Comment by zloyden** [comment]
As I can see, it is related to this https://github.com/AdguardTeam/AdguardFilters/issues/99486.

**Comment by jordanswrld94** [comment]
@zloyden ||log*-*.tiktokv.com^ can we remove this filter all together.  Upon first tiktok boot it breaks everything. It is still blocked in content filter

**Comment by zloyden** [comment]
@jordanswrld94 I have no issue with the rule - videos play fine on my end.
Could you describe it in detail?

**Comment by zloyden** [comment]
> Upon first tiktok boot it breaks everything

Have you meant this https://github.com/AdguardTeam/AdguardFilters/issues/99486 or something else?

**Comment by jordanswrld94** [comment]
Yes

> > Upon first tiktok boot it breaks everything
> 
> Have you meant this #99486 or something else?

Yes that issue. Does the same thing because it still exists in content filter even tho it was removed from dns filter
