### ISSUE TITLE
amazon tracker

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#138112]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

amazon.com

### What filters do you have enabled?

AdGuard Tracking Protection filter

### Add your comment and screenshots

||unagi.amazon.com
||unagi-na.amazon.com

could we block these two? easyprivacy has "/unagi.amazon." in there filters

these show up in amazon app and amazon website

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
Hello @jordanswrld94
We have `||unagi*.amazon.*/1/events^` and it works well but I will change it to `||unagi*.amazon.` to get it into the DNS filter. I hope nothing will break.

**Comment by Alex-302** [comment]
Reverted https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1367
