### ISSUE TITLE
Some videos are being mistaken as ads I assume because of the ads being embedded in some of the embedded videos 

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#138228]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.5

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gaypornhdfree.com/nikita-repa-spanking-2/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>So gaypornhdfree.com is no longer detecting my adgaurd premium at all it’s working perfectly however some videos have been blocked I assume it’s because some of the embedded videos from dood.re which are being on gaypornhdfree inspect element have embedded ads so adguard I assume is not being able to distinguish the two and is mistaking the embedded video with the embedded ads as an ad it’s self. Is there anyway this can be resolved of separating the line of code of the ads and the line of code that make up the video so only the line of code that makes up the ads is blocked so that I can still view the video?2. 

Here is video url links to certain videos on gaypornhdfree.com that I have no access to as long as adguard keeps blocking them as ads 

https://gaypornhdfree.com/giuspel-favio-vador-behind-the-scenes-in-the-park/

https://gaypornhdfree.com/ethan-chase-ridick/

https://gaypornhdfree.com/nikita-repa-spanking-2/

Part of me is worried if any of you attempt this could it jeopardize what has already been in state of gaypornhdfree no longer detecting my adblocker???

3. Screenshots
<details><summary>Screenshot 1:</summary>

![C2E79D47-ED34-478B-BE50-999C915A7E7C](https://user-images.githubusercontent.com/118444664/209419496-5f681322-8843-4843-a123-bb40dda36eae.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Disabled problematic rule, update available in about 3-4 hours.

**Comment by malicerainbow** [comment]
> Disabled problematic rule, update available in about 3-4 hours.

So all I have to do is press the updating button on the main page of the AdGuard app?

**Comment by BlazDT** [comment]
Yes. It was a quite old rule though.

**Comment by malicerainbow** [comment]
> Yes. It was a quite old rule though.

What do you mean it was an old rule?

**Comment by BlazDT** [comment]
It was added years ago therefore old rule.

When the app was bought on the appstore, then not possible to transfer (Apple restriction).

If bought on our website you can use license key via login.

**Comment by malicerainbow** [comment]
> It was added years ago therefore old rule.
> 
> When the app was bought on the appstore, then not possible to transfer (Apple restriction).
> 
> If bought on our website you can use license key via login.

I actually paid for app through iOS App Store is there a way to still get the license?

**Comment by BlazDT** [comment]
Sadly not :(

Currently there is a 40% discount on licenses (up to 3 devices) on our website. In iOS app (not the Pro one) you can use your account login to get same elements
 
If you do, do not forget to cancel appstore's subscription.
You may contact our support team via inbuilt support menu. Maybe they can help a bit though.

**Comment by malicerainbow** [comment]
> Sadly not :(
> 
> Currently there is a 40% discount on licenses (up to 3 devices) on our website. In iOS app (not the Pro one) you can use your account login to get same elements
> 
> If you do, do not forget to cancel appstore's subscription. You may contact our support team via inbuilt support menu. Maybe they can help a bit though.
> 
> You do not need to remove a rule. The rule is getting removed automatically when you update filters.

Also my friend thinks you guys help premium and free users on issue tickets at same level I think he’s wrong paid users are seen first before free or is he right?

**Comment by BlazDT** [comment]
Filter issues not since we do not see any licenses etc.

When reporting technical problems via in-app support, our support team should see if a paying user is reporting (though I do not know if speed matters, you have to ask via support ticket).

**Comment by malicerainbow** [comment]
> Filter issues not since we do not see any licenses etc.
> 
> When reporting technical problems via in-app support, our support team should see if a paying user is reporting (though I do not know if speed matters, you have to ask via support ticket).

So I should end my iOS subscription and by the license on the website?

**Comment by BlazDT** [comment]
If you want to use a license on more than one device, then yes.
I advise to buy lifetime license if you can afford one. That way you only pay once.
If you have the Pro version on iOS installed, then you would need install normal AdGuard for iOS and then use your new login which you get from purchase. If everything is working as it should, uninstall the Pro version.

**Comment by malicerainbow** [comment]
> If you want to use a license on more than one device, then yes.
> I advise to buy lifetime license if you can afford one. That way you only pay once.
> If you have the Pro version on iOS installed, then you would need install normal AdGuard for iOS and then use your new login which you get from purchase. If everything is working as it should, uninstall the Pro version.



you fixed the issue thank you!!!!!

**Comment by malicerainbow** [comment]
How many devices are covered with the premium BlazDT????

**Comment by BlazDT** [comment]
Can check later if a javascript rule can be added to Auto-click some away (can take a while due to national  holidays though). This time the videos come from hqq instead of dood.

When I previously checked I only needed to click two times (and first one tells you if you misclick).

**Comment by BlazDT** [comment]
Sadly that hqq.to iframe which is embedded is very unreliable when I open the site (even without adblocker). So cannot do anything.

@AdamWr please check if hqq.to iframe works better for you and if you can disable those multiple clicks.

**Comment by malicerainbow** [comment]
> Sadly that hqq.to iframe which is embedded is very unreliable when I open the site (even without adblocker). So cannot do anything.
> 
> @AdamWr please check if hqq.to iframe works better for you and if you can disable those multiple clicks.

So those certain videos do make you do multiple clicks also?

**Comment by BlazDT** [comment]
Only two times.

**Comment by malicerainbow** [comment]
> Only two times.

Only two clicks or only two times video made you do multiple clicks?

**Comment by BlazDT** [comment]
Meant two clicks.

**Comment by malicerainbow** [comment]
> Meant two clicks.

Wait what did you do to only have to do two clicks because I have to do multiple

**Comment by BlazDT** [comment]
You have to click on the moving play button (not just anywhere), else you have to click additional times before seeing real play button.

**Comment by malicerainbow** [comment]
> You have to click on the moving play button (not just anywhere), else you have to click additional times before seeing real play button.

Is Adam going to try and figure it out?

**Comment by AdamWr** [comment]
I have to click two times and it looks like some kind of captcha/anti-bot protection, I don't think that it's something what should be fixed.

**Comment by malicerainbow** [comment]
> I have to click two times and it looks like some kind of captcha/anti-bot protection, I don't think that it's something what should be fixed.

Why should it not be fixed?

**Comment by AdamWr** [comment]
Because it looks like some kind of captcha/anti-bot protection and I don't think that such things should be fixed.

**Comment by malicerainbow** [comment]
> Because it looks like some kind of captcha/anti-bot protection and I don't think that such things should be fixed.

So as to prevent just so bots from accessing?

**Comment by AdamWr** [comment]
I guess so.

**Comment by malicerainbow** [comment]
> Meant two clicks.

Okay so sometimes straight porn wounds up on our site and I don’t like that it literally is called gaypornhdfree. for a reason I used to use adguard and block specific elements on a webpage to get rid of it but iv notice adguard removes other elements also when you do this 


Is there a way for adguard to only remove that element and nothing else!!!!!!

**Comment by BlazDT** [comment]
Better report to site author.
We do not censor any page.

**Comment by malicerainbow** [comment]
> Better report to site author.
> We do not censor any page.

No I don’t mean actually remove just block for example I used block event of adguard but it did the block of every Google image search that’s located of the exact one the actual selection block was

**Comment by malicerainbow** [comment]
> Better report to site author.
> We do not censor any page.

![C6417F99-15CF-4BDF-B538-4FE1238F989C](https://user-images.githubusercontent.com/118444664/209779863-b2407919-319f-4cf7-9580-574560121ba0.jpeg)
![959D1940-8870-4300-BD49-0462997171FC](https://user-images.githubusercontent.com/118444664/209779872-26faaf48-8614-444a-b4ae-0305e09c9e50.jpeg)
![7C075E05-EC76-4A77-9386-CCF48AF1B756](https://user-images.githubusercontent.com/118444664/209779875-d8fa8ba3-831f-4f5f-acd1-07d372f8c82d.jpeg)
![5051310C-8EF6-4740-B32D-6876B9DC27D1](https://user-images.githubusercontent.com/118444664/209779879-0d29d694-6e2f-4b57-953e-208d959fa7e0.jpeg)
