### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#138226]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.46

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.youtube.com/watch?v=0SiSwwOMBcs

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

||ytimg.com/generate_204
||youtube.com/youtubei/v1/log_event?

generate 204 is also in easyprivacy it is a tracker

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
ah ok. ty. the logevent one can be blocked tho

**Comment by jellizaveta** [comment]
`youtube.com/youtubei/v1/log_event?` blocked by AdGuard Tracking Protection filter
