### ISSUE TITLE
https://rembitteh.ru/ - hogging CPU

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#13835]
https://rembitteh.ru/info/stiralnie-mashini/error/lg/ue/

![image](https://user-images.githubusercontent.com/15856304/37873499-c70e09cc-3026-11e8-8db5-2880014b3168.png)

Reproduced on Chrome 65.0.3325.181 on macOS 10.13.3, AdGuard 1.5.3 with English, Russian, Spyware, Social media, Annoyances, and Safari filters.

**Comment by Alex-302** [comment]
Not reproduced. Please upload HAR file from browser.
