### ISSUE TITLE
compizomania.blogspot.com, lostfilm.tv: stealth mode breaks authorisation

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1383]
При включенной функции Антитрекинг есть проблема со входом и авторизацией на некоторых сайтах, например http://compizomania.blogspot.com/, http://www.lostfilm.tv/ и т.д., помогает только или полное отключение данной функции или снятие галочки с "Блокировать сторонние куки-файлы". Если бы можно было разрешать куки с определенных сайтов (типа исключения) было бы замечательно. Можно как-то реализовать эту функцию?

Скринкаст здесь: IGP-490-28593

**Comment by Alex-302** [comment]
lostfilm не починить, т.к. весь домен нужно будет исключить.

**Comment by evgeniy-ADG** [comment]
Может, его в feature request переквалифицировать, как пользователь предлагает? Есть смысл?

**Comment by Alex-302** [comment]
в этом разделе список завели для подобных случаев

**Comment by Alex-302** [comment]
compizomania.blogspot.com
авторизовался нормально
