### ISSUE TITLE
www.donanimhaber.com lefover ad

### ISSUE THREAD

**Issue by schipht** [AdguardTeam/AdguardFilters#138476]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Adguard Turkish List

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.donanimhaber.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyList, EasyList Cookie List

### What Stealth Mode options do you have enabled?

Self-destruction of third-party cookies, Protect from DPI

### Add your comment and screenshots

1. I'm using uBlock Origin, when I open website, left and right side still clickable, when you click uBlock warns you (screenshot added).
For this lefover Dark Reader extension doesn't work correctly. I solved this problem below ad rule.

_www.donanimhaber.com##.giydirme-container_

2. Screenshots
<details><summary>Screenshot 1:</summary>
![image](https://user-images.githubusercontent.com/62606788/209618839-cc6c36cb-cbf5-4c92-92eb-c67e06b5e9b1.png)
</details>

<details><summary>Screenshot N:</summary>
![image](https://user-images.githubusercontent.com/62606788/209619115-c4103d84-909a-4732-9de1-664049be1e11.png)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
It was fixed earlier. Update the filters in 1-2 hours.
