### ISSUE TITLE
I didn’t know you don’t help on none ad related issues on AdGuard so I’ll just hire a programmer to help with the blocking element issue 

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#138564]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.5

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

google.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment> I want only the element I select blocked on my screen not any other similar elements also blocked2. 

For example I blocked the element of a dog Google image search but it blocked every image search of image located exactly where the removed dog image was

I wanted only and I do mean only the dog image element blocked only 
3. Screenshots
<details><summary>Screenshot 1:</summary>

![C65EEE77-7B87-4795-95A1-7D427DDC3396](https://user-images.githubusercontent.com/118444664/209792101-3e774f49-4dfb-428f-ad03-53a27cf27515.jpeg)
![67AB6180-30AA-41A5-B8E3-EB95F178640C](https://user-images.githubusercontent.com/118444664/209792108-72d6a4e6-7e48-4c2e-bba9-553c2b15be7f.jpeg)
![E7CD4988-8D5B-4D0F-8155-EFDFB127A746](https://user-images.githubusercontent.com/118444664/209792112-f4f850bf-69cb-44a4-b2f3-181088b9319a.jpeg)
![263E1EC5-F3C8-45C4-81A4-8637EB397A4B](https://user-images.githubusercontent.com/118444664/209792115-e9f26764-f6c0-48b9-9399-ed15657bd9c8.jpeg)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
URL not matching screenshot.
Please post correct search URL and the rule which the assistant proposed.

**Comment by malicerainbow** [comment]
> URL not matching screenshot.
> Please post correct search URL and the rule which the assistant proposed.

Alex just informed me you don’t help on none ad related elements so it’s fine

**Comment by Alex-302** [comment]
I provided you all info - our syntax and popular CSS selectors. You did not even read the article about selectors.

**Comment by malicerainbow** [comment]
> I provided you all info - our syntax and popular CSS selectors. You did not even read the article about selectors.

Actually I did look over it and it’s just really complicated 


But anyway you don’t help on none ad related issues of AdGuard correct?


If so that’s fine I’ll just have to hire a programmer

**Comment by malicerainbow** [comment]
> I provided you all info - our syntax and popular CSS selectors. You did not even read the article about selectors.

You don’t help on none ad related issues of AdGuard correct?

**Comment by malicerainbow** [comment]
> I provided you all info - our syntax and popular CSS selectors. You did not even read the article about selectors.

You only help on ad related issues right

**Comment by malicerainbow** [comment]
> I provided you all info - our syntax and popular CSS selectors. You did not even read the article about selectors.

Alex I did look at it and I don’t understand it okay I’m probably not smart enough to comprehend

**Comment by malicerainbow** [comment]
> I provided you all info - our syntax and popular CSS selectors. You did not even read the article about selectors.

I read it and I don’t understand it at all

**Comment by malicerainbow** [comment]
> I provided you all info - our syntax and popular CSS selectors. You did not even read the article about selectors.

Also it is really hard to get you to respond back

**Comment by malicerainbow** [comment]
> URL not matching screenshot.
> Please post correct search URL and the rule which the assistant proposed.

I wasn’t given a proposed rule

**Comment by malicerainbow** [comment]
> I provided you all info - our syntax and popular CSS selectors. You did not even read the article about selectors.

Alex did you read any of my replies?
