### ISSUE TITLE
SCAM

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#138516]
**Здравствуйте!
Все нижеприведенные ссылки являются мошенническими копиями [сайта украинского банка Monobank!](https://monobank.ua/)**

**Список вредоносных сайтов:**
```
https://monobankcard.com/
https://50-hrn-za-reyestratsiyu-v-monobank.blogspot.com/
https://mobank.com.ua/ru/monobank-ukraine/
https://monobankinfo.com.ua/
```

**Comment by Alex-302** [comment]
Проверим.
