### ISSUE TITLE
Grey banner message ad on gayxtapes.com

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#138584]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.5

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gay.xtapes.to/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>So I don’t know if this is an ad but I think it is on gayxtapes.com 2. 

all I know is it’s some sort of message banner and this is not a cosmetic block like my element thing

it’s annoying and it’s not just something aesthetically I don’t want it’s distracting and is in the way 
3. Screenshots
<details><summary>Screenshot 1:</summary>

https://user-images.githubusercontent.com/118444664/209810325-1a74bc49-fe35-450c-b24d-28ead8d16b8d.png

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Will check this evening (6-8 hours).

**Comment by BlazDT** [comment]
Please check this rule:
`||st.chatango.com^$third-party`

**Comment by malicerainbow** [comment]
> Please check this rule:
> `||st.chatango.com^$third-party`

You want me to add that rule correct?

**Comment by BlazDT** [comment]
Yes.

**Comment by malicerainbow** [comment]
> Yes.

For some reason I’m not able to get on the website can you see if your able I’m not sure if it’s a site error of if it’s detecting AdGuard

gayxtapes.com

**Comment by malicerainbow** [comment]
> Yes.

[Link to website ](https://gay.xtapes.to/)

**Comment by BlazDT** [comment]
That icon cannot remove. It is captcha aka bot-protection.

**Comment by malicerainbow** [comment]
> That icon cannot remove. It is captcha aka bot-protection.
> 
> EDIT: Added rule to Annoyances filter. You can enable it and then please check if adblock is detected again on your previous issue website. If still everything working, you can also enable Tracking Protection filter.

I removed it my self with block element option

**Comment by malicerainbow** [comment]
> That icon cannot remove. It is captcha aka bot-protection.
> 
> EDIT: Added rule to Annoyances filter. You can enable it and then please check if adblock is detected again on your previous issue website. If still everything working, you can also enable Tracking Protection filter.

So wait if I enable annoyances filter that captcha icon will no longer be visible?

**Comment by malicerainbow** [comment]
> That icon cannot remove. It is captcha aka bot-protection.
> 
> EDIT: Added rule to Annoyances filter. You can enable it and then please check if adblock is detected again on your previous issue website. If still everything working, you can also enable Tracking Protection filter.

Do paying customers have a limit of how many issue tickets they are allowed to make over websites detecting their AdGuard or still having ads that their premium extension or app did not remove?

**Comment by BlazDT** [comment]
No limit. Annoyances filter is not removing it, but a lot of other Annoyances.
