### ISSUE TITLE
Okay I am getting frustrated I am being told to fix this my self and having to figure out on how to learn to block elements by my self I am ready to to no longer be a paying customer to AdGuard I am very upset 

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#138562]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.5

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gaypornhdfree.com/porters-big-load/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment> No one is helping me and iv been told to figure this out my self so what I am paying AdGuard for then? I am very angry and I am ready to no longer be a paying customer to adguard

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>
![62D009A3-AFD5-47BF-AEAC-1B57CDE9E22B](https://user-images.githubusercontent.com/118444664/209791563-71892e60-720d-4859-8817-fd1d8337f714.jpeg)
![3C285783-6FA5-4A94-8D0F-2BA8A6A5F9D7](https://user-images.githubusercontent.com/118444664/209791570-f3ed84c9-ff21-4017-ad54-f7fa74e0c53c.jpeg)
![CFD94375-8ACE-4AA5-8A1D-456EB25CC7F7](https://user-images.githubusercontent.com/118444664/209791577-f8170a74-2218-4a02-883c-cfe594902f75.jpeg)
![6051CA8B-4C9D-4C0D-A780-5632D7D614DB](https://user-images.githubusercontent.com/118444664/209791582-17f3c2ca-15d2-4029-b1b1-d9932e7ad4c7.jpeg)
![836FEBB1-9864-4574-90C7-4A58153EA636](https://user-images.githubusercontent.com/118444664/209791586-c2271d5b-c932-45d3-aeb0-9c221d4a5ac8.jpeg)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
That elements are not advertisements.

**Comment by malicerainbow** [comment]
> That elements are not advertisements.

So you will only do for me ad related issues?

**Comment by malicerainbow** [comment]
> That elements are not advertisements.

I wish you would have said that earlier
