### ISSUE TITLE
Block only the element I select but adguard blocks other elements of similar as well I want only that element I selected blocked only

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#138551]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.5

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gaypornhdfree.com/porters-big-load/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment> Okay so iv notice when ever I use adguard to block an element on a webpage it blocks similar elements of the one I blocked but I only wanted the one I selected blocked I don’t need help from adguard I’d like to be in control of what’s blocked only please2. 

Like for example in this screen shots I only wanted that dog image blocked but it blocked every image search that is exactly located as the dog one
![1546D61E-DEA9-4082-A56F-DDB9D308B6B8](https://user-images.githubusercontent.com/118444664/209779588-77b48bd4-48d6-4784-ad24-02734b75276e.jpeg)
![5C068438-A112-40D6-B66F-B3B7011DFE57](https://user-images.githubusercontent.com/118444664/209779594-048b4d6d-fe10-40f6-9471-fd2467121be6.jpeg)
![E107832A-5944-411A-A92E-AB0032B06568](https://user-images.githubusercontent.com/118444664/209779596-5238875e-031f-4604-93d3-045dbf86e3b0.jpeg)
![9BD65280-8618-49E9-8457-A3FFB42BFCE7](https://user-images.githubusercontent.com/118444664/209779601-19b4cf6f-e742-416b-ae16-dd52597b881b.jpeg)

3. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Here is the documentation how to create the rules
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters

**Comment by malicerainbow** [comment]
> Here is the documentation how to create the rules
> https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters

But will I be able to block just what I selected and nothing else?

**Comment by malicerainbow** [comment]
> Here is the documentation how to create the rules
> https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters

Alex?????
