### ISSUE TITLE
[iOS] m.ru.investing.com missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1385]
http://m.ru.investing.com/markets/
![image](https://cloud.githubusercontent.com/assets/15856304/12576574/57e8ab00-c41d-11e5-9a8b-a91298cd81fc.png)

DKF-869-97229

**Comment by Alex-302** [comment]
@evgeniy-ADG 
а можешь у себя проверить на каком-нибудь айфоне? Это гугловая реклама, должна блокироваться

**Comment by evgeniy-ADG** [comment]
@Bohdan-SUP проверьте на айфонах, пжлйст
