### ISSUE TITLE
I don’t understand how to create my own block element rules like Alex ask I don’t know this stuff and we’ll I don’t appreciate someone who pays for adguard premium to have to try and figure this out him self

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#138553]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.5

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gaypornhdfree.com/porters-big-load/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>
![310EC940-0A2C-4367-B2C8-4AD855B8D005](https://user-images.githubusercontent.com/118444664/209783878-ff7da48a-3a31-4d8e-8d24-2de3701c2fa7.jpeg)

2. Screenshots
<details><summary>Screenshot 1:</summary>

![26ACC7DF-9CCE-4C93-B203-3FC0DA8D4C1D](https://user-images.githubusercontent.com/118444664/209783720-07fe1986-49de-4657-86ae-d2d6173ac18a.jpeg)
![226F1882-6256-410C-8DDA-866B477015C2](https://user-images.githubusercontent.com/118444664/209783726-08e0bb2c-45d3-477b-9ae5-4cb0516d5617.jpeg)
![27C0DC16-B74C-4E72-966F-DBA40B70DD25](https://user-images.githubusercontent.com/118444664/209783729-4ab25400-e440-4d36-b5a0-7282968fc576.jpeg)
![9B3AB798-275A-46AD-A90E-C53550C2B913](https://user-images.githubusercontent.com/118444664/209783731-a934ccf7-426f-4277-ac5e-bd921bd1da4b.jpeg)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by malicerainbow** [comment]
This is the element I blocked nothing on it is similar to the documentation Alex showed me on how to block an element I don’t know how to do this 



google.com##div.T1diZc.KWE8qe:nth-child(8) > c-wiz.SDsPCf.FA7L0b.P3Xfjc.SSPGKf.BIdYQ:nth-child(2) > div.ZuT88e:nth-child(3) > c-wiz:first-child > div:nth-child(2) > div.z1Vi9d > div.dMnSie.tmS4cc.blLOvc.snjnxc > div:first-child > div.eill-c:nth-child(2) > span > div.l7VXJc.pZqGvd.sMVRZe:first-child > div.EVPn8e:last-child > div.isv-r.PNCib.MSM1fd.BUooTd:first-child

**Comment by malicerainbow** [comment]
I do not appreciate being told to do this my self when I pay for adguard 


I am not a coder, I am not a developer, I do not know how to do this okay


I am not smart enough for this

**Comment by Alex-302** [comment]
`google.com##img[src^="data:image/"]`

**Comment by malicerainbow** [comment]
> 



> google.com##img[src^="data:image/"]

I don’t understand is that a rule to block an image or do I add an image into this?


Alex I’m not a developer or a coder!!!! I am just a adguard premium customer why are you making me figure this out? I don’t get this

**Comment by malicerainbow** [comment]
No one is helping me
