### ISSUE TITLE
I want only the element I selected block not elements similar to the one I blocked also.                       Either teach me how to do this or do it yourself but don’t hand me something and expect me to figure it out on my own otherwise why am I paying for adguard????               Like I am really upset right now with Adguard and Alex 

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#138559]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.5

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari, the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gaypornhdfree.com/porters-big-load/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

![EC498B19-3977-40D4-94E0-6811E6F3BCDB](https://user-images.githubusercontent.com/118444664/209789264-81a8fa08-1585-40e2-889c-35cf539103b8.jpeg)
![6C0E6744-5748-4208-B149-D9D7F4FD2E3F](https://user-images.githubusercontent.com/118444664/209789265-ef118afb-45b5-4a75-b5db-05d89b67ddb0.jpeg)
![541B1D93-EEFF-4FA3-8FC5-C49BA9807822](https://user-images.githubusercontent.com/118444664/209789267-c4b8f0f9-5675-4f65-b895-67e797655226.jpeg)
![286E9789-792F-4C8F-AB20-FF7839FC236B](https://user-images.githubusercontent.com/118444664/209789270-3f3c3dad-a474-4d7b-ad38-f9ce36de6002.jpeg)

For example I blocked the element of a dog image but it also blocked similar element of any Google image search that’s located exactly where the dog image was
</details>

I want only the dog image blocked and nothing else of different Google image searches

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by malicerainbow** [comment]
Teach me how to do this or do it your self but don’t expect me to hand me something for me to figure it out on my own otherwise why am I paying for your adblocker?

**Comment by Alex-302** [comment]
don't create new issues, write in existing

**Comment by malicerainbow** [comment]
> don't create new issues, write in existing

No one is helping me not even you!!!!

**Comment by malicerainbow** [comment]
> don't create new issues, write in existing

I don’t know this so either teach me or do it for me but do t expect me to figure it out on my own!!!!!

**Comment by Alex-302** [comment]
We block ads, don't teach.

**Comment by Alex-302** [comment]
This is enough
https://code.tutsplus.com/tutorials/the-30-css-selectors-you-must-memorize--net-16048

**Comment by malicerainbow** [comment]
> We block ads, don't teach.

Than stop handing me something to figure out on my own

**Comment by malicerainbow** [comment]
> This is enough
> https://code.tutsplus.com/tutorials/the-30-css-selectors-you-must-memorize--net-16048

Fix my blocking event issue please!!!! I pay for AdGuard

**Comment by malicerainbow** [comment]
> This is enough
> https://code.tutsplus.com/tutorials/the-30-css-selectors-you-must-memorize--net-16048

All you did was sent me a link fix my issue please!!!!!

**Comment by malicerainbow** [comment]
> This is enough
> https://code.tutsplus.com/tutorials/the-30-css-selectors-you-must-memorize--net-16048

Will you please fix my issue please I do not understand this
