### ISSUE TITLE
Okay perhaps I have not made this clear I am not a coder I am not a developer I am not a programmer I am not any of those things I am not smart enough to be any of those things I am just a premium adguard customer that’s it so I don’t appreciate being give this and you assume I get it or me figuring this out on my own.           I’m getting annoyed

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#138556]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.5

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

GitHub.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment> I WILL SAY THIS AGAIN I AM NOT A CODER I AM NOT A PROGRAMMER I AM NOT A DEVELOPER I DO NOT NOT KNOW HOW TO DO THESE THINGS WHICH IS WHY I PAY FOR ADGUARD PREMUIM 2. 

IM GETTING ANNOYED 

So stop sending me this because I don’t get it I don’t comprehend it I don’t know how to do it 

So either explain it to me 1 on 1 or resolve it yourself 

But I am not going to be given something just to figure out on my own while I pay for adguard

So either train me or resolve this for me 
3. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
You did not state your current problem.

**Comment by malicerainbow** [comment]
> You did not state your current problem.

I did to Alex and all he did was sent me a documentation of user rules I don’t understand this 

BlazDT

**Comment by malicerainbow** [comment]
> You did not state your current problem.

My issue is not resolved aka closed BlazDT

**Comment by BlazDT** [comment]
What about posting the problem again. Without knowing your problem I cannot help.

Opening a new thread with no information about a problem or link to the problem will get the issue closed.

**Comment by malicerainbow** [comment]
> What about posting the problem again. Without knowing your problem I cannot help.
> 
> Opening a new thread with no information about a problem or link to the problem will get the issue closed.

Well I had a thread with all the information and all Alex did was sent me a documentation

**Comment by malicerainbow** [comment]
> What about posting the problem again. Without knowing your problem I cannot help.
> 
> Opening a new thread with no information about a problem or link to the problem will get the issue closed.

I just made a new thread BlazDT with all the information and screenshots 


Of which I already made by the way where Alex was of no help

**Comment by malicerainbow** [comment]
> What about posting the problem again. Without knowing your problem I cannot help.
> 
> Opening a new thread with no information about a problem or link to the problem will get the issue closed.

I feel like no one is helping me again

**Comment by BlazDT** [comment]
Please post a link to this thread, thank you.

**Comment by malicerainbow** [comment]
> Please post a link to this thread, thank you.

https://github.com/AdguardTeam/AdguardFilters/issues/138559#issuecomment-1366505790

**Comment by malicerainbow** [comment]
> Please post a link to this thread, thank you.

No one is helping me and I feel I’m just going to have to make more threads until someone does

**Comment by malicerainbow** [comment]
> Please post a link to this thread, thank you.

I am a paying customer and this is how I’m being treated of having to figure this out on my own
