### ISSUE TITLE
[pop-up] reports.adguard.com

### ISSUE THREAD

**Issue by Tctftctdtdtd** [AdguardTeam/AdguardFilters#138515]
### My filters

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, RU AdList - Counters

### Comment

Здравствуйте!
Очень раздражает всплывающее окно. Я конечно понимаю что это ваш сайт и всё такое, но когда твой браузер хранит куки 3 мин, и приходится по сто раз закрывать эту гадость это просто ни в какие ворота.

![1953887E-39AD-43BA-ABDA-368AB4C114EE](https://user-images.githubusercontent.com/121509909/209699223-ceb89672-0229-4302-8cec-43160f488b84.jpeg)

**Comment by Alex-302** [comment]
Убрал для репортилки.
