### ISSUE TITLE
joy.land [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#13857]
**Site**: http://www.joy.land/fly-with-rope.html

**Issue**: Please remove the adblock message on the page.

**Screenshot**: http://prntscr.com/iw5da4

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.181 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by AdamWr** [comment]
I can't reproduce it and this game doesn't work on my end even without AdGuard.

@Alex-302 Could you please check it?

**Comment by Nzzyme** [comment]
Please close this issue. Clicking on the close button closes the adblock message and you can proceed with the game. However, if the message can be removed, then it's better. Thanks
