### ISSUE TITLE
keygames.com [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#13865]
**Site**: http://keygames.com/fly-with-rope-2-game/

**Issue**: Please remove the adblock message on the page.

**Screenshot**: http://prntscr.com/iw5nr8

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.181 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by Nzzyme** [comment]
Gentle reminder. Thank you.

**Comment by Alex-302** [comment]
Not reproduced.
@AdamWr please take a look.

**Comment by AdamWr** [comment]
Fixed.
