### ISSUE TITLE
games.co.uk [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#13863]
**Site**: http://www.games.co.uk/game/fly-with-rope

**Issue**: Please remove the adblock message on the page.

**Screenshot**: http://prntscr.com/iw5lnf

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.181 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by AdamWr** [comment]
Fixed - https://github.com/AdguardTeam/AdguardFilters/commit/b8a60462a6818e74458039bd1d1439320ba227d2
