### ISSUE TITLE
Improve general_extensions header comment examples

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardFilters#138769]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

it should be "rule per line", isn't?
```
! Good: example.org#$##rek { display: none !important; }; example.org#%#//scriptlet('set-cookie', 'ad', '0'); example.org#%#document.cookie = "ad =0"; ; example.org$$script[tag-content="ad"][max-length="3000"].
! Bad: example.org###rek (should be in specific.txt)
```
https://github.com/AdguardTeam/AdguardFilters/blob/master/BaseFilter/sections/general_extensions.txt#L5

### Proposed solution

also the readability is better
```
! Good:
!   - example.org#$##rek { display: none !important; }
!   - example.org#%#//scriptlet('set-cookie', 'ad', '0')
!   - example.org#%#document.cookie = "ad =0";
!   - example.org$$script[tag-content="ad"][max-length="3000"]
! Bad:
!   - example.org###rek (should be in specific.txt)
```

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/170814
