### ISSUE TITLE
caribou coffee app

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#138797]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.caribou.caribouapp

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

@@||device-api.urbanairship.com^$app=com.caribou.caribouapp

@@||remote-data.urbanairship.com^$app=com.caribou.caribouapp

app wont open without these

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
i tried just one or the other and you need both for app to work

**Comment by jordanswrld94** [comment]
also another appsflyer tracker

||dlsdk.appsflyer.com^

**Comment by jordanswrld94** [comment]
yea adding those two rules i suggested helps. but adding the dnsrewrite breaks unfortunately

**Comment by jordanswrld94** [comment]
sorry  i just realized its easyprivacy issue not adguard. could we block ||dlsdk.appsflyer.com^ though

**Comment by Alex-302** [comment]
Ok, please test

```adblock
||device-api.urbanairship.com^$dnsrewrite=urbanairship.com
||remote-data.urbanairship.com^$dnsrewrite=urbanairship.com
```
and ckeck if they applied using `dig` or `nslookup`.


> could we block ||dlsdk.appsflyer.com^ though

I don't know. Need request's content.

**Comment by jordanswrld94** [comment]
![Screenshot_20230110_142006_Nslookup](https://user-images.githubusercontent.com/118186787/211653721-0c0a0dd1-b698-4cbd-a895-b00334e0811b.jpg)
![Screenshot_20230110_142002_AdGuard](https://user-images.githubusercontent.com/118186787/211653728-af953e23-5edf-4b11-858e-c346738c42c4.jpg)

this is the result

**Comment by Alex-302** [comment]
Ok added your rules (not fixes if domains are blocked by DNS)

```adblock
@@||device-api.urbanairship.com^$app=com.caribou.caribouapp
@@||remote-data.urbanairship.com^$app=com.caribou.caribouapp
```
