### ISSUE TITLE
Stealth mode affects ok.ru and youtube.com functions

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1390]
Здравствуйте ! Ребята , у меня есть наблюдение не знаю важно вам или нет , но я решил поделиться с вами .Я делюсь снимками что происходит когда я в Adguard в Антитрекинге  ставлю галочку  Скрыть User-Agent  . У меня Win 7 браузер Mozilla 

![image](https://cloud.githubusercontent.com/assets/15856304/12614913/45b87778-c50b-11e5-8341-cb8305b5f831.png)
![image](https://cloud.githubusercontent.com/assets/15856304/12614923/5373906e-c50b-11e5-91d6-3c5fd35f71a4.png)

![image](https://cloud.githubusercontent.com/assets/15856304/12614930/5a55d982-c50b-11e5-84ac-d04c46256011.png)
![image](https://cloud.githubusercontent.com/assets/15856304/12614933/60bd50b6-c50b-11e5-81d7-5a19cf3d3738.png)

ZID-205-31127

**Comment by Alex-302** [comment]
Важно знать, какой юзерагент. Не рекомендую ставить совсем экзотические. Пусть попробует юзерагент Хрома

**Comment by evgeniy-ADG** [comment]
@Alex-302 Вот, что пользователь ответи: "Добрый день ! Уважаемые разработчики, я сообщил вам об этой проблеме для того чтобы помочь вам в усовершенствовании ваших проектов (это просто информация для вас) , а мне это не мешает , я просто не включаю Скрыть User-Agent "
Если мы в курсе, то можно закрывать.

**Comment by Alex-302** [comment]
Если дефолтный юзерагент(линукс вроде), то принимаемый контент в формате, который в виндовом браузере не проиграется.
Пусть попробует в пустую строку юзерагента ввести
```
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36
```
и на 2ip.ru или аналоге сверит даные про браузер (Chrome 41) и проверит эти сайты

**Comment by evgeniy-ADG** [comment]
Вот еще пишут:

При включении функции антитрекинга "Скрыть user - agent" С настройкой по умолчанию. В браузере Firefox актуальной версии на 05.02.16 Сайт youtube.com список подписок моих каналов. Не отображаеться картинка и искревлён сам список. Линии отображаються не корректно (жирные в списке подписок, должны быть только маленькие рамочки для роликов) Решите проблему пожалуйста.

**Comment by Alex-302** [comment]
пусть другие юзерагенты пробуют, только их фоксоподобных. Иначе проблем не избежать.

**Comment by evgeniy-ADG** [comment]
Пользваватель скрыл его вообще, юзер-агент, и стлокнулсяс проблемой на ютюбе.

**Comment by Alex-302** [comment]
Всмысле скрыл? Пустая строка у него?
Вспомнил, там же ОС как Линукс представляется по дефолту(при пустой строке), поэтому косяки.
Пусть такой попробует
```
(Windows NT 6.2; WOW64) KHTML/4.11 Gecko/20130308 PaleMoon/25.1
```

**Comment by evgeniy-ADG** [comment]
Спасибо, отписал. Буду в курсе.
