### ISSUE TITLE
kylie.com

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#139120]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.46.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.kylie.com/

### What filters do you have enabled?

AdGuard Annoyances filter

### Affected site:
`https://www.kylie.com/`

(Click "**CONTINUE TO SITE**")

### Issue:
Various breakage, due to a blocked cookie consent, which needs to be accepted.
E.g. the images for more YouTube videos (below the big embedded one) are missing, and the Merch items are out of position!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **AdGuard Annoyances filter**

### Problem rules:
`||cdn.privacy-mgmt.com^$third-party`
`||privacy-mgmt.com/mms^`

### Possible fixes:
Simply:
`@@||cdn.privacy-mgmt.com^$domain=kylie.com`

..or more specifically:
`@@||cdn.privacy-mgmt.com^*/wrapperMessagingWithoutDetection.js$domain=kylie.com`
`@@||cdn.privacy-mgmt.com/mms/*/get_site_data?$domain=kylie.com`
`@@||cdn.privacy-mgmt.com/privacy-manager/$domain=kylie.com`
In this case, the last rule is needed in order to be able to customize your consents ("**SHOW PRIVACY MANAGER**").

### Other problem filters:
* ~~**I don't care about cookies** (@kiboke)~~ _(FIXED)_
 
~~`/wrapperMessagingWithoutDetection.js$domain=~standard.co.uk|~ladbible.com|~theguardian.com|~theguardian.com.|~bild.de|~autoweek.nl|~computerbild.de|~bold.dk|~welt.de|~t-online.de|~sport1.de|~focus.de|~chip.de|~faz.net|~n-tv.de|~wunderweib.de|~helpster.de|~tvmovie.de|~praxisvita.de|~cosmopolitan.de|~giga.de|~ostsee-zeitung.de|~sky.com|~lvz.de|~mein-schoener-garten.de|~boerse-online.de|~tvspielfilm.de|~autobild.de|~aftonbladet.se|~bike-bild.de|~bz-berlin.de|~travelbook.de|~cyberport.at|~cyberport.de|~golem.de|~express.de|~ksta.de|~utopia.de|~sky.it|~tv8.it|~cielotv.it|~bndestem.nl|~volkskrant.nl|~rundschau-online.de|~rtl2.de|~capital.fr|~derstandard.de|~derstandard.at|~unsere-helden.com|~rtl.de|~stern.de|~myaccount.hln.be|~nu.nl|~maennersache.de|~dpgmedia.nl|~destentor.nl|~zeit.de|~ad.nl|~dpgmedia.be|~heise.de|~t3n.de|~11freunde.de|~finanzen.at|~finanzen.net|~insider.com|~transfermarkt.at|~transfermarkt.ch|~transfermarkt.co.uk|~transfermarkt.com|~transfermarkt.com.tr|~transfermarkt.de|~transfermarkt.fr|~transfermarkt.it|~transfermarkt.nl|~transfermarkt.pl|~transfermarkt.pt|~transfermarkt.us|~vip.de|~businessinsider.de|~clever-tanken.de|~fitbook.de|~idealo.at|~idealo.co.uk|~idealo.de|~idealo.es|~idealo.fr|~idealo.it|~meinestadt.de|~metal-hammer.de|~musikexpress.de|~myhomebook.de|~noizz.de|~politico.eu|~rollingstone.de|~stylebook.de|~techbook.de|~testbild.de|~wieistmeineip.at|~wieistmeineip.de|~wieistmeineip.ch`~~

~~`privacy-mgmt.com$domain=~standard.co.uk|~theguardian.com|~theguardian.com.|~bild.de|~computerbild.de|~bold.dk|~welt.de|~t-online.de|~focus.de|~chip.de|~faz.net|~n-tv.de|~spiegel.de|~privacy-mgmt.com|~wunderweib.de|~helpster.de|~tvmovie.de|~praxisvita.de|~cosmopolitan.de|~giga.de|~ostsee-zeitung.de|~sky.com|~lvz.de|~mein-schoener-garten.de|~boerse-online.de|~tvspielfilm.de|~autobild.de|~bike-bild.de|~bz-berlin.de|~cyberport.at|~cyberport.de|~golem.de|~express.de|~sky.it|~tv8.it|~cielotv.it|~epaper.volksstimme.de|~volkskrant.nl|~rtl2.de|~si.com|~derstandard.de|~derstandard.at|~unsere-helden.com|~rtl.de|~stern.de|~freenet-funk.de|~maennersache.de|~heise.de|~t3n.de|~11freunde.de|~finanzen.at|~finanzen.net|~insider.com|~transfermarkt.at|~transfermarkt.ch|~transfermarkt.co.uk|~transfermarkt.com|~transfermarkt.com.tr|~transfermarkt.de|~transfermarkt.fr|~transfermarkt.it|~transfermarkt.nl|~transfermarkt.pl|~transfermarkt.pt|~transfermarkt.us|~vip.de|~businessinsider.de|~clever-tanken.de|~fitbook.de|~meinestadt.de|~metal-hammer.de|~musikexpress.de|~myhomebook.de|~noizz.de|~politico.eu|~rollingstone.de|~stylebook.de|~techbook.de|~testbild.de|~wieistmeineip.at|~wieistmeineip.de|~wieistmeineip.ch`~~

~~**Note to kiboke:**
Your rules have an error in them..
`theguardian.com` is listed twice, and there's a misplaced punctuation mark behind the redundant listing!~~

--

### System info:
* OS/version: Windows 10 Pro 21H2 (x64)
* Browser/version: LibreWolf v108.0.1-1 (x64) (Tracking Protection = Standard)
* Adblock Extension/version: uBlock Origin v1.46.0

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
Is a little diffrence beetween:
```
https://www.theguardian.com./international
https://www.theguardian.com/international
```

https://en.wikipedia.org/wiki/Fully_qualified_domain_name

So if ABP don't fixed problem that how long filter may need version with dot.

**Comment by THEtomaso** [comment]
OK, but uBO flags the URL as being incorrectly formatted though (red).

**Comment by krystian3w** [comment]
I wouldn't bother until uBo starts marking the whole filter as wrong (unlocked pop-up on pages where safe scripts can be still blocked).

**Comment by kiboke** [comment]
@THEtomaso thanks for letting me know, it will be fixed in IDCAC soon.

**Comment by Alex-302** [comment]
It is broken even without AdGuard

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/211147607-529e5d37-fc25-4d98-94d3-aef7a1ebb95f.png)


</details>

**Comment by THEtomaso** [comment]
> It is broken even without AdGuard

Works just fine for me (tested with Chromium-ungoogled, LibreWolf and PaleMoon):

![filterissue-kylie](https://user-images.githubusercontent.com/9382674/211152812-e3754943-ba21-41c9-a737-7b3cea8f0441.jpg)

**Comment by Alex-302** [comment]
@AdguardTeam/filters-maintainers Please take a look.

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
The website has low visitors, therefore, we do not add any rules.
