### ISSUE TITLE
[iOS] www.theverge.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1392]
Missed ad on page:
http://www.theverge.com/2016/1/25/10829594/microsoft-iphone-keyboard-word-flow-features

![image](https://cloud.githubusercontent.com/assets/15856304/12621542/b9c89828-c529-11e5-88e3-a27bdc16c20d.png)

RHS-316-75003

**Comment by Alex-302** [comment]
@evgeniy-ADG 
It is clean on my end. Please check it.
Do you recommend filters update for users with ads?
