### ISSUE TITLE
https://www.caranddriver.com/ - false blocking

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#13934]
> We have recently migrated areas of our site from an angular framework to a vueJS framework, and have been notified by a user that your application is treating our social section (iFrame) as an ad and blocking it. I’ve downloaded the Chrome extension, and replicated the event as well.
> 
> Here’s an example of a migrated page: https://www.caranddriver.com/reviews/2019-mercedes-benz-cls-class-first-drive-review
> Here’s an example of a page not yet migrated, where your application does not block the social section: https://blog.caranddriver.com/heres-a-look-at-the-2019-acura-rdx-a-spec-in-production-form/

![image](https://user-images.githubusercontent.com/15856304/37951425-08259608-31a5-11e8-9a1b-b174ce845328.png)

**Comment by Alex-302** [comment]
Not reproduced:
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/37977509-8416afda-31ec-11e8-9ce2-b859ccda0892.png)

</details>
