### ISSUE TITLE
[iOS] dreamfilmhd.bz & www.flashback.org

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1393]
Missed ad on page:
http://dreamfilmhd.bz/
![image](https://cloud.githubusercontent.com/assets/15856304/12621651/2751c086-c52a-11e5-85b8-01c97baa2e61.png)

Missed ad on page:
https://www.flashback.org/
![image](https://cloud.githubusercontent.com/assets/15856304/12621673/49a1e6d4-c52a-11e5-977e-79bee8dbafe2.png)

GMA-249-27089

**Comment by Alex-302** [comment]
Фильтры старые. Посовеуй обновиться.

**Comment by ameshkov** [comment]
Again popups are there

**Comment by ameshkov** [comment]
![screenshot_2016-02-26-11-26-13](https://cloud.githubusercontent.com/assets/5947035/13390770/700d51b6-dee1-11e5-93af-3c08d49f4547.png)
