### ISSUE TITLE
[iOS] m.tmz.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1394]
Incorrect blocking on page:
http://m.tmz.com/#news/

![image](https://cloud.githubusercontent.com/assets/15856304/12621758/ad3e4066-c52a-11e5-9e1b-ec628565f074.png)

AXE-726-83394

**Comment by Alex-302** [comment]
It is clean on iPad.
Can you check it on your device?
