### ISSUE TITLE
jbhivi.store

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/AdguardFilters#139524]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Can access phishing website `https://jbhivi.store/`

### Proposed solution

Block phishing website `https://jbhivi.store/`

**Comment by Alex-302** [comment]
dead
