### ISSUE TITLE
bmj.com advert

### ISSUE THREAD

**Issue by timoz** [AdguardTeam/AdguardFilters#139648]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [✅] I am running the latest version
- [✅] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed - don't know how to do that

### Issue Details

* AdGuard for Safari version:  
* Environment name and version: **Version 16.1 (18614.2.9.1.12)**
* Operating System:  **13.0.1 (22A400)**
* Filters you use in AdGuard: all on
* Any other browser extensions you have installed:
* 1Password, 
* Mendeley,
* ecosia

* **Version of AdGuard for Safari:**
  *   1.11.10 (build 266, CT 2.0.34)
* **Environment name and version:**
  *  Safari Version 16.1 (18614.2.9.1.12)
* **Operating system and version:**
  *  13.0.1 (22A400
* **Filters you use in AdGuard:**
  *  all on
* **Any other browser extensions you have installed:**
  * 

### Expected Behavior

To see no advertisements on the website

### Actual Behavior

banner advertisement across the top of my screen  with "Ads by Google" in the top right corner of the ad
### Screenshots

<img width="1432" alt="Screenshot 2023-01-08 at 07 47 42" src="https://user-images.githubusercontent.com/732498/211169788-9f540b32-47d8-4dda-a57d-b220bf87522a.png"><details><summary>Screenshot:</summary>

</details>

**Comment by Versty** [comment]
@timoz Hi! 
This issue has been transferred to the relevant repository.

**Comment by jellizaveta** [comment]
@timoz Fixed. Filters update should be available in 1-2 hours.
