### ISSUE TITLE
goldmesoil.live

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardFilters#139667]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://500654179.kilpa2017.fi/813712.html

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, List-KR

### Add your comment and screenshots

**Redirections List:**

0. Click the provided URL in [Google Search result page](https://www.google.com/search?q=%EC%95%A0%EB%93%9C%EA%B0%80%EB%93%9C+site:kilpa2017.fi&tbas=0&tbs=qdr:m). [^1]
1. `https://500654179.kilpa2017.fi/813712.html`
2. `https://itthis.f9dle.skin/?u=na8k605&o=a1tm57q&t=new_ip&cid=2b795g0ljktr2`
3. `https://913.goldmesoil.live/pnfcsfbf/?u=na8k605&o=a1tm57q&t=new_ip&cid=2b795g0ljktr2&f=1&sid=t4~jgizt3qlik13qv2gn5hzdipo&fp=IZVTo4K7gl1InJF8erStEKKN8KuoP9ruq3GaVCctv6ZSF4wVl%2BWs99kkfhbm%2B7fR7rK3zMjSOwd6nmuZFEDSOYFXYNdUcY0nR94ZYwhS2Kq3Ebr06%2BLMtkDGbYkP%2B0taSF4y6y7873QaJWWcKmBujkqPp%2BGX7Ux7qwKx9YMys2iffuq5No3suYSOk5GBnzj%2B7AjpNL6Ct%2BW%2B3gmkMIZ6vhX0OL5j1wVJqRGnl9quKcereUCygRliwkZPD5jmViXuilErfOGGzEeVF1PcQjbvG5kz3A6840SqiOZSYLBcD%2F7ufgHRKXfaqeD7ceYEmnsnJPwJVGBDfCHCuV3SEg4QsbhLdBzGXJO2Wtx9pOVWNtGy7CaAOUVSlcmngWY5BnFQbaeUY8J41nX7ArJZnbfnpcRt%2F2doz8ToFZLYHK1xGgO9yAzHutiw7HnjWc3HkLhBTqGPLWAvCGTFXJ%2BsEtUqrujH%2FcgGVL6zEMBWJ2e%2Bhe0XKCI5Uu8bzBsy1GrKirNZhoypYI4CMWhfV0oT4NeWXgKhGJYJ%2BeDGmq%2BMF54jmjW2aWxr4%2FVuQ6G76QXMCNMFrGWrXbWthr%2BZZYitcKLF96KeW%2BLi%2FX57uAaqFnWBIredh5Go1n0jVU7oDA1v%2B%2Fe3W9oT6fT3jISXbXKR7U8F1sgEzKFnRufcMPdQhsN4FwbGS9S6y8nWvv61M7fb7aYsmwIac5KjJp99XfV5QtpUtf3MKlW9IHRJa2Ki%2FxZ4hwZTCX2bC20F0zj1YFEj5ClDBwX%2FGazVGtl9PUdkJks5X5rfLp1aQGN1JfKJyajWPpRJL%2FlCxTyQanqXMpnzmhT1nz%2FxQM%2BuIo%2FX4mszlFtatwkJ8tyR3%2BO4zW%2Foshcg02h9Iumt3YqSIrWhs39GpH1BZn1SXzt%2BrFhY5DWNmN1Y%2FewSnKFRPb78nzvQ1hYz8qKKdEzDhx1v0TsM7TtkoHfulpRDPEBt%2Fr05okOpAal7s2yQWdTD4kr9l6TCJgJV1sFQd%2FyHgecRK8XhQz2ao0DLznCubbLoWo4xIfa%2B9y6FgQPDm9VgA%2FPdl4THDjA9HjZDMKdmHVSs6inOSrB3epAvGUFlM4%2FMfYg5hfRVCKnhTVqHZ5xhT0mDfbsrEdsvnEmRvK%2FsJBYi02k7IuLQTbavazER27sEhzajan0JPRi7w3jtLaomjQ9pZB89e0c6nowD40nnlhbyj1EBr7liMCak0Ot399nPLPS9FNmB6FuK%2FUwH60gGD4aMLDyM8r6q7bIoa4krpb229nx%2BD8i5vFV%2FLT0LZXvdw4Ub%2B7mwAiyGcY%2BknnhXrco1oBqLdy%2F9yT4J6LwEMuP%2Bfsf1eyt%2BvwjVWSxkQk5mPe07dIF97fK906Bpyqxu3fOhgMhR5qg%2BELXLy86yhdhMG4Cvt9R6BhuGq7N3tRuRB8%2FqaXJBsxGzAXS8g6tBmkC%2BSrYuy0p6lsJp5pu3wWT6vgb0Y%2FbHeypzpGwpV0NHLGsJxOK3f%2BKFSSGmPiVs2PKt8heMveGXd%2FSTmoyxtEFeOaOcU%2FH7Ed%2Fugx1IS3rBOuiuUmCrmErP%2BkxvsIzecVpAj5ajNopbwSEkcb13Ycvp5kIrCHT8z7vyBEE9lEg%2BOgoLEuNpPRNBKgQWTqdnYi4%2B%2Flum5Px5xEDH0K%2BPghN9suyYdqwoOD3XJWYHr8M067X3LzjEfp9UYlDI%2F1KiGTYiw%2FKAOc%2B%2FzQCjS%2F9boWfAnf22PQ9YHtGaDJfLQjdZcaDXvTs24ZW%2Bs951vfwsvMeLw6sObApZS0lsA1ocB5jsLWKsHCZYCXmDMMy8rhSKj48cAA5QqCXxiU0%2FsNvi%2FnCax7bwBDa2a%2F7vrYmkbQ5zfQLGHm2NLz9UQ20CSze9lpemKYfuSiEbDzou1C%2FeKAXqa0SBmEDwAxeAFA6mi%2FSIT1mcpc28PKQb`

**Virustotal Results:**
 - https://www.virustotal.com/gui/domain/goldmesoil.live
 - https://www.virustotal.com/gui/url/4c191fba7be99f37ea15ca29becd5e8541ce1f7b8ed74e28f6da1edd0bc67d42?nocache=1

[^1]: Titled as `젊꼰 디시 - kilpa2017`.

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
Eset Black Listed `goldmesoil.live`

**Comment by DandelionSprout** [comment]
I propose:
```
||sintiwent.buzz^$all
||sawsupportquiet.buzz^$all
||yepsimmen.live^$all
||rememberespeciallyturn.buzz^$all
||thoseverbmuch.buzz^$all
||crymanbee.buzz^$all
||wantledwife.buzz^$all
||catabovewinter.buzz^$all
||goldmesoil.live^$all
||againstbarsolution.buzz^$all
||spacesharpone.buzz^$all
||legenergybreak.buzz^$all
||asreadmeat.buzz^$all
||pointcookship.buzz^$all
||pointladydear.buzz^$all
||/\.(live|buzz)/.*&[a-z]{1,3}=[a-zA-Z0-9%]{150,}/^$document,popup
51.68.87.229$network
||f9dle.skin^$all
||kilpa2017.fi^$all
```

**Comment by Oniqqqq** [comment]
Thanks added to safe browsing

**Comment by piquark6046** [comment]
@Oniqqqq @iam-py-test 
Its DNS information is unavailable.
https://dns-lookup.com/goldmesoil.live

**Comment by piquark6046** [comment]
Please block tapwhomjay.live instead.

**Comment by piquark6046** [comment]
@Oniqqqq @iam-py-test 
They changed again.
Please block sadaasend.live instead.

**Comment by piquark6046** [comment]
@Oniqqqq @iam-py-test 
They changed again. (Now, hiowmas.live)
I think that using Regexp will help to resolve this issue.

**Comment by iam-py-test** [comment]
I see `2021.sagahaclub.live ` (https://app.any.run/tasks/06348b92-26cf-42bc-a725-5e2d4885831e). Any idea if the subdomain is always 2021?
Also, oddly, I get a different result in different sandboxes (one gives me the prize page, the other gives me a notification scam)
