### ISSUE TITLE
aemx.hrkbs.com

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#139628]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://aemx.hrkbs[.]com/login.php`

### What filters do you have enabled?

AdGuard Base filter, AdGuard Japanese filter

### Add your comment and screenshots

1. A long-standing phishing site spredding via email, having reported by many phishing hunters:
```
https://twitter.com/catnap707/status/1608589270859800578
https://twitter.com/harugasumi/status/1611914268563374080
https://twitter.com/hunter_phishing/status/1608530933875085312
```

2. Screenshots
<details><summary>Screenshot 1:</summary>

![scam1](https://user-images.githubusercontent.com/58900598/211230449-eb76400f-ac4e-4e08-b497-b82685e29b3b.png)

</details>

<details><summary>Screenshot 2:</summary>

![scam2](https://user-images.githubusercontent.com/58900598/211230451-b9ead550-ff5d-4e0a-b3a8-c859b29502b1.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Oniqqqq** [comment]
added this domain to our safe browsing list
