### ISSUE TITLE
Online Malicious URL Blocklist invalid link

### ISSUE THREAD

**Issue by DimitrisKalaboukas** [AdguardTeam/AdguardFilters#139783]
### Prerequisites

- [✓] I am running the latest version
- [✓] I checked the documentation and found no answer
- [✓] I checked to make sure that this issue has not already been filed

### Issue Details

Preinstalled link for Online Malicious URL Blocklist is no longer updating and so this list is stuck on December 14 2022. Please, replace it with a valid one, e.g.:

https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-online.txt

- **AdGuard version:**
  - v3.6.10
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung Galaxy A51
- **Operating system and version:**
  - Android 12
- **Root access:**
  - No

### Expected Behavior

Online Malicious URL Blocklist updates frequently.

### Actual Behavior

Online Malicious URL Blocklist is stuck on December 14 2022.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

Also, you should review all predefined filter lists in order to remove the obsolete ones that are no longer developed or supported.

**Comment by zloyden** [comment]
Not a filter issue, but we aware of this. It's temporary disabled until a server-side fix is released.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersRegistry/commit/751906be1e16c8d696671e80e4e02a58942902f6

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersRegistry/pull/721
