### ISSUE TITLE
nectarsleep.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#139769]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.nectarsleep.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

logs-01.loggly.com

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
I found loggly in an app: https://play.google.com/store/apps/details?id=com.trpz.travel

Its not blocked

**Comment by jordanswrld94** [comment]
@Alex-302

**Comment by Alex-302** [comment]
This is a bug tracking, not analytics.
