### ISSUE TITLE
Fishing sites report

### ISSUE THREAD

**Issue by A9FM** [AdguardTeam/AdguardFilters#139881]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard DNS, AdGuard for Windows

### AdGuard version

latest

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

check comment

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. Report for all fishing sites:
```apps-roblox
roblox.com.af
web.roblox.com.af
www.roblox.com.af
roblox.com.ai
web.roblox.com.as
roblox.ax
asiaroblox.cam
www-roblox.cm
apk-roblox.com
online-roblox.com
rcblox.com
robiox.com
robiox.ru.com
robiox-apps.com
robllox.com
roblox.gr.com
roblox7.com
roblox-app.com
roblox-apps.com
robloxrr.com
robloxs.com
roblox-site.com
rublox.com
sltes-roblox.com
vvv.roblox.com
vvv-roblox.com
vvvvv-robiox.com
vwvw--roblox.com
vwvw-roblox.com
wvv.roblox.com
wvvw-roblox.com
wvvw-web-roblox.com
wvww.roblox.com
wvwwww-roblox.com
wwn-roblox.com
www.roblox-x.com
www-rcblox.com
www-roblax.com
www-robllox.com
www-robloxr.com
www-rublox.com
wwwv.roblox.com
wwwvv.roblox.com
wyw-roblox.com
xn--roblx-3ta.com
robiiox.com.de
robilox.com.de
robliox.com.de
robllox.com.de
roblox.com.do
roblox.com.ee
web.roblox.com.ef
www.roblox.com.ef
roblox.com.et
www.roblox.com.et
www.robiox.eu
roblox.com.gl
web.roblox.com.gl
www.roblox.com.gl
roblox.com.gp
roblox.com.gt
www.roblox.com.gt
roblox.com.hn
roblox.com.ht
www.roblox.com.ht
http-roblox.com
roblox.com.kg
roblox.com.lv
roblox.mk
roblox.com.ms
web.roblox.com.ms
www.roblox.com.ms
roblox.com.mu
roblox.net
site-roblox.net
www-robiox.net
www-roblox.net
robiox.com.nf
roblox.com.nf
www.roblox.com.nf
www.roblox.nf
www-roblox.page
roblox.pm
roblox.com.pr
roblox.qa
www.roblox.com.ro
apps.roblox
robiox.ru
robloox.com.ru
roblox1.ru
www-roblox.com.ru
roblox.com.sb
roblox.com.sc
roblox.sx
roblox.com.tt
www.roblox.com.tt
files.txt
roblox.com.vu
roblox.wf
```
Original site: https://roblox.com

### Privacy

- [X] I agree to follow this condition

**Comment by zPitachu** [comment]
First, 99% of these domains don't work anymore (suspended already). Also, you need to report these links to mail " support@adguard.com", they will block them faster.

**Comment by VladisLoveZh** [comment]
Reviewed and blocked.
