### ISSUE TITLE
[iOS] arstechnica.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1399]
Missed ad on page:
http://arstechnica.com/apple/2016/01/apple-updates-snow-leopard-so-you-can-continue-to-upgrade-from-snow-leopard/#p3

![image](https://cloud.githubusercontent.com/assets/15856304/12642123/74a2230c-c5bc-11e5-812b-e06d0b115f18.png)

WFV-936-12151

**Comment by Alex-302** [comment]
Can't reproduce.
