### ISSUE TITLE
www.rcgroups.com

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#13998]
[https://www.rcgroups.com/forums/showthread.php?1328260-DIY-BiQuad-11dbi-antenna-tutorial!](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.rcgroups.com%2Fforums%2Fshowthread.php%3F1328260-DIY-BiQuad-11dbi-antenna-tutorial%21)

 1 и 3. Вверху страницы и между 1-м и 2-м комментом: `rcgroups.com##table[cellpadding="0"]`

<details><summary>Screenshot's:</summary>

 **1**
![1](https://user-images.githubusercontent.com/17948007/38025125-e952325e-328f-11e8-91d8-3923ae59055b.png)

 **3**
![3](https://user-images.githubusercontent.com/17948007/38025160-fbc86192-328f-11e8-9251-7124651df9ed.png)
</details><br/>

 2. Баннер(ы) в шапке. Идентификатор меняется скриптом: `||rcgroups.net/adjsc.php`

<details><summary>Screenshot's:</summary>

![2a](https://user-images.githubusercontent.com/17948007/38026026-3a54eae0-3293-11e8-818d-4f90c66ba210.png)

![2b](https://user-images.githubusercontent.com/17948007/38026038-480c3a80-3293-11e8-8507-ab03ba9c0e5d.png)
</details>

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.8.5 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
```
||rcgroups.net/adjsc.php
rcgroups.com##a[href^="https://decals.rcgroups.com/adclick.php?bannerid="]
rcgroups.com###posts > div[align="center"]+table[width="100%"][align="center"]
```

**Comment by XX-J** [comment]
<details><summary>Первый не победил...</summary>

![2018 03 30-1](https://user-images.githubusercontent.com/17948007/38131763-eddde6ba-3410-11e8-953e-f25b26e6d42e.png)
</details>

**Comment by Alex-302** [comment]
поправил

**Comment by XX-J** [comment]
Вся полоса является рекламной. Почему-бы не скрыть её полностью?

<details><summary>Screenshot:</summary>

![2018 04 02-1](https://user-images.githubusercontent.com/17948007/38210425-0ff4e530-36c0-11e8-9434-94dbe6b5f882.png)
</details>

**Comment by Alex-302** [comment]
скрыл
