### ISSUE TITLE
Three sites blocked on accident, related to coveryourtracks.eff.org

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#140021]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

trackersimulator.org, eviltracker.net, do-not-tracker.org

### What filters do you have enabled?

AdGuard Tracking Protection filter

### Add your comment and screenshots

1. These three domains are a part of EFF's fingerprinting test, and do not seem to actually track outside of the fingerprinting test
Example: Go to https://coveryourtracks.eff.org and press "Test your browser"

3. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
The reason why they are blocked
https://github.com/AdguardTeam/AdguardForAndroid/issues/249#issuecomment-167509920
