### ISSUE TITLE
Spotify iOS App

### ISSUE THREAD

**Issue by jimmysofat6864** [AdguardTeam/AdguardFilters#140190]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.5

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

Spotify iOS App

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Social Blocking List, Web Annoyances Ultralist, Peter Lowe's Blocklist, Adblock Warning Removal List, Online Malicious URL Blocklist, Fanboy's Enhanced Tracking List, I don't care about cookies, NoCoin Filter List, Dandelion Sprout's Annoyances List, Legitimate URL Shortener

### Add your comment and screenshots

1. advertisements play even when AdGuard dns is enabled

2. Screenshots
<details><summary>Screenshot 1:</summary>

![185B3ED7-957B-4B9B-9FED-24FF321077AD](https://user-images.githubusercontent.com/69532417/212562875-fd8a1e74-eb08-4de2-b99e-03424c688fba.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Tested the spotify app on ipad and cannot reproduce the ads. 
You have enabled too many third party filters that is not recommended. Please try leaving only the AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter.
Then disable-enable content blockers in Safari settings and restart Safari, and check for filters update.
Do not close AdGuard window 30-60 seconds.

**Comment by jellizaveta** [comment]
@jimmysofat6864 Hi! Any news?

**Comment by jimmysofat6864** [comment]
@jellizaveta Hi there even after leaving only those filters enabled I still get ads in the Spotify Application. To reproduce ads leave a song playing for at least 15-30 minutes and eventually an ad will come through either via a pop up or audio ad.

**Comment by jellizaveta** [comment]
Unfortunately, ads cannot be blocked by DNS filtering in this app.
