### ISSUE TITLE
m-code.kr-finance.co.kr

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardFilters#140238]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

http://m-code.kr-finance.co.kr/

### What filters do you have enabled?

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyList, List-KR

### Add your comment and screenshots

This website is a phishing site deceiving as a website of South Korean government.

References:
 - https://www.dogdrip.net/457585031 (Written in Korean language)
 - https://www.ccdailynews.com/news/articleView.html?idxno=2054085 (Written in Korean language)

### Privacy

- [X] I agree to follow this condition

**Comment by VladisLoveZh** [comment]
Reviewed as scam. Blocked
