### ISSUE TITLE
freeopenvpn.org

### ISSUE THREAD

**Issue by PoRtvine** [AdguardTeam/AdguardFilters#14039]
When you push on any link.
Adblock detected.
uBlock Origin 1.15.19
Adguard Base Filters:
/freeopenvpn.org#@#.adsbygoogle:style(position: absolute!important; left: -3000px!important;)/

**Comment by Alex-302** [comment]
not reproduced
![image](https://user-images.githubusercontent.com/8361299/38128181-326a0070-3402-11e8-93d0-31a0be77d11d.png)
