### ISSUE TITLE
[iOS] www.scout.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1404]
Incorrect blocking on page:
http://www.scout.com/college/ohio-state/
So the page doesn't load all the way. You either have to refresh or click the home link to get the page to load fully. 

![image](https://cloud.githubusercontent.com/assets/15856304/12673845/fdc2f71c-c687-11e5-8228-73a0e95c0408.png)
QPV-980-45256

**Comment by Alex-302** [comment]
Pictures are loaded on my end, but with delay(with/without Adguard)
