### ISSUE TITLE
lenta.ru - AdGuard Assistant is missing

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#14059]
***Description***:
* **Current behaviour**: 

AdGuard Assistant's icon is missing when visiting lenta.ru.
The site is not whitelisted in standard / https filter.
AdGuard Assistant has been reinstalled.

* **Expected behaviour**: 

Assistant should be visible on the site.

***Steps to reproduce the problem***:

1. Open the website;
2. Assistant icon is not visible.

***System configuration***

**Filters:**

English, Russian

Information                            | Value
---                                    | ---
Operating system:                      | Windows 7
Browser:                               | Opera Presto (12.18)
AdGuard version:                       | 6.2.437.2171
Filters enabled:                       | English, Russian
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Block 3rd party cookies (30), Block Location API, Remove X-Client-Data header, Hide Search Queries, Send DNT Header
Helpdesk ID (if exists):               | 1801726

**Comment by Alex-302** [comment]
Not reproduced. I can't help with extension.
Please write here: https://github.com/AdguardTeam/AdguardAssistant/issues
