### ISSUE TITLE
businessinsider.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#140686]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.51

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.businessinsider.com/openai-chatgpt-ceo-sam-altman-responds-school-plagiarism-concerns-bans-2023-1

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Anti-Facebook List, Legitimate URL Shortener

### Add your comment and screenshots

Screenshots
<details><summary>Screenshot 1:</summary>

![2023-1-21_17-49-23](https://user-images.githubusercontent.com/29574622/213865712-83e1803f-2a9e-4029-a746-64b812cee7ed.PNG)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Cannot reproduce. @AdguardTeam/filters-maintainers please, take a look

**Comment by zloyden** [comment]
I can reproduce it. Fixed, update should be available in 1-2 hours.
