### ISSUE TITLE
Yahoo Fantasy Sports (iOS)

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#14060]
App: https://itunes.apple.com/us/app/yahoo-fantasy-football-more/id328415391?mt=8

***Description***:
* **Current behaviour**: 

Displays ads.

<details><summary>Screenshot:</summary>

![image2](https://user-images.githubusercontent.com/33634917/38097680-aeb2e5f4-337e-11e8-9f3a-babc41402994.jpg)

</details><br/>

* **Expected behaviour**: 

Should be ad-free.

***Steps to reproduce the problem***:

1. Enable the protection, have DNS enabled and set to AdGuard Default

***System configuration***
**Logs:**
1680807
**Filters:**
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English Filter" Version=2.0.3.59 Enabled=YES
ID=3 Name="Spyware filter" Version=2.0.0.92 Enabled=YES
ID=4 Name="Social media filter" Version=2.0.0.48 Enabled=NO
ID=14 Name="Annoyances filter" Version=2.0.1.90 Enabled=YES
ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.24 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=2.0.0.75 Enabled=YES
ID=12 Name="Safari filter" Version=2.0.0.49 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=2.0.0.60 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=2.0.4.1 Enabled=YES

Information                            | Value
---                                    | ---
Operating system:                      | iOS 11.2.6
Browser:                               | n/a
AdGuard version:                       | 2.0.2.146
Filters enabled:                       | see above
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | Default
Helpdesk ID (if exists):               | 1680807

**Comment by AdamWr** [comment]
Unfortunately I can't reproduce it.

<details><summary>Screenshot</summary>

![yahoo_fantasy](https://user-images.githubusercontent.com/29142494/38258383-9c81af54-3762-11e8-9f0f-deee16b1ff26.jpeg)

</details>
<br>

@Alex-302 Could you please check it too?

**Comment by Alex-302** [comment]
It does not work on my device, even without AdGuard.
