### ISSUE TITLE
All my projects under d3ward.github.io have issues because of this rule 

### ISSUE THREAD

**Issue by d3ward** [AdguardTeam/AdguardFilters#140769]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

2.1.46.59

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://d3ward.github.io/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

I've recently received hundreds of reports from users saying that some of my projects (public and private) no longer work as expected. 
I found out that Adguard updated the annoyances list with a very strange approach related to one of my projects, the adblock test.
Here is the commit of the change: https://github.com/AdguardTeam/AdguardFilters/commit/137b1d9410091d0a675b077d02505ab20a7c0b06

Basically my very simple adblock test https://d3ward.github.io/toolz/adblock.html does a check on the most popular hosts of a couple of categories, this projects works and has helped a lot of users, it works as expected with different DNS solutions, adblock extensions and more. Unfortunately not with Adguard products, though the lists works 
In the past I had a discussion with someone from Adguard team and we agreed that Adguard solutions are different, and somehow the adblock test have false positive because of how Adguard products works, which does not mean that Adguard does not work!
When I use the Adguard lists annoyances with solutions like uBlock Origin, the test adblock works as expected and is not "useless test".

1. I don't see why it was necessary to add a statement like "! useless adblocker test with wrong tests", it feels disrespectful. In fact, I recommend using Adguard in a separate section of the adblock test.
2. Many users have reported that their Adguard product works even though the tool gives wrong results. So it's just a test. In fact, on a screenshot shared there, it shows how the test fails and Adguard works as expected. https://github.com/AdguardTeam/AdguardFilters/issues/138613#issuecomment-1366943050
3. The adblock tool even has a statement saying that some users may have problems, and there is actually a message every time the user does the test "it is a tool to use as a reference to see how efficient your blocking system is (note that with some DNS and browsers there may be problems)". I didn't want to be the one to point out which adblockers or DNS have problems (like the Adguard extension), so instead I opened  discussion with the users and explained to them how things works. As far i know , while solutions like uBlock Origin actually block the connections , with Adguard products the requests are empty and this make the test fail .
4. A rule like `$third-party,domain=d3ward.github.io,important` it's kind of too much, it's block every external api call that start from the domain "d3ward.github.io" , in practice, my main domain is now considered even more annoying than any other ad provider, tracker or otherwise. The rule it's blocking even a simple Github API call I use on my portfolio ->
<img width="577" alt="image" src="https://user-images.githubusercontent.com/39910418/213945378-fe5cd58f-1417-4578-8394-fa4da43ff23a.png">

I would like to see this resolved and perhaps open a discussion on what solution we can work on. I'm happy to provide any information, how the adblock test works, which rule should be used instead, etc. I'm aware that users are using the adblock test and thinking that Adguard is not working, and this is causing some confusion. I'm actually working on updating the test to be more clear and specific for only a set of adblocker solutions 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
I added that rule because you check domains, which are not used for ads(as sources) and for tracking.
* googleadservices.com - just a clicktrough links (for example, context ads in google search, which blocked by element hiding rules)
* amazon domains - for ads used `c.amazon-adsystem.com` Where are used another domains from the test?
* `analytics.facebook.com` - also is not used for tracking, and now it redirects to https://www.facebook.com/business/help/966883707418907
* `advertising.twitter.com` - same as FB
* also not sure about Pinterest domains
* Yandex - `adsdk.yandex.ru`, `extmaps-api.yandex.net` not used for ads. 
	* `an.yandex.ru` - used for ads
	* `mc.yandex.ru`, `mc.yandex.com` - analytics
* Xiaomi, Huawei etc. - domains used by mobole devices, and the rules in regular ad blockers are useless.


By this test you are forcing the filter developers to block domains that should not be blocked.

Also used colors - it the pain for eyes, too contrast.

**Comment by d3ward** [comment]
> I added that rule because you check domains, which are not used for ads(as sources) and for tracking.

This, at least to me, doesn't make too much sense. I don't see the reason to adopt this aggressive rule because of the list of hosts that are redirects/clicktrough. If they are harmless, why block them by blocking everything else?
Although I agree that these hosts are not ads/trackers, so running a test on them is pointless.

> By this test you are forcing the filter developers to block domains that should not be blocked.

 Didn't know I had that power. I still don't understand how I can force developers to block a domain for a simple test. Maybe you mean that users started complaining that Adguard wasn't working or something, but it's somehow not my fault, I explicitly say that the test is just a test and there may be problems. The project is open, I do my best to improve it, and I listen to user feedback.

> Also used colors - it the pain for eyes, too contrast.

Yes, I'm aware of that and have received a lot of feedback about it. The project design is years old and I'm working on an update.

Thanks for the quick and honest reply. I think what we can do there, so that both can benefit, is
- For me to update the list, which I'm already doing, the first 6 you mentioned will be completely removed from the test list on upcoming update. About the OEM ones, I don't think they are useless, a lot of users use them, I'm pretty sure there are popular solutions ( adblock lists, DNS, and others ) that actually block them too, even using Adguard system wide on Android, it works and helps users have a more privacy friendly experience by blocking OEMs specific trackers/ads, but the tests on OEMs hosts are optional, doesn't affect the result.
- I would appreciate it if the added rule was less aggressive. For example, instead of blocking directly on d3ward.github.io, it could be something like d3ward.github.io/toolz or directly d3ward.github.io/toolz/adblock.html if possible. 
- I will continue to recommend Adguard solutions, because despite this issue that confuses some users, Adguard products are among the best solutions. So while I'm working on an update, I could point out before a test that some solutions are not compatible with the test, like the adguard home solution, while other solutions work, like the adguard extension for browsers.

**Comment by d3ward** [comment]
> I added that rule because you check domains, which are not used for ads(as sources) and for tracking.

This, at least to me, doesn't make too much sense. I don't see the reason to adopt this aggressive rule because of the list of hosts that are redirects/clicktrough. If they are harmless, why block them by blocking everything else?
Although I agree that these hosts are not ads/trackers, so running a test on them is pointless.

> By this test you are forcing the filter developers to block domains that should not be blocked.

 Didn't know I had that power. I still don't understand how I can force developers to block a domain for a simple test. Maybe you mean that users started complaining that Adguard wasn't working or something, but it's somehow not my fault, I explicitly say that the test is just a test and there may be problems. The project is open, I do my best to improve it, and I listen to user feedback.

> Also used colors - it the pain for eyes, too contrast.

Yes, I'm aware of that and have received a lot of feedback about it. The project design is years old and I'm working on an update.

Thanks for the quick and honest reply. I think what we can do there, so that both can benefit, is
- For me to update the list, which I'm already doing, the first 6 you mentioned will be completely removed from the test list on upcoming update. About the OEM ones, I don't think they are useless, a lot of users use them, I'm pretty sure there are popular solutions ( adblock lists, DNS, and others ) that actually block them too, even using Adguard system wide on Android, it works and helps users have a more privacy friendly experience by blocking OEMs specific trackers/ads, but the tests on OEMs hosts are optional, doesn't affect the result.
- I would appreciate it if the added rule was less aggressive. For example, instead of blocking directly on d3ward.github.io, it could be something like d3ward.github.io/toolz or directly d3ward.github.io/toolz/adblock.html if possible. 
- I will continue to recommend Adguard solutions, because despite this issue that confuses some users, Adguard products are among the best solutions. So while I'm working on an update, I could point out before a test that some solutions are not compatible with the test, like the adguard home solution, while other solutions work, like the adguard extension for browsers.

**Comment by Alex-302** [comment]
> This, at least to me, doesn't make too much sense.

That rule was added to the filter, disabled by default. But I can remove it. I hope you will change tested domains list to real(used for hosting ads).

> Didn't know I had that power. 

But your tool have:) Many users complain that the test scores are low, and some rules were added to EasyList to block domains from the test.

**Comment by d3ward** [comment]
@Alex-302 Thank you ! 
Meanwhile I have removed the domains that were discussed. Will also keep them removed on the next update of the project.

**Comment by Alex-302** [comment]
Thanks!
