### ISSUE TITLE
Frequent crashes. Autoupdate filters on wifi setting doesn't update them

### ISSUE THREAD

**Issue by Amousey** [AdguardTeam/AdguardFilters#140749]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.4 (990)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

Autoupdate filters on wifi never updates filters

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, EasyPrivacy, Fanboy's Annoyances, Web Annoyances Ultralist, Peter Lowe's Blocklist, Adblock Warning Removal List, Online Malicious URL Blocklist, Fanboy's Anti-Facebook List, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Disable cache for third-party requests

### Add your comment and screenshots

1. Occurred on multiple versions of ios15 and on ios16.2 (latest release). Background refresh for app turned off, although running app on wifi did not update the filters either.

2. Previous date of filter update was Dec 22, 2021, which may have been when app was installed. 

Manual filter update from AdGuardsuccessful.

3. Frequent crashed on ios 15, and ios 16.2 including right after adding a custom safari filter, and after 1-2 mins of browsing existing filters. No errors displayed.

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Issue moved to [AdguardTeam/AdguardForiOS #2115](https://github.com/AdguardTeam/AdguardForiOS/issues/2115) via [**Zenhub**](https://www.zenhub.com/)

**Comment by zloyden** [comment]
@Amousey the issue was moved to another repo. Please be ready to answer there.
