### ISSUE TITLE
Skip chip.de sponsored download

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardFilters#14073]
On chip.de there's a new "feature" where with enabled adblocker you get a choice menu to either

- Watch a "sponsored ad" before getting to the download
- Continuing to the download without watching the ad

I'd like AG to completely skip this step/page and go straight to the download itself.

Example: http://www.chip.de/downloads/c1_downloads_auswahl_38429217.html?t=1522359732&v=3600&s=35882d8c9a19608f473dc2e50c580565

![](https://i.imgur.com/PdDdSnI.png)

**Comment by Alex-302** [comment]
With/without AdGuard

![image](https://user-images.githubusercontent.com/8361299/38194981-a7e55bbe-3683-11e8-962a-c4b3dcba7078.png)

@BlazDT please  take a look.

**Comment by BlazDT** [comment]
Not reproduced, hid an ad after clicking on manual download.
Try enabling Annoyance filter.

**Comment by Bluscream** [comment]
@blazdt i have almost all filters enabled incl. The annoyances one. Gonna get a ticket id witg my logs later
