### ISSUE TITLE
thecompleteuniversityguide.co.uk

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdguardFilters#140741]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

Version 4.0.64

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://www.thecompleteuniversityguide.co.uk/student-advice/what-to-study/top-ten-most-popular-courses-for-international-students`

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

<details><summary>Screenshots:</summary>

[screenshot](https://i.imgur.com/meZndqw.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@chirag127 Which is the correct link?

**Comment by jellizaveta** [comment]
On the hindustantimes.com this block is part of the page functionality.
