### ISSUE TITLE
www.studentenwerk-dresden.de

### ISSUE THREAD

**Issue by samo296** [AdguardTeam/AdguardFilters#140849]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

yes

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.studentenwerk-dresden.de/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1. Site greyed out for cookie selection, cookie selection dialog not visible

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
