### ISSUE TITLE
This isn’t a bug it’s more of a question of an issue

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#140897]
[CE1A54BC-8A96-4EBD-A15C-B39A13993CC0](https://user-images.githubusercontent.com/118444664/214453836-3b719e5b-8da2-4865-8bc5-64c7bac96a54.png)
[0FD073C2-0621-42A2-A1B1-D904434A5127](https://user-images.githubusercontent.com/118444664/214453842-9bb20a21-559d-4423-85fa-d442ef17d07b.png)
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.5

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

flowers

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>
I’m trying to figure this out and I still don’t get it maybe I’m just not smart enough to ever get this but if someone could help me I would appreciate 
2. Screenshots
<details><summary>Screenshot 1:</summary>
![8730D42F-14E6-4A20-BC6B-29C60FF744B1](https://user-images.githubusercontent.com/118444664/214453090-37178966-6308-44af-9f75-c9b259af203e.png)
![09BFB119-E178-4A8B-A2EA-F14106372F02](https://user-images.githubusercontent.com/118444664/214453119-103b2c51-035f-48af-bba5-37b552d4b1e3.png)

![E6C409BE-E7BF-4EAD-978F-6443E79E306A](https://user-images.githubusercontent.com/118444664/214453216-ece62463-f444-4bc1-9de3-a3bd3679957d.jpeg)

So I hid the element of the flower with my adguard app but it also hid the dog element of exactly where the flower element was grid on Google search 

I’m guessing that’s because there’s not a class= 

so only the flower element is hid but nothing else of a different search of where the flower was is also hid?

I don’t get this can someone please help me I don’t know how to find a YouTube video specifically on this or what but I need someone help please!!!

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by malicerainbow** [comment]
![0EA79DE4-A1E3-4D8E-83DC-87B75A1F437E](https://user-images.githubusercontent.com/118444664/214453785-14c9d4c7-063d-4861-833b-bf99b25f16d9.png)
![F7D501A0-A9E5-4E4D-B8E9-40E78B1AE5DD](https://user-images.githubusercontent.com/118444664/214453803-462553d2-441b-4af7-a4a2-37f661e2d12b.png)

**Comment by Alex-302** [comment]
Provide url of the page.

**Comment by malicerainbow** [comment]
![77176848-6E97-4461-B2C8-1237D85334DD](https://user-images.githubusercontent.com/118444664/214698871-e94311b5-9539-492e-b379-21e65b463585.png)
![F7887D53-DBA6-45AD-984B-E24A6E0B83A2](https://user-images.githubusercontent.com/118444664/214698877-69a111b0-6c2d-42b1-b40d-cab065db201f.png)


It doesn’t actually give me a url when I’m doing searches of images on Google that’s all it gives is the item I’m searching
