### ISSUE TITLE
Dead domains that can be removed from list

### ISSUE THREAD

**Issue by mmrabbani** [AdguardTeam/AdguardFilters#140899]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

DNS doesn't have version

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

DNS

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

1. <comment>
Hello

I have checked some parts of Adguard DNS list by Godaddy.com and found that 615 domains have no owner and can be bought. This means that the previous owner of the domains did not renew them. So these domains can be removed from list to make this list lighter (Adguard DNS and any other adguard list).
Lists of dead domains that I found can be downloaded in below:
[adguard dead domains.txt](https://github.com/AdguardTeam/AdguardFilters/files/10494698/adguard.dead.domains.txt)
you can check them yourself on https://www.godaddy.com/domains/bulk-domain-search
If you want, I can check all of the list.

2. Screenshots

![image](https://user-images.githubusercontent.com/56675802/214440583-8c921d48-2180-4508-84ce-be53f70665a9.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. DNS filter is compiled from few sources, including third-party, but dead domains in general is not a big problem for this filter. Later we will clean filters from such domains.
In some cases "dead" domains cannot be removed from AG filters, as the domains are `still` available (for example, sites which change domain every few days).
