### ISSUE TITLE
techspot.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#140846]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.54

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.techspot.com/article/2600-ssd-trimming-explained/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Anti-Facebook List, Legitimate URL Shortener

### Add your comment and screenshots

1. <comment>Looks like an empty ad-placeholder on the mobile version of the site.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![2023-1-24_14-34-9](https://user-images.githubusercontent.com/29574622/214245994-e667e432-8c03-428a-8967-dd5c830f9c9e.PNG)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
