### ISSUE TITLE
silvergames.com [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#14094]
**Site**: https://www.silvergames.com/en/fly-with-rope-2

**Issue**: Please remove the adblock message on the page.

**Screenshot**: http://prntscr.com/iyg0ll

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.181 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
Sorry posted this before reading your comment. You can close this one. Thanks

**Comment by AdamWr** [comment]
Ok :)

I added rules to hide ad leftovers.

**Comment by Nzzyme** [comment]
Thank you
