### ISSUE TITLE
agame.com [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#14091]
**Site**: http://www.agame.com/game/fly-with-rope-2

**Issue**: Please remove the adblock message on the page.

**Screenshot**: http://prntscr.com/iyfy3u

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.181 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by AdamWr** [comment]
Please don't report this game again, it was fixed today and update will be available in 2-3 hours.
This game is in iframe and it is from here - `https://games.softgames.com/games/fly-with-rope-2/gamesites/1665/locale/en`

Please add these rules to user filter and check the result:
```
@@||games.softgames.com/modules/ads-client.last.js
@@||games.softgames.com/assets/showads.js
@@||games.softgames.com/assets/advertisement.js
||games.softgames.com/ads/configs/match?publisher=
```

**Comment by Nzzyme** [comment]
Ok, got it. Thanks for informing. So just adding the above rules will suffice no matter which site it is right?

**Comment by AdamWr** [comment]
Yes, these rules will be work, no matter on which website this game will be embeded.

**Comment by Nzzyme** [comment]
Ok, thanks :)
