### ISSUE TITLE
online.anidub.com

### ISSUE THREAD

**Issue by malomaster** [AdguardTeam/AdguardFilters#141212]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.46.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

online.anidub.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, EasyList, EasyPrivacy, Peter Lowe's Blocklist, Online Malicious URL Blocklist, RU AdList - Counters, Fanboy's Enhanced Tracking List

### Add your comment and screenshots

After enabling/disabling filters, I found that problems with `online.anidub.com` caused by `AdGuard Russian filter` when used by `uBlock Origin` with filters I checked above + 6 built-in uBlock filters.
This issue does NOT appear on root pages: online.anidub.com, online.anidub.com/anime_ongoing, online.anidub.com/anime_tv or online.anidub.com/dorama. It appears only on RELEASES pages (like https://online.anidub.com/anime_ongoing/11560-urusei-yatsura.html)
In uBlock AdGuard Russian filter marked as "external/user filter".

The problem: when `AdGuard Russian filter` enabled, all page content just disappeared, leaving a blank page with AniDub's menu panel at the top of the page.

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
Check without built in "RU AdList" if isn't correctly disabled (RU AdList - Counters is a diffrent list and they can't be added to do not lost power of websites where don't follow file itself to fix blocked ads/trackers in 24 hours after list was updated).

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
