### ISSUE TITLE
Automatic deletion of closed websites/servers

### ISSUE THREAD

**Issue by Bushido1** [AdguardTeam/AdguardFilters#141490]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Filtering and loading websites becomes slower by time if closed websites/servers are still in the filter list(s). The bigger the size of filter file and the longer the filtering list, the slower blocking and/or loading websites.

### Proposed solution

Please delete closed websites/servers automatically from filter lists offered by AdGuard.

### Additional information

For example the Wikipedia has a bot that checks dead links: https://ru.wikipedia.org/wiki/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD:%D0%9D%D0%B5%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%BD%D0%B0%D1%8F_%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D0%B0.

**Comment by DandelionSprout** [comment]
There is https://github.com/funilrys/PyFunceble, though the biggest adblocker lists have traditionally tended to doubt its accuracy for reasons I'm not 100% sure about (I on the other hand trust that tool very strongly when I'm able to get it to run in Cygwin).

**Comment by krystian3w** [comment]
In my oragnization seemingly the biggest problem was reading the expiration date from WHOIS.

Apparently hawkeye reported 1 occurrence of a problem with regional (sub)domains - report seemingly closed as repaired.

Of course, I do not mean when the dates are hidden, for example, eu TLD domains.

**Comment by Alex-302** [comment]
Filter size does not affect filtering performance.
Tens of thousands of generic element hiding rules can affect.
But sure we will remove dead domains.

@DandelionSprout 

> There is https://github.com/funilrys/PyFunceble

I tested it, many false positives. Only one of the tools, the result of which should be checked against the other tools.

**Comment by Bushido1** [comment]
Does generic element hiding rules include cookies and annoying pop-up?

Parimat soovides
Best Regards,
________________________________

**Comment by krystian3w** [comment]
Yes if rule are generic like:

* https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/Cookies/sections/cookies_general.txt

   1497 rules counted by Notepad++ (regex `/^##/`)
   https://github.com/AdguardTeam/AdguardFilters/blob/60f2f78f981ff0b0fbcb1b84886b7ad4ff52f39c/AnnoyancesFilter/Cookies/sections/cookies_general.txt#L9-L1521

* https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/Popups/sections/popups_general.txt

   9 rules counted in same method by "poor regex":

   https://github.com/AdguardTeam/AdguardFilters/blob/8695ee8ef1385fe7bc0769974b4fe8e53737433b/AnnoyancesFilter/Popups/sections/popups_general.txt#L9-L23

**Comment by DandelionSprout** [comment]
>I tested it, many false positives. Only one of the tools, the result of which should be checked against the other tools.

Fair point, I suppose; although I faintly remember it as such that false-dead detections dropped drastically around the spring of 2022, after it began checking against WHOIS databases and such.

>Does generic element hiding rules include cookies and annoying pop-up?

Depends on the list. Ones like *I Don't Care About Cookies* and *AdGuard Annoyances Filter* specialises in that kind of stuff.

**Comment by Bushido1** [comment]
Is it possible to decrease the influence of generic element hiding 
rules file size to the website loading? So that adding such new rules 
and present rules will not affect performance?

**Comment by krystian3w** [comment]
IMO decrease/reduce is not possible without detect as not use something anymore on webpages in origin files.

As you have an idea of cutting out generic rules with something (e.g. `sed` in CLI), you can try to make a list without cosmetic generics and add as an optional list to addons(extensions)/apps what supports it (form hardrive or localhost url to avoid found free servers).

Also possible disable for few minutes use "AdGuard Annoyances"/"AdGuard Cookies"&"AdGuard Pop-ups" but this can gernerate FP e.g. lost network filtering where pages wait for blocked files/request and enough is surrogate from `redirect/`redirect-rule` to speedup problematic page.

As a poor test, you can see if this speeds up site loading on iOS/iPadOS and with the addon/extension for Safari on macOS:

```adb
@@*$ghide,important
```

For AdGuard, **but this also disable whole generic cosmetic rules form "AdGuard Base"** (~98% can be from forking EasyList https://github.com/easylist/easylist/blob/master/easylist/easylist_general_hide.txt = 19k lines vs ~500 generic rules by AdGuard Team in own files) to hide ads/placeholders&leftovers.

Whether this helps the page load faster **remains to be measured**, if the result is not good, then I recommend knocking down the rule.


---

In uBO is implemented option "Ignore generic cosmetic filters" in My Filters tab on Dashoard.

https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#ignore-generic-cosmetic-filters

And is still active for Mobile Phones/Tablets (uBo don't check ARM CPU power or name if possible with pure JavaScript).

In uBo, the above AdGuard syntax rule is incorrect, to avoid bad use in this way:
```adb
!
! https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#not-supported
! aka backdoor @@*$document for entire page exception
!
@@*$all,elemhide,important
!
! to disable use scriptlet as second "rule",
! due uBo don't use "jsinject" to disable scriptlets in network syntax of filters:
!
*#@#+js()
!
```
