### ISSUE TITLE
intellimize.co

### ISSUE THREAD

**Issue by justinhelmer** [AdguardTeam/AdguardFilters#141518]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Hello, I noticed that the adguard-bot [identified](https://github.com/AdguardTeam/AdguardFilters/issues/98907) intellimize.co spyware and added it to the list of [third party tracking servers](https://github.com/AdguardTeam/AdguardFilters/commit/1a7010e7c9362cd40b1bfd2e5f0ce49f4f90639c).

This is not a tracking service, but is a [personalization tool](https://www.intellimize.com/). What is the process for getting an exception?

### Proposed solution

Add all intellimize domains to the whitelist

**Comment by krystian3w** [comment]
> I noticed that the adguard-bot https://github.com/AdguardTeam/AdguardFilters/issues/98907 intellimize.co spyware and added it

AdGuard Bot is not AI to be able to visit a site by itself and detect something (ads, tracking, annoying elements).

> and added it

AdGuard Bot itself does not add, if you check more carefully, Alex-302 of the AdGuard Team approved it as a potential tracker: https://github.com/AdguardTeam/AdguardFilters/commit/1a7010e7c9362cd40b1bfd2e5f0ce49f4f90639c

As the form does not collect IP addresses it is unlikely we will ever know what kind of human reported it (or its own AI bot other than "AdGuard Bot").

---

To prove how simple is that "AdGuard Bot" you can use form report all broken pages:

https://github.com/AdguardTeam/AdguardFilters#report-issues

https://agrd.io/report

Only possible in that form add own github nickname:

 \> ![image](https://user-images.githubusercontent.com/35370833/215709460-0cb5c24d-7dd9-448e-9279-2f45a4ed5c7c.png)  | like in https://github.com/AdguardTeam/AdguardFilters/issues/141539
--- | ---


is not same like https://webcompat.com/ report form where possible use account to publish intead as anonymus simple bot ([webcompat-bot](https://github.com/webcompat-bot) - Mozilla Bot).

**Comment by Alex-302** [comment]
Changed to `||log.intellimize.co^`

**Comment by justinhelmer** [comment]
@Alex-302 - Appreciate the update; that being said, the `log.intellimize.co` domain is also part of the base product functionality. This domain is where events are sent, not for the purpose of user tracking or advertising, but for the purpose of personalization. If this URL is blocked, the main product breaks for websites that use the product.

Can we remove all intellimize domains?

Much appreciated.

**Comment by krystian3w** [comment]
You can exterminate own servers aka sabotage - good luck.
