### ISSUE TITLE
tinder

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#141535]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.tinder

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

![Screenshot_20230131_011129_AdGuard](https://user-images.githubusercontent.com/118186787/215692487-2e6ca779-d329-4d62-893f-2d41b7f48294.jpg)

||dlsdk.appsflyer.com^
![Screenshot_20230131_012311_AdGuard](https://user-images.githubusercontent.com/118186787/215693321-e3572244-04df-4323-bd6f-f9634be9bd78.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
||dlsdk.appsflyer.com^

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
