### ISSUE TITLE
solarmovie.cr

### ISSUE THREAD

**Issue by gedw99** [AdguardTeam/AdguardFilters#141633]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.5 (990)

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www2.solarmovie.cr/stream/winnie-the-pooh-blood-and-honey-53143/

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. <comment>

2. Screenshots

![Stream Winnie the Pooh Blood and Honey (2023) Free On SolarMovie](https://user-images.githubusercontent.com/53147028/215890588-ca64545e-94bc-4b2d-a752-dec186660de4.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. It seems this is a fake player.
Does it work on your end?
