### ISSUE TITLE
Google invaild search result

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardFilters#141681]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

Many websites

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, List-KR

### Add your comment and screenshots

In Google search result with a Korean language query, there are some spam websites that its domain is changed frequently.

It seems that importing the following rules is best idea.

```adblock
/^https:\/\/[A-z0-9\.]*[A-z0-9]+\.[A-z]+\/\?u=[A-z0-9]{7}&o=[A-z0-9]{7}/$document
/^https:\/\/[A-z]+\.[A-z]+\.[A-z]+\/[A-z]+-robot\/\?pl=[A-z0-9-]{22}&sm=[A-z]+-robot&hash=[A-z0-9-]{22}&exp=[0-9]{10}/$document
/^https:\/\/[0-9]{9}\.[A-z0-9-]+\.[A-z]{2}\/[0-9]{6}\.html$/$document
```

Related issues:
 - https://github.com/List-KR/List-KR/issues/598
 - https://github.com/AdguardTeam/AdguardFilters/issues/139667

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Do you want them in Base filter?
I'd prefer to test them un user filter some time.

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/141681#issuecomment-1421246478

Hmm... I wanted to add them into AdGuard Browsing Security database.
However, @mapx- said that adding into a language-specific filter is better if the issue is language-specific.

**Comment by Yuki2718** [comment]
I assume now `/^https:\/\/[A-z0-9\.]*[A-z0-9]+\.[A-z]+\/\?u=[A-z0-9]{7}&o=[A-z0-9]{7}/$document` part is mostly addressed by https://github.com/AdguardTeam/AdguardFilters/commit/372525846a2193efaf589752097fe1da170e4d4b - except the adopted regex uses lookahead `(?!www)`. It's just a safety measure to avoid potential FP and may possibly be removed. @Alex-302 How do you think?

**Comment by Alex-302** [comment]
I don't like common regexpes, so at least it should have more specfic regex part)

@piquark6046 What do you think?

**Comment by piquark6046** [comment]
For performance reason, a filter maintainer avoids to commonly add a regexp rule.
However, if it is necessary for many internet users, I think that it is worth adding it unless It occurs a ReDoS event.

To verify that a regexp rule does not occur a ReDoS event, I develop [List-KR/check-regex](https://github.com/List-KR/check-regex) slowly.

**Comment by piquark6046** [comment]
Or, expand feature of AdGuard Browsing Security module to support a regexp rule.
@ameshkov

**Comment by Yuki2718** [comment]
regex101 shows the number of steps to evaluate. I have learned how to reduce it, and there are some rules of thumb e.g. avoid greedy expression such as .* if possible. But you have to evaluate not only match case, but also unmatch and near-match cases - actually most of requests won't match.

**Comment by Alex-302** [comment]
So what? It seems current rule covers this case. Right?

**Comment by Yuki2718** [comment]
We argue Content Blocker.

**Comment by Yuki2718** [comment]
Will this work?`
/^https?:\/\/[0-9a-z]*\.?[-0-9a-z][-0-9a-z][-0-9a-z][-0-9a-z]+\.[a-z][a-z]+\/([0-9a-z][0-9a-z][0-9a-z][0-9a-z][0-9a-z][0-9a-z]+\/)?\/?\?[ou]=[0-9a-z][0-9a-z][0-9a-z][0-9a-z][0-9a-z][0-9a-z][0-9a-z]&[ou]=[0-9a-z][0-9a-z][0-9a-z][0-9a-z][0-9a-z][0-9a-z][0-9a-z]/$document,match-case`

**Comment by Alex-302** [comment]
It seems it blocks
`https://itthis.f9dle.skin/?u=na8k605&o=a1tm57q&t=new_ip&cid=2b795g0ljktr2`
`document` is resundant for Safari. 
CB for Android can't block the main frame.

**Comment by Yuki2718** [comment]
Okay they abuse www. too: [dangerous site] `http://www[.]winner-time-a2d[.]top/?u=1nup806&o=0wywy2l&t=LPk3Mix&cid=2rad3eu3livl71`

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/3aa844c3e8de4397d2e015af1d7d14c5788ee5fe
