### ISSUE TITLE
two-movies.net [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#14177]
**Site**: https://two-movies.net/watch_movie/Terrifier_2017

**Issue**: Please remove the fake links on the page.

**Screenshot**: http://prntscr.com/iz6g5x

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.181 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
Why was this site added to blacklist?

http://prntscr.com/j23uct

**Comment by Alex-302** [comment]
I don't know. You can send message to support.
