### ISSUE TITLE
space.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#141754]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.space.com/green-comet-tail-c2022-e3-ztf-photo-miguel-claro

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Anti-Facebook List, Legitimate URL Shortener

### Add your comment and screenshots

Scroll down a bit if it doesn't appear at first. 

Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/29574622/216302561-5b0b8c4b-e37c-4af3-87ab-1735c1bd2e0f.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
