### ISSUE TITLE
americanexpress.com

### ISSUE THREAD

**Issue by Aakarshak1** [AdguardTeam/AdguardFilters#141784]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.9.2.1234

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.americanexpress.com/en-in

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals

### Add your comment and screenshots

1. When adguard enabled site doesn't load. when disabled site loads perfectly

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
americanexpress.com is in HTTPS exclusions. Did you remove it?

**Comment by Aakarshak1** [comment]
No, I just checked its present there

**Comment by Aakarshak1** [comment]
http://www.paytmmoney.com/ also not loading

**Comment by BlazDT** [comment]
Please try to disable DNS protection.

**Comment by Alex-302** [comment]
@Aakarshak1 Please check which module breaks the site - filters, stealth mode or DNS filtering.
