### ISSUE TITLE
[iOS] adiamor.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1417]
http://www.adiamor.com/Engagement-Rings/Search/Solitaire
"If you try to select a filter for a diamond the wheel keeps spinning as if it's "searching"...forever. If you disable the filter the wheel only spins for a few seconds"
ZHB-678-63449

**Comment by Alex-302** [comment]
Maybe their server is not fast? It loads without/with Adguard near 5-10 secs.
