### ISSUE TITLE
shareus.in

### ISSUE THREAD

**Issue by iSmokeMid69** [AdguardTeam/AdguardFilters#141829]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard for Android

### AdGuard version

*

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

https://shareus.in/?i=7oYZVW

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter

### What Stealth Mode options do you have enabled?

Hide your search queries

### Add your comment and screenshots

1. <comment>
It Ask To Complete Task Or Answer Questions (Right Or Wrong Doesn't Matter)
Can It Be ByPassed Or Remove Those Annoying Things
2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
I don't understand what do you want to block. Please make screenshots.

**Comment by Alex-302** [comment]
No. It has no visitors.
