### ISSUE TITLE
Popups filter breaks twitter scrolling

### ISSUE THREAD

**Issue by Omoeba** [AdguardTeam/AdguardFilters#141866]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.5

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://twitter.com/xbox

### What filters do you have enabled?

AdGuard Popups filter

### Add your comment and screenshots

1. <comment>The popup is successfully blocked but the page can no longer scroll. Note the lack of a scroll bar in the first screenshot. The second screenshot is the same page with the Popups filter disabled.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![22CBAE1F-5F8A-4175-A221-F84561891DEF](https://user-images.githubusercontent.com/38597972/216682392-71128662-dd85-4086-a446-f7843637d667.jpeg)

</details>

<details><summary>Screenshot 2:</summary>

![C656A5D0-7E51-4774-8BC4-63C0E3E27E15](https://user-images.githubusercontent.com/38597972/216683206-f1b73bd2-07fb-493a-830c-abcfc9ba344b.jpeg)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
I couldn't reproduce this popup, but I was able to reproduce a different popup which also block scrolling.
I have added a rule which probably will fix this issue, filters update should be available in 1-2 hours.
Please update filters after about 2 hours (please do not close AdGuard app until process of updating filters will be finished) and then check if issue still occurs.
