### ISSUE TITLE
Get rid of legacy Extended CSS syntax

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#141938]
### Steps:
1. Check if the site is existing
2. If the site is dead - remove all rules for this site
3. If working - check for applied `[-ext-` rules and remove unused rules or convert to the actual syntax, if a rule applied.

This task is only about extcss, so the detailed check is optional (you can create a separate list with missed ads and process it in another task).

**Comment by BlazDT** [comment]
Finished German filter yesterday.
