### ISSUE TITLE
guitartab.player - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#1419]
https://play.google.com/store/apps/details?id=guitartab.player&hl=en
![screenshot_2016-01-30-19-08-20](https://cloud.githubusercontent.com/assets/5947035/12704803/05bb7a78-c874-11e5-8dc4-8dd8ea4bda6c.png)

**Comment by Alex-302** [comment]
There is only googleads.g.doubleclick.net on my end. It is blocked.

**Comment by ameshkov** [comment]
The issue was originally reported on 4pda, could you please answer there?

**Comment by Alex-302** [comment]
yes
