### ISSUE TITLE
CNet/RedVenture properties now advertorial?!

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardFilters#142031]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

According to [reporting](https://www.theverge.com/2023/2/2/23582046/cnet-red-ventures-ai-seo-advertisers-changed-reviews-editorial-independence-affiliate-marketing), CNet & other [RedVenture properties](https://www.redventures.com/about/brands#logoGrid) are being turned into advertorial sites via [biased AI](https://www.theverge.com/2023/1/19/23562966/cnet-ai-written-stories-red-ventures-seo-marketing) & corporate pressure.

### Proposed solution

To be determined?   I wanted to bring up the info to let the AG team decide what to do.

**Comment by Alex-302** [comment]
We definitely will not block the site)

**Comment by TPS** [comment]
Ok, but what's the right approach for an ad blocker on such advertorial sites?

**Comment by Alex-302** [comment]
@TPS Most of reviews are ads (Brand representatives often provide items for reviews). Paid reviews is not a reason to block whole sites.
