### ISSUE TITLE
Visual rules suggestion

### ISSUE THREAD

**Issue by LambLeeg** [AdguardTeam/AdguardFilters#142023]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

I have found a couple of sites where articles have visual gaps (blocked ads), and there are no CSS filtering made for those. Also, a set of rules to make Reddit mobile site workable. I use these rules myself, and tested them with Adguard and uBlock Origin extensions.

### Proposed solution

! introvertdear

introvertdear.com###AdThrive_Content_1_phone
introvertdear.com###AdThrive_Content_2_phone
introvertdear.com###AdThrive_Content_3_phone
introvertdear.com###AdThrive_Content_4_phone
introvertdear.com###AdThrive_Content_5_phone
introvertdear.com###AdThrive_Content_6_phone
introvertdear.com###AdThrive_Content_7_phone
introvertdear.com###AdThrive_Content_8_phone
introvertdear.com###AdThrive_Content_9_phone
introvertdear.com###AdThrive_Content_10_phone
introvertdear.com###AdThrive_Content_11_phone
introvertdear.com###AdThrive_Below_Post_1_phone

introvertdear.com###AdThrive_Header_1_desktop
introvertdear.com###AdThrive_Content_1_desktop
introvertdear.com###AdThrive_Content_2_desktop
introvertdear.com###AdThrive_Content_3_desktop
introvertdear.com###AdThrive_Content_4_desktop
introvertdear.com###AdThrive_Content_5_desktop
introvertdear.com###AdThrive_Content_6_desktop
introvertdear.com###AdThrive_Content_7_desktop
introvertdear.com###AdThrive_Content_8_desktop
introvertdear.com###AdThrive_Content_9_desktop
introvertdear.com###AdThrive_Content_10_desktop
introvertdear.com###AdThrive_Content_11_desktop
introvertdear.com###AdThrive_Below_Post_1_desktop

introvertdear.com##.has-background.has-text-color.has-theme-palette-1-color.top-bar-callout.has-text-align-center

! Reddit mobile

reddit.com##.XPromoBlockingModalRpl__overlay.m-animated
reddit.com##.XPromoBlockingModalRpl__content.m-animated
reddit.com##.XPromoPopupRpl__overlay.m-animated
reddit.com##.XPromoPopupRpl__content.m-animated

reddit.com##xpromo-app-selector
reddit.com##body.scroll-is-blocked:style(overflow: visible!important; position: static!important;)
reddit.com##+js(aeld, touchmove)

! Reddit

reddit.com##.XPromoPopupRpl
reddit.com##xpromo-new-app-selector
reddit.com##.bottom-bar, .XPromoBottomBar
reddit.com##.useApp,.TopNav__promoButton
reddit.com##body:style(pointer-events:auto!important;)

reddit.com##.XPromoPopup
reddit.com##body.scroll-disabled:style(overflow: visible!important; position: static!important;)
reddit.com##.XPromoInFeed
amp.reddit.com##.AppSelectorModal__body
amp.reddit.com##.upsell_banner

reddit.com##._3MknXZVbkWU8JL9XGlzASi

! The Verge

theverge.com##.flex.relative.flex-col.px-10.mb-60.w-full.max-w-container-lg.md\:mx-auto.md\:max-w-\[560px\].lg\:flex-row.lg\:pr-0.lg\:mx-auto.lg\:max-w-container-lg.home-hero > .mx-auto.block.md\:hidden
youtube.com##.flex.relative.flex-col.px-10.mb-60.w-full.max-w-container-lg.md\:mx-auto.md\:max-w-\[560px\].lg\:flex-row.lg\:pr-0.lg\:mx-auto.lg\:max-w-container-lg.home-hero > .mx-auto.block.md\:hidden

**Comment by DandelionSprout** [comment]
For `introvertdear.com`, compressing the 24 entries to `introvertdear.com##[id^=AdThrive_]` could presumably be considered.

For Reddit, I know a select few (but not all) of those entries are covered by *AdGuard Popups Filter*, *Dandelion Sprout's Annoyances List*, and possibly *AdGuard Mobile App Banners Filter*.

**Comment by Alex-302** [comment]
Please report the sites with ads or leftovers using `Report the issue` button (recommended) or `Bug report` template.
