### ISSUE TITLE
I don’t understand your document and I even am learning HTML and CSS

### ISSUE THREAD

**Issue by malicerainbow** [AdguardTeam/AdguardFilters#142188]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.5

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://adguard.com/kb/general/ad-filtering/create-own-filters/#introduction

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>
I don’t understand this document maybe I’m just too stupid but I don’t understand it at all. I’m even trying to understand html and css and hope that helps me to understand but I still don’t understand your filters 

Can someone please recommended a video or something that discuss these rules

I don’t even know what to look up I tried aduard filters but it all it gave was a 1 minute video of what filters are. 

I need something that exactly will step by step teach me what all these symbols you guys use to make custom rule filters mean

I have tried reading the document multiple times and I still don’t understand it, 

Please what exactly are these are these same rules any adblocker uses? Or are they only ones you use? 

What do I look for exactly for instance there are courses on html 

And courses on csss

So what do I call this so I can find a course?

I have learned div, <button> header head body <ul> <li> <nav> <h1> <a href= </a>

I have learned specifying

<button class=“flower”>click me</button>

Csss      Class. ID . * . Ancestor and child 

.flower {property:value; }

.flower {background-color:red; color:blue; font-size;100px}

but I still don’t understand your document 

please will someone help me I am actually trying to learn this my self so I don’t always have to bother you all!!!

 
2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
Adblockers' official syntax guides are known to be windy, to say it the least. [This page](https://github.com/DandelionSprout/adfilt/blob/master/Wiki/SyntaxMeaningsThatAreActuallyHumanReadable.md) (Disclosure: I'm the maintainer of that page) should hopefully make it a bit easier.
