### ISSUE TITLE
[iOS] washingtonpost.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1422]
https://www.washingtonpost.com/national/10-seismic-changes-since-911/2013/09/10/4499cf18-19b4-11e3-82ef-a059e54c49d0_gallery.html
MBC-535-68560

It's https website, though.

**Comment by Alex-302** [comment]
Browser extensions can filter HTTPS sites.
Please try this rule
```
washingtonpost.com##div[moat-id="ad/leaderboard"]
```

**Comment by Alex-302** [comment]
added. If it helps - close this issue
