### ISSUE TITLE
clickdoc.fr

### ISSUE THREAD

**Issue by 0o5rlubm** [AdguardTeam/AdguardFilters#142358]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

x

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://clickdoc.fr/cd-fr/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

scrolling is blocked on https://clickdoc.fr/cd-fr/ 

I've fixed same on easylist/easylist#14929, but i don't know where to fix it here.

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.

**Comment by zloyden** [comment]
> but i don't know where to fix it here

Next time you can open a pull request [here](https://github.com/AdguardTeam/AdguardFilters/pulls).

**Comment by 0o5rlubm** [comment]
thanks, i would have been unable to do the rule you've written :-)
