### ISSUE TITLE
Add guildeducation.com domain to Optimizely 

### ISSUE THREAD

**Issue by dariawhitecastle** [AdguardTeam/AdguardFilters#142370]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

If users have the AdGuard enabled in their adblocking extensions, then they cannot load our feature flags and a/b tests. The effect is different across our product, such as missing new functionality, new styles, or new versions of existing capabilities. This is especially problematic when we expect all users of a customer to have access to a capability they have paid for.

Here are the websites we are having trouble with

`https://*.guildeducation.com`
`https://optimizely.guildeducation.com/*`
`https://*.guildeducation.com/optimizelydatafile=*`
`https://cdn.optimizely.com/datafiles/* with referrer from https://*.guildeducation.com`

### Proposed solution

Adding `guildeducation.com` to the AllowedList of domains for Optimizely .

### Additional information

Our company’s product, offered through [guildeducation.com](http://guildeducation.com/) does not serve any types of ads or ad-related materials. We are an education benefit provider, helping connect our users to debt-free education. We do use Optimizely for product management best practices of testing new offerings for our users.

**Comment by Alex-302** [comment]
Need steps to reproduce, enabled filters, and probably a test account with steps to reproduce(you can send it to filters@adguard.com).

**Comment by krystian3w** [comment]
Refferer can blocked due generic:

https://github.com/AdguardTeam/AdguardFilters/blob/ce7838cdabcd20ddf8fd03348b90c5440950cc9c/SpywareFilter/sections/tracking_servers.txt#L2935
