### ISSUE TITLE
wi-fi.ru - unable to pass the authorisation

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#14242]
> Здравствуйте! Не могу зарегистрироваться в московском метро - просто не грузит сайт ( 
> В бесплатной версии хватало добавления сайтов метро в белый список, а тут не сработало ( в логах, я так понимаю, вы все увидите - добавил 2 сайта в антитрекинг и белый список. Отключение программы помогает.

> logs: https://uploads.adguard.com/lcrep.zip
> Единственное, сейчас я не могу войти в сеть пригородных электричек, но природа проблемы одна и та же, как я понимаю.  Время - с 6.25 по 6.28 я пытался зарегистрироваться в сети.

Information                            | Value
---                                    | ---
Operating system:                      | iOS
Operating system version (Android/iOS) | 11.3
Browser:                               | Safari
AdGuard version:                       | 2.0.2.146
Filters enabled:                       | 1 2 3 4 11 12
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | Default 
Helpdesk ID (if exists):               | 1814537

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Заблокированных доменов не вижу. Пусть попробует с выключенными фильтрами. Но вообще этот сайт исключен, проблем быть не должно.

**Comment by dokdotexe** [comment]
Это мой тикет проблемы. Я сегодня пробовал отключать 2 фильтра - для сафари, для мобильной рекламы. После каждого отключения пробовал заново логиниться-не вышло. Не могу понять где косяк. Но ведь при отключении программы все работает !

**Comment by Alex-302** [comment]
А полное отключение фильтров помогает?
И что вы видите на экране? Без скриншота не совсем понятно, о чём речь. Наверное, пока нет авторизации, доступ к DNS отсутствует.

**Comment by dokdotexe** [comment]
Полное отключение не пробовал. На экране - просто прогресс бар загрузки сайта в сафари доходит до четверти экрана и все. Через некоторое время - что-то в духе «страница не загружена». Через пару часов буду в метро - проверю ещё раз. 
Смутно помню, что утром выбрал днс не «AdGuard стандартный», а системный днс и все завелось. Но при таком раскладе, если не ошибаюсь, я прихожу к функционалу бесплатной версии программы...

**Comment by Alex-302** [comment]
Попробуйте с выключенным DNS, не включая фильтры.

**Comment by dokdotexe** [comment]
Как только включён режим «системный днс» - все работает и с включёнными фильтрами. Тоже самое и при передёргивании ползунка «статус»

**Comment by Alex-302** [comment]
Значит, предположение выше верно
> Наверное, пока нет авторизации, доступ к DNS отсутствует.

Попробуйте переключить режим туннеля с Full на Split. Должно заработать.

**Comment by dokdotexe** [comment]
Да, это решило вопрос! Как бы лишняя иконка (впн) в верхнем баре мозолит глаза, но хоть инет в метро есть. 
Спасибо !
