### ISSUE TITLE
cbsnews.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#142478]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.cbsnews.com/live/video/20230210052207-beloved-composer-burt-bacharach-dies-at-94/#x

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

Cant figure out why live videos or normal videos dont play

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.

**Comment by jordanswrld94** [comment]
Still doesnt work. Sorry

**Comment by jordanswrld94** [comment]
Its weird it works on firefox browser on pc but not edge. And for mobile it doesnt work at all

**Comment by jordanswrld94** [comment]
@AdamWr that worked perfect

**Comment by jordanswrld94** [comment]
Can we remove tealium.cbsnews.com from dns filter list. I think that needs to be whitelisted in order for videos to play

**Comment by jordanswrld94** [comment]
Other than that it works great now

**Comment by AdamWr** [comment]
>Can we remove tealium.cbsnews.com from dns filter list. I think that needs to be whitelisted in order for videos to play

Okay, I have removed this rule.
