### ISSUE TITLE
n.fcd.su

### ISSUE THREAD

**Issue by iSmokeMid69** [AdguardTeam/AdguardFilters#142546]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

*

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

https://n.fcd.su/MJn/ygra

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

First There is Notification Allowed Check(Disable It)
Then Popup On Skip Ad Button
Then oxy.cloud(popup) On Download Button

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Okay, fixed.
Filters update should be available in 1-2 hours.
