### ISSUE TITLE
Player at hdserials.tv & online.anidub.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1425]
http://www.hdserials.tv/Filmy/Voennye/Besslavnye-ublyudki-/-Konchenye-mrazi.html
если убрать английский и русский фильтр включается реклама и можно пропустить ее
http://prntscr.com/9x4rzu
со всеми фильтрами
http://prntscr.com/9x4sxp

http://online.anidub.com/anime_tv/anime_ongoing/9604-vrata-tam-byutsya-nashi-voiny-tv-2-gate-jieitai-kanochi-nite-kaku-tatakaeri-tv-2-01-iz-12.html
http://prntscr.com/9x54ah

KRN-342-40196 & PFR-388-21069

**Comment by Alex-302** [comment]
@Bohdan-SUP 
проверь плиз
```
#%#Object.defineProperty(window, 'iframe_adv_enabled', { get: function() { return false; } });
```
