### ISSUE TITLE
mobile.donanimhaber.com 

### ISSUE THREAD

**Issue by unununium1232** [AdguardTeam/AdguardFilters#142512]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

V3.6.11

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

mobile.donanimhaber.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals

### Add your comment and screenshots

1. <comment>
Happens on samsung internet
An obstacle appeared on the bottom of the screen
2. Screenshots
<details><summary>Screenshot 1:</summary>
![Screenshot_20230210_144045_Samsung Internet](https://user-images.githubusercontent.com/73962085/218085165-79dd6103-1156-4436-9720-c6a8ac400c13.jpg)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/142513
