### ISSUE TITLE
Missed ads at patriotupdate.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1426]
http://patriotupdate.com/if-democrats-dont-heed-this-warning-well-definitely-get-a-republican-president/
"Sponsored content" to the right
![screen shot 2016-02-01 at 2 30 32 am](https://cloud.githubusercontent.com/assets/14153331/12706366/f053ae36-c88b-11e5-936a-718b4177c810.png)
XXM-298-90538

**Comment by evgeniy-ADG** [comment]
@Alex-302 кастомер ругается :(

**Comment by Alex-302** [comment]
@evgeniy-ADG 
мутно как-то сделали. Сейчас ещё попробую. Какой у него Адгард?

**Comment by evgeniy-ADG** [comment]
@Alex-302 30 января был   "AppVersion": "6.0.146.791"

**Comment by Alex-302** [comment]
@evgeniy-ADG 
передай пока временное решение, для пользовательского фильтра. Объясни, что там очень хитро реализована реклама.
Как сделаем нормальный вариант - отпишу.
```
||patriotupdate.com/?*=*&_=
patriotupdate.com$$script[tag-content="MBoxAdMain"][max-length="20000"]  
```

**Comment by evgeniy-ADG** [comment]
ok

**Comment by evgeniy-ADG** [comment]
это все в одну строку или это два правила?

**Comment by Alex-302** [comment]
два

**Comment by Alex-302** [comment]
@evgeniy-ADG 
вроде одолел
проверь плиз такие правила:
```
patriotupdate.com#%#Object.defineProperty(window, 'zp', { get: function() { return {}; } }); 
patriotupdate.com#%#Object.defineProperty(Object.prototype, 'adbladeExports', { get: function() { return {}; } }); 
```
должны пропасть два блока под статьёй и один справа сверху

**Comment by Alex-302** [comment]
правила уже доступны для обновления. Если всё ок - закрывай.

**Comment by Alex-302** [comment]
Реклама не лезет. Юзер может удалять правила и проверить обновление фильтров.

**Comment by evgeniy-ADG** [comment]
It's back: http://patriotupdate.com/democrats-dirty-electoral-college-trick-exposed-in-recount-scam/

![image](https://cloud.githubusercontent.com/assets/15856304/20858522/2389e784-b94f-11e6-86d9-3af95c0fcbb0.png)


<details>

![image](https://cloud.githubusercontent.com/assets/15856304/20858526/36d47016-b94f-11e6-93e2-7521c900ba3d.png)

**Comment by Alex-302** [comment]
can't reproduce. That ads are blocked by
```
patriotupdate.com#%#Object.defineProperty(window, 'zp', { get: function() { return {}; } });
patriotupdate.com#%#Object.defineProperty(Object.prototype, 'adbladeExports', { get: function() { return {}; } });
```
