### ISSUE TITLE
bing.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#142774]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.bing.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Anti-Facebook List, Legitimate URL Shortener

### Add your comment and screenshots

1. <comment>Clicking on search result doesn't work and also click to show previous search results are also not appearing. Blocked by rule "||bing.com/fd/ls/"
2. Added a GIF file

3. Screenshots
<details><summary>Screenshot 1:</summary>

![b](https://user-images.githubusercontent.com/29574622/218407508-9fbc5573-eb4f-44b9-b3f9-d271fa76dd94.gif)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by SeriousHoax** [comment]
@AdamWr @zloyden @Sergey-Lyapin @jellizaveta @Alex-302 
Tagging you guys just in case so that it's fixed faster since an issue with Bing is rather urgent I think.

**Comment by AdamWr** [comment]
Unfortunately, I cannot reproduce it.
Does it work correctly if you add this rule:
```adblock
@@||bing.com/fd/ls/
```
to user rules?

**Comment by SeriousHoax** [comment]
> Unfortunately, I cannot reproduce it. Does it work correctly if you add this rule:
> 
> ```
> @@||bing.com/fd/ls/
> ```
> 
> to user rules?

Sorry about it. Looks like not an issue of Adguard. Only working in Edge + Private mode for me. But for some reason not working in Firefox in either mode and not even in a fresh Chrome portable version in either mode. Don't know what's the problem.

**Comment by AdamWr** [comment]
Okay, so I guess that it might be a website issue, though I cannot reproduce it.
