### ISSUE TITLE
forums.overclockers.ru

### ISSUE THREAD

**Issue by HanabishiRecca** [AdguardTeam/AdguardFilters#14278]
**Сайт:** https://forums.overclockers.ru/
**Проблема:** работает антиблокировщик
![image](https://user-images.githubusercontent.com/13597663/38280091-e12cfb22-37bc-11e8-889e-e0c829ce84f3.png)

Сайт производит проверку на ошибку при загрузке рекламного скрипта "rotor.overclockers.ru/www/delivery/asyncjs.php"

![image](https://user-images.githubusercontent.com/13597663/38280136-29843d40-37bd-11e8-8ea0-e07dfb4e6097.png)

Сам скрипт блокируется правилом из Английского фильтра
![image](https://user-images.githubusercontent.com/13597663/38280264-e3adcede-37bd-11e8-850e-cbff03531eba.png)

Для себя решил проблему через пользовательское правило, директива empty помогает:
||rotor.overclockers.ru^$empty

**Comment by Alex-302** [comment]
Вечером исправлено было. Проверьте обновление фильтров.

**Comment by Alex-302** [comment]
Поправил.
