### ISSUE TITLE
misskey.io

### ISSUE THREAD

**Issue by SKEIDs** [AdguardTeam/AdguardFilters#142720]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

ver 4.1.53

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://misskey.io/@kureharu_stk
https://misskey.io/tags/%E6%B0%97%E3%81%8C%E7%8B%82%E3%81%A3%E3%81%9F%E3%81%A8%E3%81%8D%E3%81%AB%E6%8A%BC%E3%81%99%E3%83%9C%E3%82%BF%E3%83%B3
https://misskey.io/@itiradi/pages/1557466961730

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Japanese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

I tried with #142719 but I could not completely hide ad.

  <details><summary>screenshots</summary>

![](https://i.slow.pics/lnAE14RG.png)
![](https://i.slow.pics/l0Zsts36.png)
![](https://i.ibb.co/2t1JLWt/image.png)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by SKEIDs** [comment]
Excuse me, all ads are back.

**Comment by Yuki2718** [comment]
Now json-prune is working without breakage, not sure if something has changed or it was my misdiagnosis (didn't have enough time at the moment). I'll bring back the rule but will keep cosmetic too.
