### ISSUE TITLE
youtube.com: URL tracking

### ISSUE THREAD

**Issue by MasterKia** [AdguardTeam/AdguardFilters#142820]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

.

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://www.youtube.com/watch?v=pAZWv8QQ8Co`

### What filters do you have enabled?

AdGuard URL Tracking filter

### Add your comment and screenshots

YouTube's description links have tracking parameters.

Example:
`https://www.youtube.com/watch?v=pAZWv8QQ8Co`

In the description:
`https://www.youtube.com/redirect?event=video_description&redir_token=[...]&q=https%3A%2F%2Fwww.paypal.me%2Fpaysyfr&v=pAZWv8QQ8Co`

`event`, `redir_token`, `q` being the destination link and `v` being the video id.

Proposed filters for AdGuard URL Tracking Protection:
```adb
||youtube.com/redirect?$removeparam=event
||youtube.com/redirect?$removeparam=redir_token
||youtube.com/redirect?$removeparam=v
```

Result link:
`https://www.youtube.com/redirect?q=https%3A%2F%2Fwww.paypal.me%2Fpaysyfr`

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
Maybe good for only My Filters Tab or User Rules (`.../pages/options.html#user-filter`) tab/Filter (apps may have list named as Filter - similar to legacy interface of ABP) due links will always ask to confirm redirect.

**Comment by krystian3w** [comment]
Worse if every day people start complaining and "you" have to paste them a link to the solution:

> - disable Filter "URL tracking"
> or
> - add this to AdGuard's own rules / my filters in uBO: 
> ```adb
> ||youtube.com/redirect?$removeparam=event,badfilter
> ||youtube.com/redirect?$removeparam=redir_token,badfilter
> ||youtube.com/redirect?$removeparam=v,badfilter
> ```

These clicker can be used in scams:

```adb
[path="/redirect?q="]www.youtube.com#%#//scriptlet('trusted-click-element', '#invalid-token-redirect-goto-site-button', '', '500')
```

**Comment by krystian3w** [comment]
But for a while the link will be automatically clicked in someone.

Maintaining in regex a list of domains where clicking looks OK may not be possible (especially when the line exceeds the limit of allowed characters per filter e.g. 65 kilibytes).

**Comment by AdamWr** [comment]
I'm not sure if these rules should be added as it causes that there is necessary to confirm redirection.
There was issue about confirming redirection (caused by `$cookie` rule) here - https://github.com/AdguardTeam/AdguardFilters/issues/128041#issuecomment-1229174825 and related comment - https://github.com/AdguardTeam/AdguardFilters/issues/128041#issuecomment-1237773494 (and comments below).
So I guess that it's not user friendly and there will be similar reports.

@Alex-302 Could you please take a look at this issue when you come back from vacation?

**Comment by Alex-302** [comment]
> I'm not sure if these rules should be added as it causes that there is necessary to confirm redirection.

This is annoying behavior. The rule is for user filter only.

**Comment by Alex-302** [comment]
You **will** be tracked by Google in any case.
