### ISSUE TITLE
www.520xingyun.com

### ISSUE THREAD

**Issue by KIL011** [AdguardTeam/AdguardFilters#142867]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Missed AD

### Proposed solution

add ||www.520xingyun.com^ to filters

**Comment by Sergey-Lyapin** [comment]
Hello @KIL011

As I understand it you just want to block ads on this site?

**Comment by Sergey-Lyapin** [comment]
Unfortunately, the reported issue does not satisfy our [filters policy](https://kb.adguard.com/en/general/adguard-filter-policy).

This site has too little traffic.

Please add to user rules: ||520xingyun.com/images/*.gif

**Comment by KIL011** [comment]
Sure. Thanks.
