### ISSUE TITLE
[NSFW] Many big ad placeholders in group of porn sites (US + DE)

### ISSUE THREAD

**Issue by garry-ut99** [AdguardTeam/AdguardFilters#142873]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

1.46.1rc0

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.pornohirsch.net/

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, EasyList, EasyList Germany, EasyPrivacy

### Add your comment and screenshots

1. https://github.com/easylist/easylist/issues/14954#issuecomment-1427779014
 https://github.com/easylist/easylistgermany/issues/250#issuecomment-1428437004
https://github.com/AdguardTeam/AdguardFilters/issues/81081

A reason why to hide at least the bottom big ad placeholder is already provided: "annoying, taking space", thus it should be fixed, otherwise a counter-argumentation why not to fix it should be provided, "no because no"/ "ignoring" is insufficient explanation.

3. Screenshots
<details><summary>Screenshot 1:</summary>

![](https://user-images.githubusercontent.com/72945564/218305818-e29c9bb9-7f0d-4e5e-ad2d-d148356e8a2a.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by garry-ut99** [comment]
The websites are popular enought, most of them have between several hundrends thousands and several millions of monthly visitors, the ads have been fixed already in the past: https://github.com/AdguardTeam/AdguardFilters/issues/81081, it's time to fix these annoying ad placeholders.

**Comment by Alex-302** [comment]
0 of these sites reported by visitors. It seems users open them by mistake or by unwanted redirects/ads.

**Comment by garry-ut99** [comment]
7 out of 20  were already reported to AG tracker by visitors and fixed in the past:
- https://github.com/AdguardTeam/AdguardFilters/issues/122000
- https://github.com/AdguardTeam/AdguardFilters/issues/72877
- https://github.com/AdguardTeam/AdguardFilters/issues/72878
- https://github.com/AdguardTeam/AdguardFilters/issues/68290
- https://github.com/AdguardTeam/AdguardFilters/issues/60116
- https://github.com/AdguardTeam/AdguardFilters/issues/60114
- https://github.com/AdguardTeam/AdguardFilters/issues/22370


Also stats of example website looks ok: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/220129393-b9720e57-cacb-4cfc-8fe7-7d18980acc4e.png)
