### ISSUE TITLE
www.torrentmac.net executing suspicious script loading CPU 

### ISSUE THREAD

**Issue by temis2k16** [AdguardTeam/AdguardFilters#142874]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.9.2.1234 release

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Firefox, Chrome, Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

www.torrentmac.net

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Annoyances filter, AdGuard DNS filter, Filter unblocking search ads and self-promotion

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

1. Suspicious script which loads cpu is executed

2. Screenshots

<details><summary>Screenshot 1:</summary>

<img width="1693" alt="1" src="https://user-images.githubusercontent.com/22080834/218734535-e35610f9-6082-41a0-a3e7-6dc552d3f161.png">

</details>

<details><summary>Screenshot 2:</summary>

<img width="1687" alt="2" src="https://user-images.githubusercontent.com/22080834/218734714-97819dca-f40f-4330-9ae4-2830a4530ea2.png">

</details>

When surfing the site or trying to download a torrent file suspicious js script executes and load cpu. May be some kind of hidden mining. AdGuard doesn't block it. Looks like disabling AdGuard protection makes it even worse.

Adding `www.torrentmac.net$$script[tag-content="split"]` or `www.torrentmac.net#%#//scriptlet("abort-current-inline-script", "String.fromCharCode")` to user rules seems to resolve the problem.

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
I couldn't reproduce high CPU usage, but I have added rules which I hope will fix this issue.
Filters update should be available in 1-2 hours.
