### ISSUE TITLE
hs.fi videos not playing

### ISSUE THREAD

**Issue by teepeevee** [AdguardTeam/AdguardFilters#142900]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.46.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome, Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.hs.fi/politiikka/art-2000009392084.html

### What filters do you have enabled?

AdGuard Social Media filter, AdGuard Annoyances filter, EasyList, Fanboy's Annoyances, Fanboy's Social Blocking List, Peter Lowe's Blocklist

### Add your comment and screenshots

1. <comment>
Videos in hs.fi don't play if I've AdGuard Annoyances on, if I disable it videos play ok.

OS/version: macOS 13.2.1
Browser/version: MS Edge 110.0.1587.41 and Chrome 110.0.5481.96 
Adblock Extension/version: uBlock Origin 1.46.0

2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="686" alt="Screenshot 2023-02-14 at 18 00 04" src="https://user-images.githubusercontent.com/42848481/218796189-d163743a-0c1e-484b-a114-d685632186ec.png">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
