### ISSUE TITLE
duden.de adblock check

### ISSUE THREAD

**Issue by Hello-olleH** [AdguardTeam/AdguardFilters#143162]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.9.2.1234

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

duden.de

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard German filter

### Add your comment and screenshots

with uBlock and these 3 Objekts I can block duden.de 

! https://github.com/uBlockOrigin/uAssets/issues/16430
!#if !env_mobile
~mentor.duden.de,duden.de##+js(aeld, DOMContentLoaded, isMobile)
!#endif
||duden.de/aab/assets/js/

https://ublockorigin.github.io/uAssets/filters/quick-fixes.txt

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
It's related to this issue - https://github.com/AdguardTeam/AdguardFilters/issues/128224#issuecomment-1229272586 (AdBlock paywall) and this - https://github.com/AdguardTeam/AdguardFilters/issues/131060

<hr>

It seems that there is working solution - https://github.com/AdguardTeam/AdguardFilters/issues/128224#issuecomment-1423819817

Please add this rule:
```adblock
||duden.de/aab
```
to user rules.

**Comment by Hello-olleH** [comment]
@AdamWr 
For what reason is this not added in AdGuard Germany as default?

**Comment by AdamWr** [comment]
The reason is provided here - https://github.com/AdguardTeam/AdguardFilters/issues/131060 and here - https://forum.adguard.com/index.php?threads/policy-on-adblock-walls.26022/

Also related discussion - https://github.com/AdguardTeam/AdguardFilters/issues/139070#issuecomment-1370069762
