### ISSUE TITLE
trinixy.ru

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#14312]
***Description***:
* **Current behaviour**: 

Videos hosted at the site do not load when AdGuard is enabled.

<details><summary>Screenshot:</summary>

![2](https://user-images.githubusercontent.com/33634917/38307932-1b76d81e-381e-11e8-9098-5659193e6c9a.jpg)
![default](https://user-images.githubusercontent.com/33634917/38307933-1b9b197c-381e-11e8-847a-494989a303a7.jpg)
</details><br/>

* **Expected behaviour**: 

AdGuard shouldn't make the video player unresponsive.

***Steps to reproduce the problem***:

1. Enable protection
2. Open site and attempt to open a video

***System configuration***

**Filters:**

English, Russian, Latvian

Information                            | Value
---                                    | ---
Operating system:                      | Windows 7 SP1, Driver: TDI
Browser:                               | Firefox_latest
AdGuard version:                       | 6.2.437.2171
Filters enabled:                       | English, Russian, Latvian
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Block 3rd-party cookies (30m), Remove X-Client-Data, Hide Search Queries, Send DNT Header
Helpdesk ID (if exists):               | 1648150

**Comment by Alex-302** [comment]
Не повторяется. Что ломает?

**Comment by akmLaVx** [comment]
Сказал кастомеру поотключать все фильтры и поврубать по очереди.

**Comment by BlazDT** [comment]
Not reproduced on http://trinixy.ru/159073-mgnovennaya-karma-nastigla-narushitelya-pdd.html

@akmLaVx 
Any news from the client?
