### ISSUE TITLE
s.weibo.com

### ISSUE THREAD

**Issue by 821938089** [AdguardTeam/AdguardFilters#143164]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://s.weibo.com/weibo?q=%E5%8E%9F%E7%A5%9E&topic_ad=

### What filters do you have enabled?

AdGuard Chinese filter

### Add your comment and screenshots

1. Sound should not appear after ad blocking

2. Video (Turn on the volume)
<details><summary>Video 1:</summary>

https://user-images.githubusercontent.com/8674809/219679089-0793cbb8-666e-438c-a0fd-2f8cc0449d2f.mp4

</details>

### Privacy

- [x] I agree to follow this condition

**Comment by Alex-302** [comment]
@821938089 Hi. Is something block video player? I can't access to this site.

**Comment by 821938089** [comment]
@Alex-302 

This video is an advertisement. When I enable AdGuard the video disappears but the sound is still playing.
As far as I can see AdGuard just adds `display: none !important;` to the ad element, without actually removing the element, causing the sound to still be played.
![2023-02-21 231231](https://user-images.githubusercontent.com/8674809/220383596-3a8dc360-3816-4e63-b141-f9f023ba0d7f.png)
![2023-02-21 231901](https://user-images.githubusercontent.com/8674809/220385233-c8c234e7-c5a4-4c20-8bae-2e77a0fa8f8b.png)

**Comment by Alex-302** [comment]
@821938089 Great. Could you please record a HAR file with disabled caching? I will try to make a safe rule. Please send it + link of this issue it to `filters@adguard.com`
How to get a HAR file:
https://toolbox.googleapps.com/apps/har_analyzer/

**Comment by 821938089** [comment]
@Alex-302 

The email has been sent, please check it.

**Comment by Alex-302** [comment]
Hmm. It seems f.video.weibocdn.com is like youtube's CDN. Which rule hides that ad? Can be checked in the filtering log (by search for `card-wrap`)
For me, it does not look like ad - probably related to content. Or not?

**Comment by 821938089** [comment]
No, this is an advertisement.
The Chinese word for "广告" in English means advertisement.

Rule:
`weibo.com#?#.card-wrap:-abp-has(>.card-top>.s-fr:-abp-contains(广告))`

![2023-02-22 164722](https://user-images.githubusercontent.com/8674809/220568885-b1472069-871e-413a-8a69-e4f51da13d10.png)

**Comment by Alex-302** [comment]
Please test 
`weibo.com#$?#.card-wrap:has(>.card-top>.s-fr:contains(广告)) { remove: true; }`

**Comment by 821938089** [comment]
I tried this rule and it worked fine and now there is no sound.
