### ISSUE TITLE
Can't drag&drop links from IE 11 to EmEditor app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1432]
1- http://go4up.com/dl/70582543642f/ltlpshpsprgusdsxpa_opg.rar 
2- IE 
3- Avast 
4- After enabling Adguard, I can't drag and drop the blue links in this page (IE browser). But when Adguard disabled, Its possible. Please show me a solution. Thanks

The customer uses this app: http://www.emeditor.com/download/
When the customer turns Adguard off, drag and drop works fine: https://vid.me/9Y2v
Adguard RC2 didn't help. Logs are here: RFA-830-82698

**Comment by Alex-302** [comment]
I can drag this buttons to notepad and get urls

**Comment by rayman3003** [comment]
notepad doesn't even support drag and dropping. How u do that?
I use another text editor named emeditor. but have this problem.

**Comment by Alex-302** [comment]
I'm using Akelpad

**Comment by rayman3003** [comment]
With the new version (final 6.0), It seems I don't have this problem.
