### ISSUE TITLE
joe.co.uk

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#143386]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.54

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.joe.co.uk/sport/unai-emery-slams-emi-martinez-after-arsenal-defeat-378620

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Anti-Facebook List, Legitimate URL Shortener

### Add your comment and screenshots

Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/29574622/219961656-a8e25911-c80f-4f91-b75a-31fe09f4b4e6.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by THEtomaso** [comment]
There's also an unsolved GDPR issue with those Joe sites (`joe.co.uk` and `joe.ie`), which was reported all the way back in 2019 here:
https://github.com/ryanbr/fanboy-adblock/issues/1274#issuecomment-568313211
