### ISSUE TITLE
Block Phishing sites

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#143440]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

other (specify in comment below)

Brave 1.48.167

### Which device do you use?

Desktop

### Where is the problem encountered?

`taylormadesells[.]com`

### What filters do you have enabled?

AdGuard Base filter, AdGuard Japanese filter

### Add your comment and screenshots

1. `taylormadesells[.]com` and `withaaglad[.]top` are phishing, pls block.

VT results for `taylormadesells[.]com`: 9/91 `https://www.virustotal.com/gui/url/3458a9ccebfcdd7705dff899495b7dc42aa814343ad061d043aa7cdb326fa42e`

for `withaaglad[.]top`: 0/90 `https://www.virustotal.com/gui/url/87babe2da879b6cec5825d849d5e30068b641e9b5a1905ea0392f5f9b1ec01d3/details`

The real site they're trying to disguise is `https://www.taylormadegolf.jp/` (NOT phishing, do not block this).

3. Screenshots
<details><summary>Screenshot 1:</summary>

![phish1](https://user-images.githubusercontent.com/58900598/220075450-64b833c1-8f84-40a9-9faa-649731477eae.png)

</details>

<details><summary>Screenshot 2:</summary>

![phish2](https://user-images.githubusercontent.com/58900598/220075505-63efe502-7d6f-45a0-af7d-57a8d56b00ef.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by enakr** [comment]
Added to Phishing and Scam lists and blocked. Thank you!
