### ISSUE TITLE
ADWALL

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#143403]
### What product do you use?

AdGuard for Android, AdGuard for iOS

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Chrome, Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://m.bild.de/adblockwall.html

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Dutch filter, AdGuard German filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter

### Add your comment and screenshots

![FB9079A0-1936-4DF2-BCE2-41944A87AF9E](https://user-images.githubusercontent.com/125828160/219970878-750890a2-1004-4a47-89a3-e94d9ecdd2e7.jpeg)

Please fix it

**Comment by BlazDT** [comment]
Adblock detection paywall, also since you deleted your account close.
