### ISSUE TITLE
Block scam dating sites

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#143447]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

coup-ling.net, coup-ling-dm.net, gokinjolove.jp, gokinjolove.net

### What filters do you have enabled?

AdGuard Base filter, AdGuard Japanese filter

### Add your comment and screenshots

1. All scam dating sites, pls block. Some details:
`coup-ling.net, coup-ling-dm.net`: `https://sakuradot.com/article/62901.html`, `https://onijima.jp/?p=71023`
`gokinjolove.jp, gokinjolove.net`: `https://deaisamurai.com/point/gokinjolove-jp/`, `https://onijima.jp/?p=77436`

3. Screenshots
<details><summary>Screenshot 1:</summary>

![dating](https://user-images.githubusercontent.com/58900598/220097401-3b2bac6b-23d5-48d0-bb71-0ec366ff18fd.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
For the `coup-ling` ones, there seem to be grounds for a `61.121.245.*$network` block, though it's hard to tell 100.0% sure.

For `gokinjolove.net`, it seems imfeasible to do an IP block unless at least the top 30 domains at https://securitytrails.com/list/ip/150.95.59.19 are all scams.

**Comment by Yuki2718** [comment]
I'd say using wildcard with `$network` is risky, unless you have a solid evidence that all the subnet is for scam.

**Comment by DandelionSprout** [comment]
The other domains I can find for that wildcard match doesn't exactly seem trustworthy either. (Source: `https://bgp.he.net/net/61.121.240.0/20#_dns`)
![image](https://user-images.githubusercontent.com/22780683/220338472-a4dbd5b6-483e-4c1b-9a43-f65cfed18e9c.png)

**Comment by Yuki2718** [comment]
Why closed?

**Comment by Alex-302** [comment]
Will be processed in internal chat. [Oniqqqq](https://github.com/Oniqqqq) can't check just now.

**Comment by enakr** [comment]
Added to Phishing list and blocked.

**Comment by Yuki2718** [comment]
@enakr Can you also block these in https://github.com/AdguardTeam/AdguardFilters/issues/143447#issuecomment-1438352020 please? All from the same actor, only excluded closed sites.
```
a-new86.com
ane102.net
honey8.love
honey888.love
ima55notice.biz
infozoomplus.biz
koi2ru.com
likechat33.net
likechat33call.net
pair55.net
pair55call.net
room2021.net
roomoshirase.net
smore91.net
som419.net
touchoshirase.net
touchtacchi.net
wsws1234.net
wswsnews.net
```

**Comment by enakr** [comment]
Also added to the blocklist. Thank you!
