### ISSUE TITLE
Include adservers_firstparty.txt in AdGuard DNS Filter

### ISSUE THREAD

**Issue by kitadai31** [AdguardTeam/AdguardFilters#143532]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Hello.

Japanese Filter's [adservers_firstparty.txt](https://github.com/AdguardTeam/AdguardFilters/blob/master/JapaneseFilter/sections/adservers_firstparty.txt) is not included in AdGuard DNS Filter.
Therefore, some domains that should be blocked are not being blocked in AdGuard DNS.

By merging adservers.txt and adservers_firstparty.txt, AdGuard DNS users can block more ads.

<details>
<summary>example 1</summary>

###  The left image uses only AdGuard DNS DoH. The right image applies adservers_firstparty.txt using uBO My Filters.

https://dictionary.goo.ne.jp/ - `adcdn.goo.ne.jp` and `yads.yjtag.yahoo.co.jp`

![goo-dictonary](https://user-images.githubusercontent.com/90122968/220101951-e5efc379-c506-4a1e-bed9-68a1ff63dee9.png)
</details>

<details>
<summary>example 2</summary>

https://www.inter-edu.com/forum/read.php?2,4874690 - `ad.inter-edu.com`

![inter-edu](https://user-images.githubusercontent.com/90122968/220102103-6a33f286-b8cf-4c0c-9e1b-11d000c07c6d.png)
</details>

<details>
<summary>example 3</summary>

http://blog.livedoor.jp/itsoku/ - `hbb.afl.rakuten.co.jp`

![itsokuhou](https://user-images.githubusercontent.com/90122968/220102325-fd9698d2-a1fc-4051-a188-b42198bd6758.png)
</details>

--

In addition, some third-party domains are mixed in with the adservers_firstparty.txt, so I think that the two files are not well distinguished.

```
These domains are ad delivery service Ninja AdMax.
- ||asumi.shinobi.jp^
- ||adf.shinobi.jp^
- ||bar*.shinobi.jp^$third-party

This domain is ad platform Adingo.
- ||adingo.jp.eimg.jp^

This is ad platform Supership ScaleOut.
- ||socdm.com^

These are Yahoo Japan ad network
- ||yads.yahoo.co.jp^
- ||yads.yjtag.yahoo.co.jp^

This is Rakuten Affiliate.
- ||hbb.afl.rakuten.co.jp^$third-party
```

(This is the reason why I suggested merging.)

### Proposed solution

Merge two files, adservers.txt and adservers_firstparty.txt.

Or, adding adservers_firstparty.txt to  [AdGuardSDNSFilter/configuration.json](https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/configuration.json) will also solve the problem.

**Comment by Yuki2718** [comment]
Oversight on https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/configuration.json ?

**Comment by kitadai31** [comment]
Yes.
Since https://github.com/AdguardTeam/AdguardFilters/commit/cca113a1790b5fd3c64b1cec1c0ffec6b8df900f .

**Comment by Yuki2718** [comment]
Maybe leave only
```
||mbadv.nan.co.jp^
||creative.live.tktube.com^
||ad.inter-edu.com^
```
and move the rest back to adservers.txt. `||counter2.blog.livedoor.com^` should be moved to TPF, I'll do. OTOH `||ad.eloan.co.jp^` can be moved to firstparty.txt, maybe `||ad.abema.io^` too. There may be more.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #1236](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1236) via [**Zenhub**](https://www.zenhub.com/)

**Comment by Yuki2718** [comment]
> In addition, some third-party domains are mixed in with the adservers_firstparty.txt, so I think that the two files are not well distinguished.

This still needs to be fixed. I'll do.
