### ISSUE TITLE
Блокируется плеер, вместо блокировки преролла.

### ISSUE THREAD

**Issue by d4mler** [AdguardTeam/AdguardFilters#143570]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://doramushka.online/3776-kazino-2-sezon.html

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

При просмотре дорамы не блокируются прероллы. Блокируется весь плеер, вместо блокировки рекламы, из-за чего последующий просмотр дорамы является недоступным.

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Не повторяется. Нужно включить русский фильтр, проверить обновление фильтров, затем очистить данные браузера и открыть сайт.
