### ISSUE TITLE
4pda.ru

### ISSUE THREAD

**Issue by HanabishiRecca** [AdguardTeam/AdguardFilters#14369]
Сайт: http://4pda.ru/
Проблема: пропущенная реклама

![image](https://user-images.githubusercontent.com/13597663/38363227-51971416-38ed-11e8-8f8f-ece4ef06c29e.png)

Верхняя плашка появляется не всегда, только когда в качестве рекламы используется картинка с самого сайта (не third-party контент). Плюс там в стилях !important и стандартные правила скрытия не работают. Потому в принципе помогает вот такое правило:
`||4pda.ru#$#a[attach_id] { height: 0; overflow: hidden; }`

Переадресация при клике по странице тоже убирается
`||4pda.ru#$#.visual>a[target] { transform: scale(0); }`

Что делать с фоном без понятия, там все !important. Механизма для записи прямо в style элемента у вас не нашел.

**Comment by Alex-302** [comment]
Скрывать можно с помощью расширенного CSS, но проблема в том, что они моментально выходят из-под блокировки. 
Подождём пока.
