### ISSUE TITLE
Baidu input application download blocked

### ISSUE THREAD

**Issue by MkQtS** [AdguardTeam/AdguardFilters#143769]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

AdGuard Home v0.107.25

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://shurufa.baidu.com/

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

Baidu hosted their input application on `speedxbu.baidu.com` (see the download link `https://speedxbu.baidu.com/shurufa/ime/setup/BaiduPinyinSetup_5.9.2.1.exe` on `https://shurufa.baidu.com/`).

It is blocked by `||sp*.baidu.com^` from:

https://github.com/AdguardTeam/AdguardFilters/blob/31f3aa413e8aa5d2bfbe0eff271571ee54b70ad5/SpywareFilter/sections/tracking_servers_firstparty.txt#L79

Baidu input is not a Spyware ~~yet~~

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available today or at least tomorrow.
