### ISSUE TITLE
[iOS] kat.cr 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1439]
https://kat.cr/tmnt-teenage-mutant-ninja-turtles-2003-complete-series-t10013624.html
![image](https://cloud.githubusercontent.com/assets/15856304/12720943/ed9b5732-c905-11e5-83e8-e4d3ebde991d.png)
Attaching the screen shot. I've also had a couple of pop ups on the Kat.cr
website - saying I won a prize or something along those lines.

This is using the safari browser on iOS 9.2.1.
UFJ-438-92653

**Comment by Alex-302** [comment]
@evgeniy-ADG 
it is clean on my end. Could you please check it on your side?

**Comment by evgeniy-ADG** [comment]
@Bohdan-SUP kindly check
