### ISSUE TITLE
Weather.gov

### ISSUE THREAD

**Issue by mplynch90** [AdguardTeam/AdguardFilters#144130]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0.543

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://water.weather.gov/ahps2/hydrograph.php?wfo=dmx&gage=cedi4&prob_type=stage

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. With Adguard enabled, the graph doesn't load and the website doesn't look fully functional. This is only recently. 

3. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot_20230226-220130_Chrome](https://user-images.githubusercontent.com/39807553/221472180-bfe30474-6ad2-41b9-be4e-fa07ee37a981.jpg)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by mplynch90** [comment]
![Screenshot_20230226-221435_Chrome](https://user-images.githubusercontent.com/39807553/221473154-772fb065-55e7-48a4-91b4-879778530280.jpg)

Without filters, website works correctly

**Comment by Alex-302** [comment]
@mplynch90 Hi. Cannot reproduce. Which filter breaks?

**Comment by mplynch90** [comment]
Hi, I cannot tell which filter breaks, I don't have any custom filters (to my knowledge) on my phone.  I tried doing a report through the App, but it made me use Git Hub due to the link, and I might not have done the report correctly. This is more information about my setup.

[cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20230227-062017_AdGuard_jpg_1677500546664][cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20230227-061952_AdGuard_jpg_1677500584309][cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20230227-061727_AdGuard_jpg_1677500602918][cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20230227-061746_AdGuard_jpg_1677500614085][cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20230227-061807_AdGuard_jpg_1677500622738][cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20230227-061815_AdGuard_jpg_1677500630863][cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20230227-061839_AdGuard_jpg_1677500639240][cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20230227-061845_AdGuard_jpg_1677500645947][cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20230227-061906_AdGuard_jpg_1677500652971]


Sent from my U.S.Cellular© Smartphone



-------- Original message --------
From: Alex ***@***.***>
Date: 2/27/23 05:26 (GMT-06:00)
To: AdguardTeam/AdguardFilters ***@***.***>
Cc: mplynch90 ***@***.***>, Mention ***@***.***>
Subject: Re: [AdguardTeam/AdguardFilters] Weather.gov (Issue #144130)


@mplynch90<https://github.com/mplynch90> Hi. Cannot reproduce. Which filter breaks?

**Comment by Alex-302** [comment]
@mplynch90 Please reply on GitHub. You screenshots are unavailable.

**Comment by mplynch90** [comment]
![20230228_075439](https://user-images.githubusercontent.com/39807553/221874775-9f190beb-8e79-4df4-b65f-c0d9acef1678.jpg)
![Screenshot_20230227-061952_AdGuard](https://user-images.githubusercontent.com/39807553/221874785-740689fd-3d14-41c0-9607-c2217658f423.jpg)
![Screenshot_20230227-061906_AdGuard](https://user-images.githubusercontent.com/39807553/221874787-23f5df2c-4a66-43ba-acc1-74a78c9b22d7.jpg)
![Screenshot_20230227-061845_AdGuard](https://user-images.githubusercontent.com/39807553/221874793-06ba65ba-515f-4847-acd9-d3b95161850c.jpg)
![Screenshot_20230227-061839_AdGuard](https://user-images.githubusercontent.com/39807553/221874800-95a607bf-6099-4a32-a150-d8c025a6b3f9.jpg)
![Screenshot_20230227-061815_AdGuard](https://user-images.githubusercontent.com/39807553/221874806-5ed29e48-c630-47ae-9c57-9b7bf456a579.jpg)
![Screenshot_20230227-061807_AdGuard](https://user-images.githubusercontent.com/39807553/221874810-d64e1892-ce21-4f2e-bc6c-8a43465d96e6.jpg)
![Screenshot_20230227-061746_AdGuard](https://user-images.githubusercontent.com/39807553/221874815-55510465-8893-4f47-b462-f3d14d1a6a34.jpg)
![Screenshot_20230227-061727_AdGuard](https://user-images.githubusercontent.com/39807553/221874822-788a5ecd-d6cc-45ad-81dc-2c0e43185972.jpg)

**Comment by Alex-302** [comment]
Please backup your settings, disable all filters, stealth mode, dns filtering and check again.
If the site will loads fine, enable disabled options one by one.
