### ISSUE TITLE
douploads.com [Fake Link]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#14427]
**Site**: https://douploads.com/atzogva40j44

**Issue**: Please remove the fake button on the page after entering the captcha.

**Screenshot**: http://prntscr.com/j1vgcu

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.181 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by Nzzyme** [comment]
Seeing fake download links on Android. Can you please check?

https://douploads.com/dsi570wb4yz1

Screenshot: https://postimg.cc/QF9cBdBy

**Comment by Alex-302** [comment]
Not reproduced
![image](https://user-images.githubusercontent.com/8361299/47556898-1a63f100-d918-11e8-93ba-ad44d3f3b84c.png)

**Comment by Nzzyme** [comment]
Confirmed on Android. Cleared browsing history, cache, etc. and disabled add-ons. Disabled all user filters and then opened this page to see fake links. Please check.

https://douploads.com/7r501idt3x2t

**Comment by Alex-302** [comment]
Not reproduced.

**Comment by Nzzyme** [comment]
Seeing again when using AG for Chrome on Windows 7

@BlazDT @AdamWr : Please check

http://prntscr.com/lpp1ao

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 70.0.3538.110 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
Nothing
![image](https://user-images.githubusercontent.com/8361299/49446898-d8af4b80-f7dd-11e8-8e3a-aaddbd4a7fba.png)

**Comment by Nzzyme** [comment]
They have changed the layout. Unable to download from the genuine download link on Android. 

Link: https://douploads.com/g0kdcquv6hhm

-Cookie Notice
-Incorrect blocking I suppose as I am unable to download from the good link.

Please fix.

**Comment by Alex-302** [comment]
> Unable to download from the genuine download link on Android

it seems it is not caused by AdGuard. I don't see checkbox without AdGuard.

**Comment by Nzzyme** [comment]
I reported to the webmaster of douploads.com and they fixed that issue. However, seeing an adblock message now. Please fix on Android.

https://douploads.com/orsplfc81pew
