### ISSUE TITLE
hdzog.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#14438]
**Site**: https://www.hdzog.com/videos/311805/best-pornstar-in-incredible-blonde-blowjob-sex-clip/?promo=10306

**Issue**: Please remove the ads on the page.

**Screenshot**: http://prntscr.com/j1xkb9

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.181 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by Nzzyme** [comment]
Pop-up seen when clicking on Play button

https://hdzog.com/videos/41453/rebeca-linares-ryan-driller-in-latina-dultery/?promo=21446

**Comment by BlazDT** [comment]
Not reproduced, please check @AdamWr

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
