### ISSUE TITLE
usatoday.com now detecting AdGuard ad blocking and throwing up a warning/block screen

### ISSUE THREAD

**Issue by jameyers4** [AdguardTeam/AdguardFilters#144331]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.11

### Environment

```markdown
- OS:Monterey 12.6.3
- Safari version: 16.3 (17614.4.6.11.6, 17614)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

Steps to reproduce:
1. navigate to usatoday.com
2. observe warning / notification screen regarding ad-blocking (and that it must be disabled to view site)
3.

### Expected Behavior

I expect to be able to read / view usatoday.com website

### Actual Behavior

I get a warning screen about ad-blocker and cannot proceed to read or view website

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="1598" alt="Screen Shot 2023-02-24 at 3 20 03 AM" src="https://user-images.githubusercontent.com/30449337/221128408-bbeec322-7f62-4ddb-9534-e28959855648.png">

**Comment by Alex-302** [comment]
Please enable `Tracking Protection Filter` or `AdGuard Popups filter`

**Comment by jameyers4** [comment]
The are both enabled.  I’m puzzled by the fact that I see Rules built Feb 14 - should this be updated by now?  (Pic attached)




Jeff Meyers
***@***.***




On Mar 3, 2023, at 9:24 AM, Alex ***@***.***> wrote:


Closed #144331 <https://github.com/AdguardTeam/AdguardFilters/issues/144331> as completed.

**Comment by Alex-302** [comment]
@jameyers4 Hi. Please reply on GitHub. We don't see attachments.



> I see Rules built Feb 14

No, filters are obsolete. Checking for manual filter updates doesn't help?

**Comment by jameyers4** [comment]
Sorry - not seeing for the life of me how do manually check for filter update.  Please advise.  

![IMG_2296](https://user-images.githubusercontent.com/30449337/222761392-6026bde1-e289-4ad6-9fa1-ecc43f67b990.PNG)

**Comment by jameyers4** [comment]
Got it - thanks
