### ISSUE TITLE
Adblock Detection : www.rockmods.net

### ISSUE THREAD

**Issue by AdishSagarawat** [AdguardTeam/AdguardFilters#144401]
When using Adguard DNS as Private DNS on android, not able to access www.rockmods.net.

Screenshot:
![Screenshot_20230302-161312_Chrome](https://user-images.githubusercontent.com/69076256/222406313-10fe39c2-2c6f-4d08-99ef-9715b47c6c4e.png)

**Comment by BlazDT** [comment]
They check if pagead2.googlesyndication.com/pagead/js/adsbygoogle.js is blocked, that domain serves most of the ads, therefore will not be unblocked.
