### ISSUE TITLE
Check if these rules are really needed

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#144407]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

NA

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

I don't remove a rule of `||a.com^` when EL has `||a.com^$third-party` as advised, but I think whether these rules are really needed should be checked. Here the list of such rules:
```
! firstparty
||ads.linkedin.com^
! adservers
||histock.info^
||admanmedia.com^
||adsrv4k.com^
||fireworkadservices1.com^
||getmyfreetraffic.com^
||paibopse.com^
||reevaipi.com^
||sendmepush.com^
||profield.ddns.net^
```

### Privacy

- [X] I agree to follow this condition

**Comment by Yuki2718** [comment]
> What is wrong?

They're mostly redundant with EL.

**Comment by Alex-302** [comment]
Removed _few_.
