### ISSUE TITLE
apk4fun.com [Ad String]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#14451]
**Site**: https://www.apk4fun.com/apk/186381/

**Issue**: Please remove the Ad string on the page.

**Screenshot**: http://prntscr.com/j22cu8

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.181 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
not reproduced.
