### ISSUE TITLE
https://meeco.kr/

### ISSUE THREAD

**Issue by hotdog5785** [AdguardTeam/AdguardFilters#144583]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

latest

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://meeco.kr/news/36902872

### What filters do you have enabled?

adguard dns, adguard mobile ads, easylist

### Add your comment and screenshots

![2BB50B10-44CE-4CE1-92CF-735681772379](https://user-images.githubusercontent.com/99060747/222896205-7761813d-34e5-4d51-b59b-f391293f76ca.png)

detected at mobile safari

not detected at main page. only detected when i click several posts
ex) https://meeco.kr/news/36902872

not detected at desktop Edge - with same filters, even when i click posts, too.

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
@hotdog5785 Please enable List-KR filter.

<details>
<summary>한국어 - Korean</summary>

List-KR 필터를 활성화해주세요.

</details>
