### ISSUE TITLE
htmlweb.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#14462]
[https://htmlweb.ru/php/example/curl_download.php](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fhtmlweb.ru%2Fphp%2Fexample%2Fcurl_download.php)

 1. Антиадблок в этом скрипте - https://htmlweb.ru/js_utf8.min.js - также, как и доступ к возможности оставить комментарий. При блокировке этого скрипта - кнопка "Прокомментировать/Отблагодарить" не нажимается.

 2. Баннер: `htmlweb.ru###r7`

 Антиадблок и баннер могут появляться не с первого раза - нужно поперезагружать и/или чистить куки.

<details><summary>Screenshot:</summary>

![2018 04 06-1](https://user-images.githubusercontent.com/17948007/38450953-77f07eca-3a2f-11e8-96a0-f8bc44460d22.png)
</details>

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.8.6 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by XX-J** [comment]
Рекламная строка.

<details><summary>Screenshot:</summary>

![2019 10 21-1](https://user-images.githubusercontent.com/17948007/67178643-2031cc80-f3dc-11e9-8638-ae5cec481c8a.png)
</details>

[https://htmlweb.ru/geo/telcod.php](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://htmlweb.ru/geo/telcod.php)

`htmlweb.ru###divtop`

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.3.1
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
ок
