### ISSUE TITLE
Remove dead domain in Base (3)

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#144603]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

NA

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

```
! foreign
mp3e.sende.biz
news.lent.az
turizm.fins.az
e14.cz
damoh.aftonbladet.se
e101.cdn.m6web.fr
net.adjara.com
bhavishya.raftaar.in
media.mensxp.com
idfl.me
depodomino.com
panel.cint.com
emagst.akamaized.net
van1.mvx-master4.work
cdn.ufabet678.com
```

### Privacy

- [X] I agree to follow this condition

**Comment by Yuki2718** [comment]
Please double-check as I only excluded those I know subdomain are alive from PyFunceble results.
```
! specific
bingretailmsndata.azureedge.net
adbroker.mp.dse.microsoft.com
videorolls.row.aiv-cdn.net
nwsfhxfqmtjx.com
virtwishes.site
production.sgweb.softgames.de
f00f00.bar
staging1.btp.ac.id
bandar21.me
static.playtube.ws
nas1.flashx.net
data.miny.cc
moongazing.xyz
stream.directmoviedl.com
entaiarena.com
faxfossil.com
fcdot.lc
pcs.boundhub.com
fay.chat
btdb.eu
somenewz.pw
static.cfgr3.com
g00.performgroup.com
seo.pandanetwork.club
ssa.1337x.to
eteknix-eteknixltd.netdna-ssl.com
static.flashx.co
c.hqq.tv
srv.queerpixels.com
static.cfgr2.com
www1.wi.to
games.softgames.com
static.x64zcsqq.netdna-cdn.com
new.evanstonnow.com
static.exosrv.com
search.vertoz.com
thevideobee.to
thumbs.dagay.com
datoporn.co
stacksocial-production-stacksocial.netdna-ssl.com
nakednepaligirl.com
redirect.won.pe
720movies.com
porncorn.co
content.shoosh.co
static.cfgr1.com
adzuna-jobbox.fairfaxmedia.com.au
static.chameleon.ad
a.onion.nu
adtag.asiaone.com
cdn.bc.vc
cdn.movieweb.com
d20flqux56m8w7.cloudfront.net
files.nyaa.eu
kad.kaskus.com
mystreans.com
porn-bb.net
pho.staticfiles.org
thessdreview1.netdna-cdn.com
zkake.exashare.com

```

**Comment by Yuki2718** [comment]
```
! replace
embed.streamx.live
bigplayer.pro
watchlivestream.me.uk
mystreans.com
now-api.mediaworks.nz
vmap.snappytv.com
```

**Comment by Alex-302** [comment]
Not dead, just you checked only a partial host name
`emagst.akamaized.net`

**Comment by Yuki2718** [comment]
> Not dead, just you checked only a partial host name `emagst.akamaized.net` `||s*emagst.akamaized.net/assets/*/js/ads_script.js$domain=emag.ro,important`

@funilrys I guess PF should take this type of rules as invalid domain?

**Comment by funilrys** [comment]
@Yuki2718 indeed it should. Is `*` in that context really a wildcard ?

**Comment by Yuki2718** [comment]
> Is `*` in that context really a wildcard ?

Yes.
