### ISSUE TITLE
[Android] Enabling ABP Japanese filter blocks using VK app

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1447]
You need to Enable ABP Japanese filters and try to use VK app or visit vk.com or m.vk.com
Chrome error is err_connection_closed
Logs here - XOU-811-95200
User complaint - SGE-852-27936

**Comment by evgeniy-ADG** [comment]
GJH-889-36740 - looks like the same issue

**Comment by Alex-302** [comment]
try this rule
```
@@||vk.com^$domain=~vk.com|~vkontakte.ru
```

**Comment by Bohdan-SUP** [comment]
Seems to be working even with ABP Japanese enabled and no custom rules applied.
Will check with users.

**Comment by Bohdan-SUP** [comment]
@Alex-302 user confirmed the rule works with ABP Japanese enabled.

**Comment by evgeniy-ADG** [comment]
Но! появилась новая проблема, при попытке отправки фотографий через
сообщения в том же контакте выдает ошибку, и так же исчезает при отключении
того же фильтра.

**Comment by Alex-302** [comment]
А юзер русскоговорящий, или японец? Если японским не владеет, то лучше выключить этот фильтр, или мешающие правила. Японцы многие домены мейл  ру  и контактов блокируют как рекламные сети.

**Comment by evgeniy-ADG** [comment]
Русскоговорящий.
