### ISSUE TITLE
http://www.msn.com/ - video playback issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1450]
When you watch the [video](http://www.msn.com/en-us/video/popculture/actors-butcher-boston-accents/vi-BBoIhZ2?ocid=spartandhp) on MSN with Adguard enabled, it gets interrupted few times a second.
Once Adguard is turned off, the video works fine. Reproduced on my side with the extension.

QZR-450-54118

**Comment by Alex-302** [comment]
@evgeniy-ADG 
" interrupted few times a second"
can you describe it? The video works on my end, but it loads slowly.

**Comment by evgeniy-ADG** [comment]
@Alex-302 короче, перерывается оно очень быстро, будто бы притормаживает
у меня вот с 6-кой все отлично, с расширением - было так, ка я описал.

**Comment by Alex-302** [comment]
может всё же они не могут видео отдать с нужной скоростью или где-то узкое место от их серверов к юзеру? Если вначале поставить на паузу и дать подгрузиться - играет нормально, а так и без Адгарда у меня тормозит
