### ISSUE TITLE
www.efilmy.tv

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#14514]
**Site Sample** | 
------------------|
http://www.efilmy.tv/film,27945,Nikt-znikad-2014-Lektor-PL.html

Information                         | Value
---                                 | ---
Operating system:                   | Manjaro Linux x86_64
Browser:                            | Google Chrome x86_64
AdGuard Chrome Extension:                    | **2.8.6**

Filters enabled |
----------------|
`english ** spy ** annoyances ** social ** polish main ** polish adguard suplement ** polish social ** I don't care about cookies ** alleblock`

### Issue:

Ad leftover, popups CC @AdamWr 

<details><summary><b>Screenshot:</b></summary>

![screenshot_20180408_164004](https://user-images.githubusercontent.com/9846948/38468823-8dabbfa0-3b4b-11e8-8f8d-4e386e70c147.png)

</details><br/>

**Comment by AdamWr** [comment]
On my end that ad is blocked by `Adblock & uBlock Polish filter` and I can't reproduce popups.
Are you sure that `Adblock & uBlock Polish filter` is enabled and updated?

**Comment by FadeMind** [comment]
Update lists resolving issue. Closing
