### ISSUE TITLE
Ifunny

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#145413]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=mobi.ifunny

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

Multiple ad domains probably not being blocked. Cant figure them out tho sorry.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
What exactly is wrong?

**Comment by jordanswrld94** [comment]
I found some domains these are the only ones that show in logs.

||rtb-useast.displayio.cloud^
||core-b8mf-nocp.tk0x1.com^
||core-b8mf.tk0x1.com^
||prebid-cache.ifunny.co^
||eu-nd*.itdsmr.com^
||static.displayio.cloud^

**Comment by jordanswrld94** [comment]
@Alex-302

**Comment by jordanswrld94** [comment]
us8.remerge.event

Heres another
