### ISSUE TITLE
translate.yandex.ru

### ISSUE THREAD

**Issue by anmishubin** [AdguardTeam/AdguardFilters#145424]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Social media buttons — share, like, tweet, etc.

### Which browser(s) do you use?

Yandex Browser

### Which device do you use?

Desktop

### Where is the problem encountered?

https://translate.yandex.ru/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter

### Add your comment and screenshots

1. При блокировке рекламы на сайте, блок рекламы исчезает, но структура сайта нарушается. Основные фреймы не по центру и аватарка сдвинута вправо.

2. Screenshots
<details><summary>Выглядит вот так:</summary>

![Снимок экрана 2023-03-13 010703](https://user-images.githubusercontent.com/52073031/224704144-69c4a9ab-ea65-48ed-a119-c9ddef23af59.png)
</details>

<details><summary>Должно быть:</summary>

![Снимок экрана 2023-03-13 010733](https://user-images.githubusercontent.com/52073031/224704300-f77151a4-20d2-4128-98b8-fd16d4df0297.png)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by anmishubin** [comment]
> У меня не повторяется

Это происходит когда ты залогинен в Яндекс ID. И если показывается релкама на странице.
Она показывается в Яндекс Браузере и не показывается, например, в Edge.
У вас не показывается реклама даже если вы залогинены, как я вижу.

> Какой фильтр приводит к поломке?

Как это узнать?

**Comment by anmishubin** [comment]
@Alex-302 Вот так?

<details><summary>Скриншот:</summary>

![Снимок экрана 2023-03-13 215728](https://user-images.githubusercontent.com/52073031/224803351-75319249-574e-4c43-85cc-4ea584242998.png)


</details>

**Comment by anmishubin** [comment]
@Alex-302 Я немного не понимаю - какие исключения и что мне нужно сделать?

**Comment by Alex-302** [comment]
Исключение - это разблокирующее правило фильтрации.
Кликнув на желтую или красную строку можно создать правило, которое разблокирует элемент страницы или запрос.

<details>
<summary>1</summary>

![image](https://user-images.githubusercontent.com/8361299/224808607-ba1109ba-5500-465f-923b-c5df7d4e7cc3.png)


</details>

<details>
<summary>2</summary>

![image](https://user-images.githubusercontent.com/8361299/224808741-6f898e8d-340f-4468-a0d4-5dd72d03d473.png)


</details>

3 - обновите вкладку.

**Comment by anmishubin** [comment]
@Alex-302 Попробовал туда-сюда и красные разблокировать и жёлтые - не помогает.
В некоторых случаях просто реклама на место возращается. А в остальных случаях ничего не происходит. Мне просто нужно чтобы элемент страницы после блокировки рекламы вернулся на место.

**Comment by Alex-302** [comment]
Добавьте в пользовательский фильтр и проверьте
`@@translate.yandex.ru^$generichide`
правила, созданные с помощью журнала, нужно удалить.

**Comment by anmishubin** [comment]
@Alex-302 Свои правила очистил. Ваше добавил - нчиего не изменилось. Рекламы нет и всё сдвинуто.

**Comment by Alex-302** [comment]
Проверьте по одному:
`@@translate.yandex.ru^$elemhide`
`@@translate.yandex.ru^$urlblock`
`@@translate.yandex.ru^$document`

**Comment by anmishubin** [comment]
@Alex-302 Первые два ничего не поменяли. Третий вернул рекламу.

**Comment by Alex-302** [comment]
А так
`@@translate.yandex.ru^$elemhide,urlblock,jsinject`

**Comment by anmishubin** [comment]
@Alex-302 Реклама остаётся.

**Comment by Alex-302** [comment]
Сейчас интересует не реклама, а поломка сайта.

**Comment by anmishubin** [comment]
@Alex-302 Ну просто реклама возвращается. Я об этом.

**Comment by Alex-302** [comment]
А с вёрсткой что? Исправилась?

**Comment by anmishubin** [comment]
@Alex-302 Ну если реклама появляется обратно, то и вёрстка становится нормальной. По сути я могу просто расширение отключить на странице.

**Comment by Alex-302** [comment]
К прошлым сообщениям:

> У вас не показывается реклама даже если вы залогинены, как я вижу.

Яндекс Браузер на ряде сайтов запрещает/мешает блокировщикам рекламы (расширениям). Может здесь такой случайй? Я у себя не вижу рекламу при выключенном блокировщике.


Вот такое ещё проверьте
`@@translate.yandex.ru^$jsinject`
это менее широкое разблокирующее правило, чем предыдущее `@@translate.yandex.ru^$elemhide,urlblock,jsinject`

**Comment by anmishubin** [comment]
@Alex-302 По некоторым причинам я переустановил систему и браузер, соответственно, тоже. Проблема решилась сама собой. На сайте перестала показываться реклама.

**Comment by Alex-302** [comment]
Хмм. Ну ладно)
