### ISSUE TITLE
Excessive CPU usage at https://rp5.ru/ website

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#14555]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

Возникает проблема с повышенной нагрузкой на процессор, при включенном фильтре "Русский фильтр Версия 2.0.2.0." на сайте https://rp5.ru/ 

Отключил все расширения (кроме AdGuard). Проблема осталась. Обновил Firefox до 59.0.2.Проблема осталась. Проверил на другой системе (windows 10 1709 64 bit, Firefox 59.0.2). Проблема также имеется. Дело именно в Русском фильтре, т.к. при его отключении все нормализуется. Это видно, в частности, по всплывающим подсказкам на сайте https://rp5.ru/ , они появляются без замедлений, и нагрузка на процессор падает сразу до 1-2%, тогда как с фильтром нагрузка 25-30%.

***System configuration***

**Filters:**

Английский фильтр Версия 2.0.4.41. Обновлено 7 апреля 2018 в 06:02.
Фильтр счетчиков и систем аналитики Версия 2.0.1.10. Обновлено 7 апреля 2018 в 03:03.
Фильтр виджетов социальных сетей Версия 2.0.1.64. Обновлено 6 апреля 2018 в 21:03.
Фильтр раздражителей Версия 2.0.2.30. Обновлено 7 апреля 2018 в 03:03.
Русский фильтр Версия 2.0.2.1. Обновлено 7 апреля 2018 в 00:04.

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | windows 10 1709 64 bit
Browser:                               | Firefox 59.0.2
AdGuard version:                       | 2.8.6
User ID .            | 1820402

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by WowDude** [comment]
@evgeniy-ADG maybe similiar: https://github.com/gorhill/uBlock/issues/3645

**Comment by Alex-302** [comment]
Сайт такой. Даже без нас при загрузке нагружает процессор.
