### ISSUE TITLE
Iplogger tracking in Email

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#145521]
Hello!

**_PLEASE READ THIS CAREFULLY_**

This isn't the first time I've seen emails with tracking pixels from iplogger (https://iplogger.org/tracking-pixel/) lined up.

Here is a fragment of one of such emails:

```
<style style="box-sizing: border-box;"> #_eoa_div, #_eoa_img { display:none; } @media print{ #_eoa_div { background-image: url('https://iplogger.com/1vvi65.jpeg'); } 
} div.OutlookMessageHeader, table.moz-email-headers-table, blockquote #_eoa_div, #mailContainerBody #_eoa_div { background-image:url('https://iplogger.com/1vvi65.jpeg') } 
</style>
<div id="_eoa_div" style="box-sizing: border-box; display: none;"></div>
```

Therefore, I propose to add the following rules to block external tracking with such emails:

```
​||iplogger.org^$third-party
||iplogger.com^$third-party
||maper.info^$third-party
||iplogger.ru^$third-party
||iplogger.co^$third-party
||2no.co^$third-party
||yip.su^$third-party
||iplogger.info^$third-party
||ipgrabber.ru^$third-party
||ipgraber.ru^$third-party
||iplis.ru^$third-party
||wl.gl^$third-party
||ed.tc^$third-party
||bc.ax^$third-party
||02ip.ru^$third-party
||ezstat.ru^$third-party
||iplogger.cn^$third-party
```

I believe this is a necessary action, as embedding such trackers as hidden pixels does serious damage to privacy by revealing information about User Agent, IP, country of residence, and the date the email was opened. Please add these rules to your list along with other types of trackers (pixels), as these are no different from them

**Comment by BlazDT** [comment]
Added all except the following (not finding information about them:

```
||ed.tc^$third-party
||bc.ax^$third-party
```

**Comment by Ctcyfyftdtfy** [comment]
> Added all except the following (not finding information about them:
> 
> ```
> ||ed.tc^$third-party
> ||bc.ax^$third-party
> ```

I hope this will help you to block them too:
![EAFF60F8-931A-42E7-B12C-3455D5C7942F](https://user-images.githubusercontent.com/128077614/225705078-42e0e980-d799-4f0e-a4c9-2d6f1978e76e.jpeg)
