### ISSUE TITLE
AdGuard Annoyances blocks link[rel=manifest]

### ISSUE THREAD

**Issue by KaKi87** [AdguardTeam/AdguardFilters#145545]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.11

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://status.katys.cf/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard French filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter, Online Malicious URL Blocklist, NoCoin Filter List

### Add your comment and screenshots

1. When the filter is disabled, a [`link[rel=manifest]`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/manifest) element is present in the web page. But when the filter is enabled, the element is missing 

2. Screenshots

None (ask what kind you'd need if any, but I have no idea at first glance).

---

Thanks

### Privacy

- [X] I agree to follow this condition

**Comment by KaKi87** [comment]
I see.

Well, I guess I'll stick to Fanboy's annoyances blocklist then, because I need those manifests.

Thanks

**Comment by krystian3w** [comment]
test add to my rules:
```adb
$@$link[rel="manifest"]
```

**Comment by KaKi87** [comment]
I'm using `link[rel=manifest]` elements from a [userscript](https://en.wikipedia.org/wiki/Userscript) to [detect a number of self-hostable webapps](https://git.kaki87.net/KaKi87/userscripts/src/branch/master/darkReaderDynamicBlacklist/main.user.js#L502) for which to programatically disable Dark Reader *([more info](https://git.kaki87.net/KaKi87/userscripts/src/branch/master/darkReaderDynamicBlacklist/README.md))*.

So, I could, indeed, manually add this counter-filter to my own configuration, but I can't ask all my userscript's users to do the same, instead I can tell them to use Fanboy's annoyances blocklist instead of AdGuard's, as it's much easier.

**Comment by krystian3w** [comment]
Now you can encourage people to switch to the modular version of AdGuard Annoyances and necessarily not activate the list to cut out buttons promoting mobile apps:

![image](https://github.com/AdguardTeam/AdguardFilters/assets/35370833/f296f6ec-5dfd-4031-8b61-6cee2baeb27b) | ![image](https://github.com/AdguardTeam/AdguardFilters/assets/35370833/09855ea5-6513-4f21-8fa7-02c8d8ce955b)
--- | --- 
uBo dev (disabled "Mobile app banners") | AdGuard 4.1.55 (disabled "Mobile app banners")

**Comment by KaKi87** [comment]
> you have to wait until it is transferred from uBo dev to the stable release

Would it be possible to import those via URL until then ?

**Comment by krystian3w** [comment]
Of course:

```adb
https://filters.adtidy.org/extension/ublock/filters/18.txt
https://filters.adtidy.org/extension/ublock/filters/19.txt
https://filters.adtidy.org/extension/ublock/filters/21.txt
https://filters.adtidy.org/extension/ublock/filters/22.txt
```
