### ISSUE TITLE
mail.yandex.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#145600]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://mail.yandex.ru

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Block WebRTC, Hide Referrer from third-parties (specify in comment below, if used custom value)

### Add your comment and screenshots

 Пропали доп. кнопки внизу левой колонки интерфейса почты, в том числе такие полезные как: Журнал учёта посещений, выбор языка и др. Всему виной правило `mail.yandex.*#%#//scriptlet('abort-on-property-read', 'Object.prototype.adv')` в фильтре Раздражителей:
https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/Other/sections/annoyances.txt#L2495

<details><summary>Как сейчас:</summary>

![2023 03 15-1](https://user-images.githubusercontent.com/17948007/225341674-c26d1b2b-9041-40bb-9d93-6347c001b806.png)
</details>

<details><summary>Как надо:</summary>

![2023 03 15-2](https://user-images.githubusercontent.com/17948007/225342002-8893fbda-07d5-45ab-a28e-c2d0a07d9e83.png)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@XX-J У себя не наблюдаю этих кнопок. Какой-то особый режим интерфейса нужно использовать?

**Comment by XX-J** [comment]
Нет, интерфейс обычный. Попробуй с отключённым AdGuard'ом пролистать левую колонку до конца и там, под рекламой, будет эта пачка кнопок. Но там, помимо тех, что на моём скрине, присутствуют ещё множество мусорных кнопок, которые я скрыл, например кнопки скачивания моб. приложений, устройства к ним на работу и т.д.

**Comment by Alex-302** [comment]
Да, это я кастомным фильтром у себя блокирую те кнопки:)
На их отсутствие жалоб нет, так что пока лучше исключение оставить в юзерфильтре
`mail.yandex.com#@%#//scriptlet('abort-on-property-read', 'Object.prototype.adv')`
