### ISSUE TITLE
o.savecall.de cname for date.wcheck.org

### ISSUE THREAD

**Issue by MrCybertux** [AdguardTeam/AdguardFilters#145666]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

1.42.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

o.savecall.de

### What filters do you have enabled?

AdGuard Tracking Protection filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Disable cache for third-party requests, Block Push API, Block Location API, Hide Referrer from third-parties (specify in comment below, if used custom value), Mask your IP address (specify in comment below, if used custom value), Protect from DPI

### Add your comment and screenshots

1. I work for a IT company and sales just asked me th CNAME a tracking link for them to [date.wcheck.org](http://date.wcheck.org/) Pls block that link right away

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Could you please elaborate why we should block o.savecall.de?

**Comment by MrCybertux** [comment]
> Could you please elaborate why we should block o.savecall.de?

Because they use the Domain as Cname for a tracking domain from ComX - AI for sales.
It CNAMES date.wcheck.org witch is used for tracking cusomer infos with the cloud AI CRM tool from ComX.
I was told the domain is used for tracking pixels etc.

**Comment by Alex-302** [comment]
Where are these domains used?

**Comment by MrCybertux** [comment]
> Where are these domains used?

Usable in Mails for tracking the times opend and watched (For users using services like Gmail in  the Webinterface a danger)
And posbibly for tracking users on Websites, i do not no witch and even if i wold not know  i can't tell you.
Since a CNMAE arguably is not a company secret i told you, but i stretches the boundries of my contract allready.
You see https://comx.io/en/home it is a tool for Tacking unknowing customers do you need more reason to block?

**Comment by Alex-302** [comment]
savecall.de is not related to comx.io
date.wcheck.org - as I see, carrot.wcheck.org used for tracking. But I can't check - if DNS blocking will break links, we should not block it.

**Comment by MrCybertux** [comment]
> savecall.de is not related to comx.io date.wcheck.org - as I see, carrot.wcheck.org used for tracking. But I can't check - if DNS blocking will break links, we should not block it.

Sorry but what herb are you smoking?
First of all why are you going to the main domain if i cleary state o.savecall.de?
You know what a CNMAE is right?
![image](https://user-images.githubusercontent.com/67368875/228847097-36d31b25-4dac-4089-b849-6b7169c30d50.png)

**Comment by Alex-302** [comment]
> You know what a CNMAE is right?

sure.

I mean they use carrot.wcheck.org according to https://woodpecker.co/help/set-up-custom-tracking-domains/

Can you show a tracking request from email?

**Comment by MrCybertux** [comment]
no i do not have any of them
