### ISSUE TITLE
Wrong line format

### ISSUE THREAD

**Issue by madmaxpro** [AdguardTeam/AdguardFilters#145785]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Latest 

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

trk.mail.ru,ping

### What filters do you have enabled?

AdGuard Tracking Protection filter

### Add your comment and screenshots

1. <comment> There is wrong format on the list `trk.mail.ru,ping` . I think the `,ping` should be removed.

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
I cannot find such rule in `AdGuard Tracking Protection filter`, there is:
https://github.com/AdguardTeam/AdguardFilters/blob/24215d2fceda9adfdadb05fcb8ed6baa6cd1ce94/SpywareFilter/sections/specific.txt#L1092

Please provide more information.
