### ISSUE TITLE
123pan.com

### ISSUE THREAD

**Issue by cyberboh** [AdguardTeam/AdguardFilters#145961]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.47.5rc2

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.123pan.com/s/qHhDVv-nuQJv

### What filters do you have enabled?

AdGuard Chinese filter, EasyList, ABPindo, AdBlockID

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/99109969/226177900-3483a8f8-0a76-42e8-9eec-6a29ac72d059.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Blocked in `AdGuard Annoyances filter` / `AdGuard Other Annoyances filter`
