### ISSUE TITLE
hurriyet.com.tr

### ISSUE THREAD

**Issue by uuqqzz** [AdguardTeam/AdguardFilters#146009]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Social media buttons — share, like, tweet, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.hurriyet.com.tr/yazarlar/dincer-guner/yepyeni-bir-donem-basliyor-42235810

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

<details><summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/226246947-6d3125bd-1e49-4ce8-8c77-b9410b4c20f7.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
