### ISSUE TITLE
store.playstation.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#1460]
https://store.playstation.com/#!/en-us/home/main 

Login doesn't work with 'Block third-party cookies' option enabled.

**Comment by Alex-302** [comment]
I can't login without Adguard, got this message
```
Site Not Available
The PlayStation®Store is currently not available. You can learn about Sony Entertainment Network content and services at Sony Entertainment Network.
```
He cen try
@@||auth.api.sonyentertainmentnetwork.com^
