### ISSUE TITLE
DuckDuckGo tracker

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#146097]
Hello! The analytics on the DuckDuckGo service. Please add to the list of link reductions from tracking parameters

Example:
`https://duckduckgo.com/?q=anything&t=iphone&iax=images&ia=images`

So can you add the following rule:
`||duckduckgo.com^$removeparam=t`

Everything works fine without this parameter. I had checked

**Comment by Alex-302** [comment]
They see your user agent.
