### ISSUE TITLE
Filter blocks legit website www.thes-du-japon.com

### ISSUE THREAD

**Issue by bxkx** [AdguardTeam/AdguardFilters#146166]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Ublock Origin 1.47.4

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.thes-du-japon.com/index.php?main_page=product_info&cPath=1_130_3&products_id=123

### What filters do you have enabled?

AdGuard Japanese filter

### Add your comment and screenshots

1. The _`/index.php?main_page=product_info&cpath=$document`_ and _`/index.php?main_page=product_info&cPath=$document`_ "malware/phishing" filter blocks legit websites. It's just URL part of certain shop systems.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@Yuki2718 It seems that rules are problematic. Temporary commented.

**Comment by Yuki2718** [comment]
Will limit domain then.
