### ISSUE TITLE
suslusozluk.com

### ISSUE THREAD

**Issue by uuqqzz** [AdguardTeam/AdguardFilters#146114]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.suslusozluk.com/loess-siyah-nokta-burun-band%C4%B1

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

<details><summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/226523603-8d6bee58-c14f-424b-a613-d0058a2f5319.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/226597566-70634140-3753-4542-a1b1-c1eb75d970a7.png)


</details>
