### ISSUE TITLE
dvdgayonline is sourcing video dood.re which is forcing me to remove my adguard Adblocker

### ISSUE THREAD

**Issue by olstice** [AdguardTeam/AdguardFilters#146112]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

Adguard 4.4.5

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://dvdgayonline.com/movies/ノンケ限界面接-the-12th-time/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment> Hi so I was visiting a website I found called gaydvdonline and I selected a video to watch which is sourcing the content directly from a second site called dood.re? And it’s telling me the publisher of the video does not allow adblockers is there anyway this could be resolved please?

3. Screenshots
<details><summary>Screenshot 1:</summary>

![DE1D8BD2-52D1-44C5-8E26-CF8003F5EE88](https://user-images.githubusercontent.com/124982114/226521991-577c00df-059a-47a3-a14a-b5e47b99d135.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Please try these rules:

```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=dvdgayonline.com
@@||dvdgayonline.com^$generichide
```

**Comment by olstice** [comment]
> Please try these rules:
> 
> ```
> @@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=dvdgayonline.com
> @@||dvdgayonline.com^$generichide
> ```

![ED395B9C-913C-4BB4-8315-E160735941EF](https://user-images.githubusercontent.com/124982114/226762151-b0b82f07-4096-4686-bb95-5d8afd7a7559.png)


It’s still not working I am using safari iOS just fyi don’t know if that helps

**Comment by olstice** [comment]
> Please try these rules:
> 
> ```
> @@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=dvdgayonline.com
> @@||dvdgayonline.com^$generichide
> ```

I actually forgot to update but every time I try I get taken out of the app

**Comment by olstice** [comment]
> Please try these rules:
> 
> ```
> @@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=dvdgayonline.com
> @@||dvdgayonline.com^$generichide
> ```

I know what I did wrong I add those two rules as one I resolved the issue adding them separately and now it’s working thank you!
