### ISSUE TITLE
GoatRAT Trojan block request

### ISSUE THREAD

**Issue by ViniciusFXavier** [AdguardTeam/AdguardFilters#146175]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

GoatRAT was originally created as an Android Remote Administration Tool to seize control of a victim’s device. However, a new version of GoatRAT functions as a Banking Trojan, specifically aimed at Brazilian banks.

Like other types of Banking Trojans, GoatRAT utilizes the Accessibility service to implement an Automatic Transfer System (ATS) framework, which enables the transfer of money from the victim’s account using the PIX key. The PIX key is used to perform the instant payment. This malware currently targets three Brazilian banks: NUBank, Banco Inter, and PagBank.

![image](https://user-images.githubusercontent.com/40774281/226697704-8d3874d2-43e6-4dbb-a8bb-5796352dccbf.png)

URL source: https://blog.cyble.com/2023/03/14/goatrat-android-banking-trojan-variant-targeting-brazilian-banks/

### Proposed solution

Block URL's:
<html>
<body>

URL | Description
-- | -- 
hxxps://bit[.]ly/nubankmodulo | Shortened malware distribution URL
hxxps://goatrat[.]com/apks/apk20.apk | Malware distribution URL
hxxp://api.goatrat[.]com:3008 | C&C server to receive PIX key

</body>
</html>

**Comment by DandelionSprout** [comment]
I propose:
```
||goatrat.com^$all
||bit.ly/nubankmodulo^$all
```

**Comment by krystian3w** [comment]
Also exist Gootloader:

https://www.mandiant.com/resources/blog/tracking-evolution-gootloader-operations

Maybe cured IP/domains:

```adb
## Goot loader command and control
||jonathanbartz.com^$all
||jp.imonitorsoft.com^$all
||junk-bros.com^$all
||kakiosk.adsparkdev.com^$all
||kepw.org^$all
||kristinee.com^$all
||lakeside-fishandchips.com^$all

## Cobalt Strike Beacon Backdoor
||108.61.242.65^$all
||108.61.242.65^$all
||146.70.78.43^$all
||146.70.78.43^$all
||87.120.254.39^$all
||87.120.254.39^$all
||45.150.108.213^$all
||45.150.108.213^$all
||92.204.160.240^$all
||92.204.160.240^$all
```

I am not convinced that AdGuard Home has already implemented the conversion of all to regular blockchain - so list may need dupliacte lines.

I also completely don't know if AdGuard Home or AdGuard DNS knows how to block IP connections (apparently Pi-Hole doesn't and it's definitely not supported in HOSTS).

**Comment by DandelionSprout** [comment]
I presume the duplicate IPs can be skipped, but the rest I agree with.

AdGuard Home has been able to block by IP for some years now. I can only vaguely presume that AdGuard DNS IO (as opposed to AdGuard Public DNS) does the same.

**Comment by piquark6046** [comment]
It is blocked by AdGuard browsing security module.
https://github.com/AdguardTeam/FiltersRegistry/issues/763#issuecomment-1479460865

**Comment by zloyden** [comment]
As I said [here](https://github.com/AdguardTeam/FiltersRegistry/issues/763#issuecomment-1479460865), it's already blocked by [our browsing security](https://reports.adguard.com/en/goatrat.com/report.html).

**Comment by krystian3w** [comment]
You missed block that https://github.com/AdguardTeam/AdguardFilters/issues/146175#issuecomment-1479126107

On your page I saw all domains and IP as allowed for anti malware mechanism...
