### ISSUE TITLE
chia-anime.tv, animeshow.tv - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1462]
http://www.chia-anime.tv/ixion-saga-dt-episode-12-english-subbed/
http://animeshow.tv/Lupin-III-2015-episode-18/

![image](https://cloud.githubusercontent.com/assets/15856304/12844485/3f9db214-cc08-11e5-8daf-b2a35889ae30.png)
![image](https://cloud.githubusercontent.com/assets/15856304/12844516/751f300c-cc08-11e5-9e59-a8f136a73641.png)

RPD-786-13365

**Comment by Alex-302** [comment]
||cpmstar.com^$object-subrequest,third-party

**Comment by Bohdan-SUP** [comment]
Another problem with mentioned website:
https://www.youtube.com/watch?v=LDtuimd-Wdw&feature=youtu.be

**Comment by Alex-302** [comment]
@Bohdan-SUP 
can you confirm his problem? I don't understand him:) The site is clean, video plays correctly.

**Comment by Bohdan-SUP** [comment]
Nope, it works fine on my end. The issue is that multiple websites freeze and he can't even click on any element with Adguard running.

**Comment by Alex-302** [comment]
Maybe too much filters? Ask him for disable all filters, except English.
