### ISSUE TITLE
Incorrect rule for xhamster.com

### ISSUE THREAD

**Issue by mtxadmin** [AdguardTeam/AdguardFilters#146364]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

*

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

xhamster.com

### What filters do you have enabled?

---Third-party filters---

### Add your comment and screenshots

The rule xhamster.com#?#div[class]:has(> div[class*="widget"]) causes a problem on xhamster.com - the page turns completely blank.

They have body>.main-wrap>.bottom-widget-section in a video page (xhamster.com/videos/...)

The rule is in https://github.com/AdguardTeam/AdguardFilters/blob/master/MobileFilter/sections/css_extended.txt

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Please test these two rules:

```
xhamster.com#@?#div[class]:has(> div[class*="widget"]) 
xhamster.com#?#div[class]:not(.main-wrap):has(> div[class*="widget"]) 
```

**Comment by zloyden** [comment]
@BlazDT the rule was removed, but I don't see any leftovers on my end. They blocked by the ext-css rule.

**Comment by BlazDT** [comment]
I had left-overs when I added that rule on my Android. But now it seems to be blocked.
