### ISSUE TITLE
Issues with MX Player app

### ISSUE THREAD

**Issue by iDNA420** [AdguardTeam/AdguardFilters#146370]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

Not Applicable

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.mxtech.videoplayer.ad

### What filters do you have enabled?

AdGuard Mobile Ads filter

### Add your comment and screenshots

1. This breaks the user experience for MX Player's OTT users as qqcdnpictest.mxplay.com is mainly used to deliver image assets (i.e. content preview and thumbnails). 

https://github.com/AdguardTeam/AdguardFilters/blob/1e0e9efa1474af5d20f04e5fe30aad2101733b6d/MobileFilter/sections/adservers.txt#L138

2. Screenshots
![Screenshot 2023-03-23 at 21 41 08](https://user-images.githubusercontent.com/80810457/227441437-7492bf0a-fa54-44e8-a3ba-fc3cc7c0897c.jpeg)

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I don't have this UI on my end. Does unblocking the request solve this problem?
@AdguardTeam/filters-maintainers please take a look at this.

**Comment by BlazDT** [comment]
To have those requests you have to be connected with an Indian VPN and then visit this site:
https://www.mxplayer.in/mx-gold

**Comment by zloyden** [comment]
I have been checking it with Indian IP. Interesting, but I still do not have the UI in the app on my end.
However, unblocking the rule is required for the site.
I guess we can remove it completely.

**Comment by BlazDT** [comment]
Removed the rule.
