### ISSUE TITLE
Bloomberg.com blank page

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdguardFilters#146392]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

Adguard 4.0 Nightly 71

### Environment

```markdown
- OS:Android 13
- Device: Samsung
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, EasyPrivacy, Fanboy's Annoyances, Fanboy's Social Blocking List, Peter Lowe's Blocklist, Online Malicious URL Blocklist, Fanboy's Enhanced Tracking List, I don't care about cookies, EasyList Cookie List, NoCoin Filter List, Dandelion Sprout's Annoyances List, Legitimate URL Shortener

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

Steps to reproduce:
1.open Samsung internet browser or Chrome browser on phone
2. Go to bloomberg.com
3.shows black screen

### Actual Behavior

Blank screen

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

[Screenshot_20230322_175958_Samsung Internet](https://user-images.githubusercontent.com/96619913/227059212-8d2cf78c-417c-4ee1-b3c3-783aec93471f.jpg)

**Comment by Batman2814** [comment]
I tried to disable that filter, and still, the issue was there.

**Comment by Versty** [comment]
@Batman2814 Please disable the filter, then restart protection.

**Comment by Batman2814** [comment]
Just did that and still have not fixed it.
