### ISSUE TITLE
Question about blocking timers

### ISSUE THREAD

**Issue by oleedd** [AdguardTeam/AdguardFilters#14668]
I know about Adsbypasser.
I have seen how AdGuad blockes timers on several sites (just very interesting about user rules of that blockings). Is it possible to block timers (with some user rules) on this non-ad links:
http://leechall.download/go/aHR0cDovL2xpbmtzaHJpbmsubmV0Lzlsejc3
http://leechall.download/thankyou/5ZTXABMPECWV
http://prem.link/dl.php?id=4796546
Please try to block them.

**Comment by BlazDT** [comment]
Second site prem.link's download link is just reverting back to the same page. Fake download site?
Fixed leechall.download.

**Comment by oleedd** [comment]
It is need to be sign in/registred to download prem.link file or even every such link is working only for the one who generated it. Is it possible to block this 15 seconds?

**Comment by oleedd** [comment]
It is need to press Login/Register button. Then Login/Register pop-up.
https://prnt.sc/j419g3
Year. It works. Thanks. AdGuard can do wonders.

**Comment by BlazDT** [comment]
Thanks for checking, added the rule to Annoyance filter.

**Comment by oleedd** [comment]
hhhh
