### ISSUE TITLE
www.urldecoder.org

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#14665]
[https://www.urldecoder.org/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.urldecoder.org%2F)

 Остатки: `urldecoder.org##.banner_right`

<details><summary>Screenshot's:</summary>

![2018 04 11-1](https://user-images.githubusercontent.com/17948007/38639054-c8088fcc-3dd8-11e8-9b0b-cb57b23f6b4f.png)
----------
![2018 04 11-2](https://user-images.githubusercontent.com/17948007/38639070-d55b4372-3dd8-11e8-98a3-15e10f910ecc.png)
</details>

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.8.6 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by XX-J** [comment]
[https://www.strreverse.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.strreverse.com/)

 Остатки от рекламы.

 Предлагаю переделать правило для этих сервисов, добавив недостающие домены и унифицировав селектор.

 Все домены этих сервисов (в порядке перечисления на страницах этих сервисов):
```
https://www.base64decode.org/
https://www.base64encode.org/
https://www.urldecoder.org/
https://www.urlencoder.org/

https://www.pdfmrg.com/
https://www.pdfspl.com/
https://www.pwdgen.org/
https://www.numgen.org/

https://www.strlength.com/
https://www.strreverse.com/
https://www.uglifycss.com/
https://www.prettifycss.com/

https://www.uglifyjs.net/
https://www.prettifyjs.net/
```

 Предлагаемое правило:
`base64decode.org,base64encode.org,urldecoder.org,urlencoder.org,pdfmrg.com,pdfspl.com,pwdgen.org,numgen.org,strlength.com,strreverse.com,uglifycss.com,prettifycss.com,uglifyjs.net,prettifyjs.net##[class^="banner_"]`

<details><summary>Screenshot's:</summary>

![2018 09 19-2](https://user-images.githubusercontent.com/17948007/47947079-d760d980-df26-11e8-9ffe-531dcc3c3f04.png)
----------
![2018 09 19-3](https://user-images.githubusercontent.com/17948007/47947084-ecd60380-df26-11e8-8e6c-36f8e051bc4a.png)
</details>

**Comment by Alex-302** [comment]
ок

**Comment by XX-J** [comment]
...и добавить два недостающих домена, из списка выше:
```
https://www.strlength.com/
https://www.strreverse.com/
```
