### ISSUE TITLE
Yahoo Weather app - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#1466]
http://forum.adguard.com/showthread.php?9017-Yahoo-Weather-App-not-filtered-(sponsored-ads)

**Comment by Alex-302** [comment]
don't see ads. Asked for the log

**Comment by evgeniy-ADG** [comment]
XCP-410-14952
![image](https://cloud.githubusercontent.com/assets/15856304/15481782/f33623a2-2134-11e6-910d-b79ebe55b67a.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
здесь логи похоже не помогут. Нужно дать новую бету и попросить записать HAR файлы. Запись включается в низкоуровневых настройках. По окончании записи опцию нужно выключить. Результат хранится рядом с папкой логов Адгрда.
Перед записью приложение надо прибить.

**Comment by evgeniy-ADG** [comment]
окей, завтра освоим и ответим.

**Comment by Alex-302** [comment]
если что, этот файл можно импортировать с помощью Fiddler
Файлы в открытом виде не выкладывай, т.к. там могут быть логины/пароли и прочее. Лучше в скайп

**Comment by evgeniy-ADG** [comment]
У меня не повторилось, пользователю я фиддлер давать не буду, никто не станет с ним возиться.

**Comment by ameshkov** [comment]
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/65/9/how-to-get-har-http-archive-files-from-android-device

**Comment by evgeniy-ADG** [comment]
ждем

**Comment by Alex-302** [comment]
нет новостей?

**Comment by evgeniy-ADG** [comment]
не отвечают.

**Comment by Alex-302** [comment]
печально
