### ISSUE TITLE
indiegogo.com

### ISSUE THREAD

**Issue by uuqqzz** [AdguardTeam/AdguardFilters#147016]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.indiegogo.com/projects/petsnowy-the-innovative-self-cleaning-litter-box#/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

`||telemetry.transcend.io^`

<details><summary>Screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/229088618-04821a48-db06-4627-9b9a-641b5c24ae3b.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
