### ISSUE TITLE
Ad leftovers on bilibili.com

### ISSUE THREAD

**Issue by shz42** [AdguardTeam/AdguardFilters#147194]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.48.2

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

www.bilibili.com

### What filters do you have enabled?

AdGuard Chinese filter

### Add your comment and screenshots

1.
On www.bilibili.com, the current filter rules:
```
bilibili.com#?#.bili-video-card > div.bili-video-card__wrap > a[href*="cm.bilibili.com"][data-target-url]:not([data-target-url*=".bili"]):upward(2)
bilibili.com#?#.bili-video-card:has(> .bili-video-card__wrap > .bili-video-card__info > .bili-video-card__info--right > .bili-video-card__info--tit > a > [class^="bili-video-card__info--ad"])
bilibili.com#?#.eva-extension-feed-body > div:not([class], [id]):has(> .bili-video-card > .bili-video-card__wrap > .bili-video-card__info > .bili-video-card__info--right > .bili-video-card__info--tit > a > [class^="bili-video-card__info--ad"])
bilibili.com#?#.bili-video-card:has(> .bili-video-card__wrap > .bili-video-card__info > .bili-video-card__info--right > .bili-video-card__info--tit > a > .bili-video-card__info--creative-img)

bilibili.com##.bili-video-card__wrap > a[href^="http"]:not([href*=".bilibili.com/"])

bilibili.com##a[href*="cm.bilibili.com"][data-target-url*="gaoneng.bilibili.com"]
bilibili.com##a[href*="cm.bilibili.com"][data-target-url*="gaoneng.bilibili.com"] + .bili-video-card__info
bilibili.com##a[href*="cm.bilibili.com"][data-target-url]:not([data-target-url*=".bili"])
bilibili.com##a[href*="cm.bilibili.com"][data-target-url]:not([data-target-url*=".bili"]) + .bili-video-card__info
```
from `AdGuard Chinese filter` produces ad leftovers occupying space (as in the screenshots 1,2). Also, rules 2-4 do not work with the new version of the website.

This can be fixed by adding the following rule (with the previous ones removed).
```
bilibili.com##.bili-video-card__wrap > a[href*="cm.bilibili.com"]:upward(.bili-video-card)
```

2. Screenshots
<details><summary>Screenshot 1:</summary>
Previous rules enabled, DOM inspector on
<img width="654" alt="屏幕截图 2023-04-01 202632" src="https://user-images.githubusercontent.com/63167402/229329633-ca431d4f-cb29-42dc-9cf2-1847bf82adc4.png">
</details>

<details><summary>Screenshot 2:</summary>
Previous rules enabled, DOM inspector off
<img width="647" alt="屏幕截图 2023-04-01 202637" src="https://user-images.githubusercontent.com/63167402/229329638-5fe942a8-2f48-4f0b-a227-54d34b353da5.png">
</details>

<details><summary>Screenshot 3:</summary>
Suggested rule enabled, previous rule disabled, DOM inspector on
<img width="649" alt="屏幕截图 2023-04-01 201930" src="https://user-images.githubusercontent.com/63167402/229329639-990d2bcf-b7f3-422d-8b6e-bb1242cf3f75.png">
</details>

<details><summary>Screenshot 4:</summary>
Suggested rule enabled, previous rule disabled, DOM inspector off
<img width="652" alt="屏幕截图 2023-04-01 201936" src="https://user-images.githubusercontent.com/63167402/229329642-dc4b483e-e8b5-40b4-a493-43fc2a771c07.png">
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Reverted

**Comment by Alex-302** [comment]
removed `bilibili.com#$?#.container > div[class*="-card"]:has(div[style="display: none !important;"]) { remove: true; }`
