### ISSUE TITLE
Anti-right click/copy on truelovejapan.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#147184]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.48.3b4

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.truelovejapan.com/blog/atm-machine-japan/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment>

On the website, whenever you try to copy or right click, it doesn't work. I fixed it by using these filters:
`truelovejapan.com##+js(aopr, disable_copy)`
`truelovejapan.com##+js(aopw, document.oncontextmenu)`

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
Too low visitors: https://www.similarweb.com/website/truelovejapan.com/#traffic
