### ISSUE TITLE
bulinews.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#147258]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://bulinews.com/news/16875/pavard-dedicates-over-dortmund-nagelsmann

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Legitimate URL Shortener

### Add your comment and screenshots

Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/29574622/229365199-6c90fbe8-76c9-4479-a8aa-ab0610702dd3.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
```adb
###hp_cc
```
