### ISSUE TITLE
express.co.uk

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#147266]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.express.co.uk/sport/tennis/1753909/Wimbledon-Elena-Rybakina-Russia-ban/amp

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Anti-Facebook List, Legitimate URL Shortener

### Add your comment and screenshots

1. It's the amp version of the page
2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/29574622/229370597-884048e6-a244-4705-ab69-523a7a8948cc.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
Hello @SeriousHoax
I can't reproduce this issue. This element is hidden by `##.ampad` from the base filter.

**Comment by SeriousHoax** [comment]
> Hello @SeriousHoax I can't reproduce this issue. This element is hidden by `##.ampad` from the base filter.

Sorry, you are right. But doesn't work with Optimized filters. Can it be made compatible with optimized?
