### ISSUE TITLE
Merge multiple `example.js` rules into one rule instead of duplicate rules

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdguardFilters#147374]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Hi, why the `/example.js` multiple rules are still not merged into a single rule when there are concatenation rules? Is there any reason for this? It would be good to get knowledge.

For example:

```Adblock Filter List
/example.js$domain=example1.com|example2.net|example3.org
```

These are a few existing examples in filter list, see:

<details><summary>vast.js duplicate rules</summary>
<p>

1. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L1667
2. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L3685
3. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L4504
4. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L4505
5. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L4508
6. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L5145
7. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L6091
8. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L6221
9. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L6929
10. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L7029
11. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L7144
12. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L7387
13. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L7802
14. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L8158
15. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L8160
16. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L8173
17. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L8609
18. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L8725
19. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L10363
20. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L10397

</p>
</details>

<details><summary>func.js duplicate rules</summary>
<p>

1. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L10880
2. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L10881
3. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L10886
4. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L10887
5. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L10897
6. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L10898
7. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L10986
8. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L11774
9. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L11775

</p>
</details>

<details><summary>customscript.js duplicate rules</summary>
<p>

1. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L363
2. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L7122
3. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L7497
4. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L7546
5. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L7747
6. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L7923
7. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L8416

</p>
</details>

<details><summary>full-page-script.js duplicate rules</summary>
<p>

1. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L6242
2. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L6285
3. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L6487
4. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L6893
5. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L6978
6. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L7117
7. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L10660

</p>
</details>

<details><summary>tools.js duplicate rules</summary>
<p>

1. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L8353
2. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L9516
3. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L11310
4. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L11413
5. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L11712
6. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L12213
7. https://github.com/AdguardTeam/AdguardFilters/blob/52dce3aa8e39a89fdac91ef5936e9d525d379a66/BaseFilter/sections/specific.txt#L13631

</p>
</details>

There are more of this in the filter list.

### Proposed solution

In the title

**Comment by krystian3w** [comment]
Well I disagree, if we don't have a `domain=` it's really impossible to know if someone isn't pirating the file from a source other than a legitimate CDN.
