### ISSUE TITLE
hket.com mobile app popup

### ISSUE THREAD

**Issue by outflank8553** [AdguardTeam/AdguardFilters#147379]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

https://inews.hket.com/article/3498981/%E3%80%90%E6%B8%AF%E8%82%A1%E5%B8%82%E6%B3%81%E3%80%91%E7%BE%8E%E5%9C%98%E8%B7%8C4-%E3%80%81%E9%98%BF%E9%87%8C%E8%B7%8C%E9%80%BE3-%E3%80%80%E3%80%8C%E4%B8%AD%E5%AD%97%E8%82%A1%E3%80%8D%E9%80%86%E5%B8%82%E5%8F%88%E7%82%92%E4%B8%8A%E3%80%80%E6%81%92%E6%8C%87%E5%8D%8A%E6%97%A5%E8%B7%8C131%E9%BB%9E%EF%BC%88%E4%B8%8D%E6%96%B7%E6%9B%B4%E6%96%B0%EF%BC%89?mtc=20037

### What filters do you have enabled?

AdGuard Base filter, AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/129025690/229691714-2f175ef5-ec5d-453f-be87-fb459855d1d4.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/147380
