### ISSUE TITLE
Any ".xyz/login|$document" caught by JP filter

### ISSUE THREAD

**Issue by iamspark1e** [AdguardTeam/AdguardFilters#147387]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://example.xyz/login

### What filters do you have enabled?

AdGuard Japanese filter

### Add your comment and screenshots

1. The filter rule ".xyz/login|$document" seems too widely to make normal login unaccessible. ".xyz" tld should not be all blocked .

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/29349655/229746755-4d2adab0-35df-40fb-bf87-eda8ac455486.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/229748318-c107e82c-54e7-4d5b-b804-9cb3dc0e6922.png)

We need a real site. Any generic rule may break any site) We can't just remove the rule.

**Comment by iamspark1e** [comment]
For example, this url: https://tickettool.xyz/login

**Comment by iamspark1e** [comment]
And this, which is found by search engine: https://academicbridge.xyz/login

**Comment by Alex-302** [comment]
Ok, removed https://github.com/AdguardTeam/AdguardFilters/commit/1a7673244032ccf772817bec50ee33be61f20aee
@Yuki2718
