### ISSUE TITLE
New trackers

### ISSUE THREAD

**Issue by tomac4t** [AdguardTeam/AdguardFilters#147405]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

N/A

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

N/A

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

1. <comment>A tracker list collected by AdguardHome.

- [ ] `uplog.inews.qq.com`
- [ ] `log1.wtlogin.qq.com`
- [ ] `log.qvb.qcloud.com`
- [ ] ~`tracker-01.qvb.qcloud.com`~ probably p2p tracker
- [ ] `log.tpns.gz2.tencent.com`
- [ ] `trace.zhiyan.tencent-cloud.net`
- [ ] `kit-device-log-1252363965.cos.ap-beijing.myqcloud.com`
- [ ] `sp1.baidu.com`
- [ ] `sp2.baidu.com`
- [x] `sp3.baidu.com`
- [ ] `norma-external-collect.meizu.com`
- [ ] `trace.hjq.komect.com`
- [ ] `log.iflytek.com`
- [ ] `log.voicecloud.cn`
- [ ] `aads.shuzilm.cn`
- [ ] `tracker.ai.xiaomi.com`
- [ ] `incoming.telemetry.mozilla.org`
- [ ] `adxlog-adnet.vivo.com.cn`
- [ ] `user-analysis.7moor.com`

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. We need sources. We can't just block domains on first request.

**Comment by Alex-302** [comment]
Ok, checked all domains and added the ones I found information about.
