### ISSUE TITLE
twitter.com: mobile app button

### ISSUE THREAD

**Issue by outflank8553** [AdguardTeam/AdguardFilters#147515]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.53

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

https://mobile.twitter.com/***/status/***

### What filters do you have enabled?

AdGuard Base filter, AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/129025690/230265278-fc3b28e3-4303-4e07-b599-5de28ebab45b.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Direct URL to check:

`https://mobile.twitter.com/CMONGames/status/1643745382508142597`

**Comment by Alex-302** [comment]
Does not look annoying.
