### ISSUE TITLE
dramaworldhd.co - showing ads in this site

### ISSUE THREAD

**Issue by MayaBi7** [AdguardTeam/AdguardFilters#147647]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard DNS

### AdGuard version

4.1.55

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

dramaworldhd.co

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Annoyances filter, EasyList, Fanboy's Annoyances, Fanboy's Social Blocking List

### Add your comment and screenshots

![IMG_20230407_163742](https://user-images.githubusercontent.com/96541364/230598861-3931265a-26c6-42f6-9f64-3e347134b190.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Can't reproduce without AdGuard.
Please upload a saved page as ZIP.
