### ISSUE TITLE
chkaja.com

### ISSUE THREAD

**Issue by 462** [AdguardTeam/AdguardFilters#147615]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.48.4

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://img.chkaja.com

### What filters do you have enabled?

AdGuard Chinese filter

### Add your comment and screenshots

1. <comment>
`chkaja.com` is a personal blog domain. And `img.chkaja.com` is an image hosting domain. Block rules in filter make website can't show properly.  #146588

2. Screenshots
<details><summary>Screenshot 1:</summary>

https://img.chkaja.com/5b67ffb95281096e.png</details>

<details><summary>Screenshot 2:</summary>

![](https://img.chkaja.com/a8ebca1aaca86f01.png)</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
We do not block it
![image](https://user-images.githubusercontent.com/8361299/230591153-94d293ec-e285-4295-818f-58e239595b55.png)
