### ISSUE TITLE
ign.com

### ISSUE THREAD

**Issue by uuqqzz** [AdguardTeam/AdguardFilters#147729]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.55

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://tr.ign.com/god-of-war-ragnarok/115683/news/god-of-war-ragnarokun-new-game-plus-modu-oyuncuyla-bulustu

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

Tracking server `||brainsland.com^$third-party`

<details><summary>Screenshot:</summary>

![resim](https://user-images.githubusercontent.com/110184059/230699283-88a2f691-390b-42d3-936b-704c21d86109.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I don't see the request on my end.
