### ISSUE TITLE
Crash reporter blocked

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#147853]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4 0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

Errlogos.umeng.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

errlogos.umeng.com^ appears in log i looked it up and it is used for crash reporting. Can we remove it

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
@Alex-302

**Comment by Alex-302** [comment]
Not sure about that. I don't trust them.
