### ISSUE TITLE
mail.yahoo.com [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#14781]
**Site**: https://mail.yahoo.com/d/folders/1

**Issue**: Please remove the adblock message on the page.

**Screenshot**: http://prntscr.com/j588o9

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.181 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by BlazDT** [comment]
Can't register due to mobile phone requirement. The virtual numbers I found online are sadly blocked :(

We don't support this number, provide another one.

@AdamWr please check.

**Comment by Nzzyme** [comment]
Ok, let me see if I can create a test account for you. In the mean time, @AdamWr pls check

**Comment by AdamWr** [comment]
I can't reproduce it, but on my end this website looks different.
<details><summary>Screenshot</summary>

![yahoo](https://user-images.githubusercontent.com/29142494/38805123-00148354-4175-11e8-9c75-e505e6570d0e.png)

</details>
<br>

Could you please open filtering log then open yahoo mail and make a screenshot with all blocked requests?

**Comment by Nzzyme** [comment]
Here you go

http://prntscr.com/j86hzd
http://prntscr.com/j86i3z
http://prntscr.com/j86i7j

After I opened Filtering Log and then when I refreshed the page to capture the requests, I did not see the adblock message.

**Comment by AdamWr** [comment]
Ok, thank you, but unfortunately I don't see anything interesting.

It's difficult to fix it as I can't reproduce it, but could you please check this rule:
`@@||mail.yahoo.com^$generichide`

**Comment by Nzzyme** [comment]
@AdamWr Tried the rule and I am still seeing the adblock message.

**Comment by BlazDT** [comment]
@Nzzyme 
If it is still happening, please write me a PM when you are free this week for a TeamViewer session, thank you.

**Comment by Nzzyme** [comment]
Ok, I will. Thanks!

**Comment by Nzzyme** [comment]
Hi,

are you facing this issue? I see this message everytime I open Yahoo Mail

http://prntscr.com/kuenid

**Comment by ameshkov** [comment]
I don't see it ..

**Comment by Nzzyme** [comment]
I think this shows to only users from certain ccountries.

**Comment by TesterMan247** [comment]
Same issue is mentioned here:
https://forum.adguard.com/index.php?threads/mail-yahoo-com-anti-adblock-message.29456

Perhaps this could be of help to you guys.
Please come by and have a look.
