### ISSUE TITLE
SoundCloud app

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#147851]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4 0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.soundcloud.android

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

||events-api.soundcloud.com^
||tracker.samplicio.us^
||turncdn.com^ (Same as turn.com which is in blocklist)

These take a while to show up in log. Takes listening to quite a few songs 

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
Also is there a way to see whay s.cdnsynd.com is i think its used for ads or tracking

**Comment by Alex-302** [comment]
i1.sndcdn.com is their CDN.

**Comment by jordanswrld94** [comment]
> i1.sndcdn.com is their CDN.

Thanks. Must be non ad then

**Comment by jordanswrld94** [comment]
||pandora.com^$app=com.soundcloud.android
||p-cdn.us^$app=com.soundcloud.android

Blocking pandora and pandora cdn in soundcloud completely stops the ads. @Alex-302

**Comment by Alex-302** [comment]
I don't see these requests. Could you please record HAR file?
https://adguard.com/kb/guides/collect-har-file/#android

**Comment by jordanswrld94** [comment]
@Alex-302 https://www.filemail.com/d/rythzpsnqmamncp

Pandora.com appears at 7:58:49
P-cdn.us appears at 7:58:48

**Comment by Alex-302** [comment]
Received the file. Removed your message.

**Comment by Alex-302** [comment]
It seems default level logs - no requests.
I see HAR files, related to another site. You can record HAR for this app and send it to filters@adguard.com
