### ISSUE TITLE
outlook.live.com [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#14782]
**Site**: https://outlook.live.com/owa/?path=/mail/inbox

**Issue**: Please remove the ad on the page seen under "Other" tab in Inbox.

**Screenshot**: http://prntscr.com/j58evb

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 65.0.3325.181 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.8.6 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by BlazDT** [comment]
Only see an empty white space at that position.

Please try this rule:

`outlook.live.com##.customScrollBar > div[class] > div[class]:not([tabindex]):not([role])`

**Comment by Nzzyme** [comment]
Tried the rule but sadly does not work. Confirmed on another PC (with Win 7)
http://prntscr.com/j5gm2r

**Comment by BlazDT** [comment]
Ah, I see the difference now. You are not in Beta mode and above rule was tested for left-over in beta mode.

Please try this rule:

`outlook.live.com##div[autoid] > .customScrollBar.scrollContainer > div > div[style]:not([class]):not([id]) > div[style="height: 45px;"]:not([id]):not([class])`

So far no issue when viewing an email with email header (like we had before).

**Comment by BlazDT** [comment]
Yes. Can you please inspect the element and post a screenshot of inspect view, thank you. Sadly I can only reproduce left-overs.

**Comment by Nzzyme** [comment]
I hope this is what you are looking for. If not, can you describe how exactly should I be doing this? Thanks

![outlook](https://user-images.githubusercontent.com/6959116/38779257-74b0e92e-40e3-11e8-8f0a-58c261a0c07f.jpg)

**Comment by BlazDT** [comment]
That is strange, the element you show is part of the rule selection above. Probably the div height is different for you.

outlook.live.com##div[autoid] > .customScrollBar.scrollContainer > div > div[style]:not([class]):not([id]) > div[style*="height"]:not([id]):not([class])

If still not working, please try to scroll up a bit until you see customScrollBar.scrollContainer before the ad in code.
Strangely the code structure is different when I view the element.

**Comment by Nzzyme** [comment]
Well, I tried again and this time searched for the string "customScrollBar" as I did not get any matches with the string "customScrollBar.scrollContainer"
![capture](https://user-images.githubusercontent.com/6959116/38779806-2bf0f294-40eb-11e8-8e25-7ba60beb28af.JPG)

**Comment by BlazDT** [comment]
@Nzzyme
It seems we probably have to a teamviewer session. You can contact me in the forum "Blaz" if you are willing to do it.
If I recall @AdamWr couldn't reproduce it too :(
@Alex-302 can you please check, thank you.

**Comment by AdamWr** [comment]
Yes, I couldn't reproduce that ad even without AdGuard.

**Comment by BlazDT** [comment]
Added the rule we used in Teamviewer session.

**Comment by Nzzyme** [comment]
Thanks mate. Appreciate it!
