### ISSUE TITLE
Chase.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#147852]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4 0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

Chase.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

||measure.chase.com

Tracking pixel that appears when logged in

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
@Alex-302

**Comment by jordanswrld94** [comment]
not sure but here is the full url https://measure.chase.com/1/d/c.gif?aqet=pv&puu=&uu=&clk=&v0=appidtest&v1=&v2=https%3A%2F%2Fsecure07ea.chase.com%2Fweb%2Fauth%2Fdashboard%23%2Fdashboard%2Findex%2Findex&r=635858758

@Alex-302

**Comment by Alex-302** [comment]
Ok, please test `||measure.chase.com^` in user filter

**Comment by jordanswrld94** [comment]
Works great
