### ISSUE TITLE
filefactory.com

### ISSUE THREAD

**Issue by iSmokeMid69** [AdguardTeam/AdguardFilters#147937]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### Where is the problem encountered?

https://www.filefactory.com/file/6835cl76ipy1

### Add your comment and screenshots

Is It Possible To ByPass The 60 Second Timer ?

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Seems that it's not.
