### ISSUE TITLE
Please help me with user filters :)

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#147942]
Hello!
Can you please tell me what rule I should add to the user filter to delete (hide) from DuckDuckGo search results all sites with a certain TLD?

For example .guru.

Objective:
To make sure that sites ending with .guru do not show up in search results

[Screenshot (example)](https://user-images.githubusercontent.com/130413825/231019637-89adc502-ebdb-4e48-8e11-20521675d47e.jpeg)

[Link with request for your convenience](https://duckduckgo.com/?q=forums+.guru) 

Once again:
I need to hide EVERY result that have .guru in domain name.

looking forward for your reply!

I will be very glad if you can help me!

Platform extension

**Comment by Sergey-Lyapin** [comment]
Hello @Yfhchdtx 
These rules should do the trick:
```
duckduckgo.com#?##links > div.nrn-react-div:has(> article > div > div > a[href*=".guru/"])
duckduckgo.com#?##links > div.nrn-react-div:has(> article > div > div > a[href$=".guru"])
```
