### ISSUE TITLE
Cashapp 

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#147900]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4 0

### What type of problem have you encountered?

Missed ads or ad leftovers, Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.squareup.cash

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

uxh52u-dlsdk.appsflyersdk.com

We can add dlsdk.appsflyersdk.com without the || or -

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Unfortunately, I can't install this app. What's the problem? Please send some screenshots showing the problem and the rule applied.

**Comment by zloyden** [comment]
> We can add dlsdk.appsflyersdk.com without the || or -

You can try this
```adblock
dlsdk.appsflyersdk.com^
```

**Comment by jordanswrld94** [comment]
Yes that works

**Comment by jordanswrld94** [comment]
![Uploading Screenshot_20230410_073451_AdGuard.jpg…]()

**Comment by jordanswrld94** [comment]
![Screenshot_20230410_073451_AdGuard](https://user-images.githubusercontent.com/118186787/230902506-c352a219-39d6-4507-b991-63c75d3ef77e.jpg)

**Comment by jordanswrld94** [comment]
The problem is its unblocked. Appsflyer is an ad domain

**Comment by jordanswrld94** [comment]
> The problem is its unblocked. Appsflyer is an ad domain

Wrong domain added. Theres an appsflyersdk and an appsflyer
