### ISSUE TITLE
googleads.g.doubleclick.net [DNS Blocking]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#14800]
**Issue**: Even before I turn on mobile data or WiFi, I am seeing some activity in the Filtering Log (mostly for all DNS requests). In that list, I am seeing some requests blocked but some not blocked for the domain:

googleads.g.doubleclick.net

Why does that happen? Ideally, it should be blocked for all the matching requests. Please fix.

Screenshot: http://image.ibb.co/iXPDj7/Screenshot_20180415150108.jpg

**System**:
- Android version: 6.0.1 MMB29M
- MIUI version: MIUI Global 9.5 - Stable [ 9.5.1.0 (MHOMIEK) ]

**AdGuard Version**:
- AdGuard for Android 2.10.176

**Filters**:
English, Spyware, Social Media, Annoyances, Mobile Ads, Simplified domain names, EasyList China, Anti-Adblock Killer-Reek

**AdGuard Settings**:

- No user filter used
- Phishing & Malware Protection: Enabled
- Block ads in all apps: Enabled
- Search ads & self-promotion of sites: Disabled
- DNS Filtering enabled with DNSCrypt (Server: AdGuard DNS)
- HTTPS Filtering: Enabled
- High quality filtering: Enabled
- Filtering mode is Local VPN

**Comment by Alex-302** [comment]
We can't block all domains using DNS, because a lot of the sites will be broken, or anti-adblock scripts will be triggered.
