### ISSUE TITLE
RuTracker.org

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#1483]
В торрент-клиенте, во вкладке "трекеры", в параметре "состояние", написано: "HTTP Error 403"

Скриншот: http://puu.sh/mYxdT.png

Используется BitTorrent 7.9.5. Проблема наблюдается в релизной версии Adguard 6.

http://forum.adguard.com/showthread.php?9065

**Comment by Alex-302** [comment]
Сложно сказать, почему так. У меня всё нормально
http://imagizer.imageshack.com/img923/6263/UrAJs6.png
Пусть попробует модули по одному выключать и выкл/вкл ту раздачу.

**Comment by onega** [comment]
The challenge now is to deal with the announce is rutracker.org (any one of the many clones), the latest beta version AdGuard and uTorrent 2.0.4 (at least in my case). Internet is distributed via a router (pppoe).

**Comment by Alex-302** [comment]
> beta version AdGuard

what version?

**Comment by onega** [comment]
6.1.278.1411

**Comment by Alex-302** [comment]
Is stealth mode enabled?

**Comment by onega** [comment]
Anti-tracking enabled, option "to hide the user-agent" is activated. We just exploring this bug.

**Comment by Alex-302** [comment]
Could you provide me remote access? I can't reproduce it on my end.

**Comment by onega** [comment]
I will answer on the official forum. My nickname is Wusa.
