### ISSUE TITLE
Lomax.dk / Lomax.se - Broken (AdGuard Annoyances filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#148503]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.48.4

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.lomax.dk/
https://www.lomax.se/

### What filters do you have enabled?

AdGuard Annoyances filter

### Affected sites:
```
https://www.lomax.dk/
https://www.lomax.se/
```

### Issue:
Frozen pages / modal overlay / broken functions.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **AdGuard Annoyances filter**

### Problem rules:
```
~excellent-hemd.de,~excellent-hose.de,~engie-energie.nl###cookieModal
||policy*.cookieinformation.com^$third-party
```

### Note:
At first glance, only that cosmetic rule seems to cause issues.
However, several problems will occur, due to that network rule as well..
E.g. never-ending animations when adding items to the shopping basket, and nothing appears to happen when you try to remove items from the shopping basket.

### Possible fix:
```
- ~excellent-hemd.de,~excellent-hose.de,~engie-energie.nl###cookieModal
+ ~excellent-hemd.de,~excellent-hose.de,~engie-energie.nl,~lomax.dk,~lomax.se###cookieModal

- @@||policy.cookieinformation.com/uc.js$domain=jysk.nl
+ @@||policy.cookieinformation.com/uc.js$domain=jysk.nl|lomax.dk|lomax.se
```

### Temp fix:
```
lomax.dk,lomax.se#@##cookieModal
@@||policy.app.cookieinformation.com/uc.js$domain=lomax.dk|lomax.se
```

### Other problem filters:
* **I don't care about cookies** _(@kiboke)_
`policy.app.cookieinformation.com$domain=~kartor.eniro.se|~kart.gulesider.no|~kort.degulesider.dk|~map.krak.dk|~altibox.no|~babysam.dk|~elkjop.no|~minaftale.dk|~skousen.dk|~skousen.no|~whiteaway.com|~whiteaway.no|~whiteaway.se|~dvdoo.dk`

--

### System info:
* OS/version: Windows 10 Pro 22H2 (x64)
* Browser/version: LibreWolf v112.0-1 (x64) [Tracking Protection = Standard]
* Adblock Extension/version: uBlock Origin v1.48.4

### Privacy

- [X] I agree to follow this condition

**Comment by kiboke** [comment]
@THEtomaso I don't see anything broken when IDCAC filter list is active.

**Comment by THEtomaso** [comment]
@kiboke:
Read what I wrote in the first post, under "**Note**".

**Comment by kiboke** [comment]
@THEtomaso thanks, I understand now. It will be fixed in IDCAC today.
