### ISSUE TITLE
Anti-adblock at jp.dk

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1485]
http://jyllands-posten.dk/
![screen shot 2016-02-08 at 4 55 45 pm](https://cloud.githubusercontent.com/assets/14153331/12888880/d1d9641a-ce84-11e5-8095-c732cee699f1.png)

**Comment by Alex-302** [comment]
added to English
@@||jyllands-posten.dk/js/ads.js

**Comment by Bohdan-SUP** [comment]
@Alex-302  it's back there. Could you check again.

**Comment by Alex-302** [comment]
I don't see antiadblock. Could you check again?:)

**Comment by evgeniy-ADG** [comment]
http://jyllands-posten.dk/

![image](https://cloud.githubusercontent.com/assets/15856304/17806978/6460cabc-6610-11e6-8344-ce5566a7cfc0.png)

<details>
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:8 Name: Dutch filter Url: http://adguard.com/ru/filter-rules.html?id=8
FilterId:101 Name: EasyList Url: https://easylist-downloads.adblockplus.org/easylist.txt
FilterId:109 Name: EasyList Italy Url: https://easylist-downloads.adblockplus.org/easylistitaly.txt
FilterId:121 Name: void.gr Url: http://www.void.gr/kargig/void-gr-filters.txt
FilterId:205 Name: Schacks Adblock Plus liste Url: http://adblock.schack.dk/block.txt
FilterId:0 Name: User filter Url: no_url
FilterId:14 Name: Annoyances filter Url: http://adguard.com/ru/filter-rules.html?id=14

**Comment by Alex-302** [comment]
fixed
