### ISSUE TITLE
Add new services in Spyware filter list

### ISSUE THREAD

**Issue by VicktoriaF** [AdguardTeam/AdguardFilters#14853]
В браузерном расширении Adguard есть фильтр "Фильтр счетчиков и систем аналитики", который блокирует коды сервисов, отслеживающих перемещения посетителей между сайтами. 
Есть несколько сервисов, которые собирают данную информацию, и работа которых не блокируется даже при включенном фильтре. Просьба добавить их в данный список https://filters.adtidy.org/extension/chromium/filters/3.txt

Это сервисы:

- calltouch.ru (mod.calltouch)
Пример сайта с кодом: http://10perevodov.ru/

- roistat.ru (cloud.roistat или collector.roistat собирают информацию)
Пример сайтов с кодом: http://10perevodov.ru/ и http://14sound.ru/

- calltracking.ru (cc.calltracking.ru)
Пример сайта с кодом: http://100audit.ru/

- mango-office.ru (dct.mango-office.ru или widgets.mango-office.ru) 
Пример сайтов с кодом: https://100fabrik.ru/ и https://100point.ru/

**Comment by Alex-302** [comment]
Заблокировал.

**Comment by VicktoriaF** [comment]
Добрый день! Большое спасибо!

**Comment by VicktoriaF** [comment]
Здравствуйте! 
Подскажите, а почему вы отнесли calltouch в Annoyances Filter, а не в Spyware?

**Comment by Alex-302** [comment]
Потому, что это виджет обратной связи. Подобные вещи блокируем в фильтре раздражителей.
Заблокировал запрос с аналитикой.

**Comment by VicktoriaF** [comment]
На самом деле все эти сервисы предлагают коллтрекинг + виджеты (чат, обратный звонок). Только некоторые из них разделяют коды, например, Манго, который для коллтрекинга сделал отдельный код  dct.mango-office.ru, а другие - нет. У Calltouch код не разделен, насколько я знаю, и mod.calltouch используется при подмене номеров, и при добавлении виджетов на сайт. Если устанавливается коллтрекинг, то переходы посетителей на сайты в любом случае отслеживаются.
