### ISSUE TITLE
ikandy.fun

### ISSUE THREAD

**Issue by Karmylr** [AdguardTeam/AdguardFilters#148568]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.12

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://ikandy.fun/vodplay/107281-1-1/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment>
When entering this page for the first time, a pop-up window will appear. It can be simulated by clearing webpage cookies. Rule: ikandy.fun#%#//scriptlet('set-constant', 'layer.open', 'undefined')
2. Screenshots
<details><summary>Screenshot 1:</summary>
![image](https://user-images.githubusercontent.com/69903376/232424839-c1165e59-52d3-4ace-8baf-c0cc6e4ffaec.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Unfortunately, the site does not open with different IPs on my end.
Seems that the native Chinese IP is required or another.
Can you translate what is written in the window?

**Comment by zloyden** [comment]
According to the translation above, it's better not to block it - a useful popup. If the rule above works fine, you can keep it in User rules.
Anyway, thanks for your participation!
