### ISSUE TITLE
Add ExperimentalNorwegianList to the list of subsciptions

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#14877]
https://github.com/DandelionSprout/adfilt/blob/master/ExperimentalNorwegianList.txt

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #48](https://github.com/AdguardTeam/FiltersRegistry/issues/48) via [**ZenHub**](https://www.zenhub.com/)
