### ISSUE TITLE
Unhidden empty ad placeholder

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#148829]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.48.9rc1

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

http://neonheightsservers.com/

### What filters do you have enabled?

AdGuard Base filter, EasyList

### Add your comment and screenshots

1. <comment>
On neonheightsservers.com, there is an unhidden ad placeholder on the right side. I was able to hide it with `neonheightsservers.com##.well:has(ins.adsbygoogle)`

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot from 2023-04-19 17-42-02](https://user-images.githubusercontent.com/89158249/233207003-0b8b9f67-690d-40db-83f5-fc633fa6ab47.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
Unfortunately, the reported issue does not satisfy our [filters policy](https://kb.adguard.com/en/general/adguard-filter-policy).
The site has too little traffic.

Please add to user rules:
`neonheightsservers.com#?#.sidebar > div.well:has(> ins.adsbygoogle)`
