### ISSUE TITLE
Kick.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#148819]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://kick.com/video/c4dca658-ce3f-4d11-b030-fed31608c006

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

||player.stats.live-video.net^

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Cannot reproduce on the page. Could you please attach a screenshot?

**Comment by jordanswrld94** [comment]
![Screenshot_20230421_122903_AdGuard](https://user-images.githubusercontent.com/118186787/233698703-8fbaf587-cc20-4625-9e54-30615e057d43.jpg)

**Comment by jellizaveta** [comment]
@jordanswrld94 If blocked in the user rules, is nothing broken?
