### ISSUE TITLE
amazon.*

### ISSUE THREAD

**Issue by recursiveGecko** [AdguardTeam/AdguardFilters#148958]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

AdGuard URL Tracking filter 2.0.4.75

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://amazon.com https://amazon.de https://amazon.co.uk & others

### What filters do you have enabled?

AdGuard URL Tracking filter

### Add your comment and screenshots

AdGuard URL Tracking filter lists strips the `smid` parameter from Amazon URLs. The `smid` parameter on Amazon sites represents the seller ID. Removing this parameter subtly breaks navigation on product pages with multiple sellers, automatically redirecting the user to the "default" seller/buy box rather than to the specific one the user had clicked on. 

This breaks the functionality of some external sites (e.g. price tracking tools) that direct the user to a product page with a specific seller ID because they've found that product to be in stock at a certain price by that specific seller.

This is most easily reproduced by browsing to a product page, visiting the "Other sellers" section, adding another seller's product to the cart, navigating to the cart and then clicking on the line item of that product (remember the seller name and price).

Normally the site would take you back to the product page, with the `smid` parameter matching the product in your cart, which would present you with the buy box and seller information of the product that you clicked on, but since AdGuard filters remove this parameter, the user ends up on the default product page.

Example URLs:
https://www.amazon.com/dp/B08J4HJ98L (default/preferred seller)
https://www.amazon.com/dp/B08J4HJ98L?smid=A26EKWRR8KY4BH (same product, different seller)
https://www.amazon.com/dp/B08J4HJ98L?smid=AIIAYKZQOBT02
https://www.amazon.com/dp/B08J4HJ98L?smid=A14EEANAI4EN1Q

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Thanks, removed.
