### ISSUE TITLE
Parental control false positive for firebase-settings.crashlytics.com

### ISSUE THREAD

**Issue by spetryjohnson** [AdguardTeam/AdguardFilters#148971]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

0.107.29

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome, Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

firebase-settings.crashlytics.com

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

Using Adguard Home on Opnsense, I see lots of blocked traffic under "adult websites" that looks to be a FP from parental control

![image](https://user-images.githubusercontent.com/275393/233626123-bc6eef9a-884a-4f01-9e8e-b7c1f28a7537.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Will be fixed.
