### ISSUE TITLE
Game pass

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#149005]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.gamepass

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

Mobile.events.data.microsoft.com
Browser.events.data.microsoft.com

These can be blocked safely.

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
The only events one that is problematic is self.events.data.microsoft.com these two are fine.

**Comment by jordanswrld94** [comment]
@Sergey-Lyapin

**Comment by Alex-302** [comment]
MS apps **will** be broken.
