### ISSUE TITLE
mail.proton.me

### ISSUE THREAD

**Issue by joshlawton** [AdguardTeam/AdguardFilters#149007]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard for Mac

### AdGuard version

2.10.0.1272

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://mail.proton.me

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Widgets filter, AdGuard Other Annoyances filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Block Push API, Block Location API

### Add your comment and screenshots

1. Proton Mail shows a sticky ad at the top of a user's list of messages.
2. Adding `mail.proton.me##div.bg-promotion` does not hide it.

3. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="766" alt="image" src="https://user-images.githubusercontent.com/453423/233716018-e120d40f-199f-45c1-9e5c-5e3ec06530b7.png">

</details>

<details><summary>Screenshot 2:</summary>

<img width="537" alt="image" src="https://user-images.githubusercontent.com/453423/233716608-e5588103-f472-4103-943c-10077661a80c.png">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by TinnyNeko** [comment]
This is what I use to block it you could give it a try.
mail.proton.me##div.flex.bg-promotion.relative:nth-child(2)

**Comment by joshlawton** [comment]
> This is what I use to block it you could give it a try. `mail.proton.me##div.flex.bg-promotion.relative:nth-child(2)`

Didn't work for me :(

**Comment by krystian3w** [comment]
You should use Safari WebExtension do this:

https://github.com/AdguardTeam/HttpsExclusions/blob/ecc4db061ebe183e08d8cae1c7d9015d156c9c22/exclusions/sensitive.txt#L9

https://github.com/AdguardTeam/HttpsExclusions/commit/346cb7191f327e5dfdc0137e4ca9db15f1328ecb

https://adguard.com/adguard-safari/overview.html

**Comment by Alex-302** [comment]
proton.me is in HTTPS exclusion, so cannot be filtered by apps.
But you may remove it.
