### ISSUE TITLE
poopymcbutt.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#149245]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.49.1b5

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.poopymcbutt.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

1. <comment>
`poopymcbutt.com###flex-container > div:has(ins.adsbygoogle)`

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot from 2023-04-24 18-18-41](https://user-images.githubusercontent.com/89158249/234128892-cd61e41e-baff-4061-b62f-a44eb6c27a96.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Unfortunately, the reported issue does not satisfy our [filters policy](https://kb.adguard.com/en/general/adguard-filter-policy). The website has low visitors.
Please add this rules 
```
poopymcbutt.com#?##flex-container > div:has(ins.adsbygoogle)
poopymcbutt.com###GDPR
```
to the User Rules.
