### ISSUE TITLE
usatoday.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#149329]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.49.1b7

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.usatoday.com/videos/news/have-you-seen/2021/05/05/huge-hairy-spider-forces-australian-woman-face-fears/4953588001/

### What filters do you have enabled?

AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>
The filter list causes the entire article to be hidden. Caused by `usatoday.com##div[class]:has(> aside[aria-label="advertisement"])` in AdGuard Mobile Ads

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot from 2023-04-25 18-48-56](https://user-images.githubusercontent.com/89158249/234424184-6d8ab66f-6495-4d32-9b1d-a63280e1f98a.png)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
@zloyden you added the rule here: https://github.com/AdguardTeam/AdguardFilters/issues/148066
Cannot find the element which should be hidden, therefore disabled rule. Please check and modify rule if you still see it, thank you.

**Comment by Sonic5435325** [comment]
@BlazDT Thanks. Seems to be working fine now.

**Comment by zloyden** [comment]
@BlazDT I have modified the rule, it shouldn't affect this page.

> Cannot find the element which should be hidden

It was on the mentioned task.

@Sonic5435325 it shouldn't affect uBO. If you use AdGuard Mobile Ads on desktop, you should disable the filter.
