### ISSUE TITLE
Etsy Cosmetic Filtering with Ublock

### ISSUE THREAD

**Issue by Anvillior** [AdguardTeam/AdguardFilters#149330]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Filter

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.etsy.com/search?q=anime%20pins&ref=search_bar

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1.  ##div[data-behat-search-results-lg] .listing-link.logged:not([data-shop-id]) seems to make it block search results, but not ads.

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>
https://imgur.com/a/GTyT936

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Removed problematic rule.
Ad removable not so easy without JS due to "fake" ads which are hidden via transform css.
@AdamWr please check.

**Comment by AdamWr** [comment]
As far as I understand, it's related to - https://github.com/AdguardTeam/AdguardFilters/issues/148111#issuecomment-1513134079 (I mean "ads").
>Just items, promoted by sellers. We should not remove them from results. They are not duplicated.

**Comment by BlazDT** [comment]
If a seller pays extra to have a higher visibility, they are ads and should be removed.

**Comment by AdamWr** [comment]
This rule seems to works fine on my end:
```adblock
etsy.com#?#div[data-search-results] .wt-list-unstyled .wt-text-caption > span[class]:contains(/Ad[\s\S].*by Etsy seller/):matches-css(display: inline-block):upward(.wt-list-unstyled)
```
but I'm not sure if it should be added - https://github.com/AdguardTeam/AdguardFilters/issues/148111#issuecomment-1513134079
@Alex-302 Could you please take a look?

**Comment by BlazDT** [comment]
The text is localized though.

**Comment by Alex-302** [comment]
> If a seller pays extra to have a higher visibility, they are ads and should be removed.

No. You will remove a part of items. OLX has same feature, and promoted items may be useful if you want to byu for example a used device. "Promoted" is not equal to "higher price".
