### ISSUE TITLE
Add simpleanalyticscdn.com to tracking_servers.txt

### ISSUE THREAD

**Issue by catleeball** [AdguardTeam/AdguardFilters#149538]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Analytics tracker *Simple Analytics* isn't currently blocked by the trackers filter.

Their [documentation](https://docs.simpleanalytics.com/script) shows the service uses `scripts.simpleanalyticscdn.com` and `queue.simpleanalyticscdn.com`.

They also suggest clients make a CNAME record pointing to `simpleanalyticsexternal.com` from the first-party domain. I'm not sure if AdGuard would block this, but I added the `simpleanalyticsexternal.com` domain too.

### Proposed solution

Proposing to add simpleanalyticscdn.com and simpleanalyticsexternal.com to the trackers filter.

I'll send a PR shortly, making this bug for tracking. I've been using the proposed filters for a few months, and haven't noticed anything breaking.

```
||simpleanalyticscdn.com^
||simpleanalyticsexternal.com^
```

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/blob/aa27afe21039a9f9de0d4200f66a6bbf97681abe/SpywareFilter/sections/tracking_servers.txt#L827

Like said Sergey-Lyapin.
