### ISSUE TITLE
hulu

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#149525]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.p

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.hulu.plus

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

ade.googlesyndication.com
s.pixsrvcs.com (tracking pixel)
cws-hulu.conviva.com (analytics domain)
ipv4.testonly.conviva.com
ipv6.testonly.conviva.com
cws.conviva.com
pr-a.ybp.yahoo.com (ad manager for yahoo)
hmi-hershey.hrzn-nxt.com (hosts Javascript claiming to be "the worlds most powerful web analytics platform)
lighthouse.edoinc.com (analytics domain)
lighthouse.edo.com (analytics domain) 
rtag.farmers.com
### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
Hulu ads load find on ad version of hulu with this blocked

**Comment by jordanswrld94** [comment]
@Sergey-Lyapin

**Comment by jordanswrld94** [comment]
What about the others? @Alex-302

**Comment by Alex-302** [comment]
Not sure about them.

**Comment by jordanswrld94** [comment]
we can block
ipv4.testonly.conviva.com and ipv6.testonly.conviva.com

**Comment by Alex-302** [comment]
No.
