### ISSUE TITLE
https://m.baidu.com - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1496]
[the link](https://m.baidu.com/from=1014019q/s?word=%E6%90%9C%E7%8B%97&sa=tb&ts=3140572&t_kt=0&ie=utf-8&rsv_t=91b1vCUACOA6qSwPakXFXuP01Zxd6BAipnPvrl3%252BVsCKkjfbcSWhTd8Fjj2toJI&rsv_pq=2225904498563202663&ss=101&t_it=1&rsv_sug4=7528&inputT=6601&oq=%26%2325628%3B%26%2329399%3B)

![image](https://cloud.githubusercontent.com/assets/15856304/12943238/a145bc76-cfe8-11e5-86d8-2edf9df81f79.png)

LGM-280-59555

**Comment by Alex-302** [comment]
Opened this url, but but the page look different - like search engine, without icons like on screenshot.

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/13815623/ff07ac90-eb93-11e5-80d2-87412f635b41.png)

http://m.baidu.com/s?from=1099b&word=%E9%AB%98%E9%93%81&s2bd=f

<details>
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.78.99 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.99 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.86 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.24.33 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.89 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.2.66 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID1 Name="EasyList" Version=1.0.54.3 Enabled=YES
ID2 Name="ABPindo" Version=1.0.0.38 Enabled=YES
ID3 Name="Bulgarian list" Version=1.0.0.6 Enabled=NO
ID4 Name="EasyList China" Version=1.0.54.24 Enabled=YES
ID7 Name="Adblock Polska" Version=1.0.0.52 Enabled=YES
ID8 Name="EasyPrivacy" Version=1.0.53.91 Enabled=YES
ID0 Name="Norsk adblockliste" Version=1.0.0.1 Enabled=YES
ID2 Name="Fanboy's Annoyances" Version=1.0.54.14 Enabled=YES
ID3 Name="Fanboy's Social Blocking List" Version=1.0.54.3 Enabled=YES
ID!5 Name="Fanboy's Enhanced Tracking List" Version=1.0.1.30 Enabled=YES
ID 5 Name="Schacks Adblock Plus liste" Version=1.0.1.22 Enabled=YES
ID 7 Name="Adblock Warning Removal List" Version=1.0.54.8 Enabled=YES
ID!1 Name="Anti-Adblock Killer | Reek" Version=1.0.1.58 Enabled=YES
ID!6 Name="Adblock polskie reguły" Version=1.0.3.34 Enabled=YES
ID!7 Name="Adblock polskie reguły cookies" Version=1.0.0.96 Enabled=YES
ID!9 Name="ChinaList+EasyList" Version=1.0.0.44 Enabled=YES
ID"0 Name="CJXsAnnoyanceList" Version=1.0.0.26 Enabled=YES

**Comment by evgeniy-ADG** [comment]
http://image.baidu.com/search/wiseala?tn=wiseala&iswiseala=1&ie=utf8&wiseps=1&word=%E8%99%8E%E9%97%A8

![image](https://cloud.githubusercontent.com/assets/15856304/14292265/09d68aec-fb70-11e5-9a3d-6f6fed593a99.png)

推广 is mean AD in china

**Comment by evgeniy-ADG** [comment]
http://pan.baidu.com/wap/link?shareid=2905397242&uk=1497151449

![image](https://cloud.githubusercontent.com/assets/15856304/14475668/d2c43d6e-010b-11e6-9559-413f35220014.png)

**Comment by Alex-302** [comment]
for
http://image.baidu.com/search/wiseala?tn=wiseala&iswiseala=1&ie=utf8&wiseps=1&word=%E8%99%8E%E9%97%A8
added to eperimental filter
```
baidu.com###search-appPromote
```

**Comment by Tetiana2020** [comment]
Seems like ads are there again.

Screenshots:
<details>

![1cf581c2910abaa963b7b9dc88d3c6bd-2](https://cloud.githubusercontent.com/assets/17504743/22614178/c97fa700-ea87-11e6-8566-b3998108e076.jpg)
![1cf581c2910abaa963b7b9dc88d3c6bd](https://cloud.githubusercontent.com/assets/17504743/22614179/ca521da2-ea87-11e6-8a4b-6f70f2127fa7.jpg)
![1cf581c2910abaa963b7b9dc88d3c6bd-4](https://cloud.githubusercontent.com/assets/17504743/22614180/cb79fb6e-ea87-11e6-9a5f-c31a2cd5066b.jpg)
![5f8602d3e9dae07049b74fd2f5bd42c8-2](https://cloud.githubusercontent.com/assets/17504743/22614181/cd0e6424-ea87-11e6-8e4f-a038d33f864f.jpg)
![1cf581c2910abaa963b7b9dc88d3c6bd-1](https://cloud.githubusercontent.com/assets/17504743/22614182/cdd70370-ea87-11e6-81a2-7834b8e1885a.jpg)
![5f8602d3e9dae07049b74fd2f5bd42c8-5](https://cloud.githubusercontent.com/assets/17504743/22614183/cea19c98-ea87-11e6-9734-6bd91ec5a298.jpg)

</details> 

Ticket: 1498577

**Comment by Alex-302** [comment]
@Tetiana2020 это скрины с превью что ли?)
