### ISSUE TITLE
Notepad

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#149803]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.ztnstudio.notepad

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

geoip.api.c0nnectthed0ts.com
checkip.amazonaws.com
metricreceiver-prod.cellrebel.com
api64.ipify.org

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not trackers.

**Comment by ramazansancar** [comment]
This is used as a helper API that returns the user's IP address. With this information, it can obtain information such as the user's approximate location and internet provider. FYI @Alex-302 @jordanswrld94

**Comment by Alex-302** [comment]
It is a public info. They know your/VPN IP in any case, and can get info about IP on their backend.

**Comment by ramazansancar** [comment]
Some data stealing systems can continue their operations by getting the first IP address (Of course, this is an exception). It could have prevented them.
