### ISSUE TITLE
Features blocked on Apple Music web player

### ISSUE THREAD

**Issue by wzxu** [AdguardTeam/AdguardFilters#149816]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

Version 2.10.0.1272 release

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://music.apple.com/

### What filters do you have enabled?

AdGuard Social Media filter

### Add your comment and screenshots

1. Rules in Social Media filter list is blocking **features**, not ads or even annoyances.

2. Screenshots
<details><summary>Screenshot 1 (filter off):</summary>

<img width="244" alt="image" src="https://user-images.githubusercontent.com/5619348/235374715-6db43277-7843-4e86-90b2-e111ffd189ed.png">

</details>

<details><summary>Screenshot 2 (filter on):</summary>

<img width="252" alt="image" src="https://user-images.githubusercontent.com/5619348/235374855-0805af3d-7247-4fc6-a858-a80f5df5afed.png">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@wzxu Hi. I don't see such buttons (logged in).

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/236196241-2e3b7867-c5ec-489e-adad-7cff09cb3363.png)


</details>

Please describe where can I found them.

**Comment by wzxu** [comment]
That's weird. They're there for every album/playlist I checked.
Could you check the DOM tree to see if they're there but perhaps already hidden by your other filters?
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/5619348/236250914-3946b132-5782-4167-84ef-43d607cbbfce.png">

**Comment by Alex-302** [comment]
@wzxu That's all

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/932452b8-d540-4cb0-b736-9b4a7f7e9387)

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/b958b4da-42ab-41b9-9ce1-19dc0835e34d)

**Comment by Alex-302** [comment]
@wzxu Just logged in using my account.

**Comment by Alex-302** [comment]
Please test in user filter

```adblock
music.apple.com#@#.songs-list-row__controls > div.songs-list-row__context-menu
music.apple.com##.contextual-menu-item > button[title="Share"]
```

**Comment by Alex-302** [comment]
> :last-child

is not a good choice.
Ok, removed that rules. Elements are not annoying.
