### ISSUE TITLE
false positive parental control for URL shortener for telegram (https://t.me/)

### ISSUE THREAD

**Issue by hw121693** [AdguardTeam/AdguardFilters#149876]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

didn't install software

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://t.me/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter

### Add your comment and screenshots

1. https://t.me/ is a link for shortened telegram URL but detected as adult content

2. Screenshots
![image](https://user-images.githubusercontent.com/15042485/235469524-6fdf1ea4-5282-4f8a-934b-beb08248ba91.png)
![image](https://user-images.githubusercontent.com/15042485/235470857-99787afe-7237-41f0-99b6-a45296412ae2.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Already fixed.
