### ISSUE TITLE
'Block WebRTC' option affects Hangouts extension

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1499]
![image](https://cloud.githubusercontent.com/assets/15856304/12944812/39663d7e-cff2-11e5-8b83-1a057966598b.png)

Здравствуйте. При включенных антибанере и антитрекинге не работает кнопка видеовызова в расширении Hangouts для Chrome. Если в настройках Adguard отключить его для Chrome, то все работает. До этого была версия 5.10. С ней подобных проблем не было.

FKS-382-32543

**Comment by Alex-302** [comment]
@evgeniy-ADG 
А попроси ссылку на расширение, а то их сам куча разных.

**Comment by evgeniy-ADG** [comment]
@Alex-302 я других кроме официального не нашел... [вот](https://chrome.google.com/webstore/detail/google-hangouts/knipolnnllmklapflnccelgolnpehhpl)

**Comment by Alex-302** [comment]
Проверь или передай такое правило
```
@@||plus.google.com/hangouts/_/CONVERSATION/$document
```
Он ломался, но не антитрекингом.

**Comment by Alex-302** [comment]
@evgeniy-ADG

**Comment by Alex-302** [comment]
Если помогло - закрывай. В фильтр добавил.

**Comment by evgeniy-ADG** [comment]
@Alex-302 У нас здесь такое:

> Здравствуйте!

1. Для версии 6.0.189.974 добавление фильтра ничего не изменило.
2. После обновления 6.0.189.984 при включенном антитрекинге (и блокировке WebRTC) заработала кнопка вызова, но стал отображаться только черный экран вместо окна с элементами управления.
3. После добавления фильтра в последнюю версию все заработало (при включенном антитрекинге и блокировке WebRTC).

На данный момент проблема решена. Спасибо.

в потом такое:

> Упс( Забыл перезагрузить Хром. После повторного открытия. Симптомы те же что и были. Помогает только снятие галки блокировать WebRTC.

**Comment by Alex-302** [comment]
передайте ещё такие правила
```
@@||plus.google.com/hangouts/$document
```
и
```
@@||plus.google.com/hangouts/
```
у меня не получается проверить с двумя аккаунтами - вызов идёт, а ответить не предлагает. Это без Адгарда.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Ну что там?

**Comment by evgeniy-ADG** [comment]
@Alex-302 Леша, это походу не расширение такое, а сайт https://hangouts.google.com/, где оконо с чатом можно вытащить куда угодно.
С правилами и с антитреккингом - работает, без правил и с антитреккингом - нет.

**Comment by Alex-302** [comment]
Ок, добавил

**Comment by Bohdan-SUP** [comment]
Проблема вернулась.
При попытке видео-звонка Hangouts просит доступ к микрофону - мы блокируем это сообщение.

**Comment by Alex-302** [comment]
Проверь такое
```
@@||plus.google.com/hangouts/$stealh
```
или в понедельник удалённо придётся смотреть.

**Comment by Bohdan-SUP** [comment]
Не могу больше повторить, уточню у юзера еще.
