### ISSUE TITLE
Incorrect blocking

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#150021]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.49.3b4

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

mariowiki.com, splatoonwiki.org, encyclopediadramatica.online, ssbwiki.com, puyonexus.com, wiki.srb2.org, runescape.wiki

### What filters do you have enabled?

AdGuard Tracking Protection filter

### Add your comment and screenshots

1. <comment>
Same as #149439 

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Ok, removed that rule.
