### ISSUE TITLE
sportbox.ru - video playback error

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1500]
http://news.sportbox.ru/Vidy_sporta/Futbol/Evropejskie_chempionaty/Angliya/spbvideo_NI589110_Zachem_Zhoze_Mourinju_nuzhen_Mu

sportbox.ru При попытке посмотреть видео - cannot load m3u8: 404 not found При отключенном Adguard видео показывает После включения Adguard просмотренные с отключенным Adguard видео показывает
![image](https://cloud.githubusercontent.com/assets/15856304/12947576/f9be0c7a-d004-11e5-9da0-3a7356ef8f12.png)
Пользовательский фильтр (пустой)

Английский фильтр

Русский фильтр

Фильтр счетчиков и системы аналитики

Фильтр виджетов социальных сетей

Экспериментальный фильтр (может в нём дело? :-) )

WWA-385-43484

**Comment by evgeniy-ADG** [comment]
у меня вот так, потому прошу вас проверить
![image](https://cloud.githubusercontent.com/assets/15856304/12947587/1ae159fc-d005-11e5-9242-20c7aef425e8.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
А что это у юзера краснеет в углу экрана?:) Пусть попробует выключить второй блокировщик.

**Comment by evgeniy-ADG** [comment]
Я и не заметил :) Написал.
