### ISSUE TITLE
HS.fi

### ISSUE THREAD

**Issue by lamtonylam** [AdguardTeam/AdguardFilters#150013]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker, Other ad blocker

### AdGuard version

,

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

hs.fi

### What filters do you have enabled?

AdGuard Base filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

The video player doesn't work with Adguard annoyances filter enabled.'
It does work when it is disabled.

https://www.hs.fi/politiikka/art-2000009558146.html

The issue appears to be this specific block filter
![image](https://user-images.githubusercontent.com/63186670/235905664-73e474e1-6ab0-4b34-8a27-9ee4dd721363.png)

![image](https://user-images.githubusercontent.com/63186670/235905548-0d6dc308-6dc5-464a-8767-e5372261f148.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@lamtonylam Please provide a url of broken page.

**Comment by lamtonylam** [comment]
https://www.hs.fi/politiikka/art-2000009558146.html

**Comment by lamtonylam** [comment]
Thank you!
