### ISSUE TITLE
Apple tv analytics

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#150003]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

4.0

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

Apple tv

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard DNS filter

### Add your comment and screenshots

metrics-config.icloud.com

Located in dns log

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Cannot find info.

**Comment by jordansworld** [comment]
@Alex-302 this is 3 years old but this domain is called to this day. its currently blocked by hagezi and has been blocked since november of 24 with no issues. think we could block it?

https://github.com/hagezi/dns-blocklists/issues/4155

**Comment by Alex-302** [comment]
A have a macbook and ipad, and I don't see this domain in my DNS logs.

**Comment by jo2dan94** [comment]
> A have a macbook and ipad, and I don't see this domain in my DNS logs.

Yeah it's only on apple tv @Alex-302

**Comment by Alex-302** [comment]
Ok, blocked.
