### ISSUE TITLE
[Windows] online-life.cc unstable site's functionality

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#1502]
Нестабильно работает сайт:

> http://www.online-life.cc
> Может загрузится нормально, а может и вот так:
> **`только фон`**
> ![2016-02-10 20-53-08 - google chrome](https://cloud.githubusercontent.com/assets/16462533/12958405/37440ccc-d03a-11e5-88ab-003a53c2d2d3.png)

Такая же ситуация, когда переходишь на фильм, может только фон, а может и вся страница.
Отключение антитрекинга проблему не решает.
Также, не работает (не появляется) переход к отметке:
![eb171e67781936fd196c62fdb088ea98](https://cloud.githubusercontent.com/assets/16462533/12958331/d3a7e18e-d039-11e5-9f57-dd47ee74b583.jpg)

Еще в Хром оповещение о блокираторе:
![2016-02-10 20-54-35 2015 1 1-6 60 - google ch](https://cloud.githubusercontent.com/assets/16462533/12958447/7265f14e-d03a-11e5-97c0-ea42ff9e7f6c.png)

**Comment by Alex-302** [comment]
То ж не о блокираторе сообщение, а о способах обхода блокировки сайта провайдером.
Проблемы не повторилисью Нужен список фильтров.

**Comment by Serzh-SUP** [comment]
@Alex-302 
Это фильтры, которые у меня. 
Пользовательский
Англ.
Русс.
Сис. аналит.
Эксперим.
Полезной рекламы

**Comment by Alex-302** [comment]
@Serzh-SUP 
у тебя повторилось? Раз десять открывал - всё нормально. Переход к позиции работает после регистрации.
