### ISSUE TITLE
URL shortener site datayi.cn is blocked

### ISSUE THREAD

**Issue by mnaoumov** [AdguardTeam/AdguardFilters#150224]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.11 (54)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://datayi.cn/w/a9By0BOo

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

1. URL shortener service datayi.cn is blocked. E.g. https://datayi.cn/w/a9By0BOo redirects to https://leetcode.com/discuss/study-guide/3458761/Open-to-Registration!-30-Days-of-LC-JavaScript-Challenge/?utm_campaign=Banner2&utm_medium=Banner&utm_source=Banner&gio_link_id=a9By0BOo

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/735878/236588008-d464614a-16e8-4541-af50-c6586217f1fe.png)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@mnaoumov А где этот сервис используется? Китайцы не жаловались, а он связан с аналитикой.

**Comment by mnaoumov** [comment]
> @mnaoumov А где этот сервис используется? Китайцы не жаловались, а он связан с аналитикой.

Этот сервис используется в ссылках на LeetCpde

**Comment by Alex-302** [comment]
Ок, разблокируем.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #1337](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1337) via [**Zenhub**](https://www.zenhub.com/)
