### ISSUE TITLE
[google.com] search field blocked

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdguardFilters#15061]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: google.com's search field blocked(can not type) as of 04/20/2018

 # description of the problem:
As of today (04/20/2018) google.com's search field is blocked,it's visible but it's not possible to type in it.
Disabling AdGuard fixes the problem.Checked the filtering logs and in "other" section is showing:
quic://74.125.202.99:443
![capture](https://user-images.githubusercontent.com/34774426/39072374-f1a001fc-44af-11e8-8e65-2d0eeba9ee9f.PNG)

* **Expected behaviour**: To be able to type.

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***
Windows 10 LTSB x64
Chromium(Slimjet) x64

**Filters:**
NoCoin Filter List,English Filter,Spyware Filter,Social media filter,Annoyances filter,EasyPrivacy,Fanboy's Annoyances,Malware Domains,Spam 404

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:    Windows 10 Enterprise LTSB x64                  | ?
Operating system version (Android/iOS) | ?
Browser:    Slimjet(Chromium)                           | ?
AdGuard version:    6.2.437.2171                   | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:   None                        | None / Default / Family Protection
Stealth mode options (Windows only)  Yes   | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Could you please update filter lists and check again?

**Comment by dnmTX** [comment]
@AdamWr  just did and now it's working.Thank you!
Closing......

**Comment by AdamWr** [comment]
Ok :)
