### ISSUE TITLE
Freevee Missed Ad Problem

### ISSUE THREAD

**Issue by orwdb** [AdguardTeam/AdguardFilters#150836]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.12

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.amazon.com/gp/video/detail/B00C17815Q/ref=atv_3p_fre_c_FCil6v_2_1?jic=36%7CCgtmcmVld2l0aGFkcxIMc3Vic2NyaXB0aW9u

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

<![freevee ad](https://github.com/AdguardTeam/AdguardFilters/assets/117128071/7b2cfc19-a856-4881-830e-e1a3ebfe523f)>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Not removable without breaking something.

**Comment by orwdb** [comment]
There's an extension developer for Chrome that developed an ad skipper works on all major platforms, you could employ a similar technique, accelerate the ad detection process and incorporate a brief pause under 1000 ms. It won't be as smooth as a filter but it's better than the alternative.

**Comment by Alex-302** [comment]
@orwdb 

> an ad skipper

Could you please give us a link?

**Comment by orwdb** [comment]
Sure no problem :)

https://www.vodextended.com/skipper#SzuRh9kJ01JhpNVDGoiZWsQfwPfUNP9M

https://chrome.google.com/webstore/detail/freevee-skipper-skip-ads/nfodepdbkedfahdadcglakjdmopkobon?utm_source=skipperLP

**Comment by orwdb** [comment]
In this the case of the Twilight Zone series as an example, the ad removal work is excellent well done, however, it's auto-skipping to the next episode a bit early , I noted it missed Rod Serling's monologue at the end.

**Comment by orwdb** [comment]
Not a request to fix, it's purely for consideration by the development team. There is a random(occasional)  minor overlap in some sections where the ads have been skipped, it restarts at a start point before the ad is inserted so some of the content is replayed for 10-20 secs or so . In another situation, it is possible to review a potential fix if it isn't time-consuming,  as mentioned in the last comment, auto skip before the series episode has ended to the next episode does occur without giving the viewer the option to cancel.

**Comment by orwdb** [comment]
Not a request to fix, it's purely for consideration by the development team. There is a random(occasional) minor overlap in some sections where the ads have been skipped, it restarts at a start point before the ad is inserted so some of the content is replayed for 10-20 secs or so . I've also disabled the autoplay next episode settings, it may override any filter updates and resolve the issue.

![Autoplay setting](https://github.com/AdguardTeam/AdguardFilters/assets/117128071/b3b7d9b1-09d8-4ab6-aba7-263f5046a3e2)

**Comment by Alex-302** [comment]
> where the ads have been skipped, it restarts at a start point before the ad is inserted so some of the content is replayed for 10-20 secs or so .

I don't understant what do you mean. Could you please record a video using a phone? (apps will record black screen)

**Comment by orwdb** [comment]
It's difficult to say if it's random or a regular occurrence on every ed break, viewing behaviour will influence it for example not starting an episode at the beginning, eg 15 mins into the episode.   For recording normally black screen is the case, I have a video recorder that captures the stream from the video card, using the browser to control events, so there's no black screen. Setting up the phone to record would take more time. Say ads are detected at 7 min 45 secs, after the ad-skipping the stream would recommence at 7 mins 30 sec. Not sure if there will be file size limits if I upload , but I'll try.

**Comment by orwdb** [comment]
An example at 43 min, the dart game scene is repeated. I went straight to the google drive, click on the link to download:

https://drive.google.com/file/d/1tA0NXN0RaAmoQ2juq0k-qKTMc1z0QHaz/view?usp=share_link

**Comment by Alex-302** [comment]
Yep, 42:50 and 44:20... We will check it.

**Comment by Alex-302** [comment]
Not sure if it can be fixed by ad blocker.

**Comment by orwdb** [comment]
I appreciate the effort and time, your skipping technique is very good even if the cue points are too dynamic to restart at the exact point the ad is inserted, Pluto TV also has streaming rights to some of the films and portions of the same TV series content, I can watch that without ads also.
