### ISSUE TITLE
[question] dealing with CORS / removing HTML element

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdguardFilters#150899]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [ ] Browser version is up-to-date;
- [ ] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.13 nightly 1 (build 4175, CL 1.11.34)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Slimjet Version 39.0.2.0 (based on Chromium 111.0.5563.41) (Official Build) (64-bit)

### Which device do you use?

Laptop

### Where is the problem encountered?

**CORS Issue**:  https://lvturbo.com/2jshfs7gfdym.html
**HTML Element**: https://www.techpowerup.com/forums/threads/ssd-help-thread.308586/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Disable cache for third-party requests, Block WebRTC, Block Push API, Block Location API, Hide your User-Agent (specify in comment below, if used custom value), Protect from DPI

### Add your comment and screenshots

1. <comment> @AdGuardTeam would appreciate some help when dealing with CORS policy as it started happening very often and some websites don't function properly,web players as well. Here is a simple example of the issue(see screenshot). So far what's worked for me was to create those two rules:

   `@@||akamai-video-content.com^$xmlhttprequest`
   `@@||lvturbo.com^$xmlhttprequest`

   but i'm not sure that this is the proper way and i'm worry that my browser is more exposed this way.
   Please advise.
<details><summary>Screenshot ☝️ :</summary>

 
![CORS](https://github.com/AdguardTeam/AdguardFilters/assets/34774426/21ab6df2-dd38-4183-8b1b-3d4cde7b9b65)

</details> 

2. <comment> Would also need some help properly removing HTML element(see screenshot). Tried many variations and the only rule so far that does the job is:

   `/*manifest*$domain=.......`

<details><summary>Screenshot ☝️ :</summary>

![manifest](https://github.com/AdguardTeam/AdguardFilters/assets/34774426/5b2d72f8-df51-4d1a-92bb-90a037029a3e)

</details>
Thank you and keep up the awesome work 👍 

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
I don't work for AdGuard but you can delete the manifest like that in Chromium:

https://github.com/AdguardTeam/AdguardFilters/issues/145545

> https://github.com/AdguardTeam/AdguardFilters/blob/82356cb7589fc4e60d86855a96de87fc354aa40b/AnnoyancesFilter/MobileApp/sections/mobile-app_specific.txt#L2466-L2470

So in the night edition you can activate the list for removing widgets for mobile apps* or copy to your rules this line (necessarily with exceptions as you use one of the listed sites).

> \* - https://filters.adtidy.org/windows/filters/20.txt

CORS is rather beyond my capabilities - Maybe it's enough to exclude these problem domains from TLS, but remember then manually update exceptions list: https://github.com/AdguardTeam/HttpsExclusions#how-the-list-gets-updated-in-the-adguard-apps.

**Comment by AdamWr** [comment]
I'm not sure if I understand correctly, but as far as I know, `$stealth` should not disable `$csp` rules.
If you don't want to disable all stealth mode options, you can try to disable only a specific option (or options if necessary), for example:
```adblock
@@||lvturbo.com^$stealth=useragent
@@||akamai-video-content.com^$stealth=useragent
```
https://adguard.com/kb/general/ad-filtering/create-own-filters/#stealth-modifier

**Comment by AdamWr** [comment]
`$csp` seems to works fine on my end alongside with `$stealth` rule.
Please try to clear website cache or refresh website using <kbd>Ctrl</kbd>+<kbd>F5</kbd>
