### ISSUE TITLE
carousell.com.hk

### ISSUE THREAD

**Issue by antermin** [AdguardTeam/AdguardFilters#150929]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.49.2

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.carousell.com.hk/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Japanese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyList

### Add your comment and screenshots

1. The homepage of Carousell Hong Kong is showing an advertisement (indicated by the "AD" label).

2. Screenshots
<details><summary>Screenshot 1:</summary>

![screenshot-1](https://github.com/AdguardTeam/AdguardFilters/assets/103918092/a18cd462-6129-431e-9d74-30865cf1fce2)

</details>

<details><summary>Screenshot 2:</summary>

![screenshot-2](https://github.com/AdguardTeam/AdguardFilters/assets/103918092/a03e0c06-49e7-4e94-a338-8d8ad256f476)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
