### ISSUE TITLE
healthline.com [Blank Ad Banner]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#15096]
**Site**: https://www.healthline.com/health/amitriptyline-oral-tablet

**Issue**: Please remove the blank Ad banner on top of the page.

**Screenshot**: http://prntscr.com/j882jw

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.117 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
it seems it has random name.
