### ISSUE TITLE
medindia.net [Ad String]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#15095]
**Site**: https://www.medindia.net/drug-price/Amitriptyline/goldep-sr-10-mg.htm

**Issue**: Please remove the Ad string seen on the top and bottom of the page.

**Screenshot**: 

http://prntscr.com/j87nho
http://prntscr.com/j87mfc

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.117 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
Alex, couple of more Ad strings seen on the this page:

https://www.medindia.net/drugs/medical-condition/depression.htm

Screenshot: http://prntscr.com/jb7oap
http://prntscr.com/jb7olw

**Comment by Alex-302** [comment]
Done.
1 - not an ad
