### ISSUE TITLE
vidaextra.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#150979]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.49.3b10

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.vidaextra.com/

### What filters do you have enabled?

AdGuard Tracking Protection filter

### Add your comment and screenshots

1. <comment>
Story panel gets hidden by AdGuard Tracking Protection of all things...

Caused by `vidaextra.com##div[style="width:100%; height:160px"]`

Also worth noting: https://github.com/easylist/easylistspanish/issues/305

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
