### ISSUE TITLE
onlaine-bank.ru

### ISSUE THREAD

**Issue by vehlwn** [AdguardTeam/AdguardFilters#151188]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

It's dns.adguard-dns.com server

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://onlaine-bank.ru/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

Is this site supposed to be blocked? Ublock with adguard filters doesn't block it, but `dig @dns.adguard-dns.com +tls onlaine-bank.ru` returns

> onlaine-bank.ru.        3600    IN      A       94.140.14.33

which points to `dns.adguard.com` and causes TLS error:

```
$ curl -v https://onlaine-bank.ru
*   Trying 94.140.14.33:443...
* Connected to onlaine-bank.ru (94.140.14.33) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=dns.adguard.com
*  start date: Dec  2 00:00:00 2022 GMT
*  expire date: Dec  2 23:59:59 2023 GMT
*  subjectAltName does not match onlaine-bank.ru
* SSL: no alternative certificate subject name matches target host name 'onlaine-bank.ru'
* Closing connection 0
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (60) SSL: no alternative certificate subject name matches target host name 'onlaine-bank.ru'
More details here: https://curl.se/docs/sslcerts.html
```

Google and CLoudflare DNS servers without filters return different result and TLS works properly:
```
dig @1.1.1.1 +tls onlaine-bank.ru
```
>onlaine-bank.ru.        14400   IN      A       185.162.8.18

### Privacy

- [X] I agree to follow this condition

**Comment by vehlwn** [comment]
PS: This [list](https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt) also doesn't contain any references to the site.

**Comment by Eugene-Savenko** [comment]
It was blocked because the domain name has features of a phishing website. We went ahead and unblocked it for you and other users. Please allow a couple of hours for the servers to update the databases.
