### ISSUE TITLE
Recently added rule prevents live streaming on SCRPCHAT site

### ISSUE THREAD

**Issue by lvzhenbo** [AdguardTeam/AdguardFilters#151108]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.55

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

stripchat.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Japanese filter, AdGuard Russian filter, Filter unblocking search ads and self-promotion

### Add your comment and screenshots

1. Recently updated rules disrupt the live streaming of this site

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image.png](https://s2.loli.net/2023/05/17/mLJEVGuQaZDh4dn.png)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
stripchat.com works fine on my end.

**Comment by lvzhenbo** [comment]
> stripchat.com works fine on my end.

Please see the picture, in the blocking log there is blocked m8u8 link, this is the live link

**Comment by Alex-302** [comment]
> m8u8

I don't see

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/f06f4ad8-b39f-4880-acd0-a7caa8935f71)


</details>

Which filter causes it?

**Comment by lvzhenbo** [comment]
AdGuard Base filter
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt
```
||*.doppiocdn.com/hls/*/master/*.m3u8$domain=xhamster20.desi|xhamster19.desi|xhwebsite2.com|xhamster18.desi|xhadult3.com|xhadult2.com|xhmoon5.com|xhwide1.com|xhwide8.com|xhamster3.com|xhplanet2.com|megaxh.com|xhamster16.*|hamsterix.*|xhamster.com|xhamster2.com|xhamster7.com|xhamster8.com|xhamster9.com|xhamster10.com|xhamster12.com|xhamster13.*|xhamster14.com|xhamster15.com|xhamster17.*|xhamster18.*|xhamster19.com|xhamster1.desi|xhamster2.desi|xhamster3.*|xhamster4.desi|xhamster20.com|xhamster22.com|xhamster23.com|xhamster25.com|xhamster26.com|xhamster27.com|openxh.com|xhamster31.com|xhamster32.com|xhamster34.com|xhamster35.com|xhamster36.com|xhamster37.com|xhamster38.com|xhamster500.com|xhamster5.desi|xhopen.com|openxh1.com|xhamster39.com|xhamster40.com|xhamster.one|xhamster.desi|stripchat.com
||go.xhamsterlive.com/api/models$third-party
```

**Comment by lvzhenbo** [comment]
> I also need a link of stream.

https://b-hls-01.doppiocdn.com/hls/67921083/67921083.m3u8?playlistType=standard

**Comment by lvzhenbo** [comment]
Here's the deal. First, please turn off the Ultar-low Latency feature. It's that lightning bolt icon. Then this is my link
https://stripchat.com/aerri_lee

**Comment by Alex-302** [comment]
> lightning bolt

I don't see it.





> https://stripchat.com/aerri_lee

Only this? It is not public.

**Comment by lvzhenbo** [comment]
![image](https://github.com/AdguardTeam/AdguardFilters/assets/32427677/7a4e1ed1-50c2-4f9e-9912-19ff665778f1)
Close the function to see the picture above, is a public live room, can be opened, but it does not matter, other live rooms are the same problem, that is, the rules block the live stream link

**Comment by lvzhenbo** [comment]
> AdGuard Base filter [AdguardTeam/FiltersRegistry@`master`/filters/filter_2_Base/filter.txt (raw)](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt)
> 
> ```
> ||*.doppiocdn.com/hls/*/master/*.m3u8$domain=xhamster20.desi|xhamster19.desi|xhwebsite2.com|xhamster18.desi|xhadult3.com|xhadult2.com|xhmoon5.com|xhwide1.com|xhwide8.com|xhamster3.com|xhplanet2.com|megaxh.com|xhamster16.*|hamsterix.*|xhamster.com|xhamster2.com|xhamster7.com|xhamster8.com|xhamster9.com|xhamster10.com|xhamster12.com|xhamster13.*|xhamster14.com|xhamster15.com|xhamster17.*|xhamster18.*|xhamster19.com|xhamster1.desi|xhamster2.desi|xhamster3.*|xhamster4.desi|xhamster20.com|xhamster22.com|xhamster23.com|xhamster25.com|xhamster26.com|xhamster27.com|openxh.com|xhamster31.com|xhamster32.com|xhamster34.com|xhamster35.com|xhamster36.com|xhamster37.com|xhamster38.com|xhamster500.com|xhamster5.desi|xhopen.com|openxh1.com|xhamster39.com|xhamster40.com|xhamster.one|xhamster.desi|stripchat.com
> ||go.xhamsterlive.com/api/models$third-party
> ```

You can see from the rules that it is indeed blocked

**Comment by Alex-302** [comment]
Please test one by one
```adblock
||*.doppiocdn.com/hls/*/master/*.m3u8$domain=stripchat.com,badfilter
```

```adblock
||go.xhamsterlive.com/api/models$third-party,badfilter
```

**Comment by lvzhenbo** [comment]
The first rule is OK, the second rule is the one I copied wrongly and don't need. 
It's actually the `*.doppiocdn.com/hls/*/master/*.m3u8` rule that's the problem

**Comment by Alex-302** [comment]
Ok.
