### ISSUE TITLE
[iOS] Can't open link from google search in the background

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1511]
Некорректная блокировка на странице:
https://yandex.ru/search/pad/?lr=213&msid=20945.9405.1455033802.73161&text=%D1%82%D0%B5%D1%81%D1%82

При открытии ссылки, из результатов поиска, открывается вкладка "about:blank"

Ошибка на iPad mini, iOS 9.2.1
![image](https://cloud.githubusercontent.com/assets/15856304/12974943/abb62672-d0c0-11e5-971b-a1c12a929b85.png)

GWC-298-45283

**Comment by Alex-302** [comment]
Добавил в фильтр Сафари
```
@@||yandex.ru/clck/jsredir?$domain=yandex.ru
@@||yandex.ua/clck/jsredir?$domain=yandex.ua
@@||yandex.by/clck/jsredir?$domain=yandex.by
```
