### ISSUE TITLE
optimizely.com - duplicate rules

### ISSUE THREAD

**Issue by uuqqzz** [AdguardTeam/AdguardFilters#151291]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

https://github.com/AdguardTeam/AdguardFilters/blob/b7f5c1ab8d39e6bfbde13c2168d7874e4b180760/SpywareFilter/sections/tracking_servers.txt#L2983
https://github.com/AdguardTeam/AdguardFilters/blob/b7f5c1ab8d39e6bfbde13c2168d7874e4b180760/SpywareFilter/sections/specific.txt#L2010
https://github.com/AdguardTeam/AdguardFilters/blob/b7f5c1ab8d39e6bfbde13c2168d7874e4b180760/SpywareFilter/sections/tracking_servers_firstparty.txt#L1078

### Proposed solution

-

**Comment by krystian3w** [comment]
Second and third can works as first party request/resource.
