### ISSUE TITLE
watch5s.is [Ads/Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#15126]
**Site**: https://watch5s.is/movie/the-last-hope/

**Issue**: Please remove the Ads and fake links seen on the page.

**Screenshot**: http://prntscr.com/j8hr92

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.117 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Bottom left corner not shown, probably fixed by other rule too, Please check for updates in 2-3 hours and report back, thank you.
