### ISSUE TITLE
Remove dead domain in Base

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#151447]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.55

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://github.com/AdguardTeam/AdguardFilters

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

As always, just raw PF results with only obviously living domain excluded so needing double-check. Some domain are included in severeal sublists e.g. d3ujids68p6xmq.cloudfront.net in allowlist and antiadblock but omitted if I noticed.

<details>
<summary>allowlist.txt</summary>

- [x] `ad-text.ru`
- [x] `fastflash.pw`
- [x] `cdn-static.liverail.com`
- [x] `jweb.kettering.edu`
- [x] `pornhub.phncdn.com`
- [x] `cupsservice.com`
- [x] `developer.softonic.com`
- [x] `edge-dl.andomedia.com`

</details>

<details>
<summary>allowlist_strealth.txt</summary>

- [x] `uauplayer.com`
- [x] `mundodebolso.me`
- [x] `conheceresaber.space`
- [x] `img.bondinternational.net`
- [x] `api-game.rivet.gg`
- [x] `player.daznfeeds.com`
- [x] `link.mazterize.com`
- [x] `31vaktii.xyz`
- [x] `cdn.bunny.sh`
- [x] `multi.idocdn.com`
- [x] `cdn-pics.pornhd.com`
- [x] `static.gota.infomaker.io`
- [x] `fox-nv.mncdn.com`
- [x] `tx.acgvideo.com`
- [x] `dizigold.org`
- [x] `thumb.comic.naver.net`
- [x] `iptvsale.info`
- [x] `bro.adcast.tech`
- [x] `accounts-flickr.yahoo.com`

</details>

<details>
<summary>antiadblock.txt</summary>

- [x] `jpblow.info`
- [x] `ultimasnoticias.com.ve`
- [x] `slones.info`
- [x] `xn--stream-oe64e.ga`
- [x] `player.oyasumi.me`
- [x] `include.canale.live`
- [x] `links.spidermods.in`
- [x] `theantiadblocker.com`
- [x] `link.mymastah.com`
- [x] `sitaronkidunya.com`
- [x] `apk24h.com`
- [x] `potvid.com`
- [x] `allmovies.tube`
- [x] `couponbro.eu`
- [x] `miraculousladybug.cf`
- [x] `download.web.id`
- [x] `oo5zw3hrsd.xyz`
- [x] `vuster.xyz`
- [x] `animesanka.net`
- [x] `blog.omglyrics.com`
- [x] `earncryptosaj786.com`
- [x] `mega-infonews1a.club`
- [x] `wikidoplaneta.club`
- [x] `vtppi.com`
- [x] `hightech.web.id`
- [x] `fullbeeg.com`
- [x] `waaws.tk`
- [x] `mw5blog.blogspot.com`
- [x] `myphotolikes.com`
- [x] `sims4marigold.blogspot.com`
- [x] `servicesfun.com`
- [x] `zoey-deutch.us`
- [x] `2o-my.com`
- [x] `rmdan.org`
- [x] `ramdan.tv`
- [x] `c4free.win`
- [x] `talkittechy.com`
- [x] `teqnwy.com`
- [x] `techfinda.com`
- [x] `jainjinvani.com`
- [x] `technoslek.com`
- [x] `royalown.review`
- [x] `teqniaplus.com`
- [x] `crabcut.net`
- [x] `firelinks.me`
- [x] `programming.discudemy.com`
- [x] `smtebooks.net`
- [x] `modapkfree.me`
- [x] `discoveryrom.org`
- [x] `sigourney-weaver.net`
- [x] `catchsms.co`
- [x] `forum.darksoftware.net`
- [x] `hdmp4mania.me`
- [x] `skyfaucet.win`
- [x] `forum.blackhatindia.ru`
- [x] `atchhowimetyourmother.com`
- [x] `bella-thorne.org`
- [x] `torrentevo.blogspot.com`
- [x] `stefaniescott.org`
- [x] `getmyfile.ga`
- [x] `simplo.gg`
- [x] `indoblog.me`
- [x] `jhub.pw`
- [x] `socksproxylist24.blogspot.com`
- [x] `funcinema.ga`
- [x] `androidoreos.info`
- [x] `business-tv.org`
- [x] `fckdescargas.com.ve`
- [x] `fckdescargaspaste.com.ve`
- [x] `fullhdxxx.org`
- [x] `smspinger.com`
- [x] `kinoking.to`
- [x] `mmoplus.info`
- [x] `thebeastnews.com`
- [x] `pornhdx.tv`
- [x] `smartinvestor.business-standard.com`
- [x] `elgoles2017.blogspot.ru`
- [x] `millonbitcoin.com`

</details>

<details>
<summary>content_blocker.txt</summary>

- [x] `livefootball77.blogspot.de`
- [x] `sevenangel.id`
- [x] `yibtccoins.com`
- [x] `faucethubgiveaway.win`
- [x] `business-tv.me`
- [x] `320box.com`
- [x] `azfinans.ru`
- [x] `conference-hosting.net`
- [x] `degree-classes.com`
- [x] `diyzone.tips`
- [x] `diysite.tips`
- [x] `filmreno.net`
- [x] `grfeed.com`
- [x] `healthysolutionsbenefit.com`
- [x] `idownloadblogs.com`
- [x] `librospdfgratis.net`
- [x] `minimilitiacheats.com`
- [x] `thestreetriders.com`
- [x] `todaysjobalert.com`
- [x] `truquesedicas.org`
- [x] `www-mabadi.com`
- [x] `viewhealth.net`
- [x] `viralholic.net`
- [x] `antiquewoodenware.com`
- [x] `game-owls.com`
- [x] `pdfadresi.com`
- [x] `vozz.vn`
- [x] `shibunnokuni.com`
- [x] `m.blogtin.video`
- [x] `blogtamsu.video`
- [x] `m.blogtamsu.vn`
- [x] `static.pornhub.phncdn.com`

</details>

<details>
<summary>cryptominers.txt</summary>

- [x] `whysoserius.club`
- [x] `xy.nullrefexcep.com`
- [x] `jshosting.bid`
- [x] `likeminer.nablabee.com`
- [x] `miner.nablabee.com`

</details>

<details>
<summary>css_extended.txt</summary>

- [x] `xenforo.pk`
- [x] `url.mailzig.com`
- [x] `royalown.review`

</details>

<details>
<summary>foreign.txt</summary>

- [x] `zyciejastrzebia.pl`
- [x] `memytutaj.pl`
- [x] `s01.pl`
- [x] `loa2.dobregry.pl`
- [x] `hentai18plus.blogspot.com`
- [x] `ahaclip.com`
- [x] `media.netnews.vn`
- [x] `member.civi.vn`
- [x] `flamingo.dailai.info`
- [x] `sezi.vn`

</details>

<details>
<summary>specific.txt</summary>

- [x] `pornhdx.tv`
- [x] `kickpunch2015.wix.com`
- [x] `justshemaletube.com`
- [x] `sexcfnm.com`
- [x] `shemalepornstartube.com`
- [x] `vrhlehhm.net`

</details>

<details>
<summary>general_extensions.txt</summary>

- [x] `pixhost.org`
- [x] `b99.tv`

</details>

<details>
<summary>replace.txt</summary>

- [x] `damoh.tv4play.se`

</details>

Also href of these in specific.txt are dead, so likely to be dead rules:

- [x] `yourbittorrent.com##a[href*="xxcdn.pw/torrent"]`
- [x] `uplod.ws##a[href^="http://earth-111.com/ref?"]`
- [x] `download3k.com##a[href^="http://link.tweakbit.com/"]`
- [x] `softwarespatch.com##a[href^="http://tfp.sapphirum.com"]`
- [x] `mmohuts.com##a[href^="http://www.mmo123.co/"]`
- [x] `phpnuke.org##a[href^="https://www.seologies.com?ref"]`
- [x] `twitch.tv##a[href^="https://www.paripartners.ru/"]`

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
I see FP, that works in Poland: `https://defence24.pl/` also bug in format:

![image](https://github.com/AdguardTeam/AdguardFilters/assets/35370833/0e34f445-009c-44a0-a3fa-e40cad26dd72)

**Comment by Yuki2718** [comment]
Yes, `defence24.pl` is alive. Will delete from the list.

**Comment by Yuki2718** [comment]
Delteded `odwebp.svc.ms` as it's living.

**Comment by Yuki2718** [comment]
Del
```
store-web.dynamics.com (buynow.production.store-web.dynamics.com)
```

**Comment by Yuki2718** [comment]
Del
```
imgtn.bdimg.com (img5.imgtn.bdimg.com)
```

**Comment by piquark6046** [comment]
Del `ad.atdmt.com` domain from the list.
 - https://www.similarweb.com/website/ad.atdmt.com/#overview
 - https://en.wikipedia.org/wiki/Atdmt

**Comment by Yuki2718** [comment]
> Del `ad.atdmt.com` domain from the list.

On my end it's NXDOMAIN. @pgl I see this is blocked on your list, is it still alive?

**Comment by piquark6046** [comment]
Del `emagst.akamaized.net` domain from the list because it is difficult to verify.

<details><summary>Screenshot and related issue</summary>

![Screenshot from 2023-06-01 21-21-19](https://github.com/AdguardTeam/AdguardFilters/assets/98787049/e7718293-bb4b-4b33-a2a9-887714e1c93b)

 - https://github.com/AdguardTeam/AdguardFilters/issues/129752

</details>
