### ISSUE TITLE
HTTPS certificate confirmation issues of certain applications.

### ISSUE THREAD

**Issue by darenchun** [AdguardTeam/AdguardFilters#151586]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android, AdGuard for Windows

### AdGuard version

3.6.11

### What type of problem have you encountered?

Missed ads or ad leftovers, Website or app doesn't work properly, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://tubemate.net

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList, List-KR

### What Stealth Mode options do you have enabled?

Hide your search queries, Self-destruction of third-party cookies, Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

1. Symptoms
 When using some application, inform shown below shows and ads won't be blocked or cannot use application at all.

For now, 2 applications majorly that I use is the problem.
1) Tubemate : 
https://tubemate.net
2) SPOTV NOW : 
https://play.google.com/store/apps/details?id=kr.co.spotvnow.app&hl=ko&gl=US&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dspotvnow&pcampaignid=APPU_1_VuZrZOySGcOK-Qbgg79o

Especially for the second version, I think this app detects adguard and blocks connection itself when using adguard.

2. Screenshots
<details>
<summary>App does not approve HTTPS certificate</summary>

![Screenshot_20230523-065714_Chrome](https://github.com/AdguardTeam/AdguardFilters/assets/36753565/6c5c7c75-97c7-4376-854d-6278f3f55330)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
Answer to question 2:
From Android 7.0, an Android app does not trust an user TLS certificate by default [^1].
This affects all local VPN-based adblockers including AdGuard or Unicorn Pro adblocker.
So, unless you root your android device, you have to disable HTTPS filtering for app and filters traffic of an app with domain information.

[^1]: https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html

**Comment by Alex-302** [comment]
Yep. Even with root access some apps can reject self-signed cert.

**Comment by darenchun** [comment]
Thanks for the reply.
Learned new info! thx
