### ISSUE TITLE
resumes.breakdownexpress.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#151687]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.49.3b19

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://resumes.breakdownexpress.com`

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyList, EasyPrivacy

### Add your comment and screenshots

1. <comment>
Possible trackers on this site.
What you'll see when going on any resume:
`breakdownexpress.com/js/analytics.js`
`breakdownexpress.com/global/assets/js/logVideoPlay.js` (Maybe?)

On breakdownexpress.com itself:
`breakdownexpress.com/js/ads/googletagPreLoginLeaderboardRect.js`
`breakdownexpress.com/js/ads/googletagLoadAds.js`
`breakdownexpress.com/js/yahoo-dom-event.js` Maybe this one should be /yahoo-dom-event.js
This Yahoo script also appears on `http://forum.pj64-emu.com/showthread.php?t=5542`

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sonic5435325** [comment]
Go to any of the listed resumes on this page:
`https://resumes.breakdownexpress.com/emailed_actors.cfm?email=24DBE770-5D8F-48E7-BAA5-977D8A41348C&`

**Comment by jellizaveta** [comment]
/yahoo-dom-event.js - UI library 
/logVideoPlay.js - seems used for logging video play events to a server
