### ISSUE TITLE
editions-eni.fr

### ISSUE THREAD

**Issue by AdSlayer** [AdguardTeam/AdguardFilters#151752]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.13

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.editions-eni.fr/

### What filters do you have enabled?

AdGuard Base filter, AdGuard French filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, Fanboy's Annoyances, Fanboy's Social Blocking List, Web Annoyances Ultralist, Adblock Warning Removal List, Fanboy's Enhanced Tracking List, Fanboy's Anti-Facebook List, NoCoin Filter List

### Add your comment and screenshots

1. When AdGuard is enabled, every page you visit on this web site pops up an error message: https://www.editions-eni.fr
Disabling AdGuard and refreshing the page gets rid of the error message.

3. Screenshots
<img width="960" alt="erreur2" src="https://github.com/AdguardTeam/AdguardFilters/assets/97131319/cb0e4cee-7906-4aa8-84b1-b9c6ecad3cbb">
<img width="960" alt="erreur" src="https://github.com/AdguardTeam/AdguardFilters/assets/97131319/7a6ce21a-a5df-4414-ad5b-75d36904ed36">

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
@AdSlayer
I can't reproduce this issue, is it still relevant?

**Comment by AdSlayer** [comment]
Hello @Sergey-Lyapin, 
Thank you. Yes it's still relevant. I spent some time trying to understand what was causing this. It's a rule set called "_Fanboy's Annoyances_". This is the only rule set that, if disabled, and if I reload the web page, allows to get rid of that error message. Please note that I noticed that, to be able to reproduce the bug, you need to:
- Use a chromium-based web browser (e.g. Chrome, Edge), because in Firefox, the result was unexpected (it timed out when trying to reload the page from scratch). Yet, insisting, I was also able to reproduce the bug in Firefox (I restarted the browser).
- Reload the page from scratch (not from cache). To do so, I hit `Ctrl-Shift-R` or `Shift-F5` in my web browser

Thank you.

**Comment by Sergey-Lyapin** [comment]
Hello @AdSlayer, thank you very much for your help.
The issue is caused by the rule `||editions-eni.fr/dlg/cookies.aspx` from Fanboy's Annoyances, please add to user rules:

```
@@||editions-eni.fr/dlg/cookies.aspx
editions-eni.fr###CkC
```

I informed the developer of Fanboy's Annoyances about this error.

**Comment by AdSlayer** [comment]
Thank you! This did the trick 😉👍
