### ISSUE TITLE
imdb.com

### ISSUE THREAD

**Issue by Felipefpl** [AdguardTeam/AdguardFilters#151866]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

None

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

www.imdb.com

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

I'm using ublock on waterfox with adguard's list and the ads are blocked in the site but the places where the ads were arent removed.

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Not reproduced. Please ensure EasyList is enabled and in options element hiding is active.
If you still can reproduce, please psot a screenshot.

**Comment by Felipefpl** [comment]
I dont understand your point, this is a problem with adguard's list, not easylist.

**Comment by Felipefpl** [comment]
I know that but this place is to report problems with adguard's list, which i what i'm doing.

**Comment by BlazDT** [comment]
Adding a rule which is already in EasyList is resulting in the filter list to have the same rule twice when using an AdGuard product.
