### ISSUE TITLE
www.hinatasoul.com

### ISSUE THREAD

**Issue by Felipefpl** [AdguardTeam/AdguardFilters#151835]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

None

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.hinatasoul.com/

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

Hi, i'm using ublock on waterfox with adguard's list and the ads in this site arent blocked.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Need a screenshot.

**Comment by Felipefpl** [comment]
Ads on top

https://www.hostpic.org/images/2305251814540277.png

**Comment by Alex-302** [comment]
Easylist in UBO must be enabled.
