### ISSUE TITLE
Facebook Tracking Rules [Android]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#15200]
Hello,

I have observed that many apps installed on Android and when run make connections to Facebook via the tracking domain:

`graph.facebook.com`

The complete URLs are shown in the below two screenshots:

**Screenshots**:
https://ibb.co/m2uiic
https://ibb.co/mfKoGx

The URL format would be the same from one app to another. The only difference would be the numbers: `v2.10/224150177763582` seen in URL of both the screenshots.

Therefore, this request is to add appropriate rules to the main filter list so that both these URL formats would be blocked in all apps. Note that directly blocking `graph.facebook.com` would have an impact as there are apps (for Ex: Facebook / Messenger) that would not work if it is blocked. Therefore, a suitable pattern has to be decided and added to the filters.

**Apps where we see these domains**:

**MX Player**: https://play.google.com/store/apps/details?id=com.mxtech.videoplayer.ad&hl=en_US
**Shapes**: https://play.google.com/store/apps/details?id=com.infinitygames.shapes&hl=en
etc.

**System**:
- Android version: 6.0.1 MMB29M
- MIUI version: MIUI Global 9.5 - Stable [ 9.5.1.0 (MHOMIEK) ]

**AdGuard Version**:
- AdGuard for Android 2.10.176

**Filters**:
English, Spyware, Social Media, Annoyances, Mobile Ads, Simplified domain names, EasyList China, Anti-Adblock Killer-Reek

**AdGuard Settings**:

- No user filter used
- Phishing & Malware Protection: Enabled
- Block ads in all apps: Enabled
- Search ads & self-promotion of sites: Disabled
- DNS Filtering enabled with DNSCrypt (Server: AdGuard DNS)
- HTTPS Filtering: Enabled
- High quality filtering: Enabled
- Filtering mode is Local VPN

**Comment by Alex-302** [comment]
graph.facebook.com is not used for ads and tracking only. This is common sub-domain.
Also it is impossible to block them on Android 6+ without root access.
You can test these rules if you see full URLs in the log:
```
||graph.facebook.com/*/activities?access_token=&event=
||graph.facebook.com/*?fields=supports_implicit_sdk_logging
```

**Comment by Nzzyme** [comment]
Thanks Alex for the rules. However, only the second rule works. Can you please check the first one?

**Comment by Alex-302** [comment]
Please copy url which is not blocked

**Comment by Nzzyme** [comment]
I don't understand Alex. Do you want me to copy the URL in the Filtering Log which is not blocked and paste it here? If so, then I have already provided the URL in the screenshot above. Let me know if this is not the case.

**Comment by Alex-302** [comment]
I need it in text form

**Comment by Nzzyme** [comment]
Ok, here you go:

`https://graph.facebook.com/v2.10/224150177763582/activities?access_token=&format=json&sdk=android`

**Comment by Alex-302** [comment]
This url is not tracker.

**Comment by Nzzyme** [comment]
Why did you close this issue? Can you provide me with a customized rule that will block this URL from all the apps (generic rule) and not per app?

**Comment by Alex-302** [comment]
```
||graph.facebook.com/*/activities?
||graph.facebook.com/*?fields=
```
or
```
||facebook.com^$important
```

**Comment by Nzzyme** [comment]
Tried the first one and it works. Thanks

The two URLs posted in the first post are seen originating from apps that have nothing to do with FB. These are tracking links and you may want to add them to the main list. Thank you!

**Comment by Nzzyme** [comment]
Hi @Alex-302 The following rule is not working:
||graph.facebook.com/*/activities?

I applied the rule in the user filters but still see connections being made.

Can you please check?

**Comment by Alex-302** [comment]
I need steps for reproducing.

**Comment by Nzzyme** [comment]
Steps to reproduce:

1. Installed the app (Thop Tv) from this link: https://bit.ly/2XP528i 

2. I also have the filter rule that you have provided earlier added to my user filter:

`||graph.facebook.com/*/activities?`

3. However, when I checked the Filtering Log, I see that connection is made to that domain and it is not blocked by the rule. It was getting blocked earlier.

Screenshot: https://ibb.co/hfrH5sj

**Comment by Alex-302** [comment]
Is filtering enabled for that app?

**Comment by Nzzyme** [comment]
> Is filtering enabled for that app?

Yes, it is

**Comment by Alex-302** [comment]
please try `||graph.facebook.com/*/activities^`
