### ISSUE TITLE
MSN ads left over cleanup needed 

### ISSUE THREAD

**Issue by techgamers2** [AdguardTeam/AdguardFilters#152187]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Version: 2.2.83.40

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.msn.com/en-in/health/medical/what-is-disease-x-all-you-need-to-know/ar-AA1bNp3R?rc=1&ocid=winp1taskbar&ei=6

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyPrivacy, NoCoin Filter List, Legitimate URL Shortener

### Add your comment and screenshots

1. <comment>when i enable easylist it fixes the problem but adguard base filter has this problem

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot 2023-05-28 211512](https://github.com/AdguardTeam/AdguardFilters/assets/44696073/9eb3c2d8-ce97-41b6-bf40-3938159238cc)

all msn site the are launched through Microsoft start has this ads leftover 
</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Hello! EasyList is included in the AdGuard Base filter. The block is not reproduced on my end, please, try refreshing the filters and clearing the browser cache

**Comment by techgamers2** [comment]
i know adguard uses easylist but is the easylist version tht adguard uses updated  ? coz i clear cache even switched browser tried in librewolf ( mozilla firefox fork ) i got the same result 
also check this easylist msn issue fix they also had this issue and they fixed after this commit  > https://github.com/easylist/easylist/commit/d7a43176ab832a838eccd90ea060ddc3510e61f3
adguard only enabled screenshot > 
![adguard](https://github.com/AdguardTeam/AdguardFilters/assets/44696073/b122e33d-a8f5-4a04-8e80-5d084caa98e7)
when easylist enabled also screenshot > 
![easylist](https://github.com/AdguardTeam/AdguardFilters/assets/44696073/fe96f1bb-906b-462f-96f7-a4bace21ef5d)

**Comment by jellizaveta** [comment]
works correctly with the AdGuard extension, I'll check now and come back in a little while

**Comment by jellizaveta** [comment]
In ublock the AdGuard Base filter without EasyList included there. Therefore, it will be necessary to enable it additionally in this extension.

**Comment by techgamers2** [comment]
cant this issue be fixed in adguard base filter ?
