### ISSUE TITLE
files.technicalatg.com

### ISSUE THREAD

**Issue by Potatoaim360** [AdguardTeam/AdguardFilters#152260]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

*

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

https://files.technicalatg.com/n0LMSfH
https://cordtpoint.co.in/?go=3f738aa5

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

 <comment>
1.First Page Has A 25 Second Timer Then Second Page Has Anti Adb & Timer,There Is Text Based Ads Too
</Comment>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
Next time please do the report via our reporting tool (click submit about an issue in our products or use [this link](https://reports.adguard.com/en/new_issue.html)).
Also note that one report should contain only one domain.

**Comment by zloyden** [comment]
Also fixed it. Update should available in 2-3 hours.
