### ISSUE TITLE
[Android] can't access login.wi-fi.ru - certificate issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1523]
![image](https://cloud.githubusercontent.com/assets/15856304/13003342/c57483b6-d17d-11e5-94bc-40fe72ac16b6.png)

Режим сжатия в браузере Opera отключен
Попробовал также открыть страничку в браузере Chrome (скрин во вложении). Никаких предупреждений не отображается, идет постоянная попытка обновить страницу

![image](https://cloud.githubusercontent.com/assets/15856304/13003361/e166077a-d17d-11e5-8c20-97a48bdc4990.png)

Только благодаря выключенному приложению удается авторизоваться на сайте. Тест провожу регулярно: с выключенным adguard проблем с авторизацией нет, с включенным есть (ранее предлствлял скрины)

DPB-793-96698

**Comment by Alex-302** [comment]
Думаю это совпадение. Видел такое несколько раз(довольно давно), и от Адгарда не зависело. Проблема из-за их сертификатов. Последний месяц такого не припомню.

**Comment by evgeniy-ADG** [comment]
Там у вас вендор по этомоу вопросу висит, можете как-то толково-профессионально ему ответить? Я не осилю ) Если что, закрывайте.

**Comment by Alex-302** [comment]
http://cdn.vmet.ro/vmetro/faq/connection-problems
последний пункт

**Comment by Alex-302** [comment]
@evgeniy-ADG 
а попроси сделать полный лог, с указанием времени ошибки
