### ISSUE TITLE
Facebook (Onion site) login / create account banner annoyance

### ISSUE THREAD

**Issue by antermin** [AdguardTeam/AdguardFilters#152491]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.49.2

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.facebookwkhpilnemxj7asaniu7vnjjbiltxjqhye3mhbshg7kx5tfyd.onion/kadokawataiwan/photos/a.120278361071648/122858280813656/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Japanese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyList

### Add your comment and screenshots

1. Browser: Tor Browser (since it is about the Onion site, so Tor Browser or Brave's Tor window is needed)
2. When I click into Facebook posts, there is a banner urging the user to log in or to create an account. It is an annoyance since:
  * There is no way to close the banner
  * Comments and image are obscured by the banner, and there is no way to see the obscured part

3. Screenshots
<details><summary>Screenshot 1:</summary>

![screenshot-1](https://github.com/AdguardTeam/AdguardFilters/assets/103918092/5413892f-bca1-4f30-a211-b41fc0a23855)

</details>

<details><summary>Screenshot 2:</summary>

![screenshot-2](https://github.com/AdguardTeam/AdguardFilters/assets/103918092/c8c0d5a6-b3a5-4e28-9b1f-2f018148cba4)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. As I remember, hiding of this popup may break their player in some cases.
