### ISSUE TITLE
YouTube doesn't work properly with AdGuard enabled

### ISSUE THREAD

**Issue by veidne** [AdguardTeam/AdguardFilters#152593]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.56

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

youtube.com

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. <comment> YouTube doesn't load properly with AdGuard on, turning it off solves the problem. Main page gets completely blank, nothing is loading.
Sometimes when I refresh the page it starts working but eg. the comments are not loading or the video is on but the rest of the page is blank, just the player with a blank background.

3. Screenshots
<details><summary>Screenshot 1: what the player looks like with AdGuard on</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/135314713/417b537d-e72e-4716-8c84-db0ebfe6feb9)

</details>

<details><summary>Screenshot N: what the YouTube main page looks like with AdGuard on</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/135314713/72be8d6f-5ffc-48ac-9b7e-513968a4a593)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Did you try to disable user filter? Any stealth options enabled?

**Comment by veidne** [comment]
> Did you try to disable user filter? Any stealth options enabled?

I deleted the AdGuard extension from Chrome, reinstalled it and it helped, so far it works.
