### ISSUE TITLE
[iOS] nbc4i.com - video don't load

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1526]
Incorrect blocking on page:

Videos don't load. 

http://nbc4i.com/2016/02/10/darrons-path-to-the-draft-preparing-for-the-nfl-combine/

BCN-683-96645

**Comment by Alex-302** [comment]
Can't confirm. Works fine with user's filter list.

**Comment by evgeniy-ADG** [comment]
@Serzh-SUP ты можешь на своих айфонах проверить?
