### ISSUE TITLE
`apple.com/metrics/` breaks WWDC livestream

### ISSUE THREAD

**Issue by yokoffing** [AdguardTeam/AdguardFilters#152894]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

n/a

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.apple.com/apple-events/event-stream/

### What filters do you have enabled?

AdGuard Tracking Protection filter

### Add your comment and screenshots

`||apple.com/metrics/` breaks playing the stream on https://www.apple.com/apple-events/event-stream/.

Try `@@||apple.com/metrics/ac-analytics/*/scripts/ac-analytics.js$script,1p`

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
We already have `@@||apple.com/metrics/ac-analytics/*/scripts/$domain=apple.com`
