### ISSUE TITLE
[iOS] google shopping issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1530]
Incorrect blocking on page:
https://www.google.co.uk/search?nota=1&complete=0&site=webhp&source=hp&ei=K965VqXqDcub6ATcmZ2oDQ&q=plug+flip+sink&oq=plug+flip+sink&gs_l=mobile-gws-hp.3...1865.5097.0.5323.0.0.0.0.0.0.0.0..0.0....0...1c.1.64.mobile-gws-hp..0.0.0.Qy0huNLh3s8

If I click any of the shopping results I get a page failure and can't even report that page with Adblock. This happens to any search and shopping on Google. If I disable Adblock it works

<details>
1st screenshot shows google shopping results
![image](https://cloud.githubusercontent.com/assets/15856304/13006779/eaa8724e-d193-11e5-8d0b-a2e17908edc8.png)

2nd screenshot shows what happens when I click any shopping result (not just this search, all searches)
![image](https://cloud.githubusercontent.com/assets/15856304/13006783/f4de9fa4-d193-11e5-9d1d-5957f116f0f6.png)

3rd screenshot shows Adghard when I try to report that page
![image](https://cloud.githubusercontent.com/assets/15856304/13006784/fb413f3c-d193-11e5-9c8e-26b4686618fa.png)

OLQ-316-28524

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Can't open this page, redirect to the search page.
Need description of steps to reproduce.

**Comment by evgeniy-ADG** [comment]
Google shopping is available in UK, not in our countries. Do you have a proxy or VPN with UK IP?

**Comment by Alex-302** [comment]
@evgeniy-ADG 
попроси юзера выключить все фильтры, оставив включенным Адгард и проверить без фильтров.
сли откроется нормально, нужно включать фильтры по одному с проверкой. После включения фильтров возможно надо будет несколько секунд подождать. Английский фильтр желательно проверять последним.
