### ISSUE TITLE
coursedrive.org

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#153016]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.49.3rc16

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://coursedrive.org`

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

1. <comment>
There's a small ad placeholder gap in between some of the articles. I fixed it with this:
`coursedrive.org##[class*="is-gap-"] > .block-inner > *:style(padding-left: unset !important; padding-right: unset !important;)`

2. Screenshots
<details><summary>Screenshot 1:</summary>

![243000834-7db3539d-764d-4c58-8d39-bcb96fd366a5](https://github.com/AdguardTeam/AdguardFilters/assets/89158249/af542ae3-f665-4ae9-8879-cdf2bd6c22d1)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reprodcued

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/538eeb78-a9e5-4250-bb16-0fca98f55f0f)


</details>

**Comment by Sonic5435325** [comment]
@Alex-302 I'm on Firefox 114.0 and uBlock Origin development release (version 1.49.3rc16), can you reproduce with those?

**Comment by Alex-302** [comment]
Added `coursedrive.org##.block-inner > div.cours-adsense-in-feed ~ br`
