### ISSUE TITLE
gae2-spclient.spotify.com

### ISSUE THREAD

**Issue by Hanif9** [AdguardTeam/AdguardFilters#153137]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://open.spotify.com

### What filters do you have enabled?

AdGuard Tracking Protection filter

### Add your comment and screenshots

filter `||gae2-spclient.spotify.com^`
in **_SpywareFilter/sections/tracking_servers_firstparty.txt_**

...is breaking spotify player. Adding exception will restore functionality, however, whether it's function as tracker or not is not known. Need clarification for the filter.

### Privacy

- [x] I agree to follow this condition

**Comment by Alex-302** [comment]
Can't reproduce. Also we don't have rules for `gae2-spclient.spotify.com`
![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/0d2a25b3-f537-4f0d-b166-459e680b2c74)

**Comment by AdamWr** [comment]
This rule has been removed yesterday - https://github.com/AdguardTeam/AdguardFilters/commit/9dcdefdaf2e3582d7b013067b766c1b3320e7d74
By the way, this request may depends on location (I mean `gae2` part).

**Comment by Alex-302** [comment]
Thanks
