### ISSUE TITLE
3movs.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#15313]
**Site**: https://www.3movs.com/videos/76448/michelle-martinez-gets-pounded-doggystyle-in-pov/

**Issue**: Please remove the empty ad banner on the page.

**Screenshot**: http://prntscr.com/ja97xk

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.117 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
A gentle reminder. Thanks

**Comment by Alex-302** [comment]
Not reproduced. Removed leftover at the bottom.
