### ISSUE TITLE
pcgamingwiki.com

### ISSUE THREAD

**Issue by MasterKia** [AdguardTeam/AdguardFilters#153222]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

-

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://www.pcgamingwiki.com/wiki/Grand_Theft_Auto_V`

### What filters do you have enabled?

AdGuard URL Tracking filter

### Add your comment and screenshots

Some links in the `Availability` section have tracking parameters:
`https://www.pcgamingwiki.com/wiki/Grand_Theft_Auto_V#Availability`

```adb
! https://epicgames.com/p/grand-theft-auto-v?epic_affiliate=pcgamingwiki
! https://gamersgate.com/product/grand-theft-auto-v-premium-edition?caff=5418682
! https://humblebundle.com/store/grand-theft-auto-v-premium-edition?partner=pcgw
||epicgames.com^$removeparam=epic_affiliate
||gamersgate.com^$removeparam=caff
||humblebundle.com^$removeparam=partner
```

The list already contains some filters for `humblebundle.com`.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
This is not tracking, just aff links. They are constant.

**Comment by Alex-302** [comment]
> double standard

Why? Removing of that parameters does not break links to discounts as I know.

**Comment by Alex-302** [comment]
@MasterKia Are you sure? Do you have a sample link?

**Comment by Alex-302** [comment]
Well, better we block that (and new similar) parameters. Added your rules.
