### ISSUE TITLE
Thisisanfield application is showing ads

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardFilters#15320]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: The application Thisisanfield is showing ads in news feed
* **Current behaviour**: Showing ads in news feed

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://files.slack.com/files-pri/T0B41S97U-FADM6KLHK/screenshot_20180426-115614.jpg)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://files.slack.com/files-pri/T0B41S97U-FADM6KLHK/screenshot_20180426-115614.jpg)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | 
Operating system version (Android/iOS) | Android
Browser:                               | Internal
AdGuard version:                       | 2.11.81
Filters enabled:                       | Default
AdGuard mode (Android only):           | Auto
Filtering quality (Android only):      | Simplified
HTTPS filtering (Android only):        | On
AdGuard DNS:                           | Default
Helpdesk ID (if exists):               | 1838973

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by TheHasagi** [comment]
[https://uploads.adguard.com/up22_hz1iz.png](url)

**Comment by Alex-302** [comment]
I need screenshot and AdGuard version.
`HTTPS filtering (Android only): | On`
it is disabled or not working.

**Comment by TheHasagi** [comment]
![img_20180427_183449](https://user-images.githubusercontent.com/37797229/39371241-c6d4b7e8-4a49-11e8-811a-002a6c237c10.jpg)
![screenshot_20180426-115614](https://user-images.githubusercontent.com/37797229/39371242-c6f52de8-4a49-11e8-8166-4df11c81a306.jpg)
Android version is 2.11.81

**Comment by Alex-302** [comment]
I mean Android version:) Is it 6+ without root?

**Comment by Alex-302** [comment]
If 6+, try `||graph.facebook.com^$app=com.goodbarber.thisisanfield1`

**Comment by bug-killer** [comment]
Reply from the customer: Android 8.0, not rooted.

**Comment by Alex-302** [comment]
@bug-killer 
https://github.com/AdguardTeam/AdguardFilters/issues/15320#issuecomment-385012226
