### ISSUE TITLE
dlpsgame.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#153363]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.1

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://dlpsgame.com/dead-rising-4-franks-big-package-ps4-download-free/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Block third-party Authorization header, Block WebRTC, Block Push API, Block Location API, Hide Referrer from third-parties (specify in comment below, if used custom value), Hide your User-Agent (specify in comment below, if used custom value), Mask your IP address (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

cloudflare challsnge screen doesnt show unless adguard is disabled tbefore cant access site

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
https://github.com/AdguardTeam/AdguardFilters/assets/118186787/f6f80d49-d497-4fd0-96a6-59b32c3d2aef

this is all it does

**Comment by jordanswrld94** [comment]
same problem with ps4pkg.com

**Comment by jordanswrld94** [comment]
@Alex-302

**Comment by jordanswrld94** [comment]
ok. looks like this is just a problem with tracking protection i guess. when i choose high instead of ultimate the sites work. sorry

**Comment by Alex-302** [comment]
@jordanswrld94 Better use custom settings instead of pre-defined profiles (like a bunch of unknown pills, when trying to cure a disease :) ) and make an informed choice.
