### ISSUE TITLE
anothersadtrombone.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#153419]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.49.3rc16

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://www.anothersadtrombone.com/`

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

![244954896-806c6239-3e64-47d9-8086-f0db8fa64ae6](https://github.com/AdguardTeam/AdguardFilters/assets/89158249/1b86aa83-b40f-4035-82f0-327ad7295b2a)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sonic5435325** [comment]
@Alex-302 Uh, no fix?

**Comment by Alex-302** [comment]
What is wrong on this site?

**Comment by Alex-302** [comment]
Less than minor:)
