### ISSUE TITLE
Google Feed Missed ads

### ISSUE THREAD

**Issue by pkp24** [AdguardTeam/AdguardFilters#153594]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0.910

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

Google Feed on far left screen

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter

### Add your comment and screenshots

1. If I refresh filters and then refresh my Google feed it will get most ads, but some game ads still show up.  There needs to be both an increase in refreshing filters and a way to not miss some of those ads. 

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
@pkp24 Did you see the advertisement on your tablet?

**Comment by pkp24** [comment]
I saw it on my android phone From: PiQuark6046Sent: Friday, June 16, 2023 7:18 AMTo: AdguardTeam/AdguardFiltersCc: pkp24; MentionSubject: Re: [AdguardTeam/AdguardFilters] Google Feed Missed ads (Issue ***@***.*** Did you see the advertisement on your tablet?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by piquark6046** [comment]
Actually, I cannot reproduce it.
