### ISSUE TITLE
:sweat_smile: why u default interception localhost?The result is a waste of time looking for bugs on the website

### ISSUE THREAD

**Issue by specked2527** [AdguardTeam/AdguardFilters#153663]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.56

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

localhost:8096/web/index.htm

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. <comment>
I can't open my webpage, I can open it after disabling blocking

2. Screenshots
<details><summary>Screenshot 1:</summary>

![20230614143014](https://github.com/AdguardTeam/AdguardFilters/assets/124735279/36dbb2cd-61cd-43f7-ba2b-e82155b41b0b)
</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Which rule breaks it?

**Comment by specked2527** [comment]
@Alex-302  

rule @@://localhost:$generichide

Only when I turn off AdGuard, I can open http://localhost:8096/ and vice versa, when AdGuard is on by default, I can't open http://localhost:8096/

![20230614164648](https://github.com/AdguardTeam/AdguardFilters/assets/124735279/637e1649-edb3-453e-b4f5-05edb041adc0)

**Comment by Alex-302** [comment]
This rule is an unblocking rule. It prevents applying generic element hiding rules.
What is broken?

**Comment by specked2527** [comment]
@Alex-302 Since there is no more log information, I don't know what is causing the webpage to not open. If you really want to solve the BUG, download and install Jellyfin, reproduce the environment, and see if you can open it

**Comment by Alex-302** [comment]
Is it for Linux only?

**Comment by specked2527** [comment]
:sweat_smile: My installation environment is WINDOWS, and localhost:8096 cannot be opened on WINDOWS.
Forget it, define the BUG as a Jellyfin problem, Close issue.
