### ISSUE TITLE
mail.google.com: app menu incorrectly blocked by annoyances filter

### ISSUE THREAD

**Issue by csdev** [AdguardTeam/AdguardFilters#153634]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

AdGuard Annoyances filter 2.1.63.9

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://mail.google.com

### What filters do you have enabled?

AdGuard Annoyances filter

## Description

I am using the AdGuard Annoyances filter in uBlock Origin. One of the filters is blocking the app menu on mail.google.com.

https://github.com/AdguardTeam/AdguardFilters/blob/d62f29389f5b42d95fe3a5727d96a268976f72d0/AnnoyancesFilter/Other/sections/self-promo.txt#L37

As a temporary workaround, I had to add a filter exception:
```
mail.google.com#@#header[role="banner"] > div[class^="gb_"] > div[class^="gb_"][data-ogsr-up] > div[style^="overflow: hidden; position: absolute; top: 0px; width: 370px; z-index:"]
```

## Screenshots
<details><summary>Screenshot 1: Blocked element</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/1824428/8401e4a6-d6ef-4f43-93f7-cc04e15f5a87)

</details>

<details><summary>Screenshot 2: Filter highlighted in uBlock Origin logger</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/1824428/e7b17d7d-8083-4d28-af08-cab928960b15)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
Cannot reproduce with my Google accounts (AdGuard enterprise and personal one ).
@AdguardTeam/filters-maintainers Please take a look.
