### ISSUE TITLE
Block Twitter hijacker

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#153603]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.56

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

http://shindaan.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Japanese filter

### Add your comment and screenshots

1. According to `https://twitter.com/yuusultultu/status/1668185343907237888` the site is trying to hijack Twitter account of user who allowed account access. Please check it. The site is shown only on mobile UA.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![shindaan](https://github.com/AdguardTeam/AdguardFilters/assets/58900598/03747e41-94c9-4c89-a84c-b74d0bf8435f)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Yuki2718** [comment]
@VladisLoveZh

**Comment by piquark6046** [comment]
Left a message in AdGuard Slack.

**Comment by Eugene-Savenko** [comment]
Fixed: https://reports.adguard.com/en/shindaan.com/report.html
