### ISSUE TITLE
yenisafak.com

### ISSUE THREAD

**Issue by qzcz** [AdguardTeam/AdguardFilters#153715]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.56

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.yenisafak.com/teknoloji/abd-ve-avrupada-yapay-zeka-markaji-4535824

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

It is a 3rd party live tv for advertising purposes.

<details><summary>Screenshot 1:</summary>

![resim](https://github.com/AdguardTeam/AdguardFilters/assets/110184059/ae12e1f0-8ba8-4c6a-844f-506ff8d8b496)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
