### ISSUE TITLE
adf.ly

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#153778]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.49.3rc16

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://adf.ly

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, EasyList, EasyPrivacy, Fanboy's Annoyances, Web Annoyances Ultralist, Peter Lowe's Blocklist, Online Malicious URL Blocklist, EasyList Cookie List, Legitimate URL Shortener

### Add your comment and screenshots

1. <comment>
Adf.ly seems to be dead, it redirects to `https://migrate-adfly.linkvertise.com`. All of it's other subdomains don't seem to work anymore either

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
That's great)
