### ISSUE TITLE
yenibiris.com

### ISSUE THREAD

**Issue by qzcz** [AdguardTeam/AdguardFilters#153713]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.56

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.yenibiris.com/is-ilanlari/izmir

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

yenibiris.com##.spotJobcont

<details><summary>Screenshot</summary>

![resim](https://github.com/AdguardTeam/AdguardFilters/assets/110184059/5e994aa3-dd44-4e8a-a90d-04155bfde4f1)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
These search results shouldn't be removed, but I blocked the leftover.

> yenibiris.com##.spotJobcont

You can use this rule in User rules.
