### ISSUE TITLE
Planet Rock

### ISSUE THREAD

**Issue by UrbainKnight** [AdguardTeam/AdguardFilters#153837]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Planet Rock application keeps luanching a popup asking you to rate the app but however many stars you give it you cannot submit it. If you click not now it goes awayfor a few seconds then pops up again. I have been reporting this to them as a bug since January they have released 3 new versions of the app not one as fixed it.

### Proposed solution

Can Adgaurd block this application pop up I have tried enabling popup blockers but I think they are just for websites

### Additional information

I an running OSX Ventura 13.4 on a M1 iMac the Planet Rock app version is now 9.21.3(3937)

**Comment by Alex-302** [comment]
Please do not use `Feature request` for reporting problems.
You can report from AdGuard menu with download link and steps to reproduce.
