### ISSUE TITLE
waka.com: livestream broken

### ISSUE THREAD

**Issue by liamengland1** [AdguardTeam/AdguardFilters#153879]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.56

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.waka.com/watch-live/

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

The livestream is broken

Please remove the filter `||snippet.univtec.com/js/new.js` and add `@@||doubleclick.net/ssai/*/streams$xhr,domain=snippet.univtec.com`

See https://github.com/uBlockOrigin/uAssets/issues/18541

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
@Alex-302 can you still reproduce adblock detection from this issue with the rule removed?
https://github.com/AdguardTeam/AdguardFilters/issues/150025

I cannot reprduce any adblock detection on mentioned page.

**Comment by Alex-302** [comment]
It seems it is fixed in Easylist by
`@@||imasdk.googleapis.com/js/sdkloader/ima3_dai.js`
