### ISSUE TITLE
false positive nip.io

### ISSUE THREAD

**Issue by vehlwn** [AdguardTeam/AdguardFilters#153802]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

It's dns.adguard-dns.com server

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

nip.io

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

Why did `nip.io` domain get blocked? This is a legitimate service providing free DNS records. Now it resolves all subdomains to all-zero record.

```
; <<>> DiG 9.18.15 <<>> @dns.adguard-dns.com +tls nip.io 10.0.0.1.nip.io. 127.0.0.1.nip.io
; (4 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59608
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 0
;; QUESTION SECTION:
;nip.io.				IN	A

;; ANSWER SECTION:
nip.io.			3600	IN	A	0.0.0.0

;; Query time: 156 msec
;; SERVER: 94.140.14.14#853(dns.adguard-dns.com) (TLS)
;; WHEN: Fri Jun 16 10:26:27 +04 2023
;; MSG SIZE  rcvd: 51

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44614
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 0
;; QUESTION SECTION:
;10.0.0.1.nip.io.		IN	A

;; ANSWER SECTION:
10.0.0.1.nip.io.	3600	IN	A	0.0.0.0

;; Query time: 160 msec
;; SERVER: 94.140.14.14#853(dns.adguard-dns.com) (TLS)
;; WHEN: Fri Jun 16 10:26:27 +04 2023
;; MSG SIZE  rcvd: 60

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8048
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 0
;; QUESTION SECTION:
;127.0.0.1.nip.io.		IN	A

;; ANSWER SECTION:
127.0.0.1.nip.io.	3600	IN	A	0.0.0.0

;; Query time: 160 msec
;; SERVER: 94.140.14.14#853(dns.adguard-dns.com) (TLS)
;; WHEN: Fri Jun 16 10:26:28 +04 2023
;; MSG SIZE  rcvd: 61
```

### Privacy

- [X] I agree to follow this condition

**Comment by vehlwn** [comment]
PS: I've found [this](https://github.com/easylist/easylist/commit/68d7a669e6cdc270d7ef67c6f13faa3f2deca207) commit in EasyPrivacy list because this domain points to localhost.

**Comment by jellizaveta** [comment]
@vehlwn Hello, this is done for security reasons. These filters are currently disabled. Related issue: https://github.com/easylist/easylist/issues/16372
