### ISSUE TITLE
GoodbyeAds Spotify

### ISSUE THREAD

**Issue by Eow2022yia** [AdguardTeam/AdguardFilters#153967]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Spotify-AdBlock.txt

Hi there,

Would you please consider adding GoodbyeAds Spotify to your lists/hosts?

This can reduce Spotify ads and it does not break the app/website.

Thank you.

### Proposed solution

Add this blocklist to your free DNS service.

**Comment by Alex-302** [comment]
Hi. No. Not sure if ads in spotify can be blocked in this way. Also this is dangerous. And this filter contains wide rules, not related to Spotify at all.
