### ISSUE TITLE
txxx.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#15408]
**Site**: https://www.txxx.com/videos/5313621/my-dirty-hobby-some-exercising-and-fucking-for-cool-down/?promo=10306

**Issue**: Please remove the ad on the page.

**Screenshot**: http://prntscr.com/jb0i1w

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.139 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by BlazDT** [comment]
Was fixed in another request.

**Comment by Nzzyme** [comment]
https://txxx.com/videos/3853642/kenzie-taylor-mick-blue-mick-blue-and-maestro-claudio-in-three-hole-kenzie-s-foot-fun-evilangel/?fr=3853642


Unable to play the video when AG is enabled

http://prntscr.com/pnwp3x

As soon as I disable AG, it reloads the page and plays

**Comment by BlazDT** [comment]
Fixed delayed play button.
