### ISSUE TITLE
porngem.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#15407]
**Site**: https://www.porngem.com/videos/anal-puppets-masters-jasmine-black-cherry-jul-defrancesca-gallardo-cj-liz-sorana-nikita-37829/?utm_source=pbweb&utm_medium=pbweb&utm_campaign=pbweb

**Issue**: Please remove the ad on the page.

**Screenshot**: http://prntscr.com/jb0h2g

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.139 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by BlazDT** [comment]
Overlay not reproduced, please check @AdamWr

**Comment by AdamWr** [comment]
Fixed.
