### ISSUE TITLE
wankoz.com [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#15406]
**Site**: https://www.wankoz.com/videos/359658/emily-austin-loves-bbc/?utm_source=pbwmed&utm_medium=cpc&utm_campaign=wank

**Issue**: Please remove the ad on the page.

**Screenshot**: http://prntscr.com/jb0bpo

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.139 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by Nzzyme** [comment]
Seeing pop-up when moving the slider on the video player
https://www.wankoz.com/videos/354760/chic-transforms-herself-into-a-slut/

**Comment by Alex-302** [comment]
fixed

**Comment by Nzzyme** [comment]
Seeing an ad banner on player after video completes.

https://prnt.sc/r2g2oc

**Comment by BlazDT** [comment]
Fixed
