### ISSUE TITLE
thepiratebay.party

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#154176]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

4.1.56

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://thepiratebay.party/torrent/69556736/Windows_XP_Professional_SP3_x86_-_Integral_Edition_2023.6.16

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter

### Add your comment and screenshots

##a[href^="https://www.onlineuserdefender.com/torrent-guard/"]

removes fake button on multiple pirate bay websites

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/d0d3c934a6085a3306c9848e4a690e785217dfc1#diff-f1ada99e961d4ff727cacd855a19ff844c71d56e51e181fc66b02bcee5e00699R258
