### ISSUE TITLE
spotify.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#154172]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.56

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://open.spotify.com/playlist/2MugcniD7704oTlF3fyByp

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

||spotify.com/gabo-receiver-service/public/v3/events
||spotify.com/gabo-receiver-service/v3/events
||adeventtrackermonitoring.spotify.com

the first two i asssume are trackers because they show up multiple times in log. second is fine with being blocked. spotify ads still play fine when using non spotify premium account.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Unfortunately, cannot find `||adeventtrackermonitoring.spotify.com^` in log.

**Comment by jellizaveta** [comment]
`||spotify.com/gabo-receiver-service/` - looks like something to debug configuration and playback

**Comment by jellizaveta** [comment]
> adeventtrackermonitoring.spotify.com

Could you show this query in the filtering log or in the network tab?

**Comment by jordanswrld94** [comment]
> > adeventtrackermonitoring.spotify.com
> 
> Could you show this query in the filtering log or in the network tab?

![Untitled](https://github.com/AdguardTeam/AdguardFilters/assets/118186787/d7b6c767-6829-4d23-a48a-201123e01f34)
