### ISSUE TITLE
qha.com.tr

### ISSUE THREAD

**Issue by qzcz** [AdguardTeam/AdguardFilters#154199]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.56

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.qha.com.tr/gundem/turkiye-galler-mac-sonucu-2-0-473994

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

<details><summary>Screenshot</summary>

![resim](https://github.com/AdguardTeam/AdguardFilters/assets/110184059/6e3e53ca-fb10-4dcb-87b6-a05815ae86ca)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
The website has low visitors.
