### ISSUE TITLE
medicalnewstoday.com [Ad Strings]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#15439]
**Site**: https://www.medicalnewstoday.com/kc/antidepressants-work-248320

**Issue**: Please remove the Ad string & empty ad banners at various places on the page (especially on the right side).

**Screenshot**: http://prntscr.com/jb7z7t and http://prntscr.com/jb7ze9

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.139 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Top element is empty and is used possibly for some other content of the site than ads. Therefore not hidden via #$#.
