### ISSUE TITLE
tweakers.net

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#154360]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.1b4

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://tweakers.net/

### What filters do you have enabled?

AdGuard Tracking Protection filter, EasyPrivacy

### Add your comment and screenshots

1. <comment>
Possible trackers
`||tweakers.net/i/*/1280x400/`
`||tweakers.nl/track/`

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
