### ISSUE TITLE
revadvert.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#154459]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.1b5

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://revadvert.com/

### What filters do you have enabled?

AdGuard Social Media filter, AdGuard Other Annoyances filter, AdGuard Base filter, EasyList, uBlock filters

### Add your comment and screenshots

1. <comment>
AdGuard - Other Annoyances has the filter `##.td_block_social_counter`. It seems better to add it to the Social filter list.

Also, in uBlock filters, `revadvert.com##^script:has-text(fakeAd)` is used to get rid of the Anti-AdBlock message instead of just `revadvert.com###AdbModel`.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot from 2023-06-22 18-46-11](https://github.com/AdguardTeam/AdguardFilters/assets/89158249/986e4e26-2bfc-4025-a4fd-73a7f538efd6)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
>AdGuard - Other Annoyances has the filter `##.td_block_social_counter`. It seems better to add it to the Social filter list.

We do not block such elements in social filter, so it's okay.

>Also, in uBlock filters, `revadvert.com##^script:has-text(fakeAd)` is used to get rid of the Anti-AdBlock message instead of just `revadvert.com###AdbModel`.

`revadvert.com###AdbModel` is compatible with all extensions/apps, while `##^` rules are supported only by extension for Firefox and apps (Android, Mac, Windows), so it's not necessary in this case.

**Comment by Sonic5435325** [comment]
@AdamWr `@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=revadvert.com` could also be added to defuse the Anti-AdBlock message.

**Comment by AdamWr** [comment]
It's not necessary to unblock ad request in case if anti-adblock message can be just hidden.
