### ISSUE TITLE
jeuxvideo.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#154471]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.1b5

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.jeuxvideo.com/

### What filters do you have enabled?

AdGuard Cookie Notices filter, EasyList Cookie List

### Add your comment and screenshots

1. <comment>
There's a cookie notice because of `@@||sdk.privacy-center.org^$from=jeuxvideo.com` in AdGuard - Cookie Notices. I could only find two closed issues for this site, and both seem to be related to ads.

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
As I can see, the cookies can't be blocked, otherwise that will lead to the incorrect blocking.
Unfortunately, uBO does not support some of our rules, that work fine on AdGuard products.
