### ISSUE TITLE
mmotutkunlari.com

### ISSUE THREAD

**Issue by qzcz** [AdguardTeam/AdguardFilters#154458]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.56

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.mmotutkunlari.com/konu/altyapi-v1-v2-v3-yayinda-server-files-teknik-destek-hizmetleri-sifirdan-files-tasarim-kisa-sure-25-indirimli.15055/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

<details><summary>Screenshot</summary>

![resim](https://github.com/AdguardTeam/AdguardFilters/assets/110184059/5ea3a4ce-4766-4811-a42d-5cc2d2a55224)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
Unfortunately, the reported issue does not satisfy our [filters policy](https://kb.adguard.com/en/general/adguard-filter-policy).

This site has too little traffic.

Please add to your user rules:
```
||mmotutkunlari.com/styles/sponsor/
mmotutkunlari.com###tanitim_alani
```
