### ISSUE TITLE
RB.GY is filtered as adult site which it isn't

### ISSUE THREAD

**Issue by hw121693** [AdguardTeam/AdguardFilters#154406]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

DNS server

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://free-url-shortener.rb.gy/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter

### Add your comment and screenshots

1. https://free-url-shortener.rb.gy/ is just a URL shortener

2. Screenshots
<summary>Screenshot with adult filter enabled:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/15042485/660520cd-0228-492c-9f6d-98f2d47efe27)

<summary>Screenshot without adult filter enabled:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/15042485/ce54972d-3b69-4d09-b66d-d1c3e66396a0)

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
The domain was removed from the list. The update should be available today.
