### ISSUE TITLE
hulu (roku)

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#154580]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

latest

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Desktop

### Where is the problem encountered?

hulu app on roku

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard DNS filter

### Add your comment and screenshots

cdn-media.brightline.tv shows up in dns log when opening hulu app on roku

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Cannot check.
