### ISSUE TITLE
[iOS] dailylocal.com 

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1547]
The ads are blocked but the story links become broken unless I reload without the blocker. 
NKN-813-74656

**Comment by Alex-302** [comment]
@Bohdan-SUP 
Need the screenshot.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
bump

**Comment by Bohdan-SUP** [comment]
Wrote a follow up.

**Comment by evgeniy-ADG** [comment]
@Alex-302 

> The ads are blocked but the links to the news stories (by clicking on the story title) are broken when AdGuard is active.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
I need the actual filter list. Can't reproduce in Safari on Mac.
