### ISSUE TITLE
flightradar24.com

### ISSUE THREAD

**Issue by pubct** [AdguardTeam/AdguardFilters#154714]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.flightradar24.com/blog/paris-air-show-2023/

### What filters do you have enabled?

AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, EasyList, EasyPrivacy, Online Malicious URL Blocklist

### Add your comment and screenshots

Under "Scenes from Paris Air Show Day 2" section, there are 3 images.
With **AdGuard – Popups filter** enabled, clicking on the images pop up empty.
Only with the mentioned filter disabled, the images could pop up after clicking on it.

Thank you.

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
