### ISSUE TITLE
getadblock.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#154762]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.1b6

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://getadblock.com/

### What filters do you have enabled?

AdGuard Cookie Notices filter, EasyList Cookie List

### Add your comment and screenshots

1. <comment>
Cookie script
`getadblock.com/js/cookie_notification.js`

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
im not getting any cookie popups

**Comment by Sonic5435325** [comment]
That's a script to run a cookie consent message. I reported it because blocking it doesn't seem to break anything.

**Comment by jordanswrld94** [comment]
oh ok. my bad
