### ISSUE TITLE
abcya.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#154798]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.1b6

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.abcya.com/

### What filters do you have enabled?

AdGuard Cookie Notices filter, EasyList Cookie List

### Add your comment and screenshots

1. <comment>
Cookie filter list causes a gap to appear at the top of the page.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![249037426-2408eab4-8d6d-456d-822a-e0a3cbad5c89](https://github.com/AdguardTeam/AdguardFilters/assets/89158249/6bc3de49-7ba4-4d85-82fc-911b71f21403)

</details>

<details><summary>Screenshot 2:</summary>

![249037435-3cdf5809-7d4a-4950-ae5f-aff91be99358](https://github.com/AdguardTeam/AdguardFilters/assets/89158249/768fe669-fd30-4960-86b1-9b6c3bf59b2d)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Seems that the our scriptlet rule does not work properly in uBO, but it's fine in AdGuard products.
Added a temporary solution.

**Comment by zloyden** [comment]
Changed the current rule a bit.

**Comment by Sonic5435325** [comment]
Rule seems to work perfectly! Thank you!
