### ISSUE TITLE
Whitelisting the qbittorrent web GUI

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#15474]
В локальной сети имеется сервер с qbittorrent v.4.0.4 с доступом через web gui. обращение к серверу происходит только по доменному имени по http://rozhkovets.ddns.com:45000. Проблема в том, что web gui qbittorrent с включенной фильтрацией отображается некорректно. Страница авторизации отображается без изображений и иногда после авторизации сервер возвращает http error 401 или страница выглядит как на скриншоте. поэтому я внес адрес сервера в белый список, но ситуация не изменилась, помогает только полное отключение фильтрации

<details> <summary> Screenshots </summary> 

![image](https://user-images.githubusercontent.com/15856304/39404019-4d77de6c-4b92-11e8-9c05-a06a9ba63ff5.png)

![image](https://user-images.githubusercontent.com/15856304/39404011-2a12dcc4-4b92-11e8-9839-900c683984e9.png)

</details>

@Alex-302  помгоги завайтлистить, пожалуйста.

**Comment by Alex-302** [comment]
Чем ломается хоть?
Можно так попробовать
`@@||rozhkovets.ddns.com^$document`

**Comment by rozhkovets** [comment]
@Alex-302, не помогло. режим фильтрации - быстрый, через VPN, +https
 также пробовал:
@@||rozhkovets.ddns.name^$network
внешний ip в белый список
внутренний ip в белый список
заходить через firefox, вместо chrome (оба актуальных версий для андроид 8)

**Comment by Alex-302** [comment]
а по такому шаблону исключить, подставив IP?
`@@IP$network`
