### ISSUE TITLE
snapinsta.app

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#154882]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.6

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://snapinsta.app/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Add your comment and screenshots

Once a link of instagram is pasted 

it gives the download option but has an empty popup where close button has to be pressed to get to the download option

![IMG_6972](https://github.com/AdguardTeam/AdguardFilters/assets/46019727/96f8bbb1-c471-4465-853c-c8f04dbdd51f)

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
Please provide more details like steps to reproduce next time.
