### ISSUE TITLE
megashara.org, mediashop.tv, myflixerhd.ru

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#154845]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.1b6

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://megashara.org`
https://mediashop.tv
https://myflixerhd.ru

### What filters do you have enabled?

AdGuard Tracking Protection filter
AdGuard Social Media

### Add your comment and screenshots

1. <comment>
Remove dead domains/invalid filters in Spyware specific.
`megashara.org/uploads/button/online.png`

In Social filter list
myflixerhd.ru
http://seriestv.watch/

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
myflixerhd.ru - this domain is part of a group of similar, ever-changing sites, so I don't see the point in removing it for now
