### ISSUE TITLE
ex.ua

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1548]
Video playback is broken
<details>
![2016-02-02 22 02 44](https://cloud.githubusercontent.com/assets/14153331/13035865/24297980-d362-11e5-8878-444a9f6b268d.png)
</details>

LMA-438-95368

**Comment by Alex-302** [comment]
@Bohdan-SUP 
а у тебя повторяется? Зашёл с прокси - что с Адгардом, что без - ошибка как на экране.
