### ISSUE TITLE
tiktok.com - Mobile App Banner filter list does not block the app banner but does block comment section

### ISSUE THREAD

**Issue by cyaugin** [AdguardTeam/AdguardFilters#154972]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.50

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.tiktok.com

### What filters do you have enabled?

AdGuard Mobile App Banners filter

### Add your comment and screenshots

1. On TikTok, the AdGuard Mobile App Banner filter list fails to block the app banner that occasionally pops up when scrolling.
2. It DOES block the comment section from popping up when tapping the comments button on a video when this is not the apparent purpose of the filter list.

3. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/37916972/c5ef93b6-4822-4c2a-ada8-92c97914c14e)

</details>

<details><summary>Screenshot 2:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/37916972/0af2d2e1-08fc-49f0-a70c-09fdb0e1891a)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Blocked on chrome and click on comment opens google store. Cannot install FF. Please check @zloyden

**Comment by zloyden** [comment]
@BlazDT 

> Blocked on chrome

As I recall, we block similar popups only in our products because uBO does not support some of our rules.

> comment opens google store

I have the same.
