### ISSUE TITLE
keewoach.net ads

### ISSUE THREAD

**Issue by mayankmetha** [AdguardTeam/AdguardFilters#154991]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

DNS

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.wcofun.org/pokemon-season-11-episode-535

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. adds are seen from https://keewoach.net/4/6041393

2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="1323" alt="Screenshot 2023-06-29 at 11 10 28 AM" src="https://github.com/AdguardTeam/AdguardFilters/assets/4472149/eff0ca1d-32bd-4c10-908a-478a6da67c06">

<details><summary>Screenshot 1: Add seen in the screenshot</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
As far as I can see, `keewoach.net` is already blocked by DNS.
It seems that these ads are loaded from `desgolurkom.com` and `neetoutoo.com`, I will add them to ad servers.

**Comment by mayankmetha** [comment]
@AdamWr i still see the ads getting loaded when i'm opening https://www.wcofun.org

**Comment by AdamWr** [comment]
It may take few hours until it will be blocked by DNS.
Please check after few hours again.

**Comment by mayankmetha** [comment]
thanks

**Comment by AdamWr** [comment]
As far as I can see, it should be blocked now.
