### ISSUE TITLE
Filter "Web Annoyances Ultralist" ? 

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#15497]
Can you test and add Filter "Web Annoyances Ultralist":
https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/ultralist.txt ?
It works perfect and more sites ignore adblockers and any show information about using adblockers in this sites.

**Comment by Alex-302** [comment]
will be added

**Comment by seba2282** [comment]
Thank you
