### ISSUE TITLE
[false-positive] sizyreelingly.com

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdguardFilters#154970]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [ ] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.13.2 (build 4287, CL 1.11.114)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Slimjet Version 39.0.2.0 (based on Chromium 111.0.5563.41) (Official Build) (64-bit)

### Which device do you use?

Laptop

### Where is the problem encountered?

**see comment section!** or better yet 👉 https://voe.sx/wijgzlzdytmi  👍 

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Disable cache for third-party requests, Block WebRTC, Block Push API, Block Location API, Hide your User-Agent (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

@AdguardTeam this is one of the `voe.sx`'s temporary redirect domains.
If you're familiar with `voe.sx`,you'd know what i mean 😄 
It was just added today as yesterday there were no issues accessing it. Here is a fresh **test** link:
https://sizyreelingly.com/wijgzlzdytmi
Thank you 👍 

P.S. One more that requiring your attention. Check out this link(make sure that AG's base filter is on):
https://github.com/AdguardTeam/cname-trackers/blob/master/data/ads/adspyglass_justdomains.txt
Do you see the irony  😜 
The rule,itself,should remain as it is very helpfull when browsing,it's just Github needs to added as exception:
`/data/ads/*$domain=~github.com`  👍 

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
`sizyreelingly.com` has been fixed in https://github.com/AdguardTeam/AdguardFilters/commit/00ec5fa4f83e18be6dbc0fb93af20f4c54114e2a
I have added exception for `github.com/AdguardTeam/`

**Comment by dnmTX** [comment]
@AdamWr looks good and thanks for the fast response and resolution 👍
