### ISSUE TITLE
billboard.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#154931]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.1b6

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.billboard.com/

### What filters do you have enabled?

AdGuard Cookie Notices filter, EasyList Cookie List

### Add your comment and screenshots

1. <comment>
"Privacy Preferences" cookie manager button.
Same problem happens on rollingstone.com.
Probably the best solution:
`billboard.com##.o-nav__list-item:has(.privacy-consent)`
2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot from 2023-06-28 13-01-44](https://github.com/AdguardTeam/AdguardFilters/assets/89158249/a1800101-4e74-4260-bbdb-03df75f0eb7f)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It is not an annoyance. Removed previously added rule for another site.
