### ISSUE TITLE
The page my.onvista.de cannot be loaded when "Protect from DPI" is enabled.

### ISSUE THREAD

**Issue by PavelParkhomenko** [AdguardTeam/AdguardFilters#155004]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.13.2

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, Chrome, Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

my.onvista.de

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard Social Media filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of first-party cookies, Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

1. In most cases, the page my.onvista.de cannot be loaded when "Protect from DPI" is enabled.

2. Screenshots
<details><summary>Screenshot 1:</summary>

 
![image](https://github.com/AdguardTeam/AdguardFilters/assets/104919935/f2123c55-4739-47ae-be57-0e23e8d2b83b)

</details>

<details><summary>Screenshot N:</summary>

 
![image](https://github.com/AdguardTeam/AdguardFilters/assets/104919935/9ed97232-8713-4f63-af0a-a464ae1329de)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by PavelParkhomenko** [comment]
@Alex-302

**Comment by Alex-302** [comment]
I can't reproduce. Please test:
`@@||my.onvista.de^$stealth=dpi`

**Comment by PavelParkhomenko** [comment]
The user has reported that the suggested rule helped resolve the issue
