### ISSUE TITLE
A cosmetic filter is not applied if DNS filters list is enabled.

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdguardFilters#155007]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: Android 13 (OneUI 5.1)
- Device: Samsung Galaxy A34 5G
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, List-KR

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable WebRTC, Block Push API, Block Location API, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

Steps to reproduce:
1. Clear cache, cookie and site data of a web browser and restart the web browser entirely.
2. Enable DNS filtering and AdGuard DNS filters list in DNS filtering module.
3. Visit https://lastpass.com/

### Expected Behavior

The element matching `iframe[src^="https://cdn.lmiutil.com/"]` are hidden as AdGuard DNS filters list is disabled.

### Actual Behavior

Even if `lastpass.com##iframe[src^="https://cdn.lmiutil.com/"]` filter is applied, the leftover still appears.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_20230622_192037_Kiwi Browser](https://github.com/AdguardTeam/AdguardForAndroid/assets/98787049/ef1cd47e-93c2-4e66-8d2e-c55b34562bca)

</details>

<details><summary>Screenshot 2:</summary>

![Screenshot_20230622_192122_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/98787049/4e43beac-f9bf-4945-a545-51c405d6a1db)

</details>

### Additional Information

 - https://github.com/AdguardTeam/AdguardFilters/issues/154305

**Comment by Alex-302** [comment]
Not a bug. lastpass.com is in HTTPS exclusions
![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/76c4ffcc-a2ff-4d91-beb8-3fae334d0c1c)
