### ISSUE TITLE
investors.verimatrix.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#155182]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.13

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://investors.verimatrix.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter

### Add your comment and screenshots

||ads.videoadex.com^

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Blocked by `://ads.$` rule in Base filter and `||videoadex.com^` AdGuard French filter
