### ISSUE TITLE
mlsbd.shop

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#155115]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.6

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://mlsbd.shop/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard DNS filter

### Add your comment and screenshots

On clicking any post of the page there is a popup which open in another tab but is blocked in content blocker

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Unfortunately, I cannot reproduce it.
Do you still can reproduce these popups?

**Comment by Bhooty** [comment]
> Unfortunately, I cannot reproduce it.
> Do you still can reproduce these popups?

No sir, seems like this was happening when adguard in ios was acting strange

after stopping and refreshing filters
It got blocked again

**Comment by AdamWr** [comment]
Okay, thank you for your reply.

>strange why do I have the option to close the issue instead of just replying

You can close issue which you have opened directly on GitHub.
But if it would be opened through reporting tool, then you could not do that.

**Comment by Bhooty** [comment]
> Okay, thank you for your reply.
> 
> > strange why do I have the option to close the issue instead of just replying
> 
> You can close issue which you have opened directly on GitHub. But if it would be opened through reporting tool, then you could not do that.

Oww ok sir
Thanks for the clarification. 😅
