### ISSUE TITLE
[Stealth Mode] block third-party cookies option  affects Yandex start page

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1551]
При включенной опции "Блокировать сторонние куки" такая проблема:
- на стартовой странице Яндекс, где показывают твою локацию:
http://prntscr.com/a2mpe1
- не применяются настройки (к примеру, при смене города и определения автоматически), страница снова обновляется и выходит тот же город и те же настройки:
http://prntscr.com/a2mpgl

NLO-503-43195

**Comment by Alex-302** [comment]
@evgeniy-ADG 
на yandex.ru / yandex.ua этой кнопки не вижу
нужня прямая ссылка или описание как до неё добраться

**Comment by evgeniy-ADG** [comment]
http://prntscr.com/a433dd
http://prntscr.com/a4334t

**Comment by Alex-302** [comment]
@evgeniy-ADG 
У вас повторяется?
У меня изменение на
https://tune.yandex.ru/region/
отражается на главной.

**Comment by evgeniy-ADG** [comment]
Мені ось що пише:

![image](https://cloud.githubusercontent.com/assets/15856304/13183227/81fa69f4-d73e-11e5-8c19-574fb10cd83b.png)

: )))

**Comment by evgeniy-ADG** [comment]
@Alex-302 не выходит воспроизвести?

**Comment by evgeniy-ADG** [comment]
у нас еще есть такая же желоба

> Воспользовался вашей рекомендацией и выяснилась такая вещь: при отключении в "Антитрекинге" только "Блокировать сторонние куки" в Яндексе при Мозилле сохраняется нормальная настройка города, а в просто Яндексе все равно остается на на автоматической настройке и постоянно Москва. Отключил функцию "Антитрекинг" и пока вроде стало как надо, те город свой сохраняется, не знаю надолго ли. Хотелось бы иметь полноценную версию Адгарда.

**Comment by Alex-302** [comment]
нет, не повторяется. Это точно при открытии со страницы яндекса, а не при переходе с другого сайта?

**Comment by vgavrish** [comment]
@Alex-302 
да, именно при открытии страницы яндекса, и при нажатии на город: http://prntscr.com/be6l1k
1. идет переход на настройки местоположения: http://prntscr.com/be6pq5
2. убираем галочку с "определять автоматически"
3. вводим какой-то город
4. нажимаем сохранить

и в итоге все равно у нас выставлен изначальный город: http://prntscr.com/be6qh8

**Comment by vgavrish** [comment]
Также такая проблема наблюдается:
При переходе с ссылки 
https://www.google.com.ua/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=active&q=%D1%8F%D0%BD%D0%B4%D0%B5%D0%BA%D1%81+%D0%B4%D0%B8%D1%81%D0%BA "Яндекс.Диск"
![google](https://cloud.githubusercontent.com/assets/18548949/15922692/d1f3d914-2e31-11e6-948f-f41ee19a6ebb.PNG)
Перебрасывает на страницу https://passport.yandex.ru/passport?mode=error&error=nocki
![screenshot_18](https://cloud.githubusercontent.com/assets/18548949/15922731/01b67530-2e32-11e6-9766-39bac07acc98.jpg)
Т.е. переход на диск не осуществляется.

Повторяется. Помогает отключение "Блокировать сторонние куки".

**Comment by Alex-302** [comment]
Передай пожалуйста на проверку:
1. `@@||pass.yandex.ru^$stealth`
2. `@@||disk.yandex.ru^$stealth`

**Comment by Alex-302** [comment]
@vgavrish

**Comment by vgavrish** [comment]
хорошо, сейчас передам

**Comment by Alex-302** [comment]
это вообще не баг, будет пилиться функция самоубивающихся куки и такого больше быть не должно. Пока ждём

**Comment by vgavrish** [comment]
"Никаких изменений (нет разницы авторизирован я на Яндекса или нет)
в Яндекс диск я могу попасть уже из меню сайта Яндекс
не критично, я вам сообщил чтоб вы знали."

**Comment by Alex-302** [comment]
Тогда ждём новую опцию.
