### ISSUE TITLE
[ads popups, nsfw ] pictoa.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#15512]
At **[NSFW]** https://www.pictoa.com  after click on picture you will redirect to blank page (randomly closing).
Solution:
```
pictoa.com##.ads.title-wrapper
pictoa.com###tab-footer
pictoa.com/js/ads.js
pictoa.com/31.php

```
CC @AdamWr

**Comment by BlazDT** [comment]
Php name seems to be random. Ads.js is already whitelisted due to adblock detection.

Not reproduced:
.ads.title-wrapper

Added rules for ads/popunder. We probably have to change .js block rule as it contains a number and may be random like the php file.
