### ISSUE TITLE
kimpetras.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#155125]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.1b9

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.kimpetras.com/home/

### What filters do you have enabled?

AdGuard Widgets filter

### Add your comment and screenshots

1. <comment>
Newsletter sign up. Some filters to use:
`||www.kimpetras.com/files/2022/11/sign-up-title.png`
`kimpetras.com###sign-up`

2. Screenshots
<details><summary>Screenshot 1:</summary>
![241304633-b0b7b805-a1b1-4fb6-808c-9cf96e4b8c31](https://github.com/AdguardTeam/AdguardFilters/assets/89158249/40297653-280e-45c1-a7f4-47428ec3d43f)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Unfortunately, the reported issue does not satisfy our [filters policy](https://kb.adguard.com/en/general/adguard-filter-policy). The website has low visitors. Please leave the suggested rules in the user rules.
