### ISSUE TITLE
joinonelove.org

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#155368]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.1b11

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.joinonelove.org/

### What filters do you have enabled?

AdGuard Widgets filter

### Add your comment and screenshots

1. <comment>
Newsletter widget:
`joinonelove.org##.footer-form`
2. Screenshots
<details><summary>Screenshot 1:</summary>

![249027873-fdbcd8c5-ce69-4fd7-9a9d-a71da994fb1a](https://github.com/AdguardTeam/AdguardFilters/assets/89158249/ffe557cd-274b-4391-a772-3b239aca5657)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
We only remove subscriptions in the footer if it is a different color strip.
