### ISSUE TITLE
cutyt.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#155367]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.1b11

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.cutyt.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>
Ad content delivery network.
`||adsterratech.com^`

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
Hello @Sonic5435325

I can't reproduce any requests to this domain.
Could you provide a screenshot of the filtering log showing these requests?

**Comment by Sonic5435325** [comment]
![Screenshot from 2023-07-04 12-20-58](https://github.com/AdguardTeam/AdguardFilters/assets/89158249/e8ac936b-3379-4a79-afc5-2ccd95f9513f)
Try refreshing while ignoring cache. (CTRL+Shift+R)

**Comment by Sergey-Lyapin** [comment]
Now I see, thank you.
