### ISSUE TITLE
romsmania.games

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#155473]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.1b11

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://romsmania.games/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

1. <comment>
There's a gap at the bottom of the screen, caused by an ad placeholder.
Possible fix: `romsmania.games##body:style(padding-bottom: unset !important;)`
2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot from 2023-07-04 13-50-26](https://github.com/AdguardTeam/AdguardFilters/assets/89158249/c7928f66-b5c7-4255-aaee-9047884db0ff)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
Unfortunately, we cannot reproduce the issue with your settings.

Please try checking the filters updates, maybe it was already solved. If you’re still able to reproduce the issue, reopen it here. We’d appreciate if you supply additional information or screenshots.
