### ISSUE TITLE
[Android] Spotify Connect issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1555]
> Spotify has a feature called Spotify Connect which allows you to play music
> over WiFi to speakers that support Spotify Connect, for example Samsung
> Roomspeakers. When Adguard is enabled, Spotify is not able to detect those
> speakers, even when I disable ad filtering for Spotify in the firewall.
> That's why I had to go in advanced settings and manually enter
> com.spotify.music.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
передай, чтоб без вильтров проверил. Не заработает - значит баг(вроде что-то похожее было/есть с подключением к телевизорам).

**Comment by evgeniy-ADG** [comment]
done

**Comment by evgeniy-ADG** [comment]
> Hi,
> 
> It works when I disable all filters.
> 
> Thanks for looking into this,

**Comment by Alex-302** [comment]
@evgeniy-ADG Значит не баг.Приведи список его фильтров. И попроси его включать по одному с проверкой.
