### ISSUE TITLE
ototeknikveri.com

### ISSUE THREAD

**Issue by xqtp** [AdguardTeam/AdguardFilters#155514]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.56

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.ototeknikveri.com/haber/27405/kocaeli-fabrikalarinda-uretilecek-e-tourneo-custom-tanitildi

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

medyanative.com is an ad server. EasyList already blocks it, but it should still be in the Turkish filter.

<details><summary>Screenshot</summary>

![resim](https://github.com/AdguardTeam/AdguardFilters/assets/103899764/c8f71183-773d-4d21-883c-a19fd0c4f0f3)

</details>

These websites also have the same ad server.
https://www.81oraytv.com/
https://www.yeniadana.net

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
