### ISSUE TITLE
[iOS] www.vesti.ru - videos don't play

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1556]
Со включенным блокировщиком не работает видео, пишет что нет Жавы и Флеша

http://www.vesti.ru/videos/show/vid/670685/#
http://prntscr.com/a3fiw4

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.77.21 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.82 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.55 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.88 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.30.98 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.2.39 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.44 Enabled=YES
ID1 Name="EasyList" Version=1.0.52.50 Enabled=NO
ID5 Name="RU AdList" Version=1.0.52.54 Enabled=NO

**Comment by Alex-302** [comment]
@evgeniy-ADG 
А на айпаде(или что у него) установка Флэша поддерживается? Без Адгарда проверяли?
В Хроме выключил флэш - тоже не работает, HTML5 у них нет.
