### ISSUE TITLE
pinterest.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#155656]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.1b13

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.pinterest.com

### What filters do you have enabled?

AdGuard Tracking Protection filter

### Add your comment and screenshots

1. <comment>
Tracker on site.
`||pinterest.com/resource/UserRegisterTrackActionResource/`
2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Not sure if this is a tracker, looks like logging information

**Comment by Sonic5435325** [comment]
`/statslogresource/*` and `/contextlogresource/*` were added to EasyPrivacy, so I don't see a problem in adding this one here.

**Comment by jellizaveta** [comment]
@zloyden hello. could you please advice?
