### ISSUE TITLE
http://old.reactor.cc and http://reactor.cc - antiadblock banner

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1557]
http://old.reactor.cc
http://prntscr.com/a3g52p

Can you block it?
HTL-895-39021

**Comment by Alex-302** [comment]
Они наблюдают за блокировщиками и оперативно переделывают. Пока закрываю.

**Comment by vgavrish** [comment]
old.reactor.cc
фильтры: 1,2,3,4,14
![screenshot_30](https://cloud.githubusercontent.com/assets/18548949/18242652/08d2e22c-7360-11e6-94d1-4889baf529ee.jpg)

**Comment by Alex-302** [comment]
В фильтре раздражителей исправил. Пока работает только с Адгардом для Винды и расширением для Хрома.

**Comment by Bohdan-SUP** [comment]
@Alex-302 Все еще повторяется с расширением для Хрома 2,4,10
![screen shot 2016-09-09 at 6 04 15 pm](https://cloud.githubusercontent.com/assets/14153331/18391791/da744a50-76b7-11e6-9994-b4607eefb3a8.png)

**Comment by Alex-302** [comment]
Он сильно дорожит этим сообщением. Иногда его код делает таким, чтоб текущее правило скрывало контент.

**Comment by Alex-302** [comment]
Попробовал. Посмортим на сколько хватит.
