### ISSUE TITLE
AdGuard blocks connections of the Microsoft Solitaire Collection game

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#15588]
### Issue URL (Incorrect Blocking)
[https://www.microsoft.com/en-us/store/p/microsoft-solitaire-collection/9wzdncrfhwd2](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fstore%2Fp%2Fmicrosoft-solitaire-collection%2F9wzdncrfhwd2)
### Comment
> Помогает отключение HTTPS фильтрации в AdGuard.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/CkbBylh.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 6.2.437.2171
Browser: | Microsoft Store game
AdGuard driver: | TDI
Filters: | Russian,<br>English,<br>Spyware,<br>Social media

**Comment by Eugene-Savenko** [comment]
Another false blocking report regarding the game:

> Hi just got the Windows 10 April Update and I wanted to let you guys know that unless I disable ad blocking for Microsoft Solitaire it won't connect to the Xbox live services.

**Comment by AdamWr** [comment]
I couldn't reproduce it.
I can log in into my account and game works fine on my end.
<details><summary>Screenshots</summary>

![msc](https://user-images.githubusercontent.com/29142494/39628493-90388830-4fa9-11e8-8c1c-a62b4a008810.png)

![image](https://user-images.githubusercontent.com/29142494/39628487-8afce82a-4fa9-11e8-9921-e53f902f112c.png)

</details>

**Comment by Alex-302** [comment]
The same.

**Comment by vozersky** [comment]
can't reproduce

**Comment by Eugene-Savenko** [comment]
Reports keep coming, here's another one - 1860101:

> Не работает Microsoft Solitaire Collection. Помогает только снятие галки «Фильтровать https протокол», но тогда https страницы открываются с рекламой. Есть ли какое-нибудь решение без отключения https?

**Comment by Alex-302** [comment]
@Eugene-Savenko может ему антивирус мешает? Пусть там попробует выключить фильтрацию https.
