### ISSUE TITLE
oload.win

### ISSUE THREAD

**Issue by Mav3r1x** [AdguardTeam/AdguardFilters#15586]
Not every oload.win/ link asks to disable the adblocker, but if you go to the following link, it says this:

> The publisher of this file doesnt allow adblock, please disable and reload!

Link: [OpenLoad Link](https://oload.win/f/iGHvmY_fFYE/PRIMALRAGEWEBD72.Ganool.ac.rar)

Help please.

**Comment by BlazDT** [comment]
Fixed in French filter. Please provide required information outlined in template next time or else your request may be get not solved.

**Comment by Mav3r1x** [comment]
@BlazDT  Thanks for updating the filter. Will make sure to follow the template next time.

Could you please tell me why was the fix added in French filter? Shouldn't this be in English filter??

**Comment by BlazDT** [comment]
French filter broke it for me, therefore fix for French filter.
