### ISSUE TITLE
www.wsj.com

### ISSUE THREAD

**Issue by jackwangshanghai** [AdguardTeam/AdguardFilters#155933]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

On www.wsj.com there are some ads block that is not blocked. The ads are blocked but the container that displays ads is not blocked. Make the article not clean.

### Proposed solution

wsj.com##.uds-ad-container

**Comment by AdamWr** [comment]
Unfortunately, I don't see it on my end.
Please make a screenshot and provide a link to article which contains such element.
