### ISSUE TITLE
wetter.com

### ISSUE THREAD

**Issue by mirtisdyleris** [AdguardTeam/AdguardFilters#156057]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Version: 2.0.20.23

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

wetter.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Cookie Notices filter, AdGuard Other Annoyances filter, Fanboy's Anti-Facebook List

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Self-destruction of third-party cookies

### Add your comment and screenshots

1. Cookie banner doesnt get removed

2. Screenshots
<details><summary>Screenshot 1:</summary>
![image](https://github.com/AdguardTeam/AdguardFilters/assets/33166892/99737267-9f0c-4b1a-8c2c-624b6c9f18f9)

![image](https://github.com/AdguardTeam/AdguardFilters/assets/33166892/fe0e78d3-62b5-4682-a76a-a263faddb39a)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Not even showing without Adblocker.
If it is uBlock Origin, it is not blocked as they do not support auto-click rules.

@zloyden can you reproduce?

**Comment by Morku** [comment]
I can reproduce the Cookie Pop-up on iPhone.

There are also several placeholder (and overblocking?) on mobile view:

<details><summary>Screenshot-1:</summary>

![wetter1](https://github.com/AdguardTeam/AdguardFilters/assets/6276915/cb21e506-fd71-4e89-b34c-cff849fd1681)


</details><br/>

<details><summary>Screenshot-2:</summary>

![wetter2](https://github.com/AdguardTeam/AdguardFilters/assets/6276915/65648557-8895-4f47-b0a1-2f8a14768498)


</details><br/>

<details><summary>Screenshot-3:</summary>

![wetter3](https://github.com/AdguardTeam/AdguardFilters/assets/6276915/262f107d-9a27-4553-96a7-8ddee20ffa09)


</details><br/>

**Comment by Morku** [comment]
@BlazDT 

I see your filters in my updated list, but none of the placeholders were fixed 🤔

Interestingly, on iPhone (where I have to click the Cookie Pop-up), there is showing the Berlin weather widget. Might have to do with the Cookie Pop-up?

<details><summary>Screenshot-1:</summary>

![IMG_710674282690](https://github.com/AdguardTeam/AdguardFilters/assets/6276915/0e120245-2038-4df7-9dbc-1a4a5f7e5889)


</details><br/>

The mobile Cookie Pop-up seems to be filtered in AdGuard German filters (instead of Annoyance). When I uncheck it, the Berlin widget loads on mobile view.
However, that filter has no affect on iPhone and since it overblocks another solution might be better.

**Comment by BlazDT** [comment]
On mobile view Chrome on Windows they are hidden. Not seeing a rule in German filter regarding cookie.

**Comment by Morku** [comment]
@BlazDT 

When I use AdGuard Extension, the Cookie Pop-up on mobile loads (and is not autopassed) on mobile view.

When I use AdGuard for Windows, the mobile Cookie Pop-up (with the loading issues) is blocked by `$$script[tag-content="Flags."][min-length="20000"][max-length="300000"]`

**Comment by zloyden** [comment]
@Morku try these rules
first leftover
```adblock
wetter.com#?#div[class^="sc-"]:has(> div.ad-container)
```

cookies
```adblock
wetter.com#%#//scriptlet('trusted-click-element', 'div[class^="sc-"] > button.primary')
```

**Comment by Morku** [comment]
I have added both rules.

- AdGuard for Windows mobile view (Firefox):
No autoclick, all placeholders are still there, as long `$$script[tag-content="Flags."][min-length="20000"][max-length="300000"]` is being used
When I exclude filter with `$@$script[tag-content="Flags."][min-length="20000"][max-length="300000"]` -> autoclick on mobile view works fine and all placeholders are not hidden

- AdGuard for iOS:
Works all fine now. Autoclick works and placeholders are hidden 👍

**Comment by zloyden** [comment]
Ok, thanks for checking this out! I added the rules, the update should be available in 2-3 hours.
