### ISSUE TITLE
www.antena3.ro cookie pop-up

### ISSUE THREAD

**Issue by andreewmat** [AdguardTeam/AdguardFilters#156005]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Ublock Origin with AdGuard Annoyance Filter

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.antena3.ro/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1. Cookie pop-up appear on the website.

### Privacy

- [X] I agree to follow this condition

**Comment by andreewmat** [comment]
Also, cookie pop-up on this site too: 
`editorial.rottentomatoes.com`

**Comment by jellizaveta** [comment]
On `editorial.rottentomatoes.com`, I сannot reproduce the cookie message with AG extension and uBlock.

**Comment by andreewmat** [comment]
> On `editorial.rottentomatoes.com`, I сannot reproduce the cookie message with AG extension and uBlock.

Hello, this is the pop-up I encounter:
![image](https://github.com/AdguardTeam/AdguardFilters/assets/79897301/310aa74b-a715-4f24-b7a0-46e626f0fdbc)

I am using only the uBlock Origin with AdGuard Annoyance Filters(all selected):
![image](https://github.com/AdguardTeam/AdguardFilters/assets/79897301/71d8d0ca-61d1-4602-b5f2-f9c92c0f7118)


> If I understand correctly, the cookies in AG filters are blocked by a scriptlet that is not supported in ublock. With the AdGuard extension I can't reproduce the cookie message.

So I understand correctly, that pop-up cannot be blocked with uBlock Origin?

**Comment by jellizaveta** [comment]
@andreewmat Checked with uBlock and AGFilter lists, the cookie message does not appear on `editorial.rottentomatoes.com`.

**Comment by andreewmat** [comment]
@jellizaveta Should I filter the logs to see only the allowed elements? Or modified ones?

**Comment by jellizaveta** [comment]
Please, try adding this rule to the user rules on the site: `editorial.rottentomatoes.com###onetrust-consent-sdk` and check if cookies blocked on `editorial.rottentomatoes.com`. (make sure to enable the user rules in the settings)

> only the allowed elements

Clearing the log --> retry cookies --> take screenshots of all requests

**Comment by andreewmat** [comment]
> `editorial.rottentomatoes.com###onetrust-consent-sdk` 

It's working with this filter, the cookie pop-up is removed and everything is fine.

Logs with the rule activated:
![image](https://github.com/AdguardTeam/AdguardFilters/assets/79897301/aafa1efe-2aa3-4864-be74-20612fb02b14)
![image](https://github.com/AdguardTeam/AdguardFilters/assets/79897301/9b6dc195-52e2-43f4-a679-9bd2942d91ab)

Also on `antena3.ro` I have the same issue with that cookie pop-up:
![image](https://github.com/AdguardTeam/AdguardFilters/assets/79897301/c44fd5da-7830-4fc6-bedf-84256ae7fec1)

There are the logs, maybe can help you:
![image](https://github.com/AdguardTeam/AdguardFilters/assets/79897301/ce4ed757-5465-4083-b4a4-82d6d05997bd)
![image](https://github.com/AdguardTeam/AdguardFilters/assets/79897301/2b881ab5-676e-4ad5-aac2-d903c5284bc1)

**Comment by andreewmat** [comment]
@jellizaveta Hello, if this filter is good `editorial.rottentomatoes.com###onetrust-consent-sdk` , can be added to AdGuard Filters? 

Also, for the other website `antena3.ro` I have added above some pictures with logs, maybe it can help you identify the cookie pop-up. Thanks for all help!
