### ISSUE TITLE
www.dropout.tv

### ISSUE THREAD

**Issue by MisterSheeple** [AdguardTeam/AdguardFilters#156221]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

AdGuard Tracking Protection filter 2.0.58.5

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.dropout.tv/make-some-noise/season:2/videos/100000-batmans

### What filters do you have enabled?

AdGuard Tracking Protection filter

### Add your comment and screenshots

When `collector.vhx.tv` is blocked, the service is unable to check user rights for content and fails to play with error: "Sorry, you are not authorized to watch this video." This breaks all streaming platforms that rely on Vimeo OTT/VHX to deliver content. Relevant issue: #89165, where the item was first added to the list.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@MisterSheeple hello! If you disable the Tracking Protection filter filter and open the site in incognito mode, does the issue persist?

**Comment by MisterSheeple** [comment]
Hi, I'm unable to boot my PC right now so I'll keep you posted when that
changes and I'm able to test that, but right now I'm testing on mobile and
even with the filter on, it appears to work despite `collector.vhx.tv`
still being blocked, so this might be a case of it only breaking on desktop.

**Comment by jellizaveta** [comment]
@MisterSheeple Hello! Any news?

**Comment by MisterSheeple** [comment]
Oddly, after testing it without having the filter enabled, it still blocks the domain, despite none of my other filter lists (even non-Adguard lists) blocking that domain. None of my other extensions are causing it to be blocked either.
