### ISSUE TITLE
Incorrect Block

### ISSUE THREAD

**Issue by ksholdings** [AdguardTeam/AdguardFilters#156317]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0.912

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

Cannot access the following URL in the app's internal browser. https://www.ksdenki.com/sp/app/anpass/customer/topmenu.aspx

### What filters do you have enabled?

AdGuard Mobile Ads filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard DNS filter

### Add your comment and screenshots

1. <comment>
   1) Install "K's Denki Anshin Passport App" from the Play Store.
   2) Open "K's Denki Anshin Passport App" and tap "Click here to register".
   3) An error message "Communication could not be established" appears.
   4) The page that should be displayed is supposed to be blocked.
   5) When AdGuard is disabled or the DNS filter function of AdGuard is disabled, the "K's Denki Anshin Passport App" behaves correctly
We wish to exclude pages under the following directories from communication blocking.
https://www.ksdenki.com/sp/app/anpass/

2. Screenshots
<details><summary>Screenshot 1:</summary>

![1)-Install--K's-Denki-Anshin-Passport-App](https://github.com/AdguardTeam/AdguardFilters/assets/139418235/ea905b43-702c-4416-b710-9be882d7ef8d)
![2)-tap-Click-here-to-register](https://github.com/AdguardTeam/AdguardFilters/assets/139418235/a18de26b-f2cf-4614-a884-2f9e06293a4a)
![3) Communication-could-not-be-established](https://github.com/AdguardTeam/AdguardFilters/assets/139418235/9e04aa7b-cfa6-46d5-9181-d1ebf32f8117)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Where it can be downloaded?
Could you please create an account for us and send it to filters@adguard.com?

> 5) When AdGuard is disabled or the DNS filter function of AdGuard is disabled, the "K's Denki Anshin Passport App" behaves correctly

so the app is broken by DNS filtering module?
If so - please disable all filters, except DNS filter, switch to non-filtered DNS and clear the filtering log. Then reproduce an issue and go to the filtering log. Filter out blocked requests and make screenshots.
