### ISSUE TITLE
lihkg.com was flagged as adult site suddenly

### ISSUE THREAD

**Issue by hw121693** [AdguardTeam/AdguardFilters#156538]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

ADGuard DNS

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://lihkg.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter

### Add your comment and screenshots

1. It's a forum 
![image](https://github.com/AdguardTeam/AdguardFilters/assets/15042485/f2f66504-8f80-4df3-ba36-cf4bca45e770)

3. Screenshots
![image](https://github.com/AdguardTeam/AdguardFilters/assets/15042485/016e38ec-2860-4456-96e4-f46cf80f7618)

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Will be checked.
