### ISSUE TITLE
GlobalTools.* - Missing objects (AdGuard Tracking Protection filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#156564]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?
```
https://www.globaltools.dk/
https://www.globaltools.no/
https://www.globaltools.se/
```

* Example:
`https://www.globaltools.no/verktoy/ror-og-vvs-vaerktoj-8817/inspektions-og-lokalisering-8857/`

### What filters do you have enabled?

* **AdGuard Tracking Protection filter**

### Affected sites:
```
https://www.globaltools.dk/
https://www.globaltools.no/
https://www.globaltools.se/
```

### Issue:
Missing objects.

### Example:
`https://www.globaltools.no/verktoy/ror-og-vvs-vaerktoj-8817/inspektions-og-lokalisering-8857/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **AdGuard Tracking Protection filter**

### Problem rule:
`||cdn.clerk.io/clerk.js
`
### Possible fix:
`@@||cdn.clerk.io/clerk.js$domain=globaltools.dk|globaltools.no|globaltools.se`

--

### System info:
* OS/version: Windows 10 Pro 22H2 (x64)
* Browser/version: LibreWolf v115.0.2-2 (x64) [Tracking Protection = Standard]
* Adblock Extension/version: uBlock Origin v1.50.0

### Privacy

- [X] I agree to follow this condition

**Comment by THEtomaso** [comment]
@Yuki2718:
Could you handle this?

**Comment by THEtomaso** [comment]
@AdamWr:
These sites also seems to require `@@||googletagmanager.com/gtm.js` now.
Can you confirm from your end?
Example:
https://www.globaltools.dk/sogning?start=true&search=hammer

**Comment by AdamWr** [comment]
Yes, I have added a rule to unblock it and removed previous rule because it looks like that `cdn.clerk.io/clerk.js` is not used anymore.
