### ISSUE TITLE
Missed ads on chrome://newtab - Yandex search

### ISSUE THREAD

**Issue by HitmanCN47** [AdguardTeam/AdguardFilters#156522]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [x] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard for Windows

### AdGuard version

7.13.2 (build 4287, CL 1.11.114)

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

chrome://newtab

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Widgets filter, I don't care about cookies

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Block WebRTC, Block Push API, Block Location API, Hide Referrer from third-parties (specify in comment below, if used custom value)

### Add your comment and screenshots

1. <comment>There is no option to block the ads on chrome://newtab using Adguard browser helper because it's inactive
2. Screenshots
<details><summary>Screenshot 1:</summary>

![newtab_1](https://github.com/AdguardTeam/AdguardFilters/assets/139629821/61c9dba3-d309-40ec-955f-4449783af0f3)

</details>

<details><summary>Screenshot 2:</summary>

![newtab_2](https://github.com/AdguardTeam/AdguardFilters/assets/139629821/8965a7a3-f5bb-4364-86e3-472413122392)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
I didn't even know it was possible to make chrome://newtab Yandex-focused.

**Comment by HitmanCN47** [comment]
I actually don't know how it is possible. Maybe it's because I have Yandex as default search engine in my Chrome settings.

**Comment by Tctcuvtchcu** [comment]
> I actually don't know how it is possible. Maybe it's because I have Yandex as default search engine in my Chrome settings.

Russian warship go fuck away!
Glory to Ukraine 🇺🇦

Greeting from Poland 🇵🇱

**Comment by krystian3w** [comment]
You will probably need a network rule added in AdGuard for Windows or macOS (not in WebExtension even on MV3).

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.

**Comment by HitmanCN47** [comment]
Hello!
My sincere gratitude to the Adguard support team. Now I see the issue is
fixed - that's great!

Best regards

пт, 21 июл. 2023 г. в 11:47, zloyden ***@***.***>:
