### ISSUE TITLE
ar.groupslinks.com and groupslinks.com | Block this NSFW group bot sites with one domain

### ISSUE THREAD

**Issue by NostalgicNeverGonnaGiveYouUp** [AdguardTeam/AdguardFilters#156630]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

last

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

ar.groupslinks.com groupslinks.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter

### Add your comment and screenshots

1. Block this site groupslinks.com and ar.groupslinks.com [ protocol domain transfer to this domain ar.groupslinks.com ] because this is pornographic sites
2. Screenshots: 18+

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
We do not block porn.
