### ISSUE TITLE
intercitypark.com

### ISSUE THREAD

**Issue by pubct** [AdguardTeam/AdguardFilters#156779]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.0

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://intercitypark.com/

### What filters do you have enabled?

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, EasyList, EasyPrivacy, Peter Lowe's Blocklist, Online Malicious URL Blocklist

### Add your comment and screenshots

Cookie notice at the bottom.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Unfortunately, the reported issue does not satisfy our [filters policy](https://kb.adguard.com/en/general/adguard-filter-policy). The website has low visitors. Please add this rule to the User Rules: `intercitypark.com##.cookie-agreement-container`
