### ISSUE TITLE
mediafire.com [Fake Button]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#15682]
**Site**: http://www.mediafire.com/error.php?errno=320&origin=download

**Issue**: Please remove the fake download button on the page.

**Screenshot**: http://prntscr.com/je07xs

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.139 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Not showing and according to code it is not set visible if this one is the correct url:

`http://desktop.mftracking.com`

@AdamWr please check.

**Comment by AdamWr** [comment]
Fixed.
