### ISSUE TITLE
ndtv.com [Incorrect Blocking]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#15690]
**Site**: https://www.ndtv.com/karnataka-news/karnataka-assembly-election-2018-live-updates-amid-a-war-of-words-high-voltage-campaign-continues-1847536

**Issue**: When scrolling down on the page, the bar shown in the screenshot always come down and because of that a lot of space is occupied. Is this the result of some improper blocking? I checked this same page without AG and the top bar does not expand. Can you please check and fix it.

Moreover, after scrolling completely down, the text is not visible as seen here: http://prntscr.com/je0uib

**Screenshot**: http://prntscr.com/je0tsv

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.139 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Removed problematic rule regarding 1st issue. Other issue sadly not reproduced. Please check @AdamWr

**Comment by AdamWr** [comment]
> Moreover, after scrolling completely down, the text is not visible as seen here: http://prntscr.com/je0uib

It happens even without AdGuard on my end.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/39700792-d0bddbc4-51fe-11e8-8260-62606fdc17ad.png)

</details>

**Comment by Nzzyme** [comment]
So, this is fixed then
