### ISSUE TITLE
reddit.com

### ISSUE THREAD

**Issue by eiqnepm** [AdguardTeam/AdguardFilters#156989]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.57

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

reddit.com

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

Annoyance to register email. If you have no email registered to your account you will see this banner on every page, you can dismiss it but it will show up again on your next session.

It can be blocked using `reddit.com##div > div.kEQVd8aneM1tVkcIKUyDT`.

I see there was an issue about this that has been closed https://github.com/AdguardTeam/AdguardFilters/issues/119302#issue-1242261606.

I have tested a completely fresh account in Tails and I can confirm the class is not unique to each account https://streamable.com/z6iums.

![](https://camo.githubusercontent.com/ea1f09c14f16d1d1745ed739166e027c37c99d1c0f85145f753fbdc8f0048b66/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f4e55474b6e77312e706e67)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Still cannot reproduce with fresh account without confirmed email.
