### ISSUE TITLE
kick.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#157004]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.50.1rc3

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://kick.com

### What filters do you have enabled?

AdGuard Tracking Protection filter

### Add your comment and screenshots

1. <comment>
Some FingerprintJS code loads on the site, currently at this URL (Not unlikely to change eventually):
`kick.com/GnBme2AEMeEWet78/mRpHqITlCMkZevXY?apiKey=YYrqGEa5NkC1NrvsiKAT&version=3&loaderVersion=3.8.3`

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
If can't be blocked at all then can be addressed only in:

https://github.com/AdguardTeam/AdguardFilters/tree/master/TrackParamFilter/sections (AdGuard URL Tracking filter).

With similar method to stephenhawk8054:
```adb
! https://github.com/AdguardTeam/AdguardFilters/issues/157004
/^https:\/\/kick\.com\/[0-9A-z]{16}\/[0-9A-z]{16}\?apiKey=/$script,1p,match-case,domain=kick.com
```

So browser still load "JS" from:

`kick.com/GnBme2AEMeEWet78/mRpHqITlCMkZevXY?version=3&loaderVersion=3.8.3`

**Comment by Sonic5435325** [comment]
Probably would be a good idea to use the same filter as uBlock filters. It's far too likely for a URL path as random as that to change soon.
