### ISSUE TITLE
lih.kg was flagged as adult site

### ISSUE THREAD

**Issue by hw121693** [AdguardTeam/AdguardFilters#157170]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

AdGuard DNS

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://lih.kg

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. https://lih.kg is a forum not an adult site

2. Screenshots
![image](https://github.com/AdguardTeam/AdguardFilters/assets/15042485/8b8616d4-9623-40fe-a881-c131cfb94a18)

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
The site may contain adult content, so is blocked by the parental control module

**Comment by hw121693** [comment]
May I advise which part of this site you think contains adult content?
It's a forum in Hong Kong mainly discuss about news topics or something like reddit

**Comment by jellizaveta** [comment]
@VladisLoveZh hello. Should we change the category of this site?
