### ISSUE TITLE
Youtube.com Video Player Blockage

### ISSUE THREAD

**Issue by chromer030** [AdguardTeam/AdguardFilters#157291]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.56

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

youtube.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, EasyList

### Add your comment and screenshots

1. After 3 warnings Youtube blocked the player and it's impossible to play any video

![Screenshot_20230724_220236](https://github.com/AdguardTeam/AdguardFilters/assets/13361552/f1a423ea-8e7d-4639-9484-123f6327492a)

Log : [Log.txt](https://github.com/AdguardTeam/AdguardFilters/files/12148915/Log.txt)

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Do you get that warning on non-subscribed channels or when you are not logged in too?

**Comment by chromer030** [comment]
non-subscribed channels or subscribed channels doesn't matter, and when i'm logged in.

**Comment by chromer030** [comment]
I'm wondering if it's server-side or client-side 🤔

**Comment by chromer030** [comment]
Adguad filtering log :

![Screenshot_20230724_222949](https://github.com/AdguardTeam/AdguardFilters/assets/13361552/f49ec629-969f-4ebf-8760-0869370c19b3)


![Screenshot_20230724_223010](https://github.com/AdguardTeam/AdguardFilters/assets/13361552/6d4e7e75-9740-4d1d-a140-ef2106b7f274)

**Comment by BlazDT** [comment]
Nothing interesting in screenshots. Are you watching youtube from time to time or more often (i try to get selected for that adblock warning message and so far I very rarely watch youtube, so likely not interesting for them so far).
So I guess they likely check if their variables are renamed. Please try to press on one line from Base filter -> unblock. If not working, next one.

**Comment by chromer030** [comment]
Watching from time to time.
To get that adblock warning change your IP to canada, i get warnings only on my canada ip .

**Comment by chromer030** [comment]
If user press `Allow Youtube Ads` :

![Screenshot_20230724_224707](https://github.com/AdguardTeam/AdguardFilters/assets/13361552/e85a826c-5435-4943-8e9a-383443ca0e1c)

**Comment by chromer030** [comment]
> Please try to press on one line from Base filter -> unblock. If not working, next one.

I tried unblocking almost the all lines , still the same warning , blocked video player.

**Comment by BlazDT** [comment]
Could you please try these two rules:
```
youtube.com#@%#//scriptlet('json-prune', 'playerResponse.adPlacements playerResponse.playerAds adPlacements playerAds', 'playerConfig.webPlayerConfig')
youtube.com#%#//scriptlet('json-prune', 'playerResponse.adPlacements playerResponse.playerAds adPlacements playerAds', 'playerConfig.streamSelectionConfig')
```

**Comment by chromer030** [comment]
> youtube.com#@%#//scriptlet('json-prune', 'playerResponse.adPlacements playerResponse.playerAds adPlacements playerAds', 'playerConfig.webPlayerConfig')
> youtube.com#%#//scriptlet('json-prune', 'playerResponse.adPlacements playerResponse.playerAds adPlacements playerAds', 'playerConfig.streamSelectionConfig')

Still the same : 
![Screenshot_20230725_073500](https://github.com/AdguardTeam/AdguardFilters/assets/13361552/d9c0b5d4-6d1e-4080-a1c8-9c2bafbb7031)

**Comment by chromer030** [comment]
Fixed, no longer warning : https://github.com/AdguardTeam/AdguardFilters/issues/156546#issuecomment-1649069518 

@BlazDT appreciating your efforts.
