### ISSUE TITLE
northerntool.com

### ISSUE THREAD

**Issue by bottleblue** [AdguardTeam/AdguardFilters#157248]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

none

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.northerntool.com/products/red-mountain-valley-patio-mat-6ft-x-9ft-palm-leaf-pattern-model-2a-pm013-104586

### What filters do you have enabled?

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdGuard Mobile App Banners filter

### Add your comment and screenshots

I have the AdGuard Tracking Protection filter list enabled in ublock origin. This causes the northerntool.com site to not load at all. I reported it in the ublock github and they said it was caused specifically by 
`||qoe-*.yottaa.net/*/configure.rapid.js`

Disabling the AdGuard Tracking Protection filter makes the site load properly
### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.

**Comment by bottleblue** [comment]
thx for the super quick fix

**Comment by THEtomaso** [comment]
@AdamWr:
The site is completely broken again (using **AdGuard Tracking Protection** filter in **uBO**)

**Comment by AdamWr** [comment]
Website loads fine on my end but I see that some elements like `Reviews` and `Questions & Answers` are empty.
I have modified rules to fix it.
