### ISSUE TITLE
upload4earn.org [Fake Button]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#15720]
**Site**: https://upload4earn.org/3zec3bm3xp62

**Issue**: Please remove the fake Download button on the page. Pop-up also observed on the page.

**Screenshot**: http://prntscr.com/jea0xs

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.139 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Popup not reproduced, please check @AdamWr

**Comment by Nzzyme** [comment]
Pop-up not seen anymore. Thank you!

**Comment by Nzzyme** [comment]
Has the fake link been hidden? I am still able to see on Android. Can you please check?

**Comment by BlazDT** [comment]
I'm not seeing it anymore on the link in the screenshot.
https://upload4earn.org/9903n7wy11td

**Comment by Nzzyme** [comment]
Visiting this link on Android shows background connections to other domains

https://upload4earn.org/54uuby574s1f

Filtering Log shows connections to 

trothko.com
housineschard.info

I guess the above 2 domains should be blocked?

**Comment by Alex-302** [comment]
ok

**Comment by Nzzyme** [comment]
Again seeing fake link on this page on Android.

https://upload4earn.org/5rgx01gef2nu

Cleared browser history, cache, etc. And disabled user filters. Please check.

**Comment by Alex-302** [comment]
Not reproduced.
