### ISSUE TITLE
 Some Google's domains used for ads/tracking to be blocked (Missed ads/tracking)

### ISSUE THREAD

**Issue by hollownights** [AdguardTeam/AdguardFilters#157310]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

AdGuard Public Plain DNS (Default servers)

### What type of problem have you encountered?

Missed ads or ad leftovers, Missed analytics or tracker

### Which browser(s) do you use?

Firefox, Chrome, other (specify in comment below), the problem is with app, not a site

### Which device do you use?

Desktop

### Where is the problem encountered?

Many websites and apps

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

Here are some Google's domains used for serving ads or for tracking that aren't currently blocked by AdGuard Public DNS: Some of them seem to only be contacted by mobile apps.

```
analytics-api-samples.googlecode.com
video-stats.video.google.com
www.googleadservices.com
domains.googlesyndication.com
www.googletagservices.com
ads.google.com
afs.googlesyndication.com
mobileads.google.com
video-ad-stats.googlesyndication.com
adservice.google.com
googletagmanager.com
www.googletagmanager.com
mobileads.google.com
mail-ads.google.com
pagead.l.doubleclick.net
```

### Privacy

- [X] I agree to follow this condition

**Comment by hollownights** [comment]
Out of those 15 domains, only `googletagmanager.com` can be seen in AdGuard's "[exclusions](https://raw.githubusercontent.com/AdguardTeam/AdGuardSDNSFilter/master/Filters/exclusions.txt)" list, and only 
`www.googleadservices.com` and `pagead.l.doubleclick.net` can be seen in the "[exceptions](https://raw.githubusercontent.com/AdguardTeam/AdGuardSDNSFilter/master/Filters/exceptions.txt)" list. All the others should be good to go.

**Comment by hollownights** [comment]
Info on those domains. Courtesy of VirusTotal:

```
https://www.virustotal.com/gui/domain/analytics-api-samples.googlecode.com/relations
https://www.virustotal.com/gui/domain/video-stats.video.google.com/relations
https://www.virustotal.com/gui/domain/www.googleadservices.com/relations
https://www.virustotal.com/gui/domain/domains.googlesyndication.com/relations
https://www.virustotal.com/gui/domain/www.googletagservices.com/relations
https://www.virustotal.com/gui/domain/ads.google.com/relations
https://www.virustotal.com/gui/domain/afs.googlesyndication.com/relations
https://www.virustotal.com/gui/domain/mobileads.google.com/relations
https://www.virustotal.com/gui/domain/video-ad-stats.googlesyndication.com/relations
https://www.virustotal.com/gui/domain/adservice.google.com/relations
https://www.virustotal.com/gui/domain/googletagmanager.com/relations
https://www.virustotal.com/gui/domain/www.googletagmanager.com/relations
https://www.virustotal.com/gui/domain/mail-ads.google.com/relations
https://www.virustotal.com/gui/domain/pagead.l.doubleclick.net/relations
```

**Comment by Alex-302** [comment]
This is not what I want. I need the sites where these domains used. Not only mentioned.

**Comment by hollownights** [comment]
www.googleadservices.com / googletagmanager.com / www.googletagmanager.com

```
https://www.ionos.com/
https://www.washingtonpost.com/
```


googletagmanager.com / www.googletagmanager.com

```
https://www.avast.com
https://www.anker.com/
https://www.nytimes.com/
https://www.ikea.com/
```


adservice.google.com

```
https://www.howtogeek.com/
https://www.bestbuy.com
```


www.googletagservices.com

```
https://www.howtogeek.com/
https://www.ikea.com/
```


mail-ads.google.com

`Just log in to GMail. Really. That's it.`


domains.googlesyndication.com/relations

`Years and years of being contacted only by malicious files: https://www.virustotal.com/gui/domain/domains.googlesyndication.com/relations`


afs.googlesyndication.com

`Also years and years of being contacted only by malicious files: https://www.virustotal.com/gui/domain/afs.googlesyndication.com/relations`

**Comment by Alex-302** [comment]
Blocking googletagmanager.com and googletagservices.com will break many sites and apps.

**Comment by hollownights** [comment]
Nice! What about www.googleadservices.com and mail-ads.google.com, though? Like I said, to see mail-ads.google.com you just gotta log in to GMail. As for www.googleadservices.com, you can it here (one more website):

```
https://www.ionos.com/
https://www.smbc.co.jp/
```

**Comment by Alex-302** [comment]
blocking www.googleadservices.com will break many sites, google shop and google ads (it is annoying when used DNS filtering only)
