### ISSUE TITLE
Rezka.ag

### ISSUE THREAD

**Issue by SaintsHunter** [AdguardTeam/AdguardFilters#157391]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

Rezka.ag

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. Slow download speed ( маленькая скорость загрузки некоторых сайтов) 1080 dont work (не загружает 1080)
2. 2-3 mb/s speed without adguard, 30-300kb/s with it. This begin two or one week ago

3. Screenshots
<details><summary>Screenshot 1:</summary>

![IMG_20230725_220815](https://github.com/AdguardTeam/AdguardFilters/assets/140549697/24bba7d0-c302-4f16-abb7-6b333215bff3)

</details>

<details><summary>Screenshot N:</summary>

![IMG_20230725_221037](https://github.com/AdguardTeam/AdguardFilters/assets/140549697/da55b8f1-4ca2-4494-b82d-d8cac19e358f)

</details>
![IMG_20230725_221037](https://github.com/AdguardTeam/AdguardFilters/assets/140549697/638f8161-da10-4c19-b502-462db18f6b44)

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Not reproduced it on my end - we do not limit the download on the site. Note that AdGuard Russian is needed for that site.
