### ISSUE TITLE
Delete Unused Domains 

### ISSUE THREAD

**Issue by xqtp** [AdguardTeam/AdguardFilters#157373]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBO 1.51

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

-

### What filters do you have enabled?

AdGuard Turkish filter

### Add your comment and screenshots

These domains appear to be dead

```
belgeselciyiz.com
dizimax.plus
filmizle.tc
hd720pfilmizle.com
indircafe.net
torrenthd.org
```

### Privacy

- [X] I agree to follow this condition

**Comment by Yuki2718** [comment]
Exactly, only `filmizle.tc`, `indircafe.net`, and `torrenthd.org` are dead while `belgeselciyiz.com` and `dizimax.plus` are parked. `hd720pfilmizle.com` is arguable as having too many subdomain (at least they are not dead), but I can't find a working site so maybe safe to remove.
