### ISSUE TITLE
cowtransfer.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#157589]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.57

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://cowtransfer.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Anti-Facebook List

### Add your comment and screenshots

Click on empty space to reproduce.
Screenshots
<details><summary>Screenshot 1:</summary>

![f](https://github.com/AdguardTeam/AdguardFilters/assets/29574622/23c68ea1-df49-437a-b443-e12235534e79)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@SeriousHoax Please try `||cowtransfer.com/api/generic/backgrounds`

**Comment by SeriousHoax** [comment]
> ||cowtransfer.com/api/generic/backgrounds

Yeah, it works 👌
