### ISSUE TITLE
www.allocine.fr - videos won't play

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1575]
The [site](http://www.allocine.fr/video/player_gen_cmedia=19550279&cfilm=204027.html).

![image](https://cloud.githubusercontent.com/assets/15856304/13105118/0e5bf86c-d56a-11e5-8c04-1b2fd1a73221.png)

WRQ-809-36766

**Comment by Alex-302** [comment]
It works on my end witl Eng, Social, Spyware and Liste FR
@evgeniy-ADG, @Bohdan-SUP, @Serzh-SUP 
please, always request for filters lists, if user didn't sent logs.

**Comment by evgeniy-ADG** [comment]
У меня повторилось с расширением с базовыми фильтрами =/ 
Завтра напишу, что за фильтрьі.
