### ISSUE TITLE
trentapizza.ro

### ISSUE THREAD

**Issue by andreewmat** [AdguardTeam/AdguardFilters#157538]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Ublock Origin with AdGuard Annoyance Filter

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.trentapizza.ro/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment> Cookie pop-up on the website

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
As I see, the cookies are blocked by the generic rule from our AdGuard Annoyances. Try to update the filters, clear browser data, restart it, open the site.
Note that the website has low visitors.
```adblock
###cookie-alert
```
