### ISSUE TITLE
tinypic.com - popups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1576]
After an iamge is uploaded on - http://tinypic.com/ an ad for PC Keeper opens up in a new tab. Here is the ad address: http://land.pckeeper.software/land/7.13.222/index.php?affid=mzb_196.12580177.1455580711.20.mzb&utm_source=adsppl&utm_medium=popunder&utm_campaign=pck_adsppl_10w_us_2029&utm_term=&utm_content=&userDefiner=mzb_2337&trt=33_2029077&tid_ext=318 Here is a pic: http://tinypic.com/r/2ugkl6u/9

We have another redirect: 
![image](https://cloud.githubusercontent.com/assets/15856304/13105502/22e7ce44-d56c-11e5-94a2-9c3c5dfb374c.png)

QNQ-265-77213

**Comment by Alex-302** [comment]
Can't confirm.
