### ISSUE TITLE
tejji.com [Ad String]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#15777]
**Site**: http://tejji.com/ip/ip-address-to-url.aspx?ip=169.60.79.143

**Issue**: Please remove the Ad string on the page.

**Screenshot**: http://prntscr.com/jertqz

http://prntscr.com/jecsj0

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.139 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
2nd screenshot is not matching site. Please open a new ticket for it.

**Comment by Nzzyme** [comment]
ah, sorry for that.
