### ISSUE TITLE
daartads.com

### ISSUE THREAD

**Issue by aljvdi** [AdguardTeam/AdguardFilters#157806]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

Version 4.1.57 stable

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://daartads.com/

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

At first, I thought the website was experiencing some technical difficulties. But after checking with a few other users, I realised the problem was with AdGuard. Apparently, the software was blocking some of the website's scripts and stylesheets, causing the page to malfunction.

2. Screenshots
<details><summary>Screenshot 1 (ADG Enabled):</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/15309978/141bff08-1bf5-454a-ab90-e3b551ba3d9b)

</details>

<details><summary>Screenshot 2 (ADG Disabled):</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/15309978/1516f04a-b95f-4b46-ae72-371b34d881fd)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Not reproduced it with AdGuard Base on my end. Perhaps the problem lies in something else. Has firefox tracking protection been disabled?

<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/33488229/0a7071b8-fef7-4711-b029-cb4d2ce93b1a)

</details><br/>

**Comment by aljvdi** [comment]
yes

**Comment by zloyden** [comment]
Try to open the site without it, also update the filter.

**Comment by aljvdi** [comment]
@zloyden 

Firefox: With Firefox Tracking Protection, Without AdGaurd:

![image](https://github.com/AdguardTeam/AdguardFilters/assets/15309978/79b9f854-d786-494f-ad7d-fd9a4af6d65c)

**Comment by aljvdi** [comment]
@zloyden 

Firefox Tracking Protection is off, and AdGuard base is ON:

![image](https://github.com/AdguardTeam/AdguardFilters/assets/15309978/d72cb6d1-9986-4225-8548-0bd841958204)

**Comment by aljvdi** [comment]
@zloyden 

It's fixed on Firefox when I turned Firefox tracking off; however, I have the error on MS-edge.

**Comment by zloyden** [comment]
That's really strange. Could you send the screenshot of the filtering log?
To do it:
1. Open the filtering log
2. Press on `blocked` button (it will show only the blocked requests) and keep the filtering log on the background
3. Reproduce the problem
4. Go back to the filtering log
5. Make a screenshot and send it here.

**Comment by zloyden** [comment]
> It's fixed on Firefox when I turned Firefox tracking off; however, I have the error on MS-edge.

So the firefox tracking protection causes it? Edge also have the same built-in functionality.

**Comment by aljvdi** [comment]
> That's really strange. Could you send the screenshot of the filtering log? To do it:
> 
> 1. Open the filtering log
> 2. Press on `blocked` button (it will show only the blocked requests) and keep the filtering log on the background
> 3. Reproduce the problem
> 4. Go back to the filtering log
> 5. Make a screenshot and send it here.

![image](https://github.com/AdguardTeam/AdguardFilters/assets/15309978/c982f387-5385-41b1-8d4e-425ee2e0d55b)

**Comment by aljvdi** [comment]
> > It's fixed on Firefox when I turned Firefox tracking off; however, I have the error on MS-edge.
> 
> So the Firefox tracking protection causes it? Edge also has the same built-in functionality.

Edge has something like Firefox, but I never turned that on in my browser.

![image](https://github.com/AdguardTeam/AdguardFilters/assets/15309978/6b829160-a0ff-4bc8-9d40-1b6d62c0344e)

**Comment by zloyden** [comment]
> Edge has something like Firefox, but I never turned that on in my browser.

It's not caused by the built-in protection. Actually, your screenshot shows the requests are blocked by `Persian Blocker`.
It's a third-party filter and only the author can fix it. @MasterKia could you take a look at this?
@aljvdi btw, this rule can help if you add it to User rules.

```adblock
@@||daartads.com^$important
```

**Comment by aljvdi** [comment]
Cheers, I'll be adding that rule.

**Comment by aljvdi** [comment]
> Please just disable AdGuard on that specific page. That site is on the list because it's advertising site, only used by their customers.
> 
> @aljvdi این سایت چون یک سایت تبلیغاتیه توی لیست هست، لطفاً‌ افزونه ادگارد رو توی اون صفحه غیرفعّال کنید.

I agree that it's an advertising website. However, you blocked the wrong domain.

Please check the following:
https://github.com/MasterKia/PersianBlocker/issues/191
