### ISSUE TITLE
Please remove the hardcoded rules to block EFF panopticlick tracking tests

### ISSUE THREAD

**Issue by jawz101** [AdguardTeam/AdguardFilters#15785]
I don't see the point of simply blocking these domains by hardcoding them in a list.
trackersimulator.org
eviltracker.net
do-not-tracker.org

If their purpose is to test certain fingerprinting techniques, why prevent them from doing that?  You're effectively breaking the test of techniques that thousands of actual tracking companies use by blocking these 3 innocuous domains.

I can't find the right words to explain that.

All I know is that you have these 3 domains sprinkled around in your various blocklists.  I liken this to cell phone companies overclocking your phone when running benchmark apps.  It helps your brand but we're actually trying to test something specific.

**Comment by Alex-302** [comment]
That is unnecessary. This is just test site.
