### ISSUE TITLE
advocatechannel.com

### ISSUE THREAD

**Issue by jputting** [AdguardTeam/AdguardFilters#158073]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.11.0.1292

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://advocatechannel.com/oceans-exploration-why-so-risky

### What filters do you have enabled?

AdGuard Social Media filter

### Add your comment and screenshots

Adguard Social Media Filter List is blocking thumbnail images on this webpage:
https://advocatechannel.com/oceans-exploration-why-so-risky)

Scroll down to where you see a side scrolling strip of featured stories from "EQUALPRIDE".

When the Adguard Social Media Filter List is used the thumbnail images are blocked. NO other Filter Lists were used and all other Adguard functions were disabled.

When the Adguard Social Media List is removed or disabled the thumbnail images are present.

This Adguard Social Media Filter list is too aggressive and blocking too much .
Please update your dguard Social Media Filter List soon. 

![With No Filter Lists Screenshot 2023-08-03 at 5 04 31 pm](https://github.com/AdguardTeam/AdguardFilters/assets/10370101/e88a6621-7f54-4162-9026-9029f812cf57)
![With Adguard Social Media Filter list Screenshot 2023-08-03 at 5 03 31 pm](https://github.com/AdguardTeam/AdguardFilters/assets/10370101/34eed3b2-f5f5-425d-a952-2edd7c8dd43f)

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.

**Comment by zloyden** [comment]
Btw, these rules may be useful. I would add them if the site had enough visits.

```adblock
advocatechannel.com##.newsletter-overlay
advocatechannel.com##div[class^="ad_"]
advocatechannel.com##.top__leaderboard
advocatechannel.com##.sidebar-newsletter
advocatechannel.com##.sponsors
advocatechannel.com##.editorial-copy
```

**Comment by jputting** [comment]
Hi zloyden, Thanks for the additional filters, they do help

**Comment by zloyden** [comment]
You are welcome:)
