### ISSUE TITLE
If you block the space item on the web version of Twitter, the display disappears, but it flickers when you scroll

### ISSUE THREAD

**Issue by yuki12127** [AdguardTeam/AdguardFilters#158068]
### AdGuard version

7.13 nightly 20 (build 4290, CL 1.11.116)

### Browser version

114.0.5735.199

### OS version

Windows 11 Pro 64-bit (10.0, Build 22621)

### Support ticket ID

772127

### Issue Details

If you block ``open space in progress'' on the web version of Twitter, it will disappear, but it will flicker when scrolling

### Additional Information

The nightly build is used to avoid the Google Translate page not opening. I learned from support.

**Comment by Alex-302** [comment]
I can't reproduce it with
`twitter.com##.r-1d6w8o1.r-1867qdf.r-1phboty.r-rs99b7.r-1ifxtd0.r-1udh08x:nth-child(4)`
