### ISSUE TITLE
merchant.bigcommerceuniversity.com

### ISSUE THREAD

**Issue by philipannis** [AdguardTeam/AdguardFilters#158006]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.57

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

merchant.bigcommerceuniversity.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Block WebRTC, Hide Referrer from third-parties (specify in comment below, if used custom value)

### Comment

Username: @philipannis

### Screenshots
<details>
<summary>Screenshot 1:</summary>
![Screenshot 2023-08-02 at 9 00 27 AM](https://github.com/AdguardTeam/AdguardFilters/assets/18536856/a4c6aab9-16af-4611-a14c-973e7d4e87e0)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
The website has low visitors.
