### ISSUE TITLE
Zoechip3.com userules you guys told me to add are no longer working 

### ISSUE THREAD

**Issue by olstice** [AdguardTeam/AdguardFilters#158058]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.6

### What type of problem have you encountered?

Missed ads or ad leftovers, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www3.zoechip.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment> The custom user rules you guys told me to add are no longer working every time I click the search bar or click a movie it opens a pop up 2. 

Please and thank you 

3. 
4. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Please enable AdGuard Annoyances Filter, the sharing popup is hidden by this filter

**Comment by olstice** [comment]
> Please enable AdGuard Annoyances Filter, the sharing popup is hidden by this filter

I actually tried to figure this out my self by using inspect element but i couldnt find where the redirects were coming from are they located in head and not body?

**Comment by olstice** [comment]
> Please enable AdGuard Annoyances Filter, the sharing popup is hidden by this filter

Adding annoyances filter does not stop the redirects if you click anywhere on the website.

**Comment by olstice** [comment]
I did it i figured it out, the way i figured it out thou i had to do trial and error of opening the filtering log of adguard of zoechip and just block and block every href link until i found the one that if i click the page will redirect me to another site


Is that what you guys have to do also?

Literally block one by one each head meta tag until you find the one that actually causes the problem?


if so than i dont feel as bad that i had to rely on that


But if you dont than i guess i have nothing to feel accomplished about

**Comment by jellizaveta** [comment]
Unfortunately, I cannot reproduce the ads popups. What address does the popup open with? Do you have DNS enabled?

**Comment by olstice** [comment]
> Unfortunately, I cannot reproduce the ads popups. What address does the popup open with? Do you have DNS enabled?

Well actually through trial and error of trying to figure this out my self i found out that the culprit is this link embeded into the script tags of the head in html that contains javascript causing the redirects


The only issue is the url link containing the javascript redirects changes frequently 

Making the userrule i add of the specific url link ineffective on blocking the redirects when i click anywhere of the website


https://kayb.krvemwbmjzrwy.top/kqmlvellejwmj/abqaj right now its this



But before it was this https://krze.klrqqylrzzzj.top/kzzeenqvnqjww/abqaj

And so on and so on with the only similairity of each url link all having.top and /abqaj


of where i had to make mutliple userrules since the last one no longer apllies when the url link changes


klrqqylrzzzj.top^$important
||qnlranvabrnq.top^$important

![image](https://github.com/AdguardTeam/AdguardFilters/assets/124982114/a9f6473b-0e73-46e5-8b50-1ab1eb466095)

![image](https://github.com/AdguardTeam/AdguardFilters/assets/124982114/30714e83-c64e-4d6e-91ae-4eee9079e3d4)

![image](https://github.com/AdguardTeam/AdguardFilters/assets/124982114/836a258b-33ae-4859-b50b-ff8468c74a55)

**Comment by jellizaveta** [comment]
Could you check if this rule helps in blocking popups if added to user rules:
```
/^(?!.*(sharecast.ws|bunnycdn.ru|bootstrapcdn.com|cdn.ampproject.org|cloudflare.com|cdn.staticfile.org|disqus.com|disquscdn.com|dmca.com|ebacdn.com|facebook.net|fastlylb.net|fbcdn.net|fluidplayer.com|fontawesome.com|github.io|google.com|googleapis.com|googletagmanager.com|gstatic.com|jquery.com|jsdelivr.net|jwpcdn.com|jwplatform.com|polyfill.io|recaptcha.net|shrink.pe|twitter.com|ulogin.ru|unpkg.com|userapi.com|vidazoo.com|vk.com|yandex.|yastatic.net|ytimg.com|zencdn.net|player|youtube.com|cackle.me|googleoptimize.com|vuukle.com|chatango.com|twimg.com|google-analytics.com|hcaptcha.com|raincaptcha.com|media-imdb.com|blogger.com|hwcdn.net|instagram.com|wp.com|imgsmail.ru)).*$/$third-party,script,_____,domain=zoechip.com
```

**Comment by olstice** [comment]
> Could you check if this rule helps in blocking popups if added to user rules:
> 
> ```
> /^(?!.*(sharecast.ws|bunnycdn.ru|bootstrapcdn.com|cdn.ampproject.org|cloudflare.com|cdn.staticfile.org|disqus.com|disquscdn.com|dmca.com|ebacdn.com|facebook.net|fastlylb.net|fbcdn.net|fluidplayer.com|fontawesome.com|github.io|google.com|googleapis.com|googletagmanager.com|gstatic.com|jquery.com|jsdelivr.net|jwpcdn.com|jwplatform.com|polyfill.io|recaptcha.net|shrink.pe|twitter.com|ulogin.ru|unpkg.com|userapi.com|vidazoo.com|vk.com|yandex.|yastatic.net|ytimg.com|zencdn.net|player|youtube.com|cackle.me|googleoptimize.com|vuukle.com|chatango.com|twimg.com|google-analytics.com|hcaptcha.com|raincaptcha.com|media-imdb.com|blogger.com|hwcdn.net|instagram.com|wp.com|imgsmail.ru)).*$/$third-party,script,_____,domain=zoechip.com
> ```

Ill add that userule on my Adguard IOS app and see if it does it

**Comment by jellizaveta** [comment]
Sometimes popups can appear because the implementation of syntax is delayed on iOS. This rule won't work on ios, sorry, I'm a bit confused because of the filtering log screenshots.

**Comment by jellizaveta** [comment]
@AdguardTeam/filters-maintainers could you please take a look?

**Comment by olstice** [comment]
> Sometimes popups can appear because the implementation of syntax is delayed on iOS. This rule won't work on ios, sorry, I'm a bit confused because of the filtering log screenshots.

Sir or mam please do not bother trying to explain this to me i dont understand anything your saying i am just an adguard user who pays for adguard annually so i dont have to deal with this and so you guys can do it for me


i tried to figure it out i dont understand it, i dont comprehend it iv accepted that im smart enough to get this like you all


so please do not waste your time messaging all this just inform me that the issue is being looked at or its been resolved

**Comment by jellizaveta** [comment]
I understand your frustration with the ongoing issue, and I apologize for the delay in finding a fix. I'd like to suggest trying an alternative variant in user rules that might be suitable: `.top/k*/a*$domain=zoechip.com` . Could you please clear your browser cache and enable/disable content blockers in safari settings before checking. Thank you for your patience.

**Comment by olstice** [comment]
> I understand your frustration with the ongoing issue, and I apologize for the delay in finding a fix. I'd like to suggest trying an alternative variant in user rules that might be suitable: `.top/k*/a*$domain=zoechip.com` . Could you please clear your browser cache and enable/disable content blockers in safari settings before checking. Thank you for your patience.

the user rule you suggested did not work i will try this one

**Comment by jellizaveta** [comment]
You can also try this rule:
```
$script,third-party,denyallow=sharecast.ws|bunnycdn.ru|bootstrapcdn.com|cdn.ampproject.org|cloudflare.com|cdn.staticfile.org|disqus.com|disquscdn.com|dmca.com|ebacdn.com|facebook.net|fastlylb.net|fbcdn.net|fluidplayer.com|fontawesome.com|github.io|google.com|googleapis.com|googletagmanager.com|gstatic.com|jquery.com|jsdelivr.net|jwpcdn.com|jwplatform.com|polyfill.io|recaptcha.net|shrink.pe|twitter.com|ulogin.ru|unpkg.com|userapi.com|vidazoo.com|vk.com|yastatic.net|ytimg.com|zencdn.net|youtube.com|cackle.me|googleoptimize.com|vuukle.com|chatango.com|twimg.com|google-analytics.com|hcaptcha.com|raincaptcha.com|media-imdb.com|blogger.com|hwcdn.net|instagram.com|wp.com|fastcomments.com|plyr.io,_____,domain=zoechip.com
```

**Comment by jellizaveta** [comment]
@olstice hello! Any news?

**Comment by olstice** [comment]
@jellizaveta it seems to be working so far of the last userrule you gave me 2 days ago

**Comment by jellizaveta** [comment]
Thanks for checking, added the rule to AdGuard filters will be available with the new update in 1-2 hours
