### ISSUE TITLE
dizilah.com

### ISSUE THREAD

**Issue by xivi1839** [AdguardTeam/AdguardFilters#158023]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.51.0

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://dizilah.com/article/first-look-yabani-fox-cast-plot-summary

### What filters do you have enabled?

---Third-party filters---

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

uBlock Origin 1.51.0

新闻看不了了，全被屏蔽了，请解决该问题。

I can't read the news anymore, it's all blocked，please fix this

https://dizilah.com/article/first-look-yabani-fox-cast-plot-summary

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Working fine, please provide enabled filters.
