### ISSUE TITLE
marca.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#158010]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.14

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://amp.marca.com/en/tennis/2023/08/01/64c95b64268e3e343a8b45c5.html?nc
### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Anti-Facebook List

### Add your comment and screenshots

Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/29574622/94933c82-556b-4734-80ab-30199c9f93bb)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reproduced. Need code of the element.

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/bf9daf12-d57e-42f0-b59b-1230a3181d42)


</details>

**Comment by SeriousHoax** [comment]
> Not reproduced. Need code of the element.
> 
> Details

From Adguard Desktop's Element Picker:

`amp.marca.com##main:nth-child(10) > div.ue-l-article:nth-child(2) > div.ue-l-article__inner > article.ue-c-article.has-image > div.ue-l-article__body:last-child > div.ue-l-article__main-column.ue-l-article--minimum-content-from-tablet > div.ue-c-article__body:nth-child(4) > div.ue-c-ad.ue-c-ad--label.ready:nth-child(3) > amp-ad.ad-slot.i-amphtml-element.i-amphtml-notbuilt.amp-notbuilt.i-amphtml-layout-fixed.i-amphtml-layout-size-defined.amp-unresolved.i-amphtml-unresolved`

From Brower Console:

`<amp-ad class="ad-slot i-amphtml-element i-amphtml-notbuilt amp-notbuilt i-amphtml-layout-fixed i-amphtml-layout-size-defined amp-unresolved i-amphtml-unresolved" width="300" height="600" data-multi-size="300x600,300x250,300x300" data-multi-size-validation="false" type="doubleclick" data-block-on-consent="" data-slot="/99071977/mc-mv2/en/tennis/amp-n" json="{&quot;targeting&quot;:{&quot;p&quot;:&quot;r&quot;, &quot;amp&quot;:1,&quot;nc&quot;:&quot;1&quot;}
}" rtc-config="{
            &quot;vendors&quot;: {
                &quot;criteo&quot;: {&quot;NETWORK_ID&quot;: 1080, &quot;LINE_ITEM_RANGES&quot;: &quot;0..10:0.01;10..25:0.05;25..50:0.10;50..100:0.25&quot;},
                &quot;aps&quot;: {&quot;PUB_ID&quot;: &quot;3537&quot;,&quot;PARAMS&quot;:{&quot;amp&quot;:&quot;1&quot;}},
                &quot;prebidappnexuspsp&quot;: { &quot;PLACEMENT_ID&quot;: 17602477 },
                &quot;richaudience&quot;: { &quot;PLACEMENT_ID&quot;: &quot;XAi8cpOVT8&quot; }}
                            ,&quot;urls&quot;: [ &quot;https://unidad.amp.permutive.com/rtc?type=doubleclick&quot; ]
                    }" data-npa-on-unknown-consent="true" i-amphtml-layout="fixed" style="width: 300px; height: 600px; --loader-delay-offset: 0ms !important;"><div slot="i-amphtml-svc" class="i-amphtml-svc i-amphtml-loading-container i-amphtml-fill-content"><div class="amp-active"><div class="i-amphtml-new-loader i-amphtml-new-loader-size-default"><div class="i-amphtml-new-loader-shim"></div><div class="i-amphtml-new-loader-logo"><div class="i-amphtml-new-loader-ad-logo"><span class="i-amphtml-new-loader-ad-label">Ad</span></div></div><div class="i-amphtml-new-loader-spinner-wrapper"><svg class="i-amphtml-new-loader-spinner" viewBox="0 0 48 48"><path class="i-amphtml-new-loader-spinner-path" fill="none" d="M24 2a22 22 0 10.01 0m33.27 5.65a22 22 0 102.74-2.1m46.13 1.35a22 22 0 105.96-3.44m42.96 2.74a22 22 0 109.49-3.93m39.46 3.28a22 22 0 1013.13-3.52M253 4.95a22 22 0 1016.69-2.2m32.32 1.65a22 22 0 1019.98 0m29.06-.5a22 22 0 1022.79 3m26.28-3.44a22 22 0 1024.98 6.69m24.1-7.07a22 22 0 1026.4 10.94m22.71-11.27a22 22 0 1026.94 15.56m22.18-15.83a22 22 0 1026.54 20.37m22.59-20.58a22 22 0 1025.17 25.17M645.7 2.12a22 22 0 1022.84 29.76m26.31-29.85a22 22 0 1019.6 33.95M744 2a22 22 0 1015.56 37.56m33.59-37.53a22 22 0 1010.83 40.42M842.3 2.12a22 22 0 105.58 42.42m43.56-42.27a22 22 0 100 43.46m49.13-43.25a22 22 0 10-5.73 43.49m54.85-43.22a22 22 0 10-11.39 42.5m60.5-42.17a22 22 0 00-16.79 40.53m65.87-40.15a22 22 0 00-21.73 37.64m70.8-37.2a22 22 0 00-26.05 33.94m75.09-33.44a22 22 0 00-29.59 29.59M1235 4.95a22 22 0 00-32.25 24.75m81.23-24.15a22 22 0 00-33.95 19.6m82.9-18.95a22 22 0 00-34.66 14.36m83.58-13.66a22 22 0 00-34.38 9.21m83.25-8.46a22 22 0 00-33.17 4.37m82.01-3.58a22 22 0 00-31.11 0m81.35 2.63a22 22 0 00-32.52-3.42m82.32 6.36a22 22 0 00-33.45-7.11m82.77 10.3a22 22 0 00-33.85-11m82.66 14.36a22 22 0 00-33.71-15.01M1726 24a22 22 0 00-33-19.05m80.73 22.49a22 22 0 00-31.72-23.04m78.91 26.4a22 22 0 00-29.87-26.9m76.55 30.09a22 22 0 00-27.49-30.53m73.69 33.47a22 22 0 00-24.6-33.85m70.36 36.48a22 22 0 00-21.25-36.81m66.62 39.05a22 22 0 00-17.51-39.32m62.57 41.12a22 22 0 00-13.43-41.33m58.24 42.65a22 22 0 00-9.1-42.8m53.74 43.61a22 22 0 00-4.59-43.7M2184 46a22 22 0 100-44m44.56 43.73a22 22 0 104.59-43.7m40.05 42.89a22 22 0 109.1-42.8m35.71 41.48a22 22 0 1013.43-41.33m31.63 39.53a22 22 0 1017.51-39.32m27.86 37.08a22 22 0 1021.25-36.81m24.51 34.18a22 22 0 1024.6-33.85m21.6 30.91a22 22 0 1027.49-30.53m19.19 27.34a22 22 0 1029.87-26.9m17.32 23.54a22 22 0 1031.72-23.04M2642 24a22 22 0 1033-19.05m15.27 15.61a22 22 0 1033.71-15.01m15.1 11.65a22 22 0 1033.85-11m15.47 7.81a22 22 0 1033.45-7.11m16.35 4.17a22 22 0 1032.52-3.42m17.72.79a22 22 0 1031.11 0m17.73-.79a22 22 0 1032.52 3.42m16.35-4.17a22 22 0 1033.45 7.11m15.47-7.81a22 22 0 1033.85 11m15.1-11.65a22 22 0 1033.71 15.01M3133 4.95A22 22 0 103166 24m16.01-19.6a22 22 0 1031.72 23.04m17.32-23.54a22 22 0 1029.87 26.9m19.2-27.34a22 22 0 1027.49 30.53m21.59-30.91a22 22 0 1024.6 33.85m24.51-34.18a22 22 0 1021.25 36.81m27.87-37.08a22 22 0 1017.51 39.32m31.62-39.53a22 22 0 1013.43 41.33m35.71-41.48a22 22 0 109.1 42.8m40.05-42.89a22 22 0 104.59 43.7M3624 2a22 22 0 100 44m49.15-43.97a22 22 0 00-4.59 43.7m53.74-43.61a22 22 0 00-9.1 42.8m58.24-42.65a22 22 0 00-13.43 41.33m62.56-41.12a22 22 0 00-17.51 39.32m66.63-39.05a22 22 0 00-21.25 36.81m70.36-36.48a22 22 0 00-24.6 33.85m73.68-33.47a22 22 0 00-27.49 30.53m76.56-30.09a22 22 0 00-29.87 26.9m78.91-26.4a22 22 0 00-31.72 23.04M4115 4.95A22 22 0 004082 24m81.98-18.45a22 22 0 00-33.71 15.01m82.66-14.36a22 22 0 00-33.85 11m82.77-10.3a22 22 0 00-33.45 7.11m82.32-6.36a22 22 0 00-32.52 3.42"></path></svg></div></div></div></div></amp-ad>`

Hope this helps.

**Comment by Alex-302** [comment]
`amp.marca.com##.ue-c-ad` blocks it.

**Comment by SeriousHoax** [comment]
> `amp.marca.com##.ue-c-ad` blocks it.

Did you want me to test by putting this in user rules? 
I did but nothing changed.

**Comment by Alex-302** [comment]
Please show attributes of `.ue-c-ad` in dev tools.

**Comment by Yuki2718** [comment]
> `amp.marca.com##.ue-c-ad` blocks it.

It is in Mobile filter, but he uses desktop. I will add the rule to EL (as generic for their preference).

**Comment by Alex-302** [comment]
ok
