### ISSUE TITLE
Zoechip turns out my fix is only a temporary solution

### ISSUE THREAD

**Issue by olstice** [AdguardTeam/AdguardFilters#158193]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.6

### What type of problem have you encountered?

Missed ads or ad leftovers, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www3.zoechip.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>So I thought I had this resolved turns out it was only a temporary solution the website Zoechip has an imbeded head meta tag href link of which right now its https://zkwl.zwmvyzyrlvzew.top/kbwaazlzkwjla/abqaj

before that it was https://krze.klrqqylrzzzj.top/kzzeenqvnqjww/abqaj

the only connection both url have is the .top/abqaj everything else is different.

And no matter which one i block of these rules ||zwmvyzyrlvzew.top^$important  klrqqylrzzzj.top^$important   ||qnlranvabrnq.top^$important

A new one just gets added into the head meta tag section of the html making the rule no longer apply

I need help please!!!!
3. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
If I understand correctly, we already have one open task on this site.

**Comment by olstice** [comment]
> If I understand correctly, we already have one open task on this site.


so did you guys resolve the IOS issue with https://www3.zoechip.com ?

**Comment by olstice** [comment]
> If I understand correctly, we already have one open task on this site.

please stop trying to explain this all to me i dont comprehend it at all 


just use words everyone understands of the problem is being looked at or its been resolved


i tried to get this and i dont so iv accepted i am just average and basic and i do not comprehend this
