### ISSUE TITLE
cleanup unused rules

### ISSUE THREAD

**Issue by xqtp** [AdguardTeam/AdguardFilters#158156]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

-

### What filters do you have enabled?

AdGuard Turkish filter

### Add your comment and screenshots

```
https://github.com/AdguardTeam/AdguardFilters/issues/13155
cezmikalorifer.com###secondary > aside[id^="media_image-"]

---

https://github.com/AdguardTeam/AdguardFilters/issues/10803
showradyo.com.tr##.wrapper_right
showradyo.com.tr##.wrapper_left

---

! https://forum.adguard.com/index.php?threads/14807/
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=ulke.com.tr

---

https://github.com/AdguardTeam/AdguardFilters/issues/12487
cumhuriyet.com.tr##.ajans

---

https://forum.adguard.com/index.php?threads/resolved-cumhuriyet-com-tr.16259/#post-113281
cumhuriyet.com.tr###page-wrapper > div#headeresque > [class^="hdr-"]

---

https://forum.adguard.com/index.php?threads/resolved-cumhuriyet-com-tr.20712/
cumhuriyet.com.tr##.s728x90

---

https://forum.adguard.com/index.php?threads/resolved-2-missed-ads.11483/#post-89096
ulke.com.tr##.newsDetailsAdvertisingBanner

---

https://forum.adguard.com/index.php?threads/resolved-ulke-com-tr.15784/
ulke.com.tr##.lineType1:empty

----

https://forum.adguard.com/index.php?threads/resolved-2-missed-ads.11483/#post-89096
ulke.com.tr##div[class^="banner"]

---

https://github.com/AdguardTeam/AdguardFilters/issues/62927
||otekisinema.com/wp-content/uploads/*/bann-

---

https://forum.adguard.com/index.php?threads/resolved-missed-ads-5-websites.10419/
otekisinema.com##.header-content a[rel="nofollow"] > img




```

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
No need to post rules if the site is dead. Just list domain.
