### ISSUE TITLE
nationaltoday.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#158265]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.51.1b7

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://nationaltoday.com/birthday/satoru-iwata/

### What filters do you have enabled?

AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment>
Some content will be unloaded until you scroll because of a Cloudflare JavaScript code.
`||cdnjs.cloudflare.com/ajax/libs/ScrollMagic/`

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
What is unloaded?

**Comment by Sonic5435325** [comment]
@Alex-302 Some of the text won't show unless you scroll down from the page.
