### ISSUE TITLE
[iOS] nyaa.se

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1583]
nyaa.se
LSE-920-45707

<details>
![image-3](https://cloud.githubusercontent.com/assets/14153331/13131900/5c2dd834-d5f7-11e5-8cab-cd3d21829b1f.png)
![image-2](https://cloud.githubusercontent.com/assets/14153331/13131901/5c320490-d5f7-11e5-871c-38f53df45ddc.png)
![image](https://cloud.githubusercontent.com/assets/14153331/13131902/5c44f3f2-d5f7-11e5-86d5-9dcd3a79247a.png)

</details>

**Comment by Alex-302** [comment]
Can't access to this site.

**Comment by Alex-302** [comment]
@Bohdan-SUP

**Comment by Bohdan-SUP** [comment]
Here'a screen from Win:
![image](https://cloud.githubusercontent.com/assets/14153331/13331306/8b6fff8c-dc05-11e5-99d7-ebc48102f60c.png)

**Comment by Alex-302** [comment]
added
nyaa.se##a[href^="http://www.nyaa.se/ap/"] > img

**Comment by evgeniy-ADG** [comment]
>ollow-up to # LSE-920-45707. as of this posting i am seeing ads on nyaa.se again both on ios and osx safari extension.

Please check
