### ISSUE TITLE
zoechip.com

### ISSUE THREAD

**Issue by olstice** [AdguardTeam/AdguardFilters#158467]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.6

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www3.zoechip.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>I'm really worried that I did something wrong and that that's why no one was assigned to my last issue or responded. If i did something against the Adguard rules, please inform me! I am very sorry for whatever is i did. Am I on a temporary suspension? A permanent suspension? Is there anything I can do to appeal?

If anyone could please inform me it be very helpful because I actually pay for Adguard. I'm on the premium on my phone and well if i am suspended permanently or something and can't get any more technical support with your app, well i need to know so that I know, it's nothing personal!
no hard feelings end my subscription and fine another adblock team that hopfully i wont have caused infractors with if i have caused any with you guys!

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/124982114/96cd824d-e648-4fc1-8fad-e5179c59a8ec)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/158470

**Comment by olstice** [comment]
> #158470
its not fixed! i updated by adguard and if you click anywhere of the website https://www3.zoechip.com/

it still redirects you to another page

The culprit is this link https://kayb.krvemwbmjzrwy.top/kqmlvellejwmj/abqaj

problem is this link located in the script tag of the head tag of html which contains the javascript code of the redirect changes freqently to a different url link making the initnial userule to the last url obsolute

before that it was this url link https://krze.klrqqylrzzzj.top/kzzeenqvnqjww/abqaj

it changes constanly with the only reconsiable part of every url being the .top and the /abqag

of which each ones code of every url link is of the majority the exact with a bit added that was not in the last
