### ISSUE TITLE
AdGuard family DNS is blocking access to `is-a.dev` and subdomains

### ISSUE THREAD

**Issue by thunder-coding** [AdguardTeam/AdguardFilters#158457]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS, Other ad blocker

### AdGuard version

(unrelated)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://is-a.dev and subdomains

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

Cloudflare DNS :+1:
```
$ dnslookup is-a.dev 1.1.1.1
dnslookup v1.9.1
dnslookup result (elapsed 237.200857ms):
;; opcode: QUERY, status: NOERROR, id: 53708
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;is-a.dev.      IN       A

;; ANSWER SECTION:
is-a.dev.       1200    IN      A       68.65.123.44
```

With Google DNS (8.8.8.8) :+1:

```
$ dnslookup is-a.dev 8.8.8.8
dnslookup v1.9.1
dnslookup result (elapsed 136.851108ms):
;; opcode: QUERY, status: NOERROR, id: 19213
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;is-a.dev.      IN       A                                                 
;; ANSWER SECTION:
is-a.dev.       1200    IN      A       68.65.123.44
```

With AdGuard Default (blocks ads + trackers) :+1:
```
$ dnslookup is-a.dev 94.140.14.14
dnslookup v1.9.1                                                           dnslookup result (elapsed 409.14004ms):
;; opcode: QUERY, status: NOERROR, id: 52383
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;is-a.dev.      IN       A

;; ANSWER SECTION:
is-a.dev.       1200    IN      A       68.65.123.44

$ dnslookup is-a.dev 94.140.15.15
dnslookup v1.9.1
dnslookup result (elapsed 156.634599ms):
;; opcode: QUERY, status: NOERROR, id: 26887
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;is-a.dev.      IN       A

;; ANSWER SECTION:
is-a.dev.       1183    IN      A       68.65.123.44
```

AdGuard non-filtering (same result as for above default filtering one) :+1:

AdGuard Family :-1:

```
$ dnslookup is-a.dev 94.140.14.15
dnslookup v1.9.1
dnslookup result (elapsed 167.088819ms):
;; opcode: QUERY, status: NOERROR, id: 22995
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;is-a.dev.      IN       A

;; ANSWER SECTION:
is-a.dev.       3600    IN      A       94.140.14.35

$ dnslookup is-a.dev 94.140.15.16
dnslookup v1.9.1
dnslookup result (elapsed 198.463718ms):
;; opcode: QUERY, status: NOERROR, id: 31559
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;is-a.dev.      IN       A

;; ANSWER SECTION:
is-a.dev.       3600    IN      A       94.140.14.35
```

Note that 68.65.123.44 is the good IP, 94.140.14.35 returns a site displaying that access to the site was denied (can't open in browser as Firefox refuses to open the page due to.SSL certificate errors). Raw HTML can be viewed with `curl -k`. **WARNING: `-k` WILL IGNORE ANY CERTIFICATE**
## Additional details

This issue was earlier reported here: https://github.com/is-a-dev/register/issues/6838

This issue was found as I was not able to connect to any of `*.is-a.dev` as well as `is-a.dev` on my phone. I use a VPN server running on localhost which disables ads by DNS injection (basically all ad sites are routed to 0.0.0.0, this disables ads on most sites improving my internet experience). This along with uBlock origin gives a really clean experience on my phone. A temporary workaround for me is to use CloudFlare or Google's DNS servers. This doesn't make any difference to me as I have a separate blocklist as well which disables ad sites as well as inappropriate sites which are not included by AdGuard DNS

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
The site has been removed from parental control lists, an update will be available within 1-2 hours.

**Comment by thunder-coding** [comment]
> The site has been removed from parental control lists, an update will be available within 1-2 hours.

Just out of curiosity, you guys aren't releasing your DNS server blocklist unlike client side blocks?

**Comment by jellizaveta** [comment]
There are no separate block lists for parental controls or phishing. But we have tracking and advertising [blocklist](https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt)
