### ISSUE TITLE
zoechip.com

### ISSUE THREAD

**Issue by olstice** [AdguardTeam/AdguardFilters#158568]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.4.6

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www3.zoechip.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>The inline script userule suggested to me did work for windows adguard extension ||zoechip.com/|$inline-script,important

it however did not work on Adguard IOS

of which neither did this userule work on IOS either

||zoechip.com/|$csp=script-src 'self' 'unsafe-eval' http: https: data: blob: mediastream: filesystem:,important

So for windows the redirect is blocked for IOS its not

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/124982114/73ec7173-71b2-45ab-8304-e48e99d421ab)

</details>
![image](https://github.com/AdguardTeam/AdguardFilters/assets/124982114/1f82d7dd-ddd5-443b-8b4a-6059e62d4ea4)

<details><summary>Screenshot N:</summary>

</details>Also im trying to learn your adblock and the custom filters

So im gonna take a shot here would these filter rules of which right now are not put correctly therefore will not block

http://ads.example.org.us/ad1.gif
    http://example.com/redirect/http://ads.example.org/
    
    Would they block if they were typed this way instead?
    
    http://ads.example.org/us/ad1.gif
    http://example.com/http:ads.example.org/redirect
    
    or would it be http://ads.example.org/redirect?
    
    
    meaning there was never supposed to be a .com only a .org because in this example these are orginization websites?
    
    or is there an example.com commerical website and a example.org orginzation website
    
    of where if what i understand is correct the addresses of websites go first of http://example.com/http:ads.example.org/redirect?
    
    
    or would it actually be http://example.com/redirect
    
    and http://ads.example.org/redirect
    
    meaning they would be two seperate filter rules?

Im trying to understand this!

If im completely wrong on why these would not be blocked

than i dont comprehend your websites explanation on filter rules at all

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
csp is not supported on iOS in basic mode. You may try to enable Advanced Protection (it allows more advanced rules to work, unsure about $csp - @zloyden do you know?).

Sadly I do not understand your questions exactly regarding filter syntax. Please elaborate your rule suggestion and the question to them.

**Comment by BlazDT** [comment]
I did not check.

**Comment by zloyden** [comment]
Could you take a look at it?

**Comment by olstice** [comment]
> Could you take a look at it?


so did you guys resolve the IOS issue with https://www3.zoechip.com ?

**Comment by olstice** [comment]
> I did not check.


so did you guys resolve the IOS issue with https://www3.zoechip.com ?

**Comment by olstice** [comment]
Krystain3w said the problem is not being analyzed or repaired why is this?

**Comment by BlazDT** [comment]
Please add this rule to user filter:
/abqaj$domain=zoechip.com

Please note it is not safely fixable via generic rules as Apple's limitation (no regexp rules).


Also it would be nice if you could avoid double posts, those just produce unnecessary emails.

**Comment by olstice** [comment]
@BlazDT oh i figured out now how to address a specific person also i think @jellizaveta resolved it with their userrule but in case it no longer works i will def try yours
