### ISSUE TITLE
Проблемная маска!

### ISSUE THREAD

**Issue by Big-U-Boss** [AdguardTeam/AdguardFilters#15867]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***: Из-за маски ||rs.mail.ru/*.gif происходит множественный вброс запросов которые то и дело  появляются с произвольными значениями тем самым забивая озу и  вешает расширение а вскоре и старинцу, поэтому просьба убрать его из списка. Полезности от него нет а вреда больше.
[сам юрл](https://my.mail.ru/mail/mak_rakov/video/_myvideo/7984.html?time=0&from=videoplayer)

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | ?
Browser:                               | Google Chrome 66
AdGuard version:                       | браузерное расширение 2.9
Filters enabled:                       | английский,русский, счётчиков и  аналитики,виджетов соц.сетей,раздражителей
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Заблокированные запросы ничего не потребляют. У меня никаких различий в работе после разблокировки нет.

**Comment by Big-U-Boss** [comment]
Извини меня кончно, но сходу 500 запросов и капец приложению и озу под 2гб в момент. К тому же я смотрел в журнале фильтрации и там чётко показывалось множество фильтров по этой маске.

**Comment by Alex-302** [comment]
Ну блокируются и пусть. У меня потребление памяти не растёт от этого
![image](https://user-images.githubusercontent.com/8361299/39914540-f7b63458-550d-11e8-9f77-a32fec463b8f.png)

**Comment by Alex-302** [comment]
без блокировки их не меньше
http://ipic.su/img/img7/fs/kiss_163kb.1526027203.jpg

**Comment by Big-U-Boss** [comment]
У тебя 16 Гб ,насколько я вижу. Разницы особо и не заметишь,если 2 Гб отнимется, а вот у кого поменьше и когда 2 Гб остается всего, то другая песня.  И чтоб вкладка хрома отнтмала по гигабайту или 2-немыслимо. Я маску разблокировал и потребление превышает не  более 400 Мб,как и у других. Я не знаю, может это приложение не потребляет памяти,но расширение не справляется  с этим. И по поводу снимков. Во втором ты утверждаешь,что  ситуация не меняется ибо запросов на картинку меньше! Но не забывай,что расширение считает эти запросы как заблокированные от того и не фиксирует их в счётчике и браузер не пытается выдать туеву хучу запросов на повторное получение ответа чем не перегружает себя же . Аналогичная ситуация наблюдалась и в mozilla firefox с тогдашним адблоком и сколько я не обращался,меня так и тоже не стали слушать и я поступил аналогичным образом.

**Comment by Alex-302** [comment]
Сколько у тебя вкладка занимает без прокрутки страницы? Нажми Shift+Ё, там можно посмотреть.
У меня после старта видео за несколько секунд до 400 МБ разрастается, потом отпускает немного. Это сама вкладка.

**Comment by Big-U-Boss** [comment]
до 350Мб доходит с маской включенной, потом начинает набигать gif заблокированные при прокрутке и под конец страницы 2 ГБ занимает вкладка.  С выключенной  в начале начинает от 200Мб и под конец 450Мб.

**Comment by Alex-302** [comment]
@zebrum проверь у себя.

**Comment by zebrum** [comment]
у меня не повторяется на виртуалке.
