### ISSUE TITLE
Auto-closing bug with French filter

### ISSUE THREAD

**Issue by NotaInutilis** [AdguardTeam/AdguardFilters#158749]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

n/a

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://gg.deals/fr/redirect/20ec256ecbda4c78e70fc0274d6149eacdf5ab9b/?utm_source=games%2Fsingle

### What filters do you have enabled?

AdGuard French filter

### Add your comment and screenshots

I have an issue with uBlock Origin while using Adguard's French filter list: when I click a link shat should open a new window/tab, it auto-closes immediately. This happens with left and right click (explicitly ask to open in a new window/tab.

On the `gg.deals` website, links to `fanatical.com` use a tracking service that triggers a `$popup` rule for the `jdoqocy.com` domain and auto-closes.

![259545604-065f753d-63a0-44ea-92ac-28b83f86f2bf](https://github.com/AdguardTeam/AdguardFilters/assets/9675966/af78b476-6f91-4ce6-a021-0de34247d6f2)

Examples on the `https://gg.deals/game/yakuza-like-a-dragon/` page.

![Capture d’écran 2023-08-10 020822](https://github.com/AdguardTeam/AdguardFilters/assets/9675966/90bccd3c-0ffb-41df-aa5a-d2bf89d9e79b)

Clicking on the first link `https://gg.deals/fr/redirect/20ec256ecbda4c78e70fc0274d6149eacdf5ab9b/?utm_source=games%2Fsingle` redirects to `https://www.jdoqocy.com/click-7770860-13212017?url=https%3A%2F%2Fwww.fanatical.com%2Fgame%2Fyakuza-like-a-dragon` and auto-closes.
Even right-clicking on the [https://gg.deals/fr/redirect/20ec256ecbda4c78e70fc0274d6149eacdf5ab9b/?utm_source=games%2Fsingle](https://gg.deals/fr/redirect/20ec256ecbda4c78e70fc0274d6149eacdf5ab9b/?utm_source=games%2Fsingle) from here, on GitHub, triggers the filter and the auto-close.

Issue is resolved by deactivating the French Adguard list in uBlock Origin. Tested on latest Firefox and Chrome, clean profile, Windows 11 64bits.

### Privacy

- [X] I agree to follow this condition

**Comment by NotaInutilis** [comment]
Thanks!
Is that auto-closing an expected behavior? From my understanding of what a popup is, I believed uBO wrongly interpreted the popup filter, as such a link is not a popup.

**Comment by AdamWr** [comment]
As far as I understand, it's a correct behaviour, `$popup` modifier closes new tab/window with specified address.
https://adguard.com/kb/general/ad-filtering/create-own-filters/#popup-modifier

**Comment by NotaInutilis** [comment]
Aaaaah!
Thanks so much for explaining!
So it treats the whole domain as a popup to be auto-closed instead of only blocking popup windows from the domain as I believed.
I was super confused when I reported that on the uBO issues and it got rejected.
