### ISSUE TITLE
www.amc.com - videos won't play

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1587]
the [link](http://www.amc.com/shows/the-walking-dead/video-extras/season-06/episode-09/the-first-4-minutes-of-the-mid-season-premiere-the-walking-dead-season-6)

![image](https://cloud.githubusercontent.com/assets/15856304/13139197/0208e2bc-d634-11e5-9df9-d5789d3a9771.png)

TMC-555-75691

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Could you please check it on you side without adguard?

**Comment by evgeniy-ADG** [comment]
@Serzh-SUP we need your iPhone : )
