### ISSUE TITLE
larousse.fr

### ISSUE THREAD

**Issue by leonecorn** [AdguardTeam/AdguardFilters#158705]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

AdGuard Browser Extension Firefox 1.51.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

www.larousse.fr

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, EasyList Italy, Liste AR

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

1.  #
2. I noticed one big problem after updating the filters. That annoying pay or consent banner was gone, but the problem was that most of the items on the site, with the exception of the few above, didn't respond when I clicked on them.
Current clickable items:
LANGUE FRANÇAISE
DICTIONNAIRES BILINGUES
TRADUCTEUR
CONJUGATEUR
ENCYCLOPÉDIE
CUISINE
FORUM
JEUX
LIVRES
Currently unclickable items: everything except the above.
e.g) Flag and language items in the centre of the website

Also, on the language-specific dictionary site, you can't enter text in an empty text box.
Also when I click the button nothing happens.

e.g) https://www.larousse.fr/dictionnaires/italien-francais
https://www.larousse.fr/dictionnaires/francais-arabe

3. Screenshots
<details><[summary]>Screenshot 1:</summary>
https://imgur.com/VXvlbeT
https://imgur.com/SYEKKYv

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
I think inccorect are blocked cookies policy or `gtm.js`.

If someting block `gtm.js` then needed is unlock:

```adb
@@||googletagmanager.com/gtm.js$script,domain=larousse.fr
```

later accept manually pop-up by OneTrust / Optanon by "accept all".

---

On page I see soft paywall with option "accept ads" (based on OneTrust mechanism):

`@@||assets.poool.fr^$document,domain=assets.poool.fr`

![image](https://github.com/AdguardTeam/AdguardFilters/assets/35370833/259caea7-309d-42c6-9b38-c9321f2ec44e)

**Comment by Alex-302** [comment]
Can't reproduce - all buttons work.
@Sergey-Lyapin please take a look.

**Comment by krystian3w** [comment]
Based on messy filed form he didn't activate AdGuard Tracking Protection in uBo 1.51.0: https://github.com/AdguardTeam/AdguardFilters/commit/e9e7d5294f2f06d7bd3d57e08109b31f54494b0c#diff-48edccb98fb0d3e69129f311e1526ec011891e603ad60785202adc5b2bbb105c

Nobody copied similar fix to EasyPrivacy or unbreak.txt.

**Comment by leonecorn** [comment]
@krystian3w @
Thanks.
I added it to my filters.
I initially thought it was working completely successfully, but since then, after I clicked on some items on the webpage, the webpage is always blurred. However, when I click on them, they are responding successfully. 

originally, When a user visits the site while using Adguard, You will receive a message like this:
Vous avez refusé le dépôt de cookies sur larousse.fr - This means that you have declined to accept cookies.
When I thought of "larousse.fr###poool-widget", this only blocks the message, but it doesn't seem to block other elements (blur effect).
It looks like you need to create a new filter rule using a combination of an existing filter that was recently modified and "larousse.fr###poool-widget".

**Comment by Alex-302** [comment]
@leonecorn Added `larousse.fr###poool-widget`. Is it enough?
In AdGuards this issue is resolved by click-action scriptlet. uBO does not support it, but setting cookies is may be a short-living solution.

**Comment by leonecorn** [comment]
I've double-checked my browser settings, tried it again, and it's working fine. I have both uBO and adguard installed on my firefox, and the filters from adguard are also available in uBo, so I think there was some confusion.
