### ISSUE TITLE
dizimini.com

### ISSUE THREAD

**Issue by xqtp** [AdguardTeam/AdguardFilters#158734]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.51

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://dizimini.com/dizi/rick-and-morty/sezon-5/bolum-9

### What filters do you have enabled?

AdGuard Turkish filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, EasyList, EasyPrivacy

### Add your comment and screenshots

`##.rek-0`

<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/103899764/c592643e-3a06-442b-b166-df8f165dd7c8)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Not reproduced it on my end. Try to update the filters, clear browser data, restart it and open the site.
