### ISSUE TITLE
ojrq.net

### ISSUE THREAD

**Issue by NotaInutilis** [AdguardTeam/AdguardFilters#158757]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

n/a

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://gg.deals/fr/redirect/eadf3c27ab710de8e9bb6c3719557df4243f2f87/?utm_source=games%2Fsingle

### What filters do you have enabled?

AdGuard French filter

### Add your comment and screenshots

Same as https://github.com/AdguardTeam/AdguardFilters/issues/158749

Links from `gg.deals` to `greenmangaming.com` are redirected via `ojrq.net` which triggers the `popup` filter on the French Adguard list and closes the window.
Example: the 2 top links on this page https://gg.deals/game/red-dead-redemption-ii/

### Privacy

- [X] I agree to follow this condition

**Comment by NotaInutilis** [comment]
Hi, is that the screenshot you need?

![Capture d’écran 2023-08-10 150515](https://github.com/AdguardTeam/AdguardFilters/assets/9675966/2726046d-174b-4335-befe-084123f0234c)
![Capture d’écran 2023-08-10 150547](https://github.com/AdguardTeam/AdguardFilters/assets/9675966/415c675c-c585-4f5f-9058-6d0167bddd51)

Yep, adding `||ojrq.net^$popup,third-party,badfilter` to my filter list fixes the issue.

**Comment by Alex-302** [comment]
Ok, fixed.
