### ISSUE TITLE
Block 3utilities.com

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#158943]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.151

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

pois-net.3utilities.com

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

`3utilities.com` has long been used for phishing with revolving subdomain. `pois-net.3utilities.com` will redirect to legit site if your UA is not mobile (my concern is rather on whether the domain would be alive when you look at this).

ref: `https://twitter.com/harugasumi/status/1690339284635762688`

### Privacy

- [X] I agree to follow this condition

**Comment by AleksandrKalininAdGuard** [comment]
Thank you for the report. Those domains were added to our block list.
