### ISSUE TITLE
globo.com

### ISSUE THREAD

**Issue by igordevezas** [AdguardTeam/AdguardFilters#159088]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.11.0.1293 beta

### What type of problem have you encountered?

Missed ads or ad leftovers, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.globo.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, Fanboy's Annoyances, Fanboy's Enhanced Tracking List, Legitimate URL Shortener

### Add your comment and screenshots

1. <comment> Importing settings from my personal laptop to my work laptop is not working. The ticket #781518 was raised. It seems as a bad communication between the app and the Safari assistant. On example 1, we see that the add is blocked, but my user role using the "Element blocking" > globo.com##section.ad-container to block the grey panel is not being blocked. On the second screenshot, not even the ads are being blocked inside Google. Both cases are not happening on Edge using the web browser extension (same laptop).

2. Screenshots
<details><summary>Screenshot 1:</summary>
<img width="1508" alt="Screenshot 2023-08-14 at 11 32 08" src="https://github.com/AdguardTeam/AdguardFilters/assets/1262003/514bd82f-0d4e-4560-a4af-7edad6079f90">

</details>

<details><summary>Screenshot 2:</summary>

<img width="1508" alt="Screenshot 2023-08-14 at 11 32 16" src="https://github.com/AdguardTeam/AdguardFilters/assets/1262003/d7717951-5d57-428b-814b-6ad604075c22">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. Fixed in Spanish filter.
