### ISSUE TITLE
c.webengage.com blocked

### ISSUE THREAD

**Issue by SarthakWebEngage** [AdguardTeam/AdguardFilters#159294]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS, AdGuard for Android, AdGuard for iOS

### AdGuard version

dns.adguard-dns.com

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

Android/iOS app

### What filters do you have enabled?

AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>
Blocked communication.
2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="877" alt="Screenshot 2023-08-16 at 9 25 17 PM" src="https://github.com/AdguardTeam/AdguardFilters/assets/85634229/fdc83c89-f266-4695-bc46-276f1e30e17e">
</details>
I'm unable to communicate with my servers because DNS is blocking domain webengage.com and its subdomains, like 'c.webengage.com'; please unblock the domain so that apps can work properly with engagement.
<details><summary>Screenshot N:</summary>

<img width="877" alt="Screenshot 2023-08-16 at 9 25 17 PM" src="https://github.com/AdguardTeam/AdguardFilters/assets/85634229/fdc83c89-f266-4695-bc46-276f1e30e17e">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. webengage.com is not blocked anymore. But c.webengage.com is blcoked as analytics. 
What exactly is broken?
