### ISSUE TITLE
zeenite.com doesn't load

### ISSUE THREAD

**Issue by gemoshi07** [AdguardTeam/AdguardFilters#159287]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Ublock Origin with AdGuard Ads filter

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://zeenite.com/

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

On the specified website, the images and videos doesn't load. I am using latest Ublock Origin with AdGuard- Ads filter enabled. 

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
Not reproduced with Ublock and AdGuard.

2 ad leftovers was fixed.

**Comment by gemoshi07** [comment]
@Sergey-Lyapin Hello, with this filter disabled:
![image](https://github.com/AdguardTeam/AdguardFilters/assets/86512304/1914ac79-4ce7-440c-891b-fe3d27679bbe)

I get this:
![image](https://github.com/AdguardTeam/AdguardFilters/assets/86512304/dc95e43e-2fbe-4f7b-be7f-093ff23b7c83)

And with the filter enabled, I get this:
![image](https://github.com/AdguardTeam/AdguardFilters/assets/86512304/3a8fa750-37a3-46a0-86f0-f1cd63fc42d6)

**Comment by Sergey-Lyapin** [comment]
I was not able to reproduce this issue with AdGuard and Ublock.
@AdguardTeam/filters-maintainers please take a look

**Comment by Alex-302** [comment]
Same. You can reproduce with one filter only, and find which rule breaks the site using the filtering log.

**Comment by gemoshi07** [comment]
@Alex-302 Hello, from the filter log:
![image](https://github.com/AdguardTeam/AdguardFilters/assets/86512304/5997359b-b594-417c-bc30-ca2dc32f4c58)

This `​https://cdn86738949.ahacdn.me/` was blocked and after allowing it, the page loads.
Here is the filter created :
`@@||cdn86738949.ahacdn.me^$script,domain=zeenite.com`

**Comment by Alex-302** [comment]
@gemoshi07 We do not block this domain. I think it is caused by uBO's CNAME filtering.

**Comment by stephenhawk8054** [comment]
Hmmm... That filter looks weird `/^?!.*(sharecast.ws`. I don't see it in any uBO's default lists.

**Comment by Alex-302** [comment]
@stephenhawk8054 This is in AdGuard Base filter. Maybe user has `cnameUncloakProxied` enabled. I check without uncloacking.

**Comment by stephenhawk8054** [comment]
Ah ok, I can see it now in Firefox since uBO uncloaks CNAME by default. So would the exception rule for that domain be in AG Base?

**Comment by Alex-302** [comment]
I am not sure where exclusion must be added. I don't think CNAME filtering should apply to rules like this (non domain type), as it's not designed for DNS filtering.

@gemoshi07 Please show details of request, blocked by that rule.
