### ISSUE TITLE
Ring App on Android logs out

### ISSUE THREAD

**Issue by bthomas24** [AdguardTeam/AdguardFilters#159350]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.1.101

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

www.ring.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

1. The Ring app continues to log me off. I searched ring KBs and found that AdGuard is the issue. I disabled AdBlock for ring and that did not fix the issue. I disabled AdGuard and that fixed the issue. I contacted Ring and they said that the issue is with AdGuard

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Not reproduced it on my end. Which filter or stealth mode option causes it?

**Comment by bthomas24** [comment]
These are all I have. Here is the KB I was referring to.

https://support.ring.com/hc/en-us/articles/360029428911-AdGuard-Causing-the-Ring-App-to-Log-Out

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zloyden** [comment]
Could you do the following?
1. Disable filters, stealth mode
2. Leave the protection
3. Clear Ring app cache, restart it and see how it goes.

If that does not help, also disable the protection for Ring app, leaving global one enabled.

**Comment by bthomas24** [comment]
Could I have instructions on how to do rack step? I only ask because I think I have done that, but what to be sure. I know I've definitely done 3 before and have not seen a change. I'm now wondering if I did 1 and 2 correctly.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zloyden** [comment]
I'm closing the task for now. Feel free to tell me what you will get when you check out the app.

**Comment by bthomas24** [comment]
Exactly what I expected. I was logged out of Ring again.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zloyden** [comment]
Did you check it without the filters as I explained above?

**Comment by bthomas24** [comment]
Yes, the filters are turned off. I shared a screenshot of it. If I did it wrong, then correct me.

________________________________
Benjamin Thomas
bthomas24.blogspot.com<http://bthomas24.blogspot.com>
________________________________

**Comment by zloyden** [comment]
You can send the screenshot if you only log in via github.

**Comment by zloyden** [comment]
@bthomas24 the issue has been moved here https://github.com/AdguardTeam/AdguardForAndroid/issues/4940. Thanks for checking this out.
