### ISSUE TITLE
[Stealth Mode] 'block third-party cookies' breaks authorization through social networks

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1593]
^^

Screenshots and the detailed description are here: ITR-608-39763

При переходе по ссылке с поиска гугл ( к примеру, в соц сети), совершается переход, но без вход в саму соц сеть (видны поля лог/пароль)
http://prntscr.com/a4t9km
http://prntscr.com/a4ta0c

При отключении "Блокировать сторонние куки", и переходе на ту же страницу из соц сети, осуществляется нормальный переход с аутентификацией.
http://prntscr.com/a4tbxp

**Comment by Alex-302** [comment]
нужны примеры урлов

**Comment by evgeniy-ADG** [comment]
@Alex-302 
1.Ищещ что-то, что точно есть в ВК, "Иван Иванов", например
2. Кликаешь на результат пои ска
3. Открывается сайт ВК, в котором ты не залогинен: http://prntscr.com/a9zuqg
4. Если отключить блокировку куков, то в результате открывается сайт в ВК, в котором ты залогинен

**Comment by evgeniy-ADG** [comment]
> Проблема такая, когда я захожу на сайт, любой на котором у меня уже произведена авторизация(ютуб, кинопоиск например) из яндекса например или с ссылки, то мне предлагается заново войти в аккаунт, это дико изматывает, а вот если выключить защиту адгварда то я уже в аккаунте сижу (к примеру с функцией отключения защиты на 30 секунд, как только по истечению 30 секунд обновляю страницу и защита включается меня опять выкидывает с акка!) Что делать?

**Comment by Alex-302** [comment]
Открыл баг по этой проблеме.

**Comment by Alex-302** [comment]
Временно можно давать подобные исключения:
@@||youtube.com/?gl=$domain=google.ru
youtube.com - куда переходишь, google.ru - откуда.
