### ISSUE TITLE
itemci.com

### ISSUE THREAD

**Issue by xqtp** [AdguardTeam/AdguardFilters#159460]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.51

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://itemci.com/

### What filters do you have enabled?

AdGuard Turkish filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Widgets filter, EasyList, EasyPrivacy

### Add your comment and screenshots

```
! Screenshot 1
itemci.com##.mpy__container-banner
itemci.com##.bg_content_right
itemci.com##.bg_content_left
itemci.com##.mpy__banners-small_container
itemci.com##.banner-section

! Screenshot 2
itemci.com##.mpy__marketplace-banner-container

! Screenshot 3
itemci.com##a[href^="https://www.beyler2.com"]

! Screenshot 4
itemci.com##.pvpAdvertRow

```

**1-**

`https://itemci.com/`

<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/103899764/00172280-1cf3-4ca2-aac2-f78a8bf9a651)

</details>

<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/103899764/206f0933-5e8f-401e-925a-f30eeca3f8db)

</details>

</details>
<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/103899764/3e170f7c-3f14-41d7-a8f2-ed2adf951734)

</details>

---

**2-**

`https://itemci.com/categories`
<details>
 <summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/103899764/39e33020-26ca-4324-9601-cfae65f411ab)

</details>

---

**3-**

`https://itemci.com/product/cs-go-item/survival-knife-night-stripe-64d13eb31cc12`
<details>
 <summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/103899764/fdb144bd-aa7a-4f10-9d5c-8ca27aa0d908)

</details>

---

**4-**

`https://itemci.com/metin2-pvp-servers`
<details>
 <summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/103899764/4772746d-8426-4d67-aae3-a0565f6701f8)

</details>

---

**ISSUE 2 — Incorrect blocking**

`https://itemci.com/product/steam-hesap/steam-10000-puan-hemen-teslim-edilir-64e510a2b8918`

Product descriptions are missing

<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/103899764/a052b3cc-8782-460e-9fb1-04e4d0b2f361)
![image](https://github.com/AdguardTeam/AdguardFilters/assets/103899764/21643fa8-1103-4cba-ad3b-d892978342b8)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Please check for filters update, ads have been blocked on this site
