### ISSUE TITLE
rtvonline.com

### ISSUE THREAD

**Issue by Bhooty** [AdguardTeam/AdguardFilters#159645]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.5.0

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.rtvonline.com/bangladesh/236473/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

Ads not blocked

[IMG_7537](https://github.com/AdguardTeam/AdguardFilters/assets/46019727/35fc8b24-56d9-4df8-8511-4a2e12ed66cc)
[IMG_7538](https://github.com/AdguardTeam/AdguardFilters/assets/46019727/f32dd579-bf66-4267-9138-6a980aa2b25c)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Don't remove details tag in screenshot section.

**Comment by Bhooty** [comment]
> Don't remove details tag in screenshot section.

Ok sir

**Comment by Bhooty** [comment]
@Alex-302 sir there are still two ads

i have marked in res for you to understand 

![IMG_7559](https://github.com/AdguardTeam/AdguardFilters/assets/46019727/7318eb8a-5f23-432c-ad05-553b91f5b082)
![IMG_7560](https://github.com/AdguardTeam/AdguardFilters/assets/46019727/39bf31fc-1a53-4ac6-b5dd-57b26c08b501)
