### ISSUE TITLE
reddit.com

### ISSUE THREAD

**Issue by GigabitEthernet** [AdguardTeam/AdguardFilters#15960]
Comments on reddit.com don't load.

Using English filter, Safari filter and "Use optimized filters" option checked. Safari 11.1, macOS 10.13.4.

Disabling English filter resolves the issue so the issue is in this filter set.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/15934

**Comment by Alex-302** [comment]
Please enable English filter only, open console and reproduce the issue.
After that enter to the search string `blocker` and make screenshot.

**Comment by GigabitEthernet** [comment]
Thanks for the quick reply.

<img width="1680" alt="screen shot 2018-05-10 at 21 33 02" src="https://user-images.githubusercontent.com/4457688/39892814-c0d80a5c-5499-11e8-8847-e98cf6a98309.png">

**Comment by Alex-302** [comment]
no, I mean this
![image](https://user-images.githubusercontent.com/8361299/39936912-b85f5f52-5556-11e8-9da7-b9048d9e67ce.png)

**Comment by GigabitEthernet** [comment]
My apologies.

<img width="1680" alt="screen shot 2018-05-12 at 11 08 31" src="https://user-images.githubusercontent.com/4457688/39956263-d86cdf1c-55d4-11e8-851f-4c6f667d9318.png">

**Comment by Alex-302** [comment]
Thanks.
I don't see suspicious scripts.
Please try to add `@@.js$domain=reddit.com`
Remove it after checking.

**Comment by GigabitEthernet** [comment]
The issue seems to have vanished 😕

**Comment by Alex-302** [comment]
@GigabitEthernet without the rule?
