### ISSUE TITLE
megane.com.pl

### ISSUE THREAD

**Issue by OlgaPetukhova** [AdguardTeam/AdguardFilters#159917]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.11.0.1292 release

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://megane.com.pl/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Polish Anti Adblock Filters

### Add your comment and screenshots

When we open the website, a huge pop-up about AdGuard detection appears.

https://uploads.adguard.org/up34_fwkel.png

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.

**Comment by zloyden** [comment]
@MajkiIT could you also fix this in the `Polish Anti Adblock Filters`?
