### ISSUE TITLE
Block almostmy.com

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#160075]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.57

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

vhresa.almostmy[.]com (Mobile UA required)

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

I have observed almostmy[.]com having been used for phishing for 2 months with changing subdomain. The latest report from a phishing hunter: `https://twitter.com/AP_Zenmashi/status/1695289979117957536`.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![almostmy](https://github.com/AdguardTeam/AdguardFilters/assets/58900598/931e24db-4fc0-4fc2-84d0-f80acbb54620)

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Added it to our base.
