### ISSUE TITLE
Tokopedia.link

### ISSUE THREAD

**Issue by TommyKing** [AdguardTeam/AdguardFilters#160004]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

V.4.1

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://tokopedia.link/tlmLRZgUsCb

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, ABPindo

### Add your comment and screenshots

1. Redirection failed. Always to app main page. The problem fixed by disabling adguard tracking filter

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
@TommyKing what exactly is wrong? I opened the link above and got redirected to `Timbuk2 Official Store` in the app.
Please write steps to reproduce in detail.

**Comment by TommyKing** [comment]
Exactly that
I have the video which show tracking filter made the redirection not working. Are you sure your tracking filter is on?

https://streamable.com/b7l6gj

Please try to see the video

**Comment by zloyden** [comment]
I see. but I always have this as it should be like the last part of the video, so I can't reproduced it on my end.
Please do the following:
1. Leave only AdGuard Tracking Protection and update it
2. Clear the app cache and stop it
3. Reproduce the issue like you did on the video

If you still get it, please do a screenshot of the blocked requests in recent activity (fourth column), then send it here.
@AdguardTeam/filters-maintainers please also take a look at this.

**Comment by TommyKing** [comment]
Still got it after leaving only tracking and clear cache and stop process

![Screenshot_20230825_173543_AdGuard](https://github.com/AdguardTeam/AdguardFilters/assets/6888937/2b64c744-8770-494f-8050-a65d9d128a74)


Here is what i got

**Comment by zloyden** [comment]
Hm, I also have it, but the app works fine. Could you add this rule to User rules (second column - Ad blocking - User rules)?
```adblock
@@||api2.branch.io^
```

**Comment by TommyKing** [comment]
With this now it works

**Comment by zloyden** [comment]
Ok, I've added the rule. The update in filters should be available in 2-3 hours. Until that time, save the rule, after updating the filters you can remove it from the User rules.
