### ISSUE TITLE
http://inter-reklama.biz/

### ISSUE THREAD

**Issue by pixkk** [AdguardTeam/AdguardFilters#160034]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.1.57

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

http://inter-reklama.biz/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter

### Add your comment and screenshots

<details><summary>Screenshot 1 (enabled Adguard):</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/30828435/fb28365e-b63b-4b2f-a9b2-78c3a944729a)

</details>

<details><summary>Screenshot 2 (disabled Adguard):</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/30828435/4cf680ac-25f0-4e4a-92fa-4b303bb48019)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Наши фильтры не ломают этот сайт. Проверьте, какие правила отображаются в журнале фильтрации.
