### ISSUE TITLE
dexerto.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#160171]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.151

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.dexerto.com/tech/linus-tech-tips-releases-first-video-following-content-hiatus-2266453/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Anti-Facebook List

### Add your comment and screenshots

Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/29574622/51673650-8d0b-4e76-a579-1ef899c4fbf5)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Seems to be fixed in https://github.com/easylist/easylist/commit/bf10232966192f394041bd2b837a71282f433518#diff-d95e1ad0368a5fb3bacb89fc7f209b9fa33a9974d9d2cf4b9a98903b7aa356a2R3649
