### ISSUE TITLE
[Android] Animania

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#1601]
http://mobi24.net/apks/Animania.apk - download link.

Ads in the app. Screenshots and video recording are available in the ticket:
LIU-555-47400

**Comment by Alex-302** [comment]
@vbagirov 
it is clean on my end. He should try to disable third-party filters and check again. Or make a log of http requests with time of starting of ads,

**Comment by oktaysar16** [comment]
Hi Alex, I disabled all filters except for mobile ads, spyware and English filters. But it's still getting ads. What else can I do?

**Comment by Alex-302** [comment]
Please make HTTP log(in settings), turn off Adguard, close the app via Android settings. Then start Adguard and your app, and write to support. I need ticket ID and time of displaying ads.

**Comment by oktaysar16** [comment]
Hi alex, here is the ticket ID:#UED-996-96148

**Comment by Alex-302** [comment]
When you saw ads? The log is too big.

**Comment by Alex-302** [comment]
check this rule
||yumenetworks.com^$empty

**Comment by oktaysar16** [comment]
I saw ad around 7:40pm. I tried the rule and it's still not working.

**Comment by Alex-302** [comment]
Could you please make a new log with this rule?

**Comment by oktaysar16** [comment]
Sure. Give me a second

**Comment by oktaysar16** [comment]
Ticket ID:#TVS-661-13949

The ad shows up at 8:52pm

**Comment by Alex-302** [comment]
thanks, i will look it

**Comment by Alex-302** [comment]
please make a screenshot. I don't see suspicious requests in a log.

**Comment by Alex-302** [comment]
Ads loaded from
https://androidads23.adcolony.com/configure
But rule
```
||adcolony.com^$empty
```
doesn't work.

**Comment by Alex-302** [comment]
@oktaysar16 
please try alpha version(don't turn on HTTPS filtering)
https://github.com/AdguardTeam/AdguardForAndroid/releases

**Comment by oktaysar16** [comment]
Hi Alex,
The alpha version is still allowing the ads in the app.
Do you want me to screenshot the ad within the app?

**Comment by Alex-302** [comment]
Did you install certificate, and enable HTTPS filtering in settings?

**Comment by oktaysar16** [comment]
I just installed the certificate and enabled HTTPS filtering but still seeing ads. Here is the ticket no:#DKN-581-60332
I show ads at 11:26pm

**Comment by Alex-302** [comment]
Please check this rule:
||d1e5xacotudrwg.cloudfront.net^$empty
if not helps, add
||s3.amazonaws.com^$empty

**Comment by oktaysar16** [comment]
Hi Alex, I tried them but still receiving ads. Please help me remove these ads ASAP otherwise no point of me having adgaurd which I paid $35 for it.

**Comment by Alex-302** [comment]
@oktaysar16 
they must be blocked.Do you have active filtering of the apps?
And where do you live? Maybe ads are geo-targeted.

Please clear cache of Animania, and make additional HTTP log and write the time when video ad is shown.

**Comment by oktaysar16** [comment]
Sorry I don't know what you mean by active filtering of the apps. 
I live in Sydney, NSW, Australia.

**Comment by oktaysar16** [comment]
OK I will make another log

**Comment by oktaysar16** [comment]
Here is the log: http://s000.tinyupload.com/index.php?file_id=37852868122179090196

I had to upload if myself because I couldn't send a feedback from adguard.

**Comment by Alex-302** [comment]
Hi
Checked your log, and found only one suspicious domain:
```
||d60y8cj1tje2a.cloudfront.net^$empty
```
Please add it to user filter, close Animania and clear cache, then run it again.

**Comment by oktaysar16** [comment]
Hi Alex, sorry for the delayed answer but im still getting ads. I dont get why after the #Animania App updated, the ads started to bypass the filters.

Any thing else i can try?

**Comment by Alex-302** [comment]
heh...
you can only send HTTP logs, I will analyze them
