### ISSUE TITLE
Instacart.com/.ca

### ISSUE THREAD

**Issue by opensorceror** [AdguardTeam/AdguardFilters#160129]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

On https://instacart.com and https://instacart.ca, sponsored ads appear in two main ways: (1) as individual results and (2) as a carousel of sponsored results. These are currently not being blocked by AdGuard.

They are similar to the Promoted results on Twitter, Facebook and other sites.

### Individual sponsored results
![individual_sponsored_results](https://github.com/AdguardTeam/AdguardFilters/assets/10184251/e9657ac1-a062-4c13-9725-54820d0a2f56)

### Carousel of sponsored results
![carousel_of_sponsored_results](https://github.com/AdguardTeam/AdguardFilters/assets/10184251/45cf9f07-e0be-49b0-b4f6-c94f51f458dc)

### Proposed solution

I would like to contribute the filters I have created for https://instacart.*. These have been tested in AdGuard on Firefox desktop (Windows), as well as on Safari iOS. 

These rules hide the individual Sponsored results, as well as the various types of Sponsored carousels on each store's homepage and in search results.

Although these filters work fine, the one optimization that I would love to do but was unable to based on my understanding of the filter syntax and capabilities, is the following. In two of the rules below, I am identifying a div that satisfies two conditions: (1) it must contain a `div[aria-label="item carousel"]` and (2) it must contain a `span:contains(Sponsor)`. (These elements are not direct children of the parent.) The optimal solution here is to identify the _closest_ ancestor that satisfies these conditions; in other words, the closest parent div that contain both elements listed above. The only way I was able to make this work was to explicitly describe the path using `div:has(> div > div > div > span:contains(Sponsor), div[aria-label="item carousel"])`, but this is brittle because the website could easily change the page structure and defeat this rule. I welcome and appreciate any guidance for improvements. Aside from that, these rules do work based on my tests. 

Thanks!

```
instacart.*##div[aria-label="Product"]:has(span:contains(Sponsor)):upward(li)
instacart.*##div:has(> div > div > div > span:contains(Sponsor), div[aria-label="item carousel"])
instacart.*##div:matches-attr("data-testid"="async-item-list")
instacart.*##div[aria-label="item carousel"]:has(span:contains(Sponsor))

! Mobile-specific
instacart.*##div:has(> div > div > div > span:contains(Sponsor), ul[class^="u-noscrollbar "])
```

**Comment by opensorceror** [comment]
Hi @Alex-302 Thank you much! 

I just tested this on instacart.ca with the latest version of AdGuard. While your change does block the individual sponsored results, it does not block the Sponsored carousel:

![image](https://github.com/AdguardTeam/AdguardFilters/assets/10184251/87ae78e4-9cab-49db-b460-004a04ef586a)

Would it be possible to also add in a rule to block this?

**Comment by Alex-302** [comment]
Hi
Please provide url.

**Comment by opensorceror** [comment]
Here is the one I used in my tests: https://www.instacart.ca/store/costco-canada/s?k=chips

(You may have to create an account to view and search through a store.)

Note: The Sponsored carousel does not always show up. You may have to refresh a couple times to make it show.

**Comment by Alex-302** [comment]
Can't reprodcue. Need a screenshot.

**Comment by opensorceror** [comment]
Hi @Alex-302 , please see attached screenshots. 

I created the following rules which work on both desktop and mobile:
```
! Desktop - home page and search results
instacart.*##div:has(> div > div > div > span:contains(Sponsor), div[aria-label="item carousel"])
instacart.*##div[aria-label="item carousel"]:has(span:contains(Sponsor))

! Mobile
instacart.*##div:has(> div > div > div > span:contains(Sponsor), ul[class^="u-noscrollbar "])
```

![featured](https://github.com/AdguardTeam/AdguardFilters/assets/10184251/bf90bbeb-5552-44c6-b1ef-e76339f20da7)
![recommended](https://github.com/AdguardTeam/AdguardFilters/assets/10184251/976911cb-b7a2-454d-a1ce-d52674d5088b)
![html](https://github.com/AdguardTeam/AdguardFilters/assets/10184251/f7660369-20d4-4f4f-af72-919ae2fa5546)
