### ISSUE TITLE
nytimes.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#160208]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.151

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.nytimes.com/2023/08/26/business/economy/us-economy-china.html

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Anti-Facebook List

### Add your comment and screenshots

1. <comment>I also use "Bypass Paywalls Clean filter". But when Adguard Tracking Protection filter is used, the paywall can not be unlocked. Adg tracking is breaking the functionality of Bypass Paywalls Clean filter.
2. It seems this rule `nytimes.com#%#//scriptlet("set-constant", "Navigator.prototype.joinParakeetInterestGroup", "noopFunc")` is the culprit. Creating an unblock/allow rule for this one makes the page show the full article. Please do something to make ADG tracking compatible with Bypass Paywall Clean filter in this case. 

3. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/29574622/fa2ebb11-9bd4-4b3f-bbe4-1ca627c559ed)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by SeriousHoax** [comment]
@AdamWr Hi! The issue still remains on my end. I tried deleting cookies for the website but it's still the same. Can you check?

**Comment by AdamWr** [comment]
Hi,
After updating filters it works correctly on my end.
That's how it looks like with `Bypass Paywalls Clean filter` enabled:
<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/29142494/4d54f843-d23e-4abf-b1bd-64f3e7c1f7c1)

</details>

And with disabled `Bypass Paywalls Clean filter`:
<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/29142494/94304908-b4cb-4a5c-8bd9-bebf00118bd5)

</details>

There were 2 similar rules which when used together caused a problem, but now I cannot reproduce it anymore.

The mentioned rule:
```adblock
nytimes.com#%#//scriptlet("set-constant", "Navigator.prototype.joinParakeetInterestGroup", "noopFunc")
```
is required for this issue - https://github.com/AdguardTeam/AdguardFilters/issues/135303#issuecomment-1356927010, without it website is broken.

If issue still occurs even after updating filters, then I recommend to add exception to user rules:
```adblock
nytimes.com#@%#//scriptlet("set-constant", "Navigator.prototype.joinParakeetInterestGroup", "noopFunc")
```

**Comment by SeriousHoax** [comment]
> Hi, After updating filters it works correctly on my end. That's how it looks like with `Bypass Paywalls Clean filter` enabled:
> 
> Screenshot
> And with disabled `Bypass Paywalls Clean filter`:
> 
> Screenshot
> There were 2 similar rules which when used together caused a problem, but now I cannot reproduce it anymore.
> 
> The mentioned rule:
> 
> ```
> nytimes.com#%#//scriptlet("set-constant", "Navigator.prototype.joinParakeetInterestGroup", "noopFunc")
> ```
> 
> is required for this issue - [#135303 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/135303#issuecomment-1356927010), without it website is broken.
> 
> If issue still occurs even after updating filters, then I recommend to add exception to user rules:
> 
> ```
> nytimes.com#@%#//scriptlet("set-constant", "Navigator.prototype.joinParakeetInterestGroup", "noopFunc")
> ```

I see. Can you try one more thing? For example, for me, after removing nytimes cookie from my browser if I visit the article reported in this issue above then the first time the full article is loaded most of the time. But then if I reload the page or go to nytimes home page and click on other articles on the home page then articles becomes locked again and "Subscribe for $0.25/Week" button appears beside the login button on top right. 
Apart from your suggested exception rule, the only other thing that is working for me is this rule `nytimes.com##+js(cookie-remover, /^/)`
But of course, this rule can not be put into Adguard Base filter since it removes cookies every single time. 
If you can not reproduce then I'll just keep using it by putting this in user rules.

**Comment by AdamWr** [comment]
I'm not sure if it's the same issue as described, but if I open article in incognito mode, then sometimes on first visit paywall is not unblocked.
The same happens if I add mentioned exception rule to user rules, or even with whole `AdGuard Tracking Protection filter` disabled, so probably it's not related to this rule.

**Comment by SeriousHoax** [comment]
> I'm not sure if it's the same issue as described, but if I open article in incognito mode, then sometimes on first visit paywall is not unblocked. The same happens if I add mentioned exception rule to user rules, or even with whole `AdGuard Tracking Protection filter` disabled, so probably it's not related to this rule.

Yeah, probably it's not related to the rule from `AdGuard Tracking Protection filter`. I have no issue with it in uBO with Adg tracking enabled. Something else might be causing it. Maybe other Adguard filter maintainers can check?

**Comment by AdamWr** [comment]
Maybe it's related to this issue - https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2459#issuecomment-1697020010
It looks like that sometimes some rules are not applied.

**Comment by SeriousHoax** [comment]
@AdamWr Hi! BTW the issue of not applying BPC filter on nytimes happens on Adguard Desktop for me also. The comments on the issue you linked above seem to discuss ADG extension only. So just in case I'm letting you know to check out such issues on Adguard Desktop also if it wasn't tested.

**Comment by AdamWr** [comment]
Hello,
It works fine on my end with AdGuard for Windows and I cannot reproduce such issue like with AdGuard extension.
So, I think that I need more details how to reproduce it.
By the way, the problem is like with extension - it doesn't work only sometimes, or it doesn't work at all?

**Comment by SeriousHoax** [comment]
> Hello, It works fine on my end with AdGuard for Windows and I cannot reproduce such issue like with AdGuard extension. So, I think that I need more details how to reproduce it. By the way, the problem is like with extension - it doesn't work only sometimes, or it doesn't work at all?

Hi! Regarding this nytimes issue, Adguard for Windows is not applying Bypass Paywall Clean filters on the site at all. 

Check this: 
`https://imgur.com/a/NEm4Fyo`

This custom filter is also not being applied. Is it compatible with ADG Windows? 
`nytimes.com##+js(cookie-remover, /^/)`

**Comment by AdamWr** [comment]
As far as I can see on the video, `Bypass Paywall Clean` filter list is not marked as "trusted", so scriptlets are not applied.
Enabling `Trust this filter` option should fixes it (after enabling it, updating filter lists might be required).
<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/29142494/39758533-be6e-438a-9acb-ebfa57d0ed34)

</details>

>This custom filter is also not being applied. Is it compatible with ADG Windows?
`nytimes.com##+js(cookie-remover, /^/)`

As far as I know, it should be compatible and it works on my end.
How exactly do you check whether it works or not?

**Comment by SeriousHoax** [comment]
> As far as I can see on the video, `Bypass Paywall Clean` filter list is not marked as "trusted", so scriptlets are not applied. Enabling `Trust this filter` option should fixes it (after enabling it, updating filter lists might be required).
> 
> Screenshot
> > This custom filter is also not being applied. Is it compatible with ADG Windows?
> > `nytimes.com##+js(cookie-remover, /^/)`
> 
> As far as I know, it should be compatible and it works on my end. How exactly do you check whether it works or not?

Ah, sorry about that. I didn't know that it has to be Trusted to make it work. Yeah, now it's working fine in ADG Windows. I still don't see BPC clean filters in the log though but it's working for sure.
Regarding the user rule cookie filter I also only checked that in the log. 
If both of these not showing in the log is a bug then you may see what's going on. But if you can't reproduce then you may ignore my comment.

**Comment by AdamWr** [comment]
Cosmetic rules (element hiding, scriptlets and JavaScript rules)  are not displayed in the filtering log in apps, there is opened task about it - https://github.com/AdguardTeam/CoreLibs/issues/180
Additional information - https://github.com/AdguardTeam/CoreLibs/issues/1784#issuecomment-1649284401
