### ISSUE TITLE
usatoday.com

### ISSUE THREAD

**Issue by jameyers4** [AdguardTeam/AdguardFilters#160339]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14 (build 301, CT 2.0.41)

### Environment

```markdown
- OS: Ventura 13.5.1 (22G90)
- Safari version: 16.6 (18615.3.12.11.2)
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

Steps to reproduce:
1. Navigate to usatoday.com
2. if adblocker warning does not display, click to another tab or minimize Safari window and wait several minutes
3.

### Expected Behavior

AdGuard should not trigger adblocker warnings

### Actual Behavior

get adblocker warning page

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
<img width="1454" alt="Screenshot 2023-08-28 at 1 45 24 PM" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/30449337/e3abae04-e99e-4f9d-a449-7d18b0737b22">

**Comment by Alex-302** [comment]
Please enable `AdGuard Tracking Protection filter` or `AdGuard Popups filter`
