### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdguardFilters#160379]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.159

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://twitter.com/elonmusk/status/1696259313990263014

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

Please avoid breaking the scroll bar @piquark6046 😄 

https://github.com/AdguardTeam/AdguardFilters/commit/3104434a26eefc7de4d9c3b5ee6c91bad44c95d1

https://github.com/AdguardTeam/AdguardFilters/blob/24312c3e1a288307eb33a932ec0e322c60418b1f/AnnoyancesFilter/Popups/sections/push-notifications_specific.txt#L74

https://github.com/AdguardTeam/AdguardFilters/blob/24312c3e1a288307eb33a932ec0e322c60418b1f/AnnoyancesFilter/Popups/sections/popups_specific.txt#L5754

About the scroll bar issue:

- https://github.com/AdguardTeam/AdguardFilters/issues/154197#issuecomment-1645465520
- https://github.com/AdguardTeam/AdguardFilters/issues/157044

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.

**Comment by zloyden** [comment]
Hm, didn't add these rules. However, I've removed them.

**Comment by kodiakhub** [comment]
@zloyden again breakage:

`AdGuard Mobile App Banners filter`
```adb
x.com#$#html[style] { overflow: auto !important; position: static !important; }
```
