### ISSUE TITLE
vercel.app

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardFilters#160420]
### AdGuard version

2.11.0.1293 nightly

### Browser version

114.0.5735.198

### OS version

13.4.1 (22F82)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Experimental filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable cache for third-party requests, Hide Referrer from third-parties, Hide your User Agent, Remove X-client-Data header, Protect from DPI

### Support ticket ID

776816

### Issue Details

Steps to reproduce:
1. Go to https://how-to-learn-rakleed.vercel.app/

### Expected Behavior

The site opens correctly.

### Actual Behavior

I get `ERR_SSL_PROTOCOL_ERROR`.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot 2023-07-06 at 04 39 30](https://github.com/AdguardTeam/AdguardForMac/assets/19418601/80adc0a3-1fd1-4783-90db-d724bb5721e1)

</details>

**Comment by Alex-302** [comment]
Cannot reproduce.
Try `@@||how-to-learn-rakleed.vercel.app^$stealth=dpi`
