### ISSUE TITLE
[iOS] free-torrents.org

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1604]
http://login.free-torrents.org/forum/login.php?redirect=/forum/tracker.php
http://prntscr.com/a5lqpk
GES-471-86403

**Comment by Alex-302** [comment]
Вроде чисто. У вас повторяется?

**Comment by Bohdan-SUP** [comment]
http://login.free-torrents.org/forum/login.php?redirect=/forum/tracker.php
http://prntscr.com/ahiuz1

**Comment by evgeniy-ADG** [comment]
http://login.free-torrents.org/forum/login.php?redirect=/forum/tracker.php
http://prntscr.com/b0awiq
Фильтры обновлены.

![image](https://cloud.githubusercontent.com/assets/15856304/15091967/32cfe634-1464-11e6-97a0-e5456d331bb5.png)

**Comment by Alex-302** [comment]
Не повторяется. Главная страница с рекламой?
