### ISSUE TITLE
Bitwarden and AdGuard compatibility error

### ISSUE THREAD

**Issue by saurane** [AdguardTeam/AdguardFilters#160593]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.14

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Desktop

### Where is the problem encountered?

api.bitwarden.eu and api.bitwarden.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Disable cache for third-party requests, Block third-party Authorization header, Block WebRTC, Block Push API, Block Location API, Hide Referrer from third-parties (specify in comment below, if used custom value), Mask your IP address (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

With AdGuard enabled, when you update any record in the Bitwarden password manager, Bitwarden will log out of your account. This happens because of the Privacy Mode in the AdGuard app.

Below is the solution to the error.

User rule: @@||api.bitwarden.*/ciphers/$stealth

api.bitwarden.eu/ciphers/ and api.bitwarden.com/ciphers/

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Need steps to reproduce

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/5c83b88e-026c-4a78-9c98-1946e7f4056a)

**Comment by saurane** [comment]
> Yeniden oluşturmak için adımlar gerekiyor
> 
> ![görüntü](https://user-images.githubusercontent.com/8361299/265023925-5c83b88e-026c-4a78-9c98-1946e7f4056a.png)

I forgot to mention, Bitwarden browser extensions also have this problem.

**Comment by Alex-302** [comment]
So web version and extension are affected?

Could you please test without `Block third-party Authorization header` stealth mode option?

**Comment by saurane** [comment]
> So web version and extension are affected?
> 
> Could you please test without `Block third-party Authorization header` stealth mode option?

Only the browser extension is affected. The problem is caused by the "Block third-party Authorization header" property, I tested it.

**Comment by Alex-302** [comment]
It seems you removed HTTPS exclusion for this domain.
![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/fe84cb32-dfbd-47d0-9f44-eca03a2d953c)

Please check, it it is exists.

**Comment by piquark6046** [comment]
![image](https://github.com/AdguardTeam/AdguardFilters/assets/98787049/b0326138-7b16-4a0d-8ea9-c031aeaaa7c1)

Already related rule exists.

**Comment by saurane** [comment]
> Screemshot
> ![image](https://user-images.githubusercontent.com/98787049/265027903-b0326138-7b16-4a0d-8ea9-c031aeaaa7c1.png)
> 
> Already related rule exists.

api.bitwarden.eu is not available in the filter.

**Comment by Alex-302** [comment]
> api.bitwarden.eu is not available in the filter.

I don't see it on your screenshot.

**Comment by Alex-302** [comment]
I am sure you removed HTTPS exclusion.
bitwarden.com should not be filtered, must look like this in the log
![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/c0387b2c-c749-446d-81cd-90f9b23ef817)

**Comment by saurane** [comment]
> HTTPS hariç tutmayı kaldırdığınızdan eminim. bitwarden.com filtrelenmemeli, günlükte bu şekilde görünmelidir ![görüntü](https://user-images.githubusercontent.com/8361299/265032408-c0387b2c-c749-446d-81cd-90f9b23ef817.png)

![Adsız](https://github.com/AdguardTeam/AdguardFilters/assets/87908352/10c7ae01-b63e-4897-a1c1-d3930a1bdca0)

**Comment by saurane** [comment]
![Adsız](https://github.com/AdguardTeam/AdguardFilters/assets/87908352/de61f338-c4f3-4495-a7b3-014d40a874c3)

**Comment by Alex-302** [comment]
@saurane When a domain is in HTTPS exclusions, you will not see HTTP path in the filtering log.

Please check it in HTTPS exclusions in AdGuard Network settings

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/5b85fe3b-25a2-4151-9fbb-cae85c865895)

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/2efaec40-5b35-4655-b7a9-a2ada2b4f930)

</details>

**Comment by saurane** [comment]
> 

I understand you, but the domain name bitwarden.eu is available for Europe and countries close to Europe. You need to add the bitwarden.eu domain name to the filter list or https exceptions.

**Comment by Alex-302** [comment]
@saurane I mean your problem.
