### ISSUE TITLE
Meross device pairing error (com.meross.meross)

### ISSUE THREAD

**Issue by FauconSpartiate** [AdguardTeam/AdguardFilters#160557]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

V4.1

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

Meross (com.meross.meross)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard French filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, EasyList, Adblock Warning Removal List, NoCoin Filter List, Legitimate URL Shortener

### Add your comment and screenshots

1. Setting up a smart home device with the Meross app fails when Adguard is enabled. Tried with several Meross MSS310 smart plugs.

2. Screenshots
<details><summary>Screenshot 1:</summary>

The setup process stays on this screen for a few minutes before failing.

![Screenshot_2023-09-01-04-11-22-51_56b7547d8e4eb7c7b8ab580c8df8134f.jpg](https://github.com/AdguardTeam/AdguardFilters/assets/49079695/65488670-1f74-4b67-9255-31cc68e7d0f3)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by FauconSpartiate** [comment]
I know it will be complicated to replicate, as a physical device is needed.
If you need any logs or filtering history, please tell me and also how to do it.

**Comment by zloyden** [comment]
I don't have the device, so I need your help. Please do the following:
1. Leave only AdGuard Base, AdGuard Tracking Protection filters
2. Update them
3. Clear and restart mentioned app
4. Reproduce the issue
5. See how it goes and tell me about it here

**Comment by FauconSpartiate** [comment]
@zloyden same behavior with only base filters.

**Comment by FauconSpartiate** [comment]
Can I just send the logs of the app here, or does it contain provate data of my network traffic?

**Comment by Alex-302** [comment]
@FauconSpartiate Please check, what breaks the app
- filters
- DNS filtering
- stealth mode
- HTTPS filtering of this app, if enabled.

**Comment by FauconSpartiate** [comment]
Logs from testing with only 2 filters like asked:
[adguard_logs_4.1.101_0609_125946.zip](https://github.com/AdguardTeam/AdguardFilters/files/12537208/adguard_logs_4.1.101_0609_125946.zip)

Logs from testing many different settings to find the issue
[adguard_logs_4.1.101_0609_141854.zip](https://github.com/AdguardTeam/AdguardFilters/files/12537214/adguard_logs_4.1.101_0609_141854.zip)

**Comment by Alex-302** [comment]
Is device rooted? Which status of HTTPS filtering of **this app**  option?

**Comment by FauconSpartiate** [comment]
No root, no HTTPS filtering in any app

**Comment by Alex-302** [comment]
So if all filters and modules are disabled, but protection enabled, the issue still exists?

**Comment by FauconSpartiate** [comment]
Exactly

**Comment by Alex-302** [comment]
Ok, it seems this is a bug.
Please write here: https://github.com/AdguardTeam/AdguardForAndroid/issues/new?assignees=&labels=Bug&projects=&template=issue_template.yaml

also you can mention this issue (do the same with your second report).
