### ISSUE TITLE
arabickeyboard.io, i2arabic.com, i2clipart.com, i2ocr.com, i2symbol.com, i2type.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#160620]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.51.1rc2

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

arabickeyboard.io, i2arabic.com, i2clipart.com, i2ocr.com, i2symbol.com, i2type.com

### What filters do you have enabled?

AdGuard Cookie Notices filter

### Add your comment and screenshots

1. <comment>
Some leftover cookie notice scripts.
```
||i2clipart.com/js/cookie.min.js
||i2ocr.com/js/cookie.min.js
||i2symbol.com/mob/js/cookie.min.js
||i2type.com/js/cookie.min.js
```

International:
```
||arabickeyboard.io/*/cookie.min.
||i2arabic.com/js/cookie.min.js
```

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
1 site - 1 issue. With screenshot.
