### ISSUE TITLE
makemytrip.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#160851]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.14

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.makemytrip.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Anti-Facebook List

### Add your comment and screenshots

Also check the page on smartphone to see if there are more annoyances like Mobile app banner.
 
Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/29574622/833732b2-f724-4e7e-8482-e604a2b1df2d)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please use reporing tool.

**Comment by SeriousHoax** [comment]
> Please use reporing tool.

Hi! The reason I stopped using the reporting tool is to keep a record of all issues I report by my GitHub account.

**Comment by Alex-302** [comment]
You can add your name to reports)

**Comment by SeriousHoax** [comment]
> You can add your name to reports)

Yeah, I'm aware of that but that does not add the reported issue to my own GitHub on `https://github.com/issues`. 
Does it create problems for Adguard maintainers if I report on GitHub instead of using the tool? Of course, I would consider using the reporting tool again if my generic reporting here makes the process problematic for you.
