### ISSUE TITLE
Ads in Outlook for Windows app

### ISSUE THREAD

**Issue by hlqviet** [AdguardTeam/AdguardFilters#160890]
### Platform

Windows

### Protocol

DNS-over-TLS

### Do you use AdGuard app?

No I don't

### Your configuration

I use AdGuard DNS filter from a different DNS service.

### Issue Details

Steps to reproduce:

1. Install the Outlook for Windows app (https://www.microsoft.com/store/productid/9NRX63209R7B?ocid=pdpshare)
2. Add an email account
3. Go to the Other tab in Inbox

### Expected Behavior

No ads appeared

### Actual Behavior

Two ads appeared above emails

### Screenshots

<details><summary>Screenshot 1:</summary>
![image](https://github.com/AdguardTeam/AdGuardDNS/assets/5486625/55122bcf-9c4c-4e4d-9c42-b57925358bfe)

</details>

### Additional Information

I noticed `outlookads.live.com` in the logs and tried blocking it and the ads didn't appear.

**Comment by piquark6046** [comment]
<details><summary>Screenshot</summary>

![Screenshot from 2023-09-05 19-09-55](https://github.com/AdguardTeam/AdguardFilters/assets/98787049/b10a9a72-5a00-4ea1-a403-ff5c07b6833e)


</details>
