### ISSUE TITLE
iplogger.org [Ad Block Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#16081]
**Site**: https://iplogger.org/logger/tnrhr61vzH57/tab=info/

**Issue**: Please remove the Ad block message on the page.

**Screenshot**: http://prntscr.com/jgy3vo

http://prntscr.com/jecsj0

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.139 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
2nd screenshot different site, please open a new issue for that.
