### ISSUE TITLE
Paywall Filter

### ISSUE THREAD

**Issue by arthurgeron** [AdguardTeam/AdguardFilters#160864]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Paywall filter

### Proposed solution

Add this Paywall filter to list
https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters

**Comment by DandelionSprout** [comment]
As much as I love and adore that list, I've got the impression that the AdGuard Team (of which I'm not a member) are rather scared of being sued by (mostly German) newssites if they include that list.

**Comment by BlazDT** [comment]
Tried German site abendblatt.de and all it seems to do is hiding the pay dialogue and not unlocking the articles. So technically nothing to sue about (at least for that page).
Imho should not be added due to possible legal issues (when blocking some third-party scripts it is possible to view some paid articles on some pages).
@AdguardTeam/filters-maintainers opinions?

**Comment by piquark6046** [comment]
AS following AdGuard policy, any paywall filters lists that want to be added into AdGuard FiltersRegistry will be rejected:
https://github.com/AdguardTeam/FiltersRegistry#what-filters-can-be-added-to-this-repository

**Comment by arthurgeron** [comment]
> AS the following AdGuard policy, any paywall filters lists that want to be added into AdGuard FiltersRegistry will be rejected: https://github.com/AdguardTeam/FiltersRegistry#what-filters-can-be-added-to-this-repository

Then why not let me add my own filters in Adguard DNS/Apps ? It's not like it's a free service.

**Comment by piquark6046** [comment]
You can add your own filters as one of custom filters.

**Comment by arthurgeron** [comment]
> You can add your own filters as one of custom filters.

I can't, not on Adguard DNS.

https://github.com/AdguardTeam/AdguardFilters/assets/3487334/5eb8ef2f-a96a-446d-94e8-c7f7c879a070

**Comment by Alex-302** [comment]
@arthurgeron This filter is useless for DNS filtering. You need ad blocker to use it.
