### ISSUE TITLE
Microsoft Authenticator no notifications (com.azure.authenticator)

### ISSUE THREAD

**Issue by FauconSpartiate** [AdguardTeam/AdguardFilters#160972]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

V4.1

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

Microsoft Authenticator (com.azure.authenticator)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard French filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, EasyList, Adblock Warning Removal List, NoCoin Filter List, Legitimate URL Shortener

### Add your comment and screenshots

1. When AdGuard is enabled, no 2FA notifications from a Microsoft account arrive. Even when the app is open and I refresh to look for login attempts, nothing shows up.

2. Screenshots
No screenshots, app doesn't allow it.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Cna't reproduce with AdGuard filters - I see the request on Android phone when trying to login to MS account.
Is the problem related to enabled filters?

**Comment by Alex-302** [comment]
Please send report from AdGuard.

**Comment by FauconSpartiate** [comment]
@Alex-302 Posted in #160978

**Comment by Alex-302** [comment]
> How can I send a report for an app from AdGuard? The form just redirects me to a normal GitHub issue if I select that it is about an app...

Support => Report incorrect blocking. 

In this case all settings entered automatically.
