### ISSUE TITLE
xtits.com

### ISSUE THREAD

**Issue by gemoshi07** [AdguardTeam/AdguardFilters#160959]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

AdGuard Bse Filter on Ublock Origin

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.xtits.com/

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1. <comment> The website doesn't load properly when I have enabled that filter. 

The first image is with filter enabled and on the  second one is disabled:
`https://imgur.com/a/o7YfsQb` 

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Unfortunately the picture is not available. I didn't notice any problems with loading. Could you please attach a link to the comment or describe the problem in more detail.

**Comment by gemoshi07** [comment]
@jellizaveta Hi, sorry about the link, now should work: `https://imgur.com/a/zNcgiYb`

The problem is, when I open the link above with the AdGuard Base Filter enabled, the images on website doesn't load.
If I disable the filter and refresh the page, the images appears.

**Comment by jellizaveta** [comment]
@gemoshi07 The video previews are loading fine. Please send a screenshot of the filtering log from your blocker.

**Comment by gemoshi07** [comment]
@jellizaveta Hello, here is the screenshot. (Hope it's ok I upload to github)
![image](https://github.com/AdguardTeam/AdguardFilters/assets/86512304/b02ae39f-fea4-4afb-ac4d-39340fc37bf0)

**Comment by jellizaveta** [comment]
Looks like there are no scriptlets for this site in the AdGuard Base filter. Do you have any other filters enabled?

**Comment by gemoshi07** [comment]
@jellizaveta I have the Easylist Ads Filter,EasyPrivacy, Dan Pollock FIlter list and  Peter Lowe list. Maybe one of these has something in conflict with the site?

I thought that if I disable a filter and then the website is working fine, that filter could be the problem.

**Comment by jellizaveta** [comment]
Yeah, probably. Could you please send a screenshot of the filter log only with the filter that is causing the problem

**Comment by jellizaveta** [comment]
Closed due to long response time
