### ISSUE TITLE
Evocreo - shop not working

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#1611]
https://play.google.com/store/apps/details?id=ilmfinity.evocreo.main.android&hl=en

**Comment by Alex-302** [comment]
I've got this error without Adguard
<details> 
![screenshot_2016-02-23-12-37-11](https://cloud.githubusercontent.com/assets/8361299/13247444/a4f14542-da2a-11e5-8256-2e2c7961e0ab.png)
</details>

**Comment by ameshkov** [comment]
I suppose you should switch the currency in your Google Play account

**Comment by Alex-302** [comment]
I did not buy it:)
Which error user got?

**Comment by ameshkov** [comment]
He just says the shop is not working and that's all

**Comment by Alex-302** [comment]
Asked about this error on 4pda
