### ISSUE TITLE
Adguard family DNS incorrectly blocks `telegra.ph`

### ISSUE THREAD

**Issue by thunder-coding** [AdguardTeam/AdguardFilters#161280]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS, Other ad blocker

### AdGuard version

Irrelevent

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Firefox, other (specify in comment below), the problem is with app, not a site

### Which device do you use?

Desktop

### Where is the problem encountered?

https://telegra.ph

### What filters do you have enabled?

AdGuard DNS filter

### About the site

https://telegra.ph is owned by Telegram and can be used to quickly write formatted texts. More details at the announcement here: https://telegram.org/blog/instant-view#telegraph. The site also has an option to report the user-generated content for illegal content, which makes it unreasonable IMO to not block this site. Users of TG might also be affected (not sure though)

### Cloudflare DNS (1.1.1.1) :white_check_mark:
```
$ dig @1.1.1.1 telegra.ph +tls

; <<>> DiG 9.18.18 <<>> @1.1.1.1 telegra.ph +tls
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4874
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; PAD: (409 bytes)
;; QUESTION SECTION:
;telegra.ph.			IN	A

;; ANSWER SECTION:
telegra.ph.		23	IN	A	149.154.164.13

;; Query time: 146 msec
;; SERVER: 1.1.1.1#853(1.1.1.1) (TLS)
;; WHEN: Sat Sep 09 18:58:05 IST 2023
;; MSG SIZE  rcvd: 468

```

### Google DNS (8.8.8.8) :white_check_mark: 
```
$ dig @8.8.8.8 telegra.ph +tls

; <<>> DiG 9.18.18 <<>> @8.8.8.8 telegra.ph +tls
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46691
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;telegra.ph.			IN	A

;; ANSWER SECTION:
telegra.ph.		38	IN	A	149.154.164.13

;; Query time: 176 msec
;; SERVER: 8.8.8.8#853(8.8.8.8) (TLS)
;; WHEN: Sat Sep 09 18:59:13 IST 2023
;; MSG SIZE  rcvd: 55

```

### Adgaurd Default (blocks ads + trackers) :white_check_mark: 
```
$ dig @94.140.14.14 telegra.ph +tls


; <<>> DiG 9.18.18 <<>> @94.140.14.14 telegra.ph +tls
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25941
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 0
;; QUESTION SECTION:
;telegra.ph.			IN	A

;; ANSWER SECTION:
telegra.ph.		141	IN	A	149.154.164.13

;; Query time: 396 msec
;; SERVER: 94.140.14.14#853(94.140.14.14) (TLS)
;; WHEN: Sat Sep 09 19:01:42 IST 2023
;; MSG SIZE  rcvd: 55


```

### Adguard Family ❌

```
$ dig @94.140.14.15 telegra.ph +tls

; <<>> DiG 9.18.18 <<>> @94.140.14.15 telegra.ph +tls
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 758
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 0
;; QUESTION SECTION:
;telegra.ph.			IN	A

;; ANSWER SECTION:
telegra.ph.		3600	IN	A	94.140.14.35

;; Query time: 413 msec
;; SERVER: 94.140.14.15#853(94.140.14.15) (TLS)
;; WHEN: Sat Sep 09 19:08:03 IST 2023
;; MSG SIZE  rcvd: 55


```

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Can't reproduce. It seems already fixed.
![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/d3971212-e356-42c1-8af9-676e934a3609)

**Comment by thunder-coding** [comment]
> Can't reproduce. It seems already fixed.

@Alex-302 I am still able to reproduce this.

**Comment by Alex-302** [comment]
Yep, confirmed now. Will be fixed.
