### ISSUE TITLE
https://claimtrx.com/dashboard

### ISSUE THREAD

**Issue by alvino-prog** [AdguardTeam/AdguardFilters#161388]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

How to block this adblocker detector, thank you

### Proposed solution

to disable adblock detector

**Comment by alvino-prog** [comment]
i mean how to block chpadblock.com adblocker detector

**Comment by Alex-302** [comment]
Please test
`claimtrx.com#%#//scriptlet('abort-on-property-write', 'AdblockRegixFinder')`
or
`claimtrx.com#%#//scriptlet('prevent-eval-if', 'chp_adblock_browser')`

**Comment by alvino-prog** [comment]
its same sir, i just try with that not work, when i try use chpadblock.com still same
