### ISSUE TITLE
[iOS] amazon.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1614]
1. https://www.amazon.com/gp/help/customer/display.html/ref=gw_m_b_he?ie=UTF8&nodeId=508510
   The contact button is not "clickable":
   http://pasteboard.co/1IQJWhjN.png
2. https://www.amazon.com/gp/help/customer/contact-us?ie=UTF8&nodeId=508510&ref_=hp_gt_comp_cu&
   The email, chat and phone buttons:
   http://pasteboard.co/1IQMUxQR.png

XKS-229-63163

**Comment by Alex-302** [comment]
1. I don't see this button.(logged in)

**Comment by Alex-302** [comment]
All buttons are clickable on my end(Safari on Mac with iPad useragent) with user's filter list.
