### ISSUE TITLE
http://www.autobuseslaunion.com white page

### ISSUE THREAD

**Issue by Aokromes** [AdguardTeam/AdguardFilters#1615]
Browser: Opera 37.
OS: Windows 10.
Adguard: 6.0.194.1008

I get white page when i try to visit http://www.autobuseslaunion.com
instead http://www.autobuseslaunion.com/en/index.asp http://www.autobuseslaunion.com/es/index.asp or  www.autobuseslaunion.com/eu works if i visit http://www.autobuseslaunion.com with one browser without adguard filtering works fine.

**Comment by Vincent-Michael** [comment]
it works only with spain browser
https://gist.github.com/Vincent-Michael/c7d24207d9be3328d5e4#file-gistfile1-txt-L25-L32

**Comment by Alex-302** [comment]
@Aokromes 
i need a remote access.
