### ISSUE TITLE
Related to the "I don't care about cookies" filter

### ISSUE THREAD

**Issue by mdziczkowski** [AdguardTeam/AdguardFilters#161791]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

The "I don't care about cookies" filter description doesn't currently explain if enabling it would cause that the "cookies consent" would disapear, automatically agreeing or rejecting the cookies, including the so called "IAD" (or whatever shortcut is used for the "legitimate interest of the administrator").

In many countries, such "legitimate interest of the administrator" is a way to bypass the restrictions of the Data Protection Act and ilegally aquire and process user data

### Proposed solution

Fix the explanation and cause that the filter would automatically reject such agreement's and block such cookies

**Comment by DandelionSprout** [comment]
I *at least* know the maintainer of I Don't Care About Cookies (Daniel Kladnik) has periodically posted disclaimers that his extension and list would auto-accept cookies on some sites, but the disclaimers has apparently not made it over to https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_229_IdontCareAboutCookies/metadata.json yet.

I suppose that link's `"description":` note could very well be updated to add such info.

**Comment by mdziczkowski** [comment]
I had raised it because the so called "Important Adninisteator Interest" (or however it's called) violates the laws (asoecially the mentioned Data Privacy Act) and thereof it should become banned and all privacy directed addons and extentions should block them

**Comment by Alex-302** [comment]
This filter is not enabled by default. User enables it if he want.

**Comment by mdziczkowski** [comment]
Even if the filter is manualy enabled, it would be great if it could block anything related to privacy risk connected with cookied
