### ISSUE TITLE
thetimes.co.uk

### ISSUE THREAD

**Issue by youdontneedtoknow22** [AdguardTeam/AdguardFilters#161765]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBO

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

thetimes.co.uk

### What filters do you have enabled?

AdGuard Base filter, AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment> So depending on what article, I get 2 Annoyances (maybe it depends on if I'm visiting the website for the first time today?)
The first Article is this (https://www.thetimes.co.uk/article/king-mohammed-vi-of-morocco-leads-life-of-luxury-in-france-l5076r6gh)
The second article is anything else random, for example this (https://www.thetimes.co.uk/article/romania-summons-russian-ambassador-over-drone-debris-lqdtjtw00)

3. Screenshots
https://imgur.com/a/6QznQ1I

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
The popup is unfortunately not reproducible on my end. When you reload, does the popup reproduced?

**Comment by youdontneedtoknow22** [comment]
After reloading the second link (the article with romania), the popup didn't show up. But after closing the tab and opening it again, the pop-up still appears.
However, the annoyance still appears on the first link even after reloading

If it's useful, I can paste the filters that remove the annoyances using uBO

**Comment by jellizaveta** [comment]
Unfortunately, we don't block popups like this because it's a paywall:
<details><summary>Screenshot:</summary>

<img width="1792" alt="Screenshot 2023-09-18 at 10 56 26" src="https://github.com/AdguardTeam/AdguardFilters/assets/91964807/9d5bddbf-ee46-4923-938d-024061397b5d">

</details><br/>

**Comment by jellizaveta** [comment]
Added a rule for the subscription popup. Will be available within 1-2 hours.

**Comment by youdontneedtoknow22** [comment]
> Unfortunately, we don't block popups like this because it's a paywall:
> Screenshot:
> <img alt="Screenshot 2023-09-18 at 10 56 26" width="1792" src="https://user-images.githubusercontent.com/91964807/268584616-9d5bddbf-ee46-4923-938d-024061397b5d.png">

The thing is, this paywall is mentioned again at the end of the free section from the article. So this pop-up does nothing besides annoying while reading the free section.
But it's your call! :)
