### ISSUE TITLE
24tv.ua

### ISSUE THREAD

**Issue by PoRtvine** [AdguardTeam/AdguardFilters#16173]
https://24tv.ua/v_ukrayini_zyavitsya_viyskove_mistechko_novogo_zrazka_poroshenko_rozpoviv_detali_n967193
 
uBO: 1.16.4
The Twitter unit does not show video.
Adguard Base Filters
Rule: 24tv.ua#@#iframe:not([src]):not([style^="height:"]):style(position: absolute!important; left: -3000px!important;)

**Comment by Alex-302** [comment]
thanks, fixed
