### ISSUE TITLE
instagram.com

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdguardFilters#161898]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.168

### What type of problem have you encountered?

Missed ads or ad leftovers, Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.instagram.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

To reproduce: Turn on the video player audio and pay attention to the audio, between posts like in the video. Missed ads (Audio) or incorrect blocking (Posts)

<details><summary>Video</summary>

https://github.com/AdguardTeam/AdguardFilters/assets/56846906/7fb9095f-2a79-4461-971e-a8756e723545

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Can't reproduce ads or videos without header.

**Comment by Alex-302** [comment]
> Don't you see the 'Sponsored' text?

no

**Comment by Alex-302** [comment]
I can't access to my account now.
