### ISSUE TITLE
NotTheBee.com & BabylonBee.Com

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardFilters#161867]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

Latest nightly

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

Most; examples below

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard Experimental filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Block WebRTC, Block Push API, Block Location API, Mask your IP address (specify in comment below, if used custom value)

### Add your comment and screenshots

As a followup to https://github.com/AdguardTeam/AdguardFilters/issues/111351 & https://github.com/AdguardTeam/AdguardFilters/issues/48254, the sibling sites have the potential for a simple URL rewrite to reduce ads & then regular filtering improves.  Examples are 
- [ ] [https://notthebee.com/<kbd>**article**</kbd>/check-out-this-mini-oasis-that-this-dude-made-on-his-balcony-for-all-the-neighborhood-squirrels](https://notthebee.com/article/check-out-this-mini-oasis-that-this-dude-made-on-his-balcony-for-all-the-neighborhood-squirrels) → [https://notthebee.com/<kbd>**cleanArticle**</kbd>/check-out-this-mini-oasis-that-this-dude-made-on-his-balcony-for-all-the-neighborhood-squirrels](https://notthebee.com/cleanArticle/check-out-this-mini-oasis-that-this-dude-made-on-his-balcony-for-all-the-neighborhood-squirrels)

- [ ] [https://babylonbee.com/<kbd>**news**</kbd>/report-the-squirrels-are-up-to-something](https://babylonbee.com/news/report-the-squirrels-are-up-to-something) → [https://babylonbee.com/<kbd>**cleanArticle**</kbd>/report-the-squirrels-are-up-to-something](https://babylonbee.com/cleanArticle/report-the-squirrels-are-up-to-something)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Need screenshots.

**Comment by TPS** [comment]
![NTB w/ Ads](https://github.com/AdguardTeam/AdguardFilters/assets/185902/3e43aa1d-e36c-4c92-bd0a-fd97bf750ec0)

![NTB w/o Ads.jpg](https://github.com/AdguardTeam/AdguardFilters/assets/185902/62c7b2e7-8a61-4177-bf88-755197758e65)

![BB w/ Ads](https://github.com/AdguardTeam/AdguardFilters/assets/185902/4331b350-0a31-4d0b-95b6-2e4d2a711906)

![BB w/o Ads](https://github.com/AdguardTeam/AdguardFilters/assets/185902/795447b2-4cdb-4094-95bf-304404dc9a62)

**Comment by Alex-302** [comment]
Please select annoyances on screenshots, they are too big.
