### ISSUE TITLE
Coinfola.com

### ISSUE THREAD

**Issue by alvino-prog** [AdguardTeam/AdguardFilters#161800]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [x] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

AdGuard Browser extension v4.2.168

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://coinfola.com/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Japanese filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, Adblock Warning Removal List

### Add your comment and screenshots

This page no need to watch any ads, but that ads are annoying have popups or any ads, it only need to press claim button original link was https://coinfola.com/ to see faucet page need to be login, you can use my account or any account, https://coinfola.com/surf it same like faucet page and original link was https://coinfola.com/ please help, thankyou a temp user was send to [filters@adguard.com](mailto:filters@adguard.com)

Screenshots
<details><summary>Screenshot 1:</summary>

Below there was surf page

<img width="960" alt="Screenshot 2023-09-14 175418" src="https://github.com/AdguardTeam/AdguardFilters/assets/54900965/32dee81c-9041-4a1d-b8cb-722ee0159ea9">

</details>

<details><summary>Screenshot 2:</summary>
This page no need to watch any ads too, and below there is a faucet page https://coinfola.com/faucet

<img width="960" alt="Screenshot 2023-09-14 175404" src="https://github.com/AdguardTeam/AdguardFilters/assets/54900965/bc361fbf-885c-492f-9785-1e87df5d8a43">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by alvino-prog** [comment]
@AdamWr @Alex-302

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
