### ISSUE TITLE
[iOS] bravotv.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1620]
Video do not play at
http://www.bravotv.com/watch-what-happens-live/season-12/videos/after-show-hugh-on-his-daily-show-tantrum
TFE-411-39629
<details>
![image1](https://cloud.githubusercontent.com/assets/14153331/13235912/9bdc9a3a-d9c9-11e5-9d83-ce1a1fd577cb.PNG)
![image2](https://cloud.githubusercontent.com/assets/14153331/13235913/9dc4c494-d9c9-11e5-82cd-278f87ef9f44.PNG)
![image3](https://cloud.githubusercontent.com/assets/14153331/13235916/a0110424-d9c9-11e5-9579-294cfec86602.PNG)
![image4](https://cloud.githubusercontent.com/assets/14153331/13235918/a314bc7e-d9c9-11e5-8c46-cf61d75f4031.PNG)
</details>

**Comment by Alex-302** [comment]
Can't reproduce on Safari for Mac with iPad useragent

**Comment by Alex-302** [comment]
Ask him for check without
ID=207 Name="Adblock Warning Removal List"
ID=209 Name="Prebake" 
ID=211 Name="Anti-Adblock Killer | Reek"
