### ISSUE TITLE
tv.htv.app

### ISSUE THREAD

**Issue by pekkle-hksar** [AdguardTeam/AdguardFilters#162044]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

N/A

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome, the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

hoy tv app (tv.htv.app)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### What Stealth Mode options do you have enabled?

Hide your search queries

### Add your comment and screenshots

1. similar to #161870, hoy tv app also wrongly block video by below rule
||imasdk.googleapis.com^

### Privacy

- [X] I agree to follow this condition

**Comment by pekkle-hksar** [comment]
seems the change in https://github.com/AdguardTeam/AdguardFilters/commit/7e093e8138fd4f6a65319f35e4394fc2203aa755 will not work.
I've tested with user rules in AdGuard for Android
the rule should be something like `@@||imasdk.googleapis.com^$app=tv.htv.app` but not `domain=htv.app`

**Comment by zloyden** [comment]
>  but not domain=htv.app

If we talk about the domains, it's kinda the same, but this one is wider.
Could you show which requests has been unblocked by the `@@||imasdk.googleapis.com^$app=tv.htv.app`?

**Comment by pekkle-hksar** [comment]
在 2023年9月20日週三 15:20，zloyden ***@***.***> 寫道：
