### ISSUE TITLE
Incorrect blocking on imusic domains

### ISSUE THREAD

**Issue by OlgaPetukhova** [AdguardTeam/AdguardFilters#162141]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.11.0.1292 release

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

imusic.dk imusic.de imusic.co imusic.no imusic.fr imusic.br.com imusic.uk imusic.ca imusic.se imusic.ch imusic.es imusic.fi imusic.be imusic.nl

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Russian filter

### Add your comment and screenshots

With AdGuard enabled the navigation bar isn't shown properly: https://uploads.adguard.org/up34_34qsz.png.
After disabling AdGuard it is displayed correctly https://uploads.adguard.org/up34_302e5.png.

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
I was not able to reproduce this problem with user settings.

**Comment by Sergey-Lyapin** [comment]
Fixed cookie message ^

**Comment by Sergey-Lyapin** [comment]
@OlgaPetukhova
У тебя повторяется?
Возможно он пытался сам заблокировать какой-то элемент и заблочил навигацию.
