### ISSUE TITLE
..........

### ISSUE THREAD

**Issue by Big-U-Boss** [AdguardTeam/AdguardFilters#16240]
<details><summary>Screenshot:</summary>
Результат! &#128540;<img src="https://monosnap.com/image/7gnWoZEqqUjO9848trrRcuZXLLMyU5.png">
</details><br/>
Значится,  нужно разобраться с этой треклятой страницей и по сему представляю список правил которые я с трудом сделал!

1. > gamer-info.com#$##all-page-content{border-color:#c9e8f3!important}
задаёт цвет обрамлению границе-белый вместо  заданного под фон;
2. > gamer-info.com#$#.gi-top-menu-cnt{border-color:rgba(0,0,0,0)!important}
меняет цвет  нижней границы хедера на полупрозрачный вместо заданного фоном;
3. > gamer-info.com##BODY > DIV > DIV > DIV:first-child > A
 запрещает кликабельную область  на месте фона;
4. > gamer-info.com##div[style="height:120px;width:728px;"],DIV.roarticlecol DIV[class*="gvs"]:not(.onl-gm-ls),#games-db-main-listblock > DIV
убирает пустоту  с плавающей панели в разделе статей и [игр](https://camo.githubusercontent.com/44fa01fdc1e01e4b664a714856c5e7130d117d78/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f6b514d716c35382e6a7067);
5. > gamer-info.com#$#div[class]>a:not(.logo){background:none!important}
убирает фоновое изображение;
6. > gamer-info.com#$#body>div[id]:not(.select-multi-vals){visibility:hidden!important}
убирает css  затычку с танками при первом заходе;
7. > gamer-info.com#$#body>div:nth-child(3)>div>div{background-color:#03384f;padding:0px!important}
задаёт цвет фона на соответствующий странице и убирает отступы сверху и снизу.

Убрать видеорекламу полностью   не получилось! Она то частично блокируется, то ставит на паузу если  запретить доступ к домену!
А так в общем получилось  сносно! Если решишь  отправить на всеобщее пользование-буду только рад! Не зря время потратил!
 Заодно  проверим твою теорию про "слежкой за темой"! 
Жду ответа!

**Comment by oleedd** [comment]
По бокам внизу страницы ссылка переадресации фона не заблокирована.
Думаю, не стоит блокировать отступы сверху и снизу, так как с рекламой они не связаны, и непривычно. В данном случае ссылка переадресации внизу страницы не заблокирована.
А так - хорошая работа.

**Comment by Big-U-Boss** [comment]
@oleedd,спасибо за ваш отзыв, я исправил  пункты 3 и 4. А по поводу отступов, я действовал исходя из задействования неиспользованного пространства.  Удобно,когда  сразу появляется  контент и не нужно листать зря! У меня такое видение по крайней мере!  &#128572;
@Alex-302, как бы то ни было, я у себя оставлю ибо мне надоело всякое непотребство постоянно с учётом того что ты смотришь сквозь розовые очки с недавних пор!

**Comment by Big-U-Boss** [comment]
@oleedd,спасибо за ваш отзыв, я исправил пункты 3 и 4. А по поводу отступов, я действовал исходя из задействования неиспользованного пространства. Удобно,когда сразу появляется контент и не нужно листать зря! У меня такое видение по крайней мере! 😼
@Alex-302, как бы то ни было, я у себя оставлю ибо мне надоело всякое непотребство постоянно с учётом того что ты смотришь сквозь розовые очки с недавних пор! Честь имею! &#128123;

**Comment by oleedd** [comment]
Как поменять 7 правило, чтобы сохранились отступы? Привык к ним просто. (И к тому же политика Adguard не блокировать отступы, не связанные с рекламой. А в пользовательском фильтре можем ставить, что хотим).
Походу, нужно 8 правило, так как в разделе игр Adguard не сдвигает контент на место нового баннера.
Кстати, иногда рекламный фон не навящивый и "малорекламный" и лучше и интереснее смотрится, чем просто синий, как фон "Тени войны".

**Comment by Big-U-Boss** [comment]
@oleedd, выбор за вами. Я лишь с делал то, что для меня кажется не раздражающим. А по поводу фона-он там долго не задержится и цвет будет из-раза в раз меняться и "светофор"  наилучший из вариантов , так что однозначности не дождаться! Был там из ненавязчивых бг ff ,но его убрали.

**Comment by Big-U-Boss** [comment]
@oleedd, выбор за вами. Я лишь с делал то, что для меня кажется нераздражающим. А по поводу фона-он там долго не задержится и цвет будет из-раза в раз меняться и "светофор" наилучший из вариантов , так что однозначности не дождаться! Был там из ненавязчивых бг ff ,но его убрали.

**Comment by oleedd** [comment]
Есть ли способ заблокировать ссылку переадресации на фоне без блокировки самого фона?

**Comment by oleedd** [comment]
Есть ли способ заблокировать ссылку переадресации на фоне без блокировки самого фона (так как 5 правило дублирует 3 по результату)?

**Comment by Big-U-Boss** [comment]
Проверьте фильтры все ли включены нужные,у меня не повторяется

**Comment by oleedd** [comment]
https://gamer-info.com/game/metro-exodus/
Сегодня стал отображаться ещё и баннер 2. Серьёзно не повторяется?
![screenshot](https://user-images.githubusercontent.com/36125949/40197317-cb1d522e-5a1b-11e8-85f6-8e3a6b8a31d4.png)
![screenshot2](https://user-images.githubusercontent.com/36125949/40197323-cea4fee2-5a1b-11e8-9c86-e7491ea442b2.png)

**Comment by Big-U-Boss** [comment]
На первом фото этого нет что сбоку,На пустую полоску  и все пропуски я изваял правило вчера, там что можешь пробовать `gamer-info.com##div[style="height:120px;width:728px;"],DIV.roarticlecol DIV[class*="gvs"]:not(.onl-gm-ls),#games-db-main-listblock > DIV `👌
На втором фото это как бы контент страницы и его нет смысла  блокировать,если только самому не захочется.

**Comment by Big-U-Boss** [comment]
На первом фото этого нет что сбоку,На пустую полоску и все пропуски я изваял правило вчера, там что можешь пробовать gamer-info.com##div[style="height:120px;width:728px;"],DIV.roarticlecol DIV[class*="gvs"]:not(.onl-gm-ls),#games-db-main-listblock > DIV👌
На втором фото это как бы контент страницы и его нет смысла блокировать,если только самому не захочется.

**Comment by Big-U-Boss** [comment]
На первом фото этого нет что сбоку,На пустую полоску и все пропуски я изваял правило вчера, там что можешь пробовать `gamer-info.com##div[style="height:120px;width:728px;"],DIV.roarticlecol DIV[class*="gvs"]:not(.onl-gm-ls),#games-db-main-listblock > DIV`👌
На втором фото это как бы контент страницы и его нет смысла блокировать,если только самому не захочется.

**Comment by Big-U-Boss** [comment]
На первом фото этого нет что сбоку,На пустую полоску и все пропуски я изваял правило вчера, так что можешь пробовать `gamer-info.com##div[style="height:120px;width:728px;"],DIV.roarticlecol DIV[class*="gvs"]:not(.onl-gm-ls),#games-db-main-listblock > DIV`👌
На втором фото это как бы контент страницы и его нет смысла блокировать,если только самому не захочется.

**Comment by oleedd** [comment]
4 правило заодно и блокирует новый баннер, который ранее блокировался в AdGuard.
Насчёт контента страницы, раньше я тоже так думал. Но это 100%-ная реклама (очень замаскированная под контент сайта). Выше описано, по каким причинам. Внешняя реклама, за которую они деньги получают и "World of Tanks" в их числе.
Только вид ссылки переадресации одного из баннеров чего стоит... Набор символов в url...
 https://gamer-info.com/redirect.php?s=https://dh7X6sgdtFgdsndj/g/tekzyq4q2i8fc6643634f7c2d5eccb/subid/gi_footer_block/

**Comment by oleedd** [comment]
Спрятать не проблема. Однако хитро они придумали с маскировкой, а сами проценты получают за привлечение и онлайн покупки. В другом случае эти игры были бы только в специальном разделе, а не на каждой странице...

**Comment by Big-U-Boss** [comment]
Если и получают, то только при переходе по ссылкам, а так ....   Я сад думал скрыть их но потом увидел что в некоторых разделах где 1 колонка будет как-т0 совсем пусто вот и  решил оставить, они как бы и не мешают особо в отличие от пропусков посреди.

**Comment by Big-U-Boss** [comment]
Если и получают, то только при переходе по ссылкам, а так ....   Я сам думал скрыть их но потом увидел что в некоторых разделах где 1 колонка будет как-т0 совсем пусто вот и  решил оставить, они как бы и не мешают особо в отличие от пропусков посреди.

**Comment by oleedd** [comment]
Кстати, советую. Самый лучший сайт в плане игровых новостей для меня. Сами пишут аналитические статьи, обзоры, новости очень интересно и профессионально, не копируя с других русскоязычных.
https://evrl.to/
Gamer-info.com лучший для меня в плане классификации игр по сериям, обновлению даты выхода, описанию вышедших игр. А тот чисто специализируется на новостях, но, как по мне, поинтересней, чем gamer-info.com.

**Comment by Big-U-Boss** [comment]
Знаю  про него, там новости смешанные,  тут же они по большей части официальные, но сам сайт оставляет желать лучшего, натыканный рекламой и наотрез отказывается от не показа. Но я с ним разберусь.......... 🎃

**Comment by oleedd** [comment]
Типо ещё осталось с видеорекламой разобраться?

**Comment by Big-U-Boss** [comment]
и это тоже,но это всё временные решения, если наш уважаемый @Alex-302  решит снова в конфронтацию вступить, то придется заново  всё делать ибо понатыкивает   в разные места  в худшем случае, в лучшем-изменит название.

**Comment by oleedd** [comment]
Нет. Проблем больше не вижу. Но по политике AdGuard баннеры со второго скрина должны однозначно все блокироваться.
Ну там же строгие правила, все правила по регламенту типо, по секциям распределены.
Только что, кстати, фон поменяли на жутко рекламный.

**Comment by Big-U-Boss** [comment]
> Но по политике AdGuard баннеры со второго скрина должны 
ты слышал алекса,  у него нет мочи бороться с ним

> Только что, кстати, фон поменяли на жутко рекламный.

 я предупреждал об этом😁

**Comment by Big-U-Boss** [comment]
> Но по политике AdGuard баннеры со второго скрина должны


ты слышал алекса, у него нет мочи бороться с ним

> Только что, кстати, фон поменяли на жутко рекламный.


я предупреждал об этом😁

**Comment by Big-U-Boss** [comment]
>  Но по политике AdGuard баннеры со второго скрина должны однозначно все блокироваться.

ты слышал алекса, у него нет мочи бороться с ним

> Только что, кстати, фон поменяли на жутко рекламный.

я предупреждал об этом😁

**Comment by oleedd** [comment]
Я уже это заметил. Действительно очень сложный и редкий сайт в плане рекламы. Но тут есть 2 других сильных гуру. Но они вроде русскими сайтами вообще не занимаются.
Но правила и для этого фона отлично работают.

**Comment by Big-U-Boss** [comment]
Это естественно, ибо в общий доступ они не попадали!

**Comment by oleedd** [comment]
Не работает 3 правило. Как изменить?
