### ISSUE TITLE
[iOS] book-secure.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1624]
https://www.book-secure.com/
<details>
![image1](https://cloud.githubusercontent.com/assets/14153331/13240629/c3ba4f0c-d9ec-11e5-9d90-80125c23d226.PNG)
![image2](https://cloud.githubusercontent.com/assets/14153331/13240630/c6d5b0aa-d9ec-11e5-8327-515d8b060d88.PNG)
</details>
SBK-507-35068

**Comment by Alex-302** [comment]
@Bohdan-SUP 
у тебя без адгарда нормально открывается? У меня пустая страница(в коде тоже не густо))

**Comment by Bohdan-SUP** [comment]
Они похоже что-то изменили на сайт. У меня тоже пусто, мобильная версия тоже кривая :/

**Comment by Alex-302** [comment]
Уточнить бы у юзера как у него отображается.

**Comment by vozersky** [comment]
@Alex-302 
У юзера вот так:
https://dl.dropboxusercontent.com/u/57517781/image1.PNG
https://dl.dropboxusercontent.com/u/57517781/image2.PNG

**Comment by Alex-302** [comment]
@vozersky 
у меня ни в какую не открывается даже на компе. Спроси, повторяется ли на десктопе. Если да - мне нужен будет удалённый доступ

**Comment by vozersky** [comment]
@Alex-302  повторяется только на ipad, на десктопе он не проверял

**Comment by vozersky** [comment]
@Alex-302 https://www.book-secure.com/index.php?s=results&property=idbin27719&arrival=2016-03-29&departure=2016-03-30&adults1=2&adults2=1&adults3=1&children1=0&children2=0&children3=0&rooms=1&locale=en_GB&currency=IDR&stid=85jx5tk3b&showPromotions=1&Clusternames=ASIAIDHTLTheSanchaya&cluster=ASIAIDHTLTheSanchaya&Hotelnames=ASIAIDHTLTheSanchaya&hname=ASIAIDHTLTheSanchaya&adult1=6&child1=0&adult2=6&child2=0&adult3=6&child3=0
