### ISSUE TITLE
http://kinokong.net/ - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1625]
![image](https://cloud.githubusercontent.com/assets/15856304/13255936/30df0398-da51-11e5-9d98-636bee5d138c.png)

Basic filter set, CBB-400-47322

**Comment by Alex-302** [comment]
||loginbox.ru^$third-party

**Comment by Bohdan-SUP** [comment]
http://prnt.sc/aa5oyh
