### ISSUE TITLE
chrome://newtab/

### ISSUE THREAD

**Issue by SergeyKolobaev** [AdguardTeam/AdguardFilters#162564]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

4.2.168

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

chrome://newtab/

### What filters do you have enabled?

AdGuard Russian filter

### Add your comment and screenshots

Ads appear when I open a new tab using the Ctrl+T keyboard shortcut in the Chrome browser.
Condition: by default, a new tab opens the ya.ru home page

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
`chrome://newtab/` cannot be filtered by browser extensions.
