### ISSUE TITLE
andante.com.tr

### ISSUE THREAD

**Issue by xqtp** [AdguardTeam/AdguardFilters#162624]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.52.2

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://www.andante.com.tr/`

### What filters do you have enabled?

AdGuard Turkish filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Widgets filter, EasyList, EasyPrivacy

### Add your comment and screenshots

Current rules blocks third-party ads, but it also blocks first-party official images. highlighted banners are not advertisements. See the screenshot below.

The ads on the site are not annoying, so they can be ignored.

```
andante.com.tr##.switching-banner-group
/files/banner/*$domain=andante.com.tr
```

<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/103899764/a05a6af8-518a-46e1-8cde-5eae303a7337)

![image](https://github.com/AdguardTeam/AdguardFilters/assets/103899764/6afb3860-87e5-4419-af06-ebcc025fcd6c)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
The website has low visitors, so the rules has been removed.
