### ISSUE TITLE
Nitefall extension causes leftovers on yorum.altin.in

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardFilters#162715]
@adguard-bot commented on [Tue May 16 2023](https://github.com/AdguardTeam/AdguardFilters/issues/151001)

### Issue URL (Ads)
 [https://yorum.altin.in/tum/dolar](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fyorum.altin.in%2Ftum%2Fdolar)
### Comment
Username: @gototheskinny
> Leftover

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Z3NnMev.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.6
Browser: | Safari
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard German, <br/>AdGuard Turkish

---

@zloyden commented on [Tue May 16 2023](https://github.com/AdguardTeam/AdguardFilters/issues/151001#issuecomment-1549587367)

Fixed, update should be available in 2-3 hours.

---

@gototheskinny commented on [Thu May 18 2023](https://github.com/AdguardTeam/AdguardFilters/issues/151001#issuecomment-1552211820)

> Fixed, update should be available in 2-3 hours.

@zloyden 
Just checked it and it's not fixed for me rn.

---

@zloyden commented on [Thu May 18 2023](https://github.com/AdguardTeam/AdguardFilters/issues/151001#issuecomment-1552519713)

Not reproduced it on my end even with a Turkish IP.
Try to clear browser data, update the filters (wait almost one minute there), open the site.
If that doesn't work, you should re-enable the content blockers in Safari settings (wait about the same time as when you update the filters).

---

@gototheskinny commented on [Thu May 18 2023](https://github.com/AdguardTeam/AdguardFilters/issues/151001#issuecomment-1552929974)

> Not reproduced it on my end even with a Turkish IP.
> 
> Try to clear browser data, update the filters (wait almost one minute there), open the site.
> 
> If that doesn't work, you should re-enable the content blockers in Safari settings (wait about the same time as when you update the filters).

Tried everything that you've said but it's not working. It's only for me I guess.

---

@zloyden commented on [Thu May 18 2023](https://github.com/AdguardTeam/AdguardFilters/issues/151001#issuecomment-1552995058)

Strange, try to do next:
1. Add the rule `yorum.altin.in#?#.sol > div:has(> ins.adsbygoogle)` in User rules
2. Wait ~ 1 minute there
3. Clear Safari browser data
4. Restart it
5. Open the site

---

@gototheskinny commented on [Thu May 18 2023](https://github.com/AdguardTeam/AdguardFilters/issues/151001#issuecomment-1553051488)

> Strange, try to do next:
> 
> 1. Add the rule `yorum.altin.in#?#.sol > div:has(> ins.adsbygoogle)` in User rules
> 
> 2. Wait ~ 1 minute there
> 
> 3. Clear Safari browser data
> 
> 4. Restart it
> 
> 5. Open the site
> 
> 

Without nitefall extension
<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/51786709/b8a5f477-2605-4805-b9b1-d40cc4bd1fe6)
</details><br/>

With nitefall ex
<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/51786709/a9141139-735f-46c8-ab3e-f34c669e28c8)
</details><br/>

Just tried without the user rule same response 

---

@zloyden commented on [Thu May 18 2023](https://github.com/AdguardTeam/AdguardFilters/issues/151001#issuecomment-1553138017)

> Without nitefall extension

Do you mean [this](https://apps.apple.com/us/app/nitefall-dark-mode-for-safari/id1575190591)? As I can see, if you enable nitefall extension, you'll get the leftover.
So, seems that the problem is not with the rules.

---

@gototheskinny commented on [Thu May 18 2023](https://github.com/AdguardTeam/AdguardFilters/issues/151001#issuecomment-1553150547)

> > Without nitefall extension
> 
> 
> 
> Do you mean [this](https://apps.apple.com/us/app/nitefall-dark-mode-for-safari/id1575190591)? As I can see, if you enable nitefall extension, you'll get the leftover.
> 
> So, seems that the problem is not with the rules.

Yes that's the extension. Yeah that's the cause of the issue. That's the first time this extension caused an issue.

**Comment by zloyden** [comment]
After spoken with `@Alex-302`, it was decided to leave it as it is.
It is blocked by the AdGuard, there is no ad. The thing is, it is the Nitefall extension that interferes with the code of the website.

**Comment by gototheskinny** [comment]
> After spoken with `@Alex-302`, it was decided to leave it as it is.
> 
> It is blocked by the AdGuard, there is no ad. The thing is, it is the Nitefall extension that interferes with the code of the website.

OK, I get it. Thank you guys for checking!
