### ISSUE TITLE
Rule broken octavius.mail.ru

### ISSUE THREAD

**Issue by Sarafa2n** [AdguardTeam/AdguardFilters#163005]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.168

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

octavius.mail.ru

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

1.  I'm opening `octavius.mail.ru` with with the rule `https://github.com/AdguardTeam/AdguardFilters/commit/3f19068fa5400a167ed5c9615b0ad47286431290` and it breaks the mail. The error `Uncaught SyntaxError: invalid escape sequence`

2. Screenshots
<details><summary>Screenshot 1:</summary>
<img width="1400" alt="image" src="https://github.com/AdguardTeam/AdguardFilters/assets/32399246/5d61f197-5515-4207-8770-5d3c8f553a9d">

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
This was fixed earlier, try to check the filters update now or in 1-2 hours.
