### ISSUE TITLE
[Stealth mode] 'block third-party cookies' blocks some aliexpress.com functions

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1632]
Блокировать сторонние куки-файлы (cookies) дает ошибку при подтверждении оплаты товара на aliexperess.com:

http://i.imgur.com/F66vyGC.jpg

DKM-719-46344

**Comment by Alex-302** [comment]
Адрес с опечаткой, в фишинг наверное нужно добавить.

По самой проблеме - передай такие правила
```
@@||icashier.alipay.com^$domain=aliexpress.com
@@||iopen.alipay.com/gateway.do$domain=aliexpress.com
```
У меня вроде работает, по крайней мере отказ банка получил.
Если поможет - закрывай. Добавил в фильтр.

**Comment by Alex-302** [comment]
ну что там?

**Comment by Alex-302** [comment]
@evgeniy-ADG

**Comment by evgeniy-ADG** [comment]
завтра проверю, если совсем молчу, пинай в скайп

**Comment by evgeniy-ADG** [comment]
Вроде бы ок, чтобы подтвердить/опровергнуть, нужно что-то купить, я пока не выбрал что :) Попрошу пользователя проверить.

**Comment by evgeniy-ADG** [comment]
Попрошено.
