### ISSUE TITLE
floweryfact.com

### ISSUE THREAD

**Issue by sunnywu484** [AdguardTeam/AdguardFilters#163233]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS, Other ad blocker

### AdGuard version

N/A Using PiHole with list

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://floweryfact.com/

### What filters do you have enabled?

EasyList

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by sunnywu484** [comment]
Admiral Ad Detection Domain

**Comment by zloyden** [comment]
I see that the domain is blocked by our AdGuard DNS. What's wrong?

**Comment by zloyden** [comment]
Btw, if you find any new admiral domains that are not in our filters, feel free to write about it.
