### ISSUE TITLE
opensource shopping cart system : OpenCart has been block by JapaneseFilter/sections/general_url.txt

### ISSUE THREAD

**Issue by asakous** [AdguardTeam/AdguardFilters#163266]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.168

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://ocam.live/index.php?route=product/product&product_id=6307

### What filters do you have enabled?

AdGuard Japanese filter

### What Stealth Mode options do you have enabled?

Hide your search queries

### Add your comment and screenshots

1. <comment>
this urle [index.php?route=product/product&product_id=$document,domain=cyou|life|live|shop|xyz] just match people use OpenCart system and  domain name end with cyou|life|live|shop|xyz.  I don't think it's a good rule. it kills so many web site. 

2. Screenshots
<details><summary>
![messageImage_1696557524042](https://github.com/AdguardTeam/AdguardFilters/assets/6611523/adb158db-e868-41d3-9943-a8b1b8ae9f4f)
</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
@Yuki2718 added the filter to block Japanese language scam websites.( https://github.com/AdguardTeam/AdguardFilters/commit/31d64b0dc104278952ff3d08223b32a50f1813fe )

**Comment by Yuki2718** [comment]
@asakous Do you have more examples? The parameter with .live is `really` commonly used for scam in Japan.

**Comment by asakous** [comment]
https://giorgiosedra.style/index.php?route=product/product&product_id=5920
https://www.chestermuseum.com/product/product&product_id=2229
https://www.labguide.com.tw/index.php?route=product/product&product_id=218
above web site all use opencart system.


threre are many site use opencart system . they may or may not affect now . but I suggest block spectific scamer domain rather than general rules.
