### ISSUE TITLE
r10.net obsolete rules

### ISSUE THREAD

**Issue by xqtp** [AdguardTeam/AdguardFilters#163226]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock origin

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.r10.net/

### What filters do you have enabled?

AdGuard Turkish filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, EasyList, EasyPrivacy

### Add your comment and screenshots

```
https://github.com/AdguardTeam/AdguardFilters/issues/60729#issue-671824977
r10.net##.text-center.dblck


https://github.com/AdguardTeam/AdguardFilters/issues/60729#issuecomment-668752445
||cdn.r10.net/p_e_p_sol.gif


https://github.com/AdguardTeam/AdguardFilters/issues/65587#issue-721668422
||cdn.r10.net/mg/ticimaxd.gif

https://github.com/AdguardTeam/AdguardFilters/issues/65587#issuecomment-710863593
/(lftstatic|footicimax)\.gif/$domain=r10.net

https://github.com/AdguardTeam/AdguardFilters/issues/76102
/images/banners/*$domain=analiz.r10.net

https://github.com/AdguardTeam/AdguardFilters/issues/81261
r10.net##a[href="https://www.paywant.com/"][target="_blank"]
||cdn.r10.net/_b4nn3r/pywnt.gif


https://github.com/AdguardTeam/AdguardFilters/commit/700d31b06c7bb3f2193a3f705a844c087356d4f5
||cdn.r10.net/mg/thodexuzun.gif

! Mobile
https://github.com/AdguardTeam/AdguardFilters/issues/97818
||cdn.r10.net/newbn/igtr.webp
r10.net##.container > div > a[target="_blank"] > img

```

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
`||cdn.r10.net/mg/ticimaxd.gif` seems to be still available, so I didn't remove it.
`r10.net##.container > div > a[target="_blank"] > img` is still required on my end in mobile view.
