### ISSUE TITLE
piwik.mw.uni-freiburg.de is filtered by dns1.adguard.com and dns2.adguard.com

### ISSUE THREAD

**Issue by thomasmerz** [AdguardTeam/AdguardFilters#163295]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

none - I use AdGuard DNS

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://piwik.mw.uni-freiburg.de/

### What filters do you have enabled?

AdGuard Mobile Ads filter

### Add your comment and screenshots

I'm using Pi-hole with different filtering DNS resolvers - but only these AdGuard DNS servers are filtering this domain for "zentraler Webserver der Universität Freiburg"

```
$ for dns in $(grep ^PIHOLE_DNS *conf -h|cut -d "=" -f2); do echo $dns; dig $h @"$dns"; done
45.90.28.241
piwik.mw.uni-freiburg.de. 86390	IN	A	132.230.133.95
45.90.30.241
piwik.mw.uni-freiburg.de. 86318	IN	A	132.230.133.95
94.140.14.14
piwik.mw.uni-freiburg.de. 3600	IN	A	0.0.0.0
94.140.15.15
piwik.mw.uni-freiburg.de. 3600	IN	A	0.0.0.0
193.110.81.9
piwik.mw.uni-freiburg.de. 86390	IN	A	132.230.133.95
185.253.5.9
piwik.mw.uni-freiburg.de. 86390	IN	A	132.230.133.95
```

Please remove from filter. Thanks in advance.

### Privacy

- [X] I agree to follow this condition

**Comment by thomas-merz** [comment]
Ah, ok, I understand. Thanks for clarifying 👍🏼
