### ISSUE TITLE
AdGuard Cookie Notices filter is causing pizzafan.gr to be unusable

### ISSUE THREAD

**Issue by GeorgeGR21** [AdguardTeam/AdguardFilters#163230]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Filter version 2.0.25.64

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.pizzafan.gr/el

### What filters do you have enabled?

AdGuard Cookie Notices filter

### Add your comment and screenshots

1. When a user visits the website, they cannot click anything on the website because a cookie notice blocks the user from doing so. AdGuard Cookie Notice filter blocks the cookie notice, but the blocking thing of that cookie notice is still left there. This prevents the user from accessing anything on the entire website, unless they disable uBlock Origin or the AdGuard Cookie Notice filter.

2. Screenshots
<details><summary>Screenshot 1: AdGuard Cookie Notice filter disabled. The cookie notice is showing up, and scrolling is blocked.</summary>

![Screenshot from 2023-10-01 17-10-18](https://github.com/AdguardTeam/AdguardFilters/assets/123986260/7d5faebd-1302-45a5-a86e-028bed806d3f)

</details>

<details><summary>Screenshot 2: AdGuard Cookie Notice filter enabled. The cookie notice is not showing up, but the website is still blocked.</summary>

![Screenshot from 2023-10-01 17-06-58](https://github.com/AdguardTeam/AdguardFilters/assets/123986260/76285e60-4e06-49ea-81a3-b4e7f0c46f20)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
