### ISSUE TITLE
url param tracking: add $removeparam=_branch_referrer

### ISSUE THREAD

**Issue by wp-seth** [AdguardTeam/AdguardFilters#163342]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

in urls such as `https://podcasters.spotify.com/pod/show/ngzh/episodes/Verschrnkung--Plastik--Parasiten-e23ae4m?%24web_only=true&_branch_match_id=...&_branch_referrer=...` the param `_branch_referrer` will not be removed, yet.
but it should be removed.

### Proposed solution

add

`$removeparam=_branch_referrer`

to TrackParamFilter/sections/general_url.txt

and remove
```
click_id=*_branch_referrer=$removeparam
```
in the same file (because it will be redundant) as well as the lines
```
||tumblr.com^$removeparam=_branch_referrer
||open.spotify.com^$removeparam=_branch_referrer
||reddit.com^$removeparam=_branch_referrer
```
in TrackParamFilter/sections/specific.txt.

furthermore line
```
||blog.twitch.tv^$removeparam=/web_only|_branch_referrer/
```
could be reduced to
```
||blog.twitch.tv^$removeparam=web_only
```

**Comment by Alex-302** [comment]
Changed.
But please do not use this template for reporting filtering issues.

**Comment by wp-seth** [comment]
> please do not use this template for reporting filtering issues.

oh, sorry. i could not find a better template, because it was no bug report, but actually just a mixture of a tiny performance improvement and a bit of code cleaning.

if i should use the bug report template, then i don't know what to put in the many non-optional fields there.

**Comment by Alex-302** [comment]
@wp-seth Your info is detailed. We can accept pull requests)

At times, the simpler form is overused, disrupting processing. 
In general, we don't mind if someone reports useful information through an inappropriate form, as long as there is configuration information.
