### ISSUE TITLE
redundant entries in tracking param list

### ISSUE THREAD

**Issue by wp-seth** [AdguardTeam/AdguardFilters#163338]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

i've found several entries in `TrackParamFilter/sections/specific.txt` that are actually already blocked by entries in `TrackParamFilter/sections/general_url.txt`.

e.g.
https://github.com/AdguardTeam/AdguardFilters/blob/b9287232ea7a93eb1ef37738047352890d66d02f/TrackParamFilter/sections/specific.txt#L195
is redundant because of
https://github.com/AdguardTeam/AdguardFilters/blob/b9287232ea7a93eb1ef37738047352890d66d02f/TrackParamFilter/sections/general_url.txt#L15

are you doing this by intention or should those redundant entries better be deleted, to keep the lists smaller/clearer/faster?

### Proposed solution

to remove the redundancies:

```perl
#!/usr/bin/perl
use strict;
use warnings;
use File::Slurp qw/read_file write_file/;

my %general;
map {
	$general{$1} = 1 if /^\$removeparam=([a-zA-Z0-9_-]+)$/
} read_file 'general_url.txt';
my @specific = grep {
	!/^\|\|[a-zA-Z0-9_.-]+\^\$removeparam=([a-zA-Z0-9_-]+)$/ || !$general{$1}
} read_file 'specific.txt';
write_file 'specific.txt', @specific;
```

**Comment by Alex-302** [comment]
Ok, removed.

**Comment by wp-seth** [comment]
at the top i just gave an example, but there are some more redundant entries. with the given script some of them are deleted. i created a pull request now. maybe that makes it clearer.

**Comment by Alex-302** [comment]
Got it. Thanks)

**Comment by Alex-302** [comment]
Visited your site:)
https://www.youtube.com/watch?v=itjmKlYjUak

**Comment by wp-seth** [comment]
?

**Comment by Alex-302** [comment]
<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/5c34ae0a-baf8-4ff5-ada1-fad68f492c40)


</details>

**Comment by wp-seth** [comment]
ok, i understand.
