### ISSUE TITLE
dailyshincho.jp - Ad

### ISSUE THREAD

**Issue by SKEIDs** [AdguardTeam/AdguardFilters#163434]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.168

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.dailyshincho.jp/article/2023/10081104/?all=1&page=2

### What filters do you have enabled?

AdGuard Base filter, AdGuard Japanese filter , AdGuard Annoyances Filter , AdGuard Social Filter

### Add your comment and screenshots

1. comment

I did not know what trouble the existing rules concerned.
`dailyshincho.jp#?#.c-box-ad:not(:has(a[href$="/recruit1/"]))`
So I create an issue instead of a PR.

2. Screenshots
<details><summary>screenshot</summary>

![](https://i.ibb.co/B2ZW120/image.png)
</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Added `dailyshincho.jp##.c-box-ad-movie--space`
Please take a look.
