### ISSUE TITLE
perchance.org

### ISSUE THREAD

**Issue by Teraskull** [AdguardTeam/AdguardFilters#163449]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.168

### What type of problem have you encountered?

Missed ads or ad leftovers, AdGuard gets detected on a website

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://perchance.org/ai-text-to-image-generator

### What filters do you have enabled?

AdGuard Base filter

### Add your comment and screenshots

AdGuard gets detected on the website and the page gets reloaded after 60 seconds when "OK" on the alert is clicked.

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/24798198/1380d69a-514f-48e7-96f8-a2c19a837be9)

</details>

I am currently using my own UserScript in Tampermonkey for bypassing the ads.

Here's the UserScript: https://greasyfork.org/en/scripts/476914-ads-perchance/code

I don't know if it's possible to create an AdGuard filter from this.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Fixed.

**Comment by trymion** [comment]
I wanted to say that this might have gotten bypassed.  I just heard of this site and I am getting the message about adblockers and the automatic 60 second reload.

Should I make a new post about it,  I wasn't sure if I should or if replying in here would be less clutter.

I have all the base/default filters and oisd big as well.
1.1.1.1 dns and "standard" tracking protection.

**Comment by Alex-302** [comment]
Updated.

**Comment by Alex-302** [comment]
Looks like their design

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/92f9d4fc-e9fc-4a3c-99e3-cdcdc167a848)


</details>

**Comment by Teraskull** [comment]
No, the bottom border gets a bit taller

**Comment by Teraskull** [comment]
Fair enough haha, strangely, my GreasyFork UserScript still works.
