### ISSUE TITLE
mail.ru

### ISSUE THREAD

**Issue by Nirineya** [AdguardTeam/AdguardFilters#163446]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.189

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome, Microsoft Edge, Yandex Browser

### Which device do you use?

Desktop

### Where is the problem encountered?

https://mail.ru/

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter

### Add your comment and screenshots

1. При включенном расширении AdGuard невозможно нормально переключаться между вкладками на скриншоте.

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/119436165/c37f0bd7-aed8-4b30-bcd8-a2d522b0fd4c)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Не повторяется, вкладки переключаются. Попробуйте обновить фильтры, очистить данные браузера, перезапустить его и открыть сайт.

**Comment by zloyden** [comment]
Также рекомендуется установить AdGuard Extra.

---

Известно, что эта проблема решается с помощью AdGuard Extra.

Если вы пользуетесь AdGuard на устройствах Windows, Mac или Android, пожалуйста, убедитесь, что AdGuard Extra включена в настройках приложения.

Если вы используете расширение AdGuard для браузера, рекомендуется также установить AdGuard Extra.

* [Установка на браузеры Chrome, Edge или другие, основанные на Chromium](https://agrd.io/adguard_extra_chrome_release)
* [Установка на Firefox](https://agrd.io/adguard_extra_firefox_release)
