### ISSUE TITLE
stadt-bremerhaven.de

### ISSUE THREAD

**Issue by herry23xet** [AdguardTeam/AdguardFilters#163468]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard for Safari 1.11.15

### Environment

```markdown
- OS: Sonoma 14
- Safari version: 17
```

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter

### Issue Details

Steps to reproduce:
1. Go to https://stadt-bremerhaven.de 
2. (Click on an article or next page)
3. A display indicating that I am using blocking then appears

### Actual Behavior

Display cannot be removed.

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="1232" alt="Bildschirmfoto 2023-10-06 um 18 02 12" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/135629084/f3664898-0c6a-4643-8d1b-866e948100e5">

</details>

**Comment by jellizaveta** [comment]
Fixed, new rules will be available with the new filter update within 1-2 hours.
