### ISSUE TITLE
chrome-stats.com - Ads

### ISSUE THREAD

**Issue by SKEIDs** [AdguardTeam/AdguardFilters#163539]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

ver 4.2.168

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://chrome-stats.com/top

### What filters do you have enabled?

AdGuard Base filter, AdGuard Japanese filter , AdGuard Annoyances Filter , AdGuard Social Filter

### Add your comment and screenshots

1.  comment 
Ads banner URL.
```
https://cdn.jsdelivr.net/gh/foyer-work/cdn-files/1.gif
https://cdn.jsdelivr.net/gh/foyer-work/cdn-files/2.gif
```

These Ads can also be found on the following websites.

https://firefox-stats.com/top
https://edge-stats.com/top

If necessary, fix this in the easyList. As at this time https://github.com/AdguardTeam/AdguardFilters/pull/156491 

2. Screenshots
 
<details><summary>screenshot</summary>

![](https://i.postimg.cc/Hn7cwdbR/image.png)
</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
