### ISSUE TITLE
Where's BarbBlock?

### ISSUE THREAD

**Issue by TheHadouJHyrule** [AdguardTeam/AdguardFilters#163578]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

BarbBlock suddenly disappeared from AdGuard. I researched why it disappeared, and it's because the URL changed.

### Proposed solution

Please use the following text file to reintroduce this list:

https://paulgb.github.io/BarbBlock/blacklists/adblock-plus.txt

### Additional information

The domains in this list can detect where blocking is an issue for these companies. They then use these analytics to write cease & desist letters to the developers of the blocklists, forcing them to comply or end up in court. To avoid any issues down the road, please implement this list by default.

**Comment by TheHadouJHyrule** [comment]
I'm not sure which category this belongs in. I'll let the AdGuard Team decide.

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/FiltersRegistry/issues/829
