### ISSUE TITLE
www.skygo.sky.de - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1635]
www.skygo.sky.de won't start the movie or live video when adguard is activated. I have to deactivate it and it works. However, I would really appreciate it when I can surf adfree in parallel when I watch sky go.

As far as I can see the site is available only for Sky users =\ How can we fix this?

FDJ-413-71665

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Ask him, please, for remote access or login:password. You can write me directly to Skype

**Comment by evgeniy-ADG** [comment]
@Alex-302 как тебя там найти? :)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
```
Alex302 .
```

**Comment by evgeniy-ADG** [comment]
Done, will update.
