### ISSUE TITLE
duden.de

### ISSUE THREAD

**Issue by herry23xet** [AdguardTeam/AdguardFilters#163687]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Safari

### AdGuard version

1.11.15

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.duden.de/rechtschreibung/Plauderlaune

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, EasyList Germany, EasyPrivacy, Peter Lowe's Blocklist

### Add your comment and screenshots

1. Website offers the correct spelling of words. If you go to a specific word, AdGuard is detected.

2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="1239" alt="Bildschirmfoto 2023-10-12 um 20 46 36" src="https://github.com/AdguardTeam/AdguardFilters/assets/135629084/eec7dabc-8368-497f-994c-1b7ece9e90ec">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
This is adblock detection paywall.

For user filter:
`||duden.de/aab`

**Comment by herry23xet** [comment]
@BlazDT Somehow I have the problem again!
With uBlock Origin I don't get this message on Windows with Firefox and "Duden.de" works there. Can you perhaps check this again?

**Comment by BlazDT** [comment]
Still blocked here with mentioned URL.
Any specific page? I tried with following URL and still working:
https://www.duden.de/rechtschreibung/Bier

**Comment by herry23xet** [comment]
@BlazDT Sorry, the rule I mentioned does work. However, for reasons unknown to me, the entry in Adguard was no longer there. But I just added it again and it works again. Thank you!

**Comment by herry23xet** [comment]
@BlazDT 
At the moment Duden is not working again.
Example: https://www.duden.de/rechtschreibung/schonen

Rule is in and also switched on. The latest version of the app is also available. And the lists are also up to date.
Could you possibly check this?

**Comment by BlazDT** [comment]
Use either rule:
```
@@|pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=duden.de
duden.de#%#//scriptlet("set-constant", "handleUtilitiesChecking", "noopFunc")
||duden.de/utilities^
```

First rule is unblocking the checking request, 2nd one breaks their checking script (which they can rename of course) and third blocks their responsible script.

**Comment by herry23xet** [comment]
@BlazDT Thank you, it works.
