### ISSUE TITLE
edgeservices.bing.com (Bing Chat in Microsoft Edge)

### ISSUE THREAD

**Issue by WakoKnight** [AdguardTeam/AdguardFilters#163763]
### Prerequisites

- [x] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.15 (4385)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

edgeservices.bing.com

### What filters do you have enabled?

AdGuard Base filter, AdGuard French filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Filter unblocking search ads and self-promotion

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Hide Referrer from third-parties (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

Steps to reproduce the problem:
1. Open the Microsoft Edge browser.
2. Open Bing Chat by clicking on the logo at the top right of the web browser’s window.
3. Start typing a question to Bing Chat.

Bing Chat reloads with a Discover page.

We can solve this problem by adding the following rule:
@@||edgeservices.bing.com^$domain=edgeservices.bing.com

As this problem can only occur in Microsoft Edge, the rule could be more precise: @@||edgeservices.bing.com^$domain=edgeservices.bing.com,app=msedge.exe

### Privacy

- [X] I agree to follow this condition

**Comment by WakoKnight** [comment]
To solve the issue, we can also uncheck ‘Hide your search queries’ when Stealth Mode is enabled.

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
