### ISSUE TITLE
Old adguard and new filters are breaking mail.ru

### ISSUE THREAD

**Issue by rfgerasimov** [AdguardTeam/AdguardFilters#164072]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.3 RC2

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Desktop

### Where is the problem encountered?

https://mail.ru

### What filters do you have enabled?

AdGuard Russian filter

### Add your comment and screenshots

1. Rules 

mail.ru#%#//scriptlet('json-prune', '*.json.result.body.direct')
mail.ru#%#//scriptlet('json-prune', 'result.status')

Many users have an old adguard with new filters and it looks like it have a bug with json-prune
Users write about problems

2. Screenshots

<details><summary>Screenshot 1:</summary>

<img width="956" alt="Снимок экрана 2023-10-18 в 18 29 54" src="https://github.com/AdguardTeam/AdguardFilters/assets/148352820/c06e7332-2f75-4bef-bcdc-6eb0d19d1021">

</details>

<details><summary>Screenshot 2:</summary>
<img width="1635" alt="Снимок экрана 2023-10-18 в 18 31 09" src="https://github.com/AdguardTeam/AdguardFilters/assets/148352820/1753ca44-a22c-4746-8e6e-ad1f3dca5c11">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I don't see such an error in the latest version of nightly.
Note that the latest [release](https://github.com/AdguardTeam/AdguardForWindows/releases/tag/v7.15.0) version is `7.15`, so it's better to update the app, then the filters, clear browser data, restart it, open the site.

**Comment by rfgerasimov** [comment]
@zloyden  Это больше про проблему пользователей 
У многих людей стоит старая версия, сложно будет всем сказать, чтобы перешли на новую

**Comment by rfgerasimov** [comment]
Многие даже не знают, что у них adguard стоит
