### ISSUE TITLE
wallstmemes.com

### ISSUE THREAD

**Issue by WakoKnight** [AdguardTeam/AdguardFilters#164281]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.15 (4385)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome, Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://token.wallstmemes.com/en#staking

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, Adblock Warning Removal List

### Other

Filter unblocking search ads and self-promotion

### Language-specific

AdGuard French filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Block Location API, Hide Referrer from third-parties (specify in comment below, if used custom value), Mask your IP address (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

Problem: When connecting to the MetaMask wallet to view the tokens, the webpage does not load correctly. The token count always displays as 0 when the “Hide your Referer from third parties” stealth option is selected. There is no need to have any tokens to see when the problem is resolved. Instead, we can look at the top of the page. The section above the “Buy on Uniswap” button displays a refresh animation instead of showing text. The HTML code for this part is:
`<div _ngcontent-ng-c3731292653="" class="w-100 bg-black d-flex flex-column align-items-center justify-content-start p-3 text-white text-center"><h4 _ngcontent-ng-c3731292653="" class="text-uppercase shimmer ng-star-inserted">Buy and stake $WSM now!</h4><!----><div _ngcontent-ng-c3731292653="" class="mb-2 font-16 break-word shimmer">Stake $WSM now to earn rewards. Staked tokens can be withdrawn after 7 days since you last updated your stake. Use 0xB62E45c3Df611dcE236A6Ddc7A493d79F9DFadEf to add $WSM to your wallet</div><div _ngcontent-ng-c3731292653="" class="usdt-val text-center mb-0 text-mid-grey fw-semibold shimmer ng-star-inserted"> Your staked  WSM = 0 </div><!----><div _ngcontent-ng-c3731292653="" class="usdt-val text-center mb-0 text-mid-grey fw-semibold d-flex align-items-center shimmer ng-star-inserted"> Your stakeable WSM = 0 <img _ngcontent-ng-c3731292653="" src="/assets/images/svg-icons/info-icon_white.svg" alt="" class="img-fluid ms-2 cursor-pointer"></div><!----><!----></div>`

I fixed the problem by adding this custom rule:
`@@||convincing-prettiest-firefly.quiknode.pro^$domain=token.wallstmemes.com,third-party`

Steps to reproduce the problem:
1. Install the MetaMask Chrome extension and create an account (this only takes a few seconds).
2. Visit the webpage https://token.wallstmemes.com/en#staking
3. Select the MetaMask wallet

### Privacy

- [X] I agree to follow this condition

**Comment by WakoKnight** [comment]
I sent my AdGuard configuration file to the email address filters@adguard.com today so you can test with my settings.

**Comment by Alex-302** [comment]
> I sent my AdGuard configuration file to the email address [filters@adguard.com](mailto:filters@adguard.com) today so you can test with my settings.

Hi.
Better report using AdGuard Assistant extension, it automatically attaches requred settings.

> I fixed the problem by adding this custom rule:
@@||convincing-prettiest-firefly.quiknode.pro^$domain=token.wallstmemes.com,third-party

Useful info, thanks:)
