### ISSUE TITLE
m.youtube.com

### ISSUE THREAD

**Issue by corobin** [AdguardTeam/AdguardFilters#164243]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

n/a

### What type of problem have you encountered?

Social media buttons — share, like, tweet, etc.

### Which browser(s) do you use?

Firefox, Chrome, Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

https://m.youtube.com/watch?v=jNQXAC9IVRw

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Social Widgets

AdGuard Social Media filter

### Add your comment and screenshots

1. in the "AdGuard – Social Media" filter list, there is a filter that specifically blocks the youtube share button on mobile: 

`m.youtube.com##ytm-button-renderer.icon-share_arrow`

the share button is actually functional and should not be blocked

2. Screenshots
<details><summary>Screenshot 1: filter list disabled - share button visible</summary>

![share-1](https://github.com/AdguardTeam/AdguardFilters/assets/15662785/700505dd-d525-42a8-8d67-85f6dc76b771)

</details>

<details><summary>Screenshot 2: filter list enabled - share button hidden</summary>

![share-2](https://github.com/AdguardTeam/AdguardFilters/assets/15662785/0994a0f1-aa49-4a01-af5c-80b334b9d9f6)

</details>

3. request: please remove this filter

the list is intended for social media annoyances. this is not a share button on a third party website like social media buttons

it does not make sense to block a button that is actually functional on the first party website itself

especially since it is *not* blocked on the desktop site, where it is arguably less useful.

the share button actually delivers useful functionality for copying short links to the video. this is particularly useful on mobile because copying the address bar will copy the URL to the mobile site

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not sure. Can be shared using browser's menu.

**Comment by corobin** [comment]
> Not sure. Can be shared using browser's menu.

The difference is that the browser's share menu uses the URL bar URL, which goes to the mobile site, while the share button uses the shortlink, which redirects to the desktop/mobile site depending on the visitor's device

Copy from URL bar: `https://m.youtube.com/watch?v=jNQXAC9IVRw`

Browser share button: `https://m.youtube.com/watch?v=jNQXAC9IVRw`

Youtube share button: `https://youtu.be/jNQXAC9IVRw?feature=shared`

Further, I don't think this is a "Social media buttons — share, like, tweet, etc." in the sense that the list is intended to capture. The spammy/annoying buttons that this clearly is meant to addresses are buttons on third party sites that invite you to share *to* social media sites.

In contrast, the button in question is a functional button on the 1st party site that provides a feature that is not otherwise easily surfaced. On desktop you can get the short URL by right clicking on the video and in the context menu you can copy the short URL or a URL to the current timestamp. This is not available on mobile. The share button is the only way (that i've been able to find, anyway) that youtube has provided to copy the short url on mobile. They haven't provided, for example, a text box with the short URL in it or anything like that.

**Comment by Alex-302** [comment]
> https://m.youtube.com/watch?v=jNQXAC9IVRw

on desktop it redirects to the desktop version. On mobile it is useless, can't even share with a time stamp.
