### ISSUE TITLE
tangerine.ca

### ISSUE THREAD

**Issue by WakoKnight** [AdguardTeam/AdguardFilters#164379]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.15 (4385)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.tangerine.ca/en

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, Adblock Warning Removal List

### Other

Filter unblocking search ads and self-promotion

### Language-specific

AdGuard French filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Block Location API, Hide Referrer from third-parties (specify in comment below, if used custom value), Mask your IP address (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

Steps to reproduce the problem:
1. Go to this URL: https://www.tangerine.ca/en
2. Click on the “Log Me In” button
3. Enter “123” in the “Login ID” textbox, then click on the “Next” button

When accessing the website for the first time within 24 hours, the page asking for the PIN doesn’t load. If we start over again from step 1, then the page asking for the PIN loads and the website works fine.

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
@WakoKnight Did you exclude the website from HTTPS exclusion of AdGuard for Windows?

**Comment by WakoKnight** [comment]
@piquark6046 No, I didn’t. I sent my AdGuard configuration file to the email address filters@adguard.com today so you can test with my settings.

**Comment by piquark6046** [comment]
I cannot reproduce. 

<details><summary>Screenshot</summary>

![Screenshot from 2023-10-24 19-19-35](https://github.com/AdguardTeam/AdguardFilters/assets/98787049/fb486864-17a5-4169-a267-d589a75245ae)

</details> 


Does AdGuard for Windows 7.15.1 help to resolve your issue?
