### ISSUE TITLE
tripcentral.ca

### ISSUE THREAD

**Issue by WakoKnight** [AdguardTeam/AdguardFilters#164376]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.15 (4385)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome, Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.tripcentral.ca/

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, Adblock Warning Removal List

### Other

Filter unblocking search ads and self-promotion

### Language-specific

AdGuard French filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Block Location API, Hide Referrer from third-parties (specify in comment below, if used custom value), Mask your IP address (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

The site won’t load when “Protect from DPI” in Stealth Mode is enabled. The error message is:

> This site can’t be reached
> www.tripcentral.ca unexpectedly closed the connection.
> ERR_CONNECTION_CLOSED
> 

This site loads normally when “Protect from DPI” is disabled.

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
@WakoKnight 
<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/98787049/74adfd8e-6aa2-4cec-8fdd-4a473bc06ac3)


</details> 

Cannot reproduce.
Can you provide AdGuard configuration file via an email (filters@adguard.com) or GitHub comment?

**Comment by WakoKnight** [comment]
@piquark6046 Sorry for the long delay. You should have the same issue as me, as I can reproduce it on my computer (Windows 11, Chrome and Edge) and my Android phone (Android 12, Chrome). Did you use the configuration file I sent by email?

**Comment by piquark6046** [comment]
> Did you use the configuration file I sent by email?

Yes.

**Comment by WakoKnight** [comment]
@piquark6046 When I don't use custom rules:
![image](https://github.com/AdguardTeam/AdguardFilters/assets/98830364/4d005367-47ff-4a64-911b-cbc6b2f4872e)

When I use a custom rule (@@$stealth=dpi,to=tripcentral.ca):
![image](https://github.com/AdguardTeam/AdguardFilters/assets/98830364/497343da-c4ca-4435-95fd-e8068bc4c629)

**Comment by WakoKnight** [comment]
@piquark6046 I just tested with a VPN using 3 different Canadian servers and I have the same issue. To make it work, I need to use the user rule:
@@$stealth=dpi,to=tripcentral.ca

**Comment by WakoKnight** [comment]
@piquark6046 Do you need more information or are there other tests I can try?

As soon as I activate “Protect from DPI”, I am unable to reach the website. I tried using Incognito/InPrivate mode in Chrome and Edge, and deleted all cookies and website data. As soon as I activate my custom user rule, it works. I will connect my computer directly to the modem later today to make sure the problem is not coming from the router.

**Comment by piquark6046** [comment]
Can you downgrade to its stable channel?

**Comment by WakoKnight** [comment]
I am on the Release channel on both my Windows computer and my Android phone. The problem happens even when I am connected directly to my ISP’s modem or using my cellphone’s data.

![image](https://github.com/AdguardTeam/AdguardFilters/assets/98830364/8cb20a4d-c6d0-41dc-bfa6-96b2b3492798)

**Comment by piquark6046** [comment]
Please try to change your DNS server to Cloudflare DNS server.

**Comment by WakoKnight** [comment]
The issue persists with Cloudflare and AdGuard DNS.

![image](https://github.com/AdguardTeam/AdguardFilters/assets/98830364/4d8a0f54-15d6-4d19-bdac-83f5fdd23013)


Chrome:
![image](https://github.com/AdguardTeam/AdguardFilters/assets/98830364/f4c5a727-d323-4d00-9f56-ca7033b5d4cc)

Edge:
![image](https://github.com/AdguardTeam/AdguardFilters/assets/98830364/98e9374d-5865-40f1-94a8-06d2f8c6fffb)

**Comment by piquark6046** [comment]
Can I connect to my desktop remotely?

**Comment by WakoKnight** [comment]
> Can I connect to my desktop remotely?

I guess you’re asking to connect to my computer remotely. I could set up a VM for you to connect whenever you want.

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/164376#issuecomment-1790841985

Oh, My bad.
Yes. Is connecting between from 10:00+0000 to 14:00+0000 UTC okay

**Comment by WakoKnight** [comment]
@piquark6046 Sure, you can connect whenever you want. Here is the password to open the file I sent you by e-mail:
`~z'c4#URQUsJe;'yJ6K%cknES|xR//WWkG?hueU1U?szo@qBnd`
