### ISSUE TITLE
anti adblock script (quiet powerful)

### ISSUE THREAD

**Issue by deodeumii** [AdguardTeam/AdguardFilters#164594]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.15.1 (4386) (build 4386, CL 1.12.87)

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://porn4f.com/upload/en/dYZ41t01XkkRbIh-JKSR-610_s.jpg / https://javball.com/upload/en/gFkUt2oT38wee0h-FAZM-007_s.jpg / https://pig69.com/upload/en/q2kt0gGBJVmRc7H-MISM-291_s.jpg / https://ovabee.com/upload/en/qv07Ux5Fw1c3JZv-561PM-007_s.jpg / https://ai18.pics/upload/en/EJl2f1KxgreC5ES-200GANA-2946_s.jpg / 

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Language-specific

List-KR

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Remove X-Client-Data header from HTTP requests

### Add your comment and screenshots

1.  when i access this site(https://sukebei.nyaa.si/?f=2&c=2_2&q=) and click on a post, i'll experience a problem if i access the link that appears. queit many. 

3. <details> </details>
![123](https://github.com/AdguardTeam/AdguardFilters/assets/146622879/983a24b3-09d0-49be-90b2-2242f04afcf9)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@deodeumii Can't reproduce. Could you please make a screenshot of the button, which I should press?

**Comment by deodeumii** [comment]
> @deodeumii Can't reproduce. Could you please make a screenshot of the button, which I should press?

Like this?

(1st image)access this site(https://sukebei.nyaa.si/?f=2&c=2_2&q=)
(2nd image) click an article
(3rd image) click a link in article


![11](https://github.com/AdguardTeam/AdguardFilters/assets/146622879/54e72b39-4be9-49f6-a246-642d9333569c)
![12](https://github.com/AdguardTeam/AdguardFilters/assets/146622879/2fa8ed76-9b3e-4ebc-bfd9-153212fa73e1)
![13](https://github.com/AdguardTeam/AdguardFilters/assets/146622879/546c0b69-9f7e-49b6-8cf2-79d52b8c4ece)

**Comment by Alex-302** [comment]
@deodeumii Can't reproduce with https://sukebei.nyaa.si/view/3988219
