### ISSUE TITLE
kanald.com.tr

### ISSUE THREAD

**Issue by fenopa** [AdguardTeam/AdguardFilters#164524]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

DNS

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.kanald.com.tr/canli-yayin

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. Can't watch live stream on https://www.kanald.com.tr/canli-yayin when using Adguard DNS, can this be solved? When I try its mobile app while Adguard DNS was active, the mobile app gives this error: "Failed to connect to geoloc.hurriyet.com.tr", that's probably reason for failure in both website and app.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@fenopa Hello. While checking could not reproduce the query from `geoloc.hurriyet.com.tr` , if you exclude this domain, does the video work?
DNS - user rules - add rule:
`@@||geoloc.hurriyet.com.tr^`

**Comment by fenopa** [comment]
@jellizaveta Hi, I'm just using the DNS, is that possible with DNS?

**Comment by jellizaveta** [comment]
@fenopa  If DNS is specified in the network settings, then unfortunately exclude is not possible. I have excluded this domain from the filtering lists. The update will be available within 24 hours. Could you please check after this time has elapsed to see if the video is loading?

**Comment by fenopa** [comment]
@jellizaveta both website and the mobile app works now. thank you for the fix.
