### ISSUE TITLE
netflix.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#164668]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.15.1

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.netflix.com/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

![Untitled](https://github.com/AdguardTeam/AdguardFilters/assets/118186787/ec90862b-b15c-49fc-aef1-f67fe2f584b9)

https://www.netflix.com/msl/playapi/cadmium/event/1?reqAttempt=4&reqName=events/start&clienttype=akira&uiversion=vc2bfd55a&browsername=chrome&browserversion=118.0.0.0&osname=windows&osversion=10.0

filter to add: ||netflix.com/msl/playapi/cadmium/event/

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Unfortunately, I can't login there for now.
@jordanswrld94 do you have any breakage with the rule?

**Comment by jordanswrld94** [comment]
No. No issues.

**Comment by jordanswrld94** [comment]
U forgot the event part. I think the one u added may be to generic.

**Comment by zloyden** [comment]
Well, I've found some info that there might be other requests.
However, I've done a more specific rule for now.
