### ISSUE TITLE
Infinite "connection checking" loading

### ISSUE THREAD

**Issue by Rairof** [AdguardTeam/AdguardFilters#164626]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

Adguard 4.3 Nightly 18

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://modyolo.com and https://apkmody.com

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Fanboy's Enhanced Tracking List, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social Widgets

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, Web Annoyances Ultralist, I don't care about cookies

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Other

Filter unblocking search ads and self-promotion, AdGuard Experimental filter

### DNS filters

AdGuard DNS filter

### Language-specific

AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Ukrainian filter, ABPindo, ABPVN List, Adblock List for Finland, AdBlockID, Bulgarian list, CJX's Annoyances List, Dandelion Sprout's Nordic Filters, Dandelion Sprout's Serbo-Croatian List, EasyList China, EasyList Czech and Slovak, EasyList Dutch, EasyList Germany, EasyList Hebrew, EasyList Italy, EasyList Lithuania, EasyList Polish, EasyList Portuguese, EasyList Spanish, EasyList Thailand, Estonian List, Frellwit's Swedish Filter, Greek AdBlock Filter, Hungarian filter, Icelandic ABP List, IndianList, KAD - Anti-Scam, Latvian List, List-KR, Liste AR, Liste FR, Macedonian adBlock Filters, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Persian Blocker, Polish Annoyances Filters, Polish Anti Adblock Filters, Polish Anti-Annoying Special Supplement, Polish GDPR-Cookies Filters, Polish Social Filters, road-block light, ROList, ROLIST2, RU AdList - Counters, Xfiles, xinggsf, YousList

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Block third-party Authorization header, Block WebRTC, Block Push API, Block Location API, Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

1. It still shows infinite loading for "checking site connection security" after the site repeated loading when adguard is on but when I disable it, the site connection settings loads and check itself and redirects me to the site. Re-enabling protection brings back the connection check issue.

2. infinite loading for "checking site connection security"-
![Screenshot_2023-10-26-09-16-49-133_com android chrome-edit](https://github.com/AdguardTeam/AdguardFilters/assets/107706560/e0862097-545b-499c-9044-279250b3f871)

Same issue on https://apkmody.com-
![Screenshot_2023-10-26-09-24-28-317_com android chrome-edit](https://github.com/AdguardTeam/AdguardFilters/assets/107706560/2c2ac759-626d-45e7-b429-d0051761d3d8)

### Privacy

- [X] I agree to follow this condition

**Comment by Rairof** [comment]
> Is it working if you disable Stealth mode?

I will try and get back to you in a minute!

**Comment by Rairof** [comment]
@BlazDT It looks like it tries to load up the site by refreshing itself and human verification pop up shows up not but the site refreshes itself before that gets done...
![Screenshot_2023-10-26-12-31-26-556_com android chrome-edit](https://github.com/AdguardTeam/AdguardFilters/assets/107706560/6c7d968c-2c07-48df-9446-37e1c2e32695)

**Comment by BlazDT** [comment]
Usually that issue is caused by Stealth mode, but it seems not this time.
I also see you have a lot of filters enabled and that is not recommended. Please try to only enable AdGuard filters.

I can check the sites in about 10 hours though earliest, @zloyden could you please check on your side, thank you.

**Comment by Rairof** [comment]
I see, I usually do use a lot of filters but it didn't caused that problem before. Anyways, I guess I'll just remove the language ones since I don't use them anyways and don't know which ones are important and which ones aren't. I'll come and report here if this fixes or any new issues shows up.
Thank you.

**Comment by zloyden** [comment]
I agree with @BlazDT about Stealth mode and it's the case. Fixed for [modyolo.com](https://modyolo.com/), update should be avaialbe in 2-3 hours.
Btw, it's not recommended to use too many filters.

**Comment by zloyden** [comment]
Please provide a link for [apkmody.com](https://apkmody.com/) where you have noticed the problem.

**Comment by Rairof** [comment]
> Please provide a link for [apkmody.com](https://apkmody.com/) where you have noticed the problem.

https://apkmody.io/apps/magic-video-maker

**Comment by Rairof** [comment]
I have sent the link in above message.
I have also now removed various language filters as said, I'd appreciate you all mentioning any other filters that are not necessary to be removed as well. Much thanks to both @BlazDT & @zloyden for solving this issue!

**Comment by Rairof** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/164626#issuecomment-1781048077
Strange, I still do get the connection check page when visiting the site after disabling all language filters.

**Comment by BlazDT** [comment]
Not getting even any connection checking on https://apkmody.io/apps/magic-video-maker

**Comment by Rairof** [comment]
I don't know what's the issue then

**Comment by Rairof** [comment]
@zloyden @BlazDT sorry to disturb but I have attached a video showing the issue, don't know why it's causing it.

https://github.com/AdguardTeam/AdguardFilters/assets/107706560/cd9d2337-598c-40f9-a469-3916fc0f3887

**Comment by BlazDT** [comment]
@AdguardTeam/filters-maintainers can anyone reproduce?

**Comment by zloyden** [comment]
I've checked it, but this is not reproduced on my end. Perhaps related to `Protect from DPI`, but it needs to be checked.
@Rairof could you disable the filters, leave stealth mode options, but turn`Protect from DPI` off, then check the site?

**Comment by Rairof** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/164626#issuecomment-1782495813
I'll try it and get back to you with the results!

**Comment by Rairof** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/164626#issuecomment-1782495813
Didn't worked, tried with disabling and re enabling all filters, except language ones and still same issue persists. Here is a screenshot of the filter I used now.

![Screenshot_2023-10-27-19-26-14-937_com adguard android-edit](https://github.com/AdguardTeam/AdguardFilters/assets/107706560/e6f7e380-8b55-4569-9f48-488d2c1901ac)

**Comment by zloyden** [comment]
Hm, strange. Please do the following:
1. Disable all filters
2. Leave Stealth mode with your options
3. Try to reproduce the problem
4. If you still get it, disable stealth module option one by one to find a problematic one.

**Comment by Rairof** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/164626#issuecomment-1782977135
I'm sorry but please give me some time to follow through your steps, I'll be sorting out the results one by one and send them collectively here once I am down with them. Thank you for helping me again.

**Comment by Rairof** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/164626#issuecomment-1782977135
stealth mode with the current filters solves it, still trying it;
disabling stealth modules one by one-
1. general ads blocking, tracking protection, annoyance blocking, DNS protection, Firewall, Browsing Security; no issues
2. Tracking methods and all filters, HTTPS filtering, userscripts no issues
3. Browser API, and Miscellaneous categories too couldn't reproduce the issue...

However, the exported settings I had been using does produce the issue. Would you like to have the export file to check why its produce only through that?

**Comment by zloyden** [comment]
> stealth mode with the current filters solves it

So there is no problem with Stealth mode?

>  the exported settings I had been using does produce the issue

Hm, ok. Send them here. Note that backup to `License` must be disabled.

**Comment by Rairof** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/164626#issuecomment-1784743834
Alright, I have selected everything except ```Licence``` to enabled.
Here is the file-
[adguard_settings_4.3.68_3010_161346.zip](https://github.com/AdguardTeam/AdguardFilters/files/13204148/adguard_settings_4.3.68_3010_161346.zip)

**Comment by zloyden** [comment]
I have checked it with your settings, but the sites open fine on my end.

**Comment by Rairof** [comment]
Then it's my network ISP...there is no other way for sites to not work for me other than that now since we checked all other options...

**Comment by Alex-302** [comment]
@Rairof Please send report from AdGuard and post resulting link here.

**Comment by Rairof** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/164626#issuecomment-1785345697
I'm sorry but I am not sure what report are you referring to, can you guide me to gather this report?

**Comment by Alex-302** [comment]
@Rairof Hi
How to send report from AdGuard:
https://adguard.com/kb/guides/report-website/

Please copy resulting link here.

**Comment by AK-Drago** [comment]
i just disabled an option called hide your user agent. problem solved

**Comment by Rairof** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/164626#issuecomment-1793377111
Alright, I did it.

**Comment by Rairof** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/164626#issuecomment-1793379721
Didn't helped me

**Comment by AK-Drago** [comment]
I also turned off https filtering on this site that also worked for me.

**Comment by Alex-302** [comment]
@Rairof Ok. Please test when disabled
- filters
- DNS filtering
- stealth mode
- AdGuard extensions (userscripts)

If the site loads fine, enable one by one with checking.
