### ISSUE TITLE
rap-up.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#164982]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.3

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.rap-up.com/2023/10/28/north-west-goes-viral-after-dressing-up-as-graduation-bear/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

https://mon16-normal-useast5.tiktokv.us
(Stands for monitoring, have similiar filters already)

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
Hmm. Did u click play on the videos?

**Comment by jordanswrld94** [comment]
Also mon.us.tiktokv.com appears. U have to click play on the tiktok videos. @Alex-302

**Comment by jordanswrld94** [comment]
@AdamWr  do u see them?

**Comment by AdamWr** [comment]
Yes, I do.
I have added rules to block these requests.
