### ISSUE TITLE
Amazon app

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#164928]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.3

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.amazon.mShop.android.shopping

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

us-east-1.paa-reporting-advertising.amazon

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
It looks like an error or warning logging request. Also I didn't find it in the app, could you attach a screenshot please?

**Comment by jordanswrld94** [comment]
It also shows up in imdb app. Better to just block it. 
![Screenshot_20231030_080820_AdGuard](https://github.com/AdguardTeam/AdguardFilters/assets/118186787/9cd20358-671a-4b86-b4b4-3c698ad5eedb)

**Comment by jordanswrld94** [comment]
![Snapchat-1275541108](https://github.com/AdguardTeam/AdguardFilters/assets/118186787/169321ba-3b3d-4047-b0c9-5ac6c053b688)

**Comment by jellizaveta** [comment]
Added. If there are any problems after blocking, please let me know
