### ISSUE TITLE
samsung ad domain

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#164983]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.3

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

n/a

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

adconsent.samsungrs.com called by phone and smart tv. Reference:

https://github.com/hagezi/dns-blocklists/issues/1063

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Bad rule, breaks everything. Removed.

**Comment by xRuffKez** [comment]
Prevents Samsung Sign in!
