### ISSUE TITLE
golem.de

### ISSUE THREAD

**Issue by fabi-hub** [AdguardTeam/AdguardFilters#165007]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.5.0

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.golem.de/news/ohne-werbung-instagram-und-facebook-demnaechst-fuer-zehn-euro-monatlich-2310-178944.html

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Language-specific

AdGuard German filter

### Add your comment and screenshots

<comment>
Ads for workshops
www.golem.de##.supplementary blocks them

2. Screenshots
<details><summary>Screenshot 1:</summary>

![dsa](https://github.com/AdguardTeam/AdguardFilters/assets/67245084/191b9045-0137-46c8-804e-e59c1dea5964)

</details>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
These are self-promos, therefore please enable AdGuard Other Annoyances filter (in German it should be "AdGuard-Filter gegen andere Belästigungen")
