### ISSUE TITLE
breakingbadizle.net

### ISSUE THREAD

**Issue by xqtp** [AdguardTeam/AdguardFilters#165138]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.52.2

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://www.breakingbadizle.net/breaking-bad-5-sezon-14-bolum-izle/`

### Ad Blocking

EasyList

### Privacy

AdGuard URL Tracking filter, EasyPrivacy

### Social Widgets

Fanboy's Social Blocking List

### Annoyances

EasyList Cookie List

### Language-specific

AdGuard Turkish filter

### Add your comment and screenshots

breakingbadizle.com now redirects to breakingbadizle.net
Current rules need to be changed.

<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/103899764/7128881c-09ab-494a-8818-77b349147d4e)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
