### ISSUE TITLE
nuwm.edu.ua

### ISSUE THREAD

**Issue by dportvine** [AdguardTeam/AdguardFilters#165125]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [ ] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [ ] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://nuwm.edu.ua/

### Ad Blocking

EasyList

### Annoyances

AdGuard Cookie Notices filter

### Add your comment and screenshots

Плашка куки.

<details>
<summary>Screenshot</summary>

![2023-11-01_091921](https://github.com/AdguardTeam/AdguardFilters/assets/111344219/0775132f-8f40-4da7-8318-2470de0937e7)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
