### ISSUE TITLE
Disqus login issue at comss.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1651]
http://www.comss.ru/disqus/page.php?id=1888#disqus_thread

Adguard + Расширение не дает войти в disqus через гугл аккаунт.
Авторизация проходит, если оставить только программу или только расширение.

В расширении фильтры: http://prntscr.com/a8ixfx
В программе: http://prntscr.com/a8ixow

После обновления фильтров:
- Заходим на сайт comss.ru - авторизация не проходит.
- Однако на самом disqus.com авторизация работает

**Comment by Alex-302** [comment]
ни разу не повторилось ни с одним браузером
