### ISSUE TITLE
Can't report using edge, submission button greyed out

### ISSUE THREAD

**Issue by WoodpeckerBaby** [AdguardTeam/AdguardFilters#165218]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

123

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

example.com

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

![image](https://github.com/AdguardTeam/AdguardFilters/assets/14303318/a4bd2abc-c1e1-46be-aa32-0fd56b45a5d5)
![a](https://github.com/AdguardTeam/AdguardFilters/assets/14303318/47faa68b-8736-442c-a292-24f982075521)
![b](https://github.com/AdguardTeam/AdguardFilters/assets/14303318/adf21ec7-4257-45ac-84b7-088f56a00a59)

https://forum.solidworks.com/ then sign in

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.

**Comment by zloyden** [comment]
In case you have some problems when creating a report, please file an issue [here](https://github.com/AdguardTeam/ReportsWebApp/issues/new).
