### ISSUE TITLE
staples.ca

### ISSUE THREAD

**Issue by WakoKnight** [AdguardTeam/AdguardFilters#165406]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.15 (4386)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome, Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.staples.ca/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, Adblock Warning Removal List

### Other

Filter unblocking search ads and self-promotion

### Language-specific

AdGuard French filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Block third-party Authorization header, Block WebRTC, Block Location API, Hide Referrer from third-parties (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

It’s impossible to load the websites when “Block the third-party Authorization header” is enabled.

The same issue occurs on the following websites (all the same business):
bureauengros.ca
bureauengros.com
staples.ca

Here is the rule I use to fix it:
`@@*$stealth=3p-auth,domain=bureauengros.ca|bureauengros.com|staples.ca`

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
