### ISSUE TITLE
facebook.com

### ISSUE THREAD

**Issue by WakoKnight** [AdguardTeam/AdguardFilters#165405]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.15 (4386)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome, Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.facebook.com/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, Adblock Warning Removal List

### Other

Filter unblocking search ads and self-promotion

### Language-specific

AdGuard French filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Block third-party Authorization header, Block WebRTC, Block Location API, Hide Referrer from third-parties (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

It’s impossible to make a video call to someone on facebook.com or messenger.com when WebRTC is blocked.

Here are the rules to fix it:
```
@@||facebook.com/groupcall/^$stealth=webrtc
@@||messenger.com/groupcall/^$stealth=webrtc
```

Thank you.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Thanks!
