### ISSUE TITLE
ground.news: Annoyance

### ISSUE THREAD

**Issue by aaronliu0130** [AdguardTeam/AdguardFilters#165522]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.53.0

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://ground.news

### Ad Blocking

EasyList

### Privacy

EasyPrivacy

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Fanboy's Annoyances, EasyList Cookie List

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Chinese filter, RU AdList - Counters

### Add your comment and screenshots

1. I'm also using all uBlock filters. On ground.news, the subscription nag ("See every side of every story") is not blocked.

2. Screenshots
<details><summary>Screenshot N:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/11874211/7081544b-c02e-4679-bbd1-59dc12851fb0)

</details>

<details><summary>uBlock Troubleshooting Information</summary>
<pre>
uBlock Origin: 1.53.0
Firefox: 115
filterset (summary):
 network: 146807
 cosmetic: 222342
 scriptlet: 30891
 html: 1342
listset (total-discarded, last-updated):
 added:
  adguard-social: 21991-858, 10m
  fanboy-cookiemonster: 48819-3895, 10m
  fanboy-social: 16165-9, 10m
  ublock-annoyances: 5702-501, 4h.51m
  CHN-0: 25493-156, 4h.51m
  RUS-0: 40170-569, 4h.51m
  adguard-cookies: 27997-66, 10m
  adguard-popup-overlays: 25037-1599, 10m
  adguard-mobile-app-banners: 4725-1068, 10m
  adguard-other-annoyances: 13734-314, 10m
  adguard-widgets: 2338-1, 10m
  easylist-annoyances: 4159-130, 10m
  [5 lists not shown]: [too many]
 default:
  user-filters: 2-0, never
  ublock-filters: 36006-456, 4h.51m
  ublock-badware: 7429-5, 4h.51m
  ublock-privacy: 651-0, 4h.51m
  ublock-unbreak: 2180-0, 4h.51m
  ublock-quick-fixes: 231-45, 5h.21m
  easylist: 72479-827, 4h.51m
  easyprivacy: 32835-821, 4h.51m
  urlhaus-1: 10925-0, 4h.51m
  plowe-0: 3721-1, 4h.51m
filterset (user): [array of 2 redacted]
trustedset:
 added: [array of 4 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 425 ms (selfie)
 maxAssetCacheWait: 247 ms
</pre>
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
This element is blocked by the AdGuard Base filter, please enable it.
By this rule:
`ground.news#?##__next > div.sticky:has(> div.sticky > div.flex > div.flex > a[href="/subscribe"])`

**Comment by aaronliu0130** [comment]
The subscription nag is from the website itself (covered under [Limitations and Exceptions](https://adguard.com/kb/general/ad-filtering/filter-policy/#ad-filters)), so I don't see why this is in AdGuard Base. (Your commit also doesn't appear to fix the subscription nag)
