### ISSUE TITLE
bild.de question

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#165614]
Hi!

I know that you can’t fix bild.de from anti-adblock, but can you tell me what custom filters I should add? I may be even custom rule?

I hope you will help me

**Comment by BlazDT** [comment]
||bilder-a.akamaihd.net/ip/js/ipdvdc/blockadblock.min.js
bild.de#%#(function(){var __de,__bild,__cmsKonfig;try{var b=function(a){a&&__bild!=a&&(__bild=a,__cmsKonfig=a.cmsKonfig,Object.defineProperty(a,"cmsKonfig",{get:function(){return __cmsKonfig},set:function(a){a&&a.system&&a.system.ad_smart_site_id&&(a.a={a:0,b:1},a.system.ad_smart_site_id=void 0);__cmsKonfig=a}}))},c=function(a){__de!=a&&(__de=a,b(__de.bild),Object.defineProperty(__de,"bild",{get:function(){return __bild},set:function(a){b(a)}}))};Object.defineProperty(window,"de",{get:function(){return __de},set:function(a){c(a)}})}catch(a){console&&console.error&&console.error(a)}})();
@@||smartadserver.com/diff/251/*$domain=bild.de 
@@/bild.js$domain=bild.de
@@/adplayer.css$domain=bild.de
@@||tagger.opecloud.com/asmi/*/tagger.js$domain=bild.de
@@||c.amazon-adsystem.com/aax2/apstag.js$domain=bild.de
@@||tags.tiqcdn.com/utag/axelspringer/bild-bild.de/prod/utag.js$domain=bild.de
bild.de#@#.ads
bild.de#@#.ad-wrapper
bild.de#@#.cbErotikContentbar15
bild.de#@#.contentbar
bild.de#@#.eyecatcher
bild.de#@#.footerbar
bild.de#@#.fullbanner
bild.de#@#.jetzt_aufnehmen
bild.de#@#.rectangle
bild.de#@#.servicelinks
bild.de#@#.tea-rectangle
bild.de#@#.txe
bild.de#@#.yield
bild.de#@$#.tea-rectangle { position: absolute!important; left: -3000px!important; }
bild.de#@$#.eyecatcher { position: absolute!important; left: -3000px!important; }
bild.de#$#.tea-rectangle { position: absolute!important; left: -3000px!important; display: block !important; }
@@||bild.de^$generichide
@@||smartadserver.com/diff/*/partners/$domain=bild.de
@@||smartadserver.com/diff/*/smartad.js$domain=bild.de
@@||sascdn.com^$domain=bild.de,script
