### ISSUE TITLE
New netflix tracker

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#165737]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

Latest

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

Netflix.com

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

logs.netflix.com appears in my dns logs. Can be blocked safely.

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I'm not sure whether the request shoud be blocked or not. Please provide HAR file with it.
You can collect it by following this [link](https://adguard.com/kb/guides/collect-har-file/). After you do that, send it to filters@adguard.com.

**Comment by jordanswrld94** [comment]
The requests are coming from my roku. Cant provide har file sorry :(

**Comment by zloyden** [comment]
Ok, I got it. Hm, what do such requests contain? Perhaps it's just telemetry. Will you have any breakage on Netflix if that's `logs.netflix.com` blocked?

**Comment by jordanswrld94** [comment]
No breakage detected here after adding tracker. My guess is another tracker because i didnt see that request start til today they must have added a new telemetry tracker

**Comment by zloyden** [comment]
I've added it for now. Thanks for your participation.

**Comment by PsycloneTM** [comment]
Blocking this URL makes my Netflix randomly start loading while watching shows. @zloyden
