### ISSUE TITLE
target.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#165778]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.15.1

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.target.com/c/christmas/-/N-5xt30

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

https://api.target.com/rum_analytics/
https://api.target.com/telemetry_data/v1/traces?key=

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reproduced. Need HAR.

**Comment by jordanswrld94** [comment]
Where is har located after i capture it? Sorry never did har before @Alex-302

**Comment by jordanswrld94** [comment]
https://www.mediafire.com/file/tx0zyuac9dse1ta/www.target.com.har/file

**Comment by jordanswrld94** [comment]
also this might be another tracker: https://api.target.com/consumers/v1/ttms/events?platform=web

**Comment by Alex-302** [comment]
HAR does not include all requests. Please open devtools and reproduce before exporting.

**Comment by jordanswrld94** [comment]
![Untitle 2d](https://github.com/AdguardTeam/AdguardFilters/assets/118186787/4d5f05b0-a942-4dde-aa5c-369c26e2af35)
![Untitled](https://github.com/AdguardTeam/AdguardFilters/assets/118186787/0db93e53-e880-408e-8d2f-7ddac6ee3e0f)
![Untitled3](https://github.com/AdguardTeam/AdguardFilters/assets/118186787/a59c79f9-d28f-4ae5-aaa6-1c2f0499152c)

**Comment by jordanswrld94** [comment]
all the requests i found with notepad++ idk why your not able to see them

**Comment by Alex-302** [comment]
I need content, not only url.
