### ISSUE TITLE
netflix app (windows)

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#165742]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.15.1

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.microsoft.com/store/productId/9WZDNCRFJ3TJ?ocid=pdpshare

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

||netflix.com/nq/msl_v1/cadmium/pbo_events/
||netflix.com/nq/msl_v1/cadmium/pbo_logblobs/

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I've changed the rules, the update should be available in 2-3 hours.
