### ISSUE TITLE
reddit.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#165996]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.15.1

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.reddit.com/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

https://www.redditstatic.com/shreddit/en-US/ad-event-tracker-7a83e6b0.js
​https://www.redditstatic.com/shreddit/en-US/w3-report-from-v2-event-50f5a9ea.js
​https://www.redditstatic.com/shreddit/en-US/telemetry-event-struct-d8880359.js
https://www.reddit.com/svc/shreddit/events

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
@jordanswrld94
Can you share some information how can i reproduce? (e.g, Reddit thread URLs)

**Comment by jordanswrld94** [comment]
Sure. Basically every reddit thread. Maybe its only reproduceable in usa? https://www.reddit.com/r/Adguard/comments/17v2ajq/does_adguard_block_telemetry_in_windows_11_and/

**Comment by piquark6046** [comment]
Blocking any of them causes an incorrect blocking.

**Comment by jordanswrld94** [comment]
Oh. I didnt reproduce that on my end. Sorry
