### ISSUE TITLE
https://www.iyf.tv

### ISSUE THREAD

**Issue by jason-lin008** [AdguardTeam/AdguardFilters#165907]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.209

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.iyf.tv/play/SiLAotPTzz8

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment>
Slide the video playback progress bar to the middle position and continue playing for more than 1 minute. The advertisement in the screenshot will appear.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![屏幕截图 2023-11-10 214853](https://github.com/AdguardTeam/AdguardFilters/assets/126739505/d761cea4-c37f-434d-bdb4-a62ca8e0b2c7)
</details>

<details><summary>Screenshot 2:</summary>

![屏幕截图 2023-11-10 214607](https://github.com/AdguardTeam/AdguardFilters/assets/126739505/748f6ef0-f992-41ef-8d43-5297674987a0)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please enable AdGuard Chinese filter.

**Comment by jason-lin008** [comment]
@Alex-302 yes, I have set the Chinese filter. The result is the same

**Comment by Alex-302** [comment]
Weird. Which Chinese filter version?
