### ISSUE TITLE
youtube.com tracker

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#165910]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.15.1

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.youtube.com/results?search_query=catdog

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

to reproduce. search something in the box and press search a couple times. it will appear in log.

|||youtube.com/pcs/activeview?xai=

here is har file with the tracker: https://www.mediafire.com/file/nbzo0j5ec95vjrx/www.youtube.com.har/file

![Untitled3](https://github.com/AdguardTeam/AdguardFilters/assets/118186787/7a97354b-9c37-4ddf-8346-29903b92f5df)

![Untitled](https://github.com/AdguardTeam/AdguardFilters/assets/118186787/292b4e91-9fb4-4680-95a1-d2017e61e17b)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It is blocked in your HAR. We need unblocked for analyze.
Added.
