### ISSUE TITLE
Cinemablend.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#166060]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.3

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.cinemablend.com/news/2495221/scary-movie-and-other-great-parody-movies-available-to-stream

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

eventsproxy.gargantuan.futureplc.com

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Blocked by TPF `||eventsproxy.gargantuan.futureplc.com/future.adtech.freyr.v1.PageViewEvent`
