### ISSUE TITLE
Localnews app ads

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#166149]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.3

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.novanews.localnews.en

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

Cant figure out how to block the ads. Seem like its different domains or something

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
Looks like this might do it. ||mob2.novanewsapp.com^

**Comment by zloyden** [comment]
Unfortunately, I can't check it on my end. The app requires an update to be installed, but this cannot be done through Google Play.

**Comment by zloyden** [comment]
> Looks like this might do it. ||mob2.novanewsapp.com^

I've seen the request from `mob.novanewsapp.com`.
Will it help if you block it?
Please check the rules one by one.
```adblock
||mob2.novanewsapp.com^
||mob*.novanewsapp.com^
```

**Comment by jordanswrld94** [comment]
||mob*.novanewsapp.com^ works

**Comment by zloyden** [comment]
Added it, thanks for checking this.
