### ISSUE TITLE
[iOS] tianya.cn/m - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1661]
the [link](http://www.tianya.cn/m/)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13378546/b771cb7e-de12-11e5-97f1-d8100bbee0b0.png)

![image](https://cloud.githubusercontent.com/assets/15856304/13378548/be92bf44-de12-11e5-9b71-cacb0027dc35.png)

</details>

GMU-623-70423

**Comment by Alex-302** [comment]
Maybe too much filters...
