### ISSUE TITLE
icloud.com

### ISSUE THREAD

**Issue by realizelol** [AdguardTeam/AdguardFilters#166135]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

0.108.0-b49

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari, other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gateway.icloud.com

### Ad Blocking

AdGuard Base filter

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

1. Seems like using parental control in AGH added some false-positives:
gateway.icloud.com - If I remember correctly this should be sync of pictures between device and icloud
setup.icloud.com - First-Time Setup check "persona/managed device [MDM]"

I don't know them but they are also appeared today:
probe.icloud.com - Geolocation anycast probing?
p59-fmf.icloud.com - FindMyDevice
p59-fmip.icloud.com - FindMyDevice
p59-fmfmobile.icloud.com - FindMyDevice
p59-caldav.icloud.com - CalDav Calendar.
p59-acsegateway.icloud.com - I've found anything detailed to this.

p59 is maybe a mirror near my location?

Apple itself doesn't let us know the exact purpose for the icloud subdomains:
https://support.apple.com/en-mide/HT210060
but here are some researched domains:
https://gist.github.com/joseconstela/a6e06ef9737e097eddcaf940ea313e38

2. Screenshots
<details><summary>Screenshot 1:</summary>

*None*

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. Cannot reproduce, and don't see icloud.com domains in parental control DB.
Maybe fixed at the moment?
