### ISSUE TITLE
Url tracking filter does not work on bilibili, it removes filtering params before loading, but the website add "vd_source" param back to ulr after loading

### ISSUE THREAD

**Issue by orbeta** [AdguardTeam/AdguardFilters#166199]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.12.2.1415

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.bilibili.com/video/BV1Sj411E7Mj/?vd_source=898sdufds8766ehhm

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, Legitimate URL Shortener

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter

### Language-specific

AdGuard Chinese filter, AdGuard Japanese filter, CJX's Annoyances List, EasyList China

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Self-destruction of third-party cookies

### Add your comment and screenshots

1. <comment>
For any bilibili video link, for example "https://www.bilibili.com/video/BV1Sj411E7Mj/?vd_source=898sdufds8766ehhm", it removes the vd_source at first and then adds vd_source part back to the url. After some testing, I found out that vd_source is just a unique id for any login user. This might be impossible to remove.
However if I am watching any video, clicking from side bar still includes tracking params.
like the screenshot below. I replaced the vd_source part with some random characters.
</comment>

2. <screenshot>
![CleanShot 2023-11-14 at 23 53 28@2x](https://github.com/AdguardTeam/AdguardFilters/assets/18389334/082bf4a1-2ae2-4003-a120-fecc04773007)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. It exists only in the address bar. It you will check with external web debugger, that parameter will be absent.

If I am wrong - please provide here more details.
