### ISSUE TITLE
Tubi

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#166180]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

N/A

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

N/A

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Add your comment and screenshots

Trackers:
ads.production-public.tubi.io
ads4.production-public.tubi.io

Suggested filter ads*.production-public.tubi.io

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
Videos play fine with these blocked. Tested extensively

**Comment by zloyden** [comment]
Where did you find the requests?

**Comment by jordanswrld94** [comment]
On my tubi smart tv app and also on apple tv app

**Comment by zloyden** [comment]
I've tried to find them in the android app, but there are no such requests.
Are they just for tracking or do they also provide ads?

**Comment by jordanswrld94** [comment]
Yea i think they only exist on apple and samsung tv afaik. And honestly dont know because ads still play fine
