### ISSUE TITLE
Adguard tracking protection filter rule breaks Netflix watched history

### ISSUE THREAD

**Issue by valynor** [AdguardTeam/AdguardFilters#166198]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

none, uBlock Origin 1.53.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

netflix.com

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Fanboy's Enhanced Tracking List, Fanboy's Anti-Facebook List

### Security

Online Malicious URL Blocklist

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

When I am watching media on Netflix.com on Brave Desktop I noticed that after November 2nd, 2023 the Netflix watch history did not update anymore. 

Going through the uBlock logger I found this rule getting enforced when I stop a video: 

```
Filter
||netflix.com*/msl*/*event*/
Filter list
[AdGuard Tracking Protection]
```

Temporarily disabling this rule via a dynamic URL filtering rule 
`www.netflix.com https://www.netflix.com/msl/playapi/cadmium/ xmlhttprequest allow`
immediately fixes the issue and media gets added to the watched list on Netflix again. 

Please modify/remove ` ||netflix.com*/msl*/*event*/` from you filter list. 

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
i can confirm that removing ||netflix.com*/msl*/*event*/ does fix watch history.

**Comment by Alex-302** [comment]
Removed as problematic. Nothing interesting there.
