### ISSUE TITLE
[iOS] www.xiamp4.com - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1662]
The [link](http://www.xiamp4.com)

![image](https://cloud.githubusercontent.com/assets/15856304/13378565/ff52b4a8-de12-11e5-8f40-e8126e342050.png)

GMU-623-70423

**Comment by Alex-302** [comment]
He uses too much filter. Limit for Safari is only 50000 rules. Ask him for total count.
