### ISSUE TITLE
DeviantArt broken by Other Annoyances filter

### ISSUE THREAD

**Issue by MIDG3Tp3nguin** [AdguardTeam/AdguardFilters#166214]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

ublock 1.53.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.deviantart.com/midgetpenguinai/art/Of-Elegance-pt2-993185310

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Social Widgets

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Widgets filter, Fanboy's Annoyances, EasyList Cookie List

### Add your comment and screenshots

1. <comment> going to individual image page to see the non-thumbnail images, the main image is hidden as well as all information for said image. This only happens with AdGuard – Other Annoyances enabled. Screenshot 1 is how it is supposed to look, screenshot 2 is how it looks with Other annoyances enabled.

2. Screenshots
<details><summary>Screenshot 1:</summary>
![Untitled-1](https://github.com/AdguardTeam/AdguardFilters/assets/146053268/501f69da-c082-4a6a-ae8f-bf549c4c663f

</details>

<details><summary>Screenshot 2:
![Untitled-2](https://github.com/AdguardTeam/AdguardFilters/assets/146053268/2c188c5e-6a38-40e0-addb-02bf2d419be9)
</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Full image and given link are working fine here in uBO. Which rule exactly breaks it from Other Annoyances?
