### ISSUE TITLE
kick out screen capture JavaScript

### ISSUE THREAD

**Issue by Chamiu** [AdguardTeam/AdguardFilters#166343]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

I've never seen a refusal to get such an operation situation, and it's equivalent to a declaration that a **virus** that captures screen in ms without any consent.

### Proposed solution

I feel the need to stop JavaScript to get cursor operations on the web page with filter.

### Additional information

In the electronic version of the Mainichi Shimbun, there was an article called "[Challenge to God: Aim at users with AI advertising, Japanese corporation representative of Apia Group](https://mainichi.jp/articles/20231015/k00/00m/040/073000c)" In this article, Koji Tachibana, the representative of Japan of the Apia Group, made a surprising statement.

>  You can determine how far you scrolled to the product page and the degree of interest in the product by the speed of scrolling. If you are interested in the product, you will read the product description carefully, so the scrolling will be slower. If you are interested, you can also trace around the product image with the cursor. Switching browser tabs is also an important element of knowing the level of interest.

I've never seen a refusal to get such an operation situation, and it's equivalent to a declaration that a **virus** that captures screen in ms without any consent.

**Comment by Alex-302** [comment]
They don't watch your screen. They track position of the page. If you know sites with tracking, please report them.
