### ISSUE TITLE
[iOS] www.bttiantang.com - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1664]
The [link](http://www.bttiantang.com/subject/4838.html)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13378616/78dafce4-de14-11e5-85cb-1a6b0d39b86a.png)
![image](https://cloud.githubusercontent.com/assets/15856304/13378625/b5788536-de14-11e5-91c4-adee30a747ef.png)

</details>

GMU-623-70423

**Comment by evgeniy-ADG** [comment]
The customer's filters for all his tasks
<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.77.77 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.84 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.67 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.24.16 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.88 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.2.44 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.46 Enabled=YES
ID1 Name="EasyList" Version=1.0.53.1 Enabled=YES
ID2 Name="ABPindo" Version=1.0.0.34 Enabled=YES
ID3 Name="Bulgarian list" Version=1.0.0.6 Enabled=NO
ID4 Name="EasyList China" Version=1.0.53.22 Enabled=YES
ID7 Name="Adblock Polska" Version=1.0.0.52 Enabled=YES
ID8 Name="EasyPrivacy" Version=1.0.52.89 Enabled=YES
ID0 Name="Norsk adblockliste" Version=1.0.0.1 Enabled=YES
ID2 Name="Fanboy's Annoyances" Version=1.0.53.13 Enabled=YES
ID3 Name="Fanboy's Social Blocking List" Version=1.0.53.1 Enabled=YES
ID!5 Name="Fanboy's Enhanced Tracking List" Version=1.0.1.23 Enabled=YES
ID 5 Name="Schacks Adblock Plus liste" Version=1.0.1.21 Enabled=YES
ID 7 Name="Adblock Warning Removal List" Version=1.0.53.6 Enabled=YES
ID!1 Name="Anti-Adblock Killer | Reek" Version=1.0.1.57 Enabled=YES
ID!6 Name="Adblock polskie reguły" Version=1.0.3.25 Enabled=YES
ID!7 Name="Adblock polskie reguły cookies" Version=1.0.0.91 Enabled=YES
ID!9 Name="ChinaList+EasyList" Version=1.0.0.35 Enabled=YES
ID"0 Name="CJXsAnnoyanceList" Version=1.0.0.23 Enabled=YES
</details>

**Comment by Alex-302** [comment]
@evgeniy-ADG 
I think too much filters enabled.
Which is summary count of rules?
