### ISSUE TITLE
Not blocking ADs in UWP apps

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#16649]
@aleksandarmomic commented on [Sun May 20 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2215)

Hello,
The app is not blocking ads in Modern UI apps (Awesome Tube in my case, Edge works). 
Here's a screenshot of browsing videos and having ads placed: [link](https://i.imgur.com/DEFzJ53.jpg)
My filter settings are: [link](https://i.imgur.com/wcsQad7.png)

I have explicitly added Awesome Tube to the list of Filtered Apps and I am using WFP driver.

### Steps to reproduce
1. Just open Awesome Tube app

### My environment

* OS: Windows 10 x64, v1803 Build 17134.48

---

@ameshkov commented on [Mon May 21 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2215#issuecomment-390579090)

Hi! You need to add this app to the filtered apps manually

---

@aleksandarmomic commented on [Mon May 21 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2215#issuecomment-390582746)

I stated above that I have explicitly added Awesome Tube to the list of Filtered Apps.

---

@ameshkov commented on [Mon May 21 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2215#issuecomment-390583257)

Got it. Moving this to the Filters repo -- the filters maintainers can handle it.

**Comment by Alex-302** [comment]
When I add *.exe from these folders, ads are blocked on my end
```
C:\Program Files\WindowsApps\2504freemp3music.MusicTubeforyoutube_1.1.4.0_x86__bsb37thm7x9z0
C:\Program Files\WindowsApps\76Chococode.BlueTube_5.1.31.0_x86__crad18n2hztbr
```
But Awesome Tube shows locally stored banner
![image](https://user-images.githubusercontent.com/8361299/40380477-e82b1fce-5e01-11e8-8a08-88a0f499e164.png)

**Comment by aleksandarmomic** [comment]
@TheHasagi So is it fixed? Is there any workaround or we have to wait for a new update?

**Comment by Alex-302** [comment]
@aleksandarmomic is this app added to the list of filtered apps?
https://github.com/AdguardTeam/AdguardFilters/issues/16649#issuecomment-391082098
