### ISSUE TITLE
After enabling EasyList China and then checking for update, it shows the error, "Filters cannot be loaded into Safari...".

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#16648]
@lancelot-moon commented on [Mon May 21 2018](https://github.com/AdguardTeam/AdguardForiOS/issues/785)

The issue didn't occur several days ago.
But it suddenly happened recently.
I intentionally disabled English filter for decreasing the amount of rules (22k rules).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/eVvkJIh.png)
</details><br/>

However, it would show the error as long as I enabled EasyList China and then checked for update.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/o8mEuyp.png)
</details><br/>

If I only disabled EasyList China, there was no the error.
It could successfully update filters for Safari.

B/R

---

@akira02 commented on [Mon May 21 2018](https://github.com/AdguardTeam/AdguardForiOS/issues/785#issuecomment-390555625)

Same issue here.

---

@lancelot-moon commented on [Mon May 21 2018](https://github.com/AdguardTeam/AdguardForiOS/issues/785#issuecomment-390570099)

@ameshkov 

Dear Sir,
I translate the comments on Taiwan app store.
Well, unstable VPN in another topic, which is really the most obvious shortcoming of AG Pro.

Another is what I reported here.
The error, "Filters cannot be loaded into Safari...". recently happened if enabling EasyList China.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/go2HYBq.png)
</details><br/>

---

@ameshkov commented on [Mon May 21 2018](https://github.com/AdguardTeam/AdguardForiOS/issues/785#issuecomment-390582823)

@Alex-302 plz take care

---

@ameshkov commented on [Mon May 21 2018](https://github.com/AdguardTeam/AdguardForiOS/issues/785#issuecomment-390582928)

Moving to the Filters repo

**Comment by Alex-302** [comment]
Excluded unsupported `$rewrite=` rules
