### ISSUE TITLE
Add phishing domains automatic block

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#166570]
Hi!

Can you add automatic phishing links blocking?

I think the best databases (updates regularly) is:
https://phishtank.org/
https://openphish.com/
https://github.com/mitchellkrogza/Phishing.Database

It is important because TOO many phishing links not blocking by AdGuard causing a risk for your customers.

Can you please take a look into this?

**Comment by DandelionSprout** [comment]
I can't say I'm particularly amazed by when users delete their GitHub accounts in the midst of active and recently made issue reports, but sure.

Phishtank: I can't in a hurry find any full lists of the domains they block.
Openphish: I found https://openphish.com/feed.txt. which should technically be able to work in AdGuard as a standalone list, but the list seems to be trivially small.
Phishing Database: This guy seems to be onto something: https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/phishing-domains-ACTIVE.txt . Normally I'd merrily have suggested at FiltersRegistry to add that list as a standalone, but that'd require AdGuard's regular blocking mode to properly treat raw domains, the way AdGuard DNS Blocking and uBlock Origin have done for years.

I should probably consider suggesting https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuard.txt on FiltersRegistry as well.

**Comment by Yuki2718** [comment]
Though I personally agree to
> It is important because TOO many phishing links not blocking by AdGuard causing a risk for your customers.

, both phishtank and openphish have occaional yet sometimes-serious false positive.

> Phishtank: I can't in a hurry find any full lists of the domains they block.

There was https://github.com/tg12/pihole-phishtank-list but seems updated was stopped on Feb.

**Comment by Alex-302** [comment]
Which domains blocked by phishtank.org and openphish.com but not by AdGuard?

**Comment by Jfydugkg** [comment]
@Alex-302 

> Can't open phishtank base
> 
> Details

[verified_online.csv](https://github.com/AdguardTeam/AdguardFilters/files/13418132/verified_online.csv)

Here is their database

> Which domains blocked by phishtank.org and openphish.com but not by AdGuard?

For example this one `https://exduswralolt.gitbook.io/us/`

Their database updates frequently, so it will be good to block the ones, that listed in their database

**Comment by piquark6046** [comment]
<details><summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/98787049/a2be06e6-61e1-4f6b-a842-5afd1bae2114)


</details> 


I can access the website with ProtonVPN KR#17 server.

**Comment by Alex-302** [comment]
Hm. We use phishtank.org DB

**Comment by DandelionSprout** [comment]
This may be slightly late, but I think "phishing-domain-ACTIVE" has its shares of problems too:

<details>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/22780683/f8517e26-c94b-4667-a67b-66bb46c91746)

</details>

Doesn't exactly help that it's the only time that list has kicked in with a warning page on my end. 😅

**Comment by Yuki2718** [comment]
Nearly every phishins lists have such FPs.
