### ISSUE TITLE
teknosa.com

### ISSUE THREAD

**Issue by hurgir** [AdguardTeam/AdguardFilters#166582]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.209

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.teknosa.com/apple-watch-series-8-gps-41mm-gece-yarisi-aluminyum-kasa-gece-yarisi-spor-kordon-p-145061656?shopId=teknosa&adp_cid=102849009815a352ebea5e1fdb21ff&adp_oid=5&adj_t=ssr0s2n&adj_campaign=paylaskazan_6792&adj_adgroup=Winfluenced&adj_creative=a2f31c32-d454-4ac5-9a5c-ed83c3435452_1016

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Add your comment and screenshots

1. <comment>
 The following url tracking parameters are not blocked

adj_creative
adj_adgroup
adj_t
adp_cid
adj_campaign

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
