### ISSUE TITLE
[Stealth mode] can't authorize on https://www.microsoft.com/ru-ru/windows/phones and others

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1666]
> Есть на портале такая штука как проверка покупок и выставление счетов. Находится по этому адресу https://account.microsoft.com/billing/orders#/ полностью блокируется получение информации Еще блокируется информация об аккаунте https://account.microsoft.com/ Получается Adgaurd полность блокирует работу домена https://account.microsoft.com/ Элементы страницы отображаются, но при получении информации происходит сбой. При внесении в исключение все отлично работает.

https://www.microsoft.com/ru-ru/windows/phones и др.
Не происходит вход после ввода данных. Идет перезагрузка страницы и сова нужно входить.
Также не отображается данное окно для входа.
http://prntscr.com/a8m18k

Помогает отключение "Блокировать куки". DHF-618-63568

**Comment by Alex-302** [comment]
@evgeniy-ADG 
на проверку:
@@||login.live.com/
@@||cdn.optimizely.com/js/$domain=account.microsoft.com
добавил. Если ок - закрывай

**Comment by Alex-302** [comment]
upd:
добавил третье правило

**Comment by Alex-302** [comment]
@evgeniy-ADG 
upd:
конечный вариант для проверки
```
@@||profile.microsoft.com/RegSysProfileCenter/
@@||microsoft.com/*/signin.aspx
@@||microsoft.com/*/signout.aspx
@@||microsoft.com/*?lc=
@@||profile.microsoft.com/RegSysProfileCenter/
@@||microsoft.com/*/signin.aspx
@@||microsoft.com/*/signout.aspx
@@||microsoft.com/*=wsign
```

**Comment by evgeniy-ADG** [comment]
Передано пользователю.

**Comment by Alex-302** [comment]
ок. Если всё норм - закрывай как fixed

**Comment by evgeniy-ADG** [comment]
> https://stores.office.com/myaccount/home.aspx?ui=ru-RU&rs=ru-RU&ad=RU&fromAR=1
> 
> При переходе по ссылке и входе в акк, старница несколько раз быстро перезагружается и выводится такое сообщение:
> http://prntscr.com/aa8ppl
> 

Если отключить "Блокировать куки" - все работает, выполняется вход

**Comment by evgeniy-ADG** [comment]
сюда те же фильтры пойдут?
