### ISSUE TITLE
Getting rid of JS rules, used to set a cookie

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#166756]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

We have ~317 JS rules, used to set a cookie. They can be found by:
`document.cookie =`
They must be replaced by `set-cookie` / `set-cookie-reload` / `trusted-set-cookie-reload` scriptlet rules.

There are many old rules, so first you need to check if the site is available, and then the need for the rule.

* For convenience, you can work in a separate browser
* Retrieve the list of domains, clean up duplicates and check if sites exist (if redirects occur, we assume that the site is dead).
* All such rules can be merged into one file, convert them to exception rules and import as custom filter. Then go down the list and check if the rules are needed (other types of problems not related to these rules are skipped).
* If the site is dead - add domains in the comment below. Then we will remove them from the filters.

In order not to overlap with other filter maintainers, it is desirable to perform batch rule replacement via pull-requests (5-10 rules per PR).

### Important
It should be checked with a Dutch or German VPN, because otherwise the cookie usage messages may not appear.

**Comment by piquark6046** [comment]
Dead domain: `first-comment.com` https://github.com/AdguardTeam/AdguardFilters/issues/83355

**Comment by piquark6046** [comment]
@Alex-302 How to fix if a rule mentions an issue in the closed AdGuard Forum?

**Comment by piquark6046** [comment]
Dead domain: `exrapidleech.info` https://github.com/jspenguin2017/uBlockProtector/issues/167

**Comment by piquark6046** [comment]
Dead domain: `yts.life` https://github.com/AdguardTeam/AdguardFilters/issues/43664

**Comment by piquark6046** [comment]
An inaccessible website: `fantasti.cc` https://github.com/AdguardTeam/AdguardFilters/issues/6540

**Comment by piquark6046** [comment]
An inaccessible website: `videowood.tv`

**Comment by piquark6046** [comment]
An inaccessible website: `mofosex.com` https://github.com/AdguardTeam/AdguardFilters/issues/6128

**Comment by piquark6046** [comment]
Dead domain: `JERUSALEMONLINE.com`
No records found.

**Comment by krystian3w** [comment]
> How to address if a rule mentions an issue in the closed AdGuard Forum?

maybe was copied to public archive.org?

**Comment by Alex-302** [comment]
> maybe was copied to public archive.org?

No(

**Comment by piquark6046** [comment]
Dead domain: `radioego.com`

**Comment by piquark6046** [comment]
Dead domain: `ddl-warez.to`

**Comment by piquark6046** [comment]
Dead domain: `filebase.ws`

**Comment by piquark6046** [comment]
Dead domain: `xbooks.to`

**Comment by piquark6046** [comment]
Dead domain: `ebonus.gg`

**Comment by piquark6046** [comment]
Dead domain: `megalyrics.ru`

**Comment by piquark6046** [comment]
Outdated domain: `daimler.com`

**Comment by piquark6046** [comment]
Inaccessible domain: `wakeboardingmag.com`

**Comment by piquark6046** [comment]
Dead domain: `2b-drinks.de`

**Comment by piquark6046** [comment]
Inaccessible domain: `mediamarkt.se`

**Comment by piquark6046** [comment]
Inaccessible domain: `prosiebengames.de`

**Comment by BlazDT** [comment]
> Inaccessible domain: `prosiebengames.de`

Site is accessible with German IP.

**Comment by piquark6046** [comment]
Inaccessible domain: `thewirecutter.com`
If you try to visit, you will be redirected to `nytimes.com`.

**Comment by Alex-302** [comment]
@piquark6046 *ping*
