### ISSUE TITLE
sso.teachable.com

### ISSUE THREAD

**Issue by maxicasa** [AdguardTeam/AdguardFilters#166748]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

AdGuard Home v0.107.40

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.calimove.com/

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

1. https://www.calimove.com/ uses the `teachable` platform for their courses. This week, the url `ssl.teachable.com` is blacklisted (why?) and the certificate is unreachable.

I tested with `Brave` browser for the navigation and also with Chrome. I am using https://hub.docker.com/r/adguard/adguardhome as dns resolver.

2. Screenshots
<details><summary>Certificate error:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/2181924/5fcf87f6-740c-40d6-bff3-2a71bb655481)

</details>

<details><summary>Adguard filter:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/2181924/78df846b-e225-4119-94a8-72695c83d2ca)

![image](https://github.com/AdguardTeam/AdguardFilters/assets/2181924/6c928751-6ffe-4ab7-8029-1a1f946ef3cf)

![image](https://github.com/AdguardTeam/AdguardFilters/assets/2181924/ff009945-e16b-47db-933a-ba64a9633368)

</details>
<details>
<summary>With the parental control disabled, the issue is solved:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/2181924/0506506a-398d-4e95-81cb-c68db7e770ec)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I don't see the site is blocked by our AdGuard DNS / Parental control.
If you still get it with the latest update, let me know. I'll reference the issue in a suitable rep.
