### ISSUE TITLE
[Stealth mode] ru2.forgeofempires.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1667]
https://ru2.forgeofempires.com

Нажимаем на "Играть", идет загрузка игры до 50% и нас снова выкидывает на начальную страницу.
http://prntscr.com/a8w9f3
http://prntscr.com/a8w9cg

Помогает отключение "Блокировать сторонние куки"
FDK-155-18069

**Comment by Alex-302** [comment]
@evgeniy-ADG 
добавил
@@||forgeofempires.com/game/json
если помогло - закрывай
