### ISSUE TITLE
tiktok.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#166716]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.53.5rc12

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.tiktok.com/@midr90s/video/7281814470437899525

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist

### Annoyances

AdGuard Cookie Notices filter, Fanboy's Annoyances

### Add your comment and screenshots

1. <comment>
Can't do CTRL+SHIFT+T while on video page

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I see that for some reason they block all keyboard inputs such as `CTRL + R`, `F5`, etc.
Fixed, update should be available in 2-3 hours.
