### ISSUE TITLE
https://www.adameve.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1669]
![image](https://cloud.githubusercontent.com/assets/15856304/13379156/f3d9e628-de26-11e5-9755-52aa093128d5.png)

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.77.38 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.4.50 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.7.79 Enabled=NO
ID Name="Filter for useful ads" Version=1.0.0.78 Enabled=NO
ID Name="Mobile ads filter" Version=1.0.1.90 Enabled=NO
ID Name="Safari Filter" Version=1.0.0.47 Enabled=YES
ID1 Name="EasyList" Version=1.0.53.33 Enabled=YES
ID8 Name="EasyPrivacy" Version=1.0.53.21 Enabled=YES
ID2 Name="Fanboy's Annoyances" Version=1.0.49.58 Enabled=NO

**Comment by Alex-302** [comment]
Can't reproduce. Can you check it?
