### ISSUE TITLE
https://www.reddit.com/ - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1670]
The [link](https://www.reddit.com/?count=26&before=t3_47r0zl)

Looks more like self-advertising
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/13379165/474aa8e2-de27-11e5-821f-28d6b9e69c5c.png)
</details>

**Comment by Alex-302** [comment]
This url is invalid now. I don't see this ad on other pages.
