### ISSUE TITLE
Базовый фильтр ломает pikabu и яндекс - диск (а может и ещё что-то)

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#167039]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [ ] AdGuard product version is up-to-date;
- [ ] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.11

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://pikabu.ru, https://disk.yandex.ru

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. С 24-го числа базовый фильтр (https://filters.adtidy.org/android/filters/2_optimized.txt) начал ломать pikabu.ru и disk.yandex.ru. Возможно поломано что-то ещё. На pikabu перестают работать скрипты и сайт практически полностью становится нефункциональным. На яндекс - диске отваливается скачивание файлов и веювинг содержимого архивов (да и всё остально, в принципе). Дезактивация подписки проблему убирает, подписка была самой свежей. Всё ломается при наличии её одной, даже если деактивировать прочие подписки. Добавление вышеозначенных сайтов в исключение ничего не даёт. Ломаются какие-то внешние элементы/скрипты. Юзается хром 90.0.4430.210 Safari с десктопным UA. Версии выше для меня неюзабельны по причине упоротого вкладочного интерфейса. Я бы галку, что "у меня браузер последней версии" и не ставил бы, равно как и галку напротив подтверждения, что "у меня последняя версия AdGuard" (т.к. на 5.1 выше не обновишь), но ваша форма иначе запостить не даёт. 

upd: Убрал.

upd: Ещё ломает https://profile.mts.ru - там бесконечный спиннер и страница не грузится. При отключенной подписке - всё ОК.

### Privacy

- [X] I agree to follow this condition

**Comment by Baltazar500** [comment]
Штош. Спасение утопающих, дело рук самих утопающих, да ? "Пишите на гит вместо форума", говорили они. Угу. Фидбэк здесь ненамного лучше.

Посредством tail и head путём сокращения диапазона строк я за полчаса выяснил, что за правило ломает сайты. Это, та - дам :

```

~vijesti.me#%#//scriptlet('prevent-element-src-loading', 'script', 'npttech.com')

```

А теперь объясните мне, какого хрена оно ломает pikabu, яндекс-диск, profile.mts.ru и прочие сайты ? Случаем не из-за "~" в начале ? Вроде в манах это значится как инверсия, которая должна применяться в связке с доменами. А тут домена нет. Т.е. оно применяется везде. Я правильно понимаю ?

Ещё момент. Это правило никак не фиксировалось в журнале фильтрации и "запеленговать" его, дабы определить причину в принципе было невозможно. Добавить игнор этого правила через "@@" тоже невозможно. Он тупо не работал в такой конструкции.

**Comment by zloyden** [comment]
Правило означало, что оно будет применяться везде, кроме `vijesti.me`. К сожалению, в таком виде оно вызывало проблемы и было переделано на более конкретное.

> Как мне исключить из фильтрации такое правило не обращаясь в саппорт (напомню, android 5.1, 3.6.11) ?

Добавив `@` в синтаксис правила. `~vijesti.me#@%#//scriptlet('prevent-element-src-loading', 'script', 'npttech.com')`, но это уже неактуально.
Рекомендуется обновить фильтры, поскольку ранее это было исправлено.

**Comment by Baltazar500** [comment]
>Правило означало, что оно будет применяться везде, кроме vijesti.me. 

Значит, я правильно всё понял.

>К сожалению, в таком виде оно вызывало проблемы и было переделано на более конкретное.

А может вам лучше сделать фильтрацию подписок, которые будут предотвращать такие нежданчики ? Да хоть банальный grep -v с регулярками (или на базе аналогичных инструментов). issue можете переоткрыть и переименовать - считайте это новым запросом. 

>Добавив @ в синтаксис правила. ~vijesti.me#@%#//scriptlet('prevent-element-src-loading', 'script', 'npttech.com'), но это уже неактуально.

Маны по составлению правил большие. Видать проворонил, как эти скриплеты экранировать. Буду теперь знать.

>Рекомендуется обновить фильтры, поскольку ранее это было исправлено.

Дык после того как написал на мыло, фильтры пофиксили за довольно короткий срок и проблема ушла.
