### ISSUE TITLE
AdGuard filters interfere with sending YouTube superchats.

### ISSUE THREAD

**Issue by erkinalp** [AdguardTeam/AdguardFilters#167193]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.209

### What type of problem have you encountered?

Website or app doesn't work properly, AdGuard gets detected on a website

### Which browser(s) do you use?

Firefox (121 beta)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://youtube.com

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Other

Filter unblocking search ads and self-promotion, AdGuard Experimental filter
[see the attached configuration for a full list of filters and other settings](https://github.com/AdguardTeam/AdguardFilters/files/13467407/20231123_143132_adg_ext_settings_4.2.209.json)

### Language-specific

AdGuard Turkish filter

### Add your comment and screenshots

1. Open a livestream in the watch view

2. Try to post superchar/super sticker/super thanks, click send

3.  Observe the payment request is blocked

From the browser inspector: 

scheme
	`https`
host
	`www.gstatic.com`
filename
	`/_/billing/_/js/{unique.id}`
 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please send report using AdGuard menu 
![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/6b376a67-d0dc-4bf2-bfd6-c5999f2556f1)

**Comment by Alex-302** [comment]
@erkinalp It is possible. Just start on any site and enter required URL. In this case all settings will be entered automatically.
