### ISSUE TITLE
Remove IPv64.net from Blocklist

### ISSUE THREAD

**Issue by ipv64net** [AdguardTeam/AdguardFilters#167322]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

IPv64.net on Blocklist

### Proposed solution

Hi Adguard Team,

can you please remove IPv64.net from the Blocklist.
The problem is solved and secured against reuse. 

Many Thanks

**Comment by Schnoopy84** [comment]
+1

**Comment by do4bmw** [comment]
+1

**Comment by ohnonick2** [comment]
+1

**Comment by do4bmw** [comment]
it is in this list

https://adguardteam.github.io/HostlistsRegistry/assets/filter_18.txt

but this is definitiv wrong

**Comment by Nollknolle** [comment]
+1

**Comment by zlElo** [comment]
+1

**Comment by androidseb25** [comment]
+1

**Comment by cocothenut** [comment]
+1

**Comment by Alex-302** [comment]
@do4bmw We use this list
https://github.com/drego85/PhishingArmyCore/
Better report them. I will unlock on our end.

**Comment by Alex-302** [comment]
Btw what exactly block the site? I see only redundant messages without info.

**Comment by Alex-302** [comment]
@Schnoopy84 @do4bmw @JonathanN1203 @ohnonick2 @itsmetin @Nollknolle @zlElo @androidseb25 @cocothenut ⬆️

**Comment by ipv64net** [comment]
Allegedly this block comes from the following website. 
https://www.phishtank.com/phish_detail.php?phish_id=8373402

**Comment by do4bmw** [comment]
> @ipv64net I mean which AdGuard service do you use?

selfhosted docker version

**Comment by Alex-302** [comment]
In adguard-dns.io `Phishing Army` is optional list.

**Comment by do4bmw** [comment]
yeah , its allready reported to them , i think you can close this topic
