### ISSUE TITLE
Add Phishing.Army blocklist to your SCAM sources

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#167354]
Hi!

Add https://phishing.army/download/phishing_army_blocklist_extended.txt as list of malware to automatic blocking. Capable with Adguard

It updates regularly.

Main page:
https://phishing.army/

Description:
> Generated every 6 hours from [PhishTank](https://www.phishtank.com/), [OpenPhish](https://openphish.com/),
[Cert.pl](https://www.cert.pl/ostrzezenia_phishing/), [PhishFindR](https://github.com/mitchellkrogza/Phishing.Database), [Urlscan.io](https://urlscan.io/) and [Phishunt.io](https://phishunt.io/) reports.
Each domain is analyzed to eliminate false positives,
through the Whitelist of [Anudeep](https://github.com/anudeepND/whitelist) and the [Alexa Rank](https://www.alexa.com/topsites)

**Comment by DandelionSprout** [comment]
Worth noting, to show that the user attempted the same thing on multiple repos: https://github.com/DandelionSprout/adfilt/issues/967

At least in my eyes personally, it seems increasingly unserious when GitHub users nowadays delete their accounts before anyone have even replied to their reports yet.

**Comment by Alex-302** [comment]
We use it.
