### ISSUE TITLE
[Question] Can you advise me user filter to block all HTTP (not HTTPS) requests?

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#167557]
Can you advise me user filter to block all HTTP (not HTTPS) requests?

**Comment by Hvufyxhcuv** [comment]
@DandelionSprout why do you think so?

P.S: I am using Tor on I’ll my browsers (not for anonymity, only like free VPN) and it is needed to prevent http attacks.

**Comment by DandelionSprout** [comment]
As I remember it, some HTTPS sites still tried to load HTTP scripts well into 2022. Depending on the exact site, this could result in e.g. a white background with all text and images on the left.

However, it seems during testing that almost all major sites I can remember, have resolved such scenarios by now.

If you want to be extra sure to avoid HTTP requests, you can supplement `|http://$all` with `$csp=upgrade-insecure-requests` and possibly `https://chromewebstore.google.com/detail/smart-https/cmleijjdpceldbelpnpkddofmcmcaknm`.

Alternately, there's https://support.mozilla.org/en-US/kb/https-only-prefs, which if Tor Browser also has that function, will avoid the need for any adblocker entries or extensions at all.

**Comment by Jbuvyfihkgtx** [comment]
> If you want to be extra sure to avoid HTTP requests, you can supplement `|http://$all` with `$csp=upgrade-insecure-requests` 

The whole rule for Adguard will be ```|http://$all$csp=upgrade-insecure-requests``` right?

> if Tor Browser also has that function, will in theory fix most of the situation, but I personally don't trust that mode very much.

I set up Adguard as system filter and redirected all traffic after Adguard through Tor (via Orbot). So I need to be sure that no other apps can connect via http, not only browsers.

P.S: Do you think reasonable to block ftp? Now already ftps exists.
P.P.S: Do you think reasonable to block .ru, .su  and other crappy TLD? I am not using them at all, so I think I can mitigate attack vector. Or it is paranoia?

**Comment by Alex-302** [comment]
You can also use our DNS with enabled `Block newly registered domains` option.
