### ISSUE TITLE
Прыгающий стиль!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardFilters#167517]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

 4.2.228

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://rezka.ag/

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Language-specific

AdGuard Russian filter, AdGuard Ukrainian filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Hide Referrer from third-parties (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests

### Add your comment and screenshots

Как показано на видео!
<details><summary>Screencast:</summary>

https://github.com/AdguardTeam/AdguardFilters/assets/34476664/ef90c8de-28a2-422c-8ded-218de65b51c6

</details>

### Privacy

- [x] I agree to follow this condition

**Comment by Spok1** [comment]
@zloyden, @Alex-302, посмотрите,пожалуйста в чём проблема.

**Comment by Alex-302** [comment]
Оформи нормально.

**Comment by Alex-302** [comment]
Мигание тут норма, т.к. брендирование удаляется.

**Comment by Alex-302** [comment]
Ну класс удаляется после его появления.

**Comment by Spok1** [comment]
@Alex-302 , удаляется,но меня не это интересует,а мигание при перезагрузке! Это баг,насколько я понимаю,такого поведения быть не должно.

**Comment by Alex-302** [comment]
Это не баг.

**Comment by Spok1** [comment]
> Это не баг.

А что тогда,если в гугл хром такое поведение не происходит!?

**Comment by Spok1** [comment]
Когда обновлений ждать фильтра?
