### ISSUE TITLE
Some scam websites are not flagged as dangerous

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#167762]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.209

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

v-hd.info, skachat-filmi.info, film-s.info, mobiletorrent.info, full-film.info, full-hd.info, rapid-torrent.top, kino-torrent.top, softif.site

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Security

Online Malicious URL Blocklist

### Add your comment and screenshots

The websites I mentioned pretend to offer options to download movies but actually contain links to softif.site that downloads an exe file which browser sometimes flags as dangerous.

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
All 9 of them seem to be hosted on `185.238.168.110`, making the potential for a mass domain block very high.

**Comment by andris86** [comment]
Update: download button now links to esoftw.site instead of softif.site. Both of these sites have the same IP address: `45.82.68.79`.

**Comment by Alex-302** [comment]
@Sergey-Lyapin What exactly?

**Comment by Sergey-Lyapin** [comment]
@Alex-302 
v-hd.info, skachat-filmi.info, film-s.info, mobiletorrent.info, full-film.info, full-hd.info, rapid-torrent.top, kino-torrent.top, softif.site, esoftw.site

**Comment by Sergey-Lyapin** [comment]
Blocked all domains hosted on 185.238.168.110
2actor.ru
999wr.ru
alexgames.ru
androidtorrent.info
astraal.ru
bigecho.ru
camrip.info
dvdrip.info
film-s.info
films-2021-online.ru
full-download.info
full-film.info
full-hd.info
get-file.info
hdrip.info
igrytorrent.ru
kino-nik.ru
kino-torrent.top
lider-tv.ru
loadmovie.ru
love-psy.ru
media-guild.ru
mobiletorrent.info
python-course.ru
rapid-torrent.info
rapid-torrent.top
realdvd.ru
skachat-filmi.info
textilpedia.ru
torrentnews.ru
v-hd.info
valvegames.ru

**Comment by DandelionSprout** [comment]
I still think it's better to say "The domains are blocked" instead of simply "Blocked", as it can be misunderstood as that the *user* think they may have been blocked from something of some sort. Though I suppose the context is clear in *this* particular case.
