### ISSUE TITLE
wenku.baidu.com

### ISSUE THREAD

**Issue by MHzsz** [AdguardTeam/AdguardFilters#16783]
![baidushurufa_2018-5-25_13-16-46](https://user-images.githubusercontent.com/39558996/40527315-3f0511c4-601e-11e8-927f-5025eed4030d.png)
![baidushurufa_2018-5-25_13-16-53](https://user-images.githubusercontent.com/39558996/40527320-43e480da-601e-11e8-8aef-cd7947c3e2f3.png)
![baidushurufa_2018-5-25_13-17-8](https://user-images.githubusercontent.com/39558996/40527321-4663d770-601e-11e8-9651-e18ac2e71ba9.png)

[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Issue URL***
https://wenku.baidu.com/view/8eaac0fb770bf78a6529548b.html 

* **Current behaviour**: I can browse the web normally only if I turn off "Stealth Mode". If it;s on, I can't see any useful information.

Information                            | Value
---                                    | ---
platform:                      | win 10
Browser:                               | Vivaldi
AdGuard version:                       | 6.2.437.2171
Stealth mode options (Windows only)    | on

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Which stealth mode options are enabled?

**Comment by MHzsz** [comment]
Thank you for help.







在2018年05月24 21时47分, "Alex"<notifications@github.com>写道:



Which stealth mode options are enabled?

**Comment by MHzsz** [comment]
I found that it was because of "referrer" and "search record" are on. @Alex-302 Thank you.

**Comment by Alex-302** [comment]
Ok. I recommend to disable these options.
