### ISSUE TITLE
lenta.ru broadcast popup

### ISSUE THREAD

**Issue by timur-davletshin** [AdguardTeam/AdguardFilters#167875]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock 1.54

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://lenta.ru

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

Ads via popup video block named "День инвестора. Стратегия 2026"

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Ads on this website are blocked by `AdGuard Russian language filter`, as far as I understand it is not available in uBlock.
Here is a link to the filter, you can add it as a custom filter:
https://filters.adtidy.org/extension/ublock/filters/1.txt
The full list of AdGuard filters is available in AdGuard extensions/applications. 

I'm not sure about the ads you described, if after adding the filter it still exists, please send a screenshot.

**Comment by timur-davletshin** [comment]
Seems like they dropped this popup already. It was really annoying.
