### ISSUE TITLE
https://stageacademy.mykajabi.com

### ISSUE THREAD

**Issue by hw121693** [AdguardTeam/AdguardFilters#167967]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

ADGuard DNS

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://stageacademy.mykajabi.com

### Ad Blocking

EasyList

### Add your comment and screenshots

1. [<comment>](https://stageacademy.mykajabi.com/login) is not an adult site

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/15042485/526c6e19-cf5a-429c-8cdb-16c444e2ce15)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Proofs?
