### ISSUE TITLE
wired.com

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#168140]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.228

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.wired.com/story/the-first-crispr-medicine-is-now-approved-in-the-us/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Security

Online Malicious URL Blocklist

### Add your comment and screenshots

See the screenshot. Suspicious scripts are indicated with red arrows.

![Screenshot 2023-12-09 162027](https://github.com/AdguardTeam/AdguardFilters/assets/43014154/d4e0629c-a995-4e5c-9e1b-52650641173a)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
These trackers are blocked, also blocking of GTM prevents loading.
