### ISSUE TITLE
[iOS] bostonglobe.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1681]
http://www.bostonglobe.com/metro/2016/02/27/pair-has-easy-access-office-they-helped-walsh-win/XW6yYww4KBUd3r23EQU87K/story.html
UWP-382-68390
<details>![image1](https://cloud.githubusercontent.com/assets/14153331/13415541/4f9e4862-df64-11e5-8f19-deea3973fa1c.PNG)
UWP-382-68390
</details>

**Comment by Alex-302** [comment]
Can't reproduce.
He can disable EasyList, because our English is a fork of it.
