### ISSUE TITLE
aliexpress.com

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#168114]
Очень большая просьба добавить в фильтр раздражителей внутреннюю рекламу на алиекспресс, это просто невозможно, оно так замусоривает поиск, что ничего не возможно найти
 <details>
 
![Беddddз имени-1](https://github.com/AdguardTeam/AdguardFilters/assets/19754243/52cdb2e0-e57e-48f0-bb73-b4471e5e97ef)
</details>

**Comment by Alex-302** [comment]
Там бывают не только самые дорогие предложения.
