### ISSUE TITLE
yandex.ru

### ISSUE THREAD

**Issue by ilyhryh** [AdguardTeam/AdguardFilters#168382]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard Content Blocker, AdGuard for Android, AdGuard for iOS, AdGuard for Mac, AdGuard for Safari, AdGuard for Windows

### AdGuard version

4.2.228

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://yandex.ru/search/?text=xbox+series+x&lr=213

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1.  Adguard removes not only ads, but useful for users snippets. As far as I know, ad blockers should only remove ads and irritating elements on a special filter list, without touching content without ads. Please make the filter more specific - so that it only cuts out ads, nothing else.

Related: https://github.com/AdguardTeam/AdguardFilters/issues/167324

3. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="1471" alt="Screenshot 2023-12-12 at 7 31 12 PM" src="https://github.com/AdguardTeam/AdguardFilters/assets/34672558/c183f215-1516-49ac-bbfe-144bbbd0bcf9">

</details>

<details><summary>Screenshot 2:</summary>

<img width="1471" alt="Screenshot 2023-12-12 at 7 35 55 PM" src="https://github.com/AdguardTeam/AdguardFilters/assets/34672558/cf4b76d6-6212-40b0-8fea-f34dc8f83a88">

</details>

<details><summary>Screenshot 3:</summary>

<img width="1471" alt="Screenshot 2023-12-12 at 7 33 38 PM" src="https://github.com/AdguardTeam/AdguardFilters/assets/34672558/1d0ae6ef-f242-46d8-b74f-bdf463a5c5a7">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by ilyhryh** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/167324

**Comment by Alex-302** [comment]
Спасибо, удалил.
