### ISSUE TITLE
[Windows] https://news.yandex.ru/quotes/1.html

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#1683]
Проблема в Internet Explorer
Не отображается график котировки.
https://www.youtube.com/watch?v=st-0-aqtSqE&feature=youtu.be
В других браузерах все нормально.

**Comment by Alex-302** [comment]
временное решение для пользовательского фильтра
```
@@||news.yandex.ru^$generichide
```

**Comment by Serzh-SUP** [comment]
@Alex-302 Да, работает. Закрывать?

**Comment by Alex-302** [comment]
нет
