### ISSUE TITLE
echo.msk.ru - Сетевизор doesn't work

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1684]
The [link](http://echo.msk.ru/programs/personalno/1717870-echo/#mmvideo)

Сетевизор работает только в Хроме. 

> Mozilla Firefox, реже Opera, ещё реже Maxthon .А вот сегодня открыл обсуждаемый с Вами сайт и сетевизор в Chrome...и всё работает,всё открылось при включённом Adguard! Перепроверил на остальных трёх вышеперечисленных браузерах- тот же чёрный экран плеера.

KWI-331-47791 - фильтры тут

**Comment by evgeniy-ADG** [comment]
Станно, у меня повторяется. Раньше не замечал такого, хотя эхо почти каждый день сомтрю. Недавно появилась проблема.

**Comment by Alex-302** [comment]
Чо то жлобствуют они - такое впечатление что плеер со всеми рекламными сетями работает.
Завтра поправлю.

**Comment by Serzh-SUP** [comment]
@Alex-302 У пользователя, по которому собственно создана заявка, проблема так и не пропала.

**Comment by evgeniy-ADG** [comment]
Она, похоже, снова появилась. У меня вот тоже черный экран в сетевизоре.

**Comment by Alex-302** [comment]
да вижу, пока не сообразил как поправить

**Comment by Alex-302** [comment]
@@||echo.msk.ru/videos/$genericblock
проверь такое у себя, не разблокировалось ли чего

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/17458814/a141038a-5c28-11e6-9130-b589161acb6e.png)
http://echo.msk.ru/tags/2673/

Вот с такой полосой белой теперь сетевизор. Если отключить АДГ, то все ок

**Comment by Alex-302** [comment]
Добавил в фильтр аналитики
```
@@||google-analytics.com/ga.js$domain=echo.msk.ru

```
@evgeniy-ADG проверь у себя ещё

**Comment by evgeniy-ADG** [comment]
It works, thank you.

**Comment by Alex-302** [comment]
Ok.
