### ISSUE TITLE
[iOS] gidonline.club - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1685]
![image](https://cloud.githubusercontent.com/assets/15856304/13436246/ff5d2c28-dfe6-11e5-9f2d-d53925bd8ea6.png)

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.78.24 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.89 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.72 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.87 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.31.40 Enabled=YES
ID Name="Mobile ads filter" Version=1.0.2.53 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.47 Enabled=YES
ID1 Name="EasyList" Version=1.0.53.38 Enabled=YES
ID5 Name="RU AdList" Version=1.0.53.42 Enabled=YES
</details>

NVM-324-63463

**Comment by Alex-302** [comment]
Чисто должно быть.
EasyList можно выключить, он входит в состав нашего англ фильтра.

**Comment by evgeniy-ADG** [comment]
Снова есть Вулкан.

**Comment by Alex-302** [comment]
Странно. В макосафари чисто.
