### ISSUE TITLE
tomshw.it - Amazon Ad - Custom filter not working

### ISSUE THREAD

**Issue by Sauzer909** [AdguardTeam/AdguardFilters#168504]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.2

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.tomshw.it/hardware/google-dice-che-i-problemi-di-drive-sono-risolti-bloccando-chi-sostiene-il-contrario

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Popups filter

### DNS filters

AdGuard DNS filter

### Language-specific

EasyList Italy, EasyList Spanish

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Remove X-Client-Data header from HTTP requests

### Add your comment and screenshots

loading any page from www.tomshw.it the amazon ads are not blocked for example on https://www.tomshw.it/hardware/google-dice-che-i-problemi-di-drive-sono-risolti-bloccando-chi-sostiene-il-contrario

Custom filtering rules such as ||[widgetbay.3labs.it/widgetbox/124](http://widgetbay.3labs.it/widgetbox/124) are not working

Screenshots

![Screenshot_20231214_093339](https://github.com/AdguardTeam/AdguardFilters/assets/153804964/6c813e76-56af-4661-9981-932b29fcce3b)

![Screenshot_20231214_093255_org mozilla firefox_edit_87533234838205](https://github.com/AdguardTeam/AdguardFilters/assets/153804964/d1f869ea-563e-4036-aa44-0518669e6866)

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
No ad shown at that location (hidden by Base filter and EasyList Italy for me).
Is HTTPS filtering enabled?

Mentioned url (widget box) is not even requested when I check the site without adblocker.

**Comment by Sauzer909** [comment]
Yes, https filtering is enabled as well as the lists you mentioned.

I blocked that widget box with uBlock Origin and it works fine.

**Comment by BlazDT** [comment]
@AdguardTeam/filters-maintainers can anyone reproduce ad?

**Comment by Alex-302** [comment]
I can't reproduce. Please report from AdGuard directly. It will load required for us settings.
