### ISSUE TITLE
Shellshock.io

### ISSUE THREAD

**Issue by AnmolrPunj** [AdguardTeam/AdguardFilters#168794]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

AdGuard Home 0.107.41 

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

shellshock.io

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

There are still ads left on the site even though i have adguard on also It was working fine litterly yesterday for me i have no idea what changed

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
DNS alone will not block these adverts. Added a rule for adverts to AdGuard blocker, will be available with the new filter update in 1-2 hours.
