### ISSUE TITLE
Shellshock.io Full Not able to function fully

### ISSUE THREAD

**Issue by AnmolrPunj** [AdguardTeam/AdguardFilters#168736]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

AdGuard Home 0.107.41 

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

shellshock.io

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

![image](https://github.com/AdguardTeam/AdguardFilters/assets/147607841/c3b147b7-fa85-4d06-a490-7fa7c20b0325)
When the button cricled in the image is clicked it is meant to let you select between 3 eggs normally without adgaurd you have to watch and ad but when you use ad gaurd i would expect it to work and just let me select immedietly. But the website gives me an error and it says i am using an adblocker it is a network error.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
They check their ad. Can't be bypassed using DNS.
