### ISSUE TITLE
Русский фильтр AdGuard (1_optimized.txt) ломает фильтрацию яндекс - рекламы.

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#168900]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [ ] AdGuard product version is up-to-date;
- [ ] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.11 [54]

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

zoneofgames.ru

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Language-specific

AdGuard Russian filter

### Add your comment and screenshots

1. Очередной косяк с вашими фильтрами. Русский фильтр AdGuard (1_optimized.txt) ломает фильтрацию яндекс - рекламы. Конкретно, реклама начинает лезть из-за фильтра
>||yandex.ru/ads/system/context.js$script,xmlhttprequest,redirect-rule=noopjs

Ещё в подписках есть подобные фильтры (их там хватает в разных подписках)

>@@||yandex.ru/ads/system/context.js$domain=russia-tv.online
>@@||yandex.ru/ads/system/context.js|$script,domain=playground.ru

которые попросту пропускают рекламу. Попытка полностью заблокировать непотрество яндекса фильтром "||yandex.ru/ads^" для сайтов, которых нет в исключениях подписок терпит фиаско. Это не работает, даже если отключить все подписки и оставить лишь собственные фильтры. Линки yandex.ru/ads/* в логе даже не маркируются как заблокированные и реклама вполне успешно пролезает.

Какого блин чёрта ?

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Ничего они не пропускают. Возьмите веб-дебагер и изучите.
`.ru/ads/` блокирует в т.ч. эти скрипты. `redirect-rule` тоже блокирует, просто иначе.

**Comment by Alex-302** [comment]
![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/4c54ad81-7534-42ff-a439-d4b954b1fce0)

Ни одного незаблокированного яндексного запроса (последний - аналитика стороннего расширения).

**Comment by Baltazar500** [comment]
>Ничего они не пропускают. Возьмите веб-дебагер и изучите.
.ru/ads/ блокирует в т.ч. эти скрипты. redirect-rule тоже блокирует, просто иначе.

Мы говорим о версии для ведра, а не для десктопа. Тем паче не самой новой версии, которую там просто не обновишь из-за старости ведра. Плюс с дебагом там есть определённые трудности. Тем не менее, если будет десктоп под рукой - гляну.

>Ни одного незаблокированного яндексного запроса (последний - аналитика стороннего расширения).

Я глубоко не копал и ZoG был дан лишь как частный пример. Там у меня блок сверху то появляется, то пропадает (но при этом место от него остаётся). Суть в том, что правило
>||yandex.ru/ads/system/context.js$script,xmlhttprequest,redirect-rule=noopjs
вступает в какой-то конфликт с правилами из основных подписок и я-реклама начинает пролезать. Это видно по банально полезшим видео-блокам и фреймам я-рекламы. То, что конкретно чудит это правило показывает его добавление в "собственные" при отключении "оптимизированной" подписки. Более наглядно наблюдал например тут https://boomdown.org/node/9413

**Comment by Alex-302** [comment]
Запишите HAR файл средствами Адгарда. Предварительно очистите кэш Адгарда, а сайт с проблемой откройте в новом приватном окне.

**Comment by Baltazar500** [comment]
Вообщем выяснилось, что фильтр

>||yandex.ru/ads/system/context.js$script,xmlhttprequest,redirect-rule=noopjs

конфликтует с глобальными http$replace - правилами, что у меня расположены в собственных правилах блокировки. Причём независимо от того, что они меняют в принципе. Любое правило http$replace (хоть http$replace=/abcd/efgh/) вызывает появление яндекс - рекламы при наличии правила выше. Почему так происходит - я без понятия. Думаю, вам лучше знать, где тут собака порылась. 

Если добавить исключение
>@@||yandex.ru/ads/system/context.js$script,xmlhttprequest,redirect-rule=noopjs

то http$replace - правила перестают конфликтовать с этим фильтром ввиду его отключения и я-реклама исчезает. 

HAR - файл нужно снимать ? Или просто проверите http$replace у себя ?

**Comment by Alex-302** [comment]
Отработало как надо

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/41a1ec35-3ee9-4918-ab91-34d5f5f879f2)

</details>



> HAR - файл нужно снимать ?

https://toolbox.googleapps.com/apps/har_analyzer/
важно отключить кэшироание в инструментах разработчика во вкладке Network.

**Comment by Baltazar500** [comment]
>Отработало как надо

А ревизия ведроидного adguard'а та же ? Для чистоты эксперимента.

>важно отключить кэшироание в инструментах разработчика во вкладке Network.

Так мне HAR снимать через коммутацию смарта по usb через десктопный хром или хватит встроенного функционала снятия HAR - дампов ?

**Comment by Alex-302** [comment]
> А ревизия ведроидного adguard'а та же ? Для чистоты эксперимента.

Даже с 3.7 работает исправно.




> Так мне HAR снимать через коммутацию смарта по usb через десктопный хром или хватит встроенного функционала снятия HAR - дампов ?

Без разницы.

**Comment by Baltazar500** [comment]
>Даже с 3.7 работает исправно.

А вы где смотрели ? Я на boomdown.org - там оно сразу вылезает если правила поперелючать. Дамп с адгарда в аттаче. Снят в режиме инкогнито.

[adguard.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/13883021/adguard.har.zip)

**Comment by Alex-302** [comment]
Лучше сюда напишите
https://github.com/AdguardTeam/AdguardForAndroid/issues

**Comment by Baltazar500** [comment]
>У вас вообще что-то непонятное.

Наконец до вас стало доходить моё замешательство.

>Адгард не кряченый случайно?

Нет. У меня лицензия. apk-ка официальная. Я мог бы и через личный кабинет или привязанную к нему почту общаться, но саппорт меня посылает на гитхаб.

>Может сломали фильтрацию.

Я пока вижу, что ломает фильтрацию вышеозначенный в начале треда фильтр вкупе с любым глобальным http$replace - фильтром в "своём" блок-листе. Причины сего мне не известны. Что-то где-то явно конфликтует. Но вот только что и где - ХЗ. Как выяснить конкретную причину конфликта - я без понятия. Я не разработчик. Пока самое "травоядное" решение проблемы, что видится мне сейчас - это добавить то правило в исключения до поры до времени, пока снова не вылезет подобный конфликт с ещё какой рекламой. А там уже походу дела смотреть.

**Comment by Alex-302** [comment]
> вкупе с любым глобальным http$replace - фильтром в "своём" блок-листе

А если так? (часть, которая ищет совпадение адреса сделал регулярным выражением)
`/http/$replace=/a/b/`

**Comment by Baltazar500** [comment]
>А если так? (часть, которая ищет совпадение адреса сделал регулярным выражением) /http/$replace=/a/b/

Идентичное поведение. Вырубаю все свои replace-правила, переделваю одно из своих правил под этот шаблон, проверяю - замена работает. Чекаю boomdown - реклама лезет. Вырубаю правило - реклама перестаёт лезть. Как-то так.

**Comment by Alex-302** [comment]
А эта версия устанавливается? Перед попыткой желательно забэкапить настройки.
https://www.apkmirror.com/apk/adguard-software-limited/adguard/adguard-4-0-64-release/

**Comment by Baltazar500** [comment]
До кучи вырубил все свои правила (3 десятка с лишним в сумме) и тройку воткнутых user.js, оставив только replace-правило. Результат тот же. Правило включено - яндекс не фильтруется. Выключено - всё ОК.

>А эта версия устанавливается? Перед попыткой желательно забэкапить настройки.
https://www.apkmirror.com/apk/adguard-software-limited/adguard/adguard-4-0-64-release/

Системный установщик на apk-ку ругаться из-за высокого api не стал (т.е. подходит) и предложил обновиться. Решил, что обновлю чуть позже (на днях) ибо если 4-ка действительно будет работать, то там надо будет ещё помаяться с сертификатом, переносом фильтров и userjs (буду настраивать с нуля и разбирать новый фкнкционал).

Примечательно, что менее месяца назад с саппортом был такой диалог :

>Скажите, у вас для Android 5.1 есть ерсия выше 3.6.1.11/54 ? Ночная/бета/тестовая ?

>На данный момент, поддержка версий Android старше Android 7.0 прекращена. Если у вас работает приложение на версии 3.6.1.11/54 и не предлагает вам обновиться, то значит, что это последняя доступная для вас версия.

Т.е. я тогда честно хотел апдейтнуть adguard, но мне сказали "низзя", ну я и забил. А на деле оказалось, что вполне можно ...
