### ISSUE TITLE
Remove "Sponsored" results from the Portuguese website PCDiga.com

### ISSUE THREAD

**Issue by Chillsmeit** [AdguardTeam/AdguardFilters#168948]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Basically what the title says, the website [https://www.pcdiga.com](https://www.pcdiga.com) which is one of the main tech/computer stores in the country has new "sponsored" results mixed with the rest.
Even if you use price filters, or order the results from low to high price, the sponsored posts still show up and completely ignore the filters, usually it's an entire row of sponsored results per 2 normal rows. 
You see this can get pretty annoying and confusing.

(Patrocionado means Sponsored in English btw)

![2023-12-21_13-38](https://github.com/AdguardTeam/AdguardFilters/assets/93094077/388e5210-9178-4f77-bdfa-556053803a13)

### Proposed solution
I came up with this and it works, but there might be a better way to do it though:
`
pcdiga.com##div.rounded-r4.md\:p-3.p-1\.5.bg-background-off.flex-col.flex:has-text(/Patrocinado/)
`

**Comment by zloyden** [comment]
Well, I don't see these items on my end with a Spanish IP.
However, we don't remove such elements because other users won't see them unless they disable protection.

**Comment by zloyden** [comment]
> I came up with this and it works, but there might be a better way to do it though:
pcdiga.com##div.rounded-r4.md\:p-3.p-1\.5.bg-background-off.flex-col.flex:has-text(/Patrocinado/)

You can use `:contains` instead of the modifier above like this.
```adblock
pcdiga.com#?#.rounded-r4.md\:p-3.p-1\.5.bg-background-off.flex-col.flex:contains(Patrocinado)
```
