### ISSUE TITLE
camwhores.video

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#169363]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.54.1rc1

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.camwhores.video/videos/13350542/demi-morgan-extreme-fucked-facialed-129397/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, Fanboy's Annoyances, EasyList Cookie List

### Add your comment and screenshots

1. <comment>
Unhidden ad placeholders on site
2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot from 2023-12-27 02-32-35](https://github.com/AdguardTeam/AdguardFilters/assets/89158249/5de071ba-3124-4b24-8d5c-3f2beaa191b7)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
