### ISSUE TITLE
moreamateurs.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#169362]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.54.1rc1

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://moreamateurs.com/videos/33497/kitty-mya69-2020-03-26-06-57/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, Fanboy's Annoyances, EasyList Cookie List

### Add your comment and screenshots

1. <comment>
Ad image is loaded on the page
`||moreamateurs.com/v/image.php`
2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot from 2023-12-27 02-29-29](https://github.com/AdguardTeam/AdguardFilters/assets/89158249/eebd2118-6646-4f8d-a35e-2aefa08403be)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.

**Comment by Sonic5435325** [comment]
Is the image going to get blocked with dynamic filters?

**Comment by zloyden** [comment]
It's blocked by the css rule. First, I saw that the images had low size, but now some of them have ~ 100Kb - will also block it.

**Comment by Sonic5435325** [comment]
Thanks, is the Fapello one too minor?

**Comment by zloyden** [comment]
Yeah, If you meant the ad image.
