### ISSUE TITLE
fapello.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#169360]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.54.1rc1

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://fapello.com/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist

### Annoyances

AdGuard Cookie Notices filter, Fanboy's Annoyances, EasyList Cookie List

### Add your comment and screenshots

1. <comment>

Unhidden ad box
`fapello.com##.wbar` (Hiding it will cause a gap to appear on top of the page, not sure what would be the optimal way to disable that for AdGuard)
`||fapello.com/assets/images/welcomebar5.png`

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot from 2023-12-24 18-07-06](https://github.com/easylist/easylist/assets/89158249/e17605ab-7209-4af0-885f-edced2c3e13c)
![Screenshot from 2023-12-24 18-10-24](https://github.com/easylist/easylist/assets/89158249/c486646b-3965-4dba-8487-613a6ca3441c)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
