### ISSUE TITLE
rakuten.tv

### ISSUE THREAD

**Issue by Andreastar669** [AdguardTeam/AdguardFilters#169369]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.16.0 (4542)

### What type of problem have you encountered?

Website or app doesn't work properly, AdGuard gets detected on a website

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.rakuten.tv/fi/player/movies/stream/hamburger-hill

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Language-specific

Adblock List for Finland

### Add your comment and screenshots

1. Rakuten.tv/fi detects Adblock and wont play video.
If you unblock tv.springserve.com for rakuten.tv/fi it will work

3. Screenshots

</details>

<details><summary>Screenshot 1:</summary>

![Näyttökuva 2023-12-27 110905](https://github.com/AdguardTeam/AdguardFilters/assets/154970198/4fc6d290-c90d-4d62-9dc4-074ee0392da2)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
