### ISSUE TITLE
Ads: www.bilibili.com

### ISSUE THREAD

**Issue by 0x391F** [AdguardTeam/AdguardFilters#169371]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.54.0

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.bilibili.com/video/av14064273/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Chinese filter

### Add your comment and screenshots

1. Remain ad

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot_20231227_175356](https://github.com/AdguardTeam/AdguardFilters/assets/56181919/abb4055f-c115-4ee4-a223-6ccab17d8b8a)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Not reproduced it on my end. Try to update the filters, clear browser data, restart it, open the site.
