### ISSUE TITLE
doctolib.fr

### ISSUE THREAD

**Issue by NotaInutilis** [AdguardTeam/AdguardFilters#169456]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBo

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.doctolib.fr/account/appointments

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances

### Add your comment and screenshots

1. <comment> Download app banner. This one seems to only show up when logged in.
Filters that I use to hide this:
```
doctolib.fr##.MuiModal-root:has-text(application)
doctolib.fr##.MuiModal-root:has([href*="play.google"])
```

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot Doctolib](https://github.com/AdguardTeam/AdguardFilters/assets/9675966/d781d71c-d910-4901-ab60-59cbe03c59fb)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Registered. Cannot reproduce.

**Comment by NotaInutilis** [comment]
What kind of additional information couId I provide that would be useful in order to reproduce the issue?

**Comment by Alex-302** [comment]
Could you please record a video in private tab? 
Auth process can be stripped, if email/name is visible.
You may send it to filters@adguard.com + link of this issue.
