### ISSUE TITLE
Website breakage in Safari

### ISSUE THREAD

**Issue by max-adblock** [AdguardTeam/AdguardFilters#169481]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS, AdGuard for Safari

### AdGuard version

latest

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.dogdrip.net/

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots
![KakaoTalk_Photo_2023-12-28-18-12-28](https://github.com/AdguardTeam/AdguardFilters/assets/155061453/f537a93e-33dc-414c-9628-09d2349ea529)
![KakaoTalk_Photo_2023-12-28-18-20-10](https://github.com/AdguardTeam/AdguardFilters/assets/155061453/56780e49-5576-4ea3-a8f6-766273e49a92)

### about issue
- following websites are broken after 15~20 seconds.
    - dogdrip.net
    - loawa.com
    - mlbpark.donga.com
    - m.ygosu.com
    - m.inven.co.kr
- it only happens in iOS and macOS Safari browser.

### Problem
- This issue is resolve when i disable this filter: https://filters.adtidy.org/ios/filters/2_optimized.txt
- These lines makes website breakage
   - `||html-load.com^$popup`
   - `||07c225f3.online^$popup`
   - `||content-loader.com^$popup`

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
@max-adblock Please install [microShield userscript](https://github.com/List-KR/microShield).

**Comment by piquark6046** [comment]
You can refer [this document](https://community.list-kr.com/docs/AdGuard/Userscripts/microShield) if you can understand the Korean language.
