### ISSUE TITLE
videomega.tv

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1695]
http://videomega.tv/?ref=1wuHi8R2eZZe2R8iHuw1
![screen shot 2016-03-04 at 12 49 13 am](https://cloud.githubusercontent.com/assets/14153331/13512397/1065597e-e1a3-11e5-88ae-f41f976fb95d.png)
XPN-914-93622

**Comment by Alex-302** [comment]
@Bohdan-SUP 
Video doesn't works. Need new link.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
bump

**Comment by Bohdan-SUP** [comment]
Can't reproduce as well. Asked user for confirmation.

**Comment by evgeniy-ADG** [comment]
@Alex-302 

> Hello,
> It was working fine for days now but i just checked and the same problem is
> happening again. That's odd. I thought Adguard filters should normally take
> care of it or it can't bypass videomega.tv? kindly let me know of any
> updates to this and i truly appreciate you got back to me on this subject.

**Comment by Alex-302** [comment]
Ask him for other links. Example doesn't work on my end.

**Comment by vozersky** [comment]
@Alex-302 
Examples:
http://videomega.tv/?ref=9r9sx4xGOGGOGx4xs9r9
http://videomega.tv/?ref=Wjn0XfZp5775pZfX0njW

Screenshot https://dl.dropboxusercontent.com/u/57517781/1.PNG

**Comment by Alex-302** [comment]
@vozersky 
still can't reproduce.
Ask him for filters list and remote access.

**Comment by evgeniy-ADG** [comment]
@Alex-302 @vozersky 
I can
![image](https://cloud.githubusercontent.com/assets/15856304/13899566/f61e79a2-edf9-11e5-80d1-7158f2b5944e.png)

Please check a reply from our customer XPN-914-93622

**Comment by Alex-302** [comment]
>>>English filter enabled and other filters also enabled.
this?

@evgeniy-ADG 
could you provide me remote access?

**Comment by evgeniy-ADG** [comment]
Before you get back to me on the videomega problem, I found a way to make
it work now on adguard adding these to the user filters:
@@||adnostri.com^$domain=videomega.tv
@@||adv4biz.com^$domain=videomega.tv

It was through this forum I found this workaround for now.
https://github.com/gorhill/uBlock/issues/1194

Commented by evgeny to bohdan Yesterday, 18:01

**Comment by evgeniy-ADG** [comment]
@Alex-302 please check above. I you need a tv, please contact me on skype

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Does this player works(play video) without Adguard?
