### ISSUE TITLE
patreon.com

### ISSUE THREAD

**Issue by NotaInutilis** [AdguardTeam/AdguardFilters#169741]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBO latest

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.patreon.com/posts/this-years-most-95119794

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances

### Add your comment and screenshots

ANNOYANCE, MOBILE APP BANNER

1. A banner for the patreon mobile app appearing on the bottom right of the desktop site. The text changes depending on the page it appears on (watch videos, follow creators, etc.)

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot 2024-01-01 at 23-04-46 This Year's Most Innovative Game is  Game Maker's Toolkit (GMTK)](https://github.com/AdguardTeam/AdguardFilters/assets/9675966/1135edd6-214d-423e-9f11-49aabfb368cc)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
Already fixed.
