### ISSUE TITLE
honkailab.com breakage (Safari, MAC & IOS)

### ISSUE THREAD

**Issue by xnusnim** [AdguardTeam/AdguardFilters#169748]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard Content Blocker, AdGuard for iOS, AdGuard for Mac, AdGuard for Safari

### AdGuard version

1.11.16

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://honkailab.com/

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. <comment> When I turn on adguard in honkailab, the screen looks broken. This problem only happens on IOS and MAC safari.
<details><summary>Screenshot 1: </summary>

<img width="1512" alt="스크린샷 2024-01-02 오전 11 09 33" src="https://github.com/AdguardTeam/AdguardFilters/assets/81290656/28d71c33-33b7-49bb-a446-a39581b5bc9d">

</details>

<details><summary>Screenshot 2:</summary>

<img width="410" alt="스크린샷 2024-01-02 오전 11 18 49" src="https://github.com/AdguardTeam/AdguardFilters/assets/81290656/2ae337e4-721d-47ef-88fe-c1d46f533a9b">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
@xnusnim 
Please refer https://github.com/AdguardTeam/AdguardFilters/issues/167048.

**Comment by piquark6046** [comment]
For its installation guide written in Korean language, please refer [here](https://community.list-kr.com/docs/AdGuard/Userscripts/microShield).
@xnusnim

**Comment by xnusnim** [comment]
@piquark6046
If you wait for about 15 seconds on the website, an error occurs that breaks the screen.
These problems are likely to cause users to leave.
I will use microShield, but please do not experience problems for users.
