### ISSUE TITLE
trello.com

### ISSUE THREAD

**Issue by NotaInutilis** [AdguardTeam/AdguardFilters#169745]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBo latest

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

https://trello.com/b/4e2O7tge/revolt-roadmap

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List

### Add your comment and screenshots

1. <comment> Annoyance, mobile app banner on firefox android.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot_20240102-005948_Trebuchet](https://github.com/AdguardTeam/AdguardFilters/assets/9675966/99a944e8-40fe-481a-b6cb-dbb0eeec3e87)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
For uBO add to user filter
`trello.com##+js(trusted-set-local-storage-item, mobilePromptClosed, $now$)`
and enable trusted scriptlets in uBO settings.

**Comment by Alex-302** [comment]
In advanced settings `trustedListPrefixes ublock- user-`
