### ISSUE TITLE
"geo" cookie at playvalorant.com obtains user's country name

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#169860]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.241

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

playvalorant.com

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Add your comment and screenshots

Cookie `geo` at playvalorant.com obtains user's country name without user's consent.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It is public info, obtained from a visitor's IP.
