### ISSUE TITLE
lostfilm.download

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#169883]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [ ] AdGuard product version is up-to-date;
- [ ] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.11

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

httpslostfilm.download

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

1. Докиньте к фильтрам лостфильма (www.lostfilm.tv) зеркало lostfilm.download

### Privacy

- [X] I agree to follow this condition

**Comment by Baltazar500** [comment]
Да накиньте вы уже лишний хост к правилам. А то бот уже грозится тред закрыть. Я у себя этот "Мир танков" заблокировал и вернул нормальный фон, так что мне в принципе ни жарко от этого, нихолодно. Просто не хочется захламлять "собственные фильтры" почём зря.

**Comment by Alex-302** [comment]
У меня вот так выглядит

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/a1e3a4b9-8a19-45b9-9228-77d243b47359)


</details>

**Comment by Baltazar500** [comment]
>У меня вот так выглядит

"Танки" уже побились какими-то другими фильтрами. Или их убрали. На момент написания - были. Плашку сверху уберите - на .tv она фильтруется. Сейчас там реклама сериала, а потом обычная реклама.

**Comment by Alex-302** [comment]
После обновления фильтров проверьте.

**Comment by Baltazar500** [comment]
Плашка ушла. Внешний вид теперь не отличается от .tv
