### ISSUE TITLE
[iOS] mobile.nytimes.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1701]
http://mobile.nytimes.com/2016/03/03/opinion/donald-trump-and-reconstruction-era-politics.html
![img_4769](https://cloud.githubusercontent.com/assets/14153331/13547203/e89f1342-e2d0-11e5-946b-3c7bed457f5e.jpg)

PGY-968-40337

**Comment by Alex-302** [comment]
I don't see this ad without filtering. Ask him for check this mobile link on desktop.
