### ISSUE TITLE
vidmoly.to (The Filter rule confusing)

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdguardFilters#170183]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

v4.2.241

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://vidmoly.to/embed-jwakm163dtn0.html

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Language-specific

AdGuard Turkish filter

### Add your comment and screenshots

See the video, why does this happen?

<details><summary>Video</summary>

https://github.com/AdguardTeam/AdguardFilters/assets/56846906/0644546c-2cc5-432e-807b-0319937291e1

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
> This is basically an alias to [$redirect](https://adguard.com/kb/general/ad-filtering/create-own-filters/#redirect-modifier) since it has the same "redirection" values and the logic is almost similar. The difference is that $redirect-rule is applied only in the case when the target request is blocked by a different basic rule.

https://adguard.com/kb/general/ad-filtering/create-own-filters/#redirect-rule-modifier
