### ISSUE TITLE
utm_content parameter is not removed from deezer

### ISSUE THREAD

**Issue by fenopa** [AdguardTeam/AdguardFilters#170206]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.deezer.com/en/track/143032368?utm_content=track-143032368&deferredFl=1

### Ad Blocking

EasyList

### Privacy

AdGuard URL Tracking filter

### Add your comment and screenshots

utm_content parameter is in https://github.com/AdguardTeam/AdguardFilters/blob/master/TrackParamFilter/sections/general_url.txt but it's not being removed from deezer URLs: https://www.deezer.com/en/track/143032368?utm_content=track-143032368&deferredFl=1

it's not on allowlist so I don't understand why it's not being removed.

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
What appears the situation, is that Deezer has somehow managed to use *2* question marks before the `utm` part. I can try to fix the part in *Dandelion Sprout's Annoyances List*, hopefully.

**Comment by zloyden** [comment]
Looks like a bug in the extension. We already have the rule for this, that works correctly in the app.
The similare case https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2558. You can leave a comment there or create a new task in the repo https://github.com/AdguardTeam/AdguardBrowserExtension/.

**Comment by gwarser** [comment]
The filter is missing in list compiled for uBO https://filters.adtidy.org/extension/ublock/filters/17.txt :

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/886325/dcc77b6d-c4f7-4794-96ae-86a1bc9bd090)
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/886325/33ea8202-8941-4edd-8664-49da8d4639c3)

**Comment by gorhill** [comment]
Looks like the issue is the regex to detect `$content` modifier is improperly detecting the filter as one using `$content`, <https://github.com/AdguardTeam/FiltersCompiler/blob/v1.1.121/src/main/platforms-config.js#L163-L165>:

```js
const CONTENT_MODIFIER_PATTERNS = [
    '\\$(?!((path|domain)=.*])).*content(,|$)',
];
```

Test: <https://regex101.com/r/XSTWoH/1>

This affects not just `utm_content`, but any filter which ends with `content`: `$removeparam=itm_content`, `$removeparam=mtm_content`, etc.

Since AdGuard for Chromium does not support `$content` option, it's seems to also be affected:

![image](https://github.com/AdguardTeam/AdguardFilters/assets/585534/2d4f6984-647e-4124-ba8f-0c76cd66af5f)

**Comment by zloyden** [comment]
It was fixed, update the filters. Thanks for letting us know and for your investigation @gorhill.

<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/33488229/c0af7efa-76c4-44ad-a4ec-b71eb43b0fb1)

</details><br/>
