### ISSUE TITLE
VG.no - Blocked videos (AdGuard Cookie Notices filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#170285]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.55.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://tv.vg.no/ (probably geo restricted)

https://vg.no/i/762Qv8/

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Cookie Notices filter

### Affected site:
`https://www.vg.no/`

### Issue:
Some videos won't load, due to a blocked cookie consent, which needs to be accepted first.

### Examples:
`https://tv.vg.no/` (probably geo restricted)

`https://vg.no/i/762Qv8/`

### Screenshots:
* **With blocked cookie consent:**

![filterissue-vg3](https://github.com/easylist/easylist/assets/9382674/6789847f-3b9f-406e-8229-fe4f33e35a7a)

* **After the cookie consent has been accepted:**

![filterissue-vg4](https://github.com/easylist/easylist/assets/9382674/cde055a1-3424-4015-94dc-a24059337ba8)

### Problem filter:
* **AdGuard Cookie Notices filter**

### Problem rule:
```
speisekarte.de,businessinsider.com,historyextra.com,finn.no,vg.no,aftenposten.no,tek.no,vglive.no,bt.no,telegraph.co.uk##div[id^="sp_message_container_"]
```

### Possible fix:
```
- speisekarte.de,businessinsider.com,historyextra.com,finn.no,vg.no,aftenposten.no,tek.no,vglive.no,bt.no,telegraph.co.uk##div[id^="sp_message_container_"]

+ speisekarte.de,businessinsider.com,historyextra.com,finn.no,aftenposten.no,tek.no,vglive.no,bt.no,telegraph.co.uk##div[id^="sp_message_container_"]
```

### Other problem filters:
* ~~**EasyList - Cookie Notices** https://github.com/easylist/easylist/issues/18245/~~ _**(FIXED)**_
~~`||cmp.vg.no^`~~

* **I don't care about cookies** **_(NOTIFIED)_**
```
/wrapperMessagingWithoutDetection.js$domain=vg.no|boerse.de|bt.no|liberation.fr

cmp.$domain=telerama.fr|courrierinternational.com|vodkaster.com|svd.se|histoire-et-civilisations.com|malservice.aftonbladet.se|vg.no|tv.nu|tek.no|finn.no|pent.no|godt.no|aftenposten.no|omni.se|e24.no|helthjem.no|minmote.no|aftenbladet.no|klart.se
```

### Temp fix:
~~`vg.no#@#div[id^="sp_message_container_"]`
`@@||cmp.vg.no^`
`||cmp.vg.no^*/metrics/$important`~~

### Updated temp. fix (for uBO):
Until everything has been resolved, this should cover the current issues for all of the mentioned problem filters, in a more convenient way:
```
vg.no##div[id^="sp_message_container_"]
cmp.vg.no##+js(trusted-click-element, .btns-container > button[title="Tilpass"])
cmp.vg.no##+js(trusted-click-element, .message-row > button[title="Avvis alle"], , 2000)
@@||cmp.vg.no^
||cmp.vg.no^*/metrics/$important
@@||privacy-mgmt.com/mms^$domain=vg.no
```
(Credit for the above `##+js` rules goes to **piquark6046**)

--

### System info:
* OS/version: Windows 10 Pro 22H2 (x64)
* Browser/version: LibreWolf v121.0-1 (x64) [Tracking Protection = Standard]
* Adblock Extension/version: uBlock Origin v1.55.0

### Privacy

- [X] I agree to follow this condition

**Comment by superlex** [comment]
@THEtomaso 
Thanks.

Could you try
```
cmp.vgn.no#%#//scriptlet('trusted-click-element', 'button.sp_choice_12[title="Tillpass"]')
cmp.vgn.no#%#//scriptlet('trusted-click-element', 'button.sp_choice_type_REJECT_ALL', '', '500')
```
, please?

**Comment by superlex** [comment]
@THEtomaso 
Thanks.
Try
```
cmp.vg.no#%#//scriptlet('trusted-click-element', 'button.sp_choice_type_12[title="Tilpass"]')
cmp.vg.no#%#//scriptlet('trusted-click-element', 'button.sp_choice_type_REJECT_ALL', '', '1000')
```

**Comment by THEtomaso** [comment]
Doesn't seem to work for me, but I'm using uBO, and I might not have converted those rules correctly.

@DandelionSprout:
Could you give that a try?

**Comment by THEtomaso** [comment]
> uBO converts them automatically

Yeah, I noticed that now.
I actually though 'My filters' was excluded from that process. :)

--

> Did you disable other cookies filter lists?

Yes

**Comment by superlex** [comment]
Uhm, maybe with 2000 instead of 1000 ms:
```
cmp.vg.no#%#//scriptlet('trusted-click-element', 'button.sp_choice_type_12[title="Tilpass"]')
cmp.vg.no#%#//scriptlet('trusted-click-element', 'button.sp_choice_type_REJECT_ALL', '', '2000')
```

**Comment by THEtomaso** [comment]
Still a no go, unfortunately. :(

**Comment by superlex** [comment]
fixed by @piquark6046 here:
https://github.com/AdguardTeam/AdguardFilters/issues/170339

**Comment by THEtomaso** [comment]
> I suppose THEtomaso enabled trusted filters in uBO

Yes, I've got `user-` added to **trustedListPrefixes**, in **Advanced settings**. :)

--

> fixed by piquark6046 here: https://github.com/AdguardTeam/AdguardFilters/commit/56eb86730205955e8ce47aafbe4eb94c8dfa15aa

I can confirm that piquark6046's fix works for uBO.
..but ONLY in conjunction with this now!:
`@@||privacy-mgmt.com/mms^$domain=vg.no`
By default, that third party asset is blocked by the following rule (found in **AdGuard Cookie Notices filter**):
`||privacy-mgmt.com/mms^`

PS:
`@@||cmp.vg.no^` is also needed, but that isn't blocked by AdGuard Cookie Notices filter anyway.

**Comment by THEtomaso** [comment]
> nuisance issue should be fixed by uBO filter lists.

Yeah.
@mapx-:
Perhaps you could add this to uBlock filters - Cookie Notices then?
```
vg.no##div[id^="sp_message_container_"]
cmp.vg.no##+js(trusted-click-element, .btns-container > button[title="Tilpass"])
cmp.vg.no##+js(trusted-click-element, .message-row > button[title="Avvis alle"], , 2000)
```

**Comment by mapx-** [comment]
ELC has

`@@||cmp.vg.no^`

does it lead to some breakage ? if yes, provide specific page to test

**Comment by THEtomaso** [comment]
Yes, but that fix is on its way:
https://github.com/easylist/easylist/commit/6ae4a5aa45bb7000bf8af718efa1a3ef930eb09d
:)

**Comment by THEtomaso** [comment]
> piquark6046 closed this as completed

@piquark6046:
This isn't fixed yet!
See my post here:
https://github.com/AdguardTeam/AdguardFilters/issues/170285#issuecomment-1884952884

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/170285#issuecomment-1886865198
So, `##div[id^="sp_message_container_"]` should be applied in vg.no?

**Comment by THEtomaso** [comment]
Yes, along with `@@||privacy-mgmt.com/mms^$domain=vg.no`

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/170285#issuecomment-1886907834
Where is the `@@||privacy-mgmt.com/mms^$domain=vg.no` rule required?

**Comment by THEtomaso** [comment]
It's not _required_, but if it's missing, it results in the popup still being briefly visible (long enough for people to actually be able to click on it), even though these scriptlet rules of yours are in place:
https://github.com/AdguardTeam/AdguardFilters/commit/56eb86730205955e8ce47aafbe4eb94c8dfa15aa

**Comment by THEtomaso** [comment]
If it's missing, `||privacy-mgmt.com/mms^` completely prevents these scriptlet rules of yours from working!:
https://github.com/AdguardTeam/AdguardFilters/commit/56eb86730205955e8ce47aafbe4eb94c8dfa15aa

**Comment by piquark6046** [comment]
Even if your allowing rule is not applied, it seems that the current AdGuard Cookie Notice filter works well with ProtonVPN DE#20 server.

**Comment by THEtomaso** [comment]
Well, not with uBO.
I guess the rule could be added to '**uBlock filters - Cookie Notices**' instead?

**Comment by piquark6046** [comment]
Do you use uBlock Origin with AdGuard Cookie Notice filter?

**Comment by THEtomaso** [comment]
Yes, it's included in its default list of filters (only needs to be checked).

**Comment by piquark6046** [comment]
Can you share screenshots about your subscribed filters lists and advanced settings of uBO?

**Comment by THEtomaso** [comment]
As you can see, uBO has its own cookie filter, which is optimized to work in conjunction with AdGuard Cookie Notices filter:

![ubo-adguard-ubo-cookiefilters](https://github.com/AdguardTeam/AdguardFilters/assets/9382674/176783dd-3d54-40fa-8c3e-c0a7312b14e3)

**Comment by THEtomaso** [comment]
> Can you share the Troubleshooting Information in uBO support tab?

No need for that.
I troubleshooted this issue quite thoroughly yesterday, disabling all other filters and what not.
@@||privacy-mgmt.com/mms^$domain=vg.no is needed, for certain!

**Comment by piquark6046** [comment]
I cannot find the request.

<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/98787049/fbb69c9f-4e2d-461d-b8e4-4ef3bb762431)


</details>

**Comment by THEtomaso** [comment]
Oh, must be a regional thing then, as often is the case with GDPR issues:

![filterissue-vg5](https://github.com/AdguardTeam/AdguardFilters/assets/9382674/80549816-13c3-4a29-8b3d-ad0ab3df0459)

**Comment by THEtomaso** [comment]
I understand, but I've already confimed the need for that last whitelisting rule, so I won't be the one to report if there's a problem, since I've already added it to my own filter. :)
