### ISSUE TITLE
Google Play Music app causes battery drain and shows incorrect data in firewall

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1703]
If you are filtering ads for Google Play music it seems that Google Play music in turn starts bombarding the app with ads and it drains battery an insane amount.

Logs: JHQ-512-93178

**Comment by evgeniy-ADG** [comment]
The blocked ads amount keeps increasing even if you do not use Play Music, I had the same issue. Can't reproduce it now, though. Recommended to turn off filtering for Play Music.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
нужен HTTP лог с указанием примерного интервала разряда и список фильтров

**Comment by evgeniy-ADG** [comment]
а тот лог, что есть, на подходит? это хттп вроде. с ним вообще никак?..

**Comment by Alex-302** [comment]
там обычный лог
