### ISSUE TITLE
Connections blocked even when no rules are applied 

### ISSUE THREAD

**Issue by SohanRay** [AdguardTeam/AdguardFilters#170401]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

v4.3.1

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.nekki.shadowfightarena

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Block WebRTC

### Add your comment and screenshots

1. <comment>
Even when no rules are applied , the connection is being blocked . why ?
2. Screenshots
<details><summary>Screenshot 1:</summary>
![Screenshot_20240108_073115_AdGuard](https://github.com/AdguardTeam/AdguardFilters/assets/97858423/96b6f153-19be-4309-9ce9-85206484ec22)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by SohanRay** [comment]
![Screenshot_20240108_073115_AdGuard](https://github.com/AdguardTeam/AdguardFilters/assets/97858423/3b918f70-2f78-4727-a5a3-494c3168130b)

**Comment by Alex-302** [comment]
Hi. Better write to https://github.com/AdguardTeam/AdguardForAndroid/issues
Probably AdGuard blocked QUIC connection. Not related to filters.
