### ISSUE TITLE
[Stealth mode] http://putlocker.is/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1705]
![image](https://cloud.githubusercontent.com/assets/15856304/13553328/645de7ac-e38e-11e5-8bcf-83978180e2c3.png)

with hide your user agent. maybe we should add some user agents as a drop-down list?..

**Comment by Alex-302** [comment]
>with hide your user agent. maybe we should add some user agents as a drop-down list?..

you can make feature request

I can't reproduce this problem. Only hiding of user agent causes it?

**Comment by evgeniy-ADG** [comment]
yes, only user agent. i'll try to reproduce it tomorrow.
will file the request :)

**Comment by evgeniy-ADG** [comment]
Короче, наверное, это хайд ёе айпи. Как-то непонятно оно проявляется, не сразу и после отключения не сразу проходит.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Не повторяется. Дай прямую ссылку где такое происходит.
Если хайд айпи, то скорее всего не поправлю.

**Comment by evgeniy-ADG** [comment]
http://putlocker.is/watch-teen-wolf-online-free-putlocker.html

у тебя вообще все ок, если включить антитреккинг полностью?.. подтверди, пож-та, есть ли с хайд айпи. кастомер пишет про антитреккинг вцелом, у меня повторялось со скрытым агентом и с выключенным скрытие айпи. потом - только со скрытием айпи. =\

**Comment by Alex-302** [comment]
блокировка реферера блокирует плеер, т.к. у них жесткая привязка.
Проверь
@@||thevideos.tv/embed-*.html$domain=putlocker.is
не разблокировалось ли чего

**Comment by Alex-302** [comment]
@evgeniy-ADG

**Comment by evgeniy-ADG** [comment]
Forwarded to the customer, thanks!

**Comment by Alex-302** [comment]
added

**Comment by evgeniy-ADG** [comment]
customer replied that the rule did not work.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
а ты проверял как оно работает без Адгарда?
Из скринов же видно, что без правила плеер не появляется .
