### ISSUE TITLE
psychologytoday.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#170640]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.4

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.psychologytoday.com/us/blog/black-belt-brain/202401/your-brain-is-bad-at-doing-everything-everywhere-all-at-once

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

page2.googlesyndication.com
sb.scorecard.research.com

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Cannot reproduce this requests on page. Could you please make screenshots of the filtering log?
```
sb.scorecard.research.com
page2.googlesyndication.com
```

**Comment by jellizaveta** [comment]
@jordanswrld94 Hello! Any news?

**Comment by jordanswrld94** [comment]
Sorry didnt see the email. Here u go. 
![Screenshot_20240117_111048_AdGuard](https://github.com/AdguardTeam/AdguardFilters/assets/118186787/c1f6a160-40a2-4edb-9e17-e904197cbf07)
![Screenshot_20240117_111042_AdGuard](https://github.com/AdguardTeam/AdguardFilters/assets/118186787/b0b630e4-3fa5-49c8-a333-b0fa070bccb5)

**Comment by jellizaveta** [comment]
Not sure about `page2.googlesyndication.com`. What is it used for?

**Comment by jordanswrld94** [comment]
Not sure as their isnt a request for a javascript file. Just the dns requests. But googlesyndication is a ad domain
