### ISSUE TITLE
Как сменить тему и убрать фон warhammer40k.fandom.com ?

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#170606]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [ ] AdGuard product version is up-to-date;
- [ ] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.11/54

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://warhammer40k.fandom.com/ru/wiki/%D0%9A%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D0%B8%D1%8F:%D0%9F%D0%BB%D0%B0%D0%BD%D0%B5%D1%82%D1%8B

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

1. Помогите сменить тему с тёмной на светлую и убрать фон на warhammer40k.fandom.com. Фон получается убрать только статичными фильтрами, но он там переодически по вики меняется, так что они что мёртвому припарка. От тёмной темы по дефолту кровь из глаз течёт (меняется в углу), хочется светлую по дефолту сделать, дабы постоянно не переключать. Знаю, что через adguard можно подобное сделать, но опыта у меня для подобного маловато. Пробовал - не получилось.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Можно так
```adblock
warhammer40k.fandom.com#%#//scriptlet('remove-class', 'mediawiki', 'body')
warhammer40k.fandom.com#$#.mediawiki { background-image: unset !important; }
warhammer40k.fandom.com#%#//scriptlet('trusted-set-cookie-reload', 'theme', 'light')
```

Первое - опционально, второго вроде достаточно для удаления фона.

**Comment by Baltazar500** [comment]
@Alex-302, спасибо.

**Comment by Baltazar500** [comment]
Если вдруг кто в ветку заглянет, то вот до кучи правило скрытия "rail" панели, которая "ездит" по странице при скролле

>warhammer40k.fandom.com##aside[class="page__right-rail"]

Для меня оно ещё больше повысило юзабилити ресурса 😂
