### ISSUE TITLE
4pda.to

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#170758]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [ ] AdGuard product version is up-to-date;
- [ ] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.11/54

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://4pda.to/forum/index.php?forums=285&topics=601691&act=search&source=pst&query=alpha

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

1. На 4pda при поиске в тредах лезет (контекстная) реклама. Обычными фильтрами не блочится. ID у рекламного блока рандомный.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![img](https://github.com/AdguardTeam/AdguardFilters/assets/12525093/0d0d9b83-03dd-413d-aaab-371d01772901)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Исправил, обновите фильтры через 2-3 часа.

**Comment by zloyden** [comment]
Не вижу в репорте, что включены фильтры: раздражителей и русский. Их необходимо включить и проверить обновление фильтров через указанное время. Также не лишним будет включить расширение AdGuard Extra в настройках программы, поскольку реклама блокируется преимущественно этим скриптом. Помимо этого рекомендуется обновить программу до актуальной версии.

**Comment by zloyden** [comment]
>  ID у рекламного блока рандомный

Этого не наблюдаю но у себя, но если правило не поможет вдруг на вашей стороне из-за этого, лучше также создать задачу [здесь](https://github.com/AdguardTeam/AdGuardExtra/issues).

**Comment by Baltazar500** [comment]
>Не вижу в репорте, что включены фильтры: раздражителей и русский.
>Также не лишним будет включить расширение AdGuard Extra в настройках

Это всё есть. Просто я при открытии тикетов задолбался проставлять эти галочки. Раздражителей у меня 9/11. В следующий раз проставлю всё что есть и сохраню шаблон. Теперь буду бегло заполнять и закидывать заполненный шаблон заменяч, что есть. Если бы редактирование было редактирование было доступно без этой формы, я бы уже давно заполненный шаблон сразу кидал и менял бы только причину. А каждый раз проставлять галки реально задалбывает.

>Их необходимо включить и проверить обновление фильтров через указанное время

Реклама ушла, но неплохо бы было ещё убрать зазор, где она была.

![SNAGIT_2024 01 14_16 24 33](https://github.com/AdguardTeam/AdguardFilters/assets/12525093/94a3c318-f9f2-4fee-8c7d-31d601b08b8e)

>Помимо этого рекомендуется обновить программу до актуальной версии.

Я бы и рад, но на ведре 5.1 это не выйдет. Нашёл вот ночнушки/альфы 4.x, буду в ближайшее время смотреть.

**Comment by zloyden** [comment]
> Теперь буду бегло заполнять и закидывать заполненный шаблон заменяя, тот что есть.

Можно так. Еще как вариант отправлять репорт через программу - большинство полей заполняются сами. Насколько я помню, остается только скриншоты загрузить.
