### ISSUE TITLE
dailymail.co.uk - comments are falsely hidden

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1708]
The link: [breaking news!](http://www.dailymail.co.uk/news/article-3478165/I-t-mum-round-lunch-Reddit-user-appeals-help-toddler-s-frozen-strawberries-leave-unfortunate-stain-table.html)

When Adguard is on, the comments section is hidden:

<details> off
![image](https://cloud.githubusercontent.com/assets/15856304/13553466/7956c494-e393-11e5-9bbf-61c588fac8e4.png)

</details>
<details> on
![image](https://cloud.githubusercontent.com/assets/15856304/13553468/876eb906-e393-11e5-9ab1-3e16bab45539.png)

</details>

**Comment by Alex-302** [comment]
||scripts.dailymail.co.uk/static/mol-adverts/
replaced to
||scripts.dailymail.co.uk/static/mol-adverts/*.css

**Comment by Bohdan-SUP** [comment]
Happens again:
http://www.dailymail.co.uk/tvshowbiz/article-3880486/Rita-Ora-models-sexy-black-underwear-pulsating-teaser-video-gears-release-lingerie-collaboration.html

<details>
![screen shot 2016-10-29 at 1 52 29 pm](https://cloud.githubusercontent.com/assets/14153331/19829016/156a9cf6-9ddf-11e6-8df7-79822e4c13a4.png)
![screen shot 2016-10-29 at 1 52 09 pm](https://cloud.githubusercontent.com/assets/14153331/19829017/15838d9c-9ddf-11e6-838d-1f9f18950bb0.png)
</details>

Filters:
<details>
![screen shot 2016-10-29 at 1 52 41 pm](https://cloud.githubusercontent.com/assets/14153331/19829018/21815ea8-9ddf-11e6-9e18-1782d35b00bb.png)
</details>

Reported in ticket 1439399

**Comment by Alex-302** [comment]
Removed from English filter
```
||scripts.dailymail.co.uk/static/mol-adverts/*/mol-adverts.js
```

**Comment by kbahlyk** [comment]
Issue happens again: http://www.dailymail.co.uk/news/article-4658420/Schools-fine-parents-60-children-late.html#comments-4658420

Ticket ID - 1584574
