### ISSUE TITLE
finn.no

### ISSUE THREAD

**Issue by kklem0** [AdguardTeam/AdguardFilters#171113]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

2.13.0.1558

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, Chrome, Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.finn.no

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

website can't be scrolled because of GDPR cookie overlay, disable it then accept it and turn it back on works.

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
Surely there have to be more lists involved in the overlay breakage than just AdGuard Base.

Are talking AdGuard Annoyances, Fanboy's Annoyances, or anything like that?

**Comment by AdamWr** [comment]
Fixed issue caused by `AdGuard Cookie Notices filter`/`AdGuard Annoyances filter`.
Filters update should be available in 1-2 hours.
