### ISSUE TITLE
Blocking PerimeterX causes Captcha to become unpassable

### ISSUE THREAD

**Issue by bryanbecker** [AdguardTeam/AdguardFilters#171116]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard DNS, AdGuard for iOS, AdGuard for Windows

### AdGuard version

4.2.241

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, Chrome, Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

www.arcteryx.com

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

1. The issue is on both mobile & desktop.  When solving the captcha, the browser gets stuck on the "..." screen, and is unable to proceed, unless I disable adguard.

I think it is related to this line:
https://github.com/AdguardTeam/AdguardFilters/blame/a6e517d5292d0ebcc193bbf935d8ae6e751c388e/SpywareFilter/sections/tracking_servers.txt#L158

I will try to create a separate PR to resolve this

2. Screenshots
<details><summary>Screenshot 1:</summary>
![image](https://github.com/AdguardTeam/AdguardFilters/assets/469798/3b7aa742-399c-4ad9-9df0-b305ccca5760)
</details>
<details><summary>Screenshot 2:</summary>
![image](https://github.com/AdguardTeam/AdguardFilters/assets/469798/48659fbc-278a-49de-82c5-819faa0ad274)
</details>
<details><summary>Screenshot 3:</summary>
![image](https://github.com/AdguardTeam/AdguardFilters/assets/469798/557135a9-2c0c-4778-807f-9a44ad75e7be)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@bryanbecker Hi. We need steps to reproduce.
At first I wanted to delete these domains, but after reading their site I doubted whose interests they protect - the site visitor or advertisers.
