### ISSUE TITLE
Check for dead possibility of direct link rules

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdguardFilters#171100]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

- [ ] 1. ||magazin.com.tr/images/hediye.com.tr.jpg
- [ ] 2. ||eskisehirkonut.com/reklamemlak.gif
- [ ] 3. ||esenyurthaberleri.com/deneme.jpg
- [ ] 4. ||esenyurthaberleri.com/esbiyorek.gif
- [ ] 5. ||esenyurthaberleri.com/taysurucu.jpg
- [ ] 6. ||duzcepostasi.com/resim/upload/23277.jpg
- [ ] 7. ||dirilispostasi.com/15tem/970x250/970x250.html
- [ ] 8. ||devmta.dirilispostasi.com/img/kahramanlar.jpg
- [ ] 9. ||images.vfl.ru/ii/1487764401/73f3bbd4/16195037.jpg
- [ ] 10. ||image.prntscr.com/image/QfvxIFDKS-S2NZDx7XAvNA.gif
- [ ] 11. ||rsc.cdn77.org/matbet/yeni/1000x60.gif
- [ ] 12. ||rsc.cdn77.org/js/splash.min.js
- [ ] 13. ||usakhabermerkezi.com/images/banner/efsun.png
- [ ] 14. ||usakhabermerkezi.com/images/banner/usak_gurkan_aydin_post.jpg
- [ ] 15. ||rentalcars.com/affiliates/rc/tr/Cheap_Car-Hire_tr.gif
- [ ] 16. ||ownerity.com/insert/i/obilet5.png
- [ ] 17. ||gercekkocaeli.com.tr/resimler/images/Teknocom(1).jpg
- [ ] 18. ||bandirmahaber.com.tr/nakliye.jpg
- [ ] 19. ||iskenderunhaber.com/dosyalar/2020/02/gozdetip2020.jpg
- [ ] 20. ||bbnhaber.com/img/enerya.gif
- [ ] 21. ||kriptoarena.com/banner/ced.jpg
- [ ] 22. ||vidtekno.com/icerikler/VidTeknoBanner.gif
- [ ] 23. ||akcaabatinsesi.com/d/other/b-773.jpg
- [ ] 24. ||cerkezkoyhaber.com.tr/images/bilboard.png
- [ ] 25. ||konyaninnabzi.web.tr/headerrekalam.gif
- [ ] 26. ||gamer.com.tr/gamer.com_masthead.png
- [ ] 27. ||bbnhaber.com.tr/assets/img/Reklam2.jpg
- [ ] 28. ||oggusto.com/UserFiles/Image/images/Nisan2021/730x730.png
- [ ] 29. ||yenicaggazetesi.com.tr/d/other/cnt.jpg
- [ ] 30. ||yerlidizi.pw/assets/js/nation.js
- [ ] 31. ||yerlidizi.pw/assets/images/h1.gif
- [ ] 32. ||cloud01.xyz/s/savoy/savoy.mp4
- [ ] 33. ||izleorg3.org/asset/jquery/slim-3.2.min.js
- [ ] 34. ||izleorg3.org/asset/vue.min.js
- [ ] 35. ||muzikmp3indir.com/mp3mzk.js
- [ ] 36. ||asyafanatiklerim.com/oneri1.js
- [ ] 37. ||xbox360torrent.com/k.js
- [ ] 38. ||bbnhaber.com/js/jquery.magnific-popup.min.js
- [ ] 39. ||insaatnoktasi.com/ads.js
- [ ] 40. ||indirmedenfilmizle.vip/pop06.js
- [ ] 41. ||hdmixfilim.com/yip.js
- [ ] 42. ||filmizlet.net/telegram.js

Redirect:

||mp3kulisi.com/js/jquery.toast.js > mp3indirdur.life/js/jquery.toast.js

This is not ad:

||sivashaberler.com/hd.jpg

### Proposed solution

Filter maintanence. 😄

**Comment by DandelionSprout** [comment]
I for one could *in theory* have run through the approx. 1,214 applicable links to check that are in Base Filter specific.txt alone, but none of my methods would've been to accomodate any additional subdomains besides `www.`.

If I were to run an attempt on BaseFilters, and it turned out an ad had originally been hosted on e.g. `https://mermaidcostumeparty.adserver.piss/(...)`, and I had only checked for:
```
https://adserver.piss/(...)
https://www.adserver.piss/(...)
http://adserver.piss/(...)
http://www.adserver.piss/(...)
```
Then I'd be in for a bad time in general.
