### ISSUE TITLE
Spyware filter blocks VIP Support form at feedly.com

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#17133]
https://feedly.com/i/support/apps

You will need a VIP account to be able to reproduce it, `||djtflbt20bdde.cloudfront.net^` is the faulty rule. The screen recording: https://uploads.adguard.com/p4ppc.mp4

**Comment by BlazDT** [comment]
This rule working fine for you then?

`@@||djtflbt20bdde.cloudfront.net^$domain=feedly.com`

**Comment by Eugene-Savenko** [comment]
Yep, worked for me.

**Comment by BlazDT** [comment]
Thank you, fixed.
