### ISSUE TITLE
techolay.net

### ISSUE THREAD

**Issue by J3ekir** [AdguardTeam/AdguardFilters#171354]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

-

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://techolay.net/sosyal/konu/reklam-engelleyici-kullanmak-ahlaki-olarak-dogru-mu.6125/

### Ad Blocking

EasyList

### Language-specific

AdGuard Turkish filter

### Add your comment and screenshots

[This filter](https://github.com/AdguardTeam/AdguardFilters/blob/8c28d657cac083f73fe4e1a285aa2910353bb34a/TurkishFilter/sections/general_url.txt#L74) prevents [this site](https://techolay.net/sosyal/konu/reklam-engelleyici-kullanmak-ahlaki-olarak-dogru-mu.6125/) from loading.

I think it should be fine after adding `|~techolay.net` to the end of the filter.

I use uBlock Origin v1.55.0 on Chrome v120.0.6099.225.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Do you use strict blocking? I can't reproduce with uBO.

**Comment by J3ekir** [comment]
Seems like this guy does it. As far as I know, the `~` part in the filter means to exclude those websites. `reklam` means advert in Turkish. `techolay.net/sosyal` is a forum site. The guy who founded `technopat.net/sosyal` (which is in the exclude list) found it.
Screenshots were taken with only `tr: AdGuard Turkish` filter.

![image](https://github.com/AdguardTeam/AdguardFilters/assets/53034558/390d8679-4625-4842-9042-4e498ff5ef4d)
![image](https://github.com/AdguardTeam/AdguardFilters/assets/53034558/06db3330-401c-4b58-8a07-d4386ea7d749)
![image](https://github.com/AdguardTeam/AdguardFilters/assets/53034558/c1d16516-b3a0-4fbe-84b1-4c15527ae8ce)

**Comment by Alex-302** [comment]
Ok, reproduced with AdGuard.
Removed that rule.

**Comment by Alex-302** [comment]
Hm. Maybe.
Added as `/reklam-$image,script`
