### ISSUE TITLE
Pornxp.com (nsfw)

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#171428]
### Prerequisites

- [ ] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.4

### What type of problem have you encountered?

Website or app doesn't work properly, AdGuard gets detected on a website

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://pornxp.com/videos/424390912279

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

Videos dont play unless i add pornxp.com to website allow list in adblocking section

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@jordanswrld94 Unfortunately, I cannot reproduce this issue. Could you please send screenshots of the filtering log?

**Comment by jordanswrld94** [comment]
Weird thing is i cant see anything in log that is being blocked. Can i post my settings and you can try it in adguard for android?

**Comment by jellizaveta** [comment]
@jordanswrld94 Do you have any filters or functions enabled other than those listed in the issue?

**Comment by jellizaveta** [comment]
Thanks, managed to reproduce it. The update will be available within 1-2 hours.
