### ISSUE TITLE
com.novanews.localnews.en

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#171510]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.4

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.novanews.localnews.en

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

uxijcz-attr.appsflyersdk.com (sugggest:         
-attr.appsflyersdk.com as the letters before attr change)

These seem to be needed. They change sites to host ads after clearig app data and scrolling around a bit

||api.inmense.site^$app=com.novanews.localnews.en
||api.dollphoin.site^$app=com.novanews.localnews.en
||api.kickoffo.site^$app=com.novanews.localnews.en
||api.firwinds.site^$app=com.novanews.localnews.en

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
Actually thinking about it we should block the below dns level as well for non adguard app users:

api.inmense.site
api.kickoffo.site
api.firwinds.site
api.dollphoin.site

**Comment by Alex-302** [comment]
Not sure about these domains. I don't see ads in this app.
