### ISSUE TITLE
chosic.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#171595]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.4

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.chosic.com/spotify-playlist-analyzer/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Block third-party Authorization header, Block WebRTC, Block Push API, Block Location API, Hide Referrer from third-parties (specify in comment below, if used custom value), Hide your User-Agent (specify in comment below, if used custom value), Mask your IP address (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

@@||api.spotify.com/ * /users/ * /playlists?$stealth=3p-auth

@@||api.spotify.com/ * /me^$stealth=3p-auth

Fixes playlists not showing up.

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
@@||api.spotify.com/ * /me^$stealth=3p-auth has to be added. Still doesnt work

**Comment by jordanswrld94** [comment]
@Alex-302

**Comment by Alex-302** [comment]
Please show full request.

**Comment by jordanswrld94** [comment]
https://api.spotify.com/v1/me

**Comment by Alex-302** [comment]
I don't see such request

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/e6c7b813-1c87-4072-8528-0d0f64724109)


</details>

Please show how it looks in the dev tools.

**Comment by jordanswrld94** [comment]
Sorry i dont have computer atm im using my samsung phone. Is there a way to do it on there
