### ISSUE TITLE
ds2play.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#171656]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.4

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://ds2play.com/e/9x6g59dzq3mmupqrxs2uhy5xa9tcwsk

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Block third-party Authorization header, Block WebRTC, Block Push API, Block Location API, Hide Referrer from third-parties (specify in comment below, if used custom value), Mask your IP address (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

Website is broke with stealth enabled.

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Please post a new link or site where you got the link from, thank you.

**Comment by jordanswrld94** [comment]
https://ww1.pornhoarder.tv/video/erin-everheart-gangbangcreampie/dVYxRUovQU1TRVF6N1lGTmluSkp5YnZncHowQ20vZk9mV3p5RStVVGw5VT0=

**Comment by BlazDT** [comment]
Cannot reproduce with your given stealth options on Android 14 and latest nightly version.. Which option exactly breaks it?
@zloyden can you reproduce?

**Comment by zloyden** [comment]
I also can't reproduced it on my end. Which stealth mode option breaks it?

**Comment by jordanswrld94** [comment]
@@||ds2play.com^$stealth=ip fixes it for me

**Comment by zloyden** [comment]
Ok, added it to our filters. The update should be available soon.
