### ISSUE TITLE
narvar.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#171871]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.4

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://returns.narvar.com/rei-co-op/returns
https://columbia.narvar.com/columbia1/tracking/dhlglobal?tracking_numbers=9261290277983721920536

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Add your comment and screenshots

@@||narvar.com^$stealth=ip

Fixes forbidden error

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
Do you use AdGuard for Anroid beta?

**Comment by piquark6046** [comment]
@jordanswrld94 
Do you use AdGuard for Anroid beta?

**Comment by jordanswrld94** [comment]
> @jordanswrld94 Do you use AdGuard for Anroid beta?

Yes

**Comment by Alex-302** [comment]
Which IP in Stealth Mode settings?
