### ISSUE TITLE
cnn.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#171850]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.4

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.cnn.com/videos/live

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests, Block third-party Authorization header, Block WebRTC, Block Push API, Hide Referrer from third-parties (specify in comment below, if used custom value), Mask your IP address (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

@@||sp.auth.adobe.com^$stealth=ip
@@||sp.auth.adobe.com^$stealth=3p-auth

Both are needed to fix tv login after clicking red button

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
I don't see errors. Need details.
