### ISSUE TITLE
Proffsmagasinet sites - Subscription options are blocked

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#171994]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.55.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.proffsmagasinet.se/
https://www.staypro.dk/
https://www.staypro.fi/
https://www.staypro.no/

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Affected sites:
```
https://www.proffsmagasinet.se/
https://www.staypro.dk/
https://www.staypro.fi/
https://www.staypro.no/
```

### Issue:
When logged in, and managing your account, the various subscription options are blocked (some of which are enabled by default).

### Screenshots:
**Subscription options blocked:**

![filterissue-staypro-1](https://github.com/AdguardTeam/AdguardFilters/assets/9382674/512db351-77eb-442f-ab25-d235d35806d6)

**Subscription options allowed:**

![filterissue-staypro-2](https://github.com/AdguardTeam/AdguardFilters/assets/9382674/3046a6d8-b661-4a6f-983d-a6b8499f22e8)

**uBO's logger:**

![filterissue-staypro-3](https://github.com/AdguardTeam/AdguardFilters/assets/9382674/ca441e33-c74e-4a55-b2ff-f1bdf3806c95)

### Problem filter:
* **AdGuard Tracking Protection filter**

### Problem rule:
`||exponea.com^$third-party`

### Possible fix:
`@@||cdn.*.exponea.com/production*/consent?$frame,domain=proffsmagasinet.se|staypro.dk|staypro.fi|staypro.no`

### Other problem filters:
* **EasyList - Cookie Notices** / **EasyPrivacy** https://github.com/easylist/easylist/issues/18433/
`##.consent-content`
`||exponea.com^$third-party`

* ~~**uBlock filters - Unbreak** https://github.com/uBlockOrigin/uAssets/issues/22298/~~ **_(FIXED)_**
~~`||exponea.com^$3p`~~

--

### System info:
* OS/version: Windows 10 Pro 22H2 (x64)
* Browser/version: LibreWolf v122.0-2 (x64) [Tracking Protection = Standard]
* Adblock Extension/version: uBlock Origin v1.55.0

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available soon.
