### ISSUE TITLE
[iOS] vk.com - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1719]
![image](https://cloud.githubusercontent.com/assets/15856304/13649331/dfb81f62-e645-11e5-8746-b05b4386c56e.png)

Can we block that? 

RGG-206-19843

**Comment by Alex-302** [comment]
@evgeniy-ADG 
у меня рекламы нет. Если вдруг увдишь, сможешь дать доступ?

**Comment by evgeniy-ADG** [comment]
Это айос, у меня такого нет :(
@Serzh-SUP у тебя в айфонах есть такое?

**Comment by Serzh-SUP** [comment]
У меня вот, как бы такая штука:
![img_8070](https://cloud.githubusercontent.com/assets/16462533/13698464/ee970d26-e77c-11e5-9d4f-e948020ab8d2.PNG)

**Comment by evgeniy-ADG** [comment]
Картинка смешная )

**Comment by Alex-302** [comment]
не повторяется. Скорее всего нужно быть подписанным на кучу всякого шлака
Есть есть возможность повторить на маке и айфонным юзерагентом, могу удалённо глянуть.

**Comment by evgeniy-ADG** [comment]
@Serzh-SUP ты подписан на кучу шлака? :)

**Comment by evgeniy-ADG** [comment]
реклама
http://prntscr.com/apkr4n

http://prntscr.com/apkr8o
http://prntscr.com/apkrd0

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.78.19 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.4.89 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.71 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.24.21 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.31.37 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.47 Enabled=YES
ID!2 Name="RU AdList: Counters" Version=1.0.49.92 Enabled=YES
ID!3 Name="RU AdList: BitBlock" Version=1.0.50.18 Enabled=YES

**Comment by Alex-302** [comment]
>реклама
http://prntscr.com/apkr4n
http://prntscr.com/apkr8o
http://prntscr.com/apkrd0
Подробнее

вот такую может заблокируем

**Comment by Alex-302** [comment]
@evgeniy-ADG 
в десктопной версии сайта она уже заблокирована

**Comment by Alex-302** [comment]
В приложении чуть позже попробую заблокировать
