### ISSUE TITLE
m.discuss.com.hk

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1720]
The [link](http://m.discuss.com.hk/index.php?action=thread&tid=24138603)

![image](https://cloud.githubusercontent.com/assets/15856304/13652761/b2b43256-e656-11e5-85f2-deb6cdb6bc89.png)

logs: HXV-765-89527

**Comment by Alex-302** [comment]
I don't see it without adguard.
please check it on real device.

**Comment by Alex-302** [comment]
@evgeniy-ADG

**Comment by evgeniy-ADG** [comment]
мы проверим, мы без айфонов.
@Serzh-SUP

**Comment by Serzh-SUP** [comment]
Проверить, то конечно пожалуйста, но что здесь не так, мне не понятно, хотя здесь все не так)))
![img_8071](https://cloud.githubusercontent.com/assets/16462533/13698639/fab48362-e77d-11e5-98dd-61176b49e8d4.PNG)

**Comment by Serzh-SUP** [comment]
А, я понял, вверху у него пустое место белое. Какие фильтры у него вкл?

**Comment by evgeniy-ADG** [comment]
@Serzh-SUP хз, глянь в тикете
