### ISSUE TITLE
jd.ru, tinydeal.com - stealh mode breaks authorisation 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1721]
не происходит авторизация через сети
http://www.jd.ru/
http://prntscr.com/aalsf6

не происходит авторизация через фейсбук
https://www.tinydeal.com/index.php?main_page=login
http://prntscr.com/aalw7f

помогает отключение "блокировать сторонние cookies"

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Передай на проверку:
1.
```
@@||signin.jd.com^
@@||unionen.jd.com/*/login.html
@@||unionen.jd.com/new/facebook/callback.html
@@||facebook.com/dialog/oauth
```
Со вторым тоже должно помочь.

В фильтр пока не добавляю.

**Comment by evgeniy-ADG** [comment]
done

**Comment by Alex-302** [comment]
@evgeniy-ADG есть ответ?
