### ISSUE TITLE
drama-live.tv

### ISSUE THREAD

**Issue by michael1900** [AdguardTeam/AdguardFilters#172128]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.5.2

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.
AdGuard gets detected on a website

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

drama-live.tv

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List

### Language-specific

EasyList Italy

### Add your comment and screenshots

Go to the site: **drama-live.tv**, AdGuard will be detected.
Go to the site: **drama-live.tv** and choose one of the available events, choose one of the streams and click on play button, a new popup will open in a new safari tab. 

Please fix this.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
> Go to the site: **drama-live.tv**, AdGuard will be detected.

Not reproduced.

Please use reporting tool instead of the template.
