### ISSUE TITLE
time4tv.online

### ISSUE THREAD

**Issue by michael1900** [AdguardTeam/AdguardFilters#172120]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.5.2

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

time4tv.online/football-live/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List

### Language-specific

EasyList Italy

### Add your comment and screenshots

Go to the site: **time4tv.online/football-live/** and choose one of the available events, a new popup will open in a new safari tab. 

Please fix this.

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Overlay blocked by generic rule from Base filter for me:
`/?oo=1&aab=1|$script,third-party,xmlhttprequest`

Adserver which is blocked by that rule is also blocked by DNS filter.

@zloyden can you reproduce?

**Comment by zloyden** [comment]
Also not reproduced on my end.
Try to clear browser data, update the filters (wait almost one minute there), open the site.
If that doesn't work, you should re-enable the content blockers in Safari settings (wait about the same time as when you update the filters).
