### ISSUE TITLE
fantasti.cc [Ad] [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#17222]
**Site**: http://fantasti.cc/user/spuugje/videos/upload/A-thick-beautiful-babe-fucks-pawnmans-cock-for-money/1552123/?utm_medium=cpm&utm_campaign=20170930&utm_source=awn-rse-fcc

**Issue**: Please remove the ad at the bottom right of the page.
 
**Screenshot**: http://prntscr.com/jodldu

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.181 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Fixed.
