### ISSUE TITLE
iceporn.com [NSFW] [AD]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#17223]
**Site**: https://www.iceporn.com/video/2723987/pov-homemade-amateur-girlfriend-facial-cumshot-she-loves-it

**Issue**: Please remove the ad at the bottom right of the page.
 
**Screenshot**: http://prntscr.com/jodscu

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.181 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Not reproduced, please check @AdamWr

**Comment by AdamWr** [comment]
I can't reproduce it.

**Comment by Nzzyme** [comment]
Pop-up seen on the page:

https://www.iceporn.com/video/3078340/hottest-amateur-mature-milf-in-elf-costume-fucking-on-webcam#dHJhY2tfdHlwZT1yZWxhdGVkX2NsaWNrJmNpZD0zMDc4MzQwJm49MTQ=

Pop-up seen when clicking on any other thumbnail on the bottom of the page.

**Comment by BlazDT** [comment]
Fixed

**Comment by Nzzyme** [comment]
https://www.iceporn.com/video/2915380/punjabi-call-girl

Incorrect blocking. When AG for Chrome is enabled, cannot see the video player. Can see it when AG is disabled

**Comment by BlazDT** [comment]
Removed the rule. Did not notice any popunders on both sites.
