### ISSUE TITLE
Scam sites: startcapitalstructure.com and bestmarketvaluation.com

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#172326]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.241

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Firefox, Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://bestmarketvaluation.com/products/princess-dress-for-big-sister-mouse-rose?promoted_link_id=beHHJOmsADW0, https://startcapitalstructure.com/products/woodstock-throw?source_id=vkKMSrKuetYCgBkI

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Other Annoyances filter

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Language-specific

AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Ukrainian filter

### Add your comment and screenshots

Both of these websites impersonate a news site (jauns.lv). Every link in these websites lead to one specific section in the page where user have to input their personal data (full name, email, phone), making them very suspicious.

Found these websites in Facebook's "Sponsored" posts, they do not get blocked on my end.

Please block these websites.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
For the first site, ESET identifies it as a suspicious site

https://www.virustotal.com/gui/url/6eb4f19ebabe87043cd09e975f1d86e4f25af1976d62319e0ce02c9979ace856?nocache=1

The second one is clean, but I can't open it. It shows up as something broken.

https://www.virustotal.com/gui/url/36dbc8a2e6058f96def81951e4de80a50320b81dab2bcccba40f2a43df981d83?nocache=1

<details><summary>Screenshot:</summary>

<img width="421" alt="Screenshot 2024-02-07 at 6 20 13 PM" src="https://github.com/AdguardTeam/AdguardFilters/assets/91964807/1b2751fe-a735-450e-b2dc-f909f9447666">

</details><br/>

Will be added to the phishing, the update will be available within 24 hours
