### ISSUE TITLE
www.matchendirect.fr

### ISSUE THREAD

**Issue by Machou** [AdguardTeam/AdguardFilters#172536]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.55.0

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox, Chrome, Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.matchendirect.fr/

### Ad Blocking

AdGuard Base filter

### Language-specific

AdGuard French filter

### What Stealth Mode options do you have enabled?

Hide your search queries

### Add your comment and screenshots

1. Missing block pub on website

2. Screenshots
<details><summary>Screenshot 1:</summary>

![](https://i.ibb.co/gzTLsKL/Capture-d-cran-2024-02-10-01-31-44-fullpage-copie.png)

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Right app QR code requires Annoyances filter, please enable and update in about 3-4 hours.

Other two elements are hidden on my uBlock installation (you need to enable Element hiding in uBlock's settings).
