### ISSUE TITLE
[Android] Adds appear in LINE app

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#1725]
TICKET ID's PAO-776-46693 and SIM-369-87313 (some logs are inside of both tickets)

English, Japanese and mobile ads filters are enabled, but some video ads still appear in LINE app: https://play.google.com/store/apps/details?id=jp.naver.line.android (in "Timeline tab", and at the bottom of "Others" tab).

**Comment by blackzigong** [comment]
Screenshots: https://imgur.com/a/gkACo

**Comment by Bohdan-SUP** [comment]
@Alex-302 Any update?

**Comment by vozersky** [comment]
@Bohdan-SUP can't reproduce it so far

**Comment by blackzigong** [comment]
They likely appear only when system language is set to Japanese(日本語).

**Comment by vozersky** [comment]
@blackzigong 

I see, thanks.

If it's possible, could you please do the following:
1. clean Line cash files
2. turn on http logs in Adguard's settings
3. Use Line, reproduce some adds and write down the exact time when they did appear.
4. Send us the logs and the time notes. 

Rather here or thhrough the ticket.

Thanks!

**Comment by evgeniy-ADG** [comment]
@vozersky CBG-111-45017

**Comment by Alex-302** [comment]
@vozersky 
```
||dl.os.line.naver.jp/r/myhome/h/LanguageMaterial$media
```
send this rule for testing in user filter

**Comment by evgeniy-ADG** [comment]
We have another set of logs, the rule above didn't help. please check the ticket.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Which of the three tickets?

**Comment by evgeniy-ADG** [comment]
@Alex-302  SIM-369-87313 - here

**Comment by Alex-302** [comment]
@evgeniy-ADG 
did you open that log? How much HTTP requests there?

**Comment by evgeniy-ADG** [comment]
Если нужно, чтобы я понимал в том, что каким логом является и определял корректность того или иного переданного лога, просьба научить меня это делать. Спасибо.

**Comment by Alex-302** [comment]
Для решения проблем с фильтрацией(ложные/реклама) нужен HTTP лог, т.к. в нём запросы видно.
Включается в расширенных настройках -> Уровень логгирования.
Отличить HTTP лог можно по строкам вида
```
12:28:08.222 [pool-2-thread-10397] DEBUG com.adguard.android.FilteringLog - TCP id=271251 GET "http://privetapp.ru/ads/mp4/76dc943b-ae9f-43e3-ba39-5b3a17b27ca0_m.mp4" 200 1589492 389ms "null" "Samsung SM-G900F stagefright/Beyonce/1.1.9 (Linux;Android 5.0)"
12:28:08.252 [pool-2-thread-10398] DEBUG com.adguard.android.FilteringLog - TCP id=271252 got connection ru.privetapp /10.101.5.193:36589 /95.213.156.146:80 10242
```
если в логе нет строк с ***com.adguard.android.FilteringLog***, то это обычный лог с минимумом информации, и в этом разделе толку от него мало.

При проблемах, не связанных с рекламой или ложной блокировкой и обычный лог сойдёт. Но это для другого раздела.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
не просил?
