### ISSUE TITLE
www.socialandtech.net

### ISSUE THREAD

**Issue by lchamp** [AdguardTeam/AdguardFilters#172676]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

4.5.2

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://socialandtech.net/

### Ad Blocking

AdGuard Mobile Ads filter

### Privacy

EasyPrivacy

### Social Widgets

AdGuard Social Media filter

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Language-specific

AdGuard French filter, EasyList Italy

### Add your comment and screenshots

1. Appears after a few seconds and/or after scrolling a bit

2. Screenshots
<details><summary>Screenshot 1:</summary>
![IMG_2431](https://github.com/AdguardTeam/AdguardFilters/assets/6057771/a4df8ab1-ef4c-4458-aa69-534ff775f8e1)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Hello. Unfortunately, the reported issue does not satisfy our [filters policy](https://kb.adguard.com/en/general/adguard-filter-policy). The website has low visitors. Please, add these rules to the User Rules:
```
||socialandtech.net/wp-content/plugins/ays-popup-box/
socialandtech.net##.ays-pb-modals.av_pop_modals_4
```
