### ISSUE TITLE
strims.in

### ISSUE THREAD

**Issue by Lukjan39** [AdguardTeam/AdguardFilters#172808]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.13

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

strims.in

### Ad Blocking

AdGuard Base filter

### Privacy

EasyPrivacy

### Annoyances

I don't care about cookies

### Security

Online Malicious URL Blocklist

### Language-specific

EasyList Polish, KAD - Anti-Scam

### Add your comment and screenshots

nie dziala czasem strona strims.in/, jak jest lista do wyboru transmisji, np tenis z doha, polski stream(polskie kanaly)
![1](https://github.com/AdguardTeam/AdguardFilters/assets/104568362/b680202c-6762-4f9c-89b8-4cd7d1a3be9d)

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Not reproduced on my end. I've also checked `WTA Doha` - works fine with AdGuard filters. Try to leave only them, update the filters, clear browser data, restart it, open the site.

**Comment by zloyden** [comment]
@AdamWr could you take a look at this on your side?

**Comment by Lukjan39** [comment]
oto screen
![Bez tytułu](https://github.com/AdguardTeam/AdguardFilters/assets/104568362/87d848b1-cb2b-4a2b-9b39-d5c3a77d3643)

**Comment by AdamWr** [comment]
U mnie wersja HD nie działa nawet z wyłączonym AdGuardem.

**Comment by Lukjan39** [comment]
aha, czyli oni cos zepsuli?

**Comment by AdamWr** [comment]
Nie wiem, poprzednio był "offline", teraz wyświetla się prawidłowo.

>Która lista filtrów albo opcja w ustawieniach AdGuarda powoduje ten problem?

**Comment by Lukjan39** [comment]
probowalem wylaczac i wlaczac po kolei i zadne filtry nie obsluguje :(

**Comment by AdamWr** [comment]
A jakaś inna opcja, na przykład "tryb niewidzialności"?

**Comment by Lukjan39** [comment]
pomoglo to wylaczyc

ukryj Referrer przed firmami trzecimi
Uniemożliwianie firmom trzecim poznania odwiedzanej witryny.

to jest wazne dla innych stron?

**Comment by AdamWr** [comment]
Dodałem regułę, która powinna to naprawić (aktualizacja filtrów będzie za około 2 godziny).
Swoją drogą, polecam korzystać z formularza do zgłaszania problemów - https://reports.adguard.com/pl/new_issue.html, wtedy wszystkie informacje odnośnie ustawień i włączonych opcji będą dodane automatycznie, co zdecydowanie ułatwia rozwiązanie problemu (w tym zgłoszeniu brakuje informacji na temat włączonego "trybu niewidzialności", dlatego o tym wspominam).

**Comment by Lukjan39** [comment]
aha, dobra

**Comment by Lukjan39** [comment]
jest dobrze, dzieki.
