### ISSUE TITLE
Missing ads on https://www.max.com/

### ISSUE THREAD

**Issue by OlgaPetukhova** [AdguardTeam/AdguardFilters#172910]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.12.2.1415

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.max.com/

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter

### Other

Filter unblocking search ads and self-promotion

### DNS filters

AdGuard DNS filter

### Language-specific

AdGuard French filter, AdGuard German filter, AdGuard Russian filter

### Add your comment and screenshots

1. When AdGuard on, the ad still play, but the ad duration is not shown while ads are playing and location of ads on the scrub bar is missing while the feature is playing.
2. Screenshot:
https://uploads.adguard.org/up35_gvzo8.png

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Can't access with VPN. Also I don't have an account.
