### ISSUE TITLE
b2.ai

### ISSUE THREAD

**Issue by rnixs** [AdguardTeam/AdguardFilters#173253]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

I have a new anti-adblock service and I don't have any filters blocking that domain so I'm trying to add it.

### Proposed solution

It's simple, you just need to block the domain.

### Additional information

https://www.b2.ai/ 
It is a company that provides anti-ad blocks as plug-ins in WordPress.

**Comment by zloyden** [comment]
Do you have a real example of this detection?

> It's simple, you just need to block the domain.

Hm, in that case this rule should help.
```adblock
||b2.ai^$third-party
```

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/173256#issuecomment-1960069663.
