### ISSUE TITLE
com.accordion.pro.camera: cookie notice

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#173499]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.3.1

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.accordion.pro.camera

### Ad Blocking

AdGuard Base filter

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

Cookie notice that can be blocked with `||fundingchoicesmessages.google.com^`. Additionally, this app creates connections with the following domains:

src.smilewhitebear.com
src.wisharcbuilder.com
apptrace.guangzhuiyuan.com
appinference-distribute.guangzhuiyuan.com

Please check what their purpose is, they might be used for analytics.

### Privacy

- [X] I agree to follow this condition

**Comment by Pixel2019999** [comment]
Hello,  @jellizaveta, I am the owner of the domain guangzhuiyuan.com. Our team is focused on research in the field of computer vision and we do not engage in any advertising development work. The domain guangzhuiyuan.com is used by us to provide server-side services to our users, including AI generation, recognition, file backup, etc. Currently, the domain guangzhuiyuan.com has been added to the filter list in BaseFilter/sections/adservers.txt, which has disrupted our services and caused inconvenience to our users. We hope that you can further confirm the purpose of the guangzhuiyuan.com domain and remove guangzhuiyuan.com from the default filter configuration. Thank you!
