### ISSUE TITLE
com.photo.android.camera: cookie notice

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#173480]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.3.1

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.photo.android.camera

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

Cookie notice from `fundingchoicesmessages.google.com` shows up after opening the app.
Fixed by rule `||fundingchoicesmessages.google.com^`

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
@andris86 not reproduced on my end, also don't see the request. Try this rule and tell me how it goes.
```adblock
||fundingchoicesmessages.google.com^$app=com.photo.android.camera
```

**Comment by zloyden** [comment]
Hm, that's strange. I assume this `com.photo.android.camera` is correct name for the app. Is the request blocked in the recent activity after adding the rule to user rules (not the DNS ones)?
You can also try to block it manually via the filtering log. Choose the request, block it and also limit it to the app.

**Comment by zloyden** [comment]
> Rule works when I put in User rules under DNS blocking section, but it gets ignored when I add the $app modifier there.

If it's still not working, perhaps that's a bug. Could you also show the screenshot from the recent activity after adding the blocking rule with the `$app` modifier?

**Comment by zloyden** [comment]
Yes, that's what I meant. The behaviour is really odd - the request must also be blocked via `Ad Blocking protection`.
To confirm that this is a bug, please send screenshots here after doing the following:
1. add the rule `||fundingchoicesmessages.google.com^$app=com.photo.android.camera` like you did before in protection (second column) - Ad blocking - user rules
2. do a screenshot
3. open recent activity
4. switch to the app
5. reproduce the problem (the cookies are still shown)
6. return to the recent activity
7. find the request `fundingchoicesmessages.google.com`
8. do a screenshot
9. send both screenshots here.

Also send the screenshots with the same steps, but with this rule in Ad blocking - user rules.
```adblock
||fundingchoicesmessages.google.com^
```

**Comment by zloyden** [comment]
As I understand, something is really wrong with the rule. Now the task is here https://github.com/AdguardTeam/AdguardForAndroid/issues/5241.
You can leave the DNS rule as a temporary solution.
