### ISSUE TITLE
att.yahoo.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1735]
User wants to block the image on the right at att.yahoo.com
![screen shot 2016-03-11 at 5 11 36 pm](https://cloud.githubusercontent.com/assets/14153331/13706903/d21ffca6-e7af-11e5-9f50-7f2dd591b574.png)

**Comment by Alex-302** [comment]
for user filter
att.yahoo.com###applet_p_50000233

**Comment by Bohdan-SUP** [comment]
http://i.imgur.com/ZcF2Npq.png

**Comment by Alex-302** [comment]
yahoo.com##div[data-applet-type="homepagepromo"]

**Comment by Bohdan-SUP** [comment]
It's back:
https://i.imgsafe.org/8edf126.jpg

Is there any generic rule we can use?

**Comment by Alex-302** [comment]
att.yahoo.com##div[data-applet-type="partnerpromo"]

**Comment by shaurmanchic** [comment]
The ads are back
![capture](https://cloud.githubusercontent.com/assets/14258460/16812151/79198938-4934-11e6-844a-40be33e8ea04.PNG)

**Comment by Alex-302** [comment]
```
yahoo.com###my-adsLREC-base
```
