### ISSUE TITLE
Oqee TV for Android TV

### ISSUE THREAD

**Issue by Barzaquaa** [AdguardTeam/AdguardFilters#173500]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

Adguard AndroidTV 4.3.1

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=net.oqee.androidmobile&hl=fr&gl=US

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

I use the OqeeTV app on AndroidTV and I want to use Adguard to block ads on it. However, OqeeTV manages to detect Adguard using Google's API.

Through a browser, using the following filter: "||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect=google-ima3,domain=oqee.tv," we managed to block ads on Oqee.tv without Adguard being detected.

So, I tried to apply the same filter for AndroidTV: "||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect=google-ima3,app=net.oqee.androidtv.store," but it didn't work. The Oqee TV app on AndroidTV still detects Adguard and blocks the videos.

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/172868#issuecomment-1963849251.
