### ISSUE TITLE
Blocking all picture and video in ensonhaber.com

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardFilters#17373]
I use AdGuard pro in my iphone, and update periodically.
But i use a website for news.
The filters is blocking all picture and video in this website 

Example:
https://m.sondakika.com/haber/haber-eli-ayagi-baglanan-doktora-gasp-iddiasi-10900636/

### Steps to reproduce

1. https://m.sondakika.com/haber/haber-eli-ayagi-baglanan-doktora-gasp-iddiasi-10900636/
2. https://m.sondakika.com/haber/haber-fenerbahce-josef-de-souza-teklifini-reddetti-12-10901262/

MY FILTERS:
English Filter, 
Spyware Filter, 
Social Media Filter, 
Turkish Filter, 
Mobile Ads Filter, 
Safari Filter

### Expected behavior

Without filters, i can see videos and pictures on a page of websites.
1. https://i.hizliresim.com/b64v0V.jpg

### Actual behavior

With filters, i can’t all except text.
1. https://i.hizliresim.com/RD6gvj.jpg

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: iPhone 6s 64gb
* Operating system and version: 11.3
* Browser: Safari
* Wi-fi or mobile internet connection: both (i tried both of theö, the results are same.)

**Comment by Alex-302** [comment]
Added to Spyware Filter
```
@@||api.dmcdn.net/pxl/cpe/client.min.js$domain=m.sondakika.com
@@||api.dmcdn.net/pxl/cpe/app.min.js$domain=m.sondakika.com
```
