### ISSUE TITLE
Strange behavior with Chrome + French Filter + Service worker

### ISSUE THREAD

**Issue by woprandi** [AdguardTeam/AdguardFilters#173725]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.13

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://partners.o-tera.com/login

### Ad Blocking

EasyList

### Language-specific

AdGuard French filter

### Add your comment and screenshots

https://partners.o-tera.com/login (every non-root) XHR requests from third party referer seems to be blocked by the French AdGuard Filter
To reproduce : 
* Chrome (I did not success to reproduce on Firefox)
* First open will success 
* Close tab and retry (always use link above to have a referer)
* Chrome display site unreachable

![image](https://github.com/AdguardTeam/AdguardFilters/assets/1449422/b7e5302e-5e5b-4e5f-8a4a-f2b46df3ba70)
![image](https://github.com/AdguardTeam/AdguardFilters/assets/1449422/dc76443b-6cc4-432b-8e52-260c0b1a9107)

* Disabling rule manually fixes the issue
* Same behavior with uBlock Origin

The issue seems related to requests from service worker.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Can't reproduce on https://partners.o-tera.com/login
That rule don't work on o-tera.com - partners.o-tera.com is not third-party for o-tera.com

**Comment by Alex-302** [comment]
@smed79 Please also take a look.
