### ISSUE TITLE
https://eatcells.com/land/

### ISSUE THREAD

**Issue by Mr-Anonymous-404** [AdguardTeam/AdguardFilters#173822]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard for Windows

### AdGuard version

4.3

### What type of problem have you encountered?

Missed ads or ad leftovers, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://eatcells.com/land/

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. <comment>
Website is redirecting to new page again and again whenever i am clicking anywhere on the website
2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. Need a source of this link. Did you click ads?
