### ISSUE TITLE
[Android] Leo Dictionary ads

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1739]
Leo Dictionary app
<details>
[The app](https://play.google.com/store/apps/details?id=org.leo.android.dict)
![screenshot_20160310-175319](https://cloud.githubusercontent.com/assets/14153331/13712450/59a9189e-e7cc-11e5-9142-5047b7ef03f3.png)
</details>
Logs and details IFH-797-59494

**Comment by Alex-302** [comment]
@Bohdan-SUP 
Не заблокировать. Баннер загружается как data:image/gif;base64 в файле, содержащем несколько страниц html.
@ameshkov 
возможно такое отфильтровать? $$ не помогает.
https://gist.github.com/Alex-302/0a384cf2b335c5fea4cb
