### ISSUE TITLE
google.ru

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#174198]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [ ] AdGuard product version is up-to-date;
- [ ] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.11/54

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://google.ru

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies

### Add your comment and screenshots

1. В гуглопоиске периодически вылезает наг-скрин вымогающий местоположение (не просто попап, а с затенением). Как заблокировать - ХЗ. Простые фильтры не срабатывают.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![SNAGIT_2024 03 05_18 45 45~01](https://github.com/AdguardTeam/AdguardFilters/assets/12525093/098167c7-22c3-465c-b60c-891ff6d9e330)

</details>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Поправил, обновление станет доступно через пару часов.

**Comment by Baltazar500** [comment]
Вылезло опять :/
![2024 03 08_19 53 41~01](https://github.com/AdguardTeam/AdguardFilters/assets/12525093/fffbc3d0-09cd-407b-968b-120dc8372c33)

**Comment by zloyden** [comment]
По этому запросу у меня не повторяется, но правило ранее было изменено. Попробуйте проверить сайт с последним обновлением фильтров.
