### ISSUE TITLE
asuratoon.com blocked by filter

### ISSUE THREAD

**Issue by NoFace33** [AdguardTeam/AdguardFilters#174172]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

v4.3.1

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://asuratoon.com/

### Ad Blocking

AdGuard Base filter

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

1. Site is accessible only when disabling dns protection
2. Might have been wrongly blocked with commit [4331a64](https://github.com/AdguardTeam/AdguardFilters/commit/4331a64edbafb7883407cd6498d9073a2070923b)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
what do you mean by `accessible`?
Please add screenshot or send report from the Support menu.
