### ISSUE TITLE
winporn.com [NSFW] [Ad]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#17435]
**Site**: https://www.winporn.com/video/320959/slim-ebony-babe-in-sexy-lingerie-has-a-black-stud-banging-her-holes-all-over-the-bed

**Issue**: Please remove the ad at the bottom right of the page.
 
**Screenshot**: http://prntscr.com/jpv7v8

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.181 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Not reproduced, fixed some ad requests.

@AdamWr please check.

**Comment by AdamWr** [comment]
I can't reproduce it.
