### ISSUE TITLE
3movs.com [NSFW] [Ad]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#17436]
**Site**: https://www.3movs.com/

**Issue**: Please remove the empty ad banner on the page. Moreover, after any video ends, seeing an ad banner on the player (http://prntscr.com/jpva0m)
 
**Screenshot**: http://prntscr.com/jpv9dp

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 66.0.3359.181 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
After-play ad not reproduced, please check after update, probably fixed too.

**Comment by Nzzyme** [comment]
Hi Blaz, I am still able to see the empty ad banner on one of the page:

http://prntscr.com/jv6qgc


Link: https://www.3movs.com/videos/72094/ryan-conner-sat-on-juan-s-face-and-got-pussy-licked/?site_id=00192

**Comment by BlazDT** [comment]
This element is hidden by extended CSS rule in English filter:
3movs.com###side_col_video_view > div.section:has(> div.block_header_side > h4:contains(Advertisement))

**Comment by Nzzyme** [comment]
I have the English filter enabled. So do I need to enable something else to hide the string/empty space? Does it get blocked for you?

**Comment by BlazDT** [comment]
Please check this rule:
3movs.com#%#Object.defineProperty(window, 'inisStick', { get: function() { return function() {}; } });

Somehow ext-CSS is doing nothing when that function is executed.

**Comment by Nzzyme** [comment]
Hi blaz, I used the AG context menu option and blocked the ad bar on the right side. I used this rule:

3movs.com###side_col_video_view > div.section:first-child

Since then, I am not seeing any ads on any page of this domain. Can you add the above rule?

**Comment by BlazDT** [comment]
first-child rules are dangerous - did you try the javascript rule I mentioned?

**Comment by Nzzyme** [comment]
Yes, I tried this one and it did not work.

`3movs.com###side_col_video_view > div.section:has(> div.block_header_side > h4:contains(Advertisement))`

Why is my rule dangerous?

**Comment by BlazDT** [comment]
That is not the javascript rule, the one with #%# is the java one.

It is dangerous as author only has to move one bit and then the site is broken as the first section element gets hidden - no matter what the content is.

**Comment by Nzzyme** [comment]
Ok, so is there a rule that works? I tried this rule but still see the empty ad banner on the right

`3movs.com###side_col_video_view > div.section:has(> div.block_header_side > h4:contains(Advertisement))`

Thank you!

**Comment by BlazDT** [comment]
@AdamWr please check - it perfectly hides it for me.

**Comment by AdamWr** [comment]
It works fine with AdGuard for Windows, but doesn't work with AdGuard Extension on my end.
If I add this rule to extension then this ad leftover is hidden:
```
3movs.com#$##side_col_video_view > div.section:has(> div.block_header_side > h4:contains(Advertisement)) { position: absolute!important; left: -3000px!important; display: none!important; }
```

**Comment by Nzzyme** [comment]
Hi Adam, the ad string is now hidden. However, after a video completes playing, I am seeing an ad banner over the player

http://prntscr.com/kavjp5

Can you check? Thanks

**Comment by Nzzyme** [comment]
Hi, still seeing the ad banner after video completes playing. Has this been fixed?

**Comment by Alex-302** [comment]
fixed
