### ISSUE TITLE
pikabu.ru & фильтры для adguard 2.12.250

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#174465]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [ ] AdGuard product version is up-to-date;
- [ ] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

2.12.250

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://pikabu.ru

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Language-specific

AdGuard Russian filter, RU AdList - Counters

### Add your comment and screenshots

1. Есть старый смарт на 4.2 с adguard 2.12.250 (как оно там работает - отдельная история, речь не про это), где новые фильтры уже не катят. Можно ли какими-то костылями там заблокировать рекламу ? Сам ресурс, что характерно, грузится быстро, но прогружающиеся постфактум рекламные блоки могут намертво повесить браузер, пока прогружаются. За точность указанного списка фильтров не ручаюсь, но используются подписки *_optimized.txt под индексами 1 - 4, 11, 14, 15 

2. Screenshots
<details><summary>Screenshot 1:</summary>

![SNAGIT_2024 03 07_17 23 14](https://github.com/AdguardTeam/AdguardFilters/assets/12525093/e15334ff-aaf8-47e0-9356-79dcb3e8c069)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Эта версия уже довольно старая, было много изменений с тех пор. Здесь остается только [самому делать правила](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters).
Возможно такое правило сработает.
```adblock
pikabu.ru$$script[wildcard="*let*=*Math.random*xhr.onreadystatechange*"][max-length="15000"]
```

**Comment by Baltazar500** [comment]
@zloyden, спасибо за попытку но не прокатило :/ Всё равно лезет. Может скриптом каким полновесным это убрать можно ? Как показали эксперименты, в правило - скриплет при желании можно целый скрипт затолкать.
