### ISSUE TITLE
dailygeekshow.com

### ISSUE THREAD

**Issue by imTHAI** [AdguardTeam/AdguardFilters#174639]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.5.2

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://dailygeekshow.com

### Ad Blocking

AdGuard Mobile Ads filter

### Language-specific

AdGuard French filter

### Add your comment and screenshots

![IMG_E01343F02915-1](https://github.com/AdguardTeam/AdguardFilters/assets/36070606/3c092e7a-3bf4-480c-8368-5a67460c1920)

There are 2 rules regarding this website:
dailygeekshow.com##.pepsia_player
dailygeekshow.com##.sidebar-sticky-ads

But those rules (at least one) prevent the site from launching
 

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
Did you add AdGuard French filter as a DNS filter?

**Comment by imTHAI** [comment]
@piquark6046 Indeed. Adguard accepted it so I concluded that it knew how to interpret the "adblock" rules to his liking. But to your question, I understand that it was a mistake. AGH simply blocks all the domains listed, is that it?

**Comment by piquark6046** [comment]
What is 'AGH'?

**Comment by imTHAI** [comment]
Adguard*

**Comment by piquark6046** [comment]
Adding a non-DNS filter as DNS filter is not recommended.
Please remove the AdGuard French filter from your DNS filters.
