### ISSUE TITLE
Update Node.js version in GitHub workflows

### ISSUE THREAD

**Issue by scripthunter7** [AdguardTeam/AdguardFilters#174676]
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

https://nodejs.org/en/about/previous-releases

<details>
<summary>Show screenshot</summary>

For example, [here](https://github.com/AdguardTeam/AdguardFilters/actions/runs/8244990654) we got this warning:

![image](https://github.com/AdguardTeam/AdguardFilters/assets/57285466/d14bc09f-6955-4ff3-bc48-f0d18c03cfc8)

</details>

**Comment by scripthunter7** [comment]
@slavaleleka @maximtop it seems [`technote-space/workflow-conclusion-action@v3`](https://github.com/technote-space/workflow-conclusion-action) is not supported anymore, we should find something else (this is also true for other repos where we use it)

**Comment by slavaleleka** [comment]
but technote-space/workflow-conclusion-action@v3 still work fine, right?
if so, I guess there is no rush and it can remain for now

**Comment by scripthunter7** [comment]
@slavaleleka yes, but it's still using Node 16, and GH is forcing 20 from May 13, and it looks like it could easily be replaced with some native GH opcode.

**Comment by scripthunter7** [comment]
@slavaleleka With this approach, "Send Slack notification **on failure**" will not run if the linting succeeded:

![image](https://github.com/AdguardTeam/AdguardFilters/assets/57285466/2bfaea4f-e9f4-4382-ba73-6e66229fa5e0)

While it ran earlier, since the job had to be started to establish the conclusion:

![image](https://github.com/AdguardTeam/AdguardFilters/assets/57285466/d9c0f365-dffe-4a62-b34e-24a4b2ffd2a4)
