### ISSUE TITLE
[Android Mobile] Disney+ ad problem

### ISSUE THREAD

**Issue by Barzaquaa** [AdguardTeam/AdguardFilters#174633]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.3.1

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

Disney+ Ads

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Language-specific

Liste FR

### Add your comment and screenshots

Hello, 

I have a problem with ad blocking on the Disney+ Android Mobile application.  I have the version of Disney+ with ads and when I get to a point where there are ads, Adguard blocks the ads but I lose a few seconds of the video, it skips a song and even if I go back impossible to see the song that was skipped. I haven't had this problem since Dinsey+ on browser. I think the problem comes from blocking the url "eu-west-1.ads.digital.disneyadvertising.com". 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
I don't have an account.
@piquark6046 please check. I found your commit https://github.com/AdguardTeam/AdguardFilters/commit/989cde506d168a6c8468caadc10b3a19a756f7aa
Maybe that domain can be unblocked for the app.

**Comment by BlazDT** [comment]
I have ad supported account, but no ads shown without AdGuard :(
Mentioned URL not requested, only sdk.iad-03.braze.com which is blocked.

**Comment by Barzaquaa** [comment]
I made a short video to show what it does.

As soon as I get to an ad, AdGuard blocks the ad very well, but then I miss between 5 and 10 seconds of the video. If I don't block "eu-west-1.ads.digital.disneyadvertising.com" as soon as I get to the ad, I do get the full 1 minute of ad, but I resume where I left off without missing between 5 and 10 seconds of the video. This happens on Android Mobile and Android TV, but I have no issues on the Chrome browser with the AdGuard extension.


https://www.youtube.com/shorts/kCfjKvaAuMg

**Comment by Barzaquaa** [comment]
> Got it. This app https://play.google.com/store/apps/details?id=com.disney.disneyplus ? If so, please test instead of custom rules `@@||ads.digital.disneyadvertising.com^$app=com.disney.disneyplus`


Hello, yes, that's the right application.

After applying the rule, I end up with ads :(

**Comment by Alex-302** [comment]
@Barzaquaa On Android 8+ we can't filter HTTPS of non-browser apps without root access, so we can't block or modify a specific request:(

**Comment by Alex-302** [comment]
But how critical is this problem? Video ads are inserted between different scenes, and usually something important doesn't happen in the first few seconds of a new scene. Isn't it?

**Comment by Barzaquaa** [comment]
On Disney+, the ads are really randomly placed. Several times, I found myself missing information to understand the following scenes, so it's really annoying. 

Well, I'm going to cancel my Disney+ subscription and download the series directly. At least then I won't have any ads.

Thanks for your help.

**Comment by Alex-302** [comment]
@Barzaquaa Ok. The rule was added in https://github.com/AdguardTeam/AdguardFilters/commit/050049a42ce0b2ce10b1d146399f19be364e635c


> and download the series directly

I also prefer it)
