### ISSUE TITLE
mega-enlace.com

### ISSUE THREAD

**Issue by Rust1667** [AdguardTeam/AdguardFilters#174863]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.13

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

mega-enlace.com

### Ad Blocking

AdGuard Base filter

### Language-specific

AdGuard Spanish/Portuguese filter

### Add your comment and screenshots

broken link shortener with AdGuard enabled: `mega-enlace.com`

I won't post an example link, because it only works when you arrive at the link shortener coming from one of the sites that use it. _(If you go to the link shortener directly it just redirects to google.com)_

Sites that use it:  (Spanish downloads sites)
```
https://pelisenhd.org/
https://www.latinomegahd.net/
https://gatonplayseries.com/
https://www.peliculasgd.net/
https://www.tododvdfull.com/
```

The main issue seems to be that this link shortener site forces you to click on some ads to move forward. But those ads are blocked by AdGuard.

_note: this link shortener site seems to save your IP address to grant you access for 24h to the downloads, once you complete the steps. This access permission is independent for each of the movie websites._

the link shortener uses these auxiliary domains: 
`todoandroid.live|gadgetzona.net|freeserverhostingweb.club|qwanturankpro.com|notipostingt.com`
`todoandroid.live,gadgetzona.net,freeserverhostingweb.club,qwanturankpro.com,notipostingt.com`
It is in these domains where the ads should show up, so we can click them. But they are blocked, so I can't move forward through the link shortener.

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
As far as I can see, we already have a rule to fix it and it works fine on my end (it shouldn't be necessary to click on ads, but wait 30 seconds).
The problem is that extension for Firefox cannot update/download new JavaScript rules.
Could you please add this rule:
```adblock
mega-enlace.com#%#!function(){const e = e=>{const o=new XMLHttpRequest;o.open("POST","/check.php",!0),o.setRequestHeader("Content-type","application/x-www-form-urlencoded"),o.send("a");const t=atob(window.ext_site).replace(/[a-z]/gi,(e=>String.fromCharCode(e.charCodeAt(0)+(e.toLowerCase()<="m"?13:-13))));let n=e.replaceAll('\\"','"');n=n.replace("'+ api_key+ '",window.api_key),n=n.replace("'+ link_out+ \"",window.link_out),n=n.replace(/action="'\+ .*?\+ '"/,`action="${t}"`);var a;const i=(a=n,(new DOMParser).parseFromString(a,"text/html")).querySelector("form"),r=new FormData(i),c=new XMLHttpRequest;c.open("POST",t,!0),c.send(r),window.tab2=window,postMessage("_clicked_b",location.origin)},o={apply:(o,t,n)=>{if(n[1]&&n[1].includes("api_key")){const o=window.link_out,t=window.api_key,a=n[1].match(/window\.open\(.*?\(atob\(main_site\)\).*?("\/.*\.php\?.*=").*?("&.*?=").*?(api_key),"view"/),i=a[1].replaceAll('"',""),r=a[2].replaceAll('"',""),c=n[1].match(/<form target=[\s\S]*?<\/form>/)[0];if(n[1]=n[1].replace("window.location.href","var nulled"),n[1]=n[1].replace("window.open(f","location.assign(f"),n[1]=n[1].replace(/(parseInt\(c\.split\("-"\)\[0\]\)<= 0).*?(\)\{)/,"$1$2"),o&&t&&i&&r&&c)try{"loading"===document.readyState?window.addEventListener("load",(()=>{e(c)}),{once:!0}):e(c)}catch(e){console.debug(e)}}return Reflect.apply(o,t,n)}};window.Function.prototype.constructor=new Proxy(window.Function.prototype.constructor,o)}();
```
to user rules, then click on any link which redirects to `mega-enlace.com`, wait a moment (timer should start automatically), then wait 30 seconds and click on the link to destination page.

**Comment by Rust1667** [comment]
Both rules are working perfectly, thank you.

**Comment by AdamWr** [comment]
I'm glad that problem has been solved.
These rules should be available in one of the next Firefox extension update.

**Comment by pastormorris** [comment]
Y ahora que hacemos con esto?

https://www.peliculasgd.net/reminiscencia-2021-brrip-1080p-latino-googledrive-ivan092/

https://external.neworldtravel.com/l.php?o=T29rT1laczJWUGFiaHE3UzVjZmQ0TnFGejFQUU9aN0NhUk95K2psSVppWE1oaDc1U29NWDhFR2dFcGZleDcySEpHWTd2M01LUVZZdDhSNzAzWWVkVXo4WHJ0L2QzcDU4RzJoYmVHRkQrdytyWnU0UU9CNnY2V2x1RUlwMTdSakVzeHR6RHFmaGQ2TitreGttYWthSVRLckd4N09yWkZxWS9mdFBCeGUrdEJjPQ==

**Comment by AdamWr** [comment]
I have added `neworldtravel.com` to current rules.
If you use AdGuard app or MV2 extension in Chromium based browser, then filters update should be available in 1-2 hours.
In the case of MV3 and Firefox extension, new JS rule will be available in one of the next extension updates.

**Comment by pastormorris** [comment]
> He añadido `neworldtravel.com`nuevas reglas a las actuales. Si usas la aplicación AdGuard o la extensión MV2 en un navegador basado en Chromium, la actualización de los filtros debería estar disponible en una o dos horas. En el caso de MV3 y la extensión de Firefox, la nueva regla de JavaScript estará disponible en una de las próximas actualizaciones de la extensión.

Thank you so much! I'm very grateful.
I'll wait a few hours to try.
