### ISSUE TITLE
Filemoon ads

### ISSUE THREAD

**Issue by technodrk** [AdguardTeam/AdguardFilters#174871]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Getting rid of the ad blocker detected message on Filemoon, a video source used on pirated movie and anime sites

### Proposed solution

Frankly, I don't know how to solve it.

### Additional information

"
Access Denied.

We have detected that your adblocker is agressively blocking our ads. In order to maintain our website we have blocked your request.

No ads No Videos. Sorry.
" You can't watch the video at all because a message popped up.

**Comment by jellizaveta** [comment]
@technodrk Hello. Could you please send links to the sites that reproduce the problem and your blocker configuration?

**Comment by technodrk** [comment]
> @technodrk Hello. Could you please send links to the sites that reproduce the problem and your blocker configuration?

The site I'm having problems with is https://moonembed.xyz/ as ghajini said (https://filemoon.sx/e/ofdwvww5uv1v as an example of a video address) and when you say blocker configuration, are you referring to the ad filters I'm currently using?

**Comment by technodrk** [comment]
![Ekran Alıntısı](https://github.com/AdguardTeam/AdguardFilters/assets/153454840/17e09efb-0472-460b-b5c1-40e4cb374587)
the warning text that pops up

**Comment by jellizaveta** [comment]
When accessing the site: `This video cannot be watched under this domain`.  Which country's IP should I use?

> when you say blocker configuration, are you referring to the ad filters I'm currently using?
Yes

**Comment by technodrk** [comment]
If it is due to the country I am in as an ip address, my country is turkey

**Comment by technodrk** [comment]
How do I send you my filter lists on ublock?

**Comment by technodrk** [comment]
By the way, I apologize for the quality of the answers I gave, I used a translation tool because my English is not enough to speak so much.

**Comment by technodrk** [comment]
I will be unavailable for the next 4 hours, I hope I have been supportive enough.

**Comment by jellizaveta** [comment]
Thank you for the information provided, updated the filters for this file sharing service (https://github.com/AdguardTeam/AdguardFilters/commit/4b26ae68c60eca61b416d48c56a6eea7e237411b ) , will be available with the new update within 1-2 hours

**Comment by MuhammetEminCakir** [comment]
`https://filemoon.sx/e/ofdwvww5uv1v`
I tried link above and it redirect me to this link ([https://fmoonembed.pro/adblock.html](https://fmoonembed.pro/adblock.html)) for some reason.
![image](https://github.com/AdguardTeam/AdguardFilters/assets/64583157/c1a981e4-a79a-4b66-a65e-bb998eb0203c)
Also fmoviesz.to (with filemoon player) appears to detect ad blockers
![image](https://github.com/AdguardTeam/AdguardFilters/assets/64583157/8cf53421-cde1-4a8b-90b1-3577f235affc)

I recommend you to add the same rules in the links shown below maybe this can solve the problems.
![image](https://github.com/AdguardTeam/AdguardFilters/assets/64583157/deb14ff5-a6e0-4eed-b4bc-ad03bb21019c)
 
BTW i'm using Chrome browser(AdGuard Browser Extension v4.3.13) with AdGuard Base and AdGuard Annoyances filters
