### ISSUE TITLE
[NSFW] http://blobopics.biz/

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#17485]
**Site Sample** | 
------------------|
http://blobopics.biz/share-7A3D_5B0D2EEA.html

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.3.974.3223**
Stealth mode: | disabled

Filters enabled |
----------------|
`english ** spy ** annoyances ** polish main ** polish adguard suplement ** KAD (fraud/scam) ** I don't care about cookies `

### Issue:

Ads, popups
<details><summary><b>Screenshot:</b></summary>

![20180603-003-screenshoot](https://user-images.githubusercontent.com/9846948/40888147-095420c4-6753-11e8-80e9-8597e4c8dbd2.png)
![20180603-001-screenshoot](https://user-images.githubusercontent.com/9846948/40888092-83a8cea2-6752-11e8-81c0-e2bed981eb95.png)
![20180603-002-screenshoot](https://user-images.githubusercontent.com/9846948/40888093-83cdffce-6752-11e8-9fc6-0317eb951fdb.png)

</details><br/>

**Comment by BlazDT** [comment]
Initial 18+ warning popup will stay.
