### ISSUE TITLE
[Android] anwap.org - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1748]
![image](https://cloud.githubusercontent.com/assets/15856304/13738787/f38d86e8-e9cf-11e5-8ee0-6b583d3c2cdb.png)

 "enabledFilterIds" : [ 2, 3, 4, 5, 1, 11 ],
  "environment" : "prod",
  "filteringQuality" : "FULL",

TST-536-96299

**Comment by Alex-302** [comment]
Добавил
||lux-static.ru^
anwap.org##.MIXADVERT_NET
anwap.org##.footrek

**Comment by vgavrish** [comment]
http://anwap.org/
![screenshot_22](https://cloud.githubusercontent.com/assets/18548949/15990507/d7b0d420-309c-11e6-9f2c-947c6e85a686.jpg)

**Comment by Alex-302** [comment]
Поправил.

**Comment by vgavrish** [comment]
Вин. 
http://anwap.org/android/
http://prntscr.com/bnt3cj

**Comment by Alex-302** [comment]
Это мобильный сайт, и посещать нужно с соответствующим фильтром.
Верхний подправил.

**Comment by vgavrish** [comment]
Андроид
Фильтры 1,2,3,4,,11,14
Реклама на главной Anwap.org
http://prntscr.com/c54w5b

**Comment by Alex-302** [comment]
Поправил.

**Comment by vgavrish** [comment]
Андроид
На главной Anwap.org
Фильтры 1,2,3,4,,11,14
![image](https://cloud.githubusercontent.com/assets/18548949/19235366/fa40140e-8ef9-11e6-9281-8007a3df974d.png)

**Comment by Alex-302** [comment]
Поправил.

**Comment by vgavrish** [comment]
http://anwap.org/serials/
Вниз листая появляется также рекламный блок. Фильтры те же.
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19314830/3296de36-90a4-11e6-8078-535d6948c721.png)

**Comment by Alex-302** [comment]
В Дроиде пока невозможно тот баннер скрыть.

**Comment by vgavrish** [comment]
@Alex-302 А когда примерно можно будет? Пользователь спрашивает.

**Comment by Alex-302** [comment]
@vgavrish 
можно в бете проверить такие правила:
```
anwap.org##body > div[class*=" "][-ext-has='a[href^="/asd/"]']
anwap.org##div[class*="footrek"]
anwap.org##div.my_razdel[-ext-has='a[href^="/asd/"]']
```

**Comment by vgavrish** [comment]
вроде бы не наблюдаю баннера
можно передать пользователю?

**Comment by Alex-302** [comment]
да, только пусть бету установит, и вручную не набирает

**Comment by Alex-302** [comment]
Добавил в мобильный фильтр
```
anwap.org##.my_razdel div.zag[-ext-has='a[href^="/asd/"]']
```

**Comment by evgeniy-ADG** [comment]
Реклама есть. Нужно
а) зарегистрироваться и залогиниться
б) пойти в Сериалы или Фильмы
в) увидеть рекламу
<details>
![screenshot_20161023-130801](https://cloud.githubusercontent.com/assets/15856304/19625499/09518800-9923-11e6-93fb-a0810d61dfb6.png)

</details>
фильтры свежие

**Comment by Alex-302** [comment]
@vgavrish 
какая версия Адгарда?

**Comment by vgavrish** [comment]
была бета 2.8.1

**Comment by Alex-302** [comment]
странно. Добавил ещё
```
anwap.org##body > div > div[class*=" "][-ext-has='a[href^="/asd/"]']
```
на нынешней лучше проверить, 2.8.15

**Comment by vgavrish** [comment]
http://anwap.org/film/ 
в разделе Фильмы осталось только: http://prntscr.com/cyuc45
в других разделах нет

**Comment by Alex-302** [comment]
добавил
```
anwap.org##.my_razdel[-ext-has='a[href^="/asd/"]']
```

**Comment by vgavrish** [comment]
1426828
реклама на главной
Фильтры 1,2,3,4,,11,14
Хром
лог время 11.59
[debug (18).txt](https://github.com/AdguardTeam/AdguardFilters/files/671762/debug.18.txt)

![image](https://cloud.githubusercontent.com/assets/18548949/21467040/aa42d8aa-c9e7-11e6-82d1-2d0a1e15dd7d.png)

**Comment by Alex-302** [comment]
Поправил.
