### ISSUE TITLE
Unable to earn rewards at store.dsc.starbucks.co.jp

### ISSUE THREAD

**Issue by elvis-hrvat** [AdguardTeam/AdguardFilters#174963]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.13

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://store.dsc.starbucks.co.jp/store-v2/product?locale=ja-jp

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

AdGuard Tracking Protection filter, EasyPrivacy

### Add your comment and screenshots

1. When I have either AdGuard Tracking Protection or EasyPrivacy enabled, on the store.dsc.starbucks.co.jp card order page https://capi.cashstar.com/v4/promo/limit/ POST requests to /will_exceed_promo_limit/ will result in a 401 error.
This will prevent you from taking advantage of the limited time promotion.
Note that this promotion runs approximately every other month.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please provide steps to reproduce and screenshot.
Also reports should be sent from AdGuard meny, not from Github
![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/71e926a8-9efd-4e64-bd8a-97caa39c7348)

**Comment by Alex-302** [comment]
Link is not working
![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/66b54bd7-da14-4aca-bc91-3fcf89d83f31)
