### ISSUE TITLE
bebetei.ro

### ISSUE THREAD

**Issue by andreewmat** [AdguardTeam/AdguardFilters#174913]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Ublock Origin with AdGuard Cookie Filter

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://comenzi.bebetei.ro/

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Cookie Notices filter

### Add your comment and screenshots

1. <comment> On the listed website `comenzi.bebetei.ro`,  if I add some products in the cart and then process thorugh checkout, the items cannot be seen. 
2. I have enabled both `AdGuard – Cookie Notices` and `EasyList – Cookie Notices` and even if I disable one of them, the problem is still there. Only if I disable both of them everything works fine.

3. Screenshots
 Let's get this page of bebtei.ro 'https://comenzi.bebetei.ro/hrana-bebe/formule-lapte-praf-bebe/formule-lapte-praf-de-crestere/" and add the first product in the cart.
<details><summary>Screenshot 1 with filters disabled:</summary>

 
![image](https://github.com/AdguardTeam/AdguardFilters/assets/79897301/3a61a4c4-0b9b-449d-b388-6361ba16cca3)

</details>

<details><summary>Screenshot 2 with filters enabled:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/79897301/7432cd68-165d-441f-9efb-3fb2466692ec)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reproduced. Please show the filtering log.

**Comment by andreewmat** [comment]
@Alex-302 :
<details><summary>Here is the log:</summary>


![image](https://github.com/AdguardTeam/AdguardFilters/assets/79897301/c4b0e33b-5be5-4ede-859f-7b2b94957195)

**Comment by Alex-302** [comment]
Please test in user rules
`@@||consent.cookiebot.com/uc.js$domain=comenzi.bebetei.ro`

**Comment by andreewmat** [comment]
@Alex-302 This filter works with the cart issue but is also enable the consent about cookie collect data. I guess this consent is the culprint of the issue with the cart?
