### ISSUE TITLE
www.mako.co.il - anti adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1750]
![image](https://cloud.githubusercontent.com/assets/15856304/13743220/35162a16-e9e9-11e5-8f00-aeecc5bfa37d.png)

http://www.mako.co.il/mako-vod-keshet/big_brother-s7/VOD-eea80828fe06351006.htm?sCh=3d385dd2dd5d4110&pId=1825219677

**Comment by Alex-302** [comment]
try these rules:
```
@@||akamai.advsnx.net/CDN/mako/mako.swf$domain=mako.co.il
@@||pubads.g.doubleclick.net/gampad/ads?ad_rule=$domain=mako.co.il
```
