### ISSUE TITLE
homemoviestube.com

### ISSUE THREAD

**Issue by cotesta** [AdguardTeam/AdguardFilters#175178]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.56.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

homemademoviestube.com

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

EasyPrivacy

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Add your comment and screenshots

1. homemoviestube.com breaks when the "Adguard - Ads" filter is enabled in uBlock Origin, the player for videos doesn't show up properly, thus I can't start playing any videos. Screenshot below shows how it looks, without that filter enabled a play button will show in the center of the video and I can click it to play videos properly.

2. Screenshots
<details><summary>Screenshot 1:</summary>
[https://imgur.com/a/4WqKnOh]

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Not reproduced on my end. Try to update the filters, clear browser data, restart it, open the site.

**Comment by zloyden** [comment]
I've also removed some ads there.
