### ISSUE TITLE
Cleanup duplicate rules in BaseFilter (foreign - Azerbaijani)

### ISSUE THREAD

**Issue by SKEIDs** [AdguardTeam/AdguardFilters#175355]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

There are multiple duplicate rules present in the filters.

```
##.ads
##.banner
##.banners-right
##.banners-top
##.bg-bnr
##.blk_rek
##.blockreklam
##.lazyLoadAd_places
##.makerekframe
```

### Proposed solution

Remove redundant rules or merge multiple rules into a single rule where possible.

### Additional information

These rules are grouped by domain, so I was unable to determine whether I should merge the rules. 
If necessary, the maintainer side should merge them or please send a comment on the pull request.
Here are examples of such rules:

`##body > a[href="http://unvan.az"][target="_blank"]`
https://github.com/AdguardTeam/AdguardFilters/blob/ce676c288a446dd200c62b983925133de2a4e1a9/BaseFilter/sections/foreign.txt#L813
https://github.com/AdguardTeam/AdguardFilters/blob/ce676c288a446dd200c62b983925133de2a4e1a9/BaseFilter/sections/foreign.txt#L925

`##.ainsyndication`
 https://github.com/AdguardTeam/AdguardFilters/blob/ce676c288a446dd200c62b983925133de2a4e1a9/BaseFilter/sections/foreign.txt#L616
https://github.com/AdguardTeam/AdguardFilters/blob/ce676c288a446dd200c62b983925133de2a4e1a9/BaseFilter/sections/foreign.txt#L674

**Comment by Alex-302** [comment]
Done. The most of the rules are obsolete.
