### ISSUE TITLE
AdGuard blocks Microsoft Active Directory B2C login calls (ad short for active directory)

### ISSUE THREAD

**Issue by AndyGettingAn** [AdguardTeam/AdguardFilters#175330]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

v4.3.13

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

receipts.anybill.de

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. <comment>

Our website uses Microsoft Active Directory login calls to login users. The URL of the login calls are build as following

https://adanybill.b2clogin&com/ad.anybill.de/....

**Descr:**
AppGuard recognizes "ad" as advertisment and blocks the API Call resulting in users not being able to login into our website when AppGuard is enabled.

**Repro steps**
Try to login with any credentials on the receipts.anybill.de website. When receiving a generic error message, App Guard blocked the API Call. Receiving specific error message means that App Guard did not block the API Call

**Expected behaviour**:
AppGuard should exclude b2c login calls from the rule to avoid login and token calls being blocked.

**Rule:** 
.com/ad.&domain=~ad-tuning.de 

2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="1275" alt="Screenshot 2024-03-20 at 09 49 56" src="https://github.com/AdguardTeam/AdguardFilters/assets/24636447/64f63a38-a3f8-402d-b5f2-2766d11a74ad">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Removed few minutes ago)
https://github.com/AdguardTeam/AdguardFilters/commit/5cd880685a4e64d9be664e0db638f0e3f229c528#diff-7e2b028bfe84b5fba383f2749cefa8833db442113164182ca766d10ddd3418a6L315
