### ISSUE TITLE
На кэшированных страницах pikabu.ru отваливается фильтрация

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#175387]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [ ] AdGuard product version is up-to-date;
- [ ] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.11/54

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.ozon.ru

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies

### Add your comment and screenshots

1. С недавних пор (раньше такого не было) предзагруженная браузером (после его перезапуска) страница на pikabu лезет полностью неотфильтрованной. Причём неотфильтрованной никак. Ни пользовательскими фильтрами, ни подписочными. Запросов при открытии страницы судя по журналу идёт уйма, т.е. реклама как минимум грузится не из кэша. В общем, на ресурсе стали использовать какой-то хитровыделанный трюк, чтобы не так, так так показать рекламу.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot_20240321_125227](https://github.com/AdguardTeam/AdguardFilters/assets/12525093/1e605602-ce89-4396-b608-2f0687ce52b2)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Какой сертификат при этом браузер использовал? Подобного на 4.3.1 не наблюдаю, реклама блокируется корректно.
Попробуй обновиться до актуальной версии 4.3.1, затем обнови фильтры (рекомендуется также включить наш скрипт AdGuard Extra в настройках), очисти данные браузера и перезапусти его.

**Comment by Baltazar500** [comment]
>Какой сертификат при этом браузер использовал? 

AdGuard

<details>

![2024 03 26_19 14 10~01](https://github.com/AdguardTeam/AdguardFilters/assets/12525093/2f3caab8-9b21-4e9f-9558-da9ef450e42e)

</details>

>Попробуй обновиться до актуальной версии 4.3.1, затем обнови фильтры

Включён по умолчанию. И не выключался.

>очисти данные браузера и перезапусти его.

Пробовал. Не помогает. Клинит именно что pikabu. На других ресурсах такого не наблюдается.

**Comment by zloyden** [comment]
> Как это сделать под ведром 5.1 ?

Здесь никак, видимо только на новом устройстве.
С актуальной версией такого не наблюдаю.

> Включён по умолчанию. И не выключался.

Экстра также блокирует рекламу на пикабу. Какая версия стоит? А если сайт открыть в инкогнито будет также?

**Comment by Baltazar500** [comment]
С очисткой кэша всё же есть нюанс.

Если кэш очистить, предварительно выкинув из фона браузер, то страница прогрузится нормально т.к. грузится заново. Но каждый раз чистить кэш перезапуская браузер - такое себе занятие. Такое впечатление, что страницы пишутся в кэш сейчас в неотфильтрованном виде. Я ХЗ :/

>Экстра также блокирует рекламу на пикабу. Какая версия стоит? 

1.0.582

>А если сайт открыть в инкогнито будет также?

Инкогнито при выбрасывании браузера из фона закрывается. В рамках же обычной работы браузера в инкогнито проблем нет. Равно как и в нормальном режиме.

**Comment by Baltazar500** [comment]
>Проверил подобный сценарий без очистки кэша на 4.3.1 и такое не повторяется. 

А вы проверяете "с" авторизацией на на ресурсе или "без" ? Без авторизации я на своей конфигурации проблем тоже не вижу. А вот будучи авторизованным, вижу всё вышеописанное и даже больше (см. ниже).

>Ещё наблюдаю такое, если возвращаюсь на страницу назад. Т.е. перейдя по любому линку в рамках той же вкладки на pikabu (например подписки), а потом ткнув "назад" получаю страничку без какой-либо фильтрации.
