### ISSUE TITLE
msn.com

### ISSUE THREAD

**Issue by Aidolii** [AdguardTeam/AdguardFilters#17542]
The Sets feature in Windows 10 RS5 has a 'New Tab' button that opens the following URL to show Apps: www.msn.com/compass/ntphost (Cannot be navigated to naturally.)

However it does not function correctly without the following exceptions:

msn.com#@#[src*="base64"]
msn.com#@#[src*="data:"]

I tried to make the filters more specific but every time I tried, it broke.

**Comment by Alex-302** [comment]
Hi
I see only blank page, even without AdGuard.
This is Easylist issue(our base filter = Easylist+our fixes). You can report here: https://github.com/easylist/easylist/issues

**Comment by Aidolii** [comment]
>I see only blank page, even without AdGuard.

You can only get to it by opening New Tab in a Windows Insider build unfortunately. I'll try reporting it there.

**Comment by Alex-302** [comment]
I don't have the Insider build.
Ok, added 
```
msn.com#@#[src*="base64"]
msn.com#@#[src*="data:"]
```

**Comment by Alex-302** [comment]
Please make ckreenshot(s) how to reproduce it.
