### ISSUE TITLE
Error in Safari

### ISSUE THREAD

**Issue by rnixs** [AdguardTeam/AdguardFilters#175444]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Safari

### AdGuard version

latest

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

apkmirror

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. <comment>
I saw the issue and found that there was a problem with the adshield in apkmirror.
So, after checking the adshield domain, I checked that popup filter works differently in safari.
I made an exception to the shield pop-up filter and it worked well. When I turned on the adguard, the domain request seems to be blocked.
In safari, I think we need to block the pop-up in another way.
So there was no problem with Chrome and firefox, but I think it was a problem because the filter worked differently in Safari.
<a href="https://github.com/AdguardTeam/AdGuardForSafari/blob/master/ElectronMainApp/filters/2.txt">Filters that are only problematic in Safari</a>

2. Screenshots
<details><summary>User rules</summary>

<img width="697" alt="image" src="https://github.com/AdguardTeam/AdguardFilters/assets/81290656/5aae7902-8c2c-4672-9b4e-60f13f8e41b7">

</details>

<details><summary>Enable user rules</summary>

<img width="702" alt="image" src="https://github.com/AdguardTeam/AdguardFilters/assets/81290656/f1155a38-5622-4c0b-a44c-8162b8ba6206">

</details>

<details><summary>Disable user rules</summary>

<img width="702" alt="image" src="https://github.com/AdguardTeam/AdguardFilters/assets/81290656/f909127c-61ad-489c-aea5-5b4f6bab4537">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
Cannot reproduce the issue and invalid screenshots [^1].
Please install microShield userscript (Its installation instruction written in Korean language is available at https://community.list-kr.com/docs/AdGuard/Userscripts/microShield ).

[^1]: The domain in the screenshot and `apkmirror.com` are not same.

**Comment by piquark6046** [comment]
![image](https://github.com/AdguardTeam/AdguardFilters/assets/98787049/4313a300-2d95-4ac7-bb6e-13f56363dc62)

**Comment by rnixs** [comment]
@piquark6046 
The reproduction method is to turn on the adguard basefilter on safari honkailab.com and wait for about 5 seconds to cause this problem.

**Comment by piquark6046** [comment]
@rnixs I can reproduce when I visit `honkailab.com`. However, the issue can be fixed by microShield userscript.
Why do you not install the userscript?

**Comment by rnixs** [comment]
MicroShield will solve the problem,
I'm just checking and letting you know that pop-up filter works differently in Safari.
