### ISSUE TITLE
animeunity.to

### ISSUE THREAD

**Issue by e075e** [AdguardTeam/AdguardFilters#175468]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

ublock 1.56.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.animeunity.to/anime/4906-undead-unluck

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

Episode numbers under the video are missing

Screenshots
<details><summary>issue with adguard:</summary>

![Screenshot_20240321-225257_Fennec](https://github.com/AdguardTeam/AdguardFilters/assets/15078341/df32fd5a-7580-480d-b6ab-d0038e58df80)

</details>

<details><summary>without adguard</summary>

![Screenshot_20240321-225211_Fennec](https://github.com/AdguardTeam/AdguardFilters/assets/15078341/9c1ebb97-a63a-4cbe-ab48-93f68daf520c)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reproduced

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/c24ada77-b42f-48ac-bc5e-6d6882b71e2b)


</details>

**Comment by Alex-302** [comment]
In general, this is uBO's CNAME problem - it matches and block CNAME of a domain, excluded in the regexp of the rule.
