### ISSUE TITLE
logs-partners.coupang.com

### ISSUE THREAD

**Issue by mAKEkr** [AdguardTeam/AdguardFilters#175772]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

`ad-shield.io` native ads solution is displaying coupang(korean commerce)'s ads and tracking users prefer items.

it looks like a same way into `criteo`

### Proposed solution

add `logs-partners.coupang.com`, `ads-partners.coupang.com` domain in `ko-KR` filters

### Additional information

![Honeycam 2024-03-27 04-55-13](https://github.com/AdguardTeam/AdguardFilters/assets/2796198/f8855c86-5780-448f-8fb6-e5bc28e8cbd9)

**Comment by piquark6046** [comment]
@mAKEkr Blocking the domains does not help to block adverts protected by Ad-Shield.
To block Ad-Shield adverts and analytics, please install [microShield userscript](https://github.com/List-KR/microShield).
Its installation instruction written in Korean language is available at https://community.list-kr.com/docs/AdGuard/Userscripts/microShield.

**Comment by piquark6046** [comment]
Also, Ad-Shield does not display only Coupang adverts.
Please refer https://www.ad-shield.io/blog/how-ad-shield-defeated-ad-blockers-while-others-failed.
