### ISSUE TITLE
||imasdk.googleapis.com^

### ISSUE THREAD

**Issue by pekkle-hksar** [AdguardTeam/AdguardFilters#175802]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

latest

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

mytvsuper app, hoytv app got wrong blocked by the rule and can't play video

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

The titled rule blocked too many video playing app in Hong Kong

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
We don't block this domain.

**Comment by Alex-302** [comment]
Please send report from AdGuard support menu.

**Comment by Alex-302** [comment]
Ah, `AdGuard for Android`.
Please try
`@@||imasdk.googleapis.com^$app=packake_name`


Where `packake_name` - ID from Google Play or from technical deyails, like `com.supercell.clashofclans` in https://play.google.com/store/apps/details?id=com.supercell.clashofclans

**Comment by pekkle-hksar** [comment]
Can unblock video playing after adding the custom rule
`@@||imasdk.googleapis.com^$app=com.tvb.mytvsuper`

**Comment by Alex-302** [comment]
Do you see ads in this case?

**Comment by pekkle-hksar** [comment]
Upto this moment, mytvsuper app doesn't have ads

**Comment by Alex-302** [comment]
Ok, added.
