### ISSUE TITLE
desidime.com

### ISSUE THREAD

**Issue by kunalagra** [AdguardTeam/AdguardFilters#175945]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

n/a

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.desidime.com/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

1. White boxes on Mobile and Desktop

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/66416646/ba646492-7a5e-4529-952a-c54ca48bfe48)
</details>

<details><summary>Screenshot 2:</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/66416646/8df024a1-7777-4593-a457-b6b4c411afdb)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
