### ISSUE TITLE
Ads in Yandeх search and main page

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#17601]
### Search 
`https://yandex.ru/search/?lr=213&text=%D0%BA%D1%83%D0%BF%D0%B8%D1%82%D1%8C%20%D1%82%D0%B5%D0%BB%D0%B5%D0%B2%D0%B8%D0%B7%D0%BE%D1%80`
* Ad blocker is not detected

<details>

![image](https://user-images.githubusercontent.com/8361299/40997785-799feeb4-690e-11e8-9eab-2d956fac3a30.png)

</details>

* When ad blocker is detected, all search resulst has the similar names.

<details>

![image](https://user-images.githubusercontent.com/8361299/40998573-e87bdce2-6910-11e8-9d1d-3ea358ab1b76.png)

</details>

### Main page

* Ad blocker is not detected

<details>

![image]()
![image](https://user-images.githubusercontent.com/8361299/40998473-977f3aaa-6910-11e8-88a4-5c67552b20aa.png)

</details>

* When ad blocker is detected, all elements names are obfuscated

<details>

![image](https://user-images.githubusercontent.com/8361299/40998390-5abbf32e-6910-11e8-8c81-d3df7d090846.png)

</details>

**Comment by ameshkov** [comment]
I'll get back to it next week once $replace rules start working on mobile
