### ISSUE TITLE
Altumcode anti-Adblock

### ISSUE THREAD

**Issue by SpotlightForBugs** [AdguardTeam/AdguardFilters#176556]
Applies to 

https://github.com/AdguardTeam/AdguardFilters/issues/176432

and

https://github.com/AdguardTeam/AdguardFilters/issues/176383

   
   Maybe a generic fix? `https://www.google.com/search?&q=%22We+serve+ads+so+we+can+keep+our+website+running.+Please+disable+your+ad+blockers.%22`
      
        Maybe a generic fix? `https://www.google.com/search?&q=%22We+serve+ads+so+we+can+keep+our+website+running.+Please+disable+your+ad+blockers.%22`

I tested in AdGuard, and these filters from uBO work fine

https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters-2023.txt#L1582-L1589
```
#@#.banner-ads
#@#.banner_ads
#@#.ad-zone
#@#.ad-space
##.banner-ads:not(.textads)
##.banner_ads:not(.textads)
##.ad-zone:not(.textads)
~nieru.net##.ad-space:not(.textads):not(.adbox)
```

from chp adblock:

https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters-2021.txt#L5123
https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters-2021.txt#L5125
```
#@#.ad-unit
~lamire.jp##.ad-unit:not(.text-ad):not(.textads)
```

_Originally posted by @D4niloMR in https://github.com/AdguardTeam/AdguardFilters/issues/176449#issuecomment-2041663967_

**Comment by SpotlightForBugs** [comment]
@D4niloMR I’ve created a new issue to address this idea

**Comment by zloyden** [comment]
Seems to be working fine on my end. I've exchanged the rules, update should be available soon.
