### ISSUE TITLE
trinixy.ru - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1766]
Пропущена реклама http://trinixy.ru/126996-kakim-byl-groznyy-vo-vremya-voyny-do-nee-i-posle-nee-71-foto.html
Скриншот: http://f1.s.qip.ru/Ogbqire3.png

**Comment by Vincent-Michael** [comment]
hm, i see no ads

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Возможно старые фильтры. Расширение или прога?

**Comment by Serzh-SUP** [comment]
@Alex-302 
У него расширение для Хрома.
Фильтры: фильтры: русский, английский, RU AdList

**Comment by Alex-302** [comment]
@Serzh-SUP у тебя повторяется? У меня чисто. Пусть RU AdList выключить попробует.
