### ISSUE TITLE
https://eztv.ag/ - pop-ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1768]
Confirmed:

> in the site https://eztv.ag/ whenever a link is clicked it is opening a new tab and runs and ad. For a little while Adguard used to block the ad and automatically close the new tab. But of late this is also not happening. The new tag starts with the URL http://ad.directrev.com/............. A java script or some such program appears to be running that is traps the mouse click and then launches the ad.directrev....... Even when Adguard blocks the new tab and closes it, one need to again click on eh same link to activate it. The mouse click trap happens on the first click, unless one refreshes the page at which time it again repeats.
> ![image](https://cloud.githubusercontent.com/assets/15856304/13818697/8fa2772a-eb9f-11e5-9032-3d926bc02def.png)

state <details>
Version: 5.10.2051.6368
Filtering mode: Redirect
Driver type: WFP
Ads blocked: 187895
Application lifetime: 292.20:34:13.2118539
Proxy settings: None
.NET version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile;
OS version: Microsoft Windows NT 6.2.9200.0
Language: en
HTTPS filtering: Enabled
Adblocker status: Enabled
Browsing Security status: Enabled
Parental Control status: Disabled

**Comment by Vincent-Michael** [comment]
try:
```
||storage.googleapis.com/prototype-lib/bin.js^$third-party
```

**Comment by Alex-302** [comment]
yes, it's time to make old rule as generic. Added

**Comment by spchtr** [comment]
It's because of the "data://" protocol in firefox, chrome, and in general HTML5.  I've discovered that if I go to about:config in firefox, and create a new boolean > "network.protocol-handler.expose.data" and set it to false, the popup new tabs no longer occur.  I have not tested enough to see if this breaks any desired functionality, but presumably the "data://" protocol is a suggested method of including images in html5.  So far I have not noticed anything missing from sites that I frequent.  Aside from the annoying and potentially malicious new tab popups, several of which were being caught by my antivirus.

**Comment by Alex-302** [comment]
@spchtr but I don't see any clickunders here

**Comment by zebrum** [comment]
@Alex-302 
can you check it: by clicking on free space a new tab is opening 
only in firefox 

![screenshot 2017-03-20 16 52 40](https://cloud.githubusercontent.com/assets/23637588/24102653/ba9218b2-0d8d-11e7-85c3-83c7e45c4f51.png)

![screenshot 2017-03-20 16 52 50](https://cloud.githubusercontent.com/assets/23637588/24102663/c54e68f0-0d8d-11e7-9e79-53d2f176e8d1.png)

**Comment by Alex-302** [comment]
@zebrum it is absolutely clean on my side.

**Comment by evgeniy-ADG** [comment]
It's not on costumer's side. What do we do? There's no issues with the cert:

![image](https://cloud.githubusercontent.com/assets/15856304/24195653/3d85f754-0f03-11e7-9f02-32895dba2300.png)

More screenshots here: 1230830

**Comment by Alex-302** [comment]
@evgeniy-ADG I can check it via TeamViewer.

**Comment by zebrum** [comment]
@evgeniy-ADG please ask user about TV session
