### ISSUE TITLE
Telenor.no - Broken (AdGuard Cookie Notices filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#176955]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin v1.57.2

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.telenor.no/

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Cookie Notices filter

### Affected site:
`https://www.telenor.no/`

### Issue:
Site broken (no scrolling).

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **AdGuard Cookie Notices filter**

### Problem rule:
`cinemark.com,lavazza.it,parcelforce.com,iberostar.com,nsandi.com,forcepoint.com,vodafone.com,sony-asia.com,abnamro.com,avis.de,unipolsai.it,o2.co.uk,tsb.co.uk,sainsburysbank.co.uk,hsbc.co.uk,sunglasshut.com,oakley.com,telekom-dienste.de,zurich.it,ray-ban.com,lavazzagroup.com,sony.*,telenor.no,tescomobile.com,falke.com,disney.pl,thewaltdisneycompany.eu,shopdisney.eu,tuclothing.sainsburys.co.uk,epson.com.br,avisautonoleggio.it,qvc.it,gap.eu,disneyplusdayroom.com,sites.prh.com,khaleejtimes.com,tealium.com,robeco.com,totalenergies.de,centrum24.pl,hsbc.com,newbalance.*,sick.com,aktion-mensch.de,diesel.com,totalenergies.com,zurich.de,cineworld.co.uk,otterbox.de,dropbox.com,penguinrandomhouse.com,familienratgeber.de,barclaycard.co.uk,tuicruises.com,bahia-principe.com,open-telekom-cloud.com,t-systems.com,nh-hotels.de,magentasport.de,goertz.de,stepstone.de,smarthome.de,nuernberger.de,cloud.telekom-dienste.de,tui.com,france.tv,opendns.com,victoriassecret.com,huawei.com,argos.co.uk,tealiumiq.com,ti.com,disney.de,ups.com,macys.com,rakuten.de,telekom.de,trendmicro.com,epson.com,3m.com.tr,command.com.tr,virginmedia.com,francetvinfo.fr,greenmangaming.com,logitech.com,logitechg.com,webex.com###__tealiumGDPRecModal`
### Possible fix:
`telenor.no#$#html { overflow: auto !important; }`

### Note:
`https://www.online.no/` (another Telenor site) has the same cookie popup, so it can be blocked in the same way:
```
online.no###__tealiumGDPRecModal
online.no###global-overlay-background
online.no#$#html { overflow: auto !important; }
```
### Other problem filters:
* **EasyList - Cookie Notices** https://github.com/easylist/easylist/issues/18966/
`##div.privacy_prompt`

--

### System info:
* OS/version: Windows 10 Pro 22H2 (x64)
* Browser/version: LibreWolf v124.0.1-1 (x64) [Tracking Protection = Standard]
* Adblock Extension/version: uBlock Origin v1.57.2

### Privacy

- [X] I agree to follow this condition

**Comment by THEtomaso** [comment]
@BlazDT:

The overlay still remains @ `online.no`.

**Required fix:**
```
- telenor.no###global-overlay-background

+ online.no,telenor.no###global-overlay-background
```

**Comment by BlazDT** [comment]
Thanks for notice. Will be done tomorrow, on Android difficult to add via website.
