### ISSUE TITLE
patreon.com

### ISSUE THREAD

**Issue by NotaInutilis** [AdguardTeam/AdguardFilters#176924]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

ubo latest

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.patreon.com/posts/this-years-most-95119794

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Add your comment and screenshots

1. "Download our app" banner that blocks the whole page. This banner is hidden by EasyList - Annoyances - Notifications but in an incomplete manner: scrolling and clicking are still disabled. https://github.com/easylist/easylist/issues/18114

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot_20240412-111805_Trebuchet](https://github.com/AdguardTeam/AdguardFilters/assets/9675966/a00c7987-5e24-4a80-ba1a-96bb5fdc81d5)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
The trusted scriptlet filter that blocks the popup in AdGuard Mobile App filters list is not executed because of security reason.
Therefore, please enable uBlock filters - Annoyance.

**Comment by NotaInutilis** [comment]
Got it! Thanks for taking care of it and explaining the issue.
