### ISSUE TITLE
65330de breaks Google Auth

### ISSUE THREAD

**Issue by cdemi** [AdguardTeam/AdguardFilters#177127]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://accounts.google.com/gsi/client

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Annoyances filter, AdGuard Popups filter

### Add your comment and screenshots

It looks like https://github.com/AdguardTeam/AdguardFilters/commit/65330deaf78aca1082505b0cffacf51bde35c9b2#diff-5bdaceb0ea8139918a1360d6a80c930b3f5f8a690f0059423b232e5c981f6d58R30 introduced also a sneaky block to Google's auth script https://accounts.google.com/gsi/client

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Which site?

**Comment by Alex-302** [comment]
This rule may break some sites, but not often. So we add exclusions for this rule.

**Comment by cdemi** [comment]
For me it's happening on several sites that contain these buttons:
![image](https://github.com/AdguardTeam/AdguardFilters/assets/8025435/2a09b6c7-cc58-4026-81b9-fc7021966d4e)

Mostly they are product back-offices which use Google Login

**Comment by Toxblh** [comment]
@Alex-302 
This rule: `||accounts.google.com/gsi/client|$script,3p`

**Comment by ArgonAlex** [comment]
> This rule may break some sites, but not often. So we add exclusions for this rule.

This is the primary script for Google Sign-in, so it is not going to be rare at all. See https://developers.google.com/identity/gsi/web/guides/client-library

Example broken sites:
bestbuy.com
patreon.com
reddit.com

**Comment by Alex-302** [comment]
Already fixed.
