### ISSUE TITLE
replacement of sites whose registration has been canceled in the domain zone `BY`

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdguardFilters#177192]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Заменить (изменить, дополнить) в фильтрах правила по сайтам: 

### Proposed solution

`reform.by`  > `reform.news`
`media-polesye.by` > `media-polesye.com`

### Additional information

https://media-polesye.com/news/domennyh-imyon-lishili-v-belarusi-izvestnye-nezavisimye-portaly-novye-adresa/

**Comment by zubrRB** [comment]
`mediazona.by` > `mediazona.com`

**Comment by zubrRB** [comment]
`ex-press.by` > `ex-press.live`

**Comment by zubrRB** [comment]
@Sergey-Lyapin не все правила были перенесены по домену `reform`, поэтому снова проявились эти элементы   https://github.com/AdguardTeam/AdguardFilters/issues/173592.

**Comment by zubrRB** [comment]
@Sergey-Lyapin Mediazona (сайты) разные есть: средназиатская, российская, а белорусская переехала именно на `.com`.

**Comment by Sergey-Lyapin** [comment]
@zubrRB mediazona.com пока не работает

**Comment by zubrRB** [comment]
mediazonaby.com

**Comment by zubrRB** [comment]
`reform.news##.wpremark:has(> div.wpremark-body > div.wpremark-content > p > a[href="https://t.me/cult_front"])`
@Sergey-Lyapin И нужно вернуть это правило, которое скрывало подписку на канал в Telegram. 

<details><summary>Screenshot:</summary>

![-](https://github.com/AdguardTeam/AdguardFilters/assets/50718960/217669cd-3768-48b5-9042-7ea90dd6d687)

</details><br/>

**Comment by Sergey-Lyapin** [comment]
@zubrRB У меня этот элемент правилом `reform.news##blockquote.info` блочится

**Comment by zubrRB** [comment]
У меня — нет. https://reform.news/rasskaz-brazilskoj-pisatelnicy-devochka-iz-belarusi-popal-v-top-rejting-detskih-knig

**Comment by zubrRB** [comment]
@Sergey-Lyapin сохранённая страница: [REFORM.news.zip](https://github.com/AdguardTeam/AdguardFilters/files/15027378/REFORM.news.zip)

**Comment by zubrRB** [comment]
@Sergey-Lyapin у меня этот элемент указанным правилом не скрывается, сохранённая страница прикреплена выше.

**Comment by zubrRB** [comment]
@Sergey-Lyapin у меня этот элемент указанным правилом не скрывается, сохранённая страница прикреплена выше.

**Comment by zubrRB** [comment]
@Sergey-Lyapin ну ты правило-то верни на своё прежнее место...

**Comment by Sergey-Lyapin** [comment]
@zubrRB Вернул
