### ISSUE TITLE
m.iyf.tv

### ISSUE THREAD

**Issue by jason-lin008** [AdguardTeam/AdguardFilters#177129]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

latest version

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://m.iyf.tv/play/98EiYwl2y4D?id=VmWVXoGhFBF

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Annoyances

AdGuard Annoyances filter

### Language-specific

AdGuard Chinese filter

### Add your comment and screenshots

1. <comment>
A 20-second ad will appear at the beginning of the video。
2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="724" alt="A6FE859C44D612332982F11904A0538A" src="https://github.com/AdguardTeam/AdguardFilters/assets/126739505/14df2395-a2ed-4834-a82c-a6a7b90a7e7b">

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
I can't reproduce.
@AdamWr @piquark6046 Please take a look.

**Comment by piquark6046** [comment]
The advert is loaded on my side after `/api/Video/GetAdsDataList?$badfilter` is applied.

**Comment by jason-lin008** [comment]
> The advert is loaded on my side after `/api/Video/GetAdsDataList?$badfilter` is applied.

This is indeed the case, how should we solve this problem?

**Comment by Alex-302** [comment]
@jason-lin008 
Cannot reproduce with your settings. 
Please try to disable-enable content blockers in Safari settings and restart Safari, and check for filters update.
Do not close AdGuard window ~90 seconds, because iOS will breaks configuration process.

Also you may reboot a device.
