### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#177448]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.57.3b5

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://twitter.com

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter

### Add your comment and screenshots

1. <comment>
Google sign in never loads while signed out. Caused by `||accounts.google.com/gsi/client|$script,3p` in AdGuard popups

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot from 2024-04-19 13-58-25](https://github.com/AdguardTeam/AdguardFilters/assets/89158249/1a06da09-f9e4-4959-abf4-3f2d91f55803)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
@Sonic5435325 The filter was updated. Please update the filters lists and try again.
