### ISSUE TITLE
Allow users to report something for TRACKING. We have a label for that

### ISSUE THREAD

**Issue by SpotlightForBugs** [AdguardTeam/AdguardFilters#177694]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

See title

### Proposed solution
See title
https://github.com/AdguardTeam/AdguardFilters/issues?q=label%3A%22T%3A+Trackers%22+

**Comment by Alex-302** [comment]
Better write here
https://github.com/AdguardTeam/ReportsWebApp/issues/84
