### ISSUE TITLE
Malicious site report label 

### ISSUE THREAD

**Issue by SpotlightForBugs** [AdguardTeam/AdguardFilters#177691]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [x] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

At the moment, malicious sites just go under in the issues tab and don’t really get enough attention. 

### Proposed solution

I’d love to be able to submit bad sites in bulk and also with a label to allow for rapid responses. At the moment they don’t get enough attention. Also: please make a pattern detection system for malicious code to block them after getting loaded, don’t only rely on urls.

**Comment by DandelionSprout** [comment]
On paper, https://github.com/AdguardTeam/ReportsWebApp/issues would be very interested in the label part too, but the latter doesn't seem to get *all* that much work put into it, so you are indeed more likely to get a faster-ish response in this repo.

**Comment by Alex-302** [comment]
Antiphishing is not related to filters. You can send dangerous sites directly to support@adguard.com
