### ISSUE TITLE
Bradesco Fake Website

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdguardFilters#177659]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.17.1

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Firefox, Chrome, Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://atendimento-resgateib2.com/online/ibpfnovologin/

### Ad Blocking

AdGuard Base filter

### Social Widgets

AdGuard Social Media filter, Fanboy's Social Blocking List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### DNS filters

AdGuard DNS filter

### Language-specific

AdGuard Spanish/Portuguese filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Block third-party Authorization header, Block WebRTC, Hide Referrer from third-parties (specify in comment below, if used custom value), Hide your User-Agent (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests

### Add your comment and screenshots

1. 
Fake Bradesco Bank:
- https://atendimento-resgateib2.com/online/ibpfnovologin/
- http://vps52503.publiccloud.com.br/livesite525
- https://atendimento-desco.grupokustodio.com/online/home.php

Official website: https://banco.bradesco
2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>
<img width="958" alt="image" src="https://github.com/AdguardTeam/AdguardFilters/assets/16819380/d0a69b82-7656-4020-8f84-0ca221b207f2">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It seems they are dead, can't access.
