### ISSUE TITLE
thegamer.com

### ISSUE THREAD

**Issue by tbcam88** [AdguardTeam/AdguardFilters#177718]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

v4.3.1

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.thegamer.com/final-fantasy-7-vii-rebirth-character-folio-manuscript-location-guide/#every-manuscript-for-cloud-strife

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, I don't care about cookies

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

[324452706-89abe447-dae8-4218-a2b0-ef12b0b062b2](https://github.com/AdguardTeam/AdguardFilters/assets/19891537/6a18a9f4-6045-4b15-9923-29677a9ccdfa)

I'm experiencing cookie notices again not long after resetting browser. Are you able to reproduce on this URL?

Thanks.

### Privacy

- [X] I agree to follow this condition

**Comment by tbcam88** [comment]
> @tbcam88 Please write only the affected domain name in the title of issues (in this case, the title should be `thegamer.com`).

Done.

**Comment by tbcam88** [comment]
> @tbcam88 Please write only the affected domain name in the title of issues (in this case, the title should be `thegamer.com`).

Have I posted in the correct place? Unsure as there have been no reply from AdGuard support. Thanks.

**Comment by Alex-302** [comment]
@tbcam88 This is the correct way to report)
https://adguard.com/kb/guides/report-website/
