### ISSUE TITLE
http://www.alluc.ee/ - add + anti adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1777]
![image](https://cloud.githubusercontent.com/assets/15856304/13858135/ed1dc09e-ec85-11e5-95cc-be2f3853bb29.png)

![image](https://cloud.githubusercontent.com/assets/15856304/13858150/09fe8e0a-ec86-11e5-9b08-01420b708ff2.png)

Direct [link](http://www.alluc.ee/l/La-Femme-Infidele-1969-FRENCH-DVDRiP-x264-AAC-HuSh-www-zone-telechargement-com/vo2jyh6u)

**Comment by evgeniy-ADG** [comment]
The same player is on http://www.vkstreamingfilm.biz/
The same issue.

**Comment by Alex-302** [comment]
can't reproduce.
Check this rule
```
@@||alluc.ee/js/ads.js
```
