### ISSUE TITLE
Paywall on seekingalpha.com 

### ISSUE THREAD

**Issue by whynotnow2** [AdguardTeam/AdguardFilters#177753]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.3.1

### What type of problem have you encountered?

Missed ads or ad leftovers, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox, Chrome, Safari, Opera, other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://email-st.seekingalpha.com/click/35137351.29895/aHR0cHM6Ly9zZWVraW5nYWxwaGEuY29tL2FjY291bnQvZW1haWwtYXV0aD9zYWlsdGhydV9hdXRoX3BhcmFtPTI3NzU1MjkzOjE3MTM5MTMzMjk6ZWUyMjczZWQ1NjU2ZmVmZDU5Y2FjZDY5NjM1Y2FjODkmcmVmPWh0dHBzOi8vc2Vla2luZ2FscGhhLmNvbS9uZXdzLzQwOTI4ODMtZ29sZHMtc2hhcnAtdHdvLWRheS1jb3JyZWN0aW9uLW92ZXJkdWUtYW5kLWhlYWx0aHktYW5hbHlzdHMtc2F5JnV0bV9jb250ZW50PWxpbmstMSZ1dG1fc291cmNlPXNlZWtpbmdfYWxwaGEmdXRtX2NhbXBhaWduPXJ0YS1zdG9jay1uZXdzJm1lc3NhZ2VpZD0yOTAwJm1haWxpbmdpZD0zNTEzNzM1MSZzZXJpYWw9MzUxMzczNTEuMjk4OTUmdXRtX3Rlcm09MzUxMzczNTEuMjk4OTUmc291cmNlPWVtYWlsXzI5MDA/60c1e4b62b40fa103225d95eB5f7e3352

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Fanboy's Enhanced Tracking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, Web Annoyances Ultralist, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Other

Filter unblocking search ads and self-promotion

### DNS filters

AdGuard DNS filter

### Language-specific

AdGuard French filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Disable cache for third-party requests, Block third-party Authorization header, Block WebRTC, Block Push API, Block Location API, Hide Referrer from third-parties (specify in comment below, if used custom value), Hide your User-Agent (specify in comment below, if used custom value), Mask your IP address (specify in comment below, if used custom value)

### Add your comment and screenshots

1. Paywall pop up is opening. Unable to read the articles from seekingalpha.com. 

![Screenshot_20240424-100849](https://github.com/AdguardTeam/AdguardFilters/assets/30954799/e54b7693-2ff2-4566-b2b5-fd3de4c0f2f5)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by whynotnow2** [comment]
How to proceed to add this filter please? Thanks

**Comment by whynotnow2** [comment]
Where is it in settings? Thanks

**Comment by Alex-302** [comment]
Can't be added to filters - unblocking of paid content.
