### ISSUE TITLE
abcalkoholu.pl - broken site

### ISSUE THREAD

**Issue by RikoDEV** [AdguardTeam/AdguardFilters#17780]
***Description***: The page does not load when you enable the Adguard's Annoyance List.
* **Current behaviour**: 

<details><summary>Screenshot:</summary>

![screencapture-abcalkoholu-pl-intro-2018-06-09-07_57_49](https://user-images.githubusercontent.com/18230443/41188235-dc14f612-6bba-11e8-9704-ff3463e01305.png)

</details><br/>

* **Expected behaviour**: 

<details><summary>Screenshot:</summary>

![screencapture-abcalkoholu-pl-intro-2018-06-09-07_58_38](https://user-images.githubusercontent.com/18230443/41188244-f183b448-6bba-11e8-8f02-66fb064fe269.png)

</details><br/>

***Steps to reproduce the problem***:

- Enable Adguard’s Annoyance List in uBlock Origin / Nano Adblocker
- Go to site

***System configuration***

**Filters:**

- Adguard’s Annoyance List
- EasyList
- EasyPrivacy
- POL: Official Polish filters for AdBlock, uBlock Origin & AdGuard

Information                            | Value
---                                    | ---
Operating system:                      |  Windows 10
Operating system version (Android/iOS) | ?
Browser:                               |  Chromium 67.0.3396.79 (64 bit)
AdGuard version:                       |  ---
Filters enabled:                       |  Adguard’s Annoyance List
AdGuard DNS:                           | None

**Comment by BlazDT** [comment]
Updated generic rules, fix is available in 2-3 hours.
