### ISSUE TITLE
[iOS] http://www.newsru.com/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1780]
http://www.newsru.com/

При переходе на другую страницу нет возможности вернуться назад по стрелке, происходит лишь обновление страницы.

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.79.48 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.7 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.97 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.31.96 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.50 Enabled=YES

**Comment by Alex-302** [comment]
Да нормально всё. У вас повторяется?
