### ISSUE TITLE
http://fishki.net/ missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1781]
http://fishki.net/
http://prntscr.com/agr661

**Comment by Alex-302** [comment]
ЭФ пусть включит. Правило не для основного фильтра.

**Comment by vgavrish** [comment]
Расширение. Реклама в видео.
Фильтры: 1,2,3,4,5,14
http://fishki.net/video/2033134-neverojatnyj-kartochnyj-fokus-ot-illjuzionista-bez-ruk.html
![screenshot_64](https://cloud.githubusercontent.com/assets/18548949/17461533/dbeb8b52-5c98-11e6-9798-91d17d887362.jpg)

**Comment by Alex-302** [comment]
Не помторилось

**Comment by vgavrish** [comment]
у меня тоже уже ничего нет
