### ISSUE TITLE
kilimall.co.ke breakge

### ISSUE THREAD

**Issue by yaardie** [AdguardTeam/AdguardFilters#178245]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

N/A. I use Ublock Origin

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.kilimall.co.ke/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, EasyList Cookie List

### Add your comment and screenshots

The ADG Tracking Protection is blocking usability of that site completely in UBO. Only a reloading circle appears in the middle.

### Privacy

- [X] I agree to follow this condition

**Comment by yaardie** [comment]
See https://github.com/uBlockOrigin/uAssets/issues/23463#issuecomment-2081014301

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/40ebdd1ff69f93fdfac0b7c222b3403082b98601
