### ISSUE TITLE
Cleanup obsolete rules or dead sites in JapaneseFilter (specific.txt)

### ISSUE THREAD

**Issue by SKEIDs** [AdguardTeam/AdguardFilters#178375]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

The following domains are inaccessible, sold, return a 403 error, or redirect to other domains. 
I accessed these domains using Chrome version 124.0.6367.91 on Windows 11, 23H2, with the UA left at its default (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36) 

- [x] abductionandconfinement.cyou
	dead domain
- [x] adbkm.com
	dead domain
- [x] afumi-stage.jp
	403 error
- [x] auc1.net
	404 error
- [x] awesome-strategy.com
	domain for sale
- [x] bbs.shitagi.org
	dead domain
- [x] bintan.ula.cc
	522 error
- [x] blankr.net
	403 error
- [x] blog-affiliate.link
	dead domain
- [x] blue-protocol-ch.com
	access blocked
- [x] bonjinnikki.com
	dead domain
- [x] career-find.jp
	dead domain
- [x] charmer-media.com
	domain changed
- [x] city.matsue.shimane.jp
	dead domain, domain changed
- [x] citykita.j-server.com
	dead domain
- [x] cndata.jpg4.pw
	access blocked
- [x] coco.to
	domain changed
- [x] cosme-world.net (also have rule on antiadblock.txt)
	dead domain
- [x] doronx.com
	access blocked
- [x] dougle.one
	dead domain
- [x] dozinge-syuka1.com
	dead domain
- [x] e-kuchikomi.info
	dead domain
- [x] elife-media.jp
	domain changed
- [x] english.talk-sense.net
	dead domain
- [x] ero-kawa.com
	dead domain
- [x] ero-meganezaru.com
	dead domain
- [x] ero-nuki.net
	access blocked
- [x] eroerotijyo.com
	access blocked
- [x] football-geek.com
	dead domain
- [x] freeze-game.com
	dead domain
- [x] gadgetlife2ch.blomaga.jp
	dead domain
- [x] gamehig.com
	dead domain
- [x] gensun.org
	dead domain
- [x] getgossip24.blog.jp
	blog disappeared
- [x] getsuaku.com
	domain changed
- [x] gumitan-com.hatenablog.com
	blog disappeared
- [x] hana3939.com
	403 error
- [x] hetano-yokozuki.net
	dead domain
- [x] honsoku.com
	nothing website 
- [x] honya-go.com
	service ended
- [x] hpav.tv
	domain changed
- [x] iionna.tokyo
	dead domain
- [x] ishikuramen.jp
	dead domain
- [x] javkimochiii.com
	access blocked
- [x] jj-blues.com
	access blocked
- [x] karelie.net
	dead domain
- [x] klmanga.vip
	dead domain
- [x] kmansin09.com
	dead domain
- [x] kojikisokuhou.com
	access blocked
- [x] libae.jp
	dead domain
- [x] live2.nicovideo.jp
	missing domain
- [x] livenan.com
	dead domain
- [x] loco.yahoo.co.jp
	service ended
- [x] love-history.jp
	403 error
- [x] mako69037965.tokyo
	dead domain
- [x] managadx.com
	dead domain
- [x] manga-to-anime.net
	dead domain
- [x] manga100ka.jp
	domain changed
- [x] mangaraw.run
	dead domain
- [x] mangaraw.so
	dead domain
- [x] mangaraw.to
	dead domain
- [x] mangaraw.vip
	dead domain
- [x] manjirushi.com
	dead domain
- [x] mayoinu.com
	dead domain
- [x] meaning.jp
	maintenance forever
- [x] mikado-koubou.com
	403 error
- [ ] mineralfoundation.work
	maintenance forever
- [x] misskey.oga.ninja
	dead domain
- [x] mm9845.com
	access blocked
- [x] moneymore.jp
	dead domain
- [x] mori.nc-net.or.jp
	domain changed
- [x] n-tel.co.jp
	403 error
- [ ] nailenamel.work
	maintenance forever
- [x] news.matomemato.me
	dead domain
- [x] news.merumo.ne.jp
	dead domain
- [x] nicoco.net
	access blocked
- [x] nicotwitter.com
	access blocked
- [x] nikonikona.blog.fc2.com
	blog disappeared
- [x] nomcaphe.com
	nothing website 
- [x] novel18.biz
	503 error
- [x] nyaasokuvip.net
	nothing website 
- [ ] oilpainting.work
	maintenance forever
- [x] okanenews24.com
	dead domain
- [x] okz-guradoru.com
	access blocked
- [x] otasoku.livedoor.biz
	blog disappeared
- [x] otonanovr.com
	dead domain
- [x] ou-kagai.com
	access blocked
- [x] panchiragazoumania.com
	access blocked
- [x] paraft.jp
	dead domain
- [x] platabi.com
	domain changed
- [x] pokemongo-master.com
	nothing website 
- [x] pormo.me
	dead domain
- [x] porolympic.tokyo
	dead domain
- [x] rakuraku-info.jp
	dead domain
- [x] rawfree.net
	access blocked
- [x] rezudx.com
	nothing website 
- [x] roadbike-labo.com
	domain for sale
- [x] sexx.fans
	dead domain
- [x] shikotch.net
	nothing website 
- [x] shitagi.org
	dead domain
- [x] sk-koubai.com
	dead domain
- [x] sumaiweb.jp
	dead domain
- [x] summertravel.info
	522 error
- [x] tasclap.jp
	service ended
- [x] trip-2ch.kokohenjp.mixh.jp
	403 error
- [x] twisave.com
	dead domain
- [x] twtimez.net
	dead domain
- [x] ula.5ch.net
	522 error
- [x] ula.cc
	522 error
- [x] vi-lab.com
	domain for sale
- [x] vipperlog.com
	access blocked
- [x] vivre-media.jp
	domain changed
- [x] volante.info
	dead domain
- [x] warattoko6727.net
	403 error
- [x] wave.popin.cc
	503 error
- [x] webdevqa.jp.net
	dead domain
- [x] wezz-y.com
	dead domain
- [x] wotopi.jp
	dead domain
- [x] wp1.fuchu.jp
	dead domain
- [x] xbooks.one
	dead domain
- [x] xn--icktho25pncf.biz
	access blocked
- [x] xn--ickua0p8b.biz
	nothing website 
- [x] xn--o9jx06gxedxziu2np5bluqts8d30r.net
	access blocked
- [x] xn--pckwb0czd195xp0kpxvqic.xyz
	domain changed
- [x] ytranking.net
	domain changed

Added on 2024-08-03

- [x] prcm.jp 
 service shutdown (novel.prcm.jp is alive)
- [x] twi-fans.com
dead domain
- [x] wiki.denfaminicogamer.jp
service shutdown
- [x] wiki.dengekionline.com 
service shutdown
- [x] wiki.famitsu.com
service shutdown

Added on 2024-08-30

- [x] 365-girl.com
DNS address could not be found
- [x] affiliate-ruby.com
DNS address could not be found
- [x] awaji-net.com
DNS address could not be found
- [x] beethovenmaster.com
DNS address could not be found
- [x] bokuweb.com
DNS address could not be found
- [x] `||cdn-images.net/ad/$third-party`
 ero-nuki.net is dead
- [x] chietoku.jp
DNS address could not be found
- [x] daijitenx.com
DNS address could not be found
- [x] dbonline.jp
domain changed
- [x] driving-license-mag.com
DNS address could not be found
- [x] ero-anime.net
DNS address could not be found
- [x] ero-outdoor.net
DNS address could not be found
- [x] ero.pet
DNS address could not be found
- [x] erokolky.com
DNS address could not be found
- [x] galgogo.com
DNS address could not be found
- [x] haremxx.com
DNS address could not be found
- [x] hawaii-mag.com
DNS address could not be found
- [x] hotanimeporno.com
DNS address could not be found
- [x] html.seo-search.com
DNS address could not be found
- [x] id.fm-p.jp
service shutdown
- [x] imishin.jp
DNS address could not be found
- [x] internal.co.jp
DNS address could not be found
- [x] it-swarm-ja.tech
DNS address could not be found
- [x] kajidore.com
DNS address could not be found
- [x] kotowaza-allguide.com
DNS address could not be found
- [x] lesbianmama.com
DNS address could not be found
- [x] love-history.jp
DNS address could not be found
- [x] mangarawplus.net
DNS address could not be found
- [x] mangarawtop.at
DNS address could not be found
- [x] n-switch.com
DNS address could not be found
- [x] news.yamahamoto.net
DNS address could not be found
- [x] one-news.jp
DNS address could not be found
- [x] pepy.jp
domain changed
- [x] shibarism.com
DNS address could not be found
- [x] shinri-mag.info
DNS address could not be found
- [x] simozo.com
DNS address could not be found
- [x] spoen.net
domain changed
- [x] sugi9532.com
DNS address could not be found
- [x] wazaari.xyz
DNS address could not be found
- [x] xn--eckhu0c0d1b5kcu5305ksfpb.com
DNS address could not be found

### Proposed solution

For cosmetic rules, it's possible to delete the rule. For basic rules, I am not certain. 

### Additional information

On some websites, there was a notice indicating that they are currently under maintenance. 
However, given that the dates mentioned do not match the present, it's possible these sites have been left in maintenance mode.

**Comment by Yuki2718** [comment]
> I accessed these domains using Chrome

That is not a very reliable way. For example, `2-d.jp` is living `https://yutorize.2-d.jp/ytsheet/sw2.5/`. You can use https://publicwww.com/ and Google search (check exact search `"2-d.jp"` and `site: 2-d.jp`).

**Comment by Yuki2718** [comment]
Removed `wp1.fuchu.jp` as dead domain.

**Comment by Yuki2718** [comment]
`o-uccino.jp` itself is still used e.g. `https://www.o-uccino.jp/cm/` but the rules would require review.

**Comment by Yuki2718** [comment]
`sagafan.jp` is living, but I found a FP on `https://imarins.sagafan.jp/`.

**Comment by Yuki2718** [comment]
`kokuban.in` is living, just not responding currently. Needs watching.

**Comment by Yuki2718** [comment]
`lithograph.work` is used only in subdocument of some games, difficult to check.

**Comment by Yuki2718** [comment]
`game-waza.net` is living, removed from the list.

**Comment by Yuki2718** [comment]
Deleted `shindans.com` for `https://dt1.shindans.com/`

**Comment by Yuki2718** [comment]
Deleted `bakotv.com` for `https://miomio.bakotv.com/tokyomer_tbs210905/`

**Comment by Yuki2718** [comment]
Removed `heisei-housewarming.work` from the post. This is not a website but used only as iframe on some game sites.

**Comment by Yuki2718** [comment]
I'm still checking occasionally.

**Comment by Alex-302** [comment]
Processed `2024-08-30` domains.

**Comment by Yuki2718** [comment]
Removed `blog2.mmm.me` and `blog18.mmm.me` for `https://neoizakaya.blog2.mmm.me/`, `http://miumiumania.blog18.mmm.me/mmmblog-entry-5021.html`. Now all fixed except for those `*.work`.
