### ISSUE TITLE
Huffington Post app - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1783]
the [app](https://play.google.com/store/apps/details?id=com.huffingtonpost.android&hl=en_GB)

HTTP logs: GFL-634-27276
<details>
"dnsFilteringEnabled" : false,
  "enabledFilterIds" : [ 2, 3, 4, 5, 1, 6, 7, 8, 11, 113, 216 ],
  "environment" : "prod",
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "firewallConfiguration" : {
    "defaultPermissions" : [ "MOBILE", "WIFI", "AD_FILTERING" ],

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/13875552/3a747c80-ed07-11e5-84b0-3de1a5b76de6.png)
у нас - черная полоса, которая мигает, у юзера - поямо реклама-реклама

**Comment by Alex-302** [comment]
у меня вообще чисто с альфой(без HTTPS)
проверьте с ней

**Comment by Alex-302** [comment]
@evgeniy-ADG

**Comment by evgeniy-ADG** [comment]
нам юзеру порекомендовать альфу?

**Comment by Alex-302** [comment]
можно. Но https пока пусть не включает.

**Comment by Alex-302** [comment]
И пусть отпишется о результате.
Кэш проги пусть не забудет очистить.
