### ISSUE TITLE
Конфликтный фильтр из подписки 2_optimized.txt ломает пользовательские AG_onLoad правила для www.youtube.com

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#178555]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [ ] AdGuard product version is up-to-date;
- [ ] Browser version is up-to-date;
- [ ] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

2.12.250

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

www.youtube.com

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

1. Собственно, всё в заголовке.

Конфликтный фильтр

```

www.youtube.com#%#(()=>{window.JSON.parse=new Proxy(JSON.parse,{apply(r,e,t){const n=Reflect.apply(r,e,t);if(!location.pathname.startsWith("/shorts/"))return n;const a=n?.entries;return a&&Array.isArray(a)&&(n.entries=n.entries.filter((r=>{if(!r?.command?.reelWatchEndpoint?.adClientParams?.isAd)return r}))),n}});})();

```
из подписки https://filters.adtidy.org/android/filters/2_optimized.txt ломает пользовательские AG_onLoad правила для www.youtube.com. По крайней мере на старом 2.12.250. Скриплеты тупо перестают работать. Добавил себе исключение, но если вышеозначенное правило кривое - уберите его из подписки.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@Baltazar500 Здравствуйте, не могли бы вы отправить пользовательское `AG_onLoad` правило, которое не работает, чтобы я могла его проверить?

**Comment by Baltazar500** [comment]
@jellizaveta, да для проверки можно самую банальщину использовать
```
www.youtube.com#%#AG_onLoad(function(){alert("123");});
```
правило выше ломает исполнение других AG_onLoad правил на целевом сайте в принципе.

**Comment by jellizaveta** [comment]
@Baltazar500 Вы не могли бы обновить AdGuard до последней версии?

**Comment by Baltazar500** [comment]
@jellizaveta,

>Вы не могли бы обновить AdGuard до последней версии?

Эта ревизия на старом смарте с 4.2. Там выше не поднять. Мне проще исключение добавить. Просто, насколько я помню "оптимизированные" фильтры предназначены именно что для старых ревизий и нахождение в них родобных фильтров по идее не должно иметь места. Но вам виднее :)

>У меня youtube на андроиде открывается в мобильной версии, которая редиректит >на m.youtube.com, при проверке, правило из вашего комментария, на этом домене >работает корректно.

У меня в  /data/local/chrome-command-line прописан десктопный UA

**Comment by jellizaveta** [comment]
Оптимизированные фильтры нужны для сокращения количества правил, которые редко используются / не подходят для какой-то платформы. Оптимизация не относится к определенной версии приложения AdGuard. Оставьте, пожалуйста, правило в исключениях, так как в актуальной версии ошибка не повторяется.
