### ISSUE TITLE
[MS Edge] finans.mynet.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#1785]
http://finans.mynet.com/borsa/hisseler/bjkas-besiktas-futbol-yat/

Adguard blocks line graphs or any graphical data on nearly every website, for example see the link above. English filter is responsible for that.

Originally from: http://forum.adguard.com/showthread.php?9659-is-this-issues-a-bug

**Comment by Alex-302** [comment]
I think it caused by injection of а big quantity of element hiding rules.

**Comment by Alex-302** [comment]
looks like a bug
