### ISSUE TITLE
www.deccanherald.com Blank space of blocked ads

### ISSUE THREAD

**Issue by Broken-Glass1** [AdguardTeam/AdguardFilters#178530]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Unlock origin

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.deccanherald.com/archives/use-ad-blocking-software-rises-1989096

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Social Widgets

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, EasyList Cookie List

### Security

NoCoin Filter List

### Other

AdGuard Experimental filter

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

Blank space of blocked ads.
Kiwi browser with ublock origin on Android.

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Please post screenshot of blank space.

**Comment by BlazDT** [comment]
Only reproduced if I disable element hiding in uBO settings (in UBO view click on Cosmetic filtering, so it is not red crossed).
