### ISSUE TITLE
2 Different Sets of Missed Ads on Yahoo News

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardFilters#1787]
**_N.B.: May require mobile browser to view these ads — I saw them via an Android browser.**_

@Alex-302 On each of:
- http://news.yahoo.com/inside-factory-where-acura-builds-121533572.html?partner=CHEETAH&share=0&language=en&isinstall=false
- http://www.yahoo.com/movies/x-men-apocalypse-first-official-trailer-promises-death-132636639.html?partner=CHEETAH&share=0&language=en&isinstall=false
- http://www.yahoo.com/movies/avengers-infinity-war-introduce-never-162038926.html?partner=CHEETAH&share=0&language=en&isinstall=false
- http://www.yahoo.com/autos/rehearsal-invasion-north-korea-looks-152100487.html?partner=CHEETAH&share=0&language=en&isinstall=false
- http://www.yahoo.com/movies/sting-reportedly-retires-professional-wrestling-140225458.html?partner=CHEETAH&share=0&language=en&isinstall=false
- http://www.yahoo.com/tv/dwayne-johnson-mark-wahlberg-sued-200-million-over-011134859.html?partner=CHEETAH&share=0&language=en&isinstall=false
- http://www.yahoo.com/tech/watch-hacker-install-credit-card-skimmer-under-3-204038233.html?partner=CHEETAH&share=0&language=en&isinstall=false

there are 2 sets of missed ads:
1. Delay-loaded (only appear after rest of article loaded) box ads every few paragraphs _in_ the article, which are pretty well-behaved — i.e., can be removed temporarily by hitting × in each ad's corner & aren't _too_ annoying, so I also nominate _these_ for inclusion in the [Useful ads whitelist](https://adguard.com/en/whitelist.html)
2. Sponsored links in the "You may also want to read" section below for further news articles, which are_n't_ well-behaved & should be destroyed at will.

**Comment by TPS** [comment]
Forgot details on my setup:

AG 2.1.359 (VPN-mode) via Amazon Appstore, all lists except Useful Ads

**Comment by Alex-302** [comment]
@TPS 
please make a screenshot. It will help me to find them.
