### ISSUE TITLE
bergfreunde.de

### ISSUE THREAD

**Issue by BenMaierEU** [AdguardTeam/AdguardFilters#178893]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Version: 2.0.36.26

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

bergfreunde.de

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Annoyances filter

### Add your comment and screenshots

On the website _bergfreunde.de_ , the rule `bergfreunde.de##div[class^="reveal-modal"]` ([link to code](https://github.com/AdguardTeam/AdguardFilters/blob/92e91d8044a3a2e6cac22fc6cd1a52bc5b9460d1/AnnoyancesFilter/Popups/sections/popups_specific.txt#L2785C1-L2785C43)) of the _Annoyances/popup filter_ breaks central popup features of the website (e.g. opening of the size chart pop-up of a product page; opening of the delivery cost pop up of a product page; etc.)

Furthermore, this specific rule is actually not necessary to block the newsletter popup of the underlying issue #93686.

As a result, the rule should imo be removed. If desired, I can submit my own merge request solving this issue here - I apologize in case wrong process, first time submitting an issue to Adguard for me.

<details><summary>Screenshot: Product information page featuring text links to size chart pop-up ("Größentabelle") and  delivery cost pop up  ("zzgl. Versandkosten") , which do not open currently.</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/9460485/b4fc86e7-7e51-4053-a809-4a59d0ab7115)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
I have removed this rule, filters update should be available in 1-2 hours.
Thank you for your detailed report.
