### ISSUE TITLE
novinky.cz - cookie popup

### ISSUE THREAD

**Issue by MIOGMIOG** [AdguardTeam/AdguardFilters#178995]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

If you visit novinky.cz, popup saying "Abyste mohli pokračovat, potřebujeme vědět, jakou formou vám můžeme zobrazovat reklamu" (translated "In order for you to proceed, we need to know how we can show you advertising") will appear shortly after visiting the website.

### Proposed solution

I made filter for this (but it needs more testing, not sure, if it breaks something, it didn't break anything for me, but we cannot be 100% sure)
```
||cmp.seznam.cz^$3p
```

### Additional information

This is also related to #177571

**Comment by kyngs** [comment]
Unfortunately, the proposed solution is not enough.
When you visit novinky.cz, the popup does not show, however it does show when you click on an article.
I'm not sure whether this can be bypassed, as the server returns 302:
![image](https://github.com/AdguardTeam/AdguardFilters/assets/38181667/56a7494f-3c9b-4b56-baef-b493762b590a)

**Comment by piquark6046** [comment]
AdGuard supports a selector including opened shadow root in `trusted-click-element` scriptlet [^1].
However, a selector with closed shadow root is not supported; the `cmp.seznam.cz` uses a closed shadow root.

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/98787049/d79dd13a-e059-46a6-8427-7c55d2510dd3)


</p>
</details> 

[^1]: https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-trusted-scriptlets.md#-%EF%B8%8F-trusted-click-element

**Comment by piquark6046** [comment]
If you use AdGuard Browser Extension on Firefox web browser, please await what the following issue is resolved:
https://github.com/AdguardTeam/Scriptlets/issues/423
Or, migrate to AdGuard CoreLib-based app or AdGuard Browser Extension alongside on Firefox.

CC: @gorhill

**Comment by gorhill** [comment]
`novinky.cz##szn-cwl` isn't sifficient?

**Comment by kyngs** [comment]
> Maybe the visitor will encounter [#178995 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/178995#issuecomment-2105683410).

It seems to be a hit-or-miss. Sometimes I get redirected, sometimes not.
