### ISSUE TITLE
louisedistanthat.com

### ISSUE THREAD

**Issue by ShalokShalom** [AdguardTeam/AdguardFilters#179070]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Vivaldi Mobile

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://s.to/serie/stream/maison-ikkoku/staffel-1/episode-1

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

EasyPrivacy, Peter Lowe's Blocklist

### Language-specific

EasyList Germany

### Add your comment and screenshots

The page simply redirects to louisedistanthat.com and that to an ad page

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
Can you show me web browser extensions list of your web browser?

**Comment by ShalokShalom** [comment]
There are no extensions supported. 

There is just an option to add and remove the filter lists. 

Thats it.

**Comment by piquark6046** [comment]
Vivaldi web browser does not support any scriptlet rule that is required to filter finely. 
Please consider installing AdGuard for Android at adguard.com official website.
