### ISSUE TITLE
ilsr.org

### ISSUE THREAD

**Issue by Mennaruuk** [AdguardTeam/AdguardFilters#179043]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.46

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

`https://ilsr.org/scaling-up-part-one`
`https://ilsr.org/how-investor-owned-utilities-turn-your-money-into-political-power`
`https://ilsr.org/watch-is-2024-the-year-of-trust-busting`

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

EasyPrivacy

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Other Annoyances filter, Adblock Warning Removal List, Fanboy's Annoyances, Web Annoyances Ultralist

### Language-specific

Liste AR

### Add your comment and screenshots

Subscription popup. This is the cosmetic filter I see: `##.pum-active.click_open.auto_open.popmake-overlay.pum-theme-2021-update.pum-theme-89991.pum-overlay.pum`

Screenshot 1 <details>

![Screenshot 2024-05-11 at 13-55-59 Webinar Scaling Up Mission-Driven Community Composting](https://github.com/AdguardTeam/AdguardFilters/assets/52135169/4ab448d1-5287-4bd5-89f6-a91d46f4d9af)

</details>

Screenshot 2 <details>

![Screenshot 2024-05-11 at 13-58-07 How Investor-Owned Utilities Turn (Your) Money into Political Power](https://github.com/AdguardTeam/AdguardFilters/assets/52135169/868923eb-50da-4086-af84-6ad1993af258)

</details>

Screenshot 3 <details>
![Screenshot 2024-05-11 at 13-58-14 Watch Trustbusters are Scoring Pivotal Wins](https://github.com/AdguardTeam/AdguardFilters/assets/52135169/003e0ba6-7611-481f-8072-ac4144c29545)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Unfortunately, I'm not able to reproduce it.
Please try to add this rule:
```adblock
ilsr.org##.popmake-overlay
```
to user rules.
