### ISSUE TITLE
curiositybox.com: tracking

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#179096]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.46

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://curiositybox.com

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Ukrainian filter

### Add your comment and screenshots

![Screenshot 2024-05-12 223403](https://github.com/AdguardTeam/AdguardFilters/assets/43014154/9f8d5896-efee-4a1c-a0f8-9e7716cd1ee4)
![Screenshot 2024-05-12 85764869png](https://github.com/AdguardTeam/AdguardFilters/assets/43014154/661c589e-99f0-4009-975c-0ac5d7280d1c)

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
`https://gtmfsstatic.getgoogletagmanager.com/js/gtmfsv2.js?shop=thecuriositybox.myshopify.com` - not sure about this.
