### ISSUE TITLE
c.webengage.com

### ISSUE THREAD

**Issue by iamaugustinthomas** [AdguardTeam/AdguardFilters#179394]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard Content Blocker, AdGuard DNS

### AdGuard version

1.11.17

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

https://c.webengage.com/lw/g1.jpg?p=eyJsYyI6In4yMDI0YjVkOCIsImwiOiJlYjU4NWI2MzM0NGZhOWI5MmU1OWI0NGMwM2Q4NGI5ODBiNTU2MGFkIiwiYyI6ImZtcF9nZl8wMDI5OTIwIiwiZW0iOiJhdWd1c3Rpbi50aG9tYXMyMkBnbWFpbC5jb20iLCJlIjoiOWZoc3FhIiwidiI6In4yMmwxNDMwIiwicyI6IjVhZ2M2M2FkZGc2ZjJpMV9iOWUzZDczOC1hYWQ4LTRhODEtOTk0YS0zYWE4MmI4MTJjYjQ6MTcxNTg3Nzk2NDc1NSIsImV2ZW50IjoiZW1haWxfY2xpY2siLCJjdGEiOiJiYjQyODhjMyIsInRvVVJMIjoiaHR0cHM6Ly9ibG9nbWVkaWEudGVzdGJvb2suY29tL2Jsb2cvd3AtY29udGVudC91cGxvYWRzLzIwMjQvMDUvcHJlZGljYXRlZC10b3BpY3MtcXMtNzA5MGZjNDMucGRmIn0%3D

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Add your comment and screenshots

2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="1080" alt="Screenshot 2024-05-17 at 3 24 24 PM" src="https://github.com/AdguardTeam/AdguardFilters/assets/141567905/774b8843-da8e-469b-b7c3-d936733ff87e">

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.

**Comment by iamaugustinthomas** [comment]
Thanks! 👍
