### ISSUE TITLE
Reconsider petametrics.com rules in TPF

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#179355]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Blocking whole petametrics is problematic and causing lots of problems including https://github.com/AdguardTeam/AdguardFilters/issues/46126 and gigantic exception under https://github.com/AdguardTeam/AdguardFilters/issues/161405. EasyPrivacy adjusted blocking as
```
||petametrics.com^$image,third-party
||query.petametrics.com^
||petametrics.com^$domain=meidastouch.com
```
by https://github.com/easylist/easylist/commit/418355816e4eed79acdef161d91f93e3e3c6f1fc I suggest the same, or at least exclude blanket blocking of the domain in DNS filter to fix `https://twitter.com/SeriousHoax/status/1791106709831959020`.

### Proposed solution

Adjust to granular blocking rules and remove some of excepion

### Additional information

cc: @SeriousHoax

**Comment by Alex-302** [comment]
![image](https://github.com/user-attachments/assets/29e90f36-f660-4cd2-90fe-6ef10bdaadda)

**Comment by Yuki2718** [comment]
What? `||petametrics.com^$third-party` is still in TPF which is very problematic.

**Comment by Alex-302** [comment]
EasyPrivacy still has it, and no `@@` rules.

**Comment by Yuki2718** [comment]
Looks it was done 3 weeks ago by https://github.com/easylist/easylist/commit/6d3bfc8efdedd91ed054888b4b042ede3da5671b @ryanbr It's problematic to wholy block.

**Comment by Yuki2718** [comment]
@Alex-302

**Comment by Alex-302** [comment]
I don't see recent problems, related to this domain.

**Comment by Yuki2718** [comment]
What about the telegraph issue I've just discussed on Slack?

**Comment by Alex-302** [comment]
Need a fresh example. 
Cannot reproduce this problem with telegraph
https://github.com/AdguardTeam/AdguardFilters/issues/46126#issue-539065897

**Comment by Yuki2718** [comment]
At least "More from The Telegraph" is broken.

**Comment by Alex-302** [comment]
Ok then
