### ISSUE TITLE
Fix to Deadline/TVLine overlay no longer works

### ISSUE THREAD

**Issue by clubside** [AdguardTeam/AdguardFilters#179494]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.5.3 (1016)

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://deadline.com/

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. I created this issue a while back. The fix no longer works and I can’t re-open previous issue: https://github.com/AdguardTeam/AdguardFilters/issues/177137
2. The last checkbox at the top of this form is untrue. Why is it required to be checked? Disabling AdGuard has no effect on this issue other than causing all the ads to appear.
3. This affects 2 sister sites and most likely all sites under the PMC.
4. The overlay does not appear on every page, it seems to appear every 3 or 4 page refreshes/navigations.

5. Screenshots
<details><summary>Screenshot 1:</summary>

![IMG_3239](https://github.com/AdguardTeam/AdguardFilters/assets/64618797/ea65c019-0be2-4514-a896-c1d0d4129e50)

</details>

<details><summary>Screenshot N:</summary>

![IMG_3240](https://github.com/AdguardTeam/AdguardFilters/assets/64618797/d6d9a635-2419-486c-9e03-f71519b018e7)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Please enable Annoyances filter and ensure it is update.

**Comment by clubside** [comment]
It’s always been on:

![IMG_3242](https://github.com/AdguardTeam/AdguardFilters/assets/64618797/a6ec39c9-1d4c-456f-8e19-cc744be939c1)

and after hitting refresh to download latest settings there’s no change on any of the PMC sites (I also tried indiewire)

![IMG_3241](https://github.com/AdguardTeam/AdguardFilters/assets/64618797/6abbdfe0-a9b1-4631-87aa-d1ac67ba88fc)

**Comment by BlazDT** [comment]
Your posted config is incomplete then. Cannot reproduce, but blocked another of their domains and added another url they check to whitelist. Please check for updates in about 3-4 hours.

**Comment by clubside** [comment]
How can I prove I have every filter turned on from the iPad app?

As mentioned this popup doesn’t appear on every page it appears intermittently every 3 or 4 navigations which could be a refresh or a link click.

**Comment by BlazDT** [comment]
Your filter screenshot is enough. It takes a while until the rules are available in filter updates (usually 3-4 hours after a commit). So best to check for updates manually after this time.
