### ISSUE TITLE
[Stealth mode] http://www.trulia.com/ - 'hide your referer' affects the site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1794]
![image](https://cloud.githubusercontent.com/assets/15856304/13885318/6c6c2a34-ed3a-11e5-80cf-8fb3f5064f5c.png)
![image](https://cloud.githubusercontent.com/assets/15856304/13885323/72735a10-ed3a-11e5-8e86-0ed646eaff14.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Can't reproduce. This option can't affect the site when you open in in address bar.
Need the source page, where he open link to this site.
