### ISSUE TITLE
testbook.com

### ISSUE THREAD

**Issue by Broken-Glass1** [AdguardTeam/AdguardFilters#179570]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

Latest version

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://testbook.com/question-answer/which-language-did-gautam-buddha-use-for-his-disco--5e71f76d1f886d0d274b3291/amp

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Add your comment and screenshots

Annoyance on Samsung internet browser on Android
![Solved  Which language did Gautam Buddha use for his discourse](https://github.com/AdguardTeam/AdguardFilters/assets/159278763/10a8d8ec-592f-423d-b9f7-8b8b637f0f01)

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
Fixed.
