### ISSUE TITLE
linkedin.com

### ISSUE THREAD

**Issue by Broken-Glass1** [AdguardTeam/AdguardFilters#179634]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

Latest version

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.linkedin.com/pulse/homeopathy-arteriosclerosis-dr-ks-gopi

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Add your comment and screenshots

Annoyance.
![HOMEOPATHY FOR ARTERIOSCLEROSIS](https://github.com/AdguardTeam/AdguardFilters/assets/159278763/9b1c4946-f3e5-4d1a-bf06-f4347cd96901)

Web browser :- Samsung internet browser on Android.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please make a screenshot.

**Comment by Alex-302** [comment]
@Broken-Glass1 `AdGuard Content Blocker` can't block it (browser's API limitations).
Please install `AdGuard for Android` from adguard.com
