### ISSUE TITLE
[Android] prime-music.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1798]
prime-music.net
Reproduced in Chrome Dev only
![_20160318_144251](https://cloud.githubusercontent.com/assets/14153331/13896245/c33dd896-ed8d-11e5-9e0d-aa1ff6fefb86.JPG)
Requester - CSD-603-82417

**Comment by Alex-302** [comment]
не повторилось даже с упрощённой фильтрацией.
