### ISSUE TITLE
syfy.com

### ISSUE THREAD

**Issue by Sonic5435325** [AdguardTeam/AdguardFilters#179845]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.57.3rc1

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.syfy.com/shows

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Annoyances

AdGuard Cookie Notices filter, Web Annoyances Ultralist, EasyList Cookie List

### Add your comment and screenshots

1. <comment>
Broken by mparticle.com
2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Player disappears even without AdGuard. Need more detais.
Screenshots are required.

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/28404745-e24a-40df-a0c4-5c84625215c0)


</details>

**Comment by Sonic5435325** [comment]
@Alex-302 The site's content refuses to display, unless the requests are enabled.
![Screenshot from 2024-05-27 11-22-01](https://github.com/AdguardTeam/AdguardFilters/assets/89158249/2b8371b9-aab1-4ed6-ad08-32990cf01ccd)

**Comment by Alex-302** [comment]
> unless the requests are enabled

Which requests? "Enabled" = "unblocked"?

**Comment by Sonic5435325** [comment]
Yes, the requests which are being blocked

**Comment by Alex-302** [comment]
@Sonic5435325 Please disable all filters, and enable one by one (1st - Base filter) with checking. And tell us which filter breaks the site.

**Comment by Alex-302** [comment]
@Sonic5435325 Please also test this rule `@@||jssdkcdns.mparticle.com/js/*/mparticle.js$domain=syfy.com`
