### ISSUE TITLE
tfl.gov.uk status

### ISSUE THREAD

**Issue by codl** [AdguardTeam/AdguardFilters#179914]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.46

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://tfl.gov.uk/tube-dlr-overground/status/

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Cookie Notices filter

### Language-specific

AdGuard French filter

### Add your comment and screenshots

On the left side of the page are boxes with live status for each London Underground line, lines experiencing delays or closures are shaded yellow and have a + sign indicating the box can be expanded for details. When AdGuard is enabled with these lists, these boxes cannot be expanded. When AdGuard is disabled, or either the Cookie Banner list or the French list is disabled, these boxes can be expanded and the first one is expanded automatically on page load.

At times when nothing is wrong on the network and every line shows "Good service", none of the boxes are meant to expand and the issue can't be reproduced, but the same issue can be seen on future dates with planned closures, for example <https://tfl.gov.uk/tube-dlr-overground/status/?Input=&lineIds=&dateTypeSelect=Future%20date&direction=&startDate=2024-08-01T00%3a00%3a00&endDate=2024-08-01T23%3a59%3a59>

<details><summary>Screenshot with AdGuard disabled:</summary>

![](https://github.com/AdguardTeam/AdguardFilters/assets/315139/e1ec0f97-326e-4e79-a22a-ba5491408689)

</details>

<details><summary>Screenshot with AdGuard enabled:</summary>

![](https://github.com/AdguardTeam/AdguardFilters/assets/315139/0a798c53-8b42-43cb-899e-da257ebeb1dc)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
