### ISSUE TITLE
api.alloha.tv should not be blocked

### ISSUE THREAD

**Issue by qt-kaneko** [AdguardTeam/AdguardFilters#180014]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.2.241

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

api.alloha.tv

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. This URL contains API for Alloha CDN so it should not be blocked.

2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="824" alt="image" src="https://github.com/AdguardTeam/AdguardFilters/assets/100197083/2c57e757-1892-42e9-9fe0-f64bf26c2127">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It is caused by Easylist. Better report them. Or add
`@@||alloha.tv^`
