### ISSUE TITLE
com.fungames.battletanksbeta

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#180072]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.4.1

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.fungames.battletanksbeta

### Ad Blocking

AdGuard Base filter

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

analytics.wildlifestudios.com
opentelemetry-collector.shared-services.us-east-1.general.prod.wildlife.io

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Added, + `push-api.topaz-analytics.com`
