### ISSUE TITLE
m.economictimes.com

### ISSUE THREAD

**Issue by Broken-Glass1** [AdguardTeam/AdguardFilters#180053]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

Latest version

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://m.economictimes.com/news/india/what-is-remal-cyclone-imd-warning-heavy-rain-in-bengal-and-odisha-cyclone-tracker-in-west-coast-of-bay-of-bengal/articleshow/110391778.cms

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Add your comment and screenshots

On Samsung internet browser on Android.
![Cyclone Remal- A severe cyclone is heading towards India; here's all you need to know - The Economic Times](https://github.com/AdguardTeam/AdguardFilters/assets/159278763/0bf391f8-9b14-40ce-829f-fb4f32106d03)

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
@Broken-Glass1 Your issue cannot be resolved because AdGuard Content Blocker uses limited API support of Samsung Internet.
AdGuard cannot enhance filtering capability unless Samsung improves the API.
Please use AdGuard for Android that can be downloaded at [here](https://adguard.com/en/adguard-android/overview.html).
