### ISSUE TITLE
bravotv.com - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1801]
Tested with GB IP, the site shows the counter but ads do not appear. We need to test it with US VPN, our customers from US experience ads on the site.

![image](https://cloud.githubusercontent.com/assets/15856304/13899510/d72d5974-edf8-11e5-82e9-acb43d7f7da1.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
I need direct url and instruction how to open the video without subscription. 
Tried to open some video, but it requested provider, and video doesn't start.
