### ISSUE TITLE
miDGT App - Connection Problem 

### ISSUE THREAD

**Issue by rodrigosambadesaa** [AdguardTeam/AdguardFilters#180131]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.4.189

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.dgt.midgt&hl=es_419

### Ad Blocking

AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List

### Social Widgets

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### DNS filters

AdGuard DNS filter

### Language-specific

AdGuard Spanish/Portuguese filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Remove X-Client-Data header from HTTP requests

### Add your comment and screenshots

1. <comment> When logged in, after tapping "Ver mi carnet" ("See my license)", a connection error is shown, saying that the app is running in disconnected mode, despite the device having Internet access.

Only contributors with Spanish driving license and Cl@ve, Electronic Spanish, National Identiy Card or Personal Data log in methods will be able to test.

I'm not willing to share my account for this case.

3. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi.
What break the app? Please test when disabled:
- all filters
- DNS protection
- Tracking Protection

**Comment by rodrigosambadesaa** [comment]
Weird. Now it's not failing, even with everything enabled.
