### ISSUE TITLE
onlytech.com

### ISSUE THREAD

**Issue by Broken-Glass1** [AdguardTeam/AdguardFilters#180212]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

Latest version

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://onlytech.com/community/threads/airtel-xstream-airfiber-3-month-plans-launched.54635/#post-602440

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Add your comment and screenshots

Annoyance on Samsung internet browser on Android
![Airtel Xstream AirFiber 3 month plans launched - OnlyTech Forums - Technology Discussion Community](https://github.com/AdguardTeam/AdguardFilters/assets/159278763/07ba55ed-d564-4000-b4f6-aa11970e6a2f)

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I've added the rule that might help, but it's better to switch to AdGuard for Android instead of AdGuard Content Blocker.

**Comment by zloyden** [comment]
AdGuard for Android does not effect on the battery. Have you tried `4.4.1` version?

**Comment by zloyden** [comment]
I can't get it. Did you have it with our app on your smartphone? If so, it's better to report [here](https://github.com/AdguardTeam/AdguardForAndroid/issues/).

> If there was any way to use Adguard Android app without vpn

Yes, you can use the proxy mode. Mostly requires root access, but it can be installed without it.
