### ISSUE TITLE
Update block list filters with newly discovered trackers and spam sites

### ISSUE THREAD

**Issue by nfhipona** [AdguardTeam/AdguardFilters#180237]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Sites are not yet blocked and kept being bypassed by filters as it is not yet in the block lists.

- `*.goeco.social`
- `*.trackswork.site`
- `*.lesterunkind.top`
- `*.sonraifishnet.website`

### Proposed solution

Update filter block lists with:

> ||goeco.social^
> ||trackswork.site^
> ||lesterunkind.top^
> ||sonraifishnet.website^

**Comment by Alex-302** [comment]
Where these domains used?
