### ISSUE TITLE
remove "e3lan" class

### ISSUE THREAD

**Issue by juarez-spa3** [AdguardTeam/AdguardFilters#180378]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.46

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

-

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

The "e3lan" class has been added to the easylist filter as a generic, so these rules are no longer needed.

drtus.com##div[class="e3lan e3lan-top"]
gemlikgundemgazetesi.com##div[class^="e3lan"]
savebutonu.com##.e3lan-top
formatatmak.com##.e3lan
kutahyaekspres.com,pckoloji.com.tr##.header-content > div.e3lan
dogus.nl##div[class$="e3lan e3lan-bottom"]
dogus.nl##div[class$="e3lan e3lan-top"]

https://github.com/easylist/easylist/commit/ed69b8b5984fadfb3ac58a85d959b0ccaa713000
https://github.com/easylist/easylist/commit/fbf572380a81bae79dcde4e303fde0d0f60845cd
https://github.com/easylist/easylist/commit/6c015aebf94aeca5c1ecb87d4a2c513e8dd4cebf
https://github.com/easylist/easylist/commit/557bda9ad8aee324de68f16ab2ab34d7defd43bb

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It is not used only for ads. I think generic rule will be removed.
