### ISSUE TITLE
globalklavye.com

### ISSUE THREAD

**Issue by juarez-spa3** [AdguardTeam/AdguardFilters#180377]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.36

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://globalklavye.com/

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

It is not dead, but the site has not been sharing since 2019 and their website is not active at the moment.

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available soon.
