### ISSUE TITLE
pch.com

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#18044]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Preconditions***

- Active USA VPN (I've been using Tunnel Bear)
- A valid account on pch.com (check the note in the ticket # 1881698, I've posted my login/password there)

***Description***:

AdGuard fails to block the counter at https://lotto.pch.com/onboarding while the actual ad is blocked

***Steps to reproduce the problem***:

1. Go to PCH.com (you might have to register to play) and log in
2. At the top of the PCH home screen, look for PCH Lotto and choose it.
3. It should bring up a lottery play screen. Go ahead and enter numbers, then submit.
4. When you submit, normally the next game comes right up (with ads blocked).

***Current behavior***: 

The video ad is blocked but you still have to wait ~10 seconds which didn't happen before

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/41332082-fd19266c-6ee4-11e8-92b8-12574f5418e4.png)

</details><br/>

***Expected behavior***: 

The counter is skipped along with the actual ad

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | macOS 10.13.5
Browser:                               | Chrome 67.0.3396.79
AdGuard version:                       | 1.5.8 b
Filters enabled:                       | Base, Social media, Spyware, Spanish, Russian, Safari, Annyances, Warning removal, I don't care about cookies
AdGuard DNS:                           | None 
Helpdesk ID (if exists):               | 1881698

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Hmm... Can't find how the timer works here.
