### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by Broken-Glass1** [AdguardTeam/AdguardFilters#180598]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

Latest version

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Yandex Browser

### Which device do you use?

Mobile

### Where is the problem encountered?

gadgets360.com

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

EasyPrivacy

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Add your comment and screenshots

![Tech News, Latest Technology, Mobiles, Laptops - Gadgets 360](https://github.com/AdguardTeam/AdguardFilters/assets/159278763/7bbe8e6f-ad60-49ba-974c-dc1060d1cebd)
Ads appearing.

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
You need to follow the instruction about microShield userscript installation.
Please refer https://github.com/AdguardTeam/AdguardFilters/issues/178058.
