### ISSUE TITLE
Mobile.twitter.com cosmetic filters broken by annoyances list

### ISSUE THREAD

**Issue by rodalpho** [AdguardTeam/AdguardFilters#18073]
***Description***:
The AdGuard Annoyances list filter:

Static filter mobile.twitter.com###react-root > div > .rn-1oszu61.rn-aqfbo4 

Breaks the mobile.twitter.com site when cosmetic filtering is enabled. This affects things like posting and replying to tweets.

* **Expected behaviour**: 

The popups should work.

***Steps to reproduce the problem***:

Install uBlock Origin, enable the AdGuard Annoyances list,  go to mobile.twitter.com, and try to post a tweet.

**Comment by BlazDT** [comment]
Thank you for the report, modified the rule, should hide the cookie now and don't block post feature.

**Comment by rodalpho** [comment]
Confirmed fixed, thank you!
