### ISSUE TITLE
rcore.co

### ISSUE THREAD

**Issue by Obokkastar** [AdguardTeam/AdguardFilters#180886]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

ublock origin 1.58.1b2

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://rcore.co/?aff=5

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter

### Add your comment and screenshots

The tracking parameter aff=5 is missed but can be removed with `||rcore.co^$removeparam=aff` . I do not know if a non-site-specific rule would be appropriate or not.

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
Very low traffic.
