### ISSUE TITLE
zazzle.com

### ISSUE THREAD

**Issue by Obokkastar** [AdguardTeam/AdguardFilters#180884]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

ublock origin 1.58.1b2

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.zazzle.com/store/Jake_Kaminski?rf=238724131204337145

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter

### Add your comment and screenshots

Website removes the unnecessary parameter rf=238724131204337145 itself on page load even with ublock origin off and firefox enhanced tracking protection disabled. Is appears to come as an interaction from asset.zcache.com where blocking any one of the 17 scripts causes it to not be cleared.

If any asset.zcache.com scripts are blocked, adding the rule `||zazzle.com^$removeparam=rf`  shows in ublock origin logger as removing the parameter but not if those scripts all run.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@Obokkastar Hi there! Could you please describe the problem in more detail? I'm not quite sure I understand the question.

**Comment by Obokkastar** [comment]
The website automatically removes its own tracking parameter from the URL after its scripts run. Adding a filter to ublock origin would not remove it before the script did it itself; I assume such scripting means they already collected that data. To remove the tracker I also had to stop their script from executing. I presume a proper solution requires finding and stopping the part of the script that was doing the cleanup.
