### ISSUE TITLE
tomthumb.com

### ISSUE THREAD

**Issue by VaelophisNyx** [AdguardTeam/AdguardFilters#181174]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

ublock origin, AdGuard Cookie Notices filter list 2.0.41.1

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.tomthumb.com

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Fanboy's Enhanced Tracking List, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social Widgets

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, Web Annoyances Ultralist, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist

### Add your comment and screenshots

1. Normal function

2. With Cookie Notification list enabled
<details><summary>Screenshot 1:</summary>

![Screenshot_5](https://github.com/AdguardTeam/AdguardFilters/assets/1534478/44c3ff86-8b84-4093-bd71-8c05e8e42e92)

</details>

<details><summary>Screenshot 2:</summary>

![Screenshot_4](https://github.com/AdguardTeam/AdguardFilters/assets/1534478/ff16721c-81ad-4be0-b371-d29ae63f12b8)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@VaelophisNyx Hello. Unfortunately, I can't reproduce the products with the extension turned off either. Could you please check these rules in the user rules?
```
tomthumb.com##+js(trusted-click-element, #onetrust-reject-all-handler)
tomthumb.com#@##onetrust-consent-sdk
```

**Comment by VaelophisNyx** [comment]
for clarification do you mean add that as a user rule, or see if its in my user rules already?

**Comment by VaelophisNyx** [comment]
If it was the former, trying it yielded no results
if it was the latter, it wasn't in there before just now

**Comment by jellizaveta** [comment]
Yes, I mean add rules to the user rules. Could you leave only the AdGuard Cookie Notices filter enabled and add these more rules to the first two: 
```
@@||cdn.cookielaw.org/scripttemplates/otSDKStub.js$domain=tomthumb.com
@@||geolocation.onetrust.com/cookieconsentpub/*/geo/location$domain=tomthumb.com
```
If it doesn't help, could you please send the screenshot of filtering log while reproducing this issue.

**Comment by VaelophisNyx** [comment]
alright with that and only the cookie notification filter on, it works now, though its drowning in ads and chat widgets

**Comment by VaelophisNyx** [comment]
oh, and with all filters renabled AND that custom filter, it works now!
