### ISSUE TITLE
www.rtl.nl

### ISSUE THREAD

**Issue by M1Aston** [AdguardTeam/AdguardFilters#181256]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

cookie filter

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.rtl.nl

### Ad Blocking

AdGuard Mobile Ads filter, EasyList

### Annoyances

AdGuard Cookie Notices filter

### Language-specific

AdGuard Dutch filter

### Add your comment and screenshots

1. cookie message

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>
![cookie](https://github.com/AdguardTeam/AdguardFilters/assets/43113612/4e315dac-e3b1-48df-90b9-aa53e035ca15)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
AdGuard blocks it.
