### ISSUE TITLE
Futura-sciences.com

### ISSUE THREAD

**Issue by frbona** [AdguardTeam/AdguardFilters#181261]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.4.1

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.futura-sciences.com/planete/photos/voyage-partir-birmanie-voyage-fascinant-antoine-1512/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Language-specific

AdGuard French filter

### Add your comment and screenshots

1. Ads section still persist after filters update

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

![Screenshot_20240611_130759_Bing](https://github.com/AdguardTeam/AdguardFilters/assets/76003831/3ced63f7-c30f-4ba1-a746-631438d3a7f5)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by frbona** [comment]
Hi @Sergey-Lyapin,

Which filters should i enable to fix the issue ?

**Comment by Sergey-Lyapin** [comment]
Hello @frbona, I can't reproduce this issue.
Please add `futura-sciences.com##div[class*="ad-parent"]` to user rules. Does it help?

**Comment by Sergey-Lyapin** [comment]
@frbona 
Please go to Settings > Filtering > Network. Do you have HTTPS-filtering enabled? Routing Mode is Local VPN, right?

**Comment by frbona** [comment]
Right, both settings are enabled

**Comment by frbona** [comment]
Per information, issue do not occur in private mode

**Comment by frbona** [comment]
Issue is resolved by enabling Adguard Mobile App Banners
You can mark this ticket as closed.
Thanks
