### ISSUE TITLE
www.blikopnieuws.nl

### ISSUE THREAD

**Issue by M1Aston** [AdguardTeam/AdguardFilters#181257]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

cookie filter

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.blikopnieuws.nl

### Ad Blocking

AdGuard Mobile Ads filter, EasyList

### Annoyances

AdGuard Cookie Notices filter

### Add your comment and screenshots

1. There is a big bar at the bottom of the page.
![cookie](https://github.com/AdguardTeam/AdguardFilters/assets/43113612/d39f6b4b-e4b6-4de3-8b47-3061f53c497b)

3. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by M1Aston** [comment]
I have ublock on Firefox.

**Comment by Alex-302** [comment]
Ok. In previous report our rule can't be applied by uBO from our filter (trusted rules can be used only from ad blocker's own filters).
