### ISSUE TITLE
mainichi.jp

### ISSUE THREAD

**Issue by zhya890** [AdguardTeam/AdguardFilters#181589]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

mainichi.jp

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter

### Language-specific

AdGuard Japanese filter

### Add your comment and screenshots

1. <comment>
Extra blank space is left here.

mainichi.jp###ad-pc-article-subsc_billboard

2. Screenshots
<details><summary>Screenshot 1:</summary>
![スクリーンショット 2024-06-17 201932](https://github.com/AdguardTeam/AdguardFilters/assets/83991086/0e670f41-9c0d-4791-98f2-29bdcda68519)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available soon.

**Comment by zhya890** [comment]
Thank You!
