### ISSUE TITLE
www.oricon.co.jp

### ISSUE THREAD

**Issue by zhya890** [AdguardTeam/AdguardFilters#181599]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.oricon.co.jp/news/2279154/full/

### Ad Blocking

AdGuard Base filter, EasyList

### Language-specific

AdGuard Japanese filter

### Add your comment and screenshots

1. <comment>
Extra blank space is left here.

oricon.co.jp###sticky > div.sticky-right-column1:first-child > div.sticky-right-column-item1.stickyfill > aside.block-sub.block-sub-news:last-child > div.border-box:last-child > table:first-child > tbody:nth-child(6) > tr

2. Screenshots
<details><summary>Screenshot 1:</summary>

![スクリーンショット 2024-06-17 220612](https://github.com/AdguardTeam/AdguardFilters/assets/83991086/1f776505-e414-4e52-baa8-2ce6f6c98c6d)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available soon.

**Comment by zhya890** [comment]
Thank You!
