### ISSUE TITLE
oricon.co.jp

### ISSUE THREAD

**Issue by zhya890** [AdguardTeam/AdguardFilters#181611]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.oricon.co.jp/news/2279154/full/

### Ad Blocking

AdGuard Base filter, EasyList

### Language-specific

AdGuard Japanese filter

### Add your comment and screenshots

1. <comment>
Extra ADs.

oricon.co.jp##.affiliateLinks

2. Screenshots
<details><summary>Screenshot 1:</summary>

![スクリーンショット 2024-06-17 233149](https://github.com/AdguardTeam/AdguardFilters/assets/83991086/1901e2cb-51dd-4949-bcfd-1220732ad162)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/c46a9e6d7e405ce2fd24edf1214061c59c4c01f3

**Comment by zhya890** [comment]
Sorry.
Thank you!
