### ISSUE TITLE
Fake KMS activators

### ISSUE THREAD

**Issue by PhoenixFossGR** [AdguardTeam/AdguardFilters#181859]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Safari

### AdGuard version

Version 1.11.18 (build 332, CT 2.0.44)

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

Multiple websites

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Fanboy's Enhanced Tracking List, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List

### Social Widgets

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

All of them are fake and malicious. A few of them are blocked by AdGuard, but most are not. They deceive users into downloading malware by making them believe they are installing a legitimate Windows activator.

```
kmspico.ws
kms-full.com
Kmspico.io
kms-tool.com
Kmsauto.info
officialkmspico.com
Ultrasonica.info
kmspicoofficial.com
Kmspi.co
Kms-pc.com
Thewindowsactivator.com
Get-kmspico.com
getkmspico.com
heukmsactivator.com
Furykms.com
kmsofficial.org
Kmspico-official.org
Yasir252.com
karanpc.com
getintopc.today
```

I also suggest the following filter: `||*kms*.*pico*.*activator*^`

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Where did you found them?

**Comment by Alex-302** [comment]
Ok, found them with Indian IP.

**Comment by abidjauhar17** [comment]
> ```
> yasir252.com
> karanpc.com
> getintopc.today
> ```

@PhoenixFossGR why did you add these 3 websites?
This website not only provides KMS activator, but also other software
and on `yasir252.com` the website comes from my country, Indonesia. it also provides other software for download

**Comment by abidjauhar17** [comment]
> These types of websites appear in Google search results when people search for KMS activators, misleading people into downloading them. Almost all KMS activators that run as executables contain serious malware. I also checked every single one of them on VirusTotal, and here is one example:
> 
> <img alt="image" width="1318" src="https://private-user-images.githubusercontent.com/123986260/341459564-df121ea1-29ae-4de9-a259-afff78785df1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4OTYwOTAsIm5iZiI6MTcxODg5NTc5MCwicGF0aCI6Ii8xMjM5ODYyNjAvMzQxNDU5NTY0LWRmMTIxZWExLTI5YWUtNGRlOS1hMjU5LWFmZmY3ODc4NWRmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQxNTAzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGE3MWNjZTBjMjcxNmNkM2U0Y2IwZWM0NThmNzNhNGM0OGZjNGRkODRhYWY3ZTM5Y2ZjZWU2ZDYyNzkxNGJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X6ddnNto0zV8pIOmhOjJ3oWsoyn8K0iwYcT7RuXc7ng">
> Here is a very recent analysis video that shows many of the links I reported: `https://youtu.be/mDyODRZq1GA`
> 
> I am not familiar with any of these sites personally, so yes, there is a chance I made a mistake with some of them. If you believe I made a mistake, please provide data that proves that they do not contain malware, phishing, scams or anything malicious.

You provide a large list of websites.
So which KMS website do you think doesn't contain viruses?

**Comment by abidjauhar17** [comment]
> Based on what I've seen from other independent online security analysts and from VirusTotal, all of them should be malicious or scams. But of course, I could be mistaken.

Many say using M.A.S is safer than other activators

**Comment by KevGreenwood** [comment]
Hi, I know this is an old topic but I am glad to know that the FuryKMS website has been blacklisted, to make a long story short I was the original author of the activator which was open source, however a third party compiled a version with malware and uploaded it to that site, I'm currently finishing the last iteration of my activator to finally release it.
