### ISSUE TITLE
getkmspico.com: Badware

### ISSUE THREAD

**Issue by PhoenixFossGR** [AdguardTeam/AdguardFilters#181844]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Safari

### AdGuard version

Version 1.11.18 (build 332, CT 2.0.44)

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

getkmspico.com

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Fanboy's Enhanced Tracking List, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social Widgets

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, Web Annoyances Ultralist, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

This website is a total nightmare. It is filled with malicious and phishing ads and pop-ups. Clicking anywhere results in a random malicious website appearing. I recommend blocking this domain entirely, as there are multiple associated malicious domains.

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I don't see popups there.

---


Try to clear browser data, leave only AdGuard filters (the list of the filters below), update them (wait almost one minute there), open the site.
If that doesn't work, you should re-enable the content blockers in Safari settings (wait about the same time as when you update the filters).
```
AdGuard Base
AdGuard Tracking Protection
AdGuard Social Media
AdGuard Annoyances
```
