### ISSUE TITLE
temu.com track params

### ISSUE THREAD

**Issue by hurgir** [AdguardTeam/AdguardFilters#182182]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

 4.3.53

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

temu.com

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Add your comment and screenshots

1. <comment>
The temu.com site adds various tracking and affilate links to urls. I added these filters to my personal filter list and tried them for 3 weeks and did not encounter any problems.
link 1:
https://www.temu.com/goods.html?_bg_fs=1&goods_id=601099515313495&_x_sessn_id=uhnu2qvuvo&refer_page_name=bgt_order_receipt&refer_page_id=10471_1718277961666_tdvyd6mvrs

params 1:
_bg_fs
_x_sessn_id
refer_page_name
refer_page_id

link 2:
https://www.temu.com/goods.html?goods_id=601099514889442&sku_id=17592205444096&refer_share_id=okaxyflouvlz7jbeaxvmgj8zrej9117t&refer_share_channel=copy_link&_oak_page_source=417&_oak_region=203&refer_share_suin=RSSBA4XLGIME5JTNPRQGA3WFXGHT5GU6AMGYXG7DHM3GFJTAAMKEG6ISXWATDUKPI2DL55EF5I

params 2:
sku_id
refer_share_id
refer_share_channel
_oak_page_source
_oak_region
refer_share_suin

link 3:
https://www.temu.com//bronze-ay-y%C4%B1ld%C4%B1z-kuvars-cep-saati-vintage-moda-kolye-zinciri-saat-eid-al-adha-ramadan-kareem-kad%C4%B1nlar-ve-erkekler-i%C3%A7in-hediyeler-g-601099549677058.html?_oak_mp_inf=EIKsiKmm1ogBGhZnb29kc181M2NyOWNfcmVjb21tZW5kIPSUk4uBMg%3D%3D&top_gallery_url=https%3A%2F%2Fimg.kwcdn.com%2Fproduct%2Fopen%2F2024-03-04%2F1709566868743-1316b2d12adc4bbfbf57d61359ba7969-goods.jpeg&spec_gallery_id=4106700595&refer_source=10016&freesia_scene=11&_oak_freesia_scene=11&_oak_rec_ext_1=MTAwNDg&_oak_gallery_order=690148383%2C961207598%2C859358083%2C779219786%2C40271338&_x_channel_scene=spike&_x_channel_src=1

params 3:
_oak_mp_inf
top_gallery_url
spec_gallery_id
refer_source
freesia_scene
_oak_freesia_scene
_oak_rec_ext_1
_oak_gallery_order
_x_channel_scene
_x_channel_src

link 4:
https://www.temu.com/goods.html?share_img=https%3A%2F%2Fimg.kwcdn.com%2Fproduct%2Ffancy%2Fec18f382-a617-492f-bdcb-a51277fd8d35.jpg&from_share=1&goods_id=601099581551934

params 4:
share_img
from_share
3. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by piquark6046** [comment]
How to get the parameters from the website?

**Comment by hurgir** [comment]
> How did you get the parameters from the website?

These links are to a forum where users share deals and shopping."https://forum.donanimhaber.com/temu-indirim-firsat-ve-kampanyalar-ana-konu--158899451-3#158899857"
