### ISSUE TITLE
[iOS] soundcloud.com - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1821]
Ad appears when trying to play a song through this website on iPad. The ad won't go away and the song never plays

Missed ad on page:
https://soundcloud.com/flux-pavilion/flux-pavilion-i-cant-stop

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.79.77 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.7 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.87 Enabled=NO
ID Name="Mobile ads filter" Version=1.0.2.80 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID1 Name="EasyList" Version=1.0.48.96 Enabled=NO
ID8 Name="EasyPrivacy" Version=1.0.49.54 Enabled=NO
ID2 Name="Fanboy's Annoyances" Version=1.0.48.60 Enabled=NO
ID!5 Name="Fanboy's Enhanced Tracking List" Version=1.0.1 Enabled=NO
ID 4 Name="Peter Lowe's list" Version=1.0.1.72 Enabled=NO
ID 6 Name="Xfiles" Version=1.0.0.39 Enabled=NO
ID 7 Name="Adblock Warning Removal List" Version=1.0.54.71 Enabled=YES
ID 9 Name="Prebake" Version=1.0.1.10 Enabled=YES
ID!1 Name="Anti-Adblock Killer | Reek" Version=1.0.1.58 Enabled=YES

**Comment by Alex-302** [comment]
@evgeniy-ADG 
I need a screenshot, because I don't have real device

**Comment by evgeniy-ADG** [comment]
@Serzh-SUP

**Comment by evgeniy-ADG** [comment]
The customer is refusing send us a screenshot, asked again.

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/14013546/bf62031a-f1b5-11e5-8286-e9d0221b794c.png)

**Comment by Alex-302** [comment]
It is youк own screenshot? I don't see it on Android tablet without filtering.
