### ISSUE TITLE
canada.ca

### ISSUE THREAD

**Issue by reprting4dty** [AdguardTeam/AdguardFilters#182194]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

AdGuard ~~Annoyances~~  _Social Widgets_ filter for uBlock Origin - updated today

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome, Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

Many. Examples - https://www.canada.ca/en/services/culture.html;  https://www.canada.ca/en/services/jobs.html 

### Ad Blocking

EasyList

### Social Widgets

AdGuard Social Media filter

### Add your comment and screenshots

1. <comment> Many webpages on the Government of Canada's website (canada.ca) have a "Date modified" CMS tag near the bottom, just above the black footer section. (This is important for multiple reasons, including that people may need to know when the page has been modified so they can look for the changed content on the page.)

For a large number of those webpages, the "Date modified" line is stripped out by three popular filter lists for uBlock Origin:

* AdGuard - Social Widgets

* EasyList - Social Widgets

* Fanboy's Annoyance List

(I confirmed each had that effect with careful one-by-one process of elimination.)

This is on Chrome and Edge for Windows, fully updated with updated extensions and filters.

Here are examples of two high-level webpages on which this occurs:

https://www.canada.ca/en/services/culture.html

https://www.canada.ca/en/services/jobs.html

(I have already reported this on the Lanik forums to request action on the same problem in the EasyList and Fanboy filters.)

Thank you for your help.

3. Screenshots
<details><summary>Screenshot 1:</summary>

Date modified visible:
![image](https://github.com/AdguardTeam/AdguardFilters/assets/173762823/2e13ded2-a141-4a11-a8c2-54a265447f22)
</details>

<details><summary>Screenshot 2:</summary>
Date modified removed:

![image](https://github.com/AdguardTeam/AdguardFilters/assets/173762823/0b28c225-c471-4dc6-823b-d303dc111ff3)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
