### ISSUE TITLE
mp3-pn.com [Pop-Up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#18219]
**Site**: https://mp3-pn.com/song/73754661/Antony_Blaze_-_Valley_Of_The_Dreams/

**Issue**: Please remove the pop-ups seen when clicking on the Play/Download or moving the seekbar of the music being played on the page.
 
**Screenshot**: N/A

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 67.0.3396.87 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
Not reproduced.
@AdamWr

**Comment by AdamWr** [comment]
Added:
```
mp3-pn.com#%#window.zfgloadedpopup = true;
mp3-pn.com#%#(function() { window.open_ = window.open; var w_open = window.open, regex = /demolat\.com/; window.open = function(a, b) { if (typeof a !== 'string' || !regex.test(a)) { w_open(a, b); } }; })();
```
