### ISSUE TITLE
walmart app

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#182233]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.6

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.walmart.android

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

Tracker: collector-pxuarm9b04.perimeterx.net

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It is not a tracker.

**Comment by jordanswrld94** [comment]
Should we remove these from the dns filter then?
|collector-*.px-cloud.net^
||collector-*.px-cdn.net^
||collector-*.pxchk.net^

@Alex-302

**Comment by Alex-302** [comment]
Removed.
