### ISSUE TITLE
fmovie.cc [Pop-Up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#18229]
**Site**: https://fmovie.cc/

**Issue**: Please remove the pop-up on the page.

**Screenshot**: http://prntscr.com/jb0i1w

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 67.0.3396.79 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Anti-Adblock Killer-Reek, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by Alex-302** [comment]
Not reproduced.

**Comment by Nzzyme** [comment]
This is not resolved. I am still seeing pop-ups on the page that redirect to zukxd6fkxqn.com

**Comment by AdamWr** [comment]
Added:
`fmovie.cc#%#window.zfgloadedpopup = true;`

**Comment by Nzzyme** [comment]
Thank you.

**Comment by Nzzyme** [comment]
Pop-up seen on this page:

https://www5.fmovie.cc/

Please add
