### ISSUE TITLE
AdGuard no longer blocks ads on Disney+

### ISSUE THREAD

**Issue by troaphy** [AdguardTeam/AdguardFilters#182396]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS, AdGuard for iOS

### AdGuard version

4.5.4 on iOS, idk about the DNS

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://disneyplus.com

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### DNS filters

AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Hide your search queries

### Add your comment and screenshots

Recently, AdGuard no longer works on Disney+ after months of working just fine. This initially started on my iPhone before it started affecting my TV too.  

[IMG_0635](https://github.com/AdguardTeam/AdguardFilters/assets/96665071/a7d2c8a5-5b5a-481e-8b16-42e512da35f1)
[IMG_0634](https://github.com/AdguardTeam/AdguardFilters/assets/96665071/78ea3b59-9a8e-4a62-b43c-f3b2555f0bed)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@troaphy AdGuard for iOS may not block all ads, because iOS has critical bugs, related to filtering, and it does not have native way for applying advanced rules.

Also we cannot check, because we don't have an account.

> This initially started on my iPhone before it started affecting my TV too.

I think they just started to show ads for you.
