### ISSUE TITLE
Ad elements are not being hidden in Google News app on Android

### ISSUE THREAD

**Issue by zefwef** [AdguardTeam/AdguardFilters#18244]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Ads in the Google News app on Android are blocked, but the elements containing the ads are not hidden and display the text "Webpage not available."

***Steps to reproduce the problem***:

[//]: # Turn on Adguard and open the Google News app. Select an article containing ads.

***System configuration***

**Filters:**

[//]: # English, Mobile Ads, Spyware

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android) | 9
AdGuard version:                       | 2.12.60
Filters enabled:                       | English, Mobile Ads, Spyware
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
This app uses own encryption an cannot be filtered.
