### ISSUE TITLE
270towin.com: detection

### ISSUE THREAD

**Issue by PhoenixFossGR** [AdguardTeam/AdguardFilters#182464]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Safari

### AdGuard version

Version 1.11.18 (build 332, CT 2.0.44)

### What type of problem have you encountered?

AdGuard gets detected on a website, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.270towin.com/2024-presidential-election-polls/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Fanboy's Enhanced Tracking List, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List

### Social Widgets

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

This website detects AdGuard and shows this pop up.

<details><summary>Screenshot:</summary>

<img width="967" alt="image" src="https://github.com/AdguardTeam/AdguardFilters/assets/123986260/b3237662-71ce-40e7-818d-708c0c39ed48">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Not reproduced with AdGuard filters on my end. Leave only them like the config below, update filters (do not close AdGuard window ~ 1-2 min), clear browser data, restart it.
```
AdGuard Base
AdGuard Tracking Protection
AdGuard Annoyances
```
