### ISSUE TITLE
Scam websites

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#182518]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Safari

### AdGuard version

Latest

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

Multiple websites

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

The following domains are being spread by bots on Twitter and on other websites in order to scam users. Some of them are phishing links, others are plain scams, others might be malicious, and others are adware or redirection websites that pass through malicious domains.

```
hsuitehub.com
teslafond.io
pump.fun/H4j8NPrYBk2ZuweAy2oYkrehaEHrK5J8YHsm45krpump
ousd-vault.com
dash.pocketuniverse.app/ref/GERU
https://avarik.web.app/progress/QWU4NnRydWVubzA0OzM0Nzk7MjE0Mzs4UVdOVlc7aHR0cHM6Ly9wYnMudHdpbWcuY29tL3Byb2ZpbGVfaW1hZ2VzLzE3OTk3Njc1Nzc4ODkyMzkwNDEvM19kYVFxYVFfbm9ybWFsLnBuZw==
ddzk513bd.com
uprising.kip.pro/join?ref=QYFVKK
app.jameswoof.com/login?invitecode=W5135014
miles.plumenetwork.xyz/mint
earth-ling.org
https://pambi.tech/airdrop/GHqQSvqBMWccHgQnWRZKQ8phLbQJni55KX8HHfKNdoYF
http://help.premium-x-notes.com
dInp2rm.suitablepartner.life/uzmrwfe
p𝓸𝘳𝘯𝚔𝘢f.net/fea
netfucks1.com
c.dreamdating1.fun
yoursecrethookup.com
brttre.com
ohmysweetromancespot.life
𝚋yest𝚊r.com/hot
yourdatefind.com
hushlove.com
olosex.pics/fap
veilcurtin.world
yikesgroto.com
midnightsociety-x.com
2d45b3cf2299d8ba038f45cb38aca4f2ecfbcb8d264ba28432ae5c51.com
corroercl.xyz
miahershberger.buzz
viktoriadelenick.za.com
h.yqyh571.xyz
```

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I see you have some list of scam sites. Better send it to support@adguard.com.
