### ISSUE TITLE
wsj.com

### ISSUE THREAD

**Issue by antonme** [AdguardTeam/AdguardFilters#182768]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

version: 2.3.42.32 updated: July 2, 2024 at 08:31 PM

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome, other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

Arc with Chromium Engine Version 126.0.6478.127, but the problem reproduceable everywhere

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. Example URL: https://www.wsj.com/politics/elections/tight-inner-circle-urges-biden-to-press-on-cef5b69b?mod=hp_lead_pos7

2. Screenshots
<details><summary>Article without much of its text:</summary>
![image](https://github.com/AdguardTeam/AdguardFilters/assets/1531009/0a748282-a3df-4c43-8d92-ff4c51a34ed9)

</details>
<details><summary>Same article with base filter off:</summary>
![image](https://github.com/AdguardTeam/AdguardFilters/assets/1531009/1369c8e4-0c9e-4747-81a7-15051db335b9)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
