### ISSUE TITLE
habr.com

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#182761]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [ ] AdGuard product version is up-to-date;
- [ ] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.11/54

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://habr.com/ru/feed/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies

### Add your comment and screenshots

1. Собственно сабж. На хабре под авторизованный аккаунте, в разлеле "моя лента" напичканы промо/рекламные блоки. Грузятся постфактум и обычными правилами забороть не удалось. Промо грузилось  с effect.habr.com, только какие-бы я к нему правила не применял, блоки всё равно грузились, пока я его тупо не локкнул через hosts. Блоки "ГОЛОС СВЫШЕ" грузятся по другой схеме, пока не вникал.

2. Screenshots

<details><summary>Screenshot №:1</summary>

![2024 07 03_08 43 10~01](https://github.com/AdguardTeam/AdguardFilters/assets/12525093/023d0b24-8abd-4cf2-a951-b8f546368f41)

</details>

<details><summary>Screenshot №:2</summary>

![2024 06 28_18 26 08~01](https://github.com/AdguardTeam/AdguardFilters/assets/12525093/3058b237-4f9a-4eaa-95a0-5461a2739510)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
`Голос свыше` в ленте не наблюдаю, но другое промо убрал. Обновление в фильтрах станет доступно через пару часов.

**Comment by Baltazar500** [comment]
@zloyden, как раз этот "голос свыше" глаза и мозолит. Попробуйте новый акк регнуть. Я там новичёк, так что походу потому и лезет.

**Comment by zloyden** [comment]
Вот на новом и нет этого. Если еще есть оно, пришли сохраненную страницу zip архивом на filters@adguard.com.

**Comment by Baltazar500** [comment]
.Отправил

**Comment by zloyden** [comment]
Ага, увидел. Добавил правило, которое должно помочь. Обновление в фильтрах станет доступно через пару часов.

**Comment by Baltazar500** [comment]
Спасибо. Блоки скрылись
