### ISSUE TITLE
https://github.com/notifications/beacon/.......gif

### ISSUE THREAD

**Issue by elvis-hrvat** [AdguardTeam/AdguardFilters#182867]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://github.com/notifications/beacon/BCAUPRASDHLMUXMTDWP7BJLZKUQ7HA5CNFSM6AAAAABKLI6EVOWGG33NNVSW45C7OR4XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHI47GIZM.gif

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Language-specific

AdGuard Japanese filter

### Add your comment and screenshots

1. Tracking pixels are not blocked. This image is included in newsletters sent from notifications@github.com.
2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Yuki2718** [comment]
@jellizaveta We already have `||github.com/notifications/beacon/$important`.

**Comment by jellizaveta** [comment]
@Yuki2718 Won't work on tracking pixels in the email because of the email client's proxy
