### ISSUE TITLE
links.mail.crunchyroll.com

### ISSUE THREAD

**Issue by elvis-hrvat** [AdguardTeam/AdguardFilters#182882]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://links.mail.crunchyroll.com/wf/open?upn=u001.hmJObf9614OzCwvvgejPu8ukS-2FYxzCW-2B9SLWsRuws9OGJwX-2BzZzuYj8yM56QgIVSwcHcf4CXojjyo5o1OYziHQoX-2BMoyoFZn2W1udkPx-2FM5N17unKHlGrkvrmi1loei3GSLIDpXfa2q-2FE4JJ2nNm-2FaDIEQnWm1AlKfaVMIWuiX37nxQfwlVb1jry8cqMpCE-2FgS2A5RCWA9kt3s2jFib6pBVmT0lQnYkco8rw9-2BtfLm5mY4gkBjhyI59yJ1tzX1PEaMUBUa3VC-2FhLPM8URElYJeJsvp6N06gaGzYDnwBwgeVX4ACxiKliJbqndm5jr0d0hCQzTXS3mjZoppcDSkn6ujjMIbAdNYU-2F8XKWauxTqVdmXde-2FEYi2HDcy5QSmrBzZzQ-2F46x2Xaa5GGPY-2BBm9-2FtXeZGy8823UsK-2B86ZBCMnTj8I3GG9Wj9oFLnclkrsQDnwBy5OXg4iREO-2BorJ4Con54AMwyiv03fyCy67TT64mfk6-2FQUFJmFXWOQx9Nim1QjzvxnUmelTs4ZbD926Zms4cYMmmt2tWzTa17aH8msqSXk7vVeIsJfqed1aVZxF6FHbP7mmt9uunzTr0mbuNdOep9jwZImo8aaGD7pHePizIto7nHYPwjg2t7anRf9oOrtV9z6c-2Fy8uW3K4NQb6ndqc7To-2FRsXAXQDgjTFW9rP8qYZ5Hek9qgV5-2FwM0ZPaW4RUw

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Annoyances

AdGuard Cookie Notices filter, EasyList Cookie List

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Chinese filter, AdGuard Japanese filter

### Add your comment and screenshots

1. Tracking pixels are not blocked. This image is included in newsletters sent from hello@info.crunchyroll.com.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Already blocked by 
```
/wf/open?upn=$image
%2Fwf%2Fopen%3Fupn%3D$image
```
