### ISSUE TITLE
mandrillapp.com

### ISSUE THREAD

**Issue by elvis-hrvat** [AdguardTeam/AdguardFilters#182875]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://mandrillapp.com/track/open.php?u=31032185&id=79afdfae6e7e4d28b936ab9735b76536

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Annoyances

AdGuard Cookie Notices filter, EasyList Cookie List

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Chinese filter, AdGuard Japanese filter

### Add your comment and screenshots

1. Tracking pixels are not blocked. This image is included in newsletters sent from notification@service.spamhaus.com.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Should be blocked by 
`/track/open.php?u=$image`
or
`%2Ftrack%2Fopen.php%3Fu%3D$image`
Could you please send a sample letter without personal information?

**Comment by jellizaveta** [comment]
Yes, already blocked

**Comment by jellizaveta** [comment]
I answered in https://github.com/AdguardTeam/AdguardFilters/issues/182878 comment. Please, show in the filter log with AdGuard Tracking Protection filter enabled a non-blocked tracking pixel when you open a page with an email
