### ISSUE TITLE
email.bitbank.cc

### ISSUE THREAD

**Issue by elvis-hrvat** [AdguardTeam/AdguardFilters#182866]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://email.bitbank.cc/trk?t=1&mid=NjY3LVNYRy0xMDgAAAGUHBhyzRkG-8h-GoT-FrAKiJ6f865_JDHJZfazEROrxVBFMM_boAQUg3N-aKVOXN2FZeHFu5rFnDaxy1vCmdXspCP1zOXR9w16sRGaaYpfoqkxE_3Ll0uPq_8evnaj5wusYnXS9mFf-gk

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Language-specific

AdGuard Japanese filter

### Add your comment and screenshots

1. <comment>
Tracking pixels are not blocked. This image is included in newsletters sent from noreply@bitbank.cc.

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available soon.
