### ISSUE TITLE
link.pixiv.net

### ISSUE THREAD

**Issue by elvis-hrvat** [AdguardTeam/AdguardFilters#182873]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://link.pixiv.net/wf/open?upn=u001.AIJWcdPBGVnWRD71Xl9ipleVaSasp2TPXp-2FTtBhP7xbCIR2iyCm83Bjm-2FBkb8ROTOIlL1IIMASeyXgsWmWZpyyAdUGsYI9zH8KLPzQUpFSh9xDQ-2FsN7tosDxk7lcLt2JQsuV7hNc3h1Dp4FWXVV49W1SYPc6N40GLnNKtNu-2FoWMVsFPjuN0QPIIidmF1blwLi7S7ha8hbQ4u670kHEFFYwgyOR3m6ca3sDTN2-2F6LP4RN0Frppw4ZpcTajC9LVeDxcYH3AVLG-2FQNRZg7BrSZ-2BYmg6VNLz-2FN-2BqszDap6zlLXYf-2Fz82osQvzaI5pC3LGeFg

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Annoyances

AdGuard Cookie Notices filter, EasyList Cookie List

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Chinese filter, AdGuard Japanese filter

### Add your comment and screenshots

1. Tracking pixels are not blocked. This image is included in newsletters sent from no-reply@pixiv.net.

### Privacy

- [X] I agree to follow this condition

**Comment by Yuki2718** [comment]
Please provide actual urls the tracking pixel will be seen.

**Comment by Yuki2718** [comment]
Okay

**Comment by Yuki2718** [comment]
This is already caught by `/wf/open?upn=$image`.

**Comment by Yuki2718** [comment]
@Alex-302 Should we add a  rule with `%2F` replacement?

**Comment by Alex-302** [comment]
I will check all these issues.

**Comment by Yuki2718** [comment]
Actually we already have `%2Fwf%2Fopen%3Fupn%3D$image` too, closing. Please report only those actually unblocked.
