### ISSUE TITLE
images.ctfassets.net

### ISSUE THREAD

**Issue by elvis-hrvat** [AdguardTeam/AdguardFilters#182876]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://images.ctfassets.net/7rifqg28wcbd/6Xa3RLs8deEywtgXmAo9JV/61b1ee3576f0473ea04f86166fc8f4b1/spacer.gif

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Annoyances

AdGuard Cookie Notices filter, EasyList Cookie List

### Language-specific

AdGuard Chinese filter, AdGuard Japanese filter

### Add your comment and screenshots

1. Tracking pixels are not blocked. This image is included in newsletters sent from PayPal@emails.paypal.com.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Does not look like a tracker.
