### ISSUE TITLE
www.amazon.co.jp

### ISSUE THREAD

**Issue by elvis-hrvat** [AdguardTeam/AdguardFilters#182884]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.amazon.co.jp/gp/r.html?C=9KE1SRS9EJSV&K=2YVB5SSIBI3Q2&M=urn:rtn:msg:20240630122855112d0febf1fb469ab37964d95c20p0fe&R=2F30PSCMLWGR9&T=E&U=https%3A%2F%2Fimages-fe.ssl-images-amazon.com%2Fimages%2FG%2F01%2Fnav%2Ftransp.gif&H=SECJNTMOIZFSPGNORVD0GFHW32YA&ref_=pe_2323522_278267842_open

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Annoyances

AdGuard Cookie Notices filter, EasyList Cookie List

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Chinese filter, AdGuard Japanese filter

### Add your comment and screenshots

1. Tracking pixels are not blocked. This image is included in newsletters sent from gc-orders@gc.email.amazon.co.jp.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Need eml file.
