### ISSUE TITLE
Add the "Content Farm" and "Low Traffic" labels

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/AdguardFilters#182911]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Avoid type words like "garbage", "trash" etc. on the comments. Because from the perspective of end users reporting issue, the concepts are inappropriate and very open to misunderstandings. Use a more appropriate term.

### Proposed solution

Add the "Content Farm" label (With tooltip: Farming, Low-quality, auto-generated content sites etc for high traffic & ads revenue.)

The term "Content Farm" is used to describe sites filled with particularly low-quality, often auto-generated or copied content. Such sites are generally created to attract high traffic and generate ads revenue.

Add the "Low Traffic" label (With tooltip: This issue cannot be resolved due to low traffic <100k.)

**Comment by Alex-302** [comment]
No need.
