### ISSUE TITLE
m.ctrip.com

### ISSUE THREAD

**Issue by chengnan049** [AdguardTeam/AdguardFilters#183040]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.5.17

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

m.ctrip.com

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Other

AdGuard Experimental filter

### Language-specific

YousList

### What Stealth Mode options do you have enabled?

Hide your search queries, Self-destruction of third-party cookies

### Add your comment and screenshots

1. This rule will make m.ctrip.com cant login.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot_20240706-144823_AdGuard](https://github.com/AdguardTeam/AdguardFilters/assets/46060083/1041c603-7497-4d7d-a836-3224c961bd61)

</details>

<details><summary>Screenshot 2:</summary>

![Screenshot_20240706-144823_AdGuard](https://github.com/AdguardTeam/AdguardFilters/assets/46060083/c0a9bd46-d431-42a1-bedc-2357576e1dfb)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It is loaded from EasyList. Reported to the author.
