### ISSUE TITLE
Email tracking pixels

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#183060]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge, other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

mail.google.com

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Other Annoyances filter

### Security

Online Malicious URL Blocklist

### Add your comment and screenshots

Email tracking pixels:

In Google Mail (text after hashtag in ci3.googleusercontent.com request):

- https://emea.focusvision.com/tracker/v7y552UNmX
- https://links.news.maxima.lv/o/kt9/3p9Y8gqR2IAc1gxjj8Yc3a/md98/F/353377aa
- https://files.fm/l/email-pix

In Proton Mail (with removed user identifying url parameters): 

- https://mail.proton.me/api/core/v4/images?Url=https%3A%2F%2Freferrer.disqus.com%2Fjuggler%2Fevent.gif
(https://referrer.disqus.com/juggler/event.gif)

- https://mail.proton.me/api/core/v4/images?Url=http%3A%2F%2Femailcontent.rockstargames.com%2Fp%2Fcp%2Fa817918b107990d0%2Fo.gif
(http://emailcontent.rockstargames.com/p/cp/a817918b107990d0/o.gif)

- https://mail.proton.me/api/core/v4/images?Url=https%3A%2F%2Fclick.email.vimeo.com%2Fopen.aspx
(https://click.email.vimeo.com/open.aspx)

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@andris86 Hello. Could you please send saved pages with emails as HTML to `filters@adguard.com`?

**Comment by jellizaveta** [comment]
@andris86 Yeah, sure

**Comment by jellizaveta** [comment]
Thank you, the trackers have been added. The update will be available within 1–2 hours.

**Comment by Yuki2718** [comment]
@andris86 
> with removed user identifying url parameters

Is actual url of e.g. `https://mail.proton.me/api/core/v4/images?Url=https%3A%2F%2Freferrer.disqus.com%2Fjuggler%2Fevent.gif` longer and `%3F` follows? I wonder if
```
%2Fevent.gif%3F
%2Fo.gif%3F
%2Fopen.aspx%3F
```

catches them for EasyPrivacy.

**Comment by Yuki2718** [comment]
> %2Fo.gif is followed only by DryRun parameter

What characters exactly?

**Comment by Yuki2718** [comment]
`%2Fo.gif` may cause false positive. Is `%2Fo.gif0` fine?

**Comment by Yuki2718** [comment]
Thanks, so `%2Fo.gif&`.
