### ISSUE TITLE
xbabe.com [Ad]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#18306]
**Site**: https://xbabe.com/videos/brunette-with-big-tits-tries-anal-in-crazy-scenes/

**Issue**: Ad bar that stays at the bottom of the page when scrolling

**AdGuard Version**:
- AdGuard for Android 2.11.81

**System**:
- Android version: 6.0.1 MMB29M
- MIUI version: MIUI Global 9.5 - Stable [ 9.5.3.0 (MHOMIFA) ]

**Filters**:
English, Spyware, Social Media, Annoyances, Mobile Ads, EasyList China, Anti-Adblock Killer-Reek

**AdGuard Settings**:

- Phishing & Malware Protection: Enabled
- Block ads in all apps: Enabled
- Search ads & self-promotion of sites: Disabled
- DNS Filtering: Disabled
- HTTPS Filtering: Enabled
- High quality filtering: Enabled
- Filtering mode is Local VPN

**Comment by Nzzyme** [comment]
Ad message on the video player.

https://xbabe.com/videos/arousing-milf-enjoys-young-meat/?promoid=1263

Screenshot: http://prntscr.com/mvg7q2

Please fix

**Comment by Alex-302** [comment]
Not reprodued.
