### ISSUE TITLE
rinku.me

### ISSUE THREAD

**Issue by detyso** [AdguardTeam/AdguardFilters#183012]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard Content Blocker

### AdGuard version

Latest

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox, Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

https://rinku.me/0XLi6

### Ad Blocking

AdGuard Base filter, EasyList

### Add your comment and screenshots

1. <comment> the website says to click on an ad to continue but adguard blocks it
2. Also They domain changes when you click on the link are crewbase.net batmanfactor.com beautifulfashionnailart.com

3. Screenshots
<details><summary>Screenshot 1:</summary>

![IMG_0695](https://github.com/AdguardTeam/AdguardFilters/assets/163365484/c231dbe9-390d-4a6b-8253-943def3bc118)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available soon.

**Comment by dnet890** [comment]
@zloyden it looks like for this rinku.me URL https://7mb.site/U6SXLYIM and then click the cloudflare verification and then you are greeted with adblock blocker. What do you think? 

<img width="757" alt="Image" src="https://github.com/user-attachments/assets/9c7908de-1e2b-431a-9e4e-ae769a56e03a" />

**Comment by zloyden** [comment]
It is best reported using our tools like [it was done here](https://github.com/AdguardTeam/AdguardFilters/issues/198028) and please do not leave comments in old tasks. Fixed, update should be available soon.
