### ISSUE TITLE
czech-craft.eu

### ISSUE THREAD

**Issue by wowfilip999** [AdguardTeam/AdguardFilters#183013]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.58.0

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://czech-craft.eu/

### Ad Blocking

EasyList

### Add your comment and screenshots

</details>
i ublock origin user  i have enabled adguard ads 
ad banner show on right side with background
can be simply fixed by add this settings
czech easylist seems not responding i will be happy if this will be fixed i seen some czech webs in filters

||czech-craft.eu/static/uploads/abanners/ss1.png$image
czech-craft.eu##.container-right

<details><summary>Screenshot N:</summary>

![obrazek](https://github.com/AdguardTeam/AdguardFilters/assets/67916726/f426b4c0-9243-42d7-bb74-dbbbb704a0b7)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available soon.
