### ISSUE TITLE
Scam site

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#183117]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

7k28lv6.woreunfish.live

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Other Annoyances filter

### Security

Online Malicious URL Blocklist

### Add your comment and screenshots

After clicking on download button in site mentioned in issue https://github.com/AdguardTeam/AdguardFilters/issues/183116 user gets directed to scam site.

<details><summary>Scam site window</summary>

![Screenshot 2024-07-07 201150 - Copy](https://github.com/AdguardTeam/AdguardFilters/assets/43014154/d61fe286-0ae1-4677-929a-2e4634f530b3)

![Screenshot 2024-07-07 202207](https://github.com/AdguardTeam/AdguardFilters/assets/43014154/2121254b-0917-4988-a281-b60d84ae9e2b)

</details>

Site might sometimes redirect user to other site where Adguard catches it.

<details><summary>Adguard has catched a scam site</summary>

![Screenshot 2024-07-07 201130](https://github.com/AdguardTeam/AdguardFilters/assets/43014154/f95a7a91-0ee9-428d-ad66-b8503bd8b04e)

![Screenshot 2024-07-07 201817](https://github.com/AdguardTeam/AdguardFilters/assets/43014154/52595cdc-fdc6-49ca-970f-b9e78a611724)
</details>

URL of one of scam links:
`https://7k28lv6.woreunfish.live/rxsexewg/?cid=813d3gxy9e816fe04c&u=6vl82k7&t=111&o=uwdw1nh&f=1&sid=t4~nfxf2yaloljj3dg21lcsw5zt&fp=GYZYdeoqX%2BKCchYuAauaFw%3D%3D`

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I see that was already blocked. Btw, if you notice some phishing sites, you can report them to support@adguard.com.
