### ISSUE TITLE
Joyn.de stops working properly when Privacy tracking is turned on

### ISSUE THREAD

**Issue by michalklempa** [AdguardTeam/AdguardFilters#183277]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://joyn.de

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter

### Add your comment and screenshots

I do believe filtering
- event-collector.prd.data.s.joyn.de
- heartbeats.prd.data.s.joyn.de

causes the webpage functionality to break. I.e. the Jetzt weiterschauen stops working completely. 
Have submitted the issue to the vendor, who says it might be related to AdGuard.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Does not work on my end with VPN

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardFilters/assets/8361299/162fccef-556b-4961-aff4-87452fb9bb57)


</details>


@BlazDT Please take a look.
