### ISSUE TITLE
Can't report website via link.adtidy.org

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardFilters#183462]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

N/A

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

N/A

### Ad Blocking

EasyList

### Add your comment and screenshots

https://link.adtidy.org/forward.html?app=win&v=7.18.4778.0&appid=5b1ce805094a46d78ce72ff97bf32c15&action=report&from=assistant&product_type=Win&product_version=7.18.1%20(4778)&url=https%3A%2F%2Fen.club-opel.com%2Fvideo%2Fhow-to-replace-dpf-differential-sensor-astra-14204&referrer=https%3A%2F%2Fduckduckgo.com%2F&user_agent=Mozilla%2F5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F123.0.0.0%20Safari%2F537.36%20OPR%2F109.0.0.0&filters=105.109.110.120.216.238.249.13.16.17.1.224.2.3.6.7.8.9&license_type=paid&userscripts=https%3A%2F%2Fgithub.com%2FAnarios%2Freturn-youtube-dislike%2Fraw%2Fmain%2FExtensions%2FUserScript%2FReturn%2520Youtube%2520Dislike.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F423435%2FIGG%2520Games%2520%2520bluemediafiles%2520bypass.user.js%2Chttps%3A%2F%2Fgreasyfork.org%2Fscripts%2F4646-google-direct-link%2Fcode%2FGoogle%2520direct%2520Link.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F394039%2FNexus%2520No%2520Wait.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F398802%2FGoogle%2520Images%2520direct%2520links%25202.user.js%2Chttps%3A%2F%2Fuserscripts.adtidy.org%2Fbeta%2Fadguard-extra%2F1.0%2Fadguard-extra.user.js%2CD%3A%5CDownloads%5CRedirect%2520Steam.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F33005%2FDirect%2520download%2520from%2520Google%2520Play.user.js%2Chttps%3A%2F%2Fgreasyfork.org%2Fscripts%2F425813-google-play-apk-downloader%2Fcode%2FGoogle%2520Play%2520APK%2520downloader.user.js%2Chttps%3A%2F%2Fraw.githubusercontent.com%2FMottie%2FGitHub-userscripts%2Fmaster%2Fgithub-image-preview.user.js%2Chttps%3A%2F%2Fgithub.com%2FMr-VIT%2FSteamWebTools%2Freleases%2Flatest%2Fdownload%2Fsteamwebtools.tm.user.js%2Chttps%3A%2F%2Fraw.githack.com%2FSak32009%2FGetDataFromSteam-SteamDB%2Fmain%2Fdist%2Fsak32009-get-data-from-steam-steamdb.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F461981%2F%25E6%25B5%258F%25E8%25A7%2588Steam%25E6%2597%25B6%25E8%2587%25AA%25E5%258A%25A8%25E9%25A2%2586%25E5%258F%2596Steam%25E8%25B4%25B4%25E7%25BA%25B8.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F446867%2FSkip%2520Steam%2520Age%2520Check.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F13858%2FShow%2520Metacriticcom%2520ratings.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F23564%2FAdd%2520SteamDB%2520info.user.js%2Chttps%3A%2F%2Fopenuserjs.org%2Finstall%2Fpromythyus%2FOpen_In_Steam.min.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F22104%2FSteam%2520DLC%2520wishlister.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F35532%2FSteam%2520Game%2520Page%2520-%2520Add%2520Links%2520To%2520Game%2520Trailer%2520%2520Gameplay%2520Search%2520On%2520YouTube.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F369980%2FSteam%2520totally%2520disable%2520autoplay.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F375742%2FYet%2520Another%2520Enhanced%2520Steam.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F32605%2FReSteam.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F37194%2FSteam%2520Store%2520-%2520Search%2520Results%2520Actions.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F379386%2FSteamDeveloperAndPublisherSearch.user.js%2CC%3A%5CUsers%5Cblusc%5CDesktop%5CNew%2520Text%2520Document.txt%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F397614%2FYoutube%2520Speed%2520By%2520Channel.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F491068%2FDiscord%2520Auth%2520Scope%2520and%2520Permission%2520Purger.user.js%2Chttps%3A%2F%2Fraw.githubusercontent.com%2FMottie%2FGitHub-userscripts%2Fmaster%2Fgithub-sort-content.user.js%2Chttps%3A%2F%2Fraw.githubusercontent.com%2FMottie%2FGitHub-userscripts%2Fmaster%2Fgithub-webhook-utils.user.js%2Chttps%3A%2F%2Fraw.githubusercontent.com%2FMottie%2FGitHub-userscripts%2Fmaster%2Fgithub-raw-menu.user.js%2Chttps%3A%2F%2Fuserscripts.adtidy.org%2Frelease%2Fassistant%2F4.3%2Fassistant.user.js%2Chttps%3A%2F%2Fuserscripts.adtidy.org%2Frelease%2Fpopup-blocker%2F2.5%2Fpopupblocker.user.js%2Chttps%3A%2F%2Fuserscripts.adtidy.org%2Frelease%2Fadguard-wot%2F1.0%2Fwot.user.js%2Chttps%3A%2F%2Fraw.githubusercontent.com%2FCitrinate%2FFreePackages%2Fmain%2FFreePackagesImporter%2Fcode.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F449046%2FNew%2520Steam%2520Workshop%2520Downloader.user.js%2Chttps%3A%2F%2Fgitlab.com%2Fcarbonwind%2Fsteamdetective%2F-%2Fraw%2Fmain%2FSteamDetective.user.js%2Chttps%3A%2F%2Fopenuserjs.org%2Finstall%2FVitoTheWolf%2FVacChecker.min.user.js%2Chttps%3A%2F%2Fopenuserjs.org%2Finstall%2Fn0name%2FSteamRep_Profile_Checker.min.user.js%2Chttps%3A%2F%2Fopenuserjs.org%2Finstall%2FRaikoZA%2FSteam_auto_agree_for_sales.min.user.js%2Chttps%3A%2F%2Fgist.githubusercontent.com%2Fpointfeev%2F31618a04ab2f754158ca7d950e1dd35c%2Fraw%2Chttps%3A%2F%2Fopenuserjs.org%2Finstall%2Ftkhquang%2FSteam_Community_-_Show_Nicknames_on_Badge_Page.min.user.js%2Chttps%3A%2F%2Fopenuserjs.org%2Finstall%2Falike03%2FSteam_Achievements_Helper.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F404754%2FASF%2520STM.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F379435%2FVacyourfriendsRemastered.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F428608%2Fsteam%2520protocol%2520opener.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F21808%2Fsteam%2520family%2520auto%2520login.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F20922%2FEnhanced%2520Steam%2520Community.user.js%2Chttps%3A%2F%2Fgithub.com%2FZeusJunior%2Fsteam-tradeoffer-alert%2Fraw%2Fmaster%2Fsteam-tradeoffer-alert.user.js%2Chttps%3A%2F%2Fupdate.greasyfork.org%2Fscripts%2F18450%2FSteam%253A%2520Bypass%2520age%2520confirmation%2520prompts.user.js&win.wfp=true&stealth.enabled=true&stealth.hide_search_queries=true&stealth.DNT=true&stealth.x_client=true&stealth.disable_third_party_cache=false&stealth.webrtc=false&stealth.push=true&stealth.location=true&stealth.disable_windows_telemetry=true&stealth.turn_off_advertising_id=true&stealth.disable_windows_defender=true&stealth.disable_wap_push_message_routing_service=true&stealth.dpi=true&stealth.strip_url=true&stealth.block_third_party_auth=false&stealth.third_party_cookies=180&stealth.block_trackers=true&stealth.ip=&stealth.flash=true&stealth.java=false&dns.enabled=true&dns.timeout=5000&dns.fallback_mode=System&dns.custom_fallback=&dns.custom_bootstrap=&dns.servers=https%3A%2F%2Fd.adguard-dns.com%2Fdns-query%2F319fd726%2Ctls%3A%2F%2F319fd726.d.adguard-dns.com%2Cquic%3A%2F%2F319fd726.d.adguard-dns.com&dns.filters_enabled=true&dns.filters=https%3A%2F%2Ffilters.adtidy.org%2Fwindows%2Ffilters%2F15.txt%2CUser%20rules&parental_control.enabled=false&browsing_security.enabled=false&system_version=Microsoft%20Windows%20NT%2010.0.22631.0

results in a clouflare error:

Web server is returning an unknown error Error code 520
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=link.adtidy.org) for more information.
2024-07-12 03:55:21 UTC

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Please file an issue [here](https://github.com/AdguardTeam/ReportsWebApp/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen) if you still have this.

**Comment by Bluscream** [comment]
https://github.com/AdguardTeam/ReportsWebApp/issues/365
