### ISSUE TITLE
Scams hosted on IP 185.149.120.173

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#183432]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

many sites

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Other Annoyances filter

### Security

Online Malicious URL Blocklist

### Add your comment and screenshots

Many scam sites are hosted on ip `185.149.120.173`. They all look the same. All of them offer a zip file for download which is downloaded from Discord servers.

These are some of sites: dreamzwedding.com, yulyanavalnaya.com, parkmanautomotive.com, plastercraftacademy.com.

Here's the full list of them: https://viewdns.info/reverseip/?host=dreamzwedding.com&t=1

Some are blocked by Google Safe Browsing, some show 404 not found error and some look like the 4 sites I mentioned before.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@andris86 Please provide actual working sites on this IP

**Comment by Alex-302** [comment]
@andris86 

> dreamzwedding.com, yulyanavalnaya.com, parkmanautomotive.com, plastercraftacademy.com.

Thanks, this is enough. Just want to check what exactly hosted here.
