### ISSUE TITLE
animevietsub.app

### ISSUE THREAD

**Issue by animevsubtv** [AdguardTeam/AdguardFilters#183550]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard Content Blocker, AdGuard for iOS, AdGuard for Mac, AdGuard for Safari

### AdGuard version

4.3.53

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, Chrome, Safari, Microsoft Edge, Opera, Yandex Browser

### Which device do you use?

Desktop

### Where is the problem encountered?

https://animevietsub.app/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>
Dear AdGuard Support Team,

I am writing to bring to your attention an issue that is affecting the functionality of my website, animevietsub.. It appears that the filter ||lh.googleusercontent.com^$domain=animevietsub.* in your system is blocking video playback on my site, making it impossible for users to view content.

This filter is causing significant disruption to my users' experience and affecting the overall functionality of the website. I kindly request that you review and remove this filter to restore normal operation for our visitors.

Thank you for your prompt attention to this matter.
2. Screenshots
<details><summary>Screenshot 1:</summary>

![450963022_503626458996821_646246004823127039_n](https://github.com/user-attachments/assets/bc1530c2-cb77-4888-bda4-46877560037e)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Update available in about 3-4 hours.
@zloyden I see you wanted to block some ad pictures which are hosted there. But also valid pictures and more important, videos requests are stored there too.

**Comment by zloyden** [comment]
@BlazDT yep, there were some ad pictures. Thanks for removing it.
