### ISSUE TITLE
Why emathhelp.net is blocked?

### ISSUE THREAD

**Issue by proy87** [AdguardTeam/AdguardFilters#18365]
This is educational site, not advertising.

**Comment by BlazDT** [comment]
Not blocked here.

**Comment by proy87** [comment]
Line 207 at https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/antiadblock.txt

Formulas (mathjax) are blocked on the site when adblock is enabled.
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' * 'unsafe-inline'".

https://www.emathhelp.net/calculators/calculus-1/derivative-calculator/

**Comment by BlazDT** [comment]
That specific rule is to combat ads/adblock. That error is not shown when I try in console log.
Please post required information as outlined in the form.

**Comment by proy87** [comment]
Did you see any errors in console?
Did you enable adblock when you visit the page?

**Comment by BlazDT** [comment]
Only the usual blocked ad urls. Please provide required information as outlined in form.

**Comment by proy87** [comment]
In what form?

**Comment by BlazDT** [comment]
The one you got when opening the issue. https://github.com/AdguardTeam/AdguardFilters/blob/master/issue_template.md

**Comment by proy87** [comment]
OK. Thank you.

**Comment by BlazDT** [comment]
You should have mentioned you are using Chrome Extension, was testing on iOS and full app all the time.
Update will be available in 2-3 hours.

**Comment by BlazDT** [comment]
Can't reproduce the error on Extension in console anymore.
Please check @AdamWr

**Comment by AdamWr** [comment]
It works fine on my end.
By the way, did you update filter lists?
If no, could you please open AdGuard settings, click on "Check for filter updates" and check again?

**Comment by proy87** [comment]
Still formulas are blocked in Chrome.

**Comment by AdamWr** [comment]
Do you mean this?
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/41612550-8da3456a-73f3-11e8-8f59-099189e88dfa.png)

</details>
<br>

If no, please provide a linkt to broken page and make screenshot with broken element.
Did you update filter lists manually?

**Comment by proy87** [comment]
I mean this

![e1](https://user-images.githubusercontent.com/8571708/41613301-dfa4a78c-73fd-11e8-93e7-2c248df8ae36.png)

What filter lists are you talking about? Formulas are blocked for ALL users that have adblock turned on.
It blocks not only formulas but all javascript.

I doubt that every user will update filter lists.
I have complaints that formulas are not rendered correctly.

**Comment by AdamWr** [comment]
>What filter lists are you talking about?

I mean these filter lists:
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/41613647-79b21038-73f6-11e8-9dae-81082517594a.png)

</details>
<br>

>Formulas are blocked for ALL users that have adblock turned on.
It blocks not only formulas but all javascript.

It works fine on my end, you can see it on my screenshot in my previous post.

>I doubt that every user will update filter lists.

If I'm not wrong in AdGuard filter lists are updated automatically every 48 hours, so you will need to wait or update them manually.

By the way, on your screenshot I see that you are using Adblock Plus, we can't fix it for Adblock Plus, but you can report it here - https://github.com/easylist/easylist/issues or here - https://forums.lanik.us/viewforum.php?f=64
or you can add this rule to user filter (it should works with Adblock Plus too):
`@@||emathhelp.net^$csp=script-src 'self' * 'unsafe-inline'`

**Comment by proy87** [comment]
OK. Thank you.
