### ISSUE TITLE
toyokeizai.net

### ISSUE THREAD

**Issue by curlingchimpanzeeowl** [AdguardTeam/AdguardFilters#183610]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.58.0

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://toyokeizai.net/articles/-/406082

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Japanese filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

1. Website displays anti-adblock popup.
You can avoid this anti-adblock by applying the following custom filter.
```
toyokeizai.net##.pi_content
toyokeizai.net##.pi_modalbg
```

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot from 2024-07-14 22-19-48](https://github.com/user-attachments/assets/e0698e7f-d0ef-45e8-8f85-855a31bb3886)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@curlingchimpanzeeowl I can't reproduce it with your settings.
