### ISSUE TITLE
Shopify analytics

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#183862]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

latest

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

Many shopify sites

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Other Annoyances filter

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Ukrainian filter

### Add your comment and screenshots

Some Shopify sites load analytics script which has the same path in all Shopify sites, domain name is THE ONLY PART that's changing. 

The path is `/cdn/shopifycloud/media-analytics/v0.1/analytics.js`.  I first encountered this file in ridge.com (now redirects me to https://ridgewallet.eu/), today I have encountered it in https://lumenofficial.com/.

The best rule for this is: `/cdn/shopifycloud/media-analytics`

Also there are some web pixel scripts. I have found them on many sites:

- https://mythical.com/
- https://ridgewallet.eu/
- https://lumenofficial.com/
- https://getw.com/
- https://www.shanedawsonmerch.com/
- https://cloakbrand.com/

![Screenshot 2024-07-17 181348](https://github.com/user-attachments/assets/2b66863e-c4d9-4b8b-80a5-e940f1c7aef3)

The best rule to deal with them would be: `/wpm@*/web-pixel`

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Dangerous. We already block requests from this script.
