### ISSUE TITLE
play.dictionary.com

### ISSUE THREAD

**Issue by Linisdjxm** [AdguardTeam/AdguardFilters#183837]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

None

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://play.dictionary.com/games/todays-hurdle

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Other Annoyances filter, Fanboy's Annoyances

### Language-specific

AdGuard Chinese filter

### Add your comment and screenshots

See uBlockOrigin/uAssets/issues/24514.

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Not reproduced with AdGuard filters. Please check the site without third-party ones.

**Comment by Linisdjxm** [comment]
@zloyden  https://filters.adtidy.org/extension/ublock/filters/2_without_easylist.txt ,

`||ams.cdn.arkadiumhosted.com/advertisement/` is causing the problem.

**Comment by zloyden** [comment]
How to reproduce it? The game is fine with the rule on my end. You can try this rule.
```adblock
||ams.cdn.arkadiumhosted.com/advertisement/$badfilter
```

**Comment by zloyden** [comment]
@AdguardTeam/filters-maintainers please also take a look at this.

**Comment by Alex-302** [comment]
Also not reproduced.
