### ISSUE TITLE
xhamster 

### ISSUE THREAD

**Issue by Leah96xxx** [AdguardTeam/AdguardFilters#183968]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

AdGuard - Ads list in uBlock Origin (freshly updated)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Opera

### Which device do you use?

Desktop

### Where is the problem encountered?

https://xhamster.com

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. The AdGuard - Ads filter list in uBlock Origin prevents xhamster.com from loading, getting it stuck in a refresh loop. If have found that the following filter is causing the issue:
`xhamster.com##+js(set-cookie-reload, ts_popunder, 1)`
I have reset UBO to default settings (disabling the AdGuard list) and confirmed it works. I can also confirm that the issue does still exist with other extensions and my browser's built-in adblocker disabled. Using uBlock's logger, I was able find the above rule by individually bypassing each filtered element that was logged.
Initially during testing, I was able to resolve the issue by bypassing this filter, which is from uBlock's default ad list: `xhamster.*##+js(set-cookie, ts_popunder, true, , reload, 1)`, however I ruled this one out since the site works OK when uBlock is only running on defaults. This is what led me to then find the rule I mentioned at the top of this comment, as it is the only other one that references cookie `ts_popunder`
I have also confirmed that the issue persists when uBlock is running defaults with the AdGuard - Ads list enabled, and that the issue does not exist when other non-default lists and custom filters are enabled without the AdGuard list.

2. Screenshots
<details><summary>Screenshot 1 - Rule causing the issue, logged in uBlock Origin:</summary>

![image](https://github.com/user-attachments/assets/08497978-df20-4235-9672-23f8189c8a80)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
I don't know why uBO sets `true`, instead of `1`. Will disable our rule for uBO.
