### ISSUE TITLE
https://filters.adtidy.org/extension/ublock/filters/3.txt is blocking static.klaviyo.com/onsite/js/klaviyo.js

### ISSUE THREAD

**Issue by chas-klaviyo** [AdguardTeam/AdguardFilters#183967]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

ublock origin 1.58

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

Everywhere

### Ad Blocking

EasyList

### Add your comment and screenshots

1. Our customers have written in that our embedded forms are not showing up on their websites when adguard lists are used (for example in ublock origin). Many of them build sites around these embedded forms.

Since `||static.klaviyo.com/onsite/js/klaviyo.js` has been added to https://filters.adtidy.org/extension/ublock/filters/3.txt our sign up forms are no longer showing up when this filter is enabled.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Where exactly?

**Comment by Alex-302** [comment]
There are no complaints from site visitors. Apparently they are not inconvenienced by it.
