### ISSUE TITLE
impuls.cz

### ISSUE THREAD

**Issue by wowfilip999** [AdguardTeam/AdguardFilters#184011]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.58.0

### What type of problem have you encountered?

Missed ads or ad leftovers czech and slovak https://github.com/tomasko126/easylistczechandslovak is almost not active not patching issues will be good if adguard make fork 

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.impuls.cz/

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

EasyPrivacy

### Annoyances

EasyList Cookie List

### Language-specific

EasyList Czech and Slovak

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

1. <comment>

</details>
ad banner remains on page
<details><summary>Screenshot N:</summary>

![obrazek](https://github.com/user-attachments/assets/27d1346a-194e-41bb-9f2c-dd13c7c15084)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I've seen only leftovers there, that was fixed. Update in the filters should be available soon.
