### ISSUE TITLE
www.tsbohemia.cz

### ISSUE THREAD

**Issue by wowfilip999** [AdguardTeam/AdguardFilters#184103]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] Browser version is up-to-date;

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.58.0

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.tsbohemia.cz

### Ad Blocking

EasyList

### Language-specific

EasyList Czech and Slovak

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

<comment>
https://github.com/tomasko126/easylistczechandslovak last commit in month (czech / slovak specific filters) unactive i will be happy if be fixed 
  here is ad for product on this page and self promo without the banners but the page looks better 
   here me settings what i find work myself:
 ||link.tsbohemia.cz/$image (disable promo to products on they own web)
 ||www.tsbohemia.cz/inc/hp-html/img/akce_hp.jpg$image (selfpromo)
if i find something more i will send
 Screenshots
<details><summary>Screenshot 1:</summary>

![obrazek](https://github.com/user-attachments/assets/54293ff4-bcac-4f31-95ad-5c60f58aef80)
</details>

<details><summary>Screenshot 2:</summary>

![obrazek](https://github.com/user-attachments/assets/6cb79c78-10d4-403d-9535-d0f69c60c3b2)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi
For user filter:
```
||tsbohemia.cz/inc/hp-html/img/akce_hp.jpg
tsbohemia.cz##.jcarousel-container
```

Promos may be useful on such sites.
