### ISSUE TITLE
Wildcard block should not be placed on Cloudflare R2 domain

### ISSUE THREAD

**Issue by cicku** [AdguardTeam/AdguardFilters#184379]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://pub-*.r2.dev

### Ad Blocking

AdGuard Base filter

### Language-specific

AdGuard Japanese filter

### Add your comment and screenshots

Cloudflare Public R2.dev Bucket URL should not be blocked. Unless there is any specific domain, you should not block with a wildcard.

- https://github.com/AdguardTeam/AdguardFilters/blob/master/JapaneseFilter/sections/general_url.txt#L97

Please remove this entry. Any issues with Cloudflare, should be reported to https://abuse.cloudflare.com/.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
What exactly is broken by this rule, used in ad blockers? Need a real case.

CC: @Yuki2718

**Comment by Yuki2718** [comment]
As commented, provide **real case** that we can check and compare the risk and the benefit.

**Comment by elithrar** [comment]
Hi folks — I work at Cloudflare and want to add some context here.

Blocking `https://pub-*.r2.dev` is equivalent to blocking `*.s3.amazonaws.com`, `*.storage.googleapis.com` or `storage.googleapis.com/*` — this is a shared domain with per-customer subdomains, identical to how AWS and Google Cloud provide public bucket URLs for their object storage.

As it stands, the rule blocks any site attempting to serve any content from their storage bucket — JS, CSS, HTML, images, video files, file downloads — directly.

You are welcome to block _specific_ buckets — e.g. `pub-12345abcdef.r2.dev` that don't match your content rules, but blocking the entire subdomain (`pub-*`) blocks every single public bucket past and future.

**Comment by cicku** [comment]
> What exactly is broken by this rule, used in ad blockers? Need a real case. 

Everytime I create a bucket in my Cloudflare account and try to visit the URL, the page gets instantly blocked by adguard, this already indicates a very inconvenient environment for testing because I need to share this URL with others but want to know how the page looks like. To help you better understand, this is the source of the URL at Cloudflare:

![image](https://github.com/user-attachments/assets/0015315c-a66c-48bf-b391-164ab5b9b734)

> That service is used in Japan for illegal purposes

I cannot really give you an answer of why R2 is often used for illegal purposes in Japan, but I think being as an ad filter, you should not block domains on behalf of the law enforcement, since I use the filter in the Canada for hosting my pictures.

> and domains are frequently changed (maybe CF blocks it sometimes).

Yes, the URL is unique to a bucket, I have created 6 buckets in my account, each of them has a different id in the URL. If someone wants to dodge the ban, they can recreate a bucket so the URL will change, but it also blocks legitimate users.

---

My real case is that I do not want to bind a [custom domain](https://developers.cloudflare.com/r2/buckets/public-buckets/#custom-domains) to the R2 bucket, so I need to use this URL for file sharing. It is just a legitimate use case. 

I appreciate the response from @elithrar, this is exactly what I am doing, and likely many others doing when they do not own any domain.

**Comment by Yuki2718** [comment]
Okay, thank you for clarification. It seems now criminals no longer actively use them: https://urlscan.io/search/#hash%3A2f1e4e12cad95a5be818ecc2731ba22789c698fb01e3c24fd4cd02233db7866f So I'll disable the rule, but seriously hope CF to take acition for these massive fraud campaigns.
