### ISSUE TITLE
Trackers added to EasyPrivacy not present in AdGuard Tracking Protection filter

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#184584]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.3.53

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

Multiple websites

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, Legitimate URL Shortener, Fanboy's Anti-Facebook List

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Hide Referrer from third-parties (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests

### Add your comment and screenshots

Here are some trackers which were added to EasyPrivacy recently but not present in AdGuard Tracking at the moment.

```
||mantrafox.com^
Source: https://www.rollingstone.com/

||count.darkreader.app^
Source: https://darkreader.org/

||stytch.com/sdk/v1/events
||telemetry.stytch.com^
||unifyintent.com/analytics/
Source: https://stytch.com/

||desmos.com/analytics/js/
Source: https://www.desmos.com/

||hdnux.com/HNP/stats/page_view?
Source: https://www.sfgate.com/

||apple-mapkit.com/mw/v1/reportAnalytics
||xp-qa.apple.com/report/2/xp_amp_web_error_log
||xp-qa.apple.com/report/2/xp_amp_web_perf_log
Source: https://beta.maps.apple.com/

||stonechin.com^
Source: https://variety.com/

||forevergears.com^
Source: https://stylecaster.com/

||ultravalid.com^
Source: https://dailyvoice.com/

||wiredforcoffee.com^
Source: https://www.nsnews.com/

||drogasil.com.br/$third-party
```

### Privacy

- [X] I agree to follow this condition

**Comment by SeriousHoax** [comment]
> Just enable that filter. Our filter is not a fork, we have different rules.

I see. I thought that if EasyPrivacy considered them tracking then AdGuard will too and probably just hasn't discovered them yet.
Anyway, no problem.

**Comment by Alex-302** [comment]
@SeriousHoax Admiral domains are dual purpose - we block them in Popups filter.

**Comment by Alex-302** [comment]
Added some rules.
