### ISSUE TITLE
185.149.120.173

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#184671]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard DNS

### AdGuard version

latest

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

multiple sites

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

Related to https://github.com/AdguardTeam/AdguardFilters/issues/183432

I use Adguard public DNS set in my devices settings. I don't use the private DNS.

I am wondering if this scam IP (`185.149.120.173)` and other malicious IP's can be blocked in Adguard DNS so websites from this IP cannot be accessible on device where Adguard DNS is installed.

Users who use only Adguard browser extension are still at risk because it does not support `$network` modifier and DNS level blocking seems a good choice.

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
https://bgp.he.net/ip/185.149.120.173#_dnsrecords definitely attests to a need to block the IP address for sure.

**Comment by Alex-302** [comment]
This rule did not make it into the DNS filter. We'll look into it.
Antiphishing does not support block sites by IP.

**Comment by Alex-302** [comment]
🐛 https://github.com/AdguardTeam/HostlistCompiler/issues/69
