### ISSUE TITLE
Cleanup dead sites in MobileFilter (specific_web.txt)

### ISSUE THREAD

**Issue by SKEIDs** [AdguardTeam/AdguardFilters#184870]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

The following domains are inaccessible, sold, return a 403 error, or redirect to other domains.
I accessed these domains in the browser and checked their availability on urlscan.io. 
However, I don't think it is perfect.

- [x] 3rxing.org
This site can’t be reached
- [x] afumi-stage.jp
	403 error
- [x] anime.anidub.life
This site can’t be reached
- [x] animeplus.tv
This site can’t be reached
- [x] animetoon.org
domain for sale
- [x] apk-live.com
404 error
- [x] asbook.net
This site can’t be reached
- [x] bash.im
This site can’t be reached
- [ ] delivery.rakuten.co.jp
This site can’t be reached
- [x] dlbooks.to
This site can’t be reached
- [x] dm88.me
This site can’t be reached
- [x] doctorslounge.com
This site can’t be reached
- [x] dougle.one
This site can’t be reached
- [x] ero-mag.site
There is nothing on this website.
- [x] eromanga-numa.com
This site can’t be reached
- [x] eromanga-yoru.com
This domain redirects to other website
- [x] etotop.cc
This site can’t be reached
- [x] ff4psp.jp
This site can’t be reached
- [ ] ficbook.com
This site can’t be reached
- [x] fourth-sphere-302420.appspot.com
404 error
- [x] fzdm.com
This site can’t be reached
- [ ] game.asahi.com
This site can’t be reached
- [x] game4v.com
This site can’t be reached
- [x] ganmodoki.net
This site can’t be reached
- [x] goblintvfree.com
This site can’t be reached
- [x] goodporn.to
This site can’t be reached
- [x] heiye.cc
This site can’t be reached
- [ ] hikkoshi-line.com
This site can’t be reached
- [x] javsubtitle.co
Access blocked by Adguard
- [x] kissanime.mobi
There is nothing on this website.
- [x] lasela.jp
404 error
- [x] loveha.net
This site can’t be reached
- [ ] manganelo.com
This site is closed
- [ ] mangapanda.com
This site can’t be reached
- [ ] mangareader.net
This site can’t be reached
- [ ] mangastream.com
This domain is expired
- [ ] mangastream.com
This site can’t be reached
- [ ] mediazona.online
404 Not Found
- [ ] meduza.global.ssl.fastly.net
This site can’t be reached
- [ ] memecenter.com
This site can’t be reached
- [ ] mess-y.com
This site can’t be reached
- [ ] metruyenchu.com
404 error
- [ ] milliyetemlak.com
This site can’t be reached
- [ ] mkan.eastday.com
This site can’t be reached
- [ ] news-select.net
This site can’t be reached
- [ ] nfmovies.com
There is nothing on this website
- [ ] nfydd.com
This site can’t be reached
- [ ] novelplanet.com
There is nothing on this website
- [ ] nyaasokuvip.net
maintenance forever
- [ ] ok-tv.org
There is nothing on this website
- [ ] olive-hitomawashi.com
404 Not Found
- [ ] oshto.kg
This site can’t be reached
- [ ] p4svip.com
This site can’t be reached
- [ ] pornodiamant.com
This site can’t be reached
- [ ] pornovsem.net
This site can’t be reached
- [ ] readlightnovel.org
This site can’t be reached
- [ ] russkie-seriali.online
This site can’t be reached
- [ ] s.ekiten.jp
This site can’t be reached
- [ ] sefon.pro
403 error
- [ ] seikantai.er0.buzz
This site can’t be reached
- [ ] sexkvartal.net
domain for sale
- [ ] st12.jp
This site can’t be reached
- [ ] titsbox.com
This site can’t be reached
- [ ] toonova.net
This site can’t be reached
- [ ] toonsarang.buzz
There is nothing on this website
- [ ] truyenqqpro.com
This site can’t be reached
- [ ] usatooday.com
There is nothing on this website
- [ ] vivud.com
This site can’t be reached
- [x] vtuber-matome.com
This site can’t be reached
- [ ] wealthadvisor.co.jp
403 error
- [x] fengfuyi.com
This site can’t be reached
- [x] youflix.is
This site can’t be reached
- [ ] xs010696.xsrv.jp
403 error
- [x] xxxfiles.tv
This site can’t be reached
- [x] yasehub.com
This site can’t be reached
- [x] yingshidaquan.cc
This site can’t be reached

### Proposed solution

For cosmetic rules, it's possible to delete the rule. For basic rules, I am not certain.

### Additional information

On some websites, there was a notice indicating that they are currently under maintenance.
However, given that the dates mentioned do not match the present, it's possible these sites have been left in maintenance mode.
Please feel free to disregard everything except for the domains that are definitively unnecessary. 
I will also remove any uncertain domains from the list on my end.

**Comment by Yuki2718** [comment]
Don't close issues while someone is addressing.

**Comment by Alex-302** [comment]
403 is not equal to dead. sefon.pro and xs010696.xsrv.jp are working

**Comment by Yuki2718** [comment]
`olive-hitomawashi.com` is living, wrong deleteion

**Comment by Yuki2718** [comment]
`xs010696.xsrv.jp` will be fine to remove though is not literally dead.
