### ISSUE TITLE
my.pltw.org

### ISSUE THREAD

**Issue by Jap2-0** [AdguardTeam/AdguardFilters#184980]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.58.1rc11

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://my.pltw.org/

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, EasyList Cookie List

### Security

Online Malicious URL Blocklist

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

This displays a completely white page if AdGuard Tracking Protection is enabled, due to the `||cdn.pubnub.com^` filter.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Does this rule fix the problem?
`@@||cdn.pubnub.com/pubnub-3.14.5.min.js$domain=my.pltw.org`
I can't register. Login page is not broken.

**Comment by Jap2-0** [comment]
@Alex-302 Yes, I con confirm that rule fixes it.

**Comment by Alex-302** [comment]
Added.
