### ISSUE TITLE
outlook mail wont load with base filter

### ISSUE THREAD

**Issue by GitCartel** [AdguardTeam/AdguardFilters#18494]
outlook mail wont load with base filter

inbox wont load emails

https://i.imgur.com/01idIGg.jpg
https://i.imgur.com/AfsHhqW.jpg

W7 x64, Basilisk 64, noscript, UBO

**Comment by BlazDT** [comment]
Not reproduced. Please check @AdamWr

**Comment by AdamWr** [comment]
I can't reproduce it.
<details><summary>Screenshot</summary>

![outlook](https://user-images.githubusercontent.com/29142494/41658765-ba24f12a-7497-11e8-84f0-09ab6f66b4fa.png)

</details>
<br>

You can check this rule, maybe it will help:
```
outlook.live.com#@#.scrollContainer > div[class][style^="height:"] div[style*="height:"]:not([style*="auto"]):not([id]):not([class])
```

**Comment by Alex-302** [comment]
@GitCartel please leave Base Filter only, open filtering log and reproduce the issue. Make screenshot of the log after that.

**Comment by GitCartel** [comment]
![2017113](https://user-images.githubusercontent.com/30365972/41670421-ca4a7186-74a3-11e8-9ea9-cf45d5c52491.jpg)
![2017114](https://user-images.githubusercontent.com/30365972/41670423-ca6968d4-74a3-11e8-9f3e-0df9f9cb46cb.jpg)


Only difference I see is that static filter.

**Comment by GitCartel** [comment]
I notice this "collector" is making my whole browser slow. Its not giving up.
Its like I'm ddos'd for blocking it.

![2017115](https://user-images.githubusercontent.com/30365972/41670898-1761acfe-74a5-11e8-8e84-dac6748401f2.jpg)

**Comment by Alex-302** [comment]
Not reproduced with AdGuard, the site works fine. You can exclude this rule if you want.

**Comment by Alex-302** [comment]
Excluded this rule for uBO.

**Comment by GitCartel** [comment]
Thank you for all your help!
