### ISSUE TITLE
Tiktok

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#185072]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

Tracker: rtlog16-normal-useast5.tiktokv.us

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
engagements.appsflyer.com
s2s.adjust.com

here is two more that appeared. @Alex-302

**Comment by Alex-302** [comment]
Ok

**Comment by jordanswrld94** [comment]
here is two more i found:

proxy.telemetry.us-ashburn-1.oci.oraclecloud.com
sf16-telemetry-proxy-oci.tiktokcdn-us.com

@Alex-302

**Comment by Alex-302** [comment]
Done.

**Comment by Alex-302** [comment]
Thanks, added.
