### ISSUE TITLE
titsbox.com [NSFW] [Ad]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#18503]
**Site**: http://titsbox.com/video/pNWweqqN/?sid=12111

**Issue**: Please remove the ad on the video player and also the bottom ad bar.
 
**Screenshot**: http://prntscr.com/jx0bcv

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 67.0.3396.87 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
Hi blaz, I am now seeing ad text string when opening from Android. Can you add the relevant filter for that pls. Thanks.

**Comment by BlazDT** [comment]
Fixed.
