### ISSUE TITLE
17track app

### ISSUE THREAD

**Issue by panchaln-git** [AdguardTeam/AdguardFilters#185120]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

 AdGuard for Android 4.6.1

### Environment

- OS version: 14
- Device: Samsung S24 Ultra

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist

### Language-specific

IndianList

### Other

Filter unblocking search ads and self-promotion, AdGuard DNS filter, AdGuard Experimental filter

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

Regular

### Issue Details

Steps to reproduce:
1. tiktok ad banners are showing up on 17Track application
2.
3.

### Expected Behavior

If the app traffic is routed through Adguard, ad banners should not be shown on that app

### Actual Behavior

tiktok ad banner shows up in the app

### Screenshots

<details><summary>Screenshot 1</summary>

![image](https://github.com/user-attachments/assets/84c95c0b-72a5-4d03-b523-8f510124d2c9)

</details>

**Comment by Alex-302** [comment]
@Versty I can't reproduce. https://github.com/AdguardTeam/AdguardFilters/issues/184507#issuecomment-2250396895

Please ask for the filtering log screenshots, when used only dns filtering.

**Comment by Versty** [comment]
@panchaln-git Can't reproduce this ad on our side, therefore we would like you to help us. 
1. Please disable all protection modules except for DNS Protection
2. Select DNS server: `AdGuard DNS Non-filtering` or `Google DNS`
3. Make sure that the `AdGuard DNS Filter` is enabled 
*Protection tab -> DNS Protection -> DNS filters*
2. Close all apps except for AdGuard
3. Clear recent activity log 
  *Statistics tab -> Recent activity -> context menu -> Clear recent activity* 
4. Launch the 17track app and open the screen where the ad is observed 
5. Return to AdGuard -> Statistics tab -> Recent activity 
6. Provide the screenshots of Recent activity log here

**Comment by panchaln-git** [comment]
![Screenshot_20240731_114603_AdGuard](https://github.com/user-attachments/assets/0715a553-e49c-420a-a2d2-5dba39fbb202)

**Comment by Alex-302** [comment]
@panchaln-git As I see, google ads are blocked. Please press on `I` icon on the banner and show the ad info.

**Comment by panchaln-git** [comment]
@Alex-302 , pressing on i icon doesn't do anything actually. But when I double click on the ad itself, it opens a webpage which doesn't load either.
![Screenshot_20240807_193722_Samsung Internet](https://github.com/user-attachments/assets/65a83d84-c5b7-4dc0-8e19-a84ced2a2904)

**Comment by Alex-302** [comment]
@panchaln-git On your screenshot I see applied DNS filtering. In this case Google Ads must be blocked.
I think they just use custom image, hosted on the main server, but used google ads link for click action.

Do you see same image(s) after restart the app?

**Comment by panchaln-git** [comment]
@Alex-302 it's not exactly same image but similar every time. Not sure how TikTok banners are coming through in some apps, this is one app, there is one more, SlickDeals, there also TikTok, hungama, those banners show up.

**Comment by Alex-302** [comment]
> SlickDeals

Full screen ad when you launch the app?

**Comment by Alex-302** [comment]
> So can it cause such ad banners in some apps?

Indeed. Apps can load ads through Google Services.

**Comment by panchaln-git** [comment]
> > So can it cause such ad banners in some apps?
> 
> Indeed. Apps can load ads through Google Services.

So is there any way around this? because if I route my Google and Google Play Services traffic through AdGuard, then 8/10 voice commands for android auto in my car fails with error 'Something went wrong with the connection', so I have to keep these out of AdGuard routing. Is there any way to conditionally route traffic through Adguard?

**Comment by Alex-302** [comment]
Without the filtering log I can't exactly tell you the reason why you're seeing ads.

Please enable debug logging, close AdGuard and this app, and clear cache. Then start AdGuard, turn on protection, start this app and reproduce the problem. After that, turn off protection and export logs, and sent to me to Telegram https://t.me/Alex302_AdGuard

>  Is there any way to conditionally route traffic through Adguard?

not sure. If you have problems with car when used AdGuard, please write to
https://github.com/AdguardTeam/AdguardForAndroid
