### ISSUE TITLE
[popup] lqrlhmdwy.com

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdguardFilters#18537]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
Observed here: http://www.russiacup2018.stream/stream-1.php  
* **Current behaviour**: 
Clicking play will activate popup which adguard popup blocker will stop,but blocking the domain 
( **||lqrlhmdwy.com^$third-party** ) will not even activate the blocker.I think the rule should 
be added.Thank you.

**Comment by BlazDT** [comment]
Not reproduced, please list your filters.

**Comment by dnmTX** [comment]
AdGuard Base Filter
AdGuard Spyware Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
Fanboy's Annoyances
EasyPrivacy
Malware Domains
Spam404

I couldn't find the domain i listed in any of those.

**Comment by dnmTX** [comment]
UPDATE: Ok,i just updated the filters and it was added to the Base Filter(my last update was 7 hrs. ago).You guys are fast.Closing this,issue has been resolved.Thank you.

**Comment by BlazDT** [comment]
You are welcome, though the update is from EasyList on which our filters are based. Strange that request wasn't even showing for me.
