### ISSUE TITLE
nnm-club.me & nnmclub.to

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1853]
http://www.nnm-club.me
http://nnmclub.to/

http://prntscr.com/ajv0kn
http://pasteboard.co/2xbJnqJU.png

JOZ-924-48147

**Comment by Vincent-Michael** [comment]
http://forum.adguard.com/showthread.php?9863-*-http-nnmclub-to&p=80083&viewfull=1#post80083

**Comment by vozersky** [comment]
@Alex-302 надо наверное перенести в annoyances из экспериментального, а то пишут что не блокируется.

**Comment by Alex-302** [comment]
Фильтр раздражителей и ЭФ сейчас идентичны.
У юзера ни ЭФ ни фильтр раздражителей не включен. Загляните в state.txt

**Comment by vozersky** [comment]
@Alex-302 
не понял сейчас про какого ты юзера и какой стэйт говоришь, видимо про другой кейс
но я сам вчера проверил, с хромэкстеншене блочилось только ЭФ  :\

**Comment by Alex-302** [comment]
@vozersky 
про того, который в тикете указан. У меня только раздражители включены, всё блокитруется, т.к. он и эф абсолютно одинаковы(пока)
