### ISSUE TITLE
Cleanup obsolete rules or dead sites in JapaneseFilter (general_extensions.txt)

### ISSUE THREAD

**Issue by SKEIDs** [AdguardTeam/AdguardFilters#185320]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

 

The following domains are inaccessible, sold, return a 403 error, or redirect to other domains.
I accessed these domains in the browser and checked their availability on urlscan.io. 
However, I don't think it is perfect.

- [ ] avgle.com
I can not access
- [ ] b2.sakki2022.com
404 error
- [ ] japaneseasmr.top
dead domain
- [ ] jp-xvideos.info
dead domain
- [ ] kandatasokuho.blog.fc2.com 
redirects to other website 
- [ ] profile.ameba.jp
redirects to other website 

### Proposed solution

For cosmetic rules, it's possible to delete the rule. For basic rules, I am not certain.

### Additional information

Please feel free to disregard everything except for the domains that are definitively unnecessary. 
I will also remove any uncertain domains from the list on my end.

**Comment by Sergey-Lyapin** [comment]
Lets wait a couple of month with avgle.com.
