### ISSUE TITLE
Imgur App Sponsored Ads

### ISSUE THREAD

**Issue by ATalkingBlob** [AdguardTeam/AdguardFilters#185315]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker, AdGuard DNS, AdGuard for Android, AdGuard for Windows

### AdGuard version

7.6.1

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.imgur.mobile

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Fanboy's Enhanced Tracking List, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social Widgets

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, Web Annoyances Ultralist, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Other

Filter unblocking search ads and self-promotion, AdGuard Experimental filter

### DNS filters

AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

![Screenshot_20240802_213227_Imgur](https://github.com/user-attachments/assets/567d6857-0821-443e-bf29-47021d30674a)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by ATalkingBlob** [comment]
This is happening in the imgur app. I have tried googlefu to fix issue to no avail. Before the last update I had no ads on the app at all and now there are full page ads between posts that sometime load and sometimes don't.

**Comment by ATalkingBlob** [comment]
![Screenshot_20240802_213227_Imgur](https://github.com/user-attachments/assets/cb35b98d-bc3b-42b6-b6d1-02a12986168a)

**Comment by Alex-302** [comment]
It cannot be blocked - element of the app or used ad library.
