### ISSUE TITLE
ohou.se

### ISSUE THREAD

**Issue by Decaffeinated-Usagi** [AdguardTeam/AdguardFilters#185452]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

2.7.3

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://ohou.se/

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Add your comment and screenshots

1. When using AdGuard Content Blocker on Samsung Internet, blank screen is encountered on ohou.se. Clicking the button on Screenshot 1 will redirect to a page that will supposedly prompt to open/download app in Google Play Store. With tracking protection filter open, however, it results in a blank screen (Screenshot 2).

2. Screenshots
<details><summary>Screenshot 1:</summary>

**![website](https://github.com/user-attachments/assets/f37d6e59-59e1-4fe4-af66-801a342f6d49)**

</details>

<details><summary>Screenshot 2:</summary>

![blankscreen](https://github.com/user-attachments/assets/22f01e70-3406-410b-930f-1642f1bf567b)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@Decaffeinated-Usagi Hi. Cannot reproduce. Do you use only Base filter?

Also I have another question - do you know about `AdGuard for Android`, or do you just prefer `AdGuard Content Blocker` for Samsung Browser?
