### ISSUE TITLE
budgetlightforum.com broken by recent Adguard-Ads update

### ISSUE THREAD

**Issue by valynor** [AdguardTeam/AdguardFilters#185537]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

none, uBlock Origin 1.59.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Brave 1.68.134 Chromium: 127.0.6533.88 (Official Build) (arm64) 

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://budgetlightforum.com/

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Fanboy's Enhanced Tracking List, Fanboy's Anti-Facebook List

### Annoyances

AdGuard Cookie Notices filter, EasyList Cookie List

### Security

Online Malicious URL Blocklist

### DNS filters

AdGuard DNS filter

### Language-specific

EasyList Germany

### Add your comment and screenshots

https://budgetlightforum.com/
fails to load completely (it still worked earlier today), see screenshot from uBO logger: 

![Screenshot 2024-08-05 at 22 28 58](https://github.com/user-attachments/assets/62aea2d1-495c-4730-a210-bc2f904e58f3)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Removed a bad rule. After an hour, you may check for filters update.
