### ISSUE TITLE
douyu

### ISSUE THREAD

**Issue by wolaikk** [AdguardTeam/AdguardFilters#185601]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.18.1

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.douyu.com/g_Mario

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Annoyances filter

### Language-specific

AdGuard Chinese filter

### Add your comment and screenshots

![屏幕截图 2024-08-06 181800](https://github.com/user-attachments/assets/2bb4aeb9-fca0-4d77-8d1a-82a8512d3e73)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please make full screenshots of pages.

**Comment by Alex-302** [comment]
Both slides are ads?

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/3c045fc6-df70-49cd-a26a-23cef5439a77)

![image](https://github.com/user-attachments/assets/ae7dae21-3f70-4e8c-acc8-af5ae453156b)


</details>
