### ISSUE TITLE
Need to remove site from filter as it is legit

### ISSUE THREAD

**Issue by tharun-abishek** [AdguardTeam/AdguardFilters#185777]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

other

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://apptics.zoho.com

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>
<img width="819" alt="image" src="https://github.com/user-attachments/assets/39d5058f-4a57-4f9b-8756-f69a250960af">

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@tharun-abishek  Hello. Could you please clarify a little more information? Based on [this issue](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1327) this domain is tracking. Do you have any functionality breaking?

**Comment by tharun-abishek** [comment]
Yes. Iam unable to access the domain 'https://apptics.zoho.com '. Can you
please remove it from tracking?

**Comment by jellizaveta** [comment]
@tharun-abishek I was just wondering what this is used for? Does it have a legitimate purpose beyond collecting user information?

**Comment by tharun-abishek** [comment]
Zoho Apptics is a legitimate service provided by Zoho Corporation. It is a privacy-by-design application analytics tool that focuses on monitoring app performance, crash reporting, and in-app usage. Importantly, it prioritizes user privacy and data safety, ensuring that no personal user information is collected

As as of now it only tracks mobile data, no web tracking is there! So, I would like to request its removal from the blocklist.

**Comment by jellizaveta** [comment]
Thank you for your patience and help! An update will be available in 1-2 hours.

**Comment by tharun-abishek** [comment]
Any updates?
