### ISSUE TITLE
mirror.co.uk

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#185726]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.mirror.co.uk/tv/tv-news/freddie-flintoff-cried-every-two-33396271

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Annoyances

AdGuard Annoyances filter, Adblock Warning Removal List, Fanboy's Annoyances

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

Cant figure out why video wont play

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld94** [comment]
I have tried disabling non adguard lists and still cant figure it out

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
