### ISSUE TITLE
http://www.forbes.com - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1857]
http://www.forbes.com/sites/jasonevangelho/2016/03/23/all-i-want-from-nintendo-is-a-powerful-console-with-no-gimmicks-and-great-games/#7f943f4a4d6b

![image](https://cloud.githubusercontent.com/assets/15856304/14054634/60b4a03c-f2e3-11e5-90bc-7a6de380b20a.png)

<details>
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.70.27 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.3.63 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.13 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.78 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.28.15 Enabled=NO
ID=6 Name="German filter" Version=1.0.21.56 Enabled=NO
ID=7 Name="Japanese filter" Version=1.0.92.87 Enabled=NO
ID=8 Name="Dutch filter" Version=1.0.8.53 Enabled=NO
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.8 Enabled=NO
ID Name="Turkish filter" Version=1.0.0.28 Enabled=NO
ID Name="Mobile ads filter" Version=1.0.1.37 Enabled=YES
ID Name="Mobile Safari filter" Version=1.0.0.3 Enabled=YES

**Comment by Alex-302** [comment]
Там адский антиблокировщик, в иОС обойти не возможно, т.к. правила JavaScript не поддерживаются.

**Comment by vozersky** [comment]
User states that Purify does block ads on Forbes:
https://itunes.apple.com/en/app/purify-blocker-no-ads.-no/id1030156203?mt=8

Could you please check?

**Comment by Alex-302** [comment]
@vozersky 
I can't buy it

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/14410420/d59c39a4-ff37-11e5-9f54-84f9de48eb01.png)

That's how the site with purify adblocker.

**Comment by vozersky** [comment]
@Alex-302   Alex, forbes thing here

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/14644973/8e132490-065c-11e6-84c6-e789154785bf.png)

Missed ad on page:
http://www.forbes.com/sites/hughmcintyre/2016/04/07/taylor-swifts-apple-music-commercial-spurred-a-431-jump-in-sales-for-drake/#2f9a59372789

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/15114328/1c7a0f14-1602-11e6-8dab-8a882e9ef584.png)

Display ad + catfish ad screenshot. Taken from the following page 

http://www.forbes.com/sites/kellyphillipserb/2016/05/04/taxpayers-across-the-country-reporting-uptick-in-irs-tax-related-scams/#44c19ebc3940
TICKET ID
XKP-352-10605

**Comment by Alex-302** [comment]
I know about it. But their damn ad block detection...

**Comment by Alex-302** [comment]
@evgeniy-ADG 
try this:
- disable Safari filrer
- add these rules:
```
@@||forbes.com^$generichide
@@||tpc.googlesyndication.com/safeframe/1-0-2/html/container.html$domain=forbes.com
@@||securepubads.g.doubleclick.net^$domain=forbes.com
@@||forbesbidder.servedbyopenx.com^$domain=forbes.com
```

**Comment by Alex-302** [comment]
Fixed.

**Comment by Bohdan-SUP** [comment]
LBA-661-60743
![image1](https://cloud.githubusercontent.com/assets/14153331/15880298/868d29ba-2d34-11e6-8f9b-65a44bf5ae81.PNG)

**Comment by Alex-302** [comment]
Can't reproduce. Please check on your side.
User can disable EasyList filter. It is included in our English filter.

**Comment by shaurmanchic** [comment]
User reported that enabling Fanboy's Annoyances filter fixed the issue.

**Comment by Alex-302** [comment]
It is impossible, because element hiding is disabled due anti-adblock script.

**Comment by worldsdream** [comment]
There are no ads on forbes.com on iOS. Are they using the english filter? Let them use that! I was one of the first that reported forbes.com ads and they are all gone.

**Comment by worldsdream** [comment]
There is an add on this page: http://www.forbes.com/sites/katiasavchuk/2016/06/15/happy-family-shazi-visram-women-entrepreneurs/#4dffd9b13930

Can you see it?

**Comment by worldsdream** [comment]
After a refresh, it was gone. Weird!

**Comment by Alex-302** [comment]
>After a refresh, it was gone. Weird!

I don't know why this page is not filtered completely when it visited first time.

**Comment by Alex-302** [comment]
>After a refresh, it was gone. Weird!

I don't know why this page is not filtered completely when it visited first time.
@ameshkov could you comment this?

**Comment by worldsdream** [comment]
Exactly, i just tried it again. First load shows advert and a refresh will hide the advert.

**Comment by Alex-302** [comment]
It is not filters issue. You can open issue in iOS section, with detailed description.
