### ISSUE TITLE
www.abola.pt

### ISSUE THREAD

**Issue by marcogpg** [AdguardTeam/AdguardFilters#185825]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard for iOS

### AdGuard version

4.5.5 iOS version | 4.3.53 Browser extension

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome, Safari

### Which device do you use?

Desktop

### Where is the problem encountered?

www.abola.pt

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. When clicking on a main news image, site gets stuck with a circle and do not go to the news page related with the image:

https://www.abola.pt

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://github.com/user-attachments/assets/2dbd64e1-30ec-4a87-ba86-81df3e94dff2)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
Please enable Spanish/Portuguese filter

**Comment by marcogpg** [comment]
Already tested with and without this filter enabled. Same behaviour

![image](https://github.com/user-attachments/assets/40f38432-08ff-48e8-a3d7-35e0664a3771)
