### ISSUE TITLE
marketingtoolssupportcenter.company.site and marketing-tools-meta.mfb00.click

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#185878]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard DNS

### AdGuard version

latest

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

marketingtoolssupportcenter.company.site, marketing-tools-meta.mfb00.click

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

`marketingtoolssupportcenter.company.site`  is a phishing site. There is only one button in this website and when it is clicked, a new website opens - `marketing-tools-meta.mfb00.click` with Facebook style.

After continue button is, it asks to input personal info.

<details>
<summary>Source</summary>
https://www.reddit.com/r/facebook/comments/1enu7gy/comment_on_my_page_saying_that_the_picturelogo_im/
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Thanks, done.

**Comment by Alex-302** [comment]
Blocked also naruto.vlhentaiz.com They sent "incorrect password" there.
