### ISSUE TITLE
Chime

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#186074]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.onedebit.chime

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

event-router.chime.com

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Hello! I'm not quite sure about this domain because it's a banking app. Have you checked the domain blocking on your device?

**Comment by jordanswrld94** [comment]
Seems fine with it blocked. Event router domains seems to be like event logging.

**Comment by jordanswrld94** [comment]
Example: ||event-router.olympics.com^

**Comment by jellizaveta** [comment]
Thanks for the reply, added the rule to the filters. If there are any problems with this domain, feel free to mention me.
