### ISSUE TITLE
[iOS] cnews.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1860]
http://www.cnews.ru/news/top/2016-03-25_httpfilearchivecnewsruimgcnews20160325tor100
![image1](https://cloud.githubusercontent.com/assets/14153331/14060477/cff84400-f36d-11e5-9d7a-19ce3feaffde.PNG)
Logs - ZWC-497-98469

**Comment by Alex-302** [comment]
Не повторилось. Пусть попробует выключить RU AdList
