### ISSUE TITLE
Huawei Health fails to sync data because AdGuard Tracking Protection filter blocking grs.dbankcloud.* URLs

### ISSUE THREAD

**Issue by muchqs** [AdguardTeam/AdguardFilters#186086]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

v4.6.1

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://consumer.huawei.com/en/mobileservices/health/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, Peter Lowe's Blocklist

### Add your comment and screenshots

Android 14.

Huawei Health app fails to sync data due to **`AdGuard Tracking Protection filter`** rule `||grs.dbankcloud.` blocking the following URLs:
`grs.dbankcloud.com`
`grs.dbankcloud.cn`
`grs.dbankcloud.asia`
`grs.dbankcloud.eu`

At least _one_ of these needs to be unblocked for the app to work properly. I unblocked the .com URL and sync immediately started working.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
The rule has been removed from the filters. Update will be available in 1–2 hours.
