### ISSUE TITLE
iptunnels.com

### ISSUE THREAD

**Issue by malikshi** [AdguardTeam/AdguardFilters#186032]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

nightly

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.iptunnels.com

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. <comment>
falsepositive, could you remove it iptunnels site from list https://github.com/AdguardTeam/AdguardFilters/blob/422841fd675b13a838d899d907a934d14ac78530/BaseFilter/sections/content_blocker.txt#L540
2. Screenshots
<details><summary>Screenshot 1:</summary>
![image](https://github.com/user-attachments/assets/a671a47f-eca3-4996-81ac-86df4f002bb5)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@malikshi Hello. Could you please describe the issue in more details? This rule [was added](https://github.com/AdguardTeam/AdguardFilters/issues/59669) for anti-adblock for this site and only applies in AdGuard for Safari and AdGuard Content Blocker on android.
