### ISSUE TITLE
Duplicate rules in ChineseFilter (general_extensions.txt)

### ISSUE THREAD

**Issue by SKEIDs** [AdguardTeam/AdguardFilters#186174]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

There are multiple duplicate rules in the filters.

```
#%#//scriptlet('prevent-window-open')
#$#body { background-image: none !important; }
#$#body { padding-top: 0!important; }
```

```
applefans.today#$#.tipi-overlay { display: none !important; }
applefans.today#$#body { overflow: auto !important; }
```

### Proposed solution

Merge or remove rules if possible.

**Comment by zloyden** [comment]
For the first list of rules, it is better to have them separately in order to keep some rules for one site in one place. We do not consider that as duplicate.

**Comment by zloyden** [comment]
However, the last rules are duplicates. I've removed it.
