### ISSUE TITLE
Zeit.de Cookiebanner annoyance

### ISSUE THREAD

**Issue by palzkillm** [AdguardTeam/AdguardFilters#186225]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.5.5

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.zeit.de/politik/ausland/2024-08/kursk-offensive-militaer-krieg-ukraine-russland

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Language-specific

AdGuard German filter

### Add your comment and screenshots

1. zeit.de still shows Cookie Banner

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Advanced protection is enabled (requires paid license)?

**Comment by palzkillm** [comment]
No advanced protection.

**Comment by BlazDT** [comment]
It is required for more advanced cookies. When not accepting cookies on some sites features like embedded videos, socials etc. not working.
