### ISSUE TITLE
skmedix.pl: conflict with ubo filters

### ISSUE THREAD

**Issue by hugo9655** [AdguardTeam/AdguardFilters#186294]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

n/a

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://skmedix.pl/

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. <comment>
Using uBO default settings+config and enabling "AdGuard - Ads" filter list, it causes an invisible element to appear on skmedix, meaning u cant navigate the site.

Was recommended by a person over at uassets to make an issue here.

Main thread can be found [here](https://github.com/uBlockOrigin/uAssets/issues/24746).

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I've been checking the site for some time and found that Easylist filter breaks it. Will report to its author.

**Comment by ryanbr** [comment]
Not sure if we're breaking this, removed a bait. but the download buttons aren't always showing even I disable the lists.
