### ISSUE TITLE
AdGuard Japanese : news.yahoo.co.jp, main content area blocked wrongly on mobile

### ISSUE THREAD

**Issue by siubb** [AdguardTeam/AdguardFilters#186203]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.59.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

news.yahoo.co.jp

### Ad Blocking

AdGuard Base filter

### Language-specific

AdGuard Japanese filter

### Add your comment and screenshots

1. <comment>
2. This rule blocks the main news content, was working ok, maybe yahoo japan changed something. 
Disabling it (#@# in my filter) solves the problem.

news.yahoo.co.jp##main#contents > div[class^="sc-"]:has(> div[class*=" "]:not([style]) > div[id^="yads_"])

3. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please wait an hour for filters update.
