### ISSUE TITLE
Glaz.tv compatibility

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1862]
Глаз ТВ
http://www.glaz.tv/download
При добавлении программы в фильтруемые и нажатии в программе на любой из каналов выскакивает сообщение "Ошибка данных":
http://prntscr.com/ak64r2

Если перезапустить ТВ канал, вылазит другое сообщение-ошибка:
http://prntscr.com/ak6567

Помогает отключение Русского фильтра.
Детали - EBJ-186-78654

**Comment by Alex-302** [comment]
добавил в русский
@@||winvideo.org/index.php?r=view/player$domain=m.glaz.tv
в экспериментальный(строка о пропуске рекламы над плеером)
m.glaz.tv###stream > div[style]

**Comment by Bohdan-SUP** [comment]
Снова появилась реклама:
http://prnt.sc/aswxvc

**Comment by Alex-302** [comment]
Чисто. У юзера программа? Исполняемый файл есть в списке фильтремых приложений?
<details> 
![](http://imagizer.imageshack.com/img921/1308/N6lVn5.png)
</details>

**Comment by Bohdan-SUP** [comment]
Программа, в списке есть, фильтры обновлены.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
попроси удалённый доступ, иного выхода нет.

**Comment by Bohdan-SUP** [comment]
Попросил, отпишу в чате.

**Comment by Alex-302** [comment]
Всё-таки повторяется у меня. Но её не убрать, т.к. она в плейлисте видео, и не отличима от основного видео.

**Comment by vgavrish** [comment]
Опять появляется "Ошибка данных" при нажатии в программе на любой из каналов (самое первое сообщение).
Помогает отключение русского фильтра. У меня проблемы не наблюдается. Версия программы GlazTV v 1.02

**Comment by Alex-302** [comment]
Не повторяется.

**Comment by vgavrish** [comment]
все работает)
