### ISSUE TITLE
animevost.org

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1863]
http://animevost.org/tip/tv/1481-gate-jieitai-kanochi-nite-kaku-tatakaeri-enryuu-hen.html
http://prntscr.com/ak6mvt

OIJ-769-11164

**Comment by Alex-302** [comment]
добавил в русский
world-art.ru##noindex > table[height="251"]
animevost.org#$#div[class^="headbg"] { background: transparent!important; }

**Comment by vgavrish** [comment]
1494657
Расширение
На главной баннер появляется после обновления страницы
Опера
Ф: 1,2,3,14
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/22370673/4a5cb36a-e49b-11e6-938e-923814116e35.png)

![image](https://cloud.githubusercontent.com/assets/18548949/22370704/6962b930-e49b-11e6-9853-cbd197e8183c.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
animevost.org#$#.banerTop { position: absolute!important; left: -3000px!important; }
animevost.org##div[id^="ambn"]
```

**Comment by ypetruk** [comment]
http://animevost.org/tip/tv/1904-youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e.html

Ad leftover
 iOS

<details><summary>Screenshot:</summary>

![image1](https://user-images.githubusercontent.com/28784344/28987212-0475531c-7973-11e7-93e1-4fa27c9f0291.JPG)

</details>

**Comment by Alex-302** [comment]
Fixed.
Please don't reopen old issues,
