### ISSUE TITLE
rightwingnews.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1865]
rightwingnews.com never load unless I disable Adguard.

Here are a few sample links

http://rightwingnews.com/column-2/cruz-must-anti-trump/

http://rightwingnews.com/legal/sheriff-blm-will-deputize-every-man-woman-child-get-real/

http://rightwingnews.com/culture/got-work-ethic-mike-rowe-launches-new-workers-programspoiled-whiners-need-not-apply/

![image](https://cloud.githubusercontent.com/assets/15856304/14064676/bfb634c4-f414-11e5-846d-957d2c87c4c6.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
I can't reproduce, need the filter list.
