### ISSUE TITLE
ok app - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1867]
https://play.google.com/store/apps/details?id=ru.ok.android&hl=uk

![image](https://cloud.githubusercontent.com/assets/15856304/14065150/9c919d46-f426-11e5-9a9d-788a8bf9c9ae.png)

 "versionName" : "2.5.70",
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "asus ASUS_T00G",
  "userfilter" : [ ],
  "updateChannel" : "BETA",
  "enabledFilterIds" : [ 2, 3, 4, 5, 1, 11 ],

http logs: XTY-406-46747

**Comment by Alex-302** [comment]
с этим приложением не знаю что делать
@Revertron 
можешь как-нибудь посмотреть? Они там JSON'ами вроде грузятся

**Comment by Alex-302** [comment]
нужно ждать реализации модификатора замены как в десктопном Адгарде
