### ISSUE TITLE
DB Navigator iOSWidget on Mac not working

### ISSUE THREAD

**Issue by Hessenpower01** [AdguardTeam/AdguardFilters#186976]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Mac

### AdGuard version

2.15.1.1731

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari, the problem is with app, not a site

### Which device do you use?

Desktop

### Where is the problem encountered?

DB Navigator Widget

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
And what exactly is not working?
Please try to enable German filter.

How to enable that widget on MAC?

**Comment by Hessenpower01** [comment]
> And what exactly is not working? Please try to enable German filter.
> 
> How to enable that widget on MAC?

thx for your reply

German filter is and was enabled. Any filter I shall disable?


It's one of the widgets that shows info from the corresponding iPhone App but displays it in the widget on the Mac Desktop. I don't know if the content in the widget is mirrored from the iPhone or grabbed from the web.

**Comment by BlazDT** [comment]
I see, so you need an iOS device where the app is running.

Any other filters except Base and German filters enabled? In the post only Base filter is shown.

**Comment by Hessenpower01** [comment]
> I see, so you need an iOS device where the app is running.
> 
> Any other filters except Base and German filters enabled? In the post only Base filter is shown.

Sorry, I did not post the correct info in my post regarding the filters. It is all standard setup (see attached screenshot). 

The widget does not connect any longer to the phone as you see in the attached screenshot, working again when disabling AdGuard.


![Uploading IMG_1128.jpeg…]()

**Comment by Hessenpower01** [comment]
![IMG_1129](https://github.com/user-attachments/assets/11dcc9de-de33-40aa-ade3-45801465faa3)
![IMG_1130](https://github.com/user-attachments/assets/f81165d2-e09f-4bb6-9405-751ea0d84d49)

**Comment by Alex-302** [comment]
@Hessenpower01 Please describe steps to reproduce.

**Comment by Hessenpower01** [comment]
@Alex-302 thanks for your efforts. Sorry, I thought it was clear but I will provide a detailed description now.

My Setup:
MacBook Pro M1, Macbook Air M1, both on MacOS Sonoma 14.6.1
iPhone 13 and 15, both on iOS 17.6.1

Issue happens on both Macbook.

AdGuard for Mac is installed on the Macbooks.
I installed DB Navigator on Iphone ( https://apps.apple.com/de/app/db-navigator/id343555245 ).
Then i added on my Macbook a Widget that is provided from the DB Navigator App on the iPhone (shows upcoming train connections on the Mac Desktop).

Works when AdGuard is deactivated. With AdGuard activated, the Widget does not any longer connect to the iPhone.


Hope this is clear now, thx again,

Meik

**Comment by Alex-302** [comment]
Ok, installed and registered.

> Then i added on my Macbook a Widget that is provided from the DB Navigator App on the iPhone (shows upcoming train connections on the Mac Desktop).

Can't find it. Need more details. Also please describe the problem - previous is unclear for me.


Btw is the problem related to enabled filters and DNS filtering on Mac?

> Works when AdGuard is deactivated. 

on iOS or Mac?

**Comment by Hessenpower01** [comment]
> Can't find it. Need more details. Also please describe the problem - previous is unclear for me.
right click on Mac Desktop - "Widgets bearbeiten" - search for "DB Navigator" and add one of the Widgets.

With AdGuard for Mac disabled, the widget will connect to the iPhone and display info. With Adguard for Mac enabled, it won't.

**Comment by Hessenpower01** [comment]
> I have another lang of OS. Please show screenshots.

do you need more info or is [the post](https://github.com/AdguardTeam/AdguardFilters/issues/186976#issuecomment-2321250472) from @rakleed sufficient?
