### ISSUE TITLE
add 123notes.com to whitelist 

### ISSUE THREAD

**Issue by ousigui123** [AdguardTeam/AdguardFilters#186975]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

up-to-date

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.123notes.com

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter

### Social Widgets

Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter

### Security

Online Malicious URL Blocklist

### Other

AdGuard Experimental filter

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
We don't whitelist sites. What is wrong?

**Comment by DandelionSprout** [comment]
Seemingly related to https://github.com/DandelionSprout/adfilt/issues/1050, though I can't find any indications that any of my lists are in fact involved either.
