### ISSUE TITLE
Faino TV app - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1869]
Faino TV
https://play.google.com/store/apps/details?id=com.electroncccp.fainotv&hl=en

в бете такая реклама: http://prntscr.com/aklo1n
выглядит белым окном с крестиком.

Необходимо покликать по каналам, чтобы она появилась (появляется перед загрузкой плеера).

**Comment by Alex-302** [comment]
там обычная реклама от google. Посоветуй установить бету(не включая HTTPS), там блокировка доменов улучшена.
