### ISSUE TITLE
onual.com

### ISSUE THREAD

**Issue by hurgir** [AdguardTeam/AdguardFilters#187018]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.4.18

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Chrome, other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://onual.com/fiyat/dyson-v15-detect-kablosuz-supurge-p-1531647.html#fiyat=22999&kullanici=42&link_t=8X49QOUUCM

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, Adblock Warning Removal List

### Language-specific

AdGuard Turkish filter

### Add your comment and screenshots

1. <comment>
track param to be removed
* kullanici
* link_t
2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
The parameters can be removed if they go after `?` in the URL.
