### ISSUE TITLE
tracker.openwebtorrent.com false positive.

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#187166]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

tracker.openwebtorrent.com

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

tracker.openwebtorrent.com is used by torrents. shouldnt be blocked.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Reported.

**Comment by Alex-302** [comment]
@hagezi I also see it in your list.

**Comment by hagezi** [comment]
Thanks @Alex-302, will be removed.
