### ISSUE TITLE
missing tracking links

### ISSUE THREAD

**Issue by sarimc** [AdguardTeam/AdguardFilters#187149]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

nightly

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

mail.google.com

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

Email tracking pixels and links: 

https://click.contact.kamalaharris.com/ss/c/id-redacted
https://email.win.donaldjtrump.com/c/id-redacted

Thank you

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@sarimc Hello. Could you please send mail sample to filters@adgurd.com (just to make sure we don't block anything necessary). personal info can be removed

**Comment by sarimc** [comment]
> @sarimc Hello. Could you please send mail sample to [filters@adgurd.com](mailto:filters@adgurd.com) (just to make sure we don't block anything necessary). personal info can be removed

No problem, just sent two samples - thank you

**Comment by jellizaveta** [comment]
Thank you! Added rules, will be available with the new update within 1-2 hours
