### ISSUE TITLE
uwlathletics.com

### ISSUE THREAD

**Issue by Jap2-0** [AdguardTeam/AdguardFilters#187287]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBo 1.59.1b7

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop and mobile

### Where is the problem encountered?

https://uwlathletics.com/

### Ad Blocking

The issue is in Adguard Cookie

### Add your comment and screenshots

See https://github.com/easylist/easylist/issues/19801.

`||transcend-cdn.com^$third-party` in the Adguard cookie list (cookies_general) leads to large or complete breakage on a variety of college sports websites.

Blocking this results in `Uncaught TypeError: airgap.toggle is not a function` on all pages; this may be something which is easily dealt with by shim or scriptlet or whatnot (I haven't kept up with writing filters much the past couple years) if that is the best solution.

For some reason I didn't notice this until a while after it was unblock in Easylist cookie, but it was introduced to this list by https://github.com/AdguardTeam/AdguardFilters/commit/f3e045dde8f14e68fe26a3dbdf29f5b6e5ce380e (issue https://github.com/AdguardTeam/AdguardFilters/issues/179568).

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available soon.
