### ISSUE TITLE
[iOS] Missed Ad http://vesti-ukr.com

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#1873]
http://vesti-ukr.com
Проверял с базовыми, обновленными фильтрами.
![image1](https://cloud.githubusercontent.com/assets/16462533/14074179/d11ebb64-f4d7-11e5-82d4-7e1f2e50a51c.PNG)

**Comment by Alex-302** [comment]
@Serzh-SUP
не повторяется без Адгарда. Удалённо бы глянуть

**Comment by Serzh-SUP** [comment]
@Alex-302 
Удаленно на ios?

**Comment by Alex-302** [comment]
а, не заметил.
У вас повторяется?

**Comment by Serzh-SUP** [comment]
@Alex-302 
Конечно, у меня на фоне та же картина.
Фильтры:
Англ., Русс., Сис. аналит., Эксперим., Полезной рекламы, Моб.рекламы, Для Сафари.

**Comment by Alex-302** [comment]
@Serzh-SUP 
Странно всё это. На айпаде чисто.
