### ISSUE TITLE
Inactive domains

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#187439]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

latest

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

many sites

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

Inactive domains:

toonget.net
animeshow.tv
mangafreak.net
mangapanda.com
memecenter.com (ERR_TOO_MANY_REDIRECTS)
mangareader.net (Ad redirect, possibly scam)
goodanime.co
toonova.net (I think must be blocked entirely, when I opened it, it replaced my tabs with ad urls)
gogoanime.in (redirects to gogoanime3.co)
kimcartoon.me (redirects to kimcartoon.li)
123-movies.life
123films.cc
123ssgm.cc (redirects somewhere, Adguard blocks it)
123moviesfx.live
123movies4u.icu
gofilms4u.co (redirects somewhere, Adguard blocks it)
gomovies.ltd (dns address not found)
gomovieshd.be
moviesahd.com (dns address not found)
my123movies.org
putlockerslinks.com
rdxhd.cool
the123movies.com
watchseriesproject.info
d123movies.to (redirects to 0123movies.la)
123movieshd.ws
gomovies.la
hentaivn.la
animeseed.com
ev01.sx (dns address not found)
asianhd1.com (redirects to draplay.info)
animetvn.xyz
animekaizoku.com (redirects to simkl.com)
toonanime.tv
animexin.xyz
4anime.to
french-stream.gg (redirects to vvw.french-stream.bio)
watch-free.tv (dns address not found)
webtoonplus.com (dns address not found)
readwebtoononline.net

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Thanks, done.

**Comment by Yuki2718** [comment]
`mangafreak.net` is changed to `mangafreak.me`, we might need a new rule.

**Comment by Yuki2718** [comment]
> Most of these are from rule in line 220 antiadblock.txt in Base Filter. Will continue looking through that later at some time.

If you can group the entries by including files, it will be helpful.

**Comment by Yuki2718** [comment]
Yeah, sorry, I deleted the comment. Checking status of them will already be quite a workload for you.

**Comment by Alex-302** [comment]
We have a tool to remove 100% dead domains.

**Comment by Alex-302** [comment]
It's not a quick process. Given the number of reports, it is not a high priority.

**Comment by Alex-302** [comment]
I remember about anidub.

**Comment by Yuki2718** [comment]
`anidub.life` was cleared out before this issue by https://github.com/AdguardTeam/AdguardFilters/commit/5e74f43acc33f452076b6dd8f6dc0e831734e71e

**Comment by Alex-302** [comment]
Of course, we welcome it)
But it is advisable not to put out a large amount at one time. Because we need to handle user reports as well.

**Comment by Yuki2718** [comment]
> We have a tool to remove 100% dead domains.

I noticed many of the reported domain are either parked or redirecting to new domain, which can not currently be handled by DDL.

**Comment by Alex-302** [comment]
@andris86 Will check.

Better open new issues. We may miss replies in closed issues.

**Comment by Alex-302** [comment]
peers.tv is working

**Comment by Alex-302** [comment]
![image](https://github.com/user-attachments/assets/8c8cd688-ae1e-4fda-872b-1b6b0a7ed12b)

**Comment by Yuki2718** [comment]
`520call.me` is active. It's used only for iframe like `https://video.520call.me/player101.php?id=101xxGDV1lMazM=`

**Comment by Alex-302** [comment]
I better will use https://github.com/AdguardTeam/DeadDomainsLinter 
It detects fewer domains, but the checking is almost 100% reliable.

**Comment by Alex-302** [comment]
Btw it can be used to check domain lists.

**Comment by Yuki2718** [comment]
> I better will use https://github.com/AdguardTeam/DeadDomainsLinter It detects fewer domains, but the checking is almost 100% reliable.

> I noticed many of the reported domain are either parked or redirecting to new domain, which can not currently be handled by DDL.

> I understand that you use it but will you deal with domains I posted here?

I can if he doesn't. The only reason I didn't was he said he will.

**Comment by Alex-302** [comment]
Removed these 

<details>
<summary>Details</summary>

allvidview.com
alogum.com
clubpenguinhq.net
comicspace.com.br
filmninja.ws
forstreams.com
free-bitcoin.ltd
hobbugs.com
joinfaucet.com
kstarmp3.com
leakgaming.fr
mangas-vostfr.pro
markipli.com
moretvtime.com
mytech.press
omgmusik.com
phimtron.com
pstream.net
toclipit.com
todosobrepsp.com
toxicpatat.com
upclips.online
vidupstream.com

</details>

**Comment by Alex-302** [comment]
Did not removed the rest, because manual checking is a time-consuming process.

**Comment by Alex-302** [comment]
Also, I didn't delete the others because the number of rules ends up being pretty much the same. A significant amount of dead domains were deleted a few months ago.
