### ISSUE TITLE
add filter for https://uprot.net/

### ISSUE THREAD

**Issue by saoiutjioser** [AdguardTeam/AdguardFilters#187588]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

adblock detection for fix i add ||ads.host-cdn.net$script on my ublock origin i block all site becouse all site is suspicion have multiple js file

### Proposed solution

||ads.host-cdn.net$script

**Comment by jellizaveta** [comment]
@saoiutjioser ads.host-cdn.net blocked by AdGuard Base filter. Do you have it enabled?

**Comment by saoiuitjioser** [comment]
> @saoiutjioser ads.host-cdn.net blocked by AdGuard Base filter. Do you have it enabled?

OMG, you're right, the problem was solved. Thank you.

**Comment by saoiuitjioser** [comment]
Problem was solved. Thank you.
