### ISSUE TITLE
etsy.com

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardFilters#187621]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.etsy.com/search?q=ps4+external

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

https://www.etsy.com/api/v3/ajax/public/shop-analytics/impression-log

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
I don't see that there is any personal information in this request
