### ISSUE TITLE
[iOS] www.tweaktown.com - anti adblock script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#1876]
![image](https://cloud.githubusercontent.com/assets/541725/14086643/791afdc0-f526-11e5-9270-438d4a1849d2.png)

**Comment by Alex-302** [comment]
Can't reproduce. Please check this rule
@@||tweaktown.com^$generichide

**Comment by Vincent-Michael** [comment]
> @@||tweaktown.com^$generichide
does not help

its since ios 6.3

**Comment by Alex-302** [comment]
try this please
@@||tweaktown.com^$generichide,genericblock
Maybe you check not on the main page?

**Comment by Vincent-Michael** [comment]
@Alex-302 
> @@||tweaktown.com^$generichide,genericblock
Maybe you check not on the main page?

doesnt help too

**Comment by Alex-302** [comment]
@@||tweaktown.com^$document
if doesnt help too
add also
@@http://$domain=tweaktown.com
@@https://$domain=tweaktown.com

**Comment by Vincent-Michael** [comment]
i found that problem @Alex-302 

``` @@||www.tweaktown.com^$content ``` 
its noscript issue

> <noscript>&lt;meta http-equiv="refresh" content="3;URL='http://www.tweaktown.com/sp/index.html'"&gt;</noscript>

**Comment by Alex-302** [comment]
Modifier $content is not supported by browser extensions.
> its noscript issue
Are you using some noscript extension?

**Comment by Vincent-Michael** [comment]
its ios app ^^ @Alex-302
