### ISSUE TITLE
sonixgvn.net URL blockage exception

### ISSUE THREAD

**Issue by moemoe900** [AdguardTeam/AdguardFilters#187705]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.4.18

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

sonixgvn.net

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. <comment>
I know there is a similar case like [this ](https://github.com/AdguardTeam/AdguardFilters/issues/186942). But, that one is for adblock blocker. Since this is file-hosting site, adguard aggressively block the element that contain the URL that leads to external site. Is it possible to make an exception or at least make the URL visible?
Example:  https://sonixgvn.net/zettai-meirei-isekai-soushin-party-theme-song-cd/
2. Screenshots

<img width="863" alt="363465648-26168e18-24de-4578-b191-85c4dad54750" src="https://github.com/user-attachments/assets/e939bd8c-29f1-4282-9c33-8259eee89ec8">

Extension enabled

<img width="760" alt="363465627-359e4ff8-3c0d-4cff-bca0-c9846276435a" src="https://github.com/user-attachments/assets/20dc0db4-3f38-49eb-a0dd-33f9db141d54">

Extension disabled

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by moemoe900** [comment]
Hold on, I use chromium and I try to use MV3 version or MV2 version and the adblock blocker is back. 
<img width="692" alt="image" src="https://github.com/user-attachments/assets/3236f261-3f66-4d33-a629-29a6a1579263">
<img width="317" alt="image" src="https://github.com/user-attachments/assets/4bd73cad-1ef6-4287-8e37-a5630afe1982">

**Comment by AdamWr** [comment]
I checked it in Chrome with AdGuard 4.4.22 version and I couldn't reproduce anti-adblock and incorrect blocking and still cannot.
Do you have up to date filters?
And again, what filter lists do you have enabled in AdGuard settings?

**Comment by moemoe900** [comment]
here it is
<img width="883" alt="image" src="https://github.com/user-attachments/assets/cab6ac1c-6dc3-4285-8d66-bd44b5c45127">

**Comment by AdamWr** [comment]
Not all filter lists are visible on the screenshot.
As I'm not able to reproduce it and I still don't know which filter lists are enabled, then please again, list all filter lists and also disable them one by one and check which one causes incorrect blocking.

**Comment by moemoe900** [comment]
if you mean toggle on like this
<img width="274" alt="image" src="https://github.com/user-attachments/assets/783c6dfb-f4d6-4582-a327-6e843f31ab41">
or  this
<img width="396" alt="image" src="https://github.com/user-attachments/assets/03b4c9b5-0a94-490c-a2bb-4917f1aba58d">

**Comment by AdamWr** [comment]
Firstly you can disable whole group (so like on the first screenshot), then when you find which group causes incorrect blocking, you can enable this group again and if there are few filter lists in this group, disable them on by one.

**Comment by moemoe900** [comment]
Thanks, it works for MV2 version. But, I tested the MV3 version for chromium the URL blockage exist.

**Comment by AdamWr** [comment]
The problem is that MV3 extension cannot update filters (the whole extension must be updated), so it probably doesn't have new rules yet.
You can add this rule:
```adblock
sonixgvn.net#%#//scriptlet('abort-on-stack-trace', 'Object.defineProperty', '/https?:\/\/sonixgvn\.net\/.*\.js:|data:text\/javascript;base64|blocker|crabdance\.com|\/ads\//')
```
to user rules.

**Comment by moemoe900** [comment]
Thanks, it works for now. Let's see if the website updated again
