### ISSUE TITLE
Pladform Player has been blocked by French Filter

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#18776]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

The player is blocked by the blocking rule below:

URL: http://adbetnet.advertserve.com/js/libcode3.js
Referrer: http://serialbox.org/test-pleera.html

Data type: JavaScript

Rule: /adbetnet.
Filter: AdGuard French filter

[//]: # (Substitute this line with a description of the problem)

***Steps to reproduce the problem***:

Enable French filter and go to http://serialbox.org/test-pleera.html

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

Chrome v. 67.0.3396.87
adguard v. 2.9.2

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | MacOS
Browser:                               | Chrome
AdGuard version:                       | 67.0.3396.87
Filters enabled:                       | Russian, English, French, Spyware, Social Media
AdGuard DNS:                           | None 
Helpdesk ID (if exists):               | 1913931

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Different rule was the cause. Update will be available in 2-3 hours.
