### ISSUE TITLE
Nolo.com Chat feature blocked by AdGuard

### ISSUE THREAD

**Issue by SabinFiggy** [AdguardTeam/AdguardFilters#18789]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Chat feature blocked by AdGuard***:
* **Adguard prevents the chat feature on site from working altogether, rather than just blocking the popup**: 

https://www.nolo.com/legal-encyclopedia/what-independent-medical-examination-how-will-it-affect-my-workers-compensation-case.html

Sometimes the chat feature will show up on Nolo.com, but when it does, I am unable to use it because AdGuard has blocked the script entirely. 

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/32PpTyk.png)å
</details><br/>

* **Expected behaviour**: 

Click the chat button starts a chat session. 

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/MQ1UOlv.png)
</details><br/>

***Steps to reproduce the problem***:

1. Go to https://www.nolo.com/legal-encyclopedia/what-independent-medical-examination-how-will-it-affect-my-workers-compensation-case.html
2. Chat feature usually will not show up at all, but occasionally the button up at the top will display. If it displays, clicking it will result in a Javascript error. 
3. Disable AdGuard, reload site.
4. Observe "Live Chat" button at top of the site, click it. Chat will open.

***System configuration***

**Filters:**

Annoyances, English, Spyware
 
Information                            | Value
---                                    | ---
Operating system:                      | OSX
Operating system version (Android/iOS) | High Sierra 10.13.1
Browser:                               | Chrome
AdGuard version:                       | 1.5.3
Filters enabled:                       | Annoyances, English, Spyware 
AdGuard DNS:                           | Default

**Comment by BlazDT** [comment]
Annoyance filter is supposed to kill popups like this chat or am I mistaken @Alex-302?.
You can add this rule to unlock it:

@@||messenger.ngageics.com^$domain=nolo.com

**Comment by SabinFiggy** [comment]
Agreed that it should kill the popups, but it shouldn't kill the ability to use the chat altogether.

**Comment by Alex-302** [comment]
We block third-party and annoying chats in annoyances filter. This is expected behavior.
You can add the rule above to unblock that widget.
