### ISSUE TITLE
http://rufilm.tv - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1879]
http://rufilm.tv/serials/kuhnya-6-sezon-18-seriya-29-03-2016-smotret-onlayn.html
http://prntscr.com/alerfp
при нажатии на плей видео, запускается еще один сайт am15.net и исчезает
http://prntscr.com/alerqq

SCY-743-55447

**Comment by Alex-302** [comment]
У меня не всплывает. Но если всплывает и закрывается без дальнейших переходов, то это нормально. Как именно у него происходит?
