### ISSUE TITLE
Video doesn't play on rutube.ru

### ISSUE THREAD

**Issue by vapaamies** [AdguardTeam/AdguardFilters#188013]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

4.4.22

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

https://rutube.ru/video/a0449a022e3791db6efa2df4c25375c9/

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, Legitimate URL Shortener, Peter Lowe's Blocklist

### Annoyances

AdGuard Annoyances filter, Adblock Warning Removal List, EasyList Cookie List

### Language-specific

AdGuard Russian filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Hide Referrer from third-parties (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests

### Add your comment and screenshots

Video doesn't play when filtering is on (endless waiting wheel), plays normally when I disable filtering for Rutube (big green button).

This issue occurred yesterday, applies to any video on Rutube.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@vapaamies У меня не повторяется.

Можете проверить в пользовательском фильтре правило `@@||yandex.ru/ads/system/adsdk.js$domain=rutube.ru`?
https://github.com/AdguardTeam/AdguardFilters/commit/32b8d5ee63f4e1e9526731a179c96d67083df3b4#diff-69cdc757607149b729f2613bcfca302e308ceb865ad5a2eaccbb41f89398b2a1R119

**Comment by vapaamies** [comment]
@Alex-302 Не помогло. Судя по журналу, встроенное правило срабатывает раньше пользовательского, и усё.

Помогло отключение базового фильтра AdGuard в настройках (через журнал увидел, что правило на adsdk.js — в нем).

**Comment by vapaamies** [comment]
В журнале всего две строчки по этому фильтру:
* JS `https://yandex.ru/ads/system/adsdk.js` ← `.ru/ads/` Базовый фильтр AdGuard
* XHR `https://pretarg.adhigh.net/v1/segs` ← `||adhigh.net^$third-party` Базовый фильтр AdGuard

**Comment by Alex-302** [comment]
@vapaamies А правило в пользовательский фильтр добавляли? Или проверьте обновление фильтров, оно должно быть уже доступным.
