### ISSUE TITLE
Петлевой редирект в хром-интеграции телеграма на али и озоне из-за антитрекинга

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/AdguardFilters#188053]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [ ] AdGuard product version is up-to-date;
- [ ] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

3.6.11/54

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.ozon.ru

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies

### Add your comment and screenshots

1. 

В браузерной интеграции (хром) в телеграмме (FOSS) и сайты магазинов (по крайней мере озон и али) упорно не хотят открываться застревая в редирект- петле (судя по дампу из adguard 59 редиректов + исходный запрос), пока сам хром не даёт отбой по достижении предела редиректов и не выдаёт "ERR_TOO_MANY_REDIRECTS". Ссылки без трекинга (без мусора после ".html"). В хроме "напрямую" открываются без проблем. В хром-интеграции в ТГ идёт редирект-петля. Модуль антитрекинга пробовал отключать, но это не помогает. 

Похоже, дело действительно в AdGuard, но не в антитрекинге. По крайней мере не в самой функции. В режиме интеграции браузера adguard'ом срезаются куки и вероятно из-за наличия реферера телеграма (а мб и ещё почему) антиспам система озона и али считает, что ссылку открывает бот и постоянно редиректит на страницу для выдачи кук а т.к. куки срезаются всё уходит в петлю. Если отключить для озона антитрекинг через правило

>@@||ozon.ru^$stealth

то во "встроенном браузере" телеграма озон открывается без заморочек. Походу дело всё-таки в антитрекинге, но не в том, что включается отдельной функцией, а в том, что работает через фильтры. Или это один и тот же механизм ? Но почему тогда отключение функции не даёт эффекта ? Какое будет более корректное правило, что позволит минимизировать утечки ? Пробовал перебирать стелс-опции вплоть до использования

>@@||ozon.ru^$stealth=searchqueries|donottrack|3p-cookie|1p-cookie|3p-cache|3p-auth|webrtc|push|location|flash|java|referrer|useragent|ip|xclientdata|dpi

но петлевой редирект остаётся.

3. Screenshots
<details><summary>Screenshot 1:</summary>

![-5391231868826935994_121](https://github.com/user-attachments/assets/127369d3-a4f5-442f-a623-ea44db20242f)

</details>

</details>

p.s. Что промаркировать в опциях тикета стелс-режима при "высоком" уровне антитрекинга ?

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Это их антиддос. Попробуй v4, там были изменения про это.

**Comment by Baltazar500** [comment]
>Это их антиддос. Попробуй v4, там были изменения про это.

А для 3-й совсем без вариантов, кроме принудительного отключения стелса через правила для конкретного сайта ?

**Comment by Alex-302** [comment]
Скорее всего без вариантов, она давно не поддерживается, а простое обновление библиотек ничего кроме новыых проблем не даст.
