### ISSUE TITLE
www.gamak.tv

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1881]
http://www.gamak.tv/pervyi_kanal/2016-03-29/00:00/

Не воспроизводится видео трансляция, черный экран:
http://prntscr.com/alhdzk

при отключении Английского фильтра - работает
http://prntscr.com/alhdg4

**Comment by Alex-302** [comment]
добавил
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=gamak.tv
@@||gamak.tv/static/player5.8/scripts/videojs.ads.min.js$domain=gamak.tv
gamak.tv###ima-ad-container

**Comment by vgavrish** [comment]
Не воспроизводится видео трансляция, черный экран + ошибка.
http://www.gamak.tv/pervyi_kanal/2016-10-15/02:10/
Фильтры: Русский, Английский
Хром
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19408432/74565b6c-92c5-11e6-88f9-17c023b1a8d9.png)

**Comment by Alex-302** [comment]
Fixed.
