### ISSUE TITLE
smsonline.cloud

### ISSUE THREAD

**Issue by loana2918** [AdguardTeam/AdguardFilters#188411]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

Version 4.4.22

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.smsonline.cloud/

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. <comment>
When I enabled AdGuard and accessed smsonline, a warning appeared. Refreshing the page normally fixed it, but pressing Command + Shift + R to refresh consistently brings up the warning.

2. Screenshots
<details><summary>Screenshot 1</summary>

<img width="699" alt="image" src="https://github.com/user-attachments/assets/4da81dfa-d561-4d13-b850-60286cc7b289">

</details>

<details><summary>Screenshot 2</summary>

<img width="961" alt="image" src="https://github.com/user-attachments/assets/cc0b2eb9-1162-4ee2-a762-88aa36295ee2">

</details>

<details><summary>Screenshot 3: When I disable adguard</summary>

<img width="1833" alt="image" src="https://github.com/user-attachments/assets/fbdfda90-a61e-4712-a5bd-09e508045a79">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/79614f2fa16b5d2fcce7482b85f02b2f9eeca5e0
