### ISSUE TITLE
check-host.net website usage issue

### ISSUE THREAD

**Issue by yestogo** [AdguardTeam/AdguardFilters#188685]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

2.3.52.55

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://check-host.net/about/api

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

1. API page is unreadable with enabled AdGuard filters. And server's information is not available while clicking on country+city (while checking any IP address or website). 

2. Screenshots
<details>
<summary>Screenshot 1:</summary>
<img width="925" alt="apiissue" src="https://github.com/user-attachments/assets/8e48b460-0d77-41a1-b9de-b7138f4ec499">
</details>

<details><summary>Screenshot 2:</summary>
<img width="933" alt="hostinfo1" src="https://github.com/user-attachments/assets/79a1a6cf-3809-49db-b4ec-674bd6378ea8">
</details>

<details><summary>Screenshot 3:</summary>
<img width="932" alt="hostinfo2" src="https://github.com/user-attachments/assets/6c61e67e-9ea9-48ae-aba5-4574c79e11b6">
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Already fixed.
