### ISSUE TITLE
Hydro coach - missed blank space

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1887]
The [app](https://play.google.com/store/apps/details?id=com.codium.hydrocoach&hl=ru)

http://prntscr.com/am50d7
Can we remove the placeholder? It appears with HQ mode and HTTPs filtering enabled. Thanks.

**Comment by evgeniy-ADG** [comment]
The same thing in the [Gumtree ](https://play.google.com/store/apps/details?id=com.gumtree.android)app:

![image](https://cloud.githubusercontent.com/assets/15856304/14155803/ffb3ad7c-f6cb-11e5-934b-cfec2cf121a8.png)

**Comment by Alex-302** [comment]
похоже не убрать, так задумано

**Comment by Bohdan-SUP** [comment]
The issue happens only with https filtering enabled. Ads are blocked correctly without it.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
can you confirm absence of placeholder fithout HTTPS? I see it in both in both cases

**Comment by evgeniy-ADG** [comment]
@Alex-302 @Bohdan-SUP At my end the placeholder contains Ads by Google. Persists in both cases - empty with HTTPs on and showing ads without HTTPs filtering.
