### ISSUE TITLE
unka.bilecik.edu.tr

### ISSUE THREAD

**Issue by Raidware** [AdguardTeam/AdguardFilters#188823]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

im using  AdGuard/uBO – Cookie Notices on uBlockOrigin

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://unka.bilecik.edu.tr:82/User/Login

### Ad Blocking

AdGuard Base filter, EasyList

### Annoyances

AdGuard Cookie Notices filter, EasyList Cookie List

### Add your comment and screenshots

1. AdGuard/uBO – Cookie Notices breaks this website. without this filter website working properly. Also i enabled EasyList/uBO – Cookie Notices still same. Both of them breaks website.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://github.com/user-attachments/assets/8cb99262-dbc6-4514-802c-2569f93554ba)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Raidware** [comment]
@Alex-302 still same with


AdGuard/uBO – Cookie Notices and EasyList/uBO – Cookie Notices with uBlockOrigin

**Comment by Raidware** [comment]
> @Raidware Do you see `unka.bilecik.edu.tr#@##cookieConsent` in the filter?

how can i see it? is there are debug mode or something. i dont know

**Comment by Raidware** [comment]
> @Raidware Do you see `unka.bilecik.edu.tr#@##cookieConsent` in the filter?

Yes.

![Screenshot_20240916_183559](https://github.com/user-attachments/assets/42fa158f-9e48-4878-adab-dc01ea6d5f59)

**Comment by Alex-302** [comment]
Buttons don't work or work? 



uBO does not load `trusted` rules from third-party filters. 
`unka.bilecik.edu.tr#%#//scriptlet('set-cookie-reload', '.AspNet.Consent', 'yes')`
@stephenhawk8054 Please take a look.

**Comment by Raidware** [comment]
> Buttons don't work or work?
> 
> uBO does not load `trusted` rules from third-party filters. `unka.bilecik.edu.tr#%#//scriptlet('set-cookie-reload', '.AspNet.Consent', 'yes')` @stephenhawk8054 Please take a look.

yes buttons broken. Fixed with this filter.

**Comment by Alex-302** [comment]
I can't reproduce buttons breakage.

**Comment by Raidware** [comment]
> I can't reproduce buttons breakage.

Nope. With filter that you send, fixed.
