### ISSUE TITLE
Application error with content blocker

### ISSUE THREAD

**Issue by mianio** [AdguardTeam/AdguardFilters#189122]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

2.7.3

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://smsonline.cloud

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>
I can't use this web site with Adguard.
2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="410" alt="image" src="https://github.com/user-attachments/assets/35b48e07-15fc-4a78-8a8c-28241451a612">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
`AdGuard Content Blocker` cannot block this ad (error - result of partial blocking). Please install `AdGuard for Android` from adguard.com

Btw I have a question - are you aware of the existence of `AdGuard for Android` - standalone app for systemwide filtering?
