### ISSUE TITLE
Blocked site

### ISSUE THREAD

**Issue by amelia6598** [AdguardTeam/AdguardFilters#189123]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

2.7.3

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://mobile.missyusa.com/mainpage/index.asp

### Ad Blocking

AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment> ```Page URL : https://mobile.missyusa.com/mainpage/index.asp```
2. Screenshots
<details><summary>Screenshots</summary>

<img width="403" alt="image" src="https://github.com/user-attachments/assets/7d9d7cae-c4ca-41ff-92b5-b7b2f1f30d21">

<img width="403" alt="image" src="https://github.com/user-attachments/assets/952bcb48-5554-44a5-9933-98bef1aeb014">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
`AdGuard Content Blocker` cannot block this ad. Please install `AdGuard for Android` from adguard.com

Btw I have a question - are you aware of the existence of `AdGuard for Android` - standalone app for systemwide filtering?
