### ISSUE TITLE
jin115.com

### ISSUE THREAD

**Issue by mason945** [AdguardTeam/AdguardFilters#189121]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

2.7.3

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

http://jin115.com/ on samsung browser

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment> I think problem with the adguard filter. </comment>

2. Screenshots
<details><summary>Screenshot</summary>

<img width="401" alt="image" src="https://github.com/user-attachments/assets/c631a472-b25d-424b-be6d-759d262b183d">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
The website loads fine on my end.
However, it's recommended to install [AdGuard for Android](https://adguard.com/adguard-android/overview.html) instead of the AdGuard Content Blocker.
