### ISSUE TITLE
Dogdrip not working

### ISSUE THREAD

**Issue by benjamin3048** [AdguardTeam/AdguardFilters#189115]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

2.7.3

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

dogdrip.net

### Ad Blocking

AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment>
When I access dogdrip, the web page is broken, and a warning window appears like the screen below. 
Please fix it.
I'm only using the AdGuard extension in my Samsung browser.

2. Screenshots
<details><summary>Screenshot 1: using adguard</summary>

<img width="407" alt="image" src="https://github.com/user-attachments/assets/aaf2d1fd-633f-499f-b916-7b883a422942">

</details>

<details><summary>Screenshot 2: when i turn off adguard</summary>

<img width="418" alt="image" src="https://github.com/user-attachments/assets/e6e617d1-f13b-477d-94e3-275665c7b628">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
`AdGuard Content Blocker` cannot block this ad. Please install `AdGuard for Android` from adguard.com

Btw I have a question - are you aware of the existence of `AdGuard for Android` - standalone app for systemwide filtering?
