### ISSUE TITLE
Ugreen nas share page does'n work properly

### ISSUE THREAD

**Issue by wittybaji** [AdguardTeam/AdguardFilters#189159]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

128.0.6613.138

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://example.com

### Ad Blocking

AdGuard Base filter

### Social Widgets

AdGuard Social Media filter

### Add your comment and screenshots

1. <comment>
Ugreen nas file share page does'n work properly.
2. Screenshots
<details><summary>Screenshot 1:</summary>
![open](https://github.com/user-attachments/assets/aeea5cad-18d7-4025-81b4-ae49cffda448)
</details>
It should look like this.
<details><summary>Screenshot 2:</summary>
![close](https://github.com/user-attachments/assets/e6ff2882-abbd-47a4-bbb0-8a72cb6a99a4)
</details>
The corresponding rule is:
<details><summary>Screenshot 3:</summary>
![log](https://github.com/user-attachments/assets/8be22914-a3d1-4d76-8be4-1b3a1b52b935)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
What site is this happening on?

**Comment by wittybaji** [comment]
> What site is this happening on? I see that you blurred the source on the third screenshot.

This is the web console of my nas, which is bound to my own domain name. And I think this could be a public issue for UGreen NAS. This rule should be modified to be a blacklist of common websites, rather than taking effect by default on all websites.

**Comment by zloyden** [comment]
The rule blocks share elements on many sites, so it would be inefficient to make it specific.
You can make an exception for your domain by adding it to the rule below, or whitelist it completely.
```adblock
#@#.share-list
```

**Comment by wittybaji** [comment]
> The rule blocks share elements on many sites, so it would be inefficient to make it specific. You can make an exception for your domain by adding it to the rule below, or whitelist it completely.
> 
> ```
> #@#.share-list
> ```

Okay, I've reported this issue to UGreen, perhaps they will change the default class name.😂
