### ISSUE TITLE
Gemini app gives "connection was interrupted"

### ISSUE THREAD

**Issue by sodkfjoa** [AdguardTeam/AdguardFilters#189138]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.6.3

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.google.android.apps.bard

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Add your comment and screenshots

1. Shows the message "Your connection was interrupted, please try again (14)" and has trouble loading recent chats, but after a while still loads them if I reopen the app.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot_20240920_025903_com google android googlequicksearchbox](https://github.com/user-attachments/assets/73c9b630-2293-4caa-a0fb-977f5eff8fab)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Cannot reproduce. If disabling filters does not help, please write here https://github.com/AdguardTeam/AdguardForAndroid

**Comment by sodkfjoa** [comment]
If I disable the filtering for the app "Google", there aren't any more errors.

These errors don't show up all the time, but for me quite often.

Here are some more people reporting the same problem:

https://www.reddit.com/r/Bard/comments/1cc5g79/frequent_connection_error_in_app

Also moving around in the menus of the Google app, some pages don't load on the first try and give the same error, but after trying again they start working.
