### ISSUE TITLE
Reddit.com ad container elements are not being hidden

### ISSUE THREAD

**Issue by zefwef** [AdguardTeam/AdguardFilters#18927]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Reddit.com ad container elements in the sidebar are not being hidden (but the ads themselves are being hidden).

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

![image](https://user-images.githubusercontent.com/40073536/42005641-66c85ee8-7a2a-11e8-86a3-d9f54921991e.png)

</details><br/>

***System configuration***

**Filters:**

[//]: # English, Spyware

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | macOS
Operating system version (Android/iOS) | 10.14
Browser:                               | Chrome
AdGuard version:                       | 1.5.8
Filters enabled:                       | English, Spyware
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Please check this rule:
`reddit.com##div[class="s1g6rpxu-1 WwRro s180jmvl-0 eavsOb"]`
@BlazDT

**Comment by BlazDT** [comment]
Added:
`reddit.com##.ii4q9d-0.fePAzF > div.s1g6rpxu-1`

**Comment by BlazDT** [comment]
It is hidden when I try. Please check @AdamWr

**Comment by AdamWr** [comment]
I see it only while website is loading, but when it's fully loaded then these ad leftovers/containers are hidden.
You can try this rule:
```
reddit.com##.ii4q9d-0.fePAzF > div[class]:has([class^="_"] > [class*=" "]:empty:matches-css-before(content: advertisement))
```

**Comment by zefwef** [comment]
Try going to reddit.com/top instead of reddit.com.

**Comment by AdamWr** [comment]
I still can't reproduce it.
Please check this rule:
```
reddit.com##.ii4q9d-0.fePAzF > div[class]:has([class^="_"] > [class*=" "]:empty:matches-css-before(content: advertisement))
```

**Comment by zefwef** [comment]
They still show up for me even with that rule. What about on a specific subreddit like https://www.reddit.com/r/Android/?

**Comment by BlazDT** [comment]
Clean here.
