### ISSUE TITLE
[iOS] Missed Ad http://new-rutor.org/

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#1893]
Фильтры базовые.
[Линк](http://new-rutor.org/)
![image-31-03-16-12-02](https://cloud.githubusercontent.com/assets/16462533/14175946/2bda29b8-f757-11e5-99b3-9f3d99bfe330.png)

**Comment by Alex-302** [comment]
Может фильтры старые? Рекламу блокирует правило из русского:
```
||cdn7.network^
```
Очень желательно копировать сюда список фильтров, в state.txt он.

**Comment by Alex-302** [comment]
Для рекламы справа:
```
||new-rutor.org/js/js.js
||new-rutor.org/js/br.js
||fextor.ru^$third-party
```

**Comment by Serzh-SUP** [comment]
@Alex-302
Фильтры не старые, я и у себя смотрел. Вот свежие скрины:
![img_8744](https://cloud.githubusercontent.com/assets/16462533/14810004/5fd1679e-0b99-11e6-8973-a5b11d4da2b7.PNG)
![img_8743](https://cloud.githubusercontent.com/assets/16462533/14810012/68cc1ce0-0b99-11e6-9426-7bcb9f69ff1b.PNG)
![img_8745](https://cloud.githubusercontent.com/assets/16462533/14810020/6d5aa18c-0b99-11e6-9330-8db7224923fd.PNG)

**Comment by Alex-302** [comment]
какая-то непонятная магия. А можешь с одним русским фильтром проверить? Может из-за оптимизации правила не попадают в контент-блокер.

**Comment by Alex-302** [comment]
Проверил на настоящем айпаде - чисто.
