### ISSUE TITLE
https://www.onlinegdb.com/

### ISSUE THREAD

**Issue by isabella4761** [AdguardTeam/AdguardFilters#189347]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.5.5

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.onlinegdb.com/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

<comment> When using only AdGuard, an error like the one in the image occurs.
<details><summary>Screenshot 1:</summary>

<img width="326" alt="image" src="https://github.com/user-attachments/assets/7a391fe1-87ae-43d8-898e-ec06a4c70825">

</details>

<details><summary>Screenshot 2:</summary>

<img width="326" alt="image" src="https://github.com/user-attachments/assets/81ec4352-0cc4-4cfe-a9c7-b79896183d80">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Cannot reproduce with your settings. 
Please try to disable-enable content blockers in Safari settings and restart Safari, and check for filters update.
Do not close AdGuard window ~90 seconds, because iOS will break configuration process.

And check if Advanced Protection is enabled.
