### ISSUE TITLE
Blocked site again...

### ISSUE THREAD

**Issue by amelia6598** [AdguardTeam/AdguardFilters#189349]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

2.7.3

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.smsonline.cloud/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. <comment> Once again, the website loading has failed due to AdGuard.
2. Screenshots
<details><summary>Screenshot 1</summary>

<img width="407" alt="image" src="https://github.com/user-attachments/assets/57ab8a6b-9ac8-47e0-8718-0b7d5fdfb8c9">

</details>

<details><summary>Screenshot 2</summary>

<img width="411" alt="image" src="https://github.com/user-attachments/assets/8edab7f5-e799-4c08-9bda-74a5359f822b">

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please install AdGuard for Android. AdGuard Content Blocker can't help on this site.
