### ISSUE TITLE
www.missyusa.com

### ISSUE THREAD

**Issue by yoonlucas** [AdguardTeam/AdguardFilters#189344]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.5.5

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://missy

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

<img width="288" alt="image" src="https://github.com/user-attachments/assets/f9b8efa6-97bc-4226-aa80-32125bdf2786">

### Privacy

- [X] I agree to follow this condition

**Comment by Yuki2718** [comment]
You didn't fill in necessary information. The site is infected by Ad-Shield.

**Comment by Alex-302** [comment]
Can't access at the moment. But should be blocked by Advanced Protection.

**Comment by Alex-302** [comment]
Loaded. Reproduced only on very first load. After that - not reproduced. Typical iOS behaviour with advanced rules.

**Comment by Yuki2718** [comment]
> Loaded. Reproduced only on very first load. After that - not reproduced. Typical iOS behaviour with advanced rules.

Well, novice user never know and won't reload these sites... Does adding CSS filter(s) help in case scriptlet didn't work?

**Comment by Alex-302** [comment]
@Yuki2718 In iOS impossible to inject scripts like in normal browsers. Probably the same with CSS.
