### ISSUE TITLE
过滤失败

### ISSUE THREAD

**Issue by gaomengzhou** [AdguardTeam/AdguardFilters#189442]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [ ] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS, AdGuard for Safari

### AdGuard version

4.5.5

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

网址https://www.91porn.com

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

EasyPrivacy

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Widgets filter

### Security

Online Malicious URL Blocklist

### Other

Filter unblocking search ads and self-promotion

### DNS filters

AdGuard DNS filter

### Language-specific

AdGuard Chinese filter

### What Stealth Mode options do you have enabled?

Block Push API

### Add your comment and screenshots

1. Add rule

2. Screenshots
![IMG_0985](https://github.com/user-attachments/assets/e07a9601-7afd-4124-a6b3-27e248027a99)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Already blocked.
