### ISSUE TITLE
Remove anciently outdated Norwegian entries, as well as 6 duplicate entries in foreign.txt

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#189405]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

There's some very, very outdated entries in foreign.txt for Norwegian, especially in regards to VG, ITavisen, and FinnNO. Many of the entries have not matched any elements on the sites for more than 5 years, and as such I feel they should be removed.

I also detected 6 entries elsewhere in foreign.txt that had duplicates of them within the same foreign.txt file, which I hope to de-duplicate.

## Remove these entries:
```
itavisen.no##.banner
finn.no##iframe#easyad
finn.no##iframe#smallEasyAd
finn.no##.banner-skyscraper-container
finn.no##div.banners[style^="height: 150px"]
finn.no##.banners[data-banner-pos="topbanner"]
finn.no##div.external-banner-board.adsbox[data-controller]
finn.no##.banners.adsbox
e24.no##.ad
vg.no##.ad
vg.no##.inline-ad-text
vg.no##.advert
vg.no##.finn-placeholder
itavisen.no##div[id^="ad-"]
vg.no###ad-topboard
```
## Remove duplicates of:
```
||traffic.styria.hr^
||widget.admiral.hr^
nextech.sk##.promo-zone
jagonews24.com##.featured-inImage-ad-unit
minioppai.org##.kln
well.pl##.sda-container
```

### Additional information

I had noticed *"If the related issue does not exist in our repository, please create it before making pull request"* in the PR submission form, so I thought, "Hmm, fair enough. I'll create an issue report for it too."

Very loosely inspired by #188315

**Comment by Alex-302** [comment]
merged
