### ISSUE TITLE
[Android] we're missing ads in vk app with https enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1894]
https://pp.vk.me/c615725/v615725122/2b56/kQe6u8NGFrc.jpg
![image](https://cloud.githubusercontent.com/assets/15856304/14176344/32931ca4-f759-11e5-93c4-6315c4feb7b0.png)

**Comment by Alex-302** [comment]
ситуация как и с приложением одноклассников. Ждём пока

**Comment by evgeniy-ADG** [comment]
Еще нет решения?

**Comment by Alex-302** [comment]
пока нет

**Comment by vgavrish** [comment]
а сейчас?
хоть примерное время когда будет

**Comment by Alex-302** [comment]
Приложения FB, Twitter, VK, Instagramm используют SSL Pinning, т.е. не работают с расшифрованным и переподписанным трафиком.
