### ISSUE TITLE
Ecranlarge.com

### ISSUE THREAD

**Issue by Mimi87-stack** [AdguardTeam/AdguardFilters#189722]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

List only

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.ecranlarge.com/

### Ad Blocking

EasyList

### Annoyances

EasyList Cookie List

### Language-specific

AdGuard French filter

### Add your comment and screenshots

1. <comment>
The ads aren’t fully blocked, the space used by them is still displayed.

using Brave 1.69.1 on IOS 18 with default filters + fr list.

Could you add this fix to the Adguard fr list as ecranlarge.com is a French website?

thanks in advance and best reguards.
2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://github.com/user-attachments/assets/41545694-f5c8-40c4-86a9-4e0d7412ca9e)

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. Can't reproduce with AdGuard Base + AdGuard French filters in Safari on iOS. Our filters have the necessary rules.

**Comment by Mimi87-stack** [comment]
Hi, I’m using Brave, not Safari.

Adguard French filters only on top of Brave default filters so no Adguard base filters.

**Comment by Mimi87-stack** [comment]
> Hi. Can't reproduce with AdGuard Base + AdGuard French filters in Safari on iOS. Our filters have the necessary rules.

Hi, I’m using Brave, not Safari.

Adguard French filters only on top of Brave default filters so no Adguard base filters.

**Comment by Alex-302** [comment]
@Mimi87-stack Please test in user rules:
`||do69ll745l27z.cloudfront.net^`

**Comment by Mimi87-stack** [comment]
> @Mimi87-stack Please test in user rules: `||do69ll745l27z.cloudfront.net^` Another possible solution `ecranlarge.com##div[class^="cgAdSlot-"]` But it the first rule does not work - the problem is with Brav, because this rule is from Easylist.

Hi, the first rule works.

Could you add it to the French list?

**Comment by Alex-302** [comment]
This rule is from EasyList. It must be used by default in Brave.
