### ISSUE TITLE
IMDB android app: ads in video player

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#1899]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=48460253

**Comment by Alex-302** [comment]
Не повторяется вроде. Запросил информацию.

**Comment by ameshkov** [comment]
@Alex-302 let's return to this issue.

So, what's going on: Adguard often breaks IMDB video player. I suppose it happens when AG blocks video ads.

Relevant discussion:
https://forum.adguard.com/index.php?threads/adguard-pwned-by-imdb.6791/#post-100607

**Comment by Alex-302** [comment]
Can't reproduce. Tried few videos from the main page and Video category.

**Comment by ameshkov** [comment]
Kek, weird thing is that now I cannot reproduce it as well:)

Let's close this issue then.
