### ISSUE TITLE
The rules have not been updated

### ISSUE THREAD

**Issue by wolaikk** [AdguardTeam/AdguardFilters#189961]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

The rules have not been updated
![屏幕截图 2024-09-30 184449](https://github.com/user-attachments/assets/ca8d5e82-79ce-4fe2-911a-5a8796f960cd)

### Proposed solution

update rules

**Comment by Yuki2718** [comment]
I have no idea what is requested here.

**Comment by wolaikk** [comment]
> I have no idea what is requested here.

Already fixed  please close
![8a6da88bd90d95fc32c50cc9b9c6e6fd](https://github.com/user-attachments/assets/80565a67-339f-4556-a1ec-f995f98233ad)
thanks you
