### ISSUE TITLE
Plant Nanny - black placeholder

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1900]
Hi, I enabled HTTPS filtering but noticed after doing so, at least two apps were suddenly showing the place holders for where ads should be located where as before, in addition to seeing no ads, the placeholders were not visible. In disabling HTTPS filtering, the two aps were went back to not showing any placeholders

https://play.google.com/store/apps/details?id=com.fourdesire.plantnanny&hl=ru

Before enabling Adguard with HTTPs filyering <details>
![image](https://cloud.githubusercontent.com/assets/15856304/14211714/36b2f1da-f838-11e5-8774-9d006ca35fa0.png)
</details>
After <details>
![image](https://cloud.githubusercontent.com/assets/15856304/14211725/45bcea82-f838-11e5-9df2-9a4cb7865394.png)
</details>

**Comment by evgeniy-ADG** [comment]
The first one is https://github.com/AdguardTeam/ExperimentalFilter/issues/1887

**Comment by Alex-302** [comment]
I reproduced it only once. Please check with
```
@@||googleads.g.doubleclick.net/mads/gma?request_id=
@@||androidads21.adcolony.com/configure?app_id=
@@||live.chartboost.com/api/config
```
