### ISSUE TITLE
susanhavekeep.com

### ISSUE THREAD

**Issue by klik1991** [AdguardTeam/AdguardFilters#190237]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

adguard for widows 

### What type of problem have you encountered?

Website or app doesn't work properly, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Opera

### Which device do you use?

Desktop

### Where is the problem encountered?

susanhavekeep.com##div:nth-child(7) > div.guestMode:nth-child(4)

### Ad Blocking

AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, Legitimate URL Shortener

### Annoyances

AdGuard Popups filter

### Security

NoCoin Filter List

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
What's wrong?

**Comment by klik1991** [comment]
please fix it doesn't block ads on voe.sx


pt., 4 paź 2024 o 12:31 zloyden ***@***.***> napisał(a):
