### ISSUE TITLE
Google Cloud Next website not loading

### ISSUE THREAD

**Issue by zefwef** [AdguardTeam/AdguardFilters#19030]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://cloud.withgoogle.com/next18/sf/ will not load with Adguard for Mac turned on, but does load with Adguard turned off.

**Filters:**

[//]: # English, Spyware

Information                            | Value
---                                    | ---
Operating system:                      | macOS
Operating system version (Android/iOS) | 10.14
Browser:                               | Chrome
AdGuard version:                       | 1.5.8
Filters enabled:                       | English, Spyware
AdGuard DNS:                           | None

**Comment by Alex-302** [comment]
Temporary solution - add `firestore.googleapis.com` to HTTPS exclusions.

**Comment by zefwef** [comment]
In general, is there an easy way to determine which site I should add to the exclusions list? Just in case  something like this comes up again in the future.

**Comment by Alex-302** [comment]
No. The site can be broken by incorrect blocking. But not in this case.
Just report about the issues and we will help you:)

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/HttpsExclusions/commit/d1d3f3d8e38fab145e7cfd8181587640932945ed
