### ISSUE TITLE
Please add instantmessaging-pa.googleapis.com to the default HTTPS exclusions list

### ISSUE THREAD

**Issue by zefwef** [AdguardTeam/AdguardFilters#19031]
***Description***: Many commonly used Google services like messages.android.com and allo.google.com/web will not function if instantmessaging-pa.googleapis.com is not added to the HTTPS exclusions list on Adguard for Windows/Mac. Please make it a part of the default list.

Information                            | Value
---                                    | ---
Operating system:                      | macOS
Operating system version (Android/iOS) | 10.14
Browser:                               | Chrome
AdGuard version:                       | 1.5.8
Filters enabled:                       | English, Spyware
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by zebrum** [comment]
https://github.com/AdguardTeam/AdguardForMac/issues/320
https://github.com/AdguardTeam/AdguardForWindows/issues/2266

will be added soon
