### ISSUE TITLE
solarmoviesc.co [Pop-up] [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#19045]
**Site**: https://solarmoviesc.co/snowbound/?action=watching

**Issue**: Please remove the fake links & pop-ups on the page.
 
**Screenshot**: http://prntscr.com/k15p3b

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 67.0.3396.99 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Fixed popup, no ads seen and screenshot site is not opening.

**Comment by Nzzyme** [comment]
I think the server where the screenshot was hosted was down. Can you check again. I am able to see it. Also checked on Android now and see the fake links. Can you please fix that. thank you.

**Comment by BlazDT** [comment]
Added rule.

**Comment by Nzzyme** [comment]
Not sure why, but now after I tap on play, the screen goes dim and the page is not accessible. Did the video play on Android for you after applying the latest filter update?

**Comment by BlazDT** [comment]
Just tried and video works fine, try restarting your Android device.
