### ISSUE TITLE
solarmoviesc.org [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#19046]
**Site**: https://solarmoviesc.org/watch/jurassic-world-2015.html

**Issue**: Please remove the fake links & possible pop-ups on the page.
 
**Screenshot**: http://prntscr.com/k15qo3

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 67.0.3396.99 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
No popups reproduced, screenshot site was not opening, I hope I got the bad links though.

**Comment by Nzzyme** [comment]
Ok. Checked on Android and see the fake link. Can you fix that please. Thank you.

**Comment by Alex-302** [comment]
fixed
