### ISSUE TITLE
com.dragon.read

### ISSUE THREAD

**Issue by Shura23** [AdguardTeam/AdguardFilters#190436]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7nightly 12

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://ugapk.com/5Qdh?channel_from=zlink

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Fanboy's Enhanced Tracking List, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social Widgets

AdGuard Social Media filter

### Other

AdGuard Experimental filter

### DNS filters

AdGuard DNS filter

### Language-specific

AdGuard Chinese filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals

### Add your comment and screenshots

我是想要提供几条规则到adguard dns过滤器中，经过我的测试，拦截广告有效。我使用番茄小说APP时，每隔一段时间便有广告出现，你们现在的规则对这个APP无效。番茄小说APP的下载链接是https://ugapk.com/5Qdh?channel_from=zlink
我想要提供的规则是  ||zijie*   和  ||frontier100-toutiao-lf.fqnovel.com^。
没有使用上面两条规则拦截时：
[微信图片_20241007230501](https://github.com/user-attachments/assets/d3d984ed-644c-4621-b83b-44044a2f23ec)
使用上面两条规则拦截时：
[微信图片_20241007230510](https://github.com/user-attachments/assets/91462959-60bb-4a0c-9922-d1ec27570a28)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Cannot install, because Android rejects it as dangerous.
Added `||frontier100-toutiao-lf.fqnovel.com^`

**Comment by Shura23** [comment]
> Cannot install, because Android rejects it as dangerous.
> Added `||frontier100-toutiao-lf.fqnovel.com^`

||zijie*  This rule is the most important rule, blocking the most ads.You should add this rule

**Comment by Alex-302** [comment]
@Shura23 It is too wide. Need full domain name.

**Comment by Shura23** [comment]
> @Shura23 It is too wide. Need full domain name.

Hello, I have provided the complete domain name, have you added to the dns filter?

**Comment by Alex-302** [comment]
Ok, added some domains.

pglstatp-toutiao.com is already blocked.

**Comment by Shura23** [comment]
> Ok, added some domains.
> 
> pglstatp-toutiao.com is already blocked.

In addition to this one, have other items been added？

**Comment by Alex-302** [comment]
Check after an hour. Then clear the filtering log, reproduce, and make screenshots of the log, when you search for `zijieapi.com`

**Comment by Shura23** [comment]
> Check after an hour. Then clear the filtering log, reproduce, and make screenshots of the log, when you search for `zijieapi.com`

I updated the filter to the latest, intending to reproduce the scene. But I found nothing intercepted. Invalid filter rule.![Screenshot_20241011_210246_com.adguard.android.jpg](https://github.com/user-attachments/assets/3e544d58-bf65-44f9-8ae3-4dd71f86fcb6)

**Comment by Shura23** [comment]
> Check after an hour. Then clear the filtering log, reproduce, and make screenshots of the log, when you search for `zijieapi.com`

I noticed you made a mistake in one rule.Like you wrote about ||ads*-normal-hl.zijieapi.com^ ，

but actually it should be
||ads*-normal-lf.zijieapi.com
That's why I feel like there are ads, and some requests are not blocked

**Comment by Shura23** [comment]
> Check after an hour. Then clear the filtering log, reproduce, and make screenshots of the log, when you search for `zijieapi.com`

After you fix the wrong rule, help me solve this problem. Waited for days without processing.

https://github.com/AdguardTeam/AdguardFilters/issues/190503

**Comment by Shura23** [comment]
> Check after an hour. Then clear the filtering log, reproduce, and make screenshots of the log, when you search for `zijieapi.com`

I don't understand why you added this rule ||ad.zijieapi.com^  Does this rule block the domain name I provide?

And your second rule is wrong in the middle.

||ads*-normal-hl.zijieapi.com^Should be changed to  ||ads*-normal-If.zijieapi.com^

**Comment by Alex-302** [comment]
Updated to `||ads*-normal-*.zijieapi.com^` and `||mssdk*.zijieapi.com^`
The purpose of another domains is unclear.
