### ISSUE TITLE
hdpicture.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1904]
Link - http://hdpicture.ru
Screenshots - http://imgur.com/xhAYefe
Reporter - LQE-527-80335

**Comment by Alex-302** [comment]
It is blocked now.
User shoulв to check again after filters update.

**Comment by vgavrish** [comment]
http://hdpicture.ru/3/
Мозилла, Хром
Фильтры: 1,2,3,4,14
при нажатии на кнопку "войти" сразу открывается другой сайт
<details>
![screenshot_26](https://cloud.githubusercontent.com/assets/18548949/18229442/448fc5b6-7282-11e6-837f-e9b8c0811c72.jpg)

</details>
допустим при нажатии на Название чтобы открыть, тут же появляется какое ни будь окно с  рулетками и тд..
<details>
![screenshot_27](https://cloud.githubusercontent.com/assets/18548949/18229443/48ed5c7c-7282-11e6-917f-4b920388d7af.jpg)

</details>

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
hdpicture.ru#%#Object.defineProperties(window, { "_impspcabe_alpha": { value: false, writable: false }, "_impspcabe_beta": { value: false, writable: false } }); 
```

**Comment by vgavrish** [comment]
http://hdpicture.ru
Слева две колонки рекламы. + при нажатии на какой-то фильм, чтобы открыть его, всплывает окно
Ф: 1,2,3,4,14
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/19959577/81723646-a1b0-11e6-8fda-855aeea62fe6.png)

![image](https://cloud.githubusercontent.com/assets/18548949/19959587/8ef211e2-a1b0-11e6-830d-18687822ef1b.png)

![image](https://cloud.githubusercontent.com/assets/18548949/19959591/9b51e9a8-a1b0-11e6-8ca6-81ce79a3d03d.png)

**Comment by Alex-302** [comment]
Повторился только баннер слева.
Добавил в русский фильтр
```
||idaschop.ru^$third-party
||itempana.site^$third-party
```
