### ISSUE TITLE
sonixgvn.net

### ISSUE THREAD

**Issue by moemoe900** [AdguardTeam/AdguardFilters#190517]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

5.0.128

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://sonixgvn.net/dark/?aHR0cHM6Ly9yaW5rdS5tZS9scmlubkxL

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. <comment>
Hi
So, I want to open the [URL](https://sonixgvn.net/the-idolmaster-million-movement-of-stardom-road-03-hypernova/) and click the blue box provided. But, it seems the supposed countdown timer to proceed to the external site is disappeared unless I disabled the extension. What do you think?
2. Screenshots
<details><summary>Screenshot 1:</summary>
<img width="868" alt="image" src="https://github.com/user-attachments/assets/2d958972-ab29-4802-9fb9-daf8df6945f7">

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
This link is hidden when website detects ad blocker.
Fixed again, filters update should be available in 1-2 hours.
