### ISSUE TITLE
Can’t attach screenshot on report.adguard.com/new_issue.html

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardFilters#190573]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.5.5

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://reports.adguard.com/en/new_issue.html?browser=Safari&clid=jqaSCv--oF9Szp--XdOtMa--vUhwzs--htvRrW--THmzAw--HfSG0T--QXQ2SO--UgJQqu--U4X6UL--H0P2rq--ycDVq6--13UKa9--Jvyqz0--qkeDgd--FFXp5E--Lbl3I4--lYwxlc--D8RfgV--fY1sxj&filters=2.11.3.4.18.19.20.21.22.1&product_type=iOS&product_version=4.5.5&url=https%3A%2F%2Fvkusvill.ru%2Fgoods%2Fchipsy-kartofelnye-pringles-paprika-165-g-78991.html&utm_campaign=report&utm_medium=action_extension&utm_source=ios

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

1. I can't attach a screenshot on https://reports.adguard.com/new_issue.html

2. Screenshots
<details><summary>Screenshot 1:</summary>

![IMG_6117](https://github.com/user-attachments/assets/9ab2d732-3f04-4d6a-863c-e961fd83883d)

</details>

There is the screenshot which I can't attach:
<details><summary>Attached screenshot:</summary>
<p>

![IMG_6116](https://github.com/user-attachments/assets/ff299e11-af55-4ebc-9365-10dce9847f26)

</p>
</details> 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Не повторилось.
Если ещё не загружаются - напиши в https://github.com/AdguardTeam/ReportsWebApp и дай ссылку. Передам разработчикам.

**Comment by Alex-302** [comment]
Ну заведи там ишью, проверим. К фильтрам это не относится.

**Comment by Alex-302** [comment]
Ок.
