### ISSUE TITLE
online-fix.me

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#190697]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://online-fix.me/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

these domains appear in my dns log:

tds.mediapays.info
dotofverse.com
trutheyesstab.com
myroledance.com

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
forgot to mention these arent analytics they are spam/ad domains

**Comment by jellizaveta** [comment]
@jordansworld Hello. On which websites/app I can check these domains?

**Comment by jordansworld** [comment]
they appeared when i went to any page on the site. example: https://online-fix.me/games/shooter/17452-bodycam-po-seti.html

**Comment by jordansworld** [comment]
@Alex-302  can u reproduce

**Comment by jellizaveta** [comment]
Thanks, found. Added

**Comment by jordansworld** [comment]
@jellizaveta looks like they already added another. botradar.tech are you able to reproduce?

**Comment by jordansworld** [comment]
@Alex-302

**Comment by Alex-302** [comment]
I can't reproduce. Need a HAR

How to get a HAR file:
https://toolbox.googleapps.com/apps/har_analyzer/

**Comment by jordansworld** [comment]
is there a way to capture a har file on android or no? i dont have a pc at the moment

**Comment by jordansworld** [comment]
where do i find the file after? sorry @Alex-302

**Comment by Alex-302** [comment]
In exported logs) In archive.

**Comment by jordansworld** [comment]
i turned it on visited site then turned it off. still dont see a har file from today
![Screenshot_20241023_111207_My Files](https://github.com/user-attachments/assets/d3ebb7d9-3b5d-4c20-b626-cef55555b953)

**Comment by jordansworld** [comment]
got it

https://easyupload.io/u04isj

**Comment by jordansworld** [comment]
let me.know if it isnt in there it doesnt show that domain when i do secret mode in my browser so i might have to redo

**Comment by jordansworld** [comment]
https://easyupload.io/ckbqi6

**Comment by jordansworld** [comment]
@Alex-302

**Comment by Alex-302** [comment]
Invalid HAR, can't be opened. Did you stop protection before export?
