### ISSUE TITLE
samsungads.com: should be block from dns level

### ISSUE THREAD

**Issue by 3xploiton3** [AdguardTeam/AdguardFilters#190765]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

latest

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

samsungads.com

### Ad Blocking

AdGuard Base filter

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

![image](https://github.com/user-attachments/assets/796bc091-fcd9-4a14-bb02-e162034ee895)

using dns 94.140.14.14 port 5353

another domain should be block
click.googleanalytics.com
app.getsentry.com

![image](https://github.com/user-attachments/assets/e54f98fe-5f1a-4f41-babe-238c8fdef01a)

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Please post website where ads are shown from those domains (this test page does not count).
