### ISSUE TITLE
domains that shouldn't be blocked

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#191074]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.67

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

n/a

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

the below are used for error reporting:

android.bugly.qq.com
ios.bugly.qq.com
astat.bugly.qq.com
error-tracking.reddit.com

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
They don't ask about it 🤷🏻‍♂️
