### ISSUE TITLE
samsung tracker

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#191001]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.67

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

n/a found in log

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

tracker: analytics.bigdata.samsung.com

### Privacy

- [X] I agree to follow this condition

**Comment by DandelionSprout** [comment]
The report doesn't seem to mention the app and/or site where the tracker comes from. I know first-hand that AdGuard for Android supports app icons in the log to some extent, even if that mechanism works far from perfectly.

**Comment by jordansworld** [comment]
sorry found this on nextdns logs i dont know the origin

**Comment by Alex-302** [comment]
Maybe some device (TV or a phone)
