### ISSUE TITLE
vkopt extension for Firefox issue: blocked buttons, falsely hidden widgets

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1910]
![image](https://cloud.githubusercontent.com/assets/15856304/14243891/bfde4d22-fa60-11e5-91a3-544cae10c704.png)

Когда заходишь во вкладку аудиозаписи ВКонтакте, то на главном плеере не работают клавиши все клавиши в красном квадрате, а вместо их появляется миниатюрный плеер. Пробовал выключать вышеупомянутое дополнение для мозилы и релогать компьютер = ничего не помогает. Только выключение adguard и перезагрузка браузера помогает решить данную проблему (что с включённом VKopt'ом, что с выключенным). Выключал "антибаннер" в настройках, его выключение помогало, но какой из всех фильтров так действует на ВКонтакте я не смог выяснить. 

![image](https://cloud.githubusercontent.com/assets/15856304/14243938/0bcad25a-fa61-11e5-8253-22b2d508acfb.png)

Суть в том, что Adguard блокирует виджеты данного приложения (такие как: календарь, время, расширенные ссылки и т.д) Если отключить "Русский фильтр" то проблема исчерпается, но появляется реклама на других сайтах... Добавьте "vkopt" в исключения данного фильтра

**Comment by Alex-302** [comment]
@evgeniy-ADG 
нужен список фильтров, и описание настроек скрипта. которыми включаются виджеты.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
bump
