### ISSUE TITLE
golf-live.at

### ISSUE THREAD

**Issue by alextiang** [AdguardTeam/AdguardFilters#191113]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

Adguard for iOS (4.5.5)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.golf-live.at

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

Steps to reproduce: 
- After updating the AdGuard filter, I accessed Golf-live and stayed on the site for **10 seconds**, then suddenly the error message appeared. It seems to occur only on iOS Safari.

When the error message appeared, I contacted support, and they confirmed that the issue was caused by the .xyz/fl1hrrg/$popup filter. After excluding this filter, the problem no longer occurred. It seems like it would be a good idea to remove this filter.

<details>
<summary>screenshot 1</summary>

![image](https://github.com/user-attachments/assets/d4531246-1246-46ba-a483-11ee300f6964)

</details>

<details>
<summary>screenshot 2</summary>

![image](https://github.com/user-attachments/assets/cebd4837-6d81-41b4-a318-03f83d7fc569)
</details>

<details>
<summary>When add filter rule</summary>

![image](https://github.com/user-attachments/assets/5c5718f6-efc8-40b8-a0ff-2de3a2a7efd4)

![image](https://github.com/user-attachments/assets/683e280f-bb29-41a2-913b-6d580c2bf170)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
