### ISSUE TITLE
TD Bank iOS app - false blocking

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#19113]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Current behavior***: 

The [TD Bank app](https://itunes.apple.com/us/app/td-bank-us/id382107453?mt=8) does not work when AdGuard is enabled but when AdGuard is disabled the app works just fine. User 1814440 found out that whitelisting the following domains helps (the support ticket contains logs)

```
h-sdk.online-metrix.net
ads.tdbank.com
```
[//]: # (Substitute this line with a description of the problem)

***Expected behavior***: 

The banking app is not blocked by AdGuard

***System configuration***

- iOS 11.3.1
- AdGuard 2.1.1.165

PRO:

- Pro feature ENABLED.
- Tunnel mode FULL
- DNS server: Cloudfare
- 1.1.1.1
- 1.0.0.1

DnsCrypt: 0

System wide blocking subscriptions: 
name: AdGuard SDN filter url: https://filters.adtidy.org/ios/filters/15_optimized.txt last update: 6/30/18, 6:25 PM
name: AdAway default blocklist url: https://adaway.org/hosts.txt last update: 6/30/18, 6:24 PM
name: Raw Hosts url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts last update: 6/30/18, 6:25 PM

**Comment by Eugene-Savenko** [comment]
Yes. I can't test it myself as I have no access to the app.

**Comment by Alex-302** [comment]
@Eugene-Savenko please ask user to check without `ads.tdbank.com` whitelisting.
