### ISSUE TITLE
isohuntx.com

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#191282]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.67

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://isohuntx.com/torrent/?ihq=h

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

vpn warning

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
cant tell if this is an ad domain or not:

matomo.hellohi.me

**Comment by Alex-302** [comment]
No traffic.
