### ISSUE TITLE
duden.de adblocker detection

### ISSUE THREAD

**Issue by samo-1** [AdguardTeam/AdguardFilters#191464]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

N/A

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.duden.de/rechtschreibung/Balkonkraftwerk

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Annoyances

AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

![image](https://github.com/user-attachments/assets/c7b674b8-3fc0-4992-ae53-7c01f8510cbb)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@BlazDT Please take a look.

**Comment by BlazDT** [comment]
This is a paywall
