### ISSUE TITLE
Facebook feed do not update, can't send messages through Whatsapp and download from google play

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1915]
Hi Team., I started Adguard with detailed logging (Record Everything). I tried facebook feed update which is not updated. I try to send a WhatsApp message that's not sent till. 

As per the last conversation I Download The Beta Version And Reproduce The Same Issues. Facebook Update Not Happening, Can't Send Messages Through WhatsApp, Start A Game Which Is Connected With FB That Also Not Synced With FB, Can't Download Apps From Play Store. On Top Of That I Am Not Able To Send Ad Guard Feedback. So I Uninstall Beta Version And Send Through Current Active Version.

**Comment by evgeniy-ADG** [comment]
NKE-829-27658 - there're 2 sets of logs. Could you please check what's going on there? Of course, it all works fine on our side.

**Comment by evgeniy-ADG** [comment]
Doze mode, most likely, unfortunately the customer ignores our recommendations to disable Doze for ADG. Will reopen if needed.

**Comment by macrovijay** [comment]
Hi evgeniy.,
          I Got The To Disable The Doze Mode For My First Query Itself And I Did The Same. Kindly Check The Logs And Provide Me The Solution.

**Comment by evgeniy-ADG** [comment]
@macrovijay thank you!
@Alex-302 could you please check?

**Comment by Alex-302** [comment]
macrovijay, I can't reproduce your issue.
Could you please try to disable firewall and chack again? Maybe these apps blocked by it.
Also you can try to disable all filters, but don't turn off Adguard.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
у тебя повторяется? Есть ли аналогичные жалобы?

**Comment by macrovijay** [comment]
Hi Mr. Alex-302.,  Asper Your Suggestion I Tried Disabling Firewall And All Filters. But Unfortunately I Am Not Get A Positive Result. Still It's Not Allowing To Anything.

**Comment by Alex-302** [comment]
@macrovijay 
please try to go to ```Advanced settings > Low level ->pref.net.explusions```
and package name of Facebook app. It looks similat to ```com.facebook.orca```
you can find package name in Firewall when tap on the app

**Comment by evgeniy-ADG** [comment]
@Alex-302 нет, не повторяется. тут какое-то комбо просто. может, его куда-то в адрагрд для андроид перенести? там куча дебажньіх логов от юзера есть.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
давай подождём ответа про pref.net.explusions
Уточни откуда юзер, может у них сеть как-то особенно работает.
