### ISSUE TITLE
lernu.net

### ISSUE THREAD

**Issue by tbodt** [AdguardTeam/AdguardFilters#191682]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.60.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://lernu.net/kurso/nakamura/3/12 (requires login)

### Ad Blocking

AdGuard Base filter, EasyList

### Social Widgets

AdGuard Social Media filter

### Add your comment and screenshots

1. They are matched by the `##input.vk` rule but they are just text fields that happen to have `vk` class.

2. Screenshots
<details><summary>Screenshot 1:</summary>

<img width="365" alt="image" src="https://github.com/user-attachments/assets/9fcb4501-bd2c-4efc-b8dc-d37f23145b66">

</details>

<details><summary>Screenshot 2:</summary>
<img width="1114" alt="image" src="https://github.com/user-attachments/assets/7a970b12-b215-4998-980e-5327191f5e4d">
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
