### ISSUE TITLE
VSCode Marketplace

### ISSUE THREAD

**Issue by panty-sniffer** [AdguardTeam/AdguardFilters#191872]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

N/A

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://marketplace.visualstudio.com

### Ad Blocking

EasyList

### Add your comment and screenshots

Collects data in the background without respecting your cookie preferences. (MS being MS 🙃)

### Fix

```
||marketplace.visualstudio.com/_apis/*/stats
||marketplace.visualstudio.com/_apis/ClientTrace/
||marketplace.visualstudio.com/_apis/customerintelligence/
```

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
Another one; https://marketplace.visualstudio.com/_apis/customerintelligence/Events

**Comment by panty-sniffer** [comment]
> Another one; https://marketplace.visualstudio.com/_apis/customerintelligence/Events

That's covered by `||marketplace.visualstudio.com/_apis/customerintelligence/`, no?

**Comment by jordansworld** [comment]
oh my bad didnt see that
