### ISSUE TITLE
gitlab.com

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#191959]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.76

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gitlab.com/W1nst0n/universal-android-debloater

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

snowplow.trx.gitlab.net (snowplow is analytics)

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
@jordansworld 
Can you still reproduce the request? It is not shown.

**Comment by jordansworld** [comment]
yes 
![Screenshot_20241104_105031_AdGuard](https://github.com/user-attachments/assets/344eed23-e17c-41c8-9fed-c9fb35119a2a)

**Comment by BlazDT** [comment]
That is an app, not a website though.

**Comment by jordansworld** [comment]
no its a website.

**Comment by jordansworld** [comment]
![Screenshot_20241104_110619_AdGuard](https://github.com/user-attachments/assets/dbabe7fe-d700-4469-8b27-f5b286f3d49e)

**Comment by BlazDT** [comment]
Not requested here. Screenshot shows DNS request, but no browser request.

**Comment by jordansworld** [comment]
its because its blocked in my custom block list sorry

**Comment by BlazDT** [comment]
You see it as browser request when unblocked?
