### ISSUE TITLE
spam/malware domains

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#191963]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.76

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

see description below

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

to reproduce go to warez-bb.org and it will redirect with two different spam sites. ucureo.com and secrity2redline.com. i have seen a couple parked domains redirect to those domains so i think those two domains should be blocked

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
![image](https://github.com/user-attachments/assets/ab840e77-4e0b-474e-835a-830a9c5be110)

**Comment by jordansworld** [comment]
your dns is probably blocking warez-bb.org because mine redirects to ucureo.com i just tested jt.

https://github.com/user-attachments/assets/46ee1bd0-f040-463d-b959-7be0f05f86aa

**Comment by jordansworld** [comment]
@Alex-302
