### ISSUE TITLE
movieblog.to

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#191900]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.76

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://movieblog.to/venom-3-the-last-dance-2024-german-ac3-ld-tsrip-x264-ldo/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

fake download links and ad 
![Snapchat-893489298](https://github.com/user-attachments/assets/d2a1de9c-6680-4512-aa16-cbb8ceebc49e)

https://movieblog.to/venom-3-the-last-dance-2024-german-ac3-ld-tsrip-x264-ldo/

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
fake buttons still there

**Comment by AdamWr** [comment]
It's German website.
Do you have `AdGuard German filter` enabled?

**Comment by jordansworld** [comment]
oh im sorry. its gone now thanks! :)
