### ISSUE TITLE
skidrowcpygames.com

### ISSUE THREAD

**Issue by andris86** [AdguardTeam/AdguardFilters#191962]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

mv2 latest

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Desktop

### Where is the problem encountered?

skidrowcpygames.com

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Other Annoyances filter

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Chinese filter, AdGuard Russian filter

### Add your comment and screenshots

Human verification scam. Clicking button shows 4 different options, every one of them seems suspicious.

Chat messages and usernames are fake, look in page's source (ctrl  + u).

https://skidrowcpygames.com/password02/
https://skidrowcpygames.com/password01/

Reporting here because reporting tool is failing to submit the report (429 error).

<details><summary>Screenshots:</summary>

![Screenshot (277)](https://github.com/user-attachments/assets/2cb21018-2075-488b-bbc8-e7261a3ca02d)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Blocked.

**Comment by shahrukhsk699-ui** [comment]
<img width="1859" height="950" alt="Image" src="https://github.com/user-attachments/assets/ab0eeeae-8608-44b9-9b26-cd219c441f85" />

**Comment by Alex-302** [comment]
Now this is just a parked domain.

<img width="451" height="340" alt="Image" src="https://github.com/user-attachments/assets/9dea58ce-aa00-4ad4-8e4c-57451ced8fa8" />
