### ISSUE TITLE
na-ab31.marketo.com

### ISSUE THREAD

**Issue by curlingchimpanzeeowl** [AdguardTeam/AdguardFilters#192046]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.60.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

Email from `noreply@bitbank.cc`

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

AdGuard Tracking Protection filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Block WebRTC

### Add your comment and screenshots

1. An image that should not be blocked is erroneously blocked. `https://na-ab31.marketo.com/rs/bitbankincsandbox/images/M_bitbank_logo_640_264.png`

3. Screenshots
<details><summary>Screenshot 1:</summary>

![screenshot](https://github.com/user-attachments/assets/623cd9ad-d110-4a01-b2bd-a8c9ed2cf2a4)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Add steps to reproduce.
