### ISSUE TITLE
filepress.skin

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#192007]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.76

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play1.kirastream.my.id/page-download/?to-dlink=https://new1.filepress.skin/file/650d27a9745975af035693f0

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

fake buttons
![Snapchat-215799075](https://github.com/user-attachments/assets/4f6dbffc-add9-44e5-80fa-d26c72e47654)

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Could you please send the original link? Link is invalid now.

**Comment by jordansworld** [comment]
original website isnt loading sorry
