### ISSUE TITLE
[iOS] apfelpage.de

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1920]
http://www.apfelpage.de
![image2 png](https://cloud.githubusercontent.com/assets/14153331/14303312/48f3f83a-fbb2-11e5-9f09-abd6b8e7c4ed.jpeg)
UOK-262-13463

**Comment by evgeniy-ADG** [comment]
1. Install adguard from App-Store and open the app
2. Activate adguard for Safari iOS (see settings)
3. Go to apfelpage.de
4. Disable aduguard and activate adguard again see settings
5. reload the apfelpage.de site, 
6. mostly comes this ad banner, this is wrong. adguard is on.

**Comment by Alex-302** [comment]
added to safari filter
```
apfelpage.de##.a4promo_ad
konachan.net##iframe[src^="https://tbib.org/"]
```

**Comment by evgeniy-ADG** [comment]
@Alex-302 it looks like it's not fixed:

<details>
again adguard app has problem and not the filter.

so works install adguard,activate in safari conten blocker setting the app, go to website, no banner here.

with this method is banner not gone:
loading adguard from app store, disable and activate adguard in safari content blocker settings. and go to the site, it comes this banner. this is bug, adguard is on. I think extension error or background bug. please test again

**Comment by Alex-302** [comment]
@evgeniy-ADG 
не вижу списка его фильтров в тикете. Можешь попросить? С Английским, немецким и фильтром Сафари у меня чисто.
