### ISSUE TITLE
voe.sx/toddpartneranimal.com

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#192135]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.76

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://voe.sx/e/n53cgof21y3t

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

popup when clicking play

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed in https://github.com/AdguardTeam/AdguardFilters/commit/4ddb70a28084ede50728170c21ae81ef5b97d80a (filters update should be available in 1-2 hours).
