### ISSUE TITLE
uploadhive.com

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#192140]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.76

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://uploadhive.com/b8sccsfiyjmj

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

red button is fake on first page. then wait for timer to countdown and click green button you will see another fake red button

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please use reporting tool instead of the issue template.
