### ISSUE TITLE
volt-index.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#19219]
[https://volt-index.ru/electronika-dlya-nachinayushih/interesnoe/delaem-sverhdalnyuyu-wifi-antennu.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fvolt-index.ru%2Felectronika-dlya-nachinayushih%2Finteresnoe%2Fdelaem-sverhdalnyuyu-wifi-antennu.html)

 Защита от копирования. Почти то же самое, что и в #19217 - не работают кнопки мыши: левой не выделить, прокрутка страницы, при нажатии средней, не срабатывает, контекстное по правой не вылазит.

 Пробовал тоже правило с форума (адаптировал): `volt-index.ru#%#AG_onLoad(function() { document.onmousedown = document.oncontextmenu = document.ondragstart = document.onselectstart = function() {}; });`
 Всё начинает работать, и даже выделение, но, НЕ копирует выделенное (не мышкой, не клавишами).
<details><summary>Код со страницы, отвечающий за запреты:</summary>

```
<script type="text/javascript">/**/
            document.oncontextmenu = function() {
                return false;
            };
            document.onselectstart = function() {
                if (event.srcElement.type != "text" && event.srcElement.type != "textarea" && event.srcElement.type != "password") {
                    return false;
                }
                else {
                    return true;
                }
            };
            if (window.sidebar) {
                document.onmousedown = function(e) {
                    var obj = e.target;
                    if (obj.tagName.toUpperCase() == 'SELECT'
                            || obj.tagName.toUpperCase() == "INPUT"
                            || obj.tagName.toUpperCase() == "TEXTAREA"
                            || obj.tagName.toUpperCase() == "PASSWORD") {
                        return true;
                    }
                    else {
                        return false;
                    }
                };
            }
            document.ondragstart = function() {
                return false;
            };
            /**/</script>
```
</details>

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.9.2 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
там два скрипта
