### ISSUE TITLE
Bad Piggies app hangs when HTTPs filtering is enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1922]
https://play.google.com/store/apps/details?id=com.rovio.BadPiggies&hl=en

record everything logs: ATW-714-13887

**Comment by evgeniy-ADG** [comment]
По моему зависание происходит на момнт попытки приложения показать рекламный видео ролик подгружаемый из интернета. Проявляется следующим образом - после прохождения уровня (это может быть 1 ур или какой нибудь другой) появляется "чёрный" экран ( отсутсвие на мониторе какой либо информации), при этом сам планшет не виснет - есть возможность открыть другие приложения через верхнюю панель. Сбросить зависание удаётся перезагрузив планшет. (Для справки - данный дефект один к одному роявился и на смартфоне samsung i 9192).

**Comment by Alex-302** [comment]
@evgeniy-ADG 
передай на проверку
```
||static.applifier.com/impact/videos/*.mp4$mp4
```

**Comment by evgeniy-ADG** [comment]
Передал.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
ну что там?
