### ISSUE TITLE
facebook netseer

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#192267]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7.83

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

facebook

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

netseer-ipaddr-assoc.xy.fbcdn.net
netseer-ipaddr-assoc.xz.fbcdn.net
netseer.xy.fbcdn.net
netseer.xz.fbcdn.net
ns.xy.fbcdn.net
traffic-nts-ip-assoc.xy.fbcdn.net
traffic-nts-ip-assoc.xz.fbcdn.net
sonar6.xy.fbcdn.net

see here: https://github.com/hagezi/dns-blocklists/issues/3010

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
i have been testing with these filters and everything on facebook works still.

**Comment by Alex-302** [comment]
Where could I see these domains?

**Comment by jordansworld** [comment]
facebook app @Alex-302

**Comment by jordansworld** [comment]
i have been testing for days now. Nothing is blocked incorrectly everything works fine. if you dont feel comfortable adding the sonar one just add the ones with netseer or ns in the name

**Comment by jordansworld** [comment]
@Alex-302 have had these blocked for awhile  and nothing breaks. wanna add:

traffic-nts-ip-assoc.xy.fbcdn.net
traffic-nts-ip-assoc.xz.fbcdn.net
netseer-ipaddr-assoc.xy.fbcdn.net
netseer-ipaddr-assoc.xz.fbcdn.net
netseer.xy.fbcdn.net
netseer.xz.fbcdn.net
ns.xy.fbcdn.net

netseer by googling it shows it has to do with advertising. but understand if you dont wanna add them.

**Comment by Alex-302** [comment]
Not sure about these domains.

**Comment by jordansworld** [comment]
hey @Alex-302 ive had these blocked since november: 

traffic-nts-ip-assoc.xz.fbcdn.net
traffic-nts-ip-assoc.xy.fbcdn.net


literallt EVERYTHING on Facebook still works. they are definitely used for tracking purposes
