### ISSUE TITLE
down.playonpc.online/file-upload.org

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#192270]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7.83

### What type of problem have you encountered?

Website or app doesn't work properly, AdGuard gets detected on a website

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://down.playonpc.online/how-to-refinance-your-mortgage-and-save-money-in-the-long-run/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

this is a legit site. i disabled AdGuard completely and it redirects to https://www.file-upload.org/73c9w6l7o5h2 i cant figure out how to get it to work with adguard enabled though.

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I only see geo-blocking there, that is not related to AdGuard.
