### ISSUE TITLE
m.facebook.com: block attempt to open the application using the fb:// protocol

### ISSUE THREAD

**Issue by mpeter50** [AdguardTeam/AdguardFilters#192280]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Whenever the mobile facebook site is opened in a web browser, it always (or at least very often) makes the browser show a popup to open the website in the mobile facebook application, before any kind of other user interaction could happen.

When trying to emulate a mobile brower on the desktop, it looks like this:

![image](https://github.com/user-attachments/assets/ddd6a6d0-7498-4a4a-8203-d15623d1b1b4)

### Proposed solution

The popup is distracting, and cannot be set to never appear again.
I believe those who use facebook in a mobile web browser, and a content blocker like Adguard or uBO, they exactly know that they dont want to use the mobile app for privacy or other reasons.

In turn, I believe blocking any fb:// URLs from the ability to be opened could be a solution.
I'm not familiar enough with what your filtering engine is capable of, so I can't suggest a full solution.

**Comment by Alex-302** [comment]
I don't see such popup in mobile FF.
