### ISSUE TITLE
Hotstar app - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1923]
https://play.google.com/store/apps/details?id=in.startv.hotstar&hl=en

ASL-683-48070
QSS-906-54080
IAI-213-49573 - wating for http logs

**Comment by Alex-302** [comment]
I don't see ads. Need HTTPS log. Banner placeholder is builtin.

**Comment by Nzzyme** [comment]
This app does not load properly and unable to see any content after opening the app.

User Filters:

```
||graph.facebook.com/*/activities
||graph.facebook.com/*?fields=
||graph.facebook.com/adnw_sync
||graph.facebook.com/*mobile_sdk_gk
```

Filtering Log: https://ibb.co/HPx8YtY

Please check and provide proper anti-adblock rule(s).
