### ISSUE TITLE
onelink.me

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#192334]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7.83

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

polymarket-app.onelink.me

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

onelink is a link shortener. i think it should be unblocked. 

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
![Snapchat-1136965371](https://github.com/user-attachments/assets/dde5f0f4-2c7a-4ee9-93ac-0cbff84665ea)

**Comment by BlazDT** [comment]
Please subscribe to DNS filter and not filter directly.
