### ISSUE TITLE
AdGuard Base Filter breaks user rules at www.ebay.com

### ISSUE THREAD

**Issue by kriswilk** [AdguardTeam/AdguardFilters#192475]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS, AdGuard for Windows

### AdGuard version

7.19.0.4853

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.ebay.com/itm/186333967862 (or any other live listing)

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

_Issue #192269 was closed without resolving the actual problem. I don't know if maintainers will see my subsequent comments there, so I created this much more detailed issue report._

### SUMMARY

Particular user rules for www.ebay.com break only when the "AdGuard Base Filter" is enabled.

Follow the steps below to reproduce the issue. Conducting the same test with the same user rule in uBO works fine. This is specific to AdGuard Base Filter.

### STEPS TO REPRODUCE:

1. Make sure there are NO user rules
2. Make sure "AdGuard Base FIlter" is ENABLED
3. DISABLE AdGuard
4. Visit https://www.ebay.com/itm/186333967862 ... promoted content exists within a `<div>` with class `x-rx-slot`

<details><summary>Screenshot</summary>

![Screenshot 2024-11-07 092939](https://github.com/user-attachments/assets/3e816171-fa2f-4d03-b1ce-7d0228dbc998)

</details>

5. ENABLE AdGuard
6. Reload the test page ... promoted content still exists within a `<div>` with class `x-rx-slot`

<details><summary>Screenshot</summary>

![Screenshot 2024-11-07 093042](https://github.com/user-attachments/assets/8f3122af-82c6-428e-80b3-2e8217a2d3cc)

</details>

7. Now create a user rule `ebay.*##.x-rx-slot`
8. Reload the test page ... promoted content is now obfuscated, no longer with class `x-rx-slot`

<details><summary>Screenshot</summary>

![Screenshot 2024-11-07 093207](https://github.com/user-attachments/assets/87f44280-67df-4709-9f0b-70d43e1fa1b9)

</details>

9. TURN OFF the "AdGuard Base Filter"
10. Reload the test page ... the promoted content is blocked perfectly by the user rule

<details><summary>Screenshot</summary>

![Screenshot 2024-11-07 093732](https://github.com/user-attachments/assets/9c5dda30-da2d-4945-88a0-2423830794f9)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Update available in about 3-4 hours.

**Comment by kriswilk** [comment]
@BlazDT I suggest removing the filter for the specific content I was targeting. That content is likely useful to many users. I submitted PR #192487 to address this.

The anti-adblock fix is perfect. I've tested it already by adding the rules manually and it works. 👍
