### ISSUE TITLE
Get rid of JS rules against window.open

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#192412]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

We need to replace JS rules by scriptlets when it is possible.

### Proposed solution

The JS rules with `window.open_` / `window.open =` / `window.open=` must be remove or converted to the scriptlet syntax, if a rule still required.

**Comment by zloyden** [comment]
> The JS rules with `window.open_ / window.open = / window.open=` must be remove or converted to the scriptlet syntax, if a rule still required

It's done.
