### ISSUE TITLE
alexa tracker

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#192559]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7.83

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

alexa

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

alexa-hybrid-interaction-log-config-prod-na.s3.amazonaws.com

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Where can be checked? Alexa.com is another now.

**Comment by jordansworld** [comment]
it was from my alexa

**Comment by Alex-302** [comment]
Need steps to reproduce.

**Comment by jordansworld** [comment]
@Alex-302 this domain is reached to this day. it just randomly appears in my log. been blocked by hagezi for months with no issues

**Comment by Alex-302** [comment]
Ok, added.

**Comment by jordansworld** [comment]
@Alex-302 another one

kinstruments-measurements.s3-external-1.amazonaws.com (blocked by hagezi)

**Comment by Alex-302** [comment]
I don't see any info about this domain.
