### ISSUE TITLE
MX player - missed HTTPs ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1925]
Здравствуйте! С бета-версией тоже не блокируется. Кеш плеера чистил. Отчет 
из приложения, к сожалению, не отправляется, выдает ошибку, просит 
повторить попытку позже.

Я очистил кеш плеера, затем включил в адгарде "записывать всё", запустил 
плеер, поставил на паузу, мне показали рекламу гетттекси, и я даже 
перешел по ней для пущей убедительности. Высылаю лог.

MVW-101-49592

**Comment by Alex-302** [comment]
@evgeniy-ADG 
нужно время запуска приложения. Среди 30 тысяч строк сложно искать.
Фильтрация HTTPS у него похоже выключена, или сертификат не установлен.

**Comment by Alex-302** [comment]
Попроси юзера проверить настройки HTTPS, может у него сертификат удалён.
