### ISSUE TITLE
a-lohas.jp

### ISSUE THREAD

**Issue by olstice** [AdguardTeam/AdguardFilters#192521]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension

### AdGuard version

Version 4.4.41

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc., Dangerous site

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://a-lohas.jp/

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, Web Annoyances Ultralist, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### What Stealth Mode options do you have enabled?

Block WebRTC

### Add your comment and screenshots

1. <comment>
this site redirects you to spam urls everytime you try to click on something or try to go back to the original url
2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available soon.

**Comment by zloyden** [comment]
Note that AdGuard Japanese should be enabled.

**Comment by olstice** [comment]
> Fixed, update should be available soon.

when i select update it saids update not found?

**Comment by zloyden** [comment]
> when i select update it saids update not found?

Then that means there are no new updates.
Note that AdGuard for Firefox updates the filters automatically. If you does not receive the updates for some reason, then you should check them manually.

**Comment by zloyden** [comment]
I also saw some redirect in Firefox, but it's fixed. The new update will be available soon.

**Comment by olstice** [comment]
> I also saw some redirect in Firefox, but it's fixed. The new update will be available soon.
how do you check for manually?
