### ISSUE TITLE
t-mobile.com

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#192621]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7.83

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.t-mobile.com/cell-phones/brand/samsung?brand=samsung&icid=MGPO_TMO_P_24SMGXYNPI_C8816AC1ACE23BCB37823

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

||t-mobile.com/* /logging|
||t-mobile.com/* /analytics/
||cf-pixelfront-analytics.widencdn.net
### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
2nd breaks the site, long load.
