### ISSUE TITLE
mirrored.to [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#19265]
**Site**: https://www.mirrored.to/files/1VGWYTYH/KRT_CLUB_2.0.0.35.rar_links

**Issue**: Please remove the pop-up on the page.

**Screenshot**: http://prntscr.com/k2ljns

**OS**:
> `Windows 10 (32 bit)`

**Browser**: 
>` Chrome 67.0.3396.87 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled]`

**Comment by Nzzyme** [comment]
https://www.mirrored.to/files/MQY1CKGL/

Pop-up seen when clicking on 'Click to view the files'.

**Comment by BlazDT** [comment]
Not reproduced, please check @AdguardTeam/filters-maintainers

**Comment by zloyden** [comment]
Also not reproduced on my end.

**Comment by AdamWr** [comment]
I can't reproduce it either.

**Comment by Nzzyme** [comment]
Just checked again and confirm the issue. My filters just in case:

AdGuard Base filter
AdGuard Mobile Ads filter
Peter Lowe's Blocklist
AdGuard Tracking Protection filter
AdGuard Social Media filter
AdGuard Annoyances filter
Adblock Warning Removal List
Malware Domains Blocklist
Spam404
NoCoin Filter List

(No user filters).

Stealth Mode: On (default settings)

**Comment by Nzzyme** [comment]
Please fix
