### ISSUE TITLE
Missed ads on seasonvar.ru

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#1927]
Example:

http://seasonvar.ru/serial-13185-112263-1-season.html

Can disappear from time to time, please try checking few other series pages if the ad is not preset.

**Comment by Alex-302** [comment]
fixed

**Comment by Bohdan-SUP** [comment]
It's back:
![screen shot 2016-05-10 at 3 23 08 am](https://cloud.githubusercontent.com/assets/14153331/15132083/9e440610-165e-11e6-9e02-9dad23e498b2.png)

**Comment by Alex-302** [comment]
@Bohdan-SUP 
у тебя повторяется? Чисто должно быть.

**Comment by Bohdan-SUP** [comment]
Повторялось, скрин мой. Сейчас все в порядке.

**Comment by Alex-302** [comment]
Перед проверкой лучше обновлять фильтры, расширение автоматом их не очень часто проверяет.

**Comment by Bohdan-SUP** [comment]
Я обвновлял фильтры перед проверкой с приложением на Маке. Там видно Помощник в углу.
На тот момент проблема была актуальна.

**Comment by vgavrish** [comment]
http://seasonvar.ru/serial-13498-Odnazhdy_v_Rossii-3-season.html#rewind=5_seriya_na_40_minute_20_sekunde
Проблема только в Яндекс.Браузере. Расширение Антибаннер не блокирует рекламу:
http://prntscr.com/bezp4s
Обновления фильтров проверены:
http://prntscr.com/bezpa3

**Comment by Alex-302** [comment]
В яндекс браузере расширение пока не обновилось Временно можно установить из хранилища Хрома и выключить встроенное расширение(либо в новом включить только русский фильтр)
https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg
