### ISSUE TITLE
exchange.gemini.com elements being filtered

### ISSUE THREAD

**Issue by jaorsh** [AdguardTeam/AdguardFilters#192825]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

exchange.gemini.com

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Cookie Notices filter

### Add your comment and screenshots

1. A generated class used on many elements on exchange.gemini.com is being blocked by Adguard cookie filters. This was meant to block the cookie banner from displaying, but impacts many components throughout the website.

https://github.com/AdguardTeam/AdguardFilters/issues/174045
https://github.com/AdguardTeam/AdguardFilters/blob/5f17094187545527a7fdb24f7cb12017a5a0201a/AnnoyancesFilter/Cookies/sections/cookies_specific.txt#L1745

Request: Remove this line `exchange.gemini.com##.ejv4ity0`

### Privacy

- [X] I agree to follow this condition

**Comment by jaorsh** [comment]
@Alex-302 getting some eyes on this would be much appreciated.

**Comment by Alex-302** [comment]
@jaorsh Hi. Removed the bad rule. Do you see cookie notifications here? Can't register without US phone number.

**Comment by jaorsh** [comment]
@Alex-302 Appreciate it! To see the experience as new I usually open in a chrome incognito tab to https://exchange.gemini.com/register, with uBlock origin extension activated. I've also added an `id="cookie-banner"` to the cookie pop-up, to avoid the possible future case of a reused class being used to target the element.
