### ISSUE TITLE
Unblock cts.vresp.com from AdGuard DNS filter

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdguardFilters#192829]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

Adguard Home v0.108.0-b.60

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

cts.vresp.com

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by timkgh** [comment]
This happens in AdGuardHome, blocked by the "AdGuard DNS filter".

![53471](https://github.com/user-attachments/assets/afc295df-d871-4e2d-8228-58c96d4f5574)

Then domain is used by email newsletters.

**Comment by Sergey-Lyapin** [comment]
Hello @timkgh 
This domain is also used for tracking on web pages.
Please add `@@||cts.vresp.com^` to user rules.

![image](https://github.com/user-attachments/assets/4aa717a5-df69-4385-b0d2-6dbbc039a8d3)

![image](https://github.com/user-attachments/assets/88f227ef-2933-4e48-b439-3ac1bc2ebe18)
