### ISSUE TITLE
http://ponominalu.ru/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1928]
http://ponominalu.ru/
в конце оплаты заказа:
http://prntscr.com/ap5c8z

 AdBlock не влияет

LGB-755-84809

**Comment by Alex-302** [comment]
@evgeniy-ADG 
регистрация мутная. Попроси аккаунт сделать, или удалённо могу глянуть.
Ещё можешь посоветовать новую бету, в ней инжекты исправлены.

**Comment by Alex-302** [comment]
я это проверить не могу, но можешь передать для пробы
```
@@||ponominalu.ru/payments/report$elemhide,jsinject
```

**Comment by Alex-302** [comment]
Пока добавил в русский
