### ISSUE TITLE
dropgalaxy.com/financemonk.net

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#192960]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7.83

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://dropgalaxy.com/drive/es7jhuvnnlrv

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

on the first page wait for countdown then click download. it will redirect. then wait for that countdown and then click download then it will redirect then 
![Screenshot_20241114_120021_Samsung Internet](https://github.com/user-attachments/assets/35054827-e899-4e2c-9c28-57f41ea52838)
anti adblock appears

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
@Alex-302

**Comment by Alex-302** [comment]
Please send reports from AdGuard.

**Comment by jordansworld** [comment]
hello idk whats up with the adguard reporting tool but i get to the end to submit it and says an error occured. tried on two different browsers even
