### ISSUE TITLE
historyofyesterday.com

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#193068]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7.83

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://hotels.historyofyesterday.com/how-much-does-it-cost-to-stay-at-resorts-in-new-zealand-with-your-partner/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

this is a legit site it redirects to a filehost. when the timer reaches 13 seconds Anti-Adblock appears. 
![Screenshot_20241116_094013_Samsung Internet](https://github.com/user-attachments/assets/498e1a59-1f5f-473d-bfc5-4e0b21d376f7)

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Please post initial URL.

**Comment by BlazDT** [comment]
Pasted wrong link? Only download for a torrent file.

**Comment by jordansworld** [comment]
no thats the right link. it doesnt redirect for you?

**Comment by BlazDT** [comment]
Nope, just the normal download stuff from that file hoster. Captcha and waiting time.

**Comment by jordansworld** [comment]
thats so weird. are you located in the us?

**Comment by jordansworld** [comment]
https://github.com/user-attachments/assets/0594ec07-7076-44c7-8ff8-65a2cdff1e67

**Comment by jordansworld** [comment]
@Alex-302 can you reproduce?

**Comment by jordansworld** [comment]
Thankyou!

**Comment by BlazDT** [comment]
@Alex-302 
He meant the initial reported website is not opening anymore as I disabled non-required redirect on page.

**Comment by jordansworld** [comment]
yeah original site is broke can it be fixed?

**Comment by BlazDT** [comment]
Not understanding you exactly. What is exactly broken and how?

**Comment by jordansworld** [comment]
sorry. on my end its infinite reload

https://github.com/user-attachments/assets/fe271bf6-eede-48d5-beca-ede3bce0f474

**Comment by jordansworld** [comment]
Could it be my adguard version? im on 4.5 not 4.7.83

**Comment by BlazDT** [comment]
Error in video is cloudflare issue.
You can try to update to latest version and try to disable stealth options if one is set. In initial report you wrote a higher version though.

**Comment by jordansworld** [comment]
sorry i was on that version then i downgraded because it was killing my battery

**Comment by jordansworld** [comment]
i got.it! it was stealth

**Comment by jordansworld** [comment]
thankyou so much

**Comment by jordansworld** [comment]
what stealfh filter needs to be whitelisted is the question now

**Comment by jordansworld** [comment]
got it. its ip address

**Comment by jordansworld** [comment]
@BlazDT ok sorry but now its not working even after updating adguard to latest nightly and disabling tracking completely :(

**Comment by BlazDT** [comment]
I do not even get cloudflare at all when I visit the page. Maybe some issue with the site itself.
Please try to disable AdGuard and check again.

**Comment by jordansworld** [comment]
loads fine without adguard. but then i get redirected again :(

**Comment by Alex-302** [comment]
@jordansworld We don't know your settings. Please send a report from AdGuard.

**Comment by jordansworld** [comment]
should i just send my settings file through email?

**Comment by BlazDT** [comment]
Please post them here.
In case you have French filter enabled, please disable as it has a rule which block all third-party scripts.

**Comment by jordansworld** [comment]
even with French filter disabled still broke. here is my settings:

https://www.mediafire.com/file/bzohfr51wzwak4z/adguard_settings_4.5.25_2111_160412.zip/file

**Comment by jordansworld** [comment]
@BlazDT can you reproduce with my settings?

**Comment by jordansworld** [comment]
@BlazDT @Alex-302  can you reproduce?

**Comment by jordansworld** [comment]
@Alex-302 can you please test with my settings?

**Comment by jordansworld** [comment]
good news! it finally works

**Comment by Alex-302** [comment]
Probably not related to AG? Maybe ISP blocked something?
