### ISSUE TITLE
MSN Новости — последние - the feed doesn't work when Adguard is enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1930]
MSN
https://play.google.com/store/apps/details?id=com.microsoft.amp.apps.bingnews&hl=ru

ошибка при обновлении новостной ленты:
http://prntscr.com/apmeev

Помогает отключение Английского фильтра

**Comment by evgeniy-ADG** [comment]
When blocking acceptable ads, adguard blocks all msn news app content, showing a white page 'error loading page please refresh' RJB-741-56244

**Comment by Alex-302** [comment]
filter of acceptable ads did not block anything.
I can't reproduce it.
Please ask for HTTP log
