### ISSUE TITLE
ETOnline.com - Required user action blocked (AdGuard Annoyances filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#19301]
### Affected site:
`https://www.etonline.com/`

### Issue:
Required user action (cookie consent) is blocked, preventing video playback.

### Example:
`https://www.etonline.com/mila-kunis-addresses-divorce-and-pregnancy-rumors-and-the-stress-it-causes-family-105330/`

### Problem filter:
AdGuard Annoyances filter

### Problem rule:
`###_evidon_banner`

### Possible fix:
`etonline.com#@##_evidon_banner`
..but of course, if possible, bypassing this annoyance would be preferable.

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.9.3 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.2 (XUL)

**Comment by BlazDT** [comment]
Video plays fine with AdGuard product without accepting cookie. Added exclusion for uBlock.

**Comment by THEtomaso** [comment]
> Video plays fine with AdGuard product without accepting cookie. Added exclusion for uBlock.

In light of recent discoveries, it's safe to say that this is a regional problem, and not exclusive to uBlock Origin:
https://github.com/AdguardTeam/AdguardFilters/issues/20596#issuecomment-410455157
