### ISSUE TITLE
block m.ctrip.com

### ISSUE THREAD

**Issue by Shura23** [AdguardTeam/AdguardFilters#193163]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7nightly 12

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

https://microdown.myapp.com/ug/%E5%BA%94%E7%94%A8%E5%AE%9D.apk?comment=channelId%3D1181533%26context%3D%26scheme%3Dtmast%253A%252F%252Fencrypt%253Fencryptdata%253DfmhmhLuSWogrncDRTHUyILpdoRnnCP5xLYXW5WKcPc5lVDtwDloAK2D3Ekf35J167k3jA2fM7H66mvt%25252FGbFaNnGhGW3s6vH6Mz5M2vnzgBXMF5A6SEdzZDK9NJ6GnoKgc1ansy29ahGdUdW%25252FULFTBzdo3KKt8ey3Ksxib5WyHRpqeF9dWlnZgOcENdBkmqvJwZgAsXUSF0IX8vxUdHX5Iy9IRAY0wPnnxcOZpPVZyfghq5Hc9jKEYjbXA%25252FUAavtrfXs56kGjaPzd0%25252B2c7ts9YqBYhFk2G%25252Bc3vtA2X1TiBe3jn2o1op4R%25252FlCmKcbE2%25252Bpe73dFkz4BHnla1YZ6VNDUpeTQ0uZq65ll0QVATBlXaPJ2BfZYj7KMeVn2vvyHnAh0%25252BRgAQYuxaYRmzg7v%25252BDHAZC%25252F6d%25252BfBCGVCIHTsII43HJBAzDBoUSTqkVT5bbosRKVXwDhZm23pRC647rGqSag3YmT0X5pJpzgd%25252BgQqJkfZv7ef8qsxN%25252BVmjEE8cXvfl7Q77ekJuG2dH8sGX4K5RG8emgM62aWq5NYI0ZbYVi03cmyIHoc9BW2ZN7wUbv4YrsRvtW1evLa6ozobelRo4Fo2ugJE0QmYD8ofxPQmHfo3txY7DXfJAO%25252Bt0T732zLofBMVL3wReHuf7yQ7ZHk3fojWk4ME3kBhWPPkv6FoRdTEO5cro4%25252FwKjM3dgchoYrQ7i4AVuMMghlnPSA%25252BK%25252BFwpqqjGVyVExuukmAwEI4m2ZbvcjvHOaawzVrRCpKSXAvQLPSGJwG9DRkO%25252FXKUMXYovoUt8A%25253D%25253D%2526start_time%253D1731921781297%2526expiry_time%253D1731925381297%26t%3D1731921781000%26signature%3DmyLU7qEidnoCKWXnXa9BQvpM5GrLiw9JugoSVAHfIyz1lIkLVHFqaSmQ3LBzskhocvhzbvEzxSRti92qterEzp6Tk2XpYDGdU4StBlvcvYvuJZov7IXrANX%252BJKiY6riKi4YM0tmMAhTp9PDBwvB9YHl6ktx6i6h5ZRogMq2WS%252BE%253D&sign_type=V2&realname=20241113_8c221b1a125296ff8dc22e649eb38304_offset_30466048

### Ad Blocking

AdGuard Base filter

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

上面的链接是一个叫做“智行火车票”的软件的下载链接，m.ctrip.com是这个软件的广告域名，每当启动这个软件时就会出现长达3秒的广告，如果禁止这个域名，广告就会消失，并且基本功能不受影响。

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I have been checking the app for some time, but I don't have ads. Also the requests seems to be fine as I don't see something suspicious there.
@BlazDT @AdamWr please also check this.

**Comment by Shura23** [comment]
> I have been checking the app for some time, but I don't have ads. Also the requests seems to be fine as I don't see something suspicious there.
> @BlazDT @AdamWr please also check this.

可能是因为你在国外，不推送广告给你

**Comment by Shura23** [comment]
> Hm, could you translate that window and also take a look at the requests in `Recent activity`? You can get there by clicking on the `Assistant` in the AdGuard notification window - choose the app - Recent activity.
> There may be a suspicious request blocking which will help prevent this window from appearing. Please send the screenshots of them here and try to block them manually.
> If there's no effect, it's probably built into the app.

你说的翻译是指翻译我刚刚发的图片吗？这个图片圈起来的“广告”这个词的意思就是advertising。内容是抢1000元的机票补贴，总之就是广告了。第二第三张图就是启动软件时产生的请求。第一个请求就是我要你们禁止的域名
![Screenshot_20241118_183355_com.yipiao_edit_326313493412186.jpg](https://github.com/user-attachments/assets/f7eae6de-4387-4b77-b005-4f5813d7b61d)

![Screenshot_20241118_185624_com.adguard.android.jpg](https://github.com/user-attachments/assets/ee21095c-d616-4206-aa08-318020ff6c71)

![Screenshot_20241118_185642_com.adguard.android.jpg](https://github.com/user-attachments/assets/46696898-2a4c-4b96-9519-31ac7f25ab63)

**Comment by zloyden** [comment]
Ok, got it. Please try to block the requests one by one to see if that helps. You can do it by clicking on the request - scroll to the end - press on `Add blocking rule`.
If a rule or rules help, please post them here.

**Comment by Shura23** [comment]
> Ok, got it. Please try to block the requests one by one to see if that helps. You can do it by clicking on the request - scroll to the end - press on `Add blocking rule`.
> If a rule or rules help, please post them here.

![Screenshot_20241118_194558_com.adguard.android.jpg](https://github.com/user-attachments/assets/4419866d-77f5-45f3-8486-369b0141bc18)


![Screenshot_20241118_194605_com.yipiao_edit_328949121044596.jpg](https://github.com/user-attachments/assets/41e245e7-1b41-45cb-be32-89f1c43594f7)

我阻止了一个域名，然后广告就没了，直接进入第二张图的页面，不再有广告了。

**Comment by zloyden** [comment]
As I see, blocking `m.ctrip.com` helps, so a rule below should also work fine, but I see that the app name is different on your end. Is it `com.yipiao`? Is there any incorrect blocking with it?
```adblock
||m.ctrip.com^$app=com.tencent.android.qqdownloader|com.yipiao
```
