### ISSUE TITLE
iltalehti.fi

### ISSUE THREAD

**Issue by Ittenno** [AdguardTeam/AdguardFilters#193239]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

uBlock Origin 1.61.0 / Firefox 132.0.2

### What type of problem have you encountered?

Website or app doesn't work properly, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.iltalehti.fi/kamppailulajit/a/7a1723da-2275-48b3-b92c-ee8e6f640f29

### Ad Blocking

AdGuard Base filter, EasyList

### Annoyances

AdGuard Cookie Notices filter

### Add your comment and screenshots

Iltalehti.fi on recent days changed their cookie prompt and now when using the list `AdGuard – Cookie Notices` on uBlock, the cookie prompt gets blocked by the rule `||cdn.privacy-mgmt.com^$3p` and the updated `trusted-set-cookie` rule in `uBlock filters – Cookie Notices` fails to work causing for example video to not play.

Rule like this makes it work again
`@@||cdn.privacy-mgmt.com/unified/wrapperMessagingWithoutDetection.js$script,domain=iltalehti.fi`

Sample link with video
https://www.iltalehti.fi/kamppailulajit/a/7a1723da-2275-48b3-b92c-ee8e6f640f29

Screenshots / Video not playing
![image](https://github.com/user-attachments/assets/0000dbec-5909-4ddd-891d-3f8c1bf13d7f)

Video playing with the exception rule
![image](https://github.com/user-attachments/assets/f25dba1a-a3d0-4e44-8838-c98b489cbade)

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
