### ISSUE TITLE
www.lefigaro.fr

### ISSUE THREAD

**Issue by Hayastano** [AdguardTeam/AdguardFilters#193266]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.5.7

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.lefigaro.fr/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, EasyList Cookie List

### Language-specific

AdGuard French filter

### Add your comment and screenshots

Cookies are not blocked

<details><summary>Screenshot:</summary>

![IMG_3408](https://github.com/user-attachments/assets/71641f4a-1646-4ace-b87b-af358e553cc4)
</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by Hayastano** [comment]
In my case, the only way to block it is to activate the AdGuard anti-spyware filter, without which I get the window, I've tried everything but nothing works, just so you know, I have the "DNS AdGuard without filtering" with a "Hagezi Light" DNS filter.

The same goes for ticket #193268, apparently there's no problem but it doesn't work for me, I've deactivated and updated everything but nothing changes.

**Comment by Hayastano** [comment]
I followed your steps and deactivated everything, leaving only AdGuard base Filter and AdGuard cookie notice. 

I have deactivated DNS and checked that advanced protection is active.

I have a lifetime family subscription

**Comment by zloyden** [comment]
So the cookies are blocked? If not, please add this rule to user rules, wait ~ 2 minutes in the AdGuard app (it's important to stay there and not switch to other apps, otherwise the rule won't apply), then restart Safari and open the site.
```adblock
lefigaro.fr#%#//scriptlet('trusted-click-element', 'button.button__acceptAll')
```

**Comment by zloyden** [comment]
@AdamWr @BlazDT please also take a look at this.

**Comment by AdamWr** [comment]
I can reproduce that on iOS when I have only AdGuard Base filter and AdGuard Cookie Notices filter enabled.
Mentioned scriptlet doesn't work on iOS, I guess it's related to - https://github.com/AdguardTeam/Scriptlets/issues/407 (apps cannot/do not inject scripts to iframe with `about:srcdoc` source).

This rule:
```adblock
linternaute.com,lachainemeteo.com,journaldesfemmes.fr,lefigaro.fr#%#AG_onLoad(function(){if("undefined"!=typeof localStorage)try{if(!localStorage.getItem("_pubcid")){var b=new MutationObserver(function(){var a=document.querySelector("#appconsent > iframe");a&&a.contentDocument&&(a=a.contentDocument.querySelector(".button__acceptAll"))&&(b.disconnect(),a.click())});b.observe(document,{childList:!0,subtree:!0,attributes:!0});setTimeout(function(){b.disconnect()},1E4)}}catch(a){}});
```
works fine on my end.
Currently it's only available for Android, Mac and Windows apps (other platforms use scriptlet), so I will modify hints.

**Comment by zloyden** [comment]
Glad to hear that it works fine:)
