### ISSUE TITLE
Could fake unsubscribe websites be blocked (given they exist purely for phishing)?

### ISSUE THREAD

**Issue by dftf-stu** [AdguardTeam/AdguardFilters#193249]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

I use AdGuard Public DNS, using the default option which blocks ads, trackers and malware domains.

This URL inside web-browsers:
https://dns.adguard-dns.com/dns-query

And this one for the system-wide DNS on Android devices:
tls://dns.adguard-dns.com

I notice that the default filters the public DNS option uses never seem to block any of those websites
that are fake e-mail unsubscribe pages, that exist purely to harvest working e-mail addresses.

### Proposed solution

Given fake e-mail unsubscribe websites exist purely to collect working e-mail addresses to then send
more spam to, surely they should be classed as "phishing" and blocked by AdGuard DNS (and the
browser extensions also)?

The e-mail that are sent usually either lead to other phishing or scam sites, or malware pages.

### Additional information

Here are some example sites I feel AdGuard DNS should be blocking:

![allinoursite_com](https://github.com/user-attachments/assets/b87ffd07-9564-4784-8af3-3659b3db2a7c)

![doorsstormsy_shop](https://github.com/user-attachments/assets/1fa56ae3-22f4-49c7-9878-bff8ad32d31c)

![emailservicesnetau_com](https://github.com/user-attachments/assets/53f8e566-f590-4e53-9ad9-341abeb1faf1)

![euromaillinnk_com](https://github.com/user-attachments/assets/64c6dddf-812b-4904-9ba0-4bb1584b1e4c)

![findthorman_shop](https://github.com/user-attachments/assets/e1196ea5-8fa9-4ddf-9fba-023fe24cb424)

![keydoordasher_shop](https://github.com/user-attachments/assets/956c789d-c04e-413f-9970-3dd7022d7679)

![mybach_xyz](https://github.com/user-attachments/assets/853ea44f-661b-4107-9378-5ddee433f18d)

![threeneptuneboot_com](https://github.com/user-attachments/assets/2e39b662-2b4a-4b65-99b1-3a586da38772)

I do not see any-benefit to end-users of allowing access to these sites, when they're only used to gather e-mail
addresses to then send them more spam by e-mail!

Thanks

**Comment by dftf-stu** [comment]
(Oh and before any points out: yes, I am using _uBlock Origin Lite_ in _Microsoft Edge_ , not _AdGuard_ .  But I have used their browser-extension previously, and it never used to block such-sites then.  But regardless: I feel the AdGuard DNS service should do this, given all of these domains seem to exist solely to collect e-mail addresses and I doubt have any actual "good" pages hosted on them.  If you delete everything after the domain, and load their pages, you usually get a "website coming soon" landing-page, so I'd say the entire domain can just be blocked.)

**Comment by jordansworld** [comment]
can you post all the urls so they know what to block

**Comment by dftf-stu** [comment]
Hi @jordansworld : sure, but posting the entire URLs wouldn't be helpful, as these are randomised
on each e-mail so they can track who clicked them

Really it is the entire _domains_ that need to be blocked, as from what I can tell, they exist only to
serve that one fake unsubscribe page.  If you visit any these sites (none of which use HTTPS, so you'll
have to accept dropping-onto HTTP), you'll either see a "website coming soon" message, or some Linux
server message saying "how to configure your server".

List of domains:
allinoursite.com
doorsstormsy.shop
emailservicesnetau.com
euromaillinnk.com
findthorman.shop
keydoordasher.shop
mybach.xyz
threeneptuneboot.com

Thanks
