### ISSUE TITLE
nxbrew.net

### ISSUE THREAD

**Issue by AmyRose1288** [AdguardTeam/AdguardFilters#193276]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android, AdGuard for Windows

### AdGuard version

4.6.4 (Android),7.19.0 (Windows)

### What type of problem have you encountered?

AdGuard gets detected on a website, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox, Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://nxbrew.net/

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

Adblock Warning Removal List

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Chinese filter, AdGuard Japanese filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Remove X-Client-Data header from HTTP requests

### Add your comment and screenshots

https://nxbrew.net/

former site:https://nxbrew.com/ (domain down)

![image](https://github.com/user-attachments/assets/9899a64a-eb55-40aa-9900-42e8edb280cf)

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
issue already opened by me scroll down
