### ISSUE TITLE
Ozon.ru (mobile)

### ISSUE THREAD

**Issue by 333hronos** [AdguardTeam/AdguardFilters#193388]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker

### AdGuard version

21.11.24

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Yandex Browser

### Which device do you use?

Mobile

### Where is the problem encountered?

Ozon.ru

### Ad Blocking

EasyList

### Privacy

EasyPrivacy

### Annoyances

AdGuard Annoyances filter, EasyList Cookie List

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by 333hronos** [comment]
"AdGuard – Mobile Ads" при включенном фильтре - сайт перестаёт нормально отображаться.
Как отключаю - становится нормально.

**Comment by Alex-302** [comment]
@333hronos Что конкретно сломано?
