### ISSUE TITLE
flipboard.app - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#1933]
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=48674134

https://play.google.com/store/apps/details?id=flipboard.app&hl=en

**Comment by ameshkov** [comment]
Screenshot:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=48749041

**Comment by vgavrish** [comment]
@Alex-302 
появляется реклама cisco в приложении

лог 
[debug (26).txt](https://github.com/AdguardTeam/AdguardFilters/files/716586/debug.26.txt)
время 14:14

Скрин: 
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/22107138/edf4fac0-de54-11e6-920f-aee4e20c67f2.png)

</details>

Детали:
<details>
enabledFilterIds" : [ 2, 3, 14, 1, 6, 5, 11 ]
"filteringQuality" : "FULL"

"proxyMode" : true,
"proxySetupManualMode" : false

"sslMitmConfiguration" : "{\"certificateInstalledToSystemStorage\":null,\"mitmList\":\"1024 domains\",\"mitmListMode\":\"WHITELIST\"}",

"versionName" : "2.8.76",

ID: 1108156

**Comment by Alex-302** [comment]
@vgavrish лучше HAR попроси, а то не повториется никак. Может там на определённых сайтах реклама. Или на главной странице? Подробное описание не помешало бы.

**Comment by vgavrish** [comment]
отписала
