### ISSUE TITLE
letsupload.io

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#193398]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.5

### What type of problem have you encountered?

AdGuard gets detected on a website

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://letsupload.io/folder/e6843cd4a35644af5b52c590113af1aa/Crash_Bandicoot_4

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, Fanboy's Annoyances

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

![Screenshot_20241121_194335_Samsung Internet](https://github.com/user-attachments/assets/4f75c04f-9e1b-4d00-9e1b-0e24e9309825)

### Privacy

- [X] I agree to follow this condition

**Comment by AdamWr** [comment]
It's parked domain without any useful content.
