### ISSUE TITLE
ebay.com

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#193326]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.7.83

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

ebay.com

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Add your comment and screenshots

A.TELEMETRY_SDK_NAME]="opentelemetry",b[A.PROCESS_RUNTIME_NAME]="browser"(found in first tracker)

||ebaystatic.com/cr/v/c01/logs.*.bundle.js
||ebay.com/chocolatechip/track|

the above trackers found here: 

https://www.ebay.com/itm/294925656467?_skw=Polo+Black+Ralph+Lauren

https://signin.ebay.com/ws/eBayISAPI.dll?SignIn&ru=https%3A%2F%2Fwww.ebay.com%2Fmye%2Fmyebay&sgfl=sm&smuid=08dcbd996d434fbea3d6ab1937cfc823

the below trackers found above:

||ebay.com/gh/collectbehaviorinfo?
||ebay.com/ufeservice/v1/commonbeacon

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
the below is only shown if u login:

||ebay.com/blueberry/v1/ads/identity/pixelUrls

**Comment by Alex-302** [comment]
@Sergey-Lyapin All rules must be well tested.

**Comment by jordansworld** [comment]
i tested and everything works for me. Understandable if you need to test tho

**Comment by jordansworld** [comment]
What about this one?

ebay.com/blueberry/v1/ads/identity/pixelUrls/
@Sergey-Lyapin
