### ISSUE TITLE
accuweather app - can't play video

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1935]
https://play.google.com/store/apps/details?id=com.accuweather.android&hl=ru

logs: CVO-531-21930

![image](https://cloud.githubusercontent.com/assets/15856304/14390548/57396604-fdc0-11e5-8bdd-951f20f825d1.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
уточни плиз, актуально ли ещё

**Comment by evgeniy-ADG** [comment]
just have contacted the customer, will update here

**Comment by evgeniy-ADG** [comment]
> No, not fixed... Unless the app is excluded from filtering, it will still

Актуально

**Comment by Alex-302** [comment]
Пусть HAR запишет.
Только выключить запись пусть не забудет.

**Comment by Alex-302** [comment]
Не, HAR не нужен. Пусть попробует вычислить фильтр, который ломает.

**Comment by evgeniy-ADG** [comment]
Написал
