### ISSUE TITLE
Image Analysis Toolset (IAT) App [AdBlock Message] [Android]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#19355]
**App Name**: Image Analysis Toolset (IAT)
**Play Store Link**: https://play.google.com/store/apps/details?id=tk.silviomarano.imageanalysistoolset&hl=en
**Issue**: Seeing Adblock message after running the app
**Screenshot**: https://ibb.co/js1n6o

**System**:
- Android version: 6.0.1 MMB29M
- MIUI version: MIUI Global 9.5 - Stable [ 9.5.3.0 (MHOMIFA) ]

**AdGuard Version**:
- AdGuard for Android 2.11.81 (Stable)

**Filters**:
English, Spyware, Social Media, Annoyances, Mobile Ads, EasyList China

**AdGuard Settings**:

- No user filter used
- Phishing & Malware Protection: Enabled
- Block ads in all apps: Enabled
- Search ads & self-promotion of sites: Disabled
- DNS Filtering: Disabled
- HTTPS Filtering: Enabled
- High quality filtering: Enabled
- Filtering mode: Local VPN

**Comment by Alex-302** [comment]
Can't download it. Please bive me a link to apk.

**Comment by Nzzyme** [comment]
Can you try this link. It is a direct download to the apk file

https://bit.ly/2zqyRkF

**Comment by Nzzyme** [comment]
Any update please?

**Comment by Alex-302** [comment]
This app is not working on my device. I see only black screen and it freezes my device.
Try to unblock network requests one-by one.

**Comment by Nzzyme** [comment]
I monitored the connections after launching this app and see these:

https://ibb.co/jc2fR8

**Comment by Alex-302** [comment]
Please try to unblock that domain using Assistant.

**Comment by Nzzyme** [comment]
Unblocking that domain (googleads.g.doubleclick.net) might work for this app but whats the point of unblocking an ad/tracking domain? This domain is used on many sites/apps/services and is also added to the main list.

This app shows ads in the free version and the purpose of using AG is to block the ads. Whats the point of using AG then if the ad/tracking domain is whitelisted? Is there a way tackle this just like the regular web pages where there is anti adblock script?

**Comment by BlazDT** [comment]
Only seeing that message when HTTPS filtering is disabled on my Android 7.1.1.
Whitelisting the url mentioned for the app-only works too.
