### ISSUE TITLE
dijitarya.com Annoyances

### ISSUE THREAD

**Issue by Raidware** [AdguardTeam/AdguardFilters#193582]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

ublockorigin with adguard filter

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.dijitarya.com/blog/instagram-reklam-yazma-zorunlulugu-2024.html

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Annoyances filter

### Language-specific

AdGuard Turkish filter

### Add your comment and screenshots

1. when u open the website, it has closeable annoyance window.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot_20241125_121343_Quetta](https://github.com/user-attachments/assets/a681cf1d-5ecd-46e8-94d6-7e10b8701b2f)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
This website has too little traffic.
> 100000 visits/month needed

**Comment by Sergey-Lyapin** [comment]
@Raidware 
We use [Similarweb](https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/1m?webSource=Total&key=dijitarya.com)
There is also [the extension](https://chromewebstore.google.com/detail/similarweb-website-traffi/hoklmmgfnpapgjgcpechhaamimifchmp)
