### ISSUE TITLE
tureng.com ads

### ISSUE THREAD

**Issue by Raidware** [AdguardTeam/AdguardFilters#193581]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Ublock with adguard Filters

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

https://tureng.com/tr/turkce-ingilizce/strict

### Ad Blocking

AdGuard Mobile Ads filter

### Language-specific

AdGuard Turkish filter

### Add your comment and screenshots

1. Extra space due to advertising residuals

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot_20241125_150807_Quetta](https://github.com/user-attachments/assets/c54e6909-7ba7-434e-bab0-d187aeccc250)

</details>

<details><summary>Screenshot 2:</summary>

![Screenshot_20241125_150822_Quetta](https://github.com/user-attachments/assets/63e118ef-a99f-4473-9c36-3966f79f1b5f)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I have checked it on both desktop and smartphone. Have you done the following as I said?
In case you still have it, please send the saved page to filters@adguard.com. Also, what country have you visited the site from?

**Comment by Raidware** [comment]
> I have checked it on both desktop and smartphone. Have you done the following as I said? In case you still have it, please send the saved page to [filters@adguard.com](mailto:filters@adguard.com). Also, what country have you visited the site from?

In ublock "AdGuard – Ads" filter does not coming in default. I opened it and fixed.
