### ISSUE TITLE
gzt.com

### ISSUE THREAD

**Issue by Raidware** [AdguardTeam/AdguardFilters#193583]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Ublockorigin via adguard filters

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.gzt.com/

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Annoyances filter

### Language-specific

AdGuard Turkish filter

### Add your comment and screenshots

1. There are their's TV channel own ad.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot_20241125_122033_Quetta](https://github.com/user-attachments/assets/240a8247-1b00-44e3-b4cd-7c22dbb5ab18)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available soon.
