### ISSUE TITLE
iOS Safari in private mode

### ISSUE THREAD

**Issue by patoux3** [AdguardTeam/AdguardFilters#193665]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

v0.107.46

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

sex.com

### Ad Blocking

AdGuard Base filter

### Add your comment and screenshots

Hi, For your information, I am able to go to the sex.com site with Safari on iOS in private mode. It works well (it's blocking) with Brave in regular mode or in private mode. On Mac OS no problem regardless of the mode chosen with Safari and Brave. THANKS

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Works fine on my end in Safari. Why it must be blocked?
