### ISSUE TITLE
coomer.su

### ISSUE THREAD

**Issue by Weein** [AdguardTeam/AdguardFilters#193619]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.19.0 (4853)

### What type of problem have you encountered?

Website or app doesn't work properly, AdGuard gets detected on a website

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://coomer.su

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Chinese filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Block WebRTC, Block Push API, Block Location API, Hide Referrer from third-parties (specify in comment below, if used custom value), Hide your User-Agent (specify in comment below, if used custom value), Remove X-Client-Data header from HTTP requests, Protect from DPI

### Add your comment and screenshots

1. <comment>

_**Coomer & Kemono have the same issue.**_

[Coomer](https://coomer.su)
[Kemono](https://kemono.su)
[Posts of "drakevonxxx" from "OnlyFans" | Coomer](https://coomer.su/onlyfans/user/drakevonxxx)

By the way, [Web Reporting Tool](https://kb.adguard.com/technical-support/reporting-tool) doesn't work.

![Report an issue AdGuard 1](https://github.com/user-attachments/assets/cce5d1f6-5aae-4844-a99c-2cd56e3ed545)
![Report an issue AdGuard 2](https://github.com/user-attachments/assets/ee8551b3-67ed-4ef1-aae5-0f63aad1845e)

2. Screenshots
<details><summary>Screenshot 1:</summary>

[Screenshot 1](https://i.imgur.com/3bLZuEl.jpeg)

</details>

<details><summary>Screenshot 2:</summary>

![02](https://github.com/user-attachments/assets/afeaed42-09d8-480a-8e9e-502f9258621e)

</details>

<details><summary>Screenshot 3:</summary>

![03](https://github.com/user-attachments/assets/28781ea5-b2aa-4b37-89fa-c265fcba5172)

</details>

<details><summary>Screenshot N:</summary>

[Screenshot N](https://i.imgur.com/tLnLtru.jpeg)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Not reproduced on my end. Try to update the filters, clear browser data, restart it, open the site.
