### ISSUE TITLE
tubitv.com

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#193606]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.5

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://tubitv.com/movies/100030038/wrath-of-man

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Add your comment and screenshots

||tubitv.com/oz/videos/fallback-metrics?
||tubitv.com/oz/log?
||tubitv.com/*sendBeacon=

login and play video to see these.

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
> login and play video to see these.

I don't see the first two requests on my end, but I've added a rule for the last one.
Does the video work if those requests are blocked? Please also show them in the filtering log.

**Comment by jordansworld** [comment]
that rule is perfecf

**Comment by zloyden** [comment]
I've added them. Update should be available in 2-3 hours.

**Comment by jordansworld** [comment]
@zloyden forgot to mention that login is broken until you add this: @@||account.production-public.tubi.io^$stealth=3p-auth

**Comment by jordansworld** [comment]
||tubitv.com/web-k8s/dist/youbora-monitoring.*.chunk.js

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours. Thanks for letting me know.
