### ISSUE TITLE
www.radio.de

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdguardFilters#193624]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.19.0

### What type of problem have you encountered?

Missed ads or ad leftovers, Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.radio.de/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, Legitimate URL Shortener

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard German filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Remove X-Client-Data header from HTTP requests

### Add your comment and screenshots

Just in case you don't know. Your reporting page is broken and endless loading attached pictures. After it gave up, you can't create a ticket.

1. Sticky Smartbanner on Bottom

<details><summary>Screenshot:</summary>

![radio1](https://github.com/user-attachments/assets/517bf203-831f-4b61-856d-ffffc44e0431)

</details><br/>

2. Smart Ad on Bottom

<details><summary>Screenshot:</summary>

![radio2](https://github.com/user-attachments/assets/0a2df94e-1116-4a2a-9099-d9c00a7f6674)

</details><br/>

https://www.radio.de/s/16bitfmmain

3. Ad Placeholder

<details><summary>Screenshot:</summary>

![radio3](https://github.com/user-attachments/assets/64705284-1b88-4773-a656-07d0048250e7)

</details><br/>

[popupplayer.radio.net/popupplayer/index.html?station=16bitfmmain&tenant=www.radio.de&authId=6a74d679-89ff-4b5a-b1e7-fca1c9d6f3a2](http://popupplayer.radio.net/popupplayer/index.html?station=16bitfmmain&tenant=www.radio.de&authId=6a74d679-89ff-4b5a-b1e7-fca1c9d6f3a2)

4. Ad placeholder

<details><summary>Screenshot:</summary>

![radio4](https://github.com/user-attachments/assets/5d8b2180-e5bb-451e-b388-9a3b62aab789)

</details><br/>

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
Fixed, update should be available in 2-3 hours.
