### ISSUE TITLE
iqiyi.com

### ISSUE THREAD

**Issue by wolaikk** [AdguardTeam/AdguardFilters#193610]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.19

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.iqiyi.com/v_jun1tfqci4.html?themePageId=1&bkt=bkt_01&rseat=image_1&r_area=pcw_theme&ht=2&r_source=59@64&recArea=pcw_theme&isVipOnly=1&rank=1&block=bt_pcarecommendtheme_8&vfrm=pcw_home&eventId=e3bd0f9e17c6b035985377510de86add&bstp=3&e=e3bd0f9e17c6b035985377510de86add&stype=2&themeid=3259701192997802&c1=2&vfrmrst=image_1&bucket=bkt_01&vfrmblk=bt_pcarecommendtheme_8&r=6326381228729201&event_id=e3bd0f9e17c6b035985377510de86add&fatherid=3259701192997802&rpage=pcw_home&position=6

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Annoyances filter

### Language-specific

AdGuard Chinese filter

### Add your comment and screenshots

[20241126_adguard_filtering_log_records.json](https://github.com/user-attachments/files/17914372/20241126_adguard_filtering_log_records.json)
![屏幕截图 2024-11-15 195249](https://github.com/user-attachments/assets/5710b341-a846-4153-879a-41a3d7256c06)

There is a side effect - after switching episodes, the playback control bar disappears! Press the right arrow key to reproduce the control bar

![屏幕截图 2024-11-26 151231](https://github.com/user-attachments/assets/7cc14e34-5845-425c-a9f6-4b88684ba5b1)

rules  ||71edge.com/videos/other/$xhr

Please test

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
I don't see ads on my end - they have been blocked.
