### ISSUE TITLE
ify.ac

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#193662]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.5

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://ify.ac/get/1itrb0

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Add your comment and screenshots

legit site. just shows a fake download button

![Snapchat-1607734955](https://github.com/user-attachments/assets/e1e7d2a8-749c-4567-bdac-e064d6fe416f)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
![image](https://github.com/user-attachments/assets/82688aa9-cf93-4b42-a34a-f856cec9077f)

obsolete link

**Comment by jordansworld** [comment]
https://ify.ac/1SBs

try this.

**Comment by Alex-302** [comment]
It seems trash paid redirections.

**Comment by jordansworld** [comment]
wait for the go to link appear

**Comment by Alex-302** [comment]
![image](https://github.com/user-attachments/assets/8923b63d-9370-4ba0-a7b2-846388ce6897)

**Comment by Alex-302** [comment]
They promote viruses
https://ify.ac/1Qff

Blocked as phishing.
