### ISSUE TITLE
sfist.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1936]
Link - http://sfist.com/2015/04/24/airbnb_violations_now_being_used_mo.php
Reporter - MJH-523-57821
Screenshots - click on Additional Stories:
<details>
![image1](https://cloud.githubusercontent.com/assets/14153331/14396880/d8bca2fa-fde2-11e5-9c97-8a4a7b39e262.PNG)
![image2](https://cloud.githubusercontent.com/assets/14153331/14396881/d8d7786e-fde2-11e5-9b67-c34ff5eabbc2.PNG)
</details>

**Comment by Alex-302** [comment]
tabola is advertising network, it is blocked on my end. Strange issue.
