### ISSUE TITLE
msi.com

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#19361]
[https://ru.msi.com/Laptop/support/PR320PR321](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fru.msi.com%2FLaptop%2Fsupport%2FPR320PR321)

 Блокируется куки-скрипт `https://cc.cdn.civiccomputing.com/8.0/cookieControl-8.0.min.js`.
Из-за этого не нажимается кнопка "Принять" (2) в политике по куки и скачка файла (1) не начинается.
Причина в правиле `/cookiecontrol-` Фильтра раздражителей.
Исправление: `/cookiecontrol-$domain=~msi.com`

<details><summary>Screenshot:</summary>

![2018 07 07-1](https://user-images.githubusercontent.com/17948007/42412375-e26a5e48-8213-11e8-8bbf-cbee745229ff.png)
</details>

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.9.2 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by THEtomaso** [comment]
Confirmed.
Files can't be downloaded, as long as the cookie consent dialog is blocked.

**Comment by XX-J** [comment]
Знак исключения `~` забыл.
