### ISSUE TITLE
AdGuard-DNS is breaking Payoneer app.

### ISSUE THREAD

**Issue by uncharted-user** [AdguardTeam/AdguardFilters#193763]
### Platform

Android

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Your configuration

1. OpenWrt 23.05.5 with Adguard private DNS over HTTPS (forced all devices connected to the router will have to use AdGuard-DNS) e.g. https://d.adguard-dns.com/dns-query/<unique-id>
2. Android 14

### Issue Details

1. Set Adguard Private DNS over HTTPS on OpenWRT
2. Install [Payoneer](https://play.google.com/store/apps/details?id=com.payoneer.android) app
3. Launch the app

### Expected Behavior

The app should open and show the log in form.

### Actual Behavior

The never shows anything other than welcome animation loop. It is only happening when using Adguard-DNS and working seamlessly with other DNS and VPN.

### Screenshots
<details><summary>Screenshot 1:</summary>
![ScreeenShot](https://github.com/user-attachments/assets/6c343bf3-879f-451c-bcee-b5c789f49b0e)
</details>

**Comment by Alex-302** [comment]
Hi
Sorry for a delay.
Related issue: https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1794 - it is not caused by filters. Something is wrong when using our server with some ISPs or in some regions.

**Comment by uncharted-user** [comment]
> Something is wrong when using our server with some ISPs or in some regions.

Could you please find what is the reason and fix it? When I purchased it, I did not read anything related to the region.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1794#issuecomment-2506853290
