### ISSUE TITLE
http://www.opensubtitles.org/en/search

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1937]
Missed ads on top

![image](https://cloud.githubusercontent.com/assets/15856304/14403147/40616216-fe55-11e5-998a-3860e25395f6.png)

<deails>

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.80.70 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.5.18 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.9.18 Enabled=NO
ID=8 Name="Dutch filter" Version=1.0.8.70 Enabled=NO
ID=11 Name="Mobile ads filter" Version=1.0.3.8 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=101 Name="EasyList" Version=1.0.55.75 Enabled=YES
ID=106 Name="EasyList Dutch" Version=1.0.55.87 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.55.65 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.55.16 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.55.10 Enabled=NO
ID=209 Name="Prebake" Version=1.0.1.10 Enabled=NO
ID=210 Name="Spam404" Version=1.0.1.27 Enabled=NO
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.59 Enabled=YES

**Comment by worldsdream** [comment]
This one seems difficult to block, lets see...

**Comment by Alex-302** [comment]
@worldsdream 
I can't block it because can't reproduce.
Could you please to disable filters ```#101-211``` and check again?

**Comment by worldsdream** [comment]
How do i do that on my ios device?

**Comment by worldsdream** [comment]
My bad, i disabled them. Same ads.

**Comment by worldsdream** [comment]
Any updates on this one? Anyone with a iphone that can confirm those ads?

**Comment by Alex-302** [comment]
Hi
Please check for updates.

**Comment by worldsdream** [comment]
Yes it's working. I already did post in the forum that this was fixed since today.
