### ISSUE TITLE
com.kwai.video

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#193743]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.5

### What type of problem have you encountered?

Missed analytics or tracker, missed ads

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.kwai.video

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Add your comment and screenshots

||kix-ulogl2.kwai-pro.com^
||ulog2-us.kwaipros.com^
||ulog1-us.kwai-pro.com^

also reported by a redditor that ads appear. Unfortunately i cant see anything because i dont reside in the country required so.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Does not work on my end. Which country must be used in VPN?


Please test:
```
-ulogl*.kwai-pro.com^
||ulog*.kwaipros.com^
||gdfp.kwaipros.com^
||g-gdfp.uvfuns.com^
```

**Comment by jordansworld** [comment]
i downloaded the app from apkmirror. 😅 

https://www.apkmirror.com/apk/joyo-technology-pte-ltd-2/

**Comment by jordansworld** [comment]
will test those right now

**Comment by jordansworld** [comment]
ok so i think we should just add the ulog ones. as no content loads for me on the app because you have to be in brazil. so i can't tell if the other filters break anything

**Comment by jordansworld** [comment]
@Alex-302 i got the app working. but didn't need go add any filters as there was no ads.
