### ISSUE TITLE
walmart.com

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#193736]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.5

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.walmart.com/account

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, Adblock Warning Removal List, Fanboy's Annoyances

### DNS filters

AdGuard DNS filter

### Language-specific

AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Ukrainian filter

### Add your comment and screenshots

page is broke because of filter: /ads_$popup located in french filter

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
> ### Prerequisites
> * [x]  This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
> * [x]  Filters were updated before reproducing an issue;
> * [x]  AdGuard product version is up-to-date;
> * [x]  Browser version is up-to-date;
> * [x]  If the site or app is broken, disabling AdGuard protection resolves an issue.
> 
> ### What product do you use?
> AdGuard for Android
> 
> ### AdGuard version
> 4.5
> 
> ### What type of problem have you encountered?
> Website or app doesn't work properly
> 
> ### Which browser(s) do you use?
> other (specify in comment below)
> 
> ### Which device do you use?
> Mobile
> 
> ### Where is the problem encountered?
> https://www.walmart.com/account
> 
> ### Ad Blocking
> AdGuard Base filter, AdGuard Mobile Ads filter, EasyList
> 
> ### Privacy
> AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts
> 
> ### Social Widgets
> AdGuard Social Media filter
> 
> ### Annoyances
> AdGuard Annoyances filter, Adblock Warning Removal List, Fanboy's Annoyances
> 
> ### Security
> _No response_
> 
> ### Other
> _No response_
> 
> ### DNS filters
> AdGuard DNS filter
> 
> ### Language-specific
> AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Ukrainian filter
> 
> ### What Stealth Mode options do you have enabled?
> _No response_
> 
> ### Add your comment and screenshots
> page is broke because of filter: /ads_$popup which is located in french filter
> 
> ### Privacy
> * [x]  I agree to follow this condition

**Comment by Alex-302** [comment]
Works fine, it seems. Please send report from AdGuard, if still reproduced.

**Comment by jordansworld** [comment]
weird everything works today. sorry

**Comment by Alex-302** [comment]
Great)
