### ISSUE TITLE
com.disney.disneyplus

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#193799]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.5

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.disney.disneyplus

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy

### Add your comment and screenshots

ads.twdcgrid.com
beacons.digital.disneyadvertising.com

tested throughly on different devices. everything works with it blocked. (on ad supported plan)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Found same domains on the web version https://github.com/AdguardTeam/AdguardFilters/commit/eb2abc9ef5a85dda97f9114fcecf4bc117ab4a5f
