### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#193859]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.5

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

github.com

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Add your comment and screenshots

||github.githubassets.com/assets/ui_packages_microsoft-analytics_microsoft-analytics_ts-*.js

appears on login page i put a star because letters and numbers appear in the url

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
i have tested this throughly nothing is broke. there was two other ones but they break functionality so i didnt add them here.

**Comment by Alex-302** [comment]
Not sure. Looks like their bug tracking service to catch errors.
