### ISSUE TITLE
profreehost.com [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#19381]
**Site**: https://profreehost.com/

**Issue**: Please remove the adblock message on the page.
 
**Screenshot**: http://prntscr.com/k3v7qu

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 67.0.3396.99 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Message hidden, they check if adsbygoogle is shown and if adsbygoogle.js is blocked (height = 0). Didn't find any negative elements with adblocker, therefore only hid the message.
