### ISSUE TITLE
protonvpn.com

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#193804]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.5

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://account.protonvpn.com/downloads

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social Widgets

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, Adblock Warning Removal List, Fanboy's Annoyances

### DNS filters

AdGuard DNS filter

### Add your comment and screenshots

||protonvpn.com/api/* /metrics|
||kg668dbov0.execute-api.us-east-1.amazonaws.com/prod/log|
||braintreegateway.com/web/*/js/data-collector.min.js

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
for the first filter dont make it anymore generic as problems occur just keep it like i pasted.

**Comment by jordansworld** [comment]
Unfortunately i cant reproduce these again. they just appeared in my log after purchasing a subscription. guess i should have copied the full urls. sorry.

**Comment by Alex-302** [comment]
Reproduced only `https://account.protonvpn.com/api/data/v1/metrics`

**Comment by Alex-302** [comment]
Can't add 2 and 3 without checking as there is a risk of the payment process breaking down.

**Comment by jordansworld** [comment]
ah. i didn't think of that. that would be bad

**Comment by jordansworld** [comment]
can we do ||protonvpn.com/api/data/v1/metrics

Because if u go to the join page it is unblocked:

https://join.protonvpn.com/signup?plan=vpn2024&billing=24&currency=USD&coupon=BF2024YR

**Comment by jordansworld** [comment]
@Alex-302

**Comment by jordansworld** [comment]
@Alex-302

**Comment by Alex-302** [comment]
Ok, added.
