### ISSUE TITLE
gdh.digital cookie notices

### ISSUE THREAD

**Issue by Raidware** [AdguardTeam/AdguardFilters#193817]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [x] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [x] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Ublockorigin with adguard filters

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

https://gdh.digital/akraba-evliligi-yasaklanacak-mi-128551

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Annoyances

AdGuard Cookie Notices filter, EasyList Cookie List

### Language-specific

AdGuard Turkish filter

### Add your comment and screenshots

1. there are cookie notices.

2. Screenshots
<details><summary>Screenshot:</summary>

![Screenshot_20241130_094342_Quetta](https://github.com/user-attachments/assets/fdda6c7b-e64b-4a96-97da-23559b3bd99d)

<details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
We use trusted rule. Ad blockers don't load them from third-party filters.
`gdh.digital#%#//scriptlet('trusted-set-local-storage-item', 'cookie_accepted', '-1')`
