### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by oleedd** [AdguardTeam/AdguardFilters#19395]
@BlazDT
http://178.32.87.115/jetapi/?file=15121531044592
There seems to be a timer until the "Download" button appears.
![screenshot](https://user-images.githubusercontent.com/36125949/42418946-d8cfcc06-82b3-11e8-8f5e-d26a61904394.png)
Also a bug - I couldn't create an issue with adguard-bot for this url.

**Comment by BlazDT** [comment]
Sadly nothing to speed up there as the site waits for an answer of mali.php which gives download path.
