### ISSUE TITLE
rdxhd.me [Fake Links & Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#19396]
**Site**: https://rdxhd.me/newe/download/1517/Sanju_(2018).html

**Issue**: Please remove the fake links as shown on the page. Also seeing pop-ups.
 
**Screenshot**: http://prntscr.com/k3wbmg

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 67.0.3396.99 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Only reproduced "Search movies" ad and popup. Please try this rule for the other ads:

`rdxhd.me##.sprt`

**Comment by Nzzyme** [comment]
Pop-up and "Search Movies" fixed. Still seeing the other links.

http://prntscr.com/k4l0p8

Tried the rule you gave and it only changes the look and feel of the fake links. Fake links direct to 

http://34.220.213.60:8080/........ 
if that helps

**Comment by BlazDT** [comment]
Sadly it doesn't even show without adblocker and in code that IP is not showing up :(
Could you please inspect the ad links (right click -> inspect element) and post a screenshot, thank you.

**Comment by Nzzyme** [comment]
Here you go:

http://prntscr.com/k6azjh

**Comment by BlazDT** [comment]
Please try this rule:

`rdxhd.me##a[onclick][target="_top"] > img`

**Comment by BlazDT** [comment]
Any news?

**Comment by Nzzyme** [comment]
I tried that rule but I am still able to see the fake links

http://prntscr.com/k8p3rk

Can't we block this ip?

http://35.163.226.61:8080/...

**Comment by BlazDT** [comment]
According to the new screenshot the rule did hide something (the green buttons). Can you post a screenshot for those text ads please.

Why block this IP address? I don't see it in requests and not in your screenshot.

**Comment by Nzzyme** [comment]
That is very strange. The green buttons are from Kaspersky link checker informing that the links are safe.

When I move the mouse pointer over those fake links, I see the url address beginning with that ip address.

**Comment by Nzzyme** [comment]
Site is either down or location restriction in place since a long time. Please close this. Thank you.
