### ISSUE TITLE
Freedom SMS: Free Text To PH - can we remove a placeholder?

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1943]
https://play.google.com/store/apps/details?id=free.text.sms&hl=en

![image](https://cloud.githubusercontent.com/assets/15856304/14410099/a05a7462-ff2e-11e5-97df-5c536dc9be9f.png)

![image](https://cloud.githubusercontent.com/assets/15856304/14410101/abdc90ea-ff2e-11e5-9ca7-0e1d4ddba349.png)

The Adchoices ad is blocked with HTTPs filtering, but the placeholder in the top of the screen still remains.

**Comment by tjpixes** [comment]
![screenshot_2016-04-09-11-51-58](https://cloud.githubusercontent.com/assets/18402024/14434013/50d47256-0043-11e6-9cb6-d3c6f84002aa.png)

**Comment by evgeniy-ADG** [comment]
Please check the ticket, we have logs https://kb.adguard.com/staff/index.php?/Tickets/Ticket/View/276784

**Comment by Alex-302** [comment]
Please check these rules:
```
||hkshort.weixin.qq.com^
||hkextshort.weixin.qq.com^
||amazonaws.com/appodeal
```

**Comment by tjpixes** [comment]
requires username and pass

**Comment by tjpixes** [comment]
alex, i cant read chinese.. amazonaws, no idea

**Comment by Alex-302** [comment]
@evgeniy-ADG 
bump

**Comment by tjpixes** [comment]
Still getting pop up ads. Pls help. Sometimes it pops up a video ad

**Comment by Alex-302** [comment]
@tjpixes 
with the rules above?

**Comment by tjpixes** [comment]
Do i need to. Copy and paste that to adguard?

**Comment by Alex-302** [comment]
I've added them to mobile filter. Please check for updates, then check the app.

**Comment by Alex-302** [comment]
I recommend to clear the app cache.

**Comment by tjpixes** [comment]
updated adguard and cleared cache of the app. stated it right after. tada i
got an ad.

I recommend to clear the app cache.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/AdguardTeam/ExperimentalFilter/issues/1943#issuecomment-213463691>

**Comment by Alex-302** [comment]
Please make a new HTTP log. I will try to find solution.

**Comment by tjpixes** [comment]
restarted phone. cleared cache again. recording http req. no ads atm. will
give feedback later or tomorrow or when an ad pops up. thanks

**Comment by Alex-302** [comment]
Ok. I hope it is clean now)

**Comment by tjpixes** [comment]
lol it just appeared. you jinxed it. xD. feedback sent

**Comment by Alex-302** [comment]
@tjpixes 
i need the ticket number

**Comment by tjpixes** [comment]
https://kb.adguard.com/index.php?/Tickets/Ticket/View/ICJ-664-54339

**Comment by Alex-302** [comment]
Please make a new screenshot of ad. Maybe that's because this app starts before Adguard protection.

**Comment by Alex-302** [comment]
I don't see unblocked requests. You can try these rules for testing(Facebook will be broken):
```
||facebook.com^$empty
||mopub.com^$empty
||akamaihd.net^$empty
```

**Comment by tjpixes** [comment]
Same as the other one. Just got the ad after reading ur reply. Ok will try
the rules.

**Comment by tjpixes** [comment]
After filter. Just black.

**Comment by tjpixes** [comment]
After removing facebook from filter

**Comment by Alex-302** [comment]
Very strange.
Please close this app in Android settings, clear cache. Then stop and start Adguard. Add 
```
||facebook.com^$empty
||mopub.com^$empty
||akamaihd.net^$empty
```
Then start your app and remember starting time. And send a message to the support and tell me ticket ID and starting time.

**Comment by tjpixes** [comment]
Ok  ill do that. For now i cant use the app while adguard protection is
turned on. Cant send messages.

**Comment by Alex-302** [comment]
well, you can remove recently added rules

**Comment by tjpixes** [comment]
ok. just let me know. im at work and phones are not allowed so i really
could not do it earlier

**Comment by tjpixes** [comment]
Getting pop ups still. Tried "roll the ball" app i get the same black
screen pop up just like in freedom sms. Also updated adguard and used http
thing. Any fix for this or nothing we can do at this point? Or still
working on it? Thanks

**Comment by Alex-302** [comment]
Did you removed this app from network exclusions in low level settings?

**Comment by tjpixes** [comment]
No. Please tell me how to do it. Thanks for everything.

**Comment by Alex-302** [comment]
I don't see this app in exclusions list...
