### ISSUE TITLE
r10.net ads

### ISSUE THREAD

**Issue by Raidware** [AdguardTeam/AdguardFilters#194406]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

ublock with adguard filters

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://www.r10.net/gundemdeki-konular-haberler/3841833-gorev-siteleri-artik-yasaklandi-mi.html

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Other Annoyances filter, Fanboy's Annoyances, EasyList Cookie List

### Language-specific

AdGuard Turkish filter

### Add your comment and screenshots

1. there are banner ads on that website.

2. Screenshots
<details><summary>Screenshots:</summary>

![Screenshot_20241210_161001_Quetta](https://github.com/user-attachments/assets/e8adb991-1357-4f1b-b45e-da0588918678)
![Screenshot_20241210_160939_Quetta](https://github.com/user-attachments/assets/fffc80ab-42b5-4fa4-9f64-27d44d33cd72)

<details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Can't access. @jellizaveta @BlazDT Please take a look.

**Comment by BlazDT** [comment]
Should have been blocked by added rules in Turkish filters. Can you please manually check for updates.

**Comment by BlazDT** [comment]
Thanks for reminder. Please try this rule in user filter:

`r10.net##.ra5ac8f`

**Comment by Alex-302** [comment]
Maybe `.rae1fc7`?

**Comment by BlazDT** [comment]
Added some rules, update available in about 3-4 hours.

**Comment by fastphpdev** [comment]
hey @BlazDT @Alex-302 
with the latest commit, post contents and panels are not visible. this is a **critical issue** and all members are complaining. Could you please revert the changes?
ex: https://www.r10.net/sorum-var/4306846-bir-tek-bende-mi-mesajlar-vb-gozukmuyor.html
thanks!

**Comment by BlazDT** [comment]
As mentioned in other issue it is shown fine for me. Which rule exactly breaks it?

**Comment by fastphpdev** [comment]
![resim](https://github.com/user-attachments/assets/dc28353b-b491-4ca2-8e76-88b3a83c2bcc)

it’s completely wrong, especially within topics where someone shares a link like r10.net##div[class]:has(> a[target="_blank"][rel]), the content of the thread isn't visible.

link is available in the previous message.

**Comment by BlazDT** [comment]
Thank you, disabled rule, update available in about 3-4 hours.
