### ISSUE TITLE
com.mercariapp.mercari

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#194452]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.8

### What type of problem have you encountered?

Missed analytics or tracker

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.mercariapp.mercari

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Legitimate URL Shortener, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Add your comment and screenshots

gw-dv.vip is in easyprivacy. we should add similar domain: gw-dv.io

the above two domains may not show right away.

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
What about gw-dv.io and cdn-gw-dv.vip @Alex-302

**Comment by Alex-302** [comment]
`||gw-dv.vip^` is in Tracking Protection filter.
Added `||ls.cdn-gw-dv.vip^`
