### ISSUE TITLE
nextdoor.com

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#194549]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.8

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://nextdoor.com/news_feed/?from_nux

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

can sponsored ads be hidden? 
![Screenshot_20241212_155002_Samsung Internet](https://github.com/user-attachments/assets/e0a6e19e-7a5f-419c-b416-7b0d96da64fe)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
I can't register anymore. They banned my account a long time ago. Could you please register a test account?

**Comment by jordansworld** [comment]
messaged u the login on telegram @Alex-302
