### ISSUE TITLE
twitter ad subdomains

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#194610]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.8

### What type of problem have you encountered?

Missed ads or ad leftovers, Missed analytics or tracker

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

Twitter.com

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

ads-api.twitter.com
syndication.twitter.com

havd had these blocked for weeks. doesnt break the app or the website version or embedded stuff.

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
these domains are also located in hagezi list

**Comment by jordansworld** [comment]
@Alex-302

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/195335
syndication.twitter.com will be removed
