### ISSUE TITLE
freevee video ads

### ISSUE THREAD

**Issue by jordansworld** [AdguardTeam/AdguardFilters#194609]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Android

### AdGuard version

4.8

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Which device do you use?

Mobile

### Where is the problem encountered?

https://play.google.com/store/apps/details?id=com.amazon.imdb.tv.mobile.app

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

s3-iad-ww.cf.videorolls.row.aiv-cdn.net
s3.ll.videorolls.row.aiv-cdn.net

have been testing this filter for awhile. Everything works fine with this blocked. it is also in hagezis lists.

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
@Alex-302 can we reopen

**Comment by jordansworld** [comment]
looks like they added a new one: s3.ll.videorolls.row.aiv-cdn.net

**Comment by Alex-302** [comment]
The second is not for main ads

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/f42db24e-1935-4ee1-8ff0-89b9cec00be2)


</details>

Added `||s3-iad-ww.cf.videorolls.row.aiv-cdn.net^`

**Comment by jordansworld** [comment]
@Alex-302 found a tracker can we add it;

events.watchtower.imdbtv.amazon.dev

**Comment by jordansworld** [comment]
@Alex-302 i think we should try blocking s3.ll.videorolls.row.aiv-cdn.net aswell as my freevee app reached out to it today

**Comment by jordansworld** [comment]
Unfortunately i only have an apple tv and roku to test on. it works fine when blocked there but i dont have a desktop

**Comment by Alex-302** [comment]
We have `||videorolls.row.aiv-cdn.net/*.mp4$media,redirect=noopmp3-0.1s,domain=amazon.com` - just URL blocking breaks the video.

**Comment by jordansworld** [comment]
> We have `||videorolls.row.aiv-cdn.net/*.mp4$media,redirect=noopmp3-0.1s,domain=amazon.com` - just URL blocking breaks the video.

oh youve tested blocking the s3.ll.videorolls.row.aiv-cdn.net and it breaks video your saying?

**Comment by Alex-302** [comment]
No, we use the redirect rule on amazon.com because a rule without the modifier breaks a player.
