### ISSUE TITLE
http://pikabu.ru

### ISSUE THREAD

**Issue by dtitbd** [AdguardTeam/AdguardFilters#1947]
Сверху огромная реклама танков, сбоку она же. И спонсорские ссылки полезли, хотя раньше резало. Версия 2.5 бета, фильтры обновлены.
![screenshot_2016-04-11-02-38-00](https://cloud.githubusercontent.com/assets/17032471/14413298/37e205c4-ff8f-11e5-815a-788b00ec4fa9.png)

**Comment by Alex-302** [comment]
fixed

**Comment by vgavrish** [comment]
http://pikabu.ru/new
Баннеры Яндекс.Директ. Реклама появляется не каждый раз. Может минут через 15-20 просмотра сайта.
Firefox, IE
Фильтры: 1,2,3,4,14
Ссылка на сохраненную страницу:
https://yadi.sk/d/NlmHnGDQuafwq
Скрины
<details>
![screenshot_1](https://cloud.githubusercontent.com/assets/18548949/18061819/e83a303e-6e2c-11e6-892d-753fb73e57a8.jpg)
![screenshot_21](https://cloud.githubusercontent.com/assets/18548949/18061818/e8386a60-6e2c-11e6-8ec0-ea8a28ce4486.jpg)

**Comment by Alex-302** [comment]
Не повторяется. Архивы пригодились.
Добавил в русский фильтр
```
pikabu.ru##div[id^="yandex_ad_"]
```
