### ISSUE TITLE
Adguard and problem with few polish sites.

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#19481]
Windows 10 and MS Edge with Adguard extension (generally, because I don't know, how is in different systems).
All filters (without reek and don't block acceptable ads). 

Problem is hmmm... frustrated. poczta.o2.pl doesn't load, I don't see messages on centrum 24 on bzwbk.pl site and chat on tukero.org is hidden. I understand exclussion for github.com but I must add too this three sites on exclussion sites (whitelist) and it will be work later. Can help me? 
Best regards

**Comment by BlazDT** [comment]
Please enable only filters from AdGuard and check again.
Also please post screenshots of the issues in a new issue - one for each site.

**Comment by seba2282** [comment]
Can you tell me name filters, which I should have turn on to tests fix for my problem?

**Comment by BlazDT** [comment]
English, spyware, annoyance filters and if you don‘t like social widgets Social filter.
If the errors are gone, please enable Polish filters and check again.

**Comment by seba2282** [comment]
Ok. I will try but later. Thanks for suggest. 😊

**Comment by seba2282** [comment]
Sorry for my small activity here. If I will be on PC, I will try suggest with combinations filter. But on actually it isn't possible, because I am few days without home. 
Best regards

**Comment by seba2282** [comment]
I tried all options and sometimes worked sometimes not. Maybe it is bug in MS Edge for me.
