### ISSUE TITLE
Еще один сайт с майнером mediafire.com

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#19499]
На страницах загрузки файла, работает майнер судя по всему...
http://www.mediafire.com/file/cly5bdb3mf9z1fq/M%26M+10+Save+Game+Converter+v3.1.zip

**Comment by Alex-302** [comment]
Не похоже. Запросов не вижу, которые отправляют майнеры.

**Comment by Smorvel** [comment]
Хм, ну что то там не так.. При открытии сразу загрузка процессора на 30% если отключить JS тогда все в порядке... ну шяс попробую найти какой скрипт грузит..
