### ISSUE TITLE
легион.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1950]
http://xn--c1adkjnf.net/
Some ads are not blocked - http://prntscr.com/aqs37o
Press anywhere on the page and get this - http://prntscr.com/aqg9o1

**Comment by Alex-302** [comment]
в пользовательский:
```
легион.net###text-23
легион.net##div[style=" margin-top: 80px ; padding: 10px 0 5px 1px; background-color: #F0F0F0; border-radius: 8px; box-shadow: 8px 8px 6px  #000000;"]
```
в русский:
```
||bb.легион.net/c/*.js
||легион.net/wp-content/uploads/2016/02/200x170-180x153.png
```

**Comment by vgavrish** [comment]
На главной в самом низу легион.net
![screenshot_5](https://cloud.githubusercontent.com/assets/18548949/16115728/9dd4168a-33d1-11e6-864c-5aed596d4556.jpg)

**Comment by Alex-302** [comment]
||withnewswearebest.com^$third-party
