### ISSUE TITLE
flowplayer.space whitelist

### ISSUE THREAD

**Issue by hoshsadiq** [AdguardTeam/AdguardFilters#19503]
Below filter (added in #19019) whitelists a mining site. Can we get it removed please?

https://github.com/AdguardTeam/AdguardFilters/blob/4514d806db0fcf23053dbb81e678f9da7e958294/EnglishFilter/sections/whitelist.txt#L286

See https://github.com/hoshsadiq/adblock-nocoin-list/issues/271 and https://github.com/hoshsadiq/adblock-nocoin-list/commit/3d11ee6c65ca285d2f011ad9e162312c4f6641d2

Additionally, the following filters should be added to the mining filters:
```
||flowplayer.space^
||thersprens.com^
||gramombird.com^
```

**Comment by AdamWr** [comment]
Done.
Thank you.
