### ISSUE TITLE
batmanrehbergazetesi.com

### ISSUE THREAD

**Issue by Raidware** [AdguardTeam/AdguardFilters#195139]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

Ublockorigin with adguard filters

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Mobile

### Where is the problem encountered?

https://batmanrehbergazetesi.com/haber/214795-sanliurfa-barosundan-seyh-saide-hakaret-iceren-urune-tepki

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, EasyList Cookie List

### Language-specific

AdGuard Turkish filter

### Add your comment and screenshots

1. there are cookie notice.

2. Screenshots
<details><summary>Screenshot 1:</summary>

![Screenshot_20241223_115743](https://github.com/user-attachments/assets/e4d5c92c-334a-48bf-8d6d-5f216d9a4242)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
This site has too little traffic.
Please add to user rules: `batmanrehbergazetesi.com###fixed-bottom`
