### ISSUE TITLE
block joinhoney.com/

### ISSUE THREAD

**Issue by olumolu** [AdguardTeam/AdguardFilters#195127]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Browser Extension, AdGuard DNS

### AdGuard version

all

### What type of problem have you encountered?

Dangerous site

### Which browser(s) do you use?

Firefox, Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

joinhoney.com/

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Add your comment and screenshots

https://m.youtube.com/watch?v=vc4yL3YTwWk

### Privacy

- [X] I agree to follow this condition

**Comment by olumolu** [comment]
https://github.com/StevenBlack/hosts/commit/4033d2bc2662f267bcd7d6e5a49f292bd0286643
https://github.com/hagezi/dns-blocklists/issues/4666

**Comment by jellizaveta** [comment]
There doesn't seem to be any effect from the blocking
