### ISSUE TITLE
RFE/C: Use tools to wholesale block highly-suspect TLDs

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardFilters#19515]
_N.B.: Not using template, as it doesn't seem to relate to suggestions.  If I missed something, I apologize! 🙇_

@AdguardTeam https://krebsonsecurity.com/2018/06/bad-men-at-work-please-dont-click/ & comments lists some tools that, w/ _very_ high probability, identify [TLDs](https://www.icann.org/registrar-reports/accredited-list.html) that are almost exclusively used for malware/spam/&c.:

- [ ] https://www.spamhaus.org/statistics/tlds/
- [ ] https://www.symantec.com/blogs/feature-stories/top-20-shady-top-level-domains & linked

There also seems to be a high correlation of NameCheap-registered TLDs w/ malware/&c, but that may be something handled better via AGDNS.

What d'y'all think?

**Comment by ameshkov** [comment]
We discuss it once internally. The problem is that "shady" does not mean malicious or phishing and blocking the TLD completely is a bit too much.

**Comment by TPS** [comment]
That's _theoretically_ true, but definitely _practically_ worth for its own DNS-compatible <kbd>Highly Suspicious</kbd> filterlist, which would/could whitelist _(very rare)_ known-good domains.  I mean, did y'all _see_ those stats⁉️  It's terribly unlikely this would false-positive.

**Comment by ameshkov** [comment]
> I mean, did y'all see those stats⁉️ It's terribly unlikely this would false-positive.

The stats do not show the traffic distribution. Even `.com` zone is full of phishing domains, but their traffic share is tiny.

**Comment by TheHasagi** [comment]
Will be reopened if necessary.

**Comment by TPS** [comment]
I ran into this again.  Was there any further discussion, especially re: SpamHaus's TLD (& other linked) tools?

**Comment by Alex-302** [comment]
You can block them using https://adguard-dns.io/
