### ISSUE TITLE
JPN: Adguard Japan Filter blocks yahoo's blog service in japan

### ISSUE THREAD

**Issue by penguishPenguin** [AdguardTeam/AdguardFilters#19523]
The following filter included in Adguard Japan blocks the following non-blocking domains.
filter:||b*.yahoo.co.jp^
blocked domain:blogs.yahoo.co.jp

As you can see, blogs.yahoo.co.jp is just a blog service domain and should not be blocked.

**Comment by BlazDT** [comment]
Thank you for reporting, fixed.
