### ISSUE TITLE
'News' modern app in Windows 10

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#1952]
Recreated issue from Adguard for Windows: https://github.com/AdguardTeam/AdguardForWindows/issues/1024

When you start 'News' app for the first time, it crushes after a small period of time. After that, everything is fine until you restart the computer. Then it happens again, etc.

Originally from: http://forum.adguard.com/showthread.php?10465

**Comment by Alex-302** [comment]
@vbagirov 
проверю

**Comment by ameshkov** [comment]
@Alex-302 так и не воспроизводится?

**Comment by ameshkov** [comment]
> Добрый вечер, есть проблема со стандартным приложением Новости на Windows 10 и фильтрацией Адгард в нем. У меня WFP включен следовательно фильтрация в этом приложении идёт и рекламы нет, но постоянно один раз за сеанс случается вылет приложения. То есть я открываю после включения компьютера в Новостях какую то статью и приложение вылетает, потом при следующем запуске вылетов нет, но после перезагрузки/выключения опять происходит однократный вылет... То же самое кстати было еще с 5 версией, при добавлении приложения вручную в список браузеров.

**Comment by Alex-302** [comment]
@ameshkov нет, не повторяется.

**Comment by vgavrish** [comment]
Снова в приложении реклама
http://radikal.ru/lfp/s019.radikal.ru/i640/1611/e4/782a15de1f81.png/htm
Ф: 1,2,3,4,5,211
6.1.258.1302
Driver Type: Wfp
HTTPS filtering enabled: True
