### ISSUE TITLE
Missed AD on www.ruodian360.com

### ISSUE THREAD

**Issue by 0x391F** [AdguardTeam/AdguardFilters#195360]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

N/A

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Firefox

### Which device do you use?

Mobile

### Where is the problem encountered?

https://www.ruodian360.com/tech/security-monitoring/43618.html

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard URL Tracking filter, AdGuard Tracking Protection filter, EasyPrivacy, Peter Lowe's Blocklist

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Chinese filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

![IMG_20241228_131029](https://github.com/user-attachments/assets/7bb93e3b-3f35-4379-9497-10809c53c205)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Can't access
![image](https://github.com/user-attachments/assets/e227ef95-51a9-441a-93ed-3dc8e95739f4)

**Comment by 0x391F** [comment]
@Alex-302 Is there any team members whoblive in China? I can access this website. I think it limit that only China IP could access it.

**Comment by Alex-302** [comment]
@0x391F No:( Do you know how we can access to internal Chinese resources? Our Chinese VPN does not help.  It seems only residential proxy may help.

**Comment by 0x391F** [comment]
> @0x391F No:( Do you know how we can access to internal Chinese resources? Our Chinese VPN does not help. It seems only residential proxy may help.

Can you try VPN Gate? It's free and almost always include VPN servers in China: https://www.vpngate.net

**Comment by 0x391F** [comment]
@Alex-302 I find the way to block this ad: the ad points to bcd.ruodian360.com/hmjnxtvd, and it will redirect to wangmeng.baidu.com, which has been blocked, so we can simply block **bcd.ruodian360.com**.

**Comment by Alex-302** [comment]
Hmmm. Redirects what - when you click ads?
Could you please capture a HAR file?

How to get a HAR file:
https://toolbox.googleapps.com/apps/har_analyzer/

**Comment by 0x391F** [comment]
> Hmmm. Redirects what - when you click ads? Could you please capture a HAR file (without login)?
> 
> How to get a HAR file: https://toolbox.googleapps.com/apps/har_analyzer/

@Alex-302 It seems useless. I use uBlock Origin's element selector to detect the link. I couldn't find it by HAR file.

**Comment by Alex-302** [comment]
We don't use element selector tools for creating rules. Maybe an ad is loaded by obfuscated script.

**Comment by 0x391F** [comment]
@Alex-302 Can you try tencent cloud https://www.tencentcloud.com/? I test on China site https://cloud.tencent.com/, it works, but I don't know if international site. You should select China server region and **remember to delete server after finish**.

**Comment by Alex-302** [comment]
> delete server after finish

which server? I did not get about tencentcloud.com

**Comment by 0x391F** [comment]
Cloud sever you use to visit www.ruodian360.com

**Comment by Alex-302** [comment]
I don't see China in the list, only Japan, Korea, Thailand and few other servers.

**Comment by 0x391F** [comment]
> I don't see China in the list, only Japan, Korea, Thailand and few other servers.

Unfortunately you seems right. Could you try this method? https://github.com/AdguardTeam/AdguardFilters/issues/195360#issuecomment-2569404741

**Comment by Alex-302** [comment]
Please test these rules:

```
||abc.ruodian360.com^
||cpu.baidu.com/block/wap/
! track
||lf1-cdn-tos.bytegoofy.com^
||cpu.baidu.com^
```

**Comment by 0x391F** [comment]
> Please test these rules:
> 
> ```
> ||abc.ruodian360.com^
> ||cpu.baidu.com/block/wap/
> ! track
> ||lf1-cdn-tos.bytegoofy.com^
> ||cpu.baidu.com^
> ```

They work well.

**Comment by Alex-302** [comment]
Added
