### ISSUE TITLE
dizilla.club

### ISSUE THREAD

**Issue by retta1** [AdguardTeam/AdguardFilters#195431]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard Content Blocker, Other ad blocker

### AdGuard version

stable 

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Microsoft Edge

### Which device do you use?

Desktop

### Where is the problem encountered?

dizilla.club

### Ad Blocking

AdGuard Base filter

### Language-specific

AdGuard Turkish filter

### Add your comment and screenshots

dizilla.club###psContainer to block sidebar adverts

### Privacy

- [X] I agree to follow this condition

**Comment by retta1** [comment]
@AdamWr and site url changed to dizilla10.com you should add 10 11 12 etc to list.

**Comment by AdamWr** [comment]
I cannot find `#psContainer` element, please add a screenshot with marked ad on it.

**Comment by retta1** [comment]
> I cannot find `#psContainer` element, please add a screenshot with marked ad on it.

![image](https://github.com/user-attachments/assets/0919273f-77fe-47ae-9630-8cab0ac22700)

**Comment by AdamWr** [comment]
Done.
Thank you.

**Comment by retta1** [comment]
@AdamWr I found another leftover 
![Screenshot_20250101_161018_Edge](https://github.com/user-attachments/assets/70d68469-bce7-49f5-8422-6e2a5ed61779)
to hide that dizilla10.com###footerFixedDivWrapper
it's on mobile version

**Comment by AdamWr** [comment]
Okay, I have added this rule.
