### ISSUE TITLE
ad-text.ru - broken interface

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1954]
ad-text.ru
ADG on:![screenshot_1](https://cloud.githubusercontent.com/assets/14153331/14422774/1fe429d2-ffe1-11e5-9b7b-76b3d0847170.png)
ADG off:![screenshot_2](https://cloud.githubusercontent.com/assets/14153331/14422775/213c4332-ffe1-11e5-96d1-5cc892ecf62b.png)
SGI-953-55190

**Comment by Alex-302** [comment]
исправлено
