### ISSUE TITLE
axutongxue.net

### ISSUE THREAD

**Issue by Bush2021** [AdguardTeam/AdguardFilters#195528]
### Prerequisites

- [X] This site DOES NOT contain sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for Windows

### AdGuard version

7.19.0 (4853)

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

Chrome

### Which device do you use?

Desktop

### Where is the problem encountered?

https://axutongxue.net/

### Ad Blocking

AdGuard Base filter

### Language-specific

AdGuard Chinese filter

### Add your comment and screenshots

https://github.com/axutongxue/axutongxue.github.io/blob/c07418d0de5f966e384f2b76f24e4f094a4c2d1a/js/jquery.js#L250

<details><summary>Screenshot:</summary>

![image](https://github.com/user-attachments/assets/91dfd834-47a6-42ac-8a0b-901c3843ef8d)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jordansworld** [comment]
What's the problem. not understanding

**Comment by Bush2021** [comment]
> What's the problem. not understanding

The bright white box in the screenshot is a pop-up advertisement.

https://github.com/AdguardTeam/AdguardFilters/issues/145574
