### ISSUE TITLE
ANA app crush with adguard

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1958]
https://play.google.com/store/apps/details?id=jp.co.ana.android.tabidachi

When disable it, ANA app works fine.

Please check logs: AAH-995-42736

**Comment by Alex-302** [comment]
@evgeniy-ADG 
прога на японском, не знаю как повторить вылет. Попроси у юзера описание со скринами, и уточни, есть ли в проге реклама, может просто исключим её.

**Comment by Alex-302** [comment]
Передай на пробу
```
@@||ana.112.2o7.net/b/ss/
```

**Comment by evgeniy-ADG** [comment]
Жду.

**Comment by Alex-302** [comment]
.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
нет ответа?

**Comment by Yuki2718** [comment]
@Alex-302 As far as I could test the app works fine with all these 2o7 staff blocked.

![logs](https://user-images.githubusercontent.com/58900598/78565350-bfe2fa00-7858-11ea-8bb1-f100eedbf5a5.png)

So please remove the whitelist now, unless & until we get a new qualified report - this tracker is also used on their websites.

**Comment by Alex-302** [comment]
ok, removed
