### ISSUE TITLE
incomplete ad block

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#19598]
@kims602 commented on [Wed Jul 11 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/1971)

### Steps to reproduce

1. Just start app
2. I can see grey box end of the app about 5 seconds
3.
4.

### Expected behavior

![image](https://user-images.githubusercontent.com/41120778/42581156-15f8868a-8567-11e8-9083-407734d96965.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/41120778/42581085-f0f7e362-8566-11e8-9331-7d7610278466.png)

<details><summary>Screenshot:</summary>

</details>

### Customer ID 

1727740
### Your environment

* Adguard version: 2.11.81
* Adguard filtering mode: VPN
* Device model: Xiaomi redmi note 5
* Operating system and version (e.g. Android 7.1.2) Android 8.1
* Rooted or not?  No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

**Comment by zebrum** [comment]
@kims602 please provide a link to the app you've mentioned. What filters are enabled in AdGuard?

**Comment by Alex-302** [comment]
What is wrong with it?
