### ISSUE TITLE
mail.ru - yandex direct

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1962]
https://e.mail.ru/messages/inbox/

![image](https://cloud.githubusercontent.com/assets/15856304/14472936/551c9e18-00fe-11e6-86c7-1db30b9d2766.png)

базовый набор фильтров, полезная реклама выключена

**Comment by Alex-302** [comment]
@evgeniy-ADG 
программа или расширение? Какой браузер?
Этот юзер вроде уже на мейл жаловался. Попроси его проверить с одним русским фильтром, обязательно без пользовательского.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
ну что там?

**Comment by Alex-302** [comment]
@evgeniy-ADG 
bump

**Comment by evgeniy-ADG** [comment]
Опера 12.16, Хром. Ранее до переустановки программа давила директ  во всех браузерах.
Мы попросили проверть польз фильтр еще раз. Скрин мой, хром, на момент регистрации - все обновленное. Сейчас у меня рекламы нет, помощник на месте.

**Comment by evgeniy-ADG** [comment]
Guys, у пользователя лезет яндекс директ, нам любезно записали доходчивое видео: https://cloud.mail.ru/public/3Pua/gNs1j5raF

Что мы можем с этим сделать и куда копать? Тикет долгоиграющий, хотелось бы решить поскорее. Спасибо.

NDE-496-49717

**Comment by aiv3006** [comment]
Женя привет ! Меня Андрей зовут, я автор этих видео-скриншотов .Браузер у меня Chromium 50 ,так же пробовал в Slimjet ,гугл хром ситуация одна и таже.Меньше всего директ атакует в мозиле   .Так же как вариант можно посоветоваться с Денисом он разработчик ява скриптов так же создатель https://chrome.google.com/webstore/detail/stop-reclame/ohmkcnojelglgphmkgmofjlmpoelccjh его сайт с контактами http://skychko.com/

**Comment by aiv3006** [comment]
В облаке отсутствует помошник http://pic-mir.ru/allimage/0/1/4/8/4/148439.jpeg 
https://cloud.mail.ru/home/ 
https://cloud.mail.ru/public/K36A/JVrsJxkJu

**Comment by Skychko** [comment]
Добрый день! 

Я разработчик Stop Reclame. Андрей сообщил о данной теме.
Наверняка, Вы уже владеете информацией о проблеме. Тем не менее, выскажу свои мысли, возможно, Вам это поможет.
Действительно данная проблема присутствует, более ярко она выражена на сайте fs.to.
Причина: сайты сбрасывают примененные css-фильтры блокировщиков на странице. К сожалению, не владею информацией каким образом они это делают.

Что реализовано в Stop Reclame? 
1. CSS-фильтры добавляются несколько раз, триггером для добавления фильтра служит блокировка запроса на картинку или фрейм.
2. CSS-фильтры добавляются непосредственно с тегом style и дополнительно дублируются в document.styleSheets (причина: на некоторых сайтах style подчищается).

Как результат, если после сброса стилей на странице были запросы (image, frame), которые расширение блокирует, то реклама будет скрыта. Если же данного запроса не было, то реклама будет отображаться. К сожалению, Stop Reclame также на 100% не защищает от данного типа рекламы.

По-хорошему, нужно выяснить как происходит сброс стилей, попытаться перегрузить соответствующие методы (добавить сниферов) и обновлять css-фильтры после вызова этих методов.

**Comment by Alex-302** [comment]
@aiv3006 
у меня Slimjet. Реклама блокируется. Удалённо бы глянуть. Чтоб появился помощник, отключите в русском фильтре правило
`@@||cloud.mail.ru^$jsinject`
и проверьте, не пропали ли какие-нибудь элементы сайта. Ну и отпишитесь о результате. Правило старое и возможно уже не актуальное(старая проблема при выключении правила не повторяется)

@Skychko 
добрый день. На fs.to мне попасть сложно, но вроде рекламу блокируем(судя по cxz.to)
По поводу сброса стилей - у них там дичайшие скрипты. Но у нас не все стили косятся, только специфичные для этого сайта.

**Comment by aiv3006** [comment]
Алккс правило в фильтре отключил 
@@||cloud.mail.ru^$jsinject
Помошник появился кешь чистил все равно борода http://pic-mir.ru/allimage/0/1/4/8/4/148459.jpeg

**Comment by Alex-302** [comment]
@aiv3006 
удалённо смотреть нужно, через team viewer. Если готовы - можете выслать ID и пароль в личку на нашем форуме

**Comment by evgeniy-ADG** [comment]
LXR-605-46982 тут тоже проблема, которая у нас не повторяется
![image](https://cloud.githubusercontent.com/assets/15856304/15408837/d2a5a6d4-1e1a-11e6-809b-0b1fc5acef96.png)

**Comment by Alex-302** [comment]
Похоже на старые фильтры.

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/15485026/b07359a2-2145-11e6-92f2-55b554f6165a.png)
TICKET ID
BBP-360-98501

<details>

Os version: Microsoft Windows NT 6.0.6002 Service Pack 2
Dot .net version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile; 4.5.1 Windows 8;
ApplicationId: 37f25fc7d3e54d72a2c9c66c22b2486f
Language: ru
AppVersion: 6.0.226.1108
Main settings: 
Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:10 Name: Filter for useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Tdi
Ads Blocked: 221326, Trackers Blocked: 137250
Filtering Mode: Driver
Application lifetime: 78.19:30:28.4498162
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": true,
  "HideUserAgent": true,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": true
}




</details>

**Comment by Alex-302** [comment]
Даже не знаю. Какой там адрес? В тикете не видно.

**Comment by aiv3006** [comment]
Да  че адрес тут и так видать "мой мир " маил ру ! У меня такой же гемор был с директом который отслеживает все что ты ищещь в нете

**Comment by evgeniy-ADG** [comment]
Да, сорри. Это стартовая моего мира.

**Comment by vgavrish** [comment]
Проблема в Chrome
![40bf1-clip-224kb](https://cloud.githubusercontent.com/assets/18548949/15632582/0fcd6bdc-25a0-11e6-87ee-95db4e576373.jpg)
TICKET ID HWG-208-52061

**Comment by Alex-302** [comment]
@evgeniy-ADG @vgavrish у меня чисто. У вас повторяется?

не нужно в одну ишью размещать проблемы разных юзеров и разделов, неудобно же. А вот прямую ссылку на страницу крайне желательно сразу давать.

**Comment by vgavrish** [comment]
у меня с my.mail.ru не повторяется с программой

Проблема на:
https://e.mail.ru/messages/inbox/

Расширение. Браузер Хром.
Фильтры: http://prntscr.com/bjvq5u
Скрин: http://prntscr.com/bjvqgg

**Comment by Alex-302** [comment]
на проверку:
```
my.mail.ru#%#AG_onLoad(function() { function __adgObserver() { var observer = new MutationObserver(function(mutations) { mutations.forEach(function(mutation) { __adgRemoveDirect() }) }); observer.observe(document.body, { childList: true, characterData: true, subtree: true }) } var __adgRemoveDirect = function() { try { __adgRemoveMyMailRu(); console.log('REMOVED!!!'); } catch (ex) {} }; var __adgRemoveMyMailRu = function() { AG_each('a[href^="/my/clicker?mna="]', function(node) { AG_removeParent(node, function(parent) { return parent.className && parent.className.indexOf("b-history-event") >= 0 }) }) }; __adgRemoveDirect(); __adgObserver();});
```
```
e.mail.ru#$#div[data-mnemo="letters"] > div[class="b-datalist__head"][style^="display: block !important; visibility: visible !important;"] { left: -2000px!important; }
```

**Comment by vozersky** [comment]
в почте https://e.mail.ru/messages/inbox/ повторилось в расширении для хрома, win
на маке все ок

**Comment by Alex-302** [comment]
@vozersky из предыдущего сообщения проверял?

**Comment by vozersky** [comment]
@Alex-302 ```e.mail.ru#$#div[data-mnemo="letters"] > div[class="b-datalist__head"][style^="display: block !important; visibility: visible !important;"] { left: -2000px!important; }``` не помогло

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/279

**Comment by Alex-302** [comment]
добавлено временное решение

**Comment by vgavrish** [comment]
1177032 Директ. Значок Помощника отображается. Отключение расширений, откл антивируса не помогает.
https://e.mail.ru/messages/inbox/ 
Версия: 41.0.2353.46   - Используется обновленная версия Opera
Система: Windows 
Скрин: http://screenshot.ru/upload/image/Z5At
AppVersion: 6.1.258.1302
Фильтры
<details>
Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:5 Name: Experimental filter Url: http://adguard.com/ru/filter-rules.html?id=5
FilterId:14 Name: Annoyances filter Url: http://adguard.com/ru/filter-rules.html?id=14
FilterId:104 Name: EasyList China Url: https://easylist-downloads.adblockplus.org/easylistchina.txt
FilterId:105 Name: EasyList Czech and Slovak Url: 
FilterId:115 Name: RU AdList Url: https://easylist-downloads.adblockplus.org/advblock.txt
FilterId:208 Name: Malware Domains

**Comment by Alex-302** [comment]
Аналогично этой задаче
https://github.com/AdguardTeam/AdguardFilters/issues/2063

**Comment by vgavrish** [comment]
> это не чего не помогает
http://ipic.su/img/img7/fs/kiss_657kb.1478676792.png

**Comment by Alex-302** [comment]
Странно.
