### ISSUE TITLE
https://letyshops.ru/view/13366481 - cant access a store through this site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1963]
1. go to https://letyshops.ru/
2. register via social network, for instance
3. chose a store
4. press 
   ![image](https://cloud.githubusercontent.com/assets/15856304/14473162/676b3970-00ff-11e6-900d-280789aeb9f8.png)
5. see the error
   ![image](https://cloud.githubusercontent.com/assets/15856304/14473115/39e8431c-00ff-11e6-85e9-d9a5e7674d9b.png)

**Comment by Alex-302** [comment]
добавил в русский фильтр:
```
@@||letyshops.ru/sites/all/modules/*/advert.js
```

**Comment by evgeniy-ADG** [comment]
They say the issue is back: 1613574
