### ISSUE TITLE
apkinstaller.com

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#19682]
[http://apkinstaller.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fapkinstaller.com%2F)

 Стилевая защита от копирования, как здесь: https://github.com/AdguardTeam/AdguardFilters/issues/19217#issuecomment-403136711
 Стиль, в котором строчки защиты: [http://apkinstaller.com/default/style.css](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fapkinstaller.com%2Fdefault%2Fstyle.css)
 Сами строки:
```
.card { ... -webkit-user-select:none; user-select:none; ... }
.tiles { ... -webkit-user-select:none; user-select:none; }
```

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.9.2 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
У меня всё копируется.

**Comment by XX-J** [comment]
<details><summary>Не выделяется текст на главной странице:</summary>

![2018 07 16-1](https://user-images.githubusercontent.com/17948007/42766334-e2fa2c06-8922-11e8-94b2-c891487d2150.png)
</details>

**Comment by XX-J** [comment]
Исправьте, пожалуйста...

**Comment by Alex-302** [comment]
ок

**Comment by XX-J** [comment]
Вы немного напутали: домен в правило не вставили, а стили продублировали.
 А также в соседнем правиле дублируется домен `toptech360.com`.

**Comment by Alex-302** [comment]
поправил
