### ISSUE TITLE
[Android] Redirect is blocked from shareasale.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1969]
1. English, spyware, social media, german, useful ads, mobile filters enabled.
2. Open http://www.shareasale.com/r.cfm?u=966602&b=573201&m=52031&afftrack=cg&urllink=www.gearbest.com%2Fearphones%2Fpp_197277.html
3. Result is a filtered white page in the browser -> redirect is not happening.
   Adding shareasale.com to whitelist didn't help.

Reporter - WFD-195-15507

**Comment by Alex-302** [comment]
this domain is used for advertising.
Please try
@@||shareasale.com^

**Comment by Alex-302** [comment]
@Bohdan-SUP

**Comment by Bohdan-SUP** [comment]
Notified user.
