### ISSUE TITLE
Global filters not working (at least sometimes) on merriam-webster.com

### ISSUE THREAD

**Issue by levonder** [AdguardTeam/AdguardFilters#19717]
(last Chrome on macOS Sierra 10.12.6)

Sample page:

https://merriam-webster.com/dictionary/erstwhile

This works:

`merriam-webster.com##.social-sidebar`

While this doesn't

`##.social-sidebar`

Why? Such rules seem to work on other sites.

**Comment by BlazDT** [comment]
This is the reason:

@@||merriam-webster.com^$generichide

**Comment by levonder** [comment]
@BlazDT what does it mean? :D Does it means that there's a default rule (in default filters?) for the website to ignore global rules?

**Comment by BlazDT** [comment]
Correct, very likely due to some adblock measurements of the site - the rule comes from EasyList which our English filter is based on.
