### ISSUE TITLE
Bracket-style filters not working sometimes on merriam-webster.com

### ISSUE THREAD

**Issue by levonder** [AdguardTeam/AdguardFilters#19711]
(Last Chrome on macOS)

`merriam-webster.com##.full-cnt` works, but `merriam-webster.com##div[class="full-cnt"]` doesn't.

I thought it should work, because e.g. on https://translate.google.com both of these work:
- `translate.google.com##.g-section`
- `translate.google.com##div[class="g-section"]`

**Comment by BlazDT** [comment]
Your rule will only the element when  the class name is only "full-cnt". On the mentioned site the class is "full-cnt clearfix bg-white padding-lr-0p8em" and that is why the first rule with only .full-cnt is working and the 2nd is not working.

translate.google.com only has the class name g-section and therefore both rules work.
