### ISSUE TITLE
http://momocast-tv.appspot.com/help/en/inapp/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#1975]
If connected to momocast, ads are not blocked:

1. before connecting:
![image](https://cloud.githubusercontent.com/assets/15856304/14502377/ae22be4c-01b3-11e6-8403-8391b67102d0.png)

2. after: 
![image](https://cloud.githubusercontent.com/assets/15856304/14502371/a6646a98-01b3-11e6-902c-7c226a25f5fc.png)

<details>
Application version: 1.0.5.38
Application lifetime: 2016-02-27 00:30:55 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.1
ID: DB7D8402-F102-47BF-97FF-DB38C01133F1

Locale: en
Region: ca

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.81.61 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.27 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.34 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.89 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.32.89 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.8 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=113 Name="Liste FR" Version=1.0.56.7 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.55.91 Enabled=YES

**Comment by Alex-302** [comment]
I can't fix it without remote access
Or, describe, please, how to login

**Comment by evgeniy-ADG** [comment]
hz, have asked for details description.

**Comment by Bohdan-SUP** [comment]
This happens on Apple devices: iphone, ipad. It goes like this:

1) I’m using Safari. I want to play a video from, let’s say, couchtuner.ag. When I play it on the local player there are no problems: adguard blocks all the ads successfully.

2) When I want to cast the video to my TV trough Chromecast I use the Momocast extension by tapping the Action icon in Safari. This brings the cast icon on the right corner of the screen but also let all the ads show up and fills the screen with their BS.

That’s what happens.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
можешь попросить юзера выключить все фильтры, и проверить снова, не выключая самого Адгарда?

**Comment by Bohdan-SUP** [comment]
Нет новостей. Я открою снова, если будет нужно.
