### ISSUE TITLE
Adguard detected on https://itascan.info

### ISSUE THREAD

**Issue by Snake87r** [AdguardTeam/AdguardFilters#19763]
Hello, when visiting this site:
https://itascan.info/view/Tenkuu-Shinpan/04/21176/

I receive the message "Disabilita il blocco della pubblicità per proseguire." and I have to disable adguard to see the site (they use a script to detect adguard and other adblocker)

Your environment

Adguard version: 2.11.81
Adguard filtering mode: VPN
Device model: Sony Xperia Z4 Tablet
Operating system and version (e.g. Android 7.0)
Not Rooted

Filter Setup:

English Filter
Spyware Filter
Social Media Filter
Annoyances Filter
Mobile ads filter
Simplified domain names filter
EasyList Italy
Anti-adblock killer | Reek

**Comment by BlazDT** [comment]
Fixed - update will be available in 2-3 hours.
