### ISSUE TITLE
Cannot run google internet speed test

### ISSUE THREAD

**Issue by zefwef** [AdguardTeam/AdguardFilters#19783]
***Description***:
The internet speed test built into Google search will not run with Adguard turned on on both Android and Mac.

***Steps to reproduce the problem***:
1. Search "internet speed test" in Google.
2. Click "Run speed test"
3. The window will stuck at the "contacting server" screen unless adguard is turned off.

**Filters:**

[//]: # English, Spyware

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android or macOS
Operating system version (Android/iOS) | Android 9
Browser:                               | Chrome
AdGuard version:                       | Latest on both Android and Mac
Filters enabled:                       | English, Spyware
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Works fine on my Android - please check @AdamWr

**Comment by AdamWr** [comment]
I don't see Internet speed test in Google search, even without AdGuard.

**Comment by zefwef** [comment]
Try testing directly on https://speed.measurementlab.net/#/

**Comment by AdamWr** [comment]
Thank you for the link.
Unfortunately it seems that it's not a filter lists issue, but a bug, because it happens even with all filter lists disabled.
Reported here - https://github.com/AdguardTeam/CoreLibs/issues/396
