### ISSUE TITLE
[iOS] Missed Ads liga.net

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#1980]
http://m.liga.net/
Проверено.
![image1](https://cloud.githubusercontent.com/assets/16462533/14537211/b9b64b68-027e-11e6-9234-15acc9205906.PNG)

**Comment by Alex-302** [comment]
На маке не повторилось. В винде у вас повторяется, если с мобильным юзерагентом зайти?

**Comment by Bohdan-SUP** [comment]
С юзерагентом в десктопном Сафари не повторилось.
@Serzh-SUP проверь на iPhone, пожалуйста, еще раз.

**Comment by Serzh-SUP** [comment]
@Alex-302 @Bohdan-SUP 
Есть реклама.

**Comment by Alex-302** [comment]
@Serzh-SUP 
не повторяется даже с выключенным Адгардом. Можешь на десктопе повторить без Адгарда? Я бы удалённо глянул и добавил правила.

**Comment by Alex-302** [comment]
На айпаде тоже не повторилось.

**Comment by Serzh-SUP** [comment]
@Alex-302 
Попробовал на десктопе без Adguard, не повторяется... Наверно только на iose.

**Comment by Serzh-SUP** [comment]
@Alex-302 
Попробовал на десктопе без Adguard, не повторяется... Наверно только на iose.

**Comment by Alex-302** [comment]
Проверь такое:
`||source.mmi.bemobile.ua/cm/cm.js$domain=m.liga.net`

**Comment by Serzh-SUP** [comment]
@Alex-302 
не помогло.

**Comment by Alex-302** [comment]
поймал наконец. Добавил в мобильный
liga.net##body > div[id^="holder_320x"][style]
