### ISSUE TITLE
pr.sape.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1995]
http://pr.sape.ru/ блокирует нужную информацию в всплывающем окне:
adg off - http://prntscr.com/asvvks
adg on - http://prnt.sc/asy7u9

Процедура повторения проблемы:
Регистрация - Пополнение счета - Создание проекта - Создание заявки (ссылка в новости) - Выбор площадки - Ожидание выполнения заявки вебмастером - Подтверждение заявки.

На скриншоте, где видна информация, красной линией выделена не вся информация окна. Правее линии ещё серое поле, которое относится к окну и также при работе Adguard пропадает.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
передай на проверку. Не хочется деньги туда класть:)
```
@@||pr.sape.ru/advert/new
@@||pr.sape.ru/advert/$generichide
```

**Comment by Bohdan-SUP** [comment]
Передал.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
нет ответа?

**Comment by Bohdan-SUP** [comment]
Нет. Я отпишу, если что.

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/14786576/40778950-0b08-11e6-99dd-176c880d11c2.png)

> Добрый день!
> 
> К сожалению, данные правила не решили проблему.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
тогда только удалённо смотреть
