### ISSUE TITLE
[Android] buchpirat.org

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#1999]
1. Go to buchpirat.org
2. Tab anywhere.
3. adf.ly/puopen/xxx opens in a new tab.
   STV-641-76441

**Comment by Alex-302** [comment]
Can't confirm.
Please check
```
||cdn.adf.ly/js/display.js$domain=buchpirat.org
```

**Comment by Bohdan-SUP** [comment]
Still happens.
Added rule to userfilter and now it opens play.leadzu.com/?m=S4UAPOPADS

**Comment by Alex-302** [comment]
Ask for new HTTP log please.

**Comment by Bohdan-SUP** [comment]
Check this one - FXW-727-87339

**Comment by Alex-302** [comment]
Maybe my rule was not added to user filter.
Added it to mobile filter.
User should to check again after filters update.
