### ISSUE TITLE
Advert of yandex product in yandex search

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2003]
Здравствуйте! Реклама яндекс браузера на сайте яндекс не блокируется, занимает половину страницы, на остальных сайтах после обновления рекламы не вижу. Спасибо!

![image](https://cloud.githubusercontent.com/assets/15856304/14615609/28c80c34-05af-11e6-8657-ded680ffde05.png)
![image](https://cloud.githubusercontent.com/assets/15856304/14615618/2ef9ac70-05af-11e6-8dff-574d566eae53.png)

HEX-770-78646

**Comment by Alex-302** [comment]
Что-то поймать не могу. У тебя повторяется?

**Comment by evgeniy-ADG** [comment]
у меня нет устройства. попрошу Сержа, у него у одного есть.

**Comment by Serzh-SUP** [comment]
@Alex-302 
Я такое ловил, отключая фильтр полез.рекл. сейчас не получается, но может потому, что яндекс.браузер установлен на тел. Попробуй откл.

**Comment by evgeniy-ADG** [comment]
Включить фильтр полезной рекламы? А это не разлочит всю полезную рекламу, как на винде и андроиде?

**Comment by Alex-302** [comment]
@Serzh-SUP так фильтр полезной некламы не блокирует ничего, а наоборот - отключает некоторые правила.
@evgeniy-ADG 
можете у юзера уточнить, есть ли ещё эта реклама?
