### ISSUE TITLE
christianforums.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#20044]
Banner after first thread on frontpage and first post on thread pages:

```
https://www.christianforums.com/
https://www.christianforums.com/threads/what-s-really-wrong-with-society.8073175/
```

Adguard Base Filters

**Comment by BlazDT** [comment]
Please post your AdGuard product and a screenshot of the banners - I can't see them.

**Comment by adranger** [comment]
Thanks for the reply. I actually use your filters (Base+Mobile+RUS+span,por) with uBlock Origin. Contributors of uBO and EasyList acknowledged the banners, but won't add the filter(s) to their own lists:

https://github.com/uBlockOrigin/uAssets/issues/2911#issuecomment-405116926
https://forums.lanik.us/viewtopic.php?p=138767#p138767

### Frontpage

![frontpage](https://user-images.githubusercontent.com/35470489/43363363-8a1196ea-92d9-11e8-93fb-e75f3c0bd718.png)

### Thread

![banner thread](https://user-images.githubusercontent.com/35470489/43363346-36e23286-92d9-11e8-9c65-60244d2f597e.png)


```
<div style="padding: 10px 0px 0px 0px; font-size: 14px; text-align: center;">We teamed up with <a style="font-weight: bold;" href="http://go.tryonlinetherapy.com/aff_c?offer_id=14&amp;aff_id=2479&amp;source=Banner Ad 2">Faith Counseling</a>. Can they help you today?</div>
<div style="padding: 5px 0px 10px 0px; text-align: center; margin: 0 auto;">
<a href="http://go.tryonlinetherapy.com/aff_c?offer_id=14&amp;aff_id=2479&amp;source=Banner Ad 2"><img src="https://www.christianforums.com/fcbeard.jpg"></a>
</div>
```

Is this hidden by some other built-in Adguard filter?

**Comment by BlazDT** [comment]
Thank you - added to English filter:

```
christianforums.com##.ctaFtListItemsPage > div[style^="padding: "][style*="text-align: center;"]
christianforums.com##.message > div[style^="padding: "][style*="text-align: center;"]
```

The rules they supposed would have only hidden the banner - not the text above it.
