### ISSUE TITLE
https://cloud.mail.ru/home/ - missed ads, no assistant

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2005]
https://cloud.mail.ru через раз блокирует рекламму именно в г.хроме помошник отсутствует также в маил почте,облаке,поисковике от майла ,стабильно помошника наблюдаю только на главной странице майла ( кеш ,историю чистил не помогает ) http://pic-mir.ru/allimage/0/1/4/3/6/143667.jpeg

Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:109 Name: EasyList Italy Url: https://easylist-downloads.adblockplus.org/easylistitaly.txt
FilterId:111 Name: Latvian List Url: https://notabug.org/latvian-list/adblock-latvian/raw/master/lists/latvian-list.txt
FilterId:116 Name: Juvander AdblockFinland Url: https://raw.githubusercontent.com/wiltteri/wiltteri.txt/master/wiltteri.txt
FilterId:0 Name: User filter Url: no_url

**Comment by Alex-302** [comment]
У меня нормально.
Какая версия Адгарда? Браузер? В другом браузере повторяется?

**Comment by evgeniy-ADG** [comment]
У меня нет асистанта, хром, все последнее, самое новое и современное. В фф тоже. Может, мы его завайтлистили?.. Рекламы не вижу, к слову.

**Comment by Alex-302** [comment]
Да, помощника нет из-за исключения. Уже удалено.
Уточни у юзера про рекламу. Пусть проверит только с русским и английским.
