### ISSUE TITLE
1movies.se [Ads & Pop-ups]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#20063]
**Site**: https://www2.1movies.se/movie/big-game/10977-watch-online-free.html

https://www2.1movies.se/movie/deadpool-2/114727

**Issue**: Please remove the ads & pop-ups on the page.
 
**Screenshot**: http://prntscr.com/k9hqfh   and    http://prntscr.com/k9huad

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 67.0.3396.99 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Fixed popunder and ads. Unsure about captcha element. @AdamWr please check.

**Comment by AdamWr** [comment]
If we hide captcha then video player will not work.
