### ISSUE TITLE
gogomovies.us [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#20074]
**Site**: http://gogomovies.us/2018/06/04/the-purge-the-island/

**Issue**: Please remove the fake links as seen in the screenshot.
 
**Screenshot**: http://prntscr.com/k9j13p

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 67.0.3396.99 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
No visitors.

**Comment by Nzzyme** [comment]
The site won't open anyway now :(
