### ISSUE TITLE
[AnnoyancesFilter] getmdl.io - .mdl-snackbar should not be blocked

### ISSUE THREAD

**Issue by SamLex** [AdguardTeam/AdguardFilters#20081]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
This is the same #10589, but with an example and following the template.

***Description***:
* **Current behaviour**: 
  * .mdl-snackbar, used by the Material Design Lite framework, is blocked everywhere.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/733683/43047449-41a05842-8dcf-11e8-8e5b-d2608343d8cf.png)

</details><br/>

* **Expected behaviour**: 
  * Snackbar is not be blocked everywhere.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/733683/43047477-978587a0-8dcf-11e8-9656-267037ef74fa.png)

</details><br/>

***Steps to reproduce the problem***:

* Browse to https://getmdl.io/components/index.html#snackbar-section
* Press the "SHOW" button at the top.

***System configuration***

**Filters:**

AnnoyancesFilter, via uBlock Origin

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Linux
Browser:                               |  Chromium

**Likely Cause**
https://github.com/AdguardTeam/AdguardFilters/blob/abc9a132fb61726f32a51411ce38260f3371b96d/AnnoyancesFilter/sections/cookies_general.txt#L1297

**Comment by Alex-302** [comment]
ok, removed this rule
