### ISSUE TITLE
http://m.imore.com/canada - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2009]
Missed ad on page:
http://m.imore.com/canada

![image](https://cloud.githubusercontent.com/assets/15856304/14645140/45a99904-065d-11e6-9ae8-b1d1f38ea130.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.81.95 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.36 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.41 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES

**Comment by Alex-302** [comment]
Can't reproduce on iPad

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/15114404/8827420e-1602-11e6-9fdc-e9ff03dc97a5.png)
HIE-434-82140
<details>
Application version: 1.0.5.38
Application lifetime: 2016-05-07 06:10:09 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.1
ID: FACCCAEF-3788-4AFA-AE30-2E358C2BE4EF

Locale: en
Region: us

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.83.72 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.66 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.71 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.48 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=101 Name="EasyList" Version=1.0.57.53 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.57.58 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.61 Enabled=YES

**Comment by Alex-302** [comment]
it is absolutely clean on our iPad
Try to disable
ID=101 Name="EasyList" Version=1.0.57.53 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.57.58 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.61 Enabled=YES

**Comment by Bohdan-SUP** [comment]
User confirmed it's fixed.
