### ISSUE TITLE
http://forum.na-svyazi.ru/index.php 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2013]
http://forum.na-svyazi.ru/index.php
http://prntscr.com/au27on
- блокируется кнопка "Редактировать"
  ![image](https://cloud.githubusercontent.com/assets/15856304/14649122/5a0ba1e2-066e-11e6-9b9e-5e5a5ed62a8f.png)

![image](https://cloud.githubusercontent.com/assets/15856304/14649136/6311a930-066e-11e6-967f-a0bce459712a.png)

XXO-868-68797

**Comment by Alex-302** [comment]
@evgeniy-ADG 
не нужно советовать переустановку при ложном срабатывании. Передай плиз тому, кто это советовал.
Я зарегистрировался, но кнопка редактирования не активна для недавно зарегистрировавшихся.
Доступ к аккаунту нужен.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
bump

**Comment by evgeniy-ADG** [comment]
Done.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
удалённый доступ не просили?
