### ISSUE TITLE
hdrezka.me

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#2030]
Example:
![Screenshot](https://cloud.githubusercontent.com/assets/17472907/14763137/9bfd99d2-0995-11e6-9bd2-1184b10064a7.JPG)

**Comment by Alex-302** [comment]
added
||byrgin.ru^$third-party

**Comment by vozersky** [comment]
не помогло

**Comment by Katakikuto** [comment]
This block appears again :(

**Comment by evgeniy-ADG** [comment]
http://hdrezka.me/films/fiction/13910-faterlyand.html
http://prntscr.com/b84us3

а еще вот такое пишут:
Добавить в фильтры вот такие правила: ||hdrezka.me$$script[type="text/javascript"][tag-content="stabctbv.hdrezka.me"] ||hdrezka.me##div#e654d8aec9 ||hdrezka.me##div#ee9d0d6723

**Comment by Katakikuto** [comment]
Они подставляют под скрытие плеер и другие элементы сайта, и моментально реагируют на новые фильтры. Но дали возможность отключить рекламу: http://hdrezka.me/noadvert/ - эти тизерные блоки не отображаются.

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/15584485/7801c33e-2383-11e6-9d0a-e39582a6cc53.png)

<details>
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.84.92 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.88 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.94 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.25.39 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.78 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.34.18 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.62 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.51 Enabled=YES
ID=101 Name="EasyList" Version=1.0.46.60 Enabled=NO
ID=115 Name="RU AdList" Version=1.0.51.96 Enabled=NO
ID=122 Name="Fanboy's Annoyances" Version=1.0.46.71 Enabled=NO
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.46.59 Enabled=NO
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.0.88 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.53.53 Enabled=NO
ID=209 Name="Prebake" Version=1.0.1 Enabled=NO
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.57 Enabled=NO
ID=212 Name="RU AdList: Counters" Version=1.0.50.9 Enabled=NO
ID=213 Name="RU AdList: BitBlock" Version=1.0.46.49 Enabled=NO

**Comment by Alex-302** [comment]
Да, здесь лучше выключать кнопкой.

**Comment by shaurmanchic** [comment]
![screen shot 2016-06-07 at 9 49 42 pm](https://cloud.githubusercontent.com/assets/14258460/15870743/f6d7eeac-2cf9-11e6-81e7-cef537aa8dea.png)
Вернулась реклама

**Comment by Alex-302** [comment]
У нас чисто. Фильтры свежие?

**Comment by Katakikuto** [comment]
Подставляют плеер под скрытие: http://f.cl.ly/items/2l0T0L2J3J2I2S0X0q1Y/Screen%20Shot%202016-06-09%20at%209.58.38%20PM.png
И описание к видео не отображается...

**Comment by Alex-302** [comment]
@Katakikuto 
ссылка, фильтры, версия адгарда?

**Comment by Katakikuto** [comment]
Google chrome extension, фильтры обновлены. Пример, где применяется блокировка: http://hdrezka.me/series/comedy/14958-bong-vremeni.html
Прикол, они послание оставили :)
![screen shot 2016-06-09 at 10 08 51 pm](https://cloud.githubusercontent.com/assets/3155555/15942852/f5277906-2e8e-11e6-9697-c4b6fc4dfb0a.png)

**Comment by Alex-302** [comment]
да видел это. Однажды с одними даже переписка в консоли браузера состоялась.
Удалил из русского:
hdrezka.me##div[id][onclick*="cancel_bubbling"][class^="b-post"]

**Comment by Lolitka50** [comment]
Example:
http://kkkino.net/load/bodibilder/30-1-0-6011

**Comment by Alex-302** [comment]
@Lolitka50 а что здесь не так?

**Comment by Yana-SUP** [comment]
Реклама снова на сайте:
![screen shot 2016-10-19 at 9 19 33 pm](https://cloud.githubusercontent.com/assets/22892774/19531842/d576f29c-9641-11e6-8b84-10cde448953c.png)

Фильтры:
![screen shot 2016-10-19 at 9 19 45 pm](https://cloud.githubusercontent.com/assets/22892774/19531861/e7d5664e-9641-11e6-816f-93b50ae1df58.png)

Сафари 10, расширение 2.4.10

**Comment by Alex-302** [comment]
Добавил в фильтр Сафари
```
hdrezka.me##body > div[id][class][style^="background-image: url(data:image/jpeg;base64"]
```
