### ISSUE TITLE
cartoonhd.io [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#20315]
**Site**: https://cartoonhd.io/film/the-lord-of-the-rings-the-fellowship-of-the-ring

**Issue**: Please remove the adblock message on the page.
 
**Screenshot**: http://prntscr.com/kbqfyc

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 67.0.3396.99 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by AdamWr** [comment]
I can't reproduce it.

Do you still see that adblock message?

**Comment by BlazDT** [comment]
Can't reproduce.

**Comment by Nzzyme** [comment]
Don't see the adblock message anymore. Thanks
