### ISSUE TITLE
afdahmovies.org [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#20316]
**Site**: https://afdahmovies.org/

**Issue**:

On the homepage (https://afdahmovies.org/) please remove the fake "Play Now" links at the bottom of every movie poster (http://prntscr.com/kbqk9m)

To watch a movie, one has to actually click on the movie poster. Now on this page, please remove the fake "Watch Movie", "Download HD" & "Watch Now" buttons. Also remove the fake video player on the top of the page. All seen in this screenshot (http://prntscr.com/kbqls4).

Fake "Download Now" button above the actual video player (http://prntscr.com/kbqm02).

 
**Screenshot**: See above

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 67.0.3396.99 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
No visitors.

**Comment by Nzzyme** [comment]
I observed that it actually takes you to afdah.live

That's sad. This domain was created on 08-08-2018 so obviously would not have many visitors yet. How many visitors visiting a site qualify for a issue fix and can you tell me how did you check the number of visitors visiting a site? At some point or the other, every website gets created and is new to public and gradually picks up popularity/visitors.
