### ISSUE TITLE
[iOS] filmix.net

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#2037]
Missed pop-up on the main page.

![ukjqyyxnjsg](https://cloud.githubusercontent.com/assets/17472907/14771036/89e905d6-0a87-11e6-8362-f3b748600c96.jpg)

**Comment by Alex-302** [comment]
С Адгардом на айпаде не повторилось.

**Comment by vozersky** [comment]
у меня повторилось 1 раз
