### ISSUE TITLE
yugopolis.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2044]
http://www.yugopolis.ru/news/k-ubijstvu-sochinskoj-pensionerki-mozhet-byt-prichastnaya-ee-19-letnyaya-vnuchka-91497

http://prntscr.com/aw56qm
http://prntscr.com/aw56tz
https://i.imgur.com/ByYZhsb.png

IIM-675-57096

**Comment by Alex-302** [comment]
yugopolis.ru##div[class^="banner-container"]
||yugopolis.ru/data/files/*_320h400

**Comment by vgavrish** [comment]
http://www.yugopolis.ru/news/ohrannik-torgovogo-centra-v-krasnodare-iznasiloval-prodavshicu-magazina-96841
Внизу страницы реклама
Ф: 1,2,3,4,11,14
![image](https://cloud.githubusercontent.com/assets/18548949/19230709/ad0d37ae-8ede-11e6-9601-26b5ce6f8a51.png)

**Comment by Alex-302** [comment]
Fixed.
