### ISSUE TITLE
diakov.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2047]
http://www.diakov.net/6144-jv16-powertools-x-4001472-final.html
![image](https://cloud.githubusercontent.com/assets/14153331/14801216/60bbd44e-0b50-11e6-9b8f-605112b9625d.png)
FIS-194-78194

**Comment by Alex-302** [comment]
на форуме уже почистил

**Comment by vgavrish** [comment]
http://www.diakov.net/8367-qoppa-pdf-studio-pro-1030.html
Кнопка без смысловой нагрузки:
http://prntscr.com/bkryrk
Расширение.
Фильтры: http://prntscr.com/bkryxk

**Comment by Alex-302** [comment]
||x-ip-wiz.com/bin.php
