### ISSUE TITLE
katcr.co

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#20499]
VPN ad at the top of the page:

`https://katcr.co/katsearch/page/1/test` (if it gives an error, search for "test" manually to get to the search results page).

AdGuard English+Mobile+Spyware+RUS+spa,por
uBlock Origin

**Comment by Alex-302** [comment]
Not reproduced. Please provide working URL and screenshot.

**Comment by adranger** [comment]
The URL is the one I mentioned, but you can't open it directly. That's why I said you have to search for something manually (or click on "Reload this page").

```
<div class=" alert alert--danger">
      <span class="alert alert--warning"> Warning : IP-LOGGED </span>
        &nbsp; &nbsp; <a class="button button--big button--icon-button button--special_icon" href="https://www.get-express-vpn.com/torrent-vpn?offer=3monthsfree&amp;a_fid=katcr" title="Protect your privacy" target="_blank"><i class="kf__lock button--dark"></i> <span>Protect your privacy</span> </a> &nbsp; &nbsp; Before you download, search, or do anything online: PLEASE protect your online privacy. Stop ISPs and Hackers Logging Your IP and Everything You Do
</div>
```

There's a button on the sidebar too:

```
<div class="logo">
	<small class="ad__cta">
		<img class="text--nowrap text--center" src="https://statuskatcrco-631f.kxcdn.com/assets/images/privacy_warning.gif" alt="Privacy warning" width="65" height="37">
	</small>
	<div class="logo__container site_logo text--nowrap text--center">
		<a class="button button--big button--icon-button button--special_icon" href="https://www.get-express-vpn.com/torrent-vpn?offer=3monthsfree&amp;a_fid=katcr" title="Protect your privacy" target="_blank"><i class="kf__lock button--dark"></i> <span>Protect your privacy</span> </a>
	</div>
</div>
```

![vpn](https://user-images.githubusercontent.com/6733770/43531185-aa8d748a-9585-11e8-9b71-46e12930b234.png)

**Comment by Alex-302** [comment]
Ok, fixed.

**Comment by adranger** [comment]
@Alex-302 

`https://katcr.co/torrent/679510/linux-lite-4-0-user-guide.html`

![katcr co](https://user-images.githubusercontent.com/35470489/50585175-e991c200-0e5a-11e9-8859-deefd53bd86d.png)
