### ISSUE TITLE
microsoft.com - "Is this page helpful?"

### ISSUE THREAD

**Issue by jbo-85** [AdguardTeam/AdguardFilters#20506]
Annoying "Is this helpful?" on microsoft.com at the bottom
For example: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-technical-documentation?view=sql-server-2017

<details><summary>Screenshot:</summary>
![grafik](https://user-images.githubusercontent.com/1428333/43484957-2879e4f8-9510-11e8-868e-48d8c9a35732.png)
</details><br/>

Fixed with this filter: microsoft.com###openFeedbackContainer

**Comment by Alex-302** [comment]
Do you see it on another sub-domains?

**Comment by jbo-85** [comment]
I didn't see it anywhere else. Thanks for the fix!
