### ISSUE TITLE
[iOS] arcor.de

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2057]
arcor.de
can't reproduce on a desktop with useragent
![img_0400 png](https://cloud.githubusercontent.com/assets/14153331/14824532/07665d76-0bdf-11e6-808d-c3db73e7d5bc.jpeg)
IEW-863-86894

**Comment by dartrax** [comment]
This is what it looks like on my Desktop:
![image](https://cloud.githubusercontent.com/assets/15105943/14824789/7b13fbbe-0bd7-11e6-81c1-461765f5d89a.png)
I needed to define some user filters to achieve this, using the block element function on desktop:
(Not sure if they are all required)
arcor.de###vyYLffd
arcor.de##DIV.pWrap:nth-child(2) > DIV.cWrap:nth-child(4) > DIV.pContent > DIV.cContent:first-child > DIV.content:nth-child(4) > DIV.contentGrid:first-child > DIV.row:nth-child(31)
arcor.de##DIV.pWrap:nth-child(2) > DIV.cWrap:nth-child(4) > DIV.pContent > DIV.cContent:first-child > DIV.content:nth-child(4) > DIV.contentGrid:first-child > DIV.row:nth-child(2) > DIV.col.grid4.teaserArea:nth-child(2) > DIV.TEaZzeZkP:nth-child(6)
arcor.de##DIV.pWrap:nth-child(2) > DIV.cWrap:nth-child(4) > DIV.pContent > DIV.cContent:first-child > DIV.content:nth-child(4) > DIV.contentGrid:first-child > DIV.row:nth-child(2) > DIV.col.grid4.teaserArea:nth-child(2) > DIV.row:nth-child(4)
arcor.de##DIV.pWrap:nth-child(2) > DIV.cWrap:nth-child(4) > DIV.pContent > DIV.cContent:first-child > DIV.content:nth-child(4) > DIV.contentGrid:first-child > DIV.col.grid4.teaserArea:nth-child(2) > DIV.VFpOYqw:nth-child(11)
arcor.de##DIV.pWrap:nth-child(2) > DIV.cWrap:nth-child(4) > DIV.pContent > DIV.cContent:first-child > DIV.content:nth-child(4) > DIV.contentGrid:first-child > DIV.col.grid4.teaserArea:nth-child(2) > DIV.TEaZzeZkP:nth-child(5)
arcor.de###CkdTiorvP
arcor.de###lCUSCMJF
arcor.de###byZgSn
arcor.de###vJiwiiDawc
arcor.de##DIV.pWrap:nth-child(2) > DIV.NUlWvBY:nth-child(2)

**Comment by Alex-302** [comment]
please check these rules
```
arcor.de##.advRight
@@/ad_bomb/*$image,domain=arcor.de
```

**Comment by dartrax** [comment]
I've added those rules to Adguard IOS.
First, everything looked fine like this:
![foto 27 04 16 11 34 52](https://cloud.githubusercontent.com/assets/15105943/14848066/32ac492c-0c6c-11e6-8b85-efd136ccd942.png)
After a few clicks on that site, this pop-up occured (and for some reason, the ads in the back appeared for a short time):
![foto 27 04 16 11 30 01](https://cloud.githubusercontent.com/assets/15105943/14848102/616802d8-0c6c-11e6-82b0-e4704ed8acbe.png)
Also, the page detects the ad blocker and blocks videos:
![foto 27 04 16 11 31 30](https://cloud.githubusercontent.com/assets/15105943/14848126/82fed408-0c6c-11e6-9eca-0edad385d542.png)
