### ISSUE TITLE
PopSugar.* - Required user action blocked (AdGuard Annoyances filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#20596]
### Affected sites:
```
https://www.popsugar.co.uk/
https://www.popsugar.com/
https://www.popsugar.com.au/
```
(Not sure about the `.com` and `.com.au` domains though, since this seems to be a GDPR thing)

### Issue:
Required user action (cookie consent) is blocked, preventing access to the sites.

### Problem filter:
AdGuard Annoyances filter

### Problem rule:
`###_evidon_banner`

### Possible fix:
`popsugar.*#@##_evidon_banner`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.9.4 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.4 (XUL)

**Comment by Alex-302** [comment]
Can't reproduce.
Please check:
`||c.evidon.com/sitenotice/evidon-barrier.js`

**Comment by THEtomaso** [comment]
> `||c.evidon.com/sitenotice/evidon-barrier.js`

Not so fast.. that doesn't fix anything!
For it to work, you HAVE to whitelist the cosmetic rule that I refered to in my first post!
The reason why you weren't able to reproduce the issue is probably because you're not accessing the site from within EU.
It's a GDPR problem, and only the `co.uk` domain seems to be affected.
So, the fix shuld be like this:
`popsugar.co.uk#@##_evidon_banner`

**Comment by THEtomaso** [comment]
Indeed, there seems to be some location- or browser dependent differences at work when trying to access the site, even from within the EU.
From my end, this is a essential script:
`https://c.evidon.com/sitenotice/evidon-banner.js`
..but for some other users, the very same script doesn't seem to be required at all, or even attempted to be accessed.
The same thing seems to be true for the cosmetic rule in question..
For some people, it completely blocks the cookie consent, and thereby prevents access to the site, while for other users, it doesn't matter at all!

More info here:
https://github.com/ryanbr/fanboy-adblock/issues/512/
https://github.com/ryanbr/fanboy-adblock/issues/512/

**Comment by THEtomaso** [comment]
I just gave it a try, using **SRWare Iron**, which is a Chromium-based browser..
The results were exactly the same as they were with **Pale Moon** and **SeaMonkey**, which are the other two browsers that I've tested this with.
So, I guess this rules out UA sniffing (and any other forms of browser discrimination) on the server-side.
The differences that we're experiencing must therefore be location-dependent!
I'm connecting from Norway, so if anyone is interested in trying to reproduce this iussue, I guess you should try connecting from a Scandinavian proxy.

**Comment by krystian3w** [comment]
`193.234.157.214`:`8080` and Bokmål / Nynorsk prefer language:

![image](https://user-images.githubusercontent.com/35370833/43676060-253f69c0-97ea-11e8-984f-3e347130f6ac.png) |
--- |

![image](https://user-images.githubusercontent.com/35370833/43676063-327953ee-97ea-11e8-98b4-908338dd43d9.png) |
--- |

**Comment by THEtomaso** [comment]
Very strange.
You're still getting a completely different cookie consent warning than I am.
Here's the one that I'm getting:

![filterissue-popsugar3](https://user-images.githubusercontent.com/9382674/43676470-a4a3ed66-97e1-11e8-892f-03283b956953.jpg)

I see that you were using a Swedish proxy though.
Do you have the option of using a Norwegian one by any chance?

**Comment by krystian3w** [comment]
> Do you have the option of using a Norwegian one by any chance?

Nope, few free when I tested did not allow connection.

---

> ..or perhaps you could just still use the Swedish one, and change your prefered language to English?

Then I keep the same that in English.

**Comment by THEtomaso** [comment]
The issue have been confirmed now, and it seems to be limited to non-EU European countries.
Read from this post and down:
https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-410451387

Perhaps now, Alex-302, you'll reconsider to include the necessary exceptions in your filter?

**Comment by Alex-302** [comment]
ok, added exclusion
