### ISSUE TITLE
tumblr app - missed sponsored posts

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2061]
https://play.google.com/store/apps/details?id=com.tumblr&hl=en

**Comment by Alex-302** [comment]
@Revertron 
could you please help with this app?
I can't look into https responces.

**Comment by ameshkov** [comment]
@Alex-302 it would be much better if you file a feature request to Android repo.

What you need is some "low level switch" making Adguard write HTTP/HTTPS content to some file.
I suppose it would be great if we can write this file in Fiddler format for easier analysis.

**Comment by Alex-302** [comment]
@ameshkov 
done
https://github.com/AdguardTeam/AdguardForAndroid/issues/502

**Comment by ameshkov** [comment]
Nice, thank you!

**Comment by Tetiana2020** [comment]
Sponsored ads in Tumblr reported again by user 1226970. 
Reproduced with all the basic filters and HTTPS filtering. 

Screenshot:
<details>

![screenshot_2016-11-27-23-09-26-1](https://cloud.githubusercontent.com/assets/17504743/20737678/f47672ae-b6b6-11e6-8079-b704f281a617.png)

</details>

**Comment by Alex-302** [comment]
Itis impossible, because SSL Pinning used in this app.
