### ISSUE TITLE
[WIN] Missed Ads Яндекс.Почта

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2063]
**Фильтры:** Пользовательский, Англ., Русс., Сис. аналит., Эксперим., Полезной рекламы

![2016-04-26_190733](https://cloud.githubusercontent.com/assets/16462533/14851676/2b0e942c-0c8a-11e6-9e28-028698ed38ed.png)

**Comment by Alex-302** [comment]
Чисто у меня
http://imagizer.imageshack.com/img922/2365/4anIf0.png
Какой браузер?

**Comment by Serzh-SUP** [comment]
@Alex-302 
Я в мазиле пробовал

**Comment by tester031** [comment]
Alex-302 у меня Cent Browser

**Comment by Alex-302** [comment]
@tester031 
так и не повторилось у меня. Фильтрация HTTPS включена?

**Comment by tester031** [comment]
Alex-302
я использую браузерное расширение.
все детали есть в ticket талоне  #GXS-866-37445

**Comment by Alex-302** [comment]
@tester031 
у вас сказано "проблема проявляется кратковременно". Что подразумевается под "кратковременно"? Мелькает и пропадает, или что?
Что с HTTPS из предыдущего моего вопроса?

**Comment by tester031** [comment]
Alex-302 
поясню про термин "кратковременно" - Ранее (пару месяцев назад  ) я также наблюдал подобную проблему ( только на странице яндекс почты - эту же проблему), но через некоторое время расширение стало блокировать данный тип рекламного блока.

Что касается   HTTPS - HTTPS где включено ? , в самом  браузере да, само же расширение Adguard ( для браузеров ) лишена  функции фильтрации по HTTPS.
это не программа где данная функция включена в настройках.

**Comment by Alex-302** [comment]
@tester031 
у меня не получается повторить. Нужно удалённо смотреть. Можете создать ещё один ящик для тестов.

**Comment by tester031** [comment]
Alex-302 мне скрывать нечего, я могу вам дать полный доступ через TeamViewer вам подойдёт такой вариант?

**Comment by Alex-302** [comment]
да. ID и пароль можно прямо сюда написать. Сейчас подключусь и сотру

**Comment by Alex-302** [comment]
Сегодня уже не выйдет, данные не выкладывайте. Смогу завтра. Данные для входа лучше на форуме в личку пришлите.

**Comment by tester031** [comment]
может вам удобнее мне в Skype написать?

**Comment by Alex-302** [comment]
давайте
alxbrv

**Comment by tester031** [comment]
Alex-302  вроде вас добавил.

**Comment by Alex-302** [comment]
Слева убрали, верхний пока не будем трогать

**Comment by vgavrish** [comment]
Реклама в почте. Браузер Edge, Yandex. Значок Помощника есть. У меня не повторяется
**Фильтры:**
Russian
English filter 
German filter 
Dutch filter 
Adblock polskie reguły
<details>
![screenshot_25](https://cloud.githubusercontent.com/assets/18548949/16900009/feb1b05a-4c1f-11e6-85b5-545d194c57fe.jpg)
![screenshot_26](https://cloud.githubusercontent.com/assets/18548949/16900010/feb38d62-4c1f-11e6-8fdc-310c0d5a58d5.jpg)
</details>

**Comment by Alex-302** [comment]
Тоже повторить не могу. Фильтрация HTTPS на сайте работает?

**Comment by vgavrish** [comment]
Должна
HTTPS filtering enabled: True

**Comment by Alex-302** [comment]
Может всё-тики не фильтруется? Пусть в журнале фильтрации посмотрит, есть ли в нём запросы открытые в Edge.

**Comment by vgavrish** [comment]
Это нужно выбрать опцию "Все запросы" и посмотреть или же другую?

Расширение.  Фильтры: 1,2,3,4,5
Cent Browser. У меня не повторилось.
http://prntscr.com/c646wa

**Comment by Alex-302** [comment]
речь же о программе
> Реклама в почте. Браузер Edge, Yandex. Значок Помощника есть.

В Edge на виртуалке у меня даже со старыми фильтрами чисто.

**Comment by vgavrish** [comment]
да, тут речь о программе

**Comment by Alex-302** [comment]
Так что с запросами HTTPS?:)
Сертификат нужно проверить.

**Comment by vgavrish** [comment]
а как посмотреть запросы https в журнале?
за сертификат написала

**Comment by Alex-302** [comment]
открыть журнал фильтрации и обновить вкладку(для надёжности с control+F5)
Если в журнале много запросов - значит фильтруется. Если 1-2 - то нет.
Префикс HTTP пусть не смущает, это небольшой баг.

**Comment by vgavrish** [comment]
ок буду знать. написала
также по поводу расширения. там могут предоставить удаленный

**Comment by vgavrish** [comment]
Сертификат:
<details>
![screenshot_1](https://cloud.githubusercontent.com/assets/18548949/17746078/28fbe2fe-64b7-11e6-8ccd-9e342c2b5caf.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/18548949/17746079/28fe0278-64b7-11e6-9ce2-4c38492c2ead.jpg)
</details>
Запросы:
<details>
![screenshot_3](https://cloud.githubusercontent.com/assets/18548949/17746102/42ac87f8-64b7-11e6-85e1-855669855ee2.jpg)
![screenshot_4](https://cloud.githubusercontent.com/assets/18548949/17746103/42aef722-64b7-11e6-924c-87faee98302a.jpg)
<details/>

**Comment by vgavrish** [comment]
1177032 Директ. Значок Помощника отображается. Отключение расширений, откл антивируса не помогает.
Версия: 41.0.2353.46   - Используется обновленная версия Opera
Система: Windows 
Скрин: http://screenshot.ru/upload/image/Z5Aq
AppVersion: 6.1.258.1302
Фильтры
<details>
Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:5 Name: Experimental filter Url: http://adguard.com/ru/filter-rules.html?id=5
FilterId:14 Name: Annoyances filter Url: http://adguard.com/ru/filter-rules.html?id=14
FilterId:104 Name: EasyList China Url: https://easylist-downloads.adblockplus.org/easylistchina.txt
FilterId:105 Name: EasyList Czech and Slovak Url: 
FilterId:115 Name: RU AdList Url: https://easylist-downloads.adblockplus.org/advblock.txt
FilterId:208 Name: Malware Domains

**Comment by Alex-302** [comment]
Ads are blocked on my end.
Try to disable
```
FilterId:104 Name: EasyList China Url: https://easylist-downloads.adblockplus.org/easylistchina.txt
FilterId:105 Name: EasyList Czech and Slovak Url: 
FilterId:115 Name: RU AdList Url: https://easylist-downloads.adblockplus.org/advblock.txt
FilterId:208 Name: Malware Domains
```

**Comment by Alex-302** [comment]
and check HTTPS certificate on this site.

**Comment by vgavrish** [comment]
уже предлагали пользователю. В итоге 

> Если я отключить те фильтры которые подключил дополнительно и оставлю только базовые как Вы предлагаете, то программа рекламу и банеры пропускать начинает на 65%

но постараюсь снова передать

если что сертификат: http://prntscr.com/d4yonu

**Comment by Alex-302** [comment]
Подозрительное утверждение. Только один пользователь жалуется на эте рекламу?
Пусть бету попробует. Не поможет - надо будет удалённо смотреть.

**Comment by vgavrish** [comment]
Нет, еще один пользователь появился, я ему тоже посоветовала бету поставить, жду результат

**Comment by Alex-302** [comment]
Ок, только что как раз новая вышла

**Comment by vgavrish** [comment]
Не помогло 
http://ipic.su/img/img7/fs/kiss_268kb.1478856943.png  
Предлагаю удаленку

**Comment by vgavrish** [comment]
@Alex-302 
skype ник
<details>
4erep

**Comment by Alex-302** [comment]
Их десятки таких. Лучше через наш чат сообщи когда он будет готов, подключусь.
