### ISSUE TITLE
Player at n24.de

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2065]
http://www.n24.de/n24/Mediathek/Live/
Can't reproduce on my side, user gets never ending loading:
![screenshot_20160424-111406](https://cloud.githubusercontent.com/assets/14153331/14858427/be823ace-0ca8-11e6-81ec-f3cf4cdd974a.png)
More details and logs here - XHS-111-38990

**Comment by Alex-302** [comment]
@Bohdan-SUP 
так iOS или Дроид? В ведре всё работает, можно для надёжности блокировки преролла включить ЭФ и качественный режим фильтрации.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
попроси юзера проверить без фильтров, потом включать по одному и отписаться о результате.

**Comment by Bohdan-SUP** [comment]
Юзеру отписал. У меня больше не повторяется.

**Comment by Alex-302** [comment]
Ок. Ждём юзера.
