### ISSUE TITLE
losmovies.cx [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#20715]
**Site**: http://losmovies.cx/free-movie/tt126397/watch-online-bad-samaritan

**Issue**: Please remove the pop-ups seen on the page.
 
**Screenshot**: N/A

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 68.0.3440.84 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
Not fixed. Still seeing pop-up that goes to zukxd6fkxqn.com

**Comment by Alex-302** [comment]
fixed
