### ISSUE TITLE
http://tushkan.tv/ - missed ads, pop-ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2073]
http://tushkan.tv/news/sinkhronnost_2015/2016-01-27-27741

![image](https://cloud.githubusercontent.com/assets/15856304/14893761/54137924-0d79-11e6-8f74-9753f5d89e92.png)

Чтобы увидеть поп-ап, нажмите на плеер:

![image](https://cloud.githubusercontent.com/assets/15856304/14893793/732e16b6-0d79-11e6-8a4c-b0cb36abf760.png)
У меня отклася такой: http://randevu-euro.com/?btag=a_5780b_357c_45

**Comment by Alex-302** [comment]
Баннера уже нет.
Для плеера:
||mix1traff.ru^$third-party
||msrv.su^$third-party

**Comment by Bohdan-SUP** [comment]
Поп-ап с плеером снова повторяется.
Появилась вот такая реклама:
![image](https://cloud.githubusercontent.com/assets/14153331/15273624/b769a52a-1aa8-11e6-8829-da5fb4182b5f.png)
