### ISSUE TITLE
urgrove.net [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#20751]
**Site**: https://urgrove.net/mission-impossible-6-2018-720p-free-download/2528/

**Issue**: Please remove the pop-up on the page.
 
**Screenshot**: N/A

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 68.0.3440.84 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
Not reproduced.
