### ISSUE TITLE
http://www.tveda.ru - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2079]
http://www.tveda.ru/video-recepty/mirovoy-povar/govyadina-v-soevom-souse-s-badyanom/

Блокируется видео
http://prntscr.com/ayyc5q

Помогает отключение Русского фильтра

**Comment by Alex-302** [comment]
видео разблокирует это правило
```
@@||sedu.adhands.ru/view/?sid=
```
но вместе с рекламой, которую пока не победил.
Исключение добавил.
