### ISSUE TITLE
ITavisen.no - Embeded videos blocked (AdGuard Spyware filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#20808]
### Affected site:
`https://itavisen.no/`

### Issue:
Embeded videos are blocked.

### Problem filter:
AdGuard Spyware filter

### Problem rule:
`||sixscissors.com^$third-party`

### Screenshot (unblocked video):

![filterissue-itavisen3](https://user-images.githubusercontent.com/9382674/43742222-9e7fa8fe-99c0-11e8-8341-939c81328039.jpg)

### Possible fix:
`@@||sixscissors.com^$third-party,domain=itavisen.no`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.9.4 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.4 (XUL)

**Comment by BlazDT** [comment]
Video is shown fine with url blocked.
Hid ad text.

@AdamWr please try to reproduce.

**Comment by THEtomaso** [comment]
I can confirm that the current video plays just fine with the URL blocked.
Things have either been changed server-side, or it may depend on which video they're showcasing.

**Comment by AdamWr** [comment]
Ok, it also works fine on my end, so I'm closing this issue.
Please reopen if it will happens again.
