### ISSUE TITLE
http://videos.hgtv.com/ - broken video playback

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2082]
http://www.hgtv.com/shows/fixer-upper/videos and others

![image](https://cloud.githubusercontent.com/assets/15856304/14953488/b19c4b9c-1072-11e6-9a88-8a204af9f1b7.png)

When you pause protection, it's showing ads:

![image](https://cloud.githubusercontent.com/assets/15856304/14953519/fa74e630-1072-11e6-950a-66561e945f2f.png)

**Comment by evgeniy-ADG** [comment]
После рекламы видео так и не воспроизводится, возможно, связано как-то с ограничениями самого сайта. С американским IP проверить не смогу пока.

**Comment by Alex-302** [comment]
У меня только рекламные ролики играют, если без Адгарда и с ВПН США

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Попроси юзера выключить все фильтры, кроме английского. Ну и вообще проверить связано ли с фильтрами. Может антитрекинг включен.

**Comment by evgeniy-ADG** [comment]
я там какую-то платную подписку видел, наверное, это связано с подпиской... напишу.
