### ISSUE TITLE
https://www.weargustin.com - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2083]
With HTTPS filtering on, it appears as though the images of products on https://www.weargustin.com/store/3367 are getting filtered out as ads, while without HTTPS filtering on they come through, as they should.

on 
![image](https://cloud.githubusercontent.com/assets/15856304/14955119/44f10e70-1080-11e6-9fb4-7a5df8d8a0b8.png)

of
![image](https://cloud.githubusercontent.com/assets/15856304/14955126/4bbacef8-1080-11e6-815d-6cd64bd4ca49.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
I can't reproduce. I need the filters list.
