### ISSUE TITLE
[Safari] [Extension] Video won't play on CNN

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2090]
http://edition.cnn.com/2016/05/03/football/leicester-city-champions-reasons-premier-league/index.html
I get errors like these:
![screen shot 2016-05-03 at 8 33 56 pm](https://cloud.githubusercontent.com/assets/14153331/14992519/04fac1a4-116f-11e6-8a70-6bbfc74256f8.png)

ZBE-726-46685

**Comment by evgeniy-ADG** [comment]
[iOS] I have noticed that there seems to be an issue that causes videos on cnn.com not to be able to play. I've noticed this on mobile and OS X chrome extension.

Example problem URL (click on main video):
http://www.cnn.com/videos/tech/2016/04/21/nasa-spots-massive-space-bubble-orig-vstan-dlewis.cnn?iid=ob_homepage_NewsAndBuzz_pool#

BGF-240-79253
