### ISSUE TITLE
Facebook messenger android app

### ISSUE THREAD

**Issue by bobsage123** [AdguardTeam/AdguardFilters#20919]
There is a giant ad in the facebook messenger android app. Tried submitting this online but got an error.

![screenshot_20180810-012236_chrome beta](https://user-images.githubusercontent.com/20603861/43940081-03debca8-9c3c-11e8-88f0-c3574bf35532.jpg)
![20180810_005653](https://user-images.githubusercontent.com/20603861/43940084-05488628-9c3c-11e8-9007-e53ceff6fd15.jpg)

**Comment by BlazDT** [comment]
Can't be fixed due to encryption.
