### ISSUE TITLE
Picabu app missed ads

### ISSUE THREAD

**Issue by spectrenik** [AdguardTeam/AdguardFilters#2093]
https://play.google.com/store/apps/details?id=ru.futurobot.pikabuclient
![screenshot_20160504-130817](https://cloud.githubusercontent.com/assets/19185046/15011852/c3fb0b62-11fc-11e6-85ec-18d972427a72.png)

**Comment by Alex-302** [comment]
Фильтрация приложений включена? Какие фильтры? Гугловая реклама 100% должна блокироваться. У меня только чёрный фон всплывает, но после включения фильтрации DNS всё чисто.

**Comment by spectrenik** [comment]
Фильтрация включена. Фильтры: английский, счетчиков аналитики, виджетов в соц.сетях, русский и фильтр мобильной рекламы.

**Comment by Alex-302** [comment]
р

**Comment by Alex-302** [comment]
А в брандмауэре не выключали фильтрацию приложения?

**Comment by spectrenik** [comment]
Не выключал. Потестировал немного, в режиме vpn реклама вроде не пролезает. А в http прокси постоянно лезет (подключение по Wi-Fi).

**Comment by Alex-302** [comment]
@spectrenik 
очень странно. А сайты в режиме HTTP прокси фильтруются?

**Comment by spectrenik** [comment]
Сайты фильтруются, с ними проблем не замечал.

**Comment by Alex-302** [comment]
А запишите HTTP лог с указанием времени запуска этого приложения. Уровень логгирования переключается в расширенных настройках.
Возможные пути к логам:
`
/storage/emulated/Android/data/com.adguard.android/cache/log
/sdcard/Android/com.adguard.android/cache/log или
/sdcard/data/Android/com.adguard.android/cache/log или
/sdcard/Android/data/com.adguard.android/
`

**Comment by spectrenik** [comment]
Очистил лог, переключил на http-лог, записал. С самого начала лога (12:24) приложение запущено и рекламный баннер появился практически сразу. Если нужно, запишу ещё.
[adguard.zip](https://github.com/AdguardTeam/ExperimentalFilter/files/279173/adguard.zip)

**Comment by spectrenik** [comment]
Вот ещё. С 15:06
[adguard-1.zip](https://github.com/AdguardTeam/AdguardFilters/files/279440/adguard-1.zip)
.

**Comment by Alex-302** [comment]
Не вижу ничего подозрительного.
Есть ещё один вариант:
1. в низкоуровневых настройках включить запись HAR файлов
2. Прибить пикабу и очистить кэш
3. Включить защиту
4. Запустить приложение, дождаться рекламы и сделать её скриншот
5. Выключить защиту и обязательно выключить запись HAR файлов
6. Рядом с каталогом log появится HAR. Мне нужно всё его содержимое.
HAR файлы включают в себя всё содержимое ответов и запросов, что упростит поиск рекламы.

**Comment by spectrenik** [comment]
Сделал всё по инструкции. Сразу же при открытии приложения реклама, долго ждать не пришлось. 
[har.zip](https://github.com/AdguardTeam/AdguardFilters/files/281491/har.zip)
![screenshot_20160525-125424](https://cloud.githubusercontent.com/assets/19185046/15536056/7ed1a58c-2278-11e6-82cc-e52a2450a46c.png)

**Comment by Alex-302** [comment]
Что-то отстал от графика. Сегодня гляну.
Ещё вопрос - режим прокси - ручной?

**Comment by Alex-302** [comment]
Запросов от приложения не видно, похоже режим прокси - ручной. Приложения чаще игнорируют  ручные настройки и ломятся напрямую. Выход - использовать VPN или автоматический(нужен рут)

**Comment by spectrenik** [comment]
Режим ручной. Спасибо за потраченное время, тикет наверное можно закрывать.

**Comment by Alex-302** [comment]
А с VPN или автоматическим прокси пробовали?

**Comment by spectrenik** [comment]
C VPN проблем нет, рекламу не встречал. Просто нервирует постоянно висящая и уведомлениях иконка.
Автоматический прокси не пробовал, рута нет.

**Comment by Alex-302** [comment]
Такова цена качественной фильтрации приложений:)
