### ISSUE TITLE
FoxNews.com - Blocked videos (AdGuard Spyware filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#20957]
### Affected site:
`http://www.foxnews.com/`

### Issue:
Videos are blocked.

### Example:
`http://insider.foxnews.com/2018/08/10/chicago-pastor-rips-emanuel-calls-trumps-help-gun-violence-send-guard-troops/`

### Screenshot:

![filterissue-foxnews2](https://user-images.githubusercontent.com/9382674/43985225-3fc7a270-9cf5-11e8-8402-9cf66421decc.jpg)

### Problem filter:
AdGuard Spyware filter

### Problem rules:
```
||demdex.net^$third-party
||metrics.foxnews.com^
```

### Possible fix:
```
@@||demdex.net^$third-party,domain=foxnews.com
@@||metrics.foxnews.com^$first-party
```

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.9.4 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.4 (XUL)

**Comment by THEtomaso** [comment]
You've added the exceptions to the wrong filter.
They should be in '**AdGuard Spyware filter**', not in '**AdGuard Base filter**'!

**Comment by BlazDT** [comment]
Thank you for the notice, moved the rule.
