### ISSUE TITLE
"Evidon" issues (IMPORTANT!)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#20950]
### Issue:
"Evidon" rules keeps creating problems.

### Example:
`https://www.techrepublic.com/`

### Problem filter:
AdGuard Annoyances filter

### Problem rule:
`###_evidon_banner`

### Description:
When the Evidon consent is blocked, this overlay still remains, covering the page:
`techrepublic.com##.tynt-interstitial-overlay`

If you simply block the overlay too, links to some articles will still remain unclickable.
For the page to function properly, the cookie consent needs to be accepted!

### Elaboration:

All of the "Evidon" rules should probably be removed all together at this point, since they seem to cause way too many problems!
In some cases, Evidon's GDPR warnings are highly location-dependent, which makes the issues extremely difficult for filter authors to reproduce.
One example is this script, which is used by `PopSugar.co.uk`:
`https://c.evidon.com/sitenotice/4134/popsugar/settings.js`
The numbers at the end of each line appears to be country codes, and depending on your location, users can be redirected to different scripts, which in turn serves completely different types of cookie warnings.
It doesn't only serve one type of warning for European countries, and one type for non-European countries, but it also differentiates between various European countries.
More info here:
https://github.com/ryanbr/fanboy-adblock/issues/512/ 
And here:
https://github.com/AdguardTeam/AdguardFilters/issues/20596/

### Notes:

A commit was pushed earlier today, which removes the last Evidon rule from **EasyPrivacy**: 
`https://github.com/easylist/easylist/commit/bf047abd7a5d4564fecb0963d64f2efee38c3a88/`

Also, I've received a mail from the author of '**I don't care about cookies**', saying that he'll be removing all Evidon related rules from his filter too, in the next update.

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.9.4 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.4 (XUL)

**Comment by Alex-302** [comment]
As I see, these rules are not removed from Fanboy's Annoyances

**Comment by THEtomaso** [comment]
> As I see, these rules are not removed from Fanboy's Annoyances

He's well informed of the problems.
Awaiting his resonse here:
https://github.com/ryanbr/fanboy-adblock/issues/522/

**Comment by THEtomaso** [comment]
> Also, I've received a mail from the author of 'I don't care about cookies', saying that he'll be removing all Evidon related rules from his filter too, in the next update.

They've all been removed now.

**Comment by Alex-302** [comment]
https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
they are still exist

**Comment by THEtomaso** [comment]
I was refering to '**I don't care about cookies**'.
All Evidon related rules has now been removed in the latest version (v2.8.9).

**Comment by THEtomaso** [comment]
You really should reconsider removing all these "Evidon" rules.
When surfing from my location, they create issues wherever I encounter them (which is almost on a daily basis).

Here's another random example:
`https://www.cosmopolitan.com/uk/entertainment/a23860225/`
The Instagram images can't be shown, because The Evidon consent is blocked by the following rule (found in **AdGuard Annoyances filter**):
`||c.evidon.com/sitenotice/evidon-barrier.js`

**Comment by TheHasagi** [comment]
Looks like it works fine now. Will be reopened if necessary.

**Comment by THEtomaso** [comment]
No, it doesn't work fine.
Like I've pointed out before; this depends on which country your connecting from!

But I don't care anymore.
I got tired of debating this crap!:
` https://github.com/DandelionSprout/adfilt/issues/7/#issuecomment-431578932`
