### ISSUE TITLE
oceansofgamess.com [Ad String]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#20962]
**Site**: http://oceansofgamess.com/f1-2017-free-download/

**Issue**: Please remove the Ad string on the page.
 
**Screenshot**: http://prntscr.com/khb2ln

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 68.0.3440.106 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
I see no real download button.

**Comment by Nzzyme** [comment]
Scroll down on the page and you should see the Download button
http://prntscr.com/kicbg3

The request is to remove the Advertisement ad text string and not fake download button. Thanks

**Comment by Alex-302** [comment]
it redirects to http://solvettube.com/file-will-start-automatically-on-this-page-after-few-seconds-installation-video-guide-is-in-progress/

**Comment by Nzzyme** [comment]
Yes, which is the server hosting the game files. The request is not for removing the fake download button but to remove the text "Advertisement" on the main page

http://prntscr.com/khb2ln

**Comment by Nzzyme** [comment]
@BlazDT : Can you do the needful please.
