### ISSUE TITLE
www.independent.co.uk - blank page

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2096]
the page starts to load and shows content on the screen, and towards the end of loading the whole browser window turns blank. an example of a page having problem is http://www.independent.co.uk/news/science/science-or-science-fiction-how-an-italian-doctor-hopes-to-perform-first-human-head-transplant-a7007676.html
![image](https://cloud.githubusercontent.com/assets/15856304/15019052/ff4a22c0-1224-11e6-8533-ff31e20fe7a6.png)

i am using default Chrome browser (v 50.0.3661.89), adquard v 2.5.196, android version 6.0

if i disable adquard the pages displays correctly. i never had such problems with previous version of adguard (v2.1.359).
![image](https://cloud.githubusercontent.com/assets/15856304/15019065/0b46e964-1225-11e6-98e5-5ea33ec27bce.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Can't reproduce. I need the filters list.
