### ISSUE TITLE
http://www.athensmagazine.gr/ - false blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2101]
50% of the time when you press an article they load to a black page. Whitelisting/disabling only for the site doesn't fix the problem.

Adg is off 
![image](https://cloud.githubusercontent.com/assets/15856304/15050262/48609760-12fb-11e6-8fe8-77a366e9686d.png)
Adg is on 
![image](https://cloud.githubusercontent.com/assets/15856304/15050269/519e624e-12fb-11e6-964e-149b4da7e283.png)

<details>
Application version: 1.0.5.38
Application lifetime: 2016-04-24 00:11:38 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.1
ID: 5C4B855F-122B-47BD-B0EA-F7B5AC576E84

Locale: el
Region: gr

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.83.33 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.5.55 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.62 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.89 Enabled=NO
ID=7 Name="Japanese filter" Version=1.0.92.93 Enabled=NO
ID=11 Name="Mobile ads filter" Version=1.0.3.40 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=101 Name="EasyList" Version=1.0.57.22 Enabled=NO
ID=121 Name="void.gr" Version=1.0.0.59 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.12 Enabled=YES

**Comment by Alex-302** [comment]
User can disable filters one-by-one and tell us about "bad" filter

**Comment by Alex-302** [comment]
@evgeniy-ADG 
возможно баг, у меня не повторяется. Передай юзеру про выключение фильтров.
Лучше в раздел iOS продублировать.
