### ISSUE TITLE
savethevideo.com [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#21043]
**Site**: https://www.savethevideo.com

**Issue**: Please remove the pop-up on the page.
 
**Screenshot**: N/A

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 68.0.3440.106 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
When do you see the popup exactly? On the main page? When downloading?

**Comment by Nzzyme** [comment]
Ok, so after pasting a Youtube link in the search field and pressing the Enter key takes you to a page. On that page, tapping an empty space shows pop-up. Thanks

**Comment by AdamWr** [comment]
Added:
`savethevideo.com#%#window.zfgloadedpopup = true;`
