### ISSUE TITLE
hclips.com [Ad String & Pop-up][NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#21079]
**Site**: https://www.hclips.com/videos/housewife-receives-an-anal-creampie-from-her-black-lover/?pqr=1:ca02e299655209f5097abfd1528e3e5b:0:723967:1

**Issue**: Please remove the pop-up & Ad text string from the page as seen in the screenshot.
 
**Screenshot**: http://prntscr.com/kifbct

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 68.0.3440.106 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Sadly not shown. Please check @AdamWr.

**Comment by AdamWr** [comment]
Fixed.
