### ISSUE TITLE
Custom rules

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2109]
1. Необходимо авторизироваться на сайте https://www.drive2.ru

логин: zeusez@yandex.ru
пароль: testtest

Убрать нужно для мобильной версии
http://prntscr.com/b0bih6
1. Аналогичный вопрос по сайту http://kino.local.pp.ru/

логин: ZeuseZ
пароль: testtest

Необходимо скрыть раздел Порно в левом меню:
http://prntscr.com/b0bk7v

**Comment by Alex-302** [comment]
```
drive2.ru##.promocars
kino.local.pp.ru##a[href^="index.php?module=Porn"]

```

**Comment by vgavrish** [comment]
На сайте https://www.drive2.ru с тем же логином и паролем

Необходимо скрыть для мобильной версии два блока:
Подраздел "Лучшие машины" 
Подраздел "Премиум-услуги"
![f688fc08f97740479ff169e9051397ed](https://cloud.githubusercontent.com/assets/18548949/15989911/33786a5c-308e-11e6-987b-c388613e2192.png)

**Comment by Alex-302** [comment]
drive2.ru##nav.c-nav-block:nth-child(4)
drive2.ru##nav.c-nav-block:nth-child(5)
код у блоков слева одинаковый, по-нормальному ныжные не спрятать, поэтому возможно сокрытие нужного блока в будущем

**Comment by vgavrish** [comment]
Необходимо правило для показа виджетов на pikabu.ru
http://pikabu.ru/story/zaklyuchennyiy_ustroil_pobeg_chtobyi_pomoch_tyuremshchiku_u_kotorogo_sluchilsya_serdechnyiy_pristup_4326338
Виджеты: http://prntscr.com/bqsizv

**Comment by Alex-302** [comment]
```
pikabu.ru#@#.b-social-button
pikabu.ru#@#.b-social
```

**Comment by vgavrish** [comment]
В приложении https://vk.com/vznakomstveapp
Нужно скрыть вот эту строку: http://prntscr.com/c8y8pu
http://prntscr.com/c8y9xk

Пользователь создал правило, но оно у него не сохраняется:
meet.wcase.net$$div[id="vk_ads_9984"][parent-elements="div"]

**Comment by Alex-302** [comment]
пусть попробует
```
meet.wcase.net##div[id^="vk_ads_"]
```

**Comment by Alex-302** [comment]
или 
```
meet.wcase.net##div[style^="height:134px;margin-bottom:15px;"]
meet.wcase.net##.topPanel
```

**Comment by vgavrish** [comment]
Необходимо на сайте Одноклассников убрать такие блоки:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19019407/d53c6dd0-888f-11e6-84cc-b9be62edb253.png)
![image](https://cloud.githubusercontent.com/assets/18548949/19019408/dc5259a4-888f-11e6-8a8a-17b1e8d13e49.png)
</details>
при самостоятельно блокировании потом возникают проблемы с рекламой и т.д.

**Comment by Alex-302** [comment]
Для групп:
```
ok.ru###hook_Block_RecommendedGroups
```
Первый блок у меня не отображается.

**Comment by shurmosha** [comment]
а мне-то что делать...я убираю их продуктом,но потом все это пробивается
![5](https://cloud.githubusercontent.com/assets/17802561/19023061/e2a5894e-88ed-11e6-866a-cd4b3121359c.PNG)

**Comment by Alex-302** [comment]
Нижний так и не пропал?

**Comment by shurmosha** [comment]
я перезагрузил браузер так и осталось...может удалить продуктом и подождать опять или комп перезагрузить...у меня два компа и они синхронизированы браузерно-там тоже самое

**Comment by shurmosha** [comment]
после перезагрузки не пропало...я удаляю сам???

**Comment by Alex-302** [comment]
да может код элемента другой
если что - могу в понедельник удалённо глянуть

**Comment by shurmosha** [comment]
хорошо..я удаляю и посмотрим...можно по тимке,то есть по тим вьюеру

**Comment by shurmosha** [comment]
со мной можно связаться и по скайпу   скажите куда ,и я сброшу логин

**Comment by Alex-302** [comment]
напомните завтра, сообщу куда

**Comment by shurmosha** [comment]
хорошо..во второй половине дня пойдет??

**Comment by shurmosha** [comment]
я удаляю пока

**Comment by Alex-302** [comment]
> хорошо..во второй половине дня пойдет??
> а пока я удаляю

пойдёт.
Можете удалить.

**Comment by shurmosha** [comment]
я приношу свои извинения...я смогу только сегодня вечером или завтра,но пока не пробивалась реклама

**Comment by shurmosha** [comment]
я не смог раньше но пока нет рекламы не пробилась..

**Comment by Alex-302** [comment]
Ок, давайте уже завтра тогда.

**Comment by shurmosha** [comment]
хорошо..я отпишусь тут

**Comment by shurmosha** [comment]
добрый день   есть у вас время посмотреть по удаленке ??

**Comment by Alex-302** [comment]
Да я в том же часовом поясе. Напишите, когда будете готовы, постараюсь быстро ответить.

**Comment by shurmosha** [comment]
я дома -готов

**Comment by Alex-302** [comment]
ок, напишите минут через 15 id и пароль, чтоб не светить

**Comment by shurmosha** [comment]
а куда писать-то  я не умею тут прятать

**Comment by Alex-302** [comment]
можете прямо сейчас писать.

**Comment by Alex-302** [comment]
Я сразу увижу и удалю.

**Comment by shurmosha** [comment]
432719173
5966

**Comment by Alex-302** [comment]
```
```

**Comment by shurmosha** [comment]
добрый день
было все хорошо,но сегодня на леди мэйл ру на форуме  пробилась реклама-убрал ,пока не появляется,а вот на фотостране,па
![1](https://cloud.githubusercontent.com/assets/17802561/19335234/764c8ae8-910a-11e6-8cac-6b0a8ce0b1ed.PNG)
дла лезет и не блокируется-раз пять удалял и перезагружал

**Comment by shurmosha** [comment]
и вот только что открыл фотострану-вообще слетели все пользовательские фильтры-как будто и не было продукта,а может и не только пользовательские
такое и бывает периодически-в чем дело не пойму..приходится или сбрасывать все фильтры или заново переустанавливать продукт,но ,потом опять такая же чехарда

**Comment by Alex-302** [comment]
Удалённо бы глянуть.

**Comment by shurmosha** [comment]
через десять минут скину тимку -можно?? на ноуте-пока всё ок

**Comment by Alex-302** [comment]
да, давайте

**Comment by shurmosha** [comment]
432719173
4051

**Comment by shurmosha** [comment]
у отключил или вы отключились ..удалять мне элементы??

**Comment by shurmosha** [comment]
в сайбере не удаляет  картинки и часть надписей

**Comment by Alex-302** [comment]
я отключился, отписывал в чате.
Странно. Позже ещё подключусь, пока работы много.

**Comment by shurmosha** [comment]
когда примерно ?  мне ,может нужно уйти-я же тоже ваша работа!!!

**Comment by Alex-302** [comment]
давайте вечером или завтра

**Comment by shurmosha** [comment]
вообщеи сертификата нет и русского нет

**Comment by shurmosha** [comment]
я в шесть вечера уйду и буду часам к восьми

**Comment by shurmosha** [comment]
сегодня я готов
 или завтра 
смотрите..сами

**Comment by shurmosha** [comment]
сегодня я готов
 или завтра 
смотрите..сами

**Comment by shurmosha** [comment]
добрый день  будем смотреть??

**Comment by Alex-302** [comment]
Да. Засылайте реквизиты в 14:00

**Comment by shurmosha** [comment]
хорошо

**Comment by shurmosha** [comment]
присылать??? можно?

**Comment by Alex-302** [comment]
да

**Comment by shurmosha** [comment]
432719173
8897

**Comment by shurmosha** [comment]
доброго вечера!!! появилась новая проблема на двух компах сразу-реклама в почте мэйла
![default](https://cloud.githubusercontent.com/assets/17802561/19397653/6246e492-9251-11e6-9fb6-6259481fac31.PNG)

**Comment by shurmosha** [comment]
удалил все пользовательские фильтры с мэйлом,а все равно не удаляется

**Comment by shurmosha** [comment]
сегодня нижний блок пропал,а вот под словом" корзина"-не могу удалить..

**Comment by shurmosha** [comment]
отбой тревоги-служба поддержки ответила  и получилось
нужно добавить правило  e.mail.ru##.b-nav__item_settings   
а перед этим удалить в пользовательском фильтре всё,что касательно этого "настройки почты"

**Comment by shurmosha** [comment]
добрый вечер..опять сбились все фильтры на фотостране..
удалил те,что вы говорили,но все не могу убрать-не срабатывает помощник

**Comment by Alex-302** [comment]
Эх, ну давайте вечером ещё гляну.

**Comment by shurmosha** [comment]
когда примерно ..ведь ужо вечер...я просто обновил восьмёру до десятки и пошла чехарда...
на леди мэйл выскочило чуток,но убралось -перезагружать не пробовал

**Comment by shurmosha** [comment]
у каждого своя работа..моя-целительская.ваша -такая

**Comment by Alex-302** [comment]
давайте в 21 по Москве

**Comment by shurmosha** [comment]
ок...я отпишусь тут ,а то вдруг изменится что

**Comment by shurmosha** [comment]
я готов....

**Comment by Alex-302** [comment]
Высылайте

**Comment by shurmosha** [comment]
432719173
5445

**Comment by shurmosha** [comment]
432719173
5445
