### ISSUE TITLE
[iOS] Google Shopping issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2112]
When I use the shopping category of web google, I get this error when I press the button to access the stores. however if I turn off the AdGuard works perfectly.

1. 
![image](https://cloud.githubusercontent.com/assets/15856304/15092349/bcb6b8c2-146f-11e6-8dfb-3ddfae38f95d.png)
2. 
![image](https://cloud.githubusercontent.com/assets/15856304/15092350/c2be9370-146f-11e6-9e80-124f98e46d24.png)
3. 
![image](https://cloud.githubusercontent.com/assets/15856304/15092351/c8b2d0b6-146f-11e6-8f4a-9f55a4648cee.png)

<details>
Application version: 1.0.5.38
Application lifetime: 2016-04-07 17:46:20 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.1
ID: 24E11B9C-FCF0-431C-93CC-78228FF05FF0

Locale: es
Region: es

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.83.48 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.59 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.64 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.19 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.41 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=101 Name="EasyList" Version=1.0.57.39 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.57.29 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.57.51 Enabled=YES
ID=202 Name="Filtros Nauscopicos" Version=1.0.0.5 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.57.31 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.61 Enabled=YES

**Comment by Alex-302** [comment]
.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
попроси проверить без этих фильтров:
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.19 Enabled=YES
ID=101 Name="EasyList" Version=1.0.57.39 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.57.29 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.57.51 Enabled=YES
ID=202 Name="Filtros Nauscopicos" Version=1.0.0.5 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.57.31 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.61 Enabled=YES

**Comment by Bohdan-SUP** [comment]
User 1276227 has same issue on Android.
Adguard 2.6.108, disabled everything except for English Filter, Spyware Filter, Social media filter, Experimental filter, Annoyances filter and Mobile ads.
Toggling "Show useful ads" doesn't make any difference.
Log - [debug (2).txt](https://github.com/AdguardTeam/AdguardFilters/files/326286/debug.2.txt)

More screenshots and details in ticket 1276227

**Comment by Alex-302** [comment]
@evgeniy-ADG @Bohdan-SUP 
это один и тот же юзер, и проблема та же самая?

**Comment by Alex-302** [comment]
В сафари с нашими фильтрами проблема не повторилась.

**Comment by Alex-302** [comment]
По дроиду - пусть попробует выключить фильтрацию DNS

**Comment by Alex-302** [comment]
@evgeniy-ADG @Bohdan-SUP

**Comment by shaurmanchic** [comment]
Пользователь сообщил, что отключение фильтрации DNS решило проблему.

**Comment by Alex-302** [comment]
Ок, закрываем.

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/17471332/13205c48-5d4c-11e6-9424-9c3a64ccc7c9.png)

<details>
Application version: 1.0.5.38
Application lifetime: 2016-04-22 21:54:23 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.1
ID: 1B734D5B-7C63-4F26-A95E-A4C267F62243

Locale: en
Region: us

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.82.43 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.49 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.52 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES

</details>

The [link](https://www.googleadservices.com/pagead/aclk?sa=L&ai=Ctrbd912iV9f1EoiHpAOdiKWQD-vOnp1F2sT5iewB9LXJkNYBCAkQASDLkOQeKAJgyda-i8Sk_A-gAeKX_vUDyAEHqgQoT9CUcsf1QFTMHDtWqEZLIyhnCRHqqkAWRNiwGZBM07uH0-91qHlzksAFBaAGJtgGBIAHhuiBCpAHA6gHpr4bqAe1wRvYBwHgEv-igcGSxbSZYw&ctype=5&ved=0ahUKEwj3pLqylKbOAhXr6IMKHRpLDEQQuS8IGg&val=GgjVLTww5dP-lyABKAAw8NKurPyXw_WQATj0sYa8BUDtqom9BQ&sig=AOD64_2kHkowObv3pctu6zHFS8rLNVB6lw&adurl=http://148.xg4ken.com/trk/v1%3Fprof%3D105%26camp%3D7126085%26affcode%3Dpg141383%26kct%3Dgoogle%26kchid%3D7731756125%26cid%3D63303983362%26networkType%3Dsearch%26kdv%3Dt%26kpid%3D854519STEAMS%26kmc%3D5355044%26criteriaid%3Dpla-57479944948%26adgroupid%3D19968249202%26campaignid%3D224574322%26locphy%3D9015245%26adpos%3D1o1%26url%3Dhttp://www.gandermountain.com/modperl/product/details.cgi%3Fpdesc%3DMountain-Hardwear-Mens-Wicked-Short-Sleeve-Tee%26i%3D854519%26r%3Dview%26cvsfa%3D2586%26cvsfe%3D2%26cvsfhu%3D383534353139535445414d53), copied from the address bar

**1246172**

**Comment by Alex-302** [comment]
@evgeniy-ADG 
откуда эта ссылка? Нужна страница с ней. Может это не заблокированный баннер.

**Comment by Alex-302** [comment]
Пока для пользовательского фильтра:
```
@@||googleadservices.com/pagead/aclk?*&adurl=
@@||xg4ken.com/trk/*&adgroupid=
```

**Comment by Alex-302** [comment]
Добавил в фильтр Сафари
```
@@||googleadservices.com/pagead/aclk?*&adurl=
@@||xg4ken.com/trk/*&adgroupid=
```

**Comment by krystian3w** [comment]
Could you please exclude these 10-year-old rules for/from uBlock Origin MV2? They are unlikely to be needed for Firefox and Chromium forks that support MV2, these links is not strict blocked from game rewards:

```adb
! 5-60 seconds advert "reward" that lets you regain 25 energy in "Merge Prison: Hidden Puzzle", or a free ‘puzzle’ item, or a bonus box.
https://www.googleadservices.com/pagead/aclk?fbs_aeid=2666698413083424768&sa=L&ai=CgD56jTFbas2KFf7f78EPoMi5wQGM0_ipiAHO7ZSs5RWwkB8QASCvlcd8YOmEgIDsGqABpOjw70HIAQGpAhzPrqDxsJE-qAMByAOKBJgECKoEqwJP0FZiBu-rrcN5-caf_Q6EzzdX8D0cZg_B0ZMcl_qnXF-RSf8FrmcfBJ22HvlpJpQ8ictzCerIiDq6EK0flg1RIC1UxDtCdn1lyxYD-p0L9STPBIiSpevE6qHsPaSrOzsOvorLmbjvMAcnDgBqYaZ5OBFXHk_W99htzY9gJrAHB8vSqoCZ8UV-hYWq9JHh-44wwqrevWXHIljVb-hg1EP5H9Un7vgjGuM_OABi9bv5DsSRDLs5YiDr0wMo--KWnLp8AedXuVxmc-onFCibkgtfwpgaEcu0WNFnVhHTP4v5ULtnSrxw6Py4NuQh2S2uGUkg-gbXnDdTemQn8o--Sc3XOqNqnrcpz1o5DbzJWXZXxEAAC9EpwntVSEyluufeylHcACpwKfDq9YznmcAE-N-inuQFiAX_xdS9V6AGLtgGAoAHpKDBzxyYBwGoB6fMsQKoB-LYsQKoB6a-G6gHzM6xAqgH89EbqAeW2BuoB6qbsQKoB47OG6gHk9gbqAfw4BuoB-6WsQKoB_6esQKoB6--sQKoB5_hsQKoB9XJG6gH2baxAqgHusOxAqgHmgaoB_-esQKoB9-fsQKoB_jCsQKoB_vCsQKoB8LIsQLYBwHyBwJAaaAI-qIBsAgC0gg1CJHhgFAQARhfMgiri4CAoICgCToQgIABgICAgICUruADqIOAEEi9_cE6WMe06obg25UDYAGxCS72zGV8ZUg7gAoUigrgAWh0dHBzOi8vcGwubGlsbHkuY29tL3pyb3p1bWllY290eWxvc2M_dXRtX3NvdXJjZT1nb29nbGUmdXRtX21lZGl1bT1kaXNwbGF5JnV0bV9jYW1wYWlnbj1RMU9iZWNpdHlfZGdlbiZ1dG1fY29udGVudD1vYmVzaXR5LWNhcmUtMDE2NV91bmRlcnN0YW5kb2Jlc2l0eV9NX2Rnbi10cmFmZmljLSZ1dG1fdGVybT1kZW1vYmVoYXYmZ2FkX3NvdXJjZT01JmdhZF9jYW1wYWlnbmlkPTIzNDgzMTk2MTU5mAsByAsB4AsBogwDkAEBqg0CUEzIDQHwDQOIDgS4E5on2BMQghQnGiVtb2JpbGVhcHA6OjItY29tLnN0YXJyaW5nLnByaXNvbmJyZWFr0BUBmBYByhYCCgD4FgGAFwGyFzcYASoKNzgyOTcxNTE3NTIlbW9iaWxlYXBwOjoyLWNvbS5zdGFycmluZy5wcmlzb25icmVha1AGuhcCOAGqGBcJAAAAIJOnYUESCjc4Mjk3MTUxNzUYBLIYCRIC604YLiIBANAYAcIZAggB&ae=2&gclid=EAIaIQobChMIjYXshuDblQMV_u87Ah0gZC4YEAEYASAAEgKODfD_BwE&num=1&sig=AOD64_3E7ho4Zw_TEpjNQI7cJ9fWCSPmkA&client=ca-app-pub-7697227519861194&rf=1&nb=8&nx=303&ny=771&mb=1&nb=8&uach=WyJBbmRyb2lkIiwiMTYuMC4wIiwiIiwiUk1YNTMwMyIsIjE1MS4wLjc5MjIuMjkiLG51bGwsMSxudWxsLCIiLFtbIk5vdD1BP0JyYW5kIiwiOTkuMC4wLjAiXSxbIkFuZHJvaWQgV2ViVmlldyIsIjE1MS4wLjc5MjIuMjkiXSxbIkNocm9taXVtIiwiMTUxLjAuNzkyMi4yOSJdXSwwXQ..&ms=CoIGmsA_ATEaOgFnFHUnTFbYMkiKozzXHGN9JLFp6Y1_he4ZKvG80EXXVXdBRKRJrwAPSHr_S4FUrY2qJi_xe1ucfjUSvgXo9HHphVQf-nlKqlI9W8F08l-TrDlw2QSRPzwJOhvLoENTb3nKKh9bt9cc1XmctBebi8RP77JZdY4EDhCpQz18B86zzGWITNFbHYNz8XYhwMpqW13VtekwWX2plLe19_VtBsqEeTYIegSK9JFEvkddiAXNtEY_50BKx7CVxYwc3hejGUBw3jLXO_To5bVGU_4qT5YqshLfFITA7YOmB-rbt9OZ1E28k9cfihXHrdGcYyyWiUi6g7CprnRgU5i6w07pu2-gFNdXgDhHz1RdQud65Iz-XO-7F10W5EDCj-sImvUx3UlU4n4upov9Dfbfjs1PmRTXt-GMniGQAJD8Elpb1tzK7Z_8WcclIcG3Ps5w3u51QRQ88meiHhtO8CksduVSjBkjEOg5oBbciwUHVRS-w7AvE5bAVoOc7COP4KlUQQGMjdaJ15Z-kuLTaP2tpihofI5yEKTG0I5czyTR7i4PH7HozXQtToijApllIPctneSt56LKynF4aP6ElyzG3pZ_HgmYWNRwTu3sVBdj6B6rY2kmFIb5Ka-mVKfECP45NcrdNgIwRhO8i5MIjB8cCv210W4HT5y5KEtjMGbwkl7uelZhZJKUYuz-qqFsdiFF5JU6VGyS_YPA8IiKvWl183tG8ONklOYkBBOjWdWSLfVaiabLbssPuUuTTWMPls4-TZbD-fiolIGFHAhsdrwvnoFFwvvOmlhBLUegfSFvCFlO2JbZgIzUOT5oW7xD2dKY6KS7X7xa3xIXzEUDdktTUgqHEza7mHvq2VbkQyUEEB5PLRjyOP8p9Wc3bDvzZ0jm9Dqein2f7T0KKJHCYVtBZPeV8N51o63vHEIfYjrKiw_DZQ3M7jmYyjhh2110N1PLkMfOgba25vQc3Id09XXjC2cnUuDK5md0GaoBSkYICwsQAkuc8bINtezRmZXlXLIgBA&dct=1&suid=80294594359&ri=1&adurl=https://www.lilly.com/pl/znajdz-opieke-zdrowotna%3Fgad_source%3D5%26gad_campaignid%3D23483196159
```

guilty:

> ```adb
> ! https://github.com/AdguardTeam/AdguardFilters/issues/2112
> ! Fixing Google Shopping
> @@||www.googleadservices.*/aclk?*&adurl=$~3p
> ```

https://regex101.com/r/skjtSj/1

**Comment by Alex-302** [comment]
@krystian3w Please describe the problem in details. I don't understand.

**Comment by krystian3w** [comment]
1. I open the above-mentioned game.
2. I'm running out of mana to combine objects in the game and I can buy new mana by watching 5-60 seconds one advertising.
3. This particular game sometimes doesn't start the countdown without detecting a click on it.
4. When I click on app Ad,  game opens almost immediately Firefox and the page loads normally due to the rule allowing for iOS Safari in the Filter "AdGuard Filter - mobile ads".
   - The game does not detect whether I have connected to the Google server or the target domain, hence the default warning screen that the domain is blocked by Peter Lowe filters and probably the Polish one from MajkiIT is better:

> https://github.com/gorhill/ublock/wiki/Strict-blocking

My workaround in uBo:

```adb
||googleadservices.com^$all,_,reason="Reklama",_,important
@@||www.googleadservices.*/aclk?*&adurl=$~3p,badfilter
||www.googleadservices.*/aclk?*&adurl=$~3p,all,urlskip=?adurl +blocked
```

Due to the strange implementation of reson by uBo, sometimes I don't see the "Reklama" message in uBo strict block interface.
