### ISSUE TITLE
com.media.miplayer ads

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2115]
https://play.google.com/store/apps/details?id=com.media.miplayer
To reproduce the situation, select a channel or select a favorite and play, the control chinbar moves to make room for adspace.When changing stations or changing between favorite saved stations a full page ad filler page pops up.  Screenshots of both instances displayed below.  These situations did not occur under 2.1
![capture _2016-05-03-15-18-25-2](https://cloud.githubusercontent.com/assets/14153331/15095054/75b2f080-14bf-11e6-8cde-57cec82769b5.png)
![capture _2016-05-03-15-17-12](https://cloud.githubusercontent.com/assets/14153331/15095060/a98b8ef8-14bf-11e6-989f-0756c8b4eb29.png)

Logs - MJH-389-73039

**Comment by Alex-302** [comment]
@Bohdan-SUP 
Does customer use manual proxy mode?
He can try VPN mode. Also he can install beta version.

**Comment by Bohdan-SUP** [comment]
It's already VPN. Asked to try with beta.
