### ISSUE TITLE
smplayer.info

### ISSUE THREAD

**Issue by anewuser** [AdguardTeam/AdguardFilters#21174]
After you finish installing a new version of [SMPlayer](https://www.smplayer.info/) , it launches your browser automatically with a URL like `http://www.smplayer.info/post-install.php?version=18.6.0`. The option to disable this behavior [has been removed on version 17.12](https://forum.smplayer.info/viewtopic.php?p=17024&f=2#p17024).

I suggest adding `||smplayer.info/post*$document` to **Adguard Spyware Filters**.

uBlock Origin 1.16.16
Firefox 61.0.2 (64-bit)

**Comment by Alex-302** [comment]
This is just installation counter. Browser extension can't prevent POST in this case at the moment.

**Comment by anewuser** [comment]
> Browser extension can't prevent POST in this case at the moment.

This has nothing to do with the post method of forms. It's just a URL pattern that has the string "post-install" (as in "after install"):

`http://www.smplayer.info/post-install.php?version=18.6.0`
`http://www.smplayer.info/post-install.php?version=18.7.0`
`http://www.smplayer.info/post-install.php?version=18.8.0`
`http://www.smplayer.info/post-install.php?version=18.9.0`

**Comment by Alex-302** [comment]
It redirects to https://www.smplayer.info/first-steps.php
Nothing dangerous.
