### ISSUE TITLE
https://www.mycinema.pro/menu.html

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#21185]
**Site Sample** | 
-----------------------------|
https://www.mycinema.pro/menu.html

This page is part of https://chrome.google.com/webstore/detail/magic-actions-for-youtube/abjcfabbhafbcdfjoecdgepllmpfceif extension for Chrome.

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1803 x64
Browser:                               | Chrome Stable x64
AdGuard version:                       | **6.3.1399.4073**
Stealth mode:					       | enabled

| Filters enabled |
|-----------------|
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| Coin Blocker List
| EasyList Polish 
| Fanboy's Annoyances
| Fanboy's Enhanced Tracking List
| Fanboy's Social Blocking List
| I don't care about cookies
| KAD - fraud/scam 
| Malware Domains List
| NoCoin Filter List 
| Peter Lowe's list 
| Polish Annoyances
| Polish Main
| Polish Social
| Spam404

### Issue:

Text are moved up against removed adbox

<details><summary><b>Screenshot:</b></summary>

![20180817065811-screenshot](https://user-images.githubusercontent.com/9846948/44248458-edde7b00-a1ea-11e8-9f07-f0ea5d3d4363.png)

WHEN ADG is DISABLED

![20180817065855-screenshot](https://user-images.githubusercontent.com/9846948/44248485-136b8480-a1eb-11e8-9801-e27e804b5afe.png)

</details><br/>

**Comment by AdamWr** [comment]
Fixed.
