### ISSUE TITLE
360 Security - Antivirus Boost - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2118]
реклама
https://play.google.com/store/apps/details?id=com.qihoo.security&hl=en
360 Security - Antivirus Boost
JTX-657-19079

<details>
{
  "advancedPreferences" : {
  },
  "androidVersion" : "5.1 (sdk=22)",
  "appLanguage" : "ru",
  "applicationId" : "88c397fdd68efe5d",
  "autoStartEnabled" : true,
  "browsingSecurityEnabled" : true,
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "Fly FS504",
  "deviceSpeedRank" : 165,
  "dnsFilteringEnabled" : false,
  "enabledFilterIds" : [ 2, 3, 4, 1, 11 ],
  "environment" : "prod",
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "firewallConfiguration" : {
    "defaultPermissions" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
    "filterAppsTraffic" : true,
    "firewallEnabled" : true,
    "notifyForegroundAppBlocked" : true,
    "permissionsMap" : {
      "mobi.mgeek.TunnyBrowser.Theme.EnNightModeV10" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.fevdev.nakedbrowserpro" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.browser.classic" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.fb" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.browserfaster" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "explore.web.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.id" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.browser.yandex" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.ilegendsoft.mercury" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.swe.atego.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "ru.yandex.shell" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "reddit.news" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.adblockplus.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "internetexplorer.browser.webexplorer" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.th" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.BookmarksWidget" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.UCMobile.intl.x86" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "jp.ddo.pigsty.Habit_Browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.android.elex" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "net.fast.web.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.sec.android.app.sbrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.TabHistory" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.brightness" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.vionika.firephoenix" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.tablet" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.easyweb.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.android.chrome" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.chrome.deviceextras.samsung" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.pm" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.mx.browser.tablet" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.appdream.cloud" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.chrome.dev" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.asus.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.TunnyBrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.tabswitcher" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.droid.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.baidu.browserhd.inter" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.eBaySearch" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.ksmobile.cb" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "ru.mail.amigo" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.UCMobile.intl" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.mozilla.firefox" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.baidu.browser.inter" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.cloudmosa.puffinFree" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.web.browser.android" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.twitter" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.DolphinTranslate" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.MorningCoffee" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "jp.co.fenrir.android.sleipnir" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.us" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.tabreload" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.mx.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.mypdf" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.UltimateFlag" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.nubelacorp.javelin" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.linkbubble.playstore" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatgo.license.key" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.addons.pocket" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "acr.browser.lightning" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.mini.android" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.en" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "acr.browser.barebones" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "me.android.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.browser.flashfox" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.iron.srware" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.DolphinReader" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.chromium.chrome" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mark.via" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.uc.browser.hd" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.textadjust" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "nu.tommie.inbrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.addons.skitch" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.chrome.beta" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.addons.evernotesshare" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.DolphinFM" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.cleanmaster.security" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "cn.mozilla.firefox" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.apusapps.browser.turbo" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.fevdev.nakedbrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.mozilla.firefox_beta" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.express.web" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.license.key" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.ScreenCut" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.rocket.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.yandex.browser.beta" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.apusapps.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.gcp" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.alexa" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.jiubang.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.battery.saver" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.zero" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.yandex.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.explore.web.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.mini.android.yandex" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.metalasfook.nochromo" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.tencent.ibibo.mtt" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.YoutubeSearch" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.theme.ocean" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.uc.browser.en" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.browser.beta" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.TabMixPlus" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.htc.sense.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.addons.box" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.addons.dropbox" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "jp.co.fenrir.android.sleipnir_black" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.ghostery.android.ghostery" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.tint" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.yandex.browser.alpha" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.showip" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.engine" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "jp.co.fenrir.android.sleipnir_test" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.jbak.superbrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.cloudmosa.puffin" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.mozilla.fennec" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.shinyshake" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.whois" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "jp.ddo.pigsty.HabitBrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.ip" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "nextapp.atlas" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.amazon.cloud9" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.rtsw.easydownloader" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.ninesky.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.android.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatgo.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.browser.flfoxpro" : [ "MOBILE", "WIFI", "AD_FILTERING" ]
    },
    "version" : 1
  },
  "iconType" : "DEFAULT",
  "installedPackages" : [ "com.android.fmradio;version=2.0;system=true", "com.google.android.youtube;version=10.18.55;system=true", "ru.yandex.afisha;version=2.10;system=false", "com.oasisfeng.greenify;version=2.8.1;system=false", "com.android.providers.telephony;version=5.1-1456461421;system=true", "com.google.android.googlequicksearchbox;version=5.12.34.21.arm;system=true", "com.android.providers.calendar;version=5.1-1456461421;system=true", "com.android.providers.media;version=5.1-1456461421;system=true", "com.google.android.onetimeinitializer;version=5.1-1743759;system=true", "com.mediatek.fwk.plugin;version=1.0;system=true", "ru.rian.reader;version=3.6.3;system=false", "com.android.wallpapercropper;version=5.1-1456461421;system=true", "com.mediatek.schpwronoff;version=5.1-1456461421;system=true", "com.flyhelp.repair;version=1.0;system=true", "com.viber.voip;version=6.0.1.13;system=false", "com.skype.raider.tracker;version=2.2.531.19794;system=true", "com.android.documentsui;version=5.1-1456461421;system=true", "com.android.galaxy4;version=1.0;system=true", "com.android.externalstorage;version=5.1-1456461421;system=true", "com.mediatek.ygps;version=1.1;system=true", "com.android.htmlviewer;version=5.1-1456461421;system=true", "com.android.mms.service;version=5.1-1456461421;system=true", "com.android.providers.downloads;version=5.1-1456461421;system=true", "com.android.salestracking;version=1.0;system=true", "com.hongjingtel.factorytest;version=5.1-1456461421;system=true", "com.mediatek.engineermode;version=1.0;system=true", "com.android.browser.provider;version=5.1-1743759;system=true", "com.mediatek.omacp;version=5.1-1456461421;system=true", "com.android.providers.applications;version=5.1-1456461421;system=true", "ru.intaxi;version=2.0.11;system=true", "com.android.soundrecorder;version=5.1-1456461421;system=true", "com.android.defcontainer;version=5.1-1456461421;system=true", "com.android.providers.downloads.ui;version=5.1-1456461421;system=true", "com.android.vending;version=6.4.12.C-all [0] 2744941;system=true", "com.android.pacprocessor;version=5.1-1456461421;system=true", "com.android.certinstaller;version=5.1-1456461421;system=true", "android;version=5.1-1456461421;system=true", "com.mediatek.connectivity;version=1.0;system=true", "com.android.contacts;version=5.1-1456461421;system=true", "com.mediatek.bluetooth;version=5.1-1456461421;system=true", "com.android.mms;version=5.1-1456461421;system=true", "com.android.stk;version=5.1-1456461421;system=true", "com.android.launcher3;version=5.1-1456461421;system=true", "com.android.backupconfirm;version=5.1-1456461421;system=true", "com.mediatek.voiceextension;version=1.0;system=true", "com.google.android.gm;version=5.2.93937770;system=true", "ru.yandex.news;version=2.10;system=false", "ru.yandex.rasp;version=2.31;system=false", "com.android.wallpaper.holospiral;version=5.1-1456461421;system=true", "com.android.phasebeam;version=1.0;system=true", "com.mediatek.providers.drm;version=5.1-1456461421;system=true", "com.opera.max.preinstall;version=1.0;system=true", "com.google.android.setupwizard;version=2.0;system=true", "com.android.providers.settings;version=5.1-1456461421;system=true", "com.mediatek.miravision.ui;version=5.1-1456461421;system=true", "com.android.sharedstoragebackup;version=5.1-1456461421;system=true", "com.mediatek.batterywarning;version=5.1-1456461421;system=true", "com.google.android.music;version=6.7.2713Z.2790541;system=true", "com.android.printspooler;version=1;system=true", "com.android.dreams.basic;version=5.1-1456461421;system=true", "com.hjt.writeimei;version=1.0;system=true", "com.android.inputdevices;version=5.1-1456461421;system=true", "com.mediatek;version=5.1-1456461421;system=true", "com.adguard.android;version=2.5.196;system=false", "com.example;version=1.0;system=true", "com.android.musicfx;version=1.4;system=true", "ru.yandex.yandexnavi;version=1.85;system=false", "com.google.android.apps.docs;version=2.2.183.17.34;system=true", "com.google.android.apps.maps;version=9.9.0;system=true", "com.ipspirates.ort;version=5.6;system=false", "com.vgtrk.russiatv;version=1.6.6;system=false", "com.google.android.webview;version=50.0.2661.86;system=true", "com.mediatek.nlpservice;version=1.0;system=true", "com.android.server.telecom;version=5.1-1456461421;system=true", "com.google.android.syncadapters.contacts;version=5.1-1743759;system=true", "com.android.keychain;version=5.1-1456461421;system=true", "com.android.chrome;version=43.0.2357.93;system=true", "com.android.dialer;version=5.1-1456461421;system=true", "com.android.gallery3d;version=1.1.40030;system=true", "com.google.android.gms;version=8.7.03 (2645110-236);system=true", "com.google.android.gsf;version=5.1-1743759;system=true", "com.google.android.tts;version=3.8.16;system=true", "com.google.android.partnersetup;version=5.1.1-1900399;system=true", "com.android.packageinstaller;version=5.1-1456461421;system=true", "com.google.android.videos;version=3.13.10;system=true", "ru.alfabank.mobile.android;version=7.1.3;system=false", "com.fly.promo;version=1.6;system=true", "com.android.proxyhandler;version=5.1-1456461421;system=true", "com.android.musicvis;version=5.1-1456461421;system=true", "com.google.android.apps.photos;version=1.19.0.120877342;system=true", "com.google.android.calendar;version=5.5-121019539-release;system=true", "com.android.managedprovisioning;version=5.1-1456461421;system=true", "com.mediatek.calendarimporter;version=1.0;system=true", "com.mediatek.atci.service;version=1.0;system=true", "com.ubanksu;version=2.0.317;system=true", "com.android.dreams.phototable;version=5.1-1456461421;system=true", "com.mediatek.thermalmanager;version=1.0;system=true", "com.android.noisefield;version=1.0;system=true", "com.qihoo.security;version=3.6.1;system=false", "com.android.providers.partnerbookmarks;version=5.1-1456461421;system=true", "com.google.android.gsf.login;version=5.1-1743759;system=true", "com.mtk.telephony;version=1.0;system=true", "com.mediatek.voicecommand;version=1.0;system=true", "ru.dublgis.vendortag.fly3;version=1.0;system=true", "com.android.wallpaper.livepicker;version=5.1-1456461421;system=true", "com.google.android.backuptransport;version=5.1-1743759;system=true", "com.android.settings;version=5.1-1456461421;system=true", "com.my.games.vendorapp;version=null;system=true", "com.avito.android;version=3.9;system=false", "com.android.calculator2;version=5.1-1456461421;system=true", "com.rhmsoft.fm.hd;version=3.5.0;system=false", "com.mediatek.lbs.em2.ui;version=1.0;system=true", "com.android.wallpaper;version=5.1-1456461421;system=true", "ru.mail.mailnews;version=3.0.2.10590;system=false", "com.android.vpndialogs;version=5.1-1456461421;system=true", "com.google.android.talk;version=3.3.94322993;system=true", "com.android.email;version=5.1-1456461421;system=true", "com.android.phone;version=5.1-1456461421;system=true", "com.android.shell;version=5.1-1456461421;system=true", "com.yandex.browser;version=16.2.1.7529;system=false", "com.android.providers.userdictionary;version=5.1-1456461421;system=true", "net.megogo.vendor;version=1.0.fly;system=true", "com.mediatek.voiceunlock;version=5.1-1456461421;system=true", "com.android.location.fused;version=5.1-1456461421;system=true", "com.opera.preinstall;version=1.0;system=true", "com.android.deskclock;version=3.0.3;system=true", "com.android.systemui;version=5.1-1456461421;system=true", "ru.mail.mailapp;version=4.5.0.16154;system=false", "com.android.exchange;version=5.1-1456461421;system=true", "ru.yandex.weatherplugin;version=4.2;system=false", "com.mediatek.mtklogger;version=4.0.0;system=true", "com.mediatek.apst.target;version=1.1;system=true", "com.meltingsource.DocsViewer;version=10.6;system=false", "com.android.bluetooth;version=5.1-1456461421;system=true", "com.google.android.androidforwork;version=5.1-1743759;system=true", "com.android.providers.contacts;version=5.1-1456461421;system=true", "com.android.captiveportallogin;version=5.1-1456461421;system=true", "com.digitala.vesti;version=4.00;system=false", "com.hjt.writesn;version=1.0;system=true", "com.mediatek.dataprotection;version=1.0;system=true", "com.google.android.inputmethod.latin;version=4.1.23163.2622203;system=true" ],
  "installerPackage" : null,
  "kernelVersion" : "3.10.72+",
  "premium" : true,
  "proxyMode" : false,
  "proxyPort" : 8080,
  "proxySetupManualMode" : false,
  "referrer" : null,
  "sendAnonymousStatistics" : false,
  "showUsefulAds" : false,
  "sourceApk" : "/data/app/com.adguard.android-1/base.apk",
  "sslMitmConfiguration" : "{\"appsExceptions\":\"47 apps\",\"mitmList\":\"167 domains\",\"mitmListMode\":\"WHITELIST\"}",
  "statisticsInfo" : "Blocked threats:0; Blocked banners:1424; Traffic saved:37642240;",
  "trial" : false,
  "updateChannel" : "RELEASE",
  "userfilter" : [ ],
  "versionName" : "2.5.196",
  "whitelist" : [ ]
}

**Comment by evgeniy-ADG** [comment]
Я удалил и адгуард, и 360 антивирус+очистка, почистил все с помощью программы cleaner master,и вновь установил адгуард с 360 антивирус+очистка. И больше никакой рекламы в 360.Может кому-то это поможет решить такую же проблему как у меня .

**Comment by Alex-302** [comment]
ну и отлично

**Comment by Bohdan-SUP** [comment]
com.qihoo.security

Screenshots:
http://www.fotolink.su/v.php?id=06bf84037fa6647bfdf103138929cb8c
http://www.fotolink.su/v.php?id=290fa80ee914d60216bb5a8ab316d9c1

**Comment by Alex-302** [comment]
При каких условиях эта рекламы появляется? Вообще не хочется этот хлам на рутованном устройстве запускать. В прошлый раз сброс телефону делал.

**Comment by Alex-302** [comment]
Пусть пошагово опишет.

**Comment by Bohdan-SUP** [comment]
Юзеру написал.

**Comment by evgeniy-ADG** [comment]
> Sure no problem if you lock an app via the app lock feature and then open
> the lock app it it's always an ad on the screen then after you run the scan
> about 50-50 sometimes it blocks the ads other times it doesn't and that
> goes for both of the scans

**Comment by Alex-302** [comment]
Похоже не всем показывает рекламу. Попроси записать HAR файл. Инструкция 
https://kb.adguard.com/index.php?/Russian/Knowledgebase/Article/View/65/0/how-to-get-har-http-archive-files-from-android-device
