### ISSUE TITLE
https://pass.rzd.ru/timetable/logon/ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2119]
При включенной фильтрации https в AdGuard производил оплату билетов РЖД на их оффсайте pass.rzd.ru 
В процессе оплаты билетов сервис традиционно перекидывает между разными банковскими/платёжными серверами, но когда деньги на карточке заблокированы и доходит до завершения оплаты, что-то идёт не так и перебрасывает на страницу логина на сайт РЖД. Как итог, подтверждения оплаты не происходит, заказ отменяется, деньги (к счастью) возвращаются на карту. С отключенной фильтрацией https всё происходит штатно, ошибки нет. 

Могу описать последовательность действий:
авторизуемся на https://pass.rzd.ru/timetable/logon/ru
выбираем маршрут и дату, "купить билет"
выбираем поезд
выбираем вагон
вводим данные пассажиров
подтверждаем оплату
нас перебрасывает на банковский сайт ввода инфо по карте https://paygate.transcredit.ru
вводим информацию о карте
перебрасывает на на сайт банка-эмитента для смс-подтверждения платежа
подтверждаем
возвращаемся на сайт РЖД
жмём "завершить оплату" и снова попадаем на страницу авторизации
в разделе "мои заказы" билетов нет.

**Comment by evgeniy-ADG** [comment]
Вика проверила, повторилось по указанным шагам

В конце после "Завершить оплату" перекидывает на страницу авторизации и в "Мои заказы" - пусто. После отключения опции "Блокировать куки", переходит на авторизированную страницу и в "Мои заказы" показывает, что есть неоплаченные билеты.

https://pass.rzd.ru/timetable/logon/ru
лог Djanim1
пас 19933991viko

**Comment by Alex-302** [comment]
Проверьте такое
@@||pass.rzd.ru^$stealth
Добавил. Если помогло - закрывай.

**Comment by Alex-302** [comment]
Проверьте такое
@@||rzd.ru^$stealth
Добавил. Если помогло - закрывай.

**Comment by Alex-302** [comment]
@evgeniy-ADG

**Comment by evgeniy-ADG** [comment]
передал

**Comment by Alex-302** [comment]
не ответил ещё?

**Comment by vgavrish** [comment]
не ответил

**Comment by Alex-302** [comment]
Оно на поддомены не распространяется. Удалил и заменил исключением для их собственных баннеров.

**Comment by Alex-302** [comment]
Пока закрываю.
