### ISSUE TITLE
yimago.net [Empty Ad banner]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#21208]
**Site**: http://www.yimago.net/radio4/

**Issue**: Please remove the empty ad placeholders at few places on the page (http://prntscr.com/kjqkug). Another page on the same domain where this is seen is: http://yimago.net/m/radio4/ (Screenshot: http://prntscr.com/kjqlhz)
 
**Screenshot**: See above

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 68.0.3440.106 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
No visitors.

https://www.alexa.com/siteinfo/yimago.net

**Comment by Nzzyme** [comment]
Oh that's sad :(

Can I add these user filter rules by context menu or will this break the site in the future if there are any changes?

yimago.net##table:nth-child(5) > tbody > tr:last-child > td > div
yimago.net##div.grid:nth-child(6) > div.leftcol:first-child > div:nth-child(4)
yimago.net##div.grid:nth-child(6) > div.leftcol:first-child > div:nth-child(6)
yimago.net##div.grid:nth-child(6) > div.maincol:nth-child(3) > div:nth-child(4)
yimago.net###ad

**Comment by BlazDT** [comment]
Here are a few safe rules:

```
yimago.net##table[style*="header"] tr > td[style*="#ffffff;border-right"][style*="text-align:center;border-bottom"]
yimago.net##.maincol > div[style^="text-align:center;margin:"][style*="width:300px;height:250px"]
yimago.net###udtCookiebox
yimago.net###udtCookiebox ~ div[id^="udt"][style*="width: 100%;"]
yimago.net##.leftcol > div[style*="background-color:rgba(255,255,255,0.7);opacity:0.8;overflow:hidden"]
yimago.net###ad
```

Sadly your selectors are not matching any element except the last one when I test.

**Comment by Nzzyme** [comment]
Do you see visitors now?

**Comment by BlazDT** [comment]
4,8k a month is not much:
https://a.pr-cy.ru/yimago.net/
