### ISSUE TITLE
http://ru.investing.com/ - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2121]
http://ru.investing.com/
http://prntscr.com/b1z447

**Comment by Alex-302** [comment]
added to English
investing.com###TopTextAd
investing.com###mainPopUpContainer

**Comment by vgavrish** [comment]
http://www.investing.com/commodities/brent-oil

При входе на сайт, спустя пару секунд появляется затемнение в виде рекламы, которая отсутствует:
![f6b69c0d97cb48a1b16caac8bce372b5](https://cloud.githubusercontent.com/assets/18548949/15798079/80c2df90-2a35-11e6-9012-48d5a1a8916d.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/18548949/15798080/80c304de-2a35-11e6-9037-539a8cfa7398.jpg)

**Comment by Alex-302** [comment]
investing.com##.generalOverlay
и в соц фильтр кнопки шаринга
investing.com##.newSocialButtons
