### ISSUE TITLE
Pandora radio ads

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2122]
com.pandora.android
![screenshot_20160506-021341](https://cloud.githubusercontent.com/assets/14153331/15113087/dc2b59ba-15fa-11e6-9e64-faa2ec760b6b.png)
Log - MPF-233-42075

**Comment by YavorAatanasov** [comment]
If you need more logs or any other info let me know guys. Thanks

**Comment by evgeniy-ADG** [comment]
@Alex-302 we have logs, please check here: 1459863

**Comment by Alex-302** [comment]
@evgeniy-ADG 
It is useless in this case. I need a HAR file with content. User should to stop that app in system settings, then start capturing. ***Do not*** stop it after loading banner.
***Important*** I need the screenshot of loaded banner.
After that user should to tap on the banner and stop capturing.
Understand?)
