### ISSUE TITLE
filmywap.onl [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#21243]
**Site**: https://filmywap.onl/movies/devdas-2002-full-movie-watch-online-free-download/

**Issue**: Please remove the pop-up after clicking on the play button on the video player.
 
**Screenshot**: N/A

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 68.0.3440.106 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Site is not fully loading, please try this rule:

`||rgvqcsxqge.com^`

**Comment by Nzzyme** [comment]
You are right. Site is infact down. Lets close this then. Thanks.
