### ISSUE TITLE
openloadmovies.to [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#21258]
**Site**: https://openloadmovies.to/divergent/

**Issue**: Please remove the pop-up & fake links from the page.
 
**Screenshot**: http://prntscr.com/kk4dzw

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 68.0.3440.106 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Not reproduced, please try this rule for the ad links:

`openloadmovies.to##a.btn-successful[target="_blank"]`

**Comment by Nzzyme** [comment]
Works fine with the rule. Thank you.
