### ISSUE TITLE
gomovies.li [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#21254]
**Site**: https://www1.gomovies.li/divergent/

**Issue**: Please remove the pop-up & fake links from the page.
 
**Screenshot**: http://prntscr.com/kk3tlw

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 68.0.3440.106 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Popunder still reproduced?

**Comment by Nzzyme** [comment]
No. Thanks
