### ISSUE TITLE
indishare.me [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#21251]
**Site**: http://www.indishare.me/f/oyez0n-ns3g6s57efbl6

**Issue**: Please remove the pop-up after clicking on the Download button.
 
**Screenshot**: http://prntscr.com/kk3pap

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 68.0.3440.106 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Please post a new link, it is expired.

**Comment by Nzzyme** [comment]
Please check on this one: http://www.indishare.me/neywvkz4b9y4

After the countdown reaches 0, click on the download link which will take you to another page. On this page, clicking on the Download button shows pop-up. Thanks

**Comment by BlazDT** [comment]
Not reproduced, no popup after 2nd download button which gets you the file.
Still reproduced?

**Comment by Nzzyme** [comment]
Yes, reproduced yet again even with a different configuration. Pop-up goes to the domain "1bcde.com"

**Configuration**:

Windows 10 (32 bit)

AG for Chrome extension

**Filters**:
English filter
Spyware filter
Social media filter
Annoyances filter
Mobile Ads filter
Malware Domains
Spam404

**Comment by BlazDT** [comment]
Blocked two adservers which contain popunder scripts. Please check after update in about 3 hours, thank you.
