### ISSUE TITLE
filikula.co [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#21268]
**Site**: http://filikula.co/divergent/

**Issue**: Please remove the pop-up & fake links on the page.
 
**Screenshot**: http://prntscr.com/kk4rks

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 68.0.3440.106 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by BlazDT** [comment]
Fixed ads - popup not reproduced.

Do you still experience the popup?
