### ISSUE TITLE
nzherald.co.nz [Ad Banners]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#21271]
**Site**: https://www.nzherald.co.nz/entertainment/news/article.cfm?c_id=1501119&objectid=11880569

**Issue**: Please remove the empty ad banners from various places on the page.
 
**Screenshot**: http://prntscr.com/kk51hy

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 68.0.3440.106 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.9.2 `

**Filters**:
> `English, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
Not sure. Removed.
