### ISSUE TITLE
quora.com

### ISSUE THREAD

**Issue by spittingmadtruth** [AdguardTeam/AdguardFilters#21297]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

## Incorrect Blocking

**Actual Behavior: Answers are getting blocked**:

![image](https://user-images.githubusercontent.com/40901446/44306789-a0791f80-a34a-11e8-9b38-119910598fcb.png)

**Expected Behavior: I should be able to see the answers on site**: 

![image](https://user-images.githubusercontent.com/40901446/44306786-8f301300-a34a-11e8-837e-71b5aa973683.png)

***Steps to reproduce the problem***:

Enable AdGuard

## System configuration

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Mac OS High Sierra
Operating system version (Android/iOS) | 10.13.6
Browser:                               | Chrome Version 68.0.3440.106 (Official Build) (64-bit)
AdGuard version:                       | 2.9.2
Filters enabled:                       | English Filter
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | N/A
Simplified filters (iOS only)          | N/A
AdGuard DNS:                           | N/A
Stealth mode options (Windows only)    | N/A
Helpdesk ID (if exists):               | N/A

**Comment by spittingmadtruth** [comment]
In addition, I noticed that this issue occurs only for logged in users. I can see that content if I am logged out.

**Comment by BlazDT** [comment]
Should be fixed now, update will be available in about 3 hours.
