### ISSUE TITLE
quora.com [Android] [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#21299]
**Site**: quora.com
**Issue**: Seeing ads on the main page after logging in.
**Screenshot**: https://ibb.co/jsBStK

**System**:
- Android version: 6.0.1 MMB29M
- MIUI version: MIUI Global 9.5 - Stable [ 9.5.6.0 (MHOMIFA) ]

**AdGuard Version**:
- AdGuard for Android 2.11.81

**Filters**:
English, Spyware, Social Media, Annoyances, Mobile Ads, Simplified domain names, EasyList China

**AdGuard Settings**:

- Phishing & Malware Protection: Enabled
- Block ads in all apps: Enabled
- Allow search ads & the self-promotion of sites: Disabled
- DNS Filtering: Disabled
- HTTPS Filtering: Enabled
- High quality filtering: Enabled
- Filtering mode is Local VPN

**Comment by BlazDT** [comment]
Please check after update in about 3 hours.

https://github.com/AdguardTeam/AdguardFilters/issues/21297
