### ISSUE TITLE
[nsfw] http://imgsmarts.info

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#21301]
**Site Sample** | 
-----------------------------|
http://imgsmarts.info/r188.html

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1803 x64
Browser:                               | Chrome Stable x64
AdGuard version:                       | **6.3.1399.4073**
Stealth mode:					       | enabled

| Filters enabled |
|-----------------|
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| Coin Blocker List
| EasyList Polish 
| Fanboy's Annoyances
| Fanboy's Enhanced Tracking List
| Fanboy's Social Blocking List
| I don't care about cookies
| KAD - fraud/scam 
| Malware Domains List
| NoCoin Filter List 
| Peter Lowe's list 
| Polish Annoyances
| Polish Main
| Polish Social
| Spam404

### Issue:

ads, popups. redirect on click

<details><summary><b>Screenshot:</b></summary>

![20180819121318-screenshot](https://user-images.githubusercontent.com/9846948/44307813-63904580-a3a9-11e8-88f1-0c140b17b7b1.png)
![20180819121342-screenshot](https://user-images.githubusercontent.com/9846948/44307814-63904580-a3a9-11e8-9844-1bbaf92c8292.png)
![20180819121402-screenshot](https://user-images.githubusercontent.com/9846948/44307815-63904580-a3a9-11e8-825c-b190d63643cb.png)

</details><br/>

**Comment by BlazDT** [comment]
Fixed ads, popunders not reproduced. Please check after update in about 3 hours.
