### ISSUE TITLE
drive.cox.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2132]
The current version (1108) of Adguard totally blocks uploads to https://drive.cox.com through IE11. The site is a cloud backup site for my cable provider, Cox Cable. When I exit Adguard, uploads are normal. If I disable Adguard, uploads continue to be blocked. Adding drive.cox.com to the https exclusion list works, if I exit Adguard, and restart it. Simply adding the site to the exclusion list does not immediately allow uploads to resume.

ZEE-410-40059

**Comment by Alex-302** [comment]
@evgeniy-ADG 
The wide exclusion is not a good idea. I can't make a partially exclusion without access to the site.
Does this site work after disabling of all filters?
