### ISSUE TITLE
no can see video sound in site https://www.kan.org.il/Podcast/item.aspx?pid=7175

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#21324]
HI
cant see  video sound in site: https://www.kan.org.il/Podcast/item.aspx?pid=7175
exmple to video sound: http://prntscr.com/kkkijo
can see video sounnd only with disble adblock

**Comment by BlazDT** [comment]
Please provide required information:

https://github.com/AdguardTeam/AdguardFilters/blob/master/issue_template.md
