### ISSUE TITLE
cant see video sound in site https://www.kan.org.il/Podcast/item.aspx?pid=717

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#21327]
Hi

**Description:**
no can see video sound in site https://www.kan.org.il/Podcast/item.aspx?pid=7175 #21324

**Current behaviour:**
https://image.prntscr.com/image/SICUVvKHRkGL678KGGMgIQ.png

**Expected behaviour:**
https://image.prntscr.com/image/6ZUP0-rvRWasqh30iXzV_g.png

**Steps to reproduce the problem:**
enter the site: https://www.kan.org.il/Podcast/item.aspx?pid=717

**Filters:**
EasyList Hebrew,English
--

Information | Value
-- | --
Operating system: | win 10
Browser: | Chorme
AdGuard version: | 6.3.1399.4073

--

Filters enabled: | EasyList Hebrew,English
AdGuard DNS: | None 
Stealth mode options | no

**Comment by BlazDT** [comment]
Fixed, update will be available in about 3 hours.
