### ISSUE TITLE
myzuka.fm

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2139]
https://myzuka.fm/Song/1104764/Citizen-Cope-Penitentiary
![1](https://cloud.githubusercontent.com/assets/14153331/15134349/e623cfe6-1673-11e6-97ea-bd250e77a21e.jpg)
SGS-483-25490

**Comment by Alex-302** [comment]
уже заблокирована

**Comment by vgavrish** [comment]
1444709
Андроид. myzuka.fm. реклама
лог 
[debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/580729/debug.txt)
enabledFilterIds" : [ 2, 3, 4, 5, 14, 10, 1, 11, 116, 211 ],
 "filteringQuality" : "FULL",
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20138911/e01f997e-a68b-11e6-8498-70b3f22e78c1.png)

**Comment by Alex-302** [comment]
Фильтрация HTTPS не включена.
Добавил в мобильный фильтр
```
||smilered.com^
||jfduv7.com^
||retarget.ssl-services.com^
```
Пусть отпишется.

**Comment by vgavrish** [comment]
написала
странно, в стейт у него 
sslMitmConfiguration" : "{\"mitmList\":\"980 domains\",\"mitmListMode\":\"WHITELIST\"}",

**Comment by vgavrish** [comment]
отписал, что все работает, баннеры не всплывают

**Comment by Alex-302** [comment]
Ну ок тогда, с выключенной фильтрацией HTTPS или как у него блокировка доменов работает.
