### ISSUE TITLE
xiaoma.net

### ISSUE THREAD

**Issue by MHzsz** [AdguardTeam/AdguardFilters#21423]
[[//]:](url) # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Issue URL***:http://www.xiaoma.net/cet/9406.html?1523603266
* **Current behaviour**: 
xiaoma.net首页可以正常拦截广告
子网页不能正常拦截
而且Adguard助手不能使用

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image]
![imgapp](https://user-images.githubusercontent.com/39558996/44570080-34b20f00-a7af-11e8-8750-e850dd4658c8.jpg)
![_314f5c01-25c1-4b9f-b263-82a280d2a2d5](https://user-images.githubusercontent.com/39558996/44570082-37146900-a7af-11e8-847f-07eb4ab81ee6.jpg)

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | win10
Browser:                               | Vivaldi 1.15.1147.36
AdGuard version:                       | 6.3.1399.4073
Filters enabled:                       | User Filter<br>Adguard Base filter<br>Adguard Annoyances filter<br>Adblock Warning Removal list<br>Filter unblocking search ads and self-promotion<br>Adguard Simplified domain names filter<br>Adguard Japanese filter
Stealth mode options (Windows only)    | On

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Hi
I don't understand the issue. Please select ads on screenshot.

**Comment by BlazDT** [comment]
Not seeing ads, left side is chat.

**Comment by MHzsz** [comment]
@BlazDT 
right side is chat, left side is an ad.“小马特惠，火热预约中”等内容是广告。
If you don't think those are ads, all right.
But Could you please tell me why I can't use adguard assistant, there should be a floating ball like the second photo. 
Thank you.

**Comment by MHzsz** [comment]
@Alex-302 
Thank you for replying.
The problem is that adguard can't work in this web.
http://www.xiaoma.net/cet/9406.html?1523603266
I circled several ads.
And I can't use adguard assistant, it doesn't appear.It should be in the lower left corner.
![imgapp](https://user-images.githubusercontent.com/39558996/44570028-f4eb2780-a7ae-11e8-8cfc-56e3860e6683.jpg)
![_314f5c01-25c1-4b9f-b263-82a280d2a2d5](https://user-images.githubusercontent.com/39558996/44570048-06ccca80-a7af-11e8-887b-d6c1a8b2029e.jpg)

**Comment by BlazDT** [comment]
Are you sure the left side is an ad? It's class name is "online-chat". When I click on it some kind of chat opens.

Added rules to fix top and side banner on the right.
