### ISSUE TITLE
org.stocktwits.android.activity connection errors

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2144]
https://play.google.com/store/apps/details?id=org.stocktwits.android.activity
Log - HQO-607-59047
![screenshot_20160506-104719](https://cloud.githubusercontent.com/assets/14153331/15173488/f9929b06-1764-11e6-8dff-6ec6ddefdfb9.png)
![screenshot_20160505-160545](https://cloud.githubusercontent.com/assets/14153331/15173491/fafe2f0a-1764-11e6-9ac4-70c81e3621eb.png)

**Comment by Alex-302** [comment]
.

**Comment by Alex-302** [comment]
Can't confirm. Please ask for checking without filters.
