### ISSUE TITLE
[iOS] diarioshow.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2145]
http://www.diarioshow.com/article/details/61470/un-fuego-cirio-calienta-instagram-con-fotos-hot
JNM-755-63839
![image](https://cloud.githubusercontent.com/assets/14153331/15174139/bfd6a9da-1768-11e6-8a9e-2084c1aee80a.jpg)

**Comment by Alex-302** [comment]
@Bohdan-SUP 
It doesn't work without Adguard on my mobile devices, only on desktop.
