### ISSUE TITLE
Firkloveren.no - Broken (AdGuard Annoyances filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#21471]
### Affected site:
`https://www.firkloveren.no/`

### Issue:
The page is prevented from loading properly.

### Problem filter:
AdGuard Annoyances filter

### Problem rule:
`/cookienotice.`

### Screenshot:
Not needed, as the problem is obvious.

### Possible fix:
`@@/cookienotice.$domain=firkloveren.no`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.0.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.4 (XUL)

**Comment by Alex-302** [comment]
Fixed.
