### ISSUE TITLE
https://vpn.ac - Adguard is blocking VPN

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2147]
https://vpn.ac
https://addons.mozilla.org/ru/firefox/addon/secureproxy/

Adguard is blocking my VPN. It is also not leting websites open: outlook.com and msn. I know this as when I exit adguard these problems go away.  I am using Secure Proxy provided by VPN.ac.

PLEASE NOTE:
The problem is with the secure proxy that I use as an extension in 
Firefox 64bit version 46.
The proxy does not connect to the overseas server, the IP address 
remains as my China service provider's .
When I exit Adguard I get a connection, the IP changes to the proxy IP 
location.

Sequence of events.
Adguard ON.
Secure proxy click "Connect" box.
"Connect" box changes to "Disconnect" however IP still same - China IP.
Adguard EXIT
Secure proxy click "Connect" box.
"Connect" box changes to "Disconnect", IP changes to proxy server.
Proxy is now connected.

CZM-403-71357

**Comment by Alex-302** [comment]
@evgeniy-ADG 
не знаю как проверить без аккаунта. Расширение в Фоксе без ввода данных пишет что подключено, при попытке открыть сайты спрашивает пароль. Наверное сам туннель создался.
Попроси юзера выключить все фильтры и проверить снова.
У него ж прога?

**Comment by evgeniy-ADG** [comment]
Да, у меня такая же проблема. Можем попробовать организовать с ним TV. Филтьтры - попросил.

**Comment by Alex-302** [comment]
Ага, жду ответа по фильтрам.

**Comment by evgeniy-ADG** [comment]
He offered no reply yet
