### ISSUE TITLE
redirects to am15.net

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2152]
Постоянно перебрасывает на сайт am15.net. При чем переброс осуществляется со всех сайтов с фильмами - linecinema.org, kino-dom.org, coldfilm.ru, а также с других подобных. пожалуйста, исправьте.

[Тикет](https://kb.adguard.com/staff/index.php?/Tickets/Ticket/View/285976)

**Comment by Alex-302** [comment]
Повторилось только на втором сайте. Добавил
||status.kino-dom.org^

**Comment by Fridrix** [comment]
Проблема возникла вновь. Идет редирект на сайт Алибаба

**Comment by Alex-302** [comment]
На каких сайтах? На тех, которые выше - не повторяется.

**Comment by Fridrix** [comment]
@Alex-302 
kino-dom.org с этотго сайта

**Comment by Alex-302** [comment]
У тебя повторяется? Какие фильтры включены?

**Comment by vgavrish** [comment]
Редирект на coldfilm.ru. При нажатии на фильмы, чтобы их посмотреть
Хром, Ф: 1,2,3,4,11
Андроид
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20028739/7b2123c2-a342-11e6-861a-e3eb4b4dca27.png)
