### ISSUE TITLE
https://www.yahoo.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2154]
https://www.yahoo.com/
![image](https://cloud.githubusercontent.com/assets/15856304/15217128/d21fe084-1862-11e6-8d68-21f6afb32c07.png)

Hulu ads still showing

<details>
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.83.95 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.66 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.72 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.25.16 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.89 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.48 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=101 Name="EasyList" Version=1.0.57.70 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.61 Enabled=YES

**Comment by Alex-302** [comment]
I can't reproduce. Where does user live?

**Comment by evgeniy-ADG** [comment]
Locale: en
Region: us

**Comment by Alex-302** [comment]
@evgeniy-ADG @Bohdan-SUP 
could you check it? I can't reproduce it with US VPN.

**Comment by Bohdan-SUP** [comment]
Can't reproduce even without Adguard.
