### ISSUE TITLE
Radio Station Playback

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#21567]
Hello guys,

Has something changed in the rules? All of a sudden, I am unable to stream any radio station from any Android app. I have ensured that all User Filters are disabled and when I pause protection, I am able to play them. Can you please check. I am using Adguard Version 2.12.187β.

**Comment by Nzzyme** [comment]
Sorry, I was travelling that time and was writing on Phone. 

Please check with either any of the apps:

https://play.google.com/store/apps/details?id=tunein.player
(Station: Lounge FM Acoustic, Buddha Beach, etc)

https://play.google.com/store/apps/details?id=fm.radio.sanity.radiofm
(Station: TranceBase.FM, Digital Impulse - Trance, etc)

Thank you!

**Comment by BlazDT** [comment]
Not reproduced (tried the first one). Try updating to 2.12.192. Is HTTPs filtering active? Blocked an ad server.

**Comment by BlazDT** [comment]
Please disable HTTPs filtering.

Only recent rule is that settings.crashlytics.com. You can exclude it temporarily:

@@||settings.crashlytics.com

**Comment by BlazDT** [comment]
Did you try the rule?

**Comment by Nzzyme** [comment]
Unfortunately, that rule did not work.

**Comment by BlazDT** [comment]
Is it working fine if you disable spyware filter?

**Comment by Nzzyme** [comment]
That too does not help. :(

**Comment by Nzzyme** [comment]
I just updated to the latest nightly and now the issue is resolved. I am able to play every station in every app. That was an issue with the beta. Thanks

**Comment by BlazDT** [comment]
Glad it works again. I was shocked one day after I added that crashlytics rule it would cause an issue.
