### ISSUE TITLE
nonmoves.date

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2157]
http://nonmoves.date/12052016spolic.php
https://www.dropbox.com/s/s6nj6my74cda571/Screenshot_2016-05-12-18-19-07.png?dl=0
XHA-859-27223

**Comment by Alex-302** [comment]
Нежен не этот сайт, а с которого произошёл переход.
Добавил на всякий случай в мобильный фильтр.
