### ISSUE TITLE
[iOS] videoplayer missed AD 

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2159]
Повторилось с баз.фильтрами. обновленными.

http://serialomaniya.tv/pobeg-2005?w_season=%2FcontainsSeason%2F1&w_video=%2FcontainsSeason%2F1%2FcontainsSeason%2F1%2FEpisode%2F17

![image1](https://cloud.githubusercontent.com/assets/16462533/15228854/e608e8e6-1896-11e6-88ad-f88f0981f25f.PNG)

**Comment by Alex-302** [comment]
@Serzh-SUP 
там реклама или только таймер? Если только таймер, то на iOS и расширением для Сафари его не убрать

**Comment by Serzh-SUP** [comment]
@Alex-302 только таймер.

**Comment by Alex-302** [comment]
На иОС его не убрать.
