### ISSUE TITLE
com.bestappsale - missed ad / placeholder

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2161]
The problem with the full screen ad window popping up occurs in the Android app 'best app sale'.

https://play.google.com/store/apps/details?id=com.bestappsale&hl=ru

![image](https://cloud.githubusercontent.com/assets/15856304/15244446/e4952452-1909-11e6-89ec-8ed9b8d9a274.png)

logs [here](https://kb.adguard.com/staff/index.php?/Tickets/Ticket/View/286514)

**Comment by evgeniy-ADG** [comment]
I can't see a pop-up but we have logs, hopefully they'll help somehow

**Comment by Alex-302** [comment]
No, they did not...

**Comment by evgeniy-ADG** [comment]
SLB-162-38628 вот снова лог попросили, посмотри, пожалуйста. у него проблема осталась.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
не выходит убрать, похоже он фиксированной высоты.
