### ISSUE TITLE
https://www.mako.co.il/mako-vod-keshet/polyshuk-s3 - can`t see episode 11 

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#21630]
Hi

**Description:**
can`t see episode 11 in link: https://www.mako.co.il/mako-vod-keshet/polyshuk-s3  
and in more series in mako tv cant see  episode 11 with adgurd

**Current behaviour:**
https://image.prntscr.com/image/4EDckpRjQ0KolJFgtMZ7gg.png

**Expected behaviour:**
https://image.prntscr.com/image/tRzxJ-LUTn_8cvyAG9r4pA.png

**Steps to reproduce the problem:**
click on link:
**Filters:**
EasyList Hebrew,English  https://www.mako.co.il/mako-vod-keshet/polyshuk-s3   and can no see episode 11
--

Information | Value
-- | --
Operating system: | win 10
Browser: | Chorme
AdGuard version: | 6.3.1399.4073

--

Filters enabled: | EasyList Hebrew,English

EasyList Hebrew,,Annoyances,English,Adblock Warning Removal List
--

AdGuard DNS: | None 
Stealth mode options | no

**Comment by BlazDT** [comment]
Not reproduced - episode 11 is in another position than in your screenshot (with AdGuard and without), fixed social button in episode overlay and cookie notice. Please check @AdamWr 

<img width="936" alt="mako" src="https://user-images.githubusercontent.com/34266271/44655203-97e0b300-a9f4-11e8-9349-d78016e0e969.png">

**Comment by AdamWr** [comment]
On my end it's caused by `EasyList Hebrew`, so please add this rule to user filter:
`mako.co.il#@#div[class*="teaserSmall"]:nth-child(3)`

**Comment by MrTal** [comment]
yes this because EasyList Hebrew
i report on this to easylist Hebrew
tank you

**Comment by Yaron10** [comment]
@AdamWr,

Could you please have a look at https://github.com/easylist/EasyListHebrew/issues/287#issuecomment-406433709?

I'm using Firefox 52 (I don't want to update for the time being) + uBlock Origin firefox-legacy-1.16.4.4.

Thank you..
