### ISSUE TITLE
TUT.BY Новости - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2163]
у меня не повторилось тоже

TUT.BY Новости
https://play.google.com/store/apps/details?id=by.tut.android&hl=ru

реклама:
http://prntscr.com/b3wv57

TICKET ID
LZQ-627-12136

**Comment by evgeniy-ADG** [comment]
У нас не повторяется, но есть HTTP лог.

**Comment by Alex-302** [comment]
Судя по логу должно быть чисто. Может кэш?

**Comment by evgeniy-ADG** [comment]
> Здравствуйте!
> 
> Перейдите, пожалуйста, в Настройки - Расширенные и измените алгоритм фильтрации на "Качественный": 
> http://prntscr.com/b31zg5 
> 
> Затем очистите, пожалуйста, кэш приложения "TUT.BY Новости" и воспроизведите проблему.
> 
> Спасибо! Сообщите нам о результатах!
> 
> С уважением, 

Мы просили чистить кеш. Я хз в чем дело, у нас не повторяется.

**Comment by Alex-302** [comment]
Возможно режим прокси - ручной. Приложения обычно его игнорируют. Пусть попробует VPN или автоматический прокси.
