### ISSUE TITLE
rdstation.com / rdstation.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#21660]
Brazilian tracking network.

Example: `https://www.gazetadopovo.com.br/` calls `https://pageview-notify.rdstation.com.br/send`

They own `rdstation.com` too, so it's a nice idea to block external calls to the both of them.

AdGuard English+Mobile+Spyware+RUS+spa,por
uBlock Origin

**Comment by Alex-302** [comment]
done
