### ISSUE TITLE
[iOS] http://m.panduoduo.net/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2169]
![image](https://cloud.githubusercontent.com/assets/15856304/15299192/fc1996fe-1bab-11e6-8a46-5b8af328c67c.png)
LYQ-270-38762
<details>
Application version: 1.0.5.38
Application lifetime: 2016-01-18 14:37:51 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.1
ID: 6A27DCD7-6D93-4015-A5BF-DE4FD7673282

Locale: en
Region: cn

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.84.8 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.70 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.75 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.25.21 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.89 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.48 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=101 Name="EasyList" Version=1.0.57.81 Enabled=YES
ID=102 Name="ABPindo" Version=1.0.0.67 Enabled=NO
ID=103 Name="Bulgarian list" Version=1.0.0.6 Enabled=NO
ID=104 Name="EasyList China" Version=1.0.58.3 Enabled=YES
ID=117 Name="Adblock Polska" Version=1.0.0.52 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.57.71 Enabled=YES
ID=120 Name="Norsk adblockliste" Version=1.0.0.1 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.57.93 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.57.81 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.1.64 Enabled=YES
ID=205 Name="Schacks Adblock Plus liste" Version=1.0.1.34 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.57.86 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.61 Enabled=YES
ID=216 Name="Adblock polskie reguły" Version=1.0.3.88 Enabled=YES
ID=217 Name="Adblock polskie reguły cookies" Version=1.0.1.7 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.0.70 Enabled=YES
ID=220 Name="CJXsAnnoyanceList" Version=1.0.0.36 Enabled=YES

**Comment by Alex-302** [comment]
@evgeniy-ADG 
user can check for filters update.

**Comment by Alex-302** [comment]
||panduoduo.net/wapl?i=$script
||s.95105012.com^$third-party
