### ISSUE TITLE
http://www.idownloadblog.com/ - blank page

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2171]
http://www.idownloadblog.com/2016/05/12/google-gboard/
![image](https://cloud.githubusercontent.com/assets/15856304/15302656/c3be1896-1bbc-11e6-8733-7c58701aff4d.png)
IUL-825-44880
<details>
Application version: 1.0.5.38
Application lifetime: 2016-03-02 12:28:57 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.1
ID: 762D5613-DEDF-4A2B-BF3A-DCFA17AA3245

Locale: en
Region: au

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.83.95 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.66 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.82 Enabled=NO
ID=5 Name="Experimental filter" Version=1.0.25.16 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.48 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=101 Name="EasyList" Version=1.0.57.71 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.57.93 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.57.61 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.53.84 Enabled=NO
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.1.64 Enabled=YES
ID=204 Name="Peter Lowe's list" Version=1.0.2.4 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.57.76 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.53.82 Enabled=NO
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.34 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.61 Enabled=YES
ID=220 Name="CJXsAnnoyanceList" Version=1.0.0.36 Enabled=YES

**Comment by evgeniy-ADG** [comment]
@Serzh-SUP could you please check if the issue occurs at your end?

**Comment by Alex-302** [comment]
@evgeniy-ADG 
I can't reproduce it. User should to disable filters one-by-one, and report to us about problem filter.

**Comment by Serzh-SUP** [comment]
@evgeniy-ADG 
Не возникло. У него фильтры старые. Если обновление не поможет, пусть откл. до базовых.
Мои фильтры:
"User filter"
"English filter"   -  Версия фильтра 1.085.2 
"Russian filter"
"Spyware filter" 
"Experimental filter"
"Safari Filter".

**Comment by evgeniy-ADG** [comment]
ok, напишу ему

**Comment by Alex-302** [comment]
молчит?

**Comment by worldsdream** [comment]
I always check idownloadblog.com, never had any issues. I tried it with all filters and there is nothing blocking it? Let him update all filters. Should be all good.

**Comment by Alex-302** [comment]
ok then, closed
