### ISSUE TITLE
http://www.zybang.com - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2173]
http://www.zybang.com/question/19f0c69d4fee23b86fb2a3052142dcf3.html
![image](https://cloud.githubusercontent.com/assets/15856304/15303437/7a618026-1bc0-11e6-8582-c1fddd35ed0d.png)

![image](https://cloud.githubusercontent.com/assets/15856304/15303451/8857d31a-1bc0-11e6-8cc5-e1f0412d481c.png)
as you can see. on the top of the photo and middle right have AD which called us to download the app.

<details>
Application version: 1.0.5.38
Application lifetime: 2016-03-21 16:16:27 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.1
ID: 140AC5E9-D972-41E7-BBC2-0113F26F9F95

Locale: zh
Region: cn

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.83.72 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.66 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.71 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.48 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=101 Name="EasyList" Version=1.0.57.52 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.57.74 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.0.67 Enabled=NO

**Comment by Alex-302** [comment]
@evgeniy-ADG 
можешь на скрине отметить что блокировать? Никак не пойму. То ли чувака в очках, то ли ещё что-то

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/15519773/b418f190-220b-11e6-9ec9-00e14f83a204.png)
я за вот эти два элемента :)

**Comment by Alex-302** [comment]
Добавил
zybang.com##.qb-wgt_float-banner
zybang.com##.cmn-zuoyebang-slogan

**Comment by dzamyshlyayeva** [comment]
the issue is back 

![image](https://cloud.githubusercontent.com/assets/23372054/24461600/48b3666e-14aa-11e7-88b4-42acb41003fd.png)

Ticket ID 1516669

**Comment by Alex-302** [comment]
Moved to mobile filter.
