### ISSUE TITLE
kuronekoyamato.co.jp

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2174]
http://search.kuronekoyamato.co.jp/google/tnekog?number00=1&number01=410707410713&key=f553c1d809d05cc04cab22357bfe3752
http://postimg.org/image/9rf0yxnwx/
http://postimg.org/image/ic8cq3y35/

**Comment by Alex-302** [comment]
@Bohdan-SUP 
давай хоть краткое описание. Задач много, а без описания больше времени уходит на поиски проблемы, чем её устранение.

Конкретно здесь - проблема в отображаемом коде? У меня не повторяется.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
Странное явление. А попроси его выключить все фильтры.Если без фильтров норм - то пусть включает по одному с проверкой. Иначе проблему не вычислить.

**Comment by Bohdan-SUP** [comment]
Юзеру отписал, у себя больше не повторяется.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
ну что, не отписался юзер?

**Comment by Bohdan-SUP** [comment]
Нет, я переоткрою, если будет нужно.
