### ISSUE TITLE
cutscenes.net

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardFilters#21752]
**Issue URL (Ads)**

When you open this link `https://www.cutscenes.net/videos/6720/anna-2009/` then you will see ads, i have marked the ads in the screenshot:

![cutscenes](https://user-images.githubusercontent.com/19775409/44859322-8536da00-ac91-11e8-9419-58012a3929cc.JPG)

Please check and block them

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows XP SP3
Platform:                                     | Ext
AdGuard version:                       | 2.10.8
Browser::                       | Firefox 52.9.0
Filters:                | Fanboy's Social Blocking List, Annoyances, English, Fanboy's Cookiemonster List

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Fixed by modifying previous exclusion rule to only one domain.
