### ISSUE TITLE
kocaelifikir.com

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#21754]
https://kocaelifikir.com

<details><summary>Screenshot:</summary>

![kocaelifikir com 3](https://user-images.githubusercontent.com/34379403/44885543-14f87a80-acca-11e8-9bfc-39f9cd77efd2.png)

</details>
<br />

<details><summary>Screenshot:</summary>

![kocaelifikir com 2](https://user-images.githubusercontent.com/34379403/44885569-32c5df80-acca-11e8-889e-ee9aaa6d6e5a.png)

</details>
<br />
<br />

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Chrome
AdGuard version:                       | 2.10.8 Extension
Filters enabled:                       | English - Social Media - Spyware - Turkish - Annoyances - NoCoin

**Comment by AdamWr** [comment]
Fixed, but I couldn't reproduce ads at the top from the first screenshot.
Please reopen if you will see these ads after update.
