### ISSUE TITLE
[Windows][AntiAdblockScript] www.golem.de

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#21753]
https://www.golem.de

![image](https://i.imgur.com/6Kh1fAZ.jpg)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 (Build 17134.228)
Browser:                               | Vivaldi 1.16.1279.3
AdGuard version:                       | 6.4.1543.4361
Filters enabled:                       | English, Spyware, Annoyances, Experimental, Russia, German
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | No

Workround: `golem.de#%#window.uabpdl = window.uabInject = window.uabpDetect = true;`

**Comment by BlazDT** [comment]
Thank you - added.
