### ISSUE TITLE
wallstreet-online.de - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#21757]
***Site***: https://www.wallstreet-online.de
***Description***: Ads

<details>
<summary>Screenshot</summary>

![screenshot 2018-08-31 at 08 26 12](https://user-images.githubusercontent.com/10995998/44896167-8995de00-acf7-11e8-96b7-a6446b4c8466.png)

</details>

***System configuration***

Information | value
--- | ---
Browser: | Chrome
AdGuard version: | 2.10.8

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
It looks like "AdDefend", but I can't reproduce it.
Added:
`wallstreet-online.de#%#window.uabpdl = window.uabInject = window.uabpDetect = true;`
Please reopen if it will not work.
