### ISSUE TITLE
m.ithome.com

### ISSUE THREAD

**Issue by WoadZS** [AdguardTeam/AdguardFilters#21761]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
**Issue URL (Ads)**
 https://m.ithome.com/html/380324.htm

***Description***: Web Ad

<details><summary>Screenshot:</summary>

![_20180831141904](https://user-images.githubusercontent.com/18167899/44897939-00e76400-ad30-11e8-9c83-5ae5f009d531.png)

![image](%screenshot_url%)
</details><br/>

**Way to Solve this:**
According to the log, the Web API link to receive AD is https://m.ithome.com/api/lapin/ourbuyget
Just simply block it will be good, the rules I created for myself is `||m.ithome.com/api/lapin^`
the rule `ithome.com##.lapin` should works as well, I just prefer blocking the api link to save the data.

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)
EasyList China, Mobile Ads, Annoyances, English, Anti-Adblock Killer

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android 8.0
Operating system version (Android/iOS) | Android
Browser:                               | Chrome
AdGuard version:                       | 2.11.81
Filters enabled:                       | EasyList China, Mobile Ads, Annoyances, English, Anti-Adblock Killer
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On 
AdGuard DNS:                           | On

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added URL rule.
