### ISSUE TITLE
https://www.yves-rocher.ua/ - false blocking

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#21762]
***Description***

AdGuard Default DNS is preventing users from adding goods to the cart

***STR***

1. Enable AdGuard Default DNS
2. Go to https://www.yves-rocher.ua/control/product/~product_id=16084
3. Click on the Додати до кошика

***Expected result***

The good is added 

***Actual result***

It stalls

***Screenshot***

![image](https://user-images.githubusercontent.com/15856304/44898659-41cb8280-ad08-11e8-9c2e-cc7b71136849.png)

**Comment by Alex-302** [comment]
Не починим. Нужно разблокировать гугловую аналитику.

**Comment by Alex-302** [comment]
Объясни юзеру, что у DNS есть недостатки.
