### ISSUE TITLE
www.dallasnews.com

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#21763]
### Issue URL (Incorrect Blocking)
https://www.dallasnews.com/news/politics/2018/08/29/cant-ignore-beto-gop-tweets-mug-shot-cruz-skips-senate-votes-after-railing-august-recess

### Comment
> 

### Screenshots
  

  ![Screenshot 2](https://uploads.adguard.com/Cant_ignore_Beto_GOP_tweets_mug_shot_and_Cruz_skips_Senate_votes_after_railing_about_August_recess__Politics__Dallas_News_08-31-11-14.png)

### System configuration

Information | value
--- | ---
Platform: | Mac
AdGuard version: | 1.5.8
Browser: | Chrome
Filters: | Russian,<br>English,<br>Spyware,<br>Social media,<br>Safari,<br>Annoyances

**Comment by BlazDT** [comment]
Site is blocking EU visitors.
