### ISSUE TITLE
Zyro.com (website creator) on www.hosting24.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2179]
Hello, After an error message problem: 503 Forbidden Access with my web host: Hosting24 & Zyro (website creator). Would it be possible to put all this on the white list (including my website - sbmarin.com -). It's Emsisoft who suggested I contact you because I do not know much about computers :) For now I have to disable AdGuard to access my site creator Zyro at Hosting 24 and I almost close my account with them believing that the problem was at home !!! Thank you note to Good Day Bériault Sylvain Montreal (Canada) sbmarin.com

UXO-240-47247

Well I added an exception to the entire Zyro log in process for the entire site and I can access my website.. So I guess I'll just leave it like this because I need to work on website very often and don't need the hassles. It seems there are several rules added:
- us.zyro.com$document
- 31.220.17.87$document
- 31.220.17.87/cpress4350918346/frontend/paper-_lantern/zyrositebuilder/index.live.php$document
- hosting24.com$document
- 31.220.17.87/ $document

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Сумбурно описано, не понятно куда заходить. Попроси, плиз, пошаговое описание как повторить.

**Comment by Bohdan-SUP** [comment]
Попросил.
