### ISSUE TITLE
openpli.org

### ISSUE THREAD

**Issue by hawkeye116477** [AdguardTeam/AdguardFilters#21819]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: 
* **Current behaviour**: Cookie message
* **Expected behaviour**:  No cookie message

[//]: # (Substitute this line with a description of the problem)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/19818572/44945127-a3f8b600-ade2-11e8-8f47-02fa43dc4de9.png)
</details><br/>

***Steps to reproduce the problem***: Just go to this page and you will see message :smile:. 

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Linux (Manjaro)
Browser:                               | Vivaldi
AdGuard version:                       | 2.10.8
Filters enabled:                       | English Filter, AdGuard's Annoyance Filter, Fanboy's Cookiemonster List, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Polish RODO-Cookies Filters
AdGuard DNS:                           | None 
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

Another another important thing is that they do redirect on `https://forums.openpli.org/` to `openpli.org` if you log in and didn't accept cookies. It's on inline script
```
if (! euReadCookie('gdpr-accepted') && euReadCookie('coppa')) {
	window.location.replace('https://openpli.org');
}
```
.

**Comment by BlazDT** [comment]
It is possible you have to add the #%# rule to your user filter as Vivaldi is based on Opera.

**Comment by hawkeye116477** [comment]
@BlazDT Vivaldi is based on Chromium, but thanks, works perfectly :smile:.

**Comment by Alex-302** [comment]
This file contains all JS rules
https://filters.adtidy.org/extension/firefox/local_script_rules.txt
