### ISSUE TITLE
YAHTZEE® With Buddies - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2182]
https://play.google.com/store/apps/details?id=com.withbuddies.yahtzee&hl=ru

TRD-103-30457 <-- pics and HTTP logs

**Comment by Alex-302** [comment]
I don't see HTTP requests in user's log.
Also I cant reproduce the ads. I need step-by-step description.

**Comment by evgeniy-ADG** [comment]
Asked again. Will keep posted here.

**Comment by Bohdan-SUP** [comment]
Here you go - SML-457-69455

**Comment by Alex-302** [comment]
@Bohdan-SUP 
Still can;t reproduce it.
Please check these rules:
```
||s3.amazonaws.com/promos.withbuddies.com/prod/ads/
||config.sdk.scopely.io/*/android/ads_config.json
```
They are in filter now, so you can just check for filters update.

**Comment by Bohdan-SUP** [comment]
Emailed user, will update here.

**Comment by evgeniy-ADG** [comment]
Still no replies, seems to be fixed.

**Comment by Alex-302** [comment]
ok
