### ISSUE TITLE
http://kinokrad.net - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2186]
> Не блокирует рекламу, ссылка на баннер http://goo.gl/C7Qb7f, страница http://kinokrad.net/283115-lyucifer-1-sezon-2015.html

У нас чуть другие баннеры, но реклама есть: ![image](https://cloud.githubusercontent.com/assets/15856304/15407356/0fde1e1c-1e13-11e6-8033-be1213455580.png)
Проверьте еще с ваших ip, пож-та.
MJX-537-14574

**Comment by Alex-302** [comment]
Поправил.

**Comment by evgeniy-ADG** [comment]
http://kinokrad.net/
![image](https://cloud.githubusercontent.com/assets/15856304/15708629/3f0102a0-2808-11e6-8a97-955bd4ef1f86.png)
