### ISSUE TITLE
HERE maps - can't access an account

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2187]
HERE maps
https://play.google.com/store/apps/details?id=com.here.app.maps&hl=en

Проблема со входом в акк приложения через фейсбук и зарегистрированный акк.
Выдает такое сообщение при входе:
http://prntscr.com/b3uszk

Логи тут: JSD-631-42398

**Comment by Alex-302** [comment]
I can't confirm this. Please check these rules
```
@@||tt.onthe.io/?k
@@||app.adjust.com/session
```

**Comment by evgeniy-ADG** [comment]
Just forwarded to the customer.

**Comment by evgeniy-ADG** [comment]
Я извиняюсь, но мне пришлось перепрошить телефон, сейчас у меня другая
прошивка, не рутованный телефон, и данная проблема на текущей версии не
воспроизводится.
