### ISSUE TITLE
com.nextradiotv.bfmbusiness - can't start with ad filtering

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2191]
Stucks on a start screen. Disabling HTTPs filtering doesn't help. you need to turn ad filtering off or add the app to the exclusions.
It shows an ad right on startup, maybe it causes such behavior:
![image](https://cloud.githubusercontent.com/assets/15856304/15433439/16e5abf0-1ebb-11e6-9e43-3198a24b5ade.png)

XCP-410-14952

**Comment by Alex-302** [comment]
Please check this rule after stopping this app
`@@||googleads.g.doubleclick.net/mads/gma?request_id=*&_package_name=com.nextradiotv.bfmbusiness`

**Comment by evgeniy-ADG** [comment]
Могу я просто обновить фильтр и проверить?

**Comment by Alex-302** [comment]
Да, можно проверять. Сейчас правила попадают в фильтр минут через 15-30 после добавления.
