### ISSUE TITLE
com.cleanmaster.security - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2192]
https://play.google.com/store/apps/details?id=com.cleanmaster.security&hl=ru

HTTPs filtering, HQ filtering method

![image](https://cloud.githubusercontent.com/assets/15856304/15434839/98188a66-1ec1-11e6-8a2c-378c60ed298b.png)

ETP-269-94630

**Comment by Alex-302** [comment]
I can't confirm this. Please check these rules
```
@@||tt.onthe.io/?k
@@||app.adjust.com/session
```

**Comment by Alex-302** [comment]
@evgeniy-ADG 
можешь посоветовать новую бету? Там в расширенных настройках можно включить запись HAR файлов, которые содержат запросы и ответы вместе с содержимым. Хранятся в каталоге рядом с Log.
Только после отправки файлов нужно вручную обязательно выключить эту функцию.
