### ISSUE TITLE
www.tagesanzeiger.ch missed ads

### ISSUE THREAD

**Issue by tiberian83** [AdguardTeam/AdguardFilters#2193]
There are several missed ads on www.tagesanzeiger.ch. They are all in slightly orange boxes (see the picture). The same kind of ads are also shown on www.tdg.ch

![img_9562](https://cloud.githubusercontent.com/assets/10312300/15435189/1c0530e2-1ebb-11e6-80ec-6c879131e012.JPG)

**Comment by Alex-302** [comment]
Hi
I need the filters list and full URL. Also I need a screenshot with scrollbar.

**Comment by tiberian83** [comment]
They are all over the page. On the main page I was able to block them with the following rules:

tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort.twoCol.regionBZ:nth-child(5) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child > DIV.publiBox:nth-child(2)
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort.twoCol.regionBZ:nth-child(5) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child > DIV.publiBox:nth-child(2)
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort.twoCol.regionBZ:nth-child(9) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort.twoCol.regionBZ:nth-child(9) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(16) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront > DIV.teaserEditorialContent.publireportage:first-child > DIV.publiBox:nth-child(2)
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(16) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront > DIV.teaserEditorialContent.publireportage:first-child > DIV.publiBox:nth-child(2)
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(19) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child > DIV.publiBox:nth-child(2)
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(19) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child > DIV.publiBox:nth-child(2)
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressortGroup.specialSection:nth-child(24)
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressortGroup.specialSection:nth-child(24)
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort.twoCol.regionBZ:nth-child(28) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child > DIV.publiBox:nth-child(2)
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort.twoCol.regionBZ:nth-child(28) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child > DIV.publiBox:nth-child(2)
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort.twoCol.regionBZ:nth-child(28) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child > P.publiTitle:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort.twoCol.regionBZ:nth-child(28) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child > P.publiTitle:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(34) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(34) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(37) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child > DIV.publiBox:nth-child(2)
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(37) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child > DIV.publiBox:nth-child(2)
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(37) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child > P.publiTitle:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(37) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child > P.publiTitle:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(40) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(40) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(44) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront > DIV.teaserEditorialContent.publireportage:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(44) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront > DIV.teaserEditorialContent.publireportage:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(16) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront > DIV.teaserEditorialContent.publireportage:first-child > P.publiTitle:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(16) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront > DIV.teaserEditorialContent.publireportage:first-child > P.publiTitle:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(49) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(49) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(52) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(52) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort.wide:last-child > DIV.ressortRight:nth-child(3) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort.wide:last-child > DIV.ressortRight:nth-child(3) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort.twoCol.regionBZ:nth-child(5) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child > P.publiTitle:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort.twoCol.regionBZ:nth-child(5) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child > P.publiTitle:first-child
tagesanzeiger.ch###zhTipp > DIV.ressortRight.entitled.dasMagazin:nth-child(4)
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(19) > DIV.ressortRight:nth-child(4) > DIV.publireportageFront:last-child > DIV.teaserEditorialContent.publireportage:first-child > P.publiTitle:first-child
tagesanzeiger.ch###mainContainer > DIV.afterPosterAd:last-child > DIV.ressorts:first-child > DIV.ressort:nth-child(19) > DIV.ressortRight:nth-chi

But as soon as I click on a link, there are the ads again. A general rules would be nice.

My filters are:

English
Spyware
Social Media
German
Handywerbung
Safari
EasyList
EasyList Germany
EasyPrivacy
Fanboy Annoyance
Fanboy Enhanced Tracking
Peter Lowe
Adblock Warning Removal
Prebrake
Spam404

**Comment by Alex-302** [comment]
Please check these rules
```
||tagesanzeiger.ch/teaser.php
||tagesanzeiger.ch/sl/teaser/cached/front/ads
tagesanzeiger.ch##.adsTitle
tagesanzeiger.ch##.boxExclusiv.ad
```
But we can't remove all ads by browser extension.
```
tagesanzeiger.ch$$div[class="teaserEditorialContent"][tag-content="Werbung"] 
tagesanzeiger.ch$$div[class="teaserEditorialContent"][tag-content="Sponsored Content"]
```

**Comment by tiberian83** [comment]
I just tried them out. Some ads seem to be gone, but not all.

**Comment by Alex-302** [comment]
Yes, their code is similar to useful elements. Removing of them can break similar blocks.
Added to German filter.
