### ISSUE TITLE
Useful pictures are blacked out on Safari new API

### ISSUE THREAD

**Issue by tiberian83** [AdguardTeam/AdguardFilters#2195]
On www.cinemablend.com there are some useful pictures which are blacked out on Safari new API. No problem on Chrome though.
![img_9567](https://cloud.githubusercontent.com/assets/10312300/15450388/72e20630-1f9a-11e6-88ea-187533d8642f.JPG)

**Comment by Alex-302** [comment]
Can't reproduce. I need the filters list.

**Comment by tiberian83** [comment]
My filters are:
- English
- Spyware
- Social Media
- German
- Handywerbung
- Safari
- EasyList
- EasyList Germany
- EasyPrivacy
- Fanboy Annoyance
- Fanboy Enhanced Tracking
- Peter Lowe
- Adblock Warning Removal
- Prebrake
- Spam404

It also happens to Safari on iOS.

**Comment by tiberian83** [comment]
![image](https://cloud.githubusercontent.com/assets/10312300/15496624/9872d2d2-2196-11e6-8eed-e569c4c0447e.png)

**Comment by Alex-302** [comment]
Still can't reproduce
Please try to disable 
```
EasyList
EasyList Germany
EasyPrivacy
Fanboy Annoyance
Fanboy Enhanced Tracking
Peter Lowe
Adblock Warning Removal
Prebrake
Spam404
```

**Comment by tiberian83** [comment]
Just tried it out in my iPhone. The issue seems to be within Fanboy Annoyance. As soon as I disable it everything looks fine.

**Comment by Alex-302** [comment]
please check this rule
`@@||cinemablend.com/timthumb.php*/images/facebook/`

**Comment by tiberian83** [comment]
I just tried it, it works fine on iOS. I will try it on OS X as soon as I get home.

Will this rule be added to your filters or do I have to add it always manually?

**Comment by Alex-302** [comment]
Could you remove my rule, and check Fanboy Annoyance rule?
`@@||cinemablend.com/timthumb.php?src=/images/facebook/`

**Comment by tiberian83** [comment]
I removed your rule and added the other one. It seems to work fine too.

**Comment by Alex-302** [comment]
ok. You are ising optimized rules, so some rules are absent in filter.
Added this rule to Safari filter.
Please check for updates after 10 minutes. You should to remove tha rule from user filter.

**Comment by tiberian83** [comment]
Perfect. Thank you.

**Comment by Alex-302** [comment]
Please, don't forget to reply after filters update.

**Comment by tiberian83** [comment]
It works fine on iOS now. I will try it on OS X later today and report back.

**Comment by Alex-302** [comment]
Ok, thanks

**Comment by tiberian83** [comment]
Looks fine on OS X too now. Again thank you.
