### ISSUE TITLE
В приложении не блокируется реклама

### ISSUE THREAD

**Issue by ziandzivan** [AdguardTeam/AdguardFilters#2196]
В приложении https://play.google.com/store/apps/details?id=com.msmobile.hb не блокируется всплывающая реклама внизу (facebook...)
![2016-05-21_23-15-43](https://cloud.githubusercontent.com/assets/19509470/15450745/3b5e71cc-1fad-11e6-99fa-30353e7c67c3.png)

![2016-05-21_23-42-21](https://cloud.githubusercontent.com/assets/19509470/15450766/de28b2dc-1fad-11e6-8b34-8f689d898c6f.png)
Проблема в том, что это на Андроид 4.0.3
Это же приложение на 5-м андроиде без этой рекламы
Оба аппарата с лицензией.

**Comment by Alex-302** [comment]
На 4.0.3 фильтрация HTTPS включается? Без неё никак. 
Если не нужен фуйсбук, то должно помочь
`||facebook.com^$empty`
