### ISSUE TITLE
gigabyte.com

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#21971]
[https://www.gigabyte.com/Motherboard/GA-6OMM7E-rev-20](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.gigabyte.com/Motherboard/GA-6OMM7E-rev-20)

 cookie: `gigabyte.com###policy-div`

<details><summary>Screenshot:</summary>

![2018 09 04-1](https://user-images.githubusercontent.com/17948007/45004086-05db3a80-aff2-11e8-9148-510879d0de95.png)
</details>

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v2.10.8
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by AdamWr** [comment]
Added, thank you.
