### ISSUE TITLE
soft98.ir

### ISSUE THREAD

**Issue by rayman3003** [AdguardTeam/AdguardFilters#21997]
soft98.ir detects adguard.

soft98.ir (a website for downloads), won't shows the links, But showing a message that I must disable adblocker (adguard) to revealing the links.

screenshot:
https://www.qpic.ws/images/adguard.jpg

So Many Filters Enabled
Operating system:                      Windows 10
Browser:                               Firefox
AdGuard version:                      6.3.1399.4073
Filters enabled:                       Yes
AdGuard DNS:                           Default
Stealth mode options (Windows only)    Off

**Comment by BlazDT** [comment]
Not reproduced, please try to disable third-party filters and only enable AdGuard filters.

**Comment by rayman3003** [comment]
soft98.ir is a website full of ADs. I used "Adguard Assistant" to block those ads & add them to "user filter".

When I enable "user filter", It shows the adblock detector warning, And when I disable "user filter", It won't shows but instead, shows those annoying warning.

Just try to add one of those ads on "soft98ir" to "user filter" by "Adguard Assistant" & u will see the adblock detector warning.

What should I do?!

**Comment by BlazDT** [comment]
Better to report the ads next time.

Try these rules:

```
soft98.ir#$#.adx1 { visibility:hidden!important; height:0px!important; }
soft98.ir##.adx-300-250
soft98.ir#$##sidebar > .card[-ext-has='img.adx-image'] { visibility:hidden!important; height:0px!important; }
soft98.ir#$##sidebar-sticky1 > .card[-ext-has='img.adx-image'] { visibility:hidden!important; height:0px!important; }
```

**Comment by rayman3003** [comment]
Thank u, It worked.

These r all the rules from soft98.ir that  were available in my "user filter". I removed all of them & replaced them with your 4 rules & It works.

https://0bin.net/paste/u2+du7sQvYFvLedt#csq8CRUgsM+bFWjY97AfEWepKGfbBsTgMqHgMxg3JgY

Thank u again. :)

**Comment by rayman3003** [comment]
OK, I must say that today the problem returned:

1- Those 4 rules by "BlazDT" not working anymore.
2- All ads of soft98.ir returned (even with those 4 rules enabled).
3- If I use Adguard Assistant to block any of the ads, It shows the "adblock detector warning" warning & I cant use any links in the page. (exactly as I told in the first post).

screenshot:
https://www.qpic.ws/images/adguard.jpg

**Comment by BlazDT** [comment]
Added rules, it seems soon we have to rely on javascript/replace.
