### ISSUE TITLE
old.sberbank-am.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2199]
Не отображатся график на странице в IE
http://www.old.sberbank-am.ru/rus/Individuals/Mutual_Funds/Consumer_Sector/index.wbp
http://prntscr.com/b6lqoa

Помогает отключение Английского фильтра

**Comment by Alex-302** [comment]
@Bohdan-SUP 
Здесь тоже всё нормально. Какие фильтры и браузер?

**Comment by Bohdan-SUP** [comment]
Фильтры стандартные.

Проблема только в IE/Edge:
![image](https://cloud.githubusercontent.com/assets/14153331/15507156/1491974a-21d3-11e6-85c8-2bd8180fe7e3.png)

Вот так в Хроме:
![image](https://cloud.githubusercontent.com/assets/14153331/15507175/29598796-21d3-11e6-81ad-f166e8398cb0.png)

**Comment by Alex-302** [comment]
Временное решение
`@@||old.sberbank-am.ru^$elemhide`

**Comment by Alex-302** [comment]
@ameshkov 
почему svg ломается сокрытием в этих браузерах?

**Comment by Alex-302** [comment]
not reproduced now
