### ISSUE TITLE
er.oblzdrav.vrn.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2200]
Не отображается полная инфо на сайте
http://er.oblzdrav.vrn.ru/e-reg2.nsf/getlpu.xsp?city=%D0%A0%D0%BE%D1%81%D1%81%D0%BE%D1%88%D1%8C

http://prntscr.com/b6mtp2
http://prntscr.com/b6mtqq

Помогает отключение Русского фильтра

**Comment by Alex-302** [comment]
Вроде всё нормально. У тебя повторилось?
http://imagizer.imageshack.com/img924/6108/ywMdd7.png

**Comment by Bohdan-SUP** [comment]
Блокируется полный список поликлиник.

Adguard выключен:
![image](https://cloud.githubusercontent.com/assets/14153331/15507283/af5d3220-21d3-11e6-8e8c-5d25b434107b.png)

Adguard включен:
![image](https://cloud.githubusercontent.com/assets/14153331/15507314/d04ecb92-21d3-11e6-85b4-24c0f625f8ec.png)

**Comment by Alex-302** [comment]
Затупил чо то.
Добавил:
`oblzdrav.vrn.ru#@#.affiliate`
