### ISSUE TITLE
AliExpress Shopping App

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2201]
https://play.google.com/store/apps/details?id=com.alibaba.aliexpresshd

Не отображается полностью описание по товару, у нас не повторилось.
http://prntscr.com/b6nu7z

TICKET ID
JHS-149-99309

**Comment by Alex-302** [comment]
Тоже не повторяется. Попроси без фильтров проверить. И по возможности вычислить потенциально проблемный фильтр.

**Comment by Bohdan-SUP** [comment]
Отписал.

**Comment by evgeniy-ADG** [comment]
Попросили. Вот видео: https://drive.google.com/file/d/0B8GmXLzD8C-AbDlQT0NFODQ2VkU/view?usp=drivesdk

По видео начиная с 1.18 все фильтры отключены

**Comment by Alex-302** [comment]
Проблема не с фильтрами. Почему-то из-за Адгарда задержки.
Запили плиз в AdguardForAndroid
