### ISSUE TITLE
elasticweb.org - broken interface

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2203]
http://elasticweb.org/ru
Отключение всех фильтров не помогает, сайт все равно нормально не работает (либо долго открывает сайт, но стили не подгружает, либо вообще сайт не загружается
ZTG-373-56243
![screen shot 2016-05-23 at 6 22 48 pm](https://cloud.githubusercontent.com/assets/14153331/15475568/6dc5c6a8-2113-11e6-9d92-105f785235eb.png)
![screen shot 2016-05-23 at 6 23 03 pm](https://cloud.githubusercontent.com/assets/14153331/15475569/6e77db54-2113-11e6-819c-6201d9ea5786.png)

**Comment by Alex-302** [comment]
@Bohdan-SUP 
Возможно проблема у сайта. У нас с Адгардом в Сафари работает нормально, а в Хроме - без адгарда сломан.
Проверьте ещё у себя, может и баг, но маловероятно.

**Comment by Nanografon** [comment]
Баг подтверждаю. При отключении всех фильтров все равно сайт не функцианирует, при его отключении все работает стабильно (тест на хроме, опера, мозила). Все версии продуктов последние.
