### ISSUE TITLE
ttps://mygadget.su

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2205]
DBF-528-79934

https://mygadget.su/2016/05/obzor-meizu-m3-note-2-16gb/

Блокируются рекомендуемые записи в постах
http://prntscr.com/b6zvaf

Помогает отключение фильтра счетчиков и системы аналитики

---

тут же, такая ситуация
https://mygadget.su/2016/05/obzor-meizu-m3-note-2-16gb/

При добавлении сайта в исключения, не дает залогинится в Disqus:
http://prntscr.com/b6zy1w

При фильтрации сайта - без проблем логинится

При отключении защиты АДГ также проблем нет.

Если что:
лог vidjanim@gmail.com
пас: 19933991viko

---

Выкидывает из авторизации в Google Chrome. Бывает по 2-3 при входе в акк через главную страницу браузера приходится вводить свои данные

**Comment by Alex-302** [comment]
1. >рекомендуемые записи в постах
Они формируются сторонними средствами аналитики(relap.io), поэтому заблокированы соответствующим фильтром.
2. Повторилось. Не понятно почему такое происходит.
