### ISSUE TITLE
Twitter app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2207]
http://prntscr.com/b7cnsh

TICKET ID
logs with HTTP requests recorded -> EWL-284-83214

**Comment by Alex-302** [comment]
@evgeniy-ADG 
твиторы, фейсбуки проверяют сертификат. Заблокировать можно только установив какой-то модуль для xposed, и соответственно потребуется рут.

**Comment by evgeniy-ADG** [comment]
ясно.
