### ISSUE TITLE
Combination of easy and english filters breaks http://cnet.com/ in Opera 54/55

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardFilters#22086]
Easy filter and English Filter breaks http://cnet.com/
* **Current behaviour**: 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/41899455/45162713-4d7ee380-b1f7-11e8-92db-cf8a82bfa245.png)

</details><br/>

***System configuration***
Opera 54/55
extension release 2.9.2 and last beta 2.10.8

**Comment by Alex-302** [comment]
For custom filter
`cnet.com#%#(function() { var consoleLog = window.console.log; console.log = function(arg) { if (arg) { arg.toString(); } consoleLog.apply(this, arguments); } })();`
