### ISSUE TITLE
[iOS] http://expert.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2208]
http://expert.ru/expert/2016/19/voennyie-igryi/
http://prntscr.com/b7cz2b

**Comment by Alex-302** [comment]
Не повторяется. Может много фильтров включено?

**Comment by evgeniy-ADG** [comment]
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.84.75 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.85 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.93 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.34.15 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.58 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.51 Enabled=YES

Вот такие... Добавьте в лог кол-во правил во всех включенных фильтрах, в самой прогармме показывает, насколько знаю.

**Comment by Alex-302** [comment]
Может включены оптимизированные фильтры? Пусть попробует включить полные.

По количеству в логе как-то предлагал, но как-то не восприняли. Запили запрос, может сделают.

**Comment by evgeniy-ADG** [comment]
Объясни, как это сделать, пожалуйста.

**Comment by Alex-302** [comment]
айпад сейчас негде взять. Где-то в настройках есть переключатель, точное расположение не помню...

**Comment by evgeniy-ADG** [comment]
Сайт чист и красив, все ок.
