### ISSUE TITLE
[iOS] http://video.nur.kz - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2209]
http://video.nur.kz/serial/1219-fizruk-(tnt)/sezon-3
http://prntscr.com/b7d5y9

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.79.47 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.7 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.97 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.31.95 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES

**Comment by Alex-302** [comment]
@evgeniy-ADG 
фильтр мобильной рекламы же выключен.
