### ISSUE TITLE
grupoemidia.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#22143]
The `grupoemidia.com.br` ad network is not blocked. 

Example page: `https://tribunademinas.com.br/noticias/politica/06-09-2018/fotografo-da-tribuna-e-agredido-no-atentado-a-bolsonaro.html` (this page also has a leftover block in the middle of the article: `.ad-single-container`).

AdGuard English+Mobile+Spyware+RUS+spa,por
uBlock Origin

**Comment by BlazDT** [comment]
Thank you - fixed in Spanish filter.
