### ISSUE TITLE
http://www.sports.ru

### ISSUE THREAD

**Issue by dtitbd** [AdguardTeam/AdguardFilters#2214]
Фоновая реклама. Разная.
![screenshot_2016-05-24-20-27-39](https://cloud.githubusercontent.com/assets/17032471/15509811/47915084-21ee-11e6-9f6d-964776598812.png)

**Comment by dtitbd** [comment]
Фоновая реклама вроде пропала, зато теперь антиадблок появился.
![screenshot_2016-05-28-00-26-10](https://cloud.githubusercontent.com/assets/17032471/15619082/4f1a380a-246b-11e6-8412-e17ff28ffc7b.png)

**Comment by a-ladanov** [comment]
Подтверждаю насчет антиадблока
![01](https://cloud.githubusercontent.com/assets/18179397/15628539/dca5c926-251c-11e6-9227-057c15a35b04.png)

**Comment by ameshkov** [comment]
Заблокировано в фильтре раздражителей.

Он появился в бета-версии приложения для Android и в бета-версиях расширений.

**Comment by a-ladanov** [comment]
Извините, не понял.
А что, такие сообщения против блокировщиков теперь в фильтре раздражителей?
Почему не в русском?
В русском фильтре уже было правило против блокировщика раньше, но оно уже не помогает.

**Comment by Alex-302** [comment]
Он появляется только при первом посещении. После обновления вкладки сайт будет отображаться как обычно. Если при обнаружении блокировщика сайтом пользоваться невозможно, то исправление добавляется в основной фильтр.
