### ISSUE TITLE
ua.insomnia.rsa.news - ads and popups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2216]
I have sent the logs via the app as requested. Here is the link for the briefly news app which has the same issue. Full screen ad window pops up.

https://play.google.com/store/apps/details?id=ua.insomnia.rsa.newsi&hl=en&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dbriefly+news+app&pcampaignid=APPU_1_tdVDV5P5C-bWgAapj76gAQ

Again, it's clean at our end. HTTP logs: SLB-162-38628

**Comment by evgeniy-ADG** [comment]
Waiting for screenshots

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/15580373/240ebc3a-2371-11e6-99de-f4241423df85.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
посоветуй проверить с режимом VPN, т.к. ручная настройка прокси не обязывает приложения ходить через него.
