### ISSUE TITLE
http://autodont.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2217]
http://autodont.ru/system-of-ignition/ne-poyavlyaetsya-iskra-v-sisteme-zazhiganiya
http://prntscr.com/b8588e

**Comment by Alex-302** [comment]
autodont.ru##div[id^="tgroup_"]
autodont.ru##a[href^="http://s.kma1.biz/"]
||teaser.strocher.ru^$third-party
