### ISSUE TITLE
m.bild.de

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2218]
http://m.bild.de/wa/ll/bild-de/unangemeldet-42925516.bildMobile.html
TDL-880-49171
![2016-05-25 09 55 27](https://cloud.githubusercontent.com/assets/14153331/15562196/daebcc3e-2305-11e6-86b4-f1f917057be5.png)

**Comment by ameshkov** [comment]
I am not sure if it is even possible to fix it on iOS:(

**Comment by Alex-302** [comment]
,

**Comment by TPS** [comment]
Does @reek have a solution, now that you all are including his work (partially)?

**Comment by Alex-302** [comment]
@TPS 
it works fine on my end. Which filters are you using?

**Comment by TPS** [comment]
I've precisely the same as the screenshot above, w/ all filterlists enabled, except "Useful ads" & "[ABP Japanese](https://github.com/AdguardTeam/AdguardFilters/issues/2224#issuecomment-223783370)" under latest (as of now 😉) Amazon Android ß.

**Comment by Alex-302** [comment]
I think too much filtering here, because many filters. Disable them one-by-one and tell me about problem filter.

**Comment by Bohdan-SUP** [comment]
Another user with such issue - 
<details>
Device: iPhone
Platform: iPhone OS
OS: 10.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.86.71 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.35 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.27 Enabled=YES
ID=6 Name="German filter" Version=1.0.25.82 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.63 Enabled=YES
<details/>

**Comment by Alex-302** [comment]
Temporary added to Safari filter:
```
@@||m.bild.de^$elemhide
@@||sascdn.com/diff/*/pages/bild.js
@@||smartadserver.com/diff/*/smartad.js
@@||smartadserver.com/diff/*/divscripte/$script
@@||smartadserver.com/diff/*/partners/$script
```
@Bohdan-SUP @TPS 
Please check it after filter update.

**Comment by TPS** [comment]
I've no Safari filter under [Android](#issuecomment-224646938), but, anyway, after full filter update, no change. 😞

**Comment by evgeniy-ADG** [comment]
it's back <details>![screen shot 2016-08-09 at 1 57 42 pm](https://cloud.githubusercontent.com/assets/15856304/17514089/6240e566-5e39-11e6-8a43-8c60b9164271.png)</details> Adguard for iOS, with the most recent filter, no third-party ones

**Comment by Alex-302** [comment]
@evgeniy-ADG 
please check after filters update.
