### ISSUE TITLE
HD Videobox v. 2.99 

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#22195]
> В приложении HD Videobox последних версий перед просмотром фильма появляется чёрный экран с надписью реклама в верхнем левом углу и через пару сек исчезает и начинается фильм. Возможно ли заблокировать окончательно рекламу перед видео?

![screenshot_20180909-015218](https://user-images.githubusercontent.com/15856304/45261091-d2d5e400-b401-11e8-837d-90e45fc1864a.png)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | 7.1.2
Browser:                               | n/a
AdGuard version:                       | 2.12.212
Filters enabled:                       | "AdGuard Base filter", "AdGuard Mobile Ads filter", "AdGuard Spyware filter", "AdGuard Social Media filter", "AdGuard Annoyances filter", "AdGuard Experimental filter", "AdGuard Russian filter"
AdGuard mode (Android only):           | VPN 
Filtering quality (Android only):      | High-quality 
HTTPS filtering (Android only):        | On (Default mode)
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 1067648 (w/ web-requests log)

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Это не убрать. Часть приложения.
