### ISSUE TITLE
org.vndnguyen.phoneinfo - missed ads in the bottom

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2220]
Source:
http://forum.xda-developers.com/showpost.php?p=67024682&postcount=1240

**Comment by Alex-302** [comment]
It is clean on my device and user say:
"Phone INFO (org.vndnguyen.phoneinfo) is no longer getting the ads along the bottom of the screen filtered. "
But ads leftover is looks like fixed.

**Comment by vgavrish** [comment]
Можно убрать нижний блок от рекламы?
![screenshot_56](https://cloud.githubusercontent.com/assets/18548949/17455147/b4ff1e1e-5bb7-11e6-8b9c-23616347126e.jpg)

**Comment by Alex-302** [comment]
Похоже, что нет.
