### ISSUE TITLE
youtube mobile app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2221]
youtube. в вначале видео показывает рекламу. установил https сертификат. версия 2.6.23
кеш удаляли
http://prntscr.com/b8jz5y
![image](https://cloud.githubusercontent.com/assets/15856304/15584659/416dc38a-2384-11e6-8f52-118b95725a1d.png)

Записывать все: XAV-475-98327, HAR ждем.

**Comment by Bohdan-SUP** [comment]
HAR here - GUY-910-87764

**Comment by Alex-302** [comment]
@evgeniy-ADG 
с рекламой в приложении youtube нужно обращаться в раздел Android. Она зашифрована, и я здесь не помогу.

**Comment by Bohdan-SUP** [comment]
Filed https://github.com/AdguardTeam/AdguardForAndroid/issues/621
