### ISSUE TITLE
Audio ad

### ISSUE THREAD

**Issue by crypto777** [AdguardTeam/AdguardFilters#22215]
http://www.filma24.io/lake-placid-legacy-2018/

Audio ad  starts after 5 second you reload the page
without playing any video

Information | value
-- | --
Platform: | Win
AdGuard version: | 6.3.1
Browser: | Chrome
AdGuard driver: | WFP
Filters: | Russian,English,Spyware,Social media,German,Japanese,Dutch,Spanish/Portuguese,Filter unblocking search ads and self-promotion,Turkish,Annoyances,French,EasyList,Adblock Polska,EasyPrivacy,Adblock Warning Removal List

![image](https://user-images.githubusercontent.com/39701044/45265490-e017c080-b44b-11e8-98e9-3e209b8fd7d8.png)

**Comment by AdamWr** [comment]
@BlazDT this rule - `||youtube.com/embed^$domain=filma24.io` - blocks a trailer (to reproduce it click on "TRAILERI" button), so I changed it.
