### ISSUE TITLE
gmail app - missed ad in 'promotion' section

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2222]
![image](https://cloud.githubusercontent.com/assets/15856304/15585109/74b157a0-2386-11e6-8714-7d6d222095ac.png)

HTTP requests log: JBQ-219-48982

**Comment by ameshkov** [comment]
Nothing we can do about it now. It is simply impossible, all gmail content including ads is encrypted.
