### ISSUE TITLE
False positive on MDN

### ISSUE THREAD

**Issue by ExE-Boss** [AdguardTeam/AdguardFilters#22225]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**:

`<iframe>`s with a width of 100% and height of 120 are always blocked.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/3889017/45267563-33e7d100-b46f-11e8-88b6-e22de30f8545.png)
</details>

* **Expected behaviour**: 

On MDN, `<iframes>` with the `src` of <code>https://mdn.mozillademos.org/</code> are used for live examples.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/3889017/45267580-609be880-b46f-11e8-977f-5fec92226277.png)

</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)
Go to https://developer.mozilla.org/en-US/docs/Web/CSS/-ms-filter#Gradient (specifically https://developer.mozilla.org/en-US/docs/Web/CSS/-ms-filter#Result)

***System configuration***

**Filters:**

Base filters, Mobile filters

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | Desktop
Browser:                               | Firefox
AdGuard version:                       | 2018-9-9 2:00
Filters enabled:                       | Base filters, Mobile filters
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | ?

**Comment by ExE-Boss** [comment]
https://github.com/AdguardTeam/AdguardFilters/blob/6a404458555c3817cf6cb6daa4b1b901a26aad44/EnglishFilter/sections/whitelist.txt#L42-L43 It’s not just `iframe[width="100%"][height="120"]` that is be affected by this.

The AdGuard filters have a lot of `iframe[width="…"][height="…"]` rules, all of which affect every website, including MDN: https://github.com/AdguardTeam/AdguardFilters/blob/a9dfd16f4f4dd37ff242efcdc6bf87e887bae05e/EnglishFilter/sections/banner_sizes.txt#L50-L65

**Comment by BlazDT** [comment]
Ads often have those sizes.
