### ISSUE TITLE
[iOS] www.expressen.se - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2223]
missed ad: http://www.expressen.se/Global/fusion/helsida/helsida-tablet-gt_1.html#referral%3Dhttp%253A%252F%252Fwww.expressen.se%252Fgt%252F%26channel%3Dtablet
![image](https://cloud.githubusercontent.com/assets/15856304/15588471/c06ea58e-2396-11e6-8624-a4bc79074ccb.png)

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.85.2 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.90 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.96 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.55 Enabled=YES

**Comment by Alex-302** [comment]
to English
||fusion.expressen.se/script.js
||adtomafusion.net^$third-party
