### ISSUE TITLE
DailyStar.co.uk - Blocked images (AdGuard Annoyances filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#22246]
### Affected site:
`https://www.dailystar.co.uk/`

### Issue:
Many images aren't shown.

### Screenshot:

![filterissue-dailystar](https://user-images.githubusercontent.com/9382674/45302983-06edf980-b515-11e8-8fa5-7b4add86e5bf.jpg)

### Problem filter:
AdGuard Annoyances filter

### Problem rule:
`||consent.cmp.oath.com^$third-party`

### Possible fix:
`@@||consent.cmp.oath.com^$third-party,domain=dailystar.co.uk`

But if these consents behaves anyting like the notorious "Evidon" ones, then the rule should probably be removed all together.

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.0.1 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.4 (XUL)

**Comment by BlazDT** [comment]
Thank you - fixed.
