### ISSUE TITLE
False Positive → Toyota Recall Site

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardFilters#2224]
Neither http://touch.Toyota.com/recall nor http://WWW.Toyota.com/recall function w/o whitelisting `touch.Toyota.com` & `Toyota.com`, respectively.  When doing so, no ads appear, anyway.

I'm using all filters except 'Useful Ads' under Android VPN 2.6 latest Amazon ß.  Maybe the CAPTCHA is fowling this?

**Comment by Alex-302** [comment]
Disable ABP Japanese filter and Fanboy Annoyances.

**Comment by TPS** [comment]
Actually, _was_ latest build @ time of post, so no Annoyances filter, but ABP Japanese filter gives many false positives on _US_ sites (so I've that list disabled on desktop), anyway.  However,  since Toyota _is_ Japanese, _these_ pages probably should have some sort of whitelisting in that filterlist, so I've filed https://github.com/k2jp/abp-japanese-filters/issues/19.

**Comment by Alex-302** [comment]
I'm not sure that he will fix any issues, reported by non japanese users)

**Comment by TPS** [comment]
This is true.… Maybe @AdguardTeam should deprecate use (in favor of their own Japanese filterlist) once all versions can handle arbitrary subscriptions.

**Comment by TPS** [comment]
Just got the update with the Annoyances filterlist & can confirm that hasn't a negative effect on these sites.
