### ISSUE TITLE
thewatchseries.to

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2225]
http://thewatchseries.to/episode/the_mindy_project_s4_e20.html
![screen shot 2016-05-24 at 7 31 07 pm](https://cloud.githubusercontent.com/assets/14153331/15611218/f7571f68-2431-11e6-9201-bdbc0e47f870.png)
CYY-191-34884

**Comment by Alex-302** [comment]
Please check this rule
```
||nativly.com/tds/widget?wid=$third-party
```
