### ISSUE TITLE
Google Plus issue

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2228]
Повторилось у Вики один раз при простое в приложении:
http://prntscr.com/b8jvds

Блокировкой доступа в интернет приложения Google+
https://play.google.com/store/apps/details?id=com.google.android.apps.plus&hl=en

Происходит при первом запуске приложения после какого-то времени не использования или после выгрузки программы любым ресурсоёмким приложением. Если отключить файервол, обновить ленту в Google+, а потом обратно включить, то далее будет работать без проблем. До очередной выгрузки из памяти.

TICKET ID RTJ-350-72073

**Comment by Alex-302** [comment]
Не повторяется. Возможно как-то связано с фильтрацией HTTPS. Проверьте с последней бетой.

**Comment by Bohdan-SUP** [comment]
У меня не повторяется, передал @vgavrish

**Comment by vgavrish** [comment]
У меня не повторяется больше. И тогда проблема один раз была.

**Comment by Alex-302** [comment]
Тогда юзера спросите)
Может у гугла что-то было.
