### ISSUE TITLE
[NSFW] imgclick.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2230]
http://imgclick.ru/695/365884/
http://prntscr.com/b9er0k
http://prntscr.com/b9eqyc

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/15706907/a74d5ee4-27fe-11e6-9182-327a1d9b1c6f.png)

**Comment by Alex-302** [comment]
||rekhatov.ru^$third-party

**Comment by vgavrish** [comment]
Расширение. Фильтры: 1,2,3,4,14
http://imgclick.ru/348/405738/
<details>
![screenshot_40](https://cloud.githubusercontent.com/assets/18548949/19416772/d7352830-93a1-11e6-924c-3d4c19de7557.jpg)

**Comment by Alex-302** [comment]
Убрал.
