### ISSUE TITLE
ixbt.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2232]
RU AdList и Easylist уже отключил
![image1-2](https://cloud.githubusercontent.com/assets/14153331/15631001/021a308c-255b-11e6-81f9-ffd7cbdb854a.png)

**Comment by Alex-302** [comment]
Пока для юзерфильтра
@@||rose.ixbt.com/banner/*/115-$domain=ixbt.com
@@||rose.ixbt.com/banner/*/115x$domain=ixbt.com

**Comment by evgeniy-ADG** [comment]
Не, не сработало, картинки не появились и квадраты не пропали. Я полностью скрыл эти три модуля вот так:
www.ixbt.com###flow > DIV.last:nth-child(6)
www.ixbt.com###flow > DIV.offer:nth-child(6)
www.ixbt.com###flow > DIV.last:nth-child(8)
www.ixbt.com###flow > DIV.offer:nth-child(8)
www.ixbt.com###flow > DIV.last:nth-child(10)
www.ixbt.com###flow > DIV.offer:nth-child(10)
www.ixbt.com###nl_header

Sincerely, M.E.S

от 12 июня в тикете 1255452

**Comment by Alex-302** [comment]
не помогло потому, что скорее всего правила вида #@# не добавились. 
Добавил правило для сокрытия остатков от картинки
ixbt.com##a[rel="nofollow"][href^="http://rose.ixbt.com/cgi-bin/click_i.cgi?"] > img
