### ISSUE TITLE
Яндекс.Погода

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2234]
Яндекс директ в Яндекс. Погоде
https://pogoda.yandex.ru/moscow/

http://prntscr.com/b9eliz

Фильтрация HTTPS включена.
Браузер Yandex (последнее обновление). В Internet Explorer 11 подобной ситуации нет.

TICKET ID NLN-920-67578
PTF-934-24626

**Comment by vgavrish** [comment]
Та же проблема в Chrome. https включен.
У меня не повторяется
![screenshot_3](https://cloud.githubusercontent.com/assets/18548949/15645998/097c9b62-2664-11e6-8989-73bd5968a225.jpg)

TICKET ID OPA-139-82441

**Comment by Hawkrus** [comment]
Проблема воспроизводится только, когда логинишься в свою учётку яндекс.

**Comment by Hawkrus** [comment]
После очистки файлов куки директ реклама исчезает на некоторое время. Но если обновить страницу спустя 10 минут - реклама появляется.

**Comment by Alex-302** [comment]
Повторилось. Через пол часа можно обновляться. Надеюсь у вас не расширение для Фокса или Оперы. Тогда временно придётся добавить
```
yandex.ru,yandex.com,yandex.ua,yandex.kz,yandex.by#%#AG_onLoad(function(){ window.AG_removeElementBySelector('div[class*="_pos_"][style*="display:block!important;visibility:visible!important;"]'); });
```

**Comment by vgavrish** [comment]
https://pogoda.yandex.ru/arhangelsk
Реклама в IE (у 2х пользователей). У меня не повторяется

В браузерах Opera и Microsoft Edge реклама пропала
![screenshot_15](https://cloud.githubusercontent.com/assets/18548949/15891166/0a7095d6-2d7c-11e6-8a95-18ff5ba4a37d.jpg)

**Comment by Hawkrus** [comment]
adguard для android не режет директ
![screenshot_2016-06-08-15-18-01](https://cloud.githubusercontent.com/assets/19652388/15894127/dcb73de6-2d8c-11e6-8ef2-144866dc1f3d.png)

**Comment by Alex-302** [comment]
@vgavrish у меня ни в одном браузере не повторяется. Пробовал и с российским прокси.
@Hawkrus для другого сайта нужно отдельную задачу создавать, чтоб не затерялось в переписке.

**Comment by Alex-302** [comment]
@Hawkrus 
фильтрация HTTPS включена? Что написано, когда на замок в адресной строке нажимаете?

**Comment by Hawkrus** [comment]
Фильтрация https, конечно, включена.
![screenshot_2016-06-09-11-13-39](https://cloud.githubusercontent.com/assets/19652388/15923009/6e95e220-2e33-11e6-8eb8-d921639c0c83.png)

![screenshot_2016-06-09-11-09-57](https://cloud.githubusercontent.com/assets/19652388/15922920/f308dbbc-2e32-11e6-89a8-1ef80878592e.png)

**Comment by Alex-302** [comment]
Нет, нужно нашать на замок в адресной строке, а не на ключ который над ним)

**Comment by Hawkrus** [comment]
![screenshot_2016-06-09-14-20-07](https://cloud.githubusercontent.com/assets/19652388/15928069/7faf7570-2e4d-11e6-89d6-2f9da8d1062c.png)

**Comment by Alex-302** [comment]
Подправил. Проверяйте обновления.

**Comment by Hawkrus** [comment]
Очистил куки, но не помогло:
![screenshot_2016-06-10-13-11-59](https://cloud.githubusercontent.com/assets/19652388/15961370/0f5c9ce2-2f0d-11e6-88a2-9f21e8de12f6.png)

**Comment by Alex-302** [comment]
Какой алгоритм фильтрации? В расширенных настройках.

**Comment by Hawkrus** [comment]
Разобрался, надо было фильтр вручную обновить. Теперь всё ок, спасибо.

**Comment by Alex-302** [comment]
Закрыл от комментов. В дальнейшем не мешайте в одну кучу разные проблемы разных пользователей.

**Comment by vgavrish** [comment]
Все также у пользователя в ИЕ 11 реклама появляется:
http://prntscr.com/bezvvq

**Comment by vozersky** [comment]
в IE11 опять вылезает директ, что-то с инжектом

**Comment by vozersky** [comment]
@Alex-302  вылез директ в погоде: https://pogoda.yandex.ru/moscow/

повторилось и на мак версии и на pc

**Comment by vozersky** [comment]
pogoda.yandex.ru##.content__top > div[class^="navigation-city "] > div:not([class="navigation-city__controls"])
pogoda.yandex.ru##.info__ratatue > div.info__more.info__map

**Comment by vgavrish** [comment]
Директ
https://yandex.ru/pogoda/ore
http://prntscr.com/des2sb
Ф: 1,2,3,4,6,10,14,14,15

**Comment by Usmanov-Alesher** [comment]
Такой вариант не очень ювелирный, ибо скрывает и карту яндекс из нижней левой части экрана, но всё же без этой контекстной рекламы

yandex.ru##div[class^="info__map "]
yandex.ru##div[class^="maps-widget "]
yandex.ru##div[class="info__more info__more_neighbor_abs"]

https://yandex.ru/pogoda/moscow

**Comment by Alex-302** [comment]
Карта же пропадает.
Удалённо бы глянул, у меня на другой домен перекидывает, без рекламы совсем.

**Comment by vgavrish** [comment]
а по ссылке? 
https://yandex.ru/pogoda/ore

**Comment by Usmanov-Alesher** [comment]
@vgavrish, нет такого города.
Правильная ссылка такая - https://yandex.ru/pogoda/orel
И, да, конечно же там есть яндекс.директ

**Comment by Usmanov-Alesher** [comment]
@Alex-302, ок. teamviewer. куда написать id и пароль?

**Comment by Usmanov-Alesher** [comment]
[Очередная реклама на яндексе. На этот раз в новостях.](https://i.imgur.com/sD3yeZL.png)

**Comment by Alex-302** [comment]
Так не пойдёт. Откройте новые задачи, иначе каша получается.

**Comment by Alex-302** [comment]
Комментирование гостями закрыл.

**Comment by Alex-302** [comment]
Для новых проблем - новые задачи.

**Comment by Alex-302** [comment]
@Usmanov-Alesher > ок. teamviewer. куда написать id и пароль?

можно в аську 335454355 или на форуме в личку.

По рекламе в новостях - создайте новую задачу.
