### ISSUE TITLE
crackberry.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2236]
http://m.crackberry.com/blackberry-offering-discounted-device-pricing-part-may-madness-promotion
NEY-910-24430
![image2](https://cloud.githubusercontent.com/assets/14153331/15646896/fc49f278-2668-11e6-9447-1106db250ba7.PNG)
![image1](https://cloud.githubusercontent.com/assets/14153331/15646897/fc4a28ce-2668-11e6-93f5-527d66d1f754.PNG)

**Comment by Alex-302** [comment]
,

**Comment by Alex-302** [comment]
@Bohdan-SUP 
у тебя повторяется? Мне не на чем проверить.

**Comment by Bohdan-SUP** [comment]
В Сафари с юзерагентом не повторяется.
@Serzh-SUP посмотри.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
может у юзера оптимизированные фильтры?
