### ISSUE TITLE
otodom.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#22384]
@AdamWr 

**Site Sample** | 
-----------------------------|
https://www.otodom.pl/oferta/ekskluzywny-dom-dla-wymagajacych-brzyczyna-ID3Kl8o.html

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1803 x64
Browser:                               | Chrome Stable x64
AdGuard version:                       | **6.4.1544.4363**
Stealth mode:					       | enabled

| Filters enabled |
|-----------------|
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| EasyList Polish 
| Fanboy's Annoyances
| Fanboy's Cookiemonster List
| Fanboy's Enhanced Tracking List 
| Fanboy's Social Blocking List 
| KAD - fraud/scam 
| NoCoin Filter List 
| Polish Annoyances
| Polish Main
| Polish Social
| Malware Domains 
| Spam404
| Peter Lowe's List

### Issue:

Map does not showing on overlay

<details><summary><b>Screenshot:</b></summary>

![20180913121415-screenshot](https://user-images.githubusercontent.com/9846948/45482636-e7daac00-b74e-11e8-8c07-afc86bd6ab74.png)

</details><br/>

**Comment by AdamWr** [comment]
Fixed in Polish filter.
