### ISSUE TITLE
nnmclub.to - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2238]
реклама в мобильной версии nnmclub.to
скрины: http://imgur.com/a/Uzdej

<details>
{
  "advancedPreferences" : {
  },
  "androidVersion" : "4.2.1 (sdk=17)",
  "appLanguage" : "ru",
  "applicationId" : "2756f2397179c137",
  "whitelist" : [ ],
  "versionName" : "2.5.196",
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "asus ASUS Transformer Pad TF300T",
  "userfilter" : [ ],
  "updateChannel" : "RELEASE",
  "enabledFilterIds" : [ 2, 3, 4, 1, 11 ],
  "environment" : "prod",
  "filteringQuality" : "FULL",
  "statisticsInfo" : "Blocked threats:0; Blocked banners:106; Traffic saved:2819072;",
  "firewallConfiguration" : {
    "defaultPermissions" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
    "permissionsMap" : {
      "com.dolphin.browser.express.web" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.yandex.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.asus.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.uc.browser.en" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "jp.ddo.pigsty.Habit_Browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatgo.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.appdream.cloud" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.baidu.browserhd.inter" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.mozilla.firefox" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "ru.yandex.shell" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.cloudmosa.puffinFree" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.jiubang.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.fevdev.nakedbrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "internetexplorer.browser.webexplorer" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.nubelacorp.javelin" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.id" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.android.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.metalasfook.nochromo" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.baidu.browser.inter" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.engine" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.web.browser.android" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.fevdev.nakedbrowserpro" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.UCMobile.intl" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "cn.mozilla.firefox" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.sec.android.app.sbrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.droid.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.license.key" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "me.android.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.browser.beta" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.swe.atego.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.rocket.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.uc.browser.hd" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.ninesky.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "jp.ddo.pigsty.HabitBrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "acr.browser.lightning" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.tencent.ibibo.mtt" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.browser.flfoxpro" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.mini.android.yandex" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.chrome.dev" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.zero" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.amazon.cloud9" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.browser.yandex" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.ghostery.android.ghostery" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "explore.web.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.ilegendsoft.mercury" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.cloudmosa.puffin" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.mozilla.firefox_beta" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.chrome.beta" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "ru.mail.amigo" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.tint" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.mini.android" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.explore.web.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "acr.browser.barebones" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.mx.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.browser.flashfox" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "nextapp.atlas" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.cleanmaster.security" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.tablet" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.TunnyBrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.UCMobile.intl.x86" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.opera.browser.classic" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.easyweb.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.mx.browser.tablet" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.jbak.superbrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.adblockplus.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.android.chrome" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "net.fast.web.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.htc.sense.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.android.elex" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "nu.tommie.inbrowser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.vionika.firephoenix" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.yandex.browser.beta" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.ksmobile.cb" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.en" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.fb" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.gcp" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.ip" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.pm" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.th" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.twitter" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatbrowser.free.addon.us" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.boatgo.license.key" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.chrome.deviceextras.samsung" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.addons.dropbox" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.addons.evernotesshare" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.addons.pocket" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.battery.saver" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.addons.box" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.browser.addons.skitch" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.dolphin.theme.ocean" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.linkbubble.playstore" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.rtsw.easydownloader" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.yandex.browser.alpha" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.BookmarksWidget" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.DolphinFM" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.DolphinReader" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.DolphinTranslate" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.MorningCoffee" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.ScreenCut" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.TabHistory" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.TabMixPlus" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.TunnyBrowser.Theme.EnNightModeV10" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.UltimateFlag" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.YoutubeSearch" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.alexa" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.brightness" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.browserfaster" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.eBaySearch" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.mypdf" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.shinyshake" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.showip" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.tabreload" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.tabswitcher" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.textadjust" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mobi.mgeek.whois" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.mozilla.fennec" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.ecareme.asuswebstorage" : [ "MOBILE", "WIFI" ],
      "com.apusapps.browser" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "com.apusapps.browser.turbo" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "jp.co.fenrir.android.sleipnir" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "jp.co.fenrir.android.sleipnir_black" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "jp.co.fenrir.android.sleipnir_test" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "mark.via" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.chromium.chrome" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "org.iron.srware" : [ "MOBILE", "WIFI", "AD_FILTERING" ],
      "reddit.news" : [ "MOBILE", "WIFI", "AD_FILTERING" ]
    },
    "firewallEnabled" : true,
    "notifyForegroundAppBlocked" : true,
    "filterAppsTraffic" : true,
    "version" : 1
  },
  "iconType" : "DEFAULT",
  "installedPackages" : [ "air.net.machinarium.Machinarium.GP;version=2.0.39;system=false", "android;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.adguard.android;version=2.5.196;system=false", "com.alibaba.aliexpresshd;version=4.9.0;system=false", "com.amazon.kindle;version=3.6.0.87;system=true", "com.android.backupconfirm;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.bluetooth;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.browser;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.calculator2;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.calendar;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.certinstaller;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.chrome;version=26.0.1410.58;system=true", "com.android.contacts;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.defcontainer;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.deskclock;version=2.0.3;system=true", "com.android.dreams.basic;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.dreams.phototable;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.email;version=4.1;system=true", "com.android.exchange;version=5.0;system=true", "com.android.facelock;version=4.2.2-612687;system=true", "com.android.galaxy4;version=1.0;system=true", "com.android.gallery3d;version=1.1.40001;system=true", "com.android.htmlviewer;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.keychain;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.launcher;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.location.fused;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.lockscreen;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.musicfx;version=1.4;system=true", "com.android.packageinstaller;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.phone;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.providers.applications;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.providers.calendar;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.providers.contacts;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.providers.downloads;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.providers.downloads.ui;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.providers.drm;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.providers.media;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.providers.partnerbookmarks;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.providers.settings;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.providers.telephony;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.providers.userdictionary;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.settings;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.sharedstoragebackup;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.soundrecorder;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.systemui;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.vending;version=6.5.08.D-all [0] 2792142;system=true", "com.android.videoeditor;version=1.1;system=true", "com.android.vpndialogs;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.wallpaper;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.wallpaper.holospiral;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.android.wallpaper.livepicker;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.asus.Battery;version=1.1.2;system=true", "com.asus.DLNA;version=10.8.20;system=true", "com.asus.UpdateLauncher;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.asus.backuprestore;version=2.4.0;system=true", "com.asus.cm;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.asus.dictionary;version=1.0;system=true", "com.asus.dm;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.asus.emailwidget;version=1.0.1;system=true", "com.asus.facebookposter;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.asus.filemanager;version=2.4.4;system=true", "com.asus.inputdevices;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.asus.keyboard;version=1.0;system=true", "com.asus.livewallpaper;version=1.5.4;system=true", "com.asus.livewallpaper.Iceberg;version=1.0.4;system=true", "com.asus.livewallpaper.myframe;version=0.9.12;system=true", "com.asus.livewallpaper.mytree;version=2.2.4;system=true", "com.asus.lock;version=2.5.1;system=true", "com.asus.mydictionary;version=1.0.7;system=true", "com.asus.mygazine;version=2.2.0;system=true", "com.asus.pcsynclauncher;version=1.4;system=true", "com.asus.pcsynctool;version=1;system=true", "com.asus.pl;version=1.0;system=true", "com.asus.quicksearch;version=1.0;system=true", "com.asus.reader;version=2.2.10;system=true", "com.asus.screensaver;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.asus.services;version=1.1.8;system=true", "com.asus.setupwizard;version=1.0.2;system=true", "com.asus.taskwidget;version=4.2.1-WW_epad-10.6.1.27.5-20130902;system=true", "com.asus.weather;version=1.0;system=true", "com.asus.webstorage.id;version=0.9.111.1485;system=true", "com.asus.wifidirect;version=1.2.10;system=true", "com.asus.youtubesearch;version=1.0;system=true", "com.avast.android.mobilesecurity;version=5.2.0;system=false", "com.avito.android;version=4.0;system=false", "com.cn.asus.vibe;version=3.2.1.2245;system=true", "com.crescentmoongames.ravensword2;version=1.3;system=false", "com.dasuppa.metro2033wars;version=1.58.6;system=false", "com.ea.game.simcitymobile_row;version=1.12.11.43315;system=false", "com.ecareme.asuswebstorage;version=3.1.10.9222;system=true", "com.fgol.HungrySharkEvolution;version=3.9.4;system=false", "com.flyersoft.moonreaderp;version=3.5.2;system=false", "com.google.android.apps.maps;version=9.26.1;system=true", "com.google.android.apps.plus;version=7.9.0.122697338;system=true", "com.google.android.apps.uploader;version=1.3.242047;system=true", "com.google.android.backup;version=4.2.2-612687;system=true", "com.google.android.feedback;version=4.2.2-612687;system=true", "com.google.android.gm;version=6.5.122794288.release;system=true", "com.google.android.gms;version=9.0.82 (032-121907432);system=true", "com.google.android.googlequicksearchbox;version=5.13.31.16.arm;system=true", "com.google.android.gsf;version=4.2.2-612687;system=true", "com.google.android.gsf.login;version=4.2.2-612687;system=true", "com.google.android.inputmethod.latin;version=5.0.25.122319759-armeabi-v7a;system=true", "com.google.android.inputmethod.latin.dictionarypack;version=4.2.2-612687;system=true", "com.google.android.location;version=1.1.10;system=true", "com.google.android.marvin.talkback;version=4.5.0;system=true", "com.google.android.music;version=4.5.914I.590354;system=true", "com.google.android.partnersetup;version=4.2.2-612687;system=true", "com.google.android.play.games;version=3.7.23 (2867637-032);system=false", "com.google.android.setupwizard;version=1.3;system=true", "com.google.android.street;version=1.8.1.2;system=true", "com.google.android.syncadapters.bookmarks;version=4.2.2-612687;system=true", "com.google.android.syncadapters.calendar;version=4.2.2-612687;system=true", "com.google.android.syncadapters.contacts;version=4.2.2-612687;system=true", "com.google.android.talk;version=8.1.121732641;system=true", "com.google.android.tts;version=3.8.16;system=true", "com.google.android.voicesearch;version=4.0.0;system=true", "com.google.android.youtube;version=11.19.56;system=true", "com.harebrainedschemes.shadowrun;version=1.2.6;system=false", "com.ideashower.readitlater.pro;version=6.3.0.2;system=false", "com.infraware.PolarisOfficeAsusForTablet;version=4.0.5030.00-FV06;system=true", "com.inxile.BardTale;version=1.6.8;system=false", "com.lastpass.lpandroid;version=4.0.36;system=false", "com.lonelycatgames.Xplore;version=3.82.01;system=false", "com.maxmpz.audioplayer;version=2.0.10-build-588-play;system=false", "com.maxmpz.audioplayer.unlock;version=2-build-26;system=false", "com.miniclip.plagueinc;version=1.11.4;system=false", "com.mxtech.ffmpeg.tegra3;version=1.7.39;system=false", "com.mxtech.videoplayer.pro;version=1.7.40;system=false", "com.newspaperdirect.pressreader.android.hc;version=4.1.12.0817;system=true", "com.nuance.xt9.input;version=3.0.0.0;system=true", "com.nvidia.NvCPLSvc;version=1.0;system=true", "com.nvidia.demo.launcher.glowball;version=null;system=true", "com.nvidia.tegrazone;version=2.9.5;system=true", "com.splashtop.remote.pad.asus;version=1.1.0.18;system=true", "com.suishouxie.asus.supernote;version=1.55;system=true", "com.vkontakte.android;version=4.0.1;system=false", "com.yandex.browser;version=16.2.2.7988;system=false", "com.zinio.android.settings;version=2.03.3331;system=true", "com.zinio.mobile.android.reader;version=1.23.5880;system=true", "de.mobileconcepts.cyberghost;version=5.5.1.7;system=false", "hu.tagsoft.ttorrent.pro;version=1.5.5.4;system=false", "net.fishlabs.gof2hdallandroid2012;version=2.0.11;system=false", "ru.iptvremote.android.iptv.pro;version=3.3.1;system=false", "ru.yandex.mail;version=3.08;system=false" ],
  "installerPackage" : null,
  "kernelVersion" : "3.1.10-g215ae8bf",
  "sslMitmConfiguration" : null,
  "sourceApk" : "/data/app/com.adguard.android-1.apk",
  "referrer" : null,
  "proxySetupManualMode" : false,
  "proxyPort" : 8080,
  "sendAnonymousStatistics" : true,
  "showUsefulAds" : false,
  "proxyMode" : false,
  "premium" : true,
  "filtersAutoUpdateEnabled" : true,
  "trial" : false,
  "dnsFilteringEnabled" : false,
  "deviceSpeedRank" : 846,
  "browsingSecurityEnabled" : true,
  "autoStartEnabled" : false
}

**Comment by Alex-302** [comment]
Экспериментальный фильтр включен?(после обновления приложения появится фильтр раздражителей, и роль ЭФ станет иной)

**Comment by Alex-302** [comment]
Чисто, в т.ч. на на https версии сайта.

**Comment by evgeniy-ADG** [comment]
Чисто

**Comment by vgavrish** [comment]
Расширение. Вин.
Фильтры: 1,2,3,4,14
http://nnmclub.to/forum/viewtopic.php?t=881916
http://prntscr.com/ceb2y5

**Comment by Alex-302** [comment]
Чисто должно быть. Нужен скриншот вкладки Sources из инструментов разработчика.
