### ISSUE TITLE
[iOS] http://www.livelib.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2239]
Пропущена реклама на странице:
http://www.livelib.ru/reader/Felicyia/friends
![image](https://cloud.githubusercontent.com/assets/15856304/15672231/0f3d43ce-2738-11e6-9749-8959fb6dfd94.png)

**Comment by Alex-302** [comment]
Экспериментальный фильтр включен?(после обновления приложения появится фильтр раздражителей, и роль ЭФ станет иной)

**Comment by evgeniy-ADG** [comment]
Все ок, блокируется.
