### ISSUE TITLE
http://happy-hack.ru/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2241]
![image](https://cloud.githubusercontent.com/assets/15856304/15673115/311fbddc-273d-11e6-93ac-b947f63aba61.png)

**Comment by Alex-302** [comment]
@@||ad.admitad.com/3rd-party/advert.js
@@||ad.admitad.com/3rd-party/*/cookie/?f=CookieChecker.remoteTest

**Comment by vgavrish** [comment]
Та же проблема
Хром. Ф: 1,2,14,211
![image](https://cloud.githubusercontent.com/assets/18548949/20261957/c40ee70e-aa68-11e6-8cd0-781cedb64b0b.png)

**Comment by Alex-302** [comment]
fixed
