### ISSUE TITLE
[Stealth mode] block video on facebook

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2242]
Возникает проблема при видеозвонке в фейсбуке.
Когда пытаешься позвонить по видео, открывается окно, но без кнопки "Разрешить":
http://prntscr.com/bakdia

При отключении опции в Антитрекинге - Блокировать WebRTC, звонок совершается без проблем и появляется в окне кнопка "Разрешить".

TICKET ID KFG-703-33359

**Comment by Alex-302** [comment]
@vgavrish 
а куда тыкнуть надо для вызова? У меня фейсбучный акк абсолютно пустой. Может удалённо можно глянуть?

**Comment by vgavrish** [comment]
@Alex-302 
нужен кто-то в друзьях и кликнуть нужно сюда: http://prntscr.com/bdqpgu
удаленно без проблем

**Comment by Alex-302** [comment]
@vgavrish 
давай днём загляну. Напиши когда можно.

**Comment by vgavrish** [comment]
@Alex-302 
если можно 11.06 с 9-00 до 15-00

**Comment by Alex-302** [comment]
Скинь тогда ID и пароль, сюда или в скайп alxbrv
заодно это гляну
https://github.com/AdguardTeam/AdguardFilters/issues/2293

**Comment by Alex-302** [comment]
Добавил в английский
@@||facebook.com/videocall/$stealth
