### ISSUE TITLE
http://www.cnet.com/ - can

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2243]
http://www.cnet.com/videos/top-5-bluetooth-speakers-you-can-buy/
![image](https://cloud.githubusercontent.com/assets/15856304/15676600/871157fc-274f-11e6-88ad-1c199662860f.png)

Also, on the top of the cnet page you cannot swipe right or left to choose another story. I've attached a screenshot of the previous issue which was that the page abruptly ends. Thank you.

**Comment by evgeniy-ADG** [comment]
Works fine when you disable Spyware filter

**Comment by Alex-302** [comment]
Added
@@||cdn.taboola.com/libtrc/cbsinteractive-cnet/loader.js$domain=cnet.com
@@||tags.tiqcdn.com/utag/cbsi/cnetglobalsite/prod/utag.js$domain=cnet.com
