### ISSUE TITLE
Foxtel Browser Version

### ISSUE THREAD

**Issue by ravenaus** [AdguardTeam/AdguardFilters#22445]
https://watch.foxtel.com.au/app/#/play?origin=%2Fshows%2F249382%2Fseasons%2F5%2Fepisode%2F000000480208

The new way they will be running foxtel onlline
and adgaurd does not block the adverts on it

any ideas would be great as they require you to use Chrome
and they are going to disable the windows app.

**Comment by BlazDT** [comment]
Please provide required information.

**Comment by ravenaus** [comment]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

URL: https://watch.foxtel.com.au/app/#/play?origin=%2Fshows%2F249382%2Fseasons%2F5%2Fepisode%2F000000480208

***Description***: Foxtel Web Based Player
* **Current behaviour**: Plays Adverts

[//]: # (Substitute this line with a description of the problem)



[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>
![image](https://user-images.githubusercontent.com/30451585/45559920-18bdfc80-b887-11e8-854a-1a57a11a5ee2.png)
</details><br/>

 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)




[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

||7plus.com.au/js/app.*.js$replace=/t.sevenCatalog.adChoice="ssaibeacon"/t.sevenCatalog.adChoice="csai"/ @@||yospace.com/csm/$xmlhttprequest,domain=7plus.com.au,
7plus.com.au#$#.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links {display:block!important;}

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Chrome
AdGuard version:                       | 6.2
Filters enabled:                       | Yes
AdGuard DNS:                           | Default
Stealth mode options (Windows only)    | Off


[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
