### ISSUE TITLE
cbsnews.com player is blocked

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2244]
http://www.cbsnews.com/videos/530-six-people-dead-2-missing-after-weekend-flooding-veteran-wounded-in-afghanistan-climbs-mt-everest/
More details here - LYA-968-60280
![screen shot 2016-05-31 at 6 44 50 pm](https://cloud.githubusercontent.com/assets/14153331/15680894/edefd254-275f-11e6-912b-17fc849d5c98.png)

**Comment by Alex-302** [comment]
to social filter:
`cbsnews.com##.sharebar_expanded`
to spyware
'@@||tags.tiqcdn.com/utag/cbsi/cbsnewssite/prod/utag.js$domain=cbsnews.com'
