### ISSUE TITLE
com.ebay.kijiji.ca

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2245]
https://play.google.com/store/apps/details?id=com.ebay.kijiji.ca
"Adguard won't let me browse any listings in the app and blocks everything"
Logs - FQH-778-20435

**Comment by shaurmanchic** [comment]
Screenshots
![screenshot_20160531-192053](https://cloud.githubusercontent.com/assets/14258460/15721227/02604d08-2806-11e6-81cb-4e0b5d449e83.png)
![screenshot_20160531-192115](https://cloud.githubusercontent.com/assets/14258460/15721226/0257d7d6-2806-11e6-9093-a1772cc1c367.png)

**Comment by Alex-302** [comment]
Fixed in mobile filter
`@@||mingle.kijiji.ca/api/ads/`
