### ISSUE TITLE
[iOS] Missed Ads - online.anidub.com

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2246]
http://online.anidub.com/anime_tv/full/9369-sharlotta-charlotte-01-iz-13.html

Стандартные обновленные фильтры.
При нажатии на видео, вылетает предложение установить другой браузер и реклама в шапке.

![img_9318](https://cloud.githubusercontent.com/assets/16462533/15703145/8628a1a4-27ec-11e6-830a-5b289e9158bb.PNG)
![img_9319](https://cloud.githubusercontent.com/assets/16462533/15703146/862a6a7a-27ec-11e6-978d-b72131226f65.PNG)

**Comment by Alex-302** [comment]
В русский:
`||moonwalk.co/api/morefunc`
в фильтр Сафари(проблема со вторым плеером)
`@@||tube.buzzoola.com$domain=anidub.com`

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/25347192/b6941caa-2922-11e7-9d3e-1bf7ff5a7398.png)

**Comment by Alex-302** [comment]
Fixed
