### ISSUE TITLE
User can't open links in emails from model-car-world.co.uk

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2247]
On two occasions now I have received an email from a company that sells model cars. If I click on the links in the email Adblocker cuts in with a warning message the the links are to a potentially dangerous, duplicate site. This has happened with the last two emails received but did not happen before that, and I have been receiving emails from this company for years. I have reported it to the company who forwarded it to their network provider who say that it must be a virus on my computer that is changing the links. This seems very unlikely as it only happens with their emails and I have McAfee and I run Malwarebytes and Hitman Pro, neither of which have detected any problems. The company concerned is model-car-world.co.uk and the links try to go to instead to track.mlsend.com. I'd value your opinion; I can forward the email to you if you wish. Thank you.

![image](https://cloud.githubusercontent.com/assets/15856304/15709722/e8536ac2-280e-11e6-8bca-bb4c2773036e.png)

you can find forwarded email here; EOH-544-60637

**Comment by Alex-302** [comment]
@evgeniy-ADG 
я не могу их базы фишинга удалять сайты. @vbagirov глянь плиз

**Comment by ameshkov** [comment]
Удалил
