### ISSUE TITLE
ragalahari.com [Ad String]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#22480]
**Site**: http://www.ragalahari.com/localevents/185682/4/siima-2018-day-1-photos.aspx

**Issue**: Please remove the Ad string on the page.
 
**Screenshot**: http://prntscr.com/kumj9v

**OS**:
> `Windows 7 (32 bit)`

**Browser**: 
>` Chrome 69.0.3497.92 (Official Build) (32-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.8 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
Still observing oon Android. Can you please check.

**Comment by Nzzyme** [comment]
Seeing ad text string on this link: http://www.ragalahari.com/localeventssearch.aspx

Screenshot: http://prntscr.com/l5j6dg

**Comment by Alex-302** [comment]
fixed

**Comment by Nzzyme** [comment]
https://www.ragalahari.com/movies/89469/one-night-999-movie-gallery.aspx

Ad text string seen on the page.

https://i.imgur.com/UVfj6U1.png
