### ISSUE TITLE
https://www.mediamarkt.de - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2249]
https://www.mediamarkt.de/webapp/wcs/stores/servlet/LogonForm?storeId=19501&langId=-3&redirectURL=https%3A%2F%2Fwww.mediamarkt.de%2F

![image](https://cloud.githubusercontent.com/assets/15856304/15748022/ea41a268-28e5-11e6-88db-9866d8678a3d.png)

When I click on the button with the red guy, should be opening my account but they don't open it because they load endless. 
TICKET ID
WQE-334-83362

**Comment by Alex-302** [comment]
added to spyware filter:
```
@@||googletagmanager.com/gtm.js$domain=mediamarkt.de
@@||google-analytics.com/analytics.js$domain=mediamarkt.de
@@||google-analytics.com/plugins/ua/ec.js$domain=mediamarkt.de
```
to annoyances:
```
mediamarkt.de##.mrh-app-banner
mediamarkt.de#$#.app-banner-active header.mrh-header { top: 0px!important; }
mediamarkt.de#$#.app-banner-active #header-wrapper { height: 50px!important; }
```
