### ISSUE TITLE
http://dailycaller.com - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2250]
TICKET ID
XSR-741-25209

Missed ads powered by Adreclaim and Outbrain
screenshots: http://imgur.com/a/92TWP
links: 
http://dailycaller.com/2016/06/01/it-took-35-minutes-for-the-ucla-shooting-to-be-about-gun-control/
http://dailycaller.com/2016/06/01/cops-teacher-traumatized-13-year-old-student-with-months-of-sex/

**Comment by Alex-302** [comment]
blocking of ads:
`||widgets.outbrain.com/outbrain.js$domain=dailycaller.com`
fixing loading when scrollong down:
`@@||partner.googleadservices.com/gpt/pubads_impl_$domain=dailycaller.com`
