### ISSUE TITLE
indianpornfuck.com [NSFW] [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#22500]
**Site**: http://www.indianpornfuck.com/best/Doggy%20Style_1/index.php

**Issue**: Please remove the pop-up and the close button at the bottom right of the page.
 
**Screenshot**: http://prntscr.com/kuolbg

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 69.0.3497.92 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.8 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by AdamWr** [comment]
I can't reproduce popup.
