### ISSUE TITLE
http://zagrandok.ru/ - ads 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2251]
http://zagrandok.ru/migraciya-v-rf/vnzh-v-rf/vnzh-dlya-belorusov.html

![image](https://cloud.githubusercontent.com/assets/15856304/15750429/18424556-28ef-11e6-887d-3e266dcffe94.png)

![image](https://cloud.githubusercontent.com/assets/15856304/15750435/200fda50-28ef-11e6-8bce-2acb4a35dbe3.png)

**Comment by Alex-302** [comment]
zagrandok.ru##a[href*="travelpayouts.com/click?"]
zagrandok.ru##a[href^="http://top3travel.ru/"]
