### ISSUE TITLE
[WIN] Missed Ads mp3sort.biz

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2252]
http://mp3sort.biz

Фильтры стандартные, обновленные.
![2016-06-02_19-30-58](https://cloud.githubusercontent.com/assets/16462533/15753004/726130c4-28f9-11e6-8b12-f69b38c50e2e.png)

**Comment by Alex-302** [comment]
Не уверен на счёт рекламности. Может это просто часть дизайна, и ролики их?

**Comment by Serzh-SUP** [comment]
@Alex-302 
Похоже что да, ссылки ведут на их канал Ютуба.
