### ISSUE TITLE
imdp app - video ads in trailer

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2253]
@Alex-302 please check if we can block it.

**Comment by Alex-302** [comment]
Video ad is loaded by playlist with the main video.
Replacing of VAST section doesn't help, only
``
||onceux.unicornmedia.com/now/ads/vmap/*&UMADPARAMcsid=imdb.us.android$replace=/(<vmap:VMAP[\s\S]*?>)[\s\S]*<\/vmap:VMAP>/\$1<\/vmap:VMAP>/
```
Added to mobile filter.
