### ISSUE TITLE
missed ads on different sites

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2255]
Обновленные базовые фильтры.

**http://pb.wtf**

![pb wtf1](https://cloud.githubusercontent.com/assets/16462533/15778181/2e9cf73e-299d-11e6-81d2-605653af50ba.jpg)
![pb wtf2](https://cloud.githubusercontent.com/assets/16462533/15778180/2e9c6e86-299d-11e6-969e-db08a88573b3.jpg)

**http://fost.ws** - остается LOADING как на скрине

![fost ws](https://cloud.githubusercontent.com/assets/16462533/15778202/46d72478-299d-11e6-9ee7-77579d0ee895.jpg)

**http://kinopoisk.ru/** - пустое место в шапке.

![default](https://cloud.githubusercontent.com/assets/16462533/15778246/9c46a514-299d-11e6-9d65-27728275ee20.jpg)

**http://gta.com.ua/** - пару рекламных баннеров слева

![gta com ua](https://cloud.githubusercontent.com/assets/16462533/15778294/f14cacd4-299d-11e6-97a9-1e19fe194b92.jpg)

**www.skidrowcrack.com** - рекламные баннеры справа.

![www skidrowcrack com](https://cloud.githubusercontent.com/assets/16462533/15778323/19c55eb8-299e-11e6-95b9-9e7f9c4d97d4.jpg)

**Comment by Alex-302** [comment]
у кинопоиска два дизайна, так что пустоту лучше не трогать.
gta.com.ua - только картинки убрал. Текстовый блок не отличим от рекламы.
Остальное почистил.

**Comment by Serzh-SUP** [comment]
@Alex-302 
У меня почистилось все, кроме http://pb.wtf

**Comment by Alex-302** [comment]
Угу, забыл в фильтр добавить.
