### ISSUE TITLE
Ads in google apps such as Chrome and Search

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2256]
![image](https://cloud.githubusercontent.com/assets/15856304/15779838/61bde3e4-29a7-11e6-84ed-506aecc36cbc.png)

Ads in google apps such as Chrome and Search don't seem to be getting blocked. Everything else seems to work fine though. It's been a few years since I've used Adguard, and I can't figure out why it's not working.
I've cleared the app caches, Adguard was already on High-Quality, and the apps do have ad-blocking enabled in the firewall. (I don't think I included this originally, but I also have the cert installed for https adblocking.)

logs TPK-427-87503

**Comment by Alex-302** [comment]
@evgeniy-ADG 
у меня не повторяется с амениканским впн. Попроси установить бету и записать HAR файл. 
Инструкция
https://kb.adguard.com/index.php?/Russian/Knowledgebase/Article/View/65/0/how-to-get-har-http-archive-files-from-android-device

**Comment by KozelElena** [comment]
We have a HAR needed. It's here: 1514200

**Comment by Alex-302** [comment]
I don't see required requests in this HAR. Please ask to make it in private tab and refresh it few times, and send HAR after that.

**Comment by Michael23456** [comment]
here is the answer from the customer: " The issue is not in the browser but when I use the Google search widget on my Nexus 6p. It opens the search results but with ads in them."

**Comment by Alex-302** [comment]
Ah, we can't filter Google app.
