### ISSUE TITLE
mangarock app

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2258]
http://www.mangarockapp.com/definitive.html
http://files.nabstudio.com/mangarock/mangarock-definitive-v2.0.5-RELEASE.apk
![screenshot_20160603-082006](https://cloud.githubusercontent.com/assets/14153331/15785666/19f90222-29c1-11e6-80c6-29ab4806f63a.png)
![screenshot_20160603-082035](https://cloud.githubusercontent.com/assets/14153331/15785667/1b8a8232-29c1-11e6-9ae5-751f4b835f59.png)

**Comment by Alex-302** [comment]
I can't block it.
Can you write to Android section?

**Comment by Bohdan-SUP** [comment]
Done:
https://github.com/AdguardTeam/AdguardForAndroid/issues/623
