### ISSUE TITLE
samsung.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2259]
http://www.samsung.com/ua_ru/support/usefulsoftware/KIES/
Page is loaded blank with Annoyances filter enabled. Video here - WWG-190-12204

**Comment by Alex-302** [comment]
@Bohdan-SUP 
у тебя повторяется? У меня нормально всё.

**Comment by Bohdan-SUP** [comment]
Уже не повторяется.

**Comment by vgavrish** [comment]
@Alex-302 опять повторилось
http://prntscr.com/bcyavp
http://prntscr.com/bcybu5

Помогает отключение ЭФ

**Comment by Alex-302** [comment]
Не может быть, не верю)
У тебя повторяется? У меня во всех браузерах нормально отображается.

**Comment by vgavrish** [comment]
@Alex-302 
ха, сейчас все ок)
