### ISSUE TITLE
Foxtel Web Based Player

### ISSUE THREAD

**Issue by ravenaus** [AdguardTeam/AdguardFilters#22606]
URL: https://watch.foxtel.com.au/app/#/play?origin=%2Fshows%2F249382%2Fseasons%2F5%2Fepisode%2F000000480208

Description: Foxtel Web Based Player

Current behaviour: Plays Adverts
Screenshot:
![image](https://user-images.githubusercontent.com/30451585/45559920-18bdfc80-b887-11e8-854a-1a57a11a5ee2.png)

System configuration

Filters:

||7plus.com.au/js/app.*.js$replace=/t.sevenCatalog.adChoice="ssaibeacon"/t.sevenCatalog.adChoice="csai"/ @@||yospace.com/csm/$xmlhttprequest,domain=7plus.com.au,
7plus.com.au#$#.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links {display:block!important;}

Information | Value
-- | --
Operating system: | Windows 10
Browser: | Chrome
AdGuard version: | 6.2
Filters enabled: | Yes
AdGuard DNS: | Default
Stealth mode options (Windows only)

**Comment by Alex-302** [comment]
Hi
We have no access to the video. Could you please create a test account?

**Comment by ravenaus** [comment]
Can we do teamview and you can test that way?

**Comment by Alex-302** [comment]
yes

**Comment by Alex-302** [comment]
Please send password and IP to `@A;ex302` on our forum https://forum.adguard.com

**Comment by ravenaus** [comment]
The advert issue was never fixed? So should it still not be in progress?

**Comment by Alex-302** [comment]
I don't forget about it. Tried, but can't block ads.
