### ISSUE TITLE
http://couchtuner.city - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2261]
This site in general when the ad blocking is on all the videos played won't load all white screens etc... 

Incorrect blocking on page:
http://couchtuner.city/3/the-musketeers-s3-e8-prisoners-of-war/

**Comment by Alex-302** [comment]
Can't check on the real device, but on Android it works.
@Serzh-SUP @Bohdan-SUP could you check it?
