### ISSUE TITLE
zhizninauka.info

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2262]
http://zhizninauka.info/topics/kakogo-tsveta-zebra/

При нажатии на любую область статьи открывается новый сайт Booking.
http://prntscr.com/bc6hsx
Также спустя несколько секунд вылазит такая строка:
http://prntscr.com/bc6ifj

**Comment by Alex-302** [comment]
От кликандера:
`zhizninauka.info#%#Object.defineProperty(window, 'clickunderRun', { get: function() { return {}; } });`
сокрытие ленты:
`zhizninauka.info##body > div.tve-leads-ribbon'
