### ISSUE TITLE
surfingbird.ru - scroll is blocked for first 10 seconds

### ISSUE THREAD

**Issue by Joss** [AdguardTeam/AdguardFilters#2263]
Sometimes a page full loading takes a lot of time.
The example: [URL](http://4pda.ru/pages/go/?u=http%3A%2F%2Fsurfingbird.ru%2Fsurf%2Fkak-prigotovit-idealnyj-borshch--v8Vi7A66E%3F_auth%3D7ERpg_oq2UdHlkBDoXIoQg%242b6a25cc6d177e49db001584025a9925e6397b5e%26utm_campaign%3Dnewsletter_2016-06-03%26utm_content%3Dteaser5%26utm_medium%3Demail%26utm_source%3Dnewsletter&e=50126145)

w/o Adguard full page loading time ~ 3s.
with Adguard (with any settings, VPN/Proxy no matter) it takes about 15s (first part of page rendering within 2s, but you can scroll down the page only through 15s)

Adguard 2.6.67 beta 
Android 6.0.1, HTC One M8, Sense custom ROM.
[4pda link](http://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=50126145)

**Comment by Joss** [comment]
Could you move to AdguardForAndroid branch?

**Comment by Alex-302** [comment]
No, I can't move. You can just duplicate it to AdguardForAndroid and close it here.

**Comment by Joss** [comment]
I did it, thanks
https://github.com/AdguardTeam/AdguardForAndroid/issues/618

**Comment by ameshkov** [comment]
@Alex-302 this is a filters issue.

Easy to reproduce, just use the Chrome dev tools "mobile view" and keep an eye on top-level div classes.

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||relap.io/api/*/head.js?$domain=surfingbird.ru
```
to annoyances(mobile app banner)
```
surfingbird.ru##.b-mobile-redirect
```
