### ISSUE TITLE
vnukovo.ru - broken by social filter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2264]
Can't check arrivals at Vnukovo international airport, that part is unclickable.

http://www.vnukovo.ru/en/#fly-in

http://www.vnukovo.ru

It appears it is caused by social media filter, once it's off it woks fine.

**Comment by Alex-302** [comment]
Added
`@@||yandex.st/share/share.js$domain=vnukovo.ru`
