### ISSUE TITLE
idnes.cz

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2265]
http://zpravy.idnes.cz
LVC-422-49670
ADG on:
![screen shot 2016-06-06 at 10 03 25 am](https://cloud.githubusercontent.com/assets/14153331/15814253/126fafba-2bce-11e6-9238-55b1568da8f0.png)
ADG off:
![screen shot 2016-06-06 at 10 03 39 am](https://cloud.githubusercontent.com/assets/14153331/15814257/17186296-2bce-11e6-84e8-789207c5d250.png)
User also had Adblocking detection, but I wasn't able to reproduce it:
![adguard-idnes_cz](https://cloud.githubusercontent.com/assets/14153331/15814263/1f06e25c-2bce-11e6-9a64-55328e75e918.gif)

**Comment by Alex-302** [comment]
Can't reproduce. Which filters are enabled?

**Comment by evgeniy-ADG** [comment]
Hallo,
it seems to idnes.cz removed adblock detection yesterday.
I can not see it again.

**Comment by Alex-302** [comment]
That's good)
