### ISSUE TITLE
com.freeletics.lite 

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2266]
https://play.google.com/store/apps/details?id=com.freeletics.lite
Disabling HTTPS helps
![screenshot_20160601-110908](https://cloud.githubusercontent.com/assets/14153331/15815439/c2736346-2bd5-11e6-928e-54110a4eec42.png)

User ID - 1165335

**Comment by Alex-302** [comment]
с подменой сертификата проблема
