### ISSUE TITLE
com.etrade.mobilepro.activity

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2268]
Disabling https helps
![screenshot_20160601-111108](https://cloud.githubusercontent.com/assets/14153331/15815450/d4d70d08-2bd5-11e6-9227-ad87f890441f.png)

**Comment by Alex-302** [comment]
@Bohdan-SUP 
там регистрация мутная. Попроси юзера сделать аккаунт, а так же лог HTTP запросов с включенной фильтрацией HTTPS с указанием времени запуска приложения. Только проверь плиз сразу, правильно ли сделан лог(должны быть строки содержащие com.adguard.android.FilteringLog)

**Comment by Bohdan-SUP** [comment]
Спросил, отпишусь.
