### ISSUE TITLE
folha.uol.com.br

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2269]
http://painel.blogfolha.uol.com.br/2016/06/04/equipe-de-temer-corta-comida-de-dilma-rousseff-no-palacio-da-alvorada/
![screen shot 2016-06-06 at 12 09 51 pm](https://cloud.githubusercontent.com/assets/14153331/15817214/a3e535f8-2bdf-11e6-83de-175681ae2dec.png)
User ID - 1082297

**Comment by Alex-302** [comment]
Added to Spanish/Portuguese filter
`||folha.uol.com.br/folha/furniture/paywall/loader.js'
