### ISSUE TITLE
http://politiken.dk/ - anti adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2270]
![image](https://cloud.githubusercontent.com/assets/15856304/15818530/9b46a966-2be6-11e6-89b6-d950161d30d0.png)

Clear on Mac, reproduced on Win

crm id 1157108

**Comment by Alex-302** [comment]
added to annoyances filter
`||politiken.dk/bruger/AdblockBlocker/?`
