### ISSUE TITLE
irecommend.ru - yandex direct

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2271]
http://irecommend.ru/content/ochen-spetsifichnyi-neobychnyi-aromat-s-notkoi-mertvykh-popugaichikov-dlya-neordinarnykh-lyu
![screenshot_2016-06-06-14-43-05](https://cloud.githubusercontent.com/assets/15856304/15820949/6ee34276-2bf5-11e6-8193-6a74e932993f.png)
HTTPS is on, HQ mode

**Comment by Alex-302** [comment]
в русский
```
||loader.adrelayer.com^$third-party
||irecommend.ru/ya-mart/
irecommend.ru##.brusok.brusok-processed
```
в раздражители
irecommend.ru##.product-half-teaser  > div.text > div#bigright
