### ISSUE TITLE
[Browser extension] beta.theage.com.au

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#2272]
For example:
http://beta.theage.com.au/victoria/human-rights-watchdog-rules-against-firefighters-union-industrial-deal-20160605-gpc210.html

Reproduced with Chrome extension for  Windows.

Screenshot: http://screencast.com/t/8uFHsuW34

Original forum threat:
https://forum.adguard.com/index.php?threads/manual-select-of-add-not-working.10941/

**Comment by Alex-302** [comment]
added
||strap.domain.com.au^$domain=theage.com.au
theage.com.au##iframe[name="domain_dream_homes"]
||fairfaxmedia.sharedcount.com^$third-party
