### ISSUE TITLE
missed ads tele-satinfo.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2274]
http://tele-satinfo.ru/

Фильтры обновленные, базовые.

![default](https://cloud.githubusercontent.com/assets/16462533/15835108/2bee9e4c-2c37-11e6-90d5-ca9fb71fbce7.jpg)

**Comment by Alex-302** [comment]
added
tele-satinfo.ru##a[rel="nofollow"]:not([href^="http://tele-satinfo.ru"]) > img[alt]
||tele-satinfo.ru/banners/
