### ISSUE TITLE
20min.ch useful content is blocked

### ISSUE THREAD

**Issue by tiberian83** [AdguardTeam/AdguardFilters#2275]
On 20min.ch within articles Adguard blocks useful content (pictures). Tried on iOS Safari.

**Comment by tiberian83** [comment]
![image](https://cloud.githubusercontent.com/assets/10312300/15856242/a2cdf760-2cb4-11e6-85da-a9840b9208b8.png)
![image](https://cloud.githubusercontent.com/assets/10312300/15856243/a2d10cfc-2cb4-11e6-9115-be2aa79185c6.png)

**Comment by Alex-302** [comment]
Hi
I need the filters list and direct link to the broken page

**Comment by tiberian83** [comment]
Here is a direct link. But it happens in almost every article not just this one.

http://www.20min.ch/digital/news/story/China-Handy-laesst-Apple-und-Samsung-zittern-26738050

**Comment by tiberian83** [comment]
![image](https://cloud.githubusercontent.com/assets/10312300/15858551/6eedfa1e-2cc1-11e6-9ca8-8018eb364f15.png)
![image](https://cloud.githubusercontent.com/assets/10312300/15858552/6ef261a8-2cc1-11e6-9a86-e0b217754753.png)
![image](https://cloud.githubusercontent.com/assets/10312300/15858554/6ef41958-2cc1-11e6-9e0e-954cb45f8c5b.png)
![image](https://cloud.githubusercontent.com/assets/10312300/15858553/6ef27dd2-2cc1-11e6-9d69-66f9a9a72ebc.png)

**Comment by Alex-302** [comment]
Please try to temporary disable filters from the end of the list with checking. You can disable them by parts - by three filters. You can find the problem filter, and I will fix it on our side.

**Comment by Alex-302** [comment]
I can't reproduce this issue with your filters list.

**Comment by tiberian83** [comment]
Funny thing. I disabled all filters except Adguard English and the picture reappeared. Then I reenabled filter by filter. Now I have them all enabled again and the picture is still there. Maybe there was a bug within cache? Anyways it seems to work fine again. :)

**Comment by Alex-302** [comment]
Are you using optimized filters?

**Comment by tiberian83** [comment]
Yes, I think so. Is there another option than optimized filters on iOS?

**Comment by Alex-302** [comment]
Only full and optimized. I don't use iOS devices, and don't know where it is.
@vozersky could you please make a screenshot of this setting?

**Comment by vozersky** [comment]
@Alex-302 sure thing

![img_0034](https://cloud.githubusercontent.com/assets/17472907/15866772/c4709e0c-2ce8-11e6-9393-8074d266497f.PNG)

![img_0035](https://cloud.githubusercontent.com/assets/17472907/15866774/c849a5aa-2ce8-11e6-8f34-407a60edcd2d.PNG)

**Comment by tiberian83** [comment]
Oh wait, I forgot to reenable Adguard German filter. As soon as I did, the pictures are gone again. So the issue is within Adguard German filter.

**Comment by Alex-302** [comment]
@tiberian83 
could you please check with only Adguard German filter? I have no real device...

**Comment by tiberian83** [comment]
I just did, no picture. It's defenitly within Adguard German filter.

**Comment by Alex-302** [comment]
@tiberian83 Don't you have a Mac?

**Comment by tiberian83** [comment]
Yes I do have a Mac and iOS.

**Comment by tiberian83** [comment]
But this issue seems only to appear on iOS devices. But I will check it on my Mac later too.

**Comment by Alex-302** [comment]
You can check it with mobile user agent in Safari.

**Comment by tiberian83** [comment]
What do I need to do there? The bug only happens on the iPhone but not on the iPad or desktop Safari. So only the mobile page of 20min.ch is affected by it.

**Comment by Alex-302** [comment]
You can enable developer mode, then go to new menu Develop and change User-agent to iPhone. After that make a minimal width of browser and refresh the tab with this site.
If you want, I can do it via Teamviewer.

**Comment by tiberian83** [comment]
Ok, I will try it at home.

I just checked Android (Chrome) with full version of Adguard. It blocks the same pictures as on iOS. 

Here is a link:
http://www.20min.ch/schweiz/news/story/Die-Kartoffeln-faulen--die-Erdbeeren-schimmeln-20296155

**Comment by tiberian83** [comment]
![image](https://cloud.githubusercontent.com/assets/10312300/15957112/3c9127ac-2eed-11e6-8bee-08d85a96e9fc.jpeg)

**Comment by Alex-302** [comment]
Ok, confirmed.
Added:
```
20min.ch#@#.teaser.panelbox
```

**Comment by tiberian83** [comment]
I just updated the filters. Unfortunately it's not fixed yet. Neither on Android nor on iOS.

**Comment by tiberian83** [comment]
Weird. It's still broken on my devices.

**Comment by Alex-302** [comment]
You should to wait. Update is now available.

**Comment by tiberian83** [comment]
Now it works. Thank you a lot!
