### ISSUE TITLE
www.clien.net won't load randomly

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2276]
> I am not sure whether this is related to
> Adguard or not, but it seems to and any help would be appreciated!
> I've noticing that, when I browse a website "www.clien.net", a loading
> takes a long time or even does not finish in a particular website
> intermittently. If I disable Adguard and do random things in this
> website, like viewing a post and opening a menu, I don't see a problem
> with page loading. However, if I enable Adguard, it works almost fine
> but rarely page does not load. Here the setting of Adguard I used is -
> I have English filter, Spyware filter, Social media filter,
> Experimental filter, Mobile ads filter enabled, and I don't have any
> rules in User filter. I have HTTPS filtering enabled, filtering method
> is set to high-quality, and I am using VPN method for filtering.
> Because it is rare to encounter such page loading problems, I can't
> confirm that it is related to Adguard, but as I used it long time and
> tried some experiments, now I am becoming to believe that this is
> related to Adguard. I am experiencing this with all browsers I have
> tried. Maybe it is related to some third party app causing some
> conflict with browsers, and if then it won't be reproducible.. If this
> is reproducible, please

ticked id 1101991

**Comment by Alex-302** [comment]
Can't reproduce after many refreshes and opening links.
Maybe it is caused bu mobile internet.

**Comment by evgeniy-ADG** [comment]
Me neither.
