### ISSUE TITLE
filter rules that needs to be re-evaluated(based on personal observation)

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdguardFilters#22778]
Making individual issue for each seems kind of excessive so ill post here(based on my observations) some websites where the current filter rules either not working or making things worse and needs re-evaluation.They're not that many but if dev's agree we can keep the issue open and i'll keep adding in the feature.Here you go:

1.  vshare.eu
The embedded's player controls are messed up big times.Full screen is not working either.As seen here:
https://vshare.eu/bo4c5jwyilot.htm
<details><summary>Screenshot:</summary>

![vshare](https://user-images.githubusercontent.com/34774426/45834367-85445b80-bccc-11e8-877b-56456e207877.png)

</details>

2. www.proporn.com
Player is not working(videos does not start after clicking on play).Looks like the ads are to much embedded in to the player and blocking them prevents videos from playing

3. xxxdan.com
Player not even initiating there,neither "similar videos" section.

4. suprafiles.me
As of recent(i guess) the site implemented BlockAdblock so `@@||suprafiles.me^$generichide' needs to be added to the filters.
https://suprafiles.me/uxlat7nsqgw8

5. Not possible to login in `bitbucket.org` (`id.atlassian.com`) when stealth mode is enabled(similar to #22422). `@@||atlassian.com^$stealth` needs to be added and third-party cookies to be allowed in the browser as well.
<details><summary>Screenshot:</summary>

![atlassian account](https://user-images.githubusercontent.com/34774426/45835514-f5a0ac00-bccf-11e8-8d78-71635ab458f5.png)

</details>

Dev's,let me know if it's OK to keep posting here if i stumble on something in the feature or posting several issues at once won't work for you.Thank you.

***System configuration***
Windows 10 1607 V.14393.2485 LTSB

**Filters:**
AG Base filter
AG Spyware filter
Easy Privacy
AG Social Media filter
AG Annoyances filter
Fanboy's Annoyances
Spam404

**Browser**
Slimjet Browser 20.0.4.0 (based on Chromium 68.0.3440.75) (Official Build) (64-bit)

**Comment by BlazDT** [comment]
Fixed 1-4, number 5 I can't reproduce (previously the origin.com I also couldn't reproduce).
It would be better if you would open one issue for each site.
@TheHasagai @AdamWr please check number 5 stealth.

**Comment by dnmTX** [comment]
@BlazDT  in stealth mode i have `self-destructing third-party cookies` set to 0.This might be the culprit here. I was able to login successfully with `@@||atlassian.com^$stealth`
Thank you for fixing 1-4 👍 

Same ISSUE when trying to login in **forums.geforce.com**. Applying `@@||nvidia.com^$stealth` fixes it for me.

P.S. Can we keep that issue open so if there is anything else just to add it here?

**Comment by dnmTX** [comment]
@BlazDT  `@@||vshare.eu/embed-`  DOES NOT fixes the player controls on my end.It's the same,no difference.

**Comment by dnmTX** [comment]
Ok...that's the last one(promise 😁) Don't have any links handy at the moment but from what i remember 
**uploadbank.com** also implemented BlockAdblock so it's good to add `@@||uploadbank.com^$generichide` to the EnglishFilter as well.

**Comment by BlazDT** [comment]
It is a separate issue with French filter. I added three rules regarding vshare.eu. The one you are looking for is the .css rule.

I did check it with third-party 0.

**Comment by dnmTX** [comment]
@BlazDT  great job man,thanks again for fixing it.About the `stealth` issue,it's ok.I'll keep those in my custom filter,no biggie.You can close this if you want.

**Comment by AdamWr** [comment]
Regarding `bitbucket.org/id.atlassian.com` and `forums.geforce.com`, added:
`@@||id.atlassian.com^$stealth`
`@@||login.nvgs.nvidia.com^$stealth`
Please check the result.

**Comment by dnmTX** [comment]
@AdamWr  tested both,no issues.Thank you @AdamWr  and @BlazDT  for the help here,very much appreciated.Keep up the good job guys.Big AdGuard fan here.

**Comment by dnmTX** [comment]
@BlazDT  mine as well fix `youporn.com` too(player not working,no images are showing).
Whoever did that aggressive rule: `|https://$image,media,script,third-party,domain=......` to all the porn sites, tell'em that it's just plain stupid 😤
