### ISSUE TITLE
http://www.vgtv.no Incorrect blocking on page

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2277]
Incorrect blocking on page:
http://www.vgtv.no/#!/video/128403/slangen-lever-saa-gjoer-han-dette
Indeed, the video player is missing at the top of the page. If you scroll down, you'll see the image of the video with a button "To the top", but there is no video at the top.
screenshots(first three are from Chrome, the other two are from Safari iOS 9.3):
http://imgur.com/a/hpsOc

**Comment by Alex-302** [comment]
@evgeniy-ADG 
какие фильтры? У меня нормлаьно отображается
