### ISSUE TITLE
www.peelenmaasvenray.nl - anti-adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2279]
I have installed the filters "Adblock Warning Removal List" and the "Anti-Adblock Killer Reek"
I still see on a dutch website: www.peelenmaasvenray.nl the website message "You are using an adblocker on the Edge browser and the Chrome browser(this message shouldn't be not visible with the above filters on) see link screenshots:
http://goo.gl/KG9AEl
http://goo.gl/qzAdfF

**Comment by Alex-302** [comment]
added to annoyances
@@||peelenmaasvenray.nl/scripts/showads.js

**Comment by gvanosch12** [comment]
Hello Alex,

I have tried today friday june 10 to visited the same website:  http://www.peelenmaasvenray.nl/#  on the chrome and Edge browser  unforteanally the same message apear on this site  "you are using an adblocker" (see screenshot links)

http://www.awesomescreenshot.com/image/1317576/50196222d2fe1cedd0c8e1bb8b1fea2f

http://www.awesomescreenshot.com/image/1317574/d3cf1f47aa2e3062c26cfee725fc1f32

Kindly regards,

Geert Van Osch

**Comment by Alex-302** [comment]
This message doesn't break the page, so the rule is added to annoyances filter. You should to enable it.
Or add the rule to user filter, if you don't want to enable that filter.

**Comment by gvanosch12** [comment]
Hello Alex,

I have enabled the annoyances filter and the problem does not apear again

Thanks!

Geert Van Osch
