### ISSUE TITLE
missed ads 4pda.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2280]
Фильтры базовые, обновленные. Повторилось.
![image1](https://cloud.githubusercontent.com/assets/16462533/15871217/1b57d2ae-2cfc-11e6-8854-5af16b15d976.PNG)

**Comment by Alex-302** [comment]
На iOS не скрыть. Баннер здесь - родительский элемент, а содержимое - внутри него.

**Comment by evgeniy-ADG** [comment]
Но его можно сильно уменьшить и сделать некликабельным, вот правило:
4pda.ru###rHIsgR1k > ARTICLE.post:first-child > DIV.visual:first-child > A.r4mN2XBz0P.rFV30vD:first-child

1255452 от 12 июня

**Comment by Alex-302** [comment]
Они имена элементов генерируют случайным образом, и порядок элементов тоже меняют.

**Comment by Bohdan-SUP** [comment]
@Alex-302 
а такое можно заблокировать?

![screen shot 2016-10-22 at 1 07 25 pm](https://cloud.githubusercontent.com/assets/14153331/19618655/6418d416-9859-11e6-801a-aca2193793cd.png)

**Comment by Alex-302** [comment]
в сафари будет сложно и небезопасно. Они периодически порядок элементов меняют, а названия генерируют случайным образом.
