### ISSUE TITLE
yandex.ru - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2281]
![image](https://cloud.githubusercontent.com/assets/15856304/15871511/a6a34cfc-2cfd-11e6-9a03-327c8959d91c.png)
Доброго Вам дня! Выполнил Ваши рекомендации, установил 2.6 бета. результат тот же, в браузере"ХРОМ" при пользовании мобильным инетом (поисковик - Яндекс) под строкой ввода поиска выскакивает рекламный банер. данная проблема у меня на планшете под управлением Андроид. 

ID 1078699 - HAR тут

**Comment by Alex-302** [comment]
Скорее всего не работает фильтрация HTTPS, т.к. этот баннер скрывается двумя правилами
```
###banner
##iframe[width="728"][height="90"]
```
Нужно нажать на замок в адресной строке браузера и посмотреть подробности.

**Comment by evgeniy-ADG** [comment]
Написал, но в стейте вот такое:
 "sslMitmConfiguration" : "{\"appsExceptions\":\"50 apps\",\"mitmListMode\":\"WHITELIST\",\"mitmList\":\"177 domains\"}",

**Comment by Alex-302** [comment]
Нет ответа?
Попроси ещё проверить, есть ли в C:\ProgramData\Adguard\NetworkTemp\SSL
файлы x.db и/или vx.db. Если есть, нужно выключить Адгард, остановить службу и удалить эти файлы.

**Comment by evgeniy-ADG** [comment]
Молчат.
