### ISSUE TITLE
www.bigbangnews.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2282]
http://www.bigbangnews.com/politica/Arritmias-y-reposo-como-esta-el-corazon-de-Mauricio-Macri-20160604-0002.html
'Facebook' on the bottom:
![screen shot 2016-06-07 at 11 24 14 pm](https://cloud.githubusercontent.com/assets/14153331/15873397/313c1f84-2d07-11e6-97c5-ed35a6528df7.png)

**Comment by Alex-302** [comment]
to social
bigbangnews.com##.share-me
bigbangnews.com##.follow-fb-fixed
to annoyances
bigbangnews.com##.follow-fb-fixed
