### ISSUE TITLE
constitution.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2283]
http://constitution.com/wow-decorated-hero-dropped-ft-riley-prayer-breakfast-christian/
'Paid content' to the right:
![screen shot 2016-06-07 at 11 34 43 pm](https://cloud.githubusercontent.com/assets/14153331/15873680/76b7c54e-2d08-11e6-84b1-945353e9819b.png)

**Comment by Alex-302** [comment]
Added
`constitution.com#%#var cv = function() {};`
Please check it.

**Comment by Bohdan-SUP** [comment]
Works fine. Is it in the filters already?
