### ISSUE TITLE
iceporn.com [NSFW] [Pop-up & Ad]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#22849]
**Site**: https://www.iceporn.com/video/2580960/jazmin-gets-a-big-raging-donger

**Issue**: Please remove the pop-up and the ad on the page.
 
**Screenshot**: http://prntscr.com/kxb3r6

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 69.0.3497.100 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.8 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Spam 404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by AdamWr** [comment]
I can't reproduce it, do you still see that ad?
