### ISSUE TITLE
mocospace.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2284]
www.mocospace.com
Username: adguard-testing
Password: adblocktest

![screen shot 2016-06-07 at 11 48 12 pm](https://cloud.githubusercontent.com/assets/14153331/15874140/899e5720-2d0a-11e6-8ac8-69e44bea34d0.png)

**Comment by Alex-302** [comment]
Fixed in English filter.
See the commit for filter changes.
