### ISSUE TITLE
"adtiming.com" seen in MIUI "System Launcher" [Android] [Ad]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#22855]
**App**: System Launcher (Built-in app)

**Package Name**: com.miui.home

**Issue**: Checking filtering log, I can see the Request URL for this system app as:

`https://img.adtiming.com/upload/creative/2018/08/17/fef49c3ad1d8e2bed142feef678255a3.png`

Note that the domain "adtiming.com" is a ad domain. Please add appropriate rule and also add this domain to the block list.

**Screenshot**: https://ibb.co/maJCp9

**Android Version**: 6.0.1 MMB29M

**MIUI Version**: MIUI Global 9.6 | Stable [9.6.2.0 (MHOMIFD)]

**AdGuard Version**: 2.12.223

**Filters**:
AdGuard Base Filter
Mobile Ads
Spyware
Social Media
Annoyances
EasyList China

**AdGuard Settings**:
Allow search ads & self-promotion: Disabled
Block ads in all apps: Enabled
Phishing and malware protection: Enabled
HTTPS Filtering: Enabled
Proxy Settings: Off
Filtering Method: High quality
Filtering Mode: Local VPN

**Comment by Alex-302** [comment]
I need HAR file.
