### ISSUE TITLE
tomodachinocrew.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2286]
http://www.tomodachinocrew.net/ao-haru-ride/
TZZ-740-50007, works fine on my side
![image2](https://cloud.githubusercontent.com/assets/14153331/15881475/ff542402-2d3e-11e6-914b-001834a6287d.PNG)
![image1](https://cloud.githubusercontent.com/assets/14153331/15881474/ff537d90-2d3e-11e6-9bc0-f6768b741a66.PNG)

**Comment by Alex-302** [comment]
Can't reproduce.
