### ISSUE TITLE
9to5mac.com missed ad on frontpage

### ISSUE THREAD

**Issue by tiberian83** [AdguardTeam/AdguardFilters#2288]
Missed ad on frontpage with Safari iOS (I haven't tested other systems).
![image](https://cloud.githubusercontent.com/assets/10312300/15903856/149dce06-2daf-11e6-984d-c4899d976765.png)

**Comment by Alex-302** [comment]
It is clean on my end

**Comment by tiberian83** [comment]
It's fine on my side again too. Maybe it was fixed in another filter in the meantime.

**Comment by Alex-302** [comment]
Maybe)

**Comment by Bohdan-SUP** [comment]
Reproduced with US IP and default filters:
![image](https://cloud.githubusercontent.com/assets/14153331/18413898/b2f4954e-77bf-11e6-8209-52e8a9f16e72.png)

**Comment by Bohdan-SUP** [comment]
@Alex-302 please check this one.

**Comment by Alex-302** [comment]
Still can't reproduce. I need  remote access.

**Comment by osavranska** [comment]
Again 9to5Mac is not working properly with DNS activated. 
First the welcome page is strange. 
- some picture holders are either black (missing) or white. 
- when reading the news some ads are still persistent. 

Logs attached in the ticket. 

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21804349/31237756-d737-11e6-8f1e-956c7aea3259.png)

</details>

<details>

![image2](https://cloud.githubusercontent.com/assets/23258533/21804359/4744aef6-d737-11e6-88b5-5e2fcf732ed4.png)

</details>

<details>

![image3](https://cloud.githubusercontent.com/assets/23258533/21804375/5df5a268-d737-11e6-98f4-3d4355d42120.png)

</details>

<details>

Application version: 1.1.4.36
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: D8C68A2E-052A-4588-A77A-CBB66B4E48CF

Locale: en
Region: fr

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.15 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.1 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.54 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.41 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.4 Enabled=YES
ID=101 Name="EasyList" Version=1.0.66.42 Enabled=YES
ID=113 Name="Liste FR" Version=1.0.72.50 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.72 Enabled=YES
ID=229 Name="I dont care about cookies" Version=1.0.0.11 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.68 Enabled=YES

</details>

Ticket's ID: 1021351

**Comment by Alex-302** [comment]
try to disable
```
ID=101 Name="EasyList" Version=1.0.66.42 Enabled=YES - is unnecessary when English filter is enabled
ID=113 Name="Liste FR" Version=1.0.72.50 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.72 Enabled=YES
ID=229 Name="I dont care about cookies" Version=1.0.0.11 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.68 Enabled=YES
```

**Comment by Bubu92** [comment]
By the way, there is still persistent issue on the 9to5Mac iOS application.

**Comment by Alex-302** [comment]
@osavranska 


> Again 9to5Mac is not working properly with DNS activated.
> First the welcome page is strange.
> 
> some picture holders are either black (missing) or white.
> when reading the news some ads are still persistent.

is it caused by filters or by DNS?

**Comment by Bubu92** [comment]
On my side with or without the DNS the issue is still persistent.  Attached a screen shot without DNS. 
![img_0779](https://cloud.githubusercontent.com/assets/23118229/21881902/8191d026-d8a8-11e6-9a2d-7e95bd9b3cf0.PNG)

**Comment by Alex-302** [comment]
Ok. Show me screenshot without Adguard.
Which filter causes it?

**Comment by Bubu92** [comment]
Can't you download the app and try on your end? 
How do you want me to know which filter causes the problem? 
Can't the logs help you to identify the issue?

**Comment by osavranska** [comment]
https://qcrm.supportyourapp.com/#/customer/1486177

I’d really just like a refund. I’m not satisfied with the product and I
don’t want to put in anymore time into figuring out what the problem was.

Информация о ключе: YXD48NR4

Order IDSystem Order IDСистемаВремя покупкиПериодСуммаСтатусТипEmail
РеквизитыСкидка
1713724 100853076 BLUESNAP 2017-01-09 16:25 365 921,81 руб. SUCCESS Покупка
terrencewells47@gmail.com

**Comment by Alex-302** [comment]
@Bubu92 you are not topic starter, so I need more details from you.

**Comment by Bubu92** [comment]
What do you mean? I am the one who reported the issue and sent all the data and logs.

**Comment by Alex-302** [comment]
Ok)

> some picture holders are either black (missing) or white.

some images are not loaded without Adguard.

**Comment by Bubu92** [comment]
Yes like the screen shots I sent.

**Comment by Alex-302** [comment]
It is not caused by Adguard.

**Comment by dzamyshlyayeva** [comment]
ads on page https://9to5mac.com/page/2/

![image](https://cloud.githubusercontent.com/assets/23372054/23580178/3d7a7db8-0105-11e7-832c-b2a190f734ea.png)

Customer ID 1453264

**Comment by Bubu92** [comment]
Clever website because even when blocking the ad it comes back again and again.

On 4 Mar 2017, at 17:07, dzamyshlyayeva <notifications@github.com> wrote:

ads on page https://9to5mac.com/page/2/ <https://9to5mac.com/page/2/>
 <https://cloud.githubusercontent.com/assets/23372054/23580178/3d7a7db8-0105-11e7-832c-b2a190f734ea.png>
Customer ID 1453264

**Comment by Alex-302** [comment]
Added to English filter
```
9to5mac.com##.leaderboard
9to5mac.com##.post-content > div.fallback-unit.river-unit

```

**Comment by Bubu92** [comment]
Did you try it? Before it does seem working. See screen shots. 





On 5 Mar 2017, at 12:20, Alex <notifications@github.com> wrote:

Added to English filter

9to5mac.com##.leaderboard
9to5mac.com##.post-content > div.fallback-unit.river-unit

**Comment by Alex-302** [comment]
Yes. They are working.

**Comment by Bubu92** [comment]
Then why do I still have the ads (cf. Previous email)?

On 5 Mar 2017, at 12:48, Alex <notifications@github.com> wrote:

Yes. They are working.

**Comment by Alex-302** [comment]
Because they are not in the filter yet.

**Comment by Bubu92** [comment]
OK.  Just confused because you said "added" ;-)

On 5 Mar 2017, at 13:04, Alex <notifications@github.com> wrote:

Because they are not in the filter yet.
