### ISSUE TITLE
[Annoyance] www.haaretz.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2290]
![image](https://cloud.githubusercontent.com/assets/15856304/15911598/3454e980-2dd9-11e6-8f1d-a68599792bf1.png)
![image](https://cloud.githubusercontent.com/assets/15856304/15911608/3bec9044-2dd9-11e6-9318-c981bb761c8d.png)

http://www.haaretz.com/israel-news/1.723941

**Comment by Alex-302** [comment]
added
haaretz.com##body > div.footer-ruler
###trd-exitintentbox
||trendemon.com^$third-party
