### ISSUE TITLE
Яндекс.Музыка

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2291]
https://music.yandex.ru/

Необходимо авторизоваться в Яндекс.Почте, а затем появится такая картинка:
![screen3](https://cloud.githubusercontent.com/assets/18548949/15920616/db6ba8f4-2e23-11e6-987e-cbaa4e1c56aa.jpg)

ниже по странице, при нажатии на исполнителя музыки:
![screen2](https://cloud.githubusercontent.com/assets/18548949/15920615/db6a8be0-2e23-11e6-8366-b731b2f0648a.jpg)

Ситуация в Яндекс браузере и в IE 11.
У меня не повторяется.

**Comment by Alex-302** [comment]
Похоже Адгард или не работает, или HTTPS не фильтрует. У него ж прога, надеюсь?

**Comment by Serzh-SUP** [comment]
@Alex-302 
У него прога .

**Comment by Alex-302** [comment]
Проверить бы что с подменой сертификата. Можно нажать на замок в адресной строке и посмотреть на название серта.

**Comment by vgavrish** [comment]
@Alex-302 

вот все скрины:)
http://prntscr.com/bf05o3
http://prntscr.com/bf05qp
http://prntscr.com/bf05tr
http://prntscr.com/bf05w5
http://prntscr.com/bf05xl

если что фильтры:
http://prntscr.com/bf06ap

**Comment by Alex-302** [comment]
Добавил
||music.yandex.ru/handlers/*/resource/context_static_r*.js

**Comment by vozersky** [comment]
Снова вылез директ.

**Comment by Alex-302** [comment]
Не повторяется.

**Comment by vozersky** [comment]
Снова вылез директ, повторил на маке в хроме со стандартным набором фильтров.

![screen shot 2016-08-12 at 17 21 13](https://cloud.githubusercontent.com/assets/17472907/17625363/3e36e880-60b1-11e6-8014-2d83019524bf.png)

С виндой юзеры тоже репортят (расширение для хрома):

![original 1](https://cloud.githubusercontent.com/assets/17472907/17625406/71b07442-60b1-11e6-9df7-00ce522d5e74.jpg)

**Comment by Alex-302** [comment]
Нужно удалённо смотреть. Меня на российский домен не пускает.

**Comment by evgeniy-ADG** [comment]
Вот еще репорт. У меня с моим ИП не повторилось.

https://music.yandex.ru/feed

iOS, Adguard Pro

<details>
Application version: 1.1.2.24
Application lifetime: 2016-10-02 16:38:25 +0000

Device: iPad
Platform: iOS
OS: 10.1
ID: 28730513-B2C7-4981-9000-FC0ADB257B74

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.98.44 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.44 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.93 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.65 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.41.70 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.34 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.55 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.67.82 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.67.83 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.64.68 Enabled=YES
</details>

![image1 2](https://cloud.githubusercontent.com/assets/15856304/19681513/56fe62a4-9ab2-11e6-86ec-b2b66dcac475.png)

**Comment by Alex-302** [comment]
Много фильтров, качество фильтрации может упасть из-за лимита в 50000 правил.
Сообщение о блокировке с фильтрацией ДНС не убрать.

**Comment by vgavrish** [comment]
1437985
тут по music.yandex.ru
передали такое правило 
```
<details>
music.yandex.ru#%#document.addEventListener("DOMContentLoaded", function(){document.querySelector('.sidebar__placeholder').remove();document.querySelector('.centerblock-wrapper').style.width = '100%';})
</details>
```
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19765387/c886e834-9c50-11e6-8974-37f784756095.png)

**Comment by Alex-302** [comment]
Лучше удалённо глянуть, а то даже с прокси на домен RU не могу зайти. Правило может рабочее, но хотелось бы на код взглянуть.

**Comment by vgavrish** [comment]
написала

**Comment by evgeniy-ADG** [comment]
> Отключил лишние фильтры. Все равно реклама проскакивает. Правило не могу добавить. При нажатии кнопки " готово" приложение вылетает.

1105133

**Comment by Alex-302** [comment]
На iOS оно и не будет работать. Там только сокрытие и блокировка адресов работает. А это правило - JS.

**Comment by evgeniy-ADG** [comment]
А, так что, не скрыть совсем?
