### ISSUE TITLE
[iOS] Missed Ads - yandex.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2292]
Фильтры базовые, обновленные. Иногда повторяется, иногда нет.
Например зашел на yandex, рекламы нет, перешел в "новости", там яндекс.директ, вернулся назад к поисковику, появилась реклама, как на скрине кастомера:
![img_4064](https://cloud.githubusercontent.com/assets/16462533/15922391/05418322-2e30-11e6-8f1b-e7207ad65af6.PNG)

Далее, если нажимать обновление стр. то появляется, то не появляется.

**Comment by Alex-302** [comment]
Не знаю как помочь. У меня такой рекламы нет даже без Адгарда. У тебя повторяется?

**Comment by vozersky** [comment]
а что такое "базовые" фильтры? :)

**Comment by Serzh-SUP** [comment]
@Alex-302 
Да, у меня повторяется, как описал, обновил - пропал баннер, снова обновил - появился..
![img_9497](https://cloud.githubusercontent.com/assets/16462533/15986623/d9b434b6-3014-11e6-95cc-c6adca09af37.PNG)


@vozersky 
Базовые, в смысле, фильтры Adguard

![img_9498](https://cloud.githubusercontent.com/assets/16462533/15986632/fa6d8a2c-3014-11e6-997e-3a8f9f3ee4a6.PNG)

**Comment by Alex-302** [comment]
@Serzh-SUP 
странно это всё. Мне сейчас не на чем проверять. Можешь в иосном разделе спросить на этот счёт? Может особенности какие есть.
