### ISSUE TITLE
missing advertising

### ISSUE THREAD

**Issue by unknowtech** [AdguardTeam/AdguardFilters#22932]
for Adguard Simplified domain name filter

||fuckdate.club
||ok.clickvite.xyz

**Comment by Alex-302** [comment]
I need the source.

**Comment by unknowtech** [comment]
to reading on different players on streaming sites 

https://www3.voirfilms.ws/ 
https://www1.papstream.xyz/

**Comment by Alex-302** [comment]
I don't see these requests. Could you, please upload HAR file or saved pages?
