### ISSUE TITLE
Яндекс.Директ

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2293]
Блокирование содержимого расширения Яндекс.Директ в браузере Яндекс.
Повторяется. Помогает отключение Русского фильтра.

Действия:
1. Открыть Яндекс Браузер
2. Войти под своим логином
3. Выбрать настройки Яндекс - http://prntscr.com/bdt7at
4. Добавить виджет - http://prntscr.com/bdt7uo
5. Выбираем Яндекс Метрику и Яндекс Директ и сохраняем
6. Получаем - http://prntscr.com/bdt8ni и сохраняем
7. Рабочий стол выглядит так: http://prntscr.com/bdt90m

**Comment by Alex-302** [comment]
У меня вот так выглядит с русским фильтром и фильтром аналитики
http://imagizer.imageshack.com/img924/9301/mauW0C.png

**Comment by vgavrish** [comment]
У меня до сих пор вот так: http://prntscr.com/be8wyo

**Comment by Alex-302** [comment]
А рекламные компании есть? У меня какая-то тестовая есть.
Сделай плиз скрины с/без русского фильтра

**Comment by vgavrish** [comment]
@Alex-302 
нету
http://prntscr.com/bekzt2
http://prntscr.com/bel01q

**Comment by Alex-302** [comment]
Добавил в русский фильтр
direct.yandex.ru#@#.b-direct
