### ISSUE TITLE
http://m.au.ign.com - can't load video

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2294]
Unable to load video whilst ad blocker is on. 

Incorrect blocking on page:
http://m.au.ign.com/articles/2016/06/07/world-of-final-fantasy-release-date-announced

![image](https://cloud.githubusercontent.com/assets/15856304/15924327/3071a39c-2e3a-11e6-801e-332d4e39080f.png)

**Comment by evgeniy-ADG** [comment]
Loads fine at my end but the preload icon still appear. All new filers, basic set. Disabling
ID=207 Name="Adblock Warning Removal List" Version=1.0.59.49 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
doesn't help.

**Comment by Alex-302** [comment]
This player is not working on my end, even with disabled Adguard and with Australian VPN.
Please ask for disabling all filters and enable them one-by-one with checking.

**Comment by evgeniy-ADG** [comment]
у меня работает... =\ у тебя на маке?

**Comment by Alex-302** [comment]
Вот так он работает без Адгарда
<details>
![image](http://imagizer.imageshack.com/img921/9251/aRIELS.png)
</details>

**Comment by Alex-302** [comment]
Added to mobile filter
`@@||imasdk.googleapis.com/js/core/bridge*.html$domain=m.au.ign.com`
