### ISSUE TITLE
jumor.temaretik.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2295]
http://jumor.temaretik.com/907273492857358684/shutki-ot-okroshki/?utm_source=post-page&utm_medium=postlist&utm_campaign=post-2015120203

При переходе по ссылке или же по страницам сайта, появляется такое сообщение:
http://prntscr.com/be7r5h
http://prntscr.com/be7rcy

Фильтр раздражителей включен. У меня повторяется.

**Comment by Alex-302** [comment]
added to Annoyances
temaretik.com##div[ng-if="$root.joinGuest"]
