### ISSUE TITLE
oldi.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#22957]
[https://spb.oldi.ru/catalog/6869/?arFilter_[P_1748][0]=5050&arFilter_[P_21624][0]=1282980&arFilter_[P_21624][1]=1264914&arFilter_[P_21624][2]=1335555](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fspb.oldi.ru%2Fcatalog%2F6869%2F%3FarFilter_%5BP_1748%5D%5B0%5D%3D5050%26arFilter_%5BP_21624%5D%5B0%5D%3D1282980%26arFilter_%5BP_21624%5D%5B1%5D%3D1264914%26arFilter_%5BP_21624%5D%5B2%5D%3D1335555)

 Баннер-самореклама занимающий место в списке товаров. Рекламируемые акции и скидки дублируются возле каждого товара, относящегося к этим акциям и скидкам (на рис. отмечено стрелками): `oldi.ru##.mainbanner`

<details><summary>Screenshot:</summary>

![2018 09 24-7](https://user-images.githubusercontent.com/17948007/45974719-d779d980-c04a-11e8-8fca-3ffc0b9420a3.png)
</details>

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v2.10.11
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Да в магазинах вообще не вижу смысла это блокировать.
