### ISSUE TITLE
Антиадблок на сайте tapochek.net

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#22967]
При входе на http://tapochek.net/index.php и любую из его страниц, антиадблок ломает дизайн сайта и выскакивает сообщение с требованием отключить блокиратор рекламы.
Скрипт в base64

**Comment by Alex-302** [comment]
Наши фильтры не ломают.

**Comment by Alex-302** [comment]
Заблокировал рекламу.

**Comment by Smorvel** [comment]
@Alex-302 проверил, да из за RU Adlist так что это исправлено не будет?

**Comment by Alex-302** [comment]
Два русских фильтра лучше не использовать. RU Adlist в некоторых ситуациях полагается на JS Fixes.
