### ISSUE TITLE
familytreedna.com - false blocking, can't log in

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2296]
Hi - I'm trying to access a site FamilyTreeDNA and it comes up that a
filter is blocking it. I've looked but I can't seem to find where I
can add this to an exclusion list or something. The address is
https://www.familytreedna.com/login.aspx?utm_campaign=website&utm_source=sendgrid.com&utm_medium=email
Thank you. Tom Norfleet

**Comment by Alex-302** [comment]
I can't too, because can't register)
Please ask for test account.

**Comment by evgeniy-ADG** [comment]
me: Please go to Settings -> General settings, scroll the page down and open Manage HTTPS exclusions. Click "+" and add familytreedna.com to this list of exceptions. Save and reload the page in a browser by pressing Ctrl+F5.

user: It works!!! Thank you.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
зачем? Если каждый сайт с проблемами будем исключать, качество продукта упадёт.
Попроси удалить исключение и проверить по отдельности - без антитрекинга(если включен, то какие опции), без фильтров(фильтрация при этом должна быть включена). И нужен скрин ошибки.
Если проблема из-за фильтров, попроси список. И желательно заиметь аккаунт.
