### ISSUE TITLE
AdGuard blocks notifications from Badoo

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#22971]
> При включении wi-fi уведомления не показываются. Потом, когда сам запускаю приложения, вижу, что есть непрочитанные письма или сообщения. И уже при поступлении новых сообщений и писем после того, как интернет включен и я вручную открывал приложения, уведомления приходят. Также они сразу поступают, как только перезапускается защита AdGuard. 

### Steps to reproduce

1. Install Badoo v.5.82.2
2. Use the app and collect some notifications in the background
3. Pause AdGuard

### Expected behavior

You get notifications on step 2

### Actual behavior

There are no notifications on step 2; on step 3, notifications start to arrive in bulk

### Customer ID 
1604579 w/ logs and timestampts

### Your environment

* Adguard version: 2.12.223
* Adguard filtering mode: VPN
* Filters: "AdGuard Base filter", "AdGuard Mobile Ads filter", "AdGuard Russian filter"
* HTTPS filtering: on, the default mode
* DNS: false
* Device model: SM-G920P
* Operating system and version: 7.0
* Rooted or not? no
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by Eugene-Savenko** [comment]
Пользователь удалил программу (нашу) и не можем ответить на вопрос.

**Comment by Alex-302** [comment]
Пичаль.
