### ISSUE TITLE
http://xserver.a-real.ru/ - incorect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2297]
http://xserver.a-real.ru/
![image](https://cloud.githubusercontent.com/assets/15856304/15927068/267fc680-2e48-11e6-9e20-4d09414e2d4d.png)

+ add the chat to the annoyance

**Comment by Alex-302** [comment]
Added to Russian
@@||xserver.a-real.ru.images.1c-bitrix-cdn.ru/bitrix/templates/xserver_main/images/adv_
to Annoyances
||livetex.ru^$third-party
