### ISSUE TITLE
admitad - does not allow to go through links

### ISSUE THREAD

**Issue by Alexey71** [AdguardTeam/AdguardFilters#2298]
Не даёт переходить по ссылке например http://fas.st/PBR_u
![screenshot_20160610-113829](https://cloud.githubusercontent.com/assets/10572914/15958722/e039537c-2eff-11e6-89be-6eaec9415043.png)

**Comment by ameshkov** [comment]
@Alex-302 по ходу из-за $empty в мобильном фильтре

**Comment by Alex-302** [comment]
@ameshkov из-за него.
Добавил в мобильный фильтр:
```
@@||ad.admitad.com/*/?ulp=
```

**Comment by Alex-302** [comment]
А как $empty в iOS обрабатывается?
