### ISSUE TITLE
Adguard Assistent 

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2299]
# **Не появляется на epidemz.com**

![2016 06 09_00h56m39s_003_](https://cloud.githubusercontent.com/assets/16462533/15961647/7d20b690-2f0e-11e6-979b-fdcb2bd94769.jpg)

**Comment by Alex-302** [comment]
открыл баг
https://github.com/AdguardTeam/AdguardForWindows/issues/1126
перед кодом HTML мусор, и чтоб не сломать страницу Адгард в таких случаях не инжектится
