### ISSUE TITLE
Can't subscribe to newspapers http://www.adelaidenow.com.au/login

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2300]
I have not been able to activate my subscription to
Digital Newspaper. The date shows but there is no picture or graphic
to click on. If I switch A Guard off then everything works fine. I
presume there is a setting that I should attend to to prevent this
from happening. Are you able to assist please? Below is the web site
involved and I am using Windows 7 Home Edition and Explorer 11.
Digital Pass Login | The Advertiser
http://www.adelaidenow.com.au/login

Please see the screenshots here: 1083371

**Comment by Alex-302** [comment]
I can't fix it without account, but it is not free. Also I need a direct url to broken pages

**Comment by evgeniy-ADG** [comment]
@Alex-302 please check HTML page and login/pass in the ticket (a few latest messages): 1083371
If possible, try to help asap, it's been a while since we received the ticked.

**Comment by Alex-302** [comment]
Logged in successfully. 
I need step-by-step description with screenshots.
