### ISSUE TITLE
Google ads go througs, can't open the ads 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2302]
The Google app is still showing ads. When I click on them, I get an
error in Chrome: can't load www.googleadservices.com
![image](https://cloud.githubusercontent.com/assets/15856304/15964905/83738094-2f23-11e6-9f1f-3f5feba907d7.png)

![image](https://cloud.githubusercontent.com/assets/15856304/15964856/49f8e9f8-2f23-11e6-8600-719d0cc6636b.png)

It happens both with "Show useful ads" on and off.
The ad shows up in the Google ad, but clicking it doesn't load the webpage.
Ads should be blocked in the Google app or they should be usable - looks
more logic to me.

Ticket 1157037

**Comment by Alex-302** [comment]
It works fine on my end. Maybe DNS filtering is enabled. I can't find this ticket

**Comment by Alex-302** [comment]
But maybe we can do something
https://github.com/AdguardTeam/AdguardForAndroid/issues/632

**Comment by evgeniy-ADG** [comment]
> useful ads that utilize www.googleleadservices.com that appear after a
> Google search from the search bar in the Google Now Launcher gives an
> HTTP 500 error, even though www.googleleadservices.com is in the
> whitelist. Disabling Adguard restores functionality.

1015150, asked for details

**Comment by Alex-302** [comment]
@evgeniy-ADG в 1015150 сообщения за апрель прошлого года и не по теме.
Ты можешь у себя повторить эте проблему?

**Comment by evgeniy-ADG** [comment]
Нет, у меня не повторяется. Значит, не тот номер указал, найду и исправлю

**Comment by evgeniy-ADG** [comment]
Нашел.
> DNS filtering was never enabled.1299165

**Comment by Alex-302** [comment]
А теперь нужен лог HTTP запросов.

**Comment by Alex-302** [comment]
Только объясни ему, вдруг не знает как.
