### ISSUE TITLE
missed ad rustorka.com

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2305]
**Повторилось, на сайте пропущена реклама. Фильтры Adguard, обновленные.
Более того, помощник не открывается при нажатии на него, просто пропадает, также, повторилось!**

> Скрин пользователя:

![2016 06 10_17h31m03s_001_](https://cloud.githubusercontent.com/assets/16462533/15986670/d82306d0-3015-11e6-8d49-02ceb1630107.jpg)

**Comment by Alex-302** [comment]
добавил
rustorka.com##div[id^="b"][align="center"][style="display: block;"]

**Comment by vgavrish** [comment]
http://rustorka.com/forum/viewtopic.php?t=203894
http://prntscr.com/bi7fmw
http://prntscr.com/bi7fpl

Также на главной:
http://rustorka.com/forum/index.php
http://prntscr.com/bi7fx4

**Comment by vgavrish** [comment]
Андроид. Фильтры обновлены.
http://rustorka.com/forum/index.php
http://prntscr.com/bnsxwe
http://prntscr.com/bnsxr8

**Comment by vgavrish** [comment]
Расширение для Оперы
http://rustorka.com/forum/
Скрины:
http://prntscr.com/bpdinz
http://prntscr.com/bpdive

**Comment by Alex-302** [comment]
Да нет смысла уже переоткрывать. Он несколько раз в день меняет код баннера. Обновления всё равно не успевают доехать.

**Comment by Alex-302** [comment]
Вот о ложных нужнно сразу сообщать.

**Comment by vgavrish** [comment]
там снова реклама в двух блоках
http://ssmaker.ru/f216c22e/
http://ssmaker.ru/5a05b7f8

**Comment by ameshkov** [comment]
@Alex-302 вот это предлагаю:
```
rustorka.com###page_header+div[id]>[id]>a
rustorka.com###sidebar1-wrap>h3:first-child
rustorka.com###sidebar1-wrap>div[id]
/http://rustorka.com/forum/[a-z]+.js/$domain=rustorka.com
```

**Comment by Alex-302** [comment]
jQuery is blocked by regexp. Excluded them
```
@@||rustorka.com/forum/misc/js/*.js
```

**Comment by vgavrish** [comment]
снова реклама появилась
http://prntscr.com/c5htln

**Comment by Alex-302** [comment]
Она каждый день появляется)
