### ISSUE TITLE
translate.google.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2307]
В браузере Firefox, Opera и IE 11 пустое пространство
![428b8afb65f44068988b3820a540e347](https://cloud.githubusercontent.com/assets/18548949/15990004/011db352-3091-11e6-989c-926f94a85e10.png)

"В фильтре раздражителей сейчас есть правило для блокировки пустого пространства на сайте google.translate (оно появляется после блокировки рекламы). Выглядит оно так: translate.google.ru,translate.google.com#$#.gb_7c#gba { height: 60px!important; }. 
В нем нужно заменить gb_7c на gb_8c, чтобы было так: translate.google.ru,translate.google.com#$#.gb_8c#gba { height: 60px!important; }. 
Просто то правило что с 7-кой не работает а то что с 8-кой работает, уже проверил... Видимо гугл код на странице поменяли..."

**Comment by Alex-302** [comment]
Заменил.
