### ISSUE TITLE
zona.mobi annoyance

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2308]
Source report:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=50340146
Reproduced on my side.
![image](https://cloud.githubusercontent.com/assets/14153331/15990680/6cbc23de-30a3-11e6-8f10-7aa948e03d94.png)

**Comment by Alex-302** [comment]
zona.mobi###zona-android
