### ISSUE TITLE
alluc.ee - Unblockable ads?

### ISSUE THREAD

**Issue by tbcam88** [AdguardTeam/AdguardFilters#2309]
My Adguard extension (Chrome) blocks the majority of pop-ups but there are some instances where it doesn't manage to do so.

http://www.alluc.ee/l/breaking-bad-s05e01-brrip-sujaidr/d6bv1b3g

This being an example. A new tab pop-up will open every time I go to click play.

Is there a fix for this?

**Comment by Alex-302** [comment]
I don't see player, even without Adguard
http://imagizer.imageshack.com/img922/9863/r2FVGN.png
Please make a screenshot

**Comment by tbcam88** [comment]
Alex,

The screen you posted shows a different URL from the link I specified above...

Try the address I originally posted?

**Comment by Alex-302** [comment]
Tried. Now I see it.
Added to English filter
vidzi.tv##div[class$="vidzi_backscreen"]

**Comment by tbcam88** [comment]
Well done Alex, you're a champ!

I come across situations like this quite frequently, should I post them here so the filters can be updated? Or could you perhaps talk me through how you identified/corrected the issue and I can do it myself in future?


Thanks!

**Comment by Alex-302** [comment]
When the rules was added to filters, they will be available in updates after after half an hour.

**Comment by Alex-302** [comment]
@tbcam88 
please check this rule if Safari

**Comment by Alex-302** [comment]
##div[class$="vidzi_backscreen"]

**Comment by tbcam88** [comment]
What about this one, Alex?

[https://psarips.com/tv-show/game-thrones-season-6/](url)

I sometimes experience ads while expanding the columns (highlighted red below). Are you able to reproduce this?

![untitled](https://cloud.githubusercontent.com/assets/19891537/16364620/a86faa86-3be3-11e6-9a28-b70004288a4d.png)

**Comment by Alex-302** [comment]
No, I can't reproduce.

**Comment by tbcam88** [comment]
http://www.alluc.ee/l/Breaking-Bad-S04E02-DVDRip-XviD-SAiNTS-avi/fo0iw4ci

Another filter needed Alex... Could you perhaps explain how to do this so I can fix them myself in future?

Thanks!

**Comment by Alex-302** [comment]
Do you mean a popup?
Try this rule:
```
flashx.tv#%#window.btoa = function() { };
```

**Comment by tbcam88** [comment]
Yeah, that worked! Is there a tutorial anywhere on how you construct these rules? I come across pop-ups that slip past AdGuard quite often and would like to know how to fight them!

**Comment by Alex-302** [comment]
https://adguard.com/en/filterrules.html
The rule is added.

**Comment by tbcam88** [comment]
Unable to get rid of the ad highlighted below... In the past, Adblock has been able to remove it via right click. Any ideas?

![untitled](https://cloud.githubusercontent.com/assets/19891537/17085870/55381598-51db-11e6-8398-691eb4da4c88.png)

**Comment by Alex-302** [comment]
Please open new issue for other sites.
Try to enable annoyances filter.

**Comment by tbcam88** [comment]
Hi Alex,


It's the Adguard Chrome Extension I'm using, I'm not sure if adding filters is possible in this version. Okay, I'll open new thread. :+1:

**Comment by tbcam88** [comment]
https://biqle.ru/watch/-8722610_456249763

Can AdGuard block the pop-ups on this vid? 😃

**Comment by tbcam88** [comment]
![untitled](https://user-images.githubusercontent.com/19891537/44928040-78c48700-ad4e-11e8-8bb6-1f77c95db9fa.png)
Elements highlighted in red keep reappearing upon page refresh after blocking... please assist!
