### ISSUE TITLE
News.Google.com Loads & then blanks out

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardFilters#2310]
I presume this should be classified under <kbd>[Anti-Adblock](https://github.com/AdguardTeam/AdguardFilters/issues?q=ilabel%3A%22Anti+Adblock+Script%22)</kbd>:

https://News.Google.Com loads fine until the last moment, then blanks out except for the header.  This is under Adblock Android [2.6.101 ß/RC](https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v2.6.101) proxy, not premium nor HTTPS filtering, with AG English,  Spyware, Social Media, Experimental, Annoyances, Mobile Ads, & @reek's [AAK](https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer-filters.txt) filters.

**Comment by Alex-302** [comment]
Very strange. This domain use HTTPS, and can't be filtered without enabled HTTPS filtering.
Please make a screenshot, and try without any filters.
