### ISSUE TITLE
ru-board.com

### ISSUE THREAD

**Issue by a-ladanov** [AdguardTeam/AdguardFilters#2311]
Браузер не догружает страницу до конца, если Adguard включен.
http://forum.ru-board.com/misc.cgi?action=printtopic&forum=62&topic=24100
Проверить, загрузилась ли страница, можно только прокрутив ее до конца и посмотрев на даты постов (значок загрузки страницы не показатель)
Фильтры: eng,rus,social,counters
Браузер chrome

**Comment by Alex-302** [comment]
какая версия Адгарда?
Проверьте такое правило
@@||forum.ru-board.com/misc.cgi?action=printtopic$content

**Comment by a-ladanov** [comment]
Версия 6.0.226.1108
Правило помогает. Перепроверил три раза

**Comment by Alex-302** [comment]
Ок, добавил.
