### ISSUE TITLE
SafeSurf

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2312]
Программа для автосёрфинга SafeSurf в проекте JetSwap.
При включённой защите сайты показываются, но показы не засчитываются:
http://prntscr.com/bfr221

При отключении Антибаннера, проблема исчезает и просмотры сайтов засчитываются:
http://prntscr.com/bfr2p8

фильтры: http://prntscr.com/bfr3lp

логин: EgorGamov
пароль: Iwzk#Zn!8u
сама программа тут:
https://yadi.sk/d/iVsQW_J8sRDVR

**Comment by Alex-302** [comment]
Думается что они по запросам смотрят и определяют блокировку. Лучше не фильтровать её, вот и решение.

**Comment by vgavrish** [comment]
ну а так, реклама получается на страницах
