### ISSUE TITLE
Директ mail.ru

### ISSUE THREAD

**Issue by Hawkrus** [AdguardTeam/AdguardFilters#2313]
https://auto.mail.ru/
![screenshot_2016-06-13-11-56-31](https://cloud.githubusercontent.com/assets/19652388/16002055/3ade0ee8-315e-11e6-899c-21fe4fdac4a8.png)

**Comment by Alex-302** [comment]
Какая версия расширения?

**Comment by Alex-302** [comment]
Да стразу все домены с рекламой напишите, сделаем универсально) Там правило не очень хорошее, его лучше точечно применять.

**Comment by Hawkrus** [comment]
https://auto.mail.ru/
https://horo.mail.ru/
https://realty.mail.ru/
https://health.mail.ru/
https://afisha.mail.ru/
https://cloud.mail.ru/
https://otvet.mail.ru/
https://pogoda.mail.ru/
https://sport.mail.ru/
https://tv.mail.ru/
http://torg.mail.ru/
https://cars.mail.ru/

**Comment by Alex-302** [comment]
добавил эти домены в правило

**Comment by vgavrish** [comment]
https://otvet.mail.ru/question/195542738
Реклама от розетки: http://prntscr.com/d7181v
ФФ
Фильтры: 1,2,3,4,14,211

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||otvet.mail.ru^$generichide
```

**Comment by vgavrish** [comment]
Директ otvet.mail.ru
ФФ
Фильтры: 1,2,3,4,14,211
http://prntscr.com/dkufad

**Comment by Alex-302** [comment]
Пусть попробует оставить только рус и англ. У меня чисто.

**Comment by Yana-SUP** [comment]
**1464550** отписал, не помогло

**Comment by Alex-302** [comment]
Может другие блокировщики есть? У тебя повторяется?

**Comment by vgavrish** [comment]
вроде бы нет. у меня не повторяется

**Comment by vgavrish** [comment]
антивир откл, пользовательский откл и появляется баннер 

![image](https://cloud.githubusercontent.com/assets/18548949/21541917/f6534e58-cdc2-11e6-8631-469e605cc2ab.png)

**Comment by Alex-302** [comment]
Пользовательский фильтр отключали? Можно удалённо глянуть.
