### ISSUE TITLE
Amazon Seller Central

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2314]
KYG-603-11705
"I see the text addition only when one of the filters "English", "Spyware" or "German" are enabled. I do not see them when all three are disabled. I do not see any effect of the other filters."
![adguard amazon](https://cloud.githubusercontent.com/assets/14153331/16008842/a91957e0-3182-11e6-83fc-e29cb2173549.jpg)

**Comment by evgeniy-ADG** [comment]
I should mention that this happens on Safari. Amazon seller central does not work on my machine with Opera (I get an Amazon page which returns an incompatible with browser error message). 

Here are the lines with each filter enabled individually (same with User filter enabled/disabled)
<details>
Spyware filter : 
a[href^="http://metrika.yandex.ru/stat/"], a[href^="http://www.liveinternet.ru/stat/"], a[href^="https://metrika.yandex.ru/stat/"], img[width="88"][height="31"] { display: none!important; }

German filter : 
#WerbungObenRechts8_GesamtDIV, #werbeleiste, #werbung, .WerbungLinksRechts, .firstload, .text_werbung, .werbung { display: none!important; }

English filter : 
embed[width="640"][height="160"], iframe[width="100%"][height="250"], iframe[width="100%"][height="60"], img[width="240"][height="400"], object[width="100"][height="100"], object[width="1000"][height="250"], object[width="1000"][height="270"], object[width="200"][height="200"], object[width="260"][height="130"], object[width="300"][height="60"], object[width="640"][height="100"], object[width="640"][height="160"], #ad_global_below_navbar, #DAnsm, .amsSparkleAdContainer, #DAadrp, #ad, #nav-swmslot, #raw-search-desktop-advertising-tower-1, .pa-sp-container, div[style="width:300px;height:280px;"], iframe[width="100%"][height="120"], object[width="300"][height="300"], #AD_Top, #AD_banner, #AdColumn, #AdContainer, #AdHeader, #AdImage, #Adcode, #AdvertiseFrame, #Advertisements, #BottomAdContainer, #BottomAds, #ContentAd, #PreRollAd, #RightAdBlock, #TopAd, #WNAd41, #ad-area, #ad-background, #ad-bg, #ad-bottom, #ad-container, #ad-header, #ad-header-728x90, #ad-leaderboard, #ad-main, #ad-panel, #ad-right, #ad-rotator, #ad-text, #ad-top, #ad-top-banner-placeholder, #ad-top-wrapper, #ad-unit, #ad-wrapper, #ad468, #ad728, #ad728x90, #adBanner, #adBelt, #adComponentWrapper, #adDiv, #adFrame, #adGallery, #adHeader, #adHolder, #adLayer, #adLeader, #adPosition0, #adText, #ad_1, #ad_2, #ad_3, #ad_4, #ad_5, #ad_728_90, #ad_area, #ad_banner, #ad_center, #ad_content, #ad_global_above_footer, #ad_header, #ad_leaderboard, #ad_main, #ad_overlay, #ad_space, #ad_square, #ad_table, #ad_topslot, #ad_unit, #ad_wrap, #ad_wrapper, #adaptv_ad_player_div, #adbackground, #adbanner, #adbar, #adblock, #adboard, #adbody, #adbox, #adcode, #adcontainer, #adcontainer1, #adcontent, #adhead, #adheader, #adimg1, #adlabel, #adlayer, #adnews, #adposition3, #adright, #ads-col, #ads-wrapper, #ads1, #adsHeader, #ads_bottom, #ads_right, #ads_top, #ads_wrapper, #adsdiv, #adsense, #adsense_block, #adsense_inline, #adsensewide, #adspace, #adspace_top, #adspot-300x250-pos-1, #adspot-300x250-pos-2, #adstop, #adtext, #adtop, #adv-masthead, #adv-top, #advert1, #advert2, #advertContainer, #advert_box, #advertbox3, #advertise, #advertisement1, #advertisetop, #advertising_wrapper, #adverts, #advtop, #adwrapper, #banner-ad, #bannerAd, #bannerAdWrapper, #banner_ad, #banner_topad, #bannerad, #bigAd, #bigad, #body_ad, #bottomAd, #bottomAds, #bottom_ad, #centerads, #cmn_ad_tag_head, #companionAd, #content-header-ad, #contentAd, #content_ads, #content_adv, #contentad, #dart-container-728x90, #dfp_ad_Entry_728x90, #dfp_ad_Home_728x90, #divAd, #div_prerollAd_1, #download_ad, #featuread, #featured-ads, #featuredAds, #footer_ad, #footer_ads, #game-ad, #googlead, #gridAdSidebar, #head-ad, #header-ads, #headerAd, #headerAdContainer, #header_ad, #homead, #ka_adRightSkyscraperWide, #leaderAd, #leaderBoardAd, #leaderboard-ad, #leaderboard-advertisement, #leaderboardad, #left-ad, #left_ads, #leftad, #leftads, #logoAd, #logo_ad, #mainAd, #main_ad, #mini-ad, #mpu2, #mpu2_container, #mpu_container, #msad, #myAd, #player_ads, #pre_advertising_wrapper, #prerollAd, #promo-ad, #publicidad, #reklama, #rh-ad, #rightAd, #right_ads, #right_adsense, #search-sponsor, #searchAd, #search_ads, #sideAd, #side_ads, #sidebar-ads, #sidebar_ad, #sidebar_ad_1, #sidebar_ads, #sky_advert, #skybox-ad, #sponsorAdDiv, #sponsorText, #sponsoredwellcontainerbottom, #sponsors-home, #takeover_ad, #top-ad, #top-ad-content, #topAd, #topAdSpace, #topAdSpace_div, #topAdvert, #topBannerAd, #top_ad, #top_ad_game, #top_ads, #topad, #topadvert, #topbannerad, #under_story_ad, #videoAd, #videoads, .ADBAR, .AdBody:not(body), .AdBox, .AdInfo, .AdSidebar { display: none!important; } .AdTitle, .AdvertContainer, .HomeAds, .IM_ad_unit, .LazyLoadAd, .RelatedAds, .SponsoredContent, .ad-300x250, .ad-970, .ad-banner, .ad-block, .ad-body, .ad-border, .ad-btn, .ad-button, .ad-cat, .ad-cell, .ad-display, .ad-enabled, .ad-header, .ad-holder, .ad-img, .ad-inner, .ad-item, .ad-leader-top, .ad-leaderboard, .ad-left, .ad-link, .ad-links, .ad-loaded, .ad-panel, .ad-placement, .ad-right, .ad-row, .ad-section, .ad-served, .ad-sidebar, .ad-source, .ad-square, .ad-stack, .ad-text, .ad-top, .ad-unit, .ad-unit-300-wrapper, .ad-vertical-container, .ad-wide, .ad-wrap, .ad-wrapper, .ad300, .ad468, .ad728, .ad90, .adBlock, .adBottomBoard, .adBox, .adChoicesLogo, .adContent, .adDiv, .adElement, .adFrame, .adFrameCnt, .adHead, .adHeader, .adHeaderblack, .adHeadline, .adHolder, .adHoldert, .adImg, .adItem, .adLink, .adMessage, .adMiddle, .adMod, .adModule, .adOverlay, .adPanel, .adPod, .adResult, .adRight, .adRotator, .adSpace, .adSpot, .adText, .adTitle, .adTopHome, .adWidget, .adWrap, .ad_1, .ad_160, .ad_160x600, .ad_2, .ad_3, .ad_728x90, .ad_960, .ad_Right, .ad_block, .ad_body, .ad_bottom, .ad_container, .ad_description, .ad_global_header, .ad_head_rectangle, .ad_header, .ad_img, .ad_item, .ad_leaderboard, .ad_middle, .ad_outer, .ad_promo, .ad_slug_table, .ad_space, .ad_spot, .ad_text, .ad_title, .ad_trick_header, .ad_trick_left, .ad_unit, .ad_wrap, .ad_wrapper, .adarea, .adbanner, .adbar, .adbottom, .adbutton, .adcolumn, .adcont, .addiv, .adframe, .adfree, .adheader, .adholder, .adinfo, .adkit, .adlink, .adlist, .admain, .admiddle, .adright, .adrow1, .adrow2, .ads-1, .ads-2, .ads-3, .ads-area, .ads-bg, .ads-col, .ads-header, .ads-holder, .ads-inline, .ads-item, .ads-right, .ads-section, .ads-title, .ads-top, .ads1, .adsBlock, .adsWidget, .ads_catDiv, .ads_div, .ads_top, .ads_wrapper, .adsbottombox, .adsbox, .adsbygoogle, .adscontainer, .adshome, .adside, .adslot, .adslot_blurred, .adspace, .adtable, .adtile, .adtop, .adv300, .adv_300, .advert-block, .advert-box, .advert-container, .advert-content, .advert-horizontal, .advert-wrapper, .advert2, .advertColumn, .advertContainer, .advertLink, .advertText, .advert_area, .advert_container, .advert_list, .advertbox, .advertisement-1, .advertisement-block, .advertisement-swimlane, .advertiser, .advertising_banner, .advertising_block, .advertisment, .advertorial, .adverts, .adverttext, .adwords, .afs_ads, .after-post-ad, .article_ad, .b-advert, .banner-ad, .banner-ads, .banner160x600, .banner300, .bannerAd, .banner_728x90, .banner_ad, .banner_ads, .bannerad, .block-ad, .block-simpleads, .blog-ads, .bottom-ad, .bottom-ads, .bottom-left-ad, .bottomAds, .bottom_ad_block, .box-ads, .box-radvert, .boxad, .boxadv, .btn-ad, .can_ad_slug, .category-ad, .category-advertorial, .change_AdContainer, .chitikaAdBlock, .container_ad, .container_row_ad, .contentAd, .contentAds, .content_ads, .content_tagsAdTech, .cp-adsInited, .custom-ad, .desktop-ad, .dfp-tag-wrapper, .dfp_ad, .displayAd, .download_ad, .featured-ad, .featuredAdBox, .featuredAds, .flash-advertisement, .footer-ad, .footer-ads, .footerad, .forumAd, .gallery-ad, .google-sponsored { display: none!important; } .googleAdSense, .googleAds, .greyAd, .has-ad, .header-ad, .header-advert, .headerAd, .header_ad, .header_ad_center, .header_advert, .headerad, .headerads, .home-ad, .home-ads, .homeAd, .homead, .homepage-ad, .homepage_ads, .horizontal_ad, .img_ad, .imgad, .inner_ad, .innerad, .interstitial_ad_wrapper, .ipsAd, .item-ads, .item-container-ad, .leaderboard-ad, .leaderboard-ads, .leftAd, .leftad, .list-ad, .list-ads, .listad, .logo-ad, .main-ads, .marketing-ad, .mid_ad, .middle_AD, .mod-adopenx, .module-ad, .newsAd, .node-ad, .oasad, .oio-banner-zone, .openx, .page-ad, .page_ad, .pfAd, .plainAd, .playerAd, .player_ad, .player_hover_ad, .pm-ad, .post-ad, .post-sponsored, .post_ad, .postad, .premiumAdOverlay, .premiumAdOverlayClose, .promoAd, .pub_300x250, .pub_300x250m, .pub_728x90, .pushdown-ad, .rail-ad, .rbRectAd, .rectangle_ad, .refreshAds, .region-top-ad-position, .reklam, .reklama, .reportAdLink, .resultad, .review-ad, .right-ad, .rightAd, .right_ad, .right_ads_column, .rightad, .rightadv, .searchAds, .searchad, .searchads, .section-sponsor, .showAd, .side-ad, .side-bar-ad-position1, .sideAd, .sidebar-ads, .single-ad, .singleAd, .skinAd, .sky_ad, .skyscraperAd, .slide-ad, .smallAd, .small_ad, .smallads, .sponsor-box, .sponsor-logo, .sponsorBlock, .sponsorBottom, .sponsoredLinks, .sponsorlink, .sticky-ad, .story-ad, .tc_ad_unit, .text-ad, .text-ad-links, .text-ads, .textAd, .text_ad, .text_ads, .textad, .textads, .top-ad, .top-ad-container, .top-ad-content, .top-ad-wrapper, .topAds, .top_ad, .top_ad_div, .top_ad_wrap, .top_ads, .topads, .tower-ad, .trc-content-sponsored, .type_ads_default, .view_ad, .wideAd, .withAds, .wnad, .wpInsertInPostAd, .yom-ad, a[href*="/adrotate-out.php?"], a[href^="http://ad-emea.doubleclick.net/"], a[href^="http://ad.doubleclick.net/"], a[href^="http://adfarm.mediaplex.com/"], a[href^="http://ads.betfair.com/redirect.aspx?"], a[href^="http://ads2.williamhill.com/redirect.aspx?"], a[href^="http://adserving.unibet.com/"], a[href^="http://adultfriendfinder.com/p/register.cgi?pid="], a[href^="http://affiliate.coral.co.uk/processing/"], a[href^="http://marketgid.com"], a[href^="http://mgid.com/"], a[href^="http://online.ladbrokes.com/promoRedirect?"], a[href^="http://pubads.g.doubleclick.net/"], a[href^="http://us.marketgid.com"], a[href^="http://websitedhoome.com/"], a[href^="http://www.bet365.com/home/?affiliate"], a[href^="http://www.fbooksluts.com/"], a[href^="http://www.fleshlight.com/"], a[href^="http://www.liutilities.com/"], a[href^="http://www.socialsex.com/"], a[href^="http://www.yourfuckbook.com/?"], div[id^="MarketGid"], div[id^="dfp-ad-"], div[id^="div-gpt-ad"], div[itemtype="http://schema.org/WPAdBlock"], iframe[id^="google_ads_frame"], iframe[id^="google_ads_iframe"], iframe[src^="http://ad.yieldmanager.com/"], .trc_rbox .syndicatedItem, .trc_rbox_border_elm .syndicatedItem, .trc_rbox_div .syndicatedItem, .trc_related_container div[data-item-syndicated="true"] { display: none!important; }

**Comment by Alex-302** [comment]
@Bohdan-SUP @evgeniy-ADG 
I can't login here:
`Sorry, you are not an authorized Seller Central user`
Should I be registered as seller?

**Comment by Bohdan-SUP** [comment]
Yes, it's a Seller portal.

**Comment by Alex-302** [comment]
I can't get access to this portal. Is it iOS or desktop?

**Comment by evgeniy-ADG** [comment]
> 
Yes, Desktop. The portal will require registration as a seller.

**Comment by evgeniy-ADG** [comment]
I have asked for a login/pass or a TV.

**Comment by Alex-302** [comment]
ok

**Comment by evgeniy-ADG** [comment]
HAR file: 1077081 (In Chrome, press F12, open dev tools, switch to Network, click the right button and choose Save as HAR with Content and send us the HAR file. It will be helpful if a TV sessions is not acceptable to you for some reasons).

**Comment by Alex-302** [comment]
@evgeniy-ADG 
не очень хороший HAR, т.к. из-за кэширования не всё видно.
Передай на проверку:
```
@@||sellercentral.amazon.com/hz/inventory/$elemhide,jsinject
@@||sellercentral.amazon.com/gp/remote-nav-html.html$elemhide,jsinject
```
если поможет, попроси проверить, какое из них помогло.

Если не помогло, то нужно сделать новый. Сперва нужно открыть в Хроме дев тулз, на вкладке Network поставить чекбокс "Disable caching" и обновить страницу
http://imagizer.imageshack.com/img923/2432/bvr4xJ.png
и сохранить как в прошлый раз.

**Comment by evgeniy-ADG** [comment]
> @@ || sellercentral.amazon.com/gp/remote-nav-html.html$elemhide,jsinject
> if you will, ask to check which of them helped.
> 
> The first rule (inventory) eliminates the additional text which is being injected. I do not see any effect of the second one on the page rendered.
> 
> I have added both rules for now. Thanks

**Comment by Alex-302** [comment]
ok, added both
