### ISSUE TITLE
mindbodygreen.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2315]
User reported on iOS, same thing on desktop:
http://www.mindbodygreen.com/0-10999/why-you-should-foam-roll-every-day.html
![image](https://cloud.githubusercontent.com/assets/14153331/16009214/6481f860-3184-11e6-8a21-90fe35716e6f.png)

**Comment by Alex-302** [comment]
to social:
```
mindbodygreen.com##.article-social-toolbar
mindbodygreen.com###articleShareFloats
mindbodygreen.com##.article-social-toolbar.show-for-small-only
```
to Annoyances:
```
mindbodygreen.com##.reveal-modal-bg
mindbodygreen.com###freeMeditationModal
```
to mobile
```
mindbodygreen.com##.mobile-inline-ad.show-for-small-only

```
