### ISSUE TITLE
Ads in tweetbot app for iOS (Safari View)

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2317]
![image](https://cloud.githubusercontent.com/assets/15856304/16013345/bd64b6e6-3195-11e6-8b2e-3952cb3c1d50.png)

Ok. I updated and tried. In Safari no problem anymore - thanks
Calling safari view from tweetbot ad to download app still there.

ID 1117386

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/2282

**Comment by evgeniy-ADG** [comment]
A couple notes:
First screenshot is the page with blocked ads. Second one shows that Adguard is deactivated for this page and third one is the page reloaded without content blockers. The issue seems to only happen in SFSafariVC, not in Safari itself. Also it happens sometimes, not always. 

![image](https://cloud.githubusercontent.com/assets/15856304/16016167/2d92e9d6-31a2-11e6-959c-c602a179821e.png)
![image](https://cloud.githubusercontent.com/assets/15856304/16016175/35f66850-31a2-11e6-9f38-86358530e9d6.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG у вас у кого-нибудь это приложение есть? Мне не на чем проверить.

**Comment by vozersky** [comment]
не очень понял, какая связь между приложением https://itunes.apple.com/ru/app/tweetbot-4-for-twitter/id1018355599?mt=8  и тем, что на скринах

**Comment by evgeniy-ADG** [comment]
@vozersky я предполагаю, что если ссылку затвитить и открыть в этой аппе, то она использует функцию сафари вью, в которой мы вроде бы как все блокируем, да не все, как утвеождает ув. юзер.

**Comment by evgeniy-ADG** [comment]
ну ок закрою дублем...
