### ISSUE TITLE
[Windows] www.tweaktown.com - missed ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#2319]
![](http://i.imgur.com/9XZWfN2.png)

e.g. http://www.tweaktown.com/news/52572/serious-sam-vr-gory-shooting-gallery-htc-vive-oculus-rift/index.html

Remove:
```
||tweaktown.com/zyx?p=
||tweaktown.com/xyz?$script
```

Add:
``` 
tweaktown.com#%#window.checkState = function() {};
 ```

**Comment by Alex-302** [comment]
But we can just hide them:
tweaktown.com##iframe[title="3rd party ad content"]

**Comment by Vincent-Michael** [comment]
hm, are still anti adblock ads :/ @Alex-302

**Comment by Alex-302** [comment]
hmmm, they was hidden when I made this rule. Added your
