### ISSUE TITLE
biglion.ru

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#2320]
Ломается описание внутри любой акции, например: http://www.biglion.ru/deals/centrkaribija2-67/

![ekwd4fvi-ay](https://cloud.githubusercontent.com/assets/17472907/16043772/f9193608-3249-11e6-911a-db2eee52fabd.jpg)

**Comment by Alex-302** [comment]
добавил в фильтр соц сетей
@@||yastatic.net/share2/share.js$domain=biglion.ru
