### ISSUE TITLE
missed ad forum.watch.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2321]
Фильтры Adguard, обновлены. Пропускает много рекламы

http://forum.watch.ru/

![2016-06-15_21-44-47](https://cloud.githubusercontent.com/assets/16462533/16093038/ef7e654c-3342-11e6-883f-607712a0fd43.png)

**Comment by Alex-302** [comment]
watch.ru##div[style="display:block; width:100%; min-width:965px; overflow:hidden;"] a[rel="nofollow"]
watch.ru###banner1
watch.ru###banner2
||clock.ru/company/$domain=watch.ru
watch.ru##div[style*="width:100%; height:60px;"]

**Comment by vgavrish** [comment]
АНДРОИД
forum.watch.ru
верхней части не блокируется рекламный баннер, его не видно, но в незаполненной части экрана, где он размещен при нажатии происходит переход на рекламную страницу. 
Ф: 1,2,3,4,11,14
Full, https
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/20964234/5240061c-bc79-11e6-953b-6f7e23847a88.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
forum.watch.ru##div[style="display:block; width:100%; min-width:965px; height:100px; overflow:hidden;"]
```
