### ISSUE TITLE
pcmag.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2322]
http://www.pcmag.com/article2/0,2817,2475079,00.asp
Can't reproduce with useragent on a Mac.
User 1311900
![image](https://cloud.githubusercontent.com/assets/14153331/16100755/37034dbc-3369-11e6-944e-406974224325.png)
![image-1](https://cloud.githubusercontent.com/assets/14153331/16100759/3bf5c728-3369-11e6-8bdc-2d9ae2726e1f.png)

**Comment by Alex-302** [comment]
@vozersky 
check it please
Filters:
ID=2 Name="English filter" Version=1.0.86.51 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.31 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.23 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.8.75 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.3.92 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.62 Enabled=YES

**Comment by vozersky** [comment]
reproduced the message from screenshot#2, it actually moves when you scroll the page
probs an anti-adblocking script

**Comment by Alex-302** [comment]
@Bohdan-SUP @vozersky 
please update filters and check again

**Comment by ameshkov** [comment]
The same issue with desktop Safari

**Comment by ameshkov** [comment]
Filter update did not help

**Comment by Alex-302** [comment]
changed to
`pcmag.com##body > div[style^="position:fixed;top:47%;width:100%;height:auto;z-index:9999;"]`
update is ready
