### ISSUE TITLE
flyordie.com [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#23221]
**Site**: http://www.flyordie.com/backgammon/

http://www.flyordie.com/games/online/games.html?lang=en&game=Backgammon&rs=1

**Issue**: Please remove the ad text string and ads shown at various places on different pages of this site.

Note: You may have to create a free account to see some pages/play games.
 
**Screenshot**:
http://prntscr.com/l0h52m
http://prntscr.com/l0h4bd
http://prntscr.com/l0h4v8

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 69.0.3497.100 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.8 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Spam 404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
Ad text string still seen on: http://www.flyordie.com/backgammon/
Screenshot: http://prntscr.com/l2ul0t

Also, can you please check this issue. I observed on PC and Android that the page remains blank few times after clicking on the "Play Now" button as seen here http://prntscr.com/l2uolg
I think this is due to some incorrect blocking? Try clicking on the Play Now button for some other game and you will see (Ex: Checkers).

**Comment by Alex-302** [comment]
> the page remains blank

only 1-3 seconds on my end.

**Comment by Nzzyme** [comment]
Seeing an empty ad banner on Android

https://ibb.co/vxf0PFV

Please fix

**Comment by Alex-302** [comment]
It does not work on my device - "Unsupported device"
@BlazDT please take a look
