### ISSUE TITLE
onhax.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2323]
https://onhax.net/xstana-module-prime-v2-1-5-cracked-apk-is-here-latest
![screen shot 2016-06-16 at 3 57 15 am](https://cloud.githubusercontent.com/assets/14153331/16102281/88dc22a0-3376-11e6-9def-8c9b54564c2d.png)

**Comment by MuneebAhmedZia1** [comment]
Same issue :3

**Comment by Alex-302** [comment]
Added
`onhax.net##.promo-an`
