### ISSUE TITLE
yahooeu.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2324]
http://yahooeu.ru/video/79198-bad-room-83-trener-alfa-samok-18.html
![a1121ef776664be28df07b6336bcbfb8](https://cloud.githubusercontent.com/assets/18548949/16111163/fb8c20dc-33b9-11e6-9356-f5c844c3404c.png)

**Comment by Alex-302** [comment]
||llgerege.com^$third-party
