### ISSUE TITLE
goldenshara.org

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2325]
http://goldenshara.org/viewtopic.php?t=16093462

http://prntscr.com/bh1e6x
http://prntscr.com/bh1eax

**Comment by Alex-302** [comment]
в русский
||bestofgeorgia.ge/news.js$third-party
goldenshara.org##a[href^="http://sub2.admitlead.ru/sb/clk/"]

**Comment by vgavrish** [comment]
http://goldenshara.org/viewforum.php?f=845
![screenshot_8](https://cloud.githubusercontent.com/assets/18548949/16190984/ac061bb0-36ea-11e6-9694-55a4d993c915.jpg)

**Comment by Alex-302** [comment]
||cda.0-shiny.com^$third-party

**Comment by vgavrish** [comment]
Расширение
http://goldenshara.org/viewtopic.php?t=16094595

Кнопка "Скачать" - http://prntscr.com/bljl6c

**Comment by Alex-302** [comment]
goldenshara.org###main_content_wrap > table.sura
