### ISSUE TITLE
iOS tweetbot app - ads are not blocked inside Safari View Controller

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2326]
In theory Content Blocker should have been applied to the Safari View Controller (which is used by the tweetbot app), but for some reason it didn't happen.

We should investigate and find out what has happened.

http://forums.macrumors.com/threads/ios-9-content-blockers-mini-reviews.1918483/page-29#post-22990151
http://forums.macrumors.com/threads/ios-9-content-blockers-mini-reviews.1918483/page-29#post-22990155

**Comment by Stillness-2** [comment]
Unfortunately, I don't see ads on http://www.bigbangnews.com in SafariViewConrtoller. The picture, which you attached in forum, contains advertising of the app for this site, that is valid. Could you please send a picture with ads?

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/2317 ?

**Comment by Alex-302** [comment]
for mobile app banner - added to annoyances filter
bigbangnews.com##.bajar-app-fixed
to Spanish
bigbangnews.com##div[class$="b300x250"]

**Comment by Bohdan-SUP** [comment]
User 1307027 reported same issue with http://9to5mac.com/2016/06/13/new-ios-10-music-app-design/
Happens in Safari View Controller only.

**Comment by Bohdan-SUP** [comment]
Another feedback from user 1307027: 
"I wanted to add that I created a custom user filter for a page banner on YouTube.com within the standard Safari app. However, within SVC, the banner is still present in its entirety and not blocked. Again, refreshing in SVC resolves the issue.

Finally, clicking the Adguard extension while in SVC doesn't appear to be honoring the creation of custom user filters. It will go through the entire process without issue, ask permission to open the Adguard app, and then nothing. Nothing is added to user filters."

**Comment by Stillness-2** [comment]
https://github.com/AdguardTeam/AdguardForiOS/issues/97
