### ISSUE TITLE
alluc.ee

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#2327]
For example: http://www.alluc.ee/l/breaking-bad-s05e01-brrip-sujaidr/d6bv1b3g

Overlay + X in the middle of the player: http://screencast.com/t/ttG4jjq5

Original thread: 
https://forum.adguard.com/index.php?threads/unblockable-ads.11049/

**Comment by Alex-302** [comment]
already fixed on github

**Comment by vbagirov** [comment]
In Safari, there is a pop-up when you click on the player. Doesn't matter if you use iOS or desktop. In other browsers there is no popup.
