### ISSUE TITLE
notebookcheck.com - missed video ad

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2328]
Source:
https://github.com/AdguardTeam/AdguardForiOS/issues/93

Page URL:
http://www.notebookcheck.com/Samsung-Smartphones-mit-flexiblem-Display-im-naechsten-Jahr.167522.0.html

Look for a video player in the bottom of the article.
Can we simply block spoods.io?

**Comment by Alex-302** [comment]
It is blocked now by German filter(EasyList Germany)
`||widget.spoods.io/loader.js`
