### ISSUE TITLE
http://m.reklama5.mk/ - blocked images

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2329]
basic filter set
![image](https://cloud.githubusercontent.com/assets/15856304/16127880/0a713e28-3407-11e6-9ac2-3a35ef059a4b.png)

1313549

**Comment by Alex-302** [comment]
Please check in any browser with desktop Adguard:
- disable in English filter(images will be blocked)
```
@@||reklama5.mk^$~third-party
```
- add:
```
@@||reklama5.mk^$domain=reklama5.mk
```

**Comment by evgeniy-ADG** [comment]
Works fine with @@||reklama5.mk^$domain=reklama5.mk

**Comment by Alex-302** [comment]
Added to Safari filter
