### ISSUE TITLE
adguard blocking PSN

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#23309]
Adguard Defense blocking `psmedia.playstation.com` domain, Cannot open `https://www.playstation.com` site and PSN. 

https://reports.adguard.com/pl/psmedia.playstation.com/report.html

`https://secure.eu.playstation.com/psnauth/PSNAuth/pdc/?returnURL=https%3A//secure.eu.playstation.com/psn/mypsn/competelanding/&request_locale=pl_PL&postSignInURL=https://www.playstation.com/pl-pl/`

![20181002124434-screenshot](https://user-images.githubusercontent.com/9846948/46344279-ef4fef80-c640-11e8-8624-e31029134f08.png)

**Comment by AdamWr** [comment]
It seems that it was fixed, because I can't reproduce it now.
