### ISSUE TITLE
 http://www.bloomberg.com - anti adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2331]
http://www.bloomberg.com
![image](https://cloud.githubusercontent.com/assets/15856304/16132927/fb81a616-341d-11e6-9cc2-1351d7ec7bd8.png)

only mac, both app and extension, doesn't appear on win

**Comment by Alex-302** [comment]
Which browser?

**Comment by evgeniy-ADG** [comment]
Safari, I think.

**Comment by vozersky** [comment]
Managed to reproduce it on mac, Chrome only, Safari is clear.

**Comment by evgeniy-ADG** [comment]
Да, кхром, сорри. Не я тестил.

**Comment by Alex-302** [comment]
Не могу поймать, видать редкое явление.

**Comment by Aokromes** [comment]
I have this issue on windows with opera.

**Comment by Alex-302** [comment]
@Aokromes nothing on my end.
Does it appears only once?

**Comment by Aokromes** [comment]
I see it from time to time.

**Comment by Alex-302** [comment]
I can't reproduce it. Could yo please make a screenshot of html code of this message?

**Comment by Aokromes** [comment]
http://i.imgur.com/qGe8xrp.png

**Comment by Aokromes** [comment]
http://i.imgur.com/VfxECiJ.png

**Comment by Alex-302** [comment]
Please try:
```
bloomberg.com###adBlockerContainer
```
and make a screenshot of overlay code(is is not transparent, as I see on screenshot above)

**Comment by Aokromes** [comment]
It looks to work:
http://i.imgur.com/Ey0ieke.png

**Comment by Alex-302** [comment]
Is my rule works correctly? No overlay here?

**Comment by Aokromes** [comment]
It looks so, i don't see any word of anti-adblock on any browser.
BTW. that adgurd thing is intended typo?

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
bloomberg.com###adBlockerContainer
```
> BTW. that adgurd thing is intended typo?

where did you see it?

**Comment by Aokromes** [comment]
at http://i.imgur.com/Ey0ieke.png look the selected row and under it.

**Comment by Alex-302** [comment]
)) It will be fixed with a new Assistant.
