### ISSUE TITLE
megogo.net - anti adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2332]
basic filter set, up to date
![20160617_121103000_ios](https://cloud.githubusercontent.com/assets/15856304/16150118/f7c3e554-349d-11e6-85f5-77b51a7b98cf.png)

**Comment by evgeniy-ADG** [comment]
проблема в английском фильтре, без него все ок.

**Comment by Alex-302** [comment]
А русский включен? В нём-то решение
