### ISSUE TITLE
http://glavpost.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2333]
http://glavpost.com/post/16jun2016/blogs/87870-vitaliy-portnikov-doneckaya-respublika-sodoma.html

![image](https://cloud.githubusercontent.com/assets/15856304/16152048/92a800a0-34a8-11e6-86eb-2f7a3d0e2aa5.png)

**Comment by Alex-302** [comment]
добавил
glavpost.com##.useful-slider
