### ISSUE TITLE
chrdk.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#23341]
[https://chrdk.ru/news/v-mitino-srazu-tri-cheloveka-nablyudali-sharovuyu-molniyu](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://chrdk.ru/news/v-mitino-srazu-tri-cheloveka-nablyudali-sharovuyu-molniyu)

 1. В правом чёрном прямоугольнике скрывается баннер со ссылкой на статьи (каждый раз после перезагрузки - разные). Правила, ответственные за скрытие виджета:

`/securepubads.` - Английский фильтр
`||googlesyndication.com/pagead/` - Английский фильтр
`||googlesyndication.com/simgad/` - Английский фильтр
`##div[id^="google_ads_iframe_"]` - Английский фильтр
`##iframe[id^="google_ads_iframe"]` - Английский фильтр
`##iframe[width="240"][height="400"]` - Английский фильтр
`##.img_ad` - Английский фильтр

<details><summary>Screenshot's:</summary>

![2018 10 01-1](https://user-images.githubusercontent.com/17948007/46382090-f2cf8f00-c6b1-11e8-8458-ea97e7e1a38f.png)
----------
![2018 10 01-2](https://user-images.githubusercontent.com/17948007/46382094-ff53e780-c6b1-11e8-9c84-86d4330e5efc.png)
----------
![2018 10 02-1](https://user-images.githubusercontent.com/17948007/46382099-067af580-c6b2-11e8-8c0b-42c6d2b529f9.png)
</details><br/><br/>

 2. Виджет соц. сетей иногда появляется в этом прямоугольнике. Но, почему-то, следующие правила не скрывают чёрный прямоугольник, когда туда подгружаются выджеты соц. сетей (ВК и ОК):

`chrdk.ru##.lookatme_sticky:has([href*="/vk.com/chrdk_ru"])`
`chrdk.ru##.lookatme_sticky:has([href*="/www.ok.ru/"])`

<details><summary>Screenshot:</summary>

![2018 10 03-2](https://user-images.githubusercontent.com/17948007/46389368-0f7fbd00-c6da-11e8-96fb-6220f40d3f29.png)
</details>

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v2.10.11
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Они сами под критерий рекламы подвели этот блок. Разблокировать не буду.
