### ISSUE TITLE
com.ketchapp.donttouchthespikes ads

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2334]
https://play.google.com/store/apps/details?id=com.ketchapp.donttouchthespikes&hl=en
![image](https://cloud.githubusercontent.com/assets/14153331/16159978/aa93545e-3493-11e6-8f2b-149ad25dd433.png)

**Comment by Alex-302** [comment]
@Bohdan-SUP 
Фильтрация HTTPS включена?

**Comment by Bohdan-SUP** [comment]
Да, включена.

**Comment by vgavrish** [comment]
log [debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/322147/debug.txt)

**Comment by Alex-302** [comment]
@Bohdan-SUP 
какой режим фильтрации - VPN пли прокси? Если прокси ручной, то могут быть пропуски. На нерутованном девайсе только VPN поможет.

**Comment by Alex-302** [comment]
@evgeniy-ADG @vgavrish @Serzh-SUP 
тоже учитывайте этот момент при пропусках в приложениях

**Comment by evgeniy-ADG** [comment]
"proxyMode" : false,
 "proxyPort" : 8080,
 "proxySetupManualMode" : false,

Вот что у него, но там комбо - speedy режим и нет HTTPs, отписал.
