### ISSUE TITLE
Radar Express - com.appdlab.radarexpress

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2335]
https://play.google.com/store/apps/details?id=com.appdlab.radarexpress
You need US IP, or find apk [here](https://apkpure.com/radar-express-weather-radar/com.appdlab.radarexpress?hl=en)
http://imgur.com/by6Fqbk
Log - [debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/321128/debug.txt)
User - 1155233

**Comment by Alex-302** [comment]
Looks like facebook adchoices. Try to enable https filtering.

**Comment by Bohdan-SUP** [comment]
It's already enabled.

**Comment by Alex-302** [comment]
I can't reproduce it. I see ads only without HTTPS filtering.
What mode is used - VPN or proxy? If proxy - manual or auto?
