### ISSUE TITLE
BSPlayer

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2336]
https://play.google.com/store/apps/details?id=com.bsplayer.bspandroid.free&hl=en

Можно ли убрать рекламку платного плеера?
![screenshot_7](https://cloud.githubusercontent.com/assets/18548949/16169293/2aa49f34-3531-11e6-967b-516bcfd54920.jpg)

**Comment by Alex-302** [comment]
Встроен. Даже с выключенной сетью выскакивает.
