### ISSUE TITLE
Filecommander

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2337]
https://play.google.com/store/apps/details?id=com.mobisystems.fileman&hl=en

Реклама в проводнике между файлами:
![8ece32d9367e4c19a1955615622633d4](https://cloud.githubusercontent.com/assets/18548949/16169605/7752f158-353d-11e6-9526-c8a9c6034dc9.png)

**Comment by Alex-302** [comment]
У меня был такой баннер, но после очистки данных приложения он не появляется. Посоветуй поделать то же самое(может и очистки кэша достаточно). Ещё можно для надёжности в файерволе доступ к wifi и моб сети запретить.

**Comment by Alex-302** [comment]
Вообще этот баннер встроен, нашел картинки внутри apk
http://imagizer.imageshack.com/img923/6383/kVpKgv.png
Не известно при каких условиях приложение показывает баннер.

**Comment by vgavrish** [comment]
При переходе по меню приложения, внизу появляется черный баннер:
http://prntscr.com/blltsl
http://prntscr.com/bllu1j
Особенно появляется баннер, после перехода на вкладку PC File Transfer и далее по вкладкам.
Чистила данные, кэш, все равно появляется.
У пользователя выглядит так:
http://prntscr.com/bllukz
