### ISSUE TITLE
adrise.tv

### ISSUE THREAD

**Issue by FlyPigsFly** [AdguardTeam/AdguardFilters#23383]
Ads are being served from

"adrise.tv"

More specifically
"ads.adrise.tv"
"ads-tp.adrise.tv"
And others...

Also AdGuard DNS warns users of malware if visiting adrise.tv. Blocking adrise.tv fully is recommended.

**Comment by Alex-302** [comment]
It is mistakenly blocked by browsing security. Will be unblocked.

**Comment by Alex-302** [comment]
Is blocking of `ads.adrise.tv` and `ads-tp.adrise.tv` required?
