### ISSUE TITLE
pcradio.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2338]
Расширение.
Невозможное прослушивания радио http://pcradio.ru/radio/russkoe
![304bbf28439d47b1851a001d5d406c3e](https://cloud.githubusercontent.com/assets/18548949/16170622/d4e75a24-3561-11e6-9b2f-7f64a125f467.png)
Помогает отключение Английского фильтра.

**Comment by Alex-302** [comment]
Fixed
