### ISSUE TITLE
simpsons.wikia.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2340]
http://simpsons.wikia.com/wiki/Ha_Ha!

![simpsons wikia com](https://cloud.githubusercontent.com/assets/19608513/16170752/5ecdae7e-3566-11e6-84c7-10d6718ece9b.png)

**Comment by Alex-302** [comment]
to social filter
wikia.com##.share-wrapper
to annoyances
simpsons.wikia.com###WikiaNotifications
