### ISSUE TITLE
softpedia.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2344]
http://news.softpedia.com/news/microsoft-keeps-improving-iphone-apps-this-time-it-s-bing-505400.shtml  You can see below moving down page a little

![softpedia](https://cloud.githubusercontent.com/assets/19608513/16170955/10edbec8-356c-11e6-9dc8-289bc2b63ac3.png)

**Comment by Alex-302** [comment]
Added to annoyances
softpedia.com###bottombubble
