### ISSUE TITLE
pcmag.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2345]
http://www.pcmag.com/Fastest-Mobile-Networks

![pcmag_1](https://cloud.githubusercontent.com/assets/19608513/16171006/9d728742-356d-11e6-8627-b93941f1e16a.png)

![pcmag_2](https://cloud.githubusercontent.com/assets/19608513/16171009/a76045e6-356d-11e6-9fca-3b87fbffa637.png)

**Comment by Alex-302** [comment]
added to English filter
pcmag.com#%#window.checkState = function() {};
