### ISSUE TITLE
livescience.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2347]
http://www.livescience.com/50717-amazing-images.html

![livescience_1](https://cloud.githubusercontent.com/assets/19608513/16171089/41ade472-356f-11e6-999f-fabab78345cc.png)

![livescience_2](https://cloud.githubusercontent.com/assets/19608513/16171092/46ed2f7e-356f-11e6-806d-1fd4be16911b.png)

**Comment by Alex-302** [comment]
I don't see these banners. Which filters and Adguard version are you using?

**Comment by thislife81** [comment]
Filters:
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)EasyList
8)RU AdList
9)EasyPrivacy
10)RU AdList: BitBlock
11)Fanboy's Enhanced Tracking List

Version- 2.3.8 (Google Chrome browser)

**Comment by Alex-302** [comment]
try to disable
```
7)EasyList
8)RU AdList
9)EasyPrivacy
10)RU AdList: BitBlock
11)Fanboy's Enhanced Tracking List
```
EasyList is unnecessary, when our English filter is enabled.

Added to social filter
livescience.com###stickyShare
to annoyances
livescience.com##.right-rail > div[class^="subscribe"]

**Comment by thislife81** [comment]
I disabled 7-11 filters. But again these shown when enter this site

**Comment by Alex-302** [comment]
check these rules
@@||ads.servebom.com/tmnhead.js$domain=livescience.com
livescience.com#%#Object.defineProperty(window, 'tmntag_raascallback', { get: function() { return; } });

**Comment by thislife81** [comment]
Great, it worked! :+1:
