### ISSUE TITLE
designyourway.net

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2348]
http://www.designyourway.net/blog/resources/some-of-the-best-photography-books-to-help-you-become-a-pro/

![designyourway](https://cloud.githubusercontent.com/assets/19608513/16171105/e168d5f8-356f-11e6-81b5-156ecbe2de2a.png)

**Comment by Alex-302** [comment]
to English
designyourway.net##.reclamaint
to annoyances
/wp-content/plugins/arscode-ninja-popups/*$domain=designyourway.net
