### ISSUE TITLE
oddee.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2349]
http://www.oddee.com/item_97996.aspx   Move down the bottom of page

![oddee](https://cloud.githubusercontent.com/assets/19608513/16171141/c28d03a6-3570-11e6-83fc-ba8fc1f8dd45.png)

**Comment by Alex-302** [comment]
added to annoyances filter
oddee.com##div[id="slidebox"][style="right: 0px;"]
