### ISSUE TITLE
VancouverSun app

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2351]
https://www.amazon.com/VANCOUVER-SUN-NEWS-VANCOUVERSUN-COM/dp/B00XHYGJOW/
![image](https://cloud.githubusercontent.com/assets/14153331/16173274/cd09bef8-35a4-11e6-9b6f-6ee20b7e3426.png)
![image](https://cloud.githubusercontent.com/assets/14153331/16173277/d4e82178-35a4-11e6-9138-1f1ab7effea5.png)

Logs here - 1310940

**Comment by Alex-302** [comment]
I can't download it. Give me please a Google Market link, or just apk file

**Comment by Bohdan-SUP** [comment]
Yes, it is.

**Comment by Alex-302** [comment]
This app is clean. I don't see this ad without Adguard. I thins the app in Google Market is different then the app in Amazon store.
I need HTTP log and, if it is possible - apk file.
