### ISSUE TITLE
Реклама в видеоплеере на online.anidub.com

### ISSUE THREAD

**Issue by PUKALO228** [AdguardTeam/AdguardFilters#2353]
1. Переходим на http://online.anidub.com/anime_tv/anime_ongoing/9747-prikaz-svyshe-big-order-01-iz-16.html
2. Выбираем "Наш плеер Beta"
3. Видим рекламу О_о [Adguard 6.0.226.1108; Firefox 47.0]
![default](https://cloud.githubusercontent.com/assets/20024144/16175990/1a424ad4-361b-11e6-9c2a-c426e6e050ef.png)

**Comment by Alex-302** [comment]
исправлено.
