### ISSUE TITLE
http://m.welt.de/ - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2354]
http://m.welt.de/sport/fussball/em-2016/article156179248/Deutschland-macht-niemandem-Angst.html
![image](https://cloud.githubusercontent.com/assets/15856304/16176173/8198b9e0-360f-11e6-943d-94f2ead83f58.png)

ID=122 Name="Fanboy's Annoyances" Version=1.0.59.52 Enabled=YES - works without this

**Comment by Alex-302** [comment]
заблокировано корректно. Вероятно юзер не совсем понимает назначение этого фильтра.
Для пользовательского
`@@||qmerce.com^$domain=m.welt.de`
