### ISSUE TITLE
ru.cn.tv app - false blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2355]
![image](https://cloud.githubusercontent.com/assets/15856304/16176412/697ab400-3617-11e6-85a4-46e08e8684aa.png)
Disabling ad filtering helps. HTTPs is not filtered.
1315899

**Comment by Alex-302** [comment]
@evgeniy-ADG 
нужен лог HTTP запросов. У меня не работает из-за региона.

**Comment by Alex-302** [comment]
Международная версия работает без проблем.

**Comment by evgeniy-ADG** [comment]
Блин, да, сорри. Попрошено.
