### ISSUE TITLE
Incorrect Blocking and Anti Adblock Script

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2356]
http://www.fullfilmizlesin.com/chloe-and-theo-2015-turkce-dublaj-izle/

---> When choose the field of  "Openload Tek" to watch movie, it happens:
![1](https://cloud.githubusercontent.com/assets/19608513/16176995/727f0a0e-3628-11e6-890f-eb70a34495dd.png)

---> And when choose the field of "Videomega Tek", it happens:
![2](https://cloud.githubusercontent.com/assets/19608513/16177000/974e2090-3628-11e6-8e1e-5d3201f7cdc5.png)

Filters i used in version 2.3.8 (Google chrome browser extension):
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)EasyList
8)RU AdList
9)EasyPrivacy
10)RU AdList: BitBlock
11)Fanboy's Enhanced Tracking List

**Comment by thislife81** [comment]
I already dont reproduce this problem, So you can close this topic.

**Comment by Alex-302** [comment]
Maybe it was fixed in EasyList.
