### ISSUE TITLE
com.p1.chompsms ads

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2357]
https://play.google.com/store/apps/details?id=com.p1.chompsms
[debug (1).txt](https://github.com/AdguardTeam/AdguardFilters/files/322320/debug.1.txt)
![image](https://cloud.githubusercontent.com/assets/14153331/16177591/04d3a6f0-363b-11e6-93e7-bc413140d3be.png)

**Comment by Alex-302** [comment]
Чисто. У тебя повторяется?
