### ISSUE TITLE
Videos on univision.com don't work

### ISSUE THREAD

**Issue by tiberian83** [AdguardTeam/AdguardFilters#2358]
If Adguard is enabled videos don't work on univison.com.

Here is an example:

http://www.univision.com/novelas/tres-veces-ana/tres-veces-ana-santiago-ardio-de-pasion-con-ana-lucia-mientras-ana-leticia-lo-recordaba-escena-del-dia-video

**Comment by Alex-302** [comment]
I don't see this player without Adguard
http://imagizer.imageshack.com/img923/728/yJma7q.png
Maybe regional restrictions are on this site.

**Comment by tiberian83** [comment]
It's a flash player and it's geo restricted to the USA.

**Comment by Alex-302** [comment]
Tried publiс US VPN - player is not displayed. Could you provide me remote access?
