### ISSUE TITLE
utililab.mysearchguardian.com Missed ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2361]
https://utililab.mysearchguardian.com/?sft=y#q=ba&start=20
When you search on this site, you can see the following ads:

![1](https://cloud.githubusercontent.com/assets/19608513/16189000/e69c2ef4-36e0-11e6-8355-501cd3ce30c9.png)

![2](https://cloud.githubusercontent.com/assets/19608513/16189007/edf56f9e-36e0-11e6-8a6b-a4e041ea858a.png)

**Comment by Alex-302** [comment]
They use the same code for search result and for ads.
