### ISSUE TITLE
http://www.telegraaf.nl/ - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2362]
http://www.telegraaf.nl/

![image](https://cloud.githubusercontent.com/assets/15856304/16189099/60715164-36e1-11e6-922d-bf7718ea569c.png)

![image](https://cloud.githubusercontent.com/assets/15856304/16189107/6657b10e-36e1-11e6-99b6-2ab1b1ddd0f1.png)

**Comment by worldsdream** [comment]
I already mentioned this yesterday with @Alex-302, the one that sent this in, is not me. It seems more people have this ad, Let him update the Dutch filter, it should be removed, but there is another ad down under, that is still there.

**Comment by worldsdream** [comment]
https://forum.adguard.com/index.php?threads/resolved-telegraaf-nl.11188/#post-87435

**Comment by worldsdream** [comment]
Please also remove the cookie notice on this page, telegraaf.nl and add it to annoyance filter.

**Comment by Alex-302** [comment]
Tested on Safary - these ads are hidden. I see them without adguard.

**Comment by worldsdream** [comment]
It's when you enable optimized filters

**Comment by Alex-302** [comment]
I use optimized filters.

**Comment by Alex-302** [comment]
You can send message with a log to our support and tell me ticket ID.

**Comment by worldsdream** [comment]
I only see user ID in e-mail. I can't find the ticket ID

**Comment by Alex-302** [comment]
give me user id, I will try to find your ticket

**Comment by worldsdream** [comment]
1318458

**Comment by Alex-302** [comment]
Yes, you can use 1318458 as ticket ID.
Loaded your content blocker from ticket, and only one banner was reproduced:
<details>
![image](http://imagizer.imageshack.com/img921/4422/D26D6z.png)
</details>
Try this rule
`##.section-ad`
it is absent in your content blocker.

**Comment by worldsdream** [comment]
I just did, I get:

ERROR
Cannot add the filter rule. Rule text is invalid

**Comment by Alex-302** [comment]
strange.
try this:
telegraaf.nl##.section-ad

**Comment by worldsdream** [comment]
Perfect! Now it's blocked. Please add to filterlist instead of ##.section-ad

**Comment by Alex-302** [comment]
added
