### ISSUE TITLE
https://www.netflix.com/fr-en/ - can't sign in

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2363]
When tapping on sign in, I arrive on about:blank when AdGuard is enabled.

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.86.80 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.35 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.28 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.8.76 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.4 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.64 Enabled=YES

**Comment by Alex-302** [comment]
Added to Safari filter
@@||netflix.com/*/Login
