### ISSUE TITLE
freekaamaal.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2365]
http://freekaamaal.com/coupons/cardekho.com/

You can see below moving down page a little:
![w](https://cloud.githubusercontent.com/assets/19608513/16189788/ce7abecc-36e4-11e6-8f9f-2aefc5c38700.png)

And this:
![p](https://cloud.githubusercontent.com/assets/19608513/16189936/67d11044-36e5-11e6-9938-478e3ae7d234.png)

**Comment by Alex-302** [comment]
I don't see this popup, only the the bell

**Comment by thislife81** [comment]
It's interesting. On my browser moving down page, this pop-up shown

By the way active filters:
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List

Adguard version: 2.3.8
Operating system: Windows 8.1

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/16232397/09827eee-37d3-11e6-9aab-0ceca1bba741.png)
yep, scroll down and it'll appear

**Comment by Alex-302** [comment]
@evgeniy-ADG please make a screenshot of the element's code

**Comment by evgeniy-ADG** [comment]
Today it doesn't appear. We have another annoyance instead:
![image](https://cloud.githubusercontent.com/assets/15856304/16359479/7ff5ba6e-3b3e-11e6-940b-fd4c2625f884.png)
![image](https://cloud.githubusercontent.com/assets/15856304/16359493/11b838e6-3b3f-11e6-8549-4893f5fd469c.png)

**Comment by Alex-302** [comment]
I can't find this code, but added
`freekaamaal.com###ftrbgdiv`
