### ISSUE TITLE
http://www.iqiyi.com/v_19rrle5liw.html - ads before video

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2367]
It works very slow from outside China, but please have a look into this. Basic filter set + Chinese filter

![](https://cloud.githubusercontent.com/assets/15856304/16190837/fca462bc-36e9-11e6-86d9-6a0f746ad5bc.png)

**Comment by Alex-302** [comment]
I don't understand which element I should to block.

**Comment by evgeniy-ADG** [comment]
The ad before the video. It appears randomly and may not reappear after you reload the page.

**Comment by Alex-302** [comment]
It is impossible on iOS

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/16356120/12b711c2-3ad6-11e6-8700-9d1e39a812b9.png)
the same on windows with
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:5 Name: Experimental filter Url: http://adguard.com/ru/filter-rules.html?id=5
FilterId:11 Name: Mobile Ads filter Url: http://adguard.com/ru/filter-rules.html?id=11
FilterId:104 Name: EasyList China Url: https://easylist-downloads.adblockplus.org/easylistchina.txt

**Comment by Alex-302** [comment]
check these rules
||87.245.198.80/netcncoversea.inter.iqiyi.com/videos/other/*.f4v?wsiphost=local$mp4
||netcncoversea.inter.iqiyi.com/videos/other/*.f4v$mp4

**Comment by evgeniy-ADG** [comment]
http://www.iqiyi.com/v_19rrmtwz0.html
<details>
![screen shot 2016-08-17 at 12 19 56 pm](https://cloud.githubusercontent.com/assets/15856304/17731233/27d06504-6475-11e6-9c46-94f643894835.png)
![screen shot 2016-08-17 at 12 20 12 pm](https://cloud.githubusercontent.com/assets/15856304/17731234/27e16cbe-6475-11e6-8b37-55fc7763cd76.png)
</details>

the standard set + easylish china

**Comment by Alex-302** [comment]
I don't see ads in the player with easylish china

**Comment by evgeniy-ADG** [comment]
I do. Mac OS X 10.11.6, Chrome  52.0.2743.116 (64-bit), Adguard 1.3.0 beta, general filter set + easylist china

**Comment by Alex-302** [comment]
Check these rules:
```
||netcncoversea.inter.iqiyi.com/videos/other/*.f4v|$domain=iqiyi.com
||data.video.qiyi.com/videos/other/*.hml?pv=$domain=iqiyi.com
```

**Comment by evgeniy-ADG** [comment]
Sorry, it was awhile ago, but could you please check if those rules still legit?

![image](https://cloud.githubusercontent.com/assets/15856304/22463544/c546d430-e7ba-11e6-982c-92b92c25bd3b.png)

filters: 2 104 230 10000 (??? It’s EasyList China+EasyList)

**Comment by Alex-302** [comment]
Maybe ad is requested by flash player.
@seanl-adg could you take a look, please?
