### ISSUE TITLE
http://www.filmizles.org/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2369]
http://www.filmizles.org/
![6](https://cloud.githubusercontent.com/assets/19608513/16191391/a5492b9e-36ec-11e6-81a7-c0b83a1444fa.png)

Ads before movie:
http://www.filmizles.org/suc-ortagi-complicit-2013-turkce-dublaj-izle.html

![7](https://cloud.githubusercontent.com/assets/19608513/16191400/b045a95a-36ec-11e6-88c3-c8826bd799cf.png)

**Comment by Alex-302** [comment]
to Turkish filter:
filmizles.org##iframe[width="160"][height="600"]
filmizles.org###toolbar
||storage.cubecdn.net^$domain=filmizles.org
filmizles.org###VideOnrekLam
filmizles.org#$#.tabsContent { display: block!important; }

**Comment by thislife81** [comment]
I found another site that exist these ads:

For example: http://www.fullhdfilmizlebe.org/adama-2015-turkce-dublaj-izle.html
Here you can see: 1) Ad before movies; 2) A toolbar at the bottom of page blue colored "KAPAT"

So, i think you haven't to add rules for only this site. 
I mean, filmizles.org###VideOnrekLam (This rule is only for this site) not, must be ###VideOnrekLam (For all sites)

**Comment by Alex-302** [comment]
write here these sites.
These rules
###VideOnrekLam
#$#.tabsContent { display: block!important; }
should be specific, because they works in pair, but making the second rule as generic is not good idea
