### ISSUE TITLE
stealth mode breaks aliexpress

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2371]
Здравствуйте. Имеется проблема с сайтом AliExpress. В видео показал, что именно происходит. Когда включена защита, при входе в профиль, потом когда нажимаю на "Мои заказы" из сайта выкидывает, не входит, а когда защита выключена при нажатии на "Мои заказы" страница нормально открывается.

Видео тут: 1069133 от 17 июня

Помогло отключения антитреккинга, вот такое 
@@||ru.aliexpress.com^$stealth, как утверждает пользователь, не помогло.

**Comment by Alex-302** [comment]
У тебя повторяется? Потыкал - всё норм, все опции антитрекинга включены. Попроси, может юзер может вычислить опцию, при которой появляется проблема.

**Comment by evgeniy-ADG** [comment]
написал

**Comment by vgavrish** [comment]
@Alex-302 
пишет:
Когда в Антитрекинге отключен "блокировать сторонние куки-файлы" страница нормально открывается.

**Comment by Alex-302** [comment]
@vgavrish 
Не повторяется. Можешь у себя глянуть?
Какие фильтры включены?

**Comment by vozersky** [comment]
с последней бетой нормально логинится с запрещенными не только сторонними но и основными куки

**Comment by vgavrish** [comment]
У меня тоже на последней все ок
попросили пользователя обновится

**Comment by vgavrish** [comment]
Понимаете, я не хочу устанавливать бета-версию. А отключить навсегда антитрекинг невозможно.Помогает только отключение антитрекинга.

**Comment by vozersky** [comment]
Посоветовал исключить из АТ все потенциально причастные к поломке авторизации домены, помогло правило @@||trade.aliexpress.com$stealth

Однако сегодня пришел апдейт от юзера, проливающий свет на истинный источник проблемы:
"А знаете, у меня в браузере установлено приложение Aliexpress Seller Check. Удалил его, страница тоже нормально открывается, без правила в антибаннере."

**Comment by Alex-302** [comment]
@vozersky 
давай добавим наверное.

**Comment by Alex-302** [comment]
Передай на проверку такое
@@||trade.aliexpress.com$stealth,domain=aliexpress.com
чтоб только в пределах сайта исключить.

**Comment by vgavrish** [comment]
написала

**Comment by vgavrish** [comment]
@Alex-302 
"Я добавил правило - @@||trade.aliexpress.com$stealth, страница нормально открывается."

**Comment by vozersky** [comment]
@vgavrish  просьба же была попробовать @@||trade.aliexpress.com$stealth,domain=aliexpress.com

**Comment by vgavrish** [comment]
да, точно, звиняюсь

пользователь отписал - "С этим правилом не работает"
я так поняла вместе с расширением Aliexpress Seller Check.

**Comment by Alex-302** [comment]
добавил в англ
@@||trade.aliexpress.com$stealth
