### ISSUE TITLE
marktplaats.nl *Cookies*

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2372]
http://www.marktplaats.nl/

![788](https://cloud.githubusercontent.com/assets/19608513/16191699/3d60fd02-36ee-11e6-8113-3493eb7dac2b.png)

**Comment by thislife81** [comment]
Remove this cookie plz

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
marktplaats.nl#%#AG_onLoad(function() { var form = document.forms['track-accept']; if (form) { form.submit(); } });

```
