### ISSUE TITLE
Question about vk.com blocking

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#23739]
[https://vk.com/feed](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fvk.com%2Ffeed)
### Comment
Username: @pdkpv
> В ленте новостей ВК блокирую помощником блок "Возможные друзья", но он появляется после перезагрузки страницы. Попробовал обновить страницу через Ctrl+F5 - блок всё равно появляется.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/WgVimUX.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 6.4.1675.4625
Browser: | Google Chrome, версия 71.0.3554.2, dev (64 бит)
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters
Filters: | AdGuard Russian,<br>AdGuard Base,<br>AdGuard Spyware,<br>AdGuard Social Media,<br>AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>(Obsolete) Anti-Adblock Killer | Reek
Other extensions used: | ESET Internet Security 11.2.63.0

_Originally posted by @adguard-bot in https://github.com/AdguardTeam/AdguardFilters/issues/22351#issuecomment-426202978_

**Comment by BlazDT** [comment]
Working fine here (only showed up after switching from English to Russian):
`vk.com##.feed_friends_recomm`

**Comment by pdkpv** [comment]
@BlazDT thanks, the rule worked)
@Alex-302 правило помогло)

**Comment by Alex-302** [comment]
Добавил в фильтр раздражителей, т.к. не впервые жалуются.
