### ISSUE TITLE
http://www.sueddeutsche.de - ads, annoyance, placeholders

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2375]
http://www.sueddeutsche.de/bayern/riedenburgbad-abbach-passagiere-muessen-von-donau-schiff-gerettet-werden-1.3040583

![image](https://cloud.githubusercontent.com/assets/15856304/16195625/330faab4-3703-11e6-8c05-3b3fb6fe509a.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.86.71 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.35 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.27 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.89 Enabled=YES
ID=6 Name="German filter" Version=1.0.25.82 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.63 Enabled=YES
1317936

**Comment by Alex-302** [comment]
@evgeniy-ADG 
уточни у юзера, если обновить вкладку, баннер и остатки пропадают или нет.

**Comment by evgeniy-ADG** [comment]
я повторял, не помню. ща проверю еще раз.

**Comment by Alex-302** [comment]
у меня странное поведение - остатки пропадают после обновления вкладки.

**Comment by evgeniy-ADG** [comment]
Я проверял на миниайпеде 2. Почему-то не пропадают, фильтры новые, все ок... =\

**Comment by Alex-302** [comment]
Эта реклама блокируется немецким фильтром(в нормальных браузерах). Можешь включить только немецкий фильтр, повторить проблему и отправить лог(там будет файл filter.gz, в нем правила, которые переварил Адгард) в поддержку, а filter.gz выложить сюда? С ним думаю повторится, попробую потерявшиеся правила найти.

**Comment by evgeniy-ADG** [comment]
[filter.gz](https://github.com/AdguardTeam/AdguardFilters/files/331011/filter.gz)
![image](https://cloud.githubusercontent.com/assets/15856304/16324334/320a914a-39bc-11e6-9f56-136a27755176.png)

**Comment by Alex-302** [comment]
try
`sueddeutsche.de###iqd_mainAd`
or
`sueddeutsche.de##.ad`

**Comment by evgeniy-ADG** [comment]
sueddeutsche.de###iqd_mainAd - helped with side banners, but the one on top still persists
sueddeutsche.de##.ad - did the same thing

this ad still appears
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16343630/e742cc24-3a40-11e6-93a9-d3ce3fc44dd5.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
даже не представляю, почему при добавлении обоих правил такое поведение. Запили плиз в иосном разделе вопрос.
Первое правило только верхний баннер затрагивает. Явно косяк где-то.
