### ISSUE TITLE
Issue with an Adguard French Filter / uBO

### ISSUE THREAD

**Issue by StanGets** [AdguardTeam/AdguardFilters#23757]
Hi,

Running _**Adguard French filter**_ on _uBlock Origin_ v1.17.0 / _Firefox_ 52.0.3 (x64)
https://filters.adtidy.org/extension/chromium/filters/16.txt

```
Adguard French filter ! Version: 2.0.7.36
TimeUpdated: 2018-10-11T15:06:53+00:00
```

Problematic filter : `orange.fr##.o_r_notchanged`
Issue encountered at https://programme-tv.orange.fr/
Issue description : TV programs and thumbnails do not display at all
Issue solution : Added `#@#.o_r_notchanged` to uBO / My filters

Thanks

**Comment by BlazDT** [comment]
Thank you, modified rule.
