### ISSUE TITLE
filmizlesene.com.tr

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2378]
**Banner on this site**: : http://www.filmizlesene.com.tr/ayna-4-3.html

**Screenshot**: 
![q](https://cloud.githubusercontent.com/assets/19608513/16205691/9680174e-372d-11e6-9e4c-19222e582999.png)

**Adguard version**: 2.3.8

**Filters list**: 
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
||filmizlesene.com.tr/640x45
