### ISSUE TITLE
trend.az

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2379]
**Missed ads**: http://www.trend.az/

**Screenshot**: 
![q](https://cloud.githubusercontent.com/assets/19608513/16209386/7665ecf6-373f-11e6-83a7-e5601256fd82.png)

**Adguard version**: 2.3.8

**Filters list**: 
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
added
trend.az###header > div > div[id^="TREND_slot"]
for user filter(dangerous rule)
trend.az##div[class="row mbm hidden-sm hidden-xs hidden-mobile"]
