### ISSUE TITLE
oxu.az

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2380]
**Missed ads**: http://ru.oxu.az/sport/136459

**Screenshot**: 
![nb](https://cloud.githubusercontent.com/assets/19608513/16209863/adc00a18-3741-11e6-90dd-f055c5fa2f6f.png)

**Adguard version**: 2.3.8

**Filters list**: 
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
oxu.az##.load-bnr
oxu.az##.header-bnr-container
