### ISSUE TITLE
haqqin.az

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2381]
**Banner**: http://haqqin.az/news/73163

**Screenshot**: 
![yt](https://cloud.githubusercontent.com/assets/19608513/16210113/06a5c2e8-3743-11e6-8060-f1b418118fc8.png)

**Adguard version**: 2.3.8

**Filters list**: 
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by thislife81** [comment]
Please remove this.

**Comment by Alex-302** [comment]
Added to Russian filter
```
haqqin.az##.topbanners
```
