### ISSUE TITLE
milli.az

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2382]
**Site**: http://news.milli.az/politics/445060.html

**Screenshot**: 
![aa](https://cloud.githubusercontent.com/assets/19608513/16210587/78004ad8-3745-11e6-9f4c-175a6a2bc7ec.png)

![ab](https://cloud.githubusercontent.com/assets/19608513/16210593/81b124a8-3745-11e6-954d-d9e119935f2e.png)

**Adguard version**: 2.3.8

**Filters list**: 
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by thislife81** [comment]
Remove these ads

**Comment by Alex-302** [comment]
Added to English filter
```
||qafqazinfo.az/milliaz.html
milli.az##.ad-back
```
Added to Social filter
```
milli.az##.like-holder
```
