### ISSUE TITLE
bmoviesfree.ru [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#23837]
**Site**: https://bmoviesfree.ru/film/blindspot-season-4-23895033/watching.html?ep=1872173

**Issue**: Please remove the pop-up and the fake link as seen in the screenshot.

**Screenshot**: http://prntscr.com/l5lh93

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 69.0.3497.100 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.11 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Spam 404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by bogachenko** [comment]
`bmoviesfree.ru##.btn-primary.btn-lg.btn.full`
`bmoviesfree.ru^$popup`
