### ISSUE TITLE
musavat.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2384]
**Site**: http://musavat.com/

**Screenshots**: 
![1_1](https://cloud.githubusercontent.com/assets/19608513/16211280/3c7ae208-3749-11e6-831a-e15e395677e0.png)

![1_2](https://cloud.githubusercontent.com/assets/19608513/16211769/4fa244ae-374c-11e6-8a8a-42ed106c90d9.png)

![1_3](https://cloud.githubusercontent.com/assets/19608513/16211908/49166d62-374d-11e6-8486-823d5b15d210.png)

![55](https://cloud.githubusercontent.com/assets/19608513/16212101/44317e58-374e-11e6-8b85-bb5006d264f9.png)

**Site**: http://musavat.com/news/dunya/rustavide-18-mezun-zeherlenerek-xestexanaya-yerleshdirilib_356980.html

**Screenshots**: 
![2_1](https://cloud.githubusercontent.com/assets/19608513/16211304/5cdab7f8-3749-11e6-9e36-6e822e57ea8e.png)

![2_2](https://cloud.githubusercontent.com/assets/19608513/16211309/65b7633a-3749-11e6-8177-44ce41eb7247.png)

![2_3](https://cloud.githubusercontent.com/assets/19608513/16211314/71443e9e-3749-11e6-981a-3f46c420b5e9.png)

**Adguard version**: 2.3.8

**Filters list**: 
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
musavat.com##div[style^="width: 222px; height: 200px;"]
musavat.com##div[style="margin:6px 0px 0px 0px;width: 502px;display:table"] > iframe
musavat.com##.fancybox-wrap
