### ISSUE TITLE
anspress.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2385]
**Site**: http://www.anspress.com/

**Screenshot**: 
![1](https://cloud.githubusercontent.com/assets/19608513/16220064/27d10536-3793-11e6-9228-31282ec004cf.png)

**Adguard version**: 2.3.8

**Filters list**: 
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to English filter
```
anspress.com##.ans-adv-block
```
