### ISSUE TITLE
xeberle.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2386]
**Site**: http://xeberle.com/

**Screenshot**: 
![aa](https://cloud.githubusercontent.com/assets/19608513/16220369/25746a74-3795-11e6-989b-267ce8aceb8e.png)

At the botom of page: 
![ab](https://cloud.githubusercontent.com/assets/19608513/16220380/32b34598-3795-11e6-869e-2a30444340d7.png)

**Adguard version**: 2.3.8

**Filters list**: 
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to social filter
```
xeberle.com##.momizat-social_counter
```
to annoyances
```
xeberle.com##.base-box.mom_box_sc.mom_callout
```
