### ISSUE TITLE
naked-science.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#23881]
[https://naked-science.ru/article/sci/uchenye-poluchili-potomstvo-ot-dvuh](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://naked-science.ru/article/sci/uchenye-poluchili-potomstvo-ot-dvuh)

 **1.** Излишняя блокировка. Русский фильтр, правило: `||realbig.media^$third-party`
 Исключение: `||realbig.media^$third-party,domain=~naked-science.ru`

<details><summary>Screenshot's:</summary>

![2018 10 14-1](https://user-images.githubusercontent.com/17948007/46910087-21b5f280-cf47-11e8-8729-b1bf0c6f4624.png)
----------
![2018 10 13-1](https://user-images.githubusercontent.com/17948007/46910059-5f664b80-cf46-11e8-9303-5dd67713cb2e.png)
</details><br/>

 **2.** Остатки: `naked-science.ru##.pane-node-text-top`

<details><summary>Screenshot:</summary>

![2018 10 14-2](https://user-images.githubusercontent.com/17948007/46915327-d89b8800-cfb2-11e8-83c2-cc3508c795f7.png)
</details><br/>

 **3.** Остатки: `naked-science.ru##[class*="pane-advertising-node"]`
Почему-то `naked-science.ru##[class^="pane-advertising-node"]` не сработал. Почему?

<details><summary>Screenshot:</summary>

![2018 10 14-3](https://user-images.githubusercontent.com/17948007/46915381-a8a0b480-cfb3-11e8-8736-91bf28c9bc12.png)
</details><br/>

 **4.** После блокировки рекламы, перед блоком комментариев остаётся много отступов. Поэтому убираем отступ у блока комментариев: `naked-science.ru#$#.section-comments { margin-top: 0px!important; }`

<details><summary>Screenshot:</summary>

![2018 10 14-4](https://user-images.githubusercontent.com/17948007/46915430-5e6c0300-cfb4-11e8-87b4-321d4ab3ff59.png)
</details><br/>

 **5.** Долго грузится недоблокированное с **ad.outstream.today** , поэтому: `||ad.outstream.today/outstream/mwayss_invocation.min.js` или, если это рекламный домен, то: `||ad.outstream.today^$third-party`

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v2.10.11
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Баннер реализован с использованием рекламной сети. Доблокировал.

4. Это ж дизайн.
5. Заблокировал.
