### ISSUE TITLE
iddaa.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2389]
**Site**: http://www.iddaa.com/futbol-en-cok-oynanan-maclar/

**Screenshot**: 
![q](https://cloud.githubusercontent.com/assets/19608513/16221772/38e74894-379d-11e6-9180-e64de8ca239a.png)

![q1](https://cloud.githubusercontent.com/assets/19608513/16221777/3f223eda-379d-11e6-9ac8-06075f58031f.png)

**Adguard version**: 2.3.8

**Filters list**: 
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List
+11)ABPVN List

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
If you don't speak Vietnameseб you should to disable this filter.
Added to Turkish filter
```
iddaa.com##.adv728p-90
```

**Comment by thislife81** [comment]
Great, it worked :+1:

**Comment by PentagramTr** [comment]
@Alex-302 

Please hide this ad.
https://mobil.iddaa.com/

<details><summary>Screenshot:</summary>

![dl3 pushbulletusercontent com](https://user-images.githubusercontent.com/34379403/60773074-6d797f00-a108-11e9-857a-94565aa88a6a.png)


</details>

**Comment by Alex-302** [comment]
done
