### ISSUE TITLE
Ad preview is not available in Google Adwords

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2390]
В Гугл Эдвордс есть графические объявления. Есть интерфейс их настройки. Когда их настраиваешь, есть предпросмотр объявлений. Так вот, этот самый предпросмотр не отображается. Браузер Firefox.

![image](https://cloud.githubusercontent.com/assets/15856304/16226022/379ffe80-37b2-11e6-8fb4-130cc2195f56.png)

А должно быть:
![image](https://cloud.githubusercontent.com/assets/15856304/16226027/41efd856-37b2-11e6-80d0-20ba85e1e792.png)

тикет 1315357 20 мая 6-30

**Comment by Alex-302** [comment]
Передай на проверку:
```
@@|http://adsense.google.$document,~third-party
@@|http://adwords.google.$document,~third-party
@@|http://google.*/adsense$document,~third-party
@@|http://google.*/adwords$document,~third-party
@@|http://www.google.*/adsense$document,~third-party
@@|http://www.google.*/adwords$document,~third-party
@@|https://adsense.google.$document,~third-party
@@|https://adwords.google.$document,~third-party
@@|https://www.google.*/adsense$document,~third-party
@@|https://www.google.*/adwords$document,~third-party
```
Не помогут - нужен будет доступ.
