### ISSUE TITLE
filmhizmeti.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2391]
**Site**: http://filmhizmeti.com/uyumsuz-3-izle-yandas-bolum-1-hd-full-turkce-dublaj-2016.html

**Screenshot**: 
![jh](https://cloud.githubusercontent.com/assets/19608513/16228782/bce9960a-37c1-11e6-9c84-28b89a5fdf44.png)

**Adguard version**: 2.3.8

**Filters list**: 
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
filmhizmeti.com#$##Movie-video { display: inline!important; }
filmhizmeti.com#$##Video-Oncesi { display: none!important; }
```
