### ISSUE TITLE
fullhdfilmizlesene.org

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2392]
**Site**: http://www.fullhdfilmizlesene.org/ When click the button of "Filmi izle", opens a new page

**Screenshot**: 
![yj](https://cloud.githubusercontent.com/assets/19608513/16229040/494631d4-37c3-11e6-9c99-ae6349e7532b.png)

**Adguard version**: 2.3.8

**Filters list**: 
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
fullhdfilmizlesene.org#%#AG_onLoad(function() { window.openNewTab = function() {}; } );
```

**Comment by thislife81** [comment]
This issue is shown again, Plz fix it.

**Comment by Alex-302** [comment]
I can't reproduce. Which Adguard version are you using?
