### ISSUE TITLE
fullfilmizlesin.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2393]
**Site**: http://www.fullfilmizlesin.com/

**Screenshot**: Remove this banner
![8](https://cloud.githubusercontent.com/assets/19608513/16229558/ff64505c-37c5-11e6-9d00-fab469fdcb61.png)

**Adguard version**: 2.3.8

**Filters list**: 
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to  filter
```
fullfilmizlesin.com###banner
```

**Comment by Alex-302** [comment]
Added to Turkish filter
```
fullfilmizlesin.com###banner
```
