### ISSUE TITLE
onlinefilm.co

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2394]
**Site**: http://onlinefilm.co/

**Screenshot**: Remove this white place
![1](https://cloud.githubusercontent.com/assets/19608513/16229832/2920d978-37c7-11e6-8e00-2ec43476fb29.png)

Click here: http://onlinefilm.co/friday-the-13th-the-final-chapter-turkce-dublaj-izle.html
![2](https://cloud.githubusercontent.com/assets/19608513/16229871/6609ac84-37c7-11e6-9645-60c1f94cabc9.png)

At the bottom of page:
![3](https://cloud.githubusercontent.com/assets/19608513/16229897/83b778ce-37c7-11e6-8821-bdae65d5f351.png)

**Adguard version**: 2.3.8

**Filters list**: 
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
onlinefilm.co#$#.tab-reklam { display: none!important; }
onlinefilm.co#$#.tab-embed { display: inline!important; }
onlinefilm.co###sag-facebook-tablo
