### ISSUE TITLE
sinemapol.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2395]
**Site**: http://sinemapol.com/

**Screenshot**: 1) Remove this annoyance
![aa](https://cloud.githubusercontent.com/assets/19608513/16230038/2d5634e2-37c8-11e6-8627-af70340c2e2a.png)

2)Remove this banner
![ab](https://cloud.githubusercontent.com/assets/19608513/16230044/3c6321fc-37c8-11e6-9e06-71e07a389817.png)

3)There is a link in the background: When click the background, opens a new site
![ac](https://cloud.githubusercontent.com/assets/19608513/16230114/963e17c2-37c8-11e6-8fb1-304e1326bf78.png)

4)Ad before video in here: http://sinemapol.com/warcraft-turkce-altyazili-izle/
![ad](https://cloud.githubusercontent.com/assets/19608513/16230210/fdf799ce-37c8-11e6-8d9c-d51d8f18153d.png)

**Adguard version**: 2.3.8

**Filters list**: 
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
sinemapol.com#$##video { display: inline!important; }
sinemapol.com#$##video-oncesi { display: none!important; }
sinemapol.com##.textwidget > a[rel="”nofollow”"] > img
sinemapol.com###backgroundadd
```
