### ISSUE TITLE
inndirmedenfilmizle.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2396]
**Site**: http://www.inndirmedenfilmizle.com/partisan-2015-turkce-altyazili-izle.html

**Screenshot**:  Ad before video
![qw](https://cloud.githubusercontent.com/assets/19608513/16230928/828fe760-37cc-11e6-86a0-52d14265bc02.png)

**Adguard version**: 2.3.8

**Filters list**: 
1)English filter
2)Spyware filter
3)Social media filter
4)Annoyances filter
5)Russian filter
6)Turkish filter
7)RU AdList
8)EasyPrivacy
9)RU AdList: BitBlock
10)Fanboy's Enhanced Tracking List

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
inndirmedenfilmizle.com###pageskin
||inndirmedenfilmizle.com/_pois-reklam/*.mp4$mp4
inndirmedenfilmizle.com#%#AG_onLoad(function() { setTimeout(function() { jwplayer("psreklamv").remove(); $('#psreklam').hide(); $('#video').show(); }, 3000); });

```

**Comment by thislife81** [comment]
Please remove these.
![partisan izle partisan turkce altyazili izle partisan 2015 - full izle hd izle turkce dublaj izle 720p izle tek parca izle filmi](https://cloud.githubusercontent.com/assets/19608513/18517028/09633e96-7aac-11e6-8e60-6c228cbf54ee.jpg)

**Comment by Alex-302** [comment]
added
inndirmedenfilmizle.com##.adv-336

**Comment by thislife81** [comment]
Please remove this too.  inndirmedenfilmizle.com###footerkapatlink
![indirmeden](https://cloud.githubusercontent.com/assets/19608513/18554038/f7230220-7b73-11e6-9ead-35e9254d74fd.jpg)

**Comment by Alex-302** [comment]
Added to Turkish filter
```
inndirmedenfilmizle.com###toolbar
```
