### ISSUE TITLE
academia.edu

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2397]
**Current behaviour**: Document preview is never ending

<details>
Adguard on:
![screen shot 2016-06-21 at 4 57 31 pm](https://cloud.githubusercontent.com/assets/14153331/16232059/b53b407e-37d1-11e6-8b35-7bd0eecfb60e.png)

Adguard off:
![screen shot 2016-06-21 at 4 55 04 pm](https://cloud.githubusercontent.com/assets/14153331/16232082/ce8ede00-37d1-11e6-94b7-c5a8e9e6d003.png)

</details>

```

**Steps to reproduce the problem**:

* Login at academia.edu with academia_ttttt@mail.ru/test123test
* Go to  https://www.academia.edu/25720830/Suppression_of_combustion_noise_in_gas_turbine_combustors
```

**Comment by Alex-302** [comment]
Where is the **Filters list**? It is necessarily.
