### ISSUE TITLE
swinglife.ru [NSFW]

### ISSUE THREAD

**Issue by shaurmanchic** [AdguardTeam/AdguardFilters#2398]
При подгрузке подолнительных элементов теряется яркость контента.
<details>
![](https://s32.postimg.org/69ou4f701/image.jpg)
</details>
<details>
![](https://s32.postimg.org/bz52oqd69/image.jpg)
</details>
<details>
![](https://s32.postimg.org/bwl71w9ip/image.jpg)
</details>
Залогинится тестовым аккаунтом: логин - hristaf, пароль Kraslava_1985.
Альбомы - Фото - фотографии юзеров портала - последние добавленные - Еще. Каждые последующие подгрузки будут бледнее.
AppVersion: 6.0.226.1108
Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
English filter Url: http://adguard.com/ru/filter-rules.html?id=2
Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
Filter for useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
Os version: Microsoft Windows NT 10.0.10586.0
Наблюдается в Chrome и Firefox.

**Comment by vozersky** [comment]
это помощник ломает
там кривой скрипт, и мы в него инжектимся, временное решение для юзера - нужно выключить помощник в настройках

**Comment by Alex-302** [comment]
Добавил в русский
@@||swinglife.ru/*&ajax_$document
