### ISSUE TITLE
temperatur.nu

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2399]
**Description**: temperatur.nu

<details>

![image1](https://cloud.githubusercontent.com/assets/14153331/16241281/a8352240-37f5-11e6-851c-c4a8e90d8697.png)

**Filters list**:
![filters](https://cloud.githubusercontent.com/assets/14153331/16241275/a26c032e-37f5-11e6-8108-cadd9206fad6.png)

</details>
**Operating system**: Windows/macOS

**Browser**: Chrome/Safari/Edge

**Comment by Alex-302** [comment]
added to annoyances
temperatur.nu###infobar
