### ISSUE TITLE
[Windows] www.bild.de - tracking

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#2400]
**Description**: Tracking

Screenshot: 
![](http://i.imgur.com/DQv9bHI.png)
http://www.bild.de/sport/fussball/em-2016/ward-und-hector-schiessen-linienrichter-ab-46417108.bild.html

**Adguard version**: 6.0.226.1108

**Operating system**: Windows 10

**Browser**: Chrome

**Comment by Alex-302** [comment]
added
||bild.rtrp13n.de/tracking/
