### ISSUE TITLE
Adguard 2.6 interfers with Google Apps via HTTPS filtering

### ISSUE THREAD

**Issue by MartinGuayOTT** [AdguardTeam/AdguardFilters#2401]
**Description**:
Adguard 2.6 interfers with Google Apps via HTTPS filtering
**Current behaviour**: Tell us what happens
Google Photos will not do the picture back up and will list "Storage Unavailable" turning Adguard HTTPS filtering OFF fixes the issue. This is also true for Hangouts conversation and for people who uses Google Voice number.

**Comment by TPS** [comment]
Perhaps related to https://github.com/AdguardTeam/AdguardForAndroid/issues/549 or https://github.com/AdguardTeam/AdguardForAndroid/issues/597

Anyway, @MartinGuayOTT, I think you should post with far more detail @ https://github.com/AdguardTeam/AdguardForAndroid/issues, as it's probably more the app problem than the filters.…

**Comment by Alex-302** [comment]
@MartinGuayOTT 
we need step-by-step description with screenshots for each step, filters list and log with a time when you got the error message.

**Comment by Alex-302** [comment]
@MartinGuayOTT 
you can also check with all disabled filters.
