### ISSUE TITLE
[iOS] Missed Ad - korrespondent.net

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2403]
Фильтры Adguard, обновленные. Рекламный баннер повторился.

www.korrespondent.net

![image1](https://cloud.githubusercontent.com/assets/16462533/16259775/d8b87b84-386c-11e6-8fd0-13ed8f746fee.PNG)

**Comment by Alex-302** [comment]
Не повторяется никак.

**Comment by Alex-302** [comment]
Если есть возможность повторить в Сафани и соотв. юзерагентом - дай знать.

**Comment by Serzh-SUP** [comment]
@Alex-302 
А на чем проверяется? на айпаде?

**Comment by Alex-302** [comment]
Сафари в режиме отладки и собственно айпад

**Comment by Alex-302** [comment]
Пусть попробует выключить вс фильтры и включить только русский и английский. Оно же постоянно у него выскакивает?

**Comment by Serzh-SUP** [comment]
Больше не повторяется.
