### ISSUE TITLE
Pole-Emploi.fr - Pages won't load (AdGuard Annoyances filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#24040]
### Affected site:
`pole-emploi.fr`

### Issue:
Several subpages are prevented from loading.

### Example:
`https://candidat.pole-emploi.fr/offres/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
AdGuard Annoyances filter

### Problem rule:
`-cookie-law-popup.`

### Possible fix:
`@@-cookie-law-popup.$domain=pole-emploi.fr`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.1.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by AdamWr** [comment]
Fixed.
Thank you.
