### ISSUE TITLE
mamavika.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2404]
**Description**:
http://mamavika.com/detsk-zdorov/novorozhdennyie/margantsovka-dlya-kupaniya-novorozhdennyih.html

Screenshot:
http://prntscr.com/bjgtmr
http://prntscr.com/bjgsz0

**Operating system**: Windows/macOS/iOS

**Browser**:Chrome/Safari

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр(1) и соц фильтр(2)
```
mamavika.com##div[id^="tgroup_"]
mamavika.com##body > div[class^="spu-"]
```
