### ISSUE TITLE
theargus.co.uk

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2405]
**Site**: http://www.theargus.co.uk/

**Screenshot**:  Turn off adblock

![j](https://cloud.githubusercontent.com/assets/19608513/16260261/49219a7a-386f-11e6-83c2-5d776e97d23c.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
theargus.co.uk##.ad-blocker-warning
```
