### ISSUE TITLE
AdGuard Social Media filter не блокирует соц. кнопки на otvet.mail.ru

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#24059]
На страницах вопросов https://otvet.mail.ru/ не блокируются эти кнопки с недавнего времени.
![image](https://user-images.githubusercontent.com/19754243/47191806-b191dd00-d349-11e8-9dd2-20165b0cab12.png)

**Comment by krystian3w** [comment]
This is only links not wigdets, such links do not block.

https://kb.adguard.com/en/general/adguard-ad-filters#social

> If you do not like numerous **«Like»** and **«Tweet»** buttons on all the popular websites on the Internet, subscribe to this filter, and you will not see them anymore.
