### ISSUE TITLE
http://filin.tv/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2407]
**Description**:
http://filin.tv/

Screenshot:
http://prntscr.com/bjhvim

**Steps to reproduce the problem**:
При нажатии на выбор какого-либо фильма, идет перенаправление на другие сайты.

**Browser**: Chrome

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||static.filin.tv/c/
```
