### ISSUE TITLE
https://www.dixons.nl/ - false blocking by annoyances filter

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2408]
**Description**: https://www.dixons.nl/

**Current behaviour**: We block the slider

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16265682/73ad8a78-3889-11e6-8ddb-0bf3ef7f0972.png)

</details>

**Expected behaviour**: Should not block the slider...

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16265701/8818403e-3889-11e6-908e-4a2f09061bd3.png)

</details>

Works fine when Annoyances is disabled

**Comment by Alex-302** [comment]
@@||dixons.nl/catalog/view/theme/dixons/assets/js/vendor/cookieconsent2/build/cookieconsent.min.js

**Comment by worldsdream** [comment]
Confirmed working. Please add to dutch filterlist. Thanks.

**Comment by Alex-302** [comment]
http://imagizer.imageshack.com/img924/4080/2hsT6g.png
