### ISSUE TITLE
"Cookiebot" rule creates some issues (AdGuard Annoyances filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#24090]
### Issue:
Some third party elements are blocked.

### Example:
`https://www.refinery29.com/en-gb/2018/10/214421/emma-watson-trans-rights/`
(Instagram images are blocked)

### Problem filter:
AdGuard Annoyances filter

### Problem rule:
`||cookiebot.com^$third-party`

### Thoughts:
Desired behaviour, or not?
The rule might rather belong in a dedicated "privacy" filter perhaps?

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.1.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by Alex-302** [comment]
Fixed

**Comment by THEtomaso** [comment]
@Alex-302:
The `refinery29.com` thing was just one random example.
IMO, the whole 'cookiebot' rule should be moved from 'AdGuard Annoyances filter' and into a privacy filter instead (e.g. 'Adguard Spyware Filters').

..and speaking of moving things:
Could you please move this exception into the correct filter?:
`https://github.com/AdguardTeam/AdguardFilters/issues/24203/`
You've placed it in the wrong one!

**Comment by Alex-302** [comment]
> The refinery29.com thing was just one random example.

I need few examples.
