### ISSUE TITLE
can't login through bungie.net

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2410]
Destiny Item Manager https://chrome.google.com/webstore/detail/destiny-item-manager/apghicjnekejhfancbkahkhdckhdagna?hl=en
Tower Ghost https://chrome.google.com/webstore/detail/tower-ghost-for-destiny/gdjndlpockopgjbonnfdmkcmkcikjhge?hl=en

Both will not work with Adguard enabled.
Both require me to be logged into Bungie.net and I can only do that
with Adguard disabled. 

user id 1121001

**Comment by evgeniy-ADG** [comment]
Попросили детальное описание и сркины, так как у нас не повторилось должным образом

**Comment by Alex-302** [comment]
ок, ждём
