### ISSUE TITLE
Duplicate Cleaner

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2411]
**Description**:
Не блокируется реклама в приложении Duplicate Cleaner из Магазина
https://www.microsoft.com/en-sg/store/apps/duplicate-cleaner/9nblggh4nw1f
WFP включен

Screenshot:
http://prntscr.com/bjz70z
http://prntscr.com/bjz77u
http://prntscr.com/bjz7bu

**Filters list**: Russian, English, German

**Operating system**: windows 10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня чисто. Если у тебя есть реклама - дай плиз доступ. Или юзера попроси.

**Comment by vgavrish** [comment]
Написала про удаленный

**Comment by vgavrish** [comment]
Проблема больше не наблюдается:)
