### ISSUE TITLE
http://ubr.ua - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2412]
http://ubr.ua/market/transport/ukrainskie-prokatchiki-budut-sdavat-avto-pochasovo-409790

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16302433/d70c1d80-3953-11e6-9152-7f2c2ccae94d.png)

</details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.87.32 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.42 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.36 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.35.53 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.69 Enabled=YES
ID=108 Name="EasyList Hebrew" Version=1.0.2.88 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.60.47 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.57.5 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.57.32 Enabled=YES
1305030

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||adpartner.pro^$third-party
```
