### ISSUE TITLE
adf.ly

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#2414]
Reproduce this on os x:
![screenshot 2016-06-23 15 31 45](https://cloud.githubusercontent.com/assets/17472907/16303253/680b5432-3958-11e6-9e25-9aefb51e71fc.png)

![original](https://cloud.githubusercontent.com/assets/17472907/16303268/79f7432c-3958-11e6-8b6e-303d95824caa.jpg)

**Comment by Alex-302** [comment]
Пример ссылки нужен. Абсолютно всегда.
С этой всё норм http://adf.ly/1ZevYP

**Comment by vozersky** [comment]
на главной же :)

**Comment by worldsdream** [comment]
On iOS it does count down from 5. At 1, it shows a message that we are using an adblocker. When clicking ok, it starts again from 5.

**Comment by ameshkov** [comment]
@Alex-302 there's also an issue with Android:
https://github.com/AdguardTeam/AdguardForAndroid/issues/703

Nothing serious on desktop, but on mobile it prevents users from going further.

**Comment by Alex-302** [comment]
Added to English filter
```
adf.ly#@##bottom
adf.ly#@#iframe
@@||adf.ly^$content
```
But I can't block popunder.

**Comment by TPS** [comment]
Does anything in https://github.com/reek/anti-adblock-killer/issues/1497 help?
