### ISSUE TITLE
Проблемы на разных сайтах

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#24148]
В очередной раз пробежался по закладкам и не только, и вот что обнаружил:
- Из за фильтра EasyList тут https://putlockerhd.co/watch?v=Thor_2011 прячется плеер..
- https://oload.icu/embed/Qwpc--7vfZ0 при клике в любом месте часто открываются всякие окна.
- http://4pda.ru/forum/index.php?showuser=1277 на странице пользователя, если пообновлять страницу несколько раз, над шапкой появляется баннер. (удалось добится появления только после логина)
- http://www.igropoisk.com/ здесь при первом входе (очистите куки) выскакивает реклама походу которая притворяется гугл каптчой.
- http://pvpru.com/board/ рекланые баннеры под шапкой..
- https://ru.dll-files.com/shell32.dll.html если прокрутить в низ к файлам, то внизу прилипнет довольно большая табличка с их программой без возможности закрытия. Слишком уж усердное впаривание, не знаю может стоит в фильтр раздражителей занести.. А еще после клика по "Скачать" напротив любого из файлов, ничего не происходит.. не стал разбираться из за какого фильтра проблема.
- https://biqle.ru/watch/320885077_456239036 из за какого-то фильтра не грузится плеер _@@||daxab.com/player^$domain=biqle.ru,third-party_
- https://www.cy-pr.com/a/goldenshara.org рекламный баннер под шапкой.
- https://www.cracks4win.com/ баннер в шапке
- http://fastpic.ru/view/77/2018/1016/4abdee02e49ba81bc35fb7c8021f3964.jpg.html над скрином баннер
- http://rustorka.club/forum/index.php в шапке баннера не видно, но если кликнуть...
- Ну и под конец сайт о котором не раз писал, который активно борется с блокираторами pb.wtf В данный момент тут 
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/19754243/47260330-da38e480-d4b9-11e8-8afe-41519d1085b7.png)</details><br/>
на странице поиска https://pb.wtf/tracker/#results
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/19754243/47260338-f8064980-d4b9-11e8-8f22-9778ebe848e8.png)</details><br/>
На странице раздачи https://pb.wtf/topic/280509/
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/19754243/47260345-1bc98f80-d4ba-11e8-9f13-9e9fc1b95da9.png)</details><br/>
Ниже громадная реклама которая притворяется комментом (может встречаться несколько раз если много коментариев)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/19754243/47260352-3a2f8b00-d4ba-11e8-80dd-e5ec2de8968f.png)</details><br/>
Плюс дублируется такой вот псевдо комментарий
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/19754243/47260363-88448e80-d4ba-11e8-884b-2140f026a58d.png)</details><br/>

Фильтры которые использую
EasyList, RuAdList, (Adguard - Rus, Eng, Social, spyware, annoyances)

**Comment by Alex-302** [comment]
1 - не повторяется. Убрал кликандер;
2 - поправил в 1;
3, 4 - поправил;
5 - не вижу;
6 - попап убрал. Загрузка работает;
7 - не повторяется;
8, 9, 10 - поправил.

**Comment by Alex-302** [comment]
pb.wtf быстро адаптируются

**Comment by Smorvel** [comment]
6 - загрузка не работает если включен AdGuard Spyware filter (обычный клик не работает).
В самом низу я написал все свои фильтры..

**Comment by Smorvel** [comment]
@Alex-302 А я могу сам добавлять правила в adguard russian filter? Я бы поборолся с pb.wtf :)

**Comment by Alex-302** [comment]
Пулл-реквесты можно слать.

**Comment by Alex-302** [comment]
> 7 - из за фильтра RuADList

об этом лучше его автору сообщить, чтоб для всех поправил.

**Comment by Alex-302** [comment]
> 7 - из за фильтра RuADList

об этом лучше его автору сообщить, чтоб для всех поправил.
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
@Smorvel
Единственное, что я смог обнаружить из ложных срабатываний на biqle.ru, это блокировку запросов, которые появляются после установки расширения Daxab Ultimate (для Full HD). Исправлено: https://hg.adblockplus.org/ruadlist/rev/753cc611d7b9#l1.30

Если этот коммит не решает проблему, укажите пожалуйста подробный сценарий её воспроизведения и все детали конфигурации: https://forums.lanik.us/viewtopic.php?f=102&t=24280

**Comment by Smorvel** [comment]
@Alex-302 спасибо! Только что обновил все фильтры, все проблемы решены =)

@dimisa-RUAdList Ого, не ожидал... приятный сюрприз) Не знаю про расширение (не ставил), Проверил конкретно вот это правило блокирует плеер
`$third-party,popup,script,stylesheet,xmlhttprequest,domain=biqle.ru|daxab.com`
После его отключения, либо добавления этого правила в пользовательские фильтры
`@@||daxab.com/player^$domain=biqle.ru,third-party`
Плеер работает

**Comment by dimisa-RUAdList** [comment]
@Smorvel 
При тестировании дахабовские скрипты во всех случаях грузились в собственном фрейме и блокировка сторонних скриптов никак на их работу не влияла. Если в вашем случае это не так, укажите пожалуйста подробный сценарий её воспроизведения и все детали конфигурации: https://forums.lanik.us/viewtopic.php?f=102&t=24280

**Comment by Alex-302** [comment]
> UPD
> Кроме этой http://pvpru.com/board/

нужна сохранённая страница.

**Comment by Smorvel** [comment]
@Alex-302 Вот
[New zip Archive.zip](https://github.com/AdguardTeam/AdguardFilters/files/2511501/New.zip.Archive.zip)

**Comment by Alex-302** [comment]
Должен блокироваться
![image](https://user-images.githubusercontent.com/8361299/47492257-3fdbf680-d855-11e8-92a8-947f4c65f47e.png)

**Comment by Smorvel** [comment]
@Alex-302 оказалось тут тоже ruadlist виноват.. Ладно, как нибудь в другой раз гляну что там у них на форуме, и напишу про проблемы...

**Comment by dimisa-RUAdList** [comment]
У Smorvel подключен RU AdList, а поскольку противодействовать детектору адблока на этом ресурсе классическим abp-синтаксисом кроме как исключениями - нечем, там работает: `@@||pvpru.com/css/banners/300$domain=pvpru.com`. При использовании RU AdList в uBlock Origin - баннеры скрываются с помощью инжектирования стилей, которые предусмотрены версией RU AdList для этого расширения, а при использовании расширений, которые это не поддерживают - с помощью RU AdList CSS Fixes. А вот при подключении базовой (без CSS Fixes) подписки RU AdList в AdGuard получается ни то, ни сё - баннеры загружены, стили не отработали.

**Comment by Smorvel** [comment]
@Alex-302 На 4pda на страице любого пользователя снова реклама над шапкой..

**Comment by Alex-302** [comment]
@Smorvel установите AdGuard Extra.
