### ISSUE TITLE
Adguard extension affects www.gog.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2415]
I have already described the issue further here:

https://forum.adguard.com/index.php?threads/chrome-browser-extension-breaks-gog-com-even-when-protection-is-disabled.11192/

1. It does not appear to be related to any kind of filter since the error
still occurs when adblocking is entirely disabled in the extension as well
as Adguard for Windows. I have only tested it on Chrome 51 and 52, I'm
currently running Chrome 52.0.2743.41 beta-m (64-bit) - Windows 10 and it's
very much reproducible for me.

2. The error still occurs in Incognito mode. In fact, that was the easiest
way to find the extension as the culprit. If Adguard is enabled in
Inkognito mode and no other extensions are, GOG.com is still broken.
Disabled Adguard and GOG.com works fine.

The error might be difficult to reproduce once GOG's summer sale ends in 3
days, so hopefully you can track it down and squash it before that time.

As I said before: It honestly does *not *matter, *at all!*

Detailed description and screenshots <details>
I can disable absolutely every single filter and GOG.com* still remains
broken*:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16304088/9a1948e0-395c-11e6-8dd2-ee5df8c6345b.png)

</details>
GOG.com is broken in *integration mode with adblocking disabled* as well:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16304106/a93e9424-395c-11e6-8d81-dba52e5f8e5c.png)

</details>

Or in *integration mode with adblocking enabled and gog.com
<http://gog.com> whitelisted*:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/16304230/26d06aa2-395d-11e6-95e7-b6ce03adecc8.png)

</details>
Or in *standalone mode with gog.com <http://gog.com> fully excluded and all
filters disabled*:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16304126/bb5f1886-395c-11e6-8da9-31713b35a7f6.png)

</details>
As soon as the *extension is disabled from Chrome entirely* it *works fine,
with* and without *adblocking*:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16304161/e6d38268-395c-11e6-9d1c-496379901dfb.png)

</details>

Since the page layout will likely change in 46 hours, there is a limited
time for you to track down the core of this problem.

It happens persistently and reproduceably on Chrome 51 and 52 bit in 64bit
on Windows 10, even with no other extensions enabled.

It's not the filtering and it's not the Adguard windows client that's
breaking the site, it's the extension and *only *the extension and
absolutely doesn't matter in which configuration. If it's enabled in any
way, shape or form, it breaks dynamic loading of images on GOG.com
</details>
1317328

**Comment by evgeniy-ADG** [comment]
We were unable to reproduce the issue, but the customer wants you to look into it once again.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
у него главная страница ломается, или какая?

**Comment by vozersky** [comment]
Вчера обсуждалось в сап-чате же. И на форуме юзером описано. Этой страницы больше нет на gog, распродажа закончилась. При отключенной фильтрации все-равно ломалось по его словам, это не проблема фильтров.

**Comment by Alex-302** [comment]
Значит баг или конфликт.

**Comment by evgeniy-ADG** [comment]
Ну, он сильно уверен, что проблема в нас и приводит скрины, где все видно. Мне, видя скрины, и описание, над которым он изрядно постарался, сложно ему объяснять, что причина не в нас. Тем более, что он достаточно беспокойно реагирует отрицание проблемы. Ломалось при наличии расширения в браузере. Без расширения - не ломалось. Перенесите или закройте, если не актуально.

**Comment by Alex-302** [comment]
@evgeniy-ADG а почему она не может быть в нас? У него ж наверное без расширения всё нормально отображается.
Пожалуется - просите удалённый доступ, гляну что не так.

**Comment by evgeniy-ADG** [comment]
Распродажа закончилась, страницы с ней нет, как и самой проблемы. Предлагаю закрыть и переоткрыть, когда будет следующая распродажа. Конечно, если снова будет этот баг. Наверное, стоило сразу TV организовывать, сэкономили бы время ему.

**Comment by Alex-302** [comment]
Ладно, закрываю пока.
