### ISSUE TITLE
 Stealth mode is causing problems on nsfw blogs

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2417]
**Description**:  Stealth mode is causing problems for me on nsfw blogs: aifsansmystery.blogspot.in aifsansmystery.blogspot.com (Also happens on quite a few other nsfw blogs.)

**Current behaviour**: after opening blog,
when I click on 'I understand & I wish to continue'. It just loops back to same warning again and again. expected behaviour: click on 'I understand & I wish to continue' should open the blog normally.
Disabling Stealth mode fixes this

Adguard Settings: 
-- Enabled filters: English, Social Media, Spyware, Annoyances, Easy Privacy, Fanboy Annoyances
-- Stealth Mode: Enabled (All enabled except referrer & user agent) 
-- Browsing Security: Enabled 
-- Extensions: Assistant, Pop-up Blocker
1086930
[state.txt](https://github.com/AdguardTeam/AdguardFilters/files/330071/state.txt)

**Comment by Alex-302** [comment]
I can't reproduce.
Try to disable "Block third-party cookies". If it will help, switch it back and check these rules in user filter
```
@@||aifsansmystery.blogspot.in^$stealth
@@||aifsansmystery.blogspot.com^$stealth
```

**Comment by evgeniy-ADG** [comment]
@@||aifsansmystery.blogspot.in^$stealth
@@||aifsansmystery.blogspot.com^$stealth

I've added those few days back to user filter, as a temp workaround, so
that stealth mode doesn't work on these specific domains.
Adding those stealth mode exceptions does make blogs work, while letting me
keep stealth mode on for rest.

Can we somehow add similar rule for all blogspot blogs?.. The issue seems to occur in all blogs.

**Comment by Alex-302** [comment]
I'm using beta version now and still can't reproduce the issue with 'I understand & I wish to continue'
Try:
`@@||blogger.com^$stealth`
