### ISSUE TITLE
poisk-personala.ru redirects to marketis.ga

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2418]
Захожу на [сайт](http://poisk-personala.ru/personal/%D1%81%D0%B5%D0%BC%D0%B5%D0%B9%D0%BD%D0%B0%D1%8F-%D0%BF%D0%B0%D1%80%D0%B0/%D0%B3%D0%B0%D0%BB%D0%B0%D0%BD%D0%B4%D0%B8%D0%BD%D0%B0-%D0%B3%D0%B0%D0%BB%D0%B8%D0%BD%D0%B0-%D0%B3%D1%80%D0%B8%D0%B3%D0%BE%D1%80%D1%8C%D0%B5%D0%B2%D0%BD%D0%B0-%D1%80%D0%BE%D0%B5%D0%BD%D0%BA%D0%BE-%D0%B2%D0%B0%D0%BB%D0%B5%D1%80%D0%B8%D0%B9-%D0%B8%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87), а через несколько секунд вместо него открывается этот подозрительный сайт http://marketis.ga/ 

Мне пришлось добавить его в фильтр, но adguard его все равно его не блокирует. Помогите, пожалуйста.

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
liventernet.ml
```
