### ISSUE TITLE
servicemarket.su - should be blocked - fake pharmacy store

### ISSUE THREAD

**Issue by Sa-Ja-Di** [AdguardTeam/AdguardFilters#24192]
I want to report "servicemarket.su" - This is a case of the Canadian pharmacy scam campaign.

That domain is flagged here as malicious:
https://www.hybrid-analysis.com/sample/d53b1767676e2397598d66ad868101674fa00947ff53b611004333d7567f22fa/5bcc38b67ca3e1682c7d469d

Flagged Spamhaus, Quttera, Bitdefender
https://www.virustotal.com/#/url/6f4b1668d3e06b174b3d1ec50d254380a6299701d8b87cd1077d5fa9f451e210/detection

Please add this sample to your block-list too.

**Comment by TheHasagi** [comment]
This website is legit. 

Can you provide any pieces of evidence?

**Comment by Sa-Ja-Di** [comment]
Sure, just look at the Virustotal ratings. This page is no genuine online store.

virustotal.com/#/url/6f4b1668d3e06b174b3d1ec50d254380a6299701d8b87cd1077d5fa9f451e210/detection


Hope that is good enough evidence for changing your ratings for this domain.


________________________________
Von: Alexander <notifications@github.com>
Gesendet: Mittwoch, 24. Oktober 2018 11:44
An: AdguardTeam/AdguardFilters
Cc: Sajadi; Author
Betreff: Re: [AdguardTeam/AdguardFilters] servicemarket.su - should be blocked - fake pharmacy store (#24192)


This website is legit.

Can you provide any pieces of evidence?
