### ISSUE TITLE
pocketnow.com - teasers on the article page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2419]
**Description**:
Missed teasers on the article page.
http://pocketnow.com/2016/06/23/htc-sense-home-8-closed-beta

<img width="829" alt="2016-06-23_2236" src="https://cloud.githubusercontent.com/assets/5947035/16319293/f19fcb94-3992-11e6-897f-0926204f6d86.png">

**Comment by Alex-302** [comment]
Added to English filter
```
||pho.staticfiles.org/sos.js
```
It is loaded by encrypted script.
