### ISSUE TITLE
missed ads rustorka.com

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2420]
Пропущена реклама на rustorka.com

![2016-06-24_13-24-28](https://cloud.githubusercontent.com/assets/16462533/16335885/cd870914-3a11-11e6-8dff-e54d32d93d1a.png)

> ## **Мои фильтры**

![2016-06-24_13-30-59](https://cloud.githubusercontent.com/assets/16462533/16335926/12565bda-3a12-11e6-95ef-4c16f55e3614.png)

**Comment by Alex-302** [comment]
почистил

**Comment by vgavrish** [comment]
http://rustorka.com/forum/index.php
Скрины
<details>
![screenshot_1](https://cloud.githubusercontent.com/assets/18548949/16708764/df4ddd34-4606-11e6-96f6-a0b2d70bf3cb.jpg)
![screenshot_3](https://cloud.githubusercontent.com/assets/18548949/16708765/df5434c2-4606-11e6-886a-34f2c7472067.jpg)
</details>
Фильтры:
<details>
![screenshot_2](https://cloud.githubusercontent.com/assets/18548949/16708766/f416c5f0-4606-11e6-8302-c51274bd6d25.jpg)

**Comment by ameshkov** [comment]
Duplicate for #2305
