### ISSUE TITLE
twitch.tv

### ISSUE THREAD

**Issue by Legretto** [AdguardTeam/AdguardFilters#24201]
[https://www.twitch.tv/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.twitch.tv%2F)
### Comment
> Правило "twitch.tv##.pl-overlay" в английской фильтре не дает даблкликом разворачивать/сворачивать видео на весь экран.

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 6.4.1739.4753
Browser: | Vivaldi 2.1.1337.17
AdGuard driver: | TDI
Filters: | AdGuard Russian,<br>AdGuard Base

**Comment by bogachenko** [comment]
Для того чтобы отключить какой-то конкретный косметический фильтры нужно добавить @ между ##.
`twitch.tv#@#.pl-overlay`

[adguard](https://kb.adguard.com/ru/general/how-to-create-your-own-ad-filters#%D0%B8%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B4%D0%BB%D1%8F-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB-%D1%81%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D1%8F)

**Comment by AdamWr** [comment]
Fixed, thank you.
Update should be available in 2-3 hours.
