### ISSUE TITLE
Eventim sites - Blocked fuctions/media (AdGuard Spyware filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#24203]
### Affected sites:
```
https://www.billetlugen.dk/
https://www.entradas.com/
http://www.eventim.bg/
https://www.eventim.co.il/
https://www.eventim.co.uk/
https://www.eventim.com.br/
http://www.eventim.cz/
https://www.eventim.de/
https://www.eventim.fr/
http://www.eventim.hr/
http://www.eventim.hu/
https://www.eventim.nl/
https://www.eventim.no/
https://www.eventim.pl/
http://www.eventim.ro/
http://www.eventim.rs/
https://www.eventim.se/
http://www.eventim.si/
https://www.eventim.sk/
https://www.lippu.fi/
https://www.oeticket.com/
https://www.parter.ru/
https://www.ticketcorner.ch/
https://www.ticketone.it/
```

### Issue:
Many functions and media elements are blocked.

### Screenshot:
![filterissue-eventim2](https://user-images.githubusercontent.com/9382674/47270872-52fb7780-d572-11e8-9406-ae2d071200ad.jpg)

### Problem filter:
AdGuard Spyware filter

### Problem rule:
`||inpref.com^$third-party`

### Possible fix:
`@@||inpref.com^$third-party,domain=billetlugen.dk|entradas.com|eventim.bg|eventim.co.il|eventim.co.uk|eventim.com.br|eventim.cz|eventim.de|eventim.fr|eventim.hr|eventim.hu|eventim.nl|eventim.no|eventim.pl|eventim.ro|eventim.rs|eventim.se|eventim.si|eventim.sk|lippu.fi|oeticket.com|parter.ru|ticketcorner.ch|ticketone.it`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.1.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by Alex-302** [comment]
Thanks, added.

**Comment by THEtomaso** [comment]
@Alex-302:
That exception rule doesn't belong in the 'Russian Filter', but in the '**AdGuard Spyware filter**'!

**Comment by Alex-302** [comment]
Thanks, moved.

**Comment by THEtomaso** [comment]
Unfortunately, the changes that you've made to the exception rule that I posted, renders it useless!

This part needs to be removed!:
`xmlhttprequest,other,`

(Tested with 'Pale Moon' and 'SeaMonkey' web browsers)

What does the "other" syntax do anyway?

**Comment by Alex-302** [comment]
> What does the "other" syntax do anyway?

matches unknown content type(not script, XHR. stylesheet etc)



> renders it useless!

strange. It works in my PaleMoon

<details>

![image](https://user-images.githubusercontent.com/8361299/47419753-87934d00-d785-11e8-956b-048989340a60.png)

</details>

**Comment by THEtomaso** [comment]
I can confirm that it works for `eventim.de`, which you posted a screenshot of.
But not for all of the sites.
For example, it doesn't work for `eventim.no`

If you remove `xmlhttprequest,other,`, then it works for all of the sites!

**Comment by THEtomaso** [comment]
@Alex-302:
Properly working exception rules have been added to '**EasyPrivacy**' now:
https://github.com/easylist/easylist/commit/97ad9f265aabc6f4835bf017917d112de67e9623#diff-57814f66f7ce561ca9320be995443b1f
Perhaps you could just copy those?

**Comment by Alex-302** [comment]
Ok, replaced.
