### ISSUE TITLE
http://www.doviz.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2422]
**Site**: http://www.doviz.com/

**Screenshot**: ![31](https://cloud.githubusercontent.com/assets/19608513/16361308/5fb3ea84-3ba5-11e6-9d2a-92ddb3f93a5d.png)

![32](https://cloud.githubusercontent.com/assets/19608513/16361311/7114d766-3ba5-11e6-9d9a-2a2b6d0e2469.png)

![33](https://cloud.githubusercontent.com/assets/19608513/16361313/7cd60de0-3ba5-11e6-9442-1d554c86182f.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
doviz.com###scrollPopupContainer
doviz.com###ngVirgul_660x250
doviz.com##div[class^="banner"]
doviz.com##div[id$="Pageskin"]
```
