### ISSUE TITLE
bicaps.net

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2423]
**Site**: http://www.bicaps.net/

**Screenshot**: Annoyance
![indir](https://cloud.githubusercontent.com/assets/19608513/16355581/3a8669d4-3ad4-11e6-952d-fd1a31399657.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
bicaps.net###toolbar
```
