### ISSUE TITLE
evrenselfilmler.net

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2424]
**Site**: http://www.evrenselfilmler.net/

**Screenshot**: 
![4](https://cloud.githubusercontent.com/assets/19608513/16355621/0ad4cff8-3ad6-11e6-9162-e7503408d81b.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Just links to social blogs.
