### ISSUE TITLE
hizliizlefilm.net

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2425]
**Site**: http://www.hizliizlefilm.net/

**Screenshot**:  ![5](https://cloud.githubusercontent.com/assets/19608513/16355658/0d08839a-3ad7-11e6-9fe8-4eff06fba1f6.png)
When click "FILMI IZLE". opens a new page in the new tab

Click here: http://www.hizliizlefilm.net/hizli-seyret-8926-suclu-izle-hd-criminal.html
**Screenshot**:  ![6](https://cloud.githubusercontent.com/assets/19608513/16355664/43440bbe-3ad7-11e6-8634-ba66715cf5e7.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
||hizliizlefilm.net/js/bs2reklam.js
hizliizlefilm.net###video_blok > div[style]
hizliizlefilm.net###ps_kapat
hizliizlefilm.net##.video_alti_yazi

```
