### ISSUE TITLE
ofilmo.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2426]
**Site**: http://www.ofilmo.com/kara-duzen-black-mass-2015.html

**Screenshot**:  Ad before video
![7](https://cloud.githubusercontent.com/assets/19608513/16355693/01ec4388-3ad8-11e6-9f43-452af16c8512.png)

**Screenshot**:  After ad, video will be start. At the bottom of video you can see this white place
![8](https://cloud.githubusercontent.com/assets/19608513/16355697/296c7932-3ad8-11e6-92ef-8592739231db.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
I don't see social element.
Added to Turkish filter
```
ofilmo.com#$##Movie-video{ display: block!important; }
ofilmo.com###Video-Oncesi

```

**Comment by thislife81** [comment]
![k](https://cloud.githubusercontent.com/assets/19608513/16484030/ce274e80-3ebf-11e6-84ec-aa8c12b3b1b5.png)

Here is this. :)

**Comment by Alex-302** [comment]
it is hidden by
```
~baglanfilmiizle.com##div[class^="reklam-"]
```
from Turkish filter.

**Comment by thislife81** [comment]
Please remove background ad.

**Comment by Alex-302** [comment]
```
ofilmo.com##.reklamlink
||ofilmo.com/wp-content/uploads/*/plusbet

```
