### ISSUE TITLE
film-tr.com / hdfilmdeposu.net / filmbizdeizlenir.com / durdurfilmizle.com / hdfilmizlet.net / sinefan.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2427]
**Site1**: http://www.film-tr.com/

**Screenshots**:  ![9](https://cloud.githubusercontent.com/assets/19608513/16355710/59d6e034-3ad9-11e6-81b4-53d3662260b7.png)

![10](https://cloud.githubusercontent.com/assets/19608513/16355711/6556de3c-3ad9-11e6-8b9e-dd9307dc17c4.png)

**Site2**: http://www.filmbizdeizlenir.com/ Remove link in the background

**Screenshots**:  ![10](https://cloud.githubusercontent.com/assets/19608513/16358330/64a93b24-3b29-11e6-8faf-65a6c1f2dbfb.png)

![11](https://cloud.githubusercontent.com/assets/19608513/16358333/77a0a88e-3b29-11e6-9e5f-6b7979d2e1f9.png)

![12](https://cloud.githubusercontent.com/assets/19608513/16358335/8785cacc-3b29-11e6-82d5-65457fec2aa9.png)

**Site3**: http://www.hdfilmdeposu.net/Remove link in the background

**Screenshots**:  ![1](https://cloud.githubusercontent.com/assets/19608513/16361730/91a587ec-3bb3-11e6-8da9-ab90c8832a2a.png)

![2](https://cloud.githubusercontent.com/assets/19608513/16361735/a5b4ab5a-3bb3-11e6-9435-64e73dd88000.png)

**Site4**: http://www.durdurfilmizle.com/  1)Remove ad in the background, 2)Remove white place

**Screenshots**:  ![1](https://cloud.githubusercontent.com/assets/19608513/16360900/c558fd00-3b93-11e6-9b20-ed4db9ba84a8.png)

**Site5**: http://www.hdfilmizlet.net/

**Screenshots**:  ![ew](https://cloud.githubusercontent.com/assets/19608513/16358231/35509798-3b27-11e6-992a-880093e3bc00.png)

**Site6**: http://www.sinefan.com/

**Screenshots**:  ![4](https://cloud.githubusercontent.com/assets/19608513/16360978/a1456328-3b97-11e6-9646-06e29b274706.png)

![5](https://cloud.githubusercontent.com/assets/19608513/16360981/b06ac42e-3b97-11e6-87c1-062dfea49f3f.png)

![6](https://cloud.githubusercontent.com/assets/19608513/16360986/bfae3b3c-3b97-11e6-9c56-68369057ccec.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
One issue - one site.

**Comment by Alex-302** [comment]
1. Added to Turkish filte
```
film-tr.com##div[class^="sag-reklam"]
```

**Comment by thislife81** [comment]
Oh sorry about this, I haven't know that. I just edited other issues..
