### ISSUE TITLE
fullhd720pizle.com / vipfullhdfilmizle.org / fullhdfilmcehennemi.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2428]
**Site1**: http://www.fullhd720pizle.com/alacakaranlik-2-yeni-ay-2009-turkce-dublaj-izle.html

**Screenshot**:  ![11](https://cloud.githubusercontent.com/assets/19608513/16355738/4f2ae1b6-3ada-11e6-8133-594107298942.png)

**Site2**: http://www.vipfullhdfilmizle.org/dedemle-bu-yaz-turkce-dublaj-izle/
Remove these ads and add this rule for background: vipfullhdfilmizle.org#$#body {background-image: none!important; }

![bb](https://cloud.githubusercontent.com/assets/19608513/16357350/a42e8e5a-3b0d-11e6-9a8d-555b975d4b86.png)

**Site3**: http://www.fullhdfilmcehennemi.com/kod-adi-londra-london-has-fallen-turkce-dublaj-izle-2.html

![1](https://cloud.githubusercontent.com/assets/19608513/16358095/c571c4f0-3b22-11e6-81f0-efb13e778137.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Please don't place few sites in one issue on GitHub.

**Comment by Alex-302** [comment]
№2 is clean
Added to Turkish filter
```
fullhd720pizle.com###VideOnrekLam
fullhd720pizle.com#$#.video { display: block!important; }
fullhdfilmcehennemi.com###VideOnrekLam
fullhdfilmcehennemi.com#$#.video { display: block!important; }

```

**Comment by thislife81** [comment]
http://www.fullhd720pizle.com/alacakaranlik-2-yeni-ay-2009-turkce-dublaj-izle.html
This isn't remove, please remove it.
![b](https://cloud.githubusercontent.com/assets/19608513/16487111/7ba57b34-3ed1-11e6-9797-495206f21ec9.png)

**Comment by Alex-302** [comment]
Added to Turkish filter
```
fullhd720pizle.com##iframe[rel="nofollow"]

```
