### ISSUE TITLE
http://www.gezginler.net/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2429]
**Site**: http://www.gezginler.net/indir/google-chrome.html 

**Screenshot**: ![10](https://cloud.githubusercontent.com/assets/19608513/16361040/21c10de8-3b9a-11e6-8258-c3cf1c161576.png)

Click "Google Chrome 51.0.2704.84 Indir"  After clicking here, opens a new page, in this page remove these ads: 

**Screenshot**:  ![11](https://cloud.githubusercontent.com/assets/19608513/16361066/232e2070-3b9b-11e6-9dae-caa85d30ee75.png)

If you won't see ads in the background, enter this site- http://www.gezginler.net/indir/google-chrome.html 
, and click "Google Chrome 51.0.2704.84 Indir"

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
gezginler.net###iceriksol > div#indralt > div#prioyun
gezginler.net##body > div[align="center"][style="position:fixed; top:0px; width:100%; z-index:-1"] > div[style="position:relative; width:970px; margin-left:auto; margin-right:auto;"]

```
