### ISSUE TITLE
vk.com

### ISSUE THREAD

**Issue by bogachenko** [AdguardTeam/AdguardFilters#24294]
Почему фильтр `vk.com##body > div[id^="stl_"]` блокирующий кнопку перемотки страницы (слева которая) находится в базовом фильтре Adguard?

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/294c036085242d83708e6bd82547a12ede1292f0

**Comment by bogachenko** [comment]
_не хочу создавать новый тред, доедаю старый_

@Alex-302 привет, у меня проблема с https фильтрацией.

У меня на телефоне установлено одно приложение - [Instander](https://thedise.me/instander/), скачать/почитать о нем можешь [здесь](https://4pda.ru/forum/index.php?showtopic=326697&st=23400#entry96260754), он конфликтует с adguard.
В логгере, только заблокированы QUIC протоколы, которые по все видимости ему и нужны. При открытии Instander-a, с включенным Adguard-ом, первого начинает косоебить. Невозможно открыть мой аккаунт, не грузятся фотографии/видео, не грузится меню для разработчиков, однако если зайти в adguard>настройки приложений>Instander и выключить у него https фильтрацию, то все работает.

Вопрос: За каким хуем вы блокируете QUIC протокол? Через него, ведь не только реклама лезет. Как включить QUIC и при этом, блять, заставить https работать?

PS: только не говори мне, что мне предется вручную, каждый домен quic разблокировать, ведь `@@|quic://$app=com.instander.android, important` не работает.

**Comment by bogachenko** [comment]
@Alex-302 добавь в разражители

```
trialeset.net,trialnod.net##.remodal-is-opened.remodal-wrapper, .remodal-is-opened.remodal-overlay
trialeset.net,trialnod.net##html:style(overflow-y: scroll !important;)
```

**Comment by bogachenko** [comment]
@Alex-302 @AdamWr `|http*$app=com.adups.fota.sysoper|com.adups.fota` your rule breaks wireless update on my tablet

**Comment by Alex-302** [comment]
Видимо китайщина? Это приложение-шпион.

**Comment by bogachenko** [comment]
Да, я читал тот тред где вы это правило добавили, но я хз, с ним обновления не прилетают 
![Screenshot_20201218-144006](https://user-images.githubusercontent.com/8535285/102571998-12421d80-413f-11eb-873e-4f014719499c.png)

**Comment by bogachenko** [comment]
@Alex-302 на https://www.radiorecord.ru/ внизу блок с соцсетями
