### ISSUE TITLE
hdfilmgecesi.org

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2430]
**Site**: http://hdfilmgecesi.org/well-wishes-2015-full-izle.html

**Screenshot**: 
![13](https://cloud.githubusercontent.com/assets/19608513/16355780/f77979e4-3adb-11e6-96d3-55fe7fed925a.png)

And background picture is an ad content. Add this rule: 
hdfilmgecesi.org#$#body {background-image: none!important; }

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdfilmgecesi.org#$#body {background-image: none!important; } 
hdfilmgecesi.org###toolbar
hdfilmgecesi.org###filmoncereklam
hdfilmgecesi.org#$##film { display: block!important; }

```

**Comment by thislife81** [comment]
These aren't removed, please remove also them.
![a](https://cloud.githubusercontent.com/assets/19608513/16487021/e9740384-3ed0-11e6-80ee-4d8d119d5ae7.png)

**Comment by Alex-302** [comment]
I forgot to add them
Added to Turkish filter
```
hdfilmgecesi.org##iframe[width="400"][height="400"]
hdfilmgecesi.org###splashscreen
||youtube.com/embed/gj24-aYDw2o$domain=hdfilmgecesi.org
```

**Comment by thislife81** [comment]
The site is not opening with ADGUARD at the moment.

**Comment by Alex-302** [comment]
hdfilmgecesi.org#@#body > #pageskin
