### ISSUE TITLE
http://www.full-torrent.org/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2431]
**Site**: http://www.full-torrent.org/

**Screenshot**:  ![78](https://cloud.githubusercontent.com/assets/19608513/16361356/4194a456-3ba7-11e6-95c9-ebc5fb5aae22.png)
After loading page, shown this annoyance

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
It is clean now. Blocked by generic rule
