### ISSUE TITLE
filmrax.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2432]
**Site**: http://www.filmrax.com/muzede-bir-gece-1-izle-full-hd-turkce-dublaj-2006.html

**Screenshot**: ![2](https://cloud.githubusercontent.com/assets/19608513/16355943/2b5f1714-3ae1-11e6-9e0d-27f712975e96.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Social filter
```
filmrax.com###SociaLKare
```
