### ISSUE TITLE
sinemakeyfi.biz

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2433]
**Site**: http://www.sinemakeyfi.biz/

**Screenshot**: 
![0](https://cloud.githubusercontent.com/assets/19608513/16355967/3ed6c7c8-3ae2-11e6-8ff4-44b1fccc786a.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
sinemakeyfi.biz##.ana-orta
```
