### ISSUE TITLE
rutor.info

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2434]
**Description**:
rutor.info
При нажатии на любое место открывается другой сайт
http://c.mobpartner.mobi/?pool=61075&subid=1236.2298.0.UA.3

Screenshot:
http://prntscr.com/bktobv

**Filters list**: [ 2, 3, 4, 5, 14, 10, 1, 11 ], обновлены

**Operating system**: Android

**Comment by Alex-302** [comment]
Чисто у меня.

**Comment by vgavrish** [comment]
У меня еще есть:
http://prntscr.com/bns6u3
При нажатии на вот эту пустую область:
http://prntscr.com/bns7fe

**Comment by Alex-302** [comment]
Добавил в мобильный фильтр
```
||regpole.com^$empty
rutor.info,nnm.me,korzik.net,seasonvar.ru,rsload.net,nnm-club.me,nnmclub.to,rustorka.com,auto.mail.ru,horo.mail.ru,realty.mail.ru,health.mail.ru,afisha.mail.ru,cloud.mail.ru,otvet.mail.ru,pogoda.mail.ru,sport.mail.ru,tv.mail.ru,torg.mail.ru,cars.mail.ru,hi-tech.mail.ru#%#window.WebSocket = undefined;

```

**Comment by vgavrish** [comment]
У пользователя всплывающие окна
Фильтры:  2, 3, 4, 5, 14, 1, 11, 211 
Такое поведение наблюдается на всех  зеркалах сайта rutor.org (он же rutor.info), как на http://tor-ru.net/new, так и например на http://hd-bit.org/new
log
[debug (4).txt](https://github.com/AdguardTeam/AdguardFilters/files/504437/debug.4.txt)
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19015104/472e4dd0-8806-11e6-8728-15fa45d3cd09.png)

**Comment by Alex-302** [comment]
Ни на одном из зеркал проблема не повторилась. Какой режим и алгоритм фильтрации?

**Comment by paskardv** [comment]
Качественный
Локальный vpn

Реклама появляется 2 раза подряд, потом повторяется не раньше чем через полдня-день примерно. Чистка кэша её не вынуждает появиться вновь.

Добавил в пользовательский фильтр, как по аналогии выше было:
||regpole.com^$empty rutor.info,fast-bit.org,hd-bit.org,tor-ru.net
Наблюдаю, если за пару дней не появится - значит "оно"

**Comment by paskardv** [comment]
Не помогло, почистил куки и кэш в хроме, сновы открылась реклама при первом же тапе куда попало.
http://prntscr.com/cow9ay
Сжатие, кстати, в хроме отключено.

**Comment by Alex-302** [comment]
Запишите HAR файл по этой инструкции:
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/66/5/kk-poluchit-fjjly-har-http-rkhiv-n-android-ustrojjstve
Перед записью , когда сделаны нужные настройки, выключите и включите защиту. Сайт нужно открывать в приватной вкладке либо предварительно очистив кэш браузера. После попапа выключите защиту и вышлите файл.
Запись HAR в конце нужно выключить и передёрнуть защиту.

**Comment by paskardv** [comment]
Во вложении файлик har.
Записывал, воспроизведя проблему в приватной вкладке.

Отправлено из AquaMail для Андроида
http://www.aqua-mail.com


Alex <notifications@github.com> 2 октября 2016 г. 16:55:13 написал:

**Comment by Alex-302** [comment]
Не прикрепилось. Надо через сам гитхаб.

**Comment by paskardv** [comment]
[adguard.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/505111/adguard.har.zip)

**Comment by Alex-302** [comment]
Хм.. Не понятно откуда всплывает. А есть возможность подключить по ADB к компьютеру?

**Comment by paskardv** [comment]
Пока нет, к сожалению :(

**Comment by Alex-302** [comment]
Имел в виду вообще:)

**Comment by paskardv** [comment]
Вообще конечно получится. Что нужно будет сделать? Только по пунктам и по возможности подробно :)

**Comment by Alex-302** [comment]
1) На компе и телефоне открыть Хром.
2) Подключить телефон по USB в режиме отладки.
3) На компе в Хроме открыть 
```
chrome://inspect/#devices
```
и проверить, что открывается инспектор элементов для телефона.Нужно будет подтвердить авторизацию.

**Comment by paskardv** [comment]
Всё ок, подключилось. Что дальше?

**Comment by Alex-302** [comment]
Дальше через TeamViewer смотреть нужно.

**Comment by paskardv** [comment]
501 315 149
8573

**Comment by Alex-302** [comment]
Не, уже не сегодня)
Давайте завтра в течение дня.

**Comment by paskardv** [comment]
Попробую настроить на работе... Либо вечером, если не получится.

**Comment by Alex-302** [comment]
Ок, напишите, когда будете готовы. Можно не поздним вечером.

**Comment by paskardv** [comment]
Я готов к тестам.

**Comment by Alex-302** [comment]
Ок, скиньте минут через 15 ID и пароль. Пока немного занят.

**Comment by paskardv** [comment]
501 315 149
6924

**Comment by Alex-302** [comment]
```
$$script[wildcard="*script_id*onerror*ws*"][max-length="1600"]
```

**Comment by paskardv** [comment]
Зеркал много у rutor, под каждое при необходимости домен нужно будет в начале правила поменять?

**Comment by paskardv** [comment]
Из того, что попадалось раньше часто:
rutor.info
fast-bit.org
hd-bit.org
tor-ru.net
Правило из пользовательского фильтра удалил.
Если что будет еще - конечно напишу.
Спасибо за помощь! Реально очень раздражали эти всплывающие окна.

**Comment by Alex-302** [comment]
Ок, добавил два последних.

**Comment by paskardv** [comment]
Доброго времени суток, появилось новое зеркало http://super-tor.net
Добавьте пжлст. в фильтр.

**Comment by Alex-302** [comment]
Добавил

**Comment by paskardv** [comment]
Приветствую, добавьте пжлст. еще одно зеркало http://free-ru.org/new в фильтры

**Comment by Alex-302** [comment]
ок

**Comment by paskardv** [comment]
Доброго времени суток, еще одно зеркало http://all-tor.net/new

**Comment by Alex-302** [comment]
Добавил. Проверьте на всякий случай именно на этом домене
```
all-tor.net#%#window.WebSocket = undefined;
```
актуально ли ещё.

**Comment by vgavrish** [comment]
rutor.info/search/ реклама
[debug (24).txt](https://github.com/AdguardTeam/AdguardFilters/files/636019/debug.24.txt)
время: 11.50

<details>
enabledFilterIds" : [ 2, 3, 4, 1, 11 ]
"filteringQuality" : "FULL",
versionName" : "2.8.67",
proxyMode" : true,
"proxySetupManualMode" : false,
HTTPS 

![image](https://cloud.githubusercontent.com/assets/18548949/20959667/d7ddd6a6-bc64-11e6-9377-600d3260113a.png)

**Comment by Alex-302** [comment]
I don't see any requests to this site

**Comment by paskardv** [comment]
Alex-302, что с данным правилом, что без него (добавлял в собственный фильтр) - рекламы на этом домене нет.

**Comment by paskardv** [comment]
Появилось еще одно зеркало http://film-tor.org добавьте к остальным пжлст.

**Comment by Alex-302** [comment]
А какое правило там? Запишите HAR файл.
https://kb.adguard.com/index.php?/Russian/Knowledgebase/Article/View/66/5/kk-poluchit-fjjly-har-http-rkhiv-n-android-ustrojjstve

**Comment by paskardv** [comment]
Да всё те же всплывающие рекламные окна, как и раньше. Вроде бы лечится правилом, аналогичном указанному Вами несколько ранее film-tor.org$$script[wildcard="*script_id*onerror*ws*"][max-length="1600"]

**Comment by Alex-302** [comment]
Добавил.
