### ISSUE TITLE
jetfilmizle.net

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2435]
**Site**: http://jetfilmizle.net/chloe-and-theo-turkce-dublaj-film-izle-hd.html
There is an ad before video. Ad plays, but doesnt shown. After finish, video starts/

**Screenshot**:  
![8](https://cloud.githubusercontent.com/assets/19608513/16355999/1818b672-3ae3-11e6-8977-dba2833de35f.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
jetfilmizle.net###toolbar
