### ISSUE TITLE
hdfilmsaati.org

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2436]
**Site**: http://www.hdfilmsaati.org/the-confirmation-izle.html

**Screenshot**: 
![7](https://cloud.githubusercontent.com/assets/19608513/16356027/b60e790c-3ae3-11e6-82cc-f75cb90d398f.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdfilmsaati.org##.SidebarRekLam
hdfilmsaati.org###toolbar
hdfilmsaati.org###VideOnrekLam
hdfilmsaati.org#$##kendisi{ display: block!important; }
```
