### ISSUE TITLE
xmovies8.pl

### ISSUE THREAD

**Issue by Mav3r1x** [AdguardTeam/AdguardFilters#24374]
Unable to play any video on this website with Adguard active. The "video player" prompts to 'disable the adblocker' to play.

Example link: https://xmovies8.pl/movie/the-spy-who-dumped-me-2018-1080p.28335/watching.html

When you click on the Play icon, it says "Please Disable Your AdBlock
Video will be visible once you whitelist xmovies8.pl on your adblocker."

Help, please.

**Comment by AdamWr** [comment]
Added:
```
@@||static.xmovies88.online/themes/*/js/ads.js
@@||static.xmovies88.online/themes/_js/adsbygoogle.js
xmovies8.pl#%#window.check_adblock = true;
xmovies8.pl#%#window.isAdsDisplayed = true;
xmovies8.pl###upgrade_pop
||ipreparty.info^$third-party
||varielcontentdelivery.info^$third-party
||djz9es32qen64.cloudfront.net^
xmovies8.pl#%#Object.defineProperties(window,{admvpu:{get:function(){},set:function(a){if("function"==typeof a)throw Error();}},Fingerprint2:{get:function(){},set:function(){throw Error();}}});
```
Update should be available in 2-3 hours.
Please next time fill the template.
