### ISSUE TITLE
http://hdrezka.ag

### ISSUE THREAD

**Issue by alvussar** [AdguardTeam/AdguardFilters#24375]
На сайте http://hdrezka.ag есть функция, сохранения истории просмотра (http://hdrezka.ag/continue/)
С включенным Adguard (любой в том числе и расширение для браузера) эта история не сохраняется.

**Comment by Alex-302** [comment]
У меня с выключенным Адгардом ничего не попадает в список. Как по-быстрому проверить? Я открывал сериал и перематывал.

**Comment by alvussar** [comment]
Это скорее всего проблема на сервере самом. Просто она то появляется то пропадает. Adg здесь получаеться не причем.

**Comment by Alex-302** [comment]
Ок, пока закрываю.
