### ISSUE TITLE
hdfulltekpart.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2437]
**Site**: http://www.hdfulltekpart.com/

**Screenshot**: 
![70](https://cloud.githubusercontent.com/assets/19608513/16356055/d53f0214-3ae4-11e6-9e58-3daf8343fb44.png)

Click here: http://www.hdfulltekpart.com/midnight-special-film-izle-2016/

**Screenshot**: 
![71](https://cloud.githubusercontent.com/assets/19608513/16356060/f71ad62e-3ae4-11e6-97d6-5044f7ee6eb7.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdfulltekpart.com##koddostu
hdfulltekpart.com#$##filmplayer { display: block!important; }
hdfulltekpart.com###filmreklam

```
