### ISSUE TITLE
http://www.dailymotion.com/embed/video/x4hhscs - infinite loading

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2438]
**Description**: can't play a video 

**Current behaviour**: video won't start

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16356178/f549a080-3ad7-11e6-92a4-7a8e2aeacdca.png)

</details>

**Expected behaviour**:

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16356170/b8cedc2e-3ad7-11e6-93ae-2a8b99831830.png)

</details>

**Steps to reproduce the problem**:
- open the link
-  experience the issue

**Adguard version**: the latest one

**Filters list**:
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:104 Name: EasyList China Url: https://easylist-downloads.adblockplus.org/easylistchina.txt
FilterId:0 Name: User filter Url: no_url
FilterId:100000 Name: List-KR Url: https://github.com/SlowMemory/List-KR/raw/master/filter.txt

**Operating system**: win

**Browser**: ie 11

**Comment by evgeniy-ADG** [comment]
Works fine if English filter is disabled.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
please check with browser extension. If it ok, run the desktop app and disable in Eng filter
`||liverail.com^$~object-subrequest,third-party`
then add
`||liverail.com^$~object-subrequest,third-party,empty`
