### ISSUE TITLE
http://www.mackolik.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2439]
**Site**: http://www.mackolik.com/

**Screenshot**: Plz remove this
![1](https://cloud.githubusercontent.com/assets/19608513/16356216/3aafbd1e-3aea-11e6-95f9-971aa6bcd7b4.png)

Click here: http://www.mackolik.com/Mac/2464632/Albirex-Niigata-Sagan-Tosu
![2](https://cloud.githubusercontent.com/assets/19608513/16356218/4a220c20-3aea-11e6-86a4-b0b52c6f30ee.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
1 - is closed almost immediately
2 - I don't see it

**Comment by thislife81** [comment]
2)
![c](https://cloud.githubusercontent.com/assets/19608513/16489048/4a47c01e-3edc-11e6-8139-a93d2418916f.png)

**Comment by Alex-302** [comment]
Added to Turkish filter
```
mackolik.com##div[id$="978x45_div"]
```
