### ISSUE TITLE
filmgoo.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2440]
**Site**: http://www.filmgoo.com/

**Screenshot**: 
![1](https://cloud.githubusercontent.com/assets/19608513/16356450/770c2462-3af1-11e6-9356-fa8542e669fd.png)

When you click, opens a new page:
![2](https://cloud.githubusercontent.com/assets/19608513/16356453/89fda6ea-3af1-11e6-96e1-0f72308f6abe.png)

Click here: http://www.filmgoo.com/la-loi-du-marche-insanin-degeri-izle-2015.html
![3](https://cloud.githubusercontent.com/assets/19608513/16356455/adcc1e58-3af1-11e6-8034-6e7373b97557.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
||filmgoo.com/bs2popreklam.js
filmgoo.com||grbcdn.com/grandroyalbet/
filmgoo.com##.yildiz-pageskin-link

```

**Comment by thislife81** [comment]
Please remove these

http://www.filmgoo.com/
![s](https://cloud.githubusercontent.com/assets/19608513/16512871/6f9fc10e-3f68-11e6-82d8-274c46516578.png)

http://www.filmgoo.com/la-loi-du-marche-insanin-degeri-izle-2015.html
![q](https://cloud.githubusercontent.com/assets/19608513/16512877/88d7633e-3f68-11e6-8d12-8e8eccf8e749.png)

**Comment by Alex-302** [comment]
Added to Turkish filter
```
filmgoo.com##.tab-reklam
filmgoo.com#$#.tab-embed { display: inline!important; }
```
Added to Social filter
```
###sag-facebook-tablo
```
