### ISSUE TITLE
http://news.lent.az

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2441]
**Site**: http://news.lent.az/news/246480

**Screenshot 1**:  Remove these ads and white places
![222](https://cloud.githubusercontent.com/assets/19608513/16356678/82fe6326-3afa-11e6-9d6f-98d4f3384729.png)

**Screenshot 2**: 
![2](https://cloud.githubusercontent.com/assets/19608513/16356673/5d329086-3afa-11e6-9cd2-1f585de0c38d.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to English filter
```
lent.az##body > div[style="margin:0 auto;height:86px;width:990px;"]
lent.az##.lazyLoadAd_places
||apa.tv/test/banners/
||vesti.az/site/vestiiframe3lentaz
```
other rules are dangerous
