### ISSUE TITLE
http://www.canlimacizle.org/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2442]
**Site**: http://www.canlimacizle.org/

**Screenshot**:
![8](https://cloud.githubusercontent.com/assets/19608513/16357104/ac1df472-3b06-11e6-92cd-dd9cf366126a.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
canlimacizle.org##div[class^="tipoads"]

```
