### ISSUE TITLE
diziizlev.org

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2443]
**Site**: http://www.diziizlev.org/yalanci-bahar-15-bolum-izle-24-haziran-2016-dizi-izle.html

**Screenshot**: 
![q](https://cloud.githubusercontent.com/assets/19608513/16357213/29e34d9c-3b09-11e6-97d4-cdc8193f445a.png)

Add this rule for background: diziizlev.org#$#body {background-image: none!important; }

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
diziizlev.org#$##film { display: block!important; }
diziizlev.org#$#body{ background: none!important; }
diziizlev.org###filmoncereklam
diziizlev.org##a[rel="nofollow"][class="pageNoFollow_hilite"]

```

**Comment by thislife81** [comment]
Please remove this.
![vc](https://cloud.githubusercontent.com/assets/19608513/16513072/55948860-3f6a-11e6-96fe-8f3de90f2c1a.png)

**Comment by Alex-302** [comment]
Added to Turkish filter
```
diziizlev.org##koddostu
```
