### ISSUE TITLE
http://www.baslattusu.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2444]
**Site**: http://www.baslattusu.com/

**Screenshot**: 
![a8](https://cloud.githubusercontent.com/assets/19608513/16357247/40311c90-3b0a-11e6-9e29-2f916ad348ee.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
baslattusu.com###sgcboxOverlay
baslattusu.com###sgcolorbox

```
