### ISSUE TITLE
filmbudur.org

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2445]
**Site**: http://www.filmbudur.org/izle/kismetse-olur-halk-oylamasi-25-haziran-2016-izle.html

**Screenshot**: ![84](https://cloud.githubusercontent.com/assets/19608513/16357256/a870569a-3b0a-11e6-8d61-cb33a34bcc11.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
filmbudur.org###filmoncereklam
filmbudur.org#$##film { display: block!important; }

```
