### ISSUE TITLE
Что за банер ? 

### ISSUE THREAD

**Issue by aiv3006** [AdguardTeam/AdguardFilters#24462]
[http://pic-mir.ru/allimage/0/1/6/8/4/168418.jpeg](url)

**Comment by Alex-302** [comment]
Не известно.

**Comment by aiv3006** [comment]
Алекс а как в своем акке на этом сайте посмотреть все созданные темы мной подскажи ?

**Comment by Alex-302** [comment]
смотря какой репозиторий.
В этом так
https://github.com/AdguardTeam/AdguardFilters/issues/created_by/aiv3006

**Comment by aiv3006** [comment]
Алекс не по теме :( Я сам электрик + электронщик ) Я тоже на сленге могу выражатсься на что учился тока ты меня через вик-эпедемию поймешь ) Давай на рускоязычный перейдем хоть я тебя и понимаю но все же сохраним приоретет для неопытных+ начинающих пользователей   Adguard консолидарен со мной ? ;))) Что касается твоего ответа не то ! [http://pic-mir.ru/allimage/0/1/6/8/4/168419.jpeg ](url) Я много тем создавал так сказать на этом сайте про   Adguard  нужно все вопросы в моем акке найти чтобы просто -Выбрал вопро и просмотрел всю тему

**Comment by Alex-302** [comment]
Что конкретно не понятно?)

Если `aiv3006` в задаче или переписке не упоминается, то их не найти. 
Более широкий запрос - поиск среди открытых и закрытых задач:
`https://github.com/AdguardTeam/AdguardFilters/issues?utf8=%E2%9C%93&q=aiv3006+`
