### ISSUE TITLE
thepiratebay.org - popunder

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2447]
**Description**:

**Current behaviour**: Popunder script opens a new window when you click on any link there.
Go to this page: https://thepiratebay.org/search/test/0/99/0 and click on any link there.

Also I see a missed ad network there:
```
||adxprts.com^$third-party
```

It seems that it is controlled by "tpbpop" cookie.

**Comment by Alex-302** [comment]
added
`||thepiratebay.org/*.php?`
```
thepiratebay.org#%#function setCookie(c_name, exdays) { var exdate = new Date(); exdate.setDate(exdate.getDate()); var c_value = escape("2|") + escape(exdate.toUTCString()) ; document.cookie = c_name + "=" + c_value + "; path=/"; };
thepiratebay.org#%#setCookie('tpbpop', 96400000); setCookie('tpbpopa', 96400000);
```
