### ISSUE TITLE
www.hdfullfilmizlesene.org

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2448]
**Site**: http://www.hdfullfilmizlesene.org/

**Screenshot**: 
![qw](https://cloud.githubusercontent.com/assets/19608513/16358160/32b43b40-3b25-11e6-85c4-95f59c378696.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdfullfilmizlesene.org###logo > a[rel="nofollow"] > img
hdfullfilmizlesene.org##div[class$="reklam-s-koddostu"]
```
