### ISSUE TITLE
pornxs.com [NSFW] [Ad String]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#24494]
**Site**: https://pornxs.com/video.php?id=3258198&utm_source=awn-rse&utm_medium=inc&utm_campaign=20171124

**Issue**: Please remove the ad text on the page

**Screenshot**: http://prntscr.com/lb1p1s

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 70.0.3538.77 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.13 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Spam 404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by bogachenko** [comment]
check
`pornxs.com##.video__container > .video__inner > .video__content + :last-child`

**Comment by Nzzyme** [comment]
Still seeing some other ad text strings

https://pornxs.com/21729115

http://prntscr.com/nje01i
