### ISSUE TITLE
www.bizimyol.info

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2449]
**Site**: http://www.bizimyol.info/news/80350.html

**Screenshot**: ![q](https://cloud.githubusercontent.com/assets/19608513/16358869/fa4cd6b6-3b3a-11e6-8f24-08582ad0c27f.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to English filter
```
||bizimyol.info/azzz_
```
