### ISSUE TITLE
tubeon.com [NSFW] [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#24493]
**Site**: https://www.tubeon.com/video/76279/emily-vanili-gets-her-slit-licked-and-pounded-by-hung-guy-mr-pete

**Issue**: Please remove the ad text and empty ad banner on the page as seen

**Screenshot**: http://prntscr.com/lb1ngy

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 70.0.3538.77 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.13 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Spam 404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by bogachenko** [comment]
`www.tubeon.com###abmessage`
`www.tubeon.com##.thr-rcol`
removed only the right column with ads and the red caption above the video. the rest could not reproduce.
there are a lot of cosmetic filters to be rewritten for a long time, just subscribe to Easylist and Adguard Spyware Filters

**Comment by Nzzyme** [comment]
Has this been added? Pop-up also seen now.

**Comment by bogachenko** [comment]
tubeon.com$popup try ag

**Comment by bogachenko** [comment]
it has not been added @Alex-302 . call here and he will add

**Comment by Nzzyme** [comment]
Still seeing empty ad banner on video player. @Alex-302 please check:

URL: https://www.tubeon.com/video/76279/emily-vanili-gets-her-slit-licked-and-pounded-by-hung-guy-mr-pete

Screenshot: http://prntscr.com/mm8qch

**Comment by Alex-302** [comment]
not reproduced.
