### ISSUE TITLE
http://telsat.az/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2450]
**Site**: http://telsat.az/

**Screenshot**:  ![gf](https://cloud.githubusercontent.com/assets/19608513/16358980/67ea26fe-3b3d-11e6-8428-0f350acb6a78.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 8.1

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
telsat.az#$##myModalhello { display: none!important; }
telsat.az#$#.modal-backdrop { display: none!important; }
telsat.az#$#.modal-open { overflow: initial!important; }
```
