### ISSUE TITLE
Missed advert on adguard android - Ampere

### ISSUE THREAD

**Issue by versavius** [AdguardTeam/AdguardFilters#24502]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

An advert appears in ampere when adguard for Android is running (v2.12.247) with the latest default filters applied.

* **Current behaviour**: 

The advert is not being blocked, I have tried with Https filtering on and off.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.

<details><summary>Screenshot:</summary>

![screenshot_20181027-134901_ampere](https://user-images.githubusercontent.com/11394779/47604395-37b8be00-d9f1-11e8-911e-25c69edf25a8.jpg)

</details><br/>

* **Expected behaviour**: 

[The advert should be blocked

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | 8.00
Operating system version (Android/iOS) | android
Browser:                               | chrome
AdGuard version:                       | 2.12.247
Filters enabled:                       | adguard base, adguard mobile ads, adguard spyware, adguard social media, adguard annoyances, 
AdGuard mode (Android only):           | vpn
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | 
AdGuard DNS:                           | adguard-dns
Stealth mode options (Windows only)    | 
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by versavius** [comment]
These are my current log files

[Uploading adguard_logs_2.12.247_2710_1408.zip…]()

**Comment by Alex-302** [comment]
Hi
What is `Ampere`?  Please add URL and screenshot.

**Comment by BlazDT** [comment]
Looks like this one here:
https://github.com/AdguardTeam/AdguardFilters/issues/24495

**Comment by Alex-302** [comment]
This is built-in banner(self-promo).
