### ISSUE TITLE
Mackolik app ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2451]
**App**: Mackolik

**Description**: Plz remove these white places.

**Screenshot 1**: 
![1x](https://cloud.githubusercontent.com/assets/19608513/16361546/95ba2136-3bad-11e6-8b00-dc3616561f0a.png)

----------------------------------------

**Screenshot 2**: 
![2x](https://cloud.githubusercontent.com/assets/19608513/16361547/a290a218-3bad-11e6-9cee-ac72a924c7a4.png)

----------------------------------------

**Screenshot 3**: 
![3x](https://cloud.githubusercontent.com/assets/19608513/16361550/b6b045b4-3bad-11e6-9dbe-d7838f6c99f0.png)

**Adguard version**: 2.6.108

**Operating system**: Android 5.0.2

**Comment by Alex-302** [comment]
I need a download link.

**Comment by thislife81** [comment]
Here you are: https://play.google.com/store/apps/details?id=com.kokteyl.mackolik&hl=en

**Comment by Alex-302** [comment]
It looks like built in the app.

**Comment by thislife81** [comment]
So, you can't remove these free spaces?

**Comment by Alex-302** [comment]
No
