### ISSUE TITLE
winsetupfromusb.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2452]
**Description**:
http://www.winsetupfromusb.com/downloads/
Не показываются спойлеры.

Screenshot:
http://prntscr.com/bl7aif
http://prntscr.com/bl79w0

Помогает отключение ЭФ и Annoyances.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@@||winsetupfromusb.com/wp-content/plugins/uk-cookie-consent/js/uk-cookie-consent-js.js
