### ISSUE TITLE
gofobo.com site and app - anti-adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2453]
**Description**: anti-adblock shows up when English filter is on

**Current behaviour**: anti-adblock page pops up

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16361617/ed9513de-3b9e-11e6-8832-0321e7a8f390.png)
![image](https://cloud.githubusercontent.com/assets/15856304/16361622/22e89880-3b9f-11e6-8379-62efd9e4c937.png)

</details>

**Steps to reproduce the problem**:

* enable English filter
*  go to gofobo.com on any device
*  see the pop up

1318448

**Comment by Alex-302** [comment]
Added to English filter
```
gofobo.com#%#(function() { var _setTimeout = window.setTimeout, regex = /bab_elementid/; window.setTimeout = function(a, b) { if ( typeof a !== 'string' || !regex.test(a) ) { _setTimeout(a, b); } }; })(); 
```
Added to Safari filter
```
@@||gofobo.com^$generichide
```
