### ISSUE TITLE
http://v.qq.com/ - anti-adblock script

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2454]
**Description**: http://v.qq.com/x/cover/ddnwcfwv7drw90w.html?vid=t0308jc3zna

**Current behaviour**: User experience anti-adblock message

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16361771/77939a7a-3ba3-11e6-990f-8bc66686ed07.png)

</details>

**Expected behaviour**: Tell us what should happen instead

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16361777/9b6193e4-3ba3-11e6-9f0a-fd7019220632.png)
</details>

**Steps to reproduce the problem**:

* It occurs randomly, I was able to reproduce it just one
*  Open the site, it'll load the anti-adblock before the video

**Adguard version**: the latest one

**Filters list**: basic set + EasyList China

**Operating system**: win10

**Browser**: Chrome

> Yes, I have installed the Anti-adblock killer | Reek filters in my tampermonkey、Adguard plugin（https://reek.github.io/anti-adblock-killer/#userscript） and subscript the list(https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt).
> However, the anti-adblock tips still shows.
> You must know that not all video in v.qq.com will show this, but I can give a specific video that 100% will show:
> http://v.qq.com/x/cover/ddnwcfwv7drw90w.html?vid=t0308jc3zna
1302096
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||livew.l.qq.com/livemsg?ty=web&ad_type=$domain=v.qq.com
```
