### ISSUE TITLE
Reddit sync - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2455]
> Adguard not blocking sync ads
> Yes i am talking about reddit sync. I have cleared both apps cache and
> uninstalled/reinstalled adguard. Adguard 2.5 worked perfectly but ecer
> since upgrading 2.6 it has been broken. There is a thread on android
> technical support forums with others experiencing same issues.

Screenshots:
http://www.imageup.ru/img125/2465198/1bag.jpg
http://www.imageup.ru/img125/2465199/2bag.jpg
App link:
https://play.google.com/store/apps/details?id=com.laurencedawson.reddit_sync&hl=en

HAR
[adguard har file.zip](https://github.com/AdguardTeam/AdguardFilters/files/333545/adguard.har.file.zip)

**Comment by Alex-302** [comment]
try
`||oauth.reddit.com/r/diy/about.json$replace=/"hide_ads": false/"hide_ads": true/ `
or
`||oauth.reddit.com/r/diy/about.json$replace=/"hide_ads": false\,/"hide_ads": true\,/i`

**Comment by evgeniy-ADG** [comment]
> I followed your directions, but there has been no change. I am attaching a
> screenshot 
> ![image](https://cloud.githubusercontent.com/assets/15856304/17429348/f22d1636-5af6-11e6-9b93-2f39d75611a9.png)

**Comment by Bohdan-SUP** [comment]
@Alex-302 any update?

**Comment by Alex-302** [comment]
no

**Comment by Alex-302** [comment]
@evgeniy-ADG 
так он пробовал правила по отдельности, как я написал, или сразу оба добавил?

**Comment by evgeniy-ADG** [comment]
[state (14).txt](https://github.com/AdguardTeam/AdguardFilters/files/628723/state.14.txt)

[debug.txt.zip](https://github.com/AdguardTeam/AdguardFilters/files/628724/debug.txt.zip)

Missed ad Sync for Reddit. Happened after a few seconds after opening
the app and browsing. Phone time right now is 12:49. Cleared app cache
and rebooted before taking logs.

**Comment by evgeniy-ADG** [comment]
@Alex-302 + a bunch of logs here: 1414045

**Comment by Alex-302** [comment]
@evgeniy-ADG 
https://github.com/AdguardTeam/AdguardFilters/issues/2455#issuecomment-229465559
`or`
