### ISSUE TITLE
http://www.ecostream.tv/ - doesn't show Start Stream button when refresh the page

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2457]
**Description**: http://www.ecostream.tv/stream/920d8eb07911c8a61ab786f978d3dc71.html

**Current behaviour**: Doesn't show Start Stream button when refreshing the page unless you disable content blocker

<details>
![20160626_121722000_ios](https://cloud.githubusercontent.com/assets/15856304/16362222/269471cc-3bb1-11e6-81f2-d9a78992ddd8.png)
</details>

**Expected behaviour**: Should not hide the button

<details>
![20160626_120840000_ios](https://cloud.githubusercontent.com/assets/15856304/16362224/365090fa-3bb1-11e6-8948-04ae079fffb9.png)
</details>

**Steps to reproduce the problem**:

* open the site, wait
*  refresh
*  see no button

**Adguard version**: 1.0.7.48

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.85.39 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.4 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.4 Enabled=YES
ID=6 Name="German filter" Version=1.0.25.58 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.55 Enabled=YES
ID=101 Name="EasyList" Version=1.0.58.91 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.59.4 Enabled=YES

**Operating system**: iOS

**Browser**: Safari
1324177
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
These filters can't break this site, only Russian
Try this rule:
```
ecostream.tv#@#.adwrapper
```

**Comment by evgeniy-ADG** [comment]
I can't add the rule:
<details>
![20160702_221305000_ios](https://cloud.githubusercontent.com/assets/15856304/16542688/650e8a78-40bb-11e6-94a5-00ff4ff19276.png)
![20160702_221301000_ios](https://cloud.githubusercontent.com/assets/15856304/16542689/65100768-40bb-11e6-9790-965fec0cc6cc.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
can you confirm the issue with this filters list?

**Comment by Alex-302** [comment]
Добавил в английский фильтр
```
ecostream.tv#@#.adwrapper
```
