### ISSUE TITLE
[NSFW] www.bravotube.net - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2458]
**Description**: http://www.bravotube.net/videos/nasty-sandy-toys-her-ass-and-pussy-with-a-cucumber?promoid=1255

**Current behaviour**: missed banner and placeholder, the add disappears after refreshing the page

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16362445/b934e330-3bb7-11e6-8a84-11af31b9a13e.png)

</details>

Adgard version**: 1.0.6.47

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.85.84 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.9 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.8 Enabled=YES
ID=6 Name="German filter" Version=1.0.25.64 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.25 Enabled=NO
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=NO
ID=210 Name="Spam404" Version=1.0.1.31 Enabled=NO

**Operating system**: iOS

**Browser**: Safari
1325606
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't confirm on iOS. Maybe optimized filters are enabled?
Try this for leftover
```
##iframe[width="300"][height="250"]
```

**Comment by evgeniy-ADG** [comment]
Optimized filter are enabled by default, no? Switched to non-optimized, added the rule. 
I've made that screenshot, and still can see that all with the rule, it does nothing. If you refresh the page, the ad is gone and the placeholder looks smaller, just like that
<details>
![20160702_220812000_ios](https://cloud.githubusercontent.com/assets/15856304/16542675/d4f7ba36-40ba-11e6-8ad1-a9ec107e2ec6.png)

**Comment by vozersky** [comment]
Are you guys talking about using simplified rules option? 
Because you can't switch to non-optimized rules in ios. It's different. 
Anyway, checked this on ipad using both simplifed and normal rules, all clear.

**Comment by evgeniy-ADG** [comment]
Its checked by default on iOS and you can't uncheck it. I think.

**Comment by evgeniy-ADG** [comment]
Now it's clean at my end too...
