### ISSUE TITLE
[iOS] hdrezka.me - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2459]
Basic filter set
http://hdrezka.me/series/thriller/47-sherlok-online.html#t:56-s:3-e:1

![](https://pp.vk.me/c631430/v631430430/40359/vOobeUwK3hA.jpg)

**Comment by Alex-302** [comment]
Чисто у нас.

**Comment by evgeniy-ADG** [comment]
а у меня казино вулкан вверху, по бокам баннров нет уже

**Comment by Alex-302** [comment]
@evgeniy-ADG 
в винде повторяется?

**Comment by evgeniy-ADG** [comment]
Нет, на Маке чисто, например. На iOS - есть
<details>
![20160719_112516000_ios](https://cloud.githubusercontent.com/assets/15856304/16948374/4c5283d0-4d82-11e6-95bd-96cc273a606c.png)
![20160719_112525000_ios](https://cloud.githubusercontent.com/assets/15856304/16948373/4c51fe2e-4d82-11e6-8170-535bb2318c92.png)

**Comment by Alex-302** [comment]
Фильтры оптимизированные или полные?

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
hdrezka.me##div[class^="skin-block_"]
hdrezka.me##table[class^="bn_"]
hdrezka.me##div[id^="bn_"]

```

**Comment by evgeniy-ADG** [comment]
Снова есть

**Comment by vmalyuta** [comment]
Проблема повторилась опять 
1488229

<details>
![unnamed](https://cloud.githubusercontent.com/assets/23701680/21962972/c569e80e-db39-11e6-9651-333ba0a6a615.png)
![unnamed 1](https://cloud.githubusercontent.com/assets/23701680/21962988/05fc1e3c-db3a-11e6-90f6-30a55e58f998.png)
<\details>

**Comment by Alex-302** [comment]
У меня чисто. Правила применяются как надо. 
Фильтры полные или упрощённые?

**Comment by deLumren** [comment]
Проблема до сих пор актуальна.
Safari, User Agent iOS 10 iPhone.
Пример:
<details>

![screen shot 2017-03-13 at 5 37 40 pm](https://cloud.githubusercontent.com/assets/26342177/23861930/43a1a4bc-0814-11e7-8ba7-ec2efea75c49.png)

</details>

Активные фильтры
<details>

![screen shot 2017-03-13 at 5 46 21 pm](https://cloud.githubusercontent.com/assets/26342177/23862198/10e117fa-0815-11e7-80bf-485d78824df0.png)
</details>

**Comment by Alex-302** [comment]
подправил

**Comment by sergeyvdovareize** [comment]
Когда сможете вырезать из видео упоминания о всяких казино?

**Comment by Alex-302** [comment]
@sergeyvdovareize например?
iOS сильно ограничивает возможности фильтрации, не всё и не везде можно заблокировать.
