### ISSUE TITLE
[NSFW] http://4porn.com - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2460]
http://4porn.com/de/search/marsha_may/

<details>
![](https://pp.vk.me/c631430/v631430430/40363/UYdMhrPb8O4.jpg)
</details>

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.85.84 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.9 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.8 Enabled=YES
ID=6 Name="German filter" Version=1.0.25.64 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.25 Enabled=NO
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=NO
ID=210 Name="Spam404" Version=1.0.1.31 Enabled=NO

**Comment by evgeniy-ADG** [comment]
@@||aifsansmystery.blogspot.in^$stealth
@@||aifsansmystery.blogspot.com^$stealth

I've added those few days back to user filter, as a temp workaround, so
that stealth mode doesn't work on these specific domains.
Adding those stealth mode exceptions does make blogs work, while letting me
keep stealth mode on for rest.

I've asked for all sites with the same issues.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
incorrect issue.

Added to Spyware filter
```
@@||static.webclicks24.com/js/common.js$domain=4porn.com
@@||cdn.webclicks24.com^$domain=4porn.com,image
```
