### ISSUE TITLE
GLWiZ app - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2461]
**Description**:
http://forum.xda-developers.com/showpost.php?p=67481688&postcount=1428

> Has anyone here tried using the streaming video app called GLWiZ with Adguard installed?

> https://play.google.com/store/apps/details?id=com.totrix.glwiz&hl=en

> The app normally displays ads before a channel loads but it hangs and crashes when Adguard is enabled. This doesn't happen with AdAway which manages to bypass the video ads and start playing channels right away.

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||imasdk.googleapis.com/native/sdkloader/native_sdk_$app=com.totrix.glwiz
@@||imasdk.googleapis.com/native/core/*/native_bridge_$app=com.totrix.glwiz
```
