### ISSUE TITLE
CRSTodayEurope.com & MoneyCanBuyLipstick.com - Blocked sites (AdGuard Social Media filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#24618]
### Affected sites:
```
https://crstodayeurope.com/
https://www.moneycanbuylipstick.com/
```

### Issue:
The sites are prevented from loading.

### Screenshots:
Not needed, as the problems are obvious.

### Problem filter:
* AdGuard Social Media filter

### Problem rules:
```
/selection-sharer.
##.nav-social
```

### Possible fixes:
```
@@/selection-sharer.$domain=crstodayeurope.com
~moneycanbuylipstick.com##.nav-social
```

### Reference:
https://github.com/ryanbr/fanboy-adblock/issues/610/

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.1.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by Alex-302** [comment]
Fixed

**Comment by Alex-302** [comment]
Sorry, fixed.

**Comment by THEtomaso** [comment]
Turns out that a couple of  CRSTodayEurope's sister sites are affected by the `/selection-sharer.` rule too.
These are the other two domains:
```
https://crstoday.com/
https://millennialeye.com/
```
Sorry for not checking this before.

**Comment by THEtomaso** [comment]
@Alex-302:

The `/selection-sharer.` rule has been completely removed from '**Fanboys Social Blocking List**' now:
`https://github.com/easylist/easylist/commit/d5f7ff00d19e54672ecacb40414932cacc1c0ea3#diff-c4effd8e3cbe114908e64a208df1cb6a`

Perhaps it should be removed from '**AdGuard Social Media filter**' too?
Otherwise, could you please add the necessary exceptions for the 5 sites that I mentioned in my previous post?

**Comment by Alex-302** [comment]
Ok, it seems it is problematic. Removed. Thanks.
