### ISSUE TITLE
[Android] The Chive app

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#2462]
https://play.google.com/store/apps/details?id=com.thechive&hl=en

**Description**: The app doesn't go beyond starting screen when Adguard is on

**Current behaviour**: see the description

**Steps to reproduce the problem**:

* Install the app
*  Start it

**Adguard version**: 2.6 latest beta

**Filters list**: standard

**Operating system**: Android

**Browser**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by jlinn75** [comment]
im having the same issue.version 2.6.108 of adguard

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||api.branch.io/v1/install
```

**Comment by jlinn75** [comment]
still having the issue

**Comment by Alex-302** [comment]
Thanks, fixed.
Please wait for mobile filter update.
