### ISSUE TITLE
File Commander - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2463]
**Description**:
https://play.google.com/store/apps/details?id=com.mobisystems.fileman

Source:
https://forum.adguard.com/index.php?threads/%D0%A0%D0%B5%D0%BA%D0%BB%D0%B0%D0%BC%D0%B0-%D0%B2-file-commander.11393/#post-88621

**Comment by TPS** [comment]
#2337?

**Comment by Alex-302** [comment]
@TPS 
yes.

This banner is built in apk. But It was gone on my device after clearing of cache.
