### ISSUE TITLE
life.ru  - annoying subscription offer

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#2466]
str:
- goto life.ru
- scroll, click on articles, do anything
- usually appears after few seconds but could take longer open some article

![9xtcm_er1nq](https://cloud.githubusercontent.com/assets/17472907/16387883/6e0239ce-3c9f-11e6-91be-a348e4a31cb4.jpg)

![9zcnrkucyww](https://cloud.githubusercontent.com/assets/17472907/16388271/11462342-3ca1-11e6-83bf-1106a13536d7.jpg)

скрины от юзера
на маке стабильно повторяется, на винде не очень

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
life.ru#$#div[class^="arcticmodal-"] { display: none!important; }
life.ru#$#.modal-open { overflow: initial!important; } 
```

**Comment by Alex-302** [comment]
Удалил. Ломают авторизацию.
