### ISSUE TITLE
[Windows] www.computerbase.de - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#2467]
![](http://i.imgur.com/OtJNFDs.png)

https://www.computerbase.de/downloads/systemtools/entwicklung/visual-studio-2015/

``` computerbase.de##.adbox-wrapper ```

**Adguard version**: 6.1.232.1142

**Operating system**: Windows 10

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added.
