### ISSUE TITLE
missed ad kinoshek.net

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2468]
Повторился пропуск рекламы на kinoshek.net
Появляется плеер с видеороликом. 
![2016-06-29_10-29-48](https://cloud.githubusercontent.com/assets/16462533/16444081/fdd53c7c-3de4-11e6-85f6-34112b8e19db.png)

Фильтры Adguard, обновлены.

Кастомер, говорит, чтовидео заблокировал, но звук остался.

**Comment by Alex-302** [comment]
Он скрыл, а не заблокировал видео.
Поправил.
