### ISSUE TITLE
http://bbs.feng.com/ ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2469]
**Description**: http://bbs.feng.com/ shows ads on iPhone

Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16444885/f2e2882a-3de8-11e6-8db4-4461a2b6a029.png)
![image](https://cloud.githubusercontent.com/assets/15856304/16444893/f973566a-3de8-11e6-8eb0-a6a03078c38c.png)

</details>

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.83.50 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.59 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.65 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.57.61 Enabled=YES
**Operating system**: ios

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
на ipad не повторилось, только на iphone

**Comment by Alex-302** [comment]
Added to English filter
```
||s.polkoa.com^
```

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/17323691/ba24d2bc-58ab-11e6-9a6c-7722434b9ea3.png)
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.90.16 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.88 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.16 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.95 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.62.77 Enabled=YES

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||cell.zhybzp.cn^$third-party
```
