### ISSUE TITLE
http://kachelmannwetter.com/de/ ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2470]
**Description**: Missed ads

**Current behaviour**: http://kachelmannwetter.com/de/ shows ads / placeholders

Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16445510/a856de20-3deb-11e6-8f2f-e523ba0886a5.png)
on my end, with ipad it's a placeholder:
![](https://pp.vk.me/c631431/v631431430/38810/AyjkPIWaVQs.jpg)
</details>

**Adguard version**: 1.0.7.48

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.87.65 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.46 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.46 Enabled=YES
ID=6 Name="German filter" Version=1.0.25.99 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.72 Enabled=YES

**Operating system**: ios

**Browser**: safari

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
1327755

**Comment by Alex-302** [comment]
For user filter:
`kachelmannwetter.com##.spacer-lh-2`
we can't remove them safely.
