### ISSUE TITLE
m.apotheken-umschau.de - white transparent page

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2471]
**Description**: false blocking

**Current behaviour**: http://m.apotheken-umschau.de/
White, transparent field on this site. The reason for the white box is your annoyance-filter which blocks the cookie information on this site!

Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16445823/286a81c4-3ded-11e6-9025-ee532847a4d2.png)
</details>

**Adguard version**: 1.0.7.48

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.87.31 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.42 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.36 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.0.85 Enabled=YES
ID=6 Name="German filter" Version=1.0.25.93 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.7 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.69 Enabled=YES

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
I can't open mobile site on iPad, seems to be working fine on my device.

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
@@||m.apotheken-umschau.de/js/wub/AMD/Components/CookieConsent.js

```
