### ISSUE TITLE
http://www.pcmag.com/ - the site is broken by content blocker; page shows no text

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2472]
**Description**: http://www.pcmag.com/news/345570/apple-removes-encryption-from-ios-10-kernel-which-could-pay

**Current behaviour**: "The site has failed..." pop-up appears and if you scroll down, you'll see images only, without text

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16446842/688ffbb2-3df2-11e6-8de8-b3049c88c47d.png)
</details>

**Expected behaviour**: 

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16446873/8d5db466-3df2-11e6-93c9-e53a70862612.png)

</details>

**Steps to reproduce the problem**:

* open the link
*  wait 1-2 seconds
*  see the issue

**Adguard version**: 1.0.7.48

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.87.58 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.45 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.44 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.71 Enabled=YES
**Operating system**: ios

**Browser**: safari
1262812
1327526
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by vozersky** [comment]
Повторяется. Плюс предложение подписки на весь экран при входе.

**Comment by Alex-302** [comment]
Фильтры может старые? Недавно чинил вроде.

**Comment by vozersky** [comment]
Фильтры обновлял.

**Comment by evgeniy-ADG** [comment]
Аналогично, предложение подписки я запилил отдельно неск. дней назад.

**Comment by Alex-302** [comment]
Прямо сейчас проверял в Сафари на Маке - всё нормально.
@vozersky можешь проверить ещё раз?

**Comment by vozersky** [comment]
@Alex-302 проверил сейчас, все ок.
