### ISSUE TITLE
missed ads mobiltelefon.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2473]
Пропущена Яндекс.Директ на http://mobiltelefon.ru/
Фильтры обновлены, фильтры Adguard. Проблема повторилась.

![mt2](https://cloud.githubusercontent.com/assets/16462533/16451831/fa7f8266-3e0d-11e6-8941-b39adbb8798e.JPG)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||mobiltelefon.ru/lib/proxy.php?r
```
