### ISSUE TITLE
[Android] ru.appforge.domino

### ISSUE THREAD

**Issue by ajnao** [AdguardTeam/AdguardFilters#2474]
[https://play.google.com/store/apps/details?id=ru.appforge.domino](https://play.google.com/store/apps/details?id=ru.appforge.domino)

Новая игра , Крест и после завершения игры идет показ рекламы других игр с предложением скачать .

<a href="http://fastpic.ru/view/61/2016/0629/4b53b224824b075028bbf78ba1601670.png.html" target="_blank"><img src="http://i61.fastpic.ru/thumb/2016/0629/70/4b53b224824b075028bbf78ba1601670.jpeg" border="0"></a> <a href="http://fastpic.ru/view/61/2016/0629/763d07c4df55eefc3fb6593def27b7ea.png.html" target="_blank"><img src="http://i61.fastpic.ru/thumb/2016/0629/ea/763d07c4df55eefc3fb6593def27b7ea.jpeg" border="0"></a>

**Comment by Alex-302** [comment]
It is a builtin self-promo.
