### ISSUE TITLE
timesnownews.com

### ISSUE THREAD

**Issue by ghajini** [AdguardTeam/AdguardFilters#24758]
## URL(s) where the issue occurs

`https://www.timesnownews.com/`

### Describe the issue

`Live tv` doesn't start here

### Screenshot(s)

![screenshot 56](https://user-images.githubusercontent.com/20338483/47909177-20784580-deb5-11e8-9b28-8e3ce32d5505.png)

### Versions

- Browser/version: google chrome 70 stable
- adguard browser extension stable
### Settings

-  adguard default settings

**Comment by ghajini** [comment]
yes works

**Comment by AdamWr** [comment]
Thank you for checking, added.
