### ISSUE TITLE
[Extension] Short delay in new.vk.com site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2476]
**Description**: "Likes" appear with a delay

Screenshot:

<details>
No screenshots but we have so-so screencast: 
https://vid.me/FInr
1) Сначала включено расширения, я ставлю лайки и там задержка.
2) Я показываю настройки расширения.
3) Я выключаю расширения и ставлю лайки-и они ставятся сразу и без задержек.
Исправьте пожалуйста.

Проверил в других браузерах везде этот баг! С расширением не возможно нормально ставить лайки... 
Задержка значительная, особенно если листаешь новости более пяти минут, там очень большая задержка, и особенно когда много лайков на записи...
Я выключал расширение и также ставил лайки-там мгновенно работает без расширения.
Исправьте этот баг пожалуйста!
</details>

**Filters list**: waiting for data

**Operating system**:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16455275/5ef57814-3e1c-11e6-9ba4-dfdcb4a57a73.png)

</details>
**Browser**: all available

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
Ждем инфо по фильтрам итд, поддержка не смогла повторить буквально нигде и никто. Посмотрите видео, вы видите задержку? Я не особо, если честно... Пользователь настаивает, что проблема есть и из-за нее невозможно нормально ставить лайки.

**Comment by Alex-302** [comment]
Сказки. У меня что с Адгардом, что без него длительность запроса не изменяется - 100-200 мс. Это объективные данные из инструментов разработчика.

**Comment by vozersky** [comment]
Можно покопать насчет стороннего софта, никто не лезет в https, http еще? антивирусы, сторонние расширения?
