### ISSUE TITLE
Russian filter affects Bing search

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2477]
**Description**: User gets blank page when opening Bing search results

**Current behaviour**: The page is blank

Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16482280/b9e03822-3eb7-11e6-9765-1edc8dda98ec.png)
![image](https://cloud.githubusercontent.com/assets/15856304/16482285/c65754be-3eb7-11e6-92a6-25e078abe12f.png)

</details>

**Steps to reproduce the problem**:

*  I search Bing for "test" 
*  and when I click on the links
* I getting blank page
* the moment I unload Russian filter everything works fine... 

 I using the iphone 5s with the last iOS (9.3.2) and everything is up to date (including adguard filters etc.) if you need more info let me know... For now like temporary solution I just will keep Russian filter disabled...

**Adguard version**: 1 0 7

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.87.69 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.46 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.47 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.0.97 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.35.76 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.8 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.74 Enabled=YES
ID=101 Name="EasyList" Version=1.0.59.83 Enabled=NO
ID=103 Name="Bulgarian list" Version=1.0.0.8 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.60.77 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.64 Enabled=YES
**Operating system**: ios

**Browser**:
1147641
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
I can't reproduce this on iPad, @Serzh-SUP please check it on iPhone.

**Comment by evgeniy-ADG** [comment]
Ok, we can't reproduce on iPhone with the latest updates. @Alex-302 please advise.

**Comment by Serzh-SUP** [comment]
Все проверил, у меня проблемы не наблюдается, хотя, раньше, помню была такая ситуация, что перейти на сайт с bing не получалось, как у пользователя. Протестировал со всеми фильтрами польз.

**Comment by Alex-302** [comment]
Фильтры полные или оптимизированные?
Пусть проверит без этих
ID=103 Name="Bulgarian list" Version=1.0.0.8 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.60.77 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.64 Enabled=YES

**Comment by evgeniy-ADG** [comment]
оптимизированные у нас, у пользователя - не знаю. это видно в логах где-то?.. если нет, и если это важно вот в таких кейсах, нужно бы вывести в лог... запилить?

**Comment by Alex-302** [comment]
В логе есть начало работы конвертера, например вот так:
```
2016-07-04 10:11:56:243 Adguard[69347:2503] Javascript Info: 2016-07-04T07:11:56.243Z: Safari Content Blocker Converter v1.3.8
2016-07-04 10:11:56:244 Adguard[69347:2503] Javascript Info: 2016-07-04T07:11:56.244Z: Converting 47295 rules. Optimize=false
```
Добавил в фильтр Сафари:
`@@||bing.com/fd/ls/GLinkPing.aspx?`
