### ISSUE TITLE
[Extension] https://e.mail.ru/messages/inbox/ - placeholder

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2478]
![image](https://cloud.githubusercontent.com/assets/15856304/16484559/753ca308-3ec2-11e6-8ec5-9baa7d5fb857.png)

English filterVersion 1.0.87.83. Updated 30 june 2016 at 03:00.
Spyware filterVersion 1.0.6.46. Updated 27 june 2016 at 17:07.
Social media filterVersion 1.0.10.52. Updated 29 june 2016 at 16:01.
Annoyances filterVersion 1.0.1.8. Updated 29 june 2016 at 21:08.
Russian filterVersion 1.0.35.85. Updated 29 june 2016 at 20:00.
Experimental filterVersion 1.0.26.12. Updated 30 june 2016 at 01:00.
Mobile Ads filterVersion 1.0.4.9. Updated 28 june 2016 at 19:01.
EasyList ChinaVersion 1.0.61.7. Updated 30 june 2016 at 09:07.
Liste FRVersion 1.0.60.94. Updated 30 june 2016 at 13:02.

Chrome 51.0.2704.106 m, Win 10
Adguard AdBlocker 2.3.8

**Comment by evgeniy-ADG** [comment]
Иногда там появляется Яндекс.директ.

**Comment by Alex-302** [comment]
сегодня был? Его вчера или позавчера заблокировали для хромовского расширения.

**Comment by evgeniy-ADG** [comment]
был в момент оформления заявки, скрин мой. Сегодня тожде есть
![image](https://cloud.githubusercontent.com/assets/15856304/16542594/e9e74f5e-40b7-11e6-9019-b73e2f46a4a8.png)

**Comment by Alex-302** [comment]
Не вижу там директа. Остатков у меня тоже не видно, но их здесь лишний раз лучше не трогать, т.к. правила корявые получаются.

**Comment by evgeniy-ADG** [comment]
Жалоба не на дтиркет, на на плейсхолдер, как в теме ишью, и как на первом скрине. Плейсходер расширением не убрать?
