### ISSUE TITLE
swefilm.tv

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2479]
**Description**:
Missed banner at the bottom of a page.

Screenshot:
<details>
<img width="1057" alt="2016-06-30_2020" src="https://cloud.githubusercontent.com/assets/5947035/16497596/826fd9f8-3f00-11e6-863d-78fa9af3bdc8.png">
</details>

**Comment by Alex-302** [comment]
I don't see this banner without Adguard and with Swedish VPN

**Comment by ameshkov** [comment]
Yep, no banner indeed. However there is a popup ad. Click on films images several times to see it.

**Comment by cabban** [comment]
the banner is SE NU blue banner under pictures for films, its malicious sites when press there kinn regrds

**Comment by Alex-302** [comment]
Check these rules:
```
swefilm.tv##a[href="http://loading.swefilm.tv/watch/"]
swefilm.tv#$#a[href="lnk.html"] { pointer-events: none!important; cursor: default; } 
```

**Comment by cabban** [comment]
i add these swefilm.tv##a[href= <http://swefilm.tv/#%23a[href=>"
http://loading.swefilm.tv/watch/"]
swefilm.tv#$#a[href= <http://swefilm.tv/#$%23a[href=>"lnk.html"] {
pointer-events: none!important; cursor: default; }
but i dont Think any happened , im suck at this i dont understand , check
these rules makes own rules etc

2016-07-12 17:21 GMT+02:00 Alex <notifications@github.com>:

**Comment by cabban** [comment]
pop up swefilm
https://owlplayz.com/registration?theme=m-2-panther&chan=&pubid=74706051&sid=&a_bid=&a_aid=53a08c804c089&data1=&prgid=&cpnid=&clickid=adkm_9cHYqgJgJqeG6Bg-5eTpwPH9p2Uh7gVKYxLc4jRfsfTzUDqOOYNNCKqbr-sIIT7_AG-f6o7lDy7NX7X8g8NsAM8BH8DmT3WWfZFcPchi8ht6B_R9C6iXf5NMCV-8HwBPr1ilpa2du4lIOw7Xruvh3aO8FrYR7bDC4iLV6IYlM6cdIXNp8CfDpnzpsi84WqCVD2O2rlqZDo3ydLmDo3mdXkLZ13-VaREftCMh4Xca73Vam3JX0VY8oOvyFoEKq_Ywa8KYz0Ssz1znS5SJ8WlBz2JFQmc2mqX6hFQN-9Ee4Qx3ooKg83NT0hU-k47ul9r5M4U7Uk0If414rjqJKamKXsK7UPttksb1UCjf5XAOe62WNTZ6JUpfrzAobIXuN7GHbw21BZ_aFFxK1W9ICb8Nh3TIXvGPZgxtXjqQTk1BgNaukCb8fHUQBs16YTAa04RKDmiz-yNnBHsLYoq08TmR0l0wuFOmey8L3CC2DmKekVs75BiIvLc7F6Wk2pk6keBZ6Q&subid=&subid2=&subid3=&subid4=&subid5=&page=m-2-panther&var1=&var2=&CID=&dp2=&XYZ=&ymid=&sspdata=&ce_cid=&ref=1468338040&g=aa250780586748e22460533d56a62fef

2016-07-12 17:28 GMT+02:00 Superswede AWESOME <niclas.cabban@gmail.com>:

**Comment by cabban** [comment]
https://123plays.com/registration?theme=m-2-panther&chan=&pubid=5343&sid=&a_bid=&a_aid=65f4g4dfgsdfb1dfgh&data1=&prgid=&cpnid=&clickid=102279b5318b1cfbef5ec0ef6a5cfc&subid=&subid2=&subid3=&subid4=&subid5=&page=m-2-panther&var1=&var2=&CID=&dp2=&XYZ=&ymid=&sspdata=&ce_cid=&ref=1468338074&g=1440ae7a3769eac93198575354b85046

2016-07-12 17:41 GMT+02:00 Superswede AWESOME <niclas.cabban@gmail.com>:

**Comment by Alex-302** [comment]
Where? I need a url of source page.

**Comment by cabban** [comment]
AND that i gave to u :) it is not correct?

2016-07-12 17:42 GMT+02:00 Alex <notifications@github.com>:

**Comment by Alex-302** [comment]
No, I need address of the page, where you got popups

**Comment by cabban** [comment]
Https://Www.swefilm.tv had many annoying pop up ads

Skickat med AquaMail för Android
http://www.aqua-mail.com


På 12 juli 2016 20:04:10 Alex <notifications@github.com> skrev:

**Comment by Alex-302** [comment]
Which filters, OS and browser are you using?

**Comment by cabban** [comment]
@Alex-302 

![image](https://cloud.githubusercontent.com/assets/19514493/16891685/16cec79a-4afe-11e6-949f-58f0b03c16bd.png)

**Comment by Alex-302** [comment]
@cabban 
Added to English filter
```
swefilm.tv#$#a[href^="data:text/html;base64"] { position: absolute!important; top: -2000px!important; }
```

**Comment by cabban** [comment]
no its not gone its popping up up many times, :/

2016-07-18 20:54 GMT+02:00 Alex <notifications@github.com>:

**Comment by Alex-302** [comment]
Did you add this rule to user filter?

**Comment by cabban** [comment]
aha thats the thing i must do ., i idnt know that :) i test

2016-07-18 21:13 GMT+02:00, Alex <notifications@github.com>:
