### ISSUE TITLE
WATCH ABC app - player is broken or missing ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2480]
**Description**:
The app itself:
https://play.google.com/store/apps/details?id=com.disney.datg.videoplatforms.android.abc&hl=en

User report:

> I installed the play store Watch ABC app.  I see it in the Adguard Firewall.  I open the app and choose one of the featured episodes and one of two things happens, ADS play or video doesn't play(depending on episode chosen).  Is this a filter problem or something else?

**Comment by Alex-302** [comment]
It works only in USA. Tried with Tunnel Bear and got a network error in the player without Adguard, with Orbor - infinity loading.
Asked for a log.
