### ISSUE TITLE
yahoo.com 

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#24801]
`https://www.yahoo.com/news`

Ads on the tablet version of Firefox. Try this user-agent to trigger them: `Mozilla/5.0 (Android 4.4; Tablet; rv:41.0) Gecko/41.0 Firefox/41.0`.

![yahoo](https://user-images.githubusercontent.com/35470489/47950534-5e677f00-df32-11e8-899e-1effbd4d2d57.png)

Adguard Base + Mobile + spa,por + RUS filters
uBlock Origin
Firefox on an Android tablet

**Comment by Alex-302** [comment]
I don't see this element. Please upload saved page.

**Comment by adranger** [comment]
Have you tried that user-agent? You can test it with this extension: https://addons.mozilla.org/addon/user-agent-string-switcher/

I've found out the ads are actually supposed to be displayed as the news headlines, but when hiding rules are applied and hide the image, only that text remains.

[yahoo.zip](https://github.com/AdguardTeam/AdguardFilters/files/2552441/yahoo.zip)

**Comment by Alex-302** [comment]
Please check this rule
`yahoo.com##ul[class^="Mb(0)"] > li.js-stream-content:has(> div > a[rel="nofollow noopener noreferrer"]+div:contains(Patrocinado))`

**Comment by adranger** [comment]
It works. Will you add it to the Portuguese list, since the language of that text depends on your IP?

**Comment by Alex-302** [comment]
Added

**Comment by adranger** [comment]
@Alex-302 

Mozilla/5.0 (Android 7.1.2; Mobile; rv:74.0) Gecko/74.0 Firefox/74.0

[https://www.yahoo.com/news](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.yahoo.com/news/) 

[frontpage.zip](https://github.com/AdguardTeam/AdguardFilters/files/4177426/frontpage.zip)


`yahoo.com###YDC-Stream>ul>li:has(span:has-text(/^Ad$/))` :

![yahoo](https://user-images.githubusercontent.com/35470489/74098725-21594780-4afa-11ea-9dc5-34c008b6b8be.png)

----

[https://news.yahoo.com/sanders-buttigieg-backers-turn-up-the-volume-trading-barbs-at-new-hampshire-dinner-040944763.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://news.yahoo.com/sanders-buttigieg-backers-turn-up-the-volume-trading-barbs-at-new-hampshire-dinner-040944763.html) 

[article.zip](https://github.com/AdguardTeam/AdguardFilters/files/4177420/article.zip)


* Top ad banner - `yahoo.com##div[data-locator="subtree-root"]:has(a:has-text(/^Anúncio$/))`

* App banner at the bottom of the comments section:

![yahoo2](https://user-images.githubusercontent.com/35470489/74107439-cef64600-4b4e-11ea-9ff1-8b5e757cfb61.png)

----
![yahoo-app-banner](https://user-images.githubusercontent.com/35470489/74107819-a3755a80-4b52-11ea-8586-e86791f3a544.png)

**Comment by Alex-302** [comment]
please check this rule 
`yahoo.com#?##YDC-Stream > ul > li.js-stream-content:has(> div > div > span > a[href^="http://help.yahoo.com/kb/index?page=content&y="][rel="nofollow noopener"])`

**Comment by adranger** [comment]
That rule works for the frontpage.

**Comment by Alex-302** [comment]
Ok, added.
