### ISSUE TITLE
Блокировка лишних элементов Яндекс

### ISSUE THREAD

**Issue by Hawkrus** [AdguardTeam/AdguardFilters#2481]
Блокирует карту погоды **Я**ндекс:
![yandex_1](https://cloud.githubusercontent.com/assets/19652388/16515267/b0bafbc0-3f79-11e6-9c57-975cb76e714f.PNG)
А должно быть так:
![yandex_2](https://cloud.githubusercontent.com/assets/19652388/16515275/b8781f32-3f79-11e6-9c1b-dc76c7d0dbe6.PNG)
Версия Adguard 6.0.226.1108
Браузер Chrome 51.0.2704.103 m
Windows 7

**Comment by Alex-302** [comment]
Поправил.
