### ISSUE TITLE
"BlockAdblock" is blocking AdGuard on the webpage CONNECTwww.com

### ISSUE THREAD

**Issue by Yevhen1996** [AdguardTeam/AdguardFilters#24827]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Anti AdBlocker "BlockAdblock". 
* **Current behaviour**: "BlockAdblock" is blocking AdGuard on the webpage CONNECTwww.com

[//]: # (Substitute this line with a description of the problem)

[//]: # 
<img width="2047" alt="screen shot 2018-11-04 at 12 07 24 am" src="https://user-images.githubusercontent.com/39196837/47957873-c9fb2c00-dfc6-11e8-9a14-c9b32784c136.png">

<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

https://connectwww.com/category/websites/

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by krystian3w** [comment]
`@@||connectwww.com^$generichide`
