### ISSUE TITLE
avito.ru

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#2482]
"Adblock polskie reguły" breaks the page.

reproduced on:
os x 
win 
ios

str:
1. turn on the filter
2. goto https://www.avito.ru/moskva
screenshot: <details>
![screenshot 2016-07-01 12 08 58](https://cloud.githubusercontent.com/assets/17472907/16517357/9fd455fc-3f85-11e6-87cd-d5e5139c3e84.png)
  </details>
3. turn the filter off and refresh the page
screenshot: <details>
![screenshot 2016-07-01 12 15 32](https://cloud.githubusercontent.com/assets/17472907/16517360/a5b4542c-3f85-11e6-89fa-4e46933c0153.png)
 </details>

**Comment by Alex-302** [comment]
Добавил в англ
avito.ru#@#[class$="-ads"]
