### ISSUE TITLE
ukr.net

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2484]
**Description**:
ukr.net. Мобильная версия сайта
При переходе по вкладкам в разделе "Новости", типа "Политика", "Экономика" и т.д. идет долгая загрузка страницы:
http://prntscr.com/bnt29c

"enabledFilterIds" : [ 2, 3, 4, 14, 1, 11 ],

Вроде бы как помогает отключение фильтра счетчиков и систем аналитики

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||partner.googleadservices.com/gpt/pubads_impl_$domain=ukr.net

```
