### ISSUE TITLE
Яндекс директ

### ISSUE THREAD

**Issue by Hawkrus** [AdguardTeam/AdguardFilters#2485]
Снова появился Яндекс директ https://pogoda.yandex.ru/moscow/

![screenshot_2016-07-02-22-17-17](https://cloud.githubusercontent.com/assets/19652388/16542098/5bbcc6aa-40a3-11e6-923c-b6de41a8c15c.png)

Android, 2.6.108

**Comment by Alex-302** [comment]
Проверьте обновление. У меня код баннера другой.

**Comment by Hawkrus** [comment]
Проблема исчезла, можно закрывать.
