### ISSUE TITLE
http://www.sinefan.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2486]
**Site**: http://www.sinefan.com/

**Screenshot**: 
![sinefan](https://cloud.githubusercontent.com/assets/19608513/16544417/a75eb0b8-410d-11e6-93d4-d315858a2632.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
`##div[class^="sag-reklam"]`
is generic now.
