### ISSUE TITLE
https://www.filmlimani.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2488]
**Site**: https://www.filmlimani.com/

**Screenshot**: Background picture
![filmlimani](https://cloud.githubusercontent.com/assets/19608513/16544435/5d7c650c-410e-11e6-92fe-2b0ca327ed4b.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Clean
