### ISSUE TITLE
http://www.tekparthdkeyfi.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2491]
**Site**: http://www.tekparthdkeyfi.com/korkak-robert-fordun-jesse-james-suikasti-izle.html

**Screenshot**: 
![sinefan](https://cloud.githubusercontent.com/assets/19608513/16355932/84cd1dd8-3ae0-11e6-8bef-7e8e9c3fa9b3.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
tekparthdkeyfi.com##a[href^="http://goo.gl/"] > img
tekparthdkeyfi.com#$#.iframe { display: block!important; }
tekparthdkeyfi.com##.ad
```
