### ISSUE TITLE
http://www.hdsonbolumizle.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2492]
**Site**: http://www.hdsonbolumizle.com/arka-sokaklar-407-bolum-izle-tek-parca-24-haziran-2016.html

**Screenshot**: 
![sinefan](https://cloud.githubusercontent.com/assets/19608513/16355527/78f61072-3ad2-11e6-82b0-d930c7993159.png
)

**Adguard version**: 2.3.8

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdsonbolumizle.com#%#document.cookie = "popundr=1"; 
hdsonbolumizle.com##.ad
hdsonbolumizle.com#$#.iframe { display: block!important; }

```
