### ISSUE TITLE
Сортировка фильтров

### ISSUE THREAD

**Issue by bogachenko** [AdguardTeam/AdguardFilters#24926]
Почему в вашем расширении нет возможности добавлять фильтры по ссылкам, как отдельные фильтры, они все правила идут в ~одно место~ в Пользовательский список? Если я захочу добавить не один, а скажем два или три листа, которых **нет** в представленных фильтров у вас по умолчанию и я не хочу все складировать в одном месте, ведь это просто не удобно, как мне быть?

Шо цэ таке?

**Comment by Alex-302** [comment]
В 3.0 будет такая возможность.
