### ISSUE TITLE
http://www.filmizlef.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2493]
**Site**: http://www.filmizlef.com/yedinci-ogul-izle-turkce-altyazili-2014-seventh-son.html

**Screenshot**: 
![sinefan](https://cloud.githubusercontent.com/assets/19608513/16358369/a9803d3c-3b2a-11e6-9d19-13fc2e6d36c3.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
filmizlef.com###share-cerceve
```
