### ISSUE TITLE
http://www.ultrahdfilmizle.org/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2494]
**Site**: http://www.ultrahdfilmizle.org/olaylar-olaylar-yerli-film-izle.html/

**Screenshot**: 
![sinefan](https://cloud.githubusercontent.com/assets/19608513/16360963/e511167a-3b96-11e6-82d9-6ed9ccb027aa.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
ultrahdfilmizle.org###rekgecAlan
ultrahdfilmizle.org#$##plAlan { display: block!important; }
ultrahdfilmizle.org#%#AG_onLoad(function() { window.openNewTab = function() {}; } ); 

```

**Comment by thislife81** [comment]
Plz remove this facebook comment on the same
![c](https://cloud.githubusercontent.com/assets/19608513/16783098/b0c7370a-4893-11e6-85a0-8bff74e56e58.png)

**Comment by Alex-302** [comment]
Disable this exclusion in social filter
```
@@||facebook.com/plugins/comments
```

**Comment by thislife81** [comment]
This rule not worked, can you give me another rule?

**Comment by Alex-302** [comment]
```
ultrahdfilmizle.org###beyaz2 > h3.yrmbas.bir:nth-child(2)
ultrahdfilmizle.org##.fb-comments
```
