### ISSUE TITLE
http://otukenim.org/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2495]
**Site**: http://otukenim.org/2016/06/film-izle/9184

**Screenshot**: 
![otukenim](https://cloud.githubusercontent.com/assets/19608513/16544486/d192c8a8-4110-11e6-8329-651e1d957bab.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
otukenim.org###Video-Oncesi
otukenim.org#$##Movie-video { display: block!important; }
||geoloc2.geovisite.ovh/private/geocounter.js$domain=otukenim.org

```
