### ISSUE TITLE
http://www.bicaps.net/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2496]
**Site**: http://www.bicaps.net/arizona-ruyasi-arizona-dream-1992-turkce-dublaj-1080p-full-hd-izle/

**Screenshot**: 
![sinefan](https://cloud.githubusercontent.com/assets/19608513/16355574/bca55c00-3ad3-11e6-906f-2542b96d3dda.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
bicaps.net###alt
```
