### ISSUE TITLE
http://birhdfilm.org/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2497]
**Site**: http://birhdfilm.org/sinbad-besinci-seyahat-2014-full-izle.html

**Screenshot**: Add this rule for background: birhdfilm.org#$#body {background-image: none!important; }
![sinefan](https://cloud.githubusercontent.com/assets/19608513/16361143/b5c8a682-3b9e-11e6-805f-d01d7e2e2a21.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
birhdfilm.org###alt
birhdfilm.org###filmoncereklam
birhdfilm.org#$##film { display: block!important; }
birhdfilm.org#$#body { background: #000000!important; }

```
