### ISSUE TITLE
http://www.fullhdfilmizlebe.org/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2498]
**Site**: http://www.fullhdfilmizlebe.org/cocuklar-icin-uygun-degil-izle.html

**Screenshot**: 
![fullhdfilmizlebe](https://cloud.githubusercontent.com/assets/19608513/16544544/88a73a86-4113-11e6-9b2d-8297f71186be.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
fullhdfilmizlebe.org###toolbar
fullhdfilmizlebe.org###VideOnrekLam
fullhdfilmizlebe.org#$##kendisi { display: block!important; }
```

**Comment by thislife81** [comment]
![r](https://cloud.githubusercontent.com/assets/19608513/16783551/87541742-4895-11e6-98d7-b20504a9bbfb.png)

Plz remove this too

**Comment by thislife81** [comment]
![mn](https://cloud.githubusercontent.com/assets/19608513/16784067/1a352482-4898-11e6-8d04-e732f01b094b.png)

Social widget

**Comment by Alex-302** [comment]
IMHO we shouldn't block then, they are not share buttons.
