### ISSUE TITLE
http://webteizle.org/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2499]
**Site**: http://webteizle.org/film/duygularin-rengi-the-help-altyazili-izle.html

**Screenshot**: 
![webteizle](https://cloud.githubusercontent.com/assets/19608513/16544622/8802c4ea-4115-11e6-8e2e-3b8df4fc8e99.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
webteizle.org##div[id^="reklam"]
webteizle.org#$##kendisi { display: block!important }

```

**Comment by thislife81** [comment]
![x](https://cloud.githubusercontent.com/assets/19608513/16783357/b3ab76ec-4894-11e6-9127-f1e70c5a4f1b.png)

**Comment by thislife81** [comment]
PLZ REMOVE THIS

![1](https://cloud.githubusercontent.com/assets/19608513/16798817/f0412420-48fe-11e6-8aec-e7f06d8291b5.png)

**Comment by thislife81** [comment]
PLZ REMOVE THIS

![1a](https://cloud.githubusercontent.com/assets/19608513/16798867/2888c798-48ff-11e6-96ac-cab614ca97f0.png)

**Comment by Alex-302** [comment]
Done

**Comment by thislife81** [comment]
Please remove this completely

![z](https://cloud.githubusercontent.com/assets/19608513/16902253/f82cb054-4c6a-11e6-9609-fbbc7489ca7a.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
webteizle.org##a[onclick^="$('#reklam"]
```
