### ISSUE TITLE
http://www.hdfulltekpart.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2500]
**Site**: http://www.hdfulltekpart.com/

**Screenshot**: When i click any link in this site, opens a new page. New page link is this: http://www.diziizlev.org/
![hdfulltekpart](https://cloud.githubusercontent.com/assets/19608513/16545025/3c27b912-4125-11e6-98ec-d56eff3998ac.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdfulltekpart.com##.pageNoFollow_hilite
hdfulltekpart.com#%#document.cookie = "popundr=1";

```

**Comment by thislife81** [comment]
![s](https://cloud.githubusercontent.com/assets/19608513/16782946/0ce4a79e-4893-11e6-9d32-144c9b816c44.png)
And plz remove this banner

**Comment by thislife81** [comment]
Click on background.. I mean, here: 

![ass](https://cloud.githubusercontent.com/assets/19608513/18032843/84366fe8-6d24-11e6-88da-258ba92802d7.png)

You will get a popup, The link of popup is this : http://www.hddiziizle.kim/arkadaslar-iyidir-1-bolum-izle-28-agustos-2016-pazar.html

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hddiziizle.kim#%#document.cookie = "popundr=1"; 
hddiziizle.kim###pageskin

```
