### ISSUE TITLE
http://www.hdfilmsaati.org/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2501]
**Site**: http://www.hdfilmsaati.org/simulasyon-izle.html

**Screenshot**: 
![hdfilmsaati](https://cloud.githubusercontent.com/assets/19608513/16545050/246d2810-4126-11e6-9972-af0945c99c50.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
fixed

**Comment by thislife81** [comment]
Share buttons are again shown
