### ISSUE TITLE
http://www.hdfilmdeposu.net/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2502]
**Site**: http://www.hdfilmdeposu.net/

**Screenshot**: Background picture
![hdfilmdeposu](https://cloud.githubusercontent.com/assets/19608513/16545962/c2c5fe9e-4142-11e6-94ce-f7344636c5ee.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdfilmdeposu.net##.yildiz-pageskin-link
```
