### ISSUE TITLE
http://goodgame.ru/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2503]
**Description**:
http://goodgame.ru/channel/ArrowNet/
В плеере при просмотре стрима в течении 15 сек идет реклама:
![f0d344d892e44f67bd0b40252433ecb9](https://cloud.githubusercontent.com/assets/18548949/16552728/054f7c66-41cc-11e6-9d70-fa39cc9c862b.png)
Фильтры обновлены.

**Comment by Alex-302** [comment]
Странно. Это просто плеер twich. У меня всё чисто. Какие у него фильтры?

**Comment by vgavrish** [comment]
в других плеерах у меня есть реклама
Фильтры:
http://prntscr.com/bq8ll8

**Comment by Alex-302** [comment]
А можешь пример скинуть в скайп?

**Comment by vgavrish** [comment]
у меня уже нет рекламы

**Comment by Alex-302** [comment]
Ладно. Пока закрою. Какая-то она призрачная эта реклама
