### ISSUE TITLE
Odnoklassniki

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2505]
**Description**:
https://play.google.com/store/apps/details?id=ru.ok.android&hl=ru

При пролистывании ленты наблюдается реклама:
http://prnt.sc/bokqu8

Лог. время 11:31
[debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/346064/debug.txt)

"enabledFilterIds" : [ 2, 3, 4, 5, 14, 1, 11 ]
Фильтры обновлены.

**Comment by Alex-302** [comment]
Нужно записать HAR файл по инструкции из KB, только сперва закрыть приложение.

**Comment by vgavrish** [comment]
написала
если что будут здесь: 1253463

**Comment by Alex-302** [comment]
постоянно патрулировать не имею возможности, лучше пусть сообщит кто-нибудь

**Comment by vgavrish** [comment]
Har тут: 668185

**Comment by Alexeygw** [comment]
тут :-)

**Comment by Alex-302** [comment]
Try to copy this rule to user filter. HTTPS filtering must be enabled.
```
||api.ok.ru/api/batch/execute$replace=/({"pattern":"BANNER")[\s\S]*}\,/
```
it should to remove banner code between {  }
```
,{"pattern":"BANNER","title_tokens":[{"text":"none"}],"message_tokens":[{"text":"none"}],"banner":"{\"bannerId\":\"21780065\",\"templateId\":\"media\",\"header\":\"Усилитель слуха\",\"info\":\"analogplus.tvoi-mag.org\",\"text\":\"Современный усилитель слуха по уникальной цене!\",\"actionType\":\"navigate\",\"iconType\":\"square\",\"icon\":\"https://r.mradx.net/img/C2/AF38A0.jpg\",\"}]}","bannerExpiration":1469103353720,"delete_id":"AX_","feed_stat_info":"030000000"},{"pattern":"CONTENT"
```

**Comment by vgavrish** [comment]
отписала

**Comment by Alexeygw** [comment]
668185
Внёс правило в список, очистил кэш приложения, пролистав ленту сообщения с рекламой не обнаружил. Но очень много стало в приложении "рекомендованные приложения"
От этих сообщений может тоже можно избавиться?! 
Да и реклама значительно реже, но появляется.

**Comment by Alex-302** [comment]
Значит не работает правило.

**Comment by Alexeygw** [comment]
Получается частично работает, или всё же где то в кеше хранится информация о рекламе. Вообщем, что делать то дальше?

**Comment by vgavrish** [comment]
Есть какие-то изменения по фильтрации?
Новый har нужен?

**Comment by Alexeygw** [comment]
Изменений нет, а реклама в приложении есть.

Вот на пример приложение для Android  ВКонтакте,  приложении и при помощи специального  инженерного кода   *#*#856682583#*#* можно  включить дополнительные настройки ВКонтакте.
Не уже ли здесь такого нет. 


-- 
Алексей Гречишкин

**Comment by Alex-302** [comment]
@vgavrish 
> Har новый попросила

ок, ждём.

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/21265264/53bc3fba-c3a9-11e6-91f8-e34e1880c41e.jpg)

**Comment by Alex-302** [comment]
тут всё сложно, пока отложим
