### ISSUE TITLE
timesofindia.com anti-adblock

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2506]
**Description**:
http://www.businesstoday.in/technology/news/do-you-enable-adblock-you-may-have-to-bid-adieu-to-them-now/story/234498.html

Website:
http://timesofindia.com/
http://m.timesofindia.com/

You may need to use VPN to get to these websites.

**Comment by ameshkov** [comment]
@Alex-302 don't forget about iOS. As I understand, it's enough to add $elemhide exception

**Comment by Alex-302** [comment]
Added to English filter
```
@@||timesofindia.indiatimes.com/ads.cms
@@||timesofindia.com^$generichide
@@||timesofindia.com/adsblocker.cms
```

**Comment by ameshkov** [comment]
Still does not help in case of Android:
http://forum.xda-developers.com/showpost.php?p=67679995&postcount=1466

**Comment by Alex-302** [comment]
* http://www.businesstoday.in/technology/news/do-you-enable-adblock-you-may-have-to-bid-adieu-to-them-now/story/234498.html
Adguard is turned off
<details>
![image](http://imagizer.imageshack.com/img922/7094/aSpET9.png)
</details>
* http://m.timesofindia.com/india/India-carefully-studying-South-China-Sea-verdict/articleshow/53173984.cms
works fine
Is it possible to request for remote access? I can look it on user's PC.

**Comment by ameshkov** [comment]
@Alex-302 it seems that mobile website works fine. However it does not in case of browser extensions.

**Comment by Alex-302** [comment]
Added to English filter
```
businesstoday.in###adbocker_alt
```
I can visit timesofindia.com on desktop. It is redirects to http://timesofindia.indiatimes.com/

**Comment by evgeniy-ADG** [comment]
http://timesofindia.indiatimes.com/india/Mahasweta-Devi-eminent-writer-and-social-activist-dies/articleshow/53432761.cms
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17211117/2589196c-54d0-11e6-8a89-27c231e8d450.png)
</details>
Chrome 52, Extension beta, 
English filterVersion 1.0.90.2. Updated 27 july 2016 at 08:00.
Spyware filterVersion 1.0.6.84. Updated 26 july 2016 at 23:00.
Social media filterVersion 1.0.11.11. Updated 26 july 2016 at 16:38.
Annoyances filterVersion 1.0.2.10. Updated 26 july 2016 at 20:02.
Russian filterVersion 1.0.37.4. Updated 26 july 2016 at 23:00.
Experimental filterVersion 1.0.26.20. Updated 28 july 2016 at 01:30.
Mobile Ads filterVersion 1.0.4.35. Updated 26 july 2016 at 22:02.
Adblock polskie regułyVersion 1.0.4.37. Updated 26 july 2016 at 17:36.
Polski social filtrVersion 1.0.0.2. Updated 31 march 2016 at 17:06.

**Comment by Alex-302** [comment]
fixed 
https://github.com/AdguardTeam/AdguardFilters/issues/2568

**Comment by evgeniy-ADG** [comment]
It's back: m.timesofindia.com
![screenshot 10-16am aug 12 2016](https://cloud.githubusercontent.com/assets/15856304/17615329/22738710-6076-11e6-9d64-0c180ea1e03f.png)

**Comment by Alex-302** [comment]
Added to mobile filter
```
@@||m.timesofindia.com/ads_js.cms
m.timesofindia.com##.ad1.nocss
```
Added to Spyware filter
```
@@||b.scorecardresearch.com/beacon.js$domain=m.timesofindia.com
@@||google-analytics.com/analytics.js$domain=m.timesofindia.com
@@||tags.crwdcntrl.net/*.js?ns=^$domain=m.timesofindia.com
@@||static.chartbeat.com/js/chartbeat.js$domain=m.timesofindia.com
```

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/17809267/03160c50-661e-11e6-94ea-d16aba5c4661.png)
back again, reproduce on mac os x with iphone user agent

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||static.clmbtech.com^$domain=timesofindia.com,script

```

**Comment by evgeniy-ADG** [comment]
It's back.

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=m.timesofindia.com
@@||static.chartbeat.com/js/chartbeat.js$domain=m.timesofindia.com
@@||tags.crwdcntrl.net/c/*/cc.js?ns=$domain=m.timesofindia.com
```

**Comment by evgeniy-ADG** [comment]
It's back
http://m.timesofindia.com/
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/19597951/73e6c286-97a0-11e6-9ef4-df01b39622d3.png)

eng, Russian, safari, mobile ads

**Comment by Alex-302** [comment]
Can't reproduce at the moment. Which filters are enabled?
