### ISSUE TITLE
Реклама в системном приложении xiaomi

### ISSUE THREAD

**Issue by besonov** [AdguardTeam/AdguardFilters#25064]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by besonov** [comment]
Реклама в системном приложении Безопасность (очистка) и на рабочем столе

**Comment by besonov** [comment]
![screenshot_2018-11-08-21-21-06-735_com miui cleanmaster](https://user-images.githubusercontent.com/44876546/48221085-829be380-e3aa-11e8-9ee1-ec32a1dea140.png)
![screenshot_2018-11-08-21-20-40-877_com miui home](https://user-images.githubusercontent.com/44876546/48221097-8cbde200-e3aa-11e8-98fa-bb385d5d6339.png)

**Comment by Alex-302** [comment]
@besonov какой у вас Адгард? Можете записать лог запросов по этой инструкции?
https://kb.adguard.com/ru/android/solving-problems/log#web
И нужно знать название приложения - Package Name

**Comment by Alex-302** [comment]
Должно помочь правило, если после `=` вставить `package name`
`||graph.facebook.com^$app=`

**Comment by besonov** [comment]
У меня Adguard 2.12Приложение:  com.miui.securitycenter (подраздел очистка)Ещё второе место где лезет баннер, это рабочий стол в месте отображения времени и даты. Это приложение календарь com.android.calendarОтчёт отправил по инструкции на adguard.com, логи выгрузил, во вложении.23:37, 8 ноября 2018 г., Alex <notifications@github.com>:@besonov какой у вас Адгард? Можете записать лог запросов по этой инструкции?
https://kb.adguard.com/ru/android/solving-problems/log#web
И нужно знать название приложения - Package Name

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Alex-302** [comment]
А где логи? При ответе через почту вложения сюда не загружаются.
Проверьте такое правило:
`||graph.facebook.com^$app=com.miui.securitycenter`

**Comment by besonov** [comment]
Я прошу прощения, я нуб. 
[Uploading adguard_logs_2.12.247_0911_0054.zip…]()
[Uploading AdguardFilters-master.zip…]()
Не пойму как проверить правило.
Вот, что вижу в Adguard
![screenshot_2018-11-09-15-48-04-618_com adguard android](https://user-images.githubusercontent.com/44876546/48261109-59756480-e437-11e8-9d17-c0c954bc13e6.png)
![screenshot_2018-11-09-15-48-23-918_com adguard android](https://user-images.githubusercontent.com/44876546/48261110-5a0dfb00-e437-11e8-911d-35fba6d159b8.png)
![screenshot_2018-11-09-15-48-32-052_com adguard android](https://user-images.githubusercontent.com/44876546/48261111-5a0dfb00-e437-11e8-908e-3fff37b21152.png)

**Comment by Alex-302** [comment]
Не, это фейсбук. Он нам не нужен.
Логи не прикрепились, быстро нажали Отправить.

Правило нужно добавить в пользовательский фильтр(скопировать) - Меню -> Настройки -> Собственный фильтр. Нажмите на зелёную круглую кнопку и вставьте скопированное правило - ||graph.facebook.com^$app=com.miui.securitycenter

**Comment by besonov** [comment]
Прошу прощения за задержку с ответом.
[adguard_logs_2.12.247_0911_0054.zip](https://github.com/AdguardTeam/AdguardFilters/files/2576989/adguard_logs_2.12.247_0911_0054.zip)

**Comment by besonov** [comment]
Выполнил рекомендации по настройке правила, не помогло.

**Comment by besonov** [comment]
Запись экрана не грузится. Прилагаю скрины
![screenshot_2018-11-13-20-05-39-209_com adguard android](https://user-images.githubusercontent.com/44876546/48426463-4a1c5100-e780-11e8-9160-405d7b5eea01.png)
![screenshot_2018-11-13-20-09-56-287_com miui cleanmaster](https://user-images.githubusercontent.com/44876546/48426464-4a1c5100-e780-11e8-8f8a-0e1cb2329148.png)
![screenshot_2018-11-13-20-05-17-509_com adguard android](https://user-images.githubusercontent.com/44876546/48426466-4ab4e780-e780-11e8-9e54-dda3aec0a7fd.png)

**Comment by Alex-302** [comment]
Или чтоб не копировать, можно импортировать эту ссылку
https://gist.githubusercontent.com/Alex-302/81ff59d26dd08d4180157c647a804fe8/raw/ed71539a25ba3df488c49b5d7cf0490cb32146fe/xiaomi

**Comment by besonov** [comment]
[adguard_logs_2.12.247_1511_1729.zip](https://github.com/AdguardTeam/AdguardFilters/files/2585480/adguard_logs_2.12.247_1511_1729.zip)

**Comment by besonov** [comment]
Правило к сожалению не помогло

**Comment by Alex-302** [comment]
@zzebrum Можешь у себя проверить?

**Comment by besonov** [comment]
Не совсем понял. Я скачал архив АG_android_test, в нём два текстовых файла, мне нужен один, я так понимаю.

**Comment by besonov** [comment]
![screenshot_2018-11-16-08-40-36-407_com android htmlviewer](https://user-images.githubusercontent.com/44876546/48598244-646e4e80-e97b-11e8-876f-2f83addf170c.png)
Что с ним делать?

**Comment by Eugene-Savenko** [comment]
@zzebrum в поддержку все еще с этим обращаются. помогите разобраться, пож-та.

**Comment by TheHasagi** [comment]
@besonov 

Зайдите пожалуйста в системные настроки - в строке поиска наберите "Рекомендации" далее "Отключить показ рекомендаций". Перезагрузите устройство и проверьте еще раз.

**Comment by TheHasagi** [comment]
Closed.

Should be reopened if needed.

**Comment by besonov** [comment]
Для Евгения. Ничего не помогло, баннер в помощнике поверх  поисковой строки и поверх часов/календаря лезет раз в сутки стабильно. Хоть баннер и АлиЭкспрессный, в adguard в этот момент разные гугловские сервисы активны. Добавлял кучу правил, бестолку. Ещё и партнёр adguard Яндекс директ кое где появляется, но не критично. И бороться, я так понял, с партнёрами бесполезно.
По поводу советов, вроде, отключить рекомендации, почистить кэш , отключить rsa и прочее. Не помогает. Прошивка RU. На международной в другом телефоне помогало.

**Comment by Alex-302** [comment]
> Ещё и партнёр adguard Яндекс директ кое где появляется, но не критично. И бороться, я так понял, с партнёрами бесполезно.

Мы Яндекс Директ нигде не разблокируем. Они обходом блокировщиков занимаются.

Включите запись HAR, перезапустите телефон, и после запуска Адгарда запустите это приложение. Если появится реклама(а она может быть закэширована либо встроена в приложение), выключите защиту и загрузите HAR сюда(архивом ZIP)
https://kb.adguard.com/ru/android/solving-problems/har

**Comment by Eugene-Savenko** [comment]
@Alex-302 HAR от другого пользователя вот тут: 1104748

**Comment by Eugene-Savenko** [comment]
@Alex-302 там обновили фильтры, очистили кеш и ответили, что не помогло.

**Comment by Alex-302** [comment]
Пусть попробуют приложению закрыть доступ в сеть и очистить его кэш. Подозреваю, что реклама встроена, просто периодически в фоне обновляется.
