### ISSUE TITLE
uploadocean.com [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#25088]
**Site**: https://uploadocean.com/11uq2e3a0i2m

**Issue**: Please remove the fake links as seen in the screenshot.

**Screenshot**: http://prntscr.com/lg6suv

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 70.0.3538.77 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.13 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Spam 404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by AdamWr** [comment]
It seems that they change these links, added:
```
uploadocean.com##.resp-container
uploadocean.com##form > a[href]:not([href*="uploadocean.com"]) > img
||kotaroyalliving.com/ad*.php
```
