### ISSUE TITLE
indiatoday.in is detecting adblock.

### ISSUE THREAD

**Issue by jakop345** [AdguardTeam/AdguardFilters#2508]
indiatoday.in is detecting adblock.

Ex:http://indiatoday.intoday.in/technology/story/flipkart-delivery-boy-replaces-12-iphones-with-fake-ones/1/707080.html

Screenshot:
![image](https://cloud.githubusercontent.com/assets/15250559/16567006/87f5c4c0-4237-11e6-86c1-4f0ad1a55a27.png)

pls solve this

**Steps to reproduce the problem**:

* 
*  
*  

**Adguard version**:

**Filters list**:

**Operating system**:
windows 7
**Browser**:
chrome
screenshot:```<details></details>```**Steps to reproduce the problem**:* *  *  **Adguard version**:**Filters list**:**Operating system**:**Browser**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed. Please check for updates.
