### ISSUE TITLE
calciomercato.com

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#2509]
http://www.calciomercato.com/news/il-besiktas-incontra-la-juve-per-neto-e-isla-tentativo-anche-per-165384

reproduced on mac, google chrome

![original](https://cloud.githubusercontent.com/assets/17472907/16584369/5d36e8e4-42c4-11e6-927b-602d07cefb6a.jpg)

**Comment by Alex-302** [comment]
duplicate
