### ISSUE TITLE
calciomercato.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2510]
**Description**:
http://www.calciomercato.com/news/balotelli-vincero-il-pallone-d-oro-240829

**Current behaviour**: Adblocking detection

Screenshot: 
<details>
![screen shot 2016-07-05 at 4 37 19 pm](https://cloud.githubusercontent.com/assets/14153331/16586528/13250faa-42cf-11e6-90de-5d4c34a7cca1.png)

</details>

**Filters list**:
![screen shot 2016-07-05 at 4 38 51 pm](https://cloud.githubusercontent.com/assets/14153331/16586509/faa36788-42ce-11e6-8d37-8f6d45139d49.png)

**Browser**: Chrome/Safari

**Comment by Alex-302** [comment]
Added to English filter
```
@@||adv.calciomercato.com/api/ads/banners|
```

**Comment by evgeniy-ADG** [comment]
http://www.calciomercato.com/news/dani-alves-pjanic-e-higuain-la-juve-va-all-in-per-vincere-subito-986579

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17128635/d4fa4c2e-5316-11e6-97c0-8c86091724f3.png)

</details>

Reproduced with extension beta, chrome 52 Mac

**Comment by Alex-302** [comment]
Old rule is replaced by
`@@||adv.calciomercato.com/api/ads/banners?`
