### ISSUE TITLE
http://akvus35.ru/ missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2511]
http://akvus35.ru/kak-v-iphone-5-nastroit-vosproizvedenie-fotografij-s-iphone-na-ekrane-televizora

![image](https://cloud.githubusercontent.com/assets/15856304/16611955/0ecc6ab8-436d-11e6-980c-0d68444bb3ff.png)

<details>
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.87.99 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.49 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.57 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.1.14 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.35.92 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.12 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.10 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.76 Enabled=YES

**Comment by Alex-302** [comment]
akvus35.ru##.jqmOverlay
akvus35.ru###sb_popup
