### ISSUE TITLE
[NSFW] http://www.txxx.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2512]
http://www.txxx.com/videos/1345923/bonnie-rotten-david-christopher-mark-wood-in-best-of-devil-s-film-scene-07/?promo=10376
<details>
![20160706_083241000_ios](https://cloud.githubusercontent.com/assets/15856304/16612038/88f48686-436d-11e6-8cca-50ed278365c0.png)
![image](https://cloud.githubusercontent.com/assets/15856304/16612063/9cf77ac6-436d-11e6-9f95-d87dde5c031e.png)

**Comment by Alex-302** [comment]
Added to English filter
```
||txxx.com/js/*.php?z=*&sub=
txxx.com##.vda-iv
txxx.com##div[class^="adv-"]
||direct.txxx.com/_ra_lib.js

```
