### ISSUE TITLE
http://www.mediamarkt.nl/ - EasyPrivacy causes the issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2513]
1212314

Incorrect blocking on page:
http://www.mediamarkt.nl/

Everywhere I click, i get a loading spinning wheel. Please fix this.  I am always up to date with the lists before I sent an email. The problem is within easy privacy filter, disabling easyprivacy, it works correct. 

Here you go, just took a screenshot:

![image](https://cloud.githubusercontent.com/assets/15856304/16612438/abe76652-436f-11e6-8cb5-f1b11b97d709.png)

**Comment by Alex-302** [comment]
С нашим фильтром аналитики тоже ломается вроде
Добавил в фильтр аналитики
```
@@||google-analytics.com/analytics.js$domain=mediamarkt.nl
@@||googletagmanager.com/gtm.js$domain=mediamarkt.nl
@@||google-analytics.com/plugins/ua/ec.js$domain=mediamarkt.nl

```
