### ISSUE TITLE
http://vlinderscrime.nl/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2514]
http://vlinderscrime.nl/

filters
<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.0.87.97 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.6.49 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.10.56 Enabled=YES

ID=8 Name="Dutch filter" Version=1.0.8.83 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.0.76 Enabled=YES

ID=106 Name="EasyList Dutch" Version=1.0.61.5 Enabled=YES

ID=207 Name="Adblock Warning Removal List" Version=1.0.60.97 Enabled=YES

ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
</details>
Screenshots
<details>
the first open
![image](https://cloud.githubusercontent.com/assets/15856304/16612851/da47a6c2-4371-11e6-802e-0854d8b28fc2.png)

after refreshing the page
![image](https://cloud.githubusercontent.com/assets/15856304/16612857/e52bbee8-4371-11e6-97a7-e91667e25711.png)
</details>

I tried to remove the adds on this page by 'removing all elements on this page'. When I start this page as new, all adds are still visible. 

When I refresh the page, the ad blocker does its work.

**Comment by Alex-302** [comment]
I can't resolve ab issue with the first visiting, maybe it is iOS or Adguard problem. Ask in iOS repo about it.

Added to Dutch filter
```
vlinderscrime.nl##a[href="http://mariska-o.nl/"]
||diomerc.com/baner/
||vlinderscrime.nl/wp-content/uploads/*/*banner*.
```
