### ISSUE TITLE
Yandex navigator camera problem

### ISSUE THREAD

**Issue by Y2Kot** [AdguardTeam/AdguardFilters#25150]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

Последние 2 обновления ломают яндекс навигатор, скрывая камеры с интерфейса навигатора.
Лог программы - https://yadi.sk/d/HGGAWoharZTjbg

**Comment by Y2Kot** [comment]
скрин навигатора?

**Comment by Y2Kot** [comment]
![zzhbnvd0ucm](https://user-images.githubusercontent.com/4283562/48334682-8c546e00-e66c-11e8-837e-d64907a10e57.jpg)
![q5npu3o3b-4](https://user-images.githubusercontent.com/4283562/48334690-91192200-e66c-11e8-9ac7-eb32e53756ac.jpg)
С включернным из выключенным AdGuard

**Comment by Y2Kot** [comment]
При этом голосом навиагатор предупреждает

**Comment by Alex-302** [comment]
@Y2Kot Скрины фильтров не нужны. Лучше из приложения создавать отчёт, в котором будет вся необходимая информация.

У меня камеры отображаются верно. Отключение фильтров, не выключая Адгард, помогает?

<details>

![image](https://user-images.githubusercontent.com/8361299/48346730-b7e35280-e684-11e8-9e3d-dcc1e020fc90.png)

</details>

@zebrum проверь у себя ещё.

**Comment by Y2Kot** [comment]
@Alex-302 я попытался сделать в приложении (ссылка в первом сообщении) но он создает архивы 0байт

**Comment by Y2Kot** [comment]
отключил все фильтры, камер так и нет

**Comment by Alex-302** [comment]
Попробуйте в настройках приложений отключить фильтрацию этого приложения. Если не поможет - отключите для него фильтрацию HTTPS.
Фильтры можно включить, т.к. не влияют.

**Comment by karina-archazh** [comment]
@Y2Kot а уточните, пожалуйста, вашу версию Навигатора?

**Comment by Y2Kot** [comment]
@karina-archazh 3.47 от 07.11.2018, сборка 305.
@Alex-302 https был отключен. После отключения "пропускать трафик приложения через Adguard" камеры появились

**Comment by zzebrum** [comment]
@Y2Kot а DNS включен в настройках AdGuard?

**Comment by Y2Kot** [comment]
@zebrum нет

**Comment by karina-archazh** [comment]
@Y2Kot А когда последний раз у вас обновлялись карты в приложении?

**Comment by Y2Kot** [comment]
@karina-archazh 10 октября. Сейчас обновлений нет.

**Comment by karina-archazh** [comment]
@Y2Kot Можно вас попоросить с выключенным адгардом переустановить карту в Яндекс Навигаторе и проверить?

**Comment by Alex-302** [comment]
@karina-archazh посмотри, к каким доменам обращаетсяпосле очистки данных. Возможно в исключения HTTPS что-то нужно добавить.

**Comment by Y2Kot** [comment]
@Alex-302 так а какая разница, если для навигатора https отключён?

**Comment by karina-archazh** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #2311](https://github.com/AdguardTeam/AdguardForAndroid/issues/2311) via [**ZenHub**](https://www.zenhub.com/)
