### ISSUE TITLE
http://uvenco.co.uk/ - cookie notification has been missed

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2516]
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.13 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.35 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.10.27 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.1.14 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.89 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.35.92 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.10 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.76 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.49 Enabled=NO
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.64 Enabled=YES
ID=221 Name="Polski social filtr" Version=1.0.0.2 Enabled=NO
ID=222 Name="Adblock-Persian list" Version=1.0.0.7 Enabled=NO

![image](https://cloud.githubusercontent.com/assets/15856304/16613600/86477b34-4375-11e6-93ec-dec0fe12c01b.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
uvenco.co.uk##.top > div.alert
```
