### ISSUE TITLE
http://adultmult.tv/ - ads?

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2517]
![image](https://cloud.githubusercontent.com/assets/15856304/16613673/fc98b79e-4375-11e6-8ac3-fa03f498dfb6.png)

Видеореклама, запускается сама, во всех браузерах

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||vseokino.com/rotator/
```

**Comment by vgavrish** [comment]
Можно ли убрать фон на http://adultmult.tv/ и оставить без картинки?
chrome
http://prntscr.com/dv3ywx

**Comment by Alex-302** [comment]
@vgavrish 
в пользовательский
```
adultmult.tv#$#.menuposition { margin-top: 0px!important; }
||adultmult.tv/img/bckg
```

**Comment by vgavrish** [comment]
спасибо!
