### ISSUE TITLE
http://free-torrent.org/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2518]
http://free-torrent.org/

<details>
![image1](https://cloud.githubusercontent.com/assets/15856304/16614175/531c803a-4378-11e6-966b-d577f4e8ef1b.PNG)
</details>

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.32 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.52 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.69 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.1.29 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.36.8 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.77 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.49.54 Enabled=NO
ID=212 Name="RU AdList: Counters" Version=1.0.46.11 Enabled=NO
ID=213 Name="RU AdList: BitBlock" Version=1.0.45.88 Enabled=NO

**Comment by Alex-302** [comment]
Нужен скрин. Некоторую рекламу в иОС не заблокировать.

**Comment by evgeniy-ADG** [comment]
скрин под спойлером

**Comment by Alex-302** [comment]
@vozersky глянь плиз, повторяется ли?

**Comment by vozersky** [comment]
@Alex-302 да, повторил с этими фильтрами

@evgeniy-ADG  ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES   вот это всегда очень смущает в issue с пропусками рекламы, мало ли, что там может быть :)

**Comment by Alex-302** [comment]
@vozersky а проверь только с русским и английским.

**Comment by vozersky** [comment]
@Alex-302 тоже есть реклама сверху, прогружается долго и вообще страничка подвисает после этого.

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
free-torrent.org,free-torrents.org##div[id^="b_pr_"]
```

**Comment by vozersky** [comment]
http://free-torrent.org/forum/indexer1.php

проверял на os x, chrome extension 2.3.8, стандартный набор (ру, en, соц, счетчики, раздражители)
при переходе в любой раздел\тему открываются рекламные вкладки:

![screen shot 2016-08-19 at 20 34 44](https://cloud.githubusercontent.com/assets/17472907/17818486/732cbf74-664c-11e6-9604-0ec6c0f0b429.png)

**Comment by Alex-302** [comment]
@vozersky 
у меня даже в Сафари чисто. Сделай скрин вкладки Network в dev tools

**Comment by vozersky** [comment]
@Alex-302 в хроме сегодня не повторяется, все ок

**Comment by Alex-302** [comment]
ок, закрываю

**Comment by evgeniy-ADG** [comment]
![screen shot 2016-09-09 at 8 47 21 pm](https://cloud.githubusercontent.com/assets/15856304/18396931/a412713c-76ce-11e6-96bd-8fa617903bec.png)

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.93.86 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.60 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.40 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.3.68 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.38.98 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.84 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.24 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.49.54 Enabled=NO
ID=212 Name="RU AdList: Counters" Version=1.0.46.11 Enabled=NO
ID=213 Name="RU AdList: BitBlock" Version=1.0.45.88 Enabled=NO

</details>

Looks clear in safari with the user-agent, btw

**Comment by Alex-302** [comment]
@evgeniy-ADG нужен файл контент-блокера.
