### ISSUE TITLE
[Extension] http://www.ncbi.nlm.nih.gov/pubmed/ - placeholder

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2519]
**Description**: large grey blocks on top

**Current behaviour**: missed ad leftover or someting like that

Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16614696/433afe0a-437b-11e6-8861-8a9a7d9f3128.png)

</details>

**Expected behaviour**: Works fine with the standalone app

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16614641/035d9aa4-437b-11e6-9072-7a57018f0148.png)

</details>

**Steps to reproduce the problem**:

* enable extension
*  go to the site 
*  see that blocks

**Adguard version**: the latest extension

**Filters list**: gneral

**Operating system**: win, linux based os

**Browser**: opera, chrome

1338508
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
>Filters list: gneral
what does it mean? Only English(+ one language) filter is enabled by default.
Added to English filter
```
@@||ncbi.nlm.nih.gov^$jsinject
```
