### ISSUE TITLE
Adguard Assistent

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2521]
Не появляется на https://rsdn.ru/ 
От браузера не зависит. В https исключениях сайта нет.

![2](https://cloud.githubusercontent.com/assets/16462533/16619122/71e2a0cc-4395-11e6-90cf-75cf4f9d747b.jpg)

**Comment by Alex-302** [comment]
Там фреймы. Мы в них не инжектимся.
