### ISSUE TITLE
http://www.auto-motor-und-sport.de - anit-adblock script

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2522]
http://www.auto-motor-und-sport.de/news/fuehrerschein-zwangsumtausch-soll-frueher-kommen-11476958.html?block=1
Screen:
http://s019.radikal.ru/i611/1607/1f/44c92bc5ba65.png

user 1337070

**Comment by Alex-302** [comment]
Added to German filter
```
@@||auto-motor-und-sport.de^$generichide
```

**Comment by shaurmanchic** [comment]
It appeared again
![capture](https://cloud.githubusercontent.com/assets/14258460/16994515/56ce2a7e-4eb0-11e6-9589-3f49bde58b65.PNG)

**Comment by Alex-302** [comment]
@shaurmanchic don't forget to remove the "Fixed" label.
Added to German filter
```
@@||js.adscale.de/map.js
```
Added to Annoyances filter
```
||push.esputnik.com.ua^$third-party
auto-motor-und-sport.de##div[element-structure-cookiemonster]
```
Added to Social filter
```
auto-motor-und-sport.de##div[element-article-sharing]
```

**Comment by Freeglobe** [comment]
Please open this Issue, Page doesn't work now:
http://www.auto-motor-und-sport.de/news/fuehrerschein-zwangsumtausch-soll-frueher-kommen-11476958.html?block=1

**Comment by Alex-302** [comment]
Added to German filter
```
@@||auto-motor-und-sport.de/werb.gif
```

**Comment by Freeglobe** [comment]
It works well now! Thanks a lot!

**Comment by Freeglobe** [comment]
It appeared again
Page doesnt work now! Please open the issue.

![image](https://cloud.githubusercontent.com/assets/20925096/18316190/f85d4b6a-7519-11e6-93bc-9d50d28f3f12.png)

**Comment by Alex-302** [comment]
Fixed
