### ISSUE TITLE
https://www.fxp.co.il - blocks useful soundcloud element

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2523]
https://www.fxp.co.il/showthread.php?t=17396517

Screen:
http://s017.radikal.ru/i441/1607/a8/e39a0b4ce1bc.png
http://s45.radikal.ru/i110/1607/5a/a0947bec08d5.png

user 1336424

**Comment by Alex-302** [comment]
Added to English filter
```
fxp.co.il#@#iframe[width="300"][height="250"]
```
