### ISSUE TITLE
http://animalreader.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2524]
All images are blocked:

![image](https://cloud.githubusercontent.com/assets/15856304/16621390/bda9c2a2-439e-11e6-8647-932607b1db67.png)

How it should be:

![image](https://cloud.githubusercontent.com/assets/15856304/16621404/c608f576-439e-11e6-9b1c-4ba6edcf4f8a.png)

ID 1065108

**Comment by Alex-302** [comment]
Fixed
