### ISSUE TITLE
http://ipatriot.com/god-grants-increase/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2525]
http://ipatriot.com/god-grants-increase/

![image](https://cloud.githubusercontent.com/assets/15856304/16621484/115cf838-439f-11e6-94f5-27f4e27a3791.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
ipatriot.com###iPatriotWrite
```
