### ISSUE TITLE
http://ipatriot.com/god-grants-increase/ - ads and sponsored content

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2526]
http://ipatriot.com/god-grants-increase/

![image](https://cloud.githubusercontent.com/assets/15856304/16621581/6d9a442a-439f-11e6-9f17-d61e2b3483dd.png)

Basic filter, up to date. Chrome, Win 10.

**Comment by Alex-302** [comment]
Added to English filter
```
||ipatriot.com/?*=*&_=$script
```
