### ISSUE TITLE
http://www.fullhdfilmadresi.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2527]
**Site**: http://www.fullhdfilmadresi.com/mavi-gece-full-hd-izle.html

**Screenshot**: Remove background picture and ad
![fullhdfilmadresi](https://cloud.githubusercontent.com/assets/19608513/16739369/d1491726-47aa-11e6-9831-ad6d23eed5b0.png)

**Adguard version**: 2.3.8

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
fullhdfilmadresi.com###alt
```
Added to Social filter
```
fullhdfilmadresi.com##.plink
```

**Comment by thislife81** [comment]
![m](https://cloud.githubusercontent.com/assets/19608513/16783453/14f96292-4895-11e6-997e-950db9868c1e.png)

Plz, remove this
