### ISSUE TITLE
http://www.euro-football.ru/ - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2528]
На сайте не работает кнопка авторизации при включенном Adguard c русским фильтром
Ссылка
http://www.euro-football.ru/
Скрины
http://i069.radikal.ru/1607/07/9a0fd95394fd.png
http://s019.radikal.ru/i628/1607/18/ad577e07866a.png

**Comment by Alex-302** [comment]
Исправил
