### ISSUE TITLE
[annoyance] bigbangnews.com - missed app banner

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2529]
**Description**:
There is a bottom banner on an article page (clear cookies before).

Screenshot: 
![macri y el segundo semestre 3a 22las inversiones no llegan autom c3 a1ticamente 22 7c noticia de pol c3 adtica 7c big bang 21 news 2016-07-07 14-48-45](https://cloud.githubusercontent.com/assets/5947035/16652277/0ff1e3ce-4452-11e6-9b1c-1fd79491a7f7.png)

**Comment by Alex-302** [comment]
Can't reproduce. It is hidden by
`bigbangnews.com##.bajar-app-fixed`
