### ISSUE TITLE
investing.com | Mobile | Annoyance | App promotion

### ISSUE THREAD

**Issue by in4u** [AdguardTeam/AdguardFilters#25306]
***Description***

Website: `investing.com`

* **Current behaviour**: 

    Banner at the top of page on mobile, promoting app download.

    <details><summary>Screenshot:</summary>

    ![ss](https://user-images.githubusercontent.com/43062185/48395919-c726d680-e73e-11e8-949b-e9867624c5dd.png)

    </details><br/>

* **Expected behaviour**: 

    No app promotion annoyance. The banner `investing.com###smartbanner` should be hidden.

***System configuration***

Information                            | Value
---                                    | ---
Operating system:                      | Android 7.0
Browser:                               | Firefox for Android 63.0
Filters enabled:                       | Annoyances Filter

**Comment by Alex-302** [comment]
Added
