### ISSUE TITLE
http://m.ndtv.com/request - anti-adbclok

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2530]
Incorrect blocking on page:
http://m.ndtv.com/request and ndtv.com/request

![image](https://cloud.githubusercontent.com/assets/15856304/16653868/bd0cc1b0-445b-11e6-85ea-2936fefe37b0.png)

![image](https://cloud.githubusercontent.com/assets/15856304/16653879/cb6d66a6-445b-11e6-8b88-473c8590412f.png)

**Comment by ameshkov** [comment]
As I understand it blocks access to the homepage. However I cannot reproduce it, maybe indian IP is needed.

**Comment by evgeniy-ADG** [comment]
I've made those screenshots. I can reproduce it.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
it is not just a page, it is a dummy page. I need the source url.

**Comment by evgeniy-ADG** [comment]
Oh, I see. Asked for details, will post updates here.
