### ISSUE TITLE
http://www.rbc.ru/ - yandex direct

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2531]
http://www.rbc.ru/politics/07/07/2016/577e4ccc9a79471b73c814b5?from=main

![image](https://cloud.githubusercontent.com/assets/15856304/16655415/dff1ff40-4462-11e6-86b2-a87abcbc3c0b.png)

Фильтры обновлял перед тестом.

**Comment by Alex-302** [comment]
fixed

**Comment by evgeniy-ADG** [comment]
http://www.rbc.ru/rbcfreenews/579a17759a7947de1b7b9534
![image](https://cloud.githubusercontent.com/assets/15856304/17241401/13b30e28-557a-11e6-9b03-35880370d053.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
rbc.ru##.g-banner-hide-by-exclusive
rbc.ru##div[class^="js-checkad"]

```

**Comment by heru12343** [comment]
Опять не работает

**Comment by Alex-302** [comment]
Не повторяется. Какие браузер, версия Адгарда, фильтры?
