### ISSUE TITLE
m.bournemouthecho.co.uk - share buttons and cookie notice

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2532]
**Description**:
Share buttons on each article page:
http://m.bournemouthecho.co.uk/news/14603987.Woman__18__fighting_for_life_after_car_crash_which_killed_pony_on_A35/

Cookie notice when you first time get there.

**Comment by Alex-302** [comment]
Cookie notification is hidden by `###cookieWarning` But i see an anti-adblock message.
Added to English filter
```
bournemouthecho.co.uk##.ad-blocker-warning
```
Added to Social filter
```
bournemouthecho.co.uk##.custom-sharing
```
