### ISSUE TITLE
ndtv.com - social buttons

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2533]
**Description**:
Page URL:
http://www.ndtv.com/india-news/video-with-cleric-zakir-naik-brings-new-controversy-for-digvijaya-singh-1429006?pfrom=home-lateststories

Share buttons in the start and in the end of an article.

**Comment by Alex-302** [comment]
Added to Social filter
```
ndtv.com##div[class^="st_sharebar"]

```
