### ISSUE TITLE
indiatoday.intoday.in - anti-adblock message

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2534]
**Description**:
Page to check:
http://indiatoday.intoday.in/story/baby-elephant-mourns-death-wake-mother-viral-video/1/709585.html

**Current behaviour**: Tell us what happens

Screenshot:
![orphaned baby elephant mourns mother s death tries to wake her up fyi news - india today 2016-07-07 17-11-27](https://cloud.githubusercontent.com/assets/5947035/16656083/e98a3114-4465-11e6-8f2e-c8d285c0d726.png)

**Comment by Alex-302** [comment]
Added to English filter and reported
```
intoday.in#@#.right-ad
```
Added to Social filter
```
intoday.in##.fixedsocial
```
