### ISSUE TITLE
www.baskino.club - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2535]
Пропускает рекламу на сайте в мобильной версии приложения:
www.baskino.club 
Скрины:
http://s018.radikal.ru/i528/1607/1f/448f9be38721.jpg
http://s008.radikal.ru/i303/1607/43/0c521bad231f.jpg

"enabledFilterIds" : [ 2, 3, 4, 1, 11 ],
  "environment" : "prod",
  "filteringQuality" : "FULL",
  "firewallConfiguration" : {
    "defaultPermissions" : [ "MOBILE", "WIFI", "AD_FILTERING" ],

**Comment by Alex-302** [comment]
fixed
