### ISSUE TITLE
rediff.com | Annoyance | Widgets and bloat

### ISSUE THREAD

**Issue by in4u** [AdguardTeam/AdguardFilters#25359]
Website: `rediff.com`

Filters enabled: Annoyances Filter

The 3 annoyances are detailed as follows. First two are applicable for desktop while the third one is for mobile.

**Issue 1**

URL: `https://mail.rediff.com/cgi-bin/login.cgi`

This is the email login page. After entering credentials, the mailbox loads as `https://f[server number]mail.rediff.com/...`, where server number is user-specific. Notice an annoying news widget with yellow background in the mailbox.

<details><summary>Screenshot of widget:</summary>

![1a](https://user-images.githubusercontent.com/43062185/48487630-cc6e4900-e844-11e8-87de-b0acafd8f8c9.png)
</details><br/>

Relevant page code (with sensitive data removed) is shown in the accompanying screenshot for those who are unable to create a test account.

<details><summary>Screenshot of code:</summary>

![1c](https://user-images.githubusercontent.com/43062185/48487651-d8f2a180-e844-11e8-8c6c-bfc8a398a6f1.PNG)
</details><br/>

The widget is loaded in an iframe. The filter `||recoprofile.rediff.com/news_recommendation/news_template.html$subdocument,domain=rediff.com` successfully removes this widget. The iframe is contained in `rediff.com##.news_ads` so this filter may also be added but it's not really required.

**Issue 2**

URL: `http://login.rediff.com/logout/logout.php`

This can be tested without logging in or needing an account. It's the exit page after logging out but is heavily bloated with annoyances. Everything below the green *"You have successfully signed out of Rediffmail."* message is just unnecessary bloat and ads.

<details><summary>Screenshot of bloat:</summary>

![2a](https://user-images.githubusercontent.com/43062185/48487681-e90a8100-e844-11e8-8fbc-0062c8d68d07.png)
</details><br/>

The filters `login.rediff.com##.panel_rgt` and `login.rediff.com###new_design` take care of them all.

**Issue 3**

URL: `http://login.rediff.com/bn/logout.cgi?formname=general&function_name=logout`

Similar to issue 2 but this is the exit page on mobile. There's a trending products widget here.

<details><summary>Screenshot of widget:</summary>

![3a](https://user-images.githubusercontent.com/43062185/48487708-f889ca00-e844-11e8-838f-79c44a8c0f97.png)
</details><br/>

<details><summary>Screenshot of code:</summary>

![3c](https://user-images.githubusercontent.com/43062185/48487717-03dcf580-e845-11e8-9d16-9ebdd6bdf3fa.PNG)
</details><br/>

The filter `||mshop.rediff.com/trending-now/widget$subdocument,domain=login.rediff.com` gets rid of this widget.

**Comment by Alex-302** [comment]
Fixed 1 and 3

**Comment by Alex-302** [comment]
> I mentioned, requires

added.



> Also, is there any filter list you can recommend which would be relevant for 2nd case?

this?

> Issue 2

I think this is useful element.
