### ISSUE TITLE
mensxp.com - social widgets

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2536]
**Description**:
Page with share buttons:
http://www.mensxp.com/fashion/style-trends/31374-we-dressed-up-like-ranveer-singh-for-a-day-we-have-just-one-question-for-him-ndash-how-do-you-do-it-bro.html

Buttons are above and below the article.

**Comment by Alex-302** [comment]
Added to Social filter
```
mensxp.com##.long-form-social

```
