### ISSUE TITLE
rbc.ru - missed yandex direct

### ISSUE THREAD

**Issue by Hawkrus** [AdguardTeam/AdguardFilters#2538]
При прокрутке [новостей](http://www.rbc.ru/business/08/07/2016/577f55329a7947258b292459) на RBC не режется Яндекс директ:

![rbc](https://cloud.githubusercontent.com/assets/19652388/16680746/84a020b2-44f9-11e6-80b9-43bba99dda17.PNG)

Версия 6.0.226.1108
Windows 7
Chrome

**Comment by vgavrish** [comment]
Проблема наблюдается на разных новостных ссылках. К примеру:
http://www.rbc.ru/politics/08/07/2016/577f7d1c9a794752981ec3e2?from=newsfeed
Фильтры 
<details>
![screenshot_1](https://cloud.githubusercontent.com/assets/18548949/16687733/fd12166c-4522-11e6-84f9-979ddbaeb931.jpg)
</details>
Реклама
<details>
![screenshot_33](https://cloud.githubusercontent.com/assets/18548949/16687702/dfb9cc9a-4522-11e6-9f00-eca71411810c.jpg)

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/2531

не плодите дубли
