### ISSUE TITLE
vk.com - annoyances

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2539]
![image](https://cloud.githubusercontent.com/assets/15856304/16687084/f5b91e3c-451e-11e6-9e8e-bb74d0f633e8.png)

[Новости.zip](https://github.com/AdguardTeam/AdguardFilters/files/354362/default.zip)

Просит потдвердить то почту, то номер. Раздражает люто.

**Comment by Alex-302** [comment]
Что-то не выходит поймать, или я поддался на уговор и подтвердил)

**Comment by evgeniy-ADG** [comment]
Если будет надо, пни в скайп, у меня это вот все лезет каждый час. Я там саму старницу сохранил в зипе, вдруг поможет.

**Comment by Alex-302** [comment]
На проверку
```
vk.com#$#body { overflow: visible!important; } 
vk.com###box_layer_wrap.scroll_fix_wrap
vk.com##div[id="box_layer_bg"][style$="display: block;"]
```
сообщение про безопасность, поэтому не блокируем, хоть и назойливое.

**Comment by evgeniy-ADG** [comment]
окей, надеюсь поможет. если спросят - дам правило в ЮФ. странно, что никто не писал, оно просто выносит мозг ведь :)

**Comment by Alex-302** [comment]
думаю многие вводят запрашиваемую информацию
