### ISSUE TITLE
[ios] rbc.ru - missed ad

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2540]
Пропущена реклама в iOS на сайте:

http://www.rbc.ru/

![image1](https://cloud.githubusercontent.com/assets/16462533/16686010/abaca0ea-4517-11e6-964a-6c668a6c489d.PNG)

У меня так же, проблема повторилась.
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.58 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.60 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.1.42 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.89 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.36.19 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.12 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.79 Enabled=YES

**Comment by Alex-302** [comment]
Не повторяется.

**Comment by dzamyshlyayeva** [comment]
same issue here
![image](https://cloud.githubusercontent.com/assets/23372054/24461835/1abf3fe8-14ab-11e7-8d40-9eaacf4a5f55.png)

Ticket ID 1531884

**Comment by Alex-302** [comment]
У меня не повторяется никак. Попроси текст составленного правила, может по нему сориентироваться можно будет.

**Comment by Michael23456** [comment]
передали, ждем ответа

**Comment by evgeniy-ADG** [comment]
''rbc.ru##div.l-window:nth-child(7) > div.l-content.l-content-indicators-margin:first-child > div.l-content-body > div.l-row:nth-child(6) > div.main.g-news-block > div.l-row > div.main-feed:last-child > div.g-banner__main:first-child > div.g-tabletVisible:last-child > div:last-child > div:first-child''

**Comment by Alex-302** [comment]
Баннер должен быть скрыт правилом `rbc.ru##div[class^="js-checkad"]`
