### ISSUE TITLE
livelib.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2541]
**Description**: https://www.livelib.ru/reader/brunhilda

Screenshot:
<details>
![livelib](https://cloud.githubusercontent.com/assets/14153331/16705011/8e3206a2-4587-11e6-8d90-d2432258ecd0.png)
</details>

Filters:
<details>
![filters](https://cloud.githubusercontent.com/assets/14153331/16705037/da0b6e9c-4587-11e6-8a49-f3f051fcfbcd.png)
</details>

**Comment by Alex-302** [comment]
fixed. See the commit
