### ISSUE TITLE
tweakers.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2542]
**Description**: page content won't show up. @evgeniy-ADG wasn't able to reproduce with the filter set.

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/16705125/84c3248c-4589-11e6-96cf-dd703bd27f84.png)
</details>

**Adguard version**: 1.0.8.54

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.52 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.59 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.74 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.8.83 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.79 Enabled=YES
ID=106 Name="EasyList Dutch" Version=1.0.61.41 Enabled=YES

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't reproduce too.

Cookie notification is blocked.

**Comment by worldsdream** [comment]
https://forum.adguard.com/index.php?threads/tweakers-net.11775/

I can't open this page too, my filters are english, dutch, annoyance, safari, mobile ads. 

The cookie is blocking us of seeing this website

Adding those rules by Blaz

tweakers.net#@##cookieContainer
tweakers.net#@##cookieOverlay

I could see the cookie notice and accept it, so we can enter the website.

**Comment by Alex-302** [comment]
Added
```
tweakers.net#@##cookieContainer
tweakers.net#@##cookieOverlay
```
