### ISSUE TITLE
www.automotorundsport.de missed ads and blocks adblocker

### ISSUE THREAD

**Issue by tiberian83** [AdguardTeam/AdguardFilters#2543]
www.automotorundsport.de has some missed ads and it blocks now users with adblockers.

http://www.auto-motor-und-sport.de/news/neuzulassungen-sportwagen-erstes-halbjahr-2016-1324545.html?block=1

![img_0776](https://cloud.githubusercontent.com/assets/10312300/16707719/cfc7eb3a-45d8-11e6-9058-cd1b21829b50.PNG)

**Comment by Alex-302** [comment]
Please check for updates. I don't see adblock detection now. But on ios we can't block these ads at the moment.

**Comment by tiberian83** [comment]
Yes, updates seem to have solved it by now. Thanks. :)
