### ISSUE TITLE
penzainform.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2544]
**Description**: Реклама
http://www.penzainform.ru/news/global/2016/07/09/ldpr_predlozhila_uvazhit_zyuganova_i_pchelovodov_200-rublevoj_kupyuroj.html

Screenshot: 
<details>
![926e1d6073c345e586ded05fbc6dda38](https://cloud.githubusercontent.com/assets/18548949/16712121/062fc8a8-4685-11e6-9d4f-0b72d92f405a.png)
</details>
**Filters list**: http://prntscr.com/br0ydv

**Browser**: Chrome

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed

**Comment by Alex-302** [comment]
Fixed
4abd3a2
