### ISSUE TITLE
http://www.pdnonline.com/index.shtml - can't log in

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2545]
1. Go to http://www.pdnonline.com/index.shtml
2. Click "Login"
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16712599/c82aa45a-4694-11e6-8460-2bdadedf5895.png)
</details>
3. It redirects to a blocked page: https://emerald.omeda.com/npdn/custsrv_login.do
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16712603/e480a1cc-4694-11e6-884f-e45e42882efb.png)

</details>

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||emerald.omeda.com/npdn/custsrv_login.do
```
Please check it
