### ISSUE TITLE
http://www.chicagotribune.com/ and www.orlandosentinel.com - false blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2546]
http://www.chicagotribune.com/news/local/breaking/ct-chicago-police-protests-0710-20160709-story.html
http://www.orlandosentinel.com/news/ct-dallas-police-attack-20160709-story.html
We're blocking comments in every post:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16712622/b5d06ce4-4695-11e6-88c3-9688d0b57035.png)
![image](https://cloud.githubusercontent.com/assets/15856304/16712624/bce4acac-4695-11e6-8cb3-c822aace5476.png)
</details>

Basic filters set, I managed to reproduce it
1336158

**Comment by Alex-302** [comment]
Fixed.
