### ISSUE TITLE
filmix.net

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2547]
**Description**:
Реклама на главной странице http://filmix.net/
Screenshot:
<details>
![screenshot_11](https://cloud.githubusercontent.com/assets/18548949/16712721/5f85b1a2-4698-11e6-9ed5-0948ea9c5504.jpg)
![screenshot_8](https://cloud.githubusercontent.com/assets/18548949/16712724/6dda73fa-4698-11e6-98ba-28d9ce8d7e94.jpg)
</details>

**Browser**: Chrome

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
