### ISSUE TITLE
http://www.aranzulla.it - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2550]
http://www.aranzulla.it/locked-chrome.php?p=940952&fabm=file&rnd=0.35556028728202604

![image](https://cloud.githubusercontent.com/assets/15856304/16713589/ab19b696-46b5-11e6-92a1-3860f624f3af.png)

http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:10 Name: Filter for useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:101 Name: EasyList Url: https://easylist-downloads.adblockplus.org/easylist.txt
FilterId:109 Name: EasyList Italy Url: https://easylist-downloads.adblockplus.org/easylistitaly.txt
FilterId:113 Name: Liste FR Url: https://easylist-downloads.adblockplus.org/liste_fr.txt
FilterId:207 Name: Adblock Warning Removal List Url: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt

**Comment by Alex-302** [comment]
Fixed.

**Comment by evgeniy-ADG** [comment]
It's back and starts with EasyList Italy.

<details>

**Comment by Alex-302** [comment]
Done.
