### ISSUE TITLE
www.notebookcheck.com - the ad has been missed

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2551]
**Description**: missed ads [here](http://www.notebookcheck.com/Samsung-Galaxy-Note-7-Die-offiziellen-Bilder-sind-da.168453.0.html)

**Current behaviour**: 

> Scroll down, see *** Vodafone ads!! On desktop no issue. Manually add? Not fixed, if reloading the site, then comes this *** ad again!! This is issue.

Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16713687/4285bf14-46b8-11e6-817c-a7f994af60d4.png)

</details>

**Steps to reproduce the problem**:

1. Adguard in content settings is on
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16713698/8a8b8b36-46b8-11e6-90ef-1894ee79d7d2.png)
</details>

2. Disable Adguard in content settings
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16713700/93deda62-46b8-11e6-929c-431a2c56586d.png)
</details>

3. Activate Adguard in content settings
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16713701/9a67c95c-46b8-11e6-8548-1e7814878b40.png)
</details>
4. Go to Safari iOS settings, using clear cache,history
5. Open Safari iOS, go to
http://www.notebookcheck.com/Samsung-Galaxy-Note-7-Die-offiziellen-Bilder-sind-da.168453.0.html
6. You can see the ad (reproducibly 100%)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16713706/a7d7fd50-46b8-11e6-9f18-fd59df01231f.png)
</details>

**Adguard version**: the latest

**Filters list**:
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.39 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.54 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.10.63 Enabled=NO
ID=6 Name="German filter" Version=1.0.26.16 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.78 Enabled=YES

**Operating system**: ios

**Browser**: safari

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
I can't reproduce this on iPad, tried ~5 times, no joy.

**Comment by evgeniy-ADG** [comment]
> Please help me! This is big bug in your app, if disable and activate adguard in iOS settings. Then has adguard iOS no longer function, not working, no effect etc. I using other content-blocker no issue.

I confirm that, could someone please tell us is it ok, if no, what to do with it?

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardForiOS/issues/116

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Инвалид - метка для гостей:) Если будут плохо оформлять, то будут получать чёрную метку)

**Comment by evgeniy-ADG** [comment]
У меня таких уже три. Соберу много и поменяю на приз.
