### ISSUE TITLE
www.macdigger.ru - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2553]
The [link](http://www.macdigger.ru/iphone-ipod/apple-vypustila-pervuyu-obshhedostupnuyu-beta-versiyu-ios-10.html)

![20160710_133319000_ios](https://cloud.githubusercontent.com/assets/15856304/16713850/380b07ca-46bc-11e6-9c31-b679cdf9fe13.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.55 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.59 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.75 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.36.19 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.79 Enabled=YES
ID=101 Name="EasyList" Version=1.0.60.31 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.61.34 Enabled=YES

**Comment by Alex-302** [comment]
В сафари чисто. Пусть без КГ Adlist проверит.
@vozersky проверь плиз на айпаде.

**Comment by evgeniy-ADG** [comment]
Уже чисто и с ним, и без него. Скрин мой, в момент регистриации тикета, проблема была. Там  сбоку есть белый пустой квадрат, видимо, остаок от рекламы:
<details>
![20160712_165223000_ios](https://cloud.githubusercontent.com/assets/15856304/16775641/40a808ce-486a-11e6-8fb1-808c042117b5.png)
