### ISSUE TITLE
www.itechpost.com - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2554]
The [link](http://www.itechpost.com/articles/21240/20160627/fallout-4-fallout-4-update-nuka-world-fallout-4-nuka-world-last-fallout-4-dlc-bethesda-release-more-2017.htm)

<details>
![20160710_133648000_ios](https://cloud.githubusercontent.com/assets/15856304/16713862/a8713052-46bc-11e6-9e4b-99efc3ede03f.png)
![image](https://cloud.githubusercontent.com/assets/15856304/16713866/b3a94e96-46bc-11e6-9ad6-0ce6ad18c73e.png)

</details>

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.83.95 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.66 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.72 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.48 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID=101 Name="EasyList" Version=1.0.57.70 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.57.60 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.57.82 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.57.70 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.1.64 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.57.75 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.57.62 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.34 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.61 Enabled=YES
ID=220 Name="CJXsAnnoyanceList" Version=1.0.0.36 Enabled=YES

**Comment by Alex-302** [comment]
Added to English filter
```
||zorwrite.com/*/Tag.a1b$domain=itechpost.com
```
