### ISSUE TITLE
valueresearchonline.com | Annoyance | Sticky promo footer

### ISSUE THREAD

**Issue by in4u** [AdguardTeam/AdguardFilters#25551]
***Description***

Website: `valueresearchonline.com`

* **Current behaviour**: 

    Stick promo footer at the bottom of every page.

* **Expected behaviour**: 

    The sticky promo footer `valueresearchonline.com###fixed_footer` should be hidden.

***System configuration***

Information                            | Value
---                                    | ---
Operating system:                      | Windows 7
Browser:                               | Firefox 63.0.3
Filters enabled:                       | Annoyances Filter

**Comment by Alex-302** [comment]
added
