### ISSUE TITLE
http://m.thepiratebay.org/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2556]
**Current behaviour**: The search results page opens blank

Screenshot: 
<details>
![20160710_141416000_ios](https://cloud.githubusercontent.com/assets/15856304/16714104/175a663c-46c2-11e6-95df-ff512e2788ae.png)

</details>

**Expected behaviour**: Disable English filter, and it loads fine then
<details>
![20160710_141542000_ios](https://cloud.githubusercontent.com/assets/15856304/16714106/21fc632e-46c2-11e6-9958-2b2385c2384f.png)
</details>

**Adguard version**: the latest

**Filters list**:  English, dutch, spyware, mobile and safari. 

**Operating system**: ios

**Browser**: safari

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||m.thepiratebay.org/search.php?
```

**Comment by Alex-302** [comment]
@evgeniy-ADG проверь, или попроси ющера

**Comment by worldsdream** [comment]
I did report this issue, it's working great now. Thanks @evgeniy-ADG  @Alex-302 !!

**Comment by worldsdream** [comment]
Go to the piratebay website on your iOS:

www.piratebay.org
search for example: batman
you get search results
select a search result, the one in the top for example

Now you see in the top a white empty space

You can't reproduce it in Safari desktop user agent, only iOS

This rule killed it, I tested it:

thepiratebay.org##div#adrestop.sixteen.columns

or you can add:

thepiratebay.org##div#adrestop

but they change always from .se .org and so on, so it would be better to make it thepiratebay.*

correct?

**Comment by Alex-302** [comment]
This emty space is invisible on my end, because the inserted iframe is hidden by
`##iframe[width="728"][height="90"]`

**Comment by worldsdream** [comment]
Now it's hidden

**Comment by worldsdream** [comment]
My bad, it was hidden because I had a rule in userfilter. Removing the rule. Still empty space in top. Only in iOS.

**Comment by worldsdream** [comment]
Screenshot:

http://i.imgur.com/XJuUa2q.jpg

**Comment by Alex-302** [comment]
Added it to Safari filter. Check for updates after 30 minutes.

**Comment by worldsdream** [comment]
That didn't help, still white in the top.

**Comment by Alex-302** [comment]
Removed. Use it in user filter.

**Comment by worldsdream** [comment]
May I ask why you dont add this rule:

thepiratebay.org##div#adrestop

That works perfect. Is it a bad filte rule?

**Comment by worldsdream** [comment]
screenshot: http://i.imgur.com/e4fbPph.png
