### ISSUE TITLE
www.wplocker.com - anti-adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2557]
The [link](http://www.wplocker.com/templates/themeforest/8981-kwoon-multipurpose-wordpress-theme.html)
![20160710_142009000_ios](https://cloud.githubusercontent.com/assets/15856304/16714123/abb57182-46c2-11e6-91eb-fb77addd5b66.png)

Basic filter set + experimental and annoyances

**Comment by Alex-302** [comment]
Added to English filter
```
@@||wplocker.com/advertisement.js
```
