### ISSUE TITLE
football.ua

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2560]
Screenshot: http://football.ua/
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/16714888/52b40186-46d9-11e6-9555-74ab7fd9711d.png)
</details>

Screenshot: http://football.ua/germany/308475-zammer-pokinul-bavariju.html
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/16714903/8c1a9854-46d9-11e6-88b2-0fbc2810d7f5.png)
![image](https://cloud.githubusercontent.com/assets/14153331/16714904/9bb6ad0c-46d9-11e6-9edb-f66e900c30fb.png)
</details>

**Filters list**:
![image](https://cloud.githubusercontent.com/assets/14153331/16714911/d3bfabb8-46d9-11e6-8db7-b7d4b50dbb15.png)

**Comment by Alex-302** [comment]
[COLOR="#0000FF"]Добавил в русский фильтр:[/COLOR]
[CODE]
football.ua##.banner
football.ua##div[class="banner"] + div[class="separator"]
[/CODE]
Пожалуйста, проверьте результат.
