### ISSUE TITLE
m.bournemouthecho.co.uk - anti-adblock message

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2561]
**Description**:
Anti-adblock message at the bottom of the page in Safari.

Screenshot:
<details>
![van driver escapes unscathed as bridge thugs drop object through his windscreen from bournemouth echo 2016-07-10 20-23-28](https://cloud.githubusercontent.com/assets/5947035/16714989/56f00cf6-46dc-11e6-9ff9-aa90e5902255.png)

</details>

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
bournemouthecho.co.uk##.ad-blocker-warning
```
Cookie notification is hidden by
`###cookieWarning`

**Comment by ameshkov** [comment]
It is here again.

**Comment by ameshkov** [comment]
Updated rule:
`bournemouthecho.co.uk###adBlockBanner`

**Comment by ameshkov** [comment]
It is there again

**Comment by ameshkov** [comment]
@Alex-302 I've updated the filter:
https://github.com/AdguardTeam/AdguardFilters/commit/00f1e1d4fe7089758ac1b1f908b85bb04ff90671

However, it will help with iOS only, we should find another way for other AG versions.

**Comment by Alex-302** [comment]
Added to English filter
```
@@||budgetedbauer.com^$domain=bournemouthecho.co.uk
@@||ad.doubleclick.net/ddm/ad/*$domain=bournemouthecho.co.uk
```
