### ISSUE TITLE
Add EasyList Spanish subscription to the list of available

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2562]
https://adblockplus.org/subscriptions

**Comment by Alex-302** [comment]
Done. 
@mmigi , please make changes in config.

**Comment by mmigi** [comment]
Filter is added and is allowed by the name 'FanboyEspanol'.

**Comment by ameshkov** [comment]
@mmigi Fanboy? It has different name:
https://hg.adblockplus.org/easylistspanish/file/c7a72cafda37/easylistspanish.txt

**Comment by Alex-302** [comment]
It is another filter.
