### ISSUE TITLE
dreamfilm ads again

### ISSUE THREAD

**Issue by cabban** [AdguardTeam/AdguardFilters#2564]
**Description**:

**Current behaviour**: Tell us what happens

Screenshot: use the following code
<details>
![z](http://somehosting.com/adg_on.jpg)
</details>

**Expected behaviour**: Tell us what should happen instead

Screenshot:
<details>
![z](http://somehosting.com/adg_off.jpg)
</details>

**Steps to reproduce the problem**:

* 
*  
*  

**Adguard version**:

**Filters list**:

**Operating system**:

**Browser**:
chrome
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

missing ad blocking, www.dreamfilmhd.bz
![image](https://cloud.githubusercontent.com/assets/19514493/16716142/624f8e2e-46f4-11e6-8cb0-ea57ce0e8bae.png)

SE NU BLUE BANNER + the big one at the top

**Comment by Alex-302** [comment]
Please add filters list and working screenshots.

**Comment by cabban** [comment]
dont quite know how to add filter list?;/( kind regards

2016-07-12 17:12 GMT+02:00 Alex <notifications@github.com>:

**Comment by Alex-302** [comment]
You can just type them, or post screenshot.

**Comment by Alex-302** [comment]
Check these rules for blue buttons and big empty rectangle
```
dreamfilmhd.bz##a[href="http://www.byggboss.se/"]
dreamfilmhd.bz##.longbanner
```

**Comment by cabban** [comment]
but i mean how to ´type a add ? in text :)?

2016-07-12 17:14 GMT+02:00 Alex <notifications@github.com>:

**Comment by cabban** [comment]
where to find rules, and i cant not filter ads manually in chrome :/ dont
know why

2016-07-12 17:15 GMT+02:00 Alex <notifications@github.com>:

**Comment by Alex-302** [comment]
I don't understand you:)
Add these rules to user filter
```
dreamfilmhd.bz##a[href="http://www.byggboss.se/"]
dreamfilmhd.bz##.longbanner
```

**Comment by cabban** [comment]
i cant any more remove banners manually either

**Comment by Alex-302** [comment]
why? Assistant is not displayed?
The rules added to English filter

**Comment by cabban** [comment]
now i dont understand you atm, what do u mean?
i could Before hide ads on my own not now it is any issue ?

2016-07-12 17:32 GMT+02:00 Alex <notifications@github.com>:

**Comment by Alex-302** [comment]
Please describe your steps for blocking.

**Comment by cabban** [comment]
I have some reading difficulties can't understand how to add filters
, so when u add users filter then they come for all users in a filter 
update? :-)


Skickat med AquaMail för Android
http://www.aqua-mail.com


På 12 juli 2016 8:06:54 PM Alex <notifications@github.com> skrev:

**Comment by Alex-302** [comment]
I've added these rules to English filter. Check for updates.
