### ISSUE TITLE
http://epidemz.com/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2565]
**Description**: Не отображается значок Помощника на сайте:
http://epidemz.com/

Screenshot: 
<details>
![screenshot_14](https://cloud.githubusercontent.com/assets/18548949/16721757/643f16fe-474a-11e6-8c19-fd68e375a115.jpg)
</details>
**Adguard version**: 6.1

**Filters list**: http://prntscr.com/brdrhk

**Browser**: Chrome

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не инжектимся в страницу. Баг открыт
https://github.com/AdguardTeam/AdguardForWindows/issues/1126
