### ISSUE TITLE
proporn.com [NSFW] [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#25668]
**Site**: https://www.proporn.com/video/490094/indian-desi-girl-mindblowing-blowjob-than-has-sex

**Issue**: Pop-up seen when tapping on play button.

**Screenshot**: N/A

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 70.0.3538.102 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.13 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Spam 404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
Please look into this

**Comment by Alex-302** [comment]
Not reproduced.
