### ISSUE TITLE
familyguy.fox-fan.ru

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#2567]
www.familyguy.fox-fan.ru
при нажатии на любой объект - popup с рекламой mackeeper

повторил в хроме на мак, со стандартными фильтрами+раздражители, десктопный Adguard.
также повторяется в Safari и FF

**Comment by Alex-302** [comment]
Не повторилось.
Проверь ещё)

**Comment by vozersky** [comment]
сегодня не повторяется
