### ISSUE TITLE
Add missing

### ISSUE THREAD

**Issue by prashantoshi123** [AdguardTeam/AdguardFilters#25682]
Why are you not taking any action? This is showing ads.
https://www.google.co.in/amp/s/www.ndtv.com/jobs/uptet-answer-key-2018-heres-how-to-download-from-upbasiceduboard-gov-in-1950474%3famp=1&akamai-rum=off

**Comment by Alex-302** [comment]
I don't see ads.

**Comment by prashantoshi123** [comment]
Hot to unauthorized it

**Comment by Alex-302** [comment]
Please send report using AdGuard.
Do you use AdGuard? You did not provide any info.
