### ISSUE TITLE
timesofindia.indiatimes.com - anti-adblock script

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2568]
http://timesofindia.indiatimes.com/city/chandigarh/Swaraj-turns-saviour-for-foreign-bahu/articleshow/53145607.cms?intenttarget=no&utm_source=newsletter&utm_medium=referral&utm_campaign=Top_Headlines

http://s010.radikal.ru/i311/1607/8b/268bfe3adea7.png

**Comment by vozersky** [comment]
@evgeniy-ADG  не понял, а почему invalid и closed? 
там до сих пор скрипт в каждой статье

**Comment by Alex-302** [comment]
@vozersky ты ж на дату смотри:) За 20 дней уже несколько раз исправляли.

**Comment by Alex-302** [comment]
Добавил
```
@@||clmbtech.com^$domain=timesofindia.indiatimes.com
@@||partner.googleadservices.com/gpt/pubads_impl_$domain=timesofindia.indiatimes.com
@@||google-analytics.com^$domain=timesofindia.indiatimes.com
@@||b.scorecardresearch.com/beacon.js$domain=timesofindia.indiatimes.com
@@||static.chartbeat.com/js/chartbeat.js$domain=timesofindia.indiatimes.com
@@||ad.crwdcntrl.net^$domain=timesofindia.indiatimes.com
timesofindia.indiatimes.com##.toiwidgets_social
```

**Comment by Alex-302** [comment]
Добавил в англ фильтр
```
timesofindia.indiatimes.com#%#AG_onLoad(function() { window._0x89ff = []; });
```

**Comment by vozersky** [comment]
а  invalid-то почему? (:

**Comment by Alex-302** [comment]
Я ж удалил её. Правило заменил более надёжным.

**Comment by evgeniy-ADG** [comment]
Инвалид потому что дубль был, до меня сделали таск, если не ошибаюсь и если это важно. Добавьте лейбл Duplicate. Если можно.

**Comment by Alex-302** [comment]
Duplicate лучше не надо, чтоб разнотипные проблемы одного сайта не смешались в одной задаче.
