### ISSUE TITLE
Outlook ad blocker banner

### ISSUE THREAD

**Issue by shaurmanchic** [AdguardTeam/AdguardFilters#2570]
**Description**: https://outlook.live.com
If Adguard Browser extension is enabled, a banner in the right part of the main window appears, saying "It looks like you're using an ad blocker. To maximise the space in your inbox, sing up for Ad-free Outlook."
<details>
![](https://s31.postimg.org/50x8kn8l7/Outlook.png)
</details>

Russian filter  1.0.36.23   2016-07-10  
English filter  1.0.88.84   2016-07-11  
Spyware filter  1.0.6.61    2016-07-08  
Social media filter 1.0.10.79   2016-07-10  
Experimental filter 1.0.26.12   2016-06-30

**Operating system**: Windows

**Browser**: Chrome

**Comment by Alex-302** [comment]
I can't reproduce it
http://imagizer.imageshack.com/img923/8039/sF7qiS.png
Need remote access to mail.

**Comment by worldsdream** [comment]
I can reproduce this on my end

screenshot: http://i.imgur.com/7uTEIns.png

microsoft owa adsbar

**Comment by Alex-302** [comment]
check them
```
outlook.live.com#$##primaryContainer > div[style="overflow: hidden; position: absolute; top: 50px; right: 165px; bottom: 0px; left: 0px; height: auto; width: auto;"] { width: 100%!important; }
outlook.live.com#$#div[class="_n_h"][style$="height: auto; width: 165px;"] { display: none!important; }
```

**Comment by worldsdream** [comment]
worked great, you can add it to the filterlist

**Comment by Alex-302** [comment]
Added. Check for updates.

**Comment by vmalyuta** [comment]
![screen shot 2017-04-09 at 22 14 49](https://cloud.githubusercontent.com/assets/23701680/24840294/52920416-1d73-11e7-81b9-5319c3ca5de6.png)
id 1108206

**Comment by Alex-302** [comment]
Can't reproduce. 
@seanl-adg check it, please, on your side.

**Comment by seanl-adg** [comment]
I couldn't reproduce neither.

**Comment by Alex-302** [comment]
@vmalyuta please ask about this issue again.

**Comment by vmalyuta** [comment]
done

**Comment by altokarev** [comment]
Reproduced. Column visible only in fullscreen mode (or with a window width of about 1920px).

<details><summary>Screenshot:</summary>

![screen shot 2017-06-02 at 15 49 33](https://cloud.githubusercontent.com/assets/28726429/26726339/3db230fe-47ab-11e7-870e-7364a14c5e13.png)

</details>

<br>
***System configuration***

Information | value
--- | ---
Operating system: | MacOS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 12, 14

**Comment by Alex-302** [comment]
Fixed

**Comment by gotitbro** [comment]
@Alex-302 The filters work.

@ameshkov Why are antiadblock filters bundled in the "Annoyances filter"? I just recently noticed this. 
Antiadblock filters are also present in the "English filter" and other language filters presumably which block access to the content rather than just annoy.

Can the antiadblock filter also be listed separately so that I don't have to subscribe to the Annoyances filter to hide anti adb warnings? Please consider this request.

Thank You

**Comment by Alex-302** [comment]
@gotitbro it is just notification. It doesn't breaks the site.

**Comment by ameshkov** [comment]
@gotitbro 
> Can the antiadblock filter also be listed separately so that I don't have to subscribe to the Annoyances filter to hide anti adb warnings? Please consider this request.

English filter handles anti-adblock scripts which prevent you from using websites.
Annoyances filter removes "light" anti-adblock messages as well.

Actually, we'd like to make filters more "granular", the prerequisite for it is this issue:
https://github.com/AdguardTeam/AdguardFilters/issues/3937
