### ISSUE TITLE
Convert :style pseudo class into AG syntax

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2571]
**Description**:

Gorhill has recently added CSS injections rules support to ublock:
https://github.com/gorhill/uBlock/releases/tag/1.7.7b14

The problem with the syntax he uses is that these rules may break the stylesheets (as these are not real pseudo-elements).

So, we have two issues here:
1. Add support for this syntax to the server side rules converter
2. Add support for this syntax to AG products (also we should add or ignore other pseudo-elements)

**Comment by ameshkov** [comment]
Ignore rules by the following masks (regular expressions):
`.*##.*?:has\(.*`
`.*##.*?:xpath\(.*`

CSS injection conversion rule:
`example.com##h1:style(background-color: blue !important)`
into
`example.com#$#h1 { background-color: blue !important }`

**Comment by ameshkov** [comment]
I suggest you read this review before implementing it:
http://upsource.adguard.com/adguard-java-code/review/AJC-CR-8

**Comment by F4z** [comment]
Hi,
what about rules which look like this:
`example.com##[role="main"]:style(display: none;)`
`example.com##[class="class"]:style(display: none;) `
`github.com##[class]:style(display: none;)`
I see that, these type of rules do not work in Adguard, and I think it should be also converted, shouldn't it?

**Comment by ameshkov** [comment]
@F4z you're right, thank you!

Filed a bug report:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/342
