### ISSUE TITLE
megatrack.info

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2572]
**Description**: На главной http://megatrack.info/ реклама

Screenshot:
<details>
![screenshot_16](https://cloud.githubusercontent.com/assets/18548949/16762222/44123dd8-482c-11e6-8703-93b33d6e3eb9.jpg)
![screenshot_17](https://cloud.githubusercontent.com/assets/18548949/16762223/44132bd0-482c-11e6-9493-e915ee880e93.jpg)
</details>

**Filters list**: http://prntscr.com/brvdf4

**Browser**: Chrome

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
feeeed8
