### ISSUE TITLE
[Android] Lazada app

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#2573]
**Description**: App will not respond with Adguard enabled

**Current behaviour**: in the main screen the app continuosly asks you to 'tap to connect' when Adguard is enabled

**Expected behaviour**: App works normally

**Steps to reproduce the problem**:

* Install Lazada app (https://play.google.com/store/apps/details?id=com.lazada.android)
*  Enable Adguard
*  Launch the app. It asks you to 'tap to connect'

**Adguard version**:

**Filters list**:

**Operating system**: Android

**Browser**:

https://forum.adguard.com/index.php?threads/android-adguard-blocking-lazada-app.11833/

**Comment by Alex-302** [comment]
Fixed

**Comment by Alex-302** [comment]
@vbagirov 
there are HTTPS issues
These domains must be excluded:
```
mobapi.lazada.co.id
mobapi.lazada.sg
```
maybe this list is not full.
