### ISSUE TITLE
http://www.opensubtitles.org - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2574]
![20160712_150357000_ios](https://cloud.githubusercontent.com/assets/15856304/16771997/2015d73a-485b-11e6-94f7-5179e3ed4dac.png)

> After that, try:
> opensubtitles.org##DIV.content:first-child > FIELDSET.intro:nth-child(19)
> And
> opensubtitles.org##.content > DIV:first-child
> Refresh your page. Ads are gone correct?
> Please confirm and add to the filterlist.
>

**Comment by Alex-302** [comment]
These rules are dangerous. I will check it later.

**Comment by Alex-302** [comment]
@evgeniy-ADG @vozersky 
please check these rules on iOS device
```
@@||static.opensubtitles.org/libs/js/ad_
@@||ads2.opensubtitles.org^
opensubtitles.org###scrubbuad
@@||pagead2.googlesyndication.com/pagead/show_ads.js$domain=opensubtitles.org
```

**Comment by evgeniy-ADG** [comment]
![20160712_200851000_ios](https://cloud.githubusercontent.com/assets/15856304/16781816/afcf77d0-4885-11e6-9f48-366699163976.png)
![20160712_200834000_ios](https://cloud.githubusercontent.com/assets/15856304/16781817/afd18584-4885-11e6-81fc-90b44f86a8a4.png)

**Comment by worldsdream** [comment]
With those rules, on homepage the ads are gone. Thats a good thing. Now only when we search for a serie or movie, the ads are still here.

With adguard block element:

www.opensubtitles.org###search_results > TBODY > TR:nth-child(20)

**Comment by Alex-302** [comment]
@worldsdream screenshot, please.

**Comment by worldsdream** [comment]
they are the same as the one above from @evgeniy-ADG vgeniy-ADG

**Comment by Alex-302** [comment]
@worldsdream 
can you reproduce it in Safari?

**Comment by worldsdream** [comment]
On iOS, yes. Have not tried safari desktop user agent. Want me to try that out?

**Comment by Alex-302** [comment]
check these rules instead previous
```
@@||static.opensubtitles.org/libs/js/ad_
opensubtitles.org###scrubbuad
@@||pagead2.googlesyndication.com/pagead/show_ads.js$domain=opensubtitles.org
opensubtitles.org##div[id$="-placeholder"]
@@||ads2.opensubtitles.org/*www/delivery/afr.php?
```

**Comment by worldsdream** [comment]
I just tried, the same advert. When i long press on it, it's from ads2.opensubtitles.org

**Comment by Alex-302** [comment]
I  reproduced that banner in Safari, and these rules helps.

**Comment by worldsdream** [comment]
@evgeniy-ADG can you add those rules and search for a movie/serie and hit enter

**Comment by Alex-302** [comment]
```
opensubtitles.org###search_results > tbody > tr[style^="height: 115px;"]
```
check it

**Comment by worldsdream** [comment]
I added it, still the same advert at search

**Comment by Alex-302** [comment]
try
```
opensubtitles.org##tr[style^="height: 115px;"]
```

**Comment by Alex-302** [comment]
Are you using full or simplified filters?

**Comment by worldsdream** [comment]
That rule messes up the homepage and does not get rid of the ads in search 

I am using full

**Comment by Alex-302** [comment]
I need access to your browser with
http://i.imgur.com/XhwP8FS.png

**Comment by worldsdream** [comment]
Sure. When?

**Comment by Alex-302** [comment]
Now

**Comment by worldsdream** [comment]
Pmed you on forum

**Comment by Alex-302** [comment]
Added to Safari filter
```
opensubtitles.org###search_results > tbody > tr[style^="height:115px;text-align:center;margin:0px;padding:0px;"]
```

**Comment by worldsdream** [comment]
You only forgot to add:

opensubtitles.org###scrubbuad

Please add it, because on iOS, we do get that green window in left bottom area. That rule fixed it, I just checked it again.

**Comment by Alex-302** [comment]
Ok

**Comment by evgeniy-ADG** [comment]
On Win there's no Assistant icon on the site, but ads seem to be blocked. Is it ok?

**Comment by Alex-302** [comment]
Yes. In this case.
