### ISSUE TITLE
http://de.xhamster.com - ad leftover

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2576]
http://de.xhamster.com/photos/gallery/5094158/annica_hansen_all_nudes.html

NSFW. Huge empty blocks on the left and over the footer
<details>
![20160712_153059000_ios](https://cloud.githubusercontent.com/assets/15856304/16773022/06f96222-485f-11e6-8dee-adba425493a6.png)
![20160712_153054000_ios](https://cloud.githubusercontent.com/assets/15856304/16773023/0717a174-485f-11e6-8ffe-8385090dbd91.png)
</details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.85 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.61 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.79 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.1.44 Enabled=YES
ID=6 Name="German filter" Version=1.0.26.22 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.25 Enabled=NO
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=NO
ID=210 Name="Spam404" Version=1.0.1.31 Enabled=NO

**Comment by Alex-302** [comment]
I can remove only the second.
Added to Annoyances filter
```
xhamster.com###swectrqw
```
