### ISSUE TITLE
http://dreamfilmhd.bz - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2577]
http://dreamfilmhd.bz/series/details/360-game-of-thrones/

<details>
![20160712_154425000_ios](https://cloud.githubusercontent.com/assets/15856304/16773510/ee1453b4-4860-11e6-8bf5-e3a5c40c356c.png)
</details>

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.87 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.62 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.79 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.80 Enabled=YES

+ deutch + german + spanish + mobile + annoyances

**Comment by Alex-302** [comment]
Can't reproduce with Safari.
@vozersky please check it on iPad

**Comment by evgeniy-ADG** [comment]
мой скрин с айпада
