### ISSUE TITLE
http://nnmclub.to/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2578]
http://nnmclub.to/

<details>
![20160712_160232000_ios](https://cloud.githubusercontent.com/assets/15856304/16774173/94e05b6e-4863-11e6-9fb9-1af03ae6d55a.png)
</details>

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.68 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.61 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.75 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.36.20 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.16 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.80 Enabled=YES

**Comment by Alex-302** [comment]
I can't confirm it with Safari.
@vozersky please check it on iPad

**Comment by evgeniy-ADG** [comment]
мой скрин с апйпада

**Comment by vozersky** [comment]
рекламы не вижу, только сообщение сверху (harmless)

![img_0045](https://cloud.githubusercontent.com/assets/17472907/16796273/7dac9192-48ea-11e6-9c12-19641e9b5eea.PNG)

**Comment by Alex-302** [comment]
Это в раздражителях убрано.

**Comment by evgeniy-ADG** [comment]
только что проверил обновления:
![image](https://cloud.githubusercontent.com/assets/15856304/16949172/382d1c44-4d87-11e6-96df-d0fa406f4ec5.png)

**Comment by Alex-302** [comment]
У меня абсолютно чисто.

**Comment by evgeniy-ADG** [comment]
Сейчас и у меня все ок
