### ISSUE TITLE
http://www.neobuggy.net/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2579]
http://www.neobuggy.net/

The site is full of them
<details>
![20160712_161011000_ios](https://cloud.githubusercontent.com/assets/15856304/16774381/620cfbe2-4864-11e6-87b5-1dd91c1e7ed5.png)
![20160712_160959000_ios](https://cloud.githubusercontent.com/assets/15856304/16774382/62164d00-4864-11e6-9d90-722a6d045dbf.png)

</details>

Basic filters set

**Comment by Alex-302** [comment]
Added to English filter
```
neobuggy.net##a[onclick^="_gaq.push(['_trackEvent','AdLinks'"]
neobuggy.net##a[href^="http://www.spektrumrc.com/Surface/Servos.aspx?utm_source="]
neobuggy.net##a[href="http://www.agama-rc.com/"]


```
