### ISSUE TITLE
Stealth mode blocks logging on msn.com with Mocrosoft ID

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2580]
I have an issue with Adguard blocking the
connection between Msn and my Microsoft ID , which was always fine
until about a week ago . For some reason Adguard now blocks my sign in
connection with the Msn home page , so that my ID is not connected and
unable to reconnect , therefore I cannot see mail alerts on my home
page . Note that I've been using Adguard for a year and never had this
problem until last week . When I disable Adguard , this issue goes
away . But then obviously ads are back and I'm not protected . 

<details>
  "BlockThirdPartyCookies": true,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false
</details>

Disabling stealth mode did solve the problem

**Comment by evgeniy-ADG** [comment]
Я написал уже ему, логиниться нужно [сюда](http://www.msn.com/)
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16781512/4f4c58ca-4884-11e6-8790-5d28ae6f3d53.png)
</details>
как ответит - напишу про куки

**Comment by evgeniy-ADG** [comment]
@@||login.live.com$stealth - помогло

**Comment by Alex-302** [comment]
ок, добавил
