### ISSUE TITLE
uploads.to/j8l63wndcduw - pop-ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2581]
uploads.to/j8l63wndcduw

STR:

* open the link
* tap on Download or anywhere else
* site opens extra windows with ad content

Pics and description are here: 1262453

<details>
"enabledFilterIds" : [ 2, 3, 4, 14, 7, 11, 211, 216, 217 ],
  "environment" : "prod",
  "filteringQuality" : "FULL",
  "sslMitmConfiguration" : "{\"appsExceptions\":\"38 apps\",\"mitmList\":\"1021 domains\",\"mitmListMode\":\"WHITELIST\"}",
  "statisticsInfo" : "Blocked threats:49; Blocked banners:334458; Traffic saved:9942772736;",
  "trial" : false,
  "updateChannel" : "BETA",
  "upstreamProxySettings" : null,
  "userfilter" : [ "||revclouds.com^*$third-party", "||greatwork.info", "||parser4u.top", "||lucky-visit.org", "||servicegetbook.net^", "||need-this-app.com", "||steepto.com", "||asp.androidsecurityplus.com", "||google.com.pl.s3-website.eu-central-1.amazonaws.com", "||cdn.vm-corporate.com", "||babanetwork.adk2x.com", "||clkdeals.com", "||www.worldlotteryclub.com", "||androidprotect.biz", "||sunsuncre.rocks", "||e.clk.onet.pl^", "||eclkmpsa.com", "||android.com.pl.s3-website.eu-central-1.amazonaws.com", "||nextlandingads.com", "||magicalled.info", "||hbho0.voluumtrk.com", "||appstore-update.com", "||cs.gssprt.jp", "||adplexmedia.adk2x.com", "||play.appiq.mobi", "||dailyuploads.net^*$third-party", "||userscloud.com^*$third-party", "||battlecamp.tumblr.com", "||zh1.november-lax.com", "||n.targetctracker.com", "||onclickads.net", "||ze1.november-lax.com^", "||wh5fn.redirectvoluum.com", "||ocdn01.topmobsapp.com", "||justgetitfaster.com", "||jobsetter.info", "||serve.popads.net", "||zt1.november-lax.com", "||google.com--vir.us", "||tracking.mobitemedia.com" ],
  "versionName" : "2.6.108",
  "whitelist" : [ "vipersaudio.com", "mp.pianomedia.eu" ]
}

**Comment by Alex-302** [comment]
Added to English filter
```
||cloudfront.net^$domain=uploads.to
||s3.amazonaws.com^$domain=uploads.to
||d17rlarvg2khuc.cloudfront.net^
uploads.to#%#Object.defineProperty(window, '_impspcabe_alpha', { get: function() { return false; } }); Object.defineProperty(window, '_impspcabe_beta', { get: function() { return false; } });

```

**Comment by worldsdream** [comment]
Can the the secure download manager checkbox be unchecked by default? Because with the checkbox active and clicking on download, you get redirected to ads/phishing website. 

screenshot: http://i.imgur.com/kywq1uy.png

**Comment by Alex-302** [comment]
Added to English filter
```
uploads.to#%#AG_onLoad(function() { document.getElementById("chkIsAdd").checked = false });
```
