### ISSUE TITLE
google.com - annoying Google App promo

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2583]
**Description**:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=50897030

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
google.ru,google.com.ua,google.by,google.com##mobile-promo
```
`mobile-promo` is a tag

**Comment by ameshkov** [comment]
![developer tools - www google ru gfe_rd cr ei prsgv-tinc2dsahejogaag 2016-08-02 17-55-54](https://cloud.githubusercontent.com/assets/5947035/17333282/6db70e70-58da-11e6-88c4-80352227f004.png)
