### ISSUE TITLE
Stealth mode breaks WSJ authorisation

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2584]
I am trying to disable Adguard for one website only, the Wall Street Journal.  I have a subscription to the Wall Street Journal digital edition. With Adguard enabled I cannot log on to their website. If I disable Adguard I can log on. I would like to allow Adguard to always be enabled for other web sites but allow me to log into WSJ. I have tried using the Adguard filtering but see no way to disable Adguard ONLY on the WSJ web page. The web site to which I try to log on is: http://www.wsj.com. How can I do this?

@@||id.wsj.com$stealth - helps

1344319

**Comment by Alex-302** [comment]
Added.
