### ISSUE TITLE
Реклама на pikapo.ru

### ISSUE THREAD

**Issue by shaurmanchic** [AdguardTeam/AdguardFilters#2586]
Реклама появляется во всех версиях.

<details>
![](https://s31.postimg.org/q1cuwiglz/Screenshot_20160711_175039.png)
</details>
<details>
![](https://s31.postimg.org/gsaome7pz/Screenshot_20160710_120801.png)
</details>
<details>
![](https://s32.postimg.org/a3kmw7zxt/pik1.png)
</details>
<details>
![](https://s32.postimg.org/mjhcpyt9t/pik2.png)
</details>

**Comment by Alex-302** [comment]
Скрины б побольше.
В раздражители:
```
pikapo.ru##h3 > a[href^="/s"]
pikapo.ru##.btn-danger
||pikapo.ru/img/offers/
```
