### ISSUE TITLE
http://m.hindustantimes.com - anti-adblcoker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2588]
![image](https://cloud.githubusercontent.com/assets/15856304/16811549/976a5cd0-4931-11e6-85d5-0f302f69ad3b.png)

Go to m.hindustantimes.com and tap on any article, you'll be redirected to that dummy anti-adblocker page.

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.38 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.55 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.69 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.89 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.4.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.77 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.64 Enabled=YES

**Comment by Alex-302** [comment]
Can't reproduce.
@vozersky please check it on iPad

**Comment by vozersky** [comment]
m.hindustantimes.com  - is not available atm, is there a mobile version at all?
tried to reproduce on hindustantimes.com, looks clear to me

**Comment by Alex-302** [comment]
@vozersky ok
