### ISSUE TITLE
http://p.m.btime.com/ - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2589]
http://p.m.btime.com/detail?id=276615&news_from=1

![image](https://cloud.githubusercontent.com/assets/15856304/16812364/713ac9f6-4935-11e6-90ec-a9e551023c49.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.87 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.62 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.79 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.1.46 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.19 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.80 Enabled=YES
ID=101 Name="EasyList" Version=1.0.60.47 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.61.78 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.61.46 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.61.45 Enabled=NO
ID=219 Name="ChinaList+EasyList" Version=1.0.1.3 Enabled=NO

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
m.btime.com##.sx-download-bar

```
