### ISSUE TITLE
Google Adwords

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2590]
**Description**:
При выборе режима фильтрации HTTP и способ установки прокси - "автоматический", не пускает на сайт adwords.google.com
Т.е. при авторизации на сайте выдается ошибка о просроченном сертификате.

Помогает отключение Английского фильтра. У меня потворилось

Screenshot:
<details>
![screenshot_18](https://cloud.githubusercontent.com/assets/18548949/16817764/03823562-494d-11e6-9418-d4af8ac4a42d.jpg)
</details>

**Steps to reproduce the problem**:
* Перейти на сайт http://www.google.com/adwords/ 
* Затем нажать "Войти" на той же странице
*  И во время авторизации будет ошибка с сертификатом

**Adguard version**: 2.6.108

Лог 
[debug (13).txt](https://github.com/AdguardTeam/AdguardFilters/files/362357/debug.13.txt)
время 18.17

**Filters list**: 1, 2
HTTPS фильтрация отключена

**Operating system**: Андроид

**Browser**: Хром, встроенный 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Что-то не получается исключениями исправить. Создай в разделе дроида, там разработчик может проверить.

**Comment by vgavrish** [comment]
ок

**Comment by Alex-302** [comment]
@vgavrish 
передай юзеру
```
@@||adwords.google.com
```
в фильтр не пойдёт, т.к. ограничить доменом не выйдет.
