### ISSUE TITLE
missed ads https://m.iguides.ru/

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2591]
Реклама присутствует.
![img_0285](https://cloud.githubusercontent.com/assets/16462533/16820249/d1e3d388-4958-11e6-8409-41da82f99a05.PNG)

Фильтры обновленные, базовые Adguard.

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
iguides.ru##div[id^="adriver_banner_"]
```
