### ISSUE TITLE
search.pch.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2592]
**Description**: http://search.pch.com/

**Current behaviour**: Search is not happening

Screenshot: 
<details>
![screen shot 2016-07-13 at 5 28 45 pm](https://cloud.githubusercontent.com/assets/14153331/16820486/3aaedb72-491f-11e6-94ba-85d7d2b96179.png)
</details>

**Expected behaviour**: search results should appear

Screenshot:
<details>
![screen shot 2016-07-13 at 5 31 14 pm](https://cloud.githubusercontent.com/assets/14153331/16820518/7cff5934-491f-11e6-9b07-7d8458bfc083.png)
</details>

**Steps to reproduce the problem**:

* go to http://search.pch.com/
*  type anything and click Search
*  observe spinning Searching

**Adguard version**: Mac 1.3.0

**Filters list**:
![screen shot 2016-07-13 at 5 27 35 pm](https://cloud.githubusercontent.com/assets/14153331/16820445/02a490fa-491f-11e6-8acf-e2284d6bcfbb.png)

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||appapi.inspsearchapi.com^$domain=search.pch.com
@@||csr.inspsearchapi.com/lib/infospace.search.js$domain=search.pch.com
@@||tags.tiqcdn.com/utag/pch/pchsearch/prod/utag.js$domain=search.pch.com

```
Please check it
