### ISSUE TITLE
quora.com [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#25920]
**Site**: https://www.quora.com/

**Issue**: Seeing sponsor ad questions on the main home page (http://prntscr.com/lmq877).

Also seeing ads on answer pages. Check this link as an example: https://www.quora.com/Do-shy-guys-ever-confess-their-feelings-to-their-love-interest-or-wait-for-the-girl-to-make-a-move

**Screenshot**: http://prntscr.com/lmq8pf

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 70.0.3538.102 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.13 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Spam 404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
Any update guys?

**Comment by Alex-302** [comment]
I don't see this element.

**Comment by jineshpatel30** [comment]
I'm also seeing similar sponsored posts

**Comment by jineshpatel30** [comment]
May be this source will help (Search for "sponsored" )
`

</svg></span></div></div></div></a></span></div></div></div></div></div></div><div id='__w2_whV5KRoE70_suggested_section'></div></div></div></div><div class='answer_body_preview'><div class='AnswerExpandable AnswerInFeedExpandable SimpleToggle Expandable Toggle' id='__w2_whV5KRoE60__truncated'><div class='u-serif-font-main--regular'><div class='ui_qtext_truncated ui_qtext_truncated_compact'><div class='ui_layout_content_thumbnail u-flex'><div class='ui_layout_content_wrapper u-relative u-flex-2 u-margin-right--sm'><div class='ui_qtext_truncated_text'><span class="ui_qtext_rendered_qtext"><p class="ui_qtext_para"><b>Content Warning:- </b><i>Disturbing Pics ahead.</i></p><br /><p class="ui_qtext_para">I trolled a mosquito.</p><p class="ui_qtext_para">There was a mosquito annoying me, by sitting again and again on my laptop screen.</p><p class="ui_qtext_para">I shooed him away many times. But that stubborn was in ...</p></span></div><a class='ui_qtext_more_link' href='/What-is-Indian-thug-life-like/answer/Shivam-Aggarwal-139' id='__w2_whV5KRoE76_more'><span>(more)</span></a><span class='hidden' id='__w2_whV5KRoE76_loading'><span class='loading'>Loading…</span></span></div><div class='ui_layout_thumbnail u-flex-auto short_width fixed_height u-bg--center u-bg--cover' style='background-image: url(https://qph.fs.quoracdn.net/main-qimg-d07f25238d22a46848f762f091d2d2c2)'></div></div></div></div></div><div class='AnswerExpandable AnswerInFeedExpandable SimpleToggle Expandable Toggle hidden' id='__w2_whV5KRoE60__expanded'></div></div></div></div></div><div class='hidden' id='__w2_whV5KRoE47_loading'><span class='loading'>Loading…</span></div></div><div class='hidden' id='__w2_whV5KRoE47_editor'></div></div></span><span class='hidden' id='__w2_whV5KRoE33_question_answer_story_editable'></span><div class='Toggle ToggleAnswerFooterWrapper SimpleToggle' id='__w2_whV5KRoE36__truncated'></div><div class='Toggle ToggleAnswerFooterWrapper SimpleToggle hidden' id='__w2_whV5KRoE36__expanded'></div></div></div></div></div></div></div></div><div id='whV5KRoE7'><div class='Bundle' data-clog-metadata='{&quot;feed_bundle_hash&quot;: &quot;6843932438780625200&quot;}'><div class='main_feed singleton_bundle'><div class='multifeed_bundle_story'><div id='wDSrWB0T6'><div class='u-inherit' data-clog-metadata='{&quot;feed_story_hash&quot;: &quot;7500202569717386643&quot;}'><div class='FeedStory feed_item' id='__w2_wDSrWB0T8_item'><span><div class='ktktrsgiyvqpnhesqkli' id='__w2_wDSrWB0T10_tvmqfwxoohclsxgeoxrq'><div class='xlfkncxdwzwgxpaqapfw qziaodusqlvxpkvbwgxt dqirawkzqudgoxajekiq pytetwzpsrkqiqqqbywy'><div id='__w2_wDSrWB0T11_xucrhvqgelwlsewpskld'><div class='dizvvwpqugmycascrfbu'></div><div class='kyufpdqkagisbphlcvtx'><a class='muhbwxgtqyhgjvkshzpk wikrmpfwdzqiwuqtsbyl external_link link_overlay' href='https://www.commonlounge.com/discussion/9921697e30ef4d74999c7f0087bb7edd?r=qp%24-py-ind-adc_hqt_dct_dpt' target='_blank' rel='noopener nofollow' id='__w2_wDSrWB0T30_vuvviklbsboufhfaldea'><p class='mleiqcqeipqvnlhwkart'>sponsored  by Commonlounge</p></a></div><div class='eufcyklmemoiigwpjwhm' id='__w2_wDSrWB0T13_close'><a class='ui_button ui_button--styled ui_button--FlatStyle ui_button--FlatStyle--gray ui_button--size_regular u-inline-block ui_button--non_link ui_button--supports_icon ui_button--icon_only' href='#' role='button' aria-label='Close' id='__w2_wDSrWB0T26_button'><div class='ui_button_inner' id='__w2_wDSrWB0T26_inner'><span style='display: block;' id='__w2_wDSrWB0T25_tooltip'></span><div class='ui_button_icon_wrapper u-relative u-inline-block'><div id='__w2_wDSrWB0T26_icon'><span class='ui_button_icon' aria-hidden='true'><svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
--
  | <g id="small_close" class="icon_svg-stroke" fill="none" fill-rule="evenodd" stroke-linecap="round" stroke="#666666" stroke-width="1.5">
  | <path d="M12,6 L12,18" transform="translate(12.000000, 12.000000) rotate(45.000000) translate(-12.000000, -12.000000) "></path>
  | <path d="M18,12 L6,12" transform="translate(12.000000, 12.000000) rotate(45.000000) translate(-12.000000, -12.000000) "></path>
  | </g>
  | </svg></span></div></div></div></a></div><div class='ewxmvhcislifhbfrhfuj'><a class='muhbwxgtqyhgjvkshzpk external_link link_overlay' href='https://www.commonlounge.com/discussion/9921697e30ef4d74999c7f0087bb7edd?r=qp%24-py-ind-adc_hqt_dct_dpt' target='_blank' rel='noopener nofollow' id='__w2_wDSrWB0T14_wrvoccysgcypwxwdluyg'><div id='__w2_wDSrWB0T15_rtwzqafmdgmghglbwjpz'><div class='rhbsatlwdoslkljrrwsd'>Want to learn Python from scratch and for free?</div></div></a><div class='u-flex content_flex'><div class='u-flex-2'><div class='whnzxpoaenpdnlcexcfu'><div class='zorbyuiyppusqvtwjcgy'><div class='icon_frame'><div id='__w2_wDSrWB0T16_rnpxxsqhbaccrgwrohts'><div class='account_logo_img' style='background-image:url(&quot;https://qph.fs.quoracdn.net/main-qimg-0b78b5f75cb8c11e607dd755d1971ba5&quot;)'></div></div></div><div class='account_description'><div><a class='muhbwxgtqyhgjvkshzpk wikrmpfwdzqiwuqtsbyl external_link link_overlay' href='https://www.commonlounge.com/discussion/9921697e30ef4d74999c7f0087bb7edd?r=qp%24-py-ind-adc_hqt_dct_dpt' target='_blank' rel='noopener nofollow' id='__w2_wDSrWB0T31_gjebpowjvbpzmkuddzke'><p class='mleiqcqeipqvnlhwkart'>Commonlounge</p></a><div class='qcwngvgjzsgwwtjjyzjz'>Sponsored</div></div></div></div></div><div class='u-flex'><div class='u-flex-2'><a class='muhbwxgtqyhgjvkshzpk external_link link_overlay' href='https://www.commonlounge.com/discussion/9921697e30ef4d74999c7f0087bb7edd?r=qp%24-py-ind-adc_hqt_dct_dpt' target='_blank' rel='noopener nofollow' id='__w2_wDSrWB0T18_mxpknriasmstpxjnbssd'><div id='__w2_wDSrWB0T19_lllxavstozahfwhdstrb'><div class='fscngtnyfilqlfnuofwk'>Comprehensive 22-part course includes lots of coding exercises. Beginner friendly, no prerequisites!</div></div></a></div></div></div><div class='lnqbgzdkxzwoiaxscgdd'><div class='u-flex'><div class='u-flex-2'><a class='muhbwxgtqyhgjvkshzpk external_link link_overlay' href='https://www.commonlounge.com/discussion/9921697e30ef4d74999c7f0087bb7edd?r=qp%24-py-ind-adc_hqt_dct_dpt' target='_blank' rel='noopener nofollow' id='__w2_wDSrWB0T20_zfzpmljktygqfafnpzuv'><div id='__w2_wDSrWB0T21_vhrcoubndzcnmnuauiug'><div class='u-flex-auto'><div class='bqwmlorjhwrzyoevshni' style='background-image:url(&quot;https://qph.fs.quoracdn.net/main-qimg-25b1037646f562c49ec9af3240bf5adc&quot;)'></div></div></div></a></div></div></div></div><div id='__w2_wDSrWB0T22_eqtvbfhislafyplsvpvb'><div class='oqfwdvghqyoiloofrrnu'><a class='hhdhemmwjghplctarnpj external_link link_overlay' href='https://www.commonlounge.com/discussion/9921697e30ef4d74999c7f0087bb7edd?r=qp%24-py-ind-adc_hqt_dct_dpt' target='_blank' rel='noopener nofollow' id='__w2_wDSrWB0T29_ydsxcbqmurbrynbqdxnk'>Start Now at commonlounge.com</a></div></div><div class='thopburmpytjpojpinoh'><div id='wDSrWB0T23'><div class='icon_action_bar' id='__w2_wDSrWB0T24_action_bar'><div class='action_bar_inner u-flex'><div class='action_bar_inner_spacer u-margin-left--auto'>&nbsp;</div><div class='overflow action_item overflow_link u-relative'><span id='__w2_wDSrWB0T24_overflow_link'><a class='ui_button ui_button--styled ui_button--FlatStyle ui_button--FlatStyle--gray ui_button--size_regular u-inline-block ui_button--non_link ui_button--supports_icon ui_button--icon_only' href='#' role='button' aria-label='More options' id='__w2_wDSrWB0T28_button'><div class='ui_button_inner' id='__w2_wDSrWB0T28_inner'><span style='display: block;' id='__w2_wDSrWB0T27_tooltip'></span><div class='ui_button_icon_wrapper u-relative u-inline-block'><div id='__w2_wDSrWB0T28_icon'><span class='ui_button_icon' aria-hidden='true'><svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  | <g id="overflow" class="icon_svg-stroke" stroke-width="1.5" stroke="#666" fill="none" fill-rule="evenodd">
  | <path d="M5,14 C3.8954305,14 3,13.1045695 3,12 C3,10.8954305 3.8954305,10 5,10 C6.1045695,10 7,10.8954305 7,12 C7,13.1045695 6.1045695,14 5,14 Z M12,14 C10.8954305,14 10,13.1045695 10,12 C10,10.8954305 10.8954305,10 12,10 C13.1045695,10 14,10.8954305 14,12 C14,13.1045695 13.1045695,14 12,14 Z M19,14 C17.8954305,14 17,13.1045695 17,12 C17,10.8954305 17.8954305,10 19,10 C20.1045695,10 21,10.8954305 21,12 C21,13.1045695 20.1045695,14 19,14 Z"></path>
  | </g>

`

**Comment by Nzzyme** [comment]
Still seeing ads. No fix yet.

**Comment by Nzzyme** [comment]
@AdamWr Can you please check.

Link: https://www.quora.com/Can-learning-web-development-help-me-build-a-search-engine
Screenshot: http://prntscr.com/m66x73

I am also seeing ads in Yahoo email inbox (from Quora email body).

**Comment by AdamWr** [comment]
Unfortunately I can't reproduce it.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/51179638-6e062b00-18c6-11e9-9dd5-ed9c5aa9dc8d.png)

</details>

**Comment by Nzzyme** [comment]
Just checked and still seeing ads on quora.com on the main homepage and also answer pages.

**Site**: https://www.quora.com/

**Issue**: Please remove the sponsored ads as seen in the screenshot.

**Screenshot**: http://prntscr.com/mvs368

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 72.0.3626.121 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 3.0.8 `


**Filters**:
```
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404

```

**Stealth Mode Settings**:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled

**Comment by zloyden** [comment]
Is it still relevant? I can't reproduce it.
