### ISSUE TITLE
missed ads www.instructables.com

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2593]
Пропущена реклама на:
http://www.instructables.com/id/Build-A-Three-Hole-Washers-Board-Game/

![img_0286](https://cloud.githubusercontent.com/assets/16462533/16820519/29754fa4-495a-11e6-9018-0c1a66561854.PNG)

Фильтры базовые Adguard.

**Comment by Alex-302** [comment]
Чисто.

**Comment by Alex-302** [comment]
Что такое базовые фильтры?

**Comment by Serzh-SUP** [comment]
@Alex-302 

![img_0645](https://cloud.githubusercontent.com/assets/16462533/17432723/559676d8-5b09-11e6-95f4-92e677b0c026.PNG)

**Comment by Alex-302** [comment]
Не повторяется.

**Comment by Serzh-SUP** [comment]
Больше не повторяется.
