### ISSUE TITLE
http://forums.kuban.ru/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2594]
**Description**:
http://forums.kuban.ru/f1184/vystavki_i_ispytaniya_ohotnich-ih_sobak-1885835-10.html
Яндекс директ 
У меня не повторяется

**Screenshot:** 
<details>
![screenshot_19](https://cloud.githubusercontent.com/assets/18548949/16837068/c12a03c0-49c9-11e6-8456-bda4c65cd7a9.jpg)
</details>

**Adguard version**: 6.0

**Filters list**: 1,2,3,4,5,14

**Operating system**: Win

**Browser**: Хром
Расширения в браузере не установлены

**Comment by Alex-302** [comment]
Тоже чисто. У него явно какая-то проблема есть. Пусть попробует выключить все фильтры, кроме русского и английского. Если баннер пропадёт - пусть включает по одному с проверкой.

**Comment by vgavrish** [comment]
отписала

**Comment by vgavrish** [comment]
Отключение фильтров не помогло
может это поможет
https://yadi.sk/d/eNvTGND5tYqQx

**Comment by Alex-302** [comment]
Не понятно. Почему-то очень мало общих CSS правил инжектнулось в страницу. Удалённо бы глянуть.
