### ISSUE TITLE
NYTimes.com - Blocked cookie consent = Blocked videos (AdGuard Annoyances filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#25957]
### Affected site:
`https://www.nytimes.com/`

### Issue:
Depending on the location which you're connecting from, some videos won't play if the cookie consent is blocked.

### Example:
` https://www.nytimes.com/2018/09/24/style/robot-furniture-beep-beep-boop.html`

### Problem filter:
* AdGuard Annoyances filter

### Problem rule:
`nytimes.com##.expanded.gdpr[data-testid="gdpr-dock"]`

### Fix:
Remove the above rule, and allow the cookie consent!

### Note:
For the videos to play, the page needs to be refreshed after having accepted the cookie consent (site issue).

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.2.1 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by THEtomaso** [comment]
@krystian3w:

If you're able to reproduce this issue from your location, then perhaps you could post a confirmation message here?:
https://github.com/ryanbr/fanboy-adblock/issues/692/
So far, ryanbr has been unwilling to do anything about this problem, since he's unable to reproduce it from his end.

**Comment by krystian3w** [comment]
Of course, yes I can reproduce; the video does not play/autoplay without a cookie`NYT-T` (for domain "`.nytimes.com`") with any value eg. `ok`, `no`, `1` etc.

**Comment by Alex-302** [comment]
@THEtomaso I can't reproduce. Should I use VPN?(which cuntry?)

**Comment by krystian3w** [comment]
Try use with EU/Europe IP (proxy/vpn). For Example Poland or Norway (as I remember, what he has @THEtomaso)

In Poland I have Cookie Wall and "first-party" videos won't play:

 
![obraz](https://user-images.githubusercontent.com/35370833/49030477-b434ed00-f1a7-11e8-872b-ba967de82023.png) | ![obraz](https://user-images.githubusercontent.com/35370833/49030507-c7e05380-f1a7-11e8-9550-33b4d90adf2e.png)
--- | ---
before accept (black poll) | after accept (video autostart after download).

**Comment by THEtomaso** [comment]
Yeah, I connect from Norway.

**Comment by Alex-302** [comment]
Ok fixed.

**Comment by THEtomaso** [comment]
@Alex-302:
Another exception rule is needed now (blocked cookie consent again).

### Example:
`https://www.nytimes.com/video/magazine/100000006246697/olivia-colman-emma-stone-and-rachel-weisz-coffee-to-go.html`

### Problem filter:
* AdGuard Spyware filter

### Problem rule:
`||optimizely.com^$third-party`

### Possible fix:
`@@||optimizely.com^$third-party,domain=nytimes.com`

**Comment by THEtomaso** [comment]
@AdamWr:
No response from Alex-302.
Perhaps you could look into fixing this (see previous post).

**Comment by AdamWr** [comment]
Ok, added:
```
!+ NOT_PLATFORM(windows, mac, android, ext_chromium, ext_edge)
@@||cdn.optimizely.com/public/$script,domain=nytimes.com
```
By the way, without that rule video doesn't autoplay and video player is black, but works if I click on it. Anyway I added that rule as it's unexcepted behavior in my opinion.
