### ISSUE TITLE
Yandex direct on www.rambler.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2595]
**Description**:
https://www.rambler.ru/
Яндекс директ
У меня не повторяется

**Screenshot:**
<details>
![](http://somehosting.com/adg_off.jpg)
![screenshot_20](https://cloud.githubusercontent.com/assets/18548949/16837204/9882cb72-49ca-11e6-9923-77161a1ad358.jpg)
</details>

**Adguard version:** 6.0

**Filters list:** 1,2,3,4,5,14

**Operating system:** Win

**Browser**: Хром
Расширения в браузере не установлены

**Comment by Alex-302** [comment]
У меня не повторяется

**Comment by evgeniy-ADG** [comment]
У меня тоже, но у пользователя есть во всех браузерах (со слов пользователя).

https://news.rambler.ru/politics/36439245-zeman-vyskazalsya-po-povodu-lisheniya-rossii-chm-po-biatlonu/

![image](https://cloud.githubusercontent.com/assets/15856304/24345493/227de17c-12d9-11e7-87cb-4e6ae8efd396.png)

Еще вопрос, что за странности с расширением, прчему оно не рабтоает в режиме интеграции? Но Помощник при этом есть. Как бороться?

1423137 - тут больше скриншотов, стейт и другая информация.
