### ISSUE TITLE
http://m.girlscene.nl/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2596]
![20160714_112059000_ios](https://cloud.githubusercontent.com/assets/15856304/16837830/66284de2-49ce-11e6-9860-a18877078b4a.png)

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.0.89.3 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.6.64 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.10.36 Enabled=NO

ID=14 Name="Annoyances filter" Version=1.0.1.59 Enabled=YES

ID=10 Name="Filter unblocking useful ads" Version=1.0.0.89 Enabled=NO

ID=1 Name="Russian filter" Version=1.0.35.71 Enabled=NO

ID=6 Name="German filter" Version=1.0.25.98 Enabled=NO

ID=7 Name="Japanese filter" Version=1.0.92.97 Enabled=NO

ID=8 Name="Dutch filter" Version=1.0.8.86 Enabled=YES

ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.25 Enabled=NO

ID=13 Name="Turkish filter" Version=1.0.2.20 Enabled=NO

ID=5 Name="Experimental filter" Version=1.0.26.3 Enabled=NO

ID=11 Name="Mobile Ads filter" Version=1.0.4.20 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.0.81 Enabled=YES

ID=101 Name="EasyList" Version=1.0.59.83 Enabled=NO

ID=102 Name="ABPindo" Version=1.0.0.84 Enabled=NO

ID=103 Name="Bulgarian list" Version=1.0.0.8 Enabled=NO

ID=104 Name="EasyList China" Version=1.0.60.90 Enabled=NO

ID=105 Name="EasyList Czech and Slovak" Version=1.0.1.16 Enabled=NO

ID=106 Name="EasyList Dutch" Version=1.0.60.80 Enabled=NO

ID=107 Name="EasyList Germany" Version=1.0.59.28 Enabled=NO

ID=108 Name="EasyList Hebrew" Version=1.0.2.88 Enabled=NO

ID=109 Name="EasyList Italy" Version=1.0.60.58 Enabled=NO

ID=110 Name="EasyList Lithuania" Version=1.0.0.78 Enabled=NO

ID=111 Name="Latvian List" Version=1.0.0.28 Enabled=NO

ID=112 Name="Liste AR" Version=1.0.2.76 Enabled=NO

ID=113 Name="Liste FR" Version=1.0.60.76 Enabled=NO

ID=114 Name="ROList" Version=1.0.0.59 Enabled=NO

ID=115 Name="RU AdList" Version=1.0.60.72 Enabled=NO

ID=116 Name="Wiltteri" Version=1.0.1.69 Enabled=NO

ID=118 Name="EasyPrivacy" Version=1.0.61.26 Enabled=NO

ID=122 Name="Fanboy's Annoyances" Version=1.0.59.97 Enabled=NO****

**Comment by worldsdream** [comment]
Tested and working

@@||adsur.it/y/service/ads/ads.js

By Blaz

**Comment by Alex-302** [comment]
Added to English filter
