### ISSUE TITLE
http://emgn.com - placeholders

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2598]
http://emgn.com/s2/12-mindblowing-truths-star-wars/2/
![20160714_131404000_ios](https://cloud.githubusercontent.com/assets/15856304/16840581/1ae510b2-49de-11e6-8906-2fdb356f7aa8.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.3 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.59 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.10.72 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.1.59 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.81 Enabled=YES

**Comment by Alex-302** [comment]
to social
emgn.com##.rrssb-holder
to English
emgn.com##body > div[style^="position: fixed; width: 100%; text-align: center; height 110px;"]
emgn.com#$#header.header { top: 0px!important; }
