### ISSUE TITLE
otempo.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#25986]
`https://www.otempo.com.br/cidades/vaca-%C3%A9-flagrada-passeando-em-shopping-de-belo-horizonte-1.784772?amp`

`https://www.otempo.com.br/divers%C3%A3o`

```
||otempo.com.br/rest-services/ads-service
||stats.otempo.com.br^
otempo.com.br##.publicidade-article
otempo.com.br##[id^="ads-"]
```

AdGuard spa,por list
uBlock Origin

**Comment by adranger** [comment]
@Alex-302 

`https://www.otempo.com.br/cidades/pousada-em-brumadinho-foi-destruída-com-35-pessoas-no-local-1.2127989`

![seminovossuper](https://user-images.githubusercontent.com/35470489/51876750-d33f2f00-2350-11e9-9fac-2146a8f51543.png)

**Comment by adranger** [comment]
@Alex-302 

![cookie](https://user-images.githubusercontent.com/35470489/66260822-42034080-e79a-11e9-974d-d8fb696d67a1.png)

**Comment by Alex-302** [comment]
ok
