### ISSUE TITLE
http://www.finanzen.net/ annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2599]
http://www.finanzen.net/waehrungsrechner/schweizer-franken_euro

![20160714_134258000_ios](https://cloud.githubusercontent.com/assets/15856304/16841614/b4a181aa-49e2-11e6-833a-8bd20cd555df.png)

**Comment by Alex-302** [comment]
To annoyances
```
finanzen.net###showpopup2
finanzen.net###smartbanner
finanzen.net#%#document.cookie="sb-closed=true; path=/;";
```
to German
```
finanzen.net##.adsbygoogle
```

**Comment by Bohdan-SUP** [comment]
vozersky reproduced this on iPad, user reported too

please have another look

**Comment by evgeniy-ADG** [comment]
just checked, the pop up does not appear any more, but we have ads on the top, somewhere in the middle and on the right side:

<details>
![20160725_150043000_ios](https://cloud.githubusercontent.com/assets/15856304/17106198/2d7ec890-5293-11e6-85f8-b37288d42490.png)
![20160725_094522000_ios](https://cloud.githubusercontent.com/assets/15856304/17106197/2d7de70e-5293-11e6-8c03-6f89f26c781b.png)
![20160725_150053000_ios](https://cloud.githubusercontent.com/assets/15856304/17106199/2d86d148-5293-11e6-94aa-5569aa63210d.png)

</details>

**Comment by Alex-302** [comment]
@evgeniy-ADG 
check this rule for ads
```
finanzen.net###site > div[id]:not([class]):not([id="shadowContainer"]):not([id="wrapperTop"])
```
