### ISSUE TITLE
http://10tv.nana10.co.il/ - Stealth mode blocks videos

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2600]
http://10tv.nana10.co.il/ videos won't load if Stealth mode is enabled

![image](https://cloud.githubusercontent.com/assets/15856304/16842211/4637328e-49e5-11e6-8e27-bfd923da69da.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
какие опции включены? Всегда уточнайте у юзеров, если сами не пишут.

**Comment by evgeniy-ADG** [comment]
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false
}

**Comment by Alex-302** [comment]
У меня не повторяется, но я на бете. Пусть попробует её.
