### ISSUE TITLE
Edge browser, missed ads on ynet.co.il, mako.co.il

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2601]
We need some help here. User has ads in Edge on certain sites, we can't reproduce the issue;

> Regarding second issue , yes ads are disabled on Chrome , IE and others . It is only with Edge that they don't .Here are some links to pages :
> http://www.ynet.co.il/articles/0,7340,L-4827345,00.html
> http://www.ynet.co.il/articles/0,7340,L-4827207,00.html
> Note that banners are disabled but video ads play .
> Here is another link to a different website where again Adguard doesn't block video ads on Edge :
> http://www.mako.co.il/mako-vod-keshet/milers-crossroads-S1/VOD-c383ea34a84c551006.htm?sCh=3d385dd2dd5d4110&pId=1825219677

Pics<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16842475/559e5918-49e6-11e6-8c3d-64c9d92ccd28.png)
![image](https://cloud.githubusercontent.com/assets/15856304/16842485/5c8427d0-49e6-11e6-8c98-a19a3a5f24f4.png)
![image](https://cloud.githubusercontent.com/assets/15856304/16842504/652a7826-49e6-11e6-8a4b-885643da7da3.png)

</details>
here's the whole state txt <details>
Os version: Microsoft Windows NT 10.0..0
Dot .net version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: a2e9aabfd3d140d487b5d18a81e573af
Language: en
AppVersion: 6.0.226.1108
Main settings: 

FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Wfp
Ads Blocked: 160571, Trackers Blocked: 110895
Filtering Mode: Driver
Application lifetime: 346.00:12:58.5411731
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false
}
</details>

**Comment by Alex-302** [comment]
@evgeniy-ADG 
не понимаю где там нужное, где не нужное. Попроси отметить на скринах что нужно убрать.

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/16913612/a8049ed0-4cb9-11e6-978b-4b2695c404b0.png)
Это ненужное и реклама перед видео тоже не очень нужна.

**Comment by Alex-302** [comment]
У меня чисто
http://imagizer.imageshack.com/img922/7467/p23Nej.png
рекламы перед видео нет.

**Comment by evgeniy-ADG** [comment]
Нет идей, почему у него именно в едже это лезет?

**Comment by Alex-302** [comment]
Идей нет. У меня и без еврейского фильтра этот баннер блокируется.
