### ISSUE TITLE
Spotify 2.6 - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2602]
Screenshots:
<details>
It plays adverts each few songs
![image](https://cloud.githubusercontent.com/assets/15856304/16845098/5bbb7808-49f0-11e6-8d4c-78e5efeb122a.png)

![image](https://cloud.githubusercontent.com/assets/15856304/16845153/9120db3c-49f0-11e6-9c0c-2685411573cd.png)

</details>

Hars, logs and description: 1100489

**Comment by Alex-302** [comment]
@evgeniy-ADG 
ничего интересного не записалось. Подозреваю что оно в плейлисте идёт.

**Comment by ameshkov** [comment]
One more discussion about spotify:
https://forum.adguard.com/index.php?threads/nexus-6p-adguard-not-filtering-spotify.11940/

Rules:
```
||spotify.com/ads/
||adeventtracker.spotify.com^
```
