### ISSUE TITLE
soccer.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2603]
**Description**:
http://www.soccer.ru/
Реклама + "раз вы используете блокировщик"

Screenshot:
<details>
![screenshot_21](https://cloud.githubusercontent.com/assets/18548949/16853426/f10e0ffa-4a14-11e6-9d97-62835cc95b8e.jpg)
![screenshot_22](https://cloud.githubusercontent.com/assets/18548949/16853427/f10fd8c6-4a14-11e6-9f65-200eed6b6e0e.jpg)
![screenshot_23](https://cloud.githubusercontent.com/assets/18548949/16853468/1d734ac4-4a15-11e6-8f7e-673838c7cb21.jpg)
</details>

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
||push.expert^$third-party

soccer.ru#$##beforecontent > div.region-beforecontent > div.block-block { height: 0px!important; }
soccer.ru#$##main_body > div#left.sidebar { margin: 0px 0 0!important; }
@@||soccer.ru/sites/all/themes/mytheme/advert.js
```
Добавил в русский фильтр
```
||err.cloudbit.rocks^$third-party
||soccer.ru/sites/all/modules/baner/baner.js
||emu.ilovemp3.top^$third-party
```
