### ISSUE TITLE
http://www.bild.de/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2604]
http://www.bild.de/wa/ll/bild-de/unangemeldet-42925516.bild.html

![1](https://cloud.githubusercontent.com/assets/15856304/16867709/46866ece-4a41-11e6-98ff-838014d37e0a.png)

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.12 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.66 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.87 Enabled=YES
ID=6 Name="German filter" Version=1.0.26.31 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.82 Enabled=YES
</details>

USER: 1325606

**Comment by Alex-302** [comment]
@evgeniy-ADG check these rules in iOS
```
@@|http://$domain=bild.de,script,third-party
@@||bild.de^$generichide
```

**Comment by worldsdream** [comment]
On Firefox - Dutch, English, Spyware Annoyance.

Going to www.bild.de, will get redirected to the url: http://www.bild.de/wa/ll/bild-de/unangemeldet-42925516.bild.html

The page is almost empty, white page and only header is shown

Adding your rules, it did work like it should. 

I don't get it on iOS, so I can't test that

**Comment by evgeniy-ADG** [comment]
![20160719_111350000_ios](https://cloud.githubusercontent.com/assets/15856304/16948121/d8b818d2-4d80-11e6-91cd-0c28713c682c.png)
![20160719_111400000_ios](https://cloud.githubusercontent.com/assets/15856304/16948120/d8b71784-4d80-11e6-9781-84e9ff461f9c.png)

**Comment by Alex-302** [comment]
Added to Safari filter

**Comment by thislife81** [comment]
This problem is also shown on Windows

**Comment by worldsdream** [comment]
Exactly, should be added to english filter not safari

**Comment by worldsdream** [comment]
@Alex-302 alex you need to add this to english filter and not safari

**Comment by Alex-302** [comment]
@worldsdream No, it is a German site, and it works fine on desktop and Android with German filter(see JS rule for it)

**Comment by Alex-302** [comment]
> This problem is also shown on Windows
Are you using German filter?

**Comment by evgeniy-ADG** [comment]
It's back:

![image1](https://cloud.githubusercontent.com/assets/15856304/20767877/88d26fce-b744-11e6-8383-be2af1e322f2.png)

<details>

![file_000 2](https://cloud.githubusercontent.com/assets/15856304/20767900/9e5be0e6-b744-11e6-9cf7-4b28150c15a6.png)

+ Standard DNS

**Comment by Alex-302** [comment]
Excluded fron DNS filter
```
sascdn.com
```

**Comment by evgeniy-ADG** [comment]
back again: http://www.bild.de/wa/ll/bild-de/unangemeldet-42925516.bild.html

![img_0617](https://cloud.githubusercontent.com/assets/15856304/21457924/6d1bf6ca-c93b-11e6-9e64-885bd1147356.PNG)


<details>

Application version: 1.1.3.31
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: 9BC9B9D7-36F1-4C09-9447-57EF9D0C48DE

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.69 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.72 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.85 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.20 Enabled=YES
ID=6 Name="German filter" Version=1.0.29.59 Enabled=YES

**Comment by osavranska** [comment]
It's back again!

http://m.bild.de/wa/ll/bild-de/unangemeldet-42925516.bildMobile.html - incorrect blocking

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/21491675/292693c0-cc07-11e6-9461-4a65e741b6ec.png)

</details>

<details>

Application version: 1.1.3.31
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: E12897D8-28B9-4ACA-8C57-B354E767D74F

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.66 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.72 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.84 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.16 Enabled=YES
ID=6 Name="German filter" Version=1.0.29.55 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.32 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.89 Enabled=YES

</details>

ID: 1472924

**Comment by Alex-302** [comment]
It is not easy. I will check it later.

**Comment by osavranska** [comment]
One more complain.

http://m.bild.de - incorrect blocking

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/22108124/46c8e0c6-de5a-11e6-8a36-b34cde1cc353.png)

</details>

**Comment by Alex-302** [comment]
It impossible to fix it with current version.

**Comment by evgeniy-ADG** [comment]
This http://www.bild.de/wa/ll/bild-de/unangemeldet-42925516.bild.html appears when you use Adguard DNS, is smth that we're aware of?

**Comment by Alex-302** [comment]
Try to add to whitelist
```
cdn1.smartadserver.com
```
and to user filter:
```
@@||cdn1.smartadserver.com^$document
```
