### ISSUE TITLE
http://www.jeudegolf.org/ - ads, annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2605]
http://www.jeudegolf.org/Comment-lutter-contre-les-mauvais-coups-au-golf/quick-hook-swing-golf.html

<details>
![20160715_080901000_ios](https://cloud.githubusercontent.com/assets/15856304/16867870/5b6ebcaa-4a42-11e6-8279-c80ac14dcd19.png)
![20160715_080916000_ios](https://cloud.githubusercontent.com/assets/15856304/16867871/5b722c1e-4a42-11e6-999a-1b9c9e139253.png)
</details>

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.13 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.67 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.88 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.1.66 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.21 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.82 Enabled=YES
ID=101 Name="EasyList" Version=1.0.60.55 Enabled=YES
ID=113 Name="Liste FR" Version=1.0.61.84 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.61.66 Enabled=YES

**Comment by Alex-302** [comment]
added
```
jeudegolf.org##img[class*="notopenmodal"]
jeudegolf.org###myadsbanner
```
