### ISSUE TITLE
https://m.geektimes.ru/ - ads, social media

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2606]
![20160715_081517000_ios](https://cloud.githubusercontent.com/assets/15856304/16867983/075bad8e-4a43-11e6-9424-a29fff85a765.png)

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.12 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.66 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.87 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.36.47 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.82 Enabled=YES
</details>

**Comment by Alex-302** [comment]
Какие фильтры? Упрощённые или полные?
