### ISSUE TITLE
http://tapochek.net - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2607]
http://tapochek.net/index.php

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16872256/b1747d12-4a59-11e6-9a04-7f79a920e6f0.png)

Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:10 Name: Filter for useful ads Url: http://adguard.com/ru/filter-rules.html?id=10

**Comment by vgavrish** [comment]
При клике вот сюда:
http://prntscr.com/bv4fci
Открывается вулкан и еще один сайт в новом окне.
фильтры 1,2,3,4,,14

**Comment by Alex-302** [comment]
Подчистил.

**Comment by dzamyshlyayeva** [comment]
повторилось 

![screen shot 2016-11-16 at 17 42 19](https://cloud.githubusercontent.com/assets/23372054/20354223/23d8b93a-ac26-11e6-9947-8c60939aa4bc.png)

Application version: 1.1.2.24
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 663BAA65-903F-4107-A21B-2C11BCE3194E

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.0.6 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.88 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.34 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.6.23 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.42.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.65 Enabled=YES


1449954

**Comment by Alex-302** [comment]
Проверь такое
```
tapochek.net##div[id*="Composite"]
```
