### ISSUE TITLE
Yandex music / radio - intermission ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2608]
Добрый день! Предлагаю добавить
блокировку рекламы на Яндекс музыке и
Яндекс. Радио. Там в перерыве между
песнями вставляют рекламные записи.

Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:0 Name: User filter Url: no_url

**Comment by evgeniy-ADG** [comment]
Нужен российский IP, наверное

**Comment by Alex-302** [comment]
Пусть проверит снова. Там добавляли кое что.
