### ISSUE TITLE
http://m.biquge.com.tw/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2609]
http://m.biquge.com.tw/wapbook/14609_7293844.html

![image](https://cloud.githubusercontent.com/assets/15856304/16872894/d52e85c8-4a5d-11e6-940d-af8433424f99.png)

Basic filter set + ChinaList+EasyList

**Comment by Alex-302** [comment]
Basic filter set is only english filter. Spyware and social filters are not enabled by default.
Added to Eng
||ekeide.com^$third-party
