### ISSUE TITLE
com.ally.MobileBanking - whitelist banking app

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#2610]
https://play.google.com/store/apps/details?id=com.ally.MobileBanking
Doesn't work with HTTPs filtering.

**Comment by Alex-302** [comment]
Hi
I can't download this app. Could you try to disable all filters and check again?
Is this app contains ads?

**Comment by TPS** [comment]
This probably belongs under https://github.com/AdguardTeam/AdguardForAndroid/issues, right, @AdGuardTeam?

**Comment by Alex-302** [comment]
Yes.
https://github.com/AdguardTeam/AdguardForAndroid/issues/743
