### ISSUE TITLE
www.theguardian.com - elements reordered

### ISSUE THREAD

**Issue by aaaxx** [AdguardTeam/AdguardFilters#26100]
- Affected file: [AnnoyancesFilter/sections/annoyances.txt](https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/sections/annoyances.txt)
- Commit introducing Guardian rules: [c606a6bf547b22be1a37e586f17cd87620fe8eed](https://github.com/AdguardTeam/AdguardFilters/commit/c606a6bf547b22be1a37e586f17cd87620fe8eed)

The current rule for the Guardian's "Since you're here…" appeal for support, which appears at the end of articles:

```
theguardian.com##.content__main-column > .contributions__epic
```

However, it seems they did some reshuffling, and now the parent element's class is `.content__article-body`. [Here's an example article.](https://www.theguardian.com/us-news/2018/nov/26/paul-manafort-plea-deal-russia-investigation-mueller-lies)

The previous, `.content__main-column` element is still here, but it's not the immediate parent. I'm not sure why the child combinator (`>`) was used in the first place instead of a descendant combinator (space).

<details><summary>Screenshot:</summary>

![Screenshot of the "Since you're here…" appeal for support](https://user-images.githubusercontent.com/6186480/49070868-f2282480-f22c-11e8-9acb-3b728d68e568.png)
</details>

**Comment by krystian3w** [comment]
spaces are ignored, but they have a decorative function / improve readability.

**Comment by krystian3w** [comment]
If ID have space you should use backslash before any ID space:

https://codepen.io/anon/pen/aQjeZj

```html
<div id="There are no waves"> 
Waves,
There are no waves
There are no waves
There are no waves
There are no waves
There are no waves
There are no waves
</div>

Waves should be hidden.
```

```css
#There\ are\ no\ waves { display: none }
```

**Comment by aaaxx** [comment]
Huh? I was talking about descendant combinators inside CSS selectors, whose symbol is a space, and arguing for their use instead of child combinators (">" symbol), which are needlessly specific. In this case:

```
.content__main-column .contributions__epic
.content__main-column > .contributions__epic
```

**Comment by krystian3w** [comment]
https://www.w3schools.com/cssref/sel_element_gt.asp
https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator


It is better to include when adding, even when browsing the site from 3 days, than suddenly discover the subdomain where it will cut too much.


If you can safely remove the child selector, it will be removed.

**Comment by AdamWr** [comment]
Ok, I changed it.
Thank you.

**Comment by Alex-302** [comment]
@AdamWr this is equal to paywall

**Comment by AdamWr** [comment]
Ok, I removed it.

**Comment by aaaxx** [comment]
`theguardian.com##.site-message--banner.yellow.site-message--membership-prominent` should probably be removed as well. It was added in the same commit originally, and it also doesn't seem to be used anymore, as I can't see it in uBlock's logger when I browse the site.

**Comment by AdamWr** [comment]
Yes, you are right, I removed it.
Thank you.
