### ISSUE TITLE
www.15min.lt video banner

### ISSUE THREAD

**Issue by shaurmanchic** [AdguardTeam/AdguardFilters#2611]
Pop up video comes up asking to disable ad blocking.

Go to http://www.15min.lt/verslas/naujiena/kvadratinis-metras/nekilnojamasis-turtas/statybos-vilniaus-uzupyje-kiek-aukstu-matote-973-649617
Wait 10 sec, a video will slide in
<details>
![](https://s32.postimg.org/feoluvvat/Capture.png)
</details>

**Adguard version**: 6.1.232.1142

**Filters list**: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:110 Name: EasyList Lithuania Url: http://margevicius.lt/easylistlithuania.txt

**Operating system**: Windows 10

**Browser**: Chrome

**Comment by Alex-302** [comment]
Check these rules
```
15min.lt###adocean_message
@@||15min.lt/js/ads/banner.js?adzone=$domain=15min.lt
@@||15min.lt^$generichide
```
