### ISSUE TITLE
https://news.walla.co.il

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#26111]
***Description***:
Hi
For a long time have a problem in site:
https://www.walla.co.il/
exmple:
https://news.walla.co.il/item/3160688

sometimes adgaurd stop work in the site this and have much ads and Popup
sometimes this work and sometimes this stop work
i see have on thie much reports open:
https://github.com/AdguardTeam/AdguardFilters/issues/25947
https://github.com/AdguardTeam/AdguardFilters/issues/24739
It happens only with adgaurd

* **Current behaviour**: 
http://prntscr.com/lnnjlu
http://prntscr.com/lnnjrn
and have more!

***Steps to reproduce the problem***:
open the site:
https://www.walla.co.il/

Information | Value
-- | --
Operating system: | win 10
Browser: | Google Chrome
AdGuard version: |6.4.1814.4903

Filters enabled:  
EasyList Hebrew,
EasyPrivacy,
AdGuard Annoyances,
AdGuard Base,
Adblock Warning Removal List

AdGuard DNS:  None
Stealth mode options (Windows only): not enabled

**Comment by MrTal** [comment]
@Alex-302 
still have more ads:
http://prntscr.com/loikcc

**Comment by MrTal** [comment]
@Alex-302 
still have more ads!
http://prntscr.com/loil82
http://prntscr.com/loilfp

**Comment by Alex-302** [comment]
I can't reproduce these ads, only this popup

**Comment by MrTal** [comment]
@Alex-302 
this very strange
now i try with uBlock Origin and with uBlock Origin this yes work and no have ads...
maybe this A problem with adguard?...

**Comment by MrTal** [comment]
@Alex-302 
with i enable AdguardAssistant you can see all ads
http://prntscr.com/lojnvi

**Comment by Alex-302** [comment]
Please check these rules:
```
walla.co.il#%#window.atob = function() { };
walla.co.il#%#AG_abortInlineScript(/TextDecoder/, 'atob');
```

**Comment by MrTal** [comment]
@Alex-302 
yes, this work with rules this!

**Comment by Alex-302** [comment]
Great) Added.

**Comment by MrTal** [comment]
@Alex-302 
the ads are back
can you see here:
https://github.com/uBlockOrigin/uAssets/issues/4287#issuecomment-450130961

**Comment by MrTal** [comment]
@AdamWr 
@Alex-302 
the ads back again!
https://image.prntscr.com/image/UnB9KaiJTT6YfZxndmu3Cw.png
https://image.prntscr.com/image/RF6z6F-tR8ScEoj3WH-lUQ.png
https://image.prntscr.com/image/CstqhsHvQIe3lN3T9k_jog.png
http://prntscr.com/m3d2n9
https://news.walla.co.il/item/3209862
