### ISSUE TITLE
No Adguard Assistant on mts.ru 

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#2612]
All the properties are enabled, but no Assistant icon. Tested with Edge, Yandex, Google browsers.
![default](https://cloud.githubusercontent.com/assets/20476168/16894144/7913649e-4b56-11e6-9383-7ad51d3f9395.png)

**Comment by Alex-302** [comment]
@suhan3z please take a look(turn off Russian filter. It contains an exclusion)
