### ISSUE TITLE
[Windows] www.wetteronline.de - missed ad

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#2613]
![](http://i.imgur.com/TccECqw.jpg)

http://www.wetteronline.de

```
||wetteronline.de/dr/*/css/p_*.css
||wetteronline.de/dr/*/css/www.css
```

**Adguard version**: 6.1.236.1160

**Operating system**: Windows 10

**Browser**: Chrome

**Comment by Alex-302** [comment]
Thanks, added.
