### ISSUE TITLE
[Windows] www.hifitest.de - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#2615]
![](http://i.imgur.com/6C0JtAO.png)

http://www.hifitest.de

``` hifitest.de##div[class^="adl-"] ```

**Adguard version**: 6.1.236.1160

**Operating system**: Windows 10

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to German filter.
