### ISSUE TITLE
http://www.hdzog.com - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2617]
http://www.hdzog.com/videos/27952/crazy-athletes-are-fucking-hard-featuring-amia-miley/?promo=10376

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16906351/4828f27a-4c84-11e6-9aea-a804c13ea8d7.png)
+ tons of other stuff like that
</details>

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.94 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.62 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.79 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.1.49 Enabled=YES
ID=6 Name="German filter" Version=1.0.26.25 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.25 Enabled=NO
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=NO
ID=210 Name="Spam404" Version=1.0.1.31 Enabled=NO

**Comment by Alex-302** [comment]
Added to English filter
```
||direct.hdzog.com/contents/lejpppwud/
hdzog.com##.player-showtime
hdzog.com##.block-showtime
hdzog.com##div[class^="pl_showtime"]

```
