### ISSUE TITLE
[Windows] www.techpowerup.com - missed ad

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#2618]
![](http://i.imgur.com/06RuHoo.png)

https://www.techpowerup.com

```
techpowerup.com##.gfhfgjtuvc
techpowerup.com##.mjktzvfvv
```

**Adguard version**: 6.1.236.1160

**Operating system**: Windows 10

**Browser**: Chrome

**Comment by Alex-302** [comment]
The names are not random. Added.
