### ISSUE TITLE
lanacion.com.ar

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#26188]
Found 2 trackers that expose PII (with the help of Cliqz)

They come from Google (oh surprise!)

I created these rules that seem to stop them

||*pay.google.com/gp/p/ui/pay*^
||*news.google.com/swg/js/v1*^

**Comment by Alex-302** [comment]
Where can I find these requests?

**Comment by The-Filter-guy** [comment]
![captura de pantalla 2018-11-29 a la s 11 20 41](https://user-images.githubusercontent.com/45455838/49228429-378e5280-f3e3-11e8-9316-2bb9d0820d87.png)

**Comment by The-Filter-guy** [comment]
I haven't been able to reproduce the news.google one yet. I did see it yesterday but Cliqz stopped marking it as tracker, so for now, only pay.google is sending PII. If I manage to reproduce it, I´ll post picture here

**Comment by Alex-302** [comment]
Please provide URL, as it is described in template.
