### ISSUE TITLE
mywatchseries.stream [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#26190]
**Site**: https://w3.mywatchseries.stream

**Issue**: Please fix the pop-ups seen when clicking on the search box.

**Screenshot**: N/A

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 70.0.3538.110 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Spam 404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by AdamWr** [comment]
Added:
`mywatchseries.stream#%#window.zfgloadedpopup = true;`
