### ISSUE TITLE
http://www.pornhub.com/ - ads, pop ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2619]
http://www.pornhub.com/

In top its showing "ads by traffic junky, remove ads"
Clicking on a video, gives you a popup.

placeholder:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16906705/287f5b2a-4c8a-11e6-964f-d37c5abab4b2.png)
</details>
Filters:
<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.22 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.67 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.36 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.1.72 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.89 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.35.71 Enabled=NO
ID=6 Name="German filter" Version=1.0.25.98 Enabled=NO
ID=7 Name="Japanese filter" Version=1.0.92.97 Enabled=NO
ID=8 Name="Dutch filter" Version=1.0.8.87 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.25 Enabled=NO
ID=13 Name="Turkish filter" Version=1.0.2.20 Enabled=NO
ID=5 Name="Experimental filter" Version=1.0.26.3 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.4.22 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.82 Enabled=YES
</details>

I was able to reproduce the pop up only once on a first try.

**Comment by Alex-302** [comment]
It is impossible to block this clickunder on iOS, because JS is not supported by content blocker.
