### ISSUE TITLE
payeerotron.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2622]
**Description**: http://payeerotron.ru/
"Включен Adblock, Anti-Banner или похожая программа"

Screenshot:
<details>
![screenshot_28](https://cloud.githubusercontent.com/assets/18548949/16907972/8141a024-4cd0-11e6-80d9-35ac62f9efa8.jpg)
![screenshot_29](https://cloud.githubusercontent.com/assets/18548949/16907973/81460970-4cd0-11e6-8804-fa9fb6ee080a.jpg)
</details>
**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||payeerotron.ru/js/advert.js

```
