### ISSUE TITLE
7ba.ru - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2624]
**Description**:
Screenshot and description are there:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=51293482

**Comment by Alex-302** [comment]
Чисто.

**Comment by Alex-302** [comment]
У юзера рекламы больше нет.

**Comment by vgavrish** [comment]
На главной баннер 7ba.ru
Качественный
Ф: 1,2,3,4,11,14
Иногда нужно пообновлять страницу несколько раз для появления баннера
Встроенный браузер
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19618834/25ff0d8a-985e-11e6-8787-ab5791994f94.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||advcache.ru^$third-party
||my-img.ru^$third-party
```

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/23938337/9a9f3f80-0964-11e7-846a-ea40c1b056b4.png)

Full, VPN, [ 2, 3, 4, 1, 11 ]. Reproducible.

**Comment by Alex-302** [comment]
fixed
