### ISSUE TITLE
[Windows] www.neowin.net - missed ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#2626]
![](http://i.imgur.com/o7OmE9p.png)

http://www.neowin.net/forum/topic/1303154-pok%C3%A9mon-go-could-be-coming-to-windows-10-mobile-but-don039t-get-too-excited-yet/

```
neowin.net##article[class="classes cPost ipsBox ipsComment ipsComment_parent ipsClearfix ipsClear ipsColumns ipsColumns_noSpacing ipsColumns_collapsePhone"]
```

**Adguard version**: 6.1.242.1198

**Operating system**: Windows 10

**Browser**: Chrome

**Comment by Alex-302** [comment]
This element has two differences from another similar elements. But the rule is still dangerous.
Added to Experimental filter:
neowin.net##article[class^="classes "]:not([itemscope])
