### ISSUE TITLE
http://www.adslgate.com/dsl/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2627]
http://www.adslgate.com/dsl/ - missed ads
![image](https://cloud.githubusercontent.com/assets/15856304/16941109/1b0f8eb0-4d5c-11e6-866a-628972a022d1.png)

<details>

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.0.89.39 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.6.71 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.10.95 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.0.85 Enabled=YES

**Comment by Alex-302** [comment]
Added to English filter
||campaign-uploads.s3.amazonaws.com/fl/KSA-Footer/JSFiles/leader.js
