### ISSUE TITLE
https://www.tripadvisor.com - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2628]
https://www.tripadvisor.com/Hotel_Review-g60811-d93892-Reviews-Home2_Suites_by_Hilton_Baltimore_Downtown-Baltimore_Maryland.html

I'm very sure that the problem is coming from easylist China because enabling it alone is sufficient to block the images from loading (all other filters are off).

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16941178/8b07c3cc-4d5c-11e6-8410-828286a1fae9.png)
![image](https://cloud.githubusercontent.com/assets/15856304/16941188/95e21176-4d5c-11e6-9f70-3b590d5fb34f.png)
</details>

[state (40).txt](https://github.com/AdguardTeam/AdguardFilters/files/370819/state.40.txt)

**Comment by Alex-302** [comment]
Looks like a bug
https://github.com/AdguardTeam/AdguardForiOS/issues/119
Closed here
