### ISSUE TITLE
[iOS] wired.com comes up "about:blank"

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2629]
With app active wired.com comes up blank. Address box says "about:blank"

![image](https://cloud.githubusercontent.com/assets/15856304/16941265/11810b52-4d5d-11e6-8841-67e37320acbe.png)

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.21 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.67 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.90 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.1.72 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.22 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.82 Enabled=YES

**Comment by worldsdream** [comment]
I can't reproduce this on iOS with his filters. wired.com opens up great.
I think he needs to update his filterlist?

**Comment by evgeniy-ADG** [comment]
He was asked to do so and he did, I believe. I was testing this on iPad and it worked fine for me as well...

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by evgeniy-ADG** [comment]
:( Asked for more details and STR. Will try to reinstall and delete cache.
