### ISSUE TITLE
semimkv.net [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#26323]
**Site**: https://www.semimkv.net/

**Issue**: Please remove the adblock message on the page

**Screenshot**: http://prntscr.com/lpd5bn

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 70.0.3538.110 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Spam 404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by THEtomaso** [comment]
The fix that I posted is just a suggestion.
It works, but someone from the Adguard team has to add it to their filter.
When they've done so, this report's status will change from "Open" to "Closed".
In the meanwhile, you can add the fix to your personal filter.

**Comment by Alex-302** [comment]
fixed
