### ISSUE TITLE
solarmovie.cam [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#26321]
**Site**: https://solarmovie.cam/14095-nobodys-fool-for-free.html

**Issue**:

1. Please remove the fake links on the page as seen here (http://prntscr.com/lpcyx6)
2. Pop-up also seen when clicking on the actual play buton (http://prntscr.com/lpcxkh)
3. After clicking on the actual play button, on the next page, seeing again the fake links (http://prntscr.com/lpczqg)

**Screenshot**: See above

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 70.0.3538.110 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Spam 404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
@Nzzyme please check these rules(green lines only)
https://github.com/AdguardTeam/AdguardFilters/pull/26577/files

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/26319

**Comment by Nzzyme** [comment]
Ok, so is this the rule that I should check?

solarmovie.cam,solarmovie.watch##.fkplayer

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/9303987d6c2b24ee02b69c96241d98e295b1ba9b
