### ISSUE TITLE
Chatty (MacOS X facebook app) can't log in

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2632]
The [Chatty](https://itunes.apple.com/ua/app/chatty-for-facebook/id981117463?mt=12) app doesn't log in when Adguard is enabled. Turning HTTPs filtering off doesn't help. Сustomer provided the list of filters and will try to disabling them one by one, check here: **1273363**

**Comment by Alex-302** [comment]
I don't want to buy it:)
Ask him for remote access.

**Comment by evgeniy-ADG** [comment]
> I have to add www.messenger.com to whitelist and it works.
> You may close the ticket.

**Comment by Alex-302** [comment]
@evgeniy-ADG  It is too wide exclusion. Temporary added.
Ask for screenshot of filtering log of blocked requests, when messenger.com is in search field. Also I need a triggered rules.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Removed that exclusion.
Please check again.
