### ISSUE TITLE
[NSFW] http://upornia.com - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2633]
http://upornia.com/videos/406381/aiden-aspen-and-lily-labeau-pleasure-voodoo/

Please check screenshots here: **1325606**

**Comment by Alex-302** [comment]
I don't see these ads.
For clickunder:
```
||upornia.com/*.php?z=
```

**Comment by Alex-302** [comment]
The filters are simplified?
