### ISSUE TITLE
Consider adding 2 German banking sites to exceptions

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2634]
Hi, please add these banking websites to the https exceptions list:
https://www.dkb.de/ https://www.volksbankeg.de/ 

> So it would be more secure and I will feel better if Adguard didn't read the financial transactions that I take with my bank.

**Comment by Alex-302** [comment]
I can't do it. Ask in Windows repository

**Comment by worldsdream** [comment]
https://github.com/AdguardTeam/AdguardForWindows/issues/911#issuecomment-233898129

**Comment by worldsdream** [comment]
Referenced the right place, andrey will surely add those. Customer will be happy with transactions.
