### ISSUE TITLE
Filters fail to update

### ISSUE THREAD

**Issue by Fabian42** [AdguardTeam/AdguardFilters#26340]
When trying to update filters, I get the confusing message: "Filters updated successfully – Failed to get updates. Please try again later."
```
Information                            | Value
---                                    | ---
Operating system:                      | Debian
Operating system version (Android/iOS) | 9.6
Browser:                               | Chrome
AdGuard version:                       | 2.10.14
Filters enabled:                       | All except "ABP Japanese Filters"
```
<sub>What I originally wanted to report: AdGuard slightly breaks some Google pages recently, e.g. reminders in Calendar are gone, buttons in GMail are invisible, I can't comment on Google+, …</sub>

**Comment by Fabian42** [comment]
It was apparently somehow caused by "RU AdList" being active, which also seemed to have caused my issues with different websites.
If someone has an account on their forum (https://forums.lanik.us/viewforum.php?f=102), feel free to report it, I don't want to bother to create an account.
But this still shouldn't prevent filter updating, especially since that could potentially be what could fix the issue.

**Comment by Alex-302** [comment]
I can't reproduce with RU AdList enabled:
![image](https://user-images.githubusercontent.com/8361299/49334284-0aa49000-f5db-11e8-9ac4-605b40f17a8e.png)

**Comment by Fabian42** [comment]
Then I guess I'll just leave that filter disabled, it only caused issues anyway.
