### ISSUE TITLE
nulledteam.com [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#26349]
**Site**: https://www.nulledteam.com/

**Issue**: Please remove the adblock message on the page

**Screenshot**: http://prntscr.com/lplmhr

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 70.0.3538.110 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by THEtomaso** [comment]
Fix:
`@@nulledteam.com/js/SvgAdblockDetected/advertising.js`
