### ISSUE TITLE
AdGuard breaks the Comics Scroller extension

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#26352]
### Steps to reproduce

1. Install the extension from the Chrome Store: [link](https://chrome.google.com/webstore/detail/comics-scroller/mccpalfmlnjadfnojmphffidnbemnkec/related?hl=zh-TW)
2. Open `http://www.dm5.com/m5196/` it should open within the extension

### Expected behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/49337757-cc31c400-f620-11e8-8d4d-d30c9010331a.png)

</details>

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/49337760-df449400-f620-11e8-8b5c-e4159fa4c1ab.png)

</details>

### Your environment

* Environment name and version: 70.0.3538.110 
* Operating system and version: macOS 10.14.1, AdGuard 1.5.12
* Filters: Base, Spyware, Social media, Annoyances, Safari, Russian, Annoyances, all up to date
* HTTPS filtering: On

**Comment by Alex-302** [comment]
@Eugene-Savenko please send this rule to customer:
`@@www.dm5.com/*/|$jsinject,extension,elemhide`

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/CoreLibs #643](https://github.com/AdguardTeam/CoreLibs/issues/643) via [**ZenHub**](https://www.zenhub.com/)
