### ISSUE TITLE
http://www.costco.com/ - false blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2635]
On some web sites, eg. COSTCO, the drop down menus do not work unless I set Adguard as an HTTP Proxy

1. So far, this only occurs with the Costco.com website using windows 10 edge or Internet Explorer. 
2. Using Adguard with the "AdBlocker > Enable ad blocking" not checked or checking the "Use Adguard as an HTTP proxy", the dropdown menus, eg. Shop All Departments, works. 

If I keep the "Enable ad blocking" or Use Adguard as an HTTP proxy" checked, I only get the following screen and the dropdown menu for "Shop All Departments, Business Center, etc." does not work. 

**1351232**

**Comment by evgeniy-ADG** [comment]
We're unable to reproduce the issue because of **that** <details>
![image](https://cloud.githubusercontent.com/assets/15856304/16943757/53c0376e-4d6b-11e6-9279-31a474c0ad20.png)
</details>

But we have screenshots ad 2 pages saved as html in the ticket.

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||hlserve.com/Delivery/$domain=costco.com,script
```

**Comment by gwasz** [comment]
I afraid this did not solve the problem.  It allows me to set the first drop=down menu but does not allow me to bring up any of the choices presented on the next screen.  Any suggestions?  Thank you.  GLW

**Comment by Alex-302** [comment]
@gwasz could you provide me remote access via TeamViewer? I can't access to this site now.

**Comment by Alex-302** [comment]
Or check this rule in User Filter
```
@@||hlserve.com^$domain=costco.com,script
```

**Comment by gwasz** [comment]
Alex, 
Thank you for helping me with this problem. Unfortunately, this did not solve the problem. At this point I'm just going to find other options. Thanks again and have a great day. 
George 

----- Original Message -----

**Comment by Alex-302** [comment]
@gwasz 
Is the issue still exists?

**Comment by gwasz** [comment]
The user filter rule that was added for Comcast.com did not work. I removed it last week and the problem still existed until yesterday. Now, for some reason unknown, the problem is now solved and I can bring up all the menus and submenus for that website. 

However, I do have a persistent problem with www.xfinity.com . When I go to the website, I get the following message. "Your browser's cookie functionality is turned off. Please turn it on." The only way I can get to the website is if I temporarily disable protection before I bring up the site. Any suggestions? 

Thank you for your help. 

GLW 

----- Original Message -----

**Comment by Alex-302** [comment]
So costco.com works as expected?

About xfinity.com - I neen your filters list and direct link t broken page. You can help me if you find "bad" filter. You should to disable filters one-by-one with checking.

**Comment by gwasz** [comment]
The Costco.com now works as expected. 

I unchecked each of the main Filter Subscription categories ( "User Filter" through "Wiltteri" ) and still have the same problem accessing xfinity.com. Should I go to each category and uncheck each filter in that category? If so, which category do you recommend I begin with? 

I also tried unchecking the "Block 3rd party cookies" under the Stealth Mode and was then able to access xfinity.com. 

Hope this helps. 

GLW 
----- Original Message -----

**Comment by Alex-302** [comment]
Ok. I can reproduce issue with xfinity.com. As you say, it caused by "Block 3rd party cookies".
Please check this rule in user filter
```
@@||login.comcast.net^$stealth
```

**Comment by gwasz** [comment]
I added the rule and the problem is solved. Thank you for your help and have a great day ! GLW 

----- Original Message -----

**Comment by Alex-302** [comment]
Ok. Thanks) 
The rule is in English filter now.

**Comment by gwasz** [comment]
I'm sorry to say that this has now caused the following problem. When I now attempt to go to my email log on site, I'm directed to an general advertisement site. When I attempt to log on from there, I'm directed back to my original logon site. It keeps recycling through these sites: 

my.infinity.com/?cid=xfinityconnecttocomcast.net - to - xfinity.com - to - my.infinity.com/?cid=infinitycommectotcomcast.net - etc 

The rule is still in my User Filter and it was working before being also placed in the English Filter. 

I was able to access and write this email by disabling Adguard protection. 

Hope this helps. 

GLW 


----- Original Message -----

**Comment by Alex-302** [comment]
I need steps to reproduce. Is it caused by Stealth Mode?

**Comment by gwasz** [comment]
When I uncheck (disable) "Enable Stealth Mode" or "Block third-party cookies" I can access my email. If both of them are checked, I cannot access email. 


----- Original Message -----

**Comment by Alex-302** [comment]
@gwasz 
could you provide me remote access?

**Comment by gwasz** [comment]
Unfortunately, I'm not authorized to grant remote access on this system. 

Note: When I added the following rule to my User Filter, everything worked fine. 
@@||login.comcast.net^$stealth 

You then added a rule to the English Filter and present access problem started. 

Can you delete that rule from the English Filter and let me try to see if I can gain access? 

At my end, it seems that the "Block third-part cookies" is the problem. When I disable it, everything works fine. 



----- Original Message -----

**Comment by Alex-302** [comment]
You can try to disable this rule in English filter in Filter Editor. I'm not sure that this will help.
If you want,  I can give you access to my PC(you need the test email credentials for testing on my PC).

**Comment by gwasz** [comment]
I'm having a problem finding the rule in the English Filter. Is it the same as the on I inserted in the User Filter? Namely: @@||login.comcast.net^$stealth. Also, in what section of the English filtering would it be located? 

----- Original Message -----

**Comment by gwasz** [comment]
I finally found the rule in the English Filter and it didn't make any difference. I also found out the Comcast is having problems with the handling of cookies in the Windows 10 Edge browser. I need to spend some time looking into this before going any further. I really appreciate the time you've spent on this. So, for now, let's just put this on hold.. GLW 
----- Original Message -----

**Comment by Alex-302** [comment]
Heh... I don't understand where you try to login. Here?
login.comcast.net
Or on other domain?

**Comment by gwasz** [comment]
This is where I've been trying to login: https://login.comcast.net Which shows up as: https://login.comcast.net/static/html/errors/cookies-disabled.html and gives me the following message: 

"Your browser's cookie functionality is turned off. Please turn it on." 

As per my last email to you, I thought this was just a Comcast problem with the Windows Edge browser. Now I found that it has also shown up with IE 11. 

Hope this helps. 



----- Original Message -----

**Comment by Alex-302** [comment]
Please check these rules:
```
@@||my.infinity.com^$stealth
@@||login.comcast.net^$stealth
```

**Comment by gwasz** [comment]
Both of these rules did not solve the problem . However, I found that @@||comcast.net^$stealth does work. For some reason the "login." part of the original comcast.net rule was the problem. I've added the modified rule to my User Filter . However, the original nonworking rule is still in the English Filter. 

----- Original Message -----

**Comment by Alex-302** [comment]
OK, an old rule is replaced by `@@||comcast.net^$stealth`
Please check it after filters update.

**Comment by gwasz** [comment]
I can now access the Comcast site without any problem. 

Comcast and Xfinity are really one and the same business. In order to also access Xfinity, I also need to have the following added to the English Filter: @@||xfinity.com^$stealth 

Thank you. GLW 

----- Original Message -----

**Comment by Alex-302** [comment]
Ok, added.
