### ISSUE TITLE
https://www.pinterest.com/ - consider blocking registration offers/popups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2636]
![image](https://cloud.githubusercontent.com/assets/15856304/16945954/5b53246e-4d75-11e6-9133-c9a839a06d14.png)
![image](https://cloud.githubusercontent.com/assets/15856304/16945971/658576da-4d75-11e6-8df2-6ff7ee45e102.png)

**1157108**

**Comment by Alex-302** [comment]
it is impossible now
there are no useful content under popup, only dummy image
https://s-passets-cache-ak0.pinimg.com/webapp/style/app/common/images/inspired-desktop/bg_plants_grid-30ca914f.jpg
