### ISSUE TITLE
nasimke.ru

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2637]
**Description**:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=51336149

**Comment by Alex-302** [comment]
Добавил в мобильный фильтр
```
||mo.spaces.ru./static/$script,domain=nasimke.ru
```

**Comment by vgavrish** [comment]
Реклама в верху
http://nasimke.ru/music?sim=m09lp8fu3te6mmmhgppir488a4
фильтры: 1,2,3,4,11,14
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19528322/286591a6-9634-11e6-95aa-9fdb97ff176e.png)

**Comment by Alex-302** [comment]
Странно. У меня чисто.  Какой алгоритм фильтрации? Можешь у себя глянуть?

**Comment by vgavrish** [comment]
Фильтрация качественная
У меня же и повторилось. Сейчас баннер то есть, то нету. Походила по сайту, пообновляла страницу, появился снова
http://prntscr.com/cwfdv3

**Comment by Alex-302** [comment]
Добавил в мобильный фильтр
```
nasimke.ru##.data-ad-client
nasimke.ru$$script[tag-content="function show_ads"][max-length="6000"]
nasimke.ru##.body > div[class] > div[-ext-has='img[src*="/rekl/"]']
```
Проверь пожалуйста

**Comment by vgavrish** [comment]
походила по сайту, пока не вижу
