### ISSUE TITLE
hindustantimes.com and m.hindustantimes.com - anti-adblock

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2638]
**Description**:
Anti-adblock script works on the homepage. However, it seems that it works for Indian users only.

Here is how it looks like:
![lp0dlrk](https://cloud.githubusercontent.com/assets/5947035/16946351/9d9b9360-4db1-11e6-8b18-7ee14523577a.png)

Maybe we can search for this strings in the source code?

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
||pushcrew.com^$third-party
hindustantimes.com##.install_app
```
Added to English filter
```
@@||hindustantimes.com/res/js/*ads*
```
Added to Social filter
```
hindustantimes.com##.social_icons
```
