### ISSUE TITLE
http://www.qatarshares.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2639]
http://www.qatarshares.com/vb/forum.php

![20160720_054103000_ios](https://cloud.githubusercontent.com/assets/15856304/16976205/465cda40-4e1b-11e6-879c-0eeb86864327.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.0.89.39 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.6.71 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.10.95 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.0.85 Enabled=YES

+ Liste AR

**Comment by al-muftah** [comment]
yes there is lot of ads 

http://d.top4top.net/p_201hkz21.png

**Comment by Alex-302** [comment]
Added to English filter
```
qatarshares.com##.above_body > table[width="100%"] a > img
```

**Comment by Alex-302** [comment]
@al-muftah I can't open your screenshot. Please upload it to other hosting.

**Comment by al-muftah** [comment]
ads still showing on mac safari 

https://s31.postimg.org/glniuar23/Screen_Shot_2016_07_20_at_1_33_16_PM.png

**Comment by Alex-302** [comment]
Did you update the filters?

**Comment by al-muftah** [comment]
How to update the filters on mac safari?

Sent from my iPad

On Jul 21, 2016, at 12:54 AM, Alex <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you update the filters?

-

**Comment by Alex-302** [comment]
Press on Adguard icon
![s](https://adguard.com/images/articles/en/adguard-adblock-functions-en.png)
then scroll to the end of filters list and press Check for filter updstes
![s](https://camo.githubusercontent.com/f4954bdae1734f68ca9128c75ad69f7a7f1e21e8/687474703a2f2f636f6e74656e742e73637265656e636173742e636f6d2f75736572732f7368756d65676f722f666f6c646572732f4a696e672f6d656469612f31353064663565332d306163632d343339662d383561612d6363333634653638323931392f30303030303730302e706e67)

**Comment by al-muftah** [comment]
Its work ? thx

Sent from my iPad

On Jul 21, 2016, at 1:04 AM, Alex <notifications@github.com<mailto:notifications@github.com>> wrote:


Press on Adguard icon
[s]<https://camo.githubusercontent.com/2afa7bc9675655a518eacb5152c9ec41d64686f0/68747470733a2f2f616467756172642e636f6d2f696d616765732f61727469636c65732f656e2f616467756172642d6164626c6f636b2d66756e6374696f6e732d656e2e706e67>
then scroll to the end of filters list and press Check for filter updstes
[s]<https://camo.githubusercontent.com/f4954bdae1734f68ca9128c75ad69f7a7f1e21e8/687474703a2f2f636f6e74656e742e73637265656e636173742e636f6d2f75736572732f7368756d65676f722f666f6c646572732f4a696e672f6d656469612f31353064663565332d306163632d343339662d383561612d6363333634653638323931392f30303030303730302e706e67>

-
