### ISSUE TITLE
http://koozi.info/

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#26416]
***Description***:
Hi
for view video in site:
http://koozi.info/
you need click on ads (here: http://prntscr.com/lprdwl) and only next you click on ads you can see in video

* **Current behaviour**: 
http://prntscr.com/lprcv2

* **Expected behaviour**: 
http://prntscr.com/lprda8

***Steps to reproduce the problem***:
open the site:
http://koozi.info/
and click here: http://prntscr.com/lprdw
next you click on ads you can see video
Information | Value
-- | --
Operating system: | win 10
Browser: | Google Chrome
AdGuard version: |6.4.1814.4903

Filters enabled:  
EasyList Hebrew,
EasyPrivacy,
AdGuard Annoyances,
AdGuard Base,
Adblock Warning Removal List

AdGuard DNS:  None
Stealth mode options (Windows only): not enabled

**Comment by Alex-302** [comment]
Please check these rules:
```
koozi.info#$#.tien-ads-video > div#player { visibility: visible!important; }
koozi.info#$#.tien-ads-video { background: none!important; }
```

**Comment by MrTal** [comment]
@Alex-302 
yes work
tank you!

**Comment by Alex-302** [comment]
Added
