### ISSUE TITLE
missed ads baskino.club

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2642]
**Пропущена реклама**: http://baskino.club/serial/2187-kosti.html

![img_0430](https://cloud.githubusercontent.com/assets/16462533/16983509/c28da920-4e7d-11e6-876e-46f847fb0a26.PNG)

**1.0.8.54**:

**Filters list**:
Базовые Adguard обновленные.

*_iPhone OS 9.3.2 *_:

**Safari**:

**Comment by Alex-302** [comment]
Полные или оптимизированные? У меня чисто.

**Comment by Serzh-SUP** [comment]
@Alex-302 
Полные

**Comment by Alex-302** [comment]
Добавил в фильтр Сафари
```
baskino.club###b-mtbbar__container
```
нужно будет проверить после обновления фильтров.

**Comment by Serzh-SUP** [comment]
@Alex-302 
Проверяю на Adguard Pro с вкл. ВПН все хорошо, отключаю ВПН, появляется реклама Вулкана в шапке и по средине стр. есть еще рекламные баннеры. Но справа, лентой, рекламы нет, как на скрине выше.

**Comment by Alex-302** [comment]
Проверь такое:
```
baskino.club##body > div[id][class][style^="background-image: url(data:image/jpeg;base64"]
```

**Comment by evgeniy-ADG** [comment]
Вот как с этим правилом выглядит:

![file_000](https://cloud.githubusercontent.com/assets/15856304/19183016/13120faa-8c7f-11e6-9fa4-a0aa88c47cd5.png)

**Comment by Alex-302** [comment]
Это уже у юзера что-то. На первом скрине этот баннер скрыт, и у меня тоже не видно.
Добавил то правило.

**Comment by Alex-302** [comment]
Пусть попробуе выключить все фильтры и включить снова.

**Comment by evgeniy-ADG** [comment]
Снова есть. Отлично скрывается версией Pro.

![image](https://cloud.githubusercontent.com/assets/15856304/21072219/78c5df9a-bec3-11e6-984d-f99b0a172f37.png)


<details>


Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.69 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.43 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.29 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.58 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.5 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.18 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.81 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.36 Enabled=YES

**Comment by Alex-302** [comment]
Добавил в фильтр Сафари
```
baskino.club##div[id*="Composite"] *
```
мне помогло
