### ISSUE TITLE
http://www.filmarenasi.com/ -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2643]
**Site**: http://www.filmarenasi.com/karak-filmi-full-720p-izle.html

**Screenshot**: 
![qw](https://cloud.githubusercontent.com/assets/19608513/16987278/6d3af116-4e9c-11e6-907b-529bfb33407b.png)

**Adguard version**: 2.4.1

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
I don't see a player.
Added to Turkish filter
```
filmarenasi.com#$##film { display: block!important; }
filmarenasi.com###filmoncereklam
```
