### ISSUE TITLE
http://www.filmcuk.org/ -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2644]
**Site**: http://www.filmcuk.org/kemik-balta-bone-tomahawk.html

**Screenshot**: 
![as](https://cloud.githubusercontent.com/assets/19608513/16987353/c70eb970-4e9c-11e6-971a-f7c45de15578.png)

**Adguard version**: 2.4.1

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
filmcuk.org##div[class$="rkads"]
```

**Comment by thislife81** [comment]
Please remove this.

![qw](https://cloud.githubusercontent.com/assets/19608513/18032864/f3236438-6d24-11e6-8165-6e7147662746.png)

**Comment by Alex-302** [comment]
Added to Turkish filter
```
filmcuk.org##.footer-sticky
```
