### ISSUE TITLE
http://www.fullhdfilm.gen.tr/ -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2645]
**Site**: http://www.fullhdfilm.gen.tr/kanli-elmas-blood-diamond-1080p-izle.html

**Screenshot**: 
![xz](https://cloud.githubusercontent.com/assets/19608513/16987430/45092298-4e9d-11e6-96b8-76fc3cea8298.png)

**Adguard version**: 2.4.1

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
fullhdfilm.gen.tr##.tab-reklam
fullhdfilm.gen.tr#$#.tab-embed { display: block!important; }

```
