### ISSUE TITLE
http://hdfilmcenneti.org/ -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2646]
**Site**: http://hdfilmcenneti.org/korkak-2010-full-hd-izle.html

**Screenshot**: 
![cx](https://cloud.githubusercontent.com/assets/19608513/16987543/eb1bae12-4e9d-11e6-8f50-e34b844a432f.png)

**Adguard version**: 2.4.1

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdfilmcenneti.org##a[href="http://princessbet.com/promotions/"]
```
Added to Annoyances filter
```
hdfilmcenneti.org###M171545ScriptRootC54887
```

**Comment by thislife81** [comment]
Probably you forgot to add this ad.
![ew](https://cloud.githubusercontent.com/assets/19608513/16992528/b733b5f0-4eb0-11e6-92e8-f59065d2e4fc.png)

**Comment by Alex-302** [comment]
hdfilmcenneti.org###alt
hdfilmcenneti.org##a[href^="http://www.bedavaonlinebahis.com/"]
