### ISSUE TITLE
http://www.filmionlineizle.net/ -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2647]
**Site**: http://www.filmionlineizle.net/whiskey-tango-foxtrot-izle.html

**Screenshot**: 
![nb](https://cloud.githubusercontent.com/assets/19608513/16987965/bdaaaa94-4e9f-11e6-8a72-9ff8b9d40545.png)

**Adguard version**: 2.4.1

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Can't acces.

**Comment by thislife81** [comment]
When you enter the site you see that page is clean? These ads aren't shown on your browser?

![df](https://cloud.githubusercontent.com/assets/19608513/16992342/f079f924-4eaf-11e6-9f78-b98f95e33f05.png)

**Comment by thislife81** [comment]
Mmm. Then you try to enter this site: http://www.filmionlineizle.net/ and after entering click any link..

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
filmionlineizle.net###alt
```
Added to Turkish filter
```
filmionlineizle.net###filmoncereklam
filmionlineizle.net#$##film { display: block!important; }
##div[class^="bireklam"]
```
