### ISSUE TITLE
https://etatlibredorange.com/ - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2648]
https://etatlibredorange.com/en/shop/rien-intense-incense-en/#tab-description

Can't add to cart
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16991115/259955bc-4ea3-11e6-98b3-eb19a30bbb2c.png)
![image](https://cloud.githubusercontent.com/assets/15856304/16991137/34d8ed9e-4ea3-11e6-9aa9-309f3215bdb3.png)
</details>

Hiding bottles' images [here ](https://etatlibredorange.com/en/shop/) and [here](https://etatlibredorange.com/)
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/16991166/535dccd0-4ea3-11e6-92c7-6afbde936776.png)
![image](https://cloud.githubusercontent.com/assets/15856304/16991176/5b241c3a-4ea3-11e6-8103-069c8fa50e7c.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG всегда список фильтров прикладывай. Если нету - проси юзера прислать. Иначе пол часа уходит на повторение проблемы.

**Comment by Alex-302** [comment]
Добавил в фильтр раздражителей
```
@@||etatlibredorange.com/wp-content/plugins/cookie-law-info/js/cookielawinfo.js

```

**Comment by evgeniy-ADG** [comment]
Ok, буду. Sorry.
