### ISSUE TITLE
http://sinemapol.com/ -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2649]
**Site**: http://sinemapol.com/

**Screenshot**: 
![mn](https://cloud.githubusercontent.com/assets/19608513/16992986/90b66768-4eb2-11e6-8401-a42b9eb52a52.png)

**Adguard version**: 2.4.1

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
sinemapol.com###toolbar
sinemapol.com##.advertise-468x60

```
