### ISSUE TITLE
http://www.hdsonbolumizle.com/ -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2650]
**Site**: http://www.hdsonbolumizle.com/the-night-manager-1-sezon-izle.html

**Screenshot**: 
![yt](https://cloud.githubusercontent.com/assets/19608513/16993099/0c6fd98e-4eb3-11e6-9e63-fa1a8f816924.png)

**Adguard version**: 2.4.1

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdsonbolumizle.com##a[rel="nofollow"][style]


```
Added to Social filter
```
hdsonbolumizle.com##.share.meta
```
