### ISSUE TITLE
http://www.hdfullfilmizlesene.org/ -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2651]
**Site**: http://www.hdfullfilmizlesene.org/

**Screenshot**: 
![vx](https://cloud.githubusercontent.com/assets/19608513/16993500/c307318c-4eb4-11e6-9a77-e995a9fe85a2.png)

**Adguard version**: 2.4.1

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdfullfilmizlesene.org##.alt-banner
hdfullfilmizlesene.org##.splash-reklami

```

**Comment by thislife81** [comment]
Please remove this.

![nn](https://cloud.githubusercontent.com/assets/19608513/18032826/2523ee72-6d24-11e6-95ee-95ec0172ba55.png)

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdfullfilmizlesene.org##a[title$="reklam kapat"]
```
