### ISSUE TITLE
http://www.filmbudur.org/ -popup

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2652]
**Site**: http://www.filmbudur.org/

**Screenshot**: Link is this in the background
![tr](https://cloud.githubusercontent.com/assets/19608513/16993653/49906994-4eb5-11e6-8807-6c76a2c09caf.png)

**Adguard version**: 2.4.1

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
filmbudur.org#%#Object.defineProperty(window, 'initPu', { get: function() { return {}; } });
```
