### ISSUE TITLE
http://lostfilm-online.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2653]
http://lostfilm-online.ru/
![image](https://cloud.githubusercontent.com/assets/15856304/17013733/5eb60426-4eee-11e6-9780-744f9f115b36.png)
Basic filters

**Comment by Alex-302** [comment]
Скорее всего баг, веб-сокеты не блокируются
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/299
