### ISSUE TITLE
nnmclub.to - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2654]
Filters are up to date
http://nnmclub.to/forum/portal.php?c=3
![image](https://cloud.githubusercontent.com/assets/15856304/17014071/673b91b8-4ef0-11e6-8103-6fdb37cc7382.png)

**Comment by Alex-302** [comment]
Похоже на баг Сафари
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/299
