### ISSUE TITLE
http://onlainfilm.ucoz.ua/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2655]
http://onlainfilm.ucoz.ua/load/trillery/prizrak_opery_smotret_onlajn/36-1-0-4804
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17014319/045b37ae-4ef2-11e6-9fc9-6dffae941b46.png)

![image](https://cloud.githubusercontent.com/assets/15856304/17014346/259c12b2-4ef2-11e6-80a8-eed6c0ac54a0.png)

**Comment by Alex-302** [comment]
В Хроме 51 чисто и с расширением, и с программой. В иОС- баг.
Для старых версий Хрома с расширением добавил
```
onlainfilm.ucoz.ua#%#window.WebSocket = undefined;
```
