### ISSUE TITLE
https://e.mail.ru/messages/inbox# - ads, again

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2656]
https://e.mail.ru/messages/inbox#
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17015719/b7d89b08-4ef9-11e6-81d7-1ea39f08f43e.png)
![image](https://cloud.githubusercontent.com/assets/15856304/17015919/a8320b02-4efa-11e6-85cc-b8b3eb203ecf.png)

**Comment by Alex-302** [comment]
Ну ёлки, пиши хоть что за браузер и какой Адгард. Не телепат же.

**Comment by Alex-302** [comment]
Версия браузера тоже имеет значение, т.к. например в Хроме до 47 версии веб-сокеты не блокируются.

**Comment by evgeniy-ADG** [comment]
Version 51.0.2704.103 (64-bit) Mac

**Comment by Alex-302** [comment]
У меня чисто.
Пусть попробует бету
https://chrome.google.com/webstore/detail/adguard-adblocker-beta/gfggjaccafhcbfogfkogggoepomehbjl?utm_source=chrome-app-launcher-info-dialog

**Comment by evgeniy-ADG** [comment]
Чё-то все равно есть
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17047622/9f86bf9a-4fe8-11e6-9d31-2eb11b078933.png)
</details>

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17047674/fd71ab06-4fe8-11e6-960e-b202bae69b41.png)

</details>

Сохранил страницу: 
[Archive.zip](https://github.com/AdguardTeam/AdguardFilters/files/377537/Archive.zip)

**Comment by Alex-302** [comment]
Какая версия браузера? Если ниже 47, то там веб-сокеты не блокируем.

**Comment by evgeniy-ADG** [comment]
Версия та же: Version 51.0.2704.103 (64-bit) Mac, browser extension, все тестил у себя, свою версию и написал.

**Comment by Alex-302** [comment]
Крайне странно. Открой дев тулз(F12), перейди во вкладку Network, выбери WS и обнови вкладку.
http://imagizer.imageshack.com/img923/6874/M1vqXQ.png
После появления рекламы сделай скрин и скопируй сюда url запроса

**Comment by evgeniy-ADG** [comment]
Естественно, уже не повторяется, но мануал я сохраню )

**Comment by Alex-302** [comment]
Видать фильтры старые были. Ничего нового не добавлял для почты.
