### ISSUE TITLE
http://www.elperiodico.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2657]
http://www.elperiodico.com/es/noticias/politica/polemica-parlament-conjuncion-copulativa-comision-proceso-constituyente-5276985
![image](https://cloud.githubusercontent.com/assets/15856304/17021465/27d3eb62-4f16-11e6-8de7-6e8a8c409ca0.png)

We're unable to reproduce it, asked for HTTP requests logs. Please check here: 1261942

**Comment by Alex-302** [comment]
It should be clean. Google ads are blocked in his log. Maybe the page is cached, or filtering was disabled.

Added to Social filter
```
elperiodico.com##.comp.ep-toolbar
```

**Comment by evgeniy-ADG** [comment]
Done

**Comment by evgeniy-ADG** [comment]
The issue occurred again. After deleting Safari's cahce it has gone, but than it's come back. Please have a look here **1261942** and check logs (July, 20-21). Please advise.

**Comment by Alex-302** [comment]
Can't reproduce. He can try reinstall Adguard and check this site without any changes in Adguard settings.
