### ISSUE TITLE
http://www.hotelkrs.ru/  -  annoyances

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2658]
http://www.hotelkrs.ru/  - чат/зонилка

![image](https://cloud.githubusercontent.com/assets/15856304/17023102/985459a4-4f1f-11e6-8d32-004b30e4c89f.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
||consultsystems.ru^$third-party
```
