### ISSUE TITLE
http://www.legalinsurrection.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2660]
Missed ads / sponsored content:
![image](https://cloud.githubusercontent.com/assets/15856304/17047846/f8930098-4fe9-11e6-86e8-6edfc083e97b.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.58 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.76 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.1.90 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.89 Enabled=YES
ID=101 Name="EasyList" Version=1.0.60.74 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.62.13 Enabled=YES

**Comment by Alex-302** [comment]
Added to English filter
```
legalinsurrection.com#%#Object.defineProperty(window, 'gf', { get: function() { return {}; } });

```
