### ISSUE TITLE
123kmovies.co [Fake Buttons & Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#26608]
**Site**: https://www.123kmovies.co/watch-king-kong-2005-movie-free-download-720p-bluray/

**Issue**: Pop-up & fake play button

**Screenshot**: http://prntscr.com/lry7dy

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 71.0.3578.80 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by krystian3w** [comment]
`##a[href*="oclaserver.com/afu.php?zoneid="]`

:question:
