### ISSUE TITLE
http://www.macbed.com/ - anti-adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2663]
http://www.macbed.com/download/27719.html

![image](https://cloud.githubusercontent.com/assets/15856304/17051333/d1e97cd0-5000-11e6-8a41-d527c1da62b2.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-07-16 08:42:34 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.2
ID: 4D1D64F4-4285-479E-989E-C3288E53A761

Locale: en
Region: ca

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.22 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.67 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.90 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.1.72 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.89 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.22 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.82 Enabled=YES
ID=101 Name="EasyList" Version=1.0.60.60 Enabled=NO
ID=118 Name="EasyPrivacy" Version=1.0.61.75 Enabled=NO
ID=122 Name="Fanboy's Annoyances" Version=1.0.60.74 Enabled=NO
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.1.90 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.61.89 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.61.75 Enabled=NO
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES

**Comment by worldsdream** [comment]
I am having the same on iOS and Firefox

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||macbed.com^$generichide
macbed.com##.adsbygoogle
```

**Comment by worldsdream** [comment]
Thanks alex, what about firefox? We are not going to get js rules in firefox. Thanks.

**Comment by worldsdream** [comment]
I updated filterlist on my ios device, I still get that screen to disable adblock.

**Comment by Alex-302** [comment]
Maybe you are using too much filters, and some rules are missed(my filters list contains 80k rules, so in Safari we lost 30k rules)

**Comment by worldsdream** [comment]
I am using 22k

**Comment by Alex-302** [comment]
Simplified?

**Comment by worldsdream** [comment]
Nope

**Comment by Alex-302** [comment]
Are you sure? Only English filter contains more than 58k rules.

**Comment by worldsdream** [comment]
That is showing in the iOS app down below. 

7 filters enabled
Active filter rules: 21942

**Comment by Alex-302** [comment]
It is possible only if you are using simplified rules. Check this option in the settings.

**Comment by worldsdream** [comment]
I was sure and I again checked in settings, it's not enabled. 

I enabled and disabled, just to make sure. Still the same when I go to that page it's showing anti adblock. 

http://www.macbed.com/download/27719.html

**Comment by Alex-302** [comment]
It is very strange, should be 50000 rules. Confirmed on real device.

**Comment by worldsdream** [comment]
I tested on another device, enabled all the filters. Same count of rules. Is the ios app calculating it wrong then?

I also did add those 2 rules in userfilter, still get the anti adblock

**Comment by Alex-302** [comment]
Developer said the number of rules is correct.
But I don't understand why that rules are not working on iOS.
I see only one rule in content-blocer from iPad
```
    {
        "trigger": {
            "url-filter": ".*",
            "resource-type": [
                "document"
            ],
            "if-domain": [
                "*macbed.com"
            ]
        },
        "action": {
            "type": "css-display-none",
            "selector": ".adsbygoogle"
        }
    }
```
@ameshkov could you please help with this issue?
Added rules works as expected in Safari on Mac OS.

**Comment by worldsdream** [comment]
You fixed all the issues before, i'm sure you or andrey will sort this out :)

**Comment by ameshkov** [comment]
Hey @Alex-302, $generichide currently works the same way as $elemhide (so it disables ALL hiding rules).

We'll change this behaviour soon:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/171

**Comment by worldsdream** [comment]
I tried on Mac safari, also showing adblocker detection. Not using optimized filter.

**Comment by Alex-302** [comment]
@ameshkov I know it. This antiadblock script checks only for hidden elements, but this rule is not working on iOS. I don't see it in filter.log:
https://github.com/AdguardTeam/AdguardFilters/issues/2663#issuecomment-235371743

**Comment by ameshkov** [comment]
@Alex-302 of course it won't work if you have an elemhide rule disabling it.

**Comment by Alex-302** [comment]
@ameshkov but why? 
This rule must disable element hiding
`@@||macbed.com^$generichide`
this rule - for the future #171
`macbed.com##.adsbygoogle`

**Comment by worldsdream** [comment]
Any update on this one? Still having it on ios. Showing to disable adblocker.

**Comment by ameshkov** [comment]
@worldsdream it will be resolved with the next iOS release (along with Pro version release).
