### ISSUE TITLE
http://www.ad.nl/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2664]
http://www.ad.nl/
![image](https://cloud.githubusercontent.com/assets/15856304/17051489/b45c3260-5001-11e6-9dec-db8fdde7fdf3.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-06-18 14:42:42 +0000

Device: iPhone
Platform: iPhone OS
OS: 10.0
ID: 47AFDB05-5110-49B6-AB17-DE3A400232BF

Locale: nl
Region: nl

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.87.5 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.38 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.31 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.0.80 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.8.78 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.67 Enabled=YES
ID=101 Name="EasyList" Version=1.0.59.70 Enabled=YES
ID=106 Name="EasyList Dutch" Version=1.0.60.39 Enabled=YES

**Comment by worldsdream** [comment]
https://forum.adguard.com/index.php?threads/ad-nl-cookie.11247/

**Comment by Alex-302** [comment]
It is impossible to remove on iOS.
