### ISSUE TITLE
http://www.finanzen.net/ - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2667]
http://www.finanzen.net/waehrungsrechner/schweizer-franken_euro

![image](https://cloud.githubusercontent.com/assets/15856304/17057127/c8d57412-5020-11e6-9135-4b01d5f5ea6b.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.9 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.54 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.10.63 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.1.63 Enabled=YES
ID=6 Name="German filter" Version=1.0.26.30 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.82 Enabled=YES

**Comment by evgeniy-ADG** [comment]
Вова повторил, я - нет.

**Comment by Alex-302** [comment]
На иОС похоже не убрать, это антиадблоковская реклама, взамен заблокированной. Без JS не убрать.
