### ISSUE TITLE
new.vk.com - false blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2668]
Adguard blocks 'share this picture' option:

![image](https://cloud.githubusercontent.com/assets/15856304/17066596/6d939afe-5050-11e6-8e96-d37c8d44c830.png)

When you disable Adguard, it works fine, 

![image](https://cloud.githubusercontent.com/assets/15856304/17066627/8d9d0f1a-5050-11e6-9b1d-43ec7bc272d8.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
всё нормально с сайтом?

**Comment by evgeniy-ADG** [comment]
Йеп, каким-то чудом появилось три правила в юзер фильтре, которых я не вносил. Может, после тестировния чего-то остались. В общем, ложная тревога, сорри.
