### ISSUE TITLE
http://bnonews.com/news/index.php/news/id4926 - Block Adblock script

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#2669]
![default](https://cloud.githubusercontent.com/assets/20476168/17076916/42e648de-50c7-11e6-82b0-5d4011b75d1e.PNG)
Filters enabled
![default](https://cloud.githubusercontent.com/assets/20476168/17076927/695e30a8-50c7-11e6-9a4b-dc4937c3a789.PNG)

Tested with Chrome, IE, Edge.

**Comment by Alex-302** [comment]
Added to English filter
```
bnonews.com#%#(function() { var _eval = window.eval; window.eval = function(a) { if ( a.toString().indexOf('babasbmsgx') === -1 ) { _eval(a); return; } }; })();
```
Added to Safari filter
```
bnonews.com##.advertisement
bnonews.com##.adsbygoogle
bnonews.com##div[id^="div-gpt-ad"]
@@||bnonews.com^$generichide
```
