### ISSUE TITLE
http://artsgtu.ru/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2671]
**Description**: Вы посетили наш сайт с включенным блокировщиком рекламы!
http://artsgtu.ru/

Screenshot:

<details>
![](http://somehosting.com/adg_off.jpg)
![screenshot_13](https://cloud.githubusercontent.com/assets/18548949/17077631/1de1fc8c-50df-11e6-9c87-7d520d48a949.jpg)

</details>

**Adguard version**:

**Filters list**: 1,2,3,4,14

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
artsgtu.ru##table[style^="height: 200px;"][width="900"]

```
