### ISSUE TITLE
https://play.spotify.com - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2672]
https://play.spotify.com/browse
![image](https://cloud.githubusercontent.com/assets/15856304/17078409/257edba6-50fb-11e6-9f17-eef7b7ec338e.png)
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17078417/47c3f174-50fb-11e6-8e31-f9d5eca7a63e.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
spotify.com#@##ads
```
