### ISSUE TITLE
docfilms.info

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2673]
**Description**: Баннеры
http://docfilms.info/bbc/1338-bbc-kosmos.html

И при нажатии в эту область открывается левый сайт:
http://prntscr.com/bws2ld
Screenshot:

<details>
![screenshot_44](https://cloud.githubusercontent.com/assets/18548949/17082352/95e39bec-5183-11e6-8b53-1773049cd047.jpg)
</details>

**Filters list**: 1,2,3,4,14
**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||afterview.ru^$third-party
.docfilms.info^$script,domain=docfilms.info
```
