### ISSUE TITLE
[AdGuard filters, via uBlock Origin] proper.io

### ISSUE THREAD

**Issue by ArenaL5** [AdguardTeam/AdguardFilters#26745]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: `proper.io` loads advertising and tracker scripts from several domains (at least in my example, `tropes.org`)
* **Current behaviour**: 

The scripts themselves are blocked by the AdGuard filters list, but `proper.io` isn't, wasting resources on more than seventy unneeded requests. TV Tropes works all the same regardless of what domains you block.

The Cloudfront subdomain currently loads scripts from clean.gg, which are again blocked by your filters. As that subdomain is probably only used by TV Tropes, I use a domain-specific block to deal with that.

<details><summary>Screenshot:</summary>

![proper.io not directly blocked](https://user-images.githubusercontent.com/37388405/49699953-1e05bb80-fbd8-11e8-888d-1844c09a727c.png)

</details><br/>

* **Expected behaviour**: 

Those requests shouldn't appear at all in the logger. proper.io itself may track users, or start loading scripts from different servers.)

There are already exception filters for `proper.io` in your lists (to fix a couple of domains broken by EasyList?), so it should not cause any more problems to block it.

<details><summary>Screenshot:</summary>

![proper.io blocked](https://user-images.githubusercontent.com/37388405/49699956-2a8a1400-fbd8-11e8-9408-2a6709536b4b.png)
</details><br/>

***Steps to reproduce the problem***:

Go to TVTropes.org (`https://tvtropes.org`), using uBlock Origin 1.17.4 with the configuration below. I'm currently using only gufw as firewall and uBlock Origin as web blocker (no AdGuard) 

***System configuration***

**Filters:**

All of the uBlock filters (uBlock filters​​​​​, uBlock filters – Badware risks​, uBlock filters – Experimental​, ​​​​uBlock filters – Privacy​​​​​, ​​uBlock filters – Resource abuse​​​​​, ​​uBlock filters – Unbreak), AdGuard Base Filters, AdGuard Mobile Filters, AdGuard Spyware Filters, Malware Domain List, AdGuard Spanish/Portuguese.

Information                            | Value
---                                    | ---
Operating system:                      | GNU/Linux Debian
Operating system version  | 4.9.110-3+deb9u6
Browser:                               | Firefox Quantum 60.3.0esr (64-bit)

**Comment by Alex-302** [comment]
It is blocked on my end
![image](https://user-images.githubusercontent.com/8361299/49747177-7ce83500-fcab-11e8-84e1-4f9331c19de7.png)
Please check with AdGuard filters only, maybe the issue is in another filters.

**Comment by ArenaL5** [comment]
I've trying disabling any other filter, and you're right, the filter list at `adguard.com` blocks `proper.io`. The filter list I was using for uBlock origin has this header:

```
![Adblock Plus 2.0]
! Checksum: DM/bLnQq1y8OwVTa7uyljw
! Title: AdGuard Base filter
! Description: This filter is necessary for quality ad blocking.
! Version: 2.0.22.90
! TimeUpdated: 2018-12-09T01:02:22+03:00
! Expires: 2 days (update frequency)
! Homepage: http://adguard.com/filters.html#english
! License: http://creativecommons.org/licenses/by-sa/3.0/
```

and `proper.io` does not appear there, but it does appear in your page `https://filters.adtidy.org/extension/chromium/filters/2.txt`, which has a different header:

```
! Checksum: ko/URI7gxmPkkiUHvMTyug
! Title: AdGuard Base filter
! Description: EasyList + AdGuard English filter. This filter is necessary for quality ad blocking.
! Version: 2.0.23.18
! TimeUpdated: 2018-12-10T20:03:35+03:00
! Expires: 2 days (update frequency)
! Homepage: http://adguard.com/filters.html#english
! License: http://creativecommons.org/licenses/by-sa/3.0/
```

I suppose that the AdGuard filter built in uBlock Origin is meant to be used along with Easylist, not on its own. In any case, thank you.

**Comment by Alex-302** [comment]
AdGuard Base filter for uBO does not contain Easylist rules.
view-source:https://filters.adtidy.org/extension/ublock/filters/2_without_easylist.txt

**Comment by ArenaL5** [comment]
Well, that settles that. I added the Easylist rules and now `proper.io` is blocked.

I'll close this issue.
