### ISSUE TITLE
https://my-hit.org

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2674]
**Description**:
При переходе с главной страницы my-hit.org на какой-то фильм срабатывает модуль Антифишинга и появляется сообщение о заблокированной угрозе.
Сам сайт фишинговый не открывается. Срабатывает только уведомление. Можно как-то убрать этот сайт, чтобы не срабатывало оповещение?

Также черный блок сверху от рекламы остался.

Screenshot: 
<details>
![screenshot_45](https://cloud.githubusercontent.com/assets/18548949/17083350/a3b51de0-51a6-11e6-805a-493f840484dd.jpg)
</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Mozilla, Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
my-hit.org###gif_header
||skyad1.ru^$third-party
||funsmi.ru/framework/$third-party

```
