### ISSUE TITLE
http://arseblog.com/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2676]
http://arseblog.com/

![image](https://cloud.githubusercontent.com/assets/15856304/17093801/0c3e84de-5254-11e6-91cf-62894c8bbe69.png)

How it looks without Adguard:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17093811/20c4d7a0-5254-11e6-8973-51c9db0a9bc3.png)
</details>

Filter list:
<details>
Application version: 1.0.8.54
Application lifetime: 2016-07-21 23:28:12 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.3
ID: 533540F9-75FD-4B99-9761-FB6D44E857A1

Locale: en
Region: gb

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.66 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.77 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.6 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.90 Enabled=YES
</details>

logs: 1358973

**Comment by Alex-302** [comment]
Added to Mobile filter
```
arseblog.com#@#.header-ad
```
