### ISSUE TITLE
http://www.adslgate.com/ - ad, ad leftovers

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2677]
The [link](http://www.adslgate.com/dsl/showthread.php?t=2274654)

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17094029/5b299f24-5255-11e6-96a0-61d9daf27334.png)
![image](https://cloud.githubusercontent.com/assets/15856304/17094036/6599f314-5255-11e6-9fc5-021132898335.png)
</details>

State:
<details>
Application version: 1.0.8.54

Application lifetime: 2016-07-18 22:06:21 +0000

Device: iPhone

Platform: iPhone OS

OS: 9.3.2

ID: 57F0A2C6-2374-44A5-AF0B-B7D313D86561

Locale: en

Region: us

Optimazed enabled: YES

Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.0.89.68 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.6.78 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.11.7 Enabled=YES

ID=14 Name="Annoyances filter" Version=1.0.1.94 Enabled=YES

ID=10 Name="Filter unblocking useful ads" Version=1.0.0.90 Enabled=NO

ID=11 Name="Mobile Ads filter" Version=1.0.4.28 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.0.90 Enabled=YES

ID=101 Name="EasyList" Version=1.0.60.79 Enabled=YES

ID=112 Name="Liste AR" Version=1.0.4.27 Enabled=YES

ID=208 Name="Malware Domains" Version=1.0.62.11 Enabled=YES
</details>

logs: 1354928

**Comment by Alex-302** [comment]
The margins on my end are not too big.
Added to English filter
```
adslgate.com##.smallfont > center > a > img
adslgate.com##.smallfont a[href^="http://deals.souq.com/"]
```
