### ISSUE TITLE
[NSFW] vuku.cc - missed pop-ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2678]
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17096806/d0de8870-5263-11e6-9db2-7647a94e991a.png)
</details>
Click anywhere and it opens  http://pornhublite.com/?utm_source=vuku
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17096823/e9c4ebc2-5263-11e6-85cf-bbe41fd55d4f.png)
</details>
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17096847/03a7585e-5264-11e6-8107-9aeaae5ccc75.png)
![image](https://cloud.githubusercontent.com/assets/15856304/17096861/0e00ca1a-5264-11e6-8d9d-e87d09d26ecb.png)
</details>

saved pages, more samples here 677335:

[Порно онлайн видео и секс_ Смотреть порно бесплатно_ Porno video online_ Бесплатное порно на ВУКУ_ТВ_cc--1.mht.zip](https://github.com/AdguardTeam/AdguardFilters/files/381149/_._.Porno.video.online_._._cc--1.mht.zip)

**Comment by Alex-302** [comment]
I can't access to vuku.ru

**Comment by Bohdan-SUP** [comment]
Try vuku.cc

**Comment by Alex-302** [comment]
Nothing(with UA, RU and US VPN)

**Comment by evgeniy-ADG** [comment]
Apparently, it's down since yesterday.

**Comment by evgeniy-ADG** [comment]
@Alex-302 поднялся, кажется, уже

**Comment by Alex-302** [comment]
Проверил, вроде не всплывает ничего.

**Comment by evgeniy-ADG** [comment]
Так и есть, у пользователя у одного всплывает, в сохраненной странице ничего не видно? Если нет, нужно организовать ТВ, потому что там очень сильно ругаются.

**Comment by Alex-302** [comment]
Сохранённая не открывается. Удалённо можно.
