### ISSUE TITLE
Пропускает рекламу на androidpolice

### ISSUE THREAD

**Issue by thunderresistant** [AdguardTeam/AdguardFilters#26782]
Android 9 
Adguard 2.12 лицензионный
Пропускает рекламу на сайте androidpolice.com
В настройках включены: 
*Английский фильтр
*Русский фильтр
*Фильтр мобильной рекламы
*Фильтр счётчиков
*Фильтр виджетов
*Фильтр раздражителей
*Собственного фильтра нет
Режим фильтрации - качественный
В настройках Google предлагать рекламу -  отключено
Где отмечено, сейчас просто серые боксы:
https://a.radikal.ru/a24/1812/84/1efc706b2561.png

При нажатии на них появляется текст:
"Сайт googleads.g.doubleclick.net неожиданно разорвал соединение"
но там появляется полноценная реклама, к примеру:
https://c.radikal.ru/c25/1812/17/4f1958a7f0e9.png

**Comment by TheHasagi** [comment]
@thunderresistant 

Включена ли у Вас HTTPS фильтрация?

Попробуйте отключить QUIC протокол в Chrome - new tab - chrome://flags - QUIC - disabled.

**Comment by thunderresistant** [comment]
Большое спасибо за быстрый и точный совет!
После включения HTTPS фильтрации всё подчистил!)
Её вообще рекомендуется постоянно использовать?
QUIC протокол в Chrome можно и не трогать?

**Comment by Alex-302** [comment]
Без фильтрации HTTPS многие сайты не отфильтровать совсем(если реклама расположена локально), и сайтов с HTTPS с каждым днём всё больше.

QUIC должен блокироваться Адгардом, вроде и без фильтрации HTTPS.

**Comment by thunderresistant** [comment]
Господа, большое спасибо!

**Comment by Alex-302** [comment]
Обращайтесь)
