### ISSUE TITLE
http://wap.ithome.com/ ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2679]
http://wap.ithome.com/html/242988.htm

![image](https://cloud.githubusercontent.com/assets/15856304/17097107/fef3425e-5264-11e6-991f-5fadabbe22c2.png)

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.39 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.71 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.95 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.1.82 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.22 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.85 Enabled=YES
ID=101 Name="EasyList" Version=1.0.60.69 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.62.20 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.61.88 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.61.45 Enabled=NO
ID=219 Name="ChinaList+EasyList" Version=1.0.1.3 Enabled=NO
</details>
logs: 1335999

**Comment by Alex-302** [comment]
I don't understand where is an ad.

**Comment by evgeniy-ADG** [comment]
It's on the very top, with Baidu paw signature, the rest is the article.

**Comment by Alex-302** [comment]
I can't reproduce. It is blocked by rule from Easylist China
```
||pos.baidu.com^
```

**Comment by evgeniy-ADG** [comment]
Informed.
