### ISSUE TITLE
perfect remove avgle ads

### ISSUE THREAD

**Issue by accountforadg** [AdguardTeam/AdguardFilters#26794]
i can complete remove avgle ads in Chrome+uBlock Origin
 with these rules

Easylist  and
avgle.com###player_3x2_close:style(font-size: 250% !important;)
avgle.com##+js(abort-on-property-read.js, ExoLoader.serve)
avgle.com##+js(nowebrtc.js)
avgle.com##+js(set-constant.js, showBlockIf, noopFunc)
||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org|~sainsburys.jobs
||sub.avgle.com/fd/$first-party,script

Could you fix in adg  .

please check

@Alex-302  @BlazDT

**Comment by accountforadg** [comment]
These rules are enough to defeat the resistance mechanism of this website.

**Comment by BlazDT** [comment]
And movie is still playing?  In the past they required a click on the close button which sets a value (which is still set when I check). Else the movie never played.
