### ISSUE TITLE
http://midasbox.net/account - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2680]
http://midasbox.net/account

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17098910/8d84d6f6-526d-11e6-94d2-c85edb6df067.png)
</details>
Basic filters set
Login: Adguard, pass: 99439943

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||zamiko.ru^$third-party
||fast2load.ru^$third-party
```
