### ISSUE TITLE
http://omsimod.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2681]
http://omsimod.ru/

![image](https://cloud.githubusercontent.com/assets/15856304/17100355/8c5ecaf8-5276-11e6-8c04-e4c5709d901b.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-05-08 12:40:08 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.3
ID: F05B5E57-9331-40CE-8F01-A297BB86637B

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.84 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.81 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.8 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.1.98 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.89 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.36.91 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.19 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.30 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.91 Enabled=YES
ID=101 Name="EasyList" Version=1.0.60.90 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.62.40 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.57.49 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.62.40 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.62.28 Enabled=NO
ID=210 Name="Spam404" Version=1.0.1.50 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.58.98 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.59.25 Enabled=YES
ID=214 Name="ABPVN List" Version=1.0.1.59 Enabled=NO

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||aa-ds.ru^$third-party
```
