### ISSUE TITLE
missed ads nnm-club.me

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2682]
Пропущена реклама: http://nnm-club.me/

![2016-07-25 2](https://cloud.githubusercontent.com/assets/16462533/17100324/55a36ed8-5276-11e6-99e6-5f0da11def59.png)

Фильтры:

![2016-07-25_14-47-04](https://cloud.githubusercontent.com/assets/16462533/17100491/64b94504-5277-11e6-961c-0f317bcb50b8.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
/fruits.js$domain=nnm-club.me
```
