### ISSUE TITLE
missed ads mo-taxi.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2683]
**Пропущена реклама на http://mo-taxi.ru/**:

![blob](https://cloud.githubusercontent.com/assets/16462533/17102976/a23df6e2-5284-11e6-8722-f5b96fce3e7e.png)

**Проблема повторилась, фильтры обновлены:**

![2016-07-25_14-47-04](https://cloud.githubusercontent.com/assets/16462533/17102991/b0c7c06c-5284-11e6-9250-875d0b6ac5de.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||mo-taxi.ru/images/banners/
```
