### ISSUE TITLE
missed ads livelib.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2684]
**Пропущена реклама на: https://www.livelib.ru/review/676944**

![2016-07-25_17-52-44](https://cloud.githubusercontent.com/assets/16462533/17105742/237494a8-5291-11e6-930e-f0ab3edcba6c.png)

Фильтры:

![2016-07-25_14-47-04](https://cloud.githubusercontent.com/assets/16462533/17105762/3e02e09a-5291-11e6-870f-f18955f052e8.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||livelib.ru/side/index
||livelib.ru/*?alias=*&callback=

```
