### ISSUE TITLE
http://www.independent.co.uk/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2685]
http://www.independent.co.uk/news/world/europe/detainees-beaten-tortured-and-raped-after-failed-turkey-coup-amnesty-says-a7154091.html?cmpid=facebook-post

![image](https://cloud.githubusercontent.com/assets/15856304/17108357/cf1a7fb6-529b-11e6-86c1-34b312f9e97d.png)

english spyware social media annoyances russian filters

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
independent.co.uk##.adblock-modal
```
