### ISSUE TITLE
outlook.live.com - Unable to remove nag

### ISSUE THREAD

**Issue by tbcam88** [AdguardTeam/AdguardFilters#2686]
Unable to get rid of the nag highlighted below... In the past, AdBlock (for example) has been able to remove it via right click context menu but Adguard's alternative doesn't seem able to block it. Any ideas?

![55381598-51db-11e6-8398-691eb4da4c88](https://cloud.githubusercontent.com/assets/19891537/17110713/4af48632-5296-11e6-99cb-c9776d41917e.png)

(Adguard Chrome Extension - Windows 10 Pro)

**Comment by Alex-302** [comment]
Just enable Annoyances filter in extension settings.

**Comment by tbcam88** [comment]
How is it you do this Alex? I can't see such an option in the extension settings menu...

**Comment by Alex-302** [comment]
Look
http://imagizer.imageshack.com/img923/7290/9M8wrE.png
http://imagizer.imageshack.com/img921/2027/Lze1Wy.png

**Comment by tbcam88** [comment]
I tried enabling the experimental filter Alex but it hasn't made any difference. The nag still can't be removed. :(

**Comment by Alex-302** [comment]
I need remote access. This message is hidden by annoyances filter on my end.

**Comment by Alex-302** [comment]
Sorry, my mistake. You should to enable Annoyances filter.

**Comment by tbcam88** [comment]
This worked! Thanks!

**Comment by tbcam88** [comment]
![untitled](https://user-images.githubusercontent.com/19891537/44928589-2e440a00-ad50-11e8-9bc0-03906b9273aa.png)
Elements in red have reappeared once more... I've tried the annoyances filter but it hasn't worked this time :( any ideas?

**Comment by Alex-302** [comment]
I can't reproduce.
@AdamWr @BlazDT please take a look.

**Comment by BlazDT** [comment]
Self-promo fixed (for beta version too), detection not reproduced.

**Comment by tbcam88** [comment]
Sorry, I don't quite get what you mean by this? I've tried blocking both elements again but they return upon refresh...

**Comment by AdamWr** [comment]
I can reproduce it with AdGuard Extension after few refreshes, I might be wrong, but it looks like a bug.
Reported here - https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1087

**Comment by tbcam88** [comment]
Any progress with this one guys? :)

**Comment by Alex-302** [comment]
@tbcam88 please check with this build(disable existing extension before installing `unpacked` extension):
[chrome-2.10.8.zip](https://github.com/AdguardTeam/AdguardFilters/files/2356593/chrome-2.10.8.zip)

**Comment by tbcam88** [comment]
This works! :)

**Comment by tbcam88** [comment]
It results in the following notification each time you launch the browser, however...

![untitled](https://user-images.githubusercontent.com/19891537/45171851-68535700-b1fb-11e8-876c-c73a6efff8d7.png)

**Comment by tbcam88** [comment]
The developer build seems to have automatically uninstalled itself from Chrome? Is this behaviour expected?

Okay no problem. :)

**Comment by Alex-302** [comment]
Yes, Chrome does not allow to use unpacked extensions, so wait for beta in Chrome Store(the link above).
