### ISSUE TITLE
https://lady.mail.ru/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2687]
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17128695/51e8811a-5317-11e6-8ebd-d2144dbe6d1b.png)

</details>

English filterVersion 1.0.89.86. Updated 24 july 2016 at 17:00.
Spyware filterVersion 1.0.6.81. Updated 22 july 2016 at 19:00.
Social media filterVersion 1.0.11.8. Updated 22 july 2016 at 17:24.
Annoyances filterVersion 1.0.1.98. Updated 22 july 2016 at 19:02.
Russian filterVersion 1.0.36.91. Updated 24 july 2016 at 20:00.
Experimental filterVersion 1.0.26.19. Updated 24 july 2016 at 01:30.
Mobile Ads filterVersion 1.0.4.30. Updated 22 july 2016 at 22:01.

Extension, Mac, Chrome 52

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
/mimic/v1/ws/*$domain=mail.ru
```
Добавил в фильтр раздражителей
```
lady.mail.ru##.tooltip__box
```
