### ISSUE TITLE
kma.biz

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2688]
**Description**: https://kma.biz/advertisers

**Current behaviour**: Page content is blocked out

Screenshot Adguard on: <details>
![on](https://cloud.githubusercontent.com/assets/14153331/17128967/d80dd302-5318-11e6-950a-e94457159695.png)
</details>

Screenshot Adguard off:
<details>
![off](https://cloud.githubusercontent.com/assets/14153331/17128975/e51e121e-5318-11e6-8693-b836fd3bb67b.png)
</details>

**Adguard version**: Mac 1.3.0

**Filters list**:
![screen shot 2016-07-26 at 10 09 40 am](https://cloud.githubusercontent.com/assets/14153331/17129004/19e058ea-5319-11e6-995f-694d1b8303e2.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
kma.biz#@#.adv
```
