### ISSUE TITLE
pfm.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#26890]
@AdamWr 
![scr-1544687932-001](https://user-images.githubusercontent.com/9846948/49923966-5564b880-feb5-11e8-9802-a66a23cbd6b5.png)

**Site Sample** | 
-----------------------------|
https://www.pfm.pl/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Chrome Stable x64
AdGuard version:                       | **6.4.1840.4955**
Stealth mode:					       | enabled

| Filters enabled |
|-----------------|
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| CoinBlockerLists
| EasyList Polish 
| Fanboy's Annoyances
| Fanboy's Enhanced Tracking List 
| Fanboy's Social Blocking List 
| I don't care about cookies
| KAD - fraud/scam 
| Malware Domains
| NoCoin Filter List 
| Peter Lowe's List
| Polish Annoyances
| Polish Main
| Polish Social
<details><summary><b>Screenshot:</b></summary>

![scr-1544687879-001](https://user-images.githubusercontent.com/9846948/49923932-3ebe6180-feb5-11e8-84ea-5805a8f79fea.png)

</details><br/>

**Comment by AdamWr** [comment]
Added:
```
pfm.pl#%#document.cookie = 'NeucaCookieConsent={"necessary":false,"preferences":false,"statistics":false,"marketing":false,"id":""}';
```
