### ISSUE TITLE
www.mobiflip.de - ads, anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2689]
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17130030/243e4f44-531f-11e6-9960-8c7b32855c4a.png)
![image](https://cloud.githubusercontent.com/assets/15856304/17130035/2b0c58c0-531f-11e6-846f-f342955d3f85.png)
</details>

"enabledFilterIds" : [ 2, 3, 4, 14, 6, 11 ], SSL

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
@@||mobiflip.de/wp-content/themes/mobiTheme*/js/ads.js
```
Added to German filter
```
mobiflip.de##div[class^="asadiviframe"]
mobiflip.de##.asadivmain
```
Added to Social filter
```
mobiflip.de##.social-sharing-bot
```
