### ISSUE TITLE
http://filmihemenizle.com/ -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2690]
**Site**: http://filmihemenizle.com/arsivler/the-hunger-games-mockingjay-part-2-2015-altyazili

**Screenshot**: 
![screenshot_10](https://cloud.githubusercontent.com/assets/19608513/17131786/1d7f6e52-5330-11e6-9f56-5898923ed9e2.png)

Note: Annoyance in the center will be shown after loading page
Share button is at the bottom of video player

**Adguard version**: 6.1.242.1198 beta

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Social filter
```
filmihemenizle.com##.post-sharrre
```
Added to Annoyances filter
```
||filmihemenizle.com/wp-content/plugins/popover/js/public.min.js
```
