### ISSUE TITLE
http://www.vipfullhdfilmizle.org/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2691]
**Site**: http://www.vipfullhdfilmizle.org/korku-klinigi-turkce-dublaj-izle/

**Screenshot**: 

Can you add this rule -###alt as a generic rule? Now I saw in this site that you have added a few rules
For example:
filmionlineizle.net###alt
hdfilmcenneti.org###alt
hdfilmkanali.org###alt
fullhdfilmadresi.com###alt
birhdfilm.org###alt and etc.
https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/sections/remains.txt

![screenshot_11](https://cloud.githubusercontent.com/assets/19608513/17132120/6e51da6c-5331-11e6-8f1a-43755fdc1638.png)

**Adguard version**: 6.1.242.1198 beta

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
No, ###alt can break some sites
Added to Annoyances filter
```
vipfullhdfilmizle.org###alt
```
