### ISSUE TITLE
http://www.populerfilmler.net/ -background ad

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2693]
**Site**: http://www.populerfilmler.net/

**Screenshot**: The link is this in the background..

![screenshot_12](https://cloud.githubusercontent.com/assets/19608513/17132298/28a7eb22-5332-11e6-9baa-a849970546c2.png)

**Adguard version**: 6.1.242.1198 beta

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
populerfilmler.net#%#AG_onLoad(function() { window.myatu_bgm = function() {}; }); 
```
