### ISSUE TITLE
http://www.hdfilmcehennemi.com/ -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2694]
**Site**: http://www.hdfilmcehennemi.com/keanu-izle/

**Screenshot**: 
![screenshot_13](https://cloud.githubusercontent.com/assets/19608513/17132840/939bab9c-5334-11e6-80cb-9394e218a99d.png)

**Adguard version**: 6.1.242.1198 beta

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
hdfilmcehennemi.com###alt
```
Added to Turkish filter
```
||hdfilmizle.pw/cdn1/play.php?link=
||yemekcehennemi.com^$domain=hdfilmizle.pw
```
