### ISSUE TITLE
http://www.baglanfilmiizle.com/ -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2695]
**Site**: http://www.baglanfilmiizle.com/

**Screenshot**: 
![screenshot_14](https://cloud.githubusercontent.com/assets/19608513/17133046/699bc2c2-5335-11e6-8ceb-eb935f749cbf.png)

**Adguard version**: 6.1.242.1198 beta

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
baglanfilmiizle.com##div[id^="itro_"][style]
baglanfilmiizle.com##a[rel="nofollow"][class="external"] > img

```

**Comment by thislife81** [comment]
PLZ REMOVE THIS

![baglanfilmizle com hd film izle film seyret sinema izle](https://cloud.githubusercontent.com/assets/19608513/18435687/cd83df22-7905-11e6-9b51-7ef517cdec8c.png)

**Comment by Alex-302** [comment]
Added to Turkish filter
```
baglanfilmiizle.com##embed[src^="http://www.trbetmedia.com/reklam/"]

```
