### ISSUE TITLE
bigbasket.com | Mobile | Annoyance | App promotion

### ISSUE THREAD

**Issue by in4u** [AdguardTeam/AdguardFilters#26969]
***Description***

Website: `bigbasket.com`

* **Current behaviour**: 

    Banner at the top of page on mobile, promoting app download.

* **Expected behaviour**: 

    No app promotion annoyance. The banner is `bigbasket.com##.flex-android.flex-container-smart-banner`. However on blocking that element, the left side hamburger menu also disappears. The only suitable option I can think of is to block `bigbasket.com##.android-use-btn` and `bigbasket.com##.flex-android.flex-container-smart-banner > .flex-container-smart-banner` separately. But that still leaves an empty area.

***System configuration***

Information                            | Value
---                                    | ---
Operating system:                      | Android 8.1
Browser:                               | Firefox for Android 64.0.1
Filters enabled:                       | Annoyances Filter

**Comment by Alex-302** [comment]
fixed

**Comment by Alex-302** [comment]
Thanks, fixed.
