### ISSUE TITLE
http://expertvaz.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2696]
http://expertvaz.ru/2114/zerkala-vyibor-harakteristiki.html

On Mac with iOS 9.3 user agent:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17133569/4da8604e-532f-11e6-95f9-b24630f1d307.png)
</details>

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.94 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.82 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.9 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.37 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.93 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||onelead.ru^$third-party
||s4block.com^$third-party
```
в мобильный
```
||expertvaz.ru/wp-content/plugins/helper/inc/jquery.mobileInterestial
```
