### ISSUE TITLE
com.lucasarts.starts_goo  crashes after loading screen

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#2697]
https://play.google.com/store/apps/details?id=com.lucasarts.starts_goo

the reason is some rule in **Mobile ads filter**

**Comment by ameshkov** [comment]
Maybe it's time to use new $app modifier?
`@@||example.org^$app=com.lucasarts.starts_goo`

**Comment by vozersky** [comment]
just tried `@@||example.org^$app=com.lucasarts.starts_goo`, didn't  help

**Comment by vozersky** [comment]
@ameshkov  jeez i didn't notice example.org in that rule above :)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||connect.tapjoy.com/connect?$app=com.lucasarts.starts_goo
```
Please check it

**Comment by vozersky** [comment]
@Alex-302 it works

**Comment by ameshkov** [comment]
Please note that this type of rules work in v2.7 only

**Comment by Alex-302** [comment]
Ok. 
But url doesn't contains the app name. 
Temporary added:
```
@@||connect.tapjoy.com/connect?*&advertising_id=
```
Response:
```
<?xml version="1.0" encoding="UTF-8"?>
<TapjoyConnectReturnObject>
  <Success>true</Success>
  <ConnectReturnObject>
    <PrimaryColor>928844</PrimaryColor>
  </ConnectReturnObject>
</TapjoyConnectReturnObject>
```

**Comment by ameshkov** [comment]
Why, you can leave the rule with $app modifier. I am just clarifying when it will start working.
