### ISSUE TITLE
putlocker.kz [Fake Links] [Pop-Up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#26989]
**Site**: https://putlocker.kz/movie-2018/hunter-killer-putlocker.85392?utm_campaign=free-traffic&utm_source=solutions-softonic-com&utm_medium=referral

**Issue**: Please remove the fake links as shown in the screenshot. Also please remove the pop-up when clicking on Play button.

**Screenshot**: http://prntscr.com/lvb4ky

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 71.0.3578.98 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by AdamWr** [comment]
Fixed fake links, but I couldn't reproduce pop-ups.
