### ISSUE TITLE
a2zapk.com [Adblock Buttons]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#26986]
**Site**: https://a2zapk.com/347985-mx-player-pro-1-10-29-patched-ac3-dts-ultra-mod-lite-a2z.html

**Issue**: Visit the above page and click on the "Go to Download Page" button (http://prntscr.com/lvarf2). On the next page, you will see adblock button (http://prntscr.com/lvaru3). Moreover, the site tries to navigate/load a domain in the background (mobileoffers-cb-download.com) which is also seen in the screenshot. Please remove that too.

**Screenshot**: See above

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 71.0.3578.98 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by AdamWr** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/c51d8e50bd04225b62b0d1d0ee7af55cad3d916f
