### ISSUE TITLE
gomovieshd.be [Fake Links] [Pop-Up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#26983]
**Site**: https://gomovieshd.be/movie-2018/hunter-killer-online-free

**Issue**: Please remove the fake links as shown in the screenshot. Also a pop-up is seen when clicking on the play button. Can you also finally remove the text shown here (http://prntscr.com/lvamz1).

**Screenshot**: http://prntscr.com/lvam60

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 71.0.3578.98 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by AdamWr** [comment]
>Can you also finally remove the text shown here (http://prntscr.com/lvamz1).

I'm not sure if we should block it, but you can add this rule to user filter:
`gomovieshd.be##div[align="center"] > #helpus`
