### ISSUE TITLE
http://m.bild.de/ - missed ad/placeholder

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2698]
![image](https://cloud.githubusercontent.com/assets/15856304/17165676/c1ccdf9e-53da-11e6-8c9d-75f0259a8531.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-05-27 06:44:59 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.3
ID: DD4B9153-1F8A-40F3-9168-4CF75D734FB9

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.73 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.81 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.8 Enabled=YES
ID=6 Name="German filter" Version=1.0.26.46 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.30 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.91 Enabled=YES
</details>

**Comment by evgeniy-ADG** [comment]
When I try to reproduce it, I see this:
![image](https://cloud.githubusercontent.com/assets/15856304/17165750/565970d2-53db-11e6-986a-dac6249f7431.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
Try to disable mobile filter. There are few wide exclusions.

**Comment by evgeniy-ADG** [comment]
Now it shows ads

<detail>
![20160802_105237000_ios](https://cloud.githubusercontent.com/assets/15856304/17326233/a4d2eac2-58b8-11e6-8c3d-b3f256290642.png)

**Comment by Alex-302** [comment]
My mistake. Try to disable Safari filter. Mobile filter must be enabled.

**Comment by Alex-302** [comment]
@evgeniy-ADG

**Comment by evgeniy-ADG** [comment]
@Alex-302 that's helped.

**Comment by Alex-302** [comment]
ok, removed from Safari filter:
```
! bild.de [Adblock detection]
@@||bild.de^$elemhide
@@||sascdn.com/diff/*/pages/bild.js$domain=bild.de
@@||smartadserver.com/diff/*/smartad.js$domain=bild.de
@@||smartadserver.com/diff/*/divscripte/$script,domain=bild.de
@@||smartadserver.com/diff/*/partners/$script,domain=bild.de
!@@||sascdn.com^$domain=bild.de,script
! https://github.com/AdguardTeam/AdguardFilters/issues/2604
@@|http://$domain=bild.de,script,third-party
@@||bild.de^$generichide
```
