### ISSUE TITLE
https://my.mail.ru/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2700]
https://my.mail.ru/

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17166699/42cc51d2-53e1-11e6-8793-ab02ce09c989.png)
![image](https://cloud.githubusercontent.com/assets/15856304/17166723/5d195bac-53e1-11e6-8d3b-f76ef3aee64b.png)
</details>

Version 52.0.2743.82 (64-bit) 
English filterVersion 1.0.90.2. Updated 27 july 2016 at 08:00.
Spyware filterVersion 1.0.6.84. Updated 26 july 2016 at 23:00.
Social media filterVersion 1.0.11.11. Updated 26 july 2016 at 16:38.
Annoyances filterVersion 1.0.2.10. Updated 26 july 2016 at 20:02.
Russian filterVersion 1.0.37.4. Updated 26 july 2016 at 23:00.
Experimental filterVersion 1.0.26.19. Updated 24 july 2016 at 01:30.
Mobile Ads filterVersion 1.0.4.35. Updated 26 july 2016 at 22:02.

**Comment by Alex-302** [comment]
Подправил.
