### ISSUE TITLE
http://ca.dakine.com - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2701]
http://ca.dakine.com/p/backpacks-and-gear/luggage/travel-bags/split-roller-110l-bag-17w

**Current behaviour**: Useful elements are being falsely blocked

Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17166931/afec02de-53e2-11e6-9ba7-1749176682b5.png)

</details>

**Expected behaviour**: 
Screenshot:

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17166954/d0e1debe-53e2-11e6-9f51-16df031dd6ab.png)

</details>

**Adguard version**: any, tested and reproduced with beta extension on the latest chrome

**Filters list**:
English filterVersion 1.0.90.2. Updated 27 july 2016 at 08:00.
Spyware filterVersion 1.0.6.84. Updated 26 july 2016 at 23:00.
Social media filterVersion 1.0.11.11. Updated 26 july 2016 at 16:38.
Annoyances filterVersion 1.0.2.10. Updated 26 july 2016 at 20:02.
Russian filterVersion 1.0.37.4. Updated 26 july 2016 at 23:00.
Experimental filterVersion 1.0.26.19. Updated 24 july 2016 at 01:30.
Mobile Ads filterVersion 1.0.4.35. Updated 26 july 2016 at 22:02.

**Operating system**: any

**Browser**: all?

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e6a57e94a205029a090f0f34b13fce50d5790603

**Comment by Alex-302** [comment]
Thanks.
