### ISSUE TITLE
http://wyborcza.pl/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2702]
![image](https://cloud.githubusercontent.com/assets/15856304/17167539/552705fc-53e6-11e6-8737-16204a106cec.png)

http://wyborcza.pl/0,0.html?disableRedirects=true

English filterVersion 1.0.90.2. Updated 27 july 2016 at 08:00.
Spyware filterVersion 1.0.6.84. Updated 26 july 2016 at 23:00.
Social media filterVersion 1.0.11.11. Updated 26 july 2016 at 16:38.
Annoyances filterVersion 1.0.2.10. Updated 26 july 2016 at 20:02.
Russian filterVersion 1.0.37.4. Updated 26 july 2016 at 23:00.
Experimental filterVersion 1.0.26.19. Updated 24 july 2016 at 01:30.
Mobile Ads filterVersion 1.0.4.35. Updated 26 july 2016 at 22:02.

Extension beta, the latest chrome

**Comment by Alex-302** [comment]
wyborcza.pl##.mod.mod_ddbox.is-visible
