### ISSUE TITLE
http://wyborcza.pl - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2703]
http://wyborcza.pl/0,0.html?disableRedirects=true

> Adverts from a.ib.gazeta.pl are effectively disrupting the wyborcza.pl
> site (Adguard doesn't filter them, on Android and on PC)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17167729/46b063aa-53e7-11e6-9a6f-8c8c5f07ef1f.png)
![image](https://cloud.githubusercontent.com/assets/15856304/17167782/928b6a4a-53e7-11e6-9095-217e5029c5ff.png)

<details>

[ 2, 3, 4, 14, 7, 11, 211, 216, 217 ]
**1262453**

**Comment by Alex-302** [comment]
can't reproduce it with only English filter.
