### ISSUE TITLE
http://fishki.net/- missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2704]
http://fishki.net/2024223-prikolnye-i-smeshnye-gifki.html

> Если перейти на страницу и пролистывать, то ничего не происходит. Если перейти на страницу и просматривать gif, запуская их по очереди, то gif как бы раздвигаются и между ними появляется данное видео.

![image](https://cloud.githubusercontent.com/assets/15856304/17171363/1416cd78-53f9-11e6-878a-980a79fb7c95.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2015-11-30 12:57:48 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.3
ID: BA55B08B-B14C-4387-B159-185B1F6115FE

Locale: ru
Region: ru

Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.86 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.81 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.8 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.90 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.36.91 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.91 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.62.41 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.54.60 Enabled=NO

**Comment by evgeniy-ADG** [comment]
У меня не повторяется, может, ип российский нужен.

**Comment by Alex-302** [comment]
Что-то и с vpn не повторяется, даже запросов videonow нет.
