### ISSUE TITLE
Site with ads  http://samlab.ws/

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#2705]
Big banner with ad. Blocking element doesn't help.
![default](https://cloud.githubusercontent.com/assets/20476168/17177869/e97bb0ba-541b-11e6-9ee7-504e4c220796.PNG)

**Comment by Alex-302** [comment]
It was fixed few minutes ago.

**Comment by Alex-302** [comment]
You can just check for updates.

**Comment by vgavrish** [comment]
http://samlab.ws/
Можно убрать данный блок?
ВИН.АНДРОИД
ф: 1,2,3,4,11,14
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21079022/dbe53d86-bf8c-11e6-91a2-655610c2bea2.png)

**Comment by Alex-302** [comment]
Да. В раздражителях заблокировал.
