### ISSUE TITLE
Missed Ads yandex direct

### ISSUE THREAD

**Issue by Hawkrus** [AdguardTeam/AdguardFilters#2706]
Снова появился яндекс директ:
https://yandex.ru/maps/213/moscow/?ll=37.620393%2C55.753960&z=10
![yandex_3](https://cloud.githubusercontent.com/assets/19652388/17181380/9d288f00-5428-11e6-9c18-fa99121f05f5.PNG)
http://www.rbc.ru/finances/27/07/2016/5798c7949a79471047da3df0
![yandex_4](https://cloud.githubusercontent.com/assets/19652388/17181603/665cb126-5429-11e6-928a-10bbff78db7e.PNG)

**Adguard version**: 6.0.226.1108
Русский фильтр

**Operating system**: Windows 7

**Browser**: Chrome

**Comment by Alex-302** [comment]
Уже исправлено

**Comment by Hawkrus** [comment]
@Alex-302  Давно исправлено? У меня до сих пор вылазит директ, фильтры самые свежие.

**Comment by Alex-302** [comment]
За пол часа до создания вашей заявки. Какая версия фильтров?

**Comment by Hawkrus** [comment]
Только что проверил - на rbc.ru яндекс директ при прокрутке новостей, как в скриншоте.
На картах яндекс директ исчез.
Версия русского фильтра 1.0.37.13

**Comment by Alex-302** [comment]
На rbc чисто.

**Comment by Hawkrus** [comment]
Подтверждаю.
