### ISSUE TITLE
http://t3n.de/ - false blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2707]
http://t3n.de/news/google-adwords-textanzeigen-729653/

![image](https://cloud.githubusercontent.com/assets/15856304/17202064/7ae40646-549f-11e6-850d-6c424f9b01b4.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-07-22 22:31:21 +0000

Device: iPad
Platform: iPhone OS
OS: 10.0
ID: 303D3C13-A240-4F68-BD60-05A16B2A54C8

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.86 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.81 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.8 Enabled=YES
ID=6 Name="German filter" Version=1.0.26.49 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.91 Enabled=YES
</details>

You should try more then 1 time to reproduce it

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@/google-adwords$domain=t3n.de,~third-party
```
please check it

**Comment by evgeniy-ADG** [comment]
It's working.
