### ISSUE TITLE
https://home.bluesnap.com/ - annoyance 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2708]
![image](https://cloud.githubusercontent.com/assets/15856304/17202404/bbfa7bae-54a1-11e6-8331-348dc6c6aeb7.png)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17202429/d4834ff2-54a1-11e6-8bba-1b69dc0ab77e.png)

**Comment by Alex-302** [comment]
Добавил в фильтр раздражителей
```
bluesnap.com##.optin-monster-saas-overlay

```
