### ISSUE TITLE
fr.meteo app - ad leftovers

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2709]
https://play.google.com/store/apps/details?id=fr.meteo

At first it looks fine
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17203238/da1fc3aa-54a6-11e6-891d-4eee9c7d2742.png)
</details>

And then a placeholder pops up and stays
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17203232/d167253c-54a6-11e6-96ba-9bed35d8de72.png)
</details>

SSL on, HQ mode, Android 4.4.4, Eng, Spyware, social media, Annoyances, Russian, German, Mobile ads

**Comment by Alex-302** [comment]
I can't repdoduce it.
Try this
```
||dispatcher.mng-ads.com/v*/$replace=/("placements"\:)[\s\S][[\s\S]*]/\$1[]

```
if no expected result add it
```
||mobile.mng-ads.com^$empty
```

**Comment by Alex-302** [comment]
We can't remove it.
Added to Mobile ads filter
```
||dispatcher.mng-ads.com^$empty
||mobile.mng-ads.com^$empty
```
