### ISSUE TITLE
ivi.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#271]
В расширении firefox реклама перед просмотром видео.

**Comment by Alex-302** [comment]
в русском фильтре встретил такое:
```
! Разрешаем рекламу на ivi, иначе у них плеер ломается
@@||api.digitalaccess.ru$elemhide,urlblock,jsinject,content
@@||vcp.ivi.ru$elemhide,urlblock,jsinject,content
@@||license.ivi.ru$elemhide,urlblock,jsinject,content
```
наверное не победить.

**Comment by Alex-302** [comment]
Реклама повержена.

**Comment by vozersky** [comment]
Видеореклама перед просмотром, Chrome extension 2.3.7, возможно пофиксить?

**Comment by Alex-302** [comment]
не повторяется. Нужна ссылка

**Comment by vozersky** [comment]
http://www.ivi.ru/watch/masha_i_medved/43853

 2.3.8

English filterVersion 1.0.86.21. Updated 10 june 2016 at 00:00.
Spyware filterVersion 1.0.6.21. Updated 9 june 2016 at 15:00.
Social media filterVersion 1.0.10.19. Updated 9 june 2016 at 00:00.
Annoyances filterVersion 1.0.0.39. Updated 10 june 2016 at 00:02.
Russian filterVersion 1.0.34.98. Updated 10 june 2016 at 12:00.
Experimental filterVersion 1.0.25.65. Updated 10 june 2016 at 01:00.

**Comment by vgavrish** [comment]
Реклама у пользователя при просмотре в Chrome, Edge
http://www.ivi.ru/watch/144874
Фильтры - 1, 2, 14
Реклама появляется вначале ролика
http://prntscr.com/br0tqq

У меня не повторяется

**Comment by Alex-302** [comment]
Да помню. Руки никак не дойдут.
Передай на проверку
```
||api.ivi.ru/light/?r=$replace=/\"third_party_adv_xml_link\": .*?\,/"third_party_adv_xml_link": null\,/
```

**Comment by vgavrish** [comment]
написала

**Comment by Serzh-SUP** [comment]
@Alex-302
На проверку передали, сам также проверил. При работающем правиле, темный плеер, секунд 30-40 нужно подождать, пока включится фильм.

**Comment by Alex-302** [comment]
@Serzh-SUP 
т.е. рекламы нет, но нужно ждать?
У тебя без правила есть реклама?

**Comment by vgavrish** [comment]
"Рекламы нет. Но около минуты приходится ждать - видно просто черный экран."
http://prntscr.com/bv7z7g

**Comment by Alex-302** [comment]
Никак не удаётся повторить, даже с VPN, удалённый доступ нужен.

**Comment by vgavrish** [comment]
отписала

**Comment by vgavrish** [comment]
Рекламы больше нет.
Повторить я тоже не смогу. Но несколько дней она была. Спасибо.

**Comment by zebrum** [comment]
@Alex-302 
в хроме со стандартными фильтрами рекламе перед просмотром видео

**Comment by Alex-302** [comment]
@zebrum проверь снова. Вчера добавлял исправление. Но только для прог.
Проверял здесь
http://www.ivi.ru/watch/kremen_osvobozhdenie_kremen_2/107337

**Comment by zebrum** [comment]
@Alex-302 
в расширение можно добавить? :) 
а так работает!

**Comment by Alex-302** [comment]
Не, расширение так не умеет.
