### ISSUE TITLE
https://ru.giveawayoftheday.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2710]
https://ru.giveawayoftheday.com/

![image](https://cloud.githubusercontent.com/assets/15856304/17205349/4e4d6e92-54b3-11e6-8454-7ae52b24858d.png)

<details>
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:101 Name: EasyList Url: https://easylist.github.io/easylist/easylist.txt
FilterId:115 Name: RU AdList Url: https://easylist-downloads.adblockplus.org/
Filtering Mode: Driver
Driver Type: Wfp
Ads Blocked: 9407, Trackers Blocked: 6549
Filtering Mode: Driver
Application lifetime: 1.16:02:01.8346878
HTTPS filtering enabled: True

**Comment by Alex-302** [comment]
Added to English filter
```
giveawayoftheday.com##.ads_wrap
||giveawayoftheday.com/web/bannerinf.js

```
