### ISSUE TITLE
vitoriadaconquistanoticias.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#27118]
`http://www.vitoriadaconquistanoticias.com.br/v2/2018/12/17/tristeza-jovem-pisa-em-fio-desencapado-e-morre-enquanto-lavava-roupas-bahia/`

----

Several static banners before the news article. This blocks most of them altogether:

`||imgur.com/*.gif$image,domain=vitoriadaconquistanoticias.com.br`

For the remaining .jpg ads (we can't block Imgur completely because they also use it for the pictures in articles):

`vitoriadaconquistanoticias.com.br##a[target="_blank"]:has(img)`

----

Unblocked ad network (`premiumads.com.br`) connections.

-----

Also, connections are made to the `consensu.org` domain to load GDPR scripts. 

If you don't want to block it completely for European sites, at least please block it for connections from `.com.br` domains, since there's no law in Brazil requiring that.

AdGuard spa,por list
uBlock Origin

**Comment by adranger** [comment]
The banner below the headline wasn't blocked. You can safely block all gifs from Imgur since they only use this format for ads.

Also please read the rest of my post. `premiumads.com.br` and `consensu.org` connections are unblocked.

![vitoria](https://user-images.githubusercontent.com/35470489/50297839-dea35e80-0464-11e9-852d-b4ccdac28632.png)

**Comment by Alex-302** [comment]
consensu.org is blocked by annoyances filter.

> ||imgur.com/*.gif$image,domain=vitoriadaconquistanoticias.com.br

added

**Comment by adranger** [comment]
Thanks.
