### ISSUE TITLE
http://www.cluber.com.ua/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2711]
http://www.cluber.com.ua/lifestyle/rabota-lifestyle/2016/04/9-postupkov-rukovoditeley-iz-za-kotoryih-uhodyat-luchshye-sotrudniki/

![image](https://cloud.githubusercontent.com/assets/15856304/17210061/241da996-54c9-11e6-9d82-9f070ef654f7.png)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17210089/52ec2c34-54c9-11e6-897a-be7a0bb09d14.png)

**Comment by Alex-302** [comment]
Добавил в фильтр соц. сетей
```
cluber.com.ua##.popup-bg
```
