### ISSUE TITLE
http://piratbit.ru/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2713]
**Description**: Реклама
http://piratbit.ru/topic/215986/

Screenshot:
<details>
![screenshot_46](https://cloud.githubusercontent.com/assets/18548949/17240859/980679b6-5576-11e6-8f43-974e92ae8efe.jpg)
</details>

**Filters list**: 1,2,3,4,14

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
pb.wtf,piratbit.org,piratbit.ru#$#div[class][style="width: 24.1%;"] { position: absolute!important; left: -2000px!important; }

```
