### ISSUE TITLE
http://www.rbc.ru/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2714]
http://www.rbc.ru/politics/28/07/2016/5799f4fd9a7947a107638fdf?from=main

![image](https://cloud.githubusercontent.com/assets/15856304/17241360/d751d90a-5579-11e6-833e-2c937fa25eb8.png)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17241364/dec9122a-5579-11e6-9ca6-01fdca120940.png)

**Comment by Alex-302** [comment]
Добавил в фильтр раздражителей
```
rbc.ru#%#document.cookie = "pushAllow = close";

```
