### ISSUE TITLE
http://www.jabong.com/ - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2715]
http://www.jabong.com/women/

![image](https://cloud.githubusercontent.com/assets/15856304/17243674/b4ee0ade-5586-11e6-8a2a-7b5512aa08cf.png)

<details>
Os version: Microsoft Windows NT 10.0.10240.0
Dot .net version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: 41688fcf8da64973b791ccf484bcfd67
Language: en
AppVersion: 6.0.226.1108
Main settings: 
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:11 Name: Mobile Ads filter Url: http://adguard.com/ru/filter-rules.html?id=11
FilterId:101 Name: EasyList Url: https://easylist.github.io/easylist/easylist.txt
FilterId:118 Name: EasyPrivacy Url: https://easylist-downloads.adblockplus.org/easyprivacy.txt
FilterId:122 Name: Fanboy's Annoyances Url: https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
FilterId:207 Name: Adblock Warning Removal List Url: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
FilterId:211 Name: Anti-Adblock Killer | Reek Url: https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
FilterId:215 Name: Fanboy's Enhanced Tracking List Url: https://secure.fanboy.co.nz/enhancedstats.txt
FilterId:0 Name: User filter Url: no_url
FilterId:14 Name: Annoyances filter Url: http://adguard.com/ru/filter-rules.html?id=14
Filtering Mode: Driver
Driver Type: Tdi
Ads Blocked: 25250, Trackers Blocked: 17999
Filtering Mode: Driver
Application lifetime: 5.15:21:22.5156740
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": true,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false
}

**Comment by Alex-302** [comment]
fixed
