### ISSUE TITLE
naurunappula.com - missed ad

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#2717]
Reproduced on Mac OS X, Chrome, Filters: english, spyware, social media, russian, german, dutch, experimental, safari.

In order to reproduce click [here](naurunappula.com/1202860/ristiinpukeutujakisa-bmw-vs-moottoripyora.gif).
<details>
![capture](https://cloud.githubusercontent.com/assets/20476168/17268752/e5a0fd06-563c-11e6-9698-5b5fbebeb520.JPG)

and 

![image](https://cloud.githubusercontent.com/assets/15856304/17808874/51072e7e-661b-11e6-85dc-bec4ad03354b.png)

**Comment by Alex-302** [comment]
Please edit the issue according to template.

**Comment by Alex-302** [comment]
Added to English filter
```
||kuvake.net^$domain=naurunappula.com
||gooby.naurunappula.com/images/armadillo
naurunappula.com##a[href^="http://bit.ly/"] > video

```
