### ISSUE TITLE
[Filters] Problem with loading script

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardFilters#27181]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
While visiting [website](https://tovarniygid.ru/rasprodazha-11-11-v-geekbuying/) script cannot be loaded:
<script>
window.ao_subid = "MoneylinkTG";
</script>
<script src="//js.mamydirect.com/js/?h=0BBAqana"
type="text/javascript" async></script>

#### Customer ID: 1774196 (video available)

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***
Windows 7/10
**Filters:**
Base, RU

Please check if anything we can do.

**Comment by Alex-302** [comment]
added
`@@||js.mamydirect.com^$domain=tovarniygid.ru`
