### ISSUE TITLE
http://www.sinemadafilmizlee.com/ -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2718]
**Site**: http://www.sinemadafilmizlee.com/warcraft-iki-dunyanin-ilk-karsilasmasi-2016-turkce-dublaj-sinema-film-izle.html

**Screenshot**:  http://s31.postimg.org/wfbn42g0r/screenshot_19.png

**Adguard version**: 2.4.3

**Operating system**: Windows 10

**Browser**: Google Chrome

**Filter list**: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
sinemadafilmizlee.com###share-cerceve
```

**Comment by thislife81** [comment]
Not removed, Loading.. is shown again

**Comment by Alex-302** [comment]
Removed:
```
sinemadafilmizlee.com###share-cerceve
```
Added to Turkish filter
```
sinemadafilmizlee.com##.SC_TBlock
```
For user filter:
```
sinemadafilmizlee.com##.icerik > p
```
