### ISSUE TITLE
http://www.fullhd720pizle.com/ -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2719]
**Site**: http://www.fullhd720pizle.com/zor-biraderler-2-izle.html

**Screenshot**: http://s31.postimg.org/xpe1wuz6j/screenshot_20.png

**Adguard version**: 2.4.3

**Operating system**: Windows 10

**Browser**: Google Chrome

**Filter list**: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Please add filters list to your recently added issues

**Comment by thislife81** [comment]
Added

**Comment by Alex-302** [comment]
Added to Social filter
```
fullhd720pizle.com##.share-cerceve
```

**Comment by thislife81** [comment]
Can you remove above white space?

**Comment by Alex-302** [comment]
I don't see it.
