### ISSUE TITLE
http://www.sinefan.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2720]
**Site**: http://www.sinefan.com/bone-tomahawk-izle.html

**Screenshot**: 
![indir](https://cloud.githubusercontent.com/assets/19608513/17269431/eaefc0f0-5658-11e6-9f88-b456d8c9c9b8.png)

**Adguard version**: 2.4.3

**Operating system**: Windows 10

**Browser**: Google Chrome

**Filter list**: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by thislife81** [comment]
They already removed this ad. You can close this topic for now. If they again put the ad into there, I;m going to report here.
