### ISSUE TITLE
http://www.hdsonbolumizle.com/ -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2721]
**Site**: http://www.hdsonbolumizle.com/the-originals-4-sezon-1-bolum-izle.html

**Screenshot**: http://s31.postimg.org/qsogy2s9n/screenshot_22.png

**Adguard version**: 2.4.1

**Operating system**: Windows 10

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdsonbolumizle.com##.SC_TBlock
```

**Comment by thislife81** [comment]
Please remove all of these..

![000](https://cloud.githubusercontent.com/assets/19608513/18032803/3162aa3a-6d23-11e6-8b79-d8af8c3b2681.png)

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdsonbolumizle.net#$##single .videoBox .iframe { display: block!important; }
hdsonbolumizle.net##.ad
hdsonbolumizle.net#$#body { background: #000000!important; } 

```
