### ISSUE TITLE
http://www.filmrax.com/ -background ad

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2722]
**Site**: http://www.filmrax.com/

**Screenshot**: 
When I click on the background, it redirects to another site

**Adguard version**: 2.4.3

**Operating system**: Windows 10

**Browser**: Google Chrome

**Filter list**: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
filmrax.com#%#Object.defineProperty(window, 'undercipop', {get: function() { return function() {}; } });
```
