### ISSUE TITLE
http://www.inndirmedenfilmizle.com/ -ad before video

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2723]
**Site**: http://www.inndirmedenfilmizle.com/lamb-2015-turkce-altyazili-izle.html

**Screenshot**: http://s31.postimg.org/m82aj58kb/screenshot_23.png

**Adguard version**: 2.4.3

**Operating system**: Windows 10

**Browser**: Google Chrome

**Filter list**: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
||inndirmedenfilmizle.com/_pois-reklam/$media,image
```

**Comment by thislife81** [comment]
Not worked, ad is shown again

**Comment by Alex-302** [comment]
Can't reproduce.
http://i.imgur.com/gzyjPoe.png

**Comment by thislife81** [comment]
Please remove this.
![01](https://cloud.githubusercontent.com/assets/19608513/18032792/995f2060-6d22-11e6-867b-2d54e5c617df.png)

**Comment by Alex-302** [comment]
Added to Turkish filter
```
inndirmedenfilmizle.com###reklami-gec
inndirmedenfilmizle.com#$##video { display: block!important; }
```
