### ISSUE TITLE
Tapatalk banner on mobile versions of forums

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#27235]
Tapatalk ads are displayed to mobile Firefox users.

Blocking `/smartbanner/appbanner.`  fixes this.

Example pages:

    http://www.reefclub.net.br/community/index.php
    http://forum.brfoto.com.br/
    https://forum.lolesporte.com/viewforum.php?f=8
    http://forumchaves.com.br/

![tapatalk](https://user-images.githubusercontent.com/35470489/49576380-32be2700-f92c-11e8-9d41-25f134dbc706.png)

Firefox 63 for Android
uBlock Origin 1.17.4
Adguard Mobile Filters list

**Comment by BlazDT** [comment]
Please enable Annoyances filter and update.
