### ISSUE TITLE
http://hdfilmevreni.net/ -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2724]
**Site**: http://hdfilmevreni.net/

**Screenshot**: http://s31.postimg.org/q5pk8jvdn/screenshot_24.png

**Adguard version**: 2.4.3

**Operating system**: Windows 10

**Browser**: Google Chrome

**Filter list**: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdfilmevreni.net#$#body { background: #000000!important; }
```
Added to Annoyances filter
```
hdfilmevreni.net##.facebookbox
```
