### ISSUE TITLE
http://www.hdbedavaizle.com/ -free space

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2725]
**Site**: http://www.hdbedavaizle.com/kayip-balik-dori-turkce-dublaj-izle/

**Screenshot**: http://s31.postimg.org/fy70w595n/screenshot_25.png

**Adguard version**: 2.4.3

**Operating system**: Windows 10

**Browser**: Google Chrome

**Filter list**: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
hdbedavaizle.com###alt
```
