### ISSUE TITLE
Yandrx.Direct in Zen

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#2726]
![image](https://cloud.githubusercontent.com/assets/15856304/17285633/94733c64-57cc-11e6-82b3-377b6b3461e5.png)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17285640/9dc831de-57cc-11e6-9074-4445b8726b83.png)
</details>

**1129133**
**1551014**

**Comment by Alex-302** [comment]
Что есть Zen?

**Comment by evgeniy-ADG** [comment]
Ой, это нечто встроенное в Яндекс, призванное показывать рекомендации. Вова умеет повторять, вроде бы :)

**Comment by evgeniy-ADG** [comment]
https://yandex.com/discovery/zen

**Comment by ameshkov** [comment]
@Alex-302 эта штука встроена в яндекс браузер, лента новостей такая.

Еще вот:
https://zen.yandex.ru/

Важная вещь, надо исправить.

**Comment by Alex-302** [comment]
там регексп нужно сделать такой, чтоб чётность скобок учитывал.
Как-то смотрел, но правило корявое очень
https://gist.github.com/anonymous/4370c6848397e52d88de681d32651648
```
||zen.yandex.ru/api/v3/desktop/export/?country_code=$replace=/(\,"ad":)\[(.*?)\][\s\S]*(])/\,"ad": []/ 
```
http://regexr.com/3dldb

**Comment by ameshkov** [comment]
А нельзя псевдолементами загасить?

**Comment by ameshkov** [comment]
Аа, там не хтмл? Там xml-фид?

**Comment by Alex-302** [comment]
да, xml

**Comment by deLumren** [comment]
Пользователь 1537862 сообщает, что реклама от Яндекс.Директ в Дзене присутствует и сегодня.

<details>

![dzen](https://cloud.githubusercontent.com/assets/26342177/24781065/b42bcbee-1b34-11e7-851f-d1b53369515b.jpg)

</details>

**Comment by ameshkov** [comment]
@Alex-302 мы ж вроде исправляли?

**Comment by Alex-302** [comment]
@ameshkov да тогда не получилось по-нормальному - то рекламу вырезало, то содержимое портило.
Гляну ещё раз.

**Comment by ameshkov** [comment]
@Alex-302 если xml новую выгрузишь - гляну что можно сделать.

**Comment by Alex-302** [comment]
URL:
https://zen.yandex.ru/api/v3/desktop/export/?profile_id=E031D0ED&country_code=ua&ui=F74530AF-E374-49E9-B47D-77ECB98E8311&clid=2270540
Raw:
https://gist.github.com/Alex-302/52d0252a355466d023cf437822c431b0
В читаемом виде:
https://gist.github.com/Alex-302/3f7afd6e8ff43986a40af9ad1ee3856d
Пример рекламной секции:
```
        {
            "url": "https://yabs.yandex.ru/count/****",
            "title": "Dreams Beach Resort",
            "body": "Быстрое бронирование oтеля онлайн! Низкие цены! 873 отзывa ! фото!",
            "domain": "tripadvisor.ru",
            "age": "",
            "warning": "",
            "linkTail": "=**********",
            "linkHead": "https://yabs.yandex.ru/count********",
            "type": "direct",
            "size": 1
        },
```

**Comment by ameshkov** [comment]
Хм, ну я должен признать, что все-таки json дико неудобно исправлять.

Надо подумать насчет модификатора конкретно для json.

**Comment by Alex-302** [comment]
Стоит надеяться на его появление?

**Comment by ameshkov** [comment]
> Стоит надеяться на его появление?

Стоит, задача частая

**Comment by Alex-302** [comment]
Здесь тогда закрою. Отпишу в https://github.com/AdguardTeam/AdguardFilters/issues/5828

**Comment by ameshkov** [comment]
@Alex-302 а теперь ведь проще стало, они там рекламу вынесли в отдельный элемент "ad"
