### ISSUE TITLE
http://www.diary.ru/ - logs off on every restart of Safari

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2727]
Некорректная блокировка на странице:
http://www.diary.ru/

При выключении браузера Сафари идет автоматический разлогин. Отключила Adguard - проблема исчезла. То есть проблема явно в приложении.

**1268487**

<details>
Application version: 1.0.8.54
Application lifetime: 2016-05-06 21:27:44 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.2
ID: 2A8469F5-9A51-4F85-8963-E660758D57CE

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.83.67 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.66 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.71 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.33.75 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.3.48 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.0.50 Enabled=YES

**Comment by evgeniy-ADG** [comment]
Повторилось. После выключения Контент Блокера, больше не разлогинивало.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
У меня разлогинивает при полном выходе из Сафари даже без Адгарда. Когда просто закрываю - не разлогинивает. Но это на десктопе.
Можешь проверить с выключенными фильтрами?

**Comment by evgeniy-ADG** [comment]
Хм, теперь разлогинивает тоже, и без Адгарда. Странно. Я отпишу пользователю.
