### ISSUE TITLE
http://www.animespirit.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2728]
http://www.animespirit.ru/anime/rs/series-rus/11157-moya-pervaya-lyubov-monstr-hatsukoi-monster.html

**1344544**
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17286572/2ac50b88-57d3-11e6-9759-460f34ddbe9e.png)

![image](https://cloud.githubusercontent.com/assets/15856304/17286577/357abc76-57d3-11e6-8d74-6f874f4a47bb.png)
</details>

FILTERS
<details>
Application version: 1.0.8.54
Application lifetime: 2016-07-10 19:02:08 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.2
ID: 9265F89D-8164-4C5A-ADF5-43A57B2C3B89

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.81 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.61 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.79 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.1.44 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.36.23 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.19 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.80 Enabled=YES

**Comment by Alex-302** [comment]
Can't reproduce with Safari extension on Mac OS.

**Comment by Alex-302** [comment]
@vozersky please check it on iPad.

**Comment by evgeniy-ADG** [comment]
Я проверял на айпеде и у меня повторилось 1:1.

**Comment by Alex-302** [comment]
У меня нет иосных устройств. Если сможешь подключиться к айпаду через десктопный Адгард - смогу проверить, что не заблокировалось.

**Comment by evgeniy-ADG** [comment]
Были проблемы с фильтрами, не повторяется, пользователю отпишу.
