### ISSUE TITLE
http://kino-serial.net/ - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2730]
http://kino-serial.net/films/4063-belosnezhka-i-ohotnik2-smotret-online-hd-720.html

![image](https://cloud.githubusercontent.com/assets/15856304/17287223/03e0ed12-57d7-11e6-8bd2-53d92892c28a.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-02-28 04:05:18 +0000
Device: iPad
Platform: iPhone OS
OS: 9.3.3
ID: 5AC69415-669F-439E-91F4-43DA2899CFD5

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.90.31 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.95 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.23 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.2.26 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.89 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.37.23 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.25.70 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.4.41 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.96 Enabled=YES
ID=101 Name="EasyList" Version=1.0.55.43 Enabled=NO
ID=118 Name="EasyPrivacy" Version=1.0.54.67 Enabled=NO
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.1.60 Enabled=NO
ID=204 Name="Peter Lowe's list" Version=1.0.2.20 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.55.48 Enabled=NO
ID=208 Name="Malware Domains" Version=1.0.61.83 Enabled=NO
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=NO
ID=210 Name="Spam404" Version=1.0.1.50 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES

**Comment by Alex-302** [comment]
Добавил в фильтр Сафари
```
kino-serial.net##div[style^="background-image: url(data:image/jpeg;base64"]
```
