### ISSUE TITLE
www.eblogx.com - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2731]
http://www.eblogx.com/Videos/32038/Ein-neuer-Tipp-von-PS-Profi-JP-Kraemer/

Annoyances filter causes incorrect blocking:

<details>
![20160801_111237000_ios](https://cloud.githubusercontent.com/assets/15856304/17292369/46dbf556-57f2-11e6-9c53-8e5316781606.png)
![20160801_110954000_ios](https://cloud.githubusercontent.com/assets/15856304/17292370/46df7aa0-57f2-11e6-80e1-e71cff49070f.png)

</details>

<details>
Application version: 1.0.8.54
Application lifetime: 2016-07-16 17:27:03 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.3
ID: 61F98249-B915-4247-8DC7-C98AA8E99630

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.89.21 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.67 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.90 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.1.72 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.89 Enabled=YES
ID=6 Name="German filter" Version=1.0.26.33 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.22 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.82 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.61.74 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.50 Enabled=YES

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
@@||eblogx.com/js/jquery.cookiebar.js
```
