### ISSUE TITLE
http://m.pikabu.ru/ - sponsored cntent

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2732]
Пропущена реклама на странице:
http://m.pikabu.ru/
![image](https://cloud.githubusercontent.com/assets/15856304/17292481/03d0d2ee-57f3-11e6-9e94-a46324b96989.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.90.39 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.95 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.23 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.2.27 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.37.23 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.41 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.96 Enabled=YES

**Comment by Alex-302** [comment]
На иОС не убрать, JS правила не поддерживаются.
