### ISSUE TITLE
WPS Office app missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2733]
**Description**:
Source and screenshot:
http://forum.xda-developers.com/showpost.php?p=67964465&postcount=1511

> 2nd ads are not blocked in "WPS Office" (open any word doc. & scroll down to end and you will see many ads...1st one is hard coded (i think) but others can be blocked bcz they won't apper if wifi is off ) {see attachment}

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||ws.ksmobile.net/api/GetCloudMsgAdv?$empty
||cloudservice24.kingsoft-office-service.com/cards$empty
||counter.kingsoft.com^$empty
```
