### ISSUE TITLE
touch.pixiv.net - ad leftovers

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2734]
Missed ad on page:
http://touch.pixiv.net/

A black box surrounding blocked ad (on the bottom) remains.

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17322829/29a37f66-58a8-11e6-87a8-5a215bcd432e.png)
![image](https://cloud.githubusercontent.com/assets/15856304/17322835/30ee63bc-58a8-11e6-9729-7c1d38a0f322.png)
</details>

**1331438**<details>
Application version: 1.0.8.54
Application lifetime: 2016-07-29 10:51:08 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.3
ID: C0EC0546-684E-4F88-8DDA-2A8BFBFFFA07

Locale: ko
Region: kr

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.90.42 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.88 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.11.22 Enabled=NO
ID=7 Name="Japanese filter" Version=1.0.92.99 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.96 Enabled=YES
ID=224 Name="Korean Adblock List" Version=1.0.0.2 Enabled=NO
ID=227 Name="List-KR" Version=1.0.0.54 Enabled=YES

**Comment by Alex-302** [comment]
Can't reproduce
