### ISSUE TITLE
https://www.ss.lv - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2735]
https://www.ss.lv/msg/lv/work/courses-education/auklu-majkalpotaju-kursi/achcx.html

![image](https://cloud.githubusercontent.com/assets/15856304/17324358/d764465c-58ae-11e6-907f-6b8e91e5f00a.png)

I suspect Adblock Polskie Reguly. Without this filter, site loads as expected:

![image](https://cloud.githubusercontent.com/assets/15856304/17324397/0a497722-58af-11e6-91ee-41ae4d3100c2.png)

<details>
Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:10 Name: Filter for useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:104 Name: EasyList China Url: https://easylist-downloads.adblockplus.org/easylistchina.txt
FilterId:109 Name: EasyList Italy Url: https://easylist-downloads.adblockplus.org/easylistitaly.txt
FilterId:111 Name: Latvian List Url: https://notabug.org/latvian-list/adblock-latvian/raw/master/lists/latvian-list.txt
FilterId:119 Name: Icelandic ABP List Url: http://adblock.gardar.net/is.abp.txt
FilterId:216 Name: Adblock polskie reguły Url: https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt
FilterId:0 Name: User filter Url: no_url

**Comment by Alex-302** [comment]
Added to English filter
```
ss.lv#@#[id^="ads_"]

```
