### ISSUE TITLE
www.theatlantic.com - taboola ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2736]
http://www.theatlantic.com/politics/archive/2016/08/sally-bradshaw-trump-gop/493910/

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.85.29 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.4 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.3 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.55 Enabled=YES

![20160802_095756000_ios](https://cloud.githubusercontent.com/assets/15856304/17324842/1345559c-58b1-11e6-858d-d3524cd7642c.png)

**Comment by Alex-302** [comment]
Can't reproduce in Safari on Mac.

**Comment by Alex-302** [comment]
@vozersky please check it on iPad.

**Comment by vozersky** [comment]
@Alex-302 can't reproduce

**Comment by Alex-302** [comment]
ok, thanks

**Comment by Alex-302** [comment]
@evgeniy-ADG are the filters full or simplified?
