### ISSUE TITLE
loverscum.com [NSFW] [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#27369]
**Site**: https://www.loverscum.com/albums/45257/jane-wilde-cuckold-sessions/

**Issue**: Please remove the adblock message on the page.

**Screenshot**: http://prntscr.com/lyy0uo

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 71.0.3578.98 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
