### ISSUE TITLE
http://www.mitsubishiclub.cz/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2737]
http://www.mitsubishiclub.cz/

![image](https://cloud.githubusercontent.com/assets/15856304/17325848/907d5078-58b6-11e6-9345-2f796b4f9125.png)

It detects English filter.

**Comment by Alex-302** [comment]
Added to English filter
```
@@||mitsubishiclub.cz^$generichide
```
