### ISSUE TITLE
http://peers.tv/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2738]
**Description**: Не работает видео на сайте
При включённой блокировке получаю
сообщение: Error loading plugin. Plugin not found.
http://peers.tv/show/2x2tv/sandzhey_i_kreyg_sanjay_and_craig/74659469/?autoplay=1

Помогает отключение Английского фильтра

Screenshot:
<details>
![screenshot_49](https://cloud.githubusercontent.com/assets/18548949/17336260/061f7a66-58e6-11e6-91c8-28d2bebbdb08.jpg)

</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||peers.tv/jwplayer/ariver/plugin.swf$domain=peers.tv
```
