### ISSUE TITLE
m.economictimes.com - anti-adblock

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2739]
**Description**:
http://forum.xda-developers.com/showpost.php?p=68014694&postcount=1517

Any article redirects to a "blocked" page.

For instance:
http://m.economictimes.com/news/politics-and-nation/from-pm-modis-turf-sonia-gandhi-hits-out-at-modi-government/articleshow/53512266.cms

**Comment by Alex-302** [comment]
Added to English filter
```
@@economictimes.com/*ads*/*.cms
```
Added to Annoyances filter
```
indiatimes.com###pushSec
indiatimes.com##.cookie_info
```

**Comment by ameshkov** [comment]
why not `@@||economictimes.com/*ads*/*.cms`?

**Comment by Alex-302** [comment]
But I edited my rule just now)
