### ISSUE TITLE
[ERR_TOO_MANY_REDIRECTS] szukajka.tv

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#27403]
**Site Sample** | 
-----------------------------|
http://szukajka.tv

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Chrome Stable x64
AdGuard version:                       | **6.4.1840.4955**
Stealth mode:					       | **disabled**

| Filters enabled |
|-----------------|
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| CoinBlockerLists
| EasyList Polish 
| Fanboy's Annoyances
| Fanboy's Enhanced Tracking List 
| Fanboy's Social Blocking List 
| I don't care about cookies
| KAD - fraud/scam 
| Malware Domains
| NoCoin Filter List 
| Peter Lowe's List
| Polish Annoyances
| Polish Main
| Polish Social

### Issue:

`ERR_TOO_MANY_REDIRECTS` after select any content to play in inframe. 

1. Search any content name.
![scr-1545730403-001](https://user-images.githubusercontent.com/9846948/50419335-adde7300-0830-11e9-86bb-4a4202ef5dbf.png)

2. Click on title and **watch** next for opening player in inframe.
![scr-1545730416-001](https://user-images.githubusercontent.com/9846948/50419355-bd5dbc00-0830-11e9-93fd-7b21ce8474e7.png)

3. Chrome will redirect to `ERR_TOO_MANY_REDIRECTS` error page instead of content. 
![scr-1545730529-001](https://user-images.githubusercontent.com/9846948/50419369-d0708c00-0830-11e9-800e-e9b10ff54054.png)

CC @AdamWr 

Zgłosiłem to na polskie strony (polish ads) ale do dzisiaj nie naprawiono problemu bo oni nie mogli tego odtworzyć. > https://github.com/MajkiIT/polish-ads-filter/issues/8846

**Comment by AdamWr** [comment]
To jest spowodowane listą `NoCoin Filter`, ale że problem z przekierowaniem występuje tylko w przypadku programu, to dodałem reguły do "Podstawowej/Angielskiej" listy.

**Comment by FadeMind** [comment]
@AdamWr  Reguły działają pięknie. Bardzo dziękuję. Pozdrawiam

**Comment by FadeMind** [comment]
@AdamWr za dużo pozwalasz cda.pl 😱 

![scr-1546022184-001](https://user-images.githubusercontent.com/9846948/50524783-ff5c5b80-0ad7-11e9-801b-ee71cace376e.png)

**Comment by AdamWr** [comment]
To nie wina reguł, które dodałem.
Na razie możesz dodać do własnych filtrów:
`||cda.pl/*xml*.php?a`
a potem wrzucę to (albo coś podobnego) do polskiej listy.

**Comment by FadeMind** [comment]
@AdamWr jeszcze drobiazgi 😉 
![scr-1546343644-001](https://user-images.githubusercontent.com/9846948/50572639-7178bd00-0dc4-11e9-8950-f027a8e13a88.png)

![scr-1546343728-001](https://user-images.githubusercontent.com/9846948/50572641-881f1400-0dc4-11e9-8c92-48cac92acf1f.png)

![scr-1546343821-001](https://user-images.githubusercontent.com/9846948/50572650-c1f01a80-0dc4-11e9-8fe6-ddd25828e3b6.png)

**Comment by FadeMind** [comment]
@AdamWr  to się dzieje tylko na `szukajka.tv`. W EMBED > `https://openload.co/embed/S7z-GK8X8IU/The_Edge_of_Seventeen_%5B2016%5D_PLSUBBED.720p.BDRiP.XViD.AC3-MX.avi.mp4` tego nie zauważyłem. 

Dodałem 
```
||openload.co/advert2.js
```
Globalnie do reguł i nie widzę już reklam na szukajka > openload.

**Comment by AdamWr** [comment]
Ten skrypt `openload.co/advert2.js` zawiera tylko:
`var sadbl=false;`
więc to raczej służy do sprawdzania czy "adblock" jest włączony.
Swoją drogą, jesteś pewny, że po dodaniu:
`||openload.co/advert2.js`
ten skrypt został zablokowany?
Bo wydaje mi się, że dopóki nie dodasz `$important` to ze względu na tę regułę z `AdGuard Base filter`:
`@@||openload.co/advert2.js`
on nadal powinien być odblokowany.
Może coś innego powoduje ten problem?

**Comment by FadeMind** [comment]
@AdamWr Zgadza się, reguła advert2.js nie działa.
Po wyczyszczeniu cookies i cache:
![scr-1546430389-001](https://user-images.githubusercontent.com/9846948/50591167-6722f580-0e8e-11e9-8d24-01f51e3f6852.png)

Używam także Mbam Extension https://chrome.google.com/webstore/detail/malwarebytes-browser-exte/ihcjicgdanjaechkgeegckofjjedodee 
Ale nawet po wyłączeniu tego (wyczyszczenie cache, cookies) nadal reklamy się pojawiają.

**Comment by AdamWr** [comment]
Potrafię to odtworzyć tylko wtedy, gdy zezwolę na żądania z tych stron:
`vidcpm.com`
`acloudvideos.com`

Mógłbyś proszę sprawdzić te reguły:
`||vidcpm.com^$important`
`||acloudvideos.com^$important`

Jeśli to nie będzie działać to usuń te reguły następnie otwórz proszę dziennik filtrowania, odtwórz problem, wyeksportuj raport filtrowania do pliku i wstaw tutaj.

**Comment by FadeMind** [comment]
@AdamWr 
```
||vidcpm.com^$important
||acloudvideos.com^$important
```
póki co rozwiązało problem, jeżeli sytuacja się powtórzy - stworzę raport z dziennika filtrowania. Dziękuję  i pozdrawiam 😉

**Comment by FadeMind** [comment]
@AdamWr za wcześnie ogłosiłem sukces, jak wykonać poprawnie zrzut logów, które potrzebujesz do śledztwa 😈

**Comment by AdamWr** [comment]
Otwórz proszę raport filtrowania, odtwórz problem, a potem kliknij na przycisk do wyeksportowania logu do pliku (tak jak na obrazu poniżej), następnie umieść ten plik tutaj.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/50611540-21d6e600-0ed7-11e9-9141-fe5c9e3a8bc2.png)

</details>
<br>

Możesz też utworzyć plik HAR.

**Comment by FadeMind** [comment]
@AdamWr nie wiem o co chodzi, ale o dzisiaj EMBED OpenLoad Player jest baardzo mały 
![scr-1546581412-001](https://user-images.githubusercontent.com/9846948/50675370-fdb9f880-0fed-11e9-8e21-811fe8975dbe.png)
Nie pojawiają się reklamy, logi wyglądają następująco: https://pastebin.com/raw/Vdk08zYD

Odnośnie VIDOZA:
![scr-1546581685-001](https://user-images.githubusercontent.com/9846948/50675487-b8e29180-0fee-11e9-8b91-b8da55edf2d9.png)
Po włączeniu odtwarzania na tym serwerze Malwarebytes Chrome Ext. czasami blokuje połączenie. 
Dodatkowo nie ma możliwości odtwarzania w pełnym ekranie treści - po przełączeniu pełny ekran jest czarny, słychać tylko dźwięk. Jak przejdzie się na adres
EMBED URL https://vidoza.net/embed-tzn7n7b60cug.html
to pełny ekran działa - ale MBAM blokuje połączenie:
![scr-1546582069-001](https://user-images.githubusercontent.com/9846948/50675606-7a99a200-0fef-11e9-81a5-0b377c19548c.png)

LOG Adguard z filtrowania vidoza.net: https://pastebin.com/raw/rguY3jQF

**Comment by AdamWr** [comment]
Nie mam pojęcia dlaczego odtwarzacz jest taki mały (u mnie się tak nie dzieje), ale jeśli chodzi o reklamy, to mogą one być spowodowane tą regułą:
`@@||openload.co^$genericblock,generichide`
z listy `Fanboy's Enhanced Tracking List`, myślę, że najlepiej będzie jak tę regułę wyłączysz po prostu.

Odnośnie vidozy, sprawdź proszę tę regułę:
`@@||vidoza.net/js/videojs`

**Comment by FadeMind** [comment]
@AdamWr openload - reklam nie ma póki co - na szukajka tv jest mały embed - bez zmian
na vidoza.net player jest OK, ale mbam nadal krzyczy, że znalazł niebezpieczną stronę i blokuje odtwarzanie po chwili. Full screen działa poprawnie.
