### ISSUE TITLE
perfectgirls.net [NSFW] [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#27408]
**Site**: http://www.perfectgirls.net/gal/563068/Kimber_and_Emeline_are_sucking_cocks_at_the_same_time__while_kneeling_in_front_of_their_guys

**Issue**: Pop-up seen when clicking on the full screen icon (on the video player) to maximise the video.

**Screenshot**: N/A

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 71.0.3578.98 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
Not fixed. Still seeing a pop-up when clicking on the full screen icon (on the video player) to maximise the video.

http://www.perfectgirls.net/gal/627905/Pigtailed_teen_is_deepthroating_in_front_of_the_camera_although_she_is_just_an_amateur/?sub_id=911

**Comment by Alex-302** [comment]
not reproduced
