### ISSUE TITLE
missed ads ontvtime.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2740]
Пропущена на www.ontvtime.ru
Фильтры базовые, обновленные.

![image1](https://cloud.githubusercontent.com/assets/16462533/17343216/3d6e20b6-5905-11e6-80e3-9ca2824fdf98.PNG)

**Comment by Alex-302** [comment]
Не бывает базовых фильтров. Или у него японский, турецкий и испанский тоже включены?
У меня в Сафари на Макоси чисто.

**Comment by Serzh-SUP** [comment]
@Alex-302 

Базовые, имею введу фильтры Adguard, как на скрине. Перед создание задачи, я проверяю на своем телефоне. У меня нет турецких, испанских и т.д. Но сама проблема повторилась, реклама есть.

![img_0645](https://cloud.githubusercontent.com/assets/16462533/17432616/d4993138-5b08-11e6-81db-c47dacb1d2f6.PNG)

**Comment by Alex-302** [comment]
Странно, обычная гугловая реклама. Должна блокироваться.
@vozersky глянь на айпаде, повторяется ли.

**Comment by vozersky** [comment]
@Alex-302 у меня не повторяется

**Comment by Alex-302** [comment]
Странно.

**Comment by Serzh-SUP** [comment]
@Alex-302 
Проблема решена, рекламы нет.
