### ISSUE TITLE
[social] newsweek.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#27418]
**Site Sample** | 
-----------------------------|
https://www.newsweek.pl/kultura/pola-raksa-jedna-z-najwiekszych-polskich-gwiazd-dlaczego-aktorka-zniknela/p229v36

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Chrome Stable x64
AdGuard version:                       | **6.4.1840.4955**
Stealth mode:					       | **disabled**

| Filters enabled |
|-----------------|
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| CoinBlockerLists
| EasyList Polish 
| Fanboy's Annoyances
| Fanboy's Enhanced Tracking List 
| Fanboy's Social Blocking List 
| I don't care about cookies
| KAD - fraud/scam 
| Malware Domains
| NoCoin Filter List 
| Peter Lowe's List
| Polish Annoyances
| Polish Main
| Polish Social

### Issue:

Social leftover

### Fix:
```
newsweek.pl##.articleSocials
```

<details><summary><b>Screenshot:</b></summary>

![scr-1545757319-001](https://user-images.githubusercontent.com/9846948/50425031-4b589780-086f-11e9-847d-56a2caeca782.png)

</details><br/>

**Comment by AdamWr** [comment]
Lista `Fanboy's Annoyances`/`Fanboy's Social Blocking List` ukrywa odnośnik do komentarzy, czego zazwyczaj nie blokujemy.
 
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/50479208-b02e0200-09d5-11e9-921d-84f86aa29d96.png)

</details>
<br>

Myślę, że możesz tę regułę `newsweek.pl##.articleSocials` dodać do własnych filtrów albo zgłosić problem tutaj - https://github.com/ryanbr/fanboy-adblock/issues
