### ISSUE TITLE
missed ads kinopoisk.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2744]
Пропущена реклама.
Фильтры базовые Adguard, обновленные. 

https://www.kinopoisk.ru/film/3741/

![img_0595](https://cloud.githubusercontent.com/assets/16462533/17358070/90fd1c2e-5968-11e6-96dc-668d23f71013.PNG)

**Comment by Alex-302** [comment]
У меня сайт без брендинга загружается. Проверь эти правила:
```
||st.kp.yandex.net/images/bnnr/$domain=kinopoisk.ru
kinopoisk.ru###brandingFlash
```

**Comment by Serzh-SUP** [comment]
@Alex-302 
Добавил это правило в "Свои правила" на айфоне, ничего не изменилось.

**Comment by Alex-302** [comment]
Странно. В Сафари на маке без фильтров проверил, правила убирают рекламу.
Добавил
```
||st.kp.yandex.net/images/bnnr/$domain=kinopoisk.ru
kinopoisk.ru###brandingFlash
kinopoisk.ru##.direct-kp-customize
```
проверь после обновления фильтров. Может расширение тупит.

**Comment by Serzh-SUP** [comment]
@Alex-302 
Проблема решена. Спасибо.
