### ISSUE TITLE
Mail.ru excessive blocking

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#2746]
Russian filter blocks elements that lead to subsidiary domains (afisha.mail.ru etc.)

Screenshot: http://screencast.com/t/hTnwyNCL

**Comment by Alex-302** [comment]
Вот, почему блокируем - треть блоков - рекламные(те, которые на скрине, блокируются антифишингом при попытке посетить)
<details> 
![d](http://imagizer.imageshack.com/img921/5175/aKoIah.png)
</details>
