### ISSUE TITLE
rustorka.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2748]
**Description**:
http://rustorka.com/forum/viewforum.php?f=1398
Не отображается вес раздач
Помогает отключение Русского фильтра

Screenshot:
<details>

![screenshot_53](https://cloud.githubusercontent.com/assets/18548949/17372221/90a34526-59ab-11e6-8e90-9d2b36281e17.jpg)

![screenshot_54](https://cloud.githubusercontent.com/assets/18548949/17372222/90a364c0-59ab-11e6-8264-5c4f6d781bbe.jpg)
</details>

**Filters list**: 1,2,3,4,14

**Browser**: Хром

**Comment by Alex-302** [comment]
Уже отображается.

**Comment by vgavrish** [comment]
http://rustorka.com/forum/index.php
отсутствует строка для входа в свой аккаунт
Фильтры 1,2,3,4,14
<details>
![screenshot_73](https://cloud.githubusercontent.com/assets/18548949/17488633/e181d6e2-5da2-11e6-8a02-54b126030116.jpg)

**Comment by Alex-302** [comment]
Подправил.

**Comment by vgavrish** [comment]
Расширение. Опера
Не отображается чат после авторизации на сайте
Помогает отключение Русского фильтра
лог пас ниже
<details>
лог: djanim
пас: 19933991
![image](https://cloud.githubusercontent.com/assets/18548949/20461297/ee663e06-af01-11e6-9c7b-dacda1d621aa.png)

**Comment by Alex-302** [comment]
исправил

**Comment by evgeniy-ADG** [comment]
Снова проблема с чатом. Вот скрины с нами и без нас:

<details>

![off](https://cloud.githubusercontent.com/assets/15856304/22861952/4b117e78-f12d-11e6-8bc4-68aeb53c4939.png)
![on](https://cloud.githubusercontent.com/assets/15856304/22861951/4b10bc0e-f12d-11e6-8162-f1cc338452b3.png)

**Comment by Alex-302** [comment]
fixed

**Comment by zebrum** [comment]
http://rustorka.com/forum/index.php
не переходит по внутренним ссылкам на раздачи из раздела Важные объявления:

![screenshot 2017-03-31 14 19 57](https://cloud.githubusercontent.com/assets/23637588/24548318/3a753c66-161d-11e7-82fa-5334562fc713.png)

**Comment by Alex-302** [comment]
fixed
