### ISSUE TITLE
http://sdelatvideo.ru/ - anti-adblcok

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2749]
http://sdelatvideo.ru/

![image](https://cloud.githubusercontent.com/assets/15856304/17394242/bb3ce0be-5a30-11e6-90a2-ec2ee17f5e53.png)
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17394249/c800ada8-5a30-11e6-9abf-0c4b6e97d7f0.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||sdelatvideo.ru/resources/jsc/ads.js
```
