### ISSUE TITLE
http://www.kcdod.khb.ru/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2750]
http://www.kcdod.khb.ru/

Скрывается вот эта область:
![image](https://cloud.githubusercontent.com/assets/15856304/17397234/cee4d57c-5a3f-11e6-854c-f7c06d90737d.png)
1. При использовании Adguard на всех браузерах на этом сайте (www.kcdod.khb.ru)
2. Установить расширение Adguard для браузера (или использовать Win32 приложение) и зайти на сайт со стандартным набором фильтров блокировки рекламы
3. Английский фильтр, Фильтр счетчиков и системы аналитики, Русский фильтр.
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17397250/df9ec526-5a3f-11e6-87f4-50f4b455d7db.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
kcdod.khb.ru#@##banners_left

```
