### ISSUE TITLE
http://nation.foxnews.com/ - Annoyances filter blocks videos

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2751]
http://nation.foxnews.com/2016/08/02/oreilly-lesson-donald-trump

<details>
![20160804_122715000_ios](https://cloud.githubusercontent.com/assets/15856304/17401859/ae2fb98c-5a58-11e6-8eac-688c6ed711f2.png)
After disabling Annoyances:
![20160804_122827000_ios](https://cloud.githubusercontent.com/assets/15856304/17401858/ae28a8e0-5a58-11e6-89d5-23bcbb927d9e.png)
</details>

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.90.70 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.7 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.30 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.2.40 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.91 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.48 Enabled=NO
ID=12 Name="Safari filter" Version=1.0.1.2 Enabled=YES
ID=101 Name="EasyList" Version=1.0.61.24 Enabled=NO

**Comment by Alex-302** [comment]
Can reproduce it on Android. Did user checked only with Annoyances filter?

**Comment by evgeniy-ADG** [comment]
No, I checked this on iOS and it stops happening once I disable Annoyances.

**Comment by Alex-302** [comment]
Добавил в фильтр Сафари
```
@@||analytics.edgesuite.net^$domain=foxnews.com
@@||global.fncstatic.com/static/v/all/js/ads.js$domain=foxnews.com
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=foxnews.com
```
нужно проверить после обновления
