### ISSUE TITLE
http://www.raisport.rai.it/ - anti-adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2752]
![image](https://cloud.githubusercontent.com/assets/15856304/17428483/6d86a834-5af1-11e6-80fd-58babb1c86fe.png)
http://www.raisport.rai.it/dl/raiSport/dirette/ContentItem-49340f1d-5246-4cf7-931f-75d65af039e7.html

Don't block for 30 seconds:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17428503/8f81f664-5af1-11e6-97c1-654b1b60da60.png)
</details>
Filters
<details>
![Uploading image.png…]()

**Comment by Alex-302** [comment]
Список фильтров не вставился.

**Comment by Alex-302** [comment]
Передай на проверку:
```
@@||raisport.rai.it^$generichide
```
