### ISSUE TITLE
missed ads expertvaz.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2753]
Пропущена на http://expertvaz.ru/2114/ksenon-ustanovka.html

Фильтры обновлены, стандартные Adguard

Проблема повторилась.

![image1](https://cloud.githubusercontent.com/assets/16462533/17432393/9b513034-5b07-11e6-8711-d53b31ce1221.PNG)

**Comment by Alex-302** [comment]
А можешь свой filter.gz прислать? Какая-то не здоровая ситуация. Обычная гуглореклама не блокируется.

**Comment by Serzh-SUP** [comment]
> ФАЙЛ:

> [filter.gz](https://github.com/AdguardTeam/AdguardFilters/files/421934/filter.gz)

**Вот мои скрины, рекламы много:**

![img_0757](https://cloud.githubusercontent.com/assets/16462533/17727473/1a1b733a-6462-11e6-9455-2cc14c258af1.PNG)

**Скрин фильтров + Safari**

![img_0758](https://cloud.githubusercontent.com/assets/16462533/17727472/1a1af270-6462-11e6-9944-4e33fa414edb.PNG)

**Comment by Alex-302** [comment]
Странно это всё. Не первый раз гуглореклама не блокируется, хотя правило вроде есть
```
{
		"trigger": {
			"url-filter": "\\/googleads\\."
		},
		"action": {
			"type": "block"
		}
	}
```
в обычном виде
```
/googleads.
```

**Comment by Serzh-SUP** [comment]
@Alex-302 Уже все в порядке. Спасибо.
