### ISSUE TITLE
Outlook.com anti-adblocking script

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#2754]
![screen shot 2016-08-05 at 19 37 05](https://cloud.githubusercontent.com/assets/17472907/17443644/69180cea-5b44-11e6-9df0-a8cfa6fb822e.png)

**Steps to reproduce the problem**:

1. login to outlook mailbox

**Adguard version**: 1.3.0
**Filters list**:
![screen shot 2016-08-05 at 19 39 05](https://cloud.githubusercontent.com/assets/17472907/17443628/4aefdd7e-5b44-11e6-9f9a-f6158c1e6e3c.png)

**Operating system**: OS X Sierra OB3
**Browser**: latest stable Chrome

**Comment by vozersky** [comment]
@Alex-302 is it possible to fix it?

**Comment by Alex-302** [comment]
It must be fixed by rules from annoyances filter
```
outlook.live.com##div[class="_n_h"][style*="width: 165px;"]
outlook.live.com#$##primaryContainer > div[style*="right: 165px;"] { width: 100% !important; }
```
but they don't works with Adguard for Mac.

**Comment by worldsdream** [comment]
I just checked this. It works fine for mac. 

I disabled annoyance, I did get this adblock message. 
I enabled annoyance, I still did get this adblock message. I cleared cache, it works.

1) enable annoyance filter, 
2) clear cache  

Everything is fine.

**Comment by vozersky** [comment]
@worldsdream oh, yes, it was already fixed, thanks for the update!
