### ISSUE TITLE
piratebay.host 

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2755]
* go to piratebay.host 
* random page opens in background

Check screen recording:
https://www.dropbox.com/s/v6jsydmbyrzsxvy/adGuard_2.m4v?dl=0

**Adguard version**: 1.3.0

**Filters list**:
![screen shot 2016-08-06 at 1 24 23 am](https://cloud.githubusercontent.com/assets/14153331/17452072/938a7898-5b74-11e6-9169-f49dbc6f3ce2.png)

Reported by **1386967**

**Comment by Alex-302** [comment]
Added to English filter
```
piratebay.host#%#Object.defineProperty(window, '_gunggo', { get: function() { return []; } });
```
