### ISSUE TITLE
megatorrents.org.ua

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2756]
**Description**:
http://megatorrents.org.ua/load/filmy/prikljuchenija/alisa_v_zazerkale_alice_through_the_looking_glass_2016_webrip_720p/25-1-0-2552

При нажатии на кнопку "Скачать/Download" открывается в другом окне левый сайт.
Screenshot: 

<details>
![screenshot_55](https://cloud.githubusercontent.com/assets/18548949/17454888/3c85e614-5baf-11e6-8848-54dfa7c1688f.jpg)

</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Яндекс

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в фильтр Сафари
```
||mega.megatorrents.org.ua^
||megatorrents.org.ua/c/*.js
||dskrt.net^$third-party
||teamrtb.net^$third-party
```
