### ISSUE TITLE
yandex search

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2758]
**Description**:
https://www.yandex.ua/
в яндекс поиске появилось сообщение о Олимпиаде

Screenshot:
<details>
![screenshot_57](https://cloud.githubusercontent.com/assets/18548949/17455767/0bb437c2-5bcb-11e6-9271-7398c7d0684e.jpg)

</details>

**Filters list**: 1,2,3,4,14

**Browser**: Хром, EDGE

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
yandex.ru,yandex.com,yandex.ua,yandex.kz,yandex.by##.olymp__panel
```
