### ISSUE TITLE
http://bombcat.ru/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2759]
**Description**:
http://bombcat.ru/buy/
При покупке котиков не реагирует кнопка "Отправить" заказ.
Помогает отключение фильтра счетчиков и систем аналитики.

Screenshot:

<details>
![screenshot_62](https://cloud.githubusercontent.com/assets/18548949/17460608/ad08274e-5c77-11e6-92cd-ca76f3b086c0.jpg)
</details>

**Adguard version**:

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в фильтр аналитики
```
@@||mc.yandex.ru/metrika/watch.js$domain=bombcat.ru

```
