### ISSUE TITLE
devid.info

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2760]
**Description**:
http://devid.info/ru/p629489/Realtek+PCIE+CardReader
Возможно ли убрать рекламный блог на сайте? никакой смысловой нагрузки он на странице не несёт
Screenshot:

<details>
![screenshot_63](https://cloud.githubusercontent.com/assets/18548949/17461435/f04db83a-5c94-11e6-89c0-a93f76f96cbb.jpg)

</details>

**Adguard version**: Расширение

**Filters list**: 1,2,3,4,5

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```

```
