### ISSUE TITLE
tvfru.net

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2761]
**Description**:
http://tvfru.net/novinki_kino/filmy_online/boevik/varkraft_warcraft/7-1-0-654
На заднем фоне реклама казино Вулкан.
+ При нажатии на проигрывании видео, открывается другой сайт (который быстро и закрывается)
+ после открывается и реклама

Screenshot:
<details>
![screenshot_66](https://cloud.githubusercontent.com/assets/18548949/17461599/1ea3d524-5c9b-11e6-83d3-a9f08fb1000e.jpg)
![screenshot_67](https://cloud.githubusercontent.com/assets/18548949/17461600/1ea60b00-5c9b-11e6-984a-aee97a739d96.jpg)
![screenshot_65](https://cloud.githubusercontent.com/assets/18548949/17461598/1e9c78f6-5c9b-11e6-944e-1ce25dbadd56.jpg)
</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||tvfru.net/barashek.css

```
