### ISSUE TITLE
probirka.org

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2762]
**Description**:
http://www.probirka.org/
Баннеры

+ Можно убрать отступ вверху сайта?

Screenshot:
<details>
![screenshot_68](https://cloud.githubusercontent.com/assets/18548949/17461731/02281302-5c9f-11e6-86bc-332a7096e2f6.jpg)
</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
probirka.org###adfox-wrapper

```
