### ISSUE TITLE
[nsfw] https://www.xozilla.com/

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#27638]
**Site Sample** | 
-----------------------------|
https://www.xozilla.com/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Chrome Stable x64
AdGuard version:                       | **6.4.1840.4955**
Stealth mode:					       | **disabled**

| Filters enabled |
|-----------------|
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| CoinBlockerLists
| EasyList Polish 
| Fanboy's Annoyances
| Fanboy's Enhanced Tracking List 
| Fanboy's Social Blocking List 
| I don't care about cookies
| KAD - fraud/scam 
| Malware Domains
| NoCoin Filter List 
| Peter Lowe's List
| Polish Annoyances
| Polish Main
| Polish Social

### Issue:

Ad blocked by ESET.

<details><summary><b>Screenshot:</b></summary>

![scr-1546166807-001](https://user-images.githubusercontent.com/9846948/50546495-c2ec4500-0c28-11e9-9859-a484da8043f8.png)

</details><br/>

**Comment by AdamWr** [comment]
Added:
`||xozilla.com/sw.js`
`||gcontentdelivery.info^$third-party`
