### ISSUE TITLE
http://www.iphoneitalia.com/ - placeholder

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2765]
![image](https://cloud.githubusercontent.com/assets/15856304/17471903/37942e16-5d50-11e6-94c2-1abb698db704.png)

Can we hide it?

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17471925/5da8a6b8-5d50-11e6-8eb5-ba80c62f85aa.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.90.75 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.11 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.37 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.3 Enabled=YES
ID=109 Name="EasyList Italy" Version=1.0.62.89 Enabled=YES

**Comment by Alex-302** [comment]
Added to Mobile filter
```
iphoneitalia.com.page-wrapper > center > div[style^="height:50px;"]
```
