### ISSUE TITLE
http://www.quoka.de - ad + cookies

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2766]
![image](https://cloud.githubusercontent.com/assets/15856304/17472906/3ccd5424-5d56-11e6-948e-6a64b893f1d2.png)

<details>
tested and repsoduced with english + spyware + social + annoyances + russian + german + japanese + experiemental + mobile + safari

**Comment by Alex-302** [comment]
Filters are full or simplified? I can't reproduce it with full filters.
With simplified I see only the cookie notification.

**Comment by evgeniy-ADG** [comment]
Full. Reload the page a couple of times, you'll see the banner (I hope...). I don't see the same banner as use sees, but it's located in the same place and has the same size.

**Comment by Alex-302** [comment]
Check these rules:
```
||adition.com^$third-party
quoka.de###div-gpt-ad-banner
```
Added to Safari filter

**Comment by evgeniy-ADG** [comment]
The banner is blocker, cookie notification is still there

**Comment by Alex-302** [comment]
Please check again. Cookie notification is blocked by annoyances filter in my Safari.

**Comment by evgeniy-ADG** [comment]
No, it's not on a real device with beta 4. The banner is perfectly blocked at my end as well, but the customer insists it's not on his device. What do we do? IF it available in Safari filter #1.0.1.15 or in the further updates?

**Comment by evgeniy-ADG** [comment]
User updated and still see this:

![image](https://cloud.githubusercontent.com/assets/15856304/17698786/ae992c2a-63c5-11e6-8617-9bb9640f9ec2.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
а у тебя этот баннер есть? У себя без Адгарда проверияю - его нет. Попросить бы юзера на десктопе повторить, да удалённо глянуть что там.

**Comment by evgeniy-ADG** [comment]
Nope. User has German IP and he still sees the ad. I'll try to test it with German IP on iOS device.

**Comment by Alex-302** [comment]
Tried. Nothing.
Can user reproduce this banner on desktop?

**Comment by evgeniy-ADG** [comment]
He ignores this question, will ask again.
