### ISSUE TITLE
amazon.com - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2767]
![image](https://cloud.githubusercontent.com/assets/15856304/17473520/856527cc-5d59-11e6-9fb0-ef41124ec6a1.png)

Sign in pop up. Reported here: **1387734**

<details>
>for the annoyances list - It misses a whole lot of javascript/css
floater type pop ups. I think you're just going to have to add a to
block all javascript/css based floating type pop ups as so many
websites abuse these.

**Comment by Alex-302** [comment]
Думаю не стоит.
