### ISSUE TITLE
https://www.hertz247.co.uk/ - cookies notification + some incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2768]
![image](https://cloud.githubusercontent.com/assets/15856304/17477020/67583492-5d6b-11e6-8f30-8582db9e4109.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-02-12 11:25:43 am +0000

Device: iPhone
Platform: iPhone OS
OS: 10.0
ID: 5B9E5085-3A72-48F6-BCB9-CC0403A7ED8D

Locale: en
Region: gb

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.87.14 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.39 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.32 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.6 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.67 Enabled=YES
- annoyances at my end

**Comment by Alex-302** [comment]
Что заблокировано ошибочно?

**Comment by evgeniy-ADG** [comment]
Dropdown lists do not work, they do not drop, actually ;)

**Comment by Alex-302** [comment]
I can't reproduce it. Which filter causes it on you device?

**Comment by evgeniy-ADG** [comment]
It's weird, but can it by Spyware filter?

**Comment by Alex-302** [comment]
Yes. You can try to check without it. Or provide me remote access.

**Comment by evgeniy-ADG** [comment]
I did, and it seems to work fine.

**Comment by Alex-302** [comment]
Ok. Then I need access.

**Comment by evgeniy-ADG** [comment]
It's on iPad. Let's schedule it for Monday.

**Comment by Alex-302** [comment]
Ok
