### ISSUE TITLE
http://cwer.ws/node/413432/ - fake download button

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2769]
http://cwer.ws/node/413432/

![image](https://cloud.githubusercontent.com/assets/15856304/17479486/732ad882-5d7b-11e6-9562-7444fb1156b4.png)
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17479494/7cc1932c-5d7b-11e6-9d5c-a6e09d4bf79e.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
cwer.ws##a[href*="http://torr.mediaget.com/"] 

```
