### ISSUE TITLE
http://fanserials.tv/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2770]
**Description**:
Возможно убрать такие блоки на страницах? Просьба от пользователя
+ http://fanserials.tv/
<details>
![screenshot_71](https://cloud.githubusercontent.com/assets/18548949/17487146/389e09ac-5d9c-11e6-816a-56f536301296.jpg)
</details>

+ http://fanserials.tv/supernatural/
<details>
![screenshot_70](https://cloud.githubusercontent.com/assets/18548949/17487113/160b316c-5d9c-11e6-9905-e5912155e75b.jpg)

</details>
+ http://fanserials.tv/10761-sverhestestvennoe-11-sezon-19-seriya-the-chitters.html

<details>
![screenshot_69](https://cloud.githubusercontent.com/assets/18548949/17487069/ef2c0e72-5d9b-11e6-9127-422525449a2f.jpg)
</details>

**Filters list**: 1,2,3,4,14

**Browser**: Хром, Firefox

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Возможно, но не нужно. Опасные правила получаются, а смысл мало.
Помощник с этим справится.
