### ISSUE TITLE
piratepc.net [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#27715]
**Site**: https://piratepc.net/netbalancer-crack/

**Issue**: Fake links to be removed from the top, middle and bottom of the page as seen in the screenshots.

**Screenshot**: http://prntscr.com/m1lnlx  and   http://prntscr.com/m1lnta   and   http://prntscr.com/m1lnx0

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 71.0.3578.98 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by krystian3w** [comment]
`piratepc.net##a[href="javascript:void(0);"]` :question:
