### ISSUE TITLE
walla.co.il breaks completely with adguard extension

### ISSUE THREAD

**Issue by dorlev2** [AdguardTeam/AdguardFilters#27711]
Hi,
I'm thinking about purchasing adguard but at first i downloaded the adguard extenstion for chrome with this filter lists:
AdGuard Base filterVersion 2.0.26.2. Updated 31 december 2018 at 10:30.
EasyListVersion 2.0.22.41. Updated 31 december 2018 at 11:00.
Peter Lowe's listVersion 2.0.1.92. Updated 28 december 2018 at 17:02.
AdGuard Spyware filterVersion 2.0.5.15. Updated 29 december 2018 at 23:02.
AdGuard Social Media filterVersion 2.0.7.79. Updated 30 december 2018 at 02:02.
EasyList HebrewVersion 2.0.1.36. Updated 30 december 2018 at 17:00.

and "Walla.co.il" is completely broken! , how can i fix that?

**Comment by krystian3w** [comment]
What do you mean by complete corruption (breaks)?

**Comment by krystian3w** [comment]
Try open "Filtering log":

 * right click on site :arrow_right:  "AdGuard AdBlocker" :arrow_right: "filtering report"

Clear logger few times and click refresh / reload site. Now check only "blocked"

![image](https://user-images.githubusercontent.com/35370833/50558760-13c77080-0cf1-11e9-88db-0694c7657479.png) |
--- |

Maybe someone from such a log will find a faulty filter.


With me, the page has been loaded and the entire content does not disappear.

```
AdGuard Base filterVersion 2.0.26.3. Updated 31 december 2018 at 11:30.
EasyListVersion 2.0.22.41. Updated 31 december 2018 at 10:00.
Peter Lowe's listVersion 2.0.1.92. Updated 28 december 2018 at 16:02.
AdGuard Spyware filterVersion 2.0.5.15. Updated 29 december 2018 at 22:02.
AdGuard Social Media filterVersion 2.0.7.79. Updated 30 december 2018 at 01:02.
EasyList HebrewVersion 2.0.1.36. Updated 30 december 2018 at 16:00.
```

**Comment by krystian3w** [comment]
![image](https://user-images.githubusercontent.com/35370833/50559082-b84ab200-0cf3-11e9-87df-4f36bee7da76.png)

**Comment by dorlev2** [comment]
Here is mine : https://imgur.com/a/dki7GvF

**Comment by krystian3w** [comment]
As much as manually deactivated the filters, it is perhaps guilty filter some kind of a "cryptocopier" on this page block.

**Comment by dorlev2** [comment]
@krystian3w  Ok so i have used the logger to whitelist some rules and if use those whitelist filters:
@@||walla.co.il^$domain=walla.co.il,csp
@@||walla.co.il^$domain=walla.co.il,csp
@@$domain=walla.co.il,third-party,webrtc,websocket

the website is working as expected.

The weird part is that those filters exist in adblock plus and ublock so why does this happens only on adguard?

**Comment by krystian3w** [comment]
> The weird part is that those filters exist in adblock plus and ublock so why does this happens only on adguard?

I have no idea, a bit too heavy topic for me.

**Comment by Alex-302** [comment]
@dorlev2 which filter causes it?

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/51208329-9feeb000-190d-11e9-9f9f-6a04d653e48c.png) |
--- |

`*$webrtc,domain=walla.co.il`
```
||walla.co.il^$csp=script-src 'self' * blob: data: 'unsafe-inline',domain=animals.walla.co.il|b.walla.co.il|buzzit.walla.co.il|cars.walla.co.il|celebs.walla.co.il|e.walla.co.il|elections.walla.co.il|fashion.walla.co.il|finance.walla.co.il|food.walla.co.il|healthy.walla.co.il|home.walla.co.il|judaism.walla.co.il|mag.walla.co.il|movies.walla.co.il|nadlan.walla.co.il|news.walla.co.il|sports.walla.co.il|tags.walla.co.il|tech.walla.co.il|travel.walla.co.il|tv-guide.walla.co.il|viva.walla.co.il|vod.walla.co.il|weather.walla.co.il|www.walla.co.il
```

And maybe:

```
||walla.co.il^$websocket,~third-party,domain=6days.walla.co.il|animals.walla.co.il|astrology.walla.co.il|b.walla.co.il|buzzit.walla.co.il|calendar.walla.co.il|cars.walla.co.il|celebs.walla.co.il|e.walla.co.il|elections.walla.co.il|euro.walla.co.il|fashion.walla.co.il|finance.walla.co.il|food.walla.co.il|forums.walla.co.il|fun.walla.co.il|healthy.walla.co.il|home.walla.co.il|judaism.walla.co.il|kids.walla.co.il|mag.walla.co.il|maps.walla.co.il|milon.walla.co.il|movies.walla.co.il|mundial.walla.co.il|nadlan.walla.co.il|news.walla.co.il|nick.walla.co.il|olympics.walla.co.il|search.walla.co.il|sports.walla.co.il|tags.walla.co.il|tech.walla.co.il|translate.walla.co.il|travel.walla.co.il|tv-guide.walla.co.il|tv.walla.co.il|usaelections.walla.co.il|viva.walla.co.il|vod.walla.co.il|weather.walla.co.il|www.walla.co.il
```

**Comment by Alex-302** [comment]
please check `@||walla.co.il^$csp`
