### ISSUE TITLE
RU AdList blocks Yandex Zen in Yandex browser v. 18.11.2.501

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#27713]
The said filter is reportedly interfering with the Yandex Zen service. 

With AdGuard enabled: [link](https://uploads.adguard.com/Screenshot_2018-12-31-13-44-52-718_com.yandex.browser.alpha.png_10802160_12-31-13-13.png)
And disabled: [link](https://uploads.adguard.com/Screenshot_2018-12-31-13-43-05-286_com.yandex.browser.alpha.png_10802160_12-31-13-14.png)

ID: 1641676
AdGuard 3.0.166

**Comment by Alex-302** [comment]
we can't change that filter.
