### ISSUE TITLE
http://tubevintageporn.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2771]
**Description**:
http://tubevintageporn.com/uk/
Скрытая реклама внизу справа

Screenshot:
<details>
![screenshot_72](https://cloud.githubusercontent.com/assets/18548949/17487399/4acb494a-5d9d-11e6-960e-a2c73edb3502.jpg)

</details>

**Filters list**: 1,2,3,4,14

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в англ фильтр
```
||tubevintageporn.com/js/show_adv.js

```

**Comment by evgeniy-ADG** [comment]
нужно заблокирoвать еще рекламу в плеере: <details>
![screen shot 2016-08-11 at 11 20 13 am](https://cloud.githubusercontent.com/assets/15856304/17582679/abcc2fd8-5fb5-11e6-9aca-f96996ea226c.png)

**Comment by Alex-302** [comment]
Добавил в англ фильтр
```
tubevintageporn.com###invideo_new

```
