### ISSUE TITLE
mail.ru is broken in Safari

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#27712]
![image](https://user-images.githubusercontent.com/15856304/50558886-3b6f0680-0cfa-11e9-9d85-2896cb232c76.png)

OS: 10.14.2
Browser: Safari 12.0.2
Filters: Base, Safari, Russian, Spyware, 
HTTPS: on
Extensions: none

**Comment by Alex-302** [comment]
не повторяется
