### ISSUE TITLE
[Android] Daily Mail App doesn't work

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#2772]
https://play.google.com/store/apps/details?id=com.dailymail.online&hl=en
All videos in Daily Mail app doesn't play on the latest beta (v2.7.211). The problem solves by disabling filters. Also it does not reproduce on the previous beta.

https://forum.adguard.com/index.php?threads/adguard-for-android-release-candidate-v2-7-211.11930/page-2#post-94710 - Original thread

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||imasdk.googleapis.com/native/core/$app=com.dailymail.online
@@||imasdk.googleapis.com/native/sdkloader/native_sdk_$app=com.dailymail.online
```
