### ISSUE TITLE
[adblock detect] mamadu.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#27739]
@AdamWr 

**Site Sample** | 
-----------------------------|
https://mamadu.pl/140337,sklad-popularnej-szynki-z-misiem-wola-o-pomste-do-nieba-eksperci-alarmuja

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Chrome Stable x64
AdGuard version:                       | **6.4.1840.4955**
Stealth mode:					       | **disabled**

| Filters enabled |
|-----------------|
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| CoinBlockerLists
| EasyList Polish 
| Fanboy's Annoyances
| Fanboy's Enhanced Tracking List 
| Fanboy's Social Blocking List 
| I don't care about cookies
| KAD - fraud/scam 
| Malware Domains
| NoCoin Filter List 
| Peter Lowe's List
| Polish Annoyances
| Polish Main
| Polish Social

### Issue:

Adblock detect

<details><summary><b>Screenshot:</b></summary>

![scr-1546333760-001](https://user-images.githubusercontent.com/9846948/50571539-87c74e80-0dad-11e9-9ad1-723674c330c0.png)

</details><br/>

**Comment by krystian3w** [comment]
`#%#AG_abortInlineScript(/adBlock/, 'parseInt');` dalej działa, więc pewnie wystarczy dopisać domenę.
