### ISSUE TITLE
Adguard Assistent drive.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2773]
Не появляется помощник на drive.ru и есть реклама Mitsubishi на фоне.

![2016-08-08_22-55-27](https://cloud.githubusercontent.com/assets/16462533/17494222/6ee179f2-5dbc-11e6-9388-ab875d5dae64.png)

Фильтры:

Пользов.
Англ.
Русский
Фильтр счетчиков
Экспериментальный
Раздражителей

**Comment by Alex-302** [comment]
Не инжектимся.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardForWindows/issues/1222
