### ISSUE TITLE
krone.at

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#2774]
Блокируются увеличенные фотографии в статьях (по клику). С включенным Adguard при клике на фото ничего не происходит.

Проверял в последнем стабильном Chrome, Win10
Похоже что блокируется правилом из **Spyware filter**

пример:
http://www.krone.at/welt/tuerkei-konflikt-koennte-zu-uns-ueberschwappen-erdogan-gegner-story-523771

скрины (Adguard выключен):

![2016-08-08 23 09 28](https://cloud.githubusercontent.com/assets/17472907/17494642/470152fc-5dbe-11e6-8e98-9f03c3a0c056.png)
![2016-08-08 23 09 35](https://cloud.githubusercontent.com/assets/17472907/17494641/46fc5496-5dbe-11e6-8126-0ce2a2e8704a.png)

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||dispatcher.oewabox.at^$domain=krone.at
```
