### ISSUE TITLE
http://www.calciomercato.com/ - anti-adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2775]
http://www.calciomercato.com/news/pogba-day-live-oggi-visite-e-annuncio-ufficiale-con-il-mancheste-802307
![screen shot 2016-08-09 at 9 42 35 am](https://cloud.githubusercontent.com/assets/15856304/17506979/ad96ca86-5e15-11e6-9905-6ed661dd928c.png)

eng, spyware, socail, russian

**Comment by Alex-302** [comment]
Added to English filter
```
@@||adv.calciomercato.com/*banner*?
```

**Comment by evgeniy-ADG** [comment]
It's back!

![screen shot 2016-08-17 at 10 49 51 am](https://cloud.githubusercontent.com/assets/15856304/17728496/2dd59396-6468-11e6-9296-8e10f504779b.png)

**Comment by Alex-302** [comment]
Fixed

**Comment by Bohdan-SUP** [comment]
Happens again:
![screen shot 2016-09-09 at 5 14 19 pm](https://cloud.githubusercontent.com/assets/14153331/18390515/26d43a9a-76b3-11e6-845c-bd2e727a12d5.png)

**Comment by Alex-302** [comment]
fixed

**Comment by marc134** [comment]
This site 'calciomercato(dot)com' is blocking the adblocker again. They are consistently fighting to block adblockers. Everytime I find that they are blocking the adblocker, I will reopen this thread.

http://www.calciomercato.com/news/manchester-united-manchester-city-live-290327
