### ISSUE TITLE
com.todoist app doesn't work

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2776]
If Adguard is enabled, the App named 'Todoist', doesn't work (todo list
items don't load - keep seeing spinnig wheel).
If your app is disabled, it works as normal (todo items load).

**https://play.google.com/store/apps/details?id=com.todoist&hl=en**

<details>
"enabledFilterIds" : [ 2, 3, 4, 8, 11 ],
"environment" : "prod",
"filteringQuality" : "SPEEDY",
ssl: null

**Comment by evgeniy-ADG** [comment]
Waiting for details

**Comment by PeterDeKeer** [comment]
I tested them all, it's the Spyware Filer and the Social Media Filter that keep it from working correctly...

**Comment by evgeniy-ADG** [comment]
@PeterDeKeer Thank you!

**Comment by Alex-302** [comment]
@PeterDeKeer could you write step-by-step description with screenshots? I don't understand what I need do there.
