### ISSUE TITLE
http://www.today.it/ an

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2777]
http://www.today.it/media/bianca-berlinguer-addio-tg3.html
![screen shot 2016-08-09 at 10 56 27 am](https://cloud.githubusercontent.com/assets/15856304/17508894/f647604c-5e1f-11e6-8d17-41851c1a0c19.png)

And somewhere on this site there should be cookie notification missed.

**Comment by Alex-302** [comment]
Added to English filter
```
today.it#%#(function(){var a={debug:{set:function(){return a}},on:function(b,c){b||setTimeout(function(){c()},1);return a},onDetected:function(b){return a.on(!0,b)},onNotDetected:function(b){return a.on(!1,b)},check:function(){}};Object.defineProperty(window,"fuckAdBlock",{get:function(){return a}})})();
```
Added to Safari filter
```
@@||today.it^$generichide
```
