### ISSUE TITLE
http://m.beautypageants.in/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2778]
http://m.beautypageants.in/blocked.cms
![screen shot 2016-08-09 at 1 57 42 pm](https://cloud.githubusercontent.com/assets/15856304/17514073/484c61ee-5e39-11e6-8a7b-efe3719e7ed5.png)

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.90.92 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.13 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.39 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.89 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.4.50 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.7 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES

**Comment by Alex-302** [comment]
Can't reproduce.
This link is a dummy:
http://m.beautypageants.in/blocked.cms

**Comment by evgeniy-ADG** [comment]
It's old good indiatimes.com...

**Comment by Alex-302** [comment]
Nothing here
http://www.indiatimes.com/sports/rio-olympics/rio-olympics-despite-ripping-her-suit-nepal-s-13-year-old-swimmer-gaurika-singh-wins-her-heat-259589.html

**Comment by worldsdream** [comment]
http://m.beautypageants.in

Click on a blog post. You get anti adblock

I can confirm. 

English, dutch, annoyance, safari, mobile

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||m.beautypageants.in^$generichide
```
Added to Social filter
```
m.beautypageants.in##.social-icons
```
