### ISSUE TITLE
http://prefiles.com/ - pop-up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2780]
http://prefiles.com/krshgs3mjx0m/The_Official_Ubuntu_Book.epub

![screen shot 2016-08-09 at 2 07 22 pm](https://cloud.githubusercontent.com/assets/15856304/17514319/a150c068-5e3a-11e6-9cc9-030439dadd07.png)

<details>
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.39 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.7.18 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.44 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.8 Enabled=YES
ID=101 Name="EasyList" Version=1.0.61.41 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.63.46 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.63.15 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.63.17 Enabled=YES

**Comment by Alex-302** [comment]
Added to Safari filter
```
||wrmcfyzl.com^
```
@evgeniy-ADG please check after filters update.

**Comment by evgeniy-ADG** [comment]
Seems to be fine now.
