### ISSUE TITLE
Add New List-KR filter list

### ISSUE THREAD

**Issue by ptrkr** [AdguardTeam/AdguardFilters#27813]
[List-KR](https://github.com/List-KR/List-KR) is a web filter for websites in Korean language. This filter aims to filter not only ads, but also known trackers and other scripts which negatively affects user experience. SlowMemory, a original contributor, has deleted all his projects suddenly. As a result, Old List-KR filter have obsoleted in AdGuard configuration UI. So i have recreated this project repository for continued development.

Would you please add this list so it is available in the AdGuard configuration UI and can be enabled by users via a checkbox in the usual filter selection settings screen, and remove '(Obsolete) List-KR' filter?

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersRegistry
