### ISSUE TITLE
Anti-adblock

### ISSUE THREAD

**Issue by Samuel12321** [AdguardTeam/AdguardFilters#27818]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
Anti-adblocking script covers page and asks to whitelist site www.makeuseof.com
![annotation 2019-01-03 173659](https://user-images.githubusercontent.com/35312698/50623794-43d77380-0f7e-11e9-867e-fe3e5ac7c700.jpg)

* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**
- Base filter
- spyware filter
- easy privacy
- social mediafilter
- AdGuard Annoyances filter
- Fanboy's Annoyances
- Adblock Warning Removal List
- (Obsolete) Anti-Adblock Killer | Reek

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 version 1809
Browser:                               |Chrome
AdGuard version:                       | 2.10.14
Filters enabled:                       | ?
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | none

**Comment by krystian3w** [comment]
I cannot reproduce, maybe disable `(Obsolete) Anti-Adblock Killer | Reek` help...

**Comment by Samuel12321** [comment]
Sorry, just realised i had adblock plus accidentally enabled as well, turning it off resolved the problem.
