### ISSUE TITLE
http://m.biquge.com.tw - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2783]
http://m.biquge.com.tw/wapbook/11687_7354696.html

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.90.31 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.95 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.23 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.2.26 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.90 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.41 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.96 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.62.90 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES

![screen shot 2016-08-10 at 12 21 00 pm](https://cloud.githubusercontent.com/assets/15856304/17548545/0461cd0e-5ef5-11e6-96e8-d6ca69e0ee5b.png)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||xxhrd.com/ns.php?p=
```

**Comment by evgeniy-ADG** [comment]
http://m.biquge.la/book/11896/8219434.html


<details>
Application version: 1.0.8.54
Application lifetime: 2016-03-09 23:09:36 +0000

Device: iPhone
Platform: iPhone OS
OS: 10.0.1
ID: 29D252D0-71AA-4050-8769-284866918DB0

Locale: zh
Region: cn

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.95.67 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.77 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.98 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.94 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.40 Enabled=YES
ID=101 Name="EasyList" Version=1.0.63.10 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.66.47 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.1.70 Enabled=YES

![image1 1](https://cloud.githubusercontent.com/assets/15856304/18918213/c22db3ce-85a2-11e6-9238-d822dcc055f6.png)
![image2](https://cloud.githubusercontent.com/assets/15856304/18918216/c3c0f9a8-85a2-11e6-9089-ead1669acf6c.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG в пользовательском проверял? У меня чисто.
