### ISSUE TITLE
http://fast-torrent.ru/new/all/ - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2784]
http://fast-torrent.ru/new/all/

![screen shot 2016-08-10 at 1 23 23 pm](https://cloud.githubusercontent.com/assets/15856304/17550451/ba4ae27e-5efd-11e6-9f4a-c442cf89e31f.png)

Basic filters + annoyances + spanish + german and dutch

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||altpubli.com^$third-party
fast-torrent.ru##a[href^="http://lblinks.net/aff/"]

```

**Comment by vgavrish** [comment]
Реклама вверху и побокам на белом фоне если нажать, то появляется в новом окне другой сайт
Хром. Ф: 1,2,3,4,14
![image](https://cloud.githubusercontent.com/assets/18548949/20455131/de359eb4-ae5c-11e6-8b8b-a7c1d53d7c26.png)

**Comment by Alex-302** [comment]
поправил

**Comment by vgavrish** [comment]
Снова реклама в вверху и на фоне главной страницы
Хром
Ф: 1,2,3,4,14
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20859011/720c3522-b95b-11e6-85a9-90672e628b91.png)

**Comment by Alex-302** [comment]
Чисто и с прогой и с расширением.
