### ISSUE TITLE
americatv.com.ar - broken video player

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2787]
**Description**:
http://www.americatv.com.ar/vivo

**Screenshot:**
![america tv la vida en vivo 2016-08-10 20-39-08](https://cloud.githubusercontent.com/assets/5947035/17564009/85bf12ea-5f3a-11e6-99bc-094e8f77f85d.png)

**Comment by Alex-302** [comment]
Added to Safari and Spanish filters
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=vmf.edge-apps.net|americatv.com.ar
```
