### ISSUE TITLE
PBTeen.com needs unblocked on AdGuard DNS: Family

### ISSUE THREAD

**Issue by davidbdeath** [AdguardTeam/AdguardFilters#27886]
https://www.pbteen.com is blocked by adguard DNS

* **Expected behaviour**: 

PBteen (pottery barn teen) should not be flagged as adult content.

Information                            | Value
---                                    | ---
Operating system: All things on my network iOS/MacOS/Windows                     | ?
Operating system version (Latest) | ?
Browser:                               Safari
AdGuard version:                AdGuard DNS: Famly Protection
AdGuard DNS:                     Family Protection

https://www.pbteen.com was blocked and shouldn't be.
I guess @@||pbteen.com^ is needed.

**Comment by Alex-302** [comment]
@davidbdeath not reproduced. Please check again.
