### ISSUE TITLE
Adguard не  заблокировал рекламу в приложении

### ISSUE THREAD

**Issue by aefimov69** [AdguardTeam/AdguardFilters#2790]
**Description**:
Купил полную лицензию. Пробовал и с VPN и с сертификатом в приложении
https://play.google.com/store/apps/details?id=com.vladyud.balance
не блокируется реклама.
<details>
![screenshot_2016-08-11-16-49-34](https://cloud.githubusercontent.com/assets/20969799/17588267/1ae82cce-5fe7-11e6-9396-9152c40e1042.png)
![screenshot_2016-08-11-16-49-51](https://cloud.githubusercontent.com/assets/20969799/17588271/234b21a0-5fe7-11e6-95d2-889d1bcc975d.png)
![screenshot_2016-08-11-16-50-14](https://cloud.githubusercontent.com/assets/20969799/17588272/269dba70-5fe7-11e6-9f0e-484f6e823a8d.png)
</details>

**Current behaviour**: Tell us what happens

Screenshot: use the following code
```
<details>
![](http://somehosting.com/adg_on.jpg)
</details>
```

**Expected behaviour**: Tell us what should happen instead

Screenshot:
```
<details>
![](http://somehosting.com/adg_off.jpg)
</details>
```

**Steps to reproduce the problem**:

* 
*  
*  

**Adguard version**:

**Filters list**:

**Operating system**:

**Browser**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
@aefimov69 Могли бы уточнить, включена ли фильтрация HTTPS и какой алгоритм фильтрации активирован в Настройки - Расширенные, Качественный или Быстрый? Какие фильтры используете?

**Comment by aefimov69** [comment]
Так на скринах все есть. Быстрый. свои фильтры не включал. Пока еще не  знаю даже  как это сделать.

**Comment by evgeniy-ADG** [comment]
А если переключиться с быстрого на Качественный?

**Comment by evgeniy-ADG** [comment]
Про HTTPS ничего на скринах на нашел. Зайдите в Настройки - Фильтрaция HTTPS и включите.

**Comment by Alex-302** [comment]
@aefimov69 
не игнорируйте шаблон. Он создан для облегчения создания задач.

**Comment by Alex-302** [comment]
Повробуйте остановить приложение в настройках Андроида и очистить кэш.

**Comment by aefimov69** [comment]
Я первый раз делал ишью на данном сайте, вроде бы все  рекомендации с 4pda соблюл. Простите если, что не так.

**Comment by Alex-302** [comment]
Если не поможет, переключите в расширенных настройках уровень логирования на "Записывать HTTP запросы", остановите это приложение и запустите снова. Потом извлеките его и приложите здесь. Места, где может храниться лог:
```
/storage/emulated/Android/data/com.adguard.android/cache/log
/sdcard/Android/com.adguard.android/cache/log или
/sdcard/data/Android/com.adguard.android/cache/log или
/sdcard/Android/data/com.adguard.android/
```

**Comment by Alex-302** [comment]
> Я первый раз делал ишью на данном сайте, вроде бы все рекомендации с 4pda соблюл. Простите если, что не так.

с шаблоном меньше писать, и скрыны под спойлер убираются. Если скринов много, можно просто скопировать нужное количество раз код и вставлять адрес картинки
```
<details>
![](http://somehosting.com/adg_on.jpg)
</details>
```

**Comment by aefimov69** [comment]
вот лог файл. постарался убрать под спойлер.
<details>
[adguard.txt](https://github.com/AdguardTeam/AdguardFilters/files/413242/adguard.txt)
</details>

**Comment by Alex-302** [comment]
Спасибо.
Судя по логу сторонняя реклама блокируется.
Очистка кэша этого приложения не помогла?
Попробуйте остановить её и запустить при выключенном интернете. Если появится - значит встроена. Но у меня всё чисто.

**Comment by aefimov69** [comment]
Не знаю, что помогло, но  хронология такая. Вчера вечером почистил кэш программы. Перегрузил устройство полностью. Проверил реклама есть в приложении. Утром сегодня  проверил. в Приложении рекламы нет, а Adguard "последнее обновление" было  ночным. Сейчас в этом приложении  рекламы нет. Спасибо. Можно закрывать.
