### ISSUE TITLE
http://de.sputniknews.com - can't scroll images with Adguard on.

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#2791]
http://de.sputniknews.com/bilder/20160810/312046943/russland-internationale-armeespiele-pioniertruppen.html

*Tested on Lenovo S860
*Adguard 2.7
*HTTPS filtration on.
*Attaching screens won't show the issue.
*Here's the problem area <details>
![image](https://cloud.githubusercontent.com/assets/20476168/17593644/489a6d64-5fef-11e6-8855-48cb7f138dea.png)

**Comment by evgeniy-ADG** [comment]
@Fridrix use <details> ... </details> for huge images and longreads, do not post full links to the header. What about filters, filtering methods and so on?

**Comment by Alex-302** [comment]
Added to Social filter
```
@@||sputniknews.com/min/js/plugins/social-likes.min.js
```
Please check it
