### ISSUE TITLE
ru.investing.com - anti-adblock script

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2792]
**Description**:
http://ru.investing.com/commodities/brent-oil-streaming-chart

Я на сайт захожу с 3 компьютеров. С XP гугл хром, с ios Маверик, с ios Capitan.
Отключаю все фильтры Adguard, сайт работает. Затем автоматом подключается английский фильтр и уже при повторном обновлении страницы сайт не работает. Т.е. отключены все фильтры, кроме английского. 

Затем выходит сообщение - Мы заметили, что вы используете блокировщик рекламы.
Повторюсь, что сайт работал не далее, как неделю назад. На всех 3 компьютерах. 

Скрины с проблемой и настройками:
<details>
![screenshot_75](https://cloud.githubusercontent.com/assets/18548949/17613387/5a20fd34-6065-11e6-9026-243d6e7236fc.jpg)
![screenshot_76](https://cloud.githubusercontent.com/assets/18548949/17613388/5a24d8c8-6065-11e6-842d-2463a065e357.jpg)
</details>

Пользователь согласен на teamviewer. У меня не повторяется.
При подключении Фильтра раздражителей проблема не уходит.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
И у меня. Другой пользователь пишет, что помогает отключения англ. фильтра, детектится именно он.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
не удаётся повторить. Нужен удалённый доступ.

**Comment by evgeniy-ADG** [comment]
@vbagirov хотят ТВ, напиши своему кастомеру, может. У меня все чисто и красиво.

**Comment by vgavrish** [comment]
@Alex-302 
назови плиз время по teamviewer
пользователь согласен

**Comment by Alex-302** [comment]
@vgavrish 
В будние в течение дня.

**Comment by vgavrish** [comment]
@Alex-302 
завтра в 9-30 мск
<details>
816 829 641
pe5k24

**Comment by Alex-302** [comment]
@vgavrish 
ок, будильник завёл)

**Comment by Alex-302** [comment]
@vgavrish 
пароль устарел

**Comment by vgavrish** [comment]
"На 17-00 мск сегодня перенесем сеанс"
пароль должен сюда же написать

**Comment by 2286** [comment]
z442fd 17-00 мск

**Comment by Alex-302** [comment]
Добавил;
```
investing.com#$##abPopup { display: none!important; }
investing.com#$#body { overflow: visible!important; }
```
