### ISSUE TITLE
missed ads ufa.rbc.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2793]
Повторилось при первоначальной загрузки страницы.

![img_0729](https://cloud.githubusercontent.com/assets/16462533/17621977/0da761a6-60a0-11e6-90b9-15b31cca037c.PNG)

**Версия iOS: 9.3.4**
**Фильтры:**

> Английский
> Фильтр счетчиков и систем аналитики
> Экспериментальный
> Фильтр раздражителей
> Русский
> Для Safari

**Comment by Alex-302** [comment]
Не получается повторить в Сафари.
@vozersky глянь на айпаде.

**Comment by heru12343** [comment]
![default](https://cloud.githubusercontent.com/assets/21025096/17650714/4349ebc6-625d-11e6-9971-9d7a5110d2e6.jpg)

**Comment by vozersky** [comment]
у меня с этими фильтрами не повторилось

**Comment by heru12343** [comment]
Это на ПК и виндовс, у меня помимо указанных выше фильтров стоят еще RU Adlist, EasyPrivacy, Anti-Adblock Killer| reek, Пользовательский.

**Comment by vozersky** [comment]
попробуйте отключить RU Adlist, EasyPrivacy,  Пользовательский.

посмотрите, нет ли у вас в C:\ProgramData\Adguard\NetworkTemp\SSL файлов x.db, xtls.db, xv.db?

**Comment by heru12343** [comment]
Помогает убрать данную рекламу отключение Пользовательского фильтра, но без него появляется куча рекламы на данном сайте http://kolomna-spravka.ru/

**Comment by vozersky** [comment]
@heru12343 В Пользовательском находятся правила, которые вы создали самостоятельно, либо через инструмент для ручной блокировки. Видимо проблема в каком-то из них. Попробуйте удалить из Пользовательского все правила для домена rbc.ru.

**Comment by heru12343** [comment]
В данной папке нашел и удалил только файлы x.db, xtls.db

**Comment by heru12343** [comment]
Все нормально, проблема решилась отключением в Пользовательском фильтре все правила для сайта rbc.ru. Спасибо.

**Comment by vozersky** [comment]
@heru12343 Не за что. Я так понял, что изначальная проблема с iOS, которая обсуждается в этой issue - это не ваша?

@Serzh-SUP была уже уже issue по rbc, можно было новую не создавать #2540

**Comment by heru12343** [comment]
с iOS не моя, мне пришлось тут написать так как моя уже давно закрыта

**Comment by vozersky** [comment]
@heru12343 понятно, спасибо

**Comment by Alex-302** [comment]
> с iOS не моя, мне пришлось тут написать так как моя уже давно закрыта

В закрытых возможноть писать остаётся. Комментирование не запрещаем. Проблемы разных пользователей в одну лучше не смешивать, чтоб небыло недопонимания.
