### ISSUE TITLE
http://medovoemesto.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2794]
**Description**:
http://medovoemesto.ru/pcheloprodukty/pyltsa/sosny.html
Реклама в статье и в конце статьи

Screenshot:
<details>
![screenshot_78](https://cloud.githubusercontent.com/assets/18548949/17641942/a98a83cc-613c-11e6-8093-4b7257106486.jpg)
![screenshot_79](https://cloud.githubusercontent.com/assets/18548949/17641943/a98a986c-613c-11e6-8a16-f77a98f40799.jpg)
</details>

**Filters list**: 1,2,3,4,14

**Browser**: Опера

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||riverlead.ru^$third-party

```
