### ISSUE TITLE
craftmybox.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#27944]
`https://craftmybox.com/processadores`

Sponsored row (marked as "Anúncio" in this screenshot):

![sponsored](https://user-images.githubusercontent.com/35470489/50736147-c50e5080-11a0-11e9-8643-dce5391d5890.png)

AdGuard base filters + spa,por list
uBlock Origin

**Comment by adranger** [comment]
@AdamWr this now redirects to a new domain:  [https://meupc.net/memorias](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://meupc.net/memorias)

![anúncio](https://user-images.githubusercontent.com/35470489/108124874-71140c80-7086-11eb-9b71-11a9e0609366.png)

**Comment by AdamWr** [comment]
Fixed.
