### ISSUE TITLE
techspot.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#27945]
`https://www.techspot.com/review/1635-amd-wraith-coolers-compared/`

Long ad in the middle of the article:

![ad](https://user-images.githubusercontent.com/35470489/50736180-4d8cf100-11a1-11e9-811e-43ec1746fcbc.png)

Adguard Base Filters
Firefox 64.0
uBlock Origin 1.17.4

**Comment by THEtomaso** [comment]
Fix:
`techspot.com##[data-hide="#ad_rectangle"]`

**Comment by Alex-302** [comment]
I don't see this element.

**Comment by THEtomaso** [comment]
@ Alex-302:
The ad container is still there, because the rule that I created shows up in uBO's logger when i visit the page.
It's probably just not used at the moment.

**Comment by adranger** [comment]
>It's probably just not used at the moment.

Yes, that element is still in their source, even though it's currently not being used.

**Comment by adranger** [comment]
`<div style="display:none;" class="tshoop" data-type="zadbl_news_single" data-hide="#ad_rectangle"></div>`

https://gist.github.com/adranger/c7ecf1af3dcddd749b101c2154a94541

**Comment by krystian3w** [comment]
`style="display:none;"` so hidden by webmaster?

**Comment by adranger** [comment]
That's what THEtomaso and I said before. It _is_ empty.

**Comment by THEtomaso** [comment]
Also, there is this one:
`techspot.com##[id="billboard_placeholder"]`
..but I haven't actually seen it used.
