### ISSUE TITLE
prostoporno.me

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2795]
**Description**:
http://prostoporno.me/videos/128277/
При нажатии в любую область экрана открывается фишинговый сайт

Screenshot:
<details>
![screenshot_81](https://cloud.githubusercontent.com/assets/18548949/17642107/70bee5e6-6142-11e6-9fe3-43e2f5d0589b.jpg)
</details>

**Filters list**: 1,2,3,4,14

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||prostoporno.me/exads/
prostoporno.me#@#.adv_2

```
