### ISSUE TITLE
https://globoplay.globo.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2796]
**Description**:
Проблема на сайте с воспроизведением видео
https://globoplay.globo.com/v/5220227/

При нажатии на play видео, нет загрузки. Т.е. висит видео, не играет и также нет плеера.
Помогает отключение Английского фильтра

Screenshot:
<details>
![screenshot_82](https://cloud.githubusercontent.com/assets/18548949/17642381/81b3c056-614c-11e6-9ead-4448c8e2bfe1.jpg)
</details>

**Steps to reproduce the problem**:
Также есть приложение, в котором наблюдается такая же проблема:
https://play.google.com/store/apps/details?id=com.seazon.feedme&hl=pt_BR
- Ссылки на добавление подписки в приложение
  http://globotv.globo.com/rede-globo/fantastico/feed.atom
  http://www.inoreader.com/?lang=pt_BR

У нас не отображается видео в приложении. Наверное необходим португальский айпи. Логи спросили.

**Adguard version**: 2.7.220

**Filters list**: 1,2,3,4,11,14

**Browser**: Хром

**Comment by Alex-302** [comment]
Добавил в английский фильтр
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=globoplay.globo.com
```
Нужно чтоб юзер проверил и отписался.
