### ISSUE TITLE
Amazon ads appearing in Safari using AdGuard

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#27966]
@tadatildy commented on [Fri Jan 04 2019](https://github.com/AdguardTeam/AdGuardForSafari/issues/121)

**Steps to reproduce**

1. Open Safari with AdGuard as the only extension enabled, with AdGuard filters from "Your environment" below
2.  Go to https://www.cnet.com/reviews/apple-iphone-xr-2018/
3.  Scroll to near bottom of page

**Expected behavior**

No native Amazon ads should appear.

**Actual behavior**

Amazon ads appear.

**Screenshot:**

<img width="974" alt="amazon_ads" src="https://user-images.githubusercontent.com/37007448/50673431-9e3af900-0fab-11e9-93ac-47e295509ae1.png">

**Details/comments:**

I am seeing Amazon AdChoice ads on sites such as cnet.com.  I am requesting that they be removed automatically using AdGuard. I could block individual elements in a User filter, but I don't want to have to do that, especially when they are AdChoice ads.  I am reporting this as a bug as I don't believe they are intended to appear, especially with EasyList enabled.

**Your environment**

* AdGuard for Safari version: 1.2.0
* Environment name and version: Safari Version 12.0.2 (14606.3.4)
* Operating System: macOS Mojave 10.14.2
* Filters you use in AdGuard: AdGuard Base filter, AdGuard Spyware filter, AdGuard Social Media filter, AdGuard Annoyances filter, Malware Domains, Spam404, NoCoin Filter List, AdGuard Safari Filter
* Any other browser extensions you have installed: none that are active/enabled

**Comment by Alex-302** [comment]
It uses InstartLogic script. Hided that ad.
