### ISSUE TITLE
www.birhdfilm.org -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2797]
Site: http://birhdfilm.org/sniper-ghost-shooter-hd-izle.html

Screenshot: https://s10.postimg.org/kdel26k6x/image.png

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
birhdfilm.org###toolbar
||dailymotion.com/embed/$domain=birhdfilm.org
```
