### ISSUE TITLE
www.filmarenasi.com -Ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2798]
**Site**: http://www.filmarenasi.com/

**Screenshot**: 
![q](https://cloud.githubusercontent.com/assets/19608513/17643877/a7520134-6187-11e6-9206-028a5f1d7d09.png)

**Adguard version**: 2.4.6

**Operating system**: Windows 10

**Browser**: Google Chrome

**Filter list**:  English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Only branded background is displayed on my end.
Added to Turkish filter
```
filmarenasi.com#$#body { background: #000000 url(http://www.filmarenasi.com/wp-content/uploads/bahis.jpg) center top fixed no-repeat!important; }

```

**Comment by thislife81** [comment]
It worked 👍

**Comment by thislife81** [comment]
Please remove background ad..

**Comment by Alex-302** [comment]
check this:
```
filmarenasi.net#$##film { display: block!important; }
filmarenasi.net#$#body { background: #000000 url(http://www.filmarenasi.net/wp-content/uploads/bahis.jpg) center top fixed no-repeat!important; }
filmarenasi.net###filmoncereklam
```

**Comment by thislife81** [comment]
Great, Please add these rules/

**Comment by Alex-302** [comment]
Added
