### ISSUE TITLE
filmbizdeizlenir.com -Ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2799]
Site: http://www.filmbizdeizlenir.com/inatcilar-izle.html

Screenshot: 
![qw](https://cloud.githubusercontent.com/assets/19608513/17643891/4fdc735c-6188-11e6-9e57-3b8b67c35931.png)

Note: Firstly add this rule for background: filmbizdeizlenir.com##.yildiz-pageskin-link
2) Choose the section of "Tek Part2", and remove ad
3) Remove twitter share

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
I see only background and social button.
Added to Turkish filter
```
filmbizdeizlenir.com##.yildiz-pageskin-link
```
Added to Social filter
```
filmbizdeizlenir.com##.sosyal
```

**Comment by thislife81** [comment]
You can see the "Reklami gec" after entering the site, choose the section of "Tek part2". Look at the screenshot: 
![download 1](https://cloud.githubusercontent.com/assets/19608513/17748264/9279ffba-64c9-11e6-9a59-f6fa7a257dc4.png)

**Comment by Alex-302** [comment]
It is too fast, one second only.

**Comment by thislife81** [comment]
You choose Tek Part2?
Cause When I choose it, the ad is shown 10 seconds.
![cv](https://cloud.githubusercontent.com/assets/19608513/17835827/e4974998-678e-11e6-842c-b0b29a923d76.png)

**Comment by Alex-302** [comment]
Added to Turkish filter
```
filmbizdeizlenir.com##.tab-reklam
filmbizdeizlenir.com#$#.tab-embed { display: block!important; }
```
