### ISSUE TITLE
www.filmifullizle.org -Ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2800]
Site: http://www.filmifullizle.org/fitoor-2016-turkce-altyazili-izle.html

Screenshot: 
![c](https://cloud.githubusercontent.com/assets/19608513/17643923/7e02e53a-6189-11e6-8e75-b12e2a47fe64.png)

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Social filter
```
filmifullizle.org##a[onclick^="paylas_"]
```
