### ISSUE TITLE
www.filmizle.film -Ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2801]
Site: http://www.filmizle.film/

Screenshot: 
![d](https://cloud.githubusercontent.com/assets/19608513/17643932/f82ed72e-6189-11e6-9855-a722357c1c7b.png)

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by thislife81** [comment]
No, this annoyance is shown again when enter the site, maybe you should try to enter the site?

**Comment by Alex-302** [comment]
No, I'm not registered here. Please select it by assistant and copy a rule.

**Comment by thislife81** [comment]
Here you are

![ds](https://cloud.githubusercontent.com/assets/19608513/17835821/7d1c4bec-678e-11e6-8314-a25ad7305e1c.png)

**Comment by Alex-302** [comment]
Why don't you copy-pasted the rule?)

**Comment by thislife81** [comment]
Oh, sorry. 
Rule: filmizle.film###myModal

**Comment by Alex-302** [comment]
Thanks. Added.
