### ISSUE TITLE
http://www.filmizle.live/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2802]
Site: http://www.filmizle.live/

Screenshot:  Remove background ad
![r](https://cloud.githubusercontent.com/assets/19608513/17643940/36fbc7a0-618a-11e6-86da-83870e2903ec.png)

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
filmizle.live#$#body { background: #000000!important; }
```
