### ISSUE TITLE
www.filmizlesene.com.tr -Ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2803]
Site: http://www.filmizlesene.com.tr/keanu-6-4.html

Screenshot: 
![f](https://cloud.githubusercontent.com/assets/19608513/17643985/9a3cdcc2-618b-11e6-922d-2df1efe96dcf.png)

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
filmizlesene.com.tr##iframe[src^="http://goo.gl/"]
```
