### ISSUE TITLE
new rule for "AdGuard German Filter" needed

### ISSUE THREAD

**Issue by sschmiedleitner** [AdguardTeam/AdguardFilters#28046]
Could you please add the following rule to the "AdGuard German Filter" list in order to prevent adblocker detection on the news website "derstandard.at" after some (5-7) navigations:

`derstandard.at#%#document.cookie = "MGUID=";`

should imho remove the cookie named "MGUID" that stores the adblocker status check!

Otherwise the adblocker cannot be used on this website!

Thank you!

**Comment by sschmiedleitner** [comment]
I have made this pull request for it:
https://github.com/AdguardTeam/AdguardFilters/pull/28047

**Comment by krystian3w** [comment]
Maybe still logout users...

https://github.com/NanoAdblocker/NanoFilters/issues/149#issuecomment-409407092
https://github.com/NanoAdblocker/NanoFilters/issues/149#issuecomment-438055440
https://github.com/NanoAdblocker/NanoFilters/issues/149#issuecomment-438057636
https://github.com/NanoAdblocker/NanoFilters/issues/149#issuecomment-438104488

**Comment by sschmiedleitner** [comment]
ah, ok, that is bad

**Comment by sschmiedleitner** [comment]
ok as I do not need a login, I would like to add it to my custom filters in my iphone, but unfortunately it is not accepted in the app. For this I raised this issue: https://github.com/AdguardTeam/AdguardForiOS/issues/892

As soon as this is fixed, this issue here can be closed.
