### ISSUE TITLE
filmakinesi.org -Ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2804]
Site: http://filmakinesi.org/
Screenshot: https://s9.postimg.org/48bqc9can/image.png

Site: http://filmakinesi.org/shelley-izle.html
Screenshot: https://s9.postimg.org/4dpwuux1r/image.png

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
||filmakinesi.org/wp-content/themes/FilmMachine/js/fancybox/
filmakinesi.org##div[id^="single_"][style]
```

**Comment by thislife81** [comment]
You forgot to remove this
![download](https://cloud.githubusercontent.com/assets/19608513/17748053/a58378bc-64c8-11e6-8658-4c0b4ef63414.png)
