### ISSUE TITLE
www.filmrax.com -Ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2805]
Site: http://www.filmrax.com/hizli-ve-ofkeli-2-izle-2003-turkce-dublaj-720p-full-hd.html

Screenshot: 
![rf](https://cloud.githubusercontent.com/assets/19608513/17644042/24a30c6e-618d-11e6-9c46-ac0c42012230.png)

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
filmrax.com##div[class="clear-position"][style]
```
