### ISSUE TITLE
www.filmsezonu.net -Ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2806]
Site: http://www.filmsezonu.net/

Screenshot: 
![vc](https://cloud.githubusercontent.com/assets/19608513/17644061/8a9bdd66-618d-11e6-8f8d-0ef1b0a77dfb.png)

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
It is not an ad.

**Comment by thislife81** [comment]
I think it's an annoyance that they placed the video at the bottom of the page.

**Comment by Alex-302** [comment]
no, this message informs you about the reason
