### ISSUE TITLE
www.fullhdfilmizledim.net -Ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2807]
Site: http://www.fullhdfilmizledim.net/
Screenshot: https://s10.postimg.org/g3jjcu1bt/1_X.png

Site: http://www.fullhdfilmizledim.net/shelley-izle-2016-korku-filmleri-full-hd-tek-part.html
Screenshot: https://s9.postimg.org/51tmbnk8v/image.png

Site: http://www.fullhdfilmizledim.net/shelley-izle-2016-korku-filmleri-full-hd-tek-part.html
Screenshot: https://s9.postimg.org/tgu17mlv3/image.png
(When enter the site, plays a video in the background/ Link is this the same video)

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
fullhdfilmizledim.net##.vidalti_block_sag
fullhdfilmizledim.net##.film-page-content > a[href^="http://goo.gl/"][style]
||princessbet.biz/cdn/promotion

```

**Comment by thislife81** [comment]
Site: http://www.fullhdfilmizledim.net/
1) Please remove background ad and toolbar(KAPAT)
2) Click on any link or picture, you will get a popup(perabet40.com)

Site: http://www.fullhdfilmizledim.net/shelley-izle-2016-korku-filmleri-full-hd-tek-part.html
 Screenshot:  And remove this.
![deq](https://cloud.githubusercontent.com/assets/19608513/18032752/44d3e6f8-6d21-11e6-8d08-89b5ab129c9f.png)

**Comment by Alex-302** [comment]
Added to Turkish filter
```
fullhdfilmizledim.org#$#body { background: #000000!important; }
fullhdfilmizledim.org#$#.player { display: block!important; }
fullhdfilmizledim.org###toolbar_reklam
||fullhdfilmizledim.org/pop/pop.js
```
