### ISSUE TITLE
https://disk.yandex.ua/- payment

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2808]
**Description**:
При включенном adguard скрываются поля для ввода реквизитов на странице оплаты яндекс.диска: http://savepic.ru/10922951.png

Помогает отключение опции "Скрыть поисковые запросы" в Антитрекинге. 

Screenshot:
<details>
![screenshot_86](https://cloud.githubusercontent.com/assets/18548949/17647260/9cd6d912-61f2-11e6-83bf-c7cc64b9be03.jpg)
![screenshot_87](https://cloud.githubusercontent.com/assets/18548949/17647264/a4ee4aae-61f2-11e6-8b80-9449bb4f7ccd.jpg)
![screenshot_84](https://cloud.githubusercontent.com/assets/18548949/17647267/ae90ba6a-61f2-11e6-849e-8c8fb1003f7a.jpg)
![screenshot_88](https://cloud.githubusercontent.com/assets/18548949/17647269/b4acdec4-61f2-11e6-9a07-8ccc944922e0.jpg)
</details>

**Steps to reproduce the problem**:

* Зайти в яндекс диск. Нужна будет учётка на яндексе. 
https://disk.yandex.ua/
*  Перейти в "Купить еще" на странице диска.
*  Выбрать количество Гб
+ Оплатить банковской картой
* В итоге не будет полей под введение данных

**Adguard version**: 6.1.251.1269

**Filters list**: 1,2,3

**Browser**: Хром, Firefox

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил
```
@@||pcidss.yandex.net^$stealth
```
