### ISSUE TITLE
https://thepiratebay.org

### ISSUE THREAD

**Issue by locusathome** [AdguardTeam/AdguardFilters#2809]
**Description**:
Annoying window/tab creation to/from adxprts.com/adexprts.com

**Current behaviour**: Tell us what happens
See description

**Expected behaviour**: Tell us what should happen instead
Should stop creation window/tab to adverts

**Steps to reproduce the problem**:
As I have reported in the forum missed ads, this is clearly NOT fixed, I still get new window creation even with the above additions in the English filterlist.

Recap:
https://thepiratebay.org                                 (all okay, it creates 2 cookies)
https://thepiratebay.org/browse                   (all okay)
https://thepiratebay.org/browse/201            (until now all okay)
Now when I click on a link or on a empty space it triggers a new window and only after the window creation it places a cookie 'tpbpop' and that stops any new window creation.

In my opinion the cookie should be created as soon as https://thepiratebay.org is loaded, that should stop the window creation immediately.

**Adguard version**:
Adguard 2.4.6 Beta Safari extension (content blocking API)
**Filters list**:

English, Spyware, Social, Annoyances, Experimental, Safari, Adblock Warning Removal.
**Operating system**:
Mac OS X 10.11.6

**Browser**:
Safari 9.1.2

**Comment by Alex-302** [comment]
It is impossible to prevent popup with Safari extension, because it does not support javascript rules.
Please check this rule
```
||traffic.adxprts.com^$popup
```

**Comment by locusathome** [comment]
Nope does not work.

But you say javascript rules don't work with Safari extension, why do I then get _some_ result with
thepiratebay.org#%#var _wm = 'no';
Okay it is maybe nonsense but it triggers an error in safari console and it does block the popunders more then any other rule I have seen/used.
Please explain this to me because I really like to know.

Secondly there surely has to be a way to block this this really annoying behaviour?

**Comment by Alex-302** [comment]
Safari on desktop supports JS rules.
Existing rule block this clickunder on my end:
http://imagizer.imageshack.com/img922/5691/OgtVNr.png

**Comment by ameshkov** [comment]
@Alex-302 do we still have this issue with Safari content blocker?

I mean $popup rules should've worked. If not, we should file a bug to WebKit and not just leave it open.

**Comment by Alex-302** [comment]
@ameshkov this site is clean at the moment,
