### ISSUE TITLE
ISP Ad Injection

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardFilters#2810]
Hi @Alex-302 @ameshkov 

**Description**:
My ISP MTNL is injecting ads on http pages, encrypted pages are ok.
What I think they are doing is injecting the ad within the HTML, not outside it and hence it is difficult to block it.

**Current behaviour**:
I investigated the matter on my own and found the ad originating from 203.94.248.40. So i blocked it via my router but then when i load pages, it keeps on saying '_waiting for 203.94.248.40_'
if i block the above ip using my adblocker or firewall, it knows and hence on some sites which require sign in, u have to reload the page everytym or else it won't sign in. on other sites, it may make togling b/w various tabs or other functions go haywire.

**here are some details i have found**:
http://203.94.248.40/dyn/bg/MTNL-FairUsage/index.js?policy=46&policyname=MTNL-FairUsage&time=1471211943&webServer=http://203.94.248.40&url=http%3A%2F%2Fcdn.ghacks.net%2Fwp-content%2Fthemes%2Fcanvas%2Fincludes%2Fjs%2Fmodernizr.js%3Fver%3D2.6.2

the contents of it are also pasted in pastebin here : http://pastebin.com/raw/ZMmDi7Pi

the source code doesn;t mention anything of this ip or ad, so it's difficult to find it via the source code method.

**Some screenshots**:
https://i.imgur.com/jmlRAdE.png
https://i.imgur.com/yy57cJC.png

**Adguard version**:
6.1.251.1269
**Filters list**:
English, Spyware, Social, Easy Privacy, FB's Annoyances and Custom Filter List.
Browsing Sec, Parental Control and Extensions are disabled.
Stealth Mode- Enabled
Driver WFP
Filter Https site is enabled.
No real time AV is enabled. No other software that should interfere with adguard's working.
**Operating system**:
Windows 10 Pro version 1607 build 14393.51 x64
**Browser**:
Firefox Stable x64

PLZ tell if you need any other info.

**Comment by The-Commissioner** [comment]
Some discussion threads:
https://www.reddit.com/r/india/comments/3h0lfx/np_mtnl_is_injecting_ads_in_almost_all_html_pages/
https://www.reddit.com/r/india/comments/408ceq/mtnl_and_bsnl_broadband_are_both_injecting_ads_on/
https://www.reddit.com/r/india/comments/2jhefo/mtnl_popup_ads_over_webpages_now_without_a_close/?st=irvkdj8z&sh=8d6a7b56
https://www.reddit.com/r/india/comments/22p2xn/mtnl_injecting_ads_in_webpages/

**Comment by ameshkov** [comment]
> the source code doesn;t mention anything of this ip or ad, so it's difficult to find it via the source code method.

Weird, there must be something.

> it keeps on saying 'waiting for 203.94.248.40'

This means that some script constantly tries to load something from that ip. Or maybe an iframe pointing there.

**Comment by ameshkov** [comment]
According to [this screenshot](https://i.imgur.com/yy57cJC.png) these two rules should be enough:
###__BULLETIN__bdiv[style*="position"]
||203.94.248.40^$image

**Comment by The-Commissioner** [comment]
Thanx for the reply :)
That's the thing...it doesn't say anything in source file, whatever is available is available only through dev tools. I checked the network tab also, and what info was available was provided in the pastebin file.
I have now added the two filter rules, let's wait and see.

**Comment by ameshkov** [comment]
> That's the thing...it doesn't say anything in source file, whatever is available is available only through dev tools

So there is no `__BULLETIN__bdiv` occurrences in the source code? Means somewhere there is a script that shows it. We just should find it.

**Comment by The-Commissioner** [comment]
> So there is no __BULLETIN__bdiv occurrences in the source code? Means somewhere there is a script that shows it. We just should find it.

I hope u checked out that pastebin file. Also I'll keep an eye on that particular occurrence the next time. I'll copy/paste the source code next time, maybe I missed sumthing that you guys can find out.

**Comment by ameshkov** [comment]
Ah, got it.

In this case this filter should do it:
`/dyn/bg/MTNL-FairUsage/index.js$third-party`

**Comment by The-Commissioner** [comment]
I will add all three just for security and monitor and will tell you then. 
Thanx again.

**Comment by The-Commissioner** [comment]
Hi, so although the ad was blocked but as mentioned in the first post it is causing problem in sites.

> if i block the above ip using my adblocker or firewall, it knows and hence on some sites which require sign in, u have to reload the page everytym or else it won't sign in. on other sites, it may make togling b/w various tabs or other functions go haywire.

the situation is same as above when using the filter rules you mentioned. I almost have to reload the http the second time to get the functioning of the site right. But if I keep blocking it, it's like a whole day scenario and it can be a PITA.

I'm uploading some files plz see:
Source code when blocking Ad: http://pastebin.com/raw/K9dSHZbu
Inner HTML when blocking Ad: http://pastebin.com/raw/SmPvFAPc

Source Code when **not** blocking Ad: http://pastebin.com/raw/zurXX8sR
Inner HTML when **not** blocking Ad: http://pastebin.com/raw/q0jEapxm

**Comment by Alex-302** [comment]
@The-Commissioner 
hi
could you provide me remote access through TeamViewer?
Or install Fiddler and open this site in private tab. Then select all strings and save them as *.SAZ archive.

**Comment by The-Commissioner** [comment]
@Alex-302 Thanx for the reply.
remote access is not a problem, the problem is this ad is not on demand, it's randomly put on by my ISP, not sure of the time when it will occur next.
I'm not familiar with fiddler, and like said there is no exact time when the ad will appear next.
So what do you want me to do?

**Comment by Alex-302** [comment]
Ok, you can open developer tools(F12), minimize it's height and wait for ads(navigate to sites). When you get an advert, go to developer tools -> Network tab and right click on any request and select "Save as HAR with content", and upload result file.
![image](http://i.imgur.com/R4KZ5B7.png)
Which browser are you using? My example is for Chrome.

**Comment by The-Commissioner** [comment]
Ok I can do that, Firefox has the option 'Save all as HAR'
FF 48 X64

**Comment by The-Commissioner** [comment]
@Alex-302 here you go buddy:

http://www.solidfiles.com/v/WwQpvvyNnk273

**Comment by Alex-302** [comment]
Please check these rules:
```
@@||203.94.248.40/cgi-bin/redirect?url=
@@||203.94.248.40/dyn/bg/MTNL-FairUsage/index.js*&url=
||203.94.248.40^$empty
```
@@||203.94.248.40/dyn/bg/MTNL-FairUsage/index.js*&url=
203.94.248.40/cgi-bin/redirect?url= 
are excluded, because useful script is loaded through redirect. For example
`http://cdn.ghacks.net/wp-includes/js/jquery/jquery.js?ver=1.12.4`

**Comment by The-Commissioner** [comment]
I removed all the previous rules, even disabled the blocks from my router, IPsec etc. and then added the 4 rules u gave. Again it's the same result as mentioned above, although it blocks the ad successfully but it adversely affects the site functioning and I have to reload again(sumtym twice) to get the functioning right.

Quoted from first post:

> if i block the above ip using my adblocker or firewall, it knows and hence on some sites which require sign in, u have to reload the page everytym or else it won't sign in. on other sites, it may make togling b/w various tabs or other functions go haywire.

For e.g. (of sites not working properly)
**OSM**
- Site when block the MTNL Ad:
![1](https://i.imgur.com/qiDPyel.png)

- Site when not blocking the MTNL Ad(how it should load):
![2](https://i.imgur.com/4OqTEDJ.png)

**MDL**
- Site when MTNL Ad is blocked:
![3](https://i.imgur.com/CAA6opp.png)
I'm not able to put my username and password there, it just selects the text there.

- Site when not blocking the Ad:
![4](https://i.imgur.com/oq44mrh.png)

This is just an example....I have problem on all the http sites. Also login is just one kind of problem, there can be tab togling and other problems too.

**Comment by The-Commissioner** [comment]
Here's how it is behaving on askvg.com **with your rules**:

![1](https://i.imgur.com/Tnsx5dt.png)

Inner Html: http://pastebin.com/raw/XPEnWavQ
HAR: http://www.solidfiles.com/v/nNVZ624gnVzyB

**Comment by The-Commissioner** [comment]
I couldn't wait for your reply so I tried avatar's rule and it replaces your rule fine whille blocking the element
I replaced rule: 

> ##div[id=”__BULLETIN__bdiv”]

with

> ###__BULLETIN__bdiv[style*="position"]

I'll monitor for a while and tell you the results.
Thanx

**Comment by Alex-302** [comment]
Could you please open developer tools, select the border of rectangle and make screenshot of html code? Like this
http://i.imgur.com/C9iEFJi.png

**Comment by The-Commissioner** [comment]
@Alex-302 here it is: https://i.imgur.com/pOo4Byn.png

but like i said above, avatar's rule works fine.
As of now, I'm using,

> @@||203.94.248.40/cgi-bin/redirect?url=
@@||203.94.248.40/dyn/bg/MTNL-FairUsage/index.js*&url=
||203.94.248.40^$empty
###__BULLETIN__bdiv[style*="position"]

**Comment by Alex-302** [comment]
ok
Added to English filter
```
@@||203.94.248.40/cgi-bin/redirect?url=
@@||203.94.248.40/dyn/bg/MTNL-FairUsage/index.js&url=
||203.94.248.40^
###__BULLETIN__bdiv[style="position"]
```

**Comment by The-Commissioner** [comment]
@Alex-302 looks like they changed something or I don't know if the filters are not working anymore. But now site functioning is affected. I'm using these rules:
@@||203.94.248.40/cgi-bin/redirect?url=
@@||203.94.248.40/dyn/bg/MTNL-FairUsage/index.js&url=
||203.94.248.40^
###__BULLETIN__bdiv[style="position"]

also why you added rules related to ip 203.94.227.140?

**Comment by Alex-302** [comment]
IP's are different in other regions. Taken from Indian forums.

What is broken?

**Comment by The-Commissioner** [comment]
same site functioning problem as in the example shown above of OSM and MDL.

**Comment by The-Commissioner** [comment]
bump 
Hello @Alex-302 u still with me brother???

I would like to suggest changes to the rules pertaining to my IP pls. 

**Rules to be removed**
> @@||203.94.248.40/cgi-bin/redirect?url=
@@||203.94.248.40/dyn/bg/MTNL-FairUsage/index.js&url=
||203.94.248.40^
###__BULLETIN__bdiv[style="position"]

**Rules to be added**
> ||203.94.248.40^$image,third-party
###__BULLETIN__bdivImage

I have checked these rules and with them there is no site functioning problem, plz remove the old one bcuz of which there is problem and add these new ones. I request you to do this atleast for my IP if not the other IP.

**Comment by Alex-302** [comment]
Done
