### ISSUE TITLE
https://www.mediafire.com - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2811]
https://www.mediafire.com/folder/oip0rh9uca0mb#m03mnw60a2q49

![image](https://cloud.githubusercontent.com/assets/15856304/17659041/9a8c0880-62d8-11e6-935c-cd621add5bb9.png)

Confirmed.

Customer uses these filters:
<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.91.30 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.23 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.8.82 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.2.75 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.89 Enabled=NO
ID=5 Name="Experimental filter" Version=1.0.26.23 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.59 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.13 Enabled=YES
ID=101 Name="EasyList" Version=1.0.61.50 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.63.64 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.63.33 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.53.84 Enabled=NO
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2 Enabled=YES
ID=204 Name="Peter Lowe's list" Version=1.0.2.23 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.63.47 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.53.82 Enabled=NO
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.50 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
ID=220 Name="CJX's Annoyance List" Version=1.0.0.52 Enabled=YES
ID=229 Name="I dont care about cookies" Version=1.0.0.1 Enabled=YES

**Comment by Alex-302** [comment]
Too many filters. Don't ignore limit or rules quantity.
Try to disable
```
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.50 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
ID=220 Name="CJX's Annoyance List" Version=1.0.0.52 Enabled=YES
ID=229 Name="I dont care about cookies" Version=1.0.0.1 Enabled=YES
ID=101 Name="EasyList" Version=1.0.61.50 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.63.64 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.63.33 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2 Enabled=YES
```

**Comment by worldsdream** [comment]
English, dutch, annoyance, mobile, safari

I get the same.

**Comment by Alex-302** [comment]
Confirmed only on Safari with extension.
Added to Safari filter:
```
@@||cdnssl.mediafire.com/js/
```
