### ISSUE TITLE
http://www.focus.de/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2812]
http://www.focus.de/

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/17659164/7ce1201c-62d9-11e6-832c-0b45754e250e.png)

</details>

Filters:
<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.91.29 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.22 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.55 Enabled=YES
ID=6 Name="German filter" Version=1.0.26.85 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.23 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.58 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.12 Enabled=YES
ID=101 Name="EasyList" Version=1.0.61.50 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.59.91 Enabled=YES
ID=113 Name="Liste FR" Version=1.0.63.49 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.63.45 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
</details>
**1130186**

**Comment by Alex-302** [comment]
Try:
```
@@||focus.de^$generichide
```
