### ISSUE TITLE
uol.com.br - annoyances

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#28134]
### Sharing bar below the headline

`##.c-tools-share`

`https://bompracachorro.blogfolha.uol.com.br/2018/04/01/caes-participam-de-evento-e-comemoram-pascoa/`

### Floating sharing bar when you select some text from the article
`##.c-share-text` 

`https://www1.folha.uol.com.br/mercado/2018/04/spotify-tem-3a-melhor-abertura-de-capital-na-tecnologia.shtml`

Adguard Annoyances + Social + Portuguese
uBlock Origin 1.17.4
Firefox 64

**Comment by adranger** [comment]
@AdamWr 

[https://tvefamosos.uol.com.br/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://tvefamosos.uol.com.br/)

App download banner displayed on Android devices:

![banner](https://user-images.githubusercontent.com/35470489/66446462-05954600-ea21-11e9-9c50-340163e5b8b2.png)


Adguard Base + Annoyances + Mobile + Portuguese + Russian + Social + Spyware
uBlock Origin
Mozilla/5.0 (Android 7.1.2; Tablet; rv:68.0) Gecko/68.0 Firefox/68.0

**Comment by AdamWr** [comment]
Ok, fixed.
