### ISSUE TITLE
oantagonista.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#28136]
`https://www.oantagonista.com/brasil/amor-e-briga-no-rodoanel/` 

    oantagonista.com##.share
    oantagonista.com###backtotop
    oantagonista.com###buttonopenmannychat

Adguard Annoyances + Social + Portuguese
uBlock Origin 1.17.4
Firefox 64

**Comment by adranger** [comment]
@Alex-302 they've changed the newsletter code:

![antagonista](https://user-images.githubusercontent.com/35470489/66708138-3f689400-ed22-11e9-8374-9199a7db0705.png)

**Comment by Alex-302** [comment]
ok

**Comment by adranger** [comment]
`#form-newsletter` (it's better to leave the previous filter too in case they are testing which block works best):

![newsletter](https://user-images.githubusercontent.com/35470489/67203809-6c800b00-f3e2-11e9-9a93-bbe729954ff7.png)

**Comment by Alex-302** [comment]
ok
