### ISSUE TITLE
yandex pogoda - ads, yandex direct

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2814]
https://yandex.ru/pogoda/krasnodar/?from=vb-chrome

![image](https://cloud.githubusercontent.com/assets/15856304/17659959/c05ff246-62de-11e6-9c11-b7bc600924de.png)

Please check with Russian IP, I was unable to reproduce.

**1393644**

**Comment by Alex-302** [comment]
Не повторяется. Проверял с российским IP.

**Comment by evgeniy-ADG** [comment]
аналогично, а у юзера - "проскакивает", как он пишет. куда смотреть в таких случаях, что просить и как траблшутить?.. может, в кеше?

**Comment by Alex-302** [comment]
> "проскакивает"

что он под этим подразумевает? Там реклама удаляется правилом javascript, и реклама успевает на мгновение отрисоваться.

**Comment by evgeniy-ADG** [comment]
Видимо, это и имеет. Уточню. Спасибо за инфу, кстати. А может что-то не сработать и не скрыть, хотя правило корректное?

**Comment by Alex-302** [comment]
Вполне. Например, если добавлено исключение javascript

**Comment by evgeniy-ADG** [comment]
Имеешь в виду кастомное правило в польз. фильтр? Или это как-то в самом браузере можно отключить?

**Comment by Alex-302** [comment]
И так и этак. Браузером можно полность. запретить javascript.

**Comment by evgeniy-ADG** [comment]
Пропущена реклама на сайте https://yandex.ru/pogoda/
Скриншот: http://f1.s.qip.ru/OgbqisAC.png

Мои параметры:
* Win x64
* adguard в виде расширения у Chrome
* фильтры: русский, английский, RU AdList
* Dr.Web

**Comment by Alex-302** [comment]
Не вижу. Без  RU AdList пусть попробует.

**Comment by vgavrish** [comment]
yandex.ru/pogoda/krasnoe
Программа. Яндекс Директ
Ф:  1,2,3,5,14
Edge
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19761414/861d6f3e-9c3e-11e6-9682-0db32a3e9528.png)

**Comment by Alex-302** [comment]
Пусть проверит обновление фильтров. Добавлял сегодня правило, но работать будет только с бетой.

**Comment by vgavrish** [comment]
отписала

**Comment by vgavrish** [comment]
все ок, блокируется
