### ISSUE TITLE
inoreader.com - leftover iframe

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#28144]
`https://www.inoreader.com/folder/example` (account neeeded)

* Set a folder to the "Column view" 
* It loads an iframe from `||inoreader.com/sinner`
* It's hidden already but this address could be blocked completely to prevent it from flashing/making useless connections:

![inoreader](https://user-images.githubusercontent.com/35470489/50722891-31178880-10bd-11e9-88d1-1af3637ca6f2.png)

Adguard Base + Annoyances
uBlock Origin 1.17.4
Firefox 64

**Comment by Alex-302** [comment]
Can't reproduce.
![image](https://user-images.githubusercontent.com/8361299/53260365-f9e75000-36d9-11e9-9773-7f783d55bf2f.png)

**Comment by adranger** [comment]
@mapx- please follow the steps in my first post and see if you get these iframes with a folder with Youtube subscriptions.

![inoreader](https://user-images.githubusercontent.com/35470489/53265291-b03c3c80-36bc-11e9-9d10-dfc23abfb838.png)

**Comment by Alex-302** [comment]
Thanks. Added:
```
inoreader.com##div[id^="column_ad-"]
inoreader.com##.ad_footer_remove
```
