### ISSUE TITLE
http://smotri.com/ - ads before video 

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#2815]
![image](https://cloud.githubusercontent.com/assets/20476168/17667160/58a9c9e6-630c-11e6-986f-4a902e8fad6f.png)

Фильтры: 
Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский

**Comment by Alex-302** [comment]
@Fridrix 
проверьте снова. Вчера этот сайт чистил.

**Comment by evgeniy-ADG** [comment]
Fixed

**Comment by vgavrish** [comment]
Расширение. Фильтры: 1,2,3,4,14
http://smotri.com/broadcast/list/
сбоку реклама
<details>
![screenshot_25](https://cloud.githubusercontent.com/assets/18548949/18156321/1263ae06-701e-11e6-9a4e-df1099e6bace.jpg)

**Comment by Alex-302** [comment]
У меня она блокируется. Сайт не в исключениях?

**Comment by vgavrish** [comment]
сорри, Яндекс браузер.
у меня есть еще кусок рекламы:
http://prntscr.com/ccvaa0

**Comment by Alex-302** [comment]
Удалённо бы глянуть. Не выходит поймать.
