### ISSUE TITLE
hotslogs.com

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#2816]
Проверил со стандартным набором, повторяется и в Win10 и на маке с десктопным приложением.
1. заходим на http://www.hotslogs.com/
   ![screen shot 2016-08-15 at 17 30 26](https://cloud.githubusercontent.com/assets/17472907/17667679/8c2ef938-630e-11e6-9ec2-e28e08936f7b.png)
2. Нажимаем на имя любого персонажа (левый столбец (Hero), кидает на http://www.hotslogs.com/Info/AdBlock 

![screen shot 2016-08-15 at 17 30 41](https://cloud.githubusercontent.com/assets/17472907/17667678/8c2b8a14-630e-11e6-8d0b-cacbd0a0665c.png)

**Comment by Alex-302** [comment]
Поправил.

**Comment by vgavrish** [comment]
Снова та же ситуация. Нужно зайти на сайт и нажать на любого персонажа + подождать некоторое время и появится страница https://www.hotslogs.com/Info/AdBlock
Win, chome
Ф: 1,2,3,4,14

**Comment by Alex-302** [comment]
поправил

**Comment by vozersky** [comment]
Adguard doesn't block this script on Android, need a fix

**Comment by Alex-302** [comment]
Not reproduced.
Try this rule:
```
hotslogs.com$$script[tag-content="AdFillMonkeyBroker"][max-length="15000"]
```

**Comment by vozersky** [comment]
@Alex-302 this rule has helped. Works now.

**Comment by Alex-302** [comment]
Ok, added

**Comment by Alex-302** [comment]
@vmalyuta как ты повторял? У меня даже с расширением не повторяется.

**Comment by vmalyuta** [comment]
вчера на рабочем маке проверяла 
а сейчас на домашнем все ок

**Comment by Alex-302** [comment]
@vmalyuta уточни тогда у юзера, всё ли у него норм.

**Comment by aksyonova** [comment]
юзер пишет:  " При заходе в свой профиль периодически 
выбивает на страницу Ad Block. Всё так же периодически 
перенаправляет на страницу заглушку отовсюду в половине случаев.
Фильтры я обновил перед проверкой."

**Comment by Alex-302** [comment]
Вот такое передай
```
hotslogs.com$$script[tag-content="AdFillMonkeyBroker"][max-length="15000"]
```

**Comment by Alex-302** [comment]
Вот такое передай
```
hotslogs.com$$script[tag-content="AdFillMonkeyBroker"][max-length="17000"]
```

**Comment by dzamyshlyayeva** [comment]
передали
