### ISSUE TITLE
http://portable-rus.ru/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2817]
**Description**: Расширение
Реклама на http://portable-rus.ru/

Screenshot:
<details>
![screenshot_90](https://cloud.githubusercontent.com/assets/18548949/17668710/47260714-6313-11e6-9a5a-b4ee8f9de790.jpg)
</details>

**Filters list**: 1,2,3,4,5,14

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
portable-rus.ru##a[href^="http://TeaserNet"]
portable-rus.ru##a[href^="http://costaction.com/partner/"]
```
текстовые остатки не убрать.
