### ISSUE TITLE
vk.com app

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2818]
**Description**:
https://new.vk.com/app2935759_378569521
После запуска игры, выходит сообщение о фишинге.

Screenshot:

<details>
![screenshot_91](https://cloud.githubusercontent.com/assets/18548949/17673154/880e11da-6328-11e6-85c0-a533573251a9.jpg)

</details>

**Adguard version**: 6.0, 6.1

**Filters list**: 1,2,3,4,14

**Browser**: Хром

**Comment by Alex-302** [comment]
@vbagirov удали из фишинга vk.vectorgame.ru и/или vectorgame.ru

**Comment by vbagirov** [comment]
Сделано.

**Comment by vgavrish** [comment]
1112703
https://vk.com/app2622342#/play
В приложении шахмат постоянно как обновляю или заново открываю страничку выскакивает реклама, надо ждать что бы ее закрыть. 
Ф: 1,2,3,4,14
Хром
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20858295/957dfe24-b94b-11e6-9206-b02cb41ddbd7.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
1chess.org##div[id^="vk_ads_"]
||media.kahoxa.ru^$third-party

```
