### ISSUE TITLE
imageraider.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2819]
**Description**:
https://www.imageraider.com/search/#p5e62b9d109a1a62e57ff2b4f6f802de3
При поиске картинок на сайте пишется, что обнаружен адблокер

Screenshot:
<details>
![screenshot_92](https://cloud.githubusercontent.com/assets/18548949/17674643/1045f3f0-632f-11e6-90fa-3ab612c34448.jpg)

</details>

**Filters list**: 1,2,3,4,5,14

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
imageraider.com#@#.adsbygoogle

```
