### ISSUE TITLE
ashemale.one [NSFW] [Ad Strings & Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#28205]
**Site**: https://ashemale.one/vids/1006780/

**Issue**: Ad text strings & pop-ups seen on the page.

**Screenshot**: http://prntscr.com/m669us

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 71.0.3578.98 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
Please fix

**Comment by Nzzyme** [comment]
Seeing ad text strings on Firefox for Android. Can you check for Android too?

**Comment by AdamWr** [comment]
Fixed.
