### ISSUE TITLE
telegraaf.nl - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2820]
![image](https://cloud.githubusercontent.com/assets/15856304/17690620/7fdb21cc-6398-11e6-9770-fe83f7a023a2.png)

The pop up's address: [tha address](http://tmgonlinemedia.nl/consent/consent/?return=http%3A%2F%2Fwww.telegraaf.nl%2F&clienttime=1471330576084&version=0&detect=true)

Filters in MacOS app: Eng, Spywre, Social, Annoyances, Russian, German, Dutch, Spanish, Experimental, Mobile, Safari
Please check our customer's comment on the issue
<details>
On all pages of this news website "www.telegraaf.nl" I get messages
from elements that tell me that to see the content of the blocked content
(blocked by the most resticted cookie setting) and that I have to change
the cookie settings.
I can easily block the showing of the messages with this filter
www.telegraaf.nl###leftbar <http://www.telegraaf.nl/#%23%23leftbar> >
A.noConsent:nth-child(16) > DIV.addiv.noConsent
But I have to do make the filters for dozens of filters and that is a real
pita.

The best would be to block anything that contains "DIV.addiv.noConsent"
with a single filter
</details>

**1392357**

**Comment by Alex-302** [comment]
Please check this rule
```
telegraaf.nl#%#AG_onLoad(function() { if (window.location.href.indexOf("/consent/?return=") != -1) { document.cookie = "cc=clienttime-99999999.version-42"; location.reload(); } }); 
```

**Comment by worldsdream** [comment]
That didn't work, added this to userfilter on mac OS app.

**Comment by Alex-302** [comment]
@worldsdream 
Wrong domain is in my rule.
Check this:
```
tmgonlinemedia.nl#%#AG_onLoad(function() { if (window.location.href.indexOf("/consent/?return=") != -1) { document.cookie = "cc=clienttime-99999999.version-42"; location.reload(); } });
```

**Comment by worldsdream** [comment]
working perfectly

**Comment by Alex-302** [comment]
Added to Annoyances filter

**Comment by worldsdream** [comment]
See screenshot: http://i.imgur.com/ElyLD8H.png

Translation of text: To show this element, you need to accept cookies

**Comment by Alex-302** [comment]
Please make a screenshot of HTML code, I don't see these elements.

**Comment by worldsdream** [comment]
screenshot of html code: http://i.imgur.com/undefined.png

**Comment by Alex-302** [comment]
@worldsdream 
invalid screenshot.

**Comment by worldsdream** [comment]
my bad, here you go: http://i.imgur.com/H50tAF3.png

**Comment by Alex-302** [comment]
Try
```
telegraaf.nl##.noConsent
```
for FF - disable Annoyances filter and check this:
```
tmgonlinemedia.nl#%#AG_onLoad(function() { if (window.location.href.indexOf("/consent/?return=") >= 1) { document.cookie = "cc=clienttime-99999999.version-42"; location.reload(); } });
````

**Comment by worldsdream** [comment]
`telegraaf.nl##.noConsent` that worked, you can add it to filterlist

disabled annoyance and added the rule, still the same!

**Comment by Alex-302** [comment]
Added cookie existing check:
```
tmgonlinemedia.nl#%#AG_onLoad(function() { if (window.location.href.indexOf("/consent/?return=") >= 1 || document.cookie.indexOf('cc') != -1) { document.cookie = "cc=clienttime-99999999.version-42"; location.reload(); } });
```

**Comment by worldsdream** [comment]
I updated filterlist, working perfect now.

**Comment by Alex-302** [comment]
Ok.
