### ISSUE TITLE
http://zhidao.baidu.com - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2821]
http://zhidao.baidu.com/question/2073413467398033588.html

![image1](https://cloud.githubusercontent.com/assets/15856304/17690926/70c06a88-639a-11e6-8a39-38b4fe361266.png)

<details>
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.91.45 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.24 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.58 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.62 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.14 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.63.75 Enabled=YES
</details>

Reproduce in safari with iPhone user agent.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
у меня сайт не догружается. Попроси удалённый доступ к десктопу. Или может у тебя получится повторить на компе.

**Comment by evgeniy-ADG** [comment]
Повторяется на маке с айфоновым ЮА. Завтра дам тв, если не забуду. Попробуй сейчас:
556 597 498
9993
