### ISSUE TITLE
[Adguard Pro for iOS] google.ca - Chrome's self-advertising

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2822]
Can we block it?

![image](https://cloud.githubusercontent.com/assets/15856304/17691004/d998c866-639a-11e6-8a91-0b0ec08449d2.png)

state
<details>
Application version: 1.0.0.16

Application lifetime: 2016-08-02 10:25:38 +0000

Device: iPhone

Platform: iPhone OS

OS: 10.0

ID: 46F732BD-0D30-44C2-8356-AD29115B27C1

Locale: en

Region: ca

Optimazed enabled: NO

Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.0.91.53 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.7.24 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.11.58 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.1.15 Enabled=YES
</details>
**1303217**

**Comment by evgeniy-ADG** [comment]
Oops, noticed that user does not use Annoyances, will ask and post an update later.

**Comment by evgeniy-ADG** [comment]
**1251222** - the same complaint here
<details>
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.91.57 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.25 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.61 Enabled=YES
ID=6 Name="German filter" Version=1.0.26.90 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.63 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.17 Enabled=YES
ID=101 Name="EasyList" Version=1.0.61.64 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.59.94 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.63.53 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.61.80 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.61.66 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2 Enabled=YES
ID=204 Name="Peter Lowe's list" Version=1.0.2.24 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.63.67 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.50 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
<details>

**Comment by Alex-302** [comment]
Yes, it is blocked by Annoyances filter.

**Comment by evgeniy-ADG** [comment]
TY.

**Comment by maciboy** [comment]
I'm the one who reported 1251222.
Thought Annoyances were blocked, but they weren't, Filter was deactivated :/
So I activated the Annoyances filter and until now the banner doesn't reappear.

Sorry guys for bothering you, my fault ;)
Otherwise I will report back...

**Comment by evgeniy-ADG** [comment]
We have a reply from another customer, **1303217** : )
He's using Adguard Pro, though.

> I enabled the annoyance filter, tested when Safari is close from background and at launch when safari opens Google homepage the banner is still visible but when a new tab is opened the banner is blocked by Adguard. Why it's not blocking banner at startup of Safari?

**Comment by Alex-302** [comment]
@evgeniy-ADG I think it is not Adguard issue. Please ask in iOS repository about it.
