### ISSUE TITLE
https://slon.ru - placeholders

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2823]
**1393890**
https://slon.ru/posts/71985

![image1 1](https://cloud.githubusercontent.com/assets/15856304/17691776/19a707ca-639f-11e6-8a21-52d42b6f9030.png)

<details>
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.91.53 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.24 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.58 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.2.77 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.91 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.37.86 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.63 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.15 Enabled=YES

**Comment by Alex-302** [comment]
Added to Mobile filter
```
slon.ru##.advert
```
