### ISSUE TITLE
https://www.computerbase.de/ - placeholder, annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2824]
**https://www.computerbase.de/**
![file_000](https://cloud.githubusercontent.com/assets/15856304/17698623/e3a61064-63c4-11e6-9776-019c4c984d89.png)

<details>
Application version: 1.0.8.54

Application lifetime: 2016-08-10 17:20:11 +0000

Device: iPad

Platform: iPhone OS

OS: 9.3.4

ID: AE9C18EB-388A-4ECD-8686-0415BD386B28

Locale: de

Region: de

Optimazed enabled: NO

Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.0.91.19 Enabled=NO

ID=3 Name="Spyware filter" Version=1.0.7.27 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.11.62 Enabled=YES

ID=14 Name="Annoyances filter" Version=1.0.2.84 Enabled=YES

ID=6 Name="German filter" Version=1.0.26.91 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.1.17 Enabled=YES

ID=107 Name="EasyList Germany" Version=1.0.59.95 Enabled=YES

**Comment by Alex-302** [comment]
Can't reproduce on desktop Safari.

**Comment by evgeniy-ADG** [comment]
It occurs on a real device!

**Comment by vozersky** [comment]
Cookies notification? 
I can reproduce it as well

**Comment by evgeniy-ADG** [comment]
Cookies and the blank space that was used to display ads

**Comment by Alex-302** [comment]
I think it is an Adguard for iOS issue. Please ask in iOS repository.
