### ISSUE TITLE
missed ads www.ixbt.com

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2825]
Пропущена реклама в шапке.

![image1](https://cloud.githubusercontent.com/assets/16462533/17703341/fa148848-63d9-11e6-96e6-2a6831336049.PNG)

**Фильтры:**

> Английский
> Фильтр счетчиков и систем аналитики
> Экспериментальный
> Фильтр раздражителей
> Русский
> Safari

**Comment by Alex-302** [comment]
На iOS невозможно убрать отступ.
