### ISSUE TITLE
missed ads pornolab.net

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2826]
Пропущена реклама

![2016-08-16_18-12-59](https://cloud.githubusercontent.com/assets/16462533/17704343/7d1347a4-63dd-11e6-911c-706a57b45187.png)

**Фильтры:**

```
Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский
```

**Comment by Alex-302** [comment]
Fixed

**Comment by vgavrish** [comment]
Расширение. Хром. Фильтры: 1,2,3,4,5,14
http://pornolab.net/forum/index.php
http://prntscr.com/cb9z59

**Comment by Alex-302** [comment]
Убрал

**Comment by evgeniy-ADG** [comment]
http://pornolab.net/forum/index.php

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/20274235/8dc457cc-aa9c-11e6-81c2-1a7a87ae06ec.png)

![image](https://cloud.githubusercontent.com/assets/15856304/20274257/a17fb162-aa9c-11e6-88ba-520a7b81d0dd.png)

<details>

* Win x64
* adguard в виде расширения у Chrome
* фильтры: русский, английский, RU AdList

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
pornolab.net,pornolab.biz##div[id^="vsexshop"]
||annsummers.ru^$domain=pornolab.net|pornolab.biz

```

**Comment by evgeniy-ADG** [comment]
Пропущена реклама на сайте: http://pornolab.net/forum/index.php
Скриншот: http://f4.s.qip.ru/Ogbqitzo.png

Мои параметры:
* Windows 7 x64
* Adguard в виде расширения у Chrome
* Используемые фильтры: Русский фильтр, Английский фильтр, RU AdList
* Dr.Web

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21072318/8d9cbd5a-bec6-11e6-81e8-3593068d12ec.png)

**Comment by Alex-302** [comment]
fixed

**Comment by vgavrish** [comment]
http://pornolab.net/forum/index.php
Расширение. Хром
Русский фильтр, Английский фильтр, RU AdList
![image](https://cloud.githubusercontent.com/assets/18548949/22174340/b5b4fa7a-dfe4-11e6-94f2-c28469b28e62.png)

**Comment by Alex-302** [comment]
поправил

**Comment by evgeniy-ADG** [comment]
http://pornolab.net/forum/index.php

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22416907/f9f43ac4-e6d9-11e6-95bd-15d6438745d0.png)

![image](https://cloud.githubusercontent.com/assets/15856304/22416925/0d7cefaa-e6da-11e6-922c-4d10e10e6f23.png)

</details>

* Windows 7 x64
* Adguard в виде расширения у Chrome
* Используемые фильтры: Русский фильтр, Английский фильтр, RU AdList

**Comment by Alex-302** [comment]
fixed
