### ISSUE TITLE
123movies.la [Pop-ups] [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#28278]
**Site**: https://123movies.la/movie/the-lost-viking-zrmke8y

**Issue**: Pop-ups, fake links seen on the page (http://prntscr.com/m6k3hl). After clicking on play, the next page too has some other player fake buttons as seen here (http://prntscr.com/m6k47h)

**Screenshot**: See above

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 71.0.3578.98 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by AdamWr** [comment]
Regarding second screenshot, these elements don't look like a fake buttons.
