### ISSUE TITLE
http://www.sohu.com/  http://www.youku.com/ sites with ads.

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#2827]
User has the issue on Opera,IE 11,Microsoft Edge,Baidu etc.
![image](https://cloud.githubusercontent.com/assets/20476168/17710745/54b54e28-63f7-11e6-8826-2c6d83006862.png)
Hasn't been reproduced on our side.
Seems it depends on location.

**Comment by Alex-302** [comment]
По скрину не понятно, что это. Больше на ошибку похоже.
