### ISSUE TITLE
http://xbox-store-checker.com/en/ - anti-adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2828]
http://xbox-store-checker.com/en/

![screen shot 2016-08-17 at 12 31 31 pm](https://cloud.githubusercontent.com/assets/15856304/17731547/623189f2-6476-11e6-8a3f-45bbab317ee5.png)

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.91.64 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.27 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.64 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.17 Enabled=YES

**Comment by Alex-302** [comment]
Added to English filter
```
@@||xbox-store-checker.com/assets/js/*ads*.js
```
