### ISSUE TITLE
http://www.moyareklama.by

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2829]
**Description**: Реклама
http://www.moyareklama.by/Гомель/квартиры_продажа/

Screenshot:

<details>
![screenshot_96](https://cloud.githubusercontent.com/assets/18548949/17744064/ce66e2f6-64ae-11e6-8f07-2a2be0b697f6.jpg)

</details>

**Adguard version**: Андроид

**Filters list**: 1,2,3,4,14,11

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
moyareklama.by##div[bannerlocation]
```
