### ISSUE TITLE
m.habrahabr.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2830]
**Description**:
При переходе с m.habrahabr.ru по баннеру на Play market приложения  браузере зависает ссылка https://appmetrica.yandex.com/serve/745097116363323173?id=ru.habrahabr&utm_source=mobilTM&utm_medium=button&utm_campaign=appAndroid
И дальше в браузере не открывается Play market.

Помогает отключение Фильтра мобильной рекламы.

Screenshot:
<details>
![screenshot_97](https://cloud.githubusercontent.com/assets/18548949/17745143/6452f79c-64b3-11e6-9546-db40026e25a8.jpg)
![screenshot_98](https://cloud.githubusercontent.com/assets/18548949/17745114/4b748f1a-64b3-11e6-9d39-dc94515039c1.jpg)
![screenshot_99](https://cloud.githubusercontent.com/assets/18548949/17745115/4b75bb9c-64b3-11e6-9d04-10e06b01be81.jpg)

</details>

**Steps to reproduce the problem**:

* Пролистать вниз сайта и нажать на Google Play
*  В браузере идет переход на приложение в Google Play
*  Зависает переход на ссылке 
https://appmetrica.yandex.com/serve/745097116363323173?id=ru.habrahabr&utm_source=mobilTM&utm_medium=button&utm_campaign=appAndroid

**Adguard version**: 2.7.220

**Filters list**: 1,2,11,14

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил, но работать будет только при включенной фильтрации HTTPS
```
@@||appmetrica.yandex.com/serve/$domain=m.habrahabr.ru
```
если выключена - то в пользовательский фильтр
```
@@||appmetrica.yandex.com
```
