### ISSUE TITLE
No Adguard Assistant on sites

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2831]
**Description**:
На сайтах в браузере IE 11 отсутствует Помощник. В других браузерах есть.
http://internetua.com/category/news
http://www.yves-rocher.ua/control/main/

Screenshot:
<details>
![screenshot_5](https://cloud.githubusercontent.com/assets/18548949/17749764/db14220c-64c7-11e6-8557-5d1036aac096.jpg)
![screenshot_6](https://cloud.githubusercontent.com/assets/18548949/17749765/db159182-64c7-11e6-9fd9-0a4c84da6536.jpg)

</details>

**Adguard version**: 6.1.251.1269

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: IE 11

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
В раздел Windows перетащи. Фильтрами не исправить.
