### ISSUE TITLE
https://weibo.com/ - help us to create a custom rule to expand the tree

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2832]
![image](https://cloud.githubusercontent.com/assets/15856304/17767019/dccb79be-6536-11e6-8ce2-0f02dcbf6b00.png)

Customer want to have it automatically expanded.

> I am talking about text replacement can reach some website features change the role, for example, such as China Weibo, it is a China's facebook, if your text replacement function is available, then you can use the attached images in red block mark expanded by default, without the need for a mouse click again to expand the same.

More info and login and pass are available here: 1186462

**Comment by Alex-302** [comment]
I can't login. Don't know why.
