### ISSUE TITLE
com.CubeSoftware.BlockTankWars2Premium ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2833]
#### Source
http://4pda.ru/forum/index.php?showtopic=601691&st=6500#entry51796984

#### App link
https://play.google.com/store/apps/details?id=com.CubeSoftware.BlockTankWars2Premium&hl=en

#### Screenshots
<details>
![screenshot_2016-08-15-22-32-51](https://cloud.githubusercontent.com/assets/5947035/17772280/a733c152-6550-11e6-9ce7-74f09193b7f0.png)
![screenshot_2016-08-15-22-33-21](https://cloud.githubusercontent.com/assets/5947035/17772282/a95365e6-6550-11e6-90b2-77e27abfb938.png)
![screenshot_2016-08-15-22-33-50](https://cloud.githubusercontent.com/assets/5947035/17772283/ab280e80-6550-11e6-9ea7-37663f16ec11.png)
![screenshot_2016-08-15-22-35-02](https://cloud.githubusercontent.com/assets/5947035/17772287/ad9d602a-6550-11e6-926b-f756a69a4b8a.png)
</details>

**Comment by Alex-302** [comment]
Trial or license are not active.  It is clean on my end(version from 4pda)
