### ISSUE TITLE
arcadeitalia.net

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#28336]
`http://adb.arcadeitalia.net/default.php`

`.cookiesdirective.` in `Adguard's Annoyance List` breaks the search feature completely.

Adguard’s Base + Spyware + Annoyance + Social
uBlock Origin 1.17.4
Firefox 64.0.2

**Comment by krystian3w** [comment]
```
adb.arcadeitalia.net#$#body::-webkit-scrollbar-thumb { background-color: #6e6e6e !important; border: none !important; border-radius: 0 !important; box-shadow: none !important; }
adb.arcadeitalia.net#$#body::-webkit-scrollbar-track { background: #f1f1f1 !important; border-radius: 0 !important; }
adb.arcadeitalia.net#$#body::-webkit-scrollbar { width: 12px !important; }
```

Optional redesign scrollbars.

**Comment by adranger** [comment]
I didn't even know they had custom scrollbars, since that code thankfully doesn't affect Firefox. 😛

**Comment by Alex-302** [comment]
fixed
