### ISSUE TITLE
http://uploaded.net/

### ISSUE THREAD

**Issue by Alexey71** [AdguardTeam/AdguardFilters#2834]
**Description**:
http://uploaded.net/file/xl48cl9e
**Current behaviour**: Tell us what happens
Просит отключить антибаннер
Screenshot: use the following code

<details>
![2016-08-18_214535](https://cloud.githubusercontent.com/assets/10572914/17786395/5050a318-658d-11e6-87d4-e385d5018aaf.jpg)
</details>

**Expected behaviour**: Tell us what should happen instead
Должа быть кнопка серая Free download

<details>
![2016-08-18_214839](https://cloud.githubusercontent.com/assets/10572914/17786450/8e80e65c-658d-11e6-88a5-462901d9c22e.jpg)
</details>

**Adguard version**:
6.1.251.1269
**Filters list**:
 Английский-Русский-Раздражители-Экспериментальные-Счетчики и системы аналитики
**Operating system**:
win10 x64
**Browser**:
firefox
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
