### ISSUE TITLE
http://onlyf.ws/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2835]
http://onlyf.ws/

![img_0437](https://cloud.githubusercontent.com/assets/15856304/17801446/e070a280-65f2-11e6-819e-e654083e50c2.JPG)

<details>
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.91.66 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.30 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.69 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.2.89 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.37.94 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.17 Enabled=YES
ID=101 Name="EasyList" Version=1.0.61.67 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.63.75 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.63.61 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.61.83 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.63.75 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.63.63 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.50 Enabled=NO
ID=212 Name="RU AdList: Counters" Version=1.0.60.33 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.60.60 Enabled=YES

**Comment by Alex-302** [comment]
Added to Safari filter
```
onlyf.ws##body > :not(div):not(table)
```
