### ISSUE TITLE
http://watchdbsuper.net - pop up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2836]
http://watchdbsuper.net/dragon-ball-super-episode-54-subbed/

Click anywhere and it'll open a new tab

![image](https://cloud.githubusercontent.com/assets/15856304/17801782/bfb1f9f2-65f4-11e6-86df-e3a9091fa9c2.png)

<details>
Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.91.70 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.30 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.71 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.17 Enabled=YES

**Comment by Alex-302** [comment]
Один раз выскочило, больше повторить не удалось.
