### ISSUE TITLE
seasonvar.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2837]
![file_000](https://cloud.githubusercontent.com/assets/15856304/17802267/eae45bd0-65f7-11e6-86a9-f5015e3bf1fa.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-08-13 19:06:23 +0000

Device: iPhone
Platform: iPhone OS
OS: 10.0
ID: 712D2550-E6AC-4132-9E0F-D9F895D36C6C

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.91.83 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.31 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.77 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.38.3 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.18 Enabled=YES

**Comment by Alex-302** [comment]
На Маке в Сафари чисто. Скрин твой?

**Comment by evgeniy-ADG** [comment]
Мой.

**Comment by Alex-302** [comment]
Проверь с одним только русским фильтром.

**Comment by Alex-302** [comment]
Cafari не умеет блокировать веб-сокеты.
Попробуй такое:
```
seasonvar.ru##div[style="width: 227px;overflow: hidden;"]
```
