### ISSUE TITLE
https://forum.pokemobbot.com/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2839]
https://forum.pokemobbot.com/

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17809545/0c9fe3b6-6620-11e6-8bd1-589aac20ba07.png)
![image](https://cloud.githubusercontent.com/assets/15856304/17809552/166958d2-6620-11e6-9478-926e246d5ce7.png)
</details>

english, annoyances and other original adguard filters

**Comment by evgeniy-ADG** [comment]
There's kind of placeholder on the screen form iPhone...

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
@@||forum.pokemobbot.com^$generichide
```
