### ISSUE TITLE
https://www.penny-arcade.com/ broken by AdGuard Base Filter

### ISSUE THREAD

**Issue by Wizardling** [AdguardTeam/AdguardFilters#28405]
https://www.penny-arcade.com/ 's formatting and cosmetic elements are broken by the AdGuard Base Filter. See the screenshot below for an example from this PA comic's page: https://www.penny-arcade.com/comic/2019/01/16/audacious

![image](%screenshot_url%)
![image](https://user-images.githubusercontent.com/3980145/51287084-be15f680-1a5a-11e9-8a9d-43b7b693b0d7.png)

**Comment by Alex-302** [comment]
fixed
