### ISSUE TITLE
Adguard extension won't update automatically

### ISSUE THREAD

**Issue by tbcam88** [AdguardTeam/AdguardFilters#2840]
Alex,

I need to manually update filters for Adguard extension (Chrome) in order to keep it from allowing pop-ups through. Shouldn't the extension update filters automatically as soon as they're available?

Thanks.

**Comment by Alex-302** [comment]
They are udpates every 48 hours.

**Comment by tbcam88** [comment]
Mine isn't updating Alex. I'm having to manually update filters each time in order to keep extension updated...


________________________________

**Comment by Alex-302** [comment]
Maybe you are checking for updates  frequently than 48 hours.
