### ISSUE TITLE
qashqairussia.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2841]
**Description**:
qashqairussia.ru
При переходе по страницам форума на главной странице сайта у пользователя открывается казино и другие фишинговые сайты.
AdBlocker режет всплывающее окно. Очистка данных и кэша браузера не помогает. Сканировали malwarebytes тоже ничего не нашлось.
У меня не повторилось.

Видео: https://youtu.be/ocsOzWZZku8

Лог: 
[state (39).txt](https://github.com/AdguardTeam/AdguardFilters/files/428132/state.39.txt)
[debug (15).txt](https://github.com/AdguardTeam/AdguardFilters/files/428130/debug.15.txt)
в 12.25 внес изменения в логировании, затем пошёл на сайт, открыл раза три -четыре ветки и где то в 12.27 проблема повторилась

**Adguard version**: 2.7.220

**Filters list**: 2, 3, 4, 14, 10, 1, 11

**Browser**: Проблема во все браузерах (Mozilla Firefox, Chrome)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
А зачем полный лог? Меня только HTTP запросы интересуют. Вроде ничего подозрительного нет.
Пусть переделает заново, с полным закрытием браузера.
Возможно вредоносное приложение в телефоне. Можно ещё антивирусом пройтись.

**Comment by vgavrish** [comment]
Проверил несколькими антивирусами - ничего не найдено
Также: 
+ при отключении Adguard  проблема исчезает,
+ на firefox при включении ABP проблема тоже исчезает

[debug (29).txt](https://github.com/AdguardTeam/AdguardFilters/files/428790/debug.29.txt)

**Comment by Alex-302** [comment]
Странная история. Нужно HAR записать, только пусть не забудет запись выключить.
Такая реклама только на этом сайте выскакивает?

**Comment by Alex-302** [comment]
Уточни ещё, мобильный инет, или wifi.

**Comment by vgavrish** [comment]
* Проблема только на этом сайте,  в трех браузерах
* Как в мобильном интернете,  так и по wifi,  причем на разных точках.
* при отключении Адг начинают появляться банеры,  но перенаправление на сайт казино прекращается. 
HAR ждем

**Comment by Alex-302** [comment]
Возможно при детекте блокировщика скрипт альтернативной рекламы запускают, но не для всех регонов.

**Comment by vgavrish** [comment]
Har (в папке было всего два файла):
https://yadi.sk/d/4zw9RN8QuQ9sw

Также заходили с другого устройства на сайт (впервые), набрал в поиске название сайта, открыл, раз, два, и все повторилось. т.е. дело не в телефоне.

**Comment by Alex-302** [comment]
Теперь видно, откуда реклама.
Добавил в русский:
||qashqairussia.ru/script.php?

**Comment by ypetruk** [comment]
опять повторилась проблема, после обновления Android
HAR файлы, прикрепляю
https://www.dropbox.com/s/cztnm5a6wjgqw26/adguard%20%281%29.har?dl=0

Ticket ID: 1394206

**Comment by Alex-302** [comment]
Добавил старое правило в мобильный фильтр. Оптимизация выкосила.
