### ISSUE TITLE
http://www.filmz.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2842]
**Description**: http://www.filmz.ru/videos/35455/
Расширение. На странице отсутствует поле с комментариями при включенном Русском фильтре.

Screenshot:
<details>
![screenshot_10](https://cloud.githubusercontent.com/assets/18548949/17829083/d88f48c4-66aa-11e6-9c47-3303356ad29b.jpg)
![screenshot_11](https://cloud.githubusercontent.com/assets/18548949/17829084/d8909a6c-66aa-11e6-8b62-239fa03fe9e5.jpg)

</details>

**Filters list**: 1,2,3,4,14

**Browser**: Хром, Опера, Firefox

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Исправил
