### ISSUE TITLE
online.cd

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2843]
**Description**:
http://online.cd/filmy_2016/8117-den-vzyatiya-bastilii-2016-hd.html
При нажатии на плей видео открывается другой сайт, который сразу же и закрывается.

Screenshot:
<details>
![screenshot_3](https://cloud.githubusercontent.com/assets/18548949/17829515/ab931652-66b9-11e6-9a05-8504a65d678f.jpg)

</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром, IE 11

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Удалил
```
@@/mxtads.com\/[0-9]/$domain=couber.be
```

**Comment by Alex-302** [comment]
Нужно проверить, или чтоб юзер отписался.
