### ISSUE TITLE
Yandex direct

### ISSUE THREAD

**Issue by heru12343** [AdguardTeam/AdguardFilters#2844]
Опять проблемы с яндекс директом. 
![-](https://cloud.githubusercontent.com/assets/21025096/17832903/cbe4002a-6717-11e6-9e61-2af4e802735e.jpg)

Фильтры: Пользовательский, Английский, Фильтр счетчиков и систем аналитики, Фильтр виджетов социальных сетей,  Фильтр раздражителей, Русский фильтр, Anti-Adblock killer|reek

Windows 7, браузер Firefox

**Comment by Alex-302** [comment]
Версия Адгарда?

**Comment by heru12343** [comment]
6.0.226.1108

**Comment by Alex-302** [comment]
Посмотрите в коде страницы, есть ли секция `injected by Adguard`
или проверьте сертификат(поле "Кем выдан")

**Comment by heru12343** [comment]
Есть данная секция 
<script nonce="3Wjr4q/PBjCh72bxpkWiSA==">;(function(d,e,c,r){e=d.documentElement;c="className";r="replace";e[c]=e[c][r]("i-ua_js_no","i-ua_js_yes");if(d.compatMode!="CSS1Compat")e[c]=e[c][r]("i-ua_css_standart","i-ua_css_quirks")})(do.....

**Comment by heru12343** [comment]
![default](https://cloud.githubusercontent.com/assets/21025096/17837445/e661f08e-67bb-11e6-9574-8d5466239408.jpg)

**Comment by heru12343** [comment]
В общем проблема актуальна и на других компах, и, в том числе, в браузере Хром.

**Comment by Alex-302** [comment]
Ок, надо будет удалённо глянуть. Похоже код рекламы отличается.

**Comment by heru12343** [comment]
Проблема появилась сегодня на погоде https://yandex.ru/pogoda/kolomna/

**Comment by Alex-302** [comment]
Уже должно быть чисто.

**Comment by heru12343** [comment]
В погоде чисто, а в яндекс новостях как был директ, так и остался https://news.yandex.ru/?lang=ru

**Comment by heru12343** [comment]
Бесплатные блокировщики уже давно заблокировали в яндекс новостях яндекс директ.

**Comment by Alex-302** [comment]
Там довольно корявые правила, хоть и работают. Грядёт релиз, в котором возможности сокрытия элементов значительно расширены за счёт псевдо-классов.

**Comment by heru12343** [comment]
Эдгард обновил, фильтры все обновил, в ручную пробовал удалить, не помогает. Сегодня опять вылез надоедливый директ в новостях.

**Comment by heru12343** [comment]
Вобщем пообновлял страницы, фильтр срабатывает через раз или через 2

**Comment by heru12343** [comment]
Причем вначале вся страница подгружается, и только через 2 секунды выскакивает директ
