### ISSUE TITLE
www.hdizlefilmi.net -Free space

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2845]
Site: http://www.hdizlefilmi.net/kuzular-kurtlara-karsi-izle.html

**Screenshot:** 
Without ADGUARD ![1](https://cloud.githubusercontent.com/assets/19608513/17835855/fc323da0-678f-11e6-8e44-25f3781211a8.png)

With ADGUARD 
![2](https://cloud.githubusercontent.com/assets/19608513/17835860/0fb71080-6790-11e6-96d3-da8181c0550b.png)

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
For user filter:
```
hdizlefilmi.net##.video > br
```
