### ISSUE TITLE
hdfilmakinasi.com -background ad

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2846]
Site: http://www.hdfilmakinasi.com/mekanik-2-izle.html

Note: The link is this in the background.. http://hdfilmakinasi.com/ads/ukbet/ukbet-03.mp4

Adguard version: 2.4.6 beta

Operating system: Windows 10

Browser: Google Chrome

**Comment by Alex-302** [comment]
Added to Turkish filter
```
||hdfilmakinasi.com/ads/
```
