### ISSUE TITLE
hdfilmcehennemi.com -free space

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2847]
Site: http://www.hdfilmcehennemi.com/

Screenshot: 
![z](https://cloud.githubusercontent.com/assets/19608513/17836063/a0d31c7a-6796-11e6-96e8-b39be8ef0ad0.png)

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Social filter
```
hdfilmcehennemi.com##.facebookbox
```
