### ISSUE TITLE
hdfilmevreni.net -ad before video

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2848]
Site: http://hdfilmevreni.net/rebirth-2016-full-izle.html

Screenshot: 
![cx](https://cloud.githubusercontent.com/assets/19608513/17836076/14e5f1a0-6797-11e6-9510-418d5871d610.png)

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdfilmevreni.net#$##film { display: block!important; }
```

**Comment by thislife81** [comment]
Plz remove this.

![nw](https://cloud.githubusercontent.com/assets/19608513/18032731/5ef068aa-6d20-11e6-8567-5a0575580a0e.png)

**Comment by Alex-302** [comment]
hdfilmevreni.net###filmoncereklam
