### ISSUE TITLE
filmsezonu.net -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2849]
Site: http://www.filmsezonu.net/

Screenshot: 
![t](https://cloud.githubusercontent.com/assets/19608513/17836094/939a3fec-6797-11e6-9372-4127a9b885df.png)

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by thislife81** [comment]
Without Adguard. You can see ads
![x](https://cloud.githubusercontent.com/assets/19608513/17838132/305f4d70-67d6-11e6-93b8-a84d3e53ac1d.png)

With Adguard. Ads are removed for now, but they can put a new ad into the same places. You better remove the same places that I showed in the picture
![xa](https://cloud.githubusercontent.com/assets/19608513/17838141/73b0b94c-67d6-11e6-8ac7-ad96156ba455.png)

**Comment by Alex-302** [comment]
We can't hide them, because useful elements has the same code.
