### ISSUE TITLE
tubewolf.com [NSFW] [Ad Banner]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#28494]
**Site**: https://www.tubewolf.com/movies/married-white-lady-needs-that-black-cock-in-her-cunt/?promoid=1263

**Issue**: Empty ad banner on the video player.

**Screenshot**: http://prntscr.com/m98gpz

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 71.0.3578.98 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
Please fix

**Comment by slavaleleka** [comment]
@Nzzyme add to user filter temporary
`tubewolf.com##.bnnrs-player`
