### ISSUE TITLE
Website is detecting adGuard at start of video

### ISSUE THREAD

**Issue by vivshah56** [AdguardTeam/AdguardFilters#28490]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
The following website detects adguard at the beginning of a video
https://einthusan.tv/intro/

* **Current behaviour**: 
The website detects the presence of adguard and blocks the video from loading

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="988" alt="screen shot 2019-01-18 at 11 10 13 pm" src="https://user-images.githubusercontent.com/39109924/51423528-74bac980-1b76-11e9-87ce-3cb3442a571e.png">
![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

The video should play without detecting the presence of Adguard

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

1. Open the website : https://einthusan.tv/intro/
2. Click on "Hindi". It will take you to the following URL : https://einthusan.tv/launcher/?lang=hindi
3. Click on Movies. It takes you to https://einthusan.tv/movie/browse/?lang=hindi
4. Click on Any movie. Wait for the video to load. It detects adguard at this point

***System configuration***
MacOS, Google Chrome browser

**Filters:**

Adguard base filter (2.0.29.12)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | MacOS
Browser:                               | Google Chrome
AdGuard version:                       | Most recent version
Filters enabled:                       | Yes. Adguard base filter updated Jan 18 2019 (2.0.29.12)
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
vivshah56 not reproduced. Please check for filters update.
