### ISSUE TITLE
hdfilmifullizlesene.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2850]
Site: https://www.hdfilmifullizlesene.com/

Screenshot: 
![r](https://cloud.githubusercontent.com/assets/19608513/17836149/3c9c9256-6799-11e6-903a-059fddeb171b.png) (Enter the site, wait about 5seconds, you will see this)
![s](https://cloud.githubusercontent.com/assets/19608513/17836151/42fc6338-6799-11e6-8004-4154a3b12916.png)

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdfilmifullizlesene.com###spfadeinbox
hdfilmifullizlesene.com##a[href^="https://goo.gl/"][rel="nofollow"] > img
hdfilmifullizlesene.com#$#body { background: #000000!important; }
```

**Comment by thislife81** [comment]
And please remove these:
![01](https://cloud.githubusercontent.com/assets/19608513/17839289/eaae7854-67f4-11e6-926e-47dd0a5a48bd.png)

Rules: hdfilmifullizlesene.com##div.page:nth-child(3) > div.container > div.col-sm-12.nopadding:nth-child(5)
hdfilmifullizlesene.com##div.page:nth-child(3) > div.container > section.sidebar.col-md-4:last-child > aside > div.panel.text-center:nth-child(2)

**Comment by Alex-302** [comment]
For user filter:
`hdfilmifullizlesene.com##.col-sm-12.nopadding`

**Comment by thislife81** [comment]
And this? 
![de](https://cloud.githubusercontent.com/assets/19608513/18032720/f8351ae8-6d1f-11e6-85f1-d63e2aa13202.png)
