### ISSUE TITLE
webmd.com [Incorrect Blocking]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#28502]
**Site**: https://www.webmd.com/brain/brain-swelling-brain-edema-intracranial-pressure#2

**Issue**: Video/flash player not playing as seen in the screenshot.

**Screenshot**: http://prntscr.com/m9apog

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 71.0.3578.98 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by adranger** [comment]
The `Spyware list` should block `trustarc.com` and `truste.com`.

**Comment by Nzzyme** [comment]
Please fix guys

**Comment by adranger** [comment]
@Nzzyme please don't leave comments like that on Github. They just create useless notifications to us. This issue is still open, so they're eventually going to fix it.

**Comment by Nzzyme** [comment]
@AdamWr : Please fix

**Comment by Nzzyme** [comment]
@adranger: You chose to comment on this issue and thereby were 'subscribed' for any further notification. Your comment might be correct but understand that different users have different versions, filters, platform, etc and so not all can reproduce the issue. When I post a comment, it is a follow-up as the issue was not resolved even after 2 months. If you do not want to receive the notification, please unsubscribe from them. Nobody asked you to comment nor ask you for your help.

**Comment by AdamWr** [comment]
I can't reproduce it.

**Comment by adranger** [comment]
@Nzzyme, your useless comments are received by the maintainers of the projects as well. Open source projects are maintained by volunteers with their free time, so you need to wait patiently. Leaving more comments just saying "plz fix nao" just make people less motivated to solve the issues you report.

**Comment by Nzzyme** [comment]
@AdamWr : I think the issue is with the following filter added to the 'AdGuard Base Filter'

`||media.net^$third-party`


Looking at the Filtering Log, I am seeing an infinite number of connections from the following domain:

`https://cdneast2-xch.media.net/...`

Screenshots:


I just checked again after

**Comment by zloyden** [comment]
I can't reproduce it.
