### ISSUE TITLE
www.onlinemoviesgold.us- popup

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2851]
Site: http://www.onlinemoviesgold.us/

Note: Click anywhere on the site, you will get a popup immediately. 

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Can't reproduce.
Added
```
onlinemoviesgold.us##a[href="http://www.onlinemoviesgold.us/movies/go/"] > img
onlinemoviesgold.us##.osd-sms-wrapper
```
