### ISSUE TITLE
olke.az -ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2852]
Site: http://www.olke.az/olke-2/havanin-temperaturu-42-dereceye-catacaq-64507

**Screenshot1:** You can see this as soon as enter the site. 
![1a](https://cloud.githubusercontent.com/assets/19608513/17836585/a3bf4118-67a8-11e6-9bd6-997b593ed8c0.png)

**Screenshot2:** 
![2a](https://cloud.githubusercontent.com/assets/19608513/17836586/b8005798-67a8-11e6-90ab-8656f3836faa.png)

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to English filter
```
olke.az##.modal.in
olke.az##.modal-backdrop.in
olke.az##div[style$="height: 90px; text-align: center"]
||olke.az/ads/
olke.az##.adsbyskyline

```
Added to Social filter
```
olke.az##.momizat-facebook
```

**Comment by thislife81** [comment]
All of these are ads. (Without ADGUARD) 
![1z](https://cloud.githubusercontent.com/assets/19608513/17838604/644ec0be-67e2-11e6-8c72-5bd82b2f5b01.png)

By the way, you can also remove this, (With ADGUARD)
![2z](https://cloud.githubusercontent.com/assets/19608513/17838610/7bb29e1a-67e2-11e6-98fc-ef109c9e20cd.png)

**Comment by Alex-302** [comment]
Added to annoyances
olke.az##div[class="mom_visibility_desktop center"][style="padding-left: 4px"]
