### ISSUE TITLE
[nsfw] youporn.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2853]
**Current behaviour**: broken interface

Screenshot: 
<details>
![screen shot 2016-08-21 at 4 35 22 pm](https://cloud.githubusercontent.com/assets/14153331/17839679/5c7f3992-67bd-11e6-8c08-3a1fc080ba6b.png)
</details>

**Adguard version**: Mac 1.3.0, Win 6.1.252.1283

**Filters list**:
![screen shot 2016-08-21 at 4 37 45 pm](https://cloud.githubusercontent.com/assets/14153331/17839686/9ad0ea42-67bd-11e6-9262-5b944b9a87f2.png)

**Comment by Alex-302** [comment]
can't reproduce

**Comment by Bohdan-SUP** [comment]
Just reproduced the same issue on Win 6.1.252 with following filters:
![image](https://cloud.githubusercontent.com/assets/14153331/17853186/ad26606c-6873-11e6-8051-b6fbb70caaa3.png)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||static.youporn.phncdn.com/cb/assets/css/$domain=youporn.com

```
