### ISSUE TITLE
Rework list of filters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2854]
1. Make "List-KR" the only default Korean filter
2. Reorder filters (the order is pretty random now)
3. @Alex-302 include "unbreak.txt" into our Safari Filter and remove it from the List-KR:

```
@include "https://raw.githubusercontent.com/SlowMemory/List-KR/master/unbreak.txt" /exclude="exclusions.txt"
```

**Comment by mmigi** [comment]
1st is done.

**Comment by Alex-302** [comment]
#3 - done
