### ISSUE TITLE
[adblock detect] kurnik.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#28554]
**Site Sample** | 
-----------------------------|
https://www.kurnik.pl/netopol/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Chrome Stable x64
AdGuard version:                       | **6.4.1840.4955**
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
| **Filters enabled**
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| CoinBlockerLists
| EasyList Polish 
| Fanboy's Annoyances
| Fanboy's Enhanced Tracking List 
| Fanboy's Social Blocking List 
| I don't care about cookies
| KAD - fraud/scam 
| Malware Domains
| NoCoin Filter List 
| Peter Lowe's List
| Polish Annoyances
| Polish Main
| Polish Social

### Issue:

Adblock detect **AFTER** login to any sub game pages

<details><summary><b>Screenshot:</b></summary>

![scr-1548001131-001](https://user-images.githubusercontent.com/9846948/51442060-f591d680-1cd8-11e9-8193-4068348d1033.png)
![scr-1548001150-001](https://user-images.githubusercontent.com/9846948/51442061-f591d680-1cd8-11e9-8424-3000d9f4ad29.png)

</details><br/>

@AdamWr

**Comment by AdamWr** [comment]
Niestety nie potrafię tego odtworzyć.
Mógłbyś proszę włączyć listę `Polish Anti Adblock Filters`, zaktualizować filtry i sprawdzić czy problem nadal występuje?

**Comment by FadeMind** [comment]
@AdamWr na jaki adres e-mail ma wysłać Tobie HAR po zalogowaniu się na kurnik? Nie będę go udostępniał tutaj ;P

**Comment by FadeMind** [comment]
Poszło ;)

**Comment by AdamWr** [comment]
Ok, dostałem, dziękuję.
Niedługo sprawdzę.

**Comment by AdamWr** [comment]
Mógłbyś proszę sprawdzić te dwie reguły:
`kurnik.pl#@$#.adsbygoogle { height: 1px !important; width: 1px !important; }`
`kurnik.pl#$#.adsbygoogle { display: block!important; height: 2px !important; width: 1px !important; }`
a jakby nie działały to tę:
`kurnik.pl#%#Object.defineProperty(window, 'abask', { get: function() { return; } });`

**Comment by FadeMind** [comment]
Pierwsze dwie linie kodu działają poprawnie. Dzięki ;)

**Comment by AdamWr** [comment]
Dodałem, dziękuję za sprawdzenie.
