### ISSUE TITLE
Rework filters groups

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2855]
I suggest using the following structure.

@Alex-302 what do you think?
## Adguard General
- English filter
- Spyware filter
- Social media filter
- Annoyances filter
- Filter unblocking useful ads
- Experimental filter
- Mobile ads filter
- Safari filter
## Adguard Language-Specific
- Russian filter
- German filter
- Turkish filter
- Japanese filter
- Dutch filter
- Spanish/Portuguese filter
## EasyList
- EasyList
- ABPindo
- Adblock Polska
- Bulgarian list
- EasyList China
- EasyList Czech and Slovak
- EasyList Dutch
- EasyList Germany
- EasyList Germany
- EasyList Hebrew
- EasyList Italy
- EasyList Lithuania
- Icelandic ABP List
- Latvian List
- Liste AR
- Liste FR
- Norsk adblockliste
- ROList
- RU AdList
- void.gr
- Wiltteri
## Privacy Protection
- EasyPrivacy
- Fanboy's Enhanced Tracking List
- RU AdList: Counters
## Annoyances
- Adblock polskie reguły cookies
- Adblock Warning Removal
- Adblock Warning Removal List
- Anti-Adblock Killer
- CJX's Annoyance List
- Fanboy Annoyances
- Fanboy Anti-Facebook List
- Fanboy Social
- I dont care about cookies
- Polski social filtr
- Prebake
- RU AdList: BitBlock
## Other
- ABP Japanese Filters
- ABPVN List
- Adblock polskie reguły
- Adblock-Persian list
- ChinaList+EasyList
- Czech List
- Fanboy's Swedish
- FanboyEspanol
- Filtros Nauscopicos
- hufilter
- Korean Adblock List
- Malware Domains
- Peter Lowe's list
- Schacks Adblock Plus liste
- Spam404
- Xfiles
- xinggsf

**Comment by Alex-302** [comment]
I'm agree, except Wiltteri and Norsk. I think we should move them to Other
