### ISSUE TITLE
http://hdrezka.me/ - missed placeholder

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2858]
http://hdrezka.me/series/drama/18289-otzhig.html

![image](https://cloud.githubusercontent.com/assets/15856304/17857982/967df94c-688c-11e6-9f3a-d4e8a0bacc8b.png)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/17857989/a0fc4db0-688c-11e6-9c6f-542652163769.png)

**Comment by Alex-302** [comment]
На этом сайте не стоит остатки трогать, однажды плеер может пропасть.
