### ISSUE TITLE
http://kinokong.net/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2859]
http://kinokong.net/17473-film-den-nezavisimosti-2-chast-1-2015-online.html
![image](https://cloud.githubusercontent.com/assets/15856304/17858106/01dad1d8-688d-11e6-90c8-2d0cebd2d8c5.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
kinokong.net###hotnewsline

```
