### ISSUE TITLE
https://e.mail.ru/messages/inbox/ - hide mail.ru agent 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2860]
Please help us with this question, user wants to hide the Agent.
Russian, English and Annoyance filters are on.

![image](https://cloud.githubusercontent.com/assets/15856304/17858319/dc8bcfd0-688d-11e6-9219-a4488532c2a7.png)

**Comment by Alex-302** [comment]
в пользовательский
```
e.mail.ru###wa-root
```
