### ISSUE TITLE
AdChoice ads appearing in many websites using AdGuard for Safari extension despite filter block enabled

### ISSUE THREAD

**Issue by tadatildy** [AdguardTeam/AdguardFilters#28604]
**Description:**

 Adchoice ads appear pervasively on multiple websites even though AdGuard for Safari Settings/General "Allow search ads and the self-promotion of websites" is turned off/disabled (set on red, not green) and AdGuard Base filter (including EasyList and AdGuard English) is enabled

**Steps to reproduce the problem:**

1. Open Safari with AdGuard as the only extension enabled, with AdGuard filters enabled from "Filters" list below.

2. Go to https://appleinsider.com or https://forums.macrumors.com or https://www.wikihow.com/Determine-Gear-Ratio or https://9to5mac.com or https://www.theverge.com/2019/1/19/18189785/apple-iphone-se-on-sale-clearance or https://forums.dragcave.net 

3. View AdChoice ads on page

**Expected behavior:**

AdChoice ads should be blocked

**Actual behavior:**

AdChoice ads appearing

**Screenshot:**

<img src="https://i.imgur.com/pCTmXlG.png">

<img src="https://i.imgur.com/sKLb2dF.png">

**Details/comments:**

I am seeing AdChoice ads on multiple websites appearing pervasively; see above list for some examples.  I am requesting that they be removed automatically using AdGuard for Safari extension. I could block individual elements in a User filter, but I don't want to have to do that, especially when they are AdChoice ads. I am reporting this as a bug as I don't believe they are intended to appear, especially with EasyList enabled.

**System configuration**

AdGuard for Safari version: 1.2.1
Environment name and version: Safari Version 12.0.2 (14606.3.4)
Operating System: macOS Mojave 10.14.2

**Filters you use in AdGuard:**

Ad BLocking (AdGuard Base filter), AdGuard Spyware filter, AdGuard Social Media filter, AdGuard Annoyances filter, Adblock Warning Removal list, Malware Domains, Spam404, NoCoin Filter List, AdGuard Safari Filter

**Any other browser extensions you have installed:***

None that are active/enabled

**Comment by tadatildy** [comment]
Note: I just tried another extension, Ka-Block! and it blocked these ads, so something is definitely wrong.

**Comment by zloyden** [comment]
Is it still relevant? No ads on my side.
