### ISSUE TITLE
stopgame.ru

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#2861]
Some rule (looks like it is in **Russian** filter) breaks videoplayer.

str:
- open  http://stopgame.ru/gamemovie/show/387/hq
- scroll down a little and click on video to play it
- you are expected to see an endless loading loop like this:
<details>
![gg9p2k4pwtu](https://cloud.githubusercontent.com/assets/17472907/17863456/57dfb93a-68a2-11e6-9690-582476d5f5c8.jpg)
</details>

**Comment by Alex-302** [comment]
It's not working on my end without Adguard.

**Comment by vozersky** [comment]
Still can reproduce in chrome. Did you turn of Adguard extension as well?

**Comment by Alex-302** [comment]
It works as expected now. Check it again.

**Comment by vozersky** [comment]
Still have this issue in Chrome on Mac, easily reproduced, happens every time actually

**Comment by Alex-302** [comment]
Still can't reproduce on Mac

**Comment by vozersky** [comment]
Issue still happens every time, try to use russian ip

**Comment by gshumihin** [comment]
_Issue still happens every time, try to use russian ip_
Same for me.

**Comment by Alex-302** [comment]
It works on @vozersky 's notebook.
