### ISSUE TITLE
http://www.optyczne.pl/ - anti-adblocker script

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2862]
![Uploading Screenshot at Aug 22 23-09-57.png…]()

<details>
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:10 Name: Filter for useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:216 Name: Adblock polskie reguły Url: https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt
FilterId:0 Name: User filter Url: no_url

**Comment by evgeniy-ADG** [comment]
Sorry, it doesn't upload pics, but you'll see the message. Will try later.

**Comment by Alex-302** [comment]
Added
```
optyczne.pl###warning[style^="z-index:"]
```
