### ISSUE TITLE
[adblock detect] windowscentral.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#28632]
**Site Sample** | 
-----------------------------|
https://www.windowscentral.com/how-use-dism-command-line-utility-repair-windows-10-image

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Chrome Stable x64
AdGuard version:                       | **6.4.1840.4955**
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
| **Filters enabled**
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| CoinBlockerLists
| EasyList Polish 
| Fanboy's Annoyances
| Fanboy's Enhanced Tracking List 
| Fanboy's Social Blocking List 
| I don't care about cookies
| KAD - fraud/scam 
| Malware Domains
| NoCoin Filter List 
| Peter Lowe's List
| Polish Annoyances
| Polish Anti Adblock Filters
| Polish Main
| Polish Social

### Issue:

Adblock detect 

<details><summary><b>Screenshot:</b></summary>

![scr-1548170980-001](https://user-images.githubusercontent.com/9846948/51545863-2b62c680-1e63-11e9-8fd9-3fcd64371869.png)

</details><br/>

@AdamWr

**Comment by AdamWr** [comment]
Added to Annoyances filter:
```
@@||windowscentral.com/sites/all/libraries/adblockdetection/adblockDetector.min.js
windowscentral.com#$#.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links { display:block!important; }
windowscentral.com#%#Object.defineProperty(window, 'initDetection', { get: function() { return; } });
```
