### ISSUE TITLE
kinomania.ru 

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2863]
**Description**: Реклама в видео плеере. **Расширение**.

Screenshot:

<details>
![screenshot_12](https://cloud.githubusercontent.com/assets/18548949/17870483/62923614-68c0-11e6-8093-3d91bf8569f2.jpg)

</details>

**Filters list**: 1,2,3,4,5,14

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил:
```
||kinomania.ru/js/preAdvPlay.js
```
Нужно чтоб юзер отписался.
