### ISSUE TITLE
Add Fanboy Secure filter to subscriptions

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2864]
https://secure.fanboy.co.nz/filters.html

**Comment by TPS** [comment]
https://easylist.to/2013/05/17/easylist-merges-with-fanboy-s-list.html several years ago.…  What's the advantage in this? 😕

**Comment by ameshkov** [comment]
In fact some of fanboys filters aren't merged (like enhanced tracking list).

Anyway, these filters are already available in all AG versions (except Android, let's wait for v3.0)
