### ISSUE TITLE
http://imgchilibum.ru/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2865]
**Description**: Реклама вверху. **Расширение.**
http://imgchilibum.ru/v.php?id=ec14be70d7a754a81f4d54a59c71209b

Screenshot:
<details>
![screenshot_13](https://cloud.githubusercontent.com/assets/18548949/17899520/42070cea-6964-11e6-966c-6db108576e91.jpg)

</details>

**Filters list**: 1,2,3,4,5,14

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
imgchilibum.ru#%#window.open = function() {};
||imgchilibum.ru/cod2.js
||kit5hgver.com^$third-party
||meendocash.com^$third-party
```
