### ISSUE TITLE
Adblock detected at start of video

### ISSUE THREAD

**Issue by vivshah56** [AdguardTeam/AdguardFilters#28667]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Adguard is detected at the start of the video
https://einthusan.tv/movie/watch/7cWt/?lang=hindi

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
<img width="1024" alt="screen shot 2019-01-22 at 9 37 46 pm" src="https://user-images.githubusercontent.com/39109924/51585392-08014100-1e8e-11e9-90b9-716a552cbad5.png">

<img width="1004" alt="screen shot 2019-01-22 at 9 37 52 pm" src="https://user-images.githubusercontent.com/39109924/51585395-0cc5f500-1e8e-11e9-9ec2-f0da0a55b71e.png">

</details><br/>
<img width="661" alt="screen shot 2019-01-22 at 9 36 18 pm" src="https://user-images.githubusercontent.com/39109924/51585321-c7a1c300-1e8d-11e9-8f69-77461cda5aa4.png">

* **Expected behaviour**: 

Video should play without detecting adguard

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

Open the URL : https://einthusan.tv/movie/watch/7cWt/?lang=hindi

Wait for the video to load (It will say pinging available sources, loading source, etc. Just wait till the actual video loads). Wait till you see the "Play" symbol. Notice that the video does not load. Instead adblock is detected

***System configuration***

**Filters:**

Adguard base filter (2.0.29.66), AdGuard Annoyances filter (2.0.13.45)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
Operating system:                      | MacOS
Browser:                               | Google Chrome
Filters enabled:                       | Yes

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
The video is not working on my MacOS without AG.
@slavaleleka please check it.

**Comment by vivshah56** [comment]
@Alex-302 Try this URL : https://einthusan.tv/movie/watch/3x0C/?lang=hindi
Same steps to reproduce.

**Comment by Alex-302** [comment]
@vivshah56 I don't have real Mac, video is not working in VM.

**Comment by vivshah56** [comment]
@Alex-302 Operating System does not matter. The adblock gets detected in Google Chrome even on Windows 10

**Comment by Alex-302** [comment]
Can't reproduce
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/52051113-3dc3bb00-255b-11e9-9cfd-d206059cca15.png)
</details>

Please check this rule:
`@@||einthusan.tv^$urlblock`

and upload saved page, when ad blocker is detected.

**Comment by vivshah56** [comment]
@Alex-302 Added the following line in User Filters : @@||einthusan.tv^$urlblock
Still detects the ad blocker when video actually loads

**Comment by Alex-302** [comment]
@vivshah56 do you use another ad blockers?
Please upload saved page.

**Comment by vivshah56** [comment]
No I only use Adguard. Here are my screenshots that show all my filters used and also my user filters

<img width="1291" alt="screen shot 2019-02-06 at 12 41 27 am" src="https://user-images.githubusercontent.com/39109924/52329689-47f51780-29a8-11e9-9333-9977c42eb811.png">
<img width="1193" alt="screen shot 2019-02-06 at 12 41 42 am" src="https://user-images.githubusercontent.com/39109924/52329697-4b889e80-29a8-11e9-8bcf-bed3aa23315b.png">
<img width="1249" alt="screen shot 2019-02-06 at 12 42 21 am" src="https://user-images.githubusercontent.com/39109924/52329765-6fe47b00-29a8-11e9-9dea-413310d741bf.png">
<img width="1153" alt="screen shot 2019-02-06 at 12 42 27 am" src="https://user-images.githubusercontent.com/39109924/52329781-74109880-29a8-11e9-8082-832e92b41409.png">

**Comment by Alex-302** [comment]
Ok, please open filtering log and make screenshot(select `Blocked` checkbox)

**Comment by vivshah56** [comment]
@Alex-302 It is empty

<img width="1224" alt="screen shot 2019-02-07 at 12 59 16 am" src="https://user-images.githubusercontent.com/39109924/52400305-a9ce8380-2a73-11e9-8a73-fb32105e0536.png">

**Comment by Alex-302** [comment]
You need to reproduce an issue before making screenshot. Filtering log does not collect information when it is closed.

**Comment by vivshah56** [comment]
@Alex-302 Here it is 
<img width="1421" alt="screen shot 2019-02-11 at 11 47 03 pm" src="https://user-images.githubusercontent.com/39109924/52619758-77e46500-2e57-11e9-970a-a754561fb62b.png">

**Comment by Alex-302** [comment]
Strange. Do you use another ad blockers?
Please check without the filters.

**Comment by vivshah56** [comment]
@Alex-302 No I only use Adguard. I removed all the filters except 'Adguard base filter". Updated it to the most recent version. Its still not working. Below are the screenshots of the filtering log

<img width="1313" alt="screen shot 2019-02-19 at 12 20 21 am" src="https://user-images.githubusercontent.com/39109924/53000131-82b17380-33dc-11e9-91f4-e23b0ba0a766.png">

<img width="1312" alt="screen shot 2019-02-19 at 12 20 33 am" src="https://user-images.githubusercontent.com/39109924/53000137-88a75480-33dc-11e9-829d-45e6ce0354e1.png">

<img width="1313" alt="screen shot 2019-02-19 at 12 20 43 am" src="https://user-images.githubusercontent.com/39109924/53000142-9066f900-33dc-11e9-83c8-000ee70bbed6.png">
<img width="1307" alt="screen shot 2019-02-19 at 12 20 51 am" src="https://user-images.githubusercontent.com/39109924/53000162-98bf3400-33dc-11e9-8d62-ff31050bd5a4.png">

**Comment by Alex-302** [comment]
Could you, please, try to exclude these elements? (just click on blocked element and create suggested rule)
![image](https://user-images.githubusercontent.com/8361299/53017542-e4afbe80-3458-11e9-9540-ca6c26b9b74f.png)
![image](https://user-images.githubusercontent.com/8361299/53017619-13c63000-3459-11e9-95ee-eae4a43fbb6b.png)
![image](https://user-images.githubusercontent.com/8361299/53017657-2d677780-3459-11e9-972c-77e26105808b.png)

**Comment by vivshah56** [comment]
@Alex-302 Only the ones that you have highlighted or do I unblock all of the blocked elements? I did try excluding the above and also unblock and create rule for all of the blocked elements. But the next time it loaded a different list of blocked elements

**Comment by Alex-302** [comment]
ok, please check separately
```
@@||einthusan.tv^$generichide
```
```
@@||einthusan.tv^$generichide
```

**Comment by vivshah56** [comment]
@Alex-302 Thank you for your help! After some debugging, adding just this rule resolved it :  
@@||vid.springserve.com/vast/*$important,third-party

No other rules are needed

**Comment by vivshah56** [comment]
Though the ad does not load when the Play button is clicked, it does try to load the ads and hence a 'Loading advertisement' comes and stays for about a minute. But the advertisement does not play. From a user experience it would have been nice if this was avoided - but I think that cannot be prevented :)

<img width="1015" alt="screen shot 2019-02-20 at 8 01 27 pm" src="https://user-images.githubusercontent.com/39109924/53142912-a1ce1380-354a-11e9-817f-94b461ba7ca4.png">

**Comment by Alex-302** [comment]
Strange. Better add `||vid.springserve.com/vast/*einthusan.tv$empty,important,badfilter`

**Comment by vivshah56** [comment]
Changed my rule and added the above one. This issue can be closed.
