### ISSUE TITLE
adguard mobile has stopped Disqus from opening on Rawstory.com on all pages...

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardFilters#28675]
@silat commented on [Wed Jan 23 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2452)

### Steps to reproduce

1. Samsung S8 Open Raw Story in Firefox. Click on Disqus banner to make comment
2.Disqus will not open
3. Disable Adguard Mobil Ads Filter in Ublock Origin for Android
4. Disqus opens with Adquard filter disabled

### Expected behavior

Disqus should open. It has previously.

### Actual behavior

Disqus will not open..

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version:20465
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: (e.g. Google Pixel) Samsung S8Plus
* Operating system and version (e.g. Android 7.1.2) Android 8
* Rooted or not? Not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? Nope

**Comment by zzebrum** [comment]
@silat please provide us with the link to the webpage and a screenshot with the banner.

**Comment by Alex-302** [comment]
Disqus is not blocked on my end. Which filter causes it?

**Comment by silat** [comment]
Cut and paste from my original post:
Samsung S8 Open Raw Story in Firefox. Click on Disqus banner to make comment
2.Disqus will not open
Disable Adguard Mobil Ads Filter in Ublock Origin for Android
Disqus opens with Adquard filter disabled

https://www.rawstory.com/2019/01/mueller-targeted-foreign-bank-investigated-federal-reserve-230-billion-sketchy-payments/

**Comment by Alex-302** [comment]
I can't reproduce it with AdGuard. 
Disqus is broken by one of uBO  filters(maybe JS rule)

**Comment by silat** [comment]
The fact that I turned off the adguard and everything was fine doesn't
mean that it's the adguard filter?
Okay how do I clear out a ubo filter on Android? I'm a bit lost on how to
edit.

**Comment by Alex-302** [comment]
try to disable uBO filters in settings and check the site

**Comment by silat** [comment]
Disabling ublock filters stopped the problem just like disabling adguard
filter stopped the problem. But that's not a great solution for me as it
then allows every other add to show its ugly face on the site. And there
are a lot of obtrusive ads.
Can you tell me if there is a filter in the ad guard filter that prevents
the comments from opening? If so how do I go about editing the filters?

**Comment by Alex-302** [comment]
I can't reproduce an issue with AdGuard or uBO with our filters, but disabled uBO filters. You can find `##+` rule in the filtering log, copy it to custom filter and replace `##` by `#@#`

**Comment by silat** [comment]
Can you tell me where I find the filtering log on Android?

**Comment by Alex-302** [comment]
In Firefox menu. uBO has is in mobile version. Here
![image](https://user-images.githubusercontent.com/8361299/51645126-82f45580-1f7b-11e9-84f3-c29594629c0b.png)
and refresh the tab when you open filtering log.

**Comment by silat** [comment]
Thanks..
