### ISSUE TITLE
www.unutulmazfilmler.co -free spaces

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2867]
Site: http://unutulmazfilmler.co/

Screenshot: Without ADGUARD. These spaces are for ads.
![1](https://cloud.githubusercontent.com/assets/19608513/17907613/ceb0b334-698d-11e6-97cc-1b4a853fb777.png)

Screenshot: With ADGUARD. Please remove these free spaces
![2](https://cloud.githubusercontent.com/assets/19608513/17907646/ee0607c0-698d-11e6-9f26-52ab6d0407d6.png)

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
unutulmazfilmler.co##.widget-wrapper[-ext-has='.fb-like-box']
unutulmazfilmler.co##.widget-wrapper[-ext-has='#woca-social-widget']
unutulmazfilmler.co###text-2.widget-odd
```
They are not supported by  2.4.6. You can install beta version or wait for release.

**Comment by thislife81** [comment]
I'm using 2.4.10 (beta), but it is not remoded yet

**Comment by Alex-302** [comment]
Please check them in user filter.
