### ISSUE TITLE
[incorect blocking] onlineradiobox.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#28674]
**Site Sample** | 
----------------|
https://onlineradiobox.com

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Chrome Stable x64
AdGuard version:                       | **6.4.1840.4955**
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
| **Filters enabled**
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| EasyList Polish 
| Fanboy's Annoyances 
| Fanboy's Cookiemonster List
| Fanboy's Enhanced Tracking List 
| Fanboy's Social Blocking List 
| KAD - fraud/scam 
| Malware Domains
| NoCoin Filter List 
| Peter Lowe's List
| Polish Annoyances
| Polish Anti Adblock Filters
| Polish Cookies
| Polish Main
| Polish Social

### Issue:

Please ALLOW login to onlineradiobox via Social Networks - there is no other way here. 

**WHEN ADGUARD IS ENABLED**
![a](https://i.imgur.com/r4OMSnD.png)

**WHEN ADGUARD IS DISABLED** 
![b](https://i.imgur.com/8HGMTg7.png)

@AdamWr

**Comment by AdamWr** [comment]
To wina listy `Fanboy's Annoyances/Fanboy's Social Blocking List`.
Możesz dodać te reguły do własnych filtrów żeby to odblokować:
```
onlineradiobox.com#@#a[title="Facebook"]
onlineradiobox.com#@#a[title="Google+"]
onlineradiobox.com#@#a[title="Twitter"]
onlineradiobox.com#@#a[title="ВКонтакте"]
```
