### ISSUE TITLE
www.tekfullhdfilmizle.com -ad

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2868]
Site: http://tekfullhdfilmizle.com/vikings-3-sezon-9-bolum-izle-turkce-altyazili.html

Screenshot: 
![ax](https://cloud.githubusercontent.com/assets/19608513/17907961/52617280-698f-11e6-961f-2e4772281373.png)

Adguard version: 2.4.6

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
tekfullhdfilmizle.com###Video-Oncesi
tekfullhdfilmizle.com#$##Movie-video { display: block!important; }

```
