### ISSUE TITLE
http://www.15min.lt - placeholder

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2869]
![image](https://cloud.githubusercontent.com/assets/15856304/17908203/236e9996-6988-11e6-9f64-6ff47a3426dd.png)
http://www.15min.lt/m/id/sportas/kita/rio-tikslai-ir-realybe-kas-stebino-pasiekimais-o-kas-tik-dalyvavo-26-671787

<details>
Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.0.92.12 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.7.34 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.11.83 Enabled=YES

ID=14 Name="Annoyances filter" Version=1.0.3.1 Enabled=YES

ID=11 Name="Mobile Ads filter" Version=1.0.4.69 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.1.20 Enabled=YES

ID=110 Name="EasyList Lithuania" Version=1.0.0.86 Enabled=YES

ID=117 Name="Adblock Polska" Version=1.0.0.52 Enabled=YES

ID=207 Name="Adblock Warning Removal List" Version=1.0.64.4 Enabled=YES

ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES

**Comment by Alex-302** [comment]
Added to English filter
```
15min.lt##.ads
```

**Comment by kaskurkada** [comment]
I see no changes, the white space is still left in the main portal www.15min.lt (you need to scroll down a little bit), also in every article you open - on top.

**Comment by Alex-302** [comment]
Please make screenshot. I don't see it.
