### ISSUE TITLE
gadgetdetective.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2871]
**Description**: no Assistant + broken interface

Adguard ON:
<details>
![adg_on](https://cloud.githubusercontent.com/assets/14153331/17933632/8037e598-6a1d-11e6-875b-82f6e8cd8791.png)
</details>

Adguard OFF:
<details>
![adg_off](https://cloud.githubusercontent.com/assets/14153331/17933556/2cf31092-6a1d-11e6-8064-852692161dcb.png)
</details>

**Adguard version**: Mac 1.3.0, Win 6.1.255.1291

**Filters list**:
<details>
![filters](https://cloud.githubusercontent.com/assets/14153331/17933598/642010ce-6a1d-11e6-977d-a8675b9681e5.png)
</details>

**Comment by Alex-302** [comment]
With/without Adguard on my end:
<details> 
![aaa](http://imagizer.imageshack.com/img924/3374/m1rY3q.png)
</details>
Assistant is not broken by filters.
