### ISSUE TITLE
smartsource.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2873]
**Steps to reproduce the problem**:

* go to smartsource.com
* select a coupon
* click Print Coupons

**Achieved result**: http://imgur.com/O8jabvB

**Expected result**: http://imgur.com/xmoFTMy

**Filters list**:
http://i.imgur.com/L3GRtGq.png

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||online-metrix.net/*/tags.js$domain=smartsource.com
```
please check it

**Comment by Bohdan-SUP** [comment]
Still not working for me. Tried adding the rule to User Filter, but still get the error.

**Comment by Alex-302** [comment]
try in private tab

**Comment by Bohdan-SUP** [comment]
Tried it in Private at that moment. Seems to be working now.
