### ISSUE TITLE
forum.worldoftanks.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2874]
**Description**: Useful pop-up is blocked

Forum topic to check:
http://forum.worldoftanks.ru/index.php?/topic/1800027-%D1%87%D0%B8%D1%82%D1%8B-%D0%B2-%D0%B8%D0%B3%D1%80%D0%B5/page__p__44085472#entry44085472

**Adguard on**
<details>
![on](https://cloud.githubusercontent.com/assets/14153331/17943355/b287eb08-6a43-11e6-91d3-693bec219f9a.png)
</details>

**Adguard off**
<details>
![off](https://cloud.githubusercontent.com/assets/14153331/17943362/bb84958a-6a43-11e6-978a-05b3f2a4dc1e.png)
</details>

**Filters list**:
<details>
![filters](https://cloud.githubusercontent.com/assets/14153331/17943372/c4ba5892-6a43-11e6-8793-bcd5441154f2.png)
</details>

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||googletagmanager.com/gtm.js$domain=forum.worldoftanks.ru
```
