### ISSUE TITLE
KLP.no - Login options are blocked (AdGuard Spyware filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#28754]
### Affected site:
`https://www.klp.no/`

### Issue:
All login options are blocked @ `https://www.klp.no/minside/`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* AdGuard Spyware filter

### Problem rule:
`/tracking/tracking.js`

### Blocked script:
`https://klpinteraktiv.klp.no/person/plugins/komponentbiblioteket/utils/tracking/Tracking.js`

### Possible fix:
`@@||klp.no/person/plugins/komponentbiblioteket/utils/tracking/Tracking.js$script`

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.3.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.7 (XUL)

**Comment by Alex-302** [comment]
Fixed
