### ISSUE TITLE
https://society6.com/- incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2876]
https://society6.com/prismwizard

All graphical elements are being blocked, profile image at top left, 3 icons with images in them above 'art prints" "framed art prints" and "canvas prints" and 2 images under the "latest" header
![image1](https://cloud.githubusercontent.com/assets/15856304/17945554/5dd8eee4-6a12-11e6-8491-200f8a5fac0d.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-08-15 23:26:31 +0000

Device: iPad
Platform: iPhone OS
OS: 10.0
ID: B0897BCC-1BE8-45EC-B5BE-1905F660C3B8

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.91.62 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.27 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.62 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.91 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.64 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.17 Enabled=YES

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||society6.com^$domain=society6.com
```
