### ISSUE TITLE
http://m.booktxt.net/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2877]
http://m.booktxt.net/wapbook/1411.html

![screen shot 2016-08-24 at 15 57 03](https://cloud.githubusercontent.com/assets/15856304/17945832/89688ae6-6a13-11e6-8d75-cf832531fcfd.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-07-29 08:27:05 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.3
ID: 30FEDE37-F845-4DB3-97C0-A0505D4F030D

Locale: zh
Region: cn

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.92.22 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.40 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.90 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.91 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.71 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.20 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.64.27 Enabled=YES

**Comment by Alex-302** [comment]
Added to English filter
```
||c.bxjpl.cn^$third-party
||tt.twzui6.com^$third-party
```
