### ISSUE TITLE
optbaza.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2878]
**Description**: Программа, расширение
На сайте интернет-магазина блокируется добавление товаров в корзину
Пример каталога с товарами: http://www.optbaza.ru/catalog/5/

Помогает отключение Фильтра счетчиков и систем аналитики

Screenshot:
<details>
![screenshot_2](https://cloud.githubusercontent.com/assets/18548949/17966796/21d602dc-6acc-11e6-8799-2e01d2b25463.jpg)
![screenshot_14](https://cloud.githubusercontent.com/assets/18548949/17966795/21d2a3bc-6acc-11e6-89d4-75fe5e8900d5.jpg)

</details>

**Filters list**: 1,2,3,4,14

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в фильтр аналитики
```
@@||mc.yandex.ru/metrika/watch.js$domain=optbaza.ru
```
