### ISSUE TITLE
https://www.firstonetv.eu/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2879]
https://www.firstonetv.eu/en/stream/fr/28

![image](https://cloud.githubusercontent.com/assets/15856304/17972060/15c5f942-6ae6-11e6-909a-1dd38a99c8ae.png)

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.92.40 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.45 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.96 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.3.18 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.38.26 Enabled=NO
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.34 Enabled=NO
ID=5 Name="Experimental filter" Version=1.0.26.24 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.4.73 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.20 Enabled=YES
ID=112 Name="Liste AR" Version=1.0.6.28 Enabled=NO
ID=113 Name="Liste FR" Version=1.0.64.28 Enabled=YES
ID=114 Name="ROList" Version=1.0.0.66 Enabled=NO
ID=115 Name="RU AdList" Version=1.0.64.23 Enabled=NO
ID=231 Name="Easylist Spanish" Version=1.0.0.87 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.64.24 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.1.29 Enabled=NO
ID=225 Name="Fanboy Anti-Facebook List" Version=1.0.0.4 Enabled=NO
ID=229 Name="I dont care about cookies" Version=1.0.0.1 Enabled=NO
ID=224 Name="Korean Adblock List" Version=1.0.0.2 Enabled=NO
ID=208 Name="Malware Domains" Version=1.0.64.12 Enabled=NO
ID=213 Name="RU AdList: BitBlock" Version=1.0.61.9 Enabled=NO
ID=212 Name="RU AdList: Counters" Version=1.0.60.82 Enabled=NO

**Comment by Alex-302** [comment]
Added to Social filter
```
firstonetv.eu##.fb_olay
firstonetv.eu##.facebook_window
```
Added to English filter
```
@@||firstonetv.eu^$generichide
firstonetv.eu##.video-grid > div[id][style]
```
