### ISSUE TITLE
 http://m.timesofindia.com/ - placeholder?

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2880]
![image](https://cloud.githubusercontent.com/assets/15856304/17972705/4b685b4c-6ae8-11e6-9203-423dfb1e4c5e.png)

When you open this site http://m.timesofindia.com/ then after the first
headline news you will see a blank space which is showing and then rest of
the news shows. If you click any news and scroll down the page then you
will see the same blank space.

<details>
en, social media, spyware, annoyances, ru, mobile, https is on, android 4.4.4, chrome 52.0

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
m.timesofindia.com##.ad1.NativeInarticle
```
Added to Social filter
```
m.timesofindia.com##.social_links
m.timesofindia.com##.socialcont

```

**Comment by evgeniy-ADG** [comment]
It doesn't help, unfortunately.

**Comment by Alex-302** [comment]
replaced.
m.timesofindia.com##div[class^="ad1 "]
