### ISSUE TITLE
http://m.xhamster.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2881]
http://m.xhamster.com/

Then click on any video, when you click to play the video then ads by
trafficstars.com is showing.

![image](https://cloud.githubusercontent.com/assets/15856304/17972876/fed62696-6ae8-11e6-85c1-08994566718c.png)

<details>
en, social media, spyware, annoyances, ru, mobile, https is on, android 4.4.4, chrome 52.0

**Comment by Alex-302** [comment]
Added to Mobile filter
```
xhamster.com##.pop-fade
xhamster.com##.pop-advertise

```

**Comment by evgeniy-ADG** [comment]
> After updating the adguard the ads are not showing but there is a new
> problem. when you open any video then you have to click twice the play
> button then the video plays. This happens for the first video and when you
> restart the browser and play again this problem happen.

Can we fix that, @Alex-302

**Comment by rajatmathurs** [comment]
Hi.

I want to report a new problem that when you open any video then pop ups are opening.

Please fix the pop ups problem too

Thanks a lot

**Comment by Alex-302** [comment]
> Can we fix that, @Alex-302?

not sure.



> when you open any video then pop ups are opening.

can't reproduce. Please collect HTTP log
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/49/9/collecting-a-full-log-on-adguard-for-android
and list your filters.

**Comment by rajatmathurs** [comment]
Ok but please fix the double click play button problem.

Thank you

**Comment by evgeniy-ADG** [comment]
@Alex-302 is it possible to fix that issue? when you click the video it doesn't react until you click it again. So you need to tap twice to start. Not the big deal, as for me, but it's inconvenient for the customer. Ty.

**Comment by rajatmathurs** [comment]
Yes it is inconvenient. I hope this gets fixed soon.

Thank you.

**Comment by Alex-302** [comment]
Added
```
||static-ec.xhcdn.com/*/js/mobile/pop.min.js
```
check it in user filter

**Comment by rajatmathurs** [comment]
I just checked but this filter is not good as when I click to play any video then video player loads with the black background as seen in the screenshot
![screenshot_20160829-220137](https://cloud.githubusercontent.com/assets/19775409/18059065/cdfdd218-6e34-11e6-97dc-626ac68ef5db.png)

And again i have to click the play button. Please remove this filter as I like the video playing with the details as shown below without adguard enabled 

![screenshot_20160829-221402](https://cloud.githubusercontent.com/assets/19775409/18059311/12ce30bc-6e36-11e6-84d3-3326e1ddd27a.png)


Please fix this problem.

**Comment by Alex-302** [comment]
Removed.
Overlay with trafficstars is hidden.
