### ISSUE TITLE
http://www.watchseries.ac/ - ad leftovers

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2882]
http://www.watchseries.ac/link/allmyvideos.net/2339242

![image](https://cloud.githubusercontent.com/assets/15856304/17973031/8de3fe6c-6ae9-11e6-8c4e-7c56231da6e0.png)

It won't let you play the video until you close it.

<details>
Application version: 1.0.8.54
Application lifetime: 2016-08-24 18:45:58 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.4
ID: 1C603617-4262-4112-B1A3-AE36BDD877B2

Locale: en
Region: gb

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.92.38 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.43 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.96 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.3.17 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.20 Enabled=YES

**Comment by Alex-302** [comment]
I can't hide in Safari for Mac.
Please ask about element hiding inside iframes in Safari.

**Comment by ameshkov** [comment]
@Alex-302 it works if you use iframe hostname:
`allmyvideos.net###OnPlayerClose`

**Comment by Alex-302** [comment]
Ok, thanks.
Added
