### ISSUE TITLE
http://animetake.tv - site detects adblock

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#2883]
http://animetake.tv/anime/danganronpa-the-animation/

Open any video, wait about 10 seconds and get this pop-up

![image](https://cloud.githubusercontent.com/assets/20476168/17974214/d78c8d28-6aed-11e6-89c7-6520b69567c9.png)

**Comment by Alex-302** [comment]
Added to English filter
```
animetake.tv#%#(function() { var _eval = window.eval; window.eval = function(a) { if ( a.toString().indexOf('babasbmsgx') === -1 ) { _eval(a); return; } }; })(); 
```
Added to Safari filter
```
@@||animetake.tv^$elemhide

```
