### ISSUE TITLE
crunchyroll.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2884]
### **Description**:

**Current behaviour**: 2 issues with it:
1) Anti Adblock:
- go to play any video, for example http://www.crunchyroll.com/berserk/episode-7-the-black-witch-714993
- get the following message:
  <details>

  ![adblocking_detection](https://cloud.githubusercontent.com/assets/14153331/17977322/4d1e4d12-6abf-11e6-82f2-6e45f2f50dd0.png)

  </details>

2) Extension compatibility:
- install CR HLS Player [(link)](https://chrome.google.com/webstore/detail/cr-hls-player/aeajdeepnjjdekpbicjhfldagkjndjid)
- try to play any video
- it won't play, and the player window is really small:
  <details>
  <img width="1440" alt="extension" src="https://cloud.githubusercontent.com/assets/14153331/17977426/af6cfc5c-6abf-11e6-9947-43496752f897.png">
  </details>

Filters:
<details>

![screen shot 2016-08-25 at 12 30 45 pm](https://cloud.githubusercontent.com/assets/14153331/17977453/ca35a340-6abf-11e6-8917-fa7dcb9174f1.png)

</details>

**Comment by Alex-302** [comment]
1) Added to English filter
```
@@||crunchyroll.com^$generichide
```
2) It dowsn't work in my browser without Adguard(player is broken)
