### ISSUE TITLE
http://happy-womens.com/ - banners, pop-ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2885]
http://happy-womens.com/

При попытке закрыть вкладку или
обновить страницу с этим сайтом,
появляется сразу баннер с жутко
шокирующими рекламными блоками и
запросом "вы уверены???". см.скриншот.

![image](https://cloud.githubusercontent.com/assets/15856304/17978038/d241699c-6afc-11e6-99d6-0529f3016cf5.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||medicinetizer.ru^$third-party
||litthegre.com^$third-party

```
