### ISSUE TITLE
http://www.xvideos.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2887]
Just try to reach any video and you'll see it's blocked:

![image](https://cloud.githubusercontent.com/assets/15856304/17980257/12a8e1b8-6b07-11e6-8aa4-f74aa2cae013.png)

Works fine if English filter is disabled.

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||static-*.xvideos.com/*/js/
```
Added to English filter
```
xvideos.com#%#Object.defineProperty(window, 'openpop', { get: function() { return; } });
```

**Comment by evgeniy-ADG** [comment]
It's still blocked
