### ISSUE TITLE
vidcpm.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#28878]
On openload streaming sites I see that `vidcpm.com` domain is blocked directly via ESET Internet Security:

![a](https://i.imgur.com/YAz5Qbd.png)

Chrome Dev Console looks:

![b](https://i.imgur.com/A9906po.png)

Could you investigate this?
Samples - openload streaming links: 
http://ekinomaniak.tv/watch-movies/Bumblebee-4637
http://szukajka.tv/link/v6kVxmipXCy
![sd](https://i.imgur.com/XUmsRe9.jpg)
This is directly taken from openload domains links. 

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Chrome Stable x64
AdGuard version:                       | **6.4.1840.4955**
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
| **Filters enabled**
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| EasyList Polish 
| Fanboy's Annoyances 
| Fanboy's Cookiemonster List
| Fanboy's Enhanced Tracking List 
| Fanboy's Social Blocking List 
| KAD - fraud/scam 
| Malware Domains
| NoCoin Filter List 
| Peter Lowe's List
| Polish Annoyances
| Polish Anti Adblock Filters
| Polish Cookies
| Polish Main
| Polish Social

@AdamWr

**Comment by bogachenko** [comment]
https://www.virustotal.com/ru/url/27ebac5264ca38aecd1b8a5b4e28adc9f734daed01b76e3b5811c832b5ba88b5/analysis/1548668697/

**Comment by Alex-302** [comment]
vidcpm.com is ad server, and it is blocked by Eng filter
