### ISSUE TITLE
com.franco.doze app ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2888]
**Description**:
https://play.google.com/store/apps/details?id=com.franco.doze

> Not able to block ads from an app called 'Naptime'

Source:
http://forum.xda-developers.com/showpost.php?p=68319449&postcount=1558

**Comment by Alex-302** [comment]
Can't install it on my phone. Only on Android 6.0 emulator.
Dut I don't see any network requests from this app.

**Comment by ameshkov** [comment]
Ask @gshumihin to help

**Comment by gshumihin** [comment]
This is how Naptime looks for me:
<img src="https://cloud.githubusercontent.com/assets/8577547/18055951/8c797774-6e12-11e6-87be-ec7266f5bdb2.png" width="300")

**Comment by ameshkov** [comment]
So no ads?

**Comment by Alex-302** [comment]
No. 
I see only Google ads without Adguard
![s](http://imagizer.imageshack.com/img924/9804/QIi6dU.png)

**Comment by ameshkov** [comment]
Got it, so it could be cached on the user side.
