### ISSUE TITLE
escolakids.uol.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#28892]
`https://escolakids.uol.com.br/portugues/hoje-e-vinte-ou-hoje-sao-vinte.htm`

Leftovers and sharing bar:

```
escolakids.uol.com.br##.pub_left_text
escolakids.uol.com.br###uoltm-float-push
escolakids.uol.com.br##[class$="ads"]
escolakids.uol.com.br##[class$="share"]
```

Adguard Base + Annoyances + Portuguese + Social
uBlock Origin 1.18.2
Firefox 64

**Comment by Alex-302** [comment]
Screenshot, please.

**Comment by adranger** [comment]
![screenshot](https://user-images.githubusercontent.com/35470489/51876155-c15c8c80-234e-11e9-8396-789108223c3d.png)

**Comment by Alex-302** [comment]
ok

**Comment by Alex-302** [comment]
ok

**Comment by adranger** [comment]
@Alex-302 They've made some changes and now the top leftover is fixed for a few seconds after you scroll down. `.publicidade-content` and `.pub_left_text` hide the ad spaces next to the articles.

[https://brasilescola.uol.com.br/brasil2/palacios-brasil.htm](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://brasilescola.uol.com.br/brasil2/palacios-brasil.htm)

![leftovers](https://user-images.githubusercontent.com/35470489/66582689-902c9100-eb58-11e9-8720-73999a5ac1f8.png)

[https://escolakids.uol.com.br/historia/guerra-da-cisplatina.htm](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://escolakids.uol.com.br/historia/guerra-da-cisplatina.htm)

![leftovers2](https://user-images.githubusercontent.com/35470489/66582733-a1759d80-eb58-11e9-968a-0eda23a127b7.png)

**Comment by Alex-302** [comment]
@adranger fixed

**Comment by adranger** [comment]
Sorry for not making it clear at the top, but the screenshots show two different subdomains (the second link is: [https://escolakids.uol.com.br/historia/guerra-da-cisplatina.htm](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://escolakids.uol.com.br/historia/guerra-da-cisplatina.htm)).

**Comment by Alex-302** [comment]
fixed
