### ISSUE TITLE
Adguard is unable to connect to the internet on windows 10 64 bit home edition. Can't update filters. Can't activate the license. 

### ISSUE THREAD

**Issue by rajbirs1973** [AdguardTeam/AdguardFilters#28909]
Please see screenshots below.

**Comment by rajbirs1973** [comment]
![filters](https://user-images.githubusercontent.com/46999564/51837521-99a6fd80-2329-11e9-8db7-58fbad5af623.jpg)
![license](https://user-images.githubusercontent.com/46999564/51837648-07532980-232a-11e9-8950-b33020946f6f.jpg)

**Comment by rajbirs1973** [comment]
Checked and confirmed Adguard is allowed through the Firewall. I am using Comodo Dome shield Proxy. Can the problem be due to Comodo. Appreciate your kind assistance. Apologize, I am new to Github.

**Comment by adranger** [comment]
@rajbirs1973 Please click on `Close Issue` on this page, and use this site instead for tech support: https://forum.adguard.com/index.php
