### ISSUE TITLE
http://www.redtube.com/ - placeholder

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2891]
http://www.redtube.com/ 

![screenshot_20160826-031316](https://cloud.githubusercontent.com/assets/15856304/18006691/6fb9e832-6ba9-11e6-9bca-2acfe9865a23.png)

en, social media, spyware, annoyances, ru, mobile, https is on, android 4.4.4, chrome 52.0

**Comment by Alex-302** [comment]
Added to Mobile filter
```
redtube.com##.between-videos
redtube.com##.after-header
redtube.com##.top-tabs
@@||static.redtube.com/mobi/images/$domain=redtube.com
```
Added to English filter
```
redtube.com#%#Object.defineProperty(window, 'init_tj_ads', { get: function() { return; } });
```
