### ISSUE TITLE
Easy Currency Converter - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2892]
https://play.google.com/store/apps/details?id=com.easy.currency.extra.androary

![image](https://cloud.githubusercontent.com/assets/15856304/18007767/145518b8-6bae-11e6-8a11-8660f80cb436.png)

<details>
**  "enabledFilterIds" : [ 2, 3, 4, 5, 14, 11, 113, 211 ],**
HTTPS is on

**Comment by Alex-302** [comment]
встроено
