### ISSUE TITLE
mobilmania.cz

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2893]
mobilmania.cz

Screenshot:
<details>
![mobilmania](https://cloud.githubusercontent.com/assets/14153331/18009317/a6e1cd14-6b79-11e6-8202-cf8ffa5d0176.png)
</details>

**Filters list**:
![filters](https://cloud.githubusercontent.com/assets/14153331/18009326/b1954740-6b79-11e6-9b2e-94f36d2aef9e.png)

**Comment by Alex-302** [comment]
Added to English filter
```
||mobilmania.cz/RssHubPager.ashx

```
