### ISSUE TITLE
http://www.multiup.org - pop-ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2894]
When I click on download mirrors in this
website:
http://www.multiup.org/en/download/f1b09b57e1280d021b481729c7552e99/vYVCu00KnDFVdGUdKB8b5B4lxWkbm6_opg.rar
It opens at least one or maybe 3 popup websites automatically. How to
prevent these popups.

<details>
AppVersion: 6.0.226.1108
Main settings: 
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:101 Name: EasyList Url: https://easylist-downloads.adblockplus.org/easylist.txt
FilterId:122 Name: Fanboy's Annoyances Url: https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
FilterId:207 Name: Adblock Warning Removal List Url: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
FilterId:211 Name: Anti-Adblock Killer | Reek Url: https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
FilterId:215 Name: Fanboy's Enhanced Tracking List Url: https://secure.fanboy.co.nz/enhancedstats.txt

**Comment by worldsdream** [comment]
Have the same problem.

**Comment by Alex-302** [comment]
check
```
||cloudfront.net^$domain=multiup.org
multiup.org#%#window.btoa = function() { };
||amazonaws.com/amcdn/admvpopunder.swf
||jlflzjdt.com^$third-party
||fungetbag.info^$third-party
multiup.org###admvpu
```

**Comment by worldsdream** [comment]
Added those filters

1 popup after clicking on one of the links

Windows Chrome Adguard App 6.1.258.1302

**Comment by worldsdream** [comment]
On iOS we can't click download, it tells to disable adblocker.

**Comment by rayman3003** [comment]
Those filters didn't do the magic.
Still have popups.

popups mostly are these:

http://trackpprofile.com/?&tid=608876&red=1&abt=0&v=1.10.35.0&sm=5&ref=http%3A%2F%2Fwww.multiup.org%2Fen%2Fmirror%2Fcc06b0e18c07bc4c39e4ffb8e73eb6e0%2Fq92V2G9Ls6BcuBsy584wGp1xKCopg.part2.rar&_rdBW=1472347163415

https://eclkspbn.com/adserve/sa?cid=mutppop&pid=&q=woijbsgu4ffzyaf49mkg70erxrwk1e_opg.rar%2cmultiup%2cmirror%2cmirror%20upload%2cmultiupload%2c&ap=cmp%3dpopunder%26evp%3dztiiwnvm8dfntsilhnmtvr9o784x_oqbca1csevwwqh3wopjfyyjyffil3zfvdew%26tip%3ddownload%20woijb

https://offerland.info/l/8c579bd6-2433-11e6-9af1-02401b02a2b5/v/0690782a-6c40-11e6-8ca0-1140e1e6ca0d/

https://offerland.info*

http://trackpprofile.com*

https://eclkspbn.com*

**Comment by Alex-302** [comment]
> popups mostly are these:
> 
> http://trackpprofile.com/?

Maybe you did something wrong. trackpprofile.com is blocked by ||cloudfront.net^$domain=multiup.org

**Comment by Alex-302** [comment]
No clickunders on my device with
```
||cloudfront.net^$domain=multiup.org
||amazonaws.com/amcdn/admvpopunder.swf
||jlflzjdt.com^$third-party
||fungetbag.info^$third-party
multiup.org###admvpu
||d2nn3xyicdpsrf.cloudfront.net^
```

**Comment by worldsdream** [comment]
I just checked with Charles on my mac https://www.charlesproxy.com/

Add this one too:

`||negdrvgo.com^$third-party`

**Comment by rayman3003** [comment]
It doesn't work for me. I'm using IE 11.

**Comment by Alex-302** [comment]
I see only one popup, which immediately closed. But I have no idea how to prevent it.

**Comment by worldsdream** [comment]
It does not close immediately over here, it stays open. 1 popup.

**Comment by Alex-302** [comment]
As I say, I can't remove it.

@ameshkov please help with this site. I can't block clickunder, which opens after click on the page after every second refreshing.

**Comment by ameshkov** [comment]
Heh, as I've said in Slack, $popup rules does not affect that site as they use a new complicated way of opening popups which is not covered by usual popup rules. Nice.

**Comment by Alex-302** [comment]
Is there a possibility to break their main script in the source page?

**Comment by ameshkov** [comment]
No need, the actual popup script is loaded from a third-party domain

**Comment by ameshkov** [comment]
The problem is that there are hell of a lot of these domains. I suggest simply blocking third-party scripts:
```
|http*$script,third-party,domain=multiup.org
```

**Comment by Alex-302** [comment]
@worldsdream check this
multiup.org#%#window.btoa = function() { };

**Comment by worldsdream** [comment]
That did not work, still popups

**Comment by Alex-302** [comment]
it is not for ios

**Comment by worldsdream** [comment]
`|http*$script,third-party,domain=multiup.org`

this did work, but popup comes and gets hidden immediately.

**Comment by worldsdream** [comment]
I know, i did add this to windows adguard app, tested both in chrome and firefox. cleared cache.

**Comment by worldsdream** [comment]
```
 multiup.org#%#window.btoa = function() { };
|http*$script,third-party,domain=multiup.org
```

Please add both to EN filter, This will also eleminate the popup that comes up and gets hidden immediately.
I tested this on Windows, Chrome, Firefox and IE 11. Adguard 6.1.258.1302

**Comment by worldsdream** [comment]
@rayman3003 I suggest to you to move to another browser then IE11. Try the possibilities of Chrome, Firefox, Opera or even Edge. Everything is better then IE11.

**Comment by Alex-302** [comment]
Added to English filter
```
multiup.org#%#window.open = function() {};
|http*$script,third-party,domain=multiup.org
```

**Comment by rayman3003** [comment]
It has been solved. 
Thank u very much for everyone that helped here. :D

**Comment by rayman3003** [comment]
OK, I still have a little problem:

In normal mode, there is not problem 
But When I use proxy IPs in my browser, all the ads and popups come back.

Any solution?

**Comment by ameshkov** [comment]
> But When I use proxy IPs in my browser, all the ads and popups come back.

What do you mean here? What sort of proxy? How exactly do you set it up?
