### ISSUE TITLE
tsf.pt

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#28942]
Ad/tracking domains being called from `https://www.tsf.pt/internacional/interior/um-monstro-de-lama-que-engoliu-tudo-a-sua-passagem-10498957.html` :

`adtlgc.com` 
`alooma.com`
`gigya.com`
`leiki.com`
`vilynx.com`
`wibbitz.com`

Adguard Base + Annoyances + Portuguese + Social + Spyware 
uBlock Origin 1.18.2

**Comment by Alex-302** [comment]
not all third-party domains should be blocked.

**Comment by adranger** [comment]
That's why I visited them one by one and reported only the tracking/ad ones...
