### ISSUE TITLE
Forza Football app - pop-up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2895]
https://play.google.com/store/apps/details?id=se.footballaddicts.livescore&hl=en

Inside the app "Forza Football", when you open a match it sends you to
chrome with the following link

http://ads.footballaddicts.com/match_ads/bet365-v2/liveodds.html?match_id=9909897&device_bridge_version=16&locale=en_JO&state=postmatch&platform=android_phone

which does not open
![image](https://cloud.githubusercontent.com/assets/15856304/18011699/e426cf72-6bbe-11e6-8ced-4350510d5728.png)

<details>
"enabledFilterIds" : [ 2, 3, 4, 14, 10, 11, 112 ], Full, HTTPS

**Comment by Alex-302** [comment]
Can't reproduce. I need stap-by-step in instructions.
