### ISSUE TITLE
http://www.fragrantica.ru/ (.com etc) - placeholder

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2896]
http://www.fragrantica.ru/perfume/Nobile-1942/Chypre-11578.html

![image](https://cloud.githubusercontent.com/assets/15856304/18026353/b6c52a36-6c4c-11e6-9e2d-22dc27419c16.png)
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/18026355/ca0f709c-6c4c-11e6-9d42-22a4dbe48a80.png)
</details>
eng, spy, social, russian, mobile, annoyances

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
fragrantica.ru##div[id][style^="width:300px;height:250px;"]
```

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/18781789/f9d5dfec-818b-11e6-88ca-792dfb6c74d3.png)

Снова есть, кажется. 
www.fragrantica.ru/perfume/Frapin/Terre-de-Sarment-5255.html

**Comment by Alex-302** [comment]
Добавил в англ фильтр
```
fragrantica.ru,fragrantica.com##div[style="padding: 5px;"] > div[style^="width: 100%; text-align: center; clear: both"] > div[style="width: auto; margin: auto;"]

```

**Comment by evgeniy-ADG** [comment]
Что-то снова вылезло
http://www.fragrantica.ru/perfume/Davidoff/Zino-Davidoff-590.html
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/18817811/06401552-8373-11e6-835d-a8372ecdd92d.png)

**Comment by Alex-302** [comment]
Added to English filter
```
fragrantica.ru,fragrantica.com###mainpicbox > div#newsocial
```

**Comment by evgeniy-ADG** [comment]
http://www.fragrantica.ru/perfume/A-Lab-on-Fire/L-Anonyme-ou-OP-1475-A-11920.html
http://www.fragrantica.com/perfume/A-Lab-on-Fire/L-Anonyme-ou-OP-1475-A-11920.html
etc

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/20033471/e8f6a644-a3a9-11e6-93d3-c1b699c7c244.png)

![image](https://cloud.githubusercontent.com/assets/15856304/20033485/f46f8d38-a3a9-11e6-893d-7e2fa7d4cc2a.png)

</details>
