### ISSUE TITLE
dobreprogramy.pl ad about Avast doesn't block in Microsoft Edge.

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#28966]
Microsoft Edge on Windows 10, Adguard Adblocker extension
All filters without obsolete.
On dobreprogramy.pl is ad about Avast and Adguard doesn't block that
![bug](https://user-images.githubusercontent.com/16944478/51923967-6bd6bd00-23ec-11e9-859b-534245de7d8e.png)

Can I please help in fix that.

**Comment by Alex-302** [comment]
@AdamWr `dobreprogramy.pl###phContent_avastBadge`

**Comment by seba2282** [comment]
@Alex-302 I guess, your extension for Edge has the same problem like Ublock Origin or Nano Adblocker. I use Windows 10 1809 and I heard about global bug in MS Edge in that version Windows 10 (1809). And I heard is fixed in Windows 10 1903. Can you look on that depth? Any rules works on Windows 1809, few moments is ok, after refresh site is again the same (Avast back).

**Comment by seba2282** [comment]
I see, now is good and don't see that ad with avast. Thank you 🙂
