### ISSUE TITLE
http://m.xhamster.com/ double click play button problem

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardFilters#2897]
Hi.
I am using samsung inbuilt browser, when i open any video from http://m.xhamster.com/
then i have to click twice the play button then the video plays. This happens for the first video and when i restart the browser and play any video then this problem happen again.

Secondly pop ups are also opening when you click any video but this happens for the first video every time when I open my browser.

Kindly Check these problem at your end and please fix them.

Thanks

**Comment by Alex-302** [comment]
The rule for this is dangerous and can break the player.
Which Adguard version are you using?

**Comment by rajatmathurs** [comment]
I am using adguard 2.7 latest version.
If you could fix double click play button problem then it will be great.

Please check at your end and let me know if this problem could be fixed or not.

Waiting for your reply.

**Comment by Alex-302** [comment]
It is impossible.
