### ISSUE TITLE
http://www.redtube.com/

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardFilters#2898]
Hi.

Open  redtube.com at the top there is a box.  In the box there are 3 things that is first menu, second redtube name and third search. Menu and search is not working, if you click menu then menu should open and if you click search then search box should show. They are not working.

For your reference I am attaching the screenshot.

![20160827_204409](https://cloud.githubusercontent.com/assets/19775409/18031634/fb6f1956-6d07-11e6-85d7-0e441897d964.png)

Please check them at your end and fix them.

Thanks

**Comment by Alex-302** [comment]
Please don't ignore the template.

**Comment by rajatmathurs** [comment]
I don't understand. Well if you can't click the menu then how will you sign in and if you can't click search then how will you search a particular videos

**Comment by rajatmathurs** [comment]
If I disable adguard then I can click the search and menu, but when adguard is enabled then search and menu are not clickable.

Please fix this

**Comment by Alex-302** [comment]
try to add(copy and paste) to user filter
```
redtube.com#@%#Object.defineProperty(window, 'init_tj_ads', { get: function() { return; } });
redtube.com#%#Object.defineProperty(window, 'init_tj_ads', { get: function() { return continue; } });
```

**Comment by rajatmathurs** [comment]
Well I copied and pasted the filters but it's not working

**Comment by Alex-302** [comment]
make screenshot of added rules

**Comment by rajatmathurs** [comment]
![screenshot_20160828-205257](https://cloud.githubusercontent.com/assets/19775409/18034717/d493c778-6d61-11e6-8e0f-b5a4d5baf9da.png)

I had copied your filter and added in the add filter

**Comment by rajatmathurs** [comment]
I just updated adguard and now menu and search are perfectly working. 

Thanks a lot issue solved

**Comment by Alex-302** [comment]
ok
