### ISSUE TITLE
http://m.timesofindia.com/ video not playing 

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardFilters#2899]
Hi.

I am using samsung inbuilt brower and Google chrome , when i clear catche and open this video 
http://m.timesofindia.com/Sheena-case-Should-CBI-consider-all-the-20-tapes-now/videoshow/53878665.cms

Click play button then video does not start playing. If you click on any other video then it does not play. I had to disable adguard 2.7 then I reload the link then it plays video. But now when I enable adguard then it plays all the videos too.

So This video not playing problem happens all the time when I clear the catche.

Please check and fix this problem.

Thank you

**Comment by Alex-302** [comment]
Works as expected. Which filters are you using?

**Comment by rajatmathurs** [comment]
I am using the default adguard filters, did you clear the catche as when you do that then only this problem occur. Please check again.

Thanks

**Comment by Alex-302** [comment]
Default filters = English filter.

**Comment by rajatmathurs** [comment]
![screenshot_20160828-202616](https://cloud.githubusercontent.com/assets/19775409/18034571/072b971e-6d5e-11e6-8dbf-6dc385464756.png)

And mobile filter

**Comment by Alex-302** [comment]
I have the same filters. Try to disable filters one-by-one and check after each filter.

**Comment by rajatmathurs** [comment]
Well if I disable any one then it will lower the protection, which I don't want.  If you could check at your end and fix this then I really appreciate. If not then it's not a big problem.

**Comment by Alex-302** [comment]
I can't reproduce your issue.
Just  disable filters one-by-one and check after each filter and tell me which filter cause this issue.

**Comment by rajatmathurs** [comment]
I disable filters one by one but it did not play the video. After cleaning the catche I had to disable adguard then video plays. Now when I enable adguard then the videos are playing. It's just when you clear catche and play the video then this problem happen.

**Comment by Alex-302** [comment]
Where did you clear cache?

**Comment by rajatmathurs** [comment]
In applications. Then select Google chrome and there clear catche.

**Comment by Alex-302** [comment]
Are you sure that is Adguard issue?

**Comment by rajatmathurs** [comment]
Couple of hours back there was problem. Now I just checked again and i don't know what happened now after clearing catche the video's are playing.

Issue solved.

Thanks a lot for your time and support

**Comment by Alex-302** [comment]
ok
