### ISSUE TITLE
Yandex direct on yandex maps

### ISSUE THREAD

**Issue by Hawkrus** [AdguardTeam/AdguardFilters#2900]
Яндекс директ на странице яндекс карт:

![maps-direct](https://cloud.githubusercontent.com/assets/19652388/18032641/adb0b95c-6d13-11e6-85ad-452d790676c2.PNG)

**Adguard version**: 6.0.226.1108

**Filters list**: Русский фильтр 1.0.38.34

**Operating system**: Windows 10

**Browser**: Chrome

**Comment by Alex-302** [comment]
Прямая ссылка нужна. В разных регионах код баннера может отличаться.

**Comment by Hawkrus** [comment]
@Alex-302 
https://yandex.ru/maps/11268/nizhneudinsk/?ll=98.859058%2C55.076814&z=14&mode=routes&rtext=&rtt=auto
![yand-dir](https://cloud.githubusercontent.com/assets/19652388/18047327/0033343a-6de5-11e6-87e2-0adcc3f2e784.PNG)

**Comment by Alex-302** [comment]
Не повторяется. Удалённо бы глянуть. Завтра, например.

**Comment by Hawkrus** [comment]
@Alex-302 
TeamViewer 223 741 493
Жду ответа, чтобы написать пароль...

**Comment by Alex-302** [comment]
Я готов

**Comment by Hawkrus** [comment]
8vfb21

**Comment by Alex-302** [comment]
черный экран

**Comment by Hawkrus** [comment]
ещё раз

**Comment by Alex-302** [comment]
добавил в русский
```
yandex.ru#$#div[class^="route-panel-content-view__"] > div[style^="text-align:left;display:block"][data-reactid] { position: absolute!important; left: -2000px!important; }
```

**Comment by Hawkrus** [comment]
Повторил фильтр на рабочем ПК, реклама ушла. Спасибо.

**Comment by evgeniy-ADG** [comment]
Проверьте, не появилась ли снова? Поступила жалоба.

![image](https://cloud.githubusercontent.com/assets/15856304/22456768/2de6626c-e79d-11e6-8fb3-048f86846d59.png)

У меня на маке - на доли секунды отрисовывается, но тут же скрывается.

**Comment by Alex-302** [comment]
чисто у меня

**Comment by oprotsyk** [comment]
Юзер написал, что в мозилле у него чисто, у меня на винде не повторилось

что попросить юзера?

**Comment by Alex-302** [comment]
если реклама мелькает и скрывается - это нормально. Там применён расширенный CSS для сокрытия рекламы, он не самый быстрый.

**Comment by evgeniy-ADG** [comment]
Она не мелькает, она просто есть.

**Comment by Alex-302** [comment]
Может исключение в пользовательском фильтре, или кривое правило. Надо смотреть.
> В IE расширенный CSS работает?

да

**Comment by evgeniy-ADG** [comment]
Можешь чекнуть по ТВ? Вот скайп пользователя: vadimyfish (удали потом плиз).
Там с настройками все ок, в IE не скрывается, в других - скрывается, насколько помню.

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
yandex.ru,yandex.ua,yandex.by#$#.traffic-home-panel-view__body > div[style*="!important;"] { position: absolute!important; left: -3000px!important; }
```

@evgeniy-ADG на будущее - для Яндекс Карт всегда проси точную ссылку, при которой отображается реклама.
