### ISSUE TITLE
http://xda-android-marshmallow.blogspot.com/2016/05/app-forcedoze-force-doze-mode-after.html - ad block detect

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#2901]
Detects Adguard ver 6.1
Standart filters, set normally.

![image](https://cloud.githubusercontent.com/assets/20476168/18032829/d95579be-6d1b-11e6-8822-117c60a8e293.png)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||xda-android-marshmallow.blogspot.com^$generichide

```

**Comment by Fridrix** [comment]
@Alex-302 
One more 
http://apkandroidfree.info/?s=clean+ui+lock+screen

**Comment by Alex-302** [comment]
Added to English filter
```
apkandroidfree.info###fab-over
apkandroidfree.info###fab
||js.srcsmrtgs.com^$third-party

```

**Comment by Alex-302** [comment]
@Fridrix 
не нужно в одну ишью разные сайты добавлять. Только одна проблема, желательно одного юзера, иначе теряться будут.
