### ISSUE TITLE
altergames.intellect_battle

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2902]
**Description**: При входе в игру реклама. Бывает что полностью блокирует экран.
https://play.google.com/store/apps/details?id=altergames.intellect_battle&hl=uk

Screenshot:
<details>
![default](https://cloud.githubusercontent.com/assets/18548949/18033068/e5e89f34-6d21-11e6-8341-fc67d14ee6dd.jpg)
</details>

**Steps to reproduce the problem**:

* Войти в приложение
*  Быстрая игра
*  При поиске случайного игрока реклама

[debug (6).txt](https://github.com/AdguardTeam/AdguardFilters/files/441073/debug.6.txt)
[state (61).txt](https://github.com/AdguardTeam/AdguardFilters/files/441074/state.61.txt)
Появление рекламы 17:54

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Судя по логу реклама заблокирована, и видны остатки из кэша игры. Нужно их вручную очистить.

**Comment by vgavrish** [comment]
отписалась

**Comment by vgavrish** [comment]
Удаление кэша не помогло, но переустановка программы дал результат.
