### ISSUE TITLE
http://my.tvspielfilm.de/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2904]
http://my.tvspielfilm.de/

![image](https://cloud.githubusercontent.com/assets/15856304/18041618/c198fb8a-6d88-11e6-91fc-6f1a3d44b874.png)

<details>
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.92.34 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.43 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.27 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.3.14 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.84 Enabled=NO
ID=6 Name="German filter" Version=1.0.27.2 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.20 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.1.86 Enabled=NO
ID=101 Name="EasyList" Version=1.0.54.80 Enabled=NO
ID=107 Name="EasyList Germany" Version=1.0.55.3 Enabled=NO
ID=118 Name="EasyPrivacy" Version=1.0.54.70 Enabled=NO
ID=122 Name="Fanboy's Annoyances" Version=1.0.54.88 Enabled=NO
ID=208 Name="Malware Domains" Version=1.0.64.8 Enabled=YES

**Comment by Alex-302** [comment]
There are anti-adblock ads. Try this rule
```
@@||tvspielfilm.de^$generichide
```
Also I recommend to disable Malware Domains filter. It is too big. Don't forget about iOS limitations - only 50000 rules.
