### ISSUE TITLE
digitalmusicnews.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#29056]
`https://www.digitalmusicnews.com/2018/10/02/fix-overlapping-youtube-music-google-play-music/`

Annoyance displayed to people who block social features.

![annoyance](https://user-images.githubusercontent.com/35470489/52109320-398fb000-25e4-11e9-8787-cc83413061f9.png)

Adguard Base + Annoyances + Portuguese + Social + Spyware
uBlock Origin 1.18.2
Firefox 65

**Comment by adranger** [comment]
@mapx- please check if you get this.

**Comment by mapx-** [comment]
@adranger  I get no such warning
