### ISSUE TITLE
vivareal.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#29053]
`https://www.vivareal.com.br/imovel/apartamento-2-quartos-ipiranga-zona-sul-sao-paulo-com-garagem-230m2-aluguel-RS7250-id-1042765101/`

Annoyance asking me how much I like the site. Appears randomly after cookies are cleared.

`div[data-step="vote"]`

![vivareal](https://user-images.githubusercontent.com/35470489/52104276-e5c79b80-25d0-11e9-968f-ccb559ceaec3.png)

Adguard Base + Annoyances + Portuguese + Social + Spyware
uBlock Origin 1.18.2
Firefox 65

**Comment by Alex-302** [comment]
Can't reproduce. @AdamWr please take a look.

**Comment by AdamWr** [comment]
I can't reproduce it.

**Comment by adranger** [comment]
@Alex-302  @AdamWr  Try these steps:

### 1. Clear your cookies, open `https://www.vivareal.com.br/` and search for "Moema"

![1](https://user-images.githubusercontent.com/35470489/53054609-a7145b00-3483-11e9-9016-c353ad0a0075.png)

### 2. Middle-click on the first search result to open it in a new tab

![2](https://user-images.githubusercontent.com/35470489/53054735-1be79500-3484-11e9-854a-e6278eadea6c.png)

### 3. See the annoyance

![3](https://user-images.githubusercontent.com/35470489/53054739-1f7b1c00-3484-11e9-9e3e-dafd52f5773c.png)

**Comment by AdamWr** [comment]
Ok, I was able to reproduce it.
Added:
`vivareal.com.br###viva-nps-container[data-step="vote"]`

Thank you for writing steps to reproduce that issue.
