### ISSUE TITLE
bolor-toli.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#29061]
`http://www.bolor-toli.com/`

![dic](https://user-images.githubusercontent.com/35470489/52119396-1a068080-2600-11e9-9067-08486807bb22.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.2
Firefox 65

**Comment by Alex-302** [comment]
What is wrong?

**Comment by adranger** [comment]
@Alex-302 I posted a screenshot of the huge ad banner. It's a dictionary website.

**Comment by Alex-302** [comment]
Damn. I thought that the site is fast food store:)
