### ISSUE TITLE
http://m.timesofindia.com - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2906]
I am using samsung inbuilt browser, when i clear cache and open this video
http://m.timesofindia.com/Sheena-case-Should-CBI-consider-all-the-20-tapes-now/videoshow/53878665.cms

Click play button then video does not start playing. If you click on any
other video then it does not play. I had to disable adguard 2.7 then I
reload the link then it plays video. But now when I enable adguard then it
plays all the videos.

![screenshot 09-01am aug 29 2016](https://cloud.githubusercontent.com/assets/15856304/18042099/bef8c0aa-6d8c-11e6-8c1b-1f9ae5808fc6.png)

<details>
https, eng, spy, social, annoyance, rus, mobile

**Comment by Alex-302** [comment]
Added to English filter
```
@@||imasdk.googleapis.com/js/core/bridge*.html$domain=~spotify.com
```
