### ISSUE TITLE
ok.ru, mail.ru - yandex direct

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2907]
The customer with Opera and Adguard extension. Filters, screenshots and saved as 'html, whole page' are available here: 1402033
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/18042827/c6078912-6d91-11e6-8bd8-36f29540650d.png)
![image](https://cloud.githubusercontent.com/assets/15856304/18051586/88ecdc4e-6dc3-11e6-9cf4-e4c86e19eaca.png)
<details>
basic filters

**Comment by evgeniy-ADG** [comment]
Managed to reproduce in ok.com

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
odnoklassniki.ru,ok.ru#$##hook_Block_StickyBannerContainer { position: absolute!important; left: -2000px!important; }
```
По mail.ru не понятно где искать, у них десятки проектов на этом домене.

**Comment by evgeniy-ADG** [comment]
ok, спасибо. на мейл ру - в почте https://e.mail.ru/messages/inbox# у тебя ничего нет?

**Comment by Alex-302** [comment]
В почте чисто. Какая версия браузера?

**Comment by shurmosha** [comment]
у меня такая проблема уже второй день на одноклассниках а личной страничке-периодически пробивает продукт
вот ссылка на видео в ютубе  https://www.youtube.com/watch?v=xwF0qmEByNY

**Comment by Alex-302** [comment]
@shurmosha 
проверьте обновления фильтров. В комментарии выше - добавленное сегодня правило.

**Comment by shurmosha** [comment]
Alex-302
проверил и обновил-пока рекламы нет

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/18254847/bf9f7e26-73aa-11e6-94ec-f995613226b7.png)
https://my.mail.ru/#
Снова появилось: 1402033

**Comment by Alex-302** [comment]
Нужно хотфикс расширения для Хрома ждать.

**Comment by evgeniy-ADG** [comment]
>На мейл ру реклама сифонила один день, я был подключен через латвийские серверы, может быть дело было в этом.

Есть, может, возможность проверить через латвийский ип? 

<details>
Application version: 1.3.0
Applicaton shared support folder:/Library/Application Support/com.adguard.Adguard
Applicaton support folder:/Users/Dmitry/Library/Application Support/com.adguard.Adguard
Filtration Enabled
Filtration mode: direct
Blocked: 41
Application lifetime: 2016-04-28 10:07:21 +0000
Platform: Mac OS X
OS: 1011
Locale: ru

Antibanner filter: Enabled
Antiphishing filter: Enabled
Parental control: Disabled
Privacy protection: Enabled
HTTPS: Enabled
Assistant: Disabled
Web of trust: Disabled
Popup blocker: Enabled

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0
ID=2 Name="English filter" Version=1.0.97.40
ID=3 Name="Spyware filter" Version=1.0.8.14
ID=10 Name="Filter for useful ads" Version=1.0.0.89
ID=1 Name="Russian filter" Version=1.0.41.10
ID=12 Name="Safari filter" Version=1.0.1.52

SSL exception domains:
plimus.com
payproglobal.com
avangate.com
paypal.com
halifax-online.co.uk
identity.virginmedia.com
signin.ebay.com
signin.ebay.co.uk
icbc.com.cn
hsbc.co.uk
hsbc.com
secure.hsbcnet.com
bv-activebanking.de
hsbc.ca
hsbc.com.au
chase.com
secure.bnpparibas.net
bnpparibasfortis.be
webbanking.bgl.lu
secure.bnl.it
barclays.co.uk
bankofamerica.com
deutsche-bank.de
deutsche-bank.es
deutsche-bank.it
deutsche-bank.pt
db-pbc.pl
db.com
qweb.quercia.com
citibank.com
wellsfargo.com
societegenerale.fr
societegenerale.com
sgeb.bg
rbsinternational.com
sberbank.ru
alfabank.ru
zakupki.gov.ru
194.105.148.87
aus.mozilla.org
aus1.mozilla.org
aus2.mozilla.org
aus3.mozilla.org
aus4.mozilla.org
aus5.mozilla.org
aus6.mozilla.org
addons.mozilla.org
versioncheck.addons.mozilla.org
dl.dropboxusercontent.com
lastpass.com
mozilla.org
mozilla.net
webmoney.ru
wmtransfer.com
adtidy.org
chrome.adtidy.org
eff.org
8pecxstudios.com
rbsdigital.com
commonbank.com.ua
sparkasse-fuerth.de
ing-diba.de
apple.com

**Comment by shurmosha** [comment]
да .сейчас я свободен или напишите время

**Comment by evgeniy-ADG** [comment]
**https://e.mail.ru/messages/inbox?back=1&back=1#**

![image](https://cloud.githubusercontent.com/assets/15856304/20145879/5e05b300-a6aa-11e6-8857-7f2673fce66f.png)

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/20145891/6998a650-a6aa-11e6-9864-5948a2dc92ef.png)

**Comment by Alex-302** [comment]
Подправил.

**Comment by evgeniy-ADG** [comment]
Снова есть, говорят. У меня не видно.

![screenshot_1](https://cloud.githubusercontent.com/assets/15856304/22690672/a193ab5a-ed3f-11e6-9faf-2ab912c03d56.png)

**Comment by Alex-302** [comment]
Уже как-то было, что реклама не у всех отображалась. Они что-то пилят видать. Удалённо можно посмотреть.

**Comment by evgeniy-ADG** [comment]
> Здравствуйте!
> Я не блокировала рекламу вручную, у меня пользовательский фильтр пустой. И кэш браузера тоже, мне уже надоело его чистить.
> Вечером всё было нормально, но как только утром я открыла почту реклама снова была.

Фильтры - только русский, английский и spyware. ID: 1537766

**Comment by Alex-302** [comment]
Так на каком сайте реклама? В названии проблемы - их два.

**Comment by deLumren** [comment]
@Alex-302 проблема на mail.ru

**Comment by Alex-302** [comment]
доступ нужен. Наверное тестируют пока, и не у всех повторяется.

**Comment by shurmosha** [comment]
было всё нормально .пользовательские чисты фильтры. пробилась реклама в почте,на леди мэйл нет рекламы  
браузер ОПЕРА 	44.0.2510.1218 (PGO)  СИСТЕМА 10-ка 1703
![default](https://cloud.githubusercontent.com/assets/17802561/24968316/8e7df068-1fb5-11e7-87e5-faccbeded0f1.PNG)

**Comment by shurmosha** [comment]
всё =реклама ушла.после получения обновлений..спасибо

**Comment by Alex-302** [comment]
ну и отлично)
