### ISSUE TITLE
https://share.weiyun.com - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2908]
![image](https://cloud.githubusercontent.com/assets/15856304/18043501/3f5ebe08-6d96-11e6-8dbb-d7b9ad86a005.png)

You can click on this link and download it, right-click the file stand-alone icon, select the first option is to download
https://share.weiyun.com/a0a7d9fbc084faa2e5191d0c3368781d

You will find, in the case of not disable Adguard, the page will prompt: "Unable to connect to the server timed out. Please try again later."

<details>
basic set + EL China

**Comment by Alex-302** [comment]
Added to English filter
```
@@||user.weiyun.com/newcgi/outlink.fcg$document
```
