### ISSUE TITLE
https://apps.facebook.com/candycrushjelly - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2909]
Looks like the Social Media filter is blocking the Facebook
game "Candy Crush Jelly Saga") (
https://apps.facebook.com/candycrushjelly/ ). If the filter is on,
game isn't loaded correctly. Here are two screenshots, with the filter
on and off: http://imgur.com/a/Tr3aH (filter OFF)
http://imgur.com/a/K8Ug0 (filter ON) I'm using Google Chrome on
Windows 10. 

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/18045756/6cb01f4e-6da2-11e6-94b1-9b26d3fcfed5.png)

**Comment by Alex-302** [comment]
Added to Social filter
```
king.com#@##fb-root
```
