### ISSUE TITLE
http://radikal.ru/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2910]
Пропущена реклама на сайте: http://radikal.ru
Скриншот: http://f4.s.qip.ru/OgbqisBn.png

Мои параметры:
* Win x64
* adguard в виде расширения у Chrome
* фильтры: русский, английский, RU AdList
* Dr.Web

**Comment by Alex-302** [comment]
Перенёс в русский
```
f-picture.net,radical-foto.ru,radikal.cc,radikal.ru##.footer a[target="_blank"]
f-picture.net,radical-foto.ru,radikal.cc,radikal.ru##.site-footer a[target="_blank"]
```
