### ISSUE TITLE
http://www.rambler.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2911]
<details>![image](https://cloud.githubusercontent.com/assets/15856304/18051115/8ed836b0-6dc0-11e6-84ec-ce2ce15619e9.png)

![image](https://cloud.githubusercontent.com/assets/15856304/18051128/9cc26250-6dc0-11e6-923d-b81f6556d751.png)
</details>
filters
<details>
Application version: 1.3.0
Applicaton shared support folder:/Library/Application Support/com.adguard.Adguard
Applicaton support folder:/Users/user/Library/Application Support/com.adguard.Adguard
Filtration Enabled
Filtration mode: direct
Blocked: 133
Application lifetime: 2016-02-19 06:21:08 +0000
Platform: Mac OS X
OS: 109
Locale: ru

Antibanner filter: Enabled
Antiphishing filter: Enabled
Parental control: Disabled
Privacy protection: Enabled
HTTPS: Enabled
Assistant: Enabled
Web of trust: Disabled
Popup blocker: Enabled

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0
ID=2 Name="English filter" Version=1.0.92.55
ID=3 Name="Spyware filter" Version=1.0.7.48
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.89
ID=1 Name="Russian filter" Version=1.0.38.32
ID=12 Name="Safari filter" Version=1.0.1.20
ID=104 Name="EasyList China" Version=1.0.64.57

SSL exception domains:
plimus.com
payproglobal.com
avangate.com
paypal.com
halifax-online.co.uk
identity.virginmedia.com
signin.ebay.com
signin.ebay.co.uk
icbc.com.cn
hsbc.co.uk
hsbc.com
secure.hsbcnet.com
bv-activebanking.de
hsbc.ca
hsbc.com.au
chase.com
secure.bnpparibas.net
bnpparibasfortis.be
webbanking.bgl.lu
secure.bnl.it
barclays.co.uk
bankofamerica.com
deutsche-bank.de
deutsche-bank.es
deutsche-bank.it
deutsche-bank.pt
db-pbc.pl
db.com
qweb.quercia.com
citibank.com
wellsfargo.com
societegenerale.fr
societegenerale.com
sgeb.bg
rbsinternational.com
sberbank.ru
alfabank.ru
zakupki.gov.ru
194.105.148.87
aus.mozilla.org
aus1.mozilla.org
aus2.mozilla.org
aus3.mozilla.org
aus4.mozilla.org
aus5.mozilla.org
aus6.mozilla.org
addons.mozilla.org
versioncheck.addons.mozilla.org
dl.dropboxusercontent.com
lastpass.com
mozilla.org
mozilla.net
webmoney.ru
wmtransfer.com
adtidy.org
chrome.adtidy.org
eff.org
8pecxstudios.com
rbsdigital.com
commonbank.com.ua
sparkasse-fuerth.de
ing-diba.de
apple.com

**Comment by Alex-302** [comment]
@evgeniy-ADG У меня чисто. Можешь у себя проверить?

**Comment by Alex-302** [comment]
убрал пару пустот
```
rambler.ru##.b-guides__item_banner
```

**Comment by evgeniy-ADG** [comment]
Первый скрин мой, второй - кастомера. Сейчас того, что было у меня, не вижу.

**Comment by Alex-302** [comment]
Если поймаешь вдруг, или у юзера если повторяется, попроси доступ.

**Comment by vgavrish** [comment]
@Alex-302 
сегодня в 15-00 по мск времени

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
rambler.ru##.mixednews__bottom-ad
rambler.ru##.ad--center
```
