### ISSUE TITLE
http://javfor.me/  anti adblock problem

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardFilters#2912]
Hi.

There is anti adblock problem When you play any video from this site http://javfor.me/

I am attaching the screenshot

![screenshot_20160830-005005](https://cloud.githubusercontent.com/assets/19775409/18064272/43c096f4-6e4c-11e6-8309-ba78e7eb4ad9.png)

Please check and fix this issue.

Thanks

**Comment by Alex-302** [comment]
Please check it:
```
@@||serve.popads.net/checkInventory.php|$domain=jav4.me
```
Added to English filter

**Comment by rajatmathurs** [comment]
Yes it's working
Issue solved

Thank you
