### ISSUE TITLE
Sop to Http Ads

### ISSUE THREAD

**Issue by drakulaboy** [AdguardTeam/AdguardFilters#2913]
https://play.google.com/store/apps/details?id=com.devaward.soptohttp&hl=en

**Blocks with ads and popup with ads**:

Screenshot:
**Adguard version 2.6**:

**Filters list by default**:

**Operating system Android Remix OS
![screenshot_20160829-223132](https://cloud.githubusercontent.com/assets/7822898/18064675/1b34c484-6e39-11e6-8dca-07959ef67b25.png)
![screenshot_20160829-222743](https://cloud.githubusercontent.com/assets/7822898/18064681/20c31c98-6e39-11e6-8c4e-692f644d9807.png)
![screenshot_20160829-222405](https://cloud.githubusercontent.com/assets/7822898/18064685/294601d2-6e39-11e6-9242-6a98cd6949af.png)

**:

**Comment by Alex-302** [comment]
Danner at the bottom is builtin, we can't remove it.
2) I need a url of channel. Please provide me it.
