### ISSUE TITLE
dropapk.com [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#29133]
**Site**: https://dropapk.com/ykjpvb9dznp8

**Issue**: Please remove pop-up on the page. 

**Screenshot**: N/A

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 72.0.3626.81 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
I see no popups.

**Comment by Nzzyme** [comment]
Yea, seems to be fixed by itself now
