### ISSUE TITLE
http://applesencia.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2914]
http://applesencia.com/ - it keeps redirecting in loop

![image](https://cloud.githubusercontent.com/assets/15856304/18081421/209b0850-6e68-11e6-865c-135e56352e54.png)

<details>
Optimized enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.92.23 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.41 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.90 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.34 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.71 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.7 Enabled=NO

**Comment by Alex-302** [comment]
Can't reproduce.
@vozersky please check it on ipad

**Comment by evgeniy-ADG** [comment]
У меня повторилось с агентом айфона в сафари

**Comment by Alex-302** [comment]
Хм. У меня тоже, но без Адгарда.
