### ISSUE TITLE
http://arseblog.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2915]
http://arseblog.com/2016/08/interlull-whos-heading-window-closes/

![image](https://cloud.githubusercontent.com/assets/15856304/18081465/6501b462-6e68-11e6-8511-5a4ab03da272.png)

<details>
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.92.78 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.49 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.3 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.20 Enabled=YES
ID=101 Name="EasyList" Version=1.0.62.5 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.64.37 Enabled=YES

**Comment by Alex-302** [comment]
Can't reproduce. Try to disable filters on-by-one and find a filter, which causes this issue.

**Comment by duvanr** [comment]
I disabled filter movil advertising and solved 😉

**Comment by Alex-302** [comment]
Could you try to disable all filters and test with mobile filter only?

**Comment by duvanr** [comment]
Yes work 😉, but  there are blanks space.
Thanks

**Comment by Alex-302** [comment]
Very strange. Can you reproduce this issue on desktop?

**Comment by duvanr** [comment]
in desktop work fine, issue only in safari ios.

**Comment by duvanr** [comment]
please verify issue in desktop http://www.eltiempo.com/

On Fri, Sep 2, 2016 at 9:51 PM, Jose Fernando <josefernando.romero@gmail.com
> wrote:

> in desktop work fine, issue only in safari ios.
>

**Comment by Alex-302** [comment]
> please verify issue in desktop http://www.eltiempo.com/

Please open new issue for it.
