### ISSUE TITLE
http://imagetwist.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2916]
http://imagetwist.com/xqpu9lcys7pv/_GirlsWay__Melissa_Moore__Capri_Anderson_-_Twinning_2_Part_One__29.08.2016__rq.mp4_thumbs__2016.08.29_07.51.18_.jpg

![image](https://cloud.githubusercontent.com/assets/15856304/18081806/0a3a97fe-6e6a-11e6-951f-89416f302bc0.png)

* Win x64
* adguard в виде расширения у Chrome
* фильтры: русский, английский, RU AdList
* Dr.Web

**Comment by Alex-302** [comment]
Added to English filter
```
||imagetwist.com/backend_loader.php
||imagetwist.com/frontend_loader.js

```
