### ISSUE TITLE
 http://apkandroidfree.info/ - ads, redirects

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2917]
It's in our safe browsing filters, but anyway, please consider blocking redirects like that:<details>
![image](https://cloud.githubusercontent.com/assets/15856304/18083293/8d845eaa-6e70-11e6-9355-76776bac9c80.png)
![image](https://cloud.githubusercontent.com/assets/15856304/18083304/965c7832-6e70-11e6-8f27-d15bf38fa314.png)</details>

> I was searching this variable: Good Lock UI 
> And pressed this link: http://apkandroidfree.info/?s=clean+ui+lock+screen
> 
> I was first shown this warning from that site (first attachment). Which resulted in a number of redirects and prompts to download items most likely malicious. I could see my browser being redirected as I tried to back out to original search without downloading anything. (See other screen shot attachments and log).

"enabledFilterIds" : [ 2, 3, 4, 5, 14, 10, 11, 211 ],
  "environment" : "release",
  "filteringQuality" : "SPEEDY",

**Comment by Alex-302** [comment]
I can't reproduce it. It was shown when user clicked on download button?(which number)

**Comment by evgeniy-ADG** [comment]
I does not occur every time, just try a couple of times. I was unable to find out what's causing pop ups, it seems that they start popping when you click on Search button or try to open search results.

**Comment by Alex-302** [comment]
Please ask for detailed description, with steps to reproduce.

**Comment by evgeniy-ADG** [comment]
I was searching this variable: Good Lock UI 
And pressed this link: http://apkandroidfree.info/?s=clean+ui+lock+screen

I was first shown this warning from that site (first attachment). Which resulted in a number of redirects and prompts to download items most likely malicious. I could see my browser being redirected as I tried to back out to original search without downloading anything. (See other screen shot attachments and log).

pics and logs: 1138191 aug 29

**Comment by evgeniy-ADG** [comment]
Managed to reproduce.

1. Search for an app
2. Go to a result and see 3 buttons for downloading an apk
3. Hit any
4. See redirects and pop ups

**Comment by Alex-302** [comment]
I need a HAR file after cleaning browser cache.

**Comment by evgeniy-ADG** [comment]
[har.zip](https://github.com/AdguardTeam/AdguardFilters/files/449512/har.zip) time 2:36

**Comment by Alex-302** [comment]
@evgeniy-ADG уточни у него на какую кнопку Download он нажимает. Это не попап.
> Hit any

сомнительно.

**Comment by evgeniy-ADG** [comment]
Я сам лично нажимаю на любую из трех кнопок, ща дам скрин

**Comment by evgeniy-ADG** [comment]
![screenshot_2016-09-02-15-16-34](https://cloud.githubusercontent.com/assets/15856304/18203571/7a6605aa-7120-11e6-9967-ac75a28c51b3.png)
![Uploading Screenshot (03-16PM, Sep 02, 2016).png…]()

**Comment by Alex-302** [comment]
Ну это сайт такой, он ничего у себя не хранит. Ты на открытые страницы смотри, есть ли там возможность скачать.
У меня мусор открывается только при нажатии на эту кнопку
![1](https://lh5.googleusercontent.com/-nP-es-eopQo/Uot9knVHPrI/AAAAAAAAROk/qU3ABD_o-uM/s468/Download-apk.gif)
