### ISSUE TITLE
http://www.redtube.com  ad pop up problem 

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardFilters#2918]
Hi.

First of all go to applications select google chrome and delete clear data, see the screenshot below
<details>
![screenshot_20160830-155522](https://cloud.githubusercontent.com/assets/19775409/18086142/17416308-6ecc-11e6-8b0f-f30d166b55ae.png)
</details>
Now open http://www.redtube.com and click any video, then pop up ad is opening, see the screenshot below
<details>
![screenshot_20160830-155737](https://cloud.githubusercontent.com/assets/19775409/18086209/61a2b258-6ecc-11e6-8729-5f7eb850be8a.png)
</details>
This pop up ad is opening every time when I clear google chrome data.

Please check and fix this pop up ad problem

**Comment by Alex-302** [comment]
It's clean on my device

**Comment by rajatmathurs** [comment]
I had provided the screenshot and I had just checked again the pop up ad is opening and the ad url is listed below

https://ads.gold/c/468ba1af-9a6a-11e5-b565-02f6361de079?tracker_id=7348.1472569093cs452460554b28_1&pubid={{pubid}}

Please check and fix this problem 

Thanks

**Comment by rajatmathurs** [comment]
Alex please provide a fix for this problem

Thanks

**Comment by rajatmathurs** [comment]
is there anyone who could help me with this problem

**Comment by evgeniy-ADG** [comment]
@rajatmathurs please do not ignore template you see when you add new tasks here, at least use `<details>...>/details>` tags to hide large image and NSFW content, and add some info about your settings - filters, filtering method (adguard > settings > advanced), whether HTTPS filtering is enabled :) could you please update here? thanks ;)

**Comment by rajatmathurs** [comment]
Will take care about the <details>...</details>.

I just checked when I open the site in chrome incognito tab then click any video then scroll down the page and click on another video then pop ad is opening.

**Comment by rajatmathurs** [comment]
HTTPS filtering is enabled, still the pop up ads are opening. Please fix this issue.

Thanks

**Comment by evgeniy-ADG** [comment]
Well, ok, so I edited your post and placed images under spoilers, now it looks more readable and easy to understand. What about filters and filtering algorithm and method (aguard > settings > advanced)? Which are enabled in your Adguard?

**Comment by rajatmathurs** [comment]
English, spyware, social media, annoyances and mobile ads filters are enabled. I had just checked in chrome incognito tab too, first open the site then click any video then scroll down and when I click any video then pop ups ads is opening.

**Comment by evgeniy-ADG** [comment]
thanks, @Alex-302 will have a look as soon as he finish some other tasks with higher priority.

**Comment by Alex-302** [comment]
added
```
redtube.com#%#if (typeof localStorage != 'undefined' && localStorage.setItem) { localStorage.setItem('InfNumFastPops', 'undefined__1'); }
redtube.com#%#if (typeof localStorage != 'undefined' && localStorage.setItem) { localStorage.setItem('InfNumFastPopsExpire', new Date(new Date().setYear(2020))); }
```

**Comment by rajatmathurs** [comment]
Alex.

Problem is back. I have just checked again and now when you delete the chrome data and open redtube.com site and click any video then scroll down the page and click on another video then pop ad is opening. Alex please check the site again and provide a fix for this problem.

**Comment by Alex-302** [comment]
Added to English filter
```
redtube.com#%#if (typeof localStorage != 'undefined' && localStorage.setItem) { localStorage.setItem('pop_under_already_shown', 'true'); }
redtube.com#%#if (typeof localStorage != 'undefined' && localStorage.setItem) { localStorage.setItem('pop_under_initial_date', new Date(new Date().setYear(2020))); }
```
