### ISSUE TITLE
http://m.xhamster.com ad pop problem 

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardFilters#2919]
Hi.

First of all go to applications select google chrome and delete clear data, see the screenshot below
<details>
![screenshot_20160830-155522](https://cloud.githubusercontent.com/assets/19775409/18086142/17416308-6ecc-11e6-8b0f-f30d166b55ae.png)
</details>
Now open http://m.xhamster.com and click any video, then pop up ad is opening, see the screenshot below
<details>
![screenshot_20160830-160241](https://cloud.githubusercontent.com/assets/19775409/18086397/4726317e-6ecd-11e6-8332-39e8e75dfe0c.png)
</details>

This pop up ad is opening every time when I clear google chrome data.

Please check and fix this pop up ad problem

**Comment by Alex-302** [comment]
try
```
m.xhamster.com#%#Object.defineProperty(window, 'js_vars', { get: function() { return {}; } });
```

**Comment by rajatmathurs** [comment]
Its not working. I added the filter in user filter but still pop up ad is opening

**Comment by rajatmathurs** [comment]
Alex please provide a fix for this problem

Thanks

**Comment by rajatmathurs** [comment]
is there anyone who could help me with this problem

**Comment by evgeniy-ADG** [comment]
@Alex-302 could you please look into this issue once again, please? thaks!

**Comment by Alex-302** [comment]
I can't reproduce.
Please clear cache and record HAR file
https://kb.adguard.com/index.php?/Russian/Knowledgebase/Article/View/65/0/how-to-get-har-http-archive-files-from-android-device

**Comment by rajatmathurs** [comment]
In Google chrome open this site m.xhamster.com in 'New incognito tab' now when you click any video then pop up ads are opening.

Kindly fix this problem
