### ISSUE TITLE
facebook.com incorrect blocking

### ISSUE THREAD

**Issue by gwarser** [AdguardTeam/AdguardFilters#2920]
**Current behaviour**: Content of Facebook Activity Log is hidden by `facebook.com##.bottomborder`

Screenshot: 
![xxxx](https://cloud.githubusercontent.com/assets/886325/18098817/1b7b6ac8-6ee4-11e6-9150-1c331316f56d.png)

**Expected behaviour**: 

Supposedly, only cookie notice should be hidden, reported here: https://forum.adguard.com/index.php?threads/resolved-facebook-com-cookie-notice.12920/#post-96945

**Adguard version**: UBlock 1.9.5b0

**Filters list**:  Adguard Annoyances Filter‎

**Operating system**: Mint 17.3

**Browser**: Firefox 50

**Comment by Alex-302** [comment]
Can't reproduce that cookie notification. Rule is removed.
