### ISSUE TITLE
https://www.tvcook.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2921]
https://www.tvcook.ru/recipes/meet-farsh/bifshteks-rublennyy.html

![image](https://cloud.githubusercontent.com/assets/15856304/18100389/68c31fb0-6ef3-11e6-98b6-2d9e559a0a96.png)

<details>
russian english annoyances spyare social media

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||kmndj.top^$third-party

```
