### ISSUE TITLE
ipify.org

### ISSUE THREAD

**Issue by notDavid** [AdguardTeam/AdguardFilters#29213]
fyi, ipify.org is currently blocked in https://filters.adtidy.org/extension/chromium/filters/15.txt 

It has nothing to do with spyware or analytics... please consider removing.

**Comment by Alex-302** [comment]
It is used for analytics. The site ipify.org is not blocked.

**Comment by nikmartin** [comment]
api.ipify.org is still blocked:
https://github.com/AdguardTeam/AdguardFilters/blob/31bbee638510aa5477d512b2f9ff3beaa1f62399/SpywareFilter/sections/tracking_servers.txt#L1425

the ipify.org api is a simple api to return your IP address. It is used  for dynamic DNS. The primary use case is accessing remote computers behind dynamic IP addresses.

**Comment by Alex-302** [comment]
@nikmartin ok. Unblocked. But this domain is also blocked in EasyPrivacy filter.
