### ISSUE TITLE
missed ads terrikon.com

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2922]
Пропущена реклама.

Фильтры: 
Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский

![2392ae7411e516325ac28aaf9f7acafa](https://cloud.githubusercontent.com/assets/16462533/18118131/a55073d4-6f5b-11e6-8a3e-e2fb70ea7dad.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||ts2.hockey-talks.com^
||st.terrikon.com/i/ad/

```
