### ISSUE TITLE
superesportes.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#29236]
`https://www.mg.superesportes.com.br/app/noticias/futebol/cruzeiro/2019/02/04/noticia_cruzeiro,565310/thiago-neves-do-cruzeiro-se-desculpa-apos-piada-com-barragem.shtml`

`#shareitens` before the article.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.2
Firefox 65

**Comment by krystian3w** [comment]
I see also on bottom:

```
###shareitensInf > a.btn-share:not(:nth-of-type(5))
```

```
###shareitensInf > a.btn-share[id]
```

---

Block both social bottons (top and bottom):

`###shareFace, #shareGoogle, #shareTwitter`
