### ISSUE TITLE
thehouseofportable.com [Pop-ups] [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#29248]
**Site**: https://thehouseofportable.com/508/microsoft-office-2016-pro-plus-portable/

**Issue**: Please remove the pop-ups from the page. Additionally, please remove the fake links and adblock message from this page (https://thehouseofportable.com/download/?y=2018&id=99&k=1) as seen in this screenshot (http://prntscr.com/mgz1or)

**Screenshot**: See above

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 72.0.3626.81 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
Ads not reproduced. Fixed popup.
