### ISSUE TITLE
spaces.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2924]
http://spaces.ru/diary/read/?Bias=1&address=Russian_Bearing&from=main&id=2052877952&link_id=1355978

![image](https://cloud.githubusercontent.com/assets/15856304/18120666/aed5c2c4-6f2e-11e6-9105-11a9143458cb.png)

<details>
Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:5 Name: Experimental filter Url: http://adguard.com/ru/filter-rules.html?id=5
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:10 Name: Filter for useful ads Url: http://adguard.com/ru/filter-rules.html?id
FilterId:104 Name: EasyList China Url: https://easylist-downloads.adblockplus.org/easylistchina.txt
FilterId:105 Name: EasyList Czech and Slovak Url: https://raw.github.com/tomasko126/easylistczechandslovak/master/filters.txt
FilterId:108 Name: EasyList Hebrew Url: https://raw.githubusercontent.com/AdBlockPlusIsrael/EasyListHebrew/master/EasyListHebrew.txt
FilterId:111 Name: Latvian List Url: https://notabug.org/latvian-list/adblock-latvian/raw/master/lists/latvian-list.txt
FilterId:113 Name: Liste FR Url: https://easylist-downloads.adblockplus.org/liste_fr.txt
FilterId:117 Name: Adblock Polska Url: https://raw.githubusercontent.com/adblockpolska/Adblock_PL_List/master/adblock_polska.txt
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Tdi

**Comment by Alex-302** [comment]
Дроид/Винда/Макось?

**Comment by Alex-302** [comment]
Не зря же шаблон сделали. Правильно заполненный - это 80% решения проблемы.

**Comment by evgeniy-ADG** [comment]
Там винда, фильтры от нее под спойлером + оно везде повторяется вроде как. Я повторил на маке с программой.

**Comment by Alex-302** [comment]
Попробуй обновиться. В 3ebc324 пару правил добавил.

**Comment by evgeniy-ADG** [comment]
осталось
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/18166220/7ef15ef4-7052-11e6-83a7-ad66f07f017a.png)
![image](https://cloud.githubusercontent.com/assets/15856304/18166223/89465986-7052-11e6-8f6a-2028428b519c.png)

**Comment by Alex-302** [comment]
Опечатался. Проверь ещё через час или позже.

**Comment by evgeniy-ADG** [comment]
все ок
