### ISSUE TITLE
http://www.iculture.nl/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2925]
http://www.iculture.nl/

![image](https://cloud.githubusercontent.com/assets/15856304/18125280/93580434-6f43-11e6-951a-b41d8906c0ec.png)

<details>
Application version: 1.0.8.54

Application lifetime: 2016-08-09 10:55:09 +0000

Device: iPhone

Platform: iPhone OS

OS: 9.3.3

ID: 8957874A-F43D-4653-B5B1-94D1E31CC215

Locale: en

Region: nl

Optimazed enabled: NO

Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.0.92.53 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.7.48 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.11.46 Enabled=NO

ID=14 Name="Annoyances filter" Version=1.0.3.21 Enabled=YES

ID=8 Name="Dutch filter" Version=1.0.8.91 Enabled=NO

ID=11 Name="Mobile Ads filter" Version=1.0.4.74 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.1.20 Enabled=YES

**Comment by Alex-302** [comment]
```
ID=8 Name="Dutch filter" Version=1.0.8.91 Enabled=NO
```
This banner is blockeв by this filter.
