### ISSUE TITLE
http://thenextweb.com - can't play video

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2926]
http://thenextweb.com/apple/2016/08/30/report-apple-adding-glossy-space-black-color-iphone-7/

![image](https://cloud.githubusercontent.com/assets/15856304/18126448/2e4a45b0-6f49-11e6-91d8-2379a80d11a2.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-06-01 22:22:31 +0000

Device: iPhone
Platform: iPhone OS
OS: 10.0
ID: 49E48124-6FCE-43C6-B303-FC4982BFA171

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.85.58 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.5 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.6 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.55 Enabled=YES

**Comment by Alex-302** [comment]
Added to English filter
```
@@||thenextweb.com$generichide
@@||cdn.intergi.com/hera/*.js$domain=thenextweb.com
thenextweb.com##.ad-unit
```
check them
