### ISSUE TITLE
http://linkshrink.net/7RGbn3#   pop ads is opening 

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardFilters#2927]
Hi.

Open this link http://linkshrink.net/7RGbn3#  on Android mobile. 
When you click continue then pop ads is opening
<details>
![screenshot_20160831-165821](https://cloud.githubusercontent.com/assets/19775409/18127201/7714deec-6f9c-11e6-8419-41132ba4b510.png)
</details>
Please check and fix this issue

Thanks

**Comment by evgeniy-ADG** [comment]
@Alex-302 I have reproduced the issue in Safari

<details>

![screen shot 2016-09-09 at 6 54 48 pm](https://cloud.githubusercontent.com/assets/15856304/18393675/f8b7a320-76be-11e6-8559-11b0b33be4f4.png)
![screen shot 2016-09-09 at 6 53 24 pm](https://cloud.githubusercontent.com/assets/15856304/18393678/fbd850fe-76be-11e6-8a08-e8e8d716493c.png)

**Comment by Alex-302** [comment]
Added to English filter
```
linkshrink.net#%#Object.defineProperties(window, { "_impspcabe_alpha": { value: false, writable: false }, "_impspcabe_beta": { value: false, writable: false } });
```

**Comment by Noisia12** [comment]
Popup when click on Continue button
