### ISSUE TITLE
hd21.com [NSFW] [Pop-up] [Ad Text String]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#29280]
**Site**: https://www.hd21.com/video/227681/dirty-talking-wife-gets-a-big-facial-2

**Issue**: Please remove the pop-ups & Ad text string from the page.

**Screenshot**: http://prntscr.com/mh8vjv

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 72.0.3626.81 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by AdamWr** [comment]
Fixed ad leftover, popups not reproduced.
