### ISSUE TITLE
http://m.timesofindia.com anti adblocker problem 

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardFilters#2928]
Hi.

There is anti adblocker problem when I click any news on http://m.timesofindia.com

Please check and fix the issue

Thanks

**Comment by evgeniy-ADG** [comment]
@Alex-302 please check the site, they've changed smth again, 

<details>
![screen shot 2016-09-09 at 6 52 57 pm](https://cloud.githubusercontent.com/assets/15856304/18393588/a891e5cc-76be-11e6-8d2c-f18e10b108d3.png)

![screen shot 2016-09-09 at 6 53 24 pm](https://cloud.githubusercontent.com/assets/15856304/18393598/b45ba85c-76be-11e6-8498-7e85c0b9fbdb.png)

**Comment by rajatmathurs** [comment]
Checked it now and now the adblocker problem is solved.

Thanks a lot.
