### ISSUE TITLE
Bug in Adguard the same like others Adblockers.

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#29288]
Windows 10 
Microsoft Edge
Adguard Adblocker Extension for Microsoft Edge
All filters without two filters types (Acceptate Ads and all Obsoletes)

Problem is not typical. Easier is write details than give pics. 
First something blocks all pictures example on otomoto.pl , when try look on pictures with concreto cars, devices, etc. Are more site where are blocked pics.

Second (is more private). On site Santander (earlier BZWBK) - polish site - are blocked private messages and only help turn off adblocker (first situation too).

Can help?

Best Regards

**Comment by krystian3w** [comment]
No if anyone have account in this bank..., if you do not want to consult what filter, when you switch off, repairs the chat / private messages.

**Comment by krystian3w** [comment]
> and all Obsoletes

this is shuolud turned on in AdGuard Adblocker 2.X:

`(Obsolete) Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for AdGuard`, because ID this filter list now used to serve `Polish Anti Adblock Filters`.

**Comment by seba2282** [comment]
I said "Second (is more private). On site Santander (earlier BZWBK) - polish site - are blocked private messages and only help turn off adblocker (first situation too)" 
Mean it is bank site and for protection better don't give pics from banks after login.

I said too, I don't use obsoletes. Wha t you try say, I should turn on that obsolete ((Obsolete) Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for AdGuard) ?

**Comment by krystian3w** [comment]
Yes you should turn on `(Obsolete) Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for AdGuard`, because now is it `Polish Anti Adblock Filters`.

**Comment by seba2282** [comment]
Which more obsoletes should turn?

**Comment by krystian3w** [comment]
`(Obsolete) Adblock Polska` if you like filters https://github.com/KonoromiHimaries/PolishSubFilters

**Comment by krystian3w** [comment]
I will shoot ... :gun:, turn off the "Japanese ABP filters" and check both sides if they are fixed.

**Comment by seba2282** [comment]
Only that both? Suplement Adguard and Adblock Polska? Or more obsoletes?

**Comment by krystian3w** [comment]
> Only that both? Suplement Adguard and Adblock Polska? Or more obsoletes?

only this two, no more:

* `(Obsolete) Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for AdGuard`
* `(Obsolete) Adblock Polska`


The rest did not get "replacements" to avoid reaching for the new ID - IMO.

**Comment by seba2282** [comment]
But still have that two problems, what I wrote about.

**Comment by AdamWr** [comment]
Hi,
>First something blocks all pictures example on otomoto.pl , when try look on pictures with concreto cars, devices, etc. Are more site where are blocked pics.

Please provide more details about `otomoto.pl`, direct link where it happens and screenshot.

>All filters without two filters types (Acceptate Ads and all Obsoletes)

I think that it's not good idea to use (almost) all filters, it might cause many issues and as I recall, you reported similar issue in the past - https://github.com/AdguardTeam/AdguardFilters/issues/19481
Did you tried to disable all third-party filters and check if issue still persist?

**Comment by seba2282** [comment]
@AdamWr About otomoto.pl (but with all filters with that two obsolete, what about said @krystian3w.
I give you link: https://www.otomoto.pl/osobowe/?search%5Bnew_used%5D=on. It is example where don't see any pics but numer sites are. I tried turn off Alleblock, Japan Filter or Pete Love or named third party cjx. And still have the same. About bank only are blocked messages private between client-bank. Client doesn't see them. 
On that two situations (mine problems) help only turn off adblocker as turn off, not only filters.

**Comment by krystian3w** [comment]
Many filters is thrid-party: https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty

**Comment by seba2282** [comment]
Always I thought, is better blocked ads if are more filters. I see too, filters with polish in name are third party. So maybe better turn only based filters after reinstall Adguard and see ads on no polish sites. 
@krystian3w so what you suggest to make? Have all and wait on update or turn off all filters and stay only few?

**Comment by krystian3w** [comment]
I recommend no turn on ~80 filters list in uBO / AdGuard.

**Comment by seba2282** [comment]
And that method is good way when ads on no polish sites aren't blocked?

**Comment by AdamWr** [comment]
I can't reproduce issue on `otomoto.pl`.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/52358941-2e4fe080-2a39-11e9-866f-db708f3f3412.png)

</details>
<br>

Regarding Santander, I don't have account here, so I can't check it.
Please disable filters one by one and check which one cause that issue on both websites.

**Comment by seba2282** [comment]
Can you tell me, which filters you have? I first try your settings and add next filters maybe easier will be add next and check 🙂

**Comment by AdamWr** [comment]
```
AdGuard Base/English filter
AdGuard Spyware filter
AdGuard Social Media filter
AdGuard Annoyances filter
AdGuard Simplified domain names filter
AdGuard Experimental filter
AdGuard Russian filter
AdGuard German filter
Official Polish filters for AdBlock, uBlock Origin & AdGuard
Polskie Filtry Ciasteczkowe
(Obsolete) Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for AdGuard
```

**Comment by seba2282** [comment]
So time try checking. Problem isn't only in Edge. I looked on Firefox Android with Adguard with filters what I wrote and is the same. So evidently one or more filters block to much. i created issue for Edge, so I will test on Edge.

**Comment by seba2282** [comment]
For otomoto.pl ABP Japanese Filters made problems. Without that filter is ok. Now I look on site Santander and will not turn again that one filter.

**Comment by seba2282** [comment]
Idk, more are Ajax and fonts, when I look on report filtering site Santander.

**Comment by krystian3w** [comment]
> 
> 
> And that method is good way when ads on no polish sites aren't blocked?

I do not need an international websites so much I need something more than EasyList or AdGuard Base in most case.

**Comment by Alex-302** [comment]
don't enable `ABP Japanese Filters`)

**Comment by seba2282** [comment]
@Alex-302 Your suggest fix problem with otomoto.pl and more sites that type. But still I don't know, how I can make fix for Santander Bank site. Something blocks messages and I don't see them. Only see how many are them. Here help turn off all Adguard.

**Comment by krystian3w** [comment]
Try maybe beta 3.x with activate list one by one and maybe you found guilty list and after to generic filter/rule.

https://www.microsoft.com/pl-pl/p/adguard-adblocker-beta/9ndmfr4cv25m?rtc=1&activetab=pivot:overviewtab

**Comment by seba2282** [comment]
"Juvander's Adblock List for Finland" make problem with Santander Bank Polish site. 
"ABP Japanese Filters" make problem with sites like otomoto.pl. 
That two are problematic.
Suggests?

**Comment by krystian3w** [comment]
So disable this lists:

* "Juvander's Adblock List for Finland" - he tried to hide Finland's political protests with filters https://github.com/uBlockOrigin/uAssets/issues/3780, https://github.com/uBlockOrigin/uBlock-issues/issues/285, https://github.com/NanoAdblocker/NanoCore/pull/223.

   Maybe @theel0ja / @jounihh help remove bug in, if xsist in https://github.com/finnish-easylist-addition/finnish-easylist-addition

   ---

* "`ABP Japanese Filters`" - for only Japan sites, read his Policy: https://github.com/k2jp/abp-japanese-filters/wiki/Support_Policy#to-avoid-problems-with-abp-japanese-filters, rather, they will not make corrections at home and would have to be thrown into the AdGuard list ...?

**Comment by seba2282** [comment]
That two I disabled and don't use actually.

**Comment by theel0ja** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/issues/89

**Comment by krystian3w** [comment]
Thank you!

**Comment by seba2282** [comment]
All fixed. Thanks all. :)
