### ISSUE TITLE
http://hdrezka.me

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2929]
**Description**: Не работает видео плеер в Мозилле
http://hdrezka.me/films/fiction/12967-cherepashki-nindzya2.html

Screenshot:
<details>
![screenshot_24](https://cloud.githubusercontent.com/assets/18548949/18144033/63ec84c4-6fcd-11e6-89bd-ddea0241031f.jpg)
</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Мозилла

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не повторяется ни с прогой ни с расширением.
Попроси отключать фильтры с проверкой. Если стабильно какой-то фильтр ломает, то нужен будет удалённый доступ.

**Comment by vgavrish** [comment]
Отключила все фильтры, что-то тоже самое
даже при отключенном Адг не воспроизводится
сейчас отпишу пользователю

**Comment by vgavrish** [comment]
Можно сказать проблема решилась, видео начало воспроизводиться, после обновления программы  с версии 6.0 до 6.1.

**Comment by Alex-302** [comment]
Магия.
