### ISSUE TITLE
http://indianexpress.com - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2930]
http://indianexpress.com/article/cities/delhi/delhi-government-moves-supreme-court-over-l-gs-administrative-powers/
it redirects to: http://indianexpress.com/adblocker/

<details>
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:118 Name: EasyPrivacy Url: https://easylist-downloads.adblockplus.org/easyprivacy.txt
FilterId:122 Name: Fanboy's Annoyances Url: https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
FilterId:0 Name: User filter Url: no_url
FilterId:14 Name: Annoyances filter Url: http://adguard.com/ru/filter-rules.html?id=14

**Comment by Alex-302** [comment]
Added to English filter
```
@@||js.jansatta.com/ads_js.js

```
