### ISSUE TITLE
m.gadgets.ndtv.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2932]
http://m.gadgets.ndtv.com/telecom/features/reliance-jiofi-how-to-get-started-with-jios-4g-lte-hotspot-1449809

Screenshots: 
<details>
![image1](https://cloud.githubusercontent.com/assets/14153331/18225859/d84f7502-7206-11e6-9e81-8d82ceb84e9e.png)
![image2](https://cloud.githubusercontent.com/assets/14153331/18225860/d98d6bea-7206-11e6-8830-88c18a52d7df.png)
</details>

iOS 10
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.91.79 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.31 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.74 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.18 Enabled=YES

**Comment by Alex-302** [comment]
It will be hidden by the next Adguard(for iOS) version, because current version doesn't support $generichide exclusions.

**Comment by Alex-302** [comment]
Added few rules to social and annoyances filter.
