### ISSUE TITLE
monova.* (.org|.to)

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#29335]
[https://monova.org](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://monova.org)
 [https://monova.to](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://monova.to)

 **1**. Излишняя блокировка изображений флагов в SVG для обозначения языка. Причиной тому правило `|http*://$image,other,script,subdocument,xmlhttprequest,domain=monova.org|monova.to` из Базового фильтра AdGuard (убрать image?).

 **2**. Не срабатывают кнопки. Причина та же. Для кнопок нужно `@@||monova.*/js/main.js` , причём для `.org` это уже сделано, остаётся изменить `.org` на `.*`

<details><summary>Screenshot:</summary>

![2019 02 07-1](https://user-images.githubusercontent.com/17948007/52399134-5177a000-2acc-11e9-9d0e-cd477b748577.png)
</details>

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.0.3
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
Это изилисты сломали
https://github.com/easylist/easylist/issues/2779

Поправил.
