### ISSUE TITLE
Annoyance banner on https://www.datanyze.com/market-share/dns#market-share-table

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#29334]
Wait for few seconds if it doesn't show up immediately.
Browser: Firefox 66 Beta
Adblocker: uBlock Origin 1.18.4
Adguard filters: Adguard annoyances, base, spyware, social media.

Screenshot: <img src="https://mnmlsv.net/images/7f7998cc5647759b0db70cf6d69eab86.png" alt="7f7998cc5647759b0db70cf6d69eab86.png" border="0" />

**Comment by SeriousHoax** [comment]
@Alex-302 It's not fixed yet, the banner is still showing 

<img src="https://mnmlsv.net/images/986a2bd8c099695144214aceedb4e5fc.png" alt="986a2bd8c099695144214aceedb4e5fc.png" border="0" />

**Comment by Alex-302** [comment]
I can't reproduce it. @slavaleleka please take a look.

**Comment by slavaleleka** [comment]
Can't reproduce it too.

@SeriousHoax check for filter updates please

**Comment by SeriousHoax** [comment]
I received this 3 days ago which seems to fix the issue. 

<img src="https://mnmlsv.net/images/fa3d2dc56f4a53ce9b0f4db04a4849c9.png" alt="fa3d2dc56f4a53ce9b0f4db04a4849c9.png" border="0" />
