### ISSUE TITLE
com.ellize.knots

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2933]
**Description**:
https://play.google.com/store/apps/details?id=com.ellize.knots&hl=ru
Реклама в меню приложения
Screenshot:

<details>
![screenshot_29](https://cloud.githubusercontent.com/assets/18548949/18230425/a8c5cfe6-72a3-11e6-9ac6-e5d879651dc3.jpg)

</details>

**Adguard version**: 2.7.

**Filters list**: 1,2,3,4,11,14

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Баннер встроен. Пока рекламируют свои собственные приложения.
