### ISSUE TITLE
perfectgirls.net [NSFW] [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#29344]
**Site**: http://www.perfectgirls.net/gal/576159/Big_titted_brunette_milf__Nilla_Black_is_having_an_interracial_gang_bang_with_some_horny__black_guys

**Issue**: Please remove the pop-ups seen after maximising the video player to full screen. Pop-up goes to "syndication.exoclick.com"

**Screenshot**: N/A

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 72.0.3626.81 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
Please fix

**Comment by Alex-302** [comment]
Not reproduced.
