### ISSUE TITLE
ritmoteka.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#29341]
[http://ritmoteka.ru](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://ritmoteka.ru)

 **1**. Реклама, появляющаяся в результатах поиска. Поэтому для воспроизведения показа рекламы нужно что-нибудь настучать :) . Ответственные за неё: `||ritmoteka.ru/topmessage.js` и `||ritmoteka.ru/bottommess.js` - соответственно верхний и нижний модуль.

 **2**. Пустое место внизу, в результатах поиска, там где располагаются счётчики: `ritmoteka.ru##td[height="300"]`

 **3**. Перехват выделения. По окончании выделения отрезка текста, для поиска через контекстное меню, происходит автокопирование этого текста в буфер обмена и снятие выделения. Прошу Вас избавить от этой принудиловки. Вот код, находящийся в [http://ritmoteka.ru/search.php](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://ritmoteka.ru/search.php) и отвечающий за данное действие:
```
 function copythis(el) {
     var inn1=el.innerText;
     var inn2=inn1.replace(" / "," - ");
     el.innerText=inn2;
     
        if (document.selection) {
            var range = document.body.createTextRange();
            range.moveToElementText(el);
            range.select();
        } else if (window.getSelection) {
            var range = document.createRange();
            range.selectNodeContents(el);
            window.getSelection().removeAllRanges();
            window.getSelection().addRange(range);
        }
  
   try {
    var successful = document.execCommand('copy');
    var msg = successful ? 'successful' : 'unsuccessful';
    var xx=MouseCoords.x+10;
    var yy=MouseCoords.y+10;
    document.getElementById('informer').style.top=yy + 'px';
    document.getElementById('informer').style.left=xx + 'px';
    document.getElementById('informer').style.display='block';
    setTimeout(delinf,1000);
  } catch (err) {
    //console.log('Oops, unable to copy');
  }
    
    el.innerText=inn1;
 }

function delinf() {
    document.getElementById('informer').style.display='none';
    document.getElementById('informer').innerHTML='Скопировано в буфер';
}

function inform(el) {
    var xx=MouseCoords.x+10;
    var yy=MouseCoords.y+10;
    document.getElementById('informer').style.top=yy + 'px';
    document.getElementById('informer').style.left=xx + 'px';
    document.getElementById('informer').innerHTML=el.title;
    document.getElementById('informer').style.display='block';
    setTimeout(delinf,1000);
}
```

<details><summary>Screenshot's:</summary>

![2019 02 07-2](https://user-images.githubusercontent.com/17948007/52408283-9e1aa580-2ae3-11e9-848e-0cf7e98f277d.png)
----------
![2019 02 07-3](https://user-images.githubusercontent.com/17948007/52408296-a541b380-2ae3-11e9-8614-af8cec2c4f5b.png)
</details>

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.0.3
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
Рекламу заблокировал. С выделением не повторяется.

**Comment by XX-J** [comment]
> С выделением не повторяется.

<details><summary>Proof:</summary>

![video_2019-02-12_065232](https://user-images.githubusercontent.com/17948007/52612002-01685700-2e99-11e9-82bc-422c02255b5f.gif)
</details><br/>

 Может ещё пустое место под результатами поиска скроете?

**Comment by Alex-302** [comment]
отступ убрал. С выделением так и не повторяется.

**Comment by XX-J** [comment]
> С выделением так и не повторяется.

 Попробуйте выделять выдаваемые ritmotek'oй названия групп, исполнителей или песен. Или поверьте моим доказательствам, в виде анимированной gif'ки и куска кода, встроенного в `search.php`, приведённым выше.
 Создайте, пожалуйста, правило, блокироющее поведение вышеозначенного js-скрипта, а я проверю и отпишусь.

**Comment by Alex-302** [comment]
глянь такое
`#%#Object.defineProperty(window, 'copythis', { get: function() { return function(){}; } });`
или
`#%#AG_onLoad(function() { window.copythis = function() {}; });`

**Comment by XX-J** [comment]
Зашибись - Всё работает! Спасибо.

Конкретнее: Оба правила работают, НО первое ~перерабатывает~ ещё и отключает установку галочек "это она" со ссылками вида `javascript:gotit(12073,'54145')`. Поэтому лучше вариант 2 - `#%#AG_onLoad(function() { window.copythis = function() {}; });`. Надеюсь Вы его добавите в общие фильтры...

**Comment by Alex-302** [comment]
ок
