### ISSUE TITLE
Adguard not working for Multiup when proxy enabled

### ISSUE THREAD

**Issue by rayman3003** [AdguardTeam/AdguardFilters#2934]
Adguard doesn't work in multiup when proxies have been enabled in internet browsers (IE, Firefox, Chrome).

In normal mode (no proxy), there is no problem & all Ads & popups gets blocked by Adguard.

But When I use proxy (IPs)[For example 127.0.0.1:6675] in my browsers (IE, Firefox, Chrome), all the ads and popups comes back.

example link:

https://www.multiup.org/en/download/f1b09b57e1280d021b481729c7552e99/vYVCu00KnDFVdGUdKB8b5B4lxWkbm6_opg.rar

Update:

It works in proxy when multiup is not in SSL mode. But with SSL enabled, Adguard doesn't work.

----------------------------
not working (SSL enabled):

https://www.multiup.org/en/download/f1b09b57e1280d021b481729c7552e99/vYVCu00KnDFVdGUdKB8b5B4lxWkbm6_opg.rar

---------------------------
Working (no SSL);

http://www.multiup.org/en/download/f1b09b57e1280d021b481729c7552e99/vYVCu00KnDFVdGUdKB8b5B4lxWkbm6_opg.rar

**Comment by Alex-302** [comment]
Wrong repository.
Please write to AdguardForWindows
