### ISSUE TITLE
KMP Player

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2935]
**Description**: Реклама в плеере, можно убрать?
http://www.kmplayer.com/

Screenshot:
<details>
![screenshot_31](https://cloud.githubusercontent.com/assets/18548949/18245155/5d773c40-736c-11e6-9363-1b3e0aaadf8b.jpg)

</details>

**Adguard version**: 6.1

**Filters list**: 1,2,3,4,14

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Да.
Добавил в англ фильтр
```
||player.kmpmedia.net/kmp_plus/platform/view/main
```

**Comment by Alex-302** [comment]
Только в список фильтруемых нужно добавить.
