### ISSUE TITLE
https://www.engadget.com/ - social media buttons

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2937]
https://www.engadget.com/2016/09/01/youtubers-call-out-ad-guidelines-as-a-form-of-censorship/

<details>
Application version: 1.0.8.54

Application lifetime: 2016-07-08 20:23:54 +0000

Device: iPhone

Platform: iPhone OS

OS: 9.3.5

ID: 788DE48C-804A-45A5-A4D6-EAA735DF37D3

Locale: en

Region: mx

Optimazed enabled: NO

Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.0.93.15 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.7.55 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.12.17 Enabled=YES

ID=14 Name="Annoyances filter" Version=1.0.3.42 Enabled=YES

ID=1 Name="Russian filter" Version=1.0.36.20 Enabled=NO

ID=6 Name="German filter" Version=1.0.26.20 Enabled=NO

ID=7 Name="Japanese filter" Version=1.0.92.97 Enabled=NO

ID=8 Name="Dutch filter" Version=1.0.8.84 Enabled=NO

ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.34 Enabled=YES

ID=13 Name="Turkish filter" Version=1.0.2.53 Enabled=NO

ID=5 Name="Experimental filter" Version=1.0.26.12 Enabled=NO

ID=11 Name="Mobile Ads filter" Version=1.0.4.78 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.1.20 Enabled=YES

ID=101 Name="EasyList" Version=1.0.60.34 Enabled=NO

ID=207 Name="Adblock Warning Removal List" Version=1.0.61.40 Enabled=NO

ID=208 Name="Malware Domains" Version=1.0.61.71 Enabled=NO

ID=209 Name="Prebake" Version=1.0.1.14 Enabled=NO

ID=210 Name="Spam404" Version=1.0.1.50 Enabled=NO
</details>

![image](https://cloud.githubusercontent.com/assets/15856304/18251180/42b8387c-7390-11e6-9a1c-3d56cdf8d6d8.png)

**Comment by Alex-302** [comment]
Added to Social filter
```
engadget.com##.o-mobile-share-footer
```
