### ISSUE TITLE
Question about one rule for tukero.org

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#29382]
Microsoft Edge, Adguard Extension, Windows 10
Filters all without (ABP Japanese, Juvanders Finland and acceptable ads)
With Obsolete Polish Suplement Adguard and Obsolete Adblock Polska

On tukero.org chat doesn't work without rule @@||cbox.ws (in all browsers).

It is possible add that rule or I need ask somewhere else? Where?

**Comment by Alex-302** [comment]
It is blocked in ABP Japaneseonly. Please disable filters one-by-one.

**Comment by seba2282** [comment]
@Alex-302, I don't use Juvander's and ABP Japanese filters.  On tukero.org with chat is RU AdList: BitBlock filter as problematic. That filter blocks chat on tukero.org i need rule @@||cbox.ws. Now deactivated that filter and is normal chat works. So three filtrers doesn't work good: ABP Japanese, Juvander's and RU Adlist: Bitblock.

**Comment by Alex-302** [comment]
It is expected result for `RU AdList: BitBlock`
