### ISSUE TITLE
Ads on wiadomosci.wp.pl

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#29381]
Microsoft Edge, Adguard Extension, Windows 10 

Filters all without (ABP Japanese, Juvanders Finland and acceptable ads)
With Obsolete Polish Suplement Adguard and Obsolete Adblock Polska

wiadomosci.wp.pl show ads
exaple link: 

https://wiadomosci.wp.pl/tasmy-kaczynskiego-pis-prezes-od-lat-nie-byl-tak-oslabiony-ale-to-nas-wladzy-nie-pozbawi-6344046730905729a

**Comment by AdamWr** [comment]
Please update filters.

**Comment by seba2282** [comment]
Now works. Thank you
