### ISSUE TITLE
http://fikirto.com/ - social media buttons

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2938]
http://fikirto.com/instagram-zoom-nasil-yapilir/

![image](https://cloud.githubusercontent.com/assets/15856304/18251421/9609a30c-7391-11e6-8b14-834748ad16d5.png)

<details>
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.93.37 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.55 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.21 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.38.66 Enabled=YES
ID=6 Name="German filter" Version=1.0.27.12 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.93.1 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.8.94 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.34 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.3.35 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.79 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.21 Enabled=YES

**Comment by Alex-302** [comment]
fixed
