### ISSUE TITLE
gittigidiyor.com - broken payments

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#294]
Credit Card payments are broken

https://qcrm.cc/#/customer/717598

**Comment by Alex-302** [comment]
Сложно с турками, сайт без других языков...
Посоветовать бы выключать фильтры по одному, начиная с изи-листов.

**Comment by vbagirov** [comment]
спросил у юзера, поможет ли занесение в вайтлист

**Comment by Alex-302** [comment]
Молчит?
