### ISSUE TITLE
https://www.chotot.com - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2940]
https://www.chotot.com/quan-hoang-mai/mua-ban-dien-thoai-di-dong/sky-760s-vega-pantech-full-pk-2-pin-sdp-10400mah-z-18004796.htm#

1. That website only https://www.chotot.com, i use firefox and chrome.

2. When I need the mobile number of the seller, i click "Bấm để hiện số" in
website. if adguard enable "don't show any". if adguard disable "i have
mobile number after click".

3.
Screenshot when adguard enable: http://i.imgur.com/9Of0mlt.jpg
Screenshot when adguard disable: http://i.imgur.com/Gs6I5Th.jpg

<details>
AppVersion: 6.1.258.1302
Main settings: 
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:207 Name: Adblock Warning Removal List Url: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
FilterId:211 Name: Anti-Adblock Killer | Reek Url: https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
FilterId:214 Name: ABPVN List Url: http://abpvn.com/filter/abpvn-53fde4f714c78.txt
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Tdi

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||tags.tiqcdn.com/utag/schibsted/chotot/prod/utag.js
```
