### ISSUE TITLE
https://news.yandex.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2941]
![image](https://cloud.githubusercontent.com/assets/15856304/18253403/186b6ec4-739d-11e6-8549-e6cdb52f14db.png)
1. На сайте https://news.yandex.ru/ в браузерах google chrome и firefox
2. Русский, английский, Фильтр счетчиков и системы аналитики, Фильтр 
   виджетов социальных сетей, Фильтр раздражителей, anti-adblock-killer.
3. В режиме Инкогнито или Приватного окна рекламы яндекс директ нет.

Если удалить куки, то реклама пропадает до авторизации на яндексе.

1159630

**Comment by Alex-302** [comment]
Какой браузер, версия Адгарда, список фильтров?

**Comment by Rbuha** [comment]
google chrome и firefox, adguad 6.1258.1302 
Русский, английский, Фильтр счетчиков и системы аналитики, Фильтр виджетов социальных сетей, Фильтр раздражителей, anti-adblock-killer, эксперементальный фильтр.
Сегодня обнаружил, что реклама везде заблокирована.
Спасибо!

**Comment by vgavrish** [comment]
Реклама. Браузер Firefox
фильтры 1,2,3,4,14,5
расширений нет
страница если поможет
https://yadi.sk/d/zz-NSb4mwMpHE
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19154468/4c1e9fbc-8be3-11e6-8021-d9c57b1d7742.png)

**Comment by Alex-302** [comment]
Это в прогой?

**Comment by vgavrish** [comment]
Да, прога

**Comment by Alex-302** [comment]
Передай на проверку
```
news.yandex.ru##.rubric_type_main > div[class*=" "][-ext-has='a[href*="/clck/jsredir?"]']
news.yandex.ru##.page-content__extra-item[-ext-has='div.page-content__extra-item > div > h3 > a[title="Яндекс.Директ"]']
```
желательно по нескольким разделам побродить и новостям в них.

**Comment by vgavrish** [comment]
хорошо, передаю

**Comment by vgavrish** [comment]
1081932
Правила не помогли. Реклама появилась
Новая сохранненая страница, может поможет
https://yadi.sk/d/Xp73grlFwiEjF

**Comment by Alex-302** [comment]
а попроси точные ссылки на страницы с рекламой.
Сохраненная не поможет, элементы динамически добавляются.

**Comment by vgavrish** [comment]
Есть вот такая ссылка:

news.yandex.ru/yandsearch?cl4url=ria.ru/world/20161010/1478849235.html&lang=ru&from=main_portal&lr=172

**Comment by Alex-302** [comment]
Вроде заблокировал. Но есть баг с новым типом правил, из-за которого скрытые элементы снова становятся видны.

**Comment by vgavrish** [comment]
id 1430744
https://news.yandex.ru/yandsearch?lr=213&cl4url=www.kommersant.ru%2Fdoc%2F3130780&content=video&from=story
Вот снова на странице появилась реклама: http://prntscr.com/d0emhp
Ф: 1,2
Хром
версия 6.1.258.1302

**Comment by Alex-302** [comment]
поправил

**Comment by Serzh-SUP** [comment]
**У нашего пользователя снова появилась реклама в [Яндекс.](https://news.yandex.ru/quotes/1006.html) У меня кстати тоже, первый раз проверял, ее не было, сейчас также есть.**

![2016-11-29_21-48-05](https://cloud.githubusercontent.com/assets/16462533/20726338/ccc5a6a0-b67d-11e6-8d43-6c076a3bb5a6.png)

**Comment by Alex-302** [comment]
Поправил.
Не забывай переоткрывать, чтоб не терялось.

**Comment by Bohdan-SUP** [comment]
У пользователя 1081932 снова появилось:
<details>

![default](https://cloud.githubusercontent.com/assets/14153331/22855315/3ea6cc02-f087-11e6-8a2c-d5d6f9f01392.jpg)
![default](https://cloud.githubusercontent.com/assets/14153331/22855316/3f80031e-f087-11e6-9609-9bdf05433719.jpg)

</details>

**Comment by Alex-302** [comment]
@Bohdan-SUP передай на проверку
```
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua##.page-content__layout > div.page-content__right > div[class]:not([class*="page-content__col"])[-ext-has='div > h3 > a[href*="/clck/jsredir"]']
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua##.page-content__layout > div.page-content__left > div[class][-ext-has='div > h4 > a[href*="/clck/jsredir"]']
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua##.page-content__layout > div.page-content__right > div.page-content__col > div[-ext-has='div > h3 > a[title="Яндекс.Директ"]']
news.yandex.by,news.yandex.com,news.yandex.kz,news.yandex.ru,news.yandex.ua##.page-content__layout > div.page-content__right > div.page-content__col > div.page-content__extra-item > div[class][role="complementary"][-ext-has='a[href*="/clck/jsredir"]']
```

**Comment by Bohdan-SUP** [comment]
Передал.

**Comment by Bohdan-SUP** [comment]
@Alex-302 помогло

**Comment by Alex-302** [comment]
атлична-атлична
