### ISSUE TITLE
missed ads plomba911.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2942]
**Проблема повторилась, как на ПК, так и на iOS**

http://plomba911.ru/lechenie-zubov/pulpit/udalenie-nerva-iz-zuba.html

**ФИЛЬТРЫ:**

> Пользовательский
> Английский
> Фильтр счетчиков и систем аналитики
> Экспериментальный
> Фильтр раздражителей
> Русский

![image1](https://cloud.githubusercontent.com/assets/16462533/18276820/05b45558-7455-11e6-887a-12800ee99f96.PNG)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
plomba911.ru##.banner_left
```
