### ISSUE TITLE
AdGuard chrome extension - blocking cookie notices?

### ISSUE THREAD

**Issue by tbcam88** [AdguardTeam/AdguardFilters#29432]
Hi all,

Is it possible to block cookie notices? (see pic below) I've tried annoyances filter but they persist!

![cookies](https://user-images.githubusercontent.com/19891537/52520283-d7782000-2c5f-11e9-8325-6f639c328532.png)

**Comment by Eugene-Savenko** [comment]
The AdGuard Annoyances filter blocks such notices. If it fails to block an annoyance on a certain website, please report that website from within the extension ("Submit a complaint about this website").
