### ISSUE TITLE
http://community.us.playstation.com - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2943]
Incorrect blocking on page:
http://community.us.playstation.com/t5/Consoles-Peripherals/Sony-stole-150-from-me-for-an-unnecessary-quot-out-of-warranty/m-p/45937011#M260237

I cannot click any buttons on the PlayStation forum. I have to disable AdGuard to do so. This problem also extends to the Safari version of AdGuard

<details>
![image1](https://cloud.githubusercontent.com/assets/15856304/18276967/7858c03a-7455-11e6-8bca-adcb7b21b734.PNG)
</details>

**Comment by evgeniy-ADG** [comment]
Spyware filter causes this.

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||metrics.us.playstation.com/b/ss/
```
