### ISSUE TITLE
http://m.peru21.pe/movil - incorrect blocking

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2944]
**Description**:
http://m.peru21.pe/movil

I guess this is because `body class="adstop"`

**Comment by Alex-302** [comment]
The same issue on desktop.
Added to English filter
```
peru21.pe#@#.adstop

```

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/18322818/a0953936-7502-11e6-9485-3478155235da.png)
Works fine once Safari filter is disabled.

**Comment by Alex-302** [comment]
Very strange. Safari filter has no rules for this site.

**Comment by evgeniy-ADG** [comment]
I asked the customer to turn subscriptions one by one, he replied that it starts rendering correctly when he disables Safari filter. I could not reproduce it on my iPad at all. On Safari with iPhone user-agent it behaves in a strange way - works fine for some time, then turns blank and won't display the site when you disable Adguard.

**Comment by Alex-302** [comment]
I see only popup with registration form.
