### ISSUE TITLE
Ads and video ads are not being blocked on Facebook.com

### ISSUE THREAD

**Issue by zefwef** [AdguardTeam/AdguardFilters#29459]
The ads that appear in your Facebook feed, as well as the ads that appear while watching Facebook videos are not being blocked on desktop.

Filters used are the base filter and spyware filter.

**Comment by BlazDT** [comment]
Ads in videos not reproduced. Ads will be handled again, trying to find good selector for it.
Please always provide every required information as outlined in template, thank you.
