### ISSUE TITLE
rbc.ru

### ISSUE THREAD

**Issue by Hawkrus** [AdguardTeam/AdguardFilters#2945]
Появилась реклама на [rbc.ru](http://www.rbc.ru/technology_and_media/07/09/2016/57cffb769a7947a3459e4a2e):

![rbc](https://cloud.githubusercontent.com/assets/19652388/18313375/3067982e-7517-11e6-83a7-829dc4fd5bd8.PNG)

**Adguard version**: 6.1.258.1302

**Filters list**: Русский фильтр

**Operating system**: Windows 7

**Browser**: Chrome

**Comment by Hawkrus** [comment]
Так же появился яндекс директ при прокрутке новостей: 
![rbc](https://cloud.githubusercontent.com/assets/19652388/18383154/d5188ac4-768c-11e6-9e9f-a6bc386597f0.PNG)

**Comment by Alex-302** [comment]
После обновления будет чисто.
