### ISSUE TITLE
http://www.golem.de/ - self-advertising

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2946]
http://www.golem.de/news/eu-kommission-facebook-uebernahme-von-whatsapp-wird-neu-geprueft-1609-123072.html

<details>

![img_0380](https://cloud.githubusercontent.com/assets/15856304/18315612/453ee05a-7520-11e6-8b20-f171c150dbd7.PNG)
</details>

Filters
<details>
Application version: 1.0.8.54
Application lifetime: 2016-09-03 15:43:09 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.5
ID: 5451F795-F8BD-48CA-90EB-BE83200D86B1

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.93.37 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.55 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.21 Enabled=YES
ID=6 Name="German filter" Version=1.0.27.12 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.21 Enabled=YES
+ annoyances

**Comment by Alex-302** [comment]
Added to German filter
```
golem.de##iframe[width="940"][height="250"]

```
