### ISSUE TITLE
http://www.igen.fr - missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2947]
http://www.igen.fr/actu?page=1#comments

![image](https://cloud.githubusercontent.com/assets/15856304/18317117/137cc404-74eb-11e6-932d-2187bf17596b.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-09-04 01:35:26 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.5
ID: BF6B03EC-35EA-4B6F-9A82-00D7243A6F67

Locale: fr
Region: ca

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.93.71 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.58 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.31 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.24 Enabled=YES
ID=113 Name="Liste FR" Version=1.0.65.4 Enabled=YES

**Comment by Alex-302** [comment]
Added to English filter
```
igen.fr##body > a[style^="z-index:"]
igen.fr#$##motherboard { top: 30px!important; }
```
The second rule is not for iOS.
