### ISSUE TITLE
gazetadodia.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#29491]
`https://gazetadodia.com/`
`https://gazetadodia.com/2019/02/de-kart-e-embriagado-homem-foge-da-pm-pelas-ruas-no-parana-veja-o-video/3622/`

Ad banners, which can be blocked with: `||ibb.co^$domain=gazetadodia.com`

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.4
Firefox 65

**Comment by BlazDT** [comment]
No visitors.
Blocking whole ibb.co for whole domain can be dangerous as they may use it in the future for real ads.
Safer rules for user filter:
```
gazetadodia.com##.td-a-rec
gazetadodia.com##a[href*="gazetadodia.com"] > img[src*="ibb.co"]
gazetadodia.com##.vc_raw_html a[href]:not([href*="gazetadodia.com"]) > img
```

**Comment by adranger** [comment]
@BlazDT, sorry, but I didn't understand you. If you mean that they might use it for first-party ads, I don't think that's the case, because they use their servers for their own images. 

@Alex-302 blocked Imgur for another site in a similar case: 

https://github.com/AdguardTeam/AdguardFilters/issues/27118#issuecomment-449415306

https://github.com/AdguardTeam/AdguardFilters/blob/8c772e6a91d98f99c009afff8bad5f48bee4aa56/SpanishFilter/sections/specific.txt#L5

**Comment by BlazDT** [comment]
The site has not enough visitors for filter lists.

**Comment by krystian3w** [comment]
How find visitors counter?

**Comment by BlazDT** [comment]
https://www.alexa.com/siteinfo/gazetadodia.com

**Comment by adranger** [comment]
Using Alexa is irrational. It only counts people who have installed their malware or sites that use their scripts.

>Alexa's traffic estimates are based on data from our global traffic panel, which is a sample of millions of Internet users using one of many different browser extensions. In addition, we gather much of our traffic data from direct sources in the form of sites that have chosen to install the Alexa script on their site and certify their metrics. However, site owners can always choose to keep their certified metrics private.
