### ISSUE TITLE
fishki.net

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2949]
**Description**:
http://m.fishki.net/2048586-15-prichin-pochemu-ne-stoit-est-v-makdonaldse.html?from=fb

На андроид пролистав страницу появляется сообщение:
http://prntscr.com/cfb90z

На вин идет осветление страницы:
http://prntscr.com/cfbag4

Можно убрать сообщение?

**Filters list**: 1,2,3,4,11,14

**Operating system**: Андроид, Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в фильтр соц. сетей
```
fishki.net##.like_wall
```
