### ISSUE TITLE
efl.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2950]
**Description**: League table is blocked at http://www.efl.com/sky-bet-championship/league-table/

Screenshots:
<details>
![nothing here](https://cloud.githubusercontent.com/assets/14153331/18341589/516cc4e4-75b3-11e6-97a3-316acbefffbf.png)
![adguard off](https://cloud.githubusercontent.com/assets/14153331/18341598/5a231f3e-75b3-11e6-9fa1-08d9108f1f35.png)
</details>

**Filters list**:
![screen shot 2016-09-08 at 11 00 10 am](https://cloud.githubusercontent.com/assets/14153331/18341609/6d79eae0-75b3-11e6-89fc-8ae14e003e47.png)

**Comment by Alex-302** [comment]
There are only ads
<details>
![image](http://imagizer.imageshack.com/img923/3512/LRX1Yb.png)
</details>
