### ISSUE TITLE
pilotavia.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2951]
**Description**: we block the passenger number selection

Screenshots:
<details>
![screen shot 2016-09-08 at 12 52 55 pm](https://cloud.githubusercontent.com/assets/14153331/18345262/6562ebe4-75c3-11e6-80d2-0ca9bb035508.png)
![screen shot 2016-09-08 at 12 52 47 pm](https://cloud.githubusercontent.com/assets/14153331/18345263/65661ddc-75c3-11e6-9674-be07121c51f6.png)
</details>

**Filters list**:
![screen shot 2016-09-08 at 11 00 10 am](https://cloud.githubusercontent.com/assets/14153331/18345273/6e98bb26-75c3-11e6-953d-0a62057037e6.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
pilotavia.ru#@##adt
```
