### ISSUE TITLE
http://the-watch-series.to

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2952]
**Description**: click-under at http://the-watch-series.to/serie/Teen_Titans_Go

Screenshot: 
<details>
![screen shot 2016-09-08 at 1 37 02 pm](https://cloud.githubusercontent.com/assets/14153331/18346590/a2c2c47c-75c9-11e6-9056-12756aacbc59.png)
</details>

**Filters list**:
![screen shot 2016-09-08 at 11 00 10 am](https://cloud.githubusercontent.com/assets/14153331/18346591/a5fa96a6-75c9-11e6-967a-b574b8c16f9d.png)

**Comment by Alex-302** [comment]
Added to English filter
```
the-watch-series.to#%#Object.defineProperties(window, { "_impspcabe_alpha": { value: false, writable: false }, "_impspcabe_beta": { value: false, writable: false } });
||ws-gateway.com^

```
