### ISSUE TITLE
videoplayer blocked

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2953]
Блокируется плеер на сайте:
http://putlocker.is/watch-how-i-met-your-mother-tvshow-season-5-episode-20-online-free-putlocker.html

При отключении, появляется.

**Фильтры:**
```
Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский
```

**Comment by Alex-302** [comment]
fixed
