### ISSUE TITLE
Missed ads in NYT email on iOS

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2954]
Ok, so user receives emails and Adgaurd on iOS doesn't block ads in them, from AdChoices, for example, emails are opened through the browser. It's perfectly blocked on Mac OS X.

The original thread, please have a look: 1372096

How dow it looks on Mac OS X without Adguard:
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/18357009/4314984a-75bd-11e6-87e4-ead850d9c57b.png)

</details>

Om Mac OS X with Adguard extensions
<details>
![image](https://cloud.githubusercontent.com/assets/15856304/18357029/55bb2ce8-75bd-11e6-909a-0a225aee01bc.png)

</details>

On iOS with English, Spyware, Annoyances, Russian filters
<details>
![file_000](https://cloud.githubusercontent.com/assets/15856304/18356959/fff7e328-75bc-11e6-8cea-6f9ed3461b3a.png)
![image](https://cloud.githubusercontent.com/assets/15856304/18357043/641bc374-75bd-11e6-9584-64e817ed62dd.png)

**Comment by Alex-302** [comment]
Пример письма нужен.

**Comment by Alex-302** [comment]
И контент-блокер из иОС (filter.gz)

**Comment by evgeniy-ADG** [comment]
в тикете пример письма посмотри, пож-та, пользователь пересылал, дебаг там тоже есть, но, думаю, стоит просить новый, по-нормальному записанные и со временем?

**Comment by Alex-302** [comment]
На иос нет журнала запросов.

**Comment by Alex-302** [comment]
> в тикете пример письма посмотри
не вижу. Только скрин. Пусть перешлёт на почту Адгарда, и добавит что это для меня

**Comment by evgeniy-ADG** [comment]
там не скрин, там именно письмо, нужно посмотреть письма пользователя как html.
