### ISSUE TITLE
place.leadada.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2955]
Hello,

for some reason Adguard add-on installed on Yandex browser blocks our content.
We use domain place.leadada.com to load widgets on sites, working in afiliate program, and this affects
their appearance. For example, http://demo.protein.company

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/18357379/c7583e6c-75be-11e6-9d6d-567c8b3d7349.png)
</details>

Please see for more details: 1407348

**Comment by Alex-302** [comment]
@evgeniy-ADG 
в шаблоне запрашивается два скрина - с и без Адгарда. Как их виджет выглядит?

**Comment by astudnev** [comment]
Прикрепляю с выключенным и включенным  adguard
![adguard_off](https://cloud.githubusercontent.com/assets/1385046/18962004/134f30c4-8680-11e6-989b-f520fc8b1058.png)
![adguard_on](https://cloud.githubusercontent.com/assets/1385046/18962005/135cc2d4-8680-11e6-9a95-fbd9f2de1141.png)

**Comment by Alex-302** [comment]
@astudnev Не совсем понятно, как задуман показ - либо слайдер либо баннер партнёрки, или одновременно? У меня отображается либо первое(без фильтров) либо второе(с фильтрами)

**Comment by astudnev** [comment]
Да, приглашение там показывается вместо слайдера. И если включить AdGuard то ничего не показывается.

У нас большая часть работы этого домена ( leadada.com  )  в показе встроенных форм и виджетов для сайтов. Блокируя это содержимое, смысл страницы сайта полностью теряется.

Вот пример:
https://kredit.beregu.ru/

Без AdGuard:
![beregu_without_adguard](https://cloud.githubusercontent.com/assets/1385046/18992167/d43dd422-872d-11e6-81c2-13b5421e780d.png)

С Adguard
![beregu_with_adguard](https://cloud.githubusercontent.com/assets/1385046/18992174/e32b1cec-872d-11e6-9919-71cd98197c6b.png)

**Comment by Alex-302** [comment]
Понял, починим.

**Comment by Alex-302** [comment]
После обновления фильтров leadada.com блокироваться не будет.

**Comment by astudnev** [comment]
спасибо
