### ISSUE TITLE
http://m.muyuge.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2956]
http://m.muyuge.com/51_51490/19602855.html

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/18365728/d4267cd0-75e1-11e6-88ae-13c22220389f.png)
</details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.93.78 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.59 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.33 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.89 Enabled=NO
ID=5 Name="Experimental filter" Version=1.0.26.24 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.83 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.24 Enabled=YES
ID=101 Name="EasyList" Version=1.0.62.39 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.65.23 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.1.46 Enabled=YES

**Comment by Alex-302** [comment]
@evgeniy-ADG все картинки - реклама?
Я добавил в моб фильтр
```
||sscefsol.com^
||sas816.ujikdd041o.cn^$third-party
```
пусть юзер проверит
