### ISSUE TITLE
https://m.geektimes.ru/ - annoyances

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2957]
https://m.geektimes.ru/

![image](https://cloud.githubusercontent.com/assets/15856304/18366297/21e16136-75e4-11e6-86b6-36809eb5aeae.png)

Мы можем такое скрыть?

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
m.geektimes.ru##.footer__apps
```
