### ISSUE TITLE
www.extragold.nl -doesn't filter at all.

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#2958]
Ads. No even Adguard Assistant icon.
![image](https://cloud.githubusercontent.com/assets/20476168/18379933/a9d40a14-767d-11e6-8871-3e80a60177c1.png)
 Adguard version 6.1
Default settings
Browser Chrome

**Comment by Alex-302** [comment]
What is not removed?

**Comment by Fridrix** [comment]
@Alex-302 no even Adguard icon. But why?

**Comment by Alex-302** [comment]
Страница состоит из нескольких фреймов, поэтому помощника нет.
