### ISSUE TITLE
Ghostery settings issue

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2959]
**Steps to reproduce the problem**:
- install Ghostery
- go to https://extension.ghostery.com/en/settings
- click on Social media category -> it won't expand. Disabling Annoyances filter helps.
- click on Advertising -> won't expand. Disabling Russian filter helps.

The settings user is referring to:
https://i.imgur.com/HyMvwow.png

More details in ID **1409527**

**Comment by Alex-302** [comment]
C соц сетями не повторилось.
Добавил в русский:
```
extension.ghostery.com#@##advertising
```
