### ISSUE TITLE
rumedia.ws

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#2960]
если полазить по страничке, вылетит вот такой попап http://vulkangames.net/?lp=bc_jmp2&trackCode=mb_trafstore_vp_split_insdepjmp2_78

сегодня днем у тебя повторялось :)

хром, macos app, стандартные фильтры,

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||rumedia.ws/jjgfdfasa.js
rumedia.ws#%#Object.defineProperty(window, 'utg_click', { get: function() { return 1; } });

```
