### ISSUE TITLE
http://www.ndtv.com/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2961]
http://www.ndtv.com/video/live/channel/ndtv24x7?pfrom=home-topnavigation2016

![screen shot 2016-09-09 at 6 29 09 pm](https://cloud.githubusercontent.com/assets/15856304/18392699/6a2dd636-76bb-11e6-8af1-d34dc1056ae7.png)

<details>

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0
ID=2 Name="English filter" Version=1.0.93.90
ID=3 Name="Spyware filter" Version=1.0.7.60
ID=4 Name="Social media filter" Version=1.0.12.41
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.89

**Comment by Alex-302** [comment]
Fixed today.
