### ISSUE TITLE
http://www.mackungfu.org - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2962]
![screen shot 2016-09-09 at 7 51 02 pm](https://cloud.githubusercontent.com/assets/15856304/18395322/c4b22cc8-76c6-11e6-9429-ed9a1a314103.png)

<details>
![screen shot 2016-09-09 at 6 53 24 pm](https://cloud.githubusercontent.com/assets/15856304/18395329/cb435774-76c6-11e6-9799-1fd7e4b3456a.png)

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||mackungfu.org^$generichide
```
