### ISSUE TITLE
auto.am

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2964]
auto.am

Screenshot:

![screen shot 2016-09-09 at 9 26 54 pm](https://cloud.githubusercontent.com/assets/14153331/18398216/6a438fee-76d4-11e6-848e-47db9827b915.png)

**Filters list**:
![screen shot 2016-09-09 at 9 27 49 pm](https://cloud.githubusercontent.com/assets/14153331/18398235/8042a65e-76d4-11e6-8749-05ddbe441362.png)

**Comment by Alex-302** [comment]
Added to English filter
```
||auto.am/files/uploads/html5_banners/
||auto.am/ajax.php?act=loadBanners

```
