### ISSUE TITLE
##img[width="***"][height="***"] - Breakage (AdGuard Base filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#29659]
### Issue:
Generic image filters causes random breakage.

### Example:
`http://emilyblunt.us/photos/displayimage.php?album=173&pid=4243/`

### Screenshot (blocked image marked in red):

![filterissue-emilybluntus](https://user-images.githubusercontent.com/9382674/52852191-31715d80-3118-11e9-990a-e4cd5403a495.jpg)

### Elaboration:
In the example above, the breakage is caused by the following rule (found in '**AdGuard Base filter**'):
`~4pda.ru,~drweb.co.il,~moboi.narod.ru##img[width="240"][height="400"]`

### Possible fixes:
* Alternative 1 (modify the specific problem rule, to include one more exception):
`~4pda.ru,~drweb.co.il,~emilyblunt.us~moboi.narod.ru##img[width="240"][height="400"]`

* Alternative 2 (modify all generic image rules, to exclude all similar photo galleries) **[Needs to be verified]**:
```
~4pda.ru,~drweb.co.il,~moboi.narod.ru##img[width="240"][height="400"]:not([src*="albums"])
##img[width="240px"][height="400px"]:not([src*="albums"])
##img[width="460"][height="60"]:not([src*="albums"])
##img[width="468"][height="60"]:not([src*="albums"])
##img[width="600"][height="90"]:not([src*="albums"])
##img[width="720"][height="90"]:not([src*="albums"])
##img[width="728"][height="90"]:not([src*="albums"])
```

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.3.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.8 (XUL)

**Comment by krystian3w** [comment]
Should good as long ads no use "`albums`" in URL/URI to show up.
