### ISSUE TITLE
revouninstaller ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2965]
**Description**:
Номер сборки 2.0.0
Скачивал с официального сайта, чуть ниже бесплатная версия http://www.revouninstaller.com/revo_uninstaller_free_download.html

Программа добавлена в фильтруемые. у меня не повторяется.
программу переустанавливали

Screenshot:
<details>
![default](https://cloud.githubusercontent.com/assets/18548949/18408397/64d9ee64-7737-11e6-9a60-6c845055fae7.jpg)
</details>

**Adguard version**: 6.1

**Filters list**: Русский, Английский

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Тоже не повторяется.

**Comment by Alex-302** [comment]
Можно удалённо глянуть.

**Comment by Alekseyghub** [comment]
Вначале она может не повторяться, но потом все равно вылезает. Удаленно можете глнять мой телефон для связи вышлю через почту мой email aleksey.mail2@gmail.com

**Comment by Alex-302** [comment]
@Alekseyghub написал вам на почту.

**Comment by Alekseyghub** [comment]
Ответил, должно придти письмо.

**Comment by Alex-302** [comment]
Похоже баннер локально хранится. Запросов не видно.
