### ISSUE TITLE
2gis ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2966]
**Description**:
https://play.google.com/store/apps/details?id=ru.dublgis.dgismobile&utm_source=2gisru&utm_medium=link&utm_campaign=android

Город Красноярск. Нажимаем на любое здание, снизу вытягиваем шторку(
подробная информация об организациях) и там реклама. Прилагаю скриншот.

Можно убрать?

Screenshot:
<details>
![img_20160909_123705](https://cloud.githubusercontent.com/assets/18548949/18408510/5468dc18-773a-11e6-8c70-652e2d521c56.JPG)

</details>

**Adguard version**: 2.7

**Filters list**: 1,2,3,4,11,14

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Она в базу встроена, как в десктопной версиию
