### ISSUE TITLE
batzbatz.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2967]
**Description**:
http://batzbatz.com/
При нажатии в любом месте на сайте, к примеру, красная область, открывается другой сайт.

Screenshot:
<details>
![screenshot_34](https://cloud.githubusercontent.com/assets/18548949/18409481/c82f1c1e-7750-11e6-9e58-170b1a112ab6.jpg)
</details>

**Filters list**: 1,2,3,4,14

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Уже исправлено.
