### ISSUE TITLE
http://putlocker.is/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2968]
**Description**:
http://putlocker.is/watch-how-i-met-your-mother-tvshow-season-5-episode-20-online-free-putlocker.html

БЛокируется плеер на этом сайте при нажатии на Play Video. Помогает отключение Английского фильтра

Screenshot:

<details>
![screenshot_35](https://cloud.githubusercontent.com/assets/18548949/18410045/cc6afd98-775f-11e6-9e20-2dcf20f832b4.jpg)
![screenshot_36](https://cloud.githubusercontent.com/assets/18548949/18410046/cc6c79e8-775f-11e6-94a8-dd96eb0d7b53.jpg)

</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
