### ISSUE TITLE
viafree.dk - adblocking detected

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2970]
**Description**: http://www.viafree.dk/programmer/shows/linse-og-de-bare-bryster/saeson-1/episode-1

Reproduced with Danish IP.

Screenshot: 
<details>
![screen shot 2016-09-11 at 5 49 46 am](https://cloud.githubusercontent.com/assets/14153331/18414879/a3cb109c-77e3-11e6-8be0-4845c8928095.png)
</details>

**Filters list** <details>
![screen shot 2016-09-11 at 5 50 45 am](https://cloud.githubusercontent.com/assets/14153331/18414883/b2a67c50-77e3-11e6-8d54-5e4d1cfcfedf.png)
</details>

**Comment by Alex-302** [comment]
Added to English filter
```
@@||viafree.dk$generichide
```

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/18565274/cea56008-7b97-11e6-8229-83c804ac0ae6.png)

<details>
English filterVersion 1.0.94.50. Updated 15 september 2016 at 22:00.
Russian filterVersion 1.0.39.31. Updated 15 september 2016 at 22:00.

**Comment by Alex-302** [comment]
Can't reproduce
http://imagizer.imageshack.com/img922/2860/5RcHRo.png

**Comment by Bohdan-SUP** [comment]
Works fine for me too. We emailed the user.

**Comment by evgeniy-ADG** [comment]
Occurs with the extensions:

<details>
![screen shot 2016-09-20 at 18 13 36](https://cloud.githubusercontent.com/assets/15856304/18676353/fe9f4584-7f5d-11e6-8f33-e810857fa863.png)

English filterVersion 1.0.94.83. Updated 19 september 2016 at 00:00.
Spyware filterVersion 1.0.7.72. Updated 16 september 2016 at 22:19.
Social media filterVersion 1.0.12.74. Updated 18 september 2016 at 20:00.
Annoyances filterVersion 1.0.4.10. Updated 18 september 2016 at 20:02.
German filterVersion 1.0.27.40. Updated 19 september 2016 at 10:01.
Experimental filterVersion 1.0.26.25. Updated 12 september 2016 at 20:30.
Anti-Adblock Killer | ReekVersion 1.0.1.65. Updated 6 juli 2016 at 20:04.

**Comment by Alex-302** [comment]
Fixed.

**Comment by Ottodue** [comment]
Not working for me

**Comment by Alex-302** [comment]
@Ottodue which AdGuard version and filters?
