### ISSUE TITLE
Facebook ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2971]
**Description**:
браузере FF 48.0.1, в ленте новостей, периодически появляется
реклама.
В приватном также есть реклама. Помощник есть.

Может пригодится страница
https://yadi.sk/d/yqy6eKu8v29bj

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/18416293/072993fe-7819-11e6-9809-fcf0bb00ac7c.png)

</details>

**Adguard version**: 6.1

**Filters list**: 1,2,3

**Operating system**: Вин

**Browser**: Мозилла

**Comment by Alex-302** [comment]
Лента похоже динамически загружается. Удалённо бы глянуть.
