### ISSUE TITLE
lozamet.com.pl

### ISSUE THREAD

**Issue by kulfoon** [AdguardTeam/AdguardFilters#29710]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Breakage - some of images/banners not loading

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/43844449/50053850-e9e04c80-013b-11e9-8a94-9f6d40d42161.png)
</details><br/>

* **Expected behaviour**: 

The images/banners should load fine.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/43844449/50053854-ef3d9700-013b-11e9-82f6-6fb223360475.png)
</details><br/>

***Steps to reproduce the problem***:

Visit the website.

***System configuration***

**Filters:**

uBO default + AdGuard Annoyances filter

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 7 SP1 64bit
Browser:                               | Firefox 65.0.1 64bit (the issue doesn't appear on Opera 58 64bit)
AdGuard version:                       | uBlock Origin 1.18.4

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

Orginally reported here: https://github.com/ryanbr/fanboy-adblock/issues/811, as Fanboy's Cookie List was causing it too.

**Comment by krystian3w** [comment]
`/mod_cookiesaccept/*`
