### ISSUE TITLE
zfilm-hd.net

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#2972]
**Description**: Пропуск рекламы  в видео
http://zfilm-hd.net/107-tayny-smolvilya-vse-serii.html

Screenshot:
<details>
![screenshot_37](https://cloud.githubusercontent.com/assets/18548949/18416412/b1da3c42-781c-11e6-9045-4e321c96f1fb.jpg)

</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Опера

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Уже исправлено.
