### ISSUE TITLE
videoplayer missed AD

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#2973]
Пропускает отсчет рекламы в плеере.

http://ymka.tv/publ/zarubezhnye_teleserialy/vo_vse_tjazhkie/2-1-0-37

![2016-09-11_13-26-20](https://cloud.githubusercontent.com/assets/16462533/18416682/c6f05e98-7823-11e6-8751-c51a0c63fb70.png)

**Фильтры:**

> Пользовательский
> Английский
> Фильтр счетчиков и систем аналитики
> Экспериментальный
> Фильтр раздражителей
> Русский

**Comment by Alex-302** [comment]
Уже чисто.
