### ISSUE TITLE
pega.com

### ISSUE THREAD

**Issue by angelboy65** [AdguardTeam/AdguardFilters#29746]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Using Adguard DNS at router level and it is blocking www.pega.com website. 

[//]: # (Incorrect Blocking)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>
![image](https://user-images.githubusercontent.com/42597687/52909083-c9fdff80-3236-11e9-84a7-427398dcf3f6.png)

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | / Default / 
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@angelboy65 hi. It is blocked by the rule from EasyList. it seems this site it used for tracking on another sites.

**Comment by angelboy65** [comment]
@Alex-302 thank you very much for your reply. I am not sure how it can be tracking other website its a that is selling software for office automation. its like adobe, Microsoft or any other software company. how can we undo this rule from easylist?

**Comment by Alex-302** [comment]
@angelboy65 you can try to report them directly
https://github.com/easylist/easylist/issues

**Comment by angelboy65** [comment]
@Alex-302 thank you very much. I have submitted issue at their GitHub site. Let see what they have to say.
