### ISSUE TITLE
nytimes.com

### ISSUE THREAD

**Issue by krystian3w** [AdguardTeam/AdguardFilters#29754]
[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

```css
nytimes.com###site-content > div[class^="css-"] > div[class^="css-"] > div[class^="css-"] > div[class^="css-"]:has(div[class^="css-"] + div[class*="dfp-ad-"])
```

https://github.com/AdguardTeam/AdguardFilters/blob/f758c4ddf42522051ebd2c8e8d0c0505aeab2329/MobileFilter/sections/css_extended.txt#L5

Break mobile `AdGuard Mobile Ads filter`:

https://old.reddit.com/r/firefox/comments/ar9w0p/new_york_times_site_on_mobile_browser_with_ublock/

> Recently I noticed that, when I try to visit the New York Times' website on my android mobile browser with uBlock Origin running, I no longer see any headlines or news stories. They sometimes appear for a fraction of a second, then disappear, and the page only shows me the "Opinion" and "Lifestyle" sections. I tried contacting their help, they told me that it was a problem with a timestamped bookmark (I don't even know what that means) and cookies, and that if I cleared my cache it would be fine. But I tried that, and tried using private browsing, and the problem persists.
>
> It almost feels like the site has decided what content I "want" to see and is only showing me that. Has this happened to anyone else?

***System configuration***

**Filters:** 

[//]: # (Substitute this line with the list of your active filters, separated by commas)

AdGuard Mobile Ads filter

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 8.1
Browser:                               | Firefox 65.0.1
~~AdGuard~~ version:                       |  uBO 1.18.4
Filters enabled:                       | AdGuard Mobile Ads filter
AdGuard mode (Android only):           |  No
Filtering quality (Android only):      |  No
HTTPS filtering (Android only):        | No
Simplified filters (iOS only)          | No
AdGuard DNS:                           | None 
Stealth mode options (Windows only)    | No
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

---

@BlazDT  fyi.

**Comment by BlazDT** [comment]
Thank you for the notice, I updated rule.

**Comment by TPS** [comment]
@BlazDT, @ameshkov:

I need a little advice as to best place to file issue that NY Times is now detecting AG Android Stealth Mode (tested myself that way, article giving overview @ https://digiday.com/uk/subscription-publishers-close-loopholes-paywall-blockers-emerge/ ).

 Should it be filed as new issue or is there an appropriate issue to append/reopen, & would that be someplace here in Filters, Stealth Mode, ForAndroid, CoreLibs, &/or other repos?  I'm unsure of how that functionality is implemented/shared, & I wish not to spam a new issue incorrectly (perhaps only borrow a tangentially-related closed issue for this query). 🙇🏾‍♂️

**Comment by BlazDT** [comment]
Best to file it here since this thread is about the website.
But I cannot reproduce with Stealth Mode, it is not asking me to login/pay regarding paywall. Do you have a screenshot of the issue?

@AdamWr please check on your side.

**Comment by TPS** [comment]
Did y'all try just an article listing or a specific article?  For me it shows up solely on articles, & after a minute or so.  Try https://www.nytimes.com/2019/05/23/opinion/privacy-tech-companies.html (incidentally, the content opines antithetically to this issue! 🙃)

**Comment by BlazDT** [comment]
I tried just the one you linked and left it open for a few minutes, no paywall with Stealth module :(

**Comment by TPS** [comment]
Hrm.  Maybe I did something myself.  I'll try to track it down.

Thanks!

**Comment by TPS** [comment]
For the record, it's not happening now to me, either, but I confirmed that it's happening when I posted first yesterday & today — most recently 2 hours ago!  Maybe they've shut it down since the publicity hit?  I'll report whenever it recurs.
