### ISSUE TITLE
zfilm-hd.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2975]
**Description**: Пропуск рекламы  в видео
http://zfilm-hd.net/107-tayny-smolvilya-vse-serii.html

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/18416922/32dc36e8-782b-11e6-85cf-d1a5b15dded1.png)
</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Опера

**Comment by Alex-302** [comment]
Исправил.
Ещё в таком плеере бывает таймер сверху, вот с ним не разобрался.
