### ISSUE TITLE
besplatka.ua

### ISSUE THREAD

**Issue by PoRtvine** [AdguardTeam/AdguardFilters#29768]
Превью объявлений не загружается, нужно перейти на следующую страницу.
![default](https://user-images.githubusercontent.com/28482376/52916640-ccba2c80-32ea-11e9-937d-4f2840f53600.png)
[https://besplatka.ua/electronika-i-bitovaya-tehnika/optika/binokli/page/1](url)
AdGuard Spyware filter​
`||googletagmanager.com/gtm.js?$third-party`
uBO 1.18.5b3
win7x64
Opera|Beta

**Comment by Alex-302** [comment]
Спасибо, поправил.
