### ISSUE TITLE
facebook - recommended posts

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2976]
**Description**:
браузере FF 48.0.1, в ленте новостей, периодически появляется реклама.
В приватном также есть реклама. Помощник есть.

Может пригодится страница
https://yadi.sk/d/yqy6eKu8v29bj

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/18416927/5f407082-782b-11e6-9b9c-3011e8e4187f.png)
</details>

**Adguard version**: 6.1

**Filters list**: 1,2,3

**Operating system**: Вин

**Browser**: Мозилла

**Comment by Alex-302** [comment]
Фокс пока не умеет в расширенный CSS.

**Comment by Alex-302** [comment]
Нужно новую версию ждать, но сроков не знаю. На Дроиде и Маке тоже пока нет такой возможности.

**Comment by vgavrish** [comment]
id 1008878
MAC. Safari 10.0.1 на Sierra 10.12.1
Все реклама режется, кроме рекламных постов (suggested, sponsored)
Значок помощника отображается. Проблем с рекламой на других HTTPS-сайтах нет. 
Application version: 1.3.0
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0
ID=2 Name="English filter" Version=1.0.99.6
ID=3 Name="Spyware filter" Version=1.0.8.64
ID=4 Name="Social media filter" Version=1.0.14.7
ID=14 Name="Annoyances filter" Version=1.0.5.80
ID=10 Name="Filter for useful ads" Version=1.0.0.89
ID=1 Name="Russian filter" Version=1.0.42.5
ID=12 Name="Safari filter" Version=1.0.1.57
ID=207 Name="Adblock Warning Removal List" Version=1.0.68.23
ID=213 Name="RU AdList: BitBlock" Version=1.0.64.2
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19935468/d040f534-a122-11e6-84d4-07ce056ceff8.png)

**Comment by Alex-302** [comment]
там эти правила пока не работают. Скоро будет новая бета, можно будет проверить.
