### ISSUE TITLE
Browser hijacking pop-up

### ISSUE THREAD

**Issue by tbcam88** [AdguardTeam/AdguardFilters#2977]
https://storage.googleapis.com/microsoft-detected-windows-critical-error-call-for-ip-change/Microsoft%20Official%20Support-gb.html

I've had this one a few times... Adguard doesn't seem able to prevent it (I've tried updating filters also)

**Comment by Alex-302** [comment]
Where you got it?

**Comment by tbcam88** [comment]
Hmm, I can't find the page that caused it... I'll get back to you if I find it!


________________________________

**Comment by Alex-302** [comment]
Ok. Now I close this issue. When you will open new, fill the provided template.
