### ISSUE TITLE
borderfree.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2978]
**Description**: borderfree.com loads blank with EasyPrivacy enabled

Screenshots: <details>
![screen shot 2016-09-12 at 12 18 54 pm](https://cloud.githubusercontent.com/assets/14153331/18430922/340ba3b0-78e3-11e6-8058-7f9d54c40ce8.png)
![screen shot 2016-09-12 at 12 18 21 pm](https://cloud.githubusercontent.com/assets/14153331/18430921/3409be4c-78e3-11e6-903e-e92ba78c23f5.png)
</details>

Filters:
<details>
![screen shot 2016-09-12 at 12 20 17 pm](https://cloud.githubusercontent.com/assets/14153331/18430943/4ebb99a4-78e3-11e6-8c95-745d975eafa0.png)

</details>

**Comment by Alex-302** [comment]
Fixed by the EasyPrivacy author.
