### ISSUE TITLE
www.720pizle.com -video annoyance

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2980]
Site: http://720pizle.com/izle/dublaj/scooby-doo-and-wwe-curse-of-the-speed-demon.html/3

Screenshot: After pressing buton "Play". you will see an annoyance
![scooby-doo ve hiz yarisinin laneti izle 720p turkce dublaj izle - 720p film izle](https://cloud.githubusercontent.com/assets/19608513/18435403/04714cce-7904-11e6-882b-77e4ed557446.png)

Adguard version: 2.4.10

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Not shown.

**Comment by thislife81** [comment]
You press this play button? This shown after i press play button.

![sco](https://cloud.githubusercontent.com/assets/19608513/18613825/4fce093a-7d93-11e6-9178-6161d5b58581.jpg)

Ater this, please remove this. 

![scooby-doo ve hiz yarisinin laneti izle 720p turkce dublaj izle - 720p film izle](https://cloud.githubusercontent.com/assets/19608513/18613832/8bf93010-7d93-11e6-9863-6076b7309dd4.jpg)

**Comment by Alex-302** [comment]
> You press this play button? This shown after i press play button.

sure. It not displayed. Can it be selected by assistant?

Added to Social filter
```
720pizle.com##.film-icerik-paylas
```

**Comment by thislife81** [comment]
Assistant only lets me to block whole player.

![scooby-doo ve hiz yarisinin laneti izle 720p turkce dublaj izle - 720p film izle 1](https://cloud.githubusercontent.com/assets/19608513/18623186/65afdd6a-7e4b-11e6-937c-4c3c1f415545.jpg)

**Comment by Alex-302** [comment]
Nothing. Even with Turkish VPN.
