### ISSUE TITLE
123movies

### ISSUE THREAD

**Issue by ghajini** [AdguardTeam/AdguardFilters#29814]
URL(s) where the issue occurs-

https://123movies.mx/watch/yellowstone-season-1-19396

http://www0.123hulu.com

Describe the issue

Popup ads

Screenshot(s)

Versions

Browser/version: Firefox android 65
Adguard version: adguard browser extension  2.10.17
Settings

-adguard default settings

**Comment by Alex-302** [comment]
fixed
