### ISSUE TITLE
www.akalitefilmizle.net -share button

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2981]
Site: http://www.akalitefilmizle.net/yarin-el-cortez-2006-turkce-dublaj-izle.html

Screenshot: 
![yarin el cortez 2006 turkce dublaj izle film izle online film izle online hd film izle hd film izle 1](https://cloud.githubusercontent.com/assets/19608513/18435483/8fe8c87c-7904-11e6-9ca3-16cfcd73a41e.png)

Adguard version: 2.4.10

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Social filter
```
akalitefilmizle.net##.share
```
