### ISSUE TITLE
arasfilmizle.com -free space

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2982]
Site: http://arasfilmizle.com/45-yil-2015-filmi-turkce-dublaj-izle.html

Screenshot: 
![45 yil 2015 filmi turkce dublaj izle aras film izle](https://cloud.githubusercontent.com/assets/19608513/18435526/da9ae2ba-7904-11e6-9ee0-a5d9f08f54fa.png)

Adguard version: 2.4.10

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
It is too small.
