### ISSUE TITLE
www.altyazilifilm.org

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2983]
1) Site: http://www.altyazilifilm.org/

Screenshot: 
![altyazili film izle 720p full hd filmler online sinema izle](https://cloud.githubusercontent.com/assets/19608513/18435569/256baaf4-7905-11e6-8e07-b2f492829680.png)

2) Site: http://www.altyazilifilm.org/sihirbazlar-cetesi-2-2016-filmi-izle.html

Screenshot: Should be like in the pic. But, when you enter the site, the same video is not shown. I found out that Turkish filter causes this problem.

![sihirbazlar cetesi 2 - now you see me 2 2016 altyazili izle 720p full hd goruntu kalitesinde turkcealtyazili com](https://cloud.githubusercontent.com/assets/19608513/18436902/b3cebb8c-790b-11e6-9b1c-bddf1a72053f.png)

Adguard version: 2.4.10

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
altyazilifilm.org##.sidebar > ul > li > center > br+a:not([href^="http://www.altyazilifilm.org/"])
altyazilifilm.org##a[href^="https://goo.gl/"] > img 
altyazilifilm.org#@##reklam
altyazilifilm.org#$##konumuz { display: block!important; }

```

**Comment by thislife81** [comment]
#1. Please remove this completely
![altyazili film izle 720p full hd filmler online sinema izle](https://cloud.githubusercontent.com/assets/19608513/18516451/186c1e00-7aaa-11e6-8fc2-ee3238e0c173.jpg)

#2. Remove this
![sihirbazlar cetesi 2 - now you see me 2 2016 altyazili izle - 720p full hd goruntu kalitesinde - turkcealtyazili com](https://cloud.githubusercontent.com/assets/19608513/18516489/4d226ffa-7aaa-11e6-9360-4055b1c9f09d.jpg)

**Comment by Alex-302** [comment]
#1 - it is unnecessary, very small.

**Comment by thislife81** [comment]
Oh, then you please remove this rule from the rulelist:
altyazilifilm.org##.sidebar > ul > li > center > br+a:not([href^="http://www.altyazilifilm.org/"])

**Comment by Alex-302** [comment]
Why? There are ads.
The rule for leftovers is dangerous.
