### ISSUE TITLE
www.1cubukadam.com -ad

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#2984]
Site: http://www.1cubukadam.com/2015/10/sadece-cesur-ve-cilgin-kadinlarin-giyebilecegi-15-tshirt/sadece-cesur-ve-cilgin-kadinlarin-giyebilecegi-15-tshirt-2/

Screenshot: 
![www 1cubukadam com 2015 10 sadece-cesur-ve-cilgin-kadinlarin-giyebilecegi-15-tshirt sadece-cesur-ve-cilgin-kadinlarin-giyebilecegi-15-tshirt-2](https://cloud.githubusercontent.com/assets/19608513/18438302/cec4a9c8-7911-11e6-85d8-f3fc82594ee8.png)

Adguard version: 2.4.10

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
1cubukadam.com##.ads
1cubukadam.com#$##galleryContent { visibility: visible!important; }
```
