### ISSUE TITLE
http://www.redtube.com ad pop up problem (Android)

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardFilters#2986]
Hi.

Problem is back. I have just checked again and everytime when i open this site redtube.com in 'New incognito tab' in chrome android, first click any video then scroll down the page and now when i click any other video then pop up ads are opening.

And everytime when i clear the data and catche of chrome and open this site in normal tab then also pop up ads are opening

Alex provide a fix for this problem.

**Comment by rajatmathurs** [comment]
I have Check in uc browser. I disabled uc browser inbuilt ad blocker and use adguard and there is no   ad pop up problem. This problem is with chrome.

Please check at your end and fix this issue.

Thanks

**Comment by Alex-302** [comment]
Template is ignored again.
I can't fix your issue when I don't know Adguard config.

**Comment by Alex-302** [comment]
Try this rule:
```
#%#Object.defineProperty(window, 'init_tj_ads', { get: function() { return function() { }; } });
```

**Comment by rajatmathurs** [comment]
Alex.

This new rule is working great, now this is no pop ups ads are opening but with this new rule the search and menu button is not working at all.

Please check and provide a new rule that works well with search and menu button.

Let me know

Thanks

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/2918
