### ISSUE TITLE
http://m.xhamster.com ad pop problem (Android)

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardFilters#2987]
In Google chrome android open this site m.xhamster.com in 'New incognito tab' now when you click any video then pop up ads are opening.

Kindly fix this problem

**Comment by rajatmathurs** [comment]
I have Check in uc browser. I disabled uc browser inbuilt ad blocker and use adguard and there is no   ad pop up problem. This problem is with chrome.

Please check at your end and fix this issue.

Thanks

**Comment by Alex-302** [comment]
Template is ignored.

**Comment by rajatmathurs** [comment]
It won't happen again. Alex Please fix this problem. 

Thanks

**Comment by Alex-302** [comment]
Please open new issue and fill the template
https://github.com/AdguardTeam/AdguardFilters/issues/new
