### ISSUE TITLE
market.yandex.ru - click is blocked

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2988]
**Description**:
The problem is actual for iOS.

You can reproduce it with desktop Safari (change user agent to iphone).

![2016-09-13 17-47-00](https://cloud.githubusercontent.com/assets/5947035/18478472/119e0000-79da-11e6-9256-da70d426b992.png)

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||awaps.yandex.net^$domain=awaps.yandex.net
```
Can't find the better solution.
