### ISSUE TITLE
yandex direct with yandex pogoda

### ISSUE THREAD

**Issue by Hawkrus** [AdguardTeam/AdguardFilters#2989]
На странице [погоды яндекс](https://yandex.ru/pogoda/moscow/) появился директ, реклама появляется спустя какое-то время после открытия страницы:
![pogoda](https://cloud.githubusercontent.com/assets/19652388/18479074/3c3afc08-79dc-11e6-89b7-a96719e58df8.PNG)

**Filters list**: Русский фильтр актуальный

**Operating system**: Windows 7

**Browser**: Chrome

**Comment by Alex-302** [comment]
Чисто с разными IP. При этом я вижу как срабатывает правило.

**Comment by Hawkrus** [comment]
@Alex-302 могу так же, как в прошлый раз дать удаленное подключение.

**Comment by Alex-302** [comment]
Давай

**Comment by Hawkrus** [comment]
@Alex-302 
223 741 493
2b17yi

**Comment by Hawkrus** [comment]
@Alex-302 а можно ссылку на виндовый репозиторий?

**Comment by Alex-302** [comment]
вот сюда лучше
https://github.com/AdguardTeam/ExtendedCss/issues/
этот репозиторий посвящён расширенному CSS

**Comment by Alex-302** [comment]
Закрой здесь, когда там отпишешь, чтоб лишнее не висело.

**Comment by Hawkrus** [comment]
Проблема [создана](https://github.com/AdguardTeam/ExtendedCss/issues/14) в репозитории для Windows.

**Comment by Alex-302** [comment]
спс
