### ISSUE TITLE
Add KAD filter to the list of available filters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#2990]
**Description**:
https://github.com/azet12/KAD

Source issue:
https://github.com/AdguardTeam/AdguardForWindows/issues/1290

**Comment by Alex-302** [comment]
@mmigi 
It is in `ABP/OtherFilters/KADPrzekrety/filter.txt` now.
Don't forget about it.

**Comment by mmigi** [comment]
KAD - Przekrety filter has been added!

**Comment by ameshkov** [comment]
So we can close this issue?

**Comment by Alex-302** [comment]
Yes.
