### ISSUE TITLE
brest.btrans.by

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#2991]
**Description**: https://brest.btrans.by/
User reported on iOS, reproduced on desktop as well.
 
Screenshot: 
<details>
![screen shot 2016-09-13 at 8 38 28 pm](https://cloud.githubusercontent.com/assets/14153331/18496223/398a91c4-79f2-11e6-832c-30508c5ec79b.png)
</details>

**Filters list**:
<details>
![screen shot 2016-09-13 at 8 39 01 pm](https://cloud.githubusercontent.com/assets/14153331/18496234/4d7ea760-79f2-11e6-88a0-db230d09b0de.png)
</details>

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
@@||btrans.by/js/advert.js
```
