### ISSUE TITLE
m.xhamster.com ad pop problem in chrome 'New incognito tab' (Android)

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardFilters#2992]
**Description**: m.xhamster.com ad pop problem in chrome 'New incognito tab'

**Current behaviour**: In Google chrome android open this site m.xhamster.com in 'New incognito tab' now when you click any video then pop up ads are opening.

Screenshot:
<details>
![screenshot_20160914-182038](https://cloud.githubusercontent.com/assets/19775409/18513168/f935cb1c-7aa9-11e6-84e0-6ca0eae361c0.png)
</details>
**Expected behaviour**: when you click any video then pop up ads should not open in chrome 'New incognito tab' 

**Steps to reproduce the problem**:
-  open Google chrome 'New incognito tab'
-  now open m.xhamster.com
-  click any video, then pop up ads are opening.

**Adguard version**: 2.7

**Filters list**: 1, 2, 3, 4, 13

**Operating system**: Android 6

**Browser**: Google Chrome

**Comment by Alex-302** [comment]
Now it is good:) I will check it.

**Comment by rajatmathurs** [comment]
Alex.

Please fix this problem.

Waiting for your reply.

Thanks

**Comment by rajatmathurs** [comment]
Still waiting for the fix??

**Comment by Bohdan-SUP** [comment]
@Alex-302 please have a look here

**Comment by Alex-302** [comment]
@rajatmathurs 
please check this rule:
```
m.xhamster.com#%#Object.defineProperty(Object.prototype, 'popSeen', { get: function() { return true; } });
```

**Comment by rajatmathurs** [comment]
@Alex-302

The rule is not working, still pop up ads are opening.

**Comment by Alex-302** [comment]
@rajatmathurs what filtering algorithm are you using?

**Comment by rajatmathurs** [comment]
I am using Filters list: 1, 2, 3, 4, 13

I have just checked and ad pop are opening when you do these steps

open Google chrome 'New incognito tab'
now open m.xhamster.com
click any video, then pop up ads are opening

Please check again and fix this issue

**Comment by Alex-302** [comment]
Heh... Please make screenshots of advanced settings.

**Comment by rajatmathurs** [comment]
Here is the screenshot 

<details>
![screenshot_20160918-212729](https://cloud.githubusercontent.com/assets/19775409/18617182/654ef252-7de7-11e6-8c8b-65f58237e47a.png)


![screenshot_20160918-212745](https://cloud.githubusercontent.com/assets/19775409/18617177/4f55cdae-7de7-11e6-8f59-ee6a18892837.png)

</details>

**Comment by rajatmathurs** [comment]
Still waiting for the fix.

**Comment by rajatmathurs** [comment]
Alex.

Please check and fix this issue.

Thanks

**Comment by Alex-302** [comment]
I don't forgot about it.

**Comment by Alex-302** [comment]
I can't remove it

**Comment by rajatmathurs** [comment]
So there so no filter that works to block the ad pop ups. Oh no. Anyway thanks for trying. Well keep this topic open, may be you could fix this problem later.
