### ISSUE TITLE
m.youjizz.com ad pop problem in chrome 'New incognito tab'

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardFilters#2993]
**Description**: m.youjizz.com ad pop problem in chrome 'New incognito tab'

**Current behaviour**: In Google chrome android open this site m.youjizz.com in 'New incognito tab' now when you click any video or scroll down the page and when you click next page then pop up ads are opening.

Screenshot:
<details>
![screenshot_20160915-124204](https://cloud.githubusercontent.com/assets/19775409/18541834/41748e5e-7b45-11e6-8bbf-2dbbf6c64f8c.png)
![screenshot_20160915-124108](https://cloud.githubusercontent.com/assets/19775409/18541835/417d0b6a-7b45-11e6-9282-9b38d529eca7.png)

</details>
**Expected behaviour**: when you click any video then pop up ads should not open in chrome 'New incognito tab' 

**Steps to reproduce the problem**:

*  open Google chrome 'New incognito tab'
*  now open m.youjizz.com
*  click any video, then pop up ads are opening.

**Adguard version**: 2.7

**Filters list**: 1, 2, 3, 4, 13

**Operating system**: Android 6

**Browser**: Google Chrome

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by rajatmathurs** [comment]
Alex.

Please fix this problem.

Waiting for your reply.

Thanks

**Comment by Bohdan-SUP** [comment]
@Alex-302 could you please check this one?

**Comment by Alex-302** [comment]
Added to English filter
```
||youjizz.com/xoa/*.js
youjizz.com#%#Object.defineProperty(window, 'ExoLoader', { get: function() { return; } });
```
