### ISSUE TITLE
http://www.ran.de/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2995]
![image](https://cloud.githubusercontent.com/assets/15856304/18549947/3683c5a4-7b5a-11e6-916b-35cc40894725.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-06-21 21:37:00 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.5
ID: 49AFED65-F575-43C4-B8E1-5FEAEE80CC9D

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.15 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.61 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.50 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.3.77 Enabled=YES
ID=6 Name="German filter" Version=1.0.27.29 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.24 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.85 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.26 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.60.15 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.10 Enabled=YES

**Comment by Alex-302** [comment]
Try
```
@@||ran.de^$generichide
```
I'm not sure that will help. There are anti-adblock ads.

**Comment by Fisch231** [comment]
Solved the problem immediately.

Will report if it stays like that.

**Comment by Alex-302** [comment]
@Fisch231 
Did my rule helps you?

**Comment by Fisch231** [comment]
Helped! Tank you!

**Comment by Alex-302** [comment]
Ok, added to Safari filter.
