### ISSUE TITLE
[Extension 2.4.10] https://music.yandex.ru/feed - anti-adblocker, ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2997]
![image](https://cloud.githubusercontent.com/assets/15856304/18553384/e78f308c-7b68-11e6-91aa-88a08208c023.png)

<details>
English filterVersion 1.0.94.23. Updated 13 september 2016 at 13:00.
Russian filterVersion 1.0.39.17. Updated 12 september 2016 at 23:00.

**Comment by evgeniy-ADG** [comment]
У меня повторилось 1:1

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
music.yandex.ua,music.yandex.ru##div.smalladv.smalladv_side[-ext-has=".smalladv__item"]
```
Это скорее на будущее, т.к. с расширенным CSS есть проблемка.
По детекту - проверь такие правила:
```
@@||music.yandex.ua^$generichide
@@||an.yandex.ru/system/context.js$domain=music.yandex.ua
```
