### ISSUE TITLE
http://old.reactor.cc/ - annoyance, redirects

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#2998]
http://old.reactor.cc/tag/%25D1%2586%25D1%258B%25D0%25B3%25D0%25B0%25D0%25BD%25D0%25B5

![image](https://cloud.githubusercontent.com/assets/15856304/18553738/3b7af676-7b6a-11e6-9216-3807763cf01f.png)

Редирект срабатывает при клике на по фону (желто-оранжевые поля по бокам), либо при открытии комментария, вкладки-спойлера (скрывает слишком длинные посты) или же по основным вкладкам в шапке сайта.

<details>

Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:8 Name: Dutch filter Url: http://adguard.com/ru/filter-rules.html?id=8
FilterId:105 Name: EasyList Czech and Slovak Url: https://raw.github.com/tomasko126/easylistczechandslovak/master/filters.txt
FilterId:111 Name: Latvian List Url: https://notabug.org/latvian-list/adblock-latvian/raw/master/lists/latvian-list.txt
FilterId:200 Name: ABP Japanese Filters Url: https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abpjf.txt
</details>
1072148

**Comment by Alex-302** [comment]
`FilterId:200 Name: ABP Japanese `
сразу в топку
Лучше пусть выключит автоматическое подключение фильтров.

**Comment by Alex-302** [comment]
Вроде пока работает решение.
