### ISSUE TITLE
http://wikianime.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3000]
Пропущена реклама на сайте: http://wikianime.ru/anime/re_zero_kara_hajimeru_isekai_seikatsu/schedule
Скриншот: http://f1.s.qip.ru/OgbqisIh.png

Мои параметры:
* Win x64
* adguard в виде расширения у Chrome
* фильтры: русский, английский, RU AdList
* Dr.Web

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||ts.wikianime.ru^

```
