### ISSUE TITLE
mobile.twitter.com - app download bar

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#30008]
`https://mobile.twitter.com/gorhill`

"Get the most out of Twitter" annoyance on mobile devices:

![twitter](https://user-images.githubusercontent.com/35470489/53241415-633a7500-3680-11e9-8b7c-8f1a0a5c306b.png)

Adguard Base + Mobile Ads filter + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.4
Firefox 65

**Comment by Alex-302** [comment]
Their HTML is obfuscated.
