### ISSUE TITLE
http://sexs-foto.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3001]
http://sexs-foto.com/znamenitosti/6384-golaya-emiliya-klark-21-foto.html

![image](https://cloud.githubusercontent.com/assets/15856304/18562943/6084f3d0-7b8e-11e6-96c3-e01868248830.png)

* Win x64
* adguard в виде расширения у Chrome
* фильтры: русский, английский, RU AdList
* Dr.Web

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||dvanaro.ru^$third-party
```
