### ISSUE TITLE
ivoox.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#30026]
`https://br.ivoox.com/pt/podcast-vuelta-al-mundo-en-80-musicas_sq_f1896_1.html`

Bottom cookie notice.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.4
Firefox 65

**Comment by krystian3w** [comment]
`###cookies_message`

**Comment by Alex-302** [comment]
It is hidden by Annoyances filter.

**Comment by krystian3w** [comment]
Generic hide in ublock lists?

**Comment by adranger** [comment]
Sorry, @krystian3w  is right (https://github.com/uBlockOrigin/uAssets/commit/dbde782bf49d838c85fb40798a2a01f23febfd8d#commitcomment-32461807).

**Comment by krystian3w** [comment]
Bad situation...
