### ISSUE TITLE
http://www.idownloadblog.com/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3002]
Incorrect blocking on page:
http://www.idownloadblog.com/

![image](https://cloud.githubusercontent.com/assets/15856304/18563095/02088708-7b8f-11e6-822c-1f61f4204e85.png)

<details>

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.3 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.61 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.29 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.3.70 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.89 Enabled=NO
ID=5 Name="Experimental filter" Version=1.0.26.24 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.85 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.24 Enabled=YES
ID=101 Name="EasyList" Version=1.0.62.49 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.65.9 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.65.40 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.9 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.65.23 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
ID=220 Name="CJX's Annoyance List" Version=1.0.0.62 Enabled=YES
ID=229 Name="I dont care about cookies" Version=1.0.0.3 Enabled=YES
ID=204 Name="Peter Lowe's list" Version=1.0.2.30 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.59 Enabled=YES
ID=228 Name="xinggsf" Version=1.0.0.58 Enabled=YES

**Comment by Alex-302** [comment]
Не повтоярется, без Адгарда. Можешь с юзерагентом попробовать повторить?

**Comment by evgeniy-ADG** [comment]
No, I can't reproduce it now.

But could you please check if we can remove the blank space under the header?

<details>
![screen shot 2016-09-21 at 8 10 19 pm](https://cloud.githubusercontent.com/assets/15856304/18721160/e269f6d6-8037-11e6-81db-616f20a23a89.png)

Application version: 1.0.8.54
Application lifetime: 2016-09-14 01:55:35 +0000

Device: iPhone
Platform: iPhone OS
OS: 10.0.1
ID: BF8A3724-A807-4FCC-BF58-44E6F5D807AA

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.91 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.73 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.78 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.31 Enabled=YES

**Comment by Alex-302** [comment]
Added to Mobile filter
```
idownloadblog.com##.wptouch-custom-ad
```
