### ISSUE TITLE
http://macys.com/

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3003]
**Incorrect blocking on page**

```
English filter
Spyware filter
Annoyances filter
Russian filter
Experimental filter
Safari filter
```

![img_1177](https://cloud.githubusercontent.com/assets/16462533/18565313/021fac5e-7b98-11e6-9381-9a9546552b83.PNG)

![img_1178](https://cloud.githubusercontent.com/assets/16462533/18565321/080f138e-7b98-11e6-89c5-73756fff21ca.PNG)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||assets.macys.com/dyn_img/site_ads/
```
