### ISSUE TITLE
nakedsecurity.sophos.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#30052]
**Site Sample** | 
----------------|
https://nakedsecurity.sophos.com/2018/03/20/nine-years-on-firefoxs-master-password-is-still-insecure/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Mozilla Firefox Quantum x64
AdGuard version:                       | **6.4.1840.4955**
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
| **Filters enabled**
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| EasyList Polish 
| Fanboy's Annoyances 
| Fanboy's Cookiemonster List
| Fanboy's Enhanced Tracking List 
| Fanboy's Social Blocking List 
| KAD - fraud/scam 
| Malware Domains
| NoCoin Filter List 
| Peter Lowe's List
| Polish Annoyances
| Polish Anti Adblock Filters
| Polish Cookies
| Polish Main
| Polish Social
| Spam404

### Issue:

Ad

<details><summary><b>Screenshot:</b></summary>

![scr-1550918296-001](https://user-images.githubusercontent.com/9846948/53285380-e54d9b00-375f-11e9-885b-ea4be99ae7d1.png)

</details><br/>

@AdamWr

**Comment by Alex-302** [comment]
Self-promo. Fixed in annoyances.
