### ISSUE TITLE
stileproject.com [Ads] [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#30054]
**Site**: https://www.stileproject.com/video/blonde-cheating-husband-with-anal-fuck-7814744.html?utm_source=pbweb

**Issue**: Please remove the Ads

**Screenshot**: http://prntscr.com/mp0r7b

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 72.0.3626.81 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Nzzyme** [comment]
https://www.stileproject.com/video/blonde-cheating-husband-with-anal-fuck-7814744.html

Ad banner seen over the video player. Please check

**Comment by AdamWr** [comment]
Fixed.

**Comment by Nzzyme** [comment]
https://www.stileproject.com/video/boom-asian-milf-fucked-8281.html

Ad banner seen on the player.

https://i.imgur.com/QcQ5Zos.png

**Comment by AdamWr** [comment]
Fixed.
