### ISSUE TITLE
yourcinema.tv

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3006]
**Description**: http://yourcinema.tv/serial/360-igra-prestolov-3-sezon-1-10-seriya-lostfilm.html

Screenshot: 
<details>
![screenshot_20160916-141304](https://cloud.githubusercontent.com/assets/14153331/18584369/01d20694-7c19-11e6-8816-5f8e4724232b.png)
</details>

**Adguard version**: 2.7.220

**Filters list**:  2, 3, 4, 14, 1, 11

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
yourcinema.tv$$script[tag-content="var et_ws"][max-length="800"]
```
Алгоритм фильтрации должен быть качественный.
