### ISSUE TITLE
Root Browser ads

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3007]
**Description**:

https://play.google.com/store/apps/details?id=com.jrummy.root.browserfree

Screenshot:
<details>
![screenshot 04-52pm 14 2016](https://cloud.githubusercontent.com/assets/14153331/18584730/60d33e0e-7c1b-11e6-86ea-43f1c0682f59.jpg)
</details>

Logs - https://gist.github.com/Bohdan-SUP/69549d4348c160a9464725b97faa84df

**Comment by Alex-302** [comment]
@Bohdan-SUP there are over 3000 strings. And no state.txt.
What filtering mode is used?
