### ISSUE TITLE
buzzfeednews.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#30083]
`https://www.buzzfeednews.com/article/carolineodonovan/youtube-just-demonetized-anti-vax-channels`

Newsletter annoyance appears while scrolling down.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.4
Firefox 65

**Comment by Alex-302** [comment]
Please add screenshot.

**Comment by adranger** [comment]
@Alex-302 

![screenshot](https://user-images.githubusercontent.com/35470489/53598620-fcd3bc00-3b83-11e9-8420-7ff6e3ccdbbc.png)


I've found this in my log: 

`https://abeagle-public.buzzfeed.com/public/v2/experiment_variants?experiment_names=bfn_support_text;bfn_newsletter_popup;bfn_recirc_popup;ad_exchange_vox_concert;ads_inline_density_bfnews;ad_display_card_sticky;moat_dfp_native_video_tracking;advertise_international;non_us_ad_lookahead_adjustments;ADSGROUP-408_bouncex_bpager;ADSGROUP-442-permutive;ADSGROUP-143_new_ad_calls_structure;ADSGROUP-655-prefetch;ADSGROUP-699-outbrain-redux;ADSGROUP-747-ad-lightning&user_id=2152540449&client_id=buzz_web`

Adding `buzzfeed.com/public/v2/experiment` stops it.

**Comment by Alex-302** [comment]
ok, fixed in Annoyances.
