### ISSUE TITLE
https://yandex.ru/ - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3008]
Пропущена реклама на странице:
https://yandex.ru/search/touch/?clid=1906591&text=oneplus%203%20ifixit&lr=213

При любом запросе в яндексе появляется вот такая реклама снизу:
![image](https://cloud.githubusercontent.com/assets/15856304/18593711/6af298ec-7c45-11e6-8325-79f961857192.png)
<details>
Application version: 1.0.8.54
Application lifetime: 2016-07-20 17:41:45 +0000

Device: iPhone
Platform: iPhone OS
OS: 10.0.1
ID: 51F4DA51-4E3D-4EC6-9DAC-9494412596AA

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.49 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.76 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.11 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.3.99 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.39.30 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.87 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.27 Enabled=YES

</details>
Обновил, реклама яндекса как была так и осталась. Она убирается таким фильтром:
yandex.ru##DIV.page-layout.i-bem.page-layout_js_inited:nth-child(AAA) > DIV.page-layout__content > DIV.footer.footer_type_distro.clearfix.flex-none.i-bem.footer_js_inited:last-child > DIV.footer__inner ,
где вместо ААА - различные цифры. Т.е. нужно составить универсальное правило.

**Comment by Alex-302** [comment]
Добавил в фильтр раздражителей
```
yandex.ru,yandex.by,yandex.ua##a.scroll-spy_js_inited
```
