### ISSUE TITLE
https://lotzon.com/blog

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3009]
https://lotzon.com/blog

![image](https://cloud.githubusercontent.com/assets/15856304/18595047/9ca66534-7c4b-11e6-97b4-dd3900cf5901.png)

Фильтры:
Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
lotzon.com##div[id^="bn_"]
lotzon.com##div[id^="banner-"]
@@||lotzon.com$generichide

```
