### ISSUE TITLE
vsetv.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3011]
**Description**:
http://vsetv.net/ctc-love.html

Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/18606719/868aa402-7cc0-11e6-88d2-c56f09358e0c.png)
</details>

**Filters list**:
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/18606727/b98f8412-7cc0-11e6-9f3f-3d99aa4a65e1.png)
</details>

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||vsetv.net/advert.js
```
