### ISSUE TITLE
deezer.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#30110]
`https://www.deezer.com/`

"Trending searches" annoyance when you click on the search bar while logged in. It keeps showing pop artists even if you never listen to pop. 

`deezer.com##.search-category:nth-child(2)`

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.4
Firefox 65

**Comment by Alex-302** [comment]
not reproduced

**Comment by adranger** [comment]
@Alex-302 it seems they've changed the code but I still get the recommendations when I click on the search bar:

![trending searches](https://user-images.githubusercontent.com/35470489/54782841-9714a600-4bfe-11e9-8daa-a065084316cd.png)
