### ISSUE TITLE
https://www.welt.de/wirtschaft/article158193297/Das-wuetende-Amerika-riskiert-eine-neue-Bankenkrise.html

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3012]
Ads in video after 5-10 seconds watching
![1](https://cloud.githubusercontent.com/assets/20476168/18608053/09e7a450-7ce7-11e6-8208-d10e1fd3b8cc.PNG)
![2](https://cloud.githubusercontent.com/assets/20476168/18608054/09ee2910-7ce7-11e6-832e-81a2c5dbfa4c.PNG)

Windows 10 
Chrome 

Screen
![bug](https://cloud.githubusercontent.com/assets/20476168/18608059/1c3988a8-7ce7-11e6-9627-483694a96d7f.png)

**Comment by Alex-302** [comment]
Added to German filter
```
||damoh.welt.de^$replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/
||smartadserver.com/ac?siteid=$replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/
||welt.de/homadConfigEnabled$replace=/"enabled":[\s\S]*true\,/"enabled": false\,/i
||svonm.com/www.welt.de/config.json$replace=/"enabled":[\s\S]*true\,/"enabled": false\,/i
||s3.amazonaws.com/homad-global-configs.schneevonmorgen.com/global_config.json$replace=/"enabled":[\s\S]*true\,/"enabled": false\,/i

```
