### ISSUE TITLE
pilot.wp.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#30126]
**Site Sample** | 
----------------|
https://pilot.wp.pl/tv

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Mozilla Firefox Quantum x64
AdGuard version:                       | **6.4.1814.4903 [STABLE]** 
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
| **Filters enabled**
| Adguard Annoyances 
| Adguard English
| Adguard Social
| Adguard Spy 
| AlleBlock
| EasyList Polish 
| Fanboy's Annoyances 
| Fanboy's Cookiemonster List
| Fanboy's Enhanced Tracking List 
| Fanboy's Social Blocking List 
| KAD - fraud/scam 
| Malware Domains
| NoCoin Filter List 
| Peter Lowe's List
| Polish Annoyances
| Polish Anti Adblock Filters
| Polish Cookies
| Polish Main
| Polish Social
| Spam404

### Issue:

Unable play conent - buttons on right slider inactive.

@AdamWr

**Comment by AdamWr** [comment]
Niestety nie potrafię tego odtworzyć.
Jak wyłączysz "Stealth Mode" to działa prawidłowo?
Jeśli nie, to czy mógłbyś proszę wyłączyć jedną listę po drugiej i sprawdzić, która lista powoduje ten problem?

**Comment by FadeMind** [comment]
@AdamWr NIE mam pojęcia o co chodzi, ale po restarcie systemu wszystko wróciło do normy. Dzień świra normalnie. Zamykam.

**Comment by AdamWr** [comment]
Ok, dziękuję za odpowiedź :)
