### ISSUE TITLE
https://ru.aliexpress.com - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3013]
![image](https://cloud.githubusercontent.com/assets/15856304/18608596/746a19ac-7cf6-11e6-918c-f653c6af7240.png)

<details>
russian, annoyances, s. media, eng

**Comment by Alex-302** [comment]
Добавил в фильтр раздражителей
```
aliexpress.com##body > div.ui-mask
aliexpress.com##.ui-newuser-layer

```

**Comment by evgeniy-ADG** [comment]
Снова вылезло что-то
https://ru.aliexpress.com/ru_home.htm

![image](https://cloud.githubusercontent.com/assets/15856304/19717582/047559a8-9b6a-11e6-8916-7ab280616974.png)

**Comment by Alex-302** [comment]
Да там бесполезно скрывать, каждый день что-то новое.

**Comment by evgeniy-ADG** [comment]
Ок, так и отвечу.
