### ISSUE TITLE
http://ru.investing.com/ - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3014]
http://ru.investing.com/economic-calendar/

Настройки при установке в основном были
оставлены по умолчанию. По мимо блокировки рекламы, так же блокируется
автоматическое обновление индексов в момент их публикации (обведено красным
на принтскрине, то есть в 00:00 должно было автоматически появиться
значение 52,3 для валюты CAD по индексу деловой активности), если отключить
Adguard и обновить страницу, значения индексов обновляются в корректном
режиме. Подскажите, пожалуйста, можно ли что-нибудь изменить в настройках
программы, что бы реклама продолжила блокироваться, а индексы стали
обновляться автоматически?

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/18608653/f84af006-7cf7-11e6-9359-4fd19d87c3a6.png)

AppVersion: 6.1.258.1302
Main settings: 
Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Wfp

**Comment by Alex-302** [comment]
А с каким интервалом они обновляются?

**Comment by evgeniy-ADG** [comment]
Узанем. Есть такое:

>только что проверил все.. проблема кроется в Английском фильтре.. после его
удаления, сайт открывается нормально, но адгард подключает английский
фильтр автоматически и все, больше меню и обновление не работает! что
делать?

**Comment by evgeniy-ADG** [comment]
День добрый! на данном сайте при
блокировке некликабельно меню и нет
обновления цены с графиком..
http://ru.investing.com/commodities/brent-oil

только что проверил все.. проблема кроется в Английском фильтре.. после его
удаления, сайт открывается нормально, но адгард подключает английский
фильтр автоматически и все, больше меню и обновление не работает! что
делать? отключить английский фильтр навсегда? =)

тикет 1151145
<details>
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:116 Name: Wiltteri Url: https://raw.githubusercontent.com/wiltteri/wiltteri.txt/master/wiltteri.txt
FilterId:120 Name: Norsk adblockliste Url: http://home.fredfiber.no/langsholt/adblock.txt
FilterId:216 Name: Adblock polskie reguły Url: http://www.certyficate.it/adblock/adblock.txt

**Comment by Alex-302** [comment]
> блокировке некликабельно меню

какое? Скрин нужен.

**Comment by Serzh-SUP** [comment]
Внесу немного ясность. Проблема действительно существует, во всяком случае у меня также проявилась. На скрине, меню выделено в красную рамку. Проблема с браузерами Опера и ФФ. Например, в Хроме такой проблемы нет.

Скрин: 
![2016-09-28 2](https://cloud.githubusercontent.com/assets/16462533/18903496/3a79f824-8562-11e6-868c-9c949955e693.png)

**Мои фильтры:**
> Пользовательский
> Английский
> Фильтр счетчиков и систем аналитики
> Экспериментальный
> Фильтр раздражителей
> Русский

**Comment by Alex-302** [comment]
Всё равно не повторяется. Доступ нужен.

**Comment by Serzh-SUP** [comment]
@Alex-302 
Ждем от пользователя решение на доступ.
