### ISSUE TITLE
gizmodo.com - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3015]
Gizmodo.com (and its sister sites): the 'previous page' swipe doesn't work, I'm stuck on the page.
After whitelisting the page works again. 

<details>
Application version: 1.0.8.54
Application lifetime: 2016-09-16 10:09:05 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.5
ID: AE8E313E-6D2C-4F98-A1D4-1B4279061B06

Locale: nl
Region: nl

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.60 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.72 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.68 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.4.3 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.8.98 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.27 Enabled=YES
</details>
1413592

**Comment by Alex-302** [comment]
> Gizmodo.com (and its sister sites):

ask him for the full list of these sites.






> the 'previous page' swipe doesn't work

I don't know how it looks on iphone. Is it possible to show it on screenshot?
