### ISSUE TITLE
http://megapeer.org/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3017]
![image](https://cloud.githubusercontent.com/assets/15856304/18609326/16a5590a-7d08-11e6-8692-539674094737.png)

Just click on any movie and you'll see a popup
<details>
rus, eng

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||megapeer.org/c/*.js
```

**Comment by vgavrish** [comment]
1050245
Расширение. Вин
тоже самое, когда нажимаешь на фильм, открывается другой сайт. Яндекс.
Фильтр счетчиков и системы аналитики
Фильтр раздражителей
Фильтр виджетов социальных сетей
Английский фильтр
Русский фильтр
Эксперементальный фильтр.

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||megapeer.org^$generichide
@@.adframesrc.$domain=megapeer.org
```
