### ISSUE TITLE
tukero.org - active RSS

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#30176]
Hello, 
I longer time see RSS button over chat on tukero.org like is on that screen:
![tukero](https://user-images.githubusercontent.com/16944478/53413671-e0415380-39cc-11e9-8f51-88016a751227.png)

I reported on polish filters team in that issue: https://github.com/MajkiIT/polish-ads-filter/issues/12257
and I have only information about tukero isn't polish. Only one person added rule, what fix my problem: 
tukero.org##.clearfix.widget-content

And my question. It is possible adding that rule ( tukero.org##.clearfix.widget-content ) to some filter which blocks frustrated elements or I don't know?

Best Regards

**Comment by Alex-302** [comment]
Blocked as social widget leftover.
