### ISSUE TITLE
MentalFloss.com - Broken function (AdGuard Annoyances filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#30190]
### Affected site:
`https://mentalfloss.com/`

### Issue:
The "**MENU**" button (in the top right corner) doesn't work!
(GDPR related)

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* AdGuard Annoyances filter

### Problem rule:
`||consensu.org^$third-party`

### Blocked script:
`https://cdn.conversant.mgr.consensu.org/gdpr/cmp/config/m/e/mentalfloss.com/config.js`

### Possible fix:
`@@||consensu.org^$third-party,domain=mentalfloss.com`

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.4.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.8 (XUL)

**Comment by Alex-302** [comment]
fixed
