### ISSUE TITLE
www.durdurfilmizle.com -share button

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#3019]
Site: http://www.durdurfilmizle.com/dag-adamlari-turkce-dublaj-izle.html

Screenshot: https://s4.postimg.org/61i6jwkdp/image.jpg

Adguard version: 2.4.13

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Social filter
```
durdurfilmizle.com##.sosyal
```
