### ISSUE TITLE
filmkomedi.com -annoyances

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#3020]
Site: http://filmkomedi.com/category/yerli-filmler/
Screenshot: 

![filmkomedi](https://cloud.githubusercontent.com/assets/19608513/18614132/de0d0592-7d99-11e6-853e-4850da12a827.jpg)

2) Wait 10 seconds after enter the site

![filmkomedi2](https://cloud.githubusercontent.com/assets/19608513/18614133/e4ed8a3a-7d99-11e6-915f-d5e16e4ff96d.jpg)

2.Site: http://filmkomedi.com/category/yerli-filmler/
Screenshot: 
![donerse senindir izle](https://cloud.githubusercontent.com/assets/19608513/18614144/37f5a780-7d9a-11e6-8ee2-cb95e7c80468.jpg)

Adguard version: 2.4.13

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
filmkomedi.com###filmoncereklam
filmkomedi.com#$##film { display: block!important; }
filmkomedi.com##.dialog-social
filmkomedi.com###.footer > div.footeright

```

**Comment by thislife81** [comment]
Please remove this: http://filmkomedi.com/masal-izle/

![masal izle](https://cloud.githubusercontent.com/assets/19608513/18622846/299902c0-7e46-11e6-9677-976c66100ddc.jpg)

**Comment by Alex-302** [comment]
Fixed.
