### ISSUE TITLE
www.filmexpresi.com -skip ad

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#3021]
Site: http://www.filmexpresi.com/kali-izle-tek-parca.html

Screenshot: https://s21.postimg.org/dn4mgzsl3/FILMEXPRESI.jpg

Adguard version: 2.4.13

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
filmexpresi.com#$##film { display: block!important; }
filmexpresi.com###filmoncereklam

```
