### ISSUE TITLE
www.filmizle.film -share button

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#3022]
Site: http://www.filmizle.film/special-correspondents-izle.html

Screenshot: https://s14.postimg.org/r6d7439fl/filmizle.jpg

Adguard version: 2.4.13

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Fixed
