### ISSUE TITLE
m.spankbang.com ads pop up problem

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardFilters#3023]
Hi.

I am using adguard 2.7, Filters list: 1, 2, 3, 4, 13 with Android 6. Open this site http://m.spankbang.com  in chrome 'New incognito tab'. Now click on any video, then when you click to play the video or click to change the quality to high, medium, low then  pop up ads are opening.

screenshots
<details>
![screenshot_20160918-143937](https://cloud.githubusercontent.com/assets/19775409/18614665/b8e88de2-7db0-11e6-94e3-4856b866ad32.png)
</details>

Please check and fix this issue.

**Comment by Alex-302** [comment]
Can't open it.

**Comment by rajatmathurs** [comment]
I had just checked and ad pop are still opening when you do these steps
Open this site http://m.spankbang.com in chrome 'New incognito tab'. Now click on any video, then when you click to play the video the ads are opening 

or click to change the quality to high, medium, low then pop up ads are opening.

Please check again and fix this issue

**Comment by rajatmathurs** [comment]
Anyone help me with the fix?

**Comment by Bohdan-SUP** [comment]
@Alex-302 please check it. Reproduced on my side.

**Comment by Alex-302** [comment]
Added to Mobile filter
```
m.spankbang.com#%#Object.defineProperty(window, 'launchRpuLink', { get: function() { return; } });
```

**Comment by rajatmathurs** [comment]
Hi.

Thanks now ad pop is not opening, but now the menu and search is not
working at all, they are not clickable anymore. Earliear they were working.

Please check and fix menu and search so that when I click then it should
work.

Waiting for the fix

Added to Mobile filter

m.spankbang.com#%#Object.defineProperty(window, 'launchRpuLink', {
get: function() { return; } });

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AdguardTeam/AdguardFilters/issues/3023#issuecomment-248224457>,
or mute the thread

**Comment by Alex-302** [comment]
thanks, replaced bt
```
m.spankbang.com#%#AG_onLoad(function() { rpuSetCookie('true', '1000'); });
```

**Comment by rajatmathurs** [comment]
I had added the new rule filter in user filter and the menu and search is still not working at all, they are not clickable.

Please check again.

**Comment by Alex-302** [comment]
You need update your filters. And remove that rules from custom filter.

**Comment by rajatmathurs** [comment]
Hey updated adguard, now it's working great.

Thanks a lot
