### ISSUE TITLE
woman.ru Social Widget is blocked problem

### ISSUE THREAD

**Issue by MikhailRokhin** [AdguardTeam/AdguardFilters#30253]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: [The ISSUE was closed](https://github.com/AdguardTeam/AdguardFilters/issues/28193) , but wasn't solved. Still  AdGuard Spyware filter blocks social widget at [woman.ru](http://www.woman.ru/stars/life/article/226161/)
* **Current behaviour**: AdGuard Spyware filter blocks social widget

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/16386541/53552507-810a4d00-3b4c-11e9-9fc7-1472a1d31a81.png)

</details><br/>

* **Expected behaviour**: AdGuard Spyware filter should be updated to stop blocking the social widget.

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/16386541/53552459-6932c900-3b4c-11e9-90bd-3dd713bb2335.png)

</details><br/>

***Steps to reproduce the problem***: 

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**
AdGuard Spyware filter 

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Reproduced, fixed. You can reply in your closed issues, instead of creating new issues.

**Comment by MikhailRokhin** [comment]
> Reproduced, fixed. You can reply in your closed issues, instead of creating new issues.

Thank you for quick fix and thank you for development!)
