### ISSUE TITLE
http://m.ndtv.com/video/live - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3025]
http://m.ndtv.com/video/live

![image](https://cloud.githubusercontent.com/assets/15856304/18616270/5d0c1d48-7dc1-11e6-9e8d-7298c2c21d15.png)

<details>
enabledFilterIds" : [ 2, 3, 4, 14, 11, 211 ],

**Comment by Alex-302** [comment]
Added to Mobile filter
```
m.ndtv.com#@#.ad300
m.ndtv.com#%#Object.defineProperty(window, 'canRunAdsN', { get: function() { return false; } }); 

```
