### ISSUE TITLE
Avtosfer.Az -Banners and Free spaces

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#3026]
Site: http://avtosfer.az/news/25150

Screenshots: 

@1
![avto1](https://cloud.githubusercontent.com/assets/19608513/18623227/d0abbdfa-7e4b-11e6-8d67-637d1eac3974.jpg)

@2
![avto2](https://cloud.githubusercontent.com/assets/19608513/18623230/dd92257c-7e4b-11e6-83b7-b6b47f05130d.jpg)

@3
![avto3](https://cloud.githubusercontent.com/assets/19608513/18623234/eb7bf6ae-7e4b-11e6-912b-e2b5dba2546c.jpg)

@4
![avto4](https://cloud.githubusercontent.com/assets/19608513/18623251/11ffc792-7e4c-11e6-9dee-1244b386d2c9.jpg)

Adguard version: 2.4.13

Operating system: Windows 10

Browser: Google Chrome

Filter list: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to English filter
```
||avtosfer.az/banner*_
avtosfer.az##div[style$="width:240px;min-height:160px;"]
avtosfer.az##.SC_TBlock
||criminal.az/avtosfer.html
avtosfer.az##iframe[src^="http://avtosfer.az/banner"]
avtosfer.az##div[style$="width:240px;min-height:300px;"]
||avtosfer.az/banner240x
avtosfer.az##div[class^="bannerArea"]
||avtosfer.az/banners/

```
