### ISSUE TITLE
thefappening.so

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3027]
**Description**:
http://thefappening.so/

Screenshot: use the following code
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/18625820/b0184852-7e59-11e6-8417-a291811e9ee4.png)
</details>

Filters: русский, английский, RU AdList.

**Comment by Alex-302** [comment]
Added to English filter
```
||thefappening.so/sproject/*.php
thefappening.so##iframe[src^="/icloud"]

```
