### ISSUE TITLE
amiro.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3028]
После последних обновлений в этом месяце плагин стал блокировать всплывающие элементы в админке сайта от amiro cms ( amiro.ru ).
Нельзя добавить фото к товару, новости и т.д., т.е. там где есть всплывающий iframe отображается пустота. 
Добавление сайта в исключение проблему не решает. А вот если выполнить "Приостановить защиту Adguard", то проблема исчезает. В Яндекс браузере требуется полное отключение надстройки. В настройках плагина пробовал поотключать почти все, но и это не помогло.
Тестировал в последних версиях браузеров Chrome и Яндекс.
Воспроизвести проблему можно на демо стенде любой из редакций amiro: http://demo.amiro.ru/_admin/702.0/start.php?lang=&lang_data=

<details>
тветы на опросник ниже. Хочу обратить ваше внимание, что добавление сайта в белый список не помогает, также не везде срабатывает "Приостановить защиту Adguard" и приходится выключать плагин через список надстроек, а далее перезапускать браузер. Пробовал останавливать защиту антивируса и выгружать его из системы - не влияет вообще.
Также пробовал выключать все фильтры в настройках плагина (Антибаннер и Антифишинг) + сайт в белом списке - не влияет на результат.
Разработчики движка также тестировали эту ситуацию, проблема именно в плагине.
Такая ситуация ни у одного меня, имеется действующий интернет-магазин на этом движке и контент-менеджеры (ОС и антивирусы разные, браузер один, наличие плагина не у всех), у некоторых менеджеров плагин отсутствует и все прекрасно работает.
1. Версия ОС: Win 10 Pro
2. Версия Adguard: 2.4.10
3. Браузер: Google Chrome 53.0.2785.116 m
4. Анти-вирус: Kaspersky Internet Security 16.0.1.445 (e)
5. Фильтры: 
   Основные настройки
   Разрешить полезную рекламуУзнать об этом подробнее - ДА
   Показывать количество заблокированной рекламы на иконке Adguard - ДА
   Автоматически подключать наиболее подходящие фильтры - ДА

Антибаннер Количество правил фильтрации: 89576
Английский фильтрВерсия 1.0.94.27. Обновлено 13 сентября 2016 в 17:00. - ДА
Фильтр счетчиков и системы аналитикиВерсия 1.0.7.62. Обновлено 12 сентября 2016 в 19:00. - ДА
Фильтр виджетов социальных сетейВерсия 1.0.12.52. Обновлено 13 сентября 2016 в 16:00. - ДА
Русский фильтрВерсия 1.0.39.19. Обновлено 13 сентября 2016 в 17:00. - ДА
Немецкий фильтрВерсия 1.0.27.32. Обновлено 13 сентября 2016 в 16:01. - ДА
Adblock PolskaВерсия 1.0.0.52. Обновлено 23 ноября 2014 в 09:02. - ДА

Антифишинг
Защита от фишинговых и вредоносных сайтовУзнать об этом подробнее - ДА
Помогать в развитии антифишингаОтправлять анонимную статистику о подозрительных сайтах - ДА
Белый список
Adguard не работает на сайтах, добавленных в белый список.
Инвертировать белый списокРазблокировать рекламу везде, кроме белого списка
ПОИСК ПО БЕЛОМУ СПИСКУ 
Введите строку поиска
business.amiro.ru

Разное
Использовать оптимизированные фильтрыСписки фильтров, оптимизированных для мобильных устройств - НЕТ
Отправлять статистику использования фильтровУзнать об этом подробнее - НЕТ
Добавить Adguard в контекстное меню браузера - ДА
Показывать информацию о полной версии Adguard - НЕТ
</details>

ticket id 1412220

**Comment by Alex-302** [comment]
Уже есть 2.4.13. Можно с ней проверить.

Я войти не могу, там авторизоваться нужно. Попроси тесктовый акк.
