### ISSUE TITLE
http://www.extragold.nl/ - Assistant doesn't appear on the page

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3029]
![screen shot 2016-09-19 at 9 58 55 pm](https://cloud.githubusercontent.com/assets/15856304/18645050/5f8b6792-7eb4-11e6-8cff-7e5cfd74382a.png)

<details>
![screen shot 2016-09-19 at 10 00 07 pm](https://cloud.githubusercontent.com/assets/15856304/18645077/74ab1a32-7eb4-11e6-960a-f3d38cbfd959.png)

**Comment by Alex-302** [comment]
Because it is based on frame set.
