### ISSUE TITLE
http://www.calciomercato.com/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3030]
http://www.calciomercato.com/news/londra-chiude-il-mitologico-locale-fabric-club-ma-il-calcio-non--279065

![screen shot 2016-09-19 at 11 48 28 pm](https://cloud.githubusercontent.com/assets/15856304/18648503/a74cf3de-7ec3-11e6-82a8-3ff6d17bdd04.png)

<details>
![screen shot 2016-09-19 at 10 00 07 pm](https://cloud.githubusercontent.com/assets/15856304/18648587/f0bdd0ec-7ec3-11e6-84a2-8dd6deb39273.png)

**Comment by Alex-302** [comment]
Fixed
