### ISSUE TITLE
http://www.calciomercato.com detects Adguard

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3031]
Windows 10
Chrome
ver 6.1
![1](https://cloud.githubusercontent.com/assets/20476168/18663777/98c78f4e-7f28-11e6-8616-ea3dd7fb287c.PNG)
![2](https://cloud.githubusercontent.com/assets/20476168/18663776/98c74db8-7f28-11e6-9054-a1dfde28ac54.PNG)

Detects Adguard and hides content
Link:
http://www.calciomercato.com/news/la-rivincita-di-mazzarri-che-convince-in-premier-ecco-le-sue-mos-286813
![default](https://cloud.githubusercontent.com/assets/20476168/18663797/acef1dfc-7f28-11e6-8c24-3b0e4a57d3f5.PNG)

**Comment by Alex-302** [comment]
It was fixed today.
