### ISSUE TITLE
life.ru - Adguard blocks sign-in

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3032]
**Description**:
https://life.ru/t/%D0%BD%D0%B0%D1%83%D0%BA%D0%B0/904318/nie_tu_rakietu_nazvali_satanoi?utm_source=push

Source:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=53221631

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/2466
Fixed
