### ISSUE TITLE
http://www.primewire.ag/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3033]
http://www.primewire.ag/

1414352

![image](https://cloud.githubusercontent.com/assets/15856304/18672249/098bcdb8-7f50-11e6-85ed-aac33c35620f.png)

<details>
Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.15 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.61 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.49 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.35 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.26 Enabled=YES
ID=101 Name="EasyList" Version=1.0.62.54 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.65.17 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.62.54 Enabled=YES
ID=231 Name="Easylist Spanish" Version=1.0.1.94 Enabled=YES
ID=230 Name="FanboyEspanol" Version=1.0.0.1 Enabled=YES

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||images.primewire.ag^
```
