### ISSUE TITLE
gameguru.ru

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#30342]
***Description***:

* **Current behaviour**: 
При включенном AdGuard очень медленно прогружается сайт

* **Expected behaviour**: 
AdGuard не должен влиять на скорость загрузки сайта.

**Reproduced on**
Information                            | Value
---                                    | ---
Operating system:                      | Windows
Operating system version (Android/iOS) | Windows 10 Insider Preview (18346.1)
Browser:                               | Chrome 72
AdGuard version:                       | 7.0.2243.5761 (CL 1.3.185)
Filters enabled:                       | Base, Russian, Mobile, Annoyances, Adblock Warning Removal List
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | 1688445

**Original submission**
Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | Android 4.4.2 (manufacturer=LGE model=LG-V500 brand=lge version=4.4.2)
Browser:                               | Chrome
AdGuard version:                       | 2.12.247
Filters enabled:                       | Base, Russian, Mobile, Annoyances, Spyware, Social Media
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On, WHITELIST
AdGuard DNS:                           | None
Filtering mode: | 
Stealth mode options (Windows only)    | Not enabled

**Comment by Alex-302** [comment]
У меня главная за 8 секунд полностью прогружается.
Сделайте аналогичный скриншот инструментов разработчика
![image](https://user-images.githubusercontent.com/8361299/53799927-40437700-3f44-11e9-90df-4a5e6bf0057d.png)

**Comment by Alex-302** [comment]
@akmLaVx а что там дольше всего грузится? На скрине не видно.

**Comment by akmLaVx** [comment]
watch.js Time: 1.4 min

**Comment by Alex-302** [comment]
IP не украинский, случайно?

> watch.js Time: 1.4 min

мне скриншот нужно. Длительность мало о чём говорит.

**Comment by Alex-302** [comment]
вот так хотя бы
![image](https://user-images.githubusercontent.com/8361299/54348440-b5ecc880-4651-11e9-8432-8536aa50588d.png)

**Comment by akmLaVx** [comment]
@Alex-302 у меня украинский, но аналогичная проблема и у юзеров с российским IP.
![CLOSER](https://user-images.githubusercontent.com/33634917/54348476-c43ae480-4651-11e9-87a8-130b72dce03a.jpg)

**Comment by Alex-302** [comment]
Само содержимое страницы тоже медленно рисуется? Или только крутится значок загрузки?

**Comment by akmLaVx** [comment]
Тоже медленно. На отрисовку сайта уходит около минуты. Пока скрипт не догрузится - ссылки либо открываются лишь через новую вкладку, либо вообще некликабельны.

**Comment by Alex-302** [comment]
А если заблокировать его? Проверь с фильтром аналитики.

**Comment by Alex-302** [comment]
> Пока скрипт не догрузится

у тебя на скрине он по таймауту видать не догрузился из-за блокировки яндексов.

**Comment by slavaleleka** [comment]
у меня не повторяется
