### ISSUE TITLE
https://apfeleimer.de/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3035]
https://apfeleimer.de/2016/09/iphone-7-vorverkauf-apple-store-down-telekom-beendet-iphone-7-reservierung

![screen shot 2016-09-20 at 16 39 44](https://cloud.githubusercontent.com/assets/15856304/18672439/df6341dc-7f50-11e6-9267-730196e31e8e.png)

<details>
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.3 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.61 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.42 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.3.70 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.92 Enabled=YES
ID=6 Name="German filter" Version=1.0.27.29 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.85 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.24 Enabled=YES

**Comment by Alex-302** [comment]
Больше на обычную рекламу похоже. Ссылки на левые сайты.
Добавил в немецкий:
```
apfeleimer.de##body > div.ftr
apfeleimer.de###wbounce-modal
```
