### ISSUE TITLE
http://dailycaller.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3036]
http://dailycaller.com/2016/09/19/computer-tech-who-asked-how-to-strip-out-email-addresses-may-have-worked-for-hillary/

![screen shot 2016-09-20 at 16 41 43](https://cloud.githubusercontent.com/assets/15856304/18672518/28052dec-7f51-11e6-8817-58bbd4d11909.png)

Recommended by ***

<details>
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.18 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.52 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.61 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.77 Enabled=YES

**Comment by Alex-302** [comment]
Английский фильтр блокирует вроде. Глянь ещё плиз.
