### ISSUE TITLE
xhamster.one [Android] [Ads] [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#30366]
**Site**: https://m.xhamster.one/videos/bdsm-indian-wife-handcuffed-and-fucked-in-ass-4311424?pb=&xh_proxy=1

**Issue**: Please remove the empty ad banners at two places on the page.

**Screenshot**: https://ibb.co/LRV9xk7

**Android Version**: 6.0.1 MMB29M

**MIUI Version**: MIUI Global 10.2 - Stable [10.2.1.0 (MHOMIXM)]

**AdGuard Version**: 3.0.257 (Nightly)

**Filters**:
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404

**AdGuard Settings**:
"Other" & "Custom" category Filters: Disabled
Block ads in all apps: Enabled
Phishing and malware protection: Enabled
HTTPS Filtering: Enabled
Filter websites with an EV Certificate: Enabled
Filter Blacklist Only: Disabled
Proxy Settings: Disabled
DNS Filtering: Disabled
Filtering Method: Local VPN
Stealth Mode: Disabled
Low Level Settings: Default

**Addiional Notes**:
All filters updated
Check Done with WiFi connection
Browsing history & cache cleared from FF browser

**Comment by Nzzyme** [comment]
Pop- up also seen on AG for Chrome on Windows 7. Please fix

**Comment by Nzzyme** [comment]
Please fix guys

**Comment by AdamWr** [comment]
Fixed.
