### ISSUE TITLE
http://hk.on.cc/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3037]
http://hk.on.cc/hk/news/mobile/index.html

![screen shot 2016-09-20 at 16 44 04](https://cloud.githubusercontent.com/assets/15856304/18672617/77022f44-7f51-11e6-9005-2bc8b0d3a205.png)

<details>
English filterVersion 1.0.94.90. Updated 20 september 2016 at 16:00.
Spyware filterVersion 1.0.7.68. Updated 16 september 2016 at 01:00.
Social media filterVersion 1.0.12.67. Updated 16 september 2016 at 17:00.
Annoyances filterVersion 1.0.4.15. Updated 20 september 2016 at 15:03.
Russian filterVersion 1.0.39.53. Updated 20 september 2016 at 15:00.
German filterVersion 1.0.27.38. Updated 16 september 2016 at 11:00.

**Comment by Alex-302** [comment]
Added to English filter
```
@@||hk.on.cc/mobile/js/lib/adbanner.js
```
