### ISSUE TITLE
moviesand.com [Ad Text String] [Android] [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#30376]
**Site**: https://www.moviesand.com/1977400-badass-milf-cec-does-what-she-does-best-working-hard-penis-with-her-hands-and-curvy-ass.html?utm_source=PBWeb&utm_medium=PBWeb&utm_campaign=PBWeb

**Issue**: Please remove the ad text string on the page. Also seeing ad banner on video player on AG for Chrome on Windows (http://prntscr.com/ms791d)

**Screenshot**: https://ibb.co/WyM3Qyx

**Android Version**: 6.0.1 MMB29M

**MIUI Version**: MIUI Global 10.2 - Stable [10.2.1.0 (MHOMIXM)]

**AdGuard Version**: 3.0.257 (Nightly)

**Filters**:
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404

**AdGuard Settings**:
"Other" & "Custom" category Filters: Disabled
Block ads in all apps: Enabled
Phishing and malware protection: Enabled
HTTPS Filtering: Enabled
Filter websites with an EV Certificate: Enabled
Filter Blacklist Only: Disabled
Proxy Settings: Disabled
DNS Filtering: Disabled
Filtering Method: Local VPN
Stealth Mode: Disabled
Low Level Settings: Default

**Addiional Notes**:
All filters updated
Check Done with WiFi connection
Browsing history & cache cleared from FF browser

**Comment by Nzzyme** [comment]
On the page, scroll down and tap on any thumbnail and that opens a pop-up. Can you please check?

**Comment by AdamWr** [comment]
Fixed.

**Comment by Nzzyme** [comment]
https://www.moviesand.com/v/jules-jordan-big-tit-milf-star-kendra-lust-has-a-bbc-celebration/

Seeing a pop-up when clicking on the play button. Please fix.

**Comment by AdamWr** [comment]
Fixed.
