### ISSUE TITLE
intel.com

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#30380]
[https://downloadcenter.intel.com/ru/product/80939](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://downloadcenter.intel.com/ru/product/80939)

 Стилевая защита от выделения (копирования).
 В [https://downloadcenter.intel.com/inc/styles/downloadcenter-includes.min.css](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://downloadcenter.intel.com/inc/styles/downloadcenter-includes.min.css) найдена следующая строка: `...;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;-o-user-select:none;user-select:none;...`

<details><summary>Screenshot:</summary>

![2019 03 02-1](https://user-images.githubusercontent.com/17948007/53681174-8acfb400-3cf6-11e9-851d-1269d691c07d.png)
</details><br/>

 С учётом массового распространения защиты от копирования (#25351, #25353, #28866, на mail.ru и др. сайтах, на которые не всегда есть время завести issue) предлагаю:
 **Сделать правило разблокирующее стилевую защиту от копирования - ОБЩИМ**
 Или, как минимум, объединить следующие похожие правила, из Фильтра раздражителей, в одно:
```
fmoviez.org#$#html { -webkit-touch-callout: default!important; -moz-user-select: text!important; -webkit-user-select: text!important; -ms-user-select: text!important; -o-user-select: text!important; user-select: text!important; -khtml-user-select: text!important; }
dzelectronic.com#$#body { -webkit-touch-callout: default!important; -moz-user-select: text!important; -webkit-user-select: text!important; -ms-user-select: text!important; -o-user-select: text!important; user-select: text!important; -khtml-user-select: text!important; }
hulkpop.com#$#body.unselectable { -webkit-touch-callout: default!important; -moz-user-select: text!important; -webkit-user-select: text!important; -ms-user-select: text!important; -o-user-select: text!important; user-select: text!important; -khtml-user-select: text!important; }
droidtk.com#$#body[data-protect="true"] { -webkit-touch-callout: default!important; -moz-user-select: text!important; -webkit-user-select: text!important; -ms-user-select: text!important; -o-user-select: text!important; user-select: text!important; -khtml-user-select: text!important; }
toptech360.com,devicespecifications.com,apkinstaller.com,androidmtk.com,serial-key.com,sjcrack.com,themeslide.com,openssource.biz,kinogo-net-2017.ru,kinogo-online.online,kino-zal.net,lavka-invaitov.ru#$#body * { -webkit-touch-callout: default!important; -moz-user-select: text!important; -webkit-user-select: text!important; -ms-user-select: text!important; -o-user-select: text!important; user-select: text!important; -khtml-user-select: text!important; }
catekno.com#$#img { -webkit-touch-callout: default!important; -webkit-user-select: text!important; }
```

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.0.6
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
У меня копируется. Общим не вижу смысла делать. К блокировке рекламы это не относится.

**Comment by XX-J** [comment]
> У меня копируется.

 Не выделяется (копируется) то, что в красной рамке. Присутствие соответствующих стилей это подтверждает.

> Общим не вижу смысла делать.

* Чтобы в дальнейшем Вас не беспокоить.
* Привести соответствующие стили к первоначальному значению.
* Позволить выделять и копировать в любом месте и на любом сайте.

> К блокировке рекламы это не относится.

 Но это относится к Раздражителям.

**Comment by krystian3w** [comment]
Maybe report to uAssets and subscribe uBlock Annoyance list?

**Comment by Alex-302** [comment]
Для всех сайтов есть `Select like a Boss` и аналоги.

**Comment by XX-J** [comment]
@krystian3w

 For myself, i made this rule:
`dostfilms.*,intel.com,kimovil.*#$#* { -webkit-touch-callout: default!important; -webkit-user-drag: element!important; -webkit-user-select: text!important; user-select: text!important; -moz-user-select: text!important; -khtml-user-select: text!important; -o-user-select: text!important; -ms-user-select: text!important; }`

@Alex-302

 А Вы больше не будете добавлять правила разблокирующие выделение и копирование текста на страницах сайтов?

**Comment by Alex-302** [comment]
Буду. Но общими делать не будем.

**Comment by krystian3w** [comment]
Good

**Comment by XX-J** [comment]
@Alex-302 

> Буду. Но общими делать не будем.

 Тогда добавьте, пожалуйста, правило, приведённое мной выше:
`dostfilms.*,intel.com,kimovil.*#$#* { -webkit-touch-callout: default!important; -webkit-user-drag: element!important; -webkit-user-select: text!important; user-select: text!important; -moz-user-select: text!important; -khtml-user-select: text!important; -o-user-select: text!important; -ms-user-select: text!important; }`

 Оно касается: #25351, #30380 и #23028

__________

 А лучше, я думаю, совместить все однотипные идентификаторы, касающиеся запрета выделения, на основе CSS, со всеми доменами, на которых эти идентификаторы применяются. Получится одно всеобъемлющее правило, в которое в дальнейшем можно будет добавлять только домены.

 Т.е. берём подсекцию "--- CSS ---" секции "Unblock context menu and other mouse limitations" файла [.../AnnoyancesFilter/sections/tweaks.txt](https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/sections/tweaks.txt):
```
fmoviez.org#$#html { -webkit-touch-callout: default!important; -moz-user-select: text!important; -webkit-user-select: text!important; -ms-user-select: text!important; -o-user-select: text!important; user-select: text!important; -khtml-user-select: text!important; }
dzelectronic.com#$#body { -webkit-touch-callout: default!important; -moz-user-select: text!important; -webkit-user-select: text!important; -ms-user-select: text!important; -o-user-select: text!important; user-select: text!important; -khtml-user-select: text!important; }
hulkpop.com#$#body.unselectable { -webkit-touch-callout: default!important; -moz-user-select: text!important; -webkit-user-select: text!important; -ms-user-select: text!important; -o-user-select: text!important; user-select: text!important; -khtml-user-select: text!important; }
droidtk.com#$#body[data-protect="true"] { -webkit-touch-callout: default!important; -moz-user-select: text!important; -webkit-user-select: text!important; -ms-user-select: text!important; -o-user-select: text!important; user-select: text!important; -khtml-user-select: text!important; }
toptech360.com,devicespecifications.com,apkinstaller.com,androidmtk.com,serial-key.com,sjcrack.com,themeslide.com,openssource.biz,kinogo-net-2017.ru,kinogo-online.online,kino-zal.net,lavka-invaitov.ru#$#body * { -webkit-touch-callout: default!important; -moz-user-select: text!important; -webkit-user-select: text!important; -ms-user-select: text!important; -o-user-select: text!important; user-select: text!important; -khtml-user-select: text!important; }
catekno.com#$#img { -webkit-touch-callout: default!important; -webkit-user-select: text!important; }
```

 Сливаем все домены и CSS-свойства в одно правило, добавляем мои три ~~копейки~~ домена и, вуаля:

`fmoviez.org,dzelectronic.com,hulkpop.com,droidtk.com,toptech360.com,devicespecifications.com,apkinstaller.com,androidmtk.com,serial-key.com,sjcrack.com,themeslide.com,openssource.biz,kinogo-net-2017.ru,kinogo-online.online,kino-zal.net,lavka-invaitov.ru,catekno.com,dostfilms.*,intel.com,kimovil.*#$#* { -webkit-touch-callout: default!important; -webkit-user-drag: element!important; -webkit-user-select: text!important; user-select: text!important; -moz-user-select: text!important; -khtml-user-select: text!important; -o-user-select: text!important; -ms-user-select: text!important; }`

**Comment by Alex-302** [comment]
`*` в доменах правил сокрытия/стилей/JS  не работает

**Comment by XX-J** [comment]
> `*` в доменах правил сокрытия/стилей/JS не работает

 Работает, как минимум в сокрытиях и стилях. У меня так многие правила работают, например связанные с Яндексом, да и моё, вышеуказаное правило тоже работает, т.к. я им пользуюсь.

 Если предположить что ошибочные домены игнорируются и правило срабатывает везде, то это тоже не так, я проверял.

**Comment by krystian3w** [comment]
Maybe no supported is `*` as many TLD-s (suffixs)?

https://publicsuffix.org/list/public_suffix_list.dat
