### ISSUE TITLE
http://www.zr.ru/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3038]
http://www.zr.ru/

![screen shot 2016-09-20 at 16 47 42](https://cloud.githubusercontent.com/assets/15856304/18672740/fba6ab8a-7f51-11e6-9bfc-93ab1190d69a.png)

<details>
English filterVersion 1.0.94.90. Updated 20 september 2016 at 16:00.
Spyware filterVersion 1.0.7.68. Updated 16 september 2016 at 01:00.
Social media filterVersion 1.0.12.67. Updated 16 september 2016 at 17:00.
Annoyances filterVersion 1.0.4.15. Updated 20 september 2016 at 15:03.
Russian filterVersion 1.0.39.53. Updated 20 september 2016 at 15:00.
German filterVersion 1.0.27.38. Updated 16 september 2016 at 11:00.

**Comment by Alex-302** [comment]
Добавил в фильтр раздражителей
```
zr.ru#%#document.cookie = "zrPushSubsPopUp=1";
```
