### ISSUE TITLE
se.feomedia.quizkampen.ru.lite - adguard breaks login

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3039]
**Description**:
https://play.google.com/store/apps/details?id=se.feomedia.quizkampen.ru.lite

Source:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=53289012

**Comment by Alex-302** [comment]
Can't reproduce. Asked for details.

**Comment by ministr91** [comment]
На видео все должно отображаться.
Стоит Nexus 5, Android 4.4.4
http://radikal.ru/video/6uTEFpeDo8U

**Comment by Alex-302** [comment]
Просмотрел половину. Дальше вроде ничего нового.
Переключите запись журнала в режим записи HTTP запросов, остановите игру, очистите её кэш и запустите. Время запуска запишите. Сделайте несколько попыток авторизоваться.
Места, где могут находиться логи:
```
/storage/emulated/Android/data/com.adguard.android/cache/log
/sdcard/Android/com.adguard.android/cache/log
/sdcard/data/Android/com.adguard.android/cache/log
/sdcard/Android/data/com.adguard.android/
```

**Comment by ministr91** [comment]
Толкто здесь есть папка, но она пустая

**Comment by ministr91** [comment]
/sdcard/Android/data/com.adguard.android/

**Comment by ministr91** [comment]
1) /storage/emulated/ там у меня Android или legacy
2) /sdcard/Android/ здесь у меня выбор папки data или obb
3) /sdcard/data здесь у меня папки build или data

**Comment by Alex-302** [comment]
Странно. Каталог пуст после обновления вкладки?

**Comment by ministr91** [comment]
Какого обновления? Я сделал все по инструкции, каталог пуст. Что теперь делать? Могу видос запилить

**Comment by Alex-302** [comment]
После остановки и запуска приложения в том каталоге должен появиться файл с журналом.
Адгард был включен когда лог записывали?

**Comment by ministr91** [comment]
Да

**Comment by Alex-302** [comment]
Странно. Попробуйте отправить сообщение в поддержку, может лог где-нибудь в другом месте находится, если прошивка не оригинальная.

**Comment by ministr91** [comment]
Оригинальная прошивка. Зачем мне отправлять сообщение в поддержку? Тут же сидит разработчик

**Comment by Alex-302** [comment]
Сидит. Но без лога гадать сложно.

**Comment by ministr91** [comment]
Может лог в другой папке?

**Comment by Alex-302** [comment]
Не знаю. Отправьте сообщение в поддержку с прикреплением лога и сообщите мне номер заявки.

**Comment by ministr91** [comment]
1418578

**Comment by ministr91** [comment]
У меня программа частично работает. Выскакивает надпись об ошибке, после 5 раз нажатия на "попробовать снова" - запустилась. Но проблему эту не решает, надо найти способ, чтобы без этой таблицы игра запускалась

**Comment by Alex-302** [comment]
Похоже вы не переключили журналирование на запись HTTP запросов.
Сделайте следующее:
1) В настройках Андроида очистите кэш Адгарда, без остановки. Это сотрёт существующий лог.
2) Полностью остановите игру.
3) Передёрните защиту Адгарда
4) Запустите игру и обязательно запишите время запуска
5) После возникновения ошибки нажмите "повторить" два раза(но чтоб не было успешного запука)
6) Отправьте сообщение в поддержку как в прошлый раз.

Есть ещё вариант - проверьте с отключенными фильтрами. Если будет запускаться нормально, включайте по одному с проверкой.

**Comment by ministr91** [comment]
Что значит передернуть?

**Comment by Alex-302** [comment]
выключить и включить

**Comment by ministr91** [comment]
HTTP я включал

**Comment by ministr91** [comment]
Сейчас HTTP мне не нужно включать?

**Comment by ministr91** [comment]
Отправил. Только мне тикет не пришел. Время 13:38 +- 2 минуты

**Comment by Alex-302** [comment]
Тогда напишите часть адреса эл почты. По ней найду.

**Comment by ministr91** [comment]
ministr91@rambler.ru

**Comment by Alex-302** [comment]
Такой же как и в прошлый раз.
Покажите скриншот расширенных настроек.
Режим прокси ручной или автоматический? Режим VPN не пробовали?

**Comment by ministr91** [comment]
Я же пилил видос,все тоже самое
http://s011.radikal.ru/i316/1609/75/1034ceefd79f.png

**Comment by ministr91** [comment]
Только у меня такая проблема? Попробуйте сделать все настройки как у меня и посмотреть

**Comment by Alex-302** [comment]
Видео не очень удобный вариант. Если нужно найти конкретную настройку, то заново смотреть нужно. Учитывая количество заявок(есть ещё форум), это не самый оптимальный вариант.



> Только у меня такая проблема? Попробуйте сделать все настройки как у меня и посмотреть
проверял, не повторяется.

Пробуйте по порядку:
- выключить все фильтры
- выключить https фильтрацию

**Comment by ministr91** [comment]
сделал все как и сказали - в приложение вошло, но реклама появилась

**Comment by ministr91** [comment]
Включил https фильтрацию и проблема снова появилась

**Comment by ministr91** [comment]
Отключены все фильтры и включен режим https - проблема остается

**Comment by ministr91** [comment]
Проблема решена. Отключил в настройке приложения фильтрацию https. Приложение работает, рекламы нет. Тему можно закрывать

**Comment by Alex-302** [comment]
Это уже интереснее.
Полностью фильтрацию HTTPS можно не выключать, это можно сделать через настройки приложений для конкретного приложения.

Можете собрать logcat по этой инструкции после повторения ошибки?
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/63/5/kk-poluchit-log-logcat-n-ustrojjstve-android

**Comment by ministr91** [comment]
да я и не стал полностью отключать https, я же написал "Отключил в настройке приложения".
Слишком долго как вы написали. Такой лог кэт вам подойдет? http://4pda.ru/forum/index.php?showtopic=260024 В приложении есть функция "сохранить".

**Comment by Alex-302** [comment]
Сделайте, посмотрим)
Только напишите примерное время возникновения ошибки.

**Comment by Alex-302** [comment]
Т.к. проблема с фильтрацией SSL, здесь закрываю.
Лог можете сразу в раздел Андроида выложить:
https://github.com/AdguardTeam/AdguardForAndroid/issues/811
