### ISSUE TITLE
http://anitokyo.tv - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3040]
http://anitokyo.tv/anime/3053-zanovo-zhizn-s-nulya-v-drugom-mire-re-zero-kara-hajimeru-isekai-seikatsu.html

![screen shot 2016-09-20 at 17 12 22](https://cloud.githubusercontent.com/assets/15856304/18673692/6b4b75ee-7f55-11e6-8f90-3ac3e0a25b21.png)

<details>
 adguard в виде расширения у Chrome
* фильтры: русский, английский, RU AdList
* Dr.Web

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
anitokyo.tv#$#body { background: #e4f1f6!important; }
anitokyo.tv#$#body > div#wrapper > header { margin: 0px 0 0 0!important; }
anitokyo.tv##body > div#wrapper > div > a > div[style]

```
