### ISSUE TITLE
podbean.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#30401]
`https://www.podbean.com/`

Bottom cookie notice.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.4
Firefox 65

**Comment by adranger** [comment]
@Alex-302 they've changed the `background` property of the style you used. 

In case this works on Adguard too, it does the trick: `podbean.com##div:has(>#ok_use_cookie_warning)`

**Comment by Alex-302** [comment]
Existing rule works on my end.

**Comment by adranger** [comment]
The existing rule has:

```
background: rgb(101, 101, 101);
```

While this is the website code displayed to me:

```
background: rgb(101, 101, 101) none repeat scroll 0% 0%; 
```

**Comment by Alex-302** [comment]
Please upload saved full page.

**Comment by adranger** [comment]
[Free Podcast Hosting - Starting a Podcast in 5 Minutes   Podbean_files.zip](https://github.com/AdguardTeam/AdguardFilters/files/3237822/Free.Podcast.Hosting.-.Starting.a.Podcast.in.5.Minutes.Podbean_files.zip)

**Comment by Alex-302** [comment]
It is matched my existing rule:

<details>
![image](https://user-images.githubusercontent.com/8361299/58702950-d9512500-83af-11e9-8871-05831caaa63a.png)

</details>

**Comment by adranger** [comment]
@uBlock-user was this supposed to be working on uBlock Origin?

**Comment by Alex-302** [comment]
The same rule should to work in uBO
