### ISSUE TITLE
xozilla.com [Ad Banner] [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#30421]
**Site**: https://www.xozilla.com/videos/118412/busty-japansese-amane-arisu-titty-fucked-in-censored-asian-movie/

**Issue**: Please remove the ad banner seen at the bottom right of the page.

**Screenshot**: http://prntscr.com/msj328

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 72.0.3626.81 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by Alex-302** [comment]
@Nzzyme please check again

**Comment by Nzzyme** [comment]
It works fine now. Thank you!

**Comment by Nzzyme** [comment]
Pop-up seen now. Can you please check.

**Comment by AdamWr** [comment]
Added:
`||xozilla.com/js/ppndr.js`
`xozilla.com#%#AG_abortOnPropertyRead('popunder');`
