### ISSUE TITLE
MSN News app issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3042]
https://play.google.com/store/apps/details?id=com.microsoft.amp.apps.bingnews&hl=ru

It shows error, disabling HTTPS filtering doesn't help, disabling filtering makes it work again.

![image](https://cloud.githubusercontent.com/assets/15856304/18681814/5b61150e-7f72-11e6-9c3e-4ecee48a0dad.png)

eng, spyware, social, mobile, russian

**Comment by Alex-302** [comment]
Added:
```
@@||appex-rf.msn.com/*.js?adtype=
```

**Comment by Bohdan-SUP** [comment]
Same issue with MSN Money - https://play.google.com/store/apps/details?id=com.microsoft.amp.apps.bingfinance

**Comment by Alex-302** [comment]
Can't reproduce. Need http log.

**Comment by vgavrish** [comment]
В MSN News снова проблема с загрузкой новостей: http://prntscr.com/d7h2ra
Помогает отключение Английского фильтра

**Comment by Alex-302** [comment]
@vgavrish а можно удалённо глянуть? Так быстрее будет)

**Comment by vgavrish** [comment]
@Alex-302  да, конечно
сегодня или завтра?

**Comment by Alex-302** [comment]
@vgavrish давай завтра уже)

**Comment by vgavrish** [comment]
[debug (1).txt](https://github.com/AdguardTeam/AdguardFilters/files/600251/debug.1.txt)
17-16

**Comment by Alex-302** [comment]
Не тот лог) Нужны HTTP запросы.

**Comment by Alex-302** [comment]
решено
