### ISSUE TITLE
tigernet.com - incorrect blocking due to social filter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3043]
**Description**:
"Boards" menu item missing in mobile version of the website.
Problematic rule is `###social`

Without AG:
http://i.imgur.com/oRiLGS6.png

With AG:
http://i.imgur.com/Eakvebk.png

**Comment by ameshkov** [comment]
New issue: 

> Same website, another issue I've recently noticed. This time it's a 'You May Like' with a bunch of links and thumbnails. Here's a screenshot:
> http://i.imgur.com/MqFGfH3.png

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
tigernet.com###adblockSky
tigernet.com###adblockBox
tigernet.com###topAdBlock
```
Added to English filter
```
||d2ymkpxi1rgldj.cloudfront.net^
tigernet.com###wrapper_front > div[style="height:250px;"]
```
