### ISSUE TITLE
psarips.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3044]
Just wanted to ask why is psarips on the whitelist?
there is a rule: @@||psarips.com^$script
I want to ask why is it necessary to whitelist it?
Site functions well even without the whitelist use.

**Comment by Alex-302** [comment]
It is EasyList rule. I will exclude it on our side.

**Comment by Bohdan-SUP** [comment]
It is still in English filter on my end:
![screen shot 2016-09-27 at 12 22 03 pm](https://cloud.githubusercontent.com/assets/14153331/18867479/0c4598d8-84ad-11e6-976e-b6202688d526.png)

**Comment by Alex-302** [comment]
I will exclude it, not excluded:)
Excluded it now.

**Comment by Bohdan-SUP** [comment]
Still there:)
![image](https://cloud.githubusercontent.com/assets/14153331/19219130/02543120-8e14-11e6-8fea-962313f13134.png)

User **1023133** wonders if there is a need for such rule, since the website works fine without this exception.

**Comment by Alex-302** [comment]
Now it is excluded finally.
