### ISSUE TITLE
https://apps.crashlytics.com - blocked by a content blocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3045]
https://apps.crashlytics.com/projects?utm_medium=webclip&utm_source=webclip

![img_0299](https://cloud.githubusercontent.com/assets/15856304/18719212/1869c3dc-802f-11e6-8c08-d05c7ab78ebf.PNG)

<details>

Application version: 1.0.8.54
Application lifetime: 2016-09-16 03:42:36 +0000

Device: iPhone
Platform: iPhone OS
OS: 10.0.1
ID: 8DB14ADB-C266-4C41-8F51-0A0E742D659A

Locale: en
Region: gb

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.57 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.71 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.68 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.4.3 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.39.33 Enabled=NO
ID=6 Name="German filter" Version=1.0.27.37 Enabled=NO
ID=7 Name="Japanese filter" Version=1.0.93.1 Enabled=NO
ID=8 Name="Dutch filter" Version=1.0.8.98 Enabled=NO
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.35 Enabled=NO
ID=13 Name="Turkish filter" Version=1.0.3.54 Enabled=NO
ID=5 Name="Experimental filter" Version=1.0.26.25 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.88 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.27 Enabled=YES
ID=101 Name="EasyList" Version=1.0.62.67 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.65.49 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.62.67 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.62.81 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.14 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.65.63 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
ID=220 Name="CJX's Annoyance List" Version=1.0.0.63 Enabled=YES
ID=225 Name="Fanboy Anti-Facebook List" Version=1.0.0.6 Enabled=YES
ID=229 Name="I dont care about cookies" Version=1.0.0.3 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.65.51 Enabled=YES
ID=204 Name="Peter Lowe's list" Version=1.0.2.32 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.59 Enabled=YES

**Comment by Alex-302** [comment]
It is blocked as mobile analytics.
For user filter:
```
@@||crashlytics.com^$domain=crashlytics.com
```
or
```
@@||crashlytics.com^
```

User have enabled tooo much filters. Limit is only 50000 rules. These filters contains ~200k rules.
