### ISSUE TITLE
autonaminuty.org

### ISSUE THREAD

**Issue by kulfoon** [AdguardTeam/AdguardFilters#30457]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Breakage - shadow overlay

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
Screenshoots:

<details not-open>
<summary>screenshoot 1 - after enabling Fanboy’s Social Blocking List and/or AdGuard Social Media filter</summary>

![ss_033](https://user-images.githubusercontent.com/43844449/53731055-e5dde400-3e79-11e9-856e-bc943d1957c8.png)

</details>
.

<details not-open>
<summary>screenshoot 2 - after disabling the lists</summary>

![ss_031](https://user-images.githubusercontent.com/43844449/53731070-ee361f00-3e79-11e9-8958-a29f2d1107e5.png)

</details>
<br>

* **Expected behaviour**: 

No shadow overlay

<details><summary>screenshoot 3 - after closing/hiding the message</summary>

![image](https://user-images.githubusercontent.com/43844449/53731780-1c1c6300-3e7c-11e9-8487-10cc50269489.png)
</details><br/>

***Steps to reproduce the problem***:

Visit the website.

***System configuration***

**Filters:**

uBO default + 
AdGuard Social Media filter +
Fanboy Social Blocking List

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 7 SP1 64bit
Browser:                               | Firefox 65.0.2 64bit / Opera 58 64bit
AdGuard version:                       | uBlock Origin 1.18.4

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

Orginally reported here: https://github.com/ryanbr/fanboy-adblock/issues/963, as Fanboy's Social Blocking List is causing it too.

**Comment by Alex-302** [comment]
Reproduced with our Social Media filter. Fixed.
