### ISSUE TITLE
http://www.buscape.com.br/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3046]
http://www.buscape.com.br/

![image-1](https://cloud.githubusercontent.com/assets/15856304/18719406/f247a1f0-802f-11e6-8cf9-38e9c7cb8f7e.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-09-11 21:00:51 +0000

Device: iPad
Platform: iPhone OS
OS: 10.0.1
ID: 903DA602-62CA-4FA6-8515-CC9B0B676A9F

Locale: en
Region: br

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.42 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.64 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.59 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.3.91 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.35 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.87 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.27 Enabled=YES
ID=101 Name="EasyList" Version=1.0.62.62 Enabled=YES

**Comment by Alex-302** [comment]
Check this rule:
```
@@||buscape.com.br^$domain=buscape.com.br
```
