### ISSUE TITLE
http://www.nydailynews.com/ - placeholder

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3047]
http://www.nydailynews.com/

![image1](https://cloud.githubusercontent.com/assets/15856304/18721233/3cafe074-8038-11e6-8e4a-ffdc92e79ce1.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-09-14 01:55:35 +0000

Device: iPhone
Platform: iPhone OS
OS: 10.0.1
ID: BF8A3724-A807-4FCC-BF58-44E6F5D807AA

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.91 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.73 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.78 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.31 Enabled=YES

**Comment by Alex-302** [comment]
Added to Mobile filter
```
body > #r-main > div.r-yieldmo
```
