### ISSUE TITLE
http://www.lemonde.fr/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3048]
http://www.lemonde.fr/televisions-radio/video/2016/09/22/au-dela-des-murs-la-fiction-francaise-hors-des-sentiers-battus_5001697_1655027.html

Adguard seems to block video playback on the site <details>
![screen shot 2016-09-22 at 5 35 16 pm](https://cloud.githubusercontent.com/assets/15856304/18752412/ff423026-80ea-11e6-86c3-855a06aa50c7.png)

![screen shot 2016-09-22 at 5 36 22 pm](https://cloud.githubusercontent.com/assets/15856304/18752455/1a0377e4-80eb-11e6-899e-496ab9993420.png)

**Comment by Alex-302** [comment]
Please check this rule:
[CODE]
@@||ultimedia.com/deliver/video$domain=ultimedia.com,xmlhttprequest,other
[/CODE]

**Comment by Seko33** [comment]
I'm afraid it did'n't work.
Rule Ticked or not nothing new appears. Video isn't available.

**Comment by Alex-302** [comment]
I can't reproduce it now.
@Seko33 Could you, please, provide me remote access via TeamViewer?

**Comment by Seko33** [comment]
Yes I can.

**Comment by Alex-302** [comment]
Please check it few days. If it will works, please let me know.
Maybe the issue was in Liste FR, and fixed by the author.
