### ISSUE TITLE
https://apk4free.net - pop ups 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3049]
Please check, I was able to reproduce this. 
SRT
1. Go there http://apk4free.net
2. Click the green Menu button
3. It opens pop ups with multiple redirects, it ends on facebook or google play or anywhere else.

<details>
  "enabledFilterIds" : [ 2, 3, 4, 14, 1, 6, 7, 8, 9, 13, 5, 11, 102, 104, 109, 113, 114, 200, 211, 216, 217 ],
HTTPS is on

**Comment by Alex-302** [comment]
Added to English filter
```
||cloudfront.net^$domain=apk4free.net
```
