### ISSUE TITLE
Adguard DNS blocks redirecting links

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardFilters#30514]
### AG for Android + Adguard DNS
<br/>

Go to http://fas.st/6y4ERD  →  `shopbop.evyy.net` request blocked by `||evyy.net^` rule from
[DnsFilter](https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/filter_15_DnsFilter/filter.txt#L20728) (the original rule is in [Spyware filter](https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/tracking_servers.txt#L1038))

Should `@@||shopbop.evyy.net^|` be added to SDNS-filter/exceptions.txt?

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/53
