### ISSUE TITLE
Yandex Zen issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3051]
на странице яндекса вкладки, в разделе новости дзен, где адгуард, не отображается и страницу невозможно добавить в исключения, при нажатии на некоторые новости, открывается не те страницы, при отключении адгуард, проблема исчезает.

видео здесь: 1252489

state <details>
Os version: Microsoft Windows NT 6.1.7601 Service Pack 1
Dot .net version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: d06ac18de7b84a9ba7e8e1e23b321c42
Language: ru
AppVersion: 6.1.258.1302
Main settings: 
Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:14 Name: Annoyances filter Url: http://adguard.com/ru/filter-rules.html?id=14
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Tdi
Ads Blocked: 40035, Trackers Blocked: 30495
Filtering Mode: Driver
Application lifetime: 5.03:33:50.2203091
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 1,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": true,
  "HideUserAgent": true,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": true,
  "CustomIp": "209.141.53.254"
}

**Comment by Alex-302** [comment]
Передай на проверку:
```
@@||zen.yandex.ru^$stealth
```
