### ISSUE TITLE
com.itvasoft.radiocent app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3052]
https://play.google.com/store/apps/details?id=com.itvasoft.radiocent

![screenshot_2016-09-16-10-34-03](https://cloud.githubusercontent.com/assets/15856304/18763399/e4ac1daa-8115-11e6-8f7d-a974dd4e6728.png)

<details>
HTTP logs here: 1411694

**Comment by Alex-302** [comment]
Установил, запустил с выключенным интернетом - баннер есть, т.е. встроен.
