### ISSUE TITLE
Site with ads and pop-ups http://www.myvidster.com/

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3053]
Adguard 6.1
Windows 10
Chrome
<details> ![1](https://cloud.githubusercontent.com/assets/20476168/18789753/ce1061ce-81b4-11e6-837c-9f2d0364b4ae.PNG)
![2](https://cloud.githubusercontent.com/assets/20476168/18789754/ce1288be-81b4-11e6-917b-a2ec13e61a19.PNG) </details>

The issue is
<details> ![1](https://cloud.githubusercontent.com/assets/20476168/18789843/22c76c80-81b5-11e6-9355-1a1991632b3a.PNG)
![j2](https://cloud.githubusercontent.com/assets/20476168/18789842/22c4a5fe-81b5-11e6-8e30-ddce84dfb9a4.PNG) </details>

**Comment by evgeniy-ADG** [comment]
+ check for pop ups, the main concern s was pop up, I had it on my windows machine and will update here

**Comment by Alex-302** [comment]
Added to English filter
```
||myvidster.com/*_neverblock.php
```
