### ISSUE TITLE
http://newdeaf-online.net/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3054]
Reproduced with the extension on Mac:

<details>
![screen shot 2016-09-23 at 6 56 46 pm](https://cloud.githubusercontent.com/assets/15856304/18792539/9e94b32c-81bf-11e6-917c-bf8a0ed41bbd.png)
</details>

English filterVersion 1.0.95.17. Updated 23 september 2016 at 16:00.
Russian filterVersion 1.0.39.62. Updated 23 september 2016 at 16:00.

With the app we have placeholders like this:
<details>
![screen shot 2016-09-23 at 6 59 15 pm](https://cloud.githubusercontent.com/assets/15856304/18792612/d883471a-81bf-11e6-8466-d27b37592bd8.png)
<details>

**Comment by vozersky** [comment]
full screen pop ups and missed ads with Mac App as well:

![screen shot 2016-09-23 at 19 37 44](https://cloud.githubusercontent.com/assets/17472907/18793845/5882332c-81c5-11e6-8d29-5ba850f4c69d.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||ortetse.ru^$third-party

```
