### ISSUE TITLE
https://yandex.ru/maps - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3055]
1134382
1059796
Реклама появляется в блоке «Маршруты» на Яндекс.Картах: https://yandex.ru/maps/2/saint-petersburg/?ll=30.315868%2C59.932724&z=11&mode=routes&rtext=&rtt=mt

![screen shot 2016-09-23 at 7 03 35 pm](https://cloud.githubusercontent.com/assets/15856304/18792761/7370e03e-81c0-11e6-8496-c26e42f5200f.png)

Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:105 Name: EasyList Czech and Slovak Url: https://raw.github.com/tomasko126/easylistczechandslovak/master/filters.txt
FilterId:216 Name: Adblock polskie reguły Url: http://www.certyficate.it/adblock/adblock.txt

**Comment by Alex-302** [comment]
Убрал
