### ISSUE TITLE
http://fs.to/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3056]
http://fs.to/

http://fs.to/video/serials/iLevrG1negsah0fWYeJ8Na-horosheje-mesto.html

<details>
![screen shot 2016-09-23 at 7 39 12 pm](https://cloud.githubusercontent.com/assets/15856304/18793867/70951dc6-81c5-11e6-80ff-4ef72087c479.png)
</details>

![screen shot 2016-09-23 at 7 39 50 pm](https://cloud.githubusercontent.com/assets/15856304/18793885/816f6e80-81c5-11e6-9ebe-be0ac004b93e.png)

**Comment by Alex-302** [comment]
на маке пока полностью не исправить
