### ISSUE TITLE
http://hentai-share.me/ - pop-up ads

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3057]
Windows 10 
Chrome
Adguard 6.1

http://hentai-share.me/568-moya-gornichnaya-cundere-seksi-zastenchivaya-gornichnaya.html
<details>
![1](https://cloud.githubusercontent.com/assets/20476168/18794539/954cbdf6-81c8-11e6-980d-82a2a08dd2ec.PNG)
![2](https://cloud.githubusercontent.com/assets/20476168/18794540/954e17c8-81c8-11e6-9158-845bc403f3fc.PNG)

After 10 seconds on site

<details>
![gh](https://cloud.githubusercontent.com/assets/20476168/18795257/57be2c46-81cc-11e6-93e2-5635cde43bd2.PNG)

</details>

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||tivisla.ru^$third-party

```
