### ISSUE TITLE
Aeroplan.com first access bug

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3059]
Windows 10 
Adguard 6.1
Bug reproduced with all browsers.
<details>
![1](https://cloud.githubusercontent.com/assets/20476168/18808099/803d28bc-8261-11e6-88c1-64bc460f66da.PNG)
![2](https://cloud.githubusercontent.com/assets/20476168/18808100/803eb722-8261-11e6-8592-ce56d060fdbc.PNG)
</details>
When you reach the site first time you get screen with language choice. Clicking on this choice buttons change nothing, Just disabling Adguard helps.
<details>
![default](https://cloud.githubusercontent.com/assets/20476168/18808109/cd824c6a-8261-11e6-866e-b56dd9dd60ed.PNG)
</details>

**Comment by Alex-302** [comment]
I can't reproduce with these filters.

**Comment by Bohdan-SUP** [comment]
@Fridrix can you still reproduce the issue?

**Comment by Fridrix** [comment]
@Alex-302 That's ok now)

**Comment by Alex-302** [comment]
@Fridrix close then.

**Comment by Alex-302** [comment]
Or can't you close issues end edit labels?

**Comment by Fridrix** [comment]
@Alex-302  i can't

**Comment by Alex-302** [comment]
Ok then
