### ISSUE TITLE
xakep.ru

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#30615]
Description:

Current behaviour:
При включенном AdGuard очень медленно прогружается сайт

Expected behaviour:
AdGuard не должен влиять на скорость загрузки сайта.

Network console:
![xakep_ru](https://user-images.githubusercontent.com/33634917/53944403-f71c3000-40c7-11e9-8286-03242758e149.jpg)

Reproduced on
Information | Value
--- | ---
Operating system: | Windows
Operating system version (Android/iOS) | Windows 10 Insider Preview (18351.1)
Browser: | Chrome 72
AdGuard version: | 7.0.2243.5761 (CL 1.3.185)
Filters enabled: | Base, Russian, Mobile, Annoyances, Adblock Warning Removal List
AdGuard mode (Android only): | VPN / Proxy (manual/auto)
Filtering quality (Android only): | High-quality / High-speed / Simplified
HTTPS filtering (Android only): | On (Default/Blacklist mode) / Off
Simplified filters (iOS only) | On / Off
AdGuard DNS: | None
Stealth mode options (Windows only) | None
Helpdesk ID (if exists): | 1688445

Original submission
Information | Value
--- | ---
Operating system: | Android
Operating system version (Android/iOS) | Android 4.4.2 (manufacturer=LGE model=LG-V500 brand=lge version=4.4.2)
Browser: | Chrome
AdGuard version: | 2.12.247
Filters enabled: | Base, Russian, Mobile, Annoyances, Spyware, Social Media
AdGuard mode (Android only): | VPN
Filtering quality (Android only): | High-quality
HTTPS filtering (Android only): | On, WHITELIST
AdGuard DNS: | None
Filtering mode: |
Stealth mode options (Windows only) | Not enabled

**Comment by Alex-302** [comment]
Так же не повторяется.

**Comment by Alex-302** [comment]
Пусть фильтр аналитики попробуют включить.

**Comment by Big-U-Boss** [comment]
Все-равно долго загружает статьи!😞

**Comment by Alex-302** [comment]
А через VPN?

**Comment by Big-U-Boss** [comment]
Отображается быстро

**Comment by Alex-302** [comment]
Ну вот. Провайдер мешает, или его днс.

**Comment by Big-U-Boss** [comment]
После твоих манипуляций стало гораздо быстрее,до 10 секунд с минуты. Жаль я не могу.проследить.запросы,помощник не показывает всё.

**Comment by Alex-302** [comment]
Запиши HAR с очисткой кэша.
