### ISSUE TITLE
myprokatonline.ru - rental form is blocked

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3061]
**Description**: go to http://myprokatonline.ru/zakaz-avto.html#!yalta/051016/131016

Screenshot: 
<details>

![screen shot 2016-09-25 at 1 35 48 am](https://cloud.githubusercontent.com/assets/14153331/18811666/98b2dcf2-82c0-11e6-8bdd-82df04af8429.png)
![screen shot 2016-09-25 at 1 36 04 am](https://cloud.githubusercontent.com/assets/14153331/18811665/98b166c4-82c0-11e6-90b4-58e790c85b3b.png)
</details>

Filters:
<details>
![screen shot 2016-09-25 at 1 37 29 am](https://cloud.githubusercontent.com/assets/14153331/18811669/ad8f31fc-82c0-11e6-9b3c-fa3a8a79deb8.png)

</details>

**Comment by Alex-302** [comment]
Can't reproduce with these filters.

**Comment by Bohdan-SUP** [comment]
Huh, checked again and works like a charm on Windows/Mac. Not sure what caused it in first place :/
