### ISSUE TITLE
fs.to постеры

### ISSUE THREAD

**Issue by mksy** [AdguardTeam/AdguardFilters#3062]
**Description**:
Не отображаются постеры если подключен русский фильтр, на их место gif'ка 1х1 пиксель стает.

Screenshot: 
<details>
![](https://cdn.pbrd.co/images/76JUdZ7fR.png)
</details>

**Adguard version**: 2.4.14

**Operating system**: Windows 10 x64

**Browser**: Opera 40.0.2308.62

**Comment by Alex-302** [comment]
Исправил. Обновление где-то через час будет доступно.
