### ISSUE TITLE
savefrom.net - annoyance

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3063]
**Steps to reproduce the problem**:

* go to savefrom.net
* paste a link to download a YT video (for example https://youtu.be/KGR5HP3KSBk)
* the following annoyance appears

<details>
![screen shot 2016-09-25 at 1 42 55 am](https://cloud.githubusercontent.com/assets/14153331/18811708/a84e628e-82c1-11e6-836e-7fc17e040cb8.png)
</details>

Filters:
<details>
![screen shot 2016-09-25 at 1 37 29 am](https://cloud.githubusercontent.com/assets/14153331/18811709/b6e52c56-82c1-11e6-9c7e-312b7cc231a8.png)
</details>

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
savefrom.net###modal-container > div.shade
savefrom.net###modal-container > div.popup-content
```
