### ISSUE TITLE
[Windows] www.tweaktown.com - anti adblock ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#3064]
![](http://i.imgur.com/7m8Y1QB.png)

http://www.tweaktown.com/

**Adguard version**: 6.1.258.1302

**Operating system**: Windows 10

**Browser**: Chrome

**Comment by Alex-302** [comment]
I can't reproduce it. Which script do it?
Maybe this?(from HTML)
```
function setupGPTuo(isAdblocked)....
```

Removed
```
tweaktown.com#%#window.blockAdBlock = function() {};
tweaktown.com#%#window.checkState = function() {};
```

**Comment by Vincent-Michael** [comment]
rnd bug ...

**Comment by Alex-302** [comment]
What?:)

**Comment by Vincent-Michael** [comment]
@Alex-302 
Ads are again back for me ...

i can skip via:
``` tweaktown.com#%#window.Map = function() {}; ```

and this rule kil video on page: 
 ``` tweaktown.com##iframe[src][width] ```

**Comment by Alex-302** [comment]
Added:
```
@@||pagead2.googlesyndication.com/pagead/osd.js$domain=tweaktown.com
@@||tweaktown.com^$generichide,content
@@||ad.doubleclick.net/ddm/ad/*$domain=tweaktown.com
@@||global.ssl.fastly.net/ad/script/x.js$domain=tweaktown.com,third-party
tweaktown.com#@#iframe[src][width]
```
