### ISSUE TITLE
Soundhound

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3065]
**Steps to reproduce the problem**:
* install SoundHound - https://play.google.com/store/apps/details?id=com.melodis.midomiMusicIdentifier.freemium
* When app tries to search song details an error message appear. If you press Retry it works.

**Adguard version**: 2.7.220

**Operating system**: Android 6.0.1

HTTP log - 
[debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/491472/debug.9.txt)

**Comment by Alex-302** [comment]
похоже баг
https://github.com/AdguardTeam/AdguardForAndroid/issues/805
