### ISSUE TITLE
http://m.photos.timesofindia.com  Anti adblocker problem

### ISSUE THREAD

**Issue by rajatmathurs** [AdguardTeam/AdguardFilters#3066]
Hi.

I have Adguard version: 2.7, Filters list: 1, 2, 3, 4, 13, Operating system: Android 6
I would like to report anti adblocker for the below link in Google chrome android.

http://m.photos.timesofindia.com/celebs/celeb-themes/celebs/celeb-themes/hottest-golfers/articleshow/48683227.cms

For your reference screenshot
<details>
![screenshot_20160925-193358](https://cloud.githubusercontent.com/assets/19775409/18815758/0c87577a-8357-11e6-97ed-b342eb13aa2c.png)

</details>

Please fix this anti adblocker issue

Thanks

**Comment by Alex-302** [comment]
please check
```
@@||timesofindia.com^$generichide
```

**Comment by rajatmathurs** [comment]
Yes the new filter worked.

Thanks  a lot

**Comment by Alex-302** [comment]
Added to mobile filter.
