### ISSUE TITLE
m.rus.delfi.ee - anti-adblock

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3067]
http://m.rus.delfi.ee/estonia/article.php?id=75709379

Source:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=53448364

**Comment by Alex-302** [comment]
Added to Mobile filter
```
delfi.ee#@#.adbanner
delfi.ee##.md-banner-placement
+
delfi.ee#%#Object.defineProperty(window, 'adblock_detect_run', { get: function() { return true; } });
```

**Comment by ministr91** [comment]
это мне?

**Comment by Alex-302** [comment]
оно уже в фильтре. Проверьте обновления.

**Comment by ministr91** [comment]
Вот еще проблема
http://www.javadecompilers.com/apk

**Comment by ministr91** [comment]
На несколько секунд пускает, потом надпись. Я не могу картинку сюда прикрепить, сайт не позволяет это сделать?

**Comment by ministr91** [comment]
Сюда кинул http://s019.radikal.ru/i616/1609/7c/5b5ae3600e89.png

**Comment by Alex-302** [comment]
Новую задачу откройте. Не стоит в кучу всё мешать.

**Comment by ministr91** [comment]
Я не умею. Можете сами открыть?

**Comment by ministr91** [comment]
Кстати, проблема не решена. Рекламу пропускает всю. http://s020.radikal.ru/i701/1609/69/11f8b46ecc4d.png

**Comment by Alex-302** [comment]
> Я не умею. Можете сами открыть?Это легко:)

<details>
![image](http://imagizer.imageshack.com/img923/250/oOBPfT.png)
</details>
Дальше заполняете шаблон(версия Адгарда, фильтры, как повторить, и скрины) и всё
<details>
![image](http://imagizer.imageshack.com/img923/6445/WvFoDw.png)
</details>

**Comment by Alex-302** [comment]
> Кстати, проблема не решена. Рекламу пропускает всю. http://s020.radikal.ru/i701/1609/69/11f8b46ecc4d.png

так это другая страница, не мобильная версия, на которой был детект блокировки. Почищу.

**Comment by ministr91** [comment]
Ок
