### ISSUE TITLE
Не получается войти

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#3068]
http://www.javadecompilers.com/apk вот сайт
Вот скрин http://s019.radikal.ru/i616/1609/7c/5b5ae3600e89.png
Пускает на несколько сек. Фильтры рус, англ и блк фильтр

**Comment by Alex-302** [comment]
Исправил. Алгоритм фильтрации качественный?(в расширенных настройках)
Название задачи должно содержать название сайта, и по желанию тип проблемы. Это на будущее.

**Comment by ministr91** [comment]
Нет, быстрый. На качественном тормозит сильно Nexus 5 Android 4.4.4
Так название сайта я дал, проблему указал

**Comment by Alex-302** [comment]
Очень странно, что на Nexus 5 тормозит. Тогда добавлю худший вариант в мобильный фильтр(возможна разблокировка рекламы).

> Так название сайта я дал, проблему указал

имеется в виду, что при создании следует придерживаться определённого формата. Предложенный шаблон тоже не стоило удалять, там только поля заполнить нужно.

**Comment by ministr91** [comment]
Что значит добавите худший вариант в мобильный фильтр? При качественном у меня станицы долго грузятся, чем при быстром. Вот что я имел в виду
Ну а насчет шаблона - тут же и так все понятно. Есть сайт, на него не зайти, блочат, вот и все.

**Comment by Alex-302** [comment]
> Что значит добавите худший вариант в мобильный фильтр?

там скрипт проверяет атрибуты элементов, и если определённый элемент скрыт, то срабатывает блокировка. Его можно обмануть только частично отключив сокрытие элементов, либо с помощью Javascript правила. Второй вариант я добавил в английский фильтр, на Дроиде он работать будет только при качественном алгоритме фильтрации. Первый вариант - только в мобильный фильтр.

**Comment by ministr91** [comment]
почему второй вариант в английском фильтре? Сайт же русский
Да и еще вопросик не по теме, когда примерно будет блокироваться реклама на ютубе? Смогли что-то с этим сделать?

**Comment by Alex-302** [comment]
> Сайт же русский

большинство посетителей - из англоязычных стран. Да и русскоязычного интерфейса не вижу.

> реклама на ютубе

они зашифровались сильно. Попробуйте с 4pda версию ютуба за начало этого года.

**Comment by ministr91** [comment]
Насчет рекламы - шифровка это плохо, но почему другие блокираторы рекламы, как вы, смогли заблочить рекламу? Может вам стоит у них взять алгоритм блокировки?

**Comment by Alex-302** [comment]
Какие другие? Мне известен способ только с изменением файлов системы(модуль xposed)
Речь же про приложение, а не сайт?

**Comment by ministr91** [comment]
все верно. У ваших аналогов блокировщиков реклама не работает в ютубе. Может у них идею блока возьмете?

**Comment by Alex-302** [comment]
Так назовите их.

**Comment by ministr91** [comment]
http://4pda.ru/forum/index.php?showtopic=180515
Это не блокировщик, но зато рекламы нет. А если нет, значит у них какой-то алгоритм есть

**Comment by Alex-302** [comment]
Как на зло у меня там реклама редко встречается)

**Comment by ministr91** [comment]
но единый алгоритм выработать можно. У вас же большая компания, кто-то да справится

**Comment by ministr91** [comment]
Что насчет этого отчета? https://github.com/AdguardTeam/AdguardForAndroid/issues/811

**Comment by Alex-302** [comment]
Завтра посмотрим.

**Comment by ministr91** [comment]
А в чем тут проблема может быть? Если отключить HTTPS для приложения, то все работает. Что не так?

**Comment by Alex-302** [comment]
Реклама разблокируется, если полностью исключать. Нужно найти ломающийся домен.

**Comment by ministr91** [comment]
Хорошо. Насчет проблемы с ютубе - она очень актуальна и я надеюсь, что вы сможете заблокировать рекламу а приложении
