### ISSUE TITLE
Detecting adguard 

### ISSUE THREAD

**Issue by InBlis** [AdguardTeam/AdguardFilters#30696]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***The Hindu website is detecting adgaurd***:
 URL: https://www.thehindu.com/ 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>
![Screenshot_2019-03-09 Breaking News, India News, Sports News and Live Updates](https://user-images.githubusercontent.com/23461491/54062900-05d12700-422f-11e9-8acd-a0cb6e57ee77.png)

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | ?
Browser:                               | Firefox
AdGuard version:                       | 7.0.2286.5847
Filters enabled:                       | Adguard annoyance + base
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | Default 
Stealth mode options (Windows only)    | Yes
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by InBlis** [comment]
+ In my search to remove the overlay I found a gem. Please see if any of this could be a part of adguard.
https://github.com/NicolaeNMV/BehindTheOverlay
First remove the popup and then this extension did the trick.

**Comment by AdamWr** [comment]
Please enable `AdGuard Annoyances filter` and update filters.
https://github.com/AdguardTeam/AdguardFilters/issues/30700

**Comment by InBlis** [comment]
It is working. Perfect. Thank you team 👍
