### ISSUE TITLE
animeflv.net

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#3069]
- Adguard extension
- Chrome
- standard filter list

" if you click in the page, a new page with the same url you are in opens and the current page turns into an ad"

**Comment by Alex-302** [comment]
Added to English filter
```
animeflv.net#%#Object.defineProperties(window, { "_impspcabe_alpha": { value: false, writable: false }, "_impspcabe_beta": { value: false, writable: false } });
```
