### ISSUE TITLE
http://asbook.net/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3071]
http://asbook.net/abooks/history/10079-nikolaevskie-monte-kristo-valentin-pikul.html#play

Application version: 1.0.8.54
Application lifetime: 2016-03-25 21:20:03 +0000

Device: iPhone
Platform: iPhone OS
OS: 10.0.2
ID: 41426C72-97DB-47B2-8755-80206DB0723D

Locale: ru
Region: by

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.95.22 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.74 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.89 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.39.68 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.33 Enabled=YES

<details>
![image1](https://cloud.githubusercontent.com/assets/15856304/18837399/4c6bb15a-840c-11e6-8b7b-ed7bce083480.png)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
asbook.net##div.mgline[class*="teaser-"]
```
