### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#30719]
Membership annoyance:

`https://www.youtube.com/watch?v=BGN8bP5uJvM`
![{F60736AA-4950-4EC4-AEB7-54C8C1CE81A1}](https://user-images.githubusercontent.com/35470489/54070774-17bcc500-4243-11e9-91e8-231d4b748291.png)

`https://www.youtube.com/channel/UCkJEpR7JmS36tajD34Gp4VA/videos`
![{817BD986-7A36-44AC-8394-8915D99C9BE1}](https://user-images.githubusercontent.com/35470489/54070778-38851a80-4243-11e9-985d-8b846b7640ad.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.4
Firefox 65

**Comment by krystian3w** [comment]
`##ytd-popup-container:has(>iron-dropdown:has-text(/wspieranie/i))`
`##ytd-popup-container:has(>iron-dropdown:has-text(/membership/i))`

**Comment by Alex-302** [comment]
Not reproduced. @BlazDT please take a look.

**Comment by krystian3w** [comment]
Try without logon @BlazDT.

**Comment by krystian3w** [comment]
For my this is deleted from YouTube - Google read `AdguardFilters` repo?

**Comment by BlazDT** [comment]
Not reproduced with and without login.

**Comment by adranger** [comment]
@mapx- Please check this with a clear container/profile.

**Comment by mapx-** [comment]
`youtube.com##.ytd-popup-container`

**Comment by krystian3w** [comment]
Again comeback?

**Comment by adranger** [comment]
It never went away for me.

**Comment by krystian3w** [comment]
`##ytd-popup-container > .ytd-popup-container > #contentWrapper > .ytd-popup-container[style_="BUBBLE_HINT_STYLE_BLUE_TOOLTIP"]`

how long youtube no change color or `style_` attrib.
