### ISSUE TITLE
http://www.syfy.com/ - videos won't play

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3072]
http://www.syfy.com/channelzero/blog/4-videos-countless-terror

![file_000](https://cloud.githubusercontent.com/assets/15856304/18840882/bf27f1c0-8418-11e6-92c3-487b89df8f48.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-09-17 19:34:16 +0000

Device: iPhone
Platform: iPhone OS
OS: 10.0.2
ID: 8E0DC032-12AF-42F6-ADB9-486301D827EC

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.71 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.72 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.70 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.4.6 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.27 Enabled=YES

**Comment by Alex-302** [comment]
Оно и без Адгарда не работает. Попроси юзера проверить.
