### ISSUE TITLE
http://www.wp.pl/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3073]
![file_000 1](https://cloud.githubusercontent.com/assets/15856304/18841238/bbc37d82-8419-11e6-8479-e83dece51a62.png)

<details>
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.95.5 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.74 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.61 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.4.27 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.94 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.33 Enabled=YES
ID=101 Name="EasyList" Version=1.0.62.85 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.65.80 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.62.99 Enabled=YES
ID=117 Name="Adblock Polska" Version=1.0.0.52 Enabled=YES

**Comment by Alex-302** [comment]
Фильтры полные или упрощённые? Это всегда нужно узнавать.
Adblock Polska год не обновлялся. Пусть попробует Adblock polskie reguly, как-то так называется.
