### ISSUE TITLE
Incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3074]
https://www.google.co.uk/aclk?sa=L&ai=DChcSEwiL_cqr8KzPAhVOte0KHfemADUYABAJ&sig=AOD64_24FyDQ5HFhcjVyqVNFw2XgHAbMxw&ctype=5&q=&ved=0ahUKEwiE3ser8KzPAhWpI8AKHVM7AzkQwg8IHA&adurl=

Why do we blocking this?

>Here's the link I clicked on which failed to open. I have put Google.co.uk and Ebay.co.uk in my whitelist, but still can't open this URL.

<details>

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.95.48 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.76 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.94 Enabled=NO
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.94 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.97 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.35 Enabled=YES
ID=101 Name="EasyList" Version=1.0.63.4 Enabled=NO
ID=118 Name="EasyPrivacy" Version=1.0.66.6 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.66.8 Enabled=YES

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||ebay.co.uk/itm/like/*&adgroupid=$domain=ebay.com|ebay.co.uk
@@||rover.ebay.com/rover/$domain=ebay.com|ebay.co.uk
@@||rover.ebay.co.uk/rover/$domain=ebay.com|ebay.co.uk
```
