### ISSUE TITLE
http://www.sports.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3075]
http://www.sports.ru/

![image1 1](https://cloud.githubusercontent.com/assets/15856304/18843526/08c6aaac-8422-11e6-908e-e05b194742a3.png)

<details>

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.95.3 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.74 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.80 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.39.55 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.33 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.65.91 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.65.92 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.62.77 Enabled=YES

**Comment by Alex-302** [comment]
Added to Safari filter
```
sports.ru###top-banner-place
sports.ru##.columns-layout__right > a[style^="display: inline-block !important;"] > img
```
