### ISSUE TITLE
http://www.hongkongairport.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3076]
http://www.hongkongairport.com/flightinfo/eng/chkfltarr.html

Screenshots
<details>
![image1 2](https://cloud.githubusercontent.com/assets/15856304/18843732/ef64f824-8422-11e6-948c-46b4d0c681bd.png)
![file_000 2](https://cloud.githubusercontent.com/assets/15856304/18843754/0de1eafa-8423-11e6-8295-7bdcca3c3239.png)

</details>

state 
<details>
Application version: 1.0.8.54
Application lifetime: 2016-09-25 09:27:48 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.5
ID: 098ECC75-DD9D-41C5-BF95-207D619C00EB

Locale: zh
Region: hk

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.95.39 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.75 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.92 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.4.40 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.33 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.66.30 Enabled=YES

**Comment by Alex-302** [comment]
Can't reproduce. Try to find a filter, which causes it.
