### ISSUE TITLE
Samsung info app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3077]
https://play.google.com/store/apps/details?id=org.vndnguyen.phoneinfo&hl=en

![1474815668204](https://cloud.githubusercontent.com/assets/15856304/18847795/3b01708a-8434-11e6-8bb8-078e8d0767fe.png)

Check here for the HTTP requests log: 1417056

<details>
  "dnsFilteringEnabled" : true,
  "enabledFilterIds" : [ 2, 3, 4, 10, 11, 223 ],
  "environment" : "release",
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "iconType" : "NONE",
SSL is on

**Comment by Alex-302** [comment]
У меня блокируется. Попроси переделать лог с полным закрытием приложения и очисткой кэша. В текущем логе мало информации.
