### ISSUE TITLE
https://uplod.ws

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#3078]
Hey.
in site https://uplod.ws
have popups, and anti adblock
exmple:
https://uplod.ws/0n1m2h4lq742

**Comment by Alex-302** [comment]
Added to English filter
```
uplod.ws##a[href^="http://earth-111.com/ref?"]
uplod.ws#%#Object.defineProperty(window, '_pop', { get: function() { return {}; } });
uplod.ws##.adsbygoogle
@@||uplod.ws^$generichide

```

**Comment by MrTal** [comment]
Hey,
the filter good but way no added this for English filter?

**Comment by Alex-302** [comment]
The rules are in the filter. Look the commit
https://github.com/AdguardTeam/AdguardFilters/commit/fbe4090722df640f1fef0f739c8969a4b180db26
But you ignored the template, and I don't know what browser, filters and Adguard version you are using.

**Comment by MrTal** [comment]
have me chrome
version adgurad me: 6.1.258.1302

**Comment by Alex-302** [comment]
Which filters are you using? Did you checked again?
