### ISSUE TITLE
http://al.ly/ anti adblock

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#3079]
Hey. 
in site: http://al.ly/
  have anti adblock
exmple:
http://al.ly/n6FBx
filter this solver:
`@@||al.ly^$generichide
`
`@@||popads.net^$domain=al.ly
`

**Comment by Alex-302** [comment]
Download is not working without Adguard.
Could you check it?

**Comment by MrTal** [comment]
I did not understand what you mean

**Comment by Alex-302** [comment]
Download button was inactive умуц without Adguard. Now it works.
The rule is added.
