### ISSUE TITLE
Yandex Search

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3080]
**С недавнего времени, поисковик [Яндекс](yandex.ru) стал тормозить (ставишь курсор в строку поиска, начинаешь набирать, а он тормозит) Отключаешь фильтрацию - все нормально становиться как и должно быть. Такая ситуация только с IE11. (Описана проблема пользователя, у меня, также повторилось).**

## **Фильтры:**

> Пользовательский
> Английский
> Фильтр счетчиков и систем аналитики
> Экспериментальный
> Фильтр раздражителей
> Русский
> 

**`OS: Windows 10 PRO Insider Preview Build 14926`**

**Comment by Alex-302** [comment]
А сильно тормозит? Такое вообще возможно из-за расширенных CSS правил.
У меня просто i7, может поэтому не замечаю.
Попробуй в редакторе фильтров вбить в поиск `[-ext-has=` и в русском фильтре выключить правила для yandex.ru/ua. Если тормозить перестанет, включай по одному до появления торможения. Тормозное правило скопируй сюда.

**Comment by Serzh-SUP** [comment]
@Alex-302 
Правило, которое явно влияет на тормоз:
`yandex.ru,yandex.ua,yandex.by##.sidebar-panel-view .home-panel-content-view__body > div:not([class]) > div[style*="!important"][-ext-has="div>a:contains(Яндекс.Директ)"]`

**Comment by Alex-302** [comment]
@Serzh-SUP если юзер из России, попроси отключить это правило и побродить по Яндекс Картам. Если не будет рекламы(она справа), то удалю это правило.

**Comment by Serzh-SUP** [comment]
@Alex-302 
Я кст. недавно зашел у себя и не обнаружил рекламу в картах, хотя была...Наверно удалять надо.

**Comment by Alex-302** [comment]
Ок, отключил пока.
