### ISSUE TITLE
dictionary.cambridge.org - cookie consent

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3081]
**Description**: dictionary.cambridge.org

Screenshot: 
<details>
![screen shot 2016-09-27 at 12 13 38 pm](https://cloud.githubusercontent.com/assets/14153331/18867275/403343d0-84ac-11e6-9de0-0ba2fc8e4027.png)
</details>

**Filters**
![screen shot 2016-09-27 at 12 17 00 pm](https://cloud.githubusercontent.com/assets/14153331/18867286/4d8d6cae-84ac-11e6-8710-85ea51007789.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
dictionary.cambridge.org##li[data-notification-id="cookiewarning"]
```
