### ISSUE TITLE
teletoonplus.pl

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#30823]
Chrome + Adguard extension 3.0.8
All filters without ABP Japanesee and all obsoletes.
Tested all on small filters too and on teletoonplus.pl is still some banner nc+ on top site.
![nc+](https://user-images.githubusercontent.com/16944478/54134961-2eb51000-4419-11e9-824b-db17bf6f1bbd.jpg)
Can I please fix problem?

**Comment by seba2282** [comment]
@AdamWr, Firefox Windows + Adguard Extension still see thabanner from nc+.

**Comment by AdamWr** [comment]
Nie potrafię tego odtworzyć.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/54679656-1ecbb900-4b08-11e9-82e2-ec5b97bd8265.png)

</details>

Ta reklama powinna być zablokowana przez `Podstawowy filtr AdGuard`.
`||services.ncplus.pl/belka/$domain=teletoonplus.pl`
`teletoonplus.pl###nctopcontainer`

**Comment by seba2282** [comment]
Ja ją cały czas widzę. Co ciekawe, Adguard jako na Windows nie ma problemu, ale jako rozszerzenie pokazuje mi to. Coś jest nie tak z tym blokowaniem przez dodatki w przeglądarkach.
![Bez tytułu](https://user-images.githubusercontent.com/16944478/54680792-0ad58680-4b0b-11e9-9b64-11308512ac38.png)
Zeby nie było. Na dowód wrzucam zrzut.

**Comment by AdamWr** [comment]
>I dodanie twojej reguły pomogło w pozbyciu się tego obiektu.

Te reguły są w filtrach AdGuarda, może sprawdź, czy `Podstawowy filtr AdGuard` jest włączony i spróbuj zaktualizować filtry.

**Comment by seba2282** [comment]
Jest aktualny z dzisiaj, ale bez twojej reguły jako filtr użytkownika nie blokuje mi tego baneru.

**Comment by AdamWr** [comment]
Jak wyłączysz wszystkie inne filtry i zostawisz włączony tylko `Podstawowy filtr AdGuard` to problem nadal występuje?

**Comment by seba2282** [comment]
Sprawdzę to za jakąś chwilę, bo teraz nie jestem na PC. I dam ci znać. Ale patrząc na cały raport filtrowania, nigdzie nie rzuciły mi się elementy blokujące ten banner.

**Comment by seba2282** [comment]
@AdamWr, aktywny teraz tylko Podstawowy Filtr Adguard i banner NC+ jest cały czas na teletoonplus.pl + wykrywanie Adblocker Adguard na stronie. To wykrywanie rozumiem, bo wyłączyłem wszelkie inne filtry, zostawiłem na moment ten nas interesujący i mało tego wyłączyłem ten try niewidzialności na wiarygodność testów.

**Comment by seba2282** [comment]
@AdamWr, po aktualizacji AG Firefox na PC mam cały czas ten sam problem. Co ciekawe udało mi się skonfigurować AG Firefox na Android (choć to było uciążliwe, bo cała przeglądarka potrafiła z tym dodatkiem się sama od siebie wyłączyć) i nie mam tam tego baneru. To tak, jakby jakaś reguła wyparowała dla PC w dodatku adguard firefox.

**Comment by seba2282** [comment]
Ten temat pozwolę sobie zamknąć, gdyż zgłosiłem bezpośrednio przez Adguard problem z tym paskiem NC+ i nie wiedzieć czemu cały czas go widzę nieodfiltrowanego. :)

**Comment by krystian3w** [comment]
#40202
