### ISSUE TITLE
thetimes.co.uk - annoyance

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3082]
**Description**: http://www.thetimes.co.uk/

Screenshot: 
<details>
![screen shot 2016-09-27 at 12 13 49 pm](https://cloud.githubusercontent.com/assets/14153331/18867319/72d32eae-84ac-11e6-9fea-89d1fabe8675.png)

</details>

**Filters**
![screen shot 2016-09-27 at 12 17 00 pm](https://cloud.githubusercontent.com/assets/14153331/18867286/4d8d6cae-84ac-11e6-8710-85ea51007789.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
##.CookieMessage

```
