### ISSUE TITLE
theguardian.com - cookie consent

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3083]
**Description**: https://www.theguardian.com/uk

Screenshot: 
<details>
![screen shot 2016-09-27 at 12 14 02 pm](https://cloud.githubusercontent.com/assets/14153331/18867373/9fe0fcb4-84ac-11e6-9f49-896ede2de2b6.png)

</details>

**Filters**
![screen shot 2016-09-27 at 12 17 00 pm](https://cloud.githubusercontent.com/assets/14153331/18867286/4d8d6cae-84ac-11e6-8710-85ea51007789.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
theguardian.com##.site-message--cookies
```
