### ISSUE TITLE
swindonadvertiser.co.uk

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3084]
**Description**: http://www.swindonadvertiser.co.uk/

Screenshot:
<details>
![screen shot 2016-09-27 at 12 39 31 pm](https://cloud.githubusercontent.com/assets/14153331/18868090/9ca5b30c-84af-11e6-9696-c0b896afa24e.png)
</details>

**Filters**
<details>
![screen shot 2016-09-27 at 12 40 13 pm](https://cloud.githubusercontent.com/assets/14153331/18868107/ad94ee1c-84af-11e6-83f5-072398ade6c4.png)
</details>

**Comment by Alex-302** [comment]
Added to English filter
```
@@||ad.doubleclick.net/ddm/ad/*$domain=swindonadvertiser.co.uk
```
