### ISSUE TITLE
m.market.yandex.ua

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3085]
**Description**: search and menu buttons won't work with Adguard enabled

Screenshot:
<details>
![screenshot_20160927-131210](https://cloud.githubusercontent.com/assets/14153331/18869689/103d9018-84b6-11e6-8aba-ccbd3db0dc37.png)
</details>

**Adguard version**:
2.7.220

**Filters list**:
enabledFilterIds" : [ 2, 3, 4, 14, 1, 11 ]
HTTPS is ON

**Operating system**:
Android 6

**Browser**:
Chrome, Yandex Beta

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||mc.yandex.ru/metrika/watch.js
```

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||mc.yandex.ru/metrika/watch.js$domain=m.market.yandex.ru|m.market.yandex.ua|m.market.yandex.by|m.market.yandex.kz
```

**Comment by dentra** [comment]
Does not work not only at m.market.yandex.ua, originally also at m.market.yandex.ru

**Comment by dentra** [comment]
Ok in filter. Thanks
