### ISSUE TITLE
anod-master.ru - no assistant

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3086]
**Current behaviour**: Assistant is not shown on the page, even though ads are blocked:
http://www.anod-master.ru/

Screenshot: 
<details>
![screen shot 2016-09-27 at 1 36 57 pm](https://cloud.githubusercontent.com/assets/14153331/18870044/9e5b8520-84b7-11e6-948d-ac9242df0be9.png)
</details>

**Comment by Alex-302** [comment]
Не инжектимся. Кривой HTML. C фильтрами не всязано.
