### ISSUE TITLE
Не входит на сайт

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#3087]
Много писать не буду, напишу кратко: не заходит на сайт, при попытке зайти , просит отключить эдблок. Фильтры всевозможные стоят, версия последняя. forums.overclockers.ru
Алекс, действуй

**Comment by Alex-302** [comment]
Писал же как оформлять.
"Фильтры всевозможные стоят," не подходит.

**Comment by ministr91** [comment]
но проблема то не в фильтрах. Разве на сайт с включенным эдгуардом заходит?

**Comment by Alex-302** [comment]
> но проблема то не в фильтрах. Разве на сайт с включенным эдгуардом заходит?

в данном случае именно в них. Скрипт обнаруживает блокировку и показывает заглушку, и комменты в статьях прячет.

**Comment by ministr91** [comment]
А что мне делать ? Как на сайт зайти? Что включить?

**Comment by evgeniy-ADG** [comment]
![screen shot 2016-09-27 at 7 45 00 pm](https://cloud.githubusercontent.com/assets/15856304/18883178/e8ca1d78-84ea-11e6-9d55-e848fe7eef8c.png)

<details>
![screen shot 2016-09-27 at 7 45 29 pm](https://cloud.githubusercontent.com/assets/15856304/18883208/fee8b83a-84ea-11e6-8214-8a0fe5f7d0e4.png)
![screen shot 2016-09-27 at 7 45 35 pm](https://cloud.githubusercontent.com/assets/15856304/18883209/ff0b76b8-84ea-11e6-8115-f7c4adcceafa.png)

**Comment by Alex-302** [comment]
Для начала нужно обновить фильтры. Исправление внесено. Если не поможет(маловероятно) - выключите два последних фильтра.

**Comment by evgeniy-ADG** [comment]
Обновил - заработало.

**Comment by ministr91** [comment]
Алекс,зачем 2 часа назад закрыл тему? Это не было исправлено, фильтры я 2 часа назад обновлял

**Comment by Alex-302** [comment]
На момент написания комментария, исправление уже находилось в фильтре.
Хоть и оформление неправильное, проблема не была проигнорирована. Внесенные изменения можно просматривать, щёлкнув на хэш, указанный стрелкой:
<details>
![image](http://imagizer.imageshack.com/img923/9506/Xbrjzo.png)
</details>

**Comment by ministr91** [comment]
Почему мне тут никто не отвечает? Проблема решена, можно закрывать. https://github.com/AdguardTeam/AdguardForAndroid/issues/811 
Кстати, что насчет моего предложения в той теме о внесении изменения в поиск лог Кэт?

**Comment by Alex-302** [comment]
> Проблема решена, можно закрывать.

Так днём же ещё закрыл.



> Кстати, что насчет моего предложения в той теме о внесении изменения в поиск лог Кэт?

Это уже не ко мне. Спросите в разделе Андроида, в AdguardTeam/AdguardForAndroid#811

**Comment by ministr91** [comment]
Днем? Утром. Час назад ровно. И закрылм не вы, а другой админ, который прочитал мое предложение и проигнорил меня. Кому можно написать еще?

**Comment by Alex-302** [comment]
Ну так вы не написали про какую задачу речь. 
Переспросите или лучше создайте там новую задачу про изменение/дополнение инструкции.

**Comment by ministr91** [comment]
Там же? Можно в этом разделе? Вы почаще отвечаете

**Comment by Alex-302** [comment]
Я мануал не могу править. Так что только там. В отдельной задаче ответят как руки дойдут.

**Comment by ministr91** [comment]
Создал. Можете в теме свое мнение высказать? Вероятность того, что мое предложение примут возрастет https://github.com/AdguardTeam/AdguardForAndroid/issues/818

**Comment by Alex-302** [comment]
Переименовал. Осмысленный заголовок с большей вероятностью привлечёт внимание нужных людей.

**Comment by ministr91** [comment]
Это хорошо, ну а вы пару строк напишите в комментах?

**Comment by ministr91** [comment]
@Alex-302 зря не написали свое мнение

**Comment by Alex-302** [comment]
C вами же согласились.

**Comment by ministr91** [comment]
Частично

**Comment by ministr91** [comment]
Алекс, меня игорят везде, что делать? 
https://github.com/AdguardTeam/AdguardForAndroid/issues/811
https://github.com/AdguardTeam/AdguardForAndroid/issues/818

**Comment by Alex-302** [comment]
Баги исправляют. Дойдут руки - дополнят.

**Comment by ministr91** [comment]
Алекс, столько времени прошло и ничего нет . сколько ждать?

**Comment by Alex-302** [comment]
Я не знаю. Инструкция по снятию логката - не самая приоритетная задача.

**Comment by ministr91** [comment]
Ладно с этой инструкцией, но эту ошибку можно было исправить https://github.com/AdguardTeam/AdguardForAndroid/issues/811 Играть невозможно. Вручную не хочется вносить, лучше через обнову автоматом

**Comment by Alex-302** [comment]
Так её в самом приложении исправили, новую версию подождать нужно. Исключение - лишь временное решение.
