### ISSUE TITLE
http://m.pc841.com/ ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3088]
http://m.pc841.com/shoujijiqiao/38409.html

![file_000](https://cloud.githubusercontent.com/assets/15856304/18875724/a5215a2a-84cf-11e6-81b3-ecf823918d67.png)

<details>
english, easylist china, others

**Comment by Alex-302** [comment]
Added to English filter
```
||cdnny.com^
```
