### ISSUE TITLE
wixsite.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#30893]
`https://shiroqueen01.wixsite.com/shiroqueen/single-post/2016/07/26/Cultura-Nipo-Kakigori-Raspadinha-de-gelo`
`https://shostkashans92.wixsite.com/shans`
`https://enzanseikotuin.wixsite.com/home`

Fixed bar at the top.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.4
Firefox 65

**Comment by zloyden** [comment]
try this 
`wixsite.com#$##WIX_ADS { display: none!important; }`
`wixsite.com#$##SITE_BACKGROUND { top: 0!important; }`
