### ISSUE TITLE
conjuga-me.net

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#30905]
`http://www.conjuga-me.net/`

Top cookie notice.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.4
Firefox 65

**Comment by adranger** [comment]
@AdamWr this has been changed:

![cookie](https://user-images.githubusercontent.com/35470489/82325499-bb5e4500-99b1-11ea-8f95-83a4ff7b8629.png)

**Comment by AdamWr** [comment]
Ok, fixed.
