### ISSUE TITLE
http://navcomic.com/ - anti-adblocker 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3091]
http://navcomic.com/

I am emailing you to report what I hope is a bug with AdGuard 2.3.8. I 
have noticed at even though I have AdGuard protection turned off on a 
site. I have attached two screenshots showing the same website with 
AdGuard with protection turned off and with AdGuard disabled completely. 
This has happened on multiple sites. Why is AdGuard blocking ads even if 
I have whitelisted the sites?

<details>
![with adguard protection off](https://cloud.githubusercontent.com/assets/15856304/18877244/4a3e7e34-84d5-11e6-84a3-60687731fb7c.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
navcomic.com##body > div#document-header > aside.widget.widget_text
```

**Comment by Alex-302** [comment]
Exclusion is works as expected"
<details>
![image](http://imagizer.imageshack.com/img924/5485/usfkz6.png)
</details>
