### ISSUE TITLE
http://www.familyhandyman.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3092]
http://www.familyhandyman.com/

<details>
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:116 Name: Wiltteri Url: https://raw.githubusercontent.com/wiltteri/wiltteri.txt/master/wiltteri.txt
</details>

<details>
![screen shot 2016-09-27 at 5 48 40 pm](https://cloud.githubusercontent.com/assets/15856304/18878805/aeb71632-84da-11e6-86b0-e144178f6927.png)
![screen shot 2016-09-27 at 5 48 49 pm](https://cloud.githubusercontent.com/assets/15856304/18878804/aeb4f6d6-84da-11e6-9e1a-651cacfa7f2c.png)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||ad.doubleclick.net/ddm/ad/*$domain=familyhandyman.com
@@||d3ujids68p6xmq.cloudfront.net/x.js$domain=familyhandyman.com
@@||familyhandyman.com$generichide
familyhandyman.com##.rd_mediakit
```
Added to Social filter
```
familyhandyman.com##.socialshare
```
