### ISSUE TITLE
http://www.newpct1.com/ - ads, pop ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3093]
http://www.newpct1.com/

![screen shot 2016-09-27 at 6 10 46 pm](https://cloud.githubusercontent.com/assets/15856304/18879651/d04ce03a-84dd-11e6-8656-e3746463b6b4.png)

Also, if you click anywhere, pop up opens 

<details>
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:9 Name: Spanish/Portuguese filter Url: http://adguard.com/ru/filter-rules.html?id=9
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:216 Name: Adblock polskie reguły Url: http://www.certyficate.it/adblock/adblock.txt

**Comment by Alex-302** [comment]
Added to English filter
```
||bezoya.work^$third-party
||bethoy.es^$third-party
newpct1.com##.pub728x90
newpct1.com#%#Object.defineProperty(window, '_pop', { get: function() { return {}; } });
newpct1.com#%#Object.defineProperty(window, 'PopAds', { get: function() { return {}; } });
newpct1.com##div[style*="width:300px;height:250px;"]

```
