### ISSUE TITLE
http://video.golem.de/ - false blocking, videos do not play

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3094]
http://video.golem.de/mobil/17705/googles-android-7.0-alias-nougat-test.html

![screenshot_20160927-094938](https://cloud.githubusercontent.com/assets/15856304/18882684/ec5903de-84e8-11e6-8004-e04059971fd4.png)

<details> 
"enabledFilterIds" : [ 2, 3, 4, 14, 6, 5, 11, 211 ],
FULL, HTTPS is on
Firefox

**Comment by evgeniy-ADG** [comment]
Customer reported that the the site detects adguard and blocks pages, but we couldn't reproduce this issue.

**Comment by Alex-302** [comment]
Try this rule:
```
@@://*.damoh.golem.de/$replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/,domain=video.golem.de
```
Copy-paste it to user filter.

**Comment by Vincent-Michael** [comment]
i use current:

```
||homad-global-configs.schneevonmorgen.com.s3.amazonaws.com/global_config.json$replace=/"enabled": true\,/"enabled": false\,/i,domain=golem.de
||damoh.golem.de^$replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/
```

**Comment by Alex-302** [comment]
Thanks. Added.

**Comment by Alex-302** [comment]
Removed:
```
://*.damoh.golem.de/$replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/,domain=video.golem.de
```

**Comment by Alex-302** [comment]
@evgeniy-ADG check it please
