### ISSUE TITLE
tvnturbo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [AdguardTeam/AdguardFilters#3095]
**Description**: ad block 

**Current behaviour**: hit play button 

Screenshot: use the following code

`http://www.tvnturbo.pl/aktualnosci,1850,n/dym-spod-naczepy-i-czolg-na-holu,212785.html`

**Expected behaviour**: movie should play 

**Steps to reproduce the problem**:

*  hit play button on movie 
 

**Adguard version**: PRO 1.1.0

**Filters list**: English, Spyware, Social, Safari, Polish, Reek, KAD filters

**Operating system**: iso 9.3.5

**Browser**: safari

**Comment by Alex-302** [comment]
> Current behaviour: hit play button

what does it mean? The button works. I don't understand. Please make a screenshot of the issue.

**Comment by xxcriticxx** [comment]
pressing play button gives me ad block 

![img_3351](https://cloud.githubusercontent.com/assets/15007183/18914917/06d118cc-855d-11e6-8ca4-1c49489c404e.PNG)

**Comment by Alex-302** [comment]
@xxcriticxx 
please check these rules
```
@@||cdntvn.pl/adscript.js?_=$domain=tvnturbo.pl
@@||cdn.behavioralengine.com/scripts/btest/advertisement.js$domain=tvnturbo.pl
@@||s.tvn.pl/tools/_ads/advert.js$domain=tvnturbo.pl
```

**Comment by xxcriticxx** [comment]
works thx!

any quick way to move this code in to iphone to PRO version? import option maybe?

**Comment by Alex-302** [comment]
You can copy-paste the rules.
Added them. Please check for updates in 1,5 hours
