### ISSUE TITLE
[NSFW] www.imagefap.com - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3096]
Пропущена реклама на сайте http://www.imagefap.com/pics/2/amateur.php
Скриншот: http://f5.s.qip.ru/OgbqisRB.png

Мои параметры:
* Win x64
* adguard в виде расширения у Chrome
* фильтры: русский, английский, RU AdList
* Dr.Web

**Comment by Alex-302** [comment]
Added to English filter
```
@@||ads.exoclick.com/*.php$domain=imagefap.com
```
