### ISSUE TITLE
Ads before the video cannot be blocked(youku.com)

### ISSUE THREAD

**Issue by MHzsz** [AdguardTeam/AdguardFilters#30978]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

# Ads before the video cannot be blocked

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>
https://v.youku.com/v_show/id_XMjgyNTcyNjAyOA==.html?spm=a2h0j.11185381.listitem_page1.5!8~A&s=3127efbfbd11250911ef

![BaiduShurufa_2019-3-14_14-1-3](https://user-images.githubusercontent.com/39558996/54334671-aaa19900-4661-11e9-9c27-edf27cf86f9c.png)

![BaiduShurufa_2019-3-14_13-52-53](https://user-images.githubusercontent.com/39558996/54334678-ae352000-4661-11e9-91cd-bc143c43ae34.png)

* **Expected behaviour**: 

昨天及以前都正常，广告不会被播放，没有声音和画面(昨晚win10有更新过）。
我尝试禁止用户过滤器，尝试关闭所有过滤器，一个个打开，都没有效果。

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |Win10 1803 17134.648
Browser:                               | Vivaldi 2.3.1440.60 (Stable channel) (64-bit)
AdGuard version:                       | 6.4.1814.4903
Filters enabled:                       | 用户过滤器，英语过滤器，日语过滤器，社交媒体插件过滤器，烦人过滤器，Adblock Warning Removal List, Malware Domains, Adguard DNS 过滤器，EasyList China
AdGuard DNS:                           |  Default 
Stealth mode options (Windows only)    |on
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced with AdGuard app.
