### ISSUE TITLE
http://seekingalpha.com/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3097]
http://seekingalpha.com/article/4008963-best-near-term-price-gains-ahead-big-pharma-stocks

![screen shot 2016-09-28 at 8 36 40 pm](https://cloud.githubusercontent.com/assets/15856304/18925126/50075048-85bb-11e6-86bc-65547cd9ea91.png)

<details>
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:9 Name: Spanish/Portuguese filter Url: http://adguard.com/ru/filter-rules.html?id=9
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:116 Name: Wiltteri Url: https://raw.githubusercontent.com/wiltteri/wiltteri.txt/master/wiltteri.txt

**Comment by evgeniy-ADG** [comment]
+ they detecting us:

![screen shot 2016-09-28 at 8 39 23 pm](https://cloud.githubusercontent.com/assets/15856304/18925213/ae973506-85bb-11e6-8060-3ffaddd6f0d3.png)

**Comment by Alex-302** [comment]
Both issues are not reproduced.

**Comment by evgeniy-ADG** [comment]
The second one is still there, just log in and browse the site for a couple of minutes, I am sure you'll see it:
![screen shot 2016-09-29 at 4 32 40 pm](https://cloud.githubusercontent.com/assets/15856304/18956010/7fd7966e-8662-11e6-9739-5f10b636246c.png)

**Comment by Alex-302** [comment]
I need remote access.

**Comment by evgeniy-ADG** [comment]
ok, let me know when you're ready.

**Comment by Alex-302** [comment]
I am ready.

**Comment by Alex-302** [comment]
@evgeniy-ADG

**Comment by evgeniy-ADG** [comment]
Doesn't occur on Win, will let you know when I'll get to my Mac.

**Comment by evgeniy-ADG** [comment]
Nope, it does.

**Comment by Alex-302** [comment]
Added to English filter
```
@@||ad.doubleclick.net/ddm/ad/*$domain=seekingalpha.com
@@||d3ujids68p6xmq.cloudfront.net^$domain=seekingalpha.com

```
