### ISSUE TITLE
[NSFW] http://www.xvideos.com/ - can't read comments

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3098]
http://www.xvideos.com/video20059907/la_masturban_con_un_desodorante_y_se_la_cojen_mientras_estan_en_el_parque_sin_audio_#_tabComments

![screen shot 2016-09-28 at 8 47 32 pm](https://cloud.githubusercontent.com/assets/15856304/18925475/cdb3c732-85bc-11e6-9e07-98b05472ae29.png)

<details>
Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:8 Name: Dutch filter Url: http://adguard.com/ru/filter-rules.html?id=8
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:109 Name: EasyList Italy Url: https://easylist-downloads.adblockplus.org/easylistitaly.txt
FilterId:113 Name: Liste FR Url: https://easylist-downloads.adblockplus.org/liste_fr.txt
FilterId:119 Name: Icelandic ABP List Url: http://adblock.gardar.net/is.abp.txt

**Comment by Alex-302** [comment]
Added to English filter
```
@@||xvideos.com/video-get-comments/
```
