### ISSUE TITLE
http://www.pogo.com/ - anti-adblock script

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3099]
http://www.pogo.com/games/bej3?intcmp=a_pg_hr_gme_bj3#game

![screen shot 2016-09-28 at 11 08 07 pm](https://cloud.githubusercontent.com/assets/15856304/18930366/7164fe60-85d0-11e6-9cdf-ad1a7f4d240b.png)

<details>
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10

**Comment by Alex-302** [comment]
It is not an adblock detection. Just countdown.
Fixed the padding
```
pogo.com#@##leaderboard-ad
```
For user filter:
```
pogo.com##iframe#egpGeniusPregameAd
pogo.com#$##egpGeniusGame { display: block!important; }
```
These rules will hide the countdown.
