### ISSUE TITLE
http://www.highbrewcoffee.com/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3100]
http://www.highbrewcoffee.com/our-coffee/#faq
![screen shot 2016-09-28 at 11 43 32 pm](https://cloud.githubusercontent.com/assets/15856304/18931576/71f28384-85d5-11e6-8b36-aab47ee4f0bb.png)

<details>

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.95.67 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.77 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.98 Enabled=NO
ID=12 Name="Safari filter" Version=1.0.1.40 Enabled=YES

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
highbrewcoffee.com##.ulp-overlay
highbrewcoffee.com##.ulp-window

```
