### ISSUE TITLE
http://www.sultanovic.net anti-adblock script

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3101]
http://www.sultanovic.net/forum/12-321-604

**Screenshot:**
![7afe02476bd9b49f38b3b28b21469279](https://cloud.githubusercontent.com/assets/16462533/18931612/9685c24c-85d5-11e6-8778-d1b6768d011f.png)

**Filters:**
Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский

**Comment by Alex-302** [comment]
Fixed
