### ISSUE TITLE
rutracker.cr -  Incorrect Blocking

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3102]
https://rutracker.cr/forum/viewtopic.php?t=1026542&start=30

**На этом форуме, в конце страницы остается поле, где находилась реклама. Самого баннера нет, но пользователю не нравится, что остается лишнее место. Проблему проверили и выявили, что рекламного баннера нет, но если на него навести курсор, то можно кликнув перейти по ссылке.**

Screenshot:
![6b648e5d1e208c13196a46d886824d1b](https://cloud.githubusercontent.com/assets/16462533/18953423/17a7fd8c-8657-11e6-9399-ba8e7d195d54.png)

Фильтры:

> Пользовательский
> Английский
> Фильтр счетчиков и систем аналитики
> Экспериментальный
> Фильтр раздражителей
> Русский

**Comment by Alex-302** [comment]
А почему Incorrect Blocking? Всё верно заблокировано.
Пустоту убрал.

**Comment by Serzh-SUP** [comment]
@Alex-302 
Будет в обновление фильтров или можно прям сейчас у себя убрать? У меня пока что пустота осталась.

**Comment by Alex-302** [comment]
Ну час подождать надо, пока фильтры пересоберутся.
Изменения фильтров можно смотреть щёлкнув на хэш справа(до или после моих сообщений)
<details>
![image](http://imagizer.imageshack.com/img922/1483/zSJpYV.png)
</details>
