### ISSUE TITLE
https://netzpolitik.org/ - annoaynce

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3104]
https://netzpolitik.org/2016/infografik-die-privatsphaereeinstellungen-von-facebook-richtig-nutzen/

Can we remove such self-advertising?

![image](https://cloud.githubusercontent.com/assets/15856304/18993973/7cb22a68-872e-11e6-9176-b7bea8d8865f.jpg)

eng, german, annoyances filters

**Comment by Alex-302** [comment]
I cant reproduce this message on Android and Safari with changed user agent.

**Comment by Alex-302** [comment]
For full site:
[CODE]
netzpolitik.org###spendenBanner
[/CODE]
