### ISSUE TITLE
http://www.hiendgear.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3105]
http://www.hiendgear.com/forum2/ultiweb.cgi?action=index

![screen shot 2016-09-30 at 4 56 59 pm](https://cloud.githubusercontent.com/assets/15856304/18994112/eca559bc-872e-11e6-926b-2db797be2816.png)

<details>

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.0.95.57 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.7.77 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.12.95 Enabled=YES

ID=1 Name="Russian filter" Version=1.0.39.91 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.1.38 Enabled=YES

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
hiendgear.com##body > center > a[rel="nofollow"] > img
```
