### ISSUE TITLE
http://yarportal.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3106]
http://yarportal.ru/forum256.html?prune_day=100&sort_by=Z-A&sort_key=last_post&st=27

![screen shot 2016-09-30 at 5 04 05 pm](https://cloud.githubusercontent.com/assets/15856304/18994306/ea11a420-872f-11e6-81cc-f2b851eb0c96.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-09-28 08:01:53 +0000

Device: iPad
Platform: iPhone OS
OS: 9.0.2
ID: 72671D01-F1DA-4C8B-8D1C-70F05F18A642

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.95.67 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.77 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.98 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.39.97 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.40 Enabled=YES

**Comment by Alex-302** [comment]
[COLOR="#0000FF"]Добавил в русский фильтр:[/COLOR]
[CODE]
yarportal.ru##iframe[width="480"][height="100"]
yarportal.ru###ipbwrapper > table#table1 > tbody > tr > td[width="50%"]
yarportal.ru###ipbwrapper > div[style$="height: 60px;"]
[/CODE]
Пожалуйста, проверьте результат.
