### ISSUE TITLE
http://forum.saransk.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3107]
http://forum.saransk.ru/index.php?app=core&module=search&do=user_activity&mid=18088

![image1](https://cloud.githubusercontent.com/assets/15856304/18999641/5a081446-8747-11e6-88d3-7f80ab96b97a.png)

<details>
Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.95.91 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.81 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.4 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.4.66 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.40.15 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.2 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.42 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.66.44 Enabled=YES

**Comment by evgeniy-ADG** [comment]
>Правила для блокировки

forum.saransk.ru##DIV[class="banner_zone_1"]
forum.saransk.ru##DIV[class="banner_zone_2"]
forum.saransk.ru##DIV[class="banner_zone_3"]

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
forum.saransk.ru##div[class^="banner_zone"]
```
