### ISSUE TITLE
Реклама в почте mail.ru | Ads on mail.ru

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#31088]
@sindzicat commented on [Sat Mar 16 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2511)

Здравствуйте. Сегодня зашёл в почту mail.ru и офигел: появился правый вертикальный блок с рекламой. Кому надо удалить, добавьте в пользовательский фильтр

```
e.mail.ru/api-proxy/rb-mimic/
```

и всё будет работать.

Андрей.

---

Hello!

Today I log in mail web interface from mail.ru and found the vertical right block with 2-3 ads. To remove this block just add a new rule in user filters:

```
e.mail.ru/api-proxy/rb-mimic/
```

It will fix this problem.

Best regards,
Andrey.

**Comment by Alex-302** [comment]
Перенёс в подходящий репозиторий.

**Comment by sindzicat** [comment]
Спасибо! Не знал о нём.

**Comment by XX-J** [comment]
Спасибо, но уже не работает. Есть ещё решения?

**Comment by sindzicat** [comment]
Работает вроде частично. То, что вылезает, лезет из инлайнового `<script>`. Вроде 9-го по счёту. Я пока не умею блочить такие скрипты. Как-нить займусь на днях.

**Comment by Alex-302** [comment]
У меня только пустые блоки, т.к. если их скрыть включается обфускация.

**Comment by XX-J** [comment]
[https://e.mail.ru/inbox/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://e.mail.ru/inbox/)

 У меня раньше скрывало это правило `e.mail.ru/api-proxy/rb-mimic/` **всю** рекламу в правой колонке, кроме самой, пустой колонки.

<details><summary>А теперь выглядит так:</summary>

![2019 05 30-1](https://user-images.githubusercontent.com/17948007/58615229-37eca500-82c3-11e9-8c1a-8d150f81f817.png)
</details><br/>

 Я нашёл пару способов, как скрыть правую колонку в режиме обфускации:

 **1**. В идеале должно быть так:

 `e.mail.ru##div:matches-css(margin-right: 256px) ~ div`
 `e.mail.ru#$#div:matches-css(margin-right: 256px) { margin-right: 0px!important; }`

 Но, из-за несовершенства работы указателя `:matches-css` , оговорённого в [#1345](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1345), эти правила пока не применимы.

 **2**. Остаётся второй вариант, который пока работает:

 `e.mail.ru##div:has(> div > div > div > span:contains(Пройти опрос))`
 `e.mail.ru#$#div:has(> div > div > div > div > span:contains(Пройти опрос)) > div:nth-child(2) { margin-right: auto!important; }`


 Но скрытие правой колонки приводит к чрезмерно медленной работе интерфейса почты, причём настолько, что работать в этом интерфейсе становится невозможно. Поэтому я временно отключил вышеозначенные правила.

 Думаю нужно искать решение в остановке или замедлении работы скриптов, отвечающих за попытки восстановления правой колонки, дабы разгрузить монотонную и бессмысленную борьбу между этими скриптами и AdGuard'ом.

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.1.0
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
да, расширенный CSS тут не помощник.
Проверь такое:
`#%#AG_setConstant('setTimeout', 'noopFunc');`
оно плохое, не для фильтров, но реклама вроде не может загрузиться.

**Comment by Alex-302** [comment]
ну всё равно так себе вариант. Для личного пользования)

**Comment by a-ladanov** [comment]
В ruadlist приняли смелое решение и режут полностью правый блок. Есть последствия в виде недоступности некоторых функций в правой части внутри письма, но если не пользуетесь ими, то можно применить правило `e.mail.ru##body.page .layout__column_right > :not(.feedback-banner)`

**Comment by XX-J** [comment]
Чтобы были доступны функции в правой части письма, нужно: `e.mail.ru#$#.layout__main-frame { z-index: 111!important; }`

 Но как это всё повлияет на обфускацию страницы? - время покажет.

**Comment by a-ladanov** [comment]
Появилось предложение пройти опрос "Как вам новая почта?" и вместе с ним вылезла реклама. Закрыл опрос - реклама исчезла)
На ruadlist изменения:
https://hg.adblockplus.org/ruadlist/rev/8d37d7d7ce81
Оставил в пользовательском эти правила, пока блокирует нормально:
```
e.mail.ru##.application-mail__wrap > .layout > .layout__main-frame ~ .layout__column_right
e.mail.ru#$#.layout__main-frame { z-index: 111!important; }
```
Можете подсказать как тут можно искать изменения правил по домену?
https://github.com/AdguardTeam/AdguardFilters/commits/master
На ruadlist очень удобно, а тут черт ногу сломит.

**Comment by a-ladanov** [comment]
С правилом `e.mail.ru##.application-mail__wrap > .layout > .layout__main-frame ~ .layout__column_right` второе уже не нужно. Верстку видимо поменяли.

**Comment by XX-J** [comment]
Здравствуй обфускация и "наш ответ Чемберлену":
`e.mail.ru##div:has(> div > div > div > div > div > .thread) ~ div`
`e.mail.ru#$#div:has(> div > div > div > div > div > .thread) { margin-right: auto!important; }`

**Comment by a-ladanov** [comment]
Можно еще попробовать
`e.mail.ru##+js(set-constant.js, Object.prototype.mimic, undefined)`

**Comment by ameshkov** [comment]
Между делом AdGuard Extra сейчас нормально режет там все:
https://github.com/AdguardTeam/AdGuardExtra/

Пока она не стала частью расширения, но через тамперманки можно ставить.

**Comment by ShaMAD** [comment]
Для VK WorkMail я решил проблему двумя фильтрами в Adblock Plus:
[e.mail.ru#?#div:-abp-has(>](http://e.mail.ru/#?#div:-abp-has(%3E) div.fill-parent)
[e.mail.ru#?#div>](http://e.mail.ru/#?#div%3E) div> div> div> div> div> div:-abp-contains(О Рекламодателе)
