### ISSUE TITLE
http://www.aargauerzeitung.ch/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3108]
http://www.aargauerzeitung.ch/aargau/kanton-aargau/weil-die-aargauer-justiz-patzt-kommt-ein-gewalttaetiger-somalier-frueher-frei-130612197

![screen shot 2016-09-30 at 9 21 00 pm](https://cloud.githubusercontent.com/assets/15856304/19002250/cd4a841e-8753-11e6-8839-3b9b4495d917.png)

<details>
eng +
![screen shot 2016-09-30 at 9 21 30 pm](https://cloud.githubusercontent.com/assets/15856304/19002262/df605192-8753-11e6-8907-c0ed70d51848.png)

**Comment by Alex-302** [comment]
Added to German filter
```
@@||aka-cdn-ns.adtech.de/dt/common/DAC.js$domain=aargauerzeitung.ch
```
