### ISSUE TITLE
fandom.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#31093]
`https://www.fandom.com/` 

App banner displayed to mobile users.

![fandom](https://user-images.githubusercontent.com/35470489/54476682-0f363280-47df-11e9-913b-50c616ee42c6.png)

Adguard Base + Annoyances + Mobile + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.4
Firefox 65 for Android

**Comment by Michael82548** [comment]
Since the Minecraft wiki changed domains, the bar no longer shows up for desktop users
