### ISSUE TITLE
http://allhentai.ru [NSFW]

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3111]
Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19018322/adb20ffc-8864-11e6-81da-7346c52ff1b6.png)
</details>

Happens on desktop as well

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.95.95 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.81 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.7 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.4.69 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.40.18 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.2 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.42 Enabled=YES

**Comment by Alex-302** [comment]
Done.
