### ISSUE TITLE
opitanii.net

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3112]
**Description**: Реклама вверху и внизу страницы
http://opitanii.net/story/sup-iz-krolika

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19019890/a43b9386-889f-11e6-8605-357e053e1332.png)
![image](https://cloud.githubusercontent.com/assets/18548949/19019891/ac001d26-889f-11e6-8712-2f20063a9f46.png)
</details>

**Filters list**: 1,2,3,4,14

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||opitanii.net/views/ajax$xmlhttprequest
```
