### ISSUE TITLE
climatempo.com.br

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3113]
Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19020964/4e76b6cc-88bf-11e6-840e-dd1e310fd1ef.png)
</details>

**Filters list**:
![image](https://cloud.githubusercontent.com/assets/14153331/19020968/6c6271ee-88bf-11e6-9990-2dc78f1c60b6.png)

**Comment by Alex-302** [comment]
Fixed.
