### ISSUE TITLE
Аномальное поведение сайта!

### ISSUE THREAD

**Issue by Big-U-Boss** [AdguardTeam/AdguardFilters#31132]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: Забивает полностью весь доступный ресурс ПК так,что сложно закрыть вовремя!

***Steps to reproduce the problem***:
http://igeek.ru/novosti/internet/59102-v-runete-na-86-snizilos-chislo-sajtov-s-agressivnoj-i-razdrazhayushhej-reklamoj.html

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Platform:                    | Ext
Browser:                               | Google Chrome 72.0.3626.121
AdGuard version:                       | 3.0.8
Filters enabled:                      | AdGuard Russian, AdGuard Annoyances, AdGuard Base, AdGuard Tracking Protection, AdGuard Social Media
Stealth mode options   | Hide your search queries, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Hide your Referrer from third-parties

**Comment by bogachenko** [comment]
@slavaleleka бля, чувак ты сайты смотришь сам или нет? ты типа по приколу закрываешь вопросы и лейбишь "Cant reproduce"? Проблему искать даже не надо, она на поверхности...
Вот майнер `igeek.ru/jquerys.js`
***

@Big-U-Boss можешь ознакомиться с этим https://github.com/uBlockOrigin/uAssets/issues/5638

и добавь в пользовательские фильтры это `||igeek.ru/jquerys.js$script` или это `igeek.ru#%#//scriptlet("abort-current-inline-script", "document.getElementById")`

**Comment by slavaleleka** [comment]
@bogachenko типа по преколу не закрываю — этот майнер уже блокируется базовым фильтром `.ru/jquerys.js`

**Comment by bogachenko** [comment]
я кажется опр**е**колился, алекс опять вернул этот фильтр
