### ISSUE TITLE
http://hostsfileseditor.weebly.com/

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3114]
We block the System Requirements section:
http://hostsfileseditor.weebly.com/

Screenshots: 
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19021018/df53b0d6-88c0-11e6-8c84-c8623c0dca1f.png)
![image](https://cloud.githubusercontent.com/assets/14153331/19021019/eda24044-88c0-11e6-99c8-4714bc3f8206.png)
</details>

Filters:
![image](https://cloud.githubusercontent.com/assets/14153331/19021023/067d1738-88c1-11e6-98d8-7f2020057c89.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
weebly.com#@##banner-wrap
```
