### ISSUE TITLE
http://www.sports.ru

### ISSUE THREAD

**Issue by dtitbd** [AdguardTeam/AdguardFilters#3115]
Неимоверная куча рекламы бк Марафон.
<details>
![](
![screenshot_2016-10-02-21-49-28](https://cloud.githubusercontent.com/assets/17032471/19022183/64e289be-88eb-11e6-92ba-80e361e86007.png)
)
</details>
**Adguard version**: 2.7.220

**Operating system**: Android (5.1.1)

**Browser**: Chrome

**Comment by Alex-302** [comment]
Проверил - чисто. Эту рекламу они показывают взамен гугловой. Есть три варианта:
- включена фильтрация DNS и она полностью блокирует рекламные домены гугла
- старые фильтры
- сторонний блокировщик.

**Comment by dtitbd** [comment]
Да, дело оказалось в dns фильтрации, без нее вроде чисто.
Я просто не до конца понимаю, что она делает, ибо не очень в этом разбираюсь. Но можно не объяснять особо, а ответить на вопрос: скажется ли на общем качестве фильтрации это отключение или нет?

**Comment by Alex-302** [comment]
Фильтрация DNS заворачивает запросы к заблокированным доменам на локальный IP, т.е. в Интернет эти запросы не попадают. Исключения конкретных адресов в этом случае могут не работать.
