### ISSUE TITLE
docs.fluentd.org - breaks navigation

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3116]
**Description**:
http://docs.fluentd.org/articles/install-by-deb

Try clicking the table of contents link.
Or try clicking on any link in the navigation sidebar.

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||in.treasuredata.com/js/v*/event/fluentd_website/anchor_clicks_$domain=docs.fluentd.org
```
