### ISSUE TITLE
www.prof-police.ru

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3117]
**Справа не блокируется баннер.**

http://www.prof-police.ru/gu-mvd-rossii-po-g-moskve/ugibdd/2193-sereznye-problemy-v-gai-i-ne-tolko.html

**Screenshot:**

![image1](https://cloud.githubusercontent.com/assets/16462533/19031733/777608da-895e-11e6-95de-f32bb7f87a9a.PNG)

**Adguard version**: 
PRO 1.1.1

**Filters list**:
Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский

**Operating system**:
iOS

**Browser**:
SAFARI

**Comment by Alex-302** [comment]
В упор не вижу баннеров.

**Comment by Serzh-SUP** [comment]
@Alex-302 
Баннера нет, есть справа пустое выезжающее поле, обрати внимание на Х справа и чуть ниже, как заканчивается название сайта prof-police.ru чуть ниже после u Х - Закрыть окно.

**Comment by Alex-302** [comment]
Ни первого, ни второго не вижу. Скриншоты кода нужны.

**Comment by Serzh-SUP** [comment]
@Alex-302 как получить код страницы на ios? Проблема появляется конкретно, когда я перехожу по ссылке ГУ МВД России по г. Москве - УГИБДД. На главной нет такого. На ноуте не получается воспроизвести. Или скрин сделать с ноута ?

**Comment by Alex-302** [comment]
Код можно с десктопа. Сайт же без мобильной версии?
Без блокировки на десктопе повторяется?
