### ISSUE TITLE
ecigtalk.ru - ads

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3118]
**Пропущена реклама**

http://www.ecigtalk.ru/usercp.php

Screenshot: 
![img_1365 2](https://cloud.githubusercontent.com/assets/16462533/19032192/0857a488-8961-11e6-8f28-d30a300267c1.PNG)

**CUSTOMER Adguard version**:
1.0.8.54

**MY Adguard version**:
PRO 1.1.1

**MY Filters list**:
Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский

**Customer Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.21 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.83 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.20 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.4.77 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.40.31 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.43 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.66.60 Enabled=YES

**Operating system**:
iOS

**Browser**:
SAFARI

**Comment by Alex-302** [comment]
Fixed
