### ISSUE TITLE
techshout.com

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3119]
Повторилось:
http://www.techshout.com/alternatives/2013/16/gopro-alternative/

**Скриншот пользователя:**
![image1](https://cloud.githubusercontent.com/assets/16462533/19032895/f4e8a2a4-8964-11e6-9ae3-4fb48626af23.PNG)

**Adguard version**:
1.0.8
**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.14 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.61 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.45 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.3.74 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.85 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.25 Enabled=YES

**Мой скрин:**

![img_1366](https://cloud.githubusercontent.com/assets/16462533/19032914/0b175444-8965-11e6-860f-8c6ef8bb5097.PNG)

Мой **Adguard version**:
PRO 1.1.1

Мой **Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.0.96.21 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.7.83 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.13.20 Enabled=NO

ID=14 Name="Annoyances filter" Version=1.0.4.77 Enabled=YES

ID=1 Name="Russian filter" Version=1.0.40.31 Enabled=YES

ID=5 Name="Experimental filter" Version=1.0.26.27 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.1.43 Enabled=YES

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||yuhuads.com^$third-party
```
