### ISSUE TITLE
techbang.com - Ad Leftover

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3120]
Судя по скриншоту, остались пустые места от рекламы. У меня повторилось, их там много, через каждые пост -два.

techbang.com

![img_0283](https://cloud.githubusercontent.com/assets/16462533/19033398/d73c09ce-8966-11e6-8e38-444d065eef4e.PNG)

**Мои фильтры:** 
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.14 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.61 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.45 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.3.74 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.85 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.25 Enabled=YES

**Comment by Alex-302** [comment]
Fixed.
