### ISSUE TITLE
Malware Domains

### ISSUE THREAD

**Issue by istvandavid** [AdguardTeam/AdguardFilters#31201]
**Missing Sites From Simplified Domain Name Filter**

### Malwares:

demdex.com
worldtxt.club
justgetlook.com
imgsolutix.com
pushokey.com
authorse.com
wshifen.com
haphetititletleres.club
cyneburg-yam.com
### 
### ADS
tutupop.com
zcoup.com
adthor.com
asdkd.tutuapp.com
asdkd-tutuapp-com.tutuapp.net
advertising.amazon.com

**Comment by Alex-302** [comment]
@istvandavid Hi. We need the sources of domains(ads only)
