### ISSUE TITLE
New specific filter for content farm in search results.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardFilters#31218]
@ameshkov 
@AdamWr 

content farm:
https://en.wikipedia.org/wiki/Content_farm

ex: Content Farm Terminator
https://chrome.google.com/webstore/detail/content-farm-terminator/lcghoajegeldpfkfaejegfobkapnemjl?hl=en-us

Now AdGuard can't block content farm.
There are many fake websites in search results.

Is it possible that AdGuard provides a specific filter for content farm?

B/R

**Comment by ameshkov** [comment]
@AdguardTeam/filters-maintainers thoughts?

**Comment by Alex-302** [comment]
I don't know what to do with it. We have a lot of these sites in Russian filter, but we block on them ads only.

**Comment by lancelot-moon** [comment]
I think the difficulty is content farm for other specific languages.

The fake websites of content farm include keywords which are searched by users.

You might have no such kind of database for Chinese and any other languages.

BTW, there are some content farm blockers on extensions store.

**Comment by Alex-302** [comment]
> The fake websites of content farm include keywords which are searched by users.

not all sites are fake. Many sites in top search result has foreign text, but rewrited, + a lot of ads..
