### ISSUE TITLE
http://www.snn.ir/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3122]
http://www.snn.ir/detail/News/490303/156

![image](https://cloud.githubusercontent.com/assets/15856304/19035138/51e9bf0a-8970-11e6-8841-dfb61294f972.png)

<details>
ilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:14 Name: Annoyances filter Url: http://adguard.com/ru/filter-rules.html?id=14
FilterId:222 Name: Adblock-Persian list Url: http://ideone.com/plain/K452p
FilterId:0 Name: User filter Url: no_url
Filtering

**Comment by Alex-302** [comment]
Fixed
