### ISSUE TITLE
[tube8.com] player and images blocked

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdguardFilters#31232]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: see title
* **Current behaviour**: player and images are blocked(site is broken)

[//]: # (Substitute this line with a description of the problem)

* **Expected behaviour**: player working,images visible

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

AG Base filter
AG Spyware filter
Easy Privacy
AG Social Media filter
AG Annoyances filter
Fanboy's Annoyances

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                     |  Win 10x64 
Browser:                             |  Slimjet 
AdGuard version:                      |   6.4.1814.4903
AdGuard DNS:                        | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Not reproduced, fixed ads and adblock message.
Please check @AdamWr

**Comment by Alex-302** [comment]
Also not reproduced. Which filter causes it?

**Comment by AdamWr** [comment]
I can't reproduce it too, other issues also not reproduced - https://github.com/AdguardTeam/AdguardFilters/issues/31233, https://github.com/AdguardTeam/AdguardFilters/issues/31234, https://github.com/AdguardTeam/AdguardFilters/issues/31235, https://github.com/AdguardTeam/AdguardFilters/issues/31236, https://github.com/AdguardTeam/AdguardFilters/issues/31238, https://github.com/AdguardTeam/AdguardFilters/issues/31239

**Comment by dnmTX** [comment]
same rule as #31238. Sorry guys.
