### ISSUE TITLE
[anyporn.com] broken player

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdguardFilters#31237]
***Description***: see title
* **Current behaviour**: player is broken,can't slide forward or backwards

[//]: # (Substitute this line with a description of the problem)

* **Expected behaviour**: fully working web player

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

AG Base filter
AG Spyware filter
Easy Privacy
AG Social Media filter
AG Annoyances filter
Fanboy's Annoyances

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                     |  Win 10x64 
Browser:                             |  Slimjet 
AdGuard version:                      |   6.4.1814.4903
AdGuard DNS:                        | None

**Comment by BlazDT** [comment]
Fixed

**Comment by dnmTX** [comment]
Thank you 👍
