### ISSUE TITLE
[jizzbunker.com] broken website

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdguardFilters#31234]
***Description***: site is completely broken(won't even open)

* **Expected behaviour**:  to be able to open and browse

***System configuration***

**Filters:**
AG Base filter
AG Spyware filter
Easy Privacy
AG Social Media filter
AG Annoyances filter
Fanboy's Annoyances

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  Win 10x64
Browser:                               |  Slimjet
AdGuard version:                       |  6.4.1814.4903

**Comment by BlazDT** [comment]
Fixed left-over, not reproduced. Please check @AdamWr

**Comment by dnmTX** [comment]
Same as #31238. Sorry again.
