### ISSUE TITLE
[xxxdan.com] broken website

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdguardFilters#31233]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: site is completely broken(won't even open)

* **Expected behaviour**:  to be able to open and browse

***System configuration***

**Filters:**
AG Base filter
AG Spyware filter
Easy Privacy
AG Social Media filter
AG Annoyances filter
Fanboy's Annoyances

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  Win 10x64
Browser:                               |  Slimjet
AdGuard version:                       |  6.4.1814.4903

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Fixed left-over, not reproduced. Please check @AdamWr

**Comment by dnmTX** [comment]
same rule as #31238 was causing it. Sorry.
