### ISSUE TITLE
http://dugtor.ru/ - fake download button

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3123]
http://dugtor.ru/programmy/sistema/20118-vit-registry-fix-pro-127-repack-portable-by-tryroom-multi-ru.html

![2016-09-28_170811](https://cloud.githubusercontent.com/assets/15856304/19035568/edb7c2ae-8972-11e6-8489-304769b022a4.png)

![2016-09-28_170811 2](https://cloud.githubusercontent.com/assets/15856304/19035610/30ee5894-8973-11e6-9f6e-ceeb80690c7b.png)

**Comment by Alex-302** [comment]
Fixed.
