### ISSUE TITLE
[zmovs.com] player and images blocked

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdguardFilters#31235]
***Description***: see title
* **Current behaviour**: player and images are blocked(site is broken)

[//]: # (Substitute this line with a description of the problem)

* **Expected behaviour**: player working,images visible

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

AG Base filter
AG Spyware filter
Easy Privacy
AG Social Media filter
AG Annoyances filter
Fanboy's Annoyances

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                     |  Win 10x64 
Browser:                             |  Slimjet 
AdGuard version:                      |   6.4.1814.4903
AdGuard DNS:                        | None

**Comment by BlazDT** [comment]
Also not reproduced here, please check @AdamWr

**Comment by dnmTX** [comment]
same as #31238.
