### ISSUE TITLE
[vivud.com] player and images are blocked

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdguardFilters#31238]
***Description***: see title
* **Current behaviour**: player and images are blocked(site is broken)

[//]: # (Substitute this line with a description of the problem)

* **Expected behaviour**: player working,images visible

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

AG Base filter
AG Spyware filter
Easy Privacy
AG Social Media filter
AG Annoyances filter
Fanboy's Annoyances

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                     |  Win 10x64 
Browser:                             |  Slimjet 
AdGuard version:                      |   6.4.1814.4903
AdGuard DNS:                        | None

**Comment by BlazDT** [comment]
Player and images are working fine when I try. Fixed ad left-overs.
@AdamWr please check.

@dnmTX 
Is it working if you disable Stealth mode?

**Comment by dnmTX** [comment]
@BlazDT ok,let me apologize here on this one first.Looks like i had a custom rule set to be activated on each site and stop that script(if any):
![Capture](https://user-images.githubusercontent.com/34774426/54621338-9b419780-4a35-11e9-892d-f0357ab45efe.PNG)

Usually i doesn't cause any problems but unfortunately on that specific website it won't let neither the videos or images trough.I exemed this site from the rule and it's working.
I'll recheck the rest of the issues that i posted earlier for the same problem and report.
Unless you have more questions you can close this one and sorry again.

**Comment by dnmTX** [comment]
One more question if you don't mind.
So the original rule looked like this:
`$$script[tag-content="(function(i,s,o,g,r,a,m)"]`
and in order to whitelist that site i did this way but i'm not sure that it will just whitelist that particular site or the rule will just stop working all together.Can you please advise:
`~vivud.com$$script[tag-content="(function(i,s,o,g,r,a,m)"]`

**Comment by dnmTX** [comment]
Ok,i'm closing this.Just one(#31239) left that needs fixing.Thanks again and very sorry for the false alarms.

**Comment by BlazDT** [comment]
Your exclusion rule is correct. It means it will apply the rule to every site except the ones with ~ in front of it.
