### ISSUE TITLE
[hdzog.com] player not loading

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdguardFilters#31239]
***Description***: see title
* **Current behaviour**: player stuck on **Loading...**

[//]: # (Substitute this line with a description of the problem)

* **Expected behaviour**: working web player

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

AG Base filter
AG Spyware filter
Easy Privacy
AG Social Media filter
AG Annoyances filter
Fanboy's Annoyances

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                     |  Win 10x64 
Browser:                             |  Slimjet 
AdGuard version:                      |   6.4.1814.4903
AdGuard DNS:                        | None

**Comment by BlazDT** [comment]
Not reproduced, fixed ad text.
@AdamWr please check.

**Comment by dnmTX** [comment]
I tried with AG disabled fully and the player started working but just sound,no video was showing at all.
I don't know what to make of it.

**Comment by dnmTX** [comment]
Ok,this is what i discovered so far:
Video was stuck on **Loading...** because of that rule:
`||hdzog.com^$~third-party,xmlhttprequest` (Adguard Base Filter) which was blocking `member.hdzog.com`
by whitelisting it: `@@||member.hdzog.com^$xmlhttprequest,domain=hdzog.com,important`
the video started working,all good but once you click on the **PLAY** button and there was a **POPUP**
right away from `go.ero-advertising.com` so in order to stop it i had to block one of the inline scripts:
`hdzog.com$$script[tag-content="adver('popunder', {"]` and so far so good.
I hope this will help narrow it down at your end.

**Comment by BlazDT** [comment]
member.hdzog.com is not blocked when I visit the site.

**Comment by dnmTX** [comment]
![Capture](https://user-images.githubusercontent.com/34774426/54631224-8ff86700-4a49-11e9-9a7a-79fe8dcaf084.PNG)

I'm not imagining.It's definitely getting blocked by one of the base rules.

**Comment by dnmTX** [comment]
> member.hdzog.com is not blocked when I visit the site.

@BlazDT don't just visit the site but try to watch some video.I think that's when it's happening as that domain is linked to fetch the video.

**Comment by BlazDT** [comment]
Tried with user agent and still no block.

Does this rule work for you?

@@||member.hdzog.com/get_file^

**Comment by dnmTX** [comment]
@BlazDT  yes it's working and the good thing is that there are no popups showing **BUT** only  if i disable
the rule: `||hdzog.com^$~third-party,xmlhttprequest` from Adguard Base Filter. If that rule is active it's still the same like before(player stuck on loading...). 
I would suggest to remove it completely and add that new rule that you suggested in your last post.

**Comment by BlazDT** [comment]
Do we still need this rule @dnmTX ?

**Comment by dnmTX** [comment]
Of course we do.Nothing really changed since my last post. You requested review from what i can tell here:
https://github.com/AdguardTeam/FiltersRegistry/pull/178
I'm not sure what is the hold up from the reviewers but this commit should've been merged long time ago.
