### ISSUE TITLE
[Extension] http://turbobit.net/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3124]
http://turbobit.net/download/free/6t4d1qnkvjsp#

![image](https://cloud.githubusercontent.com/assets/15856304/19035727/06d1cac2-8974-11e6-9bcb-1601899ddb29.png)

<details>
English filterVersion 1.0.96.21. Updated 2 october 2016 at 21:00.
Russian filterVersion 1.0.40.32. Updated 3 october 2016 at 14:04.
Liste FRVersion 1.0.66.66. Updated 3 october 2016 at 13:32.

Original report was about ads:

![2016-09-28_170811 3](https://cloud.githubusercontent.com/assets/15856304/19035745/216746aa-8974-11e6-88a2-6ebd9a96443e.png)

**Comment by Alex-302** [comment]
1) Что не так?
2) У меня чисто.
Убрал огрызок на странице загрузки.

**Comment by Alex-302** [comment]
У меня без проблем загружалось. Проблема только с Liste FR?

**Comment by evgeniy-ADG** [comment]
Не повторяется уже ничего. Дома еще раз попробую.
