### ISSUE TITLE
RadioClient Lite

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3126]
**Description**: Реклама. Можно ее убрать?
https://play.google.com/store/apps/details?id=com.itvasoft.radiocent&hl=en

Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19040505/055396ee-898d-11e6-9832-7acdeebd494c.png)
</details>

versionName" : "2.7.220"
**Filters list**: 2, 3, 4, 5, 14, 1, 11, 211
"filteringQuality" : "FULL",
"proxyMode" : false

Записан лог с ХТТП запросами
время 12:20
[debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/506427/debug.txt)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не уверен, что её можно убрать. Она их собственная, возможно встроена.

**Comment by Alex-302** [comment]
Так и есть, встроена.
