### ISSUE TITLE
Custom rules fotostrana

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3127]
Нужно убрать для пользователя данные блоки в сообщениях на фотостране
fotostrana.ru

Screenshot:
<details>
![screenshot_38](https://cloud.githubusercontent.com/assets/18548949/19047396/42751724-89aa-11e6-92ae-a5593bedc60b.jpg)
![image](https://cloud.githubusercontent.com/assets/18548949/19050269/8c08f35e-89b6-11e6-9430-b1ba7a9ef306.png)

</details>

Зарегистрироваться на сайте можно с любой соц сети. Затем нужно написать кому-то сообщение.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Там же помощник отлично справится. Для удобства можно включить опцию "Блокировать похожие элементы"
По первому нужно просто написать `fotostrana.ru##.текст_указанный_стрелкой' Т.е имя класса подставить.
По второму аналогично
<details>
![image](http://imagizer.imageshack.com/img924/5637/Bwb2Vu.png)
</details>

**Comment by shurmosha** [comment]
![8](https://cloud.githubusercontent.com/assets/17802561/19105879/1e3828f8-8aed-11e6-8977-69429274bd92.PNG)
они мне ответили  с команды агуард и прислали правило для фотостраны-  fotostrana.ru##.div.fsm_gift_holiday
сказали внести его в пользовательский фильтр и перезагрузить сообщения..я даже и комп перезагрузил-ноль эмоций

**Comment by Alex-302** [comment]
Ок, когда будет одноклассники смотреть, этот сайт тоже глянем.
