### ISSUE TITLE
promo.maximarkets.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3128]
**Description**:
http://promo.maximarkets.ru/demo-real/

При нажатии в указанную область дважды, открывается новая вкладка  другим сайтом
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19048925/fb6020e8-89b0-11e6-96fe-74b2ae022d5f.png)
</details>
 
**Filters list**: 1,2,3,4,14

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
