### ISSUE TITLE
http://www.java-programmieren.com/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3130]
http://www.java-programmieren.com/

![image](https://cloud.githubusercontent.com/assets/15856304/19066394/bf636502-8a21-11e6-91cf-6365f8c60737.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-04-16 20:28:27 +0000

Device: iPhone
Platform: iPhone OS
OS: 10.1
ID: 18222FEE-30D9-4630-A5A2-48D4E5D33C0A

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.30 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.87 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.24 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.4.83 Enabled=YES
ID=6 Name="German filter" Version=1.0.27.64 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.6 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.43 Enabled=YES

**Comment by Alex-302** [comment]
Fixed
