### ISSUE TITLE
com.cricbuzz.android.vernacular - doesn't work on first start

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3131]
https://play.google.com/store/apps/details?id=com.cricbuzz.android.vernacular

![screenshot_20161004-122014](https://cloud.githubusercontent.com/assets/15856304/19069178/7166a60e-8a2e-11e6-8131-65166869e5bc.png)

eng, spyware, social media, annoyances, russian, mobile

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||ads.cricbuzz.com/adserver/units/mobile/set_ads_values.php
```
