### ISSUE TITLE
http://www.ecigtalk.ru/forum - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3132]
http://www.ecigtalk.ru/forum

![screenshot_20161003-221609](https://cloud.githubusercontent.com/assets/15856304/19072628/f6fb8dc4-8a3e-11e6-8337-f1826697c953.jpg)

<details>
eng, ru, mobile, spyware, annoyances, also reproduced on windows

**Comment by Alex-302** [comment]
> also reproduced on windows

a you sure? It is clean on my end. I see only one small banner.

**Comment by evgeniy-ADG** [comment]
Well, yeah, I am sure that I saw ads on the win machine yesterday.

**Comment by evgeniy-ADG** [comment]
![screen shot 2016-10-05 at 8 14 24 am](https://cloud.githubusercontent.com/assets/15856304/19101814/df24baf0-8ad3-11e6-8674-d62107745d01.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
ecigtalk.ru##.forumbit_post p.forumdescription > a[rel="nofollow"] > img
ecigtalk.ru##div#content > div[style="margin-top:20px;"] a > img

```
