### ISSUE TITLE
sh.st

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#3133]
Hey
i no can pass page in click on "skip this as" nothing happened
i checked and without this yes work
exmple:
http://sh.st/BrH0i

**Comment by Alex-302** [comment]
It works on my end.

**Comment by MrTal** [comment]
oh i worn in exmple,
for me  this no work in all browser and without adgurad this work

**Comment by Alex-302** [comment]
You did not provided any information.

**Comment by MrTal** [comment]
see:;
https://i.gyazo.com/0769ac5f647822d2864c3364175a2b7b.gif

**Comment by Alex-302** [comment]
Please press New issue button and read the template. There is a list of required information.

**Comment by MrTal** [comment]
I removed adguard and Installations and now this work

**Comment by MrTal** [comment]
this again no work...

**Comment by MrTal** [comment]
Expected behaviour: Hey
i no can pass page in click on "skip this as" nothing happened
i checked and without this yes work, this only adgurad happened and i try disable filer "English filter" and this no work, only when i disable protection this yes work.

Screenshot: https://i.gyazo.com/0769ac5f647822d2864c3364175a2b7b.gif
Steps to reproduce the problem: on clic in "skip ads" nothing happened.

Adguard version: 6.1.258.1302.

Filters list: EasyList Hebrew, EasyList Privacy,English Filter.

Operating system: Windows 10.

Browser: Google Chrome 53.0.2785.143.

**Comment by Alex-302** [comment]
Strange. Still can't reproduce with your config. Could you provide me remote access via TeamViewer?
