### ISSUE TITLE
https://soundcloud.com/ - cookies notification

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3134]
https://soundcloud.com/greenqueenmusic/the-gentlemen-callers-of-la-2
![screen shot 2016-10-05 at 8 52 08 am](https://cloud.githubusercontent.com/assets/15856304/19102484/45c1b9d4-8ad9-11e6-981c-c5341b683206.png)

<details>
![screen shot 2016-10-05 at 8 54 31 am](https://cloud.githubusercontent.com/assets/15856304/19102496/59ccc978-8ad9-11e6-839d-8fe3af166640.png)

**Comment by Alex-302** [comment]
Fixed
