### ISSUE TITLE
audioboo.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3135]
**Description**:
audioboo.ru/alfavit

Всплывает рекламный браузер. У меня не повторяется. Чистка кэша и данных не помогла.

log
[debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/510157/debug.txt)
время проблемы 05.05 (по Алматы)

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19102489/5193b884-8ad9-11e6-8471-696bd52b38f5.png)
</details>

**Steps to reproduce the problem**:

* Перейти по ссылке
*  Выбрать букву "В"
*  Далее в новом окне выбрать "васильев андрей" и после чего опять всплыл рекламный баннер, который закрыл весь экран

**Adguard version**: 2.7.220

**Filters list**: 2, 3, 4, 14, 10, 1, 11
filteringQuality" : "FULL"

**Browser**: Встроенный

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Поправил в русском фильтре.
