### ISSUE TITLE
www.wp.pl

### ISSUE THREAD

**Issue by kulfoon** [AdguardTeam/AdguardFilters#31356]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Breakage - locked page due to a missing scroll-bar.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![ss542](https://user-images.githubusercontent.com/43844449/54745660-569b3500-4bca-11e9-8f2b-ef99af396801.png)

</details><br/>

* **Expected behaviour**: 

The scroll bar should appear, and the page unblocked.

<details><summary>Screenshot:</summary>

![ss543](https://user-images.githubusercontent.com/43844449/54745751-9d892a80-4bca-11e9-9691-86bf91c4050a.png)

</details><br/>

***Steps to reproduce the problem***:

Visit the website.

***System configuration***

**Filters:**

uBO default + AdGuard Base filter

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 7 SP1 64bit
Browser:                               | Firefox 66 64bit (on Opera 58 64bit the scrollbar disappear and then after several seconds appear)
AdGuard version:                       | uBlock Origin 1.18.9rc2

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by gaaargull** [comment]
ref https://github.com/MajkiIT/polish-ads-filter/issues/7533
