### ISSUE TITLE
http://www.schieb.de/ - anti-adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3136]
http://www.schieb.de/

![screen shot 2016-10-05 at 9 09 37 am](https://cloud.githubusercontent.com/assets/15856304/19102769/78b2412c-8adb-11e6-8c33-ebdfc20babb0.png)

<details>

![screen shot 2016-10-05 at 8 54 31 am](https://cloud.githubusercontent.com/assets/15856304/19102770/7a8381d2-8adb-11e6-9934-e5ffeb881eb6.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
schieb.de##div[id][class][style*="opacity: 1; visibility: visible; background: rgb"]
schieb.de##body > div[style] > div[class][style^="display: block; cursor: pointer; background: rgba"]
schieb.de#%#document.cookie = "anCookie=true";

```
