### ISSUE TITLE
http://www.klamm.de/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3137]
![image1 1](https://cloud.githubusercontent.com/assets/15856304/19102819/c23ac936-8adb-11e6-89c8-ad2638c03b3a.png)
![image3](https://cloud.githubusercontent.com/assets/15856304/19102821/c422e3f0-8adb-11e6-9d3b-aa960e267d92.png)

<details>
![screen shot 2016-10-05 at 8 54 31 am](https://cloud.githubusercontent.com/assets/15856304/19102824/cadddc4a-8adb-11e6-9ee3-3d475cdb4d5b.png)

**Comment by Alex-302** [comment]
Added to German filter
```
klamm.de##.centerX > a > img[style]
```
№2 is a register button
