### ISSUE TITLE
https://www.linuxfoundation.org/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3138]
https://www.linuxfoundation.org/

![screen shot 2016-10-05 at 9 20 44 am](https://cloud.githubusercontent.com/assets/15856304/19103029/18888728-8add-11e6-81e3-e3026970bc4c.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-04-16 20:28:27 +0000

Device: iPhone
Platform: iPhone OS
OS: 10.1
ID: 18222FEE-30D9-4630-A5A2-48D4E5D33C0A

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.32 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.87 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.24 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.4.84 Enabled=YES
ID=6 Name="German filter" Version=1.0.27.64 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.6 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.43 Enabled=YES

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
linuxfoundation.org##.sliding-popup-bottom

```
