### ISSUE TITLE
http://ok-tv.org/ - fullscreen ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3139]
http://ok-tv.org/channels/36-ntn-ukraina.html

![file_000](https://cloud.githubusercontent.com/assets/15856304/19105196/6fab9cf0-8ae9-11e6-9c74-aadfd38fc4a6.png)

<details>

eng / spyware / social / russian / spanish / mobile / safari / use simplified - no

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||ok-tv.org/images/banner_ipone.jpg
||ok-tv.org/ruuc.js
ok-tv.org##a[href^="https://ad.admitad.com/"]
```
