### ISSUE TITLE
ecigtalk.ru 

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3140]
**Description**:
ecigtalk.ru/forum
Внизу страницы реклама

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19105553/3a0ff486-8aeb-11e6-82bb-2c1f22d3e714.png)

</details>

**Filters list**: 1,2,3,4,14,11

**Browser**: встроенный, опера

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
ecigtalk.ru##.body_wrapper > div:not([id]) a[rel="nofollow"] > img
ecigtalk.ru##.body_wrapper > div:not([id]) > a > img[style^="width: 450px;"]

```
