### ISSUE TITLE
http://updato.com/ - anti-adblock annoaynce

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3141]
http://updato.com/firmware-archive-select-model?record=BD18000387CB11E69B2DFA163EE8F90B

![screen shot 2016-10-05 at 12 23 31 pm](https://cloud.githubusercontent.com/assets/15856304/19107788/91dd5784-8af6-11e6-8677-611819192951.png)

<details>
![screen shot 2016-10-05 at 8 54 31 am](https://cloud.githubusercontent.com/assets/15856304/19107796/9b6daa92-8af6-11e6-8349-ac090a189464.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
updato.com##.blocker-popup

```
