### ISSUE TITLE
http://www.lucianne.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3142]
http://www.lucianne.com/

![screen shot 2016-10-05 at 1 31 14 pm](https://cloud.githubusercontent.com/assets/15856304/19109894/08a5b0e2-8b00-11e6-9092-d51d9bb1ec80.png)

Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:104 Name: EasyList China Url: https://easylist-downloads.adblockplus.org/easylistchina.txt

**Comment by Alex-302** [comment]
Added to English filter
```
lucianne.com##table[width="728"][height="119"]
lucianne.com##table[width="180"][height="630"]
lucianne.com##table[width="300"][height="290"]
||luc.sslimages.com^$domain=lucianne.com

```
