### ISSUE TITLE
ndtv.com(breakage)

### ISSUE THREAD

**Issue by ghajini** [AdguardTeam/AdguardFilters#31432]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
***Try Indian IP with given setup***
@Alex-302
***Description***:

URLs where issue occurs-
All news content at 

`ndtv.com`

`khabar.ndtv.com`

`sports.ndtv.com`

`gadgets.ndtv.com`

`food.ndtv.com`

`swirlster.ndtv.com`

* **Current behaviour**: 

[//]: # (legit news content is blocked by taboola filter in adguard filters )

Screenshot- how do I show content which is hidden
* **Expected behaviour**: 

1. There should be unblock of legit content of taboola

![Screenshot_2019-03-22-23-15-42-959_org mozilla firefox](https://user-images.githubusercontent.com/20338483/54842708-8c274780-4cca-11e9-96bc-785fe437971a.png)

***Steps to reproduce the problem***:

[//]: # (Go here

1. Eg
https://www.ndtv.com/entertainment/these-adorable-pics-of-taimur-are-the-perfect-cure-for-your-holi-hangover-2011371?pfrom=home-lateststories

2. Unblock taboola completely in order to display legit news content provided by taboola......
3. Reload page
4.this is legit news content

![Screenshot_2019-03-22-23-15-42-959_org mozilla firefox](https://user-images.githubusercontent.com/20338483/54842732-9cd7bd80-4cca-11e9-92f8-f9ce5d295126.png)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Operating system: android

Operating system version - Android 7

Browser:  
Firefox browser for android

AdGuard version:  
adguard browser extension 3.0.10 Firefox Android

Filters enabled: 
 adguard base filter
                              Adguard mobile ads filter
                             Adguard tracking  protection filter
                              Malware domains
                             No coins filter list

**Comment by ghajini** [comment]
Fix is apparently
@@||taboola.com$domain=ndtv.com,third-party
@Alex-302

**Comment by Alex-302** [comment]
taboola is blocked by `Adguard tracking protection filter`. It is expected behavior. You can add
`||taboola.com^$third-party,badfilter` to custom filter.

**Comment by ghajini** [comment]
Taboola serves legit news.content, blocking that will cause breakage

**Comment by ghajini** [comment]
Fixed in ublock origin for Firefox android. ....
Adguard still suffers.....
Blocking legitimate content
@Alex-302 fyi
