### ISSUE TITLE
[nsfw] xvideos.com is broken by Safari extension

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3143]
**Description**:
https://forum.adguard.com/index.php?threads/adguard-and-a-nsfw-site.14489/

For instance:
http://www.xvideos.com/video20964341/1799482

**Comment by Alex-302** [comment]
Can't reproduce. Asked for more information.

**Comment by ameshkov** [comment]
Why, I can easily reproduce it with the latest safari extension version

**Comment by Alex-302** [comment]
I use 2.4.13. I will try with a new version.

**Comment by Alex-302** [comment]
Still can't reproduce. Checked on many videos.

**Comment by ameshkov** [comment]
In my case it's broken by these:
```
Content blocker prevented frame displaying http://www.xvideos.com/video23201395/blonde_pretty_teen_girl_public_gangbang_car_orgy from loading a resource from http://static-hw.xvideos.com/v3/js/libs/hls.min.js
```

This rule helps:
`@@//*.xvideos.com^$domain=xvideos.com`

**Comment by Alex-302** [comment]
Ok, added.
