### ISSUE TITLE
progrib.ru - ads

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3144]
**Пропущена реклама.**

![2016-10-05_17-30-23](https://cloud.githubusercontent.com/assets/16462533/19125306/43a64898-8b3f-11e6-91f3-09fc62ba13ab.png)

Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский

**Comment by Alex-302** [comment]
Fiexed.
