### ISSUE TITLE
losmovies.club - popup

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3145]
www.losmovies.club

Opens new pages when you click anywhere, including player controls

![screen shot 2016-10-06 at 9 50 07 am](https://cloud.githubusercontent.com/assets/15856304/19143094/4f4ecad8-8baa-11e6-81da-10de00fc2fc5.png)

<details>
![screen shot 2016-10-06 at 9 51 25 am](https://cloud.githubusercontent.com/assets/15856304/19143127/7625708a-8baa-11e6-9260-722fcff0f6e1.png)

**Comment by Alex-302** [comment]
Added to English filter
```
||3al.pw^$third-party
```

**Comment by evgeniy-ADG** [comment]
http://losmovies.club/free-movie/tt91234/watch-online-ice-age-collision-course

When you click Play it still pops with some ads

**Comment by Alex-302** [comment]
Added to English filter
```
fmovies.to#%#Object.defineProperty(window, 'j4v6', { get: function() { return {}; } });
```
