### ISSUE TITLE
support.google.com -  Incorrect Blocking icon AdSense

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3146]
**Блокируется ярлык AdSense слева, как на скриншоте. Проблема в англ.фильтре.**

**Фильтры:**
```
Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский
```
![12](https://cloud.githubusercontent.com/assets/16462533/19144139/9b29c182-8bb0-11e6-8641-a34ce13ad696.png)

**Comment by Alex-302** [comment]
Fixed.
