### ISSUE TITLE
http://wap.lexun.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3147]
http://wap.lexun.com/index.php?cd=0&lxt=bbe5af8feb2a09e3rggttcfff&_r=233494475&vs=1

![image1 3](https://cloud.githubusercontent.com/assets/15856304/19144182/d61dced2-8bb0-11e6-8dd8-74891b2d6af3.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-10-04 17:33:01 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.3
ID: 0F2791EB-B2B3-49F3-862E-4683B07082CD

Locale: zh
Region: cn

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.44 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.92 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.26 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.5.8 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.44 Enabled=YES
ID=101 Name="EasyList" Version=1.0.63.35 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.66.60 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.66.91 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.1.78 Enabled=YES

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by evgeniy-ADG** [comment]
I can, on a real device, were unable to reproduce in a desktop Safari though

**Comment by Alex-302** [comment]
Added to Mobile filter
```
wap.lexun.com###ad
```
