### ISSUE TITLE
AdGuard for Mac blocks AirPlay at hdrezka.ag

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#31473]
### Issue URL (Incorrect Blocking)
[http://hdrezka.ag/films/thriller/30224-zerkalo-zadnego-vida-2017.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fhdrezka.ag%2Ffilms%2Fthriller%2F30224-zerkalo-zadnego-vida-2017.html)
### Comment

На видео-плеере на сайте http://hdrezka.ag <http://hdrezka.ag/>, AdGuard, блокирует кнопку AirPlay. При нажатии не выпадает меню.

> Информация ниже сгенерирована автоматически, не удаляйте ее.
> 
> Referrer:
> 
> 
> Custom userscripts:
> https://cdn.adguard.com/public/Userscripts/Wot/1.0/wot.meta.js
> https://cdn.adguard.com/public/Userscripts/AdguardPopupBlocker/2.5/popupblocker.meta.js
> https://cdn.adguard.com/public/Userscripts/AdguardAssistant/4.2/assistant.meta.js

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Y4JYZW0.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/Whust8B.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Mac, iPhone
AdGuard version: | 2.0.0.524 nightly / 1.3.x
Browser: | Safari
Filters: | AdGuard Russian,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

**Comment by Alex-302** [comment]
На айпаде этой кнопки не вижу даже без Адгарда.

**Comment by boog9** [comment]
@Alex-302 Вы не видите данную кнопку скорее всего из-за того что в вашей локальной сети нет AirPlay сервера(AppleTV, etc..)
На данный момент проблема присутствует на macOS (10.14.6) и AdGuard 2.0.6

Фильтры:

- AdGuard Russian,
- AdGuard Annoyances,
- AdGuard Base,
- AdGuard Tracking Protection,
- AdGuard Social Media

**Comment by Eugene-Savenko** [comment]
Подтверждаю. @Alex-302 могу дать доступ,  если нужно, у меня всё повторяется, ка ки ранее.

**Comment by Alex-302** [comment]
@Eugene-Savenko давай гляну.

**Comment by Alex-302** [comment]
Подправил. Через час-полтора можно будет проверять обновление фильтров.

**Comment by boog9** [comment]
@Alex-302 к сожалению проблема по прежнему присутсвует. Dropdown menu/popup не появляется.
https://rezka.ag/cartoons/comedy/1760-yuzhnyy-park-1997.html
Проблема в AdGuard Base Filter

**Comment by Alex-302** [comment]
@boog9 не появилась кнопка?

**Comment by coldy13** [comment]
> @boog9 не появилась кнопка?

Такая же проблема, как у Eugene-Savenko. При включенном ad Guard 2.1.2.595 при нажатии на кнопку airplay, меню для выбора устройства apple tv не открывается, а фильм ставится на паузу.

**Comment by Alex-302** [comment]
@coldy13 а у меня всё нормально сейчас - с афпада на телек стримится без проблем.

**Comment by boog9** [comment]
@Alex-302 
Доброго дня. К сожалению проблема по прежднему присутствует на macOS, с iPad и iPhone, работает нормально. На iPad и iPhone проблема исчезла после обновления Adguard на версию 2

**Comment by Alex-302** [comment]
@boog9 в макоси у меня эта функция не доступна даже без блокировщиков.

Но зачем "это" стримить на телек?) У них же качество как у 480p при выбранном 1080p в лучшем случае. На ноуте качество посредственное, а на большом экране смотреть невозможно.

**Comment by Alex-302** [comment]
проверил еще раз - функция работает
![image](https://user-images.githubusercontent.com/8361299/63773925-d8fbf380-c8e4-11e9-9ada-cedba3216591.png)

**Comment by boog9** [comment]
@Alex-302 
На ноутбуке это кнопка у меня есть, только когда я на нее нажимаю, вместо попапа(с выбором устройсва для стрима) нажимается паузы. Относительно качества, на этом сайте оно довольно приличное, а данный плеер используется на многих других ресурсах.

**Comment by Alex-302** [comment]
@boog9 консолью в Сафари умеете пользоваться?
Если ломает базовый фильтр, нужно выключить все фильтры, кроме него, повторить проблему и сюда сохранённый вывод консоли скопипастить. Попробую посмотреть, что может ломать. (можно отфильтровать по слову `blocked`)

> Относительно качества, на этом сайте оно довольно приличное, а данный плеер используется на многих других ресурсах.

ну с рипами на торрентах ни в какое сравнение же не идёт. Сейчас глянул - там загружается кусками по 0.5-2 МБ(Зв. Войны 7) длительностью примерно по 10 с. Таких кусков - около 830. Объём фильма получается менее 2 ГБ:) И звук с низким битрейтом. Качественный рип этого фильма в H.264 имеет объём хорошо за 10 ГБ(18 с несколькими звуковыми дорогами), а в H.265 - 6.5 ГБ(но только две звуковые дорожки). Разве что в дороге смотреть годится по мобильному интернету:) Когда-то был сайт fs.to, вот там были оригинальные файлы с торрентов. Но этот сайт бессовестно уничтожили:(

**Comment by boog9** [comment]
@Alex-302 Отключил все фильтры, потом включил и все заработало. Пробелема решина.
Спасибо @Alex-302 и хорошего Вам дня.

А по поводу rezka.ag, согласен файлы там по 2ГБ, но лучшего ничего не нашел.

**Comment by Alex-302** [comment]
> Отключил все фильтры, потом включил и все заработало

странно. Баг что ли. Попробуем проверить.

**Comment by boog9** [comment]
The following issue has appeared again.
macOS version: 15.3.2
AdGuard for Mac: Version 2.16.4.1870 release
