### ISSUE TITLE
http://www.espn.com - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3150]
Adguard is not allowing changes on the goggles on the scoreboard. For example, if I try to switch between different weeks, nothing happens - it works when ad block is disabled.

Incorrect blocking on page:
http://www.espn.com/nfl/scoreboard/_/year/2016/seasontype/2/week/5

![file_000 3](https://cloud.githubusercontent.com/assets/15856304/19144542/d38648c8-8bb2-11e6-8eae-95222d95d9dd.png)

<details>
Application version: 1.0.8.54
Application lifetime: 2016-10-06 02:22:17 +0000

Device: iPhone
Platform: iPhone OS
OS: 10.1
ID: 5F313F21-B980-42A5-A431-03A12B9ECFCC

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.52 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.95 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.34 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.4.97 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.9 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.44 Enabled=YES

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||espn.com/b/ss/$domain=espn.com
```
