### ISSUE TITLE
http://rustorka.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3151]
http://rustorka.com/forum/index.php

![screen shot 2016-10-06 at 12 05 51 pm](https://cloud.githubusercontent.com/assets/15856304/19146689/44e9062c-8bbd-11e6-9d0a-2ccd829cd135.png)

<details>
English filterVersion 1.0.96.53. Updated 6 october 2016 at 09:00.
Spyware filterVersion 1.0.7.95. Updated 6 october 2016 at 02:00.
Social media filterVersion 1.0.13.34. Updated 6 october 2016 at 02:00.
Annoyances filterVersion 1.0.4.97. Updated 6 october 2016 at 02:02.
Russian filterVersion 1.0.40.54. Updated 5 october 2016 at 22:00.
Mobile Ads filterVersion 1.0.5.9. Updated 5 october 2016 at 16:06.
Safari filterVersion 1.0.1.45. Updated 6 october 2016 at 09:01.

**Comment by Alex-302** [comment]
Ашчувю

**Comment by vgavrish** [comment]
Расширение
http://rustorka.com/forum/index.php
При нажатии в любую область, открывается окно с другим сайтом
Опера
Ф: 1,2,4,115
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/20407952/25c217cc-ad1c-11e6-9269-5f84712229e8.png)

**Comment by Alex-302** [comment]
Расширения для Оперы и Фокса не могут JS правила загружать.
Вот такие передай
<details>
```
rustorka.com#%#Object.defineProperty(window, 'MTretCK', { get: function() { return false; } });
rustorka.com#%#Object.defineProperty(window, 'pindos', { get: function() { return false; } }); Object.defineProperty(window, 'pidaras', { get: function() { return null; } });
```
</details>

**Comment by Pavluha72** [comment]
Сейчас, после обновления фильтров, перестал работать чат на этом сайте.

**Comment by Alex-302** [comment]
А дайте адрес страницы.

**Comment by Pavluha72** [comment]
http://rustorka.com/forum/

**Comment by Alex-302** [comment]
исправил

**Comment by vgavrish** [comment]
http://rustorka.com/forum/
При нажатии в любую область сайта открывается Pari match
Ф: 1,2,3,4,14

**Comment by Alex-302** [comment]
в пользовательский
```
rustorka.com#%#Object.defineProperty(window, 'dhyutkdjdfg', { get: function() { return undefined; } });
```
Опера не может загружать правила javascript при обновлении фильтров

**Comment by Pavluha72** [comment]
так и перебрасывает на левые сайты :(

**Comment by Alex-302** [comment]
исправлено

**Comment by vgavrish** [comment]
у меня еще открывается пари матч

**Comment by Alex-302** [comment]
фильтры свежие? Прога/расширение?

**Comment by vgavrish** [comment]
еще раз обновила фильтры (расширение)
теперь все ок

**Comment by Pavluha72** [comment]
все равно при нажатии в любой области сайта открывается вкладка с левым сайтом
фильтры обновлены, подробности на скринах
![1](https://cloud.githubusercontent.com/assets/23558063/22372308/10677368-e4ad-11e6-923c-8e5caaa71ecb.jpg)
![2](https://cloud.githubusercontent.com/assets/23558063/22372311/106e8e5a-e4ad-11e6-8617-d4118c494ffe.jpg)
![3](https://cloud.githubusercontent.com/assets/23558063/22372309/1067a78e-e4ad-11e6-9485-16e392bf1f00.jpg)
![4](https://cloud.githubusercontent.com/assets/23558063/22372310/1067d5ce-e4ad-11e6-8ba9-8d68e895255f.jpg)

**Comment by Alex-302** [comment]
@Pavluha72 это из-за параноидальности создателей оперы. Она не разрешает загружать JS правила.
Добавьте
```
rustorka.com#%#Object.defineProperty(window, 'user_agent', { get: function() { return {}; } }); Object.defineProperty(window, 'pidar', { get: function() { return false; } });
```

**Comment by Pavluha72** [comment]
Спасибо. Вроде помогло.

**Comment by Pavluha72** [comment]
решения так и нет :(

**Comment by vgavrish** [comment]
@Alex-302 
 на время правило помогло 
сейчас опять открывается окно

**Comment by Alex-302** [comment]
Новая вкладка автоматом закрывается. Подождём, пока он перестанет скрипт переделывать.

**Comment by Pavluha72** [comment]
@Alex-302
Больше информации нет? Проблема так и не решена.

**Comment by Alex-302** [comment]
для оперы сложно придумать альтернативу javascript правилам. Они(браузер) игнорируют такие правила при обновлении фильтров.
Через час будет обновление, проверьте вручную.

**Comment by Pavluha72** [comment]
Спасибо. Подскажите, а в Хроме таких проблем с  javascript правилам нет?

**Comment by Alex-302** [comment]
В Хроме таких проблем нет.
Проверили, как после обновления работает?

**Comment by Pavluha72** [comment]
Да, спасибо. Окно мелькает и сразу закрывается.

**Comment by Alex-302** [comment]
Позже исправлю это, когда хозяин сайта успокоится)

**Comment by Pavluha72** [comment]
сегодня стало открывать левые сайты в отдельном фоновом окне

**Comment by evgeniy-ADG** [comment]
http://rustorka.com/forum/index.php

![image](https://cloud.githubusercontent.com/assets/15856304/24827583/39a6b542-1c55-11e7-8dee-a83fd392f9d1.png)

Ad blocker Filter rules count: 91660
English filterVersion 1.1.14.1. Updated 8 april 2017 at 09:00.
Social media filterVersion 1.0.18.47. Updated 7 april 2017 at 22:01.
Annoyances filterVersion 1.0.11.62. Updated 7 april 2017 at 22:02.
Russian filterVersion 1.0.49.45. Updated 7 april 2017 at 22:00.
Dutch filterVersion 1.0.9.23. Updated 24 march 2017 at 18:01.
Spanish/Portuguese filterVersion 1.0.86.59. Updated 23 march 2017 at 15:01.
Bulgarian listVersion 1.0.0.13. Updated 4 february 2017 at 15:30.

**Comment by Alex-302** [comment]
fixed

**Comment by evgeniy-ADG** [comment]
Снова есть, фильтры обновлены. Баннеры те же.

**Comment by zebrum** [comment]
@Alex-302 посмотри пожалуйста, новые окна открываются

**Comment by Alex-302** [comment]
убрал
