### ISSUE TITLE
businessinsider.com 

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#3153]
![screen shot 2016-10-06 at 19 04 40](https://cloud.githubusercontent.com/assets/17472907/19160264/e6c53d78-8bf7-11e6-81cd-0b2d136c6f8d.png)

chrome extension

English filterVersion 1.0.96.43. Updated 5 october 2016 at 11:00.
Social media filterVersion 1.0.13.27. Updated 5 october 2016 at 12:00.
Annoyances filterVersion 1.0.4.90. Updated 5 october 2016 at 12:02.
Russian filterVersion 1.0.40.47. Updated 5 october 2016 at 12:00.
Anti-Adblock Killer | ReekVersion 1.0.1.65. Updated 6 july 2016 at 21:04.

**Comment by Alex-302** [comment]
Fixed.
