### ISSUE TITLE
http://kinokrad.co/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3154]
**Description**: Реклама сбоку
http://kinokrad.co/301271-iskusstvennyy-intellekt-dostup-neogranichen.html

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19166468/4caba128-8c10-11e6-8273-c0fdbff752fc.png)

</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
kinokrad.co##a[href^="http://wow-partners.com/"]
```
