### ISSUE TITLE
filmix-online.net

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3155]
**Description**: Реклама
И отступ от шапки можно убрать?
http://filmix-online.net/publ/28

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19166617/dfd61456-8c10-11e6-85c7-b10ba7f795d7.png)
</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня не открывается. Там с прокси нужно заходить?

**Comment by Bohdan-SUP** [comment]
@Alex-302 Могу ТВ дать доступ.

**Comment by Alex-302** [comment]
Открылось. Исправил.
