### ISSUE TITLE
dave.uktv.co.uk - website not showing

### ISSUE THREAD

**Issue by Marko321** [AdguardTeam/AdguardFilters#3156]
Page is loaded normally when Adguard is turned off.

Filters:
- English filter
- Spyware filter
- Social filter
- Annoyances filter
- EasyPrivacy
- Adblock Warning Removal Lists
- Anti-Adblock Killer | Reek
- I dont care about cookies
- Malware Domains

![screenshot_1](https://cloud.githubusercontent.com/assets/7421544/19167045/5d34181e-8c0a-11e6-9b18-107ea0a0d66b.png)

**Comment by Alex-302** [comment]
Fixed in Annoyances filter.
