### ISSUE TITLE
telecinco.es

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#3157]
Chrome extension
Через некоторое время на сайте перекидывает на http://www.telecinco.es/informacionPublicidad.html

![2016-10-06 23 51 34](https://cloud.githubusercontent.com/assets/17472907/19170168/0744b33a-8c20-11e6-8b32-d4fdc693a1bb.png)

![2016-10-06 23 51 37](https://cloud.githubusercontent.com/assets/17472907/19170169/0744fa52-8c20-11e6-9f91-4b3e8aa14269.png)

**Comment by Alex-302** [comment]
Добавил в испанский:
```
@@||telecinco.es^$generichide
telecinco.es##.ad-top
```
