### ISSUE TITLE
http://multitime.ru/ - false blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3158]
http://multitime.ru/

Before <details>
![screen shot 2016-10-07 at 9 55 13 am](https://cloud.githubusercontent.com/assets/15856304/19181175/e3a75a28-8c73-11e6-9c25-7513adfb21c3.png)

</details>
After <details>
![screen shot 2016-10-07 at 9 54 59 am](https://cloud.githubusercontent.com/assets/15856304/19181183/f13ffc26-8c73-11e6-96e1-0661230de050.png)

</details>

English filterVersion 1.0.96.65. Updated 7 october 2016 at 02:00.
Russian filterVersion 1.0.40.60. Updated 7 october 2016 at 02:00.

**Comment by Alex-302** [comment]
Ну хоть пару слов коммента можно?
Добавил
```
@@||multitime.ru/images/adv/
```

**Comment by vgavrish** [comment]
Adguard блокирует элементы дизайна сайта по не понятной причина ( орнамент и рамки дизайна не)
Блокирует он следующие два сайта multitime.ru и multitime24.ru 

**Помогает отключение Английского фильтра. Хром**

Блокировка элементов дизайна
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21426278/ae842a46-c856-11e6-8cdf-a718a14a4627.png)

</details>

Как должно быть: 
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21426294/cfe2fd52-c856-11e6-909b-04d7f65fff97.png)

**Comment by Alex-302** [comment]
Исправил.
