### ISSUE TITLE
metabans.com

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3160]
**Description**: Adblocker detected

**Current behaviour**: Red banner in the middle of the screen tells the user he is using an adblocker.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/10995998/19191759/13193fd0-8ca4-11e6-89a8-b565d21386f7.png)

**Expected behaviour**: Red banner shouldn't be there.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/10995998/19191797/36eb635c-8ca4-11e6-84d9-fc513c1bd6a5.png)

**Adguard version**: 6.1.258.1302

**Filters list**: 
English filter 1.0.96.68
Spyware filter 1.0.7.99
Social media filter 1.0.13.37
Annoyances filter 1.0.5.4
German filter 1.0.27.77

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Thanks, fixed in annoyances filter.
