### ISSUE TITLE
Moonwalk ( плеер ) AdGuard не даёт выбрать качество

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#31602]
@XNoInformationX commented on [Sun Mar 24 2019](https://github.com/AdguardTeam/AdguardForiOS/issues/923)

### Steps to reproduce

hdrezka.ag
1. Выбираете любой фильм/сериал
2. Заходите 
3. Жмёте копку старт на плеере 
4. Пытаетесь выбрать качество, вместо этого он останавливает и запускает видео 

### Actual behavior

<details><summary>Screenshot:</summary>
Не приложу, так как не выйдет это заснять

</details>

### Your environment

* Device model: iPad Pro
* Operating system and version: 10.3.3
* Browser - Safari
* Wi-fi or mobile internet connection - Wi-Fi

**Comment by Alex-302** [comment]
@XNoInformationX
попробуйте добавить в пользовательский фильтр это правило
`@@||ed98512111bb19e5.in.net/`
может разблокироваться реклама в плеере, но на iOS другого решения нет.

**Comment by sewahohlik** [comment]
> @XNoInformationX
> попробуйте добавить в пользовательский фильтр это правило
> `@@||ed98512111bb19e5.in.net/`
> может разблокироваться реклама в плеере, но на iOS другого решения нет.

Не помогает

**Comment by XNoInformationX** [comment]
> @XNoInformationX
> попробуйте добавить в пользовательский фильтр это правило
> `@@||ed98512111bb19e5.in.net/`
> может разблокироваться реклама в плеере, но на iOS другого решения нет.

Стало легче, теперь исчез значок плеера ( когда это происходит, всего одна реклама ), когда он есть две.
P.S Значок плеере - та штука на которую надо нажать для запуска видео
Жду когда придумаете как убрать рекламу, заранее спасибо

**Comment by Alex-302** [comment]
Чтоб не было рекламы, нужно удалить то правило) На на iOS иначе никак, скудная система в плане возможностей приложений.

**Comment by sewahohlik** [comment]
В перспективе это вообще решаемо, или можно забыть про кинцо на планшете?

**Comment by Alex-302** [comment]
Проверьте обновление фильтров.

**Comment by sewahohlik** [comment]
> Проверьте обновление фильтров.

Продвижение есть
В мобильной версии плеера всё по-старому, качество не поменять
Если перезагрузить страницу на полную версию сайта, то качество меняется и рекламы нет, НО!
Качество видеоряда не поднимается выше 480р. В настройках может стоять 720р, 1080р - видеоряд всё равно не выше 480р. При этом можно снизить до 360р, и оно действительно снизится (обратите внимание на надпись)
![5E297264-7764-4064-BD1F-0760D1BB697E](https://user-images.githubusercontent.com/39390377/55821321-e0715a80-5b05-11e9-9797-af5af429162c.png)
![D0E17EE3-B731-4E57-8623-E662CA683DDF](https://user-images.githubusercontent.com/39390377/55821323-e0715a80-5b05-11e9-8008-c1cdb46daa18.png)
![CA76EB69-9BD8-499E-AA69-FC1C256CF120](https://user-images.githubusercontent.com/39390377/55821325-e0715a80-5b05-11e9-97be-33f67b3d9a01.png)
![AB344018-65AF-4D50-B507-5C5B2CBDC45A](https://user-images.githubusercontent.com/39390377/55821327-e109f100-5b05-11e9-9a50-3c29de70f843.png)

**Comment by Alex-302** [comment]
всё остаётся по-прежнему - блокировка видеорекламы в Сафари ломает переключение качества.

**Comment by sewahohlik** [comment]
> всё остаётся по-прежнему - блокировка видеорекламы в Сафари ломает переключение качества.

Ну, то есть это уже не будет исправляться со стороны адгварда?

**Comment by Alex-302** [comment]
Ну либо реклама, либо качество. Это чисто сафарийная проблема, другой плеер используют. На iOS наши возможности ограничены, в отличие от других ОС.
