### ISSUE TITLE
kinokong.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3161]
**Description**: http://kinokong.net/28533-dom-strannyh-detey-miss-peregrin-2016-online.html
Reproduced in Chrome with **extension only**

Screenshot: use the following code
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19195403/32bdf608-8cba-11e6-9055-745ffce033d8.png)
</details>

**Filters list**:
![image](https://cloud.githubusercontent.com/assets/14153331/19195428/4aca2294-8cba-11e6-950c-494391a017dd.png)

**Comment by Alex-302** [comment]
Fixed.

**Comment by zebrum** [comment]
http://kinokong.cc/20788-pribytie-istoriya-tvoey-zhizni-2016.html
browser extension chrome
en rus annoyances spyware social media

<details>

![2017-01-23 14 16 37](https://cloud.githubusercontent.com/assets/23637588/22201851/94c0d65c-e176-11e6-873d-73f784000e1e.png)

</details>

**Comment by Alex-302** [comment]
fixed
