### ISSUE TITLE
duden.de

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3162]
**Description**: Cookie notice not blocked

**Current behaviour**: Site shows a cookie notice at the bottom.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/10995998/19208362/608a41c4-8cf9-11e6-8ebb-24c9fa25e2b3.png)

**Expected behaviour**: Cookie notice should be blocked.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/10995998/19208377/8c1079e4-8cf9-11e6-8083-a6b96dd231eb.png)

**Adguard version**: 6.1.258.1302

**Filters list**: 
English filter 1.0.96.72
Spyware filter 1.0.8.2
Social media filter 1.0.13.41
Annoyances filter 1.0.5.8
German filter 1.0.27.77

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
duden.de###sliding-popup
```
