### ISSUE TITLE
adobe.com/de/

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3163]
**Description**: Cookie notice not blocked

**Current behaviour**: Site shows a cookie notice at the top.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/10995998/19208443/2b3cc194-8cfa-11e6-85b0-dce0744d12ff.png)

**Expected behaviour**: Cookie notice should be blocked.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/10995998/19208455/448f68ea-8cfa-11e6-81b6-9acc2c9117da.png)

**Adguard version**: 6.1.258.1302

**Filters list**: 
English filter 1.0.96.72
Spyware filter 1.0.8.2
Social media filter 1.0.13.41
Annoyances filter 1.0.5.8
German filter 1.0.27.77

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
adobe.com##body > div.message
```
