### ISSUE TITLE
dooralei.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3164]
**Description**: Просьба убрать всплывающее окно
http://dooralei.ru/blog/43130008392/Rossiya-razryivayet-otnosheniya-s-Gaagoy

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19210920/be758566-8d38-11e6-8239-ebdfadfe3360.png)
</details>

**Filters list**: 1,2,3,4,11,14

**Operating system**: Андроид

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Убрал.
