### ISSUE TITLE
Player with ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3165]
**Description**: Реклама в одном и том же плеере на 2х сайтах.
http://small-games.info
http://welovebundles.ru/wuppo/
- Расширения отключали. Через Приватную также реклама. У меня не повторяется.
- Вначале ролика сначала страница как бы тормозит, потом загружается рекламный ролик, а потом сам ролик . 
- В конце каждого видео еще переходы на другие сайты

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19211922/755ffbf0-8d50-11e6-98ea-afa6d42f8987.png)
![image](https://cloud.githubusercontent.com/assets/18548949/19211926/7e34c5bc-8d50-11e6-898a-b43c08567dd6.png)
![image](https://cloud.githubusercontent.com/assets/18548949/19211948/e60aa954-8d50-11e6-993e-ab255b3b1c15.png)
</details>

**Adguard version**: 6.1.258.1302

**Filters list**: 1,2,3,5

**Operating system**: Вин

**Browser**: Опера 41 Beta (41.0.2353.10), PaleMoon Portable.

**Comment by Alex-302** [comment]
Тоже не повторяется. Удалённо бы глянуть. Или попроси скрин вкладки Sources из инструментов разработчика
<details>
![image](http://imagizer.imageshack.com/img921/241/U9Jgkn.png)
</details>

**Comment by vgavrish** [comment]
написала
