### ISSUE TITLE
1fichier.com's picture Ads (by Taboola)

### ISSUE THREAD

**Issue by rayman3003** [AdguardTeam/AdguardFilters#3166]
Hi

There are some annoying Picture Ads on the 1fichier website (A hosting website).
Is there any script to block these images?

Note: Above the pictures, It says: "Sponsored Links by Taboola"

Example Link:

https://1fichier.com/?ycusncmxkn

Screenshot:

![untitled](https://cloud.githubusercontent.com/assets/17022701/19221346/21604b0e-8e31-11e6-854d-fdc4d5cb47a8.jpg)

---------------------------
OS; Windows 10 x64

Browsers: Chrome - Firefox - IE

AppVersion: 6.1.258.1302
 Main settings: 
 Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
 FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
 FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
 FilterId:122 Name: Fanboy's Annoyances Url: https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
 FilterId:207 Name: Adblock Warning Removal List Url: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
 FilterId:211 Name: Anti-Adblock Killer | Reek Url: https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
 FilterId:215 Name: Fanboy's Enhanced Tracking List Url: https://secure.fanboy.co.nz/enhancedstats.txt

**Comment by rayman3003** [comment]
Screenshot has been added.

**Comment by rayman3003** [comment]
Bump

**Comment by Alex-302** [comment]
Hi
Does HTTPS filtering enabled? Please make a screenshot of SSL certificate details.
Press F12 in your browser and make screenshot of following window:
![image](http://imagizer.imageshack.com/img921/4585/t9G2am.png)

**Comment by rayman3003** [comment]
here is screenshot:

http://img.ctrlv.in/img/16/10/21/58096fa47db47.jpg

OK, by adding https option, it has been solved. thank u.
