### ISSUE TITLE
zserials.tv

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3167]
**Description**: В альтернативном и Дополнительном плеере реклама
http://zserials.tv/russkie/shaman.php

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19219021/2d747480-8e11-11e6-8535-742c3038091d.png)
</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

**Comment by Alex-302** [comment]
Поправил.

**Comment by dzamyshlyayeva** [comment]
same issue here: http://zserials.cc/anime/masamune-kuns-revenge.php

Screenshot: http://f5.s.qip.ru/OgbqiuvN.png
* Windows 7 x64
* Adguard  Chrome Extension
* Filters: Russian,English, RU AdList
* Dr.Web

Ticket ID 1076701

**Comment by Alex-302** [comment]
fixed
