### ISSUE TITLE
http://www.macdigger.ru/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3168]
**Description**: Реклама вверху
http://www.macdigger.ru/

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/18548949/19219404/e639a162-8e1a-11e6-9d45-7d4ae1b4f513.png)
</details> 

**Adguard version**:  1.1.1.23

**Filters list**: 
<details>
Optimazed enabled: NO

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.68 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.99 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.37 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.4 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.40.62 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.12 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.48 Enabled=YES
ID=101 Name="EasyList" Version=1.0.63.44 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.66.72 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.63.59 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.66.85 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.66.86 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.60 Enabled=YES
</details> 
**Operating system**: iOS

**Browser**: Сафари

**Comment by Alex-302** [comment]
Не повторяется что-то.
