### ISSUE TITLE
https://m.iguides.ru/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3169]
**Description**: Реклама вверху
https://m.iguides.ru/

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19219413/7b368794-8e1b-11e6-9604-42e4b3dba1e6.png)

</details> 

**Adguard version**:  1.1.1.23

**Filters list**: 
<details>
Optimazed enabled: NO

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.68 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.99 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.37 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.4 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.40.62 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.12 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.48 Enabled=YES
ID=101 Name="EasyList" Version=1.0.63.44 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.66.72 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.63.59 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.66.85 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.66.86 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.60 Enabled=YES
</details> 
**Operating system**: iOS

**Browser**: Сафари

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
m.iguides.ru##.pageContent_topBar > a[href="https://www.iguides.ru/blackfriday2016-mobile"]

```
