### ISSUE TITLE
idwl.cn

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3171]
**Description**: Вулкан на фоне
idwl.cn

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19235438/622ba858-8efa-11e6-96ff-5c2d6f4f8e0a.png)

</details>

**Filters list**: 1,2,3,4,11,14

**Operating system**: Андроид

**Browser**: Встроенный

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
idwl.cn##.brand
||idwl.cn/brand/

```
