### ISSUE TITLE
nnm.me - ads

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3172]
# [nnm.me](http://nnm.me/)

![09281dd7c02d48e7beccf7f31e59c075](https://cloud.githubusercontent.com/assets/16462533/19236035/d7dff844-8efd-11e6-9b9d-1af61a805266.png)

> **Пользовательский
> Английский
> Фильтр счетчиков и систем аналитики
> Экспериментальный
> Фильтр раздражителей
> Русский**

**Comment by Alex-302** [comment]
Чисто[уже]

**Comment by SKAT-Krd** [comment]
Сегодня снова на этом же сайте http://prntscr.com/ct84io

**Comment by SKAT-Krd** [comment]
Сохраненная страница, вдруг поможет. https://cloud.mail.ru/public/LSTs/8DdycqKpH

**Comment by vozersky** [comment]
опять повторяется
@Alex-302  check please

**Comment by Alex-302** [comment]
Fixed.

**Comment by SKAT-Krd** [comment]
@Alex-302 Спасибо.
