### ISSUE TITLE
erozasvet.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3173]
**Description**: Расширение. Посторонняя реклама*
erozasvet.com

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19236452/2e781f2c-8f00-11e6-8454-39a463c3942e.png)
</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
