### ISSUE TITLE
forums.overclockers.ru - antiadblock script

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3174]
**Current behaviour**: Anti-adblock message, even though Annoyances filter is up&running.

Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19242071/4869bf02-8f1a-11e6-9762-95a93d4419b4.png)
</details>

**Adguard version**: 2.7.220

**Filters list**: [ 2, 3, 4, 14, 1, 11 ], https filtering is ON

**Operating system**: Android 6.0.1

**Browser**: Chrome, Yandex

**Comment by Alex-302** [comment]
Fixed

**Comment by Bohdan-SUP** [comment]
@Alex-302 still see the message after filter update.
Should I just wait for a while?

**Comment by Alex-302** [comment]
@Bohdan-SUP Which Adguard?

**Comment by Bohdan-SUP** [comment]
Android, 2.7.220, только что снова обновил фильтры - все еще вижу сообщение и определении блокировщика рекламы.

**Comment by Alex-302** [comment]
И фильтрация HTTPS не включена, похоже.
Добавил в мобильный фильтр:
```
@@||amazon-adsystem.com$domain=overclockers.ru
```
