### ISSUE TITLE
Version - 6.1.271.1366 Breaks communications to all of *.google.com and adgaurd.com etc. see list #1314

### ISSUE THREAD

**Issue by southwestvinyl** [AdguardTeam/AdguardFilters#3177]
**Description**:
latest beta update breaking all google domains mail.google.com maps.google.com youtube etc.. also it is breaking adguards domains as well! please see the following list when i turn off proxy mode everything working fine! re-enable it and everything breaks! thanks 

List:
mailtrack.io
mail.google.com
hangouts.google.com
*.client-channel.google.com
*.google.com
*.gstatic.com
mail-attachment.googleusercontent.com
*.googleusercontent.com
lh3.googleusercontent.com
fonts.googleapis.com
*.youtube.com
accounts.google.com
*.googleapis.com
nexus-websocket-b.intercom.io
api-iam.intercom.io

https://adguard.com/en/versions.html#6.1.258 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
https://adguard.com/en/versions.html#6.1.258:1 GET https://adguard.com/en/versions.html net::ERR_TUNNEL_CONNECTION_FAILED

also 

http://prntscr.com/csmyrx

http://prnt.sc/favicon.ico Failed to load resource: the server responded with a status of 502 (Bad Gateway)
http://prnt.sc/csmyrx Failed to load resource: the server responded with a status of 502 (Bad Gateway)

also 

error details

System.Net.Sockets.SocketException: An address incompatible with the requested protocol was used [2400:cb00:2048:1::6819:ca1c]:80Source: SystemStack trace:    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)   at Adguard.Filter.Proxy.HttpRemoteEndPoint.Connect()   at Adguard.Filter.Proxy.HttpProxyConnectionContext.GetRemoteEndPoint(Uri requestUri, Boolean flushCache)   at Adguard.Filter.Proxy.HttpProxyServer.WriteHttpRequest(HttpRequest request, HttpProxyConnectionContext context, ProxyRequestStatistics proxyRequestStatistics, FilteringContext filteringContext, Boolean reconnect)   at Adguard.Filter.Proxy.HttpProxyServer.ProcessHttpRequest(HttpRequest request, HttpProxyConnectionContext context, FilteringContext filteringContext)   at Adguard.Filter.Proxy.HttpProxyServer.ProcessRequest(HttpRequest request, HttpProxyConnectionContext proxyContext, FilteringContext filteringContext)   at Adguard.Filter.Proxy.BaseHttpServer.ProcessConnection(TcpConnectionContext context)

please see mouse hover of localhost with port info
http://prnt.sc/csn2qx

![screenshot_1](https://cloud.githubusercontent.com/assets/22777187/19285034/b6fca916-8fb5-11e6-93d8-d3fd00fcedbc.png)

see it working using another proxy that hasn't been updated!

http://prntscr.com/csn4sj
![adguard breaks2](https://cloud.githubusercontent.com/assets/22777187/19285127/3068a46c-8fb6-11e6-8d79-ac074316758e.png)

gmail working with another proxy not upgraded to latest beta
http://prnt.sc/csn7cb
![adguard breaks3-gmail-example](https://cloud.githubusercontent.com/assets/22777187/19285326/d34c575a-8fb6-11e6-9af3-c81078a2cff4.png)

in gmail switched to localhost+port mouse hover showing details
http://prnt.sc/csn8zt
![adguard breaks4-gmail-showing-localhost port-example](https://cloud.githubusercontent.com/assets/22777187/19285512/6acb34de-8fb7-11e6-8750-480934157651.png)

adguard breaks here is a list inside Omega Switch in a profile showing ive entered those broken google domains and subdomains in a bypasslist showing inside list + localhost port
http://prntscr.com/csnaqf
![adguard breaks5-omega-bypasslist-showing-inside-list-localhost port-example](https://cloud.githubusercontent.com/assets/22777187/19285581/c87d50da-8fb7-11e6-846f-8275987fe910.png)

adguard breaks omega removed broken google services from the bypasslist showing inside list localhost port
http://prntscr.com/csndaf
![adguard breaks6-omega-removed-broken-google-services-from-the-bypasslist-showing-inside-list-localhost port-example](https://cloud.githubusercontent.com/assets/22777187/19285777/93a78e4c-8fb8-11e6-84c0-c70efbfad93b.png)

adguard breaks showing inside gmail totally broken after removing the bypass google domains etc.
http://prntscr.com/csnfar
![adguard breaks7-gmail-totally-broken-example](https://cloud.githubusercontent.com/assets/22777187/19285881/03d4d224-8fb9-11e6-8cdc-dade2cb5fd00.png)

**Current behaviour**: Tell us what happens
!.........!
**Expected behaviour**: Tell us what should happen instead
!.........!
!.........!
**Steps to reproduce the problem**:
!.........!
**Adguard version**:
Version - 6.1.271.1366

**Filters list**:
User Filters:
@@||ch131.me$document
@@||icefilms.info$document
@@||twomovies.us$document
@@||hugefiles.net$document
@@||dsspros.com$document
@@||allmyvideos.net$document
@@||myvideolinks.eu$document
@@||primewire.ag$document
@@||iwatchonline.to$document
@@||tv-releases.net$document
@@||tv-release.net$document
@@||movietv.to$document
@@||clicktoplay.to$document
@@||watchseries-online.ch$document
@@||oneclickwatch.org$document
@@||clickplay.to$document
@@||movie4k.to$document
@@||streamallthis.is$document
@@||losmovies.tv$document
@@||solarmovie.is$document
@@||oneclickwatch.ws$document
@@||moviestorm.eu$document
@@||vidics.ch$document
@@||projectfreetv.ch$document
@@||stream-tv1.me$document
@@||rissource.net$document
@@||watchseries.ag$document
@@||uflix.me$document
@@||watchfree.to$document
@@||watchseries.sx$document
@@||merdb.ae$document
@@||solvemedia.com$document
@@||hitbox.tv$document
@@||promptfile.com$document
@@||ishared.eu$document
@@||channelcut.tv$document
@@||animeultima.io$document
@@||animeultima.tv$document
@@||directdownload.tv$document
@@||tvonline.cc$document
@@||simplymovies.net$document
@@||scenelog.org$document
@@||free-tv-video-online.me$document
@@||o2tvseries.com$document
@@||flixanity.tv$document
@@||g2g.fm$document
@@||watchmoviesonline.mobi$document
@@||watch-series-online.li$document
@@||109.121.134.13$document
@@||api.hitbox.tv$document
@@||imdb.com$document
@@||m2v.ru$document
@@||ishared2.me$document
@@||shared2.me$document
@@||tvrage.com$document
@@||streamin.tv$document
@@||streamin.to$document
@@||veehd.com$document
ezmoviestv.com###bsaancstkf > B
ezmoviestv.com###bsaa1pG8qk > S
bittit.info###bsaancstkf > B
bittit.info###bsaa1pG8qk > S
nastybreast.com###layer
@@||sls.update.microsoft.com/SLS/*
@@||sls.update.microsoft.com$document
@@//www.haslcutah.org^$document
@@||veoh.com$document
@@||vodlocker.com$document
@@||tudou.com$document
@@||steamcommunity.com$document
@@||steamstatic.com$document
@@||store.akamai.steamstatic.com$document
@@||cdn.akamai.steamstatic.com$document
@@||bbc.com$document
@@||sa.bbci.co.uk$document
@@||news.bbcimg.co.uk$document
@@||sa.bbc.co.uk$document
@@||twitch.tv$document
@@||steamusercontent.com$document
@@||akamaihd.net$document
au.ibtimes.com###singleplayer-0
orbitlifestyles.com###block-block-5 > DIV.content > DIV.video-header:first-child
orbitlifestyles.com###playerDafIUGiYRPih_display > DIV.jwpreview.jwuniform:first-child
orbitlifestyles.com###playerDafIUGiYRPih_display_button_buffer
orbitlifestyles.com###playerDafIUGiYRPih_display
revolve.co.kr###__TAToaster > DIV.openSlide:nth-child(2) > IMG
drtube.co###spu-103859 > DIV.spu-content:first-child > P > A.hoverZoomLink > IMG.alignnone.wp-image-103860.hoverZoomLink
drtube.co###spu-103859
drtube.co###spu-bg-103859
empflixcams.com###adultOverlayContainer
empflixcams.com###adultOverlay
empflixcams.com##DIV.wrapper:nth-child(5)
empflixcams.com###footer
empflixcams.com###footer > DIV.textcolor_05.bg_head:last-child > P.rta:nth-child(5)
empflixcams.com###footer > DIV.textcolor_05.bg_head:last-child > P.rta:last-child
empflixcams.com###footer > DIV.textcolor_05.bg_head:last-child > P.footer_text:nth-child(6)
sqft.com###password-form
sqft.com###password-bg
@@//www.htcdev.com^$document
@@||curse.com$document
@@||liverail.com$document
imagetwist.com###vz_frame
imagetwist.com###left > CENTER:nth-child(17) > IFRAME:last-child
imagetwist.com###left > IFRAME:nth-child(10)
@@||drive.google.com$document
@@||docs.google.com$document
@@||accounts.google.com$document
@@||accounts.youtube.com$document
@@||ssl.gstatic.com$document
rebelioncorp.org###lightview > DIV.lv_Container > UL.lv_Frames:last-child > LI.lv_PrevNext:last-child > DIV.lv_Button.lv_NextButton:last-child
rebelioncorp.org###lightview > DIV.lv_Container > UL.lv_Frames:last-child > LI.lv_PrevNext:last-child
@@||googleusercontent.com$document
@@||istream-xbmc-repo.googlecode.com$document
@@||googlecode.com$document
@@||ia.media-imdb.com$document
@@||tribeca.tvaddons.ag$document
@@||tvaddons.ag$document
@@||api-v2launch.trakt.tv$document
@@||trakt.tv$document
@@||zamcloud.zemana.com$document
||gpsoftware.com.au^$third-party
||gpsoft.com.au^$third-party
@@||crl.microsoft.com$document
@@||www.google.com$document
@@||gdata.youtube.com$document
@@||youtubeonfire.com$document
@@||imdbapi.com$document
@@||api.themoviedb.org$document
@@||www.movietube.cz$document
@@||thetvdb.com$document
@@||cdn.superantispyware.com$document
@@||www.imdbapi.com$document
@@||m.vkool.net$document
@@||cloudyvideos.com$document
@@||xty.me$document
@@||ah-me.com$document
@@||www.vidics.ch$document
@@||movies25.ag$document
@@||viooz.ac$document
@@||zillow.com/homes/for_rent/Albuquerque-NM/house,condo,apartment_duplex_type/23429_rid/paymentd_sort/35.247021,-106.23539,34.917748,-107.117043_rect/10_zm/10_p/$document
@@//www.zillow.com^$document
@@||steamcommunity.com/id/dyingjedi/commentnotifications/$document
@@||secure.bluebird.com$document
@@||www.primewire.ag$document
@@||ads.pushplay.com$urlblock
@@||ads.pushplay.com$document
@@||steamcommunity.com/id/SteamHookups$elemhide,content,urlblock
@@//downloadcenter.samsung.com^$document
@@//talkz.com^$document
europaplay.com##DIV.overlay:nth-child(16)
europaplay.com###content
vikingfence.org###art-main > HEADER.art-header:first-child > DIV.art-shapes:first-child
//www.google.com/cse?q=moving%20mouse%20mute&r=m&cx=partner-pub-3825586834467728%3A1836874994&fexp=20606%2C2631660&client=google-coop&hl=en&type=0&oe=UTF-8&ie=UTF-8&format=p3&ad=p3&nocache=4761434205898332&num=0&output=uds_ads_only&source=gcsc&v=3&allwcallad=1&adext=as1%2Csr1%2Cctc1&bsl=10&u_his=2&u_tz=-360&dt=1434205898333&u_w=1920&u_h=1080&biw=1269&bih=549&psw=1269&psh=233&frm=0&uio=uv3st16sd13sv13lhsl1sr1cc1-&rurl=http%3A%2F%2Fjasonsavard.com%2Fsearch%3Fq%3Dmoving%2Bmouse%2Bmute&referer=http%3A%2F%2Fjasonsavard.com%2Fsearch%3Fq%3Dmoving%2Bmouse%2Bmute#master-1
||google.com/cse/cse.js?language=en&cx=partner-pub-3825586834467728:1836874994$domain=jasonsavard.com,third-party
||google.com/uds/?file=ads&v=3&packages=search&async=2$domain=jasonsavard.com,third-party
||google.com/uds/?file=ads&v=3&packages=search&async=2$third-party
||google.com/cse/cse.js?language=en&cx=partner-pub-3825586834467728:1836874994$third-party
jasonsavard.com###master-1
business.angieslist.com###ctl00_ContentPlaceHolderMainContent_CocoFunnelSection_COCOFunnelPanel
business.angieslist.com###ctl00_ContentPlaceHolderMainContent_CocoFunnelSection_COCOFunnelModal_backgroundElement
free-torrents.org###lx_392229 > DIV.lx_wrap > TABLE.lx_table
thebluebook.com###content > DIV.prospectTrialEndedPopup:nth-child(3) > DIV.message:last-child
thebluebook.com###content > DIV.prospectTrialEndedPopup:nth-child(3)
bitchesofbackpage.com###lightbox > DIV.lb-outerContainer.animating:first-child > DIV.lb-container > DIV.lb-nav:nth-child(2) > A.lb-next:last-child
bitchesofbackpage.com###lightbox > DIV.lb-outerContainer:first-child > DIV.lb-container > DIV.lb-nav:nth-child(2)
thebluebook.com###bs-projectview-modal-lg > DIV.modal-dialog > DIV.modal-content
thebluebook.com###bs-projectview-modal-lg
thebluebook.com##DIV.modal-backdrop.in:nth-child(10)
reallifecam.com##DIV.themodal-overlay:first-child > DIV.modal.denied
reallifecam.com##.modal,.message,.premium,.adg-similar
q-see.com###navbar
q-see.com##HEADER.site-header:nth-child(4) > NAV.navbar.mega.navbar-inverse:nth-child(2) > DIV.navbar-header:nth-child(2) > A.navbar-brand:last-child > SPAN
kcsoftwares.com##DIV.cc_banner-wrapper:first-child > DIV.cc_banner.cc_container.cc_container--open
nolo.com###searchbox_bg
nolo.com###block-block-2523
nolo.com###page > DIV.span-26.last.col_holder:last-child > DIV.span-8.rightcol.last:nth-child(3)
nolo.com###expert_html_container_content_2630781 > DIV.expert-html-container-compound-content.clearfix
nolo.com###responsive-footer
nolo.com###block-expert_sniblet-23
nolo.com###responsive-footer-legal
reallifecam.com##DIV.themodal-overlay:first-child > DIV.modal.message.premium
reallifecam.com##.themodal-overlay
reallifecam.com##
mysalesman.com##DIV.jqmOverlay:first-child
mysalesman.com##DIV.jqmWindow.jqmID1:nth-child(5) > DIV.bw-header:first-child
mysalesman.com##DIV.jqmWindow.jqmID1:nth-child(5)
@@||mailtrack.io$document
loading-system32.net##DIV.header:first-child
loading-system32.net##DIV.image_header:nth-child(2)
loading-system32.net##DIV.content:nth-child(3)
loading-system32.net##DIV.comments:nth-child(4)
loading-system32.net##DIV.footer:nth-child(5)
loading-system32.net##.content
amazon.com###magnifierLens
@@||sigma.validns.com$document
ietab.net###license-dialog
ietab.net###lean_overlay
@@||cpanel.com$document
@@||sigma.validns.com:2080$document
@@//businesshelp.comcast.com^$document
@@//*.client-channel.google.com^$document
@@//%2A.client-channel.google.com^$document
@@//clients4.google.com^$document
@@//*.clients4.google.com^$document 
@@//%2A.clients4.google.com^$document
@@||%2A.clients4.google.com$document
@@||*.clients4.google.com$document
@@||clients4.google.com$document
@@||%2A.client-channel.google.com$document
@@||*.client-channel.google.com$document
@@||client-channel.google.com$document
@@||houzz.com$urlblock
@@||mailtrack.us3.list-manage.com$elemhide,content,urlblock
@@||m.trulia.com$elemhide,content,urlblock
@@||m.trulia.com/rental/3034178333$elemhide,content,urlblock
@@||trulia.com$elemhide,content,urlblock
||dealply.com/^
||dealply.com/
@@||dell.com$urlblock
@@||downloads.dell.com$urlblock
@@||tinycammonitor.com$urlblock
@@||amazon.com$document
@@||walgreens2.shoplocal.com/Walgreens/BrowseByPage$elemhide,content,urlblock
@@||walgreens.com$elemhide,content,urlblock
@@||walgreens2.shoplocal.com$elemhide,content,urlblock
@@||routerlogin.net$elemhide,content,urlblock
@@||lowes.com$elemhide,content,urlblock
@@||grainger.com$document
@@//www.kbb.com^$document

English Filters - Updated 10.11.2016 3pm
Spyware Filter - 10.11.2016 2pm
![clipboard image](https://cloud.githubusercontent.com/assets/22777187/19289043/0e30c8c4-8fc6-11e6-8b30-d5961a699cb6.png)
![clipboard image 1](https://cloud.githubusercontent.com/assets/22777187/19289042/0e309192-8fc6-11e6-8718-0d574413b493.png)
![clipboard image 2](https://cloud.githubusercontent.com/assets/22777187/19289041/0e2c6ff4-8fc6-11e6-9a17-cb65c82ea039.png)

**Operating system**: 
Windows 7 Ultimate Edition latest updates Version: Build 6.1.7600 Build 7600 
http://prnt.sc/csnsww

**Browser**:
Doesn't matter what so ever becasue im running adguard in proxy mode.
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by southwestvinyl** [comment]
Please see all photos that are working here https://github.com/AdguardTeam/AdguardForWindows/issues/1314 but ill be closing that thread.

**Comment by The-Commissioner** [comment]
can you try manualy importing the AG certificate, delete the previous one and import again.

**Comment by Alex-302** [comment]
Incorrect repository. Please continue in https://github.com/AdguardTeam/AdguardForWindows/issues/1314
I can't help with this issue.
