### ISSUE TITLE
zvistka.net - ads

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3178]
![001 jpg](https://cloud.githubusercontent.com/assets/16462533/19301164/b69b0272-9066-11e6-98ee-025e751433f0.png)

Фильтры:
Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский

**Comment by Alex-302** [comment]
Проверь на иоси такие правила:
```
zvistka.net##.pum-container
zvistka.net##div[id*="Composite"]
```

**Comment by Serzh-SUP** [comment]
@Alex-302 рекламы нет

**Comment by Alex-302** [comment]
Ок, добавил в иозный фильтр.
