### ISSUE TITLE
overclockers.ru -  Anti Adblock Script

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3179]
**Повторилось на Windows и iOS**

Фильтры:
Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский

![img_1422 3](https://cloud.githubusercontent.com/assets/16462533/19306351/ed5e25f2-907d-11e6-98b7-5f9f549a3f50.PNG)

![2016-10-12_11-25-02](https://cloud.githubusercontent.com/assets/16462533/19302814/9755d862-906e-11e6-9ab7-789c0d9ee9da.png)

**Comment by Serzh-SUP** [comment]
## Снова Кот, сайт блокируется.
![2016-11-03_18-37-15](https://cloud.githubusercontent.com/assets/16462533/19975442/a344d8e8-a1f4-11e6-9caa-c1d3c7c65abb.png)

**Comment by Alex-302** [comment]
исправил

**Comment by Serzh-SUP** [comment]
**Та же история, только блокировка происходит переходя по ссылке, по любой на главной странице.**

**Comment by Alex-302** [comment]
fixed

**Comment by vgavrish** [comment]
**Снова кот**
https://www.overclockers.ru/lab/71658_7/vybiraem-kompaktnyj-korpus-dlya-sborki-proizvoditelnogo-pk.html
Ф:  1,2,3,4,6,14, Norsk adblockliste
Chrome\Edge
У меня не повторилось

**Comment by str1k3r** [comment]
@vgavrish это мой тикет. я только что проверил как с Norsk так и без - кота больше нет. думаю мой кейс можно закрыть. Спасибо большое!

**Comment by Serzh-SUP** [comment]
**Проблема возобновилась, перешел по [ссылке](https://www.overclockers.ru/hardnews/80580/rossijskij-overkloker-stavit-rekordy-na-geforce-gtx-1070-s-chastotami-2200-9000-mgc.html) с главной [overclockers.ru](overclockers.ru) получил:**
![2016-11-03_18-37-15 2](https://cloud.githubusercontent.com/assets/16462533/20480835/f2b03188-afec-11e6-833e-7f573af76ca7.png)

**А вообще, проблема заключается в том, что у нашего пользователя, не отображается текст статьи, либо появляется КОТ (скрин 1). Также, нет строки указанной на скриншоте (скрин 2), на которой можно дать оценку статье и там же правее, поделиться в соц сетях.**

<details>

![2016-11-18_160943](https://cloud.githubusercontent.com/assets/16462533/20480950/5ce547dc-afed-11e6-9ac3-fcfef5ac863b.png)

![2016-11-21_140117](https://cloud.githubusercontent.com/assets/16462533/20481055/f4749990-afed-11e6-9cfc-0d8bb66d635f.png)

**Comment by str1k3r** [comment]
Подтверждаю слова @Serzh-SUP. Сегодня опять КОТ.

**Comment by Alex-302** [comment]
исправил

**Comment by Pavliknemorozov** [comment]
Как я понял пока, в программе пока отключена блокировка мусора на оверах. Реклама на пол страницы, но вечером даже при этом стал вылетать кот. Помогает побороть кота "отключить защиту".

**Comment by Alex-302** [comment]
Абсолютно чисто.

**Comment by str1k3r** [comment]
Только верхний баннер

**Comment by Alex-302** [comment]
Скрин в студию.

**Comment by str1k3r** [comment]
![image](https://cloud.githubusercontent.com/assets/19888/20542298/115d1a30-b112-11e6-8bb6-9c6233b572e0.png)
![image](https://cloud.githubusercontent.com/assets/19888/20542308/1ceacb4a-b112-11e6-85d9-d14b36601b33.png)

**Comment by Pavliknemorozov** [comment]
Перейти сейчас в конференцию и тут же кота получишь.

**Comment by Alex-302** [comment]
Не вижу помощника. HTTPS на сайте фильтруется?
Откройте журнал фильтрации и обновите страницу. Видны ли запросы?

**Comment by str1k3r** [comment]
Подтверждаю @Pavliknemorozov 
@Alex-302 у меня десктопное приложение

**Comment by str1k3r** [comment]
@Alex-302 
![image](https://cloud.githubusercontent.com/assets/19888/20542412/9533b2f6-b112-11e6-8ecc-43104367ae1e.png)

**Comment by Alex-302** [comment]
@str1k3r тогда жмите **New issue** и добавьте сюда недостающую информацию)

**Comment by Pavliknemorozov** [comment]
У меня помощника в левом нижнем углу нет. А до вчерашнего дня дней 5 не было текста. Думаю, если сейчас появится помощник, пропадёт вся реклама вместе с котом, то опять не будет текста.

**Comment by Pavliknemorozov** [comment]
Ну так как быть? Рекламы на пол страницы и даже сам не могу убрать баннеры пользовательским фильтром, потому что в нижнем правом углу нет помощника.
https://cloud.mail.ru/public/6tDP/3qpAmVDak
https://cloud.mail.ru/public/5FHS/GhqctkeNv

**Comment by Alex-302** [comment]
Как минимум двух верхних строк с рекламой быть не должно.
Попробуйте установить бету. Ещё могу удалённо глянуть, т.к. гадать сложно.

**Comment by Pavliknemorozov** [comment]
А бету где скачать?24.11.2016, 18:45, "Alex" <notifications@github.com>:Как минимум двух верхних строк с рекламой быть не должно.
Попробуйте установить бету. Ещё могу удалённо глянуть, т.к. гадать сложно.

**Comment by Alex-302** [comment]
Отвечайте через сайт, иначе читать неудобно.
Можно в настройках переключить канал обновления
http://ipic.su/img/img7/fs/kiss_46kb.1480002771.png
или с гитхаба
https://github.com/AdguardTeam/AdguardForWindows/releases/download/v6.1.290.1526-rc/Setup.exe

**Comment by Pavliknemorozov** [comment]
Ответил бы через сайт, но что-то сегодня уведомления на мыло не идут.
Начал качать бету, уже в процессе этого появилось окошко, что установлен помощник.
Обновилась программа и всё стало как должно быть. А пару баннеров убрал вручную, их и ранее приходилось убирать вручную. При этом перейдя на сайте в любой обзор или новость, я наконец-то вижу текст статьи. Надеюсь так и будет всегда.
https://cloud.mail.ru/public/rYcf/xYwwjMsrp
И как я раньше не знал про обновление беты, может и не было бы этих проблем...

**Comment by Alex-302** [comment]
> Надеюсь так и будет всегда.

в лучшем случае пару дней) Они почти каждый день детектор блокировки перестраивают.



> пару баннеров убрал вручную

можно скрин этих баннеров?

**Comment by Pavliknemorozov** [comment]
Может это и не баннеры, но верхний белый прямоугольник меня не устраивает и ниже три квадрата с рекламой тоже.
https://cloud.mail.ru/public/8p8B/8dpd7BcnJ
https://cloud.mail.ru/public/J7JC/ZAuSqyD5q

**Comment by Alex-302** [comment]
самый верхний - скрыт.
Остальные гляну.

**Comment by Pavliknemorozov** [comment]
если в комментарии зайти https://forums.overclockers.ru/viewtopic.php?f=58&t=567970&start=20&sid=d5770ffc88e7a48cb1139c15506e1486 то будет кот

**Comment by Alex-302** [comment]
fixed

**Comment by Pavliknemorozov** [comment]
День добрый.
Сегодня в лаборатории кот поселился https://www.overclockers.ru/lab/80987/killing-room-recenziya.html

**Comment by Alex-302** [comment]
Вышвырнули кота)

**Comment by Pavliknemorozov** [comment]
Не зря говорится, у кошек 9 жизней...
