### ISSUE TITLE
appledaily.com.tw - iOS PRO

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3180]
User ID **1428907**

The video won't play at:
http://m.appledaily.com.tw/realtimenews/article/hot/20161011/965746

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.97.13 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.7 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.45 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.21 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.49 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.63.57 Enabled=YES

**Comment by Alex-302** [comment]
Не повторилось. Ломают фильтры или ДНС?

**Comment by Bohdan-SUP** [comment]
Похоже что именно ДНС. Пересоздать в AdguardForIOS ?

**Comment by Alex-302** [comment]
Нужно знать какой именно днс. Если попросишь лог ДНС, то можно здесь попробовать разобраться.

**Comment by Bohdan-SUP** [comment]
Запросил лог.

**Comment by Bohdan-SUP** [comment]
Прислал лог в тикете 1428907

**Comment by Alex-302** [comment]
Юзер прав, ломает блокировка 2mdn.net Исключил.
