### ISSUE TITLE
4pda.ru - ad

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3181]
# Фильтры:

**Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский**

![2016-10-12_14-25-10](https://cloud.githubusercontent.com/assets/16462533/19308643/5cfe3ffe-9089-11e6-8dfd-fcaf1a1ffb90.png)

**Comment by Alex-302** [comment]
Поправил.

**Comment by vgavrish** [comment]
Можно на Андроид поправить? http://prntscr.com/ctohok
Фильтры: 1,2,3,4,11,14

**Comment by Alex-302** [comment]
Новая бета эти правила уже поддерживает. Отступ трогать не рекомендую, т.к. они порядок элементов меняют и потом ломаются новости. Этот отступ равнозначен новости.

**Comment by Alex-302** [comment]
Может позже поправим, когда они перестанут постоянно переделывать код.

**Comment by Bohdan-SUP** [comment]
@Alex-302 на iOS можно исправить?

**Comment by OlegSUP** [comment]
@Alex-302 
Ещё один случай на iOS Pro

<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24334683/73c9c7c4-1277-11e7-83c8-89ab52867093.png)

</details>

**Comment by Alex-302** [comment]
на проверку
```
4pda.ru##header#header+div[id] > div[class*=" "]~div:empty+div:empty+div:empty+div[class*=" "] > section > article > article.post > div.visual > a
```

**Comment by evgeniy-ADG** [comment]
оно в iOS не добавляется, выдает ошибку "rule text is invalid".

**Comment by Alex-302** [comment]
`:empty` видать не переваривает. Нужно новую версию ждать.

**Comment by deLumren** [comment]
Еще одна жалоба 1541224

**Comment by Alex-302** [comment]
OS: 10.3.1
бета-тестеры иоси должны ждать, пока яблоко свои баги исправит.
