### ISSUE TITLE
keeplinks.eu

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3183]
**Current behaviour**: 'Hide your referrer from third party' in Stealth mode breaks the captcha at keeplinks.eu

Screenshot - http://imgur.com/eOiC14v

Reported by user **1023133**, ticket CNI-966-57211

**Comment by Alex-302** [comment]
У меня и без Адгарда ссылки не преобразуются этим сервисом.

**Comment by The-Commissioner** [comment]
The ticket was closed abruptly, can you please explain in english.

**Comment by Alex-302** [comment]
@The-Commissioner Hello
Please check this rule in user filter:
```
@@||api-secure.solvemedia.com^$stealth
```

**Comment by The-Commissioner** [comment]
@Alex-302 this works great now, thanx so much for your time :-) 
This issue can be closed now. Thanx to @Bohdan-SUP also

**Comment by Alex-302** [comment]
Ok.
