### ISSUE TITLE
https://sheva7.co.il/ 

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#31834]
***Description***:
Hi
have more ads and Popup in site: 
https://sheva7.co.il/

* **Current behaviour**: 
http://prntscr.com/n561g7
http://prntscr.com/n561md
http://prntscr.com/n561pm
and have more!
- i thine this same problem like:
https://github.com/AdguardTeam/AdguardFilters/issues/27607

***Steps to reproduce the problem***:
open the site:
https://sheva7.co.il

Information | Value
-- | --
Operating system: | win 10
Browser: | Google Chrome
AdGuard version: |6.4.1814.4903

Filters enabled:  
EasyList Hebrew,
EasyPrivacy,
AdGuard Annoyances,
AdGuard Base,
Adblock Warning Removal List

AdGuard DNS:  None
Stealth mode options (Windows only): not enabled

**Comment by MrTal** [comment]
@AdamWr 
@Alex-302

**Comment by AdamWr** [comment]
Could you please update filters and check if you still see these ads?

**Comment by MrTal** [comment]
@Alex-302 
now this work, tank you.

**Comment by AdamWr** [comment]
Ok, thank you for your reply.
