### ISSUE TITLE
empty space after blocking ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3184]
638562
**Description**: Проблема в блокировке сообщения от Яндекс браузера в поиске яндекса. После добавления Фильтра раздражителей, у пользователя осталось только пустое поле без рекламы.  

Расширения отключали, кэш браузера чистили. Пользовательский фильтр отключен

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19315814/ddabefc0-90a7-11e6-9058-0e045b28e7bf.png)
</details>

**Adguard version**: 6.1.258.1302

**Filters list**: фильтр счетчиков и системы аналитики, фильтр виджетов социальных сетей, фильтр раздражителей, русский фильтр, английский

**Browser**: Версия Вивальди 1.4.589.38 (Stable channel) (32 бит), 
Версия Опера 40.0.2308.81

как выглядит страница у пользователя
https://yadi.sk/d/fl9hdkPdwiQ3U

**Comment by Alex-302** [comment]
Не повторилось.
