### ISSUE TITLE
lemonde.fr

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3185]
http://www.lemonde.fr/proche-orient/article/2016/10/09/jerusalem-plusieurs-blesses-lors-d-une-attaque-a-l-arme-a-feu_5010635_3218.html

Screenshot:
<details>
![image1](https://cloud.githubusercontent.com/assets/14153331/19319078/e2a5341c-90b3-11e6-9fae-eff8920d685c.png)
</details>

**Filters:**
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.48 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.93 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.24 Enabled=NO
ID=5 Name="Experimental filter" Version=1.0.26.27 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.9 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.44 Enabled=YES
ID=101 Name="EasyList" Version=1.0.63.36 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.66.61 Enabled=YES
ID=113 Name="Liste FR" Version=1.0.66.79 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.66.75 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.60 Enabled=YES

**Comment by Alex-302** [comment]
Can't reproduce.
Try with
ID=2 Name="English filter" Version=1.0.96.48 Enabled=YES
ID=113 Name="Liste FR" Version=1.0.66.79 Enabled=YES
