### ISSUE TITLE
tradingmania.it

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3186]
http://www.tradingmania.it/

user 1427037

<details>
![img_0452](https://cloud.githubusercontent.com/assets/14153331/19319499/c8dcb2c4-90b5-11e6-8409-f0642ba1662c.jpg)
</details>

**Filters subscriptions**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.29 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.87 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.23 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.43 Enabled=YES
ID=101 Name="EasyList" Version=1.0.63.30 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.66.50 Enabled=YES
ID=109 Name="EasyList Italy" Version=1.0.66.50 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.66.64 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.66.52 Enabled=YES
ID=206 Name="Xfiles" Version=1.0.0.57 Enabled=NO

**Comment by Alex-302** [comment]
Added to English filter
```
||tradingmania.it/wp-content/uploads/*bdswiss$image
||tradingmania.it/wp-content/uploads/2016/09/corso-trading-online.gif
||tradingmania.it/wp-content/uploads/2016/06/Bonus-100-mania.jpg

```
