### ISSUE TITLE
startpage.com – ad-sponsored search results

### ISSUE THREAD

**Issue by JayBrown** [AdguardTeam/AdguardFilters#31861]
***Description***: ad-sponsored links in startpage.com search results
* **Current behaviour**:

ad-sponsored links in startpage.com search results are now showing up again; this problem only started today (31 Mar 2019); tested again after updating filters

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/bCSKkF4.jpg)
</details><br/>

* **Expected behaviour**: 

Should not show any ad-sponsored search results

***Steps to reproduce the problem***:

go to startpage.com ; search for anything ; ad-sponsored search results will show up

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | macOS 10.4.4
Browser:                               | Firefox 66.0.2
AdGuard version:                       | Adguard Desktop for Mac 1.5.14
Filters enabled:                       | AdGuard Base, Easy List, Peter Lowe, AdGuard Tracking Protection, EasyPrivacy, Fanboy's Enhanced Tracking, Fanboy Anti-Facebook, AdGuard Social Media, Fanboy's Social Blocking, Adguard Annoyances, Fanboy's Annoyances, Adblock Warning Removal, I don't care about cookies, Fanboy's Cookiemonster, Malware Domains, Spam404, NoCoin, AdGuard Russian, AdGuard German, AdGuard Japanese, AdGuard Dutch, AdGuard Spanish/Portugese, AdGuard French, AdGuard Czech & Slovak, EasyList Germany, EasyList Italy, Icelandic ABP, ricklist, AakList (Anti-Adblock Killer), Block-EU-Cookie-Shit-List, and a couple of rules in the user filter
AdGuard DNS:                           | None

**Comment by BlazDT** [comment]
Not reproduced. @AdamWr please check.

**Comment by JayBrown** [comment]
There were apparently some TLS problems with the startpage site. (Whether related to Adguard's man-in-the-middle I can't say.) Firefox always dropped the initial connection, offering the "Try again" button, and then it worked, but the ads started to appear.

The TLS problems are now gone, and so are the ads. Weird thing, though.
