### ISSUE TITLE
icefilms.info - clickunder

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3187]
Simply click anywhere at icefilms.info

Screenshot: 
<details>
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/14153331/19365437/7709bfe6-919b-11e6-8f2e-43ff853c6171.gif)

</details>

reported by user 1427697

**Comment by Alex-302** [comment]
Added to English filter
```
icefilms.info#%#Object.defineProperties(window, { "_impspcabe_alpha": { value: false, writable: false }, "_impspcabe_beta": { value: false, writable: false } }
```
