### ISSUE TITLE
iledebeaute.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3188]
**Description**: Расширение. Реклама на фоне
http://iledebeaute.ru/

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19379234/a413e1d4-91f9-11e6-9cda-3c7ffc7ba0cd.png)
</details>

**Filters list**: русский, английский, RU AdList

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
iledebeaute.ru##.banner
iledebeaute.ru#$#body { background: #EBDAEA url(http://static.iledebeaute.ru/@/css/pattern.jpg)!important; }

```
