### ISSUE TITLE
[android] com.nbcuni.nbc missed video ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#319]
https://play.google.com/store/apps/details?id=com.nbcuni.nbc

**Comment by Alex-302** [comment]
||nbc-jite.s3.amazonaws.com^$empty

**Comment by ameshkov** [comment]
Сломало плеер вообще говорит

**Comment by Alex-302** [comment]
оч странно. Может ему лень было правило полностью набирать и он amazonaws.com^$empty добавил?
Если правило расширить до s3.amazonaws.com^$empty - всё ломается.
