### ISSUE TITLE
Userfilter rules won't work with Annoyances filter enabled

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3190]
**Description**: **Extension for Firefox**

**Rules should block:**
- Russian subforum
- Mac subforum
- the adguard IOS subforum and the android subforum. 

**Steps to reproduce the problem**:

*  Enable English, Spyware, Social,Annoyance, Easyprivacy and FB annoyances filters.
*  Add following rules to a userfilter:

forum.adguard.com###english-forums\.47 > .nodeList > .node_84.level_2.category_forum.node
forum.adguard.com###english-forums\.47 > .nodeList > .node_79.level_2.category_forum.node
forum.adguard.com###english-forums\.47 > .nodeList > .node_74.level_2.category_forum.node
forum.adguard.com###russian-forums-russkie-forumy\.3

**Then**
* Go to forum.adguard.com and mentioned subforums are still there:
- Page refresh, private window and Firefox restart won't help:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19388648/5d112aaa-9229-11e6-9325-63f8be7b5d5b.png)
</details>

* Disabled Annoyances filter;
* Relaunch Firefox; 
* Go to forum.adguard.com -> now the subforums are blocked (you may need to refresh the page 2-3 times):
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19388688/9bb3cf24-9229-11e6-9012-e2d6afed2801.png)
</details>

Works fine with Chrome extension or application.

**Adguard version**: 2.3.8

**Browser**: FF 49.0.1

Reported by user **1023133**
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce.
```
forum.adguard.com##[id="russian-forums-russkie-forumy.3"]
forum.adguard.com##.nodeList > li[class="node category_forum level_2 node_79"]
forum.adguard.com##.nodeList > li[class="node category_forum level_2 node_84"]
```
