### ISSUE TITLE
WomanLog

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3191]
id 1428019
**Description**: Реклама в приложении
https://appsto.re/ru/kqxhz.i

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19389233/d2e1f05a-922b-11e6-80e7-82c7b2585524.png)

</details>

**Adguard version**: 1.1.1.23

**Filters list**:
<details>
Optimazed enabled: NO
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.95 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.3 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.43 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.12 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.40.73 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.28 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.14 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.49 Enabled=YES
ID=101 Name="EasyList" Version=1.0.63.54 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.66.90 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.63.55 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.63.70 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.67.21 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.67.3 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.26 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.67.4 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.1.78 Enabled=YES
ID=220 Name="CJX's Annoyance List" Version=1.0.0.66 Enabled=YES
ID=225 Name="Fanboy Anti-Facebook List" Version=1.0.0.7 Enabled=YES
ID=229 Name="I dont care about cookies" Version=1.0.0.5 Enabled=YES
ID=204 Name="Peter Lowe's list" Version=1.0.2.38 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.63.89 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.63.59 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.61 Enabled=YES
ID=228 Name="xinggsf" Version=1.0.0.74 Enabled=YES
</details>

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Крайне много фильтров. Лимит - 50000 правил.
