### ISSUE TITLE
m.basketnews.lt

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3194]
**Description**: https://m.basketnews.lt/

Screenshot:
<details>
![image1 1](https://cloud.githubusercontent.com/assets/14153331/19392486/984f9920-9239-11e6-92f5-084ad0bcd472.png)
</details>

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.90 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.77 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.12.97 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.5.10 Enabled=YES
ID=18 Name="Dutch filter" Version=1.0.9 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.13 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.49 Enabled=YES
ID=10 Name="EasyList Lithuania" Version=1.0.0.91 Enabled=NO

**Comment by Alex-302** [comment]
Added to English filter
```
m.basketnews.lt##div[style^="text-align: center; width: 300px; height: 250px;"]
m.basketnews.lt##.main_title > div[style="text-align: center;"] > a > img
```
