### ISSUE TITLE
stampedeblue.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3195]
**Description**: Team Shop is showing up, reproduced on desktop with useragent as well.
http://www.stampedeblue.com/2016/10/11/13252456/2016-nfl-week-5-inside-the-colts-numbers-winning-ugly#comments
Reported by customer **1429417**

Screenshot: 
<details>

![image1 2](https://cloud.githubusercontent.com/assets/14153331/19394481/0ea28864-9242-11e6-963c-00e519601a55.png)
</details>

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.97.6 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.2 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.44 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.16 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.48 Enabled=YES

**Comment by Alex-302** [comment]
Check this rule:
```
stampedeblue.com##.l-col__sidebar > aside[class="c-rock-list"]
```
