### ISSUE TITLE
spidersweb.pl

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3196]
**Description**:  http://www.spidersweb.pl/2016/10/iphone-7-plus-recenzja.html
Ad before and after the article. Customer ID **1429316**

Screenshot: 
<details>
![image1 3](https://cloud.githubusercontent.com/assets/14153331/19395617/2b713210-9247-11e6-846f-4d994ef9adf9.png)
</details>

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.97.16 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.8 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.46 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.18 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.50 Enabled=YES
ID=117 Name="Adblock Polska" Version=1.0.0.52 Enabled=YES
ID=216 Name="Adblock polskie reguły" Version=1.0.4.90 Enabled=YES

**Comment by Alex-302** [comment]
Added to English filter
```
spidersweb.pl##a[href^="http://clk.tradedoubler.com/click?"] > img
spidersweb.pl##a[href^="https://www.playstation.com/"] > img

```
