### ISSUE TITLE
Rules of 3 seconds timer for ad video.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardFilters#31966]
@AdamWr 
@Alex-302 

https://jspenguin2017.github.io/uBlockProtector/

Nano Defender + Nano Adblocker have rules of 3 seconds timer for ad video.
Ex: The original ad video takes 30 seconds.
But it will only take 3 seconds with Nano.

https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb

https://chrome.google.com/webstore/detail/nano-adblocker/gabbbocakeomblphkmmnoamkioajlkfo

https://github.com/AdguardTeam/AdguardFilters/issues/18815#issuecomment-468868509

It seems that AG filter devs can't make rules for skipping its ad videos.
https://ani.gamer.com.tw/

With AG, need to wait for 30 sec until the countdown of ad video ends.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/IGr6MVD.png)
</details><br/>

With Nano, only take 3 sec.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/8T6iI6K.png)
</details><br/>

At least, may you make rules/scripts of 3 seconds timer for ad video such like Nano?
Thanks.

**Comment by lancelot-moon** [comment]
I found this though it can't skip ad video on https://ani.gamer.com.tw/.
https://adsbypasser.github.io/

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardExtra #3](https://github.com/AdguardTeam/AdGuardExtra/issues/3) via [**ZenHub**](https://www.zenhub.com/)
