### ISSUE TITLE
dtorrent.com.br, blockadblock.com, bludv.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3198]
**Current behaviour**: websites use blockadblock system

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19416186/8924f134-9392-11e6-9ebb-7564545c415d.png)
</details>

**Filters list**:
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19416213/a8644544-9393-11e6-9d2d-3c40c246d6f9.png)
</details>

**Comment by Alex-302** [comment]
Fixed
