### ISSUE TITLE
comandofilmes.net

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3199]
http://www.comandofilmes.net/

Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19416219/d64bdda0-9393-11e6-97e2-957f0061e44c.png)
</details>

**Filters list**:
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19416213/a8644544-9393-11e6-9d2d-3c40c246d6f9.png)
</details>

**Comment by Alex-302** [comment]
Added to Spanish filter
```
@@||comandofilmes.net^$generichide
```
