### ISSUE TITLE
tishreen.news.sy

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#32002]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: The site autoplays what I assume is the Syrian national anthem, with no apparent way to turn it off before the anthem ends.
* **Current behaviour**: See above.

[//]: # (Substitute this line with a description of the problem)

Having previously submitted annoyances-related stuff to *uBlock Filters - Annoyances* instead, I decided to try to submit something for **AdGuard Annoyances filter** instead this time.

I am aware that this issue may or may not be slightly politically contentious, seeing as `tishreen.news.sy` is a very Assad-faithful newssite and thus would be likely to be overly patriotic by playing the anthem and such. But seeing as there's no way to turn off the anthem, I think that makes it qualify for annoyances lists in general.

My suggestion for a fix is `||tishreen.news.sy/wp-content/uploads/syr.*^`.

* **Screenshot:**

Not applicable, as the problem is audio-only.

* **Expected behaviour**: 

Ideally they shouldn't have had a song autoplay on a newssite with no way to turn it off.

***Steps to reproduce the problem***:

* Visit `http://tishreen.news.sy/`.
* Wait up to 5 seconds, or for the page to fully load, whichever comes last.

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)
![image](https://user-images.githubusercontent.com/22780683/55428460-6f6ff700-5589-11e9-8c8e-1234fea6926a.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 October 2018 Update
Operating system version (Android/iOS) | 
Browser:                               | Google Chrome
AdGuard version:                       | Tested in Nano Adblocker 1.0.0.100 (Can test in AdGuard's desktop version on request.)
Filters enabled:                       |  See the filters screencap above.
AdGuard mode (Android only):           | 
Filtering quality (Android only):      | 
HTTPS filtering (Android only):        | 
Simplified filters (iOS only)          | 
AdGuard DNS:                           | None
Stealth mode options (Windows only)    |
Helpdesk ID (if exists):               |

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Ok.
