### ISSUE TITLE
get-albums.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3200]
1431218
**Description**: Реклама вверху и слева
http://get-albums.ru/

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19416320/9b701914-9396-11e6-98f4-4d8a0bef17e8.png)
![image](https://cloud.githubusercontent.com/assets/18548949/19416327/b7da688e-9396-11e6-9156-e2276cd9072b.png)

</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
