### ISSUE TITLE
yuncomics.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3201]
**Description**: http://www.yuncomics.com/archives/1791519
Works fine with macOS Safari + useragent
Customer ID **1429917**

Screenshot: use the following code

<details>

![image](https://cloud.githubusercontent.com/assets/14153331/19416662/459620f2-939f-11e6-8b66-06468182f986.png)
</details>

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.97.26 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.12 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.50 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.25 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.93.2 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.29 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.21 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.51 Enabled=YES
ID=101 Name="EasyList" Version=1.0.63.61 Enabled=YES
ID=224 Name="Korean Adblock List" Version=1.0.0.2 Enabled=YES
ID=227 Name="List-KR" Version=1.0.1.19 Enabled=YES

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by Bohdan-SUP** [comment]
So do I on a desktop with useragent.

**Comment by Alex-302** [comment]
On Windows or MacOS?

**Comment by Bohdan-SUP** [comment]
Mac, of course) Safari 9 with iPhone useragent + Adguard extension. Don't have access to real iOS for now.

**Comment by SlowMemory** [comment]
Possibly related to https://github.com/AdguardTeam/AdguardForiOS/issues/184

**Comment by Alex-302** [comment]
> Mac, of course) Safari 9 with iPhone useragent

still can't reproduce. Works as expected.

**Comment by ameshkov** [comment]
I suggest trying `@@||yuncomics.com^$elemhide`. If it helps let's add it to safari filter.

**Comment by SlowMemory** [comment]
But the current rule @@||yuncomics.com^$generichide works in other browsers. Shouldn't it work on Safari as well..?

**Comment by ameshkov** [comment]
I need to get the actual content blocker file used by an iOS version.

@gshumihin here's what I need you to do:
1. Reproduce the issue on iPad or iPhone 
2. Send a message to support.
3. Get "filters.gz" file from that message and attach it to this issue.

**Comment by gshumihin** [comment]
Here's it:
[filter.gz](https://github.com/AdguardTeam/AdguardFilters/files/536178/filter.gz)
