### ISSUE TITLE
m.pikabu.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3202]
id 1429952
Некорректная блокировка на странице:
http://m.pikabu.ru/

Исчезают изображения. Проблема наблюдается при включенных фильтрах - Anti-Adblock Killer | Reek, RU AdList: Counters и RU AdList: BitBlock

Application version: 1.1.0.53

<details>

![image](https://cloud.githubusercontent.com/assets/18548949/19416798/845c5a4c-93a2-11e6-9c57-e59cb6ecf01d.png)

![image](https://cloud.githubusercontent.com/assets/18548949/19416800/8a95b368-93a2-11e6-815a-2f736d2ed4fc.png)

**Comment by Alex-302** [comment]
Не на чем повторить. Какой именно фильтр ломает? Или любой из трёх?

**Comment by Sirse** [comment]
Сейчас сайт разваливается с включенным фильтром русской рекламы. Когда сообщал об ошибках (два дня назад) отключал только три фильтра из верхнего поста, сайт грузился нормально.

**Comment by Alex-302** [comment]
@Sirse а можете с одним только русским фильтром повторить и снова отправить сообщение в поддержку с диагностической информацией? Мне это сильно поможет.
Отдельно можете проверить в пользовательском фильтре такое правило:
```
@@||m.pikabu.ru^$urlblock
```
Ещё вопрос - фильтрация DNS включена? Если да, то какой вариант?

**Comment by Sirse** [comment]
На гитхаб кинуть ответ или на мыло?

**Comment by Alex-302** [comment]
Файл filter.gz нужен. Его можно прямо сюда.

**Comment by Sirse** [comment]
Отключил все фильтры кроме русского, стало ещё забавней, на некоторых сайтах поехала вёрстка (нет изображений), некоторые вообще не грузятся в Safari. Из блокировщиков только AdGuard, DNS блокировки нет.
![photo_2016-10-16_21-37-46](https://cloud.githubusercontent.com/assets/3335371/19418169/df50f7be-93e8-11e6-926d-2ab295732152.jpg)
![photo_2016-10-16_21-37-50](https://cloud.githubusercontent.com/assets/3335371/19418172/df51c220-93e8-11e6-8097-96d83e27adaa.jpg)
![photo_2016-10-16_21-37-53](https://cloud.githubusercontent.com/assets/3335371/19418170/df51829c-93e8-11e6-8d28-02cefac0cc0a.jpg)
![photo_2016-10-16_21-37-56](https://cloud.githubusercontent.com/assets/3335371/19418171/df51c11c-93e8-11e6-817b-75afbe90093c.jpg)
[filter.gz](https://github.com/AdguardTeam/AdguardFilters/files/531877/filter.gz)

**Comment by Alex-302** [comment]
Ок, будем смотреть.

**Comment by Alex-302** [comment]
@Sirse проверьте обновление фильтров. Сутра ошибка закралась, а Адгард для Сафари таким вот неожиданным образом отреагировал.

**Comment by vgavrish** [comment]
1431791
Такая же проблема у другого пользователя с отображением сайта

> Проблема заключается именно в фильтре RU AdList:Bitblock
отключив этот фильтр и оставив все остальные, сайт m.pikabu.ru начал нормально отображаться

**Comment by Alex-302** [comment]
Уже не та же проблема.
Этот фильтр достаточно опасный, особенно в сафари с его багами.
Для пользовательского фильтра:
```
@@||pikabu.ru^$third-party,~image
```
