### ISSUE TITLE
[Windows] www.techpowerup.com - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#3203]
![](http://i.imgur.com/Yn3HmOV.png)

https://www.techpowerup.com/

**Adguard version**: 6.1.273.1479

**Operating system**: Windows 10

**Browser**: Chrome

``` techpowerup.com##.bgujfgdn ```

**Comment by Alex-302** [comment]
Reproduced. Added.
