### ISSUE TITLE
365Scores -ios adgurd pro

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#32047]
Issue URL (Ads):
https://itunes.apple.com/us/app/365scores-live-scores/id571801488?mt=8

Screenshots:
http://prntscr.com/n6zt82

System configuration:

Information | value
-- | --
Platform: | iOS
AdGuard version: | 2.1.1
System wide filtering: | enabled
Simplified filters: | disabled
AdGuard DNS: | Default
Filters: | AdGuard Mobile Ads,AdGuard Safari,AdGuard Base, Spyware filter, safari filter, EasyList Hebrew

**Comment by Alex-302** [comment]
@MrTal I can't reproduce. Please clear DNS log, reproduce an issue and make screenshot on DNS log.

**Comment by MrTal** [comment]
@Alex-302 
 http://prntscr.com/n86gp7

**Comment by MrTal** [comment]
@Alex-302
 still have ads:
http://prntscr.com/n9muyj
log:
http://prntscr.com/n9mv41
and
http://prntscr.com/n9mv79

**Comment by Alex-302** [comment]
Please enable-disable airplane mode, clear DNS log and reproduce an issue. Maybe some records are cached.

**Comment by MrTal** [comment]
@Alex-302 
on now i see for now this work and no have popup and ads,
but i think we'll wait day for will sure no have ads nothing
tnak you

**Comment by Alex-302** [comment]
ok

**Comment by MrTal** [comment]
@Alex-302 
ok, this work good and no have ads
tank you

**Comment by MrTal** [comment]
@AdamWr 
@Alex-302 
Hi
the ads back...
log:
http://prntscr.com/nhqao0
screenshot:
http://prntscr.com/nhqb0q

**Comment by Alex-302** [comment]
@MrTal this is Facebook Ads. Can be blocked only blocking `graph.facebook.com` only.
