### ISSUE TITLE
androidobzor.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3204]
**Description**: Реклама
http://androidobzor.com/?p=3900

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19426274/d225a48a-9443-11e6-9c2a-8e8655ae7e34.png)
</details>

**Adguard version**: 2.8

**Filters list**: 1,2,3,4,11,14

**Operating system**: Андроид

**Browser**: Встроенный

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Russian filter
```
androidobzor.com##.sb_popup
androidobzor.com##.jqmOverlay

```
