### ISSUE TITLE
sport.ua

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3205]
Ads in video-player:
http://basketball.sport.ua/news/322190

Screenshot:

![image](https://cloud.githubusercontent.com/assets/14153331/19438828/5c464738-9484-11e6-8925-4e86576b08bd.png)

**Filters list**:
![image](https://cloud.githubusercontent.com/assets/14153331/19438863/882d69d0-9484-11e6-9326-019f9e8cdba1.png)

Customer ID **1432233**

**Comment by Alex-302** [comment]
Added to Russian filter
```
||rtb.meta.ua/sport/get_vast.cgi$replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/
||cobrand.ria.com^$third-party
||meta.ua/rest.asp?hostURL=
||rtb.meta.ua/*/get_vast.cgi?rtb=
```
Added to Spyware filter
```
||videostat.meta.ua^
||ms.meta.ua/vast/cache_url.php?callback=
||meta.ua/f_new.asp?g=
```
