### ISSUE TITLE
ajaxshowtime.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3206]
https://www.ajaxshowtime.com/article/hoofdnieuws/99782/viergever-mocht-van-bosz-niet-vertrekken

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19441942/3c087e3a-9490-11e6-8045-91e445e43341.png)
</details>

**Filters list**:
![image](https://cloud.githubusercontent.com/assets/14153331/19441901/12b0dfc8-9490-11e6-8d77-15eccb07c9cf.png)

Reported by customer **1431946**

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
ajaxshowtime.com##.ablo
```
Added to Dutch filter
```
@@/ad_bomb/*$image,domain=ajaxshowtime.com
```
