### ISSUE TITLE
tvshowtime.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3207]
**Description**: www.tvshowtime.com/en/show/95011

**Current behaviour**: 
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19442574/67c1d8e4-9492-11e6-81f3-7b6a77cca78b.png)
</details>

**Expected behaviour**: 
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19442570/6255ea58-9492-11e6-85da-2497261cc9c1.png)
</details>

**Filters list**:
![image](https://cloud.githubusercontent.com/assets/14153331/19442559/58d84dea-9492-11e6-8fa8-7a8a22c1ad9a.png)

Customer ID **1429979**

**Comment by Alex-302** [comment]
Added to Russian filter
```
tvshowtime.com#@##top-banner
```
