### ISSUE TITLE
Disqus widget

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3209]
Is it possible to block Disqus comments and comment counter:
1. At some particular website, for example redmondpie.com
2. For every website?

Screenshots:
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19445039/7ddb45d0-949b-11e6-9114-9997a65eca10.png)
![image](https://cloud.githubusercontent.com/assets/14153331/19445044/8099f154-949b-11e6-9ed8-03f7c2d44af6.png)
</details>

Customer ID **1426738**

**Comment by Alex-302** [comment]
```
||disqus.com/embed.js$third-party
||disqus.com/count.js$third-party
~disqus.com###disqus_thread
```
