### ISSUE TITLE
EpicGames.com - Unable to shop at store (AdGuard Tracking Protection filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#32092]
### Affected site:
`https://www.epicgames.com/store/`

### Issue:
Unable to shop at store.
Gets stuck at "Loading your order...".

### Screenshots:
* **Screenshot 1 (stuck page):**

![filterissue-epicgames1](https://user-images.githubusercontent.com/9382674/55572634-50e43a00-5708-11e9-8b3f-69a8fd183a6e.jpg)

* **Screenshot 2 (uBO logger):**

![filterissue-epicgames2](https://user-images.githubusercontent.com/9382674/55572651-59d50b80-5708-11e9-9112-3538fb671048.jpg)

### Problem filter:
* AdGuard Tracking Protection filter (a.k.a. 'AdGuard Spyware filter')

### Problem rule:
`||tracking.epicgames.com^`

### Blocked script:
`https://tracking.epicgames.com/tracking.js`

### Possible fix (confirmed working):
`@@||tracking.epicgames.com/tracking.js$first-party`

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.4.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.10 (XUL)

**Comment by BlazDT** [comment]
Thank you for the report, I removed the rule as it seems it is only requested on first-party base.
