### ISSUE TITLE
gidonlinehd.ru -pop ups

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3211]
Windows 10
Adguard 6.1
Detected in Chrome, Yandex
Filters 
<details>
![image](https://cloud.githubusercontent.com/assets/20476168/19451380/b8b27b96-94b5-11e6-9f47-68cb5e6d4607.png)
</details>
Link
http://gidonlinehd.ru/2016/07/bolnica-nikerboker

When you click on video area the first time to pay it, you get advert pop-up that immediately closes.
Unfortunately, can't screen. It happens too fast.

**Comment by Alex-302** [comment]
Fixed.
