### ISSUE TITLE
extratorrent.cc - ads

### ISSUE THREAD

**Issue by MarkoXD** [AdguardTeam/AdguardFilters#3212]
Ads are visible on extratorrent.cc

Activated filters:

- English filter
- Spyware filter
- Social filter
- Annoyances filter
- EasyPrivacy
- Adblock Warning Removal Lists
- Anti-Adblock Killer | Reek
- I dont care about cookies
- Malware Domains

![screenshot_1](https://cloud.githubusercontent.com/assets/7421544/19471953/8cf0b854-9525-11e6-8eaf-1d72a029bcc6.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/7421544/19471952/8ceba846-9525-11e6-9fdc-9c96383844c0.png)

**Comment by Alex-302** [comment]
@MarkoXD Which Adguard version are you using? I can't reproduce even with one English filter.

**Comment by MarkoXD** [comment]
I'm using Adguard Browser Extension v2.4.14 & Opera 40.0.2308.90.

**Comment by Alex-302** [comment]
Please check this rule in user filter:
```
|ws*://*$domain=http://extratorrent.cc
```

**Comment by Alex-302** [comment]
Please check this rule in user filter:
```
|ws*://*$domain=extratorrent.cc
```

**Comment by MarkoXD** [comment]
Ads are still visible with this rule. Now instead showing girl ads, it's showing loading.

![screenshot_1](https://cloud.githubusercontent.com/assets/7421544/19484349/959c3492-9557-11e6-8cf1-0cdad62d2923.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/7421544/19484350/95b916c0-9557-11e6-9804-afb1053dd08e.png)

**Comment by Alex-302** [comment]
It is expected result:) That ads are blocked.
This rule will hide leftovers:
```
extratorrent.cc#$#div[id^="MarketGid"] { position: absolute!important; left: -2000px!important; }
```

**Comment by MarkoXD** [comment]
I can still see VPN ads. Is it possible to remove them?
