### ISSUE TITLE
beta.speedtest.net

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#3214]
When you start the test, 'Connecting...' never ends unless you disable Adguard.

Tested in Chrome with Adguard for Windows.

Original thread:
https://forum.adguard.com/index.php?threads/adguard-%D0%B4%D0%BB%D1%8F-windows-%D0%91%D0%B5%D1%82%D0%B0-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F-6-1-273-1479-r2.14749/page-2#post-107189

**Comment by Alex-302** [comment]
Added to English filter
```
@@|http*:*/ws|$domain=beta.speedtest.net
```
