### ISSUE TITLE
missed ads and trackers on iphone

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#3216]
sorry for moving this around so much. i figured this would be the best place to post this. i added some more filters i found

c00.adobe.com (adobe marketing)
apptentive.com (apptentive helps companies engage mobile customers/advertise )
apptimize.com (analytics company)
urbanairship.com (Advertisements, Analytics company)
datametrical.com
instabug.com (crash reporting analytics)
adtilt.com
log.iyunmai.com
stats.jpush.cn
umeng.com (https://techcrunch.com/2013/11/20/umeng-alibaba/)
collect-elb-_.amazonaws.com (http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-access-logs.html)
appboy.com ( mobile marketing company)
adserver.pandora.com
intowow.com (mobile video advertising)
device-analytics.rollout.io
ce-global-track-_.amazonaws.com
analytics-rollout-*.amazonaws.com
data.mob.com
stats.pandora.com
log.musical.ly
stats.paypal.com
metrics.mzstatic.com

here is the log file for some of the trackers above. i removed unneeded lines: https://nopaste.me/view/402b702f

**Comment by Alex-302** [comment]
app.link,branch.io - will break some Android apps
umeng.com - too wide. Some services will be boken
appboy.com - I don't recommend to block it completely

Added to Spyware filter
```
||collect-elb-*.amazonaws.com^$empty
||stats.jpush.cn^$empty
||log.iyunmai.com^$empty
||instabug.com^$empty
||datametrical.com^$empty
||apptimize.com^$empty
||apptentive.com^$empty
||c00.adobe.com^$empty
||device-analytics.rollout.io^$empty
||data.mob.com^$empty
||stats.pandora.com^$empty
||log.musical.ly^$empty
||stats.paypal.com^$empty
||metrics.mzstatic.com^$empty
```
Added to Mobile filter
```
||intowow.com^$empty
||adtilt.com^$empty
```

**Comment by Alex-302** [comment]
You can check for new rules after two days in this file
```
https://raw.githubusercontent.com/AdguardTeam/AdguardDNS/master/Filters/filter.txt
```

**Comment by jo2dan23** [comment]
@Alex-302 thanks for adding these. Here are some ones that got missed.

adserver.pandora.com
analytics-rollout-*.amazonaws.com
ce-global-track-.amazonaws.com
urbanairship.com

**Comment by jo2dan23** [comment]
@Alex-302 i understand not wanting to block the whole domains of these. But can we atleast try these?

shared.iad.appboy.com
alog.umeng.com
dev.appboy.com

**Comment by jo2dan23** [comment]
also idk if you missed urbanairship by accident or purpose but it has too many subdomains to block one by one. Its used for nothing but marketing/advertising. We can always remove it if it causes fp/s

**Comment by jo2dan23** [comment]
Another i found:
wm.adblockerkillswebsites.pw

**Comment by jo2dan23** [comment]
Pinterest app tracker: trk.pinterest.com

**Comment by jo2dan23** [comment]
if you dont think blocking the whole urbanairship.com domain we can just do the ones that are seen in alot of apps

combine.urbanairship.com
device-api.urbanairship.com

these are seen in allergycast app and starbucks app

**Comment by Alex-302** [comment]
@jo2dan23 please sort these domains by type, I will check them tomorrow.

> urbanairship.com

I found this
https://www.urbanairship.com/blog/c500k-in-action-at-urban-airship
So we can't block it completely, but maybe some sub-domeins which you found.

**Comment by jo2dan23** [comment]
@Alex-302 sorry for the jumbled mess lol. i added new ones as i found them from my iphone. here they are all sorted for you.


advertising:

adserver.pandora.com
flexdt.com
flexdirectpath.com
tap-nexus.appspot.com (http://websites.milonic.com/tap-nexus.appspot.com)
onelink.me
usekahuna.com
kahuna.com
adswizz.com
bttn.io
mparticle.com
usebutton.com
autopilothq.com
tritondigital.com
admarvel.com
theappsales.com
vrvm.com (vervemobile.com)
onshowit.com
mads.amazon.com (same as mads.amazonadsystem)
cliipa.com
ads.tremorhub.com
swrve.com
dev.appboy.com
combine.urbanairship.com
device-api.urbanairship.com


spyware:

analytics-rollout-*.amazonaws.com
ce-global-track-*.amazonaws.com
adblockerkillswebsites.pw
trk.pinterest.com
assets.adobedtm.com (http://www.searchdiscovery.com/adobe-dtm/is-adobe-dtm-for-me/)
log.umsns.com
pingma.qq.com
metric.timewarnercable.com
data-collector.wefi.com
checkip.amazonaws.com
mevents.trusteer.com
fullstory.com
renaissance.com
video-stats.l.google.com
bugmuncher.com
amp-error-reporting.appspot.com
cuebiq.com
heartbeat.iheart.com
gameanalytics.com
ping1.tnt-ea.com
geoip.tnt-ea.com
stats.popcap.com
alog.umeng.com
oc.umeng.com

**Comment by jo2dan23** [comment]
@Alex-302 the push notifications they are talking about are used for advertising. See here: https://www.urbanairship.com/products/mobile-app-engagement it says Increase user engagement up to 4x with automated push notifications and in-app messaging. Meaning the notifications arent like regular ones they are used for marketing.

**Comment by jo2dan23** [comment]
@Alex-302 i added some more new ones also :)

**Comment by Alex-302** [comment]
Added to English filter
```
||vrvm.com^$third-party
||onshowit.com^$third-party
||ads.tremorhub.com^$third-party
||bee7.com^$third-party
```
Added to Mobile filter
```
||adserver.pandora.com^$empty
||tap-nexus.appspot.com^$empty
||ads.tremorhub.com^$empty
||dev.appboy.com^$empty
||shared.iad.appboy.com^$empty
```
> mads.amazon.com (same as mads.amazon-adsystem.com)

I think it will break some sites and amazon

----

Added to Spyware filter
```
||analytics-rollout-*.amazonaws.com
||ce-global-track-*.amazonaws.com
||metric.timewarnercable.com^$third-party
||data-collector.wefi.com^$third-party
||mevents.trusteer.com^$third-party
||fullstory.com^$third-party
```

To mobile 
```
||amp-error-reporting.appspot.com
||stats.popcap.com
||alog.umeng.com
||oc.umeng.com
||ar.umeng.com
||crasheye.cn
||beacon.shazam.com
||etl.tindersparks.com
||trk.pinterest.com
||log.umsns.com
||pingma.qq.com
||mobilelog.upqzfile.com
||beacon.qq.com
```

About other advertising and analytics domains - I don't recommend to block them with the main page, so I need sub-domains list and sources where did you found them(app or site)

Are these domains related to the apps or to the sites?
```
||heartbeat.iheart.com
||ping1.tnt-ea.com
||geoip.tnt-ea.com
||count.whitetilecn.cmcm.com
||log-live.direct.ly
||lively-collect-elb-*.amazonaws.com
```

**Comment by jo2dan23** [comment]
ticketmaster app https://itunes.apple.com/us/app/ticketmaster-tickets-for-concerts/id500003565?mt=8:

api.usebutton.com
config2.mparticle.com
nativesdks.mparticle.com

iheartradio app https://itunes.apple.com/us/app/iheartradio-free-music-radio/id290638154?mt=8

lt110.tritondigital.com (there is multiple lt numbers used on different radio apps)
config2.mparticle.com
nativesdks.mparticle.com
heartbeat.iheart.com

**Comment by jo2dan23** [comment]
Some more:

adanalytics.openload.co
tracking.adactioninteractive.com
r.remarketingpixel.com

**Comment by jo2dan23** [comment]
Some more:

adanalytics.openload.co
tracking.adactioninteractive.com
r.remarketingpixel.com

**Comment by jo2dan23** [comment]
I sorted them all out for you @Alex-302

**Comment by jo2dan23** [comment]
Found 2 more trackers in my log. Dont know which website:
shared.report-uri.io
collector-medium.lightstep.com

**Comment by Alex-302** [comment]
I don't have iOS device, so I can't check and add all domains.
I will edit your message, when domain was added.

**Comment by jo2dan23** [comment]
config2.mparticle.com (marketing, advertising, and analytics)
nativesdks.mparticle.com (marketing, advertising, and analytics)
heartbeat.iheart.com
playlist.ma.tune.com (marketing)

Sorry to bug you. what about these?

**Comment by jo2dan23** [comment]
@Alex-302 sorry. Dont know if you missed the notification for the above

**Comment by jo2dan23** [comment]
@Alex-302 do the android versions of these apps show different trackers then the iOS ones because i know snapchat on android had a tracker that iOS version didnt.  I can get you a fiddler log if you would like or anything you need to help. :)

**Comment by Alex-302** [comment]
> Dont know if you missed the notification for the above

received all. I will check them a bit later.

**Comment by jo2dan23** [comment]
alog.umeng.co and oc.umeng.co are now trying to be reached in one of my apps

**Comment by jo2dan23** [comment]
What if we just add lt110.tritondigital.com and ill let you know if it breaks anything in the iheart radio app @Alex-302

**Comment by jo2dan23** [comment]
More openload ad domains:

phox2ey.bid
555fff555f.net
track.appinthis.com
voluumtrk2.com
c.actrck.com
ebfjbrlcvjlv.com
