### ISSUE TITLE
lenfilm.tv

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3218]
**Description**: Реклама вверху и между фильмами в мобильной версии сайта. 
http://lenfilm.tv/filmcat/view/id/5/theme/mobile

И в обычной версии вверху
http://lenfilm.tv/filmcat/view/id/5/theme/touch
Лог по 2й проблеме. Время 14.44 и 14.45.
[debug (8).txt](https://github.com/AdguardTeam/AdguardFilters/files/539697/debug.8.txt)

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19528864/5aa95614-9636-11e6-9531-9a5994f28636.png)
![image](https://cloud.githubusercontent.com/assets/18548949/19529049/1238cc38-9637-11e6-9f7c-0abe643cc57e.png)
</details>

**Filters list**: 2, 3, 4, 1, 11 

**Browser**: Встроенный, cm browser

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
lenfilm.tv##.rek
lenfilm.tv###adv_kod_frame
```

**Comment by evgeniy-ADG** [comment]
Она есть... ( фильтры новые.
<details>
![screenshot_20161023-130801](https://cloud.githubusercontent.com/assets/15856304/19625511/6443bddc-9923-11e6-8015-c025fbac0524.png)

**Comment by Alex-302** [comment]
Какой браузер и версия Адгарда? Пока только дроидная бета может скрыть.

**Comment by evgeniy-ADG** [comment]
Скрин мой, Хром и бета АДГ, все посленее.

**Comment by Alex-302** [comment]
Переделали.
Заменил на 
```
lenfilm.tv##body > div.rek[-ext-has="div"]
lenfilm.tv#%#window.WebSocket = undefined;
```
