### ISSUE TITLE
LevelApp ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3219]
**Description**: Можно убрать рекламу в приложении? или она встроенная?
https://play.google.com/store/apps/details?id=com.volt.levelapp

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19531949/5543a38a-9642-11e6-939e-0953849403f5.png)

</details>

**Filters list**: 1,2,3,4,11,14

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by jo2dan23** [comment]
Dns log would help alot

**Comment by Alex-302** [comment]
@vgavrish 
Please ask for dns log

**Comment by gshumihin** [comment]
@jo2dan23 this is android app, we do not have DNS log in Adguard for android

**Comment by Alex-302** [comment]
Ads are builtin. They are displayed without internet connection.
