### ISSUE TITLE
ottclub.cc 

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3220]
**Description**:
Пользователь просит добавить в исключения чат-онлайн консультанта на сайте. 

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19533357/188dc30c-9648-11e6-9c0d-3c39325cdf50.png)
</details>

**Filters list**: 1,2,3,4,14

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Он блокируется фильтром раздражителей.
Для пользовательского фильтра:
[CODE]
@@||jivosite.com^
[/CODE]

**Comment by gunners91** [comment]
Добавил данное правило в adguard, проблема остается.

**Comment by Alex-302** [comment]
Откройте журнал фильтрации и поставьте чек-бокс "Blocked", обновите вкладку и сделайте скриншот

**Comment by gunners91** [comment]
Как открыть не знаю.

**Comment by Alex-302** [comment]
Расширение или программа?

**Comment by gunners91** [comment]
Программа.

**Comment by Alex-302** [comment]
Щёлкните правой кнопкой по значку в панели задач и перейдите в меню как на скриншоте
![image](http://imagizer.imageshack.com/img924/6538/ughbd1.png)

**Comment by gunners91** [comment]
[url=http://s50.radikal.ru/i129/1610/54/7a465f32f3b7.jpg]2.jpg[/url]

**Comment by gunners91** [comment]
[url=http://s50.radikal.ru/i129/1610/54/7a465f32f3b7.jpg]2.jpg[/url]

**Comment by Alex-302** [comment]
Странно. У меня он и без Адгарда перестал отображаться.
А судя по скрину исключение не добавлено, либо добавлено не туда. Куда вы его добавляли? Желательно со скрином, вдруг с ошибкой вставлено.

**Comment by gunners91** [comment]
[url=http://s017.radikal.ru/i422/1610/73/f732585d3834.jpg]1.jpg[/url]

[url=http://s018.radikal.ru/i506/1610/ae/f965146f8400.jpg]2.jpg[/url]

**Comment by Alex-302** [comment]
Вот так нужно
```
@@||jivosite.com^
```
Тэги случайно попали.

**Comment by gunners91** [comment]
Сейчас все нормально, спасибо!

**Comment by Alex-302** [comment]
Не за что.
