### ISSUE TITLE
www.overclockers.ru - anti-adblock pop-up.

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3221]
Microsoft Windows NT 6.1.7601 Service Pack 1
Adguard version. 6.0.226.1108
Browser Palemoon
Filters
<details>
English filter
Spyware filter
Social media filter
Experimental filter
Annoyances filter
Anti-Adblock Killer
EasyList Czech and Slovak
Liste FR
German filter
</details>
Screenshots
<details>
![image](https://cloud.githubusercontent.com/assets/20476168/19535718/8b3d7376-9651-11e6-9ea3-2d0ce9e9fe1c.png)

![image](https://cloud.githubusercontent.com/assets/20476168/19535682/6a4cc162-9651-11e6-9a6a-76aa8d6a4204.png)
</details>

Tried to reproduce on my side. Nothing happens. The only one difference is that i have Adguard 6.1

Ticket ID 1078874

**Comment by Serzh-SUP** [comment]
## Снова возникла проблема
![2016-10-31_16-52-16](https://cloud.githubusercontent.com/assets/16462533/19858537/833c6078-9f8a-11e6-90e2-894c155e347f.png)

## Фильтры
**Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский**

**Comment by Alex-302** [comment]
Не повторилось.

**Comment by iverkhohliad** [comment]
Проблема повторилась в еще одного пользователя
Советовала включить фильтр раздражителей. Проблема пропала и появилась через день.

**Filters:**
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.32.40 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.77 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.82 Enabled=YES
ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.19 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.57.71 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.91 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.64 Enabled=YES

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Device: | iPad
Operating system:                   | 10.3.3
Browser:                            | Safari
AdGuard version:                    | 1.3.1.82
Simplified filters (iOS only)       | Off
Helpdesk ID (if exists):            | 1640323

**Comment by Alex-302** [comment]
Fixed.

**Comment by d7th** [comment]
Доброго времени, нет, неисправленно, только что обновил фильтры и зашёл на сайт, вижу тоже самое...
пс: ios 10.3.3 , короче мой конфиг постом выше...

**Comment by Alex-302** [comment]
Видать в оптимизированные фильтры не попали ещё.
В пользовательский фильтр добавьте
```
overclockers.ru#@#.adsbygoogle
www.overclockers.ru##.citi_ban
forum.awd.ru##.adsbygoogle
~overclockers.ru,overclockers.ru##body ins.adsbygoogle
```

**Comment by Alex-302** [comment]
Видать в оптимизированные фильтры не попали ещё.
В пользовательский фильтр добавьте
```
overclockers.ru#@#.adsbygoogle
www.overclockers.ru##.citi_ban
forum.awd.ru##.adsbygoogle
www.overclockers.ru#@#body ins.adsbygoogle
```

**Comment by d7th** [comment]
добавил, safari принуительно закрыл и снова зашёл на сайт...польз-й не сработал.
пс: " ins.adsbygoogle" следущей строкой? спробелом? или оставить как есть?

**Comment by Alex-302** [comment]
всё как есть - 4 строки.
Попробуйте `www.` убрать.

**Comment by d7th** [comment]
несработало,  попробовал у брать везде и наоборот, поставить везде www

**Comment by Alex-302** [comment]
Предыдущие правила можете удалить, и добавьте
```
www.overclockers.ru#@#noindex
```

**Comment by d7th** [comment]
сработало! благодарю
