### ISSUE TITLE
http://picforall.ru/ ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3223]
**Description**: Расширение. Реклама
http://picforall.ru/348/79967/
Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19570291/09afbbdc-9702-11e6-89dc-7024bca5417a.png)
</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Никогда не понимал смысла оставлять обшарпанную деревянную входную дверь при наличии железной.

Добавил в русский фильтр
```
picforall.ru##noindex a[rel="follow"] > img
```
