### ISSUE TITLE
https://zhidao.baidu.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3225]
https://zhidao.baidu.com/question/570195031.html?fr=ala&word=cutie&device=mobile&ssid=0&from=1099b&uid=0&pu=usm@2,sz@1320_2001,ta@iphone_1_9.3_3_601&bd_page_type=1&baiduid=9040974E006413BD2002DF090E7CCFA9&tj=zhidao_4_0_10_l1

![image](https://cloud.githubusercontent.com/assets/15856304/19594400/8a428a82-978d-11e6-9868-fb1ee8de4ba1.png)

<details>
Application version: 1.1.2.24
Application lifetime: 2016-10-16 07:36:10 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.5
ID: 6F827936-2899-4D7D-884A-C45E36C3DD29

Locale: zh
Region: cn

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.97.81 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.22 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.70 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.24 Enabled=NO
ID=12 Name="Safari filter" Version=1.0.1.53 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.67.66 Enabled=YES

**Comment by Alex-302** [comment]
Added to English filter
```
zhidao.baidu.com##a[class="cur"][href^="/mobile/board?"] > img
```
