### ISSUE TITLE
https://mobdisc.com/

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardFilters#32263]
### Issue URL (Ads)
[https://mobdisc.com/dw9n08e050/download.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://mobdisc.com/dw9n08e050/download.html) 

### Comment
Username: @Big-U-Boss
 
 > И ещё одно, при автосоздании рапорта пишет, что данный тип URL не поддерживается вашим автозаполнениеv!  Прошу, избавьте меня от этого заполнения вручную в дальнейшем!
### Screenshots
<details><summary>Screenshot 1</summary>

![image](https://monosnap.com/image/j4n0C6DLzjcm6w9sUUQjf6JJKUCsiR)
</details>

### System configuration

Information                            | Value
---                                          | ---
Platform:	|Ext
AdGuard version:	|3.0.11
Browser:	|Chrome
Stealth mode options:	|Hide your search queries, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Hide your Referrer from third-parties
Filters:	|AdGuard Russian,</br>AdGuard Annoyances,</br>AdGuard Base,</br>AdGuard Tracking Protection,</br>AdGuard Social Media

**Comment by Spok1** [comment]
Э,чё закрыл,там редирект же!

**Comment by Chinaski1** [comment]
Blacklisted!

**Comment by Spok1** [comment]
> Blacklisted!

В смысле? А маску не добавила для фильтрации?
