### ISSUE TITLE
http://www.omroepbrabant.nl/ - ad leftovers

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3226]
http://www.omroepbrabant.nl/
Chrome, Mac OS X app, Adg 1.3.0 beta

![image](https://cloud.githubusercontent.com/assets/15856304/19594664/c1fa6d54-978e-11e6-9ab3-762aaa19aab4.png)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/19594670/d32f1516-978e-11e6-85d8-2a94c8cb277f.png)
![image](https://cloud.githubusercontent.com/assets/15856304/19594677/d99df46c-978e-11e6-9d62-8621a14da7c8.png)
and the user sees ads on iPhone 6 with the same filters
![image](https://cloud.githubusercontent.com/assets/15856304/19594704/ef7fda52-978e-11e6-8ac2-2d9d1e0ba9e8.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
omroepbrabant.nl##.sticky-footer
```
Added to Dutch filter
```
omroepbrabant.nl#$#.ad-banner-container { position: absolute!important; left: -2000px!important; }
```
