### ISSUE TITLE
3dnews.ru

### ISSUE THREAD

**Issue by a-ladanov** [AdguardTeam/AdguardFilters#3229]
http://www.3dnews.ru/
Фон кликабельный, хотя изображения баннера нет.
![default](https://cloud.githubusercontent.com/assets/18179397/19610702/46681024-97f7-11e6-895d-4a7add3f9bbb.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
3dnews.ru#$#body { background: rgba(225,225,225,1)!important; }
3dnews.ru$$script[tag-content="ad.3dnews.ru/www/delivery/ck.php"][max-length="700"]
3dnews.ru#$#div[id="global-wrapper"][style] { background: none!important; padding-top: 0px!important; cursor: auto!important; }
```
второе правило убирает кликабельность, но работает только в программе.

**Comment by a-ladanov** [comment]
После правок для http://www.3dnews.ru/ за 22/10/2016
повылезала реклама, может чего-то поломали.
![default](https://cloud.githubusercontent.com/assets/18179397/19621939/00b24002-98b7-11e6-8f33-256553b121cd.png)

**Comment by Alex-302** [comment]
Баннеры переделали. Заблокировал.

**Comment by a-ladanov** [comment]
Переделали почти сразу после ваших правок, в субботу вечером?
Значит точно отслеживают списки.
Еще один вид рекламы на сайте, вылазит не всегда.
![default](https://cloud.githubusercontent.com/assets/18179397/19624393/12082aea-990e-11e6-9b33-1af0e8802add.png)

**Comment by Alex-302** [comment]
> Переделали почти сразу после ваших правок, в субботу вечером?

скорее совпадение. И без изменений в правилах  оно висит.  Для кого-то вечер, для кого-то день.


> Еще один вид рекламы на сайте, вылазит не всегда.

поправил
