### ISSUE TITLE
www.livenewschat.eu - Adblock killer

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3230]
Windows 10
Adguard 6.1
Filters
<details>![image](https://cloud.githubusercontent.com/assets/20476168/19617386/faa3854c-9837-11e6-8884-e49280f026eb.png)
![image](https://cloud.githubusercontent.com/assets/20476168/19617392/141e7f2c-9838-11e6-9ad5-37966d954b92.png)</details>
Go to http://www.livenewschat.eu/stocks/ and wait a little
<details>
![image](https://cloud.githubusercontent.com/assets/20476168/19617435/d71d70be-9838-11e6-8700-b87298738d80.png)
</details>

**Comment by Alex-302** [comment]
Added to English filter
```
@@://*.ico$domain=livenewschat.eu
@@||adsatt.espn.starwave.com^$domain=livenewschat.eu,~script

```
