### ISSUE TITLE
http://sugaring.su/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3231]
**Description**: Расширение/программа
Срезание логотипа и основного меню сайта 
http://sugaring.su/

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19617781/11d1330e-9842-11e6-9d32-f76fa781f563.png)
![image](https://cloud.githubusercontent.com/assets/18548949/19617782/268a20b2-9842-11e6-9e32-83e9dc0b5a6f.png)
</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не повторилось даже со всеми включенными фильтрами. Может в пользовательском заблокировано.

**Comment by vgavrish** [comment]
Да, утром блокировалось, сейчас все ок
