### ISSUE TITLE
globalnews.ca

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3232]
**Description**: video won't play at:
http://globalnews.ca/news/3013833/caught-on-camera-mother-catches-man-attempting-to-take-baby-out-of-shopping-cart/?campaign_id=A100

Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19618561/ea5070d2-9856-11e6-8386-93cbc162fa89.png)
</details>

**Expected behaviour**: video should start playing when you tap on it.

Customer ID **827954**

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||metrics.corus.ca/b/ss/corus-tv-globalnews/
```
