### ISSUE TITLE
newsru.com - ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#3233]
**Description**: ads are not blocked
Works ok in desktop Safari with user-agent.
Customer ID **1433653**

Screenshot: use the following code
<details>
![image](https://cloud.githubusercontent.com/assets/22892774/19619061/b527fda8-9865-11e6-968e-51c95eb2bc99.png)
</details>

**Adguard version**: 1.1.1.54 for iOS

**Filters list**: 
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.95.37 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.75 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.92 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.39.78 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.95 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.33 Enabled=YES

**Operating system**: 10.0.2

**Browser**: Safari

**Comment by Alex-302** [comment]
У меня чисто. Передай на пробу
```
newsru.com##.page > div[style="background: #FFFFFF; border: 1px solid #BFCFE2; width: 1248px;"]
```

**Comment by evgeniy-ADG** [comment]
>Добавил, не помогло.

**Comment by Alex-302** [comment]
фильтры полные или оптимизированные? У меня в сафари баннер скрыт.
