### ISSUE TITLE
mydealz.de

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3234]
**Site**: https://www.mydealz.de/
**Description**: Cookie notice not blocked.

**Current behaviour**: Site shows a cookie notice at the bottom.

<details>
<summary>Screenshot</summary>
![2016-10-22 15_07_12-_new 6 - notepad](https://cloud.githubusercontent.com/assets/10995998/19619553/4d316a2c-986a-11e6-88e5-17992be0b608.png)
</details>

========

**Expected behaviour**: Cookie notice should be blocked.

<details>
<summary>Screenshot</summary>
![2016-10-22 15_08_02-mydealz de - schnappchen angebote deine shopping-community](https://cloud.githubusercontent.com/assets/10995998/19619559/6957d9de-986a-11e6-848f-ce779f3c0a98.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.30
Spyware filter 1.0.8.39
Social media filter 1.0.13.88
Annoyances filter 1.0.5.60
German filter 1.0.27.97

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
mydealz.de###softMessages-list
```
