### ISSUE TITLE
t3n.de

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3235]
**Site**: http://t3n.de/
**Description**: Adguard detected.

**Current behaviour**: Site shows a detection message.

<details>
<summary>Screenshot</summary>
![2016-10-22 15_28_58-t3n digital pioneers _ das magazin fur digitales business](https://cloud.githubusercontent.com/assets/10995998/19619642/a3b494d0-986c-11e6-8797-c18c4324681c.png)
</details>

========

**Expected behaviour**: Detection message should be blocked.

<details>
<summary>Screenshot</summary>
![2016-10-22 15_29_32-t3n digital pioneers _ das magazin fur digitales business](https://cloud.githubusercontent.com/assets/10995998/19619644/a99e9c74-986c-11e6-8698-3fe8e8b81cb3.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.30
Spyware filter 1.0.8.39
Social media filter 1.0.13.88
Annoyances filter 1.0.5.60
German filter 1.0.27.97

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
t3n.de###js-adbnotice
```
