### ISSUE TITLE
computerlexikon.com

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3236]
**Site**: http://www.computerlexikon.com/
**Description**: Cookie notice not blocked.

**Current behaviour**: Site shows a cookie notice at the bottom.

<details>
<summary>Screenshot</summary>
![2016-10-22 15_32_59-sept](https://cloud.githubusercontent.com/assets/10995998/19619660/0ec03a86-986d-11e6-8b79-9bd08879c2b6.png)
</details>

========

**Expected behaviour**: Cookie notice should be blocked.

<details>
<summary>Screenshot</summary>
![2016-10-22 15_33_14-computer lexikon - fachbegriffe verstandlich erklart _ pc edv glossar](https://cloud.githubusercontent.com/assets/10995998/19619659/0c3e7bec-986d-11e6-8c22-9e6e8edccb0c.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.30
Spyware filter 1.0.8.39
Social media filter 1.0.13.88
Annoyances filter 1.0.5.60
German filter 1.0.27.97

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
computerlexikon.com###eucookieconsent
```
