### ISSUE TITLE
TheMarker App - iOS adgurd pro 

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#32374]
Issue URL (Ads):
https://itunes.apple.com/il/app/themarker-%D7%93%D7%94%D7%9E%D7%A8%D7%A7%D7%A8/id360938308?mt=8

Screenshots:
With adgurd VPN:
https://image.prntscr.com/image/XpAVgH2iRrCNroX2FZacrA.png
this down and the app no work and no loading

without Adgurd
have popup:
http://prntscr.com/na272c
click X and this yes work:
http://prntscr.com/na27nz

System configuration:

Information | value
-- | --
Platform: | iOS
AdGuard version: | 2.1.1
System wide filtering: | enabled
Simplified filters: | disabled
AdGuard DNS: | Default
Filters: | AdGuard Mobile Ads,AdGuard Safari,AdGuard Base, Spyware filter, safari filter, EasyList Hebrew

**Comment by Alex-302** [comment]
@MrTal could you please check again? It works fine on my end.

**Comment by MrTal** [comment]
@Alex-302 
still no work
maybe because of EasyList Hebrew?

**Comment by Alex-302** [comment]
Please chek blocked requests in DNS log. Do you know how to do it?

**Comment by MrTal** [comment]
http://up419.siz.co.il/up3/dkymjzmu131g.png
http://up419.siz.co.il/up1/ytqnttozmbqw.png

**Comment by Alex-302** [comment]
@MrTal ok. Could you, please, try to exclude blocked domains one-by-one?

**Comment by MrTal** [comment]
@Alex-302 
ok, with i add this to whitelist this work but have popup and have popup too more app
`ssl.google-analytics.com`

**Comment by Alex-302** [comment]
We can't unblock this domain in DNS:(

**Comment by Alex-302** [comment]
GA is too popular.

**Comment by MrTal** [comment]
@Alex-302 
ah, I thought maybe It was possible add filter to baypss the block

**Comment by Alex-302** [comment]
You can unblock anything you want on your device)
