### ISSUE TITLE
sueddeutsche.de

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3237]
**Site**: http://www.sueddeutsche.de/
**Description**: Adguard detected.

**Current behaviour**: Site shows a adblock detection message.

<details>
<summary>Screenshot</summary>
![2016-10-22 15_36_18- 1 nachrichten aus politik kultur wirtschaft und sport - suddeutsche de](https://cloud.githubusercontent.com/assets/10995998/19619692/8e6cc07e-986d-11e6-9f4d-5e95a93790b8.png)
</details>

========

**Expected behaviour**: Detection message should be blocked.

<details>
<summary>Screenshot</summary>
![2016-10-22 15_36_45- 1 nachrichten aus politik kultur wirtschaft und sport - suddeutsche de](https://cloud.githubusercontent.com/assets/10995998/19619689/8aeb7562-986d-11e6-971e-0f51bc2f1086.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.30
Spyware filter 1.0.8.39
Social media filter 1.0.13.88
Annoyances filter 1.0.5.60
German filter 1.0.27.97

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
For user filter, because this message doesn't affect the site, but the rule will unhide some elements:
`@@||sueddeutsche.de$generichide`
