### ISSUE TITLE
Ненужный Milestone

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardFilters#32380]
Стоит закрыть https://github.com/AdguardTeam/AdguardFilters/milestone/1, т. к. он не нужен.

**Comment by bogachenko** [comment]
![Безымянный](https://user-images.githubusercontent.com/8535285/55891454-1e24c080-5ba4-11e9-8b8a-e74114dd8883.png)

**Comment by Alex-302** [comment]
удалил
