### ISSUE TITLE
netzwelt.de

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3238]
**Site**: https://www.netzwelt.de/
**Description**: Cookie notice not blocked. Notice may not pop up until you read an article. 

**Current behaviour**: Site shows a cookie notice at the bottom.

<details>
<summary>Screenshot</summary>
![2016-10-22 15_42_57-pixel xl vs iphone 7 plus im blindtest_ bildqualitat im vergleich - netzwel](https://cloud.githubusercontent.com/assets/10995998/19619755/8082de52-986e-11e6-8652-7a7479d431c4.png)
</details>

========

**Expected behaviour**: Cookie notice should be blocked.

<details>
<summary>Screenshot</summary>
![2016-10-22 15_43_01-pixel xl vs iphone 7 plus im blindtest_ bildqualitat im vergleich - netzwel](https://cloud.githubusercontent.com/assets/10995998/19619761/83c89d5e-986e-11e6-841f-4163a9a9d818.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.30
Spyware filter 1.0.8.39
Social media filter 1.0.13.88
Annoyances filter 1.0.5.60
German filter 1.0.27.97

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
netzwelt.de##.ckch
```
Added to Social filter
```
netzwelt.de##.stcl
```
