### ISSUE TITLE
wired.com

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3239]
**Site**: https://www.wired.com/
**Description**: Link to article is blocked, but shouldn't.

**Current behaviour**:

<details>
<summary>Screenshot</summary>
![2016-10-22 15_48_09-wired](https://cloud.githubusercontent.com/assets/10995998/19619825/c9f3ee5e-986f-11e6-96e8-09df63affae5.png)
</details>

========

**Expected behaviour**:

<details>
<summary>Screenshot</summary>
![2016-10-22 15_49_50-wired](https://cloud.githubusercontent.com/assets/10995998/19619829/db691a88-986f-11e6-9422-ac9da35ed42f.png)
Notice: I disable the adblocking for this to show up.
This article got blocked: https://www.wired.com/2014/08/i-liked-everything-i-saw-on-facebook-for-two-days-heres-what-it-did-to-me/
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.30
Spyware filter 1.0.8.39
Social media filter 1.0.13.88
Annoyances filter 1.0.5.60
German filter 1.0.27.97

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Please add these rules
```
wired.com#%#Object.defineProperty(window, 'sniffAdBlock', { get: function() { return function() { }; } });
wired.com#%#Object.defineProperty(window, 'blockAdBlock', { get: function() { return function() { }; } });
```
and check also for adblock detection.

**Comment by danidoedel** [comment]
These rules don't seem to change anything for me

**Comment by Alex-302** [comment]
oh, my mistake
```
wired.com#@%#Object.defineProperty(window, 'sniffAdBlock', { get: function() { return function() { }; } });
wired.com#@%#Object.defineProperty(window, 'blockAdBlock', { get: function() { return function() { }; } });
```
or you can disable previous rules in English filter in Filter Editor

**Comment by Alex-302** [comment]
Removed that rules.
Please wait for filter updates and reply, please, after you check it.

**Comment by danidoedel** [comment]
It's working now, but this part is loading a lot slower than without adguard. Not sure if that issue can be resolved.

**Comment by Alex-302** [comment]
It other case we get anti-adblock message:)
