### ISSUE TITLE
gamespilot.de

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3240]
**Site**: http://www.gamespilot.de/
**Description**: Cookie notice not blocked.

**Current behaviour**: Site shows a cookie notice at the bottom.

<details>
<summary>Screenshot</summary>
![2016-10-22 16_05_35-gamespilot _ alle news games](https://cloud.githubusercontent.com/assets/10995998/19619903/8ce98a30-9871-11e6-9744-ca0ed96581cc.png)
</details>

========

**Expected behaviour**: Cookie notice should be blocked.

<details>
<summary>Screenshot</summary>
![2016-10-22 16_05_38-gamespilot _ alle news games](https://cloud.githubusercontent.com/assets/10995998/19619902/8a06a528-9871-11e6-86d7-80e52c2a2d1b.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.30
Spyware filter 1.0.8.39
Social media filter 1.0.13.88
Annoyances filter 1.0.5.60
German filter 1.0.27.97

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
gamespilot.de##.notification.is-info
```
