### ISSUE TITLE
tw.news.appledaily.com (Paywall)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardFilters#32419]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

Issue URL (Paywall)
https://tw.news.appledaily.com/international/realtime/20190411/1548615/

***Description***:
@AdamWr

Recently, the news website started to ask readers to login for free reading its news.
It maybe plans to ask payment for reading its news in the future.
Blocking `img.appledaily.com.tw/pay/js/paywall.20190410.js` can solve it.

Please add `||img.appledaily.com.tw/pay/js/paywall$script` in **Base filter**.
Thanks.

BTW, `img.appledaily.com.tw/pay/js/paywall.20190410.js` won't appear in the filtering log of AG for Windows v6.4.1814.4903 if I don't first block it in the user filter.
https://github.com/AdguardTeam/AdguardForWindows/issues/2571

* **Current behaviour**: 
Ask readers to login for free reading its news.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/tSJSxu1.png)
</details><br/>

* **Expected behaviour**: 
Without login, I can read news.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ObFvkUb.png)
</details><br/>

Information                            | Value
---                                    | ---
Operating system:                      | Win
Operating system version (Android/iOS) | 10
Browser:                               | Chrome
AdGuard version:                       | 6.4.1814.4903
Filters enabled:                       | EasyList China, AdGuard Annoyances, AdGuard Base, Adblock Warning Removal List, Spam404, CJX's Annoyance List, AdGuard Tracking Protection, AdGuard Social Media, AdGuard Japanese
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Added to Annoyances filter, thank you.

>BTW, img.appledaily.com.tw/pay/js/paywall.20190410.js won't appear in the filtering log 

Maybe it was loaded before and it's in cache, try to use "force reload" `"Ctrl" + "F5"`.

**Comment by lancelot-moon** [comment]
You're right.
After "force reload" "Ctrl" + "F5", it appeared in the filtering log.

**Comment by AdamWr** [comment]
>Which is better?

In this case both rules block the same request, so I think there is no difference (I just prefer second rule).

>You added the rule in Annoyances filter.
But I remember that Annoyances filter isn't enabled by default.
I supposed that it's better to add it in Base filter.

We don't block paywalls in Base filter.

**Comment by TesterMan247** [comment]
> We don't block paywalls in Base filter.

I'd like to get some paywalls removed if thats ok?

**Comment by AdamWr** [comment]
>I'd like to get some paywalls removed if thats ok?

It depends how these paywalls looks like, in case of `appledaily.com` it just requires to create an account and it was "easy" to fix, but if I'm not wrong, if paywall will requires to pay and/or it will be not easy to fix then it will be not fixed.

By the way, there is AdGuard policy on adblock walls - https://forum.adguard.com/index.php?threads/policy-on-adblock-walls.26022/

**Comment by lancelot-moon** [comment]
@AdamWr

Today, it updates scripts.

`||img.appledaily.com.tw/pay/js/paywall.*.js` is still valid.

For mobile browsers, everything is ok. 
But...
For desktop browsers, content of news will be empty without login.

You can try browser mobile mode and desktop mode on Android.

If disabling adblockers without login, we can see some news content in the back of warning which asks to login by mobile browsers.

By desktop browsers, it seems to be empty in the back of warning.

Do you have ideas?

**Comment by AdamWr** [comment]
Could you please check this rule:
```
appledaily.com#$#.ndAritcle_headPic,.ndArticle_margin,.mediabox,#playerVideo,.articulum { display: block!important; }
```

**Comment by lancelot-moon** [comment]
Oh my God, you're my idol.
I tried it with AG for Android by browser desktop mode.
It's valid!
Please add it.

Is that rule syntax supported by Chrome or Safari?

Thanks a lot.

**Comment by lancelot-moon** [comment]
Another thing.
BTW, Nano has fixed the 3 sec timer.
If you're interested the JS rules, I sent the link to you on telegram.

**Comment by AdamWr** [comment]
>It's valid!
Please add it.

Ok, added.
Thank you for checking it.

>Is that rule syntax supported by Chrome or Safari?

It's supported by Chrome/Opera/Firefox/Edge extension, but as far as I know Safari extension/content blocker doesn't support it.

>If you're interested the JS rules, I already sent the link to you on telegram.

I saw it, thank you.

**Comment by lancelot-moon** [comment]
@AdamWr 

This afternoon, it just updated scripts.
The old rules are already invalid for desktop browsers.
(**Still valid for mobile browsers.**)
May you try to fix it?

Thanks.

**Comment by AdamWr** [comment]
Could you please check this rule:
`tw.news.appledaily.com#%#AG_setConstant('paywall', 'noopFunc');`

**Comment by lancelot-moon** [comment]
@AdamWr 

Hi, not `tw.news.appledaily.com`.
It has other sub-domains for different categories.
Better to use appledaily.com in your rules.

1. Please keep old rules and additionally add `appledaily.com#%#AG_setConstant('paywall', 'noopFunc');`.

2. I see "cssSelector": ".thoracis" in the codes.
Should we modify your past rule as the below?
**Please ignore if it's unnecessary.**
(If keeping the original rules with your new rule, they're valid.
So I don't know if it's necessary...)

`appledaily.com#$#.ndAritcle_headPic,.ndArticle_margin,.mediabox,#playerVideo,.articulum { display: block!important; }`
-> `appledaily.com#$#.ndAritcle_headPic,.ndArticle_margin,.thoracis,.mediabox,#playerVideo,.articulum { display: block!important; }`

```
"description": "俄擬拓展北極勢力　普丁喊提升運量將擴編船隊",
--
  | "url": "https://tw.appledaily.com/new/realtime/20190411/1548615/",
  | "thumbnailUrl": "https://img.appledaily.com.tw/images/ReNews/20190411/640_6d806dc610fa02bde3706da7de9219f0.jpg",
  | "dateCreated": "2019-04-11T06:00+08:00",
  | "articleSection": "蘋果_國際",
  | "creator": "蘋果新聞網",
  | "keywords": ["國際","北極","俄羅斯","歐盟","美國"],
  | "isAccessibleForFree": "False",
  | "hasPart": [{
  | "@type": "WebPageElement",
  | "isAccessibleForFree": "False",
  | "cssSelector": ".ndAritcle_headPic"
  | },{
  | "@type": "WebPageElement",
  | "isAccessibleForFree": "False",
  | "cssSelector": ".ndArticle_margin"
  | },{
  | "@type": "WebPageElement",
  | "isAccessibleForFree": "False",
  | "cssSelector": ".thoracis"
  | },{
  | "@type": "WebPageElement",
  | "isAccessibleForFree": "False",
  | "cssSelector": ".mediabox"
  | }]
  | }
```

**Comment by AdamWr** [comment]
Ok, added.
`appledaily.com#%#AG_setConstant('paywall', 'noopFunc');`

>I see "cssSelector": ".thoracis" in the codes.
Should we modify your past rule as the below?

I think that it's not necessary, because this element is not hidden.
