### ISSUE TITLE
nordbayern.de - iOS

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3241]
**Site**: http://www.nordbayern.de/
**Description**: Ad left over and big app notice at the top on iOS devices.

**Current behaviour**: Marked in the screenshots

<details>
<summary>Screenshot</summary>
![img_3566](https://cloud.githubusercontent.com/assets/10995998/19619979/75d66cb2-9873-11e6-9767-25c3feeb0d47.PNG)
![img_3567](https://cloud.githubusercontent.com/assets/10995998/19619980/79c811d6-9873-11e6-9432-20e2c37b453b.PNG)
</details>

========

**Expected behaviour**: Marked problems should be blocked.

========

**Adguard version**: 1.1.1

**Filters list**: 
English filter 1.0.98.31
Spyware filter 1.0.8.40
Social media filter 1.0.13.88
Annoyances filter 1.0.5.60
German filter 1.0.27.97
Mobile ads filter 1.0.5.33
Safari filter 1.0.1.55

**Operating system**: iOS 10.1
**Device**: iPhone 6s

**Browser**: Safari

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
nordbayern.de##.appBanner
```

**Comment by danidoedel** [comment]
@Alex-302 There is still that spinning loading animation with the word "Anzeige" (ad) above.
If think this should be added to the filter: 
`nordbayern.de##div[id*="-mobile-ad-"]`

**Comment by Alex-302** [comment]
Ok, added to modile filter.
