### ISSUE TITLE
twitch.tv

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3242]
**Site**: https://www.twitch.tv/
**Description**: Cookie notice not blocked.

**Current behaviour**: Site shows a cookie notice at the bottom.

<details>
<summary>Screenshot</summary>
![2016-10-22 16_26_36-twitch](https://cloud.githubusercontent.com/assets/10995998/19620051/8719545c-9874-11e6-95cb-f53daa5e2dc2.png)
</details>

========

**Expected behaviour**: Cookie notice should be blocked.

<details>
<summary>Screenshot</summary>
![2016-10-22 16_26_38-twitch](https://cloud.githubusercontent.com/assets/10995998/19620049/826af802-9874-11e6-9cf7-402d9e5cdec7.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.31
Spyware filter 1.0.8.40
Social media filter 1.0.13.88
Annoyances filter 1.0.5.60
German filter 1.0.27.97

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Not show. Please make a screenshot of it's come in developer tools.

**Comment by danidoedel** [comment]
@Alex-302 Not sure if I understood that correctly, but here is a screenshot:
![2016-10-23 15_41_49-twitch](https://cloud.githubusercontent.com/assets/10995998/19626698/761261da-9937-11e6-80f7-b225aaa5d1ee.png)
If you need anything else just let me know.

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
twitch.tv##.noty_bar
```
