### ISSUE TITLE
nordbayerischer-kurier.de

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3243]
**Site**: http://www.nordbayerischer-kurier.de/
**Description**: Ad left over

**Current behaviour**: Site has some ad left over spaces.

<details>
<summary>Screenshot</summary>
![2016-10-22 16_30_03-aktuell _ nordbayerischer kurier](https://cloud.githubusercontent.com/assets/10995998/19620082/353c2960-9875-11e6-9f54-f66420f664b9.png)
</details>

========

**Expected behaviour**: Ad left over spaces should be removed.

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.31
Spyware filter 1.0.8.40
Social media filter 1.0.13.88
Annoyances filter 1.0.5.60
German filter 1.0.27.97

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
We can't remove that in thes case.
