### ISSUE TITLE
gamecopyworld.eu

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3244]
**Site**: http://www.gamecopyworld.eu/games/gcw.php
**Description**: Ad not blocked

**Current behaviour**: Site shows ad at the top.

<details>
<summary>Screenshot</summary>
![2016-10-22 16_38_31-gamecopyworld - no-cd no-dvd patches pc game fixes trainers cheats - kopie](https://cloud.githubusercontent.com/assets/10995998/19620143/73261bea-9876-11e6-90c3-57c1a0312866.png)
</details>

========

**Expected behaviour**: Ad should be blocked.

<details>
<summary>Screenshot</summary>
![2016-10-22 16_38_31-gamecopyworld - no-cd no-dvd patches pc game fixes trainers cheats](https://cloud.githubusercontent.com/assets/10995998/19620144/77c39e66-9876-11e6-8fd8-0d2abfd47148.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.31
Spyware filter 1.0.8.40
Social media filter 1.0.13.88
Annoyances filter 1.0.5.60
German filter 1.0.27.97

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to English filter
```
gamecopyworld.eu##div[style="padding:4px 4px 4px 4px"] > table:first-child  td[align="center"] > table[style="height:90px;"]
```
