### ISSUE TITLE
postbank.de

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3245]
**Site**: https://www.postbank.de/
**Description**: Cookie notice not blocked.

**Current behaviour**: Site shows a cookie notice at the top.

<details>
<summary>Screenshot</summary>
![2016-10-22 16_54_50-postbank_ schnell und bequem girokonto eroffnen gunstige kredite abschliessen s](https://cloud.githubusercontent.com/assets/10995998/19620212/6e3a2264-9878-11e6-9a55-c916fbe654b6.png)
</details>

========

**Expected behaviour**: Cookie notice should be blocked.

<details>
<summary>Screenshot</summary>
![2016-10-22 16_54_57-postbank_ schnell und bequem girokonto eroffnen gunstige kredite abschliessen s](https://cloud.githubusercontent.com/assets/10995998/19620211/6c5313fc-9878-11e6-9750-773bac114f8c.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.31
Spyware filter 1.0.8.40
Social media filter 1.0.13.88
Annoyances filter 1.0.5.60
German filter 1.0.27.97

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
postbank.de##.pkh-notification
```
