### ISSUE TITLE
leo.org

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3246]
**Site**: http://www.leo.org/
**Description**: Adguard detected.

**Current behaviour**: Site shows a message about the detection at the top.

<details>
<summary>Screenshot</summary>
![2016-10-22 17_03_15-leo org - ihr sprachangebot im web](https://cloud.githubusercontent.com/assets/10995998/19620271/0004772a-987a-11e6-85ab-e2567fc1c689.png)
</details>

========

**Expected behaviour**: Detection message should be blocked.

<details>
<summary>Screenshot</summary>
![2016-10-22 17_05_00-leo org - ihr sprachangebot im web](https://cloud.githubusercontent.com/assets/10995998/19620264/e9144ee6-9879-11e6-8617-102b64673c5a.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.31
Spyware filter 1.0.8.40
Social media filter 1.0.13.89
Annoyances filter 1.0.5.61
German filter 1.0.27.97

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
leo.org###topBranding > div.floatRight
```
