### ISSUE TITLE
3dnews.ru

### ISSUE THREAD

**Issue by a-ladanov** [AdguardTeam/AdguardFilters#3247]
После правок для http://www.3dnews.ru/ за 22/10/2016
повылезала реклама, может чего-то поломали.
![default](https://cloud.githubusercontent.com/assets/18179397/19621939/00b24002-98b7-11e6-8f33-256553b121cd.png)

**Comment by Alex-302** [comment]
Новую задачу не нужно открывать. Ответьте в старой, так удобнее ведь.
