### ISSUE TITLE
souz.net

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3248]
**Description**: Баннеры внизу
http://souz.net/news/4/454/50903

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19625305/b99b0a02-991d-11e6-8b72-031eb46b8295.png)

</details>

**Adguard version**: 2.8.15

**Filters list**: 1,2,3,4,11,14

**Operating system**: Андроид

**Browser**: Встроенный

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
souz.net##.bloc-content.text-center > span > table[align="center"] a > img
```
