### ISSUE TITLE
kinotut.su and 7ba.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3249]
"enabledFilterIds" : [ 2, 3, 4, 14, 1, 11 ],
  "environment" : "beta",
  "filteringQuality" : "FULL",

<details>![screenshot_20161023-125213](https://cloud.githubusercontent.com/assets/15856304/19625388/d2a57daa-991f-11e6-958b-8764931e7855.png)
![screenshot_20161023-125226](https://cloud.githubusercontent.com/assets/15856304/19625389/d2a81858-991f-11e6-9d52-e517dacac9e7.png)

**Comment by Alex-302** [comment]
С бетой всё чисто. Релизная пока так не умеет.

**Comment by Yana-SUP** [comment]
на kinotut.su снова реклама есть
"enabledFilterIds" : [ 2, 3, 4, 14, 1, 11 ],
"filteringQuality" : "FULL"
"environment" : "beta",
"Screenshot" : http://prnt.sc/dbcij0

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||clickads.name^$third-party
||ksjdkjh.ru^$third-party
||cdn-my1.ru^$third-party
```
