### ISSUE TITLE
http://daringlifenewyork.rusff.ru/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3250]
**Description**: Просьба не блокировать скрипт с Яндекс.Музыкой на форуме
http://daringlifenewyork.rusff.ru/viewtopic.php?id=275

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19625662/7b787444-9927-11e6-9dfb-5418d13491c0.png)
![image](https://cloud.githubusercontent.com/assets/18548949/19625670/98913d7c-9927-11e6-9b34-7574de109a0c.png)

</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
daringlifenewyork.rusff.ru#@#iframe[width="600"][height="100"]
```
