### ISSUE TITLE
https://nnmclub.to - loading speed issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3251]
Сайт работает крайне медленно при включенной фильтрации.
Если перейти на Вход, а с него идти на стартовую, задержка в 5-7 секунд. Без фильтрации - доли секунды, но с невероятным кол-вом рекламы.

1057751
<details>
Os version: Microsoft Windows NT 10.0.14393.0
Dot .net version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: d482860d62e048a8994461ecb44e5cee
Language: ru
AppVersion: 6.1.258.1302
Main settings: 
Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Wfp
Ads Blocked: 27012, Trackers Blocked: 14461
Filtering Mode: Driver
Application lifetime: 12.21:03:36.3555425
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": false,
  "BlockWebRtc": false,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"
}

**Comment by Alex-302** [comment]
У меня и без Адгарда тормозит.

**Comment by evgeniy-ADG** [comment]
А у меня нет.

**Comment by Alex-302** [comment]
Может ддосили их. Сейчас нормально всё.
