### ISSUE TITLE
sportsnet.ca - Adguard blocks results element

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3252]
Windows 10
Adguard 6.1
Reproduced on Chrome, Edge
Filters
<details>
![filters](https://cloud.githubusercontent.com/assets/20476168/19626702/ebedf4a2-993f-11e6-81d5-418891cc902a.PNG)
</details>

When Adguard enabled we just see blue area
<details>
![default](https://cloud.githubusercontent.com/assets/20476168/19626720/28d133ac-9940-11e6-9c79-10c150446141.PNG)
</details>

With disabled Adguard we can see matches schedule and results
<details>
![default](https://cloud.githubusercontent.com/assets/20476168/19626735/5f698cac-9940-11e6-9e34-c21c292b99c9.PNG)
</details>

**Comment by Alex-302** [comment]
Added to English filter
```
@@||sportsnet.ca/wp-content/plugins/bwp-minify/$domain=sportsnet.ca
```
