### ISSUE TITLE
literaturcafe.de

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3253]
**Site**: http://www.literaturcafe.de/
**Description**: Adguard detected.

**Current behaviour**: Site shows a adblock detection message.

<details>
<summary>Screenshot</summary>
![2016-10-23 17_58_18-vorlesung](https://cloud.githubusercontent.com/assets/10995998/19627606/a4f0df6e-994a-11e6-9698-2985ecd71963.png)
</details>

========

**Expected behaviour**: Detection message should be blocked.

<details>
<summary>Screenshot</summary>
![2016-10-23 17_58_43-literaturcafe de der literarische treffpunkt im internet](https://cloud.githubusercontent.com/assets/10995998/19627607/a7d33ad8-994a-11e6-93bd-ad60466de4a9.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.44
Spyware filter 1.0.8.44
Social media filter 1.0.13.93
Annoyances filter 1.0.5.65
German filter 1.0.27.98

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
literaturcafe.de###sidebar div[class^="box-outer text-"][-ext-has=">.box-inner>h2:contains(Anzeige)"]
```
