### ISSUE TITLE
indianexpress.com - Adguard detection

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3254]
Windows 10
Adguard 6.1
Filters
<details>
![filters](https://cloud.githubusercontent.com/assets/20476168/19628084/a0ce5f6a-995e-11e6-85b8-674661ce72a7.PNG)
</details>
Entered users link (http://indianexpress.com/article/lifestyle/books/wonder-woman-is-75-but-this-superheros-feminist-origins-keeps-her-relevant-3098345/) And got such screen
<details>
![image](https://cloud.githubusercontent.com/assets/20476168/19628094/dd709a32-995e-11e6-866c-69b8e6bc8fed.png)
</details>
Ticket Id 1406620

**Comment by seanl-adg** [comment]
Added to English filter:
```
||s1.wp.com/*/ie_block_redirect.js$important,domain=indianexpress.com
indianexpress.com#%#window.RunAds = !0;
```
