### ISSUE TITLE
www.nbcsports.com - detects Adguard during streaming

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3255]
Windows 10
Adguard 6.1.258.1302
Happens on Edge, IE and Firefox
Filters
<details>English filter
Spyware filter
Social media filter
Experimental filter
Annoyances filter
Anti-Adblock Killer</details>

When you start watching online stream Anti Adblock script runs.

Screenshot
<details>
![image](https://cloud.githubusercontent.com/assets/20476168/19628757/93c0c470-996d-11e6-8413-335fc2315e67.png)
</details>
Ticket id 1032209

**Comment by Alex-302** [comment]
Not reproduced, but player is not working on my end.
Added to English filter
```
@@||pdk.theplatform.com/*/AdManager.swf$domain=vplayer.nbcsports.com
@@||mssl.fwmrm.net/crossdomain.xml$domain=vplayer.nbcsports.com
@@||bea4.v.fwmrm.net/ad/u$domain=nbcsports.com
@@||mssl.fwmrm.net/p/nbcu_sports_tp_live/AdManager.swf$domain=vplayer.nbcsports.com
```
Please check these rules.
