### ISSUE TITLE
http://www.yourlifestyle.ru/ - ADs

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3256]
## На сайте полно рекламы.

![2016-10-23_22-11-41](https://cloud.githubusercontent.com/assets/16462533/19628774/c4b761b0-996d-11e6-95c1-49021ec634e4.png)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||yourlifestyle.ru/ads*.js
```
