### ISSUE TITLE
www.theinquirer.net - Detects Adguard

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3257]
Windows 10 
Adguard 6.1
Reproduced on Opera, Chrome, Edge.
Filters
<details>
![filters](https://cloud.githubusercontent.com/assets/20476168/19628874/9bd706c6-9970-11e6-9b0a-a0b6bcb3653b.PNG)
</details>

Everything seems ok, bu when you try to read some articles (example: http://www.theinquirer.net/inquirer/review/2474485/google-pixel-xl-review)
You get such blocked content
<details>
![image](https://cloud.githubusercontent.com/assets/20476168/19628890/e7c61766-9970-11e6-8fcf-c328bc0fb796.png)
![image](https://cloud.githubusercontent.com/assets/20476168/19628891/f6698942-9970-11e6-95d9-a236b380f104.png)
</details>

ID 978434

**Comment by Alex-302** [comment]
Added to English filter
```
@@||securepubads.g.doubleclick.net/gampad/ads$domain=theinquirer.net
@@||partner.googleadservices.com/gpt/pubads_impl_$domain=theinquirer.net
@@||googletagservices.com/tag/js/gpt.js$domain=theinquirer.net
@@||ssl.cf3.rackcdn.com/Pub/*$domain=theinquirer.net
@@||ssl.cf3.rackcdn.com/Ads/*$domain=theinquirer.net
@@|http://*.theinquirer.net/$script
@@||theinquirer.net^$generichide
theinquirer.net##.ad-slot-full
theinquirer.net#%#window._r3z = {}; Object.defineProperties(window._r3z, { jq: { value: undefined }, pub: { value: {} } });

```
