### ISSUE TITLE
nnmclub.to - ads

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3258]
![img_0605](https://cloud.githubusercontent.com/assets/16462533/19629201/bb5c803c-9977-11e6-8e64-6f7eacf51241.PNG)

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/2654

**Comment by Alex-302** [comment]
В Сафари в Макоси чисто, на иосном проверить не могу.

**Comment by Serzh-SUP** [comment]
@Alex-302 
У меня повторяется. Что-то предоставить?

**Comment by Alex-302** [comment]
@Serzh-SUP 
доступ
