### ISSUE TITLE
trouw.nl, trouw.nl, tweakers.net - annoyances

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3260]
Missed cookies notifications

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/19640523/ca51c9bc-99e5-11e6-9351-cc627cec43b5.png)
![image3](https://cloud.githubusercontent.com/assets/15856304/19640542/e181ad1e-99e5-11e6-9450-cea44fcd64b9.png)
![image1 1](https://cloud.githubusercontent.com/assets/15856304/19640562/f4cb2cf6-99e5-11e6-9e81-427f76242f72.png)

![image](https://cloud.githubusercontent.com/assets/15856304/19640571/04763394-99e6-11e6-990d-6c1ac76ccd7e.png)

**Comment by Alex-302** [comment]
It is impossible on iOS.

**Comment by evgeniy-ADG** [comment]
Could you please tell us more about the reasons so we could use this info when working with customers?

**Comment by Alex-302** [comment]
Limitation of Safari content blocker(Apple). We can only block utl and hide elements by CSS. JS is not supported in mobile Safari.
