### ISSUE TITLE
linkedin.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#32618]
`https://www.linkedin.com/jobs/`

Top cookie notice.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.6
Firefox 66

**Comment by BlazDT** [comment]
Fixed for AdGuard products which support javascript.

For user filter if you do not care about error messages on top like "Emails aren’t getting through to one of your email addresses. Please update or confirm your email. More info":

`linkedin.com##artdeco-global-alert[severity="notice"]`

If the mentioned element is hidden, the other notice is not displayed.

**Comment by adranger** [comment]
@BlazDT please answer this:
>Are you able to reproduce such warning ? Provide the necessary steps.
 https://github.com/uBlockOrigin/uAssets/issues/5356#issuecomment-483852416

**Comment by BlazDT** [comment]
Replied there @adranger
