### ISSUE TITLE
stealth mode causes issue with playback on Google Drive

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3261]
**Description**:
https://github.com/AdguardTeam/AdguardForWindows/issues/1326

**Comment by Alex-302** [comment]
@ameshkov  Confirmed with "Hide search queries", but can't fix it. Tried to exclude all domains
`@@||***$stealth` and `@@||` but without result.

**Comment by seanl-adg** [comment]
`@@||youtube.googleapis.com/embed/$jsinject` resolves the stealth mode issue for me, I'll try to narrow down which JS rule is causing it

**Comment by Alex-302** [comment]
It seems that is broken not by a specific rule.

**Comment by seanl-adg** [comment]
Even if I add a rule @@||youtube.googleapis.com/embed/$stealth Adguard still injects some scripts related to stealth mode, also even if I enable only "hide your search queries" option, it replaces document.referrer into "http://adguard.com/referrer.html"
Can somebody reproduce this?

**Comment by seanl-adg** [comment]
I can't reproduce this issue with the latest beta. Can somebody check?

**Comment by ameshkov** [comment]
Should be resolved now
