### ISSUE TITLE
vivareal.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#32617]
`https://www.vivareal.com.br/`

Mobile app banner.

Adguard Base + Annoyances + Mobile + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.6
Firefox 66 for Android

**Comment by BlazDT** [comment]
Fixed for products which support #$# rules.
With normal CSS hiding rules you will have left-over at top where the banner was showing.

**Comment by adranger** [comment]
Thanks. That works on uBlock Origin.
