### ISSUE TITLE
Focus online app - doesn't play videos when enabled spyware filter in Adguard

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3262]
Lenovo S860
Android 4.4.2
Filters
<details>
![filters](https://cloud.githubusercontent.com/assets/20476168/19646132/c6b4b236-9a00-11e6-93f1-3a95d6f69b66.PNG)
+Mobile Ads Filter
</details>
HTTPS enabled

When Spyware filter enabled videos don't play (infinite loading) 
Disabling Spyware filter resolves the issue.

HTTP log 15:32
[issue.zip](https://github.com/AdguardTeam/AdguardFilters/files/547788/issue.zip)

**Comment by Alex-302** [comment]
Does he use Adguard for Windows as proxy?

**Comment by Fridrix** [comment]
@Alex-302 Seems like he uses VPN mode
 "proxyMode" : false,  
"proxySetupManualMode" : false,

**Comment by Alex-302** [comment]
@Fridrix Ask then how it works on user's device.

**Comment by Alex-302** [comment]
Is is caused by mobile filter, not spyware.
Added to Mobile filter
```
@@||imasdk.googleapis.com^$app=de.cellular.focus
```

**Comment by Alex-302** [comment]
@Fridrix don't use a bug label when an issue caused by filters.

**Comment by Fridrix** [comment]
@Alex-302 ok. Got it.
