### ISSUE TITLE
ain.ua - ADs

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3263]
## http://ain.ua/2016/10/24/677569

![2016-10-24_16-30-25](https://cloud.githubusercontent.com/assets/16462533/19647876/c23cac88-9a08-11e6-9e43-5f3d41f7564a.png)

Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
ain.ua###subbody > a[target="_blank"][style^="position: fixed; top: 0px;"]
ain.ua#$#body { margin-top: 0px!important; }
```
