### ISSUE TITLE
Yandex.Direct AD in Yandex.Map

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3264]
## Повторилось, реклама появилась в картах Яндекс. Перешел по ссылке предоставленной пользователем:

https://yandex.ru/maps/213/moscow/?ncrnd=3316&l=trf%2Ctrfe&ll=37.766992%2C55.694474&z=12

![2016-10-24_17-11-13](https://cloud.githubusercontent.com/assets/16462533/19649156/673fe3ea-9a0d-11e6-8f80-f6c273a99cab.png)

```
Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский
```

**Comment by Alex-302** [comment]
Fixed.

**Comment by Serzh-SUP** [comment]
## Возобновилось.
![2016-11-16_21-44-06](https://cloud.githubusercontent.com/assets/16462533/20363046/695a0868-ac46-11e6-8d45-c2fdfc8c9860.png)

**Comment by Alex-302** [comment]
Not reproduced
<details>
![image](http://img.ii4.ru/images/2016/11/17/792106_kiss_405kb.png)
</details>

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
yandex.ua#$#.traffic-home-panel-view__body div[style*="visibility: visible"][style$="!important"] { position: absolute!important; left: -2000px!important; }
```
