### ISSUE TITLE
www.hgtv.com - doesn't play videos when Adguard enabled

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3265]
Windows 10
Adguard 6.1
Filters
<details>
![filters](https://cloud.githubusercontent.com/assets/20476168/19649858/09801d94-9a10-11e6-9aad-910699710bd7.PNG)
</details>
When you open video page and try to watch one of them you see just black player screen

Link:
http://www.hgtv.com/design/hgtv-urban-oasis/2016/hgtv-urban-oasis-2016-videos
Screenshot
<details>
![image](https://cloud.githubusercontent.com/assets/20476168/19650014/7ec06924-9a10-11e6-97c4-93995105cea7.png)
</details>
Adguard disabled screenshot
<details>
![image](https://cloud.githubusercontent.com/assets/20476168/19650106/c5062aa4-9a10-11e6-8b00-6c7c8ce06f7b.png)
</details>

Id 1182387

**Comment by Alex-302** [comment]
Added to English filter
```
@@||pdk.video.snidigital.com/*/AdManager.swf$domain=hgtv.com
@@||adm.fwmrm.net/p/scripps_pdk_flash_live/AdManager.swf$domain=hgtv.com
@@||adm.fwmrm.net/p/scripps_pdk_flash_live/Video2AdRenderer.swf$domain=hgtv.com
```
@Fridrix User should to check them. I'm waiting for reply.

**Comment by Fridrix** [comment]
@Alex-302 reproduced on my side. Player works, but i see advertisement video. Sent to to user. Wait for the reply.

**Comment by Alex-302** [comment]
@Fridrix Do you see the main video after ads with and without Adguard?

**Comment by Fridrix** [comment]
@Alex-302 Nope. But i can't see it neither with Adguard disabled.

**Comment by Alex-302** [comment]
@Fridrix Ask then how it works on user's device.
