### ISSUE TITLE
https://www.newstube.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3266]
https://www.newstube.ru/
При включеной блокировке не воспроизводится видео.

В вложении 2 скрина, на 1 все включеные у меня фильтры, на втором того что при этом с сайтом (вечно крутящееся колесико загрузки), начинает работать нормально только если отключаю все кроме номера 2, 3, 4 с первого скрина. При добавлении любого из отключеных четырех, проблема повторяется.
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/19680835/d3ffaa36-9aaf-11e6-8284-ac086318e4d8.png)
![image 1](https://cloud.githubusercontent.com/assets/15856304/19680839/d50ca55a-9aaf-11e6-8adb-71670d9f85d1.png)
</details>

1420001

**Comment by evgeniy-ADG** [comment]
У нас не повторяется никак, куда можно еще покопать?

**Comment by Alex-302** [comment]
Выключать фильтры по одному с конца и проверять.
У меня тоже работает, но Сафари десктопный.
