### ISSUE TITLE
http://simple.ripley.cl/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3267]
Guys from http://simple.ripley.cl/ will change their internal offers system to DFP and wonder if they will be blocked by Adguard after that.

They enabled DFP for a few ads and here is the results (attachments shows same section in http://simple.ripley.cl/ . One with adblock enabled and the other with adblock disabled.

Ripley-Electro section (no adblock).png
<details>

![ripley-electro section no adblock](https://cloud.githubusercontent.com/assets/15856304/19682669/5b46830a-9ab7-11e6-8434-5c9e5d1276c1.png)

</details>
Ripley-Electro section (adblocked)
<details>

![ripley-electro section adblocked](https://cloud.githubusercontent.com/assets/15856304/19682688/6dbde76c-9ab7-11e6-9c85-765c650eb66f.png)

</details>
1433374

**Comment by Alex-302** [comment]
Added to English filter
```
@@||simple.ripley.cl$generichide
@@||partner.googleadservices.com/gpt/pubads_impl_$domain=simple.ripley.cl
@@||securepubads.g.doubleclick.net/gampad/ads$domain=simple.ripley.cl
@@||tpc.googlesyndication.com/simgad/*$domain=simple.ripley.cl
```

**Comment by bfell** [comment]
Hello guys,

I'm still getting the issue. Is this supposed to become available immediately or takes a few hours?

Thanks in advance 

Attach picture of the issue:


![ripley-electro section adblocked](https://cloud.githubusercontent.com/assets/5280738/19691092/5844fd52-9aa9-11e6-995d-5f75b3010374.png)

**Comment by evgeniy-ADG** [comment]
Hi there! Could you please make sure your filters are up to date?

**Comment by bfell** [comment]
Yes that was it!

Thanks guys

**Comment by evgeniy-ADG** [comment]
@Alex-302 the customer reported they have the same problem with http://simple.ripley.com.pe
Ticket: 1506223

**Comment by Alex-302** [comment]
@evgeniy-ADG not reproduced. Which filters are enabled?

@bfell could you, please, check it?

**Comment by bfell** [comment]
Yes @Alex-302 our fellows from Peru want to implement DFP aswell but you can't reproduce because it is not implemented yet. They want to be added as a prevention measure and then install the dfp blocks.
Could they be added to filter before installing dfp or you need live proof that is being blocked?
Thanks in advance

**Comment by Alex-302** [comment]
oh, domain name is different
please try
```
@@||simple.ripley.com.pe$generichide
@@||partner.googleadservices.com/gpt/pubads_impl_$domain=simple.ripley.com.pe
@@||securepubads.g.doubleclick.net/gampad/ads$domain=simple.ripley.com.pe
@@||tpc.googlesyndication.com/simgad/*$domain=simple.ripley.com.pe
```

**Comment by JohanLlerena** [comment]
Hello @ Alex-302 is correct, they are different domains. Would you confirm us if the request was made?

Thanks since now.

**Comment by Alex-302** [comment]
I see that google ulrs, but can't reproduce the issue.

**Comment by JohanLlerena** [comment]
Hi @Alex-302 at the moment the problem of block is not visualized in our web since we only did the tests for a moment to see if Adguard still blocks our publications, I show you screenshots:

Adguard active
![captura](https://cloud.githubusercontent.com/assets/25959465/23237594/1575afb2-f92c-11e6-9912-0dfc909d9429.JPG)

Adguard deactivated
![captura2](https://cloud.githubusercontent.com/assets/25959465/23237604/2378c19e-f92c-11e6-88dd-40d3d283e4c1.JPG)

**Comment by Alex-302** [comment]
Strange. It works fine on my side
[CODE]
http://imagizer.imageshack.com/img923/7106/j4jo45.png
[/CODE]
Are you using another ad blocking software?

**Comment by bfell** [comment]
@JohanLlerena Could you make sure your adguard filters are up to date?

**Comment by JohanLlerena** [comment]
Hi @Alex-302, we are only using Adguard.

**Comment by Alex-302** [comment]
@JohanLlerena I can take a look via TeamViewer tomorrow(by Moscow time)

**Comment by JohanLlerena** [comment]
Hello @Alex-302 , we are still blocked by Adguard. Could you help us with this, please?

**Comment by Alex-302** [comment]
@JohanLlerena what do you mean?
Try
```
@@||simple.ripley.com.pe$generichide
@@||partner.googleadservices.com/gpt/pubads_impl_$domain=simple.ripley.com.pe
@@||securepubads.g.doubleclick.net/gampad/ads$domain=simple.ripley.com.pe
@@||tpc.googlesyndication.com/simgad/*$domain=simple.ripley.com.pe
```

**Comment by veronikasav** [comment]
@Alex-302 We tried to add these rules and it didn't help:

@@||simple.ripley.com.pe$generichide
@@||partner.googleadservices.com/gpt/pubads_impl_$domain=simple.ripley.com.pe
@@||securepubads.g.doubleclick.net/gampad/ads$domain=simple.ripley.com.pe
@@||tpc.googlesyndication.com/simgad/*$domain=simple.ripley.com.pe

Need your help
Ticket ID: 1506223

**Comment by Alex-302** [comment]
works fine on my end. Added
