### ISSUE TITLE
com.anoshenko.android.fav_solitaires

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3268]
**Description**: 
https://play.google.com/store/apps/details?id=com.anoshenko.android.fav_solitaires&hl=ru

Заставка с рекламой появляется каждый раз после удачного расклада пасьянса. Когда неудачная попытка, не появляется. Очистка кеша ничего не дает.

Лог
[debug (7).txt](https://github.com/AdguardTeam/AdguardFilters/files/550525/debug.7.txt)

Скрин:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19689418/ff156c1c-9ad5-11e6-9bca-99dce67cb30d.png)
</details>

**Adguard version**: 2.8.15

**Filters list**: 2, 3, 4, 5, 14, 1, 11, 116, 211
 "filteringQuality" : "FULL",
HTTPS включен

**Operating system**: Андроид

**Comment by Alex-302** [comment]
@vgavrish Лучше записать HAR? предварительно очистив кэш игры.

**Comment by vgavrish** [comment]
окей, написала

**Comment by vgavrish** [comment]
Хар https://yadi.sk/d/gOmiHLnsxzJpD
говорит это все файлы
кэш и данные стирал

**Comment by Alex-302** [comment]
<details>
![image](http://imagizer.imageshack.com/img921/2645/wCqxF7.png)
</details>
всё, что с кодом 500 и 0 - заблокировано. Других рекламных запросов нет.
Какой режим фильтрации?

**Comment by vgavrish** [comment]
Был "filteringQuality" : "FULL",

**Comment by Alex-302** [comment]
это алгоритм. Режим - VPN или прокси(ручной/авто)

**Comment by vgavrish** [comment]
ой, сори
ВПН

**Comment by Alex-302** [comment]
Тогда странно. Запроси, наверное, свежий полный лог, с предварительным закрытием приложением и очисткой кэша, и указанием точного времени запуска приложения.
И продублируй в раздел Дроида, а то у меня идей больше нет.

**Comment by vgavrish** [comment]
ок

**Comment by vgavrish** [comment]
> Оказывается реклама встроена в эту игру.Там даже в настройках есть позиция выбора  между постоянным небольшим банером и полноэкранным. Я удалил пасьянсы т.к. с рекламой пользоваться её неудобно.
