### ISSUE TITLE
torrentom.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3269]
**Description**: 
**UC Browser**
Всплывающие окна после нажатия на панель открытия видео во весь экран
http://torrentom.com/film/Komediya/online-ochen-plohie-mamochki.htm

+ Просьба скрыть ненужный элемент самого браузера 
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19687343/b87d4174-9acd-11e6-87e5-a5d0880c8305.png)
</details>

Screenshot рекламы:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19687444/0c6169a0-9ace-11e6-8453-106c6955f432.png)
 </details>

**Хром** Реклама в первом плеере. При нажатии на второй плеер ниже, открывается всплывающее окно.
У пользователя еще в первом верхнем плеере появляется реклама в виде Алиэкспресс
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19687607/cf89364c-9ace-11e6-8e88-39c93c1a6c21.png)
![image](https://cloud.githubusercontent.com/assets/18548949/19687685/20461794-9acf-11e6-936f-378bcc7323d0.png)
</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: UC Browser, Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Реклама как на последнем скрине не повторилась.
Добавил:
```
||01n2e3pac2.com^$popup
||player.kinotreiler.com/media_adv/
||sv.ltzvs.ru^
```
То, что добавляет в плеер UС Browser, можно попробовать убрать помощником.

**Comment by vgavrish** [comment]
А помощником оно выделяет только весь плеер http://prntscr.com/cz5pl7

**Comment by Alex-302** [comment]
Так я про ту оранжевую штуку, которую UC браузер добавляет.
