### ISSUE TITLE
allestörungen.de

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3270]
**Site**: http://www.allestörungen.de/
**Description**: Adguard detected.

**Current behaviour**: Site shows a detection message.

<details>
<summary>Screenshot</summary>
![image](https://cloud.githubusercontent.com/assets/10995998/19692206/64d2bc3e-9ad7-11e6-9b69-0996d2042fa5.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.72
Spyware filter 1.0.8.47
Social media filter 1.0.13.96
Annoyances filter 1.0.5.70
German filter 1.0.28.1

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by danidoedel** [comment]
It takes a few moments until that message pops up.

**Comment by danidoedel** [comment]
Ok doesn't happen anymore... strange. I will reopen if it does again :)
