### ISSUE TITLE
http://m.ynet.co.il - shows ads

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3271]
Ads on ynet.co.il and mako.co.il. Ads from (www.cappsool.com ad server) Tested on our side. Nothing happens no ads. 
Meizu MX4 Pro
Android 5.1.1
Ver. 2.7.220
HTTPS Enabled
Filters
<details>
English filter
Spyware filter
Social media filter
Experimental filter
Filter unblocking useful ads
Mobile Ads filter
EasyList Hebrew
Anti-Adblock Killer | Reek
</details>
Screenshot
<details>
![yanet](https://cloud.githubusercontent.com/assets/20476168/19695929/b6c6379e-9aed-11e6-9ee1-a0452496d10d.jpg)
</details>
ID 1433884
Debug file:
[d.zip](https://github.com/AdguardTeam/AdguardFilters/files/551259/d.zip)

**Comment by Alex-302** [comment]
Not reproduced.
Try
```
||cappsool.com^$domain=ynet.co.il
ynet.co.il##div[id^="GoogleAdStrip"]
```
