### ISSUE TITLE
Ads in  Paytm , Lufthansa, Money manager, Instagram

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardFilters#3273]
Ads in many applications. Seems something wrong with the device.
Xiaomi MI MAX
Ver. 2.7.220
HTTPS enabled
Android 6.0.1
Filters
<details>
English filter
Spyware filter
Social media filter
Experimental filter
Annoyances filter
Anti-Adblock Killer
Mobile Ads Filter
</details>
Screenshot
<details>
![image](https://cloud.githubusercontent.com/assets/20476168/19696577/5c1e2fec-9af0-11e6-8d45-7277c022c1dd.png)
</details>
HTTP request log
[iss.zip](https://github.com/AdguardTeam/AdguardFilters/files/551298/iss.zip)
between 21:57 & 21:59
Id 1435262

**Comment by evgeniy-ADG** [comment]
@Fridrix Instagram is whitelisted, it checks the certificate so they had to do that. There's a bunch of Lufthansa apps in the store. The customer mentioned a lot of other apps that you didn't specify here. Thanks for the awesome task.
Asked for screenshots and links.

**Comment by Alex-302** [comment]
One app - one issue.
