### ISSUE TITLE
claro.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#32744]
`https://www.claro.com.br/celular/controle`

Overlay annoyance. Wait for the page to load completely, and then move your mouse cursor to another tab.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.6
Firefox 66

**Comment by adranger** [comment]
@Alex-302  `https://planos.claro.com.br/monte-sua-combinacao`

Enter this info: 
CEP 01420-000
Número 616

![net](https://user-images.githubusercontent.com/35470489/61295693-05353800-a7af-11e9-9fda-689f858a9ecd.png)

The overlay when you move the cursor out of the page:

![net2](https://user-images.githubusercontent.com/35470489/61295789-3877c700-a7af-11e9-8e70-cba78ada5282.png)

**Comment by Alex-302** [comment]
not good rules. Better for custom filter:
```
planos.claro.com.br#$#.cdk-overlay-backdrop { display: none !important; }
planos.claro.com.br#$#.cdk-global-overlay-wrapper { display: none !important; }
planos.claro.com.br#$#body { overflow: visible!important; }
```
