### ISSUE TITLE
http://smexo.tv - anti-adblock script

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#3274]
При попытке зайти, просит отключить эдблок. Фильтры по-умолчанию, версия 2.7(не бета). http://smexo.tv/iframe_player/?essenceId=53&entityId=92260&uid=38220

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/19714266/5ecb9ce2-9b55-11e6-8985-52cebc20da2f.png)

**Comment by Alex-302** [comment]
Fixed.
