### ISSUE TITLE
https://m.gasbuddy.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3275]
https://m.gasbuddy.com/touch/#StationList_page
I was unable to reproduce it. User said that Pro blocks the banner but he uses DNS quite rarely because he has another VPN app. Could you please check why it's not blocked? See logs attached.

![image1 3](https://cloud.githubusercontent.com/assets/15856304/19714756/58fff26e-9b59-11e6-9e3f-29ee8187375f.png)
<details>
 Timing was 6:27AM Pacific time
Check logs here: 
[filter.gz](https://github.com/AdguardTeam/AdguardFilters/files/552418/filter.gz)

Application version: 1.1.2.24
Application lifetime: 2016-10-15 13:52:14 +0000

Device: iPhone
Platform: iOS
OS: 10.0.2
ID: 4DD28E22-87C5-48BB-A8CB-09AEBB493143

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.98.70 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.47 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.96 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.70 Enabled=YES
ID=6 Name="German filter" Version=1.0.28 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.38 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.55 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.67.82 Enabled=YES

**Comment by Alex-302** [comment]
The site is clean with user's content blocker file.
