### ISSUE TITLE
https://order.suddenlink.com/Buyflow/Storefront - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3277]
Hi, I can't seem to click continue on this website: https://order.suddenlink.com/Buyflow/Storefront

It's a website for SuddenLink to check if their service is available in an area.
When I disable Adguard, the button works.

<details>
Application version: 1.1.1.54
Application lifetime: 2016-09-24 18:43:33 +0000

Device: iPhone
Platform: iOS
OS: 10.1
ID: E6EE168B-24C6-4CA1-AE7F-8E481F409DD4

Locale: en
Region: us

Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.98.76 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.50 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.98 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.55 Enabled=YES
</details>

1437647

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||cdn.mxpnl.com/libs/mixpanel-*.min.js$domain=order.suddenlink.com
```
