### ISSUE TITLE
gazetteandherald.co.uk & wiltshiretimes.co.uk

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3278]
1419164
**Description**: large blue box at the bottom of every page on the site
gazetteandherald.co.uk
wiltshiretimes.co.uk

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19732133/778ddb98-9ba8-11e6-8327-26f66c3e7e1a.png)
![image](https://cloud.githubusercontent.com/assets/18548949/19732246/d69227fc-9ba8-11e6-831e-e84f4c3fee92.png)

</details>

**Filters list**: 1,2,3,4,14,211

**Operating system**: Win

**Browser**: Chrome

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
