### ISSUE TITLE
cityam.com anti-adblock

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3279]
**Description**:
http://www.cityam.com/252183/winners-and-losers-heathrow-expansion

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19732291/097ecb34-9ba9-11e6-94c8-eb8ddfc5619e.png)
</details>

**Filters list**: 1,2,3,4,14,211

**Operating system**: Win

**Browser**: Chrome

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
