### ISSUE TITLE
yts.ac

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#3280]
www.yts.ac
Lots of popups and malware redirects.
Should we try to fix it or just add to safebrowsing filter?
Please assist.

**Comment by jo2dan23** [comment]
Yts.ag is the Real one.  This might be a fake site

**Comment by vozersky** [comment]
@jo2dan23  .ac one will go to safebrowsing filter then, cheers mate. But isn't yts.ph the real one?

**Comment by jo2dan23** [comment]
It looks like there are multiple fake sites. Example: https://yts.la requires registration to view site. But see here: https://torrentfreak.com/yts-ag-wants-to-be-the-new-yify-on-popular-torrent-sites-151113/

Yify is shut down but yts.ag is just bringing it back to life

**Comment by vozersky** [comment]
Thanks again.

**Comment by jo2dan23** [comment]
yts.ac does have 258 more movies than yts.ag though. so i dont know which one is better. lol
