### ISSUE TITLE
airport-nuernberg.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3281]
**Site**: https://www.airport-nuernberg.de/
**Description**: Cookie notice not blocked.

**Current behaviour**: Site shows a cookie notice at the top.

<details>
<summary>Screenshot</summary>
![image](https://cloud.githubusercontent.com/assets/10995998/19741171/f4e06342-9bbf-11e6-8625-09b5decd5405.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.83
Spyware filter 1.0.8.55
Social media filter 1.0.13.99
Annoyances filter 1.0.5.72
German filter 1.0.28.3

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
airport-nuernberg.de###cookies_hint
airport-nuernberg.de#$#body.pt50 { padding-top: 0px!important; }
```
