### ISSUE TITLE
gaming.youtube.com/de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3282]
**Site**: https://gaming.youtube.com/de
**Description**: Cookie notice not blocked.

**Current behaviour**: Site shows a cookie notice at the bottom.

<details>
<summary>Screenshot</summary>
![image](https://cloud.githubusercontent.com/assets/10995998/19742178/14555292-9bc4-11e6-9ee4-66d17b1ebb94.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.83
Spyware filter 1.0.8.55
Social media filter 1.0.13.99
Annoyances filter 1.0.5.72
German filter 1.0.28.3

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Not shown. Could you make a screenshot of html of this message?

**Comment by danidoedel** [comment]
I hope that's what you need:
![image](https://cloud.githubusercontent.com/assets/10995998/19783361/fa8a524e-9c91-11e6-82c1-94695ce5df5e.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
gaming.youtube.com##.ytg-notification-footer
```
