### ISSUE TITLE
touch.lovescout24.de - iOS - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3283]
**Site**: https://touch.lovescout24.de/
**Description**: Cookie notice not blocked.

**Current behaviour**: Site shows a cookie notice at the top.

<details>
<summary>Screenshot</summary>
![image](https://cloud.githubusercontent.com/assets/10995998/19742383/1a3b481e-9bc5-11e6-97d1-1ade4a6e210d.png)
</details>

========

**Adguard version**: 1.1.1

**Filters list**: 
English filter 1.0.98.83
Spyware filter 1.0.8.55
Social media filter 1.0.13.99
Annoyances filter 1.0.5.72
German filter 1.0.28.3
Mobile ads filter 1.0.5.44
Safari filter 1.0.1.56

**Operating system**: iOS 10

**Browser**: Safari

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
lovescout24.de###i-cookie-cnil
```
