### ISSUE TITLE
Can't create the exception for Google Play Music

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#3285]
When I try to add Google Play Music website to exceptions, it fails; assistant always comes back.
Added to HTTPS exceptions but that didn't help.

Steps to reproduce:
1. Go to: https://play.google.com/music/listen
2. Add this website to exceptions

User's video:
https://www.dropbox.com/s/bars0ocl8tcp96b/Google%20Play%20Adguard.mov?dl=0

**Adguard version**: 1.3.0

**Filters list**: http://prnt.sc/czr9h4

**Comment by Alex-302** [comment]
Please write it to Mac repository.

**Comment by evgeniy-ADG** [comment]
I reproduced it on Wondows.

**Comment by Alex-302** [comment]
I can't fix bugs of the app.

**Comment by evgeniy-ADG** [comment]
So should we file this to both windows and mac projects or what?

**Comment by Alex-302** [comment]
Better ask it the chat. I'm not sure that is a bug.
