### ISSUE TITLE
APKPure ß App has unblocked ads

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardFilters#32867]
@TPS commented on [Fri Apr 12 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2703)

The APKPure app, since recent versions, has unblocked ads, especially upon launching.
### Steps to reproduce

1. Download ß app from https://m.apkpure.com/apkpure-app.html & install
2. Open app.
3. If wished, browse around.
4. Check AG log.

### Expected behavior

No ads, no counter, & blocks shown in AG log.

### Actual behavior

An opening intersticial ad appears, complete w/ timeout counter.  When checking AG log, not much useful info appears to help block it.

Screenshot: Can't upload example of actual ad 😕

</details>

### Customer ID 

1122984
### Your environment

* Adguard version: 3.0.311η
* Adguard filtering mode: Local VPN
* Device model: Moto G5+
* Operating system and version:  Android Oreo 8.1.0
* Root access:  No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: 
No

---

@zzebrum commented on [Mon Apr 15 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2703#issuecomment-483163827)

@TheHasagi try to repro, move to filters repo if needed.

---

@TPS commented on [Sat Apr 20 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2703#issuecomment-485163036)

I think I've solved this for myself.  Firstly, I *en*abled HTTPS Filtering for the app, which seems to show more requests in the AG log related to it, w/o affecting functionality!  Then I tried the following filters.  (I don't know whether any are redundant or irrelevant, or *dis*abling HTTPS Filtering for it would work):
````
||zcoup.
54.179.191.158$network
||a.pureapk.com^
||admarvel.

---

@lancelot-moon commented on [Sun Apr 21 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2703#issuecomment-485231592)

This isn't app's issue and should be moved to filters repo.

---

@TPS commented on [Sun Apr 21 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2703#issuecomment-485249884)

I wasn't sure, because of that № 1 step of first toggling the defaulted HTTPS Filtering.

---

@ameshkov commented on [Mon Apr 22 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2703#issuecomment-485369167)

@AdguardTeam/filters-maintainers guys, could you please take a look?

---

@Alex-302 commented on [Mon Apr 22 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2703#issuecomment-485376767)

@TPS please make screenshot of ads.
admarvel must be blocked by mobile filter.

---

@TheHasagi commented on [Mon Apr 22 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2703#issuecomment-485390258)

Unable to reproduce. Please, download or update to the release version 3.0.297.

**Comment by TPS** [comment]
@TheHasagi I'm actually on 3.0.315η, so that's ok, but it'll take me few days to try to figure out why I can't upload screenshot to GitHub via mobile.  Probably, I'll do it via desktop, instead.…
