### ISSUE TITLE
telekom.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3286]
**Site**: https://www.telekom.de/
**Description**: Cookie notice not blocked.

**Current behaviour**: Site shows a cookie notice at the top.

<details>
<summary>Screenshot</summary>
![image](https://cloud.githubusercontent.com/assets/10995998/19783501/7cfc637a-9c92-11e6-9bc9-fb0322914606.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.98.90
Spyware filter 1.0.8.57
Social media filter 1.0.14.3
Annoyances filter 1.0.5.75
German filter 1.0.28.4

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
telekom.de##.message-bar
```
