### ISSUE TITLE
uploadocean.com anti adblock

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#3287]
Hey
have in site uploadocean.com anti adblock
exmple:
https://uploadocean.com/aktv7d59gb12
http://prntscr.com/cz7jt2

**Comment by Alex-302** [comment]
Nothing:
<details>
![image](http://i82.fastpic.ru/big/2016/1028/e5/01413fab4d2935f9391e9d5c64611de5.png)
</details>

**Comment by MrTal** [comment]
now i see this work

**Comment by Alex-302** [comment]
ok

**Comment by MrTal** [comment]
now this no work with link:
https://uploadocean.com/zp4wqajfv7uu

**Comment by Alex-302** [comment]
Which Adguard version?

**Comment by Alex-302** [comment]
temporary added
```
@@||uploadocean.com^$generichide,content
```

**Comment by MrTal** [comment]
still have anti adblock:
http://prntscr.com/cz7jt2\
version Adguard: 6.1.258.1302

**Comment by Alex-302** [comment]
It is ok on my end
http://i82.fastpic.ru/big/2016/1031/6f/4ddf4e9f6b4766255e982e0ffafa9b6f.png
Which filters are you using?
