### ISSUE TITLE
videolishd.com

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#32885]
https://videolishd.com/movie/40148588499aa3f6cd6063fb2532268a/iframe
Видео реклама перед началом просмотра и при перемотке.

**Comment by Alex-302** [comment]
@Smorvel прога или расширение? С прогой фильтрация HTTPS отваливается, а расширение - блокирует.

**Comment by Smorvel** [comment]
@Alex-302 прога..

**Comment by Alex-302** [comment]
@Smorvel Сейчас HTTPS фильтруется, рекламы нет. Глянь у себя.

**Comment by Smorvel** [comment]
Да, нету. (но у меня теперь 7 адгард, когда писал не помню какой версией пользовался)

**Comment by Alex-302** [comment]
ок
