### ISSUE TITLE
https://dnevnik.ru/ - Assistant doesn't show up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3289]
https://dnevnik.ru/

the user filter is clear

![image](https://cloud.githubusercontent.com/assets/15856304/19814995/645b4bf8-9d49-11e6-9ca2-ad90ca52b199.png)

**Comment by Alex-302** [comment]
В исключениях он, т.к. никто не дал доступ для устранения ложного срабатывания.

**Comment by Alex-302** [comment]
Исключение удалил. Будут жаловаться - сразу доступ просите.

**Comment by evgeniy-ADG** [comment]
ок
