### ISSUE TITLE
Whitelist Bank

### ISSUE THREAD

**Issue by LewisLebentz** [AdguardTeam/AdguardFilters#32893]
Please add:

* monzo.com

To the HTTPS Filtering whitelist, they're a bank in the UK so shouldn't have their traffic inspected by AdGuard.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/HttpsExclusions #172](https://github.com/AdguardTeam/HttpsExclusions/issues/172) via [**ZenHub**](https://www.zenhub.com/)
