### ISSUE TITLE
kinozal.me

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3291]
**Description**: Всплывающее окно при нажатии, к примеру, на выделенную на скрине область страницы
http://kinozal.me/

Screenshot:
<details>
![screenshot_42](https://cloud.githubusercontent.com/assets/18548949/19827663/8a315d56-9dba-11e6-8c3d-b36fd124328f.jpg)

</details>

**Filters list**: 1,2,3,4,14,211

**Operating system**: Вин

**Browser**: IE

**Comment by Alex-302** [comment]
Не повторилось.

**Comment by Nemo005** [comment]
При открытии любой ссылки на сайте постоянно перебрасывает на другую страницу:
![default](https://cloud.githubusercontent.com/assets/23156825/19840447/70f4b328-9f0f-11e6-87d5-e106b5427fa3.jpg)

**Comment by Alex-302** [comment]
Added to English filter
```
||mxtads.com:8040
```
