### ISSUE TITLE
gismeteo.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3292]
**Description**: Вверху реклама
https://www.gismeteo.ru/city/hourly/5028/4/

**Expected behaviour**: Tell us what should happen instead

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19827782/5aa1cb5e-9dbd-11e6-9353-4b0f74490cd7.png)

</details>

**Filters list**: 1,2,3,4,14,211

**Operating system**: Вин

**Browser**: Хром

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
gismeteo.ru###rbc > div.rframe
```

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/20112011/375afa38-a5f3-11e6-866e-18b8664efd55.png)

Говорят, на иОС есть снова.

<details>
Application version: 1.1.1.54
Application lifetime: 2016-01-18 16:27:09 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: 240C951D-77AD-4959-86D1-9820BD93DD43

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.99.81 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.81 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.26 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.42.41 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.61 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.64 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.51.81 Enabled=NO
ID=212 Name="RU AdList: Counters" Version=1.0.48.38 Enabled=NO
ID=213 Name="RU AdList: BitBlock" Version=1.0.48.64 Enabled=NO
фильтры обновляли
</details>

1445500

**Comment by Alex-302** [comment]
@evgeniy-ADG 
проверь такие правила:
```
gismeteo.ru##div.fcontent[style="min-height:400px;padding:1px;"]
gismeteo.ru##div.rframe[style="clear: both;min-height:90px;"]
gismeteo.ru##div.fcontent[style="height: 400px;"]
```
