### ISSUE TITLE
123movies.to - clickunder

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3293]
**Description**: go to 123movies.to and click anywhere on the page, another tab opens up

Screenshot: <details>
![screen shot 2016-10-29 at 12 42 11 pm](https://cloud.githubusercontent.com/assets/14153331/19828663/36f63920-9dd5-11e6-8ae4-b40d9e9c218b.png)
</details>

**Filters list**:
<details>
![screen shot 2016-10-29 at 12 43 12 pm](https://cloud.githubusercontent.com/assets/14153331/19828667/450534d0-9dd5-11e6-9c3c-d08cc7c962e8.png)
</details>

**Operating system**: reproduced on Win, iOS and macOS.

Reported in tickets 1439627 and 677335

**Comment by Alex-302** [comment]
Added to English filter
```
||glaswall.online^$third-party
||go.cartstick.com^$third-party
||ficusoid.xyz^$third-party
```
