### ISSUE TITLE
onhax.me

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3294]
**Description**: search box is mistakenly blocked
reported in ticket 1251036

Screenshot: 
<details>
![2016-10-30 12_41_46-allman brown - rivers](https://cloud.githubusercontent.com/assets/14153331/19836045/75a524e6-9e9e-11e6-8324-1d0e861a810f.png)
![2016-10-30 12_40_39-on hax _ tech forever](https://cloud.githubusercontent.com/assets/14153331/19836046/75a63ade-9e9e-11e6-9fe2-4fecde1cba96.png)
</details>

Filters:
<details>
![2016-10-30 12_42_36-filter editor](https://cloud.githubusercontent.com/assets/14153331/19836050/844d48a2-9e9e-11e6-863b-bf2e6832d366.png)

</details>

**Comment by Alex-302** [comment]
Temporary added:
```
onhax.me#@#[class][value]
```
