### ISSUE TITLE
whois.com

### ISSUE THREAD

**Issue by ReporterX** [AdguardTeam/AdguardFilters#32951]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 
Annoying animated ads on main site and search result.

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![screenshot](https://user-images.githubusercontent.com/8235338/56662144-e9e9ed80-66d5-11e9-8cfb-267f55d487e3.jpg)

</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

AdGuard Base
AdGuard Tracking Protection
AdGuard Annoyances
Easylist
EasyPrivacy

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows
Operating system version (Android/iOS) | 7
Browser:                               | Firefox
AdGuard version:                       | 3.0.13
Filters enabled:                       | Yes
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | no
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Hi
Please add to custom filter:
```
whois.com##.promoblurb-container
whois.com##.homepage-product-banner
```
