### ISSUE TITLE
ebookbb.com - Incorrect Blocking

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3295]
## Как должно
![001_10_30_12](https://cloud.githubusercontent.com/assets/16462533/19848360/c9792c90-9f55-11e6-8f4f-57b2ec707ecd.jpg)

## Как с Adguard
![001_10_30_40](https://cloud.githubusercontent.com/assets/16462533/19848379/dc98fdd2-9f55-11e6-869a-d006fd5d12f4.jpg)

## Фильтры на тесте:
Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский

**Comment by Alex-302** [comment]
Added to English filter
```
ebookbb.com##body > a[rel="nofollow"][onclick]
@@||ebookbb.com/wp-content/plugins/wp-minify/min/?f=
```
Added to Annoyances filter
```
ebookbb.com##.special-message-wrapper
```
