### ISSUE TITLE
http://thevideo.me/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3297]
http://thevideo.me/wlho0fcqkmq3

There's no play button. Works fine without ADG.

![image](https://cloud.githubusercontent.com/assets/15856304/19849976/addc9c7a-9f5e-11e6-84b3-9beb4022347f.png)

<details>
Application version: 1.1.1.54
Application lifetime: 2016-10-10 01:47:08 +0000

Device: iPod touch
Platform: iOS
OS: 10.0.2
ID: 6D7D8D71-5F6B-4D99-B346-D6665B621ED2

Locale: en
Region: ca

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.99.3 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.64 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.7 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.57 Enabled=YES

**Comment by Alex-302** [comment]
This site is too slow on my end, can't open it even with VPN.
Could you check it in Safari?

**Comment by Alex-302** [comment]
Loaded, but the video is not working with paused Adguard
<details>
![image](http://imagizer.imageshack.com/img924/7961/fYzTvK.png)
</details>
