### ISSUE TITLE
http://www.sueddeutsche.de/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3298]
It opens this page when the site is loaded: http://www.sueddeutsche.de/adblock

![image](https://cloud.githubusercontent.com/assets/15856304/19850315/8a5bea60-9f60-11e6-8ab5-d8711663ae0f.png)

<details>
Application version: 1.1.1.54
Application lifetime: 2016-10-15 13:50:28 +0000

Device: iPad
Platform: iOS
OS: 10.1
ID: A37486B3-48D0-4215-9455-6D6FA1266F6F

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.98.72 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.48 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.96 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.71 Enabled=YES
ID=6 Name="German filter" Version=1.0.28.1 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.40 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.55 Enabled=YES
ID=101 Name="EasyList" Version=1.0.64.11 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.67.81 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.60.45 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.67.95 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES

**Comment by danidoedel** [comment]
I use this page regularly and I can't reproduce this...

**Comment by evgeniy-ADG** [comment]
I was able to reproduce, all filters are up to date. Te script detects English filter.

**Comment by Alex-302** [comment]
Can't reproduce with German filter.

**Comment by evgeniy-ADG** [comment]
I can, reproduced on Mac, with German filter, all is up to date

**Comment by Alex-302** [comment]
@evgeniy-ADG 
try this, please
```
@@||sueddeutsche.de^$elemhide
```
if it will helps, replace it by this rule and check again 
```
@@||sueddeutsche.de^$generichide
```

**Comment by evgeniy-ADG** [comment]
both don't work.

eng, spyware, social media, annoyances, russian, mobile ads, safari
