### ISSUE TITLE
de.xhamster.com - Annoyance - Ad Leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3299]
**Site**: https://de.xhamster.com/
**Description**: Cookie notice not blocked. Ad leftover on mobile devices.

**Current behaviour**: Site shows a cookie notice at the bottom and has some ad leftover on mobile devices at the top, middle and bottom.

========

This should block the cookie notice (Annoyances filter):
`xhamster.com##.bottom_message`

This should block the ad leftover (Mobile ads filter):
`xhamster.com##.ts`

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.99.9
Spyware filter 1.0.8.65
Social media filter 1.0.14.7
Annoyances filter 1.0.5.81
German filter 1.0.28.6
Mobile ads filter 1.0.5.47
Safari filter 1.0.1.57

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
thanks, added
