### ISSUE TITLE
https://luki.org/ - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3300]
**Site**: https://luki.org/
**Description**: Cookie notice not blocked.

**Current behaviour**: Site shows a cookie notice at the bottom.

<details>
<summary>Screenshot</summary>
![image](https://cloud.githubusercontent.com/assets/10995998/19851194/ed65961e-9f5c-11e6-8429-1dd503e60322.png)
</details>

========

This should block the cookie notice:
`luki.org##.eu-law-container`

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.99.9
Spyware filter 1.0.8.65
Social media filter 1.0.14.7
Annoyances filter 1.0.5.81
German filter 1.0.28.6
Mobile ads filter 1.0.5.47
Safari filter 1.0.1.57

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added
