### ISSUE TITLE
eraffe24.de - Mobile - Ad Leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3301]
**Site**: https://www.eraffe24.de/
**Description**: Smartbanner not blocked on mobile devices. And some ad leftover (not only on mobile devices).

**Current behaviour**: Site shows a smartbanner at the bottom. Ad leftover is marked in the screenshot as well.

<details>
<summary>Screenshot</summary>
![image](https://cloud.githubusercontent.com/assets/10995998/19851966/d7f9a78a-9f60-11e6-9cb0-6d233deaadbd.png)
</details>

========

This should block the smartbanner:
`eraffe24.de##.smartbanner`

Don't know how to handle the ad leftover though...

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.99.9
Spyware filter 1.0.8.65
Social media filter 1.0.14.7
Annoyances filter 1.0.5.81
German filter 1.0.28.6
Mobile ads filter 1.0.5.47
Safari filter 1.0.1.57

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
> eraffe24.de##.smartbanner

added


> Don't know how to handle the ad leftover though...

With theid design - nohow.
