### ISSUE TITLE
dasoertliche.de -  Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3306]
**Site**: http://www.dasoertliche.de/
**Description**: Site detects adblocker.

**Current behaviour**: Site shows a adblock notice after you searched for something, e.g.  http://www.dasoertliche.de/Themen/Orthop%C3%A4dietechnik/berlin.html.

<details>
<summary>Screenshot</summary>
![image](https://cloud.githubusercontent.com/assets/10995998/19854038/1cfb1718-9f6d-11e6-8150-3ed8ff0c6d8b.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.99.10
Spyware filter 1.0.8.65
Social media filter 1.0.14.7
Annoyances filter 1.0.5.82
German filter 1.0.28.6
Mobile ads filter 1.0.5.47
Safari filter 1.0.1.57

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Do you mean this?
<details>
![image](http://imagizer.imageshack.com/img922/458/cZn77q.png)
</details>

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
dasoertliche.de###banner-right
```

**Comment by danidoedel** [comment]
Yes exactly. Thank you!
