### ISSUE TITLE
schuhmuecke.de - Ad Leftover/Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3311]
**Site**: http://www.schuhmuecke.de/
**Description**: Site shows some empty white box (ad leftover?).

**Current behaviour**: Site shows some empty white box.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/19854459/5a3c62e2-9f6f-11e6-83d2-e1ab2b7770f9.png)

</details>

========

**Expected behaviour**: Box should be blocked.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/19854489/8196028a-9f6f-11e6-9f3b-d9300db5f005.png)

</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.99.10
Spyware filter 1.0.8.65
Social media filter 1.0.14.7
Annoyances filter 1.0.5.82
German filter 1.0.28.6
Mobile ads filter 1.0.5.47
Safari filter 1.0.1.57

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Can't open screenshots.
I see popup.
Added
```
schuhmuecke.de##div.monoOverlay
schuhmuecke.de##.monoOverlayContent
```

**Comment by danidoedel** [comment]
Updated the screenshots above.
It's fixed now! Thank you.
