### ISSUE TITLE
kleiderkreisel.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3312]
**Site**: https://www.kleiderkreisel.de/
**Description**: Cookie notice not blocked.

**Current behaviour**: Site shows a cookie notice at the top.

<details>
<summary>Screenshot</summary>
![image](https://cloud.githubusercontent.com/assets/10995998/19854596/1aee9bea-9f70-11e6-9052-a13763fd51cc.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.99.10
Spyware filter 1.0.8.65
Social media filter 1.0.14.7
Annoyances filter 1.0.5.82
German filter 1.0.28.6
Mobile ads filter 1.0.5.47
Safari filter 1.0.1.57

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Fixed
