### ISSUE TITLE
gazetaonline.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#33134]
`https://www.gazetaonline.com.br/`

Sponsored "articles": `.cat-conteudo_patrocinado`

![patrocinado](https://user-images.githubusercontent.com/35470489/56856422-4a746700-6930-11e9-841b-68ec19ef9e28.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.16
Firefox 66

**Comment by Alex-302** [comment]
Not sure about blocking.

**Comment by adranger** [comment]
@Alex-302 They are the same kind of ads as these ads you've blocked on other news sites:

https://github.com/AdguardTeam/AdguardFilters/issues/21659
https://github.com/AdguardTeam/AdguardFilters/issues/29486
