### ISSUE TITLE
de.pinterest.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3313]
**Site**: https://de.pinterest.com/
**Description**: Cookie notice not blocked.

**Current behaviour**: Site shows a cookie notice at the top.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/19854675/8da928b2-9f70-11e6-9a64-563cce9ac5b5.png)

</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.99.11
Spyware filter 1.0.8.65
Social media filter 1.0.14.7
Annoyances filter 1.0.5.82
German filter 1.0.28.6
Mobile ads filter 1.0.5.48
Safari filter 1.0.1.57

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Not shown. Please show html code of this element.

**Comment by danidoedel** [comment]
I updated the screenshot above.
It's blocked after recent filter update. Or maybe they have different cookie messages... 
Anyway I don't see it anymore :)
