### ISSUE TITLE
https://13tv.co.il - Popup

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#33131]
***Description***:
Hi
have popup in site
https://13tv.co.il/
* **Current behaviour**: 
http://prntscr.com/ngy68r

***Steps to reproduce the problem***:
open the site:
It happens when click in link on the site:
https://13tv.co.il/
Information | Value
-- | --
Operating system: | win 10
Browser: | Google Chrome
AdGuard version: |6.4.1814.4903

Filters enabled:  
EasyList Hebrew,
EasyPrivacy,
AdGuard Annoyances,
AdGuard Base,
Adblock Warning Removal List

AdGuard DNS:  None
Stealth mode options (Windows only): not enabled

**Comment by BlazDT** [comment]
Not reproduced, please check @AdamWr

**Comment by AdamWr** [comment]
@MrTal Could you please check this rule:
`13tv.co.il#%#document.cookie = "r13_maavron=5; path=/";`

**Comment by MrTal** [comment]
@AdamWr 
still have popup:
http://prntscr.com/ni6pwi

**Comment by AdamWr** [comment]
>https://13news.co.il/news/additional/commentaries/

It's a different website.
Please remove previous rule and check this:
`13news.co.il,13tv.co.il#%#document.cookie = "r13_maavron=5; path=/";`

**Comment by MrTal** [comment]
@AdamWr 
yes this work
tank you!

**Comment by AdamWr** [comment]
Added.
Thank you for your reply.
