### ISSUE TITLE
deezer.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3314]
**Site**: https://www.deezer.com/
**Description**: Cookie notice not blocked.

**Current behaviour**: Site shows a cookie notice at the top.

<details>
<summary>Screenshot</summary>

![deezer](https://cloud.githubusercontent.com/assets/10995998/19945881/556f9174-a142-11e6-882c-260fd8c5896e.png)

</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.99.11
Spyware filter 1.0.8.65
Social media filter 1.0.14.7
Annoyances filter 1.0.5.82
German filter 1.0.28.6
Mobile ads filter 1.0.5.48
Safari filter 1.0.1.57

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Can't login here. Screenshot url is not valid.

**Comment by danidoedel** [comment]
@Alex-302 Updated the screenshot above and here is the html code for the element:

![deezer2](https://cloud.githubusercontent.com/assets/10995998/19945949/a7f3b722-a142-11e6-87ee-a32df76771e8.png)

**Comment by Alex-302** [comment]
Check this rule:
```
###cookies_banner:not(body):not(html)
```

**Comment by danidoedel** [comment]
@Alex-302 Yes this works!

**Comment by Alex-302** [comment]
Added.
