### ISSUE TITLE
justwatch.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3315]
**Site**: https://www.justwatch.com/de
**Description**: Site shows a mobile promo banner at the top.

<details>
<summary>Screenshot</summary>
![image](https://cloud.githubusercontent.com/assets/10995998/19855385/90a4cb12-9f74-11e6-8b4c-8a5a1712c24e.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.99.11
Spyware filter 1.0.8.65
Social media filter 1.0.14.7
Annoyances filter 1.0.5.82
German filter 1.0.28.6
Mobile ads filter 1.0.5.48
Safari filter 1.0.1.57

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
justwatch.com#%#AG_onLoad(function() { setTimeout(function() { document.body.className = document.body.className.replace("promotion","."); console.log('dasd'); },1500); });
```
