### ISSUE TITLE
ferrari.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3317]
**Site**: http://www.ferrari.com/de_de/
**Description**: Cookie notice not blocked.

**Current behaviour**: Site shows a cookie notice at the top.

<details>
<summary>Screenshot</summary>
![image](https://cloud.githubusercontent.com/assets/10995998/19855517/52ef8c20-9f75-11e6-9ea2-8d57686cd85e.png)
</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.99.11
Spyware filter 1.0.8.65
Social media filter 1.0.14.7
Annoyances filter 1.0.5.82
German filter 1.0.28.6
Mobile ads filter 1.0.5.48
Safari filter 1.0.1.57

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
fixed
