### ISSUE TITLE
Adguard Detected before video loads

### ISSUE THREAD

**Issue by vivshah56** [AdguardTeam/AdguardFilters#33179]
***Description***:
* **Current behaviour**: 

The following website detects the presence of Adguard :
https://einthusan.tv/
<img width="652" alt="Screen Shot 2019-04-28 at 12 40 17 PM" src="https://user-images.githubusercontent.com/39109924/56869243-eba40180-69b2-11e9-956b-a0ba7933619d.png">

* **Expected behaviour**: 

The video should load without detecting Adguard

***Steps to reproduce the problem***:
1. Open https://einthusan.tv/intro/
2. Click HINDI
3. Click Movies
4. Click on any movie
5. Wait for sometime. You will see messages like "pinging available sources", "Loading source". Wait few minutes - it takes time to load. If it's not loading, reload the page or follow steps 1-4 again.
6. Before the video can load, it displays Adblock detected message

***System configuration***
Google Chrome : Version 73.0.3683.103
Operating System : WIndows 10

**Filters:**
Adguard Base Filter : Updated April 28 12.30PM

User Filters : 
||vid.springserve.com/vast/*einthusan.tv$empty,important,badfilter
@@||einthusan.tv^$urlblock

Screenshots showing blocked elements : 
<img width="1219" alt="Screen Shot 2019-04-28 at 12 40 05 PM" src="https://user-images.githubusercontent.com/39109924/56869314-15a9f380-69b4-11e9-8490-2e6d29f62992.png">

**Comment by BlazDT** [comment]
Thank you for the report, fixed, update is available in about 3 hours.
