### ISSUE TITLE
allthatsinteresting.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#33171]
`https://allthatsinteresting.com`

Overlay annoyance.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.16
Firefox 66

**Comment by adranger** [comment]
@BlazDT It appears when you move your mouse cursor to another tab.

![overlay](https://user-images.githubusercontent.com/35470489/56965850-7ceeb180-6b34-11e9-8904-fdcaa27f4d1f.png)

**Comment by BlazDT** [comment]
Thank you, fixed along some left-overs.
