### ISSUE TITLE
Not blocking Pop Up & Vibrating Ads

### ISSUE THREAD

**Issue by jerryn70** [AdguardTeam/AdguardFilters#3320]
Is there any way to block pop up ads and vibrating ads? I mean when i try to download files from some sites my phone starts vibrating and a pop up will come like saying your phone is in danger or phn got virus scan now/install antivirus or maybe install this app to remove virus from your phone, click here to download games and movies etc like pop up and vibrations. 

●Adguard version : 2.7.220
●Operating system : Android Marshmallow 6.0.1

●Below i listed some of that kind of sites●

https://dropapk.com/munh0ciu8h89

http://ul.to/9mfxlw6x

https://dailyuploads.net/ifsksrv94c1r

https://filescdn.com/fwy5vrgsysq7

https://uplod.ws/ny5w868j53k7

https://userscloud.com/7ww5ltgaf6kt

http://hugefiles.net/4o2sy9b5gxnx

**Comment by Alex-302** [comment]
1,2,4,7 - not reproduced
5
Added to Mobile filter
```
||ongkidcasarv.com^
||puhtml.com^
||buzzonclick.com^
||poptm.com^
||javacript.gq^
||r7mediar.com^$popup
||hormebets.info^$popup
||campaigns.apps-connects.com^$popup
```
6
```
||clkfeed.com^$popup
||campaigns.apps-connects.com^$popup
||d2nrdy2pg3k168.cloudfront.net^
```
