### ISSUE TITLE
yummyanime.com

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3321]
**Description**: ads on yummyanime.com

Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/14153331/19855438/3d857572-9f7d-11e6-9109-35f20119f87c.png)
</details>

**Adguard version**: 1.1.1.54

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.99.6 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.64 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.7 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.42.5 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.57 Enabled=YES

**Operating system**: iOS 10.1

Reported in ticket 1440401

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
yummyanime.com##body > div.top > a[rel="nofollow"]
||yummyanime.com/img/ignore/sprit/dragon.jpg
```
