### ISSUE TITLE
pg21.ru - ads

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3323]
## Реклама на сайте
![2016-10-31_20-29-39](https://cloud.githubusercontent.com/assets/16462533/19866618/85755dbc-9fa9-11e6-901f-ecae3e6f2724.png)
## Фильтры при тесте
> Пользовательский
> Английский
> Фильтр счетчиков и систем аналитики
> Экспериментальный
> Фильтр раздражителей
> Русский

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||pg21.ru/userfiles/b/
pg21.ru##div[class^="Banner"]
```
