### ISSUE TITLE
smotret-porno-besplatno.ru - Ads

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3324]
## Ссылка предоставленная пользователем: 
http://smotret-porno-besplatno.ru/cat-48-dagestanskoe.html
## Фильтры теста:
> **Пользовательский
> Английский
> Фильтр счетчиков и систем аналитики
> Экспериментальный
> Фильтр раздражителей
> Русский**

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||code.vh45130.eurodir.ru^
```
