### ISSUE TITLE
mail.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3325]
У меня на айпеде повторилось. 
![img_0925](https://cloud.githubusercontent.com/assets/15856304/19884093/ae6aade0-a020-11e6-9e7c-53977fbce613.png)

<details>
Application version: 1.1.2.24
Application lifetime: 2016-10-16 20:31:40 +0000

Device: iPad
Platform: iOS
OS: 10.0.2
ID: 897B8DB0-FE31-4DD6-AF70-6AEAC8E159E4

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.97.94 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.62 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.6 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.78 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.42.2 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.47 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.57 Enabled=YES

**Comment by Alex-302** [comment]
У меня только макось есть, в Сафари чисто.
@gshumihin можешь на айфоне проверить?

**Comment by gshumihin** [comment]
У меня не повторилось ни на обычной версии, ни на прошке.
Смотрел через сафари.

**Comment by evgeniy-ADG** [comment]
https://mail.ru/

![image1 1](https://cloud.githubusercontent.com/assets/15856304/24952718/28c3ae5e-1f81-11e7-9344-76a2583a64e4.PNG)

Не повторяется, естественно.

1. OS: 10.3.1
2. Adguard 1.1.5.40
3. Optimized enabled: YES
5. Filters subscriptions:

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.14.5 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.11.34 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.18.47 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.11.64 Enabled=YES
- ID=10 Name="Filter unblocking useful ads" Version=1.0.1.3 Enabled=NO
- ID=1 Name="Russian filter" Version=1.0.49.50 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.2.84 Enabled=YES

**Comment by Alex-302** [comment]
> OS: 10.3.1

бета же, там сокрытие частично сломано. Пусть 10.3.2 пробует. В ней и VPN починили.
