### ISSUE TITLE
http://www.maniac.de/ - anti-adblock script

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3326]
http://www.maniac.de/

![image](https://cloud.githubusercontent.com/assets/15856304/19884387/3a28125e-a022-11e6-8f92-02611a632ba2.jpg)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/19884394/48047c64-a022-11e6-80bb-1f1f598972f9.png)

**Comment by Alex-302** [comment]
Added:
```
||tracking.bdi-services.de^
maniac.de##div[id="Dingdong"][style^="z-index:"]
maniac.de#%#(function() { var w_open = window.open, regex = /maniadrd.php/; window.open = function(a, b) { if (typeof a !== 'string' || !regex.test(a)) { w_open(a, b); } }; })();
```

**Comment by vmalyuta** [comment]
http://prnt.sc/f0h4yq
ticket id 1441210

**Comment by Alex-302** [comment]
German filter fixes it.
