### ISSUE TITLE
http://vidzi.tv/ - pop-ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3327]
http://vidzi.tv/nxmfu6h370ph.html

![image](https://cloud.githubusercontent.com/assets/15856304/19887175/a1dc303a-a02f-11e6-8321-bf5c6321afc3.png)

<details>
Os version: Microsoft Windows NT 6.3.9600.0
Dot .net version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: 9f9fb156cad34fc298232521b91cb01d
Language: en
AppVersion: 6.1.258.1302
Main settings: 
Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:8 Name: Dutch filter Url: http://adguard.com/ru/filter-rules.html?id=8
FilterId:9 Name: Spanish/Portuguese filter Url: http://adguard.com/ru/filter-rules.html?id=9
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:101 Name: EasyList Url: https://easylist.github.io/easylist/easylist.txt
FilterId:116 Name: Wiltteri Url: https://raw.githubusercontent.com/wiltteri/wiltteri.txt/master/wiltteri.txt
FilterId:122 Name: Fanboy's Annoyances Url: https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
FilterId:207 Name: Adblock Warning Removal List Url: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
FilterId:211 Name: Anti-Adblock Killer | Reek Url: https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
FilterId:214 Name: ABPVN List Url: http://abpvn.com/filter/abpvn-53fde4f714c78.txt
FilterId:216 Name: Adblock polskie reguły Url: https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt
FilterId:0 Name: User filter Url: no_url
FilterId:14 Name: Annoyances filter Url: http://adguard.com/ru/filter-rules.html?id=14
Filtering Mode: Driver
Driver Type: Wfp
Ads Blocked: 76250, Trackers Blocked: 1328
Filtering Mode: Driver
Application lifetime: 94.05:42:14.0795228
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "BlockBrowserPushApi": true,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": true,
  "HideUserAgent": true,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": true,
  "CustomIp": "209.141.53.254"
}

**Comment by Alex-302** [comment]
Fixed.
Could you block that domain on screenshot as malicious?
