### ISSUE TITLE
radio.sport5.co.il

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#33277]
***Description***:
Hi
cant see video with adgurd in site:
http://radio.sport5.co.il/

* **Current behaviour**: 
http://prntscr.com/nj0xve

* **Expected behaviour**: 
http://prntscr.com/nj0xqp

***Steps to reproduce the problem***:
open the site:
http://radio.sport5.co.il/

Information | Value
-- | --
Operating system: | win 10
Browser: | Google Chrome
AdGuard version: |6.4.1814.4903

Filters enabled:  
EasyList Hebrew,
EasyPrivacy,
AdGuard Annoyances,
AdGuard Base,
Adblock Warning Removal List

AdGuard DNS:  None
Stealth mode options (Windows only): not enabled

**Comment by AdamWr** [comment]
It seems that it's caused by `EasyPrivacy`, so please add this rule to user filter:
`@@||radio.sport5.co.il/js/angulartics-google-analytics.js`

Reproted here - https://github.com/easylist/easylist/issues/3357
