### ISSUE TITLE
free-rutor.org

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3328]
ID 1315777 
**Description**: 
> Когда я прикасаюсь пальцем в любом месте на стартовой странице free-rutor.org, тогда открываются посторонние сайты... и открывается приложение PlayMarket (AliExpress, Dragon Soul).

Лог 
[debug (1).txt](https://github.com/AdguardTeam/AdguardFilters/files/564320/debug.1.txt)
Проблема проявилась в 19:07 (НСК)

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19894362/68d3d934-a055-11e6-9496-17bb30d33016.png)
![image](https://cloud.githubusercontent.com/assets/18548949/19894365/6c1b135a-a055-11e6-998e-df9598571fbd.png)

</details>

**Adguard version**: 2.7.220

**Filters list**: 2, 3, 4, 14, 1, 11, 211
"filteringQuality" : "FULL",

**Operating system**: Андроид

**Browser**: Встроенный

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Исправил.
