### ISSUE TITLE
https://www.baidu.com/ - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3329]
it’s a popular search engine in China just like google. when you enter the website and type Chinese word “天气” in the search box, which means “weather” in English, then click the search button “百度一下”,  then the website will show you the weather in your location. I don’t know if it works in abroad

<details>

![image1](https://cloud.githubusercontent.com/assets/15856304/19922184/36377da6-a0ea-11e6-987f-54a9958f8b77.png)

![image2](https://cloud.githubusercontent.com/assets/15856304/19922166/191a7eee-a0ea-11e6-87e4-1873afbb46b6.png)

</details>

I found out the problem, the filter "EasyList China" caused the problem.

**Comment by Alex-302** [comment]
Can't reproduce.
Try this rules separately:
```
@@||baidu.com^$elemhide
```
```
@@||baidu.com^$urlblock
```
