### ISSUE TITLE
https://www.google.com/edu/cs/explore.html - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3330]
https://www.google.com/edu/cs/explore.html

The first one is with adguard enabled.
The second image with selections is with adguard disabled.

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/19923264/40f6d30e-a0ef-11e6-86c6-1a6e75a80c8f.png)

![image-1](https://cloud.githubusercontent.com/assets/15856304/19923266/42b20d26-a0ef-11e6-8bf2-61d35fa6aa50.png)

</details>

state<details>
Application version: 1.1.1.54
Application lifetime: 2016-10-01 21:09:06 +0000

Device: iPhone
Platform: iOS
OS: 10.1
ID: 9FEC680E-C63A-43D8-9659-9C79C2699617

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.99.13 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.65 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.9 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.57 Enabled=YES

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||ssl.google-analytics.com/ga.js$domain=google.ae|google.at|google.be|google.by|google.ca|google.ch|google.cl|google.cn|google.co.id|google.co.in|google.co.jp|google.co.th|google.co.uk|google.co.ve|google.co.za|google.com|google.com.ar|google.com.au|google.com.bd|google.com.br|google.com.co|google.com.eg|google.com.hk|google.com.mx|google.com.my|google.com.ng|google.com.pe|google.com.ph|google.com.pk|google.com.sa|google.com.sg|google.com.tr|google.com.tw|google.com.ua|google.com.vn|google.de|google.dk|google.ee|google.es|google.fr|google.gr|google.hu|google.ie|google.it|google.nl|google.no|google.pl|google.pt|google.ro|google.rs|google.ru|google.se|google.sk|google.tn
```
