### ISSUE TITLE
http://www.hotukdeals.com/ - pop-ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3331]
http://www.hotukdeals.com/gaming/deals/hot?page=2

>When on hotukdeals.com (a website for deals and offers) anytime I click one of the deal links to take me to the external site Adguard blocks the third party link. 

<details>
Application version: 1.1.2.24
Application lifetime: 2016-11-01 14:49:42 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: F0223BCB-5A5C-4981-89EE-38525CFBE1BA

Locale: en
Region: gb

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.99.25 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.67 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.16 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.58 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.68.26 Enabled=YES

![file_000](https://cloud.githubusercontent.com/assets/15856304/19923553/a2c123ea-a0f0-11e6-81b3-9b0209ede03a.png)

**Comment by Alex-302** [comment]
Not reproduce.
`Optimazed enabled: NO`
Try with optimized filters.

**Comment by evgeniy-ADG** [comment]
Reproducible on a real device, I have toggled 'Use simplified rules' and it has not changed anything, the empty page still pops up.

**Comment by Alex-302** [comment]
I need en example link. Tried few, but they are was not blocked.

**Comment by Alex-302** [comment]
For the link from screenshont try:
```
@@||awin1.com^$domain=hotukdeals.com
```
