### ISSUE TITLE
http://m.mangafox.me/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3332]
Screenshot 1: the homepage/main page section has a large banner that used to be blocked by default (circled)
Screenshot 2: if you pick any series to read and actually flip through some pages, you'll find some ads occasionally pop up at the bottom (see circled area)
Screenshot 3: if you pick any series to read and look at the chapters available, you may also see a banner appear near the top

<details>

![image1 1](https://cloud.githubusercontent.com/assets/15856304/19923779/be1eb7dc-a0f1-11e6-8361-00c3bab060a8.png)

![image2 1](https://cloud.githubusercontent.com/assets/15856304/19923783/c10f637e-a0f1-11e6-9d00-00c99d1164be.png)

![image3](https://cloud.githubusercontent.com/assets/15856304/19923787/c342d4f0-a0f1-11e6-813f-f30bffce1b2d.png)

</details>
State
<details>
Application version: 1.1.1.54
Application lifetime: 2016-03-25 03:30:41 +0000

Device: iPad
Platform: iOS
OS: 10.1.1
ID: E3F82948-A2F2-4585-A91D-A45259411824

Locale: en
Region: ca

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.99.16 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.66 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.11 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.5.52 Enabled=YES
ID=12 Name="Safari Filter" Version=1.0.1.57 Enabled=YES
ID=101 Name="EasyList" Version=1.0.54.94 Enabled=NO
ID=118 Name="EasyPrivacy" Version=1.0.68.20 Enabled=YES
ID=204 Name="Peter Lowe's list" Version=1.0.2.45 Enabled=YES

**Comment by Alex-302** [comment]
Added to Mobile filter
```
mangafox.me##.adv-here
mangafox.me##.mobile-banner
```
Added to English filter
```
mangafox.me###content > div#spotlights
mangafox.me##div[id^="mfad"]
||mfcdn.net/store/mfbanners/$domain=mangafox.me
```
