### ISSUE TITLE
doridro.com

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3333]
**Description**:
The website isn't loading and requires disabling adblock. 
http://doridro.com/forum/ucp.php?mode=register

Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/17504743/19924991/d1cdd6aa-a0f6-11e6-80f8-1d5ba5ea7873.png)
</details>

**Adguard version**: 1.1.2.24

**Filters list**: 
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.99.27 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.68 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.16 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.59 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.68.41 Enabled=YES

**Operating system**: iOS

Tested on desktop Safari. 
Customer 1442619.

**Comment by Alex-302** [comment]
Added to English filter
```
@@||doridro.com$generichide
```

**Comment by Bohdan-SUP** [comment]
@Alex-302 Still happens on iOS, reproducible with Safari 10 + useragent + extension.

**Comment by Alex-302** [comment]
Check this:
```
@@||doridro.com^$elemhide
```
and maybe
```
@@||doridro.com/forum/styles/FLATBOOTS/theme/images/logo.png
```

**Comment by Bohdan-SUP** [comment]
The second one helped me:
``@@||doridro.com/forum/styles/FLATBOOTS/theme/images/logo.png``

**Comment by Alex-302** [comment]
ok.

**Comment by iverkhohliad** [comment]
situation repeats
https://github.com/AdguardTeam/AdguardFilters/issues/8833
