### ISSUE TITLE
http://www.zdfans.com/ - Assistant doesn't show up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3334]
I can't provide a screenshot (will update later) but I was able to reproduce it. Works fine on Mac, misses on Win.

<details>
Os version: Microsoft Windows NT 10.0.14393.0
Dot .net version: 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: 29b7dbf2de094a30a9404474146a974a
Language: zh
AppVersion: 6.1.258.1302
Main settings: 
Subscriptions: FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:101 Name: EasyList Url: https://easylist.github.io/easylist/easylist.txt
FilterId:104 Name: EasyList China Url: https://easylist-downloads.adblockplus.org/easylistchina.txt
FilterId:220 Name: CJX's Annoyance List Url: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Tdi
Ads Blocked: 2743, Trackers Blocked: 629
Filtering Mode: Driver
Application lifetime: 13.11:01:23.1848808
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"
}

**Comment by Alex-302** [comment]
Не открывается. Проверь в винде, есть ли в коде страницы `injected by Adguard`

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/19964594/46625412-a1cb-11e6-8fe0-80cbf6b29f37.png)

вроде да, асистента нет.

**Comment by Alex-302** [comment]
Всё заинжекчено. У тебя конец выделен.
Сделай скрин консоли с загруженной страницей.
Если сайт не в исключениях, то лучше в виндовую репу написать, правилами не исправить.
