### ISSUE TITLE
https://nl.express.live/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3335]
https://nl.express.live/2016/10/28/115545algoritmes-merkel-vrijgave/

![image](https://cloud.githubusercontent.com/assets/15856304/19925472/c62e3d24-a0f8-11e6-9f25-1c29bcfd1c88.png)

<details>
{
  "advancedPreferences" : {
  },
  "androidVersion" : "7.0 (sdk=24)",
  "appLanguage" : "en",
  "applicationId" : "f348f0aae73c4f67",
  "autoStartEnabled" : true,
  "browsingSecurityEnabled" : true,
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "Huawei Nexus 6P",
  "deviceSpeedRank" : 57,
  "dnsFilteringEnabled" : false,
  "enabledFilterIds" : [ 2, 3, 4, 10, 11 ],
  "environment" : "release",
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "iconType" : "DEFAULT",
  "installedPackages" : [ "com.android.cts.priv.ctsshim;version=7.0-2996264;system=true", "com.google.android.youtube;version=11.41.56;system=true", "mobi.inthepocket.fostplus.recyclage;version=1.3.2.130;system=false", "com.google.android.ext.services;version=1;system=true", "be.belgacom.hello;version=3.5.0;system=false", "com.android.providers.telephony;version=7.0;system=true", "me.autodialog.myopel;version=2.0.1;system=false", "com.android.sdm.plugins.connmo;version=1.0;system=true", "com.google.android.googlequicksearchbox;version=6.6.21.21.arm64;system=true", "com.mobilityware.spider;version=3.4.0.125;system=false", "com.android.providers.calendar;version=7.0;system=true", "com.android.providers.media;version=7.0;system=true", "com.huawei.entitlement;version=1.0;system=true", "com.google.android.apps.docs.editors.docs;version=1.6.412.11.40;system=false", "com.google.android.onetimeinitializer;version=7.0;system=true", "com.google.android.ext.shared;version=1;system=true", "com.android.wallpapercropper;version=7.0;system=true", "com.quicinc.cne.CNEService;version=7.0;system=true", "com.android.documentsui;version=7.0;system=true", "com.twipemobile.metn;version=3.1.4;system=false", "com.android.externalstorage;version=7.0;system=true", "com.google.android.apps.enterprise.dmagent;version=7.10;system=true", "com.vaillant.android.mobildialog3;version=1.3.0;system=false", "com.android.htmlviewer;version=7.0;system=true", "com.huawei.callstatisticsutils;version=7.0;system=true", "com.google.android.apps.cultural;version=4.0.3;system=false", "com.android.mms.service;version=7.0;system=true", "com.google.android.apps.docs.editors.sheets;version=1.6.412.09.40;system=false", "org.kman.WifiManager;version=3.6.0.5;system=false", "com.android.providers.downloads;version=7.0;system=true", "com.google.android.apps.enterprise.cpanel;version=2016062304;system=false", "com.google.android.apps.messaging;version=1.8.528 (2959790-49.phone);system=true", "android.autoinstalls.config.google.nexus;version=1000;system=true", "com.google.android.apps.genie.geniewidget;version=2.8.5 (136063537);system=false", "com.appventions.atlasfree;version=1.9;system=false", "com.smsBlocker;version=8.0.22;system=false", "com.google.android.configupdater;version=7.0;system=true", "com.android.defcontainer;version=7.0;system=true", "MyING.be;version=8.1.1;system=false", "org.zwanoo.android.speedtest;version=3.2.26;system=false", "com.android.providers.downloads.ui;version=7.0;system=true", "com.android.vending;version=7.0.17.H-all [0];system=true", "com.android.pacprocessor;version=7.0;system=true", "com.asus.filemanager;version=2.0.0.320_160912-4;system=false", "com.android.certinstaller;version=7.0;system=true", "com.android.carrierconfig;version=1.0.0;system=true", "com.google.android.marvin.talkback;version=5.0.4;system=true", "android;version=7.0;system=true", "com.android.hotwordenrollment;version=7.0;system=true", "com.google.android.apps.inputmethod.hindi;version=3.2.0.125756904-preload-arm64-v8a;system=true", "com.android.egg;version=1.0;system=true", "com.android.mtp;version=7.0;system=true", "com.android.nfc;version=7.0;system=true", "com.android.stk;version=7.0;system=true", "com.brother.printservice;version=1.2.0;system=false", "com.android.backupconfirm;version=7.0;system=true", "com.nmbs;version=7.0;system=false", "com.google.android.launcher;version=1.4.large;system=true", "com.google.android.deskclock;version=4.6.1 (3299599);system=true", "com.pinterest;version=6.3.0;system=false", "com.zappotvapple;version=0.92.7171App;system=false", "com.asustek.aicloud;version=2.1.0.0.70;system=false", "org.codeaurora.ims;version=1.0;system=true", "com.android.statementservice;version=1.0;system=true", "com.google.android.carrierentitlement;version=7.0;system=true", "com.google.android.gm;version=6.10.9.136347105.release;system=true", "com.melodis.midomiMusicIdentifier.freemium;version=7.1.4;system=false", "com.android.sdm.plugins.sprintdm;version=1.0;system=true", "com.google.android.setupwizard;version=224;system=true", "com.qualcomm.qcrilmsgtunnel;version=7.0;system=true", "com.android.providers.settings;version=7.0;system=true", "com.android.sharedstoragebackup;version=7.0;system=true", "com.google.android.music;version=6.10.3050BN.2965801;system=true", "com.android.printspooler;version=7.0;system=true", "radiotime.player;version=16.6;system=false", "com.android.sdm.plugins.diagmon;version=7.0;system=true", "com.android.dreams.basic;version=7.0;system=true", "mobi.inthepocket.mediafin.detijd;version=3.5.1;system=false", "com.android.inputdevices;version=7.0;system=true", "com.google.android.dialer;version=4.1.134720488;system=true", "com.adguard.android;version=2.7.220;system=false", "com.dropbox.android;version=20.2.2;system=false", "be.belgacom.mobile.adeleeverywhere;version=2.2.3;system=false", "com.google.android.apps.cloudprint;version=1.36b;system=true", "com.android.musicfx;version=1.4;system=true", "com.google.android.apps.docs;version=2.4.382.19.40;system=true", "com.google.android.apps.maps;version=9.39.2;system=true", "com.tunnelbear.android;version=v135;system=false", "com.android.cellbroadcastreceiver;version=7.0;system=true", "com.google.android.webview;version=51.0.2704.90;system=true", "com.google.android.contacts;version=1.5.16;system=true", "com.android.server.telecom;version=7.0;system=true", "com.google.android.syncadapters.contacts;version=7.0;system=true", "com.android.facelock;version=7.0;system=true", "com.android.keychain;version=7.0;system=true", "com.google.android.gm.exchange;version=6.4.123892212.release;system=false", "com.google.android.calculator;version=7.1.1 (3300836);system=true", "com.android.chrome;version=54.0.2840.68;system=true", "tw.mobileapp.qrcode.banner;version=1.6.5;system=false", "com.google.android.packageinstaller;version=7.0;system=true", "com.google.android.gms;version=9.8.77 (440-135396225);system=true", "com.google.android.gsf;version=7.0;system=true", "com.google.android.tag;version=1.1;system=true", "com.google.android.tts;version=3.9.16;system=true", "com.google.android.apps.walletnfcrel;version=1.0.103778191;system=true", "com.android.calllogbackup;version=7.0;system=true", "com.google.android.partnersetup;version=7.0;system=true", "com.google.android.videos;version=3.19.11;system=true", "com.android.proxyhandler;version=7.0;system=true", "com.adelinolobao.belgiekranten;version=4.5;system=false", "com.tripadvisor.tripadvisor;version=18.0;system=false", "org.videolan.vlc;version=2.0.6;system=false", "com.google.android.feedback;version=7.0;system=true", "com.google.android.printservice.recommendation;version=1.0.0;system=true", "com.google.android.apps.photos;version=2.3.0.137311865;system=true", "com.google.android.calendar;version=5.6-133922642-release;system=true", "com.android.managedprovisioning;version=7.0;system=true", "com.eurostar.androidapp;version=5.0.0;system=false", "com.android.sdm.plugins.dcmo;version=7.0;system=true", "com.google.android.apps.unveil;version=1.9.4;system=false", "com.android.providers.partnerbookmarks;version=7.0;system=true", "com.google.android.gsf.login;version=7.0;system=true", "com.android.wallpaper.livepicker;version=7.0;system=true", "com.belgacom.fon;version=3.3.9;system=false", "com.huawei.mmitest;version=7.0;system=true", "be.belgacom.mobile.tveverywhere;version=5.2.7;system=false", "com.google.android.inputmethod.korean;version=1.5.0.125756861-preload-arm64-v8a;system=true", "com.google.android.apps.translate;version=5.5.0.RC04.137189260;system=false", "com.adobe.reader;version=16.3.1;system=false", "com.google.android.backuptransport;version=7.0;system=true", "com.themobilecompany.delijn;version=3.1.4;system=false", "com.android.bookmarkprovider;version=7.0;system=true", "com.android.settings;version=7.0;system=true", "com.google.android.inputmethod.pinyin;version=4.3.0.125756775-preload-arm64-v8a;system=true", "com.google.android.setupwizard.overlay.smartdevice;version=1.0;system=true", "com.google.android.apps.tycho;version=I.2.3.34-xxhdpi (2943463);system=true", "com.android.omadm.service;version=1.0.0;system=true", "tv.pluto.android;version=2.4.13;system=false", "com.android.cts.ctsshim;version=7.0-2996264;system=true", "com.huawei.sarcontrolservice;version=1.0;system=true", "com.booking;version=11.3.1;system=false", "com.android.vpndialogs;version=7.0;system=true", "com.google.android.keep;version=3.3.431.0;system=false", "com.google.android.talk;version=10.1.123988066-system;system=true", "com.android.phone;version=7.0;system=true", "com.google.vr.vrcore;version=1.0.160613022;system=true", "com.android.shell;version=7.0;system=true", "com.android.wallpaperbackup;version=7.0;system=true", "com.android.providers.blockednumber;version=7.0;system=true", "be.electrabel.energymanager;version=2.1.7;system=false", "com.android.providers.userdictionary;version=7.0;system=true", "com.android.emergency;version=7.0;system=true", "com.asus.aihome;version=1.0.0.2.61;system=false", "com.google.android.inputmethod.japanese;version=2.18.2569.3.124334694-arm64-v8a;system=true", "com.neuralprisma;version=1.1.56;system=false", "com.android.location.fused;version=7.0;system=true", "com.android.systemui;version=7.0;system=true", "com.android.bluetoothmidiservice;version=7.0;system=true", "com.carlson.android;version=2.8.1;system=false", "com.android.huawei.hiddenmenu;version=1.0;system=true", "com.google.android.launcher.layouts.angler;version=7.0;system=true", "net.aviascanner.aviascanner;version=3.3.4;system=false", "com.google.android.play.games;version=3.9.06 (3327802-040);system=true", "com.google.android.apps.gcs;version=D.1.5.10 (3152254);system=true", "com.android.bluetooth;version=7.0;system=true", "com.qualcomm.timeservice;version=7.0;system=true", "com.android.providers.contacts;version=7.0;system=true", "com.android.captiveportallogin;version=7.0;system=true", "com.google.android.GoogleCamera;version=4.1.006.126161292;system=true", "com.sony.songpal;version=4.2.0;system=false", "cn.wps.moffice_eng;version=9.9.5;system=false", "com.android.connectivity.metrics;version=1.0;system=true", "com.google.android.inputmethod.latin;version=5.1.23.127065177-arm64-v8a;system=true" ],
  "installerPackage" : null,
  "kernelVersion" : "3.10.73-g875b816",
  "premium" : true,
  "proxyMode" : false,
  "proxyPort" : 8080,
  "proxySetupManualMode" : false,
  "referrer" : null,
  "sendAnonymousStatistics" : true,
  "showUsefulAds" : true,
  "sourceApk" : "/data/app/com.adguard.android-1/base.apk",
  "sslMitmConfiguration" : null,
  "statisticsInfo" : "Blocked threats:2; Blocked banners:446088; Traffic saved:12671708160;",
  "trial" : false,
  "updateChannel" : "RELEASE",
  "upstreamProxySettings" : null,
  "userfilter" : [ ],
  "versionName" : "2.7.220",
  "whitelist" : [ ]
}

**Comment by Alex-302** [comment]
Which filters?

**Comment by evgeniy-ADG** [comment]
check the spoiler above.  "enabledFilterIds" : [ 2, 3, 4, 10, 11 ],

**Comment by Alex-302** [comment]
The answer is in your question. Annoyances filter is not enabled.
