### ISSUE TITLE
reddit.com/r/CrappyDesign

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#33361]
`https://old.reddit.com/r/CrappyDesign/`

Tag simulating a dead pixel to trick users: `reddit.com##a[href="#pixel"]`.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.16
Firefox 66

**Comment by BlazDT** [comment]
Difficult to click on though with 1x1 link.

**Comment by adranger** [comment]
@BlazDT it's not for you to click. It's to make you think there's a problem with your monitor or that it is dirty.
