### ISSUE TITLE
http://games.aarp.org/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3336]
http://games.aarp.org/games/crossword-easy/

![image](https://cloud.githubusercontent.com/assets/15856304/19926352/c047b166-a0fc-11e6-8817-baacd6cd128d.png)

<details>
Os version: Microsoft Windows NT 6.1.7601 Service Pack 1
Dot .net version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile; 4.5.2;
ApplicationId: 5a2758158cc54564b77958cf75b47e7c
Language: en
AppVersion: 6.1.258.1302
Main settings: 
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:8 Name: Dutch filter Url: http://adguard.com/ru/filter-rules.html?id=8
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Tdi
Ads Blocked: 694169, Trackers Blocked: 518496
Filtering Mode: Driver
Application lifetime: 301.00:50:21.7714843
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"
}

**Comment by Alex-302** [comment]
Not reproduced.
