### ISSUE TITLE
Add Hexxium Threat List to the available Filters

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardFilters#3337]
https://hexxiumcreations.github.io/threat-list/

The list contains URL's of typical misspelled URL's to prevent any kind of scam but mostly phone support scam.

**Comment by Alex-302** [comment]
The last update was 2016 08 09

**Comment by Bluscream** [comment]
Does that mean it's bad, @Alex-302?

**Comment by Alex-302** [comment]
Not bad, but it contains only 145 rules and some domains are dead.
https://hexxiumcreations.github.io/threat-list/hexxiumthreatlist.txt
