### ISSUE TITLE
http://m.papajohns.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3338]
**Description**: http://m.papajohns.ru/catalog/pizzas
При переходе в раздел Пицца не происходит выбор пиццы. Т.е. при нажатии на нужную, не открывается в новом окне описание пиццы. 

Помогает отключение Фильтра счетчиков и систем аналитики

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19937140/b39c5c10-a128-11e6-8f8d-683b352bb922.png)
![image](https://cloud.githubusercontent.com/assets/18548949/19937163/c7e1b18e-a128-11e6-977b-2fe46d3c7d67.png)

</details>

**Adguard version**: 2.8.15
6.1

**Filters list**: 1,2,3,4,14,11

**Operating system**: ВИН/АНДРОИД

**Browser**: Хром/встроенный

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Скрины не рабочие.
Добавил в фильтр аналитики
```
@@||googletagmanager.com/gtm.js$domain=m.papajohns.ru
@@||google-analytics.com/analytics.js$domain=m.papajohns.ru
@@||google-analytics.com/plugins/ua/ec.js$domain=m.papajohns.ru
```
