### ISSUE TITLE
livetv.sx

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#33382]
***Description***:
Hi
in the like to games in site: http://livetv.sx
have link with ads
exmple:
http://livetv.sx/enx/eventinfo/798143_bournemouth_tottenham/#webplayer_alieztv|89662|798143|1169665|1|1|en

* **Current behaviour**: 
http://prntscr.com/nkaov1

* **Expected behaviour**: 
http://prntscr.com/nkap3k

***Steps to reproduce the problem***:
open the site:
http://radio.sport5.co.il/
and click on the link for games

Information | Value
-- | --
Operating system: | win 10
Browser: | Google Chrome
AdGuard version: |6.4.1814.4903

Filters enabled:  
EasyList Hebrew,
EasyPrivacy,
AdGuard Annoyances,
AdGuard Base,
Adblock Warning Removal List

AdGuard DNS:  None
Stealth mode options (Windows only): not enabled

**Comment by MrTal** [comment]
@AdamWr 
@Alex-302 
exmple from now:
http://livetv.sx/enx/eventinfo/800121_feyenoord_den_haag/#webplayer_alieztv|89389|800121|1175171|22|1|en
http://prntscr.com/nnj3p6

**Comment by MrTal** [comment]
and have ads:
http://prntscr.com/nnj47p

**Comment by MrTal** [comment]
@AdamWr 
@AdamWr 
there is no solution?

**Comment by AdamWr** [comment]
I'm sorry for late reply.
Added:
`aplayer2.me###ads`
`aplayer2.me##.banner`
Update should be available in 1-2 hours.

**Comment by MrTal** [comment]
@AdamWr 
tank you now this work but sometimes have this X:
http://prntscr.com/nv57gl
http://prntscr.com/nv576p
can blok this?

**Comment by AdamWr** [comment]
Could you please provide link to stream where you see this "X" button?
Regarding "Click here to unmute" - I think that it shouldn't be blocked.

**Comment by MrTal** [comment]
@AdamWr 
"Click here to cunmute" this popup (no have popup with adgurd blcker) so i thnk yes remove "Click here to cunmute"
exmple:
http://cdn.livetvcdn.net/webplayer.php?t=ifr&c=1185432&lang=en&eid=807616&lid=1185432&ci=64&si=1
http://prntscr.com/nwghf3
http://prntscr.com/nwghmk

**Comment by AdamWr** [comment]
Thank you for links, added:
```
livesport4u.com,pcast.pw##.advertisement
livesport4u.com,pcast.pw,sportlive.site###localpp
||pcast.pw/addycash.js
||dynamicadx.com^$third-party
```

Regarding "Click here to unmute" - this button just enable sound in stream/video player, but if you want to hide it then you can add this rule to user filter:
`streamcdn.co,whostreams.net###btn-unmute`
