### ISSUE TITLE
m.rus.delfi.ee/ - Anti Adblock Script

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3339]
## Проблема повторилась, конкретно по ссылке ниже:

**http://m.rus.delfi.ee/estonia/article.php?id=75790237**

![image1](https://cloud.githubusercontent.com/assets/16462533/19945204/c32ff208-a147-11e6-9345-c762fd30793c.PNG)
## Фильтры:
> **Пользовательский
> Английский
> Фильтр счетчиков и систем аналитики
> Экспериментальный
> Фильтр раздражителей
> Русский**

**Comment by Alex-302** [comment]
Added to English filter
```
delfi.ee#@#.adbanner
delfi.ee###ab-top-bar
||ado.delfi.ee^

```
