### ISSUE TITLE
support.mozilla.org

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#33390]
`https://support.mozilla.org/en-US/questions/firefox`

Survey annoyance.

![survey](https://user-images.githubusercontent.com/35470489/57181050-3fa45f80-6e65-11e9-8063-b98c68ddb417.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.16
Firefox 66

**Comment by krystian3w** [comment]
Browser limitation?

**Comment by adranger** [comment]
You don't see it? Use a private window, scroll down and reload the page. I use temporary containers and keep getting that overlay every day I open this page.

**Comment by krystian3w** [comment]
I see when disable uBO, but any filters no works on `support.mozilla.org` in Firefox (blank logger).

**Comment by krystian3w** [comment]
Other story is workaround with: 

**about:config** , **privacy.resistFing­erprinting.block_mozA­ddonManage­r**, **true**.

and remove domains in **extensions.webextensi­ons.restricted­Domains** on **about:config** .

**Comment by adranger** [comment]
I already had those settings.

The filter `||surveygizmobeacon.s3.amazonaws.com` seems to stop the overlay.

**Comment by krystian3w** [comment]
What you unlock works uBO to works in Mozilla domains? this is seems outdated / blocked https://github.com/AdguardTeam/AdguardFilters/issues/33390#issuecomment-489469021

**Comment by adranger** [comment]
Yes. My browser is configured the way you said.

**Comment by Alex-302** [comment]
Can't reproduce. Could you please upload HAR file?

**Comment by krystian3w** [comment]
Still exsist for my side, but when create HAR? You try analize 4-5 refresh after show for me?

**Comment by krystian3w** [comment]
[Archive 19-05-13 18-13-43.zip](https://github.com/AdguardTeam/AdguardFilters/files/3173837/Archive.19-05-13.18-13-43.zip)

**Comment by Alex-302** [comment]
Added `||surveygizmobeacon.s3.amazonaws.com^$domain=support.mozilla.org`
