### ISSUE TITLE
Issues with sites

### ISSUE THREAD

**Issue by alexholox** [AdguardTeam/AdguardFilters#33392]
SFW SITES:

https://www.serpadres.es

Problem: strong anti-adblock. Adblocker detected and site gets blocked until you disable it.

https://www.logrosxbox.com/

Problem: strong anti-adblock. Site detects adblocker and gets blocked until you disable it.

https://salud.enfemenino.com

Problem: Ads still displayed, no matter adblock is active, some ads still pass through the filter.

https://deviantart.com

Problem: anti-adblock, but seems to be just triggered in mobile site. Adblock detected and site gets blocked: this exclusively happens in the mobile page format; if you see the page like PC format then you are not blocked

http://gdforum.freeforums.net

Problem: page is still navigable as normal, but when you enter on a thread a message is displayes requesting to turn off adblocker.

NSFW SITES:

https://www.pornhub.com

Problem: weird to explain. It's a format issue: the site is not displayed with the original design; instead, is shown without background and totally white, with no video thumbnails and disorganized. Also, links which are the only thing shown, does not work and redirect nowhere.

Android 9 last patch
No root
Nokia 6
Samsung Internet last version
AdGuard v2.3.7

**Comment by BlazDT** [comment]
Please post your used filters.
