### ISSUE TITLE
m.filmix.net - missed ad

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3340]
## Мобильная версия сайта проскает рекламу.
**У пользователя на андроиде, у меня повторилось на ios.**
**http://m.filmix.net/dramy/113436-horoshee-povedenie-2016.html**
![screenshot_2016-11-02-23-22-30](https://cloud.githubusercontent.com/assets/16462533/19946434/cf6bfbf2-a14c-11e6-866e-da26b07f9be6.png)
![img_1756](https://cloud.githubusercontent.com/assets/16462533/19946435/cf701a66-a14c-11e6-9043-ea8b1f7d79d4.PNG)
## Тестируемые фильтры:

> Пользовательский
> Английский
> Фильтр счетчиков и систем аналитики
> Экспериментальный
> Фильтр раздражителей
> Русский

**Comment by Alex-302** [comment]
iOS в веб-сокеты не умеет.
Проверь такие:
```
filmix.net##noindex > div[style$="!important;"]
filmix.net##div[id*="Composite"]
```
добавил в фильтр Сафари

**Comment by vgavrish** [comment]
Правила не помогли на Андроид

> На m.filmix.net всё так же реклама. Она не на главной странице. Надо войти
на любую вкладку с фильмами. Она как раз в аккурат под плеером там большая
такая.

>

**Comment by Alex-302** [comment]
Там и смотрел.
У меня в макосном сафари чисто
http://i85.fastpic.ru/big/2016/1109/e0/402d41c9f5087666ada15cdad44be7e0.png
иосного девайса нет.
Указанная релама скрыта правилом `filmix.net##div[id*="Composite"]`
@gshumihin можешь на айфоне проверить наличие баннера?

**Comment by vgavrish** [comment]
Так это на Андроиде же

**Comment by Alex-302** [comment]
Там тем более чисто)

**Comment by vgavrish** [comment]
У юзера еще реклама на андроид.
Качественный, фильтры те же
Лог. Заходил на m.filmix.net в 21:24.
[debug (2).txt](https://github.com/AdguardTeam/AdguardFilters/files/584318/debug.2.txt)

**Comment by Alex-302** [comment]
Похоже веб-сокеты.
Передай на проверку
```
filmix.net#%#window.WebSocket = undefined;
```
алгоритм фильтрации должен быть качественным.

**Comment by Alex-302** [comment]
Заблокировал ещё аналитику из его лога.

**Comment by vgavrish** [comment]
передала

**Comment by vgavrish** [comment]
говорит "Без результата"

**Comment by Alex-302** [comment]
А какой браузер?

**Comment by vgavrish** [comment]
@Alex-302 Cm browser

**Comment by Alex-302** [comment]
Он наверное сжатие использует. Лучше в Хроме проверить.

**Comment by vgavrish** [comment]
Говорит в Хроме результат тот же
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/20478885/be52bdd2-afe4-11e6-9c32-601ab79dd97e.png)

**Comment by Alex-302** [comment]
Пусть HAR запишет, у меня даже на iOS не повторяется.

**Comment by odudnyk** [comment]
Прислал HAR.
Пользователь - 1426828

**Comment by Alex-302** [comment]
Не вижу файла. Вы его к тикету прикрепили или где его искать?)

**Comment by odudnyk** [comment]
Он в тикете, да. Не получается его сюда прикрепить.

**Comment by vgavrish** [comment]
har - https://yadi.sk/d/ICtE-dIHzRTHH

**Comment by Alex-302** [comment]
Можно попробовать в низкоуровневых настройках добавить порт 8040 в список фильтруемых

**Comment by vgavrish** [comment]
отписала

**Comment by Alex-302** [comment]
ок, ждём

**Comment by Alex-302** [comment]
Мистика.
А фильтрация HTTPS включена?

**Comment by vgavrish** [comment]
отключена
он не хочет ее включать
без нее мол никак?

**Comment by Alex-302** [comment]
Да должна блокироваться. У тебя без HTTPS повторяется?

**Comment by vgavrish** [comment]
в прошлые разы блокировалась
сейчас глянула, не блочится без https

**Comment by Alex-302** [comment]
Хм, потерялось правило при оптимизации
```
||wsp.marketgid.com^
```
Добавил.

**Comment by vgavrish** [comment]
шикарно!

> Огромное Вам спасибо за решение проблемы с рекламой на m.filmix.net
> Вы лучшие. Огромное спасибо.

**Comment by Alex-302** [comment]
отлично

**Comment by vgavrish** [comment]
m.filmix.me
тут сайт теперь с https, и без фильтрации появляется баннер. Можно ли блокировать без включения https?

![image](https://cloud.githubusercontent.com/assets/18548949/21954154/8ab1c048-da52-11e6-8321-d294670acb22.png)

**Comment by Alex-302** [comment]
можно
