### ISSUE TITLE
2daygeek.com - Annoyance - Ad Leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3341]
**Site**: http://www.2daygeek.com/
**Description**: Weird message and ad leftover.

**Current behaviour**: Site shows a weird message in the middle of the site. And there is some ad leftover at the right side of the page.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/19946686/4416d3a8-a145-11e6-8673-6be548ae3be9.png)

</details>

========

**Adguard version**: 6.1.278.1411

**Filters list**: 
English filter 1.0.99.39
Spyware filter 1.0.8.72
Social media filter 1.0.14.20
Annoyances filter 1.0.5.97
German filter 1.0.28.15
Mobile ads filter 1.0.5.58
Safari filter 1.0.1.60

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to English filter
```
2daygeek.com##.sidebar-content div.widget.widget_text[-ext-has=">h3:contains( Ads –)"]
```
Added to Social filter
```
||apis.google.com^*/widget/render/page?$third-party
2daygeek.com##body > div[id^="spu-"]
```
