### ISSUE TITLE
http://www.tmz.com - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3342]
http://www.tmz.com/photos/2016/10/30/halloween-boo-ties-guess-whose-photos/images/2016/10/28/halloween-booty-03-jpg
The red arrows don't work, so I can't scroll through the gallery.
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/19959311/5f014c84-a1ae-11e6-99f1-7880f3715865.png)

</details>

>It works on the release version. It still does not work the latest fully updated beta.  

Reproduced on Mac 1.3.0 beta with the following filters:

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/19959328/7ff86de6-a1ae-11e6-9978-68663fd59614.png)

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||b.scorecardresearch.com/beacon.js$domain=tmz.com
```

**Comment by jo2dan23** [comment]
Looks like there is a tracker on the mobile version. Cant check atm but url is  cdn.trac.us
