### ISSUE TITLE
http://omelchuck.ru/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3343]
**Description**: Не отображаются картинки на странице
http://omelchuck.ru/samokat-oxelo-town-7-foto-obzor-i-vpechatleniya/

Помогает отключение фильтра Виджетов соц сетей

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/19959511/031a0c42-a1b0-11e6-85c7-cfbc4d3eece4.png)

</details>

**Adguard version**: 2.8.15, 6.1

**Filters list**: 1,2,3,4,14,11

**Operating system**: ВИН/Андроид

**Browser**: Хром, встроенный

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
