### ISSUE TITLE
http://www.phonecurrent.com/  - ads

### ISSUE THREAD

**Issue by jerryn70** [AdguardTeam/AdguardFilters#3345]
Showing ads 
http://www.phonecurrent.com/best-alternative-apps-to-truecaller/

**Comment by evgeniy-ADG** [comment]
Looks clear at my end, could you paste a screenshot here and give us some info about your filters?

**Comment by jerryn70** [comment]
<a href='http://i.imgur.com/bHABjNM' title=''><img src='http://i.imgur.com/bHABjNM.jpg' alt='' title='Hosted by imgur.com' /></a>

**Comment by evgeniy-ADG** [comment]
@Alex-302 indeed, it's self-advertising, more like an annoyance.

**Comment by Alex-302** [comment]
Yes. It is a desktop version of the site, on mobile device is annoying.
Added to Annoyances filter
```
phonecurrent.com##.td-more-articles-box
```
