### ISSUE TITLE
"eBay Kleinanzeigen" app

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3346]
**Description**:
http://forum.xda-developers.com/showpost.php?p=69453211&postcount=1814

**Comment by seanl-adg** [comment]
Added to English filter: `||google.com/ads/search/app?`
Added to German filter: `@@||api.ebay-kleinanzeigen.de/api/ads/`
But `@@||www.google.*/ads/$~third-party` in English filter should be fixed first.

It will leave ebay logos at the placeholder of ads like ![this](https://cloud.githubusercontent.com/assets/22858651/20026634/90f8e488-a341-11e6-994d-a940d7fa34b7.png)
Or we can unblock it and apply element hiding rules to leave the placeholder blank.
Also, is ![this](https://cloud.githubusercontent.com/assets/22858651/20026643/c69dbd34-a341-11e6-8468-434e42e26188.png) an ad?

**Comment by danidoedel** [comment]
@seanl-adg Yes that's an ad.

**Comment by ameshkov** [comment]
@Alex-302 we need your help to sort out `@@||www.google.*/ads/$~third-party` issue

**Comment by seanl-adg** [comment]
Fixed. How about [these](https://cloud.githubusercontent.com/assets/22858651/20078594/8996b09a-a584-11e6-80b9-d285ab9854d9.png) - ads?

**Comment by danidoedel** [comment]
Entries marked with "Top" aren't ads.
