### ISSUE TITLE
http://fanserials.tv

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3347]
**Description**: 
http://fanserials.tv/22122-sverhestestvennoe-12-sezon-3-seriya-the-foundry.html#
**Firefox.** Блокируется кнопка "Показать все" на странице. При нажатии  просто перекидывается вверх страницы.

**IE**. Реклама + кнопка Одноклассников
и на этой странице: http://fanserials.tv/supernatural/supernatural-12-sezon/

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20028389/bc1eea26-a338-11e6-9d60-146237777719.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20028403/1b51d9ae-a339-11e6-9102-c05084df0344.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20028408/31e3b1ec-a339-11e6-930c-11ff23b012be.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20028413/578fc64c-a339-11e6-8a0c-560f60a9f44b.png)

</details>

**Adguard version**: 6.1.278.1411

**Filters list**: 1,2,4,14

**Operating system**: Вин

**Browser**: Firefox, IE

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
> Firefox. Блокируется кнопка "Показать все" на странице. При нажатии просто перекидывается вверх страницы.

похоже фоксопроблемы. У меня она и без Адгарда в основном не работает.

Рекламу поправил.

**Comment by vgavrish** [comment]
в ФФ кнопка одноклассников - http://prntscr.com/d441pl
"Показать все" работает при адг

**Comment by Alex-302** [comment]
Непонятная проблема. Как я писал выше, и без Адгарда тоже иногда не работает.
Исключениями не исправить.
Кнопку убрал.

**Comment by vgavrish** [comment]
Просьба с форума и от того же пользователя
https://forum.adguard.com/index.php?threads/%D0%A0%D0%B5%D1%88%D0%B5%D0%BD%D0%BE-fanserials-tv.15260/page-2
добавить те три правила 


```
@@||fanserials.tv^$content
@@||mc.yandex.ru^
@@/*.js
```
+ 
> есть ли возможность заблочить кнопку Одноклассников, чтобы список из за неё не ломался (я когда проверял, было так что список торрентов не работал после блокировки этой кнопки)

**Comment by Alex-302** [comment]
Передай такое на проверку
```
@@||fanserials.tv^$jsinject,generichide,content 
```

**Comment by vgavrish** [comment]
передала

**Comment by vgavrish** [comment]
> Помогло. Но стали пролазить кнопки соц. сетей и кнопка "Посмотрел серию?"
![image](https://cloud.githubusercontent.com/assets/18548949/20406614/a754d1a4-ad16-11e6-95cf-7bddcd467b4e.png)

**Comment by Alex-302** [comment]
Такова цена починки в Фоксе)
Теперь пусть попробует по очереди удалять модификаторы(jsinject,generichide,content) с проверкой.

**Comment by vgavrish** [comment]
Здравствуйте. Проверил еще раз те 3 правила что Алекс давал мне раньше, и дополнительно проверил свои правила блокировки кнопки Одноклассников - вроде более менее работает. Передайте пожалуйста чтобы были добавлены сначала 3 правила Алекса отсюда
<https://forum.adguard.com/index.php?threads/%D0%A0%D0%B5%D1%88%D0%B5%D0%BD%D0%BE-fanserials-tv.15260/page-2#post-111258>.
А потом 2 моих тоже чтобы добавили:

```
fanserials.tv###container > DIV.serial-page >
DIV.serial-page-cont:nth-child(5) > DIV.serial-page-cont-top:nth-child(2) >
DIV.serials-block-social:last-child > DIV.ya-share2.ya-share2_inited >
DIV.ya-share2__container.ya-share2__container_size_m >
UL.ya-share2__list.ya-share2__list_direction_horizontal:first-child >
LI.ya-share2__item.ya-share2__item_service_odnoklassniki:last-child >
A.ya-share2__link > SPAN.ya-share2__badge:first-child >
SPAN.ya-share2__icon:first-child
```
```
fanserials.tv###container > DIV.serial-page.serial-page-full >
DIV.serial-page-top:nth-child(9) > DIV.serial-page-info >
DIV.right-block:last-child > DIV.ya-share2.ya-share2_inited >
DIV.ya-share2__container.ya-share2__container_size_m >
UL.ya-share2__list.ya-share2__list_direction_horizontal:first-child >
LI.ya-share2__item.ya-share2__item_service_odnoklassniki:last-child >
A.ya-share2__link > SPAN.ya-share2__badge:first-child >
SPAN.ya-share2__icon:first-child
```

С его 3 правилами работает список торрентов, а мои блокируют кнопки
Одноклассников тут <http://fanserials.tv/supernatural/> и тут
<http://fanserials.tv/23780-sverhestestvennoe-12-sezon-6-seriya-pochtit-pamyat-asy-foks.html>

**Comment by Alex-302** [comment]
Да пусть удалит всё что раньше добавил. Нужно только это правило проверить в разных комбинациях:
```
@@||fanserials.tv^$jsinject,generichide,content 
@@||fanserials.tv^$jsinject,generichide 
@@||fanserials.tv^$generichide,content 
@@||fanserials.tv^$jsinject,content 
@@||fanserials.tv^$jsinject
@@||fanserials.tv^$generichide
@@||fanserials.tv^$content 
```
Правила, созданные помощником меня не особо интересуют, лучше скрины с разблокированным присылает со ссылками на страницы.
