### ISSUE TITLE
4pda.ru - incorrect blocking

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3348]
**Description**:
Браузер Chrome. При переходе на сайт и пролистывании страницы, страница загружается не полностью. Помогает отключение Русского фильтра
Во встроенном браузере проблемы нет

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20028682/08843878-a341-11e6-9e12-8b520c930f8e.png)

</details>

**Adguard version**: 2.8.40

**Filters list**: 1,2,3,4,11

**Operating system**: Андроид

**Browser**: Хроm
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
А в другом браузере как работает? У меня в Хроме без Адгарда семь постом загружается.

**Comment by vgavrish** [comment]
у меня все посты отображаются при выкл адг до перечня страниц
а с адг все таже проблема в хроме: http://prntscr.com/d3olcm
во встроенном и в Яндексе все в порядке: http://prntscr.com/d3ola5

**Comment by Alex-302** [comment]
Вроде нашёл возможную причину. Правила добавил.

**Comment by vgavrish** [comment]
проверила, все работает

**Comment by Alex-302** [comment]
ну и отлично

**Comment by vgavrish** [comment]
818707
Не загружаются скриншоты в шапке темы, когда нажимаешь плюс
http://4pda.ru/forum/index.php?showtopic=154770&st=2860

Хром. Прога
Ф: 1,2,14

**Помогает отключение фильтра Раздражителей**
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/21542419/39764a34-cdc6-11e6-9ef9-5f88d2f5727f.png)

**Comment by Alex-302** [comment]
Поправил.

**Comment by evgeniy-ADG** [comment]
https://4pda.ru/forum/index.php?act=search&source=all&forums=281&subforums=1&query=Vk

Сайт поломался:

![screenshot_2017-02-24-20-34-58](https://cloud.githubusercontent.com/assets/15856304/23330681/9c68fdd0-fb5c-11e6-8678-18cff222c1ce.png)

<details>

HQ method, SSL filtering, English, Russian, Spyware, SM, Annoyances. VPN.

**Comment by Alex-302** [comment]
> Сайт поломался

похоже так и есть. У меня без Адгарда повторяется.
