### ISSUE TITLE
http://segodnya.ua - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3349]
http://sport.segodnya.ua/football/byvshemu-igroku-metallista-zapretili-igrat-za-sbornuyu-italii-767164.html

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/20029171/06d0bfd0-a34e-11e6-8f3b-935801319b52.png)

</details>

Russian, English, annoyancesm Social madia, spyware

**Comment by Alex-302** [comment]
Fixed
