### ISSUE TITLE
http://www.redtube.com/ - English filter breaks distorts the site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3350]
http://www.redtube.com/

<details>
With EF

![screenshot_2](https://cloud.githubusercontent.com/assets/15856304/20029369/aa755f20-a352-11e6-81f4-0d7fc823923d.png)

</details>

<details>
and without

![screenshot_3](https://cloud.githubusercontent.com/assets/15856304/20029371/b24b1e10-a352-11e6-9547-5b62e4ea1714.png)

</details>

**Comment by Alex-302** [comment]
Fixed
