### ISSUE TITLE
seasonvar.ru - ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3351]
**Description**:  На главной вверху реклама
seasonvar.ru

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20029553/82a3c4dc-a357-11e6-8010-5a170a8c750c.png)

</details>

**Adguard version**: 2.8.40

**Filters list**: 1,2,3,4,5,11,14,211

**Operating system**: Андроид

**Browser**: Хром, встроенный

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
поправил
