### ISSUE TITLE
Facebook 

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3352]
1437156
**Description**: Мы же блокируем данные блоки?
http://prntscr.com/d3da99

**Adguard version**: 1.3.0

**Filters list**: 1,2,3,4,10

**Operating system**: Мас

**Browser**: Сафари, Хром, Мозилла

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Да, но для макосной программы ещё не доехал расширенный CSS.
