### ISSUE TITLE
https://paybis.com/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3354]
https://paybis.com/

![image](https://cloud.githubusercontent.com/assets/15856304/20036451/767603e0-a411-11e6-8f60-c5195a9b8754.png)

<details>
{
  "advancedPreferences" : {
    "pref.splash.enabled" : true,
    "pref.vpn.ipv6.force" : false,
    "pref.vpn.disable.pause" : false,
    "pref.har.capture" : false,
    "pref.vpn.ipv4.force.default" : false,
    "pref.vpn.ipv6.bypass" : false,
    "pref.vpn.ipv6.disable" : false,
    "pref.vpn.ipv4.force.complex" : false,
    "pref.proxy.block.ipv6" : false,
    "pref.vpn.capture" : false
  },
  "androidVersion" : "4.2.2 (sdk=17)",
  "appLanguage" : "en",
  "applicationId" : "4d2bb5658efd4811",
  "whitelist" : [ ],
  "versionName" : "2.8.40",
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "intel 3GD52I",
  "userfilter" : [ ],
  "upstreamProxySettings" : null,
  "enabledFilterIds" : [ 2, 3, 4, 14, 1, 11, 211 ],
  "environment" : "beta",
  "filteringQuality" : "SPEEDY",
  "updateChannel" : "BETA",
  "iconType" : "LOW_PRIORITY",
  "installedPackages" : [ "android;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "cc.madkite.freedom;version=1.3.4;system=false", "com.acr.screenshothd;version=1.0.6;system=false", "com.adguard.android;version=2.8.40;system=false", "com.android.bluetooth;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.calculator2;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.calendar;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.certinstaller;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.contacts;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.defcontainer;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.deskclock;version=2.0.3;system=true", "com.android.dreams.basic;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.dreams.phototable;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.galaxy4;version=1.0;system=true", "com.android.gallery3d;version=1.1.40001;system=true", "com.android.htmlviewer;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.inputdevices;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.internal.telephony.CwsMMGRService;version=1.0;system=true", "com.android.keychain;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.location.fused;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.magicsmoke;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.mms;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.music;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.musicfx;version=1.4;system=true", "com.android.musicvis;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.noisefield;version=1.0;system=true", "com.android.packageinstaller;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.phasebeam;version=1.0;system=true", "com.android.phone;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.providers.applications;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.providers.calendar;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.providers.contacts;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.providers.downloads;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.providers.downloads.ui;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.providers.drm;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.providers.media;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.providers.settings;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.providers.telephony;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.providers.userdictionary;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.settings;version=null;system=true", "com.android.sharedstoragebackup;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.smspush;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.soundrecorder;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.stk;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.systemui;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.vending;version=7.0.17.H-all [0];system=true", "com.android.videoeditor;version=1.1;system=true", "com.android.vpndialogs;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.wallpaper;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.android.wallpaper.livepicker;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.blankmediagames.townofsalem;version=1.4;system=false", "com.borqs.factorytest;version=4.2.2-eng.xiaoyuguang.20140725.204833;system=true", "com.bsplayer.bspandroid.full;version=1.27.189;system=false", "com.delphicoder.flud;version=1.4.5;system=false", "com.fsck.k9;version=4.804;system=false", "com.ghisler.android.TotalCommander;version=2.72;system=false", "com.google.android.apps.maps;version=1.0.1;system=true", "com.google.android.configupdater;version=4.2.2-721232;system=true", "com.google.android.gms;version=3.1.59 (736673-30);system=true", "com.google.android.gsf;version=4.2.2-721232;system=true", "com.google.android.gsf.login;version=4.2.2-721232;system=true", "com.google.android.location;version=1.01;system=true", "com.google.android.partnersetup;version=4.2.2-721232;system=true", "com.google.android.youtube;version=10.43.60;system=false", "com.imdb.mobile;version=4.3.2.104320110;system=false", "com.instagram.android;version=7.20.0;system=false", "com.intel.filemanager;version=0.1.2.1001;system=true", "com.intel.security.service;version=1.0;system=true", "com.kainy.client;version=1.74;system=false", "com.lingualeo.android;version=2.5.3;system=false", "com.necta.wifimouse;version=1.6.9;system=false", "com.openmygame.games.kr.client;version=1.2.6;system=false", "com.opera.browser.beta;version=35.0.2070.100163;system=false", "com.pushbullet.android;version=17.6.11;system=false", "com.svox.pico;version=1.0;system=true", "com.teamviewer.teamviewer.market.mobile;version=11.0.4376;system=false", "com.the7art.skatingrinkwallpaper;version=2.4.3;system=false", "com.uc.browser.hd;version=3.4.3.532;system=false", "com.urbandroid.lux;version=6.5;system=false", "com.yandex.android.inputmethod.latin;version=1.01;system=true", "com.yandex.browser;version=16.7.0.2777;system=true", "com.yandex.location;version=1.01;system=true", "com.yandex.onetime.init;version=1.0;system=true", "com.yandex.recognition;version=1.01;system=true", "com.yandex.setup.wizard;version=1.0;system=true", "com.yandex.shell;version=3.11;system=true", "com.yandex.store;version=2.43;system=true", "com.yandex.sync;version=1.02;system=true", "com.yandex.wallpaperchooser;version=1.0;system=true", "dkc.video.fsbox;version=2.3.6;system=false", "eu.chainfire.supersu;version=2.78;system=true", "org.telegram.messenger;version=3.4.2;system=false", "ru.angryrobot.chatvdvoem;version=2.31;system=false", "ru.e_num;version=3.2.0;system=false", "ru.kinopoisk;version=3.5.0;system=false", "ru.vdmodule.androidmetrix;version=3.8;system=false", "ru.yandex.disk;version=2.77;system=true", "ru.yandex.mail;version=3.02;system=true", "ru.yandex.market;version=2.20;system=true", "ru.yandex.metro;version=2.32;system=true", "ru.yandex.translate;version=2.60;system=true", "ru.yandex.yandexmaps;version=5.2;system=true", "ru.yandex.yandexnavi;version=2.03;system=true", "yourstyleapps.livewallpaper3d06;version=1.19;system=false" ],
  "installerPackage" : null,
  "kernelVersion" : "3.4.34-00033-g5afba23",
  "statisticsInfo" : "Blocked threats:0; Blocked banners:23670; Traffic saved:618433536;",
  "sslMitmConfiguration" : "{\"mitmListMode\":\"WHITELIST\",\"mitmList\":\"1018 domains\",\"certificateInstalledToSystemStorage\":null}",
  "sourceApk" : "/data/app/com.adguard.android-2.apk",
  "referrer" : null,
  "proxySetupManualMode" : false,
  "sendAnonymousStatistics" : false,
  "showUsefulAds" : false,
  "proxyPort" : 8080,
  "proxyMode" : true,
  "premium" : false,
  "trial" : false,
  "filtersAutoUpdateEnabled" : true,
  "dnsFilteringEnabled" : false,
  "deviceSpeedRank" : 329,
  "browsingSecurityEnabled" : false,
  "autoStartEnabled" : true
}

**Comment by Alex-302** [comment]
fixed
