### ISSUE TITLE
https://www.jumia.com.ng/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3356]
https://www.jumia.com.ng/crystal-phone/

![image](https://cloud.githubusercontent.com/assets/15856304/20061419/6eb8c000-a508-11e6-89dd-b55142025e56.png)

<details>
Application version: 1.1.2.24
Application lifetime: 2016-11-04 23:48:37 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.3
ID: FF5454B3-D5D2-47FA-ACCD-52082A44B807

Locale: en
Region: ng

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.99.64 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.79 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.24 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.6.4 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.59 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.64 Enabled=YES
ID=15 Name="Adguard DNS" Version=1.0.0.5 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.68.61 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.68.49 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.62 Enabled=YES

**Comment by Alex-302** [comment]
Please check without Adguard(on my end only few images was loaded)
