### ISSUE TITLE
[Extension] http://all-poster.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3357]
http://all-poster.ru/?v=xml8rznt.jpg

![image](https://cloud.githubusercontent.com/assets/15856304/20061753/e49e014e-a509-11e6-95e9-1f13a46d0c5a.png)

<details>
Мои параметры:
* Win x64
* adguard в виде расширения у Chrome
* фильтры: русский, английский, RU AdList
* Dr.Web

**Comment by Alex-302** [comment]
Fixed
