### ISSUE TITLE
finanzen100 app

### ISSUE THREAD

**Issue by n0w4y** [AdguardTeam/AdguardFilters#33570]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 
<details><summary>Screenshot:</summary>

![Screenshot_2019-05-09-21-01-14-793_de finanzen100](https://user-images.githubusercontent.com/26310479/57479778-839cc780-729e-11e9-91dd-be2bd0e41545.png)
</details><br/>

* **Expected behaviour**: 

<details><summary>Screenshot:</summary>

![Screenshot_2019-05-09-21-01-21-681_de finanzen100](https://user-images.githubusercontent.com/26310479/57479710-56501980-729e-11e9-9a28-2cea70253f4e.png)
</details><br/>

***Steps to reproduce the problem***:
Open Finanzen100 app (https://play.google.com/store/apps/details?id=de.finanzen100) on an Android smartphone.

***System configuration***:

**Filters:**
Adguard Base Filter, Adguard Mobile Filter

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 9
Browser:                               | Chrome
AdGuard version:                       | 3.0.297
Filters enabled:                       | see above
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | N/A
AdGuard DNS:                           | Off
Stealth mode options (Windows only)    | N/A
Helpdesk ID (if exists):               | N/A

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
App opens fine, also tried with AdGuard DNS and still working.
Please check @AdamWr
