### ISSUE TITLE
https://nstarikov.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3358]
https://nstarikov.ru/blog/72008

![image](https://cloud.githubusercontent.com/assets/15856304/20061823/1d172dac-a50a-11e6-858e-71381a26c70f.png)

<details>
Мои параметры:
* Win x64
* adguard в виде расширения у Chrome
* фильтры: русский, английский, RU AdList
* Dr.Web

**Comment by Alex-302** [comment]
Не повторилось.
RU AdList - их три. Какой именно добавлен, и помогает ли его отключение?

**Comment by Serzh-SUP** [comment]
@Alex-302 Спросили у пользователя, ожидаем ответ.

**Comment by vgavrish** [comment]
Без ничего, просто RU AdList
http://f3.s.qip.ru/Ogbqitl9.png

У меня повторилось:
http://prntscr.com/d5m4nx
http://prntscr.com/d5m536

**Comment by Alex-302** [comment]
Похоже от фильтров не сильно зависит. У меня с одним немецким ломается. Только сайт открываться перестал.

**Comment by evgeniy-ADG** [comment]
А от чего зависит?

**Comment by Alex-302** [comment]
Не знаю) Сейчас у меня всё работает
http://ipic.su/img/img7/fs/kiss_792kb.1479413665.png
может сам сайт глючил.

**Comment by vgavrish** [comment]
а у меня все та же ситуация - http://prntscr.com/d965p0
при отключении фильтрации на странице, видео показывается

**Comment by Alex-302** [comment]
Странно. Удалённо бы глянуть.

**Comment by evgeniy-ADG** [comment]
@vgavrish @Alex-302 могли бы вы немного сориентировать по срокам? Вы можете у себя сделать ТВ или нужно просить кастомера?

**Comment by Alex-302** [comment]
@evgeniy-ADG в рабочее время. Юзеру, естественно, тоже нужно установить teamviewer.

**Comment by vgavrish** [comment]
@Alex-302 сейчас подойдет?

**Comment by Alex-302** [comment]
@vgavrish лучше в скайп стучи, иначе реакция не быстрая.
Завтра смогу.

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||nstarikov.ru^$generichide
```

**Comment by vgavrish** [comment]
Теперь таже проблема с RU AdList http://f3.s.qip.ru/Ogbqitl9.png
При отключении фильтра, видео отображается.

**Comment by Alex-302** [comment]
А он русский фильтр не выключил?

**Comment by vgavrish** [comment]
Нет, с включенным Русским
а зачем? с отключенным Русским все равно блокируется видео
Странная сейчас ситуация, теперь и Английский фильтр блочит вместе с RU AdList

**Comment by Alex-302** [comment]
Ну у меня больше версий нет. Повторить так и не удаётся.
Не исключено, что баг.

**Comment by vgavrish** [comment]
Ну могу опять доступ дать

**Comment by Alex-302** [comment]
Давай тогда завтра гляну.

**Comment by vgavrish** [comment]
если получится то после 3х, а так в субботу лучше

**Comment by Alex-302** [comment]
Ок, можно в субботу.

**Comment by TomCruiseXZ** [comment]
Alex-302, 
1) проверь свой комп на вирусы
2) поставь чистый Chrome и одно расширение Adguard и на нём тести

**Comment by Alex-302** [comment]
@TomCruiseXZ мне-то чего лечить? У меня всё работает. Или думаешь вирус может чинить плеер?:)

**Comment by TomCruiseXZ** [comment]
Alex-302, вот именно, ни у кого не работает, а у тебя норм
Судя по скрину твоего браузера, не пойми какой сборки школьника и не пойми какая куча плагинов
> поставь чистый Chrome и одно расширение Adguard и на нём тести

**Comment by TomCruiseXZ** [comment]
Когда поправите ?
