### ISSUE TITLE
spotify.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#33629]
@AdamWr  Daily Mix playlist does not work at https://open.spotify.com/browse/featured 
When I click on PLAY - nothing happen. Other playlists/albums works well.

**Comment by AdamWr** [comment]
Mógłbyś proszę dokładniej opisać (albo zrobić zrzut ekranu) co muszę zrobić aby odtworzyć ten problem?
Nie widzę niczego takiego jak "Daily Mix" u siebie.

**Comment by FadeMind** [comment]
![scr-1557512923-001](https://user-images.githubusercontent.com/9846948/57548920-79440180-7362-11e9-9fc7-d74f3cddc729.png)
![scr-1557512956-001](https://user-images.githubusercontent.com/9846948/57548921-79440180-7362-11e9-814c-b3f3ad5aa4ef.png)
![scr-1557512976-001](https://user-images.githubusercontent.com/9846948/57548922-79dc9800-7362-11e9-9db1-f7002ffcb7ce.png)

Dla porównania playlista zamknięta (o określonej liczbie utworów) działa.
![scr-1557512998-001](https://user-images.githubusercontent.com/9846948/57548923-79dc9800-7362-11e9-96b9-9bee41194086.png)

**Comment by FadeMind** [comment]
@AdamWr  Konsola na Daily Mix daje takie wyniki:
![scr-1557514361-001](https://user-images.githubusercontent.com/9846948/57550093-9deda880-7365-11e9-946a-55c759c07cf4.png)

**Comment by AdamWr** [comment]
Nie potrafię znaleźć niczego takiego u siebie, to "Daily Mix" to się jakoś samemu tworzy?
Mógłbyś proszę sprawdzić, która lista powoduje ten problem i zrobić zrzut ekranu z zablokowanymi połączeniami?

**Comment by FadeMind** [comment]
@AdamWr  jeżeli intensywnie korzystasz ze Spotify oni po jakimś czasie wrzucają ulubione single do dwóch playlist - Ulubione z Radia i Daily Mix kolejno numerowane.

Wyślę Ci na maila służbowego JSON log.

**Comment by FadeMind** [comment]
@AdamWr sprawdź pocztę e-mail ;)

**Comment by AdamWr** [comment]
Dostałem, dziękuję.
Niedługo sprawdzę.

**Comment by AdamWr** [comment]
Sprawdź proszę, czy po dodaniu tych reguł działa:
```
@@||fastly-insights.com/insights.js$domain=open.spotify.com
@@||vt.myvisualiq.net/*/vt-*.js$domain=open.spotify.com
@@||sb.scorecardresearch.com/beacon.js$domain=open.spotify.com
```

**Comment by FadeMind** [comment]
@AdamWr nie działa.

**Comment by AdamWr** [comment]
Niestety bez możliwości odtworzenia problemu nie jest łatwo ustalić co jest przyczyną problemu
Sprawdź proszę:
```
@@||spclient.wg.spotify.com/metrics-backend/$domain=open.spotify.com
@@||fastly-insights.com^$domain=open.spotify.com
@@||myvisualiq.net^$domain=open.spotify.com
@@||scorecardresearch.com^$domain=open.spotify.com
@@||spclient.wg.spotify.com/ads/$domain=open.spotify.com
@@||open.spotify.com/log/$domain=open.spotify.com
```

**Comment by FadeMind** [comment]
@AdamWr Najdziwniejsze jest to, że nawet jak adguard wyłączę, wyczyszczę cache i cookies to i tak nie działa xD W Aplikacji UWP Spotify Adguard nie blokuje reklam, ale daily mix działają.

**Comment by AdamWr** [comment]
Czyli rozumiem, że coś nie tak jest ze stroną.

>W Aplikacji UWP Spotify Adguard nie blokuje reklam, ale daily mix działają.

Ok, sprawdzę to, ale już nie dzisiaj :)
Swoją drogą, chodzi o tę aplikację? https://www.microsoft.com/en-us/p/spotify-music/9ncbcszsjrsb?cid=spotifyweb-windows10-store-direct
