### ISSUE TITLE
http://ark.intel.com/  -  incorrect blocking.

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#3365]
Не работает меню "ARK Menu" в левом верхнем углу страницы.
На это влияет фильтр - `||tags.tiqcdn.com/utag/*/utag.js`
Следующее исключение заставляет его работать - `@@||tags.tiqcdn.com/utag/intel/*`

![ark intel com](https://cloud.githubusercontent.com/assets/17948007/20100003/569b699a-a5cc-11e6-80fe-72afc1e1e0c3.jpg)

**Comment by Alex-302** [comment]
Спасибо, исправил.
