### ISSUE TITLE
nnm.me - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3366]
Reproduced. 

![image](https://cloud.githubusercontent.com/assets/15856304/20102860/494ce0a8-a5d0-11e6-8274-479306391b20.png)

<details>
Фильтр раздражителей,полезной рекламы,Русский,экспериментальный,мобильной рекламы,сафари,ru adlist bit lock,ru adlist counters

**Comment by Alex-302** [comment]
It is clean in Safari for MacOS
http://i83.fastpic.ru/big/2016/1108/79/ff90e2ab197dea4fcb0d99f82378ed79.png
Try without third-party filters.

**Comment by evgeniy-ADG** [comment]
Yes, but it's not on iPhone. We reproduced it here in the office.

**Comment by Alex-302** [comment]
Please check this rule:
```
##body > div[id][class][style*="data:image/jpeg;base64"]
```
