### ISSUE TITLE
[NSFW][ADS]katestube.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#33663]
**Site Sample** | 
----------------|
https://www.katestube.com/videos/2328735/thick-bbw-latina-needs-a-huge-cock/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.0.x Nightly** 
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
| **=== FILTERS ENABLED ===**
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| facebook annoyances blocker
| **SECTION :: Ads**
| Adguard Base Filter 
| EasyList
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| EasyPrivacy
| Fanboy's Anti-Facebook List 
| Fanboy's Enhanced Tracking List 
| **SECTION :: Social**
| Adguard Social Filter
| Fanboy's Social Blocking List 
| **SECTION :: Annoyances**
| Adblock Warning Removal List
| Adguard Annoyances
| Fanboy's Annoyances 
| I don't care about cookies
| **SECTION :: Security**
| Malware Domains
| Spam404
| NoCoin Filter List 
| **SECTION :: Customs**
| AlleBlock
| EasyList Polish 
| KAD - fraud/scam
| Polish Annoyances Filters
| Polish Anti Adblock List Filters
| Polish Main Filters
| Polish Social Filters

### Issue:

Ads BEFORE clip start. Cookies should be purged for recreate this issue. 

<details><summary><b>Screenshot:</b></summary>

![scr-1557557317-001](https://user-images.githubusercontent.com/9846948/57566204-1dad5e80-73ca-11e9-86dd-500716d84559.png)

</details><br/>

@AdamWr

**Comment by Nzzyme** [comment]
Seeing pop-ups on Windows when clicking on play button 
https://www.katestube.com/videos/601121/sophie-dee-and-emma-heart/

Checked with AG for Chrome.

**Comment by AdamWr** [comment]
Fixed.

**Comment by AdamWr** [comment]
Fixed.
