### ISSUE TITLE
vider.info

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#33672]
vider.info should be whitelisted in STEALTH mode against player streaming issues.

```
@@||vider.info^$stealth
```

@AdamWr

**Comment by AdamWr** [comment]
Mógłbyś proszę napisać jak odtworzyć ten problem?
Chodzi o to, że jeśli to możliwe, wolałbym nie wyłączać trybu "niewidzialności" na całej stronie i dodać na przykład coś takiego `@@||vider.info/embed/$stealth`

**Comment by FadeMind** [comment]
@AdamWr  Co jakiś nieokreślony czas podczas oglądania filmu na vider.info przerywało odtwarzanie i wyskakiwał błąd o dostępie do pliku źródłowego/czy to problem z integralnością danych. Jak dodałem `@@||vider.info^$stealth` problem zniknął. Być może to problem tylko i wyłącznie odtwarzacza używanego na tej stronie gdy aktywny jest `stealth`.

**Comment by AdamWr** [comment]
Ok, dodałem.
