### ISSUE TITLE
https://flippa.com - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3367]
https://flippa.com

Search functionality and buttons do not work on Flippa.com site. Not
sure why but when I disable adguard they work again.

![image](https://cloud.githubusercontent.com/assets/15856304/20103964/b7171a3c-a5d4-11e6-9a25-fcef5356932c.png)

<details>
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:109 Name: EasyList Italy Url: https://easylist-downloads.adblockplus.org/easylistitaly.txt
FilterId:113 Name: Liste FR Url: https://easylist-downloads.adblockplus.org/liste_fr.txt
FilterId:0 Name: User filter Url: no_url
FilterId:14 Name: Annoyances filter Url: http://adguard.com/ru/filter-rules.html?id=14
Filtering Mode: Driver
Driver Type: Tdi

**Comment by Alex-302** [comment]
Try this rule:
```
@@||d3dmykktyp55kz.cloudfront.net^$domain=flippa.com
```
