### ISSUE TITLE
[NSFW] vivatube.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#33681]
**Site Sample** | 
----------------|
https://www.vivatube.com/pl/video/291873/amateur-barbara-from-poland-dildo-masturbate

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.0.x Nightly** 
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
| **=== FILTERS ENABLED ===**
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| facebook annoyances blocker
| **SECTION :: Ads**
| Adguard Base Filter 
| EasyList
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| EasyPrivacy
| Fanboy's Anti-Facebook List 
| Fanboy's Enhanced Tracking List 
| **SECTION :: Social**
| Adguard Social Filter
| Fanboy's Social Blocking List 
| **SECTION :: Annoyances**
| Adblock Warning Removal List
| Adguard Annoyances
| Fanboy's Annoyances 
| I don't care about cookies
| **SECTION :: Security**
| Malware Domains
| Spam404
| NoCoin Filter List 
| **SECTION :: Customs**
| AlleBlock
| EasyList Polish 
| KAD - fraud/scam
| Polish Annoyances Filters
| Polish Anti Adblock List Filters
| Polish Main Filters
| Polish Social Filters

### Issue:

Adboxes, Overalys, Redirects. 
Popup after click play on VIDEO. 

Reporoduce:
open main page vivatube.com
Click random video and play. Popup opened. Popupblocker does not handle it all of them. 

Opened many redirects and last is site
`t.winpbn.com` - blocked with Adguard Defense
`mptentry.com` - blocked with Adguard Defense
`cradver.livejasmin.com/pu/fsrnd?ms_rnd=1557595971.42274&pstool=300_20&psid=ed_vivtbdt&site=jsm&utm_medium=partner&utm_source=dtb&category=girl&origin=mptentry.com` opened. 

<details><summary><b>Screenshot:</b></summary>

![scr-1557595885-001](https://user-images.githubusercontent.com/9846948/57573087-62b1af00-7423-11e9-8981-a223122cc62b.png)

</details><br/>

@AdamWr

**Comment by AdamWr** [comment]
Naprawiłem wyskakujące okienka i kilka pozostałości po reklamach, ale nie potrafię odtworzyć tych elementów z zrzutu ekranu, nawet po wyłączeniu AdGuarda.
