### ISSUE TITLE
http://www.geektime.co.il/

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#3369]
Hey
have in site: http://www.geektime.co.il/
mechanism anti adblock on clic this
http://prntscr.com/d4q4o2
can give me filter for block this?

**Comment by Alex-302** [comment]
I don't understand anything.
Please show me expected and current behaviour.

**Comment by MrTal** [comment]
i wont block the mechanism anti adblock this, on clic this:
http://prntscr.com/d4q4o2

**Comment by Alex-302** [comment]
Ok, I understood  now.
Added to Annoyances filter
```
geektime.co.il#%#Object.defineProperty(window, 'DetectionProcessRunning', { get: function() { return true; } });
```

**Comment by MrTal** [comment]
the filter work but still no added to Annoyances filter

**Comment by Alex-302** [comment]
wait 1 hour before update
