### ISSUE TITLE
hipenpal.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#33696]
`http://www.hipenpal.com/`

Top cookie notice.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.16
Firefox 66

**Comment by adranger** [comment]
@Alex-302 

![cookie notice](https://user-images.githubusercontent.com/35470489/61143418-9010ec80-a4a8-11e9-9485-504abce1483f.png)

**Comment by Alex-302** [comment]
Please show HTML code or upload saved page.

**Comment by adranger** [comment]
@Alex-302 

[hi penpal.zip](https://github.com/AdguardTeam/AdguardFilters/files/3436430/hi.penpal.zip)

**Comment by Alex-302** [comment]
Fixed
