### ISSUE TITLE
http://m.finn.no/user/ads.html - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3371]
http://m.finn.no/user/ads.html

![image](https://cloud.githubusercontent.com/assets/15856304/20111105/b7a26338-a5ef-11e6-8a92-9e9ee8d302bc.png)

<details>
Application version: 1.1.1.54
Application lifetime: 2016-09-17 13:25:15 +0000

Device: iPhone
Platform: iOS
OS: 10.0.2
ID: 7EDE339B-AC6F-4FBF-BB4C-8A4C523EB8E4

Locale: en
Region: no

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.70 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.72 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.70 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.4.5 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.88 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.27 Enabled=YES
ID=120 Name="Norsk adblockliste" Version=1.0.0.1 Enabled=YES

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||finn.no/user/ads.html
```
