### ISSUE TITLE
xhamster.desi [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#33728]
**Site**: https://xhamster.desi/videos/mere-bhai-ne-meri-gand-mari-7587791#mlrelated

**Issue**: Please remove the pop-up after clicking on the video thumbnails (below the player).

**Screenshot**: N/A

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 74.0.3729.131 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 3.0.14 `

**Filters**:
```
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404
NoCoin Filter List

```

**Stealth Mode Settings**:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled

**Comment by bogachenko** [comment]
are you about this?
`xhamster.*##.no-popunder.wid-sponsor-banner`

**Comment by Nzzyme** [comment]
Popup seen when clicking on the thumbnail of videos at the bottom of the page.

Moreover, after pausing the video, seeing a "X" symbol on the player

http://prntscr.com/oxoiua

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.

**Comment by Nzzyme** [comment]
Link: https://xhamster.desi/videos/paki-aunty-fucked-7830439?pb=#

After clicking on the play button and then on the pause button shows a pop-up. Can  you please check .
