### ISSUE TITLE
http://www.dignitymemorial.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3372]
http://www.dignitymemorial.com/mount-moriah-freeman-funeral-home/en-us/photo-gallery.page?internalfullsite=1&internalfullsite=1

Tapping the links doesn't work. Tap & hold and peek & pop do work. Once Adguard was switched off for this domain, link behavior returned to normal. 

![image](https://cloud.githubusercontent.com/assets/15856304/20111390/b2457348-a5f0-11e6-9cf3-8452c588ef76.png)

<details>
Application version: 1.1.1.54
Application lifetime: 2016-09-14 12:18:12 +0000

Device: iPhone
Platform: iOS
OS: 10.0.1
ID: 6454BC20-6999-4D33-90FC-B0E6FC24C890

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.36 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.63 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.27 Enabled=YES

**Comment by Alex-302** [comment]
Can't access to mobile version. Do you know how to do it?
