### ISSUE TITLE
http://www.spiegel.de/ - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3373]
http://www.spiegel.de/wirtschaft/unternehmen/deutsche-telekom-prueft-angeblich-rueckzug-aus-grossbritannien-a-1119852.html

Managed to reproduce:

![file_000](https://cloud.githubusercontent.com/assets/15856304/20111714/e719f6ce-a5f1-11e6-9844-d0d8a524d200.png)

<details>

Application version: 1.1.1.54
Application lifetime: 2016-03-08 22:14:45 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.5
ID: AAA99C6E-70E0-4BDF-83A9-447D37A96943

Locale: de
Region: de

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.99.56 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.79 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.24 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.6.2 Enabled=YES
ID=6 Name="German filter" Version=1.0.28.17 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.62 Enabled=YES
ID=101 Name="EasyList" Version=1.0.64.39 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.64.56 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.60.50 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.48 Enabled=NO
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
ID=204 Name="Peter Lowe's list" Version=1.0.2.46 Enabled=YES
ID=205 Name="Schacks Adblock Plus liste" Version=1.0.1.59 Enabled=YES

**Comment by Alex-302** [comment]
Added to German filter
```
spiegel.de##div[data-position="outstream"]+div[class]>div[id]
```
//spiegel.de#%#Object.defineProperty(window, 'spBemiOn', { get: function() { return false; } });

**Comment by Bohdan-SUP** [comment]
@Alex-302 looks like it's back again, reported by customer 1444371

**Comment by Alex-302** [comment]
it is clean on my device

**Comment by evgeniy-ADG** [comment]
I've sent a follow-up, will update here later.

**Comment by osavranska** [comment]
It's back again, reported by customer 1469605
Screenshot: http://prntscr.com/dkqp99

**Comment by Alex-302** [comment]
Replaced by
```
spiegel.de##div.adition ~ div[class]:not([data-position]):not([itemscope]) > div > :not(div)[id][class]
```
