### ISSUE TITLE
https://qrz.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3374]
https://qrz.com/db/DG4IX

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/20112083/99bc6bd0-a5f3-11e6-909e-210ae054f071.png)

![image](https://cloud.githubusercontent.com/assets/15856304/20112092/a15bcbf6-a5f3-11e6-8a79-281c700a0f09.png)

Application version: 1.1.1.54
Application lifetime: 2016-11-01 10:28:19 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: 957BC6C7-008D-49FF-B9D3-B38C23C067FB

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.99.42 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.74 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.22 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.6 Enabled=YES
ID=6 Name="German filter" Version=1.0.28.16 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.59 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.61 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.68.35 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.64.51 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.48 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.68.49 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES

</details>

**Comment by Alex-302** [comment]
Added to English filter
```
||qrz.com/ads/
```
