### ISSUE TITLE
[incorect blocking] wiemy.to

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#33740]
After some time or scrolling all page just gone. 
https://wiemy.to/
![scr-1557673623-001](https://user-images.githubusercontent.com/9846948/57584144-618e8980-74d8-11e9-95eb-171b919a997e.png)

[20190512_adguard_filtering_log_records.zip](https://github.com/AdguardTeam/AdguardFilters/files/3170240/20190512_adguard_filtering_log_records.zip)

@AdamWr 

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.0.x Nightly** 
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
| **=== FILTERS ENABLED ===**
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| Fuck Fuckadblock
| **SECTION :: Ads**
| Adguard Base Filter 
| EasyList
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| EasyPrivacy
| Fanboy's Anti-Facebook List 
| Fanboy's Enhanced Tracking List 
| **SECTION :: Social**
| Adguard Social Filter
| Fanboy's Social Blocking List 
| **SECTION :: Annoyances**
| Adblock Warning Removal List
| Adguard Annoyances
| Fanboy's Annoyances 
| I don't care about cookies
| **SECTION :: Security**
| Malware Domains
| Spam404
| NoCoin Filter List 
| **SECTION :: Customs**
| AlleBlock
| EasyList Polish 
| KAD - fraud/scam
| Polish Annoyances Filters
| Polish Anti Adblock List Filters
| Polish Main Filters
| Polish Social Filters

**Comment by AdamWr** [comment]
To najprawdopodobniej wina `Fanboy's Annoyances`, dodaj proszę tę regułę do własnych filtrów:
`wiemy.to#@#.scroll-up`

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/13905

**Comment by krystian3w** [comment]
@ryanbr / @khrin - see https://github.com/AdguardTeam/AdguardFilters/issues/33740#issuecomment-492625823

> This is probably `Fanboy's Annoyances` fault, please add this rule to your own filters:
>
>`wiemy.to#@#.scroll-up`
