### ISSUE TITLE
Google ads are blocked

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3375]
Every time I try to click on a google ad it is blocked! I have Adguard disabled on google but this still happens 

Incorrect blocking on page:
https://www.google.co.uk/search?q=folding+beauty+dish&ie=UTF-8&oe=UTF-8&hl=en-gb&client=safari
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/20113577/97acb45c-a5f9-11e6-85be-1cecbe24a6f3.png)

![image](https://cloud.githubusercontent.com/assets/15856304/20113561/8d758482-a5f9-11e6-8dfc-714d4269a334.png)

The above page appears after clicking the jessops ad circled in the next screenshot

![image](https://cloud.githubusercontent.com/assets/15856304/20113590/a3648798-a5f9-11e6-81f1-c82bd47d5eb7.png)

![image](https://cloud.githubusercontent.com/assets/15856304/20113599/aac60066-a5f9-11e6-9680-1bd31ec48e2b.png)

The above screenshot appears after selecting any of the ebay ads like the one circled below

Application version: 1.1.1.54
Application lifetime: 2016-04-15 17:44:50 +0000

Device: iPad
Platform: iOS
OS: 10.1.1
ID: E4EC5935-DD14-4664-8066-46FB8499C28D

Locale: en
Region: gb

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.93.47 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.55 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.21 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.79 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.22 Enabled=YES
ID=101 Name="EasyList" Version=1.0.62.31 Enabled=YES

**Comment by Bluscream** [comment]
@evgeniy-ADG Just cause i'm curious, how do you add spoilers on Github?

**Comment by Bohdan-SUP** [comment]
@Bluscream you use ```<details>content</details>```

**Comment by Bluscream** [comment]
Awesome, thanks <3 @Bohdan-SUP

**Comment by Alex-302** [comment]
The shop items are not displayed on my end. 
Give me blocked URLs as text
