### ISSUE TITLE
[Android] Youtube App Ad "Suggested Video" not blocked.

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardFilters#3376]
I was not quite sure wether to drop this here or on the Android repo, so if it's wrong i repost it over there.

So i wonder why the ad on the app (with the yellow label "Werbung") isn't blocked :o

![https://i.gyazo.com/1d903019e2f5d435b5db447650102d5c.png](https://i.gyazo.com/1d903019e2f5d435b5db447650102d5c.png)

**Comment by ameshkov** [comment]
Oh my, that's on me, i was planning to make another Youtube ads diving anyway

**Comment by Bluscream** [comment]
Can i close this as "needs SSL unpinning"?

**Comment by ameshkov** [comment]
Yep:(
