### ISSUE TITLE
nashynogi.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3378]
**Description**: Реклама внизу. 3 ряда баннеров
http://nashynogi.ru/raznoe/remont-obuvi-nabojka-na-kabluk-svoimi-rukami.html

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20131595/23b3c0ea-a667-11e6-98d7-3ba7ac16b0c5.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20131599/2a004004-a667-11e6-9d66-c2d1cfc97474.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20131604/3110cf8a-a667-11e6-934c-18e166eee151.png)

</details>

**Adguard version**: 2.8.40

**Filters list**: 1,2,3,4,11,14

**Operating system**: Андроид

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||s1venus.biz^$third-party
nashynogi.ru##center > a[rel="nofollow"] > img
```
