### ISSUE TITLE
com.shaden.kidssongs ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3379]
**Description**: Реклама при пролистывании песен
https://play.google.com/store/apps/details?id=com.shaden.kidssongs&hl=uk
У меня повторилось
Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20132535/166058f4-a66c-11e6-8344-3de3a7b32742.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20132560/2e895322-a66c-11e6-8266-cce73662ea43.png)

</details>

**Adguard version**: 2.8.40
Качественный. ХТТПС

**Filters list**: 1,2,3,4,5,10,11,14,211

**Operating system**: Андроид

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Хмм. Один раз проскочила, больше не повторяется, и в логе пусто. Баннеры выглядят совсем простыми, возможно встроены.
Можешь попробовать лог записать?

**Comment by vgavrish** [comment]
Хорошо, попробую

**Comment by vgavrish** [comment]
повторила
[debug (10).txt](https://github.com/AdguardTeam/AdguardFilters/files/584006/debug.10.txt)
1-16...1-17

**Comment by Alex-302** [comment]
Куда-то свой телефон ломится подозрительно. Добавил в мобильный
```
||nlog.droid4x.cn^
||mtlog.droid4x.cn^
||log.droid4x.cn^
```
и реклама приложения, наверное:
```
||metrics.adflake.com^
||api.adflake.com/custom^
||adflake.com/banner/
```

**Comment by vgavrish** [comment]
Глянь пож-та тут пользователя лог
[debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/615917/debug.txt)
Проблема была в 21:14

**Comment by Alex-302** [comment]
Судя по логу, всё заблокировано. 
Можно такое правило проверить
```
||api.adflake.com^$app=com.shaden.kidssongs
```
но наблюдать нужно не пять минут, для надёжности.

**Comment by vgavrish** [comment]
> только после добавления правила она исчезла.

**Comment by Alex-302** [comment]
Т.е. это правило помогло?
Добавил
```
||api.adflake.com^
```

**Comment by vgavrish** [comment]
да, помогло
