### ISSUE TITLE
ESPN app - missed ads placeholders

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3380]
**Description**:
For some reason AG leaves empty placeholders in ad spots.

App link:
https://play.google.com/store/apps/details?id=com.espn.score_center&hl=en

User complaint:
> Yes, ESPN app blocks the ad but basically leaves what's best described as a chalk outline of where the ad would be. It's nit picky but it does ruin the experience if I have to scroll down a bit further to read the next article. And ESPN is a bastard and puts these ads after every two or three headlines. I think this is a recent occurrence in the past month or two because I didn't have this issue before.

**Comment by Alex-302** [comment]
Strange. Checked with/without Adguard - placeholders are collapsed.
Could you please ask for screenshot?

**Comment by seanl-adg** [comment]
This should be resolvable only with domain name based blocking, right? I couldn't find an obvious empty ad placeholder.

**Comment by ameshkov** [comment]
User has reported that the issue was resolved by enabling DNS filtering.

Do you have it enabled?

**Comment by seanl-adg** [comment]
No, also enabling it didn't make any noticeable difference on my end.
