### ISSUE TITLE
News modern app

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3382]
**Description**: Реклама в приложении Новости
http://radikal.ru/lfp/s019.radikal.ru/i640/1611/e4/782a15de1f81.png/htm

**Adguard version**: 6.1.258.1302

**Filters list**: 1,2,3,4,5,211
Driver Type: Wfp

**Operating system**: Вин 10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by vvgnovanet** [comment]
Вот этот кусок блокируется
https://api.taboola.com/1.2/json/msn-windowsapps-news-russia/recommendations.get?app.type=desktop&app.apikey=04c37990859dbf24d6b38e15a59a975eaa160145&rec.count=1&rec.type=mix&rec.thumbnail.width=296&rec.thumbnail.height=184&user.session=init&source.type=text&source.placement=article-upnext&source.id=AAk64JV&source.url=https://a.msn.com/r/2/AAk64JV?m=ru-ru&device.id=55C37A8D78354066AE21AE07F105A9FE&Client-AppVersion=4.16.22.0

Таким правилом 
Пользовательский фильтр:
||api.taboola.com/*/json/msn-windowsapps-news-russia/recommendations.get?

**Comment by Alex-302** [comment]
@vvgnovanet привет!
У меня этой рекламы почему-то нет. Это правило блокирует баннер как на скрине?

**Comment by vvgnovanet** [comment]
Здарова Alex !!!
Да, вот это правило у меня чистит эту гадость
||api.taboola.com/*/json/msn-windowsapps-news-russia/recommendations.get?

Но нужно ещё кеш чистить чтобы окончательно пропало.
Сейчас ещё раз прошерстил различными сканерами, заразы нет. Эта реклама уже месяца  3 как висит
Просто достала уже, решил сам разобраться ))).

Вкладка сегодня + если нажать любую новость и пролистать её до конца будет  полоска " следующая новость " вот в ней тоже была реклама.

**Comment by Alex-302** [comment]
Ок, тогда добавляю в англ фильтр. Расширю до
```
||api.taboola.com/*/json/msn-windowsapps-*/recommendations.get?
```

**Comment by Alex-302** [comment]
@vgavrish нужно чтоб юзер проверил. Про чистилку из комментария выше тоже нужно сказать.

**Comment by vgavrish** [comment]
ок, это за кэш?

**Comment by Alex-302** [comment]
Да, про очистку кэша,

**Comment by vgavrish** [comment]
отписала

**Comment by vvgnovanet** [comment]
vgavrish, спасибо. Это я с вами по почте общался ))
Правило работает.
Спасибо !!!

**Comment by Serzh-SUP** [comment]
@Alex-302 @vvgnovanet 
Да, ситуация странная. Я также проверял и отключал Adguard, рекламы нет, что так, что так.
Если все работает, тогда закрываем задачу.

@vvgnovanet приносим извинения, за неудобства и долгую переписку, но нам нужно было отсекать поочередно все варианты.
