### ISSUE TITLE
Yandex direct

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3383]
**Description**: 

> Мне надо чтобы у меня ПОКАЗЫВАЛАСЬ реклама Яндекс Директ. Не на какой тоодной площадке, а вообще везде показывалась. 

Включение фильтра полезной рекламы не дает отображение ни в яндекс поиске, ни в яндекс почте.
6.1.258.1302

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня в поиске разблокировалась. 
http://i85.fastpic.ru/big/2016/1109/a6/8b40922af3c825fb344a0f55b88170a6.png
У тебя повторилась проблема? 
По остальному директу - в редакторе можно ввести в поиск `.yandex.`
и выключить все правила, не содержащие @@ и #@#

**Comment by vgavrish** [comment]
у меня в поиске отобразилась
а правила выключать в Полезной рекламе или в Русском фильтре?

**Comment by Alex-302** [comment]
нужно выключить в русском фильтре.

**Comment by vgavrish** [comment]
ок, написала
