### ISSUE TITLE
http://warungbioskop.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3384]
http://warungbioskop.com/

<details>

![image1](https://cloud.githubusercontent.com/assets/15856304/20141541/868dc760-a699-11e6-8d5c-7dfdcaa8f028.png)

![image2](https://cloud.githubusercontent.com/assets/15856304/20141542/87c7748c-a699-11e6-9f3e-2a34024ed6dc.png)

![image3](https://cloud.githubusercontent.com/assets/15856304/20141547/89a3feba-a699-11e6-8e6f-781c2b80362f.png)

Application version: 1.1.2.24
Application lifetime: 2016-10-18 16:47:23 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: B92629AD-9702-4D86-B278-DBC7A239A1B8

Locale: en
Region: id

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.99.89 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.8.83 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.14.29 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.6.13 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.5.61 Enabled=NO
ID=12 Name="Safari filter" Version=1.0.1.64 Enabled=YES
ID=15 Name="Adguard DNS" Version=1.0.0.6 Enabled=YES
ID=101 Name="EasyList" Version=1.0.64.51 Enabled=NO
ID=118 Name="EasyPrivacy" Version=1.0.68.58 Enabled=NO
ID=102 Name="ABPindo" Version=1.0.1.24 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.68.72 Enabled=YES

</details>

**Comment by Alex-302** [comment]
Added to English filter
```
warungbioskop.com##.sponsor
warungbioskop.com##div[class^="iklan"]
```
