### ISSUE TITLE
web.threema.ch

### ISSUE THREAD

**Issue by agentsonny** [AdguardTeam/AdguardFilters#33884]
Hello, 
unfortunately, the input of IP addresses only one day worked. Since then I have to disable AdGuard again to call ThremaWeb.

![Anmerkung 2019-05-16 180513](https://user-images.githubusercontent.com/38537094/57869555-9155ce00-7805-11e9-82ee-3015c85a0443.jpg)

_Originally posted by @agentsonny in https://github.com/AdguardTeam/AdguardFilters/issues/33767#issuecomment-493131693_

**Comment by agentsonny** [comment]
the old thread is web.threema.ch #33767

**Comment by AdamWr** [comment]
Hello,
if these addresses are changing often, then I think the easiest way to fix this issue permanently will be just disable "Block WebRTC" option in Stealth Mode settings.

**Comment by agentsonny** [comment]
Thanks, I unblocked "WebRTC" and it works now :-)

**Comment by AdamWr** [comment]
Ok, I'm glad that it works.
