### ISSUE TITLE
medi-bayreuth.de - Ad - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3388]
**Site**: http://www.medi-bayreuth.de/
**Description**: Ad and several ad leftovers.

**Current behaviour**: Site shows an ad and some ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20157009/17663a2c-a6d3-11e6-8184-ecabf9970e1b.png)

**And:**

![image](https://cloud.githubusercontent.com/assets/10995998/20157053/4a46c736-a6d3-11e6-8594-e1eb24620cff.png)

</details>

______________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.13
Spyware filter 1.0.8.89
Social media filter 1.0.14.35
Annoyances filter 1.0.6.26
German filter 1.0.28.27
Mobile ads filter 1.0.5.63
Safari filter 1.0.1.66

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
I see only leftovers without ads.
Please check:
```
medi-bayreuth.de##.banner
```

**Comment by danidoedel** [comment]
@Alex-302 Yes that works. Thank you!

**Comment by Alex-302** [comment]
Added.
