### ISSUE TITLE
http://m.qidian.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3392]
http://m.qidian.com/

![1](https://cloud.githubusercontent.com/assets/15856304/20192836/2c64e862-a794-11e6-808f-109305f409a7.jpg)

![2](https://cloud.githubusercontent.com/assets/15856304/20192862/487870fa-a794-11e6-9de1-716ecb1a5116.jpg)

<details>
Application version: 1.1.1.54
Application lifetime: 2016-05-18 08:11:09 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: 5AF379C0-719F-488A-9B96-A1200FAFE288

Locale: zh
Region: cn

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.98.90 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.57 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.4 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.30 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.45 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.56 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.68.26 Enabled=YES

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
m.qidian.com##.fixBox > div.popup_box_bg
m.qidian.com##.fixBox > div.fixbg
m.qidian.com##.app_download_ad
m.qidian.com##.app_download_blank_show
```

**Comment by evgeniy-ADG** [comment]
http://m.qidian.com/book/bookreader.aspx?bookid=1002202256&chapterid=280960845

![2016111401](https://cloud.githubusercontent.com/assets/15856304/20272805/bf45ec52-aa97-11e6-8fdd-689fdfbfbc74.jpg)

<details>
Basic + EL China

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
m.qidian.com##.read_app_download
```
