### ISSUE TITLE
http://www.autoblog.com - sponsored content / ads / social media widget

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3393]
http://www.autoblog.com/2016/11/10/california-clean-vehicle-rebate-funds-given-to-wealthy/

![file_000](https://cloud.githubusercontent.com/assets/15856304/20193080/1a1ba2da-a795-11e6-9c8c-d38151d82e59.png)

<details>
Application version: 1.1.1.54
Application lifetime: 2015-10-23 19:40:41 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: 1159ED3C-6BFE-417F-AB08-8543A97C33CD

Locale: en
Region: ca

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.97.76 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.20 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.65 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.89 Enabled=NO
ID=12 Name="Safari filter" Version=1.0.1.52 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.1.53 Enabled=NO

**Comment by Alex-302** [comment]
Added to English filter
```
autoblog.com##.grv-related
```
