### ISSUE TITLE
kedrovaja.ibord.ru - missed ads

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3396]
## Реклама на сайте [kedrovaja.ibord.ru](kedrovaja.ibord.ru) 
<details>

![2016-11-11_09-28-07](https://cloud.githubusercontent.com/assets/16462533/20207689/bfe33b4a-a7f1-11e6-840f-09d13d145119.png)
</details>

## Фильтры:
<details>

**Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский**

**Comment by Alex-302** [comment]
У себя проверял? Реклама блокируется двумя очень старыми правилами.
