### ISSUE TITLE
http://grammarist.com/ - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3397]
http://grammarist.com/spelling/gray-grey/

![image](https://cloud.githubusercontent.com/assets/15856304/20225616/fa436cf0-a84c-11e6-86d8-b0fafa69b62c.png)

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/20225631/0e5d2bc2-a84d-11e6-80f5-1f9feed55bf0.png)

**Comment by Alex-302** [comment]
Added to English filter
```
||asdorka.com^$third-party
||d3noqwmgo39at7.cloudfront.net^
grammarist.com###content > center > div[id^="div-gpt-ad"]+div[align="center"]

```
