### ISSUE TITLE
http://m.qu.la

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3402]
Missed banner on the bottom of the page 
http://m.qu.la/book/903/

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/17504743/20235159/5ce4afea-a893-11e6-9c00-26f4b97a6b06.png)
</details>

**Adguard version**: 1.1.1.54

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.52 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.95 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.34 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.4.97 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.9 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.44 Enabled=YES
ID=101 Name="EasyList" Version=1.0.63.38 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.66.64 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.66.95 Enabled=YES

**Operating system**: iOS 10.0

Reproduced in desktop Safari.

Customer ID: 1359009

**Comment by Alex-302** [comment]
Added to English filter
```
||ppco.trwba.com^$third-party
||5568.gjghy.com^$third-party
```

**Comment by dzamyshlyayeva** [comment]
looks like it's back

<descrption>
![screen shot 2016-11-26 at 1 10 01 pm](https://cloud.githubusercontent.com/assets/23372054/20639943/438319a4-b3da-11e6-8dcf-f3903049c35c.png)
</description>

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.12 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.13 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.72 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.6.82 Enabled=NO
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=NO
ID=5 Name="Experimental filter" Version=1.0.26.31 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.5.88 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.70 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.19 Enabled=NO
ID=104 Name="EasyList China" Version=1.0.69.77 Enabled=YES

Customer ID:1453776

**Comment by Alex-302** [comment]
Not reproduced.
