### ISSUE TITLE
experts-exchange.com

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#34046]
[https://www.experts-exchange.com/questions/29141515/Windows-2003-server-share-can-be-accessed-by-some-users-and-not-others.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.experts-exchange.com/questions/29141515/Windows-2003-server-share-can-be-accessed-by-some-users-and-not-others.html)

 **1**. Скрываются правильные ответы от "экспертов". Показываем:
`experts-exchange.com#$#.interceptReplaceElement { display: block!important; }`

 **2**. Вместо правильного ответа от "эксперта" показывается блок-заглушка с кнопкой триала на 7 дней на фоне фальш-правильного ответа от "эксперта", но размытого.
 Фальш - потому что это картинка, а не текст и меняется она при каждом обновлении страницы. Поэтому - не нужно, скрываем:
`experts-exchange.com##.interceptBackgroundBlocker`

 **3**. Остатки от саморекламы: `experts-exchange.com##.adBanner-comment`

 **4**. Нижний баннер - самореклама: `experts-exchange.com##.ctaSolutionStickyWrapper`

<details><summary>Screenshot's:</summary>

![2019 05 20-1](https://user-images.githubusercontent.com/17948007/57991109-55e12b00-7ab5-11e9-835a-182851bb23f1.png)
----------
![2019 05 20-2](https://user-images.githubusercontent.com/17948007/57991105-4eba1d00-7ab5-11e9-8442-89bf7735dc4c.png)
</details>

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.0.13
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
добавил
