### ISSUE TITLE
[NSFW][ADBLOCK DETECT] xkeezmovies.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#34056]
**Site Sample** | 
----------------|
https://xkeezmovies.com/freetushy-julia-rain-i-blame-my-husband/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1809 x64
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.0.x Nightly** 
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
| **=== FILTERS ENABLED ===**
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| EasyList
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| EasyPrivacy
| Fanboy's Anti-Facebook List 
| Fanboy's Enhanced Tracking List 
| **SECTION :: Social**
| Adguard Social Filter
| Fanboy's Social Blocking List 
| **SECTION :: Annoyances**
| Adblock Warning Removal List
| Adguard Annoyances
| Fanboy's Annoyances 
| Fanboy's Cookiemonster List
| **SECTION :: Security**
| Malware Domains
| Spam404
| NoCoin Filter List 
| **SECTION :: Customs**
| AlleBlock
| EasyList Polish 
| KAD - fraud/scam
| Polish Annoyances Filters
| Polish Anti Adblock List Filters
| Polish Main Filters
| Polish Social Filters

### Issue:

Adblock detect on OPENLOAD player. Click BLUE play button, they will rolling and after while POPUP warning about adblock detection show up. 

**ADGUARD filtering JSON log file:**  
[xkeezmovies.com-adguard.zip](https://github.com/AdguardTeam/AdguardFilters/files/3196668/xkeezmovies.com-adguard.zip)

<details><summary><b>Screenshot:</b></summary>

![scr-1558335776-001](https://user-images.githubusercontent.com/9846948/58002551-f8fa6a80-7ade-11e9-9134-af7171b6b1e6.png)

</details><br/>

@AdamWr

**Comment by Alex-302** [comment]
Not reproduced on my end. Please check without third-party filters.

**Comment by FadeMind** [comment]
@Alex-302  SOURCE ISSUE was **EasyPrivacy Filter**. After removing it all is fine. Weird.

**Comment by Alex-302** [comment]
Not reproduced with this filter:(
Could you please make screenshot of blocked by EasyPrivacy  requests?

**Comment by FadeMind** [comment]
JSON > https://pastebin.com/raw/zBcjJqSe

![scr-1559159867-001](https://user-images.githubusercontent.com/9846948/58587092-d09c0a00-825c-11e9-83d9-3d0d8de45472.png)

**Comment by Alex-302** [comment]
Ok, reported
https://github.com/easylist/easylist/issues/3536
