### ISSUE TITLE
m.focus.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3406]
**Site**: http://m.focus.de/
**Description**: Ad leftover.

**Current behaviour**: Site has some ad leftover at the top and between some articles.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20238671/0b9a85ac-a8f1-11e6-958f-716dbbc9c3ee.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20238684/58b0c19e-a8f1-11e6-9d3b-d3da431b6c8c.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.29
Spyware filter 1.0.8.94
Social media filter 1.0.14.43
Annoyances filter 1.0.6.36
German filter 1.0.28.30
Mobile ads filter 1.0.5.69
Safari filter 1.0.1.68

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
m.focus.de##section#main > article[data-teaser-type="unspecified_group"]
```
