### ISSUE TITLE
filepursuit.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#34069]
`https://filepursuit.com/`

App banner.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.19.2
Firefox 66

**Comment by adranger** [comment]
@AdamWr this one is also displayed to desktop users, by the way.

**Comment by AdamWr** [comment]
Yes, I know and it's blocked by `AdGuard Annoyances filter` for me.

**Comment by adranger** [comment]
Thanks. I hadn't received the update yet and wasn't sure what filter you had added it to.
