### ISSUE TITLE
ariva.de - Ads - Ad leftover - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3407]
**Site**: http://www.ariva.de/
**Description**: Ad leftover, cookie notic and ad articles.

**Current behaviour**: Site has some ad leftover at the top, a cookie notice at the bottom and some ad articles marked with "Anzeige" and "Anzeigen".

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20238746/700f143e-a8f2-11e6-8d8e-e3871ffa083d.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20238758/ab30e682-a8f2-11e6-9bdc-0770515d1d0a.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.29
Spyware filter 1.0.8.94
Social media filter 1.0.14.43
Annoyances filter 1.0.6.36
German filter 1.0.28.30
Mobile ads filter 1.0.5.69
Safari filter 1.0.1.68

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Cookie and leftover are removed. Anzeigen from the second screenshot have the save code as useful columns.
