### ISSUE TITLE
drehscheibe-online.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3409]
**Site**: http://www.drehscheibe-online.de/
**Description**: Ad leftover.

**Current behaviour**: Site has some ad leftover at the top right side.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20238866/ff4f4414-a8f4-11e6-871a-92285cf1435f.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.29
Spyware filter 1.0.8.94
Social media filter 1.0.14.43
Annoyances filter 1.0.6.36
German filter 1.0.28.30
Mobile ads filter 1.0.5.69
Safari filter 1.0.1.68

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to German filter
```
drehscheibe-online.de###dsHeaderColoured
```
