### ISSUE TITLE
netzwelt.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3410]
**Site**: https://www.netzwelt.de/
**Description**: Cookie notice.

**Current behaviour**: Site displays a cookie notice at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20239010/ac30bb16-a8f7-11e6-8ee8-06393687116b.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.29
Spyware filter 1.0.8.94
Social media filter 1.0.14.43
Annoyances filter 1.0.6.36
German filter 1.0.28.30
Mobile ads filter 1.0.5.69
Safari filter 1.0.1.68

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
it will be better if you will put your rules just in issues. It will faster for me)
