### ISSUE TITLE
mytopdeals.net - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3411]
**Site**: https://www.mytopdeals.net/
**Description**: Ad leftover.

**Current behaviour**: Ad leftover on the right side.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20240823/7b783082-a922-11e6-9b9e-6d1e1685e13c.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.32
Spyware filter 1.0.8.95
Social media filter 1.0.14.43
Annoyances filter 1.0.6.36
German filter 1.0.28.30
Mobile ads filter 1.0.5.70
Safari filter 1.0.1.68

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to German filter
```
mytopdeals.net##aside[class$="adsense-widget"]
```
