### ISSUE TITLE
en.oxforddictionaries.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3412]
**Site**: https://en.oxforddictionaries.com/
**Description**: Ad leftover.

**Current behaviour**: Site displays some ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20240831/d2c5d3b2-a922-11e6-8054-b85ae942253c.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.32
Spyware filter 1.0.8.95
Social media filter 1.0.14.43
Annoyances filter 1.0.6.36
German filter 1.0.28.30
Mobile ads filter 1.0.5.70
Safari filter 1.0.1.68

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Fixed
