### ISSUE TITLE
porndr.com [NSFW] [Ads & Pop-ups]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#34130]
**Site**: https://www.porndr.com/videos/9905/first-ever-buttfuck-for-steamy-ginger-haired-nubile-rebecca-rainbow/

**Issue**: Please remove the ads on the video player and other places on the page. Pop-up also seen.

**Screenshot**: http://prntscr.com/nrohrg

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 74.0.3729.169 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 3.0.14 `

**Filters**:
```
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404
NoCoin Filter List

```

**Stealth Mode Settings**:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled

**Comment by Nzzyme** [comment]
https://www.porndr.com/videos/37200/ample-ass-fucking-internal-cumshot-in-funnel/

Ad seen before the video starts playing and unable to play video. Seen on AG for Chrome

https://prnt.sc/q9srcp

**Comment by Alex-302** [comment]
Cannot reproduce.
