### ISSUE TITLE
http://extra.to/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3415]
**Description**: При нажатии в любом месте страницы открывается другой сайт
http://extra.to/torrent/5283284/Doctor+Strange+2016+HD-TS+x264+AC3-CPG.html

**Adguard version**: 6.1

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
