### ISSUE TITLE
www.consumerreports.org

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3417]
**Description**: Incorrect blocking on the page 
http://www.consumerreports.org/cro/index.htm
Unable to open any subsection on the website. 
Works fine if Adguard's off. 

**Adguard version**: 1.1.1.54

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.0.38 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.95 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.43 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.68 Enabled=YES

**Operating system**: both in iOS 10.1.1 and OS X 10.11.6

**Browser**: Safari and Google Chrome

Customer ID 1448562

**Comment by Alex-302** [comment]
Please describe it step-by-step. Checked in Safari some links on the page and in menu - all works fine.

**Comment by Tetiana2020** [comment]
I tried on different computers - all the same: when I go to the site, I can't open any section from the menu and can't open any product page. All the buttons are inactive. 
Here is list of my filters:
![image](https://cloud.githubusercontent.com/assets/17504743/20391181/ec6356a8-acda-11e6-967d-4f27aff7e8e9.png)

**Comment by Alex-302** [comment]
Reproduced in Safari:)
Added to Spyware filter
```
@@||metrics.consumerreports.org/b/ss/cuglobal/
```
