### ISSUE TITLE
250+ Solitaire Collection - ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3418]
1443607
**Description**: Реклама проявляется после завершения пасьянсах до предложения с играть ещё
или выйти. Причём либо появляется после каждого сыгранного пасьянсах, либо не появляется какое-то время
https://play.google.com/store/apps/details?id=com.anoshenko.android.solitaires

Лог:
[debug (4).txt](https://github.com/AdguardTeam/AdguardFilters/files/588972/debug.4.txt)
проблема в 9.21

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20261468/964e9c26-aa66-11e6-891e-71d1e827793d.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20261474/9d52565c-aa66-11e6-8ede-42804277d988.png)

</details>

**Adguard version**: 2.7.220

**Filters list**: 2, 3, 4, 14, 1, 11 
  "filteringQuality" : "FULL",

**Operating system**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Передай на проверку:
```
||alxanosoft.com/rk/
```
Работать будет только с включенной фильтрацией HTTPS.
В фильтр добавил.

**Comment by vgavrish** [comment]
ок, передала
