### ISSUE TITLE
https://www.chaosgroup.com/ - Incorrect Blocking

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3422]
## Не отображается [сайт](https://www.chaosgroup.com/)

![2016-11-14_21-31-03](https://cloud.githubusercontent.com/assets/16462533/20279687/2b37e022-aab2-11e6-98d4-45dff16d61f3.png)

<details>

## Фильтры:

**Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский**
</details>

**Comment by Alex-302** [comment]
Fixed
