### ISSUE TITLE
http://www.realspeaker.net/ru cookies notification

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3423]
**Description**: Cookies notification not blocked on this site
http://www.realspeaker.net/ru 
![image](https://cloud.githubusercontent.com/assets/17504743/20299308/14dcc56a-ab23-11e6-9d54-74a99b0aefaa.png)

Customer ID 1419169

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
realspeaker.net##.s-cookie-notification-bar
```
