### ISSUE TITLE
ondemandkorea.com

### ISSUE THREAD

**Issue by waynesong21** [AdguardTeam/AdguardFilters#34251]
[//]: # https://www.ondemandkorea.com/i-live-alone-e295.html

***Description***:
* **Current behaviour**:
[//]: #  Adguard is getting blocked on iOS. I can't watch any videos on here unless I turn it off.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

<details><summary>Screenshot:</summary>

![IMG_1147](https://user-images.githubusercontent.com/32917426/58362919-d1dec880-7e51-11e9-9b84-3c1734cd83a6.jpeg)

</details><br/>

* **Expected behaviour**: 

[//]: # Plays the video right away and never gets interrupted with ads.

<details><summary>Screenshot:</summary>

![IMG_1147](https://user-images.githubusercontent.com/32917426/58362919-d1dec880-7e51-11e9-9b84-3c1734cd83a6.jpeg)

</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # Go to the url pasted above and you'll see the message. I'm using iPhone 7 Plus. iOS version 12.1.2

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | iOS
Operating system version (Android/iOS) | 12.1.2
Browser:                               | Safari
AdGuard version:                       | 2.1.2(101)
Filters enabled:                       | Adguard base, Adguard Mobile Ads, Easy List, Peter Lowe's, Adblock Warning Removal, Adguard Safari, Korean, Adblock List.
Simplified filters (iOS only)          | On / Off idk what this is.
AdGuard DNS:                           | Default
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@waynesong21 Hi. Sorry for the late reply. 
I cannot access to this site with our and public proxy.

![image](https://user-images.githubusercontent.com/8361299/58564248-47251180-8235-11e9-869d-ee5834ae3880.png)

Could you, please, provide remote access?
