### ISSUE TITLE
trialeset.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3426]
**Description**: пропуск рекламы (баннеры с рекламой вулкана и тд)

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20306056/3e591fb0-ab41-11e6-8151-4005434eefd5.png)

</details>

**Adguard version**: 2.8.40

**Filters list**: 1,2,3,4,14,11,211

**Operating system**: Андроид

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не повторилось. Нужен лог с указанием времени.

**Comment by vgavrish** [comment]
написала

**Comment by vgavrish** [comment]
[debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/598511/debug.txt)
время 00-13

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||skidl.ru^$third-party
```
ещё надо проверить

**Comment by Alex-302** [comment]
@vgavrish можно ещё попробовать установить бету, и в низкоуровневых настройках добавить порт 8040 в список фильтруемых в `pref.filtered.ports`
У меня почему-то не повторяется уже, даже без добавления порта.

**Comment by vgavrish** [comment]
ок, отписала

**Comment by vgavrish** [comment]
правило не помогло, как и установка беты и настроек
новый лог
[debug (3).txt](https://github.com/AdguardTeam/AdguardFilters/files/611279/debug.3.txt)

>пропуск идет по правой колонке , раньше было по всему сайту.

**Comment by Alex-302** [comment]
странно. Чётко вижу, что рекламный запрос заблокирован(тот самый веб-сокет)
`TCP id=100507 GET ads=1 "ws://et-code.ru:8040/`
но не вижу запросов ресурсов страницы.
Может закэшировалась реклама? Нужно очистить кэш браузера и попробовать снова.

**Comment by vgavrish** [comment]
ок, написала
