### ISSUE TITLE
http://www.heavy-r.com - pop-up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3428]
Missed ad on page:
http://www.heavy-r.com/free_porn/bigcock.html

<details>

![image1 2](https://cloud.githubusercontent.com/assets/15856304/20308823/3caf7d78-ab4e-11e6-8dd6-296c3b3b6c69.png)

![image2 2](https://cloud.githubusercontent.com/assets/15856304/20308824/3da2620e-ab4e-11e6-9bbf-a4d831e417f8.png)

</details>

state
<details>
Application version: 1.1.1.54
Application lifetime: 2016-11-14 00:19:05 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: 83E670EE-CD08-4266-B6CF-A08F641AA726

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.0.41 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.96 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.45 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.6.39 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.71 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.68 Enabled=YES

**Comment by Alex-302** [comment]
I can't reproduce.
@seanl-adg could you check it?
