### ISSUE TITLE
http://www.phonearena.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3430]
Incorrect blocking on page:
http://www.phonearena.com/

Cannot login to this website when Adblock Is on

<details>
Application version: 1.1.1.54
Application lifetime: 2016-11-14 16:15:53 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.5
ID: 3A1F01DF-5EC9-45BD-BB9C-2DF5C10E7044

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.0.50 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.98 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.48 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.68 Enabled=YES
</details>

confirmed, it won'tlet us sign in or register an acc

**Comment by Alex-302** [comment]
Added to English filter
```
phonearena.com#@#.s_mb_10
```
