### ISSUE TITLE
m.wxrw123.com [nsfw]

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#3432]
**Description**: fullscreen pop-up 
http://m.wxrw123.com/show-105-3939367-0.html

Happens both with Adguard and Adguard PRO.

Screenshot: <details>
![screen shot 2016-11-15 at 5 46 45 pm](https://cloud.githubusercontent.com/assets/23372054/20312253/7855b22c-ab5b-11e6-8108-8e6d39073bb8.png)
</details>

**Adguard version**: 1.1.2.24

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.0.47 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.98 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.45 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.6.40 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.73 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.68 Enabled=YES
ID=101 Name="EasyList" Version=1.0.64.70 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.69.12 Enabled=YES

**Operating system**: iOS 10

**Browser**: Safari

Customer ID - 1449435

**Comment by Alex-302** [comment]
fixed
