### ISSUE TITLE
youtube.com - Annoyance

### ISSUE THREAD

**Issue by a-ladanov** [AdguardTeam/AdguardFilters#3433]
https://www.youtube.com/watch?v=IZyIBK2HH5I
Какой-то новый вид аннотаций появился на youtube
Фильтр раздражителей подключен, но не помогает.
![default](https://cloud.githubusercontent.com/assets/18179397/20313721/9eb07d30-ab79-11e6-9df6-255744ea5591.png)

**Comment by Alex-302** [comment]
Мы аннотации не блокируем фильтром раздражителей.
Можете добавить
```
youtube.com##.ytp-ce-element
```

**Comment by vgavrish** [comment]
Как то так получилось, что в один момент начали блокироваться аннотации Фильтром раздражителей
С фильтром - http://prntscr.com/detegm
Без - http://prntscr.com/detepj
https://www.youtube.com/watch?v=CjPsq6D5nC4

**Comment by Alex-302** [comment]
Поправил.

**Comment by a-ladanov** [comment]
Ну и что? Все анотации повылазили.
А это и есть раздражитель - всплывают когда видео еще идет.
Отключайте фильтр раздражителей.

**Comment by Alex-302** [comment]
Вообще мы и не должны были их блокировать.
Для этого есть отдельный фильтр
https://youtube.adblockplus.me/

**Comment by a-ladanov** [comment]
Да с этими аннотациями всегда беда была.
То мы не блокируем, то в русском фильтре, то в экспериментальном,
недавно в фильтре раздражителей, теперь опять не блокируем.
Начальство же за то, чтобы блокировались в фильтре раздражителей:
1)
https://forum.adguard.com/index.php?threads/resolved-youtube-annotations.6113/#post-95819
2)
https://forum.adguard.com/index.php?threads/%D0%A4%D0%B8%D0%BB%D1%8C%D1%82%D1%80-%D1%80%D0%B0%D0%B7%D0%B4%D1%80%D0%B0%D0%B6%D0%B8%D1%82%D0%B5%D0%BB%D0%B5%D0%B9.10831/#post-84879

Если ситуация спорная - обращаемся к политике составления правил:

> Собственная реклама веб-сайтов не должна удаляться специально. С другой стороны, она не должна быть разблокирована, если ее разблокировка может привести к появлению рекламных объявлений третьей стороны.

Разве не подходит этот пункт?
Сделайте пометку, может @ameshkov заглянет сюда.

**Comment by Alex-302** [comment]
Хм, попутал значит. 
Вернул
```
youtube.com##.ytp-ce-element
youtube.com##.video-annotations
||youtube.com/annotations_invideo?$object-subrequest
```

**Comment by vgavrish** [comment]
А мы "Watch Now" можем блокировать?

Вот в этом видео: https://www.youtube.com/watch?v=Yf_Lwe6p-Cg
С Расширением и Раздражителем появляется: http://prntscr.com/dskey9
Ф: 1,2,3,4,14
ВИН (Хром), МАК (Сафари)

**Comment by Alex-302** [comment]
Добавил в фильтр раздражителей
```
youtube.com##.annotation.iv-promo
```
