### ISSUE TITLE
PIP Camera-Photo Editor Pro - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3434]
https://play.google.com/store/apps/details?id=com.pipcamera.activity&hl=en

<details>
![screenshot_2016-11-14-12-37-49-076_com pipcamera activity](https://cloud.githubusercontent.com/assets/15856304/20316290/e8113556-ab69-11e6-99ef-6d98de9c56fa.png)

![screenshot_2016-11-14-12-35-12-554_com pipcamera activity](https://cloud.githubusercontent.com/assets/15856304/20316292/e8fd605c-ab69-11e6-8bb3-e8b0efb8f3e3.png)
</details>

SSL, HQ
Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский

**Comment by Alex-302** [comment]
Они встроены, не убрать.
