### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by Kujawskie** [AdguardTeam/AdguardFilters#34362]
***Opis/description***: Ta strona internetowa, pomimo zgłoszenia problemu w wątku #24384 (z dnia 25.10.2018 r.), wciąż wyświetla komunikaty RODO. Ponadto istnieje problem z reklamami, które nie są blokowane przez wtyczkę, jedynie nadal są wyświetlane na stronie, przy czym poniekąd dzieje się to w różnych miejscach, więc przy usuwaniu za pomocą zaznaczania elementów i tworzenia filtrów kosmetycznych można przypadkiem usunąć okienko normalnie działające prawidłowo. 
Próbowałem rozwiązać ten problem na własną rękę, i prawdopodobnie znalazł się skrypt, który wysyła reklamy (||*.wp.pl/4lK28MhTVxwjbUs5DHtDHCFBVCQKe0McIUFUJAp5RwsqQhYnG2tRXBwKfSIlMmEeAWFdeAkyBAMgZHIDAiUENgx0cn8-G0ElD3xOPiYaDFgeUEgqMi5fCgl2UCsYLUVec2FLAF8gexgvRlQIDD5xOjJ7WTlfEk4fBHtgBTgndhsNXmsaXBFVGD51bHQNOm4LGGoMLic-dQh8YX08AzpnXg5gQAUEN20kM0ZUIR8WWgopSA0YXBVaXRwFaQhYAHwoLV1fJi8sRV8SYg08XSICCH9iCiIaBwE4DnQBCQkwfDUSeVceDiVOBDN8dnonO3MtPFNIJTAFQ1QTWFMdAQVENA8KfTpcAWQlMQZUChsTXz98Y38uLWZ6NB1iDTovHEU8M1dzFxkXYSEPegwDUBt_WwRFSQxcIXoOJwtafycWQyd4BVIBGh8ANR16chwGPgMlDABSDDIXehYvfgAvLhNlJXJfTQQvaQU=/*$script,domain=www.wp.pl), chyba celowo tak zagmatwana nazwa, z tym że:
-po nim pozostają widoczne miejsca, gdzie te reklamy miały być, czego nie mogłem usunąć;
-nie mam pewności, czy nie zmienią nazwy nawet jutro, bo tak się zdarza z innymi skryptami na domenach *.wp.pl;
-strona dość często, w ok. 40% przypadkach, zwłaszcza jak za mocno zacznie się przewijać stronę, przestaje poprawnie się odtwarzać i proponuje przejść do wersji statycznej, gdzie z kolei już działa dobrze
-reklamy rzadko, ale dają się przemycić.
Problem dotyczy Firefoksa oraz Google Chrome.

Despite the problem of showing GDPR infoboxes was reported on Oct 25 2018 (thread #24384), the webpage still manages to bypass the filters. There is also a problem with advertisements, which are not being blocked by the uBlock Origin browser extension. What's more, they tend to appear in different places, so when you try to delete the ads by adding cosmetic filters, you might also filter an innocent element of the webpage. 
I tried to fix the problem myself and I have probably found the script which sends ads (shown above), but:
- after blocking this script, there still remain placeholders for ads, which I haven't managed to remove;
- I'm not sure whether the script name will be the same tomorrow, since they change their names on other domains of style *.wp.pl
- the page, having this script blocked, often (in around 40% of cases) crashes, especially when you scroll through the page too fast. It offers you to go to the static version, which works perfectly fine (and without ads).
- ads do happen to bypass the block
This concerns Firefox and Google Chrome.

***Steps to reproduce the problem***: Just enter wp.pl via Firefox or Google Chrome
Find the script mentioned above and block it. If the script's name has changed, try to block other ones.

***System configuration***

**Filters:** 
"selectedFilterLists": [
    "https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/anti-adblock.txt",
    "RUS-0",
    "POL-2",
    "POL-0",
    "plowe-0",
    "fanboy-social",
    "fanboy-annoyance",
    "fanboy-cookiemonster",
    "adguard-social",
    "adguard-annoyance",
    "malware-1",
    "malware-0",
    "easyprivacy",
    "adguard-spyware",
    "easylist",
    "adguard-mobile",
    "adguard-generic",
    "ublock-unbreak",
    "ublock-abuse",
    "ublock-privacy",
    "ublock-badware",
    "ublock-annoyances",
    "ublock-filters",
    "user-filters"
  ]
Information                            | Value
---                                    | ---
Operating system:                      | Windows 7
Operating system version (Android/iOS) | ?
Browser:                               | Firefox 67.0
AdGuard version:                       | 2.0.51.1
Filters enabled:                       | 
AdGuard DNS:                           | ?
Stealth mode options (Windows only)    | ?

**Comment by bogachenko** [comment]
Blocking such scripts will not lead to anything (in such scripts, in addition to advertising, there are vital site functions), you need to go into the scripts themselves and watch how to disable fucking ads.

However, so if you want to add this regexp, this site uses advertising cookies, the address of these scripts changes in random order (it will block these scripts, but again, it may break something necessary. See for yourself.)

`/^https?:\/\/www\.wp.pl\/[^\s]{470,}\D/$script,domain=www.wp.pl`

**Comment by AdamWr** [comment]
>Ta strona internetowa, pomimo zgłoszenia problemu w wątku #24384 (z dnia 25.10.2018 r.), wciąż wyświetla komunikaty RODO. Ponadto istnieje problem z reklamami, które nie są blokowane przez wtyczkę[...]

Niestety nie potrafię tego odtworzyć, zarówno RODO, jak i reklamy są u mnie zablokowane.

>Filters:
[...]
"ublock-"

Z jakiego rozszerzenia do blokowania reklam korzystasz?

**Comment by krystian3w** [comment]
uBlock Origin, niestety trzeba było wycofać kilka filtrów `set-constant.js`, bo psuły np. komentarze...

**Comment by krystian3w** [comment]
W uBO niestety nie da się łatwo skonwertować skryptu AdGuardowego ani nikt nie chce wziąć na brzemię problemów niby z Gemius:

```
||wp.pl/*-FwkqOxhmGz4XCSo7GGYbPhcJKjsYZhs-$script,domain=~pilot.wp.pl
```

A opcja wycinając go kosmetycznie odpada, dalej wtedy nie działa odtwarzacz na skrypcie WP/nie odtwarza się `open.fm`.
