### ISSUE TITLE
macrumors.com - Ad leftover - mobile

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3436]
**Site**: http://www.macrumors.com/
**Description**: Ad leftover on mobile devices.

Rules: 

```
macrumors.com###adTop_mobile
macrumors.com###adUnder_mobile
macrumors.com###adUnder2_mobile
```

(I'm sure these two "adUnder" rules can be combined somehow.)

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20325395/be8f5670-ab84-11e6-86bf-7c64911fd180.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.64
Spyware filter 1.0.9.3
Social media filter 1.0.14.52
Annoyances filter 1.0.6.53
German filter 1.0.28.42
Mobile ads filter 1.0.5.75
Safari filter 1.0.1.68

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by seanl-adg** [comment]
The element with id "adTop_mobile" already has the height 0px, and hiding it does not make any visible changes of the page, so I didn't hide it.
