### ISSUE TITLE
frustfrei-lernen.de - Ad - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3437]
**Site**: http://www.frustfrei-lernen.de/
**Description**: Ad leftover and ad.

Rules for leftovers:

```
frustfrei-lernen.de##.noContentBannerAd
frustfrei-lernen.de##.tandem_top
```

Not sure how to block the ad marked in the screenshot.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20325877/b8f0a424-ab86-11e6-8bc8-b9a1ddde7524.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20325909/d75ff590-ab86-11e6-80b5-8719a070903b.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.64
Spyware filter 1.0.9.3
Social media filter 1.0.14.52
Annoyances filter 1.0.6.53
German filter 1.0.28.42
Mobile ads filter 1.0.5.75
Safari filter 1.0.1.68

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by seanl-adg** [comment]
I am not sure whether the text "Anzeigen:" and the image below it should be blocked. Are they actually ads? I am asking because it is a link to their own page and hiding "Anzeigen:" text will require a JS rule which could be dangerous.

**Comment by danidoedel** [comment]
@seanl-adg The image is indeed NOT an ad. My fault :O
But the text "Anzeigen:" is some ad leftover...

**Comment by seanl-adg** [comment]
@danidoedel Check this rule: 
```
frustfrei-lernen.de#%#AG_onLoad(function(){document.getElementsByClassName("contentBody")[0].innerHTML = document.getElementsByClassName("contentBody")[0].innerHTML.replace(/Anzeigen:<br>\s*<script [\s\S]*?>\s*?\/\/dupZwOX[\s\S]*?<\/script>/, "");});
```
It hides the text after the page is loaded. Do you prefer to have this rule in spite of the flickering?

**Comment by danidoedel** [comment]
@seanl-adg That rule works fine I would say. But it's still there on mobile devices: 
![image](https://cloud.githubusercontent.com/assets/10995998/20390853/e78b33a8-acd0-11e6-840b-f8f6e54c10be.png)
