### ISSUE TITLE
parentherald.com - Ad - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3438]
**Site**: http://www.parentherald.com/
**Description**: Ad and Ad leftover in articles.

Rules:

```
parentherald.com##.at-sns
parentherald.com##.at-comt
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20326155/e384f0d6-ab87-11e6-8055-d20367306684.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20326190/ff22e2ee-ab87-11e6-91f8-5db41791ba4d.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.64
Spyware filter 1.0.9.3
Social media filter 1.0.14.52
Annoyances filter 1.0.6.53
German filter 1.0.28.42
Mobile ads filter 1.0.5.75
Safari filter 1.0.1.68

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by seanl-adg** [comment]
The required rule `|ws*://$domain=parentherald.com` was added to English filter from other sources.
