### ISSUE TITLE
spiegel.de

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3439]
**Site**: http://www.spiegel.de/
**Description**: Lots of whitespace under article on mobile devices (whitespace also on non-mobile devices, but not that huge). Example article: http://www.spiegel.de/politik/deutschland/hans-georg-maassen-weist-vorwuerfe-der-tuerkei-zur-pkk-zurueck-a-1121460.html

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20326461/2f262432-ab89-11e6-9966-779499bbcef3.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.64
Spyware filter 1.0.9.3
Social media filter 1.0.14.52
Annoyances filter 1.0.6.53
German filter 1.0.28.42
Mobile ads filter 1.0.5.75
Safari filter 1.0.1.68

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to German  filter
```
spiegel.de###spRecommendations
```
