### ISSUE TITLE
http://the-watch-series.to - incorrect blcoking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3443]
http://the-watch-series.to/cale.html?r=aHR0cDovL3ZvZGxvY2tlci5jb20vbzF0OXc1OW5iZDM4

With Adguard don't have click to play

![image1](https://cloud.githubusercontent.com/assets/15856304/20352427/e5310468-ac1f-11e6-8ba6-4ac20739e090.png)

<details>
Application version: 1.1.1.54
Application lifetime: 2016-11-10 11:18:47 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: C0871370-BAF6-4FF7-83F4-2BF9F8319A27

Locale: en
Region: us

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.0.16 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.89 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.35 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.66 Enabled=YES

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||static.the-watch-series.to/public/js/
```
