### ISSUE TITLE
http://tmxc.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3444]
http://tmxc.ru/url/create.php

![image](https://cloud.githubusercontent.com/assets/15856304/20360237/a478220a-ac3b-11e6-810a-9c7c749957b2.png)

![image](https://cloud.githubusercontent.com/assets/15856304/20360286/d2fd902e-ac3b-11e6-995f-45d2d562113c.png)

Please consider removing these particular buttons from the social media filter

**Comment by Alex-302** [comment]
doesn't work even without Adguard.
http://img.ii4.ru/images/2016/11/17/792100_kiss_16kb.png
http://img.ii4.ru/images/2016/11/17/792101_kiss_7kb.png
\
