### ISSUE TITLE
madeleine.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3445]
**Site**: https://www.madeleine.de/
**Description**: Cookie notice.

Possible rule:
`madeleine.de###AcceptCookiesBannerTemplate`

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20368553/d3d6a5b2-ac54-11e6-80c4-f6a6dc19925d.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.77
Spyware filter 1.0.9.4
Social media filter 1.0.14.56
Annoyances filter 1.0.6.59
German filter 1.0.28.47
Mobile ads filter 1.0.5.78
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added
