### ISSUE TITLE
gutefrage.net - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3446]
**Site**: http://www.gutefrage.net/
**Description**: Some questions on this site have an ad as answer (e.g. http://www.gutefrage.net/frage/von-blut-bzw-plasmaspenden-narben)

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20368796/dcfd702a-ac55-11e6-898b-7b8efc679725.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.77
Spyware filter 1.0.9.4
Social media filter 1.0.14.56
Annoyances filter 1.0.6.59
German filter 1.0.28.47
Mobile ads filter 1.0.5.78
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Not shown at the moment

**Comment by danidoedel** [comment]
@Alex-302 It's there again:
![image](https://cloud.githubusercontent.com/assets/10995998/20433036/3274fd28-ada2-11e6-8d7b-3b9223f58ca5.png)

**Comment by Alex-302** [comment]
Nothing. Need remote access.

**Comment by danidoedel** [comment]
@Alex-302 Yep it's not there again. It seems that changes every day... :(
