### ISSUE TITLE
Question: Possible to block Taboola content on all websites?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [AdguardTeam/AdguardFilters#34465]
For example here:
https://www.gadgety.co.il/
Or more specifically on its articles. Example:
https://www.gadgety.co.il/231015/dell-xps-13-computex-2019/

**Comment by Alex-302** [comment]
hi. You can use these rules in custom filter:
```
##[id^="taboola"]
##[class^="taboola"]
||taboola.com^$third-party
```

**Comment by Alex-302** [comment]
Also you can enable `AdGuard Tracking Protection filter`, which block Taboola.

**Comment by AndroidDeveloperLB** [comment]
Isn't this filter just for anti-tracking itself, and not blocking the content?

**Comment by Alex-302** [comment]
taboola is used not for advertising only, so we make domain specific rules.

**Comment by AndroidDeveloperLB** [comment]
It is used as clickbait articles which have ads...

**Comment by Alex-302** [comment]
Not clickbait  only. Many popular sites uses it for their own articles, as "recommended"

**Comment by AndroidDeveloperLB** [comment]
It's the same. They put links that have nothing to do with the current article, sometimes of old ones, and in bad places on the website too.

**Comment by Alex-302** [comment]
Spyware filters blocks it anywhere.

**Comment by AndroidDeveloperLB** [comment]
I don't understand. You mean there is already a filter here?

**Comment by Alex-302** [comment]
Yes, it block Taboola as analytics.

**Comment by AndroidDeveloperLB** [comment]
What is "it" ? Which filter exactly?

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/58736585-0bda3c80-8407-11e9-8fc6-ac14ea22cee5.png)
new name of that filter is `AdGuard Tracking Protection filter`

**Comment by AndroidDeveloperLB** [comment]
But why call it "web analytics tools", if it also blocks ad-content?

**Comment by ghajini** [comment]
>
>
>Many popular sites uses it for their own articles, as "recommended"

Then why your view differs here

https://github.com/AdguardTeam/AdguardFilters/issues/31432

Taboola sponsored legit (site depending on taboola for serving legit articles) articles NOT ADS

**Comment by AndroidDeveloperLB** [comment]
@ghajini Why do you think those are legit? They take a lot of space on the screen out of the content, not related to the article, and cannot be turned off.
They are ads for inside the website. Still ads.
I don't need suggestions of "You might be interested in" of articles from long time ago either.
There are much better ways to search for similar articles : Search-field, tags, and if you want to search globally , use Google.
