### ISSUE TITLE
digitalfernsehen.de - Ad - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3447]
**Site**: http://www.digitalfernsehen.de/
**Description**: Ad and Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20368902/6cd86808-ac56-11e6-882b-ca2c081269b2.png)

**Forum (https://forum.digitalfernsehen.de/):**

![image](https://cloud.githubusercontent.com/assets/10995998/20368973/d66c1c56-ac56-11e6-8bc6-2828fdb8c0f8.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20369000/00ff4f88-ac57-11e6-8613-c253c1486b85.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.77
Spyware filter 1.0.9.4
Social media filter 1.0.14.56
Annoyances filter 1.0.6.59
German filter 1.0.28.47
Mobile ads filter 1.0.5.78
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
1. Check
```
digitalfernsehen.de##.white_anzeige
```
2. Right column is not shown on my end

**Comment by danidoedel** [comment]
1. That rule does block the ads at the right side.
2. There is then some ad leftover space:
![image](https://cloud.githubusercontent.com/assets/10995998/20395052/e4c3fc7a-ace1-11e6-849b-e1582ac74e50.png)
To block that, these rules could be added: 

```
digitalfernsehen.de###c206811
digitalfernsehen.de###c265197
digitalfernsehen.de###c5046
digitalfernsehen.de###c98969
digitalfernsehen.de###c5052
digitalfernsehen.de###c206828
```

But I don't know if that's a proper way to block that or these ids aren't unique...

3 . That stuff in the forums isn't blocked yet. To block the part on the bottom right this rule could be added: `digitalfernsehen.de##.section.infoBlock.sharePage`
Not sure how the small part at the top right could be blocked:

![image](https://cloud.githubusercontent.com/assets/10995998/20395307/b7e662f0-ace2-11e6-9281-597b6d73c984.png)

4. And there is some social leftover after articles:

![image](https://cloud.githubusercontent.com/assets/10995998/20395466/5521832e-ace3-11e6-8bd6-5feaf9a8ecc3.png)

Could be blocked with `digitalfernsehen.de##.service_zeile_unten`

What an annoying site :D

**Comment by Alex-302** [comment]
Added to German filter
```
digitalfernsehen.de##.white_anzeige
digitalfernsehen.de###right_boxes_two > div.content_box_right[-ext-has=".white_anzeige"]

```

**Comment by danidoedel** [comment]
@Alex-302 
Social widget leftover below article (http://www.digitalfernsehen.de/Neujahrsgewinnspiel-Standlautsprecher-von-Teufel-gewinnen.148613.0.html):

![image](https://cloud.githubusercontent.com/assets/10995998/21981886/d47487b8-dbe9-11e6-9803-4effc236892e.png)

Ad leftover in first post of each page in forums (https://forum.digitalfernsehen.de/threads/umzug-ben%C3%B6tige-hilfe.371158/):

![image](https://cloud.githubusercontent.com/assets/10995998/21981910/fe3aa1ae-dbe9-11e6-8358-24ed5052c51a.png)

**Comment by Alex-302** [comment]
fixed
