### ISSUE TITLE
ipadforums.net - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3448]
**Site**: http://www.ipadforums.net/
**Description**: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20369086/71ba43ea-ac57-11e6-9f4b-cb6c722a244a.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20369100/85968090-ac57-11e6-8b04-249dd43a44b8.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.77
Spyware filter 1.0.9.4
Social media filter 1.0.14.56
Annoyances filter 1.0.6.59
German filter 1.0.28.47
Mobile ads filter 1.0.5.78
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to English filter
```
ipadforums.net##.pageContent > div.sectionMain.funbox
ipadforums.net##.mainContent > div.sectionMain.funbox
```
