### ISSUE TITLE
deskmodder.de - Ad - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3449]
**Site**: https://www.deskmodder.de/
**Description**: Ad leftover and Ad post in forum.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20369187/ef8b8b30-ac57-11e6-873d-cc390967b060.png)

**Ad post in forum (e.g.: https://www.deskmodder.de/phpBB3/viewtopic.php?f=343&t=18155&sid=e868a5206e21eb407d8fb0d493dc6eac):**

![image](https://cloud.githubusercontent.com/assets/10995998/20369179/e66c1ce0-ac57-11e6-9fbf-90b7640d23d0.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.77
Spyware filter 1.0.9.4
Social media filter 1.0.14.56
Annoyances filter 1.0.6.59
German filter 1.0.28.47
Mobile ads filter 1.0.5.78
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to German filter
```
deskmodder.de###secondary aside.widget.widget_text[-ext-has="*>.adsbygoogle"]
deskmodder.de##div[id^="google"][class^="post"]

```
