### ISSUE TITLE
windowsarea.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3450]
**Site**: http://windowsarea.de/
**Description**: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20369673/bafdb098-ac5a-11e6-96f0-6a33f7ad6ecb.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.77
Spyware filter 1.0.9.4
Social media filter 1.0.14.56
Annoyances filter 1.0.6.59
German filter 1.0.28.47
Mobile ads filter 1.0.5.78
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
windowsarea.de##.widgetized.w-3 > aside.clearfix.widget_text
```
