### ISSUE TITLE
forums.windowscentral.com - Ad leftover (mobile)

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3451]
**Site**: http://forums.windowscentral.com/
**Description**: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20369777/47d32296-ac5b-11e6-891c-e97017bb201c.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20369788/54538e02-ac5b-11e6-900d-79a0e1a62945.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.77
Spyware filter 1.0.9.4
Social media filter 1.0.14.56
Annoyances filter 1.0.6.59
German filter 1.0.28.47
Mobile ads filter 1.0.5.78
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Mobile filter
```
forums.windowscentral.com##.adunit
```
please check it, because I see only on leftover at the top

**Comment by danidoedel** [comment]
Uhh I just tested this site without Adguard and I think this site is broken on mobile devices with Adguard enabled:

Disabled:

![image](https://cloud.githubusercontent.com/assets/10995998/20390986/92be2604-acd1-11e6-903f-91cd2925df70.png)

Enabled:

![image](https://cloud.githubusercontent.com/assets/10995998/20391004/a297da34-acd1-11e6-8b13-1b96a7b7007e.png)

**Comment by Alex-302** [comment]
Yes, it is broken.
Added to Mobile filter:
```
@@||forums.windowscentral.com^$script,~third-party
```
Please check

**Comment by danidoedel** [comment]
That's perfect!
I guess these parts can't be removed, right?
![image](https://cloud.githubusercontent.com/assets/10995998/20397181/1627c1c8-ace9-11e6-998b-21d16741298d.png)

**Comment by Alex-302** [comment]
1 and 3 are parts of design.
Added to Mobile filter
```
forums.windowscentral.com##.homeforums > div[align="center"][style="padding:15px"]
```
