### ISSUE TITLE
Rename "Adguard DNS" filter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3452]
This name is too confusing.
We should change it to something more appropriate.

We also should change it's name here:
https://adguard.com/filters.html#dns

For instance:
`Simplified hosts-blocking filter`

You'd better also change the filter description. Emphasize, that the filter is simplified in order to be better compatible with DNS-level ad blocking.

Don't forget to update it in oneskyapp!

**Comment by vbagirov** [comment]
Filter is renamed, description is changed. Oneskyapp translations are updated. Soon changes will be commited to the main server.
