### ISSUE TITLE
73online.ru - Incorrect Blocking

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3453]
## **Скриншоты:**

<details>

![2_](https://cloud.githubusercontent.com/assets/16462533/20390419/78853042-acd7-11e6-9139-f9ec4fef5711.png)

![3_](https://cloud.githubusercontent.com/assets/16462533/20390418/788275fa-acd7-11e6-940f-c3af414ee0bf.png)

![4_](https://cloud.githubusercontent.com/assets/16462533/20390417/78817dbc-acd7-11e6-975f-d90173c5a30c.png)

</details>

## **Фильтры:**

<details>

**Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский**

</details>

**Comment by Alex-302** [comment]
Invalid HTML. No Adguard injections.
https://github.com/AdguardTeam/AdguardForWindows/issues/1222#issuecomment-261308516
