### ISSUE TITLE
http://www.b.dk/ - Annoyance 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3454]
**Description**: 
Cookies notification not blocked on this site
http://www.b.dk/

Screenshot:
![screen shot 2016-11-17 at 3 16 43 pm](https://cloud.githubusercontent.com/assets/17504743/20390865/53417abe-acd9-11e6-8d1d-55aa5e91bac1.png)

**Adguard version**: 1.3.0.

**Filters list**: 
User
English
Spyware
Social media
Russian
Spanish/Portuguese
EasyList Hebrew

**Operating system**:  OS X 10.11.6

**Browser**: Chrome

Customer ID: 1449953

**Comment by Alex-302** [comment]
они хитро с блокировщиками борются. Пока не выходит побороть. Сдал разработчикам.
