### ISSUE TITLE
dropbox.com - Annoyance leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3455]
**Site**: https://www.dropbox.com/
**Description**: Cookie notice leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20391293/0f210cd8-acd3-11e6-9e1c-c3992d3703f7.png)

</details>

________________

**Adguard version**: 6.1.281.1494

**Filters list**: 
English filter 1.1.0.78
Spyware filter 1.0.9.4
Social media filter 1.0.14.56
Annoyances filter 1.0.6.60
German filter 1.0.28.50
Mobile ads filter 1.0.5.78
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Not shown on my end.

**Comment by danidoedel** [comment]
@Alex-302 Maybe you can see that cookie notice here: https://www.dropbox.com/de or maybe that helps:

![image](https://cloud.githubusercontent.com/assets/10995998/20396114/6c7e5d38-ace5-11e6-94fd-b470f4ae0b11.png)

But with `dropbox.com###top-notification-bar-container` there is then some leftover:
![image](https://cloud.githubusercontent.com/assets/10995998/20396256/e5d24802-ace5-11e6-90e5-b686f1ee67ea.png)

**Comment by Alex-302** [comment]
Nothing:) Even with German proxy.

**Comment by danidoedel** [comment]
Still happening for me. Annoyance filter blocks the content of that notification bar, although there isn't a dropbox rule in that filter... strange! :(

**Comment by Alex-302** [comment]
Please provide me remote access on the Monday. Ok?

**Comment by worldsdream** [comment]
@Alex-302 i made a topic about this 5 days ago. 

https://forum.adguard.com/index.php?threads/dropbox-com.16067/

**Comment by Alex-302** [comment]
I know.

**Comment by seanl-adg** [comment]
Should be fixed in the respective forum thread.
