### ISSUE TITLE
https://tjournal.ru -  ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3456]
## При включенной фильтрации HTTPS, сайт [tjournal.ru](tjournal.ru) не открывается.
**Проблема повторилась, помогло откл. HTTPS. Антивируса нет.**

<details>

![2016-11-17_16-25-09](https://cloud.githubusercontent.com/assets/16462533/20393056/14e66de2-ace3-11e6-9b9e-1d2e19afc296.png)

</details>

## Фильтры:

<details>

**Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский**

**Comment by Alex-302** [comment]
Это не связано с фильтрами. С недавних пор сайты с SSL сертификатами от StartCom и WoSign прога не фильтрует в целях безопасности.
