### ISSUE TITLE
gamecopyworld.eu

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#34586]
1. Select any mirror
https://gamecopyworld.eu/games/pc_the_witcher_2.shtml
2. adfly did not work (timer not show up). 
3. Only `http://ceesty.com` timer works. 
4. On main  `d1.consoletarget.com` dowload page ads show up. 

Sample URL 
https://d1.consoletarget.com/?y=5d9f4e4d&x=1%2F2K%2FpOTYejPT5RP0KB5OEXoW8BikBNE4chB4DFmfhB1SkOGclFk%2FbRKUkyOGzDY7QI%2FotoXHXzk%2FPQCR2y8flIbl4X0%2FEVRlk3nttNetVEXzliU4lV2IYDyiZmBsdSE12we5qXwIviUV4lYy%2Bi8KLCMGjDZ39rqsOuONt42jxp17Pm%2FcvuqWk25uyJkjhSfY4kRoPBX3c1%2Ba%2FkNDPzFqg%3D%3D

![scr-1559320087-001](https://user-images.githubusercontent.com/9846948/58720223-dbc47680-83d1-11e9-9ac1-de2f7aef30da.png)

Ads box, MP4 from 
`d1.consoletarget.com/i/tc/pm/f0431_1.mp4` with dancing girls.

**Comment by FadeMind** [comment]
@Alex-302 same on https://gamecopyworld.eu/games/search_results.shtml?q=witcher+3&sa=%C2%A0+Google+Search%C2%A0+
![scr-1559362718-001](https://user-images.githubusercontent.com/9846948/58743621-51adf980-8435-11e9-9aff-0d2716af8630.png)

and yes, I have lastest adguard filters with Fix from `b9da86d` commit.

**Comment by FadeMind** [comment]
@Alex-302 I have still this ad
https://gamecopyworld.eu/games/pc_the_witcher_2.shtml
![scr-1559492505-001](https://user-images.githubusercontent.com/9846948/58764079-4bb63680-8563-11e9-86e4-dcdfcd24e9e9.png)


https://gamecopyworld.eu/games/pc_rico.shtml

![scr-1559492541-001](https://user-images.githubusercontent.com/9846948/58764088-5ffa3380-8563-11e9-9d9e-66383b4c81e8.png)

**Comment by Alex-302** [comment]
Fixed.

**Comment by FadeMind** [comment]
@Alex-302 new one
https://www.gamecopyworld.com/games/pc_nfs_carbon.shtml
![scr-1561033527-001](https://user-images.githubusercontent.com/9846948/59849275-6eb85700-9367-11e9-9682-414a14d0c5ac.png)

**Comment by Alex-302** [comment]
New domain. Fixed
