### ISSUE TITLE
Incorrect blocking https://itunes.apple.com

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3458]
**Description**:
Incorrect blocking if browsing from iPhone. From Mac everything looks fine. 
https://itunes.apple.com/us/app/twitter/id333903271?mt=8

Screenshot: 
![screen shot 2016-11-17 at 5 52 33 pm](https://cloud.githubusercontent.com/assets/17504743/20396534/33f3d83a-acef-11e6-8bb0-204a701ba411.png)

**Adguard version**: 1.1.1.54

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.98.93 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.58 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.5 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.45 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.56 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.62 Enabled=YES

**Operating system**: iOS 10.1.1

**Browser**: Safari

Reproduced in desktop Safari in iPhone mode. 

Customer ID 1450482

**Comment by Alex-302** [comment]
It is impossible to open his site on iOS device, even without AG. When I trying it always opens iTunes app.

**Comment by worldsdream** [comment]
Alex is correct.
