### ISSUE TITLE
Missed ads http://www.zdfans.com/

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3459]
**Description**:
Missed ads in the top right corner on the site http://www.zdfans.com/

Screenshot: 
![image](https://cloud.githubusercontent.com/assets/17504743/20397183/7bc3c36c-acf1-11e6-854c-aa8553560675.png)

**Adguard version**: 6.1.258.1302

**Filters list**:
FilterId:2 Name: English filter
FilterId:104 Name: EasyList China 
FilterId:118 Name: EasyPrivacy
FilterId:0 Name: User filter 
FilterId:220 Name: CJX's Annoyance List 
FilterId:100000 Name: EasyList Lite 

**Operating system**: Microsoft Windows NT 10.0.14393.0

Reproduced in Chrome. 

Customer ID 1432221

**Comment by seanl-adg** [comment]
Please check, I can't stably reproduce the ads.

**Comment by Alex-302** [comment]
I can't reproduce
