### ISSUE TITLE
http://motherless.com/ - false blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3460]
http://motherless.com/73687EC

Can't add/remove a pic to favorites. Works fine when you disable Adguard English filter.

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/20397399/3f933e44-acf2-11e6-98c6-ee36f0333bcf.png)

use login thomas534test and 99439943 as a pass to log in.

**Comment by Alex-302** [comment]
Added to English filter
```
@@||motherless.com/favorites/
```
There is only one issue?

**Comment by hoonkai** [comment]
Videos won't play unless English filter is disabled.

**Comment by Alex-302** [comment]
Not reproduced. Which Adguard version are you using?

**Comment by hoonkai** [comment]
I'm using the Safari Extension 2.5.12.

**Comment by Alex-302** [comment]
Added
```
@@||videos.motherlessmedia.com/videos/*.mp4?
```
