### ISSUE TITLE
Ads in applications

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3461]
Sorry for merging them into one issue.

1. https://play.google.com/store/apps/details?id=com.usnaviguide.radar_now
2. https://play.google.com/store/apps/details?id=com.farproc.wifi.analyzer
3. https://play.google.com/store/apps/details?id=com.andrwq.recorder 

We couldn't reproduce these issues, so we've asked to clear the cache and to provide HTTPS logs and the timing for each one. Please see logs here: 1448784

<details>
{
  "advancedPreferences" : {
    "pref.vpn.disable.pause" : false,
    "pref.har.capture" : false,
    "pref.vpn.ipv6.force" : false,
    "pref.vpn.ipv4.force.default" : false,
    "pref.proxy.block.ipv6" : false,
    "pref.splash.enabled" : true,
    "pref.vpn.ipv6.disable" : false,
    "pref.vpn.capture" : false,
    "pref.vpn.ipv4.force.complex" : false,
    "pref.vpn.ipv6.bypass" : false
  },
  "androidVersion" : "6.0.1 (sdk=23)",
  "appLanguage" : "en",
  "applicationId" : "8ec20ad826e20dd2",
  "autoStartEnabled" : true,
  "browsingSecurityEnabled" : true,
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "samsung SM-G900V",
  "deviceSpeedRank" : 125,
  "dnsFilteringEnabled" : false,
  "enabledFilterIds" : [ 2, 3, 14, 11, 15, 108 ],
  "environment" : "beta",
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "iconType" : "LOW_PRIORITY",

<details>
  "installedPackages" : [ "org.prowl.torquefree;version=1.2.16;system=false", "com.mobeam.barcodeService;version=1.3.7  ;system=true", "com.samsung.android.provider.filterprovider;version=2.0.07;system=true", "com.synology.dsphoto;version=3.11.1;system=false", "com.monotype.android.font.rosemary;version=1.0.02-2;system=true", "com.sec.android.app.DataCreate;version=1.0;system=true", "com.sec.android.providers.mapcon;version=1.1.01-15;system=true", "com.skype.raider;version=7.24.0.255;system=false", "com.gd.mobicore.pa;version=3.0079 (51551);system=true", "com.google.android.youtube;version=11.43.54;system=true", "com.samsung.android.app.galaxyfinder;version=4.0.71;system=true", "com.sec.android.app.chromecustomizations;version=1.0.03;system=true", "com.farproc.wifi.analyzer;version=3.10.1-L;system=false", "com.android.providers.telephony;version=6.0.1;system=true", "com.sec.android.app.parser;version=1.0;system=true", "com.sec.android.providers.iwlansettings;version=1.1.01-13;system=true", "com.google.android.googlequicksearchbox;version=6.7.21.21.arm;system=true", "com.verizon.vzwavs;version=4.2;system=true", "com.vlingo.midas;version=11.7.0.1;system=true", "com.android.providers.calendar;version=6.0.1;system=true", "com.osp.app.signin;version=2.1.0309;system=true", "com.sec.android.directshare;version=2.5.0;system=true", "com.samsung.clipboardsaveservice;version=1.0;system=true", "com.sec.automation;version=1.0.1;system=true", "com.android.providers.media;version=6.0.1;system=true", "com.samsung.android.sdk.spenv10;version=4.0.00-1;system=true", "com.google.android.onetimeinitializer;version=6.0.1;system=true", "com.amazon.venezia;version=21.0.2;system=false", "com.united.mobile.android;version=2.1.11;system=false", "com.qualcomm.ltebc_vzw;version=vzw_2.8.29.51.0;system=true", "com.sec.android.widgetapp.digitalclock;version=1.0.01;system=true", "com.android.wallpapercropper;version=6.0.1;system=true", "com.teslacoilsw.launcher;version=4.3.1;system=false", "com.samsung.android.provider.shootingmodeprovider;version=1.0;system=true", "com.sec.android.app.wfdbroker;version=2.0.09;system=true", "com.samsung.android.app.withtv;version=1.0.37;system=true", "com.maxmpz.audioplayer.unlock;version=2-build-26;system=false", "com.sec.android.app.safetyassurance;version=1.0.34;system=true", "com.sec.factory.camera;version=1.0.15;system=true", "org.simalliance.openmobileapi.service;version=4.0.0;system=true", "com.sec.usbsettings;version=1.0;system=true", "com.samsung.syncmlservice;version=6.0.1;system=true", "com.samsung.android.easysetup;version=4.0.9329764;system=true", "com.android.documentsui;version=6.0.1;system=true", "com.android.externalstorage;version=6.0.1;system=true", "com.sec.android.easyonehand;version=2.0;system=true", "com.sec.factory;version=6.0.1;system=true", "tv.peel.smartremote;version=8.6.5;system=true", "com.android.htmlviewer;version=1.1.08;system=true", "com.whatsapp;version=2.16.352;system=false", "com.imdb.mobile;version=6.0.7.106070100;system=true", "com.android.mms.service;version=6.0.1;system=true", "com.samsung.vzwlbs;version=1.0.0;system=true", "com.cequint.ecid;version=5.0.8 2016-01-08 r4258@release-v5_0_8-r4258;system=true", "com.android.providers.downloads;version=6.0.1;system=true", "com.samsung.ucs.agent.boot;version=6.0.1;system=true", "com.vzw.hss.myverizon;version=12.4.15;system=true", "com.synology.DSaudio;version=3.11.1;system=false", "com.sec.android.app.tourviewer;version=1.78.0;system=true", "com.infraware.polarisoffice5;version=5.0.3602.03;system=true", "com.paypal.android.p2pmobile;version=6.6.1;system=false", "com.sec.android.app.FlashBarService;version=1.0;system=true", "com.sec.android.Kies;version=1.0.17;system=true", "com.sec.android.app.voicenote;version=20.1.60-20;system=true", "com.sec.android.app.easylauncher;version=2.0.12;system=true", "com.samsung.knox.rcp.components;version=2.6.04001020;system=true", "com.sec.android.widgetapp.easymodecontactswidget;version=1.0.27;system=true", "com.samsung.android.intelligenceservice2;version=2.3.06;system=true", "com.samsung.android.MtpApplication;version=1.0;system=true", "com.sec.android.app.factorykeystring;version=6.0.1;system=true", "com.synology.DScam;version=2.5.6;system=false", "com.sec.android.app.samsungapps;version=3.1.07-44;system=true", "com.vcast.mediamanager;version=15.4.33;system=true", "com.sec.android.emergencymode.service;version=6.0.1;system=true", "com.mm.android.direct.AmcrestViewPro;version=3.41.0204;system=false", "com.eclipsim.gpsstatus2;version=7.3.155;system=false", "com.google.android.configupdater;version=6.0.1;system=true", "com.sec.android.app.wlantest;version=1.0.0;system=true", "com.sec.android.widgetapp.SPlannerAppWidget;version=2.1.11;system=true", "com.sec.android.widgetapp.activeapplicationwidget;version=1.0.0;system=true", "com.sec.android.app.billing;version=3.0.35-0;system=true", "com.sec.android.app.minimode.res;version=6.0.1;system=true", "com.android.defcontainer;version=6.0.1;system=true", "com.sec.android.daemonapp;version=160210.1514259;system=true", "org.zwanoo.android.speedtest;version=3.2.26;system=false", "com.sec.ims;version=1.0;system=true", "com.sec.sve;version=1.0;system=true", "com.sec.enterprise.knox.attestation;version=1.0.2;system=true", "com.android.vending;version=7.1.15.I-all [0] [PR] 137333487;system=true", "com.android.pacprocessor;version=6.0.1;system=true", "com.dsi.ant.service.socket;version=4.14.20;system=true", "com.sec.android.app.popupuireceiver;version=1.6;system=true", "com.ipsec.service;version=3.5;system=true", "com.nll.acr;version=18.7;system=false", "com.sec.android.app.soundalive;version=2.0.27;system=true", "com.sec.android.providers.security;version=1.0.01;system=true", "com.sec.android.provider.badge;version=1.0.11-1;system=true", "com.android.certinstaller;version=6.0.1;system=true", "com.samsung.android.securitylogagent;version=4.3.34;system=true", "com.android.carrierconfig;version=1.0.0;system=true", "com.google.android.marvin.talkback;version=5.0.4;system=true", "com.sec.android.app.taskmanager;version=2.1;system=true", "com.samsung.android.app.assistantmenu;version=1.5.75-0;system=true", "com.sec.android.directconnect;version=3.7;system=true", "com.samsung.SMT;version=201503021;system=true", "com.samsung.dcm;version=2.0;system=true", "com.samsung.sdm;version=1.0;system=true", "com.samsung.spg;version=3.1.07;system=true", "com.samsung.vvm;version=4.1.25;system=true", "com.sec.android.ofviewer;version=1.0.21;system=true", "com.samsung.everglades.video;version=1.0.35;system=true", "android;version=6.0.1;system=true", "com.android.contacts;version=3.3.05;system=true", "com.samsung.hs20provider;version=1.0;system=true", "com.vzw.apnservice;version=17.2;system=true", "com.citi.citimobile;version=7.8.0;system=false", "com.dsi.ant.sample.acquirechannels;version=01.00.05;system=true", "com.andrwq.recorder;version=1.8.0;system=false", "com.samsung.android.smartface;version=1.0;system=true", "com.android.mms;version=1.0.0;system=true", "com.android.nfc;version=6.0.1;system=true", "com.android.stk;version=6.0.1;system=true", "com.usbank.mobilebanking;version=2.13.15;system=false", "com.sec.knox.foldercontainer;version=2.6.04001013;system=true", "com.android.backupconfirm;version=6.0.1;system=true", "com.skymotion.skymotion;version=4.4.104;system=false", "com.samsung.klmsagent;version=2.6.081;system=true", "com.instagram.android;version=9.8.0;system=false", "com.samsung.android.app.memo;version=1.2.9018997;system=true", "flipboard.app;version=3.4.15;system=true", "com.sec.android.app.storycam;version=4.169;system=true", "com.samsung.carrier.logcollector;version=1.6;system=true", "com.etrade.mobilepro.activity;version=5.1;system=false", "com.android.statementservice;version=1.0;system=true", "com.samsung.android.sdk.samsunglink;version=2.0.3729;system=true", "com.google.android.gm;version=6.10.23.137993986.release;system=true", "com.YRH.PackPoint;version=3.9.12-v187;system=false", "com.sec.android.app.hwmoduletest;version=6.0.1;system=true", "com.geico.mobile;version=4.6.1;system=false", "com.sec.bcservice;version=2.0;system=true", "com.android.calendar;version=2.1.36;system=true", "com.sec.modem.settings;version=1.0.1;system=true", "com.android.phasebeam;version=1.0;system=true", "com.yahoo.mobile.client.android.weather;version=1.6.2;system=false", "com.monotype.android.font.samsungsans;version=1.0.01-1;system=true", "com.sec.android.app.sysscope;version=1.3.65;system=true", "com.sec.android.app.wallpaperchooser;version=3.0.14;system=true", "com.samsung.android.providers.context;version=2.0.8;system=true", "com.sec.android.app.servicemodeapp;version=6.0.1;system=true", "com.sec.android.preloadinstaller;version=6.0.1;system=true", "com.google.android.setupwizard;version=2.0;system=true", "com.samsung.android.sdk.professionalaudio.utility.jammonitor;version=2.1.05;system=true", "com.sec.android.gallery3d;version=6.0.1;system=true", "com.android.providers.settings;version=6.0.1;system=true", "com.sec.imsservice;version=1.0;system=true", "com.sec.app.TransmitPowerService;version=1.0;system=true", "com.android.sharedstoragebackup;version=6.0.1;system=true", "com.sec.android.widgetapp.dualclockdigital;version=1.0.06;system=true", "com.samsung.sdm.sdmviewer;version=1.0;system=true", "com.samsung.android.app.colorblind;version=2.3.11;system=true", "com.google.android.music;version=6.16.3624-0.I.3421865;system=true", "com.sec.android.pagebuddynotisvc;version=1.0;system=true", "com.android.printspooler;version=1;system=true", "com.sec.providers.settingsearch;version=1.1;system=true", "com.vzw.hss.widgets.infozone;version=2.2.19;system=true", "com.android.dreams.basic;version=6.0.1;system=true", "com.sec.android.app.bcocr;version=6.2.2.0;system=true", "com.sec.android.widgetapp.ap.hero.accuweather;version=160224.1600815;system=true", "com.sec.android.app.music;version=16.1.63-24;system=true", "com.android.incallui;version=2.1.04;system=true", "com.sec.app.samsungprintservice;version=3.01.161021;system=true", "dji.pilot;version=3.1.0;system=false", "com.sec.android.app.dictionary;version=2.5.42.seller;system=true", "com.android.inputdevices;version=6.0.1;system=true", "com.slacker.radio;version=6.1.19;system=true", "com.sec.esdk.elm;version=5.0.07;system=true", "com.socialnmobile.dictapps.notepad.color.note;version=3.11.7;system=false", "com.sec.android.app.videoplayer;version=1.0.49;system=true", "com.sec.providers.assisteddialing;version=6.0.1;system=true", "com.sec.android.app.filtermanager;version=2.0.13;system=true", "com.adguard.android;version=2.8.40;system=false", "com.sec.android.service.sm;version=1.2.8;system=true", "com.sec.android.gallery3d.panorama360view;version=1.0.2;system=true", "com.sec.smartcard.manager;version=2.0;system=true", "com.sec.allsharecastplayer;version=1.0.03;system=true", "com.sec.android.automotive.drivelinkremote;version=0.2.2.1250855;system=true", "com.yelp.android;version=8.23.0;system=false", "com.sec.android.Preconfig;version=6.0.1;system=true", "com.vznavigator.Generic;version=9.0.8.92;system=true", "com.sec.android.settingsmaps;version=1.0;system=true", "com.test.LTEfunctionality;version=1.0;system=true", "com.google.android.apps.docs;version=2.4.382.19.35;system=true", "com.google.android.apps.maps;version=9.40.2;system=true", "com.google.android.apps.plus;version=9.1.0.138578129;system=true", "com.sec.enterprise.mdm.vpn;version=1.3;system=true", "com.dsi.ant.plugins.antplus;version=3.6.10;system=true", "com.samsung.android.personalpage.service;version=1.0;system=true", "com.samsung.android.service.travel;version=1.0;system=true", "com.samsung.advp.imssettings;version=1.0;system=true", "com.sec.android.inputmethod;version=4.0;system=true", "com.teslacoilsw.launcher.prime;version=D;system=false", "com.sec.android.app.clockpackage;version=1.1.27;system=true", "com.sec.android.RilServiceModeApp;version=6.0.1;system=true", "com.google.android.webview;version=54.0.2840.85;system=true", "com.samsung.android.app.mirrorlink;version=1.0.44;system=true", "com.sec.kidsplat.installer;version=3.0.01;system=true", "com.android.server.telecom;version=1.0.0;system=true", "com.google.android.syncadapters.contacts;version=6.0.1;system=true", "com.sec.imslogger;version=1.20160121_LDM;system=true", "com.samsung.android.clipboarduiservice;version=6.0.1;system=true", "com.android.keychain;version=6.0.1;system=true", "com.synology.DSfile;version=4.9.2;system=false", "com.sec.setdefaultlauncher;version=1.0;system=true", "com.samsung.huxextension;version=1.0.07;system=true", "com.samsung.android.app.sounddetector;version=1.0;system=true", "com.android.chrome;version=54.0.2840.85;system=true", "com.google.android.street;version=2.0.0.137864541;system=false", "com.google.android.gms;version=10.0.84 (438-137749526);system=true", "com.google.android.gsf;version=6.0.1;system=true", "com.google.android.tts;version=3.10.10;system=true", "com.android.calllogbackup;version=6.0.1;system=true", "com.google.android.partnersetup;version=6.0.1;system=true", "com.usnaviguide.radar_now;version=6.3;system=false", "com.sec.android.diagmonagent;version=4.1.13;system=true", "com.android.packageinstaller;version=6.0.1;system=true", "com.google.android.videos;version=3.20.10;system=true", "com.samsung.mdl.radio;version=1.5.1600015044;system=true", "com.sec.spp.push;version=1.6.00;system=true", "com.dsi.ant.server;version=3.0.0;system=true", "com.samsung.syncmlphonedataservice;version=6.0.1;system=true", "com.sec.android.widgetapp.digitalclockeasy;version=1.0.01;system=true", "com.wits.obdm_permissions;version=2.0;system=true", "com.sec.android.app.myfiles;version=1.7.0;system=true", "com.android.proxyhandler;version=6.0.1;system=true", "com.samsung.android.allshare.service.fileshare;version=2.5;system=true", "com.sec.android.mimage.photoretouching;version=6.0.34;system=true", "com.sec.android.app.launcher;version=1.0.58;system=true", "com.qti.backupagent;version=1.0;system=true", "com.customermobile.preload.vzw;version=201511091516;system=true", "com.sec.android.automotive.drivelink;version=0.2.16.1393613;system=true", "com.samsung.helphub;version=1.0.0;system=true", "com.sec.android.app.cmas;version=1.1.7;system=true", "com.sec.android.app.sns3;version=2.0.12;system=true", "flipboard.boxer.app;version=2.1.14;system=true", "com.google.android.feedback;version=6.0.1;system=true", "com.google.android.apps.photos;version=2.4.0.138833446;system=false", "com.google.android.calendar;version=5.6.6-137495241-release;system=false", "com.google.android.syncadapters.calendar;version=5.2.3-99827563-release;system=true", "com.android.managedprovisioning;version=6.0.1;system=true", "com.samsung.android.app.filterinstaller;version=2.0.00;system=true", "com.sec.android.GeoLookout;version=2.0.17;system=true", "com.sec.android.providers.tasks;version=6.0.1;system=true", "com.monotype.android.font.chococooky;version=1.0.03-3;system=true", "com.sec.android.stub.paywithpaypal;version=1.0.0.0;system=true", "com.lifevibes.trimapp;version=174.7.ms_hw;system=true", "com.telecomsys.directedsms.android.SCG;version=0.0.2.453;system=true", "com.android.dreams.phototable;version=6.0.1;system=true", "com.nll.acr.license;version=1.5;system=false", "com.sec.android.service.health;version=2.1.1.001;system=true", "com.samsung.safetyinformation;version=1.0.04-0;system=true", "com.bestdeals;version=3.0.0;system=false", "com.facebook.katana;version=102.0.0.28.70;system=false", "com.sec.android.app.ringtoneBR;version=6.0.1;system=true", "com.ipsec.vpnclient;version=3.5;system=true", "com.android.noisefield;version=1.0;system=true", "com.verizonmedia.go90.enterprise;version=1.4.0;system=true", "com.chrome.deviceextras.samsung;version=34.0.1847.114;system=false", "com.android.providers.partnerbookmarks;version=6.0.1;system=true", "com.foscam.foscam;version=1.7.4;system=false", "com.google.android.gsf.login;version=6.0.1;system=true", "com.motricity.verizon.ssodownloadable;version=3.1.28;system=true", "com.sec.vowifispg;version=1.1;system=true", "com.samsung.android.app.accesscontrol;version=1.5.13-29;system=true", "com.android.wallpaper.livepicker;version=6.0.1;system=true", "com.samsung.android.beaconmanager;version=4.0.9329764;system=true", "com.sec.enterprise.mdm.services.simpin;version=6.0.1;system=true", "com.samsung.ucs.ucspinpad;version=1.0;system=true", "com.android.apps.tag;version=2.0.02;system=true", "com.amazon.mShop.android;version=6.5.0.200;system=true", "com.samsung.android.app.FileShareClient;version=2.5;system=true", "com.sec.android.app.mv.player;version=1.0.03;system=true", "com.healthagen.iTriage;version=5.72;system=false", "com.chase.sig.android;version=3.33;system=false", "d.android.wallpaper.simpleblack;version=1;system=false", "com.sec.android.app.popupcalculator;version=3.2.18;system=true", "com.sec.android.soagent;version=3.1.12;system=true", "com.samsung.android.scloud.backup;version=6.4.03;system=true", "com.samsung.android.fmm;version=6.0.40;system=true", "com.samsung.android.mdm;version=1.0;system=true", "com.sec.android.app.shealth;version=4.6.2.0057;system=true", "com.sec.phone;version=1.0;system=true", "com.samsung.accessory;version=2.16.122;system=true", "com.google.android.apps.translate;version=5.5.0.RC04.137189260;system=false", "com.samsung.knox.appsupdateagent;version=2.6.04001008;system=true", "com.google.android.backuptransport;version=6.0.1;system=true", "com.sec.knox.knoxsetupwizardclient;version=2.6.04001014;system=true", "com.visionobjects.resourcemanager;version=1.5.0;system=true", "com.samsung.android.scloud;version=1.4.42;system=true", "com.sec.app.RilErrorNotifier;version=1.0.0;system=true", "com.android.bookmarkprovider;version=6.0.1;system=true", "com.linkedin.android;version=4.0.86;system=false", "com.android.settings;version=6.0.1;system=true", "com.samsung.app.newtrim;version=1.0.24;system=true", "org.awallet.free;version=6.6.1;system=false", "com.sec.android.mmapp;version=1.0.16;system=true", "com.sec.android.app.bluetoothtest;version=6.0.1;system=true", "com.samsung.android.intelligenceservice;version=2.2.02;system=true", "uk.co.josephearl.android.apps.decibelometerfree;version=1.0.2;system=false", "com.sec.android.emergencylauncher;version=1.0.45;system=true", "com.google.android.apps.books;version=3.10.29;system=true", "com.sec.hearingadjust;version=3.0.07;system=true", "com.google.android.apps.inbox;version=1.34 (137563954);system=false", "com.samsung.android.dlp.service;version=1.0;system=true", "com.samsung.android.bbc.bbcagent;version=2.0;system=true", "com.samsung.android.nearby.mediaserver;version=2.1;system=true", "com.wssnps;version=6.0.46;system=true", "com.samsung.android.app.watchmanagerstub;version=1.1.15-12310;system=true", "com.policydm;version=4.1.42;system=true", "com.samsung.android.app.FileShareServer;version=2.5;system=true", "com.samsung.android.sdk.professionalaudio.app.audioconnectionservice;version=2.1.00;system=true", "com.audible.application;version=2.1.0;system=true", "com.asurion.android.verizon.vms;version=4.2.0;system=true", "gbis.gbandroid;version=5.0.1 20034;system=false", "com.sec.android.app.snsimagecache;version=1.0.01;system=true", "uk.co.aifactory.ginrummyfree;version=1.172;system=false", "com.android.vpndialogs;version=6.0.1;system=true", "com.samsung.InputEventApp;version=1.0.0;system=true", "com.qualcomm.vzw_api;version=2.8.29.43.0;system=true", "com.google.android.keep;version=3.3.431.0;system=false", "com.google.android.talk;version=14.0.136618992;system=true", "com.sec.android.widget.samsungapps;version=5.02.066;system=true", "com.android.email;version=5.0.0.0400;system=true", "com.android.phone;version=1.0.0;system=true", "com.android.shell;version=6.0.1;system=true", "com.android.providers.userdictionary;version=6.0.1;system=true", "com.sec.enterprise.knox.cloudmdm.smdms;version=1.7.6;system=true", "com.arcsoft.magicshotstudio;version=3.0.0.75;system=true", "com.android.location.fused;version=6.0.1;system=true", "com.samsung.groupcast;version=2.7.039;system=true", "com.sec.face;version=1.0;system=true", "com.android.systemui;version=6.0.1;system=true", "com.sec.android.app.personalization;version=6.0.1;system=true", "com.monotype.android.font.cooljazz;version=1.0.03-3;system=true", "com.android.exchange;version=5.0.0.0400;system=true", "com.android.bluetoothmidiservice;version=6.0.1;system=true", "com.yahoo.mobile.client.android.finance;version=3.6.1;system=false", "com.ebay.mobile;version=5.5.1.17;system=false", "com.mathpad.mobile.android.wt.unit;version=2.9.11;system=false", "com.sec.android.provider.logsprovider;version=2.0;system=true", "com.sec.android.app.SamsungContentsAgent;version=1.0.03;system=true", "com.samsung.aasaservice;version=3.3;system=true", "com.sec.android.app.setupwizard;version=1.3.42;system=true", "com.sec.android.app.mediasync;version=2.2.0;system=true", "com.samsung.android.allshare.service.mediashare;version=2.2;system=true", "com.sec.android.app.mt;version=1.0.01-0;system=true", "com.samsung.android.app.gestureservice;version=1.0.00-1;system=true", "com.sec.android.provider.emergencymode;version=1.0;system=true", "com.google.android.play.games;version=3.9.08 (3448271-038);system=true", "com.samsung.android.fingerprint.service;version=1.1.0;system=true", "com.sec.knox.switcher;version=2.6.04001008;system=true", "com.sec.android.app.camera;version=3.0;system=true", "com.google.android.apps.magazines;version=3.5.3;system=true", "com.android.bluetooth;version=6.0.1;system=true", "com.qualcomm.timeservice;version=6.0.1;system=true", "com.qualcomm.atfwd;version=6.0.1;system=true", "com.qualcomm.embms;version=1.0;system=true", "com.android.providers.contacts;version=6.0.1;system=true", "com.sec.android.app.magnifier;version=1.4.13;system=true", "com.samsung.sec.android.application.csc;version=6.0.1;system=true", "com.android.captiveportallogin;version=6.0.1;system=true", "com.devuni.flashlight;version=5.2.4;system=false", "com.sec.android.filter;version=2.0.01;system=true", "com.nuance.swype.input;version=1.8.23.1082300.40905;system=true", "com.samsung.android.sconnect;version=3.0.6914363;system=true", "com.maxmpz.audioplayer;version=2.0.10-build-588-play;system=false", "com.sec.android.easysettings;version=6.0.1;system=true", "net.recollect.washingtoncounty;version=2016.10.25;system=false", "com.verizon.messaging.vzmsgs;version=6.0.10;system=true", "com.verizon.llkagent;version=2.0.02;system=true", "com.gotv.nflgamecenter.us.lite;version=12.1.99;system=true", "com.amazon.kindle;version=7.5.0.51;system=true", "com.samsung.location;version=v5.12h;system=true", "com.sec.android.mimage.sstudio;version=1.7.5;system=true" ],

</details>
  "installerPackage" : null,
  "kernelVersion" : "3.4.0-8025411",
  "premium" : true,
  "proxyMode" : false,
  "proxyPort" : 8080,
  "proxySetupManualMode" : false,
  "referrer" : null,
  "sendAnonymousStatistics" : true,
  "showUsefulAds" : false,
  "sourceApk" : "/data/app/com.adguard.android-1/base.apk",
  "sslMitmConfiguration" : "{\"certificateInstalledToSystemStorage\":null,\"mitmList\":\"1018 domains\",\"mitmListMode\":\"WHITELIST\"}",
  "statisticsInfo" : "Blocked threats:0; Blocked banners:74802; Traffic saved:1949842432;",
  "trial" : false,
  "updateChannel" : "RELEASE",
  "upstreamProxySettings" : null,
  "userfilter" : [ ],
  "versionName" : "2.8.40",
  "whitelist" : [ ]
}

**Comment by Alex-302** [comment]
I need screenshots of ads.

**Comment by reuveng60** [comment]
Screen shoots.
![screenshot_2016-11-13-18-19-30](https://cloud.githubusercontent.com/assets/23532620/20406981/5f0a8b0c-acc4-11e6-98b0-a0ebf0ac3f00.png)
![screenshot_2016-11-14-07-15-27](https://cloud.githubusercontent.com/assets/23532620/20406982/5f0c1f6c-acc4-11e6-8172-c9474a09f9e0.png)
![screenshot_2016-11-14-07-17-08](https://cloud.githubusercontent.com/assets/23532620/20406983/5f0f554c-acc4-11e6-9823-894819e43c9e.png)

**Comment by Alex-302** [comment]
com.farproc.wifi.analyzer - it is clean on my eng. As I see in your log, ad requests are blocked.
com.andrwq.recorder - is also clean.
Please try to clear cache of these apps.
Are you using VPN mode?

com.usnaviguide.radar_now - can't install on my devices
