### ISSUE TITLE
Patient.info - Unable to access forum (AdGuard Annoyances filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#34618]
### Affected site:
`https://patient.info/forums/`

### Issue:
Unable to access forum, because of a blocked cookie consent.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* AdGuard Annoyances filter

### Problem rule:
`###cookie-policy`

### Possible fix:
`patient.info#@##cookie-policy`

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.5.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.10 (XUL)

**Comment by AdamWr** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/897eb25dc58e1af081193cb2825b99d734c31624
https://github.com/AdguardTeam/AdguardFilters/issues/34767
