### ISSUE TITLE
http://pesnik.su/mp3 - Missed ads

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3463]
**Description**: Missed ads on the website
http://pesnik.su/mp3/%D0%A3%D0%BB%D1%83%D0%B3%D0%B1%D0%B5%D0%BA%20%D0%97%D0%B0%D1%80%D0%B8%D0%BF%D0%BE%D0%B2

Screenshot: use the following code

<details>

![screen shot 2016-11-17 at 7 30 47 pm](https://cloud.githubusercontent.com/assets/17504743/20400267/adda8bd2-acfc-11e6-8c22-42cd818891e9.png)

</details>

**Adguard version**: 1.3.1 beta

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0
ID=2 Name="English filter" Version=1.1.0.79
ID=3 Name="Spyware filter" Version=1.0.9.5
ID=4 Name="Social media filter" Version=1.0.14.56
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.90
ID=1 Name="Russian filter" Version=1.0.42.97
ID=105 Name="EasyList Czech and Slovak" Version=1.0.1.77

**Operating system**: Mac OS X 1012

Customer ID 1431737

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||teaser.redpic.ru^$third-party
```
