### ISSUE TITLE
THT CLUB app

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3465]
**Description**: Блокируется видео
К примеру, зайти на раздел "ТНТ видео" - Дом2 и включить видео -проигрыватель будет белый

Помогает отключение Английского фильтра

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20401821/0610f592-ad03-11e6-9704-844224bd3508.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20401827/0b26b094-ad03-11e6-9cc8-dca5e168e4b9.png)

</details>

**Adguard version**: 2.8.53

**Filters list**: 1,2,3,4,11,14

**Operating system**:Андроид

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||rutube.ru/play/embed/*?advertiser_id=
```
