### ISSUE TITLE
http://ffclub.ru/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3467]
**Description**: У юзера пролезает Директ
У меня там пустое место, но есть розовая полоска от рекламы
http://ffclub.ru/forum/

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20406944/0f9400fe-ad18-11e6-82ed-0629a09ae7be.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20406950/15ecbe5a-ad18-11e6-844b-459eb83b47ae.png)

</details>

**Adguard version**: 6.1.258.1302

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Директа нет. Возможно в юзерфильтре где-то исключение для яндекса.
Добавил
```
ffclub.ru##.adv_center
```
