### ISSUE TITLE
minfin.com.ua - missed ADs

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3468]
## Реклама пропущена на [minfin.com.ua](minfin.com.ua), только в IE
**Например в хроме такого нет.**

## Скрины:

<details>

![2016-11-18_14-21-35](https://cloud.githubusercontent.com/assets/16462533/20430042/c22831e0-ad9a-11e6-874e-eac4677c3ccf.png)

![2016-11-18_14-21-52](https://cloud.githubusercontent.com/assets/16462533/20430061/df1725b8-ad9a-11e6-944d-cdf3fcc40909.png)

</details>

## Фильтры:

<details>

**Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский**

</details>

**Comment by Alex-302** [comment]
Странно, гугловая реклама должна блокироваться в любом случае. Только на этом сайте проблема?

**Comment by Alex-302** [comment]
Убрал пару огрызков
```
minfin.com.ua##.teaser-wrap
minfin.com.ua##.mfz-banner-c
```
