### ISSUE TITLE
http://www.sport-express.ru/

### ISSUE THREAD

**Issue by dtitbd** [AdguardTeam/AdguardFilters#3469]
Огромное окошко СЭ в фейсбук+затемнение все страницы. В куки записывается ровно на 24 часа.

<details>
![screenshot_2016-11-18-22-46-58](https://cloud.githubusercontent.com/assets/17032471/20440462/023499c6-ade2-11e6-87ab-03057dc56aa7.png)
</details>

**Operating system**: Android

P.S. Скрин под спойлером почему-то не грузится, хотя если вставить вне спойлера, то отображается.

**Comment by Alex-302** [comment]
убрал и подчистил от остатков рекламы
