### ISSUE TITLE
toolslib.net - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3470]
**Site**: https://toolslib.net/
**Description**: Cookie notice and Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20446332/59970fd6-add9-11e6-9fbf-75904db6e79a.png)

(Link to that site [Attention: That will probably download that software straightaway]: https://toolslib.net/downloads/finish/1)

</details>

________________

**Adguard version**: 6.1.281.1519

**Filters list**: 
English filter 1.1.0.89
Spyware filter 1.0.9.8
Social media filter 1.0.14.62
Annoyances filter 1.0.6.73
German filter 1.0.28.62
Mobile ads filter 1.0.5.82
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Not reproduced
http://ipic.su/img/img7/fs/kiss_111kb.1479901166.png
Is HTTPS filtering works on this site?

**Comment by danidoedel** [comment]
Latest Adguard for Windows update fixed it!
