### ISSUE TITLE
http://znaj.ua/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3474]
http://znaj.ua/news/incident/76701/motoroshna-avariya-u-kiyevi-ulamki-avto-rozletilisya-na-30-metriv-navkolo.html

![image](https://cloud.githubusercontent.com/assets/15856304/20458462/79713fa4-aeae-11e6-82d4-7354f1d83a10.png)

Eng, ru, annoyances, social media

**Comment by Alex-302** [comment]
Повторялось? У меня чисто.
