### ISSUE TITLE
lostfilm-online.ru - Incorrect blocking

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3475]
**Description**:
Incorrect blocking on the page http://lostfilm-online.ru/serials.html

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/17504743/20458563/429df6fe-aeb1-11e6-9c7e-08a590ff57a0.png)
</details>

**Adguard version**: 1.1.1.54

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.0.90 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.8 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.63 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.43.8 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.82 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.69 Enabled=YES
ID=101 Name="EasyList" Version=1.0.64.83 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.69.38 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.66.24 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.65.94 Enabled=YES

**Operating system**: iOS 10.1.1

**Browser**: reproduced both in Safari and Chrome 

Customer ID 1249959

**Comment by Alex-302** [comment]
Push notification is blocked by annoyances filter.
For leftovers:
```
lostfilm-online.ru##.left > div.block[-ext-has="div.block_head:contains(Статистика)"]
lostfilm-online.ru##.left > div.block[-ext-has="div.block_head:contains(Статистика)"]+div.bb
lostfilm-online.ru##.left > div.block[-ext-has="div.block_head:contains(Вас заинтересует)"]
lostfilm-online.ru##.left > div.block[-ext-has="div.block_head:contains(Не пропустите)"]
lostfilm-online.ru##.right > div.block[-ext-has="div.block_head:contains(Мы в ВКонтакте)"]
lostfilm-online.ru##.right > div.block[-ext-has="div.block_head:contains(Интересное в сети)"]
lostfilm-online.ru##.right > div.block[-ext-has="div.block_head:contains(Интересное в сети)"]+div.bb
lostfilm-online.ru##div[class^="block_bottom"]
```
Please check them also in IE
