### ISSUE TITLE
delivembed.cc (videobalancer.net) антиадблок

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#34769]
https://appi234567.delivembed.cc/embed/movie/3569 антиадблок не дает переключать качество видео.

**Comment by Smorvel** [comment]
@Alex-302 снова антиадблок...

**Comment by Alex-302** [comment]
Не повторяется. Другие блокировщики есть?

**Comment by Smorvel** [comment]
@Alex-302 нет, проверил отключив все другие фильтры, оставив только базовый фильтр и проблема все еще есть, после его отключения проблема исчезает.

**Comment by Alex-302** [comment]
@Smorvel а если оставить базовый + русский, какие правила применяются из базового? Отфильтровать по заблокированному нужно(чекбокс в журнале)

**Comment by Smorvel** [comment]
@Alex-302 в журнале почему-то пусто по заблокированному...

**Comment by Alex-302** [comment]
От DNS зависит? Другие блокировщики есть? Без Адгарда всё нормально?

**Comment by Alex-302** [comment]
может антитрекинг виноват?

**Comment by Smorvel** [comment]
@Alex-302 Ну я же писал что нету других..
Зависит только от базового фильтра, больше ни от чего. Я пытался вручную поймать нужное правило в базовом фильтре методом тыка, но программа для Windows слишком лагучая, с ней трудно работать...

**Comment by Smorvel** [comment]
@Alex-302 кстати.. у тебя скорее всего какой-то другой фильтр просто исправляет проблему. Попробуй отключить у себя все фильтры кроме базового, после этого думаю проблема появится.
