### ISSUE TITLE
mathe-lexikon.at - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3477]
**Site**: http://www.mathe-lexikon.at/
**Description**: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20459578/4a4e3e20-aec7-11e6-92c9-64b0de24e996.png)

</details>

________________

**Adguard version**: 6.1.281.1519

**Filters list**: 
English filter 1.1.0.93
Spyware filter 1.0.9.8
Social media filter 1.0.14.65
Annoyances filter 1.0.6.74
German filter 1.0.28.63
Mobile ads filter 1.0.5.82
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
mathe-lexikon.at##body > div#lb
