### ISSUE TITLE
rechneronline.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3478]
**Site**: https://rechneronline.de/
**Description**: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20459586/8f4b508a-aec7-11e6-9bdf-d8058c7f648d.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20459599/b6270b4a-aec7-11e6-95c5-a745d0099dac.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20459603/060c93c8-aec8-11e6-82b7-711ee1c2d169.png)

</details>

________________

**Adguard version**: 6.1.281.1519

**Filters list**: 
English filter 1.1.0.93
Spyware filter 1.0.9.8
Social media filter 1.0.14.65
Annoyances filter 1.0.6.74
German filter 1.0.28.63
Mobile ads filter 1.0.5.82
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
added
```
rechneronline.de##td > div[style="font-size:10px;margin-top:1px"]
```
