### ISSUE TITLE
deutschland-in-zahlen.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3479]
**Site**: https://deutschland-in-zahlen.de/
**Description**: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20459608/49ad1472-aec8-11e6-96b1-d5e5444801b1.png)

And so on...

</details>

________________

**Adguard version**: 6.1.281.1519

**Filters list**: 
English filter 1.1.0.93
Spyware filter 1.0.9.8
Social media filter 1.0.14.65
Annoyances filter 1.0.6.74
German filter 1.0.28.63
Mobile ads filter 1.0.5.82
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to german filter
```
deutschland-in-zahlen.de##.werbung_oben
deutschland-in-zahlen.de##.werbung_oben + div[style="position:absolute;top:15px;left:2px"]

```

**Comment by danidoedel** [comment]
@Alex-302 Still some ad leftover: 

![image](https://cloud.githubusercontent.com/assets/10995998/20630616/53aad338-b332-11e6-8d91-ac6e5a863ac1.png)

**Comment by Alex-302** [comment]
fixed
