### ISSUE TITLE
gulli.com / board.gulli.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3480]
**Site**: http://www.gulli.com/ and http://board.gulli.com/
**Description**: Ad leftover and cookie notice at the top.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20459624/0a31326e-aec9-11e6-927c-fc186dd65f48.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20459631/52fb877e-aec9-11e6-824f-e6e1336af0db.png)

</details>

________________

**Adguard version**: 6.1.281.1519

**Filters list**: 
English filter 1.1.0.93
Spyware filter 1.0.9.8
Social media filter 1.0.14.65
Annoyances filter 1.0.6.74
German filter 1.0.28.63
Mobile ads filter 1.0.5.82
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to German filter
```
gulli.com##div[id^="crt-"]
gulli.com###sidebar_container div.block.smaller[-ext-has="div.blockrow > div#plista_widget_board"]
```
