### ISSUE TITLE
seattlepi.com - Missed ads

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3481]
**Description**: Missed ads on the site
http://www.seattlepi.com/sports/

Screenshot: 
<details>

<img width="320" alt="screen shot 2016-11-19 at 3 59 44 pm" src="https://cloud.githubusercontent.com/assets/17504743/20460234/7d93a81a-aee5-11e6-93d7-f529bfb818be.png">

![screen shot 2016-11-19 at 3 57 19 pm](https://cloud.githubusercontent.com/assets/17504743/20460235/7ef979e6-aee5-11e6-98f2-9c90c5d3ae98.png)

</details>

**Adguard version**: 1.1.1.54

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.0.91 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.8 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.64 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.6.74 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.31 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.82 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.69 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.16 Enabled=YES
ID=101 Name="EasyList" Version=1.0.64.83 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.69.29 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.64.85 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.65.3 Enabled=YES
ID=102 Name="ABPindo" Version=1.0.1.27 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.54 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.69.31 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.62 Enabled=YES

**Operating system**: iOS 10.1.1

**Browser**: Safari 

Reproduced in Safari and Chrome

Customer ID: 1418175

**Comment by Autoplayhater5** [comment]
This happen on MacOS via Safari as well as when viewed on mobile.

**Comment by Alex-302** [comment]
Added to English filter
```
seattlepi.com##.commerce
```
