### ISSUE TITLE
http://www.theatlantic.com - Anti-Adblock

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3482]
**Description**: Anti-Adblock Warning on this site
http://www.theatlantic.com/please-support-us

Screenshot: 
<details>

![image](https://cloud.githubusercontent.com/assets/17504743/20460527/8e563ad8-aeee-11e6-9513-9ec598676d70.jpg)

</details>

**Adguard version**: 1.1.2.24

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.94.50 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.68 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.64 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.3.99 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.87 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.27 Enabled=YES

**Operating system**: iOS 10.2

**Browser**: Safari and Chrome

Reproduced in multiple browsers with Adblock Warning Removal List and Anti-Adblock Killer on.

Customer ID:  1182387

**Comment by Alex-302** [comment]
@Tetiana2020 please check it on iOS(don't forget to update filters)

**Comment by Tetiana2020** [comment]
ok. thank you.

**Comment by Alex-302** [comment]
@Tetiana2020 did you check? What result?
