### ISSUE TITLE
https://www.investigationdiscoverygo.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3483]
https://www.investigationdiscoverygo.com/

![pastedimage](https://cloud.githubusercontent.com/assets/15856304/20462022/a851b1a4-af18-11e6-8fee-2cf186f1132b.png)

<details>
Os version: Microsoft Windows NT 10.0.14393.0
Dot .net version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: 0cd5dc055e51493e9a2bac72161101a4
Language: en
AppVersion: 6.1.258.1302
Main settings: 
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:113 Name: Liste FR Url: https://easylist-downloads.adblockplus.org/liste_fr.txt
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Wfp
Ads Blocked: 94787, Trackers Blocked: 89414
Filtering Mode: Driver
Application lifetime: 17.21:17:23.9017884
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": false,
  "BlockWebRtc": false,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"
}

**Comment by evgeniy-ADG** [comment]
We can't even sign in, please advise.

**Comment by Alex-302** [comment]
Remote access.
