### ISSUE TITLE
http://multivarka.pro/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3484]
**Description**: На некоторых сайтах, например
http://multivarka.pro/catalog/chayniki_i_termopoty/rk_m159/ 
не открываются вкладки (описание/технические характеристики/отзывы) и не перелистываются фотографии.

**Adguard version**: 6.1.287.1519

**Filters list**: 1,2,3,4,14,211

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||multivarka.pro/bitrix/templates/multivarka/scripts/popuper.js
```
