### ISSUE TITLE
Girlsofdesire.org [NSFW] breakage

### ISSUE THREAD

**Issue by dumbusernameidk** [AdguardTeam/AdguardFilters#34849]
Since this site relies on use of external sites for pictures the current filter `
girlsofdesire.org##a[href^="http://refer.ccbill.com/"]` causes breakage if the pictures come from that link see here: `https://www.girlsofdesire.org/galleries/zoey-devorah-in-pussy-royale/388186/` [nsfw].

If the filter is intended to block the banner images then you can substitute it with `girlsofdesire.org##[style*="base64"]`.

Using Ublock Origin V1.19.6 with default filters + adguard filters.

**Comment by Alex-302** [comment]
> girlsofdesire.org##a[href^="http://refer.ccbill.com/"]

it is ok. The links go to suspicious sites.



> girlsofdesire.org##[style*="base64"]

we have no this rule. Maybe EasyList issue.
