### ISSUE TITLE
coding-board.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3486]
**Site**: http://www.coding-board.de/
**Description**: Ad leftover and ad post in forums.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20464302/627d2e92-af45-11e6-8bf9-533efa7ae16f.png)

**Ad post (eg.: http://www.coding-board.de/threads/dynamische-rekursive-erzeugung-von-threads-im-programm.37245/):**

![image](https://cloud.githubusercontent.com/assets/10995998/20464304/75df5596-af45-11e6-9876-a4215d773ae1.png)

</details>

________________

**Adguard version**: 6.1.281.1519

**Filters list**: 
English filter 1.1.0.95
Spyware filter 1.0.9.8
Social media filter 1.0.14.67
Annoyances filter 1.0.6.75
German filter 1.0.28.63
Mobile ads filter 1.0.5.83
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
coding-board.de##.sidebar > span[style="font-size: 10px"]
coding-board.de##.pageContent > center > span[style="font-size: 10px"]

**Comment by danidoedel** [comment]
@Alex-302 Ad post in forum not blocked: http://www.coding-board.de/threads/minimax-algorithm-4-gewinnt.36866/

**Comment by Alex-302** [comment]
Added to German filter
```
coding-board.de##.messageList li[data-author="coding-board"][data-author-id="19792"]
```
