### ISSUE TITLE
computerhilfen.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3487]
**Site**: http://www.computerhilfen.de/hilfe-14-0.html
**Description**: Ad leftover (blank space between topics should be removed).

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20464389/ce46fdf0-af46-11e6-910a-567ec20f5fc4.png)

</details>

________________

**Adguard version**: 6.1.281.1519

**Filters list**: 
English filter 1.1.0.95
Spyware filter 1.0.9.8
Social media filter 1.0.14.67
Annoyances filter 1.0.6.75
German filter 1.0.28.63
Mobile ads filter 1.0.5.83
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
computerhilfen.de##tr > td[class="mesind_topiclist1"]
