### ISSUE TITLE
informationsarchiv.net - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3489]
**Site**: http://www.informationsarchiv.net/
**Description**: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20464441/0229b3aa-af48-11e6-9583-c01e2cea5024.png)

</details>

________________

**Adguard version**: 6.1.281.1519

**Filters list**: 
English filter 1.1.0.95
Spyware filter 1.0.9.8
Social media filter 1.0.14.67
Annoyances filter 1.0.6.75
German filter 1.0.28.63
Mobile ads filter 1.0.5.83
Safari filter 1.0.1.69

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
informationsarchiv.net##div[class^="ads_"]
