### ISSUE TITLE
Seattle PI - Missed ad on MacOS Safari

### ISSUE THREAD

**Issue by Autoplayhater5** [AdguardTeam/AdguardFilters#3490]
Dealnews ads are not being blocked on the www.seattlepi.com website when viewed on MacOS Safari.  I use both the Safari plugin and the Adguard standalone app.

A user defined rule can be created, however this only works for one instance of the ad and page.  Reloading the page causes the ad to come back.

<img width="1440" alt="screen shot 2016-11-20 at 12 56 02 pm" src="https://cloud.githubusercontent.com/assets/23619858/20466093/4d314218-af21-11e6-9578-95b010d1b7f6.png">
<img width="1440" alt="screen shot 2016-11-20 at 12 56 09 pm" src="https://cloud.githubusercontent.com/assets/23619858/20466094/4d64419a-af21-11e6-91d8-05964e4ca4f5.png">

Screenshot: use the following code
```
<details>
![](http://somehosting.com/adg_on.jpg)
</details>
```

**Expected behaviour**: Tell us what should happen instead

Screenshot:
```
<details>
![](http://somehosting.com/adg_off.jpg)
</details>
```

**Steps to reproduce the problem**:

* 
*  
*  

**Adguard version**:

**Filters list**:

**Operating system**:

**Browser**:

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
https://github.com/AdguardTeam/AdguardFilters/issues/3481
