### ISSUE TITLE
minfin.com.ua - Ad leftover

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3491]
**Description**: Missed banner on the page
http://minfin.com.ua/banks/forum/banks/ 

Screenshot: 
<details>

![screen shot 2016-11-20 at 11 40 11 pm](https://cloud.githubusercontent.com/assets/17504743/20466365/b8fc7162-af7a-11e6-81e6-5350b91a769b.png)

</details>

**Adguard version**:

**Filters list**:
English
Spyware
Social media
Annoyances
Russian
Experimental

**Operating system**: macOS 10.12.1

**Browser**: Chrome

Customer ID: 1449704

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
||api.venyoo.ru^$third-party
```
Added to Russian filter
```
||minfin.com.ua/files/img/
```
