### ISSUE TITLE
applesencia.com - Loading incessantly iOS

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3492]
**Description**: The page is reloading incessantly
http://applesencia.com/2016/11/apple-podria-haber-iniciado-conversaciones-con-mclaren

Only iOS Safari 

**Adguard version**: 1.1.2.24

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.0.97 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.9 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.55 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.6.75 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.46 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.83 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.69 Enabled=YES

**Operating system**: iOS: 9.3.3

**Browser**: Safari

Customer ID: 1451994

**Comment by SBI-boy** [comment]
Just want to add that this also happens on the DNS adblocker, so other browsers are affected

**Comment by Alex-302** [comment]
Added to Mobile filter(for Android users)
```
@@||b.marfeel.com/statics/marfeel/gardac.js$domain=applesencia.com
```
added to DNS filter
```
@@||marfeel.com^
```
