### ISSUE TITLE
http://www.zdfans.com/ - Assistant doesn't show up

### ISSUE THREAD

**Issue by liangshengzero** [AdguardTeam/AdguardFilters#3493]
![ashampoo_snap_2016 11 21_14h50m01s_001_](https://cloud.githubusercontent.com/assets/17328925/20473261/60d78c58-affa-11e6-85dd-b7e5619641f4.jpg)

Adguard version: 6.1.258.1302

Filters list:
FilterId:2 Name: English filter
FilterId:104 Name: EasyList China
FilterId:118 Name: EasyPrivacy
FilterId:0 Name: User filter
FilterId:220 Name: CJX's Annoyance List
FilterId:100000 Name: EasyList Lite

Operating system: Microsoft Windows NT 10.0.14393.0

Chrome  54.0.2840.99 m (64-bit)

**Comment by Alex-302** [comment]
It is not filters issue. Please write in Windows repository
https://github.com/AdguardTeam/AdguardForWindows
