### ISSUE TITLE
http://www.yaplakal.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3495]
Некорректная блокировка на странице:
http://www.yaplakal.com/

Чёрный экран, кэш чистил фильтры обновлял.

![image1 1](https://cloud.githubusercontent.com/assets/15856304/20474600/e3d416c4-afcf-11e6-9bea-2ea3967e310e.png)

<details>
Application version: 1.1.1.54
Application lifetime: 2016-05-29 15:29:50 +0000

Device: iPad
Platform: iOS
OS: 10.1.1
ID: B5E3B17B-2353-4BC8-A1AD-A78C6DEB7166

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.0.93 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.8 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.65 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.6.74 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.89 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.43.8 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.82 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.69 Enabled=YES

**Comment by evgeniy-ADG** [comment]
Получили 2-3 жалобы, у меня как не повторялось, так и не повтоярется. Посмотри, что можно сделать.

**Comment by Alex-302** [comment]
Если повторяется постоянно, пусть попробуют найти фильтр, который приводит к такому результату. Затем нужно будет с этим фильтром повротить и отправить в поддержку сообщение с прикреплённой диагностической информацией.
