### ISSUE TITLE
MSN news - doesn't work

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3498]
https://play.google.com/store/apps/details?id=com.microsoft.amp.apps.bingnews&hl=en

![image](https://cloud.githubusercontent.com/assets/15856304/20476845/aa0024d6-afdb-11e6-83dd-293d271e017b.png)

<details>
{
  "advancedPreferences" : {
  },
  "androidVersion" : "6.0.1 (sdk=23)",
  "appLanguage" : "en",
  "applicationId" : "973c88bb8622368",
  "autoStartEnabled" : true,
  "browsingSecurityEnabled" : true,
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "samsung SM-N910F",
  "deviceSpeedRank" : 128,
  "dnsFilteringEnabled" : false,
  "enabledFilterIds" : [ 2, 3, 4, 10, 11 ],
  "environment" : "release",
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "iconType" : "DEFAULT",
  "installedPackages" : [ "com.mobeam.barcodeService;version=1.3.7  ;system=true", "com.samsung.android.provider.filterprovider;version=2.0.07;system=true", "com.samsung.android.writingbuddyservice;version=6.0.1;system=true", "com.monotype.android.font.rosemary;version=1.0.02-2;system=true", "com.sec.android.app.DataCreate;version=1.0;system=true", "com.sec.android.providers.mapcon;version=1.1.01-12;system=true", "com.skype.raider;version=7.25.0.308;system=false", "com.gd.mobicore.pa;version=3.0079 (51551);system=true", "com.sec.android.widgetapp.samsungapps;version=1.01.009;system=true", "com.google.android.youtube;version=11.43.54;system=true", "com.samsung.android.app.galaxyfinder;version=4.0.73;system=true", "com.sec.android.app.chromecustomizations;version=1.0.02;system=true", "com.sec.android.app.ocrseg;version=4.0.22;system=true", "com.android.providers.telephony;version=6.0.1;system=true", "com.sec.android.app.parser;version=1.0;system=true", "com.sec.android.providers.iwlansettings;version=1.1.01-10;system=true", "com.dictionary.paid;version=7.0.1;system=false", "com.google.android.googlequicksearchbox;version=6.8.21.21.arm;system=true", "com.vlingo.midas;version=11.7.0.1;system=true", "com.android.providers.calendar;version=6.0.1;system=true", "com.osp.app.signin;version=2.1.0356;system=true", "com.sec.android.directshare;version=2.5.0;system=true", "com.samsung.clipboardsaveservice;version=1.0;system=true", "com.sec.automation;version=1.0.1;system=true", "com.android.providers.media;version=6.0.1;system=true", "com.google.android.apps.docs.editors.docs;version=1.6.412.11.36;system=false", "com.google.android.onetimeinitializer;version=6.0.1;system=true", "com.sec.android.widgetapp.digitalclock;version=1.0.19;system=true", "com.android.wallpapercropper;version=6.0.1;system=true", "com.samsung.android.provider.shootingmodeprovider;version=1.0;system=true", "com.sec.android.app.wfdbroker;version=2.0.08;system=true", "com.biblediscovery;version=4.0;system=false", "com.clippersync.android.plugin;version=1.0.4;system=false", "com.samsung.android.app.withtv;version=1.0.82;system=true", "com.microsoft.amp.apps.bingnews;version=1.2.0;system=false", "com.samsung.android.hmt.vrshell;version=2.3.02;system=true", "com.sec.android.app.safetyassurance;version=1.0.28;system=true", "com.sec.factory.camera;version=1.0.16;system=true", "com.thomsonreuters.reuters;version=3.0.2;system=false", "com.viber.voip;version=6.5.0.3367;system=false", "org.simalliance.openmobileapi.service;version=4.0.0;system=true", "com.sec.usbsettings;version=1.0;system=true", "keepass2android.keepass2android;version=1.0.0-e;system=false", "com.samsung.android.easysetup;version=4.0.9329764;system=true", "com.android.documentsui;version=6.0.1;system=true", "com.sec.android.app.SPenKeeper;version=1.4.00-5;system=true", "com.android.externalstorage;version=6.0.1;system=true", "com.sec.android.easyonehand;version=2.0;system=true", "com.sec.factory;version=6.0.1;system=true", "tv.peel.smartremote;version=9.5.4.2;system=true", "com.android.htmlviewer;version=1.1.08;system=true", "com.whatsapp;version=2.16.352;system=false", "com.ghisler.android.TotalCommander;version=2.72;system=false", "com.android.mms.service;version=6.0.1;system=true", "com.android.providers.downloads;version=6.0.1;system=true", "org.me.five_stones_project;version=2.2.5;system=false", "com.samsung.ucs.agent.boot;version=6.0.1;system=true", "com.wsomacp;version=5.1.21;system=true", "com.sec.android.app.tourviewer;version=1.78.0;system=true", "com.paypal.android.p2pmobile;version=6.7.1;system=false", "com.sec.android.app.FlashBarService;version=1.0;system=true", "com.sec.android.Kies;version=1.0.17;system=true", "thefreedictionary.dictionary;version=6.0;system=false", "com.sec.android.app.voicenote;version=20.1.70-39;system=true", "com.sec.android.app.easylauncher;version=2.0.07;system=true", "com.aff.otpdirekt;version=12.1;system=false", "com.samsung.knox.rcp.components;version=2.6.04001020;system=true", "com.microsoft.office.officelens;version=16.0.7316.3028;system=false", "com.google.android.apps.genie.geniewidget;version=2.8.5 (136063537);system=false", "com.sec.android.widgetapp.easymodecontactswidget;version=1.0.28;system=true", "com.samsung.android.intelligenceservice2;version=2.3.06;system=true", "com.sec.di.SmartSelfShot;version=1.61;system=true", "com.samsung.android.MtpApplication;version=1.0;system=true", "com.sec.android.app.factorykeystring;version=6.0.1;system=true", "com.sec.android.app.samsungapps;version=4.2.01-13;system=true", "com.sec.android.emergencymode.service;version=6.0.1;system=true", "hu.khb;version=2.1.0;system=false", "com.google.android.configupdater;version=6.0.1;system=true", "com.sec.android.app.wlantest;version=1.0.0;system=true", "air.com.myheritage.mobile;version=3.7.1;system=false", "com.sec.android.widgetapp.SPlannerAppWidget;version=2.2.29;system=true", "com.sec.android.widgetapp.activeapplicationwidget;version=1.0.0;system=true", "com.sec.android.app.billing;version=3.0.34-7;system=true", "com.sec.android.app.minimode.res;version=6.0.1;system=true", "jp.ne.hardyinfinity.bluelightfilter.free;version=2.2.4;system=false", "com.android.defcontainer;version=6.0.1;system=true", "com.sec.android.daemonapp;version=160511.1926282;system=true", "telekom.hu.android.mobilvasarlas;version=2.8;system=false", "com.samsung.SMT.lang_en_gb_l01;version=1.2;system=false", "com.sec.enterprise.knox.attestation;version=1.0.2;system=true", "com.android.vending;version=7.1.15.I-all [0] [PR] 137333487;system=true", "com.android.pacprocessor;version=6.0.1;system=true", "com.sec.android.app.musiccontroller;version=1.0;system=true", "bbc.mobile.news.ww;version=3.9.4.42 GNL;system=false", "com.dsi.ant.service.socket;version=4.14.20;system=true", "com.sec.android.app.popupuireceiver;version=1.6;system=true", "com.sec.android.AutoPreconfig;version=2.0.0;system=true", "com.cnn.mobile.android.phone;version=2.9.4;system=false", "com.sec.android.app.soundalive;version=3.1.35;system=true", "com.aff.index.main;version=4.3;system=false", "com.sec.android.providers.security;version=1.0.01;system=true", "com.sec.android.provider.badge;version=1.0.11-1;system=true", "com.android.certinstaller;version=6.0.1;system=true", "com.samsung.android.securitylogagent;version=4.3.52;system=true", "com.android.carrierconfig;version=1.0.0;system=true", "com.google.android.marvin.talkback;version=5.0.4;system=true", "com.sec.android.app.taskmanager;version=2.1;system=true", "com.samsung.android.app.assistantmenu;version=1.5.75-0;system=true", "com.samsung.SMT;version=201503021;system=true", "com.samsung.dcm;version=2.0;system=true", "com.sec.android.ofviewer;version=1.110;system=true", "com.samsung.everglades.video;version=1.0.28;system=true", "android;version=6.0.1;system=true", "com.android.contacts;version=3.3.09;system=true", "com.flyersoft.moonreaderp;version=4.0.3;system=false", "com.samsung.hs20provider;version=1.0;system=true", "com.samsung.android.sm.devicesecurity;version=16.0.92;system=true", "hu.mavszk.vonatinfo;version=161107;system=false", "mobi.goldendict.android;version=1.6.5;system=false", "com.dsi.ant.sample.acquirechannels;version=01.00.05;system=true", "com.guardian;version=4.12.897;system=false", "com.samsung.android.smartface;version=1.0;system=true", "com.android.mms;version=1.0.0;system=true", "com.android.nfc;version=6.0.1;system=true", "com.android.stk;version=6.0.1;system=true", "com.sec.knox.foldercontainer;version=2.6.04001003;system=true", "com.android.backupconfirm;version=6.0.1;system=true", "com.sec.android.cloudagent.dropboxoobedummy;version=1.0;system=true", "com.samsung.klmsagent;version=2.6.032;system=true", "com.instagram.android;version=9.8.0;system=true", "flipboard.app;version=3.4.15;system=true", "com.sec.android.app.storycam;version=4.167;system=true", "com.sec.android.app.SecSetupWizard;version=1.0;system=true", "com.microsoft.office.onenote;version=16.0.7466.1778;system=false", "com.android.statementservice;version=1.0;system=true", "com.samsung.android.sdk.samsunglink;version=2.0.3715;system=true", "com.google.android.gm;version=6.10.23.137993986.release;system=true", "com.sec.android.app.hwmoduletest;version=6.0.1;system=true", "com.sec.bcservice;version=2.0;system=true", "com.sec.spen.flashannotate;version=1.0.34;system=true", "com.android.calendar;version=2.5.07;system=true", "com.sec.modem.settings;version=1.0.1;system=true", "com.android.phasebeam;version=1.0;system=true", "jp.ne.hardyinfinity.bluelightfilter.nightmode;version=2.0.2;system=false", "com.monotype.android.font.samsungsans;version=1.0.01-1;system=true", "com.appxy.tinyscan;version=3.4.3;system=false", "com.sec.android.app.sysscope;version=1.3.78;system=true", "com.sec.android.app.wallpaperchooser;version=3.0.10;system=true", "com.samsung.android.providers.context;version=2.0.8;system=true", "com.sec.android.app.servicemodeapp;version=6.0.1;system=true", "com.sec.android.preloadinstaller;version=6.0.1;system=true", "la.droid.qr;version=6.8;system=false", "com.sec.android.widgetapp.tapandpay;version=1.0.00;system=true", "com.google.android.setupwizard;version=2.0;system=true", "com.samsung.android.sdk.professionalaudio.utility.jammonitor;version=2.1.05;system=true", "com.sec.android.gallery3d;version=1.1.19;system=true", "com.sec.android.app.automotive.carmoderemote;version=2.0.2.1250855;system=true", "com.android.providers.settings;version=6.0.1;system=true", "com.qualcomm.qcom_qmi;version=1.0;system=true", "com.raraxy.angol.nyelvtan;version=3.0;system=false", "com.sec.app.TransmitPowerService;version=1.0;system=true", "com.android.sharedstoragebackup;version=6.0.1;system=true", "com.sec.android.widgetapp.dualclockdigital;version=1.0.08;system=true", "com.samsung.android.app.colorblind;version=2.3.11;system=true", "com.google.android.music;version=7.0.4007-1.J.3489099;system=true", "com.android.printspooler;version=1;system=true", "com.sec.providers.settingsearch;version=1.1;system=true", "com.samsung.android.hmt.vrsvc;version=2.4.04;system=true", "com.android.dreams.basic;version=6.0.1;system=true", "com.sec.android.widgetapp.ap.hero.accuweather;version=160512.1934765;system=true", "com.sec.android.app.music;version=16.1.63-24;system=true", "com.android.incallui;version=6.0.1;system=true", "com.sec.app.samsungprintservice;version=3.01.161021;system=true", "com.sec.android.omc;version=1.0.06-0;system=true", "com.sec.android.app.dictionary;version=2.5.32.seller;system=true", "com.android.inputdevices;version=6.0.1;system=true", "de.telekom.tsc;version=4.3.11;system=true", "com.sec.esdk.elm;version=5.0.07;system=true", "com.sec.android.app.videoplayer;version=1.0.44;system=true", "all.newspapers.world;version=2.4;system=false", "de.halfreal.clipboardactions;version=1.33;system=false", "com.merriamwebster.premium;version=3.3.1;system=false", "com.lge.app1;version=3.3.6;system=false", "com.sec.android.app.filtermanager;version=2.0.12;system=true", "com.adguard.android;version=2.7.220;system=false", "com.sec.android.service.sm;version=1.2.8;system=true", "com.samsung.android.app.simplesharing;version=2.2.03;system=true", "com.sec.android.gallery3d.panorama360view;version=1.0.2;system=true", "com.sec.smartcard.manager;version=2.0;system=true", "com.sec.allsharecastplayer;version=1.0.03;system=true", "com.dropbox.android;version=22.2.2;system=true", "com.sec.android.Preconfig;version=6.0.1;system=true", "com.sec.android.settingsmaps;version=1.0;system=true", "com.samsung.app.slowmotion;version=9.47;system=true", "org.wikipedia;version=2.4.160-r-2016-10-14;system=false", "com.google.android.apps.docs;version=2.4.382.19.36;system=true", "com.google.android.apps.maps;version=9.41.1;system=true", "com.google.android.apps.plus;version=9.1.0.138578129;system=true", "com.sec.enterprise.mdm.vpn;version=1.3;system=true", "hu.h2online.elsosegely;version=2.0.1;system=false", "com.samsung.android.app.pinboard;version=15.9.71;system=true", "com.dsi.ant.plugins.antplus;version=3.6.10;system=true", "com.samsung.android.personalpage.service;version=1.0;system=true", "com.microsoft.office.word;version=16.0.7426.1015;system=false", "com.sec.android.inputmethod;version=4.0;system=true", "com.samsung.android.app.advsounddetector;version=18.0.00-5;system=true", "com.astonsoft.android.essentialpim;version=4.2.6;system=false", "com.sec.android.app.clockpackage;version=2.0.80;system=true", "com.sec.android.RilServiceModeApp;version=6.0.1;system=true", "com.google.android.webview;version=54.0.2840.85;system=true", "com.sec.enterprise.knox.myknoxsetupwizard;version=1.0.17;system=true", "com.samsung.android.app.mirrorlink;version=1.0.44;system=true", "com.samsung.android.app.vrsetupwizardstub;version=1.2.13;system=true", "com.android.server.telecom;version=1.0.0;system=true", "com.google.android.syncadapters.contacts;version=6.0.1;system=true", "com.samsung.android.clipboarduiservice;version=6.0.1;system=true", "com.android.keychain;version=6.0.1;system=true", "com.android.chrome;version=54.0.2840.85;system=true", "com.samsung.android.asksmanager;version=1.0.08;system=true", "com.samsung.android.sm;version=16.0.92;system=true", "com.sec.android.widgetapp.locationwidget;version=1.0.05;system=true", "com.google.android.gms;version=10.0.84 (430-137749526);system=true", "com.google.android.gsf;version=6.0.1;system=true", "com.google.android.tts;version=3.10.10;system=true", "com.android.calllogbackup;version=6.0.1;system=true", "com.google.android.partnersetup;version=6.0.1;system=true", "com.sec.android.diagmonagent;version=4.1.13;system=true", "com.android.packageinstaller;version=6.0.1;system=true", "com.google.android.videos;version=3.20.10;system=true", "com.sec.android.easysidepanel;version=2.0;system=true", "com.sec.spp.push;version=1.6.01;system=true", "com.dsi.ant.server;version=3.0.0;system=true", "finarea.Poivy;version=5.77;system=false", "com.sec.android.widgetapp.digitalclockeasy;version=1.0.00;system=true", "com.sec.android.app.myfiles;version=2.0.68;system=true", "com.android.proxyhandler;version=6.0.1;system=true", "com.tranzmate;version=5.0.4.250;system=false", "com.radio.fmradio;version=8.0;system=false", "com.samsung.android.allshare.service.fileshare;version=2.5;system=true", "org.videolan.vlc;version=2.0.6;system=false", "com.sec.android.mimage.photoretouching;version=6.0.26;system=true", "com.sec.android.app.launcher;version=1.0.96;system=true", "uk.co.economist;version=2.1.8;system=false", "com.sec.android.automotive.drivelink;version=1.2.27.1458296;system=true", "com.samsung.helphub;version=1.0.0;system=true", "com.sec.android.app.sns3;version=2.0.13;system=true", "flipboard.boxer.app;version=2.1.18;system=true", "com.google.android.feedback;version=6.0.1;system=true", "com.google.android.apps.photos;version=2.4.0.138833446;system=true", "com.google.android.calendar;version=5.6.6-137495241-release;system=false", "com.google.android.syncadapters.calendar;version=5.2.3-99827563-release;system=true", "com.android.managedprovisioning;version=6.0.1;system=true", "com.samsung.android.app.filterinstaller;version=2.0.00;system=true", "com.audials;version=6.3.529.0;system=false", "com.hancom.office.viewer;version=7.0.160212;system=true", "com.sec.android.providers.tasks;version=6.0.1;system=true", "com.sevenlynx.idioms;version=1.2;system=false", "com.sec.android.app.sbrowser;version=4.0.20-6;system=true", "com.monotype.android.font.chococooky;version=1.0.03-3;system=true", "com.lifevibes.trimapp;version=174.7.ms_hw;system=true", "com.android.dreams.phototable;version=6.0.1;system=true", "com.bloomberg.android.plus;version=2.22.303601.0.62820da;system=false", "com.sec.android.service.health;version=2.1.1.001;system=true", "com.samsung.safetyinformation;version=1.0.04-0;system=true", "com.facebook.katana;version=103.0.0.20.72;system=false", "com.sec.android.app.ringtoneBR;version=6.0.1;system=true", "com.android.noisefield;version=1.0;system=true", "com.origo.laboratory;version=1.0;system=false", "com.android.providers.partnerbookmarks;version=6.0.1;system=true", "com.facebook.pages.app;version=93.0.0.23.70;system=true", "com.google.android.gsf.login;version=6.0.1;system=true", "com.cleanmaster.sdk;version=5.5.10;system=true", "com.samsung.android.keyguardwallpaperupdator;version=1.0.03;system=true", "com.samsung.android.app.accesscontrol;version=1.5.13-26;system=true", "yo.app.free;version=1.27.7;system=false", "com.android.wallpaper.livepicker;version=6.0.1;system=true", "com.samsung.android.beaconmanager;version=4.0.9329764;system=true", "com.sec.enterprise.mdm.services.simpin;version=6.0.1;system=true", "com.samsung.ucs.ucspinpad;version=1.0;system=true", "com.android.apps.tag;version=2.0.02;system=true", "com.facebook.orca;version=97.0.0.13.71;system=false", "com.samsung.android.app.FileShareClient;version=2.5;system=true", "com.facebook.system;version=D17.0;system=true", "com.socialnmobile.colordict;version=4.4.1;system=false", "com.sec.android.app.popupcalculator;version=3.2.18;system=true", "com.sec.android.soagent;version=3.1.12;system=true", "com.samsung.android.scloud.backup;version=6.4.03;system=true", "com.samsung.android.fmm;version=6.0.41;system=true", "com.samsung.android.mdm;version=1.0;system=true", "com.urbandictionary.android;version=2.0.1;system=false", "com.sec.android.app.shealth;version=5.3.1.0005;system=true", "com.sec.penup;version=2.3.07;system=true", "com.sec.phone;version=1.0;system=true", "english.grammar.test.app;version=1.8.6;system=false", "com.google.android.apps.translate;version=5.5.0.RC04.137189260;system=false", "com.samsung.android.app.scrollcapture;version=1.0.46;system=true", "com.adobe.reader;version=16.4;system=false", "com.samsung.knox.appsupdateagent;version=2.6.04001008;system=true", "com.google.android.backuptransport;version=6.0.1;system=true", "com.sec.knox.knoxsetupwizardclient;version=2.6.04001009;system=true", "com.modelmakertools.simplemindpro;version=1.14.0;system=false", "com.evernote;version=7.9.6;system=true", "com.visionobjects.resourcemanager;version=1.5.0;system=true", "com.bitknights.betegseglexikon;version=1.4.2;system=false", "com.samsung.android.scloud;version=2.1.10;system=true", "com.sec.app.RilErrorNotifier;version=1.0.0;system=true", "com.android.bookmarkprovider;version=6.0.1;system=true", "com.android.settings;version=6.0.1;system=true", "com.samsung.app.newtrim;version=1.0.22;system=true", "com.akkzrt.szotarhuen012014a;version=1.1.0;system=false", "com.sec.android.mmapp;version=1.0.13;system=true", "com.coolmobilesolution;version=3.3;system=false", "com.sec.android.app.bluetoothtest;version=6.0.1;system=true", "com.samsung.android.intelligenceservice;version=2.2.02;system=true", "com.samsung.android.sm.policy;version=1.0.07;system=true", "fi.rojekti.clipper;version=2.4.7;system=false", "com.sec.android.emergencylauncher;version=1.0.35;system=true", "com.google.android.apps.books;version=3.10.29;system=true", "com.sec.hearingadjust;version=4.0.07;system=true", "com.qualcomm.location;version=1.0;system=true", "com.samsung.android.dlp.service;version=1.0;system=true", "com.samsung.android.bbc.bbcagent;version=2.0;system=true", "com.samsung.android.nearby.mediaserver;version=2.1;system=true", "com.sec.spen.flashannotatesvc;version=1.0.10;system=true", "com.sec.android.cloudagent;version=1.2.3;system=true", "com.wssnps;version=6.0.88;system=true", "com.samsung.android.app.watchmanagerstub;version=1.1.15-12310;system=true", "com.lgi.orionandroid;version=2.3.12 Production ;system=false", "com.sec.android.app.interactivekeyguardtutorial;version=1.0;system=true", "com.policydm;version=4.1.80;system=true", "com.sec.android.app.SmartClipService;version=1.0.31;system=true", "com.samsung.android.app.FileShareServer;version=2.5;system=true", "com.samsung.android.sdk.professionalaudio.app.audioconnectionservice;version=2.1.00;system=true", "com.samsung.android.service.aircommand;version=1.0;system=true", "com.enhance.gameservice;version=1.0.70;system=true", "com.quoord.lawGuide;version=2.2;system=false", "com.sec.android.app.snsimagecache;version=1.0.01;system=true", "com.samsung.SMT.lang_hu_hu_l01;version=1.2;system=false", "com.qualcomm.qti.services.secureui;version=1.0;system=true", "com.android.vpndialogs;version=6.0.1;system=true", "hu.tesco.clubcard;version=1.1.51;system=false", "com.wordwebsoftware.android.wordweb;version=3.2;system=false", "com.aaron.parkingbudapest;version=1.0.9;system=false", "com.google.android.keep;version=3.3.431.0;system=false", "com.google.android.talk;version=14.0.136618992;system=true", "hu.hvg.android;version=2.1.7;system=false", "com.android.email;version=5.0.0.0400;system=true", "com.android.phone;version=1.0.0;system=true", "com.oup.gab.odquicksearch;version=1.2.0;system=false", "com.android.shell;version=6.0.1;system=true", "com.here.app.maps;version=2.0.10914;system=false", "com.nerddevelopments.taxidriver.orderapp;version=4.5.5;system=false", "com.android.providers.userdictionary;version=6.0.1;system=true", "com.sec.enterprise.knox.cloudmdm.smdms;version=1.7.7;system=true", "com.arcsoft.magicshotstudio;version=3.0.0.80;system=true", "com.ideashower.readitlater.pro;version=6.4.2.5;system=false", "com.wssyncmldm;version=1.5.33;system=true", "com.android.location.fused;version=6.0.1;system=true", "com.samsung.android.sm.provider;version=16.0.37;system=true", "com.sec.face;version=1.0;system=true", "com.android.systemui;version=6.0.1;system=true", "com.sec.android.app.personalization;version=6.0.1;system=true", "com.monotype.android.font.cooljazz;version=1.0.03-3;system=true", "com.android.exchange;version=5.0.0.0400;system=true", "com.android.bluetoothmidiservice;version=6.0.1;system=true", "com.app.englishidioms;version=2.0;system=false", "com.facebook.appmanager;version=D17.0;system=true", "com.sec.android.provider.logsprovider;version=2.0;system=true", "com.got.anonymcallfree;version=1.2;system=false", "com.sec.android.app.SamsungContentsAgent;version=1.0.03;system=true", "com.samsung.aasaservice;version=4.0;system=true", "com.samsung.android.allshare.service.mediashare;version=2.2;system=true", "com.sec.android.app.mt;version=1.0.01-0;system=true", "com.bsplayer.bspandroid.free;version=1.27.190;system=false", "com.sec.android.provider.emergencymode;version=1.0;system=true", "com.google.android.play.games;version=3.9.08 (3448271-030);system=true", "com.samsung.android.fingerprint.service;version=1.1.0;system=true", "com.sec.knox.switcher;version=2.6.04001008;system=true", "com.sec.android.app.camera;version=3.0;system=true", "com.google.android.apps.magazines;version=4.0.0;system=true", "com.android.bluetooth;version=6.0.1;system=true", "hu.donmade.menetrend.budapest;version=2.1.0.159;system=false", "com.qualcomm.timeservice;version=6.0.1;system=true", "com.qualcomm.atfwd;version=6.0.1;system=true", "com.android.providers.contacts;version=6.0.1;system=true", "com.sec.android.app.magnifier;version=1.4.14;system=true", "com.sec.android.widgetapp.webmanual;version=1.0.07;system=true", "com.samsung.sec.android.application.csc;version=6.0.1;system=true", "com.android.captiveportallogin;version=6.0.1;system=true", "com.sec.android.filter;version=2.0.01;system=true", "com.samsung.android.sconnect;version=3.0.6914363;system=true", "com.samsung.android.coreapps;version=2.3.12;system=true", "com.sec.android.easysettings;version=6.0.1;system=true", "hr.asseco.android.mtoken.cib;version=1.0.2;system=false", "cn.wps.moffice_eng;version=9.9.8;system=false", "com.washingtonpost.rainbow;version=1.9.2;system=false", "com.samsung.android.snote;version=5.1.02-18;system=true", "com.samsung.location;version=v5.12h;system=true", "com.sec.android.mimage.sstudio;version=1.7.2;system=true" ],
  "installerPackage" : null,
  "kernelVersion" : "3.10.40-9428727",
  "premium" : true,
  "proxyMode" : false,
  "proxyPort" : 8080,
  "proxySetupManualMode" : false,
  "referrer" : null,
  "sendAnonymousStatistics" : true,
  "showUsefulAds" : true,
  "sourceApk" : "/data/app/com.adguard.android-2/base.apk",
  "sslMitmConfiguration" : null,
  "statisticsInfo" : "Blocked threats:0; Blocked banners:185306; Traffic saved:4933610496;",
  "trial" : false,
  "updateChannel" : "RELEASE",
  "upstreamProxySettings" : null,
  "userfilter" : [ ],
  "versionName" : "2.7.220",
  "whitelist" : [ ]
}

**Comment by Alex-302** [comment]
fixed
