### ISSUE TITLE
Video ads in Angry Birds app for iOS

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#3501]
https://itunes.apple.com/app/angry-birds/id343200656?mt=8

Please test it.

Original thread:
https://forum.adguard.com/index.php?threads/16272/

**Comment by gshumihin** [comment]
here's fiddler log: (ads were shown at 17:40-17:41)
[angrybirds.saz.txt](https://github.com/AdguardTeam/AdguardFilters/files/603858/angrybirds.saz.txt)
@Alex-302 can you take a look please?

**Comment by Alex-302** [comment]
```
iosads24.adcolony.com
```
this domain should be blocked by dns filter rule
```
||adcolony.com^
```

**Comment by Alex-302** [comment]
@gshumihin

**Comment by gshumihin** [comment]
Here's screenshot of DNS log:
<details>
![slack for ios upload 1](https://cloud.githubusercontent.com/assets/8577547/20593884/085a5b58-b245-11e6-9dd1-3285497bddc5.jpg)
</details>

**Comment by gshumihin** [comment]
@Alex-302

**Comment by Alex-302** [comment]
> And there's no requests for adcolony.com.

maybe you did not clear DNS cache.
I see it in your Fuddler log
http://img.ii4.ru/images/2016/11/24/795304_kiss_115kb.png
video is loaded from adcolony.com
Please describe how to reproduce that video and I will check it.

**Comment by gshumihin** [comment]
1. Install https://itunes.apple.com/app/angry-birds/id343200656?mt=8
2. Play this game for 5-10 minutes.
3. At some point u'll se video ads

**Comment by Alex-302** [comment]
Found another domains
```
adserver.unityads.unity3d.com
cdn.unityads.unity3d.com
```
Please try to block them

**Comment by vbagirov** [comment]
@vozersky take a look please.

**Comment by vozersky** [comment]
blocking  
`adserver.unityads.unity3d.com
cdn.unityads.unity3d.com`
didn't help

**Comment by Alex-302** [comment]
are they marked as blocked in dns log?
