### ISSUE TITLE
markup question

### ISSUE THREAD

**Issue by bogachenko** [AdguardTeam/AdguardFilters#35029]
How to convert this rule to your markup?

`shitsite.com##^script:has-text(shit-text)`

I tried like this
`shitsite.com##^script:contains(shit-text)`
and this
`shitsite.com##script:contains(shit-text)`
 but failed.
Нow to do it? @Alex-302 @AdamWr @BlazDT

**Comment by Alex-302** [comment]
`shitsite.com$$script[tag-content="shit-text"]`

**Comment by bogachenko** [comment]
не работает

**Comment by bogachenko** [comment]
почему не знаю

**Comment by Alex-302** [comment]
какой браузер?

**Comment by bogachenko** [comment]
ff

**Comment by Alex-302** [comment]
в квантуме должно работать

**Comment by Alex-302** [comment]
и обязательно с ограничением на домен

**Comment by bogachenko** [comment]
ну на проверь, не работает

`narod.i.ua$$script[tag-content="zmctrack"]`

**Comment by Alex-302** [comment]
в коде этого видно не будет. В журнале нужно проверять

**Comment by Alex-302** [comment]
ещё нужно ограничение длины скрипта указать, т.к. он длиннее 300 символов, включая тег

**Comment by bogachenko** [comment]
>в коде этого видно не будет. В журнале нужно проверять
![Безымянный](https://user-images.githubusercontent.com/8535285/59202361-05f31100-8be8-11e9-91cb-3af7820f48e2.png)

**Comment by Alex-302** [comment]
вот такой результат должен быть
 ![image](https://user-images.githubusercontent.com/8361299/59202365-f900fe00-8ba4-11e9-89d0-78493979b619.png)

**Comment by bogachenko** [comment]
блтяь

**Comment by bogachenko** [comment]
старые не удалил

**Comment by bogachenko** [comment]
найс... спасибо алекс
