### ISSUE TITLE
mathelounge.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3504]
**Site**: https://www.mathelounge.de/397604/was-ist-der-kehrwert-von-3-3
**Description**: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20489405/d57cc090-b00a-11e6-9356-1c1dd14cabea.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20489483/19234a08-b00b-11e6-898b-796bab407cd1.png)

</details>

________________

**Adguard version**: 6.1.281.1519

**Filters list**: 
English filter 1.1.1.3
Spyware filter 1.0.9.9
Social media filter 1.0.14.71
Annoyances filter 1.0.6.77
German filter 1.0.28.64
Mobile ads filter 1.0.5.86
Safari filter 1.0.1.70

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
mathelounge.de##div[class^="adholder"]
