### ISSUE TITLE
Missed Admob plugin

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardFilters#35051]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Admob plugin missed in the app called OptionScan (com.vedantatech.optionscan):
http://adlic.rjfun.com/adlic

* **Expected behaviour**: 

Expect AdGuard to detect Admob plugins

***Steps to reproduce the problem***:

Simply open the app

***System configuration***

**Filters:**

Too many to list. I use ALL of the recommended filters + all optional ones except for the deprecated ones. As for language I use all recommended + most EasyList (62 filters in all).

Operating System: Android 8.0.0
AdGuard version: 3.1.0 Beta
AdGuard mode (Android only): VPN
Filtering quality (Android only): High-quality
HTTPS filtering (Android only): On, Default
AdGuard DNS: Default

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Hi
Please provide download link or APK file(without malware:) ).
