### ISSUE TITLE
https://apps.crashlytics.com - add to list of exceptions

### ISSUE THREAD

**Issue by Joss** [AdguardTeam/AdguardFilters#3508]
**Description**: 
No way to download crashlytics app on Android with Adguard

**Current behaviour**:
Site doesn't allowed to establish connection

Screenshot:

<details>
<img src=http://ipic.su/img/img7/fs/screenshot_99.1479752382.jpg>
</details>

**Expected behaviour**: 
Page open 

Screenshot:

<details>
<img src=http://ipic.su/img/img7/fs/screenshot_100.1479752409.jpg>
</details>

**Steps to reproduce the problem**:

* https://apps.crashlytics.com/register/<removed key>/download?utm_medium=email&utm_source=new_release
*  
  

**Adguard version**:
2.8b

**Filters list**:
ru, en

**Operating system**:
Android 7.1

**Browser**:
Chrome

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
hi
try
```
@@||apps.crashlytics.com^$domain=crashlytics.com
```
then run and check this app. It need some exclusions too, I think.
