### ISSUE TITLE
http://kukuruza.me/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3510]
**Description**: Расширение.
http://kukuruza.me/?id=senbng&user=5833f96439489
При выборе определенного плеера и надатии на плей открывается окно другого сайта.

Screenshot:
<details>

![screenshot_1](https://cloud.githubusercontent.com/assets/18548949/20515305/a5eaeb74-b099-11e6-870c-a44818faa0dd.jpg)

</details>  

**Adguard version**: 2.4.14

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня адрес плеера по dns не резолвится
http://ipic.su/img/img7/fs/kiss_22kb.1479816957.png
кликандера нет

**Comment by vgavrish** [comment]
Там есть ниже кнопочка "Сменить источник". Нажми до появления какого-то плеера

**Comment by Alex-302** [comment]
поправил
