### ISSUE TITLE
[Extension] kinopoisk.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#3511]
Верхний баннер блокируется, но при клике по пустому полю открывается новая вкладка. 

В разделе "кадры" или "постеры" какого-нб фильма фотографии не листаются кликом по ним. Видео - https://cloud.mail.ru/public/4zJn/zZsPJivGM

Тестировалось с Opera extension

**Comment by Alex-302** [comment]
пусть скрины даст, которые перечислены в шаблоне.

**Comment by Alex-302** [comment]
У меня сайт работает корректно

**Comment by vbagirov** [comment]
У меня перестало повторяться с баннером, повторяется с неперелистыванием кадров/постеров кликами по фото.

**Comment by Alex-302** [comment]
И перелистывается нормально.
