### ISSUE TITLE
http://m.spiegel.de/  - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3512]
http://m.spiegel.de/#spRedirectedFrom=www&referrrer=

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/20522069/ecdb81fc-b0b6-11e6-93b1-b32fc3842f1a.png)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 92529422-36B9-4466-8A87-A60F775DF63D

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.10 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.12 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.72 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.6.81 Enabled=YES
ID=6 Name="German filter" Version=1.0.28.68 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.88 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.70 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.18 Enabled=YES
**ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.55 Enabled=YES** - this one's breaking the site

</details>

**Comment by Alex-302** [comment]
we need two screenshots - with correctly loaded page and broken

**Comment by dzamyshlyayeva** [comment]
http://www.spiegel.de/politik/ausland/recep-tayyip-erdogan-plant-keinen-deutschlandauftritt-a-1140218.html - missed ad on page 

<details>

![image](https://cloud.githubusercontent.com/assets/23372054/24284129/4eb09834-1072-11e7-9dca-f09a5ebddb60.png)

</details>

Application version: 1.1.5.65

Device: iPad
Platform: iOS
OS: 10.2.1
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.7.40 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.43 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.83 Enabled=YES
ID=6 Name="German filter" Version=1.0.30.76 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.23 Enabled=YES

Ticket ID 1528908

**Comment by Alex-302** [comment]
Not reproduced. Ad  and share buttons are blocked.
Check for exclusions in white list and user filter. Also user can try to enable simplified/optimized filters.

**Comment by dzamyshlyayeva** [comment]
emailed.
