### ISSUE TITLE
if Adguard update filter , firefox be "can not connect netword"

### ISSUE THREAD

**Issue by we684123** [AdguardTeam/AdguardFilters#35133]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
i use firefox now , and if Adguard update filter
firefox will "can not connect netword" ( like to video 1:30 )
Even i exclude "firefox" ( "setting" -> "netwoker" -> "list of filtered applications" -> "untick" )  ( like to video 1:02 )

debug log will send email to devteam@adguard.com
and title is 【if Adguard update filter , firefox be "can not connect netword" debug log】

* **Current behaviour**: 
Adguard update filter
[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 
Adguard update filter and firefox be working normally

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

youtube video : 
https://youtu.be/mS_j6Y677DU

1. open AdGuard -> "setting" -> "general setting" -> "reset setting to defaults"-> (AdGuard restart) 

2. AdGuard  -> "setting" -> "general setting" -> "change language" -> "englist"

3. AdGuard  -> "setting" -> "general setting" -> "change logging level to debug"

4. AdGuard  -> "setting" -> "netwoker" -> "list of filtered applications" -> "untick firefox and https"

5. open firefox -> open youtube -> open a video -> open a new video on new tab(now have two tab and can see AdGuard assistant is not wokr on firefox )

6. open AdGuard -> "update" -> (can see "AdGuard base filter" is update)

7. firefox -> open new video on new tab -> (firefox can't connect netword)

8. firefox -> back to old tab -> click new video -> (firefox can't connect netword)

9. close firefox

10. open AdGuard -> "setting" -> "advanced setting" -> "exclude app from filtering by entering the full path" -> "C:\Program Files\Mozilla Firefox\firefox.exe" -> save

11. open AdGuard -> "setting" -> "general setting" -> "reset setting to defaults"-> (AdGuard restart) 

12. open AdGuard -> "setting" -> "advanced setting" -> "exclude app from filtering by entering the full path" -> (can see it not be reset setting to defaults , still kept) -> save

13. AdGuard  -> "setting" -> "netwoker" -> "list of filtered applications" -> "untick firefox and https"

14. open firefox -> open youtube -> open a video -> open a new video on new tab(now have two tab and can see AdGuard assistant  is not wokr on firefox )

15. open AdGuard -> "update" -> (can see "AdGuard base filter" is update)

16. firefox -> open new video on new tab -> (firefox can connect netword )

***System configuration***

OS : win7 Professional version service pagk 1
firefox(x64) : 
68.0b9 and 67.01
nightly(69.0a1)
dev(68.0b7)
all can reproduce the problem

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  win7 Professional version service pagk 1
Operating system version (Android/iOS) | Not Android/iOS
Browser:                               | firefox(x64): 68.0b9 and 67.01、nightly(69.0a1)、dev(68.0b7)
AdGuard version:                       | 7.0.2693.6661 RELEASE(CL 1.3.351)
Filters enabled:                       | all is defaults
AdGuard mode (Android only):           | not
Filtering quality (Android only):      | not
HTTPS filtering (Android only):        | not
Simplified filters (iOS only)          | not
AdGuard DNS:                           | Default 
Stealth mode options (Windows only)    | not open
Helpdesk ID (if exists):               | nano

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by ameshkov** [comment]
You should update AdGuard to 7.1
