### ISSUE TITLE
androidinsider.ru - некорректная блокировка

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#3514]
Description: блокирует доступ к сайту
http://androidinsider.ru/reklama/chernaya-pyatnitsa-po-kitayski-uspey-kupit-krutyie-gadzhetyi.html

Screenshot: 
<details>
![image](https://cloud.githubusercontent.com/assets/23372054/20532594/40251162-b0e3-11e6-8add-e6b56fff5d17.png)

</details>

Application version: 1.1.1.54

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.6 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.11 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.71 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.6.80 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.43.17 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.88 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.70 Enabled=YES

Customer ID: 1452358

**Comment by Alex-302** [comment]
Добавил в фильтр Сафари
```
@@||androidinsider.ru/reklama/$~urlblock,~elemhide
```
пусть отпишется
