### ISSUE TITLE
videoframe.blue пропуск рекламы (в виде ютуб плеера)

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#3515]
Перед запуском видео, заставляют смотреть ролик с ютуба определенное количество секунд.

Ссылка (к примеру) http://videoframe.blue/?kp_id=527
#Ads

**UPD:**
А еще на hdgo.cc блокируется выбор качества из за фильтров "Английский фильтр" и "EasyList".
Вот видео для примера http://hdgo.club/video/Q298nQsLY481iJzUPrlwVnRh6EqC8Ctd/5937/ _(даю через зеркало, потому что через оригинальный домен не позволяет смотреть)_
Плюс при первом переходе по ссылке, и клике по видео _(или даже без клика)_, открывается сторонняя рекламная вкладка _(после обновления страницы больше не повторяется, но через некоторое время снова)_

**UPD2:**
_Кто нибудь? Помогите..
И подскажите - как тут добавлять лейблы? никак не пойму... или я не должен этого делать?_

**Comment by Smorvel** [comment]
Кто нибудь? Помогите..
И подскажите - как тут добавлять лейблы? никак не пойму... или я не должен этого делать?

**Comment by Alex-302** [comment]
> http://videoframe.blue/?kp_id=527

пока не разобрался как заблокировать.


> hdgo.cc

ссылку на страницу тоже дайте, у меня коряво по этой ссылке загружается, не видно органов управления.


> как тут добавлять лейблы?

гостям - никак. Так на всём GitHub, чтоб ненужных изменений избежать.

**Comment by Smorvel** [comment]
> ссылку на страницу тоже дайте, у меня коряво по этой ссылке загружается, не видно органов управления.
На какую страницу? оригинальнал выглядит так же, только вместо club сс http://hdgo.cc/video/Q298nQsLY481iJzUPrlwVnRh6EqC8Ctd/5937 но по ней видео закрыто.

**Comment by Alex-302** [comment]
Ок, понял. Исправление добавил в русский фильтр.

**Comment by Smorvel** [comment]
hdgo снова пропала возможность выбора качества, и при первом клике по видео, открывается сторонний сайт с рекламой.
Возможно они следят за темой...

**Comment by Alex-302** [comment]
возможно проверяют как с блокировщиками работает. Попроавил.

**Comment by Smorvel** [comment]
С videoframe может кто-то разобраться?

**Comment by Alex-302** [comment]
> Ссылка (к примеру) http://videoframe.blue/?kp_id=527

Попробуйте такое:
```
||videoframe.blue^$replace=/\{timer:\d\d\, hardTimer\:\d\d\,/\{timer:0\, hardTimer\:0\,/i,important
```
У вас программа, надеюсь?

**Comment by Smorvel** [comment]
Да программа, спасибо.
А что на счет общих правил, не получится ничего сделать?

**Comment by Alex-302** [comment]
Каких общих?
Это добавил в фильтр.

**Comment by Smorvel** [comment]
Ну я про фильтры adguard (русский фильтр)..

**Comment by Alex-302** [comment]
тогда закрываю
