### ISSUE TITLE
[Windows] www.netflix.com - Login blocked

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#3516]
![](http://i.imgur.com/SJ70k1U.png)

https://www.netflix.com/de/Login

**Adguard version**: 6.1.290.1526

**Operating system**: Windows 10

**Browser**: Chrome

Works fine with:
```@@||netflix.com/*/Login ```

**Comment by Alex-302** [comment]
Which rule blocks it? I can't reproduce.

**Comment by Vincent-Michael** [comment]
![](http://i.imgur.com/bP5Uw5n.png) @Alex-302

**Comment by Alex-302** [comment]
Replaced by 
```
||netflix.com/*/log|
```
please check after updates.
