### ISSUE TITLE
http://auth.wi-fi.ru - Incorrect blocking 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3517]
**Description**: Incorrect blocking on the page 
http://auth.wi-fi.ru/auto_auth

Screenshot: 

<details>

![image1](https://cloud.githubusercontent.com/assets/17504743/20547723/d870be60-b126-11e6-874b-6a10d342c235.PNG)

</details>

**Adguard version**:  1.1.1.54

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.0.95 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.8 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.67 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.43.10 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.69 Enabled=YES

**Operating system**: iOS 10.2

Customer ID: 1144547

**Comment by Alex-302** [comment]
Даже не знаю, как помочь. Вы как повторяли?

**Comment by LeshaYulin** [comment]
Добрый день!
Есть ли все таки идеи насчет того, как можно решить данную проблему?
К сожалению, она никуда не пропала и возникает до сих пор.

**Comment by Alex-302** [comment]
@LeshaYulin после ввода капчи пускает в интернеты? Есть ли сторонние блокировщики или приложение для автовхода?

**Comment by LeshaYulin** [comment]
@Alex-302 после ввода в интернет пускает, он работает. Из блокировщиков установлен только Adguard для Safari. Каких-либо других сторонних приложений для автовхода и пр. нет. Раньше подобных проблем не возникало. Она появилась не так давно.

**Comment by Alex-302** [comment]
а бел блокировщиков есть запрос? Они могли просто авторизацию прикрыть капчей.

**Comment by LeshaYulin** [comment]
Что-то у них изменилось. Теперь авторизация происходит по другому и сообщение с просьбой ввести код не появляется.

**Comment by Alex-302** [comment]
У них разные сегменты сети могут по-разному работать. Когда-то катался, на моей ветке часто глючила авторизация. Переходил на другую - там работала.
