### ISSUE TITLE
Ad blocking failed in below link

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#35176]
@jeevaraj94 commented on [Thu Jun 13 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2793)

### Steps to reproduce

1.visit the link
https://www.nakkheeran.in/24-by-7-news/thamizhagam/if-dmk-involved-cinema-associations-elections
![IMG_20190613_144103](https://user-images.githubusercontent.com/48148892/59420756-0f000000-8deb-11e9-9e0b-2040b98dfcee.jpg)

2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version: 
* Adguard filtering mode: (e.g. Local VPN / HTTP Proxy (Auto/Manual))
* Device model: (e.g. Google Pixel)
* Operating system and version: (e.g. Android 7.1.2)
* Root access:  (e.g. Yes / No)
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?:

**Comment by AdamWr** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/35175
