### ISSUE TITLE
http://losmovies.club/ - Missed ads (redirections) 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3518]
**Description**: When you click on some movie on this site
http://losmovies.club/
the movie opens in a new tab and the old tab redirects to different websites. 
It doesn't happen every time. 

**Adguard version**: 1.3.0

**Filters list**:
English
Spyware
Social media
Annoyances
Russian
Experimental

**Operating system**:  macOS 10.12.1

**Browser**: Chrome

Customer ID: 1424790

**Comment by Alex-302** [comment]
fixed
