### ISSUE TITLE
http://www.umj.com.ua/ - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3519]
http://www.umj.com.ua/article/6962/voprosy-diagnostiki-i-terapii-neproduktivnogo-kashlya

![image](https://cloud.githubusercontent.com/assets/15856304/20552931/732f406c-b158-11e6-9afd-a353bc252423.png)

<details>
Russian

**Comment by Alex-302** [comment]
fixed
