### ISSUE TITLE
Openload.co ads iphone

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#3520]
phox2ey.bid
555fff555f.net

http://www.lfporn.com/kira-parvati-nancy-a-wonderful-wakeup/

**Comment by Alex-302** [comment]
@seanl-adg please take a look. You can check it in Windows with exclusion
```
@@||openload.co^$content,jsinject,generichide
```
and disabled exclusion in English filter
```
@@||openload.co^$generichide
```

**Comment by seanl-adg** [comment]
Can you elaborate more about ads you are experiencing?
I only found a popup that is blocked by JS rules in other platform.

**Comment by Alex-302** [comment]
If you don't have Safari browser, you should disable JS rules.
Two rules are not equal to `$content,jsinject,generichide`
```
@@||openload.co^$content,jsinject
@@||openload.co^$generichide
```

**Comment by jo2dan23** [comment]
I use ghostery. And those domains appeared in my dns logs.

**Comment by jo2dan23** [comment]
I use ghostery. And those domains appeared in my dns logs.

**Comment by Alex-302** [comment]
```
||phox2ey.bid^$third-party
||555fff555f.net^$third-party
```
added
