### ISSUE TITLE
ADG ломает отображение полосы просмотренного видео на YouTube.

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3522]
### При включенном  Adguard (НЕ ВСЕГДА, во всяком случае у меня так, связь не нашел), отображается полоса просмотренных видеороликов на YouTube. Это будет видно на скриншоте, то есть, иногда полностью полоса отображается, но зачастую она остается короткой.

![2016-11-23_16-55-50](https://cloud.githubusercontent.com/assets/16462533/20567472/7c12f342-b1a1-11e6-9f12-b8fbf9f25c35.png)

<details>

**Если, ADG отключен, после просмотра видео, полоса полностью заполнена, если просмотрел половину ролика, тогда полоса на половине, как бы, дает знать, сколько было просмотрено, при включенном ADG, не срабатывает. Отключал антитрекинг, не помогло. Отключал английский фильтр, также, не помогло.**

## Фильтры:
**Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский**

P.S. У Наших агентов, проблема также повторилась.

</details>

**Comment by Alex-302** [comment]
Какой фильтр портит?
У меня такие же включены, и всё нормально
http://ipic.su/img/img7/fs/kiss_125kb.1479916095.png

**Comment by vgavrish** [comment]
Опять та же ситуация
нужно отключить Фильтр счетчиков и аналитики и просмотреть полностью видео, тогда появится цельная красная полоса: http://prntscr.com/dyevhm
Если включить фильтр и снова перейти на видео и просмотреть его до конца, то полоса будет на середине записи. Проверять нужно в обычной вкладке Хрома

**Comment by Alex-302** [comment]
```
@@||youtube.com/api/stats/watchtime?$domain=youtube.com
@@||s.youtube.com/api/stats/playback?
```
должно помочь. Добавил.

**Comment by vgavrish** [comment]
да, правила помогают
