### ISSUE TITLE
@Upgraider они борятся с блокировщиками, как и на всех своих сервисах.

### ISSUE THREAD

**Issue by Upgraider** [AdguardTeam/AdguardFilters#35236]
@Upgraider они борятся с блокировщиками, как и на всех своих сервисах.

_Originally posted by @Alex-302 in https://github.com/AdguardTeam/AdguardFilters/issues/33027#issuecomment-502166181_

Я это все понимаю. Только не понимаю, почему "блокировщики" с этим не борятся?

**Comment by Alex-302** [comment]
Не нужно новую задачу создавать, отвечать можно в той, где я писал.



> Только не понимаю, почему "блокировщики" с этим не борятся?

борятся. Но им это делать проще. Они используют собственную систему, а не сторонние скрипты, которые можно просто заблокировать. Программой эта реклама надёжнее блокируется, а расширение обойти для них - секундное дело.
