### ISSUE TITLE
[Question] Redirect a url with a filter?

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardFilters#3525]
Sorry if this question sounds dumb but i just want the url
```
://myteamspeak.com*platforms=WINDOWS_X86_64
```
redirect to
```
https://r4p3.net/categories/addons.71/
```

P.S. How do i return some plain text content whenever `http://news.teamspeak.com/en/news.txt` is requested?

**Comment by Alex-302** [comment]
Hi
I don't get your idea) Could you, please, explain it?

**Comment by Bluscream** [comment]
Isn't the $replace modifier made for this?

**Comment by Bluscream** [comment]
Closing as dublicate of https://github.com/AdguardTeam/AdguardForWindows/issues/1505
