### ISSUE TITLE
digital-eliteboard.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3526]
**Site**: http://www.digital-eliteboard.com/threads/windows-10-angeblich-sicherer-als-linux.425724/
**Description**: Ad post in forums.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20577156/56de5b82-b1c1-11e6-99cd-b2a0ec952f0f.png)

</details>

________________

**Adguard version**: 6.1.290.1526

**Filters list**: 
English filter 1.1.1.29
Spyware filter 1.0.9.15
Social media filter 1.0.14.78
Annoyances filter 1.0.6.91
German filter 1.0.28.76
Mobile ads filter 1.0.5.94
Safari filter 1.0.1.73

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to German filter
```
||digital-eliteboard.com/images/scout.gif
digital-eliteboard.com##.messageList > li[class="message"]:not([id]):not([data-author])
```
