### ISSUE TITLE
Redırectıng

### ISSUE THREAD

**Issue by terlan2** [AdguardTeam/AdguardFilters#35271]
Hello this site redırects me to other NSFW sıtes

https://eastmostlitharges.online/tr_dating/?tag=1093-o52Y1XOihY&step2=1&subid=ba_OIzye-Ujb00di-iuVKTWo89UzE3E9wfpJI8

**Comment by bogachenko** [comment]
and what's the problem? This site has such a code.

![Безымянный](https://user-images.githubusercontent.com/8535285/59547035-de9f9980-8f83-11e9-8824-8fd5d3627b37.png)

**Comment by terlan2** [comment]
This site should be detect as "harmful site"

**Comment by terlan2** [comment]
This domain should be blocked automatically because it is useless site. Just redirects to other sites.

**Comment by bogachenko** [comment]
@terlan2 should have said so from the start

***

@Chinaski1 проснись и пой, солнышко, для тебя есть работа.

**Comment by Chinaski1** [comment]
Blacklisted!

**Comment by terlan2** [comment]
New domain: webtedizi.org

@Chinaski1

**Comment by terlan2** [comment]
Again redirecting domain.  filmiizlefullizle.com

@Chinaski1

**Comment by Chinaski1** [comment]
Killed!

**Comment by terlan2** [comment]
Again redirecting domain: gunlukfilm.net

**Comment by Alex-302** [comment]
Where does it happen?

**Comment by Chinaski1** [comment]
gunlukfilm.net - killed!

**Comment by terlan2** [comment]
@Chinaski1 

New redirecting site: http://www.windowsdeal.com/category/giveaways

**Comment by Chinaski1** [comment]
Blacklisted!

**Comment by terlan2** [comment]
New website: 131sex.com @Chinaski1

**Comment by Chinaski1** [comment]
Killed!
