### ISSUE TITLE
Fake site

### ISSUE THREAD

**Issue by terlan2** [AdguardTeam/AdguardFilters#35281]
Fake site:
1) http://www.internetuzerindenis.com/para-kazandiran-brave-browser/
2) http://www.yapmayav.com/en-kolay-kravat-nasil-baglanir.html

@Chinaski1

**Comment by Chinaski1** [comment]
Blacklisted!

**Comment by terlan2** [comment]
3. kredivebankalar.org/banka-sinavlarina-hazirlanma-rehberi.html/

@Chinaski1

**Comment by Chinaski1** [comment]
And another one!
