### ISSUE TITLE
http://m.espn.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3529]
http://m.espn.com/nba/playercard?playerId=3468&src=desktop

![file_000](https://cloud.githubusercontent.com/assets/15856304/20589253/0431cef6-b224-11e6-9f8e-500173e557f5.png)

<details>
Application version: 1.1.1.54
Application lifetime: 2016-10-06 02:22:17 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: 5F313F21-B980-42A5-A431-03A12B9ECFCC

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.99.2 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.64 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.7 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.80 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.47 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.57 Enabled=YES
ID=101 Name="EasyList" Version=1.0.63.55 Enabled=NO
ID=118 Name="EasyPrivacy" Version=1.0.66.93 Enabled=NO

</details>

**Comment by Alex-302** [comment]
@evgeniy-ADG 
@vgavrish 
please check this rule
```
@@||espncdn.com/*/*.css
```
added to Safari filter
