### ISSUE TITLE
techsighter.com [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#35294]
**Site**: https://www.techsighter.com/

**Issue**: Please remove adblock message.

**Screenshot**: http://prntscr.com/o262yj

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 75.0.3770.80 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 3.1.3 `

**Filters**:
```
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404
NoCoin Filter List

```

**Stealth Mode Settings**:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled

**Comment by ptrkr** [comment]
Resolved in https://github.com/List-KR/List-KR/commit/da80ec833eb9a5987717bd377a9ac853f4465de0

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back

**Comment by AdamWr** [comment]
>Anti Adblock is back

Fixed, update should be available in 1-2 hours.
