### ISSUE TITLE
uiporn.com [NSFW] [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#35291]
**Site**: https://www.uiporn.com/videos/my-collection-13-6704/

**Issue**: Please remove the pop-ups on the page.

**Screenshot**: http://prntscr.com/o25rq7

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 75.0.3770.80 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 3.1.3 `

**Filters**:
```
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404
NoCoin Filter List

```

**Stealth Mode Settings**:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled

**Comment by Alex-302** [comment]
fixed

**Comment by Nzzyme** [comment]
Ad text string seen which reads "This ad helps us keep your porn free" on almost all pages. Please fix

**Comment by Alex-302** [comment]
ok
