### ISSUE TITLE
No assistant on overclockers.ru

### ISSUE THREAD

**Issue by odudnyk** [AdguardTeam/AdguardFilters#3530]
**Ad is not blocking at overclockers.ru, and assistant doesn't show up**:

<details> 

http://prntscr.com/db44d8

</details>

<details>

Os version: Microsoft Windows NT 6.1.7601 Service Pack 1
Dot .net version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: 393a2e0e86b74911ae29f80f8b6b6bc1
Language: ru
AppVersion: 6.0.226.1108
Main settings: 
Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:9 Name: Spanish/Portuguese filter Url: http://adguard.com/ru/filter-rules.html?id=9
FilterId:104 Name: EasyList China Url: https://easylist-downloads.adblockplus.org/easylistchina.txt
FilterId:105 Name: EasyList Czech and Slovak Url: https://raw.github.com/tomasko126/easylistczechandslovak/master/filters.txt
FilterId:110 Name: EasyList Lithuania Url: http://margevicius.lt/easylistlithuania.txt
FilterId:116 Name: Wiltteri Url: https://raw.githubusercontent.com/wiltteri/wiltteri.txt/master/wiltteri.txt
FilterId:216 Name: Adblock polskie reguły Url: https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Tdi
Ads Blocked: 52305, Trackers Blocked: 0
Filtering Mode: Driver
Application lifetime: 245.03:14:45.4902021
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false
}

</details>

Problem present both on Windows and Mac

**Comment by Alex-302** [comment]
Not reproduced.
As I see ads are not blocked. Maybe https filtering is not works on this site.
Go to this folder and make screenshot ar copy file names
C:\ProgramData\Adguard\NetworkTemp\SSL

**Comment by evgeniy-ADG** [comment]
We reproduced it on Mac.

**Comment by Alex-302** [comment]
It is not caused by filters. Use beta version.

**Comment by vgavrish** [comment]
@Alex-302 
Пользователь отписался что до 6.1.258.1302 не отображается Помощник и не блочится реклама

> Правило из русского фильтра (1.0.43.46 от 26.11.16) -> "||overclockers.ru^$replace=/var ads = /var аds = /" приводит к отключению фильтрации и помощника на соответствующем сайте. Браузеры: Opera (41.0.2353.69) и Microsoft Edge (38.14393.0.0).

**Comment by Alex-302** [comment]
Да, убрал пока.
