### ISSUE TITLE
http://wccftech.com/ - disqus comments are blocked

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3531]
http://wccftech.com/radeon-rx-490-vr-4k-december/

![file_000 1](https://cloud.githubusercontent.com/assets/15856304/20590153/1df2fb84-b22a-11e6-90f6-fd4a95249505.png)

<details>
Application version: 1.1.1.54
Application lifetime: 2016-11-24 2:40:09 am +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.3
ID: 007A8FD8-9596-4FF2-86F2-39A0618423D3

Locale: en
Region: gb

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.31 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.16 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.79 Enabled=NO
ID=12 Name="Safari filter" Version=1.0.1.73 Enabled=NO
ID=101 Name="EasyList" Version=1.0.64.91 Enabled=NO
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.64.93 Enabled=NO
ID=122 Name="Fanboy's Annoyances" Version=1.0.65.11 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.69.70 Enabled=YES

**Comment by Alex-302** [comment]
added to Safari filter
```
@@||disquscdn.com^$script,domain=wccftech.com
@@||disqus.com^$script,domain=wccftech.com
```
