### ISSUE TITLE
http://sdfgdf.xyz

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#35329]
***Description***:
Hi
in the like to games in site: http://sdfgdf.xyz
have link with ads
exmple:
http://sdfgdf.xyz/live/2200/venezuela-vs-peru/

* **Current behaviour**: 
https://image.prntscr.com/image/2xC80gXGTAKhqxlrkCG_sg.png

* **Expected behaviour**: 
https://image.prntscr.com/image/8n_fQyFhRw_N0CqYPWay_Q.png
(see video but have ads)

Information | Value
-- | --
Operating system: | win 10
Browser: | Google Chrome
AdGuard version: |6.4.1814.4903

Filters enabled:  
EasyList Hebrew,
EasyPrivacy,
AdGuard Annoyances,
AdGuard Base,
Adblock Warning Removal List

AdGuard DNS:  None
Stealth mode options (Windows only): not enabled

**Comment by Alex-302** [comment]
Not reproduced. Which filter causes it?

**Comment by LucasDiTomase** [comment]
I tried loading the website but it says 'nothing found'
