### ISSUE TITLE
hdkinoteatr.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3532]
**Description**: Полная версия сайта. Реклама слева в колонке
hdkinoteatr.com

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20590962/c97a1722-b22e-11e6-971c-4b1405c2ad25.png)

</details>

**Adguard version**: 2.8.58

**Filters list**: 1,2,3,4,11,14

**Operating system**: Анроид

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||et-code.ru/bens/vinos.js$empty,important
```
Нужно чтоб юзер сообщил о результате. Или у себя проверьте.

**Comment by vgavrish** [comment]
у меня все норм
навсяк еще юзеру отписалась
