### ISSUE TITLE
blastarena.io проблема

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#35341]
Из за базового фильтра AdGuard не корректно работает кнопка Play Again после окончания матча.. Новый матч не начинается.
http://blastarena.io/#

**Comment by Alex-302** [comment]
@Smorvel такое помогает?
```
@@||blastarena.io^$jsinject
```

**Comment by Smorvel** [comment]
нет

**Comment by Alex-302** [comment]
а `@@||blastarena.io^$urlblock`?

**Comment by Smorvel** [comment]
@Alex-302 в каком-то роде да.. но внизу появилась полосочка от рекламы, и при нажатии на Play again идет реклама хоть ее и не видно, и нужно ждать чтобы появилась кнопка пропустить рекламу. Только я тестировал оба эти правила одновременно, может по этому.

**Comment by Alex-302** [comment]
Ок, нужен список заблокированных запросов с включенным одним базовым фильтром.

**Comment by Smorvel** [comment]
@Alex-302 пришлось по одному копировать.. не нашел как экспортировать только заблокированные...
http://server.cpmstar.com/view.aspx?poolid=80558&json=c_mp&mv=1&multi=2&w=960&h=540&callback=doue5d
http://server.cpmstar.com/view.aspx?poolid=80560&json=c_mp&callback=bnry9a
http://server.cpmstar.com/view.aspx?poolid=80560&json=c_mp&mv=1&callback=gi67rx
http://server.cpmstar.com/view.aspx?poolid=79938&subpoolid=0&script=1&rnd=878818
http://server.cpmstar.com/view.aspx?poolid=79932&script=1&rnd=214774
http://server.cpmstar.com/view.aspx?poolid=79932&script=1&rnd=561523

**Comment by Alex-302** [comment]
Такое помогает?
`@@||server.cpmstar.com/view.aspx?poolid=$domain=blastarena.io`

**Comment by Smorvel** [comment]
@Alex-302 ну как бы результат полностью такой же как и с тем правилом...

**Comment by Alex-302** [comment]
с каким?

**Comment by Smorvel** [comment]
@Alex-302 вторым @@||blastarena.io^$urlblock

**Comment by Smorvel** [comment]
@Alex-302 почему у себя не проверяешь?) Так легче будет по моему)

**Comment by Alex-302** [comment]
такое глянь
`blastarena.io#%#AG_abortInlineScript(/cpmstarAPI/, 'document.createElement');`
ну игры время отнимают, сейчас уже сам проверил

**Comment by Alex-302** [comment]
на досовскую Dyna Blaster похоже)

**Comment by Smorvel** [comment]
@Alex-302 Игра хороша (когда не лагает) иногда там проблемы с пингом..
На счет нового правила, с ним после нажатия на плэй аген просто поле показывается... Точнее результат такой же как и без любого из этих правил.

**Comment by Smorvel** [comment]
@Alex-302 хотя только что проверил опять и на этот раз вроде все ок.. нужно еще попроверять

**Comment by Smorvel** [comment]
@Alex-302 в общем да, вроде все в порядке.

**Comment by Smorvel** [comment]
@Alex-302 на счет dyna чет не слыхал про такое название) Я знаю ее как "Bomberman")

**Comment by Alex-302** [comment]
Просто другое название, игра та же
