### ISSUE TITLE
http://www.mirror.co.uk/ - anti-adblock script

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3534]
http://www.mirror.co.uk/3am/celebrity-news/how-kate-bushs-son-bertie-4119962

![image](https://cloud.githubusercontent.com/assets/15856304/20605390/dae1f2ba-b273-11e6-98e1-02cf992ae79e.png)

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/20605408/eec2200c-b273-11e6-9ae1-d807a52a6772.png)

etc

**Comment by Alex-302** [comment]
fixed in annoyances
