### ISSUE TITLE
http://tes-game.ru/ - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#3535]
**http://tes-game.ru/**:

![2016-11-24 19 38 39](https://cloud.githubusercontent.com/assets/23637588/20605983/2aaf2d7a-b27f-11e6-92ad-2f892a8c3312.png)

**Filters list**: User filter, English, SM, Annoyance, Spyware, Russian

**Comment by Alex-302** [comment]
fixed
