### ISSUE TITLE
https://www.nur.kz/ - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#3536]
**https://www.nur.kz/**

![2016-11-24 20 14 45](https://cloud.githubusercontent.com/assets/23637588/20606595/011103cc-b283-11e6-86f3-767dd1a179a8.png)

<details>
User filter, English, SM, Annoyance, Spyware, Russian
</details>

**Comment by Alex-302** [comment]
Там ссылка на их собственный проект.

**Comment by zebrum** [comment]
@Alex-302 
под ссылкой рекламная картинка

**Comment by Alex-302** [comment]
То вообще объявления с их портала, но ладно, скрою.
