### ISSUE TITLE
http://zfilm-hd.net/ - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#3537]
http://zfilm-hd.net/

![2016-11-24 20 30 16](https://cloud.githubusercontent.com/assets/23637588/20607163/203a8850-b287-11e6-877a-681f24798158.png)

<details>
Eng, SM, Annoyance, Spyware, Rus
</details>

**Comment by Alex-302** [comment]
Добавил в фильтр раздражителей
```
zfilm-hd.net##.main2 > div[id]:empty:not([class])
```

**Comment by zebrum** [comment]
http://zfilm-hd.club/25374-13-prichin-pochemu.html
ru en social media spyware annoyances
adg 1.4.1

![screenshot 2017-05-16 13 26 42](https://cloud.githubusercontent.com/assets/23637588/26101863/553303f2-3a3b-11e7-8b14-3e94ca65daf6.png)

**Comment by Alex-302** [comment]
Fixed
