### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#35400]
`https://www.google.com/search?client=firefox-b-d&hl=en&q=trip`

![google ads](https://user-images.githubusercontent.com/35470489/59628327-ca3fd600-9116-11e9-9498-ead2302c7e7d.png)

Adguard Base + Annoyances + Mobile + Portuguese + Russian + Social + Spyware
uBlock Origin 1.20.0
`Mozilla/5.0 (Android 4.4.2; Mobile; rv:66.0) Gecko/66.0 Firefox/66.0`

**Comment by Alex-302** [comment]
Not reproduced with AdGuard. Please upload saved page.

**Comment by adranger** [comment]
@Alex-302 I can't reproduce it with `google.com` anymore, but I still see the same ads on `google.com.br`:

`https://www.google.com.br/search?client=firefox-b-d&hl=en&q=trip`

`Mozilla/5.0 (Android 4.4.2; Mobile; rv:67.0) Gecko/67.0 Firefox/67.0`

[trip - Google Search.zip](https://github.com/AdguardTeam/AdguardFilters/files/3315313/trip.-.Google.Search.zip)

**Comment by Alex-302** [comment]
Ok. Next time please save page with and without AdGuard. I want to check it they are using anti-adblock script.

**Comment by adranger** [comment]
I use your lists with uBlock Origin, but here's the page with the extension disabled: [2.zip](https://github.com/AdguardTeam/AdguardFilters/files/3342718/2.zip)

@mapx- please check if you can reproduce this with the given user agent.

**Comment by mapx-** [comment]
it should already work this uBo filter
```
!#if env_mobile
google.*##a[href*="aclk"]:xpath(//span[(text()='Ad')]/../../../..)
!#endif
```

**Comment by krystian3w** [comment]
If break emulation so no hide on PC with Emulate android.

**Comment by adranger** [comment]
@krystian3w I used the desktop version to take the screenshot but I'm getting ads on an actual phone too.

@mapx- That's also supposed to work with Fennec (the version of Firefox on F-Droid), right? I don't know what's wrong. I don't get any CSS rule in the logger. Other sites work as expected. Anyway, since this only seems to affect me, I'm closing this.
