### ISSUE TITLE
http://www.multidown.me/ Player anti adblock 

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#3540]
Hey.
in site http://www.multidown.me/ on the player have anti adblock:
http://prntscr.com/d1s2gb
exmple:
http://www.multidown.me/%D7%AA%D7%90%D7%92%D7%93-%D7%A2%D7%95%D7%A0%D7%94-1-%D7%A4%D7%A8%D7%A7-25-taagad-s01e25/

**Comment by Alex-302** [comment]
Added to English filter
```
@@||rapidvideo.com/embed/$generichide
```
