### ISSUE TITLE
classic.newsru.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3542]
**Description**: Директ
http://classic.newsru.com/

сохраненная страница если поможет
https://yadi.sk/d/GHAP-HVyzRfut

в Приватной вкладке тоже реклама

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20616648/4c303238-b2ec-11e6-8ec7-37058936c711.png)

</details> 

**Adguard version**: 6.1.287.1519

**Filters list**: 1,2,3,4,14
Пользовательский отключен

**Browser**: Хром. кэш чистился

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не повторяется. Пусть бету попробует. И юзерфильтр тоже можно попробовать выключить

**Comment by Alex-302** [comment]
Убрал пару пустых блоков.
