### ISSUE TITLE
internet-advert.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3543]
**Description**:

> Здравствуйте, мы заметили, что наш сайт www.internet-advert.ru некорректно отображается в браузерах на компьютерах, где установлен adguard. Изучив вопрос, мы пришли к выводу, что adguard вырезает все файлы стилей, js, картинки, потому что в пути к файлом есть указание на домен internet-advert.ru, который включает слово advert.
На нашем сайте нет рекламы, пользователи заходят на него для получения интересующей их информации. Таким образом, фильтрация adguard файлов стилей, js и картинок ошибочная. 
Есть ли возможность добавить данный сайт в исключения для всех пользователей. 

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20619024/d69c9cf0-b2fa-11e6-94ad-fa86b5eabb68.png)

</details>

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
