### ISSUE TITLE
http://spec-komp.com/ - Anti-Adblock

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3544]
**Description**:
http://spec-komp.com/load/

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20620201/345583ce-b301-11e6-95f7-0ff749482ad0.png)

</details>

**Adguard version**: 6.1.290

**Filters list**: 1,2,3,4,14,211

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by odudnyk** [comment]
Повторилось на Mac

**Comment by Alex-302** [comment]
fixed
