### ISSUE TITLE
https://kurs.com.ua/

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#35445]
Ads reinsertation script(zmctrack.net). Or redirect to ad.
If ads not loaded, please try to block `zmctrack.net`

Screenshot:

<details>

![image](https://user-images.githubusercontent.com/8361299/59701774-f9317700-91fe-11e9-853c-939145a4ca0d.png)

</details>

and similar ads.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardExtra #2](https://github.com/AdguardTeam/AdGuardExtra/issues/2) via [**ZenHub**](https://www.zenhub.com/)
