### ISSUE TITLE
http://tumejortorrent.com/ - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#3545]
http://tumejortorrent.com/

**Current behaviour**: new window pop-ups appear while surfing site
![2016-11-25 12 11 54](https://cloud.githubusercontent.com/assets/23637588/20620185/7f089912-b309-11e6-9a14-23546bf7af9f.png)

  

**Adguard version**: chrome extension 

**Filters list**:en, sm, spyware, rus

**Comment by Alex-302** [comment]
added to Spanish filter
```
tumejortorrent.com###box-ads-tr
tumejortorrent.com##div.pub728x90
tumejortorrent.com#%#Object.defineProperty(window, '_pop', { get: function() { return {}; } });
```
