### ISSUE TITLE
chip.de - Social button leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3546]
**Site**: http://www.chip.de/downloads/CCleaner_16317939.html
**Description**: Social media button leftover. Similar to #3488, but that's a different button.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20630763/355c6508-b333-11e6-95f9-cc9eef10a41a.png)

</details>

________________

**Adguard version**: 6.1.290.1526

**Filters list**: 
English filter 1.1.1.40
Spyware filter 1.0.9.16
Social media filter 1.0.14.85
Annoyances filter 1.0.7.1
German filter 1.0.28.79
Mobile ads filter 1.0.5.96
Safari filter 1.0.1.76

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Social filter
```
chip.de##.LikeButton
```
