### ISSUE TITLE
dfb.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3547]
**Site**: http://www.dfb.de/start/
**Description**: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20630857/f150eacc-b333-11e6-9af9-6aba15ef453f.png)

</details>

________________

**Adguard version**: 6.1.290.1526

**Filters list**: 
English filter 1.1.1.40
Spyware filter 1.0.9.16
Social media filter 1.0.14.85
Annoyances filter 1.0.7.1
German filter 1.0.28.79
Mobile ads filter 1.0.5.96
Safari filter 1.0.1.76

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
dfb.de##.ad
