### ISSUE TITLE
AG renews site

### ISSUE THREAD

**Issue by terlan2** [AdguardTeam/AdguardFilters#35486]
With AG this site renews again and again. : https://filehippo.com/download_google_chrome/91388/

**Comment by Alex-302** [comment]
@terlan2 not reproduced.
Please don't ignore template.

**Comment by terlan2** [comment]
Please look at: https://drive.google.com/file/d/1pkxAGdrvE42hrwAqF-6JVTT3UgmUAFZQ/view?usp=sharing

**Comment by Alex-302** [comment]
Please send report using AdGuard assistant. It will filled automatically(except few simple steps). We don't know even about used filters.

**Comment by terlan2** [comment]
Before I create this issue here, I tried to send with assistant. But I cant use assistant, because site renews itself less than 3  seconds.  

Here: https://drive.google.com/file/d/1FOa68xjoMMsLzbBt6MpwdJRtYJuSRFS4/view?usp=sharing

**Comment by terlan2** [comment]
But my System configuration is this: (I took a screen from other issues that I reported with AG)

![screenshot_430](https://user-images.githubusercontent.com/51233370/59760112-0f801700-9281-11e9-9e82-930576bcd389.png)

**Comment by BlazDT** [comment]
Issue is stealth mode third-party cookies setting 0, therefore it is refreshing everytime. That setting can cause lot of problems like in this case, therefore I do not recommend it.

This rule fixes it though, but not sure if we should add such wide rule to filters (tried manual ones too):
`@@||filehippo.com^$script,stealth,third-party`

**Comment by terlan2** [comment]
> That setting can cause lot of problems like in this case

I use this setting long time, but this problem was apperanced at this site once.



> @@||filehippo.com^$script,stealth,third-party

It didnt work( Video: https://drive.google.com/file/d/14pAUq4gKrJ19zlwLaMk_bKpH2Vb3ICR9/view?usp=sharing

**Comment by BlazDT** [comment]
Try this one:

`@@||filehippo.com^$script,stealth`

**Comment by terlan2** [comment]
> `@@||filehippo.com^$script,stealth`

Great.. It worked..

**Comment by Alex-302** [comment]
Better change self-destruction cookie option.

**Comment by terlan2** [comment]
Suggestion:

Then, please note a warning text below "Set to "0" to block cookies completely like in "Block third-party Autharization header".

**Comment by terlan2** [comment]
> Then, please note a warning text below "Set to "0" to block cookies completely" like in "Block third-party Autharization header".

@ameshkov what do you think about this? Can we add a warn text to give information about this issue to users, if they choose "0" ?
