### ISSUE TITLE
cocopanda.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3548]
**Site**: https://www.cocopanda.de/
**Description**: Cookie notice.

**Current behaviour**: Site displays a cookie notice at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20630908/34354bda-b334-11e6-9f91-3b05b16684d8.png)

</details>

________________

**Adguard version**: 6.1.290.1526

**Filters list**: 
English filter 1.1.1.40
Spyware filter 1.0.9.16
Social media filter 1.0.14.85
Annoyances filter 1.0.7.1
German filter 1.0.28.79
Mobile ads filter 1.0.5.96
Safari filter 1.0.1.76

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Please don't collect the sites for a long time. Post them immediately when you found an issue:)

**Comment by danidoedel** [comment]
@Alex-302 I don't. I discovered that today.

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
###cookieInfoBanner
```
