### ISSUE TITLE
www.hdfilmcehennemi.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#3549]
**Site**: http://www.hdfilmcehennemi.com/

**Screen**: http://s12.postimg.org/nnzm6cu9p/screenshot_2.png

**Adguard version**: 2.5.1

**Operating system**: Windows 10

**Browser**: Google Chrome

**Filter list**: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by seanl-adg** [comment]
This was fixed in a similar thread in the forum.
