### ISSUE TITLE
http://anistar.ru/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#355]
Антиадблок при попытке просмотра видео.

**Comment by Alex-302** [comment]
Проверь вот такое:
@@/advert.$domain=anistar.ru
и проверь, запускается ли видео, а то в какой-то момент глянул, что плеер видно, но он не работает. В этом случае проверь ещё с таким:
@@|http://ad.

**Comment by vbagirov** [comment]
Все равботает у меня, и даже без второго правила.

**Comment by Alex-302** [comment]
Добавил в ЭФ.

**Comment by evgeniy-ADG** [comment]
![screen shot 2016-09-30 at 4 59 57 pm](https://cloud.githubusercontent.com/assets/15856304/18994189/55e55b66-872f-11e6-97af-3799d20586eb.png)

**Comment by Alex-302** [comment]
Done.
