### ISSUE TITLE
https://ok.ru/

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#35505]
Ads reinjection.

Screenshots:
<details>

![image](https://user-images.githubusercontent.com/8361299/59772815-2f313280-92b5-11e9-84f6-22e8bc57ea7e.png)

</details>

<details>

![image](https://user-images.githubusercontent.com/8361299/59772890-4a03a700-92b5-11e9-959f-c66556ce12f6.png)

</details>

Promoted post is also obfuscated.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardExtra #1](https://github.com/AdguardTeam/AdGuardExtra/issues/1) via [**ZenHub**](https://www.zenhub.com/)
