### ISSUE TITLE
www.sinemafilm.org

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#3552]
**Site**: http://www.sinemafilm.org/

**Screen**: http://s12.postimg.org/vefl2zbct/screenshot_4.png

2) Click any link. You will get a popup. 

**Site**: http://www.sinemafilm.org/iftarlik-gazoz-2016/108491/
**Screen**: http://s12.postimg.org/93izuwg8t/screenshot_5.png

**Adguard version**: 2.5.1

**Operating system**: Windows 10

**Browser**: Google Chrome

**Filter list**: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by thislife81** [comment]
Pleae remove these: http://s12.postimg.org/6ebz7wzel/screenshot_6.png

**Comment by Alex-302** [comment]
Added to Turkish filter
```
sinemafilm.org#$##filmoncereklam { display: none!important; }
sinemafilm.org#$##film { display: block!important; }

```
