### ISSUE TITLE
www.filmi-izle.org

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#3555]
**Site**: http://www.filmi-izle.org/landmine-goes-click.html

**Screen**: http://s12.postimg.org/picx7gy7x/screenshot_7.png

**Adguard version**: 2.5.1

**Operating system**: Windows 10

**Browser**: Google Chrome

**Filter list**: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
filmi-izle.org#$##film { display: block!important; }
filmi-izle.org#$##filmoncereklam { display: none!important; }

```

**Comment by thislife81** [comment]
Please remove this: http://s12.postimg.org/wgskhb0al/screenshot_1.png
