### ISSUE TITLE
www.birdenizle.net

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#3556]
**Site**: http://www.birdenizle.net/aloys.html

**Screen**: http://postimg.org/image/ihtisfltl/

**Adguard version**: 2.5.1

**Operating system**: Windows 10

**Browser**: Google Chrome

**Filter list**: English, Spyware, Social, Annoyances, Russian, Turkish

**Comment by Alex-302** [comment]
Added to Turkish filter
```
birdenizle.net#$##rk-content { display: none!important; }
birdenizle.net#$##cn-content { display: block!important; }

```
