### ISSUE TITLE
deezer app for windows - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3557]
![2016-11-26](https://cloud.githubusercontent.com/assets/15856304/20639986/4074de3a-b3dc-11e6-811e-1af0c2dc434d.png)

The app's installed to 
C:\Program Files\WindowsApps\Deezer.62021768415AF_3.2.15.0_x86__q7m17pa7q8kj0  and added manually to the list
I'm using Russian, English, annoyances, spyware and some other filters, all up to date.

**Comment by Alex-302** [comment]
I need more details how to reproduce it.

**Comment by evgeniy-ADG** [comment]
1. Go to Windows store on Windows 10, the latest build, type Deezer in the search bar, locate and download the app
2. Sign in and start listening
3. The ad appears every 4-5 songs t

**Comment by Alex-302** [comment]
@evgeniy-ADG this app works incorrectly even without AG - all tracks are skipped within 1 second of starting on my end.

**Comment by evgeniy-ADG** [comment]
I don't have this problem.

**Comment by Alex-302** [comment]
Could you provide remote access?

**Comment by evgeniy-ADG** [comment]
@Alex-302 yep, give me a shout in skype ~ 17:00 Kyiv time. Will be happy to get rid of this ad, it's really annoying.

**Comment by Alex-302** [comment]
Today it is too late. What about tomorrow?
Also you can install Fiddler.
