### ISSUE TITLE
Download of official pornhub app blocked

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardFilters#3558]
![screenshot_20161127-010722](https://cloud.githubusercontent.com/assets/3318223/20644702/b12f2b28-b43e-11e6-82dc-c43ac947f8bc.png)
http://www.pornhub.com/fun/android

**Comment by Alex-302** [comment]
Use provided template, when you open issues.

**Comment by Bluscream** [comment]
My Setup:
<details>
Samsung Galaxy Tab 9.3 (SM-T555)
Android 6.0.1 Build: MMB29M (Stock Touchwiz ROM)
Rooted with superSU
AdGuard BETA 6.1.287.1519  
Google Chrome 56.0.2919.3 (Official Build) dev (32-Bit)
</details>

**Comment by Bluscream** [comment]
@Alex-302 

My Setup:
<details>
Samsung Galaxy Tab 9.3 (SM-T555)

Android 6.0.1 Build: MMB29M (Stock Touchwiz ROM)

Rooted with superSU

AdGuard BETA 2.8.58

Google Chrome 56.0.2919.3 (Official Build) dev (32-Bit)
</details>

**Comment by Alex-302** [comment]
Filters? HTTPS filtering?

**Comment by Bluscream** [comment]
![https://puu.sh/swCJO/8d336661e5.mp4](https://puu.sh/swCJO/8d336661e5.mp4)

**Comment by Alex-302** [comment]
Not working. Make screenshots.
