### ISSUE TITLE
Streaming website as false positive

### ISSUE THREAD

**Issue by skri56** [AdguardTeam/AdguardFilters#35590]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
On the website : https://watchhowimetyourmother.online/episodes/how-i-met-your-mother-5x7/ ( any episode) The player number 1 is curently broken. It is considered as a false positive i suppose. After a few seconds of being normal AdGuard considers it as an ad ( since it has built in ads i suppose ) and it just force crashes it. 

In addition player 2 sometimes doesnt work either. The "Play" Button is also considred an add and the lines of codes that are supposed to happen after you click it do no happen. That is because it normally opens an add on a new tab then opens the player.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

<br/>

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<br/>

***Steps to reproduce the problem***:
-->Go to the website : https://watchhowimetyourmother.online/episodes/how-i-met-your-mother-5x7/#option-1
       For bug number 1 : 
-->Click on "Server 1" if it is not automatically selected.
-->Click on the play button, then wait about 30 seconds max.
-->Watch the player randomly crash.

      For bug number 2:
--->Click on "Server 2".
--->Try to click on the play button in the middle of the player.
--->Notice the page trying to process lines of codes but gets blocked by AdGuard.
(There is however a temporary fix : AdGuard does not concider the rest of the space in the player ( other than the play button) as an ad so if you click a few times under the play button it should result in your video openning but it is annoying and not how it is supposed to work.) 

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***
Nothing out of the ordinary: normal "gaming laptop" with a custom dns ( 1.1.1.1 but it used to work correctly before AdGuard)
**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | ----
Browser:                               | Chrome
AdGuard version:                       | 7.0.2693.6661
Filters enabled:                       | yes
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
How do you define "crash" exactly? Tried and fast forwarded a bit with both servers and no error.

**Comment by skri56** [comment]
A message used to apear stopping the video and forcing you to reload the page otherway you cant watch. Used to say "Could not reach the server" or "Connection to server was interupted" aprox

**Comment by skri56** [comment]
And for me it used to happen with server 1 i would start at 0 and it would just crash after 15 - 30 seconds

**Comment by BlazDT** [comment]
Please check @Alex-302. I cannot reproduce :(

**Comment by skri56** [comment]
I will try to take a screenshot of the bug asap. Sorry for the extra steps!

**Comment by Alex-302** [comment]
Please send report using AdGuard Assistant, we need more info.

**Comment by skri56** [comment]
Alright i will send it!

**Comment by skri56** [comment]
and also here is the screen : 
![image](https://user-images.githubusercontent.com/29429662/60025833-5c555a80-9692-11e9-8809-eed0a97d462b.png)

**Comment by skri56** [comment]
and also here is the screen : 
![image](https://user-images.githubusercontent.com/29429662/60025888-7a22bf80-9692-11e9-855a-441e06f2924d.png)

**Comment by Alex-302** [comment]
> Alright i will send it!

Please post link here.

Which filter causes it?

**Comment by skri56** [comment]
I did some deeper testing and it seems like it was caused by the Adguard French Filter (since the Player is in french and runs ads its considered false positive)

**Comment by Alex-302** [comment]
Hmm. It works with French filter on my end. Could you please make screenshot of blocked by FR filter requests?
![image](https://user-images.githubusercontent.com/8361299/60093790-faa8f500-9752-11e9-9475-8d828fa87aa3.png)

**Comment by skri56** [comment]
seems like it was my bad
![image](https://user-images.githubusercontent.com/29429662/60117645-5767d800-9772-11e9-8e73-9efc95bb02be.png)

**Comment by skri56** [comment]
here is a link to the Log File : https://www.dropbox.com/s/q3nob3e8b4uqz9z/20190625_adguard_filtering_log_records.json?dl=0

**Comment by Alex-302** [comment]
> it seems like it was caused by the Adguard French Filter

please try to check with Adguard French Filter only. I see no blocked requests by this filter.

**Comment by skri56** [comment]
yes it was blocked again using only the French filter ( i also noticed it was blocking a twitch notification extention on chrome but that s another problem) here is the logs : https://www.dropbox.com/s/sfjzixo027het8b/20190626_adguard_filtering_log_records.json?dl=0

**Comment by Alex-302** [comment]
I see no blocked request. I can check it using teamviewer, if it is possible.

**Comment by skri56** [comment]
sure how do you want to procede ?
Just to make sure i will send again new logs  : https://www.dropbox.com/s/sfjzixo027het8b/20190626_adguard_filtering_log_records.json?dl=0
i have no other Ad blocking program or Chrome Extension and it works when AdGuard is disabled im just lost now

**Comment by Alex-302** [comment]
Again - no blocked or midified requests
<details>

![image](https://user-images.githubusercontent.com/8361299/60258313-949ca900-98dd-11e9-9fec-26d76576aefc.png)

</details>

It seems the log is not full. 
Do you use VPN or proxy?

**Comment by skri56** [comment]
No i dont think so... however i seem to be the only one having this problem. Other adguard users i know do  ot have any errors so i belive it is on me. If you still want to continue i ll gladly help but i honestly think its not a major issue so it might be fixed some day by accident.

**Comment by Alex-302** [comment]
Could you please provide remote access?

**Comment by skri56** [comment]
yeah sure we just need to be online at the same moment for that

**Comment by Alex-302** [comment]
I am online 10:00-23:00(UTC +2)

**Comment by skri56** [comment]
I am awfully sorry but i will be away from today untill the 18th ( at least ) so i do not have access to my laptop and will be lacking time however i will make sure to send you everything you need when i come back sorry again and thanks for your hard work

**Comment by Alex-302** [comment]
Ok, will wait:)

**Comment by Alex-302** [comment]
@skri56 any news?:)
