### ISSUE TITLE
http://fmovies.to/film/ben-hur.1n26w/6w1lx9 - incorrect blocking 

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3559]
Incorrect blocking on page: http://fmovies.to/film/ben-hur.1n26w/6w1lx9

Can't play the movies. But when AdGuard is disabled everything works fine.

Application version: 1.1.1.54
Application lifetime: 2016-11-19 05:30:04 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: 2AF3E3CC-D174-4714-A864-B45E58FF77B3

Locale: en
Region: se

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.62 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.19 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.93 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.77 Enabled=YES
ID=102 Name="ABPindo" Version=1.0.1.28 Enabled=YES
ID=223 Name="Fanboy's Swedish" Version=1.0.0.4 Enabled=YES

**Comment by Alex-302** [comment]
[COLOR="#0000FF"]Added to Safari filter:[/COLOR]
[CODE]
@@|http://*$domain=fmovies.to,~third-party
[/CODE]
Please, check the result.
