### ISSUE TITLE
https://text.ru/ - Assistant doesn't not show up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3560]
https://text.ru/

![image](https://cloud.githubusercontent.com/assets/15856304/20646477/e5f1fd20-b481-11e6-99a7-b6ab48e998c8.png)

В исключениях сайт не нанешл.

**Comment by Alex-302** [comment]
It is not caused by filters(can not be fixed). Please move to Windows section.
