### ISSUE TITLE
http://bleacherreport.com/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3561]
http://bleacherreport.com/articles/2675902-barcelona-transfer-news-lionel-messi-reportedly-delays-contract-negotiations

Video starts playing automatically and quite loud:

![image](https://cloud.githubusercontent.com/assets/15856304/20646839/9bce6994-b48c-11e6-8fc7-6a32af7827ed.png)

Eng, annoyances etc filters

**Comment by Alex-302** [comment]
It is not caused by filters(can not be fixed). Please move to Windows section.
