### ISSUE TITLE
Remove obsolete rules egy.best sites

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardFilters#35635]
Remove obsolete rules of egy.best sites as they seem not to work anymore.

Commented out normal rules so far and if site does not come back for two weeks, I will remove them completely alongside from domain list.

egy.best
egybest.site
egybest.co
egybest.com
egybest.net

**Comment by minanagehsalalma** [comment]
@BlazDT  the site will be back after tomorrow or one more day

**Comment by BlazDT** [comment]
Thank you for the notice :)

**Comment by krystian3w** [comment]
All still no configured / down.

**Comment by minanagehsalalma** [comment]
@krystian3w  i don't know why they didn't do [their word !](https://twitter.com/EgyOfficial/status/1145251940453896192)
they posted it a long while ago on twitter .

**Comment by BlazDT** [comment]
They have until 1st August time. Then rules will be removed.

**Comment by krystian3w** [comment]
I see only logo on homepage (no links on site) or down domain (e.g. error 50x or error load).

**Comment by krystian3w** [comment]
Maybe numeric is better:

```json
! https://github.com/abp-filters/abp-filters-anti-cv/issues/194
egybest2.com,egybest4.com##+js(abort-current-inline-script.js, Math, zfgloaded)
egybest2.com,egybest4.com##+js(window.open-defuser.js)
egybest2.com,egybest4.com,streamega.com##+js(nowebrtc.js)
egybest2.com,egybest4.com##+js(setTimeout-defuser.js, '0x)
||glauvoob.com^
```

**Comment by minanagehsalalma** [comment]
> I see only logo on homepage (no links on site) or down domain (e.g. error 50x or error load).
@krystian3w 
i think cause there still trying to fix it out .
..
@BlazDT 

> They have until 1st August time. Then rules will be removed.

thanks :)

**Comment by BlazDT** [comment]
Site is up again and a colleague already reenabled the rules.
