### ISSUE TITLE
google.com - missed Google shopping sponsored ads

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3564]
[incorrect blocking on page](https://www.google.ru/search?newwindow=1&client=safari&hl=ru-ru&ei=Xyo6WL_5I4WMsAHCvZygCw&q=%D1%81%D1%82%D0%B0%D0%B1%D0%B8%D0%BB%D0%B8%D0%B7%D0%B0%D1%82%D0%BE%D1%80+%D0%B4%D0%BB%D1%8F+gopro&oq=%D1%81%D1%82%D0%B0%D0%B1%D0%B8%D0%BB%D0%B8%D0%B7%D0%B0%D1%82&gs_l=mobile-gws-serp.1.0.0i67k1l3j0l2.158497.160783.0.161490.14.12.2.0.0.0.79.625.11.11.0....0...1.1.64.mobile-gws-serp..1.13.650.3..35i39k1j0i131k1j0i10k1.gd3j4BXbBOU
)

<details>

![image](https://cloud.githubusercontent.com/assets/23258533/20648413/ee757f1c-b4ae-11e6-8fb7-65f66a8017be.png)

</details>

<details>

![image-1](https://cloud.githubusercontent.com/assets/23258533/20648411/cbef9572-b4ae-11e6-97b7-0f4e05843a67.png)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2016-08-10 11:43:09 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: 947D7C51-ECFD-49C9-8A94-B20B303DD8B2

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.95.44 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.75 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.94 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.4.45 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.39.84 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.95 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.34 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.66.15 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.60.12 Enabled=NO

</details>

**Comment by Alex-302** [comment]
Не получается повторить в Макоси и на Айпаде, но это не ложное срабатывание, просто блок не скрыт

**Comment by evgeniy-ADG** [comment]
The same problem:

<details>

![image1 1](https://cloud.githubusercontent.com/assets/15856304/20858783/b9102236-b955-11e6-96f7-e60dd86c4b49.png)

</details>

Unblock useful ads filter is disabled.

**1111021**

**Comment by Alex-302** [comment]
This ad is not shown without VPN. With US VPN is works as expected
<details>

![image](http://imagizer.imageshack.com/img924/8906/qL8s8o.png)
</details>
