### ISSUE TITLE
fishki.net & old.fishki.net missed ads

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3565]
### Фильтры: 

```Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский
Anti-Adblok Killer | Reek
```
### Скриншоты:

<details>

![2016-11-27_14-47-37](https://cloud.githubusercontent.com/assets/16462533/20648490/5ad7e5e4-b4b1-11e6-8967-40087ece1c7f.png)

![2016-11-27_14-48-34](https://cloud.githubusercontent.com/assets/16462533/20648489/5ad6c40c-b4b1-11e6-8318-0112cbb7bf3f.png)

![2016-11-27_14-49-06](https://cloud.githubusercontent.com/assets/16462533/20648491/845ae8d0-b4b1-11e6-96ac-13d7cde8a752.png)

![2016-11-27_14-49-43](https://cloud.githubusercontent.com/assets/16462533/20648493/8d487d40-b4b1-11e6-8b75-577c25d8a517.png)

</details>

**Comment by Alex-302** [comment]
Фон не повторился, рекламные посты убрал.

**Comment by Alex-302** [comment]
А какой Адгард?

**Comment by ayratus** [comment]
Adguard 6.1.258.1302, то есть самый свежий для Windows.

**Comment by Alex-302** [comment]
Если выключить все фильтры, кроме русского, фоновая реклама остаётся?

**Comment by ayratus** [comment]
Что такое фоновая реклама?

**Comment by Alex-302** [comment]
рекламный фон, warthunder.

**Comment by ayratus** [comment]
Выключил все фильтры, кроме русского, появилась реклама вартандера.

**Comment by ayratus** [comment]
Фильтры обновлённые только что.

**Comment by Alex-302** [comment]
Ладно, давайте сначала - какую рекламу вы видите, когда включены фильтры как в первом сообщении?

**Comment by ayratus** [comment]
Когда у меня включены все фильтры как обычно, то на сайте http://old.fishki.net/ я вижу только ту рекламу, которая отмечена словом "Реклама" и буквой Р в кружке.

**Comment by Alex-302** [comment]
Попробуйте обновиться до беты. У меня после добавления правил всё чисто.

**Comment by ayratus** [comment]
Бета версии только избранным присылают, так я понял на https://forum.adguard.com/index.php?threads/%D0%91%D0%B5%D1%82%D0%B0-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-adguard-%D0%B4%D0%BB%D1%8F-windows.1159/?
Вы не можете скинуть сюда инстальник, чтобы я проверил?

**Comment by Alex-302** [comment]
да можно просто в настройках переключить канал обновления
http://s8.hostingkartinok.com/uploads/images/2016/11/4a800d5a184fa82a0d48418650efafbe.png

**Comment by ayratus** [comment]
Ну вот обновился до версии 6.1.258.1302, всё равно на той странице есть рекламное сообщение, например, с заголовком "Мажор 2. Премьера на Rutube"

**Comment by ayratus** [comment]
Неужели у вас его нет?

**Comment by Alex-302** [comment]
Сайт-то какой?

**Comment by ayratus** [comment]
Я же писал http://old.fishki.net/

**Comment by Alex-302** [comment]
Всё скрывается. Там реклама специфическая, её "медленные" правила прячут, поэтому её можно успеть заметить. У вас она совсем не пропадает?

**Comment by ayratus** [comment]
Совсем. А какой фильтр её убирает? Может, у меня его нет?

**Comment by Alex-302** [comment]
русский должен убирать.
Другие фильтры не должны мешать, если сайт не заносится в исключения.

**Comment by ayratus** [comment]
![image](https://cloud.githubusercontent.com/assets/19325361/20678334/20215fd6-b5b8-11e6-928b-f16c5483e7ae.png)
![image](https://cloud.githubusercontent.com/assets/19325361/20678345/2ab1d5d4-b5b8-11e6-8f48-d37e5864a69a.png)
![image](https://cloud.githubusercontent.com/assets/19325361/20678357/36694718-b5b8-11e6-9496-9a49d2d3d646.png)
![image](https://cloud.githubusercontent.com/assets/19325361/20678374/452d4d94-b5b8-11e6-8d99-f5e64db979a2.png)
![image](https://cloud.githubusercontent.com/assets/19325361/20678382/4e89304c-b5b8-11e6-9a0c-b313c20dfca4.png)

**Comment by ayratus** [comment]
Ну вот же!
Слово "Реклама" и буква Р в кружке.

**Comment by Alex-302** [comment]
Даже не знаю. У меня всё скрывается. Проверьте в IE.

**Comment by ayratus** [comment]
Точно! В IE всё убирается!
Вот только что скриншоты сделал.
В IE после жирафа сразу про храм гроба:
![ie](https://cloud.githubusercontent.com/assets/19325361/20705319/4f8040d0-b644-11e6-9f3d-7083e1fca739.jpg)
А в Хроме после жирафа идёт реклама:
![chrome](https://cloud.githubusercontent.com/assets/19325361/20705375/7f914f4e-b644-11e6-8645-a75bdee96835.jpg)

**Comment by ayratus** [comment]
При этом у меня в Хроме нет расширений, которые бы организовывали какое-нибудь зашифрованное прокси или VPN.

**Comment by Alex-302** [comment]
Значит правило работает)
Можно ещё в портативном Хромоподобном браузере проверить, например в этом
https://www.srware.net/en/software_srware_iron_download.php

**Comment by ayratus** [comment]
А почему тогда в Хроме не работает?

**Comment by Alex-302** [comment]
Вы в портативном проверяли?
Причин может быть множество.

**Comment by ayratus** [comment]
Установил ваш Iron и добавил его в фильтруемые приложения адгарда. В нём всё фильтруется, как и в IE.

**Comment by ayratus** [comment]
Получается, только в классическом Хроме почему то не фильтрует ту хитрую рекламу.

**Comment by Alex-302** [comment]
Да реклама не хитрая. С браузером что-то. Откройте журнал фильтрации и обновите вкладку - видны ли запросы к сайту?

**Comment by Serzh-SUP** [comment]
@Alex-302 

Да, запросы видны и их довольно-таки много:

![2016-11-29_16-55-45](https://cloud.githubusercontent.com/assets/16462533/20714531/f3d459c2-b654-11e6-81e3-684b8f9e789a.png)

**Comment by Alex-302** [comment]
Тогда какая-то проблема в обычном Хроме. Если ценных данных нет, можете попробовать снести его полностью с удалением профиля.

**Comment by ayratus** [comment]
Вот журнал фильтрации. Есть запросы, много. Я даже поставил галочку "заблокированные", чтобы отсеять лишнее.
![image](https://cloud.githubusercontent.com/assets/19325361/20717950/069d295c-b679-11e6-9f1f-bae69f615cad.png)

**Comment by Alex-302** [comment]
да не в этом дело

**Comment by ayratus** [comment]
О! Я узнал, в чём разница!

**Comment by ayratus** [comment]
На Хроме я смотрю этот сайт, будучи авторизованным, а на других браузерах я смотрел без авторизации. Вышел из своего логина и Хром тоже стал резать всю рекламу!

**Comment by ayratus** [comment]
Авторизуюсь через аккаунт гугла, то есть через кнопку g+.
Специально зашёл в аккаунт через IE и вот она, реклама:
![image](https://cloud.githubusercontent.com/assets/19325361/20719939/50725178-b67f-11e6-9589-d1233944f3b0.png)
![image](https://cloud.githubusercontent.com/assets/19325361/20719978/6c35091e-b67f-11e6-89b8-dbf0159b5abb.png)
![image](https://cloud.githubusercontent.com/assets/19325361/20719989/7bafdc8e-b67f-11e6-8410-c334516b8845.png)

**Comment by ayratus** [comment]
Теперь что-то проясняется для вас?

**Comment by Alex-302** [comment]
Да, теперь повторилось:)
Проверяйте
```
old.fishki.net##.list-view-items > div[id^="post-"][-ext-has='a[href="/profile/543769/"]']
```

**Comment by ayratus** [comment]
Да, всё отлично! Спасибо! Всё отлично!
Теперь можно такое правило сделать универсальным как для старой версии оформления http://old.fishki.net/ , так и для новой версии http://fishki.net/ , и всё готово, задачу можно будет закрыть!

**Comment by ayratus** [comment]
Погодите, а почему вы так конкретно написали "/profile/543769/" ? Это просто для проверки или это универсальное решение для http://old.fishki.net/ для всех авторизованных пользователей ?

**Comment by Alex-302** [comment]
это номер профиля юзера, от имени которого рекламные посты размещаются.
на новом fishki.net у меня чисто и без этого правила.

**Comment by ayratus** [comment]
Но новом http://fishki.net/ без авторизации есть реклама!
Например, "Полезная реклама"
![image](https://cloud.githubusercontent.com/assets/19325361/20722774/b9b1dd48-b689-11e6-9cc3-1b1316ded0d3.png)
Потом дальше внизу есть "Достали черные пятницы? Начните покупку с бесплатного совета!"
![image](https://cloud.githubusercontent.com/assets/19325361/20722812/dbf627ec-b689-11e6-85b9-3c7bb129de37.png)

**Comment by ayratus** [comment]
И можно ли сделать профиль этого рекламного юзера забить универсально? Например, под маской *

**Comment by Alex-302** [comment]
добавил предыдущее и
```
fishki.net##.drag_list > div.drag_element > div[data-post-id][-ext-has='a[href$="-poleznaja-reklama.html"]']
```



> И можно ли сделать профиль этого рекламного юзера забить универсально? Например, под маской *

не понял?

**Comment by ayratus** [comment]
Ну если изменится номер профиль, тогда фильтрация нарушится.

**Comment by Alex-302** [comment]
а, ну здесь универсального способа нет.

**Comment by ayratus** [comment]
то есть нет какой-нибудь маски типа звёздочки *, дескать, любые символы ?

**Comment by Alex-302** [comment]
А чем маска поможет? Только все посты скроет.
