### ISSUE TITLE
Amazon Ads on the Lock Screen 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3567]
**Description**: Amazon Ads appear on the lock screen 

Screenshot: 

<details>

![screenshot_20161126-104350](https://cloud.githubusercontent.com/assets/17504743/20650711/dea4fce6-b4dd-11e6-8f94-4c9772f225c4.png)
![screenshot_20161126-104323](https://cloud.githubusercontent.com/assets/17504743/20650712/dfa2b962-b4dd-11e6-824a-4fd9da70e00c.png)
![screenshot_20161127-112825](https://cloud.githubusercontent.com/assets/17504743/20650713/e0b99b5e-b4dd-11e6-8bfa-4d179b402c14.png)
![screenshot_20161127-113215](https://cloud.githubusercontent.com/assets/17504743/20650714/e1a60bc4-b4dd-11e6-95c5-642c905d272a.png)

</details>

Forum:
https://forum.adguard.com/index.php?threads/amazon-ads-on-amazon-variant-moto-g4.16632/
https://forum.adguard.com/index.php?threads/android-lock-screen-ads-on-amazon-prime-version-blu-r1-hd.13623/

**Adguard version**: 2.8.58

**Filters list**:
English filter
Spyware filter
Social media filter
Experimental filter
Annoyances filter
Anti-Adblock Killer
Mobile ads filter

**Operating system**:   Android: 6.0.1 

Customer ID: 1453689

**Comment by ameshkov** [comment]
We'll need @TPS's help to crack this issue:)

**Comment by TPS** [comment]
It depends if I keep the phone.  Right now, I'm a little dissatisfied w/ both Amazon & the device, so it's still 50/50 whether I'll keep it.

Stay tuned.… 😑

**Comment by TPS** [comment]
Still, I had a thought: does clearing Amazon Offers' App Data ([like for YT](https://github.com/AdguardTeam/AdguardForAndroid/issues/907) after AG is running) help this @ all?

**Comment by ameshkov** [comment]
> Still, I had a thought: does clearing Amazon Offers' App Data (like for YT after AG is running) help this @ all?

In theory it should be enough to clear Amazon Offers data&cache and to block it's network access.

However, it didn't help here: https://forum.adguard.com/index.php?threads/android-lock-screen-ads-on-amazon-prime-version-blu-r1-hd.13623/

**Comment by gpioneer** [comment]
Hello, I am the submitter of the ticket. Cleaning the cache still displays ads. I'm not sure if it got rid of the non-generic Amazon ads yet or not though. Since yesterday it seems only Amazon ads appear (i.e Kindle, and general "order from Amazon" ad). Will update.

**Comment by gpioneer** [comment]
It appears I am only getting two Amazon ads that must be hardcoded in. Was hoping they can be removed all together

**Comment by TPS** [comment]
Only sol'n to hard-coded ads is reflash, which, I read, is trickier every phone OS update.  Still, thanks for excellent feedback! 👏

@AdguardTeam Still fiddling w/ Amazon to be able to contribute w/ this; will keep y'all posted. :roll_eyes:

**Comment by ameshkov** [comment]
Let's keep it open for some time then.

@gpioneer what are these hardcoded ads? Some amazon-specific stuff?

**Comment by TPS** [comment]
Just to officially inform y'all:  I didn't keep the Prime phone (nothing wrong w/ the device; just gotta a better phone for a better deal 😀), so I can't help with this.… Other than moral support:  Go @AdguardTeam! 🏁🎆🎇🎉🎊
