### ISSUE TITLE
Feature request google anti tracker 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3568]
**Description**:
Right-clicking on google search result, we can copy the link. However
Google wants to analyze traffics and adds extra stuff to the original
link. Please make a filter that gets rid of the extra stuff on copying
link. There is a chrome extension that does this: source code on
https://github.com/Rob--W/dont-track-me-google/ and extension on
https://chrome.google.com/webstore/detail/dont-track-me-google/gdbofhhdmcladcmmfjolgndfkpobecpg?utm_source=chrome-app-launcher-info-dialog.

Customer ID: 1455593

**Comment by Alex-302** [comment]
Please move it to Extension section.

**Comment by Tetiana2020** [comment]
Moved to
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/447
