### ISSUE TITLE
[Windows] www.techpowerup.com - Missed Ads 

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#3569]
![](http://i.imgur.com/hHRK6Fr.png)

https://www.techpowerup.com/

**Adguard version**: 6.1.294.1539

**Operating system**: Windows 10

**Browser**: Chrome

```
techpowerup.com#$#body { background-image: none !important; background-color: white !important; }
techpowerup.com##a[target="_blank"][rel="nofollow external"]
```

**Comment by seanl-adg** [comment]
Sorry, checked this too late. It seems that those banners are gone now, but added the first rule. Second rule is too wide.
