### ISSUE TITLE
com.dcinside.app 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3570]
**Description**:
Missed ads in the DCInside app:
https://play.google.com/store/apps/details?id=com.dcinside.app&hl=en

**Original report:**
https://github.com/AdguardTeam/AdguardForAndroid/issues/931

**Screenshot:**
https://pp.vk.me/c638926/v638926269/dff4/RQYuy6ldmiE.jpg

**Comment by seanl-adg** [comment]
I think it's the user who misconfigured the app. The user maybe not subscribed to List-KR or does not enabled ipv6 disable.
