### ISSUE TITLE
Nekto.me app ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3572]
**Description**:
Details are here:
https://github.com/AdguardTeam/AdguardForAndroid/issues/933

**Comment by Alex-302** [comment]
Not reproduced
<details>

![screenshot_2016-11-28-17-23-55](https://cloud.githubusercontent.com/assets/8361299/20673935/a07f8668-b58f-11e6-9ea6-c170c6b56827.png)

</details>

Asked for log/har

**Comment by vgavrish** [comment]
лог [debug (5).txt](https://github.com/AdguardTeam/AdguardFilters/files/618565/debug.5.txt)
Время возникновения
проблемы - 2:50-2:55 (МСК)

**Comment by Alex-302** [comment]
Ответил в https://github.com/AdguardTeam/AdguardForAndroid/issues/933

**Comment by Alex-302** [comment]
Вроде всё заблокировано.
Попроси понажимать по баннеру, интересует какая рекламная система
![image](http://s8.hostingkartinok.com/uploads/images/2016/11/2c1bf125c7442db3270f57c14eff4e21.png)
Если никакой информации не будет, нужно выключить фильтры, щёлкнуть по баннеру и снова прислать HTTP лог с указанием точного времени.

**Comment by vgavrish** [comment]
отписала

**Comment by vgavrish** [comment]
@Alex-302 оно?
![image](https://cloud.githubusercontent.com/assets/18548949/20884443/edcad800-baf3-11e6-8954-47e829efa0e1.png)

**Comment by Alex-302** [comment]
Да. Если потыкать, то можно(наверное) найти название рекламной системы.
Спроси заодно - при выключенном инете этот блок есть?
