### ISSUE TITLE
Inshorts app fullscreen ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3573]
**Description**:
https://play.google.com/store/apps/details?id=com.nis.app

Report:
http://forum.xda-developers.com/showpost.php?p=69767871&postcount=1881

**Comment by Alex-302** [comment]
Not reproduced on my end.

**Comment by seanl-adg** [comment]
Not reproduced too, but I will try to setup a indian VPN.
