### ISSUE TITLE
lacuerda.net False positive

### ISSUE THREAD

**Issue by estebanpanelli** [AdguardTeam/AdguardFilters#35758]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
False positive for website lacuerda.net not loading stylesheet
* **Current behaviour**: 
Blocking stylesheets for the site

***Steps to reproduce the problem***:
Go to: lacuerda.net

**Comment by Alex-302** [comment]
Hi
Not reproduced
<details>

![image](https://user-images.githubusercontent.com/8361299/60087432-ae0aed00-9745-11e9-9e74-67cdede43118.png)

</details>

Which filter causes it?

**Comment by estebanpanelli** [comment]
![image](https://user-images.githubusercontent.com/22087348/60112061-82880280-9745-11e9-8c10-8a406b94498e.png)

**Comment by Alex-302** [comment]
Our filter does not have this rule. 
We have only `||pub.lacuerda.net^`, but uBO blocks as `||lacuerda.net^$stylesheet` or `||lacuerda.net^$script`. It seems their bug. Not reproduced in AdGuard.
![image](https://user-images.githubusercontent.com/8361299/60175471-5b503480-981c-11e9-8afd-ea740e17d232.png)

**Comment by AdamWr** [comment]
I guess it was due to this rule - https://github.com/AdguardTeam/FiltersRegistry/commit/2d8ae7ee5a88e41901f4af8dae032bb53935f90b#diff-909cb1e3434dff06d07785976540b983L64, should be okay now.
