### ISSUE TITLE
http://eu.battle.net/en/ - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3575]
http://eu.battle.net/en/ - incorrect blocking

This page contains the following errors: error on line 10
at column 122: EntityRef: expecting ';' Below is a rendering of the
page up to the first error.
Screenshot: use the following code

<details>

![photo40300305659835614](https://cloud.githubusercontent.com/assets/23258533/20660549/e984c086-b552-11e6-858e-613835e2b447.jpg)

</details>

<details>

"androidVersion" : "4.2.2 (sdk=17)",
  "appLanguage" : "en",
  "applicationId" : "4d2bb5658efd4811",
  "versionName" : "2.8.40",
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "intel 3GD52I",
  "upstreamProxySettings" : null,
  "enabledFilterIds" : [ 2, 3, 4, 14, 1, 11, 211 ],
  "environment" : "beta",
  "filteringQuality" : "SPEEDY",
  "updateChannel" : "BETA",
  "iconType" : "LOW_PRIORITY",
"sslMitmConfiguration" : "{\"mitmListMode\":\"WHITELIST\",\"mitmList\":\"1018 domains\",\"certificateInstalledToSystemStorage\":null}",

</details>

**Comment by Alex-302** [comment]
It is a bug.
