### ISSUE TITLE
[NSFW] smutr.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#35756]
**Site Sample** | 
----------------|
https://smutr.com/v/61390/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1903 x64
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.1.2817 RELEASE** 
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
|Disable cache for 3rd-party requests
| **=== FILTERS ENABLED ===**
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| Fuck Fuckadblock
| **SECTION :: Ads**
| Adguard Base Filter 
| EasyList
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| EasyPrivacy
| Fanboy's Anti-Facebook List 
| Fanboy's Enhanced Tracking List 
| **SECTION :: Social**
| Adguard Social Filter
| Fanboy's Social Blocking List 
| **SECTION :: Annoyances**
| Adblock Warning Removal List
| Adguard Annoyances
| Fanboy's Annoyances 
| Fanboy's Cookiemonster List
| **SECTION :: Security**
| Malware Domains
| Spam404
| NoCoin Filter List
| **SECTION :: Customs**
| AlleBlock
| EasyList Polish 
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

POPUPS (some blocked via Adguard Popup Blocker), REDIRECTS (after click on LOGO SITE), ad leftover on right down corner, ad video before main content.

<details><summary><b>Screenshot:</b></summary>

![scr-1561392357-001](https://user-images.githubusercontent.com/9846948/60034505-1a84de00-96ab-11e9-988f-220adba194ec.png)
![scr-1561392382-001](https://user-images.githubusercontent.com/9846948/60034506-1a84de00-96ab-11e9-85e5-ba8c157c09b3.png)
![scr-1561392507-001](https://user-images.githubusercontent.com/9846948/60034507-1b1d7480-96ab-11e9-967e-129a75357475.png)

</details><br/>

@AdamWr @Alex-302

**Comment by Alex-302** [comment]
Video ad is a part of the main video.
