### ISSUE TITLE
addons.mozilla.org - annoying element // question

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3576]
1. The page is in the HTTPS exceptions for some reason, can it be removed from there?
2. If possible, add a rule to block the highlighted annoying element:

![image](https://cloud.githubusercontent.com/assets/15856304/20662336/ad455a0a-b55b-11e6-80e4-10b9c30e553c.png)

**Comment by Alex-302** [comment]
Какой Адгард, фильтры?

**Comment by Serzh-SUP** [comment]
@Alex-302 

**v6.1.296.1549**

**Фильтры:** 
```
английский фильтр
фильтр счётчиков и системы аналитики
фильтр виджетов социальных сетей
фильтр раздражителей 
фильтр полезной рекламы
русский фильтр
```
По-прежнему появляется окно приветствия при первом открытии сайта addons.mozilla.org. Последующие страницы открываются без этого окна, но если перезапустить браузер или завершить сессию и потом начать новую, то приветствие опять выскакивает. На данный момент использует правило [addons.mozilla.org###site-welcome].

**Comment by Alex-302** [comment]
А, mozilla.org в исключениях HTTPS, а у тебя видать расширение стоит.

**Comment by Alex-302** [comment]
Фильтрами оно не скрывается, добавил в раздражители
```
addons.mozilla.org###site-welcome.site-balloon
```
