### ISSUE TITLE
aainflight.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#35761]
***Description***:
* **Current behaviour**: 

Throws a "Too many redirects" error when AdGuard is enabled  and the user is accessing the website from an American Airlines flight.

This is a customer portal allowing American Airlines passengers to purchase internet trafic while they're on a flight.

<details><summary>Screenshot:</summary>

n/a
</details><br/>

* **Expected behaviour**: 

AdGuard shouldn't render the site unusable.

***Steps to reproduce the problem***:

1. get on American Airlines flight
2. on phone, turn off any vpns; I use Proton
3. connect to WiFi network
4. using safari go to aainflight.com
5. page attempts to load but then says cannot due to too many redirects
6. turn off AdGuard pro
7. using safari go to aainflight.com
8. page loads which then allows me to purchase internet service

***System configuration***

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="AdGuard Base filter" Version=2.0.54.3 Enabled=YES
ID=11 Name="AdGuard Mobile Ads filter" Version=2.0.6.17 Enabled=YES
ID=3 Name="AdGuard Tracking Protection filter" Version=2.0.7.30 Enabled=YES
ID=4 Name="AdGuard Social Media filter" Version=2.0.11.83 Enabled=YES
ID=14 Name="AdGuard Annoyances filter" Version=2.0.21.25 Enabled=YES
ID=208 Name="Malware Domains" Version=2.0.41.12 Enabled=YES
ID=12 Name="AdGuard Safari filter" Version=2.0.1.38 Enabled=YES

Information                            | Value
---                                    | ---
Operating system:                      | iOS
Operating system version (Android/iOS) | 12.3.1
Browser:                               | Safari
AdGuard version:                       | 2.1.1.165 Pro
Filters enabled:                       | See above
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | Default
Helpdesk ID (if exists):               | 2241918

**Comment by Alex-302** [comment]
I see only blank page, with or without AdGuard.

**Comment by Alex-302** [comment]
@akmLaVx

**Comment by akmLaVx** [comment]
We won't get any content in here - this is some kind of an "in-flight" portal only available for American Airlines passengers.

**Comment by Alex-302** [comment]
I don't know how to fix it without any data.
Try `@@||aainflight.com^`
