### ISSUE TITLE
https://newengland.com/ - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3578]
https://newengland.com/yankee-magazine/living/home-decor/vermont-family-christmas/

![image](https://cloud.githubusercontent.com/assets/15856304/20667429/db3e9b18-b571-11e6-988d-188a550b0417.png)

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/20667448/f2cba8ac-b571-11e6-8368-ef9bb4c04415.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
newengland.com##div[id^="haven-paywall"]
```
