### ISSUE TITLE
http://www.ecigtalk.ru/ - incorrect blocking 

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3579]
http://www.ecigtalk.ru/ - incorrect blocking 

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/20668449/a32d0a38-b577-11e6-804c-606e95e1348f.png)

</details>

<details>

![image2](https://cloud.githubusercontent.com/assets/23258533/20668463/b1fa35c2-b577-11e6-8a25-97dca87f378a.png)

</details>

<details>

Application version: 1.0.5.38
Application lifetime: 2015-11-30 12:57:48 +0000

Device: iPad
Platform: iPhone OS
OS: 9.2.1
ID: BA55B08B-B14C-4387-B159-185B1F6115FE

Locale: ru
Region: ru

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.79.63 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.5.7 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.9.2 Enabled=YES
ID Name="Filter for useful ads" Version=1.0.0.89 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.32.6 Enabled=YES
ID Name="Safari Filter" Version=1.0.0.50 Enabled=YES
ID5 Name="RU AdList" Version=1.0.54.60 Enabled=YES
ID3 Name="Fanboy's Social Blocking List" Version=1.0.54.56 Enabled=YES

</details>

**Comment by Alex-302** [comment]
А ссылка на страницу где?)
Она нужна всегдаа, даже если всё очевидно.

Пока я жду ссылку, можно для пробы выключить эти фильтры)
```
ID�5 Name="RU AdList" Version=1.0.54.60 Enabled=YES
ID�3 Name="Fanboy's Social Blocking List" Version=1.0.54.56 Enabled=YES
```

**Comment by evgeniy-ADG** [comment]
http://www.ecigtalk.ru/forum/f14/t137282.html вот ссылка, повторилось на винде

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21141529/69646b9a-c146-11e6-8257-781383d069a1.png)

<details>

А вот так без нас 

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21141555/877a7f0c-c146-11e6-988a-048680617e7f.png)


Чет картинка не загрузилась, но хотя бы видно, что она там есть. Фильтры стандартные, английский-русский, виджеты, раздражители и safebrowsing

**Comment by Alex-302** [comment]
поправил.
