### ISSUE TITLE
http://cafe.daum.net/BerryGood - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3580]
http://cafe.daum.net/BerryGood - incorrect blocking
can not see members who are connected.

<details>

![safasf](https://cloud.githubusercontent.com/assets/23258533/20668759/228b093c-b579-11e6-97ed-bfc70d9fdf52.png)

</details>

<details>

Os version: Microsoft Windows NT 10.0.14393.0
Dot .net version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: 856aff3ed0c34cd1913129c1ef0acfd0
Language: ko
AppVersion: 6.1.258.1302
Main settings: 
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:227 Name: List-KR Url: https://raw.githubusercontent.com/SlowMemory/List-KR/master/filter.txt
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Wfp
Ads Blocked: 1802, Trackers Blocked: 556
Filtering Mode: Driver
Application lifetime: 08:55:53.7127820
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": false,
  "BlockWebRtc": false,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"

</details>

**Comment by seanl-adg** [comment]
I can't reproduce the issue with the user's filter and stealth mode settings for now.

I have some things to let the user try in order to resolved the problem. Please pass it to the user and tell the user if any of those resolves the problem.

 * Disable the stealth mode.
 * Leave the stealth mode enabled, and add `@@||cafe.daum.net/_c21_/dwr/cafechat/$stealth` or `@@||cafe.daum.net/_c21_/dwr/cafechat/` to the user filter.
 * Add a rule `@@||cafe.daum.net/_pageview/` to the user filter.
 * Temporarily disable a filter List-KR.

**Comment by osavranska** [comment]
passed to the user

**Comment by seanl-adg** [comment]
I'll close it for now as there seems to be no response from the user.
