### ISSUE TITLE
Hill Climb Racing app - Missed Ads 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3581]
**Description**: Missed ads in the application
https://play.google.com/store/apps/details?id=com.fingersoft.hillclimb
Appear after the race is over on the result screen.

Screenshot: 
<details>

![screenshot_2016-11-28-23-38-35](https://cloud.githubusercontent.com/assets/17504743/20690502/b397b038-b5d3-11e6-8459-9d9b1d0936cd.jpg)
</details>

**Adguard version**: 2.8.58

**Filters list**:
English filter
Spyware filter
Social media filter
Experimental filter
Annoyances filter
Anti-Adblock Killer
Mobile ads 
Russian

**Operating system**: Android: 6.0.1

Reproduced with HTTPS filtering on. 

Customer ID: 1326130

**Comment by Alex-302** [comment]
Is it google or facebook ads? What mode - proxy(auto/manual) or VPN?

**Comment by Tetiana2020** [comment]
@Alex-302 it's VPN.

**Comment by Alex-302** [comment]
@Tetiana2020 
> HTTPS filtering on

default or black lict mode?

Please press on this icon and tell me about ad system(as I see - it is Google ads, should be blocked)

![image](http://imagizer.imageshack.com/img922/8979/R4x38Y.png)
