### ISSUE TITLE
Weather & Clock Widget Android app - Missed ads

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3582]
**Description**: Missed ads in the application
https://play.google.com/store/apps/details?id=com.devexpert.weather

Screenshot:
<details>

![screenshot_2016-11-28-23-37-53_720](https://cloud.githubusercontent.com/assets/17504743/20690650/885a3b6a-b5d4-11e6-98c0-71933fe35d09.jpg)

</details>

**Adguard version**: 2.8.58

**Filters list**:
English filter
Spyware filter
Social media filter
Experimental filter
Annoyances filter
Anti-Adblock Killer
Mobile ads
Russian

Operating system: Android: 6.0.1

Reproduced with HTTPS filtering on.

Customer ID: 1326130

**Comment by Alex-302** [comment]
It is builtin ad.
@nkartyshov can we deceive this app? This dummy is shown when ads are blocked, but $empty modified doesn't helps.

**Comment by evgeniy-ADG** [comment]
Есть новости? Нет? @nkartyshov @Alex-302

**Comment by Alex-302** [comment]
@nkartyshov а условия её появления не узнать? Когда блокировка выключена, видна только реклама. Пробовал частично разблокировать, но слишком много и непрерывно посылает запросов, так трафик весь съест

**Comment by nkartyshov** [comment]
@Alex-302 К сожалению нет. В FiltingLog видны запросы только когда нажимаем на рекламу, при открытие ничего нету.

**Comment by Alex-302** [comment]
Тогда закрываю.
