### ISSUE TITLE
Musixmatch app

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3583]
**Description**: Реклама
https://play.google.com/store/apps/details?id=com.musixmatch.android.lyrify&hl=ru

лог 
[debug (3).txt](https://github.com/AdguardTeam/AdguardFilters/files/618385/debug.3.txt)
Время проблемы 17:18-17:19.

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20701104/c339dd9a-b619-11e6-9d40-5bc188145f3b.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20701106/c94e0396-b619-11e6-8a9a-a44e08404499.png)

</details>

**Adguard version**:" 2.8.58

**Filters list**: 2, 3, 4, 1, 11 
 "filteringQuality" : "FULL",

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Фильтрация HTTPS не включена?
Добавил
```
||graph.facebook.com^$app=com.musixmatch.android.lyrify
```
нужно проверить и дать мне знать о результате.
Если всё ок - закрывай.

**Comment by vgavrish** [comment]
HTTPS  включена
отписала
