### ISSUE TITLE
reddit.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#35843]
Cookies 
![scr-1561566555-001](https://user-images.githubusercontent.com/9846948/60197777-63ba6680-9840-11e9-9541-b6326c3d8cf0.png)

@Alex-302

**Comment by Alex-302** [comment]
Not reproduced. Please show HTML of this element.

**Comment by FadeMind** [comment]
![scr-1561632683-001](https://user-images.githubusercontent.com/9846948/60260678-649fd680-98da-11e9-9e79-67a0fb730dfa.png)

**Comment by Alex-302** [comment]
better upload saved page(log out before is). It seems it is not a top element of popup.

**Comment by FadeMind** [comment]
![scr-1561648568-001](https://user-images.githubusercontent.com/9846948/60278326-82336700-98ff-11e9-8e34-b69e3ead073e.png)
![scr-1561648643-001](https://user-images.githubusercontent.com/9846948/60278327-82cbfd80-98ff-11e9-8e1a-f1a07f1994e8.png)


Workaround works for me:
```
reddit.com###SHORTCUT_FOCUSABLE_DIV > div:last-child
```

**Comment by Alex-302** [comment]
Please check:
```
reddit.com###SHORTCUT_FOCUSABLE_DIV > style+div > div > form > div[style*="---toaster-indicator-color:#24A0ED;"]
```

**Comment by FadeMind** [comment]
@Alex-302 works well. Thanks
