### ISSUE TITLE
http://www.ph4.ru - Anti Adblock Script

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3586]
**Description**:
http://www.ph4.ru/kidsafe_index.php

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20705446/a950ebfa-b62b-11e6-87de-dc4d12950fc1.png)

</details>

**Adguard version**: 6.1.294

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в фильтр раздражителей
```
||ph4.ru/images/b/
```
