### ISSUE TITLE
Peel Smart Remote ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3588]
**Description**: 
https://play.google.com/store/apps/details?id=tv.peel.app&hl=ru
При входе в "пульт" появляется блок экрана

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20708505/f0662098-b638-11e6-926d-7fc373f71646.png)

</details>

**Adguard version**: 2.8.53

**Filters list**: 1,2,3,4,11,14
Full
Https
логи если что попросила

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не загружается у меня. Можешь APK раздобыть?

**Comment by vgavrish** [comment]
Пока есть только версия 9.5.4.2
https://yadi.sk/d/ipCDpJsLzu2im

**Comment by vgavrish** [comment]
940023
Логи 
[debug (11).txt](https://github.com/AdguardTeam/AdguardFilters/files/623934/debug.11.txt)
Время 16.52 Мск (20.52 Томск)

**Comment by Alex-302** [comment]
В логе ни одного запроса от этого приложения. Пусть остановит приложение в настройках дроида, и снова повторит. Время нужно его локальное, как в логе. 
Когда появится реклама, защиту нужно остановить. Время окончания тоже нужно.

**Comment by vgavrish** [comment]
ок, отписала

**Comment by vgavrish** [comment]
вот что-то прислал
[debug (15).txt](https://github.com/AdguardTeam/AdguardFilters/files/630649/debug.15.txt)
время 20.23-20.24

**Comment by Alex-302** [comment]
опять полный лог, вместо http запросов, и опять ничего, относящегося к этому приложению. Надеюсь приложение было закрыто перед снятием лога?
Есть ещё вариант - в расширенных настройках есть настройка вышестоящего прокси. Тужа нужно вбить любой ip:port и посмотреть, будет ли реклама в приложении.

**Comment by Alex-302** [comment]
Если юзер не против, можно пригласить сюда, чтоб напрямую общаться.

**Comment by acidpiro** [comment]
Доброго времени суток. Приложение было закрыто перед снятием лога, как и было указано в инструкции. Единственный непонятный момент «указать время начала проблемы и время окончания». Я просто запускаю приложение - реклама есть сразу в части интерфейса (это время начала?), что значит время окончания? Реклама не исчезает. «в расширенных настройках есть настройка вышестоящего прокси. Тужа нужно вбить любой ip:port и посмотреть, будет ли реклама в приложении.» - попробовал, реклама есть. Может, что-то делаю не так.

**Comment by Alex-302** [comment]
> указать время начала проблемы и время окончания

видать некорректная формулировка в инструкции. Скорее время запуска приложения. Окончание - 
когда защиты выключили, чтоб знать какой журнала лога смотреть.



> вышестоящего прокси. Тужа нужно вбить любой ip:port

Ещё вопрос - телефон рутован? Для того чтоб завернуть трафик приложений через прокси, возможно нужны права root.

Также реклама может быть встроенной, и обновляться при обновлении приложения.
Можете файл APK прислать? На мои устройства из маркета не устанавливается.

**Comment by acidpiro** [comment]
Давайте разберемся по порядку.

1. Останавливаем приложение в настройках андроид. 
2. Переключите "Уровень логгирования" на "Записывать HTTP запросы" в расширенных настройках Adguard. (переключаем)
3. Воспроизведите проблему. (Просто запускаем приложение? Нужно в приложении совершать дейтвия?)
4. Переключите уровень логгирования обратно на обычный.
5. Отправьте нам сообщение из программы и укажите конкретное время возникновения проблемы (пункт меню "Сообщение в поддержку"). - время запуска приложения? часы и минуты? (секунды в телефоне не отображаются)

p.s. телефон не рутирован, прошивка стоковая. Это приложение предустановлено было, может, в этом и проблема..

p.p.s. файл приложения ниже

[Peel_Smart_Remote_TV_Guide_9.zip](https://github.com/AdguardTeam/AdguardFilters/files/642746/Peel_Smart_Remote_TV_Guide_9.zip)

**Comment by Alex-302** [comment]
Вот он баннер
<details>

![image](http://imagizer.imageshack.com/img922/3532/GBqFT3.png)
</details>
Встроен. Адгардом не убрать.

**Comment by Alex-302** [comment]
Ещё вопрос - бывают ситуации, когда этот баннер не отображается?

**Comment by acidpiro** [comment]
Бывает так, что он появляется не сразу, а с небольшой задержкой (в секунду примерно), что натолкнуло на мысль о том, что, возможно, этот блок - рекламный модуль. И появился он сравнительно недавно, с последними обновлениями программы. Кстати, в этом приложении раньше (до этого банера) была другая реклама в другом месте (возле кнопки вкл/выкл), которую адгард успешно блокировал. Получается, этот банер - часть приложения?

**Comment by acidpiro** [comment]
Без адгарда месте банера другая реклама (меняющаяся)

**Comment by acidpiro** [comment]
Всё-таки заблокировали баннер!! 👍

**Comment by Alex-302** [comment]
Возможно:)
