### ISSUE TITLE
SO FOOT app doesn't start

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3589]
https://play.google.com/store/apps/details?id=com.sofoot&hl=fr

"enabledFilterIds" : [ 2, 3, 4, 11, 113 ],
I suspect the Mobile ads filter, it's started working without this filter t my end.

<details>

before disabling Mobile ads filter

![image](https://cloud.githubusercontent.com/assets/15856304/20708626/7acf42c8-b639-11e6-90b8-40df814e819a.png)

and after

![image](https://cloud.githubusercontent.com/assets/15856304/20708618/75257cfc-b639-11e6-873e-d864b9e445af.png)

</details>

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||engine.widespace.com/map/provisioning?appId=com.sofoot$app=com.sofoot
```
