### ISSUE TITLE
http://www.csnbayarea.com - videos are blocked

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3590]
http://www.csnbayarea.com/video/klay-thompson-makes-paper-airplane-throws-it-camera-end-interview

<details>

protection's enabled

![image](https://cloud.githubusercontent.com/assets/15856304/20708826/718b8360-b63a-11e6-82a3-57c3ec988ae2.png)

and disabled

![image](https://cloud.githubusercontent.com/assets/15856304/20708842/84671d3c-b63a-11e6-8a31-32f451e6f9b9.png)

<details>

Application version: 1.3.0
Applicaton shared support folder:/Library/Application Support/com.adguard.Adguard
Applicaton support folder:/Users/dmurph/Library/Application Support/com.adguard.Adguard
Filtration Enabled
Filtration mode: direct
Blocked: 56823
Application lifetime: 2016-05-06 14:12:28 +0000
Platform: Mac OS X
OS: 1012
Locale: en-US

Antibanner filter: Enabled
Antiphishing filter: Enabled
Parental control: Disabled
Privacy protection: Enabled
HTTPS: Enabled
Assistant: Enabled
Web of trust: Disabled
Popup blocker: Disabled

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0
ID=2 Name="English filter" Version=1.1.1.72
ID=3 Name="Spyware filter" Version=1.0.9.19
ID=10 Name="Filter for useful ads" Version=1.0.0.89
ID=113 Name="Liste FR" Version=1.0.70.1

SSL exception domains:
plimus.com
payproglobal.com
avangate.com
paypal.com
halifax-online.co.uk
identity.virginmedia.com
signin.ebay.com
signin.ebay.co.uk
icbc.com.cn
hsbc.co.uk
hsbc.com
secure.hsbcnet.com
bv-activebanking.de
hsbc.ca
hsbc.com.au
chase.com
secure.bnpparibas.net
bnpparibasfortis.be
webbanking.bgl.lu
secure.bnl.it
barclays.co.uk
bankofamerica.com
deutsche-bank.de
deutsche-bank.es
deutsche-bank.it
deutsche-bank.pt
db-pbc.pl
db.com
qweb.quercia.com
citibank.com
wellsfargo.com
societegenerale.fr
societegenerale.com
sgeb.bg
rbsinternational.com
sberbank.ru
alfabank.ru
zakupki.gov.ru
194.105.148.87
aus.mozilla.org
aus1.mozilla.org
aus2.mozilla.org
aus3.mozilla.org
aus4.mozilla.org
aus5.mozilla.org
aus6.mozilla.org
addons.mozilla.org
versioncheck.addons.mozilla.org
dl.dropboxusercontent.com
lastpass.com
mozilla.org
mozilla.net
webmoney.ru
wmtransfer.com
adtidy.org
chrome.adtidy.org
eff.org
8pecxstudios.com
rbsdigital.com
commonbank.com.ua
sparkasse-fuerth.de
ing-diba.de
apple.com

**Comment by Alex-302** [comment]
I can't watch these videos even without AG.
