### ISSUE TITLE
Microsoft Solitaire Collection app

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3591]
**Description**: Приложение с магазина
Приложение добавлено в список фильтруемых

> Не фильтруется реклама ни в квадратных окошках, ни полноэкранная, ни реклама игрушек, ни реклама крема для бритья

+ в разделах "Ежедневных заданиях" и в "Звёздном клубе" рекламный ролик

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20708605/60ff077a-b639-11e6-98c2-8baad4514bae.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20708939/0df7f62a-b63b-11e6-83c6-99ff54653215.png)

![image](https://cloud.githubusercontent.com/assets/18548949/20708955/238a1f7c-b63b-11e6-9e72-7da4702c4d37.png)

</details>

**Adguard version**: 6.1.258.1302

**Filters list**: 1,2

**Operating system**: Вин 10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Что-то еле загружается у меня. Как повторить рекламу - просто в самом приложении, играть не нужно?

**Comment by Alex-302** [comment]
Попробуй такие правила:
```
||api.taboola.com/1.1/json/microsoftsolitairecollection/recommendations.get
||adbroker.mp.dse.microsoft.com^
```
---
Это на память)
```
||api.taboola.com/1.1/json/microsoftsolitairecollection/recommendations.get?app.type=desktop&app.apikey=fd3c24f39fb8c3a4e0a3d8f8504b67b864cc007d&app.name=microsoftsolitairecollection&rec.count=2&rec.thumbnail.width=100&rec.thumbnail.height=100&rec.visible=false&source.type=text&source.id=https://www.microsoft.com/en-us/store/apps/microsoft-solitaire-collection/9wzdncrfhwd2&source.url=https://www.microsoft.com/en-us/store/apps/microsoft-solitaire-collection/9wzdncrfhwd2&source.placement=End-of-Game-Screen&user.session=v2_f23b2a37a9bcfeaf4576802dfb65fe7b_9bf4a3f543e8d94c405b2da22f26b79e_1480432141_1480432141_CNawjgYQhdA_GIiKh4WLKyABKAU&user.agent=Windows-10-Native-App---Solitaire&device.id=9bf4a3f543e8d94c405b2da22f26b79e
https://adbroker.mp.dse.microsoft.com/v1/adbroker/ad?adm=2&cfmt=text%2cimage%2chtml5richmedia%2cpolyad&sft=jpeg%2cpng%2cgif&cltp=app&rafb=3&nct=1&idtp=mid&uid=781df6e2-80ba-409b-8361-5ef9355ec6c2&pubid=c6a11590-c4c9-496c-a51f-cffa42edccba&pid=300548&asid=26b23fcfae6648c3b6ab3fad29516ad0&aid=1a36fd17-5161-4651-ae2d-13384e427ea8&adid=9bf4a3f543e8d94c405b2da22f26b79e&devmake=VMware%2c%20Inc.&devmodel=VMware%20Virtual%20Platform&devos=WINDOWS&devosver=10.0.10240.16725&devfrm=Unknown&devfam=Windows.Desktop&geoacc=2.00375e%2b07&lc=ru&sdkversion=10.0.1611.17001&sdktype=msa-xaml-display&w=300&h=250&vx=701.00&vy=298.00&vosp=1.00&vocc=2&vop=1.00&vhf=2&vaw=1103.00&vah=869.00&ProviderId=ProviderId
```

**Comment by Serzh-SUP** [comment]
@Alex-302 

**Для повторения рекламы:**

**1. Запустить игру
2. Дождаться логона на сервере и синхронизации данных.
3. Зайти в "Ежедневные задания", открыть игру с меткой "Эксперт" или
"Сложная" - появится ролик.**

**Comment by Alex-302** [comment]
@Serzh-SUP @vgavrish никак ролик не повторяется. Проверьте с правилами выше.
Если стабильно повторяется, могу удалённо глянуть.

**Comment by vgavrish** [comment]
@Alex-302 
помогло это правило
||adbroker.mp.dse.microsoft.com^

Второе ничего не дало

**Comment by Alex-302** [comment]
Спасибо, добавил

**Comment by vgavrish** [comment]
> Включена фильтрация для пасьянса, но в одном из разделов - Звёздный клуб - реклама снова стала показываться.
На вложении - настройки adguard на фоне полноэкранного рекламного ролика в пасьянсе.
![image](https://cloud.githubusercontent.com/assets/18548949/21740796/209a2d92-d4cd-11e6-8e91-37527227f47e.png)

Russian filter
English filter 
EasyList China 
Adblock polskie reguły
WFP
HTTPS
6.1.298.1564
Win 10

**Comment by Alex-302** [comment]
А в фильтруемые именно это приложение добавлено?

**Comment by vgavrish** [comment]
да, добавлено вродь
еще в тот раз проблему у него решили, и на скриншоте вот добавлено вроде

**Comment by Yana-SUP** [comment]
есть какие-то новости?

**Comment by Alex-302** [comment]
Нет. У меня рекламы нет. Но я и не играл особо.

**Comment by evgeniy-ADG** [comment]
>У меня Windows 10 разных версий - x86, x64, релиз, инсайдерская последняя, в виртуальной машине и на разных железках - везде реклама показывается.
Для лицезрения выберите "Ежедневные задания", откройте любой день и запустите экспертный уровень (****). Получите ролик. На простых уровнях обычно не запускают.
Отчёт отправил.

Реклама в пасьянсе полезла в 00:34, длится секунд 15-20.

[Uploading debug (3).txt…]()

**Comment by Alex-302** [comment]
Лог не поможет. Нужно Фидлером смотреть. Спроси про удалённый доступ.

**Comment by vgavrish** [comment]
окей, написала

**Comment by evgeniy-ADG** [comment]
Там согласны на ТВ, @Alex-302 логин и парлль тут: 1325700
Могу сегодня с 14 до 19.

**Comment by Alex-302** [comment]
Подключился.
Пока такие правила
```
||api.vungle.com/api/v3/reportAd
||api.vungle.com/api/v3/sessionEnd
||api.vungle.com/api/v3/sessionStart
||api.vungle.com/api/v3/requestAd 
||api.vungle.com/api/v3/requestStreamingAd
```
подождём отзыва. Если ок - добавлю.

**Comment by vgavrish** [comment]
>1. На Windows 10 x64 (десктоп и виртуальная машина, на которой выполнялась отладка) фильтрация исправно работает. Не считая задержки в игре на месте рекламы - но тут уж вряд ли что можно сделать. Или можно?

> 2.  На Windows 10 x86 (планшет Samsung Ativ Smart pc 500) фильтрация заработала и работала на протяжении примерно 4-5 игр, в которых должна была быть реклама. После этого ролики снова стали показываться (не из старых загрузок, их я предварительно удалил). Кроме того, стали показываться ролики, которые показывались осенью и их победили в конце ноября при помощи двух фильтров, которые и сейчас в adguard имеются. Похоже, что MS борется как-то с вашей программой и счёт пока в их пользу :( 
Планшет, конечно, весьма "могучий" и сомнительно, что на нём получится организовать сеанс отладки, но я попробую и сообщу, если получится.

> 3. На Windows 10 x64 Insider Preview b.15014 adguard блокирует работу Edge (а не adblocker uBlock, как вчера подумали). На релизных сборках такой блокировки нет. 
Оно, конечно, предварительная версия, но через пару месяцев (обещано в апреле) это будет релизом.

**Comment by vgavrish** [comment]
в 3м пунтке что там было?

**Comment by Alex-302** [comment]
3 - страницы не загружаются. Точнее их не видно. Проверим.

Передай ещё вот такое:
```
||vungle.com^
```

**Comment by Alex-302** [comment]
в Edge можно попробовать отключить `TCP fast open`, или в расширенных настройках Адгарда заблокировать(через трей)

**Comment by vgavrish** [comment]
окей, передаю

**Comment by vgavrish** [comment]
@Alex-302 правило помогло в обоих случаях

**Comment by Alex-302** [comment]
ок, добавил.
А отключение TCP fast open испhавило проблему с браузером Edge?

**Comment by vgavrish** [comment]
да, исправило
