### ISSUE TITLE
com.cloudmagic.mail

### ISSUE THREAD

**Issue by oxavor** [AdguardTeam/AdguardFilters#3592]
**Description**: https://play.google.com/store/apps/details?id=com.cloudmagic.mail

**Current behaviour**: Ads asking for subscription in the menu and settings

Screenshot: 

<details>

![image](https://cloud.githubusercontent.com/assets/18646046/20709349/70c96d4a-b63d-11e6-9779-2edb1a7a5134.png)

</details>

**Adguard version**: 2.8.58

**Filters list**:  2, 3, 4, 14, 5, 15, 113, 211

**Operating system**: Android 6.0.1

Customer ID: 1063185

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
We can't remove element of the app.
