### ISSUE TITLE
http://fanserials.tv/?do=search&subaction=search&story= - annoying ads

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3593]
Пропущена реклама на странице:
http://fanserials.tv/?do=search&subaction=search&story=

При любом переходе на сайте приходится ждать 5 секунд, потом закрывать окно
с рекламой

<details>

![img_0070](https://cloud.githubusercontent.com/assets/23258533/20709489/6494a106-b63e-11e6-841c-28b42ae4e679.png)

![img_0069](https://cloud.githubusercontent.com/assets/23258533/20709469/4776e624-b63e-11e6-8ea0-ed09c3532051.png)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2016-11-23 13:56:52 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: D5DA0465-8C90-47F2-AC56-FF34D312FCD7

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.25 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.13 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.77 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.43.29 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.93 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.72 Enabled=YES

</details>

**Comment by Alex-302** [comment]
хмм, не повторилось, даже без Адгарда. Попроси юзера проверить на десктопе с иосным юзерагентом(можно с выключенным блокировщиком).

**Comment by Alex-302** [comment]
Если повторится, то надо будет удалённо глянуть.
