### ISSUE TITLE
Sports.ru app

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3596]
**Description**:
https://play.google.com/store/apps/details?id=ru.sports&hl=ru

Реклама в разделе Материалы - Футбол

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20711487/97371b48-b648-11e6-9c68-42c3b2498512.png)

</details>

**Adguard version**: 2.8

**Filters list**: 1,2,3,4,11,14
full, https
лог попросила если что

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
к сожалению, не убрать.
