### ISSUE TITLE
duolingo.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#35988]
`https://forum.duolingo.com/comment/27042002/Let-me-tell-you-something-about-pronunciation`

Annoyances: 

* Large bottom bar 
* Overlay when you scroll down

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.20.0
Firefox 67

**Comment by krystian3w** [comment]
Ad?

```
###vmgInterstitial
```

**Comment by krystian3w** [comment]
```
##body > #root > div > div > div > .GB_SB

##div.ReactModalPortal:nth-of-type(7)
```

**Comment by adranger** [comment]
@Alex-302  

[https://forum.duolingo.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://forum.duolingo.com/)

![duolingo](https://user-images.githubusercontent.com/35470489/65731866-d33d2d80-e09d-11e9-8e8b-3380135ca1af.png)

**Comment by krystian3w** [comment]
I see old filter break login, so this is enough `:has(img[src$="/images/duo_wave.svg"])`.

**Comment by Alex-302** [comment]
yes, added.
