### ISSUE TITLE
missing ad on exviuswiki.com

### ISSUE THREAD

**Issue by odudnyk** [AdguardTeam/AdguardFilters#3598]
On Android website exviuswiki.com is showing ad

Screenshots:
https://pp.vk.me/c638926/v638926269/e736/uZYsJgzvRAA.jpg
https://pp.vk.me/c638926/v638926269/e72c/w8dVGwUvlX0.jpg
</details>

**List of applied filters**:
English filter
Spyware filter
Social media filter
Annoyances filter
Russian filter
Experimental filter
Mobile ads
</details>

HTTPS filtration is on

**Adguard version**: 2.7.220

**Operating system**: Android 6.0.1

**Browser**: Google chrome

**Comment by Alex-302** [comment]
Is HTTPS filtering works on this site?
Show me certificate info(press on green lock->Details):
<details>

![screenshot_2016-11-29-19-42-38](https://cloud.githubusercontent.com/assets/8361299/20721787/bdfe05e2-b66c-11e6-95d9-eb0a86668efa.png)
![screenshot_2016-11-29-19-42-24](https://cloud.githubusercontent.com/assets/8361299/20721792/c1f7856a-b66c-11e6-944f-2cb8fff3ed6e.png)
</details>

**Comment by odudnyk** [comment]
Here you go.

https://pp.vk.me/c638926/v638926269/e847/Wlr_uBEbbyw.jpg

**Comment by Alex-302** [comment]
I see Comodo cert here.
Which HTTPS filtering mode - filter all except the whitelist or filter only blacklist?

**Comment by odudnyk** [comment]
Blacklist only

**Comment by Alex-302** [comment]
It is a reason. Invert it, or add this domain to black list.
