### ISSUE TITLE
m.fumanhua.net - banner

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#3602]
http://m.fumanhua.net/manhua/4720/571815.html - banner in the bottom 

NSFW
<details>

![screen shot 2016-11-30 at 20 04 59](https://cloud.githubusercontent.com/assets/23372054/20764872/c92a854a-b738-11e6-8ed6-0d53cfe09c1e.png)

</details>
<details>
Application version: 1.1.1.54
Platform: iOS
OS: 10.1.1

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.87 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.27 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.1 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.27 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.93.3 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.31 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.4 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.78 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.70.26 Enabled=YES
</details>
Customer ID 1457738

**Comment by Alex-302** [comment]
Fixed
