### ISSUE TITLE
sudomod.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#36037]
`https://sudomod.com/forum/index.php`

Overlay annoyance.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.20.0
Firefox 67

**Comment by adranger** [comment]
@okiehsch Please take a look at this.

![sudomod com](https://user-images.githubusercontent.com/35470489/61675154-8c157380-accd-11e9-9d2c-4e99de4fae37.png)

**Comment by okiehsch** [comment]
The message is not an anti-adblock message, I get the same message with uBO-disabled, so no filter will be added to uBO-annoyances.
![image](https://user-images.githubusercontent.com/16838044/61675302-107cec00-acf8-11e9-99e9-9e4761226a0b.png)

````
sudomod.com##.fade
sudomod.com##body:style(overflow: auto !important;)
````

**Comment by adranger** [comment]
I consider it an annoyance because it shows up if you open a forum thread from search engine results. They could limit that message to forum members only.

**Comment by Alex-302** [comment]
ok
