### ISSUE TITLE
mathebibel.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3605]
**Site**: http://www.mathebibel.de/ and sub pages like: http://www.mathebibel.de/potenzgesetze
**Description**: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20769740/73a6f77e-b743-11e6-9d49-bc51d5ce8c6e.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20769757/7fa2e8f8-b743-11e6-9d72-9b71085b3273.png)

**And sub pages like that:**

![image](https://cloud.githubusercontent.com/assets/10995998/20769676/33ec7c30-b743-11e6-8b3c-bd0709ad4f5d.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20769693/4450bc80-b743-11e6-9df2-59e4e7217753.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20769702/52a7ab4a-b743-11e6-8d70-1abb425340ff.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20769716/60459834-b743-11e6-887f-a3f541145bc9.png)

</details>

________________

**Adguard version**: 6.1.296.1549

**Filters list**: 
English filter 1.1.1.89
Spyware filter 1.0.9.27
Social media filter 1.0.15.3
Annoyances filter 1.0.7.28
German filter 1.0.28.91
Mobile ads filter 1.0.6.6
Safari filter 1.0.1.78

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to German filter
```
mathebibel.de##iframe[id^="ylt-"]
```
