### ISSUE TITLE
www.skidrowreloaded.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#36056]
Weird BLANK popup window when open any links on https://www.skidrowreloaded.com/
![scr-1561976545-001](https://user-images.githubusercontent.com/9846948/60429218-ebb2be80-9bfa-11e9-9908-cd0e9ccf018a.png)

SETUP
[20190701_122309_adg_settings_7.1.2817.0.zip](https://github.com/AdguardTeam/AdguardFilters/files/3345103/20190701_122309_adg_settings_7.1.2817.0.zip)

@Alex-302  @AdamWr

**Comment by FadeMind** [comment]
@bogachenko thanks a lot. Your fix WORKS AS EXPECTED 😍 

![scr-1562007749-001](https://user-images.githubusercontent.com/9846948/60460278-918a1b80-9c43-11e9-8cc2-2f37c9d528e0.png)

**Comment by BlazDT** [comment]
Also not reproduced.
