### ISSUE TITLE
mathematik-wissen.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3607]
**Site**: http://www.mathematik-wissen.de/
**Description**: Ad leftover

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20769863/f1a1c73a-b743-11e6-9b18-9fbc1674284a.png)

</details>

________________

**Adguard version**: 6.1.296.1549

**Filters list**: 
English filter 1.1.1.89
Spyware filter 1.0.9.27
Social media filter 1.0.15.3
Annoyances filter 1.0.7.28
German filter 1.0.28.91
Mobile ads filter 1.0.6.6
Safari filter 1.0.1.78

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to German filter
```
mathematik-wissen.de#$#body { margin-top: 0px!important; }
```
Added to Annoyances filter
```
mathematik-wissen.de###infobereich > div.info[-ext-has="h4:contains(Facebook)"]
```

**Comment by danidoedel** [comment]
@Alex-302 Thank you! But it's not fully fixed yet. There is some ad/ad leftover at the left side and some ad leftover at the right side:
![image](https://cloud.githubusercontent.com/assets/10995998/20847184/41704324-b8cd-11e6-9c0b-3520b80f8ce0.png)

**Comment by Alex-302** [comment]
1. Added to German filter
```
mathematik-wissen.de##a[href="http://fabalista.com/landingpage/"]
```
2. It is small, I don't use slow extended CSS rule here.
