### ISSUE TITLE
theverge.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#36082]
***Description***:
* **Current behaviour**: 

Goes into infinite reload loop.
<details><summary>Screen recording:</summary>

https://wetransfer.com/downloads/ba65fec55ce0bbdf701be3ab5144c2cf20190630112513/62e942

</details><br/>

* **Expected behaviour**: 

Should load just fine

***Steps to reproduce the problem***:

1. Enable Annoyances filter
2. Load the website
3. Bingo!

The issue seems to be caused by this specific rule: 
![Captura de Pantalla 2019-06-25 a la(s) 07 55 12](https://user-images.githubusercontent.com/33634917/60462345-b7b6b800-9c51-11e9-84c0-d92375a3dc44.png)

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | macOS Catalina public beta
Browser:                               | Chrome
AdGuard version:                       | 2.0.6 release
Filters enabled:                       | Base, [?], Annoyances
Helpdesk ID (if exists):               | 2237028

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by LucasDiTomase** [comment]
I spotted/reported this bug. I attach link to video of the bug: https://we.tl/t-i3P7mPXuJP%C2%A0
