### ISSUE TITLE
http://www.stern.de - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3609]
http://www.stern.de - missed ad

<details>

![img_0385](https://cloud.githubusercontent.com/assets/23258533/20774290/649700b0-b75e-11e6-99bf-c5d2d7e63c92.png)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2016-11-26 15:05:02 +0000

Device: iPad
Platform: iOS
OS: 10.1.1
ID: CD44D6DE-0A8C-4BDB-B48E-C34006D26D5C

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.66 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.19 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.94 Enabled=YES
ID=6 Name="German filter" Version=1.0.28.80 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.77 Enabled=YES
ID=101 Name="EasyList" Version=1.0.65.3 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.60.68 Enabled=YES

</details>

**Comment by Alex-302** [comment]
Fixed
