### ISSUE TITLE
net.bestmafia app is broken by high-quality filtering

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#3610]
Немного странная проблема. Стоит adguard 2.8 Android. Фильтры по умолчанию. Запускаю приложение https://play.google.com/store/apps/details?id=net.bestmafia&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dмафия+непобедима+гугл&pcampaignid=APPU_19_e1g_WJWcK4Wg6ASC1YTgCQ
При быстрой фильтрации все работает, при качественной загрузка долго идет и потом белый экран

**Comment by ministr91** [comment]
Приложение adguard как-то странно себя ведет, при запуске белый экран тоже

**Comment by ministr91** [comment]
Вот видео http://dropmefiles.com/FbxXf

**Comment by ministr91** [comment]
Вот лог
Фильтрация качественная. Начало 2:06.
 2:07 белый экран приложения.
 2:08 Фильтрация быстрая, удачный запуск

**Comment by ministr91** [comment]
Вот лог http://dropmefiles.com/8z8ES

**Comment by ministr91** [comment]
@nkartyshov

**Comment by ministr91** [comment]
@Alex-302
@ameshkov
Гляньте что там

**Comment by Alex-302** [comment]
Всё работает.

**Comment by ministr91** [comment]
Что именно? Я видео снял. ничего не работает. На видео видно, что при качесвтенном режиме фильтрации не работает приложение, а при быстром работает

**Comment by ministr91** [comment]
никто помогать не хочет (
@zebrum может вы сможете помочь?

**Comment by ameshkov** [comment]
@Alex-302 у тебя точно не повторяется с "качественной" фильтрацией? На видео проблема есть, скорее всего должно помочь отключение фильтрации для какого-то урла, только бы вычислить его.

@ministr91 а полный лог можете записать?

**Comment by ministr91** [comment]
@ameshkov так это и был полный лог, что не так сделал?

**Comment by Alex-302** [comment]
@ameshkov 
> у тебя точно не повторяется с "качественной" фильтрацией?

не повторяется.

@ministr91 мне только лог HTTP запросов нужен, или файл HAR.
Если отключить все фильтры проблема остаётся?

**Comment by ministr91** [comment]
Можете инструкцию кинуть как лог http или har записать? 
При отключении всех фильтров проблема остается

**Comment by zebrum** [comment]
@ministr91 
https://kb.adguard.com/index.php?/Russian/Knowledgebase/Article/View/66/0/kk-poluchit-fjjly-har-http-rkhiv-n-android-ustrojjstve

**Comment by ministr91** [comment]
Я не знаю что это за опция и как она влияет на приложение, но после включения этой опции у меня белого экрана больше нет, только долгая загрузка.

**Comment by ministr91** [comment]
Выключил опцию, включил качественный режим фильтрации и опять белый экран

**Comment by ministr91** [comment]
Я не знаю что это за опция и как она влияет на приложение, но после включения этой опции у меня белого экрана больше нет, только долгая загрузка.

**Comment by ministr91** [comment]
http://dropmefiles.com/eoO9f

**Comment by ministr91** [comment]
При упрощенной фильтрации белого экрана нет

**Comment by Alex-302** [comment]
На другой обменник залейте, с этого не загружается.

**Comment by ministr91** [comment]
Только что загрузил, проблем не было
http://my-files.ru/t9lrq5

**Comment by Alex-302** [comment]
Файл некорректный. Не редактировали его?

**Comment by ministr91** [comment]
нет

**Comment by ministr91** [comment]
Вот лог запросов. Сначала нормальный запуск, потом запуск с белым экраном. Далее хотел войти в эдгуард, но у меня он вылетел с ошибкой
http://my-files.ru/tsnnlz

**Comment by ministr91** [comment]
Вот новый лог с .хар. http://my-files.ru/henfjp
после включения этой опции у меня белого экрана больше нет, только долгая непрекращающаяся загрузка.

**Comment by ameshkov** [comment]
Попробуйте в белый список добавить:
```
mafia-rules.net
```

Помогает ли?

**Comment by ministr91** [comment]
Да. А в чем ошибка была? Можете ее как-нибудь системно исправить и обойтись без белого списка?

**Comment by ameshkov** [comment]
Да не особо, это именно фильтрацией надо обходить для этого конкретного приложения.

@Alex-302 вот как-то так:
```
@@||mafia-rules.net^$app=net.bestmafia
```

**Comment by Alex-302** [comment]
ок, добавил

**Comment by ministr91** [comment]
Оно уже вступило в силу? Должно работать? Или только с новой версией заработает?

**Comment by Alex-302** [comment]
Уже

**Comment by ministr91** [comment]
@Alex-302, открывай тему заново, не работает. Качественный режим фильтрации, фильтры обновлены. Захожу в игру и опять белый экран. Далее захожу в adguard , добавляю в белый список mafia-rules.net и приложение работает как надо

**Comment by ameshkov** [comment]
Может на сервере еще фильтры не обновились, завтра лучше проверь

**Comment by ameshkov** [comment]
А, блин

**Comment by ameshkov** [comment]
@Alex-302 вот такое правило должно быть, я затупил:
`@@||mafia-rules.net^$app=net.bestmafia,document`

**Comment by ministr91** [comment]
http://my-files.ru/sosawy

**Comment by ministr91** [comment]
А я уже видос запил с неработающим фильтром

**Comment by ministr91** [comment]
@Alex-302, изменения внесешь?

**Comment by ministr91** [comment]
Тоже самое, 1 в 1. При быстрой фильтрации все работает, при качественной нет. Вот видео. Идет оно долго, потому что у меня Adguard лагает. Почему лаги, не знаю. http://my-files.ru/ehmbai

**Comment by ministr91** [comment]
Хотел сделать логи серого экрана, но теперь даже до серого экрана не дошло. Бесконечная загрузка, потом сброс. Опять загрузка и сброс. 
3:08 - бесконечная загрузка, хотя около 3:00 все входило. http://my-files.ru/zxvyqr

**Comment by ministr91** [comment]
@Alex-302, @ameshkov

**Comment by Alex-302** [comment]
У меня с качественной фильтрацией и фильтрацией HTTPS игра запускается.

**Comment by ministr91** [comment]
@Alex-302, ты же видос видел? Это значит, что проблема есть. @ameshkov же выше еще писал. Что мне делать, чтобы устранить проблему? Почему у тебя работает, а у меня нет?

**Comment by ameshkov** [comment]
Вот это правило которое добавили в мобильный фильтр:
`@@||mafia-rules.net^$app=net.bestmafia,document`

Делает то же самое, что и добавление `mafia-rules.net` в белый список, так что я не очень понимаю в чем дело.

@ministr91  А если такое добавить в пользовательский?
`@@||mafia-rules.net^$app=net.bestmafia`

**Comment by ministr91** [comment]
@Alex-302, @ameshkov
1) Добавил mafia-rules.net в белый список, проблема осталась - серый экран появляется после авторизации.
2) Добавил @@||mafia-rules.net^$app=net.bestmafia в пользовательский, проблема осталась - серый экран появятся после авторизации.
3) Во время всех этих манипуляций, при выборе Adguard был белый экран, потом чёрный, потом жуткие лаги - выбрал опцию и спустя 5 секунд только программа среагировала. В конце концов программа вылетела с ошибкой. Можете глянуть что там? 21:15-21-25 http://my-files.ru/ndjcy1

**Comment by ameshkov** [comment]
Нужно полный лог записать, в этом ничего полезного

**Comment by ministr91** [comment]
@ameshkov, а что насчет проблемы с игрой?
Речь идет о логе вылета Adguard? Как записать полный? Имеется в виду har и лог веб запросов?

**Comment by ameshkov** [comment]
@ministr91 вот я про игру и говорю, непонятная фигня, то помогает белый список, то не помогает.

Лог веб-запросов нужен

**Comment by ministr91** [comment]
@ameshkov а что насчет вылетов приложения Adguard? Пишет, что приложение не отвечает и выбор "закрыть или подождать"? Тут какие логи нужны?

**Comment by ameshkov** [comment]
Да те же самые, должно хватить

**Comment by ministr91** [comment]
Логи начинаются от 3 часов ночи примерно. Записал на видео еще. На видео примерно с 5 минуты идут жуткие лаги Adguard, потом вылет с ошибкой. Видел записывал и логи с добавлением mafia-rules.net в белый список.  Разницы нет, в белом она или нет. В самом конце видео отключил защиту и игра запустилась, а до этого вечное подключение. 
http://my-files.ru/g4gvym

**Comment by ministr91** [comment]
@ameshkov, @Alex-302

**Comment by ameshkov** [comment]
А дай видео тоже посмотреть тоо

**Comment by ministr91** [comment]
@ameshkov  @Alex-302 так я же скинул, все в том файле находится, только что открыл его, видео есть.

**Comment by ameshkov** [comment]
@ministr91 блин, а логи не записал, ну что ты будешь делать :(

Похоже ты перепутал HAR-файл с логом самой программы, для отслеживания багов HAR-файл бесполезен.

Уровень логгирования другой нужен, у тебя сейчас дефолтный:
https://kb.adguard.com/ru/android/solving-problems/log

**Comment by ministr91** [comment]
@ameshkov вот, не могу я больше этот баг воспроизвести с вылетом, не всегда получается. Забудем на время про него. 
Что там с игрой? Как исправить?

**Comment by ameshkov** [comment]
Блин, я про игру, на вылет пофиг, это просто какое-то последствие

**Comment by ministr91** [comment]
http://my-files.ru/3tddrd
15:12-15:13 бесконечная загрузка
15:13 белый и черный экран Adguard, но вылета не было.
15:14 каким-то чудом смог зайти в игру

**Comment by ameshkov** [comment]
Вот такое еще правило надо попробовать в юзерфильтр докинуть (дополнительно к прошлому):
`@@||bestmafia.net^$app=net.bestmafia,document`

**Comment by ministr91** [comment]
@ameshkov было уже такое правило https://github.com/AdguardTeam/AdguardFilters/issues/3610#issuecomment-265187014

**Comment by ameshkov** [comment]
@ministr91 это другое, надо оба

**Comment by ministr91** [comment]
Не помогает, к тому же приложение Adguard вылетело с ошибкой. Можешь лог глянуть? Может что-то серьезное.

**Comment by ministr91** [comment]
http://my-files.ru/imgoix

**Comment by ameshkov** [comment]
@ministr91 а можешь на бета-версии проверить все же? Я смотрю у тебя логи с релиза.

**Comment by ministr91** [comment]
@ameshkov не могу, вдруг в бете будет еще больше ошибок, придется с беты опять на прошлую релизную переходить. Если проблема с вылетом Adguard не срочная, то я дождусь новой релизной версии и там уже проверю.

**Comment by ministr91** [comment]
Проблема с игрок не решена, после входа серый экран и ничего. После этого зашел в Adguard и все такие же лаги и несколько секунд нет реакции от Adguard. Я жму на настройки и ничего, потом жуткие лаги, белый экран и спустя какое-то время отвисает и опять все нормально. 
@ameshkov, @alex-302

**Comment by Alex-302** [comment]
Так определи, что ломает - фильтры или прога. Попробуй выключить фильтры и проверить. Не поможет - выключи фильтрацию приложения и т.д.
