### ISSUE TITLE
com.popularapp.thirtydayfitnesschallenge - ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3612]
**Description**: Реклама в разделах. Можно ее удалить?
https://play.google.com/store/apps/details?id=com.popularapp.thirtydayfitnesschallenge&hl=ru

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20785173/7c326d24-b7a7-11e6-8658-882b810e9b4e.png)

</details>

**Adguard version**: 2.8.53

**Filters list**: 2, 3, 4, 14, 1, 11 
full
https

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by odudnyk** [comment]
Sent his logs
Customer id 1143570

**Comment by vgavrish** [comment]
[debug (19).txt](https://github.com/AdguardTeam/AdguardFilters/files/626591/debug.19.txt)

> 15:57 до 16:00 зашёл в приложении запустил упражнения, дальше отключил упражнения вылезла реклама, и дальше я зашёл в адгуард и поставил уровень логировария по стандарту, надеюсь

**Comment by Alex-302** [comment]
Ёлки, опять полный прислали.
У меня не повторилось, пусть проверит
```
||setting.rayjump.com^
```

**Comment by vgavrish** [comment]
хм, странно, писала про хттп
отписала по правилу

**Comment by evgeniy-ADG** [comment]
Не помогло, попросил скинуть кеш и записать еще один именно хттп лог.

**Comment by Alex-302** [comment]
HAR бы ещё не помешал, с предварительной остановкой приложения и очисткой его кэша.

**Comment by vgavrish** [comment]
написала

**Comment by vgavrish** [comment]
хар - https://yadi.sk/i/byR4Ly_X32sHBZ
Вот примерно с 21:09 до 21:13, я нажал специально ещё на рекламу перешёл в
гугл плей закрыл

**Comment by Alex-302** [comment]
Доступа к файлу нет. Пусть на другой обменник зальёт.

**Comment by vgavrish** [comment]
[adguard.txt](https://github.com/AdguardTeam/AdguardFilters/files/659377/adguard.txt)
только я отключил https фильтрацию серавно она
не помогает, а сайты из за неё очень долго грузяться,вот даже фотки
прислал, что я ткнул на рекламу и перешёл в гугл плей: http://prntscr.com/dkuzr1

**Comment by Tetiana2020** [comment]
@Alex-302 , do we have any updates concerning this issue? The user is asking.

**Comment by Alex-302** [comment]
@Tetiana2020 HAR file is broken. I need a new file. Don't edit it.

**Comment by Tetiana2020** [comment]
@Alex-302 попросила залить на файлообменник.

**Comment by Tetiana2020** [comment]
@Alex-302 https://drive.google.com/drive/folders/0Bx2r2JOXGTP8V2luc2JPc19FdHM?usp=sharing

**Comment by Alex-302** [comment]
Почему-то битый HAR, не открывается.
Подозреваю, что заглушка встроена.

**Comment by Tetiana2020** [comment]
@Alex-302 что можно с этим сделать?

**Comment by Alex-302** [comment]
Всё же хотелось бы увидеть нормальный лог **HTTP** запросов
Возможно это имеет отношение к рекламе
```
||ad.period-calendar.com^
```

**Comment by evgeniy-ADG** [comment]
>здравствуйте,внёс правило (||ad.period-calendar.com^) не помогло. записал ещё раз лог с 13:27 по 13:29 снова ткнул на рекламу перешёл в гугл плей, и закрыл его.

[debug (7).txt](https://github.com/AdguardTeam/AdguardFilters/files/670931/debug.7.txt)

**Comment by Alex-302** [comment]
```
||graph.facebook.com^$app=com.popularapp.thirtydayfitnesschallenge
```
