### ISSUE TITLE
News Republic app ads 

### ISSUE THREAD

**Issue by oxavor** [AdguardTeam/AdguardFilters#3613]
**Description**: ads in News Republic app on Android 
(link:https://play.google.com/store/apps/details?id=com.mobilesrepublic.appy&hl=en)

Screenshot: 

<details>

![image](https://cloud.githubusercontent.com/assets/18646046/20791970/3b768a42-b7c8-11e6-9a8d-4a2e6b51c3c2.png)

</details>

**Adguard version**: 2.8.67

**Filters list**: 2, 3, 4, 14, 5, 15, 113, 211

**Operating system**: Android 6.0.1 

**HTTP log, time: 19:34** - 1063185

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня не повторяется. Передай эти правила на пробу:
```
||analytics.rayjump.com^
||ksmobile.net/news/report
||cm.gcm.ksmobile.com^
||startup.mobile.yandex.net/analytics/
||setting.rayjump.com/appwall/setting?app_id=
||setting.rayjump.com/setting?app_id=
```
это не реклама, аналитика, но возможно как-нибудь с рекламой связана.

Скрин твой?
