### ISSUE TITLE
kat.how - chain of redirects

### ISSUE THREAD

**Issue by oxavor** [AdguardTeam/AdguardFilters#3614]
**Description**: pop ups with dangerous web sites appear everytime you click anywhere on www.kat.how 

Screenshot: 

<details>

![unnamed](https://cloud.githubusercontent.com/assets/18646046/20792456/74e7247e-b7ca-11e6-96c6-8c5854725c1a.png)

</details>

**Adguard version**: 2.7.220 (repeated with 1.3.0 on mac)

**Filters list**: 2, 3, 14, 11, 211

**Operating system**: Android 6.0.1 (repeated on mac 10.11.6 too)

**Browser**: Chrome

**Customer ID:** 1335553

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
