### ISSUE TITLE
http://fxprosystems.com/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3615]
**Description**: На главной странице баннер

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20794146/663430da-b7d3-11e6-8091-303cb76be08c.png)

</details>

**Adguard version**: 6.1.296

**Filters list**: 1,2,3,4,14

**Operating system**: Вин

**Browser**: Хром

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
fxprosystems.com##.wpmui-popup.no-subtitle
```
