### ISSUE TITLE
retro-bit.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#36159]
`http://retro-bit.com/`

Newsletter overlay annoyance.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.20.0
Firefox 67

**Comment by THEtomaso** [comment]
Simply blocking it causes the page to freeze.
Unless someone can come up with a better solution than the one found in '**Fanboy's Annoyance List**':
https://github.com/ryanbr/fanboy-adblock/issues/1079/

**Comment by THEtomaso** [comment]
@tvinzz:
I don't see this doing anything:
`retro-bit.com#%#document.cookie = "empopup=null";`
At least not when using uBlock Origin.

**Comment by tvinzz** [comment]
@THEtomaso
retro-bit.com#$#body._has-modal { overflow: visible !important } - prevent scroll freezing

**Comment by THEtomaso** [comment]
Confirmed.
Good work! :)
