### ISSUE TITLE
pornhub doesn't play videos on android [NSFW]

### ISSUE THREAD

**Issue by oxavor** [AdguardTeam/AdguardFilters#3616]
**Description**: Video is disabled and only audio can be heard.

Screenshot: 

<details>

![screen shot 2016-12-01 at 2 55 39 pm](https://cloud.githubusercontent.com/assets/18646046/20794711/48e772b4-b7d6-11e6-9ed7-e8ebb3dc4172.png)

</details>

**Adguard version**: 2.8.67

**Filters list**: English, Spyware, Social Media, Annoynces, Modile Ads, Simplified domain names, Anti-Adblock Killer

**Operating system**: Android 

**Browser**: Chrome

**Customer ID**: 1454606

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
pornhub.com#@#div > [style*="width: 100%;"]:first-child
```
