### ISSUE TITLE
http://online.anidub.com/ - incorrect blocking

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#3617]
Browser Extension 

русский фильтр блокирует поле логин\пароль для входа на сайт справа вверху над главным меню сайта

**Current behaviour**: 

<details>

![2016-12-01 19 43 15](https://cloud.githubusercontent.com/assets/23637588/20803003/de477886-b7fe-11e6-8c28-4fe39fcc3087.png)

</details>

**Expected behaviour**: Tell us what should happen instead

<details>

![2016-12-01 19 16 18](https://cloud.githubusercontent.com/assets/23637588/20803054/020e5398-b7ff-11e6-8824-b8b5e1390ea7.png)

</details>

**Comment by Alex-302** [comment]
fixed
