### ISSUE TITLE
https://www.cnet.com/internet-speed-test/ - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3618]
https://www.cnet.com/internet-speed-test/ - missed ad

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/20813803/c0dd0b78-b81f-11e6-98f7-0281dd8ceaf2.JPG)

</details>

<details>

Application version: 1.1.2.24
Application lifetime: 2016-11-11 15:12:05 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.2
ID: 4EF78E09-4E19-4624-B73F-05839E28D987

Locale: en
Region: iq

Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.50 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.17 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.90 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.77 Enabled=YES

</details>

**Comment by Alex-302** [comment]
Fixed
