### ISSUE TITLE
http://mobilesyrup.com/ - Incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3620]
Incorrect blocking on page:
http://mobilesyrup.com/

<details>

![image1 2](https://cloud.githubusercontent.com/assets/23258533/20814054/cdc04782-b820-11e6-8d12-33284a2760a5.png)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2015-10-23 19:40:41 +000
Device: iPhone
Platform: iOS
OS: 10.1.1
ID: 1159ED3C-6BFE-417F-AB08-8543A97C33CD
Locale: en
Region: ca
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.0.30 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.94 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.43 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.6.36 Enabled=YES
ID=10 Name="Filter for useful ads" Version=1.0.0.89 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.68 Enabled=YES
ID=11 Name="Mobile ads filter" Version=1.0.1.53 Enabled=YES

</details>

**Comment by Alex-302** [comment]
@osavranska 
Screenshot is wrong. Reupload, please.
