### ISSUE TITLE
http://www.quankan.tv/ - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3622]
http://www.quankan.tv/ - missed ad

<details>

![img_0214](https://cloud.githubusercontent.com/assets/23258533/20814275/ad774aba-b821-11e6-9acd-f23e5d1e4bd3.png)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2016-12-01 09:02:26 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: 5297079D-B8A3-446E-8910-C170F35B48D5

Locale: zh
Region: cn

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.91 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.9.27 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.15.4 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.7.29 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.6.6 Enabled=NO
ID=12 Name="Safari filter" Version=1.0.1.78 Enabled=NO
ID=101 Name="EasyList" Version=1.0.65.11 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.69.99 Enabled=NO
ID=122 Name="Fanboy's Annoyances" Version=1.0.65.31 Enabled=NO
ID=104 Name="EasyList China" Version=1.0.70.31 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.70.13 Enabled=NO
ID=220 Name="CJX's Annoyance List" Version=1.0.0.78 Enabled=YES

</details>

**Comment by Alex-302** [comment]
Not reproduced.
