### ISSUE TITLE
kuban24.tv missed ads

### ISSUE THREAD

**Issue by odudnyk** [AdguardTeam/AdguardFilters#3624]
**Ads showing up on kuban 24**:

Problem is present on Mac and Android (possibly iOS and Windows, didn't check yet)

<details>
http://prnt.sc/de8jyd

http://prntscr.com/de8ltk
</details>

**Adguard version**: 1.3.0/2.7.220

**Filters list**: http://prntscr.com/de8mtz

**Operating system**: Mac/Anrdoid

**Browser**: Chrome

**Comment by Alex-302** [comment]
Fixed
https://github.com/AdguardTeam/AdguardFilters/issues/3626
