### ISSUE TITLE
[Android] Twitter sponsored ads not filtered

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardFilters#3625]
![tmp_22149-screenshot_20161202-050217-1780612151](https://cloud.githubusercontent.com/assets/3318223/20822684/1c172dac-b84d-11e6-883d-4a1f06a1df29.png)

<details>
-

[![s](http://valid.x86.fr/cache/banner/a1xkj3.png)](http://valid.x86.fr/a1xkj3)

[Settings & Filterlists](http://www.youtube.com/watch?feature=player_embedded&v=-ITaEru6WtI)

Software | Channel | Version
--- | --- | ---
[Android](https://www.android.com/) | Stock | 6.0.1 (SDK 23) ARMv7
[SuperSU Pro](http://www.supersu.com) | Stable | 2.78
[AdGuard](https://adguard.com/) | Beta | 2.8.58
[AdAway](https://adaway.org/) | Stable | 3.2
[Adblock Plus](https://adblockplus.org/android-about) | Stable | 1.1.3
[Chrome](https://www.google.com/chrome/) | Dev | 56.0.2919.3
[Opera Mini](http://www.opera.com/) | Beta | 21.0.2254.110494
[Firefox](https://www.mozilla.org/en-US/firefox/products/) | Aurora | 52.0a2

Last updated: `11/30/2016`
</details>

**Comment by Alex-302** [comment]
Where is sponsored ads? Is it an app or a site?

**Comment by Bluscream** [comment]
Where it says "Gesponsert". I mean the sponsored tweet which are ads IMO

**Comment by Alex-302** [comment]
> Is it an app or a site?

**Comment by Bluscream** [comment]
It's the official Twitter app > com.twitter.android

**Comment by Alex-302** [comment]
It is impossible to filter twitter(and twitter, for example) app traffic, because ssl pinning.

**Comment by Bluscream** [comment]
That would mean every website/app could make filtering impossible...

**Comment by Alex-302** [comment]
Only apps.
You can ask in Android section.
