### ISSUE TITLE
Spyware filter blocks "install now" buttons in Safari extensions store

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#3627]
they just disappear if Spyware filter is on:

![image](https://cloud.githubusercontent.com/assets/17472907/20840553/ab51acd0-b8c1-11e6-87c5-ab909bac274c.png)

![image](https://cloud.githubusercontent.com/assets/17472907/20840563/b1aca24c-b8c1-11e6-82cf-c774a262084b.png)

**Comment by vozersky** [comment]
they just disappear

**Comment by Alex-302** [comment]
Not reproduced.
