### ISSUE TITLE
focus.de - Missed social media buttons

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3628]
**Description**: Missed social media buttons on the webpage (on iOS):
http://m.focus.de/digital/videos/nach-spott-und-verzoegerung-kommen-sie-ueberhaupt-noch-tim-cook-macht-andeutung-zu-airpod-ohrhoerern_id_6282751.html

Screenshot: 
<details>

![image1](https://cloud.githubusercontent.com/assets/17504743/20842837/981e4be6-b8c1-11e6-8045-0b3eeafe98b6.PNG)

</details>

**Adguard version**: 1.1.2.24

**Filters list**:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.99 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.30 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.8 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.35 Enabled=YES
ID=6 Name="German filter" Version=1.0.28.94 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.7 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.79 Enabled=YES

**Operating system**: iOS 10.2

Customer ID: 1458691

**Comment by Alex-302** [comment]
Added to Social filter
```
m.focus.de##.social_sticky
```
