### ISSUE TITLE
support.ubi.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3629]
**Site**: https://support.ubi.com/de-de/
**Description**: Cookie notice.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20854849/8f038270-b8f7-11e6-8141-34424aa24f84.png)

</details>

________________

**Adguard version**: 6.1.298.1564

**Filters list**: 
English filter 1.1.2.9
Spyware filter 1.0.9.35
Social media filter 1.0.15.11
Annoyances filter 1.0.7.40
German filter 1.0.28.97
Mobile ads filter 1.0.6.9
Safari filter 1.0.1.80

**Operating system**: Windows 10 x64

**Browser**: Chrome

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
support.ubi.com##.message--cookie
```
