### ISSUE TITLE
m.toysrus.com- incorrect blocking

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#3630]
https://m.toysrus.com/brsearch#brm-search?facet.range=price%3A%5B100%20TO%20*%5D&facet.range=price%3A%5B75%20TO%20100%5D&facet.range=price%3A%5B50%20TO%2075%5D&facet.range=price%3A%5B40%20TO%2050%5D&facet.range=price%3A%5B30%20TO%20 - no access with Adguard enabled
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/20855158/fb2f9078-b902-11e6-8bed-67103776694f.png)

</details>

looks this way with Adguard disabled
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/20855236/f9198554-b903-11e6-9bea-a3965cbad5df.png)

</details>

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.35 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.16 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.98 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.6.97 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.94 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.75 Enabled=YES

Customer ID: 1451583

**Comment by Alex-302** [comment]
It does not work on my end without Adguard
<details>

![image](http://imagizer.imageshack.com/img924/6514/NeO8Ay.png)
</details>
