### ISSUE TITLE
Adblock detection | Aternos.org

### ISSUE THREAD

**Issue by RefexHD** [AdguardTeam/AdguardFilters#36313]
***Description***:
Adblock detection on aternos.org --
I made a fix for it: https://pastebin.com/rxz21N4U
* **Current behaviour**: 
Detects the filter

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste an image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Yt8pEJ5.png)
</details><br/>

* **Expected behaviour**: 
Shouldn't detect the filter
* **With the fix**(The header can't be removed since its an detector): 

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/uM1IenJ.png)
</details><br/>

***Steps to reproduce the problem***:
Go to aternos.org,
Click on play,
Login with an Account,
After logging in,
Then a screen comes that you should disable your adblocker.

[//]: # (Substitute this line with step-by-step instruction on how to reproduce the issue)

***System configuration***

**Filters:**
Adguard Base List

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 Home
Browser:                               | Firefox
AdGuard version:                       | 3.2.1
Filters enabled:                       | Adguard Base List

**Comment by Alex-302** [comment]
Please enable Annoyances filter.

**Comment by RefexHD** [comment]
Doesn't help it will still show it with this filter enabled.

**Comment by Alex-302** [comment]
Ok, reproduced. Fixed.
Please update filters after 1-2 hours.
