### ISSUE TITLE
blackberry launcher app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3632]
https://play.google.com/store/apps/details?id=com.blackberry.blackberrylauncher

It's blocked at my end wit the HTTPS filtering, but the customer still can see it. Screen and HAR:

![screenshot_20161125-142113](https://cloud.githubusercontent.com/assets/15856304/20857380/f98b6e9c-b932-11e6-9d70-1f7d28ecf0f1.png)
[state (15).txt](https://github.com/AdguardTeam/AdguardFilters/files/628727/state.15.txt)

[hars.zip](https://github.com/AdguardTeam/AdguardFilters/files/628726/hars.zip)

>The .har files are attached in a zip file. There are four files because I
enabled har logging, then turned off AdGuard protection, and turned on
AdGuard protection again before clearing the Launcher app cache and data
again -- and then I restarted the phone at about 9:57 am. (I've attached a
screenshot of the ad that appeared after restart.) After restarting the
phone, the banner ad appears in the Launcher app drawer.
Overall, the ads appeared upon installation of the Launcher app. In other
words, AdGuard has never blocked the BlackBerry Launcher app ads. After
clearing the Launcher cache and data, the ads appear immediately after
restarting the phone.

**Comment by Alex-302** [comment]
Reproduced only without AG(with/without HTTPS filtering). If that ads was loaded, they can be removed when you stop this app in device settings and start it again.
All requests to ad network in the log are blocked.
Let me know about result.
