### ISSUE TITLE
m.gutenberg.org - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3633]
I used the app "QR reader" and accessed the project Gutenberg.org mobile site where I saw an ad for "jackpot city slots". I almost didn't get a screenshot of it, but I did. It was at 11:10pm

I believe the offending domain is "adztec.com"

![image1](https://cloud.githubusercontent.com/assets/15856304/20857513/142e38d8-b938-11e6-8540-34a6b399565f.png)

logs: 1436166

**Comment by Alex-302** [comment]
@evgeniy-ADG are you sure that is Safari?

**Comment by rhett121** [comment]
It was inside the app "QR Reader". It was the internal browser used inside the app, not sure what it uses.

**Comment by Alex-302** [comment]
Not reproduced.
