### ISSUE TITLE
Sky Force Reloaded app

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3634]
1458468
**Description**: Баннер от Sky Force. Можно его убрать?
https://play.google.com/store/apps/details?id=pl.idreams.SkyForceReloaded2016&hl=ru

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20858413/56a87d30-b94d-11e6-886d-d7efe8747ad2.png)

</details>

**androidVersion** : 7.0

**Adguard version**: 2.8.67

**Filters list**: 2, 3, 4, 14, 1, 11, 15
  "filteringQuality" : "FULL",
 HTTPS

**Лог** 
[debug (6).txt](https://github.com/AdguardTeam/AdguardFilters/files/628786/debug.6.txt)
время появления в 16.03

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Ads are not shown on my end.
Please check this rule:
```
||server.idreams.pl/news/ads_sfr_*.json
```

**Comment by vgavrish** [comment]
отписала

**Comment by vgavrish** [comment]
> Индивидуальное правило работает отлично.
Большое Вам спасибо!

**Comment by Alex-302** [comment]
Добавил.
