### ISSUE TITLE
www.wiwo.de - adblocking detected 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#3636]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://www.wiwo.de/impressum/nutzungshinweise/blocker/?callback=%2Fmanipulationen-des-goldpreises-deutsche-bank-willigt-in-strafe-ein%2F14928780.html

* **Current behaviour**: adblocking is detected 

<details>

![image](https://cloud.githubusercontent.com/assets/23372054/20861344/76e7931c-b996-11e6-9e35-1130b3e34917.png)

</details>

***System configuration***

Operating system: iOS
Adguard version: 1.1.2.24
Adguard filters: 
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.14 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.36 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.12 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.40 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=NO
ID=6 Name="German filter" Version=1.0.28.97 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.80 Enabled=YES

Ticket ID: 1459423

**Comment by Alex-302** [comment]
Added to German filter
```
@@||wiwo.de/js/*/iqadcontroller.js
wiwo.de##.hcf-ad-superbanner
```
Added to Social filter
```
wiwo.de##.hcf-action-share
```
