### ISSUE TITLE
hosgeldi.com - missed ad

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#3637]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://hosgeldi.com/heb/?d=17090&r=6&utm_source=newsletters&utm_medium=email&utm_campaign=email&code=359446
* **Current behaviour**: missed ad

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/20861907/1ea708ae-b9a5-11e6-88e4-b0ef0c7c6717.png)

</details>

Application version: 1.1.1.54
Device: iPhone
OS: 10.1.1

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.88.18 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.52 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.61 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.35.98 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.77 Enabled=YES

Ticket ID: 1459522

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||hosgeldi.com/js/
```
