### ISSUE TITLE
http://freescreens.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3641]
Пропущена реклама на сайте http://freescreens.ru/348/424815/
Скриншот: http://f6.s.qip.ru/OgbqitwM.png

Мои параметры:
* Win x64
* adguard в виде расширения у Chrome
* фильтры: русский, английский, RU AdList
* Dr.Web

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||ibishic.ru^$third-party
freescreens.ru##noindex > a > img
```
