### ISSUE TITLE
https://www.yandex.ru/ - incorrect blocking 

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3643]
https://www.yandex.ru/ - incorrect blocking 

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/20875890/e9fbce28-bac6-11e6-9b87-7da00abc23e9.png)

</details>

<details>

Application version: 1.1.2.24
Application lifetime: 2016-12-03 22:12:54 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: E1004C52-C954-410A-9B93-6E0ABE1C1595

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.18 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.36 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.13 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.43.80 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.80 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.70.29 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.70.30 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.67.15 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.66.85 Enabled=YES

</details>

Ticket ID: 1459584

**Comment by Alex-302** [comment]
Ёлки, ну по-русски ж уже написал, добавляйте описание, хотя бы для ложных
![image](http://imagizer.imageshack.com/img921/9465/lH7lOR.png)

**Comment by dzamyshlyayeva** [comment]
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/20889765/ee2e0998-bb0c-11e6-81da-e55e7c7313c5.png)

</details>

белое поле вместо баннера

**Comment by Alex-302** [comment]
Странно. У меня скрыто.
В пользовательском фильтре нужно проверить:
```
yandex.by,yandex.ru,yandex.ua##.body__topblocks
```
если не поможет, надо проверить, работает ли сокрытие элементов
```
yandex.by,yandex.ru,yandex.ua##body
```
это правило должно скрыть всю страницу. Если не скроет, надо будет дальit смотреть, а правило - удалить.
