### ISSUE TITLE
http://vlinderscrime.nl/ - Incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3644]
Incorrect blocking on page: http://vlinderscrime.nl/

Ads are not blocked when page loads for first time. When I press refresh button and page reloads, upper adds are perfectly blocked.

<details>

![image](https://cloud.githubusercontent.com/assets/23258533/20878064/4a6ecb58-bad5-11e6-894a-99d3a04ca27f.png)

![image](https://cloud.githubusercontent.com/assets/23258533/20878083/5f0dfbf6-bad5-11e6-84d7-d4dab7279ecf.png)

</details>

</details>

<details>

Application version: 1.1.1.54

Application lifetime: 2015-11-21 22:24:33 +0000

Device: iPhone

Platform: iOS

OS: 10.1

ID: 9002691F-E094-493E-94ED-B3AEB43CDE4B

Locale: nl

Region: nl

Optimazed enabled: NO

Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.1.2.32 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.9.36 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.15.13 Enabled=YES

ID=14 Name="Annoyances filter" Version=1.0.7.41 Enabled=YES

ID=8 Name="Dutch filter" Version=1.0.9.10 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.1.80 Enabled=YES

ID=106 Name="EasyList Dutch" Version=1.0.70.43 Enabled=YES

ID=207 Name="Adblock Warning Removal List" Version=1.0.70.36 Enabled=YES

ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES

</details>

Ticket ID: 1138658

**Comment by Alex-302** [comment]
It is a bug with the first visiting.

Added to Dutch filter
```
vlinderscrime.nl##a[href="http://www.fashioncarmen.nl"]
vlinderscrime.nl##.a-single > a[class="gofollow"] > img

```

**Comment by osavranska** [comment]
Github says problem solved. But I update the filter and still see the adds.... and don't see them when I refresh the page. (Just like original situation). I think I see what you have changed. However, your solution is only for one add. There are 7/8 more that needs to be blocked. 

Missed ad on page: http://vlinderscrime.nl/
Several ads are not blocked. Top and bottom.

<details>

![slack_for_ios_upload_160-3](https://cloud.githubusercontent.com/assets/23258533/20914256/132cef46-bb87-11e6-8ad6-b613f56459e7.jpg)

![slack_for_ios_upload_160](https://cloud.githubusercontent.com/assets/23258533/20914260/1881bad0-bb87-11e6-8d68-b1dd88b8fbb7.jpg)

![slack_for_ios_upload_160-1](https://cloud.githubusercontent.com/assets/23258533/20914262/1c5900f0-bb87-11e6-8585-73957a4818e0.jpg)

![slack_for_ios_upload_160-2](https://cloud.githubusercontent.com/assets/23258533/20914263/1fe771de-bb87-11e6-9829-f72ebfc28b02.jpg)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2015-11-21 22:24:33 +0000
Device: iPhone
Platform: iOS
OS: 10.1
ID: 9002691F-E094-493E-94ED-B3AEB43CDE4B
Locale: nl
Region: nl
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.35 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.36 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.15 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.42 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.9.11 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.80 Enabled=YES
ID=106 Name="EasyList Dutch" Version=1.0.70.47 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.70.40 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES

</details>

Ticket ID: 1138658

**Comment by Alex-302** [comment]
All these ads are  blocked on my end.
Could you check it on mobile device?
I see only ad leftover at the top
added
```
vlinderscrime.nl###top-banner
```
