### ISSUE TITLE
mx player ad still exists

### ISSUE THREAD

**Issue by myungou** [AdguardTeam/AdguardFilters#36447]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>
![Screenshot_20190708-225651_MX Player](https://user-images.githubusercontent.com/52665560/60816022-c06c3880-a1d3-11e9-8241-bdc00cec4648.jpg)
![Screenshot_20190708-225633_MX Player](https://user-images.githubusercontent.com/52665560/60816046-c95d0a00-a1d3-11e9-9928-45dc7bc1dfb2.jpg)
![Screenshot_20190708-225626_MX Player](https://user-images.githubusercontent.com/52665560/60816070-d2e67200-a1d3-11e9-888f-d7e6bf37102e.jpg)

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android) | 9
Browser:                               | Mx player(application)
AdGuard version:                       | latest
Filters enabled:                       | on
AdGuard mode (Android only):           | VPN 
Filtering quality (Android only):      | High-quality 
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | Default
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Filters list and screenshot, please.

**Comment by krystian3w** [comment]
![Screenshot_20190708-225651_MX Player](https://user-images.githubusercontent.com/52665560/60816022-c06c3880-a1d3-11e9-8241-bdc00cec4648.jpg) 

![Screenshot_20190708-225633_MX Player](https://user-images.githubusercontent.com/52665560/60816046-c95d0a00-a1d3-11e9-9928-45dc7bc1dfb2.jpg)

 ![Screenshot_20190708-225626_MX Player](https://user-images.githubusercontent.com/52665560/60816070-d2e67200-a1d3-11e9-888f-d7e6bf37102e.jpg)

**Comment by krystian3w** [comment]
> Filters list and screenshot, please.

Lists I cannot found without crystal ball... 🔮.

![Screenshot_20190708-225651_MX Player](https://user-images.githubusercontent.com/52665560/60816022-c06c3880-a1d3-11e9-8241-bdc00cec4648.jpg) |
---|
![Screenshot_20190708-225633_MX Player](https://user-images.githubusercontent.com/52665560/60816046-c95d0a00-a1d3-11e9-9928-45dc7bc1dfb2.jpg) |
 ![Screenshot_20190708-225626_MX Player](https://user-images.githubusercontent.com/52665560/60816070-d2e67200-a1d3-11e9-888f-d7e6bf37102e.jpg) |

**Comment by myungou** [comment]
AdGuard Base filter  
2.0.61.52 updated 2019. 7. 9. 오전 1:30:45  
AdGuard Mobile Ads filter  
2.0.6.65 updated 2019. 7. 9. 오전 1:30:11  
EasyList  
2.0.34.84 updated 2019. 7. 9. 오전 12:00:16  
Peter Lowe's list  
2.0.2.84 updated 2019. 7. 8. 오후 6:00:51
AdGuard Tracking Protection filter  
2.0.7.74 updated 2019. 7. 8. 오후 10:30:51
AdGuard Social Media filter  
2.0.12.99 updated 2019. 7. 9. 오전 1:30:51  
Fanboy's Social Blocking List  
2.0.34.81 updated 2019. 7. 9. 오전 12:00:44
Malware Domains  
2.0.43.52 updated 2019. 7. 9. 오전 12:00:56  
Spam404  
2.0.1.33 updated 2019. 7. 3. 오전 6:00:59  
NoCoin Filter List  
1.0.1.80 updated 2019. 6. 30. 오후 12:01:38
AdGuard Annoyances filter  
2.0.23.31 updated 2019. 7. 9. 오전 1:30:21  
Web Annoyances Ultralist  
1.0.0.42 updated 2019. 7. 9. 오전 12:00:49  
Fanboy's Annoyances  
2.0.34.83 updated 2019. 7. 9. 오전 12:00:42  
Adblock Warning Removal List  
2.0.43.51 updated 2019. 7. 9. 오전 12:00:55  
(Obsolete) Anti-Adblock Killer | Reek  
1.0.1.69 updated 2017. 12. 4. 오후 8:19:37
AdGuard Russian filter  
2.0.16.90 updated 2019. 7. 9. 오전 1:30:29  
AdGuard Turkish filter  
2.0.7.15 updated 2019. 7. 9. 오전 1:30:16  
AdGuard French filter  
2.0.15.82 updated 2019. 7. 8. 오후 1:30:21  
AdGuard German filter  
2.0.7.32 updated 2019. 7. 8. 오후 11:31:02  
AdGuard Japanese filter  
2.0.1.98 updated 2019. 7. 6. 오전 3:31:10  
AdGuard Spanish/Portuguese filter  
2.0.4.13 updated 2019. 7. 8. 오후 11:31:08  
EasyList Czech and Slovak  
2.0.1.29 updated 2019. 7. 5. 오후 6:00:21  
EasyList Lithuania  
2.0.1.15 updated 2019. 7. 6. 오전 12:00:23  
EasyList China  
2.0.43.52 updated 2019. 7. 9. 오전 12:00:21
Liste AR  
2.0.43.51 updated 2019. 7. 9. 오전 12:00:26  
Bulgarian list  
2.0.0.24 updated 2019. 3. 19. 오전 12:00:17  
Official Polish filters for AdBlock, uBlock Origin & AdGuard  
2.0.8.10 updated 2019. 7. 8. 오전 6:01:04  
EasyList Hebrew  
2.0.1.94 updated 2019. 7. 8. 오전 6:00:22  
Frellwit's Swedish Filter  
2.0.5.18 updated 2019. 7. 8. 오후 9:01:36  
Adblock List for Finland  
2.0.1.37 updated 2019. 7. 8. 오전 3:01:27  
List-KR  
2.0.1.61 updated 2019. 7. 8. 오후 6:01:16  
EasyList Italy  
2.0.43.51 updated 2019. 7. 9. 오전 12:00:25  
ABPindo  
2.0.1.89 updated 2019. 7. 3. 오후 9:00:20
Latvian List  
2.0.0.35 updated 2019. 3. 5. 오후 6:00:34  
Icelandic ABP List  
2.0.0.1 updated 2017. 12. 4. 오후 8:19:37  
Dandelion Sprout's Nordic Filters  
2.0.1.99 updated 2019. 7. 1. 오전 3:02:14  
YousList  
2.0.3.82 updated 2019. 7. 8. 오후 12:01:33  
xinggsf  
2.0.0.78 updated 2019. 6. 12. 오전 12:01:42  
Korean Adblock List  
2.0.0.26 updated 2019. 3. 1. 오전 3:21:04  
ABP Japanese Filters  
2.0.0.82 updated 2019. 7. 8. 오전 12:00:45

pref.proxy.block.ipv6  | On

**Comment by myungou** [comment]
Sorry... I'm not used to using Github.

**Comment by myungou** [comment]
I added some of missing info of my phone and other setting(Adguard) sry..😓

**Comment by Alex-302** [comment]
Better sent new report from AdGuard, I need to see your config
`Support` -> `Send feedback` -> `Missed ad`
It's simple. Just add screenshot. All fields will be filled automatically.

**Comment by Alex-302** [comment]
and post report link here

**Comment by krystian3w** [comment]
Player nod give http link.

**Comment by myungou** [comment]
I stucked. Because u guys need a URL but this is an application.. so i can't proceed the report progress (STEP 3/8). I don't know about MX Player's URL.
so Alex-302 could u show me how to get URL of application? im not familiar with it...😭

btw I am lifetime user. krystian3w.😓

**Comment by myungou** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/36539

**Comment by myungou** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/36540

**Comment by myungou** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/36544

filtering logs screenshot

**Comment by Alex-302** [comment]
> I stucked. Because u guys need a URL but this is an application.. so i can't proceed the report progress (STEP 3/8). I don't know about MX Player's URL.
> so Alex-302 could u show me how to get URL of application? im not familiar with it...
> 
> btw I am lifetime user. krystian3w.

Hi. That domains must be blocked by DNS.

At step 3 enter just URL of this issue:)
https://github.com/AdguardTeam/AdguardFilters/issues/36447
