### ISSUE TITLE
Netflix Windows 10 app doesn't work with the Stealt mode

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3645]
Hi, I'm having problem with the Netflix app for windows 10 (not the
browser netflix page that works pretty well with adguard). The app
doesn't load if Adguard stelth mode is on. How can I white list the
Netflix app

The option “Hide your User-Agent” causes the problem.

1152599

**Comment by Alex-302** [comment]
@seanl-adg we should exclude some URL with `$stealth` modifier
