### ISSUE TITLE
nytimes.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#36458]
***Description***:
* **Current behaviour**: 

Broken by an unspecified Base filter rule. Seems like AdGuard removes some additional news categories

<details><summary>Screenshot:</summary>

https://i.imgur.com/v3rRPpL.jpg
</details><br/>

* **Expected behaviour**: 

SHould have all news categories available.

<details><summary>Screenshot:</summary>

https://i.imgur.com/xJ2qa42.jpg
</details><br/>

***Steps to reproduce the problem***:

1. Only have Base filter enabled
2. Visit nytimes.com

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | iOS
Operating system version (Android/iOS) | unspecified
Browser:                               | Safari
AdGuard version:                       | Pro 2.1
Filters enabled:                       | Base
Simplified filters (iOS only)          | unspecified
Helpdesk ID (if exists):               | 1746513

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Reproduced on Windows, but I wasn't able to reproduce it on iOS.
Fixed.
