### ISSUE TITLE
http://www.worldsnooker.com/ - incorrect blocking 

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3646]
Некорректная блокировка на странице: http://www.worldsnooker.com/
Не работает кнопка меню в правом верхнем углу.

<details>

![image](https://cloud.githubusercontent.com/assets/23258533/20879123/e6828c3c-bada-11e6-8730-1a3928c015ca.png)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2015-11-25 19:01:14 +0000

Device: iPad
Platform: iOS
OS: 10.1.1
ID: 32D5BC3C-86D6-4B81-9D9B-236B967A48A2

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.71.65 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.9.12 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.7.51 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.5.41 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.43.21 Enabled=YES
ID=6 Name="German filter" Version=1.0.25.40 Enabled=NO
ID=8 Name="Dutch filter" Version=1.0.8.74 Enabled=NO
ID=5 Name="Experimental filter" Version=1.0.26.31 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.88 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.79 Enabled=YES
ID=101 Name="EasyList" Version=1.0.65.5 Enabled=YES
ID=106 Name="EasyList Dutch" Version=1.0.58.30 Enabled=NO
ID=107 Name="EasyList Germany" Version=1.0.58.41 Enabled=NO
ID=115 Name="RU AdList" Version=1.0.69.96 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.69.83 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.65.25 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.60.27 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.58 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.69.97 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.61.19 Enabled=NO
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.50 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.57.89 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.66.82 Enabled=YES
ID=225 Name="Fanboy Anti-Facebook List" Version=1.0.0.7 Enabled=YES

</details>

Ticket ID: 1142623

**Comment by Alex-302** [comment]
Added to English filter
```
@@||adtech.de/dt/common/DAC.js$domain=worldsnooker.com
```
