### ISSUE TITLE
http://onelike.tv/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3648]
http://onelike.tv/sts-love.html

![image](https://cloud.githubusercontent.com/assets/15856304/20882105/054d243a-bae8-11e6-96d0-919e30f95af9.png)

English filterVersion 1.1.2.33. Updated 5 december 2016 at 11:00.
Russian filterVersion 1.0.43.81. Updated 4 december 2016 at 14:00.

**Comment by Alex-302** [comment]
![image](http://imagizer.imageshack.com/img921/7383/QEvpT5.png)
