### ISSUE TITLE
https://muzofond.com/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3649]
https://muzofond.com/search/%D0%BD%D0%B5%20%D0%BE%D1%82%D0%BF%D1%83%D1%89%D1%83%202016

![image](https://cloud.githubusercontent.com/assets/15856304/20882354/3602cf70-bae9-11e6-820f-2b2f6c194062.png)

English filterVersion 1.1.2.33. Updated 5 december 2016 at 11:00.
Spyware filterVersion 1.0.7.74. Updated 21 september 2016 at 17:00.
Social media filterVersion 1.0.12.82. Updated 21 september 2016 at 23:00.
Annoyances filterVersion 1.0.7.41. Updated 3 december 2016 at 20:01.
Russian filterVersion 1.0.43.81. Updated 4 december 2016 at 14:00.

Расширение, Хром, Мак.

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||muzofond.com/mithdl.js
```

**Comment by KozelElena** [comment]
We have an issue regarding this website (Vulkan ads on the background)
Using the extension only 
I was able to reproduce

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24330669/acf5ca66-122c-11e7-9703-d861d1b501ff.png)

![image](https://cloud.githubusercontent.com/assets/17320558/24330675/b7f06b74-122c-11e7-9b6d-d2bcea011e84.png)

</details>

Ticket ID: 1516094

**Comment by Alex-302** [comment]
Fixed
