### ISSUE TITLE
http://izzylaif.com/ - Anti Adblock Script

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3650]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Отключите Адблок
http://izzylaif.com/ru/enter-unlock-password-key/

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/20884724/b0814784-baf5-11e6-9d75-0bb7e77c1541.png)

</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

***System configuration***

Information | value
--- | ---
Operating system: | Вин
Browser: | Хром
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Simplified filters(iOS) |  Off
Adguard DNS: | None 
Adguard filters: | Русский, Английский, Фильтр счетчиков и аналитики, раздражителей, 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
