### ISSUE TITLE
Incorrect Blocking amway.ua

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3651]
## Не логинится [amway.ua](https://www.amway.ua):

**При нажатии на "Вход для НПА/клиентов", не появляется окно для логина.**
#### Включенный ADG
![2016-12-05_16-09-18 2](https://cloud.githubusercontent.com/assets/16462533/20888251/baa911d6-bb06-11e6-8343-5f725c889f5c.png)

#### Выключенный ADG
![2016-12-05_16-09-51](https://cloud.githubusercontent.com/assets/16462533/20888298/ea3cf4e4-bb06-11e6-8cab-f25bd2405465.png)
## Фильтры:

Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский
Anti-Adblok Killer | Reek

**Comment by Alex-302** [comment]
Добавил в фильтр аналитики
```
@@||tags.tiqcdn.com/utag/amway/eia/prod/utag.js$domain=amway.ua
```
