### ISSUE TITLE
Ads on news.yandex.ru

### ISSUE THREAD

**Issue by Usmanov-Alesher** [AdguardTeam/AdguardFilters#3652]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Реклама в нижней части страницы на сайте https://news.yandex.ru/Moscow

Иногда для проявления рекламы приходится подождать некоторое время или несколько раз обновить страницу.

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://i82.fastpic.ru/big/2016/1205/4f/06fa787295b93620d4a1bb5c0fb08c4f.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](https://i.imgur.com/A87fxo8.png)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows all
Browser: | Chrome 55.0.2883.75 m (64-bit)
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | TDI
Adguard DNS: | Family Protection
Adguard filters: | Английский фильтр, Фильтр счётчиков и системы аналитики, Фильтр виджетов социальных сетей, Фильтр раздражителей, Русский фильтр, Упрощённый фильтр доменов

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to German filter
```
mathebibel.de##iframe[id^="ylt-"]
```

**Comment by Serzh-SUP** [comment]
## Реклама внизу страницы.
https://news.yandex.ru/yandsearch?lr=213&cl4url=ria.ru%2Ftv_politics%2F20161213%2F1483504096.html&content=alldocs&from=story

## Фильтры:
**Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский**
![image](https://cloud.githubusercontent.com/assets/16462533/21157273/6c2e5b20-c181-11e6-8d61-51a15bfdd031.png)

**Comment by Alex-302** [comment]
Не повторяется
http://imagizer.imageshack.com/img922/2681/Ge86R0.png
Без Адгарда вижу такую в точности.

**Comment by Yana-SUP** [comment]
https://news.yandex.ru/yandsearch?cl4url=regnum.ru/news/polit/2238492.html&lang=ru&from=main_portal&lr=65&msid=1487048674.87482.22896.32176&mlid=1487048446.glob_225.cb53bc81

**Screenshot**: http://prnt.sc/e8p4m8
**Filters**: 1, 5
**AppVersion**: 6.1.298.1564
**Browser**: Chrome
**Driver Type**: Tdi
 **Ticket** **ID**: 1503745

**Comment by Alex-302** [comment]
у меня не повторяется. Может удалённо пустят посмотреть?

**Comment by Yana-SUP** [comment]
еще один человек жалуется ID 1504318
сейчас попрошу удаленку

**Comment by Alex-302** [comment]
ага, жду

**Comment by vmalyuta** [comment]
@Alex-302 user 1050245 needs the TV session today at 5PM, UTC time
Is it possible?

**Comment by Alex-302** [comment]
@vmalyuta write to our chat about remote access, otherwise I can miss the message.
