### ISSUE TITLE
Gismeteo.ru - missed ads

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3654]
## У пользователя пропущена реклама на новом сайте [Gismeteo.ru](https://www.gismeteo.ru)
**Проверять пришлось через Опера+VPN, повторилось.**
### Фильтры:
**Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский
Anti-Adblok Killer | Reek**
### Мой скрин: 
![2016-12-05_21-31-18](https://cloud.githubusercontent.com/assets/16462533/20899548/8d521a66-bb33-11e6-96b9-b05649c48cb7.png)
### Скрин пользователя:
![-us-ascii-b-0khqvdc40lzqvtc6incz0ljrgdc80lxrgtc10l4uslbh-](https://cloud.githubusercontent.com/assets/16462533/20899626/cff9b658-bb33-11e6-9c34-5e7281aaaa1e.jpg)

**Comment by Alex-302** [comment]
VPN Оперы не фильтруем.
Рекламу убрал.

**Comment by Serzh-SUP** [comment]
**Пользователь написала, что появился Яндекс.Директ на новой версии Gismeteo. Если вернуться на старый дизайн сайта, фильтруется абсолютно всё, блоки пропускаются только на новой версии сайта.**

**Comment by Alex-302** [comment]
@Serzh-SUP это сегодняшняя жалоба?

**Comment by Serzh-SUP** [comment]
@Alex-302 Да, буквально часов в 20.40

**Comment by Alex-302** [comment]
Нужен актуальный скрин и прямые ссылки(если не только на главной), а то не совсем пойму что не заблокировано.

**Comment by vgavrish** [comment]
@Alex-302 
ссылка:
gismeteo.ru/weather-samara-4618/3-days/

скрины:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21003606/054a4482-bd35-11e6-8c5f-f44d58fd2cb9.png)
![image](https://cloud.githubusercontent.com/assets/18548949/21003612/0aa22db4-bd35-11e6-8015-f276466ab1cc.png)

**Comment by Alex-302** [comment]
Подправил. Часа через полтора можно будет обновляться.
