### ISSUE TITLE
mysku.ru - Incorrect blocking

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3655]
***Description***: On the website 
http://mysku.ru/
there is option "Перейти в магазин" under the price of every item. When you try to follow the link that goes to aliexpress website - the tab just closes. It happeneds because of Social Media Filter. 

Reported by the customer: 1100783

**Comment by Alex-302** [comment]
Added to Russian filter
```
@@||cityadspix.com^$domain=systemrtb.com,popup
```
