### ISSUE TITLE
http://fmovies.to/film/the-accountant.7jz17/oxqqrz - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3656]
Incorrect blocking on page: http://fmovies.to/film/the-accountant.7jz17/oxqqrz
No videos being loaded

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/20913730/eefcdfc2-bb82-11e6-8960-dade1bb8563d.png)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2016-11-24 02:02:33 +0000

Device: iPad
Platform: iPhone OS
OS: 9.3.3
ID: C66805D3-C9C8-40FF-B408-20E4353D7FDA

Locale: en
Region: gb

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.13 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.37 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.16 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.44 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.79 Enabled=NO
ID=122 Name="Fanboy's Annoyances" Version=1.0.65.47 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.70.27 Enabled=YES

</details>

Ticket ID: 1453656

**Comment by Alex-302** [comment]
Not reproduced. Did you check on your end?

**Comment by evgeniy-ADG** [comment]
Yep, it's fine now. But, when you tap the Play button, it opens a website on the background.

**Comment by Alex-302** [comment]
Try
```
||syndication.exdynsrv.com^$popup
```
we can't completely prevent popup on this site on iOS.

**Comment by sostostg** [comment]
Still seeing this behaviour on fmovies.se on Safari 10.0.3 using browser extension 2.5.11, this is happening when English Filter is enabled.

Seems to work fine on Chrome with same filters enabled.

**Comment by Alex-302** [comment]
@sostostg Adguard(and other adblockers) uses Apple's content blocker, it can't do some things.
Added to Saffari filter
```
||cb8717377086c72d.com^$popup
||partners.parimatch.net^$popup
||go.mobiprotg.com^$popup
```

**Comment by sostostg** [comment]
Sorry should have been more specific. Was referring to the behaviour of no videos being loaded as in the screenshots on fmovies.se  . Any videos from any servers are blocked by the extension.

**Comment by Alex-302** [comment]
My mistake:)
This player is not working on my side without AG.
Please check these rules:
```
@@blob$domain=fmovies.se
@@||fmovies.se/ajax/
@@||fmovies.se
@@||redirector.googlevideo.com/videoplayback?id=
@@||apis.google.com^$domain=fmovies.se
```

**Comment by sostostg** [comment]
I couldn't quite get it working with your filters but I've had some success with these 

@@||fmovies.se/*

Server F2
@@||*.googlevideo.com/*

Server F1
@@||*.*.blogspot.com/*

OpenLoad
@@||openload.co/*
@@||*.oloadcdn.net/*
@@||jwpltx.com/*

I'm not sure why this issue has just cropped up, perhaps it should be investigated with easy list? Also not sure why this is only happening in Safari on the latest extension version, was not happening on 2.4.x

what do you suggest?

**Comment by Alex-302** [comment]
Safari Content Blockers works differently than Adguard apps and browser extensions.
fmovies.to redirects me to fmovies.se
Try these rules:
```
@@||fmovies.se^$domain=fmovies.se
@@||googlevideo.com^$domain=fmovies.se
@@||oloadcdn.net^$domain=fmovies.se
@@||jwpltx.com^$domain=fmovies.se
```
this rule is wide
```
@@||openload.co^$domain=fmovies.se
```
I need example link for the page with this player.
`@@||*.*.blogspot.com/*`
what is it?

**Comment by sostostg** [comment]
You can try the three different servers here for example

https://fmovies.se/film/westworld.801pn/8xm98n

I tried episode one without ad blocker and all 3 servers are working

**Comment by sostostg** [comment]
so Server F1 fails due to this 

`Content blocker prevented frame displaying https://fmovies.se/film/westworld.801pn/k37r69 from loading a resource from https://3.bp.blogspot.com/HENnUN1y_btNs8hxGtSFZDCTyCb7sWfMlvJR6Zq5pBSiSaBtO2c=m22`

and OpenLoad still fails due to these
`Content blocker prevented frame displaying https://fmovies.se/film/westworld.801pn/oxy9n4 from loading a resource from https://openload.co/stream/1PY72i9RRxU~1486055719~89.21.0.0~Dydegyk0?mime=true`

You can try the different servers under the video player to see whether they work

**Comment by Alex-302** [comment]
Another try:)
```
@@||bp.blogspot.com^$domain=fmovies.se|fmovies.to
@@||openload.co/stream/$domain=fmovies.se|fmovies.to
```

**Comment by sostostg** [comment]
So far so good with these 6 rules.. will continue to test 

`@@||fmovies.se^$domain=fmovies.se|fmovies.to`
`@@||googlevideo.com^$domain=fmovies.se|fmovies.to`
`@@||oloadcdn.net^$domain=fmovies.se|fmovies.to`
`@@||jwpltx.com^$domain=fmovies.se|fmovies.to`
`@@||bp.blogspot.com^$domain=fmovies.se|fmovies.to`
`@@||openload.co/stream/$domain=fmovies.se|fmovies.to`

**Comment by Alex-302** [comment]
these rules are in safari filter, you can delete them
```
@@||fmovies.se^$domain=fmovies.se|fmovies.to
@@||googlevideo.com^$domain=fmovies.se|fmovies.to
@@||oloadcdn.net^$domain=fmovies.se|fmovies.to
@@||jwpltx.com^$domain=fmovies.se|fmovies.to
```
added
```
@@||bp.blogspot.com^$domain=fmovies.se|fmovies.to
@@||openload.co/stream/$domain=fmovies.se|fmovies.to
```
