### ISSUE TITLE
http://m.ltaaa.com/ - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3657]
http://m.ltaaa.com/ - missed ad
The ad banner at the bottom of ltaaa.com cannot be removed.

<details>

![image1 2](https://cloud.githubusercontent.com/assets/23258533/20914458/6a0ce32e-bb88-11e6-96e8-b6a7bb2e7bc3.png)

</details>

<details>

Application version: 1.1.2.24
Application lifetime: 2016-11-27 19:55:12 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: 07E854E7-69C9-423C-8509-34F803A5840F

Locale: zh
Region: cn

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.41 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.37 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.19 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.47 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.13 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.80 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.26 Enabled=NO
ID=101 Name="EasyList" Version=1.0.65.27 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.70.29 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.70.60 Enabled=YES

</details>

**Comment by Alex-302** [comment]
Fixed
