### ISSUE TITLE
http://m.imore.com/ - anti-adblocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3658]
http://m.imore.com/when-your-car-wont-play?bt_ee=2UmVTzttd/DKCb8SI3Igueq4yJg734TYFkoF8Pcemt0=&bt_ts=1480962143593

An annoying pop-up that ask to disable adblocker 

<details>

![image1 3](https://cloud.githubusercontent.com/assets/23258533/20914993/dc35375a-bb8b-11e6-9454-07f8f46d3835.png)

</details>

<details>

Application version: 1.1.2.24
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 0E76C3BD-9171-421D-B4E8-9DAA305D8E09

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.97.34 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.14 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.42 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.26 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.23 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.51 Enabled=YES

</details>

Ticket ID: 1182387

**Comment by Alex-302** [comment]
Not reproduced with the same config.
