### ISSUE TITLE
http://www.playground.ru/ - background video ad

### ISSUE THREAD

**Issue by HanabishiRecca** [AdguardTeam/AdguardFilters#3661]
http://www.playground.ru/ - background video ad

<details>
Windows / Chrome Extension

**Filter list:**
Английский фильтр 1.1.2.41.
Фильтр счетчиков и системы аналитики 1.0.9.37.
Русский фильтр 1.0.43.89.
EasyList 1.0.65.27.
EasyPrivacy 1.0.70.30.
Adblock Warning Removal List 1.0.70.44.
RU AdList 1.0.70.43.
Anti-Adblock Killer | Reek 1.0.1.68.
Malware Domains 1.0.70.32.
RU AdList: Counters 1.0.66.99.
Spam404 1.0.1.63.
</details>

Rule to add
-
```
playground.ru###brandVideo
playground.ru###videoCtrl
```

**Comment by Alex-302** [comment]
Added
```
||playground.ru/download/bg/wot-*.mp4
playground.ru##button#videoCtrl
playground.ru###brandVideo
```
