### ISSUE TITLE
Google analytic!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardFilters#36612]
Как убрать utm-метку с юрл http://feedproxy.google.com/~r/itc-ua/~3/dzA3BTfAPaQ/ с помощью расширения? Аналитика гугла достала уже!
---------------------------------------------------------------------How to remove the utm-tag from http://www.feedproxy.google.com/~r/itc-ua/~3/dzA3BTfAPaQ/ using the extension? Google Analytics got already!

**Comment by Alex-302** [comment]
Откуда эта ссылка? Лучше в репозиторий расширения или CoreLibs пиши про хотелку.

**Comment by Spok1** [comment]
С ленты новостей гугл хром для андроид!
