### ISSUE TITLE
Custom rule for mail.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3663]
На главной странице mail.ru <http://mail.ru/> нужно скрыть блок 

<div id="news" class="news" data-extspace="{&quot;5072&quot;:1,&quot;5092&quot;:1,&quot;5360&quot;:1}">

![pastedgraphic-1 copy](https://cloud.githubusercontent.com/assets/15856304/20921242/e7650964-bbab-11e6-84ac-384939804d58.png)

**Comment by Alex-302** [comment]
```
mail.ru##div.layout__centercol__wrap > div#news
```

**Comment by m-emelchenkov** [comment]
Воспользуйтесь браузером macOS/Safari с применением данного правила и увидите, что правило начинает отрабатывать только после первого рефреша страницы. Каждая первоначальная загрузка показывает блок новостей. Иными словами, правило не работает.

**Comment by Alex-302** [comment]
Правило работает, это с расширением проблема
https://github.com/AdguardTeam/AdguardForiOS/issues/101

**Comment by Alex-302** [comment]
@m-emelchenkov 
В следующей версии расширения будет исправлено.
Если не хотите ждать, можете установить бета-версию
https://github.com/AdguardTeam/AdguardBrowserExtension/releases

**Comment by m-emelchenkov** [comment]
На бете у меня это тоже не работает.

**Comment by m-emelchenkov** [comment]
На бете работает, но не очень хорошо: на ~1 секунду новости всё же рендерятся, затем новостной блок пропадает. Хотелось бы, чтоб не рендерились вообще (может какой JS блокировать для этого?)

**Comment by Alex-302** [comment]
Может комп медленный. 
Попробуйте дополнительно
```
mail.ru##div.layout__centercol__wrap > div#news *
```

**Comment by m-emelchenkov** [comment]
Знаете, да, это правило работает много лучше — первый раз новостной блок быстро-быстро мелькнул, но со второго раза и далее проблем не возникло. Такая работоспособность мне вполне подходит, спасибо большое.
