### ISSUE TITLE
livejournal.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#36645]
***Description***:
* **Current behaviour**: 

Broken CSS when protection is enabled. No user filter rules applied.
<details><summary>Screenshot:</summary>

User report
![user_report](https://user-images.githubusercontent.com/33634917/61061414-e298cd00-a404-11e9-9194-2aefa71da3d4.png)

Reproduction
![мертвый лайвжурнал](https://user-images.githubusercontent.com/33634917/61061431-ed536200-a404-11e9-837d-3f0387df7fe7.png)

</details>

* **Expected behaviour**: 

Site should display properly.

***Steps to reproduce the problem***:

1. Just visit the site with protection enabled.

Filtering logs available in ticket 1043902.

***System configuration***

_**Filters**_

**Original submission**: Base, Russian, German, French, Dutch, Official Polish filters for AdBlock, uBlock Origin & AdGuard
**Repro**: Base, Russian, Annoyances, Adblock Warning Removal List

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Original: Windows 7. Reproduced on: Windows 10, Android
Operating system version (Android/iOS) | Original: Windows 7. Repro: Windows 10 Insider Preview build 18936 / Android 9
Browser:                               | Original & reproduction: Chrome 
AdGuard version:                       | Original: 7.1.2817. Reproduced on: 7.1.2848n (Win), 3.1.84n (Android)
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | **original**: Block 3rd-party cookies (180), Block Location API, Remove X-Client-Data header, Hide search queries, Send DNT header. **Reproduction**: None
Helpdesk ID (if exists):               | 1043902

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.
