### ISSUE TITLE
http://www.lots.org.uk/ and http://www.extragold.nl/ - Assistant doesn't show up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3664]
http://www.lots.org.uk/

I was unable to find any expectations for this site.

![image](https://cloud.githubusercontent.com/assets/15856304/20921478/e5b46ed8-bbac-11e6-8917-4f07d27e295c.png)

1295530

**Comment by Alex-302** [comment]
@evgeniy-ADG 
шаблон кто заполнять будет?

**Comment by evgeniy-ADG** [comment]
Все дефолтное

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/21073350/40c364ca-bee4-11e6-8d27-29c2c74dbeea.png)

**Comment by Alex-302** [comment]
Список фильтров обязателен. Если в каком-нибудь из включенных сайт в исключениях, то логично, что помощник туда инжектиться не будет.
Конкретно эти сайты основаны на наборе фреймов, в которые поможник не инжектится, иначе их были бы десятки на странице.
