### ISSUE TITLE
Google Ads missed when using the extension

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3665]
https://www.google.com.ua/search?q=google&oq=google&aqs=chrome..69i57j69i60l3j0l2.1220j0j7&sourceid=chrome&ie=UTF-8#q=travel

![image](https://cloud.githubusercontent.com/assets/15856304/20921699/fe1f1dfa-bbad-11e6-8577-2be088ce3347.png)

![image](https://cloud.githubusercontent.com/assets/15856304/20921707/04ead96c-bbae-11e6-8d2c-5e7c5848f607.png)

**Comment by Alex-302** [comment]
Скрин твой? Нужен скриншот кода элемента
