### ISSUE TITLE
linkdrop.net detect Adguard & won't load

### ISSUE THREAD

**Issue by rayman3003** [AdguardTeam/AdguardFilters#3666]
The short url website "linkdrop.net" can detect Adguard and won't load. It shows the following text:

"Please disable your adblock and script blockers to view this page"

example link:

http://linkdrop.net/8SsT4

-----------------------------
OS; Windows 10 x64

Browsers: Chrome - Firefox - IE

AppVersion: 6.1.298.1564
 Main settings:
 Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
 FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
 FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
 FilterId:122 Name: Fanboy's Annoyances Url: https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
 FilterId:207 Name: Adblock Warning Removal List Url: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
 FilterId:211 Name: Anti-Adblock Killer | Reek Url: https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
 FilterId:215 Name: Fanboy's Enhanced Tracking List Url: https://secure.fanboy.co.nz/enhancedstats.txt

**Comment by Alex-302** [comment]
check these rules
```
@@||advertising.yahoo.com/favicon.ico$domain=linkdrop.net
@@||bannertrack.net/*ad$domain=linkdrop.net
@@||yahoo.$domain=linkdrop.net
@@||adtrackers.net^$domain=linkdrop.net
@@||bannertrack.net^$domain=linkdrop.net
@@||cdn.rawgit.com^$domain=linkdrop.net
```

**Comment by rayman3003** [comment]
No, none of these helped. Still showing that.

**Comment by Alex-302** [comment]
Added to English filter
```
linkdrop.net#%#(function() { var sto = window.setTimeout, re = /\.bab_elementid.$/; window.setTimeout = function(a, b) { if ( typeof a !== 'string' || !re.test(a) ) { return sto(a, b); } }.bind(window); var signatures = [ ['blockadblock'], ['babasbm'], [/getItem\('babn'\)/], ['getElementById','String.fromCharCode','ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789','charAt','DOMContentLoaded','AdBlock','addEventListener','doScroll','fromCharCode','<<2|r>>4','sessionStorage','clientWidth','localStorage','Math','random'] ]; var check = function(s) { var tokens, match, j, token, pos; for ( var i = 0; i < signatures.length; i++ ) { tokens = signatures[i]; match = 0; for ( j = 0, pos = 0; j < tokens.length; j++ ) { token = tokens[j]; pos = token instanceof RegExp ? s.search(token) : s.indexOf(token); if ( pos !== -1 ) { match += 1; } } if ( (match / tokens.length) >= 0.8 ) { return true; } } return false; }; var realEval = window.eval; window.eval = function(a) { if ( !check(a) ) { return realEval(a); } var el = document.body; if ( el ) { el.style.removeProperty('visibility'); } el = document.getElementById('babasbmsgx'); if ( el ) { el.parentNode.removeChild(el); } }.bind(window); })()
```

**Comment by rayman3003** [comment]
Thank u.

But I must say that it gets resolved in Firefox & Chrome but the warning still showing on IE:

"Please disable your adblock and script blockers to view this page. "
