### ISSUE TITLE
sznpaste.net detect Adguard & won't load

### ISSUE THREAD

**Issue by rayman3003** [AdguardTeam/AdguardFilters#3667]
The short url website "sznpaste.net" can detect Adguard and won't load. It shows the following text:

"Please disable your adblock and script blockers to view this page"

example link:

http://sznpaste.net/RZwFrKaC

-----------------------
OS; Windows 10 x64

Browsers: Chrome - Firefox - IE

AppVersion: 6.1.298.1564
 Main settings:
 Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
 FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
 FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
 FilterId:122 Name: Fanboy's Annoyances Url: https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
 FilterId:207 Name: Adblock Warning Removal List Url: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
 FilterId:211 Name: Anti-Adblock Killer | Reek Url: https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
 FilterId:215 Name: Fanboy's Enhanced Tracking List Url: https://secure.fanboy.co.nz/enhancedstats.txt

**Comment by Alex-302** [comment]
Added to English filter
```
@@||sznpaste.net^$generichide
```

**Comment by rayman3003** [comment]
Thank u.
