### ISSUE TITLE
einthusan.com

### ISSUE THREAD

**Issue by vivshah56** [AdguardTeam/AdguardFilters#36675]
***Description***:
* **Current behaviour**: 

The following website detects the presence of adguard : https://einthusan.com

<img width="707" alt="Screen Shot 2019-07-11 at 9 24 12 PM" src="https://user-images.githubusercontent.com/39109924/61102342-48478200-a422-11e9-9511-b4687b946ba4.png">

* **Expected behaviour**: 

Adguard should not be detected. User should be able to load the website and do the following : 
1. Open einthusan.com 
2. Click "Hindi"
3. Click "Movies"
4. Click on any movie video. The video should load when clicking the "Play" button

***Steps to reproduce the problem***:
1. Open https://einthusan.com

***System configuration***

**Filters:**
AdBlocking Filter, Annoyances Filter

Information                            | Value
---                                    | ---
Operating system:                      | MacOS
Browser:                               | Google Chrome
Filters enabled:                       | Yes

**Comment by krystian3w** [comment]
I can reproduce without any click.

**Comment by krystian3w** [comment]
`@@||einthusan.com/prebid.js$script,first-party`

**Comment by bogachenko** [comment]
@krystian3w `first-party` adguard does not support this flag

**Comment by AdamWr** [comment]
Unfortunately I can't reproduce it.
Do I understand correctly that this rule `@@||einthusan.com/prebid.js` is enough and other exclusions are not needed to watch video, like it was in case of `einthusan.tv`?

**Comment by vivshah56** [comment]
Looks like this has been resolved.

**Comment by AdamWr** [comment]
I was able to reproduce it today.
Fixed, update should be available in 1-2 hours.

Thank you for your reply.
