### ISSUE TITLE
http://www.imagebam.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3668]
Пропущена реклама на сайте http://www.imagebam.com/image/add017517623263
Скриншот: http://f5.s.qip.ru/OgbqitxD.png

Мои параметры:
* Win x64
* adguard в виде расширения у Chrome
* фильтры: русский, английский, RU AdList
* Dr.Web

**Comment by Alex-302** [comment]
Added to English filter
```
||imagebam.com/files/_b*.php
```
