### ISSUE TITLE
[Extension] http://hdrezka.me

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#3669]
Невозможно изменить качество видео, Адгард детектится.

Проблема наблюдалась в расширении для Opera. 

Например здесь:
http://hdrezka.me/series/fantasy/22421-davay-srazhatsya-prizrak.html

Фильтры: Английский, Русский, Фильтр счетчиков и системы аналитики, Фильтр виджетов социальных сетей, Фильтр раздражителей.

**Comment by Alex-302** [comment]
Всё норм

![image](http://imagizer.imageshack.com/img924/2140/ogR8km.png)
