### ISSUE TITLE
Реклама на сайте

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#3670]
http://justfitnes.ru/potyanul-spinu-my-podskazhem-kak-i-chto-delat/
Фильтры по-умолчанию. Реклама на мобильнике такая, Фильтрация быстрая
http://s019.radikal.ru/i616/1612/b9/cd22eddac17d.png

**Comment by ministr91** [comment]
@Alex-302, Хоть бы коммент написал какой-нибудь

**Comment by Alex-302** [comment]
Метка вполне однозначная.
Читай
https://github.com/AdguardTeam/AdguardFilters/issues/new

**Comment by ministr91** [comment]
Инсипукция по составлению запроса? 
Но ведь проблема же есть, я скрин кинул

**Comment by ministr91** [comment]
Зачем по инструкции? Я описал проблему, скрин есть
