### ISSUE TITLE
thewindowsclub.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#36705]
**Site Sample** | 
----------------|
https://www.thewindowsclub.com/remove-default-windows-10-sign-in-picture

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1903 x64
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.1.2817 RELEASE** 
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
|Disable cache for 3rd-party requests
| **=== FILTERS ENABLED ===**
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| Fuck Fuckadblock
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| Fanboy's Enhanced Tracking List
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| Fanboy's Annoyances
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

Cookie

<details><summary><b>Screenshot:</b></summary>

![scr-1562954511-001](https://user-images.githubusercontent.com/9846948/61148921-290f2a00-a4e0-11e9-931d-806360aa3ecd.png)

</details><br/>

@AdamWr @Alex-302

**Comment by Alex-302** [comment]
Not reproduced. Please upload saved page.
Is scrolling locked?

**Comment by FadeMind** [comment]
Is GEO locked - EU GDPR restrictions IMHO. 

Scroll works.

```
thewindowsclub.com###ez-cookie-dialog-wrapper
```
ZIPPED FULL SITE 
[thewindowsclub-site-cmpl.zip](https://github.com/AdguardTeam/AdguardFilters/files/3390254/thewindowsclub-site-cmpl.zip)

**Comment by Alex-302** [comment]
Ok, added.
