### ISSUE TITLE
[Extension] https://www.lostfilm.tv/ - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#3671]
browser extension
current:
<details>

![2016-12-07 14 37 29](https://cloud.githubusercontent.com/assets/23637588/20966368/f775609e-bc8a-11e6-9161-ce3f0053a601.png)

</details>

expected:

<details>

![2016-12-07 14 40 57](https://cloud.githubusercontent.com/assets/23637588/20966409/2fc1331a-bc8b-11e6-84f8-d69281d59716.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Adguard filters: | Английский, Русский, Фильтр счетчиков и системы аналитики, Фильтр виджетов социальных сетей, Фильтр раздражителей.

**Comment by Alex-302** [comment]
not reproduced
http://imagizer.imageshack.com/img922/4565/BlFfmq.png

**Comment by zebrum** [comment]
в опере, сафари и хроме повторяется
в яндекс-браузере - не повторяется

**Comment by Alex-302** [comment]
Удалённо бы глянуть. Повторить не удаётся
http://imagizer.imageshack.com/img922/4002/ozJcQ1.png

**Comment by zebrum** [comment]
@Alex-302 
agrrrhhhhh
<details>






![2016-12-14 18 45 41](https://cloud.githubusercontent.com/assets/23637588/21188778/89b264be-c22d-11e6-91e4-688267f5de3a.png)

</details>

**Comment by Alex-302** [comment]
@zebrum is https filtering works on this site?
Check for this string in HTML code
```
injected by Adguard
```

**Comment by zebrum** [comment]
yes
i checked

**Comment by Alex-302** [comment]
Still can't reproduce, so I can't fix it.

**Comment by zebrum** [comment]
right now everything is ok, so i'm closing it )
