### ISSUE TITLE
http://vlinderscrime.nl/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3672]
Missed ad on page: http://vlinderscrime.nl/

<details>

![image2](https://cloud.githubusercontent.com/assets/15856304/20973015/9df83018-bc9f-11e6-8640-8313bd8aa9e9.png)

![image1 2](https://cloud.githubusercontent.com/assets/15856304/20973018/9ff13c48-bc9f-11e6-94fe-443d37e2763d.png)

</details>

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.35 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.36 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.15 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.42 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.9.11 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.80 Enabled=YES
ID=106 Name="EasyList Dutch" Version=1.0.70.47 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.70.40 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES

**Comment by Alex-302** [comment]
This site is not working at the moment
