### ISSUE TITLE
http://m.ensonhaber.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3673]
http://m.ensonhaber.com/tuncay-ozkan-fethullahin-itleri-yildiramaz-bizleri-2016-12-07.html

Videos are blocked.

![file_000 2](https://cloud.githubusercontent.com/assets/15856304/20973687/355192e0-bca2-11e6-919a-e06ec9d6b652.png)

<details>

Optimazed enabled: NO

Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.55 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.39 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.20 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.5.15 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.81 Enabled=YES
ID=101 Name="EasyList" Version=1.0.65.31 Enabled=YES

**Comment by tagataho** [comment]
Yeah, i can not see video in Ensonhaber. When you fix that problem?

**Comment by Alex-302** [comment]
Added to English filter
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=videonuz.ensonhaber.com
```
