### ISSUE TITLE
yandex.*

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#36732]
[https://yandex.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://yandex.ru/)

 главный Баннер на Главной:

 `yandex.*##.main [class=""] > :matches-css(margin-bottom: 0px)`
 `yandex.*#$#.main [class=""] :matches-css(background-repeat: no-repeat):has(.home-logo) { background-image: none!important; }`

<details><summary>Screenshot:</summary>

![2019 07 13-4](https://user-images.githubusercontent.com/17948007/61166039-b67a6a80-a530-11e9-87fa-e17764c4ed6b.png)
</details>

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.2.1
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
Стрёмные правила.

**Comment by XX-J** [comment]
> Стрёмные правила.

 Зато вот уже сколько месяцев работают БЕЗ проблем. Специально долго тестировал, перед тем как создавать тему.
 И не такие-уж они стрёмные, если ХОРОШЕНЬКО разобраться.
