### ISSUE TITLE
 FoxNews.com - Incorrect blocking

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3674]
***Description***:  When trying to watch some video on the website FoxNews.com it won't play. Just black square instead of media player. 

Operating system: | Windows 10
Browser: | IE/Chrome/Edge 
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) |   
"BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"
Adguard filters: | 
English filter 
Spyware filter 
Social media filter 
Liste FR 
User filter 
Annoyances filter

The weird thing is: first the issue reproduced as described. Then I turned Adguard off and back on and after that - videos were playing fine.

Customer ID: 1457669

**Comment by Alex-302** [comment]
@seanl-adg consider that sometimes it is not working even with only Eng filter
