### ISSUE TITLE
Jysk sites - Blocked content (AdGuard Social Media filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#36754]
### Affected sites:
All of Jysk's domains.

### Problem filter:
* AdGuard Social Media filter

### Problem rule:
`##.social-share`

### Issue:
Full info here (with a solution in the second post):
https://github.com/ryanbr/fanboy-adblock/issues/1095/

**Comment by krystian3w** [comment]
https://jysk.pl/guide/jak-wybrac-zaslony-i-zaluzje

**Comment by Alex-302** [comment]
What is wrong? Please add screenshots.

**Comment by THEtomaso** [comment]
Really?
OK, issue reopened here (with screenshot):
https://github.com/AdguardTeam/AdguardFilters/issues/36836/
