### ISSUE TITLE
forum.donanimhaber.com - pop-up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3675]
forum.donanimhaber.com

You need to spend a few minutes on a forum browsing and this will pop up:
[link](https://ad.donanimhaber.com/PageBanner.aspx?a1=8545a5d404aa4df6be106d45863bb4457427d20ac38947a791ff425223d735c389d84521853d42c7a7ce9071e040ce7d30e0f2e36bc94095ac8556a48e8def46&q1=2&a2=b042ce0425d2452989b69998dd662ca62fd70dc3e6574be18e3a2b1848cb2dec&q2=1&a3=19dadce1f5c04529b28ed60b980071d987a5cae337f14fd386eafc8987fb5eb4&q3=199&q4=1&q5=0&a4=26ccacad298041748e0a58098961e255&q6=0&q7=11&a5=394f888a7df444f985d3b4576627f301&ref=https://forum.donanimhaber.com/m_122364482/tm.htm&a6=5c230806ccc949238dfae861272b5d4ee565d0f40bb2404498108d55e7eddc8bf42c6d33befe410baf5692f4bb6f0debefa91d8baf754bd6bdced876bd5737709522e73038de43619e050e347ecb72ef32fd7f1a698546e9a9b6c889f51298eeff5b517071a3423baa0f3d12eb8a52fa98505e12df1f42d4a1d00a835b84862c20f1f77b27ff40419907f5f8b971b6f8)

<details>
Os version: Microsoft Windows NT 10.0.14393.0
Dot .net version: 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: a9bc92f4277943f18bc164b134e24f96
Language: tr
AppVersion: 6.1.298.1564
Main settings: 
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:5 Name: Experimental filter Url: http://adguard.com/ru/filter-rules.html?id=5
FilterId:13 Name: Turkish filter Url: http://adguard.com/ru/filter-rules.html?id=13
FilterId:14 Name: Annoyances filter Url: http://adguard.com/ru/filter-rules.html?id=14
FilterId:113 Name: Liste FR Url: https://easylist-downloads.adblockplus.org/liste_fr.txt
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Wfp
Ads Blocked: 138299, Trackers Blocked: 70444
Filtering Mode: Driver
Application lifetime: 2.16:56:54.5107150
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": false,
  "BlockWebRtc": false,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"
}

[debug (4).txt](https://github.com/AdguardTeam/AdguardFilters/files/637579/debug.4.txt)

**Comment by tagataho** [comment]
Yeah, can you fix this? I use safari on iphone

**Comment by Alex-302** [comment]
Added to Turkish filter
```
forum.donanimhaber.com##div[class^="DH-Reklam-"]
forum.donanimhaber.com#%#Object.defineProperty(window, 'pageCount', { get: function() { return 0; } });
```

> Yeah, can you fix this? I use safari on iphone
Sadly, but it is impossible on iOS, because it doesn't support JS rules.
