### ISSUE TITLE
torrentgirl.org - No assistant, Missed ads 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3676]
***Description***:  Missed ads and no assistant (only on Windows) on the website:
torrentgirl.org 
Screenshot:
<details>

![capture](https://cloud.githubusercontent.com/assets/17504743/20985107/b0865936-bccb-11e6-95c4-b608e6cabba4.PNG)

</details> 

***System configuration***

Information | value
--- | ---
Operating system: | Microsoft Windows NT 10.0.10586.0
Browser: | Google Chrome
Adguard version: | 6.1.298.1564 (the same with 6.1.258.1302)
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | 
 "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "BlockBrowserPushApi": true,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": true,
  "HideUserAgent": false,
  "CustomUserAgent": "Mozilla/5.0 (Linux; Android 5.1.1; SM-G928X Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Mobile Safari/537.36",
  "CustomReferer": null,
  "HideIp": true,
  "CustomIp": "128.0.0.1"
Adguard filters: | User, English, Spyware, Social media, Russian, Annoyance, Experimental

Ticket ID: 1101991

**Comment by seanl-adg** [comment]
'No assistant' part should be reported on AdguardForWindows repo, moved here https://github.com/AdguardTeam/AdguardForWindows/issues/1449
