### ISSUE TITLE
numberempire.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3677]
***Site***: http://www.numberempire.com/integralcalculator.php
***Description***: Site detects Adguard.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20986287/3ec80b26-bcc8-11e6-80dd-afc885dea512.png)

</details>

***Steps to reproduce the problem***: Message will be displayed after you calculate something (e.g. you can try to insert "x")

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.2.64
 Spyware filter | 1.0.9.42
 Social media filter | 1.0.15.27
 Annoyances filter | 1.0.7.55
 German filter | 1.0.29.9
 Mobile ads filter | 1.0.6.18
 Safari filter | 1.0.1.81

**Comment by Alex-302** [comment]
Not reproduced.

**Comment by danidoedel** [comment]
@Alex-302 Still there for me, I hope this helps:
![image](https://cloud.githubusercontent.com/assets/10995998/21196196/174b3ae0-c237-11e6-8ab1-5f77302e8079.png)

And there is now some ad as well:

![image](https://cloud.githubusercontent.com/assets/10995998/21196240/3790a9de-c237-11e6-99f8-7b5374f533fc.png)
