### ISSUE TITLE
maclife.de - Social Widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3679]
***Site***: http://www.maclife.de/ratgeber/apple-pay-deutschland-richten-bezahldienst-schon-jetzt-10086186.html
***Description***: Social button leftover on desktop and mobile.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/20986603/9c834a2c-bcc9-11e6-8a74-44db76d0ac15.png)

![image](https://cloud.githubusercontent.com/assets/10995998/20986621/aca54f72-bcc9-11e6-9c16-ffdda5119fd8.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.2.64
 Spyware filter | 1.0.9.42
 Social media filter | 1.0.15.27
 Annoyances filter | 1.0.7.55
 German filter | 1.0.29.9
 Mobile ads filter | 1.0.6.18
 Safari filter | 1.0.1.81

**Comment by Alex-302** [comment]
Added to Social filter
```
maclife.de##.flexshare > ul.share
```
