### ISSUE TITLE
http://www.mackungfu.org - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3680]
Missed ad on page: http://www.mackungfu.org/CreatingtheultimateMacApplerepairtoolbox

An annoying pop-up appears while loading the page, saying to disable adblocker.

<details>

![image](https://cloud.githubusercontent.com/assets/23258533/20988767/cb717faa-bcda-11e6-919b-832b0f45d4b7.jpg)

</details>

<details>
Application version: 1.1.2.24
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 3DA0C1AE-EE48-4D2E-87F8-1F55E0369324

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.34 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.36 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.14 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.41 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.9 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.80 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.32 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.70.39 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.63 Enabled=YES

</details>

Ticket ID(if exists): 1461765

**Comment by Alex-302** [comment]
fixed
