### ISSUE TITLE
https://www.aclu.org - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3681]
Missed ad on page:
https://www.aclu.org/news/aclu-and-lgbt-groups-call-obama-grant-clemency-chelsea-manning

there is a huge banner saying "PROTECT OUR RIGHTS your gift to the ACLU Will be Matched Donate Now"

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/20992341/360f8d6e-bcec-11e6-8ac1-53f530452c01.png)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2016-12-04 05:26:39 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: A3D31A3C-5603-4742-B433-15301CBEC975

Locale: en
Region: se

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.50 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.39 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.19 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.81 Enabled=YES
ID=102 Name="ABPindo" Version=1.0.1.28 Enabled=YES
ID=223 Name="Fanboy's Swedish" Version=1.0.0.4 Enabled=YES

</details>

Ticket ID(if exists): 1459191

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
aclu.org###block-aclu-promotions-aclu-promotions-banner
```
