### ISSUE TITLE
https://www.washingtonpost.com - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3682]
Missed ad on page:
https://www.washingtonpost.com/news/morning-mix/wp/2016/12/07/colombia-shaken-after-wealthy-architect-charged-with-kidnapping-slaying-of-7-year-old-indigenous-girl/?hpid=hp_mhp-morning-mix_mm-colombia%3Ahomepage%2Fstory

At the bottom, while it may not be an "ad" per se, it was not created by the website. 

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/20997356/6b42093c-bd0d-11e6-8524-64828e8bbf44.png)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2016-04-02 20:07:59 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: DCD32809-3776-40BE-AD62-75704C8F586C

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.59 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.40 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.21 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.81 Enabled=YES

</details>

Ticket ID(if exists): 1462129

**Comment by Alex-302** [comment]
Not reproduced.
