### ISSUE TITLE
лидер-качества.рф

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3683]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Блокируются некоторые кнопки на сайте (не дают
http://xn----8sbahhgctvf2dqn1e.xn--p1ai/

Расширение, программа
Помогает отключение Фильтр счетчиков и аналитики,

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21001076/043dd986-bd27-11e6-85a6-330800b3bc9e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | ВиН
Browser: | Хром
Adguard version: | 6.1.298 и 2.4.14
Adguard driver (Windows): | WFP 
Adguard DNS: | None 
Adguard filters: | Русский, Английский, Фильтр счетчиков и аналитики, фильтр виджетов, раздражителей

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1461908

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||mc.yandex.ru/metrika/watch.js$domain=лидер-качества.рф
```
