### ISSUE TITLE
pogoda.yandex.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3684]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Директ
https://yandex.ru/pogoda/orel
https://yandex.ru/pogoda/podgornoe-novohopersky-district

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21007709/c534973c-bd46-11e6-9f04-8897344d0863.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21007715/cb8d3e68-bd46-11e6-911f-a332421d6f96.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Вин
Browser: | Хром
Adguard version: | 6.1.296.1549 и 6.1.298.1564
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Stealth mode options(Windows) | null
Adguard filters: | Русский, Английский, Фильтр счетчиков и аналитики, фильтр виджетов, раздражителей

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1437937, 1259727 и 942797

> Это происходит во всех браузерах. Реклама то пропадает, то опять появляется. И происходит это только при просмотре погоды в поисковике Яндекса. Значок помощник Adguard на странице отображается.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Почему-то стиль, применяемый с помощью расширенного CSS сбрасывается в некоторых случаях(например масштабирование страницы или изменение размера окна)
@vozersky сообщи куда следует)

**Comment by Alex-302** [comment]
@vgavrish уточни плз, повторяется ли с текущей бетой
