### ISSUE TITLE
Yandex Zen ads in Yandex browser using Content Blocker 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3685]
***Description***: Appearing of ads on Yandex Zen (Yandex Browser's function that
show news from several sites)

Screenshot:
<details>

![screenshot_2016-12-07-16-59-05](https://cloud.githubusercontent.com/assets/17504743/21016884/0360ff2c-bd70-11e6-81e3-3380f6eb6ae0.png)

</details>

Content Blocker used 

Ticket ID(if exists): 1425634

**Comment by Alex-302** [comment]
Content Blocker can't block Yandex ads in general(hardcoded exclusions in Yandex Browser)
