### ISSUE TITLE
rutracker.org - Missed ads 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3686]
***Description***: Banner on the website rutracker.org/forum

Screenshot:
<details>

![capture](https://cloud.githubusercontent.com/assets/17504743/21025474/4a60d534-bd91-11e6-976a-b3fe01244561.PNG)

</details>

Information | value
--- | ---
Operating system: | Microsoft Windows NT 6.1.7601 Service Pack 1
Browser: | Google Chrome
Adguard version: | 6.1.258.1302 (reproduced with the last one)
Adguard driver (Windows): | TDI
Filters: | English, Spyware, Social media, German, User (reproduced with all basic ones) 
Ticket ID(if exists): | 1462805

Assistant's present

**Comment by Alex-302** [comment]
Fixed
