### ISSUE TITLE
YouTube Comments disabled using default.

### ISSUE THREAD

**Issue by VanillaChan6571** [AdguardTeam/AdguardFilters#36860]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: YouTube Comments disabled.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: Not disabled.
![youtube enabledpng](https://user-images.githubusercontent.com/39040261/61199919-f78f8d80-a69c-11e9-930d-4e9a05bd43d1.png)

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)
![disabled](https://user-images.githubusercontent.com/39040261/61199950-0fffa800-a69d-11e9-98d0-03a780bfad72.png)

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:
1. Launch youtube app
2. Load comments and disabled.
3. Use a differnt dns and comments are back making this dns not useful.
[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

Information                            | Value
---                                    | ---
Operating system:                      | IOS
Operating system version (Android/iOS) |  IOS
Browser:                               |  N/A
AdGuard version:                       | N/A
Filters enabled:                       | N/A
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | Default
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               |  None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by bogachenko** [comment]
This is all cool of course, but how does this relate to the adguard program, if the author of the video turned off the possibility of commenting?

**Comment by Alex-302** [comment]
@VanillaChan6571 please copy URL of the video.
Is Family DNS enabled?

**Comment by krystian3w** [comment]
https://m.youtube.com/watch?v=qqtEEFKYAVM / https://www.youtube.com/watch?v=qqtEEFKYAVM

**Comment by Alex-302** [comment]
I see comments. They are blocked with Family DNS enabled.
