### ISSUE TITLE
palemoon.org - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3687]
***Site***: https://www.palemoon.org/
***Description***: Ad leftover at the right side.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21026768/6996ce3e-bd8e-11e6-82a2-25ee6ce70707.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.2.69
 Spyware filter | 1.0.9.43
 Social media filter | 1.0.15.29
 Annoyances filter | 1.0.7.58
 German filter | 1.0.29.12
 Mobile ads filter | 1.0.6.18
 Safari filter | 1.0.1.81

**Comment by Alex-302** [comment]
Added to English filter
```
palemoon.org##.sidebar > table.topnews~div[style^="text-align: center;"]
```

**Comment by THEtomaso** [comment]
@Alex-302:

> Added to English filter
> 
> ```
> palemoon.org##.sidebar > table.topnews~div[style^="text-align: center;"]
> ```

That rule now blocks their donation banner, which I assume should be considered unintended!

**Comment by Alex-302** [comment]
fixed
