### ISSUE TITLE
https://m.news.rambler.ru - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3688]
Missed ad on page: https://m.news.rambler.ru/weapon/35524813-kompleks-s-300-szheg-sebya-svoey-raketoy/?utm_source=mhead&utm_content=news&utm_medium=mnews&utm_term=head 

Big banner at the top of the page is not blocked.

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21027931/ad621c56-bd9b-11e6-951e-9cb74c22ff79.png)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2016-12-05 17:34:55 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: AEE223C8-3B32-49F0-9B73-8D60A0043B46

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.63 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.41 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.26 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.52 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.17 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.81 Enabled=YES

</details>

Ticket ID(if exists): 1461751

**Comment by Alex-302** [comment]
Can't reproduce.
Removed social share button.
