### ISSUE TITLE
http://hackyouriphone.org/ - missed ad, incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3689]
http://hackyouriphone.org/ - missed ad and incorrect blocking

Missed ad - see screenshot 
Incorrect blocking - blank space at the top of the page (see screenshot)

<details>

![slack for ios upload](https://cloud.githubusercontent.com/assets/23258533/21028444/e247ab0a-bd9d-11e6-97f3-ab229b639cc4.jpg)

</details>

<details>

![slack for ios upload 1](https://cloud.githubusercontent.com/assets/23258533/21028466/fbdeec5e-bd9d-11e6-801a-2ff80bf5b3fc.jpg)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2016-11-19 22:43:55 +0000
Device: iPhone
Platform: iPhone OS
OS: 9.3.3
ID: 65FEA986-E43A-461D-BBCA-6598FF930464
Locale: it
Region: it
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.69 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.9.43 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.14.76 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.7.58 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.18 Enabled=NO
ID=12 Name="Safari filter" Version=1.0.1.81 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.36 Enabled=YES
ID=101 Name="EasyList" Version=1.0.65.37 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.70.47 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.65.40 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.65.58 Enabled=YES
ID=109 Name="EasyList Italy" Version=1.0.70.47 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.70.61 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.69.51 Enabled=NO
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=206 Name="Xfiles" Version=1.0.0.59 Enabled=YES

</details>

Ticket ID(if exists): 1453442

**Comment by Alex-302** [comment]
Added to English filter
```
hackyouriphone.org##.sweet-overlay
hackyouriphone.org##div.show-sweet-alert

```
