### ISSUE TITLE
 chip.de - Annoyance - Social - Mobile

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3690]
***Site***: http://www.chip.de/news/Virus-entfernen-kostenlos-Malwarebytes-Anti-Malware-hilft-Virenscannern_90204782.html
***Description***: 
1. On mobile site shows an app banner at the bottom. 
2. Site asks to like the page on facebook to read the full article (or press no to watch it anyway).

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21029155/ae5394a8-bd98-11e6-8791-255212400b6f.png)

</details>

***Steps to reproduce the problem***: Open the link above on mobile and the facebook request will show up after a short time.

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.2.69
 Spyware filter | 1.0.9.43
 Social media filter | 1.0.15.29
 Annoyances filter | 1.0.7.58
 German filter | 1.0.29.12
 Mobile ads filter | 1.0.6.18
 Safari filter | 1.0.1.81

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
chip.de#%#document.cookie = "likeGateOpened=true";
```
