### ISSUE TITLE
fosshub.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#36924]
https://www.fosshub.com/foobar2000.html

Donation annoyance
```
fosshub.com###adLocation
```

![s](https://i.imgur.com/drV6BjG.png)

@Alex-302

**Comment by tvinzz** [comment]
Please enable Annoyances filter.

**Comment by FadeMind** [comment]
@tvinzz 
Current used setup:

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1903 x64 (lastest)
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.1.2817 RELEASE** 
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Block WebRTC/Location API/Java/Flash
|Disable cache for 3rd-party requests
|Hide your search queries
|Remove X-Client-Data header from HTTP requests
|Self-destructing third-party cookies
|Send Do-Not-Track header
|Strip tracking parameters from URLs
| **=== FILTERS ENABLED ===**
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| Fuck Fuckadblock
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| Fanboy's Annoyances
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

**Comment by Alex-302** [comment]
@FadeMind it is hidden by `fosshub.com##aside.ad[aria-label="Advertisement"]` from Annoyances.

**Comment by FadeMind** [comment]
@Alex-302 my bad. Somehow Adguard Annoyances was not active. Regards.
