### ISSUE TITLE
gehaxelt.in - Ad - Social leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3692]
***Site***: http://www.gehaxelt.in/blog/
***Description***: Social leftover and Ad at the right side.

<details>
<summary>Screenshot</summary>
Social leftover:

![image](https://cloud.githubusercontent.com/assets/10995998/21029399/c530dafe-bd99-11e6-8d78-d0b24f6a42a5.png)

Ad:

![image](https://cloud.githubusercontent.com/assets/10995998/21029407/d3925cf8-bd99-11e6-9f4b-412778415e62.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.2.69
 Spyware filter | 1.0.9.43
 Social media filter | 1.0.15.29
 Annoyances filter | 1.0.7.58
 German filter | 1.0.29.12
 Mobile ads filter | 1.0.6.18
 Safari filter | 1.0.1.81

**Comment by Alex-302** [comment]
Added to German filter
```
gehaxelt.in##.sidebar .first.even[-ext-has="h1:contains(Werbung)"]
```
1. is too small
