### ISSUE TITLE
board.gulli.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3693]
***Site***: http://board.gulli.com/thread/268082-ist-es-illegal-wenn-ich-faq-s-zu-tauschboersen-poste/
***Description***: Ad leftover after forum posts.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21029543/8edb7a8a-bd9a-11e6-8e45-28e706f7cc25.png)

</details>

***Steps to reproduce the problem***: -
***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.2.69
 Spyware filter | 1.0.9.43
 Social media filter | 1.0.15.29
 Annoyances filter | 1.0.7.58
 German filter | 1.0.29.12
 Mobile ads filter | 1.0.6.18
 Safari filter | 1.0.1.81

**Comment by Alex-302** [comment]
Added to German filter
```
board.gulli.com###posts > li.postbitlegacy:not([id^="post_"]):not([class*="old"])
```
