### ISSUE TITLE
erlangen.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3695]
***Site***: http://www.erlangen.de/
***Description***: Cookie notice at the bottom right.
<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21031513/2c02b1da-bda4-11e6-8f91-b37f5d23ae05.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.2.69
 Spyware filter | 1.0.9.43
 Social media filter | 1.0.15.29
 Annoyances filter | 1.0.7.58
 German filter | 1.0.29.12
 Mobile ads filter | 1.0.6.18
 Safari filter | 1.0.1.81

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
erlangen.de##.cookie_richtlinien
```
