### ISSUE TITLE
nytimes.com

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardFilters#36954]
Tracker found by Ghostery anti-tracking technology:

pay.google.com

![Captura de Pantalla 2019-07-16 a la(s) 11 19 04](https://user-images.githubusercontent.com/46760897/61302290-e6896e00-a7bb-11e9-97f5-58ef9a2575f2.png)

Filters enabled in AdGuard Nightly for macOS Catalina Beta:

English AdGuard ( base ) filter
Spyware AdGuard filter
Social Networks AdGuard filter
Annoyances AdGuard filter
Russian AdGuard filter
Spanish/Portuguese AdGuard filter

**Comment by Alex-302** [comment]
Not a good idea to block it.
