### ISSUE TITLE
lanacion.com.ar

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardFilters#36955]
Trackers found by Ghostery anti-tracking technology:

google.com/recaptcha/api2/
pay.google.com

![Captura de Pantalla 2019-07-16 a la(s) 11 19 13](https://user-images.githubusercontent.com/46760897/61302654-8e06a080-a7bc-11e9-8117-63dfbcd7255e.png)

Filters enabled in AdGuard Nightly for macOS Catalina Beta:

English AdGuard ( base ) filter
Spyware AdGuard filter
Social Networks AdGuard filter
Annoyances AdGuard filter
Russian AdGuard filter
Spanish/Portuguese AdGuard filter

**Comment by Alex-302** [comment]
not a trackers.
You can block `||google.com^$third-party` if you hate google:)
