### ISSUE TITLE
http://www.ilovesmj.com - Incorrect blocking 

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3697]
Incorrect blocking on page: http://www.ilovesmj.com/medical-home
It's loads as a blank page.

<details>

![image](https://cloud.githubusercontent.com/assets/23258533/21032837/e56858fe-bdb4-11e6-8c27-c5832ad1fec7.png)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2016-10-10 21:30:17 +0000

Device: iPhone
Platform: iPhone OS
OS: 9.3.3
ID: FDB9CEA8-A12F-4269-9E0D-0F3A351CD4E2

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.86 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.27 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.1 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.25 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.31 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.3 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.78 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.65.30 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.51.95 Enabled=NO
ID=208 Name="Malware Domains" Version=1.0.48.97 Enabled=NO

</details>

Ticket ID(if exists): 1136604

**Comment by Alex-302** [comment]
Added
```
@@/rssButton.$domain=ilovesmj.com
```
