### ISSUE TITLE
studienwahl.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3701]
***Site***: http://www.studienwahl.de/
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21047129/7362e78e-be08-11e6-851d-3e02dffb7203.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21047158/946860a8-be08-11e6-8e64-648965123b9c.png)

***http://www.studienwahl.de/de/news/studieren/klausuren-online-schreiben01935.htm:***

![image](https://cloud.githubusercontent.com/assets/10995998/21047192/d48fe638-be08-11e6-8150-2a312248e2a2.png)

***http://www.studienwahl.de/de/chorientieren/orientieren068.htm:***

![image](https://cloud.githubusercontent.com/assets/10995998/21047209/e5f2321e-be08-11e6-8d1a-b9b28b64d1d9.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.2.70
 Spyware filter | 1.0.9.44
 Social media filter | 1.0.15.30
 Annoyances filter | 1.0.7.59
 German filter | 1.0.29.18
 Mobile ads filter | 1.0.6.18
 Safari filter | 1.0.1.81

**Comment by Alex-302** [comment]
Added to German filter
```
studienwahl.de##div[id^="ad_"]
```
