### ISSUE TITLE
ebz-business-school.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3705]
***Site***: http://www.ebz-business-school.de/
***Description***: Cookie notice.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21047637/4c9eed7a-be0b-11e6-8547-2f796aa1dcaa.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.2.70
 Spyware filter | 1.0.9.44
 Social media filter | 1.0.15.30
 Annoyances filter | 1.0.7.59
 German filter | 1.0.29.18
 Mobile ads filter | 1.0.6.18
 Safari filter | 1.0.1.81

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
ebz-business-school.de###cooklay
```
