### ISSUE TITLE
daimler.com/de - Incorrect Blocking - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3706]
***Site***: https://www.daimler.com/de/
***Description***: Cookie notice is incorrectly blocked

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21047724/c101b12a-be0b-11e6-9eb6-d636b63d7876.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.2.70
 Spyware filter | 1.0.9.44
 Social media filter | 1.0.15.30
 Annoyances filter | 1.0.7.59
 German filter | 1.0.29.18
 Mobile ads filter | 1.0.6.18
 Safari filter | 1.0.1.81

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
||daimler.com/system/js/vendor/jquery-fancybox-pack.js
```
Please check

**Comment by danidoedel** [comment]
Yes that works. Thank you!

**Comment by danidoedel** [comment]
@Alex-302 It's back again...

**Comment by Alex-302** [comment]
replaced by
`daimler.com#%#document.cookie = "cookie_policy=true";`

**Comment by danidoedel** [comment]
@Alex-302 I have that message on my iPhone now. On my computer it's just fine.

**Comment by Alex-302** [comment]
They are use blocking scroll. If we hide it, the site will be locked.
