### ISSUE TITLE
www.tf-robots.nl - incorrect blocking

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3707]
Source report:
http://forum.xda-developers.com/showpost.php?p=70005728&postcount=1956

> got a little false positive on www.tf-robots.nl
> the hotdog menu("navigatie") is blocked by adguard.
> the button is there, but while adguard is active it doesn't open.

**Comment by seanl-adg** [comment]
This is strange, the problem is not reproduced with desktop browsers and mobile Samsung browser, but reproduced with mobile Chrome. `@@||tf-robots.nl^$elemhide,jsinject,content` resolves the problem but I can't find out the reason.

**Comment by ameshkov** [comment]
There're no ads there so I guess we can add this rule to mobile filter.

**Comment by seanl-adg** [comment]
Added :/
