### ISSUE TITLE
There should be a way to have specific rules for different product types

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3708]
Windows/Mac/Android/Extension rules could be slightly different.

For instance, Win/Mac/Android have `$$` rules support, while extension don't.

**Comment by ameshkov** [comment]
I propose doing it with a special "Hint" comment (inspired by the Oracle DB hints system) -- http://docs.oracle.com/cd/E25178_01/server.1111/e16638/hintsref.htm

"Hint" is a special comment, instruction to the filters compiler used on the server side.

### Hints syntax

```
!+ HINT_NAME1(PARAMS) HINT_NAME2(PARAMS)
```

Note, that you can apply multiple hints.

### `PLATFORM` and `NOT_PLATFORM` hints

Specify which platforms can apply this rule.

List of existing platforms:

* `windows` -- Adguard for Windows (https://filters.adtidy.org/windows/filters/2.txt)
* `mac` -- Adguard for Mac (https://filters.adtidy.org/mac/filters/2.txt)
* `android` -- Adguard for Android (https://filters.adtidy.org/android/filters/2.txt)

* `ios` -- Adguard for iOS (https://filters.adtidy.org/ios/filters/2.txt)
* `ext_chromium` -- Adguard browser extension for Chrome (https://filters.adtidy.org/extension/chromium/filters/2.txt)
* `ext_ff` -- Adguard browser extension for Firefox (https://filters.adtidy.org/extension/firefox/filters/2.txt)
* `ext_safari` -- Adguard browser extension for Safari (https://filters.adtidy.org/extension/safari/filters/2.txt)
* `ext_android_cb` -- Adguard Content Blocker (https://filters.adtidy.org/extension/android-content-blocker/filters/2.txt)

**Examples:**

This rule will work on Windows, Mac, and Android only:
```
!+ PLATFORM(windows,mac,android)
||example.org^
```

This rule will work on every platform except Safari extension, iOS, and Android content blocker:
```
!+ NOT_PLATFORM(ext_safari, ext_android_cb, ios)
||example.org^
```

**Comment by ameshkov** [comment]
@seanl-adg @Alex-302 need your feedback

**Comment by Alex-302** [comment]
Good idea.
Will `!+ NOT_PLATFORM` be visible only in repository and parsed by back-end, or it will remain as a comment in filter?

**Comment by ameshkov** [comment]
> Will !+ NOT_PLATFORM be visible only in repository and parsed by back-end, or it will remain as a comment in filter?

What do you prefer?

**Comment by Alex-302** [comment]
Currently, the search in filter editor works as filter, these comments will not shown. So no difference there.
But if classic search mode will be implemented, comments will be useful.

**Comment by ameshkov** [comment]
Let's then leave the comments intact.

**Comment by seanl-adg** [comment]
I haven't seen much cases where manually annotating filter rules was necessary.

For `$$` and `$replace` rulues speak for itself without needing annotations. Filters compiler can detect and remove such rules for unsupported platforms.

For content blockers, Safari filter was being used for rules that are needed for such platforms.

It might be helpful for FF and Opera extension, as it can't receive JS rules from filters update. I've been not caring much about adding specific rules for FF and Opera.

**Comment by ameshkov** [comment]
> For $$ and $replace rules, they speak for themselves without needing annotations. Filters compiler can detect and remove such rules for unsupported platforms.

Yep, they still will.

> For content blockers, Safari filter was being used for rules that are needed for such platforms.

I still hope we can get rid of it one day.

**Comment by seanl-adg** [comment]
> Yep, they still will.

Is removing `$$` and `$replace` from backend still being happening? There were several reports like
`Cannot create rule from filter 2: ://api.audioaddict.com/v1/radiotunes/track_history/channel/*.json|$xmlhttprequest,replace=/(?:(?:(?<=\[)|\G)\{“ad”:[\s\S]*?“type”:“advertisement”\}(?:\,|(?=\]))|\,\{“ad”:[\s\S]*?“type”:“advertisement”\}(?=[\,\]]))//g, cause Unknown option: REPLACE` ?

>I still hope we can get rid of it one day.

We can remove it as soon as when this issue is settled. We can just add a section 
`!+ PLATFORM(ext_safari, ext_android_cb, ios)` at the end of each of filters.

**Comment by ameshkov** [comment]
> Is removing $$ and $replace from backend still being happening?

The script is rather stupid, it checks for substring `$replace`

**Comment by Alex-302** [comment]
@ameshkov please add `ext_ublock` and `ext_edge` to 
https://github.com/ameshkov

**Comment by ameshkov** [comment]
@Alex-302 done

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/5488
@ameshkov please add `ext_opera` to 
https://github.com/AdguardTeam/AdguardFilters/issues/3708#issuecomment-303155314

**Comment by ameshkov** [comment]
done
