### ISSUE TITLE
zp.today

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3710]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Блок рекламы 
http://zp.today/obschestvo/2314-zaporozhskie-deputaty-gotovy-soedinyat-serdca.html

Первые 3 секунды блока нет на сайте, но после он появляется
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21072904/8a0c2334-bed9-11e6-890b-3810d2c3276b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Вин
Browser: | Хром
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Adguard DNS: | None 
Stealth mode options(Windows) | null
Adguard filters: | Русский, Английский, Фильтр счетчиков и аналитики, фильтр виджетов, раздражителей

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1463527

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
|ws*://*$domain=zp.today
```

**Comment by F4z** [comment]
```
Adguard for Windows 6.1.298.1564
Filters: User, English, Spyware, Russian, German, Social Media, Annoyances, Experimental, Anti-Adblock Killer, Adblock polskie reguły
```
@Alex-302 it does not work for me, I still see these ads.
I think in Adguard for Windows this should be blocked by this rule - `||10root25.website^` but for some reason it does not work for me.
![image](https://cloud.githubusercontent.com/assets/11742596/21117425/e708fddc-c0b9-11e6-9ebe-e68a7f2efa67.png)

**Comment by Alex-302** [comment]
@F4z the seme. It is blocked by JS rule.

**Comment by ameshkov** [comment]
10root25.website uses known bad SSL certificate (StartCom issued after October 21).

Chrome beta already blocks access to domains with new startcom certificates.
However, it seems that Chrome release does not do it yet.

**Comment by F4z** [comment]
@Alex-302 I did not notice second fix, sorry.
Yes, with JS rule I do not have ads.

@ameshkov ok, thank you for this information.
So, if I understand correctly, Adguard for Windows does not block these websocket connections, because `10root25.website` uses bad SSL certificate, yes?

**Comment by ameshkov** [comment]
Yep, when Adguard considers SSL certificate invalid, it stops filtering for this domain and bypasses it as is, so that it's up to browser to handle it properly. It seems that we've implemented the StartCom&WoSign certs detection earlier than these changes were made to release Chrome version.

**Comment by ameshkov** [comment]
More info on the issue:
https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html

**Comment by F4z** [comment]
Ok, I understand.
Thank you for your answer.
