### ISSUE TITLE
tumejortorrent.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3711]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: tumejortorrent.com
* **Current behaviour**: random ad opens in a new window when you tap on any film

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/14153331/21072938/c6d90aba-beda-11e6-9832-27dbb11dc8be.png)
![image](https://cloud.githubusercontent.com/assets/14153331/21072939/ca9f4952-beda-11e6-9f5c-1beedc971414.png)

</details>

***Steps to reproduce the problem***:
1. go to tumejortorrent.com
2. tap anywhere

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Operating system: Android
Browser: Chrome
Adguard version: 2.8.76
Adguard mode (Android): VPN
Filtering quality (Android): High-quality
Adguard DNS: None
Adguard filters: 2, 3, 4, 14, 9, 11, 15

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1463025

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Aokromes** [comment]
it affects windows too, they have some heavy anti-adblocking scripts.

**Comment by Alex-302** [comment]
Added to English filter
```
tumejortorrent.com##.pub728x90
tumejortorrent.com###box-ads-tr
tumejortorrent.com#%#window.atob = function() { };
tumejortorrent.com$$script[tag-content="if (window.atob)"][max-length="3500"]
```
