### ISSUE TITLE
dn.se

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3712]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: pictures are blocked randomly
Original request here:
https://forum.adguard.com/index.php?threads/v2-8-58-high-quality-filtering-not-working.16566/page-2#post-116709

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/14153331/21073011/044b0fae-bedd-11e6-8e8d-ffaa8055e764.png)

</details>

***System configuration***

Operating system: Android
Browser: Chrome, Firefox 
Adguard version: 2.8.76
Adguard mode (Android): VPN
Filtering quality (Android): High-quality
Adguard DNS: None
Adguard filters: 2, 4, 14, 11, 15, 223

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1456058, requested HTTP log

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
Please check the ticket for more logs: 1456058

**Comment by Alex-302** [comment]
I need direct link.
The page looks differently
http://imagizer.imageshack.com/img921/7766/QXwOGo.png

**Comment by Xophile** [comment]
Hi again! 

Finally setup an account here since this issue really annoys me. Thanks for your support in advance! 

Well, the site is www.dn.se when using Firefox on Android 6.0.1 and a Samsung Galaxy S7 Edge. I receive the Grey areas on the front page and when scrolling down to read the news the size of the Grey area (= the "blocked" ad) is changing its height and then my browsing experience gets ready annoying. 

I hope you can verify it! 

Merry Christmas to you all!

**Comment by Alex-302** [comment]
answered on the forum

**Comment by vbagirov** [comment]
User still has the issue, soon he will provide more information and a screenshot.

**Comment by OlegSUP** [comment]
@vbagirov  User sent new logs (as discussed on forum). Time 11.46 am
ID:1456058
[debug (1).txt](https://github.com/AdguardTeam/AdguardFilters/files/884096/debug.1.txt)
