### ISSUE TITLE
http://www.aftonbladet.se/ - Missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3715]
Missed ad on page:
http://www.aftonbladet.se/

There is an big ad banner almost at the end of the webpage. The title of the ads banner is: AFTONBLADETS RABATTKODER

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/21078767/785ca208-bf83-11e6-8695-12aabeb8ceac.png)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2016-12-04 05:26:39 +0000
Device: iPhone
Platform: iOS
OS: 10.1.1
ID: A3D31A3C-5603-4742-B433-15301CBEC975

Locale: en
Region: se
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.80 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.47 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.32 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.82 Enabled=YES
ID=102 Name="ABPindo" Version=1.0.1.28 Enabled=YES
ID=223 Name="Fanboy's Swedish" Version=1.0.0.4 Enabled=YES

</details>

Ticket ID: 1459191

**Comment by Alex-302** [comment]
Not shown.
