### ISSUE TITLE
http://trinixy.ru/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3716]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Блокируется видео на сайте
http://trinixy.ru/138579-zhutkaya-tayna-moiseya-smotret-do-konca.html

Помогает отключение Русского фильтра

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21079662/499ac666-bfa1-11e6-94a6-56dc9e27810b.png)

</details>

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21079665/625bbcdc-bfa1-11e6-8961-e5dd4e65ddc6.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Вин. Расширение
Browser: | Хром
Adguard version: | 2.5.8
Adguard filters: | Русский фильтр, Английский фильтр, RU AdList

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1076701

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
