### ISSUE TITLE
CM Security 

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3717]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Не могут обновится антивирусные базы. Выдается ошибка о плохом интернет-соединении
**Помогает отключение Фильтра мобильной рекламы**
**Логи попросила**

https://play.google.com/store/apps/details?id=com.cleanmaster.security&hl=en

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21079830/a4e7d2d4-bfa6-11e6-9174-5c1154c06f67.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21079831/b1dc5a14-bfa6-11e6-9778-83c79db13b7c.png)

</details>

***Steps to reproduce the problem***:

+ Перейти в меню Антивируса
+ Нажать проверить обновления
+ Появится ошибка

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Андроид
Adguard version: | 2.8.76
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality 
Adguard DNS: | None 
Adguard filters: | Русский, Английский, Фильтр счетчиков и аналитики, Фильтр виджетов, Фильтр раздражителей, Фильтр мобильной рекламы

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1461043

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by vgavrish** [comment]
@Alex-302 лог 
[adguard (2).txt](https://github.com/AdguardTeam/AdguardFilters/files/648594/adguard.2.txt)
время 12-25

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||ups.ksmobile.net^$app=com.cleanmaster.security
```

**Comment by vgavrish** [comment]
В DNS режиме с фильтром DNS та же проблема
Лог нужен?

**Comment by Alex-302** [comment]
Нет, в ДНС исключил
```
ups.ksmobile.net
```

**Comment by Alex-302** [comment]
It is whitelisted properly, and works fine on my device.

**Comment by TPS** [comment]
What lists are you testing w/?  I use all, except acceptable ads & HTTPS, & still must have `@@||ups.ksmobile.net$important` put in manually, else I don't have virus definition updates for CM ___&___ CMAV.

**Comment by Alex-302** [comment]
try to leave only Adguard filters

**Comment by TPS** [comment]
If the filters I'm using are _builtin_ to AG-Android, wouldn't it be more correct for you to update this filter/exclusion, than me working around/unsubscribing from an _official_ filterlist?

**Comment by Alex-302** [comment]
I don't understand, what do you mean. The necessary exclusion is in the mobile filter few months.

**Comment by TPS** [comment]
IIUC, you asked me to use _only_ the filterlists from AdGuard.com (technically, now from AdTidy.org, IRC), but I use (almost) _all_ the lists via the ☑️s in `Settings: Adblocker`, as mentioned [above](https://github.com/AdguardTeam/AdguardFilters/issues/3717#issuecomment-285921602).  Those _all_ seem to be officially supported lists, then, right?

Then, using that combo, neither `@@||ups.ksmobile.net^$app=com.cleanmaster.security` nor `@@||ups.ksmobile.net^` is sufficient. `@@||ups.ksmobile.net$important` is ___required___ (or perhaps `@@||ups.ksmobile.net^$important`, though the builtin app-filtering doesn't generate _that_ from the builtin [log](https://github.com/AdguardTeam/AdguardForAndroid/issues/11)).

**Comment by Alex-302** [comment]
make it as specifiс for this app

**Comment by Alex-302** [comment]
If ups.ksmobile.net is excluded, it can't be blocked by another filter

**Comment by TPS** [comment]
> make it as specifiс for this app

There's a _lot_ of Cheetah Mobile apps, & adding more all the time, many of which use the virus defs w/ updates.  Is it practical to add so many via `$app=`?  Does `$app=` even handle multiple packages?  Or can AG-Android handle `$app=foo,app=bar,app=…`?
> If ups.ksmobile.net is excluded, it can't be blocked by another filter

Conceptually true, yet ***I*** get no virus def updates w/o `@@||ups.ksmobile.net$important` added to my user filters (though I added `ups.ksmobile.net` to user whitelist, also, after I determined  `@@||ups.ksmobile.net$important` _worked_).  Should AG-Android process exclusions differently based on `$important`?

**Comment by Alex-302** [comment]
ups.ksmobile.net is used also for spyware purposes. As I remember, they are collecting IMEI/ESN and current location.

**Comment by TPS** [comment]
So, it's in the `Spyware` filter & unexcluded from there?

**Comment by Alex-302** [comment]
it is in mobile filter

**Comment by TPS** [comment]
So, it's just blocked now, for that reason?  Then all is ok.  If *I* want it, I'll keep it unblocked myself.

Thanks for taking the time to track it down.  Maybe you should change the flags for this issue from <kbd>Incorrect Blocking</kbd><kbd>Resolved</kbd>→<kbd>Declined</kbd>.  It'll make things easier for those finding this, as I did.

**Comment by Alex-302** [comment]
Not sure. That rule helps me and user from T/N 1461043
I did not see  your log, maybe package name is different.
