### ISSUE TITLE
Please change the Wiltteri list (Finnish block list) to Juvander's Adblock List for Finland

### ISSUE THREAD

**Issue by TommiHynynen** [AdguardTeam/AdguardFilters#3718]
Wiltteri list for Finland is no longer updated and the new updated list is Juvander's Adblock List for Finland:

https://www.juvander.fi/site/ilpo/Home/tabid/127/EntryId/825/New-Adblock-filter-list.aspx
http://adb.juvander.net/Finland_adb.txt

**Comment by Alex-302** [comment]
But Finland_adb.txt contains only 700 strings, an old filter contains more than 3600.

**Comment by TommiHynynen** [comment]
Old filter is updated 16 May 2015 so it might contain old and useless rules. Juvander's list is updated quite regularly.

At the moment you can't add own filter list subscription in Adguard for Android or in Adguard for mac, and that's whyt it should be included in Adguard and looks like it's been there (http://www.juvander.fi/site/ilpo/Forums/tabid/139/forumid/23/threadid/3798/scope/posts/Default.aspx) but maybe it's removed in some update?

**Comment by Alex-302** [comment]
> At the moment you can't add own filter list subscription in Adguard for Android

but you can import this filter by URL(not the best solution, but..)

Could you ask Ilpo Juvander about an old filter? Is it still actual?

@ameshkov What should we do - append new(small)  filter to existing, or add new filter?(will not be available for android users)

**Comment by Alex-302** [comment]
Ok, got it.

**Comment by ameshkov** [comment]
@Alex-302 I guess we should make it available for all AG versions and make it default for Finnish users

**Comment by Alex-302** [comment]
@ameshkov What exactly am I have to do?
- add new filter and leave an old filter
- add new, and remove old

**Comment by ameshkov** [comment]
Add new and leave old filter untouched.

Eventually we will mark it deprecated.

**Comment by Alex-302** [comment]
@mmigi Please make you changes. Details are in PM.

**Comment by ameshkov** [comment]
@mmigi ping

**Comment by mmigi** [comment]
All is ok! *Juvander's Adblock List for Finland* filter has been added and it will be by default for Filnland.

**Comment by juvander** [comment]
Nice one 😀

And yes, this list is regularly updated as well based on feedback that I get 😀

**Comment by TommiHynynen** [comment]
Hi! Are you going to add Juvander's list to the Android version or replace Wiltteri with it any time soon?

**Comment by Alex-302** [comment]
@TommiHynynen 
https://github.com/AdguardTeam/AdguardForAndroid/issues/1225

**Comment by ameshkov** [comment]
Re-assigned that to v2.9 R2 patch so that it was released as soon as possible.
