### ISSUE TITLE
nintendosoup.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#37183]
`https://nintendosoup.com/the-chinese-pokemon-bootleg-everyone-praised-for-its-animations-reportedly-steals-user-data/`

Overlay annoyance while scrolling down.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
@adranger do you see any other popups on this site?
```
nintendosoup.com##.spu-box[data-box-id="5356"]
nintendosoup.com##.spu-bg
```

**Comment by adranger** [comment]
@Alex-302 your filters work and I don't see any other problem on that site.

**Comment by Alex-302** [comment]
I mean another popups(useful)

**Comment by adranger** [comment]
I don't think so. They also sell stuff, but I got to the "Checkout" page without any popup.

**Comment by Alex-302** [comment]
ok
