### ISSUE TITLE
http://www.sport-express.ru/

### ISSUE THREAD

**Issue by dtitbd** [AdguardTeam/AdguardFilters#3720]
<details>

![image](http://image.prntscr.com/image/d298c1e05a754a05820378c39c5e81f1.png)
</details>
1. Внизу шапки (слева направо): 1. Значки соц. сетей. 2. Кусочек рекламы. 

2. Пустое пространство от заблоченной рекламы под блоком с результатами.

И хотел спросить можно ли в какую-нибудь подписку добавить этот рейтинг игроков с Nissan?
В шапке небольшой, плюс на страницах матчей
Скрин:<details>

![image](http://image.prntscr.com/image/c6bcd89e58824d2bafd496b23da707c9.png)
</details>
Пример: http://football.sport-express.ru/matchcenter/256269/

***System configuration***

Information | value
--- | ---
Operating system: | Windows/Android
Browser: | Chrome
Adguard filters: | 

Фильтры
<details>

![image](http://image.prntscr.com/image/f99132bea6ec4114bf1ab8e2508115cf.png)
</details>

**Comment by Alex-302** [comment]
Соц кнопки - ссылки на блоги. Убираем только в том случае, если они слишком бросаются в глаза и занимают много места.Здесь же они встроены в другой блок.
Рекламу убрал. По остальному - в пользовательский фильтр:
```
sport-express.ru##.addmenu li.advertwww
sport-express.ru##.place_ratingAnnounce
football.sport-express.ru##.b-nissan_button
```
