### ISSUE TITLE
http://hentaichan.me/ - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3721]
http://hentaichan.me/ - missed ad
banner at the top of the page

<details>

![image1 2](https://cloud.githubusercontent.com/assets/23258533/21090355/d6a73b56-c047-11e6-9e46-48d9b3af6b72.png)

</details>

<details>
Application version: 1.1.1.54
Application lifetime: 1970-01-01 00:00:00 +0000
Device: iPad
Platform: iOS
OS: 10.2
ID: 75D81780-D089-44B5-A821-AF0E3036B276

Locale: uk
Region: ua
Optimazed enabled: NO

Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.89 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.47 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.32 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.44.13 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.19 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.82 Enabled=YES
ID=101 Name="EasyList" Version=1.0.65.47 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.70.63 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.70.76 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.70.77 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.70.65 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.67.62 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.67.32 Enabled=YES
</details>

</details>

Ticket ID: 1464567

**Comment by Alex-302** [comment]
fixed
