### ISSUE TITLE
https://regnum.ru - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3722]
Пропущена реклама на странице:
https://regnum.ru/news/economy/2216267.html

Рекламный баннер снизу и справа 

<details>

<img width="375" alt="image1 3" src="https://cloud.githubusercontent.com/assets/23258533/21090837/2200b8fe-c04b-11e6-9cf7-f782b51037a7.png">

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2016-11-08 18:27:40 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: B452ADB0-5CB4-4A36-84C5-35C136948929

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.91 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.27 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.4 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.29 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.43.71 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.6 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.78 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.70.12 Enabled=YES

</details>

Ticket ID: 1464993

**Comment by Alex-302** [comment]
fixed
