### ISSUE TITLE
http://m.zngirls.com - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3723]
http://m.zngirls.com - missed ad
banner at the bottom of the page

<details>

![image1 4](https://cloud.githubusercontent.com/assets/23258533/21090965/da690810-c04b-11e6-8dfb-560626cc1b59.png)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 2016-11-16 22:18:35 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: BF995343-4745-40C1-A395-DBA433894D9A

Locale: zh
Region: cn

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.54 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.39 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.20 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.81 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.70.67 Enabled=YES

</details>

Ticket ID:1464159

**Comment by Alex-302** [comment]
can't reproduce.
Could you check in chrome extension with simplified filters?
