### ISSUE TITLE
http://old.fishki.net/best/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3724]
Если включен "Adgurd" то имеются пересылки на сайт "Эхо Москвы", если не включен - то нет ссылок
Даже если взять пример статью про Слуцкого, то когда отключен Adgurd, даже через поиск не ищется статья на странице

Ссылка сайта: http://old.fishki.net/best/
Скриншоты прикрепил к письму

Мои параметры:
* Windows 7 x64
* Adguard в виде расширения у Chrome
* Используемые фильтры: Русский фильтр, Английский фильтр, RU AdList
* Dr.Web

<details>

![qip shot - screen 898](https://cloud.githubusercontent.com/assets/15856304/21091677/93e39e1e-c050-11e6-8164-b78485bb5fb1.png)

![qip shot - screen 899](https://cloud.githubusercontent.com/assets/15856304/21091679/951de6c2-c050-11e6-9051-597af87b4755.png)

**Comment by Alex-302** [comment]
Повторяется?
У меня не скрывает
http://imagizer.imageshack.com/img923/8817/vtHW45.png

**Comment by TomCruiseXZ** [comment]
Alex-302, 
1) проверь свой комп на вирусы
2) поставь чистый Chrome и одно расширение Adguard и на нём тести

**Comment by TomCruiseXZ** [comment]
Когда поправите ?

**Comment by evgeniy-ADG** [comment]
@Alex-302 не повторяется. в "популчрное" - только посты от пользователей, что с, что без.

**Comment by Alex-302** [comment]
Попроси тогда отключать фильтры по одному. Может удастся найти фильтр, который даёт такой результат.
