### ISSUE TITLE
pixiv.net

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdguardFilters#37250]
***Description***:

* **Current behavior**: 

<details><summary>Screenshot:</summary>

![pixiv01](https://user-images.githubusercontent.com/5698157/61603815-ad487680-ac71-11e9-92ef-7a5768c45fa1.png)

</details>

* **Expected behavior**: 

<details><summary>Screenshot:</summary>

![pixiv02](https://user-images.githubusercontent.com/5698157/61603876-f7315c80-ac71-11e9-896c-89fea5844fc3.png)

</details>

***Steps to reproduce the problem***:

1. Login pixiv.
1. Goto <https://www.pixiv.net/bookmark_add.php?type=illust&illust_id={any_picture_id}>.
1. Click ![image](https://user-images.githubusercontent.com/5698157/61603970-55f6d600-ac72-11e9-98e3-6d0f5af5a457.png) to bookmark picture.

***System configuration***

**Filters**

1. AdGuard Base filter
1. AdGuard Mobile Ads filter
1. AdGuard Annoyances filter
1. AdGuard Experimental filter
1. AdGuard Japanese filter

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 x64 1903
Browser:                               | Cent Browser
AdGuard version:                       | 7.1.2866 (CL 1.4.96)
Filters enabled:                       | Filters section all
AdGuard DNS:                           | None
Stealth mode options (Windows only)    |

![image](https://user-images.githubusercontent.com/5698157/61604280-7a9f7d80-ac73-11e9-899a-7f47ec95f7a5.png)

**Comment by Alex-302** [comment]
@bestpika What I see with AdGuard
<details>

![image](https://user-images.githubusercontent.com/8361299/61636654-b69c0800-ac9e-11e9-935f-c34c4d3968dc.png)

</details>
Which filter causes this issue?

**Comment by bestpika** [comment]
The `{any_picture_id}` please replace with any number.
Like <https://www.pixiv.net/bookmark_add.php?type=illust&illust_id=151566>.

**Comment by bestpika** [comment]
And I use AdGuard Home so the iframe's content can't show.

**Comment by Alex-302** [comment]
On my end it is blocked by `||pixon.ads-pixiv.net^` from Base filter.
Please open filtering log, reproduce an issue, enter `pixon.ads-pixiv.net` to search string and make screenshot.

**Comment by bestpika** [comment]
The `<iframe>` element not hidden is the main problem.

**Comment by Alex-302** [comment]
Is it after reproducing an issue? Do you use VPN/proxy?

**Comment by bestpika** [comment]
I do not use VPN/proxy.
I clean log before I click the add bookmark button.
Then I click it, I cannot see any request about `pixon.ads-pixiv.net`.

**Comment by bestpika** [comment]
So maybe the issue is AdGuard's issue?

**Comment by Alex-302** [comment]
I don't know. Could you please record HAR file?
https://toolbox.googleapps.com/apps/har_analyzer/

**Comment by bestpika** [comment]
I observed the browser's request.
After I click add to bookmark, the browser does not navigate to a new location.
So the target page is built by javascript (maybe fronted framework), so AdGuard does not capture any request.

**Comment by bestpika** [comment]
![image](https://user-images.githubusercontent.com/5698157/61853749-3a4c3380-aeef-11e9-97e3-47b4b6319f50.png)

**Comment by bestpika** [comment]
Right panel is target page.
I can't any AdGuard injection CSS like the left panel.

![image](https://user-images.githubusercontent.com/5698157/61854171-1c330300-aef0-11e9-975c-9a14f1b83a4f.png)

**Comment by Alex-302** [comment]
I need HAR

**Comment by bestpika** [comment]
After today's update (7.1.2872 CL 1.4.120), this problem is gone.

**Comment by Alex-302** [comment]
ok
