### ISSUE TITLE
vectorstock.com - iOS - Site blocked/won't load

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3725]
***Site***: https://www.vectorstock.com/
***Description***: Page is blocked.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21094535/ab87ebd6-c057-11e6-92d8-ed618a6f569c.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2
Browser: | Safari
Adguard version: | 1.1.2
Adguard driver (Windows): | -
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | -

Adguard filter | Version
--- | ---
English filter | 1.1.2.95
 Spyware filter | 1.0.9.47
 Social media filter | 1.0.15.32
 Annoyances filter | 1.0.7.63
 German filter | 1.0.29.21
 Mobile ads filter | 1.0.6.20
 Safari filter | 1.0.1.82

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||vectorstock.com^$domain=vectorstock.com
```
