### ISSUE TITLE
Finance Manager app 

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3726]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Можно убрать блок внизу приложения?
https://play.google.com/store/apps/details?id=com.finperssaver

Лог 
[adguard (1).txt](https://github.com/AdguardTeam/AdguardFilters/files/645727/adguard.1.txt)

Проблема в 12-46
Пыталась потыкать на ту область

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21096694/a004e72a-c069-11e6-81c3-4a8d08b3eb13.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Андроид
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
Adguard DNS: | None 
Adguard filters: | Русский, Английский, Фильтр счетчиков и аналитики, Фильтр виджетов, Фильтр раздражителей, Фильтр мобильной рекламы

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1212839

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня не выскакивает.
В логе только один запрос гугловой рекламы. Можно попробовать
```
@@||googleads.g.doubleclick.net/mads/gma?carrier=*&_package_name=com.finperssaver
```
**или**
```
||googleads.g.doubleclick.net/mads/gma?carrier=*&_package_name=com.finperssaver$empty
```
**или**
```
||googleads.g.doubleclick.net/mads/gma?carrier=*&_package_name=com.finperssaver$mp4
```
Но не думаю, что поможет.

**Comment by vgavrish** [comment]
Не помогло, но 

> мне этот блок не мешает,поэтому не принципиально

**Comment by Alex-302** [comment]
ну ок тогда, прикроем
