### ISSUE TITLE
All outgoing Bing links blocked

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#37273]
@planet0 commented on [Mon Jul 22 2019](https://github.com/AdguardTeam/AdguardForiOS/issues/1142)

> AdGuard blocks sites redirected through bing
> I hope that makes sense. I use Bing and after searching, if I select a link from the search results AdGuard blocks it. Whether it’s reddit, time, Gizmodo, whatever. Any site from my search results gets blocked. I’ve tried adding bing to my white list and have gotten the same results. Ditto if I add the site it’s linking to. I love the way it works on my iPhone XS, but this has been a reason to turn it off rather than keep it on

https://www.reddit.com/r/Adguard/comments/cg9wce/adguard_blocks_sites_redirected_through_bing/

Someone has mentioned that all links in the Bing search results are blocked in Safari.
Tried it myself and yes, it is blocked. Bing seems to link outgoing results as: www.bing.com/fd/ls/GLinkPing.aspx?IG=XXXXXX

### Steps to reproduce

1. Enable AdGuard in Safari
2. Search using bing.com
3. Tap on any search result

### Expected behavior

Go to website

### Actual behavior

AdGuard blocks outgoing link and user cannot view website.

**Comment by Alex-302** [comment]
```
!+ PLATFORM(ios, ext_safari, ext_android_cb)
||bing.com/fd/ls/
```
