### ISSUE TITLE
Liste FR unblocks ads in multiple apps

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#3727]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: Enabling Liste FR unblocks ads in some apps. 

Reproducible.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Videos:
https://drive.google.com/folderview?id=0B8faJCkSPmZ9MEEycE5mMTI3ZTA

Google Play links:
<details>

https://play.google.com/store/apps/details?id=fr.leboncoin

https://play.google.com/store/apps/details?id=mobi.infolife.eraser&hl=fr 

https://play.google.com/store/apps/details?id=com.lbe.parallel.intl

https://play.google.com/store/apps/details?id=com.pagesjaunes

</details>

***System configuration***

Information | value
--- | ---
Operating system: |Android 
Adguard version: | 2.8.76
Filtering quality (Android): | High-quality 
Adguard filters: | English, Spyware, Social media, Mobile, List FR, Anti-Adblock Killer | Reek
HTTPs filtering: | on

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 848734

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@seanl-adg please take a look
