### ISSUE TITLE
Add a validity checking for element hiding rules

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#3730]
**Current behaviour:** The rules, which are placed after invalid rule, are not working.
**Example of issue:**
https://forum.adguard.com/index.php?threads/resolved-missed-ad-on-extratorrent.17401/
**Screenshot:**
<details>

![image](http://i65.tinypic.com/9sw64y.jpg)
</details>

**Invalid rule:**

```
etmirror.com,etproxy.com,extra.to,extratorrent.cc,extratorrent.works,extratorrentlive.com,extratorrentonline.com##td > table[style*=border: 0px"]
```
table[style*=border: 0px"] - missed the first quotes

**Comment by ameshkov** [comment]
1. You can use nodejs and phantomjs to run an embedded browser and compile a CSS selector.
2. You can also detect `extended css` rules and validate them as well.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersCompiler #3](https://github.com/AdguardTeam/FiltersCompiler/issues/3) via [**ZenHub**](https://www.zenhub.com/)
