### ISSUE TITLE
video.i.ua - incorrect blocking

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#3731]
Блокируется видео, пример: http://video.i.ua/user/1632723/42590/228035/

![scrn-20161212195132](https://cloud.githubusercontent.com/assets/17948007/21108693/1b6f4396-c0a7-11e6-91aa-9258caa381f3.jpg)

 На это влияет "Русский фильтр", а конкретно правило: `||holder.com.ua^$third-party`
Выход из ситуации - исключение: `@@||holder.com.ua^$domain=video.i.ua`

**Comment by XX-J** [comment]
Проверил все 4 ПО-ОТДЕЛЬНОСТИ и 3 Ваших вместе: результат один - рекламы нет, но некоторые видеоролики стартуют не с первого раза (видимо в этом месте должна быть реклама), кроме одного правила отдельно: `@@||i.holder.com.ua/*.mp4$domain=video.i.ua`   -   видео нет (т.е. отдельно бесполезно).
 Т.к. правило, которое предложил я, по результату не отличается от Ваших 3-х, то зачем писать 3, если сгодится одно?

**Comment by Alex-302** [comment]
Правила нужно все вместе проверять.
Отличие в том, что с тремя правилами реклама не загружается, т.к. исключено только то, что необходимо для работы плеера.
Можете скинуть пару ссылок на страницы, где видео не сразу запустилось? Желательно выключить вручную добавленные правила для этого сайта и обновить фильтр.

**Comment by XX-J** [comment]
Я на этом видеосервисе посмотрел не больше 40 видеороликов и НИ В ОДНОМ НЕ УВИДЕЛ ВИДЕОРЕКЛАМЫ - будь-то у меня выключенным Adguard или добавлено моё правило-исключение.

 Протестировал с выключенными плагинами: Браузер Pale Moon v26.5 (WinXP), Flash v23.0.0.207, Java v1.7.0.101, ВСЕ ПЛАГИНЫ ОТКЛЮЧЕНЫ (браузер перезапущен) - всё равно некоторые видео стартуют не с первого раза. Причём это не зависит от конкретных видеороликов, а спонтанно; т.е. любой ролик может загрузиться с первого раза, а может со второго, третьего и т.д.
 Думаю причина в браузере.

 Пример: [Жук](http://video.i.ua/user/1632723/42590/228034/)
 1) Первая загрузка:
![scrn-20161213193532](https://cloud.githubusercontent.com/assets/17948007/21182180/ce2a21ba-c212-11e6-8415-f41eafb99174.jpg)

 2) Вторая загрузка:
![scrn-20161213193656](https://cloud.githubusercontent.com/assets/17948007/21182195/dc3f098c-c212-11e6-868c-8788229504a9.jpg)

 3) На третьей ролик начал проигрываться:
![scrn-20161213193743](https://cloud.githubusercontent.com/assets/17948007/21182208/ea3bd4fc-c212-11e6-9f14-dd11aba2349b.jpg)

**Comment by Alex-302** [comment]
C расширением повторил, но исключение не помогает
http://imagizer.imageshack.com/img921/9607/ByRYEN.png
иногда видео не стартует даже с выключенной фильтрацией.

**Comment by XX-J** [comment]
> иногда видео не стартует даже с выключенной фильтрацией.

Вот и я о том-же.

Проверил ещё в Google Chrome v44.0.2403.157:
   С ВКЛючённым Adguard на замершем воспроизведении появилась метка "Реклама" вместо кнопки "Старт/Пауза", слева внизу:
![scrn-20161215174013](https://cloud.githubusercontent.com/assets/17948007/21229059/55ac1790-c2f1-11e6-810c-77dd023d045a.jpg)

   С ВЫКЛюченным Adguard'ом поведение САйТА не отличается от такого-же в Pale Moon.

Думаю это проблема САЙТА, а не фильтров, Adguard'a и уж тем более браузеров. Если Вы считаете также, то на этом тему можно закрыть...

**Comment by Alex-302** [comment]
Выждем пока. Если сам плеер глючит, то я не удивлюсь, т.к. на вопрос про защиту HTTPS(хотя бы для почты), они ответили, что в этом нет необходимости:)
