### ISSUE TITLE
Unblocking Google Tag Manager

### ISSUE THREAD

**Issue by gurgun-dayioglu** [AdguardTeam/AdguardFilters#37322]
Related: https://github.com/disconnectme/disconnect-tracking-protection/issues/31

Google says GTM isn't involved in any kind of tracking so some of the list maintainers such as Disconnect stopped blocking them. Since it doesn't track any user data it should not be blocked.

Link: https://support.google.com/tagmanager/answer/9323295#data
> ### Data collected by Google Tag Manager
> 
> In order to monitor system stability and performance, Google Tag Manager may collect some aggregated data about tag firing. This data does not include user IP addresses or any user-specific identifiers that could be associated with a particular individual. Other than data in standard HTTP request logs, all of which is deleted within 14 days of being received, Google Tag Manager does not collect, retain, or share any information about visitors to our customers’ properties, including page URLs visited. Learn more about our use of Google Tag Manager data in our terms of service.

**Comment by gurgun-dayioglu** [comment]
**To better clarify:**
[Here](https://kb.adguard.com/en/general/adguard-filter-policy#what-shall-be-blocked-with-this-filter), AdGuard's Policies state the following for the Tracking Protection filter:
> This filter shall block all counters that collect personal data of users.

As far as Google says, no personal info is collected and GTM is important for websites to function. Even Ghostery has them in their Essential category now. So as long as no data is collected it should not be included in the Tracking Protection list.

**Comment by ameshkov** [comment]
By "do not collect" they state that they do not "save" the data. IMO, the fact that the data is sent to their servers and interpreted there is enough to categorize it as a third-party tracker. Moreover, GTM's primary purpose is to load all kinds of tracking and ad scripts.

Although, I can understand why Ghostery categorized it not as a tracker, and they also have a point. However, we are not as flexible as they are.

If we had multiple tracking protection filter lists (for instance, "tracking protection and paranoid tracking protection), we would have added GTM to the latter. It's likely that at some point we'll do it, but not today.

@AdguardTeam/filters-maintainers FYI.
