### ISSUE TITLE
outlook.live.com

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardFilters#37327]
Annoying ads bar (in the right) in outlook for web is not blocked (even though in previous filters it did)

![Captura de Pantalla 2019-07-23 a la(s) 10 47 37](https://user-images.githubusercontent.com/46760897/61717477-ab091980-ad50-11e9-9ea7-ad189f631aa5.png)

Filters enabled in AdGuard Nightly for macOS Catalina Beta:

English AdGuard ( base ) filter
Spyware AdGuard filter
Social Networks AdGuard filter

Annoyances AdGuard filter
Spanish/Portuguese AdGuard filter
Mobile Ads AdGuard filter

Safari AdGuard filter
Experimental AdGuard filter
Simplified Domain Names AdGuard filter

**Comment by Alex-302** [comment]
LucasDiTomase It is hidden on my end by Annoyances filter:
`outlook.live.com##div[aria-label="Navigation pane"][data-max-width] ~ div[class^="_3_"]:last-child`
If you know how to do it, please check this selector in developer tools:
`div[aria-label="Navigation pane"][data-max-width] ~ div[class^="_3_"]:last-child`

**Comment by LucasDiTomase** [comment]
Hi. I can confirm that rule is enabled in my AdGuard annoyances filter, but it is not working in my Safari. Could you confirm if you are using Safari or another browser? Maybe Safari in the latest beta version could be the problem?

![Captura de Pantalla 2019-07-23 a la(s) 11 55 45](https://user-images.githubusercontent.com/46760897/61722534-fb38a980-ad59-11e9-964d-55a0aa5ec37c.png)
 
![Captura de Pantalla 2019-07-23 a la(s) 11 53 53](https://user-images.githubusercontent.com/46760897/61722476-e5c37f80-ad59-11e9-873a-b936ef4a61d4.png)

**Comment by Alex-302** [comment]
I am using MacOS Mojave, and that element is hidden(AdGuard for Mac and AdGuard for Safari).

**Comment by LucasDiTomase** [comment]
Thanks for the answer. Given that I ended up blocking that element manually I will close this issue. I don't know why the default annoyances rules won't hide the bar in my Mac but it is fixed now, so thanks.

**Comment by Alex-302** [comment]
ok.

**Comment by LucasDiTomase** [comment]
I can´t comment on my previous issue #38880 

To @Alex-302 , the rule you mentioned 

outlook.live.com##div[aria-label="Navigation pane"][data-max-width] ~ div[class^="_3_"]:last-child 

is not blocking that ad bar on my end, and like I said, I think it´s because of language translation issues of the rule ( especifically the 'Navigation pane' part which in my spanish browser has different class name ).

The rule that @krystian3w proposed 

outlook.live.com##div[aria-label][data-max-width] ~ div[class^="_3"]:last-child 

is working for me and it´s virtually the same rule that you are suggesting, except it does not have the language issue and that way it is working on my end. 

Why not add that one rule instead? Please.

Thanks.

**Comment by Alex-302** [comment]
> especifically the 'Navigation pane' part which in my spanish browser has different class name

which name?

**Comment by Alex-302** [comment]
ok, changed

**Comment by LucasDiTomase** [comment]
Thank you very much :)
