### ISSUE TITLE
cnews.ru - Adblock Killer

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3734]
***Description***: Adblock Killer on the website:
http://www.cnews.ru/payment

Screenshot:
<details>

![screen shot 2016-12-13 at 02 02 42](https://cloud.githubusercontent.com/assets/17504743/21121987/3a268886-c0d8-11e6-8c56-20d3a445da97.png)
</details>

***System configuration***

Information | value
--- | ---
Operating system: | Microsoft Windows NT 6.1.7601 Service Pack 1 (Reproduced on Mac)
Browser: | Chrome
Adguard version: | 6.1.258.1302 (Reproduced with the last version)
Adguard driver (Windows): | TDI
Stealth mode options(Windows) | "BlockThirdPartyCookies": true,  "BlockThirdPartyCookiesPeriodMin": 30,  "BlockFirstPartyCookies": false,  "BlockFirstPartyCookiesMin": 2880,  "DisableThirdPartyCache": true,  "BlockWebRtc": true,  "BlockBrowserPushApi": false,  "BlockBrowserLocationApi": true, "RemoveXClientDataHeader": true,  "HideSearchQueries": true,  "SendDoNotTrackHeader": true,  "RemoveRefererFromThirdPartyRequests": false,  "HideUserAgent": false,  "CustomUserAgent": null,  "CustomReferer": null,  "HideIp": false, "CustomIp": "209.141.53.254"
Adguard filters: | Reproduced with English, Spyware, Social media, Annoyances, Russian, Experimental, Adblock Warning Removal List, Anti-Adblock Killer

Ticket ID(if exists): 1465210

**Comment by ministr91** [comment]
Плагиат! Я уже писал об этом, нефиг тырить темы

**Comment by Alex-302** [comment]
Fixed.
