### ISSUE TITLE
royal.uk

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3736]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
На сайте появляется уведомление об использовании куки-файлов

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21132300/eaf2d14a-c11b-11e6-8eb3-c50b9d0a2fa5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Вин
Browser: | Хром
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard DNS: | None 
Stealth mode options(Windows) | null
Adguard filters: | Русский, Английский, Фильтр счетчиков и аналитики, Фильтр виджетов, Фильтр раздражителей

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1419169

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
royal.uk###sliding-popup
```

**Comment by adranger** [comment]
@Alex-302 has this rule been removed?

[https://www.royal.uk/new-zealand](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.royal.uk/new-zealand)
