### ISSUE TITLE
http://www.theatlantic.com - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3737]
http://www.theatlantic.com/please-support-us/?next=http%3A%2F%2Fwww.theatlantic.com%2Fhealth%2Farchive%2F2016%2F06%2Fi-stopped-showering-and-life-continued%2F486314%2F%3Futm_source%3Datlfb#seen

<details>

![file_000](https://cloud.githubusercontent.com/assets/15856304/21140454/cf50a3b6-c140-11e6-82c1-10f786071ccd.png)

Application version: 1.1.2.24
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 0E76C3BD-9171-421D-B4E8-9DAA305D8E09

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.75 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.45 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.31 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.61 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.19 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.82 Enabled=YES

**Comment by Alex-302** [comment]
@seanl-adg you can reproduce it on Andoid oк with mobile user agent(don't use js and CSS rules for iOS issues)

**Comment by seanl-adg** [comment]
@Alex-302 Could you check if this resolves the issue with Safari content blocker?

**Comment by Alex-302** [comment]
@seanl-adg sometimes their script triggers even with AG for Windows.

**Comment by seanl-adg** [comment]
I haven't seen an actual block screen yet, but I confirm that `Modernizr["blocker-enabled"]` returns true in rare occasions. With AG for Windows there will be no problem because of $$ rule, so I'll investigate this later.

**Comment by ameshkov** [comment]
People say the issue is still present in iOS. It is now even worse since they put a hard anti-adblock script on the website.

**Comment by Alex-302** [comment]
@ameshkov I can't reproduce it on iOS+Adguard DNS.
Which filters that people are using?

**Comment by ameshkov** [comment]
@Alex-302 I wonder could it be that the anti-adblock is for US users only?

**Comment by Alex-302** [comment]
Tested with TunnelBear. I think adblock detection is caused by third-party filters.

**Comment by ameshkov** [comment]
Ok then
