### ISSUE TITLE
Wolf on the Farm app

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3738]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Баннеры 
https://play.google.com/store/apps/details?id=com.nomoc.wolfonfarm

Лог: 
[debug (12).txt](https://github.com/AdguardTeam/AdguardFilters/files/648983/debug.12.txt)

> очистил кеш и данные, включил логирование https, воспроизвел баннерыв игре 2016.12.13 в 14:03

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21141267/e53bd2b4-c144-11e6-8f90-c3977f7bcbe5.png)
 
еще скрин
http://s8.hostingkartinok.com/uploads/images/2016/12/46eed560e7f787b9dc046eb9c7d48890.png
</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android
Adguard version: | 2.8.76
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
Adguard DNS: | None 
Adguard filters: | [ 2, 3, 14, 1, 11 ]

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1465507

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в мобильный:
```
||crosspromo*.qplaze.com/PushCampaignXMLOut.php
```
пусть отпишется, т.к. второй баннер не появился.

**Comment by flydvorkin** [comment]
Обновил фильтры, перезапустил защиту.
Реклама осталась.

при запуске игры:
https://drive.google.com/file/d/0BxPpQaqFWSy6ME5ZVFlJMlV4Ym8/view

в процессе игры:
https://drive.google.com/file/d/0BxPpQaqFWSy6VzJ3ZHd5akZYWlE/view

**Comment by Alex-302** [comment]
@flydvorkin так рано ещё:) Нужно час-полтора ждать, если обновлять фильтры. Либо в пользовательский фильтр скопировать.

**Comment by flydvorkin** [comment]
понял, огонь! :-)

**Comment by flydvorkin** [comment]
Ну вот если брать 1-ый скрин старта игры, то ушел один центральный баннер. Нижний остался.
А самое главное: 2-й скрин - игровой процесс, баннер внизу остался.

**Comment by Alex-302** [comment]
@flydvorkin у меня второго баннера нет. Что открывается при его нажатии? Есть ли этот баннер при отключении интернета?

**Comment by Alex-302** [comment]
Без фильтрации у меня баннер повторился, со значком гугло-рекламы. Блокируется даже без фильтрации.

**Comment by flydvorkin** [comment]
новый отчет (в приложении выслал тоже с приложенными логами):
при старте есть нижний баннер с яндекс браузером. При тапе по нему через гуглохром переход в маркет на страницу яндекс-браузера.
В игровом процессе - внизу банер.
При тапе по нему - гуглохром в котором на секунду в адресной строке что-то типа googleads...чтототам и переход на целевой рекламный сайт.
время воспроизведения: 21:26
логирование http на момент воспроизведения - включил.
Перед воспроизведением очистил кеш и данные приложения.

П.С. при отключенном интернете (выкл вифи, выкл сотовый инет) рекламы нет.

**Comment by flydvorkin** [comment]
https://drive.google.com/file/d/0BxPpQaqFWSy6dEt5RElwLURpcnM/view
https://drive.google.com/file/d/0BxPpQaqFWSy6cjBwWTdGU2swbVU/view

**Comment by flydvorkin** [comment]
может блокирнуть
googleads.g.doubleclick.net
?

**Comment by Yana-SUP** [comment]
@Alex-302 посмотрите, пожалуйста

**Comment by Alex-302** [comment]
ок
@flydvorkin 
попробуйте удалить правила из пользовательского фильтра и добавить
```
||crosspromo*.qplaze.com^$app=com.nomoc.wolfonfarm
```

**Comment by Alex-302** [comment]
Добавил.
