### ISSUE TITLE
http://www.ugorod.kr.ua/ - ads on the local news site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3739]
![image](https://cloud.githubusercontent.com/assets/15856304/21143206/5fe0c606-c14e-11e6-8467-d795bb6d7c8b.png)

<details>

Application version: 1.1.1.54
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 14F70EE1-7C80-4D88-8D19-7F340CB6EB31

Locale: ru
Region: ua

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.1 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.48 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.34 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.70 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.44.22 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.21 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.83 Enabled=YES
ID=101 Name="EasyList" Version=1.0.65.54 Enabled=YES

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||static.ugorod.ua/cache/biz_banners/
ugorod.kr.ua##.block-banner

```
