### ISSUE TITLE
Update ABP Vietnamese link

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3740]
Hi developer, you should update ABPVN list (abpvn.com)
ABPVN had update new link filter.

Link filter: http://abpvn.com/filter/abpvn-bqcLEp.txt
Or abp:subscribe?location=http://abpvn.com/filter/abpvn-bqcLEp.txt&title=ABPVN%20List

1464462

**Comment by Alex-302** [comment]
Done
