### ISSUE TITLE
icefilms.info - Incorrect Blocking

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#3741]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Adguard blocks useful content, also there is no Assistant there
* **Current behaviour**:  http://giphy.com/gifs/l3vRhYYxjK3OZgunC

***System configuration***

Information | value
--- | ---
Operating system: | Mac, Windows
Adguard filters: | English, Spyware, Social media, Annoyances, Russian

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1427697

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
```
icefilms.info###buttons > #list
```
replaced by
```
icefilms.info###buttons > #list > div[style="width:300px; float:left; "]
```
