### ISSUE TITLE
Moshi.com - Login blocked (AdGuard Social Media filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#37423]
### Affected site:
`https://www.moshi.com/`

### Issue:
Login is blocked.

### How to reproduce:
1 - Click on the "**MENU**" button, in the top left corner.
2 - Click on "**Login / Create an Account**".

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* AdGuard Social Media filter

### Problem rule:
`||apis.google.com/js/platform.js$third-party`

### Possible fix:
`@@||apis.google.com/js/platform.js$third-party,domain=moshi.com`

### Other problem filters (Referece only):
* Fanboy's Annoyance List
* Fanboy's Social Blocking List
https://github.com/ryanbr/fanboy-adblock/issues/1113/

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.6.0.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by AdamWr** [comment]
Fixed.
Thank you.
