### ISSUE TITLE
wagnardsoft.com - Ad leftover - Ad post

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3742]
***Site***: http://www.wagnardsoft.com/ and http://www.wagnardsoft.com/forums/viewtopic.php?f=5&t=706&sid=d37cffd3d12faa70dcf1077d84d77693
***Description***: Ad leftover and ad post in forums.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21174481/b7acdaa2-c1dd-11e6-9c56-28ca3ec5d898.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21174451/7fe75390-c1dd-11e6-89a3-e40b4a1c1e06.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.9
 Spyware filter | 1.0.9.52
 Social media filter | 1.0.15.41
 Annoyances filter | 1.0.7.77
 German filter | 1.0.29.28
 Mobile ads filter | 1.0.6.23
 Safari filter | 1.0.1.85

**Comment by Alex-302** [comment]
Added to English filter
```
wagnardsoft.com###page article[class^="block block-block"][-ext-has="script:contains(google)"]
wagnardsoft.com###page-body div.post:not([class*="has-profile"])
```
