### ISSUE TITLE
lawdepot.co.uk

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3743]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
На сайте появляется уведомление об использовании куки-файлов

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21176215/6001fc22-c1ee-11e6-85f3-11430ed74f8a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Вин
Browser: | Хром
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard DNS: | None 
Stealth mode options(Windows) | null
Adguard filters: | Русский, Английский, Фильтр счетчиков и аналитики, Фильтр виджетов, Фильтр раздражителей

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1419169

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
lawdepot.co.uk#$#html { margin-top: 0px!important; }
lawdepot.co.uk##.wbUKCookies
```
@vgavrish лучше на английском создавать, а то у нас тут помощнег есть, по-русски не понимает)
