### ISSUE TITLE
weltbild.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3744]
***Site***: https://www.weltbild.de/
***Description***: Cookie notice at the top.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21176297/611707ea-c1e6-11e6-994b-974ab5b794eb.png)

</details>

***Rule for Annoyance filter***: `weltbild.de##.cookie-hint`

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.9
 Spyware filter | 1.0.9.52
 Social media filter | 1.0.15.41
 Annoyances filter | 1.0.7.77
 German filter | 1.0.29.28
 Mobile ads filter | 1.0.6.23
 Safari filter | 1.0.1.85

**Comment by Alex-302** [comment]
Added
