### ISSUE TITLE
Currently blocking some Push Notifications in Chrome

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardFilters#37453]
@planet0 commented on [Wed Jul 03 2019](https://github.com/AdguardTeam/AdguardForMac/issues/550)

In the last month or so, I've noticed that I am no longer getting Push Notifications from Facebook in Google Chrome. This used to work fine beforehand alongside AdGuard, so there has been a change and I'm not sure where to really get it back to how it was before.

Push API is **not** blocked in Stealth Mode.
Sites like reddit.com are still having Push Notifications working.

Also, Facebook thinks Chrome Notifications cannot be enabled via their website either. See: https://www.facebook.com/settings?tab=notifications and under 'Browser'. The switch cannot be toggled 'on', or if it is on from before using AdGuard, it still doesn't work regardless and may revert back to the 'off' position.

A filter rule or stealth mode setting is preventing Facebook and Instagram from using Push Notifications. Other websites are fine.

### Steps to reproduce

1. Try to enable Push Notifications on Facebook and Instagram desktop websites after logging in (Both Facebook and Instagram ask you for notification permission after logging in for the first time).

### Expected behavior

Chrome allows notifications on the browser, and Push Notifications come through

### Actual behavior

Chrome allows notifications on the browser, but Push Notifications don't come through. Disable or quit AdGuard and reproduce, everything works fine.

<details><summary>Screenshot:</summary>

<img width="775" alt="Screen Shot 2019-07-03 at 9 43 54 am" src="https://user-images.githubusercontent.com/46271764/60553550-188be080-9d77-11e9-8ccd-69a8db3088d6.png">

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59): AdGuard 2.0.6.560 nightly, Chrome Version 75.0.3770.100 (Official Build) (64-bit)
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners): None

---

@planet0 commented on [Sat Jul 06 2019](https://github.com/AdguardTeam/AdguardForMac/issues/550#issuecomment-508889788)

It's also happening for Google Drive, where notifications fail to turn on.

<img width="569" alt="Screen Shot 2019-07-06 at 12 09 33 pm" src="https://user-images.githubusercontent.com/46271764/60750115-38294000-9fe7-11e9-8d4a-108f3f3453b2.png">

<img width="360" alt="Screen Shot 2019-07-06 at 12 09 40 pm" src="https://user-images.githubusercontent.com/46271764/60750116-3eb7b780-9fe7-11e9-8781-3e8c121a11a0.png">

---

@ameshkov commented on [Mon Jul 08 2019](https://github.com/AdguardTeam/AdguardForMac/issues/550#issuecomment-509154255)

Hm, can you reproduce it here?
https://web-push-book.gauntface.com/demos/notification-examples/

---

@planet0 commented on [Mon Jul 08 2019](https://github.com/AdguardTeam/AdguardForMac/issues/550#issuecomment-509169662)

It seems to work for that page, and it still is working for Reddit. Not for Facebook, Instagram and Google Drive as for now.

---

@zzebrum commented on [Wed Jul 17 2019](https://github.com/AdguardTeam/AdguardForMac/issues/550#issuecomment-512289701)

the switch indeed can't be toggled on. it shows this:
<details>

![image](https://user-images.githubusercontent.com/44832195/61384225-db683800-a8b8-11e9-867b-db89b3ca0ca2.png)

</details>

and even if I enable notifications by that steps above, the switch still looks disabled on FB settings page. Also, AdGuard disabled on my side too :) 
@planet0  Can you try the same thing for google drive, please?

---

@planet0 commented on [Thu Jul 18 2019](https://github.com/AdguardTeam/AdguardForMac/issues/550#issuecomment-512578834)

> Can you try the same thing for google drive, please?

Hi @zzebrum, I'm not sure what to try - Chrome already is set to allow for facebook.com and drive.google.com when I was trying to enable notifications on both sites. If I quit AdGuard and relaunch the browser, then the switch is enabled and notifications come through for Facebook, and Google Drive can enable notifications again.

---

@planet0 commented on [Sat Jul 20 2019](https://github.com/AdguardTeam/AdguardForMac/issues/550#issuecomment-513439422)

Adding `@@||facebook.com^$document`, `@@||instagram.com^$document` and `@@||drive.google.com^$document` allows the notifications to be turned on and work, so I'm trying to figure out what exactly inside AdGuard is causing this issue.

Excluding stealth didn't work so far, so it's not Stealth Mode related. It could be a particular filter rule.

---

@planet0 commented on [Sat Jul 20 2019](https://github.com/AdguardTeam/AdguardForMac/issues/550#issuecomment-513440025)

Okay, figured it out. It's related to a rule in AdGuard Annoyances Filter, for `$$link[rel="manifest"]`.

It seems that these sites need this HTML element in order to have Push notifications working.
What's the best way to resolve this @ameshkov, @TheHasagi & @zzebrum? Was there a reason this was added to the Annoyances Filter?

**Comment by TPS** [comment]
Is this the explanation for the (base) rule?  _(It's probably my most activated content rule.)_
>! Suppressing PWA "Add To Home screen" annoyance
> ! Limit it to mobile versions only
> ! causes some issues: https://github.com/AdguardTeam/AdguardForMac/issues/550

Or is it something else?  The formatting in that list is… challenging.

**Comment by ameshkov** [comment]
Well, in order to implement the native "Add to Home Screen" feature the website needs to add a link to the "manifest" to its code. AdGuard removes that link, hence no "Add to Home screen" annoyances.
