### ISSUE TITLE
np-coburg.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3745]
***Site***: http://www.np-coburg.de/
***Description***: Various ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21176520/652e0f12-c1e7-11e6-8248-d17b4920697d.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21176547/8aa9def6-c1e7-11e6-9a2b-0738801c5223.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21176567/9de6b8b8-c1e7-11e6-8d3a-3ff3a39164b0.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21176580/ad1b4b6e-c1e7-11e6-8a44-8b9a1e3b3f21.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21176594/bffcf9f8-c1e7-11e6-83b8-c5f1846db14b.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21176610/d0f4fb0c-c1e7-11e6-9c0d-1fadc7b22a85.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21176624/df85ea50-c1e7-11e6-9b41-763264ce3db9.png)

</details>

***Possible rules***: 
`np-coburg.de##div[id*="werb"]`
`np-coburg.de###internbox`

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.9
 Spyware filter | 1.0.9.53
 Social media filter | 1.0.15.41
 Annoyances filter | 1.0.7.77
 German filter | 1.0.29.28
 Mobile ads filter | 1.0.6.23
 Safari filter | 1.0.1.85

**Comment by Alex-302** [comment]
Added to German filter
```
np-coburg.de##.right.group#internbox
np-coburg.de##div[id*="_werb"]

```
