### ISSUE TITLE
wiesentbote.de - Ad - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3747]
***Site***: http://www.wiesentbote.de/
***Description***: Ad and Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21178047/15a45684-c1ee-11e6-8c88-bc728e8912ef.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21178041/074f1024-c1ee-11e6-9869-b3c0ae81a625.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.9
 Spyware filter | 1.0.9.53
 Social media filter | 1.0.15.41
 Annoyances filter | 1.0.7.77
 German filter | 1.0.29.28
 Mobile ads filter | 1.0.6.23
 Safari filter | 1.0.1.85

**Comment by Alex-302** [comment]
to German
wiesentbote.de##.sidebar-content > div#advanced_text-5
to annoyances
wiesentbote.de###footer-widgets
