### ISSUE TITLE
extreme.pcgameshardware.de - Ad leftover - Ad post

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3748]
***Site***: http://extreme.pcgameshardware.de/prozessoren/462291-ich-weiss-nicht-mehr-weiter-hilfe.html
***Description***: Ad leftover and ad post in forums.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21178483/0b754194-c1f0-11e6-85e8-7ec2861b6039.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21178449/ebb094c6-c1ef-11e6-94c8-a5ea6ffc4a35.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.9
 Spyware filter | 1.0.9.53
 Social media filter | 1.0.15.41
 Annoyances filter | 1.0.7.77
 German filter | 1.0.29.28
 Mobile ads filter | 1.0.6.23
 Safari filter | 1.0.1.85

**Comment by Alex-302** [comment]
Added to German filter
```
extreme.pcgameshardware.de###post_rec
extreme.pcgameshardware.de##.floatcontainer.doc_header#header
```
