### ISSUE TITLE
thunderbirdclub.de/forum - cannot whitelist the site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3751]
1. website: thunderbirdclub.de/forum
2. I've simply added „https://thunderbirdclub.de“ to the whitelist. That didn´t work at all. When I add „thunderbirdclub.de“ to the whitelist, I see a blank space instead of the adds.
3. Screenshot #1 with Adguard enabled but domain whitelisted and #2 with Adguard disabled.

<details>

1
![bildschirmfoto 2016-12-14 um 00 04 06](https://cloud.githubusercontent.com/assets/15856304/21191102/c3f3202e-c22c-11e6-99bb-5368d725fc6a.jpg)

2
![bildschirmfoto 2016-12-14 um 00 04 54](https://cloud.githubusercontent.com/assets/15856304/21191111/c85ab758-c22c-11e6-9d40-737b0cf9c8d5.jpg)

</details>

Filters
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21191182/01ab4478-c22d-11e6-8b6b-6f19d52665b9.png)

**Comment by Alex-302** [comment]
Confirmed. But it is not filters issue. Exclusion works as expected on Windows.
Ask in Mac repository.
