### ISSUE TITLE
http://www.depo.ua/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3752]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Ads under articles

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21202118/3953b652-c256-11e6-9b62-07ae501d3bac.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
Should be no ads

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
Open the link and scroll down.
http://www.depo.ua/rus/politics/nabu-oprilyudnila-video-yak-ohendovskomu-povidomlyali-pro-14122016170300

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10
Browser: | Chrome
Adguard version: | The latest one, 6.1
Adguard driver (Windows): | WFP
Adguard mode (Android): | VPN or proxy(manual/auto)
Filtering quality (Android): | High-quality / high-speed / simplified
Simplified filters(iOS) | On / Off
Adguard DNS: | None / Default / Family Protection
Stealth mode options(Windows) | Nope
Adguard filters: | English, Russian, SocialMedia, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): no ticket

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
