### ISSUE TITLE
Incorrect blocking "logoads"

### ISSUE THREAD

**Issue by HanabishiRecca** [AdguardTeam/AdguardFilters#3753]
English Filter blocks **all** images with name "**logoads**" on **any** site.

> Rule: /logoads.
> Filter: English Filter

**Comment by Alex-302** [comment]
Whats wrong? Please provide examples of broken sites.

**Comment by HanabishiRecca** [comment]
@Alex-302, every file with name "logoads" blocked, on any site.
https://hanabishirecca.github.io/logoads_example/

**Comment by Alex-302** [comment]
@HanabishiRecca it is your own example:) I need examples of real sites.

**Comment by HanabishiRecca** [comment]
@Alex-302, you are joking? You see the rule `/logoads.`, it blocks images on any site. Is this not obvious?

**Comment by Alex-302** [comment]
@HanabishiRecca all generic rules can block something useful. In these cases we add specific exclusions.
You did not provided any examples.

**Comment by HanabishiRecca** [comment]
@Alex-302
My opinion, this is just not right to discriminate something only by name.
What if people want to name image exactly? What if there are more rules such like this?
But ok, do what you want.

**Comment by Alex-302** [comment]
Never seen complaints about it.
