### ISSUE TITLE
http://board.salle.com.ua - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3754]
Пропущена реклама на странице:
http://board.salle.com.ua/member_change.php
Всплывающий баннер на всю страницу

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21216120/a6951754-c2ad-11e6-9403-a947d21accb1.png)

</details>

<details>

Application version: 1.1.1.54
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: 742919A0-EF43-41E8-AB02-4B503827AF9A

Locale: ru
Region: ua

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.35 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.16 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.83 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.43.37 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.75 Enabled=YES

</details>

Ticket ID: 1465478

**Comment by Alex-302** [comment]
У меня на айпаде не повторилось. Скрин твой? Регаться нужно?
