### ISSUE TITLE
m.haberturk.com All things are blocked

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardFilters#3755]
http://m.haberturk.com/

http://i.hizliresim.com/m4L2a0.jpg

Hi
I can not use this site. Because news scroll and same things are blocked.
You check that.
Please fix it.

I use ENGLİSH,
SPYWARE,
SOCIAL MEDIA,
Annoyances,
Mobile Ads,
SAFARI,
TURKISH,
EASYLIST FILTERS.

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||m.haberturk.com/adscbg/mdet.js
```
Please check in user filter.

**Comment by tagataho** [comment]
Thanks fixed..
