### ISSUE TITLE
[Windows] www.wired.com - anti adblock script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#3756]
![](http://i.imgur.com/SpE9cZT.png)
https://www.wired.com/2016/12/secure-news-grades-media-sites-https-fail/

**Adguard version**: 6.1.298.1564

**Operating system**: Windows 10

**Browser**: Chrome

trigger via blockAdBlock

#1741 rule is missing and still works

**Comment by Alex-302** [comment]
Please check again. Must be fixed.

**Comment by Alex-302** [comment]
Also added your rule)
