### ISSUE TITLE
[Windows] www.onmsft.com - anti adblock script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#3757]
![](http://i.imgur.com/sKmeFws.png)
www.onmsft.com

**Adguard version**: 6.1.298.1564

**Operating system**: Windows 10

**Browser**: Chrome

``` ||flavordecision.com^$domain=onmsft.com ```

Note: Was early "winbeta.org"

**Comment by Alex-302** [comment]
Added
