### ISSUE TITLE
exist.ru - Missed notification 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3759]
***Description***: Missed notification conerning suspicious script on the website:
exist.ru 

Screenshot:
<details>

![screen shot 2016-12-16 at 2 49 02 am](https://cloud.githubusercontent.com/assets/17504743/21247696/3c5fe552-c33a-11e6-97aa-a5a24c492a97.png)

</details>

Ticket ID(if exists): 1071569

**Comment by Alex-302** [comment]
Не повторилось
