### ISSUE TITLE
bus tracking app by conjoinix - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3760]
https://play.google.com/store/apps/details?id=com.conjoinix.smartparent

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21260445/9778f3a8-c38e-11e6-90f7-34b5503ba11f.png)

</details>

Adchoices ads, the HTTPS is on. Clearing the cache doesn't help. Logs: 1083734

<details>
{
  "advancedPreferences" : {
  },
  "androidVersion" : "5.1.1 (sdk=22)",
  "appLanguage" : "en",
  "applicationId" : "a7603fe5f2a87781",
  "autoStartEnabled" : true,
  "browsingSecurityEnabled" : true,
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "Xiaomi Redmi Note 3",
  "deviceSpeedRank" : 107,
  "dnsFilteringEnabled" : false,
  "enabledFilterIds" : [ 2, 3, 4, 11 ],
  "environment" : "release",
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "iconType" : "DEFAULT",
  "installedPackages" : [ "com.jio.media.ondemand;version=1.2.11;system=false", "com.jio.jioplay.tv;version=4.1.26;system=false", "com.jio.media.jiobeats;version=1.7.8;system=false", "com.google.android.youtube;version=11.45.59;system=true", "com.duckduckmoosedesign.pb;version=1.4;system=false", "com.enliteus.triggerinn;version=1.1.1;system=false", "com.qrd.omadownload;version=1.0;system=true", "com.android.providers.telephony;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.miui.powerkeeper;version=3.0.00;system=true", "com.google.android.googlequicksearchbox;version=6.8.23.21.arm64;system=true", "com.miui.fm;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.providers.calendar;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.providers.media;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.milink.service;version=1.0.9;system=true", "pl.idreams.potterylite;version=1.61;system=false", "com.touchtype.swiftkey;version=6.4.8.37;system=false", "com.qti.service.colorservice;version=1.0;system=true", "com.raiz.returninghome;version=4.0;system=false", "com.google.android.onetimeinitializer;version=5.1-1743759;system=true", "com.securespaces.android.trustagent;version=5.1.1-eng.jrong.20160627.115608;system=true", "com.xiaomi.account;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.qualcomm.shutdownlistner;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.wallpapercropper;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.quicinc.cne.CNEService;version=1.0;system=true", "co.haptik;version=5.0.1;system=false", "com.cricbuzz.android;version=3.2.4;system=false", "com.miui.milivetalk;version=7.5.2.04;system=true", "com.android.updater;version=3.0.0;system=true", "com.android.documentsui;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.galaxy4;version=1.0;system=true", "com.android.externalstorage;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.timerswitch;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.htmlviewer;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.qualcomm.sta;version=1.0;system=true", "com.miui.securityadd;version=V8_6.6.27;system=true", "com.whatsapp;version=2.16.392;system=false", "com.miui.gallery;version=2.0.0;system=true", "com.varshylmobile.snaphomework;version=3.14;system=false", "com.android.mms.service;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.codeaurora.fmradio;version=5.1.1-eng.zhoumingliang.20160418.141239;system=true", "com.appsvolume.BestGuitarRingtonesFree;version=1.6;system=false", "com.android.providers.downloads;version=6.07.13.700005;system=true", "com.qualcomm.qti.auth.sampleauthenticatorservice;version=1.0;system=true", "com.Cmoar.CmoarVirtualCinemaPro;version=4.7;system=false", "com.xiaomi.payment;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.miui.securitycenter;version=1.8.1;system=true", "com.android.browser.provider;version=5.1-1743759;system=true", "com.qualcomm.qti.engineertool;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.qualcomm.qti.notificationservice;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.qapp.secprotect;version=1.0;system=true", "carzonrent.crdapp;version=3.3;system=false", "com.qualcomm.interfacepermissions;version=1.0;system=true", "com.android.browser;version=8.1.4;system=true", "com.miui.systemAdSolution;version=2016.11.25;system=true", "com.bsbportal.music;version=1.4.1.4;system=false", "com.miui.videoplayer;version=1.0;system=true", "com.android.providers.applications;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.qualcomm.qti.vtremoteservice;version=1.0.0;system=true", "com.google.android.configupdater;version=5.1-1743759;system=true", "com.irusu.vrzone;version=1.1;system=false", "in.amazon.mShop.android.shopping;version=8.9.2.300;system=false", "com.android.soundrecorder;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.defcontainer;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.miui.guardprovider;version=1.0;system=true", "com.qualcomm.agpstestmode;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "org.zwanoo.android.speedtest;version=3.2.26;system=false", "com.android.providers.downloads.ui;version=6.07.13.700005;system=true", "com.android.vending;version=7.2.13.J-all [0] [PR] 138561921;system=true", "com.android.pacprocessor;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.qualcomm.cabl;version=1.0;system=true", "com.miui.backup;version=4.3.3;system=true", "com.xiaomi.ab;version=1.1.1;system=false", "cris.icms.ntes;version=2.0.1;system=false", "com.android.certinstaller;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.google.android.marvin.talkback;version=5.0.4;system=true", "org.codeaurora.bluetooth;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.ovnistudios.peronio;version=0.9.79;system=false", "android;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.contacts;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.qualcomm.wfd.service;version=2.0;system=true", "com.miui.securitycore;version=2;system=true", "com.ThirdState.SineLine;version=3.5.3_Butterfly;system=false", "com.google.android.apps.inputmethod.hindi;version=3.1.0.110136527-arm64-v8a;system=false", "com.creanet3d.drc;version=3.9.5;system=false", "com.android.mms;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.stk;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.backupconfirm;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.mfashiongallery.emag;version=M716051600-G;system=false", "com.ukxinhk.ringpopular;version=1.3;system=false", "com.qualcomm.qti.supersaver;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.miui.player;version=2.6.14;system=true", "com.google.samples.apps.cardboarddemo;version=1.8;system=false", "com.android.provision;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "org.codeaurora.ims;version=1.0;system=true", "in.startv.hotstar;version=5.8.1;system=false", "com.google.android.gm;version=6.11.6.140557227.release;system=true", "com.RyanBousfield.AChairInARoom;version=2.1;system=false", "com.miui.system;version=1.7.0.0;system=true", "com.android.wallpaper.holospiral;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.calendar;version=8.0.10.5;system=true", "com.android.phasebeam;version=1.0;system=true", "com.miui.translation.kingsoft;version=1.0;system=true", "se.maginteractive.wordalot;version=3.430;system=false", "com.olacabs.customer;version=4.2.3;system=false", "com.bigbasket.mobileapp;version=3.0.3;system=false", "com.miui.compass;version=1.6;system=true", "com.google.android.setupwizard;version=2.0;system=true", "com.miui.rom;version=1.4.0.0;system=true", "com.teewe.client;version=3.1.1;system=false", "com.qualcomm.qcrilmsgtunnel;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.providers.settings;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.qualcomm.qcom_qmi;version=1.0;system=true", "com.sculfa.vroceanaquarium;version=1.0.7;system=false", "com.HD_goshow01;version=2.1.5;system=false", "com.android.sharedstoragebackup;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.google.android.music;version=7.0.4007-1.J.3489099;system=true", "com.android.printspooler;version=1;system=true", "com.android.dreams.basic;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.amazon.sellermobile.android;version=3.8.1;system=false", "com.android.incallui;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.duokan.phone.remotecontroller;version=5.1.4a;system=false", "com.miui.bugreport;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.google.android.stardroid;version=1.9.2;system=false", "com.android.inputdevices;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.qualcomm.qti.biometrics.fingerprint.service;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.qualcomm.qti.auth.securesampleauthservice;version=1.0;system=true", "com.oma.drm;version=1.0;system=true", "com.adguard.android;version=2.8.67;system=false", "com.lenovo.anyshare.gps;version=3.6.88_ww;system=false", "com.qualcomm.gsmtuneaway;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.fileexplorer;version=1.7.7;system=true", "com.qti.xdivert;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.miui.stepsprovider;version=2.0;system=true", "com.android.musicfx;version=1.4;system=true", "com.google.android.apps.docs;version=2.4.452.14.45;system=true", "com.google.android.apps.maps;version=9.42.3;system=true", "com.tunnelbear.android;version=v135;system=false", "com.shakingearthdigital.vrsecardboard;version=3.4.76;system=false", "com.idsNextRoomsTonite.RoomsTonite;version=4.5;system=false", "com.miui.cloudbackup;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "net.one97.paytm;version=5.5.13;system=false", "com.android.cellbroadcastreceiver;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.google.android.webview;version=54.0.2840.85;system=true", "com.android.server.telecom;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.google.android.syncadapters.contacts;version=5.1-1743759;system=true", "com.android.keychain;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.keyguard;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.camera;version=1;system=true", "com.android.chrome;version=54.0.2840.85;system=true", "com.xiaomi.xmsf;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.idleif.abyssrium;version=1.2.1(2);system=false", "com.jio.media.jioxpressnews;version=1.2.1;system=false", "com.miui.klo.bugreport;version=1.0.36;system=false", "com.google.android.gms;version=10.0.84 (248-137749526);system=true", "com.google.android.gsf;version=5.1-1743759;system=true", "com.google.android.tts;version=3.10.10;system=true", "com.jio.media.jiomags;version=1.1.5;system=false", "com.google.android.partnersetup;version=5.1.1-2176675;system=true", "com.raymi.mifm;version=2.0.4;system=false", "com.android.packageinstaller;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.google.android.videos;version=3.20.10;system=true", "org.codeaurora.btmultisim;version=1.0;system=true", "it.couchgames.apps.cardboardcinema;version=0.10.10;system=false", "com.dsi.ant.server;version=4.0.0;system=true", "com.xiaomi.finddevice;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.mi.global.bbs;version=1.1.1;system=false", "com.android.proxyhandler;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "org.videolan.vlc;version=2.0.6;system=false", "com.qti.backupagent;version=1.0;system=true", "com.miui.mipub;version=1.0.5.1;system=true", "com.miui.notes;version=1.0.4;system=true", "com.practo.droid;version=8.0.4;system=false", "com.drashvr.titansofspacecb;version=1.1c;system=false", "com.jio.myjio;version=3.2.19;system=false", "com.google.android.feedback;version=5.1-1743759;system=true", "com.android.musicvis;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.xiaomi.midrop;version=1.0.3;system=true", "com.google.android.apps.photos;version=2.5.0.140879878;system=true", "com.miui.translationservice;version=1.0;system=true", "com.google.android.syncadapters.calendar;version=5.1-1743759;system=true", "com.miui.cloudservice;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.managedprovisioning;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.swiftkey.swiftkeyconfigurator;version=2.0.0.139;system=false", "air.com.funtoo.HindiVernoForKids;version=1.0.3;system=false", "com.fingerprints.sensortesttool;version=1.0;system=true", "com.firstplayable.pigpen;version=1.0.2;system=false", "com.syntellia.fleksy.keyboard;version=8.3.2;system=false", "com.ubercab;version=3.130.12;system=false", "com.nearbuy.nearbuymobile;version=2.1.1;system=false", "com.android.dreams.phototable;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.miui.touchassistant;version=1.1.2;system=true", "com.purplepillvr.rapidvr;version=2;system=false", "com.facebook.katana;version=105.0.0.23.137;system=false", "com.xiaomi.providers.appindex;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.bt.bms;version=5.0.7;system=false", "com.wemersive.player1157;version=1.0.3;system=false", "com.android.noisefield;version=1.0;system=true", "com.qti.smq.qualcommFeedback;version=1.4.1.53-snapdragonPrd;system=true", "com.android.providers.partnerbookmarks;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.securespaces.android.ssm.service;version=1.0;system=true", "com.android.fingerprint;version=1.0;system=true", "com.google.android.gsf.login;version=5.1.1-3031930;system=true", "com.android.smspush;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.miui.calculator;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.cleanmaster.sdk;version=5.5.6;system=true", "com.apps.onewayit.docpoke;version=1.15;system=false", "com.android.wallpaper.livepicker;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.motionvolt.flipdiving;version=2.5.5;system=false", "org.blackmart.market;version=0.99.2.89B;system=false", "com.qualcomm.qti.bluetooth.operation;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.miui.miwallpaper;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.bmt;version=2.8;system=false", "com.conjoinix.smartparent;version=1.9;system=false", "com.hungama.myplay.activity;version=4.8.2;system=false", "com.longcheertel.AutoTest;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.google.android.backuptransport;version=5.1-1743759;system=true", "com.miui.cleanmaster;version=1.2.5;system=true", "com.qualcomm.qti.accesscache;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.wdstechnology.android.kryten;version=1.0.0;system=true", "com.podcast.podcasts;version=4.9.4-161205115.recad03c;system=false", "com.miui.analytics;version=1.20.0;system=true", "com.android.settings;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.miui.weather2;version=8.1.1;system=true", "com.google.vr.cyclops;version=1.0.0.120917439;system=false", "com.google.vr.expeditions;version=1.1.0;system=false", "com.grofers.customerapp;version=3.0.1;system=false", "com.qualcomm.location;version=1.0;system=true", "com.xiaomi.scanner;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.miui.networkassistant;version=V7.5.11.5;system=true", "pl.mkexplorer.kormateusz;version=2.5.4;system=false", "com.delphicoder.flud;version=1.4.8.1;system=false", "com.fingerprints.service;version=1.0;system=true", "com.miui.yellowpage;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.miui.antispam;version=1.0.0;system=true", "com.apusapps.browser;version=1.5.6;system=false", "com.android.wallpaper;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.qualcomm.qti.services.secureui;version=1.0;system=true", "com.android.vpndialogs;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.longcheertel.cit;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.qualcomm.location.XT;version=1.0;system=true", "com.google.android.keep;version=3.4.462.01.40;system=false", "com.google.android.talk;version=15.0.141104777;system=true", "com.mi.global.shop;version=2.0.2;system=false", "com.yodo1.rodeo.safari;version=1.3.3;system=false", "com.android.email;version=MIUI_V8_EMAIL_20160715_b2;system=true", "com.android.phone;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.shell;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.providers.userdictionary;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.miui.providers.weather;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.qualcomm.qti.lunarinfo;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.firstplayable.stoneagesnap_vr;version=1.0;system=false", "com.imo.android.imoim;version=9.8.000000004201;system=false", "com.intsig.camscanner;version=4.2.0.20161025;system=false", "com.android.location.fused;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.deskclock;version=2.0.4;system=true", "com.android.systemui;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.qualcomm.qti.engineertool.operation;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.yodo1.roda;version=1.0.9;system=false", "com.qualcomm.qti.confdialer;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.kiloo.subwaysurf;version=1.64.1;system=false", "com.xiaomi.discover;version=3.1.1;system=true", "com.qualcomm.qti.networksetting;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.thememanager;version=0.8;system=true", "com.qualcomm.fastdormancy;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.lbe.security.miui;version=1.3;system=true", "com.smgstudio.onemorebounce;version=1.0.2.110;system=false", "com.google.android.play.games;version=3.9.08 (3448271-048);system=false", "com.dmitril.droidoverwifi;version=1.6.4;system=false", "co.immersv.trailers.cardboard;version=1.1;system=false", "com.miui.whetstone;version=2.0;system=true", "com.android.bluetooth;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "sauer.battle;version=0.9.12;system=false", "com.qualcomm.timeservice;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.google.android.androidforwork;version=5.1-1743759;system=true", "com.android.providers.contacts;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.android.captiveportallogin;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.Cmoar.CmoarRollerCoaster;version=1.1;system=false", "com.swiftkey.languageprovider;version=null;system=false", "com.sketchfab.sketchfabvr;version=1.02;system=false", "cn.wps.moffice_eng;version=9.9.9;system=false", "com.miui.core;version=1.7.0.0;system=true", "com.miui.home;version=1.0;system=true", "com.qualcomm.qti.calendarlocalaccount;version=5.1.1-V8.0.6.0.LHOMIDG;system=true", "com.google.android.inputmethod.latin;version=5.1.23.127065177-arm64-v8a;system=true" ],
  "installerPackage" : "com.adguard.android",
  "kernelVersion" : "3.10.73-perf-g94fc9a6",
  "premium" : true,
  "proxyMode" : false,
  "proxyPort" : 8080,
  "proxySetupManualMode" : false,
  "referrer" : null,
  "sendAnonymousStatistics" : true,
  "showUsefulAds" : false,
  "sourceApk" : "/data/app/com.adguard.android-2/base.apk",
  "sslMitmConfiguration" : "{\"certificateInstalledToSystemStorage\":null,\"mitmList\":\"1024 domains\",\"mitmListMode\":\"WHITELIST\"}",
  "statisticsInfo" : "Blocked threats:0; Blocked banners:66436; Traffic saved:1732141056;",
  "trial" : false,
  "updateChannel" : "RELEASE",
  "upstreamProxySettings" : null,
  "userfilter" : [ ],
  "versionName" : "2.8.67",
  "whitelist" : [ ]
}

**Comment by evgeniy-ADG** [comment]
The users have the same issue with Cricbuzz app, the same adchoices ads. I only have a placeholder. What can be wrong?

**Comment by docgaurav** [comment]
Yes,
The ads are also seen on Cricbuzz app.
Also splash screen ads - full screen ads before an app opens are also seen in https://play.google.com/store/apps/details?id=com.conjoinix.smartparent 
and also have now started appearing (for the last few days) before an app called Rodeo Stampede: Sky Zoo Safari by Yodo1 Games

**Comment by Alex-302** [comment]
@docgaurav please check this rule:
```
||graph.facebook.com^$app=com.conjoinix.smartparent|com.conjoinix.smartparent
```

> Logs: 1083734

it is useless. I need HTTP log.

**Comment by docgaurav** [comment]
I have sent the https logs before,
Please suggest how to send these again.
Regards

**Comment by Alex-302** [comment]
@docgaurav what about the rule?

> Please suggest how to send these again.

```
1. Open Adguard and go to "Settings".
2. Choose "Advanced" in the left menu.
3. Set "Logging level" to "HTTP requests". It's desirable to close all background apps that don't concern the problem beforehand.
4. Reproduce the problem and set the logging level back to "Default". 
5. Send us a message from program by choosing "Send Feedback" in the menu. Don't forget to check the "Send detailed system info" checkbox under the text field.

You can also download logs directly:
/storage/emulated/Android/data/com.adguard.android/cache/log
/sdcard/Android/com.adguard.android/cache/log or
/sdcard/data/Android/com.adguard.android/cache/log or
/sdcard/Android/data/com.adguard.android/
```

**Comment by docgaurav** [comment]
I have sent this feedback multiple times,
   Even today,
Not sure what else to do,
Regards

**Comment by Tetiana2020** [comment]
@Alex-302 , new logs:
[debug (10).txt](https://github.com/AdguardTeam/AdguardFilters/files/661393/debug.10.txt)
[debug (9).txt](https://github.com/AdguardTeam/AdguardFilters/files/661394/debug.9.txt)

**Comment by Alex-302** [comment]
@docgaurav 
***
**@docgaurav please check this rule:**
**||graph.facebook.com^$app=com.conjoinix.smartparent|com.conjoinix.smartparent**
***

**Comment by docgaurav** [comment]
Gaurav Gupta loves MUBI and thinks you might love it too.

At MUBI we think life is too short for bad films.
So, every day we add a cinematic gem to our carefully curated selection and you have 30 days to watch.

Start Your Free Month: https://mubi.com/t/web/email/y92xZBtH?email=reply%2B00412d4e499b3020fa74726d768e130c2d55fbb12a8b4ce292cf00000001146c0e5192a169ce0baf38a9%40reply.github.com&utm_campaign=invitation&utm_source=refer_friend&utm_medium=email
