### ISSUE TITLE
theguardian.com

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardFilters#37608]
1 tracker found by Ghostery Anti-tracking

cdn.krxd.net

AdGuard Spyware filter is enabled and should block this tracker.

![Captura de Pantalla 2019-07-29 a la(s) 08 29 14](https://user-images.githubusercontent.com/46760897/62045192-20ef0400-b1db-11e9-90ae-f766150e0743.png)

**Comment by AdamWr** [comment]
Hi,
it's already blocked, the same on wsj.com - https://github.com/AdguardTeam/AdguardFilters/issues/37607

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/62045446-a1c2f580-b205-11e9-918d-a5b7e14058d5.png)

</details>
