### ISSUE TITLE
Liste AR blocks www.independent.co.uk

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3761]
The page loads blank.

<details>
Os version: Microsoft Windows NT 10.0.14393.0
Dot .net version: 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: e7acb0fe3c814f789bd0e8351dafe956
Language: en
AppVersion: 6.1.258.1302
Main settings: 
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:112 Name: Liste AR Url: https://liste-ar-adblock.googlecode.com/hg/Liste_AR.txt
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Wfp
Ads Blocked: 34562, Trackers Blocked: 26954
Filtering Mode: Driver
Application lifetime: 19.21:48:23.2551041
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": false,
  "BlockWebRtc": false,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"
}

**Comment by Alex-302** [comment]
Not reproduced.
@seanl-adg please check on your side with the same filters.

**Comment by evgeniy-ADG** [comment]
It's ok now. Weird.

**Comment by Alex-302** [comment]
Ok then.
