### ISSUE TITLE
wired.com

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardFilters#37617]
use.typekit.net/*

Tracker spotted by Ghostery Anti-tracking

Both AdGuard Spyware and Social media filters enabled

![Captura de Pantalla 2019-07-29 a la(s) 09 50 29](https://user-images.githubusercontent.com/46760897/62049845-77ae0b00-b1e6-11e9-9b54-09c32bef1ddb.png)

**Comment by BlazDT** [comment]
The Typekit service used to deliver this font or fonts for use on websites.

Tracking is blocked by Spyware filter:
||p.typekit.net^$third-party
