### ISSUE TITLE
clarin.com

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardFilters#37615]
Facebook.com/connect/ping?client_id=*
cdns.us1.gigya.com/gs/webSdk/*
platform.twitter.com/widgets/widget_iframe*

Trackers spotted by Ghostery Anti-tracking

Both AdGuard Spyware and Social media filters enabled

![Captura de Pantalla 2019-07-29 a la(s) 09 33 30](https://user-images.githubusercontent.com/46760897/62048800-1f760980-b1e4-11e9-96e8-a65a33400757.png)

**Comment by Alex-302** [comment]
Ghostery blocks too much

**Comment by LucasDiTomase** [comment]
I agree. Thats because, if I´m not mistaken, Ghostery uses the same anti tracking technology as Cliqz which is based in machine learning and can spot trackers ( or more precisely UIDs ) better than blocklist-based tools

Source: https://cliqz.com/en/magazine/how-we-at-cliqz-protect-users-from-web-tracking

**Comment by Alex-302** [comment]
Maybe. Also Ghostery  detects trackers, blocked by ad blockers, as not blocker(for example inline scripts)
