### ISSUE TITLE
wired.com

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardFilters#37619]
Annoying bar not blocked by AdGuard base filter nor AdGuard Annoyances filter

![Captura de Pantalla 2019-07-29 a la(s) 10 10 48](https://user-images.githubusercontent.com/46760897/62051624-230c8f00-b1ea-11e9-911a-6de6ca174206.png)

Blocked element manually via AdGuard browser extension succesfully with this rule

wired.com###app-root > div.app-shell-component.app-shell-component--article > div.page-loader-component:nth-child(4) > div.page-wrapper.page-wrapper--article.page-wrapper--default.page-wrapper--lede-photo > aside.paywall-container-component.paywall-container-component--growler:first-child > div.expandable-growler-wrapper.expandable-growler-wrapper__expanded:last-child

**Comment by BlazDT** [comment]
Not sure if we should fix in self-promo.  When reading more articles it just says 0 free articles left, but articles work.

`wired.com##.page-wrapper--article > .paywall-container-component[aria-labelledby="growler-label"]`

@Alex-302 what do you think?

**Comment by krystian3w** [comment]
Works or have cuted ~1/4 of text?

**Comment by LucasDiTomase** [comment]
It is working for me at least ( on Chrome )

**Comment by Alex-302** [comment]
I see this element only
![image](https://user-images.githubusercontent.com/8361299/63347408-b3f50700-c35f-11e9-9fc2-64739e2f45e8.png)

**Comment by LucasDiTomase** [comment]
That I fixed with this rule: wired.com##.ad--side_rail

**Comment by Alex-302** [comment]
it is not annoying

**Comment by LucasDiTomase** [comment]
Sry. I though you were mentioning looking for a fix

**Comment by Alex-302** [comment]
I can't reproduce element like on the first screenshot.

**Comment by LucasDiTomase** [comment]
I think someone made a commit that fixed it

![IMG_2081](https://user-images.githubusercontent.com/46760897/63457516-968b7000-c427-11e9-9e25-a695d10a0d88.jpg)

**Comment by krystian3w** [comment]
Bogachenko list on added as `3p` list in AG, for only only for manual subscription?

**Comment by LucasDiTomase** [comment]
These 2 rules are working for me

wired.com##.page-wrapper--article > .paywall-container-component[aria-labelledby="growler-label"]

wired.com##.ad--side_rail

**Comment by Alex-302** [comment]
For custom filter:
```
wired.com##.paywall-container-component
wired.com##.expandable-growler-wrapper
```
