### ISSUE TITLE
https://einthusan.com/ - anti-adblocker 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3762]
https://einthusan.com/ detects adguard - redirected to
https://einthusan.com/adblocker/

![image](https://cloud.githubusercontent.com/assets/15856304/21261500/8278bbea-c394-11e6-8343-02f3a2ffd575.png)

<details>

Application version: 1.3.0
Applicaton shared support folder:/Library/Application Support/com.adguard.Adguard
Applicaton support folder:/Users/jambur/Library/Application Support/com.adguard.Adguard
Filtration Enabled
Filtration mode: direct
Blocked: 213860
Application lifetime: 2016-09-04 12:34:13 +0000
Platform: Mac OS X
OS: 1012
Locale: en-US

Antibanner filter: Enabled
Antiphishing filter: Enabled
Parental control: Disabled
Privacy protection: Enabled
HTTPS: Enabled
Assistant: Enabled
Web of trust: Disabled
Popup blocker: Disabled

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0
ID=2 Name="English filter" Version=1.1.3.13
ID=3 Name="Spyware filter" Version=1.0.9.53
ID=4 Name="Social media filter" Version=1.0.15.45
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.89
ID=1 Name="Russian filter" Version=1.0.44.29
ID=7 Name="Japanese filter" Version=1.0.93.3
ID=113 Name="Liste FR" Version=1.0.71.1
ID=121 Name="void.gr" Version=1.0.0.77

SSL exception domains:
plimus.com
payproglobal.com
avangate.com
paypal.com
halifax-online.co.uk
identity.virginmedia.com
signin.ebay.com
signin.ebay.co.uk
icbc.com.cn
hsbc.co.uk
hsbc.com
secure.hsbcnet.com
bv-activebanking.de
hsbc.ca
hsbc.com.au
chase.com
secure.bnpparibas.net
bnpparibasfortis.be
webbanking.bgl.lu
secure.bnl.it
barclays.co.uk
bankofamerica.com
deutsche-bank.de
deutsche-bank.es
deutsche-bank.it
deutsche-bank.pt
db-pbc.pl
db.com
qweb.quercia.com
citibank.com
wellsfargo.com
societegenerale.fr
societegenerale.com
sgeb.bg
rbsinternational.com
sberbank.ru
alfabank.ru
zakupki.gov.ru
194.105.148.87
aus.mozilla.org
aus1.mozilla.org
aus2.mozilla.org
aus3.mozilla.org
aus4.mozilla.org
aus5.mozilla.org
aus6.mozilla.org
addons.mozilla.org
versioncheck.addons.mozilla.org
dl.dropboxusercontent.com
lastpass.com
mozilla.org
mozilla.net
webmoney.ru
wmtransfer.com
adtidy.org
chrome.adtidy.org
eff.org
8pecxstudios.com
rbsdigital.com
commonbank.com.ua
sparkasse-fuerth.de
ing-diba.de
apple.com

**Comment by evgeniy-ADG** [comment]
Can anyone look into this, please? The customer's pinging us.

**Comment by Alex-302** [comment]
Fixed
