### ISSUE TITLE
outlook.live.com - Adguard Assistant Bug

### ISSUE THREAD

**Issue by Serzh-SUP** [AdguardTeam/AdguardFilters#3763]
### При посещении сайта outlook.live.com (для просмотра почты на @outlook.com или @hotmail.com аккаунте) помощник Adguard перезапускается, сбрасывает все свои настройки, и отображает сообщение, которое появлялось при первом его первом запуске после установки программы. Под сбрасываемыми настройками имеется ввиду сброс настроек отображения иконки помощника. Делаю её маленькой и перемещаю влево, но при посещении вышеуказанного сайта всё сбивается, и она становится по умолчанию – большой и справа.

> ### Антитрекинг не влияет на проблему.

## Фильтры:
**Пользовательский
Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский
Anti-Adblok Killer | Reek**

> ### Adguard 6.1.298.1564.

### Screenshot:

<details>

![2016-12-16_13-45-04](https://cloud.githubusercontent.com/assets/16462533/21262108/27163b3e-c398-11e6-9fe5-f67e1eb08cff.png)

</details>

**Comment by zebrum** [comment]
@ameshkov please take a look
id 1267493
upd 
Internet Explorer и Microsoft Edge
Кроме того, точно важно, что проблема проявляется только при наличии непрочитанного письма. Причём, у меня это происходит только после того, как это непрочитанное письмо пару минут повисит непрочитанным, то есть заходить на сайт outlook.live.com нужно через пару минут после отправки письма.

есть видео:
[adguard_outlook_bug.mp4.zip](https://github.com/AdguardTeam/AdguardFilters/files/657693/adguard_outlook_bug.mp4.zip)

**Comment by Alex-302** [comment]
@zebrum а выключние фильтров что-то меняет?

**Comment by ameshkov** [comment]
Это подтвержденный баг помощника

**Comment by Alex-302** [comment]
тогда закрываю?
