### ISSUE TITLE
music.yandex.*

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#37647]
[https://music.yandex.ru/artist/5656951/tracks](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://music.yandex.ru/artist/5656951/tracks)

 Блок справа: `music.yandex.*##.teaser ~ div`

<details><summary>Screenshot:</summary>

![2019 07 30-1](https://user-images.githubusercontent.com/17948007/62090203-ae326700-b274-11e9-9a67-f36a433aa53f.png)
</details>

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.2.1
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by XX-J** [comment]
@Alex-302 

 Почему Вы не используете звёздочку, а предпочитаете перечислять домены? Есть какие-то ограничения?

**Comment by Alex-302** [comment]
программы в звёздочку пока не умеют. Но скоро научатся.
