### ISSUE TITLE
newkaliningrad.ru - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#3764]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

Пропущена реклама на сайте:
newkaliningrad.ru

Screenshot:
<details>

![image]
![8zvgsevampg](https://cloud.githubusercontent.com/assets/22892774/21272405/c7185d72-c3c7-11e6-9405-9051f53aaf84.jpg)
)
</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Chrome
Adguard version: | 2.8.76
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
Adguard filters: | 2, 3, 4, 14, 1, 11
HTTPS filtering: | on

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1468299

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
