### ISSUE TITLE
hallo-eltern.de - Ad - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3765]
***Site***: http://www.hallo-eltern.de/
***Description***: Ad and Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21280604/3c75d008-c3e7-11e6-9cbf-abc260c126fe.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21280612/4a72f4c4-c3e7-11e6-829c-5178281d5f70.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.36
 Spyware filter | 1.0.9.61
 Social media filter | 1.0.15.58
 Annoyances filter | 1.0.7.94
 German filter | 1.0.29.39
 Mobile ads filter | 1.0.6.27
 Safari filter | 1.0.1.86

**Comment by Alex-302** [comment]
Added to German filter
```
hallo-eltern.de##div#wunsch1.home_block.mobile-hide[style="background-color:#ffffff; padding-bottom=20px; border: 1px solid #f5a922;"]
hallo-eltern.de###content-ad-bottom

```
