### ISSUE TITLE
rund-ums-baby.de - Ad - Social leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3766]
***Site***: http://www.rund-ums-baby.de/
***Description***: Ad at the top of the site and Social leftover at the end of the site.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21280645/7d642420-c3e7-11e6-9b7e-d291348fbfd6.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21280658/9335e978-c3e7-11e6-846e-4ff121c2d9cf.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.36
 Spyware filter | 1.0.9.61
 Social media filter | 1.0.15.58
 Annoyances filter | 1.0.7.94
 German filter | 1.0.29.39
 Mobile ads filter | 1.0.6.27
 Safari filter | 1.0.1.86

**Comment by Alex-302** [comment]
Added to German filter
```
rund-ums-baby.de##div[style="position:relative; height:214px; margin-bottom:66px;"]
rund-ums-baby.de##div[style="position:absolute; z-index:1; left:26px; width:898px; background-color:#f6f5f3;"]

```
