### ISSUE TITLE
windeln.de/magazin - Annoyance - Social leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3767]
***Site***: http://www.windeln.de/magazin/
***Description***: Cookie notice at the top and Social leftover at the end of the site.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21280747/2674a396-c3e8-11e6-9cf9-e80102d274dc.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21280763/33cbd3c0-c3e8-11e6-82be-8c6c4531ce1d.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.36
 Spyware filter | 1.0.9.61
 Social media filter | 1.0.15.58
 Annoyances filter | 1.0.7.94
 German filter | 1.0.29.39
 Mobile ads filter | 1.0.6.27
 Safari filter | 1.0.1.86

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
windeln.de###sliding-popup
```
Added to Social filter
```
windeln.de###col2_content > div[id^="block-block-"][class="block block-block"]:last-child
```

**Comment by danidoedel** [comment]
@Alex-302 That rule for social filter wasn't added to the filter.

**Comment by Alex-302** [comment]
added
