### ISSUE TITLE
wundertuete.eltern.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3768]
***Site***: https://wundertuete.eltern.de/
***Description***: Ad leftover at the top.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21280824/b38ee7a0-c3e8-11e6-8711-a57ba598d8b2.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.36
 Spyware filter | 1.0.9.61
 Social media filter | 1.0.15.58
 Annoyances filter | 1.0.7.94
 German filter | 1.0.29.39
 Mobile ads filter | 1.0.6.27
 Safari filter | 1.0.1.86

**Comment by Alex-302** [comment]
Added to German  filter
```
wundertuete.eltern.de##div[class^="m-ad-"]
```
