### ISSUE TITLE
bambiona.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3769]
***Site***: http://www.bambiona.de/thema/baby-entwicklung
***Description***: Ad leftover

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21280933/729b03a4-c3e9-11e6-848d-67bc25e168ad.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21280940/87241702-c3e9-11e6-9542-42c6723ed5f0.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21280950/9758d0f4-c3e9-11e6-979f-df37afd16a4c.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.36
 Spyware filter | 1.0.9.61
 Social media filter | 1.0.15.58
 Annoyances filter | 1.0.7.94
 German filter | 1.0.29.39
 Mobile ads filter | 1.0.6.27
 Safari filter | 1.0.1.86

**Comment by Alex-302** [comment]
Can't access to this site.

**Comment by seanl-adg** [comment]
Not reproduced.

**Comment by danidoedel** [comment]
Has been fixed somehow.
