### ISSUE TITLE
itv.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#377]
На сайте антиадблок работает. 
Для того, чтобы зайти на сайт, надо британское прокси (я пользовался tunnelbear) и аккаунт ( ukukc@hotmail.com / poiuZXCV ). 

https://qcrm.cc/#/customer/879552

**Comment by Alex-302** [comment]
Пока не придумал как нормально убрать сообщение, только разблокировкой рекламы:
@@||itv.com^$urlblock


itv_adserve.js

**Comment by vbagirov** [comment]
Уже передавать юзеру или еще поколдуешь?

**Comment by Alex-302** [comment]
Как временный вариант можно. Лучше не получается. Прокси отшивает, а в tunnelbear трафик закончился.
Добавил в ЭФ пока.

**Comment by vbagirov** [comment]
Передал. Пока закрывать?

**Comment by Alex-302** [comment]
Вроде всё норм, лишнего нет.

**Comment by ghajini** [comment]
Antiadblock here
`https://www.itv.com/hub/the-jeremy-kyle-show/1a5163a2515`
Requires UK Ip and ITV account....
Adguard updated to latest
Chrome

**Comment by Alex-302** [comment]
I can't check it.

**Comment by ghajini** [comment]
What info you require from me to check?

**Comment by Alex-302** [comment]
@ghajini  ITV account.
It it free or not?

**Comment by ghajini** [comment]
Email: johnbenson@mailinator.com
Password: johnbenson
Found on adguard Forum

**Comment by Alex-302** [comment]
Please check these rules:
```
@@||tom.itv.com/itv/tserver/size=videosponsor/*/viewid=
||tom.itv.com/itv/tserver/size=*/viewid=$important,replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/
```

**Comment by ghajini** [comment]
removes antiadblock..but i think ads comein.....

**Comment by Alex-302** [comment]
@ghajini which Adguard are you using?

**Comment by ghajini** [comment]
Adguard browser extension chrome

**Comment by Alex-302** [comment]
It can't replace content of requests. Only Adguard for Windows/Android/Mac can do it.

**Comment by ghajini** [comment]
So I have to use adguard for windows😢

**Comment by Alex-302** [comment]
It is better than extensions:)

**Comment by ghajini** [comment]
Thank you

**Comment by jspenguin2017** [comment]
@ghajini It is patched by uBlock Protector loopback engine. I can patch server response (for XHR), but for this case I just put in a constant payload. 

p.s. I'm linked here from issue 113 of AAK-Cont.

**Comment by jspenguin2017** [comment]
@Alex-302 That rule removed everything in `<VAST>` tag... Looks like my solution was overkill.
