### ISSUE TITLE
http://onelike.tv/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3771]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Не работает видео на ПОТОКАХ 1,2
http://onelike.tv/eurosport-2.html

На ПОТОКЕ 2, черный экран, помогает отключение Английского фильтра. Тогда значок Плея появляется 
На ПОТОКЕ 1, не работает вобще видео, помогает отключение "Скрыть поисковые запросы" в Антитрекинге

Screenshot:

<details>

Поток 2
![image](https://cloud.githubusercontent.com/assets/18548949/21285921/b593bbfa-c44e-11e6-9528-b3214dca2ab5.png)

Поток 1
![image](https://cloud.githubusercontent.com/assets/18548949/21285925/cc340d6a-c44e-11e6-947f-65a4d31c8ebe.png)

</details>

* **Expected behaviour**: 

Screenshot:
<details>

Поток 2
![image](https://cloud.githubusercontent.com/assets/18548949/21285931/ef2822e8-c44e-11e6-9933-d6eecc0c24cd.png)

Поток 1
![image](https://cloud.githubusercontent.com/assets/18548949/21285945/4a60f7a2-c44f-11e6-843d-db9c8f575ded.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | ВИН
Browser: | ХРОМ
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard DNS: | None
Stealth mode options(Windows) |   "BlockThirdPartyCookies": true,  "RemoveXClientDataHeader": true,"HideSearchQueries": true, "SendDoNotTrackHeader": true,
Adguard filters: | Русский, Английский

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1320300

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||vkluchi.tv/channels/$stealth
watchmeonline3.pw#@##ad-overlay
```
