### ISSUE TITLE
http://svetmonet.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3772]
Ссылка сайта: http://svetmonet.ru/42h9.html
Скриншот: http://f1.s.qip.ru/OgbqitCm.png

Мои параметры:
* Windows 7 x64
* Adguard в виде расширения у Chrome
* Используемые фильтры: Русский фильтр, Английский фильтр, RU AdList
* Dr.Web

**Comment by Alex-302** [comment]
У меня чисто.
Перезалей скрин.

**Comment by TomCruiseXZ** [comment]
Alex-302, 
1) проверь свой комп на вирусы
2) поставь чистый Chrome и одно расширение Adguard и на нём тести

**Comment by TomCruiseXZ** [comment]
Когда поправите ?

**Comment by evgeniy-ADG** [comment]
@Alex-302 

![image](https://cloud.githubusercontent.com/assets/15856304/21723270/7c33aaec-d438-11e6-9978-f0da676c4526.png)

Русский фильтр, Английский фильтр, RU AdList

**Comment by TomCruiseXZ** [comment]
> У меня баннеры блокируются.
Вы используете официальный Chrome с одним расширением Adguard ?
Если ДА, то скрин в студию, если НЕТ, то почему ?

> Второе - не реклама.
А что это ? 
Дополнительная опция хостинга картинок ?

**Comment by Alex-302** [comment]
http://imagizer.imageshack.com/img923/5986/IGbhVh.png

> если НЕТ, то почему ?

настройки может кривые, или что-то другое.


> А что это ?
> Дополнительная опция хостинга картинок ?

нажми и прочитай текст.

**Comment by TomCruiseXZ** [comment]
> нажми и прочитай текст.
ну так это реклама

**Comment by Alex-302** [comment]
Кого они рекламируют?

**Comment by TomCruiseXZ** [comment]
Быстрые займы он-лайн.
Не по глазам чтоль ?

**Comment by Alex-302** [comment]
Перечитай ещё раз сообщения под скрином.

**Comment by TomCruiseXZ** [comment]
под твоим скрином ?
то написано: настройки может кривые, или что-то другое.

и как это понимать ?

**Comment by Alex-302** [comment]
теперь текст на скрине из того сообщения читай

**Comment by TomCruiseXZ** [comment]
ничё не понимаю, хватит загадками говорить
у меня как была реклама так и осталась

как я понял у тебя её нет, т.к. у тебя не пойми какой сборки браузер и.т.п

**Comment by TomCruiseXZ** [comment]
чё молчим ?
