### ISSUE TITLE
yandex.ru search ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3773]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Реклама от Яндекса о установке приложения. У меня не повторяется
https://yandex.ru/search/?msid=1481722638.50481.22869.26537&lr=10741&text=%D0%BA%D0%B0%D0%BA%20%D0%B1%D1%8B%D1%81%D1%82%D1%80%D0%BE%20%D0%BF%D0%BE%D0%B3%D0%B0%D1%81%D0%B8%D1%82%D1%8C%20%D0%B8%D0%BF%D0%BE%D1%82%D0%B5%D0%BA%D1%83%20%D1%81%D1%85%D0%B5%D0%BC%D0%B0&redircnt=1481971679.1

Лог: 
[debug (4).txt](https://github.com/AdguardTeam/AdguardFilters/files/658816/debug.4.txt)
яндекс приложение по недвижимости рекламируется в 16-40

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21286255/83aa092e-c457-11e6-9c6f-07ffcb0ca29f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Андроид
Browser: | Хром
Adguard version: | 2,8,67
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality, HTTPS
Adguard DNS: | None 
Adguard filters: | [ 2, 3, 4, 14, 1, 11, 211 ]

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1150428

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
В журнале не видно запросов. Нужно узнать режим фильтрации HTTPS.

**Comment by vgavrish** [comment]
"sslMitmConfiguration" : "{\"certificateInstalledToSystemStorage\":null,\"mitmList\":\"1024 domains\",\"mitmListMode\":\"WHITELIST\"}",

**Comment by Alex-302** [comment]
Серт проверить нужно, как здесь
https://github.com/AdguardTeam/AdguardFilters/issues/3774
Это не один и тот же юзер?

**Comment by vgavrish** [comment]
написала
не, это два разных

**Comment by vgavrish** [comment]
серт. переустановить прогу и серт просили, не помогло
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21425155/24987ee6-c850-11e6-8ea8-62396806d053.png)

</details>

вот у него еще одна проблема на 
https://rueconomics.ru/214268-inoplanetyane-iz-peshchery-lastochek-popali-na-video-ochevidca

<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21425199/6a24fa5c-c850-11e6-9a03-8720a91da266.png)

лог
[debug (3).txt](https://github.com/AdguardTeam/AdguardFilters/files/668680/debug.3.txt)
время 20-50

**Comment by Alex-302** [comment]
Тогда нужно записать HAR и сделать скрин текущего баннера(или скопировать его текст), чтоб искать проще было.

**Comment by Alex-302** [comment]
rueconomics.ru - тоже норм
Можно отдельный HAR записать, предварительно перезапустив защиту, чтоб в новый файл писалось.

**Comment by vgavrish** [comment]
Вот с яндекс недвижимостью лог.
https://drive.google.com/open?id=0B5dP1M24mheOOUZVMXYzMlJ1N3c

Там скрин рекламы тот же : http://prntscr.com/dn0q0r

Вот с сайта экономики. скрин рекламы тот же
https://drive.google.com/open?id=0B5dP1M24mheONTVTaWVrcGxqZ0E

**Comment by Alex-302** [comment]
Скрин не тот же. Меня именно текст интересовал. Повезло случайно наткнуться)
На проверку:
```
yandex.ru,yandex.com,yandex.ua,yandex.kz,yandex.by##.teaser_type_internal
```
По второму - следов баннера не нашёл.
Пусть попробует в пользовательском фильтре
```
||rueconomics.ru/template/mobile/assets/jquery.smartbanner/jquery.smartbanner.js
```
Проверять в приватной вкладке или после очистки куки.

**Comment by vgavrish** [comment]
отписала
тут еще какой-то файл был, после записи файла на rueconomics.ru
https://drive.google.com/open?id=0B5dP1M24mheOckkyX290TlBqWkE

**Comment by vgavrish** [comment]
+ говорит на яндекс не помогло

+ на сайте экономики тоже + тут еще такие скрины есть, может есть там и баннеры в har

<details>
![image](https://cloud.githubusercontent.com/assets/18548949/21466735/64825b7e-c9dd-11e6-9ddd-1b70fb9bd023.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21466736/6b33c2e6-c9dd-11e6-89c7-57fbfa8dfd48.png)

**Comment by Alex-302** [comment]
> на сайте экономики решилось

с правилом или без?




> говорит на яндекс не помогло

можно так попробовать
```
yandex.ru,yandex.com,yandex.ua,yandex.kz,yandex.by##.teaser
```

**Comment by vgavrish** [comment]
экономический - без правила помогло
на яндекс вроде бы проблема убралась, но я попросила проверить некоторое время

**Comment by vgavrish** [comment]
> Я мере проверил в двух браузерах , с очисткой Кеша, кукла и добавлением вашего правила,насчет яндекса ,и вроде бы проблема ушла.

**Comment by Alex-302** [comment]
Ок, добавил эти правила.

**Comment by vgavrish** [comment]
Тот же юзер. Включен сверхэкономный режим 

При поиске яндекс появляются такие рекламы:
http://prntscr.com/e1s0wv
Первую полезную рекламу мы блокируем или нет?

Лог 14-21
https://drive.google.com/open?id=0B5dP1M24mheOUHVBN1kyaGw1Q2s

Information | value
--- | ---
Operating system: | Андроид
Browser: | Хром
Adguard version: | 2,8,67
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality, HTTPS
Adguard DNS: | Default 
Adguard filters: | [ 15 ]

**Comment by Alex-302** [comment]
Только с качественным режимом.

**Comment by vgavrish** [comment]
В смысле? У меня качественный и стоял

**Comment by Alex-302** [comment]
Странно. А серт подменился? У меня чисто там.
