### ISSUE TITLE
Unable download or upload any to Github Amazons CDNs 

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#37748]
Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1903 x64 (lastest)
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.1.2817 RELEASE** 
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Block WebRTC/Location API/Java/Flash
|Hide your search queries
|Remove X-Client-Data header from HTTP requests
|Send Do-Not-Track header
|Strip tracking parameters from URLs
| **=== FILTERS ENABLED ===**
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| Fuck Fuckadblock
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| Fanboy's Annoyances
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

```
github-production-release-asset-2e65be.s3.amazonaws.com  
ERR_CONNECTION_CLOSED
```
when you want download any file from GItHub, or just upload screenshot issue:

![s](https://i.imgur.com/6ldUU4U.png)

![d](https://i.imgur.com/8hmo3W2.png)

@ameshkov 

@AdamWr @Alex-302

**Comment by Alex-302** [comment]
What causes it?

**Comment by FadeMind** [comment]
@Alex-302 now I have `ERR_SSL_PROTOCOL_ERROR` (after disabling Adguard). I investigate this and issue is with ESET SSL Scanning. 

REPRODUCE

Install ESET Internet Security and Adguard For Windows.
Try download any file from Github.

Workaround: disabling internal scanning SSL protocol in Advanced ESET settings.

Weird cause this is not happend with other adblockers.

**Comment by FadeMind** [comment]
@ameshkov  comment from ESET support forum thread: https://forum.eset.com/topic/20362-eis-ssl-scanner-blocking-amazon-cdn-servers-github/

--------------

The Github certificate is self-signed. Strongly suspect this is the same issue manifested in the Chromecast thread.

Adguard must be performing some MITM port redirect activity to ports other than 443 and this is what Eset's SSL/TLS protocol scanning is hiccuping on.

Present there are two solutions:

1. Only specify port 443 in SSL/TLS protocol scanning.

2. You will have to find out what ports Adguard is performing its proxy activities with and exclude those ports from the existing Eset SSL/TLS port 0-65535 specification. For example if Adguard is using ports 1010,1011, and 1012, the Eset SSL/TLS port specification should be: 443,0-1009,1013-65535. Note that this will only work if Adguard is using static proxy port assignment. If it changes ports dynamically, you're out of luck.

I whole heartily expect many more posts like this for other apps.

--------------

So, what can I do for resolve this issue properly? What ports are used by Adguard WFP Driver SSL?

Regards

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/CoreLibs #1068](https://github.com/AdguardTeam/CoreLibs/issues/1068) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
Not related to filters. Moved to CoreLibs.
