### ISSUE TITLE
m.news.yandex.ua ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3774]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: реклама при (яндекс-директ) при открытии страницы
https://m.news.yandex.ua/index.html?nar=0 

Очистка кеша и данных не помогла, вылезает реклама «яндекс-директ».
Рекламный блок подгружается, скорее всего, скриптом, т.к. развёртывается с запозданием, после формирования структуры страницы.

Лог 
[debug (5).txt](https://github.com/AdguardTeam/AdguardFilters/files/658817/debug.5.txt)
время 10:42

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21286282/3ec4ee0e-c458-11e6-91af-ed9a0741a0fb.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Андроид (4.4.2)
Browser: | Встроенный. В Хроме проблемы нет
Adguard version: | 2.8.76
Adguard mode (Android): | proxy(auto)
Filtering quality (Android): | High-quality , HTTPS
Adguard filters: | [ 2, 3, 4, 14, 1, 5, 11 ]

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1062749

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Сайт точно фильтруется? У меня там чисто. Нуно проверить сертификат(замок в адресной строке) и узнать какой режим фильтрации HTTPS(дефолтный, или чёрный список)

Добавил в шаблон про HTTPS фильтрацию.

**Comment by vgavrish** [comment]
"statisticsInfo" : "Blocked threats:0; Blocked banners:90082; Traffic saved:2493234176;",
  "sslMitmConfiguration" : "{\"mitmListMode\":\"WHITELIST\",\"mitmList\":\"1024 domains\",\"certificateInstalledToSystemStorage\":null}",

за сертификат написала

**Comment by vgavrish** [comment]
серт
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/21419746/356e394a-c832-11e6-8bff-3a20646e5111.png)

**Comment by vgavrish** [comment]
@Alex-302 тут проблема еще не ушла
записать еще раз http лог или хар?

**Comment by Alex-302** [comment]
сертификат не подменяется, если скрин актуален.
Нужно, чтоб он проверил в другом браузере(обычный Хром). Если останется - попробовать выключить Адгард и очистить его кэш в настройках системы.
