### ISSUE TITLE
esigaram.us

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3775]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: esigaram.us
* **Current behaviour**: ads all over the place

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2016-12-17 at 13 01 14](https://cloud.githubusercontent.com/assets/14153331/21286341/b769b8ca-c459-11e6-982a-e58c6c7522fb.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | checked on Windows and macOS
Browser: | Chrome, Safari
Adguard version: | 1.4.0
Adguard DNS: | None

Adguard filters: 
<img width="1034" alt="screen shot 2016-12-17 at 13 01 49" src="https://cloud.githubusercontent.com/assets/14153331/21286351/db6905e6-c459-11e6-8064-a4bcd560ab06.png">

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1469395

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
