### ISSUE TITLE
http://cricfree.tv - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3776]
http://cricfree.tv/sky-sports-3-live-stream-3

![image](https://cloud.githubusercontent.com/assets/15856304/21286518/de8eae2e-c45e-11e6-96b3-c7acc8f2f850.png)

<details>

Os version: Microsoft Windows NT 10.0.10586.0
Dot .net version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: 0cc9d28414b0452f93b1564c311167f6
Language: en
AppVersion: 6.1.298.1564
Main settings: 
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:119 Name: Icelandic ABP List Url: http://adblock.gardar.net/is.abp.txt
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Wfp
Ads Blocked: 16153, Trackers Blocked: 10411
Filtering Mode: Driver
Application lifetime: 11.14:38:19.8076744
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": false,
  "BlockWebRtc": false,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"
}

</details>

I was able to reproduce the issue, but it doesn't occur fast. You should open a link, pause a translation, wait for a minute or so and then it'll appear.

**Comment by Alex-302** [comment]
Not reproduced.
