### ISSUE TITLE
https://web.de/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3777]
The page looks short:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21286735/921e57d2-c464-11e6-81e3-d55b691e4a3b.png)

</details>

and when you disable Adguard, it looks as intended:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21286740/ad8febe8-c464-11e6-8547-17399b16a86f.png)

</details>

comments from the customer:

> 
> https://www.gmx.net has the same issues.
> 
> If I remove the following css from AdGuard the pages looks good:
> 
> ::content .offers, ::content .lottoJackpot, ::content .buster, ::content .adv-promotion, ::content .ad-container, ::content .ad, ::content #uimTopPosition, ::content #topper, ::content #supersize, ::content #navigation > #navSpecial[style="height: 235px;"], ::content #mail-list .new.nma, ::content #mail-list .iba, ::content #info-virus, ::content #footer-icons, ::content #advTop, ::content #advSpecialMain, ::content #adv, ::content #ads, ::content .wrapper-indent > .sepLoginExpander, ::content #middle-container, ::content #wrapper2 > h\:section:not(.news), ::content object[width="640"][height="160"], ::content object[width="640"][height="100"], ::content object[width="300"][height="60"], ::content object[width="260"][height="130"], ::content object[width="200"][height="200"], ::content object[width="1000"][height="270"], ::content object[width="1000"][height="250"], ::content object[width="100"][height="100"], ::content img[width="240"][height="400"], ::content iframe[width="100%"][height="60"], ::content iframe[width="100%"][height="250"], ::content embed[width="640"][height="160"]
> 
> Thanks for your support.

**Comment by evgeniy-ADG** [comment]
Filters: Eng and Deutscher

**Comment by Alex-302** [comment]
Removed from German filter
```
gmx.net,web.de###wrapper2 > h\:section:not(.news)
```
