### ISSUE TITLE
lanacion.com.ar

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardFilters#37772]
Notification popup top left corner

Proposed rule to fix it

lanacion.com.ar##.notificacion-modal

![Captura de Pantalla 2019-07-31 a la(s) 14 07 57](https://user-images.githubusercontent.com/46760897/62232895-b6d28c80-b39d-11e9-8f38-3f75ac8f4f3a.png)

**Comment by Alex-302** [comment]
ok
