### ISSUE TITLE
fast-torrent.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#3778]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: the login overlay is blocked mistakenly
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2016-12-17 at 16 17 13](https://cloud.githubusercontent.com/assets/14153331/21287458/9d1caa7a-c474-11e6-9a0e-04160ee03967.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/14153331/21287466/b93bf666-c474-11e6-97cf-26ee31b02948.png)

</details>

***System configuration***

Information | value
--- | ---
Browser: | Safari, Chrome
Adguard DNS: | None

Adguard filters: 
<img width="1034" alt="screen shot 2016-12-17 at 16 24 51" src="https://cloud.githubusercontent.com/assets/14153331/21287497/815d3074-c475-11e6-8c9a-c410ca05b6d5.png">

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1331072

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
