### ISSUE TITLE
askdavetaylor.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#37792]
`https://www.askdavetaylor.com/enable-windows-10-defender-ransomware-protection/`

Overlay annoyance:

![annoyance](https://user-images.githubusercontent.com/35470489/62267054-2b8ae280-b401-11e9-815c-539424e28c17.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by LucasDiTomase** [comment]
Please try this rule

askdavetaylor.com##.spu-box
