### ISSUE TITLE
video-download.online - Anti-Adblock Notification

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3779]
***Description***: Anti-Adblock notification appears on the following website:
https://video-download.online/
/Windows only/

Screenshot:
<details>

![screenshot 16](https://cloud.githubusercontent.com/assets/17504743/21288005/bacaf4bc-c480-11e6-90bb-5749b29c0264.png)

</details>

***System configuration***
Information | value
--- | ---
Operating system: | Microsoft Windows NT 10.0.14393.0
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Adguard filters: | English, Experimental, Russian, Spyware, Social media, Annoyance.

Ticket ID(if exists): 1468912

**Comment by Alex-302** [comment]
fixed
