### ISSUE TITLE
appshopper.com - iOS - Site/Redirection blocked

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3780]
***Site***: http://appshopper.com/photography/videoshop-video-editor-free
***Description***: Redirection to the App Store is blocked.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21288349/20932076-c481-11e6-89e7-7268d63035d7.png)

</details>

***Steps to reproduce the problem***: 
1. In the link above click on "Buy".
2. The redirection to the App Store is blocked.

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Browser: | Safari
Adguard version: | 1.1.2
Adguard driver (Windows): | -
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | -

Adguard filter | Version
--- | ---
English filter | 1.1.3.37
 Spyware filter | 1.0.9.61
 Social media filter | 1.0.15.59
 Annoyances filter | 1.0.7.95
 German filter | 1.0.29.39
 Mobile ads filter | 1.0.6.27
 Safari filter | 1.0.1.86

**Comment by Alex-302** [comment]
Not reproduced without Adguard DNS, only with it.
Please check:
```
@@||target.georiot.com^$domain=appshopper.com
```
`georiot.com` - excluded from DNS filter.

**Comment by danidoedel** [comment]
@Alex-302 Ahh I accidentally enabled the DNS filter... That was the issue. Thank you!
