### ISSUE TITLE
[Windows] www.telegraph.co.uk - anti adblock script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#3781]
![](http://i.imgur.com/nsFxsJu.png)
http://www.telegraph.co.uk/technology/0/ces-2017-expect/

**Adguard version**: 6.1.298.1564

**Operating system**: Windows 10

**Browser**: Chrome

``` @@||static.telegraph.co.uk/*/ads/ads.js ``` (https://static.telegraph.co.uk/develop/aem/ads/ads.js)

**Comment by Alex-302** [comment]
Added to annoyances.
