### ISSUE TITLE
[Windows] www.computerbase.de - ad leftover

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#3783]
![](http://i.imgur.com/YwWqkud.png)
https://www.computerbase.de/tests/

**Adguard version**: 6.1.298.1564

**Operating system**: Windows 10

**Browser**: Chrome

``` computerbase.de##.content-list > li:not([class="article"]) ```

**Comment by Alex-302** [comment]
Added
```
computerbase.de##.content-list > li:not([class])
```
