### ISSUE TITLE
cydiageeks.com - Social Widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3785]
***Site***: http://www.cydiageeks.com/best-cydia-tweaks-pokemon-go-jailbroken-iphone.html
***Description***: Social Widget not blocked/leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21290484/72f38afa-c4bc-11e6-9da3-c3c54ac52b79.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21290488/99b46c2c-c4bc-11e6-85ab-dc7c0f120044.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.37
 Spyware filter | 1.0.9.61
 Social media filter | 1.0.15.59
 Annoyances filter | 1.0.7.95
 German filter | 1.0.29.39
 Mobile ads filter | 1.0.6.27
 Safari filter | 1.0.1.86

**Comment by Alex-302** [comment]
Added to Social filter
```
cydiageeks.com##.nc_socialPanel
cydiageeks.com###conversions-box

```
