### ISSUE TITLE
Hope to add a Chinese filter

### ISSUE THREAD

**Issue by loveqqzj** [AdguardTeam/AdguardFilters#37869]
Hope to add a chinese filiter, it's very useful for many chinese webpages, his github homepage is https://github.com/YanFung/Ads.
The filiter address is https://raw.githubusercontent.com/YanFung/Ads/master/Mobile.txt
Please help to add it, thanks very much!

**Comment by krystian3w** [comment]
Try report also to `CNX Annoyance` / `EasyList China`?

**Comment by krystian3w** [comment]
Duplictate of https://github.com/AdguardTeam/FiltersRegistry/issues/216

**Comment by krystian3w** [comment]
Duplicate of https://github.com/AdguardTeam/FiltersRegistry/issues/216
