### ISSUE TITLE
hilfdirselbst.ch - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3786]
***Site***: http://www.hilfdirselbst.ch/foren/PDF_Einstellungen_ver%E4ndern_P554085.html and http://www.hilfdirselbst.ch/foren/Adobe_GoLive_Forum_1.html
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21290496/e78a745a-c4bc-11e6-8f5c-930c318ecad6.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21290499/fd597812-c4bc-11e6-8a8e-13c6e13e1098.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21290500/1aeedb24-c4bd-11e6-944f-b72a96abfb9e.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.37
 Spyware filter | 1.0.9.61
 Social media filter | 1.0.15.59
 Annoyances filter | 1.0.7.95
 German filter | 1.0.29.39
 Mobile ads filter | 1.0.6.27
 Safari filter | 1.0.1.86

**Comment by Alex-302** [comment]
Added to Ferman filter
```
hilfdirselbst.ch###r230
hilfdirselbst.ch###r231

```
