### ISSUE TITLE
applesfera.com

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardFilters#37879]
Recommended articles at the bottom of the page ( Annoyance )

Proposed rule to fix it

applesfera.com###editorialRecommendedPosts

![Captura de Pantalla 2019-08-02 a la(s) 08 30 02](https://user-images.githubusercontent.com/46760897/62367445-10eb6300-b500-11e9-9975-5e92f185685f.png)

**Comment by Alex-302** [comment]
ok
