### ISSUE TITLE
http://ustaninyemekleri.com - incorrect blocking 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#3788]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://ustaninyemekleri.com/m/v/kayseri-deki-patlama-aninin-goruntuleri-inanilmaz-allah-belanizi-versin/2076 - incorrect blocking, empty space instead of ads

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2016-12-18 at 10 08 50](https://cloud.githubusercontent.com/assets/23372054/21292328/f09cbb0a-c509-11e6-915f-778d91599b50.png)

</details>

***System configuration***

Application version: 1.1.1.54
Device: iPhone
OS: 10.1.1
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.72 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.19 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.97 Enabled=YES
ID=6 Name="German filter" Version=1.0.28.81 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.5 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.96 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.77 Enabled=YES

Ticket ID: 1469996

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
The website link responds as "404 not found" now, so I guess we can close the issue.
