### ISSUE TITLE
http://joeforamerica.com/ - sponsored content

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3790]
http://joeforamerica.com/2016/12/votd-another-tucker-carlson-victim/

![image](https://cloud.githubusercontent.com/assets/15856304/21292502/61a9c65c-c510-11e6-9e6c-d528db971e55.png)

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21292506/73609f42-c510-11e6-8591-977040d46b27.png)

**Comment by Alex-302** [comment]
Not reproduced, only small leftover.
Added
```
joeforamerica.com##.pan-ad-inline-adsense-left
```
