### ISSUE TITLE
paycard.beeline.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3791]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
в личном кабинете платежной карты билайн https://paycard.beeline.ru/personal/ads 
при включеной защите не отображаются ссылки для перехода на сайты на которых можно при
оплате получить бонусы на эту карту (сайт *paycard.beeline.ru* добавлен в исключения ).

При выключении фильтра счетчика и системы аналитики  начинает все отображаться. 

***System configuration***

Information | value
--- | ---
Operating system: | ВИН
Browser: | Хром
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | TDI
Adguard DNS: | None

Фильтры: 
![image](https://cloud.githubusercontent.com/assets/18548949/21292718/b7f79f38-c516-11e6-8dc6-27e31ff5c99c.png)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1310523

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Проверить не на чем.
Исключение такое?
```
@@||paycard.beeline.ru^$document
```

**Comment by vgavrish** [comment]
у меня добавлено вот такое правило  @@||paycard.beeline.ru$document
Попробовал с правилом: @@||paycard.beeline.ru^$document
То та же проблема
вот видео записал https://yadi.sk/i/h92_6Y4p34PPyQ

**Comment by Alex-302** [comment]
Отключение фильтров помогает?

**Comment by Alex-302** [comment]
Пусть оставит только фильтр, которые ломает, откроет журнал и перейдёт на поломанную страницу(предварительно очистив журнал). Затем нужно выбрать опцию, чтоб показывало заблокированное, и сделать скриншот.

**Comment by evgeniy-ADG** [comment]
![2016-12-27_060517](https://cloud.githubusercontent.com/assets/15856304/21499723/fd62ab86-cc40-11e6-931d-82ae7a611bc9.png)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
пожно попробовать дополнительно исключить
```
@@||actions.cardbeeline.xyz^$document
```
