### ISSUE TITLE
pcmag.com - Ad - Ad leftover - Social widget leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3792]
***Site***: http://uk.pcmag.com/smartphones/77654/feature/how-to-record-the-screen-on-your-pc-phone-or-tablet
***Description***: Ad, Ad leftover and social widget leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21292975/eb7d9aa6-c516-11e6-8868-4dc9b9d8b4e6.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21292985/2f7c75b0-c517-11e6-8f22-131f58a56e0d.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.41
 Spyware filter | 1.0.9.61
 Social media filter | 1.0.15.59
 Annoyances filter | 1.0.7.95
 German filter | 1.0.29.39
 Mobile ads filter | 1.0.6.27
 Safari filter | 1.0.1.86

**Comment by Alex-302** [comment]
added
```
pcmag.com#$##adkit_billboard { padding-top: 0px!important; }
uk.pcmag.com##.social300
pcmag.com###uswitch_widget_container
```
