### ISSUE TITLE
gospelprime.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#37942]
`https://www.gospelprime.com.br/o-bom-mocismo-do-padre-fabio-de-melo/`

Newsletter overlay while scrolling up and down.

![gospelprime](https://user-images.githubusercontent.com/35470489/62411322-6e96b280-b5c7-11e9-9e31-d4e544f00178.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by pradorocchi** [comment]
Filter rule needed to block:

gospelprime.com.br###simplemodal-container
