### ISSUE TITLE
sciencedaily.com - Mobile Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3794]
***Site***: https://www.sciencedaily.com/releases/2016/12/161213161051.htm
***Description***: Ad leftover

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21293036/dfd306da-c518-11e6-88e8-977e1f5c5bac.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21293039/f83551ba-c518-11e6-91d1-b7a70e12f9f0.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21293040/0950805a-c519-11e6-9b87-16d94e1626c1.png)

</details>

***Steps to reproduce the problem***: -

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.41
 Spyware filter | 1.0.9.61
 Social media filter | 1.0.15.59
 Annoyances filter | 1.0.7.95
 German filter | 1.0.29.39
 Mobile ads filter | 1.0.6.27
 Safari filter | 1.0.1.86

**Comment by Alex-302** [comment]
Added to English filter
```
giveaway-club.com##.b-spot-adsense
giveaway-club.com###today-giveaway > div[style="width: 960px;height:310px;overflow:hidden;"]

```

**Comment by danidoedel** [comment]
@Alex-302 That white space ad leftover is still there.

**Comment by Alex-302** [comment]
added
```
giveaway-club.com##.mobile-top-rectangle
```

**Comment by danidoedel** [comment]
@Alex-302 Ad leftover still there:

```
sciencedaily.com##.mobile-top-rectangle
sciencedaily.com##.mobile-middle-rectangle
sciencedaily.com##.mobile-bottom-rectangle
```

**Comment by Alex-302** [comment]
Added. Previous rule has wring domain.
