### ISSUE TITLE
http://www.giveaway-club.com/ - incorrect blocking, ad leftovers

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3795]
http://www.giveaway-club.com/

Leftovers:

![image](https://cloud.githubusercontent.com/assets/15856304/21293089/bba0570e-c522-11e6-8bb1-823de87ecd69.png)

the button doesn't work:

![image](https://cloud.githubusercontent.com/assets/15856304/21293091/c9081ea4-c522-11e6-97e3-0f39dc677b91.png)

<details>

Win, Mac, Chrome. Aнглийский, счётчиков и системы аналитики, виджетов социальных сетей, раздражителей, полезной рекламы и русский

**Comment by Alex-302** [comment]
Not reproduced. Check again.
