### ISSUE TITLE
compress.ru - Missed ads

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3796]
***Description***: Missed ads on the website:
http://compress.ru/article.aspx?id=9633#10

Screenshot:
<details>

![kymqlmbbqu4](https://cloud.githubusercontent.com/assets/17504743/21294804/f719ddce-c54e-11e6-84e9-2a1664628e33.jpg)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android: 6.0.1
Browser: | Chrome
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
Adguard filters: | Reproduced with English, Spyware, Social media filter, Annoyances, Russian, Spanish, Mobile ads.

Ticket ID(if exists): 1142980

**Comment by Alex-302** [comment]
Added to Mobile filter
```
compress.ru##div[class^="baner-top"]
compress.ru##.right-sidebar
```
