### ISSUE TITLE
extratorrent.cc - news blocked

### ISSUE THREAD

**Issue by MarkoXD** [AdguardTeam/AdguardFilters#3797]
I can't view news on Extra Torrent when Adguard Browser Extension is enabled. When I disable it, I can view news articles normally.

Activated filters:
- English filter
- Spyware filter
- Social filter
- Annoyances filter
- EasyPrivacy
- Adblock Warning Removal List
- Anti-Adblock Killer | Reek
- I don't care about cookies
- Malware Domains

![screenshot_1](https://cloud.githubusercontent.com/assets/7421544/21295223/b7d9ad18-c550-11e6-9c24-e74ef1bca616.png)

**Comment by Alex-302** [comment]
not reproduced. Which filter causes it?

**Comment by MarkoXD** [comment]
Looks like English filter. When I disable it news article is visible but ads not blocked.

**Comment by Alex-302** [comment]
Try to disable all filters and enable them one-by-one with checking.
Or provide me remote access via TeamViewer:)

**Comment by Alex-302** [comment]
@seanl-adg could you check it?

**Comment by MarkoXD** [comment]
_"Try to disable all filters and enable them one-by-one with checking."_

I did. English filter is making problems.

**Comment by Alex-302** [comment]
@MarkoXD ok
try:
```
@||extratorrent.cc^$generichide
```
or
```
@||extratorrent.cc^$elemhide
```
or
```
@||extratorrent.cc^$urlblock
```

**Comment by MarkoXD** [comment]
None of them work.

**Comment by Alex-302** [comment]
Another ad blockers?

**Comment by MarkoXD** [comment]
I have only Adguard installed.

**Comment by Alex-302** [comment]
Huh.. What about TeamViewer?

**Comment by MarkoXD** [comment]
Looks like something was in my user filter that blocked it. It works now. Thanks anyway.
![screenshot_1](https://cloud.githubusercontent.com/assets/7421544/21458000/8dafdaee-c933-11e6-906c-2e6b1b50079f.png)

**Comment by Alex-302** [comment]
ok then
