### ISSUE TITLE
Yandex Weather app - Incorrect blocking

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3798]
***Description***: Precipitation map is blocked in the Yandex Weather app. The issue is probably caused by Mobile ads filter. 

***System configuration***

Information | value
--- | ---
Operating system: | Android: 6.0.1
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
Adguard filters: | Reproduced with English, Spyware, Social media filter, Annoyances, Russian, Spanish, Mobile ads.

Ticket ID: 1106197
Ticket ID: 1469444

**Comment by Alex-302** [comment]
Карты не вижу и без Адгарда. Скрин в студию.

**Comment by vgavrish** [comment]
отписала сюда 1469444

**Comment by vgavrish** [comment]
надо добавить город Одинцово, потом будет там строка "карта осадков"
но такое как у юзера на скринах нету
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/21349217/5b4ab956-c6b9-11e6-90e8-6225844317bf.png)
юзера
![image](https://cloud.githubusercontent.com/assets/18548949/21349303/e30edc14-c6b9-11e6-860e-b9241b2f5a16.png)
![image](https://cloud.githubusercontent.com/assets/18548949/21349306/e7c49668-c6b9-11e6-91ae-dbf1a7f19cfb.png)

**Comment by Alex-302** [comment]
@vgavrish а как её открыть-то? Нигде не могу найти.

**Comment by Alex-302** [comment]
Карту нашёл. но проблема не повторилась.
Попроси проделать следующее:
- выключить все фильтры, закрыть приложение и проверить снова
Поможет - пусть вернёт фильтры и запишет лог HTTP запросов. Если не поможет:
- выключить фильтрацию HTTPS

**Comment by vgavrish** [comment]
я там выше писала, что помогает отключение Мобильного фильтра
и https у юзера не включена
по этому спрашиваю лог:)

**Comment by Alex-302** [comment]
ок, тогда нужен лог только с мобильным фильтром.
Если, конечно, не попросила уже с его фильтрами)

**Comment by Yana-SUP** [comment]
[debug (5).txt](https://github.com/AdguardTeam/AdguardFilters/files/664476/debug.5.txt)

время 16:20

**Comment by Alex-302** [comment]
Вот правила, нужно в пользовательском фильтре проверить(добавить копи-пастой, не вручную набирать):
```
@@||settings.crashlytics.com^
@@||analytics.mobile.yandex.net^
@@||banners.mobile.yandex.net^
@@||mobile.yandexadexchange.net^
```
Если поможет - удалять по одному с проверкой. Так вычислим, что именно нужно исключить.

**Comment by Yana-SUP** [comment]
спасибо, отписала 1469444

**Comment by vgavrish** [comment]
> Не сработало. Включил фильтр мобильной рекламы. Добавил 4 правила. Не работает. Удалял по одному. Не работает карта погоды с этими правилами и включенным фильтром.

**Comment by Alex-302** [comment]
А с фильтрацией HTTPS?
Я ни в каком случае повторить не могу.

**Comment by vgavrish** [comment]
всмысле включить HTTPS? 
(у него сейчас отключена)

**Comment by Alex-302** [comment]
ну да, включить и проверить

**Comment by vgavrish** [comment]
@Alex-302 никто не отписался:(
вобщем правила сработали с HTTPS фильтрацией

еще один пользователь появился, с той же проблемой и фильтром
отписала ему о правилах

**Comment by Alex-302** [comment]
Странные дела. Ждём лог тогда.

**Comment by vgavrish** [comment]
говорит пользователь Яндекс. Погода обновила приложение и все работает

**Comment by Alex-302** [comment]
на другом формуме разобрались
