### ISSUE TITLE
https://toneto.net/ - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3799]
Пропущена реклама на странице: https://toneto.net/news/tehnologii/LG-Display-postavit-skladnie-OLED-ekrani-Apple--Google-i-Microsoft

Всплывающее окно на всю страницу
<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21303490/6ceea566-c5c7-11e6-960d-6ba47e8e5431.png)

</details>

<details>
Application version: 1.1.1.54
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: 742919A0-EF43-41E8-AB02-4B503827AF9A

Locale: ru
Region: ua

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.1.35 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.16 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.83 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.43.37 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.75 Enabled=YES

</details>

Ticket ID: 1465478

**Comment by Alex-302** [comment]
С этими же фильтрами не повторилось.

**Comment by Alex-302** [comment]
На декстопе неплохо бы повторить. Подключился бы и поправил.
