### ISSUE TITLE
[iOS] mobil.hurriyet.com.tr

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#3800]
Missed ad remainer.

Filters in use: ENGLİSH, SPYWARE, SOCIAL MEDIA, Annoyances, Mobile Ads, SAFARI, TURKISH, EASYLIST.

Screenshot: https://i.hizliresim.com/DB2rv1.jpg

Inviting @tagataho

**Comment by vbagirov** [comment]
Also, this video is claimed to not work: http://mobil.hurriyet.com.tr/video/140694

**Comment by Alex-302** [comment]
Not reproduced.
Video is not vorking even without Adguard.

**Comment by tagataho** [comment]
@Alex-302
No; videos are working without adguard. I tested.

**Comment by tagataho** [comment]
@alex-302
1- without adguard
http://i.hizliresim.com/njR2g0.jpg

2- within adguard
http://i.hizliresim.com/vXbRLv.jpg

**Comment by Alex-302** [comment]
@tagataho Which filter causes it? Try to disable them one-by-one.

**Comment by tagataho** [comment]
@alex-302
I tried as one by one.
There are three filters which make trouble the videos.

1- English
2- Mobile
3- Easylist

In my opinion; All knowledge turkish website's videos affect that.

**Comment by Alex-302** [comment]
Still can't reproduce.
@vozersky please check it

**Comment by tagataho** [comment]
I think that this filters block ads which after the videos; so it block the videos.

**Comment by Alex-302** [comment]
@tagataho 
please add test rule
```
@@google
```
and check again

**Comment by tagataho** [comment]
@alex-302 it worked on m.hurriyet.com.tr when i add this rule; but why did not add the rule  in filters?

**Comment by Alex-302** [comment]
It is too wide,
Try this
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=hurriyet.com.tr
```
if it will not helps, add this
```
@@||imasdk.googleapis.com^$domain=hurriyet.com.tr
```

**Comment by tagataho** [comment]
No; not working; stil not open video in mobile

http://mobil.hurriyet.com.tr/cem-yilmaz-ile-cansu-dere-ayni-karede-40367579

**Comment by Alex-302** [comment]
It doesn't work on my side without ad blocking
<details>

![image](http://imagizer.imageshack.com/img922/1925/p4W3GY.png)
</details>
