### ISSUE TITLE
[iOS] Social buttons on Onedio.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#3801]
Filters in use: ENGLİSH, SPYWARE, SOCIAL MEDIA, Annoyances, Mobile Ads, SAFARI, TURKISH, EASYLIST.

Screenshot: https://i.hizliresim.com/LZAXA1.jpg

Inviting @tagataho

**Comment by Alex-302** [comment]
Added to Social filter
```
onedio.com##.floating-social
```
