### ISSUE TITLE
[iOS] m.ensonhaber.com social Buttons and unneeded bar

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#3802]
Filters in use: ENGLİSH, SPYWARE, SOCIAL MEDIA, Annoyances, Mobile Ads, SAFARI, TURKISH, EASYLIST.

Screenshot: https://i.hizliresim.com/1Vv38A.jpg

Inviting @tagataho

**Comment by Alex-302** [comment]
For user filter only:
```
m.ensonhaber.com##.head.cf
m.ensonhaber.com##.menu.cf
```
