### ISSUE TITLE
[iOS] m.sporx.com social Buttons

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#3804]
Unnecessary and useless Social buttons/bar.

Filters in use: ENGLİSH, SPYWARE, SOCIAL MEDIA, Annoyances, Mobile Ads, SAFARI, TURKISH, EASYLIST.

Screenshot: https://i.hizliresim.com/Er80P8.jpg

Inviting @tagataho

**Comment by Alex-302** [comment]
Not a social button.
For user filter:
```
m.sporx.com##.back-to
```
