### ISSUE TITLE
[iOS] m.sondakika.com and other websites

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#3805]
Videos do not open on this website and others:

http://m.sondakika.com/haber/haber-onundei-haber-metnini-okuyamayan-nevsin-mengu-9059901/

http://m.haberler.com/onundeki-haber-metnini-okuyamayan-nevsin-mengu-9059901-videosu/

http://m.medyafaresi.com/video/nevsin-mengu-canli-yayinda-sinirlendi/799657

http://m.a24.com.tr/video/nevsin-mengu39nun-zor-anlari-16399.html?v=0

http://m.internethaber.com/buraya-unlu-olmaya-geldim-deyince-video-galerisi-1738746.htm

Old task: https://github.com/AdguardTeam/AdguardForiOS/issues/295

Filters in use: ENGLİSH, SPYWARE, SOCIAL MEDIA, Annoyances, Mobile Ads, SAFARI, TURKISH, EASYLIST.

Inviting @tagataho

**Comment by Alex-302** [comment]
1,2,4 - works

**Comment by tagataho** [comment]
@alex-302
No; now 4-5 work

1-2-3 not work

**Comment by Alex-302** [comment]
2,
Try
```
@@||m.haberler.com/static/advertisement/ads_ima.js$domain=m.haberler.com
@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$domain=m.haberler.com
```
1 - working
3 - not working without Adguard

**Comment by tagataho** [comment]
@alex-302
I tried as one by one.
There are three filters which make trouble the videos.

1- English
2- Mobile
3- Easylist

If i disable this filters; the problem can solved. But i do not want disable; please fix it.

**Comment by Alex-302** [comment]
So you can reproduce it only with Mobile filter?

**Comment by Alex-302** [comment]
Are you using full on simplified rules?

**Comment by tagataho** [comment]
I use most of them ; but i disabled everyone; then i check one by one.

English
Easylist
Mobile
This filters block the videos all websites.

**Comment by Alex-302** [comment]
try the same
https://github.com/AdguardTeam/AdguardFilters/issues/3800#issuecomment-269209739

**Comment by tagataho** [comment]
@alex-302 when i add the test rule;
http://m.sondakika.com/haber/haber-onundei-haber-metnini-okuyamayan-nevsin-mengu-9059901/
(Not worked)


http://m.haberler.com/onundeki-haber-metnini-okuyamayan-nevsin-mengu-9059901-videosu/
(Before the video; opened ad page and i saw another one ad for 10sec on area of video.)

It worked on the other websites in first message.

We have gone a long way in this; thanks for helping. There are 1-2 step to solve the problem.

In addition; Why did not add this test rule in filters?

**Comment by Alex-302** [comment]
It is too wide,
Try this
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js
```
if it will not helps, add this
```
@@||imasdk.googleapis.com^
```
