### ISSUE TITLE
Adguard is not able to whitelist googleleadservices.com

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#3806]
http://googleleadservices.com/
android 6.0.1 
adg 2.8.67
when you add googleleadservices.com to whitelist you can't open the site
<details>

![screenshot_20161216-102324](https://cloud.githubusercontent.com/assets/23637588/21315273/6c91408e-c60c-11e6-9b26-4c0c04df309e.png)

</details>

id 1466427

**Comment by ameshkov** [comment]
Weird error code: `ERR_QUIC_PROTOCOL_ERROR`.

What for another browsers?

**Comment by Alex-302** [comment]
I can't reproduce it on Android 5.1.1

**Comment by taylortracey** [comment]
Original issue poster here. For clarification, I am using Android version 6.0.1, Android security patch level October 1, 2016.

**Comment by ameshkov** [comment]
Ah, I think i got it.

Instead of adding it to whitelist, try adding this rule to your user filter:
`@@||googleleadservices.com`

`@@` chars means literally "do not block URLs starting with this"

**Comment by ameshkov** [comment]
I've just took a look at the ticket and it seems that you were omitting `@@` mark.

**Comment by taylortracey** [comment]
Hi.

If you read back through the ticket thread, there was this part of the
conversationsection:

> > > On Fri, Dec 16, 2016 at 6:40 AM, Support Team
> > > wrote:
> > >
> > > > Hello!
> > > >
> > > > Sorry for the inaccurate suggestion, my bad. Could you please do the
> > same
> > > > in the User filter? Or add exceptions to the whitelist without extra
> > > > symbols, just add a domain.
> > > >
> > > > Sincerely yours,
> > > > Adguard Support Team
> > > >
> > > >
> > > > On Wed, 14 Dec 2016 23:50:30 +0300, Taylor@ccil.org Taylor wrote:
> > > > > Thanks for your reply. I tried to add each of the following
strings:
> > > > >
> > > > > @@||googleleadservices.com$document
> > > > > AND
> > > > > @@||googleleadservices.com
> > > > >
> > > > > Both produced the error "The domain name is not valid".
> > > > >
> > > > > Any other suggestions?
> > > > >
> > > > > -Tracey

-Tracey
___________________________

**Comment by taylortracey** [comment]
If you read through all the emailed conversation thread about this issue,
you'll see that I was already instructed to add the symbols, which I did,
and reported errors. Then, the suggesting person said to remove the
symbols.

I'd appreciate if you would each read through everything before telling me
the same things over and over. I appreciate the suggestions, but not when
they've already been tried and produced errors.

Thanks,
-Tracey
_____________________________________

> > > On Fri, Dec 16, 2016 at 6:40 AM, Support Team
> > > wrote:
> > >
> > > > Hello!
> > > >
> > > > Sorry for the inaccurate suggestion, my bad. Could you please do the
> > same
> > > > in the User filter? Or add exceptions to the whitelist without extra
> > > > symbols, just add a domain.
> > > >
> > > > Sincerely yours,
> > > > Adguard Support Team
> > > >
> > > >
> > > > On Wed, 14 Dec 2016 23:50:30 +0300, Taylor@ccil.org Taylor wrote:
> > > > > Thanks for your reply. I tried to add each of the following
strings:
> > > > >
> > > > > @@||googleleadservices.com$document
> > > > > AND
> > > > > @@||googleleadservices.com
> > > > >
> > > > > Both produced the error "The domain name is not valid".
> > > > >
> > > > > Any other suggestions?
> > > > >
> > > > > -Tracey


-Tracey
​___________________________

**Comment by evgeniy-ADG** [comment]
@ameshkov we add it with @@|| in a user filter, without - in a whitelist, correct?

**Comment by ameshkov** [comment]
@taylortracey, of course, I read it, but I have also read the log file and saw there that domain was not properly unblocked.

This line indicates that it was blocked, which is impossible if the rule is added properly.
```
15:21:02.815 [pool-3-thread-5555] DEBUG com.adguard.android.FilteringLog - TCP id=194219 CONNECT ads=1 https://www.googleadservices.com/ com.android.chrome 0 0
```

So, this rule should be added to the User filter in order to unblock that domain:
```
@@||googleadservices.com
```


@evgeniy-ADG it is always better to use the User filter. Also in this particular case whitelist won't help.

**Comment by taylortracey** [comment]
Once again, as I've told you previously, adding the filter per your
instructions does not work to allow access to the site.

(Screenshot attached)

This filter, as you have stipulated, been in place since the second email.
I have even tried adding in various permutations of that string, also to no
affect.

- Tracey
(mobile)
_________________________

**Comment by taylortracey** [comment]
Ah hah! Google has conjoined their wording, yet I was properly spelling and
combining "Google Lead Services", yet they smuushed it together as
"Googlead Services". I'm an editor, so I have a tough time deliberately
misspelling things. I am uodating my User Filter now.

- Tracey
(mobile)
_________________________

**Comment by taylortracey** [comment]
My apologies! Your formatting and instruction was correct. Once I
reproduced Google's odd spelling in the filter, the sites were properly
unblocked.

I am sorry for my frustration. I don't know whether you recognized the
difference between my whitelisted site name spelling and Google's.

Thank you for your persistence and patience!

- Tracey
(mobile)
_________________________

**Comment by ameshkov** [comment]
No worries, I am glad it works now! Happy new year:)
