### ISSUE TITLE
BFM Paris by NextRadioTV - ads #296

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#3807]
VPN DNS does not work on BFMParis application: BFM Paris by NextRadioTV
https://appsto.re/us/r2Bxfb.i

<details>

![image1](https://cloud.githubusercontent.com/assets/15856304/21190580/f49195f0-c22a-11e6-9aa9-1e3c1fc4eef2.PNG)

![image2](https://cloud.githubusercontent.com/assets/15856304/21190588/fc5133a4-c22a-11e6-91a9-58b6c47de67d.PNG)

</details>

State and logs: 1021351

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by evgeniy-ADG** [comment]
We have logs and screenshots in the same ticket: 1021351, Feb 3 ticket. Please advise. 
I managed to reproduce something similar, open an article, watch a video and then swipe right to the next article. This opens instead od an article:

<details>

![file_000 3](https://cloud.githubusercontent.com/assets/15856304/22625284/5c131454-eb9a-11e6-98f1-3f76cf801c79.png)
