### ISSUE TITLE
battle.net - Incorrect blocking

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3808]
***Description***: Incorrect blocking on the website:
battle.net

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/17504743/21325737/6ae032e4-c630-11e6-8312-6c2bd8f12ab4.png)
</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android (Reproduced on Mac)
Browser: | Chrome
Adguard version: | 2.8.76
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On
Adguard filters: | Reproduced with English, Russian, Experimental, Annoyance, Spyware, Social media. 

Ticket ID(if exists): 1073595

**Comment by Alex-302** [comment]
а где прямая ссылка?

**Comment by Tetiana2020** [comment]
@Alex-302 так это она и есть - battle.net
или обязательно eu.battle.net/ru/ ?
Проблема на Android и Mac. На Windows все ок.

**Comment by Alex-302** [comment]
@Tetiana2020 т.е. и на главной так же?

**Comment by Alex-302** [comment]
ага, повторил

**Comment by Alex-302** [comment]
@Tetiana2020 
передай юзеру. 
`@@||battle.net^$document`
Решение временное, в новой версии баг будет исправлен.

**Comment by Tetiana2020** [comment]
@Alex-302 сасибо. передала.
