### ISSUE TITLE
 EssentialPIM Free app - Missed ads

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3809]
***Description***: Missed ads in the application  EssentialPIM Free on Windows.

Screenshot:
<details>

![epim 1](https://cloud.githubusercontent.com/assets/17504743/21344844/7f843166-c6a6-11e6-8c1f-570b7d84b911.png)

![epim 2-2](https://cloud.githubusercontent.com/assets/17504743/21344841/7d4d7010-c6a6-11e6-9d98-e6aff2f0e83d.png)

</details>

Asked to send system configurations. Will edit as soon as I get those

***System configuration***

Ticket ID(if exists): 1419169

**Comment by Alex-302** [comment]
Встроено в программу.
