### ISSUE TITLE
mcdonalds.com - Incorrect blocking

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3810]
***Description***: Incorrect blocking on the website:
www.mcdonalds.com.tr

The issue is caused by Turkish filter.

Screenshot:
<details>

![mc](https://cloud.githubusercontent.com/assets/17504743/21348706/013f4988-c6b7-11e6-9218-5258a4230b54.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows NT 10.0.14393.0
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Stealth mode options(Windows) |  "BlockThirdPartyCookies": true,  "BlockThirdPartyCookiesPeriodMin": 30,  "BlockFirstPartyCookies": false,  "BlockFirstPartyCookiesMin": 2880,  "DisableThirdPartyCache": false, "BlockWebRtc": false,  "BlockBrowserPushApi": false,  "BlockBrowserLocationApi": true,  "RemoveXClientDataHeader": true,  "HideSearchQueries": true,  "SendDoNotTrackHeader": true,  "RemoveRefererFromThirdPartyRequests": false,  "HideUserAgent": false,  "CustomUserAgent": null,  "CustomReferer": null,  "HideIp": false,  "CustomIp": "209.141.53.254"
Adguard filters: |  English, Spyware, Social media, Experimental, Turkish, Annoyances. 

Ticket ID(if exists): 1334723

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
