### ISSUE TITLE
Удаление рекламы с сервиса Яндекс Музыка (bug, feature request, compatibility)

### ISSUE THREAD

**Issue by decagon82** [AdguardTeam/AdguardFilters#38100]
Здравствуйте. 

На сайте Greasy Fork есть полезный скрипт который удаляет достающее всплывающее уведомление и пустой баннер сверху у тех у кого нету платной подписки на сервисе Яндекс Музыка. 

Внимание если у вас есть подписка на сервисе Яндекс Музыка и вы вышли со своего аккаунта чтобы протестировать как работает реклама на этом сайте, то почистите куки и кеш или зайдите с другого браузера.

В данный момент AdGuard это всплывающее уведомление и верхний пустой баннер не блокирует к сожалению, и об этом очень часто пишут пользователи на форуме.

Примечательно то что в коде скрипта оочень мало строк. Поэтому хотелось бы чтобы разработчики посмотрели на этот код и что-то подобное или тоже самое внедрили в AdGuard в ближайшие сроки.

Работа скрипта была протестирована @Chinaski1 и мною @decagon82.

### Ссылка на сам скрипт:
https://greasyfork.org/ru/scripts/387870-yanex-music-adsplus-disable/code

### Скриншот:
https://ibb.co/QnKZm1T

### Мои логи находятся под ID поддержки: 
В ожидании письма на почту.

**Comment by Alex-302** [comment]
@decagon82 сверху не повторяется. 
Проверьте для баннера справа:
```
music.yandex.ru##.sidebar div.teaser-autoplaylist ~ div:nth-child(3)
music.yandex.ru##.sidebar div.teaser-autoplaylist ~ div:nth-child(4)
```

**Comment by decagon82** [comment]
Прошу не использовать данный скрипт. А просто добавить в AdGuard фильтр следующие правила:

1 - music.yandex.ru##div.page-root.page-root_no-player.deco-pane-back > div[class][data-b="2"][style="display: block;"]
2 - music.yandex.ru##div.notify > div.deco-tooltip_notify.notify_shown

Первое убирает пустой блок сверху,
Второе всплывающие уведомление о том что включен блокировщик рекламы.

Так же в правом блоке иногда всплывает баннер "Семейная подписка. Яндекс+" можно убрать таким правилом:
1 - music.yandex.ru##a.teaser__content[href="https://music.yandex.ru/family-plus"] > img.teaser__img

Важно обращать на регион! Если вы с Казахстана то требуются такие же правила для сайта music.yandex.kz 

За правила огромное спасибо - @zovihuxij

**Comment by decagon82** [comment]
> @decagon82 сверху не повторяется.
> Проверьте для баннера справа:
> 
> ```
> music.yandex.ru##.sidebar div.teaser-autoplaylist ~ div:nth-child(3)
> music.yandex.ru##.sidebar div.teaser-autoplaylist ~ div:nth-child(4)
> ```

Вот это правило не работает - music.yandex.ru##.sidebar div.teaser-autoplaylist ~ div:nth-child(3)

А это правило смогло успешно убрать синюю надпись "Отключить рекламу" -music.yandex.ru##.sidebar div.teaser-autoplaylist ~ div:nth-child(4)

Спасибо @Alex-302

**Comment by decagon82** [comment]
В общем итоговый список правил для сайта Яндекс Музыка:

music.yandex.ru##div.page-root.page-root_no-player.deco-pane-back > div[class][data-b="2"][style="display: block;"]
music.yandex.ru##div.notify > div.deco-tooltip_notify.notify_shown
music.yandex.ru##a.teaser__content[href="https://music.yandex.ru/family-plus"] > img.teaser__img
music.yandex.ru##.sidebar div.teaser-autoplaylist ~ div:nth-child(4)
music.yandex.kz##div.page-root.page-root_no-player.deco-pane-back > div[class][data-b="2"][style="display: block;"]
music.yandex.kz##div.notify > div.deco-tooltip_notify.notify_shown
music.yandex.kz##a.teaser__content[href="https://music.yandex.ru/family-plus"] > img.teaser__img
music.yandex.kz##.sidebar div.teaser-autoplaylist ~ div:nth-child(4)
music.yandex.com##div.page-root.page-root_no-player.deco-pane-back > div[class][data-b="2"][style="display: block;"]
music.yandex.com##div.notify > div.deco-tooltip_notify.notify_shown
music.yandex.com##a.teaser__content[href="https://music.yandex.ru/family-plus"] > img.teaser__img
music.yandex.com##.sidebar div.teaser-autoplaylist ~ div:nth-child(4)

Просьба разработчиков проверить и добавить в официальный фильтр

**Comment by Alex-302** [comment]
нужны страницы, на которых эти правила срабатывают.
`:nth-child` лучше избегать

**Comment by zovihuxij** [comment]
@Alex-302 ,
```
music.yandex.ru##div.page-root.page-root_no-player.deco-pane-back > div[class][data-b="2"][style="display: block;"]
music.yandex.ru##div.notify > div.deco-tooltip_notify.notify_shown
music.yandex.ru##a.teaser__content[href="https://music.yandex.ru/family-plus"] > img.teaser__img
```
Эти правила работают на всех страницах. nth-child правила не добавляй - они ломают сайт.

**Comment by Alex-302** [comment]
напиши для чего каждое? Желательно со скринами, чтоб потом не гадать.

**Comment by zovihuxij** [comment]
![Аннотация 2019-08-08 234937](https://user-images.githubusercontent.com/20907093/62737027-8d69ce80-ba37-11e9-8852-61bdc6cd7a9f.png)
![Аннотация 2019-08-08 235024](https://user-images.githubusercontent.com/20907093/62737034-93f84600-ba37-11e9-9589-0df2f3e41e70.png)
![Аннотация 2019-08-08 235123](https://user-images.githubusercontent.com/20907093/62737044-978bcd00-ba37-11e9-9535-12c04133c0d0.png)
```
! Пустой блок в шапке
music.yandex.ru##div.page-root.page-root_no-player.deco-pane-back > div[class][data-b="2"][style="display: block;"]
! Включен блокировщик рекламы
music.yandex.ru##div.notify > div.deco-tooltip_notify.notify_shown
! Семейная подписка. Яндекс+
music.yandex.ru##a.teaser__content[href="https://music.yandex.ru/family-plus"] > img.teaser__img
```

**Comment by Alex-302** [comment]
ок, добавил

**Comment by Alex-302** [comment]
Закрыл как повтор.
