### ISSUE TITLE
goodgame.ru 

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3811]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
При попытке входа на сайте, страница просто не загружается 

> только после выключения Антибанера сайт нормально стал загружаться
> Сайт загружает пустую страницу при входе на него, хотя  с другими сайтами подобной проблемы нет, только с сайтом goodgame.ru. 

**Помогает отключение Английского фильтра**

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21349569/4cc288ee-c6bb-11e6-9bac-02d0022eb886.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21349572/511a606a-c6bb-11e6-8beb-a24eaf302d9e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Опера
Adguard version: | 6.1.298.1564
Adguard driver (Windows): |  TDI
Adguard DNS: | None
Stealth mode options(Windows) | none
Adguard filters: | Russian, English, Liste FR , Adblock polskie reguły

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1468956

может если понадобятся логи 
https://yadi.sk/d/-jh8MZx_349XUb

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня не повторяется.
Вижу он исключение добавлял
```
@@||goodgame.ru$document
```
Оно помогало?

Попроси проверить с англ и русским, но с выключенным пользовательским.

**Comment by vgavrish** [comment]
> Нет,  данный сайт не находился у меня в исключениях, при отключении "пользовательского фильтра" изменений никаких не было. Попробовал сейчас полностью удалить и переустановить программу, вроде помогло. Посмотрим как дальше будет. 

у другого пользователя та же проблема (1054468). Я ж там раньше писала, что помогало отключение Английского фильтра

**Comment by Alex-302** [comment]
А у тебя повторяется? Доступ бы получить.

**Comment by vgavrish** [comment]
у меня не повторяется, нужен акк я так понимаю, чтобы повторить
пользователю отписала
