### ISSUE TITLE
EssentialPIM Free Portable

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3812]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
Поставил портативную версию EssentialPIM Free, внёс исполняемый файл в список фильтруемых приложений, но реклама о возможностях версии Pro не исчезла (в правом верхнем углу раздела “Почта” EssentialPIM). Реклама маленькая, но совершенно ненужная.
Может ли всё-таки бравый Эдгард изничтожить её (но чтобы почта работала)?

Скачать EssentialPIM Free Portable можно тут:
http://www.essentialpim.com/download/EssentialPIMPort7.zip

или тут напрямую:
http://download.cnet.com/EssentialPIM-Portable/3001-2124_4-10497313.html

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21350766/d7e8e55c-c6c1-11e6-886e-80d5a562dbe6.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21350770/dc4dc52c-c6c1-11e6-9709-278e18f543eb.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard DNS: | None
Adguard filters: | 1,2,3,4,10,14
Stealth mode options(Windows) |  
![image](https://cloud.githubusercontent.com/assets/18548949/21350807/172720d0-c6c2-11e6-9e10-437d3fccdd64.png)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1419169

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Было уже. Реклама встроена.
