### ISSUE TITLE
Blockade

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#38124]
@nettw commented on [Tue Aug 06 2019](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/109)

@Alex-302 

### Steps to reproduce

Hi,

I hope that you put these lists into the filter and block them in the file, thank you!
||global.adserver.yahoo.com^
||tw.adserver.yahoo.com^
||ailiyou1999.com^
||snyowx29.com^
||tuigang1999.com^
||victory1999.com^

### Expected behavior

They are the ad server that must be blocked.

### Actual behavior

Has not been added yet.

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default
| How did you setup DNS configuration:| System
| Device model:| Samsung Galaxy A7 2018
| Operating system and version:| Android 9

---

@Alex-302 commented on [Tue Aug 06 2019](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/109#issuecomment-518673801)

Hi. I need more details. Where are they used?

**Comment by nettw** [comment]
@Alex-302 
Hi,
Both belong to the Chinese advertising server.

These two are used inside Chinese Yahoo.
||global.adserver.yahoo.com^
||tw.adserver.yahoo.com^

This is an advertising service provider in mainland China.
|ailiyou1999.com^
||snyowx29.com^
||tuigang1999.com^
||victory1999.com^
Here are some examples:
khlgauqt2000.com/svr/wxclick.aspx?huyidata=scol1%3d11180%26scol2%3d10368
snyowx29.com/uploadfiles/20197/201971617_5.gif
thanks!

**Comment by Alex-302** [comment]
Where yahoo ad servers used? I need page URL.

**Comment by nettw** [comment]
> Where yahoo ad servers used? I need page URL.

Original website:
https://tw.mobi.yahoo.com
Found from this code:
https://s.yimg.com/ud/fp/js/ADPositions.007baa97e1144c04df08.min.js

**Comment by Alex-302** [comment]
ok, added ad servers. `adserver.yahoo.com` is blocked by the filters.
