### ISSUE TITLE
www.onlinevideoconverter.com - pop-ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3813]
The site opens extra windows when a download is finished.

SRT:

1. Go here: www.onlinevideoconverter.com
2. Hit Covert a video link/URL 
3. Add a link > Start
4. Press Download
5. See a pop-up

Filters: 1,2,3,4,14. Reproduced on Win 10, Chrome. Ticket: 1469978

**Comment by Alex-302** [comment]
Not reproduced with English filter only.
@seanl-adg could you check it?

**Comment by seanl-adg** [comment]
Not reproduced on my end too.
