### ISSUE TITLE
Fanboy's annoyances block the Evernote web clipper

### ISSUE THREAD

**Issue by ploum** [AdguardTeam/AdguardFilters#3814]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

1. Install the Chrome Evernote web clipper
2. Enable Fanboy's annoyances rules in adguard
3. Evernote web clipper doesn't work anymore.

Incriminated rule : ||evernote.com^$third-party

* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4
Adguard DNS: | None / Default / Family Protection
Stealth mode options(Windows) | 
Adguard filters: | Fanboy's Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Hi
Please open filtering log, press on extension icon and make screenshot.
After that check this rule:
```
@@||evernote.com^$domain=pioclpoplcdbaefihamjohnefbikjilc
```
