### ISSUE TITLE
babycenter.de - Ad leftover - Social widget - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3816]
***Site***: http://www.babycenter.de/a25007210/weihnachtsfest---tipps-f%C3%BCr-eltern
***Description***: Ad leftover and Social widget leftover. And site tries to move the page down a bit to open the cookie notice, but it's already blocked (Annoyance filter rule below fix this issue).

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21358521/4153ee58-c6d9-11e6-9aac-029531cf1c20.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21358584/748497b4-c6d9-11e6-98bf-8071655f4968.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21358598/83030528-c6d9-11e6-8165-83e109b2fc0d.png)

________________________

![image](https://cloud.githubusercontent.com/assets/10995998/21358260/6f2182ce-c6d8-11e6-81fb-14dc30e518c6.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21358296/8c6d0e66-c6d8-11e6-9f9c-2f4a637efa27.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21358360/bd519d9e-c6d8-11e6-8973-00389eaba9f8.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21358464/1422b478-c6d9-11e6-948c-4ed96d476f9b.png)

</details>

_______________________

***Possible rules:*** 

German filter:
```
babycenter.de##div[id^="topAdContainer"]
babycenter.de##div[id^="premiumSponsorBox"]
babycenter.de##div[id^="mobileAd"]
babycenter.de##div[id^="sponsoredAd"]
babycenter.de###footerPremiumAd
```
Annoyances filter:
```
babycenter.de###disclaimerBox
```
Social media filter:
```
babycenter.de##.socialLinksContainer 
```

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.57
Spyware filter | 1.0.9.66
Social media filter | 1.0.15.71
Annoyances filter | 1.0.8.5
German filter | 1.0.29.53
Mobile ads filter | 1.0.6.30
Safari filter | 1.0.1.88

**Comment by Alex-302** [comment]
Added
```
##.socialLinksContainer
babycenter.de##.bcAd
```

**Comment by danidoedel** [comment]
@Alex-302 
Overlay when accessing an article on mobile (http://www.babycenter.de/a25007268/babynamen-trends-2016):

![image](https://cloud.githubusercontent.com/assets/10995998/21982063/d845c37e-dbea-11e6-9fc4-cf6b72d43bb3.png)

Ad leftover at the top on mobile:

![image](https://cloud.githubusercontent.com/assets/10995998/21982124/20f2608c-dbeb-11e6-83a2-082a77e1543f.png)

**Comment by Alex-302** [comment]
```
babycenter.de###topAdContainerMobile
```
