### ISSUE TITLE
linuxundich.de - Ad - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3817]
***Site***: https://linuxundich.de/ and/or https://linuxundich.de/gnu-linux/erfolgreicher-brute-force-angriff-auf-pwdhash/
***Description***: Ads / Ad leftover

<details>
<summary>Screenshot</summary>

Main page:

![image](https://cloud.githubusercontent.com/assets/10995998/21360212/3cc8b67e-c6df-11e6-8126-4cb6faf5b65e.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21360238/53a05c08-c6df-11e6-8824-4d780d1b985e.png)

______________________________
Article page:

![image](https://cloud.githubusercontent.com/assets/10995998/21360253/6e4d86b6-c6df-11e6-9c5a-2d14cb676f0c.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21360275/8657bc4a-c6df-11e6-94b2-97465996a78a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.57
Spyware filter | 1.0.9.66
Social media filter | 1.0.15.71
Annoyances filter | 1.0.8.5
German filter | 1.0.29.53
Mobile ads filter | 1.0.6.30
Safari filter | 1.0.1.88

**Comment by Alex-302** [comment]
added
```
linuxundich.de##.anzbfdcwuie
linuxundich.de##.td-a-rec
linuxundich.de##.td-ss-main-sidebar > .td_block_wrap.td_block_text_with_title.td_block_widget
```
