### ISSUE TITLE
aftvhacks.de - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3820]
***Site***: http://aftvhacks.de/anleitung-kodi-auf-dem-fire-tv-1-2-stick-installieren-ab-firmware-5-0-5-1/
***Description***: Ad leftover / Social widgets

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21360961/5b7d6b5c-c6e2-11e6-9ec8-2477706d4129.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21360994/7b7bb508-c6e2-11e6-9e99-1ae96f11ff1e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.57
Spyware filter | 1.0.9.66
Social media filter | 1.0.15.71
Annoyances filter | 1.0.8.5
German filter | 1.0.29.53
Mobile ads filter | 1.0.6.30
Safari filter | 1.0.1.88

**Comment by Alex-302** [comment]
To German:
```
aftvhacks.de##div[id^="advads_ad_widget"]
```
