### ISSUE TITLE
theatlantic.com - iOS or Safari ad blocking detection

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3821]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
Website detects ad blocking when you use Safari extension.

Open https://www.theatlantic.com/technology/archive/2016/12/america-already-had-a-muslim-registry/511214/

You'll quickly get redirected to:
https://www.theatlantic.com/please-support-us/?next=https%3A%2F%2Fwww.theatlantic.com%2Ftechnology%2Farchive%2F2016%2F12%2Famerica-already-had-a-muslim-registry%2F511214%2F#seen

**Comment by ameshkov** [comment]
Huh, $generichide still does not work as it should

**Comment by ameshkov** [comment]
It does.

The issue is that this rule is missing in the optimized filter.
Temporary solution: add `theatlantic.com` rules from english filter to safari filter.

**Comment by Alex-302** [comment]
Done.
