### ISSUE TITLE
eatsmarter.de - Ad - Ad leftover - Annoyance - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3823]
***Site***: http://eatsmarter.de/ and http://eatsmarter.de/rezepte/rezeptsammlungen/einfache-weihnachtsrezepte#/0
***Description***: Newsletter popup, Ad, Ad leftover, Social widget (desktop/mobile)

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21369473/6212fdfe-c707-11e6-9bd6-a241a88c4eda.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21369514/9db4a592-c707-11e6-9c45-f70855de03c8.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21369530/abbb1d2e-c707-11e6-85ec-3b72596999cd.png)

____________________________

![image](https://cloud.githubusercontent.com/assets/10995998/21369554/ca2e9a10-c707-11e6-823d-bde5651538e5.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21369604/fc90ee2c-c707-11e6-879b-c8ccfd09b1d7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.58
Spyware filter | 1.0.9.67
Social media filter | 1.0.15.75
Annoyances filter | 1.0.8.8
German filter | 1.0.29.53
Mobile ads filter | 1.0.6.30
Safari filter | 1.0.1.88

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
eatsmarter.de##.newsletter-overlay
```
to German
```
eatsmarter.de##.adsense
```
so social
```
eatsmarter.de##.pane-fb-profile-widget
```
