### ISSUE TITLE
m.apotheken-umschau.de - Social widget - iOS

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3824]
***Site***: http://m.apotheken-umschau.de/Ernaehrung/Wie-gesund-Granataepfel-wirklich-sind-102237.html
***Description***: Strange grey overlay on iOS (first picture). If you open the mobile site on a desktop computer you will see that overlay very short and it disappears. 
Social widgets (rules below).

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21370159/bd07eb72-c70a-11e6-8b22-b5e7dda5e0ba.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21369987/e92ad170-c709-11e6-9bf2-06e0b99495d7.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21369866/4c393370-c709-11e6-8c4b-e831cfda74bc.png)

</details>

_____________________

***Possible rules:***
Social media filter:
```
apotheken-umschau.de##.socialshareprivacy
apotheken-umschau.de##.socialMediaButtonBar
```

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.58
Spyware filter | 1.0.9.67
Social media filter | 1.0.15.75
Annoyances filter | 1.0.8.8
German filter | 1.0.29.53
Mobile ads filter | 1.0.6.30
Safari filter | 1.0.1.88

**Comment by Alex-302** [comment]
Fixed.

**Comment by Alex-302** [comment]
Overlay is not reproduced.

**Comment by danidoedel** [comment]
@Alex-302 The social media buttons on mobile are still there. Looks like the rules weren't added to the filter.

**Comment by Alex-302** [comment]
I see only like on the bottom screenshot.
Added
```
apotheken-umschau.de##.socialMediaButtonBar
```
