### ISSUE TITLE
KTVL News app for iOS

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#38243]
***Description***:

**App link**: https://apps.apple.com/us/app/ktvl-news-10/id548807608

* **Current behaviour**: 
<details><summary>Screenshot:</summary>

![fullsizeoutput_16c](https://user-images.githubusercontent.com/33634917/62723263-ea09c100-ba18-11e9-8513-f94b820f3aa1.jpg)
![fullsizeoutput_16d](https://user-images.githubusercontent.com/33634917/62723264-ea09c100-ba18-11e9-8b6d-2aecffb412ad.jpg)

</details><br/>

* **Expected behaviour**: 

Ads should be blocked.

***Steps to reproduce the problem***:

Installing & launching the app should be enough.

***System configuration***
**Platform:** AdGuard Pro 2.1.2.173, unspecified iPhone @ iOS 12.4

**Filters:** Base, Mobile Ads

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | iOS
Operating system version (Android/iOS) | 12.4
Browser:                               | n/a
AdGuard version:                       | 2.1.2.174
Filters enabled:                       | Base, Mobile Ads
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | Default
Helpdesk ID (if exists):               | 1542582

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@akmLaVx this is Facebook ads. Can be blocked by `||graph.facebook.com^`, but Facebook will be broken.
