### ISSUE TITLE
vidavida.de - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3825]
***Site***: http://www.vidavida.de/weihnachtszeit_gesund_naschen_erlaubt/
***Description***: Social widget leftover (rule below).

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21370472/2874e954-c70c-11e6-9a35-cba6758a405c.png)

</details>

________________________

***Possible rules:***
Social media filter:
```
vidavida.de##.social-share-wrapper
```

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.58
Spyware filter | 1.0.9.67
Social media filter | 1.0.15.75
Annoyances filter | 1.0.8.8
German filter | 1.0.29.53
Mobile ads filter | 1.0.6.30
Safari filter | 1.0.1.88

**Comment by Alex-302** [comment]
added
```
##.social-share-wrapper
```
