### ISSUE TITLE
box.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#38267]
`https://m.box.com/shared_item/https%3A%2F%2Fapp.box.com%2Fs%2Fx8nir3eyzx4qyk00xwun9zc4n6der1ky`

Mobile app banner.

Adguard Base + Annoyances + Mobile + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox for Android

**Comment by krystian3w** [comment]
`###mod-mobile-app-banner-1.module.android-app-banner.mobile-app-banner`
