### ISSUE TITLE
pasta-selber-machen.de - Ad - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3827]
***Site***: http://www.pasta-selber-machen.de/pasta/alles-dreht-sich-um-pasta-selber-machen/
***Description***: Ad. Social widgets.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21370615/cb4ed964-c70c-11e6-9185-acc18fd0ece7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.58
Spyware filter | 1.0.9.67
Social media filter | 1.0.15.75
Annoyances filter | 1.0.8.8
German filter | 1.0.29.53
Mobile ads filter | 1.0.6.30
Safari filter | 1.0.1.88

**Comment by Alex-302** [comment]
added
```
##.shariff-button
pasta-selber-machen.de##.aawp-widget
```
