### ISSUE TITLE
abnehmen.com - Ad - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3828]
***Site***: http://www.abnehmen.com/ and http://www.abnehmen.com/threads/300071-portionsgroessen-einschaetzen
***Description***: Ad, Ad leftover and ad post in forums.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21390562/ce811ffe-c787-11e6-9ff6-d5026732754f.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21390580/ea0114c8-c787-11e6-96f4-1223355378be.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21390606/08094896-c788-11e6-8dd3-b81d35ce94ce.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.62
Spyware filter | 1.0.9.69
Social media filter | 1.0.15.76
Annoyances filter | 1.0.8.9
German filter | 1.0.29.54
Mobile ads filter | 1.0.6.30
Safari filter | 1.0.1.88

**Comment by Alex-302** [comment]
Added to German filter
```
abnehmen.com##div[id^="crt-"]
abnehmen.com##.ad_marker
abnehmen.com##.yui-sidebar div.ffwidget_sidebar[-ext-has=">div.ffwidget_sidebar_title:contains(Angebote & Sponsoren)"]
abnehmen.com###sidebar div[class="block smaller"][-ext-has="span.blocktitle:contains(Angebote & Sponsoren)"]
abnehmen.com###posts > li.postbitlegacy.postcontainer.old:not([id^="post_"])

```
