### ISSUE TITLE
kochen-mit-liebe.de - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3829]
***Site***: http://www.kochen-mit-liebe.de/
***Description***: Social widgets.
<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21390724/9e8b68c6-c788-11e6-92fe-6bf63e25277a.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21390737/ac18e95a-c788-11e6-8288-1aee29243d17.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21391039/141f4b92-c78a-11e6-9a51-d3f1f7fb55ae.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.62
Spyware filter | 1.0.9.69
Social media filter | 1.0.15.76
Annoyances filter | 1.0.8.9
German filter | 1.0.29.54
Mobile ads filter | 1.0.6.30
Safari filter | 1.0.1.88

**Comment by Alex-302** [comment]
added
```
||e-mailit.com/widget/$third-party
##.widget_FacebookLikeBox
```
