### ISSUE TITLE
abendzeitung-muenchen.de - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3830]
***Site***: http://www.abendzeitung-muenchen.de/
***Description***: Ad leftover on mobile and social widget (rules below).

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21391845/a14d042a-c78d-11e6-9e4c-f0117a770c92.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21392028/5a633e84-c78e-11e6-962f-11c335f041bb.png)

</details>

_____________________

***Possible rules:***
German filter:
```
abendzeitung-muenchen.de##.ad
```
Social filter:
```
abendzeitung-muenchen.de###article-social-bar
```

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.62
Spyware filter | 1.0.9.69
Social media filter | 1.0.15.76
Annoyances filter | 1.0.8.9
German filter | 1.0.29.54
Mobile ads filter | 1.0.6.30
Safari filter | 1.0.1.88

**Comment by Alex-302** [comment]
added
