### ISSUE TITLE
augsburger-allgemeine.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3832]
***Site***: http://m.augsburger-allgemeine.de/
***Description***: Cookie notice on mobile devices.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21395996/ebdb40ea-c79e-11e6-8fb3-932a66ef8879.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.62
Spyware filter | 1.0.9.70
Social media filter | 1.0.15.77
Annoyances filter | 1.0.8.10
German filter | 1.0.29.54
Mobile ads filter | 1.0.6.32
Safari filter | 1.0.1.89

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
m.augsburger-allgemeine.de##.aa-cookie-alert
```
