### ISSUE TITLE
taboola.com - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3835]
***Site***: https://www.taboola.com/
***Description***: Site doesn't load (white page)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.64
Spyware filter | 1.0.9.70
Social media filter | 1.0.15.79
Annoyances filter | 1.0.8.11
German filter | 1.0.29.54
Mobile ads filter | 1.0.6.32
Safari filter | 1.0.1.89

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||app-*.marketo.com/js/forms2/js/forms*.min.js$domain=taboola.com
```
