### ISSUE TITLE
https://m.lenta.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3836]
https://m.lenta.ru/comments/articles/2016/12/21/privatenacional/

![image](https://cloud.githubusercontent.com/assets/15856304/21399294/b3e53730-c7b3-11e6-8bb3-dd860259686b.png)

<details>

{
  "advancedPreferences" : {
    "pref.vpn.ipv4.bypass" : false,
    "pref.har.capture" : false,
    "pref.vpn.ipv4.force.default" : false,
    "pref.proxy.block.ipv6" : false,
    "pref.splash.enabled" : true,
    "pref.vpn.ipv6.disable" : false,
    "pref.root.clear.youtube" : false,
    "pref.boot.startup.delay" : 10,
    "pref.vpn.ipv4.force.complex" : false,
    "pref.vpn.disable.pause" : false,
    "pref.vpn.ipv6.force" : false,
    "pref.enforce.paused.notification" : false,
    "pref.vpn.tun.mtu" : 9000,
    "pref.vpn.capture" : false,
    "pref.vpn.ipv6.bypass" : false
  },
  "androidVersion" : "5.0.1 (sdk=21)",
  "appLanguage" : "ru",
  "applicationId" : "f3c6b7a008f67bd3",
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "LGE LG-D838",
  "enabledFilterIds" : [ 2, 3, 4, 14, 1, 11 ],
  "environment" : "release",
  "filteringQuality" : "FULL",
  "iconType" : "DEFAULT",
  "installedPackages" : [ "org.telegram.messenger;version=3.15.0;system=false", "com.lge.divx.permission;version=5.0.1-D83820d.1427087767;system=true", "ru.payqr.android;version=3.0;system=false", "com.lge.qremote;version=4.40.12;system=true", "com.lge.mtalk.sf;version=5.3.1;system=true", "com.ubanksu;version=3.0.0;system=false", "com.android.gallery3d;version=4.40.24;system=true", "com.lge.gnsslogcat;version=1.0;system=true", "com.lge.wfds.service.v2;version=2.0.7;system=true", "com.android.packageinstaller;version=5.0.1-D83820d.1427087767;system=true", "com.android.providers.userdictionary;version=5.0.1-D83820d.1427087767;system=true", "ru.ftc.faktura.binbank;version=3.6.1;system=false", "com.google.android.apps.cloudprint;version=1.36b;system=true", "com.google.android.apps.pdfviewer;version=2.2.841.27.30;system=false", "com.penzasoft.textreader;version=3.3;system=false", "com.google.android.googlequicksearchbox;version=6.8.23.21.arm;system=true", "ru.mos.parking.mobile;version=3.1.20;system=false", "com.lge.shutdownmonitor;version=5.0.1-D83820d.1427087767;system=true", "com.lge.smartcard.apdu.uicc;version=1.2;system=true", "com.android.providers.partnerbookmarks;version=5.0.1-D83820d.1427087767;system=true", "kr.kkh.image_search2;version=3.3;system=false", "com.lge.doyouknow;version=4.40.05;system=true", "com.lge.bnr;version=5.38.16;system=true", "ru.yandex.yandexnavi;version=2.17;system=false", "com.qualcomm.wfd.service;version=2.0;system=true", "com.android.managedprovisioning;version=5.0.1-D83820d.1427087767;system=true", "com.google.android.play.games;version=3.9.08 (3448271-038);system=true", "com.lge.filemanager;version=4.40.12;system=true", "com.google.android.feedback;version=5.0.1-1602158;system=true", "com.lge.email;version=6.41.19;system=true", "com.android.wallpaper.livepicker;version=4.40.5;system=true", "com.google.android.onetimeinitializer;version=5.0.1-1602158;system=true", "com.hy.system.fontserver;version=v4.20.2;system=true", "com.android.inputdevices;version=5.0.1-D83820d.1427087767;system=true", "com.android.bluetooth;version=5.0.1-D83820d.1427087767;system=true", "com.qualcomm.qcrilmsgtunnel;version=5.0.1-D83820d.1427087767;system=true", "com.lge.splitwindow;version=20141215bL;system=true", "com.lge.pcsyncui;version=4.40.1;system=true", "com.android.printspooler;version=1;system=true", "com.lge.defaultaccount;version=3.0.0;system=true", "com.google.android.apps.maps;version=9.42.3;system=true", "ru.megafon.mlk;version=2.3.0;system=false", "com.android.contacts;version=4.40.22;system=true", "com.android.vpndialogs;version=5.0.1-D83820d.1427087767;system=true", "com.lge.sizechangable.musicwidget.widget;version=4.40.5;system=true", "com.android.server.telecom;version=null;system=true", "com.webmoney.my;version=2.7.2, build 3f42c13;system=false", "com.google.android.tag;version=1.1;system=true", "eu.dedb.nfc.moscow;version=3.3.2;system=false", "com.lge.ime;version=5.1.13;system=true", "ru.bytemax.vezdehod;version=2.5;system=false", "com.android.defcontainer;version=5.0.1-D83820d.1427087767;system=true", "com.lge.cloudhub;version=2.3.0;system=true", "com.lge.gnss.airtest;version=5.0.1-D83820d.1427087767;system=true", "com.adguard.android;version=2.8.76;system=false", "com.google.android.gm;version=5.0.1 (1642443);system=true", "com.android.systemui;version=4.50.141229;system=true", "com.lge.privacylock;version=4.40.14;system=true", "com.its.rto;version=3.15.2;system=false", "com.android.nfc;version=5.0.1-D83820d.1427087767;system=true", "com.lge.systemservice;version=5.0.1-D83820d.1427087767;system=true", "com.lge.gnsspostest;version=2.0;system=true", "com.android.providers.calendar;version=4.2.8;system=true", "com.android.vending;version=7.2.13.J-all [0] [PR] 138561921;system=true", "com.lge.qvoiceplus;version=4.45.6;system=true", "com.lge.eula;version=4.40.62;system=true", "com.android.mms;version=4.40.31;system=true", "com.android.providers.downloads;version=5.15.61005;system=true", "com.google.android.gsf;version=5.0.1-1602158;system=true", "com.lge.wernicke.nlp;version=5.2.5;system=true", "com.idamob.tinkoff.android;version=3.2.6;system=false", "com.lge.eulaprovider;version=4.40.70;system=true", "ru.mos.polls;version=2.1.1;system=false", "com.lge.smartshare;version=3.5.1;system=true", "ru.stepup.MDMmobileBank;version=3.7.0;system=false", "com.google.android.youtube;version=11.47.57;system=true", "ru.kykyryza;version=2.8.2;system=false", "ru.yandex.rasp;version=2.31;system=false", "com.android.htmlviewer;version=5.0.1-D83820d.1427087767;system=true", "com.lge.lginstallservies;version=4.40.20;system=true", "com.android.location.fused;version=5.0.1-D83820d.1427087767;system=true", "com.lge.ime.dictionary.xt9;version=9.9.4;system=true", "com.shazam.android;version=7.4.0-161214;system=false", "com.rarlab.rar;version=5.50.build42;system=false", "com.uei.lg.quicksetsdk.maxq616;version=2.1.91;system=true", "com.android.LGSetupWizard;version=4.40.0;system=true", "com.android.providers.contacts;version=4.40.22.6;system=true", "com.ghisler.android.TotalCommander;version=2.72;system=false", "com.edadeal.android;version=3.6.9;system=false", "ru.bm.mbm;version=3.0;system=false", "com.zholdak.safeboxpro;version=1.49.5;system=false", "com.qualcomm.qti.services.secureui;version=1.0;system=true", "com.lge.lteconfig;version=1.41223;system=true", "com.signzzang.sremoconlite;version=2.39;system=false", "com.lge.keepscreenon;version=4.40.1;system=true", "com.google.android.setupwizard;version=2.0;system=true", "com.lastpass.lpandroid;version=4.1.742;system=false", "com.android.incallui;version=4.40.15;system=true", "com.lge.gestureanswering;version=2.0.0;system=true", "com.rsupport.rsperm;version=3.0.1.13 (Build 313);system=true", "com.lge.lgdmsclient;version=2.3.3.1;system=true", "ru.sberbankmobile;version=7.3.0;system=false", "com.lge.videotool;version=4.40.8;system=true", "com.android.captiveportallogin;version=5.0.1-D83820d.1427087767;system=true", "com.google.android.gms;version=10.0.84 (238-137749526);system=true", "ru.yandex.yandexbus;version=3.81;system=false", "com.google.android.configupdater;version=5.0.1-1602158;system=true", "org.codeaurora.btmultisim;version=1.0;system=true", "com.rsupport.rs.activity.lge;version=4.1.10 (Build 481);system=true", "com.lge.settings.easy;version=4.40.0;system=true", "free.zaycev.net;version=4.3.6;system=false", "com.lge.onehandcontroller;version=1.0;system=true", "com.android.pacprocessor;version=5.0.1-D83820d.1427087767;system=true", "com.lge.wernicke;version=2.01.2;system=true", "com.lge.drmservice;version=5.0.1-D83820d.1427087767;system=true", "com.android.vending.billing.InAppBillingService.LOCK;version=6.2.6;system=false", "com.lge.android.atservice;version=5.0.1-D83820d.1427087767;system=true", "com.lge.provider.systemui;version=5.0.1-D83820d.1427087767;system=true", "com.google.android.apps.books;version=3.8.41;system=true", "ru.yandex.metro;version=2.5.1;system=false", "com.android.facelock;version=5.0.1-1602158;system=true", "com.lge.videoplayer;version=4.40.16;system=true", "com.avito.android;version=8.0;system=false", "com.android.stk;version=1.1;system=true", "com.google.android.gsf.login;version=5.0.1-1602158;system=true", "com.surpax.ledflashlight.panel;version=1.1.4;system=false", "com.lge.clock;version=4.41.16;system=true", "org.kman.AquaMail;version=1.7.0-80;system=false", "com.lge.lgfota.permission;version=5.0.1-D83820d.1427087767;system=true", "com.android.calendar;version=4.40.17;system=true", "com.ivolk.StrelkaGPS;version=5.41;system=false", "ru.mw;version=3.2.0;system=false", "com.lge.smartshare.dlna;version=3.5.0;system=true", "com.android.backupconfirm;version=5.0.1-D83820d.1427087767;system=true", "com.lge;version=3.0.0;system=true", "com.alensw.PicFolder;version=4.6.9.1486;system=false", "com.android.settingsaccessibility;version=4.40.27;system=true", "com.android.externalstorage;version=5.0.1-D83820d.1427087767;system=true", "com.android.providers.downloads.ui;version=5.15.41112;system=true", "com.lge.servicemenu;version=1.0;system=true", "com.lge.networksettings;version=4.8.50;system=true", "com.prodoomman.sberbankunroot;version=1.1;system=false", "com.news.rssfeedreader;version=1.2.8;system=false", "com.android.calculator2;version=4.40.11;system=false", "com.android.shell;version=5.0.1-D83820d.1427087767;system=true", "ru.rocketbank.r2d2;version=3.3.3;system=false", "com.mobeam.beepngo;version=4.2.2;system=false", "com.android.chrome;version=55.0.2883.91;system=true", "com.android.proxyhandler;version=5.0.1-D83820d.1427087767;system=true", "com.lge.voicerecorder;version=4.40.10;system=true", "com.google.android.marvin.talkback;version=4.5.1;system=true", "com.lge.sizechangable.favoritecontacts;version=4.40.3;system=true", "com.lge.wv.hidden;version=5.0.1-D83820d.1427087767;system=true", "org.kman.AquaMail.UnlockerMarket;version=1.0.21-77;system=false", "PSB.Droid;version=2.9.17;system=false", "com.android.keychain;version=5.0.1-D83820d.1427087767;system=true", "com.qualcomm.timeservice;version=5.0.1-D83820d.1427087767;system=true", "com.akbars.bankok;version=3.4;system=false", "com.lge.camera;version=4.8.10;system=true", "com.lge.qmemoplus;version=4.40.14;system=true", "com.lge.sizechangable.weather.platform;version=4.40.8;system=true", "com.lge.appbox.client;version=4.40.104;system=true", "ru.e_num;version=E-NUM v. 3.5.4 build 3429a8d 24.10.2016;system=false", "com.lge.appwidget.lgsearch;version=4.0.6;system=true", "com.megafon.bank;version=1.0.1188;system=false", "com.keramidas.TitaniumBackupPro;version=1.3.0;system=false", "com.google.android.street;version=2.0.0.140637942;system=true", "ru.ftc.faktura.europlan;version=2.8.1;system=false", "com.lge.lgworld;version=1.0.1;system=false", "com.lge.wapservice;version=5.0.21200;system=true", "com.infraware.polarisviewer;version=5.6.4004.00-FT02;system=true", "com.lge.sui.widget;version=5.2.11;system=true", "com.lge.music;version=4.40.16;system=true", "com.lge.sizechangable.weather;version=4.40.8;system=true", "com.android.phone;version=4.40.15;system=true", "com.dukei.android.apps.anybalance;version=3.9.804;system=false", "com.lge.lgdrm.permission;version=5.0.1-D83820d.1427087767;system=true", "com.google.android.apps.plus;version=4.8.0.81189390;system=true", "com.android.certinstaller;version=5.0.1-D83820d.1427087767;system=true", "android;version=5.0.1-D83820d.1427087767;system=true", "com.lge.ime.theme.black;version=3.0.13;system=true", "ru.bm.transport;version=2.1.12;system=false", "com.android.providers.telephony;version=4.1.01;system=true", "com.google.android.webview;version=55.0.2883.91;system=true", "com.box.android;version=1.0;system=false", "com.twitter.android;version=6.17.0;system=false", "ru.mediametrics;version=1.02;system=false", "com.lge.sizechangable.weather.theme.optimus;version=4.40.8;system=false", "ru.yandex.disk;version=3.02;system=false", "com.lge.smartsharepush;version=4.40.22;system=true", "com.android.cellbroadcastreceiver;version=4.40.5;system=true", "com.mazda.mymazdaapp;version=1.3;system=false", "com.lge.touchcontrol;version=1.0;system=true", "com.lge.wfds.service.v3;version=3.0.4;system=true", "eu.chainfire.supersu;version=2.79;system=true", "com.lge.lockscreensettings;version=4.6.62;system=true", "com.google.android.talk;version=2.5.83281670;system=true", "com.lge.Notebook;version=4.40.6;system=false", "com.lge.launcher2.theme.bunnyfairy;version=4.3.131029;system=true", "com.lge.hiddenmenu;version=5.0.1-D83820d.1427087767;system=true", "com.zholdak.safeboxsyncer;version=1.09.1;system=false", "com.android.documentsui;version=5.0.1-D83820d.1427087767;system=true", "com.android.settings;version=4.40.0;system=true", "com.android.sharedstoragebackup;version=5.0.1-D83820d.1427087767;system=true", "com.lge.livewallpaper.multiphoto;version=4.40.5;system=true", "org.simalliance.openmobileapi.service;version=3.2.1;system=true", "com.android.wallpapercropper;version=5.0.1-D83820d.1427087767;system=true", "com.lge.mrg.boardcontent;version=4.21.2;system=true", "com.qualcomm.location;version=1.0;system=true", "com.lge.smartshare.provider;version=1.0.16;system=true", "com.lge.updatecenter;version=4.40.104;system=true", "com.lge.app.floating.res;version=2015-01-13;system=true", "ru.ozon.app.android;version=2.5.1;system=false", "com.whatsapp;version=2.16.392;system=false", "com.lge.smartcover;version=4.21.31;system=true", "ru.yandex.partners;version=1.00;system=false", "info.mapcam.droid;version=2.7.420;system=false", "com.google.android.videos;version=3.6.14;system=true", "com.google.android.syncadapters.contacts;version=5.0.1-1602158;system=true", "com.lge.mlt;version=2.5.7;system=true", "com.android.providers.settings;version=4.0.00;system=true", "com.google.android.syncadapters.calendar;version=5.0.1-1602158;system=true", "com.mxtech.videoplayer.ad;version=1.8.10;system=false", "com.lge.widget.quickcovercontacts;version=4.40.3;system=true", "com.google.android.backuptransport;version=5.0.1-1602158;system=true", "ru.yandex.yandexmaps;version=5.3.1;system=false", "com.lge.launcher2;version=4.40.23;system=true", "com.lge.permissions;version=3.0.0;system=true", "com.lge.lmk;version=4.41.1;system=false", "com.alibaba.aliexpresshd;version=5.1.0;system=false", "com.lge.task;version=4.40.2;system=false", "com.lge.appwidget.clock;version=4.40.2;system=true", "com.lge.homeselector;version=4.40.04;system=true", "com.quicinc.cne.CNEService;version=5.0-eng.lnxbuild.20141211.051420;system=true", "com.qualcomm.atfwd;version=5.0.1-D83820d.1427087767;system=true", "com.lge.launcher2.theme.optimus;version=4.0.552;system=true", "com.google.android.apps.docs;version=2.4.351.24.35;system=true", "com.lge.sync;version=4.40.6;system=true", "com.belous.v.yapikplus;version=1.1.8;system=false", "codes.simen.l50notifications;version=1.12;system=false", "com.android.mms.service;version=5.0.1-D83820d.1427087767;system=true", "com.lge.app.richnote;version=4.40.1;system=true", "com.google.android.tts;version=3.10.10;system=true", "com.lge.gnsstest;version=5.0.1-D83820d.1427087767;system=true", "com.android.providers.media;version=5.0.1-D83820d.1427087767;system=true", "com.lge.easyhome;version=4.21.5;system=true", "com.android.browser;version=5.2.34C26;system=true", "com.google.android.partnersetup;version=5.0.1-1602158;system=true", "com.lge.formmanager;version=4.20.15;system=true" ],
  "installerPackage" : null,
  "kernelVersion" : "3.4.0-perf-g5637f0e",
  "referrer" : null,
  "sourceApk" : "/data/app/com.adguard.android-1/base.apk",
  "sslMitmConfiguration" : "{\"certificateInstalledToSystemStorage\":null,\"mitmList\":\"1024 domains\",\"mitmListMode\":\"WHITELIST\"}",
  "statisticsInfo" : "Blocked threats:16; Blocked banners:1092124; Traffic saved:31071223808;",
  "updateChannel" : "BETA",
  "upstreamProxySettings" : null,
  "userfilter" : [ ],
  "versionName" : "2.8.76",
  "whitelist" : [ ],
  "autoStartEnabled" : true,
  "browsingSecurityEnabled" : true,
  "deviceSpeedRank" : 92,
  "dnsFilteringEnabled" : false,
  "filtersAutoUpdateEnabled" : true,
  "premium" : true,
  "proxyMode" : false,
  "proxyPort" : 8080,
  "proxySetupManualMode" : false,
  "sendAnonymousStatistics" : true,
  "showUsefulAds" : false,
  "trial" : false
}

**Comment by Alex-302** [comment]
Там только логотип липтона рекламный.
Добавил в русский фильтр
```
lenta.ru##.b-goodnews-lipton-link
```
