### ISSUE TITLE
https://hh.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3837]
https://hh.ru/vacancy/19028415

![file_000](https://cloud.githubusercontent.com/assets/15856304/21399776/b1d2c762-c7b5-11e6-9971-708e26191f98.png)

<details>

Application version: 1.1.1.54
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 86A8280B-7ABB-41CC-B9E9-C9E6E5F42BE4

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.45 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.61 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.60 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.96 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.96 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.43 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.27 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.87 Enabled=YES

**Comment by evgeniy-ADG** [comment]
повтоярется, все, что справа, включая картинку - что-то похожее на sponsored content

**Comment by Alex-302** [comment]
C оптимизированными проверь. У меня чисто.

**Comment by evgeniy-ADG** [comment]
Simplified filters имеешь в виду? Сегодня и без этого чисто, странно.

**Comment by Alex-302** [comment]
да, они.
Пока прикрою.

**Comment by evgeniy-ADG** [comment]
Тут снова пришел репорт на сайт, https://novosibirsk.hh.ru/
Пользователь использует контент-блокер из гугл плей. У меня пробелмы с его фильтрами нет.

![screenshot_2017-01-07-12-04-03](https://cloud.githubusercontent.com/assets/15856304/21748990/76d4aece-d59c-11e6-8c57-1f01fb618570.png)

Фильтры: англ, счетчиков, соцсетей, раздражителей, русский, мобильный. Яндекс браузер.

Тикет: 1050245

**Comment by Alex-302** [comment]
Яндекс Браузер свои исключения вставляет в контент блокер. Так что с якдексовой рекламой в их браузере придётся смириться.
