### ISSUE TITLE
AlloCiné : Cinéma et Séries iOS app - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3838]
Can't open app with adguard on. Stuck on loading. Turned on DNS logging to track why for you, assume it's attached now.

The screenshot won't help you, it's just their yellow splash screen that keeps the loading state until I turn off Adguard.

Logs: 1311900

**Comment by Alex-302** [comment]
I need a time of starting the app.

**Comment by Arnoud-B** [comment]
@Alex-302 What do you mean? The date/timestamp of when it happened?

By the way, the issue cannot be reproduced after loading the app with Adguard turned off, then turning Adguard back on. The app seems to set a flag "ad seen" until the next ad needs to be shown to users.

**Comment by Alex-302** [comment]
@Arnoud-B 

> The date/timestamp of when it happened?

yes, date/timestamp.

Installed this app for the first timeб the issue was not reproduced.
