### ISSUE TITLE
n24.de - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3839]
***Site***: http://m.n24.de/n24/Sport/Fussball/1-bundesliga/d/9600036/warum-mats-hummels-jetzt-blondie-ist.html
***Description***: Social widget at the bottom of mobile site.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21409986/e8f54cf6-c7dd-11e6-8fea-4c656288ef8a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.66
Spyware filter | 1.0.9.71
Social media filter | 1.0.15.82
Annoyances filter | 1.0.8.15
German filter | 1.0.29.54
Mobile ads filter | 1.0.6.32
Safari filter | 1.0.1.89

**Comment by Alex-302** [comment]
It redirects me to welt.de Can't reproduce on this domain.
Could you open this site on the phone, and connect it to USB and open `chrome://inspect/#devices` ?

**Comment by danidoedel** [comment]
Isn't there anymore.
