### ISSUE TITLE
hi-tech.mail.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3840]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Блокируются элементы медиа от twitter,
https://hi-tech.mail.ru/news/airpods-tonnels/

**Помогает отключение Русского фильтра**

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21421794/687f131c-c83d-11e6-9696-cec0d039f367.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21421813/7ade7fd4-c83d-11e6-9bc6-ac83809acdf8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Хром
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Adguard DNS: | None 
Stealth mode options(Windows) | none
Adguard filters: | 1,2,3,4,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1472061

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.

**Comment by vgavrish** [comment]
https://hi-tech.mail.ru/news/
Блокируется колонка Новостей
Как должно быть: http://prntscr.com/dvh0ub
Как есть: http://prntscr.com/dvh10w
Помогает отключение Фильтра раздражителей
Браузер Хром

**Comment by Alex-302** [comment]
поправил
