### ISSUE TITLE
chan.sankakucomplex.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3841]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Открывается другая страница при нажатии к примеру в эту область:
http://prntscr.com/dmjopj

https://chan.sankakucomplex.com/?tags=jojo%27s_bizarre_adventure+official_art&commit=Search

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Хром
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Adguard filters: | 1,2,3,4,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1040294

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
