### ISSUE TITLE
xu.su - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#3842]
https://xu.su/
adg 1.4.0
chrome opera yandex browser
en rus spyware socialmedia annoyances 
<details>

![2016-12-22 15 14 57](https://cloud.githubusercontent.com/assets/23637588/21425314/7697d9ae-c859-11e6-8a36-df88e9adcc0d.png)

</details>

**Comment by Alex-302** [comment]
fixed
