### ISSUE TITLE
nationalpost.com - Ad

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#3843]
missed Ad

**Filters** 1, 2, 3, 4, 5, 14

**OS** Mac, Windows

Chrome, Safari

**Screenshot**
http://prnt.sc/dml3s7

**Comment by Alex-302** [comment]
Added to English filter
```
nationalpost.com##a[rel="external nofollow"] > img[src^="/images/offers/"]
```
