### ISSUE TITLE
https://www.sports.ru/

### ISSUE THREAD

**Issue by dtitbd** [AdguardTeam/AdguardFilters#3846]
Лига болельщиков вверху, раз. Оранжевые кнопочки, ведущие на winline, рядом с каждым матчем, два.
<details>

![image](https://cloud.githubusercontent.com/assets/17032471/21435303/f33f8ff6-c89a-11e6-97b3-3b672ec12676.png)
</details>

Три (возможно не глобально): при включенном adguard не сворачивается верхняя панель браузера на планшете. И проблемы с безопасностью https. При выключенном все нормально.

<details>

![image](https://cloud.githubusercontent.com/assets/17032471/21435332/1856c6ba-c89b-11e6-8f40-9105cb161f68.png)
</details>

<details>

![image](https://cloud.githubusercontent.com/assets/17032471/21435342/2620aa0e-c89b-11e6-9097-14226f98ae1a.png)
</details>

Information | value
--- | ---
Operating system: |  Android 
Browser: | Chrome
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard DNS: | None
Adguard filters: | [аналогично этим](https://camo.githubusercontent.com/2e4ffa92acc5f1ab3b96fd490f4974c950be8863/687474703a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f66393931333262656136656334313134626631616238653235303831313563662e706e67)

**Comment by Alex-302** [comment]
Убрал. 
Баннер как на третьем скрине не нашёл.

**Comment by dtitbd** [comment]
На третьем скрине adguard отключен.
Там суть не в рекламе, а в том, что верх браузера не сворачивается при включенном сабже. Проблема появилась не так давно, 1-2 недели назад, точнее не скажу.

**Comment by Alex-302** [comment]
Хм.. У меня она не сворачивается и без Адгарда. Похоже так и задумано.

**Comment by dtitbd** [comment]
Действительно. Точнее, в первые 7-8 секунд она сворачивается, а потом обратно появляется и не скрывается. Дело может быть в самом сайте? И можно ли как-то силами адгуард поправить это или нет?

**Comment by Alex-302** [comment]
Можно только скрыть полностью. Чтоб сворачивалось - нужно им писать.
