### ISSUE TITLE
http://www.iphones.co.il/ - Incorrect blocking 

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3847]
Incorrect blocking on page:
http://www.iphones.co.il/

When I click on any article white page appears

<details>

Application version: 1.1.3.31
Application lifetime: 1970-01-01 00:00:00 +0000
Device: iPhone
Platform: iOS
OS: 10.2
ID: 77F9EB72-B284-432F-9DBA-0424E6A50069
Locale: he
Region: il
Optimazed enabled: YES

Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.67 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.72 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.85 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.17 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.96 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.32 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.89 Enabled=YES
ID=101 Name="EasyList" Version=1.0.65.78 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.71.30 Enabled=YES
ID=108 Name="EasyList Hebrew" Version=1.0.3.72 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.71.44 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES

</details>

Ticket ID: 1468978

**Comment by Alex-302** [comment]
not reproduced
try to disable
```
ID=101 Name="EasyList" Version=1.0.65.78 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.71.30 Enabled=YES
ID=108 Name="EasyList Hebrew" Version=1.0.3.72 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.71.44 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
```
