### ISSUE TITLE
otvet.mail.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#38486]
**1**. При нажатии на кнопку "Показать ещё" внизу страницы, при большом количестве ответов, скрытые ответы не подгружаются. Всему виной следующее правило из Русского фильтра:

`otvet.mail.ru##.container-for-answers > div.answer-separator ~ div:not([data-aid]):not([class*="answer "]):not([class*="answer-"]):not(:empty):not([class*="title"]):not([class*="OTVET"]):not([class*="btns"])`

 Страницы для проверки:

 [https://otvet.mail.ru/question/214310055](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://otvet.mail.ru/question/214310055)
 [https://otvet.mail.ru/question/214311362](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://otvet.mail.ru/question/214311362)
 [https://otvet.mail.ru/question/214372361](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://otvet.mail.ru/question/214372361)

___________________________________________________

 **2**. Реклама в правой колонке отображается, хотя Русский фильтр подключён. Это из-за того, что Вы правило, блокирующее рекламу в правой колонке, добавили в Фильтр раздражителей (при последней правке: [895b4b5](https://github.com/AdguardTeam/AdguardFilters/commit/895b4b54c3bb8a89ed8c66eef3b88af2ace1ffde)), а надо в Русский.

<details><summary>Screenshot:</summary>

![2019 08 13-2](https://user-images.githubusercontent.com/17948007/62904908-d475fd80-bd70-11e9-9010-f5c59220c806.png)
</details>

___________________________________________________

 **3**. Всплывашка-Раздражитель.
 Появляется НЕ каждый раз при заходе на Ответы.Майл.ру и висит секунд ~10, затем пропадает.

<details><summary>Screenshot:</summary>

![2019 05 20-3](https://user-images.githubusercontent.com/17948007/58010029-46cf9c80-7af8-11e9-9bf8-fed94bb63a7d.png)
----------
![2019 08 13-1](https://user-images.githubusercontent.com/17948007/62904931-f1aacc00-bd70-11e9-95c6-d0939909832f.png)
</details>

[https://otvet.mail.ru/question/46812002](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://otvet.mail.ru/question/46812002)

`otvet.mail.ru##.nt--position`

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.2.1
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
1 - удалил
2 - так правило дольше проживёт. Пока так
3 - ну значит не сильно и раздражает)
