### ISSUE TITLE
http://www.sueddeutsche.de/adblock - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3848]
http://www.sueddeutsche.de/adblock - incorrect blocking

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21441692/17c8fb94-c8a2-11e6-8e17-323c1f7f1dd1.png)

</details>

<details>

![image](https://cloud.githubusercontent.com/assets/23258533/21441763/78efff30-c8a2-11e6-888d-e2b7754719f2.png)

</details>

<details>

Application version: 1.1.3.31
Application lifetime: 2016-11-04 17:36:34 +0000

Device: iPad
Platform: iOS
OS: 10.1.1
ID: 995D1D4B-4118-4236-8155-E29BC95A353E

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.69 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.72 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.85 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.20 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=NO
ID=6 Name="German filter" Version=1.0.29.59 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.89 Enabled=YES

</details>

Ticket ID: 1459423

**Comment by Alex-302** [comment]
not reproduced. Try simplified filters.
