### ISSUE TITLE
http://www.focus.de/ - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3849]
http://www.focus.de/ - missed ad

A banner at the top of the page

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/21445361/ac59bbc2-c8c0-11e6-9b1c-1d3756eeb5e1.png)

</details>

<details>

Application version: 1.1.3.31
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: 64E884B6-DA47-4574-96DE-A8C9ED2A0ACC

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.69 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.72 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.19 Enabled=YES
ID=6 Name="German filter" Version=1.0.29.58 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.89 Enabled=YES

</details>

Ticket ID(if exists): 1135463

**Comment by Alex-302** [comment]
Try this rule
```
@@google$domain=focus.de,script
```
