### ISSUE TITLE
рязанскийкирпич.рф

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3850]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
на сайте  http://xn--80aneaaefcxzcih6g1e.xn--p1ai/katalog/gazosilikatnye-bloki/gazosilikatnyy-blok-poritep-stenovoy-d-500-shirina-500-mm/# вкладки "розница" и "опт" не открываются

**Помогает отключение Фильтра виджетов соц сетей**

* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21450345/d18a157a-c8fe-11e6-84dc-68bdd3cbbf5c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Хром
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Adguard DNS: | None
Stealth mode options(Windows) | none
Adguard filters: | 1,2,3,4,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1105330

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
