### ISSUE TITLE
http://kinogo-online.net/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3852]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Блок с предложением установить Амиго + при нажатии открывается другой сай
http://kinogo-online.net/load/list/trillery/film_inkarnacija_2016/48-1-0-481

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21452080/fb779e08-c90c-11e6-9166-104588521f51.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Хром
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Adguard filters: | 1,2,3,4,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
