### ISSUE TITLE
pastebin.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#38541]
`https://pastebin.com/`
`https://pastebin.com/0bbKkySg`

Fixed-position annoyance. There are already other elements on the pages telling people to create an account.

![pastebin](https://user-images.githubusercontent.com/35470489/62956471-64479600-bdc9-11e9-97c0-a025b88b4c4e.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by LucasDiTomase** [comment]
Please try this rule

pastebin.com###float-box-frame
