### ISSUE TITLE
auth.wi-fi.ru - пропущена реклама

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#3855]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://auth.wi-fi.ru/auth - видео реклама

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/21453214/a58494a2-c915-11e6-8c2e-3f8c7dc6b239.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***
Application version: 1.1.3.31
Device: iPhone
Platform: iOS
OS: 10.2
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.66 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.72 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.84 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.19 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.62 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.32 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.89 Enabled=YES
ID=101 Name="EasyList" Version=1.0.65.78 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.71.30 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.65.94 Enabled=NO
ID=115 Name="RU AdList" Version=1.0.71.42 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.71.44 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.68.28 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.67.97 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1260402

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by deLumren** [comment]
Seems like the problem is back in 1.2
User 1517823 started seeing videos yesterday.

**Comment by deLumren** [comment]
Another complaint from 1283234

**Comment by Alex-302** [comment]
Is is impossible on iOS, because auth will be broken.
