### ISSUE TITLE
computerbild.de - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3858]
***Site***: http://www.computerbild.de/artikel/cbs-News-PC-PS4-Xbox-For-Honor-11973591.html
***Description***: Ad leftover. Social widget.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21454893/4f5ac662-c91c-11e6-944b-f6361e0d0840.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21454902/60298eb0-c91c-11e6-8ac0-05a90bd695eb.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21454909/758b023e-c91c-11e6-963f-8fc068eb0065.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.72
Spyware filter | 1.0.9.72
Social media filter | 1.0.15.85
Annoyances filter | 1.0.8.22
German filter | 1.0.29.60
Mobile ads filter | 1.0.6.33
Safari filter | 1.0.1.89

**Comment by Alex-302** [comment]
added
```
##.socialmediabar
computerbild.de##.teaserblock.kaufenteaser
computerbild.de###teaser_right > div.labeling
```
