### ISSUE TITLE
Блокировка

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#38595]
@slavserver commented on [Mon Aug 12 2019](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1460)

ПОСЛЕДНЕЕ ОБНОВЛЕНИЕ версии 2019-08-12 23:28

Здравствуйте, блокирует информационные виджеты курса валют, что крайне не удобно..
пример кода:

<script type="text/javascript" src="https://files.coinmarketcap.com/static/widget/currency.js"></script>
<div class="coinmarketcap-currency-widget" data-currency="expanse" data-base="USD" data-secondary="BTC" data-ticker="true" data-rank="true" data-marketcap="true" data-volume="true" data-stats="USD" data-statsticker="true"></div>

**Comment by Alex-302** [comment]
@slavserver мало информации. Отправьте отчёт из расширения, и всё станет ясно.

**Comment by slavserver** [comment]
URL: https://files.coinmarketcap.com/static/widget/currency.js
Тип: JavaScript
Правило: ||coinmarketcap.com^$third-party
Фильтр: Базовый фильтр AdGuard

**Comment by Alex-302** [comment]
> Отправьте отчёт из расширения, и всё станет ясно
