### ISSUE TITLE
bwin.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3860]
***Site***: https://sports.m.bwin.com/de/sports
***Description***: Annoying overlay on mobile site.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21455159/4a1a39b0-c91e-11e6-9a3b-0aa6e1e9f473.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.73
Spyware filter | 1.0.9.72
Social media filter | 1.0.15.85
Annoyances filter | 1.0.8.22
German filter | 1.0.29.60
Mobile ads filter | 1.0.6.33
Safari filter | 1.0.1.89

**Comment by Alex-302** [comment]
Not reproduced.

**Comment by seanl-adg** [comment]
I couldn't reproduce neither, could you provide some steps to reproduce after clearing caches&cookies?

**Comment by danidoedel** [comment]
Looks like they removed it meanwhile.
