### ISSUE TITLE
extra-radio.de - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3862]
***Site***: http://www.extra-radio.de/
***Description***: Ad leftover at the right. Social widget leftover at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21455442/51838c18-c920-11e6-9d47-ab86d07d4333.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21455446/6b285068-c920-11e6-905b-c44abbd0d886.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.73
Spyware filter | 1.0.9.72
Social media filter | 1.0.15.85
Annoyances filter | 1.0.8.22
German filter | 1.0.29.60
Mobile ads filter | 1.0.6.33
Safari filter | 1.0.1.89

**Comment by Alex-302** [comment]
added
```
extra-radio.de##.bc_right div.box_right:last-child
extra-radio.de##.bc_left div.box_left[-ext-has="div.box_left_headline>h5.swiss:contains(Facebook)"]
```
