### ISSUE TITLE
hypnotube.com [NSFW] [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#38636]
**Site**: https://hypnotube.com/video/black-cock-worship-987.html

**Issue**: Please remove the ads on the video player and on the right & bottom of the page.

**Screenshot**: http://prntscr.com/osxfw0

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 76.0.3809.100 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 3.2.1	 `

**Filters**:
```
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404
NoCoin Filter List

```

**Stealth Mode Settings**:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled (Default)

**Comment by BlazDT** [comment]
Fixed the ads I saw on the site. If possible, please use different file hoster for screenshots (or just upload them to github), that one is not showing pictures for me.
