### ISSUE TITLE
trendlouds.com [Ad Text Strings] [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#38632]
**Site**: http://trendlouds.com/spotifynew

**Issue**: Please remove the Ad-block message and Ad text string on the page. Possible pop-ups (please check).

**Screenshot**: http://prntscr.com/osvq2w

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 76.0.3809.100 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 3.2.1	 `

**Filters**:
```
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404
NoCoin Filter List

```

**Stealth Mode Settings**:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled (Default)

**Comment by Nzzyme** [comment]
I was able to see the Google captcha but still seeing the Ad text string and pop-up when clicking on empty blank space below that...Can you please check this again?

http://prntscr.com/otiy6r

**Comment by AdamWr** [comment]
I can't reproduce it.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/63173097-703c8d80-c03f-11e9-8052-d671e26a8517.png)

</details>

Popup also not reproduced.

@slavaleleka Could you please check it?

**Comment by slavaleleka** [comment]
I don't see ad leftover at my end

**Comment by Nzzyme** [comment]
Yes, neither do I now. However, now I am still seeing the adblock message. Not sure whats going on with this site

http://prntscr.com/ott0il


Cleared browser cache, updated filters and checked again.

**Comment by oleedd** [comment]
@Nzzyme 
This site changes its domain at least each week (sometimes after several days). It is already changed. You need to use this rule and change the domain in the rule after it changes:
`@@||parentingss.xyz^$generichide`

**Comment by Alex-302** [comment]
Fixed

**Comment by oleedd** [comment]
@Alex-302 Why didn't you choose generichide? Just interesting.

**Comment by Alex-302** [comment]
because it is not required here

**Comment by oleedd** [comment]
Thanks Captain!
When is it required?

**Comment by oleedd** [comment]
Thanks Captain! This info is extremely useful.
When is it required?

**Comment by slavaleleka** [comment]
@oleedd 

generic rule — it's a cosmetic rule which is not specified for any particular domain. and there are a lot of generic rules in our filter lists. 

`@@||parentingss.xyz^$generichide` is disabling **all** generic rules. also it can make ad appear which should be handled, but it means + more rules. in this case it was enough to disable just few of gerenic rules to circumvent adblock detection

**Comment by oleedd** [comment]
> also it can make ad appear which should be handled

By this logic, generichide shouldn't be used at all. When is generichide required?

**Comment by slavaleleka** [comment]
for example, generichide + few ad handling rules are better than 5 or more exclusion rules. generally each case is considered from the perspective of potential threat of generichide and number of rules

**Comment by oleedd** [comment]
If to think logically, to block an element with the anti adblock warning - is easy and quick (because need only one rule). But it doesn't work for this site. Why not block (when it helps) instead of unblocking?
