### ISSUE TITLE
http://app.plex.tv/web/app - cannot log in

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3863]
http://app.plex.tv/web/app

Safari, MacOS and iOS.
The prompt does not disappear even if you reload the page. No problems in Chrome browser.

![file_000 1](https://cloud.githubusercontent.com/assets/15856304/21455606/4e030b40-c92a-11e6-8b31-cbbb68d1957b.png)

<details>
"User filter" Version=1.0.0.0
ID=2 Name="English filter" Version=1.1.3.70
ID=3 Name="Spyware filter" Version=1.0.9.72
ID=4 Name="Social media filter" Version=1.0.15.85
ID=14 Name="Annoyances filter" Version=1.0.8.20
ID=207 Name="Adblock Warning Removal List" Version=1.0.71.4

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||metrics.plex.tv/collect/event
```
@evgeniy-ADG check it.

**Comment by evgeniy-ADG** [comment]
I have opened the site in the private tab, logged in, it still shows the "please wait" prompt but reloading the page helps. The rule is added, the DNS is turned off.

**Comment by Alex-302** [comment]
@evgeniy-ADG try without spyware filter

**Comment by Alex-302** [comment]
Just update the filters and check. Should be working.

**Comment by Alex-302** [comment]
@evgeniy-ADG
