### ISSUE TITLE
einsatz-live.de - Ads - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3864]
***Site***: http://einsatz-live.de/
***Description***: Ads. Ad leftover. Social widget leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21455705/c2863e4a-c922-11e6-838b-8b3d5037290f.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21455717/e73066e4-c922-11e6-861c-5ff2978daff0.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21455725/f0fcb0ec-c922-11e6-9b6a-f21d83bc0859.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.3.74
Spyware filter | 1.0.9.73
Social media filter | 1.0.15.86
Annoyances filter | 1.0.8.23
German filter | 1.0.29.60
Mobile ads filter | 1.0.6.33
Safari filter | 1.0.1.90

**Comment by Alex-302** [comment]
Site is not popular, less than 6k visits per month.
For top banners:
```
einsatz-live.de##.main > div.top > div.wrap_inner > section > div#top.wow.zoomIn[style^="visibility: visible;"]
```
