### ISSUE TITLE
Weather and clock app - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3865]
https://play.google.com/store/apps/details?id=com.devexpert.weather&hl=ru

![lscp9vn98hq](https://cloud.githubusercontent.com/assets/15856304/21458324/3f2c007c-c93e-11e6-80c5-49a05eaf9c05.jpg)

<details>

{
  "advancedPreferences" : {
    "pref.vpn.disable.pause" : false,
    "pref.har.capture" : false,
    "pref.vpn.ipv6.force" : false,
    "pref.vpn.ipv4.force.default" : false,
    "pref.enforce.paused.notification" : false,
    "pref.proxy.block.ipv6" : false,
    "pref.splash.enabled" : true,
    "pref.vpn.ipv6.disable" : false,
    "pref.vpn.capture" : false,
    "pref.vpn.ipv4.force.complex" : false,
    "pref.vpn.ipv6.bypass" : false
  },
  "androidVersion" : "6.0.1 (sdk=23)",
  "appLanguage" : "ru",
  "applicationId" : "ce31325d0456df68",
  "autoStartEnabled" : true,
  "browsingSecurityEnabled" : true,
  "currentWifiProxyConfiguration" : "port=0 manual",
  "deviceName" : "samsung SM-A510F",
  "deviceSpeedRank" : 125,
  "dnsFilteringEnabled" : true,
  "enabledFilterIds" : [ 2, 3, 4, 14, 1, 9, 11, 105 ],
  "environment" : "release",
  "filteringQuality" : "FULL",
  "filtersAutoUpdateEnabled" : true,
  "iconType" : "DEFAULT",
  "installedPackages" : [ "com.samsung.android.provider.filterprovider;version=2.0.15;system=true", "com.monotype.android.font.rosemary;version=1.0.03-3;system=true", "com.sec.android.app.DataCreate;version=1.0;system=true", "com.sec.android.providers.mapcon;version=1.1.01-19;system=true", "com.skype.raider;version=7.29.0.370;system=true", "com.gd.mobicore.pa;version=3.0079 (51551);system=true", "com.sec.android.widgetapp.samsungapps;version=1.5.57;system=true", "com.google.android.youtube;version=11.47.57;system=true", "com.samsung.android.app.galaxyfinder;version=4.0.99;system=true", "com.samsung.android.themestore;version=1.03.25(20160614);system=true", "com.sec.android.app.chromecustomizations;version=1.0.03;system=true", "se.ace.simpletruths;version=1.2.8;system=false", "com.android.providers.telephony;version=6.0.1;system=true", "com.sec.android.app.parser;version=1.0.09;system=true", "com.samsung.svoice.sync;version=1.7.21-3;system=true", "com.sec.android.providers.iwlansettings;version=1.1.01-13;system=true", "com.google.android.googlequicksearchbox;version=6.9.37.21.arm;system=true", "com.RTU.MoreOrLess;version=1.0.0;system=false", "com.android.providers.calendar;version=6.0.1;system=true", "com.osp.app.signin;version=2.2.01-46;system=true", "com.samsung.clipboardsaveservice;version=1.0;system=true", "com.sec.automation;version=1.0.1;system=true", "com.android.providers.media;version=6.0.1;system=true", "com.google.android.onetimeinitializer;version=6.0.1;system=true", "com.sec.android.widgetapp.digitalclock;version=5.0.34;system=true", "com.android.wallpapercropper;version=6.0.1;system=true", "com.samsung.android.provider.shootingmodeprovider;version=1.0;system=true", "com.samsung.android.gametuner.thin;version=2.1.2;system=false", "com.skms.android.agent;version=1.0.26-1;system=true", "com.sec.android.app.safetyassurance;version=2.0.11;system=true", "com.sec.factory.camera;version=1.0.27;system=true", "com.viber.voip;version=6.5.5.1365;system=false", "org.simalliance.openmobileapi.service;version=4.0.0;system=true", "com.sec.usbsettings;version=1.0;system=true", "com.samsung.android.easysetup;version=4.0.9329764;system=true", "com.zoomshift.app;version=1.3.1;system=false", "com.android.documentsui;version=6.0.1;system=true", "com.android.externalstorage;version=6.0.1;system=true", "com.sec.android.easyonehand;version=3.0;system=true", "com.sec.factory;version=6.0.1;system=true", "com.android.htmlviewer;version=1.1.09;system=true", "com.android.mms.service;version=6.0.1;system=true", "com.sec.android.wallpapercropper2;version=1.0.39;system=true", "com.android.providers.downloads;version=6.0.1;system=true", "com.samsung.android.qconnect;version=4.1.7947735.0;system=true", "com.samsung.ucs.agent.boot;version=6.0.1;system=true", "com.wsomacp;version=5.1.30;system=true", "com.sec.android.Kies;version=1.0.21;system=true", "com.samsung.faceservice;version=1.0;system=true", "com.sec.android.app.voicenote;version=20.1.81-16;system=true", "com.sec.android.app.easylauncher;version=1.0.61;system=true", "com.samsung.knox.rcp.components;version=2.6.04001026;system=true", "com.monotype.android.font.foundation;version=1.0.01-1;system=true", "com.sec.android.widgetapp.easymodecontactswidget;version=1.0.38;system=true", "com.samsung.android.email.provider;version=3.3.69;system=true", "com.samsung.android.intelligenceservice2;version=2.4.01;system=true", "com.samsung.android.MtpApplication;version=1.0;system=true", "com.sec.android.app.factorykeystring;version=6.0.1;system=true", "com.sec.android.app.samsungapps;version=4.2.04-5;system=true", "com.sec.android.emergencymode.service;version=6.0.1;system=true", "com.google.android.configupdater;version=6.0.1;system=true", "com.sec.android.app.wlantest;version=1.0.0;system=true", "com.microsoft.office.excel;version=16.0.7531.1011;system=true", "com.sec.android.app.billing;version=4.1.00-6;system=true", "com.sec.android.app.minimode.res;version=6.0.1;system=true", "com.android.defcontainer;version=6.0.1;system=true", "com.sec.android.daemonapp;version=1.2.19-1;system=true", "org.zwanoo.android.speedtest;version=3.2.27;system=false", "com.sec.enterprise.knox.attestation;version=1.0.2;system=true", "com.android.vending;version=7.3.07.K-all [0] [PR] 139935798;system=true", "com.android.pacprocessor;version=6.0.1;system=true", "com.dsi.ant.service.socket;version=4.14.20;system=true", "com.sec.android.app.popupuireceiver;version=1.6;system=true", "com.sec.android.AutoPreconfig;version=2.0.0;system=true", "com.microsoft.skydrive;version=4.8;system=true", "com.samsung.android.SettingsReceiver;version=6.0.1;system=true", "com.sec.android.app.soundalive;version=3.1.53;system=true", "com.sec.android.providers.security;version=1.0.04;system=true", "com.sec.android.provider.badge;version=1.0;system=true", "com.android.certinstaller;version=6.0.1;system=true", "com.samsung.android.securitylogagent;version=4.3.52;system=true", "com.android.carrierconfig;version=1.0.0;system=true",
"com.samsung.android.app.assistantmenu;version=1.6.04-0;system=true", "com.samsung.android.communicationservice;version=1.1.36;system=true", "com.sec.android.directconnect;version=3.7;system=true", "com.samsung.SMT;version=201503041;system=true", "com.samsung.cmh;version=2.0.22;system=true", "com.sec.android.ofviewer;version=1.112;system=true", "com.samsung.android.drivelink.stub;version=1.1.09;system=true", "android;version=6.0.1;system=true", "com.android.contacts;version=2.2.49;system=true", "com.samsung.hs20provider;version=1.0;system=true", "com.samsung.android.sm.devicesecurity;version=16.1.67;system=true", "com.dsi.ant.sample.acquirechannels;version=01.00.05;system=true", "com.samsung.android.smartface;version=1.0;system=true", "com.android.mms;version=2.1.72;system=true", "com.android.nfc;version=6.0.1;system=true", "com.android.stk;version=6.0.1;system=true", "com.sec.knox.foldercontainer;version=2.6.04001035;system=true", "com.android.backupconfirm;version=6.0.1;system=true", "com.samsung.klmsagent;version=2.6.172;system=true", "com.samsung.android.app.memo;version=16.0.00-327;system=true", "com.sec.android.app.SecSetupWizard;version=1.0;system=true", "com.microsoft.office.onenote;version=16.0.7571.1804;system=true", "com.android.statementservice;version=1.0;system=true", "brychta.stepan.quantum_en;version=2.3.0;system=false", "com.google.android.gm;version=6.8.132350049.release;system=true", "ru.yandex.taxi;version=3.24.0;system=false", "fm.last.android;version=2.0.0.4;system=false", "com.google.android.apps.tachyon;version=5.1.142054125.DR5_RC14;system=false", "ua.privatbank.ap24;version=5.14.00;system=false", "com.sec.android.app.hwmoduletest;version=6.0.1;system=true", "com.sec.bcservice;version=2.0;system=true", "com.android.calendar;version=3.1.67;system=true", "com.sec.modem.settings;version=1.0.1;system=true", "com.sec.android.app.sysscope;version=1.3.78;system=true", "com.sec.android.app.wallpaperchooser;version=2.1.03;system=true", "com.samsung.android.providers.context;version=2.0.8;system=true", "com.sec.android.app.servicemodeapp;version=6.0.1;system=true", "com.sec.android.preloadinstaller;version=6.0.1;system=true", "com.google.android.setupwizard;version=2.0;system=true", "com.samsung.android.sdk.professionalaudio.utility.jammonitor;version=2.1.07;system=true", "com.sec.android.gallery3d;version=2.1.92;system=true", "com.android.providers.settings;version=6.0.1;system=true", "com.sec.app.TransmitPowerService;version=1.0;system=true", "com.android.sharedstoragebackup;version=6.0.1;system=true", "com.sec.android.widgetapp.dualclockdigital;version=5.0.42;system=true", "com.samsung.android.app.colorblind;version=2.3.26;system=true", "com.google.android.music;version=7.1.4120-1.K.3577996;system=true", "com.android.printspooler;version=1;system=true", "com.samsung.storyservice;version=1.0;system=true", "com.android.dreams.basic;version=6.0.1;system=true", "com.sec.android.app.music;version=16.1.91-14;system=true", "com.android.incallui;version=1.0.21;system=true", "com.sec.app.samsungprintservice;version=3.01.161021;system=true", "com.sec.android.omc;version=1.0.07-0;system=true", "com.sec.android.app.dictionary;version=2.6.12.seller;system=true", "com.android.inputdevices;version=6.0.1;system=true", "com.sec.esdk.elm;version=5.0.07;system=true", "com.samsung.android.app.talkback;version=4.3.01-53;system=true", "com.noodlecake.tryharder.free;version=1.0.1;system=false", "com.android.stk2;version=6.0.1;system=true", "com.adguard.android;version=2.8.76;system=false", "com.samsung.android.app.simplesharing;version=2.1.84;system=true", "com.sec.smartcard.manager;version=2.0;system=true", "com.samsung.android.authservice;version=1.0.15;system=true", "com.sec.android.Preconfig;version=6.0.1;system=true", "com.perm.kate;version=36;system=false", "com.google.android.apps.docs;version=2.4.452.14.35;system=true", "com.google.android.apps.maps;version=9.42.3;system=true", "com.sec.enterprise.mdm.vpn;version=1.3;system=true", "com.tunnelbear.android;version=v136;system=false", "com.samsung.android.weather;version=1.2.19-1;system=true", "com.dsi.ant.plugins.antplus;version=3.6.10;system=true", "com.microsoft.office.word;version=16.0.7531.1011;system=true", "com.sec.android.inputmethod;version=1.2.56;system=true", "com.sec.android.app.clockpackage;version=6.0.22;system=true", "com.sec.android.RilServiceModeApp;version=6.0.1;system=true", "com.google.android.webview;version=56.0.2924.23;system=true", "com.sec.android.app.simsettingmgr;version=1.0;system=true", "com.pikpok.gbod;version=1.5;system=false", "com.pikpok.rua2;version=1.7.1;system=false", "com.microsoft.office.powerpoint;version=16.0.7531.1011;system=true", "com.sec.enterprise.knox.myknoxsetupwizard;version=1.0.28;system=true", "com.samsung.android.app.mirrorlink;version=1.0.53;system=true", "com.android.server.telecom;version=1.0.0;system=true", "com.google.android.syncadapters.contacts;version=6.0.1;system=true", "com.sec.android.fido.uaf.client;version=15.0.79;system=true", "com.samsung.android.clipboarduiservice;version=6.0.1;system=true", "com.android.keychain;version=6.0.1;system=true", "com.devexpert.weather;version=5.9.1.2;system=false", "com.android.chrome;version=55.0.2883.91;system=true", "com.samsung.android.asksmanager;version=1.0.08;system=true", "com.samsung.android.themecenter;version=2.1.0.0;system=true", "com.google.android.packageinstaller;version=6.0.1;system=true", "com.samsung.android.sm;version=16.1.67;system=true", "com.google.android.gms;version=10.0.84 (438-137749526);system=true", "com.google.android.gsf;version=6.0.1;system=true", "com.google.android.tts;version=3.10.10;system=true", "com.android.calllogbackup;version=6.0.1;system=true", "com.google.android.partnersetup;version=6.0.1;system=true", "com.sec.android.diagmonagent;version=4.1.16;system=true", "com.trustonic.tuiservice;version=1.0;system=true", "com.google.android.videos;version=3.21.10;system=true", "com.google.android.apps.nexuslauncher;version=7.1.1-3359438;system=false", "com.sec.spp.push;version=1.6.00;system=true", "com.dsi.ant.server;version=3.0.0;system=true", "com.sec.android.widgetapp.digitalclockeasy;version=5.0.23;system=true", "com.sec.android.app.myfiles;version=3.1.57;system=true", "com.android.proxyhandler;version=6.0.1;system=true", "com.google.chromeremotedesktop;version=53.0.2785.30;system=false", "com.samsung.android.allshare.service.fileshare;version=2.5;system=true", "org.videolan.vlc;version=2.0.6;system=false", "com.sec.android.mimage.photoretouching;version=1.2.77;system=true", "com.sec.android.app.launcher;version=2.2.85;system=true", "com.samsung.android.universalswitch;version=1.0.00-64;system=true", "com.sec.android.app.sns3;version=2.0.17;system=true", "flipboard.boxer.app;version=2.6.9;system=true", "com.google.android.feedback;version=6.0.1;system=true", "com.google.android.apps.photos;version=2.6.0.141921143;system=true", "com.google.android.syncadapters.calendar;version=5.2.3-99827563-release;system=true", "com.android.managedprovisioning;version=6.0.1;system=true", "com.samsung.android.app.filterinstaller;version=2.0.03;system=true", "com.spotify.music;version=6.2.0.1015;system=false", "com.sec.android.providers.tasks;version=6.0.1;system=true", "com.sec.android.app.sbrowser;version=4.0.20-66;system=true", "com.monotype.android.font.chococooky;version=1.0.03-3;system=true", "com.android.dreams.phototable;version=6.0.1;system=true", "com.sec.android.service.health;version=2.1.3.001;system=true", "com.samsung.safetyinformation;version=1.0.05-0;system=true", "com.facebook.katana;version=106.0.0.26.68;system=true", "com.sec.android.app.ringtoneBR;version=6.0.1;system=true", "com.android.providers.partnerbookmarks;version=6.0.1;system=true", "com.google.android.gsf.login;version=6.0.1;system=true", "com.cleanmaster.sdk;version=5.6.2;system=true", "com.samsung.android.app.accesscontrol;version=1.5.13-37;system=true", "com.android.wallpaper.livepicker;version=6.0.1;system=true", "com.samsung.android.beaconmanager;version=4.0.9329764;system=true", "com.sec.enterprise.mdm.services.simpin;version=6.0.1;system=true", "com.samsung.ucs.ucspinpad;version=1.0;system=true", "com.android.apps.tag;version=2.0.02;system=true", "com.facebook.orca;version=100.0.0.29.61;system=false", "com.samsung.android.app.FileShareClient;version=2.5;system=true", "com.facebook.system;version=16.2;system=true", "com.sec.android.app.popupcalculator;version=5.0.59;system=true", "com.sec.android.soagent;version=3.1.16;system=true", "org.mozilla.firefox;version=50.1.0;system=false", "com.samsung.android.fmm;version=6.1.21;system=true", "com.samsung.android.mdm;version=1.0;system=true", "com.sec.android.fido.uaf.asm;version=15.0.79;system=true", "com.sec.android.app.shealth;version=5.4.1.0003;system=true", "com.sec.phone;version=1.0;system=true", "com.samsung.android.app.scrollcapture;version=1.0.67;system=true", "com.samsung.knox.appsupdateagent;version=2.6.04001008;system=true", "com.google.android.backuptransport;version=6.0.1;system=true", "com.sec.knox.knoxsetupwizardclient;version=2.6.04001036;system=true", "com.samsung.android.scloud;version=1.5.66;system=true", "com.samsung.android.app.soundpicker;version=6.1.62-15;system=true", "com.sec.app.RilErrorNotifier;version=1.0.0;system=true", "com.samsung.android.spayfw;version=1.0.01;system=true", "com.android.bookmarkprovider;version=6.0.1;system=true", "com.android.settings;version=6.0.1;system=true", "com.samsung.app.newtrim;version=1.1.21;system=true", "com.sec.android.app.bluetoothtest;version=6.0.1;system=true", "com.samsung.android.intelligenceservice;version=2.2.02;system=true", "com.sec.android.emergencylauncher;version=1.0.68;system=true", "com.google.android.apps.books;version=3.11.19;system=false", "com.sec.hearingadjust;version=2.0.51;system=true", "com.google.android.apps.inbox;version=1.37 (142224063);system=false", "com.samsung.android.dlp.service;version=1.0;system=true", "com.samsung.android.bbc.bbcagent;version=2.0;system=true", "com.samsung.android.voicewakeup;version=1.9.24-16;system=true", "com.sec.android.splitsound;version=1.0;system=true", "com.lexa.fakegps;version=2.0.6;system=false", "com.wssnps;version=7.1.37;system=true", "com.samsung.android.app.watchmanagerstub;version=1.1.15-12310;system=true", "com.delphicoder.flud;version=1.4.8.1;system=false", "com.policydm;version=4.1.80;system=true", "com.samsung.android.app.FileShareServer;version=2.5;system=true", "com.samsung.android.sdk.professionalaudio.app.audioconnectionservice;version=2.1.00;system=true", "com.enhance.gameservice;version=1.0.75;system=true", "com.sec.android.app.snsimagecache;version=1.0.01;system=true", "com.android.vpndialogs;version=6.0.1;system=true", "com.google.android.apps.wallpaper;version=1.0.139964517;system=false", "com.google.android.talk;version=15.0.141104777;system=true", "com.samsung.dcmservice;version=1.0;system=true", "com.android.phone;version=1.0.0;system=true", "com.android.shell;version=6.0.1;system=true", "com.android.providers.userdictionary;version=6.0.1;system=true", "com.sec.enterprise.knox.cloudmdm.smdms;version=1.7.16;system=true", "com.arcsoft.magicshotstudio;version=3.0.0.80;system=true", "com.sec.svoice.lang.de_DE;version=1.7.31;system=true", "com.sec.svoice.lang.en_GB;version=1.7.31;system=true", "com.sec.svoice.lang.en_US;version=1.7.31;system=true", "com.sec.svoice.lang.es_ES;version=1.7.31;system=true", "com.sec.svoice.lang.fr_FR;version=1.7.31;system=true", "com.sec.svoice.lang.it_IT;version=1.7.31;system=true", "com.wssyncmldm;version=1.5.41;system=true", "com.sec.svoice.lang.ru_RU;version=1.7.31;system=true", "net.megogo.vendor;version=1.0.samsung_2million;system=false", "com.android.location.fused;version=6.0.1;system=true", "com.samsung.android.sm.provider;version=16.0.35;system=true", "com.android.systemui;version=6.0.1;system=true", "com.sec.android.app.personalization;version=6.0.1;system=true", "com.monotype.android.font.cooljazz;version=1.0.04-4;system=true", "com.android.bluetoothmidiservice;version=6.0.1;system=true", "com.facebook.appmanager;version=16.2;system=true", "com.samsung.voiceserviceplatform;version=1.9.38-5;system=true", "com.sec.android.provider.logsprovider;version=2.0;system=true", "com.sec.android.app.SamsungContentsAgent;version=1.0.03;system=true", "com.samsung.aasaservice;version=5.0;system=true", "com.samsung.android.allshare.service.mediashare;version=2.2;system=true", "com.sec.android.app.fm;version=1.0;system=true", "com.sec.android.app.mt;version=1.0.03-0;system=true", "com.samsung.android.app.gestureservice;version=1.0.00-1;system=true", "com.sec.android.provider.emergencymode;version=1.0;system=true", "com.google.android.play.games;version=3.9.08 (3448271-038);system=false", "com.sec.android.app.applinker;version=1.0.00-26;system=true", "com.samsung.android.fingerprint.service;version=1.1.0;system=true", "com.sec.knox.switcher;version=2.6.04001029;system=true", "com.sec.android.app.camera;version=4.0;system=true", "com.google.android.apps.magazines;version=4.0.0;system=false", "com.android.bluetooth;version=6.0.1;system=true", "com.android.providers.contacts;version=6.0.1;system=true", "com.sec.android.app.magnifier;version=2.2.22;system=true", "com.sec.android.widgetapp.webmanual;version=1.0.10;system=true", "com.samsung.sec.android.application.csc;version=6.0.1;system=true", "com.android.captiveportallogin;version=6.0.1;system=true", "com.samsung.upsmtheme;version=2.00.22;system=true", "com.samsung.android.sconnect;version=1.0.0;system=true", "com.samsung.android.coreapps;version=2.3.27;system=true", "com.adguard.android.contentblocker;version=1.3.0;system=false", "com.google.android.inputmethod.latin;version=6.0.69.142176780-armeabi-v7a;system=false", "com.samsung.android.video;version=1.1.02;system=true", "ua.novaposhtaa;version=4.85;system=false", "com.samsung.location;version=v5.12l;system=true" ],
  "installerPackage" : null,
  "kernelVersion" : "3.10.61-8208732",
  "premium" : true,
  "proxyMode" : false,
  "proxyPort" : 8080,
  "proxySetupManualMode" : false,
  "referrer" : null,
  "sendAnonymousStatistics" : true,
  "showUsefulAds" : false,
  "sourceApk" : "/data/app/com.adguard.android-2/base.apk",
  "sslMitmConfiguration" : "{\"certificateInstalledToSystemStorage\":null,\"mitmList\":\"1024 domains\",\"mitmListMode\":\"WHITELIST\"}",
  "statisticsInfo" : "Blocked threats:0; Blocked banners:51841; Traffic saved:1353992192;",
  "trial" : false,
  "updateChannel" : "BETA",
  "upstreamProxySettings" : null,
  "userfilter" : [ "lg.com.ua##body", "lg.com##body" ],
  "versionName" : "2.8.76",
  "whitelist" : [ ]
}

**Comment by Alex-302** [comment]
логи

**Comment by evgeniy-ADG** [comment]
Record HTTP requests was enabled, cache cleared, ads starting from 18:42

[debug (6).txt](https://github.com/AdguardTeam/AdguardFilters/files/671153/debug.6.txt)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
на пробу
```
@@||googleads.g.doubleclick.net/mads/static/mad/sdk/native/*/sdk-core-v40-impl.js$app=com.devexpert.weather
||googleads.g.doubleclick.net/mads/gma?carrier=$replace=/\<script\>[\s\S]*\<\/script\>/,important
```
Без фильтрации HTTPS можно даже не пробовать.
