### ISSUE TITLE
http://www.faronics.com - download won't start

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3867]
Currently, I am having this issue only on Faronics download link (http://www.faronics.com/downloads/download-form/?product=DFS).
The process goes that when I fill up my information and click on the submit button. It will automatically go back and ask me to fill up the form again. But when i disabled Adugard, after clicking the Submit button. i as able able to download the file.

I found the cause. It is because I enabled self-destructing first party cookies. Disabling it fix my problem.

<details>

without adg 

![untitled3](https://cloud.githubusercontent.com/assets/15856304/21462247/794a9060-c962-11e6-987f-77c8fb9925d1.png)

with adg (returns to the same page when you fill the form and press OK)
![untitled2](https://cloud.githubusercontent.com/assets/15856304/21462249/806f2af4-c962-11e6-866b-d37c8a55f4f0.png)

</details>

1456343

**Comment by Alex-302** [comment]
> self-destructing first party cookies

Not reproduced with timeout=10 minutes, only with "0"
For user filter:
```
@@||faronics.com^$stealth
```
