### ISSUE TITLE
http://www.nationalpost.com - ads, no assistant

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3868]
1457728

http://www.nationalpost.com/index.html

![afmmiogcemagpgpo](https://cloud.githubusercontent.com/assets/15856304/21466057/3ad0c38e-c9c3-11e6-83bb-b5450265c66f.png)

User filter is clear.

<details>

![kjphdmaclikfngei](https://cloud.githubusercontent.com/assets/15856304/21466062/75ed9096-c9c3-11e6-89a9-6941cbb586c1.png)

Os version: Microsoft Windows NT 10.0.14393.0
Dot .net version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: 76ffee40fe864f4891f62b3be910f6d0
Language: en
AppVersion: 6.1.258.1302
Main settings: 
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:119 Name: Icelandic ABP List Url: http://adblock.gardar.net/is.abp.txt
FilterId:216 Name: Adblock polskie reguły Url: http://www.certyficate.it/adblock/adblock.txt
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Wfp
Ads Blocked: 269186, Trackers Blocked: 210143
Filtering Mode: Driver
Application lifetime: 232.06:17:28.7885349
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"
}

**Comment by evgeniy-ADG** [comment]
> The problem appears to be limited to Chrome.  If I open the same page in Microsoft Edge I get no adverts (but still no Adguard  Assistant icon).

**Comment by Alex-302** [comment]
Not reproduced. 
Check only with English filter.

**Comment by F4z** [comment]
I also do not see this ads, but I think this website uses `g00/I10C script` mentioned here - https://github.com/AdguardTeam/AdguardFilters/issues/3844
@Alex-302 could you block this, please?

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/11742596/21472250/ff1294a4-cacf-11e6-804d-38987f6dc569.png)

</details

**Comment by Alex-302** [comment]
As I say, I can't reproduce these ads. When I block g00 sub-domains, the site is not loading completely.
@seanl-adg could you please check this site? I got few errors with your JS rules.

**Comment by seanl-adg** [comment]
I can't reproduce ads but can reproduce g00 requests. As listed in the database in the referenced issue, this website uses HtmlStreaming which we don't block right now. I noticed that now the 'alert' JS rule for detecting I10C type is not working currently.

**Comment by evgeniy-ADG** [comment]
I can't see the ad too (the assistant icon is missing though), but the customer has ads (googleads.g.doubleclick.net/...) even in the incognito mode. What can I suggest him?

**Comment by seanl-adg** [comment]
We can suggest him to add several rules manually:
```
@@/favicon.ico^$domain=nationalpost.com
@@||google-analytics.com/__utm.gif^$domain=nationalpost.com
@@/adchoice_$image,domain=nationalpost.com
@@||nationalpost.com^$generichide
```

**Comment by evgeniy-ADG** [comment]
It's back, I can to reproduce the issue even with those rules. They worked before, as far as I understand.
