### ISSUE TITLE
pikas-img.ru, img-pika.ru, images-pic.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3869]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Баннеры на баннерах 18+. обязательно нужно дождаться загрузки.
И там еще перенаправления. 

http://pikas-img.ru/1m8.html 
http://img-pika.ru/1oa.html
http://images-pic.ru/ldh.html

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21466368/f1ad31ba-c9d1-11e6-9ccc-9dbf8756e110.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21466374/3dabeb7e-c9d2-11e6-96fb-708c3c2f155b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | FF
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Adguard filters: | 1,2,3,4,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 731323

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Поправил.

**Comment by OlegSUP** [comment]
Повторная жалоба на данный сайт, у нас повторяется.

<details>

![image](https://cloud.githubusercontent.com/assets/26434103/25891997/a96d3dda-357b-11e7-983f-15726c1eeb22.png)

</details>

Ticket ID: 1556369

**Comment by Alex-302** [comment]
там домен другой. 
Поправил.
