### ISSUE TITLE
fotostrana.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3870]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

Реклама внутри сайта

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21467080/7ba68940-c9e9-11e6-9c0b-3ca48a9a6add.png)

Если пригодится
![image](https://cloud.githubusercontent.com/assets/18548949/21467087/ab084782-c9e9-11e6-97d6-8c0cca3455e8.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21470650/9f6613da-ca9a-11e6-96e0-887788fd2804.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21470654/2b587130-ca9b-11e6-899d-1e6fa9509e73.png)

</details>

***Steps to reproduce the problem***:

+ необходимо зарегистрироваться или же войти с помощью соцсети
+ перейти сюда https://fotostrana.ru/rating/top/ (возможно нужно будет поклацать по сайту)
далее сбоку в столбике (реклама) будут и сами баннеры

+ Главная страница (выбрано любое фото в конкурсе "Лицо с обложки")
и будет баннер внизу

+ при просмотре профиля чьего-то будет баннер в самом углу

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Хром
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Adguard filters: | 1,2,3,4,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1473867

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by vgavrish** [comment]
а у меня все ще есть
могу доступ дать

**Comment by Alex-302** [comment]
Ок, давай глянем.
Там точно реклама, а не своё что-то?
