### ISSUE TITLE
https://www.wired.com - Incorrect blocking 

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3871]
Incorrect blocking on page:
https://www.wired.com/2016/12/encryption-app-signal-fights-censorship-clever-workaround/

The page is not scrollable with Adguard enable. Works if I disable it.

<details>

Application version: 1.1.3.31
Application lifetime: 2016-12-23 22:12:47 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: E0F29222-A84E-4298-8068-8BF171943ABD

Locale: en
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.77 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.76 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.88 Enabled=YES
ID=6 Name="German filter" Version=1.0.29.60 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.34 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.92 Enabled=YES

</details>

Ticket ID: 1473639

**Comment by Alex-302** [comment]
Not reproduced with the same filters.
