### ISSUE TITLE
filmysign.com { Popup Ads }

### ISSUE THREAD

**Issue by ghajini** [AdguardTeam/AdguardFilters#38710]
### URL(s) where the issue occurs

`https://filmysign.com/stake-land-2010-hollywood-hindi-dubbed-full-movie-watch-online-free-download/`

### Describe the issue

Popup ads on clicking anywhere in page

### Versions

- Browser/version: firefox browser desktop stable cersion

- Adguard  version: adguard browser extension version 3.2.1

### Settings

- adguard browser extension default settings+ adguard spyware filter + phishing &malware protection on

**Comment by Alex-302** [comment]
Not reproduced. @zloyden please take a look.

**Comment by zloyden** [comment]
Sadly, not reproduced on latest stable firefox with extension.

**Comment by ghajini** [comment]
Please check right now....

**Comment by ghajini** [comment]
Is it possible to fix
