### ISSUE TITLE
daemon-tools.cc

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#38719]
`https://www.daemon-tools.cc/`

Cookie notice.

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by krystian3w** [comment]
Cookies is blocked in `Polskie filtry rodo-ciasteczkowe`: https://github.com/AdguardTeam/iltersRegistry/blob/4f41fe9674b8a5ff75a434f4bf1a917fd1613a1a/filters/ThirdParty/filter_217_PolskiFiltrCookies/filter.txt#L450

https://github.com/AdguardTeam/FiltersRegistry/commit/b7733a2f5d49282c6a388855101dad2a11da3dcb#diff-a8744bf71672ffd0c7161f12d21390e6R395

**Comment by krystian3w** [comment]
Cookies is blocked in `Polskie filtry rodo-ciasteczkowe`: 

https://github.com/AdguardTeam/FiltersRegistry/blob/4f41fe9674b8a5ff75a434f4bf1a917fd1613a1a/filters/ThirdParty/filter_217_PolskiFiltrCookies/filter.txt#L450

https://github.com/AdguardTeam/FiltersRegistry/commit/b7733a2f5d49282c6a388855101dad2a11da3dcb#diff-a8744bf71672ffd0c7161f12d21390e6R395

**Comment by adranger** [comment]
@Alex-302  This is an international site.

![cookie](https://user-images.githubusercontent.com/35470489/63295554-556a5300-c2a3-11e9-83b9-a63773e6a752.png)

**Comment by Alex-302** [comment]
What is wrong?
