### ISSUE TITLE
opensource.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#38720]
`https://opensource.com/article/19/8/how-encrypt-files-gocryptfs`

Newsletter annoyance, social buttons and cookie notice.

![annoyances](https://user-images.githubusercontent.com/35470489/63205015-87e23900-c074-11e9-8d4a-897105c51266.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
don't make URL non-clickable
