### ISSUE TITLE
https://lols.gg/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3873]
https://lols.gg/

before

![before](https://cloud.githubusercontent.com/assets/15856304/21470353/62c9e422-ca8d-11e6-94e5-ce52cbe27fc2.png)

after:

![after](https://cloud.githubusercontent.com/assets/15856304/21470354/66978b7c-ca8d-11e6-800f-0aa72d2ffada.png)

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21470358/90aeb782-ca8d-11e6-9886-c022df864f8f.png)

**Comment by Alex-302** [comment]
Исправил в русском.
