### ISSUE TITLE
http://www.rbc.ru/ - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3874]
Пропущена реклама на странице:
http://www.rbc.ru/

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21470698/4c94c8c4-ca9d-11e6-9323-ec262fb4fcb8.png)

</details>

<details>

Application version: 1.1.3.31
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: 1A833391-C661-42E7-926E-BE83BA5A5F21

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.79 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.76 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.90 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.69 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.93 Enabled=YES

</details>

Ticket ID: 1213960

**Comment by Alex-302** [comment]
Поправил.

**Comment by Alex-302** [comment]
@dzamyshlyayeva а подробности хоть какие-нибудь?

**Comment by dzamyshlyayeva** [comment]
извините, не там переоткрыла задачу

**Comment by Alex-302** [comment]
можно не переоткрывать) Реклама неуловимая, уже три дня ищу где повторить)
