### ISSUE TITLE
http://memurlar.net/ - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3875]
http://memurlar.net/ - incorrect blocking

You can see black gray space on the bottom. I couldn't disable it with adguard or adguard pro element blocker tool too.

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/21470713/158b7cf0-ca9e-11e6-95ac-1564426ad61b.png)

</details>

<details>

Application version: 1.1.2.57
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 21627A4D-4CD6-479A-A7B3-DC6ECBD71AB8

Locale: tr
Region: tr

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.79 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.76 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.90 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.5.54 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.93 Enabled=YES

</details>

Ticket ID: 1474294

**Comment by Alex-302** [comment]
Can't reproduce this banner without Adguard.
