### ISSUE TITLE
Apparently no video ad blocking on sueddeutsche.de

### ISSUE THREAD

**Issue by JayBrown** [AdguardTeam/AdguardFilters#3876]
Example: http://www.sueddeutsche.de/politik/de-maiziere-bedrohungslage-in-deutschland-bleibt-hoch-1.3308874

There's a 20 to 30 seconds video ad that isn't blocked by Adguard (newest version).

**Comment by Alex-302** [comment]
Please don't ignore provided template.
Not reproduced.
