### ISSUE TITLE
myscore.com.ua - Incorrect blocking

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3877]
***Description***: Incorrect blocking on the page:
http://www.myscore.com.ua/
Unable to Sign up or Log in. 

Screenshot:
<details>

![3f0ef29db959](https://cloud.githubusercontent.com/assets/17504743/21473298/3eda12b8-cb0e-11e6-8d89-064f52b05b3c.jpg)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 6.1.7601
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | TDI
Stealth mode options(Windows) | "BlockThirdPartyCookies": false,  "BlockThirdPartyCookiesPeriodMin": 30, "BlockFirstPartyCookies": false,  "BlockFirstPartyCookiesMin": 2880,  "DisableThirdPartyCache": true  "BlockWebRtc": true,  "BlockBrowserPushApi": true,  "BlockBrowserLocationApi": true,  "RemoveXClientDataHeader": true,  "HideSearchQueries": true, "SendDoNotTrackHeader": true,  "RemoveRefererFromThirdPartyRequests": true,  "HideUserAgent": true,  "CustomUserAgent": null,  "CustomReferer": null,  "HideIp": false,  "CustomIp": "120.24.73.165"
Adguard filters: | Russian, English, Spyware, Social media, Annoyances

Ticket ID(if exists): 1150428

**Comment by Alex-302** [comment]
It is not caused by Adguard
Added to annoyances filter:
```
myscore.com.ua###lsid-window-mask
```
