### ISSUE TITLE
atarigamer.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#38785]
`https://www.atarigamer.com/articles/top-20-atari-lynx-games-by-jon-mc`

Annoyance covering the article as you scroll down:

![atarigamer](https://user-images.githubusercontent.com/35470489/63218836-11f4d500-c13b-11e9-876d-dc6611659c33.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by LucasDiTomase** [comment]
Fixed with this rule

atarigamer.com##.at_sm_popup
