### ISSUE TITLE
dna.fi - Incorrect blocking (iOS)

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3879]
***Description***: Incorrect blocking on the page:
https://www.dna.fi/
iOS

Screenshot:
<details>

<b>Adguard on</b>
![image1](https://cloud.githubusercontent.com/assets/17504743/21473596/dc517224-cb19-11e6-93e7-e4671aa95a6e.png)

<b>Adguard off</b>
![image2](https://cloud.githubusercontent.com/assets/17504743/21473597/dde00880-cb19-11e6-8b77-ba188f6eebfc.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2
Browser: | Safari
Adguard version: | 1.1.3.31
Adguard filters: | English, Spyware, Social media, Russian, Safari, Wiltteri

Ticket ID(if exists): 1474323

**Comment by Alex-302** [comment]
fixed
