### ISSUE TITLE
thehackernews.com

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardFilters#38806]
Social bar top right -> Rule: thehackernews.com##.top-follow
Suscribe buttom -> Rule: thehackernews.com##.sub-button

![Captura de Pantalla 2019-08-18 a la(s) 10 29 58](https://user-images.githubusercontent.com/46760897/63225106-52883900-c1a3-11e9-8183-f9b8753bc220.png)

Social bar -> Rule: thehackernews.com##.social-box 

Also: thehackernews.com###follow-us

![Captura de Pantalla 2019-08-18 a la(s) 10 28 31](https://user-images.githubusercontent.com/46760897/63225107-53b96600-c1a3-11e9-8308-e9e40f597a57.png)

**Comment by Alex-302** [comment]
not annoying

**Comment by LucasDiTomase** [comment]
Hi. But shouldn't social AdGuard filter block these?

**Comment by superlex** [comment]
@LucasDiTomase 
AG Social filter doesn't block links to the social accounts, only widgets.

**Comment by LucasDiTomase** [comment]
Ok. I did not know. Thanks.
