### ISSUE TITLE
anon.to

### ISSUE THREAD

**Issue by poganytamastsys** [AdguardTeam/AdguardFilters#38807]
Adguard DNS (176.103.130.130) is blocking the website anon.to, with malware site reason.
This is an url shortener service. I agree that the site can be used to hide malicious links, but it is not a malware site.
![2019-08-18 15 39 02](https://user-images.githubusercontent.com/35097992/63225290-6bf2aa80-c1ce-11e9-866d-6428315d3ce9.jpg)

**Comment by TheHasagi** [comment]
Removed from the blacklist.
