### ISSUE TITLE
http://mintmanga.com - pop-ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3880]
http://mintmanga.com/magical_girl_of_the_end/vol3/12?mature=1

Когда читаешь на этом сайте через 5-10 мин выбивает на рекламный сайт. Например, если нажать на "Закрыть справку", то переадресует на другйо сайт.

<details>

Application version: 1.1.2.57
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2.1
ID: 92F89E17-A6F1-459D-9181-EC67856A1220

Locale: ru
Region: md

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.79 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.76 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.88 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.24 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.69 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.31 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.6.34 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.92 Enabled=YES

**Comment by Alex-302** [comment]
Added to Safari filter
```
/\:\/\/[a-z0-9]*.[a-z]*\/[0-9]*\//$domain=mintmanga.com,third-party
```
