### ISSUE TITLE
https://www.icloud.com/ - annoying banner at the top

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3882]
https://www.icloud.com/

![icloud com annoying banner](https://cloud.githubusercontent.com/assets/15856304/21479155/b21af69c-cb5a-11e6-8641-46b9ff351fbc.gif)

<details>

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0
ID=2 Name="English filter" Version=1.1.3.79
ID=3 Name="Spyware filter" Version=1.0.9.76
ID=4 Name="Social media filter" Version=1.0.15.90
ID=14 Name="Annoyances filter" Version=1.0.8.25
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95

**Comment by Alex-302** [comment]
It is not safely in this case.
