### ISSUE TITLE
http://xrutor.org/top/ - pop-ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3883]
http://xrutor.org/top/

После нажатия любой ссылки на сайте открывается https://sslcasino10.com или другой.

<details>

Application version: 1.1.3.31
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: 3C8C6539-8D95-4FF2-8A49-87A62E39BC3C

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.78 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.76 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.88 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.24 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.69 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.92 Enabled=YES

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||xrutor.org/lastvisit.js
```
