### ISSUE TITLE
www.vpgazeta.ru - Missed ads

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3885]
***Description***: Missed ads on the page:
http://www.vpgazeta.ru/

Screenshot:
<details>

![screenshot 6](https://cloud.githubusercontent.com/assets/17504743/21484317/2ea71c3e-cb99-11e6-9ada-670913f3db39.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 10.12 (Reproduced on Windows with basic filters) 
Browser: | Chrome
Adguard version: | 1.4.0
Adguard filters: | English, Spyware, Social media, Annoyance, Russian, German, Safari, EasyList China, EasyList Czech and Slovak, EasyList Lithuania

Ticket ID(if exists): 1475278

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
vpgazeta.ru##div[style="position:relative; left:0px; top:0px; width:100%; height:149px"]
||vpgazeta.ru/share/docs/*.gif
vpgazeta.ru##div[style^="float:right; width:220px;"] > div[style^="height:"]:empty
vpgazeta.ru##a[href="http://www.vpgazeta.ru/article/advert"]

```
