### ISSUE TITLE
Aliexpress - Incorrect blocking

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3886]
***Description***: 
После последнего обновления
закрываются открываемые в новом окне
вкладки на aliexpress. Ссылки вида
https://goo.gl/U6dmkU (например с видео
https://www.youtube.com/watch?v=1sbz2HfmyH0) закрываются в
100% случаев, но если скопировать ссылку
и в новом окне открыть - открывается.
Также на самом сайте Aliexprees ссылки в
новом окне окрываются не с первого
раза (т.е.окрывается вкладка и сразу
закрывается), также зарывается
вкладка при переходе например на
другой товар в текущем окне.

Проблема вызвана фильтром Liste FR

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | TDI
Stealth mode options(Windows) | "BlockThirdPartyCookies": true,  "BlockThirdPartyCookiesPeriodMin": 30,  "BlockFirstPartyCookies": false,  "BlockFirstPartyCookiesMin": 2880,  "DisableThirdPartyCache": true,  "BlockWebRtc": true,  "BlockBrowserPushApi": false,  "BlockBrowserLocationApi": true,  "RemoveXClientDataHeader": true,  "HideSearchQueries": true,  "SendDoNotTrackHeader": true,  "RemoveRefererFromThirdPartyRequests": false,  "HideUserAgent": false,  "CustomUserAgent": null,  "CustomReferer": null,  "HideIp": false,  "CustomIp": "209.141.53.254"
Adguard filters: | Russian, English, Spyware, Social media, German, EasyList China, Liste FR, Wiltteri, Icelandic, Adblock polskie reguly, EasyList Azech

Ticket ID(if exists): 1474381

**Comment by Alex-302** [comment]
Если юзер французским не владеет, то лучше выключить этот фильтр.
В противном случае можно выключить эти правила в фильтре:
```
||aliexpress.com^*&aff_platform=$popup
||click.aliexpress.com^$popup
```
