### ISSUE TITLE
thedrum.com

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardFilters#38876]
Take an article, for example this one: https://www.thedrum.com/news/2019/06/19/hands-the-cookie-jar-the-future-targeting-restrictions-data-tighten

![Captura de Pantalla 2019-08-19 a la(s) 08 46 41](https://user-images.githubusercontent.com/46760897/63287710-65793700-c291-11e9-85f1-019c4d8e79b9.png)

I managed to block this message with this rule: thedrum.com##.freewall

But then the text in the article did this:

![Captura de Pantalla 2019-08-19 a la(s) 14 54 14](https://user-images.githubusercontent.com/46760897/63287737-7c1f8e00-c291-11e9-9455-87b1b6b70233.png)

I cannot block that transparency/opacity effect

**Comment by krystian3w** [comment]
If addon/application support CSS filters:

`thedrum.com#$#.freewall--disable .article__body, .freewall--disable .article__img, .freewall--disable .feature__body, .freewall--disable .list-container { -webkit-filter: blur(0) !important; filter: blur(0) !important }`

**Comment by LucasDiTomase** [comment]
Thanks again! That worked perfect :)
