### ISSUE TITLE
thelocal.ch

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardFilters#38877]
![Captura de Pantalla 2019-08-19 a la(s) 14 59 15](https://user-images.githubusercontent.com/46760897/63288004-05cf5b80-c292-11e9-8831-48d9b3fecd30.png)

I managed to block the second sponsored article with this rule: thelocal.ch##.promo-module

But I cannot block the first one because the class name is random

![Captura de Pantalla 2019-08-19 a la(s) 14 59 43](https://user-images.githubusercontent.com/46760897/63288051-24cded80-c292-11e9-8c53-41b015e75f1e.png)

I already tried this rule: thelocal.ch#?##root > div > div:contains(Expat health) 

and also this rule: thelocal.ch#?##root > div > div:contains(Sponsored)

but they don't seem to work

**Comment by krystian3w** [comment]
If addon support CSS filters:

`thelocal.ch#$#.freewall--disable .article__body, .freewall--disable .article__img, .freewall--disable .feature__body, .freewall--disable .list-container { -webkit-filter: blur(0) !important; -filter: blur(0) !important }`

**Comment by krystian3w** [comment]
If addon/application support CSS filters:

`thelocal.ch#$#.freewall--disable .article__body, .freewall--disable .article__img, .freewall--disable .feature__body, .freewall--disable .list-container { -webkit-filter: blur(0) !important; -filter: blur(0) !important }`

**Comment by krystian3w** [comment]
If addon/application support CSS filters:

`thelocal.ch#$#.freewall--disable .article__body, .freewall--disable .article__img, .freewall--disable .feature__body, .freewall--disable .list-container { -webkit-filter: blur(0) !important; filter: blur(0) !important }`

**Comment by krystian3w** [comment]
You disabled `no block good ads`?

**Comment by LucasDiTomase** [comment]
I just tried the rule you just posted and no luck. Not working :(

No, there no ads exceptions enabled on my AdGuard for Mac

**Comment by LucasDiTomase** [comment]
Another annoyance I just found in the same website

![Captura de Pantalla 2019-08-19 a la(s) 18 23 43](https://user-images.githubusercontent.com/46760897/63300526-cc591900-c2ae-11e9-8cd2-d23df5bc3d55.png)

I managed to fix it partially with these 2 rules:

thelocal.ch##.tp-modal
thelocal.ch##.tp-backdrop

but the website stands still and won't let me scroll. Its stuck and there is a div on top of the content but I can't block it

![Captura de Pantalla 2019-08-19 a la(s) 18 27 55](https://user-images.githubusercontent.com/46760897/63300646-16da9580-c2af-11e9-9c26-609e11c88985.png)

**Comment by krystian3w** [comment]
I no see in code any `id="root"`?

try this:

`thelocal.ch#?#:root > body > div > div:contains(Sponsored)`

`thelocal.ch#?#:root > body > div > div:contains(Expat health)`

`:root` - in most cases this is `<html> ... </html>`

---

https://developer.mozilla.org/en-US/docs/Web/CSS/:root
https://developer.mozilla.org/es/docs/Web/CSS/:root

**Comment by LucasDiTomase** [comment]
Those 2 rules worked perfect! Thanks :)

So, to sumarize. So far these rules fix some of the issues:

thelocal.ch##.promo-module
thelocal.ch#?#:root > body > div > div:contains(Sponsored)
thelocal.ch#?#:root > body > div > div:contains(Expat health)

But the popup I just posted is still not solved

**Comment by krystian3w** [comment]
> https://github.com/AdguardTeam/AdguardFilters/issues/38877#issuecomment-522761155 + https://github.com/AdguardTeam/AdguardFilters/issues/38877#issuecomment-522762026

I cannot reproduce - maybe blocked by network filter on my side...

---

If addon / application support CSS filters try this:

`thelocal.ch#$#body { overflow: visible !important; }`

if nope, I suppose no possible block without breakage or scriplet injection (if supported on macOS app / addon).

**Comment by BlazDT** [comment]
Fixed newsletter and sponsored posts. Update available in about 3 hours.

Adblock detection not reproduced, please check @zloyden

**Comment by LucasDiTomase** [comment]
Yeah it works great in Google Chrome. I was testing it on Safari and I think the problem is happening only there. So, everything good in Chrome but not on Safari. Its odd because I am using AdGuard for Mac so the filters should work equally fine in every browser, but I just verified that Safari is not working while Chrome is, so...

To sumarize, these rules are working great and have fixed my issues:

thelocal.ch##.promo-module
thelocal.ch#?#:root > body > div > div:contains(Sponsored)
thelocal.ch#?#:root > body > div > div:contains(Expat health)

thelocal.ch##.tp-modal
thelocal.ch##.tp-backdrop
thelocal.ch#$#body { overflow: visible !important; }

**Comment by LucasDiTomase** [comment]
There is one "sponsored" section that it is not being blocked by the rules ( even though it seems the same as the others ). If you open an article like this one https://www.thelocal.ch/20190819/swiss-city-does-u-turn-over-100-franc-fine-for-5-year-old-girl-without-ticket you will find it below the text

![Captura de Pantalla 2019-08-19 a la(s) 18 49 32](https://user-images.githubusercontent.com/46760897/63301946-3e7f2d00-c2b2-11e9-92ba-3dc1a43e40d1.png)

I tried with no luck a rule like the others ( slightly changed to match this case ): thelocal.ch#?#:root > body > div > div:contains(From our sponsors)

But it breaks the website

![Captura de Pantalla 2019-08-19 a la(s) 18 52 35](https://user-images.githubusercontent.com/46760897/63302080-9ae24c80-c2b2-11e9-9cfa-84828197045d.png)

**Comment by krystian3w** [comment]
Deeper embeded on site:

`thelocal.ch#?#body > div > div > div:contains(From our sponsors)`

**Comment by LucasDiTomase** [comment]
That worked! Thanks again :)

**Comment by LucasDiTomase** [comment]
To sumarize, these rules are working great and have fixed my issues:

thelocal.ch##.promo-module
thelocal.ch#?#:root > body > div > div:contains(Sponsored)
thelocal.ch#?#:root > body > div > div:contains(Expat health)
thelocal.ch#?#body > div > div > div:contains(From our sponsors)
thelocal.ch##.tp-modal
thelocal.ch##.tp-backdrop
thelocal.ch#$#body { overflow: visible !important; }

**Comment by krystian3w** [comment]
maybe this is safe - but very slow and possible lag of site:

```
thelocal.ch##div[id]:not([class]):matches-css(background-color: rgb(255, 238, 221))
```

**Comment by BlazDT** [comment]
Added rule for that sponsored element below an article.

**Comment by LucasDiTomase** [comment]
All sponsored ads have been fixed. Thanks people!

But the adblocker notice is still there

![63300526-cc591900-c2ae-11e9-8cd2-d23df5bc3d55](https://user-images.githubusercontent.com/46760897/63381965-1e15a800-c370-11e9-8b0d-175bb0c1edfd.png)

**Comment by LucasDiTomase** [comment]
These 2 rules hide it but leave the website unscrollable

thelocal.ch##.tp-modal
thelocal.ch##.tp-backdrop

**Comment by krystian3w** [comment]
`thelocal.ch#$#body.tp-modal-open { overflow: visible !important; }`

**Comment by krystian3w** [comment]
If possible, remove from own filters fixed sites.

**Comment by LucasDiTomase** [comment]
Fixed! Thanks :)

**Comment by BlazDT** [comment]
This is a paywall and we do not fix those.

**Comment by LucasDiTomase** [comment]
I didn´t know that. But still, the picture I posted was not that one. It was an adblocker notice.

**Comment by BlazDT** [comment]
If you click on link to become a subscriber (after getting adblock message) it tells you to pay, therefore sadly a paywall.

**Comment by krystian3w** [comment]
And add to report your activated filters list.
