### ISSUE TITLE
outlook.live.com

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardFilters#38880]
Hi. Some time ago I opened a bug about this ( #37327 ) and then I closed because I decided to block it manually. When I reported it, Alex-302 pointed out to me that there was a rule already to block this in the annoyances Adguard filter 

( this rule: outlook.live.com##div[aria-label="Navigation pane"][data-max-width] ~ div[class^="_3_"]:last-child )

and I verified that the rule was in my filters but it was not working for me. I think I just realized what was the cause.

I´m  using the spanish version of the website and the classes/labels seem to be different and that is the reason ( I think ) why "Navigation pane" is not working

![61717477-ab091980-ad50-11e9-9ea7-ad189f631aa5](https://user-images.githubusercontent.com/46760897/63291202-79289b80-c299-11e9-9fb5-cd332dba3817.png)

I managed to fix it with these 2 rules:

outlook.live.com##div.ms-Fabric._2HTFmaDIVHVbnIkwPM9srx.root-40 > div._3KAPMPOz8KsW24ooeUflK2:last-child > div._2jR8Yc0t2ByBbcz_HIGqZ4 > div._1TpU2KF6f_EeQiytBaYj8I:first-child > div._3_hHr3kfEhbNYRFM5YJxH9:last-child > div._23fxOotSm5HPNB1U_ZVw4i

outlook.live.com##div.ms-Fabric._2HTFmaDIVHVbnIkwPM9srx.root-40 > div._3KAPMPOz8KsW24ooeUflK2:last-child > div._2jR8Yc0t2ByBbcz_HIGqZ4 > div._1TpU2KF6f_EeQiytBaYj8I:first-child > div._3_hHr3kfEhbNYRFM5YJxH9:last-child

**Comment by krystian3w** [comment]
Maybe wait for implement `:xpath(..)`: https://github.com/AdguardTeam/ExtendedCss/issues/86 (maybe years waiting).

`outlook.live.com##a[href="https://windows.microsoft.com/outlook/ad-free-outlook"]:xpath(../../../..)`

**Comment by LucasDiTomase** [comment]
That rule ( outlook.live.com##a[href="https://windows.microsoft.com/outlook/ad-free-outlook"]:xpath(../../../..) ) is not working for me. But the 2 I posted are.

**Comment by krystian3w** [comment]
> Maybe **wait** for implement

https://github.com/AdguardTeam/ExtendedCss/issues/86 - still open and suppose no stared programing (addon / application).

---

other:

`outlook.live.com#?#div.ms-Fabric.root-40:not([id]) > div[class]:not([id]):last-child > div[class]:not([id]) > div[class]:not([id]):first-child > div[class]:not([id]):last-child:has(> div[class]:not([id]) > div[class]:not([id]) > span[class]:not([id]) > a[href="https://windows.microsoft.com/outlook/ad-free-outlook"]:not([class]):not([id]))`

**Comment by LucasDiTomase** [comment]
Sry, I thought you were posting that rule for me to try it :)

The last rule you posted 

( outlook.live.com#?#div.ms-Fabric.root-40:not([id]) > div[class]:not([id]):last-child > div[class]:not([id]) > div[class]:not([id]):first-child > div[class]:not([id]):last-child:has(> div[class]:not([id]) > div[class]:not([id]) > span[class]:not([id]) > a[href="https://windows.microsoft.com/outlook/ad-free-outlook"]:not([class]):not([id])) ) 

worked perfect but with a mini delay ( like I saw the bar for one sec and then it disappeared )

Thanks!

**Comment by krystian3w** [comment]
> I´m using the spanish version of the website and the classes/labels seem to be different and that is the reason ( I think ) why "Navigation pane" is not working

Or Alex still have old Layout (my account can not disable new layout, now maybe enough stable?).

**Comment by krystian3w** [comment]
`##div[aria-label="Panel de navegación"][data-max-width] ~ div[class^="_3"]:last-child`

> español (España, alfabetización internacional)

Maybe stable use only attrib name?

`##div[aria-label][data-max-width] ~ div[class^="_3"]:last-child`

**Comment by LucasDiTomase** [comment]
I confirm this rule also works ( in fact, it´s better. Cause there is no delay )

##div[aria-label][data-max-width] ~ div[class^="_3"]:last-child

Thanks again :)

**Comment by Alex-302** [comment]
duplicate

**Comment by Alex-302** [comment]
It is hidden by 
`outlook.live.com##div[aria-label="Navigation pane"][data-max-width] ~ div[class^="_3_"]:last-child`
