### ISSUE TITLE
Speedtest.net application - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3891]
Speedtest.net application - missed ad

<details>

![image2](https://cloud.githubusercontent.com/assets/23258533/21491329/876bcc0a-cc04-11e6-91f9-9837cbde98c9.png)

</details>

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21491332/9115ba5e-cc04-11e6-82bc-74acdac779fe.png)

</details>

<details>

Application version: 1.1.3.31
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: 3C8C6539-8D95-4FF2-8A49-87A62E39BC3C

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.78 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.76 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.88 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.24 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.69 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.92 Enabled=YES

</details>

Ticket ID:

**Comment by Alex-302** [comment]
not reproduced.
Try to clear DNS cache and restart this app.

**Comment by altokarev** [comment]
Reproduced on Android app.

<details><summary>Screenshot:</summary>

![screenshot_20170526-135754](https://cloud.githubusercontent.com/assets/28726429/26492210/bfd45fa2-421b-11e7-80d1-6916eb4fc2b7.png)

![screenshot_20170526-135823](https://cloud.githubusercontent.com/assets/28726429/26492214/c2a3e2d4-421b-11e7-9dee-2e8f634b3bb1.png)

</details>
<br>
***System configuration***

Information | value
--- | ---
Operating system: | Android
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On Default
Adguard DNS: | None 
Adguard filters: | 1, 2, 3, 4, 11, 14, 15

**Comment by Alex-302** [comment]
It is not a filter's issue. This app is clean on my devices, google ads are blocked.

**Comment by dzamyshlyayeva** [comment]
same issue on iOS here: 

![image](https://cloud.githubusercontent.com/assets/23372054/26524673/8acaa842-4343-11e7-94d4-e41d0ebfeac7.png)

Ticket ID 1545382

**Comment by Alex-302** [comment]
@dzamyshlyayeva I don't see the logs for this issue.

**Comment by dzamyshlyayeva** [comment]
asked for the logs

**Comment by veronikasav** [comment]
Logs
<details>

[com.adguard.AdguardPro.tunnel.gz](https://github.com/AdguardTeam/AdguardFilters/files/1036443/com.adguard.AdguardPro.tunnel.gz)
[com.adguard.AdguardPro.ActionExtension.gz](https://github.com/AdguardTeam/AdguardFilters/files/1036442/com.adguard.AdguardPro.ActionExtension.gz)
[filter.gz](https://github.com/AdguardTeam/AdguardFilters/files/1036440/filter.gz)
[com.adguard.AdguardPro.gz](https://github.com/AdguardTeam/AdguardFilters/files/1036441/com.adguard.AdguardPro.gz)

</details>

**Comment by Alex-302** [comment]
@veronikasav 
время бы уточнили. Там в логах гигантский промежуток времени охвачен, месяц почти.

**Comment by dzamyshlyayeva** [comment]
29. 05 around 6:37 and 6:38 am (France time)

**Comment by Alex-302** [comment]
@dzamyshlyayeva Which file?

**Comment by dzamyshlyayeva** [comment]
com.adguard.AdguardPro.tunnel.gz

**Comment by Alex-302** [comment]
I see invalid rules
```
2017/05/29 06:35:19:481  Error creating invalid rule: ||readms.net###mobile-reader-floating^
2017/05/29 06:35:19:481  Error creating invalid rule: ||mangastream.com###mobile-floating^
```
Please ask for removing them, and check again

**Comment by veronikasav** [comment]
Asked to remove and check again.
