### ISSUE TITLE
http://turktorrent.cc/ Unbloked Unvisible Ad

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardFilters#3892]
Hi
When you enter this website; then you click anywhere in the website, one ad page will open. But only first click.

Can you block that?

I use ENGLİSH,
SPYWARE,
SOCIAL MEDIA,
Annoyances,
Mobile Ads,
SAFARI,
TURKISH FILTERS.

**Comment by Alex-302** [comment]
Not reproduced.
Please fill template(always)

**Comment by tagataho** [comment]
@Alex-302 how can i do this?

**Comment by Alex-302** [comment]
@tagataho press green button and read proposed text:)

![image](http://i89.fastpic.ru/big/2017/0110/c9/763f632cdb916ee8209023e3f29281c9.jpg)
