### ISSUE TITLE
rae.es

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#38927]
https://enclave.rae.es/

![cookie](https://user-images.githubusercontent.com/35470489/63368281-f7e20f00-c353-11e9-8b69-7c5f5b71cf11.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by adranger** [comment]
This subdomain has a different cookie bar: [https://dle.rae.es/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://dle.rae.es/)

![cookie](https://user-images.githubusercontent.com/35470489/76789040-d25a9e00-679a-11ea-897c-d224a96da6af.png)

**Comment by Alex-302** [comment]
Fixed
