### ISSUE TITLE
dilo.de

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#38926]
https://www.dilo.de/index.php?id=55&L=5

![cookie](https://user-images.githubusercontent.com/35470489/63367947-4642de00-c353-11e9-9f79-4faa605bd63d.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by BlazDT** [comment]
Not enough visitors.

`dilo.de###cookieInformDialog`
