### ISSUE TITLE
domkino.tv/schedule - Incorrect Blocking

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#3894]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: при входе на сайт появляется коричневый прямоугольник.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](
![screen_shot_2016-12-28_at_08 56 00](https://cloud.githubusercontent.com/assets/22892774/21515829/b2b94cb6-ccdb-11e6-9f75-9b2b4ee71d38.png)
)
</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS
Browser: | Chrome
Adguard version: | 6.1.298.1564, 1.4.0
Adguard filters: | 1,2,3,4,5,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 818707

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Social filter
```
domkino.tv##.social-annoyer
```
