### ISSUE TITLE
http://www.songkick.com - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3895]
Incorrect blocking on page:
http://www.songkick.com/concerts/28793554-after-the-burial-at-grizzly-hall?utm_source=8123&concert=6jRTy88QcxGXJjJAzDDcdP&utm_content=cbe9381eb3de4a0c61fa16620bc1f6b6&utm_campaign=email20161227&utm_medium=partner

Trying to buy tickets to concert and when I click the link it says it is blocked by adblocker. After adding site to whitelist, the link to buy tickets is then blocked by a content blocker.

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21516163/7920bf86-ccde-11e6-88a3-145517929845.png)

</details>

<details>
Application version: 1.1.2.57
Application lifetime: 2016-09-06 04:36:23 +0000

Device: iPhone
Platform: iOS
OS: 10.0.2
ID: D17F3D8E-2DD2-4388-94C3-8A63B1344E4B

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.92 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.84 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.97 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.34 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.43 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.97 Enabled=YES
ID=101 Name="EasyList" Version=1.0.65.85 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.71.64 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.65.88 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.66.7 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.71.66 Enabled=YES

</details>

Ticket ID(if exists): 1476864

**Comment by Alex-302** [comment]
@osavranska на какой странице он кнопку нажимает?
Мне нужны адрес и скрин той страницы с кнопкой.

**Comment by osavranska** [comment]
<details>

![slack for ios upload](https://cloud.githubusercontent.com/assets/23258533/21541802/0d4c8346-cdc2-11e6-9d46-a5ae344e0522.jpg)

</details>

http://www.songkick.com/concerts/28793554-after-the-burial-at-grizzly-hall?utm_source=8123&concert=6jRTy88QcxGXJjJAzDDcdP&utm_content=cbe9381eb3de4a0c61fa16620bc1f6b6&utm_campaign=email20161227&utm_medium=partner 
Если на этой странице нажать buy tickets, переходит на http://www.songkick.com/tickets/22398489?p=8123 с проблемой

**Comment by Alex-302** [comment]
Ещё вопрос - фильтрация DNS у него же выключена? У меня только с ней повторяется.
