### ISSUE TITLE
picjumbo.com - No Assistant

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#3896]
Screenshot: http://prnt.sc/dotboo

**Filters**: 1,2,3,4,5,14
**Browser**: Chrome
**OS**: Windows, Mac

User filter is clear.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1476250

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't fix it.
Opened in Windows repository:
https://github.com/AdguardTeam/AdguardForWindows/issues/1462
