### ISSUE TITLE
antonioli.eu

### ISSUE THREAD

**Issue by ao-ku** [AdguardTeam/AdguardFilters#38969]
The website does not load with adblock on, not even the assistant is displayed.
If turned off, it loads normally.
![Screenshot 2019-08-21 at 15 30 15](https://user-images.githubusercontent.com/10236930/63436234-9d66b280-c428-11e9-9406-52cfd6256ef5.png)

macosx / safari (latest version)

**Comment by BlazDT** [comment]
Fixed title. not reproduced.
Please provide required information as outlined in the template, thank you.

**Comment by krystian3w** [comment]
@seba2282 masz to u siebie, że biała strona?

**Comment by seba2282** [comment]
![Screenshot_2019-08-21-18-43-06](https://user-images.githubusercontent.com/16944478/63451033-98fbc300-c443-11e9-9b30-59c6d43bf5a8.png)

Na Android. Ale nie wiem jak pc edge

**Comment by seba2282** [comment]
![zrzut](https://user-images.githubusercontent.com/16944478/63453356-c7c86800-c448-11e9-91bb-bf77cbb4e1ef.png)

PC Microsoft Edge (EdgeHtml) Adguard Extension i spora ilość filtrów (@krystian3w wie :) ) 
i zero problemów.

**Comment by krystian3w** [comment]
So broken on only macOS or with `problematic` filter lists activaded (ABP Japanese and other).

**Comment by seba2282** [comment]
I try turn them and look, maybe autor need inactive that filter.

**Comment by seba2282** [comment]
ABP Japanese any problem on that site. :)

**Comment by Alex-302** [comment]
just free domain

**Comment by BlazDT** [comment]
Strange, it did not accept change of thread title. But now.

**Comment by ao-ku** [comment]
it’s antonioli.eu not antonioni

**Comment by seba2282** [comment]
You have turned off ABP Japanese and all filters with tagged obsolete and problematic?

**Comment by ao-ku** [comment]
yes, I tried turning everything off including the default ones. Also the site keeps reloading.

**Comment by seba2282** [comment]
I try after few moment look on that site, because I am without home. And better look for me, when I have connect with wifi. 🙂

**Comment by ao-ku** [comment]
-viewing source code: no code displayed, only when the page starts reloading there is  code shown for a second, I managed to grab a screenshot with a screen recording but it does not show much to me
![Screenshot 2019-08-22 at 09 46 50](https://user-images.githubusercontent.com/10236930/63496251-d737c780-c4c1-11e9-89d1-42309068c062.png)

-can click back in the browser for every reload on the site
-same machine but chrome works without any issues

**Comment by ao-ku** [comment]
sorry about the wrong formatting and missing info, GitHub is very confusing for me (even after watching tutorial)

**Comment by seba2282** [comment]
![Screenshot_2019-08-22-10-13-41](https://user-images.githubusercontent.com/16944478/63498151-96da4880-c4c5-11e9-9c84-f6cff405ab49.png)

Works normal. Only closed windows about few personal data write (country, etc)
@BlazDT, can you check that depth?

**Comment by BlazDT** [comment]
I do not have a Mac and on iPhone/Windows/Android it is clean.

**Comment by seba2282** [comment]
Maybe safari has problem, not macos?

**Comment by krystian3w** [comment]
@slavaleleka have macOS? or @AdamWr have iPhone?

**Comment by Alex-302** [comment]
@ao-ku please send report from AdGuard. We don't know even which AdGuard you are using, and filters.

**Comment by slavaleleka** [comment]
I have reproduced it in Safari with AdGuard for MacOS. seems like a bug and only HTTPS filtering exclusion for antonioli.eu helps

@ao-ku as a temporary solution of the problem you should do it: 
1. https://uploads.adguard.com/slbdzd8lu5rh7.png
2. https://uploads.adguard.com/slbdzd8l5v7kb.png
3. https://uploads.adguard.com/slbdzd8lkqqi0.png
4. Enter `antonioli.eu` and press `Enter`

**Comment by ao-ku** [comment]
yes that works, thanks! Logs attached.
[adguard_logs_20190822121520.zip](https://github.com/AdguardTeam/AdguardFilters/files/3530048/adguard_logs_20190822121520.zip)

**Comment by Alex-302** [comment]
I don't see `antonioli.eu`  in the log. Only added HTTPS exclusion.

**Comment by seba2282** [comment]
For me that site works with https filtering, so seriously it is temporary fix problem, what said @slavaleleka. I still guess problem is with filters Adguard on safari or https is incorrect filtering for safari. Maybe in that way look need?

**Comment by slavaleleka** [comment]
[the bug is reported](https://github.com/AdguardTeam/CoreLibs/issues/1097)
