### ISSUE TITLE
http://m.apotheken-umschau.de - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3897]
http://m.apotheken-umschau.de/Verhuetung/Notfallverhuetung-Pille-danach-226177.html - incorrect blocking

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/21521567/e0161966-cd06-11e6-9123-3c468a2e691b.png)

</details>

<details>

![image2](https://cloud.githubusercontent.com/assets/23258533/21521575/f37365cc-cd06-11e6-85c4-e5b1d5af521e.png)

</details>

<details>
Application version: 1.1.2.57
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: C3C7FD0D-99C7-4F35-A8E5-BE3CB64A158F

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.92 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.47 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.32 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.63 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.13 Enabled=NO
ID=6 Name="German filter" Version=1.0.29.20 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.19 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.82 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.37 Enabled=YES

</details>

Ticket ID: 1476857

**Comment by danidoedel** [comment]
Same as #3824

**Comment by Alex-302** [comment]
@danidoedel could you connect your device to PC, then open `chrome://inspect/#devices` in Chrome?
You will see something like this
http://imagizer.imageshack.com/img922/4148/WqInFJ.jpg
