### ISSUE TITLE
medium.com

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardFilters#38988]
medium.com##div:contains(Read to your)

![Captura de Pantalla 2019-08-21 a la(s) 14 22 05](https://user-images.githubusercontent.com/46760897/63453485-25e05580-c41f-11e9-85c9-6005fd74b54e.png)

**Comment by krystian3w** [comment]
Danger. Can cut all div on site with `Read to your`.

**Comment by LucasDiTomase** [comment]
Ok. I modify it to medium.com##div:contains(Read to your mind’s desire) then

**Comment by Alex-302** [comment]
They change that text. Better leave it.
