### ISSUE TITLE
www.amazon.com - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3898]
The [link](https://www.amazon.com/gp/f.html?C=BO2ZZ2TZDRG8&R=22BKN6789IQEN&T=C&U=https%3A%2F%2Ffls-na.amazon.com%2F1%2Fgc-core-nab%2F1%2FRW%3BaHR0cHM6Ly9lZ2lmdC5hY3RpdmF0aW9uc3BvdC5jb20vP3RpZD1ZSzFQSEgxRFg5N0QxUzFaOUhRUjg0N1A3QyZndz1uJmdzPW4mZ2NtPW4mZWlkPTA4MTdNMVpCUUdEVjNGSkJSMTBNSEY3U1cw%2F%3Fsn%3D1539307231229530%26lf%3D7SW0%26ref_%3Dpe_1870990_140900700&A=7T9LHY06ADLLH8ZTTSAHH4EGGXSA&H=KQAHHRH74P5XMNG7CJEXZZXUZAMA&ref_=pe_1870990_140900700)

![image2](https://cloud.githubusercontent.com/assets/15856304/21524461/dad8e7a4-cd1e-11e6-809e-9b5d188f55c2.png)

<details>

Application version: 1.1.1.54
Application lifetime: 2016-09-17 03:18:01 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: A1D768FC-6FBB-42AB-85E2-463F9F663300

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.97.47 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.16 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.60 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.5.32 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.5.24 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.52 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.63.83 Enabled=YES

**Comment by Alex-302** [comment]
Please check:
```
@@||fls-na.amazon.com^
```

**Comment by Alex-302** [comment]
It works:)
Added.
