### ISSUE TITLE
pilot.wp.pl 

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#38989]
Windows 10 1903, Microsoft Edge (EdgeHTML)

site: pilot.wp.pl 
cookies/rodo not blocking 

![pilot](https://user-images.githubusercontent.com/16944478/63454570-5e962400-c44b-11e9-9908-b4ae281403e2.png)

**Comment by krystian3w** [comment]
Problemy z skryptem nie rozwiązane na poziomie dodatku lub coś się zmieniło w 22 dni:

https://github.com/AdguardTeam/AdguardFilters/issues/37642

**Comment by seba2282** [comment]
Szkoda. Ale widzę, że i google zaczęło znowu sypać promo chrome. Możliwe faktycznie skopane skrypty na poziomie dodatku. :)
