### ISSUE TITLE
www.gyldendal.dk parental control false positive

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardFilters#38990]
Can this website be deleted from parental control? Thank you.

https://www.gyldendal.dk/

**Comment by krystian3w** [comment]
Blocked by AdGuard Home or AdGuard Child DNS version?

**Comment by worldsdream** [comment]
Blocked by AdGuard sensitivy level: 3 years 

I updated my filters and it seems to work fine. Can you confirm?

**Comment by Chinaski1** [comment]
This site is not in the adult category.
Please check again and send the screenshot.
