### ISSUE TITLE
The DNS filtering blocks МТС Connect iOS app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3899]
Включённый DNS фильтр блокирует работу приложения МТС connect http://www.mts.ru/connect/
https://itunes.apple.com/ru/app/mts-connect/id1046883922?mt=8

logs: 1382035

**Comment by Alex-302** [comment]
В логе ничего нужного.
Можно в самом Адгарде включить лог запросов DNS.
Сперва нужно закрыть эту прогу, вкл/выкл режим полёта и подождать пол минуты(чтоб ненужных запросов в логе было меньше). Потом включить лог и запустить приложение. После возникновения проблемы перейти в Адгард и если открыт журнал потянуть список вниз секунд через 10(домены туда с задержкой выводятся), чтоб он обновился(либо выйти в меню и снова зайти в журнал).
Затем сделать скрин(ы)

**Comment by jesusc31** [comment]
Блин я думал если они логируются то в отсылку добавляются. Ок сделаю скрины утром

**Comment by Alex-302** [comment]
@jesusc31 в файл добавляются, но он может быть довольно большим. Если не знать точного времени(его нужно указывать), поиски могут ни к чему не привести. В самой программе гораздо удобнее, и разблокировать нужный домен можно, даже если заблокирован с помощью ДНС.

**Comment by jesusc31** [comment]
![img_0806](https://cloud.githubusercontent.com/assets/12476170/21709646/a40ee800-d3f3-11e6-9f19-974ae29d96a2.PNG)
@Alex-302 привет! Похоже оно. Больше запросов не вижу

**Comment by Alex-302** [comment]
Нет. Если предлагает добавить в чёрный список, значит не заблокирован.
Давайте логи с указанием времени возникновения ошибки.

**Comment by jesusc31** [comment]
Отправил лог со скриншотом запросов днс в по почте. Время 15:48

**Comment by Alex-302** [comment]
а номер заявки?

**Comment by jesusc31** [comment]
1382035

**Comment by Alex-302** [comment]
Как и на скрине, вижу только два заблокированных домена.
Попробуйте добавить в белый список:
```
e.crashlytics.com
settings.crashlytics.com
```
Если поможет - удалите второе. Появится проблема - добавьте второе, а первое удалите. Это чтоб лишнего не исключать. Возможно исключение одного домена не поможет.

**Comment by jesusc31** [comment]
Не помогло

**Comment by Alex-302** [comment]
Из-за кэша DNS наверное не всё заблокированное видно.
Смахните приложение, вкл/выкл режим полёта, подождите минуту и повторите попытку. Только перед запуском приложения нужно очистить журнал от старых записей.

**Comment by jesusc31** [comment]
То же самое

**Comment by Alex-302** [comment]
тогда выход один - выключите все фильтры(быстрее будут добавляться исключения) и добавляйте все заблокированные домены в белый список. При этом лучше не пользоваться браузером. А там уже посмотрим.

**Comment by jesusc31** [comment]
Вот такого вида хосты events-endpoint-b-1623273513.us-east-1.elb.amazonaws.com
Внёс две штуки в белый список. Не помогло. Они появляются после того, как crashlytics в белый список вносишь.

**Comment by jesusc31** [comment]
Я думаю, тему можно закрывать: приложение просто тупо не хочет работать через с включённым vpn. Проверил на TunnelBear

**Comment by Alex-302** [comment]
@vozersky можешь у себя проверить? У меня другой МТС, залогиниться не даст.

**Comment by vozersky** [comment]
@Alex-302 
повторяется
блокируются те же самые домены:

```
e.crashlytics.com
settings.crashlytics.com
```

**Comment by Alex-302** [comment]
Тогда здесь закрываю.
