### ISSUE TITLE
[iOS] www.bild.de - anti adblock script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#3900]
![](http://i.imgur.com/NHDhwit.png)
http://www.bild.de

**Adguard version**: 1.1.2

**Operating system**: iOS

**Browser**: Safari

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/2604

**Comment by Alex-302** [comment]
Will be fixed in the next build
https://github.com/AdguardTeam/AdguardForiOS/issues/316

**Comment by Vincent-Michael** [comment]
@Alex-302
still broken on version 1.1.5

**Comment by Alex-302** [comment]
@Vincent-Michael 
which filters? Is DNS filtering enabled?

**Comment by Alex-302** [comment]
try to disable safari filter and VPN, and add
```
@@||bild.de^$elemhide
```
