### ISSUE TITLE
Adguard is reportedly blocking Spotify app on iOS

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3901]
Since today iOS Spotify can't connect anymore to the Internet with DNS activated on Default or Family Protection. 

Logs: 1021351

<details>

Application version: 1.1.3.31
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: D8C68A2E-052A-4588-A77A-CBB66B4E48CF

Locale: en
Region: fr

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.96 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.84 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.13.22 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.8.36 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.40 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.44 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.97 Enabled=YES
ID=101 Name="EasyList" Version=1.0.65.87 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.71.65 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.65.45 Enabled=NO
ID=113 Name="Liste FR" Version=1.0.71.85 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.64 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.71.81 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.67 Enabled=NO
ID=210 Name="Spam404" Version=1.0.1.65 Enabled=YES

**Comment by Alex-302** [comment]
@evgeniy-ADG 
try 
```
||spclient.wg.spotify.com^
```
