### ISSUE TITLE
gidonline.club 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3902]
***Description***: When you click on the background (margins) of this website it automatically opens vk group page. 
http://gidonline.club/ 

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | "BlockThirdPartyCookies": true, "BlockThirdPartyCookiesPeriodMin": 30,  "BlockFirstPartyCookies": false,  "BlockFirstPartyCookiesMin": 2880,  "DisableThirdPartyCache": true,  "BlockWebRtc": true,  "BlockBrowserPushApi": false, "BlockBrowserLocationApi": true, "RemoveXClientDataHeader": true,  "HideSearchQueries": true,  "SendDoNotTrackHeader": true,  "RemoveRefererFromThirdPartyRequests": false,  "HideUserAgent": false,  "CustomUserAgent": null,  "CustomReferer": null,  "HideIp": true, "CustomIp": "209.141.53.254"
Adguard filters: | English, Spyware, German, Dutch, unblocking useful ads. (Reproduced with basic ones on Mac)

Ticket ID(if exists): 1067832

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
gidonline.club###brdiml
```
