### ISSUE TITLE
4pda.ru - Adguard brakes QMS messages on the site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3903]
Здравствуйте, с сегодняшнего дня данные правила в русском фильтре ломают окно ввода нового сообщения, оно исчезает. Скорее всего на форуме что-то поменяли, прошу обновить правила под сделанные правки на форуме.

Ломает окно ввода здесь: http://4pda.ru/forum/index.php?act=qms (необходима авторизация)

Правила(ломают оба правила):
||s.4pda.to/*.js$replace=/\w\.\w+&&\w\.\w+\(\w\,\w\)[\s\S]+\w\(\)\}\)/}})/
||s.4pda.to/*.js$replace=/\w\.\w+&&\w\.\w+\(\w\,\w\)[\s\S]+\w\(\)\}\)/}})/,important

**Comment by Alex-302** [comment]
этих правил уже нет
