### ISSUE TITLE
geeklogger.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#39046]
https://romdb.geeklogger.com/

![cookie](https://user-images.githubusercontent.com/35470489/63537486-39a5bd80-c4ec-11e9-9c3a-22a0477d42f9.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by krystian3w** [comment]
```
##.eu-cookie-compliance-banner-info
##.eu-cookie-compliance-banner
###sliding-popup
##.sliding-popup-top

```

**Comment by PixelGordo** [comment]
So, I had to install an unwanted plugin just to comply with EU laws (apparently) and now people are trying to remove its result? What a marvelos the modern internet is :D

Regards

(the recent referrers log brought me here)

**Comment by adranger** [comment]
^ @Alex-302 This is why I had been posting non-clickable links.

**Comment by krystian3w** [comment]
What help my smart referer? I see same site...

Olny Wirtualna Polska (.pl) change pop-up with GDPR / privacy policy moddify if popular list block our pop-up.

**Comment by krystian3w** [comment]
If @PixelGordo is webmaster on this site, you may add more generic class / ID.

https://filters.adtidy.org/extension/ublock/filters/14.txt

Example:
```
##.cookie-hint
###cookies-alert
```

**Comment by krystian3w** [comment]
Also you  can paste before from link:

https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=

**Comment by PixelGordo** [comment]
The drupal module is EU Cookie Compliance. You can contact the authors here to see if they can apply the changes you suggest.

https://www.drupal.org/project/eu_cookie_compliance

Regards

**Comment by Alex-302** [comment]
@adranger 
> This is why I had been posting non-clickable links. I've stopped doing that [per your request](https://github.com/AdguardTeam/AdguardFilters/issues/38720#issuecomment-523045292), but site owners might come here and then circumvent your rules.

Use reporting tool, and links will be anonymized.

**Comment by krystian3w** [comment]
**gorhill** no added nowhere link to: 

https://reports.adguard.com/em/new_issue.html
