### ISSUE TITLE
https://www.change.org - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3906]
Некорректная блокировка на странице:
https://www.change.org/p/%D0%B3%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F-%D0%BD%D0%B0%D0%B3%D1%80%D0%B0%D0%B4%D0%B0-%D0%B8%D0%BC%D0%B5%D0%BD%D0%B8-%D0%B5%D0%BB%D0%B8%D0%B7%D0%B0%D0%B2%D0%B5%D1%82%D1%8B-%D0%B3%D0%BB%D0%B8%D0%BD%D0%BA%D0%B8/share?utm_source=action_alert_sign&utm_medium=email&utm_campaign=694157&alert_id=xpUBWEUTRD_s3LPpQdcb0in0RpXBVY5SOFDB745rJwWSh1wmKkFIFs%3D

<details>

![image3](https://cloud.githubusercontent.com/assets/23258533/21538091/eda59d5e-cda1-11e6-9499-f70e25cbb789.png)

</details>

<details>

![image2 1](https://cloud.githubusercontent.com/assets/23258533/21538437/bf88dac2-cda5-11e6-9d37-fa64b8f4493f.png)

</details>

<details>

![image1 2](https://cloud.githubusercontent.com/assets/23258533/21538450/d639b106-cda5-11e6-8c5a-edb3cc94fd10.png)

</details>

<details>

Application version: 1.1.3.31
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 00F9FEB2-3BE5-4E86-825C-F8870F429613

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.84 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.79 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.92 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.29 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.79 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.96 Enabled=YES

</details>

Ticket ID(if exists): 1474788

**Comment by Alex-302** [comment]
Не повторилось. 
Спроси, что блокирует - DNS или какой-то фильтр?
