### ISSUE TITLE
Hill Climb Racing 2 -  Yandex Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#3907]
Реклама Яндекса в приложении Hill Climb Racing 2
http://prnt.sc/dp77dt

Полноэкранная, запускается в приложении после прохождения какого-либо этапа.

**Filters:** 2, 3, 14, 10, 1, 11, 211
**FilteringQuality:** FULL
**Android** 2.8.76
**Https filtering** on

[debug (5).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/676779/debug.5.txt)

Время: 23:59 - 00:06

User ID: 1065108

**Comment by Alex-302** [comment]
Какой режим фильтрации?

**Comment by Yana-SUP** [comment]
Чистил, у нас не повторилось

Юзер написал "правда теперь, после чистки всей системы от мусора и прочего, сама реклама уже не показывается, а только заставка "рекламная пауза" (как на скриншоте)" http://prnt.sc/dp77dt

Режим - Качественный

**Comment by Alex-302** [comment]
> Режим - Качественный

это алгоритм. Режим - VPN или прокси(ручной/автоматический)

**Comment by Yana-SUP** [comment]
прошу прощения, VPN
