### ISSUE TITLE
anwap.org

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3908]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: При переходе на страницу http://anwap.org/films/new_year
Не отображаются ссылки на фильмы

"Помогает отключение фильтра Мобильной рекламы"

Лог 10-14 только с фильтром мобильной рекламы
https://drive.google.com/open?id=0B5dP1M24mheOdGFpQUM1MUs2cGM

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21539373/157a09ca-cdaf-11e6-8f03-83e27dc7ffc3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Хром
Adguard version: | 2.8.76
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard filters: | 1,2,3,4,11,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1426828

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
поправил

**Comment by evgeniy-ADG** [comment]
![image](https://cloud.githubusercontent.com/assets/15856304/24693890/6aea57e0-19e8-11e7-99a8-20def3eff904.png)

**Comment by Alex-302** [comment]
пусть проверит обновления, должно пропасть.
