### ISSUE TITLE
https://tengrinews.kz/ - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3910]
https://tengrinews.kz/ - missed ad
Banner at the top of the page (КазМунайГаз).

<details>

![image1 4](https://cloud.githubusercontent.com/assets/23258533/21543503/aaa6f5a6-cdcf-11e6-98b8-7144ca2c3b42.png)

</details>

<details>

Application version: 1.1.2.57
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 8E4EA5B1-5A2E-455D-A42D-EEABD4FE3A5C

Locale: ru
Region: kz

Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.96 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.84 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.36 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.83 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.44 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.97 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.51 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.68.66 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.68.35 Enabled=YES

</details>

Ticket ID(if exists): 1477730

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
tengrinews.kz###kmg_slider
```
