### ISSUE TITLE
Angry birds fight - ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3911]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:  в приложение angry birds fight через пару уровней появляется реклама.
https://play.google.com/store/apps/details?id=com.rovio.angrybirdsfight&hl=ru

Можно ее убрать?

Лог 
[debug (13).txt](https://github.com/AdguardTeam/AdguardFilters/files/677045/debug.13.txt)
время появления рекламы 10-43

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21543673/53413aea-cdd1-11e6-9039-210ce731ae65.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21543674/5794000a-cdd1-11e6-9a27-5b97098857ca.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.8.76
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard filters: | [ 2, 3, 4, 1, 11 ]

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1476128

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня ролики другие, про саму игру.
На пробу:
```
||unityads.unity3d.com^
```

**Comment by Tetiana2020** [comment]
@Alex-302 не помогло

**Comment by Alex-302** [comment]
Ролики с их основного домена грузятся.
В пользовательский фильтр:
```
||cloud.rovio.com^
```

**Comment by Tetiana2020** [comment]
@Alex-302 так не грузится игра.

**Comment by Alex-302** [comment]
Тогда без вариантов(но у меня запускается и работает без роликов). Блокировка остальных доменов ни к чему не привела.
