### ISSUE TITLE
http://www.auto-motor-und-sport.de/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3912]
http://www.auto-motor-und-sport.de/

![image1](https://cloud.githubusercontent.com/assets/15856304/21546200/c30fe8f8-cde5-11e6-8c9e-fa542d668897.PNG)

<details>

Application version: 1.1.3.31
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: 60310F67-4E2C-4DF7-B3D6-4C33E45D31C2

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.82 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.79 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.92 Enabled=YES
ID=6 Name="German filter" Version=1.0.29.62 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.40 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.96 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.49 Enabled=YES
ID=101 Name="EasyList" Version=1.0.65.85 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.71.55 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.61.6 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.71.69 Enabled=YES

**Comment by Alex-302** [comment]
I can't reproduce with this filter list.
> Optimazed enabled: NO
> Filters subscriptions:

Total rules number is over 50k. 

 It causes adblock detection in articles on my side. Try to disable these filters.
```
ID=101 Name="EasyList" Version=1.0.65.85 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.61.6 Enabled=YES
```

**Comment by evgeniy-ADG** [comment]
sponsored content у меня с 41000 правил не блокиурется. 
но баннера сверху - нет.

**Comment by Alex-302** [comment]
Сверху и справа у меня чисто. Нужно чтоб без тех двух фильтров юзер проверил.
Sponsored уберу, для них просто правил нет.

**Comment by Alex-302** [comment]
Added to German filter
```
auto-motor-und-sport.de##a[href^="http://www.leserumfragen.de/ams/"]
auto-motor-und-sport.de##body > .v-A_-wrapper--stroer > .j.t div[class="teaser t"][-ext-has="span.v-A_-headline:contains(Sponsored)"]
```

**Comment by osavranska** [comment]
He disabled those filters, but the problem still persists.

**Comment by Alex-302** [comment]
Strange. User can try to disable, then enable simplified(optimized) filters again.
