### ISSUE TITLE
pornwhite.com [NSFW] [Pop-up] [Ad Text Strings]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#39135]
**Site**: https://www.pornwhite.com/videos/1401118/hard-interracial-anal-sex-with-beautiful-blonde-mature/

**Issue**: Please remove the Ad text strings, empty ad boxes and pop-ups from the page.

**Screenshot**: http://prntscr.com/owuilh

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 76.0.3809.100 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 3.2.1	 `

**Filters**:
```
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404
NoCoin Filter List

```

**Stealth Mode Settings**:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled (Default)

**Comment by Nzzyme** [comment]
https://www.pornwhite.com/videos/795220/casey-calvert-anal-fascination-with-bbc/

Seeing empty ad banner box over video player after the video is completed

http://prntscr.com/poo0jn

**Comment by Alex-302** [comment]
Not reproduced.

**Comment by zloyden** [comment]
I was able to reproduce it. Fixed, update should be available in 1-2 hours.
