### ISSUE TITLE
[iOS] khabar.ndtv.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#3914]
http://khabar.ndtv.com/news/world/explosion-rocks-syrias-aleppo-as-residents-return-1641457
**$generichide** rule is not working.
Added to user filter:
```
##img
@@||khabar.ndtv.com^$generichide
```
but ##img is still hidden.
Eng filter contains `@@||ndtv.com^$generichide` but it also doesn't help.

Forum thread:
https://forum.adguard.com/index.php?threads/ndtv-com-anti-adb-ios.18066/#post-119932

**Comment by Alex-302** [comment]
The same issue with bild.de
Exclusions are not working
```
@@||bild.de^$elemhide,urlblock
```
or
```
@@||bild.de^$elemhide,urlblock,important
```

**Comment by ameshkov** [comment]
Relevant issue:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/507

**Comment by Alex-302** [comment]
another one
https://github.com/AdguardTeam/AdguardFilters/issues/3934
