### ISSUE TITLE
http://extra.to/torrent/ - ads, social media buttons

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3915]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
http://extra.to/torrent/5374655/Ant+Download+Manager+PRO+1.2.4+Build+35871+%2B+Patch+%5BSadeemPC%5D.html

* **Current behaviour**:  the banner missed at the top of the page, sm buttons at the bottom

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21548986/1fd251a4-cdf8-11e6-86ef-d82f2c14a6ef.png)

and

![image](https://cloud.githubusercontent.com/assets/15856304/21548993/29111da4-cdf8-11e6-9807-53b40de2e9a6.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | the latest chrome
Adguard version: | 6.1.298
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | no
Adguard filters: | eng, ru, social media, annoyances, spyware

Ticket ID(if exists): 1240891

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
extra.to##div[align="center"] > a[rel="nofollow"] > img
```
Social buttons are part of message. Can be blocked by assistant.

**Comment by evgeniy-ADG** [comment]
https://extra4-to.unblocked.lol/ - click the first link, there's a pop-up

![image](https://cloud.githubusercontent.com/assets/15856304/24835736/6f35e45e-1d12-11e7-8f0b-13115a173eac.png)

Russian, English, Safari, Annoyances, Spyware, Social media filters.

**Comment by Alex-302** [comment]
Fixed
