### ISSUE TITLE
spaces.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3916]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: the standard spaces.ru banner on the bottom of the page
http://spaces.ru/shared_zone/?link_id=260044

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image1 1](https://cloud.githubusercontent.com/assets/15856304/21553490/37db96c0-ce11-11e6-8385-017ec9722d80.PNG)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.3.31
Simplified filters(iOS) | Optimazed enabled: NO
Adguard DNS: | Default
Adguard filters: |

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.4.8 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.90 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.4 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.42 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.91 Enabled=YES
ID=6 Name="German filter" Version=1.0.29.73 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.93.3 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.9.13 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.47 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.5.60 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1477963

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Должны быть скрыты. Передобавил.
Нужно чтоб юзер проверил и отписался(минимум через два часа).

**Comment by osavranska** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/3950

**Comment by Alex-302** [comment]
завтра нужно проверить. Добавил одно правило.
