### ISSUE TITLE
e2Remote Lite app - Missed ads

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3917]
***Description***: Missed ads in the app e2Remote Lite on iOS.

Screenshot:
<details>

![image1](https://cloud.githubusercontent.com/assets/17504743/21556535/f4b43668-ce29-11e6-82f7-94a5e6df779f.PNG)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2
Adguard version: | 1.1.3.31
Adguard filters: | User filter, English filter, Spyware filter, Social media filter, Annoyances filter, Russian filter, Safari filter

Ticket ID(if exists): 1474788

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
We can't block facebook ads in apps on iOS.
If user is not using Facebook, he can add this rule to user-filter
```
||graph.facebook.com^
```
