### ISSUE TITLE
4players.de - Anti Adblock Script - iOS

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3919]
***Site***: http://www.4players.de/
***Description***: Site detects Adguard on iOS device.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21558063/cd36c83e-ce34-11e6-81bc-2aa4b320b86b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Browser: | Safari
Adguard version: | 1.1.3
Simplified filters(iOS) | Off
Adguard DNS: | None

Adguard filter | Version
--- | ---
English filter | 1.1.4.17
Spyware filter | 1.0.9.93
Social media filter | 1.0.16.8
Annoyances filter | 1.0.8.44
German filter | 1.0.29.78
Mobile ads filter | 1.0.6.48
Safari filter | 1.0.1.98

**Comment by Alex-302** [comment]
Not reproduced on my iPad. Try to enable simplified(optimized) filters.

**Comment by danidoedel** [comment]
@Alex-302 Maybe this helps to fix the issue (not sure if you need that info, but the div containing the message has the id 2145416769, changes every time you load the site):
[HAR.zip](https://github.com/AdguardTeam/AdguardFilters/files/978616/HAR.zip)

**Comment by Alex-302** [comment]
Still can't reproduce on iPad.
Try to block these images
http://static1.fore.4pcdn.de/sourcen/portal/icons/pur/960x640_01.jpg
http://static2.fore.4pcdn.de/sourcen/portal/icons/pur/960x640_02.jpg
http://static1.fore.4pcdn.de/sourcen/portal/icons/pur/960x640_03.jpg
