### ISSUE TITLE
m.dwdl.de - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3920]
***Site***: http://m.dwdl.de/a/59342
***Description***: Ad leftover on mobile. Social widget.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21558126/73fded78-ce35-11e6-95be-ee1057abca41.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21558112/5c0e9186-ce35-11e6-8498-ef734be51372.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.4.17
Spyware filter | 1.0.9.93
Social media filter | 1.0.16.8
Annoyances filter | 1.0.8.44
German filter | 1.0.29.78
Mobile ads filter | 1.0.6.48
Safari filter | 1.0.1.98

**Comment by Alex-302** [comment]
fixed
