### ISSUE TITLE
yandex.ru -  Annoyance & m.vk.com - ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3923]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Adguard Content Blocker
+ Banner in yandex search

+ can we block this: http://prntscr.com/dpnbcm ?

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21563106/04f8db02-ce87-11e6-8138-1db43c1d50b7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |Android 
Browser: | Yandex
Adguard version: | 1.4.1
Adguard filters: | 1,2,3,4,14,11

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1050245

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
No, it is impossible to hide these ads with Content Blocker.
