### ISSUE TITLE
investing.com - Incorrect Blocking 

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3924]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
investing.com 
search does not work on the site
**It should be checked in the normal Chrome tab, not private**

**Helps disabling English filter**

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21564958/9d94bed6-ce9a-11e6-8d86-0fe130537357.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard filters: | 1, 2,3,4,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1273225

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced
http://imagizer.imageshack.com/img924/8420/3hQNVA.png
Try one by one
```
@@||investing.com^$urlblock
```
**or**
```
@@||investing.com^$content
```
**or**
```
@@||investing.com^$jsinject
```

**Comment by vgavrish** [comment]
now search is working

**Comment by vgavrish** [comment]
> эти правила сработали в пользовательском фильтре
@@||investing.com^$urlblock
@@||investing.com^$content

**Comment by Alex-302** [comment]
Уже что-то. Теперь можно попросить сделать следующее:
- добавить(оставить)
```
@@||investing.com^$content
```
- включить только англ фильтр
- открыть журнал и отметить чекбокс, чтоб показывало заблокированное
- обновить вкладку
- выслать скрин журнала
Либо удалённо можно глянуть(через пару дней)

**Comment by vgavrish** [comment]
ок, попрошу сначала сделать
