### ISSUE TITLE
www.msn.com - Slow Loading

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#3925]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: slow video loading when Adguard is enabled

Reproducible. I used "Inspect" > "Network" in Chrome, here are my screenshots

Enable Adguard ≈ 35-40 seconds for loading
http://prnt.sc/dpp0kl

Disable Adguard ≈ 5 seconds
http://prnt.sc/dpp18h

***Steps to reproduce the problem***:

Use this link, for example:
https://www.msn.com/en-us/video/watch/boss-thanks-800-employees-by-taking-them-on-caribbean-cruise/vi-BBxCtAW

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Chrome
Adguard version: | 1.4.0
Adguard filters: | 1,2,3,4,5,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1056631

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproducedOn my side - with AG less ther 3-4 seconds:
<details>

![image](http://imagizer.imageshack.com/img923/5238/mv0MiZ.png)
</details>
with extension only - 2.5-3.5 seconds
<details>

![image](http://imagizer.imageshack.com/img923/4057/6lyteS.png)
</details>
without AG - near 3-4 seconds
<details>

![image](http://imagizer.imageshack.com/img923/4057/6lyteS.png)
</details>

**Comment by Alex-302** [comment]
@Yana-SUP can you check it? I don't have macos at the moment.

**Comment by vgavrish** [comment]
i have the same in Win with extension and program
i can to give remote access
AG Program- 25-30 sec
<details>

![screenshot_4](https://cloud.githubusercontent.com/assets/18548949/21587070/d7a9664c-d0e0-11e6-9a16-eaa602dd3450.jpg)

</details>
 
without AG about 5 sec
<details>

![screenshot_6](https://cloud.githubusercontent.com/assets/18548949/21587093/0a21108e-d0e1-11e6-8c3b-ed82ffdae845.jpg)

</details>

with ext about 20 sec
<details>

![screenshot_7](https://cloud.githubusercontent.com/assets/18548949/21587100/18e7d756-d0e1-11e6-806b-25bec8456d41.jpg)

**Comment by Alex-302** [comment]
@vgavrish is it caused by filters?

**Comment by vgavrish** [comment]
yep, but after disabling English filter, playing ads

**Comment by Alex-302** [comment]
Reproduced on noutbook. I will try to fix it.

**Comment by Alex-302** [comment]
Added to Eng:
```
@@||mssl.fwmrm.net/crossdomain.xml$domain=msn.com
@@||mssl.fwmrm.net/p/msn_live/AdManager.swf$domain=msn.com
@@||msn.com/advertisement.ad.js
```
