### ISSUE TITLE
usp-forum.de - Ad - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3926]
***Site***: http://www.usp-forum.de/artikel-ratgeber/13654-silvester-apps-f-r-android-ios-smartphone-tablet-ins-neue-jahr-2017.html and ad post: http://www.usp-forum.de/apple-iphone-7-forum/126037-iphone-7-komische-display-streifen.html
***Description***: Ad leftover at the top. Social widgets. Ad post in forums on mobile.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21565672/220326a8-ce9b-11e6-80d5-7322a59833c9.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21565656/fa82b954-ce9a-11e6-956b-42d318f10157.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.4.20
Spyware filter | 1.0.9.93
Social media filter | 1.0.16.8
Annoyances filter | 1.0.8.44
German filter | 1.0.29.79
Mobile ads filter | 1.0.6.48
Safari filter | 1.0.1.98

**Comment by Alex-302** [comment]
Added
```
usp-forum.de##.above_header
usp-forum.de##.social_share_bar
```
adman is not shown

**Comment by danidoedel** [comment]
@Alex-302 Ad in forums is still there: 
![image](https://cloud.githubusercontent.com/assets/10995998/21827351/8d1ef1ee-d78b-11e6-9ca3-3c10e66d7c4e.png)
