### ISSUE TITLE
zuhause.de - Ad - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3927]
***Site***: http://www.zuhause.de/ and http://www.zuhause.de/do-it-yourself-diy-anleitungen-zum-reparieren-und-renovieren/id_70379776/index and http://www.zuhause.de/so-bohren-sie-richtig/id_72042216/index
***Description***: Ad leftover. Ad. Social widget on mobile.

<details>
<summary>Screenshot</summary>

http://www.zuhause.de/ :

![image](https://cloud.githubusercontent.com/assets/10995998/21565790/5a085f4a-ce9c-11e6-9dc5-6ae51b1243fe.png)

http://www.zuhause.de/do-it-yourself-diy-anleitungen-zum-reparieren-und-renovieren/id_70379776/index :

![image](https://cloud.githubusercontent.com/assets/10995998/21565826/a7e4cd8e-ce9c-11e6-9c12-3b40f7838193.png)

http://www.zuhause.de/so-bohren-sie-richtig/id_72042216/index :

![image](https://cloud.githubusercontent.com/assets/10995998/21565840/ca57d5c8-ce9c-11e6-8d3c-19f1a16f6a2c.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21565862/1394fd56-ce9d-11e6-8b4e-758bcdd1dbe7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.4.20
Spyware filter | 1.0.9.93
Social media filter | 1.0.16.8
Annoyances filter | 1.0.8.44
German filter | 1.0.29.79
Mobile ads filter | 1.0.6.48
Safari filter | 1.0.1.98

**Comment by Alex-302** [comment]
Added to German filter
```
zuhause.de##div[class$="Thpx270"]
zuhause.de##a[href="http://www.diy-academy.eu/"]
zuhause.de##.med_anz
zuhause.de##.Tsib div.Tmm.Tts.Ttshh[-ext-has="script:contains(GlobalAdTag)"]
```
Added to Social filter
```
zuhause.de##.Tasocnet
```
