### ISSUE TITLE
schnelle-online.info - Ads - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3929]
***Site***: https://www.schnelle-online.info/
***Description***: Social widget leftover at the left. Ads at the right side.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21565966/5de33868-ce9e-11e6-9cfd-4570835c1cf3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.4.20
Spyware filter | 1.0.9.93
Social media filter | 1.0.16.8
Annoyances filter | 1.0.8.44
German filter | 1.0.29.79
Mobile ads filter | 1.0.6.48
Safari filter | 1.0.1.98

**Comment by Alex-302** [comment]
fixed
