### ISSUE TITLE
izzylaif.com/ru - anti-adblocker

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#3931]
for example: http://izzylaif.com/ru/%D0%BA%D0%B0%D0%BA-%D0%BE%D1%82%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C-%D0%B7%D0%B2%D1%83%D0%BA-%D0%B2-%D0%BE%D0%BA%D0%BD%D0%B5-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B0/ 

<details>

![screenshot](https://cloud.githubusercontent.com/assets/23637588/21566361/71ae71e0-ceb3-11e6-96ca-b5e04107e6f4.jpg)

</details>

**Comment by Alex-302** [comment]
fixed
