### ISSUE TITLE
lolking.net - Anti Adblock Script - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3932]
***Site***: http://www.lolking.net/
***Description***: Site detects Adguard. Ad leftover at the right. See rules below.
Not sure if something should be done with the right column though...

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21566701/c0661bc0-cea5-11e6-9c7a-075c0040c653.png)

</details>

***Possible rules:***

English filter:

```
lolking.net##.ad-container
lolking.net##.ad-block-messaging
```

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.4.20
Spyware filter | 1.0.9.93
Social media filter | 1.0.16.8
Annoyances filter | 1.0.8.44
German filter | 1.0.29.79
Mobile ads filter | 1.0.6.48
Safari filter | 1.0.1.98

**Comment by danidoedel** [comment]
@seanl-adg Why was the rule `lolking.net##.ad-container` not added?

**Comment by Alex-302** [comment]
It looks like just a padding
http://i90.fastpic.ru/big/2017/0115/1c/02703e6b1fb38c06e291e4bfe059e61c.jpg

**Comment by danidoedel** [comment]
Ok. For me it's just the one at the top which contained the adblock message. But that's fine. Thank you!
