### ISSUE TITLE
Yandex Disk iOS app - self-advertising

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3933]
https://itunes.apple.com/ru/app/andeks.disk-hranenie-i-obmen/id553266487?mt=8

![image1 2](https://cloud.githubusercontent.com/assets/15856304/21567172/a14f6acc-ceb2-11e6-9d0e-681e5a705b67.PNG)

Is it possible to remove the ads by the DNS filtering?
Logs: 1138152

**Comment by Alex-302** [comment]
I need DNS log.
Try this rule:
```
||banners.mobile.yandex.net^
```
or/and
```
||banners-slb.mobile.yandex.net^
```

**Comment by evgeniy-ADG** [comment]
DNS log is here: 1138152

**Comment by vgavrish** [comment]
@Alex-302 rules help
> Эти фильтры я добавил 2-3 дня назад. 
Результат есть ,баннеры в приложениях ЯНДЕКС блокируются.  Спасибо за работу!

**Comment by Alex-302** [comment]
Ок, добавил в мобильный.
