### ISSUE TITLE
http://m.imore.com/ - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3934]
Incorrect blocking on page:
http://m.imore.com/lg-5k?bt_ee=aD/zDbA1qaayK2Zr4vA10QHOBo0tjRipdVUvo/NP9a0=&bt_ts=1483111972624

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21573022/b26a6e84-cee8-11e6-9817-7378918571f2.png)

</details>

<details>

Application version: 1.1.3.31
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 0E76C3BD-9171-421D-B4E8-9DAA305D8E09

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.80 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.77 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.90 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.25 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.40 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.95 Enabled=YES

</details>

Ticket ID(if exists): 1182387

**Comment by Alex-302** [comment]
@osavranska 
try this rule:
```
@@||imore.com^$generichide
```
But we have some issues with this type of exclusions, maybe it is not working.
