### ISSUE TITLE
Better filters categorization/tagging

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3937]
What we have now is beyond good and evil. Simply splitting filters into three categories, meh.

The thing is that we should keep these categories (for backward compatibility), but also introduce a new better categorization. Maybe we should even use "tagging" instead of categories.

Here are some key things:
1. What filter does block (ads, spyware/tracking, social widgets, all sorts of annoyances, malware, other, etc)?
2. What if filter serves more than one purpose?
3. Is filter language specific or not?
4. Who supports the filter?
5. What if the filter is outdated and is not supported anymore?
6. What if the filter is a supplement for another filter?
7. Do we recommend to use this filter?
8. What if the filter needs to be used along with something else. Like AAK, which needs to be used along with AAK userscript. Or RuAdList, which is better to use along with RuAdList CSS fixes and userscript.

@Alex-302 @seanl-adg 
I need your opinion on this. What do you think about it? What do you think we should do?

**Comment by seanl-adg** [comment]
## Current 'Problems'

1. Regional users who does not visit English sites at all have to use the whole English filter to block ads. For example, some users may do not need PopAds domains in the filters at all.

2. There is no categorization based on website's language in Spyware, Social media, Annoyance filter.

3. Filters with several purposes are mixed in Annoyance filter.

4. Mobile users have to use more filters than desktop users. (rules like `##object[width="1024"][height="150"]` will hardly be needed for mobile websites.)

5. It is impossible to annotate filter rules.

---

One proposal is that every filter rules should have at least one tag (or belongs exactly one category) in following criteria: `Language`, `Purpose`, `Platform`.
Filter rules can optionaly have one more data in `comment`

 * `Language` tags would be `rus, eng, deu,...`, category would be similar, but should have `common` category to deal with problem 1.

* `Purpose` tags would be `ads`, `spyware`, `social`, `annoyance`,
We can split annoyance into more specific purposes, such as `annoyance.popup`, `annoyance.cookie`, `annoyance.self-promo`,... 
We can introduce additional tag in `social`, `social.comments` to block comments widgets.

* `Platform` tag should reflect whether the filter is used on desktop or mobile, whether the platform supports certain syntax (like `$$`). We may even use `max-width:`, `min-width` like media queries in CSS.

 * `comment` information can be used in illustrating what is being blocked in user interface. e.g. `google-analytics.com - Google Analytics`

To classify existing filter rules into this way, there should be some way to deal with filters that are synced to EasyList. Most of third-party filter lists fall in a category of language: certain language, purpose: ads, platform: desktop.

There should be some way to easily maintain such information.

**Comment by ameshkov** [comment]
Please don't forget that we should build this **on top of existing structure** -- to make it compatible with other ad blockers.

**Comment by ameshkov** [comment]
So, do you propose to tag every filter rule?

I'd like us to start with an easier thing: tag filter lists.

**Comment by Alex-302** [comment]
We can make existing files as default for all products, and create additional separate files for browser extensions only.

**Comment by ameshkov** [comment]
We'd better refresh all the filters translations after doing it:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1152

**Comment by TPS** [comment]
To quote @Alex-302 & [myself](https://github.com/AdguardTeam/AdguardFilters/commit/f5cd0e211a27c56ac74e7f21e587e185b1c5211f#commitcomment-22328240), agreeing w/ @seanl-adg (also shows great minds, independently, thinking alike 😁):
>>>So, it's default-*on* for everyone?  I think I've never seen that _written_ anyplace in the GUI, so it might be critical to mention that on the `Filters` tab.  Otherwise, someone who only browses non-English sites may think they're smart by turning it _off_.
>>>
>>>Maybe relabel "Base & English" filters or some such?
>>
>> Easylist is a base filter for all filters. Our Eng filter contains it.
`One does not simply disable Eng/Easylist filter'
>
> Well, sure, ___you___ & ___I___ know that, but Ĵōë Åѷéŕãğê who doesn't English won't know that unless educated.  That toggle isn't protected in _any_ fundamental fashion.

**Comment by ameshkov** [comment]
> Well, sure, you & I know that, but Ĵōë Åѷéŕãğê who doesn't English won't know that unless educated. That toggle isn't protected in any fundamental fashion.

All filters names are translated to Joe's native language so this will not be a problem.

**Comment by TPS** [comment]
I'm not sure we're understanding each other, @ameshkov:

The [conversation](https://github.com/AdguardTeam/AdguardFilters/issues/3937#issuecomment-304896076) I'd w/ @Alex-302 seemed to imply that the AG English _filterlist_ is the base subscription that _everyone_ should have active, whether or not English is a language in which they consume content.

Based on this understanding, I propose that this filterlist be renamed "Base & English" (or smoother equivalent) ___&___ that toggling _off_ said subscription invoke some sort of warning.

**Comment by ameshkov** [comment]
I just suppose that we can safely rename it to "Base" without emphasizing that it was named English before:)

**Comment by TPS** [comment]
> _Like AAK, which needs to be used along with AAK userscript._

_N.B.: [AAK is now practically obsolete](https://github.com/AdguardTeam/AdguardForWindows/issues/1609), so I hope this issue will involve categorizing its various replacements._

**Comment by ministr91** [comment]
Хотелось бы все же увидеть перевод List-KR и описание фильтра  Anti-Adblock Killer | Reek
![_20170619_155823](https://user-images.githubusercontent.com/22351242/27286416-bd72a57a-5508-11e7-94c6-0585b66776a7.JPG)
![_20170619_155852](https://user-images.githubusercontent.com/22351242/27286421-c275dd3a-5508-11e7-8d39-ccb07100dda4.JPG)

**Comment by ameshkov** [comment]
Instead of categories, I propose to stick to the filter level tags. It's up to apps how to work with these tags. 

We should also maintain a list of tags which can be used along with tags description and translations. Despite having that list, free-form tags should also be allowed.

Tag | Description
---- | -------
`purpose:ads` | Blocks ads. Example: EasyList
`purpose:privacy` | Blocks trackers. Example: Adguard Spyware filter
`purpose:social` | Blocks social widgets. Example: Adguard Social filter
`purpose:security` | Security-related filter. Example: Malwaredomains
`purpose:annoyances` | Filter is for blocking ads. Example: Adguard Annoyances filter
`purpose:cookies` | Blocks EU cookie notices. Example: prebake
`lang:*` | Language-specific filters. Examples: `lang:ru`, `lang:zh-cn`
`reference:*` | Filter references another filter. It may contain or be based on the referenced filter. Example: `reference:101` (References EasyList).
`recommended` | Filter is recommended to be used with AdGuard. For example, if a user opts to use `purpose:social` filters, recommended filters will be enabled by default.

**Examples of filters with tags**

* `Adguard English filter`: `purpose:ads`, `recommended`
* `List-KR`: `purpose:ads`, `purpose:privacy`, `lang:kr`, `recommended` 
* `Fanboys Annoyances`: `purpose:social`, `purpose:annoyances`

**Comment by ministr91** [comment]
Ну и раз тут такое дело, то хотелось бы убрать фильтр антиадблок киллер на основании этого сообщения https://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=62296407
