### ISSUE TITLE
FlipBoard app

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3938]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Ads in app, when you watching any news
https://www.microsoft.com/ru-ru/store/p/flipboard/9wzdncrfj32q

In win 10, app added to Filtered apps

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21576725/bbfe6f22-cf42-11e6-9377-c398fd1d6a46.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21576733/06848c84-cf43-11e6-9712-28bddeb7eca5.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21576728/e4983f12-cf42-11e6-81f7-46fca7669a60.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 8.1 |10
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard filters: | 1,2,3,4,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1325700

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня фильтруется
http://i88.fastpic.ru/big/2017/0102/c1/f365490ce87a773b21ee6785a39973c1.jpg
Узнай, видны ли в журнале фильтрации запросы к vesti.ru?(на скрине с этого сайта загружаются новости)

**Comment by vgavrish** [comment]
вот такое у себя ток нашла. попробовала нажать на рекламу
<details>

1-----

![image](https://cloud.githubusercontent.com/assets/18548949/21605211/4287af9e-d1b0-11e6-942d-896cf769cd09.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21605234/6f3f839a-d1b0-11e6-9992-cf77cd25071c.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21605244/79342360-d1b0-11e6-9e39-e051293b8cb1.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21605251/82dfc946-d1b0-11e6-9647-1fea27c2af47.png)

2--------


![screenshot_1](https://cloud.githubusercontent.com/assets/18548949/21605432/e74c9e6c-d1b1-11e6-98b7-c2952353e615.jpg)

![screenshot_2](https://cloud.githubusercontent.com/assets/18548949/21605430/e74ba19c-d1b1-11e6-838b-8b0ec29283cc.jpg)

![screenshot_3](https://cloud.githubusercontent.com/assets/18548949/21605431/e74c82b0-d1b1-11e6-8f90-23e36dd8c7d6.jpg)

![screenshot_4](https://cloud.githubusercontent.com/assets/18548949/21605433/e74fdaf0-d1b1-11e6-9904-987cb2ba3182.jpg)

3---------------

![screenshot_6](https://cloud.githubusercontent.com/assets/18548949/21605448/fa512744-d1b1-11e6-9006-d99a3c7e8ba2.jpg)

![screenshot_7](https://cloud.githubusercontent.com/assets/18548949/21605447/f5c6b2f2-d1b1-11e6-9ea1-0fbdfe218c7b.jpg)

**Comment by Alex-302** [comment]
На скрине - vc.ru, а в логе другой сайт. Лучше окна рядом расположить, чтоб сразу видеть - появляются ли в журнале запросы при навигации.

**Comment by vgavrish** [comment]
в журнале ничего не появляется, если на рекламу не нажать, а потом куча запросов идет
вобще кажется что приложение не фильтруется

<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21634530/9ff6cc0e-d260-11e6-9026-e9554c2131f3.png)

![2](https://cloud.githubusercontent.com/assets/18548949/21634493/5925a5de-d260-11e6-80e7-57aa06da83f8.jpg)

![3](https://cloud.githubusercontent.com/assets/18548949/21634494/5926c1f8-d260-11e6-8e03-de8fc2a2323c.jpg)

**Comment by Alex-302** [comment]
Драйвер - WFP? Приложение точно в фильтруемых?

**Comment by vgavrish** [comment]
> А её уже нет - после настроек, с горем пополам, фильтрация заработала.
Настройка на фильтрацию именно FlipBoard.exe помогла, бяка вычистилась.

**Comment by Alex-302** [comment]
Отлично.
