### ISSUE TITLE
can't to log in Disqus

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3939]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
https://adguard.com/ru/adguard-report/nklyga.lt/report.html

can't to log in Disqus to comment something

**helps disabling English filter**

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21576908/98686306-cf4c-11e6-8b0f-430bc920e84e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | none
Adguard filters: | 1,2,3,4,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1148922

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Strange. It is caused by URL exclusion:
```
@@|https://adguard.com/*.html$document
```

@ameshkov isn't it a bug?
I can reproduce it in private tabs even without filters, only with this rule.
