### ISSUE TITLE
dnainfo.com 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#3940]
[//]: # (***https://www.dnainfo.com/new-york/manhattan/washington-heights-inwood - annoyance popup)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Missed ad on the page***:
* **When you are scrolling down the ad appears**: 

[//]: # ()
[//]: # (Опишите проблему)

Screenshot:

[//]: # (http://prnt.sc/dq08xb)
<details>

* **site without the ad**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***https://www.dnainfo.com/new-york/manhattan/washington-heights-inwood**:

[//]: # (https://www.dnainfo.com/new-york/manhattan/washington-heights-inwood
safari
ios
scroll down and up)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.2.57
Simplified filters(iOS) | On 
Adguard filters: | ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.4.21 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.94 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.12.55 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.8.44 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.92 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.39.55 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.6.49 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.98 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(): 1400924

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
