### ISSUE TITLE
http://tvboryspil.com - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3942]
http://tvboryspil.com/novini/3280-v-aeroportu-borispil-vstanovili-punkt-obminu-samsung-galaxy-note7

![image](https://cloud.githubusercontent.com/assets/15856304/21578918/9f22369a-cf9c-11e6-838d-ba92ce6702c9.png)

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21578923/bc124880-cf9c-11e6-986c-908313cbde1f.png)

**Comment by Alex-302** [comment]
fixed
