### ISSUE TITLE
http://www.healthyfoodhouse.com - Missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3943]
Missed ad on page:
http://www.healthyfoodhouse.com/drink-apple-cider-vinegar-bed-will-treat-health-conditions/

<details>

![img_5804](https://cloud.githubusercontent.com/assets/23258533/21581450/146bde58-d03b-11e6-8142-0627e16a141b.png)

</details>

<details>

Application version: 1.1.2.57
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 42878A25-F168-4CFF-9EB5-D80C7889866D

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.4.36 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.96 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.10 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.99 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.6.50 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.99 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.53 Enabled=YES

</details>

**Comment by Alex-302** [comment]
Not reproduced.
Ads are blocked by
```
||revcontent.com^$third-party
```
