### ISSUE TITLE
http://neofeed.tv - Missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3944]
Missed ad on page:
http://neofeed.tv/69689/1/Watch-Hull-City-vs-Everton-FC/

I am using adguard pro; however, the site i use to stream sports keeps being interrupted intermittently due to an ad. It's making it unusable. The issue occurs when using safari on iPhone. Don't know about other browsers. I use this website for streaming sports.http://neolive.net/ however this ad has just recently started appearing before a stream begins and also interrupts the stream causing it to stop. When you click on it to remove it you are taken to a blank page http://www.adnetworkperformance.com/a/display.php?r=1457571.

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21581523/403ed16e-d03d-11e6-8884-aec12720c3ed.png)

</details>

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/21581527/4e693702-d03d-11e6-98d3-0023c7e760b8.png)

</details>

<details>

Application version: 1.1.3.31
Application lifetime: 2016-12-23 00:44:58 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: DF52D0EF-B148-4EB3-B7DE-E341982636D4

Locale: en
Region: gb

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.4.36 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.96 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.10 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.44 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.50 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.99 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.53 Enabled=YES
ID=101 Name="EasyList" Version=1.0.66 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.71.84 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.66.7 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.71.98 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.71.34 Enabled=NO
ID=210 Name="Spam404" Version=1.0.1.65 Enabled=NO

</details>

Ticket ID: 1155100

**Comment by Alex-302** [comment]
Added to Safari filter
```
neofeed.tv,live247.online###ad_overlay
3live.tv###bannerfloat22
```
Check it after filters update(tomorrow)
