### ISSUE TITLE
http://hdrezka.me - ads

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3945]
http://hdrezka.me/films/family/1046-garri-potter-i-kubok-ognya.html - missed ads

<details>

![image1 2](https://cloud.githubusercontent.com/assets/23258533/21581926/209ef4f4-d04e-11e6-9ba9-cc43879cc503.png)

</details>

<details>

![image2](https://cloud.githubusercontent.com/assets/23258533/21581927/26bf43ca-d04e-11e6-935d-1444bc167dea.png)

</details>

<details>

![image3](https://cloud.githubusercontent.com/assets/23258533/21581928/2e3f6e68-d04e-11e6-8ee2-c79f493bf611.png)

</details>

<details>

Application version: 1.1.2.57
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: 8F39A64B-5CF1-47E0-9DD2-D4E551D765B0

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.4.34 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.96 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.10 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.98 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.99 Enabled=YES

</details>

Ticket ID(if exists): 1479554

**Comment by Alex-302** [comment]
a duplicate
