### ISSUE TITLE
http://satcesc.com - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3946]
http://satcesc.com/web/2016/12/28/la-ufc-las-artes-marciales-mixtas-canal-gol/ - missed ad

Touching on either side of the screen, directs you to the Apple Store

<details>

![image1 3](https://cloud.githubusercontent.com/assets/23258533/21582434/c02753a2-d05f-11e6-9013-e6482ea72363.png)

</details>

<details>

Application version: 1.1.3.31
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2.1
ID: D83855D0-C974-4FF1-B809-553F47BF3F42

Locale: es
Region: es

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.4.19 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.93 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.8 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.47 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.48 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.98 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.71.78 Enabled=YES
ID=231 Name="Easylist Spanish" Version=1.0.8.55 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.71.92 Enabled=YES
ID=230 Name="FanboyEspanol" Version=1.0.0.1 Enabled=YES
ID=229 Name="I dont care about cookies" Version=1.0.0.11 Enabled=YES
ID=205 Name="Schacks Adblock Plus liste" Version=1.0.1.77 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.65 Enabled=YES

</details>

Ticket ID: 1479157

**Comment by Alex-302** [comment]
Not reproduced on iPad.
***Optimazed enabled: NO***
try to enable it, or disable
```
ID=118 Name="EasyPrivacy" Version=1.0.71.78 Enabled=YES
ID=231 Name="Easylist Spanish" Version=1.0.8.55 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.71.92 Enabled=YES
ID=230 Name="FanboyEspanol" Version=1.0.0.1 Enabled=YES
ID=229 Name="I dont care about cookies" Version=1.0.0.11 Enabled=YES
ID=205 Name="Schacks Adblock Plus liste" Version=1.0.1.77 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.65 Enabled=YES
```
ads are blocked by
```
||yuhuads.com^$third-party
```
