### ISSUE TITLE
felomena.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3948]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: When you are scrolling down the ad appears
http://felomena.com/sonnik/k/koshka/i-krysa/

Android&Win

Log. time 14-00
[debug (24).txt](https://github.com/AdguardTeam/AdguardFilters/files/680749/debug.24.txt)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21587894/d61073f8-d0e9-11e6-92b2-5127a7a0a1ed.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21587920/0c7c26e4-d0ea-11e6-80a6-61782f88de58.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Android 
Browser: | Chrome
Adguard version: | 2.8.76 & 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default)
Adguard filters: | 1,2,3,4,14,211

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1150428

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
