### ISSUE TITLE
allkharkov.info

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3949]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://allkharkov.info/
When you create your ad, its blocked by Adguard

**helps disabling Russian filter**

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screenshot_8](https://cloud.githubusercontent.com/assets/18548949/21588993/706f4de2-d0f5-11e6-91e0-14c7f8b58868.jpg)
![screenshot_9](https://cloud.githubusercontent.com/assets/18548949/21588994/70740a9e-d0f5-11e6-84f7-58268823747c.jpg)
![screenshot_10](https://cloud.githubusercontent.com/assets/18548949/21588995/70748bd6-d0f5-11e6-9f56-77adf55497a9.jpg)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard filters: | 1,2,3,4,14

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

id 1476124

**Comment by Alex-302** [comment]
added
```
@@||allkharkov.info/post-ad.html
```
please check

**Comment by vgavrish** [comment]
works

**Comment by Alex-302** [comment]
ok
