### ISSUE TITLE
https://spaces.ru - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3950]
https://spaces.ru/shared_zone/?Clt=1&from=main - missed ad

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21589295/166ffa9a-d0f9-11e6-884c-3983e08d0c0d.png)

</details>

<details>

Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2.1
ID: 3888E646-38F4-454D-9F31-0C929D0A938F

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.4.52 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.96 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.10 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.44 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.99 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.99 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.66.14 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.66.29 Enabled=NO
ID=115 Name="RU AdList" Version=1.0.72.9 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.70 Enabled=YES
ID=222 Name="Adblock-Persian list" Version=1.0.0.23 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.68.95 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.68.64 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.65 Enabled=YES
ID=232 Name="KAD - Przekrety" Version=1.0.0.83 Enabled=YES

</details>

Ticket ID(if exists): 1477963

**Comment by Alex-302** [comment]
Они жестко стиль задают при попытке скрыть. На iOS, похоже, не убрать.

**Comment by Alex-302** [comment]
А может скроется. Пусть завтра после обновления проверит.

**Comment by evgeniy-ADG** [comment]
На Маке и Виндоуз убрать можно?

http://spaces.ru/

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21731743/9349a49a-d45e-11e6-9555-ec006b7ca895.png)


</details>

Eng + Ru filters, Windows 10, 6.1.298.1564, Wfp, Stealth mode.

**Comment by evgeniy-ADG** [comment]
It's back on Windows:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21799937/115f0c0e-d724-11e6-9e5b-d6640714fb75.png)

</details>

Basic filters (ru + en + sm + spyware, no stealth, wfp, win 10)

**Comment by Alex-302** [comment]
fixed
