### ISSUE TITLE
Pixiv - Missed ads 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3951]
***Description***: Missed ads in the application Pixiv 

PlayStore link:
https://play.google.com/store/apps/details?id=jp.pxv.android 

Screenshot:
<details>

![pixiv](https://cloud.githubusercontent.com/assets/17504743/21589971/079357c2-d100-11e6-8342-af404c0f1a9a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | List-KR 1.0.1.84 Korean Adblock List 1.0.0.0.3 Anti-Adblock Killer Reek 1.0.1.68 Simplified domain names filter 1.0.0.53 Mobile Ads filter 1.0.6.50 Experimental filter 1.0.26.41 Japanese filter 1.0.93.3 Filter unblocking useful ads 1.0.0.97 Social media filter 1.0.016.10 Spyware filter 1.0.9.96 English filter 1.1.4.50

Ticket ID(if exists): 1479236

**Comment by Alex-302** [comment]
Ad is blocked on my device.
@seanl-adg please take a look.

**Comment by seanl-adg** [comment]
Not reproduced on my end too, but added some unblocked ad servers to Japanese filter.
The user can try a few things - 
 * Try enabling Japanese filter.
 * Try enabling "Filter DNS requests" option at Settings > Advanced.

After then, the user can remove Pixiv app's cache and check again.
If it does not help, we would need an app log to troubleshoot ads. https://kb.adguard.com/index.php?/Knowledgebase/Article/View/49/0/collecting-a-full-log-on-adguard-for-android
