### ISSUE TITLE
agenciatributaria.gob.es - Incorrect blocking 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3956]
***Description***:
https://www.agenciatributaria.gob.es  Is the official website of the Tax agency in Spain. They use a digital certificate to access. When AG is running even if all the filters are disabled - the web can not access the certificate. Only solution is to close AG completely to make it work.

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | "BlockThirdPartyCookies": true,  "BlockThirdPartyCookiesPeriodMin": 30,  "BlockFirstPartyCookies": false,  "BlockFirstPartyCookiesMin": 2880,  "DisableThirdPartyCache": false,  "BlockWebRtc": false,  "BlockBrowserPushApi": false,  "BlockBrowserLocationApi": true,  "RemoveXClientDataHeader": true,  "HideSearchQueries": true,  "SendDoNotTrackHeader": true,  "RemoveRefererFromThirdPartyRequests": false,  "HideUserAgent": false,  "CustomUserAgent": null,  "CustomReferer": null,  "HideIp": false,  "CustomIp": "209.141.53.254"
Adguard filters: | Spyware, English, Social media, Unblocking useful ads, German, Spanish, User

Ticket ID(if exists): 1480159

**Comment by Alex-302** [comment]
Steps to reproduce or screenshot? I do not understand. Is it HTTPS issue? This site is not filtered by AG for Windows on my side.
