### ISSUE TITLE
m.mangatown.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3957]
Source report:
https://forum.xda-developers.com/showpost.php?p=70311663&postcount=2003

The screenshot is there attached to the forum post.

Cannot reproduce it on my Android device, though. 
Please check it with https filtering disabled as well.

**Comment by Alex-302** [comment]
Not reproduced even without Adguard.
User can try
```
||graph.facebook.com^$domain=m.mangatown.com
```

**Comment by Alex-302** [comment]
For one ad and leftover:
```
m.mangatown.com##div[class^="adv-"]
```
