### ISSUE TITLE
http://dc.wikia.com/ - Anti Adblock Script

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3958]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
http://dc.wikia.com/

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21602548/b1ce7f26-d19d-11e6-83db-8f4cae5d8623.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Adguard filters: | 1,2,3,4,14,211

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1084826

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
