### ISSUE TITLE
kisscartoon.se - Anti-Adblock Notification

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#3959]
***Description***: 
When you start playing any video on kisscartoon.se in 10-30 seconds it stops and asks to turn off adblock. 
http://kisscartoon.se/Cartoon/Ready-Jet-Go/Episode-27-Diggin-Earth-Mindy-s-Mystery?id=72967

Screenshot:
<details>

![capture](https://cloud.githubusercontent.com/assets/17504743/21605963/178894e8-d1b5-11e6-8b30-7253e6f520a0.PNG)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.258.1302 (Reproduced with the latest one) 
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | "BlockThirdPartyCookies": true,  "BlockThirdPartyCookiesPeriodMin": 30,  "BlockFirstPartyCookies": false,  "BlockFirstPartyCookiesMin": 2880,  "DisableThirdPartyCache": false,  "BlockWebRtc": false,  "BlockBrowserPushApi": false, "BlockBrowserLocationApi": true,  "RemoveXClientDataHeader": true,  "HideSearchQueries": true,  "SendDoNotTrackHeader": true,  "RemoveRefererFromThirdPartyRequests": false,  "HideUserAgent": false,  "CustomUserAgent": null,  "CustomReferer": null,  "HideIp": false,  "CustomIp": "209.141.53.254"
Adguard filters: | Russian, English, Social media, Spyware, German, Mobile ads, Annoyance, Experimental

Ticket ID(if exists): 1084826

**Comment by Alex-302** [comment]
Added
```
@@||visitweb.com/js/ref.js
```
@Tetiana2020 please check it.
