### ISSUE TITLE
tapochek.net

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3960]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Ads
tapochek.net
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21606651/91dc947a-d1b9-11e6-8bb8-19fc63311970.png)

</details>

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.3.31
Simplified filters(iOS) | Optimazed enabled: NO
Adguard DNS: | Default 
Adguard filters: | 1,2,3,4,12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1154654

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
