### ISSUE TITLE
http://www.ynet.co.il - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3961]
http://www.ynet.co.il/home/0,7340,L-8,00.html - incorrect blocking

white  space at the bottom if the page

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/21608651/8a6a3fdc-d1c6-11e6-9cfd-72f052ffa790.png)

</details>

<details>

Application version: 1.1.2.24
Application lifetime: 2016-10-25 21:08:16 +0000

Device: iPhone
Platform: iOS
OS: 10.1
ID: D698D3FA-307B-4E14-BA27-96C66A6C8141

Locale: en
Region: il

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.99.89 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.8.84 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.14.30 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.64 Enabled=YES

</details>

Ticket ID(if exists): 1423882

**Comment by Alex-302** [comment]
@osavranska ad leftover is not a result of incorrect blocking.
Added:
```
m.ynet.co.il##div[id^="GoogleAdStrip"]
```
