### ISSUE TITLE
afdah.info [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#39622]
**Site**: https://afdah.info/

**Issue**: Please remove the Adblock message

**Screenshot**: Attached

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 76.0.3809.132 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 3.2.1	 `

**Filters**:
```
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404
NoCoin Filter List

```

**Stealth Mode Settings**:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled (Default)
![Screenshot_1](https://user-images.githubusercontent.com/6959116/64014777-97678480-cb40-11e9-92ee-71b1e3facf99.jpg)

**Comment by Nzzyme** [comment]
Additionally, unable to view player on this page:

https://afdah.info/watch-movies/67796-brightburn-2019/#

**Comment by Nzzyme** [comment]
Seeing an ad block message on this page on the video player
https://afdah.info/watch-movies/67827-john-wick-chapter-3-parabellum-2019/

![Annotation 2019-08-30 205304](https://user-images.githubusercontent.com/6959116/64032544-508d8500-cb68-11e9-8c05-b3dadbb0328b.png)

**Comment by Alex-302** [comment]
damn. Fixed)

**Comment by Nzzyme** [comment]
Seeing adblock message again

https://afdah.info/watch-movies/67985-richard-jewell-2019/

Screenshot: https://prnt.sc/r2q60r

**Comment by Alex-302** [comment]
Not reproduced.
