### ISSUE TITLE
https://xhamster.com - ads

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3963]
Missed ad on page:
https://xhamster.com/movies/1500435/sexy_thick_cock_sucking_girl_with_big_ass_gets_fucked_in_her_wet_little_pussy.html

it is in the right corner

<details>

![image1 3](https://cloud.githubusercontent.com/assets/23258533/21614103/d1954f7c-d1e0-11e6-9b9e-0ffca14151f6.png)

</details>

<details>

![image2](https://cloud.githubusercontent.com/assets/23258533/21614140/ee014a76-d1e0-11e6-99da-b851ae2314f1.jpeg)

</details>

<details>

Application version: 1.1.2.57
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: 871ABB72-68B1-4860-AC51-CD6A1214163A

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.55 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.66 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.69 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.88 Enabled=YES

</details>

Ticket ID: 1479237

**Comment by Alex-302** [comment]
Not reproduced.
