### ISSUE TITLE
leagueoflegends.com - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3964]
***Site***: https://account.leagueoflegends.com/euw/en/protect and https://account.leagueoflegends.com/euw/en/forgot-password and maybe others...
***Description***: Several parts of the website won't load properly.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21620153/4786a7aa-d1f3-11e6-99ea-138aa7a209d4.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21620139/3b6cd7aa-d1f3-11e6-918e-3f102fae5c23.png)

</details>

***Steps to reproduce the problem:***
1. Go to https://account.leagueoflegends.com/euw/en/forgot-password
2. Enter anything and hit submit.
3. Spinning wheel appears but nothing happens.
4. Same for https://account.leagueoflegends.com/euw/en/protect (You have to be logged in to see that though).
5. Disabling Adguard solves the problem.

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.4.68
Spyware filter | 1.0.9.99
Social media filter | 1.0.16.10
Annoyances filter | 1.0.8.46
German filter | 1.0.29.91
Mobile ads filter | 1.0.6.52
Safari filter | 1.0.2

**Comment by Alex-302** [comment]
Added to English filter
```
@@||account.leagueoflegends.com/pm.html$jsinject,elemhide
```
