### ISSUE TITLE
http://www.fanoffifa.com - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3965]
http://www.fanoffifa.com/2015/10/fifa-16-best-young-players-talents.html?m=1 - incorrect blocking

<details>

![image1 4](https://cloud.githubusercontent.com/assets/23258533/21620974/ac766cc0-d1ff-11e6-8c35-c6024ad44dc7.png)

</details>

<details>

Application version: 1.1.4.36
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 1AA7CF0F-38C0-4146-A2BA-9FF493BC729A

Locale: en
Region: au

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.4.62 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.99 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.10 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.46 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.41 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.52 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2 Enabled=YES
ID=101 Name="EasyList" Version=1.0.66.16 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.72.2 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.72.15 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES

</details>

Ticket ID(if exists): 1480820

**Comment by Alex-302** [comment]
fixed
