### ISSUE TITLE
Rework all filters metadata

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3966]
It just looks weird to me now:
https://filters.adtidy.org/extension/chromium/filters/13.txt

Two "Title" blocks
TimeUpdated instead of Updated
and some other weird things.

1. Review all filters titles, descriptions, tags
2. Take care of oneskyapp.
3. `! Title:` attribute for Adguard language-specific filters should start with 'Adguard ' prefix. For instance, `Adguard Russian filter`. Do not change filter name in the database.
4. Fix the duplicated meta attributes -- for instance, here: https://filters.adtidy.org/extension/chromium/filters/101.txt
5. `TimeUpdated:` --> `Last modified:`

**Comment by Alex-302** [comment]
Who should do this?

**Comment by ameshkov** [comment]
That's on me, partly done in other infrastructure issues, but I'd better examine it one more time after we add tags.

**Comment by vbagirov** [comment]
@ameshkov done.

**Comment by ameshkov** [comment]
https://github.com/AdguardTeam/FiltersRegistry
