### ISSUE TITLE
Hornet app

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3967]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
https://play.google.com/store/apps/details?id=com.hornet.android&hl=ru

periodically appears advertising on top in all sections of the application except the settings.

log 
[debug (41).txt](https://github.com/AdguardTeam/AdguardFilters/files/684126/debug.41.txt)
03.01 00-42

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21634903/0d8031fa-d263-11e6-85d0-991aaa6102b5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard filters: | 2, 3, 4, 14, 1, 11

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1053761

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.
Check this rule:
```
||graph.facebook.com^$app=com.hornet.android
```

**Comment by evgeniy-ADG** [comment]
Передал.

**Comment by vgavrish** [comment]
@Alex-302 
правило помогло

**Comment by Alex-302** [comment]
А уточните ещё, авторизация через FB работает с этим правилом? Не хочется через свой аккаунт туда заходить.

**Comment by vgavrish** [comment]
спросила

**Comment by evgeniy-ADG** [comment]
Не знает, авторизируется при помощи логиа и пароля. Ща попробую.

**Comment by Alex-302** [comment]
Ок, добавил.
