### ISSUE TITLE
https://mobil.teltarif.de/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3968]
https://mobil.teltarif.de/gsm-ausstieg-att-australien-deutschland/news/66846.html

![image](https://cloud.githubusercontent.com/assets/15856304/21638118/923ef1ba-d272-11e6-970e-aa4e4307c709.png)

<details>

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.4.51 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.9.99 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.10 Enabled=YES
ID=6 Name="German filter" Version=1.0.29.88 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.54 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.72 Enabled=YES
ID=229 Name="I dont care about cookies" Version=1.0.0.11 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES

**Comment by Alex-302** [comment]
Added to German filter
```
mobil.teltarif.de##p[class]+div[style^="margin:"] > i
mobil.teltarif.de##p[class]+div[style^="margin:"] > div.tgtLink
```
