### ISSUE TITLE
http://k2nblog.com - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3971]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

Can we block the annoying "wait 60 sec to proceed with the download" message?

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21640305/95ad98be-d27d-11e6-9402-06c6bc0f7c36.png)

</details>

***Steps to reproduce the problem***:

Go there http://k2nblog.com/s-e-s-remember-s-e-s-20th-anniversary-special-album/ and see the message saying you have to wait

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome 55
Adguard version: | 1.4
Adguard filters: | eng, rus, annoyances, german, spyware, social media

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1480654

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
