### ISSUE TITLE
pexels.com - Ad - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3972]
***Site***: https://www.pexels.com/photo/adventure-climb-cold-dawn-285168/
***Description***: Social widgets at the right and bottom. Sponsored ad and partner offer.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21654136/81bb8e06-d2b4-11e6-8f15-a9dc1adb6281.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21654191/c34e33aa-d2b4-11e6-9fa0-5319004dc941.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.4.78
Spyware filter | 1.0.9.99
Social media filter | 1.0.16.12
Annoyances filter | 1.0.8.48
German filter | 1.0.29.93
Mobile ads filter | 1.0.6.55
Safari filter | 1.0.2.2

**Comment by Alex-302** [comment]
fixed
