### ISSUE TITLE
lolchampion.de - Anti Adblock Script - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3973]
***Site***: http://www.lolchampion.de/
***Description***: Adblock detection at the right side and ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21654299/43e89046-d2b5-11e6-9ca8-6a2fc4bfff8e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.4.78
Spyware filter | 1.0.9.99
Social media filter | 1.0.16.12
Annoyances filter | 1.0.8.48
German filter | 1.0.29.93
Mobile ads filter | 1.0.6.55
Safari filter | 1.0.2.2

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
lolchampion.de##a[href="http://www.lolchampion.de/adblocker-deaktiveren/"] > img
lolchampion.de###sidebar div[class="widget widget_text"][-ext-has=".textwidget:contains(Anzeige)"]

```
