### ISSUE TITLE
mobafire.com - Ad leftover -  Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3974]
***Site***: http://www.mobafire.com/ and others like http://www.mobafire.com/league-of-legends/champions
***Description***: Ad leftovers. And Adblock detection (not always shown).
Same for other Mobafire Network sites like:
http://www.owfire.com/
http://www.pgfire.net/
http://www.vaingloryfire.com/
http://www.heroesfire.com/
http://www.smitefire.com/
http://www.dotafire.com/
http://www.elophant.com/

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21654637/b4be6434-d2b6-11e6-91b7-dec950cca60d.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21654661/d453bdbc-d2b6-11e6-9887-80524a739a1e.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21654725/216a2b5e-d2b7-11e6-9c5b-9bafc130c99c.png)

```html
<div class="ads-popup adblock mf" style="display:none">
	<span class="close"></span>
	<img class="sad-face" src="/images/mf-sadface.png">
	<h2>We see you are <br> running AdBlock...</h2>
	<p>MOBAFire is free and advertising <br>
		supported. Please consider whitelisting us<br>
		or signing up for <a href="http://www.mobafire.com/prime">MFN Prime</a>.
	</p>
</div>
```
</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.4.78
Spyware filter | 1.0.9.99
Social media filter | 1.0.16.12
Annoyances filter | 1.0.8.48
German filter | 1.0.29.93
Mobile ads filter | 1.0.6.55
Safari filter | 1.0.2.2

**Comment by Alex-302** [comment]
Added to English filter
```
mobafire.com##.ads
heroesfire.com,vaingloryfire.com,pgfire.net,mobafire.com##.ads-narrow
elophant.com,owfire.com,mobafire.com##.ad
```
Added to Annoyances filter
```
mobafire.com###sidebar-free-champs+div.box-shadow.mb10 
heroesfire.com,vaingloryfire.com,pgfire.net,owfire.com##.sidebar-feature.add.box
smitefire.com##.self-clear div.caroufredsel_wrapper
owfire.com,pgfire.net,vaingloryfire.com,heroesfire.com,smitefire.com,dotafire.com,elophant.com,mobafire.com#%#window.canRunAds = true;
```
