### ISSUE TITLE
eztv.ag

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#3975]
these ads arent visible but we can speed up page time by blocking them. they are only being hidden right now. it requests 14 different ad images everytime you go to the main page.

||eztv.ag/images/pcprotect/

https://eztv.ag/showlist/

example url: https://eztv.ag/images/pcprotect/win10_overlay_pcprotect_ie.png

**Comment by Alex-302** [comment]
Ok
