### ISSUE TITLE
win-10-forum.de - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3977]
***Site***: http://www.win-10-forum.de/windows-10-updates-and-patches/25353-kumulatives-update-fuer-windows-10-version-1607-fuer-x64-basierte-systeme-kb3201845.html
***Description***: Ad post on mobile.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21664232/97fad876-d2e5-11e6-9e0b-8f84a14709e4.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.4.82
Spyware filter | 1.0.10
Social media filter | 1.0.16.14
Annoyances filter | 1.0.8.51
German filter | 1.0.29.96
Mobile ads filter | 1.0.6.56
Safari filter | 1.0.2.2

**Comment by Alex-302** [comment]
fixed
