### ISSUE TITLE
deutsche-handwerks-zeitung.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#3978]
***Site***: http://www.deutsche-handwerks-zeitung.de/
***Description***: Newsletter overlay and cookie notice at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21664332/02689b76-d2e6-11e6-8d44-59e644b87e20.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.4.82
Spyware filter | 1.0.10
Social media filter | 1.0.16.14
Annoyances filter | 1.0.8.51
German filter | 1.0.29.96
Mobile ads filter | 1.0.6.56
Safari filter | 1.0.2.2

**Comment by Alex-302** [comment]
added
```
deutsche-handwerks-zeitung.de#%#document.cookie = "showsupportwin_nlreg=none"; 
deutsche-handwerks-zeitung.de###cc-box
```
