### ISSUE TITLE
britannica.com [False Blocking]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#39801]
https://www.britannica.com/animal/insect/images-videos

Unable to play the video on this page. Please check with AG for Chrome

**Comment by THEtomaso** [comment]
@AdamWr:
Another video playback issue at `britannica.com`:
`https://forum.palemoon.org/viewtopic.php?f=3&t=23957/`

**Comment by AdamWr** [comment]
Fixed, thank you for reporting it.
Update should be available in 1-2 hours.
