### ISSUE TITLE
cosstores.com 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3980]
Original report:
https://github.com/AdguardTeam/ContentBlocker/issues/47

> When clicking on a product to see more information about it, it just does nothing. This is happening when using Samsung Internet with Adguard for Android.

Actually it happens with all AG products including desktop browser extension.

**Comment by seanl-adg** [comment]
I guess we should add some JS rules to fix possible issues with google tag manager being blocked.
This JS rule should contain eventCallback and eventTimeout api for dataLayer object.

**Comment by ameshkov** [comment]
JS rules won't work in case of content blockers

**Comment by seanl-adg** [comment]
Of course we should add exception rules to at least Safari filter, but fixing it with JS rule will amend many other websites breakage as well.

**Comment by ameshkov** [comment]
Hm, wait, do we really block google tag manager? The thing is that it used for a lot of things, it could be crucial for some websites functionality.

**Comment by seanl-adg** [comment]
Only unblocking google tag manager does not help in this case, one need to whitelist google analytics script and another google's script. Therefore only removing googletagmanager rule in the Spyware filter doesn't help.

**Comment by ameshkov** [comment]
@seanl-adg but why Safari filter only? All products are affected.
