### ISSUE TITLE
http://opgelicht.avrotros.nl/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3981]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: The [link](http://opgelicht.avrotros.nl/hulp/oplichtingstrucs/item/8809/)

[//]: # (Tell us what happens)
# Adguard blocks the youtube video and the social media widget is not blocked

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21676222/7d82ecd8-d33d-11e6-8cdb-4905c9fa2f8d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.4.60
Simplified filters(iOS) | Off
Adguard filters: | 2, 3, 4, 14, 10, 8, 11, 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists):  1428196

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I need screenshot with a player. It is not working in all my browsers with completely unloaded AG.

**Comment by evgeniy-ADG** [comment]
![file_000 1](https://cloud.githubusercontent.com/assets/15856304/22460851/82669926-e7af-11e6-8d6c-36689ee923b6.png)

It available when you whitelist the site in Adguard on iPad

**Comment by Alex-302** [comment]
@evgeniy-ADG is it your screenshot? I still see an empty youtube frame(Win,iOS,Mac OS).

**Comment by evgeniy-ADG** [comment]
Yes, I made it yesterday. It's blocked unless you whitelist the site.
