### ISSUE TITLE
 Anti-adblock  http://wasabisyrup.com

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#3982]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***The client cannot access http://wasabisyrup.com it uses ad detecter that
different from fuckadblock.js .

* **User of Samsung Internet (Ver. 4.0.20-78), Chrome(Ver. 55.0.2883.91) and Adguard (Ver.2.8.76)
Has such filters enabled: English, Spyware, Mobile Ads, List-KR and User(#%#var fuckAdBlock = false) filters. Could reproduce this with the standard set of filters.
(http://imgur.com/a/eiCic Samsung internet with Adguard
http://imgur.com/3HUevfT Chrome with Adguard
http://imgur.com/a/Qfs4s Samsung internet

The issue occurs in all the browsers.
**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (http://imgur.com/a/eiCic )

***Steps to reproduce the problem***:

[//]: # Adguard blocks the access to http://wasabisyrup.com when it is enabled

***System configuration***

Information | value
--- | ---
Operating system: | Android / androidVersion" : "6.0.1 (sdk=23)
Browser: | Samsung internet, Chrome
Adguard version: | versionName" : "2.8.76
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default/Blacklist mode)
Adguard filters: |  English, Spyware, Mobile Ads, List-KR and User(#%#var fuckAdBlock = false) filters

[//]: # (*** English, Spyware, Mobile Ads, List-KR and User(#%#var fuckAdBlock = false) filters)

Ticket ID(1482302):

**Comment by Darina655** [comment]
one more message:
I request that please resolves the issue
at the same time, i searched how to fix the issue and found it.

it is add the user filter "#%#plugin01 = false"

after adding the filter, i can access wasabisyrup.com smoothly.

**Comment by Alex-302** [comment]
@Darina655 don't use `[//]: #` for useful strings. They are invisible(for example - screenshot)

Added to English filter
```
@@||wasabisyrup.com^$generichide
```
