### ISSUE TITLE
http://tumejortorrent.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3983]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

The site opens multiple windows on the background when browsing

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21679148/0cea9616-d34b-11e6-926e-db2ae35855fe.png)

</details>

***Steps to reproduce the problem***:

1. Go to http://tumejortorrent.com/
2. Click on a movie cover
3. Profit.

***System configuration***

Information | value
--- | ---
Operating system: | Android, MacOS X
Browser: | Chrome
Adguard version: | 2.8.76, 1.4
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  Off
Adguard filters: | 2, 3, 4, 14, 9, 11, 15 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1463025

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
