### ISSUE TITLE
http://qtv.ua/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3984]
http://qtv.ua/ru/video/gubka-bob-narod-diznayetsya-shho-znachit-zhiti-po-novomu/

![image](https://cloud.githubusercontent.com/assets/15856304/21695468/a1c33558-d392-11e6-8061-bdedc31a08ca.png)

Windows 10, Chrome 55, WFP. No Stealth mode. English, Russian, SM, Annoyances filters, all updated before filing the task.

**Comment by Alex-302** [comment]
fixed
