### ISSUE TITLE
http://tutknow.ru - ads

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3987]
http://tutknow.ru/cookery/second_dishes/2855-steyk-iz-govyadiny.html - missed ad

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21702835/992973ac-d3b6-11e6-823b-d647c62976a9.png)

</details>

<details>

Application version: 1.1.4.60
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: 9EF34874-2B36-4CE3-87E9-E1DB4AB05231

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.70 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.72 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.85 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.63 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.89 Enabled=YES
ID=101 Name="EasyList" Version=1.0.65.80 Enabled=YES

</details>

Ticket ID(if exists): 1243725

**Comment by Alex-302** [comment]
это не реклама, просто сайт трэшовый
