### ISSUE TITLE
facebook.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3988]
I see sponsored posts again.

Here is a rule, which helps me:
`facebook.com##div[id^="feed_stream_"] div[id^="substream_"]:has(.userContentWrapper span>span._m8d)`

@Alex-302 @seanl-adg please check what's on your side.

**Comment by Alex-302** [comment]
It works, but hides too much. `div[id^="substream_"]` should not be hidden.
Try this:
```
facebook.com##div[id^="feed_stream_"] > div[id^="more_pager_"] > div > div[id^="substream_"] div[id^="hyperfeed_story_id_"][-ext-has=".userContentWrapper span>span._m8d"]
```

**Comment by Alex-302** [comment]
added
