### ISSUE TITLE
simple-adblock.com - testing ad blocker page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#3989]
AG extension does not pass this test:
http://simple-adblock.com/faq/testing-your-adblocker/

The thing is that we don't load generic element hiding rules to small frames.
I suggest adding this rule just to pass the test:
`simple-adblock.com##.ad_300x250`

**Comment by seanl-adg** [comment]
Ok, but on AG for Windows, it even hides the iframe and test results are invisible. Should we fix this too?

**Comment by ameshkov** [comment]
Yeah, just modify `##iframe[width="300"][height="250"]` rule
