### ISSUE TITLE
http://www.thefreedictionary.com/test - incorrect blocking

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdguardFilters#3990]
Adguard completely blocks the pronounce buttons on The Free Dictionary website. Please exclude them. Thank you.

**Comment by Alex-302** [comment]
Please don't ignore the template. I'm not a mind reader:)
Try this rule:
```
thefreedictionary.com#@%#Object.defineProperty(window, 'warn', { get: function() { return -1; } });
```

**Comment by snhv** [comment]
It works! Thank you and noted.
