### ISSUE TITLE
Pizza Hut New Zealand

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#39902]
### Issue URL (Incorrect Blocking)
[https://apps.apple.com/nz/app/pizza-hut-new-zealand/id1030235266](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fapps.apple.com%2Fnz%2Fapp%2Fpizza-hut-new-zealand%2Fid1030235266)
### Comment
> Issue is with the pizza hut app. 
> Happened today at 9:16PM
> Issue is cannot connect to server 
> Running IOS 12.4 and latest version of AdGuard Pro
> 
> DNS logs are here: 2239342

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/7BXra6n.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/voV91Gw.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | iOS
AdGuard version: | 2.1.2.173
Browser: | Pizza Hut New Zealand
System wide filtering: | disabled
Simplified filters: | disabled
AdGuard DNS: | Default
Filters: | AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media,<br>AdGuard Mobile Ads,<br>AdGuard Safari,<br>AdGuard Annoyances,<br>Fanboy's Annoyances,<br>Adblock Warning Removal List,<br>Spam404

_Originally posted by @adguard-bot in https://github.com/AdguardTeam/AdguardFilters/issues/38779#issuecomment-522442029_

**Comment by zloyden** [comment]
Without DNS issue not reproduced. But if enable system wide filtering (privacy) with `adguard default` - it is reproduced. I suggest add domain in app -> Privacy Settings -> Whitelist  `fls.doubleclick.net`.

**Comment by Eugene-Savenko** [comment]
Ofc you won't reproduce it w/o the DNS - it's the DNS filtering issue, and it should be fixed.
