### ISSUE TITLE
http://vashgorod.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3991]
http://vashgorod.ru/prokopievsk/?change_city

![image](https://cloud.githubusercontent.com/assets/15856304/21721763/7299ca12-d432-11e6-9705-e81dbcf95fe1.png)

<details>

Os version: Microsoft Windows NT 6.1.7601 Service Pack 1
AppVersion: 6.1.298.1564

Subscriptions: FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
Filtering Mode: Driver
Driver Type: Tdi
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": false,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": false,
  "BlockWebRtc": false,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": false,
  "HideSearchQueries": false,
  "SendDoNotTrackHeader": false,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": true,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": true,
  "CustomIp": "209.141.53.254"

**Comment by Alex-302** [comment]
fixed
