### ISSUE TITLE
http://s0ft4pc.com/ anti adblock safari ios

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#3992]
Hey
have anti adblcok in site: http://s0ft4pc.com/ in safari on ios

**Comment by Alex-302** [comment]
Not reproduced.
Don't ignore the template.

**Comment by MrTal** [comment]
only on ios, in open site: http://s0ft4pc.com/ have anti adblock

**Comment by Alex-302** [comment]
Filters, screenshot?
