### ISSUE TITLE
https://good-surf.ru/ - annoyance/anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3993]
https://good-surf.ru/

![image](https://cloud.githubusercontent.com/assets/15856304/21731892/5e3feaba-d45f-11e6-8ee5-1b30eab2e337.png)

Ticket ID: 873545

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
||good-surf.ru//script/script.js
```
