### ISSUE TITLE
http://zismo.biz/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3994]
There's a banner on top, it opens the page on the very same site but it advertises the app. If we can block such banners, please block:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21732550/a92e2ec6-d462-11e6-847b-58fa427c162c.png)

</details>

<details>

Application version: 1.1.4.36
OS: 10.1.1
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.4.70 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.99 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.10 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.45.2 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.2 Enabled=YES

+ annoyances

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
zismo.biz##a[href^="http://zismo.biz/index.php?app="] > img
```
