### ISSUE TITLE
AppZapp Notify - missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3995]
Missed ad in application AppZapp Notify.

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21735428/7d8eaaf6-d472-11e6-8588-f0d4b97e3924.png)

</details>

<details>

Application version: 1.1.4.36
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 00F9FEB2-3BE5-4E86-825C-F8870F429613

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.1 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.15 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.53 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.45.9 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.4 Enabled=YES

</details>

Ticket ID(if exists): 1474788

**Comment by Alex-302** [comment]
Only PRO version can block ads in apps.

**Comment by Alex-302** [comment]
@osavranska 
what's wrong?)

**Comment by osavranska** [comment]
@Alex-302 user has Adguard Pro. I requested his log files. 
Please see ticket: 1474788

**Comment by Alex-302** [comment]
@osavranska а время? Тыщу раз писали же, что время открытия сайта/приложения нужно указывать. Логи слишком большие, чтобы в них можно было однозначно найти нужный адрес.
Если нажать на баннере на `(i)`, что пишет?

**Comment by Alex-302** [comment]
Возможно это реклама Facebook AdChoices, и на iOS/DNS её просто так не заблокировать.
Если пользователь не использует FB, то можно добавить в пользовательский фильтр
```
||graph.facebook.com^
```
