### ISSUE TITLE
http://seasonvar.ru - ads

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3996]
Пропущена реклама на странице:
http://seasonvar.ru/serial-14867-Kosti-12-season.html

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21739316/cea5f254-d4a0-11e6-9f5c-0dace09f4d53.png)

</details>

<details>

Application version: 1.1.4.36
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2.1
ID: CD091AEB-37D9-4D82-9D08-DA55D64BF46E

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.4.94 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.15 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.52 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.45.7 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.2 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.72.32 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.72.20 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.69.17 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.68.86 Enabled=YES

</details>

Ticket ID(if exists): 1104812

**Comment by Alex-302** [comment]
Добавил в фильтр Сафари:
```
@@||jsc.marketgid.com/*/seasonvar.ru.*.js
```
Нужно проверить. Жду ответа.
