### ISSUE TITLE
minigames.mail.ru

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardFilters#39965]
Проблема с проникновение рекламы на сайте minigames.mail.ru при включенном Adguard и Tampermonkey с самыми последними обновленными фильтрами. 

Filtering Log прикрепил ниже с описанием системы и прочей инфо.

![111](https://user-images.githubusercontent.com/23212486/64331679-e77c9600-cfdb-11e9-8612-8d18c8688bbc.jpg)

[Filtering log.zip](https://github.com/AdguardTeam/AdguardFilters/files/3578611/Filtering.log.zip)

Operating system:        Windows 10 Home
Browser:                               Chrome Version 76.0.3809.132 (Official Build) (64-bit)
AdGuard version for Chrome:                       Version 3.2.1
Filters enabled:                    AdGuard Base filter, AdGuard Tracking Protection filter, EasyPrivacy, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter
Stealth mode options (Windows only)    Enabled

**Comment by Alex-302** [comment]
@jbionic2016 повторяется ещё? Должно быть чисто.

**Comment by jbionic2016** [comment]
Да, пропало. Причём без всякого TamperMonkey. Подозреваю, что пропало до "завтра" или до понедельника )

**Comment by Alex-302** [comment]
ок, закрываю пока.
