### ISSUE TITLE
http://www.hdkinoteatr.com - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#3997]
Некорректная блокировка на странице:
http://www.hdkinoteatr.com/drama/28701-anomiya.html

При попытки запустить фильм вылетает ошибка и все...решается все путём только отключения фильтрации на этом сайте.

<details>

Application version: 1.1.4.60
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: F1799860-0F7F-46BC-8857-75795095C8C8

Locale: ru
Region: ru

Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.99 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.10 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.46 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.97 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.45.2 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.52 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.72.15 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.71 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.72.16 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.72.4 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.69.1 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.68.70 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.67 Enabled=YES
ID=232 Name="KAD - Przekrety" Version=1.0.0.84 Enabled=YES

</details>

Ticket ID(if exists): 1483289

**Comment by Alex-302** [comment]
Крайне много фильтров. Явно превышен лимит в 50000 правил.
Нужно выключить как минимум

> ID=208 Name="Malware Domains" Version=1.0.72.4 Enabled=YES
> ID=210 Name="Spam404" Version=1.0.1.67 Enabled=YES

Если не поможет, то и эти

> ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.71 Enabled=YES
> ID=207 Name="Adblock Warning Removal List" Version=1.0.72.16 Enabled=YES
> ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
> ID=213 Name="RU AdList: BitBlock" Version=1.0.69.1 Enabled=YES
> ID=212 Name="RU AdList: Counters" Version=1.0.68.70 Enabled=YES
> ID=115 Name="RU AdList" Version=1.0.72.15 Enabled=YES
> ID=232 Name="KAD - Przekrety" Version=1.0.0.84 Enabled=YES
