### ISSUE TITLE
ut-1.alexbranding.com and unitheme.net

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#3998]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:  blocking buttom "Посмотреть ассортимент" button on the banner on:
+ ut-1.alexbranding.com
**(helps disabling Russian filter)**
+ unitheme.net

* **Current behaviour**: 
**(helps disabling Adblock polskie reguły filter)**

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21740404/ff8e5228-d4c1-11e6-9c7e-8826b8271676.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21740408/0b68d456-d4c2-11e6-9da1-d44aadb78285.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21740411/1eca31ca-d4c2-11e6-9820-6161068fa372.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21740414/388420ee-d4c2-11e6-9487-5533408152e3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard filters: | 1,2,3,4,14, Adblock polskie reguły

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1410629

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
> ut-1.alexbranding.com

с русским не повторилось, только с польским.

добавил:
```
ut-1.alexbranding.com,unitheme.net#@#[class^="adv-"]
```

**Comment by vgavrish** [comment]
Проблема на этих сайтах решилась
Но с Adblock polskie reguły проблема также на других сайтах осталась

1) http://test.elton.com.ua/ - http://prntscr.com/dv1n97

2) demo.cs-cart.com :
http://prntscr.com/dv1q3a
http://prntscr.com/dv1q5k
Как повторить:
+ админка наверху справа - перейти в панель администратора
+ далее переходите товары - категории и там есть кнопка + (смотрите скриншоты)

Просьба решить проблему глобально

**Comment by Alex-302** [comment]
1 - сообщил автору польского фильтра
2 - не повторяется
Если он верстает сайт, то лучше называть кнопки именами, которые заведомо не будут блокироваться.

**Comment by vgavrish** [comment]
а у меня 2е повторяется
по верстке передам
