### ISSUE TITLE
lover.ne.kr - Incorrect Blocking

### ISSUE THREAD

**Issue by L4by** [AdguardTeam/AdguardFilters#39995]
***Description***: This site is broken when using adguard base filter (no popup window has shown).
* **Current behaviour**: 
<details><summary>Screenshot:</summary>

![img](https://user-images.githubusercontent.com/27128153/64357775-43790600-d040-11e9-8794-71c8381f6630.png)

</details><br/>

* **Expected behaviour**: 
<details><summary>Screenshot:</summary>

![img2](https://user-images.githubusercontent.com/27128153/64357947-89ce6500-d040-11e9-864c-7f0811bdc654.png)

</details><br/>

***Steps to reproduce the problem***:
This problem has caused by this adguard base filter rule:
`lover.ne.kr#%#//scriptlet("prevent-window-open")`

***System configuration***

Information                            | Value
---                                    | ---
Operating system:                      | Win
Operating system version (Android/iOS) | 10
Browser:                               | Firefox
AdGuard version:                       | 7.2.2910
Filters enabled:                       | List-KR, AdGuard Base Filter, AdGuard Tracking Protection Filter, AdGuard Annoyances Filter, Adblock Warning Removal List
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Hide your search queries, Send DNT header, Remove X-Client-Data header from HTTP requests, Strip URLs of tracking parameters, Self-destruction of third-party cookies (180 minutes)
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Removed the two rules. Did not reproduce an ad popunder.
