### ISSUE TITLE
[iOS Pro] http://www.ixbt.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#3999]
http://www.ixbt.com/

Is it possible to hide the banner on top with the DNS filtering?

![image1](https://cloud.githubusercontent.com/assets/15856304/21741097/e89feb68-d4d4-11e6-9c82-c97106564ff8.PNG)

<details>

eng, spyware, social media, annoyances, russian, mobile ads,  simplified domains, safari. Non-optimized filters, DNS is the standard protection mode, browser - Mercury free for iOS.

**Comment by Alex-302** [comment]
No.
