### ISSUE TITLE
http://www.vop.co.kr/ - incorrect filtering

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4000]
http://www.vop.co.kr/A00001108180.html This link doesn't work well
with Adguard. Reproduced, without Adguard it is full of ads. With Adguard this website doesn't work as it should and looks different.
* **Current behavior**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

(http://prntscr.com/dslrsh Without adguard
http://prntscr.com/dsls5k Without adguard
http://prntscr.com/dslsjz with adguard)

[//]: # (Go to the website with the disabled Adguard, you will see the website full af ads and banners, there is some text in Korean, we can scroll down the website, when we enable Adguard, it changes the interface of the website, it is not possible to scroll it down)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |Android samsung SM-G930L
Browser: | Chrome, Samsung inbuilt browser
Adguard version: | 2.8.76
Filtering quality (Android): | high-speed
HTTPS filtering (Android): |  On (Default)
Adguard filters: |  English filter, Spyware filter, Social media filter, Mobile Ads filter,List-KR

[//]: # (*** 2, 3, 4, 11, 227 English filter, Spyware filter, Social media filter, Mobile Ads filter,List-KR)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(1483135): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Fixed, the user can update filters and report back if it still does not work.
