### ISSUE TITLE
Kodi + IVI plugin issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4006]
Сам KODI:
https://play.google.com/store/apps/details?id=org.xbmc.kodi

Есть жалоба, что работа Adguard мешает плагину IVI:
> Возникла небольшая проблеммка: блокируется просмотр видео в плагине IVI на Kodi 16.1. Выглядит так: видны все фильмы, сериалы, сезоны, описания - но как только нажимаю на просмотр - вылетает ошибка доступа к контенту.

**Comment by Alex-302** [comment]
Не могу найти откуда этот ivi устанавливать. В их репозитории поиск не находит.

**Comment by ameshkov** [comment]
> На 4pda в теме коди этого добра как грязи :) Например в этом репо ivi есть https://raw.githubusercontent.com/seppius-xbmc-repo/ru/master/repository.seppius.zip

**Comment by ameshkov** [comment]
Информация от пользователя:
> У меня регистрации на гитхабе нет, потому тут напишу.
> Проще всего установить репо, а затем плагин ivi, наверное, так:
> Скачать по ссылке архив https://raw.githubusercontent.com/seppius-xbmc-repo/ru/master/repository.seppius.zip
> Затем в Kodi - Система - Дополнения - Установить из файла zip
> Указать путь до этого репо
> Потом Система - Дополнения - Поиск
> вписать ivi 
> Вроде как то так :) 
> Как я понимаю, причина такая - перед просмотром фильмов на ivi показывается реклама, adguard её режет, и до самого фильма дело не доходит.

**Comment by Alex-302** [comment]
Установил. Ко всем материалам доступ запрещён. Отписал на 4pda в личку.
