### ISSUE TITLE
http://m.ensonhaber.com/ - ads

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4007]
http://m.ensonhaber.com/ - missed ad

<details>

![img_0305](https://cloud.githubusercontent.com/assets/23258533/21758713/fe126566-d646-11e6-8a69-5ff945e775c7.png)

</details>

<details>

Application version: 1.1.4.36
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: E35DBB64-01C1-49BC-9831-55192686B73A

Locale: tr
Region: tr

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.4.52 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.96 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.10 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.44 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.97 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.99 Enabled=YES
ID=6 Name="German filter" Version=1.0.29.83 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.93.3 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.9.13 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.47 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.5.69 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.41 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.50 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.99 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.54 Enabled=YES
ID=101 Name="EasyList" Version=1.0.66.11 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.71.96 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.72.10 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.65 Enabled=YES

</details>

Ticket ID(if exists): 1481198

**Comment by Alex-302** [comment]
too many filters
Disable
```
ID=15 Name="Simplified domain names filter" Version=1.0.0.54 Enabled=YES
ID=101 Name="EasyList" Version=1.0.66.11 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.65 Enabled=YES
```
if ads will not blocked, disable unnecessary filters.
