### ISSUE TITLE
http://tula.price.ru/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#4008]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: ads
http://tula.price.ru/mobilnye-telefony/telefony-s-moshhnym-akkumulyatorom/

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21759553/b198f4a0-d64d-11e6-94b2-36085235a68c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard filters: | 1.2,3,4

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1018240

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
