### ISSUE TITLE
https://www.jessblog.fr/wp-admin/ - blocked by the Content blocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4009]
The (public) homepage is fully accessible on https://www.jessblog.fr (or even the http) with Adguard activated.

But the admin page, https://www.jessblog.fr/wp-admin/, is blocked as you can see on the below screenshot.  Safari indicates it cannot open the page. The error message is that the URL has been blocked by a content blocker.

When I define my site in the whitelist, no more issue, but I'm not sure why it has been blocked by default. 

Filters that are activated in my Adguard options:
- filters in English
- filters for spyware
- filters for social network
- filters for mobile advertising 
- Safari filters
- Liste FR

<details>

![image1](https://cloud.githubusercontent.com/assets/15856304/21760071/f0c97f56-d651-11e6-9867-f37b9398da62.png)

![image2](https://cloud.githubusercontent.com/assets/15856304/21760073/f2151974-d651-11e6-9495-5a48d81f27cc.png)

</details>

ID: 1484280

**Comment by Alex-302** [comment]
Try this rule:
```
@@||jessblog.fr/wp-admin/
```

**Comment by Jessblog** [comment]
Hello,
Ok, I'll try, but the main question is still why is it blocked?

**Comment by Alex-302** [comment]
@Jessblog some rule(s) from Liste FR causes it.
