### ISSUE TITLE
http://www.snbforums.com - Missed ad

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4010]
Missed ad on page: http://www.snbforums.com/

It's the tp-link ad on the right side of the page under the share this page section

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/21760353/2648d85a-d654-11e6-9058-27f9f2ada2a5.png)

</details>

<details>

Application version: 1.1.4.36
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2.1
ID: 45857B40-6156-4D84-B8ED-A6C7E3AD1312

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.12 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.1 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.15 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.4 Enabled=YES
ID=101 Name="EasyList" Version=1.0.66.40 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.72.32 Enabled=YES
ID=204 Name="Peter Lowe's list" Version=1.0.2.69 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.68 Enabled=YES

</details>

Ticket ID(if exists): 1484491

**Comment by Alex-302** [comment]
Fixed
