### ISSUE TITLE
englishexercises.org

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#40110]
[https://www.englishexercises.org/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.englishexercises.org/)

![cookie](https://user-images.githubusercontent.com/35470489/64474396-e28a2480-d14a-11e9-80f8-a6d91cb9f51d.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
it must be hidden by `###CookieConsentDiv`, but not blocked. Not reproduced with AdGuard.

**Comment by adranger** [comment]
@Alex-302 The site uses `#cookieconsentdiv` with small letters. You only have the rule `###CookieConsentDiv`.

> Cosmetic filters are CSS selectors, and browsers handle CSS selectors as case-sensitive, as per CSS specs.
https://github.com/uBlockOrigin/uAssets/issues/834#issuecomment-345850338

[cookies_general.txt](https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/sections/cookies_general.txt) already covers all possibilities for similar cases, for example:

`###cookieconsent`
`###cookieConsent`
`###CookieConsent`
`###cookieconsentbar`
`###cookieConsentBar`

**Comment by Alex-302** [comment]
Ok, added new rule, but this element 100% hidden by that rule
![image](https://user-images.githubusercontent.com/8361299/64623015-ed65e300-d3f0-11e9-9e4a-a8ab3f325ce7.png)
