### ISSUE TITLE
hackaday.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#40113]
[https://hackaday.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://hackaday.com/)

![cookie](https://user-images.githubusercontent.com/35470489/64475771-7533bf00-d15d-11e9-8ab6-1f069cceb63a.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by krystian3w** [comment]
Maybe use IDCAC as filterlist?
