### ISSUE TITLE
justwatch.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#40134]
[https://www.justwatch.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.justwatch.com/)

![cookie](https://user-images.githubusercontent.com/35470489/64483348-bb793480-d1d6-11e9-9a96-06092365e4f2.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by BlazDT** [comment]
Cookie not reproduced. Please check @AdamWr

**Comment by adranger** [comment]
@BlazDT  Sorry, the front page doesn't have it. I thought it was going to redirect you to one of the languages:

`.consent-banner`

`https://www.justwatch.com/fi`
`https://www.justwatch.com/fr`
`https://www.justwatch.com/ru`

**Comment by BlazDT** [comment]
Tried a localized version before. On other device reproduced, added rule, thank you.
