### ISSUE TITLE
SBS app doesn't work

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4013]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: The app doesn't work with Adguard

**Current behavior**: 
The app ([link](https://play.google.com/store/apps/details?id=kr.co.sbs.videoplayer)) doesn't work along with ADG, it shows the error message. Disabling the HTTPS filtering doesn't help.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screenshot_20170108-034734](https://cloud.githubusercontent.com/assets/15856304/21762989/3c66fc1a-d664-11e6-9900-2c475410156b.png)

</details>

**Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![screenshot_20170108-034804](https://cloud.githubusercontent.com/assets/15856304/21762994/45867474-d664-11e6-81f8-0f6989f7d228.png)

</details>

***Steps to reproduce the problem***:

Enable Adguard, make sure to be subscribed to the filters specified in the end of the task and just open the app.

***System configuration***

Information | value
--- | ---
Operating system: | Android 7.0, Samsung SM-G930L
Adguard version: | 2.8.76
Adguard mode (Android): | VPN
Filtering quality (Android): | SPEEDY
HTTPS filtering (Android): |  On (Default mode)
Adguard filters: | 2, 3, 4, 11, 227

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1483135, you'll find logs there

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Should be fixed now, the user can update filters and report back if it still does not work.
