### ISSUE TITLE
cafe.naver.com - no assistant

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4014]
http://cafe.naver.com/ - no assistant 

Same in all Naver cafe sites

http://prntscr.com/dtbqoa

<details>

Os version: Microsoft Windows NT 10.0.14393.0
Dot .net version: 2.0; 3.0; 3.5; 4.0 Client Profile; 4.0 Full Profile;
ApplicationId: e6f5c573b18943ee97789c1ea6ab5ebf
Language: ko
AppVersion: 6.1.298.1564
Main settings: 
Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:10 Name: Filter unblocking useful ads Url: http://adguard.com/ru/filter-rules.html?id=10
FilterId:227 Name: List-KR Url: https://raw.githubusercontent.com/SlowMemory/List-KR/master/filter.txt
FilterId:0 Name: User filter Url: no_url
Filtering Mode: Driver
Driver Type: Wfp
Ads Blocked: 224112, Trackers Blocked: 15943
Filtering Mode: Driver
Application lifetime: 9.13:54:45.4784562
HTTPS filtering enabled: True
Do not filter EV: False
Ad Blocker enabled: True
Browsing Security enabled: True
Parental Control enabled: False
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": false,
  "BlockWebRtc": false,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"

</details>

Ticket ID(if exists): 1477581

**Comment by Alex-302** [comment]
Not reproduced
http://i90.fastpic.ru/big/2017/0110/cd/40507900c0a590d08bced1bed0740bcd.jpg
Check in another browser.
