### ISSUE TITLE
http://www.elahmad.com/ - annoyance/anti-adblocker

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4015]
http://www.elahmad.com/ - annoyance/anti-adblocker

<details>

![image1 2](https://cloud.githubusercontent.com/assets/23258533/21765451/aad248a0-d671-11e6-927f-e8533769fce6.png)

</details>

<details>

Application version: 1.1.4.36
Application lifetime: 2016-12-23 00:44:58 +0000

Device: iPhone
Platform: iOS
OS: 10.1.1
ID: 02E6A45E-7536-4A72-870E-5DF4A39B834E

Locale: en
Region: gb

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.22 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.1 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.15 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.54 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.4 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.58 Enabled=YES
ID=101 Name="EasyList" Version=1.0.66.45 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.72.35 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.66.46 Enabled=NO
ID=122 Name="Fanboy's Annoyances" Version=1.0.66.66 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.72.49 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.71.34 Enabled=NO
ID=210 Name="Spam404" Version=1.0.1.68 Enabled=NO

</details>

Ticket ID(if exists): 1155100

**Comment by Alex-302** [comment]
try to disable
```
ID=15 Name="Simplified domain names filter" Version=1.0.0.58 Enabled=YES
ID=101 Name="EasyList" Version=1.0.66.45 Enabled=YES - unnecessary, when English filter is enabled
ID=118 Name="EasyPrivacy" Version=1.0.72.35 Enabled=YES
```
