### ISSUE TITLE
http://ofx.xyz/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#4016]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: when you click on background, open another site 
http://ofx.xyz/

<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21766155/67ffc71a-d675-11e6-801a-28b1410684ab.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard filters: | 1,2,3,4,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1315636

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Поправил.
