### ISSUE TITLE
Block all autoplaying video CDNs, preferably as their own annoyance category.

### ISSUE THREAD

**Issue by PaulBags** [AdguardTeam/AdguardFilters#40177]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)
Not blocking any auto playing videos.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](N/A)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)
There should be an option to nuke all video CDNs from orbit.

<details><summary>Screenshot:</summary>

![image](N/A
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)
Exist.

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)
AdGuard Base filter,AdGuard Turkish filter,AdGuard French filter,AdGuard German filter,ABPindo,EasyList China

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win10
Browser:                               | Firefox
AdGuard version:                       | 3.9.1
AdGuard DNS:                           | What?
Stealth mode options (Windows only)    | Never seen it or heard of it
Helpdesk ID (if exists):               | No

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
Feature request.
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not a good idea. Better install autoplay blocking browser extension.
