### ISSUE TITLE
vk.com - can't play suggested and popular music

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#4017]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

Doesn't load only suggested and popular music with **English filter** (should be only on Russian language on the site).

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21766846/6f5a7a10-d679-11e6-883a-4c5516c6ca20.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21766967/11a49e0e-d67a-11e6-8031-b1a5a650c9e5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | off
Adguard filters: | English

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Исключение помогает?
У меня там постоянно ошибка и музыка не стартует даже без Адгарда

![image](http://i89.fastpic.ru/big/2017/0110/94/5b34e1ba178bbc749d47d0ea1a535c94.jpg)

**Comment by vgavrish** [comment]
да, исключения помогали, сейчас опять все норм
как-то переодически случается.

**Comment by Alex-302** [comment]
Скорее всего у них проблема была. Сейчас у меня работает, и ошибок в консоли нет.
