### ISSUE TITLE
Add to filter rules #Germany

### ISSUE THREAD

**Issue by iPlachetka** [AdguardTeam/AdguardFilters#4018]
payback.de###skyscraper
rapid-search-engine.com###rightpanel
sourceforge.net##.truste_box_overlay
sourceforge.net##.truste_box_overlay
*###pb_block
chip.de##.NewsArticle__Chapter.LikeBtn, .mt-md, .is-shown, .is-animated
finanzen100.de##.slot-vertise.SMARTPHONE_BANNER_TOP, .TABLET_BANNER_TOP, .DESKTOP_BANNER_TOP
finanzen100.de###section-uebersicht > div.grid.page__section__items.grid--columns > div.grid__sidebar:last-child
finanzen100.de##.grid__sidebar
finanzen100.de###banner_336761415
finanzen100.de##.slot-vertise.TABLET_BANNER_ANY, .DESKTOP_BANNER_SINGLE_ANY, .DESKTOP_BANNER_ALL_ANY
finanzen100.de###section-partner
finanzen100.de##.slot-vertise.SMARTPHONE_FOOTER_SINGLE_ANY, .TABLET_FOOTER_SINGLE_ANY, .DESKTOP_FOOTER_SINGLE_ANY, .DESKTOP_FOOTER_ANY
finanzen100.de##.slot-vertise.SMARTPHONE_FOOTER_SINGLE_ANY, .TABLET_FOOTER_SINGLE_ANY, .DESKTOP_FOOTER_SINGLE_ANY, .DESKTOP_FOOTER_ANY
huffingtonpost.de##.adsbygoogle
huffingtonpost.de##.adsbygoogle
huffingtonpost.de##.ad_spot
huffingtonpost.de##.likegate-overlay-hp.hpgate
huffingtonpost.de##.likegate-dimmer
huffingtonpost.de##.fb_ltr
huffingtonpost.de##.shares.group
huffingtonpost.de###conversations-huffpost-web
huffingtonpost.de###social-subscribe-search

[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS / Android / Linux
Browser: | 
Adguard version: | 
Adguard driver (Windows): | WFP / TDI
Adguard mode (Android): | VPN / Proxy(manual/auto)
Filtering quality (Android): | High-quality / high-speed / simplified
HTTPS filtering (Android): |  On (Default/Blacklist mode) / Off
Simplified filters(iOS) | On / Off
Adguard DNS: | None / Default / Family Protection
Stealth mode options(Windows) | 
Adguard filters: | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
As I see, these rules are not only for ads.
Please sort them by purpose and I will add them to our filters.
