### ISSUE TITLE
javgo.me - missed

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdguardFilters#4019]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
* **Current behaviour**: 
Many popups and redirections when opening any page or click any object on javgo.me (note: p.o.r.n site)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:
Just visit javgo.me and open a page or click an object (e.g. play a video)

***System configuration***

Information | value
--- | ---
Operating system: | Android (haven't tried on Windows)
Browser: | Chrome
Adguard version: | 2.8
Adguard mode (Android): | VPN
Filtering quality (Android): | high-speed
HTTPS filtering (Android): |  On
Adguard DNS: | None
Adguard filters: | English, Spyware, Social, Annoyances, Mobile, ABPVN

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed

**Comment by snhv** [comment]
I'm sorry but not yet fully resolved. Browsing the site a little bit (maybe you can do that later at home), and you'll see it still pops up and redirects.

**Comment by Alex-302** [comment]
@snhv 
```
Filtering quality (Android):	high-speed
```
turn it to High Quality. JS rules are not applied with high-speed mode

**Comment by snhv** [comment]
It's fixed now, whether High Quality or not. I guess last time I tried, your fix hadn't reached me yet. Thank you.
