### ISSUE TITLE
teletoonplus.pl

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#40202]
Details: Windows 10, Edge Chromium Stable (EN), Adguard Extension
Site: https://www.teletoonplus.pl/
Ad banner NC+ (CANAL+) on top site.
![teletoonplus](https://user-images.githubusercontent.com/16944478/64555155-09a84800-d33d-11e9-9466-82852983bd7d.png)

Traditional my settings (filters without obsolete/problematic and without ads promotion acceptable), stealth mode turned.

**Comment by krystian3w** [comment]
```
||services.canalplus.pl/belka/$subdocument,domain=teletoonplus.pl
teletoonplus.pl###nctop
```

Czyli przebudowali to.

**Comment by krystian3w** [comment]
Dźwigacz w górę też dalej działa:

`teletoonplus.pl#?#body > div:first-of-type:has(#nctop)`

---

AG Base obecnie miałoby tylko likwidowanie luki bez usuwania reklamy.

**Comment by seba2282** [comment]
> ||services.canalplus.pl/belka/$subdocument,domain=teletoonplus.pl
> ! */belka/$subdocument,domain=teletoonplus.pl
> teletoonplus.pl###nctop

Sprawdziłem, to ukrywa tą belkę.

**Comment by AdamWr** [comment]
Poprawione, aktualizacja powinna być dostępna za około 1-2 godziny.

**Comment by seba2282** [comment]
Dzięki.
