### ISSUE TITLE
http://www.argos.co.uk - Incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4020]
Incorrect blocking on page:
http://www.argos.co.uk/m/static/Browse/ID72/33016251/c_1/1%7Ccategory_root%7CTechnology%7C33006169/c_2/2%7C33006169%7CVideo+games+and+consoles%7C33008137/c_3/3%7C33008137%7CPS4%7C37328180/c_4/4%7C37328180%7CPS4+games%7C37328859.htm

The mobile version of argos.co.uk doesn't properly load unless I disable the Adguard content blocker. If I then hold down the refresh button and choose 'Reload without content blockers' it loads fine. 
> > 
<details>

![image1 3](https://cloud.githubusercontent.com/assets/23258533/21794725/8e8b5e18-d705-11e6-959b-6a3ea4f3f903.png)

</details>

<details>

![image2](https://cloud.githubusercontent.com/assets/23258533/21794730/96952d8c-d705-11e6-8731-0d96de7bc679.png)

</details>

<details>

Application version: 1.1.4.60
Application lifetime: 1970-01-01 00:00:00 +0000
Device: iPhone
Platform: iOS
OS: 10.2
ID: E93FE080-56A8-4F7E-9554-0EEA4AF88CEA

Locale: en
Region: gb
Optimazed enabled: NO

Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.13 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.1 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.15 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.4 Enabled=YES

</details>

Ticket ID(if exists): 1484526

**Comment by Alex-302** [comment]
fixed
