### ISSUE TITLE
http://mangastream.com/ - Incorrect blocking 

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4021]
Incorrect blocking on page:
http://mangastream.com/

The blank bar under where is says "show new releases" won't go away. I even tried manually blocking it but it didn't go away. 

<details>

![img_0065](https://cloud.githubusercontent.com/assets/23258533/21795393/4e0463b2-d70a-11e6-8d3a-51f8cb0be4e7.png)

</details>

<details>

Application version: 1.1.2.56
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2.1
ID: E80A26E5-F1F9-4209-BFFF-22C428F1292F

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.25 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.1 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.88 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.8.55 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.4 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.51 Enabled=NO
ID=122 Name="Fanboy's Annoyances" Version=1.0.66.67 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.72 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.72.50 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=204 Name="Peter Lowe's list" Version=1.0.2.69 Enabled=YES

</details>

Ticket ID(if exists): 570038

**Comment by Alex-302** [comment]
fixed
