### ISSUE TITLE
http://radikal.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4022]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

http://radikal.ru/ - missed ad on the page

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21796800/babd00c8-d713-11e6-83ec-15c2a8f3a25c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.1.258.1302
Adguard driver (Windows): | TDI
Stealth mode options(Windows) | Yep
Adguard filters: | 2 3 4 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1059796

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
