### ISSUE TITLE
http://latitu.ru/ - photo upload is blocked

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4023]
http://latitu.ru/ 
Подать объявление - адрес - параметры - описание 
вводим данные в поля со звездочкой
в разделе описание блокируется загрузка фотографий 
Adguard 1.4.0 - зависает на 90%
<details>

![2017-01-10 11 38 46](https://cloud.githubusercontent.com/assets/23637588/21799436/4f47eaf8-d72a-11e6-85fb-0f8988b2b2e2.png)

</details>

Browser extension - выдает ошибку 
<details>

![2017-01-10 11 46 40](https://cloud.githubusercontent.com/assets/23637588/21799466/789b6a60-d72a-11e6-8eb3-3e09888496e9.png)

</details>

похоже английский фильтр ломает

**Comment by Alex-302** [comment]
Добавил:
```
@@||latitu.ru^*/advert_$xmlhttprequest
```
