### ISSUE TITLE
my-hit.org - missed ad

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4024]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

**Missed banner**

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](
![4xpytei0yj4](https://cloud.githubusercontent.com/assets/22892774/21811841/be52aa62-d759-11e6-8ac0-8f1ff5c997d0.jpg)

)
</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Chrome
Adguard version: | 2.8.76
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On 
Adguard filters: | 1,2,3,4,11,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 677335 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced even without AG.
Please ask for HAR filу and HTTP log(with time).
