### ISSUE TITLE
Yandex search ads

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4025]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

There are some ads of Yandex in Google search app. The issue disappears after the user reinstalls HTTPS certificate. The ads are always back. Never-ending reinstallation of HTTPS certificate is not good for the user.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
<http://prntscr.com/dtvnp5>

A user expects these ads to disappear without reinstallation of HTTPS-certificate**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Information | value
--- | ---
Operating system: |samsung SM-J510FN Android6.0.1 
Adguard version: | 2.8.76
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default/Blacklist mode)
Adguard filters: | 2, 3, 4, 14, 1, 11, 211 

[//]: # (***English filter,Russian filter,Spyware filter, Social media filter, Mobile Ads filter, Annoyances filter, Anti-Adblock Killer | Reek, ABPVN List)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID (1150428)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
This app was never filtered. It is absolutely encrypted.
