### ISSUE TITLE
booksdeity.com - anti-adblocker

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4026]
on the main page too
or any other: http://booksdeity.com/2016/12/31/best-holiday-cookies-by-marcy-goldman-epub/
<details>

![2017-01-10 20 15 11](https://cloud.githubusercontent.com/assets/23637588/21816560/915c6ad0-d771-11e6-9d9a-0ce1bda406dc.png)

</details>

**Comment by Alex-302** [comment]
fixed
