### ISSUE TITLE
novyjgod.com - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4027]
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](
![screen shot 2017-01-10 at 11 17 54 pm](https://cloud.githubusercontent.com/assets/22892774/21825125/173c50ca-d78b-11e6-9ce6-44c75dc34342.png)
)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS
Browser: | Chrome, Safari
Adguard version: | 1.4.0; 6.1.298.1564 
Adguard filters: | http://prnt.sc/dtzz7e

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID:  1485765

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
