### ISSUE TITLE
tapatalk-cdn.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#40284]
Tapatalk now has a CDN (`tapatalk-cdn.com`) for forums to display their mobile app banner. Example page: [https://forum.outerspace.com.br/index.php?threads/nintendo-switch-t%C3%B3pico-oficial-do-vai-falir.430541/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://forum.outerspace.com.br/index.php?threads/nintendo-switch-t%C3%B3pico-oficial-do-vai-falir.430541/)

![tapatalk](https://user-images.githubusercontent.com/35470489/64704760-2bace200-d485-11e9-954d-c8e72499f965.png)

Adguard Base + Annoyances + Mobile + Portuguese + Russian + Social + Spyware
uBlock Origin
Mozilla/5.0 (Android 4.4.2; Mobile; rv:66.0) Gecko/66.0 Firefox/66.0

**Comment by adranger** [comment]
@Alex-302 can't you add their domain to the `Annoyances` list? Many forums connect to it. [http://forumchaves.com.br/viewtopic.php?f=47&t=13550&start=105](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://forumchaves.com.br/viewtopic.php?f=47&t=13550&start=105)

**Comment by Alex-302** [comment]
@adranger `.TapatalkBanner_Container`?

**Comment by Alex-302** [comment]
Need few examples.

**Comment by adranger** [comment]
Examples of forums that connect to `groups.tapatalk-cdn.com/static/js/smartbanner` on mobile browsers (some load it only after you browse to another page):

[http://forumchaves.com.br/viewtopic.php?f=47&t=13550&start=105](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://forumchaves.com.br/viewtopic.php?f=47&t=13550&start=105)
[https://forum.atelevisao.com/forum/21-audi%C3%AAncias/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://forum.atelevisao.com/forum/21-audi%C3%AAncias/)
[https://forum.macmagazine.com.br/topic/196924-ajudem-me/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://forum.macmagazine.com.br/topic/196924-ajudem-me/)
[https://www.rokslide.com/forums/forums/general-discussion-forum.92/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.rokslide.com/forums/forums/general-discussion-forum.92/)
[https://thefragtank.ca/community/forums/general-reef-discussion.495/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=[https://thefragtank.ca/community/forums/general-reef-discussion.495/)
[https://www.bmwland.org.uk/index.php?forums/categories-and-forums.46/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.bmwland.org.uk/index.php?forums/categories-and-forums.46/)
