### ISSUE TITLE
sixx.de - Ad - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4032]
***Site***: http://www.sixx.de/ and http://www.sixx.de/tv/enie-backt/video/sweet-easy-christmas/521-sweet-easy-christmas-enies-adventsparty-ganze-folge and http://www.sixx.de/tv/salem/video/21-staffel-2-episode-1-der-hexenkrieg-brennt-ganze-folge
***Description***: Ad leftover at the top. Ad before video. Social widget. Ad recommendations below video.

<details>
<summary>Screenshot</summary>

***http://www.sixx.de/:***

![image](https://cloud.githubusercontent.com/assets/10995998/21829999/1b614304-d79a-11e6-909c-369952b24f4c.png)

***http://www.sixx.de/tv/enie-backt/video/sweet-easy-christmas/521-sweet-easy-christmas-enies-adventsparty-ganze-folge (Social widget and ad before video):***

![image](https://cloud.githubusercontent.com/assets/10995998/21829972/e491ed92-d799-11e6-8f30-f37bb37412c2.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21829965/d9fb81cc-d799-11e6-8066-665470fe276a.png)

***http://www.sixx.de/tv/salem/video/21-staffel-2-episode-1-der-hexenkrieg-brennt-ganze-folge:***

![image](https://cloud.githubusercontent.com/assets/10995998/21830029/47c24baa-d79a-11e6-93a4-4f77f1b7e265.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.5.51
Spyware filter | 1.0.10.13
Social media filter | 1.0.16.29
Annoyances filter | 1.0.8.68
German filter | 1.0.30.15
Mobile ads filter | 1.0.6.60
Safari filter | 1.0.2.8

**Comment by Alex-302** [comment]
disable
`@@||sixx.de^$genericblock,generichide`
and add
```
@@||sixx.de^$generichide
sixx.de###ad-fullbanner-outer
sixx.de##.social-wrapper
```

**Comment by danidoedel** [comment]
These rules block everything mentioned above:
```
@@||sixx.de^$generichide
sixx.de###ad-fullbanner-outer
sixx.de##.social-wrapper
sixx.de##div[data-position="share_video_bottom"]
```
But there is still some leftover in the sidebar:

(http://www.sixx.de/tv/mein-perfektes-hochzeitskleid/video/79-staffel-7-episode-9-once-upon-a-bride-ganze-folge:)

![image](https://cloud.githubusercontent.com/assets/10995998/21962736/8c5c3bcc-db2d-11e6-868b-f5d344bbcaca.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21962775/50c968c2-db2e-11e6-8dfa-11faab18f2e1.png)

(http://www.sixx.de/video:)

![image](https://cloud.githubusercontent.com/assets/10995998/21962784/69aebea0-db2e-11e6-85b0-18d46e77e7ff.png)

(http://www.sixx.de/tv/hart-of-dixie/video/staffel-2/217-preview-staffel-2-folge-17-trennungsschmerz-clip:)

![image](https://cloud.githubusercontent.com/assets/10995998/21962851/6038222a-db2f-11e6-978a-dfca80c78947.png)

**Comment by Alex-302** [comment]
Check these rules, and adblock detection in the player
```
sixx.de##.view-adsbygoogle
sixx.de##.view-likebox
sixx.de##section[data-track$="cont:Facebook"]
```

**Comment by Alex-302** [comment]
> @@||sixx.de^$generichide
> sixx.de###ad-fullbanner-outer
> sixx.de##.social-wrapper
> sixx.de##div[data-position="share_video_bottom"]

added

**Comment by danidoedel** [comment]
@Alex-302 Yep these rules are perfect. And I don't have any adblock detection :)

But on the main page (http://www.sixx.de/) there is still some Facebook leftover:

![image](https://cloud.githubusercontent.com/assets/10995998/22065513/e30f14be-dd88-11e6-905b-ca177a8f5308.png)

**Comment by Alex-302** [comment]
added
sixx.de###aside-zone section[data-track$="Facebook"]
sixx.de##.view-adsbygoogle
