### ISSUE TITLE
prosieben.de - Ad leftover - Ad - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4033]
***Site***: http://www.prosieben.de/ and http://www.prosieben.de/tv/gotham/video/220-staffel-2-episode-20-entfesselt-ganze-folge and http://www.prosieben.de/tv/die-promi-darts-wm-2017/video/11-die-promi-darts-wm-ganze-folge
***Description***: Ad leftover at the top. Ad before video. Social widget. Ad recommendations below video.

<details>
<summary>Screenshot</summary>

***http://www.prosieben.de/:***

![image](https://cloud.githubusercontent.com/assets/10995998/21830066/a91b2ed0-d79a-11e6-8880-26922230c6fb.png)

***http://www.prosieben.de/tv/gotham/video/220-staffel-2-episode-20-entfesselt-ganze-folge (Social widget and ad before video):***

![image](https://cloud.githubusercontent.com/assets/10995998/21830152/14d1ac44-d79b-11e6-964b-776ed75a8cfa.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21830138/0dbba8f6-d79b-11e6-96d8-ed791f1b4efa.png)

***http://www.prosieben.de/tv/die-promi-darts-wm-2017/video/11-die-promi-darts-wm-ganze-folge:***

![image](https://cloud.githubusercontent.com/assets/10995998/21830180/380d0212-d79b-11e6-9ea3-1acae6080d61.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.5.51
Spyware filter | 1.0.10.13
Social media filter | 1.0.16.29
Annoyances filter | 1.0.8.68
German filter | 1.0.30.15
Mobile ads filter | 1.0.6.60
Safari filter | 1.0.2.8

**Comment by danidoedel** [comment]
Rules from #4032 and #4033 should apply for http://www.kabeleins.de/ and http://www.sat1.de/ and http://www.prosiebenmaxx.de/ too (Same company).

**Comment by Alex-302** [comment]
disable
```
@@||prosieben.de^$genericblock,generichide
@@||prosiebenmaxx.de^$genericblock,generichide
```
and add
```
```
@@||prosieben.de^$generichide
@@||prosiebenmaxx.de^$generichide
prosieben.de###ad-fullbanner-outer
prosieben.de##.social-wrapper
prosieben.de##div[data-position="share_video_bottom"]

```

**Comment by danidoedel** [comment]
These rules will fix the issues mentioned above:

```
@@||prosieben.de^$generichide
@@||prosiebenmaxx.de^$generichide
@@||kabeleins.de^$generichide
@@||sat1.de^$generichide

prosieben.de,kabeleins.de,sat1.de,prosiebenmaxx.de###ad-fullbanner-outer
prosieben.de,kabeleins.de,sat1.de,prosiebenmaxx.de##.social-wrapper
prosieben.de,kabeleins.de,sat1.de,prosiebenmaxx.de##div[data-position="share_video_bottom"]
```

This rule can then be removed: `sat1.de##body #ad-fullbanner-outer`

There is then still some ad leftover in the sidebar same like in #4032

**Comment by Alex-302** [comment]
The rules added.
