### ISSUE TITLE
ray-ban.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4034]
***Site***: http://www.ray-ban.com/germany/ and http://www.ray-ban.com/germany/sonnenbrillen/RB4246%20MALE%20001-clubround%20at%20collection-black/8053672692440?category_Id=332940
***Description***: Cookie notice at the bottom left. Newsletter overlay.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21830402/ba578214-d79c-11e6-8ace-b43aed742d69.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21830415/d1ddc862-d79c-11e6-94ec-cde961efa854.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.5.51
Spyware filter | 1.0.10.13
Social media filter | 1.0.16.29
Annoyances filter | 1.0.8.68
German filter | 1.0.30.15
Mobile ads filter | 1.0.6.60
Safari filter | 1.0.2.8

**Comment by danidoedel** [comment]
@seanl-adg 
Cookie notice not blocked.

```html
<div id="rb_cookieBox" class="" style="bottom: 70px;">
	<div class="cbox_inner">
		<p></p>
		<p>Diese Seite benutzt Cookies, die Ihnen ein optimales Einkaufserlebnis ermöglichen. <span class="js-textClose">Ich stimme der Nutzung von Cookies zu</span> <a href="/germany/cookies-policy">Mehr Info.</a></p>
	</div>
	<a class="buttonClose">
	<img src="/Views/GenericContent/toonh2015/toonstrap/close1_edit.png">
	</a>
</div>
```

**Comment by Alex-302** [comment]
fixed
