### ISSUE TITLE
instagram.com - app banner

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#40381]
[https://www.instagram.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.instagram.com/)

![app banner](https://user-images.githubusercontent.com/35470489/64804426-3048c780-d565-11e9-88f8-7836385c50de.png)

Adguard Base + Annoyances + Mobile + Portuguese + Russian + Social + Spyware
uBlock Origin
Mozilla/5.0 (Android 4.4.2; Mobile; rv:66.0) Gecko/66.0 Firefox/66.0

**Comment by krystian3w** [comment]
`###react-root > section > main + footer + div:has(a[href^="https://play.google.com/store/apps/details?id=com.instagram.android"])`

Should works and no needed xpath.

**Comment by krystian3w** [comment]
or for Content blocker / iOS:

`###react-root > section > main + footer + div.MFkQJ`
