### ISSUE TITLE
https://www.yandex.ru - ads

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4038]
https://www.yandex.ru/search/touch/?text=%D1%81%D0%B2%D0%B5%D1%82%D0%BE%D0%B4%D0%B8%D0%BE%D0%B4%D0%BD%D1%8B%D0%B5%20%D1%81%D0%B2%D0%B5%D1%82%D0%B8%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA%D0%B8%20led%20%D0%BA%D1%83%D0%BF%D0%B8%D1%82%D1%8C%20&lr=50&redircnt=1483953805.1

Не могу заблокировать контекстную рекламу в поисковике

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/21841605/96c44ea0-d7eb-11e6-8823-784dc4df7326.png)

</details>

<details>
Application version: 1.1.4.60
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 5BF31259-6E9D-4572-A1B4-78843C80A247

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.28 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.2 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.17 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.56 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.97 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.45.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.4 Enabled=YES

</details>

Ticket ID(if exists): 1485053

**Comment by Alex-302** [comment]
Я тоже:( На iOS доступные возможности фильтрации крайне скудны.
