### ISSUE TITLE
Turktorrent First Page Click Ads

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardFilters#4039]
Hi
When you enter this website; then you click anywhere in the website, one ad page will open. But only first click.

Can you block that?

Screenshot: i think it is not necessary if you enter this page and click anywhere you can see your own eyes :)

 http://turktorrent.cc/

***System configuration***

Information | value
--- | ---
Operating system: |
Windows
Browser: chrome
Adguard version: last version:)
Adguard driver (Windows): | WFP /
Adguard DNS: | None 
Adguard filters: |  ENGLİSH, SPYWARE, SOCIAL MEDIA, Annoyances, Mobile Ads, SAFARI, TURKISH 

Ticket ID(if exists): ???

@alex-302 is it okay with that subject and topic? Please fix it.

**Comment by Alex-302** [comment]
Which Adguard version? I can't reproduce this issue.

**Comment by tagataho** [comment]
@alex-302 version 1.1.4

**Comment by tagataho** [comment]
@alex-302 version 1.1.4

**Comment by Alex-302** [comment]
@tagataho What about remote access?(TeamViewer)

**Comment by tagataho** [comment]
@alex-302 do you want access to my pc via TeamViewer? Did i understand true?

**Comment by Alex-302** [comment]
@tagataho indeed. Or to virtual PC.
