### ISSUE TITLE
Bittorrent app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4040]
**http://www.bittorrent.com/**

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21851452/d91b770c-d817-11e6-980d-9fe72cdf63ae.png)

![image](https://cloud.githubusercontent.com/assets/15856304/21851452/d91b770c-d817-11e6-980d-9fe72cdf63ae.png)

</details>
<details>

Win 10, WFP, Stealth mode on basic settings. Russian, English, Social media, Spyware, Annoyances.

**Comment by Alex-302** [comment]
Ads are blocked on my end.
User can completely disable them:
<details>

![image](http://imagizer.imageshack.com/img922/631/gVFod4.png)
</details>
Enter `offer` to search string in settings and switch  all `true` to `false`
