### ISSUE TITLE
tunein.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#40424]
[https://tunein.com/podcasts/Electronic-Garage/Dub-City-Steppers-p395036/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://tunein.com/podcasts/Electronic-Garage/Dub-City-Steppers-p395036/)

On the desktop:

![tune3](https://user-images.githubusercontent.com/35470489/64871346-6fd1eb00-d61b-11e9-82b5-138904ed0c4d.png)

When you open the mobile version of the site:

![tune1](https://user-images.githubusercontent.com/35470489/64870874-7ca20f00-d61a-11e9-95eb-535fbebe899c.png)

Then after you press the play button:

![tune2](https://user-images.githubusercontent.com/35470489/64870906-8e83b200-d61a-11e9-9ed4-8d4e2f790ec4.png)

Adguard Base + Annoyances + Mobile + Portuguese + Russian + Social + Spyware
uBlock Origin
Mozilla/5.0 (Android 4.4.2; Mobile; rv:66.0) Gecko/66.0 Firefox/66.0

**Comment by Alex-302** [comment]
It is dangerous to block these popups, ther attributes are very similar.
