### ISSUE TITLE
http://kinomonitor.ru/?m=off - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4043]
http://kinomonitor.ru/?m=off

![image](https://cloud.githubusercontent.com/assets/15856304/21852501/f663a056-d81b-11e6-9e43-82a5c756aef4.png)

<details>

Reproducible on Mac, Win, Android etc. Basic filters

**Comment by Alex-302** [comment]
fixed

**Comment by vgavrish** [comment]
На Андроиде проблема сохранилась
Лог время 20:10
[debug (20).txt](https://github.com/AdguardTeam/AdguardFilters/files/705862/debug.20.txt)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21954195/66611d46-da53-11e6-9ccb-fbf3859cb394.png)


proxyMode" : false,
tatisticsInfo" : "Blocked threats:10; Blocked banners:95830; Traffic saved:2500839424;",
  "sslMitmConfiguration" : "{\"mitmListMode\":\"WHITELIST\",\"mitmList\":\"1024 domains\",\"certificateInstalledToSystemStorage\":null}",
  "versionName" : "2.8.76",
  "enabledFilterIds" : [ 2, 3, 4, 1, 11 ],
  "filteringQuality" : "FULL",

**Comment by Alex-302** [comment]
Не открывается у меня.

**Comment by evgeniy-ADG** [comment]
У меня на Андроид все чисто

**Comment by Alex-302** [comment]
У меня везде чисто. Не уточнял, как у юзера?
