### ISSUE TITLE
computerforum.de - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4046]
***Site***: https://www.computerforum.de/
***Description***: Social widget leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21858398/3a413d26-d829-11e6-8c1d-1eafb0cbcaf4.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.5.59
Spyware filter | 1.0.10.14
Social media filter | 1.0.16.35
Annoyances filter | 1.0.8.72
German filter | 1.0.30.19
Mobile ads filter | 1.0.6.60
Safari filter | 1.0.2.8

**Comment by Alex-302** [comment]
Added to Social filter
```
computerforum.de##.sharePage
```
