### ISSUE TITLE
eforum.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4047]
***Site***: http://www.eforum.de/
***Description***: Cookie notice at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21858539/c79e5424-d829-11e6-914e-1decafa43310.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.5.59
Spyware filter | 1.0.10.14
Social media filter | 1.0.16.35
Annoyances filter | 1.0.8.72
German filter | 1.0.30.19
Mobile ads filter | 1.0.6.60
Safari filter | 1.0.2.8

**Comment by seanl-adg** [comment]
Can't access the site.

**Comment by danidoedel** [comment]
@seanl-adg 
That's the html code of the cookie bar if that helps:

```html
<div id="cbar" class="bottom">
	<p>Wir verwenden Cookies, um Inhalte und Anzeigen zu personalisieren, Funktionen für soziale Medien anbieten zu können und die Zugriffe auf unsere Website zu analysieren. Außerdem geben wir Informationen zu Ihrer Nutzung unserer Website an unsere Partner für soziale Medien, Werbung und Analysen weiter. <a rel="nofollow" href="/threads/9900-impressum/#cookies">Details ansehen</a><span class="en">schließen</span></p>
</div>
```

**Comment by Alex-302** [comment]
added
```
eforum.de###cbar
```
