### ISSUE TITLE
vwcorrado.de - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4048]
***Site***: https://www.vwcorrado.de/forum/showthread.php?t=148539
***Description***: Ad leftover in forums. Social widget at the bottom of forums.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21858628/2bb6bcf8-d82a-11e6-8726-e1097b6556a4.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21858695/5cccca30-d82a-11e6-9dcf-74c2398ae963.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.5.59
Spyware filter | 1.0.10.14
Social media filter | 1.0.16.35
Annoyances filter | 1.0.8.72
German filter | 1.0.30.19
Mobile ads filter | 1.0.6.60
Safari filter | 1.0.2.8

**Comment by Alex-302** [comment]
Added
```
##a[target="socialbookmark"] 
vwcorrado.de##div[id^="edit"] > div.vbmenu_popup+table[style="margin-top:6px;"]
```

**Comment by danidoedel** [comment]
@Alex-302 That social widget leftover is still there for me:
![image](https://cloud.githubusercontent.com/assets/10995998/22068925/d93c8850-dd96-11e6-8e48-85b3edd2c5af.png)

**Comment by Alex-302** [comment]
for user filter
```
vwcorrado.de##.page[style="width:99%; text-align:left"] > div[style="padding:0px 2px 0px 2px"] > table[width="100%"][align="center"][-ext-has="td.thead:contains(Lesezeichen)"]
```
