### ISSUE TITLE
geekwire.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#40496]
[https://www.geekwire.com/2019/nintendo-dominates-game-sales-amazon-switch-popularity-continues/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.geekwire.com/2019/nintendo-dominates-game-sales-amazon-switch-popularity-continues/)

Email subscription annoyance and Reddit sharing button.

![annoyance](https://user-images.githubusercontent.com/35470489/64910952-4b950d80-d6f2-11e9-9bf0-e294ba552a1f.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by krystian3w** [comment]
Fanboy remove reddit.
