### ISSUE TITLE
soriaudio.com - Error when Eng filter is enabled

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4051]
Screenshot:
http://prnt.sc/dulp35

***Steps to reproduce the problem***:

1) Go to https://www.soriaudio.com/index.php?mid=m_eqp&pageNum=62&subNum=108
2) Enable English filter
3) The Assistant disappears + error message

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS / Windows 
Browser: | Chrome
Adguard version: | 1.4.0; 6.1.298.1564

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1486330

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@seanl-adg  Sugested rules:
```
@@||soriaudio.com/page/banner.php?mid=m_eqp$domain=soriaudio.com - for Eng
||soriaudio.com/files/attach/banner_images/
soriaudio.com###adBannerID
```
