### ISSUE TITLE
sports.ru

### ISSUE THREAD

**Issue by dtitbd** [AdguardTeam/AdguardFilters#4053]
Все в марафоне.<details>

![image](https://cloud.githubusercontent.com/assets/17032471/21891205/47696490-d8f3-11e6-953b-d3f3b0bdd087.png)
</details>
И в некоторых местах встречается остаток от рекламы. 

Например, [здесь](https://www.sports.ru/my/news/) (нужен акк).

<details>

![image](https://cloud.githubusercontent.com/assets/17032471/21891287/c3363f9e-d8f3-11e6-9884-b9221137680b.png)
</details>

**Upd.** Еще длинные статусы не разворачиваются. https://www.sports.ru/tribuna/statuses/

***System configuration***

Information | value
--- | ---
Operating system: | Windows/Android
Browser: | Chrome
Adguard filters: | [аналогичны (обновлены)](https://camo.githubusercontent.com/2e4ffa92acc5f1ab3b96fd490f4974c950be8863/687474703a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f66393931333262656136656334313134626631616238653235303831313563662e706e67)

**Comment by Alex-302** [comment]
Рекламу убрал. 
Статусы вроде отображаются. Без Адгарда норм? Какой фильтр портит?

**Comment by dtitbd** [comment]
Плашка "реклама 18+" все равно из ленты личных новостей не убралась.
Длинные статусы, в них есть кнопка "читать дальше". Если нажать - бросает в верх страницы. Виноват фильтр счетчиков и аналитики. Без него все ок.

**Comment by Alex-302** [comment]
Убрал.
> Длинные статусы, в них есть кнопка "читать дальше". Если нажать

а можно скрин и ссылку? Не вижу что-то.

**Comment by dtitbd** [comment]
Сейчас она то есть, то нет, вообще не понимаю.
Ловить лучше на android. На винде не могу воспроизвести.
Ссылку-то на что? На конкретный статус не дать.
Вот, например, статус тупо в популярных:
![222](https://cloud.githubusercontent.com/assets/17032471/21957851/f0a534b0-dac1-11e6-84f2-3fbfb025b2c1.png)

Нажимаю "читать дальше" - кидает в верх страницы и в конец url добавляется **#** 
Потом может начать нормально разворачивать.
Правда я уже не уверен какой фильтр виноват. Но без адгуарда точно все ок.

**Comment by dtitbd** [comment]
Ставка дня еще появилась.
![screenshot_2017-01-15-19-16-14 01](https://cloud.githubusercontent.com/assets/17032471/21963169/4ceb0b88-db57-11e6-95e7-748e975db827.png)

**Comment by Alex-302** [comment]
> Нажимаю "читать дальше" - кидает в верх страницы и в конец url добавляется #



> Ставка дня еще появилась.

не повторяется.
Алгоритм фильтрации какой?

**Comment by dtitbd** [comment]
Ставка дня уже прошла, потому что матч закончился. В следующие выходные может повторится.
Со статусами сам не понимаю. Уже вроде работает. Да, в последних обновлениях фильтров что-то поправили. На одном устройстве были вчерашние - опять не разворачивало. Обновил - все ок стало.
Алгоритм качественный, если что.

**Comment by Alex-302** [comment]
Статусы не из-за адгарда не разворачивались.
