### ISSUE TITLE
apkgod.net [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#40547]
**Site**: https://apkgod.net/redflix-tv-app/

**Issue**: Please remove the fake links as seen in the screenshot from the top and bottom of the page.

**Screenshot**: http://prntscr.com/p6dpok

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 77.0.3865.75 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 3.2.1	 `

**Filters**:
```
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404
NoCoin Filter List

```

**Stealth Mode Settings**:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled (Default)

**Comment by krystian3w** [comment]
`apkgod.net##.ads-parent`
