### ISSUE TITLE
weszlo.com

### ISSUE THREAD

**Issue by MaksymilianWars** [AdguardTeam/AdguardFilters#4054]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: weszlo.com is detecting Adguard and blocking me from browsing the page

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot: 
![cn3mer5](https://cloud.githubusercontent.com/assets/25079637/21899864/25406b58-d8f2-11e6-9aff-17b588e21a03.jpg)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10
Browser: | Safari
Adguard version: | 1.1.4
Simplified filters(iOS) | Off
Adguard DNS: | None 
Stealth mode options(Windows) | 
Adguard filters: | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced on iPad.
Which filters are enabled?

**Comment by MaksymilianWars** [comment]
Indeed, I was able to browse the website for a short time after I reported the issue. However, they started blocking content once again. Any hints?

Filters I'm using currently:

English filter
Spyware filter
Social media filter
German filter
Safari filter
EasyList
Adblock Warning Removal List
Adblock polskie reguły
Anti-Adblock Kiler

Thank you

**Comment by Alex-302** [comment]
Added to English filter
```
@@||weszlo.com^$generichide
```
please check it

**Comment by MaksymilianWars** [comment]
![img_1249](https://cloud.githubusercontent.com/assets/25079637/21989378/f4ebf58c-dc0a-11e6-8af3-8f68cf6dd89d.PNG)
![img_1250](https://cloud.githubusercontent.com/assets/25079637/21989379/f4ec8b82-dc0a-11e6-9bae-8ab971a16b2f.PNG)

Thanks for your prompt response. Unfortunately the issue still exists. I added it as a user filter as well, and tried restarting both Safari and Adguard.

**Comment by Alex-302** [comment]
AG for iOS have some issues with $generic exclusions. I hope it will be fixed in next build:)

**Comment by MaksymilianWars** [comment]
OK... @Alex-302, thanks. Any ideas when would that be?

**Comment by Alex-302** [comment]
No.
BlockAdBlock script checks many elements. Are you using full or optimized filters?

**Comment by MaksymilianWars** [comment]
Do you mean simplified filters? No, they're turned off.

I found the rule above in another discussion, and it appears to be working for me on my laptop. https://github.com/MajkiIT/polish-ads-filter/issues/1997

**Comment by Alex-302** [comment]
Please wait for new version for Safari. As I said before, current version has sove troubles with $generichide/$elemhide rules.
