### ISSUE TITLE
http://hdrezka.me - ads

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4055]
Пропущена реклама на странице:
http://hdrezka.me/films/thriller/14521-rasplata.html

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21909380/5f7d29cc-d920-11e6-860a-aaf85651710e.png)

</details>

<details>

Application version: 1.1.4.60
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 5A587F48-9234-4D8C-B182-0FF3E5CB225C

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.70 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.18 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.37 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.45.32 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.8 Enabled=YES

</details>

Ticket ID: 1487270

**Comment by Alex-302** [comment]
Подправил.

**Comment by evgeniy-ADG** [comment]
Если запустить любой фильм или сериал на этом ресурсе появляется реклама.

![image1](https://cloud.githubusercontent.com/assets/15856304/24070250/1a0e6070-0bc2-11e7-82e6-777b721d3e95.png)

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.10.91 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.86 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.69 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.47.92 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.63 Enabled=YES

**Comment by evgeniy-ADG** [comment]
http://hdrezka.me/

При попытке просмотреть видео на
сайте hdrezka.me белый экран с надписью adobe
flash is disabled for this page click player area to enable.
Кликать бесполезно, добавлять сайт в
исключения ADGUARD бесполезно. Помогает
только отключение защиты. 

Os version: Microsoft Windows NT 6.1.7601 Service Pack 1
AppVersion: 6.1.331.1732
Driver Type: Tdi
HTTPS filtering enabled: True
Subscriptions: 1 2 3 4 6 8 104
Stealth Mode enabled: StealthModeSettings: {

-   "BlockThirdPartyCookies": true,
-   "BlockThirdPartyCookiesPeriodMin": 30,
-   "BlockFirstPartyCookies": false,
-   "BlockFirstPartyCookiesMin": 2880,
-   "DisableThirdPartyCache": true,
-   "BlockWebRtc": true,
-   "BlockBrowserPushApi": false,
-   "BlockBrowserLocationApi": true,
-   "RemoveXClientDataHeader": true,
-   "HideSearchQueries": true,
-   "SendDoNotTrackHeader": true,
-   "RemoveRefererFromThirdPartyRequests": false,
-   "HideUserAgent": false,
-   "CustomUserAgent": null,
-   "CustomReferer": null,
-   "HideIp": false,
-   "CustomIp": "209.141.53.254"
-
