### ISSUE TITLE
http://www.sueddeutsche.de - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4056]
http://www.sueddeutsche.de - incorrect blocking

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/21909494/ead2eca0-d920-11e6-8c1e-1708cdf5ee03.png)

</details>

<details>

Application version: 1.1.4.36
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: 995D1D4B-4118-4236-8155-E29BC95A353E

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.70 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.18 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.37 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.77 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=NO
ID=6 Name="German filter" Version=1.0.30.21 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.8 Enabled=YES

</details>

Ticket ID(if exists): 1459423

**Comment by Alex-302** [comment]
Not reproduced on my iPad. Please try to enable optimized filters.
