### ISSUE TITLE
http://japanese.engadget.com - Incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4057]
Incorrect blocking on page:
http://japanese.engadget.com/2017/01/09/beats-iphone-7/

Strange layout on iPad side view

<details>

![image2](https://cloud.githubusercontent.com/assets/23258533/21910156/84e97762-d923-11e6-8159-9d0fb2a4c142.png)

</details>

<details>

![image1 2](https://cloud.githubusercontent.com/assets/23258533/21910169/8f668e1e-d923-11e6-8d0b-ec97cfcbdd58.png)

</details>

<details>

![image3](https://cloud.githubusercontent.com/assets/23258533/21910180/9a67d750-d923-11e6-9e02-6f8cdec9fc7e.png)

</details>

<details>

![image2 1](https://cloud.githubusercontent.com/assets/23258533/21910190/a90e20e8-d923-11e6-9b49-e7644407e74f.png)

</details>

<details>

Application version: 1.1.4.60
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: 5EEC9D0F-9DEB-40C1-BA2F-0E0D2AE8376D

Locale: ja
Region: jp

Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.41 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.9 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.21 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.93.4 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.58 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.69 Enabled=NO
ID=200 Name="ABP Japanese Filters" Version=1.0.4.40 Enabled=NO

</details>

Ticket ID(if exists): 1468516

**Comment by Alex-302** [comment]
> ID=200 Name="ABP Japanese Filters" Version=1.0.4.40 Enabled=NO

it is very bad filter. It contains a lot of wide dangerous rules.
For custom filter:
```
@@||engadget.com^$domain=engadget.com
@@/*.css$domain=engadget.com
```
