### ISSUE TITLE
https://www.google.fr/search - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4058]
Incorrect blocking on page:
https://www.google.fr/search?q=inverter+packard+bell+easynote+sb85&client=safari&sa=X&hl=fr-fr&biw=375&bih=559&tbs=vw:l,ss:44&tbm=shop&prmd=sivn&srpd=10151875298932432651&prds=num:1,of:1,epd:10151875298932432651&ved=0ahUKEwi9vojnq73RAhVGthoKHWwtBSYQgjYIjQE

<details>

![image2 2](https://cloud.githubusercontent.com/assets/23258533/21910531/1a7e162e-d925-11e6-8444-f369699dcadc.png)

</details>

<details>

![image1 3](https://cloud.githubusercontent.com/assets/23258533/21910544/290f9de8-d925-11e6-82d8-49044311d903.png)

</details>

<details>

Application version: 1.1.4.60
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 38C53924-BEC0-445C-AEC6-08DEAB00CFD1

Locale: fr
Region: fr

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.90.64 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.5 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.11.29 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.4.45 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.2 Enabled=YES
ID=113 Name="Liste FR" Version=1.0.63 Enabled=YES

</details>

Ticket ID(if exists): 1364466

**Comment by Alex-302** [comment]
Not reproduced. Try
```
@@||googleadservices.com^$domain=google.fr
```

**Comment by evgeniy-ADG** [comment]
The same on google.co.il, addin the same rule but with google.co.il doesn't help. Please see:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22504855/22da7d06-e881-11e6-82b0-d064a4fa797c.png)

![image](https://cloud.githubusercontent.com/assets/15856304/22504864/2a752d7c-e881-11e6-89fb-a27f0ba83808.png)

<details>

You can find logs here: 1008106, Jan 30 ticket

**Comment by Alex-302** [comment]
thy this on iOS
```
@@||googleadservices.com^
```
When DNS filtering is enabled, $domain modifier is not working for domain blocking rules

**Comment by evgeniy-ADG** [comment]
У меня на маке блокируется в Хроме. [Вот](https://www.googleadservices.com/pagead/aclk?sa=L&ai=COq8MDSGYWNOVMZKGYdHTjCDVwPekR5qTzabTBJCAjJWmAQgAEAFgpa6jhvwioAGUqsSkA8gBAakCqs5rF-e8Yz6qBCNP0KIfBIzzEfhChh12ZyLsxMzl0cTNBjkPKbss7IqvHnr0wqAGUYAH1NW7W5AHAagHpr4b2AcB&ved=0ahUKEwiMpO7y9PrRAhXpQZoKHR-WA4sQ0QwIFg&dblrd=1&val=Ggig9XROpSBo_SABKAAw14zV77D73pZ0OJGk-MIFQIGy4MQF&sig=AOD64_2hvI5MjM46J5xpOCg9TYWswYeHWQ&adurl=https://browser.yandex.ua/get/brand_ru/%3Ffrom%3Dadwords_serp_brand_ru%26utm_source%3Dgoogle%26utm_medium%3Dsearch%26utm_campaign%3DBrand_search%26utm_term%3Dyandex%2520browser%26utm_content%3D).

**Comment by Alex-302** [comment]
Там это исключение должно срабатывать
```
@@://www.google.*/aclk$urlblock
```


> выключил фильтрацию в программе, оставил в расширении. Поискал в гугле, включил фильтарцию в прогармме, но страница по прежнему фильтруется расширением

вкладку нужно обновить.

**Comment by evgeniy-ADG** [comment]
Да обновлял... Оно все как-то странно работает в посл. время. По теме (попросили добавить правила, которые ты выше писал):

I guess that will work but shouldn't it be included automatically when I enable the setting to see friendly ads?

**Comment by Alex-302** [comment]
Там похоже что-то кроме Адгарда ещё блокирует. Разжиться бы доступом к компу с проблемой. Французкий гугл как-то плохо работает, даже без Адгарда, а ru/ua - нормально.

**Comment by evgeniy-ADG** [comment]
What do we do with such cases? If there a workaround or something?

Neither of these two rules helps:

1. @@||googleadservices.com^$domain=google.de
2. @@||googleadservices.com^

<details>

![img_0661](https://cloud.githubusercontent.com/assets/15856304/23358036/00887c9a-fce9-11e6-9e88-ba8f965e3a28.png)

</details>

It happens in Safari and in Google app from the App Store.
Adguard Pro with the DNS filtering.

**Comment by Alex-302** [comment]
Look at the filtering log and try to unblock google domains.

**Comment by evgeniy-ADG** [comment]
>I figured out how to get the Google ads working. I enabled the DNS logging
and checked which domains got blocked by Adguard DNS. The following rules
unblocked the Google search ads both in the Google app and in Safari on iOS:

>@@||www.googleadservices.com$document
@@||ad.doubleclick.net$document
@@||pagead.l.doubleclick.net$document

**Comment by Alex-302** [comment]
You can suggest these rules to users with DNS filtering.
Also, they should to add these domains to whitelist
```
www.googleadservices.com
ad.doubleclick.net
pagead.l.doubleclick.net
```
