### ISSUE TITLE
http://www.espn.com/ - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4059]
Incorrect blocking on page:
http://www.espn.com/

The "Scores" link on the top right corner doesn't work anymore. 

<details>

![image1 4](https://cloud.githubusercontent.com/assets/23258533/21910814/60dcb28c-d926-11e6-9f93-62b523b185c7.png)

</details>

<details>

Application version: 1.1.4.60
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 6D9CB7E7-C2FD-4440-9B6E-11D32EB12CB3

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.64 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.16 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.36 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.8 Enabled=YES

</details>

Ticket: 1313547

**Comment by Alex-302** [comment]
Fixed
