### ISSUE TITLE
https://www.saturn.de/ - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4060]
https://www.saturn.de/ - incorrect blocking

On this site no link does not function anymore when Adguard is active. Just click on any Link on this site and you will just see a rotating animation.

<details>

Application version: 1.1.4.60
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: ABD8BD37-0C19-4219-8383-7D4F911BDEDE

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.55 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.13 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.32 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.69 Enabled=YES
ID=6 Name="German filter" Version=1.0.30.17 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.60 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.8 Enabled=YES

</details>

Ticket ID(if exists): 1189930

**Comment by Alex-302** [comment]
Not reproduced.
I need a screenshot with broken link.

**Comment by danidoedel** [comment]
@Alex-302 
For example this link doesn't work:
![image](https://cloud.githubusercontent.com/assets/10995998/21983392/5c3d13ca-dbf1-11e6-9bf6-d53301d4ed7a.png)

And nothing happens (just that spinng wheel):

![image](https://cloud.githubusercontent.com/assets/10995998/21983417/8115dd4e-dbf1-11e6-9fc2-13b243ca53bc.png)

If I disable Spyware filter it will work.

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||google-analytics.com/plugins/ua/ec.js$domain=saturn.de
@@||google-analytics.com/analytics.js$domain=saturn.de
@@||googletagmanager.com/gtm.js$domain=saturn.de
```
