### ISSUE TITLE
userscloud.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#40614]
[https://userscloud.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://userscloud.com/)

![cookie](https://user-images.githubusercontent.com/35470489/64986119-be41ec80-d89c-11e9-8db3-144924d9d7e4.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by BlazDT** [comment]
Hidden by Annoyances filter for me.
Please check @AdamWr

**Comment by AdamWr** [comment]
I can't reproduce it.
On my end it's hidden by this rule:
`##.cc-window[aria-label="cookieconsent"]`

**Comment by adranger** [comment]
Thank you for investigating this. It turns out `uBlock filters` has `@@||userscloud.com^$generichide`.

@mapx- Please add `userscloud.com##.cc-window[aria-label="cookieconsent"]`.

**Comment by mapx-** [comment]
could you test disabling generichide filter ? (if some other issue, anti adb etc)
`@@||userscloud.com^$generichide,badfilter`

**Comment by adranger** [comment]
I don't see any other issue after disabling that filter. Test URL:  `https://userscloud.com/cjziutymnsh5`

**Comment by mapx-** [comment]
removed
