### ISSUE TITLE
philips.de - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4062]
***Site***: http://www.philips.de/
***Description***: Cookie notice is incorrect blocked. Cookie notice on mobile not blocked.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21911786/9a5200fc-d922-11e6-8cf6-483151476689.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21911850/e2dc3c3e-d922-11e6-8de2-2cec50206bbb.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.5.70
Spyware filter | 1.0.10.18
Social media filter | 1.0.16.37
Annoyances filter | 1.0.8.77
German filter | 1.0.30.21
Mobile ads filter | 1.0.6.60
Safari filter | 1.0.2.8

**Comment by Alex-302** [comment]
Can't reproduce on my side

**Comment by danidoedel** [comment]
Seems to be fixed somehow.
