### ISSUE TITLE
samsung.com - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4063]
***Site***: http://www.samsung.com/de/home/
***Description***: Blank site and will load only after ~10 seconds... Insant loading with Adguard disabled.

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.5.70
Spyware filter | 1.0.10.18
Social media filter | 1.0.16.37
Annoyances filter | 1.0.8.77
German filter | 1.0.30.21
Mobile ads filter | 1.0.6.60
Safari filter | 1.0.2.8

**Comment by Alex-302** [comment]
Added to Spyware filter
```
||assets.adobedtm.com^$domain=samsung.com
```

**Comment by danidoedel** [comment]
@Alex-302 Same does now happen to http://www.samsung.com/us/ too. 
http://www.samsung.com/de/ works fine though.

**Comment by Alex-302** [comment]
added
@@||tags.tiqcdn.com/utag/samsung/main/prod/utag.js$domain=samsung.com
