### ISSUE TITLE
https://m.yelp.com - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4064]
Incorrect blocking on page:
https://m.yelp.com/biz/vivaldi-boutique-new-york

Adguard blocks the page when you click on "read more" 

<details>

![image uploaded from ios](https://cloud.githubusercontent.com/assets/23258533/21911904/8f164e1a-d92b-11e6-8b29-06f5175ff8f1.jpg)

</details>

<details>

Application version: 1.1.4.60
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 627ADDBE-9B4D-4483-873A-61A2548BA48D

Locale: en
Region: us

Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.4.68 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.99 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.10 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.46 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.52 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.72.18 Enabled=YES

</details>

Ticket: 1444380

**Comment by Alex-302** [comment]
Try to add to whitelist:
```
app.adjust.io
```

**Comment by evgeniy-ADG** [comment]
Asked here: 1498422

**Comment by evgeniy-ADG** [comment]
1. Added app.adjust.io to whitelist. Didn't work
2. Turned off: Block pop-ups. Didn't work.
3. Request Desktop site. Worked

@Alex-302

**Comment by Alex-302** [comment]
Ok. Try to disable all filters and enable them one-by-one with checking. Tell me, which filter causes this issue.
