### ISSUE TITLE
maxidom.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#40669]
**1**. Мешающий и ненужный баннер.

<details><summary>Screenshot:</summary>

![2019 09 17-1](https://user-images.githubusercontent.com/17948007/65049395-5956c700-d96e-11e9-8811-ac6d6788d573.png)
</details>

[https://www.maxidom.ru/catalog/stulja/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.maxidom.ru/catalog/stulja/)

`maxidom.ru##.item-banner-long`

___________________________________________________

         Факультативно:
___________________________________________________

 **2**. Плавающая шапка.

<details><summary>Screenshot:</summary>

![2019 09 17-6](https://user-images.githubusercontent.com/17948007/65051226-675a1700-d971-11e9-8106-d00cd3b8171f.png)
</details>

`maxidom.ru##.fixbar`

___________________________________________________

 **3**. Лишние отступы.

<details><summary>Screenshot:</summary>

![2019 09 17-2](https://user-images.githubusercontent.com/17948007/65051408-bef88280-d971-11e9-801b-5b4f246d5c04.png)
----------
![2019 09 17-5](https://user-images.githubusercontent.com/17948007/65051488-e2233200-d971-11e9-9d78-6fbc5687d904.png)
----------
![2019 09 17-4](https://user-images.githubusercontent.com/17948007/65051504-e8b1a980-d971-11e9-8a3e-efabcedd172b.png)
----------
![2019 09 17-3](https://user-images.githubusercontent.com/17948007/65051539-f36c3e80-d971-11e9-81e7-19b1d27a1461.png)
</details>

[https://www.maxidom.ru/catalog/stulja/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.maxidom.ru/catalog/stulja/)

`maxidom.ru##[style="padding: 10px 0px;"]`
`maxidom.ru#$#.catalog, .filter-catalog, .items-list { margin-top: 0px!important; padding-top: 0px!important; padding-left: 0px!important; padding-right: 0px!important; padding-bottom: 0px!important; }`

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.2.1
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
Ну жесть же. Баннеры - не реклама. Такие во многих магазинах.

**Comment by XX-J** [comment]
Ну представьте: Я ищу стулья, а мне подсовывают баннер со смесителями (как на картинке) - это НЕ НУЖНАЯ мне в данный момент (само)РЕКЛАМА.

 Скажу больше: Когда я ищу стулья (например), то меня интересует ТОЛЬКО список этих стульев, согласно моему фильтру на сайте. Исходя из этого: меня не интересует и даже ИЗЛИШЕН БАННЕР СО СТУЛЬЯМИ, т.к. он отнимает полезное-рабочее пространство сайта и занимает внимание на то, что я полюбому увижу в списке, если это подпадёт под МОЙ фильтр.
