### ISSUE TITLE
htc.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4066]
***Site***: http://www.htc.com/de/go/launch/
***Description***: Annoying overlay when accessing this site.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21912018/cd9eb288-d923-11e6-97d8-51262d14b4f4.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.5.70
Spyware filter | 1.0.10.18
Social media filter | 1.0.16.37
Annoyances filter | 1.0.8.77
German filter | 1.0.30.21
Mobile ads filter | 1.0.6.60
Safari filter | 1.0.2.8

**Comment by Alex-302** [comment]
check it:
```
htc.com#%#document.cookie = "htc-has-view-launch-page=true";
```

**Comment by danidoedel** [comment]
Hm it looks like they don't redirect to that site anymore. If they'll do it again I will check it.
