### ISSUE TITLE
nvidia.de - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4067]
***Site***: http://www.nvidia.de/page/home.html
***Description***: Page doesn't load (only background)... only after ~10 seconds (similar to #4063)

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21912242/fbbf0b62-d924-11e6-9bde-463a068bcd45.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.5.70
Spyware filter | 1.0.10.18
Social media filter | 1.0.16.37
Annoyances filter | 1.0.8.77
German filter | 1.0.30.21
Mobile ads filter | 1.0.6.60
Safari filter | 1.0.2.8

**Comment by Alex-302** [comment]
Added to Spyware filter
```
||adobedtm.com^*/satelliteLib-$script,domain=nvidia.ru|nvidia.com|nvidia.com.tr|nvidia.com.tw|nvidia.se|nvidia.pl|nvidia.no|nvidia.nl|nvidia.com.mx|nvidia.co.kr|nvidia.co.jp|nvidia.it|nvidia.in|nvidia.co.uk|nvidia.fr|nvidia.fi|nvidia.ru|nvidia.com|nvidia.de|nvidia.es|nvidia.com.br|nvidia.at|nvidia.be|nvidia.cn|nvidia.cz|nvidia.dk
```
