### ISSUE TITLE
https://m.costco.ca - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4068]
Incorrect blocking on page:
https://m.costco.ca/Kobe-Classic-Beef-%e2%80%93-Wagyu-Gourmet-Burgers.product.10340271.html

Reviews section is empty with enabled filters. Should not be blocking reviews. All Costco pages on iOS safari win Adguard on. When disabled page works correctly

<details>

Application version: 1.1.4.36
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: F7DFEDC0-E159-4183-AE42-000ED41CF958

Locale: en
Region: ca

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.70 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.18 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.10 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.8.77 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.60 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.8 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.62 Enabled=YES
ID=101 Name="EasyList" Version=1.0.66.62 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.72.60 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.72.74 Enabled=YES

</details>

Ticket ID(if exists): 1487449

**Comment by Alex-302** [comment]
Can't access to this site
http://i91.fastpic.ru/big/2017/0114/ef/14d8320b26e6281c729b98cfd4cd4def.jpg

**Comment by seanl-adg** [comment]
I can't reproduce, above commit is for something else.

**Comment by evgeniy-ADG** [comment]
One can try accessing it with Canadian VPN, it works on a PC. Will try that later today and let you all know.

**Comment by Alex-302** [comment]
@evgeniy-ADG please ask for check without
ID=101 Name="EasyList" Version=1.0.66.62 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.72.60 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.72.74 Enabled=YES
