### ISSUE TITLE
http://maximus.ru/

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#4069]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: blocking information in http://maximus.ru/brands/acer/
**helps disabling Russian filter**

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21922445/500d4c40-d977-11e6-80da-78abad964267.png)

</details>

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21922498/93365a20-d977-11e6-8f69-565f0d851079.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows & extansion 
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard filters: | 1,2,3,4,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1487552

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
