### ISSUE TITLE
Parallel Space app - Ads 

### ISSUE THREAD

**Issue by natalysk** [AdguardTeam/AdguardFilters#4071]
***Description***: missed ads in Parallel Space app
 
Screenshots:

http://prnt.sc/dv31w6
http://prnt.sc/dv32c5

**Link:** https://play.google.com/store/apps/details?id=com.lbe.parallel.intl

***System configuration***

Information | value
--- | ---
Operating system: | Android 7.1.1
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | 2, 3, 4, 14, 1, 11

[debug (4).txt](https://github.com/AdguardTeam/AdguardFilters/files/704138/debug.4.txt)
time: 3.25

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1044345

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
We can't block ads here without breaking Facebook.
If user doesn't use it, he can add this rule to user filter:
```
||graph.facebook.com^$app=com.lbe.parallel.intl
```
