### ISSUE TITLE
http://www.360pethome.com - ads

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4073]
http://www.360pethome.com/forum-43-1.html - missed ad

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/21947511/3ece5074-d9ee-11e6-87f2-42a22795c89f.png)

</details>

<details>

![image2](https://cloud.githubusercontent.com/assets/23258533/21947514/446e1028-d9ee-11e6-803d-5f58a5369c47.png)

</details>

<details>

Application version: 1.1.4.60
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: C36086E6-AD81-4702-A1AD-9E7B390227B7

Locale: zh
Region: cn

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.6 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.1 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.15 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.97 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.4 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.72.58 Enabled=YES

</details>

Ticket ID(if exists): 1486356

**Comment by Alex-302** [comment]
Not reproduced.
