### ISSUE TITLE
http://t3n.de - ads

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4074]
http://t3n.de/news/opera-neon-konzept-browser-785166/opera-neon-konzept-browser-6/?parent=785166&ids=36d488cc893c040d4cf54fc878c226b4 - missed ad

On the entire articles on this site, there is a sticky share button on the bottom. I have the social media and the annoyance filters activated.
Its that grey Button with the paper plane. To hide it manually with Adguard does not work for all pages of this website.

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/21947590/a60b46d4-d9ee-11e6-843e-2aa93efeb2df.png)

</details>

<details>

![image2 1](https://cloud.githubusercontent.com/assets/23258533/21947595/ad1a87b4-d9ee-11e6-97ec-3fbba81332c5.png)

</details>

<details>

Application version: 1.1.4.36
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2.1
ID: 9F4067F9-8873-434C-9F4B-7AC301A2F40E

Locale: de
Region: de

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.4.88 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.15 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.51 Enabled=YES
ID=6 Name="German filter" Version=1.0.29.97 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.2 Enabled=YES

</details>

Ticket ID(if exists): 1413100

**Comment by danidoedel** [comment]
There are several other things (ads, social widgets etc.) that should be blocked too:

<details>
<summary>Screenshots</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21955571/ffc8287a-da6d-11e6-8c45-6960a07e74d2.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21955574/2501134a-da6e-11e6-925d-344928ff05df.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21955578/3fc178c8-da6e-11e6-841b-7f5449c87459.png)

</details>

_Rules to block everything:_

**Social filter:**
```
t3n.de##.tg-social-top
t3n.de##.tg-social-bottom
t3n.de##.tg-whatsapp-signup
```
**Annoyance filter:**
```
t3n.de##.c-newsletterbox
```
**German filter:**
```
t3n.de##.tg-stage-sponsoredcontent
t3n.de$$a[tag-content="Banner buchen"]
```

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
t3n.de##.c-newsletterbox
t3n.de##a[href="https://t3n.de/store/mediadaten/"]
```
Added to Social filter
```
t3n.de##.tg-social-bottom
```

**Comment by danidoedel** [comment]
@Alex-302 These two things are still there:
![image](https://cloud.githubusercontent.com/assets/10995998/22068759/5492268c-dd96-11e6-9216-816c0bbb9dd5.png)
