### ISSUE TITLE
АнтиАдБлок и пропуск рекламы.

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#4075]
На сайте http://wormax.io/ при нажатии "играть" срабатывает антиадблок, и не дает играть.

А также напоминаю про проблему с http://videoframe.blue/?kp_id=527 здесь перед началом просмотра, заставляют смотреть ролик с ютуба.
_Ранее писал об этом [тут](https://github.com/AdguardTeam/AdguardFilters/issues/3515)_

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=wormax.io
@@||googleads.g.doubleclick.net/pagead/ads?sdkv=*&url=http%3A%2F%2Fwormax.io
@@||wormax.io$generichide
```
по второму - не выходит пока.
