### ISSUE TITLE
http://kinohd.net - incorrect blocking, ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4076]
http://kinohd.net/1080p/6949-387425h383r-ben-gyr-2016.html
<details>

Ads:

![default](https://cloud.githubusercontent.com/assets/15856304/21953578/f1b41156-da43-11e6-9f01-b487460dba1a.PNG)

Missed kinopoisk button:

![default](https://cloud.githubusercontent.com/assets/15856304/21953582/06c24536-da44-11e6-94cd-a0a43cda2a89.PNG)

</details>

Adguard 6.1.258.1302
Chrome. Версия 55.0.2883.87 m (64-bit)
Filters: Eng, Ru, Annoyances, Social media
Stealth mode: off
Driver: WFP

**Comment by Alex-302** [comment]
fixed
