### ISSUE TITLE
Bubble Blast 2

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#4078]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Ads after opening app and during playing the game
https://play.google.com/store/apps/details?id=com.magmamobile.game.BubbleBlast2

LOG https://drive.google.com/open?id=0B5dP1M24mheOZ2xYTXhnbFBVMUk

time
14-27 
14-28 
14-29

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21954868/8c7ee55e-da66-11e6-845d-75c49f3cfec2.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21954870/9b8fbd5c-da66-11e6-8178-a2fdbfc6b83d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Defaulte) 
Adguard DNS: | None
Adguard filters: | 1,2,3,4,14,11

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1325165

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Баг что ли. Гугловый адрес один не блокируется, хотя в журнале помечен как заблокированный
`https://googleads.g.doubleclick.net/mads/gma?carrier=`

**Comment by Alex-302** [comment]
Не баг)
Поправил.
