### ISSUE TITLE
tim.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#40799]
[https://www.tim.com.br/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.tim.com.br/)

![cookie](https://user-images.githubusercontent.com/35470489/65270443-88e20c80-daf1-11e9-97f3-42c694dbfb9b.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by adranger** [comment]
@AdamWr App banner:

![tim](https://user-images.githubusercontent.com/35470489/74414621-883f6f00-4e20-11ea-8943-2e5d38ade9c4.png)

**Comment by AdamWr** [comment]
Fixed.
