### ISSUE TITLE
Unable to make calls using Hangouts and Google Voice

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4079]
Since I updated to AdGuard v6.1 a couple weeks ago, I can no longer make a phone call from my computer. I have to disable protection now to place then call.

STR:

<details>

I'm using Google Hangouts or Google Voice to place calls. When AdGuard protection is disabled, a call goes through (see "In voice call...0:23" in screenshot below).

![image](https://cloud.githubusercontent.com/assets/15856304/21954960/2d0cd8a8-da69-11e6-864f-bc34d6a969f4.png)

When Adguard protection is enabled, however, call will NOT go through (see "Calling..." in the screenshot below). Also note, after changing Adguard protection state, I must exit out of Google Hangouts for the change to take effect. Hope this helps. Thanks!

![image](https://cloud.githubusercontent.com/assets/15856304/21954956/152aba98-da69-11e6-8a4b-9125b7c58ff4.png)

</details>

System information:

<details>

Os version: Microsoft Windows NT 10.0.14393.0
AppVersion: 6.1.298.1564
Main settings: 
Subscriptions: 2 3 4 10
Driver Type: Wfp
HTTPS filtering enabled: True
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": false,
  "BlockWebRtc": false,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": true,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"
}

</details>

Ticket: 1487410

**Comment by Alex-302** [comment]
Is Stealth mode enabled?

**Comment by evgeniy-ADG** [comment]
yes, it's under the second spoiler

**Comment by Alex-302** [comment]
`"HideUserAgent": true,`
try to disable it

**Comment by evgeniy-ADG** [comment]
ticket: 1492110 - the same on Mac. asked to send us debug logs.

**Comment by Alex-302** [comment]
@evgeniy-ADG удалённым доступом бы разжиться. Этих Hangouts как грязи, не пойму какой не работает.

**Comment by evgeniy-ADG** [comment]
1 - asked
2- didn't respond
