### ISSUE TITLE
radio.net

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#40805]
[https://www.radio.net/s/kingfm981](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.radio.net/s/kingfm981)

![social](https://user-images.githubusercontent.com/35470489/65277761-fe090e00-db00-11e9-9241-d35b4744c4c0.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by BlazDT** [comment]
Fixed, site was showing ads to me due to Annoyances filter (other language versions not, so only removed this domain from rules).
