### ISSUE TITLE
http://www.ghanatvon.com/vox-africa-tv.html - anti-adblock

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4084]
http://www.ghanatvon.com/vox-africa-tv.html

![image](https://cloud.githubusercontent.com/assets/15856304/21957895/de1674ac-daa9-11e6-9f33-8363d8513f6e.png)

<details>

Adg 6.1, Win 10, Chrome 55, WFP, no stealth

![image](https://cloud.githubusercontent.com/assets/15856304/21957905/0542b504-daaa-11e6-8ceb-5e94399ddb0c.png)
****

**Comment by Alex-302** [comment]
fixed
