### ISSUE TITLE
sj.uukanshu.com - Missed ads (iOS)

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#4086]
***Description***: Missed ads on the website (iOS):
http://sj.uukanshu.com/book.aspx?id=39314

Screenshot:
<details>

![image1](https://cloud.githubusercontent.com/assets/17504743/21960672/77f0ed5e-dafb-11e6-89fa-93dfe1c3b43e.PNG)
![image2](https://cloud.githubusercontent.com/assets/17504743/21960673/792d4ad2-dafb-11e6-9f07-65c817212a6c.PNG)
![image3](https://cloud.githubusercontent.com/assets/17504743/21960674/7a33728a-dafb-11e6-9785-4e5c2493931c.PNG)
</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS / Android / Linux
Browser: | Safari
Adguard version: | 1.1.4.36
Adguard filters: | User filter, English filter, Spyware filter, Social media filter, Annoyances filter, Mobile Ads filter, Safari filter, EasyList China, CJX's Annoyance List

Ticket ID(if exists): 1488334

**Comment by Alex-302** [comment]
Just google ads. They are blocked on my side.
Are filters full or optimized?
