### ISSUE TITLE
https://edshopb2b.edsystem.cz - annoyance / custom rule request

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4087]
https://edshopb2b.edsystem.cz/acer-brasna-protective-sleeve-8-pro-7-8-tablet-white/product-563957

Please help us to create a rule to hide the next section on a site, if it can be considered as an annoyance, add it to the filter:

![image](https://cloud.githubusercontent.com/assets/15856304/21961497/b56b810e-db13-11e6-955e-309fbaa137a9.png)

<details>

Hello,
here is test account (case sensitive):
Name: albion-test
Password: agTest

Note that language switch to EN (english) in right-up corner doesn't 
work.
Don't hesitate If You need help with CZ-EN transation
You can view commodity items:
left column / Komponenty
second column / procesory / socket 1150
select an item
You can see now "Mohlo by Vás zajímat" annoying section

<details>

English, Russian, Social media, Czech and Slovak EL, Annoyances.

**Comment by Alex-302** [comment]
I can't access to this site. Auth is required.

**Comment by Losinsky** [comment]
"AdGuard Support team" has given credentials for test purpose. Could You ask them for it?
I can send You the credentials some private way otherwise...

**Comment by Losinsky** [comment]
AdGuard assistant disappeared from this site after last update a month ago. Custom rules has stopped filtering too. But I have AdGuard ver. 5.1 on ma old computer and the same rules works fine there.

**Comment by Alex-302** [comment]
This rule will remove recomendations:
```
edshopb2b.edsystem.cz##.products-recommended
```
Add it to user filter.

> AdGuard assistant disappeared from this site after last update a month ago. Custom rules has stopped filtering too. But I have AdGuard ver. 5.1 on ma old computer and the same rules works fine there.

I have no v5.1, but v6 works fine there, assistant works as expected)

**Comment by Losinsky** [comment]
Hi Alex,
the rule don't work on my computer. I don't see AdGuard assistant icon on left-down corner when I open eddsystem.cz (see attachment). But I can see it on other sites. How can I reappear assistant on this site? I tried delete all user rules ago, it doesn§t resolve it
![ag1](https://cloud.githubusercontent.com/assets/25163965/22021768/413a6932-dcbf-11e6-8a32-63e5a0ebad01.gif)
.

**Comment by Alex-302** [comment]
Is HTTPS filtering works?
Please show me this screenshot:

![image](http://i91.fastpic.ru/big/2017/0117/c1/d1d7b3c77c7773dc9d6db704cbc6d5c1.jpg)

**Comment by Losinsky** [comment]
Here ara screenshots...
would be there Adguard CA od VOMODO CA ?
![ed1](https://cloud.githubusercontent.com/assets/25163965/22088976/49860144-dde8-11e6-9efc-dc0a252f60de.gif)
![ed2](https://cloud.githubusercontent.com/assets/25163965/22088975/4983e36e-dde8-11e6-98bc-5b6ebb1ed5d6.gif)

**Comment by Alex-302** [comment]
> would be there Adguard CA od VOMODO CA ?

Adguard CA
HTTPS filtering is not works on this site. 
Make screenshot of this folder:
`C:\ProgramData\Adguard\NetworkTemp\SSL`
Is this checkbox enabled?

![image](http://i90.fastpic.ru/big/2017/0119/00/2b4c6cf30c72302639aad95e8214ea00.jpg)

**Comment by Losinsky** [comment]
Hi,
here is screenshot of ....NetworkTemp\SSL
I attach xv.db file too...
[xv_db.zip](https://github.com/AdguardTeam/AdguardFilters/files/717855/xv_db.zip)

HTTPS filtering is enabled
WFP driver is disabled (I is Win 7 computer)
There is used right certificate on other e-shop over HTTPS (sws.cz 3rd screenshot). AdGuard works fine there.
I don't know why edsystem.cz don't use right certificate. How can i repair it?
![ag11](https://cloud.githubusercontent.com/assets/25163965/22126637/bf8296ea-de98-11e6-889f-b7e1d9b6d532.gif)
![ag12](https://cloud.githubusercontent.com/assets/25163965/22126635/bf8141aa-de98-11e6-9763-c5cf662d0242.gif)
![ag13](https://cloud.githubusercontent.com/assets/25163965/22126636/bf815ee2-de98-11e6-8f3c-4ded14a2152f.gif)

**Comment by Alex-302** [comment]
`xv_db`
please close AG completely, stop service in task manager, then remove this file (xv.db/and x.dv) and start service and Adguard app and check again.

**Comment by Losinsky** [comment]
Hi Alex,
I stopped AG and service, deleted xv.db file. No x.dv (or x.db???) file found on disk. Restarted PC and no change at all. Site edsystem.cz uses COMODO certificate onwards. File xv.db has created and it has the same content as in the past.

**Comment by Alex-302** [comment]
Are you using Antivirus?

**Comment by Losinsky** [comment]
Yes, I use Kaspersky Antivirus 17. I tried disable it yet with no change. There is no problem at other https sites, only at edsystem.cz...

**Comment by Alex-302** [comment]
try to disable HTTPS filtering in Kaspersky and remove DB files of AG as you did it earlier.

**Comment by Losinsky** [comment]
I can see only xv.db file. Would be there x.dv file somewhere? Is it enough to delete xv.db file?

**Comment by Alex-302** [comment]
> Is it enough to delete xv.db file?

yes

**Comment by Losinsky** [comment]
I comletly disabled and exited Kaspersky antivirus.
Exited AdGuard, stoped adguard service. Deleted file xv.db (should I delete cert.db too?)
The started service and AdGuard. File xv.db doesn't exist yet. When I start FireFox and open edsystem.cz, file xv.db is created, size 83 bytes. When I login to edsystem.cz file xv.db extends to 247 bytes. Kaspersky is disabled all the time.
Please see attached log file. There are interesting lines:
Invalid server certificate, certificate subject: /OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.edsystem.cz
Add SslException firefox.exe#edshop.edsystem.cz
Driver has indicated SSL exception for edshop.edsystem.cz
And some other errors when loading rules

[service_24-01-2017-18_38_08-2017-01-24_log.txt](https://github.com/AdguardTeam/AdguardFilters/files/727519/service_24-01-2017-18_38_08-2017-01-24_log.txt)

**Comment by Losinsky** [comment]
Alex, You are on holidays?

**Comment by Alex-302** [comment]
No.
`I comletly disabled and exited Kaspersky antivirus.`
maybe Kaspersky core is still works. Is SSL filtering disabled?
@zebrum could you help with this issue?
`Driver has indicated SSL exception for edshop.edsystem.cz`

**Comment by Losinsky** [comment]
Is it suficient this way?
![kav](https://cloud.githubusercontent.com/assets/25163965/22464159/b48ca020-e7b5-11e6-8fd7-e0f59f95d613.gif)

**Comment by Alex-302** [comment]
> Is it suficient this way?

I hope:)

**Comment by zebrum** [comment]
@Losinsky yep
please choose "do not scan encrypted connections" in Kaspersky

**Comment by Losinsky** [comment]
I have choosen it all the time.

**Comment by zebrum** [comment]
@Losinsky what do you mean "all the time"?

**Comment by Losinsky** [comment]
I set "do not scan encrypted connections" two years ago, hwen I installed KAV.

**Comment by zebrum** [comment]
@Losinsky did you check this whole thing in other browser?

**Comment by Losinsky** [comment]
I have tried it just now in IE11.
It uses COMODO certificate too. AG Extension disappeared. Filtering doesn't work.

**Comment by zebrum** [comment]
@Losinsky could it be that somehow site was added to https exclusions?

**Comment by Losinsky** [comment]
the site is not in AdGuard's https excusions.

**Comment by zebrum** [comment]
@Losinsky try to uninstall with Advanced uninstall instruction: https://adguard.com/en/how-to-delete-adguard.html
