### ISSUE TITLE
Backgammon Narde app - ad leftovers

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4088]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Ads after opening app and during playing the game
https://play.google.com/store/apps/details?id=org.aastudio.games.longnards

Проблема возникла в 18-06. В игре "длинные нарды". После завершения партии, при переходе в главное меню.

[debug (12).txt](https://github.com/AdguardTeam/AdguardFilters/files/706503/debug.12.txt)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![s70114-18064231](https://cloud.githubusercontent.com/assets/15856304/21961652/fec5c0a4-db17-11e6-9da7-7a259f5b1971.jpg)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Defaulte) 
Adguard DNS: | None
Adguard filters: | 1,2,3,4,14,11

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1325165

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||report.appmetrica.yandex.net^
||mobads4app.com^
||50.17.161.250/appodeal/
||bidder.mdspinc.com^
```
