### ISSUE TITLE
snowmobile.ru - Missed ads

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#4089]
***Description***: Missed ads on the page:
http://www.snowmobile.ru/forum/index.php?threads/80230/page-16

Screenshot:
<details>

![screen shot 2017-01-15 at 14 39 27](https://cloud.githubusercontent.com/assets/17504743/21962526/a9d339d2-db30-11e6-9053-dbfcf0164bd9.png)
</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows (Reproduced on Mac)
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | "BlockThirdPartyCookies": true, "BlockThirdPartyCookiesPeriodMin": 30,  "BlockFirstPartyCookies": false,  "BlockFirstPartyCookiesMin": 2880,  "DisableThirdPartyCache": true,  "BlockWebRtc": true,  "BlockBrowserPushApi": false,  "BlockBrowserLocationApi": true,  "RemoveXClientDataHeader": true,  "HideSearchQueries": true,  "SendDoNotTrackHeader": true, "RemoveRefererFromThirdPartyRequests": false,  "HideUserAgent": false,  "CustomUserAgent": null, "CustomReferer": null,  "HideIp": false, "CustomIp": "209.141.53.254"

Adguard filters: | English filter, Spyware filter, Social media filter, Experimental filter, Annoyances filter

Ticket ID(if exists): 1088551

**Comment by Alex-302** [comment]
fixed
