### ISSUE TITLE
electricquilt.com

### ISSUE THREAD

**Issue by natalysk** [AdguardTeam/AdguardFilters#4090]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Each and every button/link that customer clicked on gave a "download file box", which didn`t download anything, and then got an error code. 
EXAMPLES OF ERRORS: 
+rvk7tF0 Failed Electronic Quilt.com - Tuesday
3eNNa1Ca Failed Electronic Quilt.com - Tuesday

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-01-15 at 10 20 03 pm](https://cloud.githubusercontent.com/assets/25100478/21965859/ea5bde9c-db70-11e6-919b-2b07e29b0ba4.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)
Go to http://electricquilt.com/online-shop/jelly-roll-quilt-magic/
Choose Add to card button
***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.1.298.1564 / 1.4.0
Adguard driver (Windows): | TDI

Adguard DNS: | None
 
Adguard filters: | 2,3,4,6,119,120

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1487549

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't fix it by exclusion. Filed a bug
https://github.com/AdguardTeam/AdguardForWindows/issues/1498
