### ISSUE TITLE
opodo.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4092]
***Site***: http://www.opodo.de/
***Description***: Newsletter message bar at the bottom. Overlay when accessing this site on mobile and app banner at the top on mobile.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21967039/b26eac1c-db7f-11e6-94c0-0cef4335bf21.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21967074/6b901a78-db80-11e6-91e6-972c576ab325.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21967048/fea965ae-db7f-11e6-818e-166488cbda32.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.5.97
Spyware filter | 1.0.10.20
Social media filter | 1.0.16.41
Annoyances filter | 1.0.8.86
German filter | 1.0.30.27
Mobile ads filter | 1.0.6.64
Safari filter | 1.0.2.13

**Comment by Alex-302** [comment]
fixed

**Comment by danidoedel** [comment]
@Alex-302 That overlay when accessing this site on a mobile device is still there. That rule blocks the overlay:
`opodo.de###appLayer`
