### ISSUE TITLE
swoodoo.com - Ad leftover - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4093]
***Site***: https://www.swoodoo.com/
***Description***: Ad leftover. Cookie notice on mobile.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21967089/ca4f2162-db80-11e6-890f-8dae017432a6.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21967102/e3b1fd1e-db80-11e6-83db-b32bcfcb69ab.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.5.97
Spyware filter | 1.0.10.20
Social media filter | 1.0.16.41
Annoyances filter | 1.0.8.86
German filter | 1.0.30.27
Mobile ads filter | 1.0.6.64
Safari filter | 1.0.2.13

**Comment by seanl-adg** [comment]
The first element was not reproduced.

**Comment by danidoedel** [comment]
@seanl-adg Html code if that helps to block that leftover:

```html
<div id="vXqB" class="section Common-Frontdoor-Brands-Swoodoo_wl-ExplorePromoAndDisplayAd fd-display-ads-wrapper ">
	<div class="fd-display-ads">
		<div class="fd-display-ad">
			<div id="zPSW" class="Common-Ads-DisplayAd location-left " js-component="true"></div>
		</div>
		<div class="fd-display-ad fd-display-ad-wide">
			<div id="ZJVn" class="Common-Ads-DisplayAd location-middle " js-component="true"></div>
		</div>
		<div class="fd-display-ad">
			<div id="kmx1" class="Common-Ads-DisplayAd location-right left-align" js-component="true"></div>
		</div>
		<br class="clear">
	</div>
</div>
```
