### ISSUE TITLE
lego.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4094]
***Site***: https://www.lego.com/de-de
***Description***: Cookie notice at the bottom. And different Privacy Policy/Cookie notice after closing this message.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21967158/fac9530c-db81-11e6-98fe-f1f2fc764588.png)

![image](https://cloud.githubusercontent.com/assets/10995998/21967168/1928f42e-db82-11e6-9a30-e13a825bb35e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.5.97
Spyware filter | 1.0.10.20
Social media filter | 1.0.16.41
Annoyances filter | 1.0.8.86
German filter | 1.0.30.27
Mobile ads filter | 1.0.6.64
Safari filter | 1.0.2.13

**Comment by seanl-adg** [comment]
Not reproduced, please check again.
