### ISSUE TITLE
sports.ru android app ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4095]
Рекламный баннер на странице с данными о матче.

Как попасть:
Матч центр - выбираешь матч какой-нибудь популярной команды, на странице над текстовой трансляцией будет баннер.

**Comment by Alex-302** [comment]
Ставки что ли?
Добавил
```
sports.ru##.b-bets-tabs
sports.ru##.make-stake-but
```

**Comment by ameshkov** [comment]
@Alex-302 да не, не ставки, прям под данными о матче и над текстовой трансляцией баннер небольшой. Хотя вот конкретно сейчас у меня его нет, хз.

Я про андроид-приложение если что.

**Comment by Alex-302** [comment]
Тоже чисто вроде.

**Comment by ameshkov** [comment]
Ну у меня чот тоже уже чисто:)
