### ISSUE TITLE
http://www.dtmts.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4096]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Adguard blocks video playback on the site
* **Current behaviour**:  

Nothing happens when you tap the play button

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image1](https://cloud.githubusercontent.com/assets/15856304/21974373/fdf3dc80-dbce-11e6-8fe8-f15ca2c20075.png)

</details>

***Steps to reproduce the problem***:

This is what you see once you select a game to watch highlights of. Normally when you tap on the play button in the middle of the video screen it will start playing an ad and then the video. With Adguard enabled for the website nothing happens when you tap on the play button. 

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | the latest one, Pro
Simplified filters(iOS) | Off
Adguard DNS: | Default
Adguard filters: | 2 3 4 11 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1488175

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||v.fwmrm.net/ad/g/*$domain=nhl.com|dtmts.com
@@||mssl.fwmrm.net/*/AdManager.js?$domain=nhl.com|dtmts.com
```
