### ISSUE TITLE
XLBygg.se - Page prevented from loading (AdGuard Annoyances filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#40968]
### Affected site:
`https://www.xlbygg.se/`

### Issue:
The page is prevented from loading, because of a blocked cookie consent message.
This occurs when '**AdGuard Annoyances filter**' is used in combination with either of the following filters:
* Fanboy's Annoyance List
* Fanboy's Cookie List
* I don't care about cookies

### Screenshot:
Not needed, as the problem is obvious, when '**AdGuard Annoyances filter**' is used in combination with either of the above filters.

### Problem filter:
* AdGuard Annoyances filter

### Problem rule:
`~samsung.com##.cookiewarning:not(body)`

### Possible fix (successfully bypassing the cookie consent message, and preventing conflicts with other filters):
```
xlbygg.se#@#.cookiewarning:not(body)
xlbygg.se##.cookievarning-wrap:not(body):not(html)
```

### Reference (issue report for Fanboy's filters):
https://github.com/ryanbr/fanboy-adblock/issues/1185/

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.7.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by BlazDT** [comment]
Thank you, fixed.
