### ISSUE TITLE
http://www.kabeleins.de/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4097]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: The site still contains some ads
* **Current behaviour**: Banners on the top and om the right side of the screen. The link: [here](https://qcrm.supportyourapp.com/#/customer/1340157)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![file_000](https://cloud.githubusercontent.com/assets/15856304/21974484/d6c8032e-dbcf-11e6-92f7-f774be7d0aee.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.4.60
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | 2 3 4 6 12 101 107

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1340157

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed. Check after filters update.

**Comment by Alex-302** [comment]
@evgeniy-ADG
