### ISSUE TITLE
Opening a website starting with "https://click1.e*" results in black screen

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#40981]
***Description***:

* **Current behaviour**: 

Opening a website starting with "https://click1.e*" results in blank screen

* **Expected behaviour**: 

This shouldn't be a blanket block.

<details><summary>Screenshot:</summary>

Not applicable
</details>

***Steps to reproduce the problem***:

1. Open any website starting with "https://1click.e*"

***System configuration***

**Filters:**

Base, German, Russian, EasyList Italy

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10, version 1903
Browser:                               | Reproduced across all browsers
AdGuard version:                       | 7.2.2920
Filters enabled:                       | Base, German, Russian, EasyList Italy
Stealth mode options (Windows only)    | Block 3rd-party cookies (10), Disable 3rd-party cache, Block WebRTC, Block Browser Push API, Block Browser Location API, Block Java, Block Flash, Remove X-Client-Data Header, Strip URL, Hide search queries, Send DNT Header, Hide IP (209.141.53.254)
Helpdesk ID (if exists):               | 1084832

**Comment by BlazDT** [comment]
Please post an example page.
Found one on google and redirect works for me:

click1.e.forward.com/bbfvvpcllmgymmtvyjqktybknpyjqqpqgkjmpczplcdgj_qmmmwsdfdtmgffdnsfnn.html?a=Daily+Newsletter+RSS&b=08%2F27%2F2019
