### ISSUE TITLE
http://www.espn.com/# - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4098]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: The element on the site doesn't react
* **Current behaviour**: The scores button in the upper right corner doesn't work

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/21975748/18f6eb1e-dbd7-11e6-9942-e48551b4984d.png)

</details>

* **Expected behavior**: It works fine once you disable adguard on the page

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.4.60
Simplified filters(iOS) | Off
Adguard DNS: | None 
Adguard filters: | 1.1.4.60

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1487597

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||dpm.demdex.net/id$domain=espn.com
@@||w88.espn.com/id?$domain=espn.com
@@||w88.go.com/id?$domain=espn.com
```
