### ISSUE TITLE
Add Iranian filter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4099]
Original request:
https://github.com/AdguardTeam/AdguardForiOS/issues/314

> User 1447133, has created Iran filter.
> He is asking to add his filter to Adguard.
> Here is his repository https://github.com/farrokhi/adblock-iran
> and his own filter list https://raw.githubusercontent.com/farrokhi/adblock-iran/master/filter.txt

**Comment by Alex-302** [comment]
added
