### ISSUE TITLE
wp.pl mobile

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#4100]
Original issue
https://github.com/AdguardTeam/AdguardForiOS/issues/308
```
still getting ads on wp.pl mobile (`http://www.wp.pl/mini.html`) with polish list turn on. i think some parts don't work correctly with adguard. checking same page on the computer with same list blocks all of the ads. 

sample of ads:

http://imgur.com/a/cWQX4
```

**Comment by Alex-302** [comment]
@xxcriticxx 
please check:
```
wp.pl##.header+div > div[class] > div[style*="display: block;"]
wp.pl###section_topnews > div:not([class]) > div[style] > div > a > img[style]
wp.pl###section_topnews > div:not([class]) > div[style*="text-align: center; max-width: 100%; table-layout: inherit; align-items: center; width: 300px; height: 250px; "]
wp.pl##section[class] > div > div > div[style^="display: block; min-height: 0px;"]
```

**Comment by xxcriticxx** [comment]
@Alex-302 got less ads but still have few left over on the main page

our polish list works just great on mini version of wp.pl but i think adguard doesn't understand all rules for wp.pl

**Comment by Alex-302** [comment]
iOS content blocker can use only 50000 rules. Maybe some rules are lost.
Please make a screenshots of leftovers, and, if you can, show me their code on desktop.

**Comment by xxcriticxx** [comment]
Active filter rules: 32777 that includes polish list

if i open it on the computer all the ads are blocked with polish list. if i open on my iphone i have some ads. today we have full page ads of Renault car, empty box and some cloths.

http://imgur.com/a/wKYjY

**Comment by seanl-adg** [comment]
Still you didn't specify what adblocker you are using on your computer. 
We are using many advanced blocking rules for wp.pl, ad blocking capability of iOS content blockers are limited and they don't support these.

**Comment by xxcriticxx** [comment]
@seanl-adg ublock origin on the computer

**Comment by xxcriticxx** [comment]
any news on this boys?

**Comment by Alex-302** [comment]
No:(

**Comment by seanl-adg** [comment]
They randomize urls, elements' class and id, it is hard to block within the capability of webkit content blockers. We will investigate if it is possible, but it would be better if this is addressed in your regional filter lists.

**Comment by xxcriticxx** [comment]
@seanl-adg its already addressed in pl list. but when i run pl list with Adguard on my iphone only blocks about half the ads

**Comment by seanl-adg** [comment]
> its already addressed in pl list
How do you verify that claim? @xxcriticxx

**Comment by xxcriticxx** [comment]
@seanl-adg i understand thank you for help
