### ISSUE TITLE
momondo.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4102]
***Site***: http://www.momondo.de/
***Description***: Overlay when accessing this site on mobile device.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/21991880/a07f15d8-dc14-11e6-9741-0256cccdc3d5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.6.5
Spyware filter | 1.0.10.20
Social media filter | 1.0.16.42
Annoyances filter | 1.0.8.86
German filter | 1.0.30.29
Mobile ads filter | 1.0.6.67
Safari filter | 1.0.2.13

**Comment by Alex-302** [comment]
check:
```
momondo.de#$##mui-header { display: block!important; }
momondo.de#$#.flights-section-container { display: block!important; }
momondo.de#$##mobile-splash-popup { display: none!important; }
```

**Comment by danidoedel** [comment]
@Alex-302 Yes, that works!
