### ISSUE TITLE
radikal.ru - pop-up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4103]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: The site opens full screen ads which you cannot close
* **Current behaviour**: 

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22020061/ef62622c-dcbe-11e6-9c28-c5148fc9ee24.png)

</details>

***Steps to reproduce the problem***:

1. open the site
2. upload a pic
3. see the problem

works fine on mac, reproduced on windows 10

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome 55
Adguard version: | 6.1
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | On
Adguard filters: | russian, english, social media, spyware, annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1059796

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.

**Comment by evgeniy-ADG** [comment]
У Яны на Винде повторилось, у меня на маке чисто тоже.

**Comment by evgeniy-ADG** [comment]
Нажимаем сюда

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22020362/87626ca6-dcc0-11e6-86a7-a17f1a3ba643.png)

</details>

и происходит рандомный редирект

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22020374/95e3d7ce-dcc0-11e6-874d-daebbff0b37b.png)

![image](https://cloud.githubusercontent.com/assets/15856304/22020400/bc443f58-dcc0-11e6-8488-6b0233135047.png)

**Comment by Alex-302** [comment]
Не повторяется никак.
Открой в приватной вкладке и сохрани HAR
https://toolbox.googleapps.com/apps/har_analyzer/?lang=ru

**Comment by Yana-SUP** [comment]
received a notification to download an external extension
HAR file
https://www.dropbox.com/s/0vvgdrfcunv1kwk/radikal.ru.har?dl=0

**Comment by Alex-302** [comment]
Попробуй это правило:
```
||octoclick.net/b/code/*.js$empty
```
И посмотри в журнале, есть ли octoclick.net и сделай скрин, если есть.
