### ISSUE TITLE
http://tv.liberoquotidiano.it - incorrect blocking

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4104]
Incorrect blocking on page:
http://tv.liberoquotidiano.it/video/esteri/12274770/divertimenti-casa-russi-scossa-elettrica-.html

Video Doesn't start at all with ad-blocker enabled

<details>

Application version: 1.1.4.60
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: 08B5681E-BED0-48F5-8D52-A2BDBB5C7AD3

Locale: en
Region: gb

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.4.70 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.99 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.10 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.2 Enabled=YES

</details>

Ticket ID(if exists): 1476371

**Comment by Alex-302** [comment]
It does not works on my side even without AG. Video ad is working, but not main video.
