### ISSUE TITLE
http://www.gumtree.com.au/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4105]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Falsely blocking site's header
* **Current behaviour**: It's green instead of showing the site's title

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

With Adguard

![1](https://cloud.githubusercontent.com/assets/15856304/22020557/9ef83b2e-dcc1-11e6-9091-1484c3633c83.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Should be like on the screengrab below

Screenshot:
<details>

![2](https://cloud.githubusercontent.com/assets/15856304/22020571/b039b6ba-dcc1-11e6-936f-72b041caa995.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome 55
Adguard version: | EXTENSION 2.5.11
Adguard filters: | Eng, Russian, RuAdlost, Polskie reguly

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1487535

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
not repdoruded
