### ISSUE TITLE
https://iosgods.com - ads

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4106]
https://iosgods.com/forum/13-cydia-substrate-cheats/page-2?prune_day=100&sort_by=Z-A&sort_key=last_post&topicfilter=all - missed ad

Google ads

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/22021347/6eb226ba-dcc5-11e6-9149-4d87e89c5aaf.png)

</details>

<details>

Application version: 1.1.4.60
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 131B3D39-9B40-494E-B783-6299510311A6

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.92 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.19 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.40 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.45.43 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.12 Enabled=YES

</details>

Ticket ID(if exists): 1488638

**Comment by Alex-302** [comment]
Very strange. Please try to disable all filters, except English.
