### ISSUE TITLE
https://play.google.com/store/apps/details?id=com.dcinside.app Adchoice ads in the app

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4110]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

 Adguard can block some banner ads from the list but Adchoice ads are showing on specific contents and comment. It occurs in the app, on the website Adguard blocks the ads.
* **1. Click the down arrow button marked green. http://prntscr.com/dx280t
2. You will see a list of the community.Click whatever you want. http://prntscr.com/dx286l
3. You can see the ads were blocked. But the issue is the banner ads is shown and wasn't blocked sometimes, quite frequently. http://prntscr.com/dx28ds
4. You can watch the picture with the advertisement.This issue occurs frequently http://prntscr.com/dx29j5**: 
* **The user expects to get rid of all the ads in the app https://play.google.com/store/apps/details?id=com.dcinside.app. The issue can be reproduced.**: 
***System configuration***

Information | value
--- | ---
Operating system: |  Android 6.0.1
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default) 
Adguard filters: | English filter, Spyware filter, Social media filter, Annoyances filter, Experimental filter, Mobile ads, Safari filter, Korean Adblock List filter
Ticket ID(if exists): 1488728

**Comment by seanl-adg** [comment]
Please send the user to enable `DNS request filtering` option at `Settings > Advanced`. These are ads which are served through non-standard ports, which is only possible to block with DNS request filtering as of now.

**Comment by osavranska** [comment]
Adchoice ads are blocking on adguard but other independent ads such as
"Netmarble" game promotion , other ads are still on the top and between the
list as a banner.

1. Click the red down arrow what I draw on screenshot 1.
2. You can see the list of a board, just click whatever on screenshot 2.
3. you can see a banner ads on top and scroll down middle side when you
scroll down. If there is no ads on top, that is adchoice banner I think, adguard block it. To check and see a ad banner, you need to refresh the list.
4. To refresh, click the title on white text on top or hold your finger and
drag down then you will see the refresh mark like the on screenshot 3.
Try it several times, then see ads except adchoice ads.

<details>

![1](https://cloud.githubusercontent.com/assets/23258533/22086080/b9d4855a-dddf-11e6-9f2c-1690b896e886.png)

</details>

<details>

![2](https://cloud.githubusercontent.com/assets/23258533/22086095/cd4d743e-dddf-11e6-8330-baa78d369af2.png)

</details>

<details>

![3](https://cloud.githubusercontent.com/assets/23258533/22086104/dad6d56e-dddf-11e6-982c-3061e696d902.png)

</details>

<details>

![4](https://cloud.githubusercontent.com/assets/23258533/22086116/e6e1308e-dddf-11e6-8d4d-55749004828c.png)

</details>

**Comment by seanl-adg** [comment]
Is it a response received from the user? Those ads are blocked if I enable DNS request filtering. Those are not 'independent ads' those are ads from an advertising network called "Cauly ads".
