### ISSUE TITLE
joyreactor.cc - ads

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#4111]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: opening another site when open pages on joyreactor.cc

logs in message id 1247089

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | 
Adguard version: | Adguard Pro for iOS 1.1.4.36
Simplified filters(iOS) | Off
Adguard DNS: | Default

ID=2 Name="English filter" Version=1.1.6.25 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.26 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.49 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.45.61 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.15 Enabled=YES
ID=101 Name="EasyList" Version=1.0.66.81 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.73.3 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.73.4 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.69.79 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1247089

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
На иоси не убрать... Там с помощью JS нужно, а он не поддерживается.
