### ISSUE TITLE
http://www.themarker.com/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4112]
http://www.themarker.com/markets/1.3273687

![image1](https://cloud.githubusercontent.com/assets/15856304/22067525/4fe62d14-dd9a-11e6-93b8-5440fc37aa28.png)

<details>

Application version: 1.1.4.60
Device: iPad
Platform: iOS
OS: 10.2
Optimized enabled: NO
DNS: NO
Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=101 Name="EasyList" Version=1.0.66.62 Enabled=YES
ID=108 Name="EasyList Hebrew" Version=1.0.3.89 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.72.73 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES

**Comment by Alex-302** [comment]
Not reproduced. Is redirect to dummy page instantaneous?

**Comment by evgeniy-ADG** [comment]
Yes, it redirects to that dummy page. I have reproduced in on iPad without the DNS filtering.

**Comment by Alex-302** [comment]
Strange.
I found ad marker. Is is blocked by Eng filter. Please check this rule or send to user:
```
||themarker.com/dclk/dfp/test/show_all_ads.js
```

**Comment by evgeniy-ADG** [comment]
Added, still redirects to the dummy page

**Comment by Alex-302** [comment]
fixed
