### ISSUE TITLE
eksisozluk.com

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#41124]
Sometimes you have to click on links twice to open them; does not happen with AdGuard disabled.

***Description***:
* **Current behaviour**: 

Links do not open on the first click

* **Expected behaviour**: 

Links open on the first click

***Steps to reproduce the problem***:

1. Go to eksisozluk.com
2. Click on the very first link
3. If it opened right away, go back, reload and try another link until the issue reproduced; it may require several attempts but the issue is reproducible

***System configuration***

**Filters:**

ID=2 Name="AdGuard Base filter" Version=2.0.76.14 Enabled=YES
ID=11 Name="AdGuard Mobile Ads filter" Version=2.0.7.91 Enabled=YES
ID=3 Name="AdGuard Tracking Protection filter" Version=2.0.9.33 Enabled=YES
ID=13 Name="AdGuard Turkish filter" Version=2.0.9.48 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  12.4.1 or 13
Operating system version (Android/iOS) | iOS
Browser:                               | Safari
AdGuard version:                       | 3.1.233
Filters enabled:                       | see above
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 2323483

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@Eugene-Savenko please check after 2 hours.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/b98eddb1d4dc052930efe47fe8407761ea0fa0a4
