### ISSUE TITLE
Not blocking adds on playstore app called Photo Grid

### ISSUE THREAD

**Issue by InBlis** [AdguardTeam/AdguardFilters#41172]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Not blocking ads on app Photo Grid. Link for the app 
https://play.google.com/store/apps/details?id=com.roidapp.photogrid&hl=en )

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
Not blocking ads on play store app called Photo Grid.
Link for the app 
https://play.google.com/store/apps/details?id=com.roidapp.photogrid&hl=end><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # ()

<Ads should be blocked>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Open app and it will show in app and full screen ads.)

***System configuration***

**Filters:**

[//]: # (All filters and HTTPS filtering is also on)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android) | Android
Browser:                               | ?
AdGuard version:                       | 3.2.150
Filters enabled:                       | Yes
AdGuard mode (Android only):           | Local VPN )
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On 
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | Default
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@InBlis duplicate https://github.com/AdguardTeam/AdguardFilters/issues/40974
