### ISSUE TITLE
frankfurt-airport.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4118]
***Site***: https://www.frankfurt-airport.com/de/reisen/rund-um-den-flug.html
***Description***: App notice at the top on mobile devices.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22086510/49e96ae0-ddd9-11e6-816f-0f24de65c7f5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.6.38
Spyware filter | 1.0.10.29
Social media filter | 1.0.16.53
Annoyances filter | 1.0.9.6
German filter | 1.0.30.43
Mobile ads filter | 1.0.6.70
Safari filter | 1.0.2.16

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
frankfurt-airport.com##.fra_js_app_banner
```
