### ISSUE TITLE
Targeted ads on vk.com & fasebook

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#4120]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Extension

> есть ли способ оставить активной таргетированную рекламу в VK и Facebook (по примеру «полезной рекламы»), при этом сохранив работу фильтров, блокирующих аналитику и другие трекеры?

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1490807

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Сложный вопрос. Не известно, используют ли они чужую аналитику.
Можно так попробовать
```
@@||vk.com^$domain=vk.com,urlblock
```
для fb аналогично

**Comment by nightmaar** [comment]
@Alex-302, не работает :-(

**Comment by Alex-302** [comment]
А так?
```
vk.com#@##wide_column .post[-ext-has=".wall_marked_as_ads"]
vk.com#@##apps_ads_wrap
vk.com#@##system_msg
vk.com#@#.ads_ads_news_wrap
vk.com#@#[class^="ads_ad_"]
vk.com#@#div#left_ads
vk.com#@#div[data-ad-view]
vk.com#@#div[data-ad]
vk.com#@#div[data-ads]
@@||vk.com/js/al/aes_light.js$third-party
@@||vk.com/rtrg$third-party
@@||vk.com/ads_rotate.php
```
Я не пойму цель всего этого.

**Comment by nightmaar** [comment]
@Alex-302, с этими правилами показ рекламы не начался, однако корректно заработал счетчик заблокированного; в консоли видно, что блокируются различные скрипты аналитики.

Цель простая, такая же, как и при разрешенной поисковой рекламе — таргетированная реклама в VK и FB тоже бывает релевантной и полезной.

**Comment by Alex-302** [comment]
Тогда так:
```
@@||vk.com^$document
```

**Comment by nightmaar** [comment]
@Alex-302, это правило полностью отключает фильтрацию (тумблер в расширении становится неактивным).

**Comment by Alex-302** [comment]
Тогда вручную разблокируйте необходимые домены или конкретные адреса правилами вида
```
@||blocked_domain.com$domain=site.com
```
и скорее всего понадобится отключение сокрытия:
```
@@||site.com^$elemhide
```
