### ISSUE TITLE
blogspot.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#4122]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: blocking the block of subscription in http://anatoliylefler.blogspot.com/

**help disabling Social media filter**

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/22107949/7005fe3e-de59-11e6-9123-9fac8ffda1c1.png)

</details>

* **Expected behaviour**: 

it needs for subscribe on blog

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/22107920/46e101de-de59-11e6-82d8-db620d0200e3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard filters: | 1,2,3,4,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1490873

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@vgavrish всё по делу заблокировано. Если пользователю нужны подобные виджеты, то фильтр соц сетей нужно отключить.

**Comment by vgavrish** [comment]
так кнопка нужна чтобы подписаться на блог и следить за новостями. это как подписка в вк на группу, только в google+
![image](https://cloud.githubusercontent.com/assets/18548949/22172796/435c7fa0-dfb9-11e6-84ed-772fd7b7484e.png)

**Comment by Alex-302** [comment]
ну это ж социальный виджет)
```
! Description: Filter for social media widgets (Like buttons and such).
```
