### ISSUE TITLE
https://yandex.ru - ads

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4123]
Пропущена реклама на странице: https://yandex.ru/pogoda/moscow

На этой странице погода яндекса. Справо-внизу колонка "яндекс.директ". Ваша программа его не режет, сделал фильтр как в вашем видеоруководстве.
Vpn включен, настройки свои правил на скрине, фильтры обновляются сами по себе. 

<details>

![image2](https://cloud.githubusercontent.com/assets/23258533/22111774/3ca8405a-de69-11e6-8f78-209b12f92444.png)

</details>

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/22112097/72d042f8-de6a-11e6-9ef5-9ca354ca3f01.png)

</details>

<details>

Application version: 1.1.4.36
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: C5100548-CB1E-4BD9-B13D-A1B3538512EE

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.6.18 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.24 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.48 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.92 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.45.58 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.69 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.14 Enabled=YES

</details>

Логи (Время 16:11 и 16:12):
[com.adguard.AdguardPro.tunnel.gz](https://github.com/AdguardTeam/AdguardFilters/files/716969/com.adguard.AdguardPro.tunnel.gz)

1489790

**Comment by Alex-302** [comment]
Это правило долго не проживёт. У них порядок элементов изменяется регулярно.

**Comment by evgeniy-ADG** [comment]
![image1 1](https://cloud.githubusercontent.com/assets/15856304/22618774/2c603f90-eaee-11e6-99bb-61095f2659c3.png)

[state (38).txt](https://github.com/AdguardTeam/AdguardFilters/files/752297/state.38.txt)


Вот еще, у меня не повторется. Уточните, что на такое отвечать. Если делат задачи - что просить.

**Comment by Alex-302** [comment]
На iOS сложно такое убрать. Выше писал почему.
Юзеру можно написать, что на иос(вообще в Сафари) возможности фильтрации ограничены предоставляемым яблоком контент-блокером(он умеет только блокировать http/https запросы и скрывать элементы). Расширенный CSS и JS не поддерживаются. 
Отсюда и цена не такая как для андроидной проги.
