### ISSUE TITLE
http://people.com - ads

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4124]
Missed ad on page:
http://people.com/movies/american-humane-association-investigation-a-dogs-purpose/

Ad covers the entire screen
<details>

![image1 2](https://cloud.githubusercontent.com/assets/23258533/22124033/c473aa4c-de96-11e6-83f9-6854d88d7147.png)

</details>

<details>

![image1 3](https://cloud.githubusercontent.com/assets/23258533/22124042/d2f9be12-de96-11e6-92ae-385d4e351312.png)

</details>

<details>

Application version: 1.1.4.60
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2
ID: 5E007E76-CC36-4BD0-8A7C-1BA64CE6D1EC

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.76 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.18 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.39 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.79 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.60 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.9 Enabled=YES
ID=101 Name="EasyList" Version=1.0.66.63 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.72.65 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.66.84 Enabled=YES

</details>

1369529

**Comment by Alex-302** [comment]
not reproduced. Try to disable
ID=101 Name="EasyList" Version=1.0.66.63 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.72.65 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.66.84 Enabled=YES
