### ISSUE TITLE
filecrypt.cc - Incorrect Blocking - iOS

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4128]
***Site***: https://www.filecrypt.cc/
***Description***: Site blocked on iOS devices (can't test on Android).

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22126329/9b02b7ec-de97-11e6-8350-7c5b48bee125.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Browser: | Safari
Adguard version: | 1.1.4
Adguard driver (Windows): | -
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | -

Adguard filter | Version
--- | ---
English filter | 1.1.6.48
Spyware filter | 1.0.10.30
Social media filter | 1.0.16.57
Annoyances filter | 1.0.9.15
German filter | 1.0.30.47
Mobile ads filter | 1.0.6.73
Safari filter | 1.0.2.17

**Comment by Alex-302** [comment]
Not reproduced.

**Comment by danidoedel** [comment]
@Alex-302 Still not working for me on iOS...

**Comment by Alex-302** [comment]
which wilter blocks it?

**Comment by danidoedel** [comment]
Just tested it and it's the German filter.
