### ISSUE TITLE
custom rule doesn't work - mobil.idnes.cz

### ISSUE THREAD

**Issue by Losinsky** [AdguardTeam/AdguardFilters#4130]
site: mobil.idnes.cz
Description: custom rule doesn't work

this site uses annoying background image (there is sometime background ad) which has url
https://1gr.cz/o/.................*.jpg
I have used custom rule 1gr.cz/o/ which filtered off this background in the past.
But id doesn't work just now. I don't know why 

Screenshot: ag21.gif

![ag21](https://cloud.githubusercontent.com/assets/25163965/22128375/7e1dab10-dea0-11e6-80de-7ca50d0db27b.gif)

Operating system: | Windows 7
Browser: FireFox 50 
Adguard version: 6.1

**Comment by seanl-adg** [comment]
The rule works on my end. Maybe the image is cached in your browser, try clearing cache or open the developer console and disable caching.

**Comment by Losinsky** [comment]
I cleared cache. Background image still appears. I dont't understand it because similar rules works on other sites. I am affraid there is something corrupted in my adguard instalation.

**Comment by seanl-adg** [comment]
I noticed that you have many rules in the user filter, can you post it here and post what other filters you are using? Maybe something in it is whitelisting it.

**Comment by Losinsky** [comment]
Here are my user filter rules and used lists...
[adguard_user_filter32.txt](https://github.com/AdguardTeam/AdguardFilters/files/750609/adguard_user_filter32.txt)
![ag](https://cloud.githubusercontent.com/assets/25163965/22593857/d6d7d006-ea20-11e6-872b-d4293661a16a.gif)
