### ISSUE TITLE
androidforums.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#41318]
[https://androidforums.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://androidforums.com/)

App banner displayed both to desktop and mobile browsers:

![app](https://user-images.githubusercontent.com/35470489/65788407-61162880-e131-11e9-9c87-4aafccb99624.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by BlazDT** [comment]
They have different texts for their app message, blocked all notices at top.
