### ISSUE TITLE
turktorrent.cc First Page Pop-up / Ads

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardFilters#4131]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
When you enter this website; then you click anywhere in the website, one ad page will open. But only first click.
Can you block that?

* **Current behaviour**: Pop-up

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot: i think it is not necessary if you enter this page and click anywhere you can see your own eyes :)

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS
Browser: | Chrome / Mozilla / UC Browser / Opera
Adguard version: | 2.5.11
Adguard driver (Windows): | 
Adguard mode (Android): |  Proxy(manual/auto)
Filtering quality (Android): | 
HTTPS filtering (Android): |  
Simplified filters(iOS) | 
Adguard DNS: | None 
Stealth mode options(Windows) | 
Adguard filters: | ENGLİSH, SPYWARE, SOCIAL MEDIA, Annoyances, Mobile Ads, SAFARI, TURKISH

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. I need a direct link.

**Comment by tagataho** [comment]
@Alex-302 http://turktorrent.cc/

sorry for that :)

**Comment by Alex-302** [comment]
> http://turktorrent.cc

is it on the main page? Still can't reproduce.
@seanl-adg could you check it on your side?

**Comment by tagataho** [comment]
@Alex-302 enter the website, then click username,password areas, after that you will see the ad.

screenshot:
http://prntscr.com/dz9vzo

**Comment by Alex-302** [comment]
Nothing...
Could you provide me remote access via TeamViewer?

**Comment by tagataho** [comment]
yes, do you have a skype account? i am here now

**Comment by Alex-302** [comment]
@tagataho 
**alxbrv**

**Comment by tagataho** [comment]
i added you.

**Comment by tagataho** [comment]
waiting... :)

**Comment by tagataho** [comment]
@Alex-302

**Comment by tagataho** [comment]
@Alex-302 ALEX :(

**Comment by Alex-302** [comment]
Added to Turkish filter
```
|http*://$script,third-party,xmlhttprequest,domain=turktorrent.cc
```

**Comment by tagataho** [comment]
**this is incredible, there was only one little problem. And Alex-302 work on that for 1-2 hours.
Then there is left only one way for me, this way is that buy adguard premium. 

I used bullshit adblock before, but now i see the god.**

**Comment by Alex-302** [comment]
Not hours, I needed only remote access:)

**Comment by tagataho** [comment]
@alex-302 can you block that on iOS?
 Do i open for iOS, too?

**Comment by Alex-302** [comment]
Yes. Try to add to user filter.
