### ISSUE TITLE
[Windows] Spotify sound ads

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#4132]
Logs are available at 1491006

Original thread: https://forum.adguard.com/index.php?threads/spotify-ads-no-longer-filtered.18641/#post-122687

**Comment by evgeniy-ADG** [comment]
I confirm this problem :(
![spotify isue](https://cloud.githubusercontent.com/assets/15856304/22155367/da6515f6-df37-11e6-918e-39f758d5494b.png)

**Comment by Bohdan-SUP** [comment]
Confirm on my side as well.

@Alex-302 please ping if you need some specific logs.

**Comment by vgavrish** [comment]
logs here id 1083024

**Comment by Alex-302** [comment]
We need session, captured by Fiddler with enabled HTTPS decryption(don't put it in public)

**Comment by zebrum** [comment]
any updates on this?

**Comment by zebrum** [comment]
@evgeniy-ADG @Bohdan-SUP could you help to reproduce?

**Comment by Bohdan-SUP** [comment]
@zebrum just install Spotify and listen to any radio or free playlist. Is plays every ~10-15 songs.
How can I capture the log with Fiddler?

**Comment by Alex-302** [comment]
@Bohdan-SUP is it on desktop on on Android?
How to capture traffic 
`2. How to capture traffic of the site or the application?​`
https://forum.adguard.com/index.php?threads/missed-ads-submission-rules.1879/
or I can do it via TeamViewer

**Comment by Bohdan-SUP** [comment]
Windows mostly, will test on Android as well.
Thanks for the instruction! Will capture and PM you.

**Comment by Alex-302** [comment]
@Bohdan-SUP 
also you can disable caching in Fiddler

![image](http://i90.fastpic.ru/big/2017/0210/79/240c11294fc959cc48083cf5fea63c79.png)

**Comment by ameshkov** [comment]
Guys?

**Comment by Bohdan-SUP** [comment]
They are really occasional, hard to catch..

**Comment by deLumren** [comment]
Same issue on iOS Pro.
User 1532092 provided logs. They could be found in ticket.

**Comment by Alex-302** [comment]
@deLumren 
try these rules:
```
||weblb-wg.dual-gslb.spotify.com^
||weblb-wg.gslb.spotify.com^
||adeventtracker.spotify.com^
||spclient.wg.spotify.com^
```

**Comment by abejfehr** [comment]
@deLumren @Alex-302 

What can I do to resolve this? Should I make a PR?

**Comment by Alex-302** [comment]
@abejfehr please add the rules from previous message to user filter and check again.

**Comment by abejfehr** [comment]
@Alex-302 can you elaborate? What is the user filter? I was under the impression that everyone was subject to all the rules that are in this repo if they're connected to AdGuard, so to use a rule it would have to be in master and deployed.

Since making this message I've added these URLs to my `/etc/hosts` to point to localhost and am using that instead (doesn't seem to be working though).

**Comment by Alex-302** [comment]
@abejfehr which Adguard are you using - AG for Windows, browser extension or DNS?

**Comment by abejfehr** [comment]
@Alex-302 DNS

**Comment by Alex-302** [comment]
ok. Could you, please, flush DNS cache, then run DNSQuerySniffer and Spotify 
http://www.nirsoft.net/utils/dns_query_sniffer.html
and save domains list after audio ads?
Or, you can make it by Fiddler
https://forum.adguard.com/index.php?threads/missed-ads-submission-rules.1879/
`2. How to capture traffic of the site or the application?​`

**Comment by SmartManoj** [comment]
I am getting this when using dns.adguard.com DNS.
