### ISSUE TITLE
arkade.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#41332]
[https://www.arkade.com.br/colecionador-encontrou-prototipo-de-controle-do-nintendo-64/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.arkade.com.br/colecionador-encontrou-prototipo-de-controle-do-nintendo-64/)

![share](https://user-images.githubusercontent.com/35470489/65802590-7fd8e700-e152-11e9-9103-fe45b43ea39f.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by BlazDT** [comment]
Fixed. The site should really update their share buttons, google+ is dead since months.
