### ISSUE TITLE
http://ofx.xyz -ads

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4135]
Реклама на странице:
http://ofx.xyz/multserial/9295-griffiny-family-guy-1999-hd-720.html

Когда нажимаю на просмотр видео появляется 13ти секундное ожидание. В Adguard на android такого нет и на компьютере тоже, только в iOS.

<details>

![image1](https://cloud.githubusercontent.com/assets/23258533/22167364/8eebe5d2-df6e-11e6-868a-3d454601de97.png)

</details>

<details>

Application version: 1.1.4.36
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPad
Platform: iOS
OS: 10.2
ID: AFD79949-F9A3-4E39-890C-21295BEF729C

Locale: ru
Region: ru

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.6.38 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.29 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.53 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.9.6 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.97 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.45.65 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.46 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.70 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.16 Enabled=YES

</details>

1484310

**Comment by Alex-302** [comment]
iOS не умеет в правила javascript.
