### ISSUE TITLE
http://www.avsforum.com - Incorrect blocking 

### ISSUE THREAD

**Issue by osavranska** [AdguardTeam/AdguardFilters#4136]
Incorrect blocking on page:
http://www.avsforum.com/forum/166-lcd-flat-panel-displays/1990706-2015-samsung-sek-3500u-za-evolution-kit-495.html#/topics/1990706?page=1&_k=xpayf9

When I click on the page. Miners in the bottom right of the first image. Then click on the link to last page in the second image. I just get the spinning blue wheel in the third image. I let it set for a minute and still the same. If I press the home button and then renter safari it state a problem occurred and the page needs to be reloaded. If I follow the same steps with Adguard disabled it jumps immediately to the last page.

<details>

![image1 1](https://cloud.githubusercontent.com/assets/23258533/22169004/87aadd90-df79-11e6-881e-e4e53139c025.png)

</details>

<details>

![image2](https://cloud.githubusercontent.com/assets/23258533/22169015/992c5d32-df79-11e6-800b-43722d618ed7.png)

</details>

<details>

![image4](https://cloud.githubusercontent.com/assets/23258533/22169021/abe58214-df79-11e6-8052-d8b851477c87.png)

</details>

<details>

Application version: 1.1.4.36
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.2.1
ID: 66F096A3-392A-478C-8A3E-2784711A074F

Locale: en
Region: us

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.6.13 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.23 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.44 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.90 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.69 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.14 Enabled=YES

</details>

1491172

**Comment by Alex-302** [comment]
Not reproduced on iPad.
Which filter causes it?
