### ISSUE TITLE
transfermarkt.de - Ad leftover - Social widget - Annoyance - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4137]
***Site***: http://www.transfermarkt.de/lewandowski-traumtor-beschert-bayern-sieg-gegen-freiburg/view/news/262168 and http://www.transfermarkt.de/
***Description***: 

- Ad block detection.
- Ad leftover. 
- Social widget.
- Annoying banner on mobile at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22170711/f58601d4-df81-11e6-8d97-0973794f653b.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22170704/cb49dd00-df81-11e6-97ed-6916c342a12e.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22170750/7418f970-df82-11e6-9295-7d9d3866059a.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22170758/7f1778f6-df82-11e6-8306-40ef4a4f5658.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22170779/b3343df4-df82-11e6-89dc-7015fa176c51.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22170701/bb70a422-df81-11e6-9f7c-ee91c37bdd4a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.6.63
Spyware filter | 1.0.10.31
Social media filter | 1.0.16.62
Annoyances filter | 1.0.9.18
German filter | 1.0.30.51
Mobile ads filter | 1.0.6.75
Safari filter | 1.0.2.17

**Comment by Alex-302** [comment]
added:
```
transfermarkt.de#%#adet = false;
@@||tmssl.akamaized.net//ads/ads.js

transfermarkt.de##div[id^="werbung_"]
transfermarkt.de##.mobile-werbung-inrow
```
the last is not reproduced.

**Comment by danidoedel** [comment]
@Alex-302 I found some more stuff:
http://www.transfermarkt.de/nach-afrika-cup-grant-hort-bei-ghana-auf/view/news/262345

Social widget at the top right, ad leftover at the bottom left and newsletter banner at the bottom:

![image](https://cloud.githubusercontent.com/assets/10995998/22201824/a164c2b2-e165-11e6-9e3d-b8bcb4781fc1.png)

Social share widget on every site at the bottom right (appears if you scroll down a bit):

![image](https://cloud.githubusercontent.com/assets/10995998/22201798/82917f38-e165-11e6-84c9-caecb7e5cc66.png)


I can't reproduce it right now too. Maybe I'll see it anytime soon again.

**Comment by Alex-302** [comment]
check for adblock detection without these rules
```
@@||transfermarkt.de^$genericblock,generichide
@@||transfermarkt.de^$generichide
```

**Comment by danidoedel** [comment]
@Alex-302 For me there is **no** adblock detection without these rules.

**Comment by Alex-302** [comment]
Ok, removed them.
Added:
```
transfermarkt.de###socialMediaLeisteMobilSticky
transfermarkt.de##.newsletter-anzeige
```

**Comment by danidoedel** [comment]
@Alex-302 That ad leftover is still there, everything else looks fine: 

![image](https://cloud.githubusercontent.com/assets/10995998/22274865/34434790-e2a9-11e6-84dd-7302a347d20d.png)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
transfermarkt.de##div[style="margin-top:20px;"] > div.fl
```
