### ISSUE TITLE
fussball.de - Ads - Social widget - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4138]
***Site***: http://www.fussball.de/ and http://www.fussball.de/newsdetail/anti-gewalt-schiris-trainieren-deeskalation/-/article-id/160734#!/section/stage
***Description***: 

- "content-block" overlay when accessing the site.
- Ads.
- Social widget.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22170809/034b8dc4-df83-11e6-8417-bc0e030baa2d.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22170827/2e312094-df83-11e6-9b77-aafc2fe3609d.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22170843/7f17cf12-df83-11e6-939f-2907d9834dbf.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22170864/ccc441a0-df83-11e6-83a8-b37102a74ea0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.6.63
Spyware filter | 1.0.10.31
Social media filter | 1.0.16.62
Annoyances filter | 1.0.9.18
German filter | 1.0.30.51
Mobile ads filter | 1.0.6.75
Safari filter | 1.0.2.17

**Comment by Alex-302** [comment]
added
```
fussball.de##.in-page-share
fussball.de###sharing
fussball.de##div[data-ng-click="closeFlyout()"]
fussball.de##.sponsor
fussball.de##div[data-ad]
fussball.de###news-sidebar div.sidebar-teaser[-ext-has='div[data-ad]']
fussball.de##.news-teaser-banner
```
