### ISSUE TITLE
digit.in [Ad Text Strings]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#41396]
**Site**: https://www.digit.in/news/mobile-phones/oneplus-explains-why-theres-no-notification-led-on-the-onplus-6t-in-an-ama-44506.html

**Issue**: Please remove the Ad text strings seen at various places on the page and possibly other pages.

**Screenshot**: http://prntscr.com/pcdkwy

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 77.0.3865.90 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 3.2.1	 `

**Filters**:
```
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404
NoCoin Filter List

```

**Stealth Mode Settings**:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled (Default)

**Comment by krystian3w** [comment]
Try:

```
digit.in##div > .adsAdvert
```
