### ISSUE TITLE
hi-tech.mail.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#4140]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: ads in page 
https://hi-tech.mail.ru/news/nokia-6-sold-out/

User filter is empty

maybe its help
[debug (29).txt](https://github.com/AdguardTeam/AdguardFilters/files/720992/debug.29.txt)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/22172919/0f9012ec-dfbc-11e6-9677-f69b8f2154fc.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Firefox
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard filters: | 1,2,3,4,10

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1437937

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
removed
```
@@||ad.mail.ru/adq/?callback=jQuery$domain=mail.ru
```
check for adblo detection(usually - unhiding of ads)
