### ISSUE TITLE
meduza.io

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#4141]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
can we block the future block wiht ads?
https://meduza.io/feature/2017/01/20/s-segodnyashnego-dnya-amerika-prezhde-vsego
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/22173174/3d2c0006-dfc3-11e6-9907-23040ba853b5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | IE, Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Adguard filters: | 1,2,3,4,14

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
поправил в раздражителях
