### ISSUE TITLE
discordapp.com

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#41429]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

The entry `##iframe[width="240"][height="300"]` in AdGuard Base Filter is under certain circumstances causing embedded Twitter videos to fail to show up or to be played.

* **Current behaviour**: 

The video fails to play back, and instead turns to grey with no sound once its thumbnail is clicked on.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/65837530-d1bb7180-e2f8-11e9-9af4-2c4e81f265b6.png)

</details><br/>

* **Expected behaviour**: 

The video is correctly played back.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/65837547-fc0d2f00-e2f8-11e9-90ad-266bb24222b9.png)

</details><br/>

***Steps to reproduce the problem***:

1) Post a link in any Discord server (except those that have turned off link embeds entirely), to a tweet that has a video in ~4:5 aspect ratio. For instance https://twitter.com/HoIdMyBeaker/status/1178329459876712453.
2) Make sure you've turned on the Discord setting that shows link previews/embeds.
3) Click on the embed.
4) See that it turns to a grey still image.

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/65837584-7938a400-e2f9-11e9-8ea5-d7ca2a10e15f.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) |
Browser:                               | Google Chrome 77 64-bit
AdGuard version:                       | Nano Adblocker 1.0.0.127 + Nano Defender 15.0.0.168
Filters enabled:                       | See screenshot of Nano Adblocker settings above.
AdGuard mode (Android only):           |
Filtering quality (Android only):      |
HTTPS filtering (Android only):        |
Simplified filters (iOS only)          |
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by krystian3w** [comment]
`@@||twitter.com^$generichide` works? Or this is "about:blank" iframes: https://github.com/uBlockOrigin/uBlock-issues/issues/688

**Comment by DandelionSprout** [comment]
In my eyes, the problem is simply about Twitter video embeds that use very specific sizing and size-related CSS values. It doesn't seem to be any more complicated than that. 
![image](https://user-images.githubusercontent.com/22780683/65839609-eefb3a80-e30e-11e9-9d33-a4df8620a999.png)

**Comment by DandelionSprout** [comment]
So `@@||twitter.com^$generichide` has no effect on it, and I'm currently presuming the fix would be `discordapp.com#@#iframe[width="240"][height="300"]` or something very similar.

**Comment by krystian3w** [comment]
Strange...

https://github.com/AdguardTeam/AdguardFilters/blob/e09034dd748253ce7f39ba263b1bc88014675986/EnglishFilter/sections/banner_sizes.txt#L56

`@@||discordapp.com^$generichide`

or (maybe invalid...):

`@@||discordapp.com^$generichide,domain=twitter.com`

**Comment by DandelionSprout** [comment]
`@@||discordapp.com^$generichide` does work, but seems very drastic to me, so I'd reserve it as a plan B.

`@@||discordapp.com^$generichide,domain=twitter.com` unfortunately doesn't work.

**Comment by krystian3w** [comment]
Why, discord in my logger no have any filters to block network or hide elements (so no have tracking / ads).

**Comment by DandelionSprout** [comment]
That is true. Discord is pretty kind by having no tracking and almost no ads.

But this is only really the 2nd generic-entry-related problem I've come across on Discord after being there for 6 months (The 1st being https://github.com/uBlockOrigin/uAssets/issues/5883), so at the current point in time I think the amount of individual problems are few enough that they can be dealt with individually.

**Comment by AdamWr** [comment]
Fixed, thank you.
