### ISSUE TITLE
Outlook app for iOS - cannot contact outlook support when the DNS filtering's on

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4142]
Can't contact support from within Outlook App with DNS Filter enabled

![file_000](https://cloud.githubusercontent.com/assets/15856304/22173366/1c839778-dfc9-11e6-95d8-9ac9ce2ac0ed.png)

<details>

![image1 1](https://cloud.githubusercontent.com/assets/15856304/22173346/9459b1ac-dfc8-11e6-950c-54ed64dcb233.png)

Logs: 1117386

**Comment by Alex-302** [comment]
Что на втором скрине?  Какой ДНС, чья поддержка? Давай хоть какой-то комментарий.

**Comment by evgeniy-ADG** [comment]
Открываешь приложение, идешь в раздел Порддержка, пишешь письмо и видишь то, что на скрине. Под катом заблокированный запрос.

**Comment by Alex-302** [comment]
Странно, вроде тот запрос не заблокирован. У меня похожего нет, заблокированных тоже, но отправка с ДНС не работает.
@vozersky глянь плиз, может из-за самого факта использования DNS не работает?

**Comment by vozersky** [comment]
@Alex-302 Повторилось.
Похоже, что нет, с opendns работает нормально.

**Comment by Alex-302** [comment]
У меня без фильтров ничего заблокированного в логе нет. А у тебя?

**Comment by vozersky** [comment]
ничего заблокированного в логе не вижу, ага

**Comment by Alex-302** [comment]
значит сам ДНС как-то ломает) Передашь куда следует?

**Comment by vozersky** [comment]
перенес в DNS
@Alex-302 а не может быть багом iOS-версии все-таки?

**Comment by Alex-302** [comment]
откуда ж я знаю?)

**Comment by ameshkov** [comment]
ДНС тут ни при чем, только если iOS

**Comment by IvanIin** [comment]
@Alex-302  проверил на ios. Блокируется адрес acompli.helpshift.com . Если его в белый список добавить - то норм работает.

**Comment by Alex-302** [comment]
@IvanIin спасибо, убрал
```
||acompli.helpshift.com^
```
