### ISSUE TITLE
allmusic.com

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#4143]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: allmusic.com
http://www.allmusic.com/album/hang-mw0002997485

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/22174002/a52c8d84-dfdb-11e6-90d9-9495b12dbadf.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard filters: | 1,2,3,4,14,211

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 734231

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
temporary solution for user
```
@@/(outbrain)|(taboola)|(doubleverify)|(adchoice)|(pubads)|(adsystem)|(\/adnexus-)|(\.openx\.)|(moatad)|(\/us-ads\.)|(adserver)|(1rx)|(safeframe)|(advert)|(revcontent)/$domain=allmusic.com
@@||c.amazon-adsystem.com/aax2/amzn_ads.js
@@||allmedia-d.openx.net/*/jstag?nc=*-SideReel
```

**Comment by Alex-302** [comment]
also you can try
```
||allmusic.com^$replace=/_0xe367/0xFFFF/,important
```

**Comment by Alex-302** [comment]
@seanl-adg Could you try to make JS rule?

**Comment by seanl-adg** [comment]
@Alex-302
```
allmusic.com#%#(function(b){window.setTimeout=new Proxy(function(){},{apply:function(d,a,c){return/^function _0x[a-z0-9]{0,8}\([\s\S]*?_0x[a-z0-9]{0,8}\[_0x[a-z0-9]{0,8}\[\d+\]\]/.test(c[0].toString())?1:b.apply(a,c)},get:function(d,a){return"toString"==a?function(){this.toString=Function.prototype.toString;return b.toString()}:b[a]},set:function(d,a,c){b[a]=c}})})(window.setTimeout);
``` 
is working on my end.
If confirmed I'll add it.

**Comment by Alex-302** [comment]
@seanl-adg it works:)

**Comment by seanl-adg** [comment]
@Alex-302 we need exception rules for Safari filter too
```
@@||allmedia-d.openx.net/*/jstag?nc=*-SideReel
@@||b.scorecardresearch.com/beacon.js^$domain=allmusic.com
@@/(doubleclick\.net\/trackimpj\/)|(doubleclick\.net\/ddm\/adj\/)/i$image,domain=allmusic.com
@@/(doubleclick\.net\/trackimp\/)|(doubleclick\.net\/ddm\/ad\/)/i$script,other,domain=allmusic.com
@@||tpc.googlesyndication.com/safeframe/$domain=allmusic.com
```
seems to be working on my end without JS rules. Could you check?

**Comment by Alex-302** [comment]
on iOS it works without additional rules.
In safari on mac with this:
```
@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$domain=allmusic.com
```

**Comment by ghajini** [comment]
issue is back on allmusic.com

**Comment by seanl-adg** [comment]
@ghajini Hi, I was unable to reproduce the issue.
Please provide more information including what software and browser you are using, if you are still experiencing the issue.

**Comment by ghajini** [comment]
`http://www.allmusic.com/newreleases/all`

`http://www.allmusic.com/newreleases`

i get antiadblock notice on allmusic randomly like playing more music and surfing....
![screenshot 155](https://cloud.githubusercontent.com/assets/20338483/23512147/a54f8004-ff85-11e6-9d2e-0822d09e4940.png)

**Comment by seanl-adg** [comment]
@ghajini 
Hi, I confirm that sometimes the detection shows up with browser extensions.
However, this is due to the current limitation of Adgaurd browser extensions. 
Adguard browser extensions cannot execute javascript injection rules early enough, and allmusic.com's anti-adblock script is located in an early part of the page, so sometimes their script runs first.
We don't have such limitations on standalone softwares. It will be improved in browser extensions when what's don in https://github.com/AdguardTeam/AdguardBrowserExtension/issues/512 is shipped.
