### ISSUE TITLE
http://online-journaloff.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4144]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Ads on the site
* **Current behaviour**: They are not blocked: http://online-journaloff.ru/sad_i_ogorod

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22174007/b8d7c66e-dfdb-11e6-9db6-db357be7a187.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS / Android / Linux
Browser: | All
Adguard version: | 
Adguard driver (Windows): | WFP / TDI both
Adguard filters: | 2 3 4 6 10

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1027688

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
