### ISSUE TITLE
http://www.turkanime.tv/ Adblock Warning 

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardFilters#4146]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
Hi
http://www.turkanime.tv/
There is Adblock warning issue in this website. You can see when you enter the website.
* **Current behaviour**:  Please fix it.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot: http://prntscr.com/dyi34z

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS /
Browser: | Chrome, Mozilla 
Adguard version: | 6.12
Adguard driver (Windows): | WFP 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): |  
Simplified filters(iOS) | 
Adguard DNS: | None 
Stealth mode options(Windows) | 
Adguard filters: | ENGLISH, SPYWARE, SOCIAL MEDIA, ANNOYANCES, TURKISH, ADBLOCK WARNING REMOVAL LIST

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
not reproduced with Turkish filter. Try without ADBLOCK WARNING REMOVAL LIST

**Comment by tagataho** [comment]
@Alex-302 no, i want to use adblock warning removal list.
Please can you fix it :+1:

**Comment by Alex-302** [comment]
just try. It is for test only

**Comment by tagataho** [comment]
@alex-302

i tested as you said. but nothing changed. :(

**Comment by tagataho** [comment]
Still continue this problem...
http://prntscr.com/efu2l7

**Comment by Alex-302** [comment]
Reproduced it now.
Added to Turkish filter
```
turkanime.tv##.modal-backdrop.fade.in
turkanime.tv##.modal.fade.in
```
