### ISSUE TITLE
[Windows] www.stern.de - Missed Ads

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#4147]
![](http://i.imgur.com/gE00olv.gif)
http://www.stern.de/digital/online/amazon-schlaegt-online-supermaerkte-wie-rewe-und-bringmeister-um-laengen-7292936.html

and this rule trigger video ads too

blame rule:
``` @@||www.stern.de^$genericblock,generichide ```

**Adguard version**: 6.1.298.1564

**Operating system**: Windows 10

**Browser**: Chrome

**Comment by Alex-302** [comment]
could you, please, check these sites?
Disable
```
@@||autobild.de^$genericblock,generichide
@@||gala.de^$genericblock,generichide
@@||ran.de^$genericblock,generichide
@@||spiegel.de^$genericblock,generichide
@@||transfermarkt.de^$genericblock,generichide
@@||www.stern.de^$genericblock,generichide
```
and add
```
@@||autobild.de^$generichide
@@||gala.de^$generichide
@@||ran.de^$generichide
@@||spiegel.de^$generichide
@@||transfermarkt.de^$generichide
@@||www.stern.de^$generichide
```

**Comment by Vincent-Michael** [comment]
@Alex-302 

works fine:
> @@||autobild.de^$generichide
@@||gala.de^$generichide
@@||ran.de^$generichide
@@||spiegel.de^$generichide
@@||www.stern.de^$generichide

transfermarkt.de has some problem with anti adblock:
![](http://i.imgur.com/UPQmCeO.png)
http://www.transfermarkt.de/rb-bleibt-an-bayern-dran-ndash-rot-fur-sge-torwart-nach-120-sekunden/view/news/262218

This rule does not work at the moment: ```||tmssl.akamaized.net//ads/ads.js$domain=transfermarkt.de```

with adguard: ![](http://i.imgur.com/wHUhDig.png)
without adguard: ![](http://i.imgur.com/V8YcEy8.png)

workround rule (works fine):  ``` transfermarkt.de#%#adet = false; ```

**Comment by danidoedel** [comment]
transfermarkt already reported here: #4137

**Comment by Alex-302** [comment]
thanks.
Excluded:
```
@@||autobild.de^$genericblock,generichide
@@||gala.de^$genericblock,generichide
@@||ran.de^$genericblock,generichide
@@||spiegel.de^$genericblock,generichide
@@||www.stern.de^$genericblock,generichide
```
added:
```
@@||autobild.de^$generichide
@@||gala.de^$generichide
@@||ran.de^$generichide
@@||spiegel.de^$generichide
@@||transfermarkt.de^$generichide
@@||www.stern.de^$generichide
```


> transfermarkt already reported here: #4137

I will answer in that issue.
