### ISSUE TITLE
bundesliga.de - Annoyance - Ads - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4148]
***Site***: http://www.bundesliga.de/de/ and http://www.bundesliga.de/de/liga/news/die-stimmen-zum-17-spieltag-bundesliga-blmd17n.jsp
***Description***: 

- Smartbanner on mobile devices.
- Sponsors ads.
- Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22178206/cd38e7fa-e030-11e6-893f-fa0bb404144b.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22178209/dc02aa64-e030-11e6-856b-dbdf5a621c95.png)

( http://www.bundesliga.de/de/liga/news/die-stimmen-zum-17-spieltag-bundesliga-blmd17n.jsp )

![image](https://cloud.githubusercontent.com/assets/10995998/22178219/1b2eaeea-e031-11e6-9596-c0d55ce1bda9.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.6.78
Spyware filter | 1.0.10.32
Social media filter | 1.0.16.62
Annoyances filter | 1.0.9.19
German filter | 1.0.30.54
Mobile ads filter | 1.0.6.75
Safari filter | 1.0.2.17

**Comment by Alex-302** [comment]
added
```
bundesliga.de###smartbanner
bundesliga.de##.banner
bundesliga.de##.partnerlist
```
