### ISSUE TITLE
waz.de - Ad leftover - Social widget - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4150]
***Site***: http://www.waz.de/
***Description***: 

- Ad leftover. 
- Social widget.
- Survey banner.

Same rules apply for the other sites of the network:

- http://www.nrz.de/
- http://www.wp.de/
- http://www.wr.de/
- http://www.ikz-online.de/

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22178409/7787e91e-e035-11e6-8adb-e517d6236fa2.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22178410/89757768-e035-11e6-829e-290f7d15115b.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22178502/56a146ca-e038-11e6-9b22-37d4556ecaa7.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22178504/69d84720-e038-11e6-99cc-40def1a8d25a.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22178507/75fb6ffa-e038-11e6-8c7e-4825d2f469f9.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22178523/f5496226-e038-11e6-8fe4-1ba6705daf23.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.6.78
Spyware filter | 1.0.10.32
Social media filter | 1.0.16.62
Annoyances filter | 1.0.9.19
German filter | 1.0.30.54
Mobile ads filter | 1.0.6.75
Safari filter | 1.0.2.17

**Comment by danidoedel** [comment]
@seanl-adg I missed an social widget leftover in articles like http://www.waz.de/staedte/oberhausen/afd-nrw-geht-gerichtlich-gegen-die-stadt-oberhausen-vor-id209368801.html:

![image](https://cloud.githubusercontent.com/assets/10995998/22208667/f7e53c16-e183-11e6-9069-7ff4ba0bf9c1.png)

Without that element the text can use the whole width of the page and that's how it should look like:

![image](https://cloud.githubusercontent.com/assets/10995998/22208798/676685f4-e184-11e6-92c5-1586feaf64a8.png)


**Same rule applies again to all of these sites.**

**Comment by Alex-302** [comment]
added
`waz.de,nrz.de,wp.de,wr.de,ikz-online.de##div.sidebar__column > div.content-options div.content-options[-ext-has="span.block-header__icon:contains(Facebook)"]`
