### ISSUE TITLE
site with ads - https://www.anekdot.ru 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4151]
[//]: # (*** )
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***site with ads - https://www.anekdot.ru***:

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (http://prnt.sc/dyqjzm)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***Android***

Information | value
--- | ---
Operating system: | Android 
Browser: | Samsung Browser 
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None 

Adguard filters: | 

[//]: # (***2, 3, 4, 14, 1, 5, 11)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1491070

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||jsc.marketgid.com/*/anekdot.ru.*.js$empty,important
```
Нужно чтоб юзер проверил и отписался. Правило в фильтре часа через два будет.

**Comment by evgeniy-ADG** [comment]
Не помогло, у меня есть этот баннер сейчас.

**Comment by Alex-302** [comment]
Ну так сколько времени прошло. Добавил новых правил.
