### ISSUE TITLE
http://www.rte.ie/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4152]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Adblock detected when playing videos from RTE player

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22181663/45a0a3e6-e099-11e6-83c0-cb96a7ad8829.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome 55
Adguard version: | 1.4
Adguard filters: | 2 3 4 10 1 7 113 121

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1406620

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||bs.serving-sys.com/crossdomain.xml$domain=rte.ie
```
@evgeniy-ADG попроси юзер отписаться, а то у меня не все ролики работают.

**Comment by evgeniy-ADG** [comment]
Done
