### ISSUE TITLE
m.heise.de - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4153]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: The green banner on the top (Abonnieren)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22181785/f77052f4-e09b-11e6-8983-ba336302a51a.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.4.60
Simplified filters(iOS) | On
Adguard DNS: | None
Adguard filters: | 2 3 4 6 14 11 12 229

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
m.heise.de##.mheise--preisvergleich-banner
```
