### ISSUE TITLE
PinkSluts.com - Blocked images (AdGuard Social Media filter) [NSFW]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#41538]
### Affected site:
`http://pinksluts.com/` **[NSFW]**

### Issue:
All images are blocked!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* AdGuard Social Media filter

### Problem rule:
`~businessinsider.com,~popcrush.com,~tasteofcountry.com,~disk.yandex.by,~disk.yandex.com,~disk.yandex.com.tr,~disk.yandex.kz,~disk.yandex.ru,~disk.yandex.ua##.share-link`

### Possible fix:
```
- ~businessinsider.com,~popcrush.com,~tasteofcountry.com,~disk.yandex.by,~disk.yandex.com,~disk.yandex.com.tr,~disk.yandex.kz,~disk.yandex.ru,~disk.yandex.ua##.share-link
+ ~businessinsider.com,~pinksluts.com,~popcrush.com,~tasteofcountry.com,~disk.yandex.by,~disk.yandex.com,~disk.yandex.com.tr,~disk.yandex.kz,~disk.yandex.ru,~disk.yandex.ua##.share-link
```

### Other problem filters:
* Fanboy's Annoyance List
* Fanboy's Social Blocking List
https://github.com/ryanbr/fanboy-adblock/issues/1195/

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.7.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by AdamWr** [comment]
Fixed.
Thank you.
