### ISSUE TITLE
Investing.com iOS app - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4154]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: The ads are not blocked in [this](https://appsto.re/tr/QGxp2.i) app

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image1 2](https://cloud.githubusercontent.com/assets/15856304/22181805/a3d0752e-e09c-11e6-995c-99983ff4a7bd.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | -
Adguard version: | 1.1.4.36
Simplified filters(iOS) | OFF
Adguard DNS: | Default 
Adguard filters: | 2 3 4 11 12 13 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID (and filtering logs): 1492006

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced in Safari on Mac and iPad.
