### ISSUE TITLE
http://m.imore.com/ - anti-adblocker script

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4155]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: The message pops up everytime you access the site

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image1 3](https://cloud.githubusercontent.com/assets/15856304/22181859/17063dac-e09e-11e6-8fee-4961b1d4b9eb.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.4.36
Simplified filters(iOS) | Off
Adguard DNS: | Default
Stealth mode options(Windows) | 
Adguard filters: | 2 3 4 14 5 11 12 211 207

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1010685

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Will be fixed in next app build. $generichide exclusion is not working at the moment.
