### ISSUE TITLE
speakingtree.in [AdBlock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#41573]
**Site**: https://www.speakingtree.in/blog/natural-ways-to-increase-your-memory

**Issue**: Please remove the Ad block message seenn on the page.

**Screenshot**: http://prntscr.com/pdr27v

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 77.0.3865.90 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 3.2.1	 `

**Filters**:
```
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404
NoCoin Filter List

```

**Stealth Mode Settings**:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled (Default)

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
