### ISSUE TITLE
Блокировка рекламы

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#4158]
Буду краток (привет @Alex-302) . Сайт http://bobfilm.tv При входе появляется баннер. Ссылка на скрин ниже. Версия эдгуарда последняя, фильтры по-умолчанию, HTTPS Фильтрация качественная http://i079.radikal.ru/1701/39/86f21ac3f5cb.png

**Comment by Alex-302** [comment]
поправил

**Comment by ministr91** [comment]
Обновил, эффекта нет. С мобильного телефона . попробуй сам зайти @Alex-302

**Comment by Alex-302** [comment]
рано. Минимум час жди.

**Comment by ministr91** [comment]
А где метка темы? Раньше всегда была..

**Comment by ministr91** [comment]
Ну ладно, беж метки проживу

**Comment by Alex-302** [comment]
Так устроит?:)
В название тему сайт надо добавлять. Его достаточно, и быстрее вставить, чем текст набирать.

**Comment by ministr91** [comment]
метка Invalid  не очень, ну да ладно
