### ISSUE TITLE
https://gebrauchte-veranstaltungstechnik.de - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4159]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: It redirects to a dummy page: https://gebrauchte-veranstaltungstechnik.de/adblock.de.html

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22194194/5a56ab90-e149-11e6-9766-15e9bca82b26.png)

</details>

Information | value
--- | ---
Operating system: | all
Browser: | Chrome
Adguard version: | 1.4 for Mac, 1.1.4.36 iOS
Simplified filters(iOS) | Off
Adguard DNS: | Default
Adguard filters: | 2 3 4 6 12 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1459423

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to German filter
```
@@||gebrauchte-veranstaltungstechnik.de/assets/js/ads.js
```
