### ISSUE TITLE
http://fishki.net/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4160]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: The [link](http://fishki.net/2196638-donalyd-tramp-oficialyno-stal-prezidentom-ssha.html?mode=recent)

***Current behaviour**: 

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22194288/17057532-e14a-11e6-89c8-a52da2db1332.png)

![image](https://cloud.githubusercontent.com/assets/15856304/22194323/5e93af0e-e14a-11e6-87ab-b01653066132.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | IOS
Browser: | SAFARI
Adguard version: | THE CURRENT ONE
Simplified filters(iOS) | Off
Adguard DNS: | Default
Adguard filters: | 2 3 4 1 11 12 101 115 213 212

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): **1492872**

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Первый не повторяется.
Добавил:
```
fishki.net##.fixed-promo
```
