### ISSUE TITLE
Xender app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4161]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Missed banner in the app
Here's the link: [link](https://play.google.com/store/apps/details?id=cn.xender&hl=en)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screenshot_2017-01-21-07-53-52](https://cloud.githubusercontent.com/assets/15856304/22195386/664fae68-e150-11e6-9bc1-6711f617adb8.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

1. Download the app
2. Open the app
3. See the banner labeled with 'Ad'

***System configuration***

Information | value
--- | ---
Operating system: | Android
Adguard version: | 2.8.76
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None
Adguard filters: | 2, 3, 4, 11

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID (with the HTTP log): 1483223 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is clean on my end. Try to clean app's cache.
Added
```
||appwall.tv2phone.cn^
||ads.pdbarea.com^
```

**Comment by ankitkumarbh** [comment]
Hi, I have cleared xender app cache.
And Added rules
||ads.pdbarea.com^
||appwall.tv2phone.cn^
But, Unfortunately I am still getting ads in xender app.

**Comment by Alex-302** [comment]
Strange. Send me new HTTP log(with time of app starting).

**Comment by zebrum** [comment]
@ankitkumarbh  at what time the app was started?
@Alex-302 
[debug (17).txt.zip](https://github.com/AdguardTeam/AdguardFilters/files/732003/debug.17.txt.zip)

**Comment by Alex-302** [comment]
@zebrum please ask for HAR file. I need to see content of some requests.

**Comment by Alex-302** [comment]
Also, user can check these rules(trackers and possible advertising):
```
||logger.ntracecloud.com^
||ymtracking.com^
||api.mobojoy.baidu.com/strategy/api/v1/rule/get?p=com.adslib.
||baidu.com/setting/grobal_strategy?p=com.adslib.
```

**Comment by zebrum** [comment]
sorry for misunderstanding  
@ankitkumarbh collect logs with this instruction, please: https://kb.adguard.com/index.php?/english/Knowledgebase/Article/View/65/9/how-to-get-har-http-archive-files-from-android-device

**Comment by ankitkumarbh** [comment]
[adguard.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/734271/adguard.har.zip)
Hi, Alex
Here's my har file.

**Comment by ankitkumarbh** [comment]
Hi, @Alex-302
I use these rules.
||logger.ntracecloud.com^
||ymtracking.com^
||api.mobojoy.baidu.com/strategy/api/v1/rule/get?p=com.adslib
||baidu.com/setting/grobal_strategy?p=com.adslib
But, Ads is still loading.

**Comment by Alex-302** [comment]
@ankitkumarbh did you try to clear app's cache?

**Comment by ankitkumarbh** [comment]
Yeah, I always do.

**Comment by ankitkumarbh** [comment]
Hi, @Alex-302
I have also try to uninstall and re-install Xender app.
But Ads is still loading.

**Comment by Alex-302** [comment]
Strange.
Please make new HTTP log without removing that rules.

**Comment by ankitkumarbh** [comment]
ok
only log? or har file?
Yes, I'm using vpn mode?

**Comment by Alex-302** [comment]
> only log? or har file?

both files:)

**Comment by Alex-302** [comment]
and screenshot of current ad

**Comment by ankitkumarbh** [comment]
[Log+HAR+Screenshot.zip](https://github.com/AdguardTeam/AdguardFilters/files/735624/Log.HAR.Screenshot.zip)
Here,
All files are in zip.

**Comment by Alex-302** [comment]
Try this:
```
||glispa.com^$app=cn.xender
```
not sure if leftovers will be removed

**Comment by ankitkumarbh** [comment]
Hi, @Alex-302
I also tried:
||glispa.com^$app=cn.xender
But, Ads is still loading.

**Comment by Alex-302** [comment]
ok, make new HAR:)

**Comment by ankitkumarbh** [comment]
[HAR file.zip](https://github.com/AdguardTeam/AdguardFilters/files/737624/HAR.file.zip)

**Comment by Alex-302** [comment]
try this:)
```
||ymcdn.ymtrack6.co/offer_single_files/
||ymcdn.ymtrack6.co/ads_file/
```

**Comment by ankitkumarbh** [comment]
This new rule is not working.
Ads is loading again and again.
I have also make new har file.
[Har.zip](https://github.com/AdguardTeam/AdguardFilters/files/738017/Har.zip)

**Comment by Alex-302** [comment]
This ad? Should be blocked by `||ymcdn.ymtrack6.co/ads_file/`
<details>

![image](http://imagizer.imageshack.com/img921/5854/qDStQR.jpg)
</details>

**Comment by ankitkumarbh** [comment]
But, Ads is still loading. :-(

**Comment by Alex-302** [comment]
damn. Please make clean FULL log, and write time, when you launch this app.

**Comment by ankitkumarbh** [comment]
App Launch time> 9:09pm
& here is full log:- 
[Full Log File.zip](https://github.com/AdguardTeam/AdguardFilters/files/739401/Full.Log.File.zip)

**Comment by Alex-302** [comment]
thanks. 
Go to low level settings and add port `20001` to `pref.filtered.ports', restart protection and make new HAR.

**Comment by ankitkumarbh** [comment]
[har.zip](https://github.com/AdguardTeam/AdguardFilters/files/741107/har.zip)

**Comment by ankitkumarbh** [comment]
[har.zip](https://github.com/AdguardTeam/AdguardFilters/files/741107/har.zip)

**Comment by Alex-302** [comment]
I can't find ad image. Could you make HAR with screenshot? You can switch log mode to "record http requests"

**Comment by ankitkumarbh** [comment]
Hi,
When, I use port 20001. then ads is not loading but internet speed goes too slow.
When, I remove port 20001, then ads is loading & internet speed is good.

**Comment by Alex-302** [comment]
> internet speed goes too slow.

in this app only, or on device?

**Comment by ankitkumarbh** [comment]
On device

**Comment by Alex-302** [comment]
What device do you have?

**Comment by ankitkumarbh** [comment]
Forget about my device.
I tried another device.
1. I enabled https filtering.
2. Added port 20001 to `pref.filtered.ports',.
I got that 
Ads is not loading anymore in xender app.
Congratulation,
Problem has solved.

**Comment by ankitkumarbh** [comment]
& no need to add any rules.

**Comment by Alex-302** [comment]
ok then. Thank you for your time.

**Comment by ankitkumarbh** [comment]
Thanks to you.
