### ISSUE TITLE
tuasaude.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#41626]
[https://www.tuasaude.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.tuasaude.com/)

![cookie](https://user-images.githubusercontent.com/35470489/66088106-4e945880-e550-11e9-8b7f-005ab56396b3.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by BlazDT** [comment]
Not reproduced, please check @zloyden

**Comment by zloyden** [comment]
I was able to reproduce it.
