### ISSUE TITLE
http://vsegdazdorov.net/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4162]
http://vsegdazdorov.net/story/tabletki-dlya-uskoreniya-obmena-veshchestv

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22202616/9cd679aa-e171-11e6-8f5e-1e78a60d9d28.png)

![image](https://cloud.githubusercontent.com/assets/15856304/22202629/ad8de864-e171-11e6-8102-b7f64eac9f2e.png)

</details>

Information | value
--- | ---
Operating system: | Microsoft Windows NT 6.1.7601 Service Pack 1 
Browser: | Chrome
Adguard version: | 6.1.258.1302
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Stealth mode options(Windows) | enabled
Adguard filters: | 1 2 3 4 10

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||vsegdazdorov.net/sites/zdorov/files/advagg_js/
```
