### ISSUE TITLE
rtl.de - Ad leftover - Social widget - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4163]
***Site***: http://www.rtl.de/cms/index.html
***Description***: 

- Ad leftovers. 
- Social widgets.
- Annoyance (mobile banner, video blocked)

<details>
<summary>Screenshot</summary>

Ad leftover appears a few times here (http://www.rtl.de/cms/index.html):

![image](https://cloud.githubusercontent.com/assets/10995998/22202482/9d4379dc-e168-11e6-9ef2-707c922890e8.png)

http://www.rtl.de/sendungen/gute-zeiten-schlechte-zeiten-2496953.html:

![image](https://cloud.githubusercontent.com/assets/10995998/22202521/c744f80a-e168-11e6-80bb-a1d0d7b963f7.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22202529/d5920c5e-e168-11e6-9363-4d6c8923688a.png)

If you try to play the video in private browsing mode there is a message you can't watch the video in this mode. Not sure if that could be blocked/changed?

http://www.rtl.de/cms/dschungelcamp-2017-kader-loth-findet-hanka-rackwitz-zum-anbeissen-4072114.html

![image](https://cloud.githubusercontent.com/assets/10995998/22202647/5fa06d5a-e169-11e6-9c75-56644d88e8d6.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
.English filter | 1.1.7.1
Spyware filter | 1.0.10.34
Social media filter | 1.0.16.66
Annoyances filter | 1.0.9.22
German filter | 1.0.30.58
Mobile ads filter | 1.0.6.76
Safari filter | 1.0.2.18

**Comment by Alex-302** [comment]
> If you try to play the video in private browsing mode

seems to be working.

Added to Mobile filter
```
rtl.de##div[class^="rtlde-medium-rectangle"]
```

**Comment by danidoedel** [comment]
@Alex-302 Nope not working here... :(

Any chance to block the social widgets I mentioned too?

**Comment by Alex-302** [comment]
It is working.

> Any chance to block the social widgets I mentioned too?

I don't see them

**Comment by danidoedel** [comment]
No it's not, but it will be hard to change that if you don't see it... so never mind...
