### ISSUE TITLE
IObit Uninstaller 6.2 app - advert

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4164]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: The app contains an ad

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22202825/9bfbee6a-e172-11e6-800c-4d2889c084ba.png)

</details>

Will check it at our end on Windows later.

***System configuration***

Information | value
--- | ---
Operating system: | Microsoft Windows NT 6.1.7601 Service Pack 1
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Stealth mode options(Windows) | enabled, default
Adguard filters: | 1 2 3 4 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1150428

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Вряд ли можно убрать. Не вижу, чтоб программа в сеть ломилась.
