### ISSUE TITLE
vox.de - Ad leftover - Social widget - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4165]
***Site***: http://www.vox.de/cms/index.html
***Description***: 
- Ad leftovers
- Social widgets
- Annoyance (video blocked)

<details>
<summary>Screenshot</summary>

http://www.vox.de/cms/index.html:

![image](https://cloud.githubusercontent.com/assets/10995998/22202982/f65a4300-e16a-11e6-9188-aab6c3c07e81.png)

http://www.vox.de/sendungen/hot-oder-schrott-die-allestester-2539062.html:

![image](https://cloud.githubusercontent.com/assets/10995998/22202908/b03d3012-e16a-11e6-8bba-08038addd211.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22202924/c4b13a20-e16a-11e6-9796-b988420dca65.png)

http://www.vox.de/cms/das-perfekte-dinner-judith-im-kulinarischen-steckbrief-4070951.html:

![image](https://cloud.githubusercontent.com/assets/10995998/22202945/e251b604-e16a-11e6-947a-8387e4da792d.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22203013/1a641e38-e16b-11e6-8073-5ec9a7987953.png)

Same for the video as in #4163. Video can't be played in private browsing mode.

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
.English filter | 1.1.7.1
Spyware filter | 1.0.10.34
Social media filter | 1.0.16.66
Annoyances filter | 1.0.9.22
German filter | 1.0.30.58
Mobile ads filter | 1.0.6.76
Safari filter | 1.0.2.18

**Comment by seanl-adg** [comment]
Video ads are not playing even without incognito mode, is it the same as your end?

**Comment by danidoedel** [comment]
Not sure what exactly you meant, but yes I don't see any video ads, neither in normal mode nor incognito mode. Just that message the video can't be played in incognito mode.
