### ISSUE TITLE
n-tv.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4167]
***Site***: http://www.n-tv.de/
***Description***: Ad leftover at the top and in right sidebar.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22203353/f30fccae-e16c-11e6-86d0-99fa27cf52c8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
.English filter | 1.1.7.1
Spyware filter | 1.0.10.34
Social media filter | 1.0.16.66
Annoyances filter | 1.0.9.22
German filter | 1.0.30.58
Mobile ads filter | 1.0.6.76
Safari filter | 1.0.2.18

**Comment by seanl-adg** [comment]
Please check:
```
n-tv.de#$#.wrapper-page { margin-top:0px!important; }
```
or should we leave some small margin at the top?

**Comment by danidoedel** [comment]
That's perfect. I would take that rule.

**Comment by danidoedel** [comment]
@seanl-adg There is something else strange with that site. Without Adguard the "wrapper-main" looks like this (correct width and the page therefore is centered):

![image](https://cloud.githubusercontent.com/assets/10995998/22208335/d0f972da-e182-11e6-83d7-a70cd84fc66e.png)

With Adguard it looks like this ("wrapper-main" has a different width and the page therefore is not centered):

![image](https://cloud.githubusercontent.com/assets/10995998/22208412/18d0395e-e183-11e6-8c55-d640a54ba4d0.png)

Hope this can be fixed too.

**Comment by seanl-adg** [comment]
Not reproduced.
