### ISSUE TITLE
chip.de - Annoyance - Social widget - Ads - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4168]
***Site***: http://www.chip.de/ (See links above the pictures for the respective page.)
***Description***:

- Lot of annoyance
- Social widget
- Ad leftover
- Ads

<details>
<summary>Screenshot</summary>

http://praxistipps.chip.de/dns-server-in-der-fritzbox-aendern-so-gehts_33877:

Vouchers at the top left.
Social widgets at the left.
Ad leftover in the middle.
Newsletter banner at the middle/right.
Vertical flyin at the bottom right will appear when you sroll down a bit.

![image](https://cloud.githubusercontent.com/assets/10995998/22209115/9ba5ab32-e185-11e6-820f-b59463f7758d.png)

Social widgets at the left.
Ad leftover at the right.
Ad in middle.

![image](https://cloud.githubusercontent.com/assets/10995998/22209190/e0526b58-e185-11e6-92ed-4ac98cff5eb0.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22209330/6c51cca2-e186-11e6-9d49-3c8aed64287f.png)

On mobile devices:

![image](https://cloud.githubusercontent.com/assets/10995998/22210307/aa4ed876-e189-11e6-8ee2-2d9e5b424666.png)

_________________________________________
_______________________________

http://www.chip.de/Downloads-Download-Charts_32427498.html:

![image](https://cloud.githubusercontent.com/assets/10995998/22209751/f0a665a2-e187-11e6-88f8-8aeb990714ea.png)

________________________________________
_______________________________

http://www.chip.de/downloads/CCleaner_16317939.html:

![image](https://cloud.githubusercontent.com/assets/10995998/22209865/280366da-e188-11e6-8643-317d7b33411c.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22209911/62babf26-e188-11e6-9791-d8cbb200e28d.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22209953/7647d0ec-e188-11e6-8591-cf850fd30a50.png)

_______________________________
_______________________________

http://www.chip.de/download/38910_Brennen-DVD/:

![image](https://cloud.githubusercontent.com/assets/10995998/22210047/c8a218b6-e188-11e6-9cea-75fb01f99fd1.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22210084/f0bf60ec-e188-11e6-87e0-86da59dea6dc.png)

_______________________________
_______________________________

http://forum.chip.de/handy-kaufberatung/gutes-dual-sim-handy-android-gesucht-1867611.html:

![image](https://cloud.githubusercontent.com/assets/10995998/22210119/0cd5988c-e189-11e6-855b-6bacd5c8fa87.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
.English filter | 1.1.7.3
Spyware filter | 1.0.10.35
Social media filter | 1.0.16.68
Annoyances filter | 1.0.9.23
German filter | 1.0.30.60
Mobile ads filter | 1.0.6.78
Safari filter | 1.0.2.19

**Comment by danidoedel** [comment]
Not everything is fixed yet...

**Comment by Alex-302** [comment]
Looks clean for me.
