### ISSUE TITLE
computerbild.de - Ads - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4169]
***Site***: http://www.computerbild.de/artikel/cb-Ratgeber-Kurse-Software-Die-55-wichtigsten-Programme-1964953.html
***Description***: Newsletter banners and ad in sidebar.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22210877/829662c0-e18b-11e6-9604-223380b1c4e1.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22210859/7bf6cf7c-e18b-11e6-8822-ba0a1d4ec767.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
.English filter | 1.1.7.3
Spyware filter | 1.0.10.35
Social media filter | 1.0.16.68
Annoyances filter | 1.0.9.23
German filter | 1.0.30.60
Mobile ads filter | 1.0.6.78
Safari filter | 1.0.2.19

**Comment by Alex-302** [comment]
added
```
computerbild.de###teaser_right > section.teaserblock.labeling
computerbild.de##.newsletterteaser
```
