### ISSUE TITLE
adf.ly - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4170]
***Site***: http://adf.ly/
***Description***: Adblock detection when you try to download a file (e.g. http://rd1.gamecopyworld.click/JKPv). You have to wait until the time counts down to 1 Second and then the message appears and stops the countdown.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22213813/d1f6a8e8-e195-11e6-8094-9a44110d65f1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
.English filter | 1.1.7.3
Spyware filter | 1.0.10.35
Social media filter | 1.0.16.68
Annoyances filter | 1.0.9.23
German filter | 1.0.30.60
Mobile ads filter | 1.0.6.78
Safari filter | 1.0.2.19

**Comment by Alex-302** [comment]
check:
```
@@||s1-adfly.com/show.php?$domain=gamecopyworld.click
@@/ad_top$domain=gamecopyworld.click,image
@@||gamecopyworld.click^$generichide
```

**Comment by danidoedel** [comment]
@Alex-302 Yeah there is no adblock detection with these rules. But the wohl page below the header (marked red in screenshot) is a random ad page. Not sure if that can be blocked without adblock detection?

![image](https://cloud.githubusercontent.com/assets/10995998/22275145/ec1bb4c8-e2aa-11e6-9d85-773a0bad4a19.png)

**Comment by Alex-302** [comment]
Strange. Ads are blocked with
```
@@||s1-adfly.com/show.php?$domain=gamecopyworld.click
@@/ad_top$domain=gamecopyworld.click,image
```

**Comment by danidoedel** [comment]
Yeah works now. Not sure what went wrong yesterday...
