### ISSUE TITLE
egeurok.ru - missed ad 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4171]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://egeurok.ru/GDZ_matem/10_11kl_Mordkovich/6/49.4.html - missed ad on page

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/22214451/4aada598-e1a0-11e6-80b9-b41646932537.png)

</details>

***System configuration***

Application version: 1.1.4.60

Device: iPhone
OS: 10.2

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.6.42 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.30 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.53 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.45.65 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.17 Enabled=YES

Ticket ID: 1491615

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
чисто
