### ISSUE TITLE
www.meddaily.ru - missed ad 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4172]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://www.meddaily.ru/all - missed ad on page

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/22215285/74a2b05c-e1a3-11e6-938f-2a2a89979af1.png)

</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

***System configuration***
Application version: 1.1.4.60
Device: iPhone
OS: 10.2

Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.6.90 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.32 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.63 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.45.79 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.76 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.17 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.73.32 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=225 Name="Fanboy Anti-Facebook List" Version=1.0.0.7 Enabled=YES
ID=229 Name="I dont care about cookies" Version=1.0.0.11 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.73.20 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.69.75 Enabled=NO
ID=205 Name="Schacks Adblock Plus liste" Version=1.0.1.78 Enabled=NO
ID=210 Name="Spam404" Version=1.0.1.68 Enabled=YES

Ticket ID: 1492707

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
