### ISSUE TITLE
rgmechanics.com - Annoyance - Social widget - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4175]
***Site***: http://www.rgmechanics.com/
***Description***: Overlay when accessing this site. Social widget leftover at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22221620/1aacc3f6-e1b4-11e6-9e1c-f83ba7584183.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22221723/770a0f46-e1b4-11e6-9e18-547daa18de56.png)

Ad leftover, social widget leftover and ads (http://www.rgmechanics.com/first-impact-rise-of-a-hero-free-download/):

![image](https://cloud.githubusercontent.com/assets/10995998/22221758/9b07c834-e1b4-11e6-8e93-f6b9f362138c.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22221816/c7366be0-e1b4-11e6-91ab-e57db97726f0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
.English filter | 1.1.7.7
Spyware filter | 1.0.10.37
Social media filter | 1.0.16.69
Annoyances filter | 1.0.9.24
German filter | 1.0.30.62
Mobile ads filter | 1.0.6.79
Safari filter | 1.0.2.19

**Comment by Alex-302** [comment]
fixed
