### ISSUE TITLE
https://fas.st links getting blocked on iOS and Android

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#41787]
https://fas.st/J_Yvvv

<details> <summary> screenshots </summary>

![image](https://user-images.githubusercontent.com/15856304/66252501-187bf200-e765-11e9-9aba-46c27fb77622.png)

![image](https://user-images.githubusercontent.com/15856304/66252505-27fb3b00-e765-11e9-98a8-7870ff0b5239.png)

</details>

<details> <summary> filters </summary>

![image](https://user-images.githubusercontent.com/15856304/66252543-ba9bda00-e765-11e9-840e-9eb4900ab684.png)

</details>

**Comment by krystian3w** [comment]
`@@||ad.admitad.com^`

?

**Comment by krystian3w** [comment]
### Problematic:

> https://github.com/AdguardTeam/AdguardFilters/blob/ec618244b2e132ce2f0837824b3982a315c26d4c/MobileFilter/sections/adservers.txt#L415 

### Fast fix (whitelist subdomain):

`@@||ad.admitad.com^`


### Less generic solution:

```
@@||ad.admitad.com/g/*/*&ulp=$domain=ad.admitad.com
```

or

```
@@||ad.admitad.com/*/?i=*&ulp=$domain=ad.admitad.com
```

---

Old maybe too specific:

> https://github.com/AdguardTeam/AdguardFilters/blob/edf439d0068c43820435a3362332c499998c7d87/SafariFilter/sections/whitelist.txt#L208-L209 https://github.com/AdguardTeam/AdguardFilters/blob/3cb9c66896d1d28253ae780d8cb164659cb57731/MobileFilter/sections/whitelist.txt#L291-L292 https://github.com/AdguardTeam/AdguardFilters/blob/55bb12c1075f5107aa098570503d18fff3fcd598/RussianFilter/sections/antiadblock.txt#L690-L692 https://github.com/AdguardTeam/AdguardFilters/blob/67bf7e4f003c9292613875340af1f10020ae055e/EnglishFilter/sections/content_blocker.txt#L1663-L1664 https://github.com/AdguardTeam/AdguardFilters/blob/c32892274c0760eb8c191fde72f9bb3d868937f7/EnglishFilter/sections/whitelist.txt#L2762-L2763

**Comment by Alex-302** [comment]
@Eugene-Savenko куда жать-то надо?

**Comment by krystian3w** [comment]
1. `fas.st/J_Yvvv` ↪️ 

2. `https://ad.admitad.com/g/6de2a29e2b952fc518f6c188ef9305/?i=10&ulp=https://www.yves-rocher.ru/podarki/vasi-3-gela-dla-dusa-i-vanny-za-499-rublej/p/yr.rukz.O3200` ↪️ 

3. `www.yves-rocher.ru/podarki/vasi-3-gela-dla-dusa-i-vanny-za-499-rublej/p/yr.rukz.O3200`

IMO need fix, if AdGuard add support this: https://github.com/AdguardTeam/CoreLibs/issues/152 / https://github.com/AdguardTeam/CoreLibs/issues/1154

**Comment by Eugene-Savenko** [comment]
@Alex-302 пришли себе ссылку из описания в телеграм и перейди )

**Comment by Alex-302** [comment]
@Eugene-Savenko надо будет проверить через пару часов.

**Comment by Alex-302** [comment]
Ещё через пару часов) Чуть иначе нужно исключать.

**Comment by Eugene-Savenko** [comment]
Теперь работает.

**Comment by Alex-302** [comment]
Наконец)
