### ISSUE TITLE
pinterest.com - Annoyance - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4178]
***Site***: https://de.pinterest.com/
***Description***: 

- Mobile app banner at the top. 
- Facebook login button blocked.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22244190/d983a346-e22a-11e6-8af4-266d26af90c2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
.English filter | 1.1.7.12
Spyware filter | 1.0.10.38
Social media filter | 1.0.16.72
Annoyances filter | 1.0.9.24
German filter | 1.0.30.67
Mobile ads filter | 1.0.6.79
Safari filter | 1.0.2.19

**Comment by seanl-adg** [comment]
Fixed a mobile app banner. @Alex-302 FB login button is being blocked by `||facebook.com/*/plugins/$domain=~facebook.com` Could you fix it? I don't know what this rule is originally intended to block.

**Comment by Alex-302** [comment]
@seanl-adg 
> ||facebook.com/*/plugins/$domain=~facebook.com

this rule blocks social widgets.
Try
```
@@||facebook.com/*/plugins/login_button.
```
This button is not working on my side without AG, window is closed immediately

**Comment by danidoedel** [comment]
Button works fine without adguard here. A new window with facebook will open.

**Comment by Alex-302** [comment]
Ok, added
