### ISSUE TITLE
aklamio.com - Annoyance - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4179]
***Site***: https://www.aklamio.com/de
***Description***: 
- Cookie notice at the bottom.
- Facebook login button blocked on mobile devices.

<details>
<summary>Screenshot</summary>

https://www.aklamio.com/de:

![image](https://cloud.githubusercontent.com/assets/10995998/22244902/ab6b300c-e22d-11e6-9791-e53812f35bb1.png)

https://www.aklamio.com/de/anmelden (Facebook button missing):

![image](https://cloud.githubusercontent.com/assets/10995998/22245008/1f072606-e22e-11e6-90b2-b9012c84f6e9.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
.English filter | 1.1.7.12
Spyware filter | 1.0.10.38
Social media filter | 1.0.16.72
Annoyances filter | 1.0.9.24
German filter | 1.0.30.67
Mobile ads filter | 1.0.6.79
Safari filter | 1.0.2.19

**Comment by Alex-302** [comment]
added
```
aklamio.com##.alert.cookie
aklamio.com#@#.icon-facebook 
```
