### ISSUE TITLE
shpock.com - Annoyance - Social widget - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4180]
***Site***: https://www.shpock.com/
***Description***: Annoyance and social widget leftover link to App Store doesn't work on iOS.

<details>
<summary>Screenshot</summary>

**Annoyance in sidebar:**

![image](https://cloud.githubusercontent.com/assets/10995998/22245402/f9d4a366-e22f-11e6-9c5f-ce48e220e32e.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22245428/1d7c447c-e230-11e6-9d88-8381c4b3bbeb.png)

**Overlay when accessing this site on mobile device:**

![image](https://cloud.githubusercontent.com/assets/10995998/22245079/754bc274-e22e-11e6-8716-b5b3df606851.png)

**App banner at the top:**

![image](https://cloud.githubusercontent.com/assets/10995998/22245119/a66ec7fc-e22e-11e6-9536-a5b415155b23.png)

**After closing first banner and reloading the page another app banner shows up:**

![image](https://cloud.githubusercontent.com/assets/10995998/22245135/bab40ee8-e22e-11e6-9a0f-5112b735f0a6.png)

**Another app banner at the top and social widget leftover below article (https://www.shpock.com/i/WHJKFO5bnlVNi0V5/):**

![image](https://cloud.githubusercontent.com/assets/10995998/22245338/b90e7b4a-e22f-11e6-87a6-4e1f5c383556.png)

**Link to App Store doesn't work on iOS:**

![image](https://cloud.githubusercontent.com/assets/10995998/22245561/d061c5a8-e230-11e6-8348-2c999735cd71.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22245542/bb457b1a-e230-11e6-80bb-30e4ffe27356.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
.English filter | 1.1.7.12
Spyware filter | 1.0.10.38
Social media filter | 1.0.16.72
Annoyances filter | 1.0.9.24
German filter | 1.0.30.67
Mobile ads filter | 1.0.6.79
Safari filter | 1.0.2.19

**Comment by seanl-adg** [comment]
The broken link issue wasn't reproduced on desktop, we should test it with iOS device.

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||go.onelink.me/*?pid=
```
