### ISSUE TITLE
http://m.pikabu.ru/new - yandex direct

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4181]
http://m.pikabu.ru/new - ads 

![image1](https://cloud.githubusercontent.com/assets/15856304/22246936/00546d10-e240-11e6-8be4-52fa521f61bb.png)

<details>

Application version: 1.1.4.60
Optimized - no.
DNS - none

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.6.49 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.30 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.60 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.9.16 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.97 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.45.72 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.73 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.17 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.69.93 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.69.72 Enabled=YES

**Comment by Alex-302** [comment]
На айпаде чисто.

**Comment by vozersky** [comment]
tested with
