### ISSUE TITLE
Tapatalk app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4184]
[com.quoord.tapatalkpro.activity](https://play.google.com/store/apps/details?id=com.quoord.tapatalkpro.activity&hl=en) app shows ads:

<details>

![screenshot_20170122-085928](https://cloud.githubusercontent.com/assets/15856304/22247801/406a2e40-e244-11e6-872f-99b2e30f0116.png)

</details>

Android 7.1.1
Adguard 2.8.76
HQ filtering method
HTTPs filtering is on, whitelist mode
DNS is off
Filters: 2, 3, 4, 14, 5, 11 
Log here, Jan 22: 1471434

**Comment by Alex-302** [comment]
Can't reproduce on my device. Third-party ad requests are blocked.
I need HAR file with screenshot of actual ad.

**Comment by evgeniy-ADG** [comment]
[adguard.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/737428/adguard.har.zip)

**Comment by Alex-302** [comment]
Try this rule with quality mode
```
||apis.tapatalk.com/api/user/info/$replace=/"ads":/"bbb":/
```

**Comment by Fla73** [comment]
Hey Alex,

it WORKS!!!! 

You can close the ticket!!!!!

Thank you,

Flavio

**Comment by Alex-302** [comment]
ok, added to mobile filter

**Comment by deLumren** [comment]
The issue is back now. Latest Mobile filter.

Reported by User 1546891

**Comment by Alex-302** [comment]
@deLumren original issue is about Android. `$replace` rules are not supported by iOS. It is not our fault.
