### ISSUE TITLE
The Atlantic sometimes shows a splash placeholder for blocked banner

### ISSUE THREAD

**Issue by hmage** [AdguardTeam/AdguardFilters#4187]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
* **Current behaviour**: 

https://www.theatlantic.com/politics/archive/2017/01/in-seconds-at-the-cia-trump-made-america-less-safe/514193/ -- with annoyances filter on, on first visit shows a splash with blocked ad image.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

![pasted_image_at_2017_01_24_19_09](https://cloud.githubusercontent.com/assets/739119/22257041/b93a908e-e26d-11e6-8435-431243d0e122.png)

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>
![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

The splash for ad should not show up. 

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

1. Allow only adguard in Chrome Incognito mode.
2. Open new incognito window.
3. Open https://www.theatlantic.com/politics/archive/2017/01/in-seconds-at-the-cia-trump-made-america-less-safe/514193/
4. 50/50 chance to see the splash placeholder.
5. If it does not show up, try again by closing incognito window and opening it again.
6. Splash is unlikely to show up again in same browser session. You need to close incognito window and open new one.

The decision to show the splash ad seems to be done on server side and they do not always decide to show it.

***System configuration***

Information | value
--- | ---
Operating system: | Linux
Browser: | Chrome 55.0.2883.87 (64-bit)
Adguard version: | 2.5.11
Adguard DNS: | None
Adguard filters: | English, Annoyances.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
I hope it is fixed this time :)
