### ISSUE TITLE
samsung tv ads 

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdguardFilters#41881]
Can you please add those domains to your main filterlist of AdGuardHome 

||config.samsungads.com^
||ads.samsungads.com^
||samsungtvads.com^
||samsungads.com^

They are responsible for advertising on samsung smart tv's i have blocked those domains for a half year and didn't see any negative effects.
Any TV function works fine, just the ads are removed.

I would appreciate it, if you add it in further filter updates.

Thank you

Edit: I just discover that "||samsungads.com^" is already in your list, but ads are still present on my TV, if I don't add the other under "Custom filtering rules".

**Comment by Alex-302** [comment]
Hi. Do you use AdGuard Home or AdGuard DNS on TV?

**Comment by uservictor** [comment]
I am using Adguard Home installed on my raspberrypi 
Here is the link: https://github.com/AdguardTeam/AdGuardHome/wiki/Raspberry-Pi

With this list: (it is the default list)
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

**Comment by Alex-302** [comment]
> ||example.com^ blocks also subdomains such "config." and "ads." am I right?

yes. `||samsungads.com^` is enough. You can check in with any site with subdomains using AG Home)
