### ISSUE TITLE
translate.ru & systemexplorer.net

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#4188]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: message about cookies
translate.ru 
http://systemexplorer.net/ru/file-database/file/shellexperiencehost-exe

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/22282282/1afc1114-e2e4-11e6-92ab-4fc8f963db07.png)

![image](https://cloud.githubusercontent.com/assets/18548949/22282338/62933de0-e2e4-11e6-9a7d-a3fcb0690e0a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | IE 11
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | enable
Adguard filters: | 1,2,3,4,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1419169

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
