### ISSUE TITLE
http://37.59.136.222/

### ISSUE THREAD

**Issue by tamibi** [AdguardTeam/AdguardFilters#41899]
ads and notification still show at this web http://37.59.136.222/
ABPIndo have been enabled

![image](https://user-images.githubusercontent.com/54970502/66296598-c4772780-e8a2-11e9-9b14-193f09fc09a2.png)

**Comment by krystian3w** [comment]
`###wraps > #floatcenter`

or you waiting for newtwork block pop-up / scriplet injection?

**Comment by Alex-302** [comment]
This site has no or too few visitors.
For custom filter:
```
37.59.136.222##div[class="overlay bm"]
37.59.136.222###floatcenter
37.59.136.222##.ads
```
