### ISSUE TITLE
http://158.69.54.218/

### ISSUE THREAD

**Issue by tamibi** [AdguardTeam/AdguardFilters#41902]
ads and notification still show at this web http://158.69.54.218/
ABPIndo have been enabled
![image](https://user-images.githubusercontent.com/54970502/66297797-39e3f780-e8a5-11e9-922e-9651177db7b9.png)

**Comment by zloyden** [comment]
The site has low visitors. Please add these rules in User's Filter:
`158.69.54.218#$#.modal { display: none!important; }`
`158.69.54.218#$#body { overflow: visible!important; }`
`158.69.54.218##div[class^="ns-"]`
`158.69.54.218##.navbar-brand`
`158.69.54.218##.ban_empat`
`158.69.54.218#?##main > div#content > div:has(> a[rel="nofollow"][target="_blank"] > img)`
`158.69.54.218#%#AG_onLoad(function() { setTimeout(function() { var el = document.querySelector('.btn-success'); if(el) el.click(); }, 300); });`.
