### ISSUE TITLE
ads on http://auto62rus.ru

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4191]
* **ads on http://auto62rus.ru**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (![image_uploaded_from_ios_720](https://cloud.githubusercontent.com/assets/23701680/22288137/37c45698-e2fe-11e6-879a-bc71a2fbea52.jpg))

<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.4
Simplified filters(iOS) |  Off
Adguard filters: | ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
 ID=2 Name="English filter" Version=1.1.7.7 Enabled=YES
 ID=3 Name="Spyware filter" Version=1.0.10.37 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.69 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.9.24 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.45.88 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.79 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.19 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.33 Enabled=NO
ID=118 Name="EasyPrivacy" Version=1.0.73.27 Enabled=NO
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.63.33 Enabled=NO
ID=122 Name="Fanboy's Annoyances" Version=1.0.67.28 Enabled=NO
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.48 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.73.41 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.65 Enabled=NO
ID=229 Name="I dont care about cookies" Version=1.0.0.11 Enabled=NO
ID=208 Name="Malware Domains" Version=1.0.66.58 Enabled=NO
ID=213 Name="RU AdList: BitBlock" Version=1.0.70.16 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.69.95 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.68 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)

Ticket ID(if exists): 1493526

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
auto62rus.ru#%#window.aadnet = {};
```
