### ISSUE TITLE
[Android] ivi app incorrect blocking

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#4192]
The app [ivi](https://play.google.com/store/apps/details?id=ru.ivi.client&hl=ru) works fine when you try to watch videos with ads. When you watch videos already free of ads, the error pops up:

![image](https://cloud.githubusercontent.com/assets/8577533/22291353/f05adf84-e316-11e6-9a09-89e711601518.png)
![image](https://cloud.githubusercontent.com/assets/8577533/22291357/f6966328-e316-11e6-91e3-cdb924b63690.png)

Disabling Adguard solves the problem.

Original thread:
https://forum.adguard.com/index.php?threads/12159/#post-123664

**Comment by Alex-302** [comment]
У меня не повторяется.
Нужно найти фильтр, который ломает(скорее всего русский или мобильный), и с ним снять http лог(и HAR не помешает)

**Comment by Alex-302** [comment]
Поправил в мобильном фильтре.

**Comment by vbagirov** [comment]
Fixed.
