### ISSUE TITLE
onlinemarketingrockstars.de - Annoyance - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4194]
***Site***: http://www.onlinemarketingrockstars.de/
***Description***: See screenshots for more information.

<details>
<summary>Screenshot</summary>

**Overlay when accessing this site:**

![image](https://cloud.githubusercontent.com/assets/10995998/22295452/42cde644-e317-11e6-9ca4-84bfda15990b.png)

**Newsletter box in the sidebar and banner at the bottom:**

![image](https://cloud.githubusercontent.com/assets/10995998/22295444/3783d122-e317-11e6-98b2-f0d71ed3fd27.png)

**Whatsapp newsletter box in the sidebar, job ad widget:**

![image](https://cloud.githubusercontent.com/assets/10995998/22295816/8c0fb354-e318-11e6-90ca-465a7ce41eb9.png)

**Social bar at the top of articles (http://www.onlinemarketingrockstars.de/ghost-restaurants-green-summit-group/):**

![image](https://cloud.githubusercontent.com/assets/10995998/22295573/aa880af8-e317-11e6-8b38-ef0c63832297.png)

**Social bar at the bottom of articles, newsletter box, job ad widget:**

![image](https://cloud.githubusercontent.com/assets/10995998/22295611/d899988a-e317-11e6-8e2d-69636b055bc3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
.English filter | 1.1.7.25
Spyware filter | 1.0.10.40
Social media filter | 1.0.16.77
Annoyances filter | 1.0.9.29
German filter | 1.0.30.72
Mobile ads filter | 1.0.6.82
Safari filter | 1.0.2.21

**Comment by Alex-302** [comment]
added
```
||onlinemarketingrockstars.de/wp-content/plugins/convertplug/modules/modal/assets/css/modal.min.css
##.socialshare
onlinemarketingrockstars.de##.cp-info-bar-wrapper
```

**Comment by danidoedel** [comment]
@Alex-302 Newsletter stuff and job ads still there...

**Comment by Alex-302** [comment]
Screenshot, please.

**Comment by danidoedel** [comment]
@Alex-302 

![image](https://cloud.githubusercontent.com/assets/10995998/23064741/1801a48e-f512-11e6-8c4e-59f14a67ef87.png)

![image](https://cloud.githubusercontent.com/assets/10995998/23064748/2366c372-f512-11e6-98ba-a7e6edee62b1.png)

http://www.onlinemarketingrockstars.de/ghost-restaurants-green-summit-group/:

![image](https://cloud.githubusercontent.com/assets/10995998/23064768/40c65d10-f512-11e6-9d95-ef95cc3228ae.png)

![image](https://cloud.githubusercontent.com/assets/10995998/23064781/4dc30c5c-f512-11e6-8328-36926f95f3b8.png)

**Comment by Alex-302** [comment]
fixed
