### ISSUE TITLE
wn.de - Ad leftover - Annoyance - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4195]
***Site***: http://www.wn.de/
***Description***: Annoyance, ad leftover and social widget leftover.

<details>
<summary>Screenshot</summary>

**Ad leftover at the top:**

![image](https://cloud.githubusercontent.com/assets/10995998/22295984/1fd56070-e319-11e6-8026-e831518128bb.png)

**Whatsapp newsletter box in sidebar:**

![image](https://cloud.githubusercontent.com/assets/10995998/22296018/3f9684b6-e319-11e6-8eb9-7549e194c999.png)

**Ad leftover in sidebar:**

![image](https://cloud.githubusercontent.com/assets/10995998/22296089/88053d64-e319-11e6-9ae9-c6e35c0afbcd.png)

**Another ad leftover in sidebar:**

![image](https://cloud.githubusercontent.com/assets/10995998/22296202/b3f0ca42-e319-11e6-82b8-dfa395dcde57.png)

**Overlay when viewing an article (http://www.wn.de/Muensterland/Kreis-Steinfurt/Greven/2674358-Tim-Edler-setzt-auf-Crowdfunding-Mit-Fan-Hilfe-zum-ersten-Album):**

![image](https://cloud.githubusercontent.com/assets/10995998/22296234/cfd3ec58-e319-11e6-901c-46ca43b75106.png)

**Social widget leftover in the left sidebar:**

![image](https://cloud.githubusercontent.com/assets/10995998/22296325/15a7aaa8-e31a-11e6-84c1-9c911ba9e091.png)

**Same on mobile device:**

![image](https://cloud.githubusercontent.com/assets/10995998/22296493/96869aa8-e31a-11e6-8da9-c6d8644737ff.png)

**Annoyance banner below article (subscription ad):**

![image](https://cloud.githubusercontent.com/assets/10995998/22296355/2d8d2378-e31a-11e6-959f-7906d6298a43.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
.English filter | 1.1.7.25
Spyware filter | 1.0.10.40
Social media filter | 1.0.16.77
Annoyances filter | 1.0.9.29
German filter | 1.0.30.72
Mobile ads filter | 1.0.6.82
Safari filter | 1.0.2.21

**Comment by Alex-302** [comment]
Added only these rules:
```
wn.de##body > div#top-position
wn.de###paywall_container
wn.de##.socialmedia_article_linkbox
m.wn.de##.social_media_block
```
