### ISSUE TITLE
holodilnik.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#41978]
Куки-бар.

<details><summary>Screenshot:</summary>

![2019 10 08-1](https://user-images.githubusercontent.com/17948007/66391910-0b663980-e9d7-11e9-9387-d3bf558debdd.png)
</details>

[https://www.holodilnik.ru/action/bosch_skidka15/gas_cookers/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.holodilnik.ru/action/bosch_skidka15/gas_cookers/)

`holodilnik.ru##.alert.fixed-bottom`

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.2.1
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by XX-J** [comment]
Куки-бар по прежнему виден.

**Comment by Alex-302** [comment]
потому что не добавил)
