### ISSUE TITLE
http://www.eurogamer.net - placeholders

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4200]
http://www.eurogamer.net

Screenshots:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22306106/99f3c248-e346-11e6-99f7-0079d5052b25.png)

</details>

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.4.36
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | 2 3 4 12 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1233134

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
eurogamer.net###mobile-leaderboard
eurogamer.net##.mobile-mpu-wrapper

```
