### ISSUE TITLE
http://www.utopia-gemist.nl/ - 2 issues

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4201]
The link: http://www.utopia-gemist.nl/aflevering/utopia-uitzending-796-maandag-23-januari-2017/

1. The Standard DNS filtering doesn't let you watch the video

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22307742/e7da6c5e-e34c-11e6-96ca-a1f132e08287.png)

</details>

2. Missed ads in video:

<details>

![image2](https://cloud.githubusercontent.com/assets/15856304/22307750/ef903eba-e34c-11e6-9b86-2d7bb9e9e99c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.1.1
Browser: | Safari
Adguard version: | 1.1.4.60
Simplified filters(iOS) | Off
Adguard DNS: | None / Default
Adguard filters: | 2 3 4 8 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1493409

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@evgeniy-ADG does main video work on your side(on desktop without AG)?

**Comment by evgeniy-ADG** [comment]
Yes, it works with and without Adguard

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22460289/d1f9a99a-e7ac-11e6-9986-8e6c5093199b.png)

**Comment by Alex-302** [comment]
У меня ни в какую не работает, всё перепробовал.
В винде у тебя такая же проблема как и на иоси?

**Comment by evgeniy-ADG** [comment]
У меня на Винде есть и "крестик", и реклама

![image](https://cloud.githubusercontent.com/assets/15856304/22518228/88112430-e8b4-11e6-9a9f-e60047570109.png)

Но на винде я DNS не пользуюсь. 
На айпеде - не играет, пока не отключить DNS.

**Comment by Alex-302** [comment]
Имел в виду без Адгарда основное видео стартует?
