### ISSUE TITLE
m.focus.de - missed ad

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4202]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:http://m.focus.de/ - missed ad on page

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/22315136/98598810-e36d-11e6-84f3-751520fdff97.png)

</details>

***System configuration***

Application version: 1.1.4.36
Platform: iOS
OS: 10.2.1

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.7.5 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.36 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.68 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.9.24 Enabled=YES
ID=6 Name="German filter" Version=1.0.30.61 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.79 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.19 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.61.56 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.73.40 Enabled=YES

Ticket ID: 1493730

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
I can't reproduce.
