### ISSUE TITLE
ebesucher.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#4203]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
http://www.ebesucher.ru/surfbar/egor788
Don't count earnings for pages viewed.

**helps disabling Spyware filter**

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/22326876/3f282e22-e3bd-11e6-8306-950e3fc50bea.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/22326914/5ee15784-e3bd-11e6-9602-f125fd7e9c3e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | FF
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | enable
Adguard filters: | 1,2,3,4,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1043635

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I don't see how to fix it.
Try
```
@@||ganzoffen.de/js/fingerprint2.min.js$domain=ganzoffen.de
@@||speed*.ganzoffen.de^$urlblock
@@||ebesucher.ru^$document
```

**Comment by vgavrish** [comment]
nope, it doesn't work

**Comment by Alex-302** [comment]
Well, he can exclude blocked requests manually
`@@||what_blocked.com^$domain=where_blocked.com`
