### ISSUE TITLE
netzwelt.de - Anti-Adblock notfication

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#4204]
***Description***:
Anti-Adblock notification on the website:
https://www.netzwelt.de/honor-6x/testbericht.html

Screenshot:
<details>

![screen shot 2017-01-26 at 1 29 37 pm](https://cloud.githubusercontent.com/assets/17504743/22329840/14f87d48-e3bb-11e6-97f9-d8d0c6586ae2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 10.12
Adguard version: | 1.4.0
Adguard filters: | "User filter", "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Filter unblocking useful ads", "German filter", "EasyList", "EasyList Germany", "Icelandic ABP List", "Adblock Warning Removal List", "I dont care about cookies" (Reproduced with basic filters)

Ticket ID(if exists): 1478777

**Comment by Alex-302** [comment]
Added to German filter
```
@@||netzwelt.de^$generichide
```
