### ISSUE TITLE
openssource.biz - anti-adblocker

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4205]
http://openssource.biz/eksklyuziv-legendarnyj-orator-uluchshi-svoyu-podachu-za-7-dnej.html 
![2017-01-27 12 29 21](https://cloud.githubusercontent.com/assets/23637588/22366371/5bab3820-e48d-11e6-8aeb-88c0d43cc181.png)
chrome
adguard 1.4.0
en rus spyware socialmedia annoyances

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
openssource.biz#@#.reklama
```
и убрал рекламу.

**Comment by zebrum** [comment]
@Alex-302 а вот за рекламу отдельное спасибо.
