### ISSUE TITLE
www.hurriyet.com.tr Unvisible Social Media Buttons

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardFilters#4206]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Hi
There are unvisible social media buttons on www.hurriyet.com.tr
You can see when you open only news page, then select some words. After that they will visible. I added screenshot.
* **Current behaviour**: 
For exampe:
This news page: http://www.hurriyet.com.tr/o-hakim-yakalandi-40348268
This is screenshots:
1. http://prntscr.com/e0zqzj
2. http://prntscr.com/e0zr9k
3. http://prntscr.com/e0zrie

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot: http://prntscr.com/e0zqzj

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome, Mozilla,UC Browser
Adguard version: | 2.5.12
Adguard driver (Windows): | WFP 
Adguard mode (Android): |
Filtering quality (Android): | 
HTTPS filtering (Android): |  
Simplified filters(iOS) | 
Adguard DNS: | None 
Stealth mode options(Windows) | 
Adguard filters: | ENGLISH, SPYWARE, SOCIAL MEDIA, ANNOYANCES, TURKISH, ADBLOCK WARNING REMOVAL LIST

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Social filter
```
/selection-sharer.
```

**Comment by tagataho** [comment]
but not fix, i updated filters and clear history,cookies. then tried.

**Comment by Alex-302** [comment]
please wait one hour

**Comment by tagataho** [comment]
okay :) 

thanks for your time..
