### ISSUE TITLE
eurosportplayer.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4207]
***Site***: http://de.eurosportplayer.com/
***Description***: Cookie notice at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22370978/af4d4c78-e494-11e6-9234-d822df85aa0e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
.English filter | 1.1.7.45
Spyware filter | 1.0.10.45
Social media filter | 1.0.16.86
Annoyances filter | 1.0.9.37
German filter | 1.0.30.78
Mobile ads filter | 1.0.6.86
Safari filter | 1.0.2.23

**Comment by Alex-302** [comment]
fixed
