### ISSUE TITLE
ads on - https://spaces.ru/shared_zone/?Clt=1&from=main

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4209]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***ads on - https://spaces.ru/shared_zone/?Clt=1&from=main***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (http://prnt.sc/e14pt8)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<http://prnt.sc/e14pt8>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.4
Simplified filters(iOS) |  Off

Adguard filters: | ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.7.40 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.44 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.83 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.9.36 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.46.3 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.86 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.23 Enabled=YES
ID=101 Name="EasyList" Version=1.0.67.16 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.73.45 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.67.19 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.67.38 Enabled=YES
ID=120 Name="Norsk adblockliste" Version=1.0.0.1 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.73.58 Enabled=YES
ID=116 Name="Wiltteri" Version=1.0.1.70 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.81 Enabled=YES
ID=234 Name="ROLIST2" Version=1.0.0.1 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.73.59 Enabled=YES
ID=214 Name="ABPVN List" Version=1.0.2.86 Enabled=YES
ID=222 Name="Adblock-Persian list" Version=1.0.0.23 Enabled=YES
ID=225 Name="Fanboy Anti-Facebook List" Version=1.0.0.7 Enabled=YES
ID=203 Name="hufilter" Version=1.0.0.58 Enabled=YES
ID=229 Name="I dont care about cookies" Version=1.0.0.11 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.70.34 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.70.13 Enabled=YES
ID=205 Name="Schacks Adblock Plus liste" Version=1.0.1.78 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.68 Enabled=YES
ID=232 Name="KAD - Przekrety" Version=1.0.0.97 Enabled=YES
ID=233 Name="Juvander's Adblock List for Finland" Version=1.0.0.4 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1477963

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
скрин странный, будто с превьюхи сделан, не видно ничего

**Comment by Alex-302** [comment]
ну и с таким количеством фильтров на iOS расчитывать на нормальную фильтрацию не стоит, т.к. лимит в 50 тысяч(введённый яблоком) правил никто не отменял

**Comment by vmalyuta** [comment]
У меня повторилось
![image_uploaded_from_ios_720](https://cloud.githubusercontent.com/assets/23701680/22383760/cac2cb60-e4d3-11e6-8eae-2a542d8a2587.jpg)

**Comment by Alex-302** [comment]
иос предоставляет крайне скудные возможности для блокировки. Попробую, конечно, убрать, но не факт что выйдет. А в ведре чисто?

**Comment by vmalyuta** [comment]
повторилось

**Comment by Alex-302** [comment]
странно. У меня везде чисто, и на ios

**Comment by evgeniy-ADG** [comment]
![screenshot_2017-03-24-16-43-11](https://cloud.githubusercontent.com/assets/15856304/24320847/a7fd248c-1146-11e7-966a-cc33c4b5cc06.png)

Вот еще, но это Андроид. Лог тут: 1149407

**Comment by Alex-302** [comment]
Подправил. После обновления нужно проверить.

**Comment by vmalyuta** [comment]
http://prnt.sc/f3tzaa
id 1477963

**Comment by Alex-302** [comment]
Они используют сертификат StartCom. Я здесь не помогу.
https://github.com/AdguardTeam/AdguardForWindows/issues/1359
