### ISSUE TITLE
Blank Box - Mangastream on Mobile

### ISSUE THREAD

**Issue by inazarab** [AdguardTeam/AdguardFilters#4210]
Using Adguard running, on iOS, using Safari, Mangastream.com has a blank box underneath the menu on the mobile site. On the desktop it works fine, it's only the mobile site.
![img_0078](https://cloud.githubusercontent.com/assets/25354384/22384418/3de81fa6-e49c-11e6-825c-71a2e87956f3.jpg)
![img_0078](https://cloud.githubusercontent.com/assets/25354384/22384417/3de7dc30-e49c-11e6-95a9-df8f97cbc3be.PNG)

**Comment by Alex-302** [comment]
it is removed on my iPad.
Which filters?

**Comment by inazarab** [comment]
I'm using Adguard Pro with the English filter, Spyware filter, Annoyances filter, Simplified domain names filter, Safari filter, Adblock warning removal list, anti-block killer reek, and Peter lowe's list. Sincerely,Alex Barazani 


    On Sunday, January 29, 2017 7:30 AM, Alex <notifications@github.com> wrote:
 

 it is removed on my iPad.
Which filters?—

**Comment by Alex-302** [comment]
For test - try to disable
Simplified domain names filter, Adblock warning removal list, anti-block killer reek, and Peter lowe's list
`Simplified domain names filter` it is unnecessary, when you are using Adguard Pro(I don't recommend to enable it)

**Comment by inazarab** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } It's still there after disabling all of those filters


Sincerely, Alex Barazani

On Monday, January 30, 2017, 7:05 AM, Alex <notifications@github.com> wrote:


For test - try to disable
Simplified domain names filter, Adblock warning removal list, anti-block killer reek, and Peter lowe's list
Simplified domain names filter it is unnecessary, when you are using Adguard Pro(I don't recommend to enable it)

**Comment by Alex-302** [comment]
that's because mobile filter is not enabled.

**Comment by inazarab** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Oh ok thanks. It's working now. What is the simplified domains filter for? 


Sincerely, Alex Barazani

On Tuesday, January 31, 2017, 7:19 AM, Alex <notifications@github.com> wrote:


that's because mobile filter is not enabled.

**Comment by Alex-302** [comment]
for slow devices(for example old Android)
