### ISSUE TITLE
 Gboard keyboard search doesn't work

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4211]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

Adguard DNS blocks Gboard search (requests time out)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image1](https://cloud.githubusercontent.com/assets/15856304/22394862/b014c492-e534-11e6-866b-2e6dfbeabc8a.PNG)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

1. Install the app
2. Set it up in Settings
3. Start typing and hit the Google button to start searching
4. It doesn't work

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2
Adguard version: | 1.1.4.36
Simplified filters(iOS) |  Off
Adguard DNS: | Please see logs here: 1494303
Adguard filters: | 2 3 4 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1494303

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
Works at my end

**Comment by Alex-302** [comment]
also not reproduced.
Ask for DNS log(filters should be disabled)

**Comment by evgeniy-ADG** [comment]
ok, waiting
