### ISSUE TITLE
http://miladynews.ru/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4212]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
The [link](http://miladynews.ru/nauka/10-nevoobrazimo-krutyx-faktov-ob-antarktide-kotorye-vy-mogli-ne-znat).

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22394947/5ca13f22-e537-11e6-9dad-eaf4a142a1b7.png)

</details>

***Steps to reproduce the problem***:

1. Go to the site
2. Scroll down a lot
3. You'll see the yellow banner with counter asking you to 'like' the page to unlock it 

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Browser: | Safari
Adguard version: | 1.1.4.36
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | 2 3 4 1 12 + annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1201796

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
