### ISSUE TITLE
http://putlockers.ch/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4213]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Unable to watch videos

SRT: Go [here ](http://putlockers.ch/watch-family-guy-tvshow-season-3-episode-1-online-free-putlocker.html)and try to watch smth, there will be no player 

Screenshots, 1 - how it is, 2 - how it should be

<details>

![file_000](https://cloud.githubusercontent.com/assets/15856304/22395136/30f98810-e53d-11e6-81e8-841c0bf4551e.png)

![file_001](https://cloud.githubusercontent.com/assets/15856304/22395137/3772e5c4-e53d-11e6-8116-389fa8c4d0a7.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10,2
Browser: | Safari
Adguard version: | 1.1.4.60
Simplified filters(iOS) | Off
Adguard DNS: |  Default
Adguard filters: | 2 3 4 11 12 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1453264

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
added to Safari filter 
```
@@||image*.putlockers.ch/
@@||thevideos.tv/js/jquery.min.js
@@||thevideos.tv/*/jwplayer*.js
```
