### ISSUE TITLE
http://www.ticotimes.net/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4214]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
The link: [link](http://www.ticotimes.net/2017/01/25/hard-rock-open-first-hotel-costa-ricas-pacific)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image2](https://cloud.githubusercontent.com/assets/15856304/22395204/5816665a-e53f-11e6-943a-ee21b720b6db.PNG)

![image3](https://cloud.githubusercontent.com/assets/15856304/22395206/5bb3d892-e53f-11e6-81ff-b4b9876ac8bb.PNG)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.4.60
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | 2 3 4 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1494618

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
ticotimes.net##div[class^="ticot-"]
```
