### ISSUE TITLE
http://www.movie-blog.org/ - false blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4215]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
The whole site is being blocked by a content blocker

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![file_000 1](https://cloud.githubusercontent.com/assets/15856304/22395399/00c9f842-e546-11e6-9acb-eacc165c166b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Browser: | Safari
Adguard version: | 1.1.4.36
Simplified filters(iOS) | Off
Adguard DNS: | Default
Adguard filters: | 2 3 4 6 12 15 101 118 123

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.
Which filter causes it?

**Comment by evgeniy-ADG** [comment]
German filter does that.

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||movie-blog.org$domain=movie-blog.org,~script,~image
```
