### ISSUE TITLE
https://www.heise.de/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4216]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
The header is blocked

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22395512/d938fd74-e549-11e6-9a68-ded223fc002f.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

See the screenshot

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22395517/ea1cb734-e549-11e6-87b6-3b9a77af602b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | all
Browser: | safari, chrome
Adguard version: | the current ones
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None 
Stealth mode options(Windows) | None
Adguard filters: | 2 3 4 6 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1495302

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed in social filter
