### ISSUE TITLE
http://allrecipes.com/ - annoyance, share buttons

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4218]
http://allrecipes.com/

The pop up asking to join when you first enter the site http://allrecipes.com

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22395862/2bf0f6a8-e553-11e6-829a-b2bb82580b11.png)

</details>

When browsing, you'll see this (http://allrecipes.com/recipes/416/seafood/fish/salmon/)

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22395899/163689da-e554-11e6-9657-8aaebf9bfb29.png)

</details>

Social media buttons: http://allrecipes.com/recipe/244337/pork-fries/?internalSource=hub%20recipe&referringContentType=search%20results&clickId=cardslot%2010

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22395888/e4ee8896-e553-11e6-9abb-06d3994bd5e9.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | The current one
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | Off
Adguard filters: | eng, annoyances, social media, spyware.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1495217

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
