### ISSUE TITLE
cronista.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#42201]
[https://www.cronista.com/apertura-negocio/empresas/Uber-sorprende-al-mercado-y-compra-la-chilena-Cornershop-20191011-0002.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.cronista.com/apertura-negocio/empresas/Uber-sorprende-al-mercado-y-compra-la-chilena-Cornershop-20191011-0002.html)

![share](https://user-images.githubusercontent.com/35470489/66692142-df1a1980-ec71-11e9-8c6d-14feb38b4fb1.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin
Firefox

**Comment by BlazDT** [comment]
Only left-over reproduced, but according to position it should be fixed too.
