### ISSUE TITLE
deutscherskiverband.de - Ad leftover - Social widget - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4223]
***Site***: http://www.deutscherskiverband.de/
***Description***: Ad leftover at the top. Social tabs at the right. Ads

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22396044/3969b3a0-e54f-11e6-9feb-94d9eaf34f03.png)

**http://www.deutscherskiverband.de/leistungssport_uebersicht_de,293.html:**

![image](https://cloud.githubusercontent.com/assets/10995998/22396049/70e5ed30-e54f-11e6-8dc4-b72b43b66693.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
.English filter | 1.1.7.60
Spyware filter | 1.0.10.47
Social media filter | 1.0.16.89
Annoyances filter | 1.0.9.41
German filter | 1.0.30.78
Mobile ads filter | 1.0.6.86
Safari filter | 1.0.2.24

**Comment by Alex-302** [comment]
fixed
