### ISSUE TITLE
macrumors.com

### ISSUE THREAD

**Issue by kfur** [AdguardTeam/AdguardFilters#42240]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
Site load script from [cdn.fraudjs.io](cdn.fraudjs.io) for fingerprinting.
* **Current behaviour**: 

* **Expected behaviour**: 
Fingerprinting script is blocked.

***Steps to reproduce the problem***:
Load [macrumors.com](macrumors.com) site with mobile UA.

***System configuration***

**Filters:**
AdGuard Base filter
AdGuard Tracking Protection filter
EasyPrivacy
Fanboy's Enhanced Tracking List
AdGuard Russian filter

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | MacOS
Operating system version (Android/iOS) | ?
Browser:                               | Safari 13
AdGuard version:                       | 1.5.4
Filters enabled:                       | YES
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@kfur I can't reproduce. Could you, please, record HAR file?(logout before it)
https://toolbox.googleapps.com/apps/har_analyzer/

**Comment by kfur** [comment]
it seems it's gone.
