### ISSUE TITLE
comedy-film.net - missed ad on page

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4225]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://comedy-film.net/novogodnie-i-rozhdestvenskie-komedii/page/2/  missed ad on page 

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/22397345/04946a3e-e578-11e6-9114-2f83636a7eee.png)

</details>

Windows 7 x64
Chrome extension
Filters: Russian, English, RU AdList 
Ticket ID: 1076701

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
