### ISSUE TITLE
3TV Phoenix iOS app - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4230]
The customer reported that the app is being blocked by the DNS filtering. Whitelisting the following domain fixed the issue: tegna.sc.omtrdc.net

The app: https://itunes.apple.com/us/app/3tv-phoenix-news/id401354850?mt=8

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Adguard version: | 1.1.4.36
Simplified filters(iOS) | Off
Adguard DNS: | Default
Adguard filters: | 2 3 4 11 12 14 101 207 211 208

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1495235

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
ok, whitelisted it.
