### ISSUE TITLE
http://www.openbusiness.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4231]
http://www.openbusiness.ru/biz/business/svoy-biznes-attraktsion-virtualnoy-realnosti/

Screenshot:

<details>

![file_000](https://cloud.githubusercontent.com/assets/15856304/22403124/b2162f5a-e616-11e6-95cf-a7692d4bb71c.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.3
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | Default
Adguard filters: | 1 2 3 4 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1495914

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
