### ISSUE TITLE
http://direct-v-adwords.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4233]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
The site is distorted by Adguard

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22404476/4a3e49fc-e63a-11e6-9b94-3ad6a1752542.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22404480/5ac4ea6a-e63a-11e6-8976-ea2772fbd471.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS
Browser: | Chrome
Adguard version: | 1.4
Adguard DNS: | None 
Adguard filters: | English, Russian, Spyware, Social media filter, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1494898

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
