### ISSUE TITLE
https:/www.ebay.co.uk/ - open box not blocked

### ISSUE THREAD

**Issue by GigabitEthernet** [AdguardTeam/AdguardFilters#4234]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

"Open" button not hidden even though the ad it would open is. Clicking the button opens a blank box where an ad would be.

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://i.imgur.com/OMGmgfF.png)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

The button should be hidden (blocked).

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Go to https://www.ebay.co.uk/ after resetting the cache and history and the button will be displayed.

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 10.12.3
Browser: | Safari 10.0.3
Adguard version: | Beta 2.5.12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Adguard filter | Version
--- | ---
English filter | 1.1.7.73
Safari filter | 1.0.2.25

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
added
ebay.co.uk###pushdownAdFragment

**Comment by GigabitEthernet** [comment]
Unfortunately the fix messes up the look of the page.

[image](http://i.imgur.com/1yrui0E.png)

**Comment by Alex-302** [comment]
strane. It is fine on my side

![image](http://imagizer.imageshack.com/img922/9035/WeMcwU.png)
