### ISSUE TITLE
[Turkish filter] [ad network] gelirartisi - app.gelirartisi.com

### ISSUE THREAD

**Issue by ahmedtds** [AdguardTeam/AdguardFilters#42368]
it's an ad network: http://www.gelirartisi.com/index.php?lang=eng

makes this request which slows pages a lot:
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +0 |  |  | eksisozluk.com | 3 | script | `https://app.gelirartisi.com/withdfp.js?sid=6` |
</details>

requests to app.gelirartisi.com should be blocked, because it causes both a privacy concern and slow page loadings

thanks

**Comment by Alex-302** [comment]
Hi. Where did you find that?

**Comment by ahmedtds** [comment]
eksisozluk.com but you can see more sites using it in "Publishers" section of their site

**Comment by Alex-302** [comment]
Ok. Thanks.
