### ISSUE TITLE
safari-lock.com/de2/index.html - Spyware/Malware

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4238]
***Site***: http://safari-lock.com/de2/index.html
***Description***: Spyware/Malware site which won't let you close the tab on mobile devices (iOS, couldn't test something else).

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22421527/e9e2da9c-e6e7-11e6-804d-a3a722b89791.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Browser: | Safari
Adguard version: | 1.1.5
Adguard driver (Windows): | -
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | -

Adguard filter | Version
--- | ---
English filter | 1.1.7.81
Spyware filter | 1.0.10.50
Social media filter | 1.0.16.96
Annoyances filter | 1.0.9.47
German filter | 1.0.30.78
Mobile ads filter | 1.0.6.89
Safari filter | 1.0.2.26

**Comment by Alex-302** [comment]
added
