### ISSUE TITLE
http://greenfrogplace.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4240]
Cannot add lots into the cart.

Here's the example link: http://greenfrogplace.com/k-chayu/

***Steps to reproduce the problem***:

1. Go here: http://greenfrogplace.com/k-chayu/
2. Add a lot
3. Open the Assistant and hit "Undo the last action"
4. Try to add more lots
5. You'll get the page stuck on loading smth and then nothing is added

The issue occurs also without #3 but you'll need to spend some time trying to reproduce it, it's not the permanent one. Screenshots won't show the issue. Was able to replicate it on Mac with the next settings:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS 10.12.2
Browser: | Chome, the latest one
Adguard version: | 1.4
Adguard DNS: | None
Adguard filters: | 1 2 3 4 14 104

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1495513

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I'm not sure that problem is caused by filters. Maybe some conflict with assistant extension.

**Comment by evgeniy-ADG** [comment]
I dunno what it is but it can be reproduced anytime and it breaks the site's functions. Should we file it somewhere else?

**Comment by Alex-302** [comment]
You can write to Windows repository.
