### ISSUE TITLE
https://www.hometheater.co.il - Annoyances 

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#4241]
Hey
in site: https://www.hometheater.co.il have message with you use in adblock
screenshot: http://prntscr.com/e28e4n
i think need block message this on Annoyances Filter

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
@@||hometheater.co.il/js/ads.js
```

**Comment by MrTal** [comment]
Hey
this no work, still have this message: http://prntscr.com/e28e4n
the filter this help:
[###aBHCgMfmnEyi
###center_728x90
](url)

**Comment by Alex-302** [comment]
replaced by
```
hometheater.co.il##td[width="900"][align="center"][valign="top"]
```

**Comment by MrTal** [comment]
now empty space in iIn the same place of message:
http://prntscr.com/e38bp6
filter this help:
`###center_728x90`

**Comment by Alex-302** [comment]
I don't see it

![image](http://imagizer.imageshack.com/img923/2779/EwmGhp.png)

**Comment by MrTal** [comment]
see hare exmple:
https://www.hometheater.co.il/forum12

**Comment by Alex-302** [comment]
added
```
hometheater.co.il###likebox
hometheater.co.il##div[style="width:728px; height:90px;"]
```

**Comment by MrTal** [comment]
now this work, tank you.
