### ISSUE TITLE
[Anti-adblock] newnavitel.blogspot.fr

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#4242]
Link: http://newnavitel.blogspot.fr/p/skin_6617.html

Screenshot: https://www.screencast.com/t/l6TYhWx8jUut

Original thread: https://forum.adguard.com/index.php?threads/2366/#post-123917

**Comment by Alex-302** [comment]
Криво детект сделали. Сообщение даже при выключенном блокировщике.
