### ISSUE TITLE
elperiodico.com - unending loading

### ISSUE THREAD

**Issue by oprotsyk** [AdguardTeam/AdguardFilters#4243]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***elperiodico.com - unending loading***:
* **Page does not finish loading**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/14153331/22433840/71698094-e722-11e6-9188-003064a77a8c.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

The page should load with Adguard enabled.

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

Search for elperiodico.com

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Chrome
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  Off 
Adguard DNS: | None
Adguard filters: | 2, 3, 4, 5, 11

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1261942

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||bc.marfeel.com/statics/marfeel/gardac.js$domain=elperiodico.com
```

**Comment by ypetruk** [comment]
Never ending page load on iOS (http://www.elperiodico.cat)
#of Ticket: 1572608
<details>

![img_3344](https://user-images.githubusercontent.com/28784344/27001682-b1301b62-4dd8-11e7-9411-4d798f6166bf.png)

<\details>
