### ISSUE TITLE
shop-apotheke.com - Annoyance - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4247]
***Site***: https://www.shop-apotheke.com/ and https://m.shop-apotheke.com/
***Description***: 
- Cookie notice at the top (on mobile site too).
- Red newsletter annoyance banner below cookie notice (on mobile site too).
- Orange ad background.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22445498/f652bd1e-e747-11e6-9173-9b7db119b838.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22445541/2eaad4d0-e748-11e6-816e-a3aaa8ed8ef7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.306.1604
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.7.90
Spyware filter | 1.0.10.51
Social media filter | 1.0.16.97
Annoyances filter | 1.0.9.50
German filter | 1.0.30.80
Mobile ads filter | 1.0.6.90
Safari filter | 1.0.2.27

**Comment by Alex-302** [comment]
fixed
