### ISSUE TITLE
metropoles.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#42495]
[https://www.metropoles.com/concursos-e-empregos/quinta-e-o-ultimo-dia-de-inscricao-a-uma-das-409-vagas-em-jogo](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.metropoles.com/concursos-e-empregos/quinta-e-o-ultimo-dia-de-inscricao-a-uma-das-409-vagas-em-jogo)

![share](https://user-images.githubusercontent.com/35470489/66996872-daa59480-f0a7-11e9-8854-a274bbb1f0ae.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by adranger** [comment]
@AdamWr do you see this message at the bottom now?

![metrópoles](https://user-images.githubusercontent.com/35470489/72371223-a3647500-36e2-11ea-97bb-0126c4f79375.png)

**Comment by AdamWr** [comment]
No, I don't see this message, at least not with AdGuard.

In uBO, you can probably use this rule:
`metropoles.com##+js(nostif, removeChild, 100)`
if I'm not wrong, it's used against this kind of anti-adblock.

**Comment by adranger** [comment]
@mapx- please see the two comments above.

**Comment by mapx-** [comment]
fixed as annoyance, enable the specific list
