### ISSUE TITLE
vnexpress.net - missed ad

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4249]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://vnexpress.net/photo/thoi-su/lang-mai-tram-tuoi-o-mien-tay-khoe-sac-vang-ruc-3534465.html - missed ad on page

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/22445824/03d6e082-e752-11e6-8751-ff50f8576f2f.png)

</details>

***System configuration***
Application version: 1.1.5.40

Platform: iOS
OS: 10.2.1
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.7.74 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.50 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.92 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.9.45 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.97 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.26 Enabled=YES
ID=117 Name="Adblock Polska" Version=1.0.0.52 Enabled=YES
ID=214 Name="ABPVN List" Version=1.0.2.88 Enabled=YES
ID=226 Name="Fanboy's Vietnamese" Version=1.0.0.2 Enabled=YES
Ticket ID: 1496428

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Not reproduced.
