### ISSUE TITLE
soundhound app - cannot connect to the server

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4250]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

The [app](https://play.google.com/store/apps/details?id=com.melodis.midomiMusicIdentifier.freemium&hl=en) returns the error while searching for songs
Disabling the HTTPS filtering for the app DIDN'T HELP.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22454107/45c8e4f6-e78c-11e6-8bf7-20f0b6ad1c2a.png)

</details>

***Expected behavior**: 

When you hit 'retry', it searches as intended. Should do the same without 'retry'.

***Steps to reproduce the problem***:

1. Open Soundhoun app for Android
2. Hit the yellow/black circle in the middle to start searching
3. Wait
4. See the error pop up

***System configuration***

Information | value
--- | ---
Operating system: | Android 5.0
Adguard version: | 2.8.76
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On Default
Adguard DNS: | Default on my end, disabled on user's end 
Adguard filters: | 2, 3, 4, 1, 11

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1008106, see logs there

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
фильтрами не починить.
https://github.com/AdguardTeam/AdguardForAndroid/issues/781
