### ISSUE TITLE
http://www.torrentino.me/ - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4251]
http://www.torrentino.me/torrent/100930

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22455726/1df91fc6-e797-11e6-839f-78bd0d039851.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.3
Browser: | Safari
Adguard version: | 1.1.5.65 
Simplified filters(iOS) | Off
Adguard DNS: | None 
Adguard filters: | 2 3 4 14 1 11 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1138135

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
