### ISSUE TITLE
https://riafan.ru/ - ads / sponsored content

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4252]
https://riafan.ru/600239-tramp-obeshchal-merkel-priehat-v-germaniyu-na-sammit-g20

![image](https://cloud.githubusercontent.com/assets/15856304/22457090/a2d54fce-e79e-11e6-9787-34d867955b58.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome, the latest one
Adguard version: | 6.1
Adguard driver (Windows): | WFP
Adguard DNS: | None 
Stealth mode options(Windows) | basic settings
Adguard filters: | 1, 2,3,4,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1449704

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
