### ISSUE TITLE
http://www.mebelkmk.ru

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardFilters#4253]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
Extension
http://www.mebelkmk.ru/shop/category/miagkaia-mebel/mini-divany
button "Заказать" does not work

**helps disabling Spyware filter**

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/22458868/128ca300-e7a7-11e6-895e-68d9c79fa6cb.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/18548949/22458837/f5a0ce2e-e7a6-11e6-86a6-4bc8d6b54e80.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome, FF
Adguard version: | 2.5.11
Adguard filters: | 1,2,3

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1496660

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Spyware filter
```
mebelkmk.ru#%#window.yaCounter27017517 ={ reachGoal: function() {} };
```
