### ISSUE TITLE
https://www.acunn.com/ There is a front Ad

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardFilters#4254]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: hi
When you enter the https://www.acunn.com/, you see big ad which middle of the page. can you block this?
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot: http://prntscr.com/e2m90b

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: |  Chrome, Moziila
Adguard version: | 
Adguard driver (Windows): | WFP 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): |
Simplified filters(iOS) | 
Adguard DNS: | None 
Stealth mode options(Windows) | 
Adguard filters: | ENGLISH, SPYWARE, SOCIAL MEDIA, Annoyances, Mobile Ads, SAFARI, TURKISH

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
||img.acunn.com/s/template/acunn/script/push.js
```
