### ISSUE TITLE
https://www.ecosia.org - useful ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4255]
https://www.ecosia.org

Consider adding them to the useful ads filter. 

Adguard enabled
![ecosia2](https://cloud.githubusercontent.com/assets/15856304/22465274/8efbca94-e7c3-11e6-8af9-e9b4844dee31.png)

and disabled:
![ecosia](https://cloud.githubusercontent.com/assets/15856304/22465287/9c94208e-e7c3-11e6-8ca8-3cf6356db9f2.png)

***System configuration***

Information | value
--- | ---
Operating system: | All
Browser: | Chrome
Adguard version: | the current ones
Adguard DNS: | None 
Adguard filters: | english, social media, enabling useful ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1497071

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
не понял вопроса. Как связаны сайт и поиск гугла?

**Comment by evgeniy-ADG** [comment]
Мы включаем фильтр, который разблокирует полезную рекламу, но в их поисковике она не появляется. Они попросили, чтобы у них это работало так же, как у Google.

**Comment by evgeniy-ADG** [comment]
Это не гугл, это - powered by bing, кажется.

**Comment by Alex-302** [comment]
Ок, изменил фильтр полезной рекламы.
