### ISSUE TITLE
www.anews.com -  missed ad

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4258]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:http://www.anews.com/ua/ - missed ad on page

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/22486960/2e4164b0-e814-11e6-8a10-a579a4b0be9b.png)

</details>

***System configuration***

Application version: 1.1.5.65

Platform: iOS
OS: 10.2
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.7.87 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.50 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.97 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.9.49 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.97 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.46.23 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.90 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.27 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.73.1 Enabled=NO
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=NO
ID=213 Name="RU AdList: BitBlock" Version=1.0.70.58 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.70.37 Enabled=YES

Ticket ID: 1489046

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не повторяется. Это обычная реклама яндекса, без выкрутасов.
