### ISSUE TITLE
Narwhal app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4260]
the app: https://itunes.apple.com/us/app/narwhal-for-reddit/id845422455?mt=8

![image1 1](https://cloud.githubusercontent.com/assets/15856304/22498060/beab93a0-e85e-11e6-942e-19a5af93a8fb.PNG)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Adguard version: | 1.1.5.40
Simplified filters(iOS) |  Off
Adguard DNS: | Default 
Adguard filters: | 2 3 4 11 12 14 101 118 123 122 207 211 210

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1436166

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced on my side.

**Comment by evgeniy-ADG** [comment]
There should be a DNS log in the ticket which we're asking each time such problem occurs. I don't see these or any other ads, too.

**Comment by Alex-302** [comment]
I don't know when this app was launched.

**Comment by dzamyshlyayeva** [comment]
customer 1436166 sent another DNS log with timing

**Comment by Alex-302** [comment]
Nothing...
You can ask user for captured traffic by Fiddler
https://forum.adguard.com/index.php?threads/missed-ads-submission-rules.1879/
`2. How to capture traffic of the site or the application?​`
I can help to do it remotely.

**Comment by dzamyshlyayeva** [comment]
done

**Comment by evgeniy-ADG** [comment]
The Fiddler capture request has been ignored but we have -another- log and screenshot here: 1436166

**Comment by Alex-302** [comment]
Facebook ads. We can't block it without breaking FB.
He can add this rule, if doesn't use Facebook
```
||graph.facebook.com^
```

**Comment by dzamyshlyayeva** [comment]
missed ad in Narwhal app again 
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/25288230/3a351472-26cd-11e7-8098-a43ac0c67e4a.png)

</details>

Application version: 1.1.5.40
Device: iPhone
Platform: iOS
OS: 10.3.1
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.14.97 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.59 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.80 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.11.99 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.5 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.89 Enabled=YES
ID=101 Name="EasyList" Version=1.0.69.51 Enabled=NO
ID=118 Name="EasyPrivacy" Version=1.0.77.40 Enabled=NO
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.69.55 Enabled=NO
ID=122 Name="Fanboy's Annoyances" Version=1.0.69.73 Enabled=NO
ID=234 Name="ROLIST2" Version=1.0.0.1 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.77.56 Enabled=NO
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=NO
ID=210 Name="Spam404" Version=1.0.1.73 Enabled=NO


Ticket ID 1436166

**Comment by Alex-302** [comment]
What ad system is used by this banner?
