### ISSUE TITLE
Bug with cosmetic filter in Addguard Annoyance in Aliexpress.com

### ISSUE THREAD

**Issue by mikhoul** [AdguardTeam/AdguardFilters#42605]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Bug with cosmetic filter in Addguard Annoyance***:
* **Block the page from scrooling**: 

[//]: # (The filter block improperly the main advertisement and prevent to be able to use Aliexpress.com )

Here's the page without cosmetic filter with the advertisement:
![image](https://user-images.githubusercontent.com/5678673/67135066-e5654400-f1e3-11e9-9150-531586b8cbe3.png)

Here's the page with the filter enabled:

![image](https://user-images.githubusercontent.com/5678673/67135139-98ce3880-f1e4-11e9-80af-94db03d3190a.png)

Since the overlay is always there you can't scroll on the page.

Here's the culprit:

![image](https://user-images.githubusercontent.com/5678673/67135097-37a66500-f1e4-11e9-803f-b18d1c233e38.png)

* **Expected behaviour**: 

Just remove the advertisement and being able to scroll.

***System configuration***

I use NanoAdblocker with your list in Brave.

Regards :octocat:

**Comment by krystian3w** [comment]
Activate uBO Annoyance: https://github.com/uBlockOrigin/uAssets/issues/6184

https://github.com/uBlockOrigin/uAssets/commit/5bfea96f5be37c053db3618346987341f27da1bb

**Comment by mikhoul** [comment]
Thanks a lot, it worked fine but I had to ad "##.opened.next-overlay-wrapper" to hide the overlay but now I can scroll.
