### ISSUE TITLE
Cookie banner on https://stellarium-web.org/

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#42617]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 
Cookie banner on the site https://stellarium-web.org/

<details><summary>Screenshot:</summary>

![image](
![image](https://user-images.githubusercontent.com/29574622/67139916-38d4a200-f277-11e9-8d30-59ddaa2fc778.png)
)
</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | ?
Browser:                               | Mozilla Firefox Developer Edition 71
AdGuard version:                       | ?
Filters enabled:                       | Adguard Annoyances, Adguard base list, Adguard tracking protection
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by krystian3w** [comment]
Maybe:

`##.secondary.v-snack__wrapper`

@kiboke, this is accepted by JS in Addon?

**Comment by kiboke** [comment]
> Maybe:
> 
> `##.secondary.v-snack__wrapper`
> 
> @kiboke, this is accepted by JS in Addon?

Not yet. I'll block `.v-snack`
