### ISSUE TITLE
https://e.mail.ru/ - Adguard distorts the site in Edge

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4261]
https://e.mail.ru/messages/inbox?back=1&back=1#

![image](https://cloud.githubusercontent.com/assets/15856304/22502387/4ae69214-e875-11e6-9051-62d1a414cf2b.png)

STR:

1. Go to mail.ru
2. Open a mailbox
3. WAIT
4. See the result

***System configuration***

Information | value
--- | ---
Operating system: | Windows NT 10.0.14393.0
Browser: | Microsoft Edge 38.14393.0.0
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard DNS: | None
Stealth mode options(Windows) | On
Adguard filters: | 1 2 6 7 21

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1101880

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
>Покопался с фильтрами в Антибаннере, пробовал с английский, русским и немецким. Немецкий сейчас включен, с ним все в порядке. А вот английский, русский, если один из них включен, а другой отключен, через какое-то время опять появляется смещение и страница как бы виснет (менял их местами, тоже самое). Сейчас отключены данные два фильтра, да, почта работает, но реклама повылазила

**Comment by Alex-302** [comment]
Не повторяется. Фильтры свежие? Несколько дней назад было правило, которое могло вызвать торможения, но ничего не ломало.

**Comment by evgeniy-ADG** [comment]
Да. Вот еще такая же жалоба: 1350285
Проверил обновления, перезапустился, все повторяется. Нужно походить по папкам и поскролить туда-сюда. Минуты через 2 вылазит.

**Comment by Alex-302** [comment]
Давай завтра уже гляну.
А от фильтров зависит?

**Comment by evgeniy-ADG** [comment]
Я не пробовал, если честно, но вот выше писали, что или русский, или английский. Если один из них вкл., то страницу перекашивает.

**Comment by Alex-302** [comment]
`2. Другой браузер Internet Explorer также всё нормально`
может какой-то конфликт с Edge. Без доступа не разобраться.

**Comment by Alex-302** [comment]
@evgeniy-ADG ну что? Посмотрим?

**Comment by evgeniy-ADG** [comment]
Да, давай.

**Comment by Alex-302** [comment]
эх, ну подождём тогда.
А юзер ничего больше не писал?
