### ISSUE TITLE
Parental control doesn't block sex shops on Google search

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#4262]
Parental Control set to 13 years finds sex shops on Google.

**Comment by Alex-302** [comment]
@zebrum

**Comment by zebrum** [comment]
it seems to work as it supposed on my side
![screen](https://cloud.githubusercontent.com/assets/23637588/22522990/c8902ab4-e8ce-11e6-8b85-937593733a31.jpg)

**Comment by zebrum** [comment]
@Tetiana2020 please be sure that user is searching under protected user

**Comment by deLumren** [comment]
I also can google "sex shop" under ANY age restrictions. With 10 and 13 options I even get the map to find the nearest one without problems :)
Everything is set up properly (I think), only have one user on PC

**Comment by zebrum** [comment]
well, now i can confirm the issue.

**Comment by zebrum** [comment]
@Tetiana2020 @deLumren guys, actually we use web engine's safe search, so in this case it just how google safesearch works
