### ISSUE TITLE
Geni.us doesn't open

### ISSUE THREAD

**Issue by dzid26** [AdguardTeam/AdguardFilters#42642]
Geni.us is completely blocked while using AdguardDNS

**Comment by Alex-302** [comment]
Hi. It is blocked as analytics. Not sure about exclusion.

**Comment by dzid26** [comment]
Big YouTubers use it nowadays to link products, so it is significant annoyance not being able to use it. 

Their privacy terms seem aggressive though https://www.geni.us/privacy, so I understand why it's blocked. I am not an expert though.

Thanks.

**Comment by Alex-302** [comment]
I need a real example of using this service. Btw it is blocked by EasyPrivacy filter.

**Comment by dzid26** [comment]
It ussualy acts as link shortener [https://geni.us/Laphroaig10](https://geni.us/Laphroaig10) or search shortcut [https://geni.us/PanasonicGH5Camera](https://geni.us/PanasonicGH5Camera).

But currently, even just visiting the main webpage [www.geni.us/](www.geni.us/) doesn't work with AdGuard DNS.

**Comment by Alex-302** [comment]
Got it.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #147](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/147) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/148
