### ISSUE TITLE
pornolab.net - Left ads

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#4264]
***Description***: Missed ads on http://f2.s.qip.ru/Ogbqiu1v.png

Screenshot:
<details>

![ogbqiu1v](https://cloud.githubusercontent.com/assets/17504743/22518110/1ae8d4fc-e8b4-11e6-985f-8a90eecc2ee6.png)
</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | Extension 
Adguard filters: | Пользовательский, Английский, Фильтр счетчиков и систем аналитики, Экспериментальный, Фильтр раздражителей, Русский (Reproduced on Mac)

Ticket ID(if exists): 1076701

**Comment by Alex-302** [comment]
Не убрать.

**Comment by TomCruiseXZ** [comment]
> Не убрать.

Да ну
