### ISSUE TITLE
hao123.com - Missed ads 

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#4265]
***Description***: Missed ads on hao123.com

Screenshot:
<details>

![image1](https://cloud.githubusercontent.com/assets/17504743/22518570/bd177f8e-e8b5-11e6-9771-83cf3ac9dc98.PNG)
</details>

***System configuration***

Information | value
--- | ---
Operating system: |  OS 9.3.5  
Adguard version: | 1.1.5.40
Adguard filters: | "User filter", "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Filter unblocking useful ads", "Experimental filter", "Mobile Ads filter", "Safari filter", "Simplified domain names filter"

Ticket ID(if exists): 1330122

**Comment by Alex-302** [comment]
I don't understand, where are ads,
Are these images - ads?

![image](http://imagizer.imageshack.com/img922/2709/eIy1N9.png)
