### ISSUE TITLE
mostindiantube.com [NSFW] [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#42662]
**Site**: https://www.mostindiantube.com/video/gorgeous-sweaty-indian-habitat-wife-beguiled-by-brother-in-law/

**Issue**: Please remove the empty ad banners seen on the page. Pop-ups also seen

**Screenshot**: http://prntscr.com/plqgix

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 77.0.3865.90 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 3.2.1	 `

**Filters**:
```
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404
NoCoin Filter List

```

**Stealth Mode Settings**:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled (Default)

**Comment by Alex-302** [comment]
This site literally has no visitors.
