### ISSUE TITLE
youku.com - Missed ads

### ISSUE THREAD

**Issue by Tetiana2020** [AdguardTeam/AdguardFilters#4266]
***Description***: Missed ads on http://www.youku.com/

Screenshot:
<details>

![image2](https://cloud.githubusercontent.com/assets/17504743/22518611/e503b698-e8b5-11e6-9ac4-7fdee379c06b.PNG)
</details>

***System configuration***

Information | value
--- | ---
Operating system: |  OS 9.3.5 
Adguard version: | 1.1.5.40
Adguard filters: | "User filter", "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Filter unblocking useful ads", "Experimental filter", "Mobile Ads filter", "Safari filter", "Simplified domain names filter"

Ticket ID(if exists): 1330122

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
youku.com##div[id$="_ykbanner"]
```
