### ISSUE TITLE
ParadoxPlaza.com - Site broken (AdGuard Annoyances filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#42666]
### Affected site:
`https://www.paradoxplaza.com/`

### Issue:
Nothing can be clicked, because of a blocked cookie consent, which needs to be accepted!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* AdGuard Annoyances filter

### Problem rule:
`###cookies-info`

### Possible fix:
`paradoxplaza.com#@##cookies-info`

### Other problem filters:
* Fanboy's Annoyance List / Fanboy's Cookie List _(reported)_ https://github.com/ryanbr/fanboy-adblock/issues/1215/
* I don't care about cookies _(reported)_

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.7.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by zloyden** [comment]
Fixed. The update will be available in 1-2 hours.

**Comment by adranger** [comment]
@zloyden  Blocking connections to `cloudfront.net/cookie-widget` stops on the forum subdomain. Please take a look: [https://forum.paradoxplaza.com/forum/index.php?threads/what-are-some-other-games-like-cities-in-motion-2-lets-make-a-list-version.681430/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://forum.paradoxplaza.com/forum/index.php?threads/what-are-some-other-games-like-cities-in-motion-2-lets-make-a-list-version.681430/)

![cookie](https://user-images.githubusercontent.com/35470489/68101161-faf89000-feaa-11e9-9c33-4c2930c7e4ab.png)

**Comment by zloyden** [comment]
@adranger thanks for your reply, fixed for the forum subdomain, update should be available in 1-2 hours.
