### ISSUE TITLE
migros.com.tr

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#42667]
https://www.migros.com.tr/le-petit-marseillais-kalip-sabun-portakal-90-g-p-1c99cfa

**Description**: Incorrect Blocking
* **Current behaviour**: 

<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/34379403/67157812-22434f00-f33a-11e9-996a-4eb72f70b59c.png)

</details>

* **Expected behaviour**: 

<details><summary>Screenshot:</summary>

![dd](https://user-images.githubusercontent.com/34379403/67157856-2d967a80-f33a-11e9-8eb4-99a9d7d2b0d5.png)

</details>

Information                            | Value
---                                    | ---
Browser:                               | Firefox Quantum
AdGuard version:                       |  Extension 3.2.1
Filters enabled:                       | Base-Annoyance-NoCoin-Social-Tracking Protection-Turkish
AdGuard DNS:                           | None 
Stealth mode options | Enabled

---

- "sanalmarket.com.tr" is now redirecting to "migros.com.tr".Please update the rules for this domain.
<details><summary>Screenshot:</summary>

![screenshot-github com-2019 10 20-13_13_07](https://user-images.githubusercontent.com/34379403/67158003-7b5fb280-f33b-11e9-9cbe-f21f79c28403.png)

</details>

- Rules are obsolete now because the design has changed.Remove these rules.
```
sanalmarket.com.tr##a[onclick^="javascript:shareFacebook"]
@@||banner.migros.com.tr^$domain=moneyclubkart.com
```

**Comment by AdamWr** [comment]
Fixed, thank you.
