### ISSUE TITLE
Add block EU Cookie filter list

### ISSUE THREAD

**Issue by heubergen** [AdguardTeam/AdguardFilters#4267]
My PR was not so successful so please add the filter to the correct list @Alex-302 
https://github.com/AdguardTeam/AdguardBrowserExtension/pull/543

The filter is the only active maintened eu cookie block list left on github (as Prebake seems to be dead)
https://github.com/r4vi/block-the-eu-cookie-shit-list

**Comment by Alex-302** [comment]
Thanks. I will add it in the morning.

**Comment by ameshkov** [comment]
We may, but we'd like to avoid swearing words in the filter subscriptions list.

What name can we use instead?

**Comment by Alex-302** [comment]
I think, according to their license, we can remove swearing from the filter name)
https://github.com/r4vi/block-the-eu-cookie-shit-list

**Comment by heubergen** [comment]
Yeah, let's take block-the-eu-cookie-list for example.

**Comment by K-os** [comment]
There is an actively maintained fork of the original Prebake list with a proper license (MIT):
https://gitlab.com/isaakm/Custom-Prebake

**Comment by Alex-302** [comment]
As I see, it is not frequently updated

**Comment by Alex-302** [comment]
It is dead.

**Comment by heubergen** [comment]
My original request is still actively maintained.  (last change 11 days ago)

**Comment by Alex-302** [comment]
I looked at
<details><summary>Screenshot:</summary>

![image](http://imagizer.imageshack.com/img924/9371/Q0YvtV.png)
</details>

**Comment by heubergen** [comment]
I'm currently use it and I don't see so much more cookie messages and when I add a rule :)
