### ISSUE TITLE
ads in Bus+  app

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4268]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***ads in Bus+  app***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/e3fh8y

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Adguard version: | 1.1.5.40
Simplified filters(iOS) | Off
Adguard filters: | ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.3.66 Enabled=NO

ID=3 Name="Spyware filter" Version=1.0.7.94 Enabled=NO

ID=4 Name="Social media filter" Version=1.0.13.32 Enabled=NO

ID=14 Name="Annoyances filter" Version=1.0.4.96 Enabled=NO

ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=NO

ID=11 Name="Mobile Ads filter" Version=1.0.5.10 Enabled=NO

ID=12 Name="Safari filter" Version=1.0.1.46 Enabled=NO

ID=101 Name="EasyList" Version=1.0.63.38 Enabled=NO

ID=104 Name="EasyList China" Version=1.0.72.69 Enabled=NO

ID=219 Name="ChinaList+EasyList" Version=1.0.1.78 Enabled=NO

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1496881

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added:
```
||ads.ad2iction.com^
```
User should to check it in custom filter.

@vmalyuta со скринами будь внимательнее. Конкретно здесь - скрин превьюхи.
