### ISSUE TITLE
ads on - http://rus.delfi.ee/daily/

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4269]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***ads on - http://rus.delfi.ee/daily/***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/e3fyor
http://prnt.sc/e3fyvs

<details>
http://prnt.sc/e3fyor
http://prnt.sc/e3fyvs
![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off

Adguard filters: | ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.8.4 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.56 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.98 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.46.32 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.92 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.30 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.76 Enabled=YES
ID=101 Name="EasyList" Version=1.0.67.36 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.73.80 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.67.39 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.67.58 Enabled=YES
ID=110 Name="EasyList Lithuania" Version=1.0.1.13 Enabled=YES
ID=111 Name="Latvian List" Version=1.0.0.34 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.73.93 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.89 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.73.94 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=218 Name="Estonian List" Version=1.0.1.4 Enabled=YES
ID=229 Name="I dont care about cookies" Version=1.0.0.11 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.70.69 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.70.48 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1497811

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
