### ISSUE TITLE
[Android] https://play.google.com/store/apps/details?id=com.vvf.fmcube

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#427]
В режиме http прокси реклама в приложении не блокируется, в режиме vpn - блокируется. 
Можно ли как-то исправить?

https://qcrm.cc/#/customer/1008405

**Comment by Alex-302** [comment]
У меня чисто в обоих режимах. Пусть прибьёт приложение с очисткой кэша, может поможет.

**Comment by vbagirov** [comment]
Утверждает, что прокси настраивал по инструкции в самой программе, и что во всех остальных приложениях работает нормально. Устройство не рутовано, вариант с остановкой приложения с очисткой кэша не помогает.

**Comment by Alex-302** [comment]
||googleadservices.com^$empty
пусть такое попробует с чисткой. В логе это единственный не заблокированный запрос.

**Comment by vbagirov** [comment]
Не помогло ему такое правило.
