### ISSUE TITLE
incorrect blocking - http://www.list-org.com/search.php?type=name&val=%D0%BF%D0%B0%D1%82

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4270]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***incorrect blocking - http://www.list-org.com/search.php?type=name&val=%D0%BF%D0%B0%D1%82***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/e3ilrc

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS (extension/application)
Browser: | Chrome
Adguard version: | 1.4.0/2.5.11
Adguard DNS: | None 
Adguard filters: | ID=0 Name="User filter" Version=1.0.0.0
ID=2 Name="English filter" Version=1.1.8.16
ID=3 Name="Spyware filter" Version=1.0.10.59
ID=4 Name="Social media filter" Version=1.0.17.5
ID=14 Name="Annoyances filter" Version=1.0.9.67
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.89
ID=1 Name="Russian filter" Version=1.0.46.36
ID=116 Name="Wiltteri" Version=1.0.1.70
ID=207 Name="Adblock Warning Removal List" Version=1.0.73.99
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1323060

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed

**Comment by vmalyuta** [comment]
Спасибо!

Сори за скрин, буду проверять
