### ISSUE TITLE
http://www.hurriyet.com.tr  Automatically start Video

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardFilters#4271]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
http://www.hurriyet.com.tr/e-5te-ceset-soku-temizlik-iscisi-buldu-belden-asagisi-ciplak-40353732

When i enter any news page which within video on hurriyet.com.tr, video in news page start automatic play. Can you fix this? 
* **Current behaviour**: 
For example: 
http://www.hurriyet.com.tr/e-5te-ceset-soku-temizlik-iscisi-buldu-belden-asagisi-ciplak-40353732

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:  http://prntscr.com/e3j5dk

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome, Mozilla
Adguard version: | 2.5.11
Adguard driver (Windows): | WFP 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): |  
Simplified filters(iOS) | 
Adguard DNS: | None 
Stealth mode options(Windows) | 
Adguard filters: | ENGLISH, SPYWARE, SOCIAL MEDIA, Annoyances, Mobile Ads, SAFARI, TURKISH

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I recommend `Disable HTML5 Autoplay` browser extension. It is more universal solution.
https://chrome.google.com/webstore/detail/disable-html5-autoplay/efdhoaajjjgckpbkoglidkeendpkolai?utm_source=chrome-app-launcher-info-dialog

**Comment by tagataho** [comment]
But then YouTube's videos not open automatically; i only want to disable in hurriyet.c.tr

**Comment by Alex-302** [comment]
try this
```
https://github.com/AdguardTeam/Userscripts/tree/master/disableAutoplay
```
