### ISSUE TITLE
ads on - http://whattomine.com/coins?

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4272]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***ads on - http://whattomine.com/coins?***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/e3jp0x
[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5
Simplified filters(iOS) | Off
Adguard DNS: | None 
Adguard filters: | D=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.8.10 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.57 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.3 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.46.36 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.33 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1498054

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed.
@vmalyuta тип проблемы в названии лучше после адреса писать. 
А лучше вообще не писать, если ставишь метки)

**Comment by koshol** [comment]
Тот же баннер вернулся :(

**Comment by Alex-302** [comment]
поправил

**Comment by koshol** [comment]
![9](https://cloud.githubusercontent.com/assets/25602156/23785635/c2a93402-0579-11e7-86bb-a5db946bae0b.png)
вернулась...
Выделил рекламу красным!

**Comment by koshol** [comment]
![10](https://cloud.githubusercontent.com/assets/25602156/23786367/a79a44d6-057d-11e7-8de7-7f8f17b97b50.png)

**Comment by Alex-302** [comment]
заменил на 
whattomine.com##.baikal-link
