### ISSUE TITLE
paypal.com

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#42742]
Сайт в исключениях - это излишне.

<details><summary>Screenshot:</summary>

![2019 10 21-2](https://user-images.githubusercontent.com/17948007/67240310-dd163e80-f459-11e9-8938-c70a146e0650.png)
</details>

[https://www.paypal.com/ru/home](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.paypal.com/ru/home)

`@@||paypal.com^$document,badfilter`

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.3.1
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
Ты им пользуешься?

**Comment by XX-J** [comment]
> Ты им пользуешься?

 Да, но не часто.
 С разблокирующим правилом `@@||paypal.com^$document,badfilter` проверял > В работе интерфейса, проведении платежа, удалении старой и добавлении новой карты проблем не замечено.

**Comment by Alex-302** [comment]
ок
