### ISSUE TITLE
ficbook.net - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4274]
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screenshot_2017-02-02-18-29-32](https://cloud.githubusercontent.com/assets/22892774/22558438/5efe6bc6-e976-11e6-8e03-a12e47644763.png)

</details>

***Steps to reproduce the problem***:

1) Go to https://ficbook.net/
2) Choose any book (for example https://ficbook.net/authors/1631948)

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Chrome
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On
Adguard filters: | English, Spyware, Social media, Annoyances, Russian, Mobile Ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1146797

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
