### ISSUE TITLE
Adding Fanboy Ultimate List - feature request

### ISSUE THREAD

**Issue by oprotsyk** [AdguardTeam/AdguardFilters#4275]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Adding Fanboy Ultimate List to the Filters List***:
* **Fanboy Ultimate List includes Easylist,
Easyprivacy, Enhanced Trackers List and Annoyances List**: 

Customer ID 1021351

**Comment by Alex-302** [comment]
I think it is not the best filter. User can enable filters that he need.
