### ISSUE TITLE
Ad Removing Problem

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#4276]
Enter this site: http://www.fullhdfilmizledim.org/lion-izle-2017-full-hd-tek-part.html (Site with enabled AD is clean like in this pic: http://s24.postimg.org/5p02lqhx1/screenshot_254.png)
But.. Now disable AD and after again enable AD. (You will see these ads: http://s24.postimg.org/oreuux3jp/screenshot_253.png) 

What causes this problem?

**Comment by Alex-302** [comment]
I can't reproduce it. Try to refresh after few seconds.

**Comment by thislife81** [comment]
I tried to refresh 2-3 times. and again shown banners. 
Blocked ads:23 With enabled AD
Blocked ads:17 (Disabling and after enabling AD)

**Comment by Alex-302** [comment]
It is not filters issue. Ask in the other repository(Windows or browser extension)
