### ISSUE TITLE
Yandex ads

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4277]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](
![s70203-123020](https://cloud.githubusercontent.com/assets/17320558/22589412/e625bb6c-ea12-11e6-878e-8a095f57dfe7.jpg)
![s70203-123125](https://cloud.githubusercontent.com/assets/17320558/22589414/e7fdcd44-ea12-11e6-9c5d-cfbbcf399d28.jpg)
)
</details>
при экономном режиме просачивается реклама. 
* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS / Android / Linux
Browser: | Yandex
Adguard version: | 2.8.76
Adguard driver (Windows): | WFP / TDI
Adguard mode (Android): | VPN / Proxy(manual/auto)
Filtering quality (Android): | High-quality 
Simplified filters(iOS) | On / Off
Adguard DNS: | None / Default / Family Protection
Stealth mode options(Windows) | 
Adguard filters: | 2, 3, 4, 14, 1, 11, 15, 211 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists):
1150428

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
В Адгарде нет экономного режима. Может упрощённый(блокируются только рекламные запросы, без сокрытия элементов) или быстрый?

**Comment by evgeniy-ADG** [comment]
Тут речь об это https://blog.adguard.com/ru/dns-filtratsiia-v-adguard-dlia-android/
Я так понимаю, оно просто не отфильтурется по DNS?

**Comment by Alex-302** [comment]
Баннер с их приложением отключается JS-ным правилом. У меня чисто.
По первому скрину - не известен адрес.
