### ISSUE TITLE
missing ad marktforschung.de

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4278]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | IOS
Browser: | Safari
Adguard version: |1.1.5.65 
Adguard driver (Windows): | WFP / TDI
Adguard mode (Android): | VPN / Proxy(manual/auto)
Filtering quality (Android): | High-quality / high-speed / simplified
HTTPS filtering (Android): |  On (Default/Blacklist mode) / Off
Simplified filters(iOS) | 
Adguard DNS: | None 
Stealth mode options(Windows) | 
Adguard filters: 
| ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.8.33 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.61 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.9 Enabled=YES
ID=6 Name="German filter" Version=1.0.30.99 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.35 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(1498773
![screen shot 2017-02-03 at 2 35 44 pm](https://cloud.githubusercontent.com/assets/17320558/22591609/1fbb359a-ea1e-11e6-8bef-8a2fe82e8823.png)
): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
