### ISSUE TITLE
Spyware Domains Used By Schools (goguardian.com)

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdguardFilters#42797]
I've recently found my school using something called GoGuardian to spy on us (the students) when we leave school, it'd be nice to have these addresses added to your DNS filter so I can block them. 

Note: This program is being used as spyware instead of making sure we (again, the students) aren't doing anything bad. It's being used to see our screens when they already have other programs in place to let them see what websites we visit and who visited them (by email). Even worse is that it sends so much info from the computers so constantly that it slows them down and makes everything really slow. 

beacon-fullpage-predictor.goguardian.com
x3-policy-maker.goguardian.com
countvoncount.goguardian.com
sockjs-goguardian.pusher.com
sock*-goguardian.pusher.com
x3-predictor.goguardian.com
screenshots.goguardian.com
ws-goguardian.pusher.com
inquisition.goguardian.com
quiddity.goguardian.com
panther.goguardian.com
sakura.goguardian.com
snat.goguardian.com
ext.goguardian.com
ip.goguardian.com

**Comment by Alex-302** [comment]
ok
