### ISSUE TITLE
english-polyglot.com - Anti-Adblock

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4279]
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-02-03 at 5 32 28 pm](https://cloud.githubusercontent.com/assets/22892774/22597260/901a06fe-ea37-11e6-886a-619aea80d2aa.png)
)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome, Safari
Adguard version: | 1.4.0
Adguard filters: | 1,2,3,4,5,11,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1022420

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
