### ISSUE TITLE
market.yandex.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#42808]
**1**. Верхний баннер: `market.yandex.ru##.main > noindex`

<details><summary>Screenshot:</summary>

![2019 04 09-1](https://user-images.githubusercontent.com/17948007/55778395-82b02480-5aab-11e9-9049-ee654c266953.png)
</details>

___________________________________________________

 **2**. Считаю недопустимым блок "Полезные статьи" в СЕРЕДИНЕ списка искомых товаров. Допускаю его расположение внизу, под списком товаров или в нижней части правой колонки, но не так, как сейчас. Поэтому: `market.yandex.*##.n-entrypoint-carousel`

<details><summary>Screenshot:</summary>

![2019 09 26-1](https://user-images.githubusercontent.com/17948007/65648750-3c746080-e00c-11e9-9a07-17cea53a766e.png)
</details>

[https://market.yandex.ru/catalog--krovati/56300/list?cvredirect=3&glfilter=11927635%3A1&glfilter=12442817%3A160~165&glfilter=15783290%3A15783300&onstock=1&local-offers-first=1&priceto=25000&viewtype=list&how=aprice](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fmarket.yandex.ru%2Fcatalog--krovati%2F56300%2Flist%3Fcvredirect%3D3%26glfilter%3D11927635%253A1%26glfilter%3D12442817%253A160%7E165%26glfilter%3D15783290%253A15783300%26onstock%3D1%26local-offers-first%3D1%26priceto%3D25000%26viewtype%3Dlist%26how%3Daprice)

___________________________________________________

 **3**. Правило `||mc.yandex.ru/metrika$third-party,domain=~mp3poisk.ru` из 'Фильтра счётчиков и систем аналитики' не блокирует `https://mc.yandex.ru/metrika/watch.js` на сайте Яндекс.Маркета. Я же его у себя блокировал сначала этим правилом `||mc.yandex.*/metrika/watch.js$domain=market.yandex.ru` , а затем решил попробовать так `||mc.yandex.*/metrika/watch.js` и пока не замечал негативных моментов (по крайней мере связанных с Яндекс.Маркетом).

 Если у Вас нет негативного опыта блокировки `https://mc.yandex.ru/metrika/watch.js` , то может стоит его заблокировать для Я.Маркета, или для всех: `||mc.yandex.*/metrika/watch.js` ?

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.3.1
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
Метрика блокируется
![image](https://user-images.githubusercontent.com/8361299/67515724-eac10380-f6a7-11e9-8822-5c0ec44605a2.png)

**Comment by XX-J** [comment]
<details><summary>НЕ Блокируется:</summary>

![2019 10 25-1](https://user-images.githubusercontent.com/17948007/67531510-aa737c80-f6cb-11e9-82f1-506c2d9ec3f7.png)
</details>

 И что с первыми двумя пунктами ?

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/67594515-2d98df00-f76d-11e9-9d75-53bb271a6162.png)

напиши в репозиторий расширения. Это не фильтропроблема.


> И что с первыми двумя пунктами ?

то же, что и с аналогичными.

**Comment by XX-J** [comment]
> напиши в репозиторий расширения. Это не фильтропроблема.

 У Вас национальность домена Yandex скорее всего другая, поэтому AdGuard считает его `third-party` - поэтому и блокирует. Но если перейти в Ru сегмент сайта Яндекс, то Ваше правило перестаёт работать.
__________

>> И что с первыми двумя пунктами ?

> то же, что и с аналогичными.

 Поясните, пожалуйста, более развёрнуто, а то не совсем понятно.
__________

 Появилась новая плашка - Предложение скачать приложение.

<details><summary>Screenshot:</summary>

![2019 12 24-1](https://user-images.githubusercontent.com/17948007/71415383-7b966a00-266c-11ea-88ad-bce3e8c01c98.png)
</details>

[https://market.yandex.ru/catalog--krovati/56300/list?cvredirect=3&glfilter=11927635%3A1&glfilter=12442817%3A160~165&glfilter=15783290%3A15783300&onstock=1&local-offers-first=1&priceto=25000&viewtype=list&how=aprice](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fmarket.yandex.ru%2Fcatalog--krovati%2F56300%2Flist%3Fcvredirect%3D3%26glfilter%3D11927635%253A1%26glfilter%3D12442817%253A160%7E165%26glfilter%3D15783290%253A15783300%26onstock%3D1%26local-offers-first%3D1%26priceto%3D25000%26viewtype%3Dlist%26how%3Daprice)

`market.yandex.*##.n-app-sms`

 И Всё вместе: `market.yandex.*##.main > noindex, .n-app-sms, .n-entrypoint-carousel`

**Comment by XX-J** [comment]
Промо в начале списка товаров.

<details><summary>Screenshot:</summary>

![2020 07 04-2](https://user-images.githubusercontent.com/17948007/86500680-73498500-bd9b-11ea-816d-03173d631c58.png)
</details>

`market.yandex.*##[data-apiary-widget-name="@MarketNode/VendorProductLinePromo"]`

[https://market.yandex.ru/catalog--vneshnie-zhestkie-diski-i-ssd/83823/list?hid=16309374&glfilter=16884012%3A16884132%2C16884129%2C16884124%2C16884117%2C16884133%2C16884119&local-offers-first=1&how=aprice](https://href.li/?https://market.yandex.ru/catalog--vneshnie-zhestkie-diski-i-ssd/83823/list?hid=16309374&glfilter=16884012%3A16884132%2C16884129%2C16884124%2C16884117%2C16884133%2C16884119&local-offers-first=1&how=aprice)

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.4.31
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики
