### ISSUE TITLE
ru.investing.com - Adguard blocks wrong element

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4281]
***Description***:
* **Current behaviour**: 

Full-screen button doesn't work when ADG is enabled

[//]: # (Опишите проблему)

Screenshot:

<details>

![screen shot 2017-02-03 at 7 30 53 pm](https://cloud.githubusercontent.com/assets/22892774/22601381/4cea7692-ea47-11e6-80cc-35bcd6a95e12.png)

</details>

* **Expected behaviour**: 

When you click on this button the graph should appear (like on my screenshot)

Screenshot:
<details>

![screen shot 2017-02-03 at 7 31 35 pm](https://cloud.githubusercontent.com/assets/22892774/22601404/6500265a-ea47-11e6-9410-3140d6e69a48.png)
)

</details>

***Link***: https://ru.investing.com/commodities/brent-oil-streaming-chart

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Firefox
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Adguard filters: | 1,2,3,4,10

Ticket ID: 1497753

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
