### ISSUE TITLE
levato.de - unable to Login

### ISSUE THREAD

**Issue by oprotsyk** [AdguardTeam/AdguardFilters#4282]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***User is not able to Login with Adg enabled***:
* **Browser attempts to open a file instaed of a web page after entering Login details and clicking Login**

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

http://imgur.com/a/vvFrJ

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

The web page should open after clicking Login. As there is no possibility to get Login details and check it by ourselves, please, inform us if it's possible to create a rule for this issue.

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Go to levato.de/Login, enter Login details, click Login

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10
Browser | Chrome, FireFox, Internet Explorer

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

1141981

**Comment by Alex-302** [comment]
Try current beta version.
