### ISSUE TITLE
http://www.nn.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4283]
http://www.nn.ru/

>AdGuard скрыл на странице элемент интерфейса абсолютно не относящийся к рекламе. Это происходит при активной опции "Фильтр виджетов социальных сетей". Пользовательские фильтры блокировки я не использую. Блокируется элемент страницы <span class="gallery-sprite moveWAll-ico" title="Тащите фото, чтобы изменить порядок"></span> - это кнопка изменения порядка пользовательских изображений.

Adg включен

![adguard_](https://cloud.githubusercontent.com/assets/15856304/22616348/22804c02-eab4-11e6-9dac-0c2982cbbd5e.jpg)

---
Adg выключен

![adguard_](https://cloud.githubusercontent.com/assets/15856304/22616349/28e28f42-eab4-11e6-8d34-0034b6de343e.jpg)

</details>

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1498797

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
а прямая ссылка где? Не вижу где повторить можно.
