### ISSUE TITLE
https://www.olx.kz/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4284]
https://www.olx.kz/ - cannot navigate through categories 

***Steps to reproduce the problem***:

1. Go to https://www.olx.kz/
2. Select a location
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22616969/e8832494-eac1-11e6-83d8-3c5ef0f5d277.png)

</details>
3. Select 'Electronics'
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22616973/fe5576aa-eac1-11e6-88f4-5371edd14d26.png)

</details>
4. Try to select any sub-category and you'll see that it does not select

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22616980/2133ef76-eac2-11e6-9fd8-e4329b2411ca.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome 56
Adguard version: | 1.4
Adguard DNS: | None 
Adguard filters: | eng, spy, social, mobile, russian, annoyances, liste-kr

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1355336

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в фильтр аналитики
```
@@||ninja.onap.io/ninja-*.js$domain=olx.kz
```
