### ISSUE TITLE
http://putlockers.ch/ - pop-up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4287]
http://putlockers.ch/watch-family-guy-tvshow-season-3-episode-5-online-free-putlocker.html

***Steps to reproduce the problem***:

1. Go to the page
2. Click on an episode in the list below the player
3. It'll open an extra page which will be blocked by the content blocker

<details>

![file_000 2](https://cloud.githubusercontent.com/assets/15856304/22618413/1c8142cc-eae4-11e6-90ef-32195ffbbf63.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | None 
Adguard filters: | 2 3 4 11 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1453264

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
They are using inline JS. We can't remove it on iOS. But this issue is not reproduced on my device.
