### ISSUE TITLE
missed ads kirovnet.ru

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4288]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
missed ads here  kirovnet.ru

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

(http://cloud.githubusercontent.com/assets/17320558/22618788/9ae04136-eaee-11e6-81fe-cc6be019975e.png)
(https://cloud.githubusercontent.com/assets/17320558/22618789/9cc74e68-eaee-11e6-9d9d-29bcac4bdacf.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS, Android 
Browser: | Chrome, Mozilla, Yandex
Adguard version: | 1.4.0
Adguard driver (Windows): | WFP 
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default)
Adguard filters: | User, English, Spyware, Social media, Annoyances, Russian

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1499308

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
