### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by hassanseoul123** [AdguardTeam/AdguardFilters#42897]
whenever I enable adguard, I can't login to any website on chrome. for example xda, facebook and twitter; however, loggimg in through apps is working.

**Comment by krystian3w** [comment]
Chrome version,
AdGuard addon / app version,
System used on PC / smartphone?

**Comment by hassanseoul123** [comment]
Device = Oppo F11
OS = ColorOs 6, Android Pie
Chrome Android Version = 78.0.3904.62
Adguard v3.3 Beta 1 (64)

**Comment by hassanseoul123** [comment]
I figured out that this issue occurs because cookies are disabled when I enable adguard.

**Comment by Alex-302** [comment]
@hassanseoul123 please send report using AdGuard.
