### ISSUE TITLE
www.marca.com - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4290]
http://www.marca.com/futbol/primera-division/2017/02/04/5895d3d446163f6f128b461b.html

![image](https://cloud.githubusercontent.com/assets/15856304/22618946/4bab75fa-eaf2-11e6-8c5f-4134db1c494d.png)

***Steps to reproduce the problem***:

1. Open a site 
2.  Browser it and wait for a minute or two
3. See a pop-up asking to disable ad blocker

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome 
Adguard version: | 1.4
Adguard DNS: | None
Adguard filters: | 2 14 211 223

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1320105

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. Try to enable
```
Spanish/Portuguese filter
```
