### ISSUE TITLE
missed ads watchcartoononline

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4292]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Саму рекламу убирает, но остается фон и кнопка для закрытия. Остается и после активации фильтра раздражителей.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/14153331/22619835/c7c529f2-eb05-11e6-8fc8-8a2fa613cedb.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |Android
Browser: | Chrome
Adguard version: | 2.8.76
Adguard driver (Windows): | WFP 
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard filters: English, Social media, annoyances, Russian, Spyware, mobile ads filters

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1499312

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Уже исправлял. Нужно проверить обновление фильтров.
