### ISSUE TITLE
Flume application ads

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4293]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

![image](https://cloud.githubusercontent.com/assets/17320558/22620197/058b4a74-eb0f-11e6-8700-eabf3204790b.png)

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)
Instal Flume -> use Instagram client
https://itunes.apple.com/app/id792425898
***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Adguard version: | 1.4.0
Adguard filters: | Eng, User, Spyware, Social media, Russian, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1104286

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня оно не работает. Крутится значек авторизации и всё. Это без Адгарда.

**Comment by Alex-302** [comment]
Могу удалённо глянуть, если пустят)

**Comment by staniki** [comment]
По моей просьбе создали тикет, могу пустить посмотреть :)

**Comment by Alex-302** [comment]
@staniki Хорошо. Напишите завтра сюда, когда будете готовы, договоримся как ID и пароль передать.

**Comment by staniki** [comment]
@Alex-302 привет, ну что, так и не получилось зайти? Как могу могу передать доступы?

**Comment by Alex-302** [comment]
@staniki Не грузится у меня. Глянуть можно завтра в течение дня. Мой скайп alxbrv

**Comment by staniki** [comment]
@Alex-302 привет, вышла новая версия, с app store удалена, попробуй новую версию, должна заработать :)
https://flumeapp.com/download/

**Comment by Alex-302** [comment]
Не запускается. Ошибка.

**Comment by staniki** [comment]
@Alex-302 2.6.1 версия?

**Comment by Alex-302** [comment]
Не знаю. Та, которая по ссылке загружается.

**Comment by staniki** [comment]
@Alex-302 они только сегодня новую версию выпустили.
FIXED: A launch crash due to Instagram switching off their previous real-time messaging servers.

У меня тоже вчера крэшанулась, сегодня обновил и пока работает.

**Comment by evgeniy-ADG** [comment]
@Alex-302 просят, чтобы ты еще раз посомтрел. говорят, там краши пофиксились и мы теперь можем туда логиниться тоже.

**Comment by Alex-302** [comment]
Установил, рекламы не вижу. Нужно описание как и где её искать.

**Comment by staniki** [comment]
@Alex-302 попробуй подписаться на популярные аккаунты, у меня реклама через один пост :(
<img width="321" alt="2017-08-07 8 15 44" src="https://user-images.githubusercontent.com/16809036/29013031-afc34216-7b48-11e7-98c7-a1c505e16e85.png">

**Comment by Alex-302** [comment]
Опиши как там подписаться и дай названия групп.

**Comment by staniki** [comment]
нажимаешь ⌘4 и вписываешь название группы, далее тыкаешь по иконке, открывается страница группы, нажимаешь на плюсик

Либо можно залогиниться в веб версии, зайти на страницу группы (пример https://www.instagram.com/dotmod) и там уже подписаться.

Реклама должна появиться.

вот мой список
fantasieliquid
themilkmaneliquid
vapebreakfastclassics
baddrip
thecustardshoppe
coilmasteruk
vapemadhatter
jammonsterliquids
dotmod

Мой регион Россия, Москва.

**Comment by Alex-302** [comment]
Подписался. Рекламы пока нет.
Напомни через пару дней, может появится.

**Comment by Alex-302** [comment]
Чисто. Рекламу мне не показывают.
Если есть комп с Windows, то могу через TeamViewer подключиться, захватить трафик и посмотреть что там.

**Comment by staniki** [comment]
Да, есть паралелька с видной

**Comment by Alex-302** [comment]
Наверное.
В винде установите Fiddler, сделайте эту настройку http://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/UseFiddlerAsReverseProxy , определите IP винды и попробуйте открыть IP:8888
Если откроется, то завтра смогу подключиться к винде и глянуть.
