### ISSUE TITLE
http://rutorgames.org - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4295]
На сайте есть реклама, если заходить на него с мобильного. Баннер с рекламой казино в верхней части экрана:

<details>

![fo0doabsfoy](https://cloud.githubusercontent.com/assets/15856304/22625642/4278f2f6-eba5-11e6-8341-8fa3df8a84e7.jpg)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Chrome
Adguard version: | 2.8
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On Default
Adguard DNS: | Default 
Adguard filters: | rus, eng, social media, annoyances, mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1143570

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
