### ISSUE TITLE
http://www.world-art.ru/ - ads, ad leftovers

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4296]
1) Placeholder:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22625756/9a362044-eba6-11e6-8c84-fac0e500ee55.png)

</details>

2. When you click it, it redirects top another page:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22625768/c1b73f5e-eba6-11e6-934a-a5d71eba645d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4 beta
Adguard filters: | russian, english, social media, annoyances, spyware, safari, mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1412565

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed

**Comment by Yana-SUP** [comment]
ads are still here
user's video 
https://drive.google.com/file/d/0B3bqlWlU2aZyVGNYaUxVWUhrZzg/view?usp=drive_web

reproducible on Mac and Windows with Incognito mode

please check this link for example
http://www.world-art.ru/cinema/cinema_trailers.php?id=8475&trailer_id=9007

**Comment by Alex-302** [comment]
Looks like a bug
https://github.com/AdguardTeam/AdguardForWindows/issues/1222#issuecomment-278366833
