### ISSUE TITLE
http://www.dobreyshey.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4297]
Adguard blocks the flash player on http://www.dobreyshey.com/ it won't start unless you disable the filtering.

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22626060/504e89d8-ebad-11e6-9a41-6e210a690a1f.png)

</details>
***System configuration***

Information | value
--- | ---
Operating system: | Mac OS X
Browser: | Chrome
Adguard version: | 1.4 beta
Adguard filters: | 2 3 4 1 5 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1436179

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by vvgnovanet** [comment]
Алекс, здарова !!!
 Я написал какое правило поправить
/fingerprint2.min.js^  - фильтр счётчиков и аналитики

в пользовательском у меня такое правило
@@/fingerprint2.min.js^$domain=livacha.com

**Comment by Alex-302** [comment]
Привет, добавил.
