### ISSUE TITLE
http://nn.by/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4298]
The page loads blank

![image](https://cloud.githubusercontent.com/assets/15856304/22626473/bae26ba8-ebb6-11e6-9df7-84d2e5138f4a.png)

Adblock Polskie reguły seems to be causing it.

***System configuration***

Information | value
--- | ---
Operating system: | Mac
Browser: | Chrome 
Adguard version: | the current one
Adguard filters: | Russian, Polskie Reguly, Spanish, Deutch, English

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1498653

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Reported: https://github.com/MajkiIT/polish-ads-filter/issues/2125
