### ISSUE TITLE
http://www.angrybirdsnest.com - anti-adblock script

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4299]
The site detects English filter, works fine without it.
The link: http://www.angrybirdsnest.com/angry-birds-evolution-part-3-fire-rooster-vs-pyromaniac/

![image](https://cloud.githubusercontent.com/assets/15856304/22626513/cf356f8c-ebb7-11e6-9bbc-000c5c651d03.png)

Without English filter:

![image](https://cloud.githubusercontent.com/assets/15856304/22626516/e04c377e-ebb7-11e6-898e-a87e8ccb38d2.png)

**Comment by Alex-302** [comment]
fixed
