### ISSUE TITLE
Cannot update time in windows using ntp servers

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4300]
Cannot update time in windows using ntp servers. It returns the error each time unless you disable the filtering.
I am not sure if it's the filtering issue but I was able to reproduce it. When you update the time and then enable Adguard back, you might not see the error again.

STR:

1. Go to Settings and search for Time
2. Open Date & Time > Additional Date & Time, Regional settings
3. Hit Set time and date > Internet time tab
4. Chane settings > Update now.
5. Error.

With Adguard

![1211212](https://cloud.githubusercontent.com/assets/15856304/22627999/cdc3e706-ebd4-11e6-801e-81feeda088c5.png)

Without Adguard

![ttrtrr](https://cloud.githubusercontent.com/assets/15856304/22628005/d7f820b6-ebd4-11e6-8891-e270a81e6919.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 (the user has  NT 6.1.7601 Service Pack 1)
Adguard version: | 6.1.309.1615
Adguard driver (Windows): | WFP (TDI on the user's side)
Adguard DNS: | None
Stealth mode options(Windows) | On, default
Adguard filters: | 1 2 3 4

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1454419

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не уверен, что это Адгард так влияет. У меня первая попытка неудачна, вторая и все последующие удачны.
@vozersky проверь, как у тебя работает.

**Comment by vozersky** [comment]
Не повторяется, все попытки успешны

**Comment by Alex-302** [comment]
@evgeniy-ADG есть какая-нибудь система у этого явления?

**Comment by evgeniy-ADG** [comment]
Только что повторилось на соседнем компьютере. Схема та же, что я описал. Вот скрины.

<details>

1. С нами
![fail 1](https://cloud.githubusercontent.com/assets/15856304/22732428/cb44ecae-edf6-11e6-9259-12774432d493.jpg)

2. Без нас
![fail 2](https://cloud.githubusercontent.com/assets/15856304/22732432/cf672f5e-edf6-11e6-8f45-45c2d29710bc.jpg)

</details>

После вкл/выкл Adguard - следующие обновления происходит корректно.

**Comment by Alex-302** [comment]
В журнале при проверке времени пусто. Если ломаем как-то, то не фильтрами.
У тебя при включенном Адгарде вообще обновить не даёт, или вторая-третья попытки удачны?

**Comment by evgeniy-ADG** [comment]
Обновляется только после постановки нас на паузу. После обновления и включения нас снова - ошибка не повторяется. Как-то так.

**Comment by Alex-302** [comment]
Похоже на баг какой-то. Без фильтров так же? Если да, то включи детальное логирование через меню в трее, сделай несколько попыток с указанием времени(желательно с секундами, не обязательно совсем точно) и продублируй в виндовом репозитории.

**Comment by evgeniy-ADG** [comment]
1616631 - тут логи, которые просили, и "Нет отключение всех фильтров не помогает решить проблему". Куда это переносить и что делать?

**Comment by Alex-302** [comment]
Это скорее всего в виндовый раздел. Но у меня никогда это не повторялось.
