### ISSUE TITLE
ural56.ru - missed ad 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4301]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description**: ads on ural56.ru/news/63/549915/c 

Screenshot:
http://prnt.sc/e4yocf
[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***
Application version: 1.1.5.40
Device: iPad
OS: 10.3
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.96.32 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.10.45 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.88 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.9.39 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95 Enabled=NO
ID=1 Name="Russian filter" Version=1.0.46.8 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.49 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.86 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.24 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.73 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.73.62 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.23 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.73.63 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.73.51 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.70.38 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.70.17 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.68 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1137674

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
ural56.ru##.beono-banner_slider
||ural56.ru/upload/rk/
```
Баннер приложения на iOS не убрать, останется дырка. Нижнего блока нет.
