### ISSUE TITLE
youtube.com annoyance

### ISSUE THREAD

**Issue by hazarek** [AdguardTeam/AdguardFilters#43018]
Notice the icon in the upper right corner;

<img width="762" alt="Ekran Resmi 2019-10-26 16 30 59" src="https://user-images.githubusercontent.com/36481442/67620381-df3c1c80-f80e-11e9-8be7-a56ebbbc3f15.png">

This rule should be added in youtube annoyance rules to block `(i)` icon.
```
youtube.com##.ytp-cards-button
```

**Comment by Alex-302** [comment]
this icon will disappear after two seconds with navigation panel
