### ISSUE TITLE
https://mail.yandex.ua - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4302]
![image](https://cloud.githubusercontent.com/assets/15856304/22638311/fe4d9c52-ec4f-11e6-8f55-ba02569d626d.png)

English filterVersion 1.1.8.57. Updated 5 february 2017 at 22:00.
Russian filterVersion 1.0.46.51. Updated 3 february 2017 at 21:00.
Dutch filterVersion 1.0.9.17. Updated 2 february 2017 at 16:52.
Spanish/Portuguese filterVersion 1.0.86.54. Updated 2 february 2017 at 16:52.
Liste FRVersion 1.0.74.27. Updated 6 february 2017 at 07:32.

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Yanedx browser
Adguard version: | 2.5.11 extension
Adguard filters: | listed above

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
не повторилось. А у тебя?

**Comment by evgeniy-ADG** [comment]
Мой скрин. Да, но как-то странно все, вот смотри

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/22692230/b408910e-ed46-11e6-9749-09ead59c6279.png)

![image](https://cloud.githubusercontent.com/assets/15856304/22692237/bebd0440-ed46-11e6-9dca-4e8d0b9f9c65.png)

**Comment by Alex-302** [comment]
Может расширение какое-то мешает? Это ЯБ?

**Comment by evgeniy-ADG** [comment]
Да, false alarm, разобрались. Непонятно откуда там взялся еще один контент-блокер, которого не было видно в панели.
