### ISSUE TITLE
Элементы Яндекс: Почта (версия 8.22.3)

### ISSUE THREAD

**Issue by Koruy** [AdguardTeam/AdguardFilters#43031]
![26 октября 2019 г  232044 GMT+0300](https://user-images.githubusercontent.com/53151866/67625504-af5d3b00-f847-11e9-853c-0acfa5782157.png)
Не могу посмотреть почту яндекс через расширение браузера. Вы мне посоветовали ввести адрес страницы на которой расширение ломается, но дело в том что это начальная страница браузера. В трее браузера иконка расширения Элементы Яндекс: Почта (версия 8.22.3). При открытии расширения открывается маленькое дополнительное окошко, в котором видны входящие письма, но этого не происходит в окошке пишет ошибка. Если открыть яндекс почту через сайт - страница почты открывается. Опытным путём было выявлено, что расширение ломает фильтр RU AdList: Counters. Куда ещё написать и сколько обращений ещё нужно что бы решить проблему?
Версия ОС Windows xp, версия браузера Opera 36, расширение браузера: Элементы Яндекса: Почта 
Версия 8.22.3
I can not see Yandex mail through a browser extension. You advised me to enter the address of the page on which the extension breaks, but the fact is that this is the start page of the browser. In the browser tray, the extension icon is Yandex Elements: Mail (version 8.22.3). When you open the extension, a small additional window opens in which incoming messages are visible, but this does not happen; an error is written in the window. If you open Yandex mail through the site, the mail page opens. Empirically, it was revealed that the extension breaks the RU AdList: Counters filter. Where else to write and how many calls still need to solve the problem?
Windows OS version xp, Opera 36 browser version, browser extension: Yandex Elements: Mail
Version 8.22.3

**Comment by Alex-302** [comment]
Поправлю с нашей стороны.

**Comment by Buldozer095** [comment]
Как скачать?
