### ISSUE TITLE
ibit.to

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#43032]
[https://ibit.to/torrent/Entirety-of-Wikipedia-in-English-with-pictures-40GB--e7a9ed/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://ibit.to/torrent/Entirety-of-Wikipedia-in-English-with-pictures-40GB--e7a9ed/)

![ibit](https://user-images.githubusercontent.com/35470489/67625583-7bb5ed00-f816-11e9-8c86-9b41357827a2.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by AdamWr** [comment]
Fixed popups and these "green" ads, but I couldn't reproduce ad at the bottom.
