### ISSUE TITLE
https://www.bkr.nl/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4303]
We're blocking too much, please see the screenshots:

1. With Adguard

![image](https://cloud.githubusercontent.com/assets/15856304/22642403/33d49f70-ec63-11e6-89a1-429e25cfb7f4.png)

2. Without Adguard:

![image](https://cloud.githubusercontent.com/assets/15856304/22642422/44ec6838-ec63-11e6-8072-141cb81b77c5.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows NT 10.0.14393.0
Browser: | Chrome
Adguard version: | 6.1.309.1615
Adguard driver (Windows): | WFP 
Adguard DNS: | None 
Stealth mode options(Windows) | On
Adguard filters: | 2 3 4 10 6 8 104

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1499320

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
This happens even if I disable filtering. I have to disable Adguard service in order to see the image. If the issue is consistently reproduced, it should be reported to AG for Windows issue tracker.

**Comment by Alex-302** [comment]
I have the same issue without AG service and extension.

**Comment by evgeniy-ADG** [comment]
It was reproduced on Mac as well, not just on Windows.

**Comment by Alex-302** [comment]
I think it is not Adguard issue.
