### ISSUE TITLE
beta.gismeteo.ru

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4306]
https://beta.gismeteo.ru/weather-moscow-4368/3-days/#/wind.precipitation.pressure.humidity/
chrome
mac 1.4.0 
spyware en rus social_media annoyances 
![screenshot 2017-02-06 14 25 11](https://cloud.githubusercontent.com/assets/23637588/22646551/02abd5c4-ec7e-11e6-9790-cbbeb8fedb8a.png)
also ad leftover top of the page:

![screenshot 2017-02-06 14 27 50](https://cloud.githubusercontent.com/assets/23637588/22646730/e3441b6e-ec7e-11e6-9e8f-8e367d2ab90a.png)

**Comment by Alex-302** [comment]
Меня на главную отправляет, на beta не пускает. Что нужно, чтоб туда попасть?

**Comment by koshol** [comment]
Верхний баннер заменяется пустым прямоугольником – это можно совсем вырезать до надписи Gismeteo?
Плюс пропадает текущая погода! Она была справа от трёх дней.

**Comment by evgeniy-ADG** [comment]
Меня тоже не пускало. @zebrum

**Comment by koshol** [comment]
не обязательно идти на beta!
по адресу https://www.gismeteo.ru/weather-moscow-4368/ тоже самое, верхний баннер заменяется пустым прямоугольником. Это можно совсем вырезать до надписи Gismeteo?
Плюс пропадает текущая погода! Она справа от трёх дней.

**Comment by Alex-302** [comment]
Текущую погоду подправил, пустого блока не вижу.

**Comment by koshol** [comment]
Белый пустой кусок над сайтом Gismeteo

**Comment by Alex-302** [comment]
поправил

**Comment by koshol** [comment]
1) Опять просят отключить блокировщик рекламы)
2) Верхний баннер после вырезания оставляет 3 пустых сантиметра в топе страницы (см. в первом сообщении вторую картинку).

**Comment by Alex-302** [comment]
отступы убрал. Детект с фильтром раздражителей не повторился.

**Comment by koshol** [comment]
![7](https://cloud.githubusercontent.com/assets/25602156/23785273/f580a72c-0577-11e7-8e42-dc253d833e6a.png)
![8](https://cloud.githubusercontent.com/assets/25602156/23785272/f575d78e-0577-11e7-9e8a-d980b873265d.png)

Выделил красным!
Вернулась пустая шапка, появилась реклама Яндекс.директ
При первом открытии появляется баннер "Отключите блокер", но только при первом...

**Comment by koshol** [comment]
![10](https://cloud.githubusercontent.com/assets/25602156/23786392/d0cdd5e8-057d-11e7-8864-3f257c2fae16.png)
