### ISSUE TITLE
[Content Blocker] http://epidemz.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4307]
The content locker misses ads in Samsung browser, see the yellow leftovers above and belove articles:

<details>

![screenshot_20170203-064525](https://cloud.githubusercontent.com/assets/15856304/22679999/7f87ec6e-ed0e-11e6-9e30-b466df0e7e2b.png)
![screenshot_20170203-064513](https://cloud.githubusercontent.com/assets/15856304/22680000/804a1654-ed0e-11e6-919a-5afbd4082d8b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Samsung
Adguard version: | 1.4.3
Adguard DNS: | None 
Adguard filters: | eng, spyware, social media, annoyances, russian, mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1307214

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@evgeniy-ADG для пробы добавил в мобильный фильтр
```
epidemz.com,epidemz.co##div[id^="cpa_rotator_block_"]
```
после обновления нужно будет проверить. Только не через месяц)

**Comment by evgeniy-ADG** [comment]
Все ок, помогло.

**Comment by oprotsyk** [comment]
The issue repeats again, in Yandex browser too.
Adguard application removes those yellow blocks.

**Comment by oprotsyk** [comment]
![image](https://cloud.githubusercontent.com/assets/25342327/22749822/50ead8ec-ee37-11e6-81f1-d0cedb56bc77.png)

in Yandex

**Comment by Alex-302** [comment]
I can't hide it. Asked in Content Blocker repository
https://github.com/AdguardTeam/ContentBlocker/issues/51

**Comment by evgeniy-ADG** [comment]
Что с этим таском? Баг в контент блокере?

**Comment by Alex-302** [comment]
Похоже.

**Comment by Alex-302** [comment]
В смысле, который в самом браузере.
