### ISSUE TITLE
Viber for iOS - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4308]
![image](https://cloud.githubusercontent.com/assets/15856304/22680497/f70438ea-ed10-11e6-944a-9cbe90b14c49.png)

***Steps to reproduce the problem***:

1. Start a call
2. Finish a call
3. See a banner

It does not occur every time so you may need to try a couple of times until you see it
DNS requests log: **1428890**

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Adguard version: | 1.1.5.40
Simplified filters(iOS) | Off
Adguard DNS: |  Default 
Adguard filters: | 2 3 4 14 10 1 5 11 12 15 101 115 213 212

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1428890

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
DNS лог здесь не поможет, и на счёт блокировки домена тоже сомневаюсь. Можно удалённо попробовать, настроив Viber через Fiddler, установленный на компе.
