### ISSUE TITLE
http://www.igen.fr/ - incorrect blcoking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4309]
http://www.igen.fr/#left-menu

![img_3401](https://cloud.githubusercontent.com/assets/15856304/22681579/a593080a-ed16-11e6-97a4-33614d61db56.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | None 
Adguard filters: | 2 3 4 11 12 14 113

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1498668

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. Which wilter causes it?

**Comment by evgeniy-ADG** [comment]
I don't know, will ask someome with the iPhone to check.

**Comment by davidXire** [comment]
Filter named "Liste Fr" causes it

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||igen.fr/sites/www.igen.fr/files/advagg_js/
```
please check in user filter or/and after filters update.

**Comment by davidXire** [comment]
It's work !
