### ISSUE TITLE
https://www.stormo.tv/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4310]
https://www.stormo.tv/videos/103202/mila-kunis-zashchitila-djastina-timberleyka-po-russki/

![image](https://cloud.githubusercontent.com/assets/15856304/22681868/44d1b154-ed18-11e6-8848-c45d22b0fa44.png)

The same on Android:

<details>

With:

![image](https://cloud.githubusercontent.com/assets/15856304/22682119/b5674928-ed19-11e6-97c8-2dbdb279326a.png)

Without:

![image](https://cloud.githubusercontent.com/assets/15856304/22682132/c419e796-ed19-11e6-9c55-9ec872e74a8a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Chrome
Adguard version: | 2.8
A
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality / 
HTTPS filtering (Android): |  On Default
Adguard DNS: | Default 
Adguard filters: | Eng, Rus, Spy, Social Media, Mobile ads, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1500333

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
