### ISSUE TITLE
WomanLog app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4311]
The WomanLog app for iOS: https://itunes.apple.com/us/app/womanlog-calendar/id421360650?mt=8

![image1 2](https://cloud.githubusercontent.com/assets/15856304/22682786/6c9f416a-ed1d-11e6-8697-ba9eba231837.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.3
Browser: | Safari
Adguard version: | 1.1.5.40
Simplified filters(iOS) | Off
Adguard DNS: |  Default
Adguard filters: | 2 3 4 5 1 11 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1428019

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Метка не правильная.
На iOS у меня чисто.
Судя по логу, реклама FB. На iOS можно заблокировать только пожертвовав самим FB. Если юзер не пользуется фейсбуком, то можно добавить:
```
||graph.facebook.com^
```
