### ISSUE TITLE
http://southpark.cc.com/, http://southpark.cc.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4312]
The link: http://southpark.cc.com/full-episodes/s20e07-oh-jeez#source=2b6c5ab4-d717-4e84-9143-918793a3b636:63a32034-1ea6-492d-b95b-9433e3f62f8d&position=2&sort=airdate

http://southpark.cc.com/full-episodes/s20e07-oh-jeez#source=2b6c5ab4-d717-4e84-9143-918793a3b636:63a32034-1ea6-492d-b95b-9433e3f62f8d&position=2&sort=airdate

![image](https://cloud.githubusercontent.com/assets/15856304/22683398/7267c434-ed20-11e6-92ad-f76a4924f14b.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4 beta,  1.4
Adguard DNS: | None 
Adguard filters: | Eng, Russian, Social, Spyware, Annoyances, Dutch, German, Safari, Mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1498888

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed

**Comment by Alex-302** [comment]
@evgeniy-ADG с копипастой внимательнее будь. Там в тикете несколько доменов. Пусть проверит, т.к. исправление заключается в удалении правила.
