### ISSUE TITLE
http://www.tvdigital.de/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4313]
http://www.tvdigital.de/

Screenshots:

<details>

![image1 3](https://cloud.githubusercontent.com/assets/15856304/22683516/eacbbde0-ed20-11e6-9b5a-8ee48b5d4ec9.png)

![image2 1](https://cloud.githubusercontent.com/assets/15856304/22683517/ec04b450-ed20-11e6-8ebb-29b996ecb756.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | 2 3 4 6 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1498773

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced with German filter.

**Comment by evgeniy-ADG** [comment]
Seems to work fine with simplified filters.
