### ISSUE TITLE
Missed ad wdzj.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#43144]
@MHzsz commented on [Tue Oct 29 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3052)

### AdGuard Product:
AdGuard for Windows version 7.2.2936.0

### Problem URL:
https://www.wdzj.com/hjzs/ptsj/20181101/868307-1.html

### Problem Type:
Missed ad (unblocked ads, ad leftovers etc.)

### Filters:	
Ad Blocking:
Peter Lowe's list
Social Widgets:
Fanboy's Social Blocking List
Annoyances:
AdGuard Annoyances filter
Security:
Malware Domains
Other:
AdGuard Simplified domain names filter
Language-specific:
EasyList China
AdGuard Dutch filter

### Actual behavior

<details><summary>Screenshot:</summary>
![2019-10-29 13 27 26 www wdzj com 867280ce7030](https://user-images.githubusercontent.com/39558996/67740940-86f55c80-fa52-11e9-86d9-acd54255f66c.png)

</details>

### Customer ID 

1711983

### Your environment

* Environment name and version: Vivaldi 2.8.1664.44
* Operating system and version: Windows 10 OS Version 1903 (Build 18362.418)

---

@MHzsz commented on [Tue Oct 29 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3052#issuecomment-547267372)

我不能使用assistant 的report 功能，所以只能这样反馈给你们。
![2019-10-29 13 48 48 reports adguard com ae94dd90875d](https://user-images.githubusercontent.com/39558996/67741049-d6d42380-fa52-11e9-8b96-dc03c2c38fce.png)

**Comment by Alex-302** [comment]
@MHzsz please check these rules.
```
! ads
wdzj.com##div[class$="-ad-top"]
wdzj.com###ggao-article-bottom
wdzj.com##.left-gg-box > div.sl-ggao > div.gg
! mobile app banner
wdzj.com##.ggao-pc_hjzs_download
```
Not sure about this
![image](https://user-images.githubusercontent.com/8361299/67764660-1f8bdc80-fa53-11e9-9bd5-9dd84f9612ee.png)
please select whole banner.

**Comment by MHzsz** [comment]
@Alex-302 
感谢回复，我重新截图了，一共5个广告。
出现新问题：assistant 的图标不能显示，设置是选择在左下角显示的。
###截图1
![2019-11-02 21 21 59 www wdzj com 5a0ccf127088](https://user-images.githubusercontent.com/39558996/68071638-28fca800-fdb7-11e9-83a1-5c4aaf97657d.png)

我尝试添加你的rules ，不确定方式是否正确。
###截图2
![批注 2019-11-02 212723](https://user-images.githubusercontent.com/39558996/68071695-da9bd900-fdb7-11e9-9d34-a0fb8ac04bea.jpg)

添加新规则之后，广告有减少，我重新截图了。
###截图3
![2019-11-02 21 27 40 www wdzj com e4e797b19c4c](https://user-images.githubusercontent.com/39558996/68071725-1171ef00-fdb8-11e9-9227-f4e736a518fb.png)

**Comment by Alex-302** [comment]
1. What is it?
![image](https://user-images.githubusercontent.com/8361299/68129612-85c8a180-ff22-11e9-96cf-8ef8dae695a6.png)
It is empty without AdGuard.

**Comment by Alex-302** [comment]
2. No. One rule - one string
![image](https://user-images.githubusercontent.com/8361299/68129704-adb80500-ff22-11e9-8436-12a12419c6ed.png)

**Comment by Alex-302** [comment]
It seems elements in rectangles are not ads, just their own stuff.

**Comment by MHzsz** [comment]
1.圆圈处原本应该显示assistant 图标。
2.我全部复制下来以后粘贴在用户过滤器里，但规则不能启用（去掉❕才可以启用）。
3.矩形标出来的广告左下角自己都带有“广告”两个字，内容也显然是广告。这种声明自己是广告的广告，adguard不负责拦截吗？

**Comment by Alex-302** [comment]
1. I don't have Assistant issue
<details><summary>Screenshot:</summary> 

![image](https://user-images.githubusercontent.com/8361299/68382027-89933880-015b-11ea-8253-965e5f02c2c7.png)

 </details>

2. Not understand what do you mean;
3. Added `wdzj.com##.ggao-everyone-rebeat`

**Comment by MHzsz** [comment]
### 添加过滤器
![批注 2019-11-08 130507](https://user-images.githubusercontent.com/39558996/68451113-739f7980-0228-11ea-9472-06ef1546d8ad.jpg)
### 添加以后的拦截状况
![2019-11-08 13 02 57 www wdzj com f6470e865879](https://user-images.githubusercontent.com/39558996/68451134-80bc6880-0228-11ea-9464-b6078f69a3bc.png)

**Comment by Alex-302** [comment]
I don't see these elements
![image](https://user-images.githubusercontent.com/8361299/68487380-a0b15380-024b-11ea-955f-9dbb69906b1b.png)
Left and top right are their own stuff.

**Comment by Alex-302** [comment]
Could you please save the page and upload it here?

**Comment by MHzsz** [comment]
[wdzj.com.zip](https://github.com/AdguardTeam/AdguardFilters/files/3845802/wdzj.com.zip)
我不懂你说的"save"是指什么操作，是这样吗？

**Comment by Alex-302** [comment]
the same 
![image](https://user-images.githubusercontent.com/8361299/68956646-32333f00-07d1-11ea-8e2c-cb03c0eabc2d.png)

**Comment by MHzsz** [comment]
好吧，如果没有AdGuard可以负责的广告，就这样吧。
感谢帮助。

**Comment by Alex-302** [comment]
Ok.
