### ISSUE TITLE
designhousestockholm.com - cookies notification

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4315]
http://designhousestockholm.com/collections/elsa-beskow/
https://designhousestockholm.com/collections/elsa-beskow/

![designhousestockholm com-http](https://cloud.githubusercontent.com/assets/15856304/22685733/21e3328c-ed2a-11e6-8d25-ba8711373137.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4
Adguard filters: | Английский фильтр, Фильтр счетчиков и системы аналитики, Фильтр виджетов социальных сетей, Фильтр раздражителей, Фильтр полезной рекламы, Русский фильтр

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
