### ISSUE TITLE
www.instantreward.site

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#43158]
@uservictor commented on [Tue Oct 29 2019](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/155)

Hello first I want to ask where is the right place to report Ad domains related to the AdGuardHome SDNS filter. (pls give me a link)

Second I want to report an advertising domain, I use AGHome with SimplifiedDNS filter and AdAway filter on my RaspberryPi.

While browsing i get an Popup with "you won... million yoogle search request...." I found this domain in the request log of AGH:

www.instantreward.site
||www.instantreward.site^$important (created block rule with AGH)

Pls keep an eye on it
Thank you

AGH v0.99.2
Device Android 8 Smartphone
Browser Opera mobile

---

@Alex-302 commented on [Tue Oct 29 2019](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/155#issuecomment-547533417)

Hi. Better report to filters repository.
https://github.com/AdguardTeam/AdguardFilters/issues
I will move this issue and block this domain.

**Comment by uservictor** [comment]
Can you add it to this filter too?
[AdGuardSDNSFilter](https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt)
btw i  am impressed how fast you guys react to issues :-)

**Comment by Alex-302** [comment]
SDNFilter compliled from files in this repository.
