### ISSUE TITLE
https://glashkoff.com/ - social widget

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4316]
https://glashkoff.com/blog/games/skidki-i-besplatnyie-klyuchi/

![image](https://cloud.githubusercontent.com/assets/15856304/22686101/85268550-ed2b-11e6-9d6e-f353777fe9a0.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Safari
Adguard version: | 1.4
Adguard DNS: | None
Adguard filters: | Rus, Eng, Social media, Spyware, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): **939612**

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
