### ISSUE TITLE
http://films.imhonet.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4317]
Adguard blocks trailers on the site, they won't play when you tap them: http://films.imhonet.ru/element/10148686/?autoplay=1#online

![image](https://cloud.githubusercontent.com/assets/15856304/22688783/7267c6f8-ed36-11e6-856a-250f6ad62760.png)

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Chrome
Adguard version: | 2.8
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On Default
Adguard DNS: | Default 
Adguard filters: | Eng Ru Social Spyware Annoyances Mobile

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1500410

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не повторяется. Список фильтров верный?

**Comment by evgeniy-ADG** [comment]
Да, верный. У меня - повтоярется до сих пор.

**Comment by Alex-302** [comment]
Добавил в мобильный фильтр
```
@@||films.imhonet.ru^$jsinject
```
нужно проверить

**Comment by evgeniy-ADG** [comment]
Работает теперь.

**Comment by Alex-302** [comment]
ок
