### ISSUE TITLE
geektime.co.il & pocketnow.com

### ISSUE THREAD

**Issue by zum348** [AdguardTeam/AdguardFilters#4318]
***Description***:
pocketnow.com & geektime.co.il pulls ads through first party iframes

Screenshot:
<details>

![image](https://secure.fanboy.co.nz/geek.il-ads.png)
</details>

* **Expected behaviour**: 
no ads should be presented

***Steps to reproduce the problem***:
just surf to pocketnow.com or geektime.co.il with chrome, you will see multiple ads.

***System configuration***
Operating system: Windows
Browser:  Chrome
Adguard version: 2.5.11
Adguard driver (Windows): Extension
Adguard filters: Hebrew & English

related issue on uBlock with screenshots:
https://github.com/uBlockOrigin/uAssets/issues/278

**Comment by Alex-302** [comment]
Please don't ignore template.

**Comment by zum348** [comment]
Done.

**Comment by Alex-302** [comment]
As I see, you are using Adblock, not Adguard.
Which elements should be blocked? Please mark them on screenshot.

**Comment by zum348** [comment]
![geek](https://cloud.githubusercontent.com/assets/25609768/22742096/3b1695d8-ee1e-11e6-86f7-1289a7dbc15b.png)
![pocket](https://cloud.githubusercontent.com/assets/25609768/22742136/621e068e-ee1e-11e6-8865-38fa4719f7e6.png)

**Comment by Alex-302** [comment]
1. geektime.co.il - there are many of redundant excsusions in Easylist Hebrew
Reported:
https://forums.lanik.us/viewtopic.php?f=62&t=35221&p=112972#p112972
2. pocketnow.com - it is clean on my side

**Comment by seanl-adg** [comment]
Should be resolved now, https://forum.adguard.com/index.php?threads/resolved-geektime-co-il.20537/ for more information.
