### ISSUE TITLE
RU AdList: Counters breaks Элементы Яндекс: Почта (версия 8.22.3) in Opera 36

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#43199]
При открытии расширения открывается маленькое дополнительное окошко, в котором видны входящие письма, но этого не происходит в окошке пишет ошибка. Если открыть яндекс
почту через сайт - страница почты открывается. Опытным путём было выявлено, что расширение ломает фильтр RU AdList: Counters.

**Comment by Alex-302** [comment]
давно исправлено с нашей стороны.
