### ISSUE TITLE
techsupport.diary.ru - missed ads

### ISSUE THREAD

**Issue by oprotsyk** [AdguardTeam/AdguardFilters#4321]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Ads at techsupport.diary.ru***:
* **Showing ads block in on the left of the page. No rules in User filter**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

![image](https://cloud.githubusercontent.com/assets/25342327/22706338/8d4e25a2-ed77-11e6-9119-2ccffb2e7ad1.png)

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

* **Expected behaviour**: 

No ads should be there.

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

***Steps to reproduce the problem***:

Go to http://techsupport.diary.ru/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS / Android 
Browser: | Chrome/ Opera
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default/Blacklist mode)
Stealth mode options(Windows) | On
Adguard filters: | 2, 5, 9, 111, 113, 116

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1183845

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
techsupport.diary.ru##.rotator-zone
```
