### ISSUE TITLE
wowhead.com - Ad leftover - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4322]
***Site***: http://de.wowhead.com/news=259977/this-week-in-broken-isles-2-7-pet-battle-bonus-event-lfr-wing-2-royal-athenaeum-
***Description***: Ad leftovers, ad block detection

<details>
<summary>Screenshot</summary>

- Ad leftover at the top.
- Ad block detection at the right.
- The right sidebar is ad leftover.

![image](https://cloud.githubusercontent.com/assets/10995998/22714799/6dea67d6-ed8e-11e6-84c0-ffac286f8aeb.png)

- Ad leftover at the bottom.

![image](https://cloud.githubusercontent.com/assets/10995998/22714813/817fafe0-ed8e-11e6-9ac8-d24d3e89ed9e.png)

That's how the page should look like:

![image](https://cloud.githubusercontent.com/assets/10995998/22714832/9ebf8e9a-ed8e-11e6-9c77-5d67ffb69ca1.png)

This can be achieved by clicking that small button at the right:

![image](https://cloud.githubusercontent.com/assets/10995998/22714857/bc3e1d38-ed8e-11e6-925c-1404dcc46c0a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.8.81
Spyware filter | 1.0.10.66
Social media filter | 1.0.17.18
Annoyances filter | 1.0.9.87
German filter | 1.0.31.16
Mobile ads filter | 1.0.7.1
Safari filter | 1.0.2.40

**Comment by Alex-302** [comment]
Added to Experimental filter
```
wowhead.com###page-content > div[class="main"] > div[class="blocks"]
wowhead.com##div[class="wrapper"] > div[class="blocks"]
```
Added to Annoyances filter
```
wowhead.com##.vertical-bg.is-atf
```
