### ISSUE TITLE
gamona.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4323]
***Site***: http://www.gamona.de/
***Description***: Ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22715013/6b5fc352-ed8f-11e6-96a4-a7e8e72ca0fa.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22715025/76a767c4-ed8f-11e6-8d48-fceb1b63be83.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22715061/8a9aa4bc-ed8f-11e6-97a4-247704509441.png)

**http://www.gamona.de/games/wiped-die-mmo-woche,wir-sind-wieder-zu-hause:article.html:**

![image](https://cloud.githubusercontent.com/assets/10995998/22715104/be2cb900-ed8f-11e6-88a0-6068748977d5.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22715113/cb341ba2-ed8f-11e6-89d9-1e343278a986.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.8.81
Spyware filter | 1.0.10.66
Social media filter | 1.0.17.18
Annoyances filter | 1.0.9.87
German filter | 1.0.31.16
Mobile ads filter | 1.0.7.1
Safari filter | 1.0.2.40

**Comment by Alex-302** [comment]
@seanl-adg Could you take a look? I think CSS rules are not the beter solution for this case.

**Comment by seanl-adg** [comment]
Removed a top ad leftover. To hide others, we can use something like 
```
gamona.de#%#(function(e){function c(a){for(var b in a)a.hasOwnProperty(b)&&("string"==typeof a[b]?d.push("."+a[b]):"object"==typeof a[b]&&c(a[b]))}var d=[];Object.defineProperty(window,"gamAdController",{value:{push:function(a){switch(typeof a){case "object":a.executeCallback&&a.executeCallback.call&&a.executeCallback();a.setStyleConfig&&a.setStyleConfig.classMap&&(c(a.setStyleConfig.classMap),a=e.createElement("style"),a.textContent=d.join(",")+"{display:none!important;}",e.head.appendChild(a));break;case "function":a()}}}})})(document);
```
but I am not sure if we should add such rules to our filters.
