### ISSUE TITLE
seat.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4324]
***Site***: http://www.seat.com/
***Description***: Cookie notice at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22715167/0dfef1be-ed90-11e6-9e17-41b66b3df9fc.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.8.81
Spyware filter | 1.0.10.66
Social media filter | 1.0.17.18
Annoyances filter | 1.0.9.87
German filter | 1.0.31.16
Mobile ads filter | 1.0.7.1
Safari filter | 1.0.2.40

**Comment by Alex-302** [comment]
fixed
