### ISSUE TITLE
[NSFW] daftporn.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#43251]
**Site Sample** | 
----------------|
https://www.daftporn.com/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.3 nightly X (XXXX)** 
Stealth Mode:					       | disabled
Chrome Extension: | [Polska Ciasteczkowa Zgoda - extra JS scripts blocking EU GDPR annoyances on polish websites](https://chrome.google.com/webstore/detail/polish-cookie-consent/bniijddcmabghibaojbkbnngbedopbno) 
Chrome Extension: | [AdGuard Adblocker Extension - Integration Mode](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg) 

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| FuckFuckAdblock
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

Ads

<details><summary><b>Screenshot:</b></summary>

![scr-1572503356-001](https://user-images.githubusercontent.com/9846948/67924192-3dbb1f00-fbb0-11e9-983a-e63dce672f01.png)

![scr-1572503385-001](https://user-images.githubusercontent.com/9846948/67924193-3dbb1f00-fbb0-11e9-9142-019f24bef9a0.png)

</details><br/>

@AdamWr @Alex-302

**Comment by FadeMind** [comment]
@AdamWr  Missed boxes iframes 
```
https://syndication.exosrv.com/ads-iframe-display.php?$domain=daftporn.com
```
![scr-1572526527-001](https://user-images.githubusercontent.com/9846948/67948515-27c85100-fbe6-11e9-9435-55520c49bf28.png)

**Comment by AdamWr** [comment]
Wygląda na to, że to wina tych reguł z listy `FuckFuckAdblock`:
`@@/^https?:\/\/(www\.)?.*\/([_-a-zA-Z0-9.]{1,15})?ad[svbx]?\.js/$script,xmlhttprequest`
`@@/^https?:\/\/(www\.)?.*\/ad[svbx]?([_-a-zA-Z0-9.]{1,15})?\.js/$script,xmlhttprequest`

**Comment by FadeMind** [comment]
CC @bogachenko incorrect blocking here

**Comment by FadeMind** [comment]
@AdamWr  dodatkowo click nie działa na odnośniki na stronie na dole jak FFA jest aktywne.

**Comment by AdamWr** [comment]
Powinno pomóc:
`daftporn.com#@%#//scriptlet("disable-newtab-links")`

**Comment by FadeMind** [comment]
Póki co wyłączyłem FFA i czekam na feedback do @bogachenko. Dzięki za pomoc.
