### ISSUE TITLE
buffed.de - Ad - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4327]
***Site***: http://www.buffed.de/Heroes-of-the-Storm-Spiel-17022/Guides/Valeera-Guide-und-Review-der-Warcraft-Assassine-1220241/
***Description***: Social bar at the bottom on mobile devices. Amazon link after the article.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22715440/39ba9956-ed91-11e6-82f5-58ed3e511993.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.8.81
Spyware filter | 1.0.10.66
Social media filter | 1.0.17.18
Annoyances filter | 1.0.9.87
German filter | 1.0.31.16
Mobile ads filter | 1.0.7.1
Safari filter | 1.0.2.40

**Comment by Alex-302** [comment]
added
buffed.de##.amazonVideoTeaser
buffed.de##.shopLinkButtonsWrapper
buffed.de##.header_footer.ui-footer
