### ISSUE TITLE
http://dio66.net/ - pop-ups

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4329]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/22725150/1b773c4a-edd4-11e6-9559-b0a71712d3f3.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

http://dio66.net/forum.php?mod=viewthread&tid=1403512&extra=page%3D1%26filter%3Dtypeid%26typeid%3D171%26typeid%3D171

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.1.298.1564 / 1.4.0
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | BlockThirdPartyCookies, DisableThirdPartyCache, BlockWebRtc, BlockBrowserPushApi, BlockBrowserLocationApi, RemoveXClientDataHeader, HideSearchQueries, SendDoNotTrackHeader, RemoveRefererFromThirdPartyRequests, HideUserAgent. 
Adguard filters: | English filter, Spyware filter, Fanboy's Annoyances, ChinaList+EasyList, Fanboy's Enhanced Tracking List, User filter / English filter, Spyware filter, Social Media filter, Annoyance filter, Russian filter.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1499272

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Ads are blocked by *Easylist China* filter. Ads in post are built in by topic starter and we need too much rules.
For test:
```
dio66.net#%#AG_onLoad(function() { window.openpopup = function() {}; });
dio66.net##td[id^="postmessage_"] > font[size="4"] > a+br+br~br
dio66.net##td[id^="postmessage_"] a > img[width="700"]
```

**Comment by githupper** [comment]
I was already using EasyList China filter.

The 3 lines works for the ads above but there are still tons of big ads below the post (scrollable windows) and small thumbnails.

**Comment by Alex-302** [comment]
@githupper please make screenshots and mark elements, which should be blocked.

**Comment by githupper** [comment]
Both big ads and thumbnail ads as circled in red.


![new bitmap image](https://cloud.githubusercontent.com/assets/25658765/22850447/830fd00c-f044-11e6-8d5c-a9984862040d.jpg)
![new bitmap image 2](https://cloud.githubusercontent.com/assets/25658765/22850480/cccb2a34-f044-11e6-81c3-9f7b35ff002f.jpg)

**Comment by Alex-302** [comment]
add
```
dio66.net##td[id^="postmessage_"] iframe
||mowatu.com^$domain=dio66.net
||javcc.net^$domain=dio66.net
||mmbo.me^$domain=dio66.net
```
Are these ads in all threads, or only in this?

**Comment by githupper** [comment]
All threads. The ads ain't static so even if I block them using element hider. After maybe a few days the ads are different and ain't blocked by element hider anymore.

**Comment by Alex-302** [comment]
are these rules helps you?

**Comment by githupper** [comment]
It works to remove the ads at the TOP of the page but I can tell they are loaded first then disappear a while later.

As mentioned, those ads below still appeared regardless of the rules

**Comment by Alex-302** [comment]
It is clean with all these rules:
```
dio66.net##td[id^="postmessage_"] iframe
||mowatu.com^$domain=dio66.net
||javcc.net^$domain=dio66.net
||mmbo.me^$domain=dio66.net
||dio66.net/images/*-700x*.gif
||dio66.net/images/*-800x*.gif
dio66.net#%#AG_onLoad(function() { window.openpopup = function() {}; });
dio66.net##td[id^="postmessage_"] > font[size="4"] > a+br+br~br
dio66.net##td[id^="postmessage_"] a > img[width="700"]
```
http://s8.hostingkartinok.com/uploads/images/2017/02/5093de9104df231633624e044314f6a6.png

**Comment by githupper** [comment]
Thanks!

The big ads are gone now.

Is it possible to remove those recommended links as well?

![new bitmap image](https://cloud.githubusercontent.com/assets/25658765/22973957/ff68984a-f3ba-11e6-9423-873c8355363d.jpg)

Thank you very much for the help

**Comment by Alex-302** [comment]
Not sure, they are just urls.
