### ISSUE TITLE
https://xhamster.com - incorret blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4330]
The Login button does not react on tapping. 
![image](https://cloud.githubusercontent.com/assets/15856304/22726426/08188b6a-eddc-11e6-86fc-ce26ff8a5c06.png)

STR: 

1. Go to https://xhamster.com/login
2. Type in some login and password
3. Tap Login
5. It does nothing

[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Browser: | Safari
Adguard version: | 1.1.5.40
Simplified filters(iOS) | Off
Adguard DNS: | Default
Adguard filters: | English, Spyware, Annoyances, Social media and Mobile ads and Safari filter

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1492456

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||xhamster.com/ajax/
@@||google.com/recaptcha/$domain=xhamster.com
@@||google.com/js/bg/$domain=xhamster.com
```
