### ISSUE TITLE
DVGet app - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4331]
https://play.google.com/store/apps/details?id=com.dv.get&hl=ru
![0mgnh5mt7lc](https://cloud.githubusercontent.com/assets/23637588/22729876/9e56207e-edf5-11e6-9a96-ad4e304efea2.jpg)

***System configuration***

Information | value
--- | ---
Operating system: | Android 4.4.2
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None 
Adguard filters: | en, ru, social media, spyware, annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

**Comment by Alex-302** [comment]
встроена
