### ISSUE TITLE
outlook.com - cannot delete an email from search results

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4332]
User report:
> I also found out that I can’t delete an e-mail from Outlook.com, when I have used the Outlook search function during Stealth mode enabled. After disabling Stealth mode, I can delete an e-mail from search function view.

**Comment by seanl-adg** [comment]
What I can reproduce is the following:
 - Search for a random word
 - In the search results page, hover on any email, then some icons (delete, mark as unread, etc) appears.
 - Click on 'delete' icon there.

Then it does not make any visual change, but if I check the inbox after then, the email was deleted. So I thought the mail wasn't deleted at first, but actually it is deleted. I guess it is what who reported the problem experienced.

However, disabling Stealth mode or disabling Adguard completely does not make difference on the result. It seems that it is the way how Outlook is supposed to work.

**Comment by Bushido1** [comment]
Interesting, why Opera browser shows ,,Content blocked" message, when Stealth mode is on at search results page. This message does not appear, when Stealth mode is disabled. I think it is related to Adguard somehow.
![5](https://cloud.githubusercontent.com/assets/11409601/22781354/cf21048c-eeca-11e6-93ea-176deff1167f.jpg)

**Comment by Alex-302** [comment]
@Bushido1 which Stealth Mode option cause to this issue?

**Comment by Bushido1** [comment]
,,Content blocked" message appears, when I manyally write something to the search box. When I click on a search hint (previously written search term), then no ,,Contect blocked" message.

**Comment by seanl-adg** [comment]
@Bushido1 Can you post a complete configuration where you reproduce the issue?
AG product, enabled filters & stealth mode options, browser versions.

**Comment by Bushido1** [comment]
@seanl-adg 
Adguard for Windows, filters are attached as images, I have enabled all stealth mode options except self-destructing first-party cookies. ..This page tries to load script from unauthorized source" message comes up with Opera 44.0.2494.0 and Google Chrome 56.0.2924.87.
![adguard for windows filter](https://cloud.githubusercontent.com/assets/11409601/22862056/ca1e9f8c-f12f-11e6-9923-03a5a81b0f1b.jpg)
![adguard for windows filter1](https://cloud.githubusercontent.com/assets/11409601/22862055/ca1e0720-f12f-11e6-84cb-4d5e9a62b4ac.jpg)
