### ISSUE TITLE
isohunt2.net

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#43339]
Клик по любых кнопках\ссылках на сайте приводит к открытию всплывающего окна..

**Comment by krystian3w** [comment]
```
||getclicky.com^
||mc.yandex.ru^
/matomo.js
```

**Comment by krystian3w** [comment]
```js
function(c) {
  var d = a(this),
    e = d.data("method"),
    k = d.data("confirm");
  if (void 0 === e && void 0 === k) return !0;
  void 0 !== k ? f.confirm(k, function() {
    f.handleAction(d)
  }) : f.handleAction(d);
  c.stopImmediatePropagation();
  return !1
}
```

`https://isohunt2.net/static/main.min.js?v=1478846420`

**Comment by Alex-302** [comment]
@Smorvel оттуда скачать хоть можно? Жму Скачать, а там бесконечное количество Continue

**Comment by Smorvel** [comment]
Я честно не в курсе)) не проверял... сейчас гляну.
Проверил... кликнул на магнитную кнопку, прошел 100 редиректов и таки получил нужный торрент в конце..) то же самое и с кнопкой скачать.

**Comment by Alex-302** [comment]
У меня посторонние окна не открываются.
