### ISSUE TITLE
vimeo.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#43335]
[https://vimeo.com/1084537](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://vimeo.com/1084537)

![vimeo](https://user-images.githubusercontent.com/35470489/68040601-68d76880-fcad-11e9-834a-f5f084eccef2.png)

Adguard Base + Annoyances + Mobile + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Mozilla/5.0 (Android 7.1.2; Tablet; rv:68.0) Gecko/68.0 Firefox/68.0

**Comment by Alex-302** [comment]
Cannot reproduce. @zloyden please take a look.

**Comment by AdamWr** [comment]
I can reproduce it.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/68122632-12676580-ff0b-11e9-8726-fc54f9d0419d.png)

</details>

Added:
`vimeo.com##.app_banner_container`

**Comment by zloyden** [comment]
Not reproduced on my end.
