### ISSUE TITLE
pikabu.ru - missed ads

### ISSUE THREAD

**Issue by oprotsyk** [AdguardTeam/AdguardFilters#4336]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Ads at pikabu.ru***:
* **At the to of the page the ads of honor appears**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

![image](https://cloud.githubusercontent.com/assets/25342327/22750066/1f10a85a-ee38-11e6-874a-18c534c340ff.png)

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

No ads should be there.

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

Open http://pikabu.ru
On Android - Open full version

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS / Android 
Browser: | Chrome, Opera
Adguard version: | 6.1.309.1615
Adguard driver (Windows): |  TDI
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default/Blacklist mode) 
Stealth mode options(Windows) | enabled
Adguard filters: | 2, 3, 4, 6, 11, 14, 101

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1093966

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
