### ISSUE TITLE
vod.pl/seriale/nimfy/dkvtqd6 - Incorrect  blocking

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4338]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: vod.pl/seriale/nimfy/dkvtqd6 - Incorrect  blocking
* **Current behaviour**: can't watch the video with Adguard enabled 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/e6ht2x

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: http://prnt.sc/e6htec

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Application version: 1.1.5.40
Platform: iOS
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.8.83 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.66 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.18 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.55 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.40 Enabled=YES
ID=101 Name="EasyList" Version=1.0.67.64 Enabled=NO
ID=117 Name="Adblock Polska" Version=1.0.0.52 Enabled=YES
ID=216 Name="Adblock polskie reguły" Version=1.0.6.25 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1501099

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
This player doesn't work with my Polish VPN.
Try these rules:
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=vod.pl
@@||securepubads.g.doubleclick.net/gpt/pubads_impl_108.js$domain=vod.pl
```

**Comment by F4z** [comment]
The first one works on my end (checked on iOS).

**Comment by Alex-302** [comment]
Ok, added.
