### ISSUE TITLE
ads 

### ISSUE THREAD

**Issue by ghajini** [AdguardTeam/AdguardFilters#4340]
***Description***: site with popunders
* **Current behaviour**: 
popups/popunders not blocked on page load

[//]: # when i go to this site and click in page,it redirects to so many pages

Screenshot
too random popups
url:
`https://www.worldfree4u.lol/category/300mb-movies/`
* **Expected behaviour**: 

popunder should be blocked by default

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: firefox 51.0.1
Adguard version: | 2.5.11
Adguard filters: | 

[//]: # adguard english filter 1.1.8.93, 
[//]: # spyware filter 1.0.10.68 ,  
[//]: # easyprivacy 1.0.74.27, 
[//]: # peter lowes list 1.0.2.73 
[//]: # malware protection 1.0.74.30

**Comment by Alex-302** [comment]
Added to English filter
```
worldfree4u.lol#$#body > a[onclick] { width: 0px!important; height: 0px!important; }
```
