### ISSUE TITLE
mail.ru - Missed ads (Yandex Extension)

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4341]
User's screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-02-09 at 4 41 47 pm](https://cloud.githubusercontent.com/assets/22892774/22788276/ff531362-eee7-11e6-8b90-4f66e746e964.png)
)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows XP
Browser: | Yandex
Adguard version: | 2.5.11
Adguard filters: | http://prnt.sc/e6jzuo

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

We were able to reproduce:
**Screenshot:** http://prnt.sc/e6k2he

Ticket ID: 1050245

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by zebrum** [comment]
have 2 complains too.

**Comment by Alex-302** [comment]
Домен не правильный. 
О пробеме знаю, дубль закрываю.

**Comment by Bohdan-SUP** [comment]
@Alex-302 is this resolved?
User 1050245 still complaints. We can't reproduce on our end on a steady basis.

**Comment by Alex-302** [comment]
@Bohdan-SUP специально же закрыл.
Вон, восемь задач на выбор
https://github.com/AdguardTeam/AdguardFilters/issues?utf8=✓&q=e.mail.ru

**Comment by Alex-302** [comment]
как-нибудь удалённо нужно будет глянуть

**Comment by Bohdan-SUP** [comment]
Ок. Будем просить удалёнку, если что.

**Comment by vmalyuta** [comment]
@Alex-302 user is okay ti have a tv session.
Today at 5 PM, UTC time

**Comment by vozersky** [comment]
@vmalyuta did you mean "UTC +7"

**Comment by vmalyuta** [comment]
@vozersky yes.
