### ISSUE TITLE
vanion.eu - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4343]
***Site***: http://www.vanion.eu/
***Description***: Ad leftovers in middle and sidebar and social widget leftover in sidebar.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22805851/c12f7796-ef1f-11e6-8450-76ec7d7ca34b.png)

![image](https://cloud.githubusercontent.com/assets/10995998/22805863/cdacbe70-ef1f-11e6-849b-f90dba2e125c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.8.97
Spyware filter | 1.0.10.68
Social media filter | 1.0.17.20
Annoyances filter | 1.0.9.92
German filter | 1.0.31.21
Mobile ads filter | 1.0.7.5
Safari filter | 1.0.2.43

**Comment by Alex-302** [comment]
fixed
