### ISSUE TITLE
mmoga.de - Ad - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4345]
***Site***: https://www.mmoga.de/
***Description***: 

- Ad background. 
- Social widget leftover in right sidebar.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/22806143/eea00ece-ef20-11e6-8a27-cc9c20fa8954.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.8.97
Spyware filter | 1.0.10.68
Social media filter | 1.0.17.20
Annoyances filter | 1.0.9.92
German filter | 1.0.31.21
Mobile ads filter | 1.0.7.5
Safari filter | 1.0.2.43

**Comment by Alex-302** [comment]
Not sure about it.
