### ISSUE TITLE
http://filecloudphone.weebly.com/blog/kak-otklyuchitj-vsplivayuschee-okno-kazino-vulkan

### ISSUE THREAD

**Issue by DopeUnicorn** [AdguardTeam/AdguardFilters#4348]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): |  
Simplified filters(iOS) | 
Adguard DNS: | None 
![screen shot 2017-02-10 at 12 03 54 pm](https://cloud.githubusercontent.com/assets/25641172/22822689/16a99788-ef89-11e6-9e18-6a3b66f580c5.png)

Stealth mode options(Windows) | 
Adguard filters: |  English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt
FilterId:4 Name: Social media filter Url: https://filters.adtidy.org/extension/chromium/filters/4.txt
FilterId:14 Name: Annoyances filter Url: https://filters.adtidy.org/extension/chromium/filters/14.txt
FilterId:1 Name: Russian filter Url: https://filters.adtidy.org/extension/chromium/filters/1.txt
FilterId:6 Name: German filter Url: https://filters.adtidy.org/extension/chromium/filters/6.txt
FilterId:7 Name: Japanese filter Url: https://filters.adtidy.org/extension/chromium/filters/7.txt
FilterId:104 Name: EasyList China Url: https://easylist-downloads.adblockplus.org/easylistchina.txt

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1428525

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
