### ISSUE TITLE
LAtimes.com  - incorrect blocking 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4349]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: LAtimes.com  - incorrect blocking 
* **Current behaviour**:  large white spaces where ads would normally be when using Adguard

Screenshot:
http://prnt.sc/e77k9r - with Adguard
http://prnt.sc/e77klg - without Adguard
http://prnt.sc/e77ks7 - with Norton

* **Expected behaviour**: http://prnt.sc/e77ks7

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***System configuration***

Application version: 1.1.5.65
OS: 10.3
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.8.93 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.7.49 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.12.3 Enabled=NO
ID=12 Name="Safari filter" Version=1.0.2.41 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1501963

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
latimes.com##.trb_masthead_adBanner
```

**Comment by evgeniy-ADG** [comment]
You fixed the blank space at the top of the page but not the multiple blank spaces where ads occur further down. Here is an example (first using adguard, second without, third with Norton adblocker):

<details>

![image1](https://cloud.githubusercontent.com/assets/15856304/23117759/df65e41a-f759-11e6-9ddb-bc7698ecea9c.png)

![image2](https://cloud.githubusercontent.com/assets/15856304/23117763/e3f34c5c-f759-11e6-872e-3ac2b78d252d.png)

![image3](https://cloud.githubusercontent.com/assets/15856304/23117769/eb5c9a5c-f759-11e6-8e12-87459c1de101.png)

**Comment by Alex-302** [comment]
Added to English filter
```
latimes.com##.trb_gptAd
```
check it
