### ISSUE TITLE
Blocking useful content сайт-краснодара.рф

### ISSUE THREAD

**Issue by oprotsyk** [AdguardTeam/AdguardFilters#4350]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Blocking the content***:
* **Adguard blocks the content of the site, leaving empty space instead**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

![screen shot 2017-02-11 at 03 52 23](https://cloud.githubusercontent.com/assets/25342327/22850135/822fee60-f00d-11e6-8af3-0c9c80db149a.png)

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:

![screen shot 2017-02-11 at 03 53 58](https://cloud.githubusercontent.com/assets/25342327/22850150/a5de561c-f00d-11e6-9c82-88a47d7e31f3.png)

![image](http://somehosting.com/adg_off.jpg)

</details>

***Steps to reproduce the problem***:

Open http://сайт-краснодара.рф/объявления/недвижимость

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: |  Chrome, Opera
Adguard version: | 1.4.0
Adguard filters: | English, Russian

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1501854

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
