### ISSUE TITLE
http://nnm.me/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4352]
![image](https://cloud.githubusercontent.com/assets/15856304/22852417/76874b58-f044-11e6-8567-a28d486b9d2b.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Safari, Chrome
Adguard version: | 1.4 beta
Adguard DNS: | None 
Adguard filters: | basic set + dutch, norsk, easylist china

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1501976

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
