### ISSUE TITLE
Реклама в приложении

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#4353]
Буду краток (привет @Alex-302). Приложение myscore Android. Пропускает рекламу, фильтры по-умолчанию, Фильтрация качественная HTTPS, версия последняя. http://s61.radikal.ru/i174/1702/32/cec6a4245fbf.png

**Comment by Alex-302** [comment]
скрин не открывается. На другой хостинг залей или сюда прикрепи файл

**Comment by ministr91** [comment]
Только что открыл и все норм. Насчет проблемы - она решена. Видимо, был сбой adguard. Перезапуск решил проблему

**Comment by ministr91** [comment]
Тему можно закрывать
