### ISSUE TITLE
Backgammon King [Android] [Incorrect Rule]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#43538]
App Name: Backgammon King
Version: 37.0
Play Store Link: https://play.google.com/store/apps/details?id=com.mobirix.backgammon&hl=en

Issue: After opening the app, click on the third option "Multiplayer" and nothing will happen. When AG for Android is disabled and the same option is tapped, we are able to play online. Please fix.

Filters: AG Base, Mobile Ads, Peter Lowe's, AG Tracking Protection, AG Social Media, Malware Domains, Spam 404, NoCoin, AG Annoyances, AG warning removal

User Filters: Disabled
Extensions: Disabled
Stealth Mode: Disabled
DNS Filtering: Enabled (AG DNS) with DNS User Filter and AG Simplified domain names

**Comment by Alex-302** [comment]
@Nzzyme please check with(one by one):
- disabled filters;
- disabled DNS filtering(use system DNS)

**Comment by krystian3w** [comment]
IMO no blocked on DNS (DoH version no block multiplayer).

**Comment by BlazDT** [comment]
Multiplayer is even broken without AdGuard for me (stuck at loading Google play servers).

**Comment by Nzzyme** [comment]
Yes, even I am now unable to play even when AG is disabled. It was playing yesterday

**Comment by krystian3w** [comment]
3 days ago works fine, IMO we need wait and again test filters before close isuee.
