### ISSUE TITLE
http://forum.xumuk.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4354]
http://forum.xumuk.ru/index.php?act=idx 

Adguard заблокировал мне панель
редактирования текста на форуме
http://forum.xumuk.ru/index.php?act=idx, оставив только
поле ввода текста. А без нее
невозможно нормально форматировать
текст (выставлять верхний/нижний
индекс, курсив, жирный шрифт и прочее).
Исправьте пожалуйста, чтоб панель не
скрывалась. PS. При выборе в помощнике
"не блокировать 30 секунд" панель
возвращается

<details>

![default](https://cloud.githubusercontent.com/assets/15856304/22853641/df40550c-f064-11e6-87ba-5310dcf3872d.jpg)

![30](https://cloud.githubusercontent.com/assets/15856304/22853642/e03bef16-f064-11e6-9008-b68218ea2c27.jpg)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows XP SP3
Browser: | Opera 12
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | TDI
Adguard DNS: | None
Stealth mode options(Windows) | On
Adguard filters: | 1 2 102

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1033881

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не повторяется. Какой фильтр ломает и что в журнале?
