### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4355]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Можно ли правило, чтоб заблокировать новости и оставить только вход?

Screenshot:

<details>

![printsreen1](https://cloud.githubusercontent.com/assets/17320558/22855878/191dfc9a-f090-11e6-8aa3-54fcb874ad1a.jpg)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.258.1302
Adguard driver (Windows): | WFP
Adguard filters: | Russian filter, English filter, Latvian List, Norsk adblockliste, Adblock polskie 

Ticket ID(if exists): 1499907

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
```
inbox.lv###adv-center
inbox.lv##.carousel_inner.col-widget-1
inbox.lv##.col-adv
inbox.lv##.adv-0
inbox.lv###carousel_slider_top.col-carousel
```
