### ISSUE TITLE
Google advertisements

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardFilters#43566]
![adguard](https://user-images.githubusercontent.com/12443285/68235678-f398ca00-0003-11ea-845e-03d37e7cace7.PNG)

Since today I am seeing ads when I search in Google. Please fix.

**Comment by BlazDT** [comment]
Not reproduced. Did you by chance enabled filter to show search ads?

**Comment by worldsdream** [comment]
@BlazDT No I don't have that option enabled. I just checked. I also reinstalled AG to check if there is something wrong with the application itself. Still the same.

**Comment by BlazDT** [comment]
HTTPS filtering is still active and AdGuard certificate is displayed I guess? Which OS is this happening at?

**Comment by worldsdream** [comment]
Yes https filtering is active and AG cert is displayed.
Windows 10 latest

**Comment by worldsdream** [comment]
I reinstalled the certificate trough AG and now all is good. Weird issue. Should not be like that all of a sudden. Closed.
