### ISSUE TITLE
15min.lt - ad leftovers

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4357]
15min.lt

![image1 2](https://cloud.githubusercontent.com/assets/15856304/22860423/3f8ddda2-f106-11e6-99dc-7ced865e7446.PNG)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: |  English, Mobile ads and Safari.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1398913

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
15min.lt##.mobile-ad-placeholder
```
