### ISSUE TITLE
https://www.yahoo.com/ - placeholder / missed ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4358]
https://www.yahoo.com/

![img_3340](https://cloud.githubusercontent.com/assets/15856304/22860762/547f711c-f110-11e6-9d2a-ac67344cc1b9.PNG)

***System configuration***

Information | value
--- | ---
Operating system: | ios 10.2.1
Browser: | safari
Adguard version: | 1.1.5.40
Simplified filters(iOS) | Off
Adguard filters: | 2 3 4 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1502987

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
www.yahoo.com###act-ad-parallax
```
