### ISSUE TITLE
pb.wtf пропуск рекламы.

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#4359]
Пролазят 2 рекламных блока: 

**Скрины:**
<details>

![image](https://monosnap.com/file/X1wixXUYr7b83u8bqutz013DST4KqC.png)

![image](https://monosnap.com/file/RLelmXLihwIJSbPxyFjwMQDJXFeaDh.png)
</details>

**Comment by Alex-302** [comment]
fixed

**Comment by Smorvel** [comment]
Если залогиниться на сайте, и открыть любую раздачу, то adguard жрет всю страницу почти (остается только шапка и низ).
Плюс после логина появляются белые пустые блоки от рекламы (под чатом) на главной странице, вообще мне они не мешают но если есть возможность, то желательно убрать.

**Comment by Alex-302** [comment]
ой) Через 15 минут будет доступно исправление.
Белые пустоты пока пусть повисят, позже уберу.

**Comment by Smorvel** [comment]
@Alex-302 они снова вернули рекламу :/ Думаю после исправления снова вернут...

**Comment by Smorvel** [comment]
@Alex-302 Снова прорвалась, и снова перевели на bxt, может стоит и bxt и axt оставить? хотя скорее всего сделают еще что-то :/

**Comment by Alex-302** [comment]
ну да, если они с Адгардом проверяют, то борьба будет бесконечной.

**Comment by Smorvel** [comment]
Значит мы проиграли? =( Печально, но все равно спасибо! Придется использовать пользовательские правила..

Добавил в пользовательские:
```
pb.wtf,piratbit.org,piratbit.ru##a[href^="/fxt/"]
pb.wtf,piratbit.org,piratbit.ru##.table-condensed+div[id][-ext-has=' > div[class] > a[style^="position: relative;"] > img[src^="/t6zer/"]']
pb.wtf,piratbit.org,piratbit.ru##script+div[id][-ext-has=' > div[class] > a[style^="position: relative;"] > img[src^="/t6zer/"]']
pb.wtf,piratbit.org,piratbit.ru##.chat+div[id][-ext-has=' > div[class] > a[style^="position: relative;"] > img[src^="/t6zer/"]']
pb.wtf###main_content > DIV:nth-child(4)
```

**Comment by Alex-302** [comment]
Ну, когда проверяют с нашим блокировщиком, то хозяин сайта всегда на шаг впереди.

**Comment by Smorvel** [comment]
@Alex-302 может стоит по другому подойти к блокировке? Заблокировать по размеру блока, или еще как...

Напоминаю, на главной странице https://pb.wtf/ реклама под чатом (когда залогинен), и рекламные вставки в верхнем меню из постеров.
На странице с раздачами https://pb.wtf/topic/254100/ реклама вверху (над заголовком), внизу в виде комментария.

**Comment by Alex-302** [comment]
> Что бы им надоело)
ну передвинут в другое место или порядок поменяют. Им не надоедает)

**Comment by Smorvel** [comment]
@Alex-302 У меня есть небольшой вопрос..
https://pb.wtf/topic/254217 тут когда зарегистрирован, есть 6 кнопок в области для скачивания.. Я пытаюсь заблокировать кнопку "Скачать по прямой ссылке" a.btn.btn-sm.btn-success.dS1.srt но никак не могу этого сделать, CSS сайта встает поверх CSS AdGuard. Почему так?

**Comment by Alex-302** [comment]
Там стиль с `display: block !important;`.
Надо вот так, например:
```
#$#a.btn.btn-sm.btn-success.dS1.srt { position: absolute!important; left: -3000px!important; }
```
