### ISSUE TITLE
 http://www.xtube.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4360]
When visiting http://www.xtube.com/ and select a random video that I want to watch, I get unwanted popup website with the address: http://www.flirt4free.com/rooms/leon-stud/?no_video=1&utm_source=pop&utm_medium=rooms&utm_campaign=xtube-mobile&utm_content=akfa3
I get a message with a red bar on Android 6.0 with Chrome and Firefox :
Error. Failed to connect to the video server. Please try refreshing the page. It happens often when i open xtube the first time.

Please see logs in the ticket.

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Chrome, FF
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On Default
Adguard DNS: | None
Adguard filters: | 2, 3, 4, 14, 8, 11, 15, 211 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1492862

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
