### ISSUE TITLE
LinkedIn not working correctly (Annoyance filter)

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardFilters#43626]
When you want to clear your search result in LinkedIn, nothing happens.
When you disable AG, it works. I can confirm that the annoyance filter is causing it.

Please check

**Comment by krystian3w** [comment]
```
linkedin.com#@#.modal-container
```

**Comment by BlazDT** [comment]
Please try this rule:

linkedin.com#@$#.modal-container { display:none!important; }

**Comment by krystian3w** [comment]
Works, uBO simplified `linkedin.com#$#.modal-container { display:none!important; }` to `linkedin.com##.modal-container`

**Comment by worldsdream** [comment]
Working great now!
