### ISSUE TITLE
yandex.ru/pogoda - yandex.direct in Firefox

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4363]
![image 001](https://cloud.githubusercontent.com/assets/15856304/22862123/466fd17c-f131-11e6-88a3-69bddab9fb39.jpg)

Вот еще жалоба. Windows.  В браузере Mozilla на странице Яндекс Погода есть реклама Яндекс Директ. В браузерах Opera и Yandex такой рекламы нет.

***System configuration***

Information | value
--- | ---
Operating system: | Windows NT 6.1.7601 Service Pack 1
Browser: | Firefox
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard DNS: | None
Stealth mode options(Windows) | On
Adguard filters: | 1 2 3 104 111 119

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1233698

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
у нас не повторяется.
Реклама мигает и пропадает, или после появления ничего с ней не происходит?
