### ISSUE TITLE
m.filmix.me - social media vidgets

### ISSUE THREAD

**Issue by oprotsyk** [AdguardTeam/AdguardFilters#4364]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***m.filmix.me***:
* **Social media vidgets are not hidden**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

![screen shot 2017-02-12 at 5 33 20 pm](https://cloud.githubusercontent.com/assets/25342327/22863472/671c554a-f149-11e6-815a-f58f3e4c3fc4.png)

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

No vidgets should be there.

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

Open https://m.filmix.me/serialy/61376-vikingi-vikings-serial-2013.html

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS / Android 
Browser: | Chrome, Android
Adguard version: | 2.8.76 / 1.4.0
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default/Blacklist mode) 
Adguard filters: | 2, 3, 4, 14, 1, 11

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1049047

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
