### ISSUE TITLE
https://inf-ege.sdamgia.ru/ anti-adblocker

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4365]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:https://inf-ege.sdamgia.ru/ anti-adblocker

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot: http://prntscr.com/e7tb72

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS / Android 
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Stealth mode options(Windows) | Enabled
Adguard filters: | 0 2 3 4 14 7 10 1 6 7 8 9 11

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 829126

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
