### ISSUE TITLE
Go Comics app ad leftover

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4366]
https://play.google.com/store/apps/details?id=com.amuniversal.android.gocomics&hl=en

User complaint:
https://forum.xda-developers.com/showpost.php?p=70909903&postcount=2120

Please check if there's anything we can do.

**Comment by seanl-adg** [comment]
I couldn't find a way to remove the ad placeholder at bottom. There are several blocked requests to googleads.g.doubleclick.net domain. Enabling DNS request blocking didn't help.

**Comment by Alex-302** [comment]
@seanl-adg try to unblock some request(s) and play with $empty and $replace :)

**Comment by ameshkov** [comment]
It very well might be a hard-coded banner place. Ok then, guys, let's leave it.
