### ISSUE TITLE
http://imgsrc.ru/ - unwanted pop-up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4367]
When browsing http://imgsrc.ru/, onderlea.info site opens in a new tab.

![image](https://cloud.githubusercontent.com/assets/15856304/22874651/ee99c81e-f1cf-11e6-9cb3-00e6ce17a8d5.png)

***Steps to reproduce the problem***:

1) Get to imgsrc.ru/main/search.php (I have it bookmarked.)
2) Click Egypt under the travel heading (though any search will do it)
3) If the onderlea.info ad hasn't yet appeared, it will by the time I choose a subcategory (e.g.- underwater ruins). In quick succession, a 'blank page' - onderlea.info - 'this page can not be displayed' happens. Again click "underwater ruins" and the sequence repeats. The third time, it allows me through to the requested page.
4) The problem can occur at any point in the process of searching - going from one picture to another, going from one page to another, changing the search (to Germany instead of Egypt for example). 
5) Rarely, perhaps one in several dozen searches, a redirect ad slips through - showing four or five url's in rapid succession, and ending with either a full window advertisement or a "YOUR COMPUTER IS INFECTED" type of page - in which case I manually shut down the computer, run rkill, JRT, adware cleaner, and a malware scan with Emsisoft. Although JRT comes up with a few temporary files to delete, the problem with onderlea.info returns with my next visit to imgsrc.

***System configuration***

Information | value
--- | ---
Operating system: | Windows NT 6.1.7601 Service Pack 1
Browser: | IE, Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | TDI
Adguard DNS: | None
Stealth mode options(Windows) | "BlockThirdPartyCookies": true, "BlockThirdPartyCookiesPeriodMin": 30, "BlockFirstPartyCookies": false, "BlockFirstPartyCookiesMin": 2880, "DisableThirdPartyCache": true, "BlockWebRtc": true, "BlockBrowserPushApi": false, "BlockBrowserLocationApi": true, "RemoveXClientDataHeader": true, "HideSearchQueries": true, "SendDoNotTrackHeader": true, "RemoveRefererFromThirdPartyRequests": true, "HideUserAgent": false, "CustomUserAgent": null, "CustomReferer": null, "HideIp": true, "CustomIp": "209.141.53.254"
Adguard filters: | 2 3 4 10

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1472655

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by Alex-302** [comment]
@seanl-adg please check it on your side.
