### ISSUE TITLE
Consider blocking https://my.openwrite.cn/js/readmore.js

### ISSUE THREAD

**Issue by maple3142** [AdguardTeam/AdguardFilters#43672]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I found that some Chinese websites(especially blogs) started to use a script created by [OpenWrite](https://my.openwrite.cn/), which requires user to scan a QR code and follow them on WeChat to get a access code to read the whole article.

### Proposed Solution

Block `https://my.openwrite.cn/js/readmore.js`.

### Additional Information

For detailed information about that script, [this](https://openwrite.cn/openwrite/openwrite-readmore/) may help.(As it is written in Chinese, I will roughly translate it if needed.)

Some example websites with this script installed:
https://snowdreams1006.github.io/hexo-plugin-readmore/
https://coderluo.top/algorithm/singlenumber/
http://www.54tianzhisheng.cn/2019/12/31/geekbang/

**Comment by Alex-302** [comment]
I see this element at http://www.54tianzhisheng.cn/2019/12/31/geekbang/ only, and blocking that script do not block QR banner.

**Comment by Alex-302** [comment]
Please add few screenshots.

**Comment by maple3142** [comment]
@Alex-302 It works for me like this: https://streamable.com/j7fji , maybe you need to use `Ctrl+F5` to force refresh everything to make sure the change works.

**Comment by Alex-302** [comment]
Got it. That's why we always ask for screenshots:)
