### ISSUE TITLE
fredolsen.es

### ISSUE THREAD

**Issue by Leon422** [AdguardTeam/AdguardFilters#43681]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

* **Current behaviour**: 

When using the "AdGuard annoyances" filter, the cookies pop-up is blocked. However, when the pop-up is supposed to appear, the scroll bar dissapears permanently and the page can't be scrolled even with the mouse wheel, rendering the site unusable.

* **Expected behaviour**: 

The scroll bar should not dissapear

***Steps to reproduce the problem***:

Enable the "AdGuard annoyances" filter
***System configuration***

**Filters:**
AdGuard Annoyances

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | ?
Browser:                               | Firefox
AdGuard version:                       | I use uBlock Origin
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.

Thank you for reporting it.
