### ISSUE TITLE
arendator.ru - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4368]
http://www.arendator.ru/news/153001-alfa-bank_i_vtb_zabrali_ofisy_svyatogora_za_dolgi/

![2017-02-13 13 35 52](https://cloud.githubusercontent.com/assets/23637588/22880062/c64387a2-f1f1-11e6-90c9-f78a0e2ff489.png)

adguard 1.4.0 chrome
spyware en ru social media annoyances

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
arendator.ru##.banner-box
arendator.ru#$#.arcticmodal-container { display: none!important; }
arendator.ru#$#.arcticmodal-overlay { display: none!important; }
arendator.ru#$#body { overflow: visible!important; }
```
