### ISSUE TITLE
eda.ua

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#4369]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://eda.ua/landing

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-02-13 at 14 01 19](https://cloud.githubusercontent.com/assets/14153331/22882703/0b1940a8-f1f5-11e6-92b8-3121af62dd4d.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![screen shot 2017-02-13 at 14 01 29](https://cloud.githubusercontent.com/assets/14153331/22882705/116a98ee-f1f5-11e6-874e-d60eec60dca5.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome, Safari
Adguard version: | 1.4.0 (375)

Adguard filters:
<img width="283" alt="screen shot 2017-02-13 at 14 04 47" src="https://cloud.githubusercontent.com/assets/14153331/22882810/9b51fd2c-f1f5-11e6-9ac5-1a115ae34473.png">

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||googleads.g.doubleclick.net/pcs/click$domain=eda.ua
@@||tpc.googlesyndication.com/simgad/*$domain=eda.ua
@@||securepubads.g.doubleclick.net/gampad/ads$domain=eda.ua
@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$domain=eda.ua
@@||eda.ua$generichide
```
