### ISSUE TITLE
www.delcotimes.com - disable ui.ppjol.com/mobile_stop script

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4370]
Hi, here's the original request, please let us know if we can fix it.

> This is https://ui.ppjol.com/mobile_stop needs to be filtered like the way you filter NY times site. I no longer get a warning about the number of free articles on NY times although that was easily beat by clearing the browser cache. This site seems to be a little harder, though. The site is **www.delcotimes.com** although I think it's the https://ui.ppjol.com/mobile_stop which is what stops me from continuing to read articles. Maybe that's the advertising tracker ? 
Anyhow, I need to clear everything in order to use the again and even sometimes that doesn't work.

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Chrome 50.0.2661.89
Adguard version: | 2.8.76
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None
Adguard filters: | 2, 3, 14, 5, 11, 104

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1504125

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. How many articles I have to "read"?
