### ISSUE TITLE
online-buhuchet.ru/buxgalterskij-uchet-obligacij - Annoying pop-up

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4371]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/22926291/a19db44a-f2b4-11e6-962b-33cf52cc5531.png)

</details>

***Steps to reproduce the problem***:

http://online-buhuchet.ru/buxgalterskij-uchet-obligacij/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.1.298 / 1.4.0
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | BlockThirdPartyCookies, BlockThirdPartyCookiesPeriodMin, BlockFirstPartyCookiesMin, BlockBrowserPushApi, BlockBrowserLocationApi, RemoveXClientDataHeader, HideSearchQueries, SendDoNotTrackHeader, RemoveRefererFromThirdPartyRequests
Adguard filters: | Russian filter, English filter, Spyware filter, Social media filter, Annoyances filter 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1460939

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
