### ISSUE TITLE
mazda.hu

### ISSUE THREAD

**Issue by krystian3w** [AdguardTeam/AdguardFilters#43724]
Invalid CSS lines (space after "❗️"):

https://github.com/AdguardTeam/AdguardFilters/blob/ccbcbb6e707a9dff5aebaa1cb63e6913192bb660/AnnoyancesFilter/sections/cookies_specific.txt#L2644 https://github.com/AdguardTeam/AdguardFilters/blob/ccbcbb6e707a9dff5aebaa1cb63e6913192bb660/AnnoyancesFilter/sections/cookies_specific.txt#L2645

**Comment by zloyden** [comment]
Thanks for your reply, fixed.
