### ISSUE TITLE
http://www.glavbukh.ru/art/9990 - Annoying pop-ups

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4372]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/22926758/af7398f8-f2b6-11e6-9697-38bd2b4e8808.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)
http://www.glavbukh.ru/art/9990

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS
Browser: | Chrome
Adguard version: | 6.1.298 / 1.4.0
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | BlockThirdPartyCookies, BlockThirdPartyCookiesPeriodMin, BlockFirstPartyCookiesMin, BlockBrowserPushApi, BlockBrowserLocationApi, RemoveXClientDataHeader, HideSearchQueries, SendDoNotTrackHeader, RemoveRefererFromThirdPartyRequests
Adguard filters: | Russian filter, English filter, Spyware filter, Social media filter, Annoyances filter

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1460939

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
