### ISSUE TITLE
TouchPal

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#4373]
With the last update of TouchPal app ads appear on top of all Windows.

TouchPal should have access to the Internet. The icon on the desktop redirects to a webpage.

<details>

![screen shot 2017-02-14 at 6 14 19 am](https://cloud.githubusercontent.com/assets/25342327/22915266/a45a084a-f27e-11e6-955f-ef914665b5f2.png)

![screen shot 2017-02-14 at 6 14 38 am](https://cloud.githubusercontent.com/assets/25342327/22915146/dd4d388a-f27d-11e6-9761-93ed4da4be7b.png)

![screen shot 2017-02-14 at 6 14 50 am](https://cloud.githubusercontent.com/assets/25342327/22915148/e05acaba-f27d-11e6-8e8e-66b6a7d5e41f.png)

</details>

https://play.google.com/store/apps/details?id=com.cootek.smartinputv5&hl=en

Filters 2, 3, 4, 14, 1, 11
versionName : 2.8.76
androidVersion : 5.1

Customer ID 670455

**Comment by Alex-302** [comment]
Can't reproduce. I see only FB ads when Adguard is disabled.

**Comment by Bohdan-SUP** [comment]
From user "Когда включены уведомления вылазит реклама. При отключения уведомлений этому приложению вслывающая реклама пропадает. "

**Comment by Alex-302** [comment]
У меня уведомления не запрещены.
Попроси пошаговое описание как повторить. Может какое-то действие нужно проделать.

**Comment by Bohdan-SUP** [comment]
Попросил. У меня тоже не повторилось.

**Comment by Alex-302** [comment]
ок, ждём

**Comment by deLumren** [comment]
User 1543970 also complains about ads in this app.
There are HTTPS logs with timestamp and screenshots in his ticket.

**Comment by Alex-302** [comment]
Лог начинается в 19:22, видно только, что фаервол заблокировал доступ в сеть.
Нужен лог ***HTTP*** запросов, а не полный, с предварительной очисткой кэша того приложения и его остановкой.

**Comment by evgeniy-ADG** [comment]
Не хотим слать, сделали рефанд уже.
