### ISSUE TITLE
https://www.basicthinking.de/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4375]
https://www.basicthinking.de/blog/advertisment

Blocked by the content blocker:

![file_000](https://cloud.githubusercontent.com/assets/15856304/22966162/9e79f12e-f369-11e6-827a-0c0e142fb30e.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Chrome
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | 2 3 4 6 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1503856

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||basicthinking.de/blog/advertisment/
```
