### ISSUE TITLE
https://m.kufar.by/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4376]
The link: [link](https://m.kufar.by/list?w=3&ca=&cg=5030&st=s&cnr=&cmptp=9&cmdtp=&cmdtfs=&cmdtfe=&cmdtr=&cmdtht=&cmdthv=&cmdtvc=&cmmnb=&cmmnd=&cmmnp=&cmmnfs=&cmmnfe=&cmmnr=&cmmnht=&cmmnhv=&cmltb=&cmltd=&cmltrs=&cmltp=&cmltfs=&cmltfe=&cmltrm=&cmltht=&cmlthv=&cmltv=&cmltuc=&cmdpb=&cmdpd=&cmdpr=&cmdpmt=&cmdpi=&cmcpt=17&cmast=&o=10)

![image2](https://cloud.githubusercontent.com/assets/15856304/22966289/2f558d70-f36a-11e6-9022-cc76dad56b28.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | 2 3 4 14 1 11 12 213 212

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1416621

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
not reproduced on my device. Which filter causes it?
