### ISSUE TITLE
m.delfi.lt - placeholders

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4377]
Web page m.delfi.lt: if you open any article, there is a white space being left after the ad is removed, like on the screenshot below (under the first paragraph):

<details>

With ad:
![image](https://cloud.githubusercontent.com/assets/15856304/22967083/ab6f0ca8-f36d-11e6-9052-c68bca636555.png)

Without ad:
![image](https://cloud.githubusercontent.com/assets/15856304/22967094/b7326454-f36d-11e6-8d7c-f1c2e0210554.png)

</details>

these were an iPad screenshots, here's how it looks on iPhones:

<details>

![image1](https://cloud.githubusercontent.com/assets/15856304/22967119/cf64a744-f36d-11e6-8960-f2a588a13a54.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | the current one
Simplified filters(iOS) | Off
Adguard DNS: | None 
Adguard filters: | 2 3 4 11 12 110

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1398913

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
