### ISSUE TITLE
gamekings.tv 

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#4379]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
http://www.gamekings.tv/videos/sniper-elite-4-review/

* **Current behaviour**: 
It asks to disable adblocking on the page :(

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-02-15 at 16 34 00](https://cloud.githubusercontent.com/assets/14153331/22978747/a35056c4-f39c-11e6-80bb-167f87983be4.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | checked on Android / Mac OS
Browser: | Chrome
Adguard version: | 2.8.76/1.4.0
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default mode)
Adguard DNS: | None

**Adguard filters:**
![screen shot 2017-02-15 at 16 37 35](https://cloud.githubusercontent.com/assets/14153331/22978877/1524319e-f39d-11e6-8a04-3fadbe1237a6.png)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1492862

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed

**Comment by Alex-302** [comment]
Please check it. Detection like on your screenshot was not reproduced, only grayscale video.

**Comment by Bohdan-SUP** [comment]
Alright, will check after the filter update goes live.
This is the part of a greyscale video :)

**Comment by Alex-302** [comment]
@Bohdan-SUP проверь, чтоб обновления не ждать
```
gamekings.tv#@#.afs_ads
```

**Comment by Bohdan-SUP** [comment]
@Alex-302 works!
на будущее - я могу с коммита вручную правила проверять?

**Comment by Alex-302** [comment]
канеш

![image](http://s8.hostingkartinok.com/uploads/images/2017/02/22c3f73e78e9bc2ff1ab462c17ef34ab.png)
