### ISSUE TITLE
www.moscow.regnews.info - missed ads

### ISSUE THREAD

**Issue by oprotsyk** [AdguardTeam/AdguardFilters#4380]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***www.moscow.regnews.info***:
* **ads are not blocked with Adguard for Android**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

![image](https://cloud.githubusercontent.com/assets/25342327/23014281/f4ccb408-f436-11e6-9871-9297fb7d90d5.png)

![screen shot 2017-02-16 at 11 00 45 am](https://cloud.githubusercontent.com/assets/25342327/23014345/43e77794-f437-11e6-88dd-4521bf484f35.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

No ads should be there

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

Go to https://www.moscow.regnews.info/v-podmoskove-podpolkovnik-policii-zaderzhan-za-vzyatku

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Browser: | Chrome
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Simplified filters(iOS) | On / Off
Adguard filters: | 2, 3, 4, 14, 1, 11, 211 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1150428

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
