### ISSUE TITLE
http://b2.ijquery11.com/cs?wsa=589f8a3f7e025965260888 - Ads website pop-up

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4382]
***Description***:

http://b2.ijquery11.com/cs?wsa=589f8a3f7e025965260888 - another website with ads is popping-up

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/23026576/5cbc9640-f46a-11e6-8f4a-c67564bd7af1.png)

</details> 

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.1.298 / 1.4.0
Adguard driver (Windows): | TDI
Stealth mode options(Windows) | BlockThirdPartyCookies, BlockBrowserLocationApi, RemoveXClientDataHeader, HideSearchQueries, SendDoNotTrackHeader
Adguard filters: |English filter, Spyware filter, Filter unblocking useful ads, Russian filter, User filter: no_url

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1505236

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@KozelElena спроси, может юзер помнит, на каком сайте открылся b2.ijquery11.com. Просто так b2.ijquery11.com мочить не стоит.

**Comment by ArleneDe** [comment]
Any new browser extensions you may need to disable/remove? Malicious browser add-ons and programs can result in unwanted browser redirects. You may need this [removal guide](http://www.icleansoftware.com/b2-ijquery11-com-removal-guide-for-windows/) in which redirect virus removal tool is available too.

**Comment by Alex-302** [comment]
Added to English filter
```
||b2.ijquery11.com^
```
