### ISSUE TITLE
ES File Explorer - ads 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4383]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Facing ads in ES File Explorer

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/23032115/1b7a6b1e-f47c-11e6-858e-26174895a0bf.png)

</details>

***Steps to reproduce the problem***:

https://play.google.com/store/apps/details?id=com.estrongs.android.pop&hl=en

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.8
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard filters: | English, Spyware, Social media, Annoyances, Russian, Mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1500802

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
That banner is blocked on my side. Which ad system is used here?

**Comment by Alex-302** [comment]
Blocked a lot of analytics used by this app.

**Comment by seanl-adg** [comment]
Not reproduced on my end too.
