### ISSUE TITLE
https://mobilitymag.de/werbung/ - incorrect blocking

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4384]
https://mobilitymag.de/werbung/

Blocked by the content blocker:

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![-qneurrtvyy](https://cloud.githubusercontent.com/assets/22892774/23033052/59860e6a-f47f-11e6-9421-417507754956.jpg)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | None 
Adguard filters: | http://prnt.sc/e9krkc

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1503856 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||mobilitymag.de/werbung/
```
