### ISSUE TITLE
Блок рекламы

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#4386]
Буду краток (привет @Alex-302). Фильтры по-умолчанию, Фильтрация качественная HTTPS. Версия последняя с телефона. Чтобы проблема воспроизвелась нужно подождать 1 мин
http://www.online-life.cc/9690-samyy-luchshiy-den-2015.html
http://savepic.ru/12926048.png

**Comment by Alex-302** [comment]
это уже исправляли вчера

**Comment by ministr91** [comment]
Я не согласен с тем, что исправление было внесено в английский фильтр. Просьба перенести в русский фильтр

**Comment by Alex-302** [comment]
при чём тут английский фильтр?

**Comment by ministr91** [comment]
Я зашел на сайт и проблема была. Зашел в программу, обновились фильтры - английский тока и проблема исчезла

**Comment by ministr91** [comment]
Куда были изменения внесены? Можешь ссылку кинуть?

**Comment by ministr91** [comment]
Хватит игнорить, @Alex-302

**Comment by ministr91** [comment]
Уже месяц жду
