### ISSUE TITLE
wow-forum.com - Ad - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4388]
***Site***: http://www.wow-forum.com/de/59483-habt-heute-wow-gemacht-erreicht.html
***Description***: Ad leftover at the top. Ad post.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/23064645/7925109e-f511-11e6-99d0-6b711e65cdb5.png)

![image](https://cloud.githubusercontent.com/assets/10995998/23064560/043cd42e-f511-11e6-8853-f691db40ce9c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.9.51
Spyware filter | 1.0.10.72
Social media filter | 1.0.17.30
Annoyances filter | 1.0.10.15
German filter | 1.0.31.42
Mobile ads filter | 1.0.7.9
Safari filter | 1.0.2.50

**Comment by Alex-302** [comment]
fixed

**Comment by danidoedel** [comment]
@Alex-302 Ad post is still there.
