### ISSUE TITLE
Google AMP ad blocking issues

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4389]
***Description***: On mobile devices Google provides many links to their AMP site of various other sites on which ad blocking does not work as on the original pages. Not sure if that is something which can be fixed... I hope so though.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/23065127/3a08d712-f514-11e6-88fb-931eccbf3ff4.png)

![image](https://cloud.githubusercontent.com/assets/10995998/23065115/291ae2ec-f514-11e6-985b-1300566cf227.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Browser: | Safari
Adguard version: | 1.1.5
Adguard driver (Windows): | -
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | -

Adguard filter | Version
--- | ---
English filter | 1.1.9.51
Spyware filter | 1.0.10.72
Social media filter | 1.0.17.30
Annoyances filter | 1.0.10.15
German filter | 1.0.31.42
Mobile ads filter | 1.0.7.9
Safari filter | 1.0.2.50

**Comment by seanl-adg** [comment]
Added a fix for zeit.de. Please let the user report each individual page with its full url.
