### ISSUE TITLE
radio-internetowe.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#43915]
**Site Sample** | 
----------------|
https://www.radio-internetowe.com/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1903 x64 (lastest)
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.3 nightly X (XXXX)** 
Stealth Mode:					       | disabled
Chrome Extension: | [Polska Ciasteczkowa Zgoda - extra JS scripts blocking EU GDPR annoyances on polish websites](https://chrome.google.com/webstore/detail/polish-cookie-consent/bniijddcmabghibaojbkbnngbedopbno) 
Chrome Extension: | [AdGuard Adblocker Extension - Integration Mode](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg) 

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| FuckFuckAdblock
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

Cookie

<details><summary><b>Screenshot:</b></summary>

![20191112-1573545384-001](https://user-images.githubusercontent.com/9846948/68652821-9b455900-052a-11ea-840c-e5983894c033.png)
![20191112-1573545407-001](https://user-images.githubusercontent.com/9846948/68652822-9b455900-052a-11ea-86a2-87eb3676fef2.png)

</details><br/>

@AdamWr @Alex-302

**Comment by zloyden** [comment]
The site has low visitors. You can add the rule in User's filter: `radioemu.com#?#body > div[id]:has(> div:contains(plików cookie))`

**Comment by FadeMind** [comment]
CC @krystian3w dodałbyś u siebie? :> Dzięki ;)

**Comment by krystian3w** [comment]
Na Dev już w EI / u Majkiego może dzisiaj +3h dla serwerów AdGuarda.

Potem ocenię konieczność sprawdzania w środku elementu słowa "cookies".
