### ISSUE TITLE
kleiderkreisel.de - iOS - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4392]
***Site***: https://www.kleiderkreisel.de/app
***Description***: App store link is blocked.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/23065427/dd9e621a-f515-11e6-9edf-74b9ce50ac53.png)

![image](https://cloud.githubusercontent.com/assets/10995998/23065420/d6eae5c4-f515-11e6-9615-4cf163e070f9.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.9.51
Spyware filter | 1.0.10.72
Social media filter | 1.0.17.30
Annoyances filter | 1.0.10.15
German filter | 1.0.31.42
Mobile ads filter | 1.0.7.9
Safari filter | 1.0.2.50****

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||app.adjust.io/*&utm_source=desktop_kleiderkreisel.de
```
