### ISSUE TITLE
http://www.penzainform.ru/ - missed ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4393]
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-02-17 at 5 02 07 pm](https://cloud.githubusercontent.com/assets/22892774/23070198/f3e6f7ea-f532-11e6-8f12-e81148eaf62c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Yandex
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP 
Adguard filters: | http://prnt.sc/e9y2s2

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1343340

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||b13.penzainform.ru^
penzainform.ru##li[style="width: 140px; height: 280px; max-height: 280px;"]

```
