### ISSUE TITLE
cucudas.com/ - incorrect blocking 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4394]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: cucudas.com/ - incorrect blocking 
* **Current behaviour**: can't open the menu with enabled Adguar

Screenshot:
http://prnt.sc/e9yuim
http://prnt.sc/e9ysmh

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5
Optimazed enabled: YES
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.9.30 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.70 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.27 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.1 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.7.7 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.47 Enabled=YES
ID=224 Name="Korean Adblock List" Version=1.0.0.3 Enabled=YES
ID=227 Name="List-KR" Version=1.0.2.17 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1502301

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Should be fixed now.
