### ISSUE TITLE
lostfilm.tv - enabling "Antitracking" option blocks downloads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4395]
***Steps to reproduce the problem***:
 
Go to lostfilm.tv - choose the movie, try to download "torrent" file with Antitracking module enabled

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Opera
Adguard version: | AppVersion: 6.1.298.1564
Adguard driver (Windows): | WFP 
Adguard filters: | http://prnt.sc/ea1y7a  ;  http://prnt.sc/ea1yge

**Stealth mode options(Windows) |**  

"BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "BlockBrowserPushApi": true,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": true,
  "HideUserAgent": true,
  "CustomUserAgent": "Mozilla/5.0 (X11; Linux i586; rv:31.0) Gecko/20100101 Firefox/47.0",
  "CustomReferer": null,
  "HideIp": true,
  "CustomIp": "195.210.130.16"

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 728879

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||tracktor.in/td.php?s=$stealth
```
Please check it.
