### ISSUE TITLE
http://pattaya.orthodox.or.th/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4396]
With Adguard
![image](https://cloud.githubusercontent.com/assets/15856304/23091947/95328b14-f5c9-11e6-94ae-ae4fa22be457.png)

Without Adguard (the icons and are falsely blocked)
![image](https://cloud.githubusercontent.com/assets/15856304/23091944/8c5f93d8-f5c9-11e6-92f5-1cd35fac6496.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4
Adguard DNS: | None
Adguard filters: | eng, ru, social media, annoyances, safari

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1505965

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
orthodox.or.th#@#.sidebaradbox
```
