### ISSUE TITLE
https://www.theatlantic.com/ - social media widget

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4397]
![image1](https://cloud.githubusercontent.com/assets/15856304/23092107/72518da4-f5cc-11e6-84dc-3387c0555561.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | the latest one
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | eng, annoyances, social media, safari, russian

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1505282

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added:
```
theatlantic.com##nav#action-bar
theatlantic.com##.ad-loaded
theatlantic.com##.native-promo-slider
```
also please check for ad block detection
