### ISSUE TITLE
Ads on the start page in Opera

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#43975]
Is it something we can block? 

![image](https://user-images.githubusercontent.com/15856304/68751136-c2268c80-0609-11ea-88e6-c6375b6d43d0.png)

AppVersion: 7.2.2936
Windows NT 10.0.18362.0
Driver Type: Wfp
HTTPS filtering enabled: True
Subscriptions: AdGuard Russian, AdGuard Base, AdGuard German filter, ABPindo, EasyList China, EasyList Czech and Slovak, Liste FR, Wiltteri, Icelandic ABP List, Official Polish filters for AdBlock, uBlock Origin & AdGuard

**Comment by BlazDT** [comment]
Probably only with DNS since no request is intercepted on apps and extensions. Not showing ads here though.

**Comment by Alex-302** [comment]
@Eugene-Savenko это разве Опера?

**Comment by krystian3w** [comment]
Adguard 7.X (Windows) / 2.6.5 (macOS) no see this?

**Comment by Eugene-Savenko** [comment]
@Alex-302 ну, вроде как да... судя по логу. мы попробуем воспроизвести у себя и чуть позже ответим.

**Comment by Alex-302** [comment]
Ок, жду.

**Comment by Alex-302** [comment]
@Eugene-Savenko ну что там?
