### ISSUE TITLE
Again e.mail.ru

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardFilters#43989]
Ads penetrates while browsing mail.ru. Below attached are screenshot and technical info

https://photos.app.goo.gl/bL4FwaA5W6a9i3kK7

Operating system:                      Windows 10 v.1909 x64
Browser:                               Google Chrome, Version 78.0.3904.97 (Official Build) (64-bit)
AdGuard version:                       Chrome plugin, Version 3.3.2

Filters enabled:                       |   AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Experimental filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter 

AdGuard DNS:                           |  Default 
Stealth mode options (Windows only)    |  On

**Comment by zloyden** [comment]
Switch to a new design, there is no ads. Also you need to install [this script](https://github.com/AdguardTeam/AdguardFilters/issues/42967#issuecomment-547845610) via `Tampermonkey`.
@Alex-302 please take a look.

**Comment by jbionic2016** [comment]
**zloyden**, What do you mean by "switching to a new design"?? How do I do this?

**Comment by zloyden** [comment]
I meant [it](https://help.mail.ru/mail-help/faq/new), please check.

**Comment by jbionic2016** [comment]
Shall I take your answer as if you were not going to move a finger unless I switch to a new interface which I don't like? :-)

**Comment by jbionic2016** [comment]
zloyden, YMF, I can't return Old view now, thanks to your advice..

**Comment by BlazDT** [comment]
Left ads are hidden by e.mail.ru###leftcol-banners for me (ad mail too - e.mail.ru##.adman-line). Above the mails I did find a car fine ad, which I fixed (hiding #announcement was a bit too risky).

**Comment by jbionic2016** [comment]
So Adguard guys seem to be in the same boat with mail.ru since they push other folks to switch to a new interface, which makes very little sense but justifies the cost of re-development... :-)

**Comment by zloyden** [comment]
We were fixed these ads for both designs, that's why I asked you to test it. According the article you can return old design by following instruction.
What is your version of script? With `AdGuard Extra 1.0.45` it's not reproduced.

**Comment by jbionic2016** [comment]
> e.mail.ru##.adman-line

I've tried adding both of your suggested rules in User filter, but the result is void as can be seen from below shot..
https://photos.app.goo.gl/grHmtYzELx5dkDdq7

**Comment by BlazDT** [comment]
Only seeing ads on the left side and not the right when I disable AdGuard.

**Comment by jbionic2016** [comment]
> We were fixed these ads for both designs, that's why I asked you to test it. According the article you can return old design by following instruction. What is your version of script? With AdGuard Extra 1.0.45 it's not reproduced.

I was naive enough to trust youк advice without even reading about the consequences, which are..
https://photos.app.goo.gl/VyMQsCBqfY6nhoFJ9

**Comment by Alex-302** [comment]
Please enable AdGuard Extra in AdGuard settings.

---

Browser extension users should to install `AdGuard Extra` script into `Tampermonkey` extension.

`AdGuard Extra` download link:
https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js

After install `Tampermonkey`, change these options like on screenshot:
![image](https://user-images.githubusercontent.com/8361299/68199152-23c17800-ffc6-11e9-99f2-13643aa771ae.png)


![image](https://user-images.githubusercontent.com/8361299/62641299-f7a54500-b94b-11e9-8a83-885d89abbeec.png)

![image](https://user-images.githubusercontent.com/8361299/68200995-a3047b00-ffc9-11e9-9999-cdcf35a0f750.png)

**Comment by jbionic2016** [comment]
Alex, thanks, it helped. Any chance we may cope with Ads without having TM enabled in the near future? :-) I guess, you DO realize that the complexity of a solution decreases the number of its users?

**Comment by Alex-302** [comment]
They bypasses AdGuard. AG Extra works in a different way.

**Comment by jbionic2016** [comment]
The same issue persists. Despite the fact I have the latest version of Adguard Extra script. Check the pics attached

![111](https://user-images.githubusercontent.com/23212486/74359422-4ab4f480-4dd4-11ea-9615-c7094a43a361.jpg)
![222](https://user-images.githubusercontent.com/23212486/74359427-4ee11200-4dd4-11ea-90ea-e7b40b576b96.jpg)
