### ISSUE TITLE
https://meduza.io/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4398]
The link: https://meduza.io/shapito/2017/02/16/fantast-nik-perumov-porugalsya-s-pisatelem-leonidom-kaganovym-iz-za-sobytiy-10-letney-davnosti-kotoryh-ne-bylo?utm_source=email&utm_medium=vecherka&utm_campaign=2017-02-16

<details>

without adg:

![img_0236](https://cloud.githubusercontent.com/assets/15856304/23092376/3becb896-f5d2-11e6-9278-4b939b9cfb28.png)

with adg:

![img_0237](https://cloud.githubusercontent.com/assets/15856304/23092378/48948ec0-f5d2-11e6-940d-2145449cee18.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.40
Simplified filters(iOS) | Off
Adguard DNS: | Default
Adguard filters: | 1 2 3 4 12 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1142623

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed in social filter
