### ISSUE TITLE
Hide your User-Agent option breaks the Google sync feature

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4399]
Hide your User-Agent option causes Google Chrome's sync feature to prompt the user for a passphrase and disables sync. It also causes some pictures on websites to not display properly

![image](https://cloud.githubusercontent.com/assets/15856304/23092975/61324e42-f5df-11e6-884e-2e50e6b9453c.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows NT 6.1.7601 Service Pack 1
Browser: | Chrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Stealth mode options(Windows) | On
Adguard filters: | 2 3 4 11 101 103 118 122 123 204 208 210 211 214 215 216 14 15

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1503006

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@evgeniy-ADG 
check this rule
```
@@||clients4.google.com/chrome-sync/$stealth
```
If it works, close as resolved. Added to Eng filter.
