### ISSUE TITLE
http://zangsisi.net/  missed ads

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4402]
http://zangsisi.net/  missed ads

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/23095751/d943d242-f617-11e6-9095-dfdfd9c15dfb.png)

Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.0

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1506615

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Should be fixed now
