### ISSUE TITLE
Feature request: filter for audio ads

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4403]
Feature request: filter for audio ads

Operating system: | Windows / Mac OS / Android / iOS

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1506102

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I need example link.

**Comment by evgeniy-ADG** [comment]
the original email:

>Trying to block this adserving URL
http://www.accuradio.com/sweeper/json/fetch/?c=sweeper&toid_next=4e38545277d9e742560253ed&p=midroll&ucoid=4e38561e77d9e74636000028&pslot=19&s=2014&u=616292973&toid_prev=4e38545077d9e7425602510e&cb=976806&device=desktop&offset=0
If i add just *sweeper* to ublock origin it works perfectly. I have
tried to add them tou your filters, but they still get through.

**Comment by Alex-302** [comment]
AG app or extension?

**Comment by evgeniy-ADG** [comment]
Adguard app v. 6.1.312.1629, Windows 10. Filters: 2 / 101 / 214 / WFP / Stealth Mode

**Comment by Alex-302** [comment]
It is fixed, but for the app only. Ask user about audio ad.
