### ISSUE TITLE
vidlox.tv/fb394na1qhq6

### ISSUE THREAD

**Issue by DopeUnicorn** [AdguardTeam/AdguardFilters#4404]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
![screen shot 2017-02-19 at 07 22 05](https://cloud.githubusercontent.com/assets/25641172/23099638/8f23af36-f674-11e6-9230-62e83c441438.png)

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | IOS 10.2.1
Browser: | Safari
Adguard version: |1.1.5.65 
Adguard driver (Windows): | 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): |  
Simplified filters(iOS) |  Off
Adguard DNS: | None 
Stealth mode options(Windows) | 
Adguard filters: | ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.9.58 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.73 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.33 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.10.18 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.7.10 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.51 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.46 Enabled=NO
ID=101 Name="EasyList" Version=1.0.67.95 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.74.79 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.65.80 Enabled=NO
ID=122 Name="Fanboy's Annoyances" Version=1.0.68.17 Enabled=YES
ID=109 Name="EasyList Italy" Version=1.0.74.78 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.2.63 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.74.94 Enabled=YES
ID=217 Name="Adblock polskie reguły cookies" Version=1.0.1.27 Enabled=NO
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=NO
ID=220 Name="CJX's Annoyance List" Version=1.0.0.87 Enabled=NO
ID=229 Name="I dont care about cookies" Version=1.0.0.12 Enabled=YES
ID=227 Name="List-KR" Version=1.0.1.41 Enabled=NO
ID=208 Name="Malware Domains" Version=1.0.71.30 Enabled=NO
ID=204 Name="Peter Lowe's list" Version=1.0.2.46 Enabled=NO
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.65 Enabled=NO
ID=206 Name="Xfiles" Version=1.0.0.60 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1506588

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
