### ISSUE TITLE
P&N Bank app - blocked by the DNS filtering

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4405]
P&N Bank: https://itunes.apple.com/au/app/p-n-banking-app/id945287091?mt=8

The VPN appears to either block my the app or triggers a redirect security on their end
Whitelisting this domain fixed the problem: h-sdk.online-metrix.net

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10,3
Browser: | 
Adguard version: | 1.1.5.40
Simplified filters(iOS) | Off
Adguard DNS: | Default
Adguard filters: | 1 2 3 4 12 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1504494

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
```
h-sdk.online-metrix.net
```
added to DNS filter

**Comment by Alex-302** [comment]
Please check it without whitelisting tomorrow.
