### ISSUE TITLE
http://www.fox.com.tr adblock detected

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4406]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Webiste detects adblocker

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot: http://prntscr.com/eapqyg

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS 
Browser: | Chrome
Adguard version: | 1.4.0 

Adguard filters: | 1,2,3,4,5,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 461686

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
not reproduced with Turkish filter.
