### ISSUE TITLE
ESPN app - blocking ad breaks radio/podcast

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4407]
Details:
https://forum.adguard.com/index.php?threads/espn-radio-stops-playing.19608/

It might be a tricky one. Check if we can use $replace rule to get rid of ESPN app ads.

Please, comment on the forum thread once the issue is resolved.

**Comment by seanl-adg** [comment]
I think we have to wait until https://github.com/AdguardTeam/AdguardForAndroid/issues/1060 is implemented.

**Comment by ameshkov** [comment]
Ah, got it, thank you!

**Comment by Alex-302** [comment]
@seanl-adg *bump*
