### ISSUE TITLE
http://gidonline.club missed ads

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4408]
***Description***:http://gidonline.club missed ads
Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/23106814/c52033b6-f6fb-11e6-8e36-f7a8684aa42f.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.1.312.1629 / mac 1.4.0
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | enabled
Adguard filters: | user, English, Russian, annoyance, spyware, social, mobile, malware domains, spam 404

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1065535

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It was fixed yesterday
