### ISSUE TITLE
easycredit-bbl.de - Ad leftover - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4409]
***Site***: http://www.easycredit-bbl.de/de/
***Description***: Some ad leftovers and partners ad at the end of the page.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/23108009/a1d51f92-f706-11e6-8555-3e685c028b92.png)

![image](https://cloud.githubusercontent.com/assets/10995998/23108012/ae374422-f706-11e6-8828-4717c02bc215.png)

![image](https://cloud.githubusercontent.com/assets/10995998/23108015/b983b608-f706-11e6-9d71-44ed2e332673.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.9.78
Spyware filter | 1.0.10.73
Social media filter | 1.0.17.37
Annoyances filter | 1.0.10.21
German filter | 1.0.31.43
Mobile ads filter | 1.0.7.11
Safari filter | 1.0.2.53

**Comment by Alex-302** [comment]
easycredit-bbl.de##.partners
easycredit-bbl.de##.box.cad
easycredit-bbl.de##.frontpage_advertisement
