### ISSUE TITLE
otto.de - Incorrect Blocking - iOS

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4410]
***Site***: https://www.otto.de/
***Description***: App Store and Google Play Store links don't work on iOS devices.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/23108036/1923c2c4-f707-11e6-831b-4855f0b4ae87.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.9.78
Spyware filter | 1.0.10.73
Social media filter | 1.0.17.37
Annoyances filter | 1.0.10.21
German filter | 1.0.31.43
Mobile ads filter | 1.0.7.11
Safari filter | 1.0.2.53

**Comment by Alex-302** [comment]
they are blocked by annoyances filter

**Comment by danidoedel** [comment]
So no chance to unblock them?

**Comment by Alex-302** [comment]
No.
