### ISSUE TITLE
zalando.de - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4411]
***Site***: https://m.zalando.de/
***Description***: App Store link doesn't work.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/23108045/65ccea42-f707-11e6-9ca8-12b171cb6f34.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.9.78
Spyware filter | 1.0.10.73
Social media filter | 1.0.17.37
Annoyances filter | 1.0.10.21
German filter | 1.0.31.43
Mobile ads filter | 1.0.7.11
Safari filter | 1.0.2.53

**Comment by Alex-302** [comment]
not Incorrect Blocking. These buttons blocked by annoyances filter.

**Comment by danidoedel** [comment]
Why are they still there then? Better remove these buttons then to prevent confusion?

**Comment by Alex-302** [comment]
I don't see this button.

**Comment by danidoedel** [comment]
I do see these buttons. On my computer and iOS devices.

**Comment by Alex-302** [comment]
show me the code of this button, or the rule.
