### ISSUE TITLE
breuninger.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4412]
***Site***: https://www.breuninger.com/
***Description***: Cookie notice at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/23108057/9f450778-f707-11e6-92ca-e6e50e981245.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.9.78
Spyware filter | 1.0.10.73
Social media filter | 1.0.17.37
Annoyances filter | 1.0.10.21
German filter | 1.0.31.43
Mobile ads filter | 1.0.7.11
Safari filter | 1.0.2.53

**Comment by Alex-302** [comment]
fixed
