### ISSUE TITLE
contextmenu

### ISSUE THREAD

**Issue by bogachenko** [AdguardTeam/AdguardFilters#44132]
`https://vfilmesonline.net/v/wjdn1snq4346q30/` 
How to remove this godless context menu by returning the native context menu for `frame`
**Without the help of third-party extensions/applications and digging into the subtle settings of the browser. Only with the help of your extension can this be removed?**

bump @Alex-302 @Sergey-Lyapin @BlazDT @tvinzz @zloyden @AdamWr @slavaleleka @PentagramTr 

![ыф](https://user-images.githubusercontent.com/8535285/68937362-56524880-07f0-11ea-8315-ac0d14508574.png)

**Comment by zloyden** [comment]
Add the rule in User filter: `vfilmesonline.net##.jw-rightclick`

**Comment by bogachenko** [comment]
@zloyden ты вопрос вообще читал?

**Comment by AdamWr** [comment]
I guess this rule should returns native context menu:
`vfilmesonline.net#%#window.addEventListener("contextmenu",function(a){a.stopPropagation()},!0);`

**Comment by bogachenko** [comment]
@AdamWr nice
