### ISSUE TITLE
www.rodwatches.ch - Parental control false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4415]
This is a switch watches site but for some reason, it's in the parental control filter.

http://family.block.dns.adguard.com/?domain=www.rodwatches.ch

![image](https://cloud.githubusercontent.com/assets/15856304/23116030/06b3bf1e-f751-11e6-84ff-6610206babc2.png)

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Adguard DNS: | Family Protection

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1021351

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@zebrum please take a look

**Comment by zebrum** [comment]
fixed
