### ISSUE TITLE
adblock.ro filter

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4416]
Want to inform this is a new Romanian filter list https://www.adblock.ro/, on our website you can find all details, may need to use translation tools because is written in Romanian. This is a Public list, and anyone can contribute on our GitHub open project.

Our Website: https://www.adblock.ro/ 
Github Project: https://github.com/tcptomato/ROad-Block

**Comment by ameshkov** [comment]
Add ROad-Block to the list of available filters.

Btw, is ROList abandoned? If so, we should make this filter default for Romanian users.

**Comment by elaur** [comment]
There is just a snippet from my email, this is the rest and the true answer about ROlist.

> There may be another one filter list on the internet like “ROList” but you have to know the owner of ROList filter is keeping this list private and don’t want to add on the list his own website, friends website and some romanian advertise networks where he is publisher, so by that one year ago has been released ROad-Block to give freedom to anyone who want to add something on the list.

**Comment by Alex-302** [comment]
It is added.
