### ISSUE TITLE
http://www.igen.fr/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4417]
http://www.igen.fr/

No content appears when I load the page: 

<details>

![fullsizeoutput_851](https://cloud.githubusercontent.com/assets/15856304/23117869/6ddd50e8-f75a-11e6-903b-de586af6307e.jpeg)

</details>

When I reload the page without content-blocking, the content (and ads) appears: 

<details>

![fullsizeoutput_852](https://cloud.githubusercontent.com/assets/15856304/23117871/734be184-f75a-11e6-8bb0-5fd66a607751.jpeg)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | 2 3 4 12 113

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1460201

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It works fine on my device with Safari filter.
Check this rule:
```
@@||igen.fr/sites/www.igen.fr/files/advagg_js/
```
