### ISSUE TITLE
mail.yahoo.com Printing from yahoo mail with AdGuard adds a large cross item to the printed letter

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#44184]
It does not happen with the Base filter disabled (needs to be doubly checked though). This occurs on Windows and macOS as well.
<details> <summary> with adguard </summary>

![image](https://user-images.githubusercontent.com/15856304/68992634-a2e06700-0876-11ea-8119-8fb485d80000.png)

</details>

<details> <summary> without adguard </summary>

![image](https://user-images.githubusercontent.com/15856304/68992740-fd2df780-0877-11ea-87bd-c771c0b4e725.png)

</details>

AdGuard for Mac v. 2.2.2.652
Base, Tracking, Annoyances, Russian, Social media filters
Firefox Quantum 69.0.1 (64-bit

**Comment by Alex-302** [comment]
Not reproduced on my device
![image](https://user-images.githubusercontent.com/8361299/69010028-c1705c00-0963-11ea-8081-4fc5ecb25b80.png)
Is it caused by filters or AG extensions?

**Comment by Eugene-Savenko** [comment]
You have to select a message and hit the printer item:

![image](https://user-images.githubusercontent.com/15856304/69012736-c0e6be00-0981-11ea-9710-ff497d5b1f4e.png)

It's caused by the Base filter - I can print without any issues when I disabled it. I also tried turning the extensions off, but that didn't change anything.

**Comment by Alex-302** [comment]
Reproduced.

**Comment by Alex-302** [comment]
Filed a bug https://github.com/AdguardTeam/CoreLibs/issues/1193
@Eugene-Savenko for custom filter `@@||mail.yahoo.com^$elemhide`
