### ISSUE TITLE
dizilab.tv

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#4418]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-02-20 at 18 23 39](https://cloud.githubusercontent.com/assets/14153331/23133614/6468de7a-f79a-11e6-8832-85dac536daac.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | checked on Mac OS
Browser: | Safari 10, Chrome
Adguard version: | 1.4.0 (374)
Adguard DNS: | None

Adguard filters:
![screen shot 2017-02-20 at 18 25 25](https://cloud.githubusercontent.com/assets/14153331/23133576/479bc29e-f79a-11e6-9466-f0922aff24f5.png)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1507198

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
