### ISSUE TITLE
zobacz.ws

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#44198]
**Site Sample** | 
----------------|
http://zobacz.ws/tvn-24

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Firefox x64 (lastest)
AdGuard version:                       | **7.3 nightly (lastest)** 
Stealth Mode:					       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| FuckFuckAdblock
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:
ESET scream about some danger, PDF FILE inject?

<details><summary><b>Screenshot:</b></summary>

![20191116-1573926729-001](https://user-images.githubusercontent.com/9846948/68997049-5579ef00-08a2-11ea-9204-30bf7875abd9.png)

![20191116-1573926758-001](https://user-images.githubusercontent.com/9846948/68997050-5579ef00-08a2-11ea-9a82-11e460378c80.png)

</details><br/>

@AdamWr @Alex-302

**Comment by Alex-302** [comment]
Probably false positive. Please write message to Eset support. I see packed script, but is is for ads.

**Comment by Alex-302** [comment]
And Virustotal report:
https://www.virustotal.com/gui/url/d58e9f35167943a29acf4dbb8e3bd38a84d689026d6ddc999d08959eb027e364/detection

**Comment by FadeMind** [comment]
@Alex-302  this issue happen on some minor other sites too (eset scream out and blocked site with HTML/ScrInject.B danger. 

`https://ekinomaniak.net/`
![20191117-1574007918-001](https://user-images.githubusercontent.com/9846948/69010356-3f7e3400-095f-11ea-94df-394acc779834.png)

I can open zobacz.ws cause I excluded domain from scanning. 
Seems ESET looking for specify code and identify as trojan thread.

**Comment by Alex-302** [comment]
@FadeMind `HTML/ScrInject.B` is not a trojav or virus. This is redirect/popup script, which redirects user to a dangerous site
https://forum.esetnod32.ru/forum33/topic13791/ (use google translate)
