### ISSUE TITLE
Tuttomercatoweb & Milannews app

### ISSUE THREAD

**Issue by Calwinpok** [AdguardTeam/AdguardFilters#44202]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: ads are not blocked using the android apps of these two sites, also a video starts. 
* **Current behaviour**: one videoad per session, ad areas in the articles are not blocked. 
https://github.com/AdguardTeam/AdguardFilters/issues/38634

[//]: # (Substitute this line with a description of the problem)

<details><summary>Screenshot:
https://ibb.co/yhQhLSf
https://ibb.co/8xmdcqk
</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://ibb.co/yhQhLSf) 
![image](https://ibb.co/8xmdcqk) 
</details><br/>

***Steps to reproduce the problem***:

# opening the apps tuttomercatoweb or Milannews shows the same issue. Opening the 2nd or 3rd article in one session a videoad starts playing for at least 5 seconds. Then the "x" appears and you can close the video. This happens once and again when you open the app a few hours later. Second point is that sometimes the add places in the article are filled with ads, sometimes these places are empty and sometimes it says, the site is not available. 

***System configuration***

**Filters:**

# Basis, mobile Anzeigen, easy list, Peter Lowe's Blocklist, Spyware Filter, Easyprivacy, Fanboy's enhanced tracking list, fanboy anti Facebook list, Fanboy's anti thirdparty fonts, social media, Fanboy's social blocking list, malware domains Blocklist, spam 404, nocoin filter list, Ärgernis-Filter, Fanboy's annoiances, Web annoiances ultralist, adblock warning removal list, I don't care about cookies, Fanboy's cookiemonster list, deutscher Filter, easylist Italy, xfiles, easylist Germany, alleblock

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | android
Operating system version (Android/iOS) | 8.0.0
Browser:                               | chrome
AdGuard version:                       | 3.2.150 (1.4.138cl)
Filters enabled:                       | yes
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality 
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | Default 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Please post google play urls of those apps.

**Comment by Alex-302** [comment]
https://play.google.com/store/apps/details?id=com.tcc.android.milannews
https://play.google.com/store/apps/details?id=com.tcc.android.tmw
Fixed.
