### ISSUE TITLE
deezer.com - incorrect blocking

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4421]
***Description***: incorrect blocking of social widgets

Screenshot:

http://prntscr.com/eb6bh7

***Steps to reproduce the problem***:

Go to Мой Аккаунт > Уведомления и обмен мнениями > see partial blocking of social widgets

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Ghrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 939612

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Советую хостинг для скринов сменить, а то здесь картина в iframe загружается, иногда долго ждать пока откроется. Ну и заливать скрины от юзеров лучше в оригинальном разрешении, а не зашакаленном.
Проблему исправил.
