### ISSUE TITLE
https://oneplus.net/support - false blocking

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4422]
***Steps to reproduce the problem***:

1) Go to https://oneplus.net/support
2) click Live chat
3) it is blocking by ADG

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Ghrome
Adguard version: | 6.1.312.1629
Adguard driver (Windows): | WFP 
Adguard filters: | 1,2,3,4,5,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 939612

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed

**Comment by Alex-302** [comment]
fixed
