### ISSUE TITLE
http://edition.cnn.com/ - block autoplay

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4427]
Videos on the [site](http://edition.cnn.com/2017/02/19/politics/craig-deare-white-house-trump/index.html) start playing automatically, is this smth that we can block by the annoyances filter?

![image](https://cloud.githubusercontent.com/assets/15856304/23161432/c581cc24-f832-11e6-8c9c-888946b64a1d.png)

***System configuration***

Information | value
--- | --
Operating system: | Mac OS 
Browser: | All
Adguard version: | 1.4
Adguard DNS: | None
Adguard filters: | 
![image](https://cloud.githubusercontent.com/assets/15856304/23161468/e3df0128-f832-11e6-8cf2-c1d55f222b60.png)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1507954

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
try this
https://github.com/AdguardTeam/Userscripts/tree/master/disableAutoplay

**Comment by ericmol** [comment]
Looks promising but ... 
How or where do I import this? I'm baffled.
I use the OSX version 1.4.0. Trial.

**Comment by Alex-302** [comment]
Ah, Adguard for Windows doesn't support user-scripts(extensions).
What browser are you using?

**Comment by ericmol** [comment]
I am using Safari on MacOs

**Comment by ericmol** [comment]
I do not have an autoplay problem on Chrome or Firefox ... only Safari. And I am trying to switch to Safari for battery life reasons (on my Macbook).  So I am looking for a solution to stop HTML5 and flash autoplay in Safari for MacOS

**Comment by Alex-302** [comment]
Sadly, but I can't prevent autoplay here.
