### ISSUE TITLE
http://v-androide.com/ - ads leftover

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4428]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/23195715/b80351d6-f8bd-11e6-99cb-b1323466f003.jpg)

</details>

***Steps to reproduce the problem***:

http://v-androide.com/instruktsii/rabota/ubrat-blokirovku-ekrana.html

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.8.76 / 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): |  high-speed / High-quality
HTTPS filtering (Android): |  Off/On (Default)
Adguard filters: | English, Spyware, Russian, Mobile ads, Social 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1049047

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
v-androide.com##.distr-rBlock0
v-androide.com##img[onclick^="window.open('http://c."]

```
