### ISSUE TITLE
dailywire.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#44287]
[https://www.dailywire.com/news/tide-in-culture-war-begins-to-shift-with-new-kanye-west-announcement-were-bringing-top-musicians-back-to-god-only-superstar-is-jesus](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.dailywire.com/news/tide-in-culture-war-begins-to-shift-with-new-kanye-west-announcement-were-bringing-top-musicians-back-to-god-only-superstar-is-jesus)

![share](https://user-images.githubusercontent.com/35470489/69038678-109ca800-09c9-11ea-8fee-429cf93f9edd.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Sergey-Lyapin** [comment]
also need to remove anti-adblock popup
![Screenshot 2019-11-18 at 17 08 26](https://user-images.githubusercontent.com/18536328/69059484-afa3bd00-0a26-11ea-80a0-3c95fedc547c.png)
