### ISSUE TITLE
Steam desktop client

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#44296]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

You guys know that pretty annoying popup window that Steam's client pops up about 10 seconds after most startups, which shows ads for new and upcoming AAA games, even when the client's store section is never visited? I have a couple of entries that aim to remove them, if they're considered eligible for AdGuard Base Filter inclusion.

### Proposed Solution

```
steamstore-a.akamaihd.net###all
||steamcdn-a.akamaihd.net/steam/marketing^$image
```

### Alternatives Considered

Since I can't seem to get *AdGuard Assistant* to work with the newestmost Steam GUI, it was very limited what kind of alternatives I could've hoped to come up with.

### Additional Information

Steam client package version: 1573780595
AdGuard for Windows version: 7.3 nightly 5
OS: Windows 10 November 2019 Update

**Comment by BlazDT** [comment]
Did you try to disable the option?

Settings -> Interface: Notify me about additions or changes to my games, new releases and upcoming releases.

**Comment by DandelionSprout** [comment]
...I am honest-to-gods astonished that that's even an option. It must've took me some 6 years before I've now become aware of it.

I have now turned off that setting, and if the popup doesn't show up by noon-ish tomorrow, I'll close this issue. You have my kindest thanks in advance.

**Comment by THEtomaso** [comment]
I've had that setting disabled for so long, that I actually had no idea what you were talking about. :)
On a side note, I'm pleased to see that Valve has restored 'Small mode', in the latest client update!

**Comment by DandelionSprout** [comment]
I didn't really know that such a setting could even exist. I thought *"What kind of webstore could possibly have a button to just turn off ads for their store items?"*. So I never bothered to look it up... 😅

**Comment by DandelionSprout** [comment]
Okay, so since the ads didn't show up again, I suppose it's now time for me to close this issue report.

I'll thank you both for educating me on all this, and I do of course I don't have egg on my face right now.
