### ISSUE TITLE
http://goodkino.net/ - Ads leftover

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4429]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/23195903/bc801f5e-f8be-11e6-8959-27df9cc2ec66.jpg)

</details>

***Steps to reproduce the problem***:

http://goodkino.net/publ/novie_serialy/supergerl_2_sezon_13_14_serija/1-1-0-11256

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): |  high-speed / High-quality
HTTPS filtering (Android): | On (Default)
Adguard filters: | English, Spyware, Russian, Mobile ads, Social 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1049047

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
There is Flash player.
