### ISSUE TITLE
[Stealth mode] https://rev.mail.ru/forums - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4430]
Adguard с некоторого момента начал блокировать картинки на форуме https://rev.mail.ru/forums.

Т.е. вместо картинки отображается иконка 403, при отключении Adguard картинки отображаются нормально, пример тем с заблокированными картинками: 

https://rev.mail.ru/forums/showthread.php?t=20004

Опытами вычленил, что мешали загрузки 2 галочки в разделе Антитрекинг, а именно "Скрывать Referer" и "Скрыть User-Agent", при их выключении картинки заново заработали и все отображается.

Правило формата @@||example.com^$stealth помогло.

![image](https://cloud.githubusercontent.com/assets/15856304/23208384/76496704-f8fd-11e6-9c0c-6f243fb453c0.png)

Ticket ID(if exists): 1072486

**Comment by Alex-302** [comment]
Повторилось только при сокрытии реферера.
Добавил в английский фильтр
```
@@||img.noobzone.ru^$stealth
```
