### ISSUE TITLE
pcgames.de - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4433]
***Site***: http://www.pcgames.de/For-Honor-Spiel-55721/News/Ban-Sperre-Account-1221502/ and http://forum.pcgames.de/
***Description***: 

- Social bar at the bottom on mobile devices. Ad leftover after article. (same as in #4327)

- Ad leftover in forums.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/23217865/e471824e-f91a-11e6-9b98-8c8021285dff.png)

![image](https://cloud.githubusercontent.com/assets/10995998/23217934/15b73da8-f91b-11e6-9a7c-230f7ab75204.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.10.3
Spyware filter | 1.0.10.76
Social media filter | 1.0.17.42
Annoyances filter | 1.0.10.25
German filter | 1.0.31.53
Mobile ads filter | 1.0.7.12
Safari filter | 1.0.2.56

**Comment by danidoedel** [comment]
@Alex-302 
***Ad leftover above forums is back again.***

![image](https://cloud.githubusercontent.com/assets/10995998/25741373/cab56c00-318a-11e7-928a-c652526a3b6e.png)

______________________________________

***Rule to block the shop leftover:***
```
pcgames.de##.shopLinkButtonsWrapper
```

![image](https://cloud.githubusercontent.com/assets/10995998/25741476/492cd37a-318b-11e7-9f33-6abf810fb43f.png)

____________________________________________

***Rule to block the banner leftover at the top:***
```
pcgames.de##.static_banner
```

![image](https://cloud.githubusercontent.com/assets/10995998/25741417/0d708d04-318b-11e7-8d50-9a1fb2b132a7.png)

**Comment by Alex-302** [comment]
fixed
