### ISSUE TITLE
Not working parental control on nigma.ru

### ISSUE THREAD

**Issue by DopeUnicorn** [AdguardTeam/AdguardFilters#4435]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # ()

***Description***:http://nigma.ru/?s=porno&t=web&rg=t%3D%D0%9A%D0%B8%D0%B5%D0%B2_c%3D%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B0_&rg_view=%D0%9A%D0%B8%D0%B5%D0%B2%D0%B5+%28%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B0%29&yn=1&gl=1&rm=1&ms=1&yh=1&av=1&nm=1&lang=all&srt=0&sf=1
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Зашел на сайт nigma.ru потом ввел
поисковый запрос "porno" и перешел по
самой первой картинке - вот ссылка:
http://school-hub.1000ds.ru/images/TQLEEXOWG7e8Q0nqH2dhgSr7F_MNeVbnXgjX6rD5BRwig3TT6geJFdn7ekdLNGHW6sjtNze24jVxUMC6AQp_jVfXqwJ7RgQ-jHDz.gif)
![screen shot 2017-02-22 at 19 02 57](https://cloud.githubusercontent.com/assets/25641172/23222765/9bb8799c-f931-11e6-8bc9-7b1f4b9edebd.png)

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): |  TDI
Adguard DNS: | None
Adguard filters: |  
English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt
FilterId:4 Name: Social media filter Url: https://filters.adtidy.org/extension/chromium/filters/4.txt
FilterId:1 Name: Russian filter Url: https://filters.adtidy.org/extension/chromium/filters/1.txt
FilterId:0 Name: User filter Url: no_url

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1509419

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is not related to filters.
