### ISSUE TITLE
gryphonconnect.com [Cookie notice]

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#44367]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 
Cookie Notice on the website
[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](
![image](
![1](https://ibb.co/RNntXGY)
)
)
</details><br/>

* **Expected behaviour**: 
Shouldn't there be a cookie notice
[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)
Adguard Base list, Adguad tracking protection, Adguard annoyances, Adguard anti social media
[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | Pro 1909
Browser:                               | Firefox Developer Edition 71.0b10
AdGuard version:                       | 
Filters enabled:                       | Yes = Adguard Base list, Adguad tracking protection, Adguard annoyances, Adguard anti social media
AdGuard mode (Android only):           | 
Filtering quality (Android only):      | 
HTTPS filtering (Android only):        | 
Simplified filters (iOS only)          | 
AdGuard DNS:                           | 
Stealth mode options (Windows only)    | 
Helpdesk ID (if exists):               | 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
