### ISSUE TITLE
cs.ingame.de - Ads - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4437]
***Site***: http://cs.ingame.de/ and http://cs.ingame.de/news/csgo/scream-wechselt-zu-team-envyus-statt-zu-faze/
***Description***: Ads at the top right. Partner ads. Amazon ads. Social bar at the bottom right.

<details>
<summary>Screenshot</summary>

**http://cs.ingame.de/:**

![image](https://cloud.githubusercontent.com/assets/10995998/23235356/80b727e6-f955-11e6-8d08-c20685f2e161.png)

![image](https://cloud.githubusercontent.com/assets/10995998/23235375/8fe4cf02-f955-11e6-9c39-5756355d25da.png)

**http://cs.ingame.de/news/csgo/scream-wechselt-zu-team-envyus-statt-zu-faze/:**

![image](https://cloud.githubusercontent.com/assets/10995998/23235434/c97c1018-f955-11e6-9719-6c4281ac9364.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.10.6
Spyware filter | 1.0.10.76
Social media filter | 1.0.17.44
Annoyances filter | 1.0.10.27
German filter | 1.0.31.57
Mobile ads filter | 1.0.7.13
Safari filter | 1.0.2.57

**Comment by Alex-302** [comment]
added
```
cs.ingame.de##.socialbar
cs.ingame.de##.mauto
cs.ingame.de##.frontpageWidgets > div#text-5.widget_text
cs.ingame.de##.widget_twitter_widget
cs.ingame.de###adzoneA_area
```
