### ISSUE TITLE
www.pmr.md 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4438]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:http://www.pmr.md/a8ce167fa124a66c7450015b9dfa6cc1/gadzheti_magazin.html - missed ad on page 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/23235553/9d7098b4-f95e-11e6-854e-679b8911e986.png)

</details>

***System configuration***
Application version: 1.1.5.65
Device: iPad
Platform: iOS
OS: 10.3
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.9.81 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.73 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.37 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.10.21 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.47.35 Enabled=YES
ID=6 Name="German filter" Version=1.0.30.78 Enabled=NO
ID=7 Name="Japanese filter" Version=1.0.93.4 Enabled=NO
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.51 Enabled=NO
ID=5 Name="Experimental filter" Version=1.0.26.49 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.7.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.54 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.73 Enabled=NO

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1138135

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed. Check after filters update(after 2-3 hours)
