### ISSUE TITLE
tvzion.com

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#4439]
fake buttons: https://i.imgsafe.org/e19229ad47.png
video overlay countdown: https://i.imgsafe.org/e19a7e49b0.png 

sources: 
http://www.tvzion.com/watch-bering-sea-gold-online-free-v1-58704#
http://www.tvzion.com/watch-bering-sea-gold-season-8-episode-3-s08e03-online3-free-v1-58704

**Comment by seanl-adg** [comment]
Fixed fack buttons. The video overlay countdown only lasts 3 seconds and it is not an ad.

**Comment by jo2dan23** [comment]
kind of an annoyance tho when binge watching. could it be added to the annoyance list? dont mean to be a bother sorry. @seanl-adg
