### ISSUE TITLE
raptu.com

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#4440]
popup and video overlay

https://www.raptu.com/embed/ykWNDsCa

**Comment by seanl-adg** [comment]
Fixed popup, please check.
It is not an overlay. There is no real video behind the image. Clicking on the image redirects to a different page which contains the real video.

**Comment by jo2dan23** [comment]
Yeah I understand that but is there a way to eliminate the need to click twice like we have been doing for other sites? @seanl-adg

**Comment by seanl-adg** [comment]
You can use
```
raptu.com#%#AG_onLoad(function(){var el=document.querySelector('body > #normalmsg > form[action="#"]');if(el)el.submit()});
```
I've felt that the purpose of Annoyance is too broad and ambiguous. We should improve it in https://github.com/AdguardTeam/AdguardFilters/issues/3937.
@Alex-302 Should we add such rules to Annoyance filter?

**Comment by Alex-302** [comment]
@seanl-adg you can put it to English fitler.

**Comment by jo2dan23** [comment]
@Alex-302 can you add this please?  :)
