### ISSUE TITLE
theculturetrip.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#44408]
[https://theculturetrip.com/asia/south-korea/articles/south-korean-anime-that-you-should-watch/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://theculturetrip.com/asia/south-korea/articles/south-korean-anime-that-you-should-watch/)

![app banner](https://user-images.githubusercontent.com/35470489/69220865-add81780-0b54-11ea-9acc-08b26ea2e98d.png)

Adguard Base + Annoyances + Mobile + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Mozilla/5.0 (Android 7.1.2; Tablet; rv:68.0) Gecko/68.0 Firefox/68.0

**Comment by adranger** [comment]
@Alex-302 

![cookie](https://user-images.githubusercontent.com/35470489/72698927-0613a180-3b25-11ea-9705-7ef67ff03e4b.png)

**Comment by Alex-302** [comment]
ok
