### ISSUE TITLE
AdGuard ignoring the Priority Tasks app

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#44420]
@akmLaVx commented on [Tue Feb 26 2019](https://github.com/AdguardTeam/AdguardForMac/issues/425)

### Steps to reproduce
1. Install the following app: https://itunes.apple.com/ua/app//id1119079160?l=ru&mt=12&ls=1>
2. Ads will not be blocked by AdGuard, even if the app is already in filtered apps list

### Expected behavior
Ads should be blocked

### Actual behavior
Ads aren't blocked

### Screenshots & Logs
Available under customer id 2090812

---

@Stillness-2 commented on [Wed Nov 20 2019](https://github.com/AdguardTeam/AdguardForMac/issues/425#issuecomment-555972913)

@Alex-302 technically AdGuard intercepts connections of this application (the last beta at least). It may be possible to create a set of rules for filtering this app.

---

@Stillness-2 commented on [Wed Nov 20 2019](https://github.com/AdguardTeam/AdguardForMac/issues/425#issuecomment-555976872)

May be like this:

```
||trenshot.com
||stat.analytiall.com
||itunes.apple.com$app=Priority Tasks
```

**Comment by Alex-302** [comment]
> technically AdGuard intercepts connections of this application (the last beta at least)

not in my case(even after restart AG). Added this app to filtered.

It seems a banner built-in to this app. Tried to block all connections, but it is not blocked. Even if network connection is disabled.
