### ISSUE TITLE
eatthis.com - incorrect blocking 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4443]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Won't load the website at all.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/23265168/915499fc-f9ec-11e6-9328-260b58414b02.png)

</details>

***Steps to reproduce the problem***:

http://www.eatthis.com/best-and-worst-store-bought-breads?src=facebook

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Chrome 
Adguard version: | 2.8
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  Off
Adguard filters: | English, Russian, Spyware, Social media, Mobile ads, User filter

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1505790

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It works?

**Comment by Bohdan-SUP** [comment]
Resolved here:
https://github.com/AdguardTeam/AdguardFilters/issues/4401
