### ISSUE TITLE
http://pg11.ru ads on the website

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4444]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

Incorrect blocking on this website: http://pg11.ru. The problem appears in Chrome, IE, Mozilla and Opera. The issue occurs on Windows/Mac OS:

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prntscr.com/ecicci

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome, Opera, IE, Mozilla
Adguard version: | 1.4.0, 6.1.314.1628
Adguard driver (Windows): | WFP
Adguard filters: | User Filter, English Filter, Spyware, Social Media Filter, Annoyance filter, Russian, Mobile Ads

[//]: # (***)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): https://qcrm.supportyourapp.com/#/customer/1114287

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
> Incorrect blocking

what is broken? I see only ads.

**Comment by Darina655** [comment]
@Alex-302 It is a news portal full of ads and banners when Adguard is enabled. This issue can be reproduced on Mac OS and Windows

**Comment by Alex-302** [comment]
Then the label is wrong.
Ads are blocked.
