### ISSUE TITLE
freetutorialseu.com 

### ISSUE THREAD

**Issue by YASINEDr** [AdguardTeam/AdguardFilters#44456]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

[//]: # (Substitute this line with a description of the problem)
AdGuard detected on 👍 

https://www.freetutorialseu.com/
https://www.freecoursessites.com/
https://www.ftuudemy.com/
https://www.ftuforums.com/

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](
![screenshot-www freetutorialseu com-2019 11](https://user-images.githubusercontent.com/34688076/69293540-75dedc00-0c09-11ea-86c3-e1730742c33c.png)
)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](
![screenshot-www freetutorialseu com-2019 11 (2)](https://user-images.githubusercontent.com/34688076/69293692-fa315f00-0c09-11ea-8a99-d39590d907d9.png)
)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Ext
Operating system version (Android/iOS) | ?
Browser:                               |Chrome
AdGuard version:                       |3.3.4
Filters enabled:                       | All
AdGuard Base,

AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
