### ISSUE TITLE
vshare.eu

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#4447]
any way to get rid of countdown?

http://vshare.eu/m1h3vvweslcd.html

**Comment by jo2dan23** [comment]
@seanl-adg @Alex-302

**Comment by Alex-302** [comment]
Don't write on the forum and github. Please use forum.

**Comment by jo2dan23** [comment]
@Alex-302 sorry. i had moved some stuff to github and forgot that i posted it already.

**Comment by Alex-302** [comment]
No, I mean use the forum instead github. It will more convenient for me)
