### ISSUE TITLE
thevideo.me

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#4448]
thevideo.me##.col-sm-3

removes sponsored content box. any way to center the video too ?

https://thevideo.me/av804jzkk3z7

**Comment by seanl-adg** [comment]
>any way to center the video too ?

```
thevideo.me#$##player_code > .col-sm-9 {width: 100%}
thevideo.me#$##player_code {height: 600px!important}
```

**Comment by jo2dan23** [comment]
thevideo.me#$##player_code > .col-sm-9 {width: 100%}

we should add this to english list
