### ISSUE TITLE
putlocker.ac

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#4450]
fake links:

https://i.imgsafe.org/f2bfbd95b5.png
https://i.imgsafe.org/f2bfc9e2e5.png
https://i.imgsafe.org/f2bfd2ffbf.png

sources:

http://putlocker.ac/watch-wonder-woman-online-free-2009-putlocker.html

http://putlocker.ac/external.php?url=aHR0cHM6Ly9vcGVubG9hZC5jby9mL3E4S2k3anlwUnJnL1dvbmRlci5Xb21hbi4yMDA5LkJSUmlwLlh2aUQuTVAzLVJBUkJHLmF2aS5tcDQ=

http://putlocker.ac/?s=pitbulls&x=0&y=0

**Comment by jo2dan23** [comment]
@Alex-302 @seanl-adg

**Comment by seanl-adg** [comment]
The button in the third screenshot doesn't seem to be a fake link.
