### ISSUE TITLE
putlockeris.org

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#4451]
fake links:

https://i.imgsafe.org/f2cd2a2e72.png
https://i.imgsafe.org/f2cd389ec9.png

sources:

http://www.putlockeris.org/x-men-first-class-2011/
http://www.putlockeris.org/go.php?url=http://www.promptfile.com/l/3D0743CCC4-367CEBFA48%20

**Comment by jo2dan23** [comment]
@Alex-302 @seanl-adg

**Comment by seanl-adg** [comment]
Elements in the first screenshot were not reproduced.

**Comment by jo2dan23** [comment]
@seanl-adg  https://i.imgsafe.org/6f3d619331.png

**Comment by jo2dan23** [comment]
@Alex-302
