### ISSUE TITLE
http://www.online-life.cc/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4452]
http://www.online-life.cc/2876-zhenaty-i-s-detmi-married-with-children-1987-1997.html

![image](https://cloud.githubusercontent.com/assets/15856304/23279610/9cf383c2-fa1e-11e6-8e2a-52187d258729.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | ЯБ
Adguard version: | последняя
Adguard driver (Windows): | WFP
Adguard DNS: | None 
Stealth mode options(Windows) | нет
Adguard filters: | рус, англ, соц. медиа, раздражителей,

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
not reproduced
