### ISSUE TITLE
SchonMagazine.com - Blocked elements (AdGuard Social Media filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#44556]
### Affected site:
`https://schonmagazine.com/`

### Issue:
Most elements are blocked!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* AdGuard Social Media filter

### Problem rule:
`~goodcooking.com##.addthis_toolbox`

### Possible fix:
```
- ~goodcooking.com##.addthis_toolbox
+ ~goodcooking.com,schonmagazine.com##.addthis_toolbox
```

### Temporary fix:
`schonmagazine.com#@#.addthis_toolbox`

### Other problem filters:
* Fanboy's Annoyance List / Fanboy's Social Blocking List https://github.com/ryanbr/fanboy-adblock/issues/1240/
* uBlock filters - Privacy https://github.com/uBlockOrigin/uAssets/issues/6608/

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.7.2 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.11 (XUL)

**Comment by AdamWr** [comment]
Fixed.

Thank you.
