### ISSUE TITLE
m.gexing.com/qqtouxiang/

### ISSUE THREAD

**Issue by DopeUnicorn** [AdguardTeam/AdguardFilters#4456]
![screen shot 2017-02-24 at 4 21 18 pm](https://cloud.githubusercontent.com/assets/25641172/23307603/c9af9ab2-fab0-11e6-9091-a735332c87d7.png)

Information | value
--- | ---
Operating system: | IOS 9.3.5
Browser: | Safari/ Chrome
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | None 
Adguard filters: | 
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.9.74 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.73 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.35 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.10.21 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.1 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.7.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.53 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.88 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.75.18 Enabled=YES

Ticket ID(if exists): 1510611

**Comment by Alex-302** [comment]
What is it?
