### ISSUE TITLE
https://lady.mail.ru/forum/ возможно ли убрать окно справа от мейл.ру

### ISSUE THREAD

**Issue by DopeUnicorn** [AdguardTeam/AdguardFilters#4457]
![screen shot 2017-02-24 at 6 21 13 pm](https://cloud.githubusercontent.com/assets/25641172/23311236/10182dea-fabe-11e6-9c1f-c134915d18d1.png)

Information | value
--- | ---
Operating system: | Windows 10
Browser: | Chrome/Edge
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Adguard DNS: | None 
Adguard filters: | 
Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:119 Name: Icelandic ABP List Url: http://adblock.gardar.net/is.abp.txt
FilterId:216 Name: Adblock polskie reguły Url: https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt
FilterId:0 Name: User filter Url: no_url

Ticket ID(if exists): 1030934

**Comment by Alex-302** [comment]
Можно.
Добавил в фильтр раздражителей
```
lady.mail.ru##div[data-adq-id^="adqcontainer"]
```
