### ISSUE TITLE
images.mynonpublic.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#4458]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: tons of ads at http://images.mynonpublic.com/openatv/5.3/index.php

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/14153331/23320155/465c962e-fae2-11e6-9354-9e6eb78f8b61.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Adguard DNS: | None

Adguard filters:
![image](https://cloud.githubusercontent.com/assets/14153331/23320171/5636c2cc-fae2-11e6-882d-fbf6be3fa7a6.png)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1509512

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
added
```
||lavatronics.co.uk/images/openatv.gif
||images.mynonpublic.com/openatv/*/_sponsoren/
||satking.de/images/banners/
```
