### ISSUE TITLE
battlecats.spica-net.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#4459]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/14153331/23320442/78e12bea-fae3-11e6-8af3-d5c3ecbd97df.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/14153331/23320435/6ec00168-fae3-11e6-9f11-415dc49670cd.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Adguard DNS: | None

Adguard filters:
![image](https://cloud.githubusercontent.com/assets/14153331/23320171/5636c2cc-fae2-11e6-882d-fbf6be3fa7a6.png)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1510878

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
