### ISSUE TITLE
http://www.theanimalrescuesite.com/ - Incorrect Blocking

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4460]
http://www.theanimalrescuesite.com/clickToGive/ars/home

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-02-24 at 10 51 03 pm](https://cloud.githubusercontent.com/assets/22892774/23320613/2dc50d9c-fae4-11e6-9ae6-ec88284c6b8e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS
Browser: | Chrome
Adguard version: | 6.1.314.1628 / 1.4.0 
Adguard filters: | 1,2,3,4,5,14

Ticket ID: 1244019

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
theanimalrescuesite.com#@#.adLink
```
