### ISSUE TITLE
play.esea.net - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4461]
***Site***: https://play.esea.net/
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/23323351/84955d76-fae8-11e6-89e3-a98d655452f7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.10.16
Spyware filter | 1.0.10.77
Social media filter | 1.0.17.47
Annoyances filter | 1.0.10.29
German filter | 1.0.31.61
Mobile ads filter | 1.0.7.13
Safari filter | 1.0.2.58

**Comment by Alex-302** [comment]
Added to English filter
```
play.esea.net###module-ads-home-bottom
```
