### ISSUE TITLE
modernboard.de - Ad leftover - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4464]
***Site***: https://www.modernboard.de/
***Description***: Ad leftover at the top. Ad post in forums.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/23323914/24d47298-faeb-11e6-81c9-d5ec661e0be6.png)

https://www.modernboard.de/threads/wechsel-auf-ip-telefonie.118594/:

![image](https://cloud.githubusercontent.com/assets/10995998/23323927/38c14a7e-faeb-11e6-8a04-e93721a38be2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.10.16
Spyware filter | 1.0.10.77
Social media filter | 1.0.17.47
Annoyances filter | 1.0.10.29
German filter | 1.0.31.61
Mobile ads filter | 1.0.7.13
Safari filter | 1.0.2.58

**Comment by Alex-302** [comment]
added
```
modernboard.de###oc24_container_top
modernboard.de###TopRectangle
modernboard.de###MidRectangle
modernboard.de##.social_share_bar
modernboard.de##.Anzeige.message
```
