### ISSUE TITLE
gamestar.de - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4465]
***Site***: http://www.gamestar.de/videos/was-ist-0-ad-age-of-empires-im-blut,92184.html
***Description***: Adblock detection on iOS devices.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/23324109/360aa658-faec-11e6-82f7-a07532c52cdc.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.10.16
Spyware filter | 1.0.10.77
Social media filter | 1.0.17.47
Annoyances filter | 1.0.10.29
German filter | 1.0.31.61
Mobile ads filter | 1.0.7.13
Safari filter | 1.0.2.58

**Comment by Alex-302** [comment]
Not reproduced.
