### ISSUE TITLE
http://dev.silverfish.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4466]
http://dev.silverfish.com/sunglasses/E.html

Try to click on any of the products on this page to load its product page. None of the links work while AdGuard is running. 

![image](https://cloud.githubusercontent.com/assets/15856304/23328927/c8c8abd6-fb35-11e6-835c-2f38e95ff7f3.png)

You have to use "don't block for 30 seconds" om PC or whitelist it on iOS

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS
Browser: | Chrome, Safari
Adguard version: | 1.4
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | Eng, Spyware, SM, Annoyances, Russian, Liste FR, Polskie reguly

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1509645

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||google-analytics.com/plugins/ua/ec.js$domain=dev.silverfish.com
@@||google-analytics.com/analytics.js$domain=dev.silverfish.com

```
