### ISSUE TITLE
coldfilm.ru - pop-ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4467]
При нажатии на кнопку play, открываются новые окна:
http://coldfilm.ru/news/grimm_6_sezon_8_serija_smotret_onlajn/2017-02-25-7125

![screenshot_18](https://cloud.githubusercontent.com/assets/15856304/23330798/579dab52-fb60-11e6-855b-a2e18abce3f8.jpg)
![screenshot_8](https://cloud.githubusercontent.com/assets/15856304/23330799/58356fd2-fb60-11e6-9a9e-c192334da28b.jpg)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Adguard filters: | 1 2 4 116

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1461884

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
