### ISSUE TITLE
http://bleacherreport.com - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4468]
http://bleacherreport.com/articles/2694523-the-question-what-can-ufc-fans-expect-from-a-returning-georges-st-pierre

The player appears in the lower right-hand corner. Can we prevent the autoplay? If no, please create a rule for the user filter so that we could send it to the customer.

![image](https://cloud.githubusercontent.com/assets/15856304/23331271/29efe944-fb6b-11e6-8436-a437d0a3358e.png)

[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS, Win
Browser: | Chrome
Adguard version: | 1.4
Adguard filters: | 1 2 3 4 10 103 104

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 626714

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
```

**Comment by Alex-302** [comment]
```
||cdn.bleacherreport.net/amp.premier/bleacher/2/amp.premier.min.js
bleacherreport.com##.atom.videoFlyin
```
