### ISSUE TITLE
autoweek.nl

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#4469]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

* **Current behaviour**: adblock detection at autoweek.nl

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/14153331/23332133/22eef1f0-fb7d-11e6-8884-a06e7c01e6ce.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS / Android
Browser: | Chrome, Safari
Adguard version: | 1.4.0/2.8.76
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default mode)
Adguard DNS: | None 

Adguard filters: 
<img width="270" alt="screen shot 2017-02-25 at 17 08 17" src="https://cloud.githubusercontent.com/assets/14153331/23332147/8d4d7d82-fb7d-11e6-9266-94a9dd2857ef.png">

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1492862

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed in annoyances filter
