### ISSUE TITLE
reddit.com

### ISSUE THREAD

**Issue by JaeeonRyoo** [AdguardTeam/AdguardFilters#44717]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

**Current behaviour**: Reddit displays constant email verification reminder even though it is not required.

<details><summary>Screenshot:</summary>

<img width="972" alt="image" src="https://user-images.githubusercontent.com/48917689/69499487-ebaeb480-0f35-11ea-8cbb-b3cf03e100d7.png">

</details><br/>

***Steps to reproduce the problem***:

Make a reddit account without providing an email.

***Fix***
```
reddit.com###SHORTCUT_FOCUSABLE_DIV > div:last-child > div

```
***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | MacOS
Operating system version (Android/iOS) | Catalina
Browser:                               | Safari
AdGuard version:                       | 1.5.4
Filters enabled:                       | AdGuard Base Filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter
AdGuard DNS:                           | None

**Comment by BlazDT** [comment]
@AdguardTeam/filters-maintainers imho only for user filter.

**Comment by JaeeonRyoo** [comment]
I sort of agree but they use anti adblock tricks for the notice so users will not be able to remove the nag screen using the element picker.

Reddit used to be completely okay with having accounts without an email address and there seems to be no consequence for the user currently for not having an email address. (Except for reddit being able to harvest more data of course.)

**Comment by Alex-302** [comment]
I don't see this message with my account. Try to verify you account.
