### ISSUE TITLE
csgoproconfig.com - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4472]
***Site***: http://www.csgoproconfig.com/
***Description***: Ads.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/23335368/d1f14496-fbb4-11e6-8238-0d6ea4c47db4.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.10.26
Spyware filter | 1.0.10.79
Social media filter | 1.0.17.50
Annoyances filter | 1.0.10.32
German filter | 1.0.31.61
Mobile ads filter | 1.0.7.15
Safari filter | 1.0.2.59

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
csgoproconfig.com##.img > a[href="contact.html"]
```
Added to English filter
```
csgoproconfig.com##img[style="vertical-align:middle;width:160px;height:600px;"]
```
