### ISSUE TITLE
m.focus.de - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4473]
***Site***: http://m.focus.de/ and http://m.focus.de/politik/ausland/neuer-affront-gegen-medien-trump-kommt-nicht-zu-traditionellem-korrespondenten-dinner_id_6706963.html
***Description***: Ad leftover. Social overlay. Social widget below article.

<details>
<summary>Screenshot</summary>

Ad leftovers index page:

![image](https://cloud.githubusercontent.com/assets/10995998/23335419/ac8e75a6-fbb5-11e6-88f1-c69a9c5cf10c.png)

![image](https://cloud.githubusercontent.com/assets/10995998/23335425/bd011678-fbb5-11e6-962d-2a80cfb82455.png)

Social overlay when clicking on an article (http://m.focus.de/politik/ausland/neuer-affront-gegen-medien-trump-kommt-nicht-zu-traditionellem-korrespondenten-dinner_id_6706963.html):

![image](https://cloud.githubusercontent.com/assets/10995998/23335441/e064526a-fbb5-11e6-80fc-9a6add714edc.png)

Social widgets below article:

![image](https://cloud.githubusercontent.com/assets/10995998/23335447/ff973d1e-fbb5-11e6-88a6-06d10ca9c6fd.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.10.26
Spyware filter | 1.0.10.79
Social media filter | 1.0.17.50
Annoyances filter | 1.0.10.32
German filter | 1.0.31.61
Mobile ads filter | 1.0.7.15
Safari filter | 1.0.2.59

**Comment by Alex-302** [comment]
Reproduced only leftovers.
Added to mobile filter:
```
m.focus.de##article.card[data-teaser-type="unspecified_group"]
```
