### ISSUE TITLE
Айдаприкол app - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4474]
Включен Adguard Pro for iOS в режиме VPN. Реклама в приложении [Айдаприкол ](https://itunes.apple.com/ru/app/айдаприкол/id412412148?mt=8) блокируется только при работе мобильного интернета (LTE от МТС). При работе WiFi реклама не блокируется. 

![image1](https://cloud.githubusercontent.com/assets/15856304/23338647/2a3e793e-fc19-11e6-9c2f-e8c40ca7381a.PNG)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Adguard version: | 1.1.5.40
Adguard DNS: | Default

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1431954

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Это не с фильтрами проблема, адреса с рекламой те же.

**Comment by evgeniy-ADG** [comment]
Это баг? Перезавести в iOS или что сделать? У пользоваля проблема и хочу понять, где искать причину.

**Comment by Alex-302** [comment]
Если реклама гугловая, то лучше в разделе iOS спросить. Она 100% должна блокироваться.
