### ISSUE TITLE
rus.delfi.ee -missed ad on page

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4476]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:http://rus.delfi.ee/daily/abroad/v-gejdelberge-avtomobil-vrezalsya-v-tolpu-i-ranil-troih?id=77357144&com=1®=1&no=0&s=1 - missed ad

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/23341366/d0a25dd8-fc4e-11e6-85f1-4fa65b39ec2e.png)

</details>

***System configuration***

Application version: 1.1.5.65
Device: iPad
Platform: iOS
OS: 10.3

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.10.33 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.79 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.50 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.59 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.75.42 Enabled=YES
ID=218 Name="Estonian List" Version=1.0.1.29 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.72.18 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.71.95 Enabled=YES

Ticket ID: 1497811

**Comment by Alex-302** [comment]
Not reproduced. Try
```
delfi.ee##div[class$="col-has-ad"] div[id^="dwidget"]
```
