### ISSUE TITLE
Expire tag on filters

### ISSUE THREAD

**Issue by MarkoXD** [AdguardTeam/AdguardFilters#4477]
Hello guys!

Can you please add "**! Expires: 1 days (update frequency)**" (without quotation marks) on top of your filters? 

This will make any ad blocking software/extension automatically update filters every day. It would be useful because filters are updated few times every day.

Thanks.

**Comment by Alex-302** [comment]
@ameshkov Should we do it?

**Comment by ameshkov** [comment]
@Alex-302 yeah, sure, also we'd better automate it for all the filters.

@Mizzick, change the filters compilation procedure. Utilize "expires" field from the DB.

**Comment by MarkoXD** [comment]
You can also set update frequency in hours. Just replace word "days" with "hours" if you think it's necessary to update it often. You can set any interval from 1 hour to 14 days. 

ABP team also mentioned that filters won't be updated at same interval as always so update time will be randomized to avoid high server load.

**Comment by Mizzick** [comment]
Added new field:
`! Expires: %s seconds (update frequency)`

**Comment by ameshkov** [comment]
@Mizzick please put the updated compiler to the filters repo.

**Comment by Mizzick** [comment]
Actually there is no need to update compiler/generator. 
In this case we append this header in cache service, so it's necessary to update backend-service.

**Comment by Alex-302** [comment]
`! Expires: 2 days (update frequency)`
Is this part necessary -  `(update frequency)` ?

**Comment by Mizzick** [comment]
@Alex-302 I think it was a part of requested format.
