### ISSUE TITLE
readmanga.me - missed ad

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4478]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://readmanga.me/everyday_life/vol7/120?mature= - missed ad on page 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-02-26 at 10 20 42 pm](https://cloud.githubusercontent.com/assets/23372054/23343342/a9ac14c0-fc72-11e6-9936-e8ae53005047.png)

</details>

***System configuration***
Application version: 1.1.5.65

Device: iPad
Platform: iOS
OS: 10.2.1

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.6.93 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.34 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.64 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.45.82 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.17 Enabled=YES

Ticket ID: 1511811

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
