### ISSUE TITLE
https://m.filmix.me/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4479]
https://m.filmix.me/serialy/55213-portlandiya-portlandia-serial-2011.html

![img_0156](https://cloud.githubusercontent.com/assets/15856304/23351584/ba70552a-fcca-11e6-812a-e95168bc87bd.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | 1 2 3 4 12 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1511198

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
DNS blocks the banner but lefts a placeholder.

**Comment by Alex-302** [comment]
Added to Mobile filter
```
m.filmix.me##.remove-sda-wrap
m.filmix.me##div[id*="Composite"]

```
