### ISSUE TITLE
onwatchseries.to - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4480]
http://onwatchseries.to/cale.html?r=aHR0cDovL2dvcmlsbGF2aWQuaW4vcXVrb2RhczdnZmR5

With content blocker + DNS

<details>

![file_000 1](https://cloud.githubusercontent.com/assets/15856304/23352117/ffa4495a-fccd-11e6-8e4b-4549093cf61b.png)

</details>

Without:

<details>

![file_000](https://cloud.githubusercontent.com/assets/15856304/23352109/f79b9baa-fccd-11e6-86eb-aa11f0c8e975.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | Default
Adguard filters: | 2 3 4 6 11 12 101

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1512365

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I see only ads without Adguard
http://imagizer.imageshack.com/img923/7044/RrKb0v.png
That button opens http://gorillavid.in/404.html
