### ISSUE TITLE
http://www.latimes.com - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4481]
http://www.latimes.com/local/california/la-me-ln-man-dead-magic-castle-hollywood-20170224-story.html

>All I do is go the www.latimes.com<http://www.latimes.com> and either click on a story on the main page, or go to a different section and click on a story. The warning only comes up when I click on an actual story... and this is on every browse

![imag0962](https://cloud.githubusercontent.com/assets/15856304/23354630/d510d8ea-fcda-11e6-8159-d31f1efee4e7.jpg)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | the current
Adguard driver (Windows): | WFP
Adguard DNS: | None
Stealth mode options(Windows) | Basic settings
Adguard filters: | English, Russian, Social media, Annoyances, Spyware

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1252981

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
I was unable to reproduce it.

**Comment by Alex-302** [comment]
Also not reproduced.

**Comment by holz75** [comment]
I'm sorry, but I think you're doing it incorrectly to replicate the issue.  You can't simply go to latimes.com.  You must go to latimes.com, click on a section like sports, and then click on an individual story.  It will happen, and if it doesn't happen, please provide a screenshot to prove it.  Thanks.

**Comment by Alex-302** [comment]
@holz75 I am tried it, and nothing.

**Comment by holz75** [comment]
Please go to www.latimes.com.  Click on "Sports".  Click on the first article "To defeat Providence, USC must first confront last season's collapse".  Then, please post a screen shot.

Thanks.

**Comment by Alex-302** [comment]
Opened. Here is a screenshot after one minute

<details>

![image](http://imagizer.imageshack.com/img923/5848/BVPliL.png)
</details>

Are you using only these filters? `English, Russian, Social media, Annoyances, Spyware`
Did you try to disable user filter?

**Comment by holz75** [comment]
Thank you for that.  Yup, I've tried everything.  :-(  What browser are you using?  Is that Chrome?  Are you using Windows 10?  I'm on a Windows 10 PC and have tried every browser.  It's always the same result.

**Comment by Alex-302** [comment]
Yes. Chrome on Win7/10.
Please try to disable all filters, except English.

**Comment by holz75** [comment]
Yeah, I just tried it, and no progress.  I tried doing just English, English + User, English + Annoyances, and English + User + Annoyances.  I'm not sure what else to do?
