### ISSUE TITLE
http://www.clixsense.com/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4483]
http://www.clixsense.com/en/View_Ads/2924894/8879485/s and others

![image](https://cloud.githubusercontent.com/assets/15856304/23359958/77404cac-fcf1-11e6-9935-2058a28ea549.png)

***Steps to reproduce the problem***:

1. Go to the site and REGISTER
2. Start watching ads and you *should* see the ad blocker

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Opera
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Stealth mode options (Windows) | On
Adguard filters: | 1 2 3 4 19

[state (54).txt](https://github.com/AdguardTeam/AdguardFilters/files/803483/state.54.txt)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1394154

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not repdoruced.
http://imagizer.imageshack.com/img924/4711/paURRX.png
http://imagizer.imageshack.com/img922/8461/ZRs0fm.png

**Comment by evgeniy-ADG** [comment]
Аналогично. Но у пользоватля вот проблема сохранется. Может, попросить ТВ и посомтришь? Не знаю, что та вообще делать. Там еще и директ в почте ))

**Comment by Alex-302** [comment]
давай гляну

**Comment by Yana-SUP** [comment]
@Alex-302 
Юзер отписал:
удобнее всего в 18 часов связаться по будням (московское время)
в выходные можно утром
ник Skype тут: 1394154

**Comment by Alex-302** [comment]
Передай на пробу
* [CODE]
@@||clixsense.com^$generichide
[/CODE]
* [CODE]
@@||clixsense.com^$genericblock
[/CODE]
* [CODE]
@@||clixsense.com^$domain=clixsense.com
[/CODE]

**Comment by evgeniy-ADG** [comment]
>И опять проблема с clixsense.com, всё сделал
как вы написали. Даже добавил строчки :
@@||clixsense.com^$generichide
@@||clixsense.com^$genericblock
@@||clixsense.com^$domain=clixsense.com
 Как то не стабильно работает ваша
программа. В чём проблема ????

**Comment by Alex-302** [comment]
```
@@||clixsense.com^$document
```
это будет работать
