### ISSUE TITLE
gamesaktuell.de - Ad - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4484]
***Site***: http://www.gamesaktuell.de/ / http://forum.gamesaktuell.de/
***Description***: 

<details>
<summary>Screenshot</summary>

Ad leftover below header:

![image](https://cloud.githubusercontent.com/assets/10995998/23377472/6ec6a9ec-fd30-11e6-960a-66510e4ec2e6.png)

Ads in right sidebar:

![image](https://cloud.githubusercontent.com/assets/10995998/23377229/7c26efb2-fd2f-11e6-9957-5726b2a636bc.png)

Ad leftover after article and Social bar at the bottom (http://www.gamesaktuell.de/Twitch-Firma-258761/News/stream-live-computerspiele-plattform-kaufen-1221915/):

![image](https://cloud.githubusercontent.com/assets/10995998/23377296/ca8dac9a-fd2f-11e6-8441-38248cb3842c.png)

Ad in right sidebar:

![image](https://cloud.githubusercontent.com/assets/10995998/23377392/32625e88-fd30-11e6-9f3f-389efb38d9cc.png)

Ad below article:

![image](https://cloud.githubusercontent.com/assets/10995998/23377413/43c0da06-fd30-11e6-87c0-8fab7030e2b5.png)

Ad leftover at the top in forums (http://forum.gamesaktuell.de/):

![image](https://cloud.githubusercontent.com/assets/10995998/23377323/f175e7be-fd2f-11e6-9448-f7ef5320be0d.png)

Ad post in forums (http://forum.gamesaktuell.de/pc-spiele/83763-ist-euer-lieblingsspiel.html):

![image](https://cloud.githubusercontent.com/assets/10995998/23377356/0c0679a4-fd30-11e6-9355-dbca014554e7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.10.50
Spyware filter | 1.0.10.81
Social media filter | 1.0.17.55
Annoyances filter | 1.0.10.37
German filter | 1.0.31.69
Mobile ads filter | 1.0.7.16
Safari filter | 1.0.2.59

**Comment by Alex-302** [comment]
Added to German filter
```
||gamesaktuell.de/tsimg/$image
gamesaktuell.de##.topFrameEddie
forum.gamesaktuell.de##.posts > ul > li.postbitlegacy#post_rec
gamesaktuell.de###pricehitsTextTeaser
```
