### ISSUE TITLE
hometogo.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4486]
***Site***: https://www.hometogo.de/
***Description***: App banner at the top.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/23377640/11e1bb4e-fd31-11e6-9a95-c4fafcc8628a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.10.50
Spyware filter | 1.0.10.81
Social media filter | 1.0.17.55
Annoyances filter | 1.0.10.37
German filter | 1.0.31.69
Mobile ads filter | 1.0.7.16
Safari filter | 1.0.2.59

**Comment by seanl-adg** [comment]
I can't reproduce.

**Comment by danidoedel** [comment]
Still there though:

[html of the site](https://github.com/AdguardTeam/AdguardFilters/files/1143373/site.txt)

![image](https://user-images.githubusercontent.com/10995998/28140900-900793c0-675a-11e7-9375-872adc70f867.png)
