### ISSUE TITLE
bosch.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4487]
***Site***: http://m.bosch.com/en/com/home/index.php
***Description***: Cookie notice at the top.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/23377703/48712f00-fd31-11e6-9baf-3d7176add662.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.10.50
Spyware filter | 1.0.10.81
Social media filter | 1.0.17.55
Annoyances filter | 1.0.10.37
German filter | 1.0.31.69
Mobile ads filter | 1.0.7.16
Safari filter | 1.0.2.59

**Comment by danidoedel** [comment]
@seanl-adg @Alex-302 
Cookie notice is back:
```
bosch.com##.O-CookieLaw
```

**Comment by Alex-302** [comment]
Added

**Comment by XX-J** [comment]
Бош - одна из тех, кто очень любит ПЕЕЧЕЕЕЕНЬКИИ!!

<details><summary>Screenshot:</summary>

![2019 10 20-1](https://user-images.githubusercontent.com/17948007/67154255-c957c480-f301-11e9-963b-900130458286.png)
----------
![2019 10 20-2](https://user-images.githubusercontent.com/17948007/67154259-ce1c7880-f301-11e9-973a-ebbc2eb4bea5.png)
</details>

[https://www.bosch.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.bosch.com/)

`bosch.com##[class^="BoschPrivacySettingsV"]`
`bosch.com#$#.privacy-settings-open > * { filter: none!important; -webkit-filter: none!important; }`

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.3.1
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
ок
