### ISSUE TITLE
pioneer-car.eu - Annoyance - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4489]
***Site***: http://www.pioneer-car.eu/eur/sites/segmentation/segmentation-de.html / http://www.pioneer-car.eu/eur/
***Description***: Links don't work with Adguard enabled. Cookie notice at the bottom.

<details>
<summary>Screenshot</summary>

http://www.pioneer-car.eu/eur/sites/segmentation/segmentation-de.html:

![image](https://cloud.githubusercontent.com/assets/10995998/23377872/ca348a82-fd31-11e6-85c4-1bc5751d7672.png)

http://www.pioneer-car.eu/eur/:

![image](https://cloud.githubusercontent.com/assets/10995998/23377949/0655da98-fd32-11e6-8d62-e0634decd324.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.10.50
Spyware filter | 1.0.10.81
Social media filter | 1.0.17.55
Annoyances filter | 1.0.10.37
German filter | 1.0.31.69
Mobile ads filter | 1.0.7.16
Safari filter | 1.0.2.59

**Comment by seanl-adg** [comment]
Related to https://github.com/AdguardTeam/AdguardForWindows/issues/1505
