### ISSUE TITLE
http://zfilm-hd.net - pop-up

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4491]
http://zfilm-hd.net/17-agenty-schit-lost.html На этом сайте, во время нажатии кнопки плэй в
видеоплеере, появляется пятнадцатисекундный таймер. Затем, через 15 секунд, появляется надпись: "Пропустить рекламу и продолжить просмотр"; при этом никакой рекламы
нет, но раньше такого не было. Также *открывается новое окно (не вкладка) с
рекламой казино*

![image](https://cloud.githubusercontent.com/assets/15856304/23400025/23ff7f9e-fdab-11e6-8411-dbc5d4d18eaa.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows NT 10.0.14393.0
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Stealth mode options(Windows) | On
Adguard filters: | 1 2 3 4 8 10 105 111 113

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1512612

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
попап не повторяется.
Добавил в русский фильтр
```
yallaneliera.com#%#Object.defineProperty(window, 'adv_enabled', { get: function() { return false; } });
```

**Comment by zebrum** [comment]
как будто бы не починилось. 
@evgeniy-ADG проверь у себя
