### ISSUE TITLE
Yandex direct on mail.yandex.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4492]
![image](https://cloud.githubusercontent.com/assets/15856304/23401318/eb17c4b6-fdaf-11e6-8486-d1654d7874ed.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Opera
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Stealth mode options (Windows) | On
Adguard filters: | 1 2 3 4 19

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1394154

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Удалённо смотреть надо.

**Comment by evgeniy-ADG** [comment]
>Не долго я радовался , снова реклама на яндексе выскочила!

![image](https://cloud.githubusercontent.com/assets/15856304/23702382/a6d8ac8e-0403-11e7-84de-273c2564a295.png)

**Comment by Alex-302** [comment]
Какие фильтры и Адгард? Сертификаты проверили?

**Comment by evgeniy-ADG** [comment]
Непонятно как это проверять в Хромах последних, опиши пошагово как это делать. Если не подменяется, что делать?

**Comment by Alex-302** [comment]
Жмёшь F12 и переходишь к безопасности как на скрине
<details>

![image](http://imagizer.imageshack.com/img924/3645/O2Te2b.png)
</details>

> Если не подменяется, что делать?

проверить в настройках Адгарда и исключениях HTTPS.
Если в `C:\ProgramData\Adguard\NetworkTemp\SSL` есть файлы `xv.db` и `x.db`, то нужно полностью остановить Адгард, удалить их и запустить снова.
И без пользовательского фильтра тоже проверять надо.
