### ISSUE TITLE
WPTV 5 app - the Mobile ads filter breaks video playback

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4493]
https://play.google.com/store/apps/details?id=com.mylocaltv.wptv&hl=ru

This is what's happening when Adguard with the Mobile ads filter is enabled:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/23405971/647477cc-fdc5-11e6-86aa-07135d2112bc.png)

</details>

And when it's disabled:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/23405960/5cf8e06e-fdc5-11e6-9d65-204bcc4b6a87.png)

</details>

[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | 
Adguard version: | 2.8
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On Default
Adguard DNS: | Default
Adguard filters: | Eng, Mobile ads, Social media, Annoaynces, ...

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1124072

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||imasdk.googleapis.com/native/core/*/native_bridge__en.js$app=com.mylocaltv.wptv
```

**Comment by evgeniy-ADG** [comment]
Still doesn't work. 
STR: 

1. Open the app
2. go to the video 
3. Try to watch any -> it doesn't start

**Comment by Alex-302** [comment]
Not reproduced on my device.
Is HTTPS filtering works?
Try this:
```
@@||imasdk.googleapis.com^$app=com.mylocaltv.wptv
```

**Comment by evgeniy-ADG** [comment]
added, restarted and still doesn't work. the https filtering is up and running.

**Comment by Alex-302** [comment]
Strange. Please ask for HTTP log.
