### ISSUE TITLE
http://www.msn.com/ - Skype ads when Skype is running

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4494]
Screenshot:

https://www.dropbox.com/s/ecqychead4b4sxf/Screenshot_1.png?dl=0

Is it possible to get rid of this window?

***Steps to reproduce the problem***:

Go to:
http://www.msn.com/ru-ru/?pc=SK216&ocid=SK216DHP&osmkt=ru-r

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP 
Adguard filters: | 1,2,3,4,5,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1386801

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Yes.
Added to Annoyances filter
```
msn.com#$##skypefredialogcontainer[data-aop="skypefredialog"] { display: none!important; }
msn.com#$#body { overflow: initial!important; }

```
