### ISSUE TITLE
ShoreTel Flex (x64) voip application fails to launch when the Adguard service is running

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4495]
ShoreTel Flex (x64) voip application fails to launch when the Adguard service is running. It throws as an error that "Port 5060 is in use". The workaround is to stop the Adguard service, launch the ShoreTel Flex application, then restart the service. 

Logs: 997994

***System configuration***

Operating system: | Windows NT 6.1.7601 Service Pack 1
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | TDI
Stealth mode options(Windows) | 
>"BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": false,
  "BlockWebRtc": false,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"

Adguard filters: 
>FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
FilterId:116 Name: Wiltteri Url: https://raw.githubusercontent.com/wiltteri/wiltteri.txt/master/wiltteri.txt
**

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I need steps to reproduce.
Is it caused by Stealth mode or by filters?

**Comment by Alex-302** [comment]
@evgeniy-ADG is the issue still actual?
