### ISSUE TITLE
pvpru.com - anti-adblocker

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4497]
http://pvpru.com/
adg.1.4.0
rus en spyware social_media annoyances

![screenshot 2017-03-01 14 06 52](https://cloud.githubusercontent.com/assets/23637588/23457284/5888ab40-fe88-11e6-8ead-2423ebc5b213.png)

**Comment by Alex-302** [comment]
Not reproduced.
Removed few leftovers.

**Comment by zebrum** [comment]
no anti adblock script at the moment.
