### ISSUE TITLE
http://www.forbes.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4498]
http://www.forbes.ru/forbeslife-photogallery/327735-glavnye-figuranty-prezentatsii-apple

![image1](https://cloud.githubusercontent.com/assets/15856304/23459141/b659a298-fe87-11e6-9dc1-3eb17bd2a6c0.png)

Unable to leaf through pics, try to do that a couple of times.

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | 0ff
Adguard DNS: | None
Adguard filters: | 1 2 3 4 12 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1494663

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||tns-counter.ru/tcounter.js$domain=forbes.ru
```
For PRO version add to whitelist
[CODE]
tns-counter.ru
[/CODE]
