### ISSUE TITLE
fclmnews.ru - anti-adblocker 

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4499]
http://fclmnews.ru/
adg 1.4.0
en rus spyware social_media annoyances

![screenshot 2017-03-01 16 37 18](https://cloud.githubusercontent.com/assets/23637588/23462060/6a2ef560-fe9d-11e6-846a-eeae2b386a37.png)

**Comment by Alex-302** [comment]
Fixed
