### ISSUE TITLE
Advanced Download Manager

### ISSUE THREAD

**Issue by DopeUnicorn** [AdguardTeam/AdguardFilters#4500]
![image](https://cloud.githubusercontent.com/assets/25641172/23467708/6f266fb2-fea7-11e6-9f68-68d6f0722ffe.png)

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.8.76
Adguard mode (Android): | Proxy
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On 

Adguard filters: | 
2, 3, 4, 14, 10, 1, 5, 11, 211

Ticket ID(if exists): 1349857

**Comment by Alex-302** [comment]
Встроено.
