### ISSUE TITLE
http://www.cbsnews.com blockig video in Safari

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4503]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

When the client goes to http://www.cbsnews.com/news/department-of-homeland-securitys-intel-wing-in-crisis-mode-over-travel-ban/ in Google Chrome browser, he can watch the video as it should be. However, in Safari browser this video can not be reproduced. He receives a message 'disable your adblocker'. I could reproduce this. Video can not be played. The screen is just black without a message to disable adblocker. 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prntscr.com/eeqynv

![image](http://somehosting.com/adg_on.jpg)
</details>

The user expects Safari to behave the same way as google Chrome. 

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Safari
Adguard version: | 1.4.0
Adguard filters: | English, Spyware, Social media, Annoyance filter, Experimental filter, Safari filter

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1512749

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It doesn't works on my side. This is probably because Flash player is not installed/allowed in Safari
