### ISSUE TITLE
https://sinoptik.com.ru  - Missed ads 

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4506]
***Description***:

Missed ads with Adg extension

Screenshot:

http://imgdepo.com/id/10350874.png

Information | value
--- | ---
Operating system: | Windows 
Browser: | Slimjet Portable, Chrome
Adguard filters: | Rus, Eng, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1510903

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Чисто.
