### ISSUE TITLE
Anti ad-block http://wallstreams.com/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4507]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
Anti ad-block http://wallstreams.com/

Screenshot:
http://prnt.sc/efhzco

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.0
Adguard filters: | 2 3 4 14 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1478777

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
