### ISSUE TITLE
afisha.ru - photos are blocked

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4508]
https://www.afisha.ru/msk/restaurant/173134/

with spyware filter on

![screenshot 2017-03-03 17 14 37](https://cloud.githubusercontent.com/assets/23637588/23554260/5d371fd8-0035-11e7-926a-c30f81d50b36.png)

should be like this: (en rus social_media annoyances) 

![screenshot 2017-03-03 17 20 11](https://cloud.githubusercontent.com/assets/23637588/23554339/b0238b46-0035-11e7-9ea9-cd0dc92e9161.png)

**Comment by Alex-302** [comment]
fixed
