### ISSUE TITLE
Add 'Adblock Protector' list to the default filters

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#4509]
URL: 
`https://raw.githubusercontent.com/X01X012013/AdBlockProtector/master/AdBlockProtectorList.txt`

Mind the #1583 issue, though.

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardForWindows/issues/1584

**Comment by Alex-302** [comment]
Added, but it is disabled until https://github.com/AdguardTeam/AdguardForWindows/issues/1583 is not fixed

**Comment by Alex-302** [comment]
Enabled
Header of this filter was changed:
`! Redirect:` to  `# Download:`
