### ISSUE TITLE
beeline.ru - incorrect blocking

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4510]
***Description***:
https://paycard.beeline.ru/personal/main

"Акции" page is blocked by Adguard

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

**Screenshot:**

<details>

![2017-02-28_23-15-35](https://cloud.githubusercontent.com/assets/22892774/23562926/2a5810b4-004d-11e7-8c6a-3c6d9f8720d1.png)

</details>

**After disabling ADG:**
Screenshot:
<details>

![2017-02-28_23-16-22](https://cloud.githubusercontent.com/assets/22892774/23562949/45e94a0a-004d-11e7-80e3-d67e3c5d687f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | TDI
Adguard filters: | Eng, Spyware, Social, Unblocking useful ads, Russian, User filter is empty

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1259356

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Зачем так долго тянуть? С 28.02 висит.
В шаблонный ответ про основные фильтры добавьте, чтоб сразу ясно было, фильтры или не фильтры ломают.

Зайти на ту страницу не могу, т.к. нужна авторизация. Могу удалённо глянуть.
Или передай на проверку
```
@@||paycard.beeline.ru^$domain=paycard.beeline.ru
```

**Comment by evgeniy-ADG** [comment]
Из-за обовлений намного больше потом обращений, потому иногда может "прописать". Пользвоателю передал.

**Comment by vmalyuta** [comment]
Согласен на ТВ
9 марта в 10-00 мск

**Comment by Alex-302** [comment]
ок. Только напомните, чтоб не забыть.
Можно мой скайп передать `alxbrv`

**Comment by vmalyuta** [comment]
напоминаю о тв в 10

**Comment by Alex-302** [comment]
@vmalyuta я не у компа был. Кто должен был стучаться? Я меня три новых контакта сегодня добавилось, и никто ничего не пишет

**Comment by vmalyuta** [comment]
https://qcrm.supportyourapp.com/#/customer/1259356

**Comment by Alex-302** [comment]
понял. Написал.
