### ISSUE TITLE
http://m.cbn.globoradio.globo.com - problem accessing the site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4511]
The correct link is: http://m.cbn.globoradio.globo.com/home/HOME.htm

**SCREENSHT**
<details>

With Adguard:

![image1](https://cloud.githubusercontent.com/assets/15856304/23576821/7a15cc8e-00b8-11e7-9660-0aa24c4eb2b1.png)

Without Adguard:

![image3](https://cloud.githubusercontent.com/assets/15856304/23576822/7f3d94f8-00b8-11e7-8fd9-2220913e2ab6.png)

</details>
***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.40
Simplified filters(iOS) | Off
Adguard DNS: | Default 
Adguard filters: | 2 3 4 9 11 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1506068

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||google-analytics.com/analytics.js$domain=cbn.globoradio.globo.com
```
