### ISSUE TITLE
fox.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#4513]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

adblocking detected http://www.fox.com/watch/886979651549
you need to use US VPN to access it

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-03-04 at 11 19 19](https://cloud.githubusercontent.com/assets/14153331/23577603/b062f6f4-00cc-11e7-993d-a31bd9889a46.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Safari, Chrome
Adguard version: | 1.4.0 (375)
Adguard DNS: | None

Adguard filters: 
<img width="266" alt="screen shot 2017-03-04 at 11 22 36" src="https://cloud.githubusercontent.com/assets/14153331/23577616/e9b2f0c6-00cc-11e7-9745-cc23563b6390.png">

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1495247

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@Bohdan-SUP 
у меня этот сайт еле грузится, даже без блокировщика не всегда видео начинает играть(после рекламы)
Передай на пробу эту пачку правил

<details>

```
@@||adm.fwmrm.net/p/fox_live/LinkTag2.js$domain=fox.com
@@||1c6e2.v.fwmrm.net/ad/g/*$domain=fox.com
@@||1c6e2.v.fwmrm.net/ad/l/*$domain=fox.com
@@||doubleclick.net^$domain=fox.com
@@||fox.com^$content
@@||fw.adsafeprotected.com/vast/fwjsvid/*$domain=fox.com
@@||fw.adsafeprotected.com/IASVideo.js$domain=fox.com
@@||ad.doubleclick.net^
@@||pixel.adsafeprotected.com/fwjsvid/*/skeleton.js?videoId=$domain=fox.com
@@||m1.fwmrm.net/m/1/*$domain=fox.com
@@||google.com/ads/user-lists/*$domain=fox.com
@@||cdn.adsafeprotected.com^$domain=fox.com
@@||dt.adsafeprotected.com/dt$domain=fox.com
@@||match.adsrvr.org^$domain=fox.com
@@||rtr.innovid.com^$domain=fox.com
@@||player.foxdcg.com^$domain=fox.com
||d2wgn7zv2wvh1n.cloudfront.net/scripts/embed-push.min.js
@@||rubiconproject.com^$domain=fox.com
@@||pagefair.$domain=fox.com
@@||moatads.com^$domain=fox.com
@@||adnxs.com^
@@||pagead2
@@||get.truex.com/*/vast/config$domain=fox.com
@@||serve.truex.com^
@@||media.truex.com/release/3.2/com/truex/placements/vpaid/partners/fw/com.truex.TrueXRenderer.js$domain=fox.com
@@||truex.com^$domain=fox.com
@@||static.doubleclick.net^
@@||googleads.g.doubleclick.net^$domain=youtube.com
@@||gcdn.2mdn.net^$domain=imasdk.googleapis.com
@@||googleadservices.com/pagead/conversion_async.js$domain=fox.com
@@||foxentertainment.hb.omtrdc.net^$domain=fox.com
@@||cdn.optimizely.com^$domain=fox.com
@@||a.fox.com/b/ss/*$domain=fox.com
@@||adm.fwmrm.net/p/fox_live/AdManager.js$domain=fox.com
@@||tags.tiqcdn.com/utag/fox/main/prod/utag.js$domain=fox.com
@@||cdn.segment.com^$domain=fox.com
@@||2364010203.log.optimizely.com^$domain=fox.com
@@||facebook.com/impression.php/*$domain=fox.com
@@||79423.analytics.edgekey.net^$domain=fox.com
@@||dpm.demdex.net^$domain=fox.com
@@||cdn-gl.imrworldwide.com^$domain=fox.com
@@||pixel.quantserve.com^$domain=fox.com
@@||secure-dcr.imrworldwide.com^$domain=fox.com
@@||r1---sn-p5qlsn6e.c.2mdn.net^$domain=imasdk.googleapis.com
@@||load.exelator.com^$domain=fox.com
@@||tags.bluekai.com^$domain=fox.com
```
</details>
Если и реклама и видео заработают, то понадобится доступ, чтоб найти только нужные правила.

**Comment by seanl-adg** [comment]
The video works without any delay on my end with above changes.
