### ISSUE TITLE
yandex direct on hi-tech.mail.ru

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4514]
![image](https://cloud.githubusercontent.com/assets/15856304/23578542/ea0a1e7c-00e1-11e7-9379-c388c6dc20eb.png)

Польз. фильтр пуст, кеш чистели, ненужное отключали.

***System configuration***

Information | value
--- | ---
Operating system: | Microsoft Windows NT 6.3.9600.0
Browser: | Яндекс
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Stealth mode options (Windows) | 
> Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": false,
  "BlockWebRtc": true,
  "BlockBrowserPushApi": true,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": true,
  "HideUserAgent": true,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": true,
  "CustomIp": "209.141.53.254"

Adguard filters: | 
>Subscriptions: FilterId:2 Name: English filter Url: http://adguard.com/ru/filter-rules.html?id=2
FilterId:3 Name: Spyware filter Url: http://adguard.com/ru/filter-rules.html?id=3
FilterId:4 Name: Social media filter Url: http://adguard.com/ru/filter-rules.html?id=4
FilterId:14 Name: Annoyances filter Url: http://adguard.com/ru/filter-rules.html?id=14
FilterId:1 Name: Russian filter Url: http://adguard.com/ru/filter-rules.html?id=1
FilterId:6 Name: German filter Url: http://adguard.com/ru/filter-rules.html?id=6
FilterId:118 Name: EasyPrivacy Url: https://easylist-downloads.adblockplus.org/

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1349719

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня чисто, только две пустые рамки. Убрал их, может и реклама пропадёт. Пусть отпишется.
