### ISSUE TITLE
http://blog.darios.ru/ incorrect blocking

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4516]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:http://blog.darios.ru/ incorrect blocking

If filter "Adblock polskie reguly" is on it's blocking the firts post on the website
Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/23580782/a67e6fd0-0110-11e7-8ff0-8ba501ea5138.png)
![image](https://cloud.githubusercontent.com/assets/25711093/23580800/0883cd4c-0111-11e7-8a4a-85eaa2ca7efa.png)

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS 
Browser: | Chrome
Adguard version: | 1.4.0

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1516111

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Reporter to author of this filter https://github.com/MajkiIT/polish-ads-filter/issues/2271
Temporary rule for user filter: `blog.darios.ru##[class*="reklama"]`
