### ISSUE TITLE
https://www.buzztoon25.com/%EC%9B%B9%ED%88%B0

### ISSUE THREAD

**Issue by YTOAA** [AdguardTeam/AdguardFilters#45177]
https://www.buzztoon25.com/%EC%9B%B9%ED%88%B0

https://www.buzztoon25.com/[%EB%B2%84%EC%A6%88%ED%88%B0]-%EC%97%B4%EB%A0%99%EC%A0%84%EC%82%AC-2%EB%B6%80-21%ED%99%94-%EB%8B%A4%ED%81%AC-5-%EC%9B%B9%ED%88%B0%EB%AF%B8%EB%A6%AC%EB%B3%B4%EA%B8%B0.html

**Comment by BlazDT** [comment]
Please use template.
