### ISSUE TITLE
WPTV 5 app - ad leftover

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4517]
https://play.google.com/store/apps/details?id=com.mylocaltv.wptv&hl=ru

Here's another problem with the app - it contains some placeholders with the spinning circles, can we block that too?

![image](https://cloud.githubusercontent.com/assets/15856304/23585935/54b94750-0193-11e7-83b2-e718c94c6014.png)

STR: Open the app, scroll a few screens down and you'll see the spinning circle of an ad trying to download itself

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | 
Adguard version: | 2.8
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On Default
Adguard DNS: | Default
Adguard filters: | Eng, Mobile ads, Social media, Annoaynces, ...

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1124072

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It has fixed size.
