### ISSUE TITLE
https://www.couponcabin.com/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4518]
https://www.couponcabin.com/

![image](https://cloud.githubusercontent.com/assets/15856304/23586669/7412c31a-01a2-11e7-807d-1dddd87e756a.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | the latest release 
Adguard driver (Windows): | WFP
Adguard DNS: | Default
Stealth mode options(Windows) | Default
Adguard filters: | Eng, Rus, Social, Spyware, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
I can't access the site even without Adguard.
