### ISSUE TITLE
[Extension] http://tree.tv/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4519]
http://tree.tv/film/24877-darvin-%E2%80%94-konechnaya-ostanovka

![image](https://cloud.githubusercontent.com/assets/15856304/23587322/3e17a8f6-01b2-11e7-8655-95dccb3f0033.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: |  2.5.11
Adguard filters: | 
>English filterVersion 1.1.10.96. Updated 4 march 2017 at 19:00.
Spyware filterVersion 1.0.10.86. Updated 3 march 2017 at 19:20.
Social media filterVersion 1.0.17.69. Updated 3 march 2017 at 19:21.
Annoyances filterVersion 1.0.10.57. Updated 3 march 2017 at 19:22.
Russian filterVersion 1.0.47.94. Updated 3 march 2017 at 23:39.
German filterVersion 1.0.31.84. Updated 4 march 2017 at 11:01.
Spanish/Portuguese filterVersion 1.0.86.56. Updated 15 february 2017 at 17:59.
EasyList Czech and SlovakVersion 1.0.1.93. Updated 13 january 2017 at 19:30.
Liste FRVersion 1.0.75.83. Updated 4 march 2017 at 19:32.
Adblock polskie regułyVersion 1.0.6.50. Updated 2 march 2017 at 23:35.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1516094

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed

**Comment by Smorvel** [comment]
@Alex-302 когда подключен фильтр "Фільтр лічильників і системи аналітики", вместо плеера открывается главная страница сайта в окне плеера. Происходит это из за правила /fingerprint2.min.js^

**Comment by Alex-302** [comment]
Интересное явление. Поправил.
