### ISSUE TITLE
nettavisen.no

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#45205]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Videos in articles are blocked due to `||imasdk.googleapis.com^` in *AdGuard Mobile Ads*.
* **Current behaviour**: Same as above. Note that there's also another entry in EasyList that also blocks the videos, as explained in https://github.com/easylist/easylist/issues/4413.
* Example page: `https://www.nettavisen.no/livsstil/dette-er-sannheten-om-greta-thunberg-bildet/3423887035.html`.
* Side note: I have [temporarily added unbreakage entries to my Nordic list](https://github.com/DandelionSprout/adfilt/commit/99ced82005b3a8b76811527b47b6b7762b078acc), although they'll only go live in the AdGuard list version sometime later today.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/69914496-81ba7180-1445-11ea-910f-00cbc2c0879f.png)
</details><br/>

* **Expected behaviour**: Videos in articles show up and are playable.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/69914491-7404ec00-1445-11ea-8125-b6c4c63aae39.png)
</details><br/>

***Steps to reproduce the problem***:

1) Turn on *AdGuard Mobile Ads* and *EasyList*.
2) Navigate to any *Nettavisen.no* article that has a native video at the top.
3) See the video doesn't show up.

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/69914535-dfe75480-1445-11ea-8814-ee84c65b7a1d.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 November 2019 Update
Operating system version (Android/iOS) | N/A
Browser:                               | Chrome 78.0.3904.108 64-bit
AdGuard version:                       | Nano Adblocker 1.0.0.130 + Nano Defender 15.0.0.170
Filters enabled:                       | See screenshot above.
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | N/A
Simplified filters (iOS only)          | N/A
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | N/A
Helpdesk ID (if exists):               | N/A

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by DandelionSprout** [comment]
Update: It appears that EasyList also had a blocking rule against `||imasdk.googleapis.com^$third-party`, meaning that a potential whitelist entry could arguably only have to be added to either one of these two lists, depending on whatever factors.

**Comment by BlazDT** [comment]
Thank you - fixed in our Base filter along with some ads.
