### ISSUE TITLE
[Parental control] https://100realt.ru - parental control false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4520]
https://100realt.ru - сайт для съема/сдачи жилья в аренду. Просят убрать из род. контроля, срабатывает защита для 3 и для 10 лет.

![image](https://cloud.githubusercontent.com/assets/15856304/23587490/fb711bb4-01b5-11e7-9fe4-43fc53d1c310.png)

**Comment by Alex-302** [comment]
@zebrum

**Comment by evgeniy-ADG** [comment]
@zebrum

**Comment by zebrum** [comment]
done
