### ISSUE TITLE
kaspyinfo.ru/lenta-novostej/ - site with ads

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4522]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: kaspyinfo.ru/lenta-novostej/ - site with ads

Screenshot:
http://prnt.sc/egjq9k

***System configuration***

Application version: 1.1.5.65
Optimazed enabled: YES
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.9.60 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.73 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.33 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.10.18 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.47.23 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.7.10 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.51 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.88 Enabled=NO
ID=213 Name="RU AdList: BitBlock" Version=1.0.71.70 Enabled=YES
ID=212 Name="RU AdList: Counters" Version=1.0.68.70 Enabled=NO

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1477730

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
