### ISSUE TITLE
Watson News App - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4524]
If Adguard Pro is enabled I get the following message when opening an article in the Watson News App (www.watson.ch / Apple Store Watson News by Fixxpunkt AG). 

![image](https://cloud.githubusercontent.com/assets/15856304/23601015/04dc9808-0252-11e7-838f-21aebf565088.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Adguard version: | 1.1.6.54
Simplified filters(iOS) | Off
Adguard DNS: | Default 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1516824

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to DNS filter:
```
@@||5471782.fls.doubleclick.net^
```
Add to whitelist(temporary):
```
5471782.fls.doubleclick.net
```

**Comment by sergerosenthaler** [comment]
Problem still exists.

**Comment by Alex-302** [comment]
Did you add this domain to the whitelist?
> 5471782.fls.doubleclick.net

**Comment by sergerosenthaler** [comment]
Added it to the Safari Whitelist instead of the systemwide add blocking Whitelist. After adding the exception to the systemwide add blocking Whitelist, error message is gone. Good work, thank you!

**Comment by Alex-302** [comment]
ok

**Comment by sergerosenthaler** [comment]
Correction: I had to add it to both Whitelists (systemwide add blocking Whitelist and filter Whitelist). I'll keep an eye on this in the coming days.

**Comment by Alex-302** [comment]
we have a little bug with whitelisting, so don't remove this exception)

**Comment by sergerosenthaler** [comment]
Problem returned 5471782.fls.doubleclick.net is still on both Whitelists

**Comment by Alex-302** [comment]
It is caused by a little bug. It will be fixed tomorrow with a new version.

**Comment by Alex-302** [comment]
@sergerosenthaler It works fine with a beta version. Please wait for release.
