### ISSUE TITLE
ozon.ru app for iOS - incrrect blocking / infinite loading

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4525]
OZON.ru https://appsto.re/ru/gXPty.i

![image1 1](https://cloud.githubusercontent.com/assets/15856304/23601142/a5afafb8-0252-11e7-9975-3087126c2a6c.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Adguard version: | 1.1.6.54
Simplified filters(iOS) | Off
Adguard DNS: | Default
Adguard filters: | 1 2 3 4 5 11 12 14 15 207 211

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID (if exists): 1382035

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
Не повторилось, в тикете есть логи в виде скриншотов блокирванных запросов.

**Comment by Alex-302** [comment]
У меня повторилось. Пока пусть добавит в белый список
```
t.appsflyer.com
```

**Comment by Alex-302** [comment]
завтра можно будет удалить их и проверить снова

**Comment by jesusc31** [comment]
Оки. Проверю завтра и дам знать

**Comment by jesusc31** [comment]
Фильтр обновил. Но как была вечная загрузка, так и осталась

**Comment by jesusc31** [comment]
Заработало после выключения всего и повторного включения. Можно закрывать

**Comment by Alex-302** [comment]
Попробуйте добавить в белый список в "Системной фильтрации"
```
t.appsflyer.com
stats.appsflyer.com
```
Либо, если нет этого раздела, то в белый список
```
@@||t.appsflyer.com^$document
@@||stats.appsflyer.com^$document
```
