### ISSUE TITLE
http://video.corriere.it - unable to play video

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4526]
http://video.corriere.it/sfida-ping-pong-piu-lunga-storia-poi-succede-questo/4a9c25b0-fb69-11e6-8df2-f7ebe5fcea94?intcmp=video_wall_hp&vclk=videowall%7Csfida-ping-pong-piu-lunga-storia-poi-succede-questo

![image](https://cloud.githubusercontent.com/assets/15856304/23601762/cbb0b2a4-0255-11e7-9ebb-b0eeeb9e669b.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | 2 3 4 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID (if exists): 1476376

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter:
```
@@||c.betrad.com/geo/h1.js$domain=video.corriere.it
@@||c.betrad.com/pub/c/*.js$domain=video.corriere.it
```
Add `c.betrad.com` to whitelist in Adguard settings.
