### ISSUE TITLE
http://www.kakprosto.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4527]
Пропускает Директ на  http://www.kakprosto.ru/kak-129479-kak-otklyuchit-podpisku-na-sayte.

![image](https://cloud.githubusercontent.com/assets/15856304/23609645/a332ed5c-0277-11e7-9ea7-a472cd9ad1cd.png)

Аналошичные баннеры в центре и внизу страницы.

***System configuration***

Information | value
--- | ---
Operating system: | Все, видимо, повторилось на Мак и на Android
Browser: | Chrome
Adguard version: | 1.4
Adguard DNS: | None 
Adguard filters: |  2, 3, 4, 14, 1, 11, 211

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1150428

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed

**Comment by evgeniy-ADG** [comment]
> В общем - всё прекрасно работает и фильтрует!
> Передайте, пожалуйста, Алексу благодарность за код :)
