### ISSUE TITLE
Yandex search annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4528]
Баннер "Вы нашли, что искали?" в результатах поиска.
Логи:  [debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/821123/debug.txt)

Время: 21:13

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/23610008/8036071a-0279-11e7-8511-cdca23cbc877.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Samsung
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On Default
Adguard DNS: | None 
Adguard filters: | 2, 3, 4, 14, 1, 11, 211

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
не повторяется. От поискового запроса зависит?
