### ISSUE TITLE
Yandex browser self-advertising

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4529]
С установленным уже ЯБ не повторилось. Есть логи, тикет 1150428, от 05.03 21:52

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/23610330/bae420a8-027a-11e7-9fa1-17f54a777662.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Samsung
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On Default
Adguard DNS: | None 
Adguard filters: | 2, 3, 4, 14, 1, 11, 211

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by evgeniy-ADG** [comment]
Аналогично, но у пользователя вот - повторяется и ему надо что-то отвечать. Что посоветовать? Что попросить/собрать?

**Comment by Alex-302** [comment]
HAR нужен
