### ISSUE TITLE
video site thumbnail pictures display problem

### ISSUE THREAD

**Issue by akidox** [AdguardTeam/AdguardFilters#4530]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
This site: http://www.bilibili.com/ , some of the thumbnails would not display with Adguard enabled
[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
![image](https://cloud.githubusercontent.com/assets/15276239/23613901/1fe25a06-02bc-11e7-8805-9cf6f7ed6aa2.png)

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Edge
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP / TDI
Adguard mode (Android): | VPN / Proxy(manual/auto)
Filtering quality (Android): | High-quality / high-speed / simplified
HTTPS filtering (Android): |  On (Default/Blacklist mode) / Off
Simplified filters(iOS) | On / Off
Adguard DNS: | None / Default / Family Protection
Stealth mode options(Windows) | 
Adguard filters: | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.
http://imagizer.imageshack.com/img922/6700/PE1b4j.png
Which filters are you using?

**Comment by akidox** [comment]
I have installed two filters. Easylist China, and Adguard's default English Filter,
![image](https://cloud.githubusercontent.com/assets/15276239/23822602/6d452702-068a-11e7-88cb-db5438faf115.png)

**Comment by Alex-302** [comment]
Ok, reproduced now.
Added to English filter
```
@@||hdslb.com/bfs/archive/*@$domain=bilibili.com,image
```
