### ISSUE TITLE
http://lifebel.com/ - Anti-Adblock

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4531]
Screenshot:

<details>

![screen shot 2017-03-06 at 10 37 21 pm](https://cloud.githubusercontent.com/assets/22892774/23628677/bd50440a-02bd-11e7-8eb3-35cb56a44356.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.0
Adguard filters: | English, spyware, social media, annoyance, experimental, Russian, mobile ads.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1516731

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
||lifebel.com/wp-content/uploads/*^*.js?ver=
```
