### ISSUE TITLE
AdGuard Base whitelist allows some ad content

### ISSUE THREAD

**Issue by jdtsillas** [AdguardTeam/AdguardFilters#45326]
This filter:

! https://github.com/AdguardTeam/AdguardFilters/issues/16141
`@@||yimg.com/uu/api/res^$domain=yahoo.com`

Allows the loading of ad images which can be filtered with this filter:

`||yimg.com^*/api/res/*/ads/`

The images are usually not visible because the containing elements (with class "Feedback") are cosmetically hidden.

An example page:

https://finance.yahoo.com/quote/DVN?p=DVN

Please see the discussion at the end of this thread:

https://forums.lanik.us/viewtopic.php?f=62&t=43951

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.

Thank you for reporting it.
