### ISSUE TITLE
Реклама в Instagram 

### ISSUE THREAD

**Issue by AmiraLV** [AdguardTeam/AdguardFilters#45335]
Почему не блокируется реклама в приложении Instagram? Я купила платную версию с целью блокировки рекламы в приложениях!

**Comment by Alex-302** [comment]
@AmiraLV в некоторых приложениях рекламу невозможно заблокировать. В некоторые приложения она встроена, а другие при блокировке перестают работать. Конкретно Instagram(Facebook) невозможно отфильтровать из-за мер защиты в этих приложениях.
