### ISSUE TITLE
https://www.dnainfo.com/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4536]
https://www.dnainfo.com/new-york/queens/astoria-long-island-city

![image](https://cloud.githubusercontent.com/assets/15856304/23695431/d9eb0584-03e7-11e7-8c96-22d54746d31e.png)

***Steps to reproduce the problem***:

1. Go to the site
2. Select a neighborhood
3. See the pop-up

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | ios
Browser: | safari
Adguard version: | 1.1.5.40
Simplified filters(iOS) | Off
Adguard DNS: | Default
Adguard filters: | English, Annoyances, SM, Spyware, Safari

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1400924

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.
