### ISSUE TITLE
启用自由门软件时AdGuard失效

### ISSUE THREAD

**Issue by MHzsz** [AdguardTeam/AdguardFilters#45365]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
我使用自由门VPN，版本号7.68，在这之后AdGuard完全失效了，不会拦截任何广告。
尝试过将AdGuard设置为HTTP代理，没有效果。
[新建 ZIP 压缩文件.zip](https://github.com/AdguardTeam/AdguardFilters/files/3919661/ZIP.zip)
压缩包内是自由门启动可能需要的文件，可能你们需要测试。

* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)
![image](https://user-images.githubusercontent.com/39558996/70107429-6b98f500-1681-11ea-9486-df9e4a3e1858.png)
上面这张图右边的块状广告以前是不会出现的，现在浏览任何网页都能看到广告。

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909
Browser:                               | Chrome/77.0.3865.93 Safari/537.36 Vivaldi/2.9.1675.11
AdGuard version:                       |7.2.2990 RELEASE

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by accountforadg** [comment]
![image](https://user-images.githubusercontent.com/39081420/70113392-f2ef6400-1693-11ea-99aa-a07a2d932168.png)

Turning on this option should solve your problem.

**Comment by MHzsz** [comment]
@accountforadg 我按照你说的做了，再观察一段时间确认有效。感谢帮助

**Comment by accountforadg** [comment]
> @accountforadg 我按照你说的做了，再观察一段时间确认有效。感谢帮助。

Glad to hear it

**Comment by Alex-302** [comment]
@MHzsz hi. Could you please collect debug logs without that option?

**Comment by MHzsz** [comment]
@Alex-302 希望有帮助
[adg_logs_7.2.2990.0_1204_2224.zip](https://github.com/AdguardTeam/AdguardFilters/files/3922415/adg_logs_7.2.2990.0_1204_2224.zip)

**Comment by Alex-302** [comment]
@MHzsz Thanks.  Could you, please, also collect debug level logs?(logging level can be changed in tray icon menu)

**Comment by MHzsz** [comment]
> @MHzsz Thanks. Could you, please, also collect debug level logs?(logging level can be changed in tray icon menu)

这个就是调试级别的日志。

**Comment by Alex-302** [comment]
Ok, thanks.
