### ISSUE TITLE
http://www.break.com/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4537]
http://www.break.com/

![image](https://cloud.githubusercontent.com/assets/15856304/23695741/54d56f86-03e9-11e7-9567-0882810581e8.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.40
Simplified filters(iOS) | Off
Adguard DNS: | Default 
Stealth mode options(Windows) | 
Adguard filters: | 2 3 4 12 + annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1400924

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
can't reproduce
