### ISSUE TITLE
http://tabletsesmartphones.org/ - anti-ablocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4538]
http://tabletsesmartphones.org/

![image](https://cloud.githubusercontent.com/assets/15856304/23696912/5ca08200-03ee-11e7-9672-0ca0ad02f107.png)

***System configuration***

Information | value
--- | ---
Operating system: | OSX
Browser: | Chrome
Adguard version: | 1.4
Adguard DNS: | None
Adguard filters: | Eng, russian, spanish, annoyances, safari, spyware, social media, mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1518981

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Spanish filter
```
tabletsesmartphones.org##.banner-336x280
@@||tabletsesmartphones.org^$generichide
```
