### ISSUE TITLE
http://kinokrad.co/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4539]
Blocked by the DNS but still go through when using the content blocker only.

![file_000 3](https://cloud.githubusercontent.com/assets/15856304/23699756/fe9e9af6-03f8-11e7-9409-2fd60d246e73.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | the current one
Simplified filters(iOS) | Off
Adguard DNS: | None 
Adguard filters: | English, Russian, Social media, Annoyances, Safari, Experimental, Mobile ads.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 629791

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Safari Content Blocker API can't block web-socket connections.
I will hide it.
