### ISSUE TITLE
https://www.gosuslugi.ru/ - Adguard breaks the site in IE

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4540]
https://www.gosuslugi.ru/

Скриншоты:
<details>

![2](https://cloud.githubusercontent.com/assets/15856304/23701871/5c59b010-0401-11e7-8efc-83932d171c27.jpg)

![Uploading Безымянный4.jpg…]()

</details>

Описание от пользователя:

>При входе в портал госуслуг сайт начинал сыпатся.Вместо русского языка писал по английски. Техподдержка портала разбиралась, и прислала рекомендации. Среди них отключить блокиорвщик рекламы. Точно отключаю, и все работает нормально. Решение..
Включить сайт в искючения. Нажимаю на добавить в ислючения. И ничего не меняетя. Помошник по прежнему зеленый. И никаких следов о исключениях.

1.В Maxthon в ультра-режиме все работает как надо. В ретро режиме 
(совместим с IE) не работает.

2.  STR: Обычный вход в госуслуги. Нажать - каталог. И уже сыпятся надписи на русском.

***System configuration***

Information | value
--- | ---
Operating system: | Microsoft Windows NT 6.1.7601 Service Pack 1
Browser: | IE, Maxthon
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | TDI
Adguard DNS: | None
Stealth mode options (Windows) | see below
Adguard filters: | 1, 2

SM 

<details>
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": false,
  "BlockWebRtc": false,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"
</details>

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1516719

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня нет доступа.
@vozersky глянь, повторяется ли в IE

**Comment by vozersky** [comment]
@Alex-302  

повторяется 

добавление в исключения, ssl-исключения, отключение фильтров, приостановка фильтрации не помогают

только остановка службы

**Comment by Alex-302** [comment]
Ок, тогда здесь закрываю.
