### ISSUE TITLE
https://wapp.baidu.com - missed ad on page 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4541]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://wapp.baidu.com/p/5005604609?lp=5028&mo_device=1&is_jingpost=0&pn=0& - missed ad on page 

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/23713689/5db9b42c-042f-11e7-9d10-2ecb22dabfab.png)

</details>

***System configuration***
Application version: 1.1.5.65
Device: iPhone
Platform: iOS
OS: 10.2.1

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.10.82 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.10.85 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.65 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.10.53 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.1 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.63 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.0.98 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.75.87 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.2.49 Enabled=YES

Ticket ID: 1515917

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It doesn't work, I see blank pagee. I need another link.
