### ISSUE TITLE
com.raildeliverygroup.railcard - broken app

### ISSUE THREAD

**Issue by jimger** [AdguardTeam/AdguardFilters#45413]
Hi, you should add the railcard apk (UK) to the excluded filtering ones. I don't think it contains ads but certainly at least with https filtering it breaks the functionality

**Comment by Alex-302** [comment]
@jimger please send report using AdGuard. We don't know even which platform you are using. And  add download link for this add, + steps to reproduce.

**Comment by jimger** [comment]
@Alex-302 I used the adguard app but it had only to submit url, so I found another menu in the app. It is android platform and more specifically Android 10. App is https://play.google.com/store/apps/details?id=com.raildeliverygroup.railcard

**Comment by Alex-302** [comment]
@jimger you can send report using `Menu -> Support -> Send feedback` and select a type of an issue.
The most options will be filled automatically.
Steps to reproduce are still required. 
Does this app has something, what must be blocked?

**Comment by jimger** [comment]
Nothing has to be blocked... Probably u just need to add it to the excluded
from adguard apps. As far as I know it doesn't have any ads or anything. It
is for some rail cards that provide discounts in UK

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #3255](https://github.com/AdguardTeam/AdguardForAndroid/issues/3255) via [**ZenHub**](https://www.zenhub.com/)
