### ISSUE TITLE
The Rugby Addict app ads

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4542]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

Our customer is getting ads in the app called "Rugby Addict". HTTPS is on, high-quality filtering is enabled, but there is still a banner at the bottom of the app window. I could reproduce this issue on my Android -> the same situation.
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prntscr.com/eho8wo
http://prntscr.com/eho99e

Download the app. Enable Adguard.
Open the app-> you will see the banner at the bottom of your screen.  The Rugby Addict app can be found here - https://play.google.com/store/apps/details?id=com.mashup.fba.rugbyaddict

***System configuration***

Information | value
--- | ---
Operating system: |Android
Adguard version: | 2.8
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard filters: | English, Spyware, Social media, Annoyances, Russian, Experimental, Mobile ads

Ticket ID(if exists): 983289
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
What is incorrectly blocked?

**Comment by Alex-302** [comment]
`"androidVersion" : "7.0 (sdk=24)"`
It is impossible to block HTTPS in apps on this Android version.
If user doesn't use Facebook, he can add `||graph.facebook.com^` and enable DNS filtering
