### ISSUE TITLE
Rules with unsupported modifiers should not be in extension filters

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#4543]
I've noticed: 
$app
$network
$protobuf
$MP4

2017-03-09T09:25:10.254Z: Cannot create rule from filter 11: ||googleapis.com/youtubei/v1/search?$protobuf=73920376, cause Unknown option: PROTOBUF

log.js:71 2017-03-09T09:25:13.894Z: Cannot create rule from filter 11: @@||mc.yandex.ru^$app=ru.yandex.weatherplugin, cause Unknown option: APP

2017-03-09T09:11:48.697Z: Cannot create rule from filter 2: 185.170.56.60:6001^$network, cause Unknown option: NETWORK

**Comment by Alex-302** [comment]
also `$$` rules. For example
```
openload.co$$script[tag-content="if(typeof adblock"]
```

**Comment by Alex-302** [comment]
unsupported rules
* android-content-blocker
`$csp=`
`[-ext-` - Extended CSS
`$app=`
`$protobuf=`
* safari
`$csp=`
`$protobuf=`
* ublock
`$protobuf=`
---
That's not all

**Comment by Mizzick** [comment]
'$protobuf' should be filtered?

**Comment by Alex-302** [comment]
> '$protobuf' should be filtered?

it should be removed from that filter. It is supported only by apps(except iOS)

**Comment by Alex-302** [comment]
unsupported rules
* android-content-blocker
`$csp=`
`[-ext-` - Extended CSS
`$app=`
`$protobuf=`
* safari
`$csp=`
`$protobuf=`
* ublock
`$protobuf=`
* edge, firefox, chromium
`$protobuf=`
* ios
`$app=`
`$protobuf`
Extended CSS rules

**Comment by Alex-302** [comment]
+ Not supported by apps(win, mac, android), ios, and content blocker
`$csp`
`$webrtc`

**Comment by ameshkov** [comment]
I guess we can ignore `$csp` and `$webrtc` in Win/Mac/Android -- they will eventually start supporting it.
