### ISSUE TITLE
[Content Blocker] yourcinema.tv

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#4544]
Ads are not blocked on the website.

**Comment by Alex-302** [comment]
Screenshot, filters, browser?

**Comment by vbagirov** [comment]
Yandex.Browser 

Filters: 
- English
- Russian
- Spyware
- Social
- Annoyances

Screenshots are excessive as it is obvious when you visit the page. If absolutely needed, I can provide them.

**Comment by Alex-302** [comment]
Yandex Browser can't block these ads
