### ISSUE TITLE
Яндекс директ не блокируется мак приложением

### ISSUE THREAD

**Issue by hmage** [AdguardTeam/AdguardFilters#4546]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: яндекс директ не блокируется мак приложением

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

![screen shot 2017-03-04 at 16 27 47](https://cloud.githubusercontent.com/assets/739119/23748908/ab9e1bae-04d6-11e7-8273-74619cea8a81.png)

* **Expected behaviour**: Блок рекламы должен отсутствовать.

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Зайти на https://market.yandex.ru/catalog/54544/list

***System configuration***

Information | value
--- | ---
Operating system: | macOS
Browser: | Safari
Adguard version: | 1.4.0
Adguard DNS: | None
Adguard filters: | English, Spyware, Russian

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
market.yandex.ru##div.headline__footer> div.layout__col > div[data-awaps-stat-url]
```
