### ISSUE TITLE
theindependent.co.uk white rectangle obstruction

### ISSUE THREAD

**Issue by hmage** [AdguardTeam/AdguardFilters#4547]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: Part of the page gets temporarily covered by white rectangle.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot: https://dl.dropboxusercontent.com/u/137524/screenshots/Screen%20Shot%202017-03-09%20at%2020.00.00.mp4

* **Expected behaviour**: Page is not obstructed by white rectangle.

***Steps to reproduce the problem***: Visit http://www.independent.co.uk/news/science/time-crystals-new-matter-atoms-law-physics-break-perpetual-motion-theory-electrons-snowflakes-a7618041.html

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | macOS
Browser: | Safari
Adguard version: | 1.4.0
Adguard DNS: | None
Adguard filters: | English, Spyware, Russian

**Comment by Alex-302** [comment]
fixed
