### ISSUE TITLE
http://www.povarenok.ru/recipes/show/40508/

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4548]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

Banners and ads on the website http://www.povarenok.ru/recipes/show/40508/. The issue is the same for Windows and Mac OS. Persists in all the browsers.:

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prntscr.com/ehyt9k

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome 
Adguard version: |  6.1.314
Adguard driver (Windows): | WFP
Adguard filters: | 1 2 3 4 5 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(1519288): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
