### ISSUE TITLE
rejseplanen.dk - loads blank

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#4549]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Go to rejseplanen.dk, it just shows as a blank white page
They wrap body into a frame - could it be the reason?

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

* **Expected behaviour**: 
The website to show up with no ads :)

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome, Firefox
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Adguard DNS: | None
Stealth mode options(Windows) | disabled

Adguard filters: 
![image](https://cloud.githubusercontent.com/assets/14153331/23767029/af3d7f5a-050f-11e7-8c3f-536507e6f665.png)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1443049

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Russian  filter
```
rejseplanen.dk#@#.bannerRight
```
