### ISSUE TITLE
tut.by In-built banner with a suggestion to subscribe.

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4550]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

On the website tut.by  the user receives a pop-up with the suggestion to subscribe. Is it possible to block the pop-up like that?

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prntscr.com/ehzy8e

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: |  6.1.314
Adguard driver (Windows): | WFP 
Adguard filters: 1 2 3 4 5 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(1512135): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
||tut.by/push/*/app.js
```
