### ISSUE TITLE
Feature suggestion - Filter Blocking Paid Mobile Subscriptions

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4551]
>подскажите когда вы выпустите отдельный фильтр для платных мобильных подписок?(на примере защиты Яндекс протект,у них есть защита от подписок),может вам посотрудничать с
Яндекс для этого?

Are there any plans for this?

Ticket ID: 1150428

**Comment by Alex-302** [comment]
@ameshkov should we block them?

**Comment by ameshkov** [comment]
@Alex-302 we might create a separate filter for it.

**Comment by ameshkov** [comment]
How long will it take to collect all th e domains?

**Comment by Alex-302** [comment]
Maybe a long time, complaints are quite rare.

**Comment by Alex-302** [comment]
I can collect them in annoyances filter as comments

**Comment by ameshkov** [comment]
Actually, is is not a secret and it's easy to find all those websites.

It's just I was thinking about implementing it as a part of the browsing security functionality though.

**Comment by Alex-302** [comment]
> is is not a secret and it's easy to find all those websites.

I have never seen paid subscriptions with my mobile internet(Intertelecom)

**Comment by ameshkov** [comment]
Seems to be specific to russian telecom
