### ISSUE TITLE
kape.cc - missed ads

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4552]
Screenshot:
<details>

![image]
(https://cloud.githubusercontent.com/assets/17320558/23782110/92ed0028-055a-11e7-8246-375441a66416.png)

</details>

***Steps to reproduce the problem***:

http://kape.cc/category/ser/
[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.0
Adguard filters: | User, English, Spyware, Social media, Annoyances, Russian, Experimental, Safari

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1518400

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
added
```
kape.cc##a > img[width="300"][height="250"]
```
