### ISSUE TITLE
Reverting exceptions?

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardFilters#4553]
In the english filter there is `@@||youtube.com/embed/$jsinject` and i would like to revert that with a user filter rule so i can use a userscript on that site. How would i do that?

Exceptionception :D

**Comment by Alex-302** [comment]
No, it is impossible.

**Comment by Bluscream** [comment]
Will a disabled rule in a non-user filter be saved over updates?

**Comment by Alex-302** [comment]
try it)
