### ISSUE TITLE
steamid.eu anti-adblocker

### ISSUE THREAD

**Issue by cicku** [AdguardTeam/AdguardFilters#4554]
Example: [https://steamid.eu/profile/76561198000000001](https://steamid.eu/profile/76561198000000001)

Rule: steamid.eu##div.container:nth-child(4) > div.row:nth-child(3) > div.col-md-12:first-child > div.panel.mainwrap:nth-child(2) > div.panel.mainwrap:first-child

**Comment by Alex-302** [comment]
Fixed in Annoyances filter.
