### ISSUE TITLE
a-d-k.ru

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#4555]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Russian filter breaks the interface at a-d-k.ru

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/14153331/23804758/ec0958be-05c3-11e7-8a6c-e697c4030ff2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS
Browser: | Chrome 
Adguard driver (Windows): | WFP
Adguard DNS: | None

Adguard filters: 
![image](https://cloud.githubusercontent.com/assets/14153331/23804813/2aa4cc70-05c4-11e7-88f7-540bfcca3264.png)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1520240

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
