### ISSUE TITLE
mamba.ru - can't block it with user filter

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4557]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Added m.mamba.ru to user filter

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/23808180/92da4ea2-05d1-11e7-8fda-038c7dc5b877.png)

</details>

Getting this notification just for a second:

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/23808213/b3bd5fe2-05d1-11e7-8209-6dddcc6199dd.png)

</details>

And right after that:

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/23808234/d1ee1074-05d1-11e7-8a9a-89dcfca70ef5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Browser: | Meizu System Browser, Chrome
Adguard version: | 2.9
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard filters: | English, Spyware, Annoyances, Social media, Mobile ads, Russian.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1519769

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
```
||mamba.ru^$empty
```

**Comment by KozelElena** [comment]
What about r0.ru (we tried ||r0.ru^$empty,  ||r0.ru^,  ||r0.ru^$third-party)?

**Comment by Alex-302** [comment]
@KozelElena так что юзеру нужно-то? Не пойму, при чём тут домен рамблера.
