### ISSUE TITLE
AdGuard intercepts wrong link

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#45590]
***Description***:
* **Current behaviour**: 

Clicking on "Groups" or "Friends" causes AdGuard to intercept the link and attempt to open it by itself.

<details><summary>Screenshot:</summary>

![Untitled 2](https://user-images.githubusercontent.com/33634917/70385959-aeb5d980-199b-11ea-894c-b47759fc00ce.png)
![Untitled](https://user-images.githubusercontent.com/33634917/70385960-af4e7000-199b-11ea-9ba7-9d2dce8012d6.png)
</details><br/>

* **Expected behaviour**: 

These shouldn't open as adguard:// links.

***Steps to reproduce the problem***:

Just open the website provided you use AdGuard for Mac.

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | macOS Catalina
Browser:                               | Safari 13
AdGuard version:                       | 3.2 release
Filters enabled:                       | Unspecified
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 1147739

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardForMac #654](https://github.com/AdguardTeam/AdguardForMac/issues/654) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
@akmLaVx wrong repository.
