### ISSUE TITLE
LiveIntent ads are not blocked in macOS Mail

### ISSUE THREAD

**Issue by jensen0914** [AdguardTeam/AdguardFilters#45614]
Using AdGuard 2.2.3.661 (CL-1.5.130), macOS Mojave (10.14.6), Mail 12.4.

See many ads powered by LiveIntent in my mail messages. E.g.,
<img width="803" alt="Screen Shot 2019-12-08 at 8 18 01 AM" src="https://user-images.githubusercontent.com/17097762/70390804-1831ea00-1994-11ea-82d8-6ab841436b4a.png">

**Comment by Alex-302** [comment]
@jensen0914 Hi. Could you, please, forward sample email to `tmail00@yandex.ru`?

**Comment by jensen0914** [comment]
Email was forwarded.

**Comment by Alex-302** [comment]
It seems this ad cannot be blocked, because resources are loaded from mail service proxy.
Where can I subscribe?

**Comment by jensen0914** [comment]
earthsky.org <http://earthsky.org/> via the Subscribe link or directly at https://earthsky.us1.list-manage.com/subscribe?u=e56e7a92b1c5790f7343ef95a&id=c643945d79 <https://earthsky.us1.list-manage.com/subscribe?u=e56e7a92b1c5790f7343ef95a&id=c643945d79>

Seems many newletters I receive from various sites use this same ad method as I'm getting this same ad also in updates from dilbert.com <http://dilbert.com/>, nytimes.com <http://nytimes.com/>, more.

**Comment by Alex-302** [comment]
Thanks. Subscribed using two services.

**Comment by Alex-302** [comment]
@jensen0914 Received. These ads cannot be blocked as I said here https://github.com/AdguardTeam/AdguardFilters/issues/45614#issuecomment-563349232
Which email service do you use - Gmail?

**Comment by Alex-302** [comment]
Checked - this ad cannot be blocked
