### ISSUE TITLE
http://www.godlikeproductions.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4563]
http://www.godlikeproductions.com/forum1/message2067815/pg1

How it's now

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/23822995/fdac84fe-0660-11e7-8c3d-c29f4473aa36.png)

</details>

How it should be

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/23822993/ef9237ce-0660-11e7-881b-824d280dd9a0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | 2 3 4 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1520722

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
added to Safari filter
```
@@||youtube.com/yts/jsbin/player-*/base.js$domain=godlikeproductions.com
@@||youtube.com/yts/jsbin/www-embed-player-*/www-embed-player.js$domain=godlikeproductions.com
```
