### ISSUE TITLE
https://vk.com - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4564]
https://vk.com/app2462_6765 - приложение

![image](https://cloud.githubusercontent.com/assets/15856304/23823236/fdf86238-0666-11e7-9df4-a2345173c48e.png)

https://vk.com/video?q=Тоттенхем%20Эвертон

![image](https://cloud.githubusercontent.com/assets/15856304/23823242/196b39c8-0667-11e7-8680-5441cd4ceff8.png)

https://vk.com/video?q=Атлетико%20М%20Валенсия&z=video-14713151_456242349 -
вот видео с баннером

![image](https://cloud.githubusercontent.com/assets/15856304/23823240/0b0fd3ca-0667-11e7-903f-5a09ca327129.png)

Баннер и видео реклама при запуске видео запускаются не всегда, а вот реклама перед запуском радио приложения регулярно. Вся эта реклама повторяется в браузерах Firefox и Chrom. польз. фильтр пуст.

***System configuration***

Information | value
--- | ---
Operating system: | Microsoft Windows NT 6.1.7601 Service Pack 1 
Browser: |  Firefox и Chromе
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | TDI
Adguard DNS: | None
Stealth mode options(Windows) | внизу
Adguard filters: | 1

<details>

"BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"

</details>

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1218594

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня чисто. Фильтрация HTTPS работает? У тебя повторяется?

**Comment by evgeniy-ADG** [comment]
Нет, не повторяется, я лейбу поставил.

**Comment by Alex-302** [comment]
Про фильтрацию HTTPS уточни, подменяется ли сертификат и включена ли она вообще.

**Comment by evgeniy-ADG** [comment]
Как мне узнать, подменяется ли серт? Хром, Мак.

**Comment by Alex-302** [comment]
на зелёный замок нажать -> соединение -> данные сертификата. Как-то так.
Но судя по наличию помощника, сайт фильтруется.
Можно ещё HAR попросить, но заливать ссылку(архив с паролем) лучше в наш чат.
https://toolbox.googleapps.com/apps/har_analyzer/?lang=ru
Ну и английский фильтр пусть включит, он обязателен.

**Comment by evgeniy-ADG** [comment]
ok, напишу. но на маке оно вот как-то так выглядит:
![image](https://cloud.githubusercontent.com/assets/15856304/23948978/0a00d9f0-098e-11e7-804d-93ba6246e5ca.png)

**Comment by Alex-302** [comment]
в site settings попробуй зайти, там что-то про сертификаты будет

**Comment by evgeniy-ADG** [comment]
Там не то. Я все обшарил.

**Comment by Alex-302** [comment]
вот в сафари

<details>

![image](http://imagizer.imageshack.com/img922/5594/BBgmEc.png)
</details>
вот в хроме(нажатие на значёк ничего у меня не открывает, поэтому смотрю через dev tools):

<details>

![image](http://imagizer.imageshack.com/img924/43/5jm3Gw.png)
</details>

**Comment by KozelElena** [comment]
Прислал HAR.
"Проблему удалось повторить только с приложением "Радио". Пришлет еще, если повторится с видео.

[vk.com1.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/851950/vk.com1.har.zip)

**Comment by Alex-302** [comment]
В HAR рекламы не вижу, как и запросов этого радио.

**Comment by k1M1zzz** [comment]
На данный момент реклама выглядит так:

1. При запуске на долю секунды выскакивает
![1](https://user-images.githubusercontent.com/31099504/29411523-e2f270d6-835d-11e7-9a16-ec665378e1ef.jpg)
2. Потом появляется обратный отсчет
![2](https://user-images.githubusercontent.com/31099504/29411546-fe7e4ffa-835d-11e7-943d-5ed8275b2977.jpg)

**Comment by Alex-302** [comment]
Это Flash. C ним ничего не поделаешь. Нужно ждать, пока Хром окончательно не выпилит поддержку.
