### ISSUE TITLE
https://news.rambler.ru/ - annoyance/ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4567]
https://news.rambler.ru/world/36274042-ukraina-vystupila-za-peresmotr-budapeshtskogo-memoranduma/comments/

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/23830804/e700616a-071b-11e7-8706-20578cd82e6d.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Open the link and scroll down, wait a second, you'll see the banner then.

***System configuration***

Information | value
--- | ---
Operating system: | Microsoft Windows NT 6.1.7601 Service Pack 1
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Adguard DNS: | None 
Stealth mode options(Windows) | below
Adguard filters: | russian, eng, social media, annoyances

SM
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/23830821/29e69ed6-071c-11e7-981c-fa04e30f6c71.png)

</details>

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1516787

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It will dangerous, scrolling is disabled.
Added
news.rambler.ru#%#if (typeof localStorage != 'undefined' && localStorage.setItem) { localStorage.setItem('rnews.disablePopups', '9999999999999'); }

**Comment by zebrum** [comment]
@Alex-302 check it again please
https://news.rambler.ru/starlife/36443628-buzova-proklyala-tarasova/

![screenshot 2017-03-27 18 01 49](https://cloud.githubusercontent.com/assets/23637588/24363123/8144fc84-1317-11e7-9d99-716984cdfb32.png)

**Comment by Alex-302** [comment]
Подправил.
