### ISSUE TITLE
Реклама в Gmail

### ISSUE THREAD

**Issue by sergsinger** [AdguardTeam/AdguardFilters#45677]
Появляется реклама.
Версия приложения 7.11.26.

**Comment by Alex-302** [comment]
О каком приложении речь?

**Comment by sergsinger** [comment]
Gmail.
![Screenshot_2019-12-10-18-38-58-007_com google android gm](https://user-images.githubusercontent.com/45709000/70544218-c7311a00-1b7c-11ea-8ea8-e107f251ad1f.jpg)
![Screenshot_2019-12-10-18-39-08-201_com google android gm](https://user-images.githubusercontent.com/45709000/70544227-c9937400-1b7c-11ea-8911-a81d865bcc59.jpg)

**Comment by sergsinger** [comment]
Ещё реклама не убирается из 2ГИС и есть в приложении TubeMate.

**Comment by Alex-302** [comment]
В этих не заблокировать.
В TubeMate какая реклама?

**Comment by sergsinger** [comment]
> В этих не заблокировать.
> В TubeMate какая реклама?

Печально :-(
В TubeMate когда-то при включении HTTPS пропадала всякая реклама, а теперь вот при запуске видно каждый раз, при проигрывании видео рекламы пока не видел.
![Screenshot_2019-12-10-18-50-56-903_devian tubemate v3](https://user-images.githubusercontent.com/45709000/70545317-702c4480-1b7e-11ea-9c9a-47052efa8ab7.jpg)

**Comment by Alex-302** [comment]
Какой браузер?

**Comment by sergsinger** [comment]
> Какой браузер?

На скриншоте выше - это TubeMate 3.2.8.
Браузер Google Chrome 63.0.3239.107.

**Comment by Alex-302** [comment]
Ничего не понял. TubeMate или Chrome?) Отдельными задачами лучше, с полноценным описанием.

**Comment by sergsinger** [comment]
> Ничего не понял. TubeMate или Chrome?) Отдельными задачами лучше, с полноценным описанием.

Вы спросили про браузер - я ответил про тот, что стоит в системе.
Изначально было сказано, что реклама есть в приложении TubeMate.
С телефона невозможно нормально составить отчёт :-(

**Comment by Alex-302** [comment]
Ну с компа можно. Или хотя бы в разных ишью всё это делать.
