### ISSUE TITLE
http://gidonline.club/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4568]
http://gidonline.club/2011/04/piraty-karibskogo-morya-na-krayu-sveta/

The video won't start, asking to wait for 15 seconds in circles.

![image](https://cloud.githubusercontent.com/assets/15856304/23832191/af877242-0738-11e7-9ef0-4bc588614b1d.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 9.3.5
Browser: | Safari
Adguard version: | 1.1.1.54
Simplified filters(iOS) |  Off
Adguard DNS: | None
Adguard filters: | 1, 2, 3, 4, 11, 12, 14, 15, 115, 212, 213, 207

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
not reproduced
try to disable 115, 212, 213, 207
