### ISSUE TITLE
https://a2zapk.com/43375-zarchiver-donate-0-8-5-pro.html anti adblock

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4569]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

When the customer follows this particular link https://a2zapk.com/43375-zarchiver-donate-0-8-5-pro.html, he receives a message 'It looks like you are using an ad blocker'. I was able to reproduce this issue. Screenshot below:
 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
http://prntscr.com/ej09bw

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |Android
Browser: | Chrome
Adguard version: | 2.8
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On
Adguard filters: | English, spyware, social media, annoyance, experimental, Russian, mobile ads.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1516731

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
