### ISSUE TITLE
missed video ad http://money.cnn.com/data/fear-and-greed/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4571]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
missed video ad http://money.cnn.com/data/fear-and-greed/
if you try to block the element using Adguard assistant, the video is not shown, but the sound is still playing in the background

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/23834452/76be9496-075f-11e7-898d-46367ccb8145.png)

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): |  TDI
Stealth mode options(Windows) | disabled
Adguard filters: | English, spyware, social, annoyance, Russian, experimental, mobile ads,

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is not an ad. Is it starts automatically on your side?
For used filter:
```
||money.cnn.com/data/fear-and-greed/fear-greed-player.html
money.cnn.com###mod-fear-greed-video
```

**Comment by Yana-SUP** [comment]
No, it doesn't
Emailed the customer.
Thank you!
