### ISSUE TITLE
com.netbiscuits.kicker - ad leftover

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4572]
https://forum.xda-developers.com/showpost.php?p=71398615&postcount=2218

**Comment by seanl-adg** [comment]
Not reproduced on my end, but blocked some request that seems to be related to ads.

**Comment by ameshkov** [comment]
Are you on Nougat? Could it be that app now targets Nougat, hence does not allow https filtering?

**Comment by Alex-302** [comment]
Also not reproduced with/without HTTPS filtering(Android 5.1.1)
Blocked some analytics.
