### ISSUE TITLE
http://www.motosiklet.net - missed ad on page

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4573]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://www.motosiklet.net/forum/alpaslan-apak/130799-motosiklet-uzerine-gezi-kitaplari-alpaslan-apak.html - missed ad on page

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/23836685/dcd8c272-0784-11e7-84f0-f39bcae76f86.png)

</details>

***System configuration***

Application version: 1.1.5.40

Device: iPad
Platform: iPhone OS
OS: 9.3.3

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.48 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.10.55 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.17.77 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.10.67 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.6.76 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.66 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.3 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.72.45 Enabled=NO
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.68.61 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.68.79 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.3.24 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.76.10 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=225 Name="Fanboy Anti-Facebook List" Version=1.0.0.8 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1520990

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Turkish filter
```
motosiklet.net##.forumreklamlari
motosiklet.net##.tepebanners

```
