### ISSUE TITLE
http://www.eurogamer.net/ - missed ad

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4574]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://www.eurogamer.net/ - missed ad on page

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/23836766/0ce1a212-0786-11e7-8e64-e632db395ab5.png)

</details>

***System configuration***

Application version: 1.1.5.65

Device: iPhone
Platform: iOS
OS: 10.2.1

Locale: en
Region: gb

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.2.68 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.9.43 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.15.29 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.7.58 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.44.5 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.18 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.1.81 Enabled=YES
ID=101 Name="EasyList" Version=1.0.65.36 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.70.59 Enabled=YES
[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1233914

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
eurogamer.net##.mobile-mpu-wrapper
eurogamer.net###mobile-leaderboard
```
Added to English filter
```
||ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js$domain=eurogamer.net
```
@dzamyshlyayeva check it please after filters update(for example tomorrow)
