### ISSUE TITLE
mindspace.ru - anti-adblocker

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4575]
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/23844811/26c3f170-07cd-11e7-8a49-aeacc94bae34.png)

</details>

***Steps to reproduce the problem***:

https://mindspace.ru/

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Adguard filters: | User, English, Russian

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1042958

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
