### ISSUE TITLE
livejournal.com - bottom panel annoyance

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4576]
Page example:
http://wakeuphuman.livejournal.com/1877.html

Screenshot:
https://monosnap.com/file/Y2j3PSd0C9yV7V2VvZxk0NxizCMyfz

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
livejournal.com##.b-discoverytimes-wrapper
```
