### ISSUE TITLE
Add Polish ads filter to the list of subscriptions

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4577]
Consider adding the new Polish filter to the list of subscriptions:
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt

Homepage: http://www.certyficate.it/
Last modified: 12 March 2017

**Comment by Alex-302** [comment]
In Adguard it is called `Adblock polskie reguły`.
I don't know why.
