### ISSUE TITLE
http://www.sportbikerider.us/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4578]
http://www.sportbikerider.us/

![image](https://cloud.githubusercontent.com/assets/15856304/23856447/6054f17a-0802-11e7-8ee6-2d7751fd3b63.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Browser: | Safari
Adguard version: | 1.1.5.40
Simplified filters(iOS) | Off
Adguard DNS: |  Default 
Adguard filters: | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 2 3 4 11 12 14 118 122 123

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed

**Comment by odinb** [comment]
Try browsing around, after 3-4 pages, it will still block you due to having an ad-blocker.

**Comment by Alex-302** [comment]
@odinb 
please copy this rule to user filter and test on few pages
```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=sportbikerider.us
```

**Comment by odinb** [comment]
Sorry to say, same thing. after 2-5 pages, the block comes back. I also updated all my filters prior to trying (9 updates).

**Comment by Alex-302** [comment]
Strange... Maybe they are using a new blockadblock script.
Please try this(for test):
```
@@*$domain=sportbikerider.us
```
ads will be loaded, but the script should not trigger.

**Comment by odinb** [comment]
Well, it still does after a couple of pages...

**Comment by Alex-302** [comment]
Hmmmm.... I can't reproduce it now.
Please try to temporary disable all filters, except English.
If detection will be reproduced, please copy URLs of the pages here.

**Comment by odinb** [comment]
http://www.sportbikerider.us/SP/663838
