### ISSUE TITLE
youku.com is not able to play videos

### ISSUE THREAD

**Issue by cicku** [AdguardTeam/AdguardFilters#4579]
Youku video is unplayable, it claims `please enable cookies of browser`.

After I disable adguard and open a new tab and paste the same URL, video starts loading.

Then it's able to enable adguard again. This time it's able to play any video.

If you can't reproduce this since you are out of Mainland China, I can help.

Exp: `http://v.youku.com/v_show/id_XMjYzMzAzOTI3Ng==.html`

**Comment by Alex-302** [comment]
please don't ignore provided template.
Open new issue and fill required information.
