### ISSUE TITLE
iOS trackers

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#4580]
||adserver.*.yahoodns.net^
||flurry.agentportal.*.yahoodns.net^ (flurry.com tracker)
||nativead.s3.amazonaws.com^
||mopub-win-us-east.bksn.se^ (adserver for mopub.com)

Saw these in my logs i dont know which apps they came from.

**Comment by Alex-302** [comment]
The first rule has invalid format - `..`
Added to Mobile filter
```
||mopub-win-us-east.bksn.se^
||nativead.s3.amazonaws.com^
||adserver.*.yahoodns.net^

||flurry.agentportal..yahoodns.net^
```
