### ISSUE TITLE
http://putlockertv.is/ - pop ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4581]
http://putlockertv.is/
As soon as you click the search box, a new tab opens up, the same thing happens when you click on the episode of a show.

![file_000](https://cloud.githubusercontent.com/assets/15856304/23893530/800ce748-08a7-11e7-9fca-43965ab9fef6.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | Default 
Adguard filters: | 2 3 4 11 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1453264

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
://*.top^$domain=putlockertv.is
://*.party^$domain=putlockertv.is
```
