### ISSUE TITLE
airly.eu

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#45818]
**Site Sample** | 
----------------|
https://airly.eu/map/pl/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Chrome x64 (lastest)
AdGuard version:                       | **7.3 NIGHTLY** 
Protection Mode:						| **WFP Driver**
Stealth Mode:					       | **enabled**

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

Annoyance

<details><summary><b>Screenshot:</b></summary>

![20191212-1576138092-001](https://user-images.githubusercontent.com/9846948/70694108-1ed79e80-1cbf-11ea-8303-144015ab2630.png)

</details><br/>

@AdamWr @Alex-302

**Comment by FadeMind** [comment]
@AdamWr nowe
![20191222-1577000290-001](https://user-images.githubusercontent.com/9846948/71318825-78498580-2496-11ea-9a4b-c72bc5194c6f.png)
![20191222-1577000372-001](https://user-images.githubusercontent.com/9846948/71318840-97481780-2496-11ea-90e0-22ef12853c04.png)

**Comment by AdamWr** [comment]
Ok, dodałem:
`airly.eu##.app__map-container > .map-container > .map-container__banner`
Dziękuję.
