### ISSUE TITLE
[Extension] Google search ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4582]
![image](https://cloud.githubusercontent.com/assets/15856304/23894060/66cc7508-08a9-11e7-84d8-9b62dc77e46a.png)

Мы почему-то пропускаем рекламу в выдаче результатов, хотя полезная реклама отключена. Появляется при любом запросе в формете "купить *название товара*".

***System configuration***

Information | value
--- | ---
Operating system: | MacOSX, 
Browser: | Chrome 
Adguard version: | Extension 2.5
Adguard filters: | Фильтр счетчиков и системы аналитики, Фильтр виджетов социальных сетей, Фильтр раздражителей, Русский фильтр

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1519284

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
странно. Может в пользовательском фильтре что-то мешает? Надо попробовать экспортировать его и проверить после его очистки.

**Comment by evgeniy-ADG** [comment]
У меня там пусто. Скрин мой.

**Comment by Alex-302** [comment]
> Может в пользовательском фильтре что-то мешает? Надо попробовать экспортировать его и проверить после его очистки.
