### ISSUE TITLE
polsatnews.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#45836]
**Site Sample** | 
----------------|
https://polsatnews.pl

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Chrome x64 (lastest)
AdGuard version:                       | **7.3 NIGHTLY** 
Protection Mode:						| **WFP Driver**
Stealth Mode:					       | **enabled**

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

Socials

<details><summary><b>Screenshot:</b></summary>

![20191212-1576157999-001](https://user-images.githubusercontent.com/9846948/70716802-58bf9980-1ced-11ea-82f2-e50f36827355.png)

</details><br/>

@AdamWr @Alex-302

**Comment by AdamWr** [comment]
Jeśli chodzi o te ikonki w prawym górnym rogu, to my tego (odnośników do portali społecznościowych) nie blokujemy - https://kb.adguard.com/en/general/adguard-filter-policy#social-media-filter

Możesz dodać te reguły do własnych filtrów:
`polsatnews.pl##.nav--social > .nav__items > .nav__item:not(.nav__item--rss)`
