### ISSUE TITLE
Far Cry from Ubisoft - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4584]
Столкнулся с такой проблемой.На компьютере установил игру Far Cry Primal (лицензия). Но если включен Adguard она не может загрузиться. Игра скачана с UPLAY официального сайта UBISOFT, версия 1.3.3, Windows. 

![image](https://cloud.githubusercontent.com/assets/15856304/23896884/9d8019b0-08b3-11e7-9129-62ba73078bf0.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | 
Adguard version: | 6.1.296.1549
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Stealth mode options(Windows) | default
Adguard filters: | 1, 2

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1155556, 1509367, 1518983

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardForWindows/issues/1598

**Comment by Alex-302** [comment]
Если отключить все фильтры, игра запускается?

**Comment by evgeniy-ADG** [comment]
Если снять галку с "Фильтровать все приложения", то да. Вот такая информация есть.

**Comment by Alex-302** [comment]
именно про фильтры спроси. В AdguardTeam/AdguardForWindows#1598 вон баг открыт. Может сама программа ломает
