### ISSUE TITLE
http://www.onet.pl/ - anti-adblocker / annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4585]
http://www.onet.pl/

![image](https://cloud.githubusercontent.com/assets/15856304/23896985/2bf985be-08b4-11e7-8458-41201a170015.png)

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS
Browser: | Chrome
Adguard version: | the latest
Adguard DNS: | None
Adguard filters: | Russian, English, Annoyance, Polskie reguły

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1521891

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed and reported to Polish filter author
https://github.com/MajkiIT/polish-ads-filter/issues/2294

**Comment by F4z** [comment]
@Alex-302 with this rule - `@@||csr.onet.pl/*/csr.js*&callback=onetShowAsynchAds$domain=onet.pl` - I have ads and ads leftovers.

http://www.onet.pl/
http://wiadomosci.onet.pl/nauka/nasa-odnalazla-zagubiona-osiem-lat-temu-sonde/bh9vczj

<details><summary>Screenshots</summary>

![image](https://cloud.githubusercontent.com/assets/11742596/23925949/e9862dd2-0911-11e7-943d-3a26e809972e.png)

![image](https://cloud.githubusercontent.com/assets/11742596/23926038/56430382-0912-11e7-9edf-84b67bba42f3.png)

</details>

**Comment by Alex-302** [comment]
Hmm... Adblock detection is not reproduced now. Removed them.

**Comment by vozersky** [comment]
Reported again:

https://forum.adguard.com/index.php?threads/adguard-is-now-detected-on-www-onet-pl-w10-creators-update.21012/#post-134035

I was able to reproduce.

**Comment by Alex-302** [comment]
It works now.
