### ISSUE TITLE
www.apkmirror.com

### ISSUE THREAD

**Issue by Oizaro** [AdguardTeam/AdguardFilters#45850]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: After enabling annoyance filters, the page not working anymore as expected.
* **Current behaviour**: A semi-trasparent black div appear on the main page, and prevents scrolling and legibility.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://i.ibb.co/kDpfZ0k/Screenshot-20191212-190013-Samsung-Internet-Beta.jpg)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://i.ibb.co/6bxLyB4/Screenshot-20191212-191109-Samsung-Internet-Beta.jpg)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | Android 10
Browser:                               | Samsung Internet Beta
AdGuard version:                       | 3.3.194
Filters enabled:                       | Annoyance
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | Google
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Not reproduced with Annoyances filter on Chrome.

**Comment by Oizaro** [comment]
@BlazDT Could you try with following filters and settings? Thanks...

https://i.ibb.co/HtGxxbR/Screenshot-20191212-210107-Ad-Guard.jpg

On Annoyance exclude the last two obsolete filters (prebake and anti-adblock killer), on Specific Language set "Italian" and on Others set only "AdGuard DNS" and "Barblock".

After this set DNS filter on Google (with also AdGuard filter name domains) and HTTPS filtering on enabled.

**Comment by zloyden** [comment]
Not reproduced on my end. @AdamWr please take a look.

**Comment by Oizaro** [comment]
I assume that can be a combination of annoyance filters and https filtering, because if one these two option is disabled this problem don't happen

**Comment by BlazDT** [comment]
HTTPS filtering is only allowing AdGuard to hide elements on the site. Please note I have both options enabled by standard on my Pixel 3.

**Comment by Oizaro** [comment]
Yes... i'm aware of it, mine was only a behavior description with (and without) these settings on the site in question

**Comment by AdamWr** [comment]
I also can't reproduce it.
Could you please clear cache and cookies on `apkmirror.com` and check again?

**Comment by Oizaro** [comment]
@AdamWr Ok I have done a test on Chrome after the described behavior has occurred on Samsung Browser, and all goes well on Chrome.

**Comment by Oizaro** [comment]
P.S = If I clear the full history on Samsung Browser this site works without problem, but only until the next opening on new tab.

**Comment by AdamWr** [comment]
I guess that you opened this website with AdGuard disabled and script related to cookie notice was loaded and now is in browser cache.
If I understand correctly you are using `Fanboy's Annoyances` filter which is hidding a cookie notice, so that's probably why it happens (I mean that you see only overlay).
You can add this rule to user filter:
`apkmirror.com#@#.qc-cmp-showing`
and you should be able to see a cookie notice and accept it or just clear cache and it should be fine too.

**Comment by Oizaro** [comment]
Nope, adguard was enabled (verified from notifications panel), and yes I have enabled fanboy's annoyance.

**Comment by AdamWr** [comment]
I meant that `Fanboy's Annoyances` filter is hidding a cookie notice, so if you add this rule to user filter:
`apkmirror.com#@#.qc-cmp-showing`
(or disable this list)
then you will be able to accept cookies.

You can also check these rules:
```
apkmirror.com#$#body .qc-cmp-showing.qc-cmp-ui-container { display: none!important; }
apkmirror.com#$#.qc-cmp-ui-showing { overflow: visible!important; }
```

**Comment by Oizaro** [comment]
@AdamWr Thanks, I will test it after that this overlay will appear again (seems that open a new tab is not enough to trigger it).

**Comment by Oizaro** [comment]
@AdamWr Ok, this behaviour occurred again, and I can confirm that only these two rules (both activated) correct the problem.

In this case this follow rule remove the overlay panel: `apkmirror.com#$#body .qc-cmp-showing.qc-cmp-ui-container { display: none!important; }`, meanwhile this reactivate scrolling: `apkmirror.com#$#.qc-cmp-ui-showing { overflow: visible!important; }`

**Comment by AdamWr** [comment]
Ok, added these rules to `AdGuard Annoyances filter`, update should be available in 1-2 hours.

Thank you for checking it.
