### ISSUE TITLE
Missed trackers

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4587]
>Здравствуйте! Был обнаружен сайт,
который можно отнести к категории
счётчиков - counter.24log.es, adguard последней
бета версии 6.1 его не обнаруживает.
Просьба добавить его в фильтры.

Screenshot:
http://i89.fastpic.ru/big/2017/0312/ae/6e5bc373e74417a7c8eb800c527605ae.jpg

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Adguard version: | 6.1.296.1549
Adguard driver (Windows): | TDI
Adguard filters: | 1,2,3,4,5, 14

Ticket ID: 731323

**Comment by Alex-302** [comment]
Добавил в фильтр аналитики
