### ISSUE TITLE
Mediametrics app

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#4589]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Articles won't open with `Simplified domain names filter` enabled

Information | value
--- | ---
Operating system: | Android
Adguard version: | 2.9.17
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None 
Adguard filters: | 2, 3, 4, 14, 1, 11, 15

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1454419

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Try
```
@@||mediametrics.ru^$app=ru.mediametrics
```
Is DNS filtering enabled?
