### ISSUE TITLE
Ads not filtered on https://www.kanald.com.tr/ 

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardFilters#4590]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
Ads on site

Screenshot:

(https://cloud.githubusercontent.com/assets/26342177/23915461/d6361dc0-08f1-11e7-8bd6-fd88d59a1bd2.png)

<details>

![image](https://cloud.githubusercontent.com/assets/26342177/23915461/d6361dc0-08f1-11e7-8bd6-fd88d59a1bd2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system:  | iOS 10
Browser: | Safari
Adguard filters: | Screenshot in Details below
<details>

![screen shot 2017-03-14 at 8 13 34 pm](https://cloud.githubusercontent.com/assets/26342177/23915813/d4740802-08f2-11e7-9635-1683a65c8a37.png)

</details>

Ticket ID(if exists): 
1522673

**Comment by Alex-302** [comment]
What is not blocked?

**Comment by deLumren** [comment]
Background ad and sidebanners (not captured on screenshot, they're lower on the page)

**Comment by Alex-302** [comment]
I don't see ads here.
