### ISSUE TITLE
lalawin.tistory.com - Anti Adblock

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4591]
Screenshot:

http://i.imgur.com/bMWiX1r.png

***Steps to reproduce the problem***:

Go to:
http://lalawin.tistory.com/3555

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS
Browser: | Chrome
Adguard version: | 6.1.314.1628; 1.4.0
Adguard filters: | 1,2,3,4,5,14

Ticket ID: 1480654

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
It is fixed in List-KR.
