### ISSUE TITLE
https://forums.rusmedserv.com/ - anti-adblock

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4592]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

When the customer tries to follow this link https://forums.rusmedserv.com/archive/index.php/t-274415.html he gets a message 'this connection is untrusted'. If Adguard is disabled, this message doesn't appear. Could reproduce this issue in Mozilla Firefox on my Xiaomi Redmi 3.:
 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prntscr.com/ek3hg4

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Mozilla
Adguard version: | 2.9.17
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | 2, 3, 4, 14, 1, 11, 15, 217, 21

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 629301

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is not ad block detection. Reinstall HTTPS to Firefox.
