### ISSUE TITLE
[Extension] https://forum.0day.kiev.ua/ - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4593]
https://forum.0day.kiev.ua/

![image](https://cloud.githubusercontent.com/assets/15856304/23936634/f117b382-095b-11e7-8c10-72d0761fb843.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 2.5
Adguard filters: | below

English filterVersion 1.1.11.85. Updated 14 march 2017 at 11:00.
Social media filterVersion 1.0.17.84. Updated 13 march 2017 at 22:00.
Annoyances filterVersion 1.0.10.81. Updated 13 march 2017 at 23:02.
Russian filterVersion 1.0.48.27. Updated 13 march 2017 at 23:00.
Dutch filterVersion 1.0.9.22. Updated 27 february 2017 at 13:01.
Spanish/Portuguese filterVersion 1.0.86.58. Updated 9 march 2017 at 13:01.
Bulgarian listVersion 1.0.0.13. Updated 4 february 20

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1523257

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
