### ISSUE TITLE
https://www.openx.com/ - false blocking 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4594]
https://www.openx.com/

![image](https://cloud.githubusercontent.com/assets/15856304/23936902/46396896-095d-11e7-84fc-d6b7c67810b8.png)

Here's how it should look:

![image](https://cloud.githubusercontent.com/assets/15856304/23936910/53be75d8-095d-11e7-9200-b4c170afc3f8.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4
Adguard filters: | English, Social media, Spyware, Annoyances, Dutch, Safari, Mobiel ads, Rus, Spanish

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1523256

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. Which filter causes it?

**Comment by evgeniy-ADG** [comment]
Works fine for me today as well.
