### ISSUE TITLE
http://torrent-lynx.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4596]
http://torrent-lynx.ru/browse.php?cat=148&page=0

![image](https://cloud.githubusercontent.com/assets/15856304/23939458/6f58997a-0969-11e7-99c3-a95469ffdba9.png)

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS
Browser: | Chrome
Adguard version: | 1.4
Adguard filters: | 2 3 4 6 9 12 102 105 109 117

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1062351

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
