### ISSUE TITLE
gelbooru.com Incorrect blocking

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4598]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
http://gelbooru.com/index.php?page=post&s=list

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/23948027/e6695fde-0989-11e7-960e-9b14cb6b7fd3.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/26434103/23948063/09de0758-098a-11e7-932a-d94ab64924ad.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac
Browser: | Chrome
Adguard version: | 1.4.0
Adguard DNS: | None 

Adguard filters: 
![screen shot 2017-03-15 at 2 20 24 pm](https://cloud.githubusercontent.com/assets/26434103/23948197/98dfaf88-098a-11e7-9e03-c8f7710bd7d7.png)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1449951

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
