### ISSUE TITLE
Wakelock Detector Lite - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4599]
Link:
https://play.google.com/store/apps/details?id=com.uzumapps.wakelockdetector.noroot&hl=ru

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screenshot_20170312-084555](https://cloud.githubusercontent.com/assets/22892774/23962758/cfbe9302-09b7-11e7-9faf-ab6264078ca3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  "{\"certificateInstalledToSystemStorage\":false,\"mitmList\":\"1024 domains\",\"mitmListMode\":\"WHITELIST\"}",
Adguard filters: | 2, 3, 4, 14, 11, 211

[debug (4).txt](https://github.com/AdguardTeam/AdguardFilters/files/845530/debug.4.txt)

time: 3.38

Ticket ID 1403048

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
As I see in the log, ads are blocked.
Does it happens with disabled internet?

**Comment by Yana-SUP** [comment]
asked the user, thanks
