### ISSUE TITLE
Fathom analytics on protondb.com

### ISSUE THREAD

**Issue by Tibladar** [AdguardTeam/AdguardFilters#46001]
**Description**:

Sites using fathom (e.g. https://www.protondb.com/) track page hits via collect.usefathom.com:
`https://collect.usefathom.com/collector/pageview?p=%2F&h=https%3A%2F%2Fwww.protondb.com&r=&sid=LNULTYDL&tz=UTC&dash=https%3A%2F%2Fwww.protondb.com%2Fproxy%2Ffathom`

ProtonDB has a loading script here: `https://www.protondb.com/proxy/fathom`

**Suggestion:** Block tracking domain `collect.usefathom.com` and loading script on ProtonDB

**Filters:**

Information                            | Value
---                                    | ---
Browser:                               | Firefox 70.0.1
Filters enabled:                       | Spyware, Social media, Annoyances, English, EasyPrivacy, Fanboy's Enhanced Tracking List, AdGuard Tracking Protection

**Comment by Alex-302** [comment]
Blocked.
