### ISSUE TITLE
wildberries.ru

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#46005]
***Description***:
* **Current behaviour**: 

Redirect links to/from this website throw a 404 error.

***Steps to reproduce the problem***:

1. Enable the protection
2. Try following any redir link to/from wildberries, i.e. https://sapi.wildberries.ru/orate/api/v2/redirect/ru/crm/999555/22345443/02754E73-FF5F-852C-0019-0149000F4083/sap=999555_975949&url=https://www.wildberries.ru/catalog/osen-zima

***System configuration***

**Filtering log**
See helpdesk ticket 2374257.

Information                            | Value
---                                    | ---
Operating system:                      | Windows
Operating system version (Android/iOS) | Windows 10 1803+
Browser:                               | Yandex Browser
AdGuard version:                       | 7.2.2990
Filters enabled:                       | Base, Russian
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Disabled
Helpdesk ID (if exists):               | 2374257

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@akmLaVx without AdGuard:
![image](https://user-images.githubusercontent.com/8361299/70918519-d229f580-2027-11ea-986d-1554d786c9c7.png)
How to get URL like that?

**Comment by akmLaVx** [comment]
I'll ask the user.

**Comment by Alex-302** [comment]
@akmLaVx any news?

**Comment by akmLaVx** [comment]
User states that the problematic links originate from their ad mailing subscription. Seems like we'll have to subscribe thru wildberries.ru to receive such email.

**Comment by Alex-302** [comment]
@akmLaVx cannpt find a subscription button:(

**Comment by akmLaVx** [comment]
@alex-302 They also offer SMS subscription here: https://security.wildberries.ru/login?returnUrl=https%3A%2F%2Fwww.wildberries.ru%2F

Perhaps we can try this one?

**Comment by Alex-302** [comment]
@akmLaVx I can't register with my phone number.

**Comment by akmLaVx** [comment]
User has sent their debug logs - see ticket 2374257 for more details.

**Comment by Alex-302** [comment]
@akmLaVx в логе нет упоминания sapi.wildberries.ru / wildberries.ru, только в старом файле.
Нужны шаги для воспроизведения проблемы, иначе починить невозможно(если проблема вообще из-за Адгарда)
