### ISSUE TITLE
https://my.mail.ru/ - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4600]
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![default](https://cloud.githubusercontent.com/assets/22892774/23969614/bbcb765e-09cf-11e7-8033-fbbef6ce0d83.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome (user was able to reproduce in Incognito)
Adguard version: | AppVersion: 6.1.314.1628
Adguard driver (Windows): | TDI
Stealth mode options(Windows) | 1,2,3,4,14

Should Annoyances filter block this filed?

Ticket ID: 630452

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed in annoyances filter
