### ISSUE TITLE
Block adguard on http://xda-developers-forum.blogspot.com/

### ISSUE THREAD

**Issue by alvussar** [AdguardTeam/AdguardFilters#4604]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
blockadblock blocked Adguard on http://xda-developers-forum.blogspot.com

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://www.dropbox.com/s/7xxw8egb04e005c/Screenshot_20170316-211246.png?dl=1)
</details>

* **Expected behaviour**: 
Blocked blockadblock script

Screenshot:
<details>

![image](https://www.dropbox.com/s/7xxw8egb04e005c/Screenshot_20170316-211246.png?dl=1)
</details>

***Steps to reproduce the problem***:
Open site http://xda-developers-forum.blogspot.com on browser Google Chrome

***System configuration***

Information | value
--- | ---
Operating system: | Android 7.1.1 (Nexus 5x)
Browser: | Google Chrome
Adguard version: | 2.9.17b
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None
Adguard filters: | All default

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
