### ISSUE TITLE
AntiAd www.viafree.no

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4605]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Anti AdBlocker on site:
https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/episode-1

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-03-17 at 1 58 44 pm](https://cloud.githubusercontent.com/assets/26434103/24042299/0b3b5d80-0b1a-11e7-99d0-c257409bd6b7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 

Adguard filters: | Screenshot below

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)
<details>

![screen shot 2017-03-17 at 2 05 07 pm](https://cloud.githubusercontent.com/assets/26434103/24042481/d48e183a-0b1a-11e7-8ae5-90df59912e25.png)

</details>
Ticket ID(if exists): 1524323

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It doesn't work on my side even with VPN, I always get en error(`something wrong` - `Noe gikk galt, og videoen kan ikke vises. Vennligst prøv igjen om en stund.`)
Try this rule:
```
@@||v.fwmrm.net/ad/g/1?$domain=viafree.no
```

**Comment by Alex-302** [comment]
also user can check these rules in addition
```
@@||mssl.fwmrm.net/p/MTG_Brightcove_HTML5/AdManager.js$domain=viafree.no
@@||mssl.fwmrm.net/p/MTG_Play_Flash/LinkTag2.js$domain=viafree.no
@@||5d404.v.fwmrm.net^$domain=viafree.no
@@||ads.stickyadstv.com^$domain=viafree.no
@@||ssl-mtgstream.tns-cs.net^$domain=viafree.no
@@||des.smartclip.net^$domain=viafree.no
@@||googletagmanager.com/gtm.js$domain=viafree.no
@@||5828054.fls.doubleclick.net^$domain=viafree.no
@@||track.adform.net^$domain=viafree.no
@@||c.eu1.dyntrk.com/adx/*$domain=viafree.no
@@||sync.search.spotxchange.com^$domain=viafree.no
```

**Comment by seanl-adg** [comment]
I tested the website with a VPN to Norway,
A video plays on my end with
```
@@||fwmrm.net/*/AdManager.js^$domain=viafree.no
@@||v.fwmrm.net/ad/*&cd=$object-subrequest,script,other,third-party
```

**Comment by seanl-adg** [comment]
Oh, actually, I have to add specify a domain.

**Comment by seanl-adg** [comment]
It would be good to have a response from the user who reported this, as I can't reliably determine the video played on my end is the main content, not an ad video.

**Comment by Leethemore** [comment]
From user who added
@seanl-adg Thanks for the help but I still get the commercials.
If u watch on the top left of the viedo (~3 sec after you start it), if it says "videon starter om xx's".
This meens "video starts in xx's" (and is a commercial) :)

**Comment by Alex-302** [comment]
@seanl-adg 
```
@@||v.fwmrm.net/ad/*&cd=$object-subrequest,script,other,third-party
```
please try to "play" with this exclusion. I think it is possibe to make that exclusion, which allow to block ad.

**Comment by seanl-adg** [comment]
Tried to fix in another way, currently the video does not play on my end with a VPN that I was using, I hope someone who reported this can check.

**Comment by Alex-302** [comment]
Ok then

**Comment by Alex-302** [comment]
@OlegSUP please ask user about this issue.

**Comment by OlegSUP** [comment]
Done, waiting for users reply.

**Comment by ghajini** [comment]
With ad blocking extensions disabled,   why video won't play

**Comment by Alex-302** [comment]
News?

**Comment by OlegSUP** [comment]
No reply from the user
