### ISSUE TITLE
www.architetturaecosostenibile.it - incorrect blocking

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4606]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:  https://www.architetturaecosostenibile.it/ - even if the website is whitelisted, ads are still blocked 
* **Current behaviour**: https://www.youtube.com/watch?v=94XoDpz0DpQ  

***System configuration***

Operating system: | Windows

Adguard version: | 6. 1. 314. 1628

Adguard driver: |  TDI

Adguard DNS: | None 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1523285

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
