### ISSUE TITLE
Goal.com

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardFilters#4607]
**Site**: http://www.goal.com/
**Page in question**: http://www.goal.com/en-india/news/221/champions-league/2017/03/16/33695382/which-country-has-the-most-players-still-in-the-champions

The above page is an e.g. On gallery pages in that site, while scrolling between the pages, there's a 'See next slide' page in between. Maybe this is where they shows ads.(Ads are removed btw) Can you remove that annoyance so that there is no pause in between the slides?

http://i.imgur.com/eldCrc9.png

Other pages on site where rule can be tested: http://www.goal.com/en-india/news/2292/editorials/2017/03/17/33726042/englands-most-iconic-stadiums-recreated-in-lego/

**Comment by Alex-302** [comment]
```
||goal.com/static/js?files=$replace=/taboolaSlide:\d\d/taboolaSlide:99/
```
Not for browser extension.

**Comment by The-Commissioner** [comment]
@Alex-302 Thanx but it didn't work out

FF ESR 45.8.0 x64
Adguard 6.1.325.1703

Did you take into consideration the localization that the site does like in the url above 'en-india' or is it not required and its something else?

**Comment by Alex-302** [comment]
try
||goal.com/static/js?files=$important,replace=/taboolaSlide:\d\d/taboolaSlide:99/

**Comment by The-Commissioner** [comment]
@Alex-302 thanx man it works now

**Comment by Alex-302** [comment]
Added to English filter
