### ISSUE TITLE
123movies.is - Incorrect blocking (only Safari)

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4608]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behavior**: 

Shows do not play when Adguard is enabled.

Adding the rule  @@||123movies.is^$domain=123movies.is didn't help.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24068714/b0532936-0b9e-11e7-890e-e7bddba6698f.png)

</details>

***Steps to reproduce the problem***:

Go to Safari 
Use following link: https://123movies.is/film/30-rock-season-3-16902/watching.html

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Safari only
Adguard version: | 1.4.1
Adguard filters: | English, Russian, User, Spyware, Social media, Safari, Annoyances, Experimental

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1313547

[//]: # (This template is for problem reports, for another type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by dzamyshlyayeva** [comment]
here is another issue with the website. when you click on a video, a new tab opens 

![image](https://cloud.githubusercontent.com/assets/23372054/24101040/61d5cd26-0d7f-11e7-97eb-21432d5a3033.png)

Ticket ID 1313547

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@$websocket,domain=123movies.is
```
