### ISSUE TITLE
http://stream.jeem.tv - false positive

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4609]
Please remove "streamer62.eboundservices.com<http://streamer62.eboundservices.com>" from Adguard DNS it is falsely blocking my online video I watch. I cannot play m3u8 unless I whitelist streamer62.  The stream: http://stream.jeem.tv/geo/geonews/playlist.m3u8

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Chrome
Adguard version: | 1.1.6.55
Simplified filters(iOS) | Off
Adguard DNS: | Default 
Adguard filters: | basic + simplified domain filter

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1303217

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by mo0424** [comment]
The main URL to whitelist is "eboundservices.com"

**Comment by mo0424** [comment]
Has this been fixed?

**Comment by mo0424** [comment]
I have Adguard DNS disabled until this "eboundservices.com" gets whitelisted. I can't watch my favourite video stream because it gets blocked.

**Comment by Alex-302** [comment]
Excluded this domain from DNS filter, but this change will not applied immediately.
Please wait few hours.

**Comment by mo0424** [comment]
Thank You all is working now.
On Mar 24, 2017, at 5:35 AM, Alex <notifications@github.com<mailto:notifications@github.com>> wrote:


Excluded this domain from DNS filter, but this change will not applied immediately.
Please wait few hours.

**Comment by mo0424** [comment]
http://stream.jeem.tv/geo/geonews/playlist.m3u8 Stopped working again. I have sent a new file logs from Adguard Pro with mentioning this case number. Seems like the Adguard DNS is too aggressive. Please keep me
Updated when fixed

**Comment by Alex-302** [comment]
It works on my device. Is it caused by filters or by DNS filtering?

**Comment by mo0424** [comment]
It is caused by DNS

Sent from my iPhone

On Mar 28, 2017, at 8:07 AM, Alex <notifications@github.com<mailto:notifications@github.com>> wrote:


It works on my device. Is it caused by filters or by DNS filtering?

**Comment by Alex-302** [comment]
Ok. Turn on DNS filtering log, then enable-disable flight mode and reproduce the issue. After that open that log and find blocked domains and write them here

**Comment by mo0424** [comment]
Added these to whitelist and it is working again. Please whitelist these from DNS. Thanks

streamer60.eboundservices.com<streamer61.eboundservices.com>
streamer61.eboundservices.com
streamer62.eboundservices.com<streamer61.eboundservices.com>
streamer63.eboundservices.com<streamer61.eboundservices.com>
streamer64.eboundservices.com<streamer61.eboundservices.com>
streamer65.eboundservices.com<streamer61.eboundservices.com>




Sent from my iPhone

On Mar 28, 2017, at 8:56 AM, Alex <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok. Turn on DNS filtering log, then enable-disable flight mode and reproduce the issue. After that open that log and find blocked domains and write them here

**Comment by Alex-302** [comment]
Try to whitelist `eboundservices.com` only.

**Comment by Alex-302** [comment]
> eboundservices.com

excluded

**Comment by mo0424** [comment]
eboundservices.com<http://eboundservices.com>
streamer60.eboundservices.com<streamer61.eboundservices.com>
streamer61.eboundservices.com
streamer62.eboundservices.com<streamer61.eboundservices.com>
streamer63.eboundservices.com<streamer61.eboundservices.com>
streamer64.eboundservices.com<streamer61.eboundservices.com>
streamer65.eboundservices.com<streamer61.eboundservices.com>
stream.jeam.tv<http://Www.stream.jeam.tv>

From my testing. All these URL have ties to the stream, it can use any URL for the stream. Better to whitelist all those from DNS. Thanks

Sent from my iPhone

On Mar 29, 2017, at 4:33 AM, Alex <notifications@github.com<mailto:notifications@github.com>> wrote:


eboundservices.com<http://eboundservices.com>

excluded

**Comment by Alex-302** [comment]
Thede domains are not blocking on my side.
