### ISSUE TITLE
http://minfin.com.ua/  - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4610]
http://minfin.com.ua/currency/mb/

![image](https://cloud.githubusercontent.com/assets/15856304/24070579/08de02f4-0bc9-11e7-96e3-f6fcfbadf333.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4
Adguard filters: | Russian, English, SM, Spyware, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1524908

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
