### ISSUE TITLE
https://www.olx.ua - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4611]
Некорректная блокировка на странице: https://www.olx.ua/i2/myaccount/active/
Необходима учётная запись.

1) На всех страницах пишет "Проверьте доступ к интернет" при этом всё грузит. Без Adguard всё ок.
2) В личном кабинете не отображается список моих объявлений. Без Adguard всё ок.

![image2](https://cloud.githubusercontent.com/assets/15856304/24070755/1655a9ac-0bcc-11e7-91be-79b1beab8a3e.png)

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.2.1
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | None 
Adguard filters: | 1 2 3 4 5 11 12 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1518078

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Повторилось только в Сафари.
Добавил в фильтр Сафари
```
@@||olx.ua/static/olxua/naspersclassifieds-regional/olxeu-atlas-web/static/js/xgemius.js
```
