### ISSUE TITLE
https://www.speedtest.net/ - false blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4612]
When logging into an account, redirects to the page which is 'blocked by Adguard': https://www.speedtest.net/ru/user-login.php

![image](https://cloud.githubusercontent.com/assets/15856304/24071041/e40b8f60-0bd1-11e7-8a93-f3b5cc006ea6.png)

***System configuration***

Information | value
--- | ---
Operating system: | MacOSX
Browser: | Chrome
Adguard version: | 1.4
Adguard filters: | 1, 2, 111, 216

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1030934

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
