### ISSUE TITLE
youtube.com - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4613]
https://www.youtube.com/watch?v=tI9F6HRLobE  
https://www.youtube.com/watch?v=uTeOCmZo6D4  
https://www.youtube.com/watch?v=a65nRcVvnKI  
https://www.youtube.com/watch?v=zUCDyq3Pbp8  

![image](https://cloud.githubusercontent.com/assets/15856304/24071126/bd6c49b0-0bd3-11e7-8fa0-dd04a5944eec.png)

***System configuration***

Information | value
--- | ---
Operating system: | Microsoft Windows NT 10.0.10586.0 
Browser: | Chrome
Adguard version: | 6.1.314.1628
Adguard DNS: | None
Stealth: below
Adguard filters: | 1 2 3 4 6 10
<details>
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": true,
  "HideUserAgent": true,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": true,
  "CustomIp": "209.141.53.254"
</details>

har: 
[www.1youtube.com.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/852321/www.1youtube.com.har.zip)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1521656

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Is HTTPS filtering enabled?
