### ISSUE TITLE
https://1free.eu/index.php - no assistant

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4614]
https://1free.eu/index.php

![image](https://cloud.githubusercontent.com/assets/15856304/24071293/4a6eb46c-0bd7-11e7-8455-1030d6fbc1d4.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4
Adguard DNS: | None
Adguard filters: | Basic set of filters

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1498653

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
Is it because of this: 
![image](https://cloud.githubusercontent.com/assets/15856304/24071301/7111940e-0bd7-11e7-8af5-be344930db94.png)

**Comment by Alex-302** [comment]
My Chrome doesn't allow to open this site.

**Comment by evgeniy-ADG** [comment]
Try a couple of times, it didn't open at first try here as well.

**Comment by Alex-302** [comment]
That's because some issues with certificate on this site
https://www.ssllabs.com/ssltest/analyze.html?d=1free.eu
