### ISSUE TITLE
riafan.ru - incorrect blocking

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4617]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
https://riafan.ru/ incorrect blocking
Screenshot:
<details>

http://prnt.sc/eljao1

</details>

Pop-up after ~15 seconds (reproduced on Windows)
Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24077021/73305060-0c48-11e7-81fe-df95edabffad.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS, Windows
Browser: | Chrome
Adguard version: | 1.4.1 / 6.1.314
Stealth mode options(Windows) | off
Adguard filters: | Russian, English, Annoyances, Social media, Spyware

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1449704

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
