### ISSUE TITLE
Ios trackers

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#4618]
settings.crashlytics.com
sdk.appsflyer.com
alogs.umeng.com
alogs.umengcloud.com
stats.umsns.com
mobileanalytics. * .amazonaws.com
device-metrics- * .amazon.com
r.my.com (mymail app tracker)

Found some unblocked trackers in my log

**Comment by Alex-302** [comment]
settings.crashlytics.com - not a tracker
sdk.appsflyer.com - not sure about it
Added
||alogs.umeng.com^
||alogs.umengcloud.com^
||stats.umsns.com^
||mobileanalytics.*.amazonaws.com^
||device-metrics-*.amazon.com^

**Comment by jo2dan23** [comment]
@alex302 crashlytics.com is an analytics domain though and so is appsflyer.com. google says appsflyer is mobile marketing analytics
