### ISSUE TITLE
saavndownload.com [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#46185]
https://saavndownload.com/download/a16904baea52e25e9ad217feaad0b668

Clicking on the text field box shows pop-up. (https://prnt.sc/qcknpa)

Also when any album thumbnail picture is clicked, seeing a pop-up (Ex: https://saavndownload.com/)

https://prnt.sc/qcksba

Checked with AG for Chrome

**Comment by Nzzyme** [comment]
Just checked with uBO this time with AG filters and still see the pop-ups. Can you check?

**Comment by AdamWr** [comment]
This popup is generated by inline script, so if you are using uBO then I think it would be better to report it to uAssets - https://github.com/uBlockOrigin/uAssets/issues

@okiehsch or @mapx- Could you please check it?

**Comment by okiehsch** [comment]
`saavndownload.com##+js(aopr, exoJsPop101)`
works on my end, I will add it.
