### ISSUE TITLE
http://www.canonrumors.com/ - ads / sponsored content

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4620]
http://www.canonrumors.com/another-camera-store-burglary-this-time-midwest-photo-exchange-is-the-victim/

![image](https://cloud.githubusercontent.com/assets/15856304/24079722/4b79e460-0c97-11e7-924e-fe2f914a1f30.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | the latest
Simplified filters(iOS) | Off
Adguard DNS: | Default
Adguard filters: | 1 2 3 4 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1525352

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
