### ISSUE TITLE
bc.geocities.yahoo.co.jp (deprecated)

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#46223]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

[//]: # (Substitute this line with a description of the problem)
A rule in AdGuard Japanese filter and Simplified domain names filter
`||bc.geocities.yahoo.co.jp^`
is no more needed since Yahoo Geocities was shut down.

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

1. Go to any of Geocities-hosted site such as http://www.geocities.jp/maxmkago/capture/capture-sn2.html
2. You will be redirected to https://info-geocities.yahoo.co.jp/ which states Geocities was shut down.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/pan9hg2.png)
</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)
AdGuard Japanese filter, Simplified domain names filter

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Whatever
Operating system version (Android/iOS) | Whatever
Browser:                               | Whatever
AdGuard version:                       | Whatever
Filters enabled:                       | AdGuard Japanese, Simplified domain names

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Great)
