### ISSUE TITLE
http://ria-smi.ru/ missed ads

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4622]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://ria-smi.ru/ missed ads
Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/24082701/89c43014-0cd2-11e7-9aad-f1310e13f5d2.png)
***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | Russian, English, annoyance, social, media, experimental, spyware.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1150428

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Мутный сайт, пародия на новостной, полезного контента он не имеет, но и не фишинг вроде.
Спроси у юзера, откуда он совершил переход на этот сайт. Подозреваю, что там просто реклама не заблокирована.
