### ISSUE TITLE
Anti AdBlocker www.menshealth.com

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4624]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Anti AdBlocker at menshealth.com

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-03-20 at 9 29 26 am](https://cloud.githubusercontent.com/assets/26434103/24091353/44be1dc6-0d50-11e7-9bda-d090f5f1cee3.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

http://www.menshealth.com/guy-wisdom/sean-spicer-green-tie-st-patricks-day 

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | Users, English, Spyware, Social media, Annoyances, Russian

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1252589

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Fixed other sites using similar measures too.
They are abusing several generic blocking rules, I added url whitelisting rules, but they might not be complete. While testing on my end, several different generic blocking rules were used. So I added a JS rule that should work without whitelisting.
