### ISSUE TITLE
forum.manjaro.org

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#46255]
**Site Sample** | 
----------------|
https://forum.manjaro.org/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Chrome x64 (lastest)
AdGuard version:                       | **7.3 NIGHTLY** 
Protection Mode:						| **WFP Driver**
Stealth Mode:					       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

Adguard For Windows does not scanning Manjaro Forum site. 

<details><summary><b>Screenshot:</b></summary>

![20191219-1576758743-001](https://user-images.githubusercontent.com/9846948/71173838-02f66e80-2264-11ea-8c9a-ca36af9567ec.png)

</details><br/>

@AdamWr @Alex-302

**Comment by Alex-302** [comment]
Nothing to block here, I guess. AdGuard can filter it
<details>

![image](https://user-images.githubusercontent.com/8361299/71253500-c3e21f00-2330-11ea-8516-09aacb1eef6d.png)

</details>
