### ISSUE TITLE
Ads displayed in youtube app.

### ISSUE THREAD

**Issue by ChimpuFernandez** [AdguardTeam/AdguardFilters#46251]
![Screenshot_20191219-172455](https://user-images.githubusercontent.com/52345784/71171737-87f18000-2284-11ea-9058-f93ca279e518.png)
![Screenshot_20191219-172427](https://user-images.githubusercontent.com/52345784/71171745-8e7ff780-2284-11ea-81cb-70c74b6be394.png)

Https filtering is on. Shouldn't that ad be completely missing from display ?

If there's any feature I have missed out kindly point me in the right direction, so I can turn it on.

**Comment by zloyden** [comment]
In this app is almost impossible to block ads, please install [YouTube Vanced](https://vanced.app/)
