### ISSUE TITLE
Incorrect blocking ads at www.infowars.com

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4626]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Incorrect blocking on page:
https://www.infowars.com/nsa-documents-prove-surveillance-on-donald-trump-and-alex-jones/

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

<details>

![screen shot 2017-03-20 at 11 00 15 am](https://cloud.githubusercontent.com/assets/26434103/24093429/793d002e-0d5c-11e7-9cb3-1aa844c55392.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |iOS 
Browser: | Safari
Adguard version: | Adguard Pro for iOS
Simplified filters(iOS) | Off
Adguard DNS: | Default 
Adguard filters: | User, English, Spyware, Social media, Annoyances,Mobile ads, Safari

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1526404
Asked DNS log

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
