### ISSUE TITLE
pre-roll Ad at http://www.iqiyi.com/ 

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4627]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Pre-roll ad before the video. This site is in Chineese.

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

 
![screen shot 2017-03-20 at 12 31 57 pm](https://cloud.githubusercontent.com/assets/26434103/24096217/5dfe4892-0d69-11e7-97fa-235b999a789e.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Open any video on this website or try the following link:
http://www.iqiyi.com/v_19rra9k1z0.html?list=19rrkc79q6

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | User, English, Spyware, Social media, Annoyances, Russian, 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1262473

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
> This site is in Chineese.

so user may use Chinese filter(s) - EasyList China, xinggsf
