### ISSUE TITLE
Ad at http://m.quankan.tv/

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4628]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Ad at http://wumaow.com/

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-03-20 at 2 09 11 pm](https://cloud.githubusercontent.com/assets/26434103/24099268/ec2ebfb8-0d76-11e7-9aca-af33ef44547e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | Default 
Adguard filters: | User, English, Social Mediam Spyware, Safari, EasyList, EasyPrivacy, EasyList China, ChinaList+EasyList, CJX's Annoyance List.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1526067

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
