### ISSUE TITLE
se.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#46291]
**Site Sample** | 
----------------|
https://www.se.pl/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Chrome x64 (lastest)
AdGuard version:                       | **7.3 NIGHTLY** 
Protection Mode:						| **WFP Driver**
Stealth Mode:					       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

Ad leftover boxes

<details><summary><b>Screenshot:</b></summary>

![20191220-1576828270-001](https://user-images.githubusercontent.com/9846948/71239120-0e9a7180-2306-11ea-9370-24dee8efab23.png)
![20191220-1576828289-001](https://user-images.githubusercontent.com/9846948/71239121-0e9a7180-2306-11ea-83f0-a2d5675ed6f2.png)

</details><br/>

@AdamWr @Alex-302

**Comment by AdamWr** [comment]
U mnie to jest ukryte przez polską listę.
@FadeMind Mógłbyś proszę sprawdzić tę regułę:
`se.pl##div[class^="zpr_inside_"][class*="placement__lazy"]`

**Comment by FadeMind** [comment]
@AdamWr  dzięki, jest OK

**Comment by AdamWr** [comment]
Dodałem, dziękuję za sprawdzenie.
