### ISSUE TITLE
Ad at http://wumaow.com/

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4629]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Ad at http://wumaow.com/

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-03-20 at 1 52 31 pm](https://cloud.githubusercontent.com/assets/26434103/24098794/01338e5e-0d75-11e7-99bf-452ed7cc22c5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard DNS: | Default 
Adguard filters: | User, English, Social Mediam Spyware, Safari, EasyList, EasyPrivacy, EasyList China, ChinaList+EasyList, CJX's Annoyance List.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1526067

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. EasyList China blocks ads completely.

**Comment by OlegSUP** [comment]
![image](https://cloud.githubusercontent.com/assets/26434103/24149996/22da82a0-0e4d-11e7-9fc2-7f406accee66.png)

Reproduced on my Android with EasyList China :( Unable to reproduce on Mac. The only difference in filters is that there's  ChinaList+EasyList on Mac app.

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||m.flowcodeapp.com^$domain=wumaow.com
```
Please check.

**Comment by dzamyshlyayeva** [comment]
same issue here 

<details>

![image](https://cloud.githubusercontent.com/assets/23372054/24577276/7a604dfa-16d3-11e7-9255-f6795f960bcf.png)

</details>

Application version: 1.1.5.65
Device: iPhone
Platform: iOS
OS: 10.3
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.13.41 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.11.22 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.18.28 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.7.67 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.78 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.20 Enabled=YES
ID=101 Name="EasyList" Version=1.0.69.41 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.77.30 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.77.62 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.2.74 Enabled=YES
ID=220 Name="CJX's Annoyance List" Version=1.0.1.19 Enabled=YES
ID=228 Name="xinggsf" Version=1.0.1.5 Enabled=YES

Ticket ID 1526067

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||sube.puwangkj.com^$third-party
||m.jsqinvest.com^$third-party
||tongqing2015.com^$third-party

```
