### ISSUE TITLE
http://www.eenadu.net - missed ad on page 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4630]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://www.eenadu.net/homeinner.aspx?category=home&item=break28 - missed ad on page 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/24101266/509bdf9a-0d80-11e7-8586-60e4a4e719b3.png)

</details>

***System configuration***

Application version: 1.1.5.65
Device: iPhone
Platform: iOS
OS: 10.2.1

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.7.66 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.49 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.89 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.24 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID:  1525282

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I don't see ads here.
Fixed ad block detection.
