### ISSUE TITLE
shazam app - missed ad 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4631]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:  even with HTTPS filtering enabled there is a bottom banner in Shazam app

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/24111641/d00702c2-0d9f-11e7-8b58-65f67be48141.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Operating system: | Android 
Adguard mode : | VPN 
Filtering quality: | High-quality 
HTTPS filtering: |  On (Default)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 980531

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by dzamyshlyayeva** [comment]
the same issue. Adguard version 2.9, HTTPS enabled
Ticket ID:1464571

**Comment by Alex-302** [comment]
Not reproduced.
Please ask for HAR file.

**Comment by dzamyshlyayeva** [comment]
asked for HAR file. waiting for a reply

**Comment by Yana-SUP** [comment]
HAR file is here:
https://we.tl/FvdnN6w7r6

18:29

**Comment by Alex-302** [comment]
As I see, HTTPS filtering is not working.
Try this rule
```
||graph.facebook.com^$app=com.shazam.android
```

**Comment by Yana-SUP** [comment]
done, waiting for his reply
