### ISSUE TITLE
comicbook.com - Anti Adblock

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4632]
Can not reach comicbook.com, even if this website is whitelisted.
Adding to HTTPS exceptions doesn't help.
I was able to reproduce the issue.

The information below is mine:

Screenshot:

<details>

![1y5nxoeispa](https://cloud.githubusercontent.com/assets/22892774/24121007/53295bc2-0dbf-11e7-9c07-f26285aa0d86.jpg)

</details>

Information | value
--- | ---
Operating system: | Android 
Browser: | Chrome
Adguard version: | 2.9.37
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | 2, 3, 4, 1, 11

my debug file:
[debug (2).txt](https://github.com/AdguardTeam/AdguardFilters/files/856326/debug.2.txt)

time: 10.43

Customer ID: 1154936

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||p.d.0mme.com/v4/$script,domain=comicbook.com
```
