### ISSUE TITLE
Не блокируется видео реклама в роликах на Ютубе

### ISSUE THREAD

**Issue by TyroSpy** [AdguardTeam/AdguardFilters#46335]
В режиме просмотра на ПК реклама блокируется, а в режиме "воспроизведения на ТВ" - НЕТ

**Comment by Alex-302** [comment]
Мало информации. Отправьте отчёт с помощью Адгарда.
Как повторить проблему?

**Comment by TyroSpy** [comment]
В браузере Google Chrome если запустить воспроизведение ролика на Ютубе то можно нажать кнопочку режима "воспроизвети на телевизоре" и тогда ролик будет стримиться по сети прямо на телек(протокол DLNA или как там это называется). Так вот в этом режиме AdGuard бессилен, т.е. в ролики проскакивают видео вставки с рекламой. Что я могу послать вам? Допустим я смотрю часовой ролик и там 2..3 рекламные вставки. Теоретически могу послать журнал AdGuard и указать время где была реклама.

**Comment by Alex-302** [comment]
А где кнопка-то? Не вижу. Телек со смартом и ютубом в этой же сети.

**Comment by TyroSpy** [comment]
Внизу справа http://ipic.su/7yIcb0.png Но она будет только в Google Chrome

**Comment by Alex-302** [comment]
В общем тут не заблокировать, т.к. браузер передаёт на телек не трафик, а ссылку, которую телевизор воспроизводит самостоятельно.
