### ISSUE TITLE
BlockAdblock on linkneverdie.com

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdguardFilters#4634]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
linkneverdie.com block me. i'm also using Greasemokey (added Anti-Adblock-Killer | Reek) but not working

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://i.imgur.com/yAO8OyZ.png)
</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS / Android / Linux
Browser: | Firefox
Adguard version: | 6.1.314.1628
Stealth mode options(Windows) | No
Adguard filters: | AakList, ABPVN List, English List

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is fixed in ABPVN List

**Comment by bigdargon** [comment]
i updated Adguard filters but not working

**Comment by Alex-302** [comment]
@bigdargon no, the fix for this site is located in ABPVN List.
This rule:
```
@@||linkneverdie.com$generichide
```

**Comment by bigdargon** [comment]
@Alex-302 i updated all filters and i found this rule in ABPVN but not working. This site also block me

**Comment by Alex-302** [comment]
@bigdargon could you please provide me remote access via teamviewer?

**Comment by bigdargon** [comment]
@Alex-302 Thanks you! i reported to ABPVN and they fixed filters in next version

**Comment by Alex-302** [comment]
I think, your filter just was old.
This rule is fix for this site:
```
@@||linkneverdie.com$generichide
```
