### ISSUE TITLE
http://www.ynet.co.il/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4635]
http://www.ynet.co.il/home/0,7340,L-8,00.html

![image](https://cloud.githubusercontent.com/assets/15856304/24137339/fc65a536-0e1b-11e7-9d39-f2ea86a57ce9.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Safari
Adguard version: | 1.4
Adguard DNS: | None
Adguard filters: | English, Social media, Hebrew, Annoyances, Safari

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1180905

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
||ynet.co.il/*/Teaser/MarketSchedual_
ynet.co.il##.HomepageTwoDivAds
ynet.co.il##div[id^="marketschedual"]
ynet.co.il##.block.B2b.spacer div.dy_unit
ynet.co.il##.block.B1.spacer div.general-image

```

**Comment by OlegSUP** [comment]
@Alex-302 I'm still getting it on Mac, 1.4.1
![screen shot 2017-03-21 at 8 13 38 pm](https://cloud.githubusercontent.com/assets/26434103/24163611/beb9ab12-0e73-11e7-977c-eb1ac1466192.png)

**Comment by Alex-302** [comment]
Added to English filter
```
ynet.co.il##.promolightboxmvc
ynet.co.il##div[class^="MarketingCarousel"]

```
