### ISSUE TITLE
antarvasnaphotos.com [NSFW] [Incorrect Blocking]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#46354]
antarvasnaphotos.com

Unable to view Photos on the page when AG is enabled.

**Comment by Nzzyme** [comment]
Can you please also remove the pop-ups seen when clicking on any links

Ex: https://www.antarvasnaphotos.com/pushpa-aunty-ki-garam-chudai/

Screenshot: https://prnt.sc/qe8hml

**Comment by BlazDT** [comment]
They are already fixed for me with the added cookie rule from the commit:
`antarvasnaphotos.com#%#document.cookie = "poppied=true";`
