### ISSUE TITLE
https://repo.xarold.com - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4636]
Bloqueo en página incorrecto:
{https://repo.xarold.com/nouveautes.php}

Incorrect blocking on that page.

![image1 1](https://cloud.githubusercontent.com/assets/15856304/24139937/db203ea8-0e26-11e7-8b54-3d929790ba41.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOD
Browser: | Safari
Adguard version: | the current release version
Simplified filters(iOS) | Off
Adguard DNS: |  Default 
Adguard filters: | 2 3 4 9 12 211

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1451994

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
ашчув
