### ISSUE TITLE
http://price.ru/ - the Assistant icon disappears when clicking on it

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4637]
http://price.ru/mobilnye-telefony/deshevye-telefony-nokia/

1
![image](https://cloud.githubusercontent.com/assets/15856304/24143946/2df0636c-0e34-11e7-9746-20039703688f.png)

2
![image](https://cloud.githubusercontent.com/assets/15856304/24143961/3667cca6-0e34-11e7-9cd2-5bcd55dd8a84.png)

***System configuration***

Information | value
--- | ---
Operating system: | MacOS
Browser: | Chrome
Adguard version: | 1.4
Adguard DNS: | None
Adguard filters: | Russian, English, Social media, Annoyances and Safari

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1526367

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
btw, can we block that pop-up?

**Comment by Alex-302** [comment]
About assistant - it will be fixed in the new version.
Temporary solution:
```
price.ru#$#html > body > iframe#adguard-assistant-dialog { height: 410px!important; }
```
Ad is blocked.
