### ISSUE TITLE
Ad blocking removal at http://books-audio.in

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4638]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Representative of this site asked us not to block useful ad, like list of book stores with similar books.
Is that possible?
Code of ads from user:
"Вот этот код  
<script type="text/topadvert">
load_event: page_load
feed_id: 13177
pattern_id: 9049
book_author: 
book_name: 
</script><script type="text/javascript" charset="utf-8" defer="defer" async="async" src="//loader.adrelayer.com/load.js"></script>

и вот этот 
<script type="text/topadvert">
load_event: page_load
feed_id: 13724
pattern_id: 9049
book_author: 
book_name: 
</script><script type="text/javascript" charset="utf-8" defer="defer" async="async" src="//loader.adrelayer.com/load.js"></script>

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24162480/553c6de4-0e70-11e7-9067-73154d7dbf0c.png)

</details>

Ticket ID(if exists): 1526645

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
No, our policy has been changed. 
`We unblock only websites' self-promotion and search ads.`
