### ISSUE TITLE
Google syndication not blocked on adguard dns ios

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#4639]
I know I can block it myself but just curious why pagead2.googlesyndication.com Is unblocked. I dont see it in the exceptions or exclusions list

**Comment by jo2dan23** [comment]
![img_0098](https://cloud.githubusercontent.com/assets/15130139/24165731/343fa6e6-0e3f-11e7-9682-73aa89bcd651.PNG)

**Comment by jo2dan23** [comment]
Found it. Theres a typo in the filter list

![img_0102](https://cloud.githubusercontent.com/assets/15130139/24169840/d174ff30-0e4c-11e7-9f6b-81b5769049fd.PNG)

**Comment by jo2dan23** [comment]
@Alex-302

**Comment by Alex-302** [comment]
It is not a typo. googlesyndicatiion.com is not related to Google.
Where did you find unblocked googlesyndication.com?

**Comment by jo2dan23** [comment]
pagead2.googlesyndication.com is a ad domain by google it shows up multiple times in my log idk why its not in the filter list

**Comment by Alex-302** [comment]
Because it will cause a lot of problems. 
As I know, ads are blocked.

**Comment by jo2dan23** [comment]
Oh ok my bad..
