### ISSUE TITLE
Cannot login to skype

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4640]
It says it doesn't recognize the login.

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/24163639/d0feb6aa-0e73-11e7-921e-d242bdecb45f.png)

</details>

Adguad is disabled:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/24163683/f61269a0-0e73-11e7-89ee-2ede7f7fd18a.png)

![image](https://cloud.githubusercontent.com/assets/15856304/24163701/037ceb38-0e74-11e7-93ea-01bd3458c980.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | 
Adguard version: | 2.9
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On Default (disabled for skype)
Adguard DNS: | Default 
Adguard filters: | Eng, Russian, Spyware, Social media, Spyware, Annoyances, Mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
Not sure, but there seems to be a problem with web.skype.com as well.

**Comment by Alex-302** [comment]
Not reproduced on my device.
Can you login with disabled filters or/and with this rule `@@||skype.com^$document` ?
