### ISSUE TITLE
Incorrect blocking at http://www.bilibili.com/

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4641]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Incorrect blocking at http://www.bilibili.com/blackboard/help.html#p

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-03-21 at 10 10 40 pm](https://cloud.githubusercontent.com/assets/26434103/24168595/6e6c529e-0e83-11e7-8b34-b663eefbd0c6.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Without Adguard

Screenshot:
<details>

![screen shot 2017-03-21 at 10 02 52 pm](https://cloud.githubusercontent.com/assets/26434103/24168629/88b7200c-0e83-11e7-9312-d81210aae502.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | User, Spyware, Social media, Annoyances, Russian, EasyList China, ChinaList+EasyList

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1186462

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
