### ISSUE TITLE
Ad in ivi app for Android

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4642]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Missed ad in https://play.google.com/store/apps/details?id=ru.ivi.client&hl=en
HAR file:
https://we.tl/m8ar0SwzAx
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24168975/d0f2e56c-0e84-11e7-9a1d-61953ce9c360.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |Android
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Blacklist mode)
Adguard filters: | Russian filter, English filter, Spyware filter, Social media filter, Mobile Ads filter, 	Annoyances filter, Anti-Adblock Killer | Reek.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1150428

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
> HTTPS filtering (Android):	On (Blacklist mode)

try with default mode. Ads are blocked on my side.

**Comment by evgeniy-ADG** [comment]
"sourceApk" : "/data/app/com.adguard.android-1/base.apk",
  "sslMitmConfiguration" : "{\"certificateInstalledToSystemStorage\":null,\"mitmList\":\"1024 domains\",\"mitmListMode\":\"WHITELIST\"}",
  "statisticsInfo" : "Blocked threats:279; Blocked 
 [ 2, 3, 4, 14, 1, 11, 211 ], HQ
![screenshot_20170404-121306](https://cloud.githubusercontent.com/assets/15856304/24649884/2c5101b2-1931-11e7-8619-cc67bd1b4eba.png)

**Comment by Alex-302** [comment]
`12-13` - в течение часа? Мне б минуты лучше

**Comment by Alex-302** [comment]
Не вижу вообще заблокированного для этого приложения. Фильтрацию для него не отключили случайно?
Ещё мне нужно название фильма, регион, в котором находится юзер, и, желательно HAR, записанный после полной остановки этого приложения и очистки кэша `Адгарда`(чтоб старые логи стёрлись)

**Comment by OlegSUP** [comment]
Еще один случай с ivi. Так же есть реклама в peer.tv https://play.google.com/store/apps/details?id=ru.cn.tv&hl=en

Скриншот

<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24673204/2726b6ce-1980-11e7-9d22-c1fb38e35a1d.png)

</details>

Logs, time 18.44: 
[debug (1).txt](https://github.com/AdguardTeam/AdguardFilters/files/894165/debug.1.txt)

Ticket ID: 1521536

**Comment by Alex-302** [comment]
Вторая прога с ivi никак не связана, реклама не повторяется.
По ivi - прочти коммент выше.

**Comment by OlegSUP** [comment]
Отправил запрос на информацию и HAR

**Comment by OlegSUP** [comment]
От пользователя 1150428  :
"Московской области, сериал
Щит, 3 серия ."

Фильтрацию не отключили
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24741142/684899b4-1aad-11e7-9e8c-e93376918575.png)

</details>

**Comment by deLumren** [comment]
Пользователь добавил 1150428 ХАРы и еще больше скриншотов.

**Comment by OlegSUP** [comment]
User 1521536 :
Я нахожусь в Нижегородской области. г.Кстово. Иногда adguard блокирует всю рекламу в приложении ivi,а иногда реклама появляется,когда включаешь непосредственно сам плеер-перед просмотром фильма,независимо какого

HAR
 [Archive.zip](https://github.com/AdguardTeam/AdguardFilters/files/907183/Archive.zip)

**Comment by Alex-302** [comment]
Через пару часов можно будет обновиться и проверить снова.

**Comment by evgeniy-ADG** [comment]
1150428 - тут не помогло, фильтры проверят каждый час.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
попроси новый HAR, с предварительной очисткой кэша ivi

**Comment by evgeniy-ADG** [comment]
Не дает залить zip сюда, потому последний har в тикете, от 24 числа, 1150428

**Comment by Alex-302** [comment]
@OlegSUP 
Проверять с выключенным мобильным фильтром по отдельности:
- первый вариант
```
||api.ivi.ru/light/$replace=/"files":[\s\S]*"mraid_file_url"/"files": []\, "mraid_file_url"/
||api.ivi.ru/light/$replace=/"files":[\s\S]*"mraid_file_url"/"files": []\, "mraid_file_url"/,important
```
- второй
```
||api.ivi.ru/light/$replace=/\"third_party_adv_xml_link\": .*?\,/"third_party_adv_xml_link": null\,/
||api.ivi.ru/light/$replace=/\"third_party_adv_xml_link\": .*?\,/"third_party_adv_xml_link": null\,/,important
```
Если какой-то вариант поможет, нужно будет проверить ещё это правило в дополнение к решившим проблему:
```
||api.digitalaccess.ru/logger/adv/problems/
```

**Comment by evgeniy-ADG** [comment]
Не помогло, говорят

> Проверил , ничего не сработал, одна
> реклама везде проскакивает, думал что
> в кеше , очищая в итоге тоже
> самое..реклама есть..но правда везде
> одна,и не везде, а через серию ..

**Comment by Alex-302** [comment]
Очень странно. А режим фильтрации - качественный?

**Comment by evgeniy-ADG** [comment]
"filteringQuality" : "FULL",

Вот тут еще жалоба и лог: 1443607, попросил HAR еще.

**Comment by Alex-302** [comment]
Угу, нужен HAR, желательно со скрином рекламы или её описанием.

**Comment by vmalyuta** [comment]
id 1443607
прислал логи

**Comment by Alex-302** [comment]
у него же фильтрация HTTPS не включена.
В state.txt
`"sslMitmConfiguration" : null`
