### ISSUE TITLE
qatarshares.com - site with ads

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4643]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: qatarshares.com - site with ads

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/emtw4i

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.1.5.6
Optimazed enabled: YES
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.37 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.6 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.16.21 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.8.62 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.0.90 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.6.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.5 Enabled=YES
ID=101 Name="EasyList" Version=1.0.66.48 Enabled=YES
ID=112 Name="Liste AR" Version=1.0.14.58 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.72.42 Enabled=YES

Ticket ID(if exists): 1354928

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
