### ISSUE TITLE
Missed ad in hh.ru app

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4644]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Missed ad in https://play.google.com/store/apps/details?id=ru.hh.android&hl=en

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24170018/0f8f567c-0e88-11e7-9a33-75876d8f7890.png)

![image](https://cloud.githubusercontent.com/assets/26434103/24169984/fc1bc35a-0e87-11e7-9834-b3014eb97e89.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Open any job application and scroll down to the bottom of the page.

***System configuration***

Information | value
--- | ---
Operating system: |Android
Adguard version: | 2.8.76
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Blacklist mode)
Adguard filters: | Russian filter, English filter, Spyware filter, Social media filter, Mobile Ads filter, Annoyances filter, Anti-Adblock Killer

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1150428

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
