### ISSUE TITLE
unblocked trackers ios

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#4645]
adserver.shadow.snapads.com (https://itunes.apple.com/us/app/snapchat/id447188370?mt=8)

geoip.ifunny.co (https://itunes.apple.com/us/app/ifunny/id429610587?mt=8)

ads-chunks.prod.ihrhls.com (https://itunes.apple.com/us/app/iheartradio-free-music-radio-stations/id290638154?mt=8)

s.jpush.cn (https://itunes.apple.com/us/app/yunmai/id1008122580?mt=8)

unagi-na.amazon.com (https://itunes.apple.com/us/app/amazon-app-shop-scan-compare-and-read-reviews/id297606951?mt=8)

r.my.com (https://itunes.apple.com/us/app/mymail-email-for-hotmail-gmail-and-yahoo-mail/id722120997?mt=8)

**Comment by Alex-302** [comment]
Did you check these apps with blocked domains?

**Comment by jo2dan23** [comment]
Yeah. All work fine with them blocked :)

**Comment by jo2dan23** [comment]
here are more

cdn2.pubexchange.com 	
main.pubexchange.com 	
pixel.app.returnpath.net 	
content.cptrack.de

**Comment by Alex-302** [comment]
I can't just block these domains without information about the source.

**Comment by jo2dan23** [comment]
adserver.shadow.snapads.com (this is from snapchat app)
metrics.g.ebay.com (this is from ebay mobile site)
geoip.ifunny.co (this is from ifunny app)
ads-chunks.prod.ihrhls.com (this is from iheartradio app)

**Comment by jo2dan23** [comment]
@Alex-302 i have added the links to the apps that contain the trackers and removed the other ones that i didn't know the sources for.

**Comment by Alex-302** [comment]
> unagi-na.amazon.com

I don't recommend block it,

Added
||gate.hockeyapp.net/*/track 
||geoip.ifunny.co^
||adserver.shadow.snapads.com^
||ads-chunks.prod.ihrhls.com^
