### ISSUE TITLE
https://geekinformer.net/auth - unable to login with Google account

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4648]
The button does not react: https://geekinformer.net/auth

![image](https://cloud.githubusercontent.com/assets/15856304/24189241/d75fb534-0eec-11e7-8fb3-e566b7361fd8.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS /
Browser: | Chrome
Adguard version: | 1.4
Adguard DNS: | None 
Adguard filters: | 1 2 3 4 10

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1109696

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
