### ISSUE TITLE
Can't reach a router link - it is blocked by Adguard

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4649]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

 http://netis.cc/500  - "Server Error The server encountered an internal error and could not complete your request."

 Can't reach by IP;
- Disabling filters and HTTPS
- WFP driver
- Beta
- Disabling COMODO AV
 doesn't help

- Doesn't work in other browsers (IE, Firefox)

***System configuration***

Information | value
--- | ---
Operating system: | Windows Browser: | 
Adguard version: |  6.1.325.1703
Adguard driver (Windows): | WFP 
Adguard filters: | English, Russian, EasyList Italy, User

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1397071

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not sure that is caused by filters.
Please ask for detailed log(with the time of attempt)

**Comment by vmalyuta** [comment]
1397071
прислал логи

**Comment by Alex-302** [comment]
Я срабатывания правил не вижу.
Влияет ли антитрекинг?

**Comment by Yana-SUP** [comment]
created Win task: 
https://github.com/AdguardTeam/AdguardForWindows/issues/1731

will ask about anti-tracking

**Comment by KozelElena** [comment]
Получили ответ: антитрекинг отключен. Даже при отключенной полной защите не
помогает. Помогает только полный выход из adguard.

**Comment by Alex-302** [comment]
Ок, тогда здесь закрываю.
