### ISSUE TITLE
www.kamikiyuki.com

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#46500]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
Anti-adblock

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/nd2t82Z.png)

</details><br/>

***Steps to reproduce the problem***:

Go to the site with a mobile device.

***System configuration***

**Filters:**

AdGuard Base filter, AdGuard Tracking Protection filter, and AdGuard Japanese filter.

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 10
Browser:                               | Chrome, Firefox
AdGuard version:                       | 3.2.150 (1.4.138cl)
Filters enabled:                       | See above
AdGuard mode (Android only):           | VPN 
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Yuki2718** [comment]
`www.kamikiyuki.com#%#//scriptlet("abort-on-property-read", "setTimeout")`
works on my end, but I'm not familiar with JS.

**Comment by Alex-302** [comment]
Fixed
