### ISSUE TITLE
bezdna.su - Ads

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4650]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

Our customer suggests us add this filter bezdna.su###quotes to the list of filters

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24203755/43ee6aa6-0f1f-11e7-8d0d-bb26151fb621.png)

</details>

***Steps to reproduce the problem***:

http://bezdna.su/#%23%23quotes

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.1.314
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | Off
Adguard filters: | User, English, Russian.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1527361

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
