### ISSUE TITLE
softportal.com - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4651]
http://www.softportal.com/get-34619-msi-afterburner.html

ru en social media spyware annoyances

adg 1.4.1

![screenshot 2017-03-22 18 57 45](https://cloud.githubusercontent.com/assets/23637588/24207277/85e3375e-0f31-11e7-9cbb-f633a8d65aa0.png)

**Comment by Alex-302** [comment]
Fixed
