### ISSUE TITLE
blackfog.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#46525]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 
Cookie Notice

<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/71404884-f015dc80-265d-11ea-96d3-7d7445864a3d.PNG)
</details><br/>
***Steps to reproduce the problem***:

Visit the site: https://www.blackfog.com/

***System configuration***
Windows 10 Pro 1909, Firefox 71, uBlock Origin 1.24.2
**Filters:**
Adguard Base list, Adguad tracking protection, Adguard annoyances, Adguard anti social media

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 1909
Browser:                               | Firefox 71
AdGuard version:                       | 
Filters enabled:                       | Adguard Base list, Adguad tracking protection, Adguard annoyances, Adguard anti social media

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Not enough visitors for filter lists, for user filter:

`blackfog.com##body > .avada-footer-scripts ~ p[style*="background-color"][style*="z-index"]`
