### ISSUE TITLE
sockscap64.com - incorrect blocking

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4652]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Adguard enabled:

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24217962/375a02fc-0f4a-11e7-8093-1c2cc04ad0d9.png)

</details>

* **Expected behaviour**: 

Adguard disabled:

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24218024/727012be-0f4a-11e7-8794-7c18b975779e.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.314
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | Off
Adguard filters: | English, Russian, User

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1186462

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Fixed now
