### ISSUE TITLE
http://www.lipstickalley.com - missed ad on page 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4653]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://www.lipstickalley.com - when you try to open any link on a website, you are redirected to another tab. each time this tab is different
for example http://www.dealsdaily.email/landing/sweepstakes?pubid=905&profileid=8158e1d4e8e4492a91ef1d929abc4678&aff_sub1=1-73-358867fb-5524-45be-9240-86bbe3180bda&cohort=1202861

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/24231317/9989e072-0f8c-11e7-82a3-388be30a261a.png)

</details>

***System configuration***

Application version: 1.1.5.65
Device: iPhone
Platform: iOS
OS: 10.2.1
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.12.34 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.1 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.98 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.10.95 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.1 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.7.47 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.74 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.11 Enabled=YES
ID=101 Name="EasyList" Version=1.0.69.5 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1527714

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Fixed

**Comment by Alex-302** [comment]
Small addition
||dk45agakx3yfl.cloudfront.net^

**Comment by dzamyshlyayeva** [comment]
Missed ad on page:
http://www.lipstickalley.com/showthread.php/1159574-Admin-we-need-transparency/page23?s=c953a051b2730da6e797873fbe44f65a

Popup for ad: 
http://track.happinessandloves.com/2ae44f15-d645-4b34-99a4-abe25e49fcac?companyid=15211&pubid=650669&pixel=1491766904mb29348442832

<details>

![image](https://cloud.githubusercontent.com/assets/23372054/24841132/0be8e7ac-1d85-11e7-93f7-a1c02555be83.png)

![image](https://cloud.githubusercontent.com/assets/23372054/24841135/23e1f27c-1d85-11e7-8592-90d5ab62ddfe.png)

</details>

**System Configuration**
Application version: 1.1.5.65
Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.11.24 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.89 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.74 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.10.66 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.7.28 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.65 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.1 Enabled=YES
ID=101 Name="EasyList" Version=1.0.68.56 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.71 Enabled=YES

**Comment by Alex-302** [comment]
Not reproduced. Try to disable
