### ISSUE TITLE
http://www.eldorado.com.ua - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4654]
http://www.eldorado.com.ua/smartphones/c1038946/city_id=2/

Clicking on these elements doesn't work

![image](https://cloud.githubusercontent.com/assets/15856304/24245150/5c48da40-0fca-11e7-8302-1d93de0e0a35.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chome 
Adguard version: | .1705
Adguard driver (Windows): | WFP
Adguard DNS: |  Default
Stealth mode options(Windows) | off
Adguard filters: | below

![image](https://cloud.githubusercontent.com/assets/15856304/24245207/905d8092-0fca-11e7-98d5-d8e82b1a2ead.png)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||google-analytics.com/plugins/ua/ec.js$domain=eldorado.com.ua
@@||google-analytics.com/analytics.js$domain=eldorado.com.ua
@@||googletagmanager.com/gtm.js$domain=eldorado.com.ua

||tracker.softcube.com^$third-party
||widget.sender.mobi^$third-party
||retarala.ru^$third-party
||dmpcloud.net^$third-party
||rtb.softcube.com^$third-party

```
