### ISSUE TITLE
ru.onlinemschool.com/math/assistance/percent/percent4/ - реклама

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4655]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: ru.onlinemschool.com/math/assistance/percent/percent4/ - сайт с рекламой

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/ennkc9

***Steps to reproduce the problem***: ведите значения в две строки и нажмите вычислить.

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.1.5.65
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.12.48 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.4 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.3 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.11.1 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.48.57 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.56 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.7.52 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.75 Enabled=YES

Ticket ID(if exists): 1518078

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
