### ISSUE TITLE
[NSFW] bravoteens.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#46552]
**Site Sample** | 
----------------|
https://www.bravoteens.com/videos/219364/small-titted-aglaya-screaming-from-having-her-coochie-boinked/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Chrome x64 (lastest)
AdGuard version:                       | **7.3 NIGHTLY** 
Protection Mode:						| **WFP Driver**
Stealth Mode:					       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

<details><summary><b>Screenshot:</b></summary>

![s](https://i.imgur.com/wYNJlEM.jpg)

</details><br/>

@AdamWr @Alex-302

**Comment by FadeMind** [comment]
@Alex-302  you have forgot about this:
![20191226-1577381021-001](https://user-images.githubusercontent.com/9846948/71484477-e54d7a00-280c-11ea-83f8-852f1125723c.png)

**Comment by Alex-302** [comment]
Fixed
