### ISSUE TITLE
[nsfw] upornia.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#46554]
**Site Sample** | 
----------------|
https://upornia.com/videos/1666669/polish-lesbians/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Chrome x64 (lastest)
AdGuard version:                       | **7.3 NIGHTLY** 
Protection Mode:						| **WFP Driver**
Stealth Mode:					       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

<details><summary><b>Screenshot:</b></summary>

![s](https://i.imgur.com/3ECvnqJ.png)

</details><br/>

@AdamWr @Alex-302

**Comment by Alex-302** [comment]
Please check these rules:
```
||onestepproductions.online^$third-party
||upornia.com/gugra/teo*.js
```
Videos are not working.

**Comment by FadeMind** [comment]
@Alex-302 video works well. No ads. 
![20191226-1577365419-001](https://user-images.githubusercontent.com/9846948/71477126-955cbc00-27e8-11ea-9f79-3ff9cbcf30e2.png)
![20191226-1577365494-001](https://user-images.githubusercontent.com/9846948/71477153-b9b89880-27e8-11ea-8000-3f51f01e3583.png)
