### ISSUE TITLE
Anti AdBlocker at https://www.native-english.ru/

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4656]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Anti AdBlocker at https://www.native-english.ru/
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-03-24 at 2 10 07 am](https://cloud.githubusercontent.com/assets/26434103/24275353/79800210-1037-11e7-8ed0-51f3978c8c64.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | User, English, Spyware, Social, Annoyances, Russian, Norsk

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1049047

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
