### ISSUE TITLE
StayOnline.Pro

### ISSUE THREAD

**Issue by Oizaro** [AdguardTeam/AdguardFilters#46560]
Anti-adblock warning

<img src="https://i.ibb.co/j6kbR5Q/Screenshot-20191224-234502-Samsung-Internet-Beta.jpg">

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | Android 10
Browser:                               | Samsung Internet 10.2.01.6
AdGuard version:                       | 3.3.220 RC
Filters enabled:                       | Everything except obsolete, privacy and social networks
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | Google
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Please post full url on which it happens. Also you have activated way too many filters.

**Comment by Oizaro** [comment]
@BlazDT Yes, sorry... stayonline is a service that checking if file is still available, this is an example found on Google (which trigger the anti-adblock warning):

https://stayonline.pro/l/wLZnY/

**Comment by PentagramTr** [comment]
@Oizaro 
`@@||stayonline.pro/js/ads.js?v=0.0.1`

**Comment by Oizaro** [comment]
@PentagramTr Good, works. Thanks.

**Comment by Oizaro** [comment]
oops, I closed the comments by mistake. 😭

**Comment by krystian3w** [comment]
@mapx- add `@@||stayonline.pro/js/ads.js`?

**Comment by BlazDT** [comment]
Thanks, fixed.
