### ISSUE TITLE
http://womanadvice.ru/ ads on Android

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardFilters#4657]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
Site has unblocked ads right after the article. Android has images and headlines, Chrome on Mac only has titles.
http://womanadvice.ru/elektronnaya-ramka-dlya-fotografiy

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![adddd](https://cloud.githubusercontent.com/assets/26342177/24275629/81cb5698-1039-11e7-97cf-3378af89ca3a.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): | Whitelist
Adguard filters: | [ 2, 3, 4, 14, 1, 11, 211 ]

Ticket ID(if exists): 1150428

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
