### ISSUE TITLE
Yandex.Direct at Yandex Disk

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4658]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Яндекс.Директ при веб доступе на Яндекс Диск. К сожалению нет возможности повторить.
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24277179/2233d4de-1044-11e7-8419-260dbdb373cf.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | FireFox
Adguard version: | 6.1.324.1701
Adguard driver (Windows): | WFP
Adguard DNS: | None
Adguard filters: | Russian, English, Spyware, Social Media, Annoyances, User

Stealth mode options(Windows)
<details>

![screen shot 2017-03-24 at 3 51 11 am](https://cloud.githubusercontent.com/assets/26434103/24277341/2b76be34-1045-11e7-8749-c5a6bda6b73f.png)

</details>

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 397797

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by MaximvsStorm** [comment]
Здравствуйте! Это мой скриншот. Я смог повторить поведение браузера. Поскольку скриншот с рабочего компа, я подумал - может виноват прокси? Попробовал с включенным и выключенным прокси - реклама отображается в обоих случаях. Добился фильтрации при включении ВПН до Финляндии посредством ОпенВПН,  Но вот тут уж не знаю чья заслуга в фильтрации, их или Ваша. Пока ничего не понятно.

**Comment by Alex-302** [comment]
@MaximvsStorm нужна прямая ссылка. Подозреваю, что не всегда они показывают рекламу.

**Comment by MaximvsStorm** [comment]
https://yadi.sk/d/y86pYFWT3GG8Mv

![default](https://cloud.githubusercontent.com/assets/26643341/24292810/eb36578e-109f-11e7-9839-b482f58fca0a.JPG)

**Comment by Alex-302** [comment]
Странно. Повторить не удалось.
В пользовательском фильтре есть правила?

**Comment by MaximvsStorm** [comment]
Правила есть. Но не относящиеся к странице в ссылке.

**Comment by Alex-302** [comment]
Удалять не обязательно, можно просто отключить для проверки.
Если что, могу глянуть удалённо через TeamViewer.

**Comment by MaximvsStorm** [comment]
Тимвьюером не пользуюсь - нельзя, комп рабочий. Ладно, давайте закроем эту проблему - реально не критично. А у Вас время отнимаю.

**Comment by Alex-302** [comment]
Ну ок. Если что - пишите.

**Comment by MaximvsStorm** [comment]
Хорошо, спасибо!
