### ISSUE TITLE
Incorrect blocking at http://m.neogaf.com/, iOS PRO

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4659]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Incorrect blocking, was able to reproduce at our end.

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24277606/d169d9d8-1046-11e7-84e1-b81fc5177e30.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24277615/e3a6136e-1046-11e7-980c-92772beb9e3f.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)
Open http://m.neogaf.com/forumdisplay.php?f=2 in iOS

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.40
Simplified filters(iOS) | Off
Adguard filters: | User, English, Spyware, Social media, Safari, Wiltteri

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1528458

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
What is blocked incorrectly? As I see, user make screenshots of the different parts of the page.
Removed leftover at the top.

**Comment by OlegSUP** [comment]
I'm having same trouble on my Android device (Chrome, Adguard 2.8, HTTPS On, Filters: English, Spyware, Annoyances, Russian, German, Mobile Ads; Local VPN, High-speed). When opening http://m.neogaf.com/forumdisplay.php?f=2 in Incognito tab with Adguard enabled I get this page:
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24292833/9f647c26-1097-11e7-9c27-2f6c152f6096.png)

</details>

When I'm trying to open any article it says::
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24292918/fc287606-1097-11e7-8cd0-9cd176c663d6.png)

</details>

Without Adguard:
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24293148/0e0aecd6-1099-11e7-9ca6-bf9a1959a653.png)


![image](https://cloud.githubusercontent.com/assets/26434103/24293030/79991474-1098-11e7-8904-c9a326a40a90.png)


</details>

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||report-ads-to.pubnation.com/dist/pnr.js?t=$domain=m.neogaf.com
```
