### ISSUE TITLE
Missed ad at http://www.bild.de/

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4660]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Missed ad at http://www.bild.de/politik/inland/talkshow/illner-talk-tuerkei-50985814.bild.html
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24279713/3afa6810-1054-11e7-8ade-970306bd3966.png)

![image](https://cloud.githubusercontent.com/assets/26434103/24279725/4942f39c-1054-11e7-8b33-d8efb399ea53.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS iPad
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | Off
Adguard filters: | User, English, Spyware, Social Media, Annoyances, German, Mobile Ads, Safari

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1528855

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. Check user filter and whitelist.
