### ISSUE TITLE
adz.bz antiadblock

### ISSUE THREAD

**Issue by ghajini** [AdguardTeam/AdguardFilters#4661]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: antiadblock
* **Current behaviour**: 
unable to bypass that antiadblock 

[//]: # antiadblock at `http://adz.bz/6CZi`

Screenshot:

![screenshot 194](https://cloud.githubusercontent.com/assets/20338483/24281717/cb78f538-1080-11e7-962e-1eb53a6a345d.png)

* **Expected behaviour**: 

[//]: # it should pass beyond avoiding their antiadblock

***Steps to reproduce the problem***:

[//]: # go to `http://adz.bz/6CZi`
click on captcha request,you will get adblock detected message

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: |  chrome 57 updated
Adguard version: | 2.5.11

Adguard filters: | english filter 1.1.12.62
| spyware filter 1.0.11.7

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed

**Comment by ghajini** [comment]
@Alex-302 
Another same site of mellowads
`http://zap.in/5WHU`

**Comment by Alex-302** [comment]
fixed.

**Comment by Alex-302** [comment]
Next time, please, create new issue.
