### ISSUE TITLE
http://tass.ru - incorrect blocking 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4662]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:http://tass.ru/proisshestviya/4121469 - incorrect blocking 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/24285476/d9a65f7c-1078-11e7-941b-445f5bf009fe.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.1.5.40

Device: iPhone
Platform: iOS
OS: 10.2.1
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.12.62 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.7 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.94 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.11.7 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.48.62 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.76 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.14 Enabled=YES
ID=101 Name="EasyList" Version=1.0.69.11 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.76.83 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.74.77 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.75.55 Enabled=NO
ID=208 Name="Malware Domains" Version=1.0.75.43 Enabled=NO
ID=213 Name="RU AdList: BitBlock" Version=1.0.73.74 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1528902

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не повторяется.
Пусть попробует выключить
ID=15 Name="Simplified domain names filter" Version=1.0.1.14 Enabled=YES
ID=101 Name="EasyList" Version=1.0.69.11 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.76.83 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.74.77 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.75.55 Enabled=NO
ID=208 Name="Malware Domains" Version=1.0.75.43 Enabled=NO
ID=213 Name="RU AdList: BitBlock" Version=1.0.73.74 Enabled=YES

**Comment by dzamyshlyayeva** [comment]
написали. ждем ответа.
