### ISSUE TITLE
[NSFW] pinflix.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#46623]
**Site Sample** | 
----------------|
https://www.pinflix.com/videos/208206/melissandra-cuckolds-douchebag-bf

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Chrome x64 (lastest)
AdGuard version:                       | **7.3 NIGHTLY** 
Protection Mode:						| **WFP Driver**
Stealth Mode:					       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

Ad leftover, player overlays

<details><summary><b>Screenshot:</b></summary>

![20191226-1577385946-001](https://user-images.githubusercontent.com/9846948/71486834-9574b000-2818-11ea-8fea-94cc87a5503e.png)
![20191226-1577385994-001](https://user-images.githubusercontent.com/9846948/71486835-960d4680-2818-11ea-96da-6366716566c9.png)

</details><br/>

@AdamWr @Alex-302

**Comment by Nzzyme** [comment]
https://www.pinflix.com/videos/57655/foxy-sheena-shaw-displays-her-big-ass-before-dp?ch=10079585

Please remove the ad text strings from the page

https://i.imgur.com/E8S7fwh.png

**Comment by AdamWr** [comment]
>Please remove the ad text strings from the page

It seems that it has been fixed today - https://github.com/AdguardTeam/AdguardFilters/commit/8b21754f4248947284b589a8252c10fe226dfca6
