### ISSUE TITLE
missed video ads https://vk.com

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4663]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: missed video ads https://vk.com

Links to videos with ads
https://vk.com/video27075981_170975676
https://vk.com/video-45280055_456239738

Firefox 52.0.1 (64-бит) – ads are in the video and in the bottom.
IE (11.0.9600.18618 UPD:11.0.40) - no ads
Google Chrome 56.0.2987.110 (64-бит) – ads are in the video and in the bottom

HAR-file https://1drv.ms/u/s!AmlwjFU4OrlmmcBOIH1XEW6XTYNa7Q
Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/24291964/de3576f2-1093-11e7-9d3d-9b955280013c.png)
![image](https://cloud.githubusercontent.com/assets/25711093/24291968/e250ef14-1093-11e7-8721-f05eb2283f3d.png)
is not reproduced on Mac

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | 6.1.326.1705
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | on
Adguard filters: | 1, 2, 3, 4, 116, 214, 14

Ticket ID(if exists): 1527600

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Вроде поправил. Через час можно будет обновляться.
