### ISSUE TITLE
[Antiadblock] allaboutphones.nl

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#4664]
On the website www.allaboutphones.nl there is a pink message about using an Adblocker.

![schermopname 99](https://cloud.githubusercontent.com/assets/19804873/24296248/9b5a3f06-109e-11e7-9dcd-1911d194412c.png)
![schermopname 100](https://cloud.githubusercontent.com/assets/19804873/24296260/b19673e8-109e-11e7-9272-818596dacb59.png)

Filters:
English, Spyware, Annoyances, Nederlands, Useful ads, Malware Domains

https://www.allaboutphones.nl/

http://www.awesomescreenshot.com/image/2325610/47c03b3417bd2d20e5088df182b4b4b5

 http://www.awesomescreenshot.com/image/2324207/f3c3a98add8e9da4adf4e4d15bf434c7

See the issue:
https://github.com/AdguardTeam/AdguardAssistant/issues/2

**Comment by seanl-adg** [comment]
Added to Dutch filter:
```
||iframe.gsminfo.nl/*/populair-beknopt^$domain=allaboutphones.nl
allaboutphones.nl##.ad-container
```

**Comment by gvanosch12** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/4664

On March 24 (seanl-adg)  has added the above script to the Dutch filter on the website:
allaboutphones.nl  with a similar adblock warning popup message wich has resolved the issue and has removed the Pink Adblock Warning Screen on the dutch website allaboutphones.nl

**Comment by gvanosch12** [comment]
Hi Seanl,

Can you please help about this issue; Alex is unable to perform the action to add this site to the Dutch(Netherlands filter) and asked me to show the html code from devtools,but i do not know how to perform the action,i;m not a professional,i just asked for help,not to participate.

Thanks in advance

Geert

**Comment by Alex-302** [comment]
@gvanosch12 why don't you ask me?:)
