### ISSUE TITLE
https://www.inside-handy.de  antiadblock

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4665]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

When you follow this link https://www.inside-handy.de/magazin/41970-moto-mods-daten-fakten-features-uebersicht Site becomes unusable with AdGuard enabled. Could reproduce.

Screenshot:
https://imgur.com/a/7p7we

***System configuration***

Information | value
--- | ---
Operating system: |Android 7
Adguard version: | 2.9.37
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 

Adguard filters: |  2, 3, 4, 14, 6, 11

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(1317328): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Fixed
