### ISSUE TITLE
pinflix.lsl.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#46652]
**Site Sample** | 
----------------|
https://www.pinflix.lsl.com/en/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Chrome x64 (lastest)
AdGuard version:                       | **7.3 NIGHTLY** 
Protection Mode:						| **WFP Driver**
Stealth Mode:					       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

Cookie, redirects to `syndication.exosrv.com^$document` blocked by Adguard. 
Redirects can be from `https://www.pinflix.lsl.com/en/` OR `https://www.pinflix.com/live-sex` sub page. I don't have idea. 

<details><summary><b>Screenshot:</b></summary>

![20191227-1577458284-001](https://user-images.githubusercontent.com/9846948/71521422-07083900-28c1-11ea-9183-72ce685e61e8.png)

</details><br/>

@AdamWr @Alex-302

**Comment by Alex-302** [comment]
Reproduced cookie mesage only.
