### ISSUE TITLE
postlnk.com

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdguardFilters#46674]
Can you please check this sites?

On many sites i get redirected to ads, they open new tabs, i find this urls:

wlbetathome.adsrv.eacdn.com
postlnk.com
https://mobile.bet365.com/olp/open-account?affiliate=365_893216

While browsing an new tab opens, with "postlnk.com" for few seconds than it redirects to "bet365" adress.

AdGuardHome 
SDNS Filter

**Comment by Alex-302** [comment]
Hi. This is a destination point of redirects. We need to know the site, which starts redirect.

**Comment by uservictor** [comment]
Have send it to you via email

**Comment by Alex-302** [comment]
@uservictor which email?

**Comment by uservictor** [comment]
The sites are:
s.to 
hdfilme.cc
There are a lot of redirection advertisements.
Thanks

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/72249948-2b734d80-3603-11ea-8a11-dd964c653035.png)
No popups at hdfilme.cc
