### ISSUE TITLE
Pink Adblock Warning Removal Screen on website: www.allaboutphones.nl 

### ISSUE THREAD

**Issue by gvanosch12** [AdguardTeam/AdguardFilters#4667]
Hello Everyone,

I see on the website www.allaboutphones.nl a pink message about that i,m using an Adblocker,please whitelist us,i have already installed the annoyance filterrule and the rule adblock warning removallist,and the anti-adblock killer reek,but none of these rules are taking effect.

Can you please add the site www.allaboutphones.nl to the Annoyance filter rule,that will remove this pink adblock  message screen on this site(see screenshot)

I have no extra filterrules at the Userfilter on the Adguard Application.
I,m using the latest version of Adguard: 6.1.314.628 with the latest build update from Windows 10 x64 bits version,and i,m using the latest version of the Chrome Browser=Version:57.0.2987.110 (64-bits)

I have just expeirenced that the Pink Adblock Warning message on the site: www.allaboutphones.nl  suddenly not apear annymore on the Edge browser,but on the Chrome browser the pink Adblock warning message screen on this site: www.allaboutphones.nl  are still apearing(see screenshot)
I have before updated the filter rules.

Can you please add the site www.allaboutphones.nl  on the Chrome browser to the Annoyance Filter rule

https://www.allaboutphones.nl/

![schermopname 101](https://cloud.githubusercontent.com/assets/19804873/24304518/ea34ed18-10b9-11e7-97df-a9183074bde6.png)

![schermopname 102](https://cloud.githubusercontent.com/assets/19804873/24305030/d1f8a7ba-10bb-11e7-8311-b5bc344a8818.png)

I,m located at The Netherlands(Dutch,Nederlands)

Kindly regards,

Geert Van Osch

**Comment by gvanosch12** [comment]
Hi,

I have solved the Pink Adblock Warning message on the site www.allaboutphones.nl,on the Chrome Browser,i had updated the Adguard  taskbar application filter database,but i had forgotten to include the Adguard extention on the Chrome Browser to check also on filter database updates,after the update the Pink Adblock warning message on this website has been gone 

Thanks very much

Kindly regards,

Geert Van Osch

**Comment by Alex-302** [comment]
> i had forgotten to include the Adguard extention

When Adguard for Windows/MacOS working, the extension works in integration mode, and filtering nothing.
