### ISSUE TITLE
www.maltaweb.biz

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#46677]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: coin miner; the title is just an example. See below.
* **Current behaviour**:
AdGuard Base filter includes these:
`||wilf.cn/wp-content/plugins/simple-monero-miner-coin-hive^`
`||gaypornwave.com/wp-content/plugins/simple-monero-miner-coin-hive^`
However, according to themesinfo.com, the simple-monero-miner-coin-hive plugin is used by 216 websites and the title site is one of them that I confirmed actually use the plugin (some links were dead or no more using it): https://themesinfo.com/wordpress-plugins/free-wordpress-simple-monero-miner-coin-hive-plugin-dez

I suggest to generalize the filter to e.g.
`/wp-content/plugins/simple-monero-miner-coin-hive/*`
for better coverage.
You can also generalize
`||gaypornwave.com/wp-content/plugins/simple-miner-tweaks^`
which is used by 19 websites: https://themesinfo.com/wordpress-plugins/wordpress-simple-miner-tweaks-plugin-dvua 

Also consider to add e.g. 
`/wp-content/plugins/wp-monero-miner`
 as it covers wp-monero-miner-using-coin-hive plugin used by 174 websites and wp-monero-miner used by 99.
https://themesinfo.com/wordpress-plugins/free-wordpress-wp-monero-miner-using-coin-hive-plugin-fcp
https://themesinfo.com/wordpress-plugins/wordpress-wp-monero-miner-plugin-dk4c
An example site for wp-monero-miner is http://ganbridge.com/

***Steps to reproduce the problem***:

Go to the example sites and the mining plugin will be loaded. I couldn't confirm if it actually mines because my anti-virus came into play, but not sure if this matters.

**Filters:**

[//]: # AdGuard Base filter

**Comment by Alex-302** [comment]
Done.
