### ISSUE TITLE
WebRTC circumvention - yad2.co.il

### ISSUE THREAD

**Issue by DanIbba** [AdguardTeam/AdguardFilters#4668]
### URL(s) where the issue occurs

http://www.yad2.co.il/
http://www.yad2.co.il/Nadlan/sales.php

### Describe the issue

**WebRTC circumvention**
Full of webRTC HTML5 crap ads. It seems like they find a way to bypass the WebRTC blocking ads.   

### Screenshot(s)

<img width="1280" alt="screen shot 2017-03-24 at 23 40 08" src="https://cloud.githubusercontent.com/assets/24211092/24312865/9584ec96-10eb-11e7-866b-099a988e1355.png">

### Versions

- Browser/version: Chrome
- uBlock Origin version: 1.11.4

### Settings

default settings + ISR: EasyList Hebrew

### Notes

I think this is made by a company called Uponit. please see my webRTC investigation below:
<img width="1280" alt="screen shot 2017-03-24 at 23 12 41" src="https://cloud.githubusercontent.com/assets/24211092/24311963/81f0df5e-10e7-11e7-91c9-7436099ad48f.png">

**Comment by ghajini** [comment]
Hey bro don't post ublock things here😹
Related to adguard only

**Comment by Alex-302** [comment]
Try this rule
```
yad2.co.il#%#Object.defineProperty( window, 'Blob', { get: function(){ return 0; } });
```

**Comment by seanl-adg** [comment]
They are using Uponit ad reinjection solution. We have an open issue tracker about it - https://github.com/AdguardTeam/AdguardFilters/issues/4186
Those ads won't load at all if you use Adguard for Windows. We are blocking connection to their ad server by their IP address, with `$network` modifier. `$network` modifier blocks any connection to certain remote ip:port pair, regardless of connection type they use, HTTP, WebSocket, or WebRTC.

**Comment by seanl-adg** [comment]
Should be fixed now.
