### ISSUE TITLE
forumua.org - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4669]
Screenshots:

https://drive.google.com/file/d/0B3XSumQQZH7PLVItdHBrcV9Zb28/view?usp=drivesdk
https://drive.google.com/file/d/0B3XSumQQZH7PUTJTdmZhb2o3blE/view?usp=drivesdk

***Steps to reproduce the problem***:

Go to:
http://forumua.org/?_=1477838032640&_=1490372483281

***System configuration***

Information | value
--- | ---
Operating system: |Android 
Browser: | Chrome
Adguard version: | 2.9.1
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard filters: | 1,2,3,4,5,11,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1529147

**Comment by Alex-302** [comment]
Fixed
