### ISSUE TITLE
no wifi in moscow metro 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4670]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: no authorization in Moscow underground's wi-fi network, while using your ad blocker

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android / iOS
Adguard version: | 1.1.5.65/ 2.8.76
Filtering quality (Android): | High-quality / high-speed 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1214655
1529154
1134513
1529108 - iOS

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by OlegSUP** [comment]
Same trouble on our side. From user:
"Здравствуйте,
Проблема в том, что реклама блокируется, но из-за неё невозможно авторизоваться на сайте. То есть заместо рекламы и прочего происходит подобная анимация и все. 
Пошаговая инструкция моей проблемы:
1. Включаем блокировку рекламы в AdGuard Pro
2. Подключаемая к wifi в метро
3. Нажимаем "Перейти в интернет"
4. После нескольких секунд появляется данное изображение в виде анимации".

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24324691/b0bcb270-1193-11e7-8f82-e49ae5f918fc.png)

</details>

Ticket ID:1529622

**Comment by Alex-302** [comment]
@OlegSUP спроси, помогает ли отключение мобильного фильтра. Если нет - то надо по одному с проверкой выключать. Сам проверить не могу.

**Comment by OlegSUP** [comment]
@Alex-302 Хорошо, отправил запрос

**Comment by Alex-302** [comment]
@OlegSUP попроси ещё адрес самой первой страницы, когда кнопки ещё не нажимались

**Comment by Alex-302** [comment]
> Хорошо, отправил запрос

а что ж ты вторую часть просьбы не передал? Так снова тратить время придётся.

**Comment by Alex-302** [comment]
У пользователей Дроида попроси лог HTTP запросов с указанием времени, когда открыли страницу авторизации

**Comment by Alex-302** [comment]
Ещё вот эти правила проверить надо, после отправки логов
```
@@||ads.adfox.ru/*/prepareCode$domain=auth.wi-fi.ru
@@||ads.adfox.ru/*/getid?pr=*&t=json$domain=auth.wi-fi.ru
```

**Comment by evgeniy-ADG** [comment]
хар тут 1214655
правила - отправлю.

**Comment by OlegSUP** [comment]
Отправил уточнение. Ответа по первому запросу всё ещё нет.

**Comment by Alex-302** [comment]
> хар тут 1214655

судя по HAR, интернет у него заработал, т.к. вижу автоматический переход на страницу с новостями на wi-fi.ru

**Comment by Yana-SUP** [comment]
передала

**Comment by OlegSUP** [comment]
Ticket ID: 1529622
User:
Сегодня пытался поочередно отключат фильтры, дабы понять какой мешает авторизации, в итоге, какой бы фильтр я не включал или не выключал, проблема оставалась нерешённой. Проблема так же остаётся, если перейти и на другую страницу 

Ответа по правилам нет.

**Comment by Alex-302** [comment]
Нет однозначного ответа - без фильтров работает?
У него вроде версия Pro. Если без фильтров не пускает, путь вкл/выкл режим полёта(это очистит кэш DNS), потом включит журнал заблокированных запросов в приложении и повторит попытку(можно несколько раз для надёжности). Затем нужно снять скриншоты журнала, на которых есть заблокированные домены.

**Comment by vmalyuta** [comment]
Ticket ID: 1529622
Юзер пробовал отключить все фильтры, в таком случае интернет работает, но фильтрация рекламы отсутствует

**Comment by Alex-302** [comment]
Нужной информации он не предоставил.
Может старинные правила помогут. На проверку:
```
@@||cdn.vmet.ro/websso/css/mac_login.css
@@||cdn.vmet.ro/websso/css/auth_success.css
@@||cdn.vmet.ro/websso/js/mac_login.js
@@||cdn.vmet.ro/brandings/_common/metro-auth.js
@@||vmet.ro/?OPERATOR_MNP=$popup
@@||cdn.vmet.ro/websso/js/auth_success.js
@@||cdn.vmet.ro/brandings/_common/pages.js
```

**Comment by Yana-SUP** [comment]
отправили на проверку

**Comment by vmalyuta** [comment]
1144547
После добавления правил у юзера ошибка устранилась, но после нажатия кнопки "Войти в интернет" его перебрасывает на страницу с рекламным роликом. Вместо самого ролика отображается черный экран и когда этот ролик закончится.

**Comment by Alex-302** [comment]
> Вместо самого ролика отображается черный экран и когда этот ролик закончится.

т.е. ничего не работает. Так?

**Comment by Alex-302** [comment]
Кстати на iOS вряд ли получится сделать авторизацию быстрой без стороннего софта, т.к. ещё год назад(и позже) они авторизацию изменили, и простая блокировка мало что даст.

**Comment by Alex-302** [comment]
@vmalyuta 
ну что?

**Comment by vmalyuta** [comment]
"Да, по окончании ожидания все начинает работать."
видео не идет, отображается только черный экран на время видео
после этого начинает работать

**Comment by Alex-302** [comment]
А уточни ещё - точно ли с правилами есть улучшение?
Возможно ли пропустить рекламу без Адгарда и с Адгардом?

**Comment by vmalyuta** [comment]
Юзер написал "Правило лишь скрывают рекламу, но пропустить ее невозможно. 
Если отключить Adguard, то рекламу также пропустить невозможно. Правда иногда можно перейти на сайт рекламодателя".

**Comment by Alex-302** [comment]
По iOS - рекламный ролик там не заблокировать, т.к. они проверяют пропуск видео, и дальнейшая авторизация не происходит.

**Comment by vmalyuta** [comment]
Юзер ответил "Фильтры обновил. Попробовал подключиться к wi-fi в метро, но ничего не вышло.
Сами рекламные ролики блокируются (появляется черный экран), но дальше ничего не произошло.
Пришлось отключить блокировку на данном сайте."

**Comment by Alex-302** [comment]
Странно. А какие фильтры включены?
Передай на проверку:
```
@@||wi-fi.ru/ad_video/
@@||login.wi-fi.ru^
@@||static0.wi-fi.ru/static/000/ios/index.html
```

**Comment by Yana-SUP** [comment]
**включены:**
Английский
Фильтр счетчиков
Фильтр виджетов соц сетей
Русский
Экспериментальный
Фильтр моб рекламы
Фильтр для Сафари

завтра проверит правила

**Comment by Alex-302** [comment]
@Yana-SUP у него включен Adguard DNS?

**Comment by Yana-SUP** [comment]
отключен http://prntscr.com/etc3x8

**Comment by Michael23456** [comment]
CustomerID:1531233
Пожалуйста, попробуйте прописать следующие правила в Пользовательском фильтре и проверьте, решит ли это проблему:

@@||cdn.vmet.ro/websso/css/mac_login.css
@@||cdn.vmet.ro/websso/css/auth_success.css
@@||cdn.vmet.ro/websso/js/mac_login.js
@@||cdn.vmet.ro/brandings/_common/metro-auth.js
@@||vmet.ro/?OPERATOR_MNP=$popup
@@||cdn.vmet.ro/websso/js/auth_success.js
@@||cdn.vmet.ro/brandings/_common/pages.js
 and 
@@||ads.adfox.ru/*/prepareCode$domain=auth.wi-fi.ru
@@||ads.adfox.ru/*/getid?pr=*&t=json$domain=auth.wi-fi.ru

Response:
Добрый день. При добавлении правил ничего не произошло. Видно что должна быть реклама, слева в верхнем углу появится динамик отключения звука, а снизу полоса времени рекламы, но она не идёт. 
Фильтры обновлял, может нужно какие то конкретно фильтры выбирать?

**Comment by Michael23456** [comment]
CustomerID: 1144547
@@||wi-fi.ru/ad_video/
@@||login.wi-fi.ru^
@@||static0.wi-fi.ru/static/000/ios/index.html
Response:
Попробовал пройти авторизацию в метро, пройти ее удалось, но только после стандартного просмотра рекламного ролика. Он не заблокировался.

**Comment by Alex-302** [comment]
@Michael23456 Для iOS это норма. К сожалению средствами, которые предоставляет эта ОС, данную рекламу не заблокировать, т.к. они проверяют, было ли загружено видео.

**Comment by OlegSUP** [comment]
CustomerID:1531233
Response:
Добрый вечер, теперь реклама вообще не блокируется, даже после добавления правил

<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24822553/a2ba207a-1bfe-11e7-8e60-5ff06ba6c550.png)

![image](https://cloud.githubusercontent.com/assets/26434103/24822563/abb3953a-1bfe-11e7-9c4f-31f4d41f10a3.png)

</details>

Пользователей iOS в таком случае больше не просить о информации или проверять правила?

**Comment by Alex-302** [comment]
> Пользователей iOS в таком случае больше не просить о информации или проверять правила?

нет, не нужно. iOS позволяет использовать только базовый функционал(скрыть элемент и заблокировать адрес), в отличие от Android, и для блокировки этой рекламы его не хватает. Это не вина Адгарда.
