### ISSUE TITLE
missed ads https://ekurilka.ua/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4671]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:missed ads https://ekurilka.ua/

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/24324138/83dc33f2-1189-11e7-9ce6-3de82b162ae8.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS / Android 
Browser: | Google chrome
Adguard version: | 1.4.1 / 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | English, Russian, annoyance, spyware, social, experimental

Ticket ID(if exists): 1529147

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
