### ISSUE TITLE
missed ad http://mobiltelefon.ru/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4672]
***Description***: missed ad http://mobiltelefon.ru/

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/24324307/afb9caae-118c-11e7-9a6e-b352e97be804.png)
***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | English, Russian, annoyance, social, spyware, experimental, mobile

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 394317

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by OlegSUP** [comment]
Same trouble on my Android device (Chrome, Adguard 2.8, HTTPS On, Filters: English, Spyware, Annoyances, Russian, German, Mobile Ads; Local VPN, High-speed/Full).

<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24325813/f2d9e996-11a9-11e7-9af2-045220f3df43.png)

</details>

**Comment by Alex-302** [comment]
Fixed
