### ISSUE TITLE
jadopado.com/en-sa - Incorrect Assistant Inject

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4673]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Incorrect Assistant Injection while displaying jadopado.com 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24324875/e793dd70-1196-11e7-9a35-5962fe8b0af5.png)

</details>

* **Expected behaviour**: 

Here is a screenshot of how it should be:

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24324881/0eea27a8-1197-11e7-802e-60ce1c3046ac.png)![image](http://somehosting.com/adg_off.jpg)

</details>

***Steps to reproduce the problem***:

https://jadopado.com/en-sa/

I recommend checking the page code while Adguard is enabled.

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.1.314/ 1.4.1
Adguard driver (Windows): | WFP
Adguard DNS: | None / Default / Family Protection
Adguard filters: |User, English, Social media, Spyware, Liste AR/ User, English, Spyware, Social media 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1529587

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is not related to filters. Please write to Windows repo.
New assistant is coming, maybe it will be fixed.

**Comment by Bohdan-SUP** [comment]
https://github.com/AdguardTeam/AdguardForWindows/issues/1641
