### ISSUE TITLE
allcables.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#46730]
**1**. При вхождении в учётную запись не происходит перенаправление на страницу, с которой был произведён вход. Виной тому зажатый Referrer, посему, хотелось бы `@@||auth.xtrend.ru^$referrer`, но приходится `@@||auth.xtrend.ru^$stealth` (AllCables.ru является частью Группы компаний Xtrend).

___________________________________________________

 **2**. Реклама.

<details><summary>Screenshot:</summary>

![2019 12 28-2](https://user-images.githubusercontent.com/17948007/71550168-019f1180-29db-11ea-90d1-ecd52db4b4b5.png)
</details>

`allcables.ru##.wrapper:has(> .gallery-holder)`

___________________________________________________

 **3**. СамоРеклама.

<details><summary>Screenshot:</summary>

![2019 12 28-3](https://user-images.githubusercontent.com/17948007/71550173-24c9c100-29db-11ea-8162-b7004627da22.png)
</details>

[https://www.allcables.ru/product/kabel-audio-1xmini-jack-2xrca-mrcable-ayjmr-03-hs-3-0m-132829/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.allcables.ru/product/kabel-audio-1xmini-jack-2xrca-mrcable-ayjmr-03-hs-3-0m-132829/)

`allcables.ru##w-div`

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.3.4
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
> хотелось бы `@@||auth.xtrend.ru^$referrer`

будет скоро.
