### ISSUE TITLE
golih.net - ads leftover

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4674]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Pop-up ads leftover. ( Customer has this issue using iOS)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24328752/226b4ce4-11fb-11e7-84f3-703e2724e943.png)

</details>

***Steps to reproduce the problem***:

http://golih.net/golie_devushki/38273-Ronda-Rouzi-20-foto.html

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.314
Adguard driver (Windows): | WFP 
Simplified filters(iOS) | Off
Stealth mode options(Windows) | Off
Adguard filters: | English, Russian, User, Spyware, Social, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1454510

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
