### ISSUE TITLE
OGYoutube 2.1 ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4675]
People report that AG does not block ads in it.

I'll report more info later on.

**Comment by worstperson** [comment]
Would think users would need to install OGYoutube v2.0 that's based on 10.45.53 for Adguard to work, but they could alternatively install an unofficial modded version that includes the AdAway patches(search for "OGYouTube AdAway"). v2.2 has just been released so it my be a bit before a patched version start circulating.

**Comment by ameshkov** [comment]
Ok, new version of OGYoutube targets Android Nougat, so HTTPS cannot be filtered inside of it.
