### ISSUE TITLE
missed ads in the app Themes for Plus Messenger https://play.google.com/store/apps/details?id=es.rafalense.themes

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4676]
***Description***:
missed ads in the app Themes for Plus Messenger https://play.google.com/store/apps/details?id=es.rafalense.themes
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/24334462/45915e8e-1273-11e7-990a-5ad8fe47ed34.png)
![image](https://cloud.githubusercontent.com/assets/25711093/24334463/48cb965a-1273-11e7-9aff-2098a515bfd7.png)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On
Adguard filters: | English, Russian, Spyware, Social media, Annoyances, Mobile ads

Ticket ID(if exists): 1138191

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
> HTTPS filtering (Android):	On

which mode? Ads are blocked on my device.
