### ISSUE TITLE
missed ads http://internetgazeta.cardvrmirrorr.ru/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4677]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: missed ads http://internetgazeta.cardvrmirrorr.ru/

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/24334625/1ea7ef10-1276-11e7-8140-b29d75919945.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | english, russian, annoyance, mobile, social, spyware, experimental

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1530287

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Ну видно же, что сайт липовый)
Узнай, откуда юзер туда перешёл(если помнит, конечно).
