### ISSUE TITLE
MogazNews.com - Blocked images (AdGuard Social Media filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#46783]
### Affected site:
`https://www.mogaznews.com/`

### Issue:
Article images are blocked.

### Example:
`https://en.mogaznews.com/Fashion/1325516`

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* AdGuard Social Media filter

### Problem rule:
`##.img-share`

### Possible fix:
`mogaznews.com#@#.img-share`

### Other problem filters:
Fanboy's Annoyance List / Fanboy's Social Blocking List https://github.com/ryanbr/fanboy-adblock/issues/1281/

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.8.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.12 (XUL)

**Comment by AdamWr** [comment]
Added, thank you.
