### ISSUE TITLE
https://reg.kontur-ca.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4680]
> занимаюсь предоставлением возможности приобрести ЭЦП для отчетности, торгов и т.п. Для этого мне необходимо создавать заявки по указанной ссылке. Когда проходишь по ней, должно всплывать окно в выбором моего сертификата, но у меня выходит ошибка (http://prntscr.com/enx4i7). Сайт добавлен в белый список, https:// не сканируется,но работать не могу. Приходится полностью отключать AdGuard, что совсем не нравится.

![image](https://cloud.githubusercontent.com/assets/15856304/24342467/be6b29c4-12c9-11e7-8ee4-8a41760b186a.png)

> Вход только через internet explorer и при наличии ЭЦП. Вход не осуществится, пока не выйдет окно с выбором сертификата (скрин - "Блокиратор отключен (1)") и вы не пройдете аутентификацию. Если вы нажмете отмену или возврат, то нужно будет перезапускать internet explorer. Перед этим у вас должен быть настроен ПК ( https://install.kontur.ru/ )

***System configuration***

Information | value
--- | ---
Operating system: | Microsoft Windows NT 6.3.9600.0
Browser: | IE
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | WFP
Adguard DNS: | None
Stealth mode options(Windows) | below
Adguard filters: | 1 2 216

<details>

Stealth Mode enabled: StealthModeSettings: {

-   "BlockThirdPartyCookies": true,
-   "BlockThirdPartyCookiesPeriodMin": 30,
-   "BlockFirstPartyCookies": false,
-   "BlockFirstPartyCookiesMin": 2880,
-   "DisableThirdPartyCache": false,
-   "BlockWebRtc": false,
-   "BlockBrowserPushApi": false,
-   "BlockBrowserLocationApi": true,
-   "RemoveXClientDataHeader": true,
-   "HideSearchQueries": true,
-   "SendDoNotTrackHeader": true,
-   "RemoveRefererFromThirdPartyRequests": false,
-   "HideUserAgent": false,
-   "CustomUserAgent": null,
-   "CustomReferer": null,
-   "HideIp": false,
-   "CustomIp": "209.141.53.254"

</details>

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1501356

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Передай, что нужно попробовать эти домены по одному в исключения HTTPS добавить
kontur.ru
kontur-ca.ru
После добавления нужно перезапускать браузер.

**Comment by Alex-302** [comment]
Есть новости?

**Comment by Alex-302** [comment]
Добавили в исключения HTTPS.
