### ISSUE TITLE
Incorrect blocking in Говорящий телефон 2 app

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4682]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

https://play.google.com/store/apps/details?id=com.graysoft.smartphone

Screenshot:

User

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24358329/7af70c4a-1309-11e7-8cf2-e2d0b576522f.png)

![image](https://cloud.githubusercontent.com/assets/26434103/24358336/84d40d80-1309-11e7-883e-18b7f724a264.png)

</details>

Got incorrect blocking when reproduced:

<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24358479/ea120d46-1309-11e7-9fee-2b875d6d8b86.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Adguard version: | 2.8
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None 
Adguard filters: | English, Spyware, Annoyances, Russian, Mobile ads, German

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1530232

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
This placeholder is builtin, I can't remove it, even with partially unblocking.

**Comment by OlegSUP** [comment]
@Alex-302 
We could reproduce it on our side. These are the steps we tried:
1. Wi-Fi is ON, Adg is on High-Filter mode and with HTTPS. Result: there is an empty placeholder in the bottom of the screen.
2. Wi-Fi is ON, app has no permission for internet connection by Adguard and app caсhe was cleared. Result: there is an empty placeholder in the bottom of the screen.
3. Wi-Fi is Off, Adguard is ON and app cache was not cleared. Result: placeholder disappeared from the screen.

Same thing on beta version

**Comment by Alex-302** [comment]
> Wi-Fi is Off, Adguard is ON and app cache was not cleared. Result: placeholder disappeared from the screen.

I think this app just read WiFi status. Tried to setup invalid proxy(WiFi without Internet) - placeholder was shown.

**Comment by OlegSUP** [comment]
And nothing we can suggest?

**Comment by Alex-302** [comment]
No.

**Comment by OlegSUP** [comment]
User says that app has connection to the internet and not just reading status. catlog, time 14.21:

[2017-03-29-14-21-32.txt](https://github.com/AdguardTeam/AdguardFilters/files/878909/2017-03-29-14-21-32.txt)

**Comment by Alex-302** [comment]
The app can receive broads from the system, or check the status of the network at the moment. It can removed only by fixing the code, or by using some Xposed module.
