### ISSUE TITLE
Watch Putlocker

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4683]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

When the user has Adguard enabled it blocks some important elements such as seasons, series and so on. when he disables Adguard this website works as it should:
When Adguard is on this website looks like this http://prntscr.com/ep5zg6
When Adguard is off this website looks in this way http://prntscr.com/ep5z6f

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: |  6.1.314.1628
Adguard filters: | English, Spyware, Experimental, Annoyances, Russian, Social media

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(1164870): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I know many sites with Putlocker in the name. Please always provide direct link.
Fixed.

**Comment by Darina655** [comment]
@Alex-302 I am really sorry for the confusion: the link is http://www.watchfree.to/watch-2b91-Touched-by-an-Angel-tv-show-online-free-putlocker.html#close-modal

**Comment by Alex-302** [comment]
I know, it is fixed)
