### ISSUE TITLE
spotify app ios

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#4684]
adeventtracker.spotify.com

https://itunes.apple.com/us/app/spotify-music/id324684580?mt=8

**Comment by jo2dan23** [comment]
i just saw it is already in a filter list. but the filter list needs to be added to the filter template for adguard dns. can we do that? @Alex-302 https://github.com/AdguardTeam/AdguardDNS/issues/131

**Comment by Alex-302** [comment]
> adeventtracker.spotify.com

added to DNS filter
