### ISSUE TITLE
justhdfilme.com

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdguardFilters#46852]
Hello, please look on this domain:
https://justhdfilme.com/
https://justhdfilme.com/stream/movie4k.su/
It is an advertising site, it opens while browsing on Video Stream websites.

If you decide to block it, than please add it to AGH SDNS filter.

Thanks

**Comment by Alex-302** [comment]
@uservictor we always need a source URL for blocking ad reason(script). Destination is not always interesting.
