### ISSUE TITLE
Missed ads on dnilife.ru

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardFilters#4686]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
Child pages of website have numerous ads
* **Current behaviour**: Ad banners on the right side

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-03-28 at 5 57 47 am](https://cloud.githubusercontent.com/assets/26342177/24387042/8cb0422c-137b-11e7-9fcb-dbf774bd50aa.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Adguard filters: | Screenshot
<details>

![screen shot 2017-03-28 at 5 58 58 am](https://cloud.githubusercontent.com/assets/26342177/24387126/028c0fa8-137c-11e7-9d52-a8f324f7294c.png)

</details>

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 638522

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
