### ISSUE TITLE
www.seattletimes.com - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4687]
1. Occurs on child pages of <http://www.seattletimes.com/> only and only using Safari
2. Navigate to <http://www.seattletimes.com/>. select any story or subpage. Resulting webpage is blank. Navigating back brings up the home page.
3. Screenshot will show a blank page. Won’t be useful

I’ve done further testing and discovered that the Privacy Protection option that is causing the issue. Disabling Privacy Protection allows pages to appear normally.

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Safari
Adguard version: | 1.4.1
Adguard filters: | below

Filters subscriptions:

- ID=0 Name="User filter" Version=1.0.0.0
- ID=2 Name="English filter" Version=1.1.12.89
- ID=3 Name="Spyware filter" Version=1.0.11.9
- ID=4 Name="Social media filter" Version=1.0.18.11
- ID=14 Name="Annoyances filter" Version=1.0.11.10
- ID=10 Name="Filter unblocking useful ads" Version=1.0.0.95
- ID=6 Name="German filter" Version=1.0.32.31
- ID=7 Name="Japanese filter" Version=1.0.93.6
- ID=12 Name="Safari filter" Version=1.0.2.77
- ID=101 Name="EasyList" Version=1.0.69.22
- ID=118 Name="EasyPrivacy" Version=1.0.76.97
- ID=123 Name="Fanboy's Social Blocking List" Version=1.0.65.87
- ID=122 Name="Fanboy's Annoyances" Version=1.0.69.43
- ID=109 Name="EasyList Italy" Version=1.0.71.42
- ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.3.40
- ID=207 Name="Adblock Warning Removal List" Version=1.0.77.13
- ID=216 Name="Adblock polskie reguÅ‚y" Version=1.0.5.66

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1418175

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced with the same filters.
Is Adguard extension enabled also? Please ask user to find the filter, which causes it(disable one-by-one from the end of the list)

**Comment by evgeniy-ADG** [comment]
As I've already mentioned, >I’ve done further testing and discovered that the Privacy Protection option that is causing the issue. Disabling Privacy Protection allows pages to appear normally.

**Comment by Autoplayhater5** [comment]
I am the user who identified the issue. 

Any Privacy filtering causes this issue. I have disable every filter and narrowed this down to the Privacy settings. The main Privacy Protection toggle must be off as well as any specific privacy filter (e.g. EasyPrivacy) or child pages will not load.

**Comment by Autoplayhater5** [comment]
whitelisting the website is not a solution as it completely defeats the reason I purchased Adguard, to block ads and tracking and protect my privacy.

**Comment by Alex-302** [comment]
@Autoplayhater5 

> Any Privacy filtering causes this issue.

for example? I need to know the filter name, which break the site.
And write, please, step by step description with the links, because I can't reproduce.


> Will ask about the extension.

what about it?

**Comment by Autoplayhater5** [comment]
The Privacy Protection controlled by the slider:
<img width="385" alt="screen shot 2017-04-05 at 6 33 58 am" src="https://cloud.githubusercontent.com/assets/23619858/24707839/f03cf1f6-19c9-11e7-9fa8-076b95536308.png">
Pages do not load and display as a blank when the slider is in the "on" position.

These two filters cause intermittent problems as well.
 
<img width="276" alt="screen shot 2017-04-05 at 6 40 36 am" src="https://cloud.githubusercontent.com/assets/23619858/24708167/f412bb52-19ca-11e7-9be8-f1b9307c0bbd.png">

I tested the above my turning all filters off, then adding back one by one while testing the site behavior.

**Comment by Alex-302** [comment]
```
ID=101 Name="EasyList" Version=1.0.69.22
```
this filter is unnecessary, if you are using English Filter.
 

> Pages do not load and display as a blank when the slider is in the "on" position.

Tried again and still not reproduced.
Please try these rules for test:
@@||seattletimes.com^$domain=seattletimes.com
*or*
@@||seattletimes.com^$urlblock

**Comment by Autoplayhater5** [comment]
I added them both as user rules. will test and get back to you.
