### ISSUE TITLE
TimParty Incorrect Blocking [AG Tracking Protection]

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardFilters#46887]
### List the website(s) you're having issues:

`https://www.timparty.tim.it/`

### What happens?

Blank (white) page.

### List Subscriptions you're using:

- AG Base
- AG Tracking Protection
- EasyList Italy

### Your settings

- OS/version: macOS
- Browser/version: Firefox
- Adblock Extension/version: uBlock0 - AdGuard Ext

### Problematic rule: 
`||googletagmanager.com/gtag/$3p`

### Possible fix:
`@@||googletagmanager.com^$domain=timparty.tim.it`

**Comment by krystian3w** [comment]
@mapx- breakage with:

`||googletagmanager.com^`
`Peter Lowe's Ad and tracking server list `

**Comment by BlazDT** [comment]
Fixed

**Comment by superlex** [comment]
@BlazDT 
The issue affects MyTim app too.
Try
`@@||googletagmanager.com^$app=it.telecomitalia.centodiciannove`
