### ISSUE TITLE
vk.com - sponsored post

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4688]
something new i suppose
https://vk.com/tavpauka
adg 1.4.1
chrome rus en malware social media annoyances 

![screenshot 2017-03-28 12 42 52](https://cloud.githubusercontent.com/assets/23637588/24402182/1947ba0a-13c0-11e7-9d86-270f23fb3dca.png)

was posted at 8.20 so scroll down

**Comment by Alex-302** [comment]
fixed
