### ISSUE TITLE
Blocking part of the site at http://yolkki.abscity.ru/

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4690]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Adguard blocks part of the site that is not an ad.
Go to http://yolkki.abscity.ru/ and click "Акции"

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-03-28 at 10 09 43 pm](https://cloud.githubusercontent.com/assets/26434103/24423029/52c24d38-1404-11e7-8909-6f47576b21e1.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
Without Adguard
Screenshot:
<details>

![screen shot 2017-03-28 at 10 09 58 pm](https://cloud.githubusercontent.com/assets/26434103/24423040/5982a438-1404-11e7-9f6e-0668d14f623b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | User, English, Spyware, Social, Annoyances, Social media, Russian

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1531265

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
