### ISSUE TITLE
haxdown.com [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#46912]
https://haxdown.com/mediahuman-youtube-downloader-3-9-9-30-full-patch/13764/

Please remove the fake links from this page.

https://prnt.sc/qi2p55

Seen on AG for Chrome

**Comment by krystian3w** [comment]
`##a[href*="/go.php?a_aid="]`

uBo use this as generic filter to kill fake buttons: https://github.com/uBlockOrigin/uAssets/issues/6686

https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L22897

**Comment by krystian3w** [comment]
@AdamWr  sprawdzisz czy wycinacie też z `releaseload.com`?

> ![obraz](https://user-images.githubusercontent.com/35370833/71683617-5653db00-2d93-11ea-97e6-19541888260c.png) |
> --- |

**Comment by AdamWr** [comment]
Z tego co patrzyłem, to te reguły to już wycinają:
```
||wp.com/crackingpatching.com/wp-content/uploads*/*Download
||wp.com/crackingpatching.com/wp-content/uploads/*/Head-Image.png
```
