### ISSUE TITLE
Blocking music at my.mail.ru

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4693]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
After playing 1-2 tracks music stops and you need to refresh the page. We reproduced it and it works fine when English filter disabled.

Link to users page with music:
https://my.mail.ru/inbox/vt-malrah/music/media

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | English, Russian, User, Social media, Spyware, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1223915

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||ad.mail.ru/static/admanhtml/rbadman-html5.min.js$domain=my.mail.ru
@@||ad.mail.ru/vp/*?content_id=*&duration=*&mm_catid=$domain=my.mail.ru
```

Это для меня. Пустой конфиг.
```
{
  "settings":
    {
        "preroll":{}
    },
  "sections":
    {
    "preroll":
      [
        
      ]
    }
}
```

**Comment by Alex-302** [comment]
Если будет звуковая реклама - сообщи.

**Comment by OlegSUP** [comment]
Ok
