### ISSUE TITLE
Missed ads on arhsvoboda.ru

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardFilters#4694]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: ads on site
* **Current behaviour**: Vertical banner in the mid-right section
Site was in our blacklists till today. Shouldn't stop the adblocking, but just to let you know.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-03-29 at 12 30 52 pm](https://cloud.githubusercontent.com/assets/26342177/24448330/82128436-147c-11e7-9a2a-475d5262e063.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Chrome
Adguard filters: | English, Russian, Spyware, Social Media

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Из списка уберём.
Добавил в русский фильтр
```
arhsvoboda.ru##.ad_wraper
```
