### ISSUE TITLE
Missed ad at songmeanings.com

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4695]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Missed ad at http://songmeanings.com/m/songs/view/62577/ and other parts of site.
Reproduced only in Safari iOS Agent

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-03-29 at 12 46 34 pm](https://cloud.githubusercontent.com/assets/26434103/24448795/e3c8ba82-147d-11e7-9f12-854e16eb035c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.40
Simplified filters(iOS) | off
Adguard DNS: | None 
Adguard filters: | English, Russian,  Social media, Spyware, Annoyances, Safari

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1355668

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
||songmeanings.com/ez_aba_load/?
```
