### ISSUE TITLE
my.mail.ru/music - switching between songs is broken

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4696]
my.mail.ru/music 
adg 1.4.1
chrome 

try to play song by clicking play button: it works only first time. you can not switch to any other song - it won't play

 problem is EN filter i guess

![screenshot at mar 29 16-13-39](https://cloud.githubusercontent.com/assets/23637588/24456245/164302a2-149b-11e7-93fa-6c3de7bdb904.png)

**Comment by Alex-302** [comment]
duplicate
https://github.com/AdguardTeam/AdguardFilters/issues/4693
