### ISSUE TITLE
incorrect blocking https://soundcloud.com/musicformedia-1/corporate-success-and-confidence-bundle-royalty-free-background-commercial-music

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4697]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: incorrect blocking https://soundcloud.com/musicformedia-1/corporate-success-and-confidence-bundle-royalty-free-background-commercial-music

the protection "cuts" a part of the pop-up window if you press "share"

Screenshot:
with Adg disabled 
![image](https://cloud.githubusercontent.com/assets/25711093/24490521/9a453184-152b-11e7-9b0e-dd59aa9513f4.png)

if the filtration is enabled:
![image](https://cloud.githubusercontent.com/assets/25711093/24490565/b85d21b8-152b-11e7-8e09-d0da487cc313.png)

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | Russian, English, experimental, annoyance, social, spyware, mobile

Ticket ID(if exists): 1099770

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
