### ISSUE TITLE
e.mail.ru

### ISSUE THREAD

**Issue by ahmedov-arsen** [AdguardTeam/AdguardFilters#46989]
! Блокировка боковой рекламы в списке писем.
e.mail.ru#?#div:matches-css(z-index: |100|)
! Уменьшение пустоты после блокировки боковой рекламы.
e.mail.ru#$#div[style^="max-width:"] > div:first-child + div { margin-right: 0 !important; }
e.mail.ru#$#div[style^="margin-right:"] > div:first-child + div { margin-right: 0 !important; }
! Исправление стиля для возврата кнопки "Фильтр" на место.
e.mail.ru#$#.portal-menu__group_float { float: left !important; }

**Comment by Sergey-Lyapin** [comment]
@ahmedov-arsen 
Рекламу на mail.ru мы блокируем с помощью скрипта AdGuard Extra

Пользователям браузерного расширения нужно установить скрипт `AdGuard Extra`. Для этого понадобится браузерное расширение-скриптоприёмник `Tampermonkey`

Ссылка на `AdGuard Extra`
https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js

После установки скрипта нужно будет зайти в настройки `Tampermonkey`, включить режим эксперта, переключить режим встраивания на `мгновенный` и перезапустить расширение:
![image](https://user-images.githubusercontent.com/8361299/62641343-07248e00-b94c-11e9-9775-9854a7922889.png)

![image](https://user-images.githubusercontent.com/8361299/62641299-f7a54500-b94b-11e9-8a83-885d89abbeec.png)
