### ISSUE TITLE
[Annoyances - Push Notifications] fox17online.com

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#46994]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Floating web notifications box on `https://fox17online.com/`
* **Current behaviour**:

A floating box that promotes web notification news updates show up. My suggested fix is `fox17online.com###desktop-notifications`. In contrast to what one could've thought, `||fox17online.com/push-worker.js^` does *not* work.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/71701273-d21c4a80-2dc8-11ea-92fc-80d55a4feb5b.png)

</details><br/>

* **Expected behaviour**: 

That the box does not show up.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/71701346-2fb09700-2dc9-11ea-8dd9-6defd6562f3c.png)
</details><br/>

***Steps to reproduce the problem***:

1) Visit `https://fox17online.com/`.
2) Wait up to 15sec.
3) See the box appear.

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/71701385-6edee800-2dc9-11ea-8b0f-f9c3d896caa7.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 November 2019 Update
Operating system version (Android/iOS) | N/A
Browser:                               | Chrome 79.0.3945.88 64-bit
AdGuard version:                       | Nano Adblocker 1.0.0.135 + Nano Defender 15.0.0.176
Filters enabled:                       | See screencap above
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | N/A
Simplified filters (iOS only)          | N/A
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | N/A
Helpdesk ID (if exists):               | N/A

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
It is registered here: https://ewscripps.brightspotcdn.com/resource/0000016e-c789-da85-a1ef-ffb9c4770000/styleguide/All.min.7c6b06e2a54715bff19b904c59e6faef.gz.js
