### ISSUE TITLE
Проблема с wifi в метро

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#4699]
Проблема с wifi в метро. Крутится колесо  и не подключается к сети. Проблема появилась неделю назад. Если отключить защиту, то все работает. Фильтры стоят по-умолчанию, фильтрация качественная, https, версия последняя стабильная.
Я не знаю какие именно логи нужно собрать, можете внизу написать, что нужно? В метро бываю не каждый день, так что желательно перечислить все возможные логи для сбора

**Comment by ministr91** [comment]
Я так понимаю, что здесь нужен https://kb.adguard.com/ru/android/solving-problems/har ? Что-то еще может пригодится?

**Comment by Alex-302** [comment]
Вот две группы правил, сделаны почти наугад, но могут и помочь.
```@@||ads.adfox.ru/*/prepareCode$domain=auth.wi-fi.ru
@@||ads.adfox.ru/*/getid?pr=*&t=json$domain=auth.wi-fi.ru
```

```
@@||cdn.vmet.ro/websso/css/mac_login.css
@@||cdn.vmet.ro/websso/css/auth_success.css
@@||cdn.vmet.ro/websso/js/mac_login.js
@@||cdn.vmet.ro/brandings/_common/metro-auth.js
@@||vmet.ro/?OPERATOR_MNP=$popup
@@||cdn.vmet.ro/websso/js/auth_success.js
@@||cdn.vmet.ro/brandings/_common/pages.js
```
Нужен HAR и лог HTTP запросов с указанием времени открытия страницы авторизации. Открывать надо в приватном режиме, чтоб избежать кэширования.

**Comment by ministr91** [comment]
Группы правил добавить можно в разделе Настройки - Собственный фильтр - Добавить правило?
В приватном режиме открывать только при логе HTTP или при HAR логе тоже?

**Comment by Alex-302** [comment]
> Группы правил добавить можно в разделе Настройки - Собственный фильтр - Добавить правило?

да



> В приватном режиме открывать только при логе HTTP или при HAR логе тоже?

это можно сделать одновременно.

**Comment by ministr91** [comment]
Правила не действуют
Вот ссылки на логи
Время 12:42-12:43
http://file.karelia.ru/zf2s8n/
если не грузит, то тут https://ru.files.fm/u/3pf2f6d4

**Comment by Alex-302** [comment]
Вот такие правила:
```
@@||ads.adfox.ru/*/getCode?p1=*;p2=v&amp;pe=b&amp;pfc=bezbz&amp;pfb=dksmt&amp;pr=eslgyih$domain=auth.wi-fi.ru
@@||ads.adfox.ru/*/getCode?p1=*&p2=*&ptrc=$domain=auth.wi-fi.ru
@@||ads.adfox.ru/*/getDefaultImage?p1=$domain=auth.wi-fi.ru
@@||ads.adfox.ru/*/getid?pr=*&t=json$domain=auth.wi-fi.ru
@@||ads.adfox.ru/*/prepareCode?pr=*auth.wi-fi.ru$domain=auth.wi-fi.ru
@@||banners.adfox.ru/transparent.gif$domain=auth.wi-fi.ru
@@||top-fwz1.mail.ru/counter?id=*;js=na$domain=auth.wi-fi.ru
```
импорnировать можно по URL:
https://gist.githubusercontent.com/Alex-302/71bcfc1d34b9a1fa08d5bcb2997ce72a/raw/6123b8bda97b12c16518639ef1fc89ec45dc4b5c/metro.txt

**Comment by ministr91** [comment]
Не работает, есть еще варианты?

**Comment by Alex-302** [comment]
Теперь нужен лог, снятый при добавленных правилах(с указанием времени попытки)

**Comment by Alex-302** [comment]
Ещё вот такое добавь:
```
@@||auth.wi-fi.ru^$content
```

**Comment by ministr91** [comment]
Этот параметр добавлять в качестве еще 1 правила или удалить старое правило и новое добавить?

**Comment by ministr91** [comment]
В выходные не смогу проверить, только в понедельник
https://ru.files.fm/u/bjdddd6g
http://file.karelia.ru/547w7n/

**Comment by ministr91** [comment]
17-54 время

**Comment by Alex-302** [comment]
Криво добавились, судя по скрину. Добавь вручную по одному
```
@@||ads.adfox.ru/*/getCode?p1=*;p2=v&amp;pe=b&amp;pfc=bezbz&amp;pfb=dksmt&amp;pr=eslgyih$domain=auth.wi-fi.ru
@@||ads.adfox.ru/*/getCode?p1=*&p2=*&ptrc=$domain=auth.wi-fi.ru
@@||ads.adfox.ru/*/getDefaultImage?p1=$domain=auth.wi-fi.ru
@@||ads.adfox.ru/*/getid?pr=*&t=json$domain=auth.wi-fi.ru
@@||ads.adfox.ru/*/prepareCode?pr=*auth.wi-fi.ru$domain=auth.wi-fi.ru
@@||banners.adfox.ru/transparent.gif$domain=auth.wi-fi.ru
@@||top-fwz1.mail.ru/counter?id=*;js=na$domain=auth.wi-fi.ru
@@||auth.wi-fi.ru^$content
```
Чтоб быстрее добавить, сначала выключи все фильтры, а после добавления правил - включи.

**Comment by ministr91** [comment]
а можешь кинуть ссылку на код? Я по юрл адресу импортирую

**Comment by ameshkov** [comment]
Вот же он:
https://gist.githubusercontent.com/Alex-302/71bcfc1d34b9a1fa08d5bcb2997ce72a/raw/6123b8bda97b12c16518639ef1fc89ec45dc4b5c/metro.txt

**Comment by Alex-302** [comment]
https://gist.github.com/Alex-302/f80cdfd51584956e8bdb06aa3cb49eeb

**Comment by ameshkov** [comment]
@Alex-302 на RAW файл давай ссылку, а то белиберда же импортнется

**Comment by Alex-302** [comment]
поправил

**Comment by ministr91** [comment]
Все правильно https://ru.files.fm/u/kucys77s ?

**Comment by Alex-302** [comment]
Да. Только скрины лучше на хостинг изображений заливай, а то лишние действия приходится делать.

**Comment by ministr91** [comment]
Скинь ссылку

**Comment by ministr91** [comment]
Какой хостинг посоветуешь?

**Comment by vozersky** [comment]
@ministr91 сюда, на гх лучше всего заливать. 

@Alex-302 скинул новый HAR

**Comment by ministr91** [comment]
@vozersky как сюда залить? Я не вижу здесь кнопки загрузить
@Alex-302 глянь полностью видео. Способ частично рабочий. После 2 минут я все-таки смог запустить интернет, только не понял как. Есть еще варианты?
https://ru.files.fm/u/nxu544zz
Время 15:44

**Comment by Alex-302** [comment]
не понятно по видео что ты делал.
На проверку(без предыдущих правил и ***без мобильного фильтра***):
```
||wi-fi.ru/ad_video/*.mp4$mp4,important
@@||ads.adfox.ru/*/prepareCode^$domain=auth.wi-fi.ru
@@||ads.adfox.ru/*/getCode^$domain=auth.wi-fi.ru
@@||login.wi-fi.ru^$jsinject
```

**Comment by ministr91** [comment]
По видео я пытался зайти в инет. Если входить в инет без защиты, то все просто. Я включаю вай фай, далее захожу в браузер, нажимаю любой сайт, меня перенаправляет на страницу авторизации, далее нажимаю войти в интернет, смотрю рекламу и получаю свой инет. 
По видео я пытался сделать тоже самое, но не вышло. В гугл хроме вообще писало, что страница не доступна, а в зеленом браузере все было норм, до того момента, пока я не нажал войти в интернет - вместо просмотра рекламы я получил мелкие картинки

**Comment by Alex-302** [comment]
https://gist.githubusercontent.com/Alex-302/dd560f1c30d6140cb680bd6da77d5749/raw/f2b1a1162256ebdcb692fee2810272a76c14c0fe/rules
> или покажи как самому такие ссылки делать

идешь на https://gist.github.com , вводишь нужный текст и жмёшь `Create secret gist`, в открывшемся окне жмёшь `Raw`, чтоб открыть ссылку в исходном виде.

**Comment by ministr91** [comment]
Как картинки сюда загрузить?
Я запустил сначала без фильтра мобильного, с трудом но запустился. Далее спустя какое-то время я запустил с мобильным фильтром и ничего не вышло, далее попытался опять без фильтра и ничего не вышло 
https://ru.files.fm/u/vtynhruu

**Comment by vozersky** [comment]
![image](https://cloud.githubusercontent.com/assets/17472907/24653640/53af6218-193f-11e7-9cf5-67ee77e9f5d5.png)

**Comment by ministr91** [comment]
@vozersky молодец, кинул скрин, а где это найти? Я не вижу в мобильной версии такого. Есть только close and comment и comment

**Comment by Alex-302** [comment]
Только через полную версию сайта можно.

**Comment by vozersky** [comment]
@ministr91 нужно использовать полноценную версию. "Request desktop site" в настройках браузера.

**Comment by ministr91** [comment]
@Alex-302 идеи закончились? Зачем было тему закрывать, если проблема не решена?
Кто может, помогите решить проблему
@ameshkov @vozersky @evgeniy-ADG @nkartyshov @Revertron @zebrum

**Comment by Alex-302** [comment]
она не закрыта.

**Comment by ministr91** [comment]
Хорошо, а что тогда делать? Как проблему решать?

**Comment by ameshkov** [comment]
Баг в 2.9:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1154

**Comment by ameshkov** [comment]
Хм, но он только с VPN, а у @ministr91 прокси, и там все должно нормально работать. Запросы к auth.wi-fi.ru я вижу например

**Comment by Alex-302** [comment]
Внёс изменения в фильтр. Через час-полтора можно будет обновляться.

**Comment by ministr91** [comment]
Никаких изменений

**Comment by ministr91** [comment]
Да и у меня стоит 2.8

**Comment by ministr91** [comment]
Я же видео записал мое последнее, значит проблема есть @ameshkov @Alex-302

**Comment by ministr91** [comment]
Может мне перед тем как проверять нужно было старое правило удалить? Я попробую завтра еще раз без правил

**Comment by Alex-302** [comment]
> Никаких изменений

Расшифруй.
Фильтры обновил? Режим по прежнему - локальный прокси?

**Comment by Alex-302** [comment]
> Может мне перед тем как проверять нужно было старое правило удалить?

да, все старые правила нужно удалить

**Comment by ministr91** [comment]
Фильтры обновил, режим не менял, алгоритм тоже старый стоит

**Comment by ministr91** [comment]
Завтра попробую без старых правил

**Comment by ministr91** [comment]
Ну что же, частично работает. На одном браузере заходит, но другом нет

**Comment by ministr91** [comment]
Хотя ладно, проблема решена. Закрывайте тему

**Comment by Alex-302** [comment]
> частично работает

расшифруй. Что было после нажатия кнопки Вход?
> но другом нет

в каком не работает и как это проявляется? Алгоритм фильтрации качественный?

**Comment by ministr91** [comment]
Да все уже заработало, все норм. Алгоритм фильтрации я не менял, всегда качественный стоит. Если будут проблемы, то я напишу. 
Закрывайте тему

**Comment by ministr91** [comment]
После нажатия кнопки вход, перенаправило на новую страницу, 5 сек крутилось колесо на черном фоне, потом опять перенаправило на wi-fi.ru и все заработало

**Comment by Alex-302** [comment]
ну ок

**Comment by ameshkov** [comment]
Ура товарищи:)

**Comment by ministr91** [comment]
@Alex-302, @ameshkov возникла небольшая проблема, это не критично, но доставляет некоторые неудобства. На этой неделе запишу видео, все сами посмотрите

**Comment by ministr91** [comment]
@Alex-302, @ameshkov вы еще здесь? Объясню проблему. Я не могу зайти с браузера гугл хром в интернет. Видеозапись и логи я прикрепил. На видео видно, что когда я звпуакаю интернет, то сразу захожу в хром. Нажимаю на сайт и у меня не переходит на страницу вай фая, далее захожу в другой браузер и там все норм. Потом я делаю перезапуск защиты и опчть пробую через хром - все работает. Какие есть варианты решения проблемы? 
https://ru.files.fm/u/pg3mbbgz

**Comment by ministr91** [comment]
Самое интересное то, что когда я отключаю вай фай и  через 20 минут снова подключаюсь, то у меня браузер хром почему-то переходит на страницу авторизации. Конечно, сперва получается сообщение от ошибке, но если много раз жать на обновить (где-то раз 5 нажал) :D то в конце концов он сдается и все-таки переходит на страницу авторизации

**Comment by ministr91** [comment]
![screenshot_2017-04-13-08-30-43](https://cloud.githubusercontent.com/assets/22351242/24991542/2f48f650-2024-11e7-9e50-98678d95613a.png)

**Comment by ministr91** [comment]
Можно еще тему открыть временно до тех пор, пока проблема не будет решена?

**Comment by Alex-302** [comment]
@ministr91 
попробуй авторизоваться с Адгардом, но с выключенными фильтрами. Возможно, это из-за того, что пытаешься сразу открыть сайт с HTTPS, и хрому не нравится сертификат, который при авторизации ставит провайдер.
Кстати, нажми на зелёный замок, там можно название сертификата посмотреть.

**Comment by ministr91** [comment]
Да там проблема в другом. В самом начале когда я пытаюсь войти, он вообще не идет на страницу авторизации. Это уже потом, когда я перезапускаю защиту, то он говорит о сертификате, но его легко обойти - я на видео это сделал. Нажал там что-то внизу и перешло. 
Самая главная проблема - это в самом начале, когда не хочет переходить на страницу авторизации и нет сообщения от ошибке сертификата

**Comment by ministr91** [comment]
Но попробую сделать как ты скзаал

**Comment by Alex-302** [comment]
@ministr91 если не авторизует без фильтров(они вряд ли ломают), попробуй через не-HTTPS-ный сайт зайти, например i.ua

**Comment by ministr91** [comment]
Есть прогресс. Если с фильтрами вообще никак не зайти было, на видео я пытался, то теперь ситуация поменялась. Я отключил фильтры и получилось войти. Все так же как и на видео, когда я отключил защиту

**Comment by ministr91** [comment]
![screenshot_2017-04-13-16-32-47](https://cloud.githubusercontent.com/assets/22351242/25007052/b87e0026-2067-11e7-8880-38859e21918f.png)
![screenshot_2017-04-13-16-32-38](https://cloud.githubusercontent.com/assets/22351242/25007051/b87d540a-2067-11e7-9bc7-bcfe45145083.png)

**Comment by ministr91** [comment]
![screenshot_2017-04-13-16-32-51](https://cloud.githubusercontent.com/assets/22351242/25007182/30fadb14-2068-11e7-8646-b4d408609db9.png)

**Comment by ministr91** [comment]
На http://i.ua у меня вообще не заходит, вечная загрузка, хоть с защитой, хоть без

**Comment by Alex-302** [comment]
странно. Хром ругается на несоответствие поля CN и домена, к которому метрошный маршрутизатор применил сертификат. Дельфин этот момент проигнорировал.
Раньше и без Адгарда такую проблему наблюдал иногда. Можешь скинуть лог запросов с указанием времени, когда хром не пустил?

**Comment by Alex-302** [comment]
Ещё можно устаносить бету 2.9, в ней есть встроенный журнал, и там можно посмотреть, какие запросы были(и были ли) заблокированы фильтрами. Этот журнал нужно предварительно включить.

**Comment by ministr91** [comment]
Ты был прав. Когда на рамблер не получалось войти, (это в 1 случае на видео, до выключения защиты), то я сейчас попробовал зайти на не HTTPS сайт и зашел http://bibliotekar.ru

**Comment by ministr91** [comment]
Ну так я же видео снял, там и время видно точное и логи. Выше ссылка

**Comment by ministr91** [comment]
Не хочется бету ставить. Есть варианты решения проблемы?

**Comment by Alex-302** [comment]
Ну мне думается, что это не проблема, а просто реакция Хрома на несоответствие сертификата домену. Я много раз пробовал так же авторизоваться у местного провайдера, и когда открываешь сайт с HTTPS хром всегда был против.
Я вижу такой выход - поставить страницу авторизации стартовой, или добавить в закладки.

**Comment by ministr91** [comment]
То есть вариант решения проблемы такой, что с хрома нужно открывать любые НЕ HTTPS страницы перед авторизацией? Почему тогда, если отключить защиту, то я могу зайти в adguard с трудом, а с вкл защитой вообще никак не входит? На видео все подробно есть. Если это так, а это так, то значит что-то в adguard, потому что он блокирует соединение и не дает войти в сеть. Почему же при выключенном защите входит, а при включенной вообще никак не войти?

**Comment by ministr91** [comment]
На видео в первом случае никак не войти, потом я отключил защиту, рамблер написал что-то там про сертификат, я нажал все равно перейти на рамблер и вошел в сеть

**Comment by ministr91** [comment]
Почему с дельфином таких проблем нет, а с хромом есть?

**Comment by ministr91** [comment]
Я предлагаю коллегиально решить эту проблему. Может @ameshkov @vozersky @evgeniy-ADG @nkartyshov @Revertron @zebrum или еще кто-нибудь сможет подкинуть идеи

**Comment by ameshkov** [comment]
Это не наша проблема

**Comment by ministr91** [comment]
Серьезно? Вообще никак не решить проблему? Я кратко расскажу в чем дело. Не удается открыть страницу с HTTPS, а обычные страницы открывает и можно спокойно подключаться к вай фай. Это  немного странно, потому что после подключения к вай фай страницы с HTTPS подключаются

**Comment by Alex-302** [comment]
Если бы пускало, то смысл в HTTPS бы пропал. Они подменяют сертификат на свой, и Хром его посылает в дальнее путешествие. Выход - использовать китайские браузеры, которым плевать на несоответствие сертификата домену, либо всегда сначала открывать `http://auth.wi-fi.ru/`
Так всегда будет в случае, когда авторизация происходит через редирект на страницу с инструкциями. Плавали, знаем)

**Comment by ministr91** [comment]
Жаль, если никто не может помочь, то пора закрыть тему @Alex-302

**Comment by ministr91** [comment]
@vozersky @evgeniy-ADG @nkartyshov @Revertron я разочаровался в вас, могли быть хоть что-нибудь написать

**Comment by Alex-302** [comment]
Зачем всем отписываться, если ответ уже был дан ранее?

**Comment by ministr91** [comment]
Ну ладно, может ты и прав

**Comment by ameshkov** [comment]
> Не удается открыть страницу с HTTPS, а обычные страницы открывает и можно спокойно подключаться к вай фай

Ну справедливости ради - у них нет выбора. Они ж не могут взять и сразу пустить в сеть без авторизации весь HTTPS-трафик. Приходится подменять сертификат на свой, на который браузер ругается.

В любом случае, Adguard тут ни при чем.

**Comment by ministr91** [comment]
@ameshkov, а почему тогда при выключенном adguard я спокойно захожу на HTTPS сайты до авторизации? Ввожу любой HTTPS сайт и меня автоматически перебрасывает на http://auth.wi-fi.ru/?
Значит adguard играет свою роль?

**Comment by Alex-302** [comment]
@ministr91 адрес вводишь именно с приставкой `https://` или просто адрес?

**Comment by ministr91** [comment]
Конечно же с HTTPS.
Может я что-то путаю, завтра проверю

**Comment by ministr91** [comment]
Логи нужно будет собрать?

**Comment by ministr91** [comment]
Сделаю HAR и лог HTTP запросов

**Comment by Alex-302** [comment]
HAR не нужен.
Проверь так - создай закладку с `https://adguard.com` и удостоверься, что префикс именно https. И в метро открой закладку. Сперва с Адгардом.

**Comment by ministr91** [comment]
![screenshot_2017-04-27-18-46-14](https://cloud.githubusercontent.com/assets/22351242/25492514/eb03bf80-2b7b-11e7-90c5-8c21dff4deec.png)


![screenshot_2017-04-27-18-46-56](https://cloud.githubusercontent.com/assets/22351242/25492572/107c6c9e-2b7c-11e7-929e-d9c835eb9bd8.png)
1 скрин с эдгуардом, второй без и возможность перейти на сайт есть. Конечно, если много раз жать на перезагрузку, то все придет в норму.

**Comment by ministr91** [comment]
Лога HTTPS запросов нет, потому что эдгуард его просто не записал, т.к. не было интернета

**Comment by ministr91** [comment]
Это не критичная проблема, не нуждается в исправлении, просто говорю как есть

**Comment by ameshkov** [comment]
> Конечно, если много раз жать на перезагрузку, то все придет в норму.

Я даже уточню, не много - а ровно два раза. В первый раз Adguard почуял неверный сертификат и порвал соединение, больше он соединение с этим доменом фильтровать не будет до переподключения к другой сети.
