### ISSUE TITLE
Tweet it For Windows app shows ads through buildin webbrowser works with Javascript.

### ISSUE THREAD

**Issue by gvanosch12** [AdguardTeam/AdguardFilters#4700]
Hello Everyone,

I use the app Tweet it For Windows on my windows 10 machine x 64 bits version,and i have expeirenced that if i browse to the build-in browser works with Javascript code,through the Javasriptcode showsup advertisement screens on multiple websites(i show you for example some sites with screenshots)

Now i come to the strange thing i expeirence,if i enable the "Tweet it" advertisement filter on the Adguard application,the Advertisement screens are now away on all sites,but the "Tweet it For Windows" features as: Tweet updates,messages,mentions,my account,likes enz aren;t working anymore and i can;t reach those features and are unable to use those features,my tweet updates does not work anymore and does not refresh/update

I have with Vasily Bagirov made before a few months ago an remote session for testing what happend on differend cases,but he was unable to filter the ads on the app "Tweet it For Windows" on websites and on the same time to make the app working on all the features wich i have described,on all the actions wich were made the "Tweet it For Windows" app have to restart again to make the changes having effect.

Are you guys having a solution for this issue

Kindly regards,

Geert Van Osch

**Comment by gvanosch12** [comment]
I have installed and tested with the latest version of Adguard version: 6.1.331.1732 on march 30 2017

Kindly regards,

Geert Van Osch

**Comment by Alex-302** [comment]
@gvanosch12 sorry for the late reply. Is the issue still actual?

**Comment by gvanosch12** [comment]
Yes,i have tested several sites there are still showing up adscreens(see screenshots)

![schermopname 24](https://user-images.githubusercontent.com/19804873/28531656-c5e85d30-7097-11e7-963a-86e31239d1b5.png)

![schermopname 25](https://user-images.githubusercontent.com/19804873/28531673-d3f19162-7097-11e7-8729-f43b48c3548d.png)

![schermopname 26](https://user-images.githubusercontent.com/19804873/28531683-dc8e8fc8-7097-11e7-8097-5875b32802bb.png)

![schermopname 27](https://user-images.githubusercontent.com/19804873/28531699-e3dc022e-7097-11e7-8dec-cfb3d587ea09.png)

![schermopname 28](https://user-images.githubusercontent.com/19804873/28531711-e9674df2-7097-11e7-82f3-4f7c44c1f9ea.png)

**Comment by Alex-302** [comment]
Is this app added to filtered apps in Adguard settings? Do you see requests from this app in the filtering log?

**Comment by gvanosch12** [comment]
If i added this app to  the Filtered apps on Adguard settings,the filter does break the app from normal functioning,i don;t receive any updates anymore,also my account info does not load anymore,no new tweet updates,no new messages,no timeline updates,they simply doesn;t load anymore.
It looks like that the app recognizes the presence of an adblocker and directly shuts down the app from functioning.
I don;t see any log filtering

**Comment by Alex-302** [comment]
Strange. Is it broken even with disabled filters?

**Comment by gvanosch12** [comment]
No the app functioning is only been broken with the filters enabled not with the filters disabled

**Comment by Alex-302** [comment]
Ok. I can't install this app. What about remote access(to PC or virtual machine) with my login and password?

**Comment by gvanosch12** [comment]
A few months ago "Vasily Bagirov" from Adguard has also connect to my pc remotely,he has tried several options from the app,but with no result,wy the app has been broken with the filter enabled from the app
Maybey you can ask "Vasily Bagirov" from the results.
I have heard of that modern UI hosted apps are not be filtered by default at the moment because of problems with some broken apps at the past.


https://forum.adguard.com/index.php?threads/tweet-it-for-windows-app.14137/

https://forum.adguard.com/index.php?threads/some-sites-doesn-t-load-if-the-systemposixspawnserver-are-enabled.21458/

https://github.com/AdguardTeam/AdguardForWindows/issues/1647

**Comment by Alex-302** [comment]
@gvanosch12 
> not with the filters disabled

I think it is broken by some filter. Can you show me blocked requests in the filtering log?

**Comment by gvanosch12** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/4700

![schermopname 29](https://user-images.githubusercontent.com/19804873/28590939-4729cb58-7184-11e7-9b12-545ef48667f2.png)

**Comment by gvanosch12** [comment]
https://forum.adguard.com/index.php?conversations/remote-control-session.12942/

**Comment by gvanosch12** [comment]
![schermopname 31](https://user-images.githubusercontent.com/19804873/28591721-ffb300ca-7186-11e7-93d2-1c1b36b8601b.png)

**Comment by Alex-302** [comment]
Hmmm....
Please add temporary exclusions for blocked domains. Add `@@||` before the domain. For example
`@@||pipe.aria.microsoft.com`

**Comment by gvanosch12** [comment]
![schermopname 33](https://user-images.githubusercontent.com/19804873/28592199-816a9c12-7188-11e7-9c28-48a65985863d.png) 

gate.hockeyapp.net (blocked request with Tweet it For Windows app enabled)

This is what i get from blocked requests from the log,i don;t have logs with temporary exclusions for blocked domains

**Comment by Alex-302** [comment]
@gvanosch12 could you check with AdGuard 6.2?

**Comment by gvanosch12** [comment]
Yes,but i don;t have version 6.2 yet

**Comment by Alex-302** [comment]
You can get it here
https://github.com/AdguardTeam/AdguardForWindows/releases/tag/v6.2.433.2167-rc
Maybe it will be a final(release) build.

**Comment by Alex-302** [comment]
It is available on official site.

**Comment by gvanosch12** [comment]
Hi Alex,
I have enabled on Adguard the "Tweet it for windows filter" and it looks like that the app are working fine this time,it does not break the app from functioning and it does filter the adds on websites.
Great job guys i;m realy excited,i will continue monitor the app over time
Thanks!

**Comment by Alex-302** [comment]
ok)
