### ISSUE TITLE
lookszone.ru - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4702]
http://lookszone.ru/

with chome extension enabled:

![screenshot 2017-03-31 15 01 46](https://cloud.githubusercontent.com/assets/23637588/24549653/fe1ec4d4-1622-11e7-95bf-466cd8c9d6fa.png)

with adg 1.4.1:

![screenshot 2017-03-31 15 03 27](https://cloud.githubusercontent.com/assets/23637588/24549709/48932258-1623-11e7-9176-0a39820a69f2.png)

 and in both cases quite a lot redirects

**Comment by Alex-302** [comment]
Fixed
