### ISSUE TITLE
dizipub.com/ - site with ads 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4703]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: dizipub.com/desperate-housewives-8-sezon-19-bolum-izle/ - site with ads 

Screenshot:
http://prnt.sc/eqqihn

![image](http://somehosting.com/adg_off.jpg)
</details>

***System configuration***

Application version: 1.1.5.65

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.12.7 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.98 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.89 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.6.87 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.70 Enabled=YES

Ticket ID(if exists): 1524752

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Turkish filter
```
dizipub.com###video-oncesi img
```
