### ISSUE TITLE
kwikeer.com

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#47039]
**1**. Раскрываем статью сразу же, без необходимости нажимать каждый раз кнопку 'Читать далее'.

 &nbsp; **а**) Удаляем класс, скрывающий контент: `kwikeer.com#%#//scriptlet("remove-attr", "class", ".__post-content-preview")`

<details><summary>Screenshot:</summary>

![2020 01 04-1](https://user-images.githubusercontent.com/17948007/71759700-a9c44700-2ec1-11ea-9ca4-7f473a5325ff.png)
</details>

 &nbsp; **б**) Скрываем кнопку 'Читать далее': `kwikeer.com##[data-post-action-id]`

<details><summary>Screenshot:</summary>

![2020 01 04-2](https://user-images.githubusercontent.com/17948007/71759765-23a90000-2ec3-11ea-9582-f4d7c19e6bfd.png)
</details>

___________________________________________________

 **2**. АнтиАдБлок на видео в статье. Реагирует на `/showads.` из 'Базового фильтра AdGuard'. Помогает `@@/showads.$domain=vidyomani.com`, но лучше `/showads.$domain=~vidyomani.com`.

<details><summary>Screenshot:</summary>

![2020 01 04-3](https://user-images.githubusercontent.com/17948007/71759790-6ff44000-2ec3-11ea-88ba-69b4fbe9502c.png)
</details>

[https://kwikeer.com/animals/belka-8-let-nastojchivo-stuchala-v-okna-ljudjam-uznav-prichinu-zhilcy-opeshili/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://kwikeer.com/animals/belka-8-let-nastojchivo-stuchala-v-okna-ljudjam-uznav-prichinu-zhilcy-opeshili/)
<br/>

P.S: А к вам в эти праздники уже приходила Белка, или, может, вы её ждёте вот-вот?..

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.3.6
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by krystian3w** [comment]
```
kwikeer.com##.__post-content-preview::after
kwikeer.com#$#.__post-content-preview { max-height: unset !important; }

**Comment by Alex-302** [comment]
статью изменил так:
```
kwikeer.com#$#.__post-content-preview::after { background-image: none !important; content: "" !important; }
kwikeer.com#$#div[id^="post_"][class="__post-content-preview"] { max-height: none !important; }
kwikeer.com#$#div[data-post-action-id^="#post_"] > button[class="__post-content-btn"] { display: none !important; }
```

**Comment by krystian3w** [comment]
Bad filter is:

`kwikeer.com#$#.__post-content-preview::after { background-image: none !important; content: "" !important; }`

My works good / property:

```
!+ NOT_PLATFORM(ios, ext_safari, ext_android_cb)
kwikeer.com##.__post-content-preview::after
```

Extend CSS propsitions:

```
kwikeer.com#$#.__post-content-preview::after { background-image: none !important; content: "" !important; position: static !important; }

kwikeer.com#$#.__post-content-preview::after { display: none !important; }
```

**Comment by krystian3w** [comment]
The idea with the script itself is not bad as it does not come the "race condition"  on page (run too fast and only once) or restore a CSS class after detecting a code integrity violation.

**Comment by Alex-302** [comment]
Ok, replaced CSS rule.

**Comment by XX-J** [comment]
@Alex-302

 Если есть `{ display: none !important; ...}`, то какой смысл дописывать всё остальное `{ ... background-image: none !important; content: "" !important; position: static !important; }` ?

**Comment by krystian3w** [comment]
Backwards compatibility, as if some archaic Firefox or Chrome display is not enough?

**Comment by XX-J** [comment]
Support for the `display` property began with Chrome v2 and FireFox v3.

**Comment by krystian3w** [comment]
I found this:

https://github.com/AdguardTeam/AdguardFilters/blob/16d5c69ffd1bd230fbdd099041daa1350b69fe27/FrenchFilter/sections/general_extensions.txt#L35

**Comment by krystian3w** [comment]
@AdamWr You want to see what's better for pseudo-elements?

`#$#::before, ::after { display: none !important; }`

vs

`#$#::before, ::after { content: none !important; }`

**Comment by AdamWr** [comment]
>@AdamWr You want to see what's better for pseudo-elements?
`#$#::before, ::after { display: none !important; }`
vs
`#$#::before, ::after { content: none !important; }`

I'm not sure if I understand correctly the question, but I think that adding just `##::before, ::after ` should be enough.

I added `hdstreamvf.com#$#.TPlayer.on::after { display: none!important; }`, because there was a bug in filters compiler and rules like `##.TPlayer.on::after` was treated as invalid - https://github.com/AdguardTeam/FiltersCompiler/issues/33

**Comment by krystian3w** [comment]
`#$#::before, ::after { content: none !important; }` - Will it also be considered abnormal in the compiler?

I'm most concerned with the very old Firefox / Chrome `content: none` is compatible. 

And possibly, like the old app/addon, it considers the filter to be wrong/invalid.
