### ISSUE TITLE
Выбор загрузки файла

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#4704]
Не знаю куда написать, так что напишу сюда. У меня предложение по улучшению. Когда я захожу в настрйоки adguard, собственный фильтр и нажимаю выбрать файл с телефона. У меня очень маленький выбор загрузки файла (скрин 1), но почему-то на других сайтах, когда я гружу, то выбор больше - скрин 2. Я не могу загрузить правило, т.к. его просто не могу найти. Можете сделать выбор такой же, как на скрине 2?
https://ru.files.fm/u/yevheqbr
http://file.karelia.ru/zvkd47/

**Comment by Alex-302** [comment]
О предложениях нужно писать сюда:
https://github.com/AdguardTeam/AdguardForAndroid

**Comment by ministr91** [comment]
ну а как тебе предложение?

**Comment by Alex-302** [comment]
Я только по URL импортирую.
