### ISSUE TITLE
maniac.de/ - site with ads 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4705]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: maniac.de/ - site with ads 

Screenshot:
http://prnt.sc/eqskfl

***System configuration***

Application version: 1.1.5.65
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.13.21 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.20 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.19 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.11.24 Enabled=YES
ID=6 Name="German filter" Version=1.0.32.40 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.7.60 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.77 Enabled=YES
ID=101 Name="EasyList" Version=1.0.69.32 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.77.14 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.62.60 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.77.30 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES

Ticket ID(if exists): 1440449

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.
ID=101 Name="EasyList" Version=1.0.69.32 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.62.60 Enabled=YES
are unnecessary

try to disable
ID=118 Name="EasyPrivacy" Version=1.0.77.14 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.77.30 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
