### ISSUE TITLE
cheb.ru - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4707]
Screenshot:
<details>

![69e6a-clip-467kb](https://cloud.githubusercontent.com/assets/22892774/24559581/e79045ba-1647-11e7-8535-89463dcd5804.jpg)

</details>

***Steps to reproduce the problem***:

Go to https://cheb.ru/ website.

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS / Android / Linux
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1 2 3 4 5b 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1117882

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||sovch.ru/bg/*.gif?uid=
cheb.ru##noindex > iframe
cheb.ru##.rurek
||afisha.cheb.ru/css/bg/*.gif?id=
||afisha.cheb.ru/css/bg/*.gif?uid=*?id=

```
