### ISSUE TITLE
USBDev.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#47077]
Остатки от рекламы - рекламная учётка "USBDev.ru Forum".

<details><summary>Screenshot:</summary>

![2020 01 05-1](https://user-images.githubusercontent.com/17948007/71772357-ff98fd80-2f5a-11ea-8b55-f79bf45374b0.png)
</details>

[https://www.usbdev.ru/f/index.php?topic=2255](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.usbdev.ru/f/index.php?topic=2255)

`usbdev.ru##.windowbg:has(> .poster:contains("USBDev.ru Forum"))`

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.3.6
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by krystian3w** [comment]
@AdamWr a po co tu `"` w contains? uBO go nie wspiera.

**Comment by XX-J** [comment]
> Why the quotes in "contains"? uBO not support this.

<details><summary>Quotes are not necessary:</summary>

![2020 01 05-2](https://user-images.githubusercontent.com/17948007/71773525-87890280-2f6f-11ea-8d96-d8ae1fcebd11.png)
</details>
