### ISSUE TITLE
ChompSMS app - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4708]
Link to the application:
https://play.google.com/store/apps/details?id=com.p1.chompsms&hl=en

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screenshot_2017-03-29-19-47-28](https://cloud.githubusercontent.com/assets/22892774/24565645/c642f954-165e-11e7-815c-8e9f433d7dd9.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.53
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default mode)
Adguard filters: | 2, 3, 4, 14, 11 

[debug (16).txt](https://github.com/AdguardTeam/AdguardFilters/files/886675/debug.16.txt)

19:00 UK time

We were unable to reproduce the issue.

Ticket ID: 1531929

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/49
The same with Textra.
If user doesn't use MMS, he can enable filtering for this app in the apps settings(also he can block internet for this app by firewall).
