### ISSUE TITLE
[iOS PRO] Ads in WeatherUnderground app

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardFilters#4709]
User 1354945 reports ads in WeatherUnderground app, but ONLY when connected to University's wi-fi. Not at home, and not while using mobile.
Here is what it looks like:
<details>

![ads wu](https://cloud.githubusercontent.com/assets/26342177/24575740/21b1321c-16b7-11e7-91d7-61b3aaa0a2b9.png)

</details>

Tunnel logs and more screen shouts in ticket.
iOS 10.3 iPhone.

**Comment by Alex-302** [comment]
I can't find anything without time stamp.
What ad system on screenshot?
