### ISSUE TITLE
[DNS] skinny.co.nz/broadband - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4713]
skinny.co.nz/broadband - blocked by the DNS

skinny.co.nz/ - not blocked

See the screenshots below:

<details>

![file_000 1](https://cloud.githubusercontent.com/assets/15856304/24578449/28b4ef18-16e9-11e7-997a-77bfabb90c4a.png)

![file_000](https://cloud.githubusercontent.com/assets/15856304/24578443/22a9fe24-16e9-11e7-876d-a42f28f68562.png)

</details>

Reproduced in Adguard for iOS Pro with the Standard DNS protection.

ID: 1117961

**Comment by Alex-302** [comment]
Fixed
