### ISSUE TITLE
[NSFW] imgfile.net

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#47149]
**Site Sample** | 
----------------|
http://www.imgfile.net/dhrdk

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Chrome x64 (lastest)
AdGuard version:                       | **7.3 NIGHTLY** 
Protection Mode:						| **WFP Driver**
Stealth Mode:					       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

Leftovers, Popups after click.

<details><summary><b>Screenshot:</b></summary>

![20200105-1578248568-001](https://user-images.githubusercontent.com/9846948/71784184-d5921a80-2ff0-11ea-93b8-f2aa1608820c.png)

</details><br/>

@AdamWr @Alex-302

**Comment by AdamWr** [comment]
Fixed ad leftovers.
Popup is already blocked by AdGuard Popup Blocker and if popup blocker is disabled then it's blocked by scriptlet on my end.
