### ISSUE TITLE
https://torrentwiz3.com/ - Assistant is missing

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4714]
https://torrentwiz3.com/

![image](https://cloud.githubusercontent.com/assets/15856304/24578471/a515841e-16e9-11e7-8340-3f5906e59aa7.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS / Win
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 2 3 4 7 104 119 227

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1534025

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
I think it is not an issue of filters and it would be more appropriate if it is reported at https://github.com/AdguardTeam/AdguardAssistant/issues.

**Comment by Alex-302** [comment]
Agree. I can't reproduce it in Windows.
