### ISSUE TITLE
incorrect blocking https://tracker.0day.kiev.ua/browse.php

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4715]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: incorrect blocking https://tracker.0day.kiev.ua/browse.php
empty spaces instead of ads

this website requires the account to log in, login details could be taken from here (customerID  1093966) or in slack

Screenshot:

![image](https://cloud.githubusercontent.com/assets/25711093/24579760/ffabba78-1703-11e7-8836-ff22830d37e4.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | English, Russian, annoyance, spyware, social, mobile, experimental

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1093966

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
логин и пароль в тикете.

**Comment by Alex-302** [comment]
Странно. У меня пустоты в этих блоках схлопнуты, и верхнего не видно.
Для боковых добавил:
```
tracker.0day.kiev.ua##td[valign="top"] > table[style^="margin-bottom: 20px"][-ext-has=".titlemedium:contains(Полезное для тебя!)"]
tracker.0day.kiev.ua##td[valign="top"] > table[style^="margin-bottom: 20px"][-ext-has=".titlemedium:contains(Реклама)"]
```
для верхнего передай
```
tracker.0day.kiev.ua##ins[data-revive-zoneid]
```
