### ISSUE TITLE
lenta.ru switches to offline mode

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#47157]
***Description***:
* **Current behaviour**: 

Site goes to "offline mode" when HTTPS protection is enabled.

<details><summary>Screenshot:</summary>

![Screenshot_2020-01-01-12-50-55-325_com android browser](https://user-images.githubusercontent.com/33634917/71786119-d0dd5e80-3010-11ea-9e23-f1a6c3558aac.jpg)
</details><br/>

***Steps to reproduce the problem***:

1. Enable HTTPS filtering
2. Try to open the site

***System configuration***

**Filtering log**

[filteringlog_screenshots.zip](https://github.com/AdguardTeam/AdguardFilters/files/4024031/filteringlog_screenshots.zip)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | Android 9
Browser:                               | Mi Browser
AdGuard version:                       | 3.3.228
Filters enabled:                       | Base, Russian, Tracking Protection, Mobile ads
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | Default, DoH
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | 1683466

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@akmLaVx it seems something is wrong with settings - no requests from browser on screenshot.

**Comment by Alex-302** [comment]
Or this browser does not support https filtering. Cannot check on my device.
