### ISSUE TITLE
http://hdrezka.me Standalone app blocking the videos

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4716]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

When you go to any video on this website (for example http://hdrezka.me/series/fantasy/24202-ledyanaya-fantaziya.html#t:97-s:1-e:3 ) it won't load and will show only white screen (http://prntscr.com/er6dpm). It can be fixed when we add this site as an exception, but a lot of ads appear (http://prntscr.com/er6d4m)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.1.314.1628 
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | on
Adguard filters: | English, Russian, Spyware, Annoyances, Experimental

Ticket ID(if exists): 1315978

**Comment by Alex-302** [comment]
Fixed

**Comment by KozelElena** [comment]
The issue occurred again:

Opera : 44.0.2510.1449
AppVersion: 6.2.357.1887
Filters;

<details>

FilterId:1 Name: Russian filter Url: https://filters.adtidy.org/extension/chromium/filters/1.txt
FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt
FilterId:4 Name: Social media filter Url: https://filters.adtidy.org/extension/chromium/filters/4.txt
FilterId:14 Name: Annoyances filter Url: https://filters.adtidy.org/extension/chromium/filters/14.txt
FilterId:0 Name: User filter Url: no_url

</details>

Logs in the ticket by ID: 1497755

**Comment by Alex-302** [comment]
Не повторяется.
Выключение фильтров по одному что-то даёт?
