### ISSUE TITLE
Frellwit's Swedish Filter is blocking non-ad urls

### ISSUE THREAD

**Issue by dieselbanger** [AdguardTeam/AdguardFilters#47177]
**Incorrectly blocked domain:** woomio.com

My job heavily depends on a tool called Woomio. I see their domain is blocked in "Frellwit's Swedish Filter" ( ||woomio.com^$third-party ), which I don't understand as they're not showing ads at all. They have some Chrome Extensions though that we like to use, that now don't work with Ad Guard as they use 3rd party cookies.

Can we please allow the domain "woomio.com", as this makes no sense and hinders a lot of my colleagues too.

**Comment by lassekongo83** [comment]
Blocked because of tracking: `api.woomio.com/assets/js/analytics/co.js`. I'll make the rule more specific.

My lists doesn't only block ads, but also tracking, annoyances, and in some cases social widgets as well.

**Comment by dieselbanger** [comment]
Sounds good. I see the domain for extensions is actually **api.woomio.com**, so please allow the domain but exclude the tracking bit then.

Thanks!
