### ISSUE TITLE
proxad.net

### ISSUE THREAD

**Issue by rawoul** [AdguardTeam/AdguardFilters#47176]
**Incorrectly blocked domain:** proxad.net

The whole domain is blocked in AdguardFilters/master/SpywareFilter/sections/tracking_servers.txt. Proxad is the parent company of the French ISP "Free", and the proxad.net is used for many critical features like gateway and set-top boxes firmware updates. Please remove this rule. I am not sure why it was added 4 years ago, the commit does not mention the reason for this addition.

Reference: https://en.wikipedia.org/wiki/Proxad

**Comment by BlazDT** [comment]
Likely blocked due to reviews like these:
https://uk.trustpilot.com/review/proxad.net
https://www.prestashop.com/forums/topic/944809-proxadnet-freefr/

Was before my time, so maybe @Alex-302 can shed a bit of light into it.

**Comment by Alex-302** [comment]
Yep. This is hosting.
