### ISSUE TITLE
ios trackers

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#4717]
flurry.agentportal-*.yahoodns.net (flurry.com tracker)
dc.services.visualstudio.com (https://docs.microsoft.com/en-us/azure/application-insights/app-insights-ip-addresses)
amptrack-dailymail-co-uk.cdn.ampproject.org (source: https://is.gd/gq8S6a)
metrics-cbslocal-com.cdn.ampproject.org (source: https://is.gd/wH8mXS)

**Comment by jo2dan23** [comment]
also the below were added to MobileFilter/sections/specific_app.txt  which is a list that isnt in the dns filter template. so they arent being blocked.

||adserver.shadow.snapads.com^
||ads-chunks.prod.ihrhls.com^

**Comment by Alex-302** [comment]
added to mobile filter
```
||flurry.agentportal-*.yahoodns.net^
||amptrack-dailymail-co-uk.cdn.ampproject.org^
||metrics-cbslocal-com.cdn.ampproject.org^
```


> ||adserver.shadow.snapads.com^
> ||ads-chunks.prod.ihrhls.com^

They are will be blocked on iOS when DNS filtering is enabled.
