### ISSUE TITLE
cnbc.com - Incorrect blocking 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4718]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

The arrangment of elements after filtering is incorrect 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24583518/9f7724b0-1755-11e7-917b-ad2537f360ea.png)
![image](https://cloud.githubusercontent.com/assets/17320558/24583520/aa11184a-1755-11e7-8596-4dc73986c038.png)
![image](https://cloud.githubusercontent.com/assets/17320558/24583522/ad2d23ac-1755-11e7-8fc4-1637da11e873.png)

</details>

***Steps to reproduce the problem***:

https://www.cnbc.com/amp/2017/03/31/competing-with-amazon-is-crushing-retailers.html

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | User, English, Russian, Spyware, Social media

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1534408

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
cnbc.com##amp-embed[type="taboola"]
cnbc.com##.leaderboard_ad
```
Added to Social filter
```
cnbc.com###social_bar_top_gig_containerParent
cnbc.com###social-tools-panel_gig_containerParent

```
