### ISSUE TITLE
wp.pl/mini.html - site with ads 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4719]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: wp.pl/mini.html - site with ads 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot: http://prnt.sc/erjfvy

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

***System configuration***

Application version: 1.1.5.65
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.9.80 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.11.9 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.11 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.7.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.77 Enabled=YES
ID=117 Name="Adblock Polska" Version=1.0.0.52 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.77.14 Enabled=YES
ID=216 Name="Adblock polskie reguły" Version=1.0.6.77 Enabled=YES
ID=217 Name="Adblock polskie reguły cookies" Version=1.0.1.32 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES

Ticket ID(if exists): 1534612

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Tested on my desktop with $jsinject,content whitelisting and disabled extended css rules, but I couldn't reproduce.

**Comment by Alex-302** [comment]
try
```
wp.pl##a[href*=".wp.pl/"] > img[style*="width: 100%;"]
wp.pl##.MTkAx
```

**Comment by Wawrzyniec-Pruski** [comment]
It worked for a while, but now again not working...
