### ISSUE TITLE
20min.ch - broken by spyware filter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4721]
**Please note, that this is about iOS only**

User report:
> Lately I am having issues with many sites when I have the following filters activated:
> Spyware filter - Adguard
> Mobile Ads filter - Adguard
> Easyprivacy - Easylist

> For example on www.20min.ch half of the website (article) is not loading anymore.
> It is enough to have one of the mentioned filters activated and the page is broken.

**Comment by Alex-302** [comment]
It works fine on my side. Could you, please, ask for direct links and screenshots?
