### ISSUE TITLE
Word Cookies annoying notifications

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4722]
App link:
https://play.google.com/store/apps/details?id=com.bitmango.go.wordcookies&hl=en

**Comment by Alex-302** [comment]
It is impossible to block them by filtering.

**Comment by ameshkov** [comment]
Huh, are you sure they are not using any third-party push notification system?

**Comment by Alex-302** [comment]
Yes. I disabled wifi.
Btw, did you mean this?

<details>

![image](http://imagizer.imageshack.com/img923/9305/F463Zq.png)
</details>

**Comment by ameshkov** [comment]
I didn't mean the  pop-ups.

What I mean is that this app shows annoying notifications when you not use it for some time.

**Comment by Alex-302** [comment]
Got it.
