### ISSUE TITLE
pop-up banner http://law03.ru/finance/article/prodazha-kvartiry-bez-posrednikov

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4723]
***Description***:
pop-up banner http://law03.ru/finance/article/prodazha-kvartiry-bez-posrednikov
scroll down, then banner appears
Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/24589191/13652190-17df-11e7-9f27-0adf033e6f4e.png)
![image](https://cloud.githubusercontent.com/assets/25711093/24589205/4a3b76b0-17df-11e7-8aa4-f33fcf9d9873.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS / Android
Browser: | chrome
Adguard version: | 1.4.1/2.9.60
Adguard filters: | Russian, English, annoyance, social, spyware, mobile, experimental 

Ticket ID(if exists): 1534524

**Comment by Alex-302** [comment]
It is their own banner.
Added to Annoyances filter
```
law03.ru##.container > #blfix
```
