### ISSUE TITLE
notalwaysright.com 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4724]
https://forum.xda-developers.com/showpost.php?p=71700096&postcount=2286

> the "ez_aba_load" directory on the "notalways" sites needs to be blocked, it contains ads directing to some particularly unwanted material such as debunked anti-vaxxers propaganda and "shocking" clickbait stories.
> this directory is used exclusively to supply these ads, and is used on notalwaysright.com (https://notalwaysright.com/ez_aba_load/) and **its sister sites**.

https://notalwaysworking.com/
https://notalwaysromantic.com/
https://notalwaysrelated.com/
https://notalwayslearning.com/
https://notalwaysfriendly.com/
https://notalwayshopeless.com/

**Comment by Alex-302** [comment]
Blocked by EasyList rule `/ez_aba_load/*`

**Comment by Alex-302** [comment]
Leftover:
`notalwayshopeless.com,notalwaysfriendly.com,notalwayslearning.com,notalwaysrelated.com,notalwaysromantic.com,notalwaysworking.com###topbar_leaderboard`
