### ISSUE TITLE
cheezburger.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4725]
https://forum.xda-developers.com/showpost.php?p=71700096&postcount=2286

> cheezburger.com also needs to be checked, they have a particularly nasty auto-play video ad in the right sidebar on every page.
> I tried blocking it manually, but even if the video itself is blocked its audio will still somehow play automatically.
> I've only encountered this one on a pc though.

**Comment by Alex-302** [comment]
It should blocked by EasyList rule `/ez_aba_load/*`

**Comment by ameshkov** [comment]
I wonder why it is not blocked in his case?

**Comment by Alex-302** [comment]
Old filters? /ez_aba_load/* is fresh, added 1-2 days ago

**Comment by ameshkov** [comment]
Got it
