### ISSUE TITLE
https://aptekamos.ru/ - no Assistant, ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4726]
https://aptekamos.ru/apteka/?r=0

![image](https://cloud.githubusercontent.com/assets/15856304/24599676/f20c7662-1859-11e7-8c17-9132f17e07d0.png)

[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows NT 6.1.7601 Service Pack 1 
Browser: | FF
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Stealth mode options(Windows) | 
Adguard filters: | 2 3 5 6 10 14

Stealth Mode enabled: StealthModeSettings: {

-   "BlockThirdPartyCookies": false,
-   "BlockThirdPartyCookiesPeriodMin": 30,
-   "BlockFirstPartyCookies": false,
-   "BlockFirstPartyCookiesMin": 2880,
-   "DisableThirdPartyCache": false,
-   "BlockWebRtc": false,
-   "BlockBrowserPushApi": false,
-   "BlockBrowserLocationApi": true,
-   "RemoveXClientDataHeader": false,
-   "HideSearchQueries": false,
-   "SendDoNotTrackHeader": false,
-   "RemoveRefererFromThirdPartyRequests": false,
-   "HideUserAgent": false,
-   "CustomUserAgent": null,
-   "CustomReferer": null,
-   "HideIp": true,
-   "CustomIp": "209.141.53.254"
- 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1444608

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. Is it working without filters?
