### ISSUE TITLE
[NSFW] porndr.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#47285]
**Site Sample** | 
----------------|
https://www.porndr.com/videos/39162/teen-first-timer-eva-arse-creamed-on-the-audition-bed

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Chrome x64 (lastest)
AdGuard version:                       | **7.3 NIGHTLY** 
Protection Mode:						| **WFP Driver**
Stealth Mode:					       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

Leftovers, banner

<details><summary><b>Screenshot:</b></summary>

![20200108-1578460607-001](https://user-images.githubusercontent.com/9846948/71952328-945f5d80-31de-11ea-98dd-045fee915ff1.png)

</details><br/>

@AdamWr @Alex-302

**Comment by zloyden** [comment]
Not reproduced. @AdamWr please take a look.

**Comment by FadeMind** [comment]
@zloyden video from main report was deleted. 
New one random https://www.porndr.com/videos/39120/ambled-in-on-my-gf-working-out-unexperienced-chi-chick/

![20200117-1579267251-001](https://user-images.githubusercontent.com/9846948/72615259-976ff180-3934-11ea-9f61-ed93325548a6.png)

Only top banner is. Regards

**Comment by zloyden** [comment]
Added top banner, but other leftovers not reproduced.

**Comment by AdamWr** [comment]
I added one more rule to fix not working video.
