### ISSUE TITLE
Denmark - Shacks Adblock List

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4729]
> Any chance you could add this list? (Denmark - Shacks Adblock List) https://adblock.dk/block.csv
> It’s standard in uBlock Origin. I’ve tested the rules on Adguard on my Mac, and it works like it should. The syntax is standard.

ID 1535769

**Comment by ameshkov** [comment]
@Alex-302 don't we already have that filter?

**Comment by Alex-302** [comment]
We have it.
It is called `Schacks Adblock Plus liste` (original filter name)
![image](http://imagizer.imageshack.com/img924/9828/Na5EHI.png)
