### ISSUE TITLE
http://rustorka.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4730]
We have multiple complaints,

Проблема заключается в доступе к поиску на rustorka.com/ когда вводишь запрос в поиск, программа блокирует доступ и я не знаю как его добавить в фильтр, потому что все равно выскакивает ошибка.

![image](https://cloud.githubusercontent.com/assets/15856304/24644439/441f7d1a-191c-11e7-98a8-53d6b661e98b.png)

***System configuration***

Information | value
--- | ---
Operating system: | Microsoft Windows NT 10.0.14393.0
Browser: | 
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
Adguard DNS: | None
Stealth mode options(Windows) | 
Adguard filters: | 1 2

Stealth Mode enabled: StealthModeSettings: {

-   "BlockThirdPartyCookies": false,
-   "BlockThirdPartyCookiesPeriodMin": 30,
-   "BlockFirstPartyCookies": false,
-   "BlockFirstPartyCookiesMin": 2880,
-   "DisableThirdPartyCache": false,
-   "BlockWebRtc": false,
-   "BlockBrowserPushApi": false,
-   "BlockBrowserLocationApi": true,
-   "RemoveXClientDataHeader": true,
-   "HideSearchQueries": false,
-   "SendDoNotTrackHeader": false,
-   "RemoveRefererFromThirdPartyRequests": false,
-   "HideUserAgent": false,
-   "CustomUserAgent": null,
-   "CustomReferer": null,
-   "HideIp": false,
-   "CustomIp": "209.141.53.254"

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1536036, 1535760

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Rugesor** [comment]
Точно так же блокируются чат и вход в аккуант

**Comment by Alex-302** [comment]
После обновления русского фильтра починится.
