### ISSUE TITLE
ikea.com - incorrect blocking

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4731]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Adguard doesn't allow to use a credit card on ikea.com

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24643145/a74ef17a-1914-11e7-924a-44e47ecc2f42.png)
![image](https://cloud.githubusercontent.com/assets/17320558/24643150/b0939380-1914-11e7-9d16-5d499ff16c89.png)
![image](https://cloud.githubusercontent.com/assets/17320558/24643155/b898e22e-1914-11e7-8683-ba9ba8b368c7.png)
![image](https://cloud.githubusercontent.com/assets/17320558/24643164/bf4014ee-1914-11e7-9708-093d3c9a2bd1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) |  Off
Adguard filters:

<details>
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.0.97.71 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.8.18 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.13.56 Enabled=YES

ID=6 Name="German filter" Version=1.0.27.85 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.1.48 Enabled=YES

ID=107 Name="EasyList Germany" Version=1.0.60.42 Enabled=YES

</details>

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1534392

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't find this window. Try this rule:
```
@@||secure.ikea.com^
```

**Comment by Alex-302** [comment]
@KozelElena

**Comment by dzamyshlyayeva** [comment]
asked the user

**Comment by Alex-302** [comment]
@KozelElena @dzamyshlyayeva any news?

**Comment by dzamyshlyayeva** [comment]
unfortunately, nothing

**Comment by Alex-302** [comment]
ok
