### ISSUE TITLE
kissanime.ru - incorrect behaviour 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4732]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Whenever our user clicks play on the video it first opens a new tab on his safari and then he needs to close it first and click play in order to start watching videos.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24650298/687fd310-1932-11e7-8822-814bc3ae0ca8.png)
![image](https://cloud.githubusercontent.com/assets/17320558/24650315/7c1b48c8-1932-11e7-9185-9674c4743178.png)
![image](https://cloud.githubusercontent.com/assets/17320558/24650337/86e029fe-1932-11e7-8f29-44db5fef9b6b.png)

![image](http://somehosting.com/adg_on.jpg)
</details>

***Steps to reproduce the problem***:

 http://kissanime.ru/Anime/Fullmetal-Alchemist-Sub/Episode-011?id=19118

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |iOS
Browser: | Safari
Adguard version: |  1.1.5.65
Simplified filters(iOS) |  Off
Adguard filters: | User, English, Spyware, Social, Safari

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1535530

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||easylist.club/popunder5.js
@@||easylist.club/adlabs.js
||kissanime.ru/ads/
*/1121482/|$domain=kissanime.ru

```
