### ISSUE TITLE
Missed ads at f1total.com

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4733]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

User has ads at http://www.f1total.com/ (redirect to http://www.motorsport-total.com/)
on Windows and Android.
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24657507/2aa5a73c-194f-11e7-9749-9ca68aa751d7.png)

![image](https://cloud.githubusercontent.com/assets/26434103/24657628/a961d8d4-194f-11e7-9043-1abab94537fa.png)

![image](https://cloud.githubusercontent.com/assets/26434103/24657638/b4090834-194f-11e7-856b-ab0902b34f31.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Android 
Browser: | Firefox
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Adguard filters: | English, German, Dutch, Spyware, Annoyances, User

Stealth mode options(Windows)

<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24657859/98c60198-1950-11e7-8afe-0fe4f6a82e4f.png)

</details>

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1337070

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Also not reproduced.
Please ask for HAR file.

**Comment by OlegSUP** [comment]
Request sent

**Comment by KozelElena** [comment]
We've got a requested HAR file
Check it, please
Ticket ID: 1337070

**Comment by Alex-302** [comment]
@KozelElena  please check for updates. It should be fixed in German filter.
