### ISSUE TITLE
https://jadopado.com/ - assistant jumps to the top

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4734]
though it's set to show up in the right-hand bottom corner.

https://jadopado.com/en-bh/merhis-opulence-edp-unisex-perfume-100ml/p/JM00268551

+ any click opens assistant's settings

![image](https://cloud.githubusercontent.com/assets/15856304/24659418/4e8eaa26-1955-11e7-8553-e8c9565c7eb0.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chromw
Adguard version: | the current release verison
Adguard DNS: | No
Stealth mode options(Windows) | Off
Adguard filters: | Eng, Rus, social media, spyware, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is not related to filters. Write to https://github.com/AdguardTeam/AdguardAssistant/issues
