### ISSUE TITLE
skidrowgamesreloaded.com - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4735]
https://skidrowgamesreloaded.com/
https://skidrowgamesreloaded.com/mass-effect-andromeda-cpy/
1.4.1  rus en spyware annoyances social media
a lot of pop ups, new windows open

![screenshot 2017-04-04 18 55 37](https://cloud.githubusercontent.com/assets/23637588/24666202/50ddbf20-1968-11e7-8a8a-2f60b8986583.png)

![screenshot 2017-04-04 18 55 25](https://cloud.githubusercontent.com/assets/23637588/24666206/5446c936-1968-11e7-8e5e-35a18a025d6f.png)

**Comment by Alex-302** [comment]
Can't reproduce. Is  HTTPS filtering works on this site?

**Comment by zebrum** [comment]
@Alex-302 yep. TV session?

**Comment by Alex-302** [comment]
@zebrum yes

**Comment by Alex-302** [comment]
Added to English filter
```
skidrowgamesreloaded.com#%#Object.defineProperty(window, 'tQZr', { get: function() { return {}; } });
```
