### ISSUE TITLE
yts.ag - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4736]
https://yts.ag/
https://yts.ag/movie/how-to-marry-a-millionaire-1953
new tab opens
chrome browser extension 2.5.11
ru en social media spyware annoyances

![screenshot 2017-04-04 19 20 09](https://cloud.githubusercontent.com/assets/23637588/24667317/bd3e7a9e-196b-11e7-8f2a-ce0afbae8074.png)

**Comment by Alex-302** [comment]
Not reproduced. Is https filtering works on this site?

**Comment by zebrum** [comment]
yes it does @Alex-302

**Comment by Alex-302** [comment]
Can you reproduce?

**Comment by zebrum** [comment]
yep

**Comment by Alex-302** [comment]
So, I need remote access.

**Comment by Alex-302** [comment]
Added to English filter
```
yts.ag#%#window.atob = function() { };
```
