### ISSUE TITLE
JioTv app has unblocked ads

### ISSUE THREAD

**Issue by Ayan3199** [AdguardTeam/AdguardFilters#47376]
JioTv app has unblocked ads. Please download the app and see it yourself, cause screenshots can't be taken due to security restrictions

**Comment by Alex-302** [comment]
@Ayan3199 Cannot register. Jio number is required.

**Comment by Ayan3199** [comment]
Use my number 7003096043

Ayan

**Comment by Alex-302** [comment]
@Ayan3199 it seems code from SMS is required. Do you have Skype or Telegram?

**Comment by Ayan3199** [comment]
U can WhatsApp me or I may activate my telegram account or just call me on
duo

Ayan

**Comment by Ayan3199** [comment]
Ok try it again now

Ayan

**Comment by Alex-302** [comment]
> or I may activate my telegram account

It would be great:) Please write to https://t.me/Alex302

Also we have an official chat in Telegram https://t.me/adguard_en

**Comment by Alex-302** [comment]
Probably ad servers:
`||jioads.akamaized.net^`
`||ajdivotdelbloab24.jio.com^`
+ tracker
`||collect.media.jio.com^`

**Comment by Alex-302** [comment]
Hi. Any news? Do these rules change something?

**Comment by Ayan3199** [comment]
Yes ads are blocked and thanks for asking🙂🙂

Ayan

**Comment by Alex-302** [comment]
Ok, added.
