### ISSUE TITLE
rsload.net - no Assistant

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4737]
* **Current behaviour**: 

User says that after the recent update:
-No Assistant at https://rsload.net/ 
-Social Media filter doesn't work
User Filter is empty
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![1](https://cloud.githubusercontent.com/assets/22892774/24676598/4b8f9ee8-198c-11e7-9bd8-1a8235b916cc.png)

</details>

User installed 6.1.314.1628 - worked fine

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Firefox 52.0.2(64-бит)
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP 
Adguard filters: | 1,2,3,4,10,14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Windows and Adguard logs are here: 1419169

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Will be fixed in the next build
https://github.com/AdguardTeam/AdguardForWindows/issues/1643
