### ISSUE TITLE
http://www.pietsmiet.de/news/uploadplan - site with ads

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4738]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://www.pietsmiet.de/news/uploadplan - site with ads

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/esl4hd

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.1.5.65
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.9.93 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.73 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.39 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.10.22 Enabled=YES
ID=6 Name="German filter" Version=1.0.31.49 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.55 Enabled=YES
Ticket ID(if exists): 1535419

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced on my side.
Try to enable simplified filters.
