### ISSUE TITLE
Cell Connect app (AdChoices ads)

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4739]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

In Cell Connect application on Android in the bottom part of the screen, there are some Adchoice ads. 
A link to the app: https://play.google.com/store/apps/details?id=com.cmplay.cellconnect&hl=en
http://prntscr.com/esm1jt: 

***System configuration***

Information | value
--- | ---
Operating system: | Android
Adguard version: | 2.9
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default)
Adguard filters: | English, Russian, Spyware, Experimental, Annoyances, Mobile Ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1535093

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня блокируется.
Передай на проверку
```
||graph.facebook.com^$app=com.cmplay.cellconnect
```
