### ISSUE TITLE
Redundant/Obsolete rules

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#47398]
1. 

**Duplicate rule**

<details><summary>Screenshot:</summary>

![github com](https://user-images.githubusercontent.com/34379403/72227852-33ef6800-35b2-11ea-9421-b823cee39eea.png)

</details>

---
2.

**Duplicate rule**

<details><summary>Screenshot:</summary>

![screenshot-github com-2020 01 10-04_48_59](https://user-images.githubusercontent.com/34379403/72119186-8f2c1b00-3364-11ea-93b9-40373feaffcb.png)

</details>

---

3.

**Invalid and obsolete rule**
`||bahisşirketleri*.com/wp-content/html-tables/$third-party`

---

4.

**Duplicate domain [indirful.com]**
`indirful.com,fullindir.me,indirful.com##.code-block > p > strong > a[href][rel="nofollow noopener"]`

---

5.

**Obsolete rule**
`macizlemek`
https://github.com/AdguardTeam/AdguardFilters/blob/20e9c7f9a7382182919821ec7792f8aeb3f1a399/SocialFilter/sections/specific.txt#L3829

---
6.

**Not Tr site. Move to the Base or Spanish filter.**
`fakings.com`
<details><summary>Screenshot:</summary>

![screenshot-github com-2020 01 10-04_58_26](https://user-images.githubusercontent.com/34379403/72119578-f6969a80-3365-11ea-9c93-586c3263a50d.png)

</details>

---

7.

**Redundant rule.
There is a general rule in the Base filter.**
`musicpleer.cc###supp-ad1-player`

---
8.

**Empty line.**

https://github.com/AdguardTeam/AdguardFilters/blob/026c55e4068dad23a574432bc3805545c6a9b5a6/TurkishFilter/sections/specific.txt#L2882

<details><summary>Screenshot:</summary>

![empty](https://user-images.githubusercontent.com/34379403/72121095-0e245200-336b-11ea-9dc3-8a5f905b254f.png)

</details>

---

9.

**Wrong section.
Please move to the Social filter**

https://github.com/AdguardTeam/AdguardFilters/blob/20e9c7f9a7382182919821ec7792f8aeb3f1a399/TurkishFilter/sections/specific.txt#L3304

---

10.

**Redundant domain.**
Remove the `gunhaber.com.tr` because `.com.tr/banner/$domain=` is already blocking ads.

https://github.com/AdguardTeam/AdguardFilters/blob/20e9c7f9a7382182919821ec7792f8aeb3f1a399/TurkishFilter/sections/specific.txt#L3261

---

11.

**These are not Tr site. Move to the Base filter**
`rong-chang.com`
`findflac.com`

https://github.com/AdguardTeam/AdguardFilters/blob/20e9c7f9a7382182919821ec7792f8aeb3f1a399/TurkishFilter/sections/antiadblock.txt#L471
https://github.com/AdguardTeam/AdguardFilters/blob/20e9c7f9a7382182919821ec7792f8aeb3f1a399/TurkishFilter/sections/antiadblock.txt#L472

https://github.com/AdguardTeam/AdguardFilters/blob/0da978aa29ed4970cc43562f5f49219a68891581/TurkishFilter/sections/antiadblock.txt#L228

---

12.

**Please move to the Tr filter**
https://github.com/AdguardTeam/AdguardFilters/blob/7015126da95ebf65a80cdfd4a837d847b0f19a7a/EnglishFilter/sections/whitelist.txt#L3150

**Comment by Yuki2718** [comment]
**Redundant domain** 
In Simplified domain names filter,
`||b16.nakanohito.jp^`
`||bs.nakanohito.jp^`
`||cs.nakanohito.jp^`
`||uh.nakanohito.jp^`
`||c.nakanohito.jp^`
are covered by
`||nakanohito.jp^`

`||clicktrack2.ziyu.net^`
`||rranking5.ziyu.net^`
are covered by
`||ziyu.net^`

`||ad.jp.ap.valuecommerce.com^`
is covered by
`||valuecommerce.com^`

`||ad-emea.doubleclick.net/`
`||fls.doubleclick.net^`
`||ad.doubleclick.net^`
`||g.doubleclick.net^`
`||n4403ad.doubleclick.net^`
`||pagead46.l.doubleclick.net^`
`||partnerad.l.doubleclick.net^`
`||static.doubleclick.net^`
`||gan.doubleclick.net^`
`||iv.doubleclick.net^`
`||ad.de.doubleclick.net^`
`||stats.g.doubleclick.net^`
`||bid.g.doubleclick.net^`
`||cm.g.doubleclick.net^`
are covered by
`||doubleclick.net^`

**Comment by Alex-302** [comment]
@Yuki2718 this is not an issue. SDN Filter compiled from our and third-party sources.

**Comment by Yuki2718** [comment]
> 
> 
> @Yuki2718 this is not an issue. SDN Filter compiled from our and third-party sources.

Got it, thanks for clarification. Anyway it won't affect performance.
