### ISSUE TITLE
http://www.rds.ca/videos - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4740]
Incorrect blocking on page:
http://www.rds.ca/videos

It blocks ads but I can't click on a video to play. Works when Liste FR is disabled but it stops blocking ads then.

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) |  Off
Adguard DNS: |  Default
Adguard filters: | 2 3 4 10 16 101 118 113 207

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1533247

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. Try to disable all third-party filters and enable French filter(Liste FR + Adruard fixes)
