### ISSUE TITLE
seesaa.jp

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#47404]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

`||seesaa.jp` in Simplified domain names filter breaks all these seesaa.jp sites including subdomains such as blog.seesaa.jp

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![seesaa](https://user-images.githubusercontent.com/58900598/72130006-8adf1c80-33bb-11ea-8597-7a3bc89c0be1.png)

![seesaa2](https://user-images.githubusercontent.com/58900598/72130017-92062a80-33bb-11ea-9368-2302e79ac50f.png)

</details><br/>

* **Expected behaviour**: 
Remove the rule, instead you can add
`||sda.seesaa.jp^`
which will be found in all seesaa blogs such as http://news4wide.net/ and is ad script.

</details><br/>

***Steps to reproduce the problem***:

just go to https://seesaa.jp/ or https://blog.seesaa.jp/ with Simplified domain names filter enabled. If https filtering was turned off on system-wide blocking, you'll just get TLS error; otherwise the pages will be broken.

***System configuration***

**Filters:**

Simplified domain names filter

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #215](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/215) via [**ZenHub**](https://www.zenhub.com/)
