### ISSUE TITLE
 https://www.aqa.ru/forum incorrect blocking of images

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4741]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

On this website https://www.aqa.ru/forum/posovetuyte-medlennyiy-akvarium-297806-page1 adguard blocks photos and images. When Adguard is disabled photos are visible
http://prntscr.com/esnz3e Adguard is enabled
http://prntscr.com/esnznb Adguard disabled

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Opera, Chrome
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | on
Adguard filters: | English, Spyware, Experimental, Russian, Social media, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 638654

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.

**Comment by vmalyuta** [comment]
Photos are not visible again 
http://prnt.sc/f6iobf 
ticket id 638654

**Comment by Alex-302** [comment]
Fixed.

**Comment by vmalyuta** [comment]
https://prnt.sc/f948go
638654
проблема до сих пор актуальна

**Comment by Alex-302** [comment]
Не до сих пор, а уже.
Поправил.
