### ISSUE TITLE
Anti Ad-Blocker at divyabhaskar.co.in

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4742]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Reproduced on our side.

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-04-05 at 1 10 34 pm](https://cloud.githubusercontent.com/assets/26434103/24701404/00a0f144-1a03-11e7-83d7-0b84c5d4d662.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Go to divyabhaskar.co.in and open any article.

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
Adguard DNS: | None 
Adguard filters: | English, Social Media, Spyware, Annoyances, 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1536170

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
