### ISSUE TITLE
 New URL to block

### ISSUE THREAD

**Issue by aravindSRM-India** [AdguardTeam/AdguardFilters#47421]
New URL to block

URLs: 
lessonis.com www.lessonis.com vd.7vid.net www.vd.7vid.net hcg82f2b.com www.hcg82f2b.com
c.adsco.re tyjyrkcrv.com 41upk.bemobtrk.com www.tyjyrkcrv.com  www.c.adsco.re www.41upk.bemobtrk.com ehu96t2p.com www.ehu96t2p.com

Type of ads: js based push add. Shows ads wide range from spam tools to porn/ sex seeking websites.

**Comment by Alex-302** [comment]
@aravindSRM-India Hi. I need example sites with these ads.

**Comment by aravindSRM-India** [comment]
You can find 
1) lessonis.com 
2) hcg82f2b.com
3)  tyjyrkcrv.com
4) ehu96t2p.com
 are listed in https://easylist.to/easylist/easylist.txt

 41upk.bemobtrk.com and c.adsco.re new sub domain of parent bemobtrk.com and adsco.re respectively. Main domain already listed in easylist.to.

Its my mistake. Instead of reporting them, I keep on adding them in my hosts file to block. I hardly remember where I found them.

**Comment by Alex-302** [comment]
Easylist is a part of Base and Simplified Domain Names filters.
Better report sites with ads, instead of rules.
