### ISSUE TITLE
https://m.calcalist.co.il - incorrect blocking 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4743]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://m.calcalist.co.il/article.aspx?guid=3711009&ref=ynet - just a blank page 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-04-05 at 15 25 34](https://cloud.githubusercontent.com/assets/23372054/24705612/6287beee-1a15-11e7-9204-fc81d9d7c84c.png)

</details>

***System configuration***

Application version: 1.1.5.65
Device: iPhone
Platform: iOS
OS: 10.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.13.66 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.23 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.32 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.11.42 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.7.71 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.80 Enabled=YES
ID=101 Name="EasyList" Version=1.0.69.53 Enabled=YES
ID=108 Name="EasyList Hebrew" Version=1.0.4.49 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.77.61 Enabled=YES

Ticket ID: 1536776

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Please check this rule:
```
calcalist.co.il###siteOverlay
```
