### ISSUE TITLE
rewasd.com - download button is blocked

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4746]
http://www.rewasd.com/
press download button - blocked by spyware filter

![screenshot 2017-04-06 15 24 51](https://cloud.githubusercontent.com/assets/23637588/24754014/6694a4f2-1add-11e7-9a9a-56133ef38d75.png)

**Comment by Alex-302** [comment]
Not reproduced. Which filter breaks it?

**Comment by zebrum** [comment]
spyware in chrome extension 
in filtering log there is only one blocked request 

@@||google-analytics.com/analytics.js$domain=rewasd.com,third-party

**Comment by Alex-302** [comment]
Does this exclusion help?

**Comment by zebrum** [comment]
yes it does

**Comment by Alex-302** [comment]
ok 
Added to Spyware filter
```
@@||google-analytics.com/analytics.js$domain=rewasd.com
```
