### ISSUE TITLE
torrent-games.net - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4747]
http://torrent-games.net/
chrome extension
Adguard 1.4.1
en ru spyware social media annoyances

![screenshot 2017-04-06 17 49 36](https://cloud.githubusercontent.com/assets/23637588/24760461/6b1bc1b8-1af1-11e7-8e85-5540ce9e6933.png)

**Comment by Alex-302** [comment]
Fixed
