### ISSUE TITLE
Anti Adblocker at nl.hardware.info

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardFilters#4748]
Shortly after entering the site a yellow banner appears asking to disable adblocking software or to add the website to exception.

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-04-07 at 2 47 43 am](https://cloud.githubusercontent.com/assets/26342177/24780064/6216fd40-1b2c-11e7-9872-fe788aadbe9b.png)

</details>

Tested on Mac and Windows with same results. Latest builds and filters.

Originally reported by User 1492862

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
nl.hardware.info##.sitearea > div:not([class]):not([id])
```
