### ISSUE TITLE
batashkihan.com [Ads] [NSFW]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#47488]
**Site**: https://batashkihan.com/blowjob/2160.php

**Issue**: Seeing ads on the page at many places

**Screenshot**: https://prnt.sc/qm9047

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 79.0.3945.117 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 3.3.8	 `

**Filters**:
```
AdGuard Base Filter
AdGuard Tracking Protection Filter
AdGuard Social Media Filter
AdGuard Annoyances Filter
AdGuard Warning Removal List
AdGuard Mobile Ads filter
Peter Lowe's list
Malware Domains
Spam404
NoCoin Filter List

```

**Stealth Mode Settings**:

Stealth Mode: On
Self-destructing third-party cookies: Enabled (value set: 2880)
Self-destructing first-party cookies: Disabled
Miscellaneous Stealth Settings: All Enabled (Default)

**Comment by krystian3w** [comment]
`batashkihan.com##[href="https://batashkihan.com/sexdating.php"]`

then all that's left is the idea of cutting off the leftovers from those spams.
