### ISSUE TITLE
mp3leaks.org - Missed ads 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4749]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-04-07 at 3 12 25 am](https://cloud.githubusercontent.com/assets/17320558/24780428/e53219ae-1b3f-11e7-9f50-745d6b46d989.png)

</details>

***Steps to reproduce the problem***:

http://mp3leaks.org/pavel-dovgal-the-aura-2016-320-kbps/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Safari, Chrome
Adguard version: | 1.4.1
Adguard filters: | User, Russian, Spyware, Social media, English

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1518078

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
/wp-content/plugins/cm-pop-up-banners/$domain=mp3leaks.org
```
