### ISSUE TITLE
Can't send image through Viber if https is enabled

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4752]
***Description***:
Can't send image through Viber if https is enabled

***System configuration***

Information | value
--- | ---
Operating system: | Android
Android version: | 6.0.1
Adguard version: | 2.9.64
Device:| samsung SM-N910P
HTTPS filtering (Android): |  On 
Adguard filters: | 2, 3, 4, 1, 11 

Ticket ID(if exists): 713686

**Comment by Bohdan-SUP** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/1103
