### ISSUE TITLE
missed ads http://imgbase.ru/287/312005/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4753]
***Description***:
missed ads http://imgbase.ru/287/312005/
Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/24796054/23e06a6c-1b94-11e7-9080-7d7caea5fbe7.png)
***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | eng, rus, annoyance, social, spyware, mobile, experimental

Ticket ID(if exists): 1154909

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
