### ISSUE TITLE
unpioneer.com - Missed ads on the background using Extension

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4755]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Issue appears while using Adguard Extension on Yandex and Opera 36 browsers

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24800104/5334d7ae-1ba7-11e7-9d29-2afdd3de7ddc.png)

</details>

***Steps to reproduce the problem***:

 - Use Opera 36 or Yandex browser 
 - http://unionpeer.com 
 - see the baсkground ad

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Opera 36, Yandex
Adguard filters: | Английский фильтр, Фильтр счетчиков и системы аналитики, Фильтр виджетов социальных сетей, Русский фильтр

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1050245

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't access to this site.
Please check this rule:
```
|ws*://$domain=unpioneer.com
```
