### ISSUE TITLE
Flipboard app - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4757]
https://play.google.com/store/apps/details?id=flipboard.app&hl=en

Original report:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1155

**Comment by Alex-302** [comment]
@cadoan 
I don't see ads on my side.
Please try these rules:
```
||ue.flipboard.com/usage
||cdn.ampproject.org/v0/amp-analytics-0.1.js
||ad.flipboard.com/impression?impression_
||ad.flipboard.com/query?feed_id=
```
You may to cleare cache of this app before you check the rules.

**Comment by ameshkov** [comment]
@Alex-302 can't we simply block `ad.flipboard.com` completely?

**Comment by Alex-302** [comment]
Yes, we can. These rules just for test. I don't see ads here.
Added
```
||ad.flipboard.com^
```
