### ISSUE TITLE
uplod.ws - anti-adblock on Android

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4758]
Source report:
https://forum.xda-developers.com/showpost.php?p=71738254&postcount=2303
https://forum.xda-developers.com/showpost.php?p=71766031&postcount=2312

Page url:
https://uplod.ws/kifeu5v2tel0

Might be a false alarm, so please just do a quick check.

**Comment by seanl-adg** [comment]
This site has BlockAdBlock beta.
Filter contains $generichide exception rules which used to be working but since I don't understand how blockadblock works added a JS rule too.
