### ISSUE TITLE
Расписание СФУ - missed ads in the application

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4759]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Ads appear in the application "Расписание СФУ"

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24813006/106adeea-1bd5-11e7-94e1-110e6ac84cd2.png)
![image](https://cloud.githubusercontent.com/assets/17320558/24813012/144442f4-1bd5-11e7-8e2c-e0a27b5801ab.png)

</details>

***Steps to reproduce the problem***:

-  https://play.google.com/store/apps/details?id=ru.ikv.sfuschedule
- Wait for 3 seconds
- redirects to VK group 

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Adguard version: | 2.9
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On 
Adguard filters: | User, English, Russian, Spyware, Social media, Mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1489066

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||overall.ikvapp.ru/api/ad?api_key=
```
