### ISSUE TITLE
The VK app opens wrong tracks on Яндекс Музыка

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#47610]
***Description***:

[//]: # (Substitute this line with a description of the problem)

При включённом AdGuard Pro наблюдается баг:
1. Из приложения VK, по ссылке, нужно открыть аудиотрек в приложении Яндекс Музыка.
2. При нажатии на ссылку открывается страница во встроенном браузере VK, после нажатия на «Слушать в приложении» открывается приложение Яндекс Музыка, но не на нужном треке, который должен открыться по ссылке, а просто главная вкладка с плейлистами.
3. Если отключить DNS фильтрацию и повторить пункты 1 и 2, то уже откроется нужный трек, баг повторяется в 100% случаев.

***System configuration***

**Filters:**
AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Safari filter, AdGuard Russian filter

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | iOS 13.3
Browser:                               | n/a
AdGuard version:                       | 2.1.2.173
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | **Default**
Helpdesk ID (if exists):               | 1065648

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@Eugene-Savenko приложений VK более одного. Нужны ссылки на скачивание или точное название, как в аппсторе.

**Comment by Eugene-Savenko** [comment]
Пользователь не отвечает. Видимо, не актуально.
