### ISSUE TITLE
Another window pops up at https://kissanime.io

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4761]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Another webpage pops up when opening any topic. Reproduced in Safari iPad.

Screenshot:

<details>

![screen shot 2017-04-08 at 5 43 58 am](https://cloud.githubusercontent.com/assets/26434103/24824990/716dc308-1c1e-11e7-806c-cb99333d844f.png)

![screen shot 2017-04-08 at 5 38 38 am](https://cloud.githubusercontent.com/assets/26434103/24824998/81e2f262-1c1e-11e7-8ecd-e46aa6fe9b12.png)

</details>

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

***System configuration***

Information | value
--- | ---
Operating system: | iOS iPad
Browser: | Safari
Adguard version: | 1.1.5.40
Simplified filters(iOS) | Off
Adguard DNS: | None 
Adguard filters: | English, Spyware, Annoyances, Social media, Safari

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1538739

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
duplicate
https://github.com/AdguardTeam/AdguardFilters/issues/4762
