### ISSUE TITLE
https://kissanime.io/ - site with ads 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4762]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://kissanime.io/ - site with ads 
* **Current behaviour**: when you click on any button it redirects to another website 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/etv4nx
http://prnt.sc/etv53v
http://prnt.sc/etv50i

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

***System configuration***

Application version: 1.1.5.40
Optimazed enabled: NO
Uilters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.14 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.33 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.47 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.82 Enabled=YES
[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1538739

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Safari filter
```
||307cc283bab2ffdec92.com^
```

**Comment by deLumren** [comment]
@Alex-302 Problem still remains. Tested just now.

**Comment by Alex-302** [comment]
Please check this rule in private tab:
```
/([a-z0-9]).com\/([0-9]).*\//$domain=kissanime.io
```
