### ISSUE TITLE
http://megashara.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4763]
Ads are not blocked by the extension.

![image](https://cloud.githubusercontent.com/assets/15856304/24827446/7570ce6c-1c52-11e7-9fb7-adcdf7bbd610.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | Browser extension, the latest version
Adguard DNS: | None
Adguard filters: | Русский фильтр, Английский фильтр, RU AdList

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1076701

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
