### ISSUE TITLE
downdetector.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#47650]
**INCORRECT BLOCKING**

**Site Sample** | 
----------------|
https://downdetector.pl/status/orange/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Chrome x64 (lastest)
AdGuard version:                       | **7.3 NIGHTLY** 
Protection Mode:						| **WFP Driver**
Stealth Mode:					       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

Disqus Plugin is blocked. Should not be. 

<details><summary><b>Screenshot:</b></summary>

WITH ENABLED ADG

![20200113-1578934350-001](https://user-images.githubusercontent.com/9846948/72275243-d26cdf00-362d-11ea-8c44-229a2ce5e519.png)

DISABLED ADG

![20200113-1578934382-001](https://user-images.githubusercontent.com/9846948/72275244-d3057580-362d-11ea-8ca4-650586589ee2.png)

</details><br/>

@AdamWr @Alex-302

**Comment by AdamWr** [comment]
Z tego co widzę, to ten problem powoduje `Fanboy's Cookiemonster`.
Dodaj proszę tę regułę do filtrów użytkownika, to powinno rozwiązać problem:
`@@||cdn.ziffstatic.com/*/zdconsent.js$domain=downdetector.pl`

**Comment by FadeMind** [comment]
@AdamWr zgłosisz proszę do Fanboya? Czy dodasz tutaj? :> 
Dziękuję, Działa. 
![20200113-1578935208-001](https://user-images.githubusercontent.com/9846948/72276166-9dfa2280-362f-11ea-88fd-1f0d1caf12de.png)

**Comment by krystian3w** [comment]
Zgłoszę na EasyList, może Khrin naprawi szybciej - bo Fanboy ma 30 zgłoszeń (social / cookies / annoyance) i naprawia ~1 na dzień.

PR też się nie opłaca im robić - bo można dodać w złym pliku i zamknął jako Invalid.

**Comment by FadeMind** [comment]
@krystian3w  dzięki ❤️
