### ISSUE TITLE
http://m.tmz.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4765]
http://m.tmz.com/#news/

![file_000 2](https://cloud.githubusercontent.com/assets/15856304/24828207/1111d1fa-1c61-11e7-830e-83fcfffa70b7.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.40
Simplified filters(iOS) |  Off
Adguard DNS: | Default 
Adguard filters: | 2, 3, 4, 12

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1538932

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Try to add to DNS whitelist:
```
bkrtx.com
or
@@||bkrtx.com^
```
I don't remember how it works in release verison, I am using beta version.

**Comment by Alex-302** [comment]
@evgeniy-ADG
