### ISSUE TITLE
http://www.rbc.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4766]
http://www.rbc.ru/

Redirects to the 'blocked by the content blocker' page when you click on the first entry on the list of news.

1. Open the site and click here:

![image](https://cloud.githubusercontent.com/assets/15856304/24828577/a190fae2-1c68-11e7-974c-c7d6c13477e2.png)

2. See this:

![image](https://cloud.githubusercontent.com/assets/15856304/24828578/a7e3d95a-1c68-11e7-9d70-9a129c9c9098.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) |Off
Adguard DNS: | None
Adguard filters: | 1 2 3 4 11 12 14 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1236012

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Поправил и убрал пару баннеров.

**Comment by OlegSUP** [comment]
Проблема все еще сохранилась. 

Пользователь прислал логи, время 20:41
[Archive.zip](https://github.com/AdguardTeam/AdguardFilters/files/923417/Archive.zip)

**Comment by Alex-302** [comment]
Не `ещё`, а `уже`. Неделя ж прошла.

**Comment by Alex-302** [comment]
Повторить не удаётся. Мобильный фильтр скрывает.

**Comment by zebrum** [comment]
@Alex-302 у меня повторяется

**Comment by KozelElena** [comment]
Пользователь отписал, что проблема та же.

**Comment by Alex-302** [comment]
С фильтрацией по DNS проблему не убрать, т.к. они используют домен an.yandex.ru как счётчик. Если разблокировать - будет реклама. Пользователь сам может в белый список добавить.
