### ISSUE TITLE
animmex.tv blockadblock

### ISSUE THREAD

**Issue by ghajini** [AdguardTeam/AdguardFilters#4767]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # antiadblock

Screenshot:

`http://prntscr.com/etynej`

***Steps to reproduce the problem***:
go here

`https://www.animmex.tv/video/40920/prison-break-s05e01-ogygia`
you will get blockadblock

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10
Browser: | chrome 59
Adguard version: | 2.5.11 
english filter: | 1.1.14.1
spyware filter: | 1.0.11.33

Note= you need to try VPN if your ISP is blocking animmex.TV functions

Any idea @ameshkov  when its going to solve.....

**Comment by Alex-302** [comment]
Fixed
