### ISSUE TITLE
facebook.com - a lot of missed ads 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4768]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

We have a complain about facebook "Create ad" content from our customer.

- He has no rules in the User filter
- There are no SSL exceptions
- Clearing browser's cache and all the cookie didn't help
- Disabling browser extensions didn't help
- He has only standard filters enabled
- The issue persists in several browsers
- WFP driver is enabled

- We have all the logs needed

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24830011/db3e7090-1c85-11e7-9a9d-67a1ecce0741.png)

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | IE, MS Edge, Chrome
Adguard version: | 6.1.314
Adguard driver (Windows): | WFP 
Adguard filters: | English, Spyware, Social, Annoyances, Experimental, Mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1524207

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by vozersky** [comment]
confirmed

**Comment by bigdargon** [comment]
confirmed

**Comment by Alex-302** [comment]
Added to English filter
```
facebook.com##.home_right_column > div#pagelet_ego_pane[-ext-has='div.ego_unit_container > div.ego_unit > div > div > div > div.uiToggle.wrap > a[ajaxify*="&eid="]']
```
