### ISSUE TITLE
app.scottscheapflights.com is not working

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#47694]
***Description***:
* **Current behaviour**: 

Throws an ERR_EMPTY_RESPONSE upon attempting to open the URL.

<details><summary>Network log:</summary>

![image](https://user-images.githubusercontent.com/33634917/72304450-3d8fd300-3679-11ea-92b4-fecd20e26eef.png)

</details><br/>

* **Expected behaviour**: 

Site should open just fine.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/33634917/72304516-631cdc80-3679-11ea-91bd-8b3ad9dbed08.png)

</details>

***Steps to reproduce the problem***:

Just open the site w/protection enabled.

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | Ver 2004 Build 19041.1
Browser:                               | Chrome 80
AdGuard version:                       | 7.3n23
Filters enabled:                       | Base, Russian, Mobile ads, Annoyances, Adblock Warning Removal List
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | 2491837

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/CoreLibs #1238](https://github.com/AdguardTeam/CoreLibs/issues/1238) via [**ZenHub**](https://www.zenhub.com/)
