### ISSUE TITLE
www.stern.de - Incorrect Blocking

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#4769]
![](http://i.imgur.com/wAm7GAT.png)
http://www.stern.de

Sidebar cannot clickable

Blame Rules:
```
||google-analytics.com/cx/api.js
||google-analytics.com/cx/api.js$third-party
```

**Adguard version**: 6.2.346.1819

**Operating system**: Windows 10

**Browser**: Vivaldi

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||google-analytics.com/cx/api.js$domain=stern.de
```
