### ISSUE TITLE
http://www.mmo-champion.com/content/ - site with ads

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4770]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://www.mmo-champion.com/content/ - site with ads

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/eubddd

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

pplication version: 1.1.5.40
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.9.61 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.10.73 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.17.33 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.51 Enabled=YES

Ticket ID(if exists): 1539491

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
mmo-champion.com##div[style="text-align:center;margin-left:auto;margin-right:auto;width:900px;margin-bottom:10px;"]
```
