### ISSUE TITLE
Adguard blocks UI elements for sharing in nextcloud

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdguardFilters#47710]
@tiiiecherle commented on [Fri Jan 03 2020](https://github.com/AdguardTeam/AdGuardForSafari/issues/306)

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest stable version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.5.4
* Environment name and version: 13.0.4
* Operating System: macOS 10.15.2
* Nextcloud Version: 17.0.2

### Behavior
When enabling "Widgets for social networks" extension it blocks the plus "+" in nextcloud which is needed for creating shared links and an essential feature. I attached two screenshots (one with and one without "Widgets for social networks" active) and marked the place with a red circle.

The same problem also exists on Adguard for Firefox. So perhaps it is a rule issue. Feel free to move the issue to the correct place inside the Adguard GitHub development.

There seems to be a few [issues about it](https://github.com/nextcloud/server/issues/16337) in nextcloud but as I understand correctly they can't do much about it and want the users to report it to the adblockers to fix it. That's what I'm doing right now ;)

Thanks for looking into it. Kind regards.

### Screenshots
![Bildschirmfoto 2020-01-03 um 08 46 22](https://user-images.githubusercontent.com/7059936/71713025-2a267180-2e08-11ea-8b90-cc48d2d599a8.jpg)
![Bildschirmfoto 2020-01-03 um 08 47 06](https://user-images.githubusercontent.com/7059936/71713026-2a267180-2e08-11ea-8d9e-3d0e6a45acb6.jpg)

**Comment by Alex-302** [comment]
@tiiiecherle Hi. Sorry for the late reply. Could you, please, open filtering log, reproduce an issue and make screenshot of blocked items?

**Comment by tiiiecherle** [comment]
Hey, thanks for the reply. We just checked with updated filters with Adguard for Safari in Versions 1.5.3 and 1.6.3. Both seem to work fine now. When I submitted the report I also updated the filter lists and it was not working. If no other user has the issue, it can be closed.

Thanks a lot for Adguard. It's really good and improves for Safari with each version ;)
