### ISSUE TITLE
http://adf.ly/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4772]
http://adf.ly/1kFhoI

What should happen on the page is to hide the ad on the adfly page with a skip ad button, but it instead leads to this screenshot with no option to go to the designated webpage. This doesn't occur with adguard disabled for this domain.

Adguard enabled:

![img_0486](https://cloud.githubusercontent.com/assets/15856304/24848244/8931f03e-1dce-11e7-8f26-0d7323683ee0.PNG)

Adguard disabled:

![img_0488](https://cloud.githubusercontent.com/assets/15856304/24848252/8eb1caca-1dce-11e7-861c-eb2a306e996d.PNG)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.1.5.65

Simplified filters(iOS) | Off
Adguard DNS: | None / Default / Family Protection
Stealth mode options(Windows) | 
Adguard filters: | 2 3 4 11 12 14 15

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1497117

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||static.adf.ly/static/css/$domain=adf.ly
@@||static.adf.ly/static/js/$domain=adf.ly
```
