### ISSUE TITLE
m.duanwenxue.com - Missed ads

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4773]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Missed ads using iOS Safari and incorrect rendering using Chrome. 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24850761/f246f56e-1dd9-11e7-9db8-c45db5842e07.png)

![image](https://cloud.githubusercontent.com/assets/17320558/24850818/2ffc9256-1dda-11e7-81d3-d9419e1476b3.png)

</details>

***Steps to reproduce the problem***:

http://m.duanwenxue.com/jingdianyulu/233431.html

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS/iOS
Browser: | Chrome/Safari
Adguard version: | 1.4.1/9.3.1
Simplified filters(iOS) | On 
Adguard filters: |User filter, English filter, Spyware filter, Social media filter, Annoyances, Russian/ User filter, English filter, Spyware filter, Social media filter, Mobile Ads filter, Safari filter, Simplified domain names filter, EasyList, EasyList China

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1539909

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||pstatp.com/site/reads-sdk*/*.js
||duanwenxue.com/js/tongji.js
||partner.toutiao.com/partner_recommend/*&url=http%3A%2F%2Fm.duanwenxue.com

```
