### ISSUE TITLE
zobacz.ws

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#47735]
**Site Sample** | 
----------------|
http://zobacz.ws/informacyjne

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Chrome x64 (lastest)
AdGuard version:                       | **7.3 NIGHTLY** 
Protection Mode:						| **WFP Driver**
Stealth Mode:					       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

Adblock

<details><summary><b>Screenshot:</b></summary>

![20200114-1579021253-001](https://user-images.githubusercontent.com/9846948/72365105-e4b34f80-36f7-11ea-9788-5412fcaeb3b0.png)

</details><br/>

@AdamWr @Alex-302

**Comment by AdamWr** [comment]
Naprawione.
