### ISSUE TITLE
"Хибины.com", "обьявления из рук в руки" 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4774]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Notifications "Server error" and "No response" when Adguard is on.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

***Steps to reproduce the problem***:

https://play.google.com/store/apps/details?id=com.umojo.irr.android&hl=en
https://play.google.com/store/apps/details?id=com.arvifox.hibiny&hl=en

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | 2, 3, 4, 14, 1, 6, 11

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1514111

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
> https://play.google.com/store/apps/details?id=com.arvifox.hibiny&hl=en
Похоже на баг. Фильтрами не исправить. Нужно в репозиторий Android писать.

> https://play.google.com/store/apps/details?id=com.umojo.irr.android&hl=en
поправил:
```
@@||irr.ru/mobile_api^$app=com.umojo.irr.android
```

**Comment by Alex-302** [comment]
Created new issue:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1164
