### ISSUE TITLE
moddb.com - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4775]
http://www.moddb.com/
adg 1.4.1 en rus annoyances social media spyware

![screenshot 2017-04-10 19 10 34](https://cloud.githubusercontent.com/assets/23637588/24871206/89ac0d9e-1e21-11e7-9422-1d7b7ea8d680.png)

**Comment by Alex-302** [comment]
Can't reproduce
http://imagizer.imageshack.com/img924/4435/iek6C6.png

**Comment by zebrum** [comment]
It looks fine now
