### ISSUE TITLE
http://regionalwolfsburg.de - missed ad on page 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4777]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://regionalwolfsburg.de/vfl-wald-spieler-und-fans-griffen-gemeinsam-zum-spaten/ - missed ad on page 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/24873689/7df9145c-1e2a-11e7-9761-4fddd9fcb2a6.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.1.5.40

Device: iPhone
Platform: iOS
OS: 10.3.1

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.14.5 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.34 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.47 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.11.64 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.49.50 Enabled=YES
ID=6 Name="German filter" Version=1.0.32.72 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.7.90 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.84 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.26 Enabled=NO

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID 1540118

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to German filter
```
regionalwolfsburg.de##.logocontainer > div.mobcenter
regionalwolfsburg.de###platzierung
```
Added to Social filter
```
~pinterest.com##a[href^="https://www.pinterest.com/pin/create/link/"]
```
