### ISSUE TITLE
Transform unicode domain names to punycode on filters compilation

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4778]
We currently do these transformations in the programs code. I guess it'd be easier for devs if these transformations were done on the server side.

**Comment by Alex-302** [comment]
Can we add unicode domains to the filters?

**Comment by ameshkov** [comment]
> Can we add unicode domains to the filters?

Yep, what I want to be done is automatically transform them to punycode on the server side.

**Comment by Alex-302** [comment]
ok, got it.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersCompiler #6](https://github.com/AdguardTeam/FiltersCompiler/issues/6) via [**ZenHub**](https://www.zenhub.com/)
