### ISSUE TITLE
http://www.gocomics.com/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4779]
http://www.gocomics.com/

![image](https://cloud.githubusercontent.com/assets/15856304/24898618/334adf9a-1ea6-11e7-9cbf-4d74ce294367.png)

***System configuration***

Information | value
--- | ---
Operating system: | Microsoft Windows NT 10.0.14393.0
Browser: | Chrome, FF
Adguard version: | : 6.1.331.1732
Adguard driver (Windows): | WFP
Adguard DNS: | None
Stealth mode options(Windows) | off
Adguard filters: | 2 3 4 10

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1540315

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Strange. I can't reproduce it after the first visit even in provate tab.
