### ISSUE TITLE
Anti Adblock blocks HD at http://www.1tv.ru/live

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4782]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Open http://www.1tv.ru/live and try changing resolution to HD when Adguard is on.

Reproduced on our side.

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-04-11 at 4 41 48 pm](https://cloud.githubusercontent.com/assets/26434103/24912250/43ed5672-1ed6-11e7-8a50-4f774a60d44e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | English, Russian, Spyware, Social media, Annoyances, User

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1540383

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce even with Safari extension.

**Comment by OlegSUP** [comment]
I can't reproduce it today on another PC. Will ask the user if this issue still persists.

**Comment by vmalyuta** [comment]
проблема актуальна
одна вещь, которая открывается без рекламы и в хорошем качестве - новости

**Comment by Alex-302** [comment]
> одна вещь, которая открывается без рекламы и в хорошем качестве - новости

там же прямой эфир. У меня по прежнему нормально
http://imagizer.imageshack.com/img923/2787/xR5em6.png

**Comment by KozelElena** [comment]
Проблема повторяется еще в одном случае (прямой эфир):
Ticket ID: 1577515

<details>

![image](https://user-images.githubusercontent.com/17320558/27374223-bd135018-5673-11e7-9598-afbbf26a9bf5.png)

</details>

**Comment by Alex-302** [comment]
Не повторяется. Вероятно проблема в стороннем блокировщике или фильтре.

**Comment by ghajini** [comment]
still reproduced when using russian adguard list

**Comment by altokarev** [comment]
Can't rep.

**Comment by Alex-302** [comment]
Maybe they are using geolocation. Where are you?
