### ISSUE TITLE
Missed ad at http://freerutor.org/

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#4784]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behavior**:  Ad appears in right part of the website

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/27292111/24916671/7b182ebc-1ee3-11e7-9f00-03f22d2f77b3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac
Browser: | Chrome
Adguard version: | 6.1.331 / 1.4.1
Adguard driver (Windows): | WFP
Adguard DNS: | None
Stealth mode options(Windows) | disabled

Adguard screenshot:
![screen shot 2017-04-11 at 6 49 56 pm](https://cloud.githubusercontent.com/assets/27292111/24918057/ae1aac8c-1ee7-11e7-86cd-086d6fbe2f27.png)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1540796

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
