### ISSUE TITLE
Incorrect blocking and missed ad at http://www.mmnews.de/

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4785]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

http://www.mmnews.de/index.php/politik/108202-co2-sekten33

Also user complains about the text ad:
>> Klicken Sie jetzt einfach HIER und erfahren Sie, wie es wirklich um Ihre Rente steht!

Reproduced in Safari iPhone.

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/24921496/b4e1e3bc-1ef3-11e7-9518-e42d49fc0306.png)

![screen shot 2017-04-11 at 8 11 43 pm](https://cloud.githubusercontent.com/assets/26434103/24921508/bc7647e4-1ef3-11e7-817f-9b96aae1c549.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |iOS
Browser: | Safari
Adguard version: | Application version: 1.1.5.40
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | English, German, Spyware, Annoyances, Social Media, Safari

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1406275

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to German filter
```
mmnews.de##div[class^="plista_widget_"]
mmnews.de##a[href^="http://www.watergate.tv/lps/"]
mmnews.de###banner > div
```
Popup is not reproduced.
