### ISSUE TITLE
Ads in "Tech News" app for Android on Beta 2.9.64

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardFilters#4786]
PlayMarket page:
https://play.google.com/store/apps/details?id=it.pinenuts.technews

Issue only occurs on beta version.
On live the ad banner is greyed out.
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![tecnnewsad](https://cloud.githubusercontent.com/assets/26342177/24935957/3d851e16-1f2e-11e7-88ed-dddc276697ee.jpg)

</details>

Settings and filters are ok.

Ticket ID(if exists): 1063185

**Comment by Alex-302** [comment]
Not reproduced. I see only empty placeholder(builtin)
Please ask for HTTP requests log.

**Comment by Alex-302** [comment]
@seanl-adg Please check in on your device.

**Comment by seanl-adg** [comment]
Not reproduced on my end too.
