### ISSUE TITLE
Columbia Ads

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardFilters#4787]
Server-side rendered ads with randomized class names.

Reported forum threads:
https://forum.adguard.com/index.php?threads/adageindia-in-missed-ads-windows.20841/
https://forum.adguard.com/index.php?threads/businessinsider-in-missed-ads-windows.19295/#post-125544
https://forum.adguard.com/index.php?threads/mensxp-com-missed-ads-windows.19296/
https://forum.adguard.com/index.php?threads/lifehacker-co-in-missed-ads-windows.19297/#post-125419
https://forum.adguard.com/index.php?threads/colombia-ads-missed-ads-windows.19238/
https://forum.adguard.com/index.php?threads/iamgujarat-com-missed-ads-windows.20826/
https://forum.adguard.com/index.php?threads/bombaytimes-com-missed-ads-windows.20842/
https://forum.adguard.com/index.php?threads/resolved-gizmodo-in-missed-ads-windows.19891/

Websites using it:
```
adageindia.in
bombaytimes.com
businessinsider.in
gizmodo.in
iamgujarat.com
in.techradar.com
lifehacker.co.in
mensxp.com
```

**Comment by gotitbro** [comment]
Other Websites:
https://forum.adguard.com/index.php?threads/resolved-colombia-ads-missed-ads-windows.19238/
https://forum.adguard.com/index.php?threads/resolved-economictimes-indiatimes-com-missed-ads-windows.19294/
https://forum.adguard.com/index.php?threads/resolved-navbharattimes-indiatimes-com-missed-ads-windows.19886/
https://forum.adguard.com/index.php?threads/resolved-eisamay-indiatimes-com-missed-ads-windows.19885/
https://forum.adguard.com/index.php?threads/resolved-maharashtratimes-indiatimes-com-missed-ads-windows.19888/
https://forum.adguard.com/index.php?threads/resolved-vijaykarnataka-indiatimes-com-missed-ads-windows.19889/
https://forum.adguard.com/index.php?threads/resolved-malayalam-samayam-com-missed-ads-windows.19894/
https://forum.adguard.com/index.php?threads/resolved-telugu-samayam-com-missed-ads-windows.19893/
https://forum.adguard.com/index.php?threads/resolved-tamil-samayam-com-missed-ads-windows.19892/

Websites:
```
timesofindia.indiatimes.com
economictimes.indiatimes.com
navbharattimes.indiatimes.com
eisamay.indiatimes.com
maharashtratimes.indiatimes.com
vijaykarnataka.indiatimes.com
malayalam.samayam.com
telugu.samayam.com
tamil.samayam.com
idiva.com
```

**Comment by seanl-adg** [comment]
https://forum.adguard.com/index.php?threads/resolved-m-timesofindia-com-missed-ads-ios.20287/#post-139881
```
m.timesofindia.com
```

**Comment by gotitbro** [comment]
@seanl-adg They seems t have changed something on their websites. the proposed solution is not working anymore:
`##style[type="text/css"] + div[class]:not([id]):not([style]):not([class*=" "])`

Please see what can be done about this.

**Comment by seanl-adg** [comment]
They placed some empty elements with `display:none` elements between `style` element and the `div` containing ads, apparently to evade our previous element hiding rules.
 so the previous rule is not working.
Added a JS rule, it is an ad hoc method, but it will be efficient than using extended selectors in this case.
