### ISSUE TITLE
https://www.ivi.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4788]
https://www.ivi.ru/watch/pepel/117590

Reproduced with Rusian IP.

![img-2017-04-11-23-21-04](https://cloud.githubusercontent.com/assets/15856304/24946382/6330a21a-1f6b-11e7-8575-652a72320981.png)
![img-2017-04-11-23-19-16](https://cloud.githubusercontent.com/assets/15856304/24946383/6399670a-1f6b-11e7-97b8-3303f290c811.png)

***System configuration***

Information | value
--- | ---
Operating system: | Microsoft Windows NT 10.0.15063.0
Browser: | Chrome
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
Adguard DNS: | Default 
Stealth mode options(Windows) | 1 2 3 4 14
Adguard filters: | below

Stealth Mode enabled: StealthModeSettings: {

-   "BlockThirdPartyCookies": true,
-   "BlockThirdPartyCookiesPeriodMin": 30,
-   "BlockFirstPartyCookies": false,
-   "BlockFirstPartyCookiesMin": 2880,
-   "DisableThirdPartyCache": true,
-   "BlockWebRtc": true,
-   "BlockBrowserPushApi": false,
-   "BlockBrowserLocationApi": true,
-   "RemoveXClientDataHeader": true,
-   "HideSearchQueries": true,
-   "SendDoNotTrackHeader": true,
-   "RemoveRefererFromThirdPartyRequests": true,
-   "HideUserAgent": false,
-   "CustomUserAgent": null,
-   "CustomReferer": null,
-   "HideIp": true,
-   "CustomIp": ""

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1341996

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
