### ISSUE TITLE
Nplayer Free - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4790]
https://itunes.apple.com/ru/app/nplayer-free-the-best-media-player/id1078835991?mt=8

![image1](https://cloud.githubusercontent.com/assets/15856304/24952086/2753f422-1f7f-11e7-9088-b450dd374a8d.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | 
Adguard version: | 1.1.5.40
Adguard DNS: | Default
Adguard filters: | 2 3 4 12 14 15 104

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Logs: 1539924

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Is it Google ad? I can't reproduce.
