### ISSUE TITLE
get-phone.info - missed ads 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4791]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Missed ads on get-phone.info
[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24958338/a6e75da6-1f97-11e7-93c5-55ef9014cfbd.png)

</details>

***Steps to reproduce the problem***:

http://get-phone.info/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS/ iOS
Browser: | Chrome/ Safari
Adguard version: | 1.4.1/ 10.3
Simplified filters(iOS) | Off
Adguard filters: | User, English, Spyware, Social media, Annoyances, Russian / User filter, English filter, Spyware filter, Social media filter, Annoyances filter, Russian filter, Mobile Ads filter, Safari filter

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1518078

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
