### ISSUE TITLE
polityczek.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#47913]
**Site Sample** | 
----------------|
http://polityczek.pl/uncategorised/12313-kto-te-straszne-dziwadla-do-europy-wpuscil-lis-o-europoslach-pis-u

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Chrome x64 (lastest)
AdGuard version:                       | **7.3 NIGHTLY** 
Protection Mode:						| **WFP Driver**
Stealth Mode:					       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

FB leftover
```
polityczek.pl###likeFB
```

<details><summary><b>Screenshot:</b></summary>

![20200116-1579172043-001](https://user-images.githubusercontent.com/9846948/72519136-0ecf5380-3857-11ea-8e40-405d5f4cc3d3.png)

</details><br/>

@AdamWr @Alex-302

**Comment by AdamWr** [comment]
Dodane, dziękuję.
