### ISSUE TITLE
https://love.ua/ ads

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4792]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)
When you follow the link https://love.ua/ you may find a lot of banners and ads there.
See screenshot below:
http://prntscr.com/evlku0
***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome, Opera
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | on
Adguard filters: | English filter, Spyware filter, Social media filter, Experimental filter, Annoyances filter

Ticket ID(if exists): 706662

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
