### ISSUE TITLE
okino.ua ads

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4793]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

Ads on okino.ua can be found in all the possible browsers on Windows as on this screenshot: http://prntscr.com/evnrxp
Moreover, the issue can be reproduced on Android. http://prntscr.com/evnu12: 

***System configuration***

Information | value
--- | ---
Operating system: | Android / Windows
Browser: | Chrome
Adguard version: | 2.9.64, 6.1.331.1732
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | English, Spyware, Russian, Experimental, Mobile Ads filter, Social Media filter, Annoyances filter

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 706662

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
