### ISSUE TITLE
Stocks, Forex, Futures & News - missed ads 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4794]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Missed ads in the application 

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24975509/9b43f3f6-1fce-11e7-891d-4f09d39304bb.png)

</details>

***Steps to reproduce the problem***:

https://play.google.com/store/apps/details?id=com.fusionmedia.investing

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.64
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On
Adguard filters: | User, English, Russian, Annoyances, Spyware, Social media, Mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1063185

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is blocked on my device. I see it without filtering.
