### ISSUE TITLE
English filter blocks an article on fstoppers.com

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4795]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Something in the English filter is blocking these subpages from fstoppers.com.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24976252/6144bdc2-1fd1-11e7-83bf-0b2ddacafb82.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24976246/5dfa1b76-1fd1-11e7-9855-9e328f794853.png)

</details>

***Steps to reproduce the problem***:

https://fstoppers.com/photojournalistic/father-and-son-project-small-steps-are-giant-leaps-photo-series-172481

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | User, English, Russian, Social media, Spyware 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1017656

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is caused by social filter.
Fixed.
