### ISSUE TITLE
http://www.mangatail.com Adblock Warning

### ISSUE THREAD

**Issue by tagataho** [AdguardTeam/AdguardFilters#4796]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
When i enter this website; 
i see this warning" Please disable AdBlock!There is no bad ads in this site.If you don not like to whitelist our domain,you still have choices to go to......."

http://www.mangatail.com

Can you fix it?

 
* **Current behaviour**: 
On my iphone:
1. When i active this filters:
SPYWARE, SOCIAL MEDIA, Annoyances, SAFARI, TURKISH, Mobile Ads, ENGLİSH
Then i see this screen:
http://i.hizliresim.com/X0la5R.png

2. When i active this filters:
SPYWARE, SOCIAL MEDIA, Annoyances, SAFARI, TURKISH, Mobile Ads
Then i see this:
http://i.hizliresim.com/Qay693.png

3. When i active this filters:
SPYWARE, SOCIAL MEDIA, Annoyances, SAFARI, TURKISH,
Then i see this:
http://i.hizliresim.com/M0ROrQ.png

I think that this problem is because of ENGLISH FILTER.
I want to see 2nd screen. :)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / iOS
Browser: | Safari
Adguard version: | 1.2.0
Adguard driver (Windows): | WFP
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): |  
Simplified filters(iOS) | Off
Adguard DNS: | None 
Stealth mode options(Windows) | 
Adguard filters: | ENGLİSH, SPYWARE, SOCIAL MEDIA, Annoyances, Mobile Ads, SAFARI, TURKISH.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. Do you see this message on desktop?

**Comment by tagataho** [comment]
Yes :(

You always write that "cant reproduce" :(

**Comment by Alex-302** [comment]
Not always.
Try these rules:
```
||mangatail.com/sites/all/themes/newbird/js/adblock-checker.min.js
||mangasail.com/sites/all/themes/newbird/js/acheck.min.js
```
