### ISSUE TITLE
Stealh mode blocks Bitrix24 calls

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#4797]
https://github.com/AdguardTeam/AdguardForWindows/issues/1685

logs 1540543

@Alex-302 can we fix it with filtering rules?

**Comment by vozersky** [comment]
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"
}

**Comment by Alex-302** [comment]
I don't understand how to reproduce it.

**Comment by vozersky** [comment]
@Alex-302 Are there no requests we can exclude in the logs?

**Comment by Alex-302** [comment]
no. I need detailed description how to reproduce the issue.
