### ISSUE TITLE
kaspyinfo.ru - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4798]
http://kaspyinfo.ru/

Screenshot:

<details>

![osebnm__hy8](https://cloud.githubusercontent.com/assets/22892774/25017802/c0f998c0-208d-11e7-9448-146d23460efa.jpg)

</details>

***System configuration***

Information | value
--- | ---
Adguard version: |  1.2.0.74

Filters:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.14.35 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.46 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.57 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.11.82 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.49.65 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.7.95 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.87 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1477730

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
