### ISSUE TITLE
gidonline.club

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4799]
***Description***:
>при просмотре фильмов в онлайн кинотеатре ГидОнлайн при переключении качества видео
появляется вторая звуковая дорожка, которая идёт с запозданием. Дорожки накладываются друг на друга. Пока не отключишь адгард проблема не устраняется.

Reproducible.

***Steps to reproduce the problem***:

Go to:
http://gidonline.club/2017/02/velikaya-stena/
Play video - Pause - the sound doesn't stop

_**_My settings:_**_
***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.2.346.1819
Adguard filters: | 1 2 3 4 5 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1542297

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
