### ISSUE TITLE
Adguard breaks https://tfl.gov.uk/plan-a-journey/

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4800]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Can't see detailed journey plan with Adguard at https://tfl.gov.uk/plan-a-journey/

Could reproduce it on Mac. 

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-04-13 at 11 24 15 pm](https://cloud.githubusercontent.com/assets/26434103/25022976/f126bdb4-208f-11e7-837d-98620f7445f7.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![screen shot 2017-04-13 at 11 23 51 pm](https://cloud.githubusercontent.com/assets/26434103/25022991/09df204e-2090-11e7-8bf3-6e651913196a.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Choose two positions, click Plan a journey and click on Least walking, Bus only or any other way.

***System configuration***

Information | value
--- | ---
Operating system: | iOS 
Browser: | Safari
Adguard version: | 1.1.5.65
Simplified filters(iOS) | On 
Adguard DNS: | None 
Adguard filters: | User, English, Spyware, Social, Safari

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1541318

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
