### ISSUE TITLE
m.8dushu.com - Missed ads

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4801]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Missed ads on m.8dushu.com.

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25027057/ba24d53a-20b2-11e7-999a-bf0e2eebb112.png)

</details>

***Steps to reproduce the problem***:

http://m.8dushu.com/book/38655-28187394/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: |  1.2.0.66
Simplified filters(iOS) | On 
Adguard filters: |User filter, English filter, Spyware filter, Annoyances filter, Experimental filter, Mobile Ads filter, Safari filter, Simplified domain names filter, EasyList China

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1435008

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||qgss8.com^

```
