### ISSUE TITLE
Anti Adblock Script on liveedu.tv

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4802]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

We have a anti block script on liveedu.tv

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25030112/6b08164c-20cb-11e7-9381-a72c90179012.png)

![image](http://somehosting.com/adg_on.jpg)
</details>

***Steps to reproduce the problem***:

- Go to www.liveedu.tv 
- Use any link 

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | User, Russian, English, Spyware, Social media, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1489655

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed

**Comment by heckslam** [comment]
@Alex-302 The main problem was that Anti Adblock Script doesn't allow to watch videos. The message disappeared and thank you for fast reaction, but I did not care about message. I want to watch videos without ads, like I can do it on YouTube. Can you do this?

**Comment by Alex-302** [comment]
@heckslam I can't reproduce an issue with the video
http://imagizer.imageshack.com/img923/1223/A1de1Z.png
Please, provide me direct link to the broken page with screenshot.

**Comment by newmediacrew** [comment]
Liveedu is now blocking browsers with ad blocking software.
http://imgur.com/a/gO0MK

solution: filter @@||www.liveedu.tv/static/js/ads.js$script

**Comment by Alex-302** [comment]
@newmediacrew this rule was added many days ago
https://github.com/AdguardTeam/AdguardFilters/commit/acbcd44db6894f7761a4240e9584dd1578e5c6ea
and issue is not reproducible now.
