### ISSUE TITLE
No Assistant on the webpage with Adguard enabled

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4803]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

No Assistant on the webpage southpark.de

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25032145/869f5870-20da-11e7-92b2-614634f91d7a.png)

</details>

***Steps to reproduce the problem***:

http://www.southpark.de

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | User, Spyware, Social media, English, Russian, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1144186

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
That's because the player is broken by extensions.
