### ISSUE TITLE
http://www.ecigtalk.ru/forum/f20/t150923.html - некорректная блокировка

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4804]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://www.ecigtalk.ru/forum/f20/t150923.html - некорректная блокировка
* **Current behaviour**:  не отображаются фото при нажатии кнопки "показать"

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://clip2net.com/s/3JvtiN4

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.331/ extension 
Adguard driver (Windows): | WFP / TDI
Adguard DNS: | None / Default 
Adguard filters: | Английский фильтр
Фильтр счетчиков и системы аналитики
Фильтр виджетов социальных сетей
Фильтр раздражителей
Русский фильтр
Экспериментальный фильтр

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1104627

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
