### ISSUE TITLE
Missed ads on Advanced Download Manager (Android app)

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdguardFilters#4805]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Missed ads on Advanced Download Manager (Android app)
* **Current behaviour**: The ads appear at the bottom of the screen (wait around 15s before the ads show up).
Link to the app on Play Store: https://play.google.com/store/apps/details?id=com.dv.adm&hl=en
It happens both with DNS request and High-quality filtering mode. In DNS request mode (as shown in 1st screenshot below), different ads show each time and is dynamic; while in High-quality mode (as shown in 2nd screenshot below), same ad shows every time and is static.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
![s70412-173538 1](https://cloud.githubusercontent.com/assets/22385284/25036135/3b3c062a-211c-11e7-8f28-84c255191f31.jpg)
![s70412-174925 1](https://cloud.githubusercontent.com/assets/22385284/25036136/3b91da64-211c-11e7-9fd9-d5a02f82ab2b.jpg)

[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | 
Adguard version: | Latest
Adguard mode (Android): | VPN
Filtering quality (Android): | both High-quality and DNS request filtering mode 
HTTPS filtering (Android): |  On
Adguard DNS: | None
Adguard filters: | English, Spyware, Social, Annoyances, Vietnamese

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It seems that builtin.

**Comment by iverkhohliad** [comment]
We got another customer with the same issue. 
Logs and timing attached in the ticket.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/31311991-14b2a9d4-abc1-11e7-92fe-82eaae2a5dea.png)

</details><br/>


[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Device: | Lenovo K33a42
Operating system:                   | 7.0
AdGuard version:                    | 2.9.136
Filters enabled:                    | 2, 3, 4, 14, 11
AdGuard mode (Android only):        | VPN 
Filtering quality (Android only):   | High-speed 
HTTPS filtering (Android only):     | Off
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1633325

**Comment by Alex-302** [comment]
Read the comment above.
