### ISSUE TITLE
convert-video-online.com

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#4806]
http://convert-video-online.com/

"It starts to happen after one or two days after installing adguard extension(not immediately after installing). The main section of "convert-video-online.com" disappears when adguard adblocker is on. I have tried other major adblocker and only adguard produces this issue."

**Comment by Alex-302** [comment]
Что не так? Загрузил видео - получил результат.

**Comment by vozersky** [comment]
yep, unconfirmed
