### ISSUE TITLE
Otvet.mail.ru программа adguard пропускает рекламу!

### ISSUE THREAD

**Issue by gilutu** [AdguardTeam/AdguardFilters#4807]
Я не знаю что творится с этой вашей программой, она всегда глючит подобным образом. на сайте Otvet.mail.ru уже дня два пропускается реклама в самом низу страницы, в левом блоке и под вопросом. нужно открыть любой вопрос что бы все это увидеть. При том что у меня подключен фильтр ruadlist который без проблем с нею справляется в других блокировщиках, в adguard, он этого не делает почемуто.

**Comment by Alex-302** [comment]
У меня и с ruadlist чисто.
<details>

![image](http://imagizer.imageshack.com/img922/971/dcnCpd.png)
</details>
Какие фильтры включены? Есть сторонние блокировщики? Какая версия программы?

**Comment by gilutu** [comment]
нашел причину, реклама появляется если включить русский фильтр от adguard.
а еще помощник на этом сайте не хочет работать, нажимаю заблокировать элемент, а выбрать ничего не возможно, мышка работает в обычном режиме.

**Comment by Alex-302** [comment]
> нашел причину, реклама появляется если включить русский фильтр от adguard.

маловероятно. У меня чито и жалоб в поддержку нет. Если что, могу удалённо взглянуть, может тестируют что-то.
> а еще помощник на этом сайте не хочет работать

похоже они его ломают. Скоро новая версия помощника выйдет, с ней проверим потом.
> и еще, чтобы появилась проблема кажется нужно пройти авторизацию на сайте.

не понял вопроса.
