### ISSUE TITLE
solarmovie.ink [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#48089]
https://www.solarmovie.ink/film/watch-27567046-Depraved/watching.html

Pop-up seen after clicking on the play button (after completing captcha on player). Moreover, fake links seen on the page (https://prnt.sc/qpq9af)

Additional Fake HOST links seen: https://prnt.sc/qpq9wj

Seen on AG for Chrome

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/1d0c5b9305ebf73ca759161bae116a781f82d781
