### ISSUE TITLE
debridnet.com antiadblock

### ISSUE THREAD

**Issue by ghajini** [AdguardTeam/AdguardFilters#4808]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
antiadblock on debridnet.com being redirected to debridnet.com/ad-blocker
* **Current behaviour**: 

[//]: # (Tell us what happens)

***Steps to reproduce the problem***:

[//]: # 
go to debridnet.com ,you will be redirected to debridnet.com/ad-blocker
***System configuration***

Information | value
--- | ---
Operating system: | Windows 10
Browser: | chrome
Adguard version: | 2.5.11
 
Adguard filters: | english filter ,spyware filter

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Should be fixed now.

**Comment by xhamid** [comment]
Thank you.
