### ISSUE TITLE
solarmovie.news [Fake Links]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#48088]
https://solarmovie.news/8364-cold-moon-for-free.html

Please remove fake links as seen here: https://prnt.sc/qpq6b9

Also after clicking on the first legit play button on the above page, it takes us to another page where the fake server is selected by default. Please remove that too: https://prnt.sc/qpq6zs  and 
https://prnt.sc/qpq6u1

Seen on AG for Chrome

**Comment by krystian3w** [comment]
```
||solarmovie.*/templates/Solar/images/button*_.png
solarmovie.news##.fkplayer2
```

**Comment by krystian3w** [comment]
or:

`solarmovie.news##[href*="/4k"]`
