### ISSUE TITLE
http://mobil.ksta.de - missed ad on page 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4809]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://mobil.ksta.de/region/leverkusen/rekordfund-fast-300-kilo-drogen-bei-leverkusener-grosshaendler-secured-26685560 - missed ad on page 
social media filter doesn't block share buttons

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/25059117/92899268-2189-11e7-9a54-f83ef50815d4.png)
![image](https://cloud.githubusercontent.com/assets/23372054/25059124/a4064072-2189-11e7-9fc8-46915c2c2945.png)

</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

***System configuration***

Application version: 1.1.5.40
Device: iPhone
Platform: iOS
OS: 10.3.1

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.14.5 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.34 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.47 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.11.64 Enabled=YES
ID=6 Name="German filter" Version=1.0.32.72 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.84 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.18 Enabled=NO
ID=101 Name="EasyList" Version=1.0.69.32 Enabled=NO
ID=118 Name="EasyPrivacy" Version=1.0.77.79 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.69.74 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.69.92 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.77.95 Enabled=YES
ID=225 Name="Fanboy Anti-Facebook List" Version=1.0.0.9 Enabled=YES
ID=229 Name="I dont care about cookies" Version=1.0.0.13 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES

Ticket ID 1539561

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
> missed ad on page

where?

> social media filter doesn't block share buttons

I can't reproduce it. Too many filters are enabled. Rules limit number is 50000. These filters contains more than 120000 rules.
Try to disable
ID=118 Name="EasyPrivacy" Version=1.0.77.79 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.69.74 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.69.92 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.77.95 Enabled=YES
ID=225 Name="Fanboy Anti-Facebook List" Version=1.0.0.9 Enabled=YES
ID=229 Name="I dont care about cookies" Version=1.0.0.13 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES

**Comment by sdHfsd3** [comment]
I can reproduce it. According to Adguard, it tells me I’m far away from 50000 used filters. Adding the following rules worked for me:
mobil.ksta.de##.social_btn.email
mobil.ksta.de##.social_btn.facebook
mobil.ksta.de##.social_btn.twitter
mobil.ksta.de##.social_btn.whatsapp
mobil.ksta.de##.twitter

**Comment by Alex-302** [comment]
Ok then, added
```
mobil.ksta.de##.social_btn
```
it should to hide social share buttons.
