### ISSUE TITLE
https://rarbg.to/torrents.php - pop-ups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4810]
![image](https://cloud.githubusercontent.com/assets/15856304/25061677/c9afc47e-2189-11e7-8443-718471496943.png)

> 
> To see it, go to https://rarbg.to/torrents.php, and click on the "search torrents" box. That pops up another tab, the same as the first except the cursor is now in the "search torrents" box.
> But, the original tab turns into an ad. 

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None
Adguard filters: | 2 3 4 10

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1542500

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed

**Comment by hugobuddel** [comment]
rarbg.to managed to do this twice to me with Brave 0.19.45. Usually it doesn't happen, took quite some time to reproduce a second time. Once on Ubuntu and once on Windows.

The specific add (tracker ids removed with [..]):
`https://flirt-and-sex.com/md/na/NL/3steps/index.html?p1=https%3A%2F%2Ftrck.addiliate.com%2Fredirect.html%3Fad%3D[..]%26add1%3D[..]%26add2%3D[..]`

**Comment by Alex-302** [comment]
@hugobuddel which browser are you using?

> The specific add

is it popup or redirect from the current page?

**Comment by hugobuddel** [comment]
Hmm, don't know how I got here! I'm using the Brave browser, which has nothing to do with your project. So please ignore me 😃. I'll go use your tool in other browsers though.

**Comment by Alex-302** [comment]
:)
Nice browser, but poor builtin ad blocker... But AdGuard for Windows can filter it.
