### ISSUE TITLE
Change Finnish default filter list from Wiltteri to Juvander's

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardFilters#4811]
According to User 1543777 default Adguard filter for Finnish Language - Witteri is outdated. 
Their GH page - https://github.com/wiltteri/ - was not updated for 2 years.

Instead they suggest we start using List by Ilpo Juvander available here:
http://adb.juvander.net/Finland_adb.txt
Which is being actively updated (Current version is from 2017-4-10).

**Comment by Alex-302** [comment]
Current url is still actual

![image](http://imagizer.imageshack.com/img923/4139/Jeonvn.png)

**Comment by deLumren** [comment]
@Alex-302 
Android filter lists only contain Wiltteri's from December the 2nd, 2016

**Comment by Alex-302** [comment]
Please write to Android repo. I think URL is hardcoded.
Attach this info:
```
}, {
    "groupId" : 2,
    "filterId" : 116,
    "name" : "Wiltteri",
    "description" : "Finnish supplement list for EasyList",
    "homepage" : "https://github.com/wiltteri/",
    "version" : "1.0.1.70",
    "expires" : 86400,
    "timeUpdated" : "2016-12-02T20:06:37+0400",
    "subscriptionUrl" : "https://raw.githubusercontent.com/wiltteri/wiltteri.txt/master/wiltteri.txt",
    "languages" : [ "fi" ],
    "displayNumber" : 124
  }, {
```
