### ISSUE TITLE
missed ad (android) https://spb.hh.ru/vacancy/20127826?utm_campaign=vacancy_polina_math_040417&utm_medium=social&utm_source=vkontakte

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4812]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: missed ad (android) https://spb.hh.ru/vacancy/20127826?utm_campaign=vacancy_polina_math_040417&utm_medium=social&utm_source=vkontakte

If you click the link, it will lead you to an external website and not to google play.
Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/25071636/2ef7cc28-22c5-11e7-8b99-291de0d0ee0e.png)

***System configuration***

Information | value
--- | ---
Operating system: Android 
Browser: | chrome
Adguard version: | 2.9.64
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On 
Adguard filters: | rus, end, annoyance, social, spyware, mobile, experimental

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1465704

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
