### ISSUE TITLE
Unblocked ios trackers/ads

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#4813]
I saw some ads in meetme app. You have to have an account and they appear randomly. Here is some i found but dont close yet i have some logs to sift thro

nexage.akadns.net (ad company hosting on cdn server)

app.roximity.com (https://www.google.com/amp/www.wsj.com/amp/articles/mobile-ad-firm-verve-acquires-beacon-company-roximity-1466534337)

rtb.adentifi.com

cdn.adtheorent.com

**Comment by Alex-302** [comment]
Added 2,3
1 - not reproduced
