### ISSUE TITLE
lepoint.fr - anti-adblocker/annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4814]
![image1 2](https://cloud.githubusercontent.com/assets/15856304/25082575/6c16830c-235a-11e7-94e4-aae02f985126.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.3.1
Browser: | Safari
Adguard version: | the current one
Simplified filters(iOS) | Off
Adguard DNS: | Default 
Adguard filters: | Eng, France, Russian, Annoyances.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 575960

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed

**Comment by MacFlurry** [comment]
hello, still see tue issue on IOS.

**Comment by Alex-302** [comment]
Got it. 
Please add to custom filter and check again
@@||lepoint.fr/publicite/*.js
Added to French(not Liste FR) filter.

**Comment by MacFlurry** [comment]
Added to custom filter works, thanks.
Do you know why it’s not worked when added to the French filter?

**Comment by Alex-302** [comment]
> Do you know why it’s not worked when added to the French filter?

URL of ad marker was changed.
