### ISSUE TITLE
esquire.ru - некорректная блокировка

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4817]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: esquire.ru - некорректная блокировка
* **Current behaviour**: не открываются статьи с включенным Adguard 

***System configuration***

Application version: 1.2.0.66
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.14.70 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.51 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.69 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.11.91 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.49.80 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.87 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.31 Enabled=NO

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1236012

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Меня перенаправляет на https://stroiki39.ru/ Там проблем не вижу, поиск работает, квартиры открываются.

**Comment by Bohdan-SUP** [comment]
@Alex-302 can you check [esquire.ru](esquire.ru) again, please?
@vmalyuta was able to reproduce it with DNS enabled

**Comment by zebrum** [comment]
esquire не работает в сафари даже если Adguard выключен.

**Comment by dzamyshlyayeva** [comment]
esquire. ru не работает с включеным Adguard. с выключеным все нормально 

ticket ID 1236012

**Comment by Alex-302** [comment]
@dzamyshlyayeva как именно не открываются - фильтр или днс блокирует? Мы ж не телепаты)

**Comment by dzamyshlyayeva** [comment]
@Alex-302 проблема повторяется и с днс, и с фильтрами

**Comment by zebrum** [comment]
@Alex-302 главная сайта загружается, но ни в одну статью не войти, на нажатия не реагирует. Только это происходит и без включенной фильтрации Adguard у меня.

**Comment by Alex-302** [comment]
@zebrum у меня работает, с/без нашего DNS.

**Comment by zebrum** [comment]
@Alex-302 у меня тоже только что работало, теперь вот не работает. Связи с нами я не выявила. И это именно на айфоне.
