### ISSUE TITLE
chip.de - Whole site access blocked.

### ISSUE THREAD

**Issue by FireEmerald** [AdguardTeam/AdguardFilters#4818]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: www.chip.de is a huge german website which provides downloads for almost all available Programms (only legal).
* **Current behaviour**: A '_you were blocked page_' is shown instead of the real website.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/1107939/25107471/e06a390e-23cf-11e7-8e59-5378b548d819.png)
</details>

* **Expected behaviour**: The normal website should be access able and shown without ads.

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![chip de_normal](https://cloud.githubusercontent.com/assets/1107939/25107530/3d3d04c2-23d0-11e7-9883-f5029ba5d2f5.png)
</details>

***Steps to reproduce the problem***: Just open the website www.chip.de without any white listing.

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Google Chrome 57.0.2987.133 (64-bit)
Adguard version: | Adguard Werbeblocker 2.5.11
Adguard driver (Windows): | Chrome Plugin
Adguard DNS: | None
Stealth mode options(Windows) | -
Adguard filters: | English Filter (1.1.14.66. 16 april 2017), Spyware-Filter (1.0.11.51. 14 april 2017), Social-Media-Filter (1.0.18.69. 14 april 2017), German Filter (1.0.32.91. 15 april 2017)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): -

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@FireEmerald are you sure that is caused by Adguard?

**Comment by FireEmerald** [comment]
@Alex-302 After white listing the site i'm able to access it without problems, so yes definitely.

**Comment by Alex-302** [comment]
Are you using stealth mode? Which options are enabled?

**Comment by FireEmerald** [comment]
What's _"stealth mode"_ ?

These options are enabled:
![adguard](https://cloud.githubusercontent.com/assets/1107939/25182324/86bc304c-2514-11e7-9cb9-8dfca12a486f.png)

**Comment by Alex-302** [comment]
Ah, browser extension...
Ok, then try to disable all filters and check again. If the issue will not be reproduced,enable filters one-by-one with checking.

**Comment by FireEmerald** [comment]
```Spyware-FilterVersion 1.0.11.56.``` breaks the site.

**Comment by Alex-302** [comment]
Good)
Now leave only this filter, open filtering log and refresh tab. Then select `Blocked` checkbox in filtering log and make screenshot.

**Comment by FireEmerald** [comment]
![protokoll](https://cloud.githubusercontent.com/assets/1107939/25184528/0b2cc8e0-251b-11e7-958c-92add073f40c.png)

**Comment by Alex-302** [comment]
Try to add to user filter:
```
@@||p.d.1enm.com^$domain=chip.de
@@||optimizely.com^$domain=chip.de
```

Do you know how to create exclusions by filtering log?

**Comment by FireEmerald** [comment]
Seems like the site is working with this custom filter rules. Now there are only 7 matches left:
![protokoll 2](https://cloud.githubusercontent.com/assets/1107939/25185414/910fb4f2-251d-11e7-980f-be9a1d75e942.png)

**Comment by Alex-302** [comment]
Ok, you can to enable your usual filters and check again.
If it is still working, try to remove one of that rules. We will find only the necessary rule.

**Comment by FireEmerald** [comment]
```@@||p.d.1enm.com^$domain=chip.de``` is the needed rule so that the site is working while all other filters are enabled.

**Comment by Alex-302** [comment]
Good)
Please copy example of p.d.1enm.com url

**Comment by FireEmerald** [comment]
**5** url's are whitelisted from ```@@||p.d.1enm.com^$domain=chip.de```.
Do you need these full urls?

**Comment by Alex-302** [comment]
yes, full. You can change meaningless character sets if you want)

**Comment by FireEmerald** [comment]
```
https://p.d.1enm.com/v4/AAAACgAAUnskf7IhAfnjsOFvI-AP4gAA_b02bwQ008645nOYMN8ylyJP93xrakhpnC2LTbjektDXnJso5AH-hWYVI7GMhOiwAgan6voftm9OTNjM2XdkoaskIXWSFPXdHQ
https://p.d.1enm.com/v4/AAAACgAAUnskf7IhAfnjsOFvI-AP4gAA_pVTy9Q0086YsuamjXm1Yh_s5dJAhf30lmOCg8rOrsQGnD_3d197l67fppG1IhPx_wNlU2LWugT-4jCMi2n3JBe98i4bspfcAAKsRol-6jgVMsxMK-QNH16ftGnDVkdeoIQ9PrIFTfSIZwHKBa2J6xkSq57u2S-r1OSyGtklFXB4JZDpRKhDOrKVdwi78xX17qQ
https://p.d.1enm.com/static.js?vt=2d023b7a269506aebd53465241556869
https://p.d.1enm.com/v1/AAAAAQAAndfj3qXAE2W0q81ZdJd-TAAA_bHC_3w02950O96Gw6_le5cl9bnlum70ygiPdlkjmAL8vBKCp-5BX4FNU4ThVn3aneO1ZCIPjMX10uopx1DC8qs_WZH4bKrASUlpMM7R4CuiJ4pNy8Y6LP3sTbCo_XJhCRvc4k35Fk0ozrduUuF2eAIm9-mZVwScECJJRt0qE25uW4kc3xgqf6JiA6G9t60xqbcoTfv4n9HI_eIfs98oelxU_9hQDbACuQMN_GlWGX_hAOmLc9d4Lxc_3JPN6Q0107MqiK71_lB709emkoAajOxU-Ze_fZMFLJ96ItZnB98rsNbmNM52BnXOaBeZlq9thT8dPq3SPLX2flARCEG68pXd_l9I8fwYbqV8JfH37KpLg
https://p.d.1enm.com/v1/AAAAAQAAndfj3qXAE2W0q81ZdJd-TAAA_bHC_3w02950O96Gw6_le5cl9bnlum70ygiPdlkjmAL8vBKCp-5BX4FNU4ThVn3aneO1ZCIPjMX10uopx1DC8qs_WZH4bKrASUlpMM7R4CuiJ4pNy8Y6LP3sTbCo_XJhCRvc4k35Fk0ozrduUuF2eAIm9-mZVwScECJJRt0qE25uW4kc3xgqf6JiA6G9t60xqbcoTfv4n9HI_eIfs98oelxU_9hQDbACuQMN_GlWGX_hAOmLc9d4Lxc_8n2yZg0171MqiK71_lB709emkoAajOxU-Ze_fZMFLJ96ItZnB98rsNbmNM52BnXOaBeZlq9thT8dPq3SPLX2flARCEG68pXVaiQpTAcYwN2knCm3rIIk_V3Fe46XzeeztR2TM78_JWlesnfnlMACTIJceIFAzZHZOKJBJE8TAvPfl9PEvFb00

Type:   JavaScript
Source: chip.de
Rule:   @@||p.d.1enm.com^$domain=chip.de
Filter: Userdefined
```
(Note: Urls partially modified, length is the same)

**Comment by Alex-302** [comment]
Try this exclusion instead of previous:
```
@@||p.d.1enm.com/static.js$domain=chip.de
```

**Comment by FireEmerald** [comment]
```@@||p.d.1enm.com/static.js$domain=chip.de``` doesn't work. I tested also the following two rules:

```
@@||p.d.1enm.com/v1^$domain=chip.de  // Doesn't work.
@@||p.d.1enm.com/v4^$domain=chip.de  // Works, see mage below:
```

![protokoll 4](https://cloud.githubusercontent.com/assets/1107939/25187881/94d4292c-2524-11e7-8784-7fbc3aa0fb53.png)

**Comment by Alex-302** [comment]
Ok, thanks. Added to Spyware filter
```
@@||p.d.1enm.com/v4^$domain=chip.de
```
