### ISSUE TITLE
Android Central app - ads leftover

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4819]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

We have some ads leftover in the Android Central application.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25108866/86e7c0c4-23e1-11e7-823d-2bb1eebf2993.png)

</details>

***Steps to reproduce the problem***:

https://play.google.com/store/newsstand/news/Android_Central?id=CAowpYEB&hl=en

Choose "Core" news from the drop-down menu.

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |Android
Adguard version: | 2.9.64
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On 
Adguard filters: | User, English, Russian, Spyware, Social media, Mobile Ads 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1316067

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
These paddings look like builtin. I don't see any separators in JSON's.
@seanl-adg please take a look.
You can close is as `won't fix`.
