### ISSUE TITLE
liveinternet.ru - ad

### ISSUE THREAD

**Issue by Ksenija-K** [AdguardTeam/AdguardFilters#4820]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
http://www.liveinternet.ru/users/lamerna/post211804227/  
Ad on the right side is not blocked

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-04-18 at 5 37 14 pm](https://cloud.githubusercontent.com/assets/27729686/25136680/55645558-245e-11e7-8b72-981ca96fb1f1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None

Adguard filters: 
<details>

![screen shot 2017-04-18 at 5 47 33 pm](https://cloud.githubusercontent.com/assets/27729686/25137002/29e4cae2-245f-11e7-92d2-468bac1d6a0b.png)

</details>

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 
795453

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. I need a HAR file or saved page(in private mode, without authorization)
