### ISSUE TITLE
EasyPrivacy blocking multiple sites links from opt-in emails on gmail [iOS]

### ISSUE THREAD

**Issue by yourduskquibbles** [AdguardTeam/AdguardFilters#48216]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

When EasyPrivacy is enabled, clicking on some links in gmail that include tracking paramaters such as an amazon order info, a fedex tracking link, a news story from seekingalpha.com, or an article from quora.com, in gmail app on iOS gets blocked by 1 or more filters in EasyPrivacy list.

My best guess is that this is false positive caused by some portion of the link in the email including `track` in the URL [See URL formats below] but I'm unable to fully debug iOS Safari issues because no MacOS to test with.

Example links getting blocked by EasyPrivacy when clicked via gmail tracking card/link that I tested as **BLOCKED** by EasyPrivacy are below:

- Amazon.com - link format: `https://www.google.com/url?q=https://www.amazon.com/gp/r.html?C%3D[redacted]%26K%3D[redacted]%26M%3Durn:rtn:msg:[redacted]%26R%3D[redacted]%26T%3DC%26U%3Dhttps%253A%252F%252Fwww.amazon.com%252Fgp%252Fyour-account%252Fship-track%253Fie%253DUTF8%2526orderId%25[redacted]%2526packageIndex%253D0%2526shipmentId%25[redacted]%2526ref_%25[redacted]_scr_pt_track%26H%3D[redacted]%26ref_%3D[redacted]_scr_pt_track&source=gmail&ust=[redacted]&usg=[redacted]`

- fedex.com - link format: `https://www.google.com/url?q=https://www.fedex.com/Tracking?action%3Dtrack%26language%3Denglish%26cntry_code%3Dus%26tracknumbers%3D [redacted20digitid]&source=gmail&ust=[redacted]&usg=[redacted]`

- quora.com - link format: `https://www.google.com/url?q=https://www.quora.com/qemail/track_click?uid%3D[redacted]%26al_imp%3D[redacted]%253D%26aoid%3D[redacted]%26request_id%3D[redacted]%26aoty%3D2%26et%3D2%26al_pri%3DQuestionLinkClickthrough%26id%3D[redacted]%253D%253D%26ct%3D[redacted]%26src%3D1%26ty_data%3D[redacted]%3D1%26click_pos%3D1%26st%3D[redacted]%26source%3D1%26stories%3D[redacted]%25[redacted]%25[redacted]%25[redacted]%25[redacted]%25[redacted]%25[redacted]%25[redacted]&source=gmail&ust=[redacted]&usg=[redacted]`
- seekingalpha.com - link format: `https://www.google.com/url?q=https://email.seekingalpha.com/news/[redacted]/track?type%3Dclick%26mailingid%3D[redacted]%26messageid%3D[redacted]%26databaseid%3D%26serial%3D[redacted]%26emailid%3D[redacted]%26userid%3D[redacted]%26extra%3D%26%26%26[redacted]%26%26%26https://seekingalpha.com/account/email_auth?auth_param%3D[redacted]%26ref%3D%252Fnews%252F[redacted]-digital-tax-in-spotlight-this-week%253Fsource%253Demail_rt_mc_readmore%2526utm_medium%253Demail%2526utm_source%253Dseeking_alpha%2523email_link&source=gmail&ust=[redacted]&usg=[redacted]=i`

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![googs](https://user-images.githubusercontent.com/22258847/72739827-785ea300-3b72-11ea-808b-2d2ca23441c6.jpg)

</details><br/>

* **Expected behaviour**: 

links clicked through gmail app should load properly even if they have some tracking metrics included in the link from the provider. 

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

AdGuard Base Filter
AdGuard Mobile Ads filter
AdGuard Tracking Protection Filter
EasyPrivacy Filter (with EasyPrivacy disabled, the tracking links via the gmail card loads fine)
AdGuard Social Media filter
Fanboy's Social Blocking List
AdGuard Annoyances Filter
I don't care about cookies
EasyList Cookie List
Web Annoyances Ultralist
AdGuard Safari filter
AdGuard Experimental filter

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | 13.3
Operating system version (Android/iOS) | iOS
Browser:                               | Safari
AdGuard version:                       | 3.1.3(252)
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by yourduskquibbles** [comment]
@ryanbr ?

**Comment by Alex-302** [comment]
It is not Easylist issue. iOS ralatet only.

**Comment by yourduskquibbles** [comment]
> It is not Easylist issue. iOS ralated only.

No exception filter is possible to counteract this behavior? Only option is disable EasyPrivacy? 

Sorry if these are noob questions, I'm not very familiar with the limitations of iOS Safari content blocker vs desktop full featured adblocker.

**Comment by Alex-302** [comment]
Please check these rules:
```
@@.com/tracking?
@@/track?*&ref=
@@/track_click?
@@||amazon.*/gp/r.html?
```

**Comment by Alex-302** [comment]
They are for test only. I will make specific exclusions for content-blockeds only.

**Comment by yourduskquibbles** [comment]
> ```
> @@.com/tracking?
> @@/track?*&ref=
> @@/track_click?
> @@||amazon.*/gp/r.html?
> ```

Tested with EasyPrivacy enabled and CONFIRMED these user filters all work - content from the 4 example sites loads correctly now.

**Comment by Alex-302** [comment]
Ok, please check these rules instead of previous
```
@@||fedex.com/tracking?
@@||amazon.*/gp/r.html?
@@/track?*&ref=$~script,~xmlhttprequest,~other
@@/track_click?$~script,~xmlhttprequest,~other
```
Please wait a minute after changing filters, do not close AG window.

**Comment by yourduskquibbles** [comment]
> Ok, please check these rules instead of previous
> 
> ```
> @@||fedex.com/tracking?
> @@||amazon.*/gp/r.html?
> @@/track?*&ref=$~script,~xmlhttprequest,~other
> @@/track_click?$~script,~xmlhttprequest,~other
> ```
> 
> Please wait a minute after changing filters, do not close AG window.

FedEx still blocked, other 3 work great though 👍

**Comment by yourduskquibbles** [comment]
> > Ok, please check these rules instead of previous
> > ```
> > @@||fedex.com/tracking?
> > @@||amazon.*/gp/r.html?
> > @@/track?*&ref=$~script,~xmlhttprequest,~other
> > @@/track_click?$~script,~xmlhttprequest,~other
> > ```
> > 
> > 
> > Please wait a minute after changing filters, do not close AG window.
> 
> FedEx still blocked - may be case sensitive - `@@||fedex.com/Tracking?` instead of `@@||fedex.com/tracking?` Will test that change and report back.
> 
> Other 3 work great though 👍

 just tested,  neither `@@||fedex.com/Tracking?`  or `@@||fedex.com/tracking?` work, still blocked

**Comment by Alex-302** [comment]
Correct rule: `@@://www.fedex.com/Tracking?`

**Comment by yourduskquibbles** [comment]
> @@://www.fedex.com/Tracking?

This works! 👍👍

**Comment by Alex-302** [comment]
Thanks.
