### ISSUE TITLE
yomasti.co - Anti Adblocker

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#4821]
Screenshot:

<details>

![screen shot 2017-04-19 at 12 05 54 am](https://cloud.githubusercontent.com/assets/27292111/25153107/0be0ca02-2494-11e7-8ef5-ab915e5b439c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1 2 3 4 5 14

Ticket ID: 1531498

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Resolved, it is using a wordpress theme which have such a feature. On platforms which supports `$replace`, it should be fixed globally. On other platforms, site-specific rules must be added.
