### ISSUE TITLE
Can't log in to grover.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#48221]
@iDjay commented on [Mon Jan 20 2020](https://github.com/AdguardTeam/AdguardForMac/issues/672)

### Steps to reproduce
1. enable advanced tracking protection in settings (screenshots -> my settings)

2. open https://www.grover.com/ and try to log in to your account -> fails

3. disable advanced tracking protection -> login works fine
= it's not a filter related issue

### Expected behavior
login should work fine with advanced tracking protection enabled

### Actual behavior
login fails because "the page jumps back to the login screen"

<details><summary>Screenshot:</summary>

<img width="680" alt="Bildschirmfoto 2020-01-20 um 16 16 17" src="https://user-images.githubusercontent.com/4127356/72737663-449a7200-3ba0-11ea-8cfe-6c6ed5c26528.png">
<img width="788" alt="Bildschirmfoto 2020-01-20 um 16 16 22" src="https://user-images.githubusercontent.com/4127356/72737664-449a7200-3ba0-11ea-9578-7741ef35e2bf.png">
<img width="714" alt="Bildschirmfoto 2020-01-20 um 16 16 28" src="https://user-images.githubusercontent.com/4127356/72737665-449a7200-3ba0-11ea-83e0-0789663c9a92.png">
<img width="736" alt="Bildschirmfoto 2020-01-20 um 16 16 35" src="https://user-images.githubusercontent.com/4127356/72737666-449a7200-3ba0-11ea-9ed1-e9a3c2d2dfe8.png">

</details>

### Your environment
macOS 10.15.2
Safari 13.0.4
AdGuard 2.3.2.710

---

@ameshkov commented on [Mon Jan 20 2020](https://github.com/AdguardTeam/AdguardForMac/issues/672#issuecomment-576376969)

> disable advanced tracking protection -> login works fine
> = it's not a filter related issue

Well, advanced tracking may sometime cause issues like that, but it can actually be solved on the filters side

**Comment by akmLaVx** [comment]
Received logs from the OP. See ticket 1938768.
