### ISSUE TITLE
conference-hosting.net - Anti Adblocker

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#4822]
Screenshot:

![screen shot 2017-04-19 at 12 13 17 am](https://cloud.githubusercontent.com/assets/27292111/25153461/455dc644-2495-11e7-9700-baf0492c57db.png)

</details>

Information | value
--- | ---
Operating system: |  Mac OS
Browser: | Chrome
Adguard version: | 1.4.1 
Adguard filters: | 1 2 3 4 5 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1531498

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Fixed
