### ISSUE TITLE
http://www.pajarracos.es - site with ads

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4823]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://www.pajarracos.es - site with ads

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/ey28bn

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.2.1.71
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.14.95 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.56 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.78 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.61 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.87 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.33 Enabled=NO
ID=101 Name="EasyList" Version=1.0.70.5 Enabled=YES
ID=231 Name="Easylist Spanish" Version=1.0.15.14 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=230 Name="FanboyEspanol" Version=1.0.0.2 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.78.39 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.73 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1545021

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced even with English filter.
