### ISSUE TITLE
http://vkinopoiskah.ru/ - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4824]
Ссылка на сайт: http://vkinopoiskah.ru/

![image](https://cloud.githubusercontent.com/assets/15856304/25165675/56aae2a6-24e0-11e7-92bc-bb54377304c3.png)

Мои параметры:
* Windows 7 x64
* Adguard в виде расширения у Chrome
* Используемые фильтры: Русский фильтр, Английский фильтр, RU AdList
* Dr.Web

**Comment by Alex-302** [comment]
Fixed
