### ISSUE TITLE
http://kinofactor.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4825]
http://kinofactor.ru/film/20560/

![image](https://cloud.githubusercontent.com/assets/15856304/25165753/978ac3f4-24e0-11e7-8727-f56b1f11de8c.png)

***System configuration***

* Windows 7 x64
* Adguard в виде расширения у Chrome
* Используемые фильтры: Русский фильтр, Английский фильтр, RU AdList
* Dr.Web

**Comment by Alex-302** [comment]
fixed
