### ISSUE TITLE
https://tjournal.ru/ - incorrect blocking / missed social media widget

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4826]
https://tjournal.ru/

![image](https://cloud.githubusercontent.com/assets/15856304/25167884/07263b04-24ea-11e7-98a3-800e1466959f.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | Chrome extension

- English filterVersion 1.1.14.67. Updated 16 april 2017 at 13:00.
- Spyware filterVersion 1.0.11.51. Updated 14 april 2017 at 17:00.
- Social media filterVersion 1.0.18.69. Updated 14 april 2017 at 21:00.
- Annoyances filterVersion 1.0.11.91. Updated 15 april 2017 at 16:02.
- Russian filterVersion 1.0.49.80. Updated 14 april 2017 at 21:00.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 939612

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
