### ISSUE TITLE
trafmag.com - no filtering

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4827]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Trafmag.com webiste isn't filtered and renders incorrectly with Adguard enabled (happends on computers as well)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25185873/23addbdc-2527-11e7-9e9d-ba4d1224c374.png)
![image](https://cloud.githubusercontent.com/assets/17320558/25185884/2b9f3fc0-2527-11e7-9638-92765d7ff933.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25185908/3d6e9b92-2527-11e7-8cab-72a136c892ec.png)

</details>

***Steps to reproduce the problem***:

http://trafmag.com/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS / Android 
Browser: | Chrome
Adguard version: | 1.4.1 / 2.9.64
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On Default
Adguard filters: | User, Spyware, Social Media, English, Annoyances 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1530099

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Seems to be a bug.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/651
