### ISSUE TITLE
www.tutuapp.vip -missed ad on page 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4829]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:http://www.tutuapp.vip/index.php?r=overseaTutu/mobileTutu&lang= - missed ad on page 
 reproduced on ios 10.3.1

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/25206206/2b632b32-256f-11e7-8feb-8028b4b17302.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.2.1.71
Application lifetime: 1970-01-01 00:00:00 +0000

Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.15.1 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.61 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.82 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.3 Enabled=YES
ID=6 Name="German filter" Version=1.0.33 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.89 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.34 Enabled=NO

Ticket ID 1545472

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
User should to Mobile filter.
Added to Mobile filter
```
||jssdk.rayjump.com^$third-party
```
