### ISSUE TITLE
https://electrek.co - missed ad on page 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4830]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://electrek.co/2017/04/19/watch-gm-self-driving-chevy-bolt-ev-prototype-racoon-video/ - missed ad on page 
 
[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/25206377/554fc300-2570-11e7-8ac6-a091c948b351.png)

</details>

***System configuration***

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3.1

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.14.93 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.56 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.78 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.2 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.87 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.33 Enabled=NO

Ticket ID 1528242

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
electrek.co##body > div[class^="th"]
electrek.co##.post-body > div[class^="th"]
electrek.co##.post-content > div[class^="th"]
```
