### ISSUE TITLE
http://mangastream.com/ - missed ad on page 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4831]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://mangastream.com/ - missed ad on page 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/25207474/8a289abe-2577-11e7-8402-e391324b2f4e.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3.1

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.14.97 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.58 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.79 Enabled=YES
ID=16 Name="French filter" Version=1.0.1.53 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.6 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.88 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.34 Enabled=NO

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID 1545382

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce without Adguard.
