### ISSUE TITLE
rufilmtv.org - site with ads 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4832]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: rufilmtv.org - site with ads 
**Current behaviour**: video ads 

Screenshot:
http://prnt.sc/eyl3gg

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.1.3./ 1.4.1
Simplified filters(iOS) | On / Off
Adguard DNS: | None
Subscriptions: 

- FilterId:1 Name: Russian filter Url: https://filters.adtidy.org/extension/chromium/filters/1.txt
- FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
- FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt
- FilterId:4 Name: Social media filter Url: https://filters.adtidy.org/extension/chromium/filters/4.txt
- FilterId:14 Name: Annoyances filter Url: https://filters.adtidy.org/extension/chromium/filters/14.txt

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 648896

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня не повторилось.
Передай на проверку(в приватной вкладке)
```
||hydr.work^$third-party
```

**Comment by KozelElena** [comment]
Пользователь сообщил, что не работает правило. Что можем еще посоветовать?

**Comment by evgeniy-ADG** [comment]
@Alex-302 у меня повторяется, но без видео, только звук. Вот [тут](http://rufilmtv.org/films/tsennyiy-gruz-smotret-onlayn.html).

**Comment by Alex-302** [comment]
На проверку:
```
rufilmtv.org#%#Object.defineProperty(Object.prototype, 'iAdTimer', { get: function() { return function() { $(document).trigger('advideoend'); }; } });
```
или
```
rufilmtv.org#%#Object.defineProperty(Object.prototype, 'iAdTimer', { get: function() { return 3; } });
```

**Comment by vmalyuta** [comment]
отправила

**Comment by Alex-302** [comment]
Не поможет(
Видео заглушку вставил вместо рекламы. Но сработает только с программой.

**Comment by KozelElena** [comment]
Теперь вообще перестали воспроизводиться фильмы. Если еще что посоветовать?

**Comment by Alex-302** [comment]
Поправил.
