### ISSUE TITLE
http://neverfold.ru/ - site with ads + incorrect blocking

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4833]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://neverfold.ru/threads/turniry-i-frirolly-kazino-nashi-prizovye-mesta.40279/page-21- site with ads + incorrect blocking 
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/eym8vs
http://prnt.sc/eym9sp
http://prnt.sc/eymhj7

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | chrome 
Adguard version: | 1.4.1 
Adguard DNS: | None 
Stealth mode options(Windows) | 
Adguard filters: | English filter
Spyware filter
Social media filter
Experimental filter
Annoyances filter

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1023486

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Рекламу убрал, ложное не повторилось. Точно только английский фильтр включен?
