### ISSUE TITLE
kinogo.club - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4834]
http://kinogo.club/
yandex browser with extension 2.5.11
en rus spyware annoyances social media

![screenshot 2017-04-20 14 45 51](https://cloud.githubusercontent.com/assets/23637588/25229219/2275a27a-25d8-11e7-9608-3cb7d75e94b3.png)

in chrome everything is ok but if you click somewhere it redirects you.

<details>

![screenshot at apr 20 14-49-37](https://cloud.githubusercontent.com/assets/23637588/25229463/0a5cec2e-25d9-11e7-8ce0-81ca4cb4b2cb.png)

</details>

**Comment by Alex-302** [comment]
Fixed
