### ISSUE TITLE
forum.autoua.net - missed pop-up

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4835]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

A pop-up comes uo after 15 seconds aproximmately.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25237569/b2964e8e-25f3-11e7-867b-59e437d4f104.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

http://forum.autoua.net/showflat.php?Cat=0&Number=9259913&Main=9244255

***System configuration***

Information | value
--- | ---
Operating system: |  iOS
Browser: | Safari
Adguard version: | 10.3
Adguard filters: | User filter, English filter, Spyware filter, Social media filter, Annoyances filter, Russian filter, Mobile Ads filter, Safari filter, EasyPrivacy

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1518078

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is impossible to block this popup in iOS in this site. Scrolling will be broken.
