### ISSUE TITLE
spaces.ru - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4836]
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![cakoibvecmk](https://cloud.githubusercontent.com/assets/22892774/25243545/0e640582-2606-11e7-9dac-4325ecd4a10a.jpg)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Browser: | Chrome
Adguard version: | 2.9.64
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard filters: | 1 2 3 4 5 11 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID): 1545906

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
