### ISSUE TITLE
Surfline Anti Block

### ISSUE THREAD

**Issue by opiumozor** [AdguardTeam/AdguardFilters#4837]
***Description***:
* **Current behaviour**: 

When trying to watch the live stream, I get an error message saying that I need to disable my ad blocker

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

http://imgur.com/a/ceQSR

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

- Go to Surfline.com 
- Try to open a video stream
- http://www.surfline.com/surf-report/topanga-beach-southern-california_4210/

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Safari
Adguard version: | latest
Adguard driver (Windows): | WFP / TDI
Adguard mode (Android): | VPN / Proxy(manual/auto)
Filtering quality (Android): | High-quality / high-speed / simplified
HTTPS filtering (Android): |  On (Default/Blacklist mode) / Off
Simplified filters(iOS) | On / Off
Adguard DNS: | None / Default / Family Protection
Stealth mode options(Windows) | 
Adguard filters: | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Should be resolved now

**Comment by opiumozor** [comment]
@seanl-adg I am still having the issue

**Comment by Alex-302** [comment]
@opiumozor which Adguard version and filters are you using?

**Comment by opiumozor** [comment]
@Alex-302 Safari filterVersion 1.0.2.93, English filterVersion 1.1.15.16, Adguard 2.5.12

**Comment by Alex-302** [comment]
@opiumozor please check again.
Filters update becomes available after 1-1.5 hours after adding the rule.

**Comment by opiumozor** [comment]
@Alex-302 works! Thanks!

**Comment by Alex-302** [comment]
Ok)
