### ISSUE TITLE
my.mail.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#48373]
При открытии фрейма с сообщениями (по иконке справа, вверху) внутри ничего не прогружается.

<details><summary>Screenshot:</summary>

![2020 01 21-1](https://user-images.githubusercontent.com/17948007/72895817-5d855d80-3d2f-11ea-82ab-6c106f1fc626.png)
</details>

 Всему виной правило `my.mail.ru#%#//scriptlet("abort-on-property-read", "Object.prototype.isFixedRightEnable")` из 'фильтра Раздражителей'. Если его исключить `my.mail.ru#@%#//scriptlet("abort-on-property-read", "Object.prototype.isFixedRightEnable")`, то содержимое прогружается, но с рекламой справа.

<details><summary>Screenshot:</summary>

![2020 01 22-1](https://user-images.githubusercontent.com/17948007/72896002-d2f12e00-3d2f-11ea-894b-8c4d54db1c9a.png)
</details>

 Для скрытия этого рекламного блока можно воспользоваться следующим правилом:
`my.mail.ru##.b-messages__right + div`

[https://my.mail.ru/mail/pinsashinri1986/?browse=messages](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://my.mail.ru/mail/pinsashinri1986/?browse=messages)

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.3.8
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
У меня не повторяется.
@tvinzz глянь плз.

**Comment by XX-J** [comment]
У меня и на чистом FireFox v68.4.2 ESR (x32) повторилось.

**Comment by XX-J** [comment]
До сих пор актуально.

**Comment by Alex-302** [comment]
@slavaleleka @zloyden проверьте у себя.

**Comment by zloyden** [comment]
Повторилось, обновление придет в течение 2-3 часов.
