### ISSUE TITLE
http://jpost.com - website crushes with Adguard enabled 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4839]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://jpost.com - website crushes with Adguard enabled 
* **Current behaviour**: jpost.com consistently crashes when Adguard is active

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/eyzbu5
http://prnt.sc/eyzbys

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

***Steps to reproduce the problem***:

1. navigate to http://jpost.com
2. try maneuvering around the page. It will be extremely slow and laggy (unlike when Adguard is not in place)
3. Click on any link in the page. It MAY load (it acts frozen at first)
6. Scroll the page and Safari will display an "A problem occurred with this webpage so it was reloaded"
4. This will keep attempting to reload and crash until the browser gives up with a message "A problem repeatedly occurred on http://m.jpost.com/#/app/article/488410"

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.2.1.75
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.14.97 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.57 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.79 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.2 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.87 Enabled=YES
ID=101 Name="EasyList" Version=1.0.70.6 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.70.8 Enabled=YES
ID=108 Name="EasyList Hebrew" Version=1.0.4.54 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1545230

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Confirmed once, but I can't open this site at the moment:
<details>

![image](http://imagizer.imageshack.com/img922/7936/CIRZ5L.jpg)
</details>
It the issue reproducible with all filters disabled?

**Comment by deLumren** [comment]
User believes the reason to be the English filter. 
They have spyware, English, social media and Safari filters. "if I remove the English filter, the problem for the most part disappeared."

They also wonder if a consistant crash is a security vulnerability that should be reported to Apple? 

Another concern they have is that this might be a jump off point for an in browser jail break.

**Comment by Alex-302** [comment]
Reproduced in Safari on MacOS without ad blocker. The tab hangs up

<details>

![image](http://i89.fastpic.ru/big/2017/0424/6c/128681cf2fb3d7e688b384120416826c.jpg)
</details>
