### ISSUE TITLE
AntiAdblocker on http://www.engineeringtoolbox.com/

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardFilters#4840]
website http://www.engineeringtoolbox.com/ has anti-adblocker banner.
Exists on Mac/PC/Android.

Looks like this:

<details>

![screen shot 2017-04-21 at 11 36 17 am](https://cloud.githubusercontent.com/assets/26342177/25270914/ec8fe086-268a-11e7-9545-d2308e1f4358.png)

</details>

Originally reported by User 1543128

**Comment by Alex-302** [comment]
Added to English filter
```
engineeringtoolbox.com##div[class^="topicAd_"]
```

**Comment by deLumren** [comment]
It is only fixed on the main page. Once you get to any entry - banner appears again:

<details>

![screen shot 2017-04-22 at 8 48 08 am](https://cloud.githubusercontent.com/assets/26342177/25301799/b155331e-2738-11e7-8ba9-2d93f132287e.png)


</details>

**Comment by Alex-302** [comment]
Fixed.
