### ISSUE TITLE
stream-mydirtyhobby.biz - adblock detected 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4841]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://stream-mydirtyhobby.biz/view/amystarr-geheimes-fickdate-im-freien/BhRdT - Adblock detection / video can't be played
reproduced on 10.3.1

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

1st click on video - the popup opens, 2nd - video starts 

<details>

![image](https://cloud.githubusercontent.com/assets/23372054/25280805/e6e94338-26b3-11e7-8623-cc286567adb0.png)

![image](https://cloud.githubusercontent.com/assets/23372054/25280825/f680b09c-26b3-11e7-9afb-b7733aede55b.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.15.18 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.65 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.89 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.9 Enabled=YES
ID=6 Name="German filter" Version=1.0.33.8 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.8 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.93 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.35 Enabled=NO

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID 1480792

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||easylist.club/popunder*.js
@@||easylist.club/adlabs.js

```

**Comment by vmalyuta** [comment]
http://prnt.sc/f1nw0a

**Comment by Alex-302** [comment]
Fixed
