### ISSUE TITLE
elbotola.com

### ISSUE THREAD

**Issue by YASINEDr** [AdguardTeam/AdguardFilters#48420]
AdGuard **detected** on 👍 

[https://www.elbotola.com/video/details/5e28c57cc5a4b007da0894fc/](url)

![screenshot-www elbotola com-2020 01 22-23_19_54](https://user-images.githubusercontent.com/34688076/72939767-d1465b00-3d6d-11ea-9400-ec65865936cd.png)

> I don't know how to fillout the form completely !

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.

Please next time fill the template or use reporting tool - https://reports.adguard.com/en/new_issue.html
