### ISSUE TITLE
Не работают трекеры в qBittorrent спустя некоторое время

### ISSUE THREAD

**Issue by LiveTuneR** [AdguardTeam/AdguardFilters#48425]
Добрый день, столкнулся с такой проблемой что +- начиная с 7 версии AdGuard для Win перестали работать трекеры (нету отдачи статистики о раздачах). Перезапуск программы помогал на не большой промежуток времени, после чего они опять не отвечали. Даже и подумать не мог что виной тому AdGuard. Версии qBit пробовал разные - проблема всегда одна.
Какие нужно предоставить логи для обнаружения и решения проблемы?

**Comment by Alex-302** [comment]
Опишите подробнее, через сколько времени после запуска клиента начинается проблема.
Отваливаются все трекеры или какие-то определённые? От раздач не зависит? Что в логе самого клиента или конкретной раздачи?

**Comment by zubrRB** [comment]
qBittorrent у вас находится в фильтруемых приложениях AdGuard?

**Comment by LiveTuneR** [comment]
@Alex-302, трекеры не работают все, по времени нет никаких точных временных интервалов. После перезапуска программы qBit трекеры работают, а следующий сеанс отключения их может быть в интервале 15 минут - 12 часов (больше не смотрел, обычно перезапускал уже). От раздач не зависит - сейчас раздается 415 раздач на 18 трекеров, после отключения трекеров  скорость соответственно падает (по ней я и узнаю отвалившийся пул трекеров). Логов программа не ведет, но в статусе трекеров на адресе трекера будет статус "Не работает". После 30 дневной борьбы с провайдером я решил проверить не мог ли это быть AdGuard (раньше у меня была проблема с интересными симптомами которую решал @confessor-adguard https://github.com/AdguardTeam/AdguardForWindows/issues/2057) и тут я решил посмотреть на то, как поведут себя трекеры (который на тот момент были уже не рабочими) при отключении фильтрации - после переанонса раздач трекеры заработали. Машина работает уже 9-ый день - возможно что из-за этого, раньше проблема #2057 так же часто возникала по этой причине.

@zubrRB нет, отдельно включенной фильтрации на нем нету, только если идет распространение с WFP-драйвера. Так же включена автоматическая фильтрация приложений.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/CoreLibs #1251](https://github.com/AdguardTeam/CoreLibs/issues/1251) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
@LiveTuneR Перетащил в другой репозиторий. Фильтрами вряд ли можно помочь.
Желательно включить в настройках Адгарда полное логирование, и после возникновения проблемы экспортировать их и отправить в поддержку, а комментом к новой задаче - номер обращения. Ну и желательно указать приблизительное время, когда отвалились трекеры.
