### ISSUE TITLE
animeid.tv - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4842]
https://www.animeid.tv/ - a lot of redirects by clicking somewhere on page with browser extension in chrome
rus en spyware annoyances social media

<details>

![screenshot 2017-04-21 17 19 31](https://cloud.githubusercontent.com/assets/23637588/25281668/b4002362-26b6-11e7-9637-f2220de7d35c.png)

</details>

**Comment by Alex-302** [comment]
Not reproduced even in Safari.

**Comment by zebrum** [comment]
@Alex-302 TV (:

**Comment by Alex-302** [comment]
Fixed
