### ISSUE TITLE
SurfEarner extension blocked by Adguard 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4843]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

SurfEarner extension for Chrome is being blocked by Adguard

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
Adguard filters: | English filter, Spyware filter, Social media filter, Filter unblocking useful ads, Russian filter, German filter, EasyList China, EasyList Italy, User filter

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1500588

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Check this rule:
```
@@||surfearner.com
```

**Comment by Astuser** [comment]
Good! This rule with rule [@@||surfearner.com$document] is working! 
SurfEarner extension no longer blocked.
Thanks!

**Comment by Alex-302** [comment]
Ok. I can't to add it to the main filters, because it is impossible to make it specific for domain/extension, so you should to leave it in user filter.
