### ISSUE TITLE
AntiAdblockScript  at https://upload.af/kmo67y0wtlyt

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardFilters#4844]
Impossible to access 
https://upload.af/kmo67y0wtlyt

Exists on all platforms. Looks like this:
<details>

![screen shot 2017-04-22 at 8 36 56 am](https://cloud.githubusercontent.com/assets/26342177/25301768/f791ba38-2737-11e7-8b56-875bf5cc1a6d.png)

</details>

Reported by User 1543128

**Comment by seanl-adg** [comment]
Fixed
