### ISSUE TITLE
Ads in AfreecaTV (Korean)

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardFilters#4845]
App is called AfreecaTV (Korean) - has no English menu.
PlayMarket https://play.google.com/store/apps/details?id=kr.co.nowcom.mobile.afreeca&amp;hl=ko

Video ads before joining a new Stream.

Here is what it looks like:
Screenshot: http://imgur.com/a/bzSPr
GIF: https://giphy.com/gifs/3og0IzfrtSN073oL0Q  (car part is an ad)

More detailed info & logs with timestamps in User 1546713's ticket.

**Comment by seanl-adg** [comment]
Hi, I've checked the app and ads wasn't reproduced too. However, in the log the user attached, there were requests to a domain admvod.afreecatv.com. On my end such request was not reproduced.

Please tell the user to try blocking the domain, by adding
```
||admvod.afreecatv.com^
```
to the user filter. It should block video ads the user reported, but have a possibility to break the app. If it does break the app, we will need a HAR request log of which instruction on getting it is written at https://kb.adguard.com/en/android/solving-problems/har

**Comment by deLumren** [comment]
Asked the user to add this rule. Will update as soon as he replies.
