### ISSUE TITLE
vse.fm

### ISSUE THREAD

**Issue by zolpar** [AdguardTeam/AdguardFilters#4846]
Когда уже мой аккаунт активируют на forum.adguard.com, а не будет отклонять каждый раз с сообщением StopForumSpam?

Заходим на сайт, выбираем любое радио, пробуем включить что-то из архива, получаем
**Уведомление от сайта vse.fm: Отключите блокировщик рекламы и обновите страницу!**

**Comment by Alex-302** [comment]
```
@@||vse.fm/advert.js
```
Оно вообще работает? Без блокировщика только рекламу показывает.

**Comment by zolpar** [comment]
сейчас вообще так
и без блокера
http://radikal.ru/lfp/s010.radikal.ru/i313/1704/52/6813775010d2.png/htm

**Comment by Alex-302** [comment]
Может парсер сломался. Выждем.

**Comment by Alex-302** [comment]
Правило добавил.

**Comment by zolpar** [comment]
сообщения нет, но при попытке воспроизведения оно навечно зависает / без блокера сначала нужно закрыть, нажав на крестик, объявление от гугла

**Comment by Alex-302** [comment]
Дай прямую ссылку. У меня там без блокировщика только реклама работает.

**Comment by zolpar** [comment]
https://vse.fm/station_66

**Comment by Alex-302** [comment]
А проверь такое:
```
@@||yastatic.net/share2/share.js$domain=vse.fm
```

**Comment by zolpar** [comment]
помогло

**Comment by Alex-302** [comment]
Добавил.

**Comment by Adguarder** [comment]
Архив вечно грузится теперь 
Либо есть невидимая плашка "отключите адблок", либо невидимый рекламный блок не исчезает и не запускает запись
Работает только в режиме инкогнито без расширений
Прямой эфир работает его никогда не трогали

**Comment by Adguarder** [comment]
новое сообщение в старой теме или каждый раз плодить темы
https://github.com/AdguardTeam/AdguardFilters/issues/4846#issuecomment-323665180
Английский фильтр Версия 1.1.28.59.
Русский фильтрВерсия 1.0.55.72.

**Comment by Adguarder** [comment]
Английский фильтр Версия 1.1.28.59.
Русский фильтр Версия 1.0.55.72.
