### ISSUE TITLE
my-hit.org missed ads

### ISSUE THREAD

**Issue by deLumren** [AdguardTeam/AdguardFilters#4848]
Issue **only** happens in Yandex.Browser (with Adguard for Windows active) before playing any video.

 Looks like this:
<details>

![bossreklama](https://cloud.githubusercontent.com/assets/26342177/25302909/73a7c61c-2751-11e7-9f5e-1c709807f420.png)

</details>

Reported by user 677335

**Comment by Alex-302** [comment]
Fixed
