### ISSUE TITLE
up-4ever.com

### ISSUE THREAD

**Issue by zolpar** [AdguardTeam/AdguardFilters#4850]
https://www.up-4ever.com/fnyaznpqlzab
ADBLOCK IS ENABLED
ADBLOCK DISRUPT WEBSITE FUNCTIONALITY, IF YOU FACE ANY PROBLEM, TRY TO DISABLE ADBLOCK. YOU CAN UPGRADE YOUR ACCOUNT TO HIDE ALL ADS.

**Comment by Alex-302** [comment]
Fixed
