### ISSUE TITLE
missed ads http://www.gamesofdesire.com/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4851]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: missed ads on the website http://www.gamesofdesire.com/
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prntscr.com/ezipnq

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | English, Russian, experimental, annoyance, social, spyware, mobile

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1050245

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
||gamesofdesire.com/vghd/
gamesofdesire.com##object[name="vghd"]
||gamesofdesire.com/skin/*_*.html
||217.23.12.240/files/flash/*-side.swf
||gamesofdesire.com/files/flash/*-side.swf

```
