### ISSUE TITLE
Useful Ads Filter Blocking (ad.doubleclick.net and adservice.google.com)

### ISSUE THREAD

**Issue by SimplyGardner** [AdguardTeam/AdguardFilters#48527]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

**Description**
Useful Ads Filter Not Unblocking Shopping/Product Ads
I have the Useful Ads Filter added and upon searching Google, I see sponsored products at the top of the search. When clicking a product, AdGuard blocks the link and it fails to load the page.

Upon clicking the product, it looks like the domains that that are being blocked is ``ad.doubleclick.net`` and then it redirects to ``adservice.google.com`` then finally the retailers website. Whitelisting these two domains work but I don't want to open the floodgates.

**Expected behaviour:**
When the Useful Ads Filter is installed, to unblock links to those sponsored ads without opening the floodgates.

[//]: # (Substitute this line with a description of the problem)

***Steps to reproduce the problem***:

1. Visit Google
2. Type a product description, i.e Adidas Trainers
3. Click the Sponsored product link (before the actual Google Results)

***System configuration***

**Filters:**
https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/UsefulAdsFilter/sections/usefulads.txt

**Comment by Alex-302** [comment]
Which AdGuard and filters are you using?
Is DNS system or AdGuard DNS?

**Comment by SimplyGardner** [comment]
Currently running AdGuard Home (Version: v0.100.9)

I have the following filters:
<img width="614" alt="Screenshot 2020-01-27 at 21 44 45" src="https://user-images.githubusercontent.com/46373533/73216637-3fb06200-414e-11ea-9f74-2675077cc498.png">

**Comment by Alex-302** [comment]
Please  show blocked google ads domains, which must be whitelisted.

**Comment by SimplyGardner** [comment]
The two blocked domains are ``ad.doubleclick.net`` and also ``adservice.google.com``.

Whitelisting these domains enables those Google Shopping ads to work correctly.

**Comment by Alex-302** [comment]
Definitely these domains are used for ads on third-party sites. You can add to whitelist them.

**Comment by ijuliank** [comment]
Why is this whitelisted? I now see ads comming thruw at some sites.. i dont want this
