### ISSUE TITLE
anti-adblock  https://www.natchezss.com

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4852]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:anti-adblock https://www.natchezss.com/case-6mm-rem-unprimed-50rd.html?bvdata=action%3Drr_submit_review%26campaignId%3DBV_PIE%26userToken%3D8fe09e6de7f6e0549d0c59b92cb507087ed32093985f05f946cba45f53a3f08966623d3f26656d61696c616464726573733d646f75677465727279253430736263676c6f62616c2e6e657426757365726e616d653d646f75677465727279253430736263676c6f62616c2e6e6574267573657269643d3238373632383026686f737465643d5645524946494544267375626a6563746964733d484f383632322f36304e2676657269666965647075726368617365723d5472756526646174653d3230313730343231266d61786167653d3330%26messageType%3DPIE%26recipientDomain%3Dsbcglobal.net%26productId%3DHO8622%26notificationId%3D47adbf6e-2708-11e7-9709-1240c57d7c64

Screenshot:

![image](https://cloud.githubusercontent.com/assets/25711093/25306896/f0aa221a-279f-11e7-97e1-ed5bfc88dd1d.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | english, russian, annoyance, social, spyware, moblile, experimental

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1547200

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
The anti-adblock logic is located in `bazaarvoice.com`'s resource. `$empty`-blocking the resource also removes the aa notification, but the submit function will be broken. We may need to find out what can be done to block the third-party resource without breaking the page.
