### ISSUE TITLE
http://www.idnes.cz/ - Incorrect Blocking 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4853]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://www.idnes.cz/ - Incorrect Blocking 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
ttp://prnt.sc/ezojfq

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:
1) Open the website
2) Click on any article

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.2.1.7
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.15.30 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.65 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.95 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.14 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.61 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.8.9 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.94 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.36 Enabled=NO
ID=101 Name="EasyList" Version=1.0.70.18 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.70.20 Enabled=YES
ID=105 Name="EasyList Czech and Slovak" Version=1.0.1.98 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.78.74 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=201 Name="Czech List" Version=1.0.0.2 Enabled=YES
ID=225 Name="Fanboy Anti-Facebook List" Version=1.0.0.9 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.78.62 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.74 Enabled=YES
ID=237 Name="AdBlock Protector List" Version=1.0.0.10 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1547161

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||idnes.cz/*.aspx?c=
```
