### ISSUE TITLE
8 ball pool app - incorrect blocking 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4854]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 8 ball pool app - incorrect blocking 
* **Current behaviour**: Adguard blocks 9 ball mode in the 8 ball pool app

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/ezp62b
http://prnt.sc/ezp6fv

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.2.1.71
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.14.90 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.56 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.76 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.11.97 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.49.88 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.61 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.8.1 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.87 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.33 Enabled=NO
ID=118 Name="EasyPrivacy" Version=1.0.78.33 Enabled=YES

Ticket ID(if exists): 1518078

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I need more detailed description.
Is disabling of PRO mode helps?

**Comment by KozelElena** [comment]
Получили ответ от пользователя:

Раньше отключал Pro режим, пару раз перезапускал игру, иногда само устройство, после чего появлялась в приложении реклама, вместе с новым режимом игры. Сейчас попробовал вышеперечисленное - не помогло. Удалил adguard - не помогло. Переустановил игру без adguard, но ничего не появилось.

Может разработчики игры убрали рекламу временно с главного экрана, не знаю. 

Заметил следующее: если без адгуард запустить игру и реклама загрузится и после включить адгуард, то реклама отображается какое-то время, видимо в кеше остаётся. Когда изначально включить адгуард и запустить приложение, чтоб реклама не отображалась, после выйти и удалить адгуард, запустить игру, то рекламы нет, нужно сыграть одну игру и тогда видимо реклама загружается.

**Comment by Alex-302** [comment]
Мне всё равно не понятно, что было неправильно заблокировано.

**Comment by Bohdan-SUP** [comment]
Разобрались с пользователем, Adguard никак не влияет.

**Comment by Alex-302** [comment]
Ну и отлично.
