### ISSUE TITLE
https://www.wattpad.com/ - site with ads

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4855]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://www.wattpad.com/story/35801060-%d0%b4%d0%bd%d0%b5%d0%b2%d0%bd%d0%b8%d0%ba-%d0%bd%d0%b5%d1%81%d1%87%d0%b0%d1%81%d1%82%d0%bd%d0%be%d0%b9-%d0%ba%d0%b5%d0%b9%d1%82 - site with ads

* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

http://prnt.sc/ezqac9

***System configuration***

Application version: 1.2.1.71
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.15.25 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.65 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.95 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.13 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.1.3 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.50.14 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.6.33 Enabled=NO
ID=12 Name="Safari filter" Version=1.0.2.94 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.36 Enabled=NO

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1138152

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
wattpad.com###bottom-banner-container
wattpad.com###announcements-container
```
