### ISSUE TITLE
de-baystars.doorblog.jp

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#48563]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

Anti-adblock (antiblock.org v2.3)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![de-baysters](https://user-images.githubusercontent.com/58900598/73118009-49409b00-3f91-11ea-9b06-6bbfc71577b8.PNG)
</details><br/>

***Steps to reproduce the problem***:

Just visit the site, reproduced on Firefox Windows too. Accessed from Japan. The site detects multiple cosmetic filters in Base filter so for iOS I guess
`||@@de-baystars.doorblog.jp^$generichide`
is best. I leave scriptlet for other platforms to you.

***System configuration***

**Filters:**

Base, Mobile, Tracking Protection, Social, & Japanese

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | iOS (iPad mini2)
Operating system version (Android/iOS) | 12.4.4
Browser:                               | Safari
AdGuard version:                       | 3.1.4 (254)
Simplified filters (iOS only)          | On
AdGuard DNS:                           | None

**Comment by Alex-302** [comment]
Fixed.

**Comment by Yuki2718** [comment]
Thx for the fix and nice to see you addressed cookie popup and blogroll too. I suggest to make
`###gdpr-banner`
generic. The rationale is it appears not only at doorblog.jp, but also at all these Livedoor domains
`2chblog.jp,blog.jp,blog.livedoor.com,blog.livedoor.jp,bloggeek.jp,blogism.jp,blogo.jp,blogpark.jp,blogstation.jp,blogto.jp,cafeblog.jp,corpblog.jp,diary.to,doorblog.jp,dreamlog.jp,gger.jp,golog.jp,ldblog.jp,liblo.jp,lineblog.me,livedoor.biz,livedoor.blog,myjournal.jp,mynikki.jp,officeblog.jp,officialblog.jp,publog.jp,storeblog.jp,teamblog.jp,techblog.jp,weblog.to,xxxblog.jp,youblog.jp`
and bunch of unique domains.

**Comment by Alex-302** [comment]
Ok. It seems this rule is not problematic.
