### ISSUE TITLE
missed ads in apps ( android 7.1.1)

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4856]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: missed ads in apps ( android 7.1.1)
https://play.google.com/store/apps/details?id=com.idea.backup.smscontacts
http://storage7.static.itmages.ru/i/17/0420/h_1492670105_4282778_e41e645877.png
https://play.google.com/store/apps/details?id=com.noinnion.android.greader.reader
http://storage7.static.itmages.ru/i/17/0420/h_1492670105_9690358_88456ce55d.png
https://play.google.com/store/apps/details?id=com.metalsoft.trackchecker_mobile
http://storage8.static.itmages.ru/i/17/0420/h_1492670106_1145020_bfd768a8aa.png
https://play.google.com/store/apps/details?id=rikka.appops
http://storage8.static.itmages.ru/i/17/0420/h_1492670106_2363894_a5c4de3465.png
https://play.google.com/store/apps/details?id=com.a0soft.gphone.app2sd
http://storage8.static.itmages.ru/i/17/0420/h_1492670106_1683390_393a02ea25.png
https://play.google.com/store/apps/details?id=nl.jacobras.notes
http://storage7.static.itmages.ru/i/17/0420/h_1492670105_8540670_236943e0bf.png

The issues started after updating from android 7.0 to  7.1.1

Issue time in the debug file 11:10-11:12
[state.txt](https://github.com/AdguardTeam/AdguardFilters/files/949736/state.txt)
[debug (70).txt](https://github.com/AdguardTeam/AdguardFilters/files/949737/debug.70.txt)

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Adguard version: | 2.9.64
device | OnePlus ONEPLUS A3010
Adguard mode (Android): | VPN 
HTTPS filtering (Android): |  On 
Adguard filters: | 2, 3, 14, 1, 11 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1545840

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
https filtering in apps on Anroid 7 is not working, until Adguard certificate is not moved to the system storage(root access is required)

**Comment by OlegSUP** [comment]
Ответ от пользователя:
"   Установка сертификата в систему не помогает.

http://savepic.ru/13864291.png 

По совету вашего представителя на 4pda включил опцию
pref.proxy.ipv6.block - бестолку Пара примеров
(во всех приложениях реклама НЕ
фильтруется):

https://play.google.com/store/apps/details?id=com.noinnion.android.greader.reader

http://savepic.ru/13835616.png

https://play.google.com/store/apps/details?id=com.idea.backup.smscontacts

http://savepic.ru/13872483.png   "

**Comment by Alex-302** [comment]
У меня седьмого ведра нет, ничего дельного, кроме переноса серта подсказать не могу.
При запуске приложений в журнале Адгарда запросов от приложений не видно(HTTPS в частности)?
После праздников, числа десятого в чат наш напиши, подумаем.

**Comment by Alex-302** [comment]
Вот это может помочь:
http://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=61181442

**Comment by AndyFresh** [comment]
Помогло. Закрывайте тикет, спасибо.
