### ISSUE TITLE
missed ad in MediaGet app ( Android 6.0)

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4857]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: missed ad in MediaGet app
https://play.google.com/store/apps/details?id=com.mediaget.android&hl=en
Screenshot:

<details>

![screenshot_2017-04-22-18-04-43](https://cloud.githubusercontent.com/assets/15856304/25353152/087247f4-2937-11e7-9147-2b4cd80885f7.png)

</details>

Is not reproduced on Meizu m3s ( android 5.1)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.64
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | 2, 3, 4, 14, 1, 11 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1398162
[state.txt](https://github.com/AdguardTeam/AdguardFilters/files/949802/state.txt)
[debug (73).txt](https://github.com/AdguardTeam/AdguardFilters/files/949803/debug.73.txt)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Судя по логу, запросы заблокированы. Но у меня реклама не хочет загружаться даже без Адгарда. 
Попроси полностью остановить это приложение, очистить его кэш, и записать лог ***http*** запросов с указанием времени запуска приложения.

**Comment by Darina655** [comment]
@Alex-302 Похоже прислал логи.
Здравствуйте.Предложение о просмотре
рекламы появляется сразу,как только
активируешь программу медиоджет.Её
можно убрать нажав на крестик в самом
банере.Но это приходится делать
каждый раз при использовании
программы.Спасибо.

**Comment by Alex-302** [comment]
Похоже встроено. У меня при выключенной сети он появился, и кнопка баннера реагирует на нажатие как часть интерфейса(заливка при долгом нажатии)
