### ISSUE TITLE
yandex.ru missed ads Android

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#4858]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: yandex.ru missed ads Android

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/25315421/3465a976-285d-11e7-9649-9ecde578d0e2.png)

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | chrome
Adguard version: | 2.9.64
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On
Adguard filters: | 2, 3, 4, 14, 1, 11 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1150428

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Что на этом скрине можно разглядеть?

**Comment by Michael23456** [comment]
![image](https://cloud.githubusercontent.com/assets/25711093/25316342/0b373a9a-286e-11e7-996e-0edb4e145367.png)

**Comment by Alex-302** [comment]
Во, так лучше)

**Comment by Alex-302** [comment]
Добавил в фильтр раздражителей
```
yandex.ru##a[href*="/clck/redir/dtype=clck/lid=geotouch.iphone.banner/"] > div[class]
yandex.ru##.homescreen.periodical-popup
```
