### ISSUE TITLE
twitch.tv -- streaming is broken in Safari

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4859]
Player shows: "Media resouce is not supported" error

**Comment by Alex-302** [comment]
@ameshkov not reproduced, in works as expected on iOS and MacOS. Checked few streams.
Which filters are enabled?

**Comment by sergeymakinen** [comment]
I reproduce it on any stream on Safari 10.1 (macOS) with
* English filter Version 1.1.15.49. Updated 24 april 2017 at 21:00.
* Spyware filter Version 1.0.11.67. Updated 24 april 2017 at 17:00.
* Russian filter Version 1.0.50.28. Updated 24 april 2017 at 19:00.
* Safari filter Version 1.0.2.94. Updated 21 april 2017 at 21:01.
* Adblock Warning Removal List Version 1.0.78.87. Updated 24 april 2017 at 20:34.
* Anti-Adblock Killer | Reek Version 1.0.1.68. Updated 2 december 2016 at 19:09.

**Comment by Alex-302** [comment]
@sergeymakinen 
please check this rule in user filter
```
@@|blob:https://www.twitch.tv
```

**Comment by sergeymakinen** [comment]
Works fine with this rule.

**Comment by Alex-302** [comment]
Ok, please wait for filters update.

**Comment by ameshkov** [comment]
The issue is still here with Turkish filter enabled

**Comment by Alex-302** [comment]
Can't reproduce. Asked for remote access.

**Comment by Demonic16** [comment]
Initially I asked  @ameshkov about this issue.
With current versions of filters I use (English filter, Version 1.1.16.48; Russian filter, Version 1.0.50.56; Safari filter, Version 1.0.3) everything works as expected on Twitch.
Thanks for solving!

**Comment by Alex-302** [comment]
Ok, that's good)
