### ISSUE TITLE
kickasstorrents popunder

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4860]
Get the current proxy domain:
https://thekickasstorrents.com/

At the moment, it is http://kickasstorrents.to/
Please note, that this is about Safari content blockers.

We might need to file a bug report to WebKit if $popup rule is not enough here.

**Comment by Alex-302** [comment]
I can't reproduce popunder(iOS 10.3.2 beta 3)
What about to create test page for it?
