### ISSUE TITLE
phandroid.com thumbnails missing

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4861]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

When Adguard is enabled on android,  phandroid.com is missing thumbnails in news headlines using VPN mode and the default list of filters enabled: 
Adguard is on http://prntscr.com/f000q9
Adguard disabled: http://prntscr.com/f0010b
The user expects Adguard won't affect this website.: 

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On 
Adguard filters: | English filter, Spyware filter, Social media filter, Annoyances filter, Mobile ads 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(1547682): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Are you sure about filters list? This site can be broken by Russian filter. Please ask about it.
