### ISSUE TITLE
Idnes.cz - incorrect blocking

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4862]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

The first page loads normally, but if you click on other links - it appears blocked.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25322766/ba3ff1cc-28c2-11e7-87e4-20b49c4ba28e.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25322763/ab6069b6-28c2-11e7-9fb5-5e07e79f5a0c.png)

</details>

***Steps to reproduce the problem***:

http://ekonomika.idnes.cz/vyplati-se-ruzyni-dalsi-ranvej-dm4-/eko-doprava.aspx?c=A170421_215500_eko-doprava_suj

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |iOS
Browser: | Safari
Adguard version: | 10.3.1
Simplified filters(iOS) |  Off
Adguard filters: | User filter, English filter, Spyware filter, Social media filter, Safari filter, EasyList Czech and Slovak

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1424766

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is already fixed. Check for updates.
