### ISSUE TITLE
nintendo.pt

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#48621]
[https://www.nintendo.pt/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nintendo.pt/)

![cookie](https://user-images.githubusercontent.com/35470489/73129946-bd992f80-3fcd-11ea-976a-8a5a9c009b1c.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
need saved page

**Comment by adranger** [comment]
[nintendo.pt.zip](https://github.com/AdguardTeam/AdguardFilters/files/4118799/nintendo.pt.zip)

The annoyances list already covers the German site, but all these sites have the same code:

* [https://www.nintendo.co.uk/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nintendo.co.uk/index.html)
* [https://www.nintendo.de/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nintendo.de/index.html)
* [https://www.nintendo.ch/de/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nintendo.ch/de/index.html)
* [https://www.nintendo.at/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nintendo.at/index.html)
* [https://www.nintendo.fr/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nintendo.fr/index.html)
* [https://www.nintendo.be/fr/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nintendo.be/fr/index.html)
* [https://www.nintendo.ch/fr/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nintendo.ch/fr/index.html)
* [https://www.nintendo.es/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nintendo.es/index.html)
* [https://www.nintendo.nl/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nintendo.nl/index.html)
* [https://www.nintendo.be/nl/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nintendo.be/nl/index.html)
* [https://www.nintendo.it/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nintendo.it/index.html)
* [https://www.nintendo.ch/it/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nintendo.ch/it/index.html)
* [https://www.nintendo.ru/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nintendo.ru/index.html)
* [https://www.nintendo.co.za/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.nintendo.co.za/index.html)

**Comment by Alex-302** [comment]
Fixed.
