### ISSUE TITLE
sozcu.com.tr - Missed ads 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4863]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Ads are not blocked by the rule dizipub.com###video-wrapper > iframe:first-child

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25322869/b1952e6a-28c3-11e7-8c14-9e89176de33d.png)

</details>

***Steps to reproduce the problem***:

http://www.sozcu.com.tr/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |iOS
Browser: | Safari
Adguard version: | 10.3.1 
Simplified filters(iOS) |  Off
Adguard filters: |
 ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.15.28 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.65 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.95 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.13 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.7.39 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.9 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.94 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1487333

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't find it. It is on the main page?
