### ISSUE TITLE
rezka.ag

### ISSUE THREAD

**Issue by likewhater** [AdguardTeam/AdguardFilters#48644]
?When adguard is on cannot play any video, attach gif
![screencast-sede administracionespublicas gob es-2020 01 16-12_35_52 (1)](https://user-images.githubusercontent.com/27908826/73136832-6ab58b80-4052-11ea-80fd-bbd5fe5e5592.gif)

**Comment by zloyden** [comment]
It was fixed, please check filters update in 2-3 hours.
