### ISSUE TITLE
olx.ua - incorrect blocking 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4864]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

We have a complaint about olx.ua: 

- Safari filter disabled -> notification "Check the internet connection"
- English filter disabled ->  the list of active adverts appeared
- Spyware filter disabled -> notification "Check the internet connection" disappeared

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25335949/e8d126c4-28fd-11e7-95c6-5a32cd05ce4b.png)
![image](https://cloud.githubusercontent.com/assets/17320558/25335955/ee453ece-28fd-11e7-92f6-ca240a7fe772.png)

![image](http://somehosting.com/adg_on.jpg)
</details>

***Steps to reproduce the problem***:

https://www.olx.ua/i2/myaccount/active/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: |  1.2.1.71
Simplified filters(iOS) | Off
Adguard filters: | 
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.15.20 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.65 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.90 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.9 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.50.10 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.8 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.93 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1518078

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
olx.ua#@##adContainer
olx.ua#@#.adRow 
```
***not finished***

**Comment by Alex-302** [comment]
Fixed
