### ISSUE TITLE
anime.anidub.life

### ISSUE THREAD

**Issue by solara322** [AdguardTeam/AdguardFilters#48653]
### Problem Description
https://anime.anidub.life/anime/anime_ongoing/11123-ruki-proch-ot-kinokluba-eizouken-ni-wa-te-wo-dasu-na.html
Не запускается плеер, пока не выключишь блокировщик рекламы.

**Comment by Alex-302** [comment]
@solara322 какой Адгард и какие включены фильтры? Антитрекинг включен?
