### ISSUE TITLE
uip.me - Incorrect blocking

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4865]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Adguard is enabled:

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25336119/b537b084-28fe-11e7-9f66-261ffb9c5c32.png)

</details>

* **Expected behaviour**: 

Adguard is disabled:

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25336159/f151e0a8-28fe-11e7-85bb-d8fc0bee682d.png)

</details>

***Steps to reproduce the problem***:

https://uip.me/2017/04/huawei-p10-lie/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.2.1.71
Simplified filters(iOS) | Off
Adguard filters: | 
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES	
ID=2 Name="English filter" Version=1.1.15.20 Enabled=YES	
ID=3 Name="Spyware filter" Version=1.0.11.65 Enabled=YES	
ID=4 Name="Social media filter" Version=1.0.18.90 Enabled=YES	
ID=14 Name="Annoyances filter" Version=1.0.12.9 Enabled=YES	
ID=1 Name="Russian filter" Version=1.0.50.10 Enabled=YES	
ID=11 Name="Mobile Ads filter" Version=1.0.8.8 Enabled=YES	
ID=12 Name="Safari filter" Version=1.0.2.93 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1518078

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
