### ISSUE TITLE
Microsoft Solitaire Collection - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4866]
https://itunes.apple.com/us/app/microsoft-solitaire-collection/id1103438575?mt=8

<details>

The app with no ads:

![image](https://cloud.githubusercontent.com/assets/15856304/25342241/1bc5793e-2914-11e7-9c8a-8470866d0a2d.png)

The pop-up ads:

![image](https://cloud.githubusercontent.com/assets/15856304/25342257/2fe56ff0-2914-11e7-9b73-f849e4a0b791.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | 
Adguard version: | 1.2.1.71
Adguard DNS: | Default

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1546147 -with logs, timing and stuff

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Also not reproduced.
The first record in the log - 15:32, not 8:46, as user said.
I need steps how to reproduce it.
