### ISSUE TITLE
popups on fmovies.se

### ISSUE THREAD

**Issue by sostostg** [AdguardTeam/AdguardFilters#4867]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: Clicking while navigating the site can produce popups

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

***Steps to reproduce the problem***: Click on videos or links on site and pop ups will open

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 10.12.4
Browser: | Safari 10.1
Adguard version: | 2.5.12
Adguard filters: | English, Spyware, Social Media, Safari

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Have notice some ads coming from these domains which can be blocked by these rules

||adexec.net^$popup
||0912701309f8ce.com^$popup

**Comment by Alex-302** [comment]
Is HTTPS filtering enabled on your device?

**Comment by uBlock-user** [comment]
add - `fmovies.*##a[href^="//"]`

**Comment by Alex-302** [comment]
@uBlock-user it is unnecessary. That buttons are already hidden.

**Comment by sostostg** [comment]
No HTTPS filtering enabled on my end, but the popups seem to have stopped with the rules I put in the first post

**Comment by Alex-302** [comment]
Which OS and Adguard version are you using?

**Comment by sostostg** [comment]
Hi there, it's all in the first post but

> Operating system:	Mac OS 10.12.4
Browser:	Safari 10.1
Adguard version:	2.5.12
Adguard filters:	English, Spyware, Social Media, Safari

In total I've added these three rules to stop popups

`||adexec.net^$popup`
`||0912701309f8ce.com^$popup`
`||d71e6dd31a026d45.com*^$popup`

Thanks again!

**Comment by Alex-302** [comment]
Ok, added to safari filter.
