### ISSUE TITLE
nordbayern.de - Social widget - iOS Browser

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4869]
***Site***: http://www.nordbayern.de/wirtschaft/neuer-bieter-osterreicher-greifen-nach-wohrl-1.6042170
***Description***: Social widgets on mobile devices at the end of an article.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25359470/b2f98242-2945-11e7-8334-7d7ffbc0da27.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.346.1819
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.15.50
Spyware filter | 1.0.11.68
Social media filter | 1.0.18.99
Annoyances filter | 1.0.12.18
German filter | 1.0.33.21
Mobile ads filter | 1.0.8.9
Safari filter | 1.0.2.94

**Comment by Alex-302** [comment]
Added to Social filter
```
nordbayern.de###socialshareprivacy
```

**Comment by danidoedel** [comment]
@Alex-302 Any way to block that green WhatsApp bar too?
