### ISSUE TITLE
AdGuard blocks embedded twitter tweets

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#48693]
@tiiiecherle commented on [Sun Jan 26 2020](https://github.com/AdguardTeam/AdGuardForSafari/issues/312)

### Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.6.4
* Environment name and version: 13.0.4 (15608.4.9.1.3)
* Operating System: macOS Catalina 10.1.5.2
* Filters you use in AdGuard: all that are marked as # recommended

### Expected Behavior
I don't know if this is expected behavior, but I would like to see embedded twitter tweets on the websites I visit.

### Actual Behavior
Embedded twitter tweets are not shown or shown shortened or as text only.

### Additional Information
The problem is not occurring when deactivating Safari - Preferences - Extensions - AdGuard Social.

It can easily be tested on multiple websites, e.g.
- containing multiple embedded tweets
[https://www.sport1.de/fussball/bundesliga/2020/01/bundesliga-mit-leipzig-gladbach-frankfurt-live-im-tv-stream-und-ticker](https://www.sport1.de/fussball/bundesliga/2020/01/bundesliga-mit-leipzig-gladbach-frankfurt-live-im-tv-stream-und-ticker)
- containing one embedded tweet in the middle
[https://www.nba.com/article/2020/01/24/when-nba-players-get-mentioned-rap-songs](https://www.nba.com/article/2020/01/24/when-nba-players-get-mentioned-rap-songs)

I don't know if this is intentional when the specified extension is enabled or if it is a rule issue.

If or if not a rule issue I'd like to know if the following user rules are the correct way and correct syntax to allow embedded twitter tweets specifically.

```
### unblock embedded twitter
# per domain
@@/tweets.json$domain=nba.com
@@/tweets.json$domain=sport1.de

# for all websites
@@||platform.twitter.com/widgets.js (not actually needed right now)
@@||syndication.twimg.com/tweets.json?*

# or for all websites
@@/tweets.json
```

Websites have to be reloaded or cache cleaned after applying the rules, but they are all working.

So there are three questions:

1. Is the syntax of the above rules correct (they are working) or do they have to be optimized to have the latest supported syntax and to avoid side effects (unblocking stuff that should not be unblocked)?

2. Is this a rule issue or intended behavior? 

3. Is there already a place (wiki, documentation) where these kind of working examples can be found by other users? It took me quite some time to figure them out with the help of the documentation and some google searching. But I did not find a place containing these kind of working rules with up-to-date syntax.

As it seems to concern rules feel free to move the issue to the correct place inside the Adguard GitHub development.

Thanks for looking into it. 

Kind regards.

**Comment by Alex-302** [comment]
We don't block embed tweets. Our rule is domain specific:
`||platform.twitter.com/widgets.js$domain=...`
@tiiiecherle please send report using AdGuard.

**Comment by tiiiecherle** [comment]
@Alex-302 Thanks, but please reopen the issue.

AdGuard for Safari does not have a feature to send a bug report via the app.

The issue is clearly reproducible on multiple macs.

In Safari all extensions are activated.

Activated filters:
- AdGuard Basis-Filter
- AdGuard Spyware-Filter
- AdGuard Social-Media-Filter
- AdGuard Ärgernis-Filter
- Fanboy's Annoyances
- AdGuard Deutscher Filter

It would be nice if the issue could be solved. If you need more information please let me know.

Additionally it would be nice to get a feedback to the syntax and the rules I implemented to work around the issue.

**Comment by slavaleleka** [comment]
@tiiiecherle 
the embedded tweets are blocked by Fanboy's Annoyances. we can't fix filter list which is not ours, but I'll report them

for now you may disable that filter list or just add such rule
`@@||syndication.twimg.com/tweets.json`

and you definitely should not disable AdGuard Social in Safari preferences

**Comment by tiiiecherle** [comment]
@slavaleleka 


> the embedded tweets are blocked by Fanboy's Annoyances. we can't fix filter list which is not ours, but I'll report them

thanks a lot

> for now you may disable that filter list or just add such rule
> `@@||syndication.twimg.com/tweets.json`

thanks, this one is working

> and you definitely should not disable AdGuard Social in Safari preferences

o.k., I only did that for testing purposes to track down the issue

**Comment by ryanbr** [comment]
What url is being blocked? we have the following whitelisted already:

`fanboy-addon/fanboy_social_whitelist.txt:@@||syndication.twitter.com/tweets.json?*&callback=$script`
`fanboy-addon/fanboy_social_whitelist.txt:@@||syndication.twitter.com/tweets.json?callback=$script`
`fanboy-addon/fanboy_social_whitelist.txt:@@||twimg.com/tweets.json?*callback$script`

**Comment by tiiiecherle** [comment]
@ryanbr 
Thanks for looking into it.
As stated above the confirmed working rule incl. URL is
`@@||syndication.twimg.com/tweets.json`

I don't know if there have to be more specifications for the fanboy whitelist after the `tweets.json`.

**Comment by tiiiecherle** [comment]
@ryanbr 
Thanks for adding the entry to the whitelist. 

Unfortunately
`@@||twimg.com/tweets.json`
does not work.

But
`@@||syndication.twimg.com/tweets.json`
does work.

I imported the latest version of 
`https://raw.githubusercontent.com/easylist/easylist/master/fanboy-addon/fanboy_social_whitelist.txt`
manually and the embed tweets still get blocked.

Would be nice if you could add the respective change. Thanks

**Comment by ryanbr** [comment]
This seems to be a bug in Adguard? Does it not understand what subdomains are?

**Comment by tiiiecherle** [comment]
Sorry, I don't know. Let's get back to the AdGuard Team for an answer.
@ameshkov 
@Alex-302 
@slavaleleka

**Comment by slavaleleka** [comment]
@ryanbr that's Safari issue, it matches only one level of subdomains

as far as `cdn.syndication.twimg.com/tweets.json` should be whitelisted, 
rule `@@||twimg.com/tweets.json` cannot be applied in Safari because there is two levels of subdomains

**Comment by Alex-302** [comment]
Added exclusion for Safari.

**Comment by tiiiecherle** [comment]
Thanks, it's working now ;)
