### ISSUE TITLE
adblock detect on in.gr

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardFilters#48694]
https://www.in.gr/2020/01/27/sports/basketball/kompi-mpraiant-anatrixiastiko-tweet-gia-ton-thanato-tou-kai-ta-erotimatika/

adblock detected  message in the middle of the page (possible glomex video)

**Comment by AdamWr** [comment]
I can't reproduce this issue on Android and Windows.

Please fill the template.

**Comment by patrickdrd** [comment]
oops, sorry I've got this issue on android, isn't for android here?

**Comment by AdamWr** [comment]
Thank you for your reply, but I still can't reproduce it with the same filters enabled.

<details><summary>Screenshot</summary>

![Screenshot_20200127-103140_Chrome](https://user-images.githubusercontent.com/29142494/73163692-c2a2cf80-40f0-11ea-8ae2-7cf1a90a8591.jpg)

</details>

As I understand, you mean this video player - [Link](https://player.glomex.com/integration/1.217.0/iframe-player.html?origin=fullpage&pageUrl=https%3A%2F%2Fplayer.glomex.com%2Fintegration%2F1.217.0%2Fiframe-player.html%3Forigin%3Dfullpage%26pageUrl%3Dhttps%253A%252F%252Fplayer.glomex.com%252Fintegration%252F1.217.0%252Fiframe-player.html%253Forigin%253Dfullpage%2526pageUrl%253Dhttps%25253A%25252F%25252Fplayer.glomex.com%25252Fintegration%25252F1.217.0%25252Fiframe-player.html%25253Forigin%25253Diframe%252526pageUrl%25253Dhttps%2525253A%2525252F%2525252Fwww.in.gr%2525252F2020%2525252F01%2525252F27%2525252Fsports%2525252Fbasketball%2525252Fkompi-mpraiant-anatrixiastiko-tweet-gia-ton-thanato-tou-kai-ta-erotimatika%2525252F%252526integrationId%25253D4059a013k56vb2yd%252526playlistId%25253Dv-c06d3sxanio1-se%252526playlistIndex%25253D0%2526integrationId%253D4059a013k56vb2yd%2526playlistId%253Dv-c06d3sxanio1-se%2526playlistIndex%253D0%26integrationId%3D4059a013k56vb2yd%26playlistId%3Dv-c06d3sxanio1-se%26playlistIndex%3D0&integrationId=4059a013k56vb2yd&playlistId=v-c06d3sxanio1-se&playlistIndex=0)

@AdguardTeam/filters-maintainers Could you please check it?

**Comment by patrickdrd** [comment]
there's my screenshot:
![image](https://user-images.githubusercontent.com/24896778/73165020-b4a67c00-40fb-11ea-9120-edb4af798b2a.png)

**Comment by zloyden** [comment]
Also not reproduced on my Android device. Which filter causes it?

**Comment by patrickdrd** [comment]
when I click on the video link,
firstly it shows the adblock message and then this video is not available :S

**Comment by zloyden** [comment]
Turn off filters and on them one by one to find a conflict.
On my end video shows without anti-adblock message.

**Comment by BlazDT** [comment]
https://player.glomex.com/integration/1.217.0/iframe-player.html?origin=fullpage&pageUrl=https%3A%2F%2Fplayer.glomex.com%2Fintegration%2F1.217.0%2Fiframe-player.html%3Forigin%3Dfullpage%26pageUrl%3Dhttps%253A%252F%252Fplayer.glomex.com%252Fintegration%252F1.217.0%252Fiframe-player.html%253FintegrationId%253D4059a013k56vb2yd%2526playlistId%253Dv-c06d3sxanio1-se%26integrationId%3D4059a013k56vb2yd%26playlistId%3Dv-c06d3sxanio1-se%26playlistIndex%3D0&integrationId=4059a013k56vb2yd&playlistId=v-c06d3sxanio1-se&playlistIndex=0

Please try to enable German filter and update. If you do not see any detection anymore, we have to move Glomex rules to English filter.

**Comment by patrickdrd** [comment]
I disabled everything, I don't know what happens,
I even disabled adguard.. still nothing,
video refuses to display..

**Comment by Alex-302** [comment]
try in clean portable browser

**Comment by patrickdrd** [comment]
do you mean for windows?
my issue is on android..

**Comment by Alex-302** [comment]
> I even disabled adguard.. still nothing,



> my issue is on android..

try another browser.
