### ISSUE TITLE
rtl.de - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4870]
***Site***: http://www.rtl.de/cms/index.html
***Description***: Just compare the screenshots. The links should be ordered in three rows, but are just in one.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25364583/b5cca63e-2963-11e7-8f36-f4eb6403d81f.png)

![image](https://cloud.githubusercontent.com/assets/10995998/25364604/dab49b1e-2963-11e7-87e6-3771eb26d9d4.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.346.1819
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.15.51
Spyware filter | 1.0.11.68
Social media filter | 1.0.18.99
Annoyances filter | 1.0.12.18
German filter | 1.0.33.21
Mobile ads filter | 1.0.8.9
Safari filter | 1.0.2.94

**Comment by seanl-adg** [comment]
Not reproduced.

**Comment by danidoedel** [comment]
Hmm it's the rule `rtl.de##div[class^="rtlde-medium-rectangle"]` in Mobile ads filter. Forgot to turn it off on my desktop pc. But the issue is the same on iPad (still a mobile device ;) ), maybe it's somehow related to the screen size?

**Comment by seanl-adg** [comment]
I guess so, it seems that something they are using to arrange tiles are misbehaving if one of tiles is hidden.
Removed the rule hiding the tile and added a rule to hide childs of the tile, and set other CSS to remove visual left overs.
