### ISSUE TITLE
http://www.ukrlit.vn.ua ads

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4871]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

When you follow this link http://www.ukrlit.vn.ua/lib/stus/y1uzd.html, lot's of ads appear in Google chrome browser.  
http://prntscr.com/f0i6tl
http://prntscr.com/f0i75i

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Google Chrome
Adguard version: | 2.9
Adguard driver (Windows): | WFP 
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On
Adguard filters: |  2, 3, 4, 14, 1, 6, 11 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1547925

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
