### ISSUE TITLE
Spotify cannot connect with the DNS filtering enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4872]
1:02 pm Spotify failed to connect to server while Adguard vpn was on, check logs here: 1546721

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Adguard version: | 1.2.1.71
Adguard DNS: | Default
Adguard filters: | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 2 3 4 11 12 14

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
` Spotify failed to connect to server` - so Spotify can't connect in general, or it connects after few attempts?
```
1:42-1:44 Spotify still doesn't
```
I don't see this time stamp in the log. 
Please ask to enable filtering log in system wide filtering, reproduce the issue and refresh the lig by swipe.
Red records are blocked domains. I need screenshots.
