### ISSUE TITLE
Unblocked ad on the website - computerworld.ru

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#4873]
Screenshot:

![screen shot 2017-04-25 at 17 37 39](https://cloud.githubusercontent.com/assets/27292111/25391019/da6366d4-29dd-11e7-9e38-1c5033480f13.png)

***Steps to reproduce the problem***:

http://www.computerworld.ru/news/Minekonomrazvitiya-predlagaet-provodit-EGE-po-tehnologiyam

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard driver (Windows): | WFP
Adguard filters: | 1 2 3 4 5 14

Ticket ID: 1233346

**Comment by Alex-302** [comment]
Fixed
