### ISSUE TITLE
http://ad.nl - site with ads

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4877]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://ad.nl - site with ads

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/f1cgmh

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.2.1
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.0.87.5 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.6.38 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.10.31 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.0.80 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.8.78 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.0.67 Enabled=YES
ID=101 Name="EasyList" Version=1.0.59.70 Enabled=YES
ID=106 Name="EasyList Dutch" Version=1.0.60.39 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1317551

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I don't see this element even without ad blocker.

**Comment by Alex-302** [comment]
@seanl-adg please take a look.
Added to Annoyances filter
```
ad.nl#@#.cookiewall
```

**Comment by seanl-adg** [comment]
Not reproduced on my end.
