### ISSUE TITLE
https://gomovies.to/ - site with ads

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4880]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://gomovies.to/ - site with ads

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/f1dzsj

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.2.1.71
Optimazed enabled: NO
Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.1.15.74 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.11.76 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.19.7 Enabled=YES

ID=14 Name="Annoyances filter" Version=1.0.12.21 Enabled=YES

ID=16 Name="French filter" Version=1.0.1.77 Enabled=YES

ID=5 Name="Experimental filter" Version=1.0.26.61 Enabled=YES

ID=11 Name="Mobile Ads filter" Version=1.0.8.12 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.2.94 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1549225

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
gomovies.to##.ann-home.alert
```
