### ISSUE TITLE
http://www.tomsk.ru - distorted view

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4882]
http://www.tomsk.ru/

![image](https://cloud.githubusercontent.com/assets/15856304/25482383/3a0992d4-2b5a-11e7-92be-b31dbe531dfc.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None
Adguard filters: | Russian, English, Social media, Spyware, Mobile ads, Safari, 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID (if exists): 1549338

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
