### ISSUE TITLE
macrumors.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4883]
***Site***: https://www.macrumors.com/
***Description***: Newsletter banners. Rules for Annoyance filter: 

```
macrumors.com##.newsletter
macrumors.com##.follow-banner
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25484256/97c22c34-2b59-11e7-8250-c0d58d52adef.png)

![image](https://cloud.githubusercontent.com/assets/10995998/25484278/a6a7a710-2b59-11e7-81bb-3bf975c4a74b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.346.1819
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.15.83
Spyware filter | 1.0.11.76
Social media filter | 1.0.19.7
Annoyances filter | 1.0.12.23
German filter | 1.0.33.31
Mobile ads filter | 1.0.8.14
Safari filter | 1.0.2.94

**Comment by Alex-302** [comment]
Ok.
