### ISSUE TITLE
sat1.de - Ad leftover - Social widget leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4885]
***Site***: http://www.sat1.de/ / http://www.sat1.de/tv/das-grosse-backen-promispezial/video/13-die-reihen-lichten-sich-ganze-folge
***Description***: Ad leftover at the top and right. Social widget leftover below videos.

Rule for German filter:

```
sat1.de##.ad
```

Rule for Social filter:

```
sat1.de##.social-wrapper
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25488888/84243988-2b68-11e7-8d33-c793c0f0f4fd.png)

![image](https://cloud.githubusercontent.com/assets/10995998/25488866/6eb5cc24-2b68-11e7-8a61-992dbb1a0c60.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.346.1819
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.15.83
Spyware filter | 1.0.11.76
Social media filter | 1.0.19.7
Annoyances filter | 1.0.12.23
German filter | 1.0.33.31
Mobile ads filter | 1.0.8.14
Safari filter | 1.0.2.94

**Comment by Alex-302** [comment]
Added
