### ISSUE TITLE
kp.by - Anti Adblocker

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4887]
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screenshot_1](https://cloud.githubusercontent.com/assets/22892774/25500550/19ac4084-2b98-11e7-9597-dd61bbbc29f9.png)

</details>

***Steps to reproduce the problem***:

Go to:
http://www.kp.by/daily/26663.3/3683152/

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.2.356.1877
Adguard filters: | 1 2 3 4 5 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1498653

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by Yana-SUP** [comment]
works fine for me now... emailed the user, will update the task
