### ISSUE TITLE
pinterest.com - Question

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4888]
***Description***:

Can ADG block pop-ups on the bottom like on my screenshots?

Screenshot:

<details>

![screenshot_2](https://cloud.githubusercontent.com/assets/22892774/25500934/8daa6f64-2b99-11e7-99de-831cfa70d558.png)

</details>

<details>

![screenshot_3](https://cloud.githubusercontent.com/assets/22892774/25500942/94669878-2b99-11e7-92ab-e81669e3041a.png)

</details>

***Steps to reproduce the problem***:

1) Go to:
https://www.pinterest.com/explore/chernobyl-radiation/

2) Scroll down to the bottom, a new black window appears.

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.2.356.1877
Adguard filters: | 1 2 3 4 5 14

Ticket ID 1498653

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
No, we can't do it on this site. In some cases they are show just screenshot of the page as background.
