### ISSUE TITLE
studychacha.com - Anti Adblocker

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4889]
Go to:
http://studychacha.com/discuss/136455-list-aicte-approved-universities-kolkata.html

Screenshot:

<details>

![screenshot_4](https://cloud.githubusercontent.com/assets/22892774/25502476/58144482-2b9f-11e7-8605-da8e3cc69a59.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.2.356.1877
Adguard filters: | 1 2 3 4 5 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID 1543128

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Fixed
