### ISSUE TITLE
imore.com - Ad leftover - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4890]
***Site***: http://www.imore.com/ / http://forums.imore.com/rumored-apple-hardware-software/386261-how-fast-iphone-8-a.html
***Description***: Menu on main page won't open. Ad leftover in forums.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25525887/60114988-2c11-11e7-8e8d-2290e847a402.png)

![image](https://cloud.githubusercontent.com/assets/10995998/25525716/7bbde610-2c10-11e7-8503-bb9e89aa6d84.png)

![image](https://cloud.githubusercontent.com/assets/10995998/25525808/ea914686-2c10-11e7-9eb6-2bd77be87753.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.356.1877
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.15.95
Spyware filter | 1.0.11.79
Social media filter | 1.0.19.14
Annoyances filter | 1.0.12.29
German filter | 1.0.33.33
Mobile ads filter | 1.0.8.14
Safari filter | 1.0.2.96

**Comment by Alex-302** [comment]
> Menu on main page won't open

It doesn't work even without Adguard.

> Ad leftover in forums.

not reproduced. Check this
```
forums.imore.com##.adunit
```

**Comment by danidoedel** [comment]
> It doesn't work even without Adguard.

@Alex-302 For me it does work without Adguard.

> not reproduced. Check this

Yeah that's better, but there is still some small leftover then:

![image](https://cloud.githubusercontent.com/assets/10995998/25579308/087412e2-2e77-11e7-88b4-24f50e9329c0.png)

Not sure if that can be removed too...

**Comment by Alex-302** [comment]
@danidoedel 

> For me it does work without Adguard.

which filter breaks it?



> but there is still some small leftover then:

added
forums.imore.com##.posts > div.mn_postbit_ab

**Comment by AdamWr** [comment]
It seems, that now menu on main page works normally, but I added rules to hide ads leftovers on forum.
