### ISSUE TITLE
news.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4891]
***Site***: http://www.news.de/
***Description***: Various ad leftovers.

<details>
<summary>Screenshot</summary>

Ad leftover in article on mobile devices:

http://m.news.de/sport/855664316/fc-bayern-muenchen-news-carlo-ancelotti-bleibt-trainer-wechsel-transfer-aktuell/1/

![image](https://cloud.githubusercontent.com/assets/10995998/25525977/d9d411ec-2c11-11e7-9c3b-088d9654c3a3.png)

Ad leftover at the top:

http://www.news.de/

![image](https://cloud.githubusercontent.com/assets/10995998/25526002/ed04356c-2c11-11e7-841e-de735f6c7e4d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.356.1877
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.15.95
Spyware filter | 1.0.11.79
Social media filter | 1.0.19.14
Annoyances filter | 1.0.12.29
German filter | 1.0.33.33
Mobile ads filter | 1.0.8.14
Safari filter | 1.0.2.96

**Comment by Alex-302** [comment]
added:
```
news.de##.cc_banner-wrapper
news.de#$#.wrapper { padding: 0px 15px!important; }
m.news.de##p.articleTeaser+div[style="height: 500px"]
```
