### ISSUE TITLE
https://de.m.xhamster.com - pop-under

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4892]
https://de.m.xhamster.com

![image](https://cloud.githubusercontent.com/assets/15856304/25545747/d8535ef2-2c68-11e7-8a51-377386597502.png)

Opens on a click on any video.

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | the latest one
Adguard DNS: | Default
Adguard filters: | 2 3 4 6 11 12 14 15 16

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1480792

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is impossible on iOS, it doesn't support JS rules.
