### ISSUE TITLE
pietsmiet.de - incorrect blocking

### ISSUE THREAD

**Issue by YoKoGFX** [AdguardTeam/AdguardFilters#4893]
The ads are not blocked on www.pietsmiet.de
![img_0369](https://cloud.githubusercontent.com/assets/18743976/25546292/afb79d88-2c62-11e7-812c-281f7d68c8c5.PNG)

System: iOS 10.3.2 Beta 5

**Comment by Alex-302** [comment]
Added to German filter
```
@@/ad_bomb/*$image,domain=pietsmiet.de
```
