### ISSUE TITLE
planetapk.net - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4894]
Screenshot:

<details>

![yoa94u88pbc](https://cloud.githubusercontent.com/assets/22892774/25547335/4ebbab02-2c6f-11e7-9e4c-2217f290659e.jpg)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Chrome
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard filters: | 2 3 4 5 11 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID 1516731

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Fixed
