### ISSUE TITLE
Некорректная блокировка - tickets.fc-zenit.ru

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#4895]
***Description***:
* **Current behaviour**: 

При включенном Adguard переход на следующую страницу при выборе места и покупке билета невозможен 

Screenshot:

![image](https://cloud.githubusercontent.com/assets/27292111/25554652/14db970a-2cdb-11e7-8380-014f3e927213.png)

***System configuration***
Application version: 1.2.1.71
Platform: iOS
OS: 10.3.1

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.16.8 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.81 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.17 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.50.49 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.96 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.41 Enabled=NO

Ticket ID: 1550888

**Comment by Alex-302** [comment]
В белый список нужно добавить
```
mc.yandex.ru
```
Добавил в фильтр аналитики
```
@@||mc.yandex.ru/metrika/watch.js$domain=tickets.fc-zenit.ru
```

**Comment by veronikasav** [comment]
Поняла, спасибо
