### ISSUE TITLE
Adguard dns detected in erai-raws.info and thair public download server

### ISSUE THREAD

**Issue by Ahmed0425** [AdguardTeam/AdguardFilters#48966]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 
Adguard DNS is detected as adblocker on erai-raws.info and their public download server
[//]: # (Substitute this line with a description of the problem)
they use blockadblock script to detect adblockers
[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url
![image](https://user-images.githubusercontent.com/25909799/73525540-10cd1100-4418-11ea-9d53-36ac9efbc3c7.png)
%)
</details><br/>

* **Expected behaviour**: 
there is anti adblock defuser filters so this should not happen
[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows
Operating system version (Android/iOS) | Windows10
Browser:                               | Firefox
AdGuard version:                       | DNS
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | Default
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.
Please show `nslookup erai-raws.info` with and without AdGuard.

**Comment by Ahmed0425** [comment]
without adguard:

> Server:  dns-cache.tedata.net
> Address:  163.121.128.134
> 
> Non-authoritative answer:
> Name:    erai-raws.info
> Address:  185.178.208.178

with adguard:

> Server:  176-103-130-130.dns.adguard.com
> Address:  176.103.130.130
> 
> Non-authoritative answer:
> Name:    erai-raws.info
> Address:  185.178.208.178

**Comment by Alex-302** [comment]
Weird. The same IP returned in both cases.
Please check with Google DNS, and/or try to disable privacy options in Firefox(just for test).

**Comment by Ahmed0425** [comment]
here

> Server:  dns.google
> Address:  8.8.8.8
> 
> Non-authoritative answer:
> Name:    erai-raws.info
> Address:  185.178.208.178

**Comment by Alex-302** [comment]
`Address: 185.178.208.178` in both cases. This means that domain is not blocked.
