### ISSUE TITLE
Leo APP ads

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardFilters#4898]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

Annoying/distracting ad in LEO app
https://play.google.com/store/apps/details?id=org.leo.android.dict

When you download the application, a small banner appears in the bottom part of the page
as here http://prntscr.com/f2jcag

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On
Adguard filters: | English, Spyware, Social media filter, Experimental, Annoyances filter, Mobile ads filter
[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(1432325): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||dict.leo.org/api/mobile/production/hello/adb/0?b=$replace=/\/adv_pda" rel="nofollow"><img width=/\\/adv_pda" rel="nofollow"><im_ width=/i
||dict.leo.org/api/mobile/production/hello/adb/0?b=$important,replace=/\/adv_pda" rel="nofollow"><img width=/\\/adv_pda" rel="nofollow"><im_ width=/i

```
