### ISSUE TITLE
codecamps.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#48983]
[https://www.codecamps.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.codecamps.com/)

![cookies](https://user-images.githubusercontent.com/35470489/73554568-c0ab7a00-442a-11ea-8e67-41e704df5804.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by krystian3w** [comment]
`###___gatsby > div > div > div[class*="Cookies__Wrapper"]`

@kiboke?
