### ISSUE TITLE
dzone.com - pop-up for email subscriptions

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4900]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/26434103/25569211/32e956ce-2e1b-11e7-9170-da8babc814f7.png)

***System configuration***

Platform: iOS
OS: 10.3.1
Adguard filters: | 2 3 4 5 12 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1338750

**Comment by seanl-adg** [comment]
Should be resolved. Please check.
