### ISSUE TITLE
com.makonda.blic app - false blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4901]
I have problem with showing video on Blic app (https://play.google.com/store/apps/details?id=com.makonda.blic )
Just seeing the symbol for playing but cannot start. When I switch off Adguard ads filtering and https filtering for that app, it works.

<details>

with adguard

![image](https://cloud.githubusercontent.com/assets/15856304/25577164/e87bb260-2e6c-11e7-885f-65b7f8902a28.png)

w/out adguard

![image](https://cloud.githubusercontent.com/assets/15856304/25577170/f232ecba-2e6c-11e7-9811-50a1b0610656.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | high-speed
HTTPS filtering (Android): |  On Default
Adguard DNS: | Default
Adguard filters: | 2, 3, 14, 10, 1, 6, 7, 8, 9, 13, 5, 11, 15, 102, 103, 104, 105, 108, 109, 111, 112, 113, 114, 121, 116, 222, 216, 217, 211, 218, 223, 226, 224, 227 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1529320

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
He uses ALL filters. Please ask for disabling really unnecessary filters and check again.

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$app=com.makonda.blic
```
Please check.
