### ISSUE TITLE
bewerbung.co - Ad - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4902]
***Site***: https://bewerbung.co/muster/muster-1
***Description***: Login with XING button is missing. Ads not blocked.

<details>
<summary>Screenshot</summary>

After pressing one of these buttons, the following login button is missing:

![image](https://cloud.githubusercontent.com/assets/10995998/25579464/6dedcfae-2e78-11e7-972e-ef070b5853d2.png)

With button:

![image](https://cloud.githubusercontent.com/assets/10995998/25579407/0b228dc4-2e78-11e7-909c-25ef3d70df8f.png)

Missing button:

![image](https://cloud.githubusercontent.com/assets/10995998/25579394/ede4ab7a-2e77-11e7-86d7-f72db458e0bb.png)

Ads not blocked:

![image](https://cloud.githubusercontent.com/assets/10995998/25579561/517bc01e-2e79-11e7-9a7b-08daae29ffa7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.15.95
Spyware filter | 1.0.11.79
Social media filter | 1.0.19.14
Annoyances filter | 1.0.12.29
German filter | 1.0.33.33
Mobile ads filter | 1.0.8.14
Safari filter | 1.0.2.96

**Comment by Alex-302** [comment]
Fixed

**Comment by danidoedel** [comment]
@Alex-302 Thank you! The button is now fixed. But after you logged in you are not able to download the documents with these buttons, instead the login page opens again and this button is missing:

![image](https://cloud.githubusercontent.com/assets/10995998/25619179/3e745ef0-2f4a-11e7-979f-68b2db6a53b7.png)

The rule `||xing-share.com^$third-party` in Social filter seems to break this functionality.

**Comment by Alex-302** [comment]
Show blocked xing-share.com requests

**Comment by danidoedel** [comment]
@Alex-302 

Log with `||xing-share.com^$third-party` active:

![image](https://cloud.githubusercontent.com/assets/10995998/25625006/88adefd4-2f5b-11e7-8c8a-c982fdc791fc.png)

Log with `@@||xing-share.com^$third-party` active in user filter:

![image](https://cloud.githubusercontent.com/assets/10995998/25625009/8e8790e0-2f5b-11e7-8fb3-c6e4d6726e5e.png)

In the second log you can see that `https://www.xing-share.com/assets/spi/message_proxy-f7ffdd55d3e0e7290d5938bbe4750aa4.js` is unblocked by `@@||xing-share.com^$third-party`, but in the first log it's not shown as blocked... seems a bit odd...

**Comment by Alex-302** [comment]
I mean only blocked requests without additional rules
http://i91.fastpic.ru/big/2017/0503/f6/1355885226931770fbd3e0d82e8f42f6.jpg

**Comment by AdamWr** [comment]
Fixed.
Please, check the result.

**Comment by danidoedel** [comment]
It's works now. Thank you! 👍
