### ISSUE TITLE
gutefrage.net - Ad leftover - iOS

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4904]
***Site***: http://www.gutefrage.net/frage/wie-streame-ich-bei-obs-auf-gpu
***Description***: Ad leftover at the bottom.

Rule for German filter:
`gutefrage.net###anchor-ad`

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25600185/a2b8736e-2ee2-11e7-8ce3-2cf9ad144407.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.356.1877
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.16.38
Spyware filter | 1.0.11.83
Social media filter | 1.0.19.17
Annoyances filter | 1.0.12.32
German filter | 1.0.33.43
Mobile ads filter | 1.0.8.20
Safari filter | 1.0.2.98

**Comment by Alex-302** [comment]
Added to Mobile filter
```
gutefrage.net##.AdSticky
```
