### ISSUE TITLE
https://download-apple-ringtones-free.mobilesringtones.com/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4906]
![image](https://cloud.githubusercontent.com/assets/15856304/25609008/ee4373b8-2f25-11e7-909a-67679fcd43ae.png)

https://download-apple-ringtones-free.mobilesringtones.com/download1.php?f=m4r%20ringtones.mp3&id=11829

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.2.346.1819
Adguard driver (Windows): | WFP
Adguard DNS: | Default
Adguard filters: | 2 3 4 10 14 207 211

Stealth Mode enabled: StealthModeSettings: {

-   "BlockThirdPartyCookies": true,
-   "BlockThirdPartyCookiesPeriodMin": 30,
-   "BlockFirstPartyCookies": false,
-   "BlockFirstPartyCookiesMin": 2880,
-   "DisableThirdPartyCache": false,
-   "BlockWebRtc": false,
-   "BlockBrowserPushApi": false,
-   "BlockBrowserLocationApi": true,
-   "RemoveXClientDataHeader": true,
-   "HideSearchQueries": true,
-   "SendDoNotTrackHeader": true,
-   "RemoveRefererFromThirdPartyRequests": false,
-   "HideUserAgent": false,
-   "CustomUserAgent": null,
-   "CustomReferer": null,
-   "HideIp": false,
-   "CustomIp": "209.141.53.254"
- 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists):  1551910

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
