### ISSUE TITLE
http://elsfile.net/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4907]
http://elsfile.net/kmbwzvhjqa6w

![image](https://cloud.githubusercontent.com/assets/15856304/25611656/8e7b6890-2f30-11e7-8d97-02bda200a0c7.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Adguard DNS: |  Default
Adguard filters: | english, spyware, annoyances, social media, experimental, mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1551511

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
