### ISSUE TITLE
rufilmtv.org - Некорректная блокировка

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#4908]
***Description***:
Перед просмотром видео появляется реклама. 

Screenshot:

![image](https://cloud.githubusercontent.com/assets/27292111/25627323/dbca8fe2-2f6a-11e7-87db-98be081af512.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Яндекс 
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP 
Adguard filters: | 1 2 3 4 5 14

Ticket ID: 677335

**Comment by Alex-302** [comment]
Вроде поправил.
