### ISSUE TITLE
Missed ads in Translate.ru app

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#4909]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/27292111/25628692/da1a2798-2f6f-11e7-9d27-919d63ee8dfa.png)

***System configuration***

Information | value
--- | ---
Operating system: |  Android 6.0.1
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On
Adguard filters: | 2 3 4 14 10 1 11

Ticket ID: 1444709

[adguard.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/971102/adguard.har.zip)

**Comment by Alex-302** [comment]
У меня не повторилось. Сторонняя реклама блокируется, но есть встроенная заглушка с рекламой Promt Offline, её не убрать.
Передай на проверку:
```
||rt.applovin.com^
||a.applvn.com^
```

**Comment by KozelElena** [comment]
Передам.
Сейчас получили информацию, что такая же проблема с другим приложением: Star Music Tag Editor.

https://play.google.com/store/apps/details?id=com.music.star.startag&hl=ru

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25731642/b3e51726-3150-11e7-8fd2-7fa9d00c01af.png)

</details>

**Comment by Alex-302** [comment]
Это другая - фейсбучная реклама.

**Comment by Alex-302** [comment]
Открой отдельную задачу с информацией о настройках.

**Comment by vmalyuta** [comment]
добавил правила - не помогло

**Comment by Alex-302** [comment]
Тогда нужен HAR и лог запросов после остановки и очистки кэша приложения.

**Comment by KozelElena** [comment]
Лог и HAR в 1444709. Посмотрите, пожалуйста

**Comment by KozelElena** [comment]
Дополнительно вопрос:

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25795047/3fa99f4c-33dc-11e7-95b8-7e82275120d1.png)

</details>

Насчёт окна с надписью "Реклама" в приложении Translate.ru - второй
скриншот. Сначала появляется вшитая реклама про Promt Offline, а через
некоторое время белое окошко с надписью "Реклама". Это так и должно быть?

**Comment by Alex-302** [comment]
Ну это заглушка просто. Она встроена.
