### ISSUE TITLE
Incorrect blocking on the page - mobile.flypgs.com

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#4910]
***Description***:
* **Current behaviour**: 

Adguard blocks the page totally. A nonspam SMS message comes.

Screenshot:

![image](https://cloud.githubusercontent.com/assets/27292111/25631539/63e59454-2f79-11e7-9511-2ababc7d879c.png)

![image](https://cloud.githubusercontent.com/assets/27292111/25631562/6e46ccd8-2f79-11e7-9e9c-7948cb3ac161.png)

***System configuration***

Device: iPhone
Platform: iOS
OS: 10.3.1

Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.16.20 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.81 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.31 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.1.3 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.7.43 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.16 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.96 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.41 Enabled=YES

Ticket ID: 1495398

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||mobile.flypgs.com/tealeaf.js
```
