### ISSUE TITLE
zfilm-hd.club - Anti-adblock + missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#4911]
Description:
Open any video at zfilm-hd.club. There is a timer for 15 sec with black screen and skip ad button.

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/27292111/25652884/080da96c-2ff3-11e7-8619-5c5c43275f7b.png)

![image](https://cloud.githubusercontent.com/assets/27292111/25652895/16398e16-2ff3-11e7-9cf1-99cdfe4afdfe.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.1 / 1.4.1
Adguard driver (Windows): | WFP 
Adguard filters: | 1 2 3 4 5 14

Ticket ID: 1552507

**Comment by Alex-302** [comment]
Fixed
