### ISSUE TITLE
kino-live.red - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4912]
http://kino-live.red/715727034-gavayi-5-0-policiya-gavayev.html
chrome browser extension and Adguard 1.4.1
ru en social media annoyances malware

![screenshot 2017-05-03 13 14 55](https://cloud.githubusercontent.com/assets/23637588/25656639/b00be08e-3002-11e7-99bc-35fad2eac8c1.png)

**Comment by Alex-302** [comment]
Fixed
