### ISSUE TITLE
isla-eden.co.uk - Unblocked pop-up

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#4913]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

Unblocked pop-up in the bottom of the sceen even during scrolling
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

![screen shot 2017-05-03 at 12 53 25 pm](https://cloud.githubusercontent.com/assets/27292111/25658796/5c7839e4-300d-11e7-8fa9-360e8f02597e.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome / Pale Moon / Internet Explorer
Adguard version: | 6.1.3 / 1.4.1 
Adguard driver (Windows): | WFP
Adguard filters: | 1 2 3 4 5 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID:1419169 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
