### ISSUE TITLE
http://www.dn.se/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4916]
![image](https://cloud.githubusercontent.com/assets/15856304/25670455/654e5d64-3035-11e7-9f84-818aebb2e3ed.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | the latest 6.2 beta
Adguard driver (Windows): | WFP
Adguard DNS: | Default 
Adguard filters: | eng, russ, annoyances, ...

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1456058

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Fixed.
