### ISSUE TITLE
http://dailygeekshow.com/ - anti-ablocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4917]
http://dailygeekshow.com/baleine-enceinte-norvege/

![image](https://cloud.githubusercontent.com/assets/15856304/25672459/4a99e3d8-303c-11e7-8f15-20a0737d58f1.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 1887 beta
Adguard driver (Windows): | WFP
Adguard DNS: | Default
Adguard filters: | English + Russian + French + Annoyances + Social Media + Spyware (the customer has much larger list)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1021351

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Fixed
