### ISSUE TITLE
desirulez.tv - Anti Adblock Script

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4918]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Our customer is facing issues with Anti adblocking script

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25674003/0fd92352-3042-11e7-81a6-0a971d0cb330.png)

</details>

***Steps to reproduce the problem***:

http://desirulez.tv/

Choose any movie and try play it.

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard driver (Windows): | WFP
Adguard filters: | English, Spyware, Social media, Unblocking useful ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1531498

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It's dead
<details>

![image](http://i33.fastpic.ru/big/2017/0504/76/773fd62324be522d584d5a973bdfdd76.jpg)
</details>
