### ISSUE TITLE
http://www.divyabhaskar.co.in/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4922]
http://www.divyabhaskar.co.in/news/MGUJ-AHM-c-69-cm-vijay-rupani-inaugurate-women-industrial-park-at-sanand-NOR.html?ref=ht

The content is mirrored...

![image](https://cloud.githubusercontent.com/assets/15856304/25700910/836e6882-30d2-11e7-92de-d5659f7c613c.png)

On Android:

![image](https://cloud.githubusercontent.com/assets/15856304/25700970/cbb04e08-30d2-11e7-93bc-e1997f09e3e9.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows. Android
Browser: | Chrome, Samsung Browser
Adguard version: | 6.2 beta, 2.7.9
Adguard driver (Windows): | WFP
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On Default
Adguard DNS: | Default
Adguard filters: | English, Russian, annoyances, Social media, Spyware, Spanish

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1536170

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Fixed
