### ISSUE TITLE
SofaScore app - AdChoices ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4923]
https://play.google.com/store/apps/details?id=com.sofascore.results&hl=ru

![screenshot_20170501-093804](https://cloud.githubusercontent.com/assets/15856304/25702624/8fb9cc50-30da-11e7-9ae8-6b54268049b7.png)

We tried clearing cache multiple times but it didn't help. Here's the har recorded after the cache has been cleared: 1076052

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | 
Adguard version: | 2.9.70
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On Default
Adguard DNS: | false 
Adguard filters: | 2, 3, 4, 14, 10, 16, 11, 113

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Temporary solution
```
||graph.facebook.com^$app=com.sofascore.results
```

**Comment by Alex-302** [comment]
Added
