### ISSUE TITLE
kundenportal.paderenergy.de tracking

### ISSUE THREAD

**Issue by Tibladar** [AdguardTeam/AdguardFilters#49256]
**Description**:

`kundenportal.paderenergy.de` sends details about the used browser and os to `https://kundenportal.paderenergy.de/client_area/client_core/ajax/portal_statistic.php`:

`json: {"deviceType":"Desktop","deviceWidth":[redacted],"deviceHeight":[redacted],"OS":"Windows","OSVersion":"8.1","browserName":"Firefox","browserVersion":"70.0.1","browserDisplayWidth":[redacted],"browserDisplayHeight":[redacted]}`

**Suggestion:** Block the `portal_statistic.php`

**Filters:**

Information                            | Value
---                                    | ---
Browser:                               | Firefox 70.0.1
Filters enabled:                       | Spyware, Social media, Annoyances, English, German, EasyPrivacy, Fanboy's Enhanced Tracking List, AdGuard Tracking Protection

**Comment by BlazDT** [comment]
The site does not have enough visitors for the filter lists.
