### ISSUE TITLE
chip.de - Annoyance - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4925]
***Site***: http://www.chip.de/
***Description***: Cookie notice at the bottom. Newsletter stuff at the bottom. Social widget at the bottom. Annoying unrelated videos below articles.

Rules to block everything mentioned above:

*Rules for Annoyance filter:*
```
chip.de###cookieChoiceInfo
chip.de##section[class^="WidgetNewsletter"]
chip.de##.VideoList
```

*Rule for Social filter:*
```
chip.de##.share-button-container
```

<details>
<summary>Screenshot</summary>

http://www.chip.de/nachrichten:

![image](https://cloud.githubusercontent.com/assets/10995998/25704181/b73382be-30d8-11e7-9cdc-aa5a51b81e14.png)

![image](https://cloud.githubusercontent.com/assets/10995998/25704560/39043ca6-30da-11e7-9a10-2eb1efa3cda6.png)

http://www.chip.de/news/Intel-stuerzt-vom-Thron-Wie-Samsung-den-Chip-Giganten-ueberholt_113960947.html:

![image](https://cloud.githubusercontent.com/assets/10995998/25704612/79767b6e-30da-11e7-9a83-d675e48cc9b6.png)

http://www.chip.de/video/kinox.to-und-Co.-birgt-mehr-Risiko-Video_113660713.html:

![image](https://cloud.githubusercontent.com/assets/10995998/25704990/f47eabaa-30db-11e7-96e5-fd5f0f32b05d.png)

http://www.chip.de/news/Intel-stuerzt-vom-Thron-Wie-Samsung-den-Chip-Giganten-ueberholt_113960947.html:

![image](https://cloud.githubusercontent.com/assets/10995998/25704834/5e4ef95a-30db-11e7-8d1d-6f8f669938b7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.356.1877
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.16.66
Spyware filter | 1.0.11.88
Social media filter | 1.0.19.24
Annoyances filter | 1.0.12.37
German filter | 1.0.33.54
Mobile ads filter | 1.0.8.26
Safari filter | 1.0.3.3

**Comment by Alex-302** [comment]
`#2' Added
1, 3 - not reproduced

**Comment by danidoedel** [comment]
@Alex-302 Hmm for me that stuff is clearly visible, otherwise I wouldn't be able to find these rules ;)
Any way to help to reproduce this issue?

**Comment by AdamWr** [comment]
Added - `chip.de###cookieChoiceInfo`
In my opinion these videos should not be hidden.

**Comment by Alex-302** [comment]
> In my opinion these videos should not be hidden.

I am agree.
