### ISSUE TITLE
which.co.uk - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4927]
***Site***: http://www.which.co.uk/
***Description***: Cookie notice at the top.

*Rule for Annoyance filter:*
`which.co.uk##.eprivacy-banner--displayed`

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25706460/d39de072-30e0-11e7-8cf1-bc2292e0e010.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.356.1877
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.16.66
Spyware filter | 1.0.11.88
Social media filter | 1.0.19.24
Annoyances filter | 1.0.12.37
German filter | 1.0.33.54
Mobile ads filter | 1.0.8.26
Safari filter | 1.0.3.3

**Comment by Alex-302** [comment]
Added
