### ISSUE TITLE
outlook.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#493]
В IE11 если очистить кэш и залогиниться, вкладки не кликаются. Если потом отключить защиту, обновить страницу и включить защиту обратно, то все будет работать как надо, до следующей чистки кэша.

http://forum.adguard.com/showthread.php?5163-Adguard-for-Windows-Beta-version-5-10-2020-6300

**Comment by Alex-302** [comment]
А есть фейковый акк?

**Comment by vbagirov** [comment]
У меня есть. Можешь написать в Скайп, я тебе передам.

**Comment by vbagirov** [comment]
Тут повторяется по-прежнему. Могу в скайп дать логин/пароль.
