### ISSUE TITLE
hifi-forum.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4932]
***Site***: http://www.hifi-forum.de/
***Description***: Ad leftover below header

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25725681/6c3c75d8-3121-11e7-959f-ec6f57b2676d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.356.1877
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.16.75
Spyware filter | 1.0.11.89
Social media filter | 1.0.19.26
Annoyances filter | 1.0.12.42
German filter | 1.0.33.55
Mobile ads filter | 1.0.8.26
Safari filter | 1.0.3.3

**Comment by Alex-302** [comment]
fixed
