### ISSUE TITLE
fitforfun.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4934]
***Site***: http://m.fitforfun.de/
***Description***: Newsletter box at the bottom.

*Rule for Annoyance filter:*
`fitforfun.de##.promotion`

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25727752/4a111180-312b-11e7-860f-eff785d172f3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.356.1877
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.16.75
Spyware filter | 1.0.11.89
Social media filter | 1.0.19.26
Annoyances filter | 1.0.12.42
German filter | 1.0.33.55
Mobile ads filter | 1.0.8.26
Safari filter | 1.0.3.3

**Comment by Alex-302** [comment]
fixed
