### ISSUE TITLE
m.brigitte.de - Annoyance - Social widget - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4936]
***Site***: http://m.brigitte.de/mode/trends/insolvenzverfahren--ist-der-katalog-riese-impressionen-bald-pleite--10924568.html
***Description***: See screenshots.

*Rule for Annoyance filter:*
```
brigitte.de##.newsletterWidget
```

*Rule for German filter:*
```
brigitte.de##.tracdelight-widget
```

*Rule for Social filter:*
```
brigitte.de##.social-sharing-view-wrapper
```

<details>
<summary>Screenshot</summary>

*1. Ad*
*2. Newsletter box*

![image](https://cloud.githubusercontent.com/assets/10995998/25729961/3ef82dac-3139-11e7-93a9-005e13a2bd88.png)

*3. Social widget leftover*

![image](https://cloud.githubusercontent.com/assets/10995998/25730041/f77d3836-3139-11e7-9b32-7c3b72352e82.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.356.1877
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.16.75
Spyware filter | 1.0.11.89
Social media filter | 1.0.19.26
Annoyances filter | 1.0.12.42
German filter | 1.0.33.55
Mobile ads filter | 1.0.8.26
Safari filter | 1.0.3.3

**Comment by Alex-302** [comment]
done
