### ISSUE TITLE
https://xakep.ru - share buttons are not blocked 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4938]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://xakep.ru/2017/05/02/swiftmedia/ - share buttons are not blocked while Social media filter is enabled 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/25734514/8c88ca58-316c-11e7-86cf-42d2c7de50e8.png)

</details>

***System configuration***

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.16.38 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.83 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.17 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.32 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.50.51 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.20 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.98 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.42 Enabled=NO
ID=118 Name="EasyPrivacy" Version=1.0.79.14 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID 1518078

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't reproduce it on iOS and MacOS.
Try
```
~vk.com##a[href^="https://vk.com/share.php"]
~facebook.com##a[href^="http://www.facebook.com/sharer.php?"]
~twitter.com##a[href^="http://twitter.com/share?"]
~plus.google.com##a[href^="https://plus.google.com/share"]
```

**Comment by dzamyshlyayeva** [comment]
Now the share buttons are blocked, but there is a pop up here https://xakep.ru/2017/06/09/nvd-lag/

![image](https://user-images.githubusercontent.com/23372054/27257166-ed884704-53d4-11e7-9b9a-be78fbf2e922.png)

Ticket ID 1518078

**Comment by Alex-302** [comment]
Fixed.
