### ISSUE TITLE
https://www.androidplanet.nl - missed ad 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4939]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:https://www.androidplanet.nl/nieuws/aliexpress-in-nederland/ - missed ad on page 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/25737379/18dcbba0-3180-11e7-93ba-f6f2986af72f.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.2.1.71
Device: iPad
Platform: iOS
OS: 10.3.1
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.16.73 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.89 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.26 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.9.26 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.3 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.45 Enabled=NO

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID 1470731

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Ads are blocked by `/ads.php` from Eng filter on my device.

**Comment by Arnoud-B** [comment]
Checked on iOS/Safari with English filter on (updated 5/5): ads are not blocked.

**Comment by Alex-302** [comment]
Try to add this rule to custom filter.
