### ISSUE TITLE
kp.ru (false positives)

### ISSUE THREAD

**Issue by zolpar** [AdguardTeam/AdguardFilters#4940]
Буду писать сюда, ибо аккаунт на форуме никто не активирует.
Ссылка: http://www.alt.kp.ru/radio/
При использовании только расширения в хроме последней версии пишет:
Мы заметили, что вы используете блокировщик рекламы.
Очень просим отключить его для ALT.KP.RU!
Реклама — основной источник дохода для нас. Без нее мы не сможем оплатить работу журналистов и их командировки.
Не лишайте себя хороших материалов!

(там есть крестик, но искал долго из-за того что он слева)

**Comment by Alex-302** [comment]
Включи фильтр раздражителей.
