### ISSUE TITLE
gtavicecity.ru - ad leftover

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#4942]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: https://www.gtavicecity.ru/gta-san-andreas/gta-san-andreas-cheats-pc.html

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screenshot_2017-05-05-12-17-44](https://cloud.githubusercontent.com/assets/23637588/25740155/f1440658-318d-11e7-980d-2f7df836b0af.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Browser: | chrome yandex firefox
Adguard version: | 2.9
Adguard mode (Android): | VPN / 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Simplified filters(iOS) | Off
Adguard DNS: | None 
Adguard filters: | ru, en, spyware, social media, annoyances, mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
a bug here
https://github.com/AdguardTeam/AdguardForAndroid/issues/1195
Added to Russian filter
```
gtavicecity.ru##div[class^="banner-"]
gtavicecity.ru#$#body>div.body-container { margin-top: auto!important; }

```
