### ISSUE TITLE
zaful.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4945]
***Site***: http://www.zaful.com/ / http://m.zaful.com/
***Description***: Newsletter at the end of the site.

*Rules:*
```
zaful.com##.cemailsWrap
zaful.com##.foot-sign
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25742102/27f4d95c-318e-11e7-9774-be623532c200.png)

![image](https://cloud.githubusercontent.com/assets/10995998/25742149/6a209064-318e-11e7-94c9-2e800d6b4fae.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.356.1877
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.16.79
Spyware filter | 1.0.11.89
Social media filter | 1.0.19.28
Annoyances filter | 1.0.12.44
German filter | 1.0.33.57
Mobile ads filter | 1.0.8.26
Safari filter | 1.0.3.3

**Comment by seanl-adg** [comment]
Fixed
