### ISSUE TITLE
momox.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4946]
***Site***: https://www.momox.de/
***Description***: Newsletter box. Cookie notice at the bottom. 

*Rules:*
```
momox.de##.newsletter
momox.de##.cookie-teaser
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25742672/cb0a91b6-3190-11e7-89bb-30026e1b54a2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.356.1877
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.16.79
Spyware filter | 1.0.11.89
Social media filter | 1.0.19.28
Annoyances filter | 1.0.12.44
German filter | 1.0.33.57
Mobile ads filter | 1.0.8.26
Safari filter | 1.0.3.3

**Comment by seanl-adg** [comment]
Fixed
