### ISSUE TITLE
speedtest.net - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4947]
***Site***: http://www.speedtest.net/de/settings
***Description***: Error while trying to change date format in settings.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25743813/94107b16-3196-11e7-8f04-fdcada63a4d6.png)

This error occurs while trying to change this setting:
edit: Ok, not just this, every setting :)

![image](https://cloud.githubusercontent.com/assets/10995998/25743855/eb3a76ee-3196-11e7-8772-adc1b037514f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.16.80
Spyware filter | 1.0.11.89
Social media filter | 1.0.19.28
Annoyances filter | 1.0.12.44
German filter | 1.0.33.58
Mobile ads filter | 1.0.8.27
Safari filter | 1.0.3.3

**Comment by seanl-adg** [comment]
Added to English filter:
```
@@||speedtest.net/api/js/user-settings|$xmlhttprequest
```
