### ISSUE TITLE
maclife.de - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4950]
***Site***: http://www.maclife.de/
***Description***: Newsletter box at the end of the site. Ad leftovers.

*Annoyance filter rule:*
```
maclife.de##.newsletter-form
```
*German filter rule:*
```
maclife.de##.ad
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25752080/7711f942-31b7-11e7-88b1-b52b473d7d4f.png)

![image](https://cloud.githubusercontent.com/assets/10995998/25752205/de39ad0e-31b7-11e7-899b-17fc9f8f27ba.png)

***(several times on the page)***

________________________________________________

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.16.83
Spyware filter | 1.0.11.91
Social media filter | 1.0.19.28
Annoyances filter | 1.0.12.46
German filter | 1.0.33.59
Mobile ads filter | 1.0.8.29
Safari filter | 1.0.3.3

**Comment by Alex-302** [comment]
1- breaks full site
2 - too small

**Comment by danidoedel** [comment]
@Alex-302 Site is fine for me, but ok...

**Comment by Alex-302** [comment]
http://imagizer.imageshack.com/img922/2959/B12mCj.png
