### ISSUE TITLE
wareable.com - Social widget - Ad leftover - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4951]
***Site***: https://www.wareable.com/vr/san-jose-state-university-incubator-vr-312
***Description***: Social leftover, ad leftover and Amazon shop ad at the end of an article.

*Rule for Social filter:*
```
wareable.com##.article-media-icons
```
*Rules for English filter:*
```
wareable.com##.dfp-article-banner
wareable.com##.affiliate-box
```

<details>
<summary>Screenshot</summary>

***1. Social widget leftover***
***2. Ad leftover:***

![image](https://cloud.githubusercontent.com/assets/10995998/25752692/50fe065e-31b9-11e7-82af-87c8aee0b15e.png)

***Amazon shop ad:***

![image](https://cloud.githubusercontent.com/assets/10995998/25752633/229f4ca0-31b9-11e7-9a79-cf6c496bb007.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.16.83
Spyware filter | 1.0.11.91
Social media filter | 1.0.19.28
Annoyances filter | 1.0.12.46
German filter | 1.0.33.59
Mobile ads filter | 1.0.8.29
Safari filter | 1.0.3.3

**Comment by Alex-302** [comment]
Added
