### ISSUE TITLE
avia.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4952]
***Site***: http://www.avia.de/privatkunden.html
***Description***: Cookie notice at the bottom.

*Rule for Annoyance filter:*
```
avia.de##.cs-info-wrapper
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25752971/37fcf538-31ba-11e7-9767-abbb7861b2bd.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.16.83
Spyware filter | 1.0.11.91
Social media filter | 1.0.19.28
Annoyances filter | 1.0.12.46
German filter | 1.0.33.59
Mobile ads filter | 1.0.8.29
Safari filter | 1.0.3.3

**Comment by Alex-302** [comment]
Added
