### ISSUE TITLE
Google Ads in Star Music Tag Editor application

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4954]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

From #4909 (https://github.com/AdguardTeam/AdguardFilters/issues/4909#issuecomment-299354744)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25731642/b3e51726-3150-11e7-8fd2-7fa9d00c01af.png)

</details>

***Steps to reproduce the problem***:

https://play.google.com/store/apps/details?id=com.music.star.startag&hl=ru

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On 
Adguard filters: |  2, 3, 4, 14, 10, 1, 11

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1444709

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by KozelElena** [comment]
Лог и HAR в 1444709. Посмотрите, пожалуйста

**Comment by Alex-302** [comment]
Это гугловая реклама. Судя по HAR она заблокирована. В логе не вижу упоминаний com.music.star.startag. Пусть лог запросов запишет
