### ISSUE TITLE
Missed ad in Виджет Погода и Часы app

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4956]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

https://play.google.com/store/apps/details?id=com.devexpert.weather&hl=ru

Just open "Погода" in the app. Reproduced on my side.

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

<details>

![image](https://cloud.githubusercontent.com/assets/26434103/25774543/8ce64c18-3299-11e7-94a3-173c8be4b10d.png)

![image](https://cloud.githubusercontent.com/assets/26434103/25774546/99f6a344-3299-11e7-8ea7-a59b73187c31.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android
Adguard version: | 2.9.70
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None 
Adguard filters: | 1, 2, 3, 4, 11, 14, 211

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1554318

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Please check these rules:
```
||graph.facebook.com/network_ads_common/$important,replace=/"placements": \[[\s\S]*/"placements": \[\n\{\n"definition": \{\}\,\n"feature_config": {}\,\n"ads": \[\]\n}\n]\n}/
||googleads.g.doubleclick.net/mads/gma?carrier=$important,replace=/\{[\s\S]*\}/{"ad_type":"banner"\,"qdata":"x"\,"ad_networks":\[{"adapters":\[""\]\,"id":""}\]\,"settings":{"click_urls":\[""\]\,"imp_urls":\[\]\,"nofill_urls":\[""\]}}/
```
HTTPS filtering is required.

**Comment by Alex-302** [comment]
Кстати эта прога шлёт много запросов и может разряжать батарею.

**Comment by Alex-302** [comment]
@OlegSUP Нет ответа?

**Comment by OlegSUP** [comment]
Решено. Фильтры помогли.

**Comment by Alex-302** [comment]
К сожалению, этот метод плох - прога непрерывно лезет за гугловой рекламой, с мобильным инетом это очень плохо.
