### ISSUE TITLE
exrapidleech.info antiadblock

### ISSUE THREAD

**Issue by ghajini** [AdguardTeam/AdguardFilters#4957]
described here
` https://github.com/jspenguin2017/AdBlockProtector/issues/167`

using latest adguard filters with default settings

**Comment by Alex-302** [comment]
Not reproduced
http://i46.fastpic.ru/big/2017/0508/3e/f5416e1c1ec382b510df1897c4071d3e.jpg

**Comment by ghajini** [comment]
Click on `public rapidleech`

**Comment by Alex-302** [comment]
Please check this rule:
```
exrapidleech.info#%#(function() { var sto = window.setTimeout, re = /\.bab_elementid.$/; window.setTimeout = function(a, b) { if ( typeof a !== 'string' || !re.test(a) ) { return sto(a, b); } }.bind(window); var signatures = [ ['blockadblock'], ['babasbm'], [/getItem\('babn'\)/], ['getElementById','String.fromCharCode','ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789','charAt','DOMContentLoaded','AdBlock','addEventListener','doScroll','fromCharCode','<<2|r>>4','sessionStorage','clientWidth','localStorage','Math','random'] ]; var check = function(s) { var tokens, match, j, token, pos; for ( var i = 0; i < signatures.length; i++ ) { tokens = signatures[i]; match = 0; for ( j = 0, pos = 0; j < tokens.length; j++ ) { token = tokens[j]; pos = token instanceof RegExp ? s.search(token) : s.indexOf(token); if ( pos !== -1 ) { match += 1; } } if ( (match / tokens.length) >= 0.8 ) { return true; } } return false; }; var realEval = window.eval; window.eval = function(a) { if ( !check(a) ) { return realEval(a); } var el = document.body; if ( el ) { el.style.removeProperty('visibility'); } el = document.getElementById('babasbmsgx'); if ( el ) { el.parentNode.removeChild(el); } }.bind(window); })();
```

**Comment by ghajini** [comment]
That removes blockadblock from initial page....
Steps to reproduce...
1.go to `http://www.exrapidleech.info/index.php`
2.enter link `http://turbobit.net/y75g8w9emr7e.html`
3.click transload
4.enter captcha...redirected to gateway page
5.click public rapidleech
6.after site redirect you to homepage/recaptcha validation
7.after all this shit this page is shown of `verify.php`
 
![img_20170508_200523](https://cloud.githubusercontent.com/assets/20338483/25809134/c06cff0a-3429-11e7-9762-509fa8c88b8b.JPG)

**Comment by Alex-302** [comment]
Show me expected result.

**Comment by ghajini** [comment]
This is expected outcome with adguard off/other adblocking extesions disabled.....

![img_20170508_232229](https://cloud.githubusercontent.com/assets/20338483/25817616/83626ebc-3445-11e7-9f75-29e2c97e8e49.JPG)
![img_20170508_232158](https://cloud.githubusercontent.com/assets/20338483/25817630/8bd33810-3445-11e7-84a8-1d9f23d914ba.JPG)

**Comment by ghajini** [comment]
Any progress

**Comment by Alex-302** [comment]
There is a looped captcha, can't do anything.

**Comment by ameshkov** [comment]
@ghajini try with those rules:
```
exrapidleech.info#%#if (document.location.href.indexOf('index.php') > 0) { window.eval = function() {}; }
exrapidleech.info#%#document.cookie = 'popcashpuCap=1';
exrapidleech.info#%#document.cookie = 'popcashpu=1';
exrapidleech.info#%#window.PopAds = "hi!";
```

**Comment by ghajini** [comment]
I see it works...thank you

**Comment by ghajini** [comment]
I wanna ask @ameshkov if you don't mind , I do use adguard and ublock origin in separate chrome profiles....in adguard it works and in ublock origin if I add above rules ,it won't work......so pls guide me to be able to work those rules in ublock .......I see gorhill also adding your English filter list in ublock .....
So that's fantastic adguard extension.....

**Comment by Alex-302** [comment]
Added

**Comment by ameshkov** [comment]
@ghajini 
> in adguard it works and in ublock origin if I add above rules ,it won't work......so pls guide me to be able to work those rules in ublock

uBO does not support JS rules. Instead, it supports "scriptlets", which are some kind of named javascript functions which can be used by filters maintainers. The downside is that it is not as flexible as JS rules.

**Comment by ghajini** [comment]
I see ....already reported these rules to @gorhill.....he has not committed yet because of lack of support of `js rules`......thank you

**Comment by ameshkov** [comment]
@ghajini scriptlets are also enough for this, it's just for this particular case it might be required to add a new scriptlet specifically for that website.
