### ISSUE TITLE
MitsubishiElectric.com - Unable to access site (AdGuard Annoyances filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#49576]
### Affected site:
`https://www.mitsubishielectric.com/`

### Issue:
Unable to access site, because the cookie consent is blocked.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* AdGuard Annoyances filter

### Problem rule:
`/cookie_policy.`

### Possible fix:
`@@/cookie_policy.$domain=mitsubishielectric.com`

### Other problem filters:
* EasyList Cookie List / Fanboy's Annoyance List https://github.com/ryanbr/fanboy-adblock/issues/1311/

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.8.2 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.17 (XUL)

**Comment by AdamWr** [comment]
Fixed, thank you.
