### ISSUE TITLE
wsj.com - charts are not displayed properly (Edge extension)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4960]
When the Adguard extension is turned on the charts on wsj.com are not displayed properly (Ref 11896793).  The issue can be reproduced here: http://quotes.wsj.com/MSFT
 
Here is a screenshot, as you can see the chart is empty. 

![unnamed 2](https://cloud.githubusercontent.com/assets/5947035/25782328/53d85156-3351-11e7-99f1-c47df3ee7b3f.jpg)

**Comment by Alex-302** [comment]
Reproduced two times on my side, and it works as expected after that without additional rules.
Is not it a bug with SVG?

**Comment by Alex-302** [comment]
Only `@@||quotes.wsj.com^$elemhide` helps. I think it is a bug with SVG.

**Comment by ameshkov** [comment]
@Alex-302 SVG? Please remind me what's that?

**Comment by Alex-302** [comment]
Filed a bug:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/683
