### ISSUE TITLE
woxikon.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4961]
***Site***: http://synonyme.woxikon.de/synonyme/auto.php
***Description***: Ad leftover

*Rule for German filter:*
```
woxikon.de##.ads-bg-white
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25812317/3237de98-3416-11e7-93f3-0d63844a91e8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.17.21
Spyware filter | 1.0.11.92
Social media filter | 1.0.19.30
Annoyances filter | 1.0.12.48
German filter | 1.0.33.68
Mobile ads filter | 1.0.8.30
Safari filter | 1.0.3.5

**Comment by Alex-302** [comment]
Added
