### ISSUE TITLE
http://www.artmoney.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4963]
http://www.artmoney.ru/r_download.htm (Taкже рекомендуем section):

![image](https://cloud.githubusercontent.com/assets/15856304/25840730/b0a0051e-34a5-11e7-8d83-a21b4b42b8fd.png)

***System configuration***

Information | value
--- | ---
Operating system: |reproduced on Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 1, 2, 3, 4

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 923093

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
