### ISSUE TITLE
https://ssp.tntech.edu/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4964]
https://ssp.tntech.edu/showLogin.cc

Adguard blocks the login form:

w/o Adguard:

![image](https://cloud.githubusercontent.com/assets/15856304/25842273/2e2c7412-34ac-11e7-8d80-e8b28ca8ea7d.png)

with Adguard, the login form is missing:

![image](https://cloud.githubusercontent.com/assets/15856304/25842282/39269dde-34ac-11e7-90a9-15ca98850253.png)

***System configuration***

Information | value
--- | ---
Operating system: | NT 10.0.14393.0
Browser: | Chrome
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
Adguard DNS: | None 
Adguard filters: | 2 3 4 10 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1524465

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
ssp.tntech.edu#@#iframe[width="100%"][height="250"]
```
