### ISSUE TITLE
vancouverok.com - Missed Ads

### ISSUE THREAD

**Issue by knekrasova** [AdguardTeam/AdguardFilters#4966]
Screenshot:
<details>

![image1](https://cloud.githubusercontent.com/assets/27948594/25849326/b5eeed52-34c6-11e7-80c6-031ecdb43ea0.png)

</details>

Information | value
--- | ---
Operating system: | iOS Pro
Browser: | Safari
Adguard version: | 1.2.1.71
Simplified filters(iOS) | On 

**Adguard filters**
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.17.26 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.93 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.49 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.50.82 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.30 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.6 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.41 Enabled=YES

Ticket ID | 1435339

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
