### ISSUE TITLE
Adguard Base blocks primary election results at Washington Post

### ISSUE THREAD

**Issue by nicknack23** [AdguardTeam/AdguardFilters#49672]
* **Current behaviour**: 

With Adguard Base enabled, you can't see the top line of the election results (showing that Bernie Sanders won) at this link:
https://www.washingtonpost.com/elections/election-results/2020-live-results-new-hampshire-democratic-primary/

***System configuration***

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox 72
AdGuard version:                       | no idea, the one that came with uBlock

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.

Thank you.
