### ISSUE TITLE
gisclub.tv -  Anti Adblock

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4967]
https://gisclub.tv/

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen_shot_2017-05-09_at_3 16 05_pm](https://cloud.githubusercontent.com/assets/22892774/25851092/09d7382e-34cd-11e7-9e49-3012a8fa1ec1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1 2 3 4 5 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID 1044396

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
