### ISSUE TITLE
Missed ad at http://ura-inform.com/

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4968]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Missed ad at    http://ura-inform.com/       start page

Reproduced on our side.

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/25853560/df2f153e-34d5-11e7-8593-ea6b16c5b8dc.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | English, Russian, Annoyances, Spyware, Social media

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Forum: https://forum.adguard.com/index.php?threads/http-ura-inform-com.21492/
Ticket ID: 793611

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
