### ISSUE TITLE
Ads penetrate Skype on Android device

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardFilters#49691]
Ads penetrate Skype on Android. Below attached are screenshot and technical info
![111 (1)](https://user-images.githubusercontent.com/23212486/74360157-9b791d00-4dd5-11ea-8658-6850c83fae21.jpg)

Operating system:                      Android 8
Browser:                               Google Chrome, Version 80.0
AdGuard version:                       Version 3.3.1, Freeware (No premium license)
Skype version:                       Version 8.56.0.100

Filters enabled:                       |   AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Experimental filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter 

AdGuard DNS:                           |  Cisco Family

**Comment by Alex-302** [comment]
Cannot reproduce on my device with US IP.
Please completely close an app and prepare to record web requests log
https://kb.adguard.com/en/android/solving-problems/log#collecting-web-requests-log
Upload it here.

**Comment by jbionic2016** [comment]
> Cannot reproduce on my device with US IP.
> Please completely close an app and prepare to record web requests log
> https://kb.adguard.com/en/android/solving-problems/log#collecting-web-requests-log
> Upload it here.

Hi Alex,

Thanks for sharing guidelines. Please advise which private address I may send my logs, so that the files were not publicly accessible??

**Comment by Alex-302** [comment]
Cannot find. I need a ticket ID. Or send it to me using Telegram.

**Comment by jbionic2016** [comment]
> Cannot find. I need a ticket ID. Or send it to me using Telegram.

Hi Alex, Please advise how else I can send you the log-file? I dont use Telegram

**Comment by Alex-302** [comment]
@jbionic2016 please send to tmail00@yandex.ru

**Comment by jbionic2016** [comment]
Done. Pls check ur mail. Thanks.

**Comment by Alex-302** [comment]
I don't see `Skype` in the log. Do you see requests in Assistant -> Filtering log?

**Comment by jbionic2016** [comment]
> I don't see `Skype` in the log. Do you see requests in Assistant -> Filtering log?

My apologies. I found that Skype had been somehow excluded from the list of Apps filtered by Adguard. So I cleaned Skype's cache, added Skype to Adguards filtering list and generated a new log. I've sent you the new log. Pls kindly verify it
Hope this helps.

**Comment by jbionic2016** [comment]
Большое подозрение что реклама как-то через Facebook проникает. Потому что когда я щелкаю на синем треугольничке в правом верхнем углу рекламного объявления (см. картинку в первом сообщении), то открывается браузер на m.facebook.com "Почему я вижу эту рекламу?". 

В итоге я включил в Adguard в фильтрацию также все приложения от Facebook (включая Facebook Services и тд), почистил кэш Skype. Перезапустил Skype .... но **реклама опять просачивается**...

**Comment by jbionic2016** [comment]
Вообщем, что я ещё выяснил. Если включить в Skype "компактный вид", то реклама почему-то не грузится. Во всяком случае пока что. 

Такое ощущение что если отключить компактный режим, то загрузка рекламы эмулирует дополнительный контакт в списке. Даже если посмотрите в первом сообщение картинку, размер красного кругляшка напротив Stoсard абсолютно совпадает с размером кругляшков с фотографиями у моих контактов (я их заштриховал, поэтому сравнивать будет сложно).

**Comment by jbionic2016** [comment]
I received feedback from your team by email:
>> As a first step, please try cleaning the application cache and setting up our DNS server.

We've passed down the logs to our development team and we'll let you know should we receive any additional recommendations.<<

I did as advised, but Ads persisted, which proves that changing DNS server has nothing to do with the problem. Switching Skype to Compact view resolves the issue, even though I cant explain it..

**Comment by Alex-302** [comment]
Загружать по идее скайп должен, но я не увидел фейсбучных запросов в логе. Видимо, что-то локальное.

**Comment by jbionic2016** [comment]
> Загружать по идее скайп должен, но я не увидел фейсбучных запросов в логе. Видимо, что-то локальное.

Во-первых, рекламная картинка меняется время от времени. Во-вторых, я специально провёл тест: почистил не просто кэш, а вообще полностью удалил все данные Скайпа, а потом залогинился по-новой, отключил компактный вид (он по умолчанию стоял) и.... РЕКЛАМА СНОВА ЗАГРУЗИЛАСЬ! Это, на мой взгляд, доказывает, что ничего локального не было.

**Comment by Alex-302** [comment]
Имел в виду, что проблема локальная. Запишите лог после чистки данных, с указанием времени запуска.

**Comment by jbionic2016** [comment]
> Имел в виду, что проблема локальная. Запишите лог после чистки данных, с указанием времени запуска.

Алекс, дорогой мой, Вы на нашу переписку выше посмотрите - из неё следует, что я Вам ничего не присылал на ваш яндекс-ящик ? Посмотри в нём ещё раз внимательно сообщения от jimmy bionic (jbionic*) и откройте последнее

**Comment by Alex-302** [comment]
Ну вот в том файле я ничего нужного и не увидел.
Попробуй экспортировать настройки, сбросить в дефолт и проверить снова(после ввода лицензии, без неё приложения не фильтруются некоторыми правилами).

**Comment by Alex-302** [comment]
Ну что там?

**Comment by jbionic2016** [comment]
> Ну что там?

Все по-старому, проникает реклама, я просто переключился в компактный вид в итоге, чтоб не проникала..

**Comment by Alex-302** [comment]
А можешь попробовать такое?
`||graph.facebook.com^$app=package_name`
`package_name` нужно заменить названием пакета, которое можно увидеть в журнале фильтрации.
Но это сломает авторизацию через Фейсбук.

**Comment by jbionic2016** [comment]
> А можешь попробовать такое?
> `||graph.facebook.com^$app=package_name`
> `package_name` нужно заменить названием пакета, которое можно увидеть в журнале фильтрации.
> Но это сломает авторизацию через Фейсбук.

Фишка как раз в том, что я не вижу в журнале фильтрации фейсбука при входе в скайп, я лишь догадываюсь что именно фейсбук как-то сопричастен к проникновению рекламы, потому что если кликнуть на саму рекламу в скайпе в правый верхний угол , то почему-от открывается именно фейсбук...

Ломать авторизацию в фейсбук мне не хотелось бы, посматриваю ленту регулярно и переписываюсь с друзьями через их мессенджер. Пока есть компактный режим в скайпе (кстати, непонятно почему переключение в этот режим влияет на проникновение рекламу) проблема не кажется такой уж назойливой. Как только и в компактном режиме реклама будет проникать, предлагаю реанимировать эту тему.

**Comment by Alex-302** [comment]
> Ломать авторизацию в фейсбук мне не хотелось бы, посматриваю ленту регулярно и переписываюсь с друзьями через их мессенджер.

это правило только для определённого приложения, если подставить нужный package_name

**Comment by jbionic2016** [comment]
Подставить package_name приложения Фейсбук?

**Comment by Alex-302** [comment]
От скайпа. Правило должно блокировать запрос к фейсбуку именно от Скайпа.

**Comment by jbionic2016** [comment]
> От скайпа. Правило должно блокировать запрос к фейсбуку именно от Скайпа.

Поэкспериментировал. Не помогло. Всё равно проникает. Может не из-за фейсбука проникает..

**Comment by Alex-302** [comment]
Какой режим фильтрации?

**Comment by jbionic2016** [comment]
Качественный

**Comment by Alex-302** [comment]
Это - алгоритм. Режим - локальный VPN или прокси.

**Comment by jbionic2016** [comment]
Локальной vpn установлен

**Comment by Alex-302** [comment]
Ну тогда не знаю. У меня никак не появляется реклама.

**Comment by Alex-302** [comment]
Повторилось. Проверяй:
```
||graph.facebook.com^$app=com.skype.raider
```

**Comment by jbionic2016** [comment]
Да, я уже понял :-) типа "сам дурак", как в таких случаях говорят.
Ничего, со всеми бывает. 

ЗЫ. Именно это правило я и добавлял в  Эдгард для com.skype.raider, у меня все равно просочилась после добавления

**Comment by Alex-302** [comment]
Тогда репозиторий Android можешь написать, и сослаться на эту задачу. Правило добавит в фильтр, предпросмотр фейсбучных ссылок не ломает вроде.

**Comment by jbionic2016** [comment]
Репозиторий Андроид - это что и где?

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues
