### ISSUE TITLE
Anti-adblocker in minigames.mail.ru

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#4970]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Anti - Ad Blocker in https://minigames.mail.ru/

Reproduced on our side. Just open any game and wait for a minute.

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

<details>

![image](https://cloud.githubusercontent.com/assets/26434103/25867590/b042f5f6-3502-11e7-827b-884d6f2354ea.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | English, Russian, Annoyances, Spyware, Social Media

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1551124

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
minigames.mail.ru###like-buttons > div[class][style="display: block;"]
minigames.mail.ru#$##like-buttons > div.soc-buttons { display: block!important; }
```

**Comment by kryoz** [comment]
You shouldn't have done that. If one day game fails to load because of adblocker users will blame game developers because they don't see the warning.

**Comment by Alex-302** [comment]
That notification is blocked in Annoyances filer. It is not enabled by default.

**Comment by kryoz** [comment]
Thank you
