### ISSUE TITLE
Again minigames.mail.ru

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardFilters#49702]
Ads penetrates while browsing mail.ru. Below attached are screenshot and technical info

![111](https://user-images.githubusercontent.com/23212486/74374387-5a8e0200-4def-11ea-8158-8eeb29c8cd3c.jpg)

![222](https://user-images.githubusercontent.com/23212486/74374398-6083e300-4def-11ea-8de4-bff419d0a464.jpg)

Operating system:                      Windows 10 v.1909 x64
Browser:                               Google Chrome, Version 80.0 (Official Build) (64-bit)
AdGuard version:                       Chrome plugin, Version 3.3.8

Filters enabled:                       |   AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Experimental filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter 

AdGuard DNS:                           |  Default 
Stealth mode options (Windows only)    |  On

**Comment by Alex-302** [comment]
@jbionic2016 глянь такие:
```
minigames.mail.ru#$?#div[style="transform: translateX(0px);"]:matches-css(width: 390px) { remove: true; }
minigames.mail.ru#$?#div[style="transform: translateY(0px);"]:matches-css(width: 390px) { remove: true; }
```
не тормозит ли у тебя с ними сайт? Сам не проверю это, комп слишком быстр)

**Comment by jbionic2016** [comment]
> @jbionic2016 глянь такие:
> 
> ```
> minigames.mail.ru#$?#div[style="transform: translateX(0px);"]:matches-css(width: 390px) { remove: true; }
> minigames.mail.ru#$?#div[style="transform: translateY(0px);"]:matches-css(width: 390px) { remove: true; }
> ```
> 
> не тормозит ли у тебя с ними сайт? Сам не проверю это, комп слишком быстр)

Добавил в User rules, закрыл браузер, почистил кэш, запустил браузер:
выглядит очень странно: справа мелькает реклама и тут же пропадает... Видео экрана не стал записывать, думаю, по думаю понятно..

**Comment by Alex-302** [comment]
Да не особо.

**Comment by Alex-302** [comment]
Эти правила добавил.

**Comment by jbionic2016** [comment]
Напрасно закрыли прецедент. Иногда реклама на указанном сайте всё таки фиксируется на экране и требуется обновление F5 страницы прежде чем она исчезает...
