### ISSUE TITLE
http://nextlivetv.com/russian-chanels/opt_live/ - некорректная блокировка

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4971]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://nextlivetv.com/russian-chanels/opt_live/ - некорректная блокировка 
* **Current behaviour**: не воспроизводятся видео

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/f604y6

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome 
Adguard version: | 6.1.3
Adguard driver (Windows): | TDI
Adguard filters: | Subscriptions: FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
FilterId:1 Name: Russian filter Url: https://filters.adtidy.org/extension/chromium/filters/1.txt
FilterId:0 Name: User filter Url: no_url

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 871912 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
