### ISSUE TITLE
meshok.net - некорректная блокировка

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#4972]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

meshok.net - некорректная блокировка 

Основная проблема - исчезновение части контента загрузки изображений при размещении лота на продажу программа блокирует загрузку iframe с адресом: https://meshok.net/item_edit_pic_frame.php?obj_id=ABC

где ABC переменная.

Screenshot:
 http://prnt.sc/f60jym
http://prnt.sc/f60k49

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome 
Adguard version: | 6.1.3 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1556277

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня не повторилось. Нужно больше сведений(фильтры, браузер, версия Адгарда)

**Comment by evgeniy-ADG** [comment]
Не повторилось. Запрсили детали.

**Comment by Alex-302** [comment]
Нет новостей?

**Comment by dzamyshlyayeva** [comment]
ничего не ответили, спросили еще раз.

**Comment by Alex-302** [comment]
А у тебя не повторяется?

**Comment by dzamyshlyayeva** [comment]
нет, ни на маке, ни на винде

**Comment by Alex-302** [comment]
ок тогда
