### ISSUE TITLE
http://www.redbull.com/ru/ru/adventure/stories

### ISSUE THREAD

**Issue by knekrasova** [AdguardTeam/AdguardFilters#4973]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

http://prnt.sc/f65msa

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.2.1.71
Simplified filters(iOS) | Off
Adguard DNS: | None / Default / Family Protection

**Adguard filters:** 
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.17.26 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.93 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.31 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.49 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.50.82 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.30 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.6 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.47 Enabled=NO
ID=118 Name="EasyPrivacy" Version=1.0.79.59 Enabled=YES

Ticket ID | 1518078

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Temporary for user filter
```
##.cookie-notification:not(body)
```
