### ISSUE TITLE
nymag.com - broken article page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#4974]
http://nymag.com/selectall/2017/05/if-your-saltshaker-doesnt-stream-music-you-should-feel-bad.html

Here is what's going on:
https://monosnap.com/file/J5mycU58sYVPEHPvVanLevOWVYkMtI

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||p.d.1enm.com/v*/*-*_$domain=nymag.com,script,other
```
