### ISSUE TITLE
go.activengage.com - incorrect blocking by French filter

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4975]
It appears that the French filter list (I haven't checked the other languages, but so far haven't been able to find it in the English rules) is blocking our script on our customer's pages.

The rule is:

://go.*/|$script,subdocument,third-party,xmlhttprequest

Our main script loads off of the domain go.activengage.com. You can see examples of this on http://www.normreeveswestcovina.com/ and in the screenshot below.

<img width="1404" alt="blocked norm reeves" src="https://cloud.githubusercontent.com/assets/15856304/25900471/41b342b8-359c-11e7-8964-f127cdf20a4c.png">

Is it possible to get this rule modified such that our script is not blocked?

ID: 1553307 - please check for more screenshots.

**Comment by Alex-302** [comment]
I need more(or all) examples.
Btw I can't reproduce it.

**Comment by Alex-302** [comment]
@seanl-adg
