### ISSUE TITLE
m.focus.de - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4976]
Links:

http://m.focus.de/regional/muenchen/polizei-muenchen-drei-junge-maenner-berauben-schueler-giesing_id_7105402.html?utm_source=facebook&utm_medium=social&utm_campaign=facebook-vermisst-und-gesucht&fbc=facebook-vermisst-und-gesucht&ts=201705091444

http://m.focus.de/regional/muenchen/polizei-muenchen-drei-junge-maenner-berauben-schueler-giesing_id_7105402.html

![image1](https://cloud.githubusercontent.com/assets/15856304/25907470/3354a1e4-35b0-11e7-92fb-0dc614fe3a28.PNG)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.3.1
Browser: | Safari
Adguard version: | 1.2.1.71
Simplified filters(iOS) | Off
Adguard DNS: |  Default 
Adguard filters: | 1 2 3 4 6 11 12 14 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1540118

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
For test:
```
||focus.de/resources/*/js/*likegate.js
```

**Comment by veronikasav** [comment]
tested 
<details>

![image](https://cloud.githubusercontent.com/assets/27292111/25918575/903c8754-35d4-11e7-9669-6727eca8b5c1.png)

![image](https://cloud.githubusercontent.com/assets/27292111/25918620/bed5aa14-35d4-11e7-8563-b3f8b9615c62.png)
