### ISSUE TITLE
slwoing down internet

### ISSUE THREAD

**Issue by tonino98** [AdguardTeam/AdguardFilters#4977]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10  1607 version
Browser: | chrome
Adguard version: | 6.2 Beta
Adguard driver (Windows): | WFP
Adguard DNS: | None
Stealth mode options(Windows) | yes
Adguard filters: | english filter/user filter/Spyware filter/EasyList/EasyPrivacy/EasyList Italy/Malware Domains

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by tonino98** [comment]
Slowing down internet

**Comment by Alex-302** [comment]
What do you mean?
```
Adguard driver (Windows):	WFP / TDI
```
Which driver are you using?

**Comment by tonino98** [comment]
my bad
WfP driver

**Comment by Alex-302** [comment]
I need more detailed description of the issue.
