### ISSUE TITLE
http://currentaffairs.gktoday.in - Anti-adblocker

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#4978]
currentaffairs.gktoday.in - Adblocker detected

![screen shot 2017-05-11 at 2 14 53 am](https://cloud.githubusercontent.com/assets/23372054/25925190/cbf2d5f8-35ef-11e7-8fb7-b10e24bacff6.png)

Reproduced on Mac, 1.4.1 Chrome 55, English, SM filter, Annoyances, Spyware, Safari 
Ticket ID 1354655

**Comment by Alex-302** [comment]
Fixed
