### ISSUE TITLE
cnn.com - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4979]
***Site***: http://edition.cnn.com/2017/05/10/politics/donald-trump-james-comey-whats-next/index.html
***Description***: Social widget leftover at the top. Ad leftover at the end of the article.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25922173/6beedfec-35d8-11e7-854e-52978104f81d.png)

![image](https://cloud.githubusercontent.com/assets/10995998/25922155/5df9963e-35d8-11e7-9ead-89982c548345.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.17.40
Spyware filter | 1.0.11.97
Social media filter | 1.0.19.35
Annoyances filter | 1.0.12.57
German filter | 1.0.33.77
Mobile ads filter | 1.0.8.31
Safari filter | 1.0.3.10

**Comment by Alex-302** [comment]
fixed

**Comment by danidoedel** [comment]
@Alex-302 There is still some ad leftover after the article:
![image](https://cloud.githubusercontent.com/assets/10995998/26459841/1c7df99c-4178-11e7-8fd8-188283da19eb.png)

**Comment by Alex-302** [comment]
fixed
