### ISSUE TITLE
filesupload.org

### ISSUE THREAD

**Issue by ghajini** [AdguardTeam/AdguardFilters#49796]
@AdamWr 
***URL(s) where the issue occurs*** =

https://filesupload.org/c12e89b311b01777?unlock

***Describe the issue*** =

clicking on ***download now*** results in ads ,not actual link/target link

***Screenshot(s)*** =

***Versions*** =

***Browser/version*** = firefox android stable 

***adguard version*** = 3.3.8

***settings*** =

  adguard browser extension default 
  settings+ decentraleyes

**Comment by Alex-302** [comment]
Not reproduced. Please send report from AdGuard.
