### ISSUE TITLE
strange issue with IDM and IE11

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/AdguardFilters#498]
http://forum.adguard.com/showthread.php?5080-Adguard-5-10-2010-6262-Problems&p=49690#post49690

In a few words:
IDM plugin for IE11 conflicts either with AG extensions (Assistant or Wot or Popup Blocker) or with JS rules.

**Comment by Alex-302** [comment]
Поставил IDM 6.23, расширения Adguard включены, в IE IDM включен. Проблем с гуглом повторить не смог.

**Comment by adguard** [comment]
TDI драйвер, после очистки кэша в IE в самый первый раз при клике на ссылке должно быть заметное торможение.

**Comment by Alex-302** [comment]
Вроде одинаково - что с, что без адгарда - за 3 сек открывается новая вкладка

**Comment by adguard** [comment]
Странно-странно, ладно, дождемся Егора, у него получалось повторить.
