### ISSUE TITLE
zillow.com - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4980]
***Site***: https://www.zillow.com/homes/
***Description***: App banner at the top (iOS/Android). Ad leftover between homes.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25926233/612071aa-35ee-11e7-927e-d37cc1a3df02.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.17.40
Spyware filter | 1.0.11.97
Social media filter | 1.0.19.35
Annoyances filter | 1.0.12.57
German filter | 1.0.33.77
Mobile ads filter | 1.0.8.31
Safari filter | 1.0.3.10

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
zillow.com###mobile-upsell-container
```
