### ISSUE TITLE
Ads in Bundle Android app

### ISSUE THREAD

**Issue by BlackOnyx1** [AdguardTeam/AdguardFilters#49801]
The recent days lots of ads in Sinhala language (Sri Lanka) appears in Android Bundle app, no filters available yet.

Selected German language, as most I read German news, nevertheless I face many ads in Sinhala, can't read Sinhala characters nor even understand the language, ads in Tamil still disappear.

Appreciate to fix issue if possible you.

Kind regards

**Comment by Alex-302** [comment]
Hi. Please send report using AdGuard(menu -> feedback) and add download link + screenshot.
