### ISSUE TITLE
gadgethacks.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4984]
***Site***: https://www.gadgethacks.com/
***Description***: Ad leftovers. As this site is the same as https://www.wonderhowto.com/ I think the same rules can be added.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25926704/f0a64cc6-35f0-11e7-89b7-b96061ac01a2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.17.40
Spyware filter | 1.0.11.97
Social media filter | 1.0.19.35
Annoyances filter | 1.0.12.57
German filter | 1.0.33.77
Mobile ads filter | 1.0.8.31
Safari filter | 1.0.3.10

**Comment by Alex-302** [comment]
Added
```
gadgethacks.com##.fixed-height-features+aside.whtaph-rightbox.whtaph-600
```

**Comment by danidoedel** [comment]
@Alex-302 There is still some ad leftover:
![image](https://cloud.githubusercontent.com/assets/10995998/26459710/af7de398-4177-11e7-850f-be1c7a6fd004.png)

**Comment by Alex-302** [comment]
Not reproduced. It is hidden by `.whtaph-rightbox`

**Comment by danidoedel** [comment]
@Alex-302 Hmm I can't find the rule `gadgethacks.com##.whtaph-rightbox` in the filters and if I add that one the leftover is removed.

**Comment by Alex-302** [comment]
http://imagizer.imageshack.com/img922/4593/Hhyvby.png
