### ISSUE TITLE
http://forums.redflagdeals.com/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4986]
http://forums.redflagdeals.com/

![image](https://cloud.githubusercontent.com/assets/15856304/25934030/291b6176-3624-11e7-92f1-211a342e13c6.png)

Manual blocker creates a rule but it doesn't block the element when you refresh the page.

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.2.0.60
Simplified filters(iOS) | Off
Adguard DNS: | efault
Adguard filters: | 2 3 4 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1303217

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
forums.redflagdeals.com##.message.guest_intro
```

**Comment by Alex-302** [comment]
fixed
