### ISSUE TITLE
https://www.google.ca/ - annoyances

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4987]
https://www.google.ca/

![file_000 3](https://cloud.githubusercontent.com/assets/15856304/25934191/034c39ba-3625-11e7-8337-f29e096c4dfa.png)

***Steps to reproduce the problem***:

1. Go to https://www.google.ca/
2. See the 'It's better in the app" message. Not sure if you need the Google app to be installed but I have it and I can reproduce the issue.

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.2.0.60
Simplified filters(iOS) | Off
Adguard DNS: | efault
Adguard filters: | 2 3 4 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1303217

**Comment by Alex-302** [comment]
Not reproduced. I need access to Safari, if it will be reproduced, or to MacOS with connected iPad
