### ISSUE TITLE
http://newnavitel.blogspot.ru/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#4988]
http://newnavitel.blogspot.ru/p/skin_6617.html

![image](https://cloud.githubusercontent.com/assets/15856304/25942790/69696b84-3646-11e7-9d8a-fe12389ea7d8.png)

***System configuration***

Information | value
--- | ---
Operating system: | OSX
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1 2 10

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1044396

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed in Annoyances filter.
