### ISSUE TITLE
focus.de - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4989]
***Site***: http://m.focus.de/kultur/kino_tv/ab-2021-swr-intendant-bringt-erhoehung-der-rundfunkgebuehren-ins-spiel_id_7122013.html
***Description***: Ad leftover. Social widget.

*Rules German filter:*
```
focus.de###top-banner
focus.de###skyscraper
focus.de##.tft_ads
focus.de###footerv2-head
```

*Rule Social filter:*
```
focus.de##.starratingv2
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25952023/c5d79d28-365f-11e7-887c-a8aa84f76b76.png)

![image](https://cloud.githubusercontent.com/assets/10995998/25951997/b7141104-365f-11e7-8f75-ee7b4910279c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.17.47
Spyware filter | 1.0.11.97
Social media filter | 1.0.19.36
Annoyances filter | 1.0.12.60
German filter | 1.0.33.77
Mobile ads filter | 1.0.8.32
Safari filter | 1.0.3.10

**Comment by Alex-302** [comment]
Not reproduced.
Added
```
m.focus.de##div[id^="M_CONTENTAD"]
```

**Comment by danidoedel** [comment]
@Alex-302 Still reproducible for me.

**Comment by Alex-302** [comment]
What?
