### ISSUE TITLE
areamobile.de - Annoyance - Ad - iOS

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4990]
***Site***: http://www.areamobile.de/
***Description***: Cookie notice and ad at the top.

*Rule for Annoyance filter:*
```
areamobile.de###cookieChooser
```

*Rule for German filter:*
```
@@/ad_bomb/*$image,domain=areamobile.de
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25953100/af1b7f2a-3662-11e7-8282-6a07504fc6f7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.17.47
Spyware filter | 1.0.11.97
Social media filter | 1.0.19.36
Annoyances filter | 1.0.12.60
German filter | 1.0.33.77
Mobile ads filter | 1.0.8.32
Safari filter | 1.0.3.10

**Comment by Alex-302** [comment]
Added
