### ISSUE TITLE
macwelt.de - Social widget - Ad leftover - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4992]
***Site***: http://www.macwelt.de/a/geruecht-ipad-pro-mit-10-5-zoll-auf-der-wwdc,3436994
***Description***: Ad leftover. Social widgets. Ads.

*Rules for German filter:*
```
macwelt.de##.adsense
macwelt.de##.tariffuxx-teaser
macwelt.de##div[data-ga-event-category="billiger_de_box_right_column"]
macwelt.de##.marketplace
```

*Rules for Social filter:*
```
macwelt.de##.socialMedia
macwelt.de##.social_media_buttons
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/25953638/43af819e-3664-11e7-91e6-f6b35a26e608.png)

![image](https://cloud.githubusercontent.com/assets/10995998/25953817/cc9795aa-3664-11e7-992d-1d8817c36823.png)

![image](https://cloud.githubusercontent.com/assets/10995998/25953848/dceca256-3664-11e7-8d21-f7d7cd004436.png)

![image](https://cloud.githubusercontent.com/assets/10995998/25954184/c78757de-3665-11e7-9ce4-4074bd08c191.png)

***Not sure how to block that last one though:***

![image](https://cloud.githubusercontent.com/assets/10995998/25954222/ddd9c0b2-3665-11e7-8d6d-c16ada0f5a4b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.17.47
Spyware filter | 1.0.11.97
Social media filter | 1.0.19.36
Annoyances filter | 1.0.12.60
German filter | 1.0.33.77
Mobile ads filter | 1.0.8.32
Safari filter | 1.0.3.10

**Comment by Alex-302** [comment]
added

**Comment by danidoedel** [comment]
@Alex-302 Still some ads on the site:
![image](https://cloud.githubusercontent.com/assets/10995998/26460091/e1094cee-4178-11e7-88ee-27cef3878729.png)
