### ISSUE TITLE
kaztorka.org - Ad Leftover

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#4993]
Screenshot:
http://prntscr.com/f6qmrl

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard filters: | 1 2 3 4 5 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID 637640

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
