### ISSUE TITLE
nytimes.com - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#4995]
***Site***: https://mobile.nytimes.com/
***Description***: Ad leftover. Newsletter signup leftover.

<details>
<summary>Screenshot</summary>

*https://mobile.nytimes.com/:*

![image](https://cloud.githubusercontent.com/assets/10995998/25971666/5d4cb548-369d-11e7-9025-68d9d4db7f27.png)

*https://www.nytimes.com/video/us/politics/100000005090665/comey-trump-russia-investigation.html:*

![image](https://cloud.githubusercontent.com/assets/10995998/25971645/4908eebc-369d-11e7-96e9-29eb5ccb5540.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.17.52
Spyware filter | 1.0.11.98
Social media filter | 1.0.19.37
Annoyances filter | 1.0.12.64
German filter | 1.0.33.79
Mobile ads filter | 1.0.8.32
Safari filter | 1.0.3.10

**Comment by Alex-302** [comment]
Just separators and `sign in` form.

**Comment by Bohdan-SUP** [comment]
@Alex-302 
Safari 10 with Adguard extension 2.6.1, same filter set:
![image](https://cloud.githubusercontent.com/assets/14153331/26400547/1a58d342-408a-11e7-80de-c46c677f477f.png)

**Comment by Alex-302** [comment]
Added to English filter
```
nytimes.com##.masthead-placeholder
```

**Comment by ameshkov** [comment]
This rule actually breaks the homepage now.

**Comment by ameshkov** [comment]
Removed it from the english filter
