### ISSUE TITLE
proswift.ru - Incorrect blocking - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#4996]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

 A pop-up window appears during the scrolling the page.

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/27292111/25978063/8d22ee60-36c8-11e7-9fe4-72ca6ddf5fff.png)

</details>

Application version: 1.2.1.71
Platform: iOS
OS: 10.3

Optimazed enabled: NO

Filters subscriptions:
ID=2 Name="English filter" Version=1.1.17.55 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.98 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.37 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.64 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.51.1 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.33 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.10 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1518078

**Comment by Alex-302** [comment]
fixed
