### ISSUE TITLE
Seven Knight game gets a connection error with Adguard enabled

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#4997]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/26004083/43903ed6-373d-11e7-9c6f-44ab0a7c9295.png)

![image](http://somehosting.com/adg_on.jpg)
</details>

***Steps to reproduce the problem***:

https://play.google.com/store/apps/details?id=com.netmarble.sknightsgb&hl=en

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |Android 
Adguard version: | 2.9.70
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On Default
Adguard filters: | English, Russian, User, Spyware, Annoyances, Social media, Mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1370578

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Filed a bug
https://github.com/AdguardTeam/AdguardForAndroid/issues/1236
