### ISSUE TITLE
macrumors.com - Incorrect blocking - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#4998]
***Description***:

The social share buttons appear under the articles.

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26017281/76523854-3771-11e7-9208-65bcaf27ecfe.png)

</details>

***System configuration***

Platform: iOS
OS: 10.3.1

Optimazed enabled: NO

Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.17.60 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.98 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.37 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.64 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.65 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.33 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.10 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1405415

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
> OS: 10.3.1

this version have a bug with element hiding rules.
