### ISSUE TITLE
forbes.ru - Incorrect blocking - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#4999]
***Description***:  

http://www.forbes.ru/tehnologii/344131-norvezhskiy-otryv-kak-potomkov-vikingov-peresazhivayut-na-elektromobili
* **Current behaviour**: 

The social share buttons appear during the scrolling the page (at any article).

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26020901/3c3a8ca4-378d-11e7-9678-30ae1e8499a3.png)

</details>

***System configuration***

Application version: 1.2.1.71

Platform: iOS
OS: 10.3

Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.17.55 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.98 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.37 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.64 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.51.1 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.33 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.10 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.79.74 Enabled=YES

Ticket ID: 1517809

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@veronikasav что не правильно заблокировано?

**Comment by veronikasav** [comment]
@Alex-302 во время прокрутки страницы появляются виджеты социальных сетей,
воспроизводится

**Comment by Alex-302** [comment]
Кнопки убрал.
