### ISSUE TITLE
aida64.com/aida64russia.com - Unblocked pop-up 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5000]
***Description***:
* **Current behaviour**: 
Unblocked pop-ups on the screen even during scrolling

Screenshot:

<details>

in the bottom

![image](https://cloud.githubusercontent.com/assets/27292111/26021657/fd518ec6-379a-11e7-969e-1dbcf7508e60.png)

on the top

![image](https://cloud.githubusercontent.com/assets/27292111/26021669/2743eba2-379b-11e7-8e4c-990c46a08cfa.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome / Pale Moon / Internet Explorer С
Adguard version: | 6.1.314.1628 / 1.4.1
Adguard driver (Windows): | WFP 
Adguard filters: | 1 2 3 4 5 10 14

Ticket ID: 1419169

**Comment by Alex-302** [comment]
ашчув
