### ISSUE TITLE
missed ads in CellMapper, WiFi Password, CornerFly (android 7)

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5001]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: missed ads in CellMapper, WiFi Password, CornerFly (android 7)

ad in CornerFly still displayed after clearing
cache. CellMapper and WiFi Password had boxes for the ads with the
error like symbol but the ads didn't display this particular time.

CornerFly https://play.google.com/store/apps/details?id=com.flyperinc.cornerfly&hl=en
WiFi Password https://play.google.com/store/apps/details?id=com.farproc.wifipassword&hl=en
Screenshot:

![image](https://cloud.githubusercontent.com/assets/25711093/26022754/c86c3a9c-37b5-11e7-8a9e-94d292269613.png)

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 7
Adguard version: | 2.9.70
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | 2, 3, 4, 14, 11, 211 

Ticket ID(if exists): 1403048

[debug (81).txt](https://github.com/AdguardTeam/AdguardFilters/files/998362/debug.81.txt)
[state123.txt](https://github.com/AdguardTeam/AdguardFilters/files/998363/state123.txt)

**Comment by Alex-302** [comment]
Try this
http://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=61181442

**Comment by Michael23456** [comment]
forwarded to the customer

**Comment by carlylemiii** [comment]
Original report information is incorrect in one regard. This is only in HTTP proxy mode (auto), NOT in VPN. This is resolved by blocking IPv6, but creates other issues for my particular situation.

**Comment by Alex-302** [comment]
@carlylemiii Hi. Please try to enable `pref.proxy.block.ipv6` in low-level settings.

**Comment by Alex-302** [comment]
Or have you tried it already?
> but creates other issues for my particular situation.

which?

**Comment by carlylemiii** [comment]
Verizon wifi calls texts sms fail completely (maybe regular network too? -
was in a WiFi only zone at the time). But yeah it killed phone
functionality and I needed a full reboot to fix it.

**Comment by Alex-302** [comment]
I can't help in this case.
I recommend to ask question in Android repository:
https://github.com/AdguardTeam/AdguardForAndroid/issues
