### ISSUE TITLE
missed ad http://batona.net/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5002]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: missed ad http://batona.net/

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/26023274/10b309ce-37c1-11e7-9a70-c79dd5706c7b.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | eng, rus, annoyance, social, spyware, mobile, experimental

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1557969

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
