### ISSUE TITLE
Missed ad in Super Cat Bros (android 7, proxy mode)

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5003]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
missed ad in Super Cat Bros https://play.google.com/store/apps/details?id=com.FDGEntertainment.SuperCatBros.gp&hl=en

The issue doesn't persist in VPN mode

* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/26023934/c66696f6-37cf-11e7-84a6-576c53b5cb8c.png)

***System configuration***

Information | value
--- | ---
Operating system: |  Android 7
Adguard version: | 2.9.70
Adguard mode (Android): | Proxy(auto)
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | 2, 3, 4, 14, 5, 11, 15, 211 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1558142

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Michael23456** [comment]
http://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=61181442 -  possible solution is forwarded to the customer

**Comment by ministr91** [comment]
@Michael23456 ничего себе, ты понимаешь русский язык? Как вообще откопал тот форум?

**Comment by Michael23456** [comment]
@ministr91 я из сапа, а решение в слаке написали. Сразу для двух кейсов

**Comment by ministr91** [comment]
нет. @Michael23456 Если бы ты был из команды поддержки, то в твоем профиле был бы знак adguard
![default](https://cloud.githubusercontent.com/assets/22351242/26071095/9d642020-39af-11e7-85c5-00adb9bcba4f.jpg)

**Comment by Alex-302** [comment]
из поддержки он. Прекращай флудить.

**Comment by evgeniy-ADG** [comment]
@Alex-302 could you please have a look? 
Also, we have had a discussion here :) Does the HTTP requests log capture https requests as well? Or should we ask for HAR instead?

**Comment by Alex-302** [comment]
did you(or user) try this?
https://github.com/AdguardTeam/AdguardFilters/issues/5003#issuecomment-301237013

**Comment by evgeniy-ADG** [comment]
@Alex-302 It was enabled, so this is another issue.

**Comment by altokarev** [comment]
@Alex-302, here is the file.

[adguard.har.zip]()

**Comment by Alex-302** [comment]
You did not attached the file

**Comment by altokarev** [comment]
Actually did, but it looks line nothing, agree. 1,6Kb.

**Comment by Alex-302** [comment]
upload it on file hosting

**Comment by Alex-302** [comment]
It is empty. I think filtering is not working.
Try VPN mode.

**Comment by Michael23456** [comment]
here is the answer from the customer, I think the ticket can be closed

"I believe I've not only solved the issue with root mode but also found an
explanation for why my logs have been coming back blank.

I use an app called Greenify, which has an "agressive doze" mode meant to
stop unnecessary apps from running in the background. I added Adguard to
Greenify's whitelist and since then I have been unable to reproduce the
issue.

So, I guess that's that. If things change I'll let you know.

Thanks for your help"
