### ISSUE TITLE
Пропущенная реклама

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#5004]
Буду краток как всегда. Adguard 2.9 , Android 4.4.4. Фильтры по-умолчанию стоят, Фильтрация качественная, HTTPS вкл. 
Сайт полной версии rambler.ru . Сначала грузит без рекламы, потом она появляется
![screenshot_2017-05-13-13-03-53](https://cloud.githubusercontent.com/assets/22351242/26024591/0cbb0256-37dd-11e7-9ceb-0f5423158e18.png)
![screenshot_2017-05-13-13-03-59](https://cloud.githubusercontent.com/assets/22351242/26024592/11c2a844-37dd-11e7-8a1b-4d6d40a3827a.png)

**Comment by ministr91** [comment]
Все вымерли что ли? :D

**Comment by ministr91** [comment]
@Alex-302, написал бы хоть что-нибудь

**Comment by Alex-302** [comment]
раньше писал уже.

**Comment by ministr91** [comment]
Что именно? Проблема не решена, фильтры обновил

**Comment by ministr91** [comment]
Или ты про расширенное описание проблемы?

**Comment by Alex-302** [comment]
Про оформление.

**Comment by ministr91** [comment]
да ладно тебе @Alex-302 , я же тебя давно знаю и ты меня, всегда так писал и все было нормально. Проблема же есть, зачем сразу закрывать тему, я даже скрины прикрепил в качестве доказательств

**Comment by Alex-302** [comment]
> давно

вот поэтому и нужно оформлять по установленным правилам.

**Comment by ministr91** [comment]
@Alex-302, там оформление непонятное, писать долго, может так пойдет?

**Comment by ministr91** [comment]
Давай в порядке исключения

**Comment by Alex-302** [comment]
если заполнить один раз правильно, то почти ничего писать будет не нужно, например информацию о системе и конфигурацию можно копировать
