### ISSUE TITLE
incorrect blocking http://echo.msk.ru/ ( on Android)

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5005]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: incorrect blocking http://echo.msk.ru/ ( on Android)
* **Current behaviour**:  afters several seconds when the page is loaded you can see the following screenshot, if adg is disabled, it seems to be ok

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/26024671/f060c0d0-37de-11e7-94c5-3d3594d6b2d4.png)

***System configuration***

Information | value
--- | ---
Operating system: | Android 5
Browser: | chrome
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | end, rus, spyware, social, annoyance, mobile, experimental

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1558456

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
