### ISSUE TITLE
gamejolt.com tracking

### ISSUE THREAD

**Issue by Tibladar** [AdguardTeam/AdguardFilters#50050]
**Description**:

`gamejolt.com` sends os and view tracking data when visiting game sites.
For example visiting `https://gamejolt.com/games/moonrisehope/463975` and scrolling a bit results in these tracking images being loaded:

`​https://gamejolt.com/tick/fireside-post/1045054?cb=1582020833600&os=windows&arch=64`
`https://gamejolt.com/tick/game-view/463975?cb=1582021007000&os=windows&arch=64`

**Suggestion:** Block `https://gamejolt.com/tick/*`

**Filters:**

Information                            | Value
---                                    | ---
Browser:                               | Firefox 70.0.1
Filters enabled:                       | Spyware, Social media, Annoyances, English, German, EasyPrivacy, Fanboy's Enhanced Tracking List, AdGuard Tracking Protection

**Comment by Alex-302** [comment]
Ok.
