### ISSUE TITLE
Macrumors.com whitespace (Safari)

### ISSUE THREAD

**Issue by GigabitEthernet** [AdguardTeam/AdguardFilters#5006]
There's visible whitespace on macrumors.com when using the English filter.

<img width="1014" alt="screen shot 2017-05-13 at 17 55 43" src="https://cloud.githubusercontent.com/assets/4457688/26027413/89b33594-3805-11e7-96da-2027bfb9e9e7.png">

**Comment by Alex-302** [comment]
fixed

**Comment by GigabitEthernet** [comment]
Still showing up on Safari 10.1 on macOS 10.12.4.

**Comment by Alex-302** [comment]
Add to custom filter
```
macrumors.com##.ad
```
