### ISSUE TITLE
http://igru-xbox.net/ - ad leftover

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5008]
There's something black on top. Assistant is missing, too.

![image](https://cloud.githubusercontent.com/assets/15856304/26032473/85032a0c-389d-11e7-8d39-9ae725550780.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None
Adguard filters: | English, Russian, Spyware, Social media, Annoyances, Safari, Mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1412565

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
