### ISSUE TITLE
https://ekurilka.ua/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5009]
https://ekurilka.ua/ 

![image](https://cloud.githubusercontent.com/assets/15856304/26032821/408886bc-38a5-11e7-8e1e-9c74f3d8b6de.png)

***Steps to reproduce the problem***:

1. Go to https://ekurilka.ua/ 
2. Request the desktop version
3. See the banner flickering in the top part of the page

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Samsung browser
Adguard version: | 2.9
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On Default
Adguard DNS: | Default 
Adguard filters: | 2, 3, 4, 14, 10, 1, 11, 211

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1529147

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
