### ISSUE TITLE
com.textra

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#50094]
***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

Displays a banner.

<details><summary>Screenshot:</summary>

![Screenshot_20200218_182430_com textra](https://user-images.githubusercontent.com/33634917/74802457-9b4fb480-52e2-11ea-8a60-e7465c2a11f1.jpg)

</details><br/>

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 9
Browser:                               | N/A
AdGuard version:                       | 3.3.229
Filters enabled:                       | "Русский фильтр", "Базовый фильтр AdGuard", "Фильтр счетчиков и систем аналитики", "Фильтр раздражителей", "Фильтр виджетов социальных сетей", "Фильтр мобильной рекламы"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | 1550362

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@akmLaVx check, if filtering is enabled for this app. As I remember, it is disabled due to issues with MMS. On my device I don't see this ad.
