### ISSUE TITLE
http://forumua.org/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5010]
http://forumua.org/

Screenshots:

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/26032845/e65d6080-38a5-11e7-8d44-e5c1e93ba282.png)

![image](https://cloud.githubusercontent.com/assets/15856304/26032850/0198284e-38a6-11e7-8398-06d793a7d7f5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Samsung browser, Chrome
Adguard version: | 2.9
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On Default
Adguard DNS: | Default 
Adguard filters: | 2, 3, 4, 14, 10, 1, 11, 211

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1529147

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
forumua.org##div[class^="ad_"]
```
Жду отзыва.

**Comment by evgeniy-ADG** [comment]
Ніби все ок, реклами немає.
