### ISSUE TITLE
Inline comments

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardFilters#5012]
In https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#comments you state that only full lines can be comments but i think it would be convinient to atleast have the possibility to add inline comments like
```
*.*.*.*:30033$network,app=ts3client_win64.exe!Block Teamspeak File Transfer
```
the inline comments could be seen bound to the rule in the same line so the filtering log could show the comment a rule has for example.
Of course if every filter had that it would be a bit more resource-eating but i'm thinking more of the user filter cause that one can get a bit messy especially since you can't easily insert a new "comment" line above a filter.

**Comment by Alex-302** [comment]
I am agree, it can be useful for the rules with Adguard syntax only.

**Comment by Bluscream** [comment]
Thanks :)

**Comment by Alex-302** [comment]
It can be applied only to Adguard specific rules.
