### ISSUE TITLE
chip.de/mactechnews.de - Incorrect blocking - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5013]
***Description***:
* **Current behaviour**: 

Social widget and cookie notice appear with all basic filters enabled.

Screenshot:

<details>

Social widget at the bottom
![image](https://cloud.githubusercontent.com/assets/27292111/26033844/e6c4e1f4-38bb-11e7-9f6f-c86f30734b97.png)

Cookie notice at the bottom and social widget after article
![image](https://cloud.githubusercontent.com/assets/27292111/26033859/16e942c6-38bc-11e7-9161-92bbe3a91a9e.png)

</details>

***System configuration***

Application version: 1.2.1.71
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.17.81 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.2 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.42 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.68 Enabled=YES
ID=6 Name="German filter" Version=1.0.33.87 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.34 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.11 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
chip.de - not reproduced
Check this rule:
`chip.de##.share-buttons`
Added to Annoyances filter
```
mactechnews.de###cookiechoice
```
Added to Social filter
```
mactechnews.de##.SynFacebookLike
mactechnews.de##.SynTwitterShare
```

**Comment by danidoedel** [comment]
@Alex-302 Yeah `chip.de##.share-buttons` does fix it.
