### ISSUE TITLE
airlive.net - anti-adblocker - iOS 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5014]
Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26034254/ada22196-38c2-11e7-9d9c-00e045702992.png)

</details>

***System configuration***

Application version: 1.2.1.71
Platform: iOS
OS: 10.3.1

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.17.83 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.2 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.42 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.68 Enabled=YES
ID=6 Name="German filter" Version=1.0.33.87 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.61 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.11 Enabled=YES

Ticket ID: 1459423

**Comment by Alex-302** [comment]
Fixed
