### ISSUE TITLE
Missed ads (Яндекс.Директ) on rambler.ru

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5015]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Missed ads(Яндекс.Директ) on rambler.ru
not reproduced on my Mac

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/26034377/76e30ede-38c4-11e7-9a4b-4806abed581c.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | opera, firefox
Adguard version: | 6.2.346.1819
Adguard driver (Windows): | TDI
Stealth mode options(Windows) | on
Adguard filters: | eng, rus, social, spyware, annoyance, unblocking useful ads.

Ticket ID(if exists): 
1558391
1444608

**Comment by Alex-302** [comment]
Сайт исклюсили:
`INFO, AdguardSvc, 134, 13.05.2017 8:27:31.915, Adding rule @@||news.rambler.ru$document filterId=0`
пусть удалят все правила для этого сайта из пользовательского фильтра.

**Comment by evgeniy-ADG** [comment]
Оба, 1558391 и 1444608?

**Comment by Alex-302** [comment]
пусть оба исключения в юзерфильтре проверят, заобно и обновления фильтров, так кое-что доблокировал новое.

**Comment by Michael23456** [comment]
отправил ответы обоим кастомерам

**Comment by Alex-302** [comment]
@ameshkov what's wrong?

**Comment by ameshkov** [comment]
@Alex-302 nevermind:) Can we close this issue?

**Comment by Alex-302** [comment]
@ameshkov maybe)
@Michael23456 any news?

**Comment by OlegSUP** [comment]
User 1558391 : Помогла полная очистка пользовательского фильтра
User 1444608: Трудности с сертификатом для Firefox, настраивает HTTPS

**Comment by Alex-302** [comment]
Ок, пока закрываю.
