### ISSUE TITLE
fapnado.com [NSFW] [Pop-up & Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#50164]
https://www.fapnado.com/videos/5858/indian-sister-has-better-pussy-than-my-girlfriend/

Ads, ad text strings and pop-ups seen on the page.

https://prnt.sc/r52otu

Checked with AG for Chrome

**Comment by Nzzyme** [comment]
https://www.fapnado.com/videos/3617/anal-slut-carina-roman-cheats-with-bbc/

Ad banner on the player when pausing the video

**Comment by Alex-302** [comment]
fixed

**Comment by Nzzyme** [comment]
https://www.fapnado.com/

ADS seen on the right side of the page.

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
