### ISSUE TITLE
skysports.com - missed ad - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5016]
***Description***:
http://www.skysports.com/f1/news/12433/10874337/sebastian-vettel-saved-by-parking-problems-in-spanish-gp-qualifying

* **Current behavior**: even element blocking does not work with this ad, appears again after reloading the page.

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26034487/ed336f2e-38c5-11e7-82fb-833030362402.png)

![image](https://cloud.githubusercontent.com/assets/27292111/26034534/ab312976-38c6-11e7-8e88-8436a1d87436.png)

</details>

***System configuration***

Application version: 1.2.1.71
Platform: iOS
OS: 10.3.2

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.17.81 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.2 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.42 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.68 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.34 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.11 Enabled=YES

Ticket ID: 1557786

**Comment by ameshkov** [comment]
It seems that this one should be enough:
`skysports.com##.widge-marketing`

This ad is present on desktop version of the website as well.

**Comment by Alex-302** [comment]
Fixed.
