### ISSUE TITLE
missed ad Yahoo mail app

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5017]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
missed ad Yahoo mail app
https://play.google.com/store/apps/details?id=com.yahoo.mobile.client.android.mail&hl=en

is not reproduced on Android 5
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/26036115/aec6b276-38e0-11e7-96ba-5655d4520cd0.png)

***System configuration***

Information | value
--- | ---
Operating system: | Android 7
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On 
Adguard filters: | 2, 3, 4, 14, 5, 11, 211 

Ticket ID(if exists): 1283099

[debug (83).txt](https://github.com/AdguardTeam/AdguardFilters/files/999573/debug.83.txt)
[state.txt](https://github.com/AdguardTeam/AdguardFilters/files/999574/state.txt)
[adguard.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/999575/adguard.har.zip)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
http://4pda.ru/forum/index.php?showtopic=601691&st=8800#entry61181442
