### ISSUE TITLE
Блокируется отправка почты mail.ru из gmail

### ISSUE THREAD

**Issue by TechnoStone** [AdguardTeam/AdguardFilters#50185]
Версия 3.3.230 для Android
Всё после сброса приложения остаётся. Блокировку для Gmail отключал
Полагаю, синхронизация тоже ломается
![Screenshot_20200220-192303](https://user-images.githubusercontent.com/26044948/74955950-6e042300-5416-11ea-9eaf-2da62e273d80.png)
При отключении защиты всё работает

**Comment by Alex-302** [comment]
@TechnoStone что ломает - фильтры или фильтрация HTTPS?
