### ISSUE TITLE
Terrarium TV - missed ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#5018]
http://www.apkmirror.com/apk/terrarium-tv/terrarium-tv/

User report:
> can you update the Mobile Ads Filter so it removes ads from Terrarium TV? I did some digging, and found the ad servers the app uses: AdBuddiz, AppLovin, Chartboost, Startapp and Vungle. I turned on all the English filters, but ads still come through. Thanks in advance!

**Comment by Alex-302** [comment]
blocked few spyware/advertising domains.

**Comment by Hazbelll** [comment]
I know this is an old issue and been closed ages ago, but I thought it's worth mentioning there are still quite a few obtrusive ads being missed by AdGuard in Terrarium TV, in recent versions at least.

Known Versions include: 1.9.2 and 1.9.3.

**Comment by Alex-302** [comment]
I need web-requests log with time stamp and screenshot of ads,
