### ISSUE TITLE
zfilm-hd.club/ - site with ads 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#5020]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: zfilm-hd.club/ - site with ads 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
http://prnt.sc/f8c6hg

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 10.3.1
Simplified filters(iOS) |  Off
Adguard DNS: | None 
Stealth mode options(Windows) | 
Adguard filters: | English filter
Spyware filter
Social media filter
Experimental filter
Annoyances filter
Mibile ads filter
Safari filter

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1559717

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
