### ISSUE TITLE
Kijiji  - app with ads

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#5021]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Kijiji  - app with ads
https://itunes.apple.com/ca/app/kijiji-local-classifieds/id318979520?mt=8

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
https://prnt.sc/f8e8ro
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.2.1.71
Platform: iOS
OS: 10.3.1
Optimazed enabled: YES
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.17.60 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.98 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.37 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.64 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.61 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.33 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.10 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.51 Enabled=NO
ID=204 Name="Peter Lowe's list" Version=1.0.2.97 Enabled=NO

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1552563 (with logs)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is impossible to block these ads on iOS.

**Comment by joeb666** [comment]
Ok. Thankyou. They were all blocked before this new update.
