### ISSUE TITLE
mopo.de - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5022]
http://www.mopo.de/

![image](https://cloud.githubusercontent.com/assets/15856304/26099751/68038e2c-3a34-11e7-9aa5-444c012028b4.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.2.1.75
Simplified filters(iOS) | Off
Adguard DNS: | Default 
Adguard filters: | English, Russian, German, Annoyances, Safari, Mobiel ads, Spyware and Social media filters

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1559733

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@seanl-adg 
Maybe this rule will helps(even in Chrome)
`@@/ad_bomb/*$image,domain=mopo.de`
check with JS exclusion or without German filter.

**Comment by danidoedel** [comment]
Yeah that removes the ad.

**Comment by Alex-302** [comment]
added
