### ISSUE TITLE
Most of the urls are not working

### ISSUE THREAD

**Issue by Varulv1997** [AdguardTeam/AdguardFilters#50228]
Hello there, I noticed that every url I click that redirects to a download page on your website is not working at all, it fails everytime.

**Comment by krystian3w** [comment]
Try on other PC / smartphone / browser / Browser?

Also try use other internet source e.g. mobile LTE HotSpot.

**Comment by Varulv1997** [comment]
> Try on other PC / smartphone / tablet / Browser?
> 
> Also try use other internet source e.g. mobile LTE hotspot (tethering).

Thank you for the reply, yes I did try on multiple devices, still the same problem.

**Comment by krystian3w** [comment]
For my this works:

`https://adguard.com/en/download.html` - I can download EXE app for Windows.

**Comment by Alex-302** [comment]
@Varulv1997 is this issue reproduced anywhere in all browsers(Chrome/FF/Edge)?
