### ISSUE TITLE
[Android] comedyportal.tv

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#5023]
Missed ads on either side of the page.

Screenshots can be found here: https://forum.adguard.com/index.php?threads/21749/

Reproduced in Chrome with filters: Russian, English, Social, Annoyances, Spyware.

**Comment by Alex-302** [comment]
It is clean on my side. Check the settings.

**Comment by vozersky** [comment]
same here, clean on my side
