### ISSUE TITLE
Ads on https://ruseo.net/chto-luchshe-google-chrome-ili-opera-t5132.html

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5024]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

One of the ads on the page is not blocked at all, others are eliminated partially

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot: 

![](http://screenshot.ru/upload/images/2017/05/17/d3ec6f566b66af597d61d.jpg)

***Steps to reproduce the problem***:

https://ruseo.net/chto-luchshe-google-chrome-ili-opera-t5132.html

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | TDI
Adguard filters: | English, Russian, Social media, Spyware, Annoyances
Ticket ID(if exists): 1150428

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
