### ISSUE TITLE
gesundheit.de - ad leftover - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5025]
https://www.gesundheit.de/ernaehrung/lebensmittel/saucen-und-oele/schwarzkuemmeloel

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26143559/2970955a-3aee-11e7-9f78-6e52f40b180e.png)

</details>

***System configuration***

Application version: 1.2.1.71
Platform: iOS
OS: 10.3.3
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.18.12 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.10 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.49 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.76 Enabled=YES
ID=6 Name="German filter" Version=1.0.33.98 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.38 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.13 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
Not reproduced. 
Try
```
gesundheit.de##.adsense
```

**Comment by danidoedel** [comment]
@Alex-302 Yep, that does fix it.

**Comment by Alex-302** [comment]
Added
