### ISSUE TITLE
Anti - Adblock at https://bitload.org/

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#5026]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Anti Adblock script. Appears when downloading a file from the link, for example https://bitload.org/lvy5dvfucgji
Just wait for 5-10 seconds and it will appear.

Reproduced on our side.
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-05-17 at 6 43 51 am](https://cloud.githubusercontent.com/assets/26434103/26150496/9703b36c-3acc-11e7-8e2e-a631d289311f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None
Adguard filters: | English, Russian, Spyware, Annoyances, Social media

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1543128

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
