### ISSUE TITLE
tr.anidub.com - incorrect blocking

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5027]
URL:

http://tr.anidub.com/

<details><summary>Screenshot:</summary>

![screen shot 2017-05-17 at 17 15 48](https://cloud.githubusercontent.com/assets/28726429/26159444/45b528d2-3b27-11e7-80ec-d46c5b6309d0.png)

</details>

<br>
***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 14

**Comment by Alex-302** [comment]
Не повторяется ни в винде, ни в макоси.
Исключений для сайта нет?

**Comment by zebrum** [comment]
@altokarev мы сами тебя запутали ( 
с Adguard все выглядит так:

![screenshot 2017-05-17 18 21 18](https://cloud.githubusercontent.com/assets/23637588/26161818/a997df88-3b2d-11e7-8e7b-e6d98e0b0844.png)

**Comment by Alex-302** [comment]
У них картинки на сторонних хостингах лежат, уже удалены.
http://imagizer.imageshack.com/img924/8421/NiYlpC.jpg

**Comment by altokarev** [comment]
Там не в этих картинках дело. Режется социальный виджет ВК (который показан на первом скрине), а не должен.

**Comment by Alex-302** [comment]
Почему не должен? Глянь на фильтры.
Чтоб номер сопоставить с названием, вместо `1` в конце подставляй номер фильтра и смотри на вторую строку:
https://filters.adtidy.org/extension/chromium/filters/1.txt
`! Title:`

**Comment by zebrum** [comment]
my mistake then.
