### ISSUE TITLE
vidto.me - ads

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#5028]
New window opens.

URL:

http://vidto.me/nn6ysn9j4wcg.html 

<details><summary>Screenshot:</summary>

![screenshot 2017-05-17 17 45 33](https://cloud.githubusercontent.com/assets/23637588/26160920/27b0d1c0-3b2b-11e7-9106-2f619f756361.png)

</details>

<br>
***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 14

**Comment by Alex-302** [comment]
fixed
