### ISSUE TITLE
m.academyvn.com - ads

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5029]
URL:
http://m.academyvn.com

<details><summary>Screenshot:</summary>

![screenshot_20170517-185605](https://cloud.githubusercontent.com/assets/28726429/26164450/58d4e3b8-3b35-11e7-9114-40ecda250bfc.png)

</details>
<br>
***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Chrome
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On Default
Adguard DNS: | None 
Adguard filters: | 1, 2, 3, 4, 11, 14

**Comment by Alex-302** [comment]
Added to Mobile filter
```
m.academyvn.com##.float-ck
```
