### ISSUE TITLE
google.com | Breakage | Firefox for Android | Adguard Mobile Ads

### ISSUE THREAD

**Issue by in4u** [AdguardTeam/AdguardFilters#50294]
***Description***:
* **Current behaviour**: 

The rule `google.com##header[id="hdr"] ~ div#main > div[class="ZINbbc xpd O9g5cc uUPGi"]` in `Adguard Mobile Ads` filter list breaks the search results page on Firefox for Android. Sections like typo-related suggestions, what people ask, etc. are also getting blocked due to this rule.

* **Expected behaviour**: 

Only ads should be blocked and not other content. Related discussion [here](https://github.com/uBlockOrigin/uAssets/issues/3482#issuecomment-589966985). Possible solution [here](https://github.com/uBlockOrigin/uAssets/issues/3482#issuecomment-589989883).

***Steps to reproduce the problem***:

Search for anything with a deliberate misspelling, e.g. `basktball`. The search results will be for `basketball` but Google's note highlighting this and offering to search for original term will be blocked. Also, the section `People also ask` will be blocked as well.

***System configuration***

Information                            | Value
---                                    | ---
Operating system version (Android/iOS) | Android 8.1
Browser:                               | Firefox for Android 68.5.0
Filters enabled:                       | Adguard Mobile Ads

**Comment by krystian3w** [comment]
New name class for Ads? AdGuard never used extendCSS to block these ADS?

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.

Thank you.
