### ISSUE TITLE
[android] missed ads in News Republic app

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/AdguardFilters#503]

**Comment by Alex-302** [comment]
Вроде чисто. Может скрины есть?

**Comment by adguard** [comment]
Не, может надо с не-русским IP смотреть?

И еще момент - посмотри запросы через fiddler, может есть что-то подозрительное и не-заблокированное.

**Comment by Alex-302** [comment]
С немецким vpn не появилась реклама. А откуда юзер?

**Comment by adguard** [comment]
Вообще он болгарин, но живет, мне кажется, где-то в Англии.

**Comment by Alex-302** [comment]
С английским и шведским впн не повторяется.
