### ISSUE TITLE
flashx.tv - AntiAdbock

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardFilters#5030]
***Description***:
* **Current behaviour**: 

A 30 sec clip saying "disable your adblocker pops up

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)

Screenshot:
<details>
![image](https://cloud.githubusercontent.com/assets/3318223/26165121/18a8a410-3b2f-11e7-82bb-ed5d12183772.png)
</details>

***Steps to reproduce the problem***:

Go to this url and click play http://www.flashx.tv/9s1gk14qoaax.html

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Firefox Dev
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP / TDI
Adguard DNS: | None
Stealth mode options(Windows) | 1,2,3,4,5,7,8,9,10,11,13
Adguard filters: | Way too many to write them all

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced with Adguard filters.
