### ISSUE TITLE
blog-rct.com - anti adblock script

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#5031]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/26187888/8a7a2904-3ba4-11e7-902a-175f8b0318f1.png)

</details>

***Steps to reproduce the problem***:

http://www.blog-rct.com/blog-medium-left-sidebar-2/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Simplified filters(iOS) |  Off
Adguard filters: | English filter, Spyware filter, Social media filter, Annoyances filter, Russian filter, Safari filter, EasyList Hebrew

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1560636

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||blog-rct.com^$generichide
```

**Comment by evgeniy-ADG** [comment]
Works in Mac, still happens in iPhone.

**Comment by Alex-302** [comment]
Try that rule on iphone.

**Comment by pak1507** [comment]
Same problem, It doesn't work.

**Comment by Alex-302** [comment]
@pak1507 
> Same problem, It doesn't work.
>> Try that rule on iphone.
`@@||blog-rct.com^$generichide`

**Comment by pak1507** [comment]
Yes. I have try yesterday, but problem still happens.

> @pak1507
> 
> Same problem, It doesn't work.
> 
> Try that rule on iphone.
> @@||blog-rct.com^$generichide

**Comment by Alex-302** [comment]
Please check:
```
blog-rct.com###cookie-law-info-bar
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
```

**Comment by pak1507** [comment]
Thanks for your help dude!
I tried, and I no longer have the anti-adblock warning, that's a good thing.
However, when I'm in, I can't "load more posts". So, I only see 5.
It makes me crazy... What a protection !!

**Comment by Alex-302** [comment]
> However, when I'm in, I can't "load more posts". So, I only see 5.

I don't see it. Please provide direct url and screenshot.

**Comment by pak1507** [comment]
I can't click on the blue dotted square to "load more posts".
Normally it works like a button.
Here it is : www.blog-rct.com/blog-medium-left-sidebar-2/

![img_3430](https://cloud.githubusercontent.com/assets/28788111/26320804/8932e65c-3f24-11e7-9bc5-71f0775c6b10.PNG)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
@@||blog-rct.com/wp-content/plugins/cookie-law-info/js/cookielawinfo.js
```
