### ISSUE TITLE
nl.express.live - different ads leftovers

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#5032]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/26191005/ca5b1c80-3bb4-11e7-800e-786cb9fb4db7.png)

![image](https://cloud.githubusercontent.com/assets/17320558/26191008/d13fc938-3bb4-11e7-91d6-774187b19ef1.png)

</details>

***Steps to reproduce the problem***:

https://nl.express.live/2017/05/17/131349comey-trump-memo/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Chrome
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard filters: | English, Russian, Spyware, Social media, User, Annoyances, Mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1143992

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. Try with Dutch filter.
