### ISSUE TITLE
dthforum.com - Anti Adblock script

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5033]
Screenshot:

<details>

![pasted_image_at_2017_05_18_05_13_pm](https://cloud.githubusercontent.com/assets/28784344/26206527/bb980f62-3bed-11e7-9e9f-75f3bc7c6723.png)

</details>

***Steps to reproduce the problem***:

Go to:
https://dthforum.com/forums/tata-sky.27/

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.2.1
Adguard filters: | 1 2 3 4 5 11 12 14

Ticket ID: 1475009

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=dthforum.com
```
