### ISSUE TITLE
https://www.google.co.uk/amp/www.telegraph.co.uk/  - Blocks tweets

### ISSUE THREAD

**Issue by vtargonskyi** [AdguardTeam/AdguardFilters#5034]
***Description***:

Blocks tweets on website

Screenshot:

![image uploaded from ios](https://cloud.githubusercontent.com/assets/28786943/26214267/6d4705c2-3c04-11e7-9c5b-e38bd060057e.jpg)

***Steps to reproduce the problem***:

Go to: https://www.google.co.uk/amp/www.telegraph.co.uk/news/2017/05/16/mcdonalds-apologises-disgusting-tv-advert-upsets-viewers/amp/

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.3

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.18.18 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.11 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.51 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.78 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.1.3 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.14 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.54 Enabled=NO

Ticket ID: 1560951

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||cdn.krxd.net/amp/remote.min.js$domain=static.telegraph.co.uk
```
