### ISSUE TITLE
Adguards blocks Яндекс.Карты app

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#5035]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
https://play.google.com/store/apps/details?id=ru.yandex.yandexmaps&hl=en

Adguard blocks Яндекс.Карты app. When Adguard enabled, Яндекс.Карты can't download maps at all on my side (Android 6).

***System configuration***

Information | value
--- | ---
Operating system: |Android
Adguard version: | 2.9.7
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None 
Adguard filters: | Russian, English, Spyware, Social Media, Annoyances, Mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1544081

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by OlegSUP** [comment]
Также появились жалобы на блокировку Яндекс.Транспорт. На Навигатор пока жалоб нет.

Ticket ID: 1561239

**Comment by vmalyuta** [comment]
Ticket ID:1561605
логи тут

**Comment by OlegSUP** [comment]
Ещё один случай

Ticket ID: 1029341

**Comment by zebrum** [comment]
https filtering breaks yandex apps.
