### ISSUE TITLE
Anti Ad-Block at http://koraaaaaabook.blogspot.co.id/

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#5036]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Anti Ad-Block at http://koraaaaaabook.blogspot.co.id/?m=1

Just open the link. Reproduced on our side.
Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-05-19 at 10 35 22 am](https://cloud.githubusercontent.com/assets/26434103/26237846/73a29f78-3c7f-11e7-9ac8-5dac470c5209.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | Russian, English, Spyware, Annoyances, Social media

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1551511

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||koraaaaaabook.blogspot.co.id^$generichide
```
