### ISSUE TITLE
m.darty.com/m/search/powerbeats-3.html - ad leftlover 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#5037]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://m.darty.com/m/search/powerbeats-3.html - ad leftlover 
 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
https://prnt.sc/f9ljhp

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Application version: 1.2.1.71
Platform: iOS
OS: 10.3.2
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.18.31 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.11 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.52 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.82 Enabled=YES
ID=16 Name="French filter" Version=1.0.2.48 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.62 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.39 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.15 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.55 Enabled=NO
ID=101 Name="EasyList" Version=1.0.66.67 Enabled=NO
ID=118 Name="EasyPrivacy" Version=1.0.71.79 Enabled=NO
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.65.45 Enabled=NO
ID=122 Name="Fanboy's Annoyances" Version=1.0.71.58 Enabled=YES
ID=113 Name="Liste FR" Version=1.0.78.49 Enabled=NO
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.3.63 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.80.29 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.67 Enabled=NO
ID=229 Name="I dont care about cookies" Version=1.0.0.13 Enabled=NO
ID=208 Name="Malware Domains" Version=1.0.78.49 Enabled=NO
ID=209 Name="Prebake" Version=1.0.1.14 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.74 Enabled=NO
ID=237 Name="AdBlock Protector List" Version=1.0.0.8 Enabled=NO

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1021351

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce even without Adguard
<details>

![image](http://imagizer.imageshack.com/img924/9518/O0WJoh.png)
</details>
Please select element by Adguard tool and copy the rule.
