### ISSUE TITLE
Пропускает рекламу на https://hi-tech.mail.ru/nokia_6_14518224-catalog/

### ISSUE THREAD

**Issue by decouxe** [AdguardTeam/AdguardFilters#5038]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**:  

[//]: # (Tell us what happens)
[//]: # Пропускает рекламу на https://hi-tech.mail.ru/nokia_6_14518224-catalog/ при нажатии на фотографию

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>
[image](http://savepic.ru/14044629.png)
http://i92.fastpic.ru/big/2017/0519/f1/ea6dcebbcc588f566029c06fb8f7f6f1.png

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)
Нажать на фотографию

***System configuration***

Information | value
--- | ---
Operating system: | **Windows** / Mac OS / Android / Linux
Browser: | Chrome
Adguard version: | 6.2 Beta 
Adguard driver (Windows): | WFP / TDI
Adguard mode (Android): | VPN / Proxy(manual/auto)
Filtering quality (Android): | High-quality / high-speed / simplified
HTTPS filtering (Android): |  On (Default/Blacklist mode) / Off
Simplified filters(iOS) | On / Off
Adguard DNS: | None / **Default** / Family Protection
Stealth mode options(Windows) | 
Adguard filters: | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
hi-tech.mail.ru##.js-popup_banner
```
