### ISSUE TITLE
Anti Ad-Block at http://viid.me/

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#5039]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Just open http://viid.me/qAVp7u

Reproduced on our side.

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screen shot 2017-05-19 at 1 44 03 pm](https://cloud.githubusercontent.com/assets/26434103/26244677/67057960-3c99-11e7-91d9-6a0758896c07.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | Russian, English, Spyware, Social media, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1059796

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||viid.me^$generichide
```
