### ISSUE TITLE
please in DNS filter add filter that enables removing of the ads from websites with Italian content

### ISSUE THREAD

**Issue by sviluppoSoftware** [AdguardTeam/AdguardFilters#50401]
i have read  https://kb.adguard.com/en/general/adguard-ad-filters and seems there isn't an Italian filter to block ads from websites with Italian content not even in DNS filter, are you intent to add this in the future in particular in DNS filter?

thanks for your work and response.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #243](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/243) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
@sviluppoSoftware moved to correct repository.
