### ISSUE TITLE
http://sovets.net/6780-kak-ustanovit-moskitnuyu-setku-na-plastikovoe-okno.html - Adguard fails to block ads

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5041]
***Description***:
* **Pop-ups, unblocked ads, repeats on Mac**: 

Screenshot:

<details>

![s70519-202830](https://cloud.githubusercontent.com/assets/28784344/26259695/d397de5e-3cd2-11e7-9018-4388052f05c8.jpg)

</details>

Screenshot:
<details>

![s70519-202825](https://cloud.githubusercontent.com/assets/28784344/26259720/f10c576c-3cd2-11e7-9f1a-b842d63fcd89.jpg)

</details>

***Steps to reproduce the problem***:

Go to http://sovets.net/6780-kak-ustanovit-moskitnuyu-setku-na-plastikovoe-okno.html 

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | default Meizu browser (screenshots)
Adguard version: | 2.9.70
Adguard mode (Android): | Proxy(manual)
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  Off
Adguard DNS: | None / Default / Family Protection
Adguard filters: | 2, 3, 4, 1, 11

Ticket ID: 1556041

**Comment by Alex-302** [comment]
Fixed.
