### ISSUE TITLE
Moon+ Reader - Adguard fails to block ads

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5043]
***Description***:
* **Adguard does not block ads in the Moon+ Reader app**: 

Screenshot:

<details>

![screenshot_20170517-215111](https://cloud.githubusercontent.com/assets/28784344/26273282/45ef28f6-3d35-11e7-9b07-73b3cf03db67.png)

</details>

***Steps to reproduce the problem***:

1. Go to https://play.google.com/store/apps/details?id=com.flyersoft.moonreader&hl=en
2. Download the app
3. Open it and try to browse any book 

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.70
Adguard mode (Android): | Proxy(manual)
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard DNS: | None 
Adguard filters: | 2, 3, 4, 14, 5, 11, 15, 211

Ticket ID: 1554810

**Comment by Michael23456** [comment]
is not reproduced on Android 5 with VPN mode.
Google Backup transport filtration is on
[state.txt](https://github.com/AdguardTeam/AdguardFilters/files/1015962/state.txt)
[debug (88).txt](https://github.com/AdguardTeam/AdguardFilters/files/1015963/debug.88.txt)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||graph.facebook.com^$app=com.flyersoft.moonreader
```
