### ISSUE TITLE
anti-adblock https://lotzon.co/blog

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5044]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: anti-adblock https://lotzon.co/blog
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/26273739/5bab1344-3d3f-11e7-87ec-0944be245414.png)

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | chorme
Adguard version: | 1.4.1
Adguard filters: | eng, rus, annoyance, social, spyware, mobile, experimental

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1043635

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
