### ISSUE TITLE
http://www.banki.ru/news/lenta/?id=9752005 - Bug report

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5045]
***Description***:
* When you go on the web site (having Adblock turned on) the actual article is missing; after switching Adguard off - the material re-appears  : 

Screenshot:

<details>

![e29a2cc34fab4a48bec56cdf92cd91b5](https://cloud.githubusercontent.com/assets/28784344/26274221/4e84af5a-3d4d-11e7-90bf-52d0d5edfde3.jpeg)

</details>

Screenshot:

<details>

![9c11d42f6bae4d60b4adefc77607de9c](https://cloud.githubusercontent.com/assets/28784344/26274223/6411810e-3d4d-11e7-9f5f-dbcb275c60f9.jpeg)

</details>

***Steps to reproduce the problem***:

1. Go on http://www.banki.ru/news/lenta/?id=9752005
2. You will probably be unable to see the article
3. Turn adguard off
4. Refresh the page
5. The article is likely to appear this time

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Adguard DNS: | Default 
Stealth mode options(Windows) | enabled 

Adguard filters: 2, 3, 4, 14, 1, 210, 0

Ticket ID: 1115588

**Comment by Alex-302** [comment]
Fixed in social filter.
