### ISSUE TITLE
gofeminin.de - Annoyance - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5046]
***Site***:http://www.gofeminin.de/ and http://www.gofeminin.de/kochen-backen/kuchen-rezepte-s2239342.html
***Description***: Several social widgets. Ad leftovers and annoying scroll to top bar.

*Rules for Social filter:*
```
gofeminin.de##.af-social-btns
gofeminin.de##.af-htmlblock-autopromo
gofeminin.de###social-icons-wrapper
```

*Rule for Annoyance filter:*
```
gofeminin.de###af-scrollspy
```

*Rules for German filter:*
```
gofeminin.de##.af-block-native
gofeminin.de##.story-ad-mobile
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26274833/a41b5706-3d53-11e7-9332-ab23cfd92c0a.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26274849/eb5db794-3d53-11e7-98ce-2ccb163f9d5e.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26274907/6c18abc2-3d55-11e7-9ce0-befaa12da479.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26274864/2db56a4c-3d54-11e7-98e7-eb88ce81ace7.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26274888/df493ae0-3d54-11e7-90ef-6a5420403a70.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.18.51
Spyware filter | 1.0.12.14
Social media filter | 1.0.19.57
Annoyances filter | 1.0.12.90
German filter | 1.0.34.7
Mobile ads filter | 1.0.8.42
Safari filter | 1.0.3.17

**Comment by danidoedel** [comment]
The rule `gofeminin.de##.af-htmlblock-autopromo` seems to break the desktop layout a bit:

![image](https://cloud.githubusercontent.com/assets/10995998/26274939/08fa60f2-3d56-11e7-817c-c836bfbb42e6.png)

Not sure if there is an other way to block this stuff...

**Comment by Alex-302** [comment]
Added
