### ISSUE TITLE
wunderweib.de - Social widget - Annoyance - Ad - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5047]
***Site***: http://www.wunderweib.de/weisse-smoothies-so-hilft-dir-das-gesunde-getraenk-beim-abnehmen-100244.html
***Description***: Ads. Ad leftover. Social widget. Newsletter subscription.

<details>
<summary>Screenshot</summary>

1. Ads + Ad leftover
```
wunderweib.de##div[id^="basic-teaser-"]
wunderweib.de##.adAnything
wunderweib.de##.adverteaser
wunderweib.de##.taboolaWrapper
```
2. Social widget 
```
wunderweib.de##.social-bar-sticky
```

![image](https://cloud.githubusercontent.com/assets/10995998/26275195/a89f0e8c-3d5b-11e7-84c8-2da23a32a081.png)

_____________________________________________

3. Newsletter
```
wunderweib.de##.newsletterSubscription
```

4. Ads
```
wunderweib.de##.teaser--aside
```

![image](https://cloud.githubusercontent.com/assets/10995998/26275236/5ad51f60-3d5c-11e7-96d0-33ef0556cd8a.png)

_____________________________________________

5. Whatsapp newsletter leftover
```
wunderweib.de##.teaser_html
```

![image](https://cloud.githubusercontent.com/assets/10995998/26275252/bc51ad62-3d5c-11e7-98fd-7f592621682d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.18.51
Spyware filter | 1.0.12.14
Social media filter | 1.0.19.57
Annoyances filter | 1.0.12.90
German filter | 1.0.34.7
Mobile ads filter | 1.0.8.42
Safari filter | 1.0.3.17

**Comment by Alex-302** [comment]
added

**Comment by danidoedel** [comment]
@Alex-302 taboolaWrapper still there:
![image](https://cloud.githubusercontent.com/assets/10995998/26460465/fe955c70-4179-11e7-9ad2-366805a9d39f.png)
