### ISSUE TITLE
menshealth.de - Ad leftover - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5048]
***Site***: http://www.menshealth.de/
***Description***: Adblock detection. Ad leftover.

<details>
<summary>Screenshot</summary>

*http://www.menshealth.de/artikel/vom-flirt-zum-sex.93741.html?block=1:*

![image](https://cloud.githubusercontent.com/assets/10995998/26275305/929a23c2-3d5d-11e7-9391-9f44d7bcdca5.png)

*Ad leftover (http://www.menshealth.de/):*

![image](https://cloud.githubusercontent.com/assets/10995998/26275355/d2df1996-3d5e-11e7-832e-c806880e3375.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.18.51
Spyware filter | 1.0.12.14
Social media filter | 1.0.19.57
Annoyances filter | 1.0.12.90
German filter | 1.0.34.7
Mobile ads filter | 1.0.8.42
Safari filter | 1.0.3.17

**Comment by Alex-302** [comment]
added
menshealth.de##div.mps-banner
menshealth.de##.mps-spon
menshealth.de#%#window.blockAdBlock = function() {};
