### ISSUE TITLE
woxikon.de - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5049]
***Site***: http://synonyme.woxikon.de/
***Description***: Ad. Rule to remove the ad: `@@/ad_bomb/*$image,domain=woxikon.de`

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26275376/53472fe2-3d5f-11e7-9765-e8422a37f5ee.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.18.51
Spyware filter | 1.0.12.14
Social media filter | 1.0.19.57
Annoyances filter | 1.0.12.90
German filter | 1.0.34.7
Mobile ads filter | 1.0.8.42
Safari filter | 1.0.3.17

**Comment by danidoedel** [comment]
Ups didn't notice I have an other woxikon issue open (#4961). But yeah after two weeks I couldn't remember that :D

**Comment by Alex-302** [comment]
Added
