### ISSUE TITLE
sandiegouniontribune.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5050]
***Site***: http://www.sandiegouniontribune.com/
***Description***: Ad leftover.

*Rules:*
```
sandiegouniontribune.com##.trb_mh_adB
sandiegouniontribune.com##.trb_gptAd
sandiegouniontribune.com##.trb_soh
sandiegouniontribune.com##.trb_ar_taboolaCmpn
sandiegouniontribune.com##.trb_ar_cont
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26275571/4b57d962-3d64-11e7-9fec-43b58f882f03.png)

*http://www.sandiegouniontribune.com/military/sd-me-seal-case-20170519-story.html:*

![image](https://cloud.githubusercontent.com/assets/10995998/26275631/c2fa65ce-3d65-11e7-889d-2b66e91bd396.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26275640/df63464a-3d65-11e7-8241-cfef6e373b53.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26275676/8430fbb8-3d66-11e7-807f-69f3a457f502.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.18.51
Spyware filter | 1.0.12.14
Social media filter | 1.0.19.57
Annoyances filter | 1.0.12.90
German filter | 1.0.34.7
Mobile ads filter | 1.0.8.42
Safari filter | 1.0.3.17

**Comment by seanl-adg** [comment]
Fixed.
Added similar rule for tronc inc. websites, they share similar layout

**Comment by danidoedel** [comment]
@seanl-adg Some ad leftover still there:

![image](https://cloud.githubusercontent.com/assets/10995998/26459226/05ece816-4176-11e7-98e5-a350bfa6c65b.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26459276/338dd4a6-4176-11e7-932e-905f907ef6f8.png)

**Comment by Alex-302** [comment]
It is clean on my iPad.
