### ISSUE TITLE
missed ad http://waitpost.ru/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5051]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: missed ad http://waitpost.ru/
![image](https://cloud.githubusercontent.com/assets/25711093/26275781/c12f537e-3d71-11e7-8523-c01b4fc3ae96.png)
![image](https://cloud.githubusercontent.com/assets/25711093/26275785/cee003b0-3d71-11e7-8029-f094b0a88ed6.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS / Android 
Browser: | chrome
Adguard version: | 1.4.1/2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | eng, rus, annoyance, spyware, social, mobile, experimental

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1562202

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
