### ISSUE TITLE
audio-track.com - anti-adblock

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#5053]
Попытка 2. Попробую еще раз. Буду краток как всегда. Adguard 2.9 , Android 4.4.4. Фильтры по-умолчанию, Фильтрация качественная, HTTPS вкл.
Сайт полной версии https://www.audio-track.com/articles/6-dub-mvo-dvo-chto-eto-takoe.html. 
![screenshot_2017-05-20-15-50-52](https://cloud.githubusercontent.com/assets/22351242/26275918/85665128-3d74-11e7-9e87-1599b5ad4eff.png)

**Comment by ministr91** [comment]
что-то пошло не так :D

**Comment by ameshkov** [comment]
`@@||audio-track.com/*/js/advertisement.js`

**Comment by Alex-302** [comment]
Добавил

**Comment by ministr91** [comment]
@ameshkov  спасибо, если бы не ты, то @Alex-302   не стал бы ничего делать :(

**Comment by Alex-302** [comment]
Стал бы. Прошлые же обработал.

**Comment by ministr91** [comment]
правда? Ну тогда все хорошо :)
