### ISSUE TITLE
Invalid cosmetic filter entry in (chromium) _English filter_ list

### ISSUE THREAD

**Issue by gorhill** [AdguardTeam/AdguardFilters#5054]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

There is what appears to be an invalid cosmetic filter in the (chromium) _English filter_ list<sup>[1]</sup>:

    euronews.com###sharethrough-ad-medium-up euronews.com##.enw-block-theme__mpu

Surely this is meant to be:

    euronews.com###sharethrough-ad-medium-up
    euronews.com##.enw-block-theme__mpu

?

[1] As seen at `https://filters.adtidy.org/extension/chromium/filters/2.txt`.

**Comment by Alex-302** [comment]
Thanks, fixed)
