### ISSUE TITLE
bunte.de - Incorrect blocking - missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5056]
http://www.bunte.de/panorama/politik/melania-trump-plumps-hier-macht-es-sich-die-first-lady-mal-richtig-bequem.html

***Description***:
* **Current behaviour**: 

Videos are blocked 
Ad after the article

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26280249/befa5c0e-3dd3-11e7-919f-7a78bed31cae.png)

![image](https://cloud.githubusercontent.com/assets/27292111/26280250/cbefaac2-3dd3-11e7-8f9d-01f57968ff39.png)

</details>

***System configuration***

Application version: 1.2.2.81

Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.18.51 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.14 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.57 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.90 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.7 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.42 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.17 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
I don't see that ad. Please check on your device.
Added to Spyware filter
```
@@||googletagmanager.com/gtm.js$domain=bunte.de
```

**Comment by veronikasav** [comment]
@Alex-302 don't see that ad on my device now as well.
It works. Thanks.
