### ISSUE TITLE
Duplicate & problematic rule

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#50575]
https://www.cpomagazine.com

<details><summary>Screenshot:</summary>

![www cpomagazine com](https://user-images.githubusercontent.com/34379403/75430704-c4181f80-595c-11ea-9232-940202e25863.png)

</details>

https://www.incelemeks.com
<details><summary>Screenshot:</summary>

![www incelemeks com](https://user-images.githubusercontent.com/34379403/75430778-e0b45780-595c-11ea-9491-cdd8de0387cc.png)

</details>

---

**This rule breaks buttons**

<details><summary>Screenshot:</summary>

![fon](https://user-images.githubusercontent.com/34379403/75430995-40126780-595d-11ea-8475-8e571543fdc1.png)

</details>

---

**Duplicate rule**

https://github.com/easylist/easylist/blob/aa5631d29a02d2235b90814fce543c49da03ae30/easylist/easylist_general_hide.txt#L18007

https://github.com/AdguardTeam/AdguardFilters/blob/843bbb3174f9849270edd37d5b06909426ae2c2b/TurkishFilter/sections/general_elemhide.txt#L119

**Comment by BlazDT** [comment]
Fixed

**Comment by PentagramTr** [comment]
@BlazDT 

Other duplicate rules
```
##.ads2
##.reklam
##.reklam2
```

https://github.com/easylist/easylist/blob/aa5631d29a02d2235b90814fce543c49da03ae30/easylist/easylist_general_hide.txt#L11737

https://github.com/easylist/easylist/blob/aa5631d29a02d2235b90814fce543c49da03ae30/easylist/easylist_general_hide.txt#L17716

https://github.com/easylist/easylist/blob/aa5631d29a02d2235b90814fce543c49da03ae30/easylist/easylist_general_hide.txt#L17720

**Comment by BlazDT** [comment]
Thank you, removed.

**Comment by PentagramTr** [comment]
@BlazDT 
I found a few more. Please remove them too.

---



`gunes.com,platinonline.com###reklam_center`
https://github.com/easylist/easylist/blob/6f53e7ffc64eb9179eaca2e3af04b9770d05291f/easylist/easylist_general_hide.txt#L6967

---
`gazetevatan.com##.adv728x90`
https://github.com/easylist/easylist/blob/6f53e7ffc64eb9179eaca2e3af04b9770d05291f/easylist/easylist_general_hide.txt#L3345

---

`soccereh.com##.player-ad` 
https://github.com/easylist/easylist/blob/6f53e7ffc64eb9179eaca2e3af04b9770d05291f/easylist/easylist_general_hide.txt#L17447

---

`basarisiralamalari.com###flyingBottomAd`
https://github.com/easylist/easylist/blob/6f53e7ffc64eb9179eaca2e3af04b9770d05291f/easylist/easylist_general_hide.txt#L5298

---

`globalklavye.com##.widget-ads`
https://github.com/easylist/easylist/blob/6f53e7ffc64eb9179eaca2e3af04b9770d05291f/easylist/easylist_general_hide.txt#L19713

---

`posta.com.tr##.adsbox`
https://github.com/easylist/easylist/blob/6f53e7ffc64eb9179eaca2e3af04b9770d05291f/easylist/easylist_general_hide.txt#L12110

---

`haberturk.com##.ads-300x600`
https://github.com/easylist/easylist/blob/6f53e7ffc64eb9179eaca2e3af04b9770d05291f/easylist/easylist_general_hide.txt#L11530

---

`||takvim.com.tr/ads.txt `
https://github.com/easylist/easylist/blob/83903b32af2a639c1238e255d2fc2dcc9f55524b/easylist/easylist_general_block.txt#L2397

---

`kayseriehaber.com,kocaelioncu.com##.left_ad_areas`
https://github.com/easylist/easylist/blob/6f53e7ffc64eb9179eaca2e3af04b9770d05291f/easylist/easylist_general_hide.txt#L16448

**Comment by Alex-302** [comment]
No. Some rules are working.
