### ISSUE TITLE
rovio.com - Annoyance - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5057]
http://www.rovio.com/

***Description***:
* **Current behaviour**: 

Cookie notice at the top of the website

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26280313/48f1f65e-3dd6-11e7-834d-d18c7f332c74.png)

</details>

***System configuration***

Application version: 1.2.2.81

Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.18.51 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.14 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.57 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.90 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.7 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.42 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.17 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
Fixed
