### ISSUE TITLE
missed ad http://kino-hd1080.ru/1809-boss-molokosos-2017-smotret-onlayn.html

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5061]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:missed ad http://kino-hd1080.ru/1809-boss-molokosos-2017-smotret-onlayn.html

after you press "Play" button, you are redirected to a page in the new tab with ads (parimatch/kazino/vulkan)

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | eng, rus, annoyance, spyware, social, mobile, experimental

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1562629

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
