### ISSUE TITLE
Anti Ad-Block at www.oploverz.in

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5062]
***Description***:
* **Current behaviour**: 
Anti Ad-Block at www.oploverz.in

Just open the link. Reproduced on our side.

Screenshot:

![screen shot 2017-05-21 at 18 30 39](https://cloud.githubusercontent.com/assets/27874000/26285188/811cd9d6-3e53-11e7-8fcd-8541fa8445c5.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Firefox
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Adguard filters: | English, Spyware, Social media, Annoyances, Experimental, ABPindo, Anti-Adblock Killer, User filter

Ticket ID: 1551511

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
