### ISSUE TITLE
incorrect blocking http://mywatchseries.to/cale.html

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5063]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
incorrect blocking http://mywatchseries.to/cale.html
protection blocks a video

Screenshot:
without blocking
<img width="2030" alt="screen shot 2017-05-21 at 19 13 01" src="https://cloud.githubusercontent.com/assets/25711093/26285488/a72445be-3e59-11e7-9693-9d0d7ec64afa.png">
with blocking
<img width="2014" alt="screen shot 2017-05-21 at 19 13 45" src="https://cloud.githubusercontent.com/assets/25711093/26285489/a88fa0a6-3e59-11e7-84f9-120faeb00894.png">

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | eng, rus, annoyance, spyware, social, mobile, experimental

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1556652

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@Michael23456 please ask for screenshot of the working video. Looks like fake player.

**Comment by Michael23456** [comment]
waiting for an answer from the customer
