### ISSUE TITLE
missed ad http://kinotut.tv/9/Serialy

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5064]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
missed ad http://kinotut.tv/9/Serialy
<img width="2046" alt="screen shot 2017-05-21 at 20 10 10" src="https://cloud.githubusercontent.com/assets/25711093/26285926/c6a91d30-3e61-11e7-9fe7-0ed935574422.png">

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS / Android 
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | eng, rus, annoyance, spyware, social, mobile, experimental

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1560071

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||puxrotate.ru$third-party
||95.213.231.34^$third-party
||pgold.pro^$third-party

```
