### ISSUE TITLE
anti-adblock http://www.zumvo.so/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5065]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
anti-adblock http://www.zumvo.so/
there is a message in top of the page
<img width="2034" alt="screen shot 2017-05-21 at 23 27 13" src="https://cloud.githubusercontent.com/assets/25711093/26287113/116d92fe-3e7d-11e7-9b6b-8a5962b7c7eb.png">

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | eng, rus, annoyance, social, spyware, mobile, experimental

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1478843

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
zumvo.so##.top-message
```
