### ISSUE TITLE
Polish ads filter -- Adguard supplement

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#5066]
https://forum.adguard.com/index.php?threads/important-polish-filter-addon-list.21172/#post-137050

This is an Adguard-specific supplement for the `Adblock polskie reguły`. We should have it as a separate filter (enabled by default for `pl`).

@mmigi @vbagirov please do it asap.

**Comment by vbagirov** [comment]
Done, waiting for the tasks above to be closed.
