### ISSUE TITLE
indeed.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5068]
***Site***: https://de.indeed.com/Jobs?q=fachinformatiker&l=Stuttgart
***Description***: Newsletter subscription in right sidebar und at the end of the page.

*Rules:*
```
indeed.com###tjobalertswrapper
indeed.com###bjobalertswrapper
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26310341/baf35fd8-3f00-11e7-910c-94b65de16a62.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26310360/cd4b984e-3f00-11e7-9b0c-62ff80bf2198.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.18.75
Spyware filter | 1.0.12.17
Social media filter | 1.0.19.61
Annoyances filter | 1.0.12.95
German filter | 1.0.34.13
Mobile ads filter | 1.0.8.43
Safari filter | 1.0.3.23

**Comment by Alex-302** [comment]
added
