### ISSUE TITLE
alphagamers.net - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5069]
***Site***: https://www.alphagamers.net/ and https://www.alphagamers.net/threads/regarding-extracting-and-reading-obb-files.13873/
***Description***: Ad leftover and ad post in forums.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26310545/677f888a-3f01-11e7-89d0-14e073b4ab8f.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26310572/88522568-3f01-11e7-8076-9d7f12688062.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.18.75
Spyware filter | 1.0.12.17
Social media filter | 1.0.19.61
Annoyances filter | 1.0.12.95
German filter | 1.0.34.13
Mobile ads filter | 1.0.8.43
Safari filter | 1.0.3.23

**Comment by seanl-adg** [comment]
Fixed

**Comment by danidoedel** [comment]
@seanl-adg Ad leftover in right sidebar is still there.
