### ISSUE TITLE
geizkragen.de / geizkragen.com/forum - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5070]
***Site***: http://www.geizkragen.de/ and http://www.geizkragen.com/forum/geiz-talk-die-plauderecke-im-forum/209777-empfehlenswerte-magazine-zu-historischen-themen.html
***Description***: Newsletter box at the bottom right side of the main page. Mister ad in forums.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26310666/f27f909c-3f01-11e7-9b29-ae9cc7c95197.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26310811/7c960e1e-3f02-11e7-9880-2be5162b9317.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.18.75
Spyware filter | 1.0.12.17
Social media filter | 1.0.19.61
Annoyances filter | 1.0.12.95
German filter | 1.0.34.13
Mobile ads filter | 1.0.8.43
Safari filter | 1.0.3.23

**Comment by Alex-302** [comment]
fixed
