### ISSUE TITLE
gamebanana.com - Ad - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5071]
***Site***: http://gamebanana.com/scripts/7454
***Description***: Ad leftovers, Ad in right sidebar. Sponsors at the end of the page.

*Rules:*
```
gamebanana.com###AtfLeaderboard
gamebanana.com###AtfSquareBannerModule
gamebanana.com###BtfSquareBannerModule
gamebanana.com###DasVerticalBannerModule
gamebanana.com###BtfLeaderboardRow
gamebanana.com###SponsorBrands
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26311145/8a0df7ea-3f03-11e7-96e2-7847c1bfaf05.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26311170/9bd05162-3f03-11e7-9b4c-ebe5d3b3dd78.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26311303/26316814-3f04-11e7-9ade-598e43a25103.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.18.75
Spyware filter | 1.0.12.17
Social media filter | 1.0.19.61
Annoyances filter | 1.0.12.95
German filter | 1.0.34.13
Mobile ads filter | 1.0.8.43
Safari filter | 1.0.3.23

**Comment by seanl-adg** [comment]
Fixed

**Comment by danidoedel** [comment]
@seanl-adg Sponsor brands at the bottom still there:
![image](https://cloud.githubusercontent.com/assets/10995998/26459127/bf232a30-4175-11e7-9660-1b1e9a1bc9e1.png)
