### ISSUE TITLE
aternos.org антиадблок

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#50719]
После регистрации, постоянно всплывает сообщение при передвижении по страницам сайта
![image](https://user-images.githubusercontent.com/19754243/75610967-63344700-5b16-11ea-8f4c-315a9f576978.png)

**Comment by krystian3w** [comment]
Problematic, site change scripts in 24-168 hours...

**Comment by krystian3w** [comment]
Duplicate of #46413
