### ISSUE TITLE
tvcok.ru - ad

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5072]
Pop-up on click on the video. Slightly randomly.

 URL:

http://www.tvcok.ru/film/prizrak-v-dospehah-2.html

<details><summary>Screenshot:</summary>

![screen shot 2017-05-22 at 18 18 09 2](https://cloud.githubusercontent.com/assets/28726429/26315954/6bab721a-3f1b-11e7-8b93-6c0bab642a60.png)

</details>

<br>
***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome, Safari
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 12, 14

**Comment by Alex-302** [comment]
Fixed
