### ISSUE TITLE
There should be a way to disable filter optimization for a rule

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#5073]
We need a hint for disabling rule optimization.

What is "hints":
https://github.com/AdguardTeam/AdguardFilters/issues/3708#issuecomment-303155314

What is "optimization":
https://adguard.com/en/filter-rules-statistics.html

### `NOT_OPTIMIZED` hint

Disables optimization for a rule.

**Examples:**

This rule won't be optimized:
```
!+ NOT_OPTIMIZED
||example.org^
```

This rule won't be optimized and will be available for Android only:
```
!+ NOT_OPTIMIZED PLATFORM(android)
||example.org^
```

**Comment by ameshkov** [comment]
@seanl-adg @Alex-302 one more "hint"

**Comment by Alex-302** [comment]
Is optimization affects whitelists and antiablock rules?

**Comment by ameshkov** [comment]
> Is optimization affects whitelists and antiablock rules?

Whichever rule you comment with a hint

**Comment by ameshkov** [comment]
Sorry, didn't get it. Yes, optimization affects all the rules.
