### ISSUE TITLE
Webpage http://www.transfermarkt.de/geruchtekuche/detail/forum/154/gk_wettbewerb_id/L1 doesn't load properly with Adguard enabled

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5075]
***Description***:

Issue reproduced on Windows (version 6.2) and Mac as well

* **Current behaviour**: 

Webpage http://www.transfermarkt.de/geruchtekuche/detail/forum/154/gk_wettbewerb_id/L1 doesn't load with Adguard enabled

Screenshot:

![screen shot 2017-05-22 at 9 11 09 pm](https://cloud.githubusercontent.com/assets/27874000/26322291/f87b4cf8-3f32-11e7-9dfe-85637aa95c8c.png)

* **Expected behaviour**: 

Screenshot:

![screen shot 2017-05-22 at 9 12 37 pm](https://cloud.githubusercontent.com/assets/27874000/26322312/1798f1bc-3f33-11e7-87ab-efeec60aed08.png)

***Steps to reproduce the problem***:

Just visit the following link

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP 
Adguard DNS: | None
Adguard filters: | English, German, Spanish, Portuguese, Adblock polskie reguły

Ticket ID: 1483141

**Comment by Alex-302** [comment]
Added to German filter
```
@@||ww251.smartadserver.com/ac?nwid=*&siteid=$domain=transfermarkt.de
```
