### ISSUE TITLE
hoerzu.de - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5076]
***Site***: https://www.hoerzu.de/
***Description***: Two ads.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26323088/d83b10a4-3f2d-11e7-97ca-d5f71fc3d4bd.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.18.75
Spyware filter | 1.0.12.17
Social media filter | 1.0.19.61
Annoyances filter | 1.0.12.95
German filter | 1.0.34.13
Mobile ads filter | 1.0.8.43
Safari filter | 1.0.3.23

**Comment by Alex-302** [comment]
added
```
hoerzu.de##.tvd-adtag+a > img
hoerzu.de###tvd-main > div[id="block-block-203"][-ext-has="> div.tvd-box > div[style] > div[style]:contains(ANZEIGE)"]

```
