### ISSUE TITLE
tvmovie.de - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5077]
***Site***: http://www.tvmovie.de/tv/wildes-neuseeland-100216442
***Description***: Ad and social widget leftover.

<details>
<summary>Screenshot</summary>

**_1. Ad leftover
2. Whatsapp newsletter subscription leftover
3. Social share button leftover
4. Ad leftover_**

![image](https://cloud.githubusercontent.com/assets/10995998/26323724/4636d050-3f30-11e7-8db5-022a2d3b0b90.png)

_**5. and 6. Ad leftover**_

![image](https://cloud.githubusercontent.com/assets/10995998/26323641/f0519f1c-3f2f-11e7-8a04-80b9e262f2e5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.18.75
Spyware filter | 1.0.12.17
Social media filter | 1.0.19.61
Annoyances filter | 1.0.12.95
German filter | 1.0.34.13
Mobile ads filter | 1.0.8.43
Safari filter | 1.0.3.23

**Comment by Alex-302** [comment]
added
tvmovie.de##.sharingbox
tvmovie.de##.adAnything
tvmovie.de#$#header > nav[role="navigation"] { margin-top: auto!important; }
