### ISSUE TITLE
Etcher.io web site makes Adguard crash, independent of browser used

### ISSUE THREAD

**Issue by engelhro** [AdguardTeam/AdguardFilters#5080]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)

***Description***:
* **Current behaviour**: 
Loading the website http://etcher.io/ makes Adguard crash. After a few seconds an error message appears: "An unexpected error has occurred.".

* **Expected behaviour**: 
The website should load and be useable afterwards.

***Steps to reproduce the problem***:

Just browse to the URL given above.

***System configuration***

Information | Value
--- | ---
Operating system: | Windows 10 (x64)
Browser: | Does not matter (crash reproduced with both Vivaldi as well as Pale Moon)
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Adguard DNS: | None
Stealth mode options (Windows) | all activated
Adguard filters: | various (English, spyware, social media, annoyances, German)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID (if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by vozersky** [comment]
Looks like social media filter is the culprit

![screen shot 2017-05-23 at 13 58 38](https://cloud.githubusercontent.com/assets/17472907/26351790/b118f09c-3fc1-11e7-9a99-4653796c88cf.png)

**Comment by Alex-302** [comment]
fixed
