### ISSUE TITLE
thinkster.io - Annoyance - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5081]
***Site***: https://thinkster.io/a-better-way-to-learn-angularjs/promises
***Description***: Newsletter overlay. Newsletter box at the top. Pro ad at the left side. Newsletter box and social leftover at the end of the page.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26332653/6e5e6e8a-3f58-11e7-9cd5-c31e38dad87b.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26332676/9dd7cb7a-3f58-11e7-936f-20321268fe05.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26332700/c723d6f4-3f58-11e7-99c3-2fa6d364bd4e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.18.75
Spyware filter | 1.0.12.17
Social media filter | 1.0.19.61
Annoyances filter | 1.0.12.95
German filter | 1.0.34.13
Mobile ads filter | 1.0.8.43
Safari filter | 1.0.3.23

**Comment by Alex-302** [comment]
added
