### ISSUE TITLE
paper.dropbox.com

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#5084]
Can't load the page when filtering is enabled
Looks like the spyware filter is the culprit

![screen shot 2017-05-12 at 19 22 28](https://cloud.githubusercontent.com/assets/17472907/26007374/ed18b4d2-3748-11e7-8f9f-8e92a67632f0.png)

looks like the spyware filter is the culprit

**Comment by Alex-302** [comment]
I see blank page without Adguard.

**Comment by zebrum** [comment]
@Alex-302  
TW me

**Comment by Alex-302** [comment]
removed
```
||marketing.dropbox.com^
```
