### ISSUE TITLE
Missed ads on http://www.liftable.com/lindsayharp/drs-say-age-9-daughter-w-cancer-48-hrs-live-next-day-mom-knows-witnessed-miracle/

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5085]
***Description***:

Paid content is not blocked on http://www.liftable.com/lindsayharp/drs-say-age-9-daughter-w-cancer-48-hrs-live-next-day-mom-knows-witnessed-miracle/ (and all over the website in general)

Reproduced on Windows (v 6.2, basic filters) and Mac

Screenshot:

![screen shot 2017-05-23 at 14 24 47](https://cloud.githubusercontent.com/assets/27874000/26352188/573fbefa-3fc3-11e7-9b32-35a15103e282.png)

***Steps to reproduce the problem***:

Just check the link, under Paid content

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
Adguard filters: | English

Ticket ID: 771224

**Comment by Alex-302** [comment]
Fixed
