### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#50861]
<details><summary>Screenshot:</summary>

![github com](https://user-images.githubusercontent.com/34379403/75797295-02ab4100-5d86-11ea-8033-679895164bda.png)

</details>

Remove this rule because there is already a general rule.

https://github.com/AdguardTeam/AdguardFilters/blob/9eb370371988985e1cb77d4120f94c01c511899c/AnnoyancesFilter/sections/popups.txt#L1282

---

This is the sharing rule. Move to the Social filter

https://github.com/AdguardTeam/AdguardFilters/blob/576e7d2b018eef0d2ce3c414f12d9f14d9d69efc/TurkishFilter/sections/specific.txt#L3146

**Comment by AdamWr** [comment]
Fixed.
Thank you.
