### ISSUE TITLE
Show Warning in Browser Console

### ISSUE THREAD

**Issue by 9iky6** [AdguardTeam/AdguardFilters#5087]
***Description***:
* **Current behaviour**: 
При открытии окна отладки кода в браузере всегда вылезает предупреждение.

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://image.prntscr.com/image/01dceac78f5141e58dd775e05f228a42.png)
</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Vivaldi (chrome)
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP / TDI
Adguard mode (Android): | VPN / Proxy(manual/auto)
Filtering quality (Android): | High-quality / high-speed / simplified
HTTPS filtering (Android): |  On (Default/Blacklist mode) / Off
Simplified filters(iOS) | On / Off
Adguard DNS: | None / Default / Family Protection
Stealth mode options(Windows) | 
Adguard filters: | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Это норма. Браузер выводит сообщение, что запрос заблокирован.
