### ISSUE TITLE
inversting.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#5088]
Missed ads (tested in Chrome):
https://www.screencast.com/t/qxGgaMbPK

Filters:
* English
* Russian
* Spyware
* Social
* Annoyances

**Comment by Alex-302** [comment]
![image](http://imagizer.imageshack.com/img923/1558/CLEVRR.png)

**Comment by sandybeachit** [comment]
I get the same as Alex


![image](https://user-images.githubusercontent.com/11394779/27153259-b23930a2-5148-11e7-980b-4e8840626f68.png)
