### ISSUE TITLE
articlesjar.com - anti-adblock script

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5089]
Appears in 3-5 seconds.

URL:

https://www.articlesjar.com/

<details><summary>Screenshot:</summary>

![screen shot 2017-05-24 at 12 05 19](https://cloud.githubusercontent.com/assets/28726429/26395628/52dd1f5e-4079-11e7-8270-312dd7149db2.png)

</details>

<br>
***System configuration***

Information | Value
--- | ---
Operating system: | MacOS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 12, 14

**Comment by Alex-302** [comment]
Fixed
