### ISSUE TITLE
Anti Ad-Blocker at https://arkforum.de/

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#5090]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Just open   https://arkforum.de/wiki/index.php/Entry/422-Allosaurus/    and wait for 20-30 sec.

Reproduced on our side.

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/26434103/26399996/b602e90c-4087-11e7-9c4b-01469094e04d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | Russian, Englisch, German, Annoyances, Spyware, Social media

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1483141

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
