### ISSUE TITLE
http://www.paklight-sharing.com/ - missed ad 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5091]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://www.paklight-sharing.com/  when you click on any link on the website, the pop-up opens in another tab https://dailysong.tk/
reproduced on iOS 10.3.1 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot: 

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/26406745/db4476ee-40a1-11e7-89c6-7fa18b88ae55.png)

![image](https://cloud.githubusercontent.com/assets/23372054/26406702/bc9237a4-40a1-11e7-9801-c6ae14a58a9a.png)

</details>

***System configuration***

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3.2
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.17.85 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.3 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.42 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.68 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.1.3 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.34 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.11 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.51 Enabled=NO
ID=237 Name="AdBlock Protector List" Version=1.0.0.14 Enabled=NO

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1563328

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Safari filter
```
||goo.gl^$domain=paklight-sharing.com,popup
```
