### ISSUE TITLE
Missed ads on https://riafan.ru/781523-shoigu-sravnil-voennye-rashody-ssha-i-rossii

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5092]
***Description***:

Reproduced on Mac with basic filters set as well

* **Current behaviour**: 

Missed ads on https://riafan.ru/781523-shoigu-sravnil-voennye-rashody-ssha-i-rossii

Screenshot:

![screen shot 2017-05-24 at 5 36 06 pm](https://cloud.githubusercontent.com/assets/27874000/26408839/88819fa8-40a7-11e7-8222-db6a6ab1eadc.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP 
Adguard filters: | English, Spyware, Social media, Annoyances, Filter unblocking useful ads, Russian

Ticket ID: 1449704

**Comment by Alex-302** [comment]
Fixed.
