### ISSUE TITLE
bie-dro.de - Element blocking

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5093]
***Description***:
* **Current behaviour**: 

The upper bar with the language switcher and some menu elements is disabled while using Adguard.

Screenshot:

<details>

Adguard enabled

![image](https://cloud.githubusercontent.com/assets/27292111/26431868/4fbb6312-4100-11e7-8db4-6af4e4f4d431.png)

Adguard disabled

![image](https://cloud.githubusercontent.com/assets/27292111/26431891/790ee8e2-4100-11e7-86d8-0e76c402afa9.png)

html code that is blocked by Adguard

![screen shot 2017-05-25 at 4 19 46 am](https://cloud.githubusercontent.com/assets/27292111/26432034/6461f38e-4101-11e7-9247-5e68148484c5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome  
Adguard version: | 6.2 beta / 1.4.1 
Adguard driver (Windows): | WFP 
Adguard filters: | 1 2 3 4 5 6 14

Ticket ID: 1564166

**Comment by Alex-302** [comment]
Fixed
