### ISSUE TITLE
gumtree.com.au - posting fails

### ISSUE THREAD

**Issue by hoonkai** [AdguardTeam/AdguardFilters#5095]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

http://www.gumtree.com.au/p-post-ad2.html?categoryId=20025&adType=OFFER

Error on Safari: "The URL was blocked by a content blocker (WebKitErrorDomain: 104)"

Screenshot:

![image](https://i.imgur.com/zRnKfwT.png)
</details>

* **Expected behaviour**: 

Create Post page should successfully load.

***Steps to reproduce the problem***:

Switch on English Filters and go to  http://www.gumtree.com.au/p-post-ad2.html?categoryId=20025&adType=OFFER

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Adguard version: | Safari Extension

**Comment by Alex-302** [comment]
Added to Safari filter
```
@@||gumtree.com.au/p-post-ad*.html
```
