### ISSUE TITLE
evensi.de - Annoynace - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5096]
***Site***: https://evensi.de/1-php-web-entwicklung-meetup-sebastian-feldmann-automating/204739418#

<details>
<summary>Screenshot</summary>

Mobile app banner and social widget bar:

![image](https://cloud.githubusercontent.com/assets/10995998/26454999/12cb23ca-4169-11e7-84d3-75c7a76bb9a6.png)

Newsletter box when scrolling down:

![image](https://cloud.githubusercontent.com/assets/10995998/26455103/7bcf1fb6-4169-11e7-806c-3e1eee17ca69.png)

Overlay:

![image](https://cloud.githubusercontent.com/assets/10995998/26455175/ac1d79a6-4169-11e7-8b57-816c7114ac90.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.19.15
Spyware filter | 1.0.12.37
Social media filter | 1.0.19.80
Annoyances filter | 1.0.13.25
German filter | 1.0.34.30
Mobile ads filter | 1.0.8.49
Safari filter | 1.0.3.32

**Comment by seanl-adg** [comment]
Fixed.
