### ISSUE TITLE
sueddeutsche.de - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5098]
***Site***: http://www.sueddeutsche.de/politik/reportage-vom-kirchentag-barack-obama-merkels-weichzeichner-1.3521020
***Description***: Social widget.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26455557/e5d6d380-416a-11e7-9c75-c7f620acb375.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.19.15
Spyware filter | 1.0.12.37
Social media filter | 1.0.19.80
Annoyances filter | 1.0.13.25
German filter | 1.0.34.30
Mobile ads filter | 1.0.8.49
Safari filter | 1.0.3.32

**Comment by Alex-302** [comment]
fixed
