### ISSUE TITLE
berliner-zeitung.de - Annoyance - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5099]
***Site***: http://mobil.berliner-zeitung.de/
***Description***: Whatsapp newsletter subscription. Social widget leftover.

<details>
<summary>Screenshot</summary>

*http://mobil.berliner-zeitung.de/:*

![image](https://cloud.githubusercontent.com/assets/10995998/26455679/362294fa-416b-11e7-9579-78ab180bc045.png)

*http://mobil.berliner-zeitung.de/politik/nato-gipfel-in-bruessel-trump-und-eu-verfolgen-gegensaetzliche-interessen-26967280:*

![image](https://cloud.githubusercontent.com/assets/10995998/26455776/715550bc-416b-11e7-87c0-a267540d3b21.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26455863/b3711e18-416b-11e7-874b-ec6b52ab49d9.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.19.15
Spyware filter | 1.0.12.37
Social media filter | 1.0.19.80
Annoyances filter | 1.0.13.25
German filter | 1.0.34.30
Mobile ads filter | 1.0.8.49
Safari filter | 1.0.3.32

**Comment by seanl-adg** [comment]
Fixed
