### ISSUE TITLE
mittelbayerische.de - Annoyance - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5100]
***Site***: http://www.mittelbayerische.de/wirtschaft-nachrichten/das-duell-um-die-grammer-ag-21840-art1522165.html
***Description***: Cookie notice at the top. Social widget.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26455972/05fcf5a8-416c-11e7-936c-f26968a03f0d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.19.15
Spyware filter | 1.0.12.37
Social media filter | 1.0.19.80
Annoyances filter | 1.0.13.25
German filter | 1.0.34.30
Mobile ads filter | 1.0.8.49
Safari filter | 1.0.3.32

**Comment by Alex-302** [comment]
Please do not accumulate issues for a long time. Post them straight away if it is possible.

**Comment by danidoedel** [comment]
I found all of that today... Nothing I can do about that...

**Comment by Alex-302** [comment]
Fixed.
