### ISSUE TITLE
esslinger-zeitung.de - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5102]
***Site***: https://www.esslinger-zeitung.de/
***Description***: Ad leftover and social widgets.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26457313/fca82384-416f-11e7-906e-d831a8b9d008.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26457299/f2764f26-416f-11e7-8d4f-12eac71726c0.png)

*https://www.esslinger-zeitung.de/region/polizei_artikel,-betrunken-unfall-verursacht-und-abgehauen-_arid,2126132.html:*

![image](https://cloud.githubusercontent.com/assets/10995998/26457337/15c6511a-4170-11e7-9b3b-3ef5a735c9b6.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26457399/3e53598e-4170-11e7-9d3c-0a52823e934c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.19.15
Spyware filter | 1.0.12.38
Social media filter | 1.0.19.81
Annoyances filter | 1.0.13.25
German filter | 1.0.34.30
Mobile ads filter | 1.0.8.49
Safari filter | 1.0.3.32

**Comment by Alex-302** [comment]
fixed
