### ISSUE TITLE
anime-odcinki.pl - Pop-ups

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5103]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

Annoying pop ups when trying to watch a video on anime-odcinki.pl
Reproduced at our side.

***Steps to reproduce the problem***:

1. Go on anime-odcinki.pl
2. Find any video and turn it on

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP 
Adguard DNS: | None 
Stealth mode options(Windows) | enabled
Adguard filters: | 2, 3, 4, 216, 0

Ticket ID: 1564890

[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by F4z** [comment]
I think these popups are from video player from vidfile.net.
Popup script - `https://d1k0glcmk0b5rb.cloudfront.net/ScjhUbUpNTD0Jd0QOZV58Sw%3D%3D`
This rule should work:
`||d1k0glcmk0b5rb.cloudfront.net^`
or
`||cloudfront.net^$domain=vidfile.net`
or
`vidfile.net#%#Object.defineProperties(window,{admvpu:{get:function(){},set:function(a){if("function"==typeof a)throw Error();}},Fingerprint2:{get:function(){},set:function(){throw Error();}}});`

I also see ad, for example here - `https://anime-odcinki.pl/anime/busou-shoujo-machiavellianism/8`

<details><summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/11742596/26468725/c1df1da2-4197-11e7-9e19-34cc195067fd.png)
</details>

<br>

These filters should block this ad:
`||p5.llog.pl^`
`||llog.pl^$third-party`
or
`||llog.pl^`

**Comment by Alex-302** [comment]
We need all three rules
