### ISSUE TITLE
rhein-zeitung.de - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5105]
***Site***: http://www.rhein-zeitung.de/
***Description***: Ad leftover. Social widget leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26469286/b94f0344-4199-11e7-9090-44b95e0546a2.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26469459/537eaa50-419a-11e7-9ec3-768a9ccb1fee.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26469419/32c26900-419a-11e7-905a-b62975ea6d96.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.19.15
Spyware filter | 1.0.12.39
Social media filter | 1.0.19.82
Annoyances filter | 1.0.13.26
German filter | 1.0.34.30
Mobile ads filter | 1.0.8.49
Safari filter | 1.0.3.32

**Comment by danidoedel** [comment]
@Alex-302 Ad leftover on mobile still there:

![image](https://user-images.githubusercontent.com/10995998/27377767-34a6fd4e-5676-11e7-97a6-48e2b0be8aaa.png)

*Rule:* 
`rhein-zeitung.de###container_banner`

**Comment by Alex-302** [comment]
added
