### ISSUE TITLE
interracial.com [NSFW] [Pop-up]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#51069]
https://www.interracial.com/videos/12621/mandy-muse-get-her-ass-filled-with-rob-piper-s-monster-meat-and-cum/

Seeing pop-up upon playback. Also seeing ad banner on the player when video is paused. Checked with AG for Chrome

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.

**Comment by Nzzyme** [comment]
https://www.interracial.com/videos/5631/assfucked-by-bbc/

Seeing ad text string on the right side of the page.

**Comment by AdamWr** [comment]
Fixed.
