### ISSUE TITLE
zeusnews.it - anti-adblock script

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5106]
Main page is OK. Only in articles. Appears in 3-5 seconds.

URL:

http://www.zeusnews.it/n.php?c=25357

<details><summary>Screenshot:</summary>

![img_0005](https://cloud.githubusercontent.com/assets/28726429/26489993/3c78ef6e-4212-11e7-9e09-912fb9c08470.PNG)
#
</details>

<br>
***System configuration***

Information | Value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.2.1
Adguard filters: | 1, 2, 3, 4, 11, 12, 14, 109

**Comment by uBlock-user** [comment]
Filter - `||zeusnews.it/antiadb.js`

**Comment by altokarev** [comment]
Works for me.

**Comment by Alex-302** [comment]
Added.
