### ISSUE TITLE
Incorrect blocking on https://anistar.me/

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5107]
***Description***:

На сайте https://anistar.me/ в правом углу видеоплеера должно быть переключение качества, которого нет.

* **Current behaviour**: 

Screenshot:

![capture](https://cloud.githubusercontent.com/assets/27874000/26488582/abb55cc4-420c-11e7-8df3-acd28538b3c3.PNG)

* **Expected behaviour**: 

Screenshot:

![capture1](https://cloud.githubusercontent.com/assets/27874000/26488589/b2598f78-420c-11e7-993e-881f75752b41.PNG)

***Steps to reproduce the problem***:

На сайте https://anistar.me/ выбрать в плеере HDGO

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP 
Adguard filters: | English, Spyware, Social media, Annoyances, Russian

Ticket ID: 1412565

**Comment by F4z** [comment]
I think they are checking if adblock is enabled.
Something like this should works:
`hdgo.cx#%#window.canRunAds = true;`
or
`@@||hdgo.cx/advert_$script`
Link to video player - `https://hdgo.cx/video/t/t758fpy8vhuvpyuhgrnon79l/225657/`
`http://hdgo.cx/advert_181.js`

**Comment by Alex-302** [comment]
Yes, it is well known video hosting, with a lot of domains.
Fixed.
