### ISSUE TITLE
online-convert.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#51083]
[https://www.online-convert.com/faq](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.online-convert.com/faq)

Cookie and add-on annoyances:

![onlien-convert](https://user-images.githubusercontent.com/35470489/76143525-e134a880-6056-11ea-9d6c-24644373a514.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by AdamWr** [comment]
Fixed cookie notice, but I couldn't reproduce this add-on popup.
If you still see this then please make a screenshot with code of this element.

**Comment by adranger** [comment]
It is actually added to the same div, so your filter already hid it.

![online converter](https://user-images.githubusercontent.com/35470489/76264110-8e6a1500-623f-11ea-84d3-d02cf35018f9.png)

**Comment by AdamWr** [comment]
Ok, thank you for your reply.
