### ISSUE TITLE
Anti-adblocker on: ff14angler.com

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5108]
***Description***:

ff14angler.com detects adblocking and prevents the user from seeing
anything.

* **Current behaviour**: 

Screenshot:

![screen shot 2017-05-26 at 12 40 00](https://cloud.githubusercontent.com/assets/27874000/26489472/3349aec6-4210-11e7-95f9-8d3cc1d401d9.png)

* **Expected behaviour**: 

Screenshot:

![screen shot 2017-05-26 at 12 40 54](https://cloud.githubusercontent.com/assets/27874000/26489503/4f84c224-4210-11e7-8fc7-ebc0bc66bae3.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP 
Adguard filters: | English

Ticket ID(if exists): 1564688

**Comment by F4z** [comment]
I think these rules should resolve this issue,
`ff14angler.com#@#.adsbygoogle`
`ff14angler.com###main > .adsbygoogle`

**Comment by uBlock-user** [comment]
`@@||ff14angler.com^$generichide`

**Comment by Alex-302** [comment]
> I think these rules should resolve this issue,
> ff14angler.com#@#.adsbygoogle
> ff14angler.com###main > .adsbygoogle

added
