### ISSUE TITLE
beauty plus APP

### ISSUE THREAD

**Issue by gemini153** [AdguardTeam/AdguardFilters#51098]
beauty plus
APP

**Comment by krystian3w** [comment]
> 
> ### Issue URL (Ads)
> 
> [https://github.com/AdguardTeam/AdguardFilters/issues/51098#issue-577357335](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fgithub.com%2FAdguardTeam%2FAdguardFilters%2Fissues%2F51098%23issue-577357335)
> ### Comment
> 
> Username: @gemini153
> 
> > 
> 
> ### Screenshots
> Screenshot 1
> Screenshot 2
> ### System configuration
> Information 	value
> Platform: 	And 10
> AdGuard version: 	3.3.2 (230)
> Browser: 	samsung internet
> AdGuard mode: 	VPN
> Filtering quality: 	High-quality
> HTTPS filtering: 	enabled
> DNS requests blocking: 	enabled
> Filters: 	Ad Blocking:
> AdGuard Base,
> AdGuard Mobile Ads
> 
> Privacy:
> AdGuard Tracking Protection
> 
> Social Widgets:
> AdGuard Social Media
> 
> Language-specific:
> List-KR
> Other extensions used: 	유니콘

**Comment by BlazDT** [comment]
Please post appstore link.

**Comment by krystian3w** [comment]
https://play.google.com/store/apps/details?id=com.commsource.beautyplus&hl=kr

**Comment by BlazDT** [comment]
How to trigger 2nd screenshot? After adding following rule I do not see first screen anymore (cleared also app cache and data):

`||graph.facebook.com^$app=com.commsource.beautyplus`

Please note this rule breaks facebook login. Sadly the app does not trust user certificates.

**Comment by Alex-302** [comment]
@BlazDT Facebook app must be instaled and logged in.
