### ISSUE TITLE
techtarget.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5110]
***Site***: http://searchenterprisedesktop.techtarget.com/tip/Windows-10-keylogger-adds-fuel-to-the-privacy-fire
***Description***: Signup form.

*Rule:*
```
techtarget.com##.sign-up-wrapper
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26492001/496461cc-4212-11e7-98b3-7810ad38d1e7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.19.24
Spyware filter | 1.0.12.43
Social media filter | 1.0.19.85
Annoyances filter | 1.0.13.30
German filter | 1.0.34.32
Mobile ads filter | 1.0.8.49
Safari filter | 1.0.3.33

**Comment by seanl-adg** [comment]
Fixed
