### ISSUE TITLE
schnaeppchenfuchs.com - Ad leftover - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5113]
***Site***: https://schnaeppchenfuchs.com/
***Description***: Partner header and app promo at the top. Ad leftover and newsletter form in right sidebar. Cookie notice at the bottom.

*Rules for German filter:*
```
schnaeppchenfuchs.com##.partners
schnaeppchenfuchs.com##div[id^="adslot-"]
```

*Rules for Annoyance filter:*
```
schnaeppchenfuchs.com##.header-promo-apps
schnaeppchenfuchs.com##.sidebar-newsletter
schnaeppchenfuchs.com##.cookie-agreement
```

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26492976/4eec8b56-4217-11e7-8d93-d3c926b75677.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26492914/fb1bae4e-4216-11e7-9935-f0a61e336c6b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.19.24
Spyware filter | 1.0.12.43
Social media filter | 1.0.19.85
Annoyances filter | 1.0.13.30
German filter | 1.0.34.32
Mobile ads filter | 1.0.8.49
Safari filter | 1.0.3.33

**Comment by danidoedel** [comment]
@Alex-302 Whatsapp newsletter in sidebar:

![image](https://user-images.githubusercontent.com/10995998/27378089-0cd16704-5677-11e7-8927-4f1a7774127d.png)

*Rule:*
`schnaeppchenfuchs.com##.sidebar-whatsapp`

**Comment by Alex-302** [comment]
added
