### ISSUE TITLE
Правила против пользователей в фильтре против рекламы (ruadlist)

### ISSUE THREAD

**Issue by a-ladanov** [AdguardTeam/AdguardFilters#51142]
В подписке против рекламы Ruadlist произошел любопытный случай.
Один из авторов, dimisa, добавил в основную подписку против рекламы правило, из-за которого все пользователи Ruadlist не могут видеть все сообщения конкретных пользователей на всем форуме. Сообщения не были рекламными. Автор подписки посчитал их флудерами, и, якобы, из-за бездействия модераторов, добавил правила в основной список.
Замечу, что правило добавлено в основной фильтр Ruadlist, который используется и в uBlock. Не в какой-то дополнительный, не в личный. И сделал это тихо.
Блокируются сообщения NikosColev и MP40
Пруфы:
https://hg.adblockplus.org/ruadlist/rev/051af9f844f6
https://hg.adblockplus.org/ruadlist/rev/197bb994911f#l3.12
Место, где произошел конфликт
http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=200#9

(кстати, из этой темы полностью убрали упоминание Adguard, по его же решению)

Меня интересует, как вы оцениваете такое решение своего коллеги? Стоит ли ожидать такие действия от работников Adguard?
И как с этим бороться, куда жаловаться в таком случае?
Пользователи должны знать, что может творить подписка. Стоит ли этот случай упоминания в блоге? Ведь многие пользователи Adguard пользуются и ruadlist.

@ameshkov, @Alex-302, @vbagirov, @Dariamag, @zebrum

**Comment by krystian3w** [comment]
@dimisa-RUAdList

**Comment by Alex-302** [comment]
Омг, и сюда принесли.

**Comment by ameshkov** [comment]
@Alex-302 

> Меня интересует, как вы оцениваете такое решение своего коллеги? Стоит ли ожидать такие действия от работников Adguard?

Не стоит.

> И как с этим бороться, куда жаловаться в таком случае?
> Пользователи должны знать, что может творить подписка. Стоит ли этот случай упоминания в блоге? Ведь многие пользователи Adguard пользуются и ruadlist.

Я не думаю, что мы моожем давать какие-то советы давать в данном конкретном случае.

**Comment by krystian3w** [comment]
Maybe you need to add a filter to the exclusions?

And in the future, the argument is not to hide the filters for a small part of the whole Internet.
