### ISSUE TITLE
phim.media - Ad leftover

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5115]
***Description***:
there are still ads showing up on http://www.phim.media/
reproduced on our side as well

Screenshot:

<details>

![screen shot 2017-05-26 at 4 08 20 pm](https://cloud.githubusercontent.com/assets/28784344/26495785/9eecfeea-422d-11e7-86ce-342bcaf6ddc6.png)

</details>

***Steps to reproduce the problem***:

1. Go on **http://www.phim.media/**

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | any
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP 
Adguard DNS: | None 
Stealth mode options(Windows) | enabled
Adguard filters: | 2, 3, 4, 5, 14, 208, 210, 0

Ticket ID(if exists): 1478843

**Comment by Alex-302** [comment]
Fixed
