### ISSUE TITLE
buzzfeed.com - Annoyance 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5116]
https://www.buzzfeed.com/susiearmitage/this-new-report-shows-how-bad-chechnyas-gay-crackdown?utm_term=.ewnm6PlNl#.wob4nvKYK

***Description***: 
* **Current behaviour**: 

Pop-up share button appears even during scrolling.

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26498606/3e6890ce-4238-11e7-82c6-02f9ea05fa0f.png)

</details>

***System configuration***

Application version: 1.2.1.71
Platform: iOS
OS: 10.3.3

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.19 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.41 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.83 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.26 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.67 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.49 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.33 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.80.79 Enabled=YES

Ticket ID: 1355668

**Comment by Alex-302** [comment]
Fixed
