### ISSUE TITLE
genius.com - unblocked pop-up - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5117]
Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26502132/3eb2a040-4244-11e7-954a-2989a57d0ed9.png)

</details>

***System configuration***

Application version: 1.2.1.71
Platform: iOS
OS: 10.3.3

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.19 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.41 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.83 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.26 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.67 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.49 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.33 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.80.79 Enabled=YES

Ticket ID: 1355668

**Comment by Alex-302** [comment]
Can't reproduce it even without Adguard. Please create a rule by Adguard tool and send it to me.

**Comment by veronikasav** [comment]
@Alex-302 Can not be reproduced on the same device twice. Tried to reproduce on a new one but while blocking by Adguard tool it disappears without creating any rules.

**Comment by Alex-302** [comment]
Can't find this element in the code.
Blocked analytics
```
||librato-collector.genius.com^
```
