### ISSUE TITLE
phim.media - Video Bug

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5118]
***Description***:
On http://www.phim.media/ in Microsoft Edge, ( with TCP in both cases - either enabled or disabled) videos can not be loaded; the pop-up, stating to turn off any ad blocking program( in our case Adguard), appears. Reproduced at our side as well.

Screenshot:

<details>

![screen shot 2017-05-26 at 7 21 51 pm](https://cloud.githubusercontent.com/assets/28784344/26503274/b53a17f8-4248-11e7-908e-9e6ed33a6dba.png)

</details>

<details>

![screen shot 2017-05-26 at 7 23 41 pm](https://cloud.githubusercontent.com/assets/28784344/26503311/df1524be-4248-11e7-8ea1-445c6754bb97.png)

</details>

***Steps to reproduce the problem***:

1.Go on http://www.phim.media/
2. Choose any video and turn it on, for example:
http://www.phim.media/phim-hiep-khach-mat-na-den/tap-1.html 

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Edge
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP 
Adguard DNS: | None 
Stealth mode options(Windows) | enabled
Adguard filters: | 2, 3, 4, 5, 14, 208, 210, 0

Ticket ID: 1478843

**Comment by Alex-302** [comment]
It is Vietnamese lang site. Enabling of `ABPVN List` will helps.

**Comment by KozelElena** [comment]
enabling ABPVN List didn't help, I was still able to reproduce it with the filter enabled as well.

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/26526289/8038e552-437e-11e7-9491-2f39be27d78c.png)

![image](https://cloud.githubusercontent.com/assets/17320558/26526291/825b4db6-437e-11e7-85c5-6974a0b2827e.png)

</details>

**Comment by ypetruk** [comment]
"phim.media" still has problems playing videos on Microsoft Edge browser. The videos loaded at the beginning then there's an ad which was blocked by Adguard but the video disappears after a few seconds. You can still hear the sound of it but no video.

Ticket ID: 1478843

**Comment by ypetruk** [comment]
There is an annoying page pop up on "phim.media" site whenever I
click on play any videos on that site. Please block it from appearing.
Here is the link to the pop up:
http://btc-news.us/143/cointelegraph-events-humaniq-announce-blockchain-oscar-winners.html?utm_id=http://www.phim.media/phim-vo-boc-ma/xem-online.html

Ticket ID: 1604852

**Comment by Alex-302** [comment]
Added to English filter
```
@@||js.genieessp.com/t^$domain=www.phim.media
@@||static.gammaplatform.com/js/ad-exchange.js$domain=phim.media
```
please check
