### ISSUE TITLE
Yellow Ablock warning popup on the site: nl.hardware.info

### ISSUE THREAD

**Issue by gvanosch12** [AdguardTeam/AdguardFilters#5119]
Hi Everyone,

On the site nl.hardware.info there are showing an yellow adblock warning message wich is detected by the site.
Can you please update the dutch filter list wich removes this yellow ad block warning message popup  on this site.

https://nl.hardware.info/nieuws/47979/chrome-gaat-adobe-flash-standaard-blokkeren-en-gaat-over-op-html5

![schermopname 12](https://cloud.githubusercontent.com/assets/19804873/26504378/ac1bdf70-4244-11e7-86df-e3bfb3f55b5a.png)

Thanks! in advance

Kindly regards,

Geert Van Osch

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
hardware.info#%#AG_onLoad(function() { var el=document.querySelector('button.btn-tertiary[name="accept"]'); if(el) el.click(); });
```

**Comment by gvanosch12** [comment]
Hi Alex,

I have installed and updated the Annoyance filter but unforteanally it doesn;t work,the yellow adblock warning message popup is still visible,if i visited the site.

Geert

**Comment by Alex-302** [comment]
I can't reproduce it now

<details>

![image](http://imagizer.imageshack.com/img923/266/W6Utib.png)
</details>

**Comment by Alex-302** [comment]
Please check in private tab without another extensions.

**Comment by gvanosch12** [comment]
I have tried the incognito modus(private tab) at chrome,but the yellow popup message screen still comes up

**Comment by gvanosch12** [comment]
Maybey it works if the anti-Adblock warning Filter Rule are added to the Dutch(Netherlands) Filter for my specific location,before on another similar issue it works

**Comment by Alex-302** [comment]
@gvanosch12 can you show me HTML code of that element?

**Comment by gvanosch12** [comment]
https://filters.adtidy.org/extension/chromium/filters/8.txt

**Comment by gvanosch12** [comment]
https://github.com/AdguardTeam/AdguardFilters/blob/master/DutchFilter/sections/antiadblock.txt

**Comment by gvanosch12** [comment]
#4664

On March 24 (seanl-adg) has added the above script to the Dutch filter on the website:
allaboutphones.nl with a similar adblock warning popup message wich has resolved the issue and has removed the Pink Adblock Warning Screen on the dutch website allaboutphones.nl

**Comment by Alex-302** [comment]
@gvanosch12 Without annoyances filter I see  grey message
http://imagizer.imageshack.com/img923/1417/q1G7mB.png
Please make screenshot of HTML from developer tools

**Comment by F4z** [comment]
@Alex-302 I can reproduce.

<details><summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/11742596/26676768/7b222e90-46c9-11e7-98f8-bd5f2ae64f70.png)
</details>

<br>

This rule works on my end:
`nl.hardware.info#@#.advertorial`
or
`nl.hardware.info#$#.advertorial { height: 1px !important; }`

**Comment by gvanosch12** [comment]
Can you please add this rule to the dutch filter,i still see the yellow adblock warning screen

**Comment by Alex-302** [comment]
Thanks, added.
