### ISSUE TITLE
[Android] korzik.net

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#512]
http://screencast.com/t/KGl7xLL4Y - реклама

https://qcrm.cc/#/customer/1029341

**Comment by Alex-302** [comment]
||krutilka.net^$empty
добавил в моб фильтр

**Comment by vgavrish** [comment]
korzik.net вверху сайта большой рекламный банер "вулкан подарков".
http://prntscr.com/blkmex

**Comment by Alex-302** [comment]
поправил.
