### ISSUE TITLE
tchgdns.de - missed ad - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5121]
https://tchgdns.de/powy-android-powerbutton-shortcuts/
https://tchgdns.de/

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26506756/494fad9c-4256-11e7-8d1a-fd1856ae9fd2.png)

![image](https://cloud.githubusercontent.com/assets/27292111/26506760/4f2d1402-4256-11e7-8bfd-ce3d619eaade.png)

</details>

***System configuration***

Application version: 1.2.2.81
OS: 10.3.3

Optimized enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.24 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.43 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.85 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.30 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.32 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.49 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.33 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
Fixed.
