### ISSUE TITLE
trustedreviewers.com - ad leftover, missed ad - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5122]
http://www.trustedreviews.com/news/adguard-windows-microsoft-edge-extension

Screenshot:

<details>

Ad leftover during scrolling

![image](https://cloud.githubusercontent.com/assets/27292111/26507161/c70de19e-4257-11e7-87e4-09c5bdbbf62e.png)

Missed ad at the end of the article

![image](https://cloud.githubusercontent.com/assets/27292111/26507188/e7ac7898-4257-11e7-9f74-231d23c0058b.png)

</details>

Application version: 1.2.2.81
OS: 10.3.3

Optimized enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.24 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.43 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.85 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.30 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.32 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.49 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.33 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
fixed
