### ISSUE TITLE
bestprosoft.com [Fake Button]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#51247]
http://bestprosoft.com/microsoft-iso-downloader-premium-2020-1-7-multilingual/

Please remove the fake download button at the bottom of the page. Checked with AG for Chrome.

**Comment by krystian3w** [comment]
`/images/download-button/download-*.$image,domain=bestprosoft.com`

or

`##.affiliate_download_imagebutton_container`
