### ISSUE TITLE
fasionunited.de - ad leftover - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5125]
Screenshot:

<details>

Ad leftover at the top
![image](https://cloud.githubusercontent.com/assets/27292111/26507736/5cb0933e-425a-11e7-8f45-eaae926f7be9.png)

</details>

Application version: 1.2.2.81
OS: 10.3.3

Optimized enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.24 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.43 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.85 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.30 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.32 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.49 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.33 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
Can't open this site:

<details>

![image](http://imagizer.imageshack.com/img922/2307/8zoBXa.png)
</details>

**Comment by veronikasav** [comment]
Could not open via computer as well but reproduced on my phone again. 
Is there any way to help you? Logs?

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26555630/a9d842d8-449e-11e7-96af-ad4f05ad0127.png)

</details>

**Comment by Alex-302** [comment]
Compare site address in the title and on your screenshot)

**Comment by Alex-302** [comment]
Added to German  filter
```
fashionunited.de##.adunit-title
```
