### ISSUE TITLE
facildownloads.net - AntiAdblock - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5126]
Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26507932/4a17142c-425b-11e7-85b0-8547959cb02e.png)

</details>

Application version: 1.2.2.81
OS: 10.3.3

Optimized enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.24 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.43 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.85 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.30 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.32 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.49 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.33 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
Added to English filter
```
||facildownloads.net/wp-content/plugins/pause-adblocker/

```
