### ISSUE TITLE
https://api.privatbank.ua - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5127]
![image](https://cloud.githubusercontent.com/assets/15856304/26513264/442e07e2-4273-11e7-9b86-c11367867ce5.png)

![image](https://cloud.githubusercontent.com/assets/15856304/26513150/9e418520-4272-11e7-8e27-18287243e40b.png)

Something's blocking the confirmation buttons when paying via PrivatBank. The URL: https://api.privatbank.ua/p24api/ishop?pid=26504309&mid=62392&dyn_string=14192508069991152011452868940330109117314994743526768635111574177&hash=dashboard

Once completely whitelisted:

![image](https://cloud.githubusercontent.com/assets/15856304/26513238/26bf2cc2-4273-11e7-8350-2f307b439a46.png)

**Comment by Alex-302** [comment]
added
@@||api.privatbank.ua^$document

**Comment by Alex-302** [comment]
Please check.
