### ISSUE TITLE
Long nards app - missed ads

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#5128]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/26515991/19e6d94e-4289-11e7-8330-1f78373bf614.png)

</details>

***Steps to reproduce the problem***:

https://play.google.com/store/apps/details?id=org.aastudio.games.longnards (you need to wait for a minute and then it will appear)

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  **OFF** 
Adguard filters: | English, Russian, Spyware, Social media, Mobile ads, Annoyances, User.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1325165

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@KozelElena  надо проверить.

**Comment by kbahlyk** [comment]
Test showed no ads.
