### ISSUE TITLE
.org and .net mirrors of pornhub.com [NSFW]

### ISSUE THREAD

**Issue by in4u** [AdguardTeam/AdguardFilters#51307]
Please update filters for `pornhub.com` to include `pornhub.org` and `pornhub.net` mirror domains as well.

**Comment by Alex-302** [comment]
At the moment they are used for redirect to pornhub.com only.

**Comment by in4u** [comment]
No, it's location based. In countries where `.com` version is banned, the other mirror is served by default. For example, test using an Indian proxy IP then even the `.com` version will be redirected to `.org` only.

**Comment by Alex-302** [comment]
With Indian IP:
![image](https://user-images.githubusercontent.com/8361299/76706362-8e5e8f00-66ef-11ea-8347-ddd0da3398f4.png)
![image](https://user-images.githubusercontent.com/8361299/76706364-94547000-66ef-11ea-8afa-e2bdb70c3632.png)

**Comment by uBlock-user** [comment]
@Alex-302 try `https://www.pornhub.net`

**Comment by in4u** [comment]
@Alex-302  Use `https` since `http` version is banned. Try `https://www.pornhub.com` with an Indian IP and it will be redirected to `https://www.pornhub.org`. If you still can't reproduce the redirection then please share the IP address with which you are testing.

**Comment by Alex-302** [comment]
@uBlock-user 
![image](https://user-images.githubusercontent.com/8361299/76711104-c2e54180-6715-11ea-90c7-8f23f47aec2c.png)
![image](https://user-images.githubusercontent.com/8361299/76711111-d7293e80-6715-11ea-86e4-6fa7b0414b94.png)

It is just blocked.
@in4u 
```
IP address: 139.59.7.59
You are from:	 India, Bangalore
```

**Comment by uBlock-user** [comment]
You will have to try the org domain then that also on `https://`

**Comment by in4u** [comment]
Can you please share a screenshot of what happens when you visit `https://www.pornhub.com` (note **HTTPS**) using that Indian IP after setting the browser to English language so that I can understand the error message?

**Comment by Vangelis66** [comment]
@in4u 

The Chrome Web Store has the following VPN (in reality a HTTPS proxy) extension: 

`https://chrome.google.com/webstore/detail/urban-free-vpn-proxy-unbl/eppiocemhmnlbhjplcgkofciiegomcon`

It has a **free** _Indian_ node, whose IP address is `101.53.139.165` [Gurgaon, Haryana (IN)]

Connecting to that node and requesting `https://www.pornhub.com` I can easily witness the redirection to `https://www.pornhub.org`: 

![EE-INDIA](https://user-images.githubusercontent.com/9669492/76820568-3bcac300-6814-11ea-8f3f-8471408fe15b.JPG)

**Comment by in4u** [comment]
Thanks for the steps to reproduce that redirection @Vangelis66! Just waiting for @Alex-302 now to test and confirm the same.

**Comment by Alex-302** [comment]
Still cannot visit this domain:(
@AdguardTeam/filters-maintainers please take a look.

**Comment by AdamWr** [comment]
`pornhub.net` redirects to `pornhub.com` on my end even with Indian IP.
But I think that this issue has been fixed in this pull request - https://github.com/AdguardTeam/AdguardFilters/pull/51591

**Comment by zloyden** [comment]
> `pornhub.net` redirects to `pornhub.com` on my end even with Indian IP.
> But I think that this issue has been fixed in this pull request - #51591

I have the same with Indian IP.

**Comment by in4u** [comment]
For India, currently the redirection is from `.com` or `.net` to `.org`. Make sure that you guys are using HTTP/S proxy only and not SOCKS based.

uBO has [updated](https://github.com/uBlockOrigin/uAssets/issues/5799#issuecomment-597367117) filters to cover `pornhub.*` Maybe try [this idea](https://github.com/uBlockOrigin/uAssets/issues/5799#issuecomment-599605375) suggested over there and test using Tunnelbear VPN for PC.

Am not sure under what circumstances or for which countries the redirection from `.com` to `.net` currently happens. This [article](https://www.businesstoday.in/current/corporate/pornhub-changes-website-address-for-reliance-jio-customers-after-ban/story/286934.html) talks about `.net` dealing with certain ISP specific bans in India so maybe `.net` is used in certain specific cases only. Or maybe it was superseded by `.org` while [keeping](https://twitter.com/Pornhub/status/1055931244129615874) `.net` as backup.

**Comment by Alex-302** [comment]
This is impossible to select specific proxy in Tunnel Bear.
I can check it using AnyDesk.

**Comment by in4u** [comment]
Alright @Alex-302, forget TunnelBear and try this...

Use Firefox and enable the setting: `Options` > `Network Settings` > `Manual proxy configuration` > `Also use this proxy for FTP and HTTPS`

Now test using each of the following IP:Port combination by entering the respective values in `HTTP Proxy` and `Port` fields under `Manual proxy configuration`:

117.255.222.64:53281
14.140.131.82:3128
117.254.177.59:8080
182.71.102.215:3128
103.47.238.116:41797
103.69.220.2:45155
182.71.102.215:3128
103.29.222.46:34418
103.29.222.38:55578
43.229.25.22:54976

After setting the proxy, visit `https://www.pornhub.com` (note HTTPS) which should redirect to `https://www.pornhub.org`. If a proxy is offline or doesn't work, try again and test using the next proxy in line.

I have personally tested every single one of these proxies and they successfully reproduce the redirection.

**Comment by mnplly** [comment]
##[👉🔴 Click Here >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
##[👉🔴 Click Here >>](https://bt-fr-cl.com/tds/ae?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
##[👉🔴 Click Here >>](https://securecd-smrtnd.com/s?a=256440&sm=46517&co=316585&mt=5)
🚀 How to Use Eporner – A Quick Guide!
Hey everyone! 👋 If you're exploring ways to use Eporner, here's a quick guide to get you started:

Steps to Use pornhub.com: ##[👉🔴 Click Here >>](https://securecd-smrtnd.com/s?a=256440&sm=46517&co=316585&mt=5)
Visit the Official Website: Head over to Eporner for a wide range of free content.
Search What You Need: Use the search bar to find specific videos or categories that interest you.
Customize Your Experience: Create an account to save favorites and access advanced features.
💡 Pro Tip: Make sure to check out the "HD" section for the best quality videos!

Let me know if you have any questions, or drop a comment below with your experience. 👍
