### ISSUE TITLE
gmx.net - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5130]
***Site***: https://navigator.gmx.net/
***Description***: Ads after logging in.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26516346/14a062ec-4285-11e7-8d85-6175061b6010.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.19.31
Spyware filter | 1.0.12.44
Social media filter | 1.0.19.88
Annoyances filter | 1.0.13.33
German filter | 1.0.34.35
Mobile ads filter | 1.0.8.50
Safari filter | 1.0.3.34

**Comment by Alex-302** [comment]
Can't register.

**Comment by danidoedel** [comment]
@Alex-302 Oh well ok. I made an account for you. Hopefully you are able to log in 

<details>
<summary>account</summary>
mail: adguard@gmx.de
password: adguardtesting
</details>


There is also some ad leftover on mobile I just noticed:

![img_5852](https://cloud.githubusercontent.com/assets/10995998/26724806/a2376b1c-479b-11e7-86f9-2d1b34bf6dfc.PNG)

**Comment by Alex-302** [comment]
Added to German filter
```
gmx.net#$#body > div[class*="has-ad-"] div.base-page__content { bottom: 0px!important; }
```
