### ISSUE TITLE
rozetka.com.ua - missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5133]
http://rozetka.com.ua/tp_link_tl_wr740n/p156837/?utm_source=yandex2&utm_medium=cpc&utm_campaign=search_popular_models&utm_term=tp%20link%20tl%20wr740n&utm_content=2076258167

Screenshot:

<details>

![screen shot 2017-05-27 at 8 42 33 am](https://cloud.githubusercontent.com/assets/27292111/26518424/e1d6569e-42b8-11e7-9aaf-fab12535fa31.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome / Opera
Adguard version: | 6.1.331.1732 / 1.4.1
Adguard driver (Windows): | WFP 
Adguard filters: | 1 2 3 4 5 14

Ticket ID: 1449704

**Comment by Alex-302** [comment]
Такое не блокируем.
В пользовательский фильтр
```
rozetka.com.ua###stretch_banner
```
