### ISSUE TITLE
Downloads are blocked when Adguard is active

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5135]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
Downloads are blocked when Adguard is active
"Using Adguard 2.9.70 and Chrome won't download any attachments at all when AG is active. When I switch it off, downloads work fine."

here is the original conversation https://forum.adguard.com/index.php?threads/downloads-blocking-when-adguard-is-active.21994/#post-138552
the customer sent us logs
[debug (98).txt](https://github.com/AdguardTeam/AdguardFilters/files/1033407/debug.98.txt)
[state.txt](https://github.com/AdguardTeam/AdguardFilters/files/1033408/state.txt)

***System configuration***

Information | value
--- | ---
Operating system: |  Android 7.0
Browser: | chrome
Adguard version: | 2.9.70
Adguard mode (Android): | VPN / Proxy(manual/auto)
Filtering quality (Android): |  high-speed
HTTPS filtering (Android): |  Off
Adguard filters: | 2, 3, 4, 11 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1565376

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is not caused by filters.
Replied on the forum.
