### ISSUE TITLE
nikos-weinwelten.de - missed ad 

### ISSUE THREAD

**Issue by vtargonskyi** [AdguardTeam/AdguardFilters#5136]
http://www.nikos-weinwelten.de/beitrag/michelin_restaurants_deutschland_2017_die_neuen_sterne_restaurants/

***Description***:
* **Current behaviour**: 

Ads on website: nikos-weinwelten.de
Appeared after updating filters.

Screenshot:

![image uploaded from ios](https://cloud.githubusercontent.com/assets/28786943/26521184/44c2bbc6-42eb-11e7-91e4-80b0cae2e4da.jpg)

***Steps to reproduce the problem***:

Go to: http://www.nikos-weinwelten.de/beitrag/michelin_restaurants_deutschland_2017_die_neuen_sterne_restaurants/

***System configuration***

Application version: 1.2.2.81

Device: iPhone
Platform: iOS
OS: 10.3.3

Optimized enabled: NO
Rules converted: 37420 from: 37420.

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.37 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.44 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.88 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.33 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.50.49 Enabled=NO
ID=6 Name="German filter" Version=1.0.34.35 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.93.6 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.8.50 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.34 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.61 Enabled=NO
ID=101 Name="EasyList" Version=1.0.70.48 Enabled=NO
ID=219 Name="ChinaList+EasyList" Version=1.0.2.83 Enabled=NO

Ticket ID(if exists): 

1480792

**Comment by Alex-302** [comment]
Added to German filter
```
nikos-weinwelten.de##.ce-ad
```
