### ISSUE TITLE
missed ad http://www.carrollcountytimes.com/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5137]
***Description***:
missed ad http://www.carrollcountytimes.com/

![image](https://cloud.githubusercontent.com/assets/25711093/26521304/f193b6fa-42ed-11e7-8b71-a004d9d5dd5d.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | eng, rus, annoyance, social, experimental, spyware, mobile.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1565266

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. It is blocked by English filter.

**Comment by Michael23456** [comment]
tested is just now @Alex-302 
it appears after browsing for some time
![image](https://cloud.githubusercontent.com/assets/25711093/26530498/5b42ed64-43de-11e7-9cf3-e6e2314f536c.png)
![image](https://cloud.githubusercontent.com/assets/25711093/26530501/6b2e64e2-43de-11e7-9f0b-02247232ab69.png)

**Comment by Alex-302** [comment]
that ad is loaded via securepubads.g.doubleclick.net, which is blocked.
Ask for HAR file
https://toolbox.googleapps.com/apps/har_analyzer/

**Comment by OlegSUP** [comment]
Could not reproduce it today on Mac and Android. Asked user for HAR and to check settings.

**Comment by ypetruk** [comment]
HAR file was submitted by the customer
Ticket ID:1565266

**Comment by Alex-302** [comment]
@ypetruk please ask for screenshot of console

**Comment by seanl-adg** [comment]
Updated anti-IL rule - https://github.com/AdguardTeam/AdguardFilters/commit/ba2b989f7c6c4539a54ae34a1f509b92f8df69d1
This may help, if still user is getting ads one more HAR log would be helpful

**Comment by vozersky** [comment]
linked a request about same fix for the Content Blocker
