### ISSUE TITLE
No longer working for YouTube

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#51393]
@stephen147 commented on [Fri Mar 13 2020](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1605)

### Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details
- **AdGuard version:**
AdGuard - Latest
- **Browser and version:**
Chrome - Latest
- **Operating system and version:**
Windows 10
- **Filters you use in AdGuard:**
NA
- **Stealth Mode settings:**
NA
- **Other browser extensions:**
NA

### Expected and Actual Behavior

As the subject. I've tried other ad blockers but the same issue is there. YT comes back with "An error has occurred..." When playing a video out of my Watch Later playlist, if the video goes to the next one. It normally goes onto the next video. Instead, it throws the error explained above.

Disabling ADg will no longer have this issue but the ads will be there.

**Comment by Alex-302** [comment]
I can't reproduce:(

**Comment by stephen147** [comment]
This is the error I get. As soon as I disable the extension I no longer get that error.

All ad blockers have the same issue. I think it may be something that has change with YT. 

![image](https://user-images.githubusercontent.com/14054664/76571821-6208ff80-64b0-11ea-8e51-dd07eb6cde29.png)

**Comment by Alex-302** [comment]
Yep. Also one user said that he can reproduce it only with one google account.

**Comment by lassekongo83** [comment]
Any difference if you change your settings at: https://adssettings.google.com/authenticated to disabled or enabled?

**Comment by stephen147** [comment]
Turning of this had no effect and still causes the same issue.

![image](https://user-images.githubusercontent.com/14054664/76658059-27b06880-656b-11ea-8256-fd8dd9b0a805.png)

**Comment by BlazDT** [comment]
Not reproduced, please try this rule:

`@@||youtube.com/get_video_info`

**Comment by stephen147** [comment]
> `@@||youtube.com/get_video_info`

Tried that but with the same issues. 

I've disabled this plugin entirely and installed Adblock Plus and so far no errors or hanging of the chrome browser either.

**Comment by Alex-302** [comment]
it seems YouTube tests some changes in  ad system.
There are two similar ad requests:
* Error, if `&adformat=15_2_1` in blocked URL:
`https://www.youtube.com/get_video_info?html5=1&video_id=a3hdfROmrQc&cpn=0k09YUObA245g2Y9&eurl&ps=desktop-polymer&el=adunit&hl=en_US&aqi=jFFvXpKLBtTjpQPeq4DIAQ&sts=18332&lact=685&c=WEB&cver=2.20200312.05.00&cplayer=UNIPLAYER&cbr=Chrome&cbrver=80.0.3987.132&cos=Windows&cosver=10.0&adformat=15_2_1&slot_pos=1&encoded_ad_playback_context=CA8QAhgBKgtzdE0yQ1BGOVlBWUIWakZGdlhwS0xCdFRqcFFQZXE0RElBUVgBYAF1bt1-Pw%253D%253D&iv_load_policy=1&autoplay=1&width=640&height=360&content_v=stM2CPF9YAY`
* No error - if `&adformat=1_8` in blocked URL:
`https://www.youtube.com/get_video_info?html5=1&video_id=Pwb6d2wK3Qw&cpn=bGiDrtqAZxYdw9Ja&eurl=https%3A%2F%2Fwww.youtube.com%2F&el=adunit&hl=en_US&sts=18333&lact=195&c=WEB_EMBEDDED_PLAYER&cver=20200312&cplayer=UNIPLAYER&cbr=Chrome&cbrver=80.0.3987.132&cos=Windows&cosver=10.0&adformat=1_8&mute=true&authuser=0&ei=hlBvXpLkKdrKigTlm5T4BA&iframe=1&embed_config=%7B%7D&co_rel=1&ancestor_origins=https%3A%2F%2Fwww.youtube.com`
