### ISSUE TITLE
cnbc.com - anti adblock script

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#5139]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Anti adblock script on cnbc.com

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/26526317/496fd9d0-437f-11e7-89d1-159da9174a01.png)

</details>

***Steps to reproduce the problem***:

http://www.cnbc.com/world/?region=world

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS
Browser: | Chrome
Adguard version: | 6.1.331 / 1.4.1
Adguard driver (Windows): | WFP 
Adguard filters: | English, Russian, Spyware, Social, ABPVN

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1478843

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
||cdn.tinypass.com^$domain=cnbc.com
```
