### ISSUE TITLE
Remove obsolete or redundant rules in Annoyances

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#51410]
As far as I could confirm, the below rulse are no more needed:
`@@||kounta.com/wp-content/plugins/popup-maker/$domain=kounta.com`
`@@||tradeciety.com/wp-content/plugins/arscode-ninja-popups/js/jquery.placeholder.js`
`@@||manjemedia.com/wp-content/plugins/convertplug/modules/assets/images/default.png`

The below rules
`||anonymousnews.ru/wp-content/plugins/convertplug/modules/modal/assets/js/modal.min.js`
`||onlinemarketingrockstars.de/wp-content/plugins/convertplug/modules/modal/assets/css/modal.min.css`
are redundant since there is already
`/wp-content/plugins/convertplug/*`

This rule is duplicated:
`||torrentmegafilme.com/wp-content/plugins/smio-push-notification/js/frontend_webpush.js`

**Comment by AdamWr** [comment]
Fixed, thank you.
