### ISSUE TITLE
http://www.areadvd.de/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5142]
http://www.areadvd.de/news/neue-amazon-deals-am-samstag-9/

![image1](https://cloud.githubusercontent.com/assets/15856304/26527051/42c88194-4394-11e7-8910-a3d128a23ce8.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.2.1.71
Simplified filters(iOS) |Off
Adguard DNS: | Default 
Adguard filters: | 2 3 4 6 14 15 107

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1440449

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by MikeKasp** [comment]
Hi, the Ads are shown if I turn on english filters + German filters. If I turn the English off, the ads are blocked

**Comment by Alex-302** [comment]
Strange. Ads are blocked on my iPad with Eng, German, Social and Spyware filters.
Is EasyList Germany enabled?

**Comment by MikeKasp** [comment]
Yes, really strange. I thought the English filter only works for us-websites. The following filters are on at the moment: spyware, social, mobile-ads, safari, German, easy privacy, easylist Germany. If I turn the English or easylist on the ads are back.

**Comment by Alex-302** [comment]
`German, easy privacy`
they are redundant. You can disable them.
Is the issue reproducible, when only Eng filter is enabled?

**Comment by MikeKasp** [comment]
Hi, if I only enable the english filter only the ads are there. And if I block the ads manually the are bock with an other web-address 

_areadvd.de###content > div.entry:nth-child(3) > p:nth-child(5) > img.aligncenter.size-full.wp-image-96476
areadvd.de###links > a:nth-child(9) > img.aligncenter
areadvd.de###xjLYvVA > img_

**Comment by Alex-302** [comment]
Please check:
```
@@/ad_bomb/*$image,domain=areadvd.de
```

**Comment by MikeKasp** [comment]
Hi, 

This works: @@/ad_bomb/*$image,domain=areadvd.de

Im added it to my personal filters.

Thanks a lot 

I have another problem with an anti adblock message on this page if I enable the English filters: http://www.maniac.de

I have opened a case here, but it doesn't work. Do you have a solution for this case too?

**Comment by Alex-302** [comment]
```
@@/ad_bomb/*$image,domain=areadvd.de
```
added



> I have another problem with an anti adblock message on this page if I enable the English filters: http://www.maniac.de

Please open new issues for another sites.
