### ISSUE TITLE
usps.com and lendingclub.com random failure to load

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5143]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
usps.com and lendingclub.com random failure to load
https://www.usps.com/
https://www.lendingclub.com/site/home
the issue doesn't persist when adg is disabled
[adguard (2).log.zip](https://github.com/AdguardTeam/AdguardFilters/files/1034198/adguard.2.log.zip)
 
is not reproduced on Meizu m3s.
Screenshot:

![image](https://cloud.githubusercontent.com/assets/25711093/26529217/ce2d3498-43c4-11e7-9e80-b0e0bc2a6dcb.png)
![image](https://cloud.githubusercontent.com/assets/14153331/26563782/519d8c76-44e0-11e7-9519-e19de3bc34de.png)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | chrome
Adguard version: | 2.9.70

Ticket ID(if exists): 1387734

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by jkljklhhjkjlhghjgjhghjg** [comment]
I am the bug reporter to support.  I want to add some info, most of which was provided to support that they didn't post.  Originally, I initiated a bug report from within the app.

------
It is only on certain websites, such as lendingclub and the usps website, and that I am unable to reproduce with Adguard disabled.

The error are random page load failures, with the error screen sent to the browser generated from Adguard, and random parts fail to load with errors generated by the website itself, or a spinner that never goes away.

Lending club can be browsed by the general public with the url https://www.lendingclub.com/browse/browse.action

Usps: again totally random. Just do things like track a package.

Again, they are totally random - you need to try it with adguard enabled during several parts of the day or night.

------
* It seems to correlate during heavier traffic loads to those websites. And 2) that the log logging "might be an attack" and drops the connecton.

Something support could not answer is if it was a known issue - but just unable to reproduce.  Loading the websites once or twice isn't reliable.

**Comment by Alex-302** [comment]
@jkljklhhjkjlhghjgjhghjg is the issue reproducible, when protection is enabled, but all filters are disabled? Please check this case.
Which Internet connection are you using?
I see some errors in the log
```
14:06:00.047 [pool-2-thread-43] ERROR c.a.android.filtering.commons.d - UDP id=109 Cannot connect to remote end point /192.168.0.1:53
```
Is it your proxy or custom DNS?

**Comment by jkljklhhjkjlhghjgjhghjg** [comment]
1) I was able to capture some more closedchannelexception tonight with everything under "ad blocker" disabled.

2) home wifi out to 3meg dsl

3)This is the gateway/router IP, which runs a simple dns forwarder.  No dns cache or http proxy.

**Comment by Alex-302** [comment]
@jkljklhhjkjlhghjgjhghjg I need a timestamp of the issue.

**Comment by Alex-302** [comment]
@jkljklhhjkjlhghjgjhghjg could you, please, check without own DNS?

**Comment by Alex-302** [comment]
Also, you can check these cases:
- with Adguard, but without HTTPS filtering;
- without Adguard.
This message say about network issue:
`ERROR c.a.android.filtering.commons.d - UDP id=109 Cannot connect to remote end point /192.168.0.1:53`

**Comment by jkljklhhjkjlhghjgjhghjg** [comment]
With adguard disabled, and the app shut down entirely - I am unable to reproduce.

Without https filtering - difficult to confirm since websites these days force https.  I'm pretty sure the problem is in the https module though as I only upgraded for the https filtering in this version, but I have never had these sort of failures with non secure connections.

I don't shouldn't have to detail timing, nor do I understand why you're focusing on the occasional dns non reply.  Just look in the logs I posted for the big blocks of text around closedchannelexception.  I will check with a different dns programmed, but I'm pretty sure I've seen these failures when connected to another wifi.

**Comment by jkljklhhjkjlhghjgjhghjg** [comment]
I captured more closedchannelexception with another dns programmed.  There were several objrcts failed to load, such as images, and spinners not going away, and at least one where the initial html failed to load producing an adguard generated error to the browser same as in the first screenshot.

[adguard - May 31.zip](https://github.com/AdguardTeam/AdguardFilters/files/1040651/adguard.-.May.31.zip)

**Comment by Alex-302** [comment]
Filed a bug in Android repository:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1251
Closed here.
