### ISSUE TITLE
www.nike.com

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#51433]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Shopping cart is broken by a rule in Tracking protection filter.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![nike](https://user-images.githubusercontent.com/58900598/76621745-7235e300-6573-11ea-98ce-9b762d9117d1.png)

</details><br/>

* **Expected behaviour**: 

Shopping cart works fine.

***Steps to reproduce the problem***:

1. Go to the URL (it seems locale is irrelevant) and add any product to your cart.
2. Open your cart and you'll see blank screen.

***System configuration***

**Filters:**

Base + Tracking Protection

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox 74.0
AdGuard version:                       | 3.3.8
Stealth mode options (Windows only)    | Default

The rule: `||nike.com*/analytics-`
Related: `https://forums.lanik.us/viewtopic.php?f=62&t=44431`

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
