### ISSUE TITLE
missed ad in https://play.google.com/store/apps/details?id=com.estsoft.alsong

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5144]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
missed ad in https://play.google.com/store/apps/details?id=com.estsoft.alsong
is not reproduced on Meizu m3s

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/26529317/7fd743ae-43c6-11e7-82a8-9fe5601aeb0a.png)

[debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/1034204/debug.txt)
issue time - 12:08
[state.txt](https://github.com/AdguardTeam/AdguardFilters/files/1034205/state.txt)

***System configuration***

Information | value
--- | ---
Operating system: |   Android 
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On 
Adguard filters: | 2, 3, 4, 11, 15, 227

Ticket ID(if exists): 1564361

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Try to enable List-KR filter.

**Comment by OlegSUP** [comment]
No ads on Nexus 5 with List-KR

**Comment by Alex-302** [comment]
Ok.

**Comment by KozelElena** [comment]
He's still facing ads (after enabling List-KR and cleaning up the cache).
I was not able to reproduce any of those ads on my side even with standard settings.

Is there anything else we can do for him?

**Comment by Alex-302** [comment]
> I was not able to reproduce any of those ads on my side even with standard settings.

Please capture HAR file.

**Comment by dzamyshlyayeva** [comment]
[adguard.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1041358/adguard.har.zip)
HAR file here

**Comment by Alex-302** [comment]
I see nothing useful in this file.
Did user stopped the app and cleared cache before recording?

**Comment by dzamyshlyayeva** [comment]
he had done it before the agent asked for a HAR. will ask to do it once again and record a new log

**Comment by Alex-302** [comment]
@seanl-adg Please check it on your device.

**Comment by Michael23456** [comment]
[adguard (1).har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1049496/adguard.1.har.zip)
here is a new log from the customer

**Comment by seanl-adg** [comment]
Not reproduced on my end, but please let the user check it again.

**Comment by dzamyshlyayeva** [comment]
asked the user
