### ISSUE TITLE
missed ad http://www.srugim.co.il/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5145]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
missed ad http://www.srugim.co.il/
on android because of the missed ads it's not even possible to close the full-page ad

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/26529515/dc22f57e-43c9-11e7-97d9-6fd0a216472f.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | eng, rus, annoyance, spyware, social, mobile, experimental, easyList Hebrew

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1549411

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
srugim.co.il##.ads_cube
```
