### ISSUE TITLE
radio.net [Incorrect Blocking]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#51478]
https://www.radio.net/s/beautifulinstrumentals

Unable to play the radio stream when AG for Chrome is enabled.

![image](https://user-images.githubusercontent.com/6959116/76677075-fe85eb80-65ef-11ea-90a6-ef587f155b04.png)

**Comment by BlazDT** [comment]
Restored popup which tells you to open the stream in a new window.

Other radio station plays fine without popup:
https://www.radio.net/s/absolute60s
