### ISSUE TITLE
yandex.ru is blocked by  ||yandex.*/clck/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5148]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:yandex.ru is blocked by  ||yandex.*/clck/

Screenshot:
![image](https://cloud.githubusercontent.com/assets/25711093/26530755/ac9677d0-43e3-11e7-8416-b0d830cb6407.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | on

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1563865

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
