### ISSUE TITLE
http://www.convertfiles.com/ AdReclaim data: & InternalRedirect.Site ads

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardFilters#5149]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

http://www.convertfiles.com/, &c, has AdReclaim data: & InternalRedirect.Site ads (similar to #2250)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Ads take over site

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>
Sorry for dark: I forgot to turn off my screen overlay.

![screenshot_20170528-125629](https://cloud.githubusercontent.com/assets/185902/26530798/09058630-43aa-11e7-87ba-47a925f8fcb6.png)

_(Y'all know we can upload these directly to GitHub now, right?)_
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Ads missing

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Just go to site & wait for finish loading.

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Any
Adguard version: | 2.9.70 Amazon ß
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  Off (but site has no HTTPS included)
Adguard DNS: | Default (via .dns. option)
Adguard filters: | All, except Acceptable Ads, & can't copy/paste my own (anyway irrelevant here)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): N/A

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed.
