### ISSUE TITLE
ticketmaster.de - total blocking - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5150]
http://www.ticketmaster.de/artist/fia-formula-e-berlin-eprix-tickets/956338?language=en-us&utm_source=Newsletter%20Re-Launch&utm_medium=email&utm_campaign=Berlin%20ePrix%202017%20relaunch&utm_term=CTA&utm_content=English

Unable to click anywhere on the website. Works when Adguard is disabled.

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26530918/6e1e8598-43e7-11e7-926e-8a92358f9181.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.42 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.44 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.88 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.33 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.51.73 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.36 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.62 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.50 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.34 Enabled=YES

Ticket ID: 1564649

**Comment by Alex-302** [comment]
fixed
