### ISSUE TITLE
shopping.uol.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#51522]
[https://shopping.uol.com.br/notebook/memoria-8-gb/memoria-12-gb/maior-que-16-gb/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://shopping.uol.com.br/notebook/memoria-8-gb/memoria-12-gb/maior-que-16-gb/)

Sponsored items:

![sponsored](https://user-images.githubusercontent.com/35470489/76691270-f5b10c00-6627-11ea-808a-6635da040e26.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
They are related to search. Just promoted items, like in all shops.

**Comment by adranger** [comment]
@Alex-302 This is a price comparison engine that shows prices on different shops. 

Those are paid ads that go directly to the websites selling them ("ir à loja") instead of letting you compare their prices with other shops.

See: https://github.com/AdguardTeam/AdguardFilters/issues/32372

**Comment by Alex-302** [comment]
Ok. Added `shopping.uol.com.br##.tp-sponsored.tp-offer`
