### ISSUE TITLE
bookatable.com - cookie notice - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5152]
https://www.bookatable.com/de

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26531045/c570985c-43e9-11e7-95f9-66f93e5cd92c.png)

</details>

***System configuration***

Application version: 1.2.2.81

Device: iPhone
Platform: iOS
OS: 10.3.3

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.52 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.45 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.91 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.36 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.39 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.53 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.35 Enabled=YES

Ticket ID:1480792

**Comment by Alex-302** [comment]
Fixed
