### ISSUE TITLE
makeuseof.com - missed ad, pop-up leftover - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5153]
http://www.makeuseof.com/tag/customize-tidy-mac-menu-bar/

Social share buttons leftover at the bottom even during scrolling
Missed ad

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26531283/e1d48148-43ee-11e7-8014-612bcb186b05.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.18.96 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.26 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.18.74 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.53 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.13 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.26 Enabled=YES

Ticket ID: 1415775

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
