### ISSUE TITLE
tube8.com - ad leftover - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5155]
https://www.tube8.com/hardcore/morning-after...%28part-ii%29/139177/

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26531701/5ef1cba6-43f7-11e7-8df2-ad7b442931e2.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.18.2 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.9 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.48 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.12 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.36 Enabled=YES

Ticket ID: 1566338

**Comment by Alex-302** [comment]
Please check these rules
```
tube8.com##.video_column_right > div[class$=" float-right"]
tube8.com##div[class] > input:first-child[type="hidden"][value="false"]+div
```

**Comment by veronikasav** [comment]
Checked. It doesn't work.

**Comment by Alex-302** [comment]
Added
```
tube8.com##body top-adblock
```
please check
