### ISSUE TITLE
mydigitallife.net

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#51551]
Куки.

<details><summary>Screenshot:</summary>

![2020 03 15-2](https://user-images.githubusercontent.com/17948007/76701760-16836b00-66d5-11ea-927b-c25fe98b0569.png)
</details>

[https://forums.mydigitallife.net/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://forums.mydigitallife.net/)

`mydigitallife.net##.PanelScroller.Notices`

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.3.8
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by krystian3w** [comment]
Possible use generic:

`##.pageContent > .PanelScroller.Notices`

recommend by @kiboke.
