### ISSUE TITLE
tagesanzeiger.ch - Annoyance - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5156]
***Site***: http://mobile2.tagesanzeiger.ch/articles/592b085fab5c376da8000001
***Description***: App banner at the top. Social widgets at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26532059/d5f972da-43f7-11e7-8c97-b59f80be76fe.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.19.55
Spyware filter | 1.0.12.47
Social media filter | 1.0.19.91
Annoyances filter | 1.0.13.37
German filter | 1.0.34.41
Mobile ads filter | 1.0.8.53
Safari filter | 1.0.3.36

**Comment by Alex-302** [comment]
1- it will leave blank space
