### ISSUE TITLE
wccftech.com - Social widget - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5157]
http://wccftech.com/two-more-amd-rx-vega-variants-d12-and-d05-pass-rra-certification/

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26555892/02a71f5a-44a0-11e7-8a94-f7ca3bfc2030.png)

</details>

***System configuration***

Application version: 1.2.2.81

Device: iPhone
Platform: iOS
OS: 10.3.3

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.66 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.50 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.94 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.41 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.43 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.53 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.38 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
Fixed
