### ISSUE TITLE
Ad on ru.insider.pro

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5158]
***Description***:
* **Current behaviour**: 

An ad appears on ru.insider.pro

Screenshot:

![47eaaa61707aa2db4756d040a22ac67c](https://cloud.githubusercontent.com/assets/27874000/26556504/82da47e4-44a3-11e7-8d24-6ff726b9d197.png)

***Steps to reproduce the problem***:

Visit ru.insider.pro website and wait a few seconds for the ad to appear

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
Adguard filters: | English, Spyware, Social media, Annoyances, Filter unblocking useful ads, Russian

Ticket ID: 1449704

**Comment by Alex-302** [comment]
Fixed
