### ISSUE TITLE
mobil.stern.de - social widget, unblocked pop-up - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5159]
http://mobil.stern.de/politik/ausland/angela-merkel--ihre-bierzelt-botschaft-an-donald-trump-reicht-nicht-7472448.html

Screenshot:

<details>

Social widget

![image](https://cloud.githubusercontent.com/assets/27292111/26556815/7e2a8cfc-44a5-11e7-9dfc-709ea7ec7f03.png)

Unblocked pop-up

![image](https://cloud.githubusercontent.com/assets/27292111/26556825/883f07b8-44a5-11e7-9f3b-9222b6370af4.png)

</details>

***System configuration***

Application version: 1.2.2.81

Device: iPhone
Platform: iOS
OS: 10.3.3

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.66 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.50 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.94 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.41 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.43 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.53 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.38 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
Fixed
