### ISSUE TITLE
web-capture.net

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#51608]
**1**. Сообщение антиблокировщика. Срабатывает на правило `.net/ads.` из 'Базового фильтра AdGuard'. Решений 2:
`@@||web-capture.net/ads.js`  или  `web-capture.net###no-ads-banner`

<details><summary>Screenshot:</summary>

![2020 03 16-3](https://user-images.githubusercontent.com/17948007/76751280-39268a00-6790-11ea-9d24-40111cee8538.png)
</details><br/>

 **2**. Отслеживание.

 Похоже на следящий скрипт: [https://monu.delivery/site/e/d/9d5bac-47c7-4aa2-b7fd-1ca5d645e836.js](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://monu.delivery/site/e/d/9d5bac-47c7-4aa2-b7fd-1ca5d645e836.js) (без него всё работает).

 Правило: `||monu.delivery$third-party`
<br/>

[https://web-capture.net/ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://web-capture.net/ru/)

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.3.8
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by krystian3w** [comment]
maybe:

```
snapito.com,web-capture.net#%#//scriptlet("abort-current-inline-script", "document.getElementById", "test-block") 
```

**Comment by XX-J** [comment]
Основная, первая, проблема не решена.
