### ISSUE TITLE
yandex.ru - missed ad - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5161]
Unable to block with a help of Adguard tool.
Could not reproduce.

Screenshot:

<details>

![screen shot 2017-05-29 at 10 30 52 pm](https://cloud.githubusercontent.com/assets/27292111/26560398/dc122a64-44be-11e7-9145-529d3fa03772.png)

![screen shot 2017-05-29 at 10 31 35 pm](https://cloud.githubusercontent.com/assets/27292111/26560400/e078dc74-44be-11e7-83b7-5589c8428c03.png)

![screen shot 2017-05-29 at 10 32 03 pm](https://cloud.githubusercontent.com/assets/27292111/26560401/e319fc7e-44be-11e7-957b-64d586545ee0.png)

![screen shot 2017-05-29 at 10 32 20 pm](https://cloud.githubusercontent.com/assets/27292111/26560402/e60725d8-44be-11e7-9d2e-f94fee3979ff.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.1

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.54 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.47 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.91 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.37 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.51.75 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.36 Enabled=YES

Ticket ID: 1566358

**Comment by Alex-302** [comment]
It is not ad.
For custom filter
```
yandex.ru##.zen_promo_yabro
```
