### ISSUE TITLE
Ads penetrate Skype on Android device

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#51610]
@jbionic2016 commented on [Tue Mar 03 2020](https://github.com/AdguardTeam/AdguardForAndroid/issues/3367)

Following the discussion here
https://github.com/AdguardTeam/AdguardFilters/issues/49691
I'd like to report the bug issue related to penetration of  ads on Android smartphone. Below attached are screenshot and technical info
![111 (1)](https://user-images.githubusercontent.com/23212486/74360157-9b791d00-4dd5-11ea-8658-6850c83fae21.jpg)

Operating system:                      Android 8
Browser:                               Google Chrome, Version 80.0
AdGuard version:                       Version 3.3.x, Freeware (No premium license)
Skype version:                       Version 8.56.0.100

Filters enabled:                       |   AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Experimental filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter 

AdGuard DNS:                           |  Cisco Family

---

@TheHasagi commented on [Wed Mar 04 2020](https://github.com/AdguardTeam/AdguardForAndroid/issues/3367#issuecomment-594497781)

@jbionic2016 

To clarify the issue:

1. Update the filters
2. Clear the app's data and cache (Skype)
3. Sign in and check that ads are missing

---

@jbionic2016 commented on [Wed Mar 04 2020](https://github.com/AdguardTeam/AdguardForAndroid/issues/3367#issuecomment-594508147)

> @jbionic2016
> 
> To clarify the issue:
> 
> 1. Update the filters
> 2. Clear the app's data and cache (Skype)
> 3. Sign in and check that ads are missing

Thanks for advice. Obviously, I've already tried everything that you proposed. 
It seems you didn't open the link from the top of my 1st post to see the history of the problem.   

---

@artemiv4nov commented on [Thu Mar 12 2020](https://github.com/AdguardTeam/AdguardForAndroid/issues/3367#issuecomment-598318261)

@jbionic2016 , hi!
I reviewed a problem and the task link above.
It's the nice try to use the rule: `||graph.facebook.com^$app=com.skype.raider`
Unfortunately, the Facebook ad can cache for the application. Did you try to re-install the Skype app to keep in filters this rule? You can use the rule `||graph.facebook.com^` for the case when an ad downloads by another service (not your app) and just passes to your app.

**Comment by Alex-302** [comment]
As I said in https://github.com/AdguardTeam/AdguardFilters/issues/49691#issuecomment-593520771 ad is blocked by `||graph.facebook.com^$app=com.skype.raider` on my device.
