### ISSUE TITLE
Anti-adblocker on: business-tv.me

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5162]
***Description***:
* **Current behaviour**: 

business-tv.me detects adblocking and prevents the user from seeing
anything.

Screenshot:

![screen shot 2017-05-29 at 10 26 27 pm](https://cloud.githubusercontent.com/assets/27874000/26560447/5a99d9ea-44bf-11e7-827b-dd404af14b13.png)

***Steps to reproduce the problem***:

Visit http://business-tv.me/player.php?id=925919

***System configuration***

Information | value
--- | ---
Operating system: Android  
Adguard version: | 6.0.1 
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On
Adguard filters: | English, Spyware, Social media, Mobile ads, Annoyances, Anti-Adblock Killer

Ticket ID: 1468315

**Comment by Alex-302** [comment]
Fixed
