### ISSUE TITLE
https://www.avanza.se/start

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#51635]
***Description***:
* **Current behaviour**: 

Does not display Assistant icon.

***Steps to reproduce the problem***:

1. Just open the website

***System configuration***

**Filters:**

Base, Russian, Mobile Ads, Adblock Warning Removal List

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 10.0.19041.153
Browser:                               | Chrome 81
AdGuard version:                       | 7.4n8
Filters enabled:                       | Base, Russian, Mobile Ads, Adblock Warning Removal List
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | None

**Comment by AdamWr** [comment]
It seems that this website is in HTTPS exclusions, so it's the reason why Assistant icon is not displayed.
