### ISSUE TITLE
Extended css rule is not included into the filter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#5163]
Here is the rule:
https://github.com/AdguardTeam/AdguardFilters/blob/master/GermanFilter/sections/css_extended.txt#L14

Rule text:
`berlin.de##.teaser[-ext-has='>.inner>h3>a.trakkking,>.inner>h3:not(:has(>*))']`

But it is not included into the filter:
https://filters.adtidy.org/windows/filters/6.txt

**Comment by ameshkov** [comment]
@Mizzick !

**Comment by Mizzick** [comment]
The rule is ignored in filter-compiler by following pattern:
`.*#{2}.*?:has\(.*`

**Comment by ameshkov** [comment]
> The rule is ignored in filter-compiler by following pattern:

This pattern is redundant, I guess we can ditch it already.

**Comment by ameshkov** [comment]
@Mizzick is it resolved?

**Comment by Mizzick** [comment]
ahh, yeap
