### ISSUE TITLE
pornhdin.com [NSFW] [Ad Banner]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#51630]
https://www.pornhdin.com/videos/51216/big-assed-asian-babe-masturbating-hd-porn-movie

Ad banners seen on the player, Checked with AG for Chrome

<details><summary>Screenshot</summary>

![Annotation 2020-03-16 231238](https://user-images.githubusercontent.com/6959116/76785612-c6db9700-67db-11ea-9ef1-78969c5bfa0d.png)

</details>

**Comment by krystian3w** [comment]
`##.inplayer-ad`
`pornhd.com##.vp-under-video-spot`
