### ISSUE TITLE
Adguard blocks UI elements for sharing in nextcloud again

### ISSUE THREAD

**Issue by tiiiecherle** [AdguardTeam/AdguardFilters#51643]
First of all thanks a lot for AdGuard to the whole team.

***Description***
It seems like a similar issue to [#47710](https://github.com/AdguardTeam/AdguardFilters/issues/47710) is back, only a little worse.

When enabling "Adguard social" extension it blocks the area in nextcloud which is needed for creating shared links which is an essential feature. I attached two screenshots (one with and one without "Widgets for social networks" active) and marked the areas.

The same problem also exists on Adguard for Firefox and for both browsers disabling "Adguard social" extension fixes the issue. So I guess it is a rule issue.

There seem to be a [few issues about](https://github.com/nextcloud/server/issues/16337) it in nextcloud but as I understand correctly they can't do much about it and want the users to report it to the adblockers to fix it. That's what I'm doing right now ;)

Thanks for looking into it. Kind regards.

***Screenshots***

![Bildschirmfoto 2020-03-16 um 22 46 40](https://user-images.githubusercontent.com/7059936/76803446-2769d480-67da-11ea-8670-1bdd195a286a.jpg)

![Bildschirmfoto 2020-03-16 um 22 45 57](https://user-images.githubusercontent.com/7059936/76803453-2d5fb580-67da-11ea-8b0a-2e0553e8d55b.jpg)

***System configuration***

**Filters:**
The relevant filter is AdGuard Social-Media-Filter.

Information                            | Value
---                                    | ---
Operating system:                      | macOS 10.15.3
Browser:                               |  Safari 13.0.5
AdGuard version:                       | 1.7.1
Filters enabled:                       | The relevant filter is AdGuard Social-Media-Filter.

**Comment by krystian3w** [comment]
fanboy social "badfilters":

```
#@##sharing
#@#.icon-share
```

**Comment by krystian3w** [comment]
For `AdGuard Social-Media-Filter` unable reproduce breakage (I do not have macOS and Safari with AG 1.7.1 extension).

**Comment by tiiiecherle** [comment]
@krystian3w thanks for the fast feedback. 

But I'm not really sure what these answers mean for me. Is there anything I can do (except adding the url to the whitelist) or do the filters have to be changed by the AdGuard team?

I veryfied that the issue still persists and we also tried on several different macs in different locations.

**Comment by AdamWr** [comment]
Unfortunately I can't reproduce it with AdGuard Social Media filter enabled.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/76848698-6c2a5580-6844-11ea-82ce-a7cb85668fe1.png)

</details>

Do you have any other filter lists enabled?

@AdguardTeam/filters-maintainers Could you please check it?
You can use demo here - https://try.nextcloud.com/

**Comment by tiiiecherle** [comment]
I have these filter lists enabled:

- AdGuard Basis-Filter
- AdGuard Tracking-Schutzfilter
- AdGuard Social-Media-Filter
- AdGuard Belästigungsfilter
- Fanboy's Annoyances
- I don't care about cookies
- AdGuard Deutscher Filter

I also tried it on the nextcloud demo site and the issue is also occurring there. Disabling "AdGuard Social" Extension in Safari brings back the UI elements.

**Comment by AdamWr** [comment]
Please check with `Fanboy's Annoyances` filter disabled.

**Comment by tiiiecherle** [comment]
> Please check with `Fanboy's Annoyances` filter disabled.

That helps ;) It is working with `Fanboy's Annoyances` filter disabled. I enabled this one as it helps  with e few sites I visit.

**Comment by AdamWr** [comment]
Ok, if you want to keep `Fanboy's Annoyances` filter enabled then you can add these rules to user filter:
```
nextcloud.com#@##sharing
nextcloud.com#@#.icon-share
```
If I'm not wrong nextcloud can be used on any domain, so you can change `nextcloud.com` to `yourdomain.com` and it should works too.

**Comment by tiiiecherle** [comment]
Thanks a lot, it worked with mydomain.com ;)
