### ISSUE TITLE
http://m.moyareklama.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5165]
http://m.moyareklama.ru/%D0%A1%D0%BC%D0%BE%D0%BB%D0%B5%D0%BD%D1%81%D0%BA/%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D0%B8/%D0%B2%D1%81%D0%B5

![image](https://cloud.githubusercontent.com/assets/15856304/26580741/20f7626a-4542-11e7-8eb2-3352cad4653a.png)

It covers the 40% of the screen on Android so we should consider removing it.

***System configuration***

Information | value
--- | ---
Operating system: | Mac
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | English, Russian, Mobiel ads, Safari, Social media, Annoyances, Spyware.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1563273

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
