### ISSUE TITLE
Ad on tracker.0day.kiev.ua

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5167]
***Description***:
* **Current behaviour**: 

На сайте tracker.0day.kiev.ua после логина на заднем фоне большая реклама.

Screenshot:

![a49fc05f6f7dcae652f0536c0b79510b](https://cloud.githubusercontent.com/assets/27874000/26581308/99ba1a24-4544-11e7-9f05-d19d18b0f4d1.png)

***Steps to reproduce the problem***:

Логин/пароль: Zelgadiss/a2a2m6d3g4p7

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP 
Adguard filters: | Russian, English, Spyware, Social media, Mobile ads, Annoyances

Ticket ID: 1093966

**Comment by Alex-302** [comment]
Fixed
