### ISSUE TITLE
Anti-adblock in GloStarTV app

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5168]
***Description***:
* **Current behaviour**: 

GloStar TV app detects adblocking and prevents the user from seeing anything.

Screenshot:

![capture123](https://cloud.githubusercontent.com/assets/27874000/26582535/42234ed8-454a-11e7-88dd-2f4d495a8e61.PNG)

***Steps to reproduce the problem***:

here's the download link: https://www.dropbox.com/s/tibje8v22if4vrq/10.%20GolStar%20TV.apk?dl=0

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.44
Adguard mode (Android): | VPN 
Filtering quality (Android): |  high-speed
HTTPS filtering (Android): |  Off
Adguard filters: | English, Spyware, Social media, Mobile ads

Ticket ID: 1565118

**Comment by ameshkov** [comment]
So they simply detect that AdGuard is installed.

**Comment by Alex-302** [comment]
It can't be fixed. This app checks for installed Adguard.

**Comment by ameshkov** [comment]
@aksyonova please ask user if he has root access?

**Comment by ameshkov** [comment]
There is an xposed module for hiding apps:
http://repo.xposed.info/module/de.depressiverobot.android.xposed.hideappsxposed

**Comment by aksyonova** [comment]
@ameshkov thank you! will contact the user.
