### ISSUE TITLE
Content blocked on sofoot.com

### ISSUE THREAD

**Issue by gfra54** [AdguardTeam/AdguardFilters#51696]
Hello.
I am the CTO of SOPRESS, a french company editing the website sofoot.com

Some of our content is blocked by adguard. It shouldn't, because it is not advertisement. It is blocked on the easylist french. I contacted them, and they updated their list. But it seems that is didn't made it to adguard french filter. can you help me ? See this forum thread for informations

https://forums.lanik.us/viewtopic.php?f=91&t=44436&p=153610

Thank you

**Comment by vbagirov** [comment]
It would be best if you filed a report using agrd.io/report

**Comment by gfra54** [comment]
ok thank you

**Comment by gfra54** [comment]
I ma not able to input the version number on this page. What shoul I input ?
![image](https://user-images.githubusercontent.com/1954396/76875655-246df300-6871-11ea-89cb-f14896e694a4.png)

**Comment by krystian3w** [comment]
numbers with dots.

e.g. 7.4  / 3.3.8

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.

Thank you for reporting it.
