### ISSUE TITLE
Sport1: Sport News Live" App - can't play videos

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#5169]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Videos can't be played while Adguard Adblocker is enabled. Disabling Adblocker helped on my side.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/26588555/58526e32-455e-11e7-87ad-69d856561709.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/26588542/5094d1e4-455e-11e7-86b0-35908657c9ae.png)

</details>

***Steps to reproduce the problem***:

https://apkpure.com/sport1-sport-news-live/sport1.mobile.android.apps

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android
Adguard version: | 2.9.70
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | English, User, Russian, Spyware, Social media, Annoyances, Mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1105236

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
The most of videos are not working on my side. Please send to user
```
@@||ad.yieldlab.net/yp/*mob_and_sport$app=sport1.mobile.android.apps
@@||pubads.g.doubleclick.net/gampad/adx?iu=/*/mob_and_sport1/$app=sport1.mobile.android.apps
@@||ad.doubleclick.net/ddm/pfadx/*dc_msid=sport1.mobile.android.apps$app=sport1.mobile.android.apps
@@||imasdk.googleapis.com/native/core/*/native_bridge__de.js$app=sport1.mobile.android.apps
@@||ad.71i.de/global_js/AppConfig/Sport1de/2.8/android.json$app=sport1.mobile.android.apps
@@||4$app=sport1.mobile.android.apps
||2mdn.net$app=sport1.mobile.android.apps
```
