### ISSUE TITLE
morgenpost.de - Social widget - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5171]
***Site***: https://m.morgenpost.de/berlin/polizeibericht/article210744177/17-Jahre-alter-Terrorverdaechtiger-in-der-Uckermark-gefasst.html
***Description***: Social widget leftover. Newsletter leftover.

<details>
<summary>Screenshot</summary>

![image](https://cloud.githubusercontent.com/assets/10995998/26591166/0f1dee7c-455d-11e7-80ac-1f239436be0f.png)

![image](https://cloud.githubusercontent.com/assets/10995998/26591186/1d67096e-455d-11e7-85da-a43afd8b82e2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.19.80
Spyware filter | 1.0.12.51
Social media filter | 1.0.19.94
Annoyances filter | 1.0.13.43
German filter | 1.0.34.44
Mobile ads filter | 1.0.8.54
Safari filter | 1.0.3.40

**Comment by danidoedel** [comment]
@Alex-302 That newsletter leftover stuff is still there. Is it possible to remove that too?

![image](https://cloud.githubusercontent.com/assets/10995998/26591186/1d67096e-455d-11e7-85da-a43afd8b82e2.png)

**Comment by Alex-302** [comment]
fixed. Not for iOS
