### ISSUE TITLE
de.filsh.net

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#51723]
`https://de.filsh.net/page/download/Zmlsc2g1ZTcxODFmNWFjNzA4OzA3YmY0YzYxM2JkNzVhYWM4Y2U4YWE1NzVjMTQ4NWFkOGU3ZWQxM2QyMDhjNWY5NDc4Yzg2MGVhYjdmYzA3MTA%3D`

***Description***: Ads on the final download page

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>
<img width="811" alt="screen54747" src="https://user-images.githubusercontent.com/48647394/76918192-febf0900-68c5-11ea-815c-b9b696d421fb.PNG">

![image](%screenshot_url%)
</details><br/>

***Steps to reproduce the problem***:

Try to convert a video

***System configuration***

**Filters:**

[settings.txt](https://github.com/AdguardTeam/AdguardFilters/files/4346598/settings.txt)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox 74

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/77074930-3929c280-69fa-11ea-9e07-a03f7c4151df.png)
It is dead.
![He is dead](https://user-images.githubusercontent.com/8361299/77074955-43e45780-69fa-11ea-93ea-71452d663899.gif)

**Comment by JobcenterTycoon** [comment]
Try with a german IP

**Comment by Alex-302** [comment]
Nothing. @BlazDT please take a look.

**Comment by BlazDT** [comment]
Site does not allow my mail address. Initial link not working.

**Comment by JobcenterTycoon** [comment]
you can use a temp mail for this

Or use my filter `||sovendus.com^$domain=de.filsh.net` because the newsletter ads are coming from `sovendus.com`

**Comment by BlazDT** [comment]
I tried a temp mail, but that one is refused too. Which temp mail provider did you try? https://tempr.email/ is refusing here.

**Comment by JobcenterTycoon** [comment]
try https://generator.email

**Comment by BlazDT** [comment]
Thank you, added as adserver.
