### ISSUE TITLE
[mobile web] autonews.com - ad leftover

### ISSUE THREAD

**Issue by opark** [AdguardTeam/AdguardFilters#5172]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

ad leftovers on autonews.com mobile articles.

* **Current behaviour**: 

article link: http://www.autonews.com/article/20170529/OEM/170529795/google-ford-deal-mark-fields?X-IgnoreUserAgent=1

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

https://puu.sh/w60Au/f3e90129ae.png

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS / Android / Linux
Browser: | 
Adguard version: | 
Adguard driver (Windows): | WFP / TDI
Adguard mode (Android): | VPN / Proxy(manual/auto)
Filtering quality (Android): | High-quality / high-speed / simplified
HTTPS filtering (Android): |  On (Default/Blacklist mode) / Off
Simplified filters(iOS) | On / Off
Adguard DNS: | None / Default / Family Protection
Stealth mode options(Windows) | 
Adguard filters: | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
autonews.com##.oas-ad
```
