### ISSUE TITLE
duolingo.com [false positive]

### ISSUE THREAD

**Issue by T1mL3arn** [AdguardTeam/AdguardFilters#51728]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: It is not possible to report an error in the practice task due to hidden pop-up element's content, see screenshot 1 below.

<details><summary>Screenshot 1:</summary>

![duo wrong](https://user-images.githubusercontent.com/9349164/76922155-ac103c00-691b-11ea-8e48-0dd7d7357b08.png)
</details><br/>

* **Expected behaviour**: Normally there should be an option list to choose the type of the error, see screenshot 2 below

<details><summary>Screenshot 2:</summary>

![duo correct](https://user-images.githubusercontent.com/9349164/76922056-5c317500-691b-11ea-9fb9-4553783faddf.png)
</details><br/>

***Steps to reproduce the problem***:

1. Start any practice task, e.g https://www.duolingo.com/skill/en/1.-Basics/practice (probably you need to be logged in duo account)
2. Answer correctly or wrongly, it does not matter
3. See button like `Report an error` (it will be `Сообщить об ошибке` in Russian) and press it
4. Notice blank pop-up

***Some notes***

It worked normally a couple of days ago. But duo has changed its layout for that pop-up. I checked the css and found the problem. It is in this rule:
https://github.com/AdguardTeam/AdguardFilters/blob/16ff0dadb4c20f1ad689cb5514859357ff8668b2/AnnoyancesFilter/sections/self-promo.txt#L694

If I disable `AdGuard Annoyances` list, then duo works as expected.

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 8.1
Browser:                               | Firefox 74.0
AdGuard version:                       | uBlock Origin
Filters enabled:                       | AdGuard Annoyances

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Removed obsolete rule.
