### ISSUE TITLE
fandom.com: .aff-unit__disclaimer-message and #mixed-content-footer

### ISSUE THREAD

**Issue by gakada** [AdguardTeam/AdguardFilters#51769]
***Description***:
* **Current behavior**:

On `https://kancolle.fandom.com/wiki/KanColle_Wiki` (and other such pages and FANDOM wikis) there is an unblocked ad element `.aff-unit__disclaimer-message` (in addition to already blocked `.aff-unit__wrapper`, since https://github.com/Wikia/app/commit/36ecbb6fcab1db5548d4bd5a68ad4034579c4c2b#diff-a52778eae3e0efd0892a65bd1e9ed30e). Additionally, there is an unblocked annoyance in the form of "Fan Feed" at the bottom (`#mixed-content-footer`).

<details><summary>Screenshots:</summary>

![1584541399](https://user-images.githubusercontent.com/13043588/76974004-03da9180-6974-11ea-97df-d194fd9a97e2.png)

![1584541884](https://user-images.githubusercontent.com/13043588/76974018-089f4580-6974-11ea-8a81-3c54a476c1a1.png)

![1584541817](https://user-images.githubusercontent.com/13043588/76974038-0b9a3600-6974-11ea-95a3-b4ef90809bd5.png)

</details><br/>

* **Expected behavior**:

`.aff-unit__disclaimer-message` and `#mixed-content-footer` blocked.

* **Related**:

- https://github.com/easylist/easylist/issues/5088

**Comment by Alex-302** [comment]
> #mixed-content-footer

Not sure about it. 

`.aff-unit__disclaimer-message`

commented in easylist/easylist#5088

**Comment by Alex-302** [comment]
If will not be added by EasyList, please write here.
