### ISSUE TITLE
smiley-bedeutung.de - ad leftover - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5177]
https://smiley-bedeutung.de/

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26611422/e3ff4236-45b6-11e7-8886-47ed883c11ef.png)

</details>

***System configuration***

Application version: 1.2.2.81

Device: iPhone
Platform: iOS
OS: 10.3.3

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.79 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.51 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.94 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.42 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.44 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.54 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.39 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
Fixed
