### ISSUE TITLE
techradar.com - social widget leftover, ad leftover - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5178]
http://www.techradar.com/news/pokemon-magikarp-jump-is-the-game-i-didnt-know-i-needed

http://www.techradar.com/ 

Screenshot:

<details>

Social widget leftover (first link)

![image](https://cloud.githubusercontent.com/assets/27292111/26611492/57804994-45b7-11e7-9ab9-78abb82ce66f.png)

Ad leftover (second link)

![image](https://cloud.githubusercontent.com/assets/27292111/26611501/5dec7c76-45b7-11e7-847c-2a978f145950.png)

</details>

***System configuration***

Application version: 1.2.2.81

Device: iPhone
Platform: iOS
OS: 10.3.3

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.79 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.51 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.94 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.42 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.44 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.54 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.39 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
fixed

**Comment by fixitplease** [comment]
@Alex-302 
Is it possible to remove that ad leftover too?

![image](https://cloud.githubusercontent.com/assets/28259813/26680829/29c4c334-46db-11e7-98a1-9b8eeed43b48.png)
