### ISSUE TITLE
autoexperience.de - ad leftover - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5179]
https://www.autoexperience.de/audi-a4-forum/6453-audi-a4-b5-rattern-beim-bremsen.html

Screenshot:

<details>

Ad leftover at the top

![image](https://cloud.githubusercontent.com/assets/27292111/26611657/392dd578-45b8-11e7-8ca9-d310d4196247.png)

Ad post in forums

![image](https://cloud.githubusercontent.com/assets/27292111/26611667/4e9395e2-45b8-11e7-8288-d0f92f37476f.png)

</details>

***System configuration***

Application version: 1.2.2.81

Device: iPhone
Platform: iOS
OS: 10.3.3

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.79 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.51 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.94 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.42 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.44 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.54 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.39 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
1 - added
```
autoexperience.de##body > div.ui-page > br:first-child
autoexperience.de##body > div.ui-page > br:first-child + div#AdMobileAdxTop + br
```
2 - we can't hide it on iOS

**Comment by fixitplease** [comment]
@Alex-302 
That ad post is in the desktop version of the page too. Is it possible to remove it there?

![image](https://cloud.githubusercontent.com/assets/28259813/26680949/9b9f613a-46db-11e7-9f11-6aed980db730.png)

**Comment by Alex-302** [comment]
fixed
