### ISSUE TITLE
forum.golem.de - ad leftover - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5180]
https://forum.golem.de/kommentare/applikationen/kuenstliche-intelligenz-alpha-go-geht-in-rente/109622,list.html

Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26611706/96ef9aca-45b8-11e7-8ac1-0303dbd5f912.png)

</details>

***System configuration***

Application version: 1.2.2.81

Device: iPhone
Platform: iOS
OS: 10.3.3

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.79 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.51 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.94 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.42 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.44 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.54 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.39 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
We can't hide it on iOS. It does not support extended CSS rules.
