### ISSUE TITLE
http://edition.cnn.com/2017/05/30/politics/russians-trump-campaign-information/index.html - incorrect Adgurd interface

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#5181]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://edition.cnn.com/2017/05/30/politics/russians-trump-campaign-information/index.html - incorrect Adguard interface
* **Current behaviour**: Adguard Assistant bar is not centered on this site

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot: https://prnt.sc/fe39si

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.2.2.81
Platform: iOS
OS: 10.3.3
Optimized enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.78 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.51 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.94 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.42 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.50.49 Enabled=NO
ID=6 Name="German filter" Version=1.0.34.44 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.93.6 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.8.53 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.39 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.63 Enabled=NO
ID=101 Name="EasyList" Version=1.0.70.48 Enabled=NO
ID=219 Name="ChinaList+EasyList" Version=1.0.2.83 Enabled=NO

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1322540

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is not the problem of filters.
Please write to
https://github.com/AdguardTeam/AdguardForiOS/issues
