### ISSUE TITLE
Ads on: fastpic.ru

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5183]
Screenshot:

![ogbqiv8k](https://cloud.githubusercontent.com/assets/27874000/26616846/4369ea6e-45da-11e7-98e3-758028140e02.png)

***Steps to reproduce the problem***:

Just visit http://fastpic.ru/

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | Chrome extension
Adguard filters: | RU AdList, Russian, English

Ticket ID: 1076701

**Comment by Alex-302** [comment]
Fixed

**Comment by kovalenkoi** [comment]
* Windows 7 x64
* Adguard в виде расширения у Chrome
* Используемые фильтры: Русский фильтр, Английский фильтр, RU AdList, Фильтр раздражителей
* Dr.Web
![image](https://user-images.githubusercontent.com/30697077/29829641-930b2164-8ce8-11e7-8672-1f0aa7169990.png)

**Comment by Alex-302** [comment]
Fixed.
