### ISSUE TITLE
Ads on: pravda.ru

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5185]
***Description***:
* **Current behaviour**: 

На сайте pravda.ru не фильтруются ссылки на социальные сети

Screenshot:

![2017-05-31-13-35-25](https://cloud.githubusercontent.com/assets/27874000/26628657/9bf439b4-4607-11e7-99f7-8d77ca4d5488.jpg)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | English, Spyware, Social media, Annoyances, Russian, Mobile ads

Ticket ID: 1567539

**Comment by Alex-302** [comment]
Не повторяется. Какой браузер?

**Comment by aksyonova** [comment]
Chrome. На главной странице проблем нет, нужно открыть любую статью

**Comment by aksyonova** [comment]
@Alex-302 Chrome. На главной странице проблем нет, нужно открыть любую статью

**Comment by Alex-302** [comment]
У меня кнопки скрыты. 
> Filtering quality (Android):	High-quality

Точно фильтрация HTTPS работает?

**Comment by aksyonova** [comment]
проверили, юзер https фильтрацию не включил)
