### ISSUE TITLE
paulasbodyshop.com - incorrect blocking 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5186]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: www.paulasbodyshop.com - the first time going to the book screen, the
embedded code leaves a blank placeholder and clicking on “book” a second time works. In some cases (haven’t been able to narrow down when/where,) it never displays. 

The booking form is not shown with ru or ua IP

ADD:
Blocking few titles, one button and embedded code on the book.html page (visible only with US IP-address).

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshots:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/26631610/8fb167c8-4614-11e7-90df-88cd080dc90b.png)

![image](https://cloud.githubusercontent.com/assets/23372054/26631699/f33d9a3c-4614-11e7-9491-b31b87261d24.png)

ADD:
![paulas1](https://cloud.githubusercontent.com/assets/28726429/26643771/2283956e-463b-11e7-8733-f7a6e62618d7.jpg)

![paulas2](https://cloud.githubusercontent.com/assets/28726429/26643777/256d1d4a-463b-11e7-8d4f-0d4e91fe0c9b.jpg)

</details>
<br>
***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | English, Spyware filter,Filter unblocking useful ads, German filter, Japanese filter, Dutch filter, EasyList China, Icelandic ABP List

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1255197

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced
http://imagizer.imageshack.com/img923/8249/z2mOG4.png

**Comment by altokarev** [comment]
There are no titles on background image on you screenshot. But they should be. And no embedded widget (visible only with US IP-address).

**Comment by Alex-302** [comment]
It is not caused by filters.

**Comment by altokarev** [comment]
The problem still exists.

User tried to investigate an issue:
```
1. Tested with filters unchecked without changing filter options and without whitelisting my site: 
Result at first attempt: Big white space where my Vagaro Scheduling App should be.
Result at clicking refresh: Vagaro Scheduling App shows up.
Result after closing tab and opening site in new tab: Vagaro Scheduling app shows up.


Added my site to the whitelist, by MANUALLY keying it in: @@||paulasbodyshop.com$document

2. Tested with filters unchecked without changing filter options and with whitelisting my site:
Result at firsts attempt: Big white space where my Vagaro Scheduling app should be.
Result at clicking Book 24/7 again: Vagaro Scheduling App shows up.
```

Reproduced. Blocked element comes up on refresh.
