### ISSUE TITLE
Loop game - missed ad 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5191]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://play.google.com/store/apps/details?id=com.balysv.loop&hl=fr> &hl=fr
pop up appears 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/26641428/3b32f2ec-4633-11e7-9aca-bfbbef33664a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.70
Adguard mode: | VPN 
HTTPS filtering: |  On (Default)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

logs are here: 1563308 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||appodealx.com^
||104.199.8.250^*/webservices/getDialogAdDetails.php
```
Please check.
