### ISSUE TITLE
Obsolete rules

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#51924]
Obsolete rules due to new design.

https://forum.adguard.com/index.php?threads/resolved-star-com-tr.23492/
`star.com.tr##.masthead.ct > [class="masthead-button pm tr cp"]`

---

https://forum.adguard.com/index.php?threads/resolved-star-com-tr.15763/
```
star.com.tr##.widget-head + .cat-user-info.him
@@||gdetr.hit.gemius.pl/gemius.js^$~third-party
```

---

https://forum.adguard.com/index.php?threads/resolved-5-websites-2.14391/#post-104361
`star.com.tr###reklam_center`

---

https://github.com/AdguardTeam/AdguardFilters/issues/12313
`||star.com.tr/dfp-fm.asp`

---

https://github.com/AdguardTeam/AdguardFilters/issues/16451

```
star.com.tr##.col-4 > div[class^="article"][-ext-has='div[id^="div-gpt-ad-"]']
star.com.tr##.col-4 > div[class^="article"][-ext-has='iframe[name="BIKADV"]']
||imgz.star.com.tr/folders/*BANNER
```

---

https://github.com/AdguardTeam/AdguardFilters/issues/8045

`star.com.tr#%#AG_onLoad(function() { $('.swiper-slide > a[href^="http://apps.star.com.tr/advredir.asp"]').closest('div.swiper-slide').remove(); $('.flx > li > a[href^="http://apps.star.com.tr/advredir.asp"]').closest('li').remove(); });`

**Comment by krystian3w** [comment]
Spyware exception can repair more than one tr site (for lack of monitoring or for the rest of the world needed).
