### ISSUE TITLE
xhamster2.desi [NSFW] [Pop-ups]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#51928]
https://xhamster2.desi/videos/husband-makes-wife-s-pussy-drip-with-jizz-13890686

X symbol seen when pausing the video. At times, seeing pop-up too when clicking on any link/page logo. Checked with AG for Chrome.

**Comment by Nzzyme** [comment]
Also seeing pop-up on AG for Android when clicking on the thumbnail.

https://xhamster2.desi/videos/fuck-a-desi-girl-8357672#mlrelated

**Comment by Alex-302** [comment]
Not reproduced.
