### ISSUE TITLE
YOUTUBE redline broken

### ISSUE THREAD

**Issue by nightznero** [AdguardTeam/AdguardFilters#51925]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)
The timelaps red line is upside down,idk maybe its one of my filters block that but its soooo annoying please fix that for me guyz

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

!<blockquote class="imgur-embed-pub" lang="en" data-id="a/KdEzjF7"  ><a href="//imgur.com/a/KdEzjF7">Broken timelaps redline</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

!<blockquote class="imgur-embed-pub" lang="en" data-id="a/n26R665"  ><a href="//imgur.com/a/n26R665">normal timelaps redline</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

Filters that i m usuing
!<blockquote class="imgur-embed-pub" lang="en" data-id="a/fE9QEtp"  ><a href="//imgur.com/a/fE9QEtp">filters</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)
!<blockquote class="imgur-embed-pub" lang="en" data-id="a/fE9QEtp"  ><a href="//imgur.com/a/fE9QEtp">filters</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win7
Operating system version (Android/iOS) | ?
Browser:                               | chrome
AdGuard version:                       | 3.3.8
Filters enabled:                       | Screen above
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | nope
Helpdesk ID (if exists):               | 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by krystian3w** [comment]
@AdamWr to jest chyba efekt polskich filtrów reklam wewnętrznych i Mateusz nie chce wyłączyć filtrów ulepszających:

* [`8e73fa9` /internal-filters/wewnetrzne.txt#L248-L252](https://github.com/KonoromiHimaries/PolishSubFilters/blob/bff07f38ae4dfa3d8affa95a3cae07fcbc4f4d1a/internal-filters/wewnetrzne.txt#L248-L252)
 * [`fbe8694` /filters/ThirdParty/filter_117_PolishSubFilters/filter.txt#L10376-L10380](https://github.com/AdguardTeam/FiltersRegistry/blob/1a8a6f4c359f0dc595046410c4c285ef3f9ac697/filters/ThirdParty/filter_117_PolishSubFilters/filter.txt#L10376-L10380)


---

@nightznero check this exceptions:

```
www.youtube.com#$@#.html5-video-player:not(.ytp-fullscreen) .ytp-progress-bar-container { position: relative!important; top: 32px!important; }
www.youtube.com#$@#.html5-video-player:not(.ytp-fullscreen) .ytp-chrome-controls { position: relative!important; top: -12px!important; }
www.youtube.com#$@#.html5-video-player.ytp-fullscreen .ytp-progress-bar-container { position: relative!important; top: 32px!important; }
www.youtube.com#$@#.html5-video-player.ytp-fullscreen .ytp-chrome-controls { position: relative!important; top: -30px!important; }
```

or disable "Polskie Filtry Wewnętrzne" on your filters list.

**Comment by krystian3w** [comment]
@AdamWr to jest chyba efekt polskich filtrów reklam wewnętrznych i Mateusz nie chce wyłączyć filtrów ulepszających:

* [`8e73fa9` /internal-filters/wewnetrzne.txt#L248-L252](https://github.com/KonoromiHimaries/PolishSubFilters/blob/bff07f38ae4dfa3d8affa95a3cae07fcbc4f4d1a/internal-filters/wewnetrzne.txt#L248-L252)
 * [`fbe8694` /filters/ThirdParty/filter_117_PolishSubFilters/filter.txt#L10376-L10380](https://github.com/AdguardTeam/FiltersRegistry/blob/1a8a6f4c359f0dc595046410c4c285ef3f9ac697/filters/ThirdParty/filter_117_PolishSubFilters/filter.txt#L10376-L10380)


---

@nightznero check this exceptions:

```
www.youtube.com#@$#.html5-video-player:not(.ytp-fullscreen) .ytp-progress-bar-container { position: relative!important; top: 32px!important; }
www.youtube.com#@$#.html5-video-player:not(.ytp-fullscreen) .ytp-chrome-controls { position: relative!important; top: -12px!important; }
www.youtube.com#@$#.html5-video-player.ytp-fullscreen .ytp-progress-bar-container { position: relative!important; top: 32px!important; }
www.youtube.com#@$#.html5-video-player.ytp-fullscreen .ytp-chrome-controls { position: relative!important; top: -30px!important; }
```

or disable "Polskie Filtry Wewnętrzne" on your filters list.
