### ISSUE TITLE
http://prnparty.com/hotvideo/tjolka-v-gimnasticheskom-kupalnike-zanimautsja-seksom.html - site with ads

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#5197]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://prnparty.com/hotvideo/tjolka-v-gimnasticheskom-kupalnike-zanimautsja-seksom.html - site with ads

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:
https://prnt.sc/fedpv4

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](http://somehosting.com/adg_on.jpg)
</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

Screenshot:
<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1/6.1
Adguard driver (Windows): |  TDI
Adguard DNS: | None 
Adguard filters: | Subscriptions: FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt	
FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt	
FilterId:4 Name: Social media filter Url: https://filters.adtidy.org/extension/chromium/filters/4.txt	
FilterId:10 Name: Filter unblocking useful ads Url: https://filters.adtidy.org/extension/chromium/filters/10.txt	
FilterId:1 Name: Russian filter Url: https://filters.adtidy.org/extension/chromium/filters/1.txt	
FilterId:0 Name: User filter Url: no_url

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1566670

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
This site has no visitors.
