### ISSUE TITLE
www.ona-on.com - incorrect blocking

### ISSUE THREAD

**Issue by lencc** [AdguardTeam/AdguardFilters#5200]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: The following rule interferes with built-in gallery on some webpages:
`||cdnjs.cloudflare.com/ajax/libs/postscribe/*/postscribe.min.js`

* **Current behaviour**: It's not possible to switch between pictures in image gallery. Only first image within a gallery is displayed.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

<details>

![image](http://somehosting.com/adg_off.jpg)
</details>

***Steps to reproduce the problem***:
1) Adguard English Filter (list is added via uBlock Origin in my case)
2) Go to webpage https://www.ona-on.com/magazin/foto-gorski-zrak-odlicno-vzdusje-in-nova-prijateljstva/
Image gallery is located in the middle of the page.

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Mozilla Firefox + uBlock Origin
Adguard filters: | Adguard English Filter, Adguard Spyware Filter

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
