### ISSUE TITLE
org.mozilla.firefox

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#52010]
***Description***:
* **Current behaviour**: 

Search suggestions do not work when protection is enabled.

<details><summary>Screenshot:</summary>

![Firefox_adguard enable](https://user-images.githubusercontent.com/33634917/77249879-d5e39e80-6c4c-11ea-89c3-6a4d91f4a8bb.jpg)

</details><br/>

* **Expected behaviour**: 

AdGuard shouldn't affect search suggestions in this browser.

<details><summary>Screenshot:</summary>

![Firefox_adguard disable](https://user-images.githubusercontent.com/33634917/77249887-e6941480-6c4c-11ea-99cb-aeeed4ab55b4.jpg)

</details><br/>

***Steps to reproduce the problem***:

1. Install Firefox, install AdGuard, try using search suggestions

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 10
Browser:                               | Firefox
AdGuard version:                       | 3.3.230
Filters enabled:                       | Base, Mobile Ads, Tracking Protection, Annoyances, Social Media filter, I don't care about cookies, French
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | Default IPv4, DoH
Helpdesk ID (if exists):               | 2259950

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/50299
https://github.com/AdguardTeam/AdguardForAndroid/issues/3361

**Comment by Alex-302** [comment]
Проблема не связана с фильтрами.
