### ISSUE TITLE
it-administrator.de - unblocked pop-up - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5202]
http://www.it-administrator.de/

Screenshot:

<details>

Cookie notice at the top

![image](https://cloud.githubusercontent.com/assets/27292111/26658423/a0af7a8e-4672-11e7-8f18-1b352c382403.png)

</details>

***System configuration***

Application version: 1.2.2.81

Device: iPhone
Platform: iOS
OS: 10.3.3

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.19.97 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.56 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.1 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.55 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.55 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.58 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.41 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
Fixed
