### ISSUE TITLE
giveaway.su

### ISSUE THREAD

**Issue by ArmynC** [AdguardTeam/AdguardFilters#52031]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Per #34689; The site giveaway.su has an anti-adblocker but the "defuser" has been added only in the Russian filter list. Other than domain, this website is used globally and has English content.

* **Current behaviour**: Isn't working with Adguard's Annoyance filter (nor the AntiAdBlock filters, from English or Annoyance).

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

![Capture](https://user-images.githubusercontent.com/16375271/77261715-2a147000-6c99-11ea-8213-60d806c4201e.PNG)

* **Expected behaviour**: It should allow me to do the tasks without adblocker turned off.

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

***Steps to reproduce the problem***:
Enter [giveaway.su](https://giveaway.su/giveaway/view/1607) and try to do the tasks with the AdBlocker turned ON.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:** [my list](https://github.com/ArmynC/ArminC-uBlock-Settings)

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  Windows 
Browser:                               | Chrome

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@ArmynC does thirs rule help?
`@@||giveaway.su/ad.js`

**Comment by ArmynC** [comment]
@Alex-302 I don't think so. 
But something like this should do it: `@@||giveaway.su/new/ad.js`

**Comment by Alex-302** [comment]
What do you see in filtering log?
Please open it and reproduce an issue.

**Comment by Alex-302** [comment]
Please check: `@@/ad.js$~third-party,domain=giveaway.su`

**Comment by ArmynC** [comment]
> What do you see in filtering log?
> Please open it and reproduce an issue.

![Capture](https://user-images.githubusercontent.com/16375271/77422451-263a3800-6dd6-11ea-97df-e5204eff0c6b.PNG)


> Please check: `@@/ad.js$~third-party,domain=giveaway.su`
Yeah, it works (acts like the one I posted above).

**Comment by Alex-302** [comment]
Ok, added to Base filter.
