### ISSUE TITLE
https://ru.investing.com/ - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5207]
Screenshot:

<details>

![image](https://cloud.githubusercontent.com/assets/27292111/26663027/b2599ee0-4690-11e7-9ab1-7bcadeac9f7e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome / Opera
Adguard version: | 6.2 / 1.4.1
Adguard driver (Windows): | WFP 
Adguard filters: | 1 2 3 4 5 14

Ticket ID: 1476529

**Comment by Alex-302** [comment]
@seanl Could you, please, help with JS rule for extension? This script with `civitik.com` looks similar to our obfuscated trafmag script

**Comment by seanl-adg** [comment]
It is Uponit, but they do not set their api `window.upManager`. I haven't found to abort their script. Adding `webrtc` worked on my end but noticed that they are using the technique described in https://github.com/gorhill/uBlock/issues/1930#issuecomment-301052117 for `WebSocket` (strangely they are not doing it for `RTCPeerConnection`) so added a csp rule.
