### ISSUE TITLE
Turkish filter question

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#5209]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: User noticed that:
Line #73
||amazonaws.com*/ad-maven-public-cdn*/$third-party^M is a part of Turkish filter

What is the reason? Is it correct? 
ID:1564642

Screenshot: https://prnt.sc/feleaa 

Thank you!

**Comment by danidoedel** [comment]
That's the correct link to the line: https://github.com/AdguardTeam/AdguardFilters/blob/master/TurkishFilter/sections/adservers.txt#L55

The other does link it to something completely different.

**Comment by Alex-302** [comment]
@vmalyuta the rule is correct
