### ISSUE TITLE
Google Analytics JS

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#52107]
@Alex-302 

EasyPrivacy blocks these scripts, but AdGuard does not.

https://www.natro.com/blog/siteme-erismesini-istemedigim-ip-adresini-htaccess-dosyasi-uzerinden-nasil-engellerim/

`https://cdnblog.natrocdn.com/wp-content/plugins/wp-google-analytics-events/js/main.js?ver=1.0`

<details><summary>Screenshot:</summary>

![ggg](https://user-images.githubusercontent.com/34379403/77374863-e72bc880-6d7c-11ea-85aa-ce44345fabdc.png)

</details>

---

https://www.canliradyodinle.fm/radyo-voyage-dinle.html

`https://www.canliradyodinle.fm/wp-content/cache/busting/google-tracking/ga-af5c617d36e28d19710b882a6824e213.js`

<details><summary>Screenshot:</summary>

![g2](https://user-images.githubusercontent.com/34379403/77374975-3e319d80-6d7d-11ea-84d6-09f4bd0246df.png)

</details>

---

https://www.hesaplamamotoru.com/iki-tarih-arasi-hesaplama-motoru

`https://www.hesaplamamotoru.com/js/googleAnalytics.js`

<details><summary>Screenshot:</summary>

![ga](https://user-images.githubusercontent.com/34379403/77469485-37a83200-6e20-11ea-9f54-4319eb83282e.png)

</details>

**Comment by Alex-302** [comment]
1, 2 - blocked;
3 - not an issue. Just initial GA script in separate file. Usually it is inline script.
