### ISSUE TITLE
inoreader.com - vertical scroll failure

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5210]
User can't scroll to the bottom end. In that case some labels don't mark as viewed.

URL:

http://www.inoreader.com/all_articles

<details><summary>Screenshot:</summary>

![screen shot 2017-06-01 at 12 07 11 2](https://cloud.githubusercontent.com/assets/28726429/26672819/4c9ddcdc-46c3-11e7-8df9-0cedfba4b9c7.png)

</details>

<br>
***System configuration***

Information | value
--- | ---
Operating system: | MacOS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 12, 14

Ticket ID #1530187

**Comment by Alex-302** [comment]
Not reproduced. Which filter breaks it?

**Comment by altokarev** [comment]
English.

**Comment by Alex-302** [comment]
Try 
```
@@||inoreader.com^$urlblock
```

**Comment by altokarev** [comment]
Nothing. English filter still affecting. Checked twice.

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/28726429/26778970/31e6d890-49ec-11e7-948d-74ed9ac3e042.png)

</details>

There are few placeholders, but scroll works well.

**Comment by Alex-302** [comment]
check with another filters

**Comment by altokarev** [comment]
I unchecked only English filter. Other filters are enabled. I assure you that it affects.

**Comment by Alex-302** [comment]
check 
@@||inoreader.com^$jsinject

**Comment by altokarev** [comment]
Nope. But with this page reloads through time, in fact. Once OK, another without content.

**Comment by altokarev** [comment]
It works, but some placeholders appears.

Just as I showed here: https://github.com/AdguardTeam/AdguardFilters/issues/5210#issuecomment-306146842

**Comment by Alex-302** [comment]
Ok, try to find URL, which must be unblocked
@@||inoreader.com^$content,elemhide
