### ISSUE TITLE
filmix.me - ad missed by extension

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5211]
URL:

https://filmix.me/page/2/

<details><summary>Screenshot:</summary>

![screen shot 2017-06-01 at 17 21 30](https://cloud.githubusercontent.com/assets/28726429/26684434/ab5c27ac-46ef-11e7-855a-c99bfbad545c.png)

</details>
<br>
***System configuration***

Information | Value
--- | ---
Operating system: | MacOS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 12, 14

**Comment by Alex-302** [comment]
Fixed
