### ISSUE TITLE
http://mobil.mopo.de - missed ad 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5212]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://mobil.mopo.de/hamburg/ehemalige-esso-haeuser-so-soll-der-neubau-auf-st--pauli-heissen-und-aussehen-26998514 - Social widget leftover before article text, social widget when scrolling down

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/26687052/7ce4f284-46f7-11e7-9ac5-9c6dcf326ee9.png)

![image](https://cloud.githubusercontent.com/assets/23372054/26687065/85a59f04-46f7-11e7-8d6f-290da38250d4.png)

</details>

***System configuration***

Application version: 1.2.2.81
Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.20.2 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.57 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.1 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.55 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.50.49 Enabled=NO
ID=6 Name="German filter" Version=1.0.34.55 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.93.6 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.8.58 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.42 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.65 Enabled=NO
ID=101 Name="EasyList" Version=1.0.70.48 Enabled=NO
ID=219 Name="ChinaList+EasyList" Version=1.0.2.83 Enabled=NO

PRO:
Pro feature DISABLED.
System-Wide filtering DISABLED.

Ticket ID: 1480792

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
