### ISSUE TITLE
Ads on: imgchilibum.ru

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5214]
***Description***:
* **Current behaviour**: 

Ads on http://imgchilibum.ru/v.php?id=f09140f48b42b6c7eefcd57ac354e804

Screenshot:

![ogbqivah](https://cloud.githubusercontent.com/assets/27874000/26687300/0fdc3a3e-46f8-11e7-9ac3-56e66fc9e41a.png)

***Steps to reproduce the problem***:

Visit the website, upload any picture, visit the link to the uploaded picture 

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | Chrome extension
Adguard filters: | RU AdList, Russian, English

Ticket ID: 1076701

**Comment by Alex-302** [comment]
Fixed

**Comment by TomCruiseXZ** [comment]
Забыли  убрать остатки
http://f4.s.qip.ru/Ogbqivbx.png

**Comment by Alex-302** [comment]
Знак вопроса - это не часть рекламы, верстальщик напартачил.
Надпись убрал.
