### ISSUE TITLE
Ads on: investopedia.com

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5215]
***Description***:
* **Current behaviour**: 

Ads on http://www.investopedia.com/terms/a/aggressor.asp

Screenshot:

![screen shot 2017-06-01 at 8 06 09 pm](https://cloud.githubusercontent.com/assets/27874000/26691451/cb2147c8-4705-11e7-8765-0fe8ba8f321e.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP 

Ticket ID: 1050376

**Comment by seanl-adg** [comment]
Fixed.
