### ISSUE TITLE
http://coolsoft.altervista.org/en/virtualmidisynth adblock detection

### ISSUE THREAD

**Issue by miguedevel** [AdguardTeam/AdguardFilters#5218]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://coolsoft.altervista.org/en/virtualmidisynth
* **Current behaviour**: Detects adblocker after few seconds and prevents browsing the site.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/26647325/26694107/62df24a4-46d4-11e7-97bb-fde8f68b3da4.jpg)
</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Edge
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Adguard DNS: | None
Stealth mode options(Windows) | off
Adguard filters: | English, Spyware, Experimental, Annoyances, Adblock Warning Removal List

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed
