### ISSUE TITLE
adult sites with ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5219]
Here's the list we received from one costumer, some unpoular porn sites with banners. See screenshots here: 1566670

http://tsn1.ru/
http://mokrayakiska.com/
http://eliotgroup.ru/
http://prnparty.com/hotvideo/tjolka-v-gimnasticheskom-kupalnike-zanimautsja-seksom.html
http://adr-mediate.com/6492571-masturbiruet-na-gimnasticheskom-myache.html
http://wrlc.info/post/1/6726#
http://hirematt.com/11847219-porno-video-devushki-v-gimnasticheskom-kupalnike-smotret-onlaynovy.html
http://selestra.info/post/6/7075#
http://romagrom.ru/video-v-kupalnike-porno.html
http://pocketscheme.net/maid/281824-v-prozrachnam-kupalnike-vanay-celka.html
http://wegcomputerforensics.com/post/34/15407#
http://snt-agrarnik.ru/se/%D0%BB%D0%B5%D1%81%D0%B1%D0%B8%D1%8F%D0%BD%D0%BA%D0%B8-%D0%B2-%D0%BB%D0%B5%D0%BE%D1%82%D0%B0%D1%80%D0%B4%D0%B5#
https://alteregoru.ru/se/%D0%BF%D0%BE%D1%80%D0%BD%D0%BE-%D0%B3%D0%B8%D0%BC%D0%BD%D0%B0%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-%D0%BA%D1%83%D0%BF%D0%B0%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA#
http://figuredmaple.tv/3605630-gimnastka-v-gimnasticheskom-kupalnike-erotika.html
http://exstasia.tv/pissing/page/175/
http://pornodiesel.porn/389214-devushka-v-kupalnik-masturbiruet.html
http://ecosafaritours.com/post/6/12#
http://npia.sexy/outside/44374-krasavica-v-golubom-kupalnike.html
http://kinshi.mobi/big-tits/355509-sestra-odevala-kupalnik-ya-spalil.html
http://lenkino.porn/fisting/336400-portfolio-devushek-v-kupalnike.html
http://npia.sexy/pussylicking/461745-nemka-masturbiruet-na-gimnasticheskom-share.html
http://turkutv.tv/
http://newventuretools.co/anal/243619-Medsestra-beret-analiz-spermy.html
http://www.nau-tech.com/anal/21893-Ozabochennaya-medsestra-beret-na-analiz-spermu.html
http://flasecrets.me/
http://canal69.tv/
http://namemedia.tv/

***System configuration***

Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.1/1.4.1
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Adguard filters: | below

1. Subscriptions: FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
2. FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt
3. FilterId:4 Name: Social media filter Url: https://filters.adtidy.org/extension/chromium/filters/4.txt
4. FilterId:10 Name: Filter unblocking useful ads Url: https://filters.adtidy.org/extension/chromium/filters/10.txt
5. FilterId:1 Name: Russian filter Url: https://filters.adtidy.org/extension/chromium/filters/1.txt
6. FilterId:0 Name: User filter Url: no_url

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by vmalyuta** [comment]
More websites: 
http://mokrayakiska.com/
http://tectonica-plus.ru/rasslablyayushiy-massazh-penisa.html
http://gastro-bar.ru/skachat-mat-daet-sinu-korotkoe-video.html
http://kviker.ru/
http://ordino.ru/prosto-mia-porno-skachat.html
http://articlub.ru/foto-golih-malchikov-s-odetimi-devushkami.html
http://flagman-podarkov.ru/
http://gamerzparadise.info/post/21/%D0%BF%D0%BE%D1%80%D0%BD%D0%BE-%D0%B2-%D1%82%D1%80%D1%83%D1%81%D0%B0%D1%85-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D0%B8#
http://olyalens.ru/
http://phoneprotect128.online/?voluumdata=BASE64dmlkLi4wMDAwMDAwOS1hNTk3LTRmMWMtODAwMC0wMDAwMDAwMDAwMDBfX3ZwaWQuLmNlYjQ0MDAwLTQ4ZmItMTFlNy04Y2Y5LWFlZTA1ZDRlOTk4Zl9fY2FpZC4uMjkzZGM1ZTAtMmZlYS00OTVkLWJhNDItNjVlOTc4NjZmMTRkX19ydC4uRF9fbGlkLi5mZTRhYmE5My1iNzQzLTQ1NDYtOWQwNy02ZDFkYzcwMTI5M2VfX29pZDEuLjk3Y2JhOTg5LThlMjItNDljYy05NmZmLTBjYmI1YmUzNDhmYl9fdmFyMS4uYjZhNzI1ODQtNDhmZC0xMWU3LWFlZWMtMTE0MTQxNTViM2MwX192YXIyLi4xNTYxXF9cOTYzMWNmZGI2YzE0X19yZC4uX19haWQuLl9fYWIuLl9fc2lkLi5fX2NyaS4uX19wdWIuLl9fZGlkLi5fX2RpdC4uX19waWQuLl9faXQuLl9fdnQuLjE0OTY1NjQwMTk2MzA&clickid=b6a72584-48fd-11e7-aeec-11414155b3c0&pub_id=1561_9631cfdb6c14&_uu=#
http://steelseed.ru/chleni-vozbuzhdayushie-bolshie-foto.html
http://www.pskov.kp.ru/daily/26439/3310156/
http://nudisty-photo.com/male-nudists/

**Comment by Alex-302** [comment]
Сайты с запредельно низкой посещаемостью.
Добавил
```
||eberalofe.pro$third-party
||hahedttont.pro^$third-party
```
