### ISSUE TITLE
ripsave.com [ads]

### ISSUE THREAD

**Issue by ArmynC** [AdguardTeam/AdguardFilters#52215]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: In the corner, I have some ads.

* **Current behaviour**: 

![ripsave](https://user-images.githubusercontent.com/16375271/77562840-354de280-6ec9-11ea-95bb-89ea4aa7b3f1.PNG)

***Steps to reproduce the problem***:

Visit [ripsave.com](https://ripsave.com/)

***System configuration***

**Filters:** [My Filters](https://github.com/ArmynC/ArminC-uBlock-Settings)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  Windows
Browser:                               |  Chrome

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
I can't reproduce these ads.
Please update filters and check again.

**Comment by ArmynC** [comment]
@AdamWr I don't use EasyList (actually EasyList Lite) which hasn't the required filters.

**Comment by AdamWr** [comment]
In AdGuard, `EasyList` is part of `Base filter`, so I think that adding duplicate rule is not a good idea.
Also, as far as I know, in uBlock Origin `EasyList` is enabled by default, so I think that it would be better if you would add this rule to user filter:
`||inpagepush.com^`
