### ISSUE TITLE
Ventana emergente about:blank

### ISSUE THREAD

**Issue by wernser412** [AdguardTeam/AdguardFilters#52223]
No se si esto pueda estar aquí, de todos modos lo pongo.

Quisiera saber si pueden crear algún filtro para que la ventana emergente "about:blank" no aparezca ya intente con las soluciones puestas por la internet . aun así no consigo bloquearlo, funciona con extension "Poper Blocker - Google Chrome" y "Popup Blocker (strict)" pero quisiera un filtro en general para todos los exploradores.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/PopupBlocker
