### ISSUE TITLE
m.androidcentral.com/uk - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5222]
https://m.androidcentral.com/uk

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/15856304/26698655/77d7c88e-471f-11e7-90b7-2131b4af9296.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android, Mac
Browser: | Safari
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 2, 3, 4, 14, 11

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID: 1567637

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by seanl-adg** [comment]
Can't reproduce neither, but it would be helpful to have a HAR log. Maybe they are doing ad reinsertion only for some targeted users and if then we may not be able to reproduce it.

**Comment by Michael23456** [comment]
[adguard.har (1).zip](https://github.com/AdguardTeam/AdguardFilters/files/1065646/adguard.har.1.zip)
this is a HAR from my phone Meizu m3s(android 5.1)
filters: eng, rus, social, spyware, annoyance, mobile, experimental

**Comment by Alex-302** [comment]
@Michael23456 I need the logs.

**Comment by Michael23456** [comment]
waiting for logs from the customer

**Comment by Alex-302** [comment]
HAR is not a log

**Comment by Alex-302** [comment]
Check this rule
```
androidcentral.com#%#Object.defineProperty(window,'adonisConnType',{get:function(){},set:function(){throw'Adguard: stopped a script execution.'}});
```

**Comment by Michael23456** [comment]
fixed the issue on Mac, but I'm still getting the ad on Android(Chrome)

**Comment by Alex-302** [comment]
Ask user about it.
Ads are blocked on my devices.
