### ISSUE TITLE
http://unicode-search.net/ Banners

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardFilters#5223]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
http://unicode-search.net/ has banner product ads

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![screenshot_20170601-170511](https://cloud.githubusercontent.com/assets/185902/26700747/8abb438c-46ec-11e7-8d38-618255315442.png)
</details>

* **Expected behaviour**: 
No ads. _(N.B.: These should be easy to block via the Android AG filtering log, but that doesn't show much useful.)_

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

***Steps to reproduce the problem***:
Visit any page.

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Any
Adguard version: | 2.9.70
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  Off
Adguard DNS: | Default
Adguard filters: | All, except useful ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): N/A

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.

**Comment by TPS** [comment]
Thanks; I guess I gotta wait for it to propagate.  Just looking @ https://github.com/AdguardTeam/AdguardFilters/commit/aebde1087d5112c385c05ef821e3b54c12722a5b, though, does that _prevent_ the ad from downloading, or just _hide_ it?

**Comment by AdamWr** [comment]
> I guess I gotta wait for it to propagate.

Yes.

It just hide it.

**Comment by TPS** [comment]
Could something like
`||unicode-search.net/img/*_*x*.$image`
be added to outright _prevent_ the ad images, too?

**Comment by AdamWr** [comment]
These images weighs about 10KB - 30KB, so in my opinion, hide them is enough.
