### ISSUE TITLE
Missing pop-ups

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5224]
***Description***:
 When you go on http://www.theonion.ru/eto-interesno/26-usmanov-protiv-navalnogo-luchshie-fotozhaby there is a pop-up that can`t be closed manually, one has to wait for 115 seconds. Reproduced at our end.
Screenshot:

<details>

![s70601-234139](https://cloud.githubusercontent.com/assets/28784344/26702946/e9b7f81a-472f-11e7-8b98-38dd6ad28a5d.jpg)

</details>

***Steps to reproduce the problem***:

1. Go on http://www.theonion.ru/eto-interesno/26-usmanov-protiv-navalnogo-luchshie-fotozhaby 

***System configuration***

Information | value
--- | ---
Operating system: |  Android
Browser: | any
Adguard version: | 	2.9.70
Adguard mode (Android): |  Proxy(manual)
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard DNS: | None
Adguard filters: | 2, 3, 4, 14, 1, 11 

Ticket ID(if exists): 1029338

**Comment by Alex-302** [comment]
Fixed
