### ISSUE TITLE
jionews.com [Incorrect Blocking]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#52255]
Incorrect blocking on the following domain:

jionews.com

Note: After logging in, when viewing any TV channels, the content does not play when AG for Chrome is enabled. Disabling AG plays the video.

Ex: https://jionews.com/liveTv/ET-Now/212

The above link will not show you the video player as it is available only after logging in.

Attaching the Filtering Log for your reference.

![image](https://user-images.githubusercontent.com/6959116/77624161-6381ff80-6f67-11ea-9c60-e98fd6b39126.png)

Let me know if you need more information

EDIT: I disabled Stealth Mode in AG settings and I am able to play the video. So the question is why does it happen?

**Comment by AdamWr** [comment]
Could you please check this rule:
`@@||tv.media.jio.com/streams_live/$stealth,domain=jionews.com`

**Comment by Nzzyme** [comment]
It works fine after applying this rule. Thank you!

**Comment by AdamWr** [comment]
Added, thank you for checking it.
