### ISSUE TITLE
bychico.net - anti adblocker script

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#5226]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/17320558/26708871/29edaa0c-4757-11e7-9b12-307feaaab7b3.png)

</details>

***Steps to reproduce the problem***:

https://www.bychico.net/ru/decrease-the-size-of-all-files-without-losing-quality-and-without-zip/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |Android
Adguard version: | 2.9.70
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On 
Adguard filters: | English, Russian, User, Spyware, Social media, Annoyances, Mobile ads

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID(if exists): 1516731

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Какая-то ерунда. Текст генератором произведён, смысла там нет.
