### ISSUE TITLE
http://m.braunschweiger-zeitung.de - missed ad 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5227]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://m.braunschweiger-zeitung.de/politik/article210773257/Trump-USA-steigen-aus-dem-Pariser-Klimaabkommen-aus.html - Social widget leftover and ad on the main page

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Screenshot:

[//]: # (use the following code. Replace exciting URL by your)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота)
<details>

![image](https://cloud.githubusercontent.com/assets/23372054/26728626/8d7dafd4-47b3-11e7-82b6-ceb30b4e9d57.png)

</details>

***System configuration***

Application version: 1.2.2.81

Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.20.8 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.58 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.4 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.59 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.50.49 Enabled=NO
ID=6 Name="German filter" Version=1.0.34.57 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.93.6 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.8.59 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.42 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.65 Enabled=NO
ID=101 Name="EasyList" Version=1.0.70.48 Enabled=NO
ID=219 Name="ChinaList+EasyList" Version=1.0.2.83 Enabled=NO

PRO:
Pro feature DISABLED.
System-Wide filtering DISABLED.

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Ticket ID 1480792

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
