### ISSUE TITLE
Ad on sovets24.ru

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5230]
***Description***:
An ad appears on http://sovets24.ru/747-kak-udalit-papku-windows-old.html

<details><summary>Screenshot:</summary>

![screen shot 2017-06-02 at 9 22 12 pm](https://cloud.githubusercontent.com/assets/28784344/26739237/ba362c4c-47d9-11e7-9b35-7b46e7a1447d.png)

</details>

***Steps to reproduce the problem***:

Visit http://sovets24.ru/747-kak-udalit-papku-windows-old.html website and wait a few seconds for the ad to appear

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP 
Adguard DNS: | None 
Stealth mode options(Windows) | enabled
Adguard filters: | English, Spyware, Social media, Annoyances, Filter unblocking useful ads, Russian
Ticket ID (if exists): | 1449704

**Comment by Alex-302** [comment]
fixed
