### ISSUE TITLE
FIREBALL Malware

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardFilters#5231]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Described in detail: http://blog.checkpoint.com/2017/06/01/fireball-chinese-malware-250-million-infection/
_(Also, as a reminder, please consider https://github.com/AdguardTeam/AdguardForAndroid/issues/908 & https://github.com/AdguardTeam/AdguardForAndroid/issues/1104.)_

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)

* **Expected behaviour**: 
The included list will be blocked:
> attirerpage[.]com
> s2s[.]rafotech[.]com
> trotux[.]com
> startpageing123[.]com
> funcionapage[.]com
> universalsearches[.]com
> thewebanswers[.]com
> nicesearches[.]com
> youndoo[.]com
> giqepofa[.]com
> mustang-browser[.]com
> forestbrowser[.]com
> luckysearch123[.]com
> ooxxsearch[.]com
> search2000s[.]com
> walasearch[.]com
> hohosearch[.]com
> yessearches[.]com
> d3l4qa0kmel7is[.]cloudfront[.]net
> d5ou3dytze6uf[.]cloudfront[.]net
> d1vh0xkmncek4z[.]cloudfront[.]net
> d26r15y2ken1t9[.]cloudfront[.]net
> d11eq81k50lwgi[.]cloudfront[.]net
> ddyv8sl7ewq1w[.]cloudfront[.]net
> d3i1asoswufp5k[.]cloudfront[.]net
> dc44qjwal3p07[.]cloudfront[.]net
> dv2m1uumnsgtu[.]cloudfront[.]net
> d1mxvenloqrqmu[.]cloudfront[.]net
> dfrs12kz9qye2[.]cloudfront[.]net
> dgkytklfjrqkb[.]cloudfront[.]net
> dgkytklfjrqkb[.]cloudfront[.]net/main/trmz[.]exe
> 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

***Steps to reproduce the problem***:
Either get infected 😜 or try visiting any of the above.

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

**Comment by Alex-302** [comment]
ok
