### ISSUE TITLE
online.anidub.com - unblocked pop-up - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5232]
***Description***: 

 http://online.anidub.com/anime_tv/full/9369-sharlotta-charlotte-01-iz-13.html

<details><summary>Screenshot:</summary>

![screen shot 2017-06-03 at 8 42 25 am](https://cloud.githubusercontent.com/assets/27292111/26751028/a0bce04e-4838-11e7-82ff-e8324a3896e9.png)

![image](https://cloud.githubusercontent.com/assets/27292111/26751032/a89d00dc-4838-11e7-9f66-c03065bc2642.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.3

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.5.46 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.5 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.43 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.69 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.51.6 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.61 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.34 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.12 Enabled=YES

Ticket ID: 1568742

**Comment by Alex-302** [comment]
Чисто у меня.
Реклама вообще блокируется?

**Comment by veronikasav** [comment]
Нет, не блокируется.
<details>

![unnamed](https://cloud.githubusercontent.com/assets/27292111/26795152/458d8b64-4a2d-11e7-8c3e-1d291800e8f1.jpg)

</details>

**Comment by Alex-302** [comment]
А должна. У меня даже без ДНС и системной фильтрации чисто.
Наверное стоит в разделе iOS спросить.

**Comment by veronikasav** [comment]
Так, проверила еще раз. Реклама блокируется, но дело-то было в том сообщении, которое выскакивает при переходе на сайт. Можно его как-то заблокировать?

**Comment by Alex-302** [comment]
Думаю да. Умеете использовать Fiddler?
Вот здесь внизу описано, как сохранить запросы. Сделаете - тогда постараюсь заблокировать.

**Comment by ministr91** [comment]
"сообщении, которое выскакивает при переходе на сайт."
Тоже выскочило

**Comment by ministr91** [comment]
Написано, что мой браузер содержит вредоносное ПО и нужно срочно его обновить

**Comment by Alex-302** [comment]
Не повторяется.
Нужен сохранённый по этой инструкции(в конце страницы) трафик
https://forum.adguard.com/index.php?threads/missed-ads-submission-rules.1879/

**Comment by ministr91** [comment]
Да ладно, ты серьезно? Ну я же логи прикрепил, веб запросов и еще какой-то. По ним нельзя?

**Comment by ministr91** [comment]
Хотя нет, забыл кинуть ссылку. Если я логи сделаю, это подойдет?

**Comment by Alex-302** [comment]
ios-ный Адгард не может логировать запросы. Поэтому прошу через Fiddler их записать.

**Comment by ministr91** [comment]
Дело в том, что у меня тоже эта ошибка на Android. Логи нужны?

**Comment by Alex-302** [comment]
Да. И HAR тоже. После включения записи страницу открывай в приватной вкладке.

**Comment by ministr91** [comment]
Не получается у меня в приватной вкладке, сделал в обычной. http://my-files.ru/pjvzdw 
17:29 июнь 14 московское время

**Comment by Alex-302** [comment]
В смысле - не получается? Чисто что ли?

**Comment by ministr91** [comment]
Да. Остается в этой папке 1 файл cache. Я его хотел скинуть, но он у меня не переносится в другие папки, пробую его сразу в архив засунуть, тоже пишет ошибку. Решил защиту отключить, тоже не вышло. Тогда решил полностью приложение остановить. После этого файл пропал

**Comment by ministr91** [comment]
Глянь что я выше скинул

**Comment by ministr91** [comment]
Хотя нет, получилось. Глянь вот это http://my-files.ru/t3bv2m

**Comment by ministr91** [comment]
Это в приватной вкладке Google chrome Android

**Comment by Alex-302** [comment]
Вся реклама заблокирована, судя по логу. HAR не открывается.
Давай ещё разок, только после повтора проблемы выключи Адгард и прямо на телефоне заархивируй, если это делаешь в другом месте.

**Comment by ministr91** [comment]
Да ладно. 2 раза скинул логи. Что в обычной вкладке, что в приватной.
Теперь в какой? Архивирую на телефоне все.
Там не совсем реклама, а баннер этот. Скрин я кидал в этот файл, ты видел

**Comment by Alex-302** [comment]
@zebrum можешь у себя проверить?

**Comment by ministr91** [comment]
Попробуй выставить на Android все параметры как у меня. Фильтры по-умолчанию, версия 2.9 HTTP вкл, HTTPS вкл и самое главное - зайти через браузер Google chrome для Android

**Comment by zebrum** [comment]
@Alex-302 ни на iOS, ни на Android не повторяется.

**Comment by ministr91** [comment]
@zebrum и что делать?

**Comment by ministr91** [comment]
@ameshkov что делать то?

**Comment by ameshkov** [comment]
Ну har-файл надо еще раз записывать, если тот поврежден

**Comment by Alex-302** [comment]
@ameshkov может пишется криво?
Вот здесь выложен
https://github.com/AdguardTeam/AdguardFilters/issues/5232#issuecomment-308459766

**Comment by ministr91** [comment]
Какой мне на этот раз записывать? В приватной вкладке или нет?

**Comment by ministr91** [comment]
Я же кинул 2 ссылки. И там и там поврежден HAR файл?

**Comment by ameshkov** [comment]
@Alex-302
Да, криво записался, надо в конце файла удалить лишние `]}}`

@ministr91 это бета-версия или релиз?

**Comment by ameshkov** [comment]
@nkartyshov посмотри плз, в HAR-файле опять лишние символы появились в конце. Мы это исправляли же.

**Comment by ministr91** [comment]
Adguard 2.9.70 релиз

**Comment by Alex-302** [comment]
@ameshkov 
> надо в конце файла удалить лишние ]}}

удалял их. Похоже в этом проблема:

<details>

![image](http://imagizer.imageshack.com/img924/457/uYG3zH.png)
</details>

**Comment by ministr91** [comment]
@Alex-302 а что за проблема? Как ее исправить? С чем она связана? Почему в этом логе мой адрес эл.почты?

**Comment by Alex-302** [comment]
а пароль можно отправить через личное сообщение в Телеграмме.

**Comment by ministr91** [comment]
Хорошо, вернемся к проблеме с сайтом. Что делать?

**Comment by ameshkov** [comment]
> удалял их. Похоже в этом проблема:

Интересно, а можешь баг завести?

**Comment by ameshkov** [comment]
HAR можно вручную поправить, @Alex-302 перешлешь мне?

**Comment by Alex-302** [comment]
Это сообщение с помощью inline скрипта, встроенного в страницу плеера, выводится.
```
<script>
    var rurl = "http://mobile.sitestatlog.net/install/4";
    var answer = confirm("Ваш браузер устарел.Для увеличения скорости просмотра фильмов, защиты от вирусных атак и мошеннического ПО - установите бесплатный Яндекс браузер.Нажмите ОК для установки из Google play");
    
    if (answer){
        window.location = rurl;
    }
    
</script>
```
@ministr91 понаблюдай с таким правилом
```
moonwalk.co$$script[tag-content="window.location = rurl;"][max-length="600"]
```

**Comment by ministr91** [comment]
Проблема решена, тему можно закрывать

**Comment by ministr91** [comment]
Правило работает

**Comment by ministr91** [comment]
А в чем было дело? Почему у zebrum и у Alex-302 не повторяется эта проблема, а на моем Android устройстве воспроизводилась?

**Comment by Alex-302** [comment]
Правило добавил.

**Comment by ministr91** [comment]
@Alex-302, почему у одних эта проблема с сайтом есть, а у других нет? Почему в приложении myscore у мен, показывалась реклама, а у тебя нет? Как такое может быть?

**Comment by Alex-302** [comment]
Не знаю. На дроиде один раз повторилось, после чего правило сделал, и всё.
