### ISSUE TITLE
Remove an obsolete whitelist in Mobile filter

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#52335]
It seems
`@@||pornhub.com^$subdocument`
has been there from the beginning of the filter, but when I added
`||pornhub.com/ads/$subdocument, important`
I had no trouble. Unless you see problems I missed, the first rule and probably also
`@@||pornhubthbh7ap3u.onion^$subdocument`
can be removed.

**Comment by Alex-302** [comment]
Ok.
