### ISSUE TITLE
shoppy.gg [Incorrect Blocking]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#52344]
https://shoppy.gg/user/Phoneix

Blank page when AG for Chrome is enabled. Disabling AG shows the content of the page.

**Comment by AdamWr** [comment]
I can't reproduce it.
Please fill the template.

**Comment by krystian3w** [comment]
https://agrd.io/report

**Comment by Nzzyme** [comment]
The page is blank when enabling the "Spam404" filter. Include this filter in AG for Chrome and then reload the page to see a blank page. Please provide appropriate rule

![image](https://user-images.githubusercontent.com/6959116/80898921-f82a0b00-8d26-11ea-86dc-d29f8c421a47.png)

**Comment by krystian3w** [comment]
try report as cleared shop?

`https://www.spam404.com/report.html`

**Comment by Nzzyme** [comment]
Did already.

**Comment by AdamWr** [comment]
Please add this rule to user filter:
`||shoppy.gg^$badfilter`
