### ISSUE TITLE
missed ads http://spaces.ru/musicat/?Clt=2&from=main

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5234]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
missed ads http://spaces.ru/musicat/?Clt=2&from=main
![image](https://cloud.githubusercontent.com/assets/25711093/26751678/e246b99a-4847-11e7-9816-273a3d90ad28.png)

![image](https://cloud.githubusercontent.com/assets/25711093/26751672/c5463da2-4847-11e7-8fee-d7f772bf09dd.png)

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS / Android 
Browser: | chrome/opera
Adguard version: | 1.4.1/2.9.70
Adguard filters: | eng, rus, annoyance, social, spyware, experimental, mobile
Ticket ID (if exists): | 1560071

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
