### ISSUE TITLE
missed ad http://kinotut.tv/new_video.html

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5235]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/25711093/26751694/33a626fe-4848-11e7-93ce-66b92487d919.png)

![image](https://cloud.githubusercontent.com/assets/25711093/26751698/5b5499ce-4848-11e7-814b-599062cd91ab.png)

</details>

missed ad http://kinotut.tv/new_video.html

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS / Android 
Browser: | chrome/opera
Adguard version: | 1.4.1/2.9.70
Adguard filters: | eng, rus, annoyance, social, spyware, experimental, mobile
Ticket ID (if exists): | 1560071

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
