### ISSUE TITLE
97.riebao.cn - pop-up - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5236]
http://97.riebao.cn/i.php?pid=10042&uid=445

Pop-up appears and disappears every 2-3 sec

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/27292111/26751751/9deabf2e-4849-11e7-821d-605a893b8fa2.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.1

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.16.35 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.82 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.17 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.55 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.42 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.64 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.81.30 Enabled=YES

Ticket ID: 1568863

**Comment by AdamWr** [comment]
Unfortunately this website does not work on my end.

![image](https://cloud.githubusercontent.com/assets/29142494/26793069/e597f4ac-4a1c-11e7-8cea-2e611f0ab24f.png)

**Comment by veronikasav** [comment]
Please, try to ckeck on the Android phone. It works.

**Comment by Alex-302** [comment]
@veronikasav please ask about purpose of this popup - ad or just annoyance.
The rule
```
97.riebao.cn.tipInfo
```
