### ISSUE TITLE
missed ads http://www.pi-news.net/angela-merkel-das-fenster-zu-ihrer-seele/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5237]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

missed ads http://www.pi-news.net/angela-merkel-das-fenster-zu-ihrer-seele/
in the top

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/25711093/26752055/f81b0a98-484f-11e7-8582-1c76f1db1718.png)

in the middle
![image](https://cloud.githubusercontent.com/assets/25711093/26752054/f1f84c20-484f-11e7-9743-5968d8d79920.png)

in the bottom
![image](https://cloud.githubusercontent.com/assets/25711093/26752057/fd4810ec-484f-11e7-8912-b9261a784364.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | chrome
Adguard version: | 2.9.111
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On  
Adguard filters: | eng, rus, German, annoyance, spyware, social, experimental, mobile
Ticket ID (if exists): | 668430

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced with German filter.
