### ISSUE TITLE
The weather channel app ios

### ISSUE THREAD

**Issue by jo2dan23** [AdguardTeam/AdguardFilters#5239]
These domains showed up randomly. So idk if you will see them

events.mapbox.com
s.mopub.com ( this whole domain should be blocked)
data-agkn-com-*.amazonaws.com (agkn.com is a ad domain)
cdn.liftoff.io
sessionstat-*.amazonaws.com

The Weather Channel: Forecast, Radar & Alerts by The Weather Channel Interactive
https://appsto.re/us/9tZNr.i

**Comment by Alex-302** [comment]
nothing to block
