### ISSUE TITLE
Ads on the background - retailers.ua

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5240]
***Description***:
* **Current behaviour**: 
Background ads on http://retailers.ua/
Reproduced at our side.

<details><summary>Screenshot:</summary>
 
![default](https://cloud.githubusercontent.com/assets/28784344/26754631/fef3780a-4886-11e7-8260-f5b93bb20e9a.jpg)

</details>

***Steps to reproduce the problem***:

Go on http://retailers.ua/

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.1/1.4.1
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Adguard filters: | 2, 3, 4, 10, 1, 0
Ticket ID (if exists): | 1566670

**Comment by AdamWr** [comment]
Fixed.
