### ISSUE TITLE
androidpolice.com (amp)

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#52405]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Many empty ads placeholders

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![Screenshot_2020-03-28 Videos in Play Store listings will play automatically starting in September(1)](https://user-images.githubusercontent.com/29574622/77822240-0929a000-711b-11ea-99ea-f6ae2700496c.png)

</details><br/>

* **Expected behaviour**: 

There should be no empty ads place holders

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

Visit this page to reproduce this: https://www.androidpolice.com/2019/08/30/play-store-autoplay-videos/?amp

***System configuration***
Windows 10, Firefox, Ublock Origin with Adguard filters
**Filters:**

Adguard Base, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                     | Windows 10
Operating system version (Android/iOS) | Pro 1909
Browser:                               | Mozilla Firefox
AdGuard version:                       | Ublock Origin with Adguard filters 
Filters enabled:                       | Adguard Base, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media
AdGuard mode (Android only):           | 
Filtering quality (Android only):      | 
HTTPS filtering (Android only):        | 
Simplified filters (iOS only)          |
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | 
Helpdesk ID (if exists):               | 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by krystian3w** [comment]
For my is clear, you disabled almost stock filters actived in uBO and use only "five" by AdGuard?

for AMP also active "`AdGuard Mobile Ads`​​​​​​​​​".

**Comment by SeriousHoax** [comment]
@krystian3w I had uBlock related filters enabled. Now I've disabled those and added Adguard Mobile Ads along with other Adguard filters. Now everything is gone except one. 

![Screenshot_2020-03-28 Videos in Play Store listings will play automatically starting in September](https://user-images.githubusercontent.com/29574622/77825280-667d1b80-7132-11ea-831b-a1c45144b282.png)

Here's the log. Hope it helps: https://pastebin.com/vp56mn83

**Comment by krystian3w** [comment]
OK, I see this:

> ![obraz](https://user-images.githubusercontent.com/35370833/77825503-125e4100-710a-11ea-8ea6-8a884430ad66.png) |
> --- |

`androidpolice.com##.ai-track.ains-ap2_outbrain.ains`

**Comment by krystian3w** [comment]
@AdamWr  what do you think about generic:

```
##.amp-unresolved
```

used by EasyList?

**Comment by SeriousHoax** [comment]
Are we gonna have an Adguard filter for this?

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
