### ISSUE TITLE
Ads on the background-  goblin-online.ru

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5241]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Ads on the background: 
http://goblin-online.ru

<summary>Screenshot:</summary>

<details>

![screen shot 2017-06-03 at 7 09 38 pm](https://cloud.githubusercontent.com/assets/28784344/26755151/404c6d44-4890-11e7-9f65-59d2ed75b445.png)

</details>

***Steps to reproduce the problem***:

Go to http://goblin-online.ru

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Adguard filters: | 1, 2, 3, 4, 9, 10, 0
Ticket ID (if exists): | 1371396

**Comment by AdamWr** [comment]
Fixed.
