### ISSUE TITLE
Blocks the download of firebox extension - Mac

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5242]
***Description***:
* **Current behaviour**: 

Adguard  blocks the download of the 1password Firefox extension on Mac OS:
https://agilebits.com/onepassword/extensions/firefox?beta=false
After disabling Adguard the download and installation are possible.
Reproduced at our side.

<summary>Screenshot:</summary>

<details>

![screen shot 2017-06-03 at 7 44 40 pm](https://cloud.githubusercontent.com/assets/28784344/26755401/3383c3d2-4895-11e7-92ed-07ce1f72a848.png)

</details>

<summary>Screenshot:</summary>

<details>

![screen shot 2017-06-03 at 7 44 48 pm](https://cloud.githubusercontent.com/assets/28784344/26755404/3f236d82-4895-11e7-871a-4c05d6b34bef.png)
 
</details>

***Steps to reproduce the problem***:

1. Open Firefox browser
2. Go on https://agilebits.com/onepassword/extensions/firefox?beta=false
3. Turn off Adguard and reproduce the steps again

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Firefox
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 0, 2, 3, 4, 10, 111
Ticket ID (if exists): | 1568984

**Comment by Alex-302** [comment]
HTTPS filtering issue
https://github.com/AdguardTeam/HttpsExclusions/issues/26
