### ISSUE TITLE
ok.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#52441]
**1**. Фон.

<details><summary>Screenshot:</summary>

![2020 03 29-1](https://user-images.githubusercontent.com/17948007/77838680-d1ecda80-717e-11ea-8f7c-a525e585f37d.png)
</details>

`ok.ru#$#[class*="megafon"] { background-image: none!important; background-color: #f0f0f0!important; }`

___________________________________________________

 **2**. Кнопка от фона.

<details><summary>Screenshot:</summary>

![2020 03 29-2](https://user-images.githubusercontent.com/17948007/77838711-0496d300-717f-11ea-9100-aeeda0186e1b.png)
</details>

`ok.ru##[data-promo*="megafon"]`

___________________________________________________

 **3**. В разделе "Популярное на ОК" присутствуют рекламные вставки из группы "Мегафон".

<details><summary>Screenshot:</summary>

![2020 03 29-3](https://user-images.githubusercontent.com/17948007/77838887-ac60d080-7180-11ea-8485-6313a2aba45c.png)
</details>

`ok.ru##.feed-list > .feed:has(.feed_ava > [href="https://ok.ru/megafon"])`

[https://ok.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://ok.ru/)

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.4.11
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
Не повторяется.
@zloyden

**Comment by zloyden** [comment]
Тоже не повторяется.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/78035583-f957c900-7371-11ea-8413-ea416bda1330.png)

</details><br/>
