### ISSUE TITLE
https://casper.com/sheets - incorrect blocking 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5244]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://casper.com/sheets - The Spyware filter make some function of the page not working, like those + button at the FAQ section at the bottom of the page. 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image uploaded from ios](https://cloud.githubusercontent.com/assets/23372054/26757910/95c60434-48d5-11e7-84e3-4da65197d851.jpg)

</details>

***System configuration***

Application version: 1.2.2.81
Device: iPhone
OS: 10.3.2

Optimized enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.20.30 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.60 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.20.11 Enabled=NO
ID=14 Name="Annoyances filter" Version=1.0.13.64 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.93.6 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.61 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.42 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.66 Enabled=NO
ID=122 Name="Fanboy's Annoyances" Version=1.0.72.37 Enabled=NO
ID=104 Name="EasyList China" Version=1.0.81.45 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.3.63 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.81.30 Enabled=YES
ID=200 Name="ABP Japanese Filters" Version=1.0.4.90 Enabled=NO
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=NO
ID=208 Name="Malware Domains" Version=1.0.81.18 Enabled=NO

PRO:
Pro feature DISABLED.
System-Wide filtering ENABLED.
DNS server: System Default

Ticket ID 1254632

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||cdn.optimizely.com/js/*.js$domain=casper.com
```
