### ISSUE TITLE
Cookie pop-up: deutsche-vogelstimmen.de

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5246]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Cookie pop-up is not blocked by Adguard on http://www.deutsche-vogelstimmen.de/
Reproduced at our side

<summary>Screenshot:</summary>

<details>

![image1](https://cloud.githubusercontent.com/assets/28784344/26760039/94fb3780-4917-11e7-890e-76d873982fb9.png)

</details>

***Steps to reproduce the problem***:

Go on http://www.deutsche-vogelstimmen.de/

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Adguard version: | 1.2.1.71
Simplified filters(iOS) | Off
Adguard DNS: | None 
Adguard filters: | 0 2 3 14 6 11 12 101 118 107, 207, 229  
Ticket ID (if exists): | 1569200

**Comment by AdamWr** [comment]
I found few more identical websites, so I added rules for them too.

Fixed.
