### ISSUE TITLE
freetorrmd.org - ads leftover

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5247]
***Description***:
* **Current behaviour**: 

Ads on the background http://freetorrmd.org/torrent/18175/tinto-brass-o-zhenschiny-fallo
Reproduced at our side.

<summary>Screenshot:</summary>

<details>

![screen shot 2017-06-04 at 2 43 27 pm](https://cloud.githubusercontent.com/assets/28784344/26761228/3e4c111c-4934-11e7-8fe6-df416dcd6bde.png)

</details>

***Steps to reproduce the problem***:

Go on http://freetorrmd.org/torrent/18175/tinto-brass-o-zhenschiny-fallo

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 14, 0
Ticket ID (if exists): | 1076701

**Comment by Alex-302** [comment]
Fixed
