### ISSUE TITLE
missed ad in Blackmart app

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5248]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
missed ad in Blackmart app
[Blackmart+v0.99.2.103B.apk.zip](https://github.com/AdguardTeam/AdguardFilters/files/1050352/Blackmart.v0.99.2.103B.apk.zip)

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/25711093/26762099/c0a0cb70-4944-11e7-90ca-9ee7d9834430.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.111
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | eng, rus, annoyance, spyware, social, mobile, experimental
Ticket ID (if exists): | 1516731

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
