### ISSUE TITLE
m.bild.de - ad leftover, social widget buttons - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5249]
http://m.bild.de/news/inland/rock-am-ring/veranstalter-rastet-aus-52029352.bildMobile.html?wtmc=mw

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/27292111/26762220/3f987d90-4947-11e7-9f91-338f88e5282b.png)

![image](https://cloud.githubusercontent.com/assets/27292111/26762221/43e26f5a-4947-11e7-8c77-433c48cf5bcb.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.18.10 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.10 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.49 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.76 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.1.3 Enabled=YES
ID=6 Name="German filter" Version=1.0.33.98 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.38 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.13 Enabled=YES
ID=101 Name="EasyList" Version=1.0.71.31 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.71.52 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.63.45 Enabled=YES

Ticket ID: 1560404

**Comment by Alex-302** [comment]
fixed
