### ISSUE TITLE
MindTap - Cengage Learning

### ISSUE THREAD

**Issue by yokoffing** [AdguardTeam/AdguardFilters#52496]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: The filter blocking the script, `/ruxitagentjs_` , prevents the user from access the online textbook.
* **Current behaviour**: Can't view online textbook. I have to whitelist the script that's blocked.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

**Script blocked:** https://postimg.cc/TygWMTvN

**Comment by Alex-302** [comment]
Hi. Please provide URL and screenshot.

**Comment by yokoffing** [comment]
@Alex-302, please disregard. I uncovered that the page breakage was a [Fanboy Annoyance list issue](https://github.com/easylist/easylist/issues/5171#issuecomment-606171955).
