### ISSUE TITLE
False positive :  https://my.vodokanal.kiev.ua/login

### ISSUE THREAD

**Issue by Alexander1414x** [AdguardTeam/AdguardFilters#52490]
URL:
https://z.moatads.com/addthismoatframe568911941483/moatframe.js
Тип:
JavaScript
Источник:
my.vodokanal.kiev.ua
Правило:
||moatads.com^$third-party
Фильтр:
Базовый фильтр AdGuard

еще

URL:
https://platform.twitter.com/widgets/widget_iframe.d0f13be8321eb432fba28cfc1c3351b1.html?origin=https%3A%2F%2Fmy.vodokanal.kiev.ua
Тип:
HTML
Источник:
platform.twitter.com
Правило:
twitter.com#%#!function(){(new MutationObserver(function(){document.querySelectorAll('div[style^="padding-bottom: 0px;"] > div[style^="padding-top:"] > div:not([class]):not([style]').forEach(function(b){Object.keys(b).some(function(a){if(a.includes("reactEventHandlers")){a=b[a];try{var c=a.children._owner.memoizedProps.id;c.includes("promotedTweet")&&(b.style="display:none!important;")}catch(d){}}})})})).observe(document,{childList:!0,subtree:!0})}();
Фильтр:
Базовый фильтр AdGuard

**Comment by Alex-302** [comment]
@Alexander1414x что сломано-то?

**Comment by Alex-302** [comment]
Лучше через меню Адгарда отправьте жалобу, проще понять будет.

**Comment by Alexander1414x** [comment]
Чат скорее проблема с общением оператора через КиевВодоканал, через Домашний Кабинет.

**Comment by Alex-302** [comment]
Туда без аккаунта не попасть. Какой фильтр ломает?

**Comment by Alex-302** [comment]
Видимо включен фильтр раздражителей, одна из задач которого - блокировка сторонних виджетов чатов.
Добавьте в пользовательский фильтр:
`@@||jivosite.com^`

**Comment by Alexander1414x** [comment]
Ок!
