### ISSUE TITLE
Missed ad place in the "theScore: Sports Scores & News" app

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5250]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
Missed ad place in the "theScore: Sports Scores & News" app
https://play.google.com/store/apps/details?id=com.fivemobile.thescore

there is a black empty rectangle where the ads should be

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/25711093/26762776/6e43ac9c-4950-11e7-98f5-3e56cf5d23f0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Android
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | eng, rus, annoyance, spyware, social, mobile, experimental
Ticket ID (if exists): | 1569011

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
This leftover is hard-coded.
