### ISSUE TITLE
Ads leftover on desiserials.org 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#5251]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Our customer found some ads leftover on desiserials.org (there are some preroll videos on some of them as well)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/17320558/26765073/0e6b4d48-497d-11e7-85c0-03157d5dc5bc.png)

</details>

***Steps to reproduce the problem***:

http://www.desiserials.org/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.2.357
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | Off
Adguard filters: | User, Russian, Spyware, Social media, English
Ticket ID (if exists): | 1531498

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
