### ISSUE TITLE
Anti adblock script on desirulez.net

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#5252]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Anti adblock script

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/17320558/26765113/ba758694-497d-11e7-8f1c-55e3b4a93f85.png)

</details>

***Steps to reproduce the problem***:

http://www.desirulez.me/ 

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.2.357
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | Off
Adguard filters: | User, English. Russian, Spyware, Social media
Ticket ID (if exists): | 1531498

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Not reproduced on my end.

**Comment by Alex-302** [comment]
I don't see BlockAdBlock script on the pages at the moment. Please check again.

**Comment by AdamWr** [comment]
I also can not reproduce this directly on `desirulez.net`, but I found in this topic (http://www.desirulez.me/threads/1007980-Kaabil-2017-Watch-Online-Download) links to movies where I see BlockAdblock message - http://conference-hosting.us/watchvideo.php?url=zeibv87sxil3
and here - http://business-solutions.us/watchvideo.php?id=vri0oh4qp6eu

Rules:
<details>

`conference-hosting.us#@##banner_ad`

`business-solutions.us#%#(function() { var sto = window.setTimeout, re = /\.bab_elementid.$/; window.setTimeout = function(a, b) { if ( typeof a !== 'string' || !re.test(a) ) { return sto(a, b); } }.bind(window); var signatures = [ ['blockadblock'], ['babasbm'], [/getItem\('babn'\)/], ['getElementById','String.fromCharCode','ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789','charAt','DOMContentLoaded','AdBlock','addEventListener','doScroll','fromCharCode','<<2|r>>4','sessionStorage','clientWidth','localStorage','Math','random'] ]; var check = function(s) { var tokens, match, j, token, pos; for ( var i = 0; i < signatures.length; i++ ) { tokens = signatures[i]; match = 0; for ( j = 0, pos = 0; j < tokens.length; j++ ) { token = tokens[j]; pos = token instanceof RegExp ? s.search(token) : s.indexOf(token); if ( pos !== -1 ) { match += 1; } } if ( (match / tokens.length) >= 0.8 ) { return true; } } return false; }; var realEval = window.eval; window.eval = function(a) { if ( !check(a) ) { return realEval(a); } var el = document.body; if ( el ) { el.style.removeProperty('visibility'); } el = document.getElementById('babasbmsgx'); if ( el ) { el.parentNode.removeChild(el); } }.bind(window); })();`
</details>

<br>
Can I add them to English Filter?

**Comment by Alex-302** [comment]
Sure. If the first rule helps, add only it.

**Comment by AdamWr** [comment]
Fixed.
