### ISSUE TITLE
License and VPN IP's

### ISSUE THREAD

**Issue by doctorwizz** [AdguardTeam/AdguardFilters#5253]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
Hiya
I started getting trial expired on 2 of my windows PC's that I used today. I have 4-lifetime licenses for windows. I have not used my other 2 PC's lately. 
I use Private Internet Access (PIA) VPN which seems to now deactivate my licenses since my IP's change every login. This has not happened at all using a VPN before today. 
So, today when I activated, I see the VPN IP.:
TVPC
173.xxx.xxx.xx
It is going to be a pain to activate on every boot. 
Adguard version: 6.2357.1887
Windows 10 and 8.1
I used the windows PIA software. 
Any advice for this? 
Thanks
[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: 
Adguard version: 6.2357.1887
Adguard driver (Windows): | WFP / TDI
Adguard mode (Android): | VPN / Proxy(manual/auto)
Filtering quality (Android): | High-quality / high-speed / simplified
HTTPS filtering (Android): |  On (Default/Blacklist mode) / Off
Simplified filters(iOS) | On / Off
Adguard DNS: | None / Default / Family Protection
Stealth mode options(Windows) | 
Adguard filters: | 
Ticket ID (if exists): | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by danidoedel** [comment]
I don't think that's a filter issue?
https://github.com/AdguardTeam/AdguardForWindows/issues would be the right place for this I guess...

**Comment by doctorwizz** [comment]
I just clicked support from the Adguard app. This is where it took me. 
Didn't realize it was in the filters section.

**Comment by danidoedel** [comment]
Yeah that's confusing...
You can try to contact the support directly too: support@adguard.com
