### ISSUE TITLE
thehackernews.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#52536]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Ads related to doubleclick.net in every page

<details><summary>Screenshot:</summary>

![z](https://user-images.githubusercontent.com/29574622/77918275-770dcd00-72bd-11ea-8785-ac20bfe30f1d.png)
</details><br/>
* **Expected behaviour**: 

There should be no ads.

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

Visit the home page or any other page on the website: https://thehackernews.com/

***System configuration***
Windows 10, Firefox, Ublock Origin with Adguard filters
**Filters:**

Adguard Base, AdGuard Mobile Ads, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | Pro 1909
Browser:                               | Mozilla Firefox 74.0
AdGuard version:                       | 
Filters enabled:                       | Adguard Base, AdGuard Mobile Ads, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media
AdGuard mode (Android only):           | 
Filtering quality (Android only):      | 
HTTPS filtering (Android only):        | 
Simplified filters (iOS only)          | 
AdGuard DNS:                           | 
Stealth mode options (Windows only)    | 
Helpdesk ID (if exists):               | 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by zloyden** [comment]
Not reproduced with US IP. @AdguardTeam/filters-maintainers  please take a look.

**Comment by SeriousHoax** [comment]
Tried with a VPN connected to USA but same I still see that ad. 
Btw, the ad doesn't show up if I enable EasyList. 
These are the two applied filter I found in the log related to EasyList which made the ad disappear I think. Take a look, hope this helps.
![1](https://user-images.githubusercontent.com/29574622/78020218-da0d6b80-7372-11ea-9379-02faf6422051.PNG)
![2](https://user-images.githubusercontent.com/29574622/78020219-db3e9880-7372-11ea-83f6-71c174397bb2.PNG)

**Comment by zloyden** [comment]
For Ublock Origin you need to enable EasyList along with AdGuard Base or import this [filter](https://filters.adtidy.org/extension/ublock/filters/2.txt) and disable EasyList.

**Comment by SeriousHoax** [comment]
I know about this list but EasyList has too many filters and Adguard Base with half the filters seems equally effective. But for the ad that I'm seeing in hackernews, I think a filter can be created in Adguard Base to fix it.

**Comment by zloyden** [comment]
Hi. AdGuard Base is an additional filter to EasyList in Ublock Origin, that's why we don't add rules in this case.
