### ISSUE TITLE
imgrum.org - Ad leftover - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5255]
http://www.imgrum.org/

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/27292111/26771082/8fc24882-49c4-11e7-9fed-011d39dfe78c.png)

</details>

***System configuration***

Application version: 1.2.2.86

Device: iPhone
Platform: iOS
OS: 10.3.3

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.20.40 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.60 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.11 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.65 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.64 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.61 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.42 Enabled=YES

Ticket ID: 1480792

**Comment by AdamWr** [comment]
I think it is impossible to hide this totally on iOS.
I will add this rule - `imgrum.org##.blogpost_preview_fw > .fw_preview_wrapper > [class="pf_output_container"][style="text-align: center; margin-bottom: 0; height: 250px;"]` - but there will be little empty space.

**Comment by Alex-302** [comment]
You can add it. Leftovers are really small.

**Comment by AdamWr** [comment]
Fixed.
