### ISSUE TITLE
pikore.co - Ad leftover - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5256]
http://pikore.co/

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/27292111/26771130/fc8ac8ae-49c4-11e7-804d-9b7f1626ee81.png)

</details>

***System configuration***

Application version: 1.2.2.86

Device: iPhone
Platform: iOS
OS: 10.3.3

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.20.40 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.60 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.11 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.65 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.64 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.61 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.42 Enabled=YES

Ticket ID:  1480792

**Comment by AdamWr** [comment]
Fixed.
