### ISSUE TITLE
Non-blocking advertising

### ISSUE THREAD

**Issue by cka87** [AdguardTeam/AdguardFilters#52572]
Microsoft Edge yeni özellikleri!
https://go.squidapp.co/n/tzoVmve via SQUID App
![Screenshot_20200331-083351](https://user-images.githubusercontent.com/62925593/77990593-6c3d5180-732a-11ea-8504-3f9ad5502a0b.jpg)

**Comment by Alex-302** [comment]
@cka87 apps cannot be filtered as browsers. When you visit this site directly is it clean?
