### ISSUE TITLE
incorrect blocking http://procamp.agency/#poiskovaya-reklama

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5261]
***Description***:
incorrect blocking http://procamp.agency/#poiskovaya-reklama

if ADG is enabled this part is completele blocked but this is not an ad

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/25711093/26775242/b03a363e-49dc-11e7-9bca-ce0d81aebd3e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | chrome 
Adguard filters: | eng, rus, annoyance, experimental, social, spyware, mobile
Ticket ID (if exists): | 1560577

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced

<details>

![image](http://imagizer.imageshack.com/img924/7559/Dm35sJ.png)
</details>

**Comment by Michael23456** [comment]
missed this, Polish filter was enabled. It's only reproduced with Adblock&polish filter

**Comment by AdamWr** [comment]
It is because of this rule  - `~rp.pl##[id*="reklama"]` - I will fix this in Polish filter.

**Comment by AdamWr** [comment]
Fixed - https://github.com/MajkiIT/polish-ads-filter/commit/677772b410f6d232ff46f29243bde1282f6db1e1#diff-711027ed0794992ae3b8710d874f3df7R207
