### ISSUE TITLE
Youtube ads are not blocked in Yandex Browser

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#52629]
***Description***:
* **Current behaviour**: 

YouTube displays its ads on Yandex.Browser

***Steps to reproduce the problem***:

1. Install YB, attempt to watch YouTube

***Attempted Steps***
Cert check = OK, no 3rd party antiviruses or firewalls. Site is not in exclusions.

***HAR***
***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Windows
Operating system version (Android/iOS) | Windows 10, version 1909, build 18363
Browser:                               | Yandex.Browser (Release)
AdGuard version:                       | 7.3
Filters enabled:                       | Useful ads, Base, Russian, Annoyances, Tracking Protection, Social Media
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | null
Helpdesk ID (if exists):               | 1508476

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't reproduce. But Yandex.Browser prevent to block Yandex ads. Probably it has side effects.
