### ISSUE TITLE
blackboard.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#52627]
***Description***:
* **Current behaviour**: 

Unable to connect when AdGuard is on.

***Steps to reproduce the problem***:

1. Enable the protection and try to access Blackboard

***HAR file***
See ticket 2614838

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Windows
Operating system version (Android/iOS) | Windows 10, version 1909, build 18363
Browser:                               | Brave Browser
AdGuard version:                       | 7.3
Filters enabled:                       | Base, Annoyances, Tracking Protection, Social Media
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Block 3rd party cookies (180), Block 1st party cookies (4320), Block WebRTC, Block Push API, Block Location API, Remove X-Client-Data Header, Hide search queries, Send DNT header, Strip URL
Helpdesk ID (if exists):               | 2614838

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Please ask for remote access. And check with disabled
- filters;
- stealth mode;
- AdGuard extensions.

**Comment by akmLaVx** [comment]
Disabling **Block WebRTC** and **Self-destructing 1st-party cookies** under Stealth Mode settings has resolved the issue.
