### ISSUE TITLE
trynews.ru - Missed ad - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5262]
http://trynews.ru/politik/30811-organy-lzhivoy-propagandy-makron-brosil-putinu-v-lico-oskorblenie,full.html

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/27292111/26776767/43a0a6c8-49e3-11e7-85f4-0981c9d5fb72.png)

![image](https://cloud.githubusercontent.com/assets/27292111/26776771/49a6a7ac-49e3-11e7-9913-3bb1b5fdba20.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.20.44 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.60 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.11 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.52.2 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.6 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.81.38 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=237 Name="AdBlock Protector List (Incompatible with Adguard)" Version=1.0.0.38 Enabled=YES

Ticket ID: 1569561

**Comment by Alex-302** [comment]
fixed
