### ISSUE TITLE
websites with ads 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5264]
Here's the list we received from one customer, some unpopular sites with banners and missed ads. See screenshots here: 1566670

http://vgolos.com.ua/
http://www.gazeta-misto.te.ua/
http://charivne.info/
https://gre4ka.info/
http://korabelov.info/
http://bukpravda.cv.ua/
http://cikavosti.com/nlo-nad-poverhneu-pivnichnogo-polusa-soncia/
http://dyvys.info/
http://o.kr.ua/
http://infomist.ck.ua/
https://podillyanews.com/
http://krapka.rv.ua/
http://basket.com.ua/
https://khersondaily.com/
http://nikmedia.com.ua/
https://galas.te.ua/
http://acc.cv.ua/
http://news.dks.com.ua/
http://www.volyn24.com/
http://ternopillive.com.ua/
http://slavinfo.dn.ua/novosti/690772
http://gopri.in.ua/
http://ogo.ua/articles/view/2017-06-04/87117.html
http://tvoemisto.tv/
http://sudba.in.ua/dating

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.2 / 1.4.1
Adguard driver (Windows): | WFP  
Adguard filters: | 1 2 3 4 14

Ticket ID: 1566670

**Comment by ypetruk** [comment]
More websites: (Ticket ID: 1566670)
https://www.0352.ua/
http://medinfo.ua/
http://www.goodhouse.com.ua/
http://zdorov-info.com.ua/stati/oftalmologija/17929-kak-sohranit-zdorove-glaz-prichiny-letnego-konjunktivita.html
http://nastroenie.com.ua/ 
https://odessitua.com/
http://zhitomir.today/news/society/moz_rozvinchuie_10_poshirenih_mifiv_pro_medichnu_reformu-id20354.html  (javascript error)
http://gazeta.lviv.ua/2017/06/19/kir-uzhe-dobravsya-lvivshhini/
http://4vlada.com/rivne/51667
http://news.poltava.info/ (the banner which says that "your advertisement can be placed here")
https://sunny7.ua/zdorove/zdorovoe-pitanie/dlya-zdorovya-i-figury--5-prichin-upotreblyat-morojenoe-letom
http://ilenta.com/news/company/news_16720.html
http://www.proagro.com.ua/bp/grain/12691.html
http://7days-ua.com/
http://gazeta.zp.ua/
http://prozahid.com/content-47104.html
http://zak-kor.net/
http://zmi.ck.ua/sotsium/poltsya-znayshla-ymovrnogo-vbivtsyu-cherkaschanina-tlo-yakogo-znayshli-v-parku.html
http://krnews.ua/
http://www.pro-lugansk.in.ua/ofitser-natsgvardii-popal-v-plen-k-boevikam-lnr/
http://dnpr.com.ua/
http://grad.ua/
http://rivnepost.rv.ua/
http://vesti.dp.ua/
http://news.dks.com.ua/
http://sevastopolnews.info/
http://newsroom.kh.ua/
http://see-life.biz/
https://lvivski.in.ua/
https://ilikenews.com.ua/%D1%8F%D0%BA%D1%96-%D0%B7%D0%BC%D1%96%D0%BD%D0%B8-%D0%BF%D1%80%D0%B8%D0%BD%D0%B5%D1%81%D0%B5-%D0%BC%D0%B5%D0%B4%D1%80%D0%B5%D1%84%D0%BE%D1%80%D0%BC%D0%B0-%D1%83-%D1%81%D0%B5%D0%BB%D0%B0/ (Loading..)

**Comment by ypetruk** [comment]
More websites: (Ticket ID: 1566670)
http://kr24.com.ua/
http://ddk.dn.ua/news/article/23264?f=y
http://footballua.tv/ru/news/football/news-video/40269--simejni-rozbirki-u-simji-balotelli-video/
http://konotop.in.ua/novosti/ostann-novini/konotoptsi-prosyat-rozchistiti-kandibine/
http://radiotrek.rv.ua/news/lidiya_taran_pryihala_do_rivnogo_zdiysnyuvaty_mriyu_divchynky_hvoroi_na_dtsp_video_216826.html
http://volyn.tabloyid.com/
http://uagolos.com/ (Loading..)
http://zak-kor.net/
http://forpost.lviv.ua/
http://prozahid.com/content-47105.html
http://www.tourdnepr.com/ (Loading..)
http://prawwwda.com/
https://avtoblog.ua/news/svezhaja-kollektsija-avtomobilnyh-prikolov6083
http://dnpr.com.ua/content/operaciya-evakuaciya-v-dnepre-2-chasa-spasali-enota
http://favoritekherson.co/
http://kumar.dn.ua/news/kak_zhivetsja_ukrainskim_voennym_na_peredovoj_vblizi_krasnogorovki/2017-06-21-4729 (Loading..)
http://krlife.com.ua/

**Comment by veronikasav** [comment]
https://tvgid.ua/fotor/22062017/89058/p0/
https://tvgid.ua/
http://take-profit.org/
https://odessitua.com/
http://www.sknews.net/u-chernihovi-lider-tin-sontsya-rozpoviv-pro-svoje-korinnya-ta-tvorchi-plany/
http://www.ukragroconsult.com/(ad leftover)
http://volyn.tabloyid.com/
http://ddk.dn.ua/news/article/23314?f=y
https://www.44.ua/news/1700412
http://cfts.org.ua/
http://dnpr.com.ua/
http://prozahid.com/content-47191.html

**Comment by Alex-302** [comment]
да когда же он уймётся?
