### ISSUE TITLE
giga.de - Missed ad - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5265]
<details><summary>Screenshot:</summary>

![screen shot 2017-06-05 at 12 51 46 pm](https://cloud.githubusercontent.com/assets/27292111/26779388/d4d73710-49ed-11e7-84d3-d22bd2e5ef6e.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPad
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.20.36 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.60 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.11 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.64 Enabled=YES
ID=6 Name="German filter" Version=1.0.34.64 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.61 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.42 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.81.34 Enabled=YES

Ticket ID: 1441210

**Comment by Alex-302** [comment]
Seems to be a bug
https://github.com/AdguardTeam/AdguardForiOS/issues/405

**Comment by Alex-302** [comment]
Fixed.
