### ISSUE TITLE
Remove, comment out, or put under NOT_OTIMIZED obsolete anti-tracking rules in Japanese filters

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#52676]
These rules seem to be inherited from Fanboy Japanese
`/analysis/AccessLog?`
`/analysis1.`
`/analysis2.`
`/beacon.php3?`
`/beacon.php?`
`/clicktrack/`
`/jpn_gtracking.js`
`/json/count?`
`/page_beacon.`
`/pvcountup.`
but I haven't ever seen they came into play on my browsing. ~~And AFAIK
`/hist_count.`
was only seen in DTI blog which was shut down on 2013 (https://www.dtiblog.com/).~~
`.jp/analyze/` was used in an older version of Ninja Analysis and currently it is only seen in non-working form e.g. https://www.wikihouse.com/pukiwiki/index.php?%C9%D4%B6%F1%B9%E7%CA%F3%B9%F0%2F34
`.jp/urchin.js` is an older Google Analytics.
Even if some of them are still in use, I think they should be in Tracking Protection filters so remove all the rules mentioned here from Japanese filters, or at least put under NOT_OPTIMIZED.

EDIT:
All right, tho DTI blog was shut down those blogs are still on the Internet and the `/hist_count.` too.
Example: `https://reiputousatu.dtiblog.com/`
I suggest to add `||dtiblog.com/hist_count.` to Tracking Protection then.

**Comment by Alex-302** [comment]
> is an older Google Analytics

but this script is still available http://google-analytics.com/urchin.js

**Comment by Alex-302** [comment]
> but I haven't ever seen they came into play on my browsing

maybe some rules are obsolete. This is not critical issue.

> I suggest to add `||dtiblog.com/hist_count.` to Tracking Protection then.

ok, replaced

**Comment by Yuki2718** [comment]
@Alex-302 All right, then please consider to remove only
`/analysis1.`
`/analysis2.`
because they are so generic that they'll cause false positives e.g. images on this site:
`https://www.holdemmanager.com/hm3/`.
I could find more FPs by them using `https://publicwww.com/`.

**Comment by Yuki2718** [comment]
According to publicwww, only places "/clicktrack/*" is used appear to be tracking iframes called from ziyu.net scripts (e.g. `http://clicktrack.ziyu.net/js/2986.js` on `http://netaatoz.jp/`), which explains why I don't see it - AdGuard already blocks ziyu.net. And `/jpn_gtracking.js` & `/page_beacon.` returned 0 hit while `/pvcountup.` 1 hit on a Korean site. Anyway, I agree that these are not critical except for the two FP-prone rules.

**Comment by Alex-302** [comment]
Removed 
```
/analysis1.
/analysis2.
```
