### ISSUE TITLE
Incorrect blocking on page: seattletimes.com

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#5267]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

The video autoplays. Blocking element only works once. Video comes back when page is reloaded.
Furthermore, pausing, scrolling down, then up, causes he video to start again. 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )

<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/17320558/26783910/5eb9a1e2-4a03-11e7-9365-8f04bd1bd37c.png)

</details>

***Steps to reproduce the problem***:

http://www.seattletimes.com/sports/seahawks/eddie-lacy-calls-seahawks-weight-incentives-a-positive-challenge/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.2.1.71
Simplified filters(iOS) | Off
Adguard filters: | User filter, English filter, Spyware filter, Social media filter, Annoyances filter, Mobile Ads filter, Safari filter
Ticket ID (if exists): | 1418175

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
For user filter
```
seattletimes.com##.featured-media
||players.brightcove.net^$domain=seattletimes.com
```
