### ISSUE TITLE
missed annoyance - https://www.kl-ruppert.de/ 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#5268]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: missed annoyance - https://www.kl-ruppert.de/ 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[/
![image](https://cloud.githubusercontent.com/assets/23701680/26804438/a4c492ee-4a50-11e7-84b4-9165ee12fd89.png)
![image_uploaded_from_ios_720]

/]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.2.2.86

Device: iPhone
Platform: iOS
OS: 10.3.3
Optimized enabled: No
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.20.45 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.60 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.11 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.67 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.50.49 Enabled=NO
ID=6 Name="German filter" Version=1.0.34.65 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.93.6 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.8.61 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.43 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.66 Enabled=NO
ID=101 Name="EasyList" Version=1.0.70.48 Enabled=NO
ID=219 Name="ChinaList+EasyList" Version=1.0.2.83 Enabled=NO

Ticket ID (if exists): | 1480792

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Fixed
