### ISSUE TITLE
https://www.bronydom.net/ - ad leftover 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#5270]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://www.bronydom.net/ - ad leftover 

![image_uploaded_from_ios_720-2](https://cloud.githubusercontent.com/assets/23701680/26806782/60ca39a8-4a5b-11e7-97fc-c7ac4c425b54.jpg)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.2.2.86
Device: iPhone
Platform: iOS
OS: 10.3.3
Optimized enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.20.45 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.60 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.11 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.67 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.50.49 Enabled=NO
ID=6 Name="German filter" Version=1.0.34.65 Enabled=YES
ID=7 Name="Japanese filter" Version=1.0.93.6 Enabled=NO
ID=11 Name="Mobile Ads filter" Version=1.0.8.61 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.43 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.66 Enabled=NO
ID=101 Name="EasyList" Version=1.0.70.48 Enabled=NO
ID=219 Name="ChinaList+EasyList" Version=1.0.2.83 Enabled=NO

Ticket ID (if exists): | 1480792 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
I do not see this ad leftover, in this place I have antiadblock message.

![image](https://cloud.githubusercontent.com/assets/29142494/26824488/e0eeb432-4ab1-11e7-8dd7-78e029713145.png)


I will hide it.

**Comment by AdamWr** [comment]
Fixed.
