### ISSUE TITLE
Championat app - Ad leftover - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5273]
https://appsto.re/us/miR4w.i

Ad leftover in the article (any article).
 
<details><summary>Screenshot:</summary>

![image](https://cloud.githubusercontent.com/assets/27292111/26821125/08175306-4aae-11e7-82ac-861021b07775.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iPhone OS
OS: 9.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.20.44 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.60 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.11 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.67 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.52.2 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.62 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.61 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.43 Enabled=YES

Ticket ID: 1527855

**Comment by Alex-302** [comment]
It is impossible to remove it on iOS
