### ISSUE TITLE
dnepr.info - missed ad, social widget buttons - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5276]
http://dnepr.info/kino/spark-geroj-vselennoj

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/26909254-3dd4d580-4c08-11e7-8801-1a0599a3fce1.png)

![image](https://user-images.githubusercontent.com/27292111/26909258-4301db84-4c08-11e7-9690-4b7f25ee709d.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.20.65 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.64 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.18 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.75 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.52.12 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.68 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.45 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.81.30 Enabled=YES

Ticket ID: 1518078

**Comment by Alex-302** [comment]
Fixed
