### ISSUE TITLE
iclarified.com - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5279]
***Site***: http://www.iclarified.com/60892/apple-updates-its-app-store-review-guidelines-heres-all-the-changes
***Description***: Social widgets.

*Rule:*
```
iclarified.com##.article_header_share
```

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/26925692-0ddd8de8-4c4b-11e7-81b1-1297aab29d1d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.20.85
Spyware filter | 1.0.12.67
Social media filter | 1.0.20.21
Annoyances filter | 1.0.13.79
German filter | 1.0.34.75
Mobile ads filter | 1.0.8.68
Safari filter | 1.0.3.47

**Comment by Alex-302** [comment]
added
