### ISSUE TITLE
netdoktor.de - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5280]
***Site***: http://www.netdoktor.de/
***Description***: Ad leftover, cookie notice and newsletter stuff.

<details>
<summary>Screenshot</summary>

**http://www.netdoktor.de/:**

![image](https://user-images.githubusercontent.com/10995998/26925901-cc04ad7e-4c4b-11e7-8eaa-7a6500a471ab.png)

![image](https://user-images.githubusercontent.com/10995998/26925938-e82186ee-4c4b-11e7-9c83-8263199fd128.png)

**http://www.netdoktor.de/diagnostik/blutuntersuchung/:**

![image](https://user-images.githubusercontent.com/10995998/26926013-25470878-4c4c-11e7-98ce-da4c4619775b.png)

![image](https://user-images.githubusercontent.com/10995998/26926028-33c6a048-4c4c-11e7-87b9-e404e0894ea2.png)

![image](https://user-images.githubusercontent.com/10995998/26926041-416616f2-4c4c-11e7-8acc-de562180dae8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.20.85
Spyware filter | 1.0.12.67
Social media filter | 1.0.20.21
Annoyances filter | 1.0.13.79
German filter | 1.0.34.75
Mobile ads filter | 1.0.8.68
Safari filter | 1.0.3.47

**Comment by Alex-302** [comment]
fixed

**Comment by danidoedel** [comment]
@Alex-302 That ad leftover and newsletter leftover below is still there:

![image](https://user-images.githubusercontent.com/10995998/26950314-7d3ae210-4c9d-11e7-808f-e488c4fb4bea.png)

```
netdoktor.de##.slot-section-container
netdoktor.de##.footer-subscribe-list
```

**Comment by Alex-302** [comment]
Fixed
