### ISSUE TITLE
femibion.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5281]
***Site***: https://www.femibion.com/de_DE/home.html
***Description***: Cookie notice overlay blocks whole site until you click somewhere.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/26926276-4f681f56-4c4d-11e7-8fd9-4979ea8ae94e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.20.85
Spyware filter | 1.0.12.67
Social media filter | 1.0.20.21
Annoyances filter | 1.0.13.79
German filter | 1.0.34.75
Mobile ads filter | 1.0.8.68
Safari filter | 1.0.3.47

**Comment by Alex-302** [comment]
fixed

**Comment by danidoedel** [comment]
@Alex-302 Site is broken now and can't be scrolled. I think there is still some kind of "invisible" overlay.

**Comment by Alex-302** [comment]
removed
