### ISSUE TITLE
Need help to form a regex filter

### ISSUE THREAD

**Issue by specter78** [AdguardTeam/AdguardFilters#52829]
So, there's this filter
`trakt.tv###hu-ck--st-er-desk-top-wrapper`

And I want to apply this regex 
`hu\-*ck\-*st\-*er\-*desk\-*top\-*wrapper`

What would be the Adguard equivalent?

**Comment by krystian3w** [comment]
Comsetic filters may no support regex.

For Firefox or Paid Application (Windows / macOS) can you use html filtering if you see this wrapper in `viewsource:trakt.tv`

**Comment by specter78** [comment]
Thanks

**Comment by Alex-302** [comment]
Regex is not supported in CSS selectors.
You can try 
`trakt.tv##div[id$="-wrapper"][id*="hu-"][id*="#-ck-"]`
