### ISSUE TITLE
gala.de - Social widget - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5282]
***Site***: http://www.gala.de/stars/news/bill-cosby-muss-er-hinter-gittern-sterben--21381738.html
***Description***: Newsletter stuff in the sidebar when scrolling down and after the article. Social widgets after the article. Ad leftover at the end of the page.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/26926544-7577a0c6-4c4e-11e7-920e-855d0d326ac8.png)

![image](https://user-images.githubusercontent.com/10995998/26926567-8c28ce6c-4c4e-11e7-8969-93f9c5ae84f3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.357.1887
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.20.85
Spyware filter | 1.0.12.67
Social media filter | 1.0.20.21
Annoyances filter | 1.0.13.79
German filter | 1.0.34.75
Mobile ads filter | 1.0.8.68
Safari filter | 1.0.3.47

**Comment by Alex-302** [comment]
fixed
