### ISSUE TITLE
wortwuchs.net - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5283]
***Site***: http://wortwuchs.net/schreibweise/excellent-exzelent-exzellent/
***Description***: Anti Adblock Script

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/26947030-8109fc5c-4c91-11e7-847d-bdbefe2b5060.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.20.90
Spyware filter | 1.0.12.68
Social media filter | 1.0.20.26
Annoyances filter | 1.0.13.83
German filter | 1.0.34.77
Mobile ads filter | 1.0.8.70
Safari filter | 1.0.3.47

**Comment by AdamWr** [comment]
Fixed.
