### ISSUE TITLE
Ultimate Ninja Blazing - ошибка соединения

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#5285]
Буду краток. Android 4.4.4, adguard 2.9.70. Фильтры по-умолчанию, Фильтрация качественная HTTPS. При попытке входа в Ultimate Ninja Blazing пишет ошибку соединения. Отключил защиту и все вошло спокойно. 
http://my-files.ru/qmm2m3

**Comment by Alex-302** [comment]
А время?

**Comment by ministr91** [comment]
Ч же написал время, специально на видном месте

**Comment by ministr91** [comment]
В названии архива время стоит

**Comment by Alex-302** [comment]
Мне нужно локальное время в нормальном виде.

**Comment by ministr91** [comment]
Что значит в нормальном виде? 9 июня 0:00-0:01. Какое еще может быть?

**Comment by Alex-302** [comment]
> Что значит в нормальном виде?

с двоеточиями.

Сделай ещё лог запросов с выключиенной фильтрацией HTTPS.

**Comment by ministr91** [comment]
Так у меня стоят двоеточия, не понял. Пример можешь привести?
Отключил Фильтрацию HTTPS и все заработало

**Comment by ministr91** [comment]
http://my-files.ru/oh8stx
9  июня 16:25-16:26

**Comment by Alex-302** [comment]
Попробуй добавить этот домен в белый список фильтрации HTTPS и с включенной проверить
```
nrbnares-channel-or-jp.global.ssl.fastly.net
```

**Comment by ministr91** [comment]
Все работает, проблема решилась

**Comment by Alex-302** [comment]
Отлично.

**Comment by ministr91** [comment]
Тему закроешь? Исправления внесешь в базу?

**Comment by Alex-302** [comment]
Исправления внести не могу. Создал задачу.

**Comment by Alex-302** [comment]
Исключения HTTPS только в новой версии доступны. Неудобно, но пока так.

**Comment by ministr91** [comment]
А нельзя ли будет в будущем будет сделать их обновление по воздуху, как и блок.рекламы? Может стоит новую тему открыть с предложением этим?

**Comment by Alex-302** [comment]
Обязательно будет ~и не раз, весь мир в труху~, но потом
