### ISSUE TITLE
wissen.de - Social widget - Ad - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5287]
***Site***: http://www.wissen.de/
***Description***: Ad overlay. Ad leftover. Ad. Facebook leftover.

<details>
<summary>Screenshot</summary>

**Ad overlay:**

![image](https://user-images.githubusercontent.com/10995998/26951485-967d108c-4ca1-11e7-9cec-99477bff81ea.png)

**Facebook leftover:**

![image](https://user-images.githubusercontent.com/10995998/26951586-ffe270b2-4ca1-11e7-987a-3d0262148f82.png)

**Ad leftover:**

![image](https://user-images.githubusercontent.com/10995998/26951604-14d417d2-4ca2-11e7-9ae8-e45fef55a1db.png)

**Ad and Ad leftover:**

![image](https://user-images.githubusercontent.com/10995998/26951632-2d1cac78-4ca2-11e7-8371-29aaa402024d.png)

**Ad leftover (http://www.wissen.de/uv-schutz-fuer-die-augen-was-muss-man-bei-einer-sonnenbrille-beachten):**

![image](https://user-images.githubusercontent.com/10995998/26951671-51c8e780-4ca2-11e7-95fe-2fe4af6d7d3e.png)

**Ad leftover on mobile:**

![image](https://user-images.githubusercontent.com/10995998/26951713-7c51cbd4-4ca2-11e7-97fb-504e792b5acc.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.20.90
Spyware filter | 1.0.12.68
Social media filter | 1.0.20.26
Annoyances filter | 1.0.13.83
German filter | 1.0.34.77
Mobile ads filter | 1.0.8.70
Safari filter | 1.0.3.47

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr There is still some ad leftover:

That will remove it: `wissen.de##.ad-container`

![image](https://user-images.githubusercontent.com/10995998/27109907-0552c058-50a6-11e7-971a-1eb5b06949de.png)

**Comment by AdamWr** [comment]
I did not notice that, sorry.
Thank you.
Added.
