### ISSUE TITLE
stackexchange.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5289]
***Site***: https://german.stackexchange.com/questions/1705/w%C3%B6rter-mit-ung%C3%BCnstiger-silbentrennung
***Description***: Newsletter form at the right side.

*Rule:*
```
stackexchange.com###newsletter-ad
```

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/26956213-67eefee0-4cbc-11e7-8a62-d9e943ba91b7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.20.92
Spyware filter | 1.0.12.69
Social media filter | 1.0.20.26
Annoyances filter | 1.0.13.84
German filter | 1.0.34.78
Mobile ads filter | 1.0.8.70
Safari filter | 1.0.3.47

**Comment by AdamWr** [comment]
Added.
