### ISSUE TITLE
tubeoffline.com [ads]

### ISSUE THREAD

**Issue by ArmynC** [AdguardTeam/AdguardFilters#52890]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Ads above.
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

![Capture](https://user-images.githubusercontent.com/16375271/78458848-1fa49e00-76bd-11ea-819e-1dc7955e0a0b.PNG)

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

Enter here: `https://www.tubeoffline.com/download-YouTube-videos.php`

***System configuration***

**Filters:** [My Filters](https://github.com/ArmynC/ArminC-uBlock-Settings)

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  Windows
Browser:                               |  Chrome

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by krystian3w** [comment]
`##table[width="100%"] > tbody > tr[style="text-align:center"] > td > a[target="_blank"] > img`

**Comment by ArmynC** [comment]
> `##table[width="100%"] > tbody > tr[style="text-align:center"] > td > a[target="_blank"] > img`

Right, there was this ad below that I didn't saw. 
![Capture](https://user-images.githubusercontent.com/16375271/78472898-16f7aa80-7745-11ea-9f8a-437e7fbc4fae.PNG)

Still, there is this below 'written ad':
![Capture](https://user-images.githubusercontent.com/16375271/78472924-54f4ce80-7745-11ea-9a06-935f0731c659.PNG)

`##div.otherSites.borderCurve.divContent2:nth-of-type(7)`

And the VPN ad above:
`##body > div:nth-of-type(1)`

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.

**Comment by ArmynC** [comment]
![Capture](https://user-images.githubusercontent.com/16375271/78577923-77671480-7837-11ea-84c1-cbc9bc225a0d.PNG)

@zloyden The upper bar is still there. Is this what you meant to do? At least, I think you should remove the **Exposed** message because even if you have VPN it doesn't know so.

**Comment by zloyden** [comment]
Thanks for your reply, I removed it fully now.
