### ISSUE TITLE
openthesaurus.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5290]
***Site***: https://www.openthesaurus.de/
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

**https://www.openthesaurus.de/:**

![image](https://user-images.githubusercontent.com/10995998/26956303-ea19d1a6-4cbc-11e7-8ff6-ef9c711444b9.png)

**Mobile:**

![image](https://user-images.githubusercontent.com/10995998/26956339-269434d2-4cbd-11e7-862c-ca85bd929dd3.png)

**https://www.openthesaurus.de/synonyme/test:**

![image](https://user-images.githubusercontent.com/10995998/26956324-09732980-4cbd-11e7-9afe-3173a16dcd6f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.20.92
Spyware filter | 1.0.12.69
Social media filter | 1.0.20.26
Annoyances filter | 1.0.13.84
German filter | 1.0.34.78
Mobile ads filter | 1.0.8.70
Safari filter | 1.0.3.47

**Comment by AdamWr** [comment]
Fixed.
