### ISSUE TITLE
ExtCss подвешивает e.mail.ru

### ISSUE THREAD

**Issue by latrekc** [AdguardTeam/AdguardFilters#5292]
Правила из коммита  [98e2d13](https://github.com/AdguardTeam/AdguardFilters/commit/98e2d131c49e9716cf731f72c6cc9bdb79355ac6) подвешивают почту
![img-2017-06-09-14-59-08](https://user-images.githubusercontent.com/312648/26975255-a4d8dedc-4d27-11e7-97c9-bd7e5161b1a3.png)

Т.к. ExtCss бегает по всем div (которых многовато в DOM) каждые 50ms, то после каждого изменения DOM вкладка начинает есть 100% cpu и соответственно все тормозит.

Вы [выкатывали](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/537) уже в январе подобное правило и сейчас проблема аналогичная.

**Comment by latrekc** [comment]
@Alex-302 проблема очень массовая

**Comment by Alex-302** [comment]
@latrekc есть такое дело. Защита от блокировки тоже не самая лояльная к ресурсам)
На своём компе(правда с i7 4770k) ощутимого ухудшения не заметил.
У пользователей прям нещадно тормозит?

**Comment by Alex-302** [comment]
Правила убрал, минут через 30 обновление будет доступно.

**Comment by latrekc** [comment]
у меня на 2,2 GHz Intel Core i7 16 GB вкладка с почтой стала отъедать по 100% при скролле или смене папки/треда.
![img-2017-06-09-15-45-37](https://user-images.githubusercontent.com/312648/26976004-c90b74ec-4d2a-11e7-8c2e-e2fe530725ef.png)
Ну и по скриншоту видно, что handleDomChange 9 секунд отрабатывает

**Comment by Alex-302** [comment]
На форуме отписал.
