### ISSUE TITLE
tv.aftonbladet.se - Missed ad - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5293]
https://tv.aftonbladet.se/abtv/articles/218623

A short ad appears before the video starts.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/26990757-76a5e95e-4d60-11e7-8bdf-1eff10bcfb45.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iPhone OS
OS: 9.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.20.99 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.69 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.27 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.87 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.52.34 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.62 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.70 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.47 Enabled=YES

Ticket ID: 1566135

**Comment by Alex-302** [comment]
It is impossible on iOS. `$replace` rules are not supported.
