### ISSUE TITLE
Blocking TorGuard Affiliate URL's

### ISSUE THREAD

**Issue by OnBrink** [AdguardTeam/AdguardFilters#52936]
Hey guys

I have some issue with your Ad extensions/software blocking Torguard affiliate URL's, for example: https://torguard.net/aff.php?aff=3040

Here is an example: https://docs.gl-inet.com/en/3/app/openvpn/#get-your-configuration-file

If you browse here with your Ad Block disabled, if you click the TorGuard option, you will see there is an affiliate link going to TorGuard, if you enable Ad Block it is gone but others are fine, i'm are just curious why that might be and how can we solve this and stop you blocking TorGuard url's?

Thanks

**Comment by Alex-302** [comment]
Hi
Please don't igrore template when you open new issue. We need that info.

**Comment by OnBrink** [comment]
My apologies, I didn't see the template when I initially sent the response but I see it now when I click "New Issue" - do you need me to fill out this template still? my issue is basically that your software on any device or browser is filtering Torguard Affiliate url's.

**Comment by Alex-302** [comment]
We have 88 filters) So we need to know your settings.
Also you can try to find what causes this issue:
https://kb.adguard.com/en/technical-support/reporting-tool#diagnosis-of-an-issue

>  I didn't see the template

It is here:

![image](https://user-images.githubusercontent.com/8361299/78894922-a28b7700-7a76-11ea-8ca1-bf95f750e33e.png)
