### ISSUE TITLE
anti-adblock https://www.aplikasipc.com/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5294]
***Description***:
anti-adblock https://www.aplikasipc.com/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/25711093/27000394-3058fb4a-4db9-11e7-8c66-a58135ecbf6a.png)
![image](https://user-images.githubusercontent.com/25711093/27000395-3bcee048-4db9-11e7-8aaa-0ecc46d8cd30.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS / Android 
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | 2, 3, 4, 14, 5, 11, 102, 211 
Ticket ID (if exists): | 1551511

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
