### ISSUE TITLE
an indelible advertisement

### ISSUE THREAD

**Issue by arnoldii** [AdguardTeam/AdguardFilters#52944]
![20200406_004150](https://user-images.githubusercontent.com/63200023/78503084-6cf93c00-779f-11ea-8f47-8a4e63d574a2.jpg)

in this app below

![Screenshot_20200406-004308_Google Play Store](https://user-images.githubusercontent.com/63200023/78503130-a3cf5200-779f-11ea-8545-ca82217e8345.jpg)

**Comment by Alex-302** [comment]
Please send report using AdGuard
https://kb.adguard.com/en/technical-support/reporting-tool
