### ISSUE TITLE
temp-mail.org

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#52947]
после получения какого либо сообщения, над ним отображается реклама которая притворяется сообщением
![image](https://user-images.githubusercontent.com/19754243/78504237-0b6baa00-776c-11ea-80a7-d51f683ddd25.png)

**Comment by JobcenterTycoon** [comment]
i still get ads with that filter 

<img width="588" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/78576955-a9737900-782d-11ea-8a8c-a3e2f9f0c3ea.PNG">

**Comment by Alex-302** [comment]
I can't reproduce
![image](https://user-images.githubusercontent.com/8361299/78894420-acf94100-7a75-11ea-8199-ebed930a8662.png)
Please check for updates manually.

**Comment by JobcenterTycoon** [comment]
my fault

**Comment by Smorvel** [comment]
У меня вернулась эта реклама...

**Comment by Alex-302** [comment]
Повторить не могу
![image](https://user-images.githubusercontent.com/8361299/79074933-01abee80-7cf8-11ea-831b-2d59fa060b2d.png)
Нужен скриншот заблокированного в журнале.

**Comment by Smorvel** [comment]
@Alex-302 Я не знаю почему, но у меня не работает бролокировка по регуляркам.. Хотя изначально после добавления правила вроде все работало..
Я сделал `contains("AD")` вместо `contains(/^ad\s*\|/gi)` и начало блокировать.. Но я также пытался сделать `contains(/AD/g)` на это оно отказывается реагировать.. Куда копать? Я что то даже не представляю в чем может быть проблема..

**Comment by Alex-302** [comment]
Попробуй отключить все фильтры кроме базового, и очистить пользовательский фильтр.

**Comment by Alex-302** [comment]
Или проверь такое:
`temp-mail.org#?#.inbox-dataList > ul > li[class]:has(> div[class="col-box"] > a > span.inboxSenderEmail:contains(/^ad\s*\|.*|^AD\s*\|.*/))`

**Comment by Smorvel** [comment]
@Alex-302 Отключил все кроме базового и очистил свой - не помогло..
Вставил твое новое правило - заработало..

Но должно же и твое первое правило работать.. Я не понимаю что творится с этим адгардом) впрочем все как обычно.. сейчас попробую снести его и поставить чистый.. Дополню ответ если переустановка спасет...

**Comment by Alex-302** [comment]
Какая версия программы?

**Comment by Smorvel** [comment]
@Alex-302 7.3 (build 3048, CL 1.5.163)

**Comment by Alex-302** [comment]
7.4 попробуй

**Comment by Smorvel** [comment]
@Alex-302 Бету? Ну ок.. Поставил бету, блокировка заработала.. Почему так? изначально оно вроде как и на стабильной блокировало...

**Comment by Alex-302** [comment]
Ладно, заменил работающим везде вариантом.
