### ISSUE TITLE
allboxing.ru/boxing-news - Ads leftover

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5296]
***Description***:
* **Current behaviour**: 

There are ads on http://allboxing.ru/boxing-news.html 
Reproduced on our side.

<details><summary>Screenshot:</summary>

![screen shot 2017-06-10 at 10 40 49 am](https://user-images.githubusercontent.com/28784344/27001062-5b5f2232-4dc9-11e7-983d-bcda941cf949.png)

</details>

****Steps to reproduce the problem***:
Go on http://allboxing.ru/boxing-news.html 

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Adguard version: | 2.9.70
Adguard mode (Android): | Proxy(manual)
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard DNS: | None 
Adguard filters: | 2, 3, 4, 1, 11
Ticket ID (if exists): | 1094129

**Comment by Alex-302** [comment]
Fixed
