### ISSUE TITLE
Obsolete share rules

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#52975]
```
gecce.com,gecce.com.tr###contentLeft > .paylasim
m.gecce.com.m.gecce.com.tr###ctl00_bodycontent_paylasim

```
https://github.com/AdguardTeam/AdguardFilters/issues/23273

---

`||tazemp3indir.com/popmajor/mp3_indir_v*.gif`
https://forum.adguard.com/index.php?threads/resolved-http-www-tazemp3indir-com.25723/#post-155249

---

`board-tr.nitrado.net##.largeButtons > .like`
https://forum.adguard.com/index.php?threads/resolved-http-board-tr-nitrado-net.19118/#post-124657
The rule seems to be working, but there is no share button on the site.

---
`amkspor.sozcu.com.tr##.in_social`
https://forum.adguard.com/index.php?threads/resolved-5-websites.12089/#post-92190

---

```
erdalsarizeybek.com.tr##.haber-paylas_ha
erdalsarizeybek.com.tr##.haber-paylasim
```
https://forum.adguard.com/index.php?threads/resolved-erdalsarizeybek-com-tr.13106/#post-98490

---

`heymp3.com##.indirPaylas`
https://github.com/AdguardTeam/AdguardFilters/issues/11297

---

`yurtgazetesi.com.tr##.hbr-shr`
https://forum.adguard.com/index.php?threads/resolved-yurtgazetesi-com-tr.17930/

---

`yurtgazetesi.com.tr##.hh-socialmedia`
https://forum.adguard.com/index.php?threads/resolved-missed-social-media-buttons-sites-that-i-use.891/#post-26692

---

`mavikocaeli.com.tr##.hbr-shr`
https://forum.adguard.com/index.php?threads/resolved-mavikocaeli-com-tr.16367/#post-114750

---

`||anamurekspres.com/img/share-$image`
https://forum.adguard.com/index.php?threads/resolved-5-websites-5.12843/#post-96635

---

`||edirnehaber.org/images/paylas.jpg`
https://github.com/AdguardTeam/AdguardFilters/issues/8759

---

```
cayyolu.com.tr#?##page_right div.right_block[-ext-has="div.title.grey:contains(Sosyal Medya)"]
cayyolu.com.tr##.socialRightBlock
```
https://forum.adguard.com/index.php?threads/resolved-5-websites-social-residuals.16567/#post-114740

---

`sesgazetesi.com.tr##div[class^="fix-share-"]`
https://forum.adguard.com/index.php?threads/resolved-sesgazetesi-com-tr.20878/#post-133614

---

`cumhuriyet.com.tr###hdrFBLike`
https://forum.adguard.com/index.php?threads/resolved-cumhuriyet-com-tr.16259/#post-113295

---

```
||oyunindir.club/indirg.png
||oyunindir.club/green.gif
```
https://forum.adguard.com/index.php?threads/resolved-http-www-oyunindir-club.27037/#post-160822

---

`sanliurfa.net##img[alt="facebook-paylas"]`
https://forum.adguard.com/index.php?threads/resolved-6-websites-social.12839/#post-96615

---

`gunaydingazetesi.com.tr##img[alt="facebook-paylas"]`
https://forum.adguard.com/index.php?threads/resolved-5-websites-2.12836/#post-96587

---

```
dunyabulteni.net###share
dunyabulteni.net##.jssocials
```
https://forum.adguard.com/index.php?threads/resolved-dunyabulteni-net.13004/#post-97381

---

```
dizifilm.com##.share-area
dizifilm.com##.thim-sc-social-links
```
https://forum.adguard.com/index.php?threads/resolved-http-www-dizifilm-com-incorrect-blocking.25057/#post-151984

---

`fullhdfilmizlesene.org##div[class$="sosyal"]`
https://forum.adguard.com/index.php?threads/resolved-fullhdfilmizlesene-org.12731/#post-96418

---

`tosunkaya.com##.td_block_social_counter + div.td_block_text_with_title`

---

`donanimhaber.com##body header.tuttur.detayda .header-paylasim`

**Comment by Alex-302** [comment]
Done.
