### ISSUE TITLE
www.oncoforum.ru - Missed ad 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5299]
http://www.oncoforum.ru/blog/posts/tishka_1983/a-svolochi-khot-inogda-boleyut-rakom/

<details><summary>Screenshot:</summary>

![screen shot 2017-06-10 at 9 22 09 pm](https://user-images.githubusercontent.com/27292111/27005269-77f71c56-4e23-11e7-9d1b-2ea362542dc2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome 
Adguard version: | 6.2 / 1.4.1
Adguard driver (Windows): | WFP  
Adguard filters: | 1 2 3 4 5 14

Ticket ID:  642749

**Comment by Alex-302** [comment]
fixed
