### ISSUE TITLE
missed ad https://play.google.com/store/apps/details?id=com.creditcardcurrencyexchange

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5301]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

missed ad https://play.google.com/store/apps/details?id=com.creditcardcurrencyexchange
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/25711093/27012703-ed4198f0-4edd-11e7-8a90-025e869ebb6b.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On 
Adguard filters: | 2, 3, 4, 14, 7, 11, 104, 211
Ticket ID (if exists): | 972462

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
got the logs:
[state.txt](https://github.com/AdguardTeam/AdguardFilters/files/1066586/state.txt)
[debug (33).txt](https://github.com/AdguardTeam/AdguardFilters/files/1066587/debug.33.txt)

**Comment by Alex-302** [comment]
Ads are blocked
![image](https://user-images.githubusercontent.com/8361299/27036372-5208ce3e-4f8d-11e7-96bf-c40ab92e2b8a.png)
http://imagizer.imageshack.com/img924/2876/IrwebF.png
`ads=1` it means `blocked'

**Comment by Michael23456** [comment]
forwarded to the customer
