### ISSUE TITLE
missed ad http://news-fort.com/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5302]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

missed ad http://news-fort.com

<details>

![image](https://user-images.githubusercontent.com/25711093/27013789-7552d0be-4ef3-11e7-86c9-3e7cb0378969.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | eng, rus, experimental, spyware, social, annoyance, mobile
Ticket ID (if exists): | 1472975

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
