### ISSUE TITLE
fmovies.to - incorrect blocking 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5303]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 9anime.to and fmovies.to - Adguard prevents videos on these websites from loading 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/23372054/27014714-a6ee0f04-4f06-11e7-8c6c-f48d8c4c846e.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Application version: 1.2.1.75
Device: iPhone
Platform: iOS
OS: 10.3.2
imazed enabled: NO
Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.21.8 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.69 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.30 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.90 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.71 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.47 Enabled=YES
ID=101 Name="EasyList" Version=1.0.72.45 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.81.70 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=NO
ID=208 Name="Malware Domains" Version=1.0.81.55 Enabled=NO

Ticket ID 1572856

**Comment by Alex-302** [comment]
Please check
```
@@||mycloud.to/resources/css/style.css
@@|blob:https://fmovies.to/
@@||ajax.googleapis.com/ajax/libs/jquery/*/jquery.min.js
@@//mycloud.to/resources/js/player.js
@@||mycloud.to/resources/player/jwplayer-*/jwplayer.js
```

**Comment by ProfTimeLord** [comment]
This worked perfectly. However, the Openload videos on the page don't play when the play button is tapped.

**Comment by Alex-302** [comment]
@ProfTimeLord the Openload videos are not working on my side without ad blocker. 
Please check without Adguard.

**Comment by ProfTimeLord** [comment]
As soon as I disable Adguard the Openload videos play fine.

**Comment by Alex-302** [comment]
@ProfTimeLord please check the rules for 9anime.to
```
@@||apis.google.com/js/api.js$domain=9anime.to
@@||googlevideo.com/videoplayback?$domain=9anime.to
@@||blogspot.com^$~image,domain=9anime.to
```
for fmovies.is
```
fmovies.is,mycloud.to###jwa[style^="width: 300px; height: 250px;"]
@@||mycloud.to/resources/css/
@@||ajax.googleapis.com/ajax/libs/jquery/*/jquery.min.js
@@//mycloud.to/resources/js/player.js
@@//mycloud.to/resources/player/jwplayer-*/jwplayer.js
```

> as I disable Adguard the Openload videos play fine

Is DNS filtering enabled? Openload does not work on my side in any case.

**Comment by ProfTimeLord** [comment]
Openload is fine on 9anime.to, it's just that the Openload videos refuse to play on fmovies only. I tried the code for fmvoies but Openload still refuses to play once selected. I've only got the normal version of Adguard for ios so I don't have DNS enabled. Thanks for your help so far in any case

**Comment by Alex-302** [comment]
@ProfTimeLord Openload is not used on 9anime.to. Btw it is not working in this site on my device even with US VPN without Adguard.

**Comment by ProfTimeLord** [comment]
That's weird Openload shows on 9anime.to on my iPhone as an available server. Back to fmovies though, is there anything that can be done to let the Openload videos play without interference from Adguard, the site definitely works, as I've tried playing the Openload videos from fmovies on my computer and they play perfectly. Thanks again

**Comment by Alex-302** [comment]
@ProfTimeLord please check for updates. Both sites are working on my iPad, even openload player.

**Comment by ProfTimeLord** [comment]
I've updated the filters in Adguard but the problem with Openload on fmovies still persists with Adguard enabled. I've tried to upload a screen shot to show what happens on my side. Thanks
![img_0658](https://user-images.githubusercontent.com/29379613/27132745-e58933a8-5107-11e7-8dd6-9dde31a1c2db.PNG)

**Comment by Alex-302** [comment]
Is it possible to tap on the play button?

**Comment by ProfTimeLord** [comment]
The above screen shot is what happens when I tap play. If I continue to tap the play button nothing happens, the video just won't start.

**Comment by Alex-302** [comment]
Please try to leave only these filters:
```
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.21.8 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.69 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.30 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.90 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.71 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.47 Enabled=YES
```

**Comment by ProfTimeLord** [comment]
I've tried using only those filters, however the video still won't play.

**Comment by Alex-302** [comment]
Please check with English filter only.
Do you have Mac OS device?

**Comment by ProfTimeLord** [comment]
Even with just the English filter enabled the video doesn't play. As for a computer I only have Windows 10.

**Comment by Alex-302** [comment]
Sadly. Only in Mac OS I can look for blocked requests.
@zebrum please check this site on iphone.

**Comment by zebrum** [comment]
@Alex-302 reproduced.
play button is not active.

**Comment by Alex-302** [comment]
Please try
```
@@||fmovies.to^$domain=fmovies.to
```

**Comment by ProfTimeLord** [comment]
Still won't play.

**Comment by Alex-302** [comment]
@ProfTimeLord 
It is invalid. Try this
```
@@||fmovies.is^$domain=fmovies.is
```

**Comment by ProfTimeLord** [comment]
Still won't play I'm afraid.

**Comment by Alex-302** [comment]
@zebrum I need remote access to Mac with connected iPhone. Could you provide it?

**Comment by ProfTimeLord** [comment]
Any progress?

**Comment by Alex-302** [comment]
It works on my iPad with Adguard. But not working is Safari for MacOS without Adguard.
What about remote access to Mac with connected iPhone?
Is Safari filter enabled?

**Comment by ProfTimeLord** [comment]
The Safari filter is enabled, although I have noticed recently on some openload videos on fmovies that rather than there being an unresponsive play button. Certain videos instead are just replaced with the word reload in purple writing and that is also unresponsive. 
As for remote access I still don't have a Mac I'm afraid.

**Comment by Alex-302** [comment]
@ProfTimeLord please try to disable all filters, except English and Safari.

**Comment by ProfTimeLord** [comment]
Still refuses to play.

**Comment by Alex-302** [comment]
I don't know what is blocked. I can fix it only with MacOS with connected iphone:(

**Comment by ProfTimeLord** [comment]
Is no one else able to provide that kind of access?

**Comment by Alex-302** [comment]
No:( I will try to find.

**Comment by ProfTimeLord** [comment]
Thanks

**Comment by Alex-302** [comment]
Please check this rule:
```
@@google^$domain=fmovies.is
```
Is fmovies.is still actual domain?

**Comment by ProfTimeLord** [comment]
Yes, that is still the domain. Still won't play though.

**Comment by Alex-302** [comment]
@ProfTimeLord 
please check:
```
@@||openload.co/assets/$domain=fmovies.is
@@||cdnjs.cloudflare.com/ajax/libs/$domain=fmovies.is
@@||vid.springserve.com/vast/$domain=fmovies.is
@@||mycloud.to/resources/$domain=fmovies.is
@@||ajax.googleapis.com/ajax/libs/jquery/$domain=fmovies.is
```

**Comment by ProfTimeLord** [comment]
It's finally fixed, thank you so much for all your help. I really appreciate it.

**Comment by Alex-302** [comment]
ok.
