### ISSUE TITLE
https://выкса.рф/ - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5304]
https://выкса.рф/
<details><summary>Screenshot:</summary>

![screen shot 2017-06-12 at 9 40 31 am](https://user-images.githubusercontent.com/27292111/27021855-b6295486-4f53-11e7-8a29-43adcfcda8cb.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.2 / 1.4.1
Adguard driver (Windows): | WFP 
Adguard filters: | 1 2 3 4 14
 
Ticket ID: 1241781

**Comment by Alex-302** [comment]
fixed
