### ISSUE TITLE
schlaukopf.de - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5305]
***Site***: https://www.schlaukopf.de/
***Description***: Smartbanner at the top. Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27031626-50f202ac-4f71-11e7-9368-621df3f7d079.png)

![image](https://user-images.githubusercontent.com/10995998/27031645-629dec0a-4f71-11e7-9948-57219e19dc9b.png)

![image](https://user-images.githubusercontent.com/10995998/27031706-9eea3678-4f71-11e7-87ff-7b9b49279a12.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.32
Spyware filter | 1.0.12.70
Social media filter | 1.0.20.34
Annoyances filter | 1.0.13.92
German filter | 1.0.34.82
Mobile ads filter | 1.0.8.71
Safari filter | 1.0.3.47

**Comment by AdamWr** [comment]
Fixed.
