### ISSUE TITLE
foodspring.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5306]
***Site***: https://www.foodspring.de/
***Description***: Cookie notice leftover. Newsletter form.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27031752-d858a1e2-4f71-11e7-8d21-19d3ed4a346e.png)

![image](https://user-images.githubusercontent.com/10995998/27031761-e61f1dec-4f71-11e7-8dec-201c9aad2405.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.32
Spyware filter | 1.0.12.70
Social media filter | 1.0.20.34
Annoyances filter | 1.0.13.92
German filter | 1.0.34.82
Mobile ads filter | 1.0.8.71
Safari filter | 1.0.3.47

**Comment by AdamWr** [comment]
Fixed.
