### ISSUE TITLE
online-lernen.levrai.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5307]
***Site***: http://www.online-lernen.levrai.de/deutsch_grammatik_uebungen_klasse_5_6_7.htm
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27031935-a17e23d0-4f72-11e7-80d0-b3d0d08c0c3c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.32
Spyware filter | 1.0.12.70
Social media filter | 1.0.20.34
Annoyances filter | 1.0.13.92
German filter | 1.0.34.82
Mobile ads filter | 1.0.8.71
Safari filter | 1.0.3.47

**Comment by AdamWr** [comment]
Fixed.
