### ISSUE TITLE
General rule request.

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#53077]
@Alex-302 

This is a commonly used  news site theme in Turkey.
<details><summary>Screenshot:</summary>

![tema](https://user-images.githubusercontent.com/34379403/78616132-1150b080-787c-11ea-8771-cba31724d603.png)

</details>

The sites below are other news sites using this theme. Total 56. All of them have a share button.

<details><summary>Websites:</summary>

`antalyahurses.com,arhavipostasi.com,buyukizmir.com,cayyolu.com.tr,denizgazete.com,egedebirgun.com,ekonomidunya.com,elazighakimiyethaber.com,gastepress.com,gercekhaberci.com,haberkurulu.com,haberturizm.com,hellohayat.com,kanalege.com.tr,kaptanhaber.com,marasnews.com,obmhaber.com,oncusehir.com,tokathaber.com.tr,turgutlupostasi.com,turizmnews.com,uretenankara.com,yeniakcakocahaber.com,afyonyerelbasin.com,gunaydingazetesi.com.tr,sanliurfagazetesi.com,yenikaramangazetesi.com,gebzeyenigun.com,sakaryakent.com,imaret.com.tr,turizm24.net,ardahanhaber.com.tr,egemetropolgazetesi.com,ucnoktacom.com,tuketicipostasi.com,rehbercanakkale.com,kurtulusgazetesi.com.tr,anadoludanmesaj.com,turkinfo.nl,samsunkulishaber.com,gazetedemokrat.com,habercuk.com,haber-sanliurfa.com,basinburosu.com,gazetemizmir.com,kulishaber.com.tr,konyaaktuel.com.tr,spilhaber.com,ilerigazetem.com,gunedogushaber.com,bakirkoygazetesi.com,aksehirpostasi.com,turkiyehaberajansi.com,mizahdunyam.com,denizlikenthaber.com,menemenhaber.com.tr`

</details>

So can you create a general rule to block these buttons?
This works fine and can block all sharing buttons on the site. `##a[onclick^="ShareOn"]`

**Comment by Alex-302** [comment]
Ok.
