### ISSUE TITLE
investing.com - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5308]
***Site***: https://www.investing.com/
***Description***: Cookie notice at the bottom. Ad leftover on mobile.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27032063-560f236c-4f73-11e7-977e-7ab29ffd8c39.png)

![image](https://user-images.githubusercontent.com/10995998/27031976-e2bbbcb8-4f72-11e7-8658-8c993d2569fc.png)

![image](https://user-images.githubusercontent.com/10995998/27032013-058e79ec-4f73-11e7-9874-bd8b4a62a224.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.32
Spyware filter | 1.0.12.70
Social media filter | 1.0.20.34
Annoyances filter | 1.0.13.92
German filter | 1.0.34.82
Mobile ads filter | 1.0.8.71
Safari filter | 1.0.3.47

**Comment by AdamWr** [comment]
Fixed.
