### ISSUE TITLE
narcity.com - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5309]
***Site***: https://www.narcity.com/ca/bc/vancouver/travel/8-round-trip-flights-from-vancouver-for-under-dollar500
***Description***: Ad leftovers. Social share bar at the bottom when scrolling down a bit (ios and android)

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27033397-6c4bd4d0-4f79-11e7-99a0-8dc4bc75fa83.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.32
Spyware filter | 1.0.12.70
Social media filter | 1.0.20.34
Annoyances filter | 1.0.13.92
German filter | 1.0.34.82
Mobile ads filter | 1.0.8.71
Safari filter | 1.0.3.47

**Comment by AdamWr** [comment]
Fixed.
