### ISSUE TITLE
zdnet.de - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5311]
***Site***: http://www.zdnet.de/88300673/iphone-8-das-intel-modem-und-die-apple-aktie/
***Description***: Ad leftover at the top (mobile). Newsletter box at the right side (desktop).

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27038309-e30a8380-4f8a-11e7-9389-9ad34d519103.png)

![image](https://user-images.githubusercontent.com/10995998/27038354-015fd150-4f8b-11e7-85c2-b35c3d92c35f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.32
Spyware filter | 1.0.12.70
Social media filter | 1.0.20.34
Annoyances filter | 1.0.13.92
German filter | 1.0.34.82
Mobile ads filter | 1.0.8.71
Safari filter | 1.0.3.47

**Comment by AdamWr** [comment]
Fixed.
