### ISSUE TITLE
morgenweb.de - Social widgets - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5312]
***Site***: https://www.morgenweb.de/
***Description***: Ad leftover and social share buttons.

<details>
<summary>Screenshot</summary>

**Ad leftover at the top and below header:**

![image](https://user-images.githubusercontent.com/10995998/27038564-ad7b02ac-4f8b-11e7-85e5-84bf4baa21a6.png)

**Ad leftover in right sidebar:**

![image](https://user-images.githubusercontent.com/10995998/27038586-bbb4d028-4f8b-11e7-97c5-97843eff0b60.png)

**Social share buttons (https://www.morgenweb.de/mannheimer-morgen_artikel,-wirtschaft-zwischen-daten-nutzen-und-daten-schuetzen-_arid,1062381.html):**

![image](https://user-images.githubusercontent.com/10995998/27038707-080028ce-4f8c-11e7-98bf-30d2fcbfc5fd.png)

![image](https://user-images.githubusercontent.com/10995998/27038756-315154aa-4f8c-11e7-8e89-a18398d30cc0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.32
Spyware filter | 1.0.12.70
Social media filter | 1.0.20.34
Annoyances filter | 1.0.13.92
German filter | 1.0.34.82
Mobile ads filter | 1.0.8.71
Safari filter | 1.0.3.47

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr There is another ad leftover at the end of the page, must have missed that one... https://www.morgenweb.de/mannheimer-morgen_artikel,-wirtschaft-zwischen-daten-nutzen-und-daten-schuetzen-_arid,1062381.html:
![image](https://user-images.githubusercontent.com/10995998/27109704-ba76295e-50a4-11e7-9670-3a0289e14cd9.png)

**Comment by AdamWr** [comment]
Fixed.
