### ISSUE TITLE
zoom.us tracking

### ISSUE THREAD

**Issue by Tibladar** [AdguardTeam/AdguardFilters#53138]
**Description**:

`zoom.us` sends tracking data with an unique tracking id about website usage, e.g. which html items where clicked.

To reproduce, visit `zoom.us` and click on 'Join a meeting'.
On the current pageload (before changing to the clicked page) it sends the data to:
`​https://zoom.us/sendUserBehavior`

**Suggestion:** Block `https://zoom.us/sendUserBehavior`

**Filters:**

Information                            | Value
---                                    | ---
Browser:                               | Firefox 75.0
Filters enabled:                       | Spyware, Social media, Annoyances, English, German, EasyPrivacy, Fanboy's Enhanced Tracking List, AdGuard Tracking Protection

**Comment by Alex-302** [comment]
Not looks like user traking
![image](https://user-images.githubusercontent.com/8361299/78811251-3820fb00-79d2-11ea-8f12-3cb42a09b220.png)
Probably stats for developers only.

**Comment by Tibladar** [comment]
There's no exact boundary between stats for developers and user tracking.

I think it's tracking as it sends an event for many if not all link/button clicks whether the href is to the zoom site or an outgoing link and the name, `sendUserBehavior`, doesn't make it look like it's intended for pure developer stats.
All events also contain unique ids:

![](https://user-images.githubusercontent.com/52620063/78822184-29cee100-79ca-11ea-8779-78c96d52797c.png)

**Comment by Alex-302** [comment]
Please look on other first-party requests - they are have the same cookies.
Probably it used to catch errors on the site.

**Comment by Tibladar** [comment]
I know about the cookies, but I think it's the combination of all things.

If you don't agree, feel free to close this issue.

**Comment by Alex-302** [comment]
Ok.
