### ISSUE TITLE
Remove redundant rules in Tracking and Social filters

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#53130]
### Tracking Protection
`||google-analytics.com^$domain=avgle.com`
`||google-analytics.com/__utm.gif`
`||google-analytics.com/analytics.js`
`||google-analytics.com/analytics.js$third-party`
`||google-analytics.com/collect`
`||google-analytics.com/collect$third-party`
`||google-analytics.com/cx/api.js`
`||google-analytics.com/cx/api.js$third-party`
`||google-analytics.com/ga.js`
`||google-analytics.com/ga_exp.js`
`||google-analytics.com/ga_exp.js$third-party`
`||google-analytics.com/plugins/`
`||google-analytics.com/plugins/$third-party`
`||google-analytics.com/r/collect^`
`||google-analytics.com/r/collect^$third-party`
`||google-analytics.com/siteopt.js?`
`||google-analytics.com/siteopt.js?$third-party`
`||google-analytics.com/urchin.js$third-party`
`||google-analytics.com^*/__utm.gif`
`||google-analytics.com^$domain=avgle.com`
are redundant by
`||google-analytics.com^`
(two entries for $domain=avgle.com is not a typo)

`||2o7.net^$third-party`
`||demdex.net^$third-party`
are redundant by
`||2o7.net^`
`||demdex.net^`

`||walgreens.sc.omtrdc.net^`
`||olympiaverlag.sc.omtrdc.net/b/ss/`
`||aftonbladetnya.sc.omtrdc.net^`
`||carfax.sc.omtrdc.net^`
`||dsg.sc.omtrdc.net^`
are redundant by
`||omtrdc.net^`

`||unacademy.com/googleAnalytics.js`
`||turizm.fins.az/themes/turizm/js/googleanalytics.js`
are redundant by
`/googleanalytics.js`

`.cloudfront.net/atrk.js$third-party`
is redundant by
`/atrk.js`

### Social madia
`gamestar.de###socialshare`
`mk.ru###vk_groups2`
`mobile.reuters.com##.amp-social-container`
`m.sports.ru##.b-social-buttons`
`therichest.com##.article_share`
`tehno-rating.ru##.fshare`
`firetv-blog.de##.sparkling-social`
`track24.ru##.b-share`
`xda-developers-forum.blogspot.com##.post-share-buttons`
`m.kmib.co.kr##.article_sns`
`kinopoisk.ru##.ya-share2`
`vsemirnyjbank.org,worldbank.org,bancomundial.org,albankaldawli.org,shihang.org,banquemondiale.org##.social-btn`
`jbzd.com.pl##.facebook-share`
`filmweb.pl##.fb-share-button`
`komputerswiat.pl,onet.pl##.fb_share`
are redundant by
`###socialshare`
`###vk_groups2`
`##.amp-social-container`
`##.b-social-buttons`
`##.article_share`
`##.fshare`
`##.sparkling-social`
`##.b-share`
`##.post-share-buttons`
`##.article_sns`
`##.ya-share2`
`~learnathome.ru,~hackerrank.com,~prezi.com##.social-btn`
`~stylebook.de##.facebook-share`
`##.fb-share-button`
`##.fb_share`

`delo.ua##.sharer`
`egy.best##.sharer`
`aspor.com.tr,ign.com##.sharer`
are redundant by
`##.sharer`

`pcmag.com###share_container`
`extremetech.com###share_container`
are redundant by
`###share_container`

`meleke.com##.post-social-goog`
`meleke.com##.post-social-pin`
are redundant by
`##.post-social-goog`
`##.post-social-pin`

**Comment by Alex-302** [comment]
Social rules are not redundant. They are for $generichide exclusions.

**Comment by Yuki2718** [comment]
> 
> 
> Social rules are not redundant. They are for $generichide exclusions.

Okay, thanks for clarifying.
