### ISSUE TITLE
Anti ad-blocker on: http://jilhub.xyz

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5314]
***Description***:
* **Current behaviour**: 

http://jilhub.xyz detects adblocking and prevents the user from seeing
anything.

![screen shot 2017-06-12 at 6 50 27 pm](https://user-images.githubusercontent.com/27874000/27042739-8cebfc52-4fa0-11e7-9001-47719121b1ff.png)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Google Chrome
Adguard version: | 1.4.1
Adguard filters: | English, Spyware, Social media, Annoyances, Russian
Ticket ID: | 1573765

**Comment by Alex-302** [comment]
fixed
