### ISSUE TITLE
poe.trade - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5315]
***Site***: http://poe.trade/
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27043074-3db98462-4f99-11e7-8903-8380cc5c5c8e.png)

**http://poe.trade/search/inarinarerihio:**

![image](https://user-images.githubusercontent.com/10995998/27043138-73381ed2-4f99-11e7-9337-ffd2758ecdc1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.35
Spyware filter | 1.0.12.70
Social media filter | 1.0.20.35
Annoyances filter | 1.0.13.94
German filter | 1.0.34.84
Mobile ads filter | 1.0.8.72
Safari filter | 1.0.3.47

**Comment by AdamWr** [comment]
Fixed.
