### ISSUE TITLE
giveawayoftheday.com - Ad leftover - Annoyance - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5316]
***Site***: https://de.giveawayoftheday.com/
***Description***: Ad leftover. Newsletter box. App ad at the bottom (mobile).

<details>
<summary>Screenshot</summary>

**Ad leftover:**

![image](https://user-images.githubusercontent.com/10995998/27043275-d6b5f8f8-4f99-11e7-9d08-695d859661cf.png)

**Newsletter box:**

![image](https://user-images.githubusercontent.com/10995998/27043282-dfb5e148-4f99-11e7-8e8e-97876f123450.png)

**Ad leftover and app ad at the bottom (https://iphone.giveawayoftheday.com/brutal-labyrinth-gold-2/?lang=de):**

![image](https://user-images.githubusercontent.com/10995998/27043425-6a1cacae-4f9a-11e7-8acc-57f2ca9b5322.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.35
Spyware filter | 1.0.12.70
Social media filter | 1.0.20.35
Annoyances filter | 1.0.13.94
German filter | 1.0.34.84
Mobile ads filter | 1.0.8.72
Safari filter | 1.0.3.47

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr Newsletter form still there and ad banner on mobile:

![image](https://user-images.githubusercontent.com/10995998/27378535-80c8ed02-5678-11e7-998f-ea2f36bd264f.png)

![image](https://user-images.githubusercontent.com/10995998/27378635-d6c3ec8e-5678-11e7-92f5-cf62cc2c76d6.png)


*Rules:*
```
giveawayoftheday.com##.subscribe_block
giveawayoftheday.com##.bottom_b
```

**Comment by AdamWr** [comment]
It's look like they changed class name of this newsletter, because when I was checking this, it was a `wrap_subscrb`.
I can not reproduce this ad banner, but I will add rule which you provided.
Thank you.
