### ISSUE TITLE
||mangachan.me/clk.js 

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#53167]
This rule seems to be in the wrong filter.

https://github.com/AdguardTeam/AdguardFilters/blob/490103e305406a5a1df61972591334871b2d67ef/TurkishFilter/sections/specific.txt#L3677

https://forum.adguard.com/index.php?threads/%D0%A0%D0%B5%D1%88%D0%B5%D0%BD%D0%BE-mangachan-me-%D0%B8-%D1%80%D0%B5%D0%BA%D0%BB%D0%B0%D0%BC%D0%B0.11134/#post-86869

**Comment by zloyden** [comment]
Does this domain `mangachan.me` work at your end?

**Comment by PentagramTr** [comment]
It seems not to working
<details><summary>Screenshot:</summary>

![Adsız](https://user-images.githubusercontent.com/34379403/78816883-006a8100-79db-11ea-9593-81d97d5f0c47.png)


</details>

**Comment by zloyden** [comment]
I removed rules for this dead domain.
