### ISSUE TITLE
Пропущенная реклама в myscore

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#5317]
Буду краток. Фильтры по-умолчанию, Фильтрация качественная, HTTP вкл, HTTPS вкл, версия приложения adguard последняя,  Android 4.4.4, приложение myscore 
20:45 июнь 12 число http://my-files.ru/6zhfq7

**Comment by ministr91** [comment]
![screenshot_2017-06-12-20-45-33](https://user-images.githubusercontent.com/22351242/27047476-eeb13e06-4fb0-11e7-8a58-350e4d48c2ca.png)

**Comment by Alex-302** [comment]
что такое myscore - приложение или сайт?

**Comment by ministr91** [comment]
Приложение
https://play.google.com/store/apps/details?id=eu.livesport.MyScore_ru

**Comment by Alex-302** [comment]
У меня не появляется. В логе, смотрю, рекламный домен Яндексане заблокирован.
Сколько нужно ждать до появления рекламы, и что происходит при нажатии на баннер и на крест?

**Comment by ministr91** [comment]
Сразу у меня появляется. Нажимаю и переходит на сайт рекламный. Нажимаю на крест, появляется выбор - пожаловаться на объявление и т.д. Эта реклама от Яндекс директ. Нажал на знак рекламы слева и перешел на сайт Яндекс директ

**Comment by ministr91** [comment]
Я же логи прикрепил, по ним никак нельзя увидеть проблему?

**Comment by Alex-302** [comment]
Можно. Выше написал же:
> В логе, смотрю, рекламный домен Яндекса не заблокирован.

Проверь 
```
||an.yandex.ru^$app=eu.livesport.MyScore_ru
```

**Comment by ministr91** [comment]
Пока сказать не могу. До применения выше команды, которую ты скинул, я нажал на крестик, выбрал не показывать больше и объявление исчезло

**Comment by Alex-302** [comment]
А сбрось данные приложения, если там ничего ценного, или останови и очисти кэш.

**Comment by ministr91** [comment]
Уже делал так. Удалял и снова ставил - пока нет рекламы. Если появится, то я попробую твой код сверху и напишу как прошло

**Comment by ministr91** [comment]
Снова появилась

**Comment by ministr91** [comment]
Пока что твое новое правило работает, это объявление с арматурой не появилось. Странно, но если и есть реклама, то почему-то эта арматура, никакой другой.

**Comment by ministr91** [comment]
Я ошибся, твое правило не работает, опять эта реклама с арматурой. Есть варианты? Как я понял, появляется эта реклама не сразу, нужно минут 5 попользоваться  приложением, ну или включить, выбрать какой-нибудь матч, потом свернуть, подождать минут 5 и далее опять войти. Вот тогда реклама активируется. Есть еще варианты решения?

**Comment by Alex-302** [comment]
> никакой другой.

может встроена? Но тогда не понятно, почему у меня не отображается. Выключаю фильтрацию - появляется только фейсбучная реклама.

> Есть еще варианты решения?

Наверное только в AdguardForAndroid писать.

**Comment by ministr91** [comment]
Может еще что-нибудь придумаешь? Давай кого-нибудь позовем на помощь

**Comment by ministr91** [comment]
@ameshkov @vozersky @evgeniy-ADG @nkartyshov @Revertron @zebrum @altokarev @atropnikov @Bohdan-SUP @confessor-adguard @hmage @mmigi @sfionov @Stillness-2 @suhan3z @vbagirov помогайте, проблема серьезная

**Comment by Alex-302** [comment]
Ну всех-то зачем?

**Comment by ministr91** [comment]
Чтобы наверняка хоть кто-нибудь пришел, да и проблема быстрее решится :)

**Comment by ameshkov** [comment]
Так это, парни, приложение в списке исключений по умолчанию (потому что оно раньше крашилось от блокировки рекламы).

Убрал его и еще убрал вот такое: `eu.livesport.FlashScore_com` (Лех, можешь посмотреть не крашится ли оно?)

@ministr91 нужно в настройках приложений включить блокировку рекламы для этого приложения вручную.

**Comment by Alex-302** [comment]
глянем сейчас

**Comment by ministr91** [comment]
@ameshkov сейчас вроде все работает, рекламы нет, приложение не крашится

**Comment by ministr91** [comment]
Ты же потом добавишь в новую версию автоматически блок реламы, чтобы не пришлось вручную добавлять его в список исключений?

**Comment by ministr91** [comment]
Создашь отдельную тему, чтобы не забыть?

**Comment by Alex-302** [comment]
Проверил, оба не крашатся.

**Comment by ministr91** [comment]
Ну так что, сделаете это в автоматическом режиме, чтобы не пришлось самому вносить в список?

**Comment by ameshkov** [comment]
Да, уже сделали, но это только в следующем обновлении. Список исключений вшит в программу.
