### ISSUE TITLE
tnaflix.com

### ISSUE THREAD

**Issue by kulfoon** [AdguardTeam/AdguardFilters#53187]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Breakage - video not playing + related videos section (below the video) not loading,
a filter which causes it from AdGuard Base Filter: `tnaflix.com##+js(addEventListener-defuser, getexoloader)`

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>NSFW Screenshot:</summary>

![111](https://user-images.githubusercontent.com/43844449/78771234-26b6ff00-7990-11ea-8a9b-2b1bc221ed58.gif)

</details><br/>

* **Expected behaviour**: 

Video should play + related videos section (below the video) should load

<details><summary>NSFW Screenshot:</summary>

![222](https://user-images.githubusercontent.com/43844449/78771245-2ae31c80-7990-11ea-85af-07f386916fdb.gif)

</details><br/>

***Steps to reproduce the problem***:

Visit the website and try to play any video, example url: 
`https://www.tnaflix.com/hd-videos/Anal-babe-gets-eaten-out/video3279946?isFeatured=1`

***System configuration***

**Filters:**

uBO default + AdGuard Base filter

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 7 SP1 64bit
Browser:                               | Firefox 75 64bit / Opera 67 64bit
AdGuard version:                       | uBlock Origin 1.26.1b3

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
Thank you.
