### ISSUE TITLE
YouTube - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5318]
***Site***: https://www.youtube.com/watch?v=g-XpPPMJlUQ
***Description***: Rule `||youtube.com/annotations_invideo?$object-subrequest` in Annoyance filter does block usefull elements like the info card (only visible while video is paused anyway) which aren't even annoying in my opinion.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27080020-645ad3e0-503a-11e7-9898-d3e8f30e7273.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.42
Spyware filter | 1.0.12.73
Social media filter | 1.0.20.38
Annoyances filter | 1.0.13.98
German filter | 1.0.34.85
Mobile ads filter | 1.0.8.72
Safari filter | 1.0.3.48

**Comment by Alex-302** [comment]
We will not unblock it.

**Comment by danidoedel** [comment]
@Alex-302 Could you please explain why then?

**Comment by Alex-302** [comment]
Because it is expected result. If you want to see it, disable the rule or filter.

**Comment by danidoedel** [comment]
That‘s not an explanation though. Why is blocking usefull elements an expected behavior?

**Comment by Alex-302** [comment]
It is just annotation, like at the bottom of some videos.
