### ISSUE TITLE
lingolia.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5319]
***Site***: https://deutsch.lingolia.com/de/
***Description***: Ad leftover.

*Rule:*
```
lingolia.com##.adv-header
```

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27080585-e3e16d3e-503c-11e7-8409-6e4786c8f8a1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.42
Spyware filter | 1.0.12.73
Social media filter | 1.0.20.38
Annoyances filter | 1.0.13.98
German filter | 1.0.34.85
Mobile ads filter | 1.0.8.72
Safari filter | 1.0.3.48

**Comment by AdamWr** [comment]
Added.
