### ISSUE TITLE
insuedthueringen.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5320]
***Site***: http://www.insuedthueringen.de/
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27081787-549b5f94-5042-11e7-8c2f-5997431b0f8d.png)

![image](https://user-images.githubusercontent.com/10995998/27081820-78a4bfde-5042-11e7-825b-bc69a90fab18.png)

![image](https://user-images.githubusercontent.com/10995998/27081841-93d7a6ea-5042-11e7-9278-a38052229445.png)

![image](https://user-images.githubusercontent.com/10995998/27081781-46d04492-5042-11e7-8da7-38c3a582b091.png)

![image](https://user-images.githubusercontent.com/10995998/27081737-08df7a04-5042-11e7-9a1c-629f98e6f401.png)

**http://www.insuedthueringen.de/region/thueringen/thuefwthuedeu/Wir-koennen-die-Frau-nichts-mehr-fragen;art83467,5568826:**

![image](https://user-images.githubusercontent.com/10995998/27081752-1959d0d2-5042-11e7-98d0-f5c661e4c30e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.42
Spyware filter | 1.0.12.73
Social media filter | 1.0.20.38
Annoyances filter | 1.0.13.98
German filter | 1.0.34.85
Mobile ads filter | 1.0.8.72
Safari filter | 1.0.3.48

**Comment by AdamWr** [comment]
Fixed.
