### ISSUE TITLE
ficbook.net

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#53213]
<details><summary>Screenshots:</summary>

![Screenshot_20200408-163135](https://user-images.githubusercontent.com/63355514/78792150-7231d300-79b9-11ea-838a-faa916488588.jpg)
![Screenshot_20200408-162942](https://user-images.githubusercontent.com/63355514/78792156-73630000-79b9-11ea-99c8-6cb4277ad98e.jpg)
![Screenshot_20200408-162900](https://user-images.githubusercontent.com/63355514/78792160-74942d00-79b9-11ea-8876-44082888da7c.jpg)
![Screenshot_20200408-162742](https://user-images.githubusercontent.com/63355514/78792162-752cc380-79b9-11ea-8280-dc536efe15f5.jpg)
![Screenshot_20200408-162657](https://user-images.githubusercontent.com/63355514/78792170-75c55a00-79b9-11ea-8cc4-649c026c19f7.jpg)
![Screenshot_20200408-162621](https://user-images.githubusercontent.com/63355514/78792172-765df080-79b9-11ea-9378-db138d837cdf.jpg)
![Screenshot_20200408-162526](https://user-images.githubusercontent.com/63355514/78792175-76f68700-79b9-11ea-8b5a-33fdd3f56f1e.jpg)
![Screenshot_20200408-162424](https://user-images.githubusercontent.com/63355514/78792178-778f1d80-79b9-11ea-80a9-aa2fafe850df.jpg)
![Screenshot_20200408-162333](https://user-images.githubusercontent.com/63355514/78792180-7827b400-79b9-11ea-86e2-61e4e83b5c1c.jpg)
![Screenshot_20200408-162246](https://user-images.githubusercontent.com/63355514/78792181-7827b400-79b9-11ea-898c-05df64f76fb1.jpg)
![Screenshot_20200408-162203](https://user-images.githubusercontent.com/63355514/78792183-78c04a80-79b9-11ea-9da0-b42c7661b42e.jpg)
![Screenshot_20200408-162131](https://user-images.githubusercontent.com/63355514/78792186-7958e100-79b9-11ea-9ef2-f4197ff59397.jpg)
![20200408_150827](https://user-images.githubusercontent.com/63355514/78792188-79f17780-79b9-11ea-85d6-04cf3907758c.jpg)
![Screenshot_20200408-150628](https://user-images.githubusercontent.com/63355514/78792189-7a8a0e00-79b9-11ea-9617-cefb0aaa3fb7.jpg)
![Screenshot_20200408-150545](https://user-images.githubusercontent.com/63355514/78792193-7b22a480-79b9-11ea-87d5-01aa13963fa7.jpg)
</details><br/>

Эта реклама абсолютно везде!

**Comment by zloyden** [comment]
Поправил, но в следующий раз отправьте репорт из программы, поскольку там указывается вся необходимая информация. Обновление прилетит через 2-3 часа.
