### ISSUE TITLE
adshrink.it

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#53221]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

Blank page when i enable `AdGuard Base` filter in uBlock Origin
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

(blank page)
<img width="1004" alt="current" src="https://user-images.githubusercontent.com/48647394/78875585-680de400-7a4e-11ea-9d3e-121e89e3ea85.PNG">

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

<img width="1028" alt="Expected" src="https://user-images.githubusercontent.com/48647394/78875611-73610f80-7a4e-11ea-86a7-cef4c6695600.PNG">

</details><br/>

***Steps to reproduce the problem***:

1. go to `https://adshrink.it/5AP7F3`

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox 75
Adblocker:                       | uBlock Origin v1.26.0
Filters enabled:                       |  

    "user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-abuse",
    "ublock-unbreak",
    "adguard-generic",
    "easylist",
    "easyprivacy",
    "malware-0",
    "malware-1",
    "plowe-0",
    "DEU-0"

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Hi,
Fixed ad leftover, but I can't reproduce reported issue.
Please fill the template.

**Comment by JobcenterTycoon** [comment]
Same issue with fresh chrome browser too but when i whitelist `adshrink.it#@#+js(abort-current-inline-script, document.addEventListener, /, displayMessage:/)` the site works

**Comment by AdamWr** [comment]
Ok, so you are using uBlock Origin.
It seems that in case of uBlock Origin the problem is with comma in the last part `/, displayMessage:/`, I'm not sure if it's a bug or by design, but escaping or removing comma fixes that issue.
I excluded this rule from Base filter for uBO, update should be available in 1-2 hours.

**Comment by Nzzyme** [comment]
https://adshrink.it/mv1iT9

Adblock message seen on Firefox for Android. Checked with AG for Android.

**Comment by AdamWr** [comment]
>Adblock message seen on Firefox for Android. Checked with AG for Android.

Fixed, update should be available in 1-2 hours.
