### ISSUE TITLE
altapress.ru - Missed Ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5322]
http://altapress.ru/ 

<details><summary>Screenshot:</summary>

![screen shot 2017-06-13 at 4 52 32 pm](https://user-images.githubusercontent.com/27292111/27085784-fb1b1df8-5058-11e7-96c1-975a601cd7ab.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.2 / 1.4.1
Adguard driver (Windows): | WFP 
Adguard filters: | 1 2 3 4 14

Ticket ID: 1050032

**Comment by Alex-302** [comment]
Fixed

**Comment by moraks** [comment]
Новая реклама появилась, блокируется правилом: `altapress.ru##div#discountsCont`
<details> 
  <summary>Скрин</summary>

![123433](https://user-images.githubusercontent.com/20518047/48312749-1d343680-e5e6-11e8-9278-0b468c11ee75.jpg)

</details>

**Comment by Alex-302** [comment]
поправил
