### ISSUE TITLE
ria-m.tv - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5323]
http://ria-m.tv/news/91335/poroshenko_odobril_vajnyiy_zakon_ob_orujii.html

<details><summary>Screenshot:</summary>

![screen shot 2017-06-13 at 5 01 39 pm](https://user-images.githubusercontent.com/27292111/27086195-1810cd58-505a-11e7-9078-b08a29a4bc4f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome / Opera
Adguard version: | 6.2 / 1.4.1
Adguard driver (Windows): | WFP 
Adguard filters: | 1 2 3 4 14 
Ticket ID: | 1574215

**Comment by Alex-302** [comment]
Fixed
