### ISSUE TITLE
online-tech-tips.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#53264]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Advertisement placeholder

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/78887585-f3549d00-7a81-11ea-99da-ab105f2d7fbf.PNG)

</details><br/>

* **Expected behaviour**: 

It shouldn't be there.

<details><summary>Screenshot:</summary>

![2](https://user-images.githubusercontent.com/29574622/78887977-a3c2a100-7a82-11ea-8224-8887edb958ef.PNG)

</details><br/>

***Steps to reproduce the problem***:

Visit this link: https://www.online-tech-tips.com/computer-tips/how-to-optimize-the-paging-file-in-windows/

***System configuration***
Microsoft Edge Chromium Beta 81
**Filters:**

Adguard Base, AdGuard Mobile Ads, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 1909
Browser:                               | Microsoft Edge Chromium Beta 81
AdGuard version:                       | Adguard extension 3.4.15
Filters enabled:                       | Adguard Base, AdGuard Mobile Ads, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media
AdGuard mode (Android only):           |
Filtering quality (Android only):      | 
HTTPS filtering (Android only):        |
Simplified filters (iOS only)          | 
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | 
Helpdesk ID (if exists):               | 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
