### ISSUE TITLE
mouse-sensitivity.com - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5326]
***Site***: https://www.mouse-sensitivity.com/
***Description***: Ad leftover in right sidebar. Social widget leftover in footer.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27098507-1960f20a-5078-11e7-9adc-244f31e46cbd.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.51
Spyware filter | 1.0.12.74
Social media filter | 1.0.20.42
Annoyances filter | 1.0.14.3
German filter | 1.0.34.88
Mobile ads filter | 1.0.8.73
Safari filter | 1.0.3.48

**Comment by AdamWr** [comment]
Fixed.
