### ISSUE TITLE
Adguard blocker detected error

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#53278]
@Zarthes commented on [Thu Apr 09 2020](https://github.com/AdguardTeam/AdguardForiOS/issues/1541)

https://nxmac.com/

![4A9BC384-4E15-47A4-8988-34E18FCDFBEC](https://user-images.githubusercontent.com/56041562/78887930-69003f00-7a69-11ea-9b02-d4d8ce90d410.png)

---

@SoLenny commented on [Thu Apr 09 2020](https://github.com/AdguardTeam/AdguardForiOS/issues/1541#issuecomment-611476361)

@Zarthes Hello, I can't reproduce it on my side, any way you can try to enable Anti-Adblock killer (Settings -> Filters -> Annoyances).
If it won't help, please provide which filters do you use?

---

@Zarthes commented on [Thu Apr 09 2020](https://github.com/AdguardTeam/AdguardForiOS/issues/1541#issuecomment-611481598)

@SoLenny hello 
Ive activated Anti Adblock Killer as you suggested,but I still got the same error
Here on SS you can see the filter lists that I’m using on iOS,
Note: Adguard for Mac works without any problem

![50DBE78A-D433-4810-8932-E77828E3B9BB](https://user-images.githubusercontent.com/56041562/78891079-7d473a80-7a6f-11ea-9a60-b34fcb7a510a.png)

---

@SoLenny commented on [Thu Apr 09 2020](https://github.com/AdguardTeam/AdguardForiOS/issues/1541#issuecomment-611528352)

@Alex-302 have a look pls

**Comment by Alex-302** [comment]
@Zarthes I also cannot reproduce. Could you, please, try to disable-enable content blockers in Safari settings and reboot device?

**Comment by Yuki2718** [comment]
I can't reproduce either.

**Comment by Zarthes** [comment]
Dear @Alex-302 
Thank you for the tip, after disabling/Re enabling content blocker from Safari And manually updating filters from Adguard, the issue has gone,

**Comment by Alex-302** [comment]
Great.
