### ISSUE TITLE
k-zeitung.de - Ad leftover - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5327]
***Site***: http://www.k-zeitung.de/
***Description***: Ad leftover and ad in right sidebar.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27109275-13027896-50a2-11e7-9a4a-4603b965f972.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.51
Spyware filter | 1.0.12.74
Social media filter | 1.0.20.42
Annoyances filter | 1.0.14.3
German filter | 1.0.34.88
Mobile ads filter | 1.0.8.73
Safari filter | 1.0.3.48

**Comment by AdamWr** [comment]
Fixed.
