### ISSUE TITLE
pz-news.de - Social widget - Ad leftover - Annoyance - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5328]
***Site***: https://www.pz-news.de/
***Description***: Ad leftover at the top. Whatsapp newsletter box in right sidebar. Facebook widget leftover in right sidebar. Ad leftover in right sidebar. Poll in right sidebar is missing.

<details>
<summary>Screenshot</summary>

**Ad leftover at the top:**

![image](https://user-images.githubusercontent.com/10995998/27109321-6a66418a-50a2-11e7-9428-642df52ad863.png)

**Whatsapp newsletter box in right sidebar:**

![image](https://user-images.githubusercontent.com/10995998/27109333-7ac76d9c-50a2-11e7-9820-98a27a5d206e.png)

**Facebook widget leftover:**

![image](https://user-images.githubusercontent.com/10995998/27109389-d835dc8e-50a2-11e7-98ea-c44e77206bcd.png)

**Ad leftover:**

![image](https://user-images.githubusercontent.com/10995998/27109393-e78cc490-50a2-11e7-909b-a2abc31caf45.png)

**Ad leftover:**

![image](https://user-images.githubusercontent.com/10995998/27109423-131de47c-50a3-11e7-8e5e-4ea039c9b6b1.png)

**Poll in right sidebar is missing:**

![image](https://user-images.githubusercontent.com/10995998/27109464-520cf47a-50a3-11e7-89be-853c0bd5f9ed.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.51
Spyware filter | 1.0.12.74
Social media filter | 1.0.20.42
Annoyances filter | 1.0.14.3
German filter | 1.0.34.88
Mobile ads filter | 1.0.8.73
Safari filter | 1.0.3.48

**Comment by Alex-302** [comment]
fixed

**Comment by danidoedel** [comment]
@Alex-302 Poll in sidebar still missing.
