### ISSUE TITLE
https://udn.com - missed ad on page 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5329]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://udn.com/mobile/index - a grayish banner on the page 
reproduced even with vpn enabled 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/23372054/27120604-e8e7a1b2-50ec-11e7-8d62-7b06781f6dbd.png)

</details>

***System configuration***

Application version: 1.2.2.87
Device: iPhone
Platform: iOS
OS: 10.3.1

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.20.82 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.12.71 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.35 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.97 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.1.5 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.62 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.72 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.48 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.72 Enabled=YES
ID=101 Name="EasyList" Version=1.0.72.45 Enabled=NO
ID=118 Name="EasyPrivacy" Version=1.0.81.69 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.81.82 Enabled=NO
ID=207 Name="Adblock Warning Removal List" Version=1.0.81.86 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.3.13 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.81.74 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.83 Enabled=YES
ID=237 Name="AdBlock Protector List (Incompatible with Adguard)" Version=1.0.0.38 Enabled=NO

PRO:
Pro feature DISABLED.
System-Wide filtering DISABLED.

Ticket ID: 1574288

**Comment by Alex-302** [comment]
Fixed
