### ISSUE TITLE
Anti-AB script on free-torrents.org

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#5330]
"Block element" tool doesn't work on http://free-torrents.org/ 
Assistant is also being cut out.

`#%#Object.defineProperty(window, 'antiadblock', { get: function() { return; } });` seems to help

**Comment by zebrum** [comment]
seems that in safari it happens again

**Comment by zebrum** [comment]
check with browser extension, please

**Comment by Alex-302** [comment]
Works

**Comment by zebrum** [comment]
in safari on mac

**Comment by Alex-302** [comment]
Indeed.

<details>

![image](http://imagizer.imageshack.com/img922/5954/YpFTST.png)
</details>
