### ISSUE TITLE
yandex.ru/pogoda/

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#5332]

**Comment by Alex-302** [comment]
@Juev попробуйте такой вариант:
```
://yandex.ru/pogoda/cry/*^|$replace=/^Ya\[([0-9]{10\,15})\]\([\s\S]*\)\$/,important
yandex.ru$$div[wildcard="*//clck.yandex.*redir*data-bem*"][parent-elements="div"][parent-search-level="2"][max-length="30000"]
```

**Comment by Juev** [comment]
Забавно, добавляю в расширение фильтр, сохраняю изменения, закрываю настройки, открываю настройки, фильтра нет.

**Comment by Alex-302** [comment]
Изначально же речь о программе шла, а не про расширение. Эти правила не поддерживаются расширениями, только программа может с ними работать.
Вы какой продукт используете?

**Comment by Juev** [comment]
Да, вы правы. Установил приложение, активировал только ваши стандартные правила, убрав EasyList и иже с ними, что использовал ранее. На странице погоды мигание в хроме прекратилось и реклама не отображается. Правда при этом перестала работать карта. Описал проблему в письме.

**Comment by Alex-302** [comment]
на понял) С этими правилами карта перестала работать?

**Comment by Juev** [comment]
Нет, до ваших правил дело не дошло. Я лишь установил приложение повторно и по рекомендации ваших коллег оставил активными только ваши подписки, не добавляя ничего стороннего.

**Comment by Alex-302** [comment]
А браузер какой? Хром или Сафари? Если Сафари, то там нужно выключить расширение, т.к. в случае с Сафари оно не знает о наличии программы и тоже работает(в Хроме оно только как индикатор работы программы).
Попробуйте методом перебора найти фильтр(не правило), который ломает карту, а то у меня не повторяется.

**Comment by Juev** [comment]
Тестировал в Хроме, с него все проблемы начались. Каким образом можно найти фильтр, что ломает карту? Прикладываю логи ошибок из консоли Хрома.

[adguard_yandex.txt](https://github.com/AdguardTeam/AdguardFilters/files/1075527/adguard_yandex.txt)

**Comment by Alex-302** [comment]
> Каким образом можно найти фильтр

для начала выключите все и проверьте, что карта работает.
Затем по одному включайте с проверкой.

**Comment by Juev** [comment]
Отключил все фильтры, почистил кеши в хроме, но страница продолжает фильтроваться. В логах консоли все те же ошибки.

<img width="1034" alt="screen shot 2017-06-14 at 22 23 17" src="https://user-images.githubusercontent.com/114635/27148100-18cf3a6c-5150-11e7-8fdc-fa613a7fb645.png">

**Comment by Alex-302** [comment]
Так а с проблемой что? Ошибки в консоли могут быть ни при чём.

**Comment by Juev** [comment]
Проблема остается. И судя по всему я не смог отключить фильтры, я лишь снял галки с имен фильтров, но сами фильтры остались активными. И нет возможности отключить сразу все правила внутри фильтров, только по одному, а их слишком много для ручного перебора.

Попробовать удалять фильтры?

**Comment by Juev** [comment]
Удалил все фильтры, блокировка продолжается, я уже ничего не понимаю.

**Comment by Alex-302** [comment]
как вариант - можно удалить фильтры.
А по какому признаку вы определили, что блокировка происходит?

**Comment by Alex-302** [comment]
И давайте с проблемой определимся - мелькающая реклама и/или нерабочая карта.

**Comment by Juev** [comment]
Реклама на странице не отображается, карта не грузится. В консоли все те же сообщения о блокировке со стороны adguard.

**Comment by Alex-302** [comment]
Наверное ещё расширение установлено. Проверьте список установленных расширений. Может там со скрытой кнопкой, или вообще другой блокировщик присутствует.

**Comment by Juev** [comment]
Чтобы с проблемой определиться, надо понять, как работает программа. И почему ее поведение столь непонятно. :(

**Comment by Juev** [comment]
Других блокирующих расширений не установлено.

**Comment by Alex-302** [comment]
А выключение программы помогает?

**Comment by Juev** [comment]
Да, выключил программу, и реклама появилась и карта.

**Comment by Alex-302** [comment]
Теперь включите и поудаляйте фильтры. Посмотрим что в этом случае будет.

**Comment by Juev** [comment]
Фильтры уже были удалены ранее. Добавил только Английский и тут же пропала и реклама на странице и карта. Других фильтров в этот момент не было.

**Comment by Alex-302** [comment]
Очень странно. У меня с одним английским реклама не блокируется(точнее они её восстанавливают)
Завтра ещё в макоси гляну и отпишу.

**Comment by Alex-302** [comment]
@Juev похоже на баг, у меня повторилось. Карта по какой-то причине блокируется CSP, сразу не заметил в вашем логе:
`togliatti/:1 Refused to load the script 'https://api-maps.yandex.ru/2.1.45/?lang=ru_RU&coordorder=longlat' because it violates the following Content Security Policy directive: "default-src 'self' yastatic.net". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.`

**Comment by Alex-302** [comment]
По миганию рекламы, как в оригинальной жалобе - правила обновил, должно исчезнуть. Но не с прогой для макоси) (пока не разберёмся с проблемой)

**Comment by Alex-302** [comment]
Всё же баг
https://github.com/AdguardTeam/AdguardForMac/issues/203

**Comment by Stillness-2** [comment]
Разобрались.. это устранимо только в следующем релизе/бете :( #203

**Comment by Juev** [comment]
Ok, thank you

-- 
Denis Evsyukov


On Thu, Jun 15, 2017, at 14:19, Roman Sokolov wrote:
> Разобрались.. это устранимо только в следующем релизе/бете :( #203[1]> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/AdguardTeam/AdguardFilters/issues/203
  2. https://github.com/AdguardTeam/AdguardFilters/issues/5332#issuecomment-308702563
