### ISSUE TITLE
csgostash.com - Ad leftover/Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5333]
***Site***: https://csgostash.com/
***Description***: Ad leftover/Adblock detection

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27145457-365d1bd6-5136-11e7-9f14-638bbe464927.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.63
Spyware filter | 1.0.12.76
Social media filter | 1.0.20.46
Annoyances filter | 1.0.14.7
German filter | 1.0.34.92
Mobile ads filter | 1.0.8.74
Safari filter | 1.0.3.49

**Comment by Alex-302** [comment]
Fixed
