### ISSUE TITLE
Anti-adblock warning blocking the playing of video and breaking the website

### ISSUE THREAD

**Issue by sandybeachit** [AdguardTeam/AdguardFilters#5334]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
Video streams being blocked on AdGuard DNS with adblock warning message being shown on screen.

* **Current behaviour**: 
When browsing a number of video streaming sites using only the AdGuard DNS the video gets blocked with an adblock warning, an example is the video on the site below:

http://www.pinoymovieonline.net/amok.html

If i use only the Chrome extention for AdGuard then the adguard warning does not appear

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
The video is blocked with an adblock warning saying to turn off your adblocker to play the video

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

</details>

* **Expected behaviour**: 
Video should not be blocked / no adblock warning should appear

[//]: # (Tell us what should happen instead)
[//]: # (Оп
![screenshot_20170614-130350-01](https://user-images.githubusercontent.com/11394779/27147272-0bce60a2-5134-11e7-8cc1-8b536e757451.png)
ишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: |  Chrome
Adguard version: | Adguard DNS
Adguard DNS: | Default
Adguard filters: | 
Ticket ID (if exists): | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by sandybeachit** [comment]
![screenshot_20170614-130350-01](https://user-images.githubusercontent.com/11394779/27147280-17128b32-5134-11e7-91ac-76c5ec3045c1.png)

**Comment by Alex-302** [comment]
Excluded from DNS filter: `easylist.club`
Please check after few hours.

**Comment by sandybeachit** [comment]
Alex i have a couple of other sites like this which are of a similar issue do you want me to report them all in one go with screenshots or individually?

I just don't want to start spamming github/forums ?

Thanks

**Comment by sandybeachit** [comment]
Ok just tested and the videos play fine, there are some spammy popups which i expected but i'll report them seperatly, so looks like its a matter of excluding the main domain and then i'll have to report anything else which appears to get that blocked.

Nice work !
