### ISSUE TITLE
freevbcode.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5335]
***Site***: http://www.freevbcode.com/ShowCode.asp?ID=1086
***Description***: Ad leftover at the top.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27147021-9d89ef32-513b-11e7-9e94-4ea027cb6981.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.63
Spyware filter | 1.0.12.76
Social media filter | 1.0.20.46
Annoyances filter | 1.0.14.7
German filter | 1.0.34.92
Mobile ads filter | 1.0.8.74
Safari filter | 1.0.3.49

**Comment by AdamWr** [comment]
Fixed.
