### ISSUE TITLE
teletoonplus.pl blocked videos and detecting AG

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#5337]
https://github.com/AdguardTeam/AdguardForAndroid/issues/1284

**Comment by seba2282** [comment]
Ok. I added rules type : @@||tvn.adocean.pl and @@||s1-player5.cdntvn.pl to Android version with DNS and https filtering. For miniminiplus.pl it is working. For Extension I see, I must not add any rules. teletoonplus.pl base on this the same rules, but films are blocking. Suggestions ?

**Comment by Alex-302** [comment]
I need more info.
@seba2282 please open new issue and fill the template
https://github.com/AdguardTeam/AdguardFilters/issues/new

**Comment by seba2282** [comment]
@Alex-302 Ok, if I will have more time, I will add more information from PC, because from mobile it is hard. :)
