### ISSUE TITLE
allgemeine-zeitung.de - Ad - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5339]
***Site***: http://www.allgemeine-zeitung.de/
***Description***: Ad leftover. Ad in right sidebar.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27158436-37740f44-5167-11e7-9e21-962aafabf08e.png)

![image](https://user-images.githubusercontent.com/10995998/27158448-4c3b7dc2-5167-11e7-8aaf-9a9313d1e818.png)

![image](https://user-images.githubusercontent.com/10995998/27158476-7492890a-5167-11e7-853c-ce8035b68846.png)

![image](https://user-images.githubusercontent.com/10995998/27158468-6b0f2424-5167-11e7-80a7-aa3cea8399ed.png)

**http://www.allgemeine-zeitung.de/lokales/mainz/nachrichten-mainz/aus-mainz-weggezogen-antje-kuessner-scheidet-aus-stadtrat-aus-gunther-heinisch-rueckt-nach_17965578.htm:**

![image](https://user-images.githubusercontent.com/10995998/27158558-cfcb56d0-5167-11e7-9b74-f878648987e1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.63
Spyware filter | 1.0.12.76
Social media filter | 1.0.20.46
Annoyances filter | 1.0.14.7
German filter | 1.0.34.92
Mobile ads filter | 1.0.8.74
Safari filter | 1.0.3.49

**Comment by AdamWr** [comment]
Fixed.
