### ISSUE TITLE
mailtrack.io - Unblocked pop-up - Adguard AdBlocker extension for Chrome

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5340]
https://mailtrack.io/trace/link/68af05769f497fcc9bca2782db2aa05897e4120d?url=http%3A%2F%2Fwww.nolo.com%2Flegal-encyclopedia%2Fwhat-independent-medical-examination-how-will-it-affect-my-workers-compensation-case.html&userId=1269685&signature=c12057303b877874

<details><summary>Screenshot:</summary>

![screen shot 2017-06-15 at 12 17 34 am](https://user-images.githubusercontent.com/27292111/27159304-94d91104-5174-11e7-9a1e-d326cba2a60d.png)

</details>

Ticket ID: 1575195

**Comment by seanl-adg** [comment]
Fixed
