### ISSUE TITLE
[Feature Request] - More Filters - From iblocklist.com

### ISSUE THREAD

**Issue by versavius** [AdguardTeam/AdguardFilters#5341]
This would be to increase the number of ip's we are blocking that are regarding as tracking, spam, malware etc.

There is a github project which pulls all of the blocklists from:

[https://www.iblocklist.com/lists.php?fileformat=p2p&archiveformat=gz](https://www.iblocklist.com/lists.php?fileformat=p2p&archiveformat=gz)

and combines them into this:

[https://gist.github.com/johntyree/3331662](https://gist.github.com/johntyree/3331662)

At present this list can be added to Deluge and torrent clients as an blocklist to give some protection, that protect is about 60%, adding these block lists to your filters would be a step into improve your filter system especially as these filters are constantly updated so there would be little manual work you would need to do to sort through them.

Thanks for listening

David

**Comment by sandybeachit** [comment]
This is the link to the article about the blocklists (i am posting this for reference so you know what i am referring to):

[https://torrentfreak.com/anti-piracy-blocklists-dont-keep-bittorrent-spies-out-120904/](https://torrentfreak.com/anti-piracy-blocklists-dont-keep-bittorrent-spies-out-120904/)


This is the original article i came across about using the blocklists:

[https://digiex.net/threads/the-best-free-blocklist-for-transmission-deluge-to-keep-you-safe-when-you-torrent.14546/](https://digiex.net/threads/the-best-free-blocklist-for-transmission-deluge-to-keep-you-safe-when-you-torrent.14546/)

**Comment by ameshkov** [comment]
Not in the AG format, cannot be added as a filter.
