### ISSUE TITLE
fitnessuebungen-zuhause.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5342]
***Site***: https://fitnessuebungen-zuhause.de/
***Description***: Cookie notice at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27206163-ddf050b6-5235-11e7-84d1-e8cfac8c4a16.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.81
Spyware filter | 1.0.12.77
Social media filter | 1.0.20.54
Annoyances filter | 1.0.14.16
German filter | 1.0.34.98
Mobile ads filter | 1.0.8.74
Safari filter | 1.0.3.49

**Comment by AdamWr** [comment]
Fixed.
