### ISSUE TITLE
реклама на сайте - http://www.fontanka.ru/ 

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#5345]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: реклама на сайте - http://www.fontanka.ru/ 
![screen shot 2017-06-16 at 5 58 38 am](https://user-images.githubusercontent.com/23701680/27210122-e0db163a-5258-11e7-9b10-44580ca2fc4b.png)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1/6.1
Adguard filters: | Английский
Фильтр счетчиков и систем аналитики
Экспериментальный
Фильтр раздражителей
Русский
Фильтр мобильной рекламы

Ticket ID (if exists): | 1575780

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
