### ISSUE TITLE
missed ads https://ru.investing.com/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5346]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
missed ads https://ru.investing.com/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/25711093/27216329-f521d352-527d-11e7-9d07-3d69130d6c33.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | extension 
Browser: | chrome
Adguard version: | 6.1.331.1732
Adguard filters: | eng, rus, annoyance, spyware, social, experimental, mobile
Ticket ID (if exists): | 1248641

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Michael23456** [comment]
There are no ads with the standalone app. Will email the customer, that there are not ads with the standalone app installed and solutions to fix the issue.

**Comment by Alex-302** [comment]
fixed
