### ISSUE TITLE
washingtonexaminer.com - image is falsely blocked

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5347]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

when you go to http://www.washingtonexaminer.com/byron-york-five-more-notes-on-trumps-current-predicament/article/2626178
the image at the top is not shown with Adguard working

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29478021/27222502-204bae10-5295-11e7-9d4e-143e36f5178e.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29478021/27222550-5ed8acdc-5295-11e7-99c9-bf10d3cb2134.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS / iOS
Browser: | Chrome, Safari
Adguard version: | 1.4.1 / 1.2.1.71
Simplified filters(iOS) | On
Adguard DNS: | None
Ticket ID (if exists): | 1574951

Adguard filters: | 
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.21.60 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.74 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.43 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.14.5 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.48 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.74 Enabled=NO

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
