### ISSUE TITLE
https://www.bfm.ru/ - ads

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5348]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

https://www.bfm.ru/ ads leftovers

![image](https://user-images.githubusercontent.com/29478021/27223867-f846a27a-529a-11e7-8499-68f1c9026022.png)

***System configuration***:

Information | value
--- | ---
Operating system: | Mac OS
Browser: |  Safari
Adguard version: | 1.4.1 
Ticket ID : | 1576039
Adguard filters: | 1 2 3 4 5 14

**Comment by Alex-302** [comment]
Fixed
