### ISSUE TITLE
Suspected tracking domains: Amazon.sa and share.musemuse.cn 

### ISSUE THREAD

**Issue by rodaimi** [AdguardTeam/AdguardFilters#53498]
I keep seeing these two domains in my DNS request logs and they both seem suspicious. 

 I believe Amazon.sa is being used by the Amazon app and may be sending location data back to Amazon.
 
The domain share.musemuse.cn Seems to be connected to the social media app TikTok. 
 
 TikTok by the way, sends alot of tracking data to various Chinese domains. I have been trying to figure out what domains are being used to serve content and which domains are used for advertising and tracking, but this has been proven to be difficult to accomplish on iOS. Maybe you can look into the TikTok app, which works on both ios and Android.

**Comment by Alex-302** [comment]
@rodaimi both domains cannot be resolved by DNS. What is the source page?

**Comment by Alex-302** [comment]
Blocked `byteoversea.com`
