### ISSUE TITLE
https://vod.tvp.pl block anti-adblock script Adguard DNS (beta)

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5349]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**:

update filter for vod.tvp.pl and block anti-adblock script

screenshot #1 from TV -> Aguard DNS enabled = polish version with warning
to turn off
screenshot #2 from PC -> Aguards DNS ENABLED + Adblock Plus DISABLED = polish
version with warning to turn off
screenshot #3 from PC -> Aguards DNS ENABLED + Adblock Plus ENABLED = no
warning
screenshot #4 from PC -> Aguards DNS ENABLED + Adblock Plus ENABLED = no
warning (Adblock Plus blocked elements list)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screnshot_1_from_tv_warning](https://user-images.githubusercontent.com/29478021/27225909-051190b4-52a5-11e7-9521-275d4c80241a.jpg)

![image](https://user-images.githubusercontent.com/14153331/27230642-9456a814-52b8-11e7-93d1-d3778a8c139d.png)

![image](https://user-images.githubusercontent.com/14153331/27230650-9b671512-52b8-11e7-8b47-f02f46e03c8d.png)

![image](https://user-images.githubusercontent.com/14153331/27230659-a07bce9e-52b8-11e7-9a77-ad6f40678fc0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Simplified filters(iOS) | On / Off
Adguard DNS: |  Default 
Ticket ID (if exists): | 1573425

**Comment by AdamWr** [comment]
As I know, with normal Adblocker (Adguard, Adblock, etc.) antiadblock message is hidden by this cosmetic rule - `tvp.pl###tvpoverlay_abdinfo` - from Polish filter list, but it is impossible to block this message with DNS, because it can only block the whole domain.

I think in this case only solution will be allowing ads.

**Comment by Alex-302** [comment]
@AdamWr please check `DNS + Adguard` and `DNS + AdBlock`
If it works with Adblock, we should to fix our filter.

**Comment by AdamWr** [comment]
Ok, I checked this.

1. DNS + Adguard (with Polish filter list) = no warning
2. DNS + Adblock (with Polish filter list) = no warning
3. DNS + Adguard/Adblock (without Polish filter list) = antiadblock message

**Comment by Alex-302** [comment]
@kbahlyk please check on your side.

**Comment by Alex-302** [comment]
@kbahlyk @Bohdan-SUP

**Comment by ypetruk** [comment]
Checked on Mac OS
1. DNS + Adguard (with Polish filter list) =  antiadblock message
2. DNS + Adblock (with Polish filter list) = no warning
3. DNS + Adguard/Adblock (without Polish filter list) = no warning

**Comment by Alex-302** [comment]
@AdamWr can you confirm it?

**Comment by AdamWr** [comment]
No, I can't.
On my end I see this adblock notice only when I disable Polish filter list or with only Adguard DNS.
From what I know, this anti-adblock is triggered when `myao.adocean.pl/_[...]/ad.xml?id=[...]`* is blocked, and it should be hidden by this rule:
`tvp.pl###tvpoverlay_abdinfo`
from Polish filter list.

*for example - `https://myao.adocean.pl/_1501264327/ad.xml?id=yq9LXcQQmDD5uMOwtt3GZo_AE9F5CfJmls8GKwlqGhL.57/aocodetype=1/vortal_id=1597634/website_id=32812442/video_id=33124112/level=0%3Avod%3B1%`
