### ISSUE TITLE
tw.mobi.yahoo.com - Missed ad - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5350]
https://tw.mobi.yahoo.com/ 

Could not reproduce.

<details><summary>Screenshot:</summary>

![screen shot 2017-06-16 at 4 37 05 pm](https://user-images.githubusercontent.com/27292111/27228927-48e9e37e-52b2-11e7-956b-291b97050128.png)

</details>

***System configuration***

Application version: 1.2.2.88

Device: iPhone
Platform: iOS
OS: 10.3.1

Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.20.82 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.12.76 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.47 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.14.9 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.1.5 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.65 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.74 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.49 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.74 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.81.83 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.82 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.3.16 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.81.88 Enabled=YES
ID=210 Name="Spam404" Version=1.0.1.83 Enabled=YES

Ticket ID:  1574288

**Comment by Alex-302** [comment]
Not reproduced without Adguard.
@seanl-adg please check it on your side.

**Comment by seanl-adg** [comment]
Not reproduced with AG for Win.
