### ISSUE TITLE
Anti ad-blocker on: maalaimalar.com

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5351]
***Description***:
* **Current behaviour**: 

http://www.maalaimalar.com detects adblocking and prevents the user from seeing
anything.

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Chrome
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | high-speed 
HTTPS filtering (Android): |  On 
Adguard filters: | English, Spyware, Social media, Mobile Ads filter, Annoyances filter
Ticket ID: | 1354655

**Comment by AdamWr** [comment]
Fixed.
