### ISSUE TITLE
Ads on: extramovies.org

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5352]
***Description***:
* **Current behaviour**: 

Pop-up windows open after clicking on the movie link or "download"

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP 
Adguard filters: | English, Spyware, Social media, Dutch, Simplified domain names filter, Anti-Adblock Killer
Ticket ID: 913016

**Comment by AdamWr** [comment]
Fixed.
