### ISSUE TITLE
Remove an obsolete whitelist for phncdn in Base filter

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#53522]
`@@||phncdn.com^$domain=pornhub.com|pornhub.org|pornhub.net|pornhubthbh7ap3u.onion,image`
is not needed as now EasyList has
`@@||phncdn.com^$image,object,other,domain=pornhub.com|pornhubthbh7ap3u.onion|redtube.com|redtube.com.br|tube8.com|tube8.es|tube8.fr|youporn.com|youporngay.com`

**Comment by Yuki2718** [comment]
> 
> 
> AG base copy only safe filters from EasyList and AG Team no recomend use EasyList instead of AdGuard Base.

I know, but both rules are in Base so they are redundant.

**Comment by Alex-302** [comment]
Removed.
