### ISSUE TITLE
image is falsely blocked - http://mirtesen.ru/pad/43652796947

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5353]
***Description***:
* **Current behavior**: 

All images are blocked on http://mirtesen.ru/pad/43652796947
Reproduced on our side.

<summary>Screenshot:</summary>

<details>

![screen shot 2017-06-16 at 8 21 50 pm](https://user-images.githubusercontent.com/28784344/27237431-bd99e308-52d1-11e7-9e08-8bbb9636ba0a.png)

</details>

***Steps to reproduce the problem***:

Go on: http://mirtesen.ru/pad/43652796947

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1 (377)
Adguard DNS: | None 
Adguard filters: | 0, 1, 2, 3, 4, 10
Ticket ID (if exists): | 1534440

**Comment by Alex-302** [comment]
Fixed.
