### ISSUE TITLE
Missed image on https://gett.com/ru/

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5354]
***Description***:
* **Current behaviour**: 

There is one missed image on https://gett.com/ru/
Reproduced on our side

<summary>Screenshot:</summary>

<details>

![adguard_bug_gett](https://user-images.githubusercontent.com/28784344/27237164-bd0754b2-52d0-11e7-8a3f-3447a896ca95.png)

</details>

***Steps to reproduce the problem***:

Go on: https://gett.com/ru/

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 	1.4.1 (377)
Adguard DNS: | None 
Adguard filters: | 0, 1, 2, 3, 4, 10
Ticket ID (if exists): | 939612

**Comment by Alex-302** [comment]
fixed
