### ISSUE TITLE
Ads filma24.to

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardFilters#53545]
@afc321 commented on [Mon Apr 13 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3267)

Dear all,

Could you please help to remove below ads on the screenshot attached

![image](https://user-images.githubusercontent.com/63599820/79131780-725f1380-7da9-11ea-911d-32af2a8a1c65.png)
https://www.filma24.to/rumble-in-the-bronx-1995-filma-me-titra-shqip/

Thank you

**Comment by afc321** [comment]
Hello,

sorry but it is not fixed
Please see below

![image](https://user-images.githubusercontent.com/63599820/79251976-339c8c80-7e81-11ea-8bb5-ea087fa48ec0.png)

**Comment by zloyden** [comment]
Hi, this is not reproduced anymore on my end, please check filters update manually.
@AdamWr could you please check?
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/79328937-89277680-7f1f-11ea-87ef-50b3cfe39aa8.png)

</details><br/>

**Comment by AdamWr** [comment]
These ads are blocked on my end.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/79329279-cbe55080-7f17-11ea-8e5f-7c598604230f.png)

</details>

`LAJMET E FUNDIT` doesn't look like an ad.
Did you update filters?

Fixed popups, update should be available in 1-2 hours.

**Comment by afc321** [comment]
thank you very much for your help
