### ISSUE TITLE
Вредоносные домены!

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#53560]
При открытии этих доменов открывается явно вредоносные сайты. Прошу принять меры.
yoytube.com
ficbook.com
seasonvar.net

Также имеется мошеннический домен:
https://tele-geo.com

**Comment by Chinaski1** [comment]
Добрый день, @ghost!
Добавили указанные сайты в черный список!

**Comment by qwerty115xjy** [comment]
> Добрый день, @ghost!
> Добавили указанные сайты в черный список!

Спасибо!
