### ISSUE TITLE
Missed ad at http://onlinemultfilmy.ru/

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#5356]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )

Missed ad at http://onlinemultfilmy.ru/ 

Reproduced on our side.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/26434103/27240642-456d0e16-52de-11e7-8c88-7148933a7a2f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None
Adguard filters: | English, Russian, Annoyances, Social media, Spyware.
Ticket ID (if exists): | 1572531

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
