### ISSUE TITLE
Video add

### ISSUE THREAD

**Issue by afc321** [AdguardTeam/AdguardFilters#53561]
Dear all,

Could you please remove the video ad on this site  https://www.filma24.to/sea-fever-2019-filma-seriale-titra-shqip/

![image](https://user-images.githubusercontent.com/63599820/79160725-8bcc8380-7dda-11ea-99d7-81254b39bae8.png)

Thank you in advance for your help

**Comment by zloyden** [comment]
It was fixed here https://github.com/AdguardTeam/AdguardFilters/issues/53545
