### ISSUE TITLE
Редирект

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#53562]
Здравствуйте, возможен ли при помощи адгарда заблокировать сайт, с последующим редиректом на другой?

Например
Если я хочу просто заблокировать сайт я ввожу такое правило:
||example.com^important

Суть вопроса:
Возможно ли сделать так, чтоб вместо сайта example.com открывался, допустим, notexample.com ?

Платформа Андроид.

**Comment by krystian3w** [comment]
IMO no possible with AdGuard for Android.

**Comment by zloyden** [comment]
Можно сделать редирект и при этом заблокировать сайт. В данном примере перекинет на `yandex.ru`. На андроиде получится при использовании программы (не путать с расширением).
```
example.com#%#AG_onLoad(function(){window.location = window.location.protocol + "//yandex.ru" + window.location.pathname;});
||example.com^
example.com##body
```
