### ISSUE TITLE
Remove obsolete exception rules in Base

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#53576]
There are 28 exception rules for `/adframe.` but this EasyList rule is no more in Base filter so they should be removed.

**Comment by krystian3w** [comment]
Maybe other filter block request (attrib/parametr in url)?

**Comment by Yuki2718** [comment]
> 
> 
> Maybe other filter block request (attrib/parametr in url)?

Possible, maybe better to check one by one? OMG...
