### ISSUE TITLE
bzbasel.ch - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5357]
***Site***: https://www.bzbasel.ch/basel/basel-stadt/live-an-der-art-basel-das-laeuft-am-wochenende-rund-um-die-kunstmesse-131418943
***Description***: Anti Adblock Script

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27248983-e9368748-530b-11e7-955d-c351a282f013.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.93
Spyware filter | 1.0.12.78
Social media filter | 1.0.20.56
Annoyances filter | 1.0.14.19
German filter | 1.0.34.99
Mobile ads filter | 1.0.8.75
Safari filter | 1.0.3.49

**Comment by Alex-302** [comment]
Added to German filter
```
bzbasel.ch#$#.blockedContainer { display: block!important; }
bzbasel.ch#$#.az-iso--adblockerBlocker { display: none!important; }
```
