### ISSUE TITLE
nkd.com - Annoyance - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5359]
***Site***: https://www.nkd.com/
***Description***: Slider not loading. Cookie notice at the bottom right. Newsletter box at the end of the site.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27249060-ed591df8-530c-11e7-9f57-b37df13c5d0b.png)

![image](https://user-images.githubusercontent.com/10995998/27249053-cde7297e-530c-11e7-8012-5b58ad459ca3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.21.93
Spyware filter | 1.0.12.78
Social media filter | 1.0.20.56
Annoyances filter | 1.0.14.19
German filter | 1.0.34.99
Mobile ads filter | 1.0.8.75
Safari filter | 1.0.3.49

**Comment by AdamWr** [comment]
Fixed.
