### ISSUE TITLE
sites with ads

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#5360]
***Description***: sites with ads

---
Fixed domains are removed
                           Alex302

**Comment by ypetruk** [comment]
More sites (Ticket ID: | 1566670)
http://zbirna.com/
http://btu.org.ua/
http://prozak.info/
http://sports.te.ua/football/13372
http://dv-gazeta.info/ 
http://www.profootball.ua/2017/06/17/galatasaray_hochet_zinchenko_i.html
http://informweek.com/
http://infoindustria.com.ua/
http://jewishnews.com.ua/ru/publication/uchenie_rasshifrovali_zapisku_na_ivrite_vremen_pervogo_hrama

**Comment by vmalyuta** [comment]
http://sudba.in.ua/dating

**Comment by kbahlyk** [comment]
More sites (Ticket ID: | 1566670):
http://latifundist.com/

![image](https://user-images.githubusercontent.com/29478021/27253649-27aac8d4-5381-11e7-9fed-b09663fcdd42.png)

http://agroportal.ua/

![image](https://user-images.githubusercontent.com/29478021/27253657-3bde3b56-5381-11e7-9e02-c222ced65b1f.png)

http://open.fm/play/31

![image](https://user-images.githubusercontent.com/29478021/27253669-4933f4e4-5381-11e7-8e5d-6fedbb57626d.png)

http://101.ru/ 

![image](https://user-images.githubusercontent.com/29478021/27253670-51231892-5381-11e7-8416-59fbb26c0f6b.png)

**Comment by kbahlyk** [comment]
More sites (Ticket ID: | 1566670):
http://mnogoradio.ru/retro/disco-90x
http://lovi.fm/stations
http://radio.online360.ru/
http://radio.puler.ru/

**Comment by kbahlyk** [comment]
More sites (Ticket ID: | 1566670):
https://imhophone.ru/news/03-04-2017/5480/
http://maxpark.com/community/politic/content/5407588
http://linkis.com/politolog.net/ukrnew/bC5jV 
http://forum-psn.ru/index.php?showtopic=22960
http://www.rbc.ru/rbcfreenews/58b117dd9a79477372bb8303
http://rarcoin.ru/index/monety_dlja_pribaltiki_quot_livonezy_quot/0-52
http://rarcoin.ru/index/monety_dlja_pribaltiki_quot_livonezy_quot/0-52 
http://politolog.net/novosti-mira/korabl-razvedchik-vms-rf-obnaruzhen-v-ekonomicheskoj-morskoj-zone-latvii/
https://www.your-point.net/
http://shariki-games.ru/pushistiki
http://politrussia.com/news/na-krupnoy-ferme-568/
http://intrest.ru/archives/4404

**Comment by ypetruk** [comment]
http://medobzor.in.ua/index.php

**Comment by dzamyshlyayeva** [comment]
http://tangent-audio.ru/catalog/Krossvord-po-terapii-na-temu-gastrit.php
http://www.lafa.tv/faq/
http://gastric.monastyr-chai.org/?data1=20170618185806x75624&a_aid=54f4b70ed8d86&a_bid=490e9ab6&vid=240a536524ec85ca1e26507ebaaaa5a2&a_cid=
http://maxpark.com/blog_content 
http://vimperor.ru/

**Comment by veronikasav** [comment]
Anti Adblock

http://www.rbcplus.ru/
https://artage.io/ru/image-5682
http://www.sbup.com/seo-forum/poiskovaya_optimizaciya_v_obshih_chertah/kak_zashitit_sait_ot_adblock_programm_/
http://checker.actionpay.ru/?type=can_close
http://vek-noviy.ru/
https://www.autonews.ru/news/594791d49a7947118cc471c7
http://www.rbcplus.ru/

**Comment by kbahlyk** [comment]
Site with ads:
http://magnolia-tv.com/

**Comment by Alex-302** [comment]
> deleted a comment from

domains was not removed. Devided them by 10.

**Comment by kbahlyk** [comment]
http://www.agroperspectiva.com/ru/press_release/18564

**Comment by kbahlyk** [comment]
http://vaadua.org/
https://www.44.ua/
http://obukhiv.info/

**Comment by vmalyuta** [comment]
http://forpost.lviv.ua/
https://www.3849.com.ua/news/1701851
http://pedpresa.ua/
http://vnz.org.ua/
http://expert17.ru/news-by-region/respublika-mordoviya/544422-unikalnyy-avtograf-fidelya-kastro-obnaruzhen-v-mordovii.html
http://portalinweb.com/obnaruzhen-ptenec-vozrastom-pochti-100-mln-let/
http://vashgolos.net/readnews.php?id=77568
https://имву.рф/?index=verification
http://zx-pk.ru/threads/27710-zx-ulax.html?p=917397
http://rarcoin.ru/index/reklama_na_sajte_rarcoin_ru_spravochnik_numizmata/0-396
http://seriatv.ru/ 
http://forum-psn.ru/index.php?
https://tube10x.com/watch/GOhSZKF2-lU/-adblock.html
http://dota-trade.com/
http://medplus.com.ua/
http://03info.com/ 
http://novadoba.com.ua/index.php
http://infoindustria.com.ua/
http://www.pro-kyiv.in.ua/
https://kiev24.ua/

**Comment by vmalyuta** [comment]
http://topor.od.ua/
http://newsroom.kh.ua/news/kernes-pokazal-svoego-vnuka
http://vedomosti.od.ua/novosti/6061-yuristy-sovetuyut-vyezd-rebenka-za-granicu-esli-odin-iz-roditeley-protiv.html

**Comment by kbahlyk** [comment]
http://khersonline.net/ 
http://vdalo.info/
http://www.ugorod.kr.ua/news/2017-06-23-58997.html
http://www.uamarket.info/ukraintsy-zametili-nedochety-v-bezopasnosti-operatsij-v-privatbanke/
http://zakarpattya.net.ua/Blogs/171388-Hibrydnyi-piar-Moskalia.-10-kav-dlia-heneral-hubernatora
http://zakarpatpost.net/2017/06/23/dvi-tretyny-ukrajintsiv-ne-mayut-zakordonnyh-pasportiv-sotsiolohy/
http://gazeta.lviv.ua/2017/06/22/druzhina-andriya-sadovogo-prijshla-loda-shhob-pidtrimati-lviv-foto-video/
http://upn.in.ua/novini/1459-hersonc-mozhut-otrimati-servsi-mnyustu-ne-vihodyachi-z-vlasnogo-budinku.html
https://www.3849.com.ua/news/1700399
http://volyninfo.com/luchani-vshanuvali-pamyat-zagiblih-u-drugiy-svitoviy-viyni-foto/
http://briz.if.ua/44084.htm
http://www.myvin.com.ua/ua/news/culture/49825.html
http://viknaodessa.od.ua/
http://ua-ekonomist.com/
http://newvv.net/
http://obsurdo.ru/index.php
https://golovne.net/
http://medic.ymka.ru/ - webpage is falsy blocked by Adguard

**Comment by vmalyuta** [comment]
http://marpeople.com/news/91490/amazon-13-7

**Comment by vmalyuta** [comment]
https://www.ucoz.ru/qa/
http://avcore.ru/ 
http://бытьсильным.рф/
https://darkteam.net/forum/
https://max777gor.io.ua/s2434461/blokiratory_reklamy_ili_kak_otklyuchit_adblock_adblock_plus_ublock
https://max777gor.io.ua/
http://sport.rbc.ru/news/585138369a794727c648828e?from=main

**Comment by vmalyuta** [comment]
http://obukhiv.info/2017/06/03/%D1%82%D1%80%D0%B8%D0%BF%D1%96%D0%BB%D1%8C%D1%81%D1%8C%D0%BA%D0%B0-%D1%82%D0%B5%D1%81-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D1%82%D0%B8%D0%BB%D0%B0-%D0%BE%D0%B4%D0%B8%D0%BD-%D0%B7-%D0%B5%D0%BD%D0%B5%D1%80/
https://www.056.ua/news/1700193
http://stepnews.ks.ua/6069
http://favoritekherson.co/2017/06/24/v-hersone-stalo-na-odin-skver-bolshe-podarok-gorodu-k-olimpiyskomu-dnyu
http://shostka.info/shostkanews/proshhaj-shkola-prishla-pora-vypusknyh-foto/
https://od-news.com/
http://bessarabiainform.com/2017/06/spasateli-govoryat-kupatsya-na-stihijnom-plyazhe-v-izmaile-nelzya-i-tochka/
http://ck.ck.ua/smelyanin-hotel-sdelat-pomojnuyu-yamu-ryadom-s-detskim-sadom/
http://cherkassy-sport.com/futbol/11873-lrosava-nasha-rjabar-lzlatokraj-2017r-14
http://vycherpno.ck.ua/u-cherkasah-startuvav-gajdafest-foto/
http://dr.ck.ua/karamelnyy-ceh-zapracyuvav-na-cherkashchyni
http://erve.ua/news/society/u-rivnomu-perekriyut-rukh-avtomobiliv-.html
http://www.ugorod.kr.ua/news/2017-06-24-59020.html
http://fotoinform.net/news/novosti-na-ukrainskom-yazike/na-kirovogradshini-u-hvorih-ditey-vidileno-rotavirus.html
https://gre4ka.info/suspilstvo/37190-u-kropyvnytskomu-vidbuvsia-moleben-na-chest-heroiv-spetspryznachentsiv-foto
http://kr24.com.ua/news/pod-krivym-rogom-uchastok-za-26-milliona-vernuli-gosudarstvu
http://vesti.dp.ua/u-dnipri-zatrimali-cholovika-yakij-vistreliv-u-policejskogo/
http://www.sobytiya.dp.ua/news/na-dnepropetrovschine-zagadochno-pogib-veteran-desantnik-posle-ssory-s-vatnikami
http://lypa.com.ua/2017/06/25/ternopolyanam-pokazaly-sche-odnu-prychynu-pojihaty-do-sela-kurjoz/  
http://pro.te.ua/2017/06/24/ternopolyanyn-rozpoviv-yak-rivnyannya-na-lyudej-skalichylo-ne-odne-zhyttya/
http://www.kn.ks.ua/news/citynews/v-kahovke-obnaruzhenyi-ostanki-soldat-vremen-vtoroy-mirovoy-voynyi/

**Comment by vmalyuta** [comment]
http://gorohiv.rayon.in.ua/news/33451-bilia-gorohivskoyi-shkoli-htos-vikinuv-malenkih-kosheniat
http://kowel.rayon.in.ua/news/33525-volinrada-gotuvatime-zvernennia-pro-vidklikannia-miskogo-golovi-kindera-deputat-oblradi
http://rozhyshche.rayon.in.ua/news/33540-sesiia-rozhishchenskoyi-rairadi-obgovorili-situatsiiu-z-vodnimi-obektami-v-raioni
http://shatsk.rayon.in.ua/topics/1113-sergii-vinnichuk-koli-opustilisia-ruki-na-dopomogu-priishli-blagodiiniki
http://volyn.tabloyid.com/layf/podarunky-syurpryzy-ta-rozvagy-u-portcity-vitaly-syna-biycya
http://lutsk.rayon.in.ua/news/33559-u-lutsku-hlopets-zakinuv-koshenia-na-dah-zupinki
http://volyninfo.com/volinyani-namagatimutsya-vigrati-chempionat-svitu-z-3h3/
http://www.zhitomirnews.com/news/v-zitomirskij-oblasti-stavsa-nesasnij-vipadok-z-vodiem-dp-starokostantinivskij-molocnij-zavod
http://www.berdychiv.info/%d0%b4%d0%b5%d0%bd%d1%8c-%d0%b4%d0%b5%d0%bf%d1%83%d1%82%d0%b0%d1%82%d0%b0-%d0%b2-%d0%bf%d1%80%d0%b8%d0%b9%d0%bc%d0%b0%d0%bb%d1%8c%d0%bd%d1%96-%d1%96%d0%b3%d0%be%d1%80%d1%8f-%d1%80%d0%be%d0%bc%d0%b0/
http://berdpo.info/news/user/miskiy_golova_vasil_mazur_vitaie_berdichivlyan_z_dnem_mista-id10322.html
http://zhitomir.today/news/society/_oblasniy_tsentr_krovi_tri_roki_nelegalno_zbuvav_krov_za_zanizhenoyu_tsinoyu_video-id20423.html
http://news.dks.com.ua/index.php/zhitomir/20052-u-zhitomiri-genprokuror-ukrajini-yurij-lutsenko-visloviv-nevdovolennya-ta-oburennya-yakistyu-roboti-prokuraturi-zhitomirskoji-oblasti
http://infomalin.biz/news/rizne/zhitomir/yak-uberegtisya-vid-botulizmu-u-radomishli-zareyestrovano-vipadok-zahvoryuvannya.html
http://westnews.com.ua/dovga-borotba-za-zemlyu-yak-na-prikarpatti-u-gutsuliv-poloninu-vidbirayut-video/
http://www.blitz.if.ua/news/mysteckyy-port-na-zahodi-ukrainy.html
http://gazeta.lviv.ua/2017/06/24/na-pochatku-lipnya-u-lvovi-vidbudetsya-festival-teatriv-lyalok/
https://www.0532.ua/news/1702105

**Comment by kbahlyk** [comment]
http://izvestia.nikolaev.ua/
http://zmi.ck.ua/cherkassy/cherkask-lkar-operuyut-patsntv-na-starih-zarjavlih-stolah-vdeo.html
http://www.hromadske-zp.tv/zaporizhci-vidznachili-mizhnarodnij-den-jogi-na-ploshhi-zaporizkij-video/
http://cikave.ko.net.ua/?p=14510
https://podillyanews.com/2017/06/21/u-hmelnytskomu-stvoryuyut-yedynyj-reyestr-simejnyh-likariv/
http://news.dks.com.ua/index.php
http://dilova.com.ua/odessa/neadekvatnyie-sportsmenyi-izbili-prohozhih-video/
http://укроп.org/
http://buknews.com.ua/

**Comment by dzamyshlyayeva** [comment]
https://summonersrift.ru/lol_news/500 
http://mykyiv.com.ua/
http://zakarpattya.net.ua/
http://www.pro-lviv.in.ua/
http://ukrainepravo.com/
http://www.ntktv.ua/
http://ternopoliany.te.ua/
https://people.in.ua/
http://cheline.com.ua/
http://rtb.rv.ua/company/tele/news/2017/06/21/chomu-proekt-po-pagorbu-slavi-dosi-zatrimuyut-vide/
http://transkarpatia.net/
http://vse.rv.ua/
http://vycherpno.ck.ua/panki-z-kanadi-vistupili-v-umani-z-debyutnim-albomom-video/
http://rivne1.tv/Info/?id=82622
https://vinbazar.com/news/politika/dva-deputati-z-vinnichchini-popalisya-na-knopkodavstvi-ue
http://sfera-tv.com.ua/index.php?m=news&d=view&nid=67242
http://kurs.if.ua/
http://fakel.kr.ua/
http://gazeta.zp.ua/
https://bikepost.ru/
http://fox-fan.ru/adBlock.php
http://gnatkovsky.com.ua/
http://perchinka-khozyayushka.ru/
https://www.ucoz.ru/qa/
https://epscape.com/
https://wildo.ru/
http://secretive.pp.ua/
http://uportfolio.ru/
https://ferrerokinders.com/
http://www.rbc.ru/
http://htmlweb.ru/java/example/adblock_detect.php
http://perchinka63.ru/
http://teremok.org.ua/
https://eu.battle.net/forums/ru/heroes/topic/17613052032
https://tvfeed.in/genre/thriller/
https://butord.com/
https://zmoe.ru/
http://acetv.me/
http://odessa.net.ua/
http://03info.com/
http://rivne1.tv/
https://vinbazar.com/news/podiyi/u-vinnitsi-cholovik-shcho-prodavav-na-bazari-krosivki-pritorgovuvav-shche-i-marikhuanoyu
http://zakarpatpost.net/
http://vesti.dp.ua/
http://dzvin.news/
http://zolotonosha.ck.ua/2017/06/16/zlatogor-peremozhets-regulyarnoyi-ta-veterans-koyi-pershostej-cherkashhy-ny-foto/
http://kurs.if.ua/
http://vimperor.ru/

**Comment by aksyonova** [comment]
https://pmg.ua/
http://misto.news/
https://kh-news.net/
http://sevastopolnews.info/
http://newsroom.kh.ua/
http://ua-ekonomist.com/
http://newvv.net/
http://www.ednist.info/
https://golovne.net/
http://reporter.zt.ua/
http://sudba.in.ua/dating
http://lovi.fm/stations/
http://medic.ymka.ru/spaiki_v_legkih.php
http://dontimes.news/
http://www.zooclub.com.ua/631
http://provoker.com.ua/
http://www.kurier.hu/
http://reporter.com.ua/
http://russia-paranormal.org/
http://www.sibcity.ru/

**Comment by aksyonova** [comment]
Anti-adblocker on https://www.obozrevatel.com

**Comment by dzamyshlyayeva** [comment]
http://kurkul.com/blog/353-agromatematika-yak-zaoschaditi-pri-viroschuvanni-soyi-ne-vtrachayuchi-produktivnosti

**Comment by kbahlyk** [comment]
http://hronika.info/fotoreportazhi/240943-prostornyy-i-uyutnyy-dom-na-meste-starogo-garazha-foto.html
