### ISSUE TITLE
"Disable AdBlock" pop-up - https://www.audio-track.com/

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5361]
***Description***:
* **Current behaviour**: 

There is a " Please Disable AdBlock" pop-up on https://www.audio-track.com/
Reproduced on our side
<summary>Screenshot:</summary>
<details>

![image1](https://user-images.githubusercontent.com/28784344/27250539-5a35107a-533b-11e7-9817-b133bf03effd.png)

</details>

***Steps to reproduce the problem***:

1. Go on https://www.audio-track.com/

***System configuration***

Information | value
--- | ---
Operating system: | iOS 
Adguard version: | 1.2.1.71
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | 0, 2, 3, 4, 14, 11, 12, 101, 118, 123, 122, 207, 229
Ticket ID (if exists): | 1576422

**Comment by Alex-302** [comment]
Not reproduced.
@seanl-adg please check on your side.

**Comment by seanl-adg** [comment]
Reproduced on my end. Fixed.
