### ISSUE TITLE
anti-adblock http://www.rbc.ru/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5362]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
anti-adblock http://www.rbc.ru/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/25711093/27250898-7d43ffd2-5308-11e7-834f-81299393da99.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | chrome
Adguard version: | 1.4.1 
Adguard filters: | eng, rus, annoyance, spyware, social, experimental
Ticket ID (if exists): | 1177530

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
