### ISSUE TITLE
Вредоносные домены!

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#53621]
Здравствуйте,
Вот ещё список вредоносных доменов!

https://www.vzlomsn.org/vzlom-vkontakte-online
https://vzlom-pro.ru/vzlom-vkontakte/
https://vzlomhack.ru/
https://mestopolozhenie-telefona.com/
https://vzlom-soft.com/instagram/112-instagram-hack-vzlom-instagram.html
https://www.mobile-tracker.biz/
https://www.mobile-location.net/

**Comment by Chinaski1** [comment]
Добрый день!
Добавили указанные сайты в черный список!
