### ISSUE TITLE
Update filter descriptions to be more precise about link between Easylist + Adguard filters

### ISSUE THREAD

**Issue by RobynScore** [AdguardTeam/AdguardFilters#5363]
There is a possible source of confusion for (new) Adguard users trying to select appropriate filters.
Right now, it is not entirely clear what the relation is between Easylist filters & Adguard filters, as the [descriptions](https://kb.adguard.com/en/general/adguard-ad-filters) leave much room for interpretation:

**Scenario 1:**
Description of the English filter:
> Filter that enables removing of the ads from websites with English content. Originally based on the EasyList filter. Modified by us according to the complaints from users. [...]

The problem here is that the user does not know whether this filter is:
- A fork of the (English) Easylist filter at one point in the past (e.g. 3 years ago) and subsequently edited by Adguard's team.
- A fork of the (English) Easylist filter which is regularly (e.g. weekly) pulled + updated with Adguard's modifications to it.

The former situation would tempt the user to also enable Easylist for more "protection", the second would not.

**Scenario 2:**
Same as scenario 1, but then for some of the regional filter lists.

A positive example is the description text of the Russian list, which is very clear about its origins and present-day composition:
> Filter that enables removing of the ads from websites in Russian. The filter was created 5 years ago. Initially, the work on creation of this filter was based on RU AdList filter and a set of rules developed by us. Subsequently, the filter was developed completely independently, so at this point there are very little intersections with RU AdList left.

**Scenario 3**
The spyware filter description reads:
> The most comprehensive list of various online counters and web analytics tools. If you do not want your actions on the Internet be tracked, use this filter. This filter is original and was developed by us from scratch

The problem here is that the user does not know whether this would create a big overlap with EasyPrivacy (besides the point that AG removes duplicate entries in the end)

A positive example is the description of the Annoyances filter:
> Blocks irritating elements on webpages, including cookie notices, third-party widgets and in-page popups (Doesn’t include social media widgets and buttons, to block them you can still use Social media filter separately). It was inspired by Fanboy Annoyances List, but doesn’t duplicate it, so you can use them both together.

Here the user clearly knows he can activate both Adguard's and Fanboy's filter if wanted.

**Scenario 4**
Same as scenario 3, but then with the Social media filter

**Comment by Alex-302** [comment]
@altokarev @vozersky 
please take a look.

**Comment by vozersky** [comment]
@vbagirov

**Comment by vozersky** [comment]
I agree that phrase "Originally based" has to be changed in English filter description, it is not completely correct. It's actually our own rules PLUS fresh EL

**Comment by vozersky** [comment]
We have a correct description in the app though: 

! Description: EasyList + Adguard English filter. Filter list that specifically removes adverts on English language websites.

**Comment by RobynScore** [comment]
There seems to be a bit of discrepancy between the apps and the knowledgebase. 
For the original issue I was referring to the knowledgebase.

However, this occasion might also be used to harmonise these descriptions while making them more accurate. This also ties in to issue #5373.
