### ISSUE TITLE
Android Anti-Adblocking Library

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardFilters#5364]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
https://github.com/javiersantos/AdBlockerAdvise is a library that, when included,  detects whether an Android app's ads have been blocked & takes action.

___N.B.:___  I've no idea whether this issue belongs here or https://github.com/AdguardTeam/AdguardForAndroid/issues. I apologize if I picked wrongly.

* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Pops-up dialog box w/ customizable action when triggered.

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![demo](https://github.com/javiersantos/AdBlockerAdvise/raw/master/Screenshots/banner.png)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

App/library's blissful ignorance of adblocking. _(No screenshot b/c it depends whatever original app is designed to do.)_

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Run any app w/ this included.

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | n/a
Adguard version: | any
Adguard mode (Android): | any
Filtering quality (Android): | any
HTTPS filtering (Android): |  either
Adguard DNS: | any
Adguard filters: | any
Ticket ID (if exists): | n/a

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by TPS** [comment]
@Alex-302 Was this addressed in any fashion?

**Comment by Alex-302** [comment]
I don't know what to do with it.

**Comment by TPS** [comment]
Then why not leave it open as a requested feature, but low priority?  The techniques used in this library here will come in handy (eventually) when trying to debug some anti-adblocking problem....

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/34356442-70b7dc5e-ea46-11e7-8553-9fc70e85681d.png)
Project was updated one year ago
