### ISSUE TITLE
Реклама

### ISSUE THREAD

**Issue by Janne152** [AdguardTeam/AdguardFilters#5365]
На этом сайте неблокируемая реклама
http://fandom.wikia.com/explore-ru
Появляется на любой странице, кроме главной (например, на этой: http://ru.disney.wikia.com/wiki/%D0%A2%D0%B0%D1%87%D0%BA%D0%B8_3)

**Comment by Alex-302** [comment]
Шаблон создан для того, чтоб предоставить необходимую для устранения проблемы информацию.
Пожалуйста, создайте заново и предоставьте необходимую информацию.
