### ISSUE TITLE
fr.de - Social widget - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5366]
***Site***: http://www.fr.de/politik/rechtsextremismus/identitaere-bewegung-gegendemonstranten-blockieren-identitaeren-aufmarsch-a-1297840
***Description***: Social share wrapper. Subscription ad after article.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27254301-0240c21a-5386-11e7-8784-50d102ce2ac5.png)

![image](https://user-images.githubusercontent.com/10995998/27254327-88513196-5386-11e7-967f-9e2d56c7f4b2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.1
Spyware filter | 1.0.12.79
Social media filter | 1.0.20.56
Annoyances filter | 1.0.14.19
German filter | 1.0.34.99
Mobile ads filter | 1.0.8.75
Safari filter | 1.0.3.49

**Comment by seanl-adg** [comment]
Fixed
