### ISSUE TITLE
fraudstercrew.su [Adblock Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#53666]
https://fraudstercrew.su/forums/general-discussion.45/

Please remove the adblock message seen on this page. Checked with AG for Chrome.

**Comment by Nzzyme** [comment]
Seeing adblock message again on the page.

https://i.imgur.com/Pel6Dyi.png

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
