### ISSUE TITLE
aachener-zeitung.de - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5367]
***Site***: http://www.aachener-zeitung.de/
***Description***: Ad leftover. Social widget leftover.

<details>
<summary>Screenshot</summary>

**Whatsapp leftover:**

![image](https://user-images.githubusercontent.com/10995998/27254395-7f53bc16-5387-11e7-875d-a953e6a34dbb.png)

**Ad leftover (http://www.aachener-zeitung.de/mobile/news/politik/weltweite-trauer-um-altkanzler-kohl-1.1648978?redir=checkmobile):**

![image](https://user-images.githubusercontent.com/10995998/27254385-62e0333e-5387-11e7-9eb3-e1ddd8c32e65.png)

![image](https://user-images.githubusercontent.com/10995998/27254363-23e42ed8-5387-11e7-9cbe-7559196e5d2e.png)

**Ad leftover after article (http://www.aachener-zeitung.de/news/politik/weltweite-trauer-um-altkanzler-kohl-1.1648978):**

![image](https://user-images.githubusercontent.com/10995998/27254403-993b2d1c-5387-11e7-8fd7-0f556bd9c622.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.1
Spyware filter | 1.0.12.79
Social media filter | 1.0.20.56
Annoyances filter | 1.0.14.19
German filter | 1.0.34.99
Mobile ads filter | 1.0.8.75
Safari filter | 1.0.3.49

**Comment by AdamWr** [comment]
Fixed.
