### ISSUE TITLE
wiki.teamliquid.net - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5368]
***Site***: http://wiki.teamliquid.net/counterstrike/ScreaM_(Belgian_player)
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27254446-5cd7cf0a-5388-11e7-9349-175a54746dab.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.1
Spyware filter | 1.0.12.79
Social media filter | 1.0.20.56
Annoyances filter | 1.0.14.19
German filter | 1.0.34.99
Mobile ads filter | 1.0.8.75
Safari filter | 1.0.3.49

**Comment by AdamWr** [comment]
Fixed.
