### ISSUE TITLE
hulu.com ads - let's check them one more time

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/AdguardFilters#537]
http://forum.adguard.com/showthread.php?3542-Hulu-Ads-missed&p=50487&viewfull=1#post50487

**Comment by Alex-302** [comment]
Не пойму что юзер хочет. Вроде ж чисто там.

**Comment by adguard** [comment]
Надо смотреть через VPN американский.

Рекламы там полно. С рекомендуемыми фильтрами в этом посте реклама должна исчезнуть, но будет тупить 30 секунд перед каждым видео.

А он говорит, что реклама все равно есть, даже с рекомендуемыми.
