### ISSUE TITLE
teamliquid.net - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5370]
***Site***: http://www.teamliquid.net/
***Description***: Ad leftovers and cookie notice at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27257200-abf5bb20-53cd-11e7-9d5d-3e20f2b086dd.png)

![image](https://user-images.githubusercontent.com/10995998/27257201-bf875004-53cd-11e7-83d5-b75f9cf7675c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.1
Spyware filter | 1.0.12.79
Social media filter | 1.0.20.56
Annoyances filter | 1.0.14.19
German filter | 1.0.34.99
Mobile ads filter | 1.0.8.75
Safari filter | 1.0.3.49

**Comment by Alex-302** [comment]
fixed

**Comment by danidoedel** [comment]
@Alex-302 Cookie notice is still there for me.

**Comment by Alex-302** [comment]
It is hidden by the rule on my side.

**Comment by danidoedel** [comment]
@Alex-302 Hmm that's strange:

![image](https://user-images.githubusercontent.com/10995998/27434203-29edbdba-5758-11e7-9c88-aae0a3e97adb.png)

**Comment by danidoedel** [comment]
@Alex-302 Any update on this one?
