### ISSUE TITLE
csgo-stats.com - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5371]
***Site***: http://csgo-stats.com/76561197988768248/
***Description***: Ads

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27257211-2394e5ac-53ce-11e7-9940-17f394c24016.png)

![image](https://user-images.githubusercontent.com/10995998/27257216-3ed12dbc-53ce-11e7-86c4-02101958209a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.1
Spyware filter | 1.0.12.79
Social media filter | 1.0.20.56
Annoyances filter | 1.0.14.19
German filter | 1.0.34.99
Mobile ads filter | 1.0.8.75
Safari filter | 1.0.3.49

**Comment by Alex-302** [comment]
Fixed

**Comment by danidoedel** [comment]
@Alex-302 There is now some huge space at the top:

![image](https://user-images.githubusercontent.com/10995998/27379431-7e00940a-567b-11e7-812d-54463995bd81.png)

Can this be fixed as well?

**Comment by Alex-302** [comment]
No.
