### ISSUE TITLE
Ad leftover - kazus.ru

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5372]
***Description***:
* **Current behaviour**: 
There are ads (without images though) on:
http://kazus.ru/forums/showthread.php?p=1128246#post1128246
Reproduced on our side.

<summary>Screenshot:</summary>
<details>

![screen shot 2017-06-18 at 11 18 22 am](https://user-images.githubusercontent.com/28784344/27259286-e0608e40-5417-11e7-9637-f796a2f23191.png)

</details>

***Steps to reproduce the problem***:
Go on http://kazus.ru/forums/showthread.php?p=1128246#post1128246
***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None
Adguard filters: | 2, 3, 4, 10, 1, 0
Ticket ID (if exists): | 1576824

**Comment by Alex-302** [comment]
Fixed
