### ISSUE TITLE
trolli.is [N: Nano Adblocker] [T: Incorrect Blocking]

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#53728]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**:

A radio player button for `FM Trölli` in the upper right is blocked by `##iframe[width="300"][height="250"]` in AdGuard Base. I recommend whitelisting `trolli.is##iframe[width="300"][height="250"]`.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/79354927-542a1c80-7f3d-11ea-979e-36dbc4cfa8fe.png)
</details><br/>

* **Expected behaviour**: 

The radio player button shows up.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/79354743-188f5280-7f3d-11ea-81e8-e46663818ffb.png)
</details><br/>

***Steps to reproduce the problem***:

1) Visit `trolli.is`.
2) Although the temp-fix I added to my Nordic list has not gone live on AdGuard at the time of writing, you can turn that list off if you want to be 100% sure.

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/79355085-86d41500-7f3d-11ea-90be-53658f6d0b3f.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 November 2019 Update
Operating system version (Android/iOS) | N/A
Browser:                               | Chrome 81.0.4044.92 64-bit
AdGuard version:                       | Nano Adblocker 1.0.0.142 + Nano Defender 15.0.0.197
Filters enabled:                       | See screenshot above
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | N/A
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | N/A
Helpdesk ID (if exists):               | N/A

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
Thank you.
