### ISSUE TITLE
Fix description of Safari filter in Adguard Knowledgebase

### ISSUE THREAD

**Issue by RobynScore** [AdguardTeam/AdguardFilters#5373]
The description now reads:

> Filter that blocks ads on iOS mobile devices in Safari browser. Contains all known mobile ad networks. [...]

This is not correct, as the filter list functions to correct problems resulting from the use of Safari's Content Blocking API. This only applies to the Knowledgebase website, as I believe the description is correct in Adguard's products, for instance in this example of Adguard for iOS.

> Special filter for Safari 9+ on iOS and OS X. We need a separate filter for Safari because it does not fully support rules syntax.

**Possible enhancement:**
The description across all products could be enhanced to indicate more clearly why this filter exists and when it should be used. Consider the following possibility:

> Special filter for Safari 9 and above on iOS and MacOS when used in combination with Adguard filter lists or Easylist/Easyprivacy. We need a seperate filter because Safari's Content Blocking API does not fully support Adguard's advanced rules syntax.

**Comment by Alex-302** [comment]
@altokarev

**Comment by altokarev** [comment]
@vbagirov

**Comment by vbagirov** [comment]
Actually done btw.
