### ISSUE TITLE
news18.com/amp, howtogeek.com/amp

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#53749]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Advertisement placeholder

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/79378051-7beda480-7f7e-11ea-9577-4b8af0c588b2.PNG)
![2](https://user-images.githubusercontent.com/29574622/79378057-7e4ffe80-7f7e-11ea-9ff6-dcc7ae1709eb.PNG)

</details><br/>

* **Expected behaviour**: 

It shouldn't be there.

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

Visit this two sites: 
https://www.news18.com/amp/news/tech/first-ever-ultra-hd-image-of-sun-reveals-500km-long-plasma-threads-in-solar-atmosphere-2576001.html

https://www.howtogeek.com/664608/why-you-shouldnt-be-using-your-isps-default-dns-server/amp/

***System configuration***

**Filters:**

Adguard Base, AdGuard Mobile Ads, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10, Android
Operating system version (Android/iOS) | 1909, Android Pie
Browser:                               | Firefox 75, Firefox for Android
AdGuard version:                       | Adguard extension 3.4.19
Filters enabled:                       | 
AdGuard mode (Android only):           |
Filtering quality (Android only):      | 
HTTPS filtering (Android only):        | 
Simplified filters (iOS only)          | 
AdGuard DNS:                           | 
Stealth mode options (Windows only)    | 
Helpdesk ID (if exists):               | 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
