### ISSUE TITLE
Missed tracker on nu.nl

### ISSUE THREAD

**Issue by RobynScore** [AdguardTeam/AdguardFilters#5374]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
Missed tracker on www.nu.nl, one of Holland's biggest news websites.
Tracker originates from Finnish domain, as nu.nl is owned by a Finnish media company.

* **Current behaviour**: 
Tracker is not blocked through any of Adguard's filter lists (is blocked by Easyprivacy though)
`http://sat.sanoma.fi/js/sat.js `

* * Other trackers exist on the page as well (not blocked by any of of the Adguard/Easylist filters).
Image: `http://privacy.www.nu.nl/pixel/[long unique string]`
Image: `http://privacy.snmmd.nl/site/nu.nl/synchronize/[long unique string]`
However, blocking these interferes with the site's cookie notice.

* **Expected behaviour**: 
At least the first tracker should be blocked in spyware filter. As Sanoma is the owner of multiple Dutch and Finnish sites, the following rule seems applicable (exact rule exists in Easyprivacy):
`||sat.sanoma.fi^`
Using this rule does not seem to impact functionality of nu.nl.

***Steps to reproduce the problem***:
Browse to www.nu.nl with any filter list activated except Easyprivacy.

**Comment by Alex-302** [comment]
Fixed
