### ISSUE TITLE
Ads leftover - khazin.ru

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5375]
***Description***:
* **Current behaviour**: 

There are ads on 
http://khazin.ru/articles/165-intervju/51629-instituty-gosudarstva-razrusheny-okonchatelno-
Reproduced on our side

<summary>Screenshot:</summary>
<details>

![screen shot 2017-06-18 at 2 08 24 pm](https://user-images.githubusercontent.com/28784344/27260228-9ef61034-542f-11e7-96ab-03cdd9bd3f58.png)

</details>

***Steps to reproduce the problem***:

Go on: 
http://khazin.ru/articles/165-intervju/51629-instituty-gosudarstva-razrusheny-okonchatelno-

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None
Adguard filters: | 2, 3, 4, 10, 1, 0
Ticket ID (if exists): | 1576849

**Comment by Alex-302** [comment]
Fixed.
