### ISSUE TITLE
incorrect blocking https://gett.com/ru/services/gettcourier/

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5376]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
incorrect blocking https://gett.com/ru/services/gettcourier/

there should be images instead of empty places
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/25711093/27262515-b6bcdb54-5460-11e7-814e-1b5652656a0c.png)
![image](https://user-images.githubusercontent.com/25711093/27262528-e1b61550-5460-11e7-9c67-08ffed9202bc.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | chrome
Adguard version: | 1.4.1
Adguard filters: | eng, rus, spyware, social, annoyance, experimental
Ticket ID (if exists): | 939612

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
