### ISSUE TITLE
imgcach.ru/1101/466897/ - ads leftovers

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5378]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Ads on http://imgcach.ru/1101/466897/ 
Reproduced at our side.

Reproduced at our side.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29478021/27264442-39750e42-5487-11e7-80de-d79501a51c58.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)
</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 14
Ticket ID :| 1076701

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
