### ISSUE TITLE
sciencealert.com amp

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#53790]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Empty advertisement placeholders

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![2](https://user-images.githubusercontent.com/29574622/79449944-f1e91e80-8005-11ea-9a7b-261158a99b20.png)

</details><br/>

* **Expected behaviour**: 

There should be none

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

Visit this site: 
https://www.sciencealert.com/hunkering-down-for-an-antarctic-winter-during-covid-19/amp

***System configuration***

**Filters:**

Adguard Base, AdGuard Mobile Ads, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10, Android
Operating system version (Android/iOS) | 1909, Android Pie
Browser:                               | Firefox 75, Firefox for Android
AdGuard version:                       | Adguard extension 3.4.19
Filters enabled:                       | 
AdGuard mode (Android only):           | 
Filtering quality (Android only):      | 
HTTPS filtering (Android only):        | 
Simplified filters (iOS only)          |
AdGuard DNS:                           | 
Stealth mode options (Windows only)    | 
Helpdesk ID (if exists):               | 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
