### ISSUE TITLE
Allocine.fr fullscreen slideshow broken

### ISSUE THREAD

**Issue by SuperPat45** [AdguardTeam/AdguardFilters#53817]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
Using Adguard Annoyance with noscript, the file:
https://filters.adtidy.org/extension/chromium/filters/14.txt
contains this filter:
`allocine.fr#$#.overlay { display: none!important; }`
who break the full screen mode of the slideshow

* **Current behaviour**: 
Slideshow does not appear

[//]: # (Substitute this line with a description of the problem)
To reproduce, go to this page:
http://www.allocine.fr/diaporamas/series/diaporama-18689048/
and try to expand the slideshow

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

**Filters:**
AdGuard Annoyances​

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows
Operating system version (Android/iOS) | 10
Browser:                               | Firefox
AdGuard version:                       | ?
Filters enabled:                       | AdGuard Annoyances​​​​​​​​​ win NoScript
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
Thank you for reporting it.
