### ISSUE TITLE
Add "Fanboy's Anti-thirdparty Fonts" filter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#5382]
Original task:
https://github.com/AdguardTeam/AdguardForiOS/issues/175

Filter:
https://fanboy.co.nz/fanboy-antifonts.txt

@mmigi it was already added by Alex:
https://github.com/AdguardTeam/AdguardForiOS/issues/175#issuecomment-252913433

**Comment by mmigi** [comment]
The filter has been added.

**Comment by ameshkov** [comment]
@Alex-302 could you please check it?

**Comment by Alex-302** [comment]
@ameshkov 
It is ok
![image](https://user-images.githubusercontent.com/8361299/27328739-d858604c-55bb-11e7-9c41-ead2a9570f4a.png)
