### ISSUE TITLE
msn.com - videos won't play

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5383]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Video's won't play, see the screenshot

The example link: http://www.msn.com/ru-ru/video/trending/%d0%b2-%d0%bb%d0%be%d0%bd%d0%b4%d0%be%d0%bd%d0%b5-%d1%84%d1%83%d1%80%d0%b3%d0%be%d0%bd-%d0%b2%d1%80%d0%b5%d0%b7%d0%b0%d0%bb%d1%81%d1%8f-%d0%b2-%d1%82%d0%be%d0%bb%d0%bf%d1%83-%d0%bb%d1%8e%d0%b4%d0%b5%d0%b9/vi-BBCRvE5?refvid=BBCKoFQ&ocid=spartanntp

* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/27276116-cb34c48e-54e2-11e7-958b-4df5eef27e5c.png)

</details>

***Steps to reproduce the problem***: Open the Edge browser, scroll down and find an article marked with a Video icon, click on it. Try to play a video.

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10
Browser: | Edge
Adguard version: | the latest beta and release
Adguard driver (Windows): | WFP
Adguard DNS: | None 
Stealth mode options(Windows) | No
Adguard filters: | Basic filters - English, Spyware, Social media, Experimental
Ticket ID (if exists): | 1056631

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Please check this rule:
```
@@||adm.fwmrm.net/p/msn_live/AdManager.swf$domain=msn.com|akamaized.net
```

**Comment by dzamyshlyayeva** [comment]
asked the user

**Comment by KozelElena** [comment]
the issue still persists. Is there anything else we can do in this case?

**Comment by altokarev** [comment]
Can't reproduce. There is some lag while videos is loading but it plays well after that.

<details><summary>Screenshot:</summary>

![screen shot 2017-06-20 at 13 33 58](https://user-images.githubusercontent.com/28726429/27329181-63eacb9e-55bd-11e7-90ed-404134431e82.png)

</details>

**Comment by Alex-302** [comment]
@KozelElena @evgeniy-ADG please check for the issue and for unblocked video ads
```
@@||adm.fwmrm.net/p/msn_live/AdManager.swf$domain=msn.com|akamaized.net
@@||adm.fwmrm.net/p/msn_live/AdManager.js$domain=www.msn.com
@@||v.fwmrm.net/ad/g/1?$domain=www.msn.com
```

**Comment by Alex-302** [comment]
Added
