### ISSUE TITLE
Missed tracker on telegraaf.nl

### ISSUE THREAD

**Issue by RobynScore** [AdguardTeam/AdguardFilters#5384]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
Missed tracker on www.telegraaf.nl, the website of Holland's biggest newspaper.
Tracker is possibly applied to multiple websites.

* **Current behaviour**: 
Tracker is not blocked through any of the Adguard or Easylist lists.
Script: `http://d2qmp7jjpd79k7.cloudfront.net/smartpixel-1.js`

* Possible other tracker, yet unique to telegraaf.nl
`http://telegraaf.tcdn.nl/javascript/analyticsfunctions.[number string].js`
Blocking it does not seem to impact the site's functionality.

* **Expected behaviour**: 
At least first tracker should be blocked in spyware filter. 
Possible rule:
`||cloudfront.net/smartpixel*`
Using this rule does not seem to impact functionality of telegraaf.nl.

***Steps to reproduce the problem***:
Browse to www.telegraaf.nl with any filter list activated

**Comment by Alex-302** [comment]
Fixed.
