### ISSUE TITLE
gamingcfg.com - Social widget - Ad leftover - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5386]
***Site***: http://www.gamingcfg.com/command/cl_predict-l4d2-23687
***Description***: Ads and ad leftover. Socialbar leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27284785-78bf7e20-54fa-11e7-8d8d-e1a8939e3e6a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.26
Spyware filter | 1.0.12.84
Social media filter | 1.0.20.57
Annoyances filter | 1.0.14.27
German filter | 1.0.35.3
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.49

**Comment by seanl-adg** [comment]
Fixed
