### ISSUE TITLE
csgoconfigs.com - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5388]
***Site***: https://csgoconfigs.com/pros/olofmeister
***Description***: Ad background. Popup when clicking on a link for the first time.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27289779-75d06b32-550b-11e7-8fce-3c2b912de230.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.28
Spyware filter | 1.0.12.84
Social media filter | 1.0.20.58
Annoyances filter | 1.0.14.29
German filter | 1.0.35.4
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.49

**Comment by AdamWr** [comment]
Fixed.
