### ISSUE TITLE
gosugamers.net - Ads - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5389]
***Site***: http://www.gosugamers.net/counterstrike/players/49078-olofmeister
***Description***: Adblock detection. Ad in sidebar. Shop ads.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27296405-ff703722-5520-11e7-8053-1f5a2b237f7d.png)

![image](https://user-images.githubusercontent.com/10995998/27296503-5a6279d8-5521-11e7-9dfc-87bffc690dd1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.28
Spyware filter | 1.0.12.84
Social media filter | 1.0.20.58
Annoyances filter | 1.0.14.29
German filter | 1.0.35.4
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.49

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr 
There are some ads and ad leftovers:

![image](https://user-images.githubusercontent.com/10995998/29611023-58606a10-87fc-11e7-823b-7659df2ef6f1.png)

![image](https://user-images.githubusercontent.com/10995998/29611042-64e04b98-87fc-11e7-8ee9-de4eae12ecb3.png)

![image](https://user-images.githubusercontent.com/10995998/29611078-80a4f662-87fc-11e7-8bdb-0cba3a8fb270.png)
