### ISSUE TITLE
esport.aftonbladet.se - Social widget - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5390]
***Site***: http://esport.aftonbladet.se/csgo/scream-this-is-the-first-time-i-feel-famous/
***Description***: Ad block detection. Social share leftover. Facebook leftover in right sidebar and when scrolling down at the bottom left.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27297653-13ebde0e-5526-11e7-8949-89a2b280e19e.png)

![image](https://user-images.githubusercontent.com/10995998/27297687-319043d2-5526-11e7-864a-4b390cf8c315.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.30
Spyware filter | 1.0.12.84
Social media filter | 1.0.20.58
Annoyances filter | 1.0.14.31
German filter | 1.0.35.4
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.49

**Comment by seanl-adg** [comment]
Fixed
