### ISSUE TITLE
my.mail.ru - Ads

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5392]
Missed ad block. Div class="rb-media-banner".

 URL:

https://my.mail.ru/

<details><summary>Screenshot:</summary>

![screen shot 2017-06-19 at 21 17 34](https://user-images.githubusercontent.com/28726429/27299352-cde547c4-5534-11e7-9fd7-9505112f75a0.png)

</details>

<br>
***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome, Safari
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 12, 14

**Comment by Alex-302** [comment]
Fixed
