### ISSUE TITLE
https://lifehacker.ru/ - Missed pop-up - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5393]
https://lifehacker.ru/
Missed pop-up at the top

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/27306876-0a93d2f6-5550-11e7-870d-b051a04fdae4.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.22.32 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.85 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.58 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.52.77 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.49 Enabled=YES

Annoyances filter was added as well

Ticket ID: 1577594

**Comment by Alex-302** [comment]
It is not HTML element.
https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html
