### ISSUE TITLE
nos.nl/teletekst - Incorrect blocking of content 

### ISSUE THREAD

**Issue by RobynScore** [AdguardTeam/AdguardFilters#5394]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Content is incorrectly blocked on www.nos.nl/teletekst
Content is an image of teletext as usually seen on television

<details><summary>Screenshot:</summary>

![No teletext](https://user-images.githubusercontent.com/29501508/27309649-7e036c56-5555-11e7-8355-cd09dfff54e6.png)

</details>

* **Expected behaviour**: 
Content should be visible.

<details><summary>Screenshot:</summary>

![With teletext](https://user-images.githubusercontent.com/29501508/27309717-db30ee80-5555-11e7-9fc3-dcd387bf6ff6.png)

</details>

***Steps to reproduce the problem***:
Browse to www.nos.nl/teletekst with Adguard's Annoyances list enabled

***System configuration***

Information | value
--- | ---
Operating system: | MacOS & iOS
Browser: | Safari 10 
Adguard version: | Adguard Adblocker 2.5.12 & Adguard for iOS
Simplified filters | On
Adguard DNS: | None

English filterVersion 1.1.22.29. Updated 19 june 2017 at 17:00.
Spyware filterVersion 1.0.12.84. Updated 19 june 2017 at 14:00.
Social media filterVersion 1.0.20.58. Updated 19 june 2017 at 15:00.
Annoyances filterVersion 1.0.14.23. Updated 18 june 2017 at 12:02.
Dutch filterVersion 1.0.9.28. Updated 5 june 2017 at 21:01.
Safari filterVersion 1.0.3.49. Updated 14 june 2017 at 16:01.
Fanboy Anti-Facebook ListVersion 1.0.0.11. Updated 19 may 2017 at 11:36.

**Comment by seanl-adg** [comment]
Fixed
