### ISSUE TITLE
www.unionpeer.com - Missed ad, anti adblock - Adguard Adblocker 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5395]
http://unionpeer.com/

<details><summary>Screenshot:</summary>

![screen shot 2017-06-20 at 2 02 28 am](https://user-images.githubusercontent.com/27292111/27310079-7954f91c-5560-11e7-8a36-aeb97f9becb2.png)

</details>

Browser: Chrome / Opera / Yandex

Ticket ID: 1050245

**Comment by Alex-302** [comment]
Обнаружения блокировщика здесь нет, просто уведомление. А рекламу где увидели?
