### ISSUE TITLE
teamfortress.tv - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5396]
***Site***: http://www.teamfortress.tv/35467/on-the-correct-value-of-zoom-sensitivity-ratio
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27310393-4350403e-555a-11e7-85ef-92ae6e0555bf.png)

![image](https://user-images.githubusercontent.com/10995998/27310400-4e561152-555a-11e7-9804-a34ac5693787.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.30
Spyware filter | 1.0.12.84
Social media filter | 1.0.20.58
Annoyances filter | 1.0.14.31
German filter | 1.0.35.4
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.49

**Comment by seanl-adg** [comment]
Fixed
