### ISSUE TITLE
cswarzone.com - Ad leftover - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5398]
***Site***: http://cswarzone.com/csgo-improve-your-fps-and-game/
***Description***: Ad and ad leftover in right sidebar. Ad leftover and sponsor ad box at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27310479-cd193e4c-555a-11e7-9a43-85c93f04c272.png)

![image](https://user-images.githubusercontent.com/10995998/27310495-ea3b6608-555a-11e7-9168-5d8c8da6e664.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.30
Spyware filter | 1.0.12.84
Social media filter | 1.0.20.58
Annoyances filter | 1.0.14.31
German filter | 1.0.35.4
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.49

**Comment by seanl-adg** [comment]
Fixed
