### ISSUE TITLE
notube.net

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#53986]
`https://notube.net`

***Description***:
Popups

***Steps to reproduce the problem***:
try do download a video

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | win 10
Browser:                               | Opera
AdGuard version:                       | 3.3.8
Filters enabled:                       | default
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by krystian3w** [comment]
Try with enabled `AdGuard Annoyance` if no help maybe should fixed in AdGuard Base.

**Comment by JobcenterTycoon** [comment]
no i still get popup ads

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
