### ISSUE TITLE
esportsearnings.com - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5399]
***Site***: https://www.esportsearnings.com/
***Description***: Ad leftovers in right sidebar. Social widget leftover in footer.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27310680-44f01142-555c-11e7-971b-dc9c947366bd.png)

![image](https://user-images.githubusercontent.com/10995998/27310687-4fff197a-555c-11e7-88df-17127d3f5bd6.png)

![image](https://user-images.githubusercontent.com/10995998/27310696-60231f2c-555c-11e7-8426-e11a76407eb6.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.30
Spyware filter | 1.0.12.84
Social media filter | 1.0.20.58
Annoyances filter | 1.0.14.31
German filter | 1.0.35.4
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.49

**Comment by seanl-adg** [comment]
Fixed
