### ISSUE TITLE
THOP TV [Android] [Ad Block Message]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#53995]
**Issue**: Seeing an adblock message upon launching the following app:

**Screenshot**: https://ibb.co/vLVSyPD

**App Name**: Thop Tv
**Download Link**: https://bit.ly/2XP528i
**Android Version**: 6.0.1 MMB29M

**AdGuard Version**: 3.3.3 (231)

**Filters Applied**:

AG Base
Mobile Ads
Peter Lowe's Blocklist
AG Tracking Protection
AG Social Media filter
Malware Domains Blocklist
Spam404
NoCoin Filter List
AG Annoyances filter
Adblock Warning Removal List

**User Filters**:

```
||graph.facebook.com/*/activities
||graph.facebook.com/*?fields=
||graph.facebook.com/adnw_sync
```

**Stealth Mode**: On (Custom)

**Additional Info**: Checking the Filtering Log and monitoring all the connections from this app shows one block rule being applied from AG Tracking Protection filter namely:

`||graph.facebook.com/*?fields=supports_implicit_sdk_logging`

Can you please check this and provide an anti-adblock fix for this?

**Comment by Alex-302** [comment]
Please provide direct link, without shortener.

**Comment by Nzzyme** [comment]
https://zecifs2x2ps7.filecloud.services/?dl=b4432b19492606913c49e051245a721f

Here you go

**Comment by Alex-302** [comment]
Ads are loaded using google services, so we cannot unblock them.

**Comment by Nzzyme** [comment]
Which Google domains are responsible? 
Are you saying that some Google rules are allowed and are not blocked for ads?
Can you provide me the rules?

**Comment by Nzzyme** [comment]
Any response please?

**Comment by Alex-302** [comment]
You can find them in the filtering log - close this app, clear filtering log and reproduce this issue. Open filtering log from the main AG window and you will see the necessary strings.
