### ISSUE TITLE
http://yummyanime.com/catalog/item/na-sever-za-almaznoj-pyl-yu - player is blocked

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5401]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
When you go to website http://yummyanime.com/catalog/item/na-sever-za-almaznoj-pyl-yu the player is blocked

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screen shot 2017-06-20 at 10 50 24 am](https://user-images.githubusercontent.com/29478021/27322331-6902cddc-55a6-11e7-822a-f6f67c33f7b6.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29478021/27322216-ea66729e-55a5-11e7-9a0b-cfdceac27718.png)

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

</details>
</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | User filter, 1,2,3,4, 14
Ticket ID (if exists): | 1076701

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Он не заблокирован. У меня и без блокировщика нужно сперва на кнопку с номером видео нажать, она вызывает плеер.
