### ISSUE TITLE
gamerconfig.eu - Social widget - Ad leftover - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5402]
***Site***: http://www.gamerconfig.eu/command/counter-strike-global-offensive/cl_teamid_overhead/
***Description***: Facbook overlay. Ad leftovers and red ad bar at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27330689-cc2e8e3c-55ba-11e7-8da7-434fa21642d7.png)

![image](https://user-images.githubusercontent.com/10995998/27330758-13549018-55bb-11e7-84ab-ee8777771216.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.40
Spyware filter | 1.0.12.86
Social media filter | 1.0.20.60
Annoyances filter | 1.0.14.34
German filter | 1.0.35.6
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.49

**Comment by seanl-adg** [comment]
Fixed
