### ISSUE TITLE
dexerto.com - Social widget - Annoyance - Ad leftover - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5403]
***Site***: https://www.dexerto.com/news/2017/02/10/envyus-makes-g2-scream-french-csgo-derby/
***Description***: Newsletter box in right sidebar. Facbook bar at the bottom. Ad in right sidebar and after article. Ad leftover after article.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27330866-6aa23118-55bb-11e7-925d-e30dde982538.png)

![image](https://user-images.githubusercontent.com/10995998/27330919-a042f7a8-55bb-11e7-82d6-815bdf621f2a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.40
Spyware filter | 1.0.12.86
Social media filter | 1.0.20.60
Annoyances filter | 1.0.14.34
German filter | 1.0.35.6
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.49

**Comment by seanl-adg** [comment]
Fixed
