### ISSUE TITLE
pcgamesn.com - Social widget - Annoyance - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5405]
***Site***: https://www.pcgamesn.com/counter-strike-console-commands
***Description***: Social wrapper leftover. Ad after article and cookie notice at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27331347-54f034bc-55bd-11e7-99de-3188042d5f8e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.40
Spyware filter | 1.0.12.86
Social media filter | 1.0.20.60
Annoyances filter | 1.0.14.34
German filter | 1.0.35.6
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.49

**Comment by seanl-adg** [comment]
Fixed
