### ISSUE TITLE
energyfm.ru

### ISSUE THREAD

**Issue by zolpar** [AdguardTeam/AdguardFilters#5406]
Не работают кнопки, которые должны двигать постеры
![image](https://user-images.githubusercontent.com/16068744/27332305-0a4f5912-55ca-11e7-86c6-cb7fe905412e.png)

И также скажите, сколько вы получаете в долларах в месяц за добавление правил по блокировке рекламы?

**Comment by Alex-302** [comment]
Всё работает.
