### ISSUE TITLE
3g.163.com - Missed ad, ad leftover - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5407]
http://3g.163.com/touch/all?dataversion=A&version=v_standard

<details><summary>Screenshot:</summary>

Missed Ad.
![image](https://user-images.githubusercontent.com/27292111/27334074-bbeb0328-55d0-11e7-8432-12c1b38cefa6.png)

Ad leftover
![image](https://user-images.githubusercontent.com/27292111/27334098-d52625ac-55d0-11e7-8608-bba7adf3947a.png)

</details>

***System configuration***

Application version: 1.1.5.40

Device: iPhone
Platform: iOS
OS: 10.3.1

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.14.5 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.11.34 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.11.64 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.2.84 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.26 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.78.12 Enabled=YES

Ticket ID : 1539924

**Comment by seanl-adg** [comment]
Could you please mark ads with red rectangles in the screenshots you've posted?

**Comment by Alex-302** [comment]
@veronikasav @Bohdan-SUP

**Comment by veronikasav** [comment]
Now it looks like this:

<details><summary>Screenshot:</summary>

![image uploaded from ios 1](https://user-images.githubusercontent.com/27292111/28656178-158be600-72a9-11e7-8883-132f3aaf06b5.jpg)

![image uploaded from ios 2](https://user-images.githubusercontent.com/27292111/28656184-1c33f3ee-72a9-11e7-81d8-6100cdeffb99.jpg)


</details>

**Comment by Alex-302** [comment]
Added to Mobile filter
```
3g.163.com##.content-list > section.m_papa,papa-item
```
please check
