### ISSUE TITLE
www.marca.com - Anti Adblock - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5408]
http://www.marca.com/index.html

Not reproduced.

<details><summary>Screenshot:</summary>

![img_0773](https://user-images.githubusercontent.com/27292111/27336881-8ba111c2-55d9-11e7-9822-a4009175a42a.PNG)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.22.38 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.85 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.60 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.14.34 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.68 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.49 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.82.32 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES

Ticket ID:  1545021

[com.adguard.AdguardPro.gz](https://github.com/AdguardTeam/AdguardFilters/files/1088400/com.adguard.AdguardPro.gz)
[com.adguard.AdguardPro.tunnel.gz](https://github.com/AdguardTeam/AdguardFilters/files/1088402/com.adguard.AdguardPro.tunnel.gz)
[com.adguard.AdguardPro.ActionExtension.gz](https://github.com/AdguardTeam/AdguardFilters/files/1088401/com.adguard.AdguardPro.ActionExtension.gz)

**Comment by Alex-302** [comment]
Also not reproduced. Try to disable 
ID=207 Name="Adblock Warning Removal List" Version=1.0.82.32 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
