### ISSUE TITLE
minigames.mail.ru

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardFilters#54085]
Проблема с проникновение рекламы на сайте minigames.mail.ru при включенном Adguard и Tampermonkey с самыми последними обновленными фильтрами.

Operating system: Windows 10 Home
Browser: Chrome Version 81 (Official Build) (64-bit)
AdGuard version for Chrome: Version 3.4.19
Filters enabled: AdGuard Base filter, AdGuard Tracking Protection filter, EasyPrivacy, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter
Stealth mode options (Windows only) Enabled
![111](https://user-images.githubusercontent.com/23212486/79806770-e08b7380-8371-11ea-94a9-348dcb2c21c4.jpg)

**Comment by zloyden** [comment]
На скриншоте не видно установленного Tampermonkey, к тому же из описания не понятно, что в нем установлено. Установите скрипт AdGuard Extra (инструкция ниже), с ним не повторяется реклама. @Alex-302 посмотри у себя.

---

Пользователям браузерного расширения нужно установить скрипт `AdGuard Extra`. Для этого понадобится браузерное расширение-скриптоприёмник `Tampermonkey`

Ссылка на `AdGuard Extra`
https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js

После установки скрипта нужно будет зайти в настройки `Tampermonkey`, включить режим эксперта, переключить режим встраивания на `мгновенный` и перезапустить расширение:
![image](https://user-images.githubusercontent.com/8361299/62641343-07248e00-b94c-11e9-9775-9854a7922889.png)

![image](https://user-images.githubusercontent.com/8361299/62641299-f7a54500-b94b-11e9-8a83-885d89abbeec.png)

**Comment by jbionic2016** [comment]
> На скриншоте не видно установленного Tampermonkey, к тому же из описания не понятно, что в нем установлено. Установите скрипт AdGuard Extra (инструкция ниже), с ним не повторяется реклама. @Alex-302 посмотри у себя.
> 
> Пользователям браузерного расширения нужно установить скрипт `AdGuard Extra`. Для этого понадобится браузерное расширение-скриптоприёмник `Tampermonkey`
> 
> Ссылка на `AdGuard Extra`
> https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js
> 
> После установки скрипта нужно будет зайти в настройки `Tampermonkey`, включить режим эксперта, переключить режим встраивания на `мгновенный` и перезапустить расширение:
> ![image](https://user-images.githubusercontent.com/8361299/62641343-07248e00-b94c-11e9-9775-9854a7922889.png)
> 
> ![image](https://user-images.githubusercontent.com/8361299/62641299-f7a54500-b94b-11e9-8a83-885d89abbeec.png)

Невидно, потому что спрятано. Всё стоит и всё настроено ровно так как Вы советовали и в прошлом тоже

**Comment by zloyden** [comment]
Странно, у меня все также не повторяется. Попробуйте это правило `minigames.mail.ru#%#//scriptlet("abort-current-inline-script", "$", "advBlock")`, проверить нужно будет в режиме инкогнито.

**Comment by jbionic2016** [comment]
> minigames.mail.ru#%#//scriptlet("abort-current-inline-script", "$", "advBlock")

В смысле "в режиме инкогнито"? В этом режиме extensions ведь отключены...

> Странно, у меня все также не повторяется. 

Вы можете не поверить, то у меня и самого этот рекламный баннер появляется через раз: иногда маячит, иногда - нет. Но уже сейчас очевидно, что Adguard его не может подавить

**Comment by zloyden** [comment]
> В смысле "в режиме инкогнито"? В этом режиме extensions ведь отключены...

Если дать разрешение расширению, то оно сможет работать в этом режиме. Нужно поставить галочку напротив опции `Разрешить использование в режиме инкогнито`. 
Правый клик на нашем расширении -> `Управление расширениями`. После активируйте эту опцию как на скриншоте либо можете очистить кэш / куки браузера и после проверить с выше правилом.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/79846272-e95a6480-83c6-11ea-9083-5a271081ea37.png)
</details><br/>

**Comment by jbionic2016** [comment]
Спасибо за инструкцию. Сделал как Вы посоветовали, рекламы пока не наблюдаю. Мне теперь постоянно что ли в режиме инкогнито держать Adguard включенным, или после эксперимента могу отключить, оставив при этом включенным только само правило?

**Comment by zloyden** [comment]
Правило можете удалить, я добавил его в наши фильтры, обновление прилетит через 2-3 часа. Насчет разрешения это на ваше усмотрение, если будете пользоваться в дальнейшем режимом инкогнито, можно оставить.
