### ISSUE TITLE
Embedded videos +++ not working

### ISSUE THREAD

**Issue by nahcos** [AdguardTeam/AdguardFilters#54081]
Hi, Settings > Network > Filtering method was initially set at local VPN. Once this setting is saved I could no longer see embedded videos (CBC News app) AND MS Teams and MS OneDrive they both behave as if I wouldn't have network connection. I tried switching to Local HTTP proxy and rebooted the (rooted) phone however the problem persists. Please advice. I purchased an unlimited licence under the name Cosmin Nahaiciuc a few days ago. 

Thanks,
Cosmin

**Comment by Alex-302** [comment]
Hi. We need more details. Please send report using AdGuard menu + direct links.
