### ISSUE TITLE
Redirection to Play market

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5409]
***Description***:
* **Current behaviour**: 
Is the redirection of the website (http://www.velodrive.ru/) to Play Market considered to be an ad? Or is it the website's own ad:  built-in ad? 
Reproduced on Android
<summary>Screenshot:</summary>
<details>

![screenshot_2017-06-20-18-32-56](https://user-images.githubusercontent.com/28784344/27343763-94dfd788-55ec-11e7-875c-8e7d14b68842.png)

</details>

***Steps to reproduce the problem***:

Go to http://www.velodrive.ru/

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.70
Adguard mode (Android): | Proxy(manual)
Filtering quality (Android): | high-speed 
HTTPS filtering (Android): |  On (Default/) / 
Adguard DNS: | None 
Adguard filters: | 2, 3, 4, 1, 11
Ticket ID (if exists): | 1559107

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Fixed in https://github.com/AdguardTeam/AdguardFilters/commit/8ee54a4378b8ef777e91d36047e2e912a812ff47
