### ISSUE TITLE
Redirection + empty ad space leftover videofun.cf

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5410]
***Description***:
* **Current behaviour**: 

Redirection that opens and closes by itself. And there is an empty ad space.
Reproduced on our side.
***Steps to reproduce the problem***:

go on: http://videofun.cf

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Adguard version: | 6.1.331.1732/ 1.4.1
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Adguard filters: | 1, 2 ,3 ,14, 0 , 4, 11, 103
Ticket ID (if exists): | 716537

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed. 
Please wride description only in the message, not in the issue name.
