### ISSUE TITLE
theverge.com delay

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdguardFilters#54102]
@SeriousHoax commented on [Sat Apr 18 2020](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626)

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  3.4.19
- **Browser and version:**
  -  Chromium Edge 81
- **Operating system and version:**
  -  Windows 10
- **Filters you use in AdGuard:**
  -  Adguard Base, AdGuard Mobile Ads, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media
- **Stealth Mode settings:**
  - 
- **Other browser extensions:**
  - 

### Expected Behavior

 Website loading with unnecessary delay

### Actual Behavior

 Delay in page loading for https://www.theverge.com/ 
When the page is visited there's always a certain unnecessary delay for the page to come into view. Now if I click on an article then there's a delay again, if I go back then there's a delay as well. This is Adguard extension related because there's no such issue with uBlock Origin with same filters.

### Screenshots

 Check the gif for details on how to reproduce

<details><summary>Screenshot:</summary>

![adg](https://user-images.githubusercontent.com/29574622/79636026-ac0f9000-8196-11ea-9402-73a7808c78d5.gif)
</details>

### Additional Information

---

@zecanard commented on [Sat Apr 18 2020](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626#issuecomment-615896273)

Not experiencing this with the browser extension in Safari on macOS Catalina 10.15.4 and iOS 13.4.1, if that helps narrow it down.

---

@SeriousHoax commented on [Sat Apr 18 2020](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626#issuecomment-615897056)

> 
> 
> Not experiencing this with the browser extension in Safari on macOS Catalina and iOS 13.4.1, if that helps narrow it down.

I've asked this to some other users on Windows and they are experiencing this delay too more or less. One of them is even using Adguard desktop. He has this delay too on The Verge website. So maybe this needs to be tested on Windows. Same behavior with Firefox on Windows 10.

---

@Yuki2718 commented on [Mon Apr 20 2020](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626#issuecomment-616291353)

> 
> One of them is even using Adguard desktop. 

In fact it's not an extension issue but a filter issue, so should be moved to AdGuardFilters.
Please add this to User Rules and test:
`||googletagmanager.com/gtm.js$script,redirect=googletagmanager-gtm,domain=theverge.com`

If the issue persists, also:
```
||googletagservices.com/tag/js/gpt.js$script,redirect=googletagservices-gpt,domain=theverge.com
theverge.com#%#//scriptlet('abort-current-inline-script', 'CONCERT_ADS_CONFIG.dfpVariables')
```

---

@Alex-302 commented on [Mon Apr 20 2020](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626#issuecomment-616431694)

Hmm. I cannot reproduce this issue - page content loaded fast.

---

@SeriousHoax commented on [Mon Apr 20 2020](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626#issuecomment-616451760)

> 
> 
> > One of them is even using Adguard desktop.
> 
> In fact it's not an extension issue but a filter issue, so should be moved to AdGuardFilters.
> Please add this to User Rules and test:
> `||googletagmanager.com/gtm.js$script,redirect=googletagmanager-gtm,domain=theverge.com`
> 

Hi, the first rule fixed the issue. The second one was not required. Now the page is loading fast as it should. So should this be forwarded to Adguard filters? 

---

@Yuki2718 commented on [Mon Apr 20 2020](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626#issuecomment-616512943)

> 
> 
> Hmm. I cannot reproduce this issue - page content loaded fast.

It may not be obvious delay, but when visited the top page I got page-blink or a temporal black screen, and after clicking any article again blink or a temporal white screen - how long it take depends, sometimes 0.5 sec or so other times more.  Reproduced on: Firefox 75.0 + AG 3.4.19 (Base + Tracking)

**Comment by Yuki2718** [comment]
@SeriousHoax commented on https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626#issuecomment-619564430
> 
> @Yuki2718 The issue has been fixed for the extension but it's still present in the desktop app for Windows. Have a look please!

Okay reproduced. Please test this:
`theverge.com#%#//scriptlet('abort-current-inline-script', 'document.documentElement', 'GTM-')`

Of note, it turned out this is not an AdGuard issue but a site issue (ill-configured Google Optimize).

**Comment by SeriousHoax** [comment]
> 
> 
> @SeriousHoax commented on [AdguardTeam/AdguardBrowserExtension#1626 (comment)](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1626#issuecomment-619564430)
> 
> > @Yuki2718 The issue has been fixed for the extension but it's still present in the desktop app for Windows. Have a look please!
> 
> Okay reproduced. Please test this:
> `theverge.com#%#//scriptlet('abort-current-inline-script', 'document.documentElement', 'GTM-')`
> 
> Of note, it turned out this is not an AdGuard issue but a site issue (ill-configured Google Optimize).

Hi, actually I don't have Adguard desktop installed right now because my browsing speed slowed down so I removed it for now. I'm unable to check at the moment if the suggested filter works. But since you were able to reproduce, I guess it should work for everyone.

**Comment by Yuki2718** [comment]
> 
> Hi, actually I don't have Adguard desktop installed right now because my browsing speed slowed down so I removed it for now. I'm unable to check at the moment if the suggested filter works. But since you were able to reproduce, I guess it should work for everyone.

All right, but please let us know if somebody has tested it before AdGurad Team.

@AdguardTeam/filters-maintainers Are there other platforms on which redirect doesn't work like extensions but support scriptlet injection? Can you add the rule with `!+ NOT_PLATFORM(windows)` (+ the other platforms if any) directive? The waiting PR is here. https://github.com/AdguardTeam/AdguardFilters/pull/54114

**Comment by SeriousHoax** [comment]
> 
> 
> > Hi, actually I don't have Adguard desktop installed right now because my browsing speed slowed down so I removed it for now. I'm unable to check at the moment if the suggested filter works. But since you were able to reproduce, I guess it should work for everyone.
> 
> ~All right, but please let us know if somebody has tested it before AdGurad Team.~
> 
> ~@Alex-302 Are there other platforms on which redirect doesn't work like extensions but support scriptlet injection? Can you add the rule with `!+ NOT_PLATFORM(windows)` (+ the other platforms if any) directive?~
> 
> @uBlok-user has suggested a better fix.

Hi, I reinstalled Adguard desktop again. The rule you gave above, `theverge.com#%#//scriptlet('abort-current-inline-script', 'document.documentElement', 'GTM-')`
This one is working. So you have found a better solution now? Let me know if you want me to try that.

**Comment by Yuki2718** [comment]
> 
> Hi, I reinstalled Adguard desktop. The rule you gave above, `theverge.com#%#//scriptlet('abort-current-inline-script', 'document.documentElement', 'GTM-')`
> This one is working. So you have found a better solution now? Let me know if you want me to try that.

Not me, uBlock-user ; )
This one:
`theverge.com#$?#.async-hide { opacity: 1.0 !important }`
Make sure to disable my previous rule. Thank you for your cooperation.

**Comment by SeriousHoax** [comment]
> 
> 
> > Hi, I reinstalled Adguard desktop. The rule you gave above, `theverge.com#%#//scriptlet('abort-current-inline-script', 'document.documentElement', 'GTM-')`
> > This one is working. So you have found a better solution now? Let me know if you want me to try that.
> 
> Not me, uBlock-user ; )
> This one:
> `theverge.com#$?#.async-hide { opacity: 1.0 !important }`
> Make sure to disable my previous rule. Thank you for your cooperation.

This one is working fine too. Happy to help :)

**Comment by Yuki2718** [comment]
Committed, just wait for the official fix!

**Comment by KilometerM** [comment]
I came across this issue as I still experience this delay on theverge.com and polygon.com (sister-site) using AdGuard for Mac. Using the below filters resolved the issue. 
`theverge.com#$?#.async-hide { opacity: 1.0 !important }`
`polygon.com#$?#.async-hide { opacity: 1.0 !important }`

I was initially confused because this issue and https://github.com/AdguardTeam/AdguardFilters/pull/54114 https://github.com/AdguardTeam/AdguardFilters/commit/75f9e43b8aff7c33ad2b26d806430ce516db34cc indicate that this should be fixed. Looking at the commit, it appears a variation on the above filter was committed which does not work. `theverge.com#$#.async-hide { opacity: 1.0 !important }` (note the missing '?') I feel that this should be fixed in the base filter so this issue on theverge.com and its sister site polygon.com can be resolved for users of the desktop app.

@Yuki2718 @Alex-302

**Comment by Yuki2718** [comment]
@KilometerM `?` was not added because pseudo-class was not used. Simply put, your filter is wrong tho it may work. I don't have Mac so can't test.

**Comment by KilometerM** [comment]
Okay, thank you. I am not as well versed in the syntax. All I know is that the committed filter does not resolve this issue on the desktop apps. The filter including the `?` as first mentioned by you here https://github.com/AdguardTeam/AdguardFilters/pull/54114#commitcomment-38753874 and tested here https://github.com/AdguardTeam/AdguardFilters/issues/54102#issuecomment-619581306 does resolve the issue demonstrated in this thread.
