### ISSUE TITLE
minigames.mail.ru/poker - ads

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5411]
Missed ad block.

 URL:

https://minigames.mail.ru/poker

<details><summary>Screenshot:</summary>

![screen shot 2017-06-20 at 20 20 07](https://user-images.githubusercontent.com/28726429/27346497-19fcbb26-55f6-11e7-8ba5-7883b718593e.png)

</details>

<br>
***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome, Safari
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 12, 14

**Comment by Alex-302** [comment]
Fixed
