### ISSUE TITLE
https://www.uranium-backup.com

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5412]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://www.uranium-backup.com/purchase-uranium-backup/ - cookies notification at the top

Operating system:	Windows / Mac OS
Browser:	Chrome / Pale Moon / Internet Explorer С
Adguard version:	613141628 / 1.4.1
Adguard driver (Windows):	WFP
Adguard filters:	1 2 3 4 5 10 14

Ticket ID: 1419169

**Comment by seanl-adg** [comment]
Fixed
