### ISSUE TITLE
fb.ru - missed ads 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#5413]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

There are ads and ads leftovers on fb.ru

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/17320558/27369421-81f9d956-5660-11e7-9f4a-e0d7b74b6241.png)

![image](https://user-images.githubusercontent.com/17320558/27369436-8d1ad768-5660-11e7-915d-f1914434ca22.png)

</details>

***Steps to reproduce the problem***:

http://fb.ru/article/307087/politolog-vyacheslav-kovtun-biografiya-foto-i-interesnyie-faktyi

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Chrome
Adguard version: | 2.9.111 beta (and on 2.9.70)
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | English, Spyware, Social, Annoyances, Russian, Mobile ads
Ticket ID (if exists): | 1568034

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
