### ISSUE TITLE
Ads on 1tv.ru/live

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#5414]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Background and video ads on 1tv.ru/live

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/17320558/27374343-13bda0c6-5674-11e7-8006-2b0cbb9eb78c.png)

![image](https://user-images.githubusercontent.com/17320558/27374346-151c0728-5674-11e7-9231-ae7cc6587474.png)

</details>

***Steps to reproduce the problem***:

http://www.1tv.ru/live

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | User, Russian, English, Annoyances, Spyware, Social media, Safari 
Ticket ID (if exists): | 1577515

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
