### ISSUE TITLE
babycenter.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5415]
***Site***: https://www.babycenter.de/
***Description***: Various newsletter stuff and overlay.

*Rules:*
```
babycenter.de###welcomeRow
babycenter.de###registrationModuleRight
babycenter.de###registrationModuleBottom
```

Note sure for the overlay though.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27374506-62d097f2-566c-11e7-846f-4570f1a7f542.png)

***https://www.babycenter.de/c26064/sie-und-ihre-familie:***

![image](https://user-images.githubusercontent.com/10995998/27374542-872bd120-566c-11e7-82f1-1db2759174e4.png)

***Overlay after some time clicking through the site:***

![image](https://user-images.githubusercontent.com/10995998/27374628-d027c6f4-566c-11e7-93f2-f1f288594612.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.49
Spyware filter | 1.0.12.87
Social media filter | 1.0.20.63
Annoyances filter | 1.0.14.35
German filter | 1.0.35.7
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.50

**Comment by AdamWr** [comment]
Fixed.
