### ISSUE TITLE
dotesports.com - Social widget - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5416]
***Site***: https://dotesports.com/
***Description***: Adblock detection. Social widget left of articles.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27376769-699f3708-5673-11e7-8944-9fdb0c239347.png)

***https://dotesports.com/counter-strike/the-most-useful-console-commands-for-cs-go-14256:***

![image](https://user-images.githubusercontent.com/10995998/27376732-55fa692a-5673-11e7-8204-ec36edb1aa85.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.49
Spyware filter | 1.0.12.87
Social media filter | 1.0.20.63
Annoyances filter | 1.0.14.35
German filter | 1.0.35.7
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.50

**Comment by AdamWr** [comment]
Fixed.
