### ISSUE TITLE
gfinityesports.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#54187]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Empty advertisement placeholders

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/79964061-fef58a00-84ab-11ea-9f83-afba0a3cdd33.jpg)

</details><br/>

* **Expected behaviour**: 

There should be none

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

Visit this site:
https://www.gfinityesports.com/article/4156/rainbow-six-siege-y5s12-patch-notes-full-update-notes-for-operation-void-edge

***System configuration***

**Filters:**

Adguard Base, AdGuard Mobile Ads, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 1909
Browser:                               | Chromium Edge 81
AdGuard version:                       | Adguard extension 3.4.19

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
