### ISSUE TITLE
expedia.com - Blocked search functionality

### ISSUE THREAD

**Issue by RobynScore** [AdguardTeam/AdguardFilters#5419]
***Description***:
Trying to search for a hotel or flight on expedia.com (and its localised domains such as expedia.nl) does not work.
* **Current behaviour**: 
Searching results in an infinite search animation (spinner).

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )

* **Expected behaviour**: 
After the search animation, a new page should be loaded displaying the results of your search.

***Steps to reproduce the problem***:
Enable spyware filter and search on expedia.com, .nl, .de, _et cetera_.

* This is caused by blocking `https://c.travel-assets.com/datacapture/2/js/dctk.js`
by the following rule in the spyware filter: `||travel-assets.com/datacapture/`
Unblocking this specific script allows the results to display.

* It is probably better not to whitelist the entire tracker domain on Expedia's domains as that will load `https://a.travel-assets.com/datacapture/2/js/cl.js` which triggers several ad scripts. 
Whitelisting this script does _not_ fix the infinite spinner.

***System configuration***

Information | value
--- | ---
Operating system: |  MacOS 
Browser: | Safari 10
Adguard version: | 2.5.12

English filterVersion 1.1.22.46. Updated 21 june 2017 at 00:00.
Spyware filterVersion 1.0.12.87. Updated 20 june 2017 at 15:00.
Social media filterVersion 1.0.20.62. Updated 20 june 2017 at 21:00.
Annoyances filterVersion 1.0.14.34. Updated 20 june 2017 at 11:02.
Dutch filterVersion 1.0.9.28. Updated 5 june 2017 at 21:01.
Safari filterVersion 1.0.3.50. Updated 20 june 2017 at 17:02.
Fanboy Anti-Facebook ListVersion 1.0.0.11. Updated 19 may 2017 at 11:36.

**Comment by Alex-302** [comment]
Removed.
