### ISSUE TITLE
watchdb.net - Missed Ad - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5421]
http://www.watchdb.net/dragon-ball-super_episodes

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/27385740-5142b71a-569c-11e7-915a-5a6673ecd50b.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 11.0

Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.22.21 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.81 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.57 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.14.31 Enabled=YES
ID=10 Name="Filter unblocking useful ads" Version=1.0.1.8 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.49 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.76 Enabled=YES
ID=101 Name="EasyList" Version=1.0.72.89 Enabled=YES

Ticket ID: 1572122

**Comment by Alex-302** [comment]
I can't watch the videos without Adguard.
