### ISSUE TITLE
hd-world.org - Unblocked pop-up - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5425]
http://hd-world.org/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/27397693-db83d8dc-56bf-11e7-81d4-fa57eb5aba17.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.22.54 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.89 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.64 Enabled=YES
ID=6 Name="German filter" Version=1.0.35.8 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.51 Enabled=YES

Annoyances Filter = YES

Ticket ID: 1578639

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
||hd-world.org/layer18.js
```
please check
