### ISSUE TITLE
hulldailymail.co.uk - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5426]
***Site***: http://www.hulldailymail.co.uk/news/hull-east-yorkshire-news/bridlington-bank-hacker-spent-100k-126052
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27410692-6ff2db20-56e9-11e7-9513-dcaf3604cbd9.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.49
Spyware filter | 1.0.12.87
Social media filter | 1.0.20.63
Annoyances filter | 1.0.14.35
German filter | 1.0.35.7
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.50

**Comment by AdamWr** [comment]
Fixed.
