### ISSUE TITLE
stylevamp.de - Annoyance - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5428]
***Site***: http://www.stylevamp.de/
***Description***: Cookie notice. Newsletter form and facebook leftover in right sidebar. Facebook button after article.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27410801-23d5c094-56ea-11e7-9842-ba2054fd521c.png)

**http://www.stylevamp.de/p/2rb53w/schneller-braun-werden-5-tricks-die-dir-eine-knackige:**

![image](https://user-images.githubusercontent.com/10995998/27410838-5a638d3a-56ea-11e7-99b2-bfee8bf3352c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.49
Spyware filter | 1.0.12.87
Social media filter | 1.0.20.63
Annoyances filter | 1.0.14.35
German filter | 1.0.35.7
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.50

**Comment by AdamWr** [comment]
Fixed.
