### ISSUE TITLE
climate.nasa.gov

### ISSUE THREAD

**Issue by yokoffing** [AdguardTeam/AdguardFilters#54289]
### List the website(s) you're having issues:

`https://climate.nasa.gov/evidence/`

### What happens?

1) Go to page
2) Scroll down a good ways on the page
3) Social media widget pops up to the left.

### Screenshot:

https://postimg.cc/yJhCxMB2

### Your settings

- OS/version: macOS 10.15.4
- Browser/version: Safari, Vivaldi, Firefox
- Adblock Extension/version: AdGuard / uBlock Origin

**Comment by krystian3w** [comment]
Use Fanboy Social Blocking list?

If this is not floating - may no fix at all by AdGuard filters.

**Comment by yokoffing** [comment]
Fanboy has fixed this on his list as of this morning. I thought I’d submit to AdGuard so y’all could cover this as well.

**Comment by krystian3w** [comment]
For my no worth for `AdGuard Social Media`, but worth for `AdGuard Annoyance`.

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
