### ISSUE TITLE
physicsworld.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#54285]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Ads + Annoyances + Empty ads placeholders

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/80155663-fdc77880-85e3-11ea-8691-2d2e023e91a4.png)

</details><br/>

* **Expected behaviour**: 
No ads, annoyances and placeholders

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

Visit this site:
https://physicsworld.com/a/hubbles-best-shots-eta-carinae/

***System configuration***

**Filters:**

Adguard Base, AdGuard Mobile Ads, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 1909
Browser:                               | Chromium Edge 81
AdGuard version:                       | Adguard extension 3.4.19

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by SeriousHoax** [comment]
Just noticed this on Firefox Android. Don't know if anything can be done about this filter wise but just putting it out here. To reproduce, visit 3-4 articles on the site then it will appear in one. 

https://ibb.co/qp87pB3

**Comment by zloyden** [comment]
Blocked ads, but we don't block their social links in header or footer. Element with Register button isn't an annoyance - it's their part of the functionality of the site.
