### ISSUE TITLE
nothingprivate.ml

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#54280]
***Description***:
* **Current behaviour**: 

Completely ignores Stealth Mode filtering options.

<details><summary>Screenshot:</summary>
![nothingprivate](https://user-images.githubusercontent.com/33634917/80135283-b1127c00-85a8-11ea-813f-e7313da9c07c.png)
</details><br/>

***Steps to reproduce the problem***:

1. Go to website, enter an identifier
2. Open the same website in incognito mode - it would still detect you

***System configuration***

**Original Submission**

Information                            | Value
---                                    | ---
Operating system:                      | macOS
Operating system version (Android/iOS) | 10.15.4
Browser:                               | Chrome, Firefox
AdGuard version:                       | 2.3.2.710 release
Filters enabled:                       | Base, Mobile Ads, Tracking Protection, Social Media, Fanboy's Social Blocking List, Annoyances, Adblock Warning Removal List, I don't care about cookies, Malware Domains, Filter unblocking search ads and self-promotion, Safari filter, Russian, German, Japanese, Dutch, Spanish/Portuguese, French, EasyList China, EasyList Czech/Slovak, EasyList Dutch, EasyList Hebrew, EasyList Italy, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Adblock List for Finland
Stealth mode options (Windows only)    | {stealth.enabled: true;stealth.third_party_cookies: 30;stealth.disable_third_party_cache: true;stealth.x_client: true;stealth.strip_url: true;stealth.strip_url_parameters: utm_source utm_medium utm_term utm_content utm_campaign utm_referrer yclid gclid fbclid _openstat fb_action_ids fb_comment_id fb_action_types fb_ref fb_source action_object_map action_type_map action_ref_map;stealth.DNT: true;stealth.ip: 209.141.53.254;stealth.block_third_party_auth: true;stealth.hide_search_queries: true;stealth.referrer:; 
stealth.user_agent:;stealth.webrtc: true;stealth.push: true;stealth.location: true;stealth.java: true
Helpdesk ID (if exists):               | 2645596

**Reproduction**
Information                            | Value
---                                    | ---
Operating system:                      | Windows
Operating system version (Android/iOS) | 10.0.18363
Browser:                               | Chrome
AdGuard version:                       | 7.3 release
Filters enabled:                       | Base, Mobile Ads, Russian, Adblock Warning Removal List
Stealth mode options (Windows only)    | {stealth.enabled: true;stealth.third_party_cookies: 30;stealth.disable_third_party_cache: true;stealth.x_client: true;stealth.strip_url: true;stealth.strip_url_parameters: utm_source utm_medium utm_term utm_content utm_campaign utm_referrer yclid gclid fbclid _openstat fb_action_ids fb_comment_id fb_action_types fb_ref fb_source action_object_map action_type_map action_ref_map;stealth.DNT: true;stealth.ip: 209.141.53.254;stealth.block_third_party_auth: true;stealth.hide_search_queries: true;stealth.referrer:; 
stealth.user_agent:;stealth.webrtc: true;stealth.push: true;stealth.location: true;stealth.java: true}
Helpdesk ID (if exists):               | Self-reported

**Reproduction HARs**:
[no-stealth-mode.zip](https://github.com/AdguardTeam/AdguardFilters/files/4524522/no-stealth-mode.zip)
[stealth-mode.zip](https://github.com/AdguardTeam/AdguardFilters/files/4524524/stealth-mode.zip)

HARs are mine, not customer's. No private data included.

Archives contain two files each: one for non-incognito tab, one for incognito tab (where detection occurs)

**Comment by Alex-302** [comment]
@akmLaVx wrong repository. Not filter's issue.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/CoreLibs #1294](https://github.com/AdguardTeam/CoreLibs/issues/1294) via [**ZenHub**](https://www.zenhub.com/)
