### ISSUE TITLE
blick.ch - Social widget - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5430]
***Site***: https://www.blick.ch/
***Description***: Social bar on mobile. Newsletter form in right sidebar. Annoying slide in when scrolling down.

<details>
<summary>Screenshot</summary>

**https://www.blick.ch/sport/tennis/entspricht-nicht-der-wahrheit-becker-wehrt-sich-gegen-die-bankrott-berichte-id6877762.html:**

![image](https://user-images.githubusercontent.com/10995998/27410911-e5d17954-56ea-11e7-97e5-227891fa1446.png)

**https://www.blick.ch/news/politik/fdp-und-svp-sind-veraergert-jeder-dritte-ahv-rentner-lebt-im-ausland-id6877558.html:**

![image](https://user-images.githubusercontent.com/10995998/27410945-178a7644-56eb-11e7-9e0d-69f3ec3bdfb2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.49
Spyware filter | 1.0.12.87
Social media filter | 1.0.20.63
Annoyances filter | 1.0.14.35
German filter | 1.0.35.7
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.50

**Comment by AdamWr** [comment]
Fixed.
