### ISSUE TITLE
abercrombie.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5436]
***Site***: https://www.abercrombie.com/shop/eu-de
***Description***: Newsletter overlays on desktop and mobile.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27435130-6e2abdc2-575b-11e7-81bb-783660deafb5.png)

![image](https://user-images.githubusercontent.com/10995998/27435138-76dafa18-575b-11e7-8d28-5564a7b19a4a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.62
Spyware filter | 1.0.12.89
Social media filter | 1.0.20.69
Annoyances filter | 1.0.14.43
German filter | 1.0.35.10
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.51

**Comment by seanl-adg** [comment]
Fixed
