### ISSUE TITLE
cultofmac.com (Google AMP) - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5437]
***Site***: https://www.google.de/amp/s/www.cultofmac.com/488640/ios-11-beta-2-whats-new/amp/
***Description***: Ad leftover after article.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27435469-9d569746-575c-11e7-9641-e7b652c00752.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.62
Spyware filter | 1.0.12.89
Social media filter | 1.0.20.69
Annoyances filter | 1.0.14.43
German filter | 1.0.35.10
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.51

**Comment by seanl-adg** [comment]
Fixed
