### ISSUE TITLE
||popupmaker.com^$third-party

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#54385]
***Description***:
* **Current behaviour**: 

We've been contacted by PopupMaker developers. They have sent us the following message:

_We are providing a Software As A Service platform called Popup Maker (
https://popupmaker.com) so that users can create marketing popups which aim
to increase their subscriptions and engagement on their websites.

Recently we have noticed that AdGuard extension started to block the popups
that have been created via our platform.
We totally understand that maybe some of our users didn't use the service
as aimed but the blocking rule was applied for anyone who uses our service
even if the popup was used to restrict the adult content and we think this
global rule is not fair.

In our terms, we have a special part where we have defined the acceptable
use and conduct of the service and we think that we have been added to
block list by mistake -> Acceptable Use and Conduct.

My question is: Could you please review the rule
(EnglishFilter->sections->adservers.txt -> ||popupmaker.com^$third-party)
which was added to your blocklist so that Adguard will not block all our
popups but ones that really doing advertisements._

**Comment by Alex-302** [comment]
The site, where it was found, is not working now. Removed from **our Base filter** only.
