### ISSUE TITLE
wp.pl - Ads Leftovers

### ISSUE THREAD

**Issue by rbeznosko-sya** [AdguardTeam/AdguardFilters#5438]
***Description***:
missed ads at www.wp.pl

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![wppl](https://user-images.githubusercontent.com/29629815/27436421-e75f7a5a-5767-11e7-9dc3-3a5c1c517254.PNG)
</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.331.1732
Adguard filters: | English, Russian, Annoyances, Spyware, Social, Adblock Polska, ublock polish filter, ublock polish filter - Adg supplement
Ticket ID : | 1579143

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@AdamWr 
please check
```
wp.pl###section_topnews > div[style*="width: 970px; caption-side: inherit; height: 300px;"]
```

**Comment by AdamWr** [comment]
@Alex-302 unfortunately it does not work on my end.

Basing on this topic - https://forum.adguard.com/index.php?threads/wp-pl.19418/#post-136768
if I disable this rule:
`www.wp.pl#%#Object.defineProperty(window,'testMess',{value:'no'});`
and then add this:
`www.wp.pl#%#Object.defineProperty( window, 'testMess', { set: function(){} });`
I do not see ads, but I think that it would be nice if @seanl-adg look at this also.

**Comment by seanl-adg** [comment]
Fixed. They added another check when the value of `testMess` is `no`.
```
var a, s, c = n(0), u = n(4), d = n(2), l = n(6), f = n(9), p = n(26), h = n(1), g = n(17)(), m = d.buildLocation, v = l.randomize, b = l.sxor, y = 'https://', w = 'pathname', E = 'hostname', S = 'search', A = 'folder', _ = 'file', T = 'indexOf', x = 'substr', C = 250, I = 'length', D = 'replace', N = 'testMess', P = 'no', k = '', O = '/', B = [
                'WP.gaf.data',
                'WP.gaf.bodies',
                'WP.inline'
            ], R = d.getParameterByName(N), L = R || c[N],;
        if (R !== P && L === P) {
            try {
                a = document.head.textContent.match(/testMess\s*=\s*['"]([a-z\.]+)['"]/);
            } catch (e) {
            }
            L = !(!a || !a[1]) && a[1];
        }
```
