### ISSUE TITLE
[Android] iWawa app

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#5439]
***Description***: в приложении родительского контроля iWawa пропущена реклама.
***Current behaviour***: после пользования приложением на протяжении некоторого времени (клики по меню туда-сюда и т.д.) появляется баннер внизу экрана либо полноформатная реклама на весь экран.

Оригинальный пост: https://forum.adguard.com/index.php?threads/4113/#post-142042

Ссылка на приложение: https://play.google.com/store/apps/details?id=com.sencatech.iwawa.iwawahome&hl=ru

Тестировалось на Android 4.4.2

**Comment by Alex-302** [comment]
Где там упоминание рекламы и скрин?

**Comment by Alex-302** [comment]
@vbagirov

**Comment by vbagirov** [comment]
Повторял у себя. Список фильтров: English, Russian, Spyware, Mobile, Social. Реклама иногда появляется в как будто бы случайные моменты после переходов по разным иконкам внутри приложения.

**Comment by Alex-302** [comment]
Не повторяется никак. Запиши HAR или юзера попроси.
