### ISSUE TITLE
kachelmannwetter.com - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5440]
***Site***: https://kachelmannwetter.com/de/homepagewetter
***Description***: Facebook leftover. Ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27444791-be455e7c-5777-11e7-82e8-7ddb2a00de71.png)

![image](https://user-images.githubusercontent.com/10995998/27444823-d8d532b2-5777-11e7-9523-51e19dd56634.png)

![image](https://user-images.githubusercontent.com/10995998/27444845-e755489a-5777-11e7-8c53-3335630919ef.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.62
Spyware filter | 1.0.12.89
Social media filter | 1.0.20.69
Annoyances filter | 1.0.14.43
German filter | 1.0.35.10
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.51

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr There is some ad leftover on the mobile page (https://kachelmannwetter.com/de/stormtracking):

![image](https://user-images.githubusercontent.com/10995998/28777938-71d763ec-75fd-11e7-8235-f4e188703d0b.png)

**Comment by AdamWr** [comment]
Ok, fixed.
