### ISSUE TITLE
wetter.com - Annoyance - Ad leftover - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5441]
***Site***: http://www.wetter.com/deutschland//wetterstation/DEXXX0146.html
***Description***: Whatsapp newsletter stuff in sidebar. Ads in sidebar. Ad leftover in forecast list.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27446041-648d8526-577c-11e7-9814-a483e712c519.png)

![image](https://user-images.githubusercontent.com/10995998/27446036-5e5d26c0-577c-11e7-8d5e-6396da2b8a40.png)

![image](https://user-images.githubusercontent.com/10995998/27446059-7779c924-577c-11e7-8a83-bcfdf1c48399.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.67
Spyware filter | 1.0.12.90
Social media filter | 1.0.20.70
Annoyances filter | 1.0.14.47
German filter | 1.0.35.11
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.51

**Comment by seanl-adg** [comment]
Fixed

**Comment by danidoedel** [comment]
@seanl-adg There is still some whatsapp newsletter leftover stuff and ad leftover at the top and near the end of the page I must have missed:

![image](https://user-images.githubusercontent.com/10995998/27734328-ac7663f2-5d9a-11e7-88f3-999ab3e602b9.png)

![image](https://user-images.githubusercontent.com/10995998/27734344-bbf42850-5d9a-11e7-912e-5cac1906c853.png)
