### ISSUE TITLE
wetter.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5442]
***Site***: http://www.wetter.de/
***Description***: Ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27446180-ebceeaca-577c-11e7-937f-d1a2794f06cb.png)

![image](https://user-images.githubusercontent.com/10995998/27446194-fad54924-577c-11e7-81f8-f5ba6185c2ba.png)

**http://www.wetter.de/deutschland/wetter-bayreuth-18227064/wetterbericht-aktuell.html:**

![image](https://user-images.githubusercontent.com/10995998/27446241-22db2632-577d-11e7-933b-aca381745d16.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.67
Spyware filter | 1.0.12.90
Social media filter | 1.0.20.70
Annoyances filter | 1.0.14.47
German filter | 1.0.35.11
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.51

**Comment by seanl-adg** [comment]
Fixed
