### ISSUE TITLE
wetteronline.de - Social widget - Ad leftover - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5443]
***Site***: http://www.wetteronline.de/
***Description***: Ad leftover at the top. Social widgets at the left side. Newsletter form.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27446322-6baec4f4-577d-11e7-9cfc-6aef6830c170.png)

![image](https://user-images.githubusercontent.com/10995998/27446351-7dd554c2-577d-11e7-9702-e91e82d8477e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.67
Spyware filter | 1.0.12.90
Social media filter | 1.0.20.70
Annoyances filter | 1.0.14.47
German filter | 1.0.35.11
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.51

**Comment by seanl-adg** [comment]
Fixed social widget at the left side. I'd rather let the top margin as is. To hide it, something like `#$##leftcontainer { top: 10px; }` should be applied. `#$##leftcontainer { top: 0px; }` makes the content stick to the top, which is not aesthetically good. I have to choose a suitable margin, but doing it looks too opinionated.
