### ISSUE TITLE
veteranstoday.com - Missed Ad, no Assistant

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5444]
http://www.veteranstoday.com/2017/06/22/my-attorneys-demand-letter-to-bnai-brith-re-holocaust-denial-libel/

Missed ad in the right part of the website.
Assistant is missing on this website. "Use Adguard Assistant" option is enabled.

<details><summary>Screenshot:</summary>

![screen shot 2017-06-22 at 9 16 49 pm](https://user-images.githubusercontent.com/27292111/27449370-dc2c64bc-5790-11e7-8a25-095aa6ce93a5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.2 / 1.4.1
Adguard driver (Windows): | WFP 
Adguard filters: | 1 2 3 4 5 14
Ticket ID : | 1527946

**Comment by Alex-302** [comment]
Blocked ads.
