### ISSUE TITLE
Проблема с московским wifi

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#5445]
Фильтры по-умолчанию, версия 2.9.7.0, HTTPS вкл, HTTP вкл, качественная Фильтрация.

**Comment by ministr91** [comment]
![screenshot_2017-06-22-16-35-43](https://user-images.githubusercontent.com/22351242/27450971-2af20426-5796-11e7-9b18-7a080d0a4ef7.png)

**Comment by ministr91** [comment]
HAR и HTTP запросов лог нужен?

**Comment by Alex-302** [comment]
лог запросов.
После ввода кода пускает?

**Comment by ministr91** [comment]
Какой лог запросов? HTTP? В субботу только смогу кинуть
После ввода кода пускает

**Comment by ministr91** [comment]
Может так правило кинешь, а я потом попробую?

**Comment by Alex-302** [comment]
> Какой лог запросов? HTTP?

да

> В приватной вкладке

да 


> Может так правило кинешь, а я потом попробую?
```
@@||wi-fi.ru^$urlblock
@@||vmet.ro^$urlblock
```
как по мне, так и с капчей норм.

**Comment by ministr91** [comment]
Какая разница между приватной вкладкой и обычной?
Капча мешает, зачем она нужна?

**Comment by Alex-302** [comment]
> Какая разница между приватной вкладкой и обычной?

в приватной нет закэшированных запросов и куки.

> Капча мешает, зачем она нужна?

4 символа ввести не самая большая проблема.

**Comment by ministr91** [comment]
Зачем вводить 4 символа, если можно их не вводить?

**Comment by ministr91** [comment]
@Alex-302, ты что-то добавлял в правило в обновлении по воздуху? Странно, но этой проблемы теперь нет. Я вошел в сеть как обычно. Проблема решилась сама собой?

**Comment by ministr91** [comment]
Как я понял, проблема возникает только 1 раз и после ввода капчи исчезает. Воспроизвести ее не могу, т.к. я уже вводил 1 раз капчу. Нужен другой телефон, чистый. Проблема с этим экраном ввода капчи есть, но воспроизвести ее нет возможности. Закрывай тему.

**Comment by Alex-302** [comment]
А можешь куки для страницы авторизации посмотреть, после ввода капчи? Если пишут проскую cookie, можно попробовать сымитировать.

**Comment by ministr91** [comment]
а как я посмотрю? У меня 1 раз всего такое было и после ввода капчи больше это окно не появлялось. Чтобы опять это окно было, нужен новый телефон с установленным adguard

**Comment by Alex-302** [comment]
В инкогнито тоже не появляется?

**Comment by ministr91** [comment]
нет. Поэтому я и не могу воспроизвести эту проблему на моем устройстве снова

**Comment by ministr91** [comment]
@Alex-302 , радуйся и открывай тему опять, проблема появилась 💃 Эта проблема появилась спустя 22 дня после того, как я ввел капчу.  Следующий раз эта проблема возникнет через 22 дня, так что оперативно проверить работает твое решение или нет я не смогу в ближайшее время. Расскажу как все произошло. Я спокойно подключится к wifi, увидел это окно и сразу решил сделать логи http://my-files.ru/9yib02 пятница, 14 июля,11:42 время московское. Решил отключить защиту adguard и посмотреть, появится ли окно капчи опять и оно появилось!!! Это невероятно, при отключенной защите появляется окно. Решил почистить кэш браузера - не помогло, это окно опять появилось. Логи сделаны, защита включена, 
я ввел капчу и полез в инет, но не все так просто как кажется - у меня появилась реклама. Я был в шоке, как же так, ее быть не должно. После рекламы, я спокойно зашел в инет. Логи рекламы сделать не стал, не подумал как-то. Лог выше, это лог этого окна ввода капчи и только. 
![screenshot_2017-07-14-11-42-32](https://user-images.githubusercontent.com/22351242/28230560-2e0ea9be-68f0-11e7-92a1-5f07cf2f5f0f.png)
![screenshot_2017-07-14-11-46-07](https://user-images.githubusercontent.com/22351242/28230586-45a38310-68f0-11e7-8a6f-343d155c26be.png)
![screenshot_2017-07-14-11-46-11](https://user-images.githubusercontent.com/22351242/28230600-4c446036-68f0-11e7-9a3c-bd9fd1283c3d.png)

**Comment by ministr91** [comment]
@Alex-302, @ameshkov, есть кто?

**Comment by ministr91** [comment]
Вот это окно http://auth.wi-fi.ru/auto_auth?segment=metro

**Comment by ameshkov** [comment]
@ministr91 так у тебя кроме Adguard что-нибудь стоит?

**Comment by Alex-302** [comment]
HAR бы глянуть, может изменилось что-то. По ссылке рекламу не вижу, может только внутри сети показывают.

**Comment by ministr91** [comment]
@ameshkov нет.
@Alex-302 у меня тоже уже нет рекламы, но она была. HAR и лог запросов есть по ссылке выше. Я же кинул ее - это лог этого окна, лога рекламы нет

**Comment by ministr91** [comment]
Может стоит избавиться от того окна капчи? Можно мне правило для этого? Я кинул логи, правило изменилось или подходит это? 
@@||wi-fi.ru^$urlblock
@@||vmet.ro^$urlblock

**Comment by ministr91** [comment]
может тему то откроете? Проблема есть и ее надо решать. Для начала проблема с вводом капчи

**Comment by Alex-302** [comment]
Ну ввести четыре символа не большая проблема.
Когда появится капча, не переходи дальше, а для проверки добавь такие правила:
```
@@||ads.adfox.ru/220463/getDefaultImage?p1=$domain=auth.wi-fi.ru
@@||banners.adfox.ru/transparent.gif$domain=auth.wi-fi.ru
@@||top-fwz1.mail.ru/counter?id=701848$domain=auth.wi-fi.ru
@@||cstream.wi-fi.ru/csc-event?p=$domain=auth.wi-fi.ru
```

**Comment by ministr91** [comment]
Хорошо, смогу проверить когда появится это окно снова

**Comment by ministr91** [comment]
тему то может откроешь? Проблема с капчей есть и вон скрины рекламы кидал...

**Comment by ministr91** [comment]
Не помогает, опять эта капча и вместе с ней реклама дезодоранта. Правила не помогают
![screenshot_2017-08-04-09-52-09](https://user-images.githubusercontent.com/22351242/28957510-d12734da-78fa-11e7-9e82-52bb787267d2.png)

**Comment by Alex-302** [comment]
Ты ходишь по ссылке, которая всегда к капче ведёт.
Сюда ходи
http://auth.wi-fi.ru/auth

**Comment by ministr91** [comment]
Нет, почему? Я все правильно иду. Сайт не метро вообще. Я потом видео сниму

**Comment by ministr91** [comment]
Короче, через 17 дней будет видео. Эта проблема каждые 20 дней, так что придется ждать

**Comment by ministr91** [comment]
http://my-files.ru/cvw46b
Ну что же @Alex-302 , вот и настал тот момент, когда больше игнорировать проблему нельзя. Всевозможные логи, видео я прислал и теперь нужно решить проблему.

**Comment by Alex-302** [comment]
Раз в месяц - это не проблема.
У тебя сохранились логи попыток открыть сайты, когда видео записывал?

**Comment by ministr91** [comment]
Очень большая проблема.
http://my-files.ru/9yib02 пятница, 14 июля,11:42 время московское.

**Comment by ministr91** [comment]
Пока все работает, проблем не было. Может проблема сама решилась?

**Comment by ministr91** [comment]
@Alex-302 , что скажешь? 
@ameshkov

**Comment by ministr91** [comment]
@Alex-302, опять с метром проблема. Реклама показывается

**Comment by ministr91** [comment]
На это раз реклама, а не капча

**Comment by ministr91** [comment]
На 4пда жалоб много про это и вот теперь я столкнулся

**Comment by ministr91** [comment]
6 дней прошло, вай фай так и не исправили. При попытке входа кнопка войти горит серым цветом, нажать нельзя. Выключил защиту и все норм с просмотр. рекламы войти можно. Проблема существует уже давно, столько было написано на 4пда, я еще тут пишу и ничего

**Comment by ministr91** [comment]
Хоть бы написал, что предоставить надо, какие логи опять

**Comment by ministr91** [comment]
@Alex-302, @ameshkov

**Comment by Alex-302** [comment]
Логи, HAR.
Только удаляй старые логи и хары перез зиписью нового. После удаления нужно перезапустить защиту.
Желательно два варианта - сначала с Адгардом, потом `без фильтров`. Для каждой попытки нужно указать время.
