### ISSUE TITLE
weather.com - Ad leftover - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5446]
***Site***: https://weather.com/de-DE
***Description***: Ad leftover at the top and above right sidebar. Facebook overlay blocks content.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27454234-87cf4520-5799-11e7-846b-4371bc8c5603.png)

**https://weather.com/de-DE/wetter/deutschland/news/unwetter-ticker-wetterchaos-in-norddeutschland-ausnahmezustand-in-berlin:**

![image](https://user-images.githubusercontent.com/10995998/27454271-a589a4e8-5799-11e7-83ed-a446ac0cd14a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.67
Spyware filter | 1.0.12.90
Social media filter | 1.0.20.70
Annoyances filter | 1.0.14.47
German filter | 1.0.35.11
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.51

**Comment by seanl-adg** [comment]
The ad leftover at the right sidebar in the first screenshot was not reproduced. Others are fixed.

**Comment by danidoedel** [comment]
Can't reproduce it now too, so everything is fine 👍
