### ISSUE TITLE
zhihu.com - missed ad on page 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5448]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://www.zhihu.com/question/61235998/answer/185699818?utm_campaign=weeklydigest261&utm_source=weekly-digest&utm_medium=email 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/23372054/27477643-6e45439e-5815-11e7-8937-cb789715a94e.png)

</details>

***System configuration***

Application version: 1.2.1.75

Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.9.17 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.12.70 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.32 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.13.91 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.71 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.47 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.81.60 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.74.82 Enabled=NO
Ticket ID: 530630

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I don't understand - is ad two strings at the bottom or green selection?

**Comment by Alex-302** [comment]
@dzamyshlyayeva

**Comment by dzamyshlyayeva** [comment]
both of them

**Comment by Alex-302** [comment]
I can't recognize that ads. Are they paid articles?

**Comment by dzamyshlyayeva** [comment]
seems like free

**Comment by Alex-302** [comment]
Please ask again about ads. Also I need new screenshot with marked ads,

**Comment by dzamyshlyayeva** [comment]
asked the user
