### ISSUE TITLE
donnerwetter.de - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5449]
***Site***: http://www.donnerwetter.de/wetter/berlin/DE14356.html
***Description***: Social widget leftover above right sidebar. Ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27479483-63f68dea-5814-11e7-8fd3-62a3ec567e98.png)

![image](https://user-images.githubusercontent.com/10995998/27479490-6a475490-5814-11e7-8d7d-d6be57f9151f.png)

**http://www.donnerwetter.de/:**

![image](https://user-images.githubusercontent.com/10995998/27479532-94e58992-5814-11e7-90c2-2b5d30d6c145.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.73
Spyware filter | 1.0.12.92
Social media filter | 1.0.20.71
Annoyances filter | 1.0.14.49
German filter | 1.0.35.13
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.51

**Comment by Alex-302** [comment]
fixed

**Comment by danidoedel** [comment]
@Alex-302 There is some ad leftover missing, everything else is perfect: 

![image](https://user-images.githubusercontent.com/10995998/27733978-23f2a5c8-5d99-11e7-8a75-e0f683eff534.png)
