### ISSUE TITLE
kotaku.com - Annoyance - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5450]
***Site***: http://kotaku.com/
***Description***: Adblock detection. Newsletter form.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27479620-e7f7a82c-5814-11e7-995a-cdf17700ee5c.png)

![image](https://user-images.githubusercontent.com/10995998/27479654-0dbff550-5815-11e7-9263-f0f4f5c6afa1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.73
Spyware filter | 1.0.12.92
Social media filter | 1.0.20.71
Annoyances filter | 1.0.14.49
German filter | 1.0.35.13
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.51

**Comment by seanl-adg** [comment]
Fixed

**Comment by danidoedel** [comment]
@seanl-adg What's with the newsletter form?

**Comment by seanl-adg** [comment]
Fixed
