### ISSUE TITLE
deviantart.com - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5451]
***Site***: http://www.deviantart.com/
***Description***: Social widget leftover and ad leftover.

<details>
<summary>Screenshot</summary>

**http://www.deviantart.com/newest/?section=&global=1&q=ios&offset=0:**

![image](https://user-images.githubusercontent.com/10995998/27479787-9aa25170-5815-11e7-921e-611493ae7dba.png)

**http://www.deviantart.com/art/Internet-Movie-Database-web-Icon-mini-688171943:**

![image](https://user-images.githubusercontent.com/10995998/27479807-b2928af2-5815-11e7-9fd7-ca300d211c83.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.73
Spyware filter | 1.0.12.92
Social media filter | 1.0.20.71
Annoyances filter | 1.0.14.49
German filter | 1.0.35.13
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.51

**Comment by seanl-adg** [comment]
Fixed the second page. The issue with the first page was not reproduced.

**Comment by danidoedel** [comment]
@seanl-adg `deviantart.com##.ad-container` does fix the first problem. 

As there are `###ad-container`, `###Ad-Container` and `##.Ad-Container` generic rules in the filter, shouldn't there be `##.ad-container` too?

**Comment by seanl-adg** [comment]
Added.

**Comment by danidoedel** [comment]
Sure, I was just wondering ;)
