### ISSUE TITLE
benetton.com - Social widget - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5452]
***Site***: https://de.benetton.com/
***Description***: Social buttons partly blocked, either unblock them or block the rest. Cookie notice at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27481222-d3637fba-581b-11e7-929d-70ca61c94037.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.73
Spyware filter | 1.0.12.92
Social media filter | 1.0.20.71
Annoyances filter | 1.0.14.49
German filter | 1.0.35.13
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.51

**Comment by seanl-adg** [comment]
Fixed
