### ISSUE TITLE
BlockAdblock script on adpop.me/URKT

### ISSUE THREAD

**Issue by Mav3r1x** [AdguardTeam/AdguardFilters#5453]
Website: adpop.me/URKT

Issue: Can someone figure out how to bypass blockadblock script on this site?

**Comment by seanl-adg** [comment]
Fixed

**Comment by Mav3r1x** [comment]
Thanks. Btw can you tell me how did you do this? I mean what's the $$script you used?

**Comment by Alex-302** [comment]
It was fixed by exclusion
![image](https://user-images.githubusercontent.com/8361299/27491550-8ddac00e-584b-11e7-9d68-ad4138cb15b0.png)

**Comment by seanl-adg** [comment]
It didn't use `$$script` rule. Instead of filtering out an inline script, we unblocked certain element which the blockadblock's inline script tests. It makes a dummy page element with advertisement-looking properties. We prefer this way because $$ rules are not supported on all platform.
