### ISSUE TITLE
csgosquad.com - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5454]
***Site***: https://csgosquad.com/
***Description***: Ad background and ads

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27484737-9f1cd5d0-582a-11e7-92be-0f6df945f123.png)

![image](https://user-images.githubusercontent.com/10995998/27484746-ab6216f2-582a-11e7-9971-959dfd4176ec.png)

**https://csgosquad.com/player/76561197988627193:**

![image](https://user-images.githubusercontent.com/10995998/27484835-f3e043b8-582a-11e7-98fe-32a90a6357cf.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.74
Spyware filter | 1.0.12.92
Social media filter | 1.0.20.72
Annoyances filter | 1.0.14.50
German filter | 1.0.35.13
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.51

**Comment by seanl-adg** [comment]
Fixed

**Comment by danidoedel** [comment]
@seanl-adg There is still an ad:

![image](https://user-images.githubusercontent.com/10995998/27512729-3e2f09f6-594b-11e7-9080-320ecd6cde86.png)

**Comment by danidoedel** [comment]
@AdamWr Maybe you have the time to look into this ;)
