### ISSUE TITLE
csgo-stats.net - Social widget - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5455]
***Site***: https://csgo-stats.net/player/~76561197988627193
***Description***: Ad. Social share leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27484986-5f4b5caa-582b-11e7-867a-8602f1186281.png)

![image](https://user-images.githubusercontent.com/10995998/27485055-8eb7a6b0-582b-11e7-92ea-36cc497adee1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.74
Spyware filter | 1.0.12.92
Social media filter | 1.0.20.72
Annoyances filter | 1.0.14.50
German filter | 1.0.35.13
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.5176
Safari filter | 1.0.3.51

**Comment by AdamWr** [comment]
Fixed.
