### ISSUE TITLE
Does user filter have the highest priority?

### ISSUE THREAD

**Issue by pguliaiev-syp** [AdguardTeam/AdguardFilters#5456]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

When user adds his own filtering rule (@@||play.tv3.lt$document) for this website: http://play.tv3.lt/programos/sviesoforas/850561?autostart=true, it doesn't work with enabled EasyList Lithuana filter. And he asked about filters priority. What filter has the higher priority?

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1
Adguard filters: | User filter, Easylist  Lithuania

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
> Does user filter have the highest priority?

No.
User should to use it with $important modifier, because another document-level exclusion is exists in the filter - `@@||play.tv3.lt^$generichide`
```
@@||play.tv3.lt$document,important
```

**Comment by Alex-302** [comment]
Or, user can disable that rule in filters editor.

**Comment by linaspasv** [comment]
@Alex-302 I did somehow miss on ``$important`` modifier. It seems to work! 

Why is the following modifier not being added by default when adguard exception is being auto-generated through the browser extension? It would be really handy and make sense to have a possibility to completely whitelist a webpage out of the box (other browser based plugins do not have this problem at all).

**Comment by Alex-302** [comment]
@pguliaiev-syp Hi
I am aggree with you.
You can create feature request about it
https://github.com/AdguardTeam/AdguardAssistant/issues
