### ISSUE TITLE
Ads in the CalcKit app 

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5457]
***Description***:
* **Current behaviour**: 

Ads in the CalcKit app on Android

![screen shot 2017-06-23 at 5 59 33 pm](https://user-images.githubusercontent.com/27874000/27487888-c847e860-583d-11e7-9223-b0b5c910ba50.png)

***Steps to reproduce the problem***:

link on Google Play: https://play.google.com/store/apps/details?id=com.ivanGavrilov.CalcKit&hl=en

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On 
Adguard filters: | Английский
Фильтр счетчиков и систем аналитики
Фильтр виджетов соц сетей
Фильтр раздражителей
Русский
Фильтр мобильной рекламы
Ticket ID: 1579123

**Comment by Alex-302** [comment]
Fixed
