### ISSUE TITLE
Ads on http://gaming-resource.3dn.ru/

### ISSUE THREAD

**Issue by theerhan** [AdguardTeam/AdguardFilters#54577]
Ads downloads from http://qgpqq.abtr4all.com/c/e4c8b34d524daca0
Ads on PC,firefox latest version adguard extension
Screenshot https://imgur.com/a/9Cbsngj

Adguard configuration screenshot -https://imgur.com/a/XQXta7R

**Comment by BlazDT** [comment]
Update available in about 3 hours in Russian filter.
