### ISSUE TITLE
sapixcraft.com антиадблок

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#54585]
На любой из страниц этого сайта всплывает сообщение с просьбой отключить адблок без возможности закрыть.. 
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/19754243/80581047-db32c680-8a0c-11ea-8c60-e85963e5be65.png)
</details><br/>

**Comment by zloyden** [comment]
Поправил, обновление прилетит через 2-3 часа. В будущем отправляйте репорт через помощник или по этой [ссылке](http://agrd.io/report), потому что указывается необходимая конфигурация.
