### ISSUE TITLE
Ads on: www.m24.ru

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5458]
***Description***:
* **Current behaviour**: 

Ads on http://www.m24.ru

![screen shot 2017-06-23 at 6 37 38 pm](https://user-images.githubusercontent.com/27874000/27489396-155003fe-5843-11e7-969c-beef6763bd87.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | TDI
Adguard filters: | Russian, English, Dutch, Liste FR, Adblock polskie reguły 
Ticket ID: | 1118755

**Comment by Alex-302** [comment]
Fixed
