### ISSUE TITLE
ich-tanke.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5460]
***Site***: https://ich-tanke.de/
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27501450-ad22e6f4-586d-11e7-9336-da85cc5202f5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.74
Spyware filter | 1.0.12.92
Social media filter | 1.0.20.72
Annoyances filter | 1.0.14.50
German filter | 1.0.35.13
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.51

**Comment by Alex-302** [comment]
Added to German filter
```
ich-tanke.de##.box-partner
```
