### ISSUE TITLE
tanke-guenstig.de - Ad leftover - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5461]
***Site***: https://www.tanke-guenstig.de/
***Description***: Ad leftover and newsletter box.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27501504-1e6614d0-586e-11e7-94e4-a5d23e750578.png)

**https://www.tanke-guenstig.de/Rund-ums-Auto/Motoroel:**

![image](https://user-images.githubusercontent.com/10995998/27501525-3fdba436-586e-11e7-9be7-72673b30b451.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.74
Spyware filter | 1.0.12.92
Social media filter | 1.0.20.72
Annoyances filter | 1.0.14.50
German filter | 1.0.35.13
Mobile ads filter | 1.0.8.76
Safari filter | 1.0.3.51

**Comment by AdamWr** [comment]
Fixed.
