### ISSUE TITLE
analytics.plaid.com

### ISSUE THREAD

**Issue by rodaimi** [AdguardTeam/AdguardFilters#54626]
This domain is found when adding bank accounts to the p2p payments app cashapp. Note that there's no visible page, but this domain resolves to AWS IP addresses

**Comment by Alex-302** [comment]
@rodaimi is not it a part of fraud protection?

**Comment by rodaimi** [comment]
@Alex-302 analytics.plaid.com is a tracking domain for plaid.com It is not fraudulent, but collects alot of data.
 
plaid.com provides an API for developers who want to link a user's bank account to their platform. It's commonly used here in the US for e-billing and mobile debit payments between two bank accounts. Therefore, only analytics.plaid.com should be blocked

**Comment by Alex-302** [comment]
@rodaimi Do you use this system? Can you check transaction with blocked `analytics.plaid.com` in User Rules?

**Comment by rodaimi** [comment]
I have verified that a user rule blocking this domain doesn't affect transactions.

Thank You,
Remi

On May 6, 2020, at 6:40 AM, Alex <notifications@github.com> wrote:

﻿

@rodaimi<https://github.com/rodaimi> Do you use this system? Can you check transaction with blocked analytics.plaid.com in User Rules?
