### ISSUE TITLE
Videos on video.rambler.ru don't play 

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#5462]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Videos on video.rambler.ru don't play (disabling filters one by one and disabling Ad Blocker didn't help)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/17320558/27503829-f3b13146-5888-11e7-9096-7dc67cb24da5.png)

</details>

***Steps to reproduce the problem***:

https://video.rambler.ru/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | User, English, Russian, Annoyances, Spyware, Social media, Safari
Ticket ID (if exists): | 857681

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
