### ISSUE TITLE
ren.tv - missed ad

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5464]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Missed ad on the page http://ren.tv/novosti/2017-06-24/video-eksperty-izuchayut-obnaruzhennuyu-na-lune-drevnyuyu-piramidu

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29478021/27507605-44ad350c-58db-11e7-8713-ee82eb45f97d.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)
</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.2.1
Simplified filters(iOS) | Off
Adguard DNS: |  Default 
Ticket ID (if exists): | 1579941
Adguard filters: | English, Spyware, Social media, Russian, Safari 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not an ad.
Added to Annoyances filter
```
ren.tv###box-view-wrapper
```
