### ISSUE TITLE
wikia.com - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5466]
***Site***: http://de.masseffect.wikia.com/wiki/Mass_Effect_Wiki
***Description***: Ads

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27508769-efed9ca2-58ec-11e7-96c0-a4f6d136f439.png)

![image](https://user-images.githubusercontent.com/10995998/27508788-6e38bfd8-58ed-11e7-94fb-d631f89cbfc7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.91
Spyware filter | 1.0.12.95
Social media filter | 1.0.20.74
Annoyances filter | 1.0.14.57
German filter | 1.0.35.14
Mobile ads filter | 1.0.8.77
Safari filter | 1.0.3.51

**Comment by Alex-302** [comment]
Not reproduced(now)

**Comment by danidoedel** [comment]
@Alex-302 Hmm I can still see the ad:

![image](https://user-images.githubusercontent.com/10995998/27641840-557ccc40-5c1d-11e7-94e8-27caae5377f0.png)

HAR if that helps:

[de.masseffect.wikia.com.zip](https://github.com/AdguardTeam/AdguardFilters/files/1108981/de.masseffect.wikia.com.zip)

**Comment by danidoedel** [comment]
de36d45e0d8b1ebff63bbf35acd94e277388e50b did fix it
