### ISSUE TITLE
minecraft.gamepedia.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5467]
***Site***: http://minecraft-de.gamepedia.com/Kreativmodus
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27508823-f7be7fae-58ed-11e7-8161-fd3d7084fdb8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.91
Spyware filter | 1.0.12.95
Social media filter | 1.0.20.74
Annoyances filter | 1.0.14.57
German filter | 1.0.35.14
Mobile ads filter | 1.0.8.77
Safari filter | 1.0.3.51

**Comment by AdamWr** [comment]
Fixed.
