### ISSUE TITLE
washingtonpost.com - Social widget - Ad leftover - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5468]
***Site***: https://www.washingtonpost.com/
***Description***: Ad leftover. Sharebar leftover. Ad articles on main page.

<details>
<summary>Screenshot</summary>

**https://www.washingtonpost.com/graphics/2017/world/national-security/obama-putin-election-hacking/?utm_term=.12a31b9dd507&hpid=hp_hp-top-table-main_russiaobama-banner-7a%3Ahomepage%2Fstory:**

![image](https://user-images.githubusercontent.com/10995998/27508844-7e184b16-58ee-11e7-81a7-d3587f528aab.png)

![image](https://user-images.githubusercontent.com/10995998/27508855-af31c448-58ee-11e7-86f3-db22cf8b09e2.png)

**https://www.washingtonpost.com/:**

![image](https://user-images.githubusercontent.com/10995998/27508864-f2e6d2e6-58ee-11e7-8be5-e4292a97baaf.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.91
Spyware filter | 1.0.12.95
Social media filter | 1.0.20.74
Annoyances filter | 1.0.14.57
German filter | 1.0.35.14
Mobile ads filter | 1.0.8.77
Safari filter | 1.0.3.51

**Comment by AdamWr** [comment]
Fixed.
