### ISSUE TITLE
freetutorials.us - Ad leftover - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5469]
***Site***: https://www.freetutorials.us/
***Description***: Adblock detection. Ad leftover in right sidebar below search box.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27508874-725f2aa0-58ef-11e7-9ddc-a61e8296d96f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.91
Spyware filter | 1.0.12.95
Social media filter | 1.0.20.74
Annoyances filter | 1.0.14.57
German filter | 1.0.35.14
Mobile ads filter | 1.0.8.77
Safari filter | 1.0.3.51

**Comment by seanl-adg** [comment]
Not reproduced, but please check if adding the following filter helps:
`freetutorials.us#$#.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links {display:block!important;}`

**Comment by danidoedel** [comment]
@seanl-adg Yes, that rule fixed the adblock detection :)

**Comment by AdamWr** [comment]
Fixed.
