### ISSUE TITLE
An ad pop-up on xeny.org

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5470]
***Description***:
* **Current behaviour**: 
There is an ad pop-up on:
https://xeny.org/trk/click.php?key=s4scfubjrw99x8q3ewts&cid=ru&rid=vse
Reproduced on our side

<summary>Screenshot:</summary>
<details>

<img width="2048" alt="screen shot 2017-06-25 at 1 26 38 am" src="https://user-images.githubusercontent.com/28784344/27512404-42d6b9d0-5947-11e7-87ce-b2258a9c2717.png">

</details>

***Steps to reproduce the problem***:

Go on:
https://xeny.org/trk/click.php?key=s4scfubjrw99x8q3ewts&cid=ru&rid=vse

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | 6.1.331.1732
Adguard driver (Windows): |  TDI
Adguard DNS: | None 
Adguard filters: | 2, 3, 14, 10, 1 ,0
Ticket ID (if exists): | 751110

**Comment by Alex-302** [comment]
Эта страница - элемент рекламы, дальше на Вулкан перекидывает.
