### ISSUE TITLE
kirmiziturkmedya.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#54701]
@Zarthes commented on [Thu Apr 30 2020](https://github.com/AdguardTeam/AdguardForiOS/issues/1545)

Hello,
When I go to https://www.kirmiziturkmedya.com/forum/f23/ 
It detects adguard and doesn’t let me go
Edit: It takes 5-10 sec to recognises adguard then block appears
![1F9413FA-B06A-45AE-96DC-09F19D415458](https://user-images.githubusercontent.com/56041562/80727581-8e371900-8b0e-11ea-8ff1-9750e55fdbff.png)

**Comment by Zarthes** [comment]
@Alex-302 Hello Alex I hope you are having a good day, I just checked website with updated filters after I saw you put resolved label from Mac & iOS but website still detects Adguard, 
Not: After 10-15 sec. website detects Adguard, not instantly, So please wait a few seconds scroll down or up it will warn Adblocker detected

**Comment by Alex-302** [comment]
@Zarthes I cannot reproduce now.
@AdamWr @BlazDT please take a look.

@ublock-user where you found `.logoyanireklam`?

**Comment by Zarthes** [comment]
@Alex-302 dear Alex thank you for taking time, it’s been few days after u updated filters it works fine on my ios and mac

**Comment by Alex-302** [comment]
Ok, thanks for reply.
