### ISSUE TITLE
click.promotion.flyscoot.com incorrect blocking

### ISSUE THREAD

**Issue by liyinsg** [AdguardTeam/AdguardFilters#54718]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
click.promotion.flyscoot.com is been wrongly blocked by rule of exacttarget.com. The link points to a refund page of an airline website.

**Filters:**
https://filters.adtidy.org/extension/chromium/filters/15.txt

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
AdGuard DNS:                           | Default

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #324](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/324) via [**ZenHub**](https://www.zenhub.com/)
