### ISSUE TITLE
theatlantic.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5472]
***Site***: https://www.theatlantic.com/world/
***Description***: Cookie notice at the top. Newsletter form. Newsletter and subscription stuff in footer.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27512641-f920f426-5947-11e7-9ca3-cf3c693e818b.png)

![image](https://user-images.githubusercontent.com/10995998/27512646-048aad3e-5948-11e7-97ad-efbbc923448f.png)

![image](https://user-images.githubusercontent.com/10995998/27512654-49d72bba-5948-11e7-808b-a406ce3a401e.png)

**https://www.theatlantic.com/international/archive/2017/06/al-jazeera-qatar-saudi-arabia-muslim-brotherhood/531471/:**

![image](https://user-images.githubusercontent.com/10995998/27512653-2089149e-5948-11e7-81e6-4cdf1659d543.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.22.91
Spyware filter | 1.0.12.95
Social media filter | 1.0.20.74
Annoyances filter | 1.0.14.57
German filter | 1.0.35.14
Mobile ads filter | 1.0.8.77
Safari filter | 1.0.3.51

**Comment by AdamWr** [comment]
Fixed.
