### ISSUE TITLE
nl.vv.fietsknoop

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#54758]
***Description***:
* **Current behaviour**: 

App displays an ERR_NAME_NOT_RESOLVES error instead of displaying actual content when AdGuard is enabled.

<details><summary>Screenshot:</summary>
![Screenshot_20200427-145857](https://user-images.githubusercontent.com/33634917/80870133-2ec33f80-8cad-11ea-924d-bd1c647b6c4a.png)

</details><br/>

***Steps to reproduce the problem***:

1. Enable AdGuard, try to open the app

***System configuration & debug logs***

See ticket 2659614 for debug logs.

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 9
Browser:                               | N/A
AdGuard version:                       | 3.3.231
Filters enabled:                       | "Filter voor mobiele advertenties", "Spyware filter", "Filter tegen irritante elementen", "Nederlands filter", "Engels filter", "Sociale media filter"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default mode)
AdGuard DNS:                           | AdGuard Default, DoH
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | 2659614

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Cannot be fixed. Ads are loaded using google services app.
