### ISSUE TITLE
watchfree.to - no assistant

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#5477]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

There is no Assistant on this website and our customer is facing annoying pop-ups on this website.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screen shot 2017-06-25 at 3 42 25 am](https://user-images.githubusercontent.com/17320558/27512838-57b86cac-5958-11e7-894b-b6a1a0672831.png)

</details>

***Steps to reproduce the problem***:

http://www.watchfree.to/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.1.331/1.4.1
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | Off
Adguard filters: | User, English, Russian, Annoyances, Spyware, Social media, Safari.
Ticket ID (if exists): | 1164870

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardAssistant/issues/73
