### ISSUE TITLE
XMovies8.ru - anti adblock script

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#5478]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Anti adblock script.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/17320558/27517555-52709dbc-59d7-11e7-8c8f-87affcdd42b7.png)

</details>

***Steps to reproduce the problem***:

https://xmovies8.ru/movie/the-bad-batch-2016/watching.html

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | User, English, Russian, Annoyances, Spyware, Social, Safari
Ticket ID (if exists): | 547934

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
