### ISSUE TITLE
Ads in Textra app 

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardFilters#5479]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
Ads in Textra app 
https://play.google.com/store/apps/details?id=com.textra&hl=tr

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/25711093/27518510-44ffb11e-59ea-11e7-8bd7-734508a5c6be.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | 2, 3, 4, 13, 11, 211
Ticket ID (if exists): | 1542146

[debug (28).txt](https://github.com/AdguardTeam/AdguardFilters/files/1100517/debug.28.txt)
[state (42).txt](https://github.com/AdguardTeam/AdguardFilters/files/1100518/state.42.txt)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Maybe filtering is disabled by default for this app.

**Comment by Michael23456** [comment]
it looks like it is, it was disabled in the filtered apps. will inform the customer, in this issue https://github.com/AdguardTeam/AdguardFilters/issues/1080
was mentioned that it could cause MMS issues. Will ask the customer to test it. Thanks
