### ISSUE TITLE
opodo.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5482]
***Site***: http://www.opodo.de/
***Description***: App banner at the top.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27519243-b43e2222-59ef-11e7-9af8-0cfcbf012c33.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23
Spyware filter | 1.0.12.95
Social media filter | 1.0.20.74
Annoyances filter | 1.0.14.57
German filter | 1.0.35.14
Mobile ads filter | 1.0.8.77
Safari filter | 1.0.3.51

**Comment by danidoedel** [comment]
Rules:
```
opodo.de###appLayer
opodo.de###new_app_layer
```

**Comment by danidoedel** [comment]
Anyone? @AdamWr @Alex-302 @seanl-adg

**Comment by AdamWr** [comment]
Added:
`opodo.de###new_app_layer`
`opodo.de###smart-banner`
`opodo.de###app-layer`
