### ISSUE TITLE
livejournal.com - Taking too long to respond when protection is enabled

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#54837]
***Description***:
* **Current behaviour**: 

For about a week or so my browsers
constantly get "This site can’t be reached scolaro.livejournal.com
took too long to respond." errors.

<details><summary>Screenshot:</summary>

Not available.
</details><br/>

***Steps to reproduce the problem***:

Enable protection.

***System configuration***

**Filters:**

Base, German

**Known user filter rules:**
@@||scolaro.livejournal.com^$important,document
@@||livejournal.com^$important,document
@@||opengapps.org^$important,document

**HAR**
Available in support ticket 2380712

Information                            | Value
---                                    | ---
Operating system:                      | Windows
Operating system version (Android/iOS) | Windows 10 v1903
Browser:                               | Chrome
AdGuard version:                       | 7.3
Filters enabled:                       | Base, German
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | 2380712

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/54102
