### ISSUE TITLE
Persian filter 1.0.0.25 blocks video playback on multiple sites

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5485]
> После обновления до версии 1.0.0.25
> фильтр ведёт себя ужасно и блочит всё,
> включая фото и видео (не запрещённый
> контент и не рекламу).

> Видео блокирует на всех ресурсах (видео плэятся, но не открываются, при переходе на ютуб показывает просто чёрный экран – на любое видео). Аватарки в ВК избирательно блокирует (рандомность по серверам). Правила-исключения не помогли.
> Проблема в браузерной версии.
> 

<details>

![screenshot6](https://user-images.githubusercontent.com/15856304/27530310-c2c3bb74-5a60-11e7-9df9-b43f3255f3d5.png)

![screenshot5](https://user-images.githubusercontent.com/15856304/27530328-dc56df8a-5a60-11e7-9a1c-07d14755dfb7.png)

**Comment by evgeniy-ADG** [comment]
Видео блокирует на всех ресурсах (видео плэятся, но не открываются, при переходе на ютуб показывает просто чёрный экран – на любое видео). Аватарки в ВК избирательно блокирует (рандомность по серверам). Правила-исключения не помогли.
Проблема в браузерной версии.

<details>

![screenshot6](https://user-images.githubusercontent.com/15856304/27530310-c2c3bb74-5a60-11e7-9df9-b43f3255f3d5.png)

**Comment by Alex-302** [comment]
Not reproduced. Both sites works fine.
I need screenshot of the filtering log - blocked requests only.

**Comment by jus7forfun** [comment]
Persian filter just became useless, almost every website doesn't work with it enabled. (videos images etc )

With "Adblock-Persian list" Filter enabled, many websites gets corrupt.

For example see twitter.com, Many elements are blocked because of this rule:

URL:https://pbs.twimg.com/media/DDIH-aNXgAIEgq1.jpg
Type:Image
Source:twitter.com
Rule:-
Filter: Adblock-Persian list

**Comment by Alex-302** [comment]
I don't know how to send a message to author. 
Rule:`-`
it is a reason of incorrect blocking.
I made this filter static, and removed invalid rules.
