### ISSUE TITLE
imore.com - Adg breaks website elements

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#5486]
https://www.imore.com

issues working with Adguard: some essential elements can’t bemclicked. Examples are the Menu on the top left corner & at the bottom of the page the “Show Me More” button.

Screen recording of the issue: https://www.dropbox.com/s/2v5bn3kz0ynipxi/Screen_recording_imore.mov?dl=0

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard filters: | 1 2 3 4 5 14

Ticket ID: 1010685

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by vozersky** [comment]
English filter is the culprit

**Comment by Alex-302** [comment]
https://forums.lanik.us/viewtopic.php?f=64&t=37288&sid=d9a46eb282e679532c4118d58435791c

**Comment by Alex-302** [comment]
Added to English filter
```
@@||imore.com/sites/imore.com/files/advagg_js/$script
```
