### ISSUE TITLE
Anti-adblocking measure on bild.de not handled by Adguard anymore

### ISSUE THREAD

**Issue by JayBrown** [AdguardTeam/AdguardFilters#5487]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: anti-adblocking script on bild.de redirects browser, and all you see is a blank page; used to work until yesterday (2017-06-25)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>
no screenshot necessary; it's just a blank page
</details>

* **Expected behaviour**: bild.de should load normally, without ads, without anti-adblocking redirects

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>
no screenshot necessary
</details>

***Steps to reproduce the problem***: just load bild.de and analyze the anti-adblocking measure

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | OS X 10.11.6
Browser: | Safari 10.1.1
Adguard version: | 1.4.1
Adguard DNS: | None
Adguard filters: | Adguard: English, Spyware, Social media, Annoyances, Russian, German, Japanese, French, Dutch, Dutch, Spanish/Portugese, Mobile Ads, Safari; EasyList: EasyList, EasyPrivacy, Fanboy's Social Blocking List, Fanboy's Annoyances, Adblock Polska, EasyList China, EasyList Czech & Slovak, EasyList Dutch, EasyList Germany, EasyList Italy, Icelandic ABP List, Liste AR, Liste FR, Norsk adblockliste, ROList, RU Adlist, void.gr, Fanboy's Enhanced Tracking List; Other: Adblock Warning Removal List, Adblock & uBlock polish filer, Adblock & uBlock plish cookies filter, Anti-Adblock Killer Reek, ChinaList+EasyList, CJX's Annoyance List, I don't care about cookies, Malware Domains, Peter Lowe's list, Prebake, RU Adlist: BitBlock, RU AdList: Counters, Spam404, Xfiles

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@JayBrown 
Please check:
```
@@||cdn1.smartadserver.com/diff/251/verify.js$domain=bild.de
@@||cdn1.smartadserver.com/diff/251/*$domain=bild.de
||code.bildstatic.de/*/min/targets/bild/default/packages/js/core.js$replace=/adClasses:\"[A-Za-z0-9;_-]*\"\,eleCSS/adClasses:""\,eleCSS/
```

**Comment by JayBrown** [comment]
Added these to my user filter, but it doesn't work. Still reroutes to blank page. Sorry.

**Comment by Alex-302** [comment]
You are using too mani filters. Please try to disable third-party filters for test:
`EasyList: EasyList, EasyPrivacy, Fanboy's Social Blocking List, Fanboy's Annoyances, Adblock Polska, EasyList China, EasyList Czech & Slovak, EasyList Dutch, EasyList Germany, EasyList Italy, Icelandic ABP List, Liste AR, Liste FR, Norsk adblockliste, ROList, RU Adlist, void.gr, Fanboy's Enhanced Tracking List; Other: Adblock Warning Removal List, Adblock & uBlock polish filer, Adblock & uBlock plish cookies filter, Anti-Adblock Killer Reek, ChinaList+EasyList, CJX's Annoyance List, I don't care about cookies, Malware Domains, Peter Lowe's list, Prebake, RU Adlist: BitBlock, RU AdList: Counters, Spam404, Xfiles`

**Comment by JayBrown** [comment]
That didn't help either; only ones active for the test were (by Adguard): English, Spyware, Social Media, Annoyances, German, Mobile Ads, Safari

**Comment by Alex-302** [comment]
Ok, please check for filters update after 90 minutes.
Or copy-paste these rules to custom filter:
```
@@||smartadserver.com/diff/251/*$domain=bild.de 
@@||smartadserver.com/diff/251/verify.js$domain=bild.de 
bild.de#@#.ads
bild.de#@#.cbErotikContentbar15
bild.de#@#.contentbar
bild.de#@#.eyecatcher
bild.de#@#.footerbar
bild.de#@#.fullbanner
bild.de#@#.jetzt_aufnehmen
bild.de#@#.rectangle
bild.de#@#.servicelinks
bild.de#@#.tea-rectangle
bild.de#@#.txe
bild.de#@#.yield
```

**Comment by JayBrown** [comment]
Will be at work; will test tonight.

**Comment by JayBrown** [comment]
Updated filters, and now it works! Thank you!
