### ISSUE TITLE
https://developers.google.com

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardFilters#54884]
https://developers.google.com/speed/pagespeed/insights/

example: https://i.imgur.com/UqDaUaQ.png

Please unblock it.

Adguard filters:
Adguard base
Adguard tracking
Adguard annoyance
Adguard dutch

**Comment by Alex-302** [comment]
What is wrong?

**Comment by worldsdream** [comment]
Clicking on analyze does not show anything. A message is showing thats it’s blocked. See the screenshot i attached.

**Comment by Alex-302** [comment]
It works on my end.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/81962809-f4e32900-961c-11ea-96bc-fe0a745896cf.png)

</details>

Is it caused by filters?
