### ISSUE TITLE
Anti-adblocker on m.bild.de

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5489]
***Description***:
* **Current behaviour**: 

m.bild.de detects Adblocker and prevents the user from seeing anything

![unnamed](https://user-images.githubusercontent.com/27874000/27547887-f971bfe2-5a9f-11e7-89c0-6a5df6718553.png)

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Chrome
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | English, Spyware, Social Media, Experimental, Mobile Ads, Annoyances
Ticket ID: | 1581333

**Comment by Alex-302** [comment]
It was fixed today.

**Comment by iverkhohliad** [comment]
![image](https://user-images.githubusercontent.com/31481372/32295372-c58a9ec6-bf51-11e7-8cbb-42e6d299b09a.png)


The issue repeated. I checked on my side with the most recent version - the same.

**Comment by Alex-302** [comment]
@iverkhohliad https://forum.adguard.com/index.php?threads/policy-on-adblock-walls.26022/
