### ISSUE TITLE
Ads in Meloman app

### ISSUE THREAD

**Issue by vmalyuta** [AdguardTeam/AdguardFilters#5490]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Ads in Meloman app

![img_1123](https://user-images.githubusercontent.com/23701680/27563211-0015a758-5ad9-11e7-8ffb-6e5574164986.jpg)

![image](%url_of_screenshot%)
</details>

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***
Application version: 1.2.1.71
OS: 10.2.1
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.22.96 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.95 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.74 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.14.57 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.53.7 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.77 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.51 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.81 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.82.67 Enabled=YES

Ticket ID (if exists): | 1580386

logs in the ticket 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@vmalyuta 
this?
https://itunes.apple.com/ru/app/meloman-great-player/id1210207476?mt=8

**Comment by Alex-302** [comment]
Не повторяется. После каких действий возникает реклама?

**Comment by Artemkiin** [comment]
Открытие приложения после закрытия (с погашением экрана и без), переключение вкладок, время от времени включается просто при использовании приложения.

**Comment by vmalyuta** [comment]
yes 
https://itunes.apple.com/ru/app/meloman-great-player/id1210207476?mt=8

**Comment by Alex-302** [comment]
@Artemkiin а можете закрыть приложение, вкл/выкл режим полёта(для сброса кэша DNS), повторить рекламу и отправиль лог в поддержку с указанием времени появления рекламы?

**Comment by Artemkiin** [comment]
Да, как только появится - отправлю. Пока реклама пропала, возможно из-за сброса кэша DNS, телефон до этого только перезагружал, в авиарежим не переводил.

**Comment by Artemkiin** [comment]
@Alex-302 отправил

**Comment by Alex-302** [comment]
@Artemkiin а куда? А оригинальной задаче ничего нового не вижу.

**Comment by Artemkiin** [comment]
@Alex-302 отправил лог в поддержку с указанием времени появления рекламы

**Comment by Alex-302** [comment]
@Artemkiin новый отправили или про старый пишете? Не пойму.

**Comment by Artemkiin** [comment]
@Alex-302 отправил новое сообщение об ошибке в техподдержку, после вашего комментария со сбросом кэша, указал время появления рекламы

**Comment by Alex-302** [comment]
@Artemkiin ок, гляну завтра.

**Comment by Alex-302** [comment]
Что-то найти не можем. Какой номер заявки?

**Comment by Artemkiin** [comment]
@Alex-302, есть только письмо автоответчика от 24 июня, в котором указано следующее:

Your personal helpdesk ID is: 1580386

На последующие отчеты об ошибке автоответчик писем не присылал(

**Comment by Alex-302** [comment]
Странно. Может письма не ушли? Попробуйте на свой личный ящик логи отправить.

**Comment by Artemkiin** [comment]
Попробовал. На личный ящик не пришли(

**Comment by Alex-302** [comment]
Наверное настройки почты на устройстве сбились. Перепроверьте их.

**Comment by Artemkiin** [comment]
Удалил и заново внёс учётную запись, отправил себе отчёт об ошибке - пришёл. Теперь буду ловить время, в которое появлялась реклама, как только насобираю достаточно случаев - отправлю лог в техподдержку  с указанием времени появления рекламы, продублирую время сюда и укажу номер, который придёт в ответ на мой отчёт об ошибке.

**Comment by Alex-302** [comment]
Ок, жду)

**Comment by Alex-302** [comment]
Ну что? Не повторилось?

**Comment by Artemkiin** [comment]
Я айфон разбил))))

26 июля 2017 г. 7:09 PM пользователь "Alex" <notifications@github.com>
написал:

**Comment by Alex-302** [comment]
Печаль. Показ закрою.

**Comment by Artemkiin** [comment]
Как куплю новый, снова буду тестить!) Спасибо!

29 сент. 2017 г. 3:52 PM пользователь "Alex" <notifications@github.com>
написал:
