### ISSUE TITLE
Advertisements Appear in Chrome but not Edge

### ISSUE THREAD

**Issue by YOWTechGuy** [AdguardTeam/AdguardFilters#5491]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

 Videos on the ctvnews.ca site display adds before starting in Google Chrome.  But using Microsoft Edge does not have behavior.  AdGuard successfully filters ads on the same site using Edge.

[//]: # (Опишите проблему)

 http://imgur.com/a/OoUWq

[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image]<blockquote class="imgur-embed-pub" lang="en" data-id="a/OoUWq"><a href="//imgur.com/OoUWq"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS / Android / Linux
Browser: | 
Adguard version: | 
Adguard driver (Windows): | WFP / TDI
Adguard mode (Android): | VPN / Proxy(manual/auto)
Filtering quality (Android): | High-quality / high-speed / simplified
HTTPS filtering (Android): |  On (Default/Blacklist mode) / Off
Simplified filters(iOS) | On / Off
Adguard DNS: | None / Default / Family Protection
Stealth mode options(Windows) | 
Adguard filters: | 
Ticket ID (if exists): | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Hi
Please provide direct url, **screen**shot and enabled filters.

**Comment by YOWTechGuy** [comment]
Hello,

I provided that information in my original GitHub post.  Curious why that is not visible to you.

Anyways, here is an example video.  http://www.ctvnews.ca/video?playlistId=1.3478923

That will have advertisements before the video starts in Google Chrome.  And no advertisements in Microsoft Egde.

This is the same for any video on the website www.ctvnews.ca<http://www.ctvnews.ca>

Thank You.

On Jun 27, 2017, at 6:11 AM, Alex <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi
Please provide direct url, screenshot and enabled filters.

**Comment by Alex-302** [comment]
Can't reproduce. Maybe English filter is not enabled in Adguard in Chrome.

**Comment by YOWTechGuy** [comment]
Ok try this instead.  Using Google Chrome, go to http://northernontario.ctvnews.ca/


Clicking on any video on that site produces advertisements first.  My english filter has been confirmed enabled.



________________________________

**Comment by Alex-302** [comment]
Try to reinstall extension, or try to disable all filters, except English. Also check whitelist for exclusions.
