### ISSUE TITLE
m.vz.ru - ads leftover

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5493]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Missed ad on the webpage https://m.vz.ru/

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screen shot 2017-06-27 at 11 39 35 am](https://user-images.githubusercontent.com/29478021/27578642-604245b0-5b2d-11e7-9893-1880249a4d03.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

</details>
***System configuration***

</details>

Information | value
--- | ---
Operating system: | iOS
Browser: | Sarafi
Adguard version: | 1.2.1
Simplified filters(iOS) | Off
Adguard DNS: |  Default 
Ticket ID (if exists): | 1550888
Adguard filters:  "User filter", "English filter" , "Spyware filter" , "Social media filter" , "Russian filter" ,"Safari filter" 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced on my device.

**Comment by zebrum** [comment]
me neither.
try to clear cache\cookies
