### ISSUE TITLE
English filter blocks adbar.fi, adbar.io (extension for Safari)

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5494]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
English filter blocks access to the websites www.adbar.fi, www.adbar.io (extension for Safari)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screenshot 2017-06-27 at 17 12 59](https://user-images.githubusercontent.com/29478021/27591961-f9616f5e-5b5b-11e7-8a7b-db93b3cf25e6.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Safari, extension v2.5.8
Adguard filters: | English, Russia, Annoyances, Social media, Spyware, 
Ticket ID (if exists): | 1581332

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.
http://imagizer.imageshack.com/img923/2325/pl8Xkr.png

**Comment by adbario** [comment]
Hi Alex,

English filter has a rule "/adbar." which blocks pages when there's no www at the beginning, so [http://adbar.io](http://adbar.io) will be blocked. Currently main domain adbar.fi is redirected to www so that seems to work, but we will take the www out soon so then it would be blocked too.

I found the filter rule from here:
[https://adguard.com/en/filter-rules.html?id=2](https://adguard.com/en/filter-rules.html?id=2)

Same rule is also found at EasyList filters:
[https://easylist.to/easylist/easylist.txt](https://easylist.to/easylist/easylist.txt)

Thanks!

**Comment by Alex-302** [comment]
Hi @adbario 
I can't reproduce even with http://adbar.io
That rule is loaded from Easylist.
Please check this rule
```
@@://adbar.io^|$domain=adbar.io
```

**Comment by adbario** [comment]
For me on Safari the url [http://adbar.io](http://adbar.io) gets blocked as seen on this screenshot. Only English and Safari filters are activated.

<img width="1015" alt="screen shot 2017-06-27 at 17 05 19" src="https://user-images.githubusercontent.com/22136575/27597640-dc7da91c-5b5a-11e7-9354-4d025441e77c.png">


If I apply your rule, everything works perfectly.

So do I need to get our domains whitelisted on EasyList and when it gets done, it automatically updates to your English filter? Or is there something you could do about this? We just really don't want our clients to be blocked out from our websites.

**Comment by Alex-302** [comment]
Added to English filter
```
@@://adbar.io^|$domain=adbar.io
@@://adbar.fi^|$domain=adbar.fi
```

**Comment by adbario** [comment]
Thanks for that. It seems to be platform specific whitelisting and I did a test with Chrome and Firefox extensions and also with Mac desktop app, they all seem to be blocking as well. So could our domains be whitelisted completely?

<img width="1191" alt="screen shot 2017-06-27 at 17 46 44" src="https://user-images.githubusercontent.com/22136575/27599492-d8d559bc-5b60-11e7-9454-bf1dd4aa16fc.png">

<img width="810" alt="screen shot 2017-06-27 at 17 54 34" src="https://user-images.githubusercontent.com/22136575/27599814-caa96a26-5b61-11e7-8578-2a142cccc57a.png">

Thanks!

**Comment by Alex-302** [comment]
It is triggered, but nothing is blocked.
I think, will be better, if you open new issue in Easylist repository, because that rule is loaded from Easylist to our English filter
https://github.com/easylist/easylist/issues/
they can change it to something like
```
/adbar.$domain=~adbar.io|~adbar.fi
```

**Comment by adbario** [comment]
I did an extra test [http://adbar.io/test.html](http://adbar.io/test.html)

There's an image linked to same server on that page, this image gets blocked with Safari, Chrome, Firefox and desktop app as well.

Image is added by code
```html
<img src="http://adbar.io/test.jpg" alt="Test image">
```

<img width="1197" alt="screen shot 2017-06-27 at 18 25 16" src="https://user-images.githubusercontent.com/22136575/27601133-145050d2-5b66-11e7-9dcb-5ff5b49b2354.png">

I will make a request for them to whitelist our domains, but could you also enable these with all platforms?

**Comment by Alex-302** [comment]
Yes. But Easylist users will not get this exclusions.
If you are related with these sites, I recommend to report to Easylist team.

**Comment by adbario** [comment]
Thanks Alex, I will let them know about this too. I really appreciate your help, and yes these are my domains.

**Comment by Alex-302** [comment]
Ok. Let me know, please, about report.
If they will not make changes, I will add exclusions to our filters.

**Comment by adbario** [comment]
Will do that, thanks. I have already posted on their forum about these domains, just need to wait for them to answer.
