### ISSUE TITLE
AdGuard tracking protection filter on viu.com uses 100% CPU

### ISSUE THREAD

**Issue by kriegaex** [AdguardTeam/AdguardFilters#54948]
This filter rule

```text
||mobileanalytics.*.amazonaws.com^
```

in https://filters.adtidy.org/extension/chromium/filters/3.txt causes the website viu.com to use 100% CPU, no matter if AdGuard protection is active or inactive for the site. In the filter log I can see that this URL is called hundreds of time every second, the filter log is full quickly and the AdGuard broswer extension symbol in Google Chrome shows a mathematical "unlimited" symbol. Even the filter protocol dialog freezes because the CPU is so high. I have to kill the AdGuard extension in the browser and re-load it in order to un-freeze the system.

![image](https://user-images.githubusercontent.com/1537384/81069874-b0fd6f00-8f0c-11ea-93bb-2211ad15e5f9.png)

For now my only option is to completely deactivate filtering for viu.com because just deactivating this rule does not help, maybe because the browser extension logs all the white-listed evens which are still thousands in a short time frame. This behaviour of viu.com is almost like a denial of service attack for ad blocker users, even though it might just be bad programming.

![image](https://user-images.githubusercontent.com/1537384/81069855-a8a53400-8f0c-11ea-8fba-fd69de5cc7b8.png)

**Comment by krystian3w** [comment]
Unable reporoduce with India VPN on Vivaldi and without account on viu.

`@@||mobileanalytics.*.amazonaws.com^$domain=viu.com`

**Comment by Alex-302** [comment]
@kriegaex Hi. Sorry for the late reply.
I see no difference with enabled/disabled AdGuard extension(CPU load ~45-55% in both cases)
![image](https://user-images.githubusercontent.com/8361299/81851266-dbc97200-9561-11ea-82a7-c4885d5d88cf.png)
Does it happen on specific page or on any page?

**Comment by krystian3w** [comment]
I suppose with sepecifc page like Episode 97 "Thai" film series.

**Comment by wft44maqb** [comment]
![image](https://user-images.githubusercontent.com/86122516/130513282-3520c9b5-97bc-4276-9100-6c3310f9a0c0.png)

**Comment by wft44maqb** [comment]
@Alex-302

**Comment by Alex-302** [comment]
@wft44maqb Thanks. Could you please copy full domain without `*`?
