### ISSUE TITLE
jp-xvideos.info

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#54943]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[NSFW] URLs:
`http://jp-xvideos.info/`
`http://jp-xvideos.info/video1141267/%EF%BB%BF%E5%88%9D%E3%82%81%E3%81%A6%E3%81%AE%E3%82%BB%E3%83%83%E3%82%AF%E3%82%B9`

1. a big placeholder and ads

2. embedded videos can't be played on Firefox but (can be played on Chromium)

3. pop-under

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

1:
![jp-xvideos](https://user-images.githubusercontent.com/58900598/81059332-37b14c80-8f0b-11ea-9fca-ed246092bee4.png)

![jp-xvideos1](https://user-images.githubusercontent.com/58900598/81059727-fec5a780-8f0b-11ea-9078-259e522b9439.png)

2:
![jp-xvideos2](https://user-images.githubusercontent.com/58900598/81059346-3c760080-8f0b-11ea-81e1-4fba95854799.png)

</details><br/>

***Steps to reproduce the problem***:
Each corresponds to the number in Description

1. Visit the homepage

2. Visit the test URL and try to play the embedded video

3. Visit the home page and choose any video from middle of the page

<details>
![jp-xvideos3](https://user-images.githubusercontent.com/58900598/81059892-5cf28a80-8f0c-11ea-82da-6ac792723353.png)
</details>

***System configuration***

**Filters:**

Base + Tracking + Japanese

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox 75.0
AdGuard version:                       | 3.4.19
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Off

For 1: `||dis.hogei.info^`
For 2: `xvideos.com#@#+js(abort-on-property-read, xv.conf.dyn.pjs)`
For 3: `||jp-xvideos.info/js/main.js` works but probably blocks too many. I don't have time to investigate deeper now.

**Comment by krystian3w** [comment]
Hide this image from childrens?

**Comment by Yuki2718** [comment]
> 
> 
> Hide this image from childrens?

yeah, my bad.
