### ISSUE TITLE
Anti adblock script tubeninja.net

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5496]
***Description***:
* **Current behaviour**: 

There is the anti adblock script saying that "Try disabling your adblocker for this site and try again" on https://www.tubeninja.net
Reproduced on our side.

<summary>Screenshot:</summary>

<details>

![screen shot 2017-06-27 at 6 09 26 pm](https://user-images.githubusercontent.com/28784344/27594899-c82e1ef2-5b63-11e7-84aa-17faa0c845b7.png)

</details>

***Steps to reproduce the problem***:

1)Go on:
https://www.tubeninja.net
2) Try to add a link to any video (from Youtube for example)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1 
Adguard DNS: | None 
Adguard filters: | 1, 2, 3, 4, 14, 0
Ticket ID (if exists): | 1582067

**Comment by Alex-302** [comment]
Fixed
