### ISSUE TITLE
http://m.rus.delfi.ee - Anti Adblock 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5497]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://m.rus.delfi.ee/opinion/article.php?id=78694914 - cannot access the website with Adguard enabled 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screen shot 2017-06-27 at 11 33 30 pm](https://user-images.githubusercontent.com/23372054/27608798-6ba0083e-5b91-11e7-9220-c7b3e58fffd9.png)

</details>

***System configuration***

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.18.49 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.14 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.57 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.90 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.51.37 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.42 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.17 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.56 Enabled=NO
ID=115 Name="RU AdList" Version=1.0.80.39 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.80.40 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=NO
ID=218 Name="Estonian List" Version=1.0.2.10 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.74.19 Enabled=NO

Ticket ID : 1582215

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
