### ISSUE TITLE
Ads on klerk.ru

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5500]
***Description***:
* **Current behaviour**: 

![screen shot 2017-06-28 at 11 17 21 am](https://user-images.githubusercontent.com/27874000/27627257-d1aeb12c-5bf3-11e7-858d-a7c3edf08b9a.png)

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Ticket ID: | 1582441

**Comment by Alex-302** [comment]
Fixed
