### ISSUE TITLE
Не блокируется реклама на сайте https://news.pn/ru/

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardFilters#55005]
@Olegmac1975 commented on [Tue May 05 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3297)

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59)
* Operating system and version: (e.g. Windows 10, v.1703, build 15063.413)

**Comment by zloyden** [comment]
@Olegmac1975 поправил, в будущем, пожалуйста, отправляйте репорт через помощник или по [этой ссылке ](https://agrd.io/report)
