### ISSUE TITLE
wefashion.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5503]
***Site***: http://www.wefashion.de/
***Description***: Cookie notice overlay.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27639549-d3dc6db8-5c16-11e7-95e7-6fe26431ad5f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.15
Spyware filter | 1.0.13
Social media filter | 1.0.20.76
Annoyances filter | 1.0.14.70
German filter | 1.0.35.21
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
