### ISSUE TITLE
icontact.com - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5504]
***Site***: https://www.icontact.com/signup-trial
***Description***: Signup doesn't work with Adguard enabled. Just enter random stuff and nothing will happen.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27640285-2399bb4c-5c19-11e7-817d-695d98efdc87.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.15
Spyware filter | 1.0.13
Social media filter | 1.0.20.76
Annoyances filter | 1.0.14.70
German filter | 1.0.35.21
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
