### ISSUE TITLE
erdbeerlounge.de - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5506]
***Site***: http://www.erdbeerlounge.de/beauty/9-total-geniale-dm-produkte-die-keiner-kennt/
***Description***: Social buttons when scrolling down.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27645690-fb184072-5c26-11e7-9a84-be4c72d764a0.png)

![image](https://user-images.githubusercontent.com/10995998/28224312-ec57a67c-68ce-11e7-8da2-ff36d5b221fa.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.18
Spyware filter | 1.0.13.1
Social media filter | 1.0.20.76
Annoyances filter | 1.0.14.72
German filter | 1.0.35.22
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr New Whatsapp newsletter signup:

![image](https://user-images.githubusercontent.com/10995998/28899149-d71e13e8-77e9-11e7-804e-e2a7603e13f3.png)

**Comment by AdamWr** [comment]
Fixed.
