### ISSUE TITLE
Suggest Filtering Rules

### ISSUE THREAD

**Issue by Icekiss69** [AdguardTeam/AdguardFilters#55086]
Hiya
these are some suggested domains i had to block myself in uBlock Origin and didn't know where to post them as suggested definitions anywhere 

gadspms.com
fadsabs.com
fadsans.com
fadsecs.com
fadslims.com
fadspms.com
mfadsrvr.com
fadsoks.com
0klxjejyxak3.com

**Comment by Alex-302** [comment]
added missed servers
