### ISSUE TITLE
reverso.net - Ad - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5508]
***Site***: http://www.reverso.net/text_translation.aspx?lang=EN
***Description***: Ad and newsletter form.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27659080-8256fcd8-5c52-11e7-89a6-cfecc7b95d74.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.20
Spyware filter | 1.0.13.2
Social media filter | 1.0.20.77
Annoyances filter | 1.0.14.73
German filter | 1.0.35.22
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
