### ISSUE TITLE
Ad leftover on habrahabr.ru

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5509]
***Description***:
* **Current behaviour**: 
There is an ad leftover on: https://habrahabr.ru/
Reproduced on our side
<summary>Screenshot:</summary>

<details>

![screen shot 2017-06-29 at 12 48 15 am](https://user-images.githubusercontent.com/28784344/27661894-a897a82c-5c64-11e7-8b86-0b61848ee59d.png)

</details>

***Steps to reproduce the problem***:
Go on:  https://habrahabr.ru/
Press on "Реклама"

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS 
Adguard version: | 1.4.0 
Adguard DNS: | None 
Adguard filters: | 0, 1, 2, 3, 4, 14
Ticket ID (if exists): | 1582845

**Comment by Alex-302** [comment]
Not reproduced.
