### ISSUE TITLE
gofobo.com - Annoyance - Social widgets - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5510]
***Site***: https://gofobo.com/main/local_movie_screenings/807
***Description***: Ad leftover. Cookie notice. Social buttons.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27663897-dc66f50e-5c64-11e7-8275-6d6735c428e3.png)

![image](https://user-images.githubusercontent.com/10995998/27663907-eb578ba0-5c64-11e7-9ad7-fcfd2e7ce1fa.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.20
Spyware filter | 1.0.13.2
Social media filter | 1.0.20.77
Annoyances filter | 1.0.14.73
German filter | 1.0.35.22
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr What about the ad leftover at the top and the cookie notice?

**Comment by AdamWr** [comment]
@danidoedel I did not noticed them, because I did not have enabled Safari filter.
I will fix this.
By the way, do you really need Safari filter in Windows with Chrome?

**Comment by danidoedel** [comment]
Well that's true, I don't really need that, not sure why I still had that enabled... :D 
Didn't realize that stuff is caused by the Safari filter...

**Comment by AdamWr** [comment]
Fixed.
