### ISSUE TITLE
nordbuzz.de - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5511]
***Site***: https://www.nordbuzz.de/
***Description***: Ad leftover. Social widgets.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27664021-99f798ee-5c65-11e7-8c29-90e5aa068ab0.png)

**https://www.nordbuzz.de/region-bremen-oldenburg/fussball-em-2024-darum-bremen-gute-chancen-spielort-werden-8409724.html:**

![image](https://user-images.githubusercontent.com/10995998/27664049-b9f31db2-5c65-11e7-866d-bd2f48300eac.png)

![image](https://user-images.githubusercontent.com/10995998/27664071-d4f99d02-5c65-11e7-835f-cae9d70443d6.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.20
Spyware filter | 1.0.13.2
Social media filter | 1.0.20.77
Annoyances filter | 1.0.14.73
German filter | 1.0.35.22
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
