### ISSUE TITLE
mr-build.ru - Ad leftover and pop ups

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5513]
***Description***:
* **Current behaviour**: 

There are ads and pop-ups on:
http://mr-build.ru/konstruktsii/kakie-okna-luchshe-stavit-v-kvartiru.html
Reproduced on our side
<summary>Screenshot:</summary>

<details>

![screen shot 2017-06-29 at 3 35 54 am](https://user-images.githubusercontent.com/28784344/27666431-4ec3577a-5c7c-11e7-8b17-c67a1db002a8.png)

</details>

***Steps to reproduce the problem***:

Go on: 
http://mr-build.ru/konstruktsii/kakie-okna-luchshe-stavit-v-kvartiru.html
Scroll down

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Adguard version: | 1.4.1.
Adguard DNS: | None
Adguard filters: | 0, 1, 2, 3, 4, 14
Ticket ID (if exists): | 1150428

**Comment by Alex-302** [comment]
Fixed
