### ISSUE TITLE
surfearner.com - Adguard blocks ad video after adding the page to exceptions

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5514]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

surfearner.com after adding the webpage to exceptions Adguard still blocks the player and video doesn't play

Login for testing can be found in the ticket: 1043635

May be it is possible to create a custom filter rule to unblock the player.

****
[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29478021/27687344-2a38fdca-5cdf-11e7-9719-4b1909ac7c43.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

</details>

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | on
Adguard filters: | User, English, Russian, Spyware, Social media, Annoyances
Ticket ID (if exists): | 1043635

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Please check these rules:
```
@@||v.kost.tv^$domain=surfearner.com
@@||v.kost.tv^$domain=winvideo.tv
```

**Comment by kbahlyk** [comment]
Rules didn't help: customer can see the player, but it is said, that there are no ad videos available. Without Adguard ad videos can be viewed.

**Comment by Alex-302** [comment]
Is is possible. A lot of ads are blocked by generic rules, and loads like requests from another page.
User can try to unblock blocked ads manually, but some ads will be unblocked on all sites which are using that ad systems.
For example:
```
@@||blocked-domain.com^
```
