### ISSUE TITLE
9to5mac.com - Ad leftover - top banner

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5515]
Placeholder under the menu.

URL:

https://9to5mac.com

<details><summary>Screenshot:</summary>

![screen-shot-2017-06-29-at-16 49 39](https://user-images.githubusercontent.com/28726429/27691085-b20426a6-5ceb-11e7-8cb6-dcbd718876fe.jpg)

</details>

<br>
***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome, Safari
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 12, 14

**Comment by Alex-302** [comment]
fixed

**Comment by ameshkov** [comment]
It came back

**Comment by Alex-302** [comment]
Added to English filter
```
!+ PLATFORM(ios)
9to5google.com,9to5mac.com,9to5toys.com,electrek.co##.site-header-placeholder+div[class]
9to5google.com,9to5mac.com,9to5toys.com,electrek.co##.site-header-placeholder+div[class][-ext-has='> div[id^="div-gpt-ad"]']
```

**Comment by ameshkov** [comment]
@Alex-302 `:has` won't work on IOS

**Comment by Alex-302** [comment]
The second rule is not for iOS.
```
!+ PLATFORM(ios)
9to5google.com,9to5mac.com,9to5toys.com,electrek.co##.site-header-placeholder+div[class]
```

**Comment by ameshkov** [comment]
My bad, thanks
