### ISSUE TITLE
Ads on msn.com

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5517]
***Description***:
* **Current behaviour**: 

![screen shot 2017-06-29 at 5 44 33 pm](https://user-images.githubusercontent.com/27874000/27693774-036b5f30-5cf3-11e7-98d9-98567c9382f7.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | Extension 
Adguard filters: | English, Spyware, Social media, Annoyances
Ticket ID: | 1583118

**Comment by Alex-302** [comment]
Can't reproduce evenwithout Adguard.
@aksyonova is it reproducible on your side?

**Comment by danidoedel** [comment]
No ads for me but plenty of ad leftover stuff:

![image](https://user-images.githubusercontent.com/10995998/27700292-712c4750-5cfd-11e7-97e0-c8cb54edfc1c.png)

![image](https://user-images.githubusercontent.com/10995998/27700301-7af61216-5cfd-11e7-952e-d0a1b2e897f3.png)

**Comment by aksyonova** [comment]
@Alex-302 i could reproduce it with both extension and app enabled - the screenshot is actually mine. But right now there are only leftovers

**Comment by Alex-302** [comment]
Added to English filter
```
msn.com##.stripecontainer[data-section-id="stripe.msstore"]
msn.com##.widead
msn.com##.ad
msn.com##.bannersectionad
```
Please check.

**Comment by danidoedel** [comment]
This rule in english filter prevents that ad leftover is removed: `www.msn.com#@#.ad`

And this rule will remove some more ad leftover: `msn.com##.stripecontainer[data-section-id="stripe.shopping1"]`:

![image](https://user-images.githubusercontent.com/10995998/27712187-2176bdb6-5d26-11e7-9af7-ecb6ddd9ee40.png)

**Comment by seanl-adg** [comment]
Why not post a full url to the page?

**Comment by danidoedel** [comment]
Sorry I thought the page is similar for all languages, I have ad leftover here: http://www.msn.com/de-de

Couldn't find `msn.com/g00/` stuff in the log.

**Comment by danidoedel** [comment]
@Alex-302 @seanl-adg Still ads on msn.com ... They are using InstartLogic (many request urls like `http://tu9srvbirvvtmjekaw1nlxmtbxnulwnvbs5ha2ftywl6zwqubmv0.g00.msn.com/g00/2_d3d3Lm1zbi5jb20%3D_/TU9SRVBIRVVTMjEkaHR0cDovL2ltZy1zLW1zbi1jb20uYWthbWFpemVkLm5ldC90ZW5hbnQvYW1wL2VudGl0eWlkL0FBcXNlMncuaW1nP2g9NjUmdz0xMzYmbT02JnE9NjAmdT10Jm89dCZsPWYmaTEwYy5tYXJrLmltYWdlLnR5cGU%3D_$/$/$/$/$` in the log).
E.g.: 

http://www.msn.com/de-de/gesundheit/ernaehrung/abnehmen-wie-die-stars-diese-lebensmittel-kommen-in-jeder-model-di%C3%A4t-vor/ar-AAqonay?li=BBqgbZL

![image](https://user-images.githubusercontent.com/10995998/29517196-337d8126-8674-11e7-8fdf-983a53f34026.png)
