### ISSUE TITLE
Adguard doesn't block particular IP

### ISSUE THREAD

**Issue by gdgjkutdd** [AdguardTeam/AdguardFilters#55173]
I want to block 107.155.52.170:5222 but no matter, how I block it - by adguard wizard or by user rules - it just won't block it.

**Comment by krystian3w** [comment]
in AdGuard addon `v3.4.19`+ try:

`||107.155.52.170:5222$all,important`

||107. is not excluded from filters lists: https://github.com/AdguardTeam/FiltersRegistry/blob/d7c233a6747649d1a05f6a815408f81c79be27ed/filters/exclusions.txt#L57-L63

---

I do not know the progress of the implementation of `all` and `important` for the application on Windows / Android / macOS (and an addition for safari) and the project AdGuard Home.

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#important

**Comment by gdgjkutdd** [comment]
Unfortunately, latest version of Android app is 3.3.3. And i don't get it,
why should "all" option help and why adguard can't block that IP now. Seems
to be a bug.

**Comment by AdamWr** [comment]
Hi,
Please check with `$network` modifier - https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#network-modifier

`107.155.52.170$network`

**Comment by gdgjkutdd** [comment]
Thank you, it works!

Though, it seems, that "empty" modifier doesn't works for Android
(rule 107.155.52.117$network,empty).

**Comment by AdamWr** [comment]
>Though, it seems, that "empty" modifier doesn't works for Android
>(rule 107.155.52.117$network,empty).

`Empty` modifier is supported by AdGuard for Android, so it should works fine. In this case I think that this rule doesn't work, because `network` modifier probably doesn't work alongside with other modifiers.

This rule works fine on my end:
`||107.155.52.117^$empty`
and this too:
`107.155.52.117$empty`
