### ISSUE TITLE
aixFOAM.* - Blurred pages (AdGuard Annoyances filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#55182]
### Affected sites:
```
https://www.aixfoam.com/
https://www.aixfoam.de/
https://www.aixfoam.dk/
https://www.aixfoam.fi/
https://www.aixfoam.fr/
https://www.aixfoam.nl/
https://www.aixfoam.se/
```

### Issue:
Blurred pages, because of blocked cookie consent popup.

### Problem filter:
* AdGuard Annoyances filter

### Problem rule:
`###cc-notification`

### Possible fix (allowing the cookie consent popup):
`aixfoam.com,aixfoam.de,aixfoam.dk,aixfoam.fi,aixfoam.fr,aixfoam.nl,aixfoam.se#@##cc-notification`

### Reference (with screenshot):
`https://forum.palemoon.org/viewtopic.php?f=3&t=24359/`

### Other problem filters:
* EasyList Cookie List / Fanboy's Annoyance List (`###cc-notification` / `###cc-notification-wrapper`) https://github.com/ryanbr/fanboy-adblock/issues/1355/
* I don't care about cookies (`###cc-notification` / `###cc-notification-wrapper`) _notified_

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.9.3 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.20 (XUL)

**Comment by krystian3w** [comment]
Why no use:

```
aixfoam.com,aixfoam.de,aixfoam.dk,aixfoam.fi,aixfoam.fr,aixfoam.nl,aixfoam.se#$##cc-notification { display: none !important; }
aixfoam.com,aixfoam.de,aixfoam.dk,aixfoam.fi,aixfoam.fr,aixfoam.nl,aixfoam.se#$#.content-blurred { filter: none !important; }
```

**Comment by krystian3w** [comment]
Create cookies with script may need 3 cookies:

```
   www.aixfoam.com

Cookies

    cc_analytics:yes
    cc_advertising:yes
    cc_necessary:yes
```

**Comment by THEtomaso** [comment]
> Why no use:
> ```
> aixfoam.com,aixfoam.de,aixfoam.dk,aixfoam.fi,aixfoam.fr,aixfoam.nl,aixfoam.se#$##cc-notification { display: none !important; }
> aixfoam.com,aixfoam.de,aixfoam.dk,aixfoam.fi,aixfoam.fr,aixfoam.nl,aixfoam.se#$#.content-blurred { filter: none !important; }
> ```

Thanks, those rules seems to work just fine for me in uBO!
Are they ABP-compatible?

**Comment by krystian3w** [comment]
Still nope.

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
Thank you.
