### ISSUE TITLE
smh.com.au - Ad leftover - Social widget - Annoyance - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5519]
***Site***: http://www.smh.com.au/
***Description***: 

Ad leftover at the end of the page.
Social button leftover. Ad leftovers on article pages. Social leftover stuff in sidebar. Newsletter button. Property and job ad.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27732917-ce001182-5d93-11e7-9178-4b534bea99ac.png)

**http://www.smh.com.au/nsw/nswwoman-who-sued-police-to-pay-250k-costs-20170630-gx2bqr.html:**

![image](https://user-images.githubusercontent.com/10995998/27733036-63b66d2a-5d94-11e7-9c31-cea0ab255a39.png)

![image](https://user-images.githubusercontent.com/10995998/27733110-9dff5622-5d94-11e7-96ec-f6a52f934c42.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.31
Spyware filter | 1.0.13.5
Social media filter | 1.0.20.80
Annoyances filter | 1.0.14.84
German filter | 1.0.35.27
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
