### ISSUE TITLE
Anti Ad Block: mp4upload.com

### ISSUE THREAD

**Issue by mxnmnm** [AdguardTeam/AdguardFilters#55197]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: An anti ad blocker has been installed on the mp4upload server for 9anime and it's the only server that lets you download episodes. I can't download episodes because of the anti ad blocker and the ads are really cancerous.

***Current behavior***: Can't use mp4upload server without disabling adguard

***Expected behavior***: Never have to think about disabling adguard

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
![Screenshot (322)](https://user-images.githubusercontent.com/8508976/81490896-42861d00-923c-11ea-907a-90df625efdef.png)

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:
Try and play an episode/click the download link with ad guard enabled and see bad things happen (be sure to use the mp4upload server). Here's a link to some anime to try it on https://9anime.to/watch/kaguya-sama-love-is-war.5pvv/ojjj0oz

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***
Not sure what to put here

**Filters:**
Base, Other, Language Specific, and Custom: AakList (Anti-Adblock Killer) [this was me trying to figure out how to fix it earlier]

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox
AdGuard version:                       | 3.4.19
Filters enabled:                       | Base, Other, Language Specific, and Custom: AakList (Anti-Adblock Killer) [this was me trying to figure out how to fix it earlier]
AdGuard DNS:                           |  Default
Stealth mode options (Windows only)    | Regular

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by mxnmnm** [comment]
The issue also persists when going to the download on mp4upload.com and it shows a little preview (although once I click the link I'm able to download without needing to disable adguard again). So I think it's safe to say mp4upload has the script while 9anime doesn't.

**Comment by AdamWr** [comment]
Hi,
Anti-adblock on `mp4upload.com` has been fixed 3 days aga and I can't reproduce this issue.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/81537226-2d5cdb80-936d-11ea-86d9-cc2ffda3d63f.png)

</details>

Please update filters and then check again.

**Comment by mxnmnm** [comment]
Oh sweet thanks, I thought I had refreshed them but I guess I didn't lol
