### ISSUE TITLE
huffingtonpost.com.au - Social widget - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5520]
***Site***: http://www.huffingtonpost.com.au/2017/06/30/aussie-cricketers-defiant-in-pay-dispute-and-could-even-miss-as_a_23007293/?utm_hp_ref=au-homepage
***Description***: Social button leftover space. Annoying social bar on mobile.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27733257-7784ded0-5d95-11e7-861c-9e4a21352aaa.png)

![image](https://user-images.githubusercontent.com/10995998/27733307-b2e81564-5d95-11e7-8161-274c441a9320.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.31
Spyware filter | 1.0.13.5
Social media filter | 1.0.20.80
Annoyances filter | 1.0.14.84
German filter | 1.0.35.27
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
