### ISSUE TITLE
block gibberish hostnames

### ISSUE THREAD

**Issue by sayjota** [AdguardTeam/AdguardFilters#55205]
### Problem Description

many malicious sites circumvent filters by using randomly generated hostnames and creating new hosts more frequently than the filters are updated.

for example urls like this:
`https://d2klx87bgzngce.com`

eventually this url will be added to the standard filters, but by that time a new gibberish host is serving the malicious ads.

### Proposed Solution

add a filter that blocks all gibberish hostnames.  of course we'd need to decide what constitutes gibberish and then how to actually identify such.

**Comment by Alex-302** [comment]
Not sure if it is possible. Some sites uses "random" domains as CDN or something like that(when ad blocker is detected - only one example).
