### ISSUE TITLE
welt.de (Google AMP) - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5521]
***Site***: https://www.google.de/amp/s/amp.welt.de/amp/vermischtes/article166094414/Land-unter-in-der-Hauptstadt-Berlin-kommt-nicht-zur-Ruhe.html
***Description***: Social share leftover. Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27734603-cf2c2228-5d9b-11e7-821e-9ab74ff9be37.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.31
Spyware filter | 1.0.13.5
Social media filter | 1.0.20.80
Annoyances filter | 1.0.14.84
German filter | 1.0.35.27
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
