### ISSUE TITLE
sueddeutsche.de (Google AMP) - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5522]
***Site***: https://www.google.de/amp/www.sueddeutsche.de/panorama/wetter-doppelt-so-viel-regen-in-berlin-wie-sonst-im-ganzen-juni-1.3567321!amp
***Description***: Ad leftovers. Social widgets.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27734663-39e72c2a-5d9c-11e7-9734-59dc0ef1036b.png)

![image](https://user-images.githubusercontent.com/10995998/27734676-4a977160-5d9c-11e7-863d-e2ac1ce9d8f3.png)

![image](https://user-images.githubusercontent.com/10995998/27734705-5f8892d4-5d9c-11e7-8a8d-5a654c028aa9.png)

![image](https://user-images.githubusercontent.com/10995998/27734709-69cde58c-5d9c-11e7-8aec-b40f5894991f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.31
Spyware filter | 1.0.13.5
Social media filter | 1.0.20.80
Annoyances filter | 1.0.14.84
German filter | 1.0.35.27
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
