### ISSUE TITLE
bild.de (Google AMP) - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5523]
***Site***: https://www.google.de/amp/m.bild.de/regional/berlin/wetter/jahrhundert-unwetter-von-berlin-52386716,view=amp.bildMobile.html
***Description***: Social button leftover space and whatsapp button. Ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27734883-346a3552-5d9d-11e7-8ced-200713bcd5a0.png)

![image](https://user-images.githubusercontent.com/10995998/27734890-3d2e24c8-5d9d-11e7-85fd-a990a3c1c3d1.png)

![image](https://user-images.githubusercontent.com/10995998/27734904-46e29382-5d9d-11e7-8881-28bb53a267aa.png)

![image](https://user-images.githubusercontent.com/10995998/27734917-599c9e1e-5d9d-11e7-867f-6656a5c92b9b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.31
Spyware filter | 1.0.13.5
Social media filter | 1.0.20.80
Annoyances filter | 1.0.14.84
German filter | 1.0.35.27
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed

**Comment by danidoedel** [comment]
@seanl-adg Ad leftovers still there:

![image](https://user-images.githubusercontent.com/10995998/27983944-c9eaa8aa-63c9-11e7-95fc-d6a516ea7589.png)

![image](https://user-images.githubusercontent.com/10995998/27983945-d2141660-63c9-11e7-8037-9c8e9638e120.png)
