### ISSUE TITLE
golem.de (Google AMP) - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5524]
***Site***: https://www.google.de/amp/s/www.golem.de/news/oepnv-in-berlin-wie-die-bvg-virtuelle-busfahrten-erfindet-1706-128664.amp.html
***Description***: Ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27735118-3df36444-5d9e-11e7-8c7c-675e18307ec2.png)

![image](https://user-images.githubusercontent.com/10995998/27735125-48030444-5d9e-11e7-89f5-6f8139cb6e7d.png)

![image](https://user-images.githubusercontent.com/10995998/27735131-52ff0c8a-5d9e-11e7-8c6c-4ea2380569cf.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.31
Spyware filter | 1.0.13.5
Social media filter | 1.0.20.80
Annoyances filter | 1.0.14.84
German filter | 1.0.35.27
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
