### ISSUE TITLE
photobucket.com - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5525]
***Site***: http://photobucket.com/recentuploads?page=1
***Description***: Annoying ad overlay. Ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27735560-865db2b4-5da0-11e7-987e-28589f1d2426.png)

**http://photobucket.com/gallery/user/Tanvir2/media/bWVkaWFJZDo5MTAwNTA3Nw==/?ref=:**

![image](https://user-images.githubusercontent.com/10995998/27735697-3c6ab5ca-5da1-11e7-970f-5b25058157bd.png)

`photobucket.com##.ads_top` and `photobucket.com##.ads_bottom`

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.31
Spyware filter | 1.0.13.5
Social media filter | 1.0.20.80
Annoyances filter | 1.0.14.84
German filter | 1.0.35.27
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
