### ISSUE TITLE
dallasnews.com - Ad leftover - Social widgets - Annoyance - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5526]
***Site***: https://www.dallasnews.com/
***Description***: Ad leftover. Social share button leftover. Sponsored stories leftover with newsletter form inside. Adblock detection (didn't pop up the first few times I reloaded the page).

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27735962-5ac4953a-5da2-11e7-9cfb-86ba3c2d1113.png)

**https://www.dallasnews.com/news/missing-person/2017/06/28/missing-lancaster-girl-may-abducted-police-say:**

![image](https://user-images.githubusercontent.com/10995998/27735930-371cb07c-5da2-11e7-983d-23c70c30525c.png)

![image](https://user-images.githubusercontent.com/10995998/27736099-f170ed30-5da2-11e7-9bd4-4714fcf79ab1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.31
Spyware filter | 1.0.13.5
Social media filter | 1.0.20.80
Annoyances filter | 1.0.14.84
German filter | 1.0.35.27
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
