### ISSUE TITLE
kissasian.com - Ad leftover - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5527]
***Site***: http://kissasian.com/Drama/The-Crossing-Part-2/Movie?id=22704
***Description***: Adblock detection after watching few seconds. Also ad leftover below video.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27736483-9f628e98-5da4-11e7-9d2a-65d04a811df1.png)

![image](https://user-images.githubusercontent.com/10995998/27736527-d00c95ca-5da4-11e7-8c9b-fe23494849b1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.31
Spyware filter | 1.0.13.5
Social media filter | 1.0.20.80
Annoyances filter | 1.0.14.84
German filter | 1.0.35.27
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
