### ISSUE TITLE
vladtv.ru - Ad leftover

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5528]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

There is the ad leftover on:
http://vladtv.ru
Reproduced on our side
<details><summary>Screenshot:</summary>

![screen shot 2017-06-30 at 3 58 30 pm](https://user-images.githubusercontent.com/28784344/27736465-fc9630da-5dac-11e7-8b00-c6f6bff510de.png)

</details>

***Steps to reproduce the problem***:
Go on: http://vladtv.ru/

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 0, 1, 2, 3, 4, 11, 14
Ticket ID (if exists): | 1118755

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
