### ISSUE TITLE
lenta.ru

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#5529]
***Description***: Yandex.direct ad appearing on lenta.ru after ~30 seconds

<details><summary>Screenshot:</summary>

![image](https://content.screencast.com/users/vasily_bagirov/folders/Jing/media/2bcd0dae-b5ff-4dde-81fe-35fa08f5f334/2017-06-30_1601.png)

</details>

***Steps to reproduce the problem***:

[//]:  open lenta.ru and wait for some time

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10
Browser: | Chrome 58
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | Block WebRTC
Adguard filters: | English, Russian, Spyware, Social, Annoyances

**Comment by Alex-302** [comment]
Not reproduced. Please capture HAR file
https://toolbox.googleapps.com/apps/har_analyzer/?lang=ru

**Comment by Alex-302** [comment]
Any news?
