### ISSUE TITLE
uraltrack.net - Ad leftover

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5530]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

There is the ad leftover and letf black spasce on:
http://uraltrack.net/
Reproduced on our side

<details><summary>Screenshot:</summary>

![screen shot 2017-06-30 at 4 12 45 pm](https://user-images.githubusercontent.com/28784344/27737004-3413ac2a-5daf-11e7-9d76-536df739ae28.png)

</details>

***Steps to reproduce the problem***:

Go on: 
http://uraltrack.net/
***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Adguard version: | 1.4.1.
Adguard DNS: | None 
Adguard filters: | 0, 1, 2, 3, 4, 11, 14
Ticket ID (if exists): | 1428525

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
