### ISSUE TITLE
fireseo.ru - Incorrect blocking

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5534]
***Description***:
* **Current behaviour**: 

When Adguard - on, the page ( https://fireseo.ru/audit-kontekstnoj-reklamy/) doesn`t show all the content ( some pictures are missed)
When Adguard -off, the issue doesn`t persist.
Reproduced on our side

<details><summary>Screenshot(Adguard ON):</summary>

![screen shot 2017-06-30 at 4 59 40 pm](https://user-images.githubusercontent.com/28784344/27739130-3bed4788-5db6-11e7-9521-6a1127ea744f.png)

</details>

<details><summary>Screenshot(Adguard OFF):</summary>

![screen shot 2017-06-30 at 4 59 07 pm](https://user-images.githubusercontent.com/28784344/27739153-4b4b4090-5db6-11e7-803c-fb566745eb82.png)

</details>

***Steps to reproduce the problem***:
1) Go on: 
https://fireseo.ru/audit-kontekstnoj-reklamy/
2) Try to disable/enable Adguard and see what happens

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 0, 1, 2, 3, 4, 11, 14
Ticket ID (if exists): | 1583689

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||fireseo.ru/wp-content/themes/fireseo/images/advertising/$domain=fireseo.ru
```

**Comment by sealucky7** [comment]
Thanks a lot! Working.
