### ISSUE TITLE
remove domain from tracking_servers.txt

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5535]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Customer asks to remove st.dynamicyield.com^$third-party from the tracking_servers.txt

https://qcrm.supportyourapp.com/#/customer/1581804

**Comment by Alex-302** [comment]
Ok.
