### ISSUE TITLE
tagesspiegel.de (Google AMP) - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5536]
***Site***: https://www.google.de/amp/amp.tagesspiegel.de/berlin/nach-dem-unwetter-in-berlin-wie-sich-der-rekordregen-auf-die-gewaesser-auswirkt/20005558.html
***Description***: Social share buttons. Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27761943-942b0f96-5e67-11e7-935b-efc39b5daca5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.31
Spyware filter | 1.0.13.5
Social media filter | 1.0.20.80
Annoyances filter | 1.0.14.84
German filter | 1.0.35.27
Mobile ads filter | 1.0.8.79
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
It is fixed in https://github.com/AdguardTeam/AdguardFilters/commit/0dc2cda39fcca0d7487d52393a322a407f63a9f3
