### ISSUE TITLE
tz.de (Google AMP) - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5537]
***Site***: https://www.google.de/amp/s/www.tz.de/sport/1860-muenchen/awata-sein-langer-weg-als-fluechtling-zu-1860-8448614.amp.html
***Description***: Social buttons. Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27761995-6e2830d4-5e68-11e7-9817-8b3b303dcd60.png)

![image](https://user-images.githubusercontent.com/10995998/27762001-8caf8da4-5e68-11e7-9a1d-4dd476dbf36a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.48
Spyware filter | 1.0.13.6
Social media filter | 1.0.20.81
Annoyances filter | 1.0.14.88
German filter | 1.0.35.27
Mobile ads filter | 1.0.8.82
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed

**Comment by danidoedel** [comment]
@seanl-adg The title of the ad leftover is still there:

![image](https://user-images.githubusercontent.com/10995998/27983936-932d2ce8-63c9-11e7-8ee6-ce21cc4d4161.png)
