### ISSUE TITLE
skyscrapercity.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#55388]
[https://www.skyscrapercity.com/threads/what-do-you-think-of-the-new-forum-site.2255198/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.skyscrapercity.com/threads/what-do-you-think-of-the-new-forum-site.2255198/)

Scroll down to see this floating annoyance. This bar can be hidden because there's already a "Login/Join" link at the top, and people are also invited to login if they try to reply to a post.

![annoyance](https://user-images.githubusercontent.com/35470489/81842230-0bf12080-9522-11ea-89ac-762cc17296a8.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
@adranger I see only static form.
Please check
 `skyscrapercity.com###thread-main-section > div.california-login-container`

**Comment by adranger** [comment]
I see it after I scroll up and down a few times. 

This block is displayed as  `#welcome_back` to me, and it's outside of `#thread-main-section`.

[skyscrapercity.zip](https://github.com/AdguardTeam/AdguardFilters/files/4634442/skyscrapercity.zip)

**Comment by Alex-302** [comment]
Ok, added `skyscrapercity.com###welcome_back`
