### ISSUE TITLE
merkur.de (Google AMP) - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5538]
***Site***: https://www.google.de/amp/s/www.merkur.de/lokales/flughafen-muenchen/am-flughafen-muenchen-trickdiebe-stehlen-teure-rolex-uhren-aus-boutique-im-terminal-8446063.amp.html
***Description***: Social buttons. Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27762031-3484961e-5e69-11e7-81b6-3ea7b7f5e520.png)

![image](https://user-images.githubusercontent.com/10995998/27762033-4dfabe02-5e69-11e7-97da-75c910acf9f9.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.48
Spyware filter | 1.0.13.6
Social media filter | 1.0.20.81
Annoyances filter | 1.0.14.88
German filter | 1.0.35.27
Mobile ads filter | 1.0.8.82
Safari filter | 1.0.3.52

**Comment by ameshkov** [comment]
Same goes for Adguard for Android

**Comment by danidoedel** [comment]
@seanl-adg The title of the ad leftover is still there: 
![image](https://user-images.githubusercontent.com/10995998/27983927-652f920e-63c9-11e7-9a60-10a2cd110598.png)
