### ISSUE TITLE
YouTube Android Unblocked Adds

### ISSUE THREAD

**Issue by zero77** [AdguardTeam/AdguardFilters#5540]
There are lots of adds video and other in the you tube android mobile app I have android 6 and the beta version of Adguard installed in VPN mode and https filtering on with updated filters.

I have looked at the packets sent by the YouTube app but was unable to spot anything.

Thanks

**Comment by Alex-302** [comment]
We can't block ads in Youtube app. Their traffic is encrypted.

**Comment by zero77** [comment]
Correct me if I am wrong but, I guess what your saying is the app uses end to end encryption with something like certificate pinning, with the IPs hard coded instead of resolving the domain.

If so, is it possible to block the IPs instead of the domain.

**Comment by Alex-302** [comment]
No, they are using not only SSL. All content is encrypted and we can't decode it.
