### ISSUE TITLE
zdnet.de - Anti Adblock script

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardFilters#5542]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

The Anti Adblock notification appears on the website.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/17320558/27764226-c9492b06-5e9c-11e7-976a-7a52a8ad217a.png)

</details>

***Steps to reproduce the problem***:

http://www.zdnet.de

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | User, English, Russian, Annoyances, Spyware, Social media, Safari
Ticket ID (if exists): | 1584248

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced with German filter.

**Comment by dzamyshlyayeva** [comment]
the user enabled German filter but the issue still persists:

"when you check the box with adblock- feature in the mobile dolphin browser, this will not work together with the adguard- system. Opting out this feature and only use adguard - then everything is fine"

**Comment by Alex-302** [comment]
Still not reproduced. Maybe another ad blocker works in the same time.

**Comment by dzamyshlyayeva** [comment]
asked the user

**Comment by kbahlyk** [comment]
No other ad blockers, but the customer uses Tor.

**Comment by Alex-302** [comment]
Can he check without Tor?
