### ISSUE TITLE
dostfilms.*

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#55429]
**1**. Сразу разворачиваем описание фильма, без необходимости нажимать кнопку "Развернуть описание".

<details><summary>Screenshot:</summary>

![2020 05 14-1](https://user-images.githubusercontent.com/17948007/81938210-4da2c980-95fd-11ea-9c32-78276e8b237c.png)
</details>

`||dostfilms.*/uploads/readmore.min.js`

___________________________________________________

 **2**. Реклама.

<details><summary>Screenshot:</summary>

![2020 05 14-2](https://user-images.githubusercontent.com/17948007/81938407-880c6680-95fd-11ea-9245-6a7d958f7c02.png)
</details>

`dostfilms.*##[class*="reklama"]`

___________________________________________________

 **3**. Раздражитель.

<details><summary>Screenshot:</summary>

![2019 09 21-1](https://user-images.githubusercontent.com/17948007/65364704-289bb980-dc1c-11e9-896a-1f210717c89c.png)
</details>

`dostfilms.*##.sidebox:contains(Интересное)`

___________________________________________________

 **4**. Социальный виджет?

<details><summary>Screenshot:</summary>

![2019 09 21-2](https://user-images.githubusercontent.com/17948007/65364791-98aa3f80-dc1c-11e9-965a-23c09824dfb9.png)
</details>

`dostfilms.*##.sidebox:contains(Мы в соцсетях)`

[https://dog.dostfilms.biz/publ/boeviki/geoshtorm_2017/18-1-0-450](https://href.li/?https://dog.dostfilms.biz/publ/boeviki/geoshtorm_2017/18-1-0-450)

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.4.19
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
Какие у них домены? `*` в TLD пока рано использовать.

**Comment by XX-J** [comment]
> Какие у них домены?

 Из того, что я знаю: `dostfilms.net,dostfilms.cc,dostfilms.biz`

> `*` в TLD пока рано использовать.

 Это из-за приложухи? Глючит?

**Comment by Alex-302** [comment]
> Это из-за приложухи? Глючит?

не во всех версиях пока есть. Релиз раскатать нужно.

> Из того, что я знаю: `dostfilms.net,dostfilms.cc,dostfilms.biz`

первые редиректят на третий - dostfilms.biz

**Comment by XX-J** [comment]
Спасибо Большое, так гораздо лучше.
 Вот если бы ещё отступы убрать - была бы вообще красота!

<details><summary>Screenshot'ы ДО:</summary>

![2020 05 23-1](https://user-images.githubusercontent.com/17948007/82736240-d4a81e00-9d30-11ea-9943-20e7af054f63.png)
----------
![2020 05 23-2](https://user-images.githubusercontent.com/17948007/82736245-e2f63a00-9d30-11ea-9888-da812e93e801.png)
</details>

<details><summary>Screenshot ПОСЛЕ:</summary>

![2020 05 23-3](https://user-images.githubusercontent.com/17948007/82736237-c6f29880-9d30-11ea-9bf6-6da0efd0c5a7.png)
</details>

`dostfilms.biz#$#header, .carousel { margin: auto!important; }`

[https://dog.dostfilms.biz/](https://href.li/?https://dog.dostfilms.biz/)

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.4.31
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by XX-J** [comment]
-- Шеф!
-- Усё пропало!
-- Клиент домен меняет,
-- Рекламу проявляет...

 Нужно правило `dostfilms.biz##div[class*="reklama"]` изменить на `dostfilms.*##div[class*="reklama"]` в [.../RussianFilter/sections/specific.txt](https://github.com/AdguardTeam/AdguardFilters/blob/master/RussianFilter/sections/specific.txt)

 А `dostfilms.biz#?#.sidebar > section.sidebox:has(> div.sidebox-ttl:contains(Интересное))` из [.../AnnoyancesFilter/sections/self-promo.txt](https://github.com/AdguardTeam/AdguardFilters/blob/master/AnnoyancesFilter/sections/self-promo.txt) вообще удалить.

[https://dostfilms.co/publ/boeviki/geoshtorm_2017/18-1-0-4457](https://href.li/?https://dostfilms.co/publ/boeviki/geoshtorm_2017/18-1-0-4457)
<br>

 Система | Фильтры | Антитрекинг
---------- | ---------- | ----------
 AdGuard v3.6.17 | Базовый AdGuard &nbsp; &nbsp; &nbsp; &nbsp; Русский | Стандарт
 FireFox v78.13 ESR | Счётчиков и аналитики &nbsp; &nbsp; &nbsp; &nbsp; Отслеживания по URL | +Блокировка WebRTC
 Win7SP1 | Виджетов социальных сетей &nbsp; &nbsp; &nbsp; &nbsp; Раздражителей | +Удаление параметров отслеживания

**Comment by XX-J** [comment]
@Alex-302 - глянь...

**Comment by Alex-302** [comment]
> Почему ты не используешь звёздочку в TLD, ведь для этого домена это особенно актуально?

Не актуально, т.к. сайт один, и домен меняется редко.

**Comment by XX-J** [comment]
Я считаю, что если домен регулярно меняется, то звёздочка в TLD - это самый логичный выход, а не переписывание правил каждый раз как сменится домен.
