### ISSUE TITLE
Issues with reflection of Github on Android 7.1.

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5543]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
When you go to https://github.com the webpage is not fully displayed on Android 7.1.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29478021/27765274-e5b845b0-5eb5-11e7-9fa6-5d694a0b4f5a.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 7.1.2
Browser: | Chrome
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default)
Adguard filters: | 2, 3, 4, 14, 1, 11
Ticket ID (if exists): | 939612

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. Is it caused by filters?

**Comment by kbahlyk** [comment]
Forwarded to the customer: asked to turn the filters on and off one by one and check if any of them causing the issue.

**Comment by dzamyshlyayeva** [comment]
only disabling https filtering helps

**Comment by Alex-302** [comment]
I asked about ***the filters***, not about https filtering

**Comment by kbahlyk** [comment]
Sent one more request to the customer.

**Comment by dzamyshlyayeva** [comment]
with all filters disabled the page loads incorrectly

**Comment by Alex-302** [comment]
Maybe HTTPS issue. Try to reinstall certificate or/and make screenshot of cert details in Chrome(press on green lock).

**Comment by dzamyshlyayeva** [comment]
asked the user

**Comment by Alex-302** [comment]
Any news?

**Comment by dzamyshlyayeva** [comment]
sorry for the delay. reinstalling certificate fixed the issue.
