### ISSUE TITLE
Проникновение рекламы на e.mail.ru

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardFilters#55431]
Проблема с проникновение рекламы на сайте e.mail.ru при включенном Adguard и Tampermonkey с самыми последними обновленными фильтрами.

Operating system: Windows 10 Home
Browser: Chrome Version 81 (Official Build) (64-bit)
AdGuard version for Chrome: Version 3.4.19
Filters enabled: AdGuard Base filter, AdGuard Tracking Protection filter, EasyPrivacy, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter
Stealth mode options (Windows only) Enabled

![111](https://user-images.githubusercontent.com/23212486/81948375-551c9f80-960a-11ea-9ea1-5de917379a49.jpg)

**Comment by Alex-302** [comment]
Попробуй новый дизайн включить и AdGuard Extra.

---

Пользователям браузерного расширения нужно установить скрипт `AdGuard Extra`. Для этого понадобится браузерное расширение-скриптоприёмник `Tampermonkey`

Ссылка на `AdGuard Extra`
https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js

После установки скрипта нужно будет зайти в настройки `Tampermonkey`, включить режим эксперта, переключить режим встраивания на `мгновенный` и перезапустить расширение:
![image](https://user-images.githubusercontent.com/8361299/62641343-07248e00-b94c-11e9-9775-9854a7922889.png)

![image](https://user-images.githubusercontent.com/8361299/62641299-f7a54500-b94b-11e9-8a83-885d89abbeec.png)

**Comment by jbionic2016** [comment]
I already have the beta-version of this script in Tampermonkey, so I've just updated and the issue seems to have disappeared. So we can close this thread. Thanks a lot.
