### ISSUE TITLE
Zoomit False Positive

### ISSUE THREAD

**Issue by DRSDavidSoft** [AdguardTeam/AdguardFilters#55441]
***Description***:
The current rule for `zoomit.ir` is overzealous blocks too much:
```
||zoomit.ir/*/*/*-*.gif
```

* **Current behaviour**: 

The actual article images are blocked

<details><summary>Screenshot:</summary>
<img src="https://user-images.githubusercontent.com/4673812/81966469-d7b75600-962e-11ea-94f1-ad92a708339c.png">
</details><br/>

* **Expected behavior**: 

Actual article images should not be blocked

<details><summary>Screenshot:</summary>
<img src="https://user-images.githubusercontent.com/4673812/81966484-dbe37380-962e-11ea-94ec-95b6776e72bf.png">
</details><br/>

***Steps to reproduce the problem***:

1. Install Block Origin on Chrome on Windows 10
2. Enable **Adguard Base** filters
3. Visit the sample page:
```
https://www.zoomit.ir/2020/4/13/347423/cloudflare-dumps-google-recaptcha-use-hcaptcha/
```
4. Notice the main article image is gone

***System configuration***
- OS: Windows 10
- Browser: Chrome
- Engine: Block Origin
- Filter: AdGuard Base

**Filters:**

<details><summary>(Click to show)</summary>
<pre>
    "https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt",
    "https://easylist-downloads.adblockplus.org/antiadblockfilters.txt",
    "user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-abuse",
    "ublock-unbreak",
    "awrl-0",
    "adguard-generic",
    "adguard-mobile",
    "easylist",
    "adguard-spyware",
    "easyprivacy",
    "fanboy-enhanced",
    "disconnect-malvertising",
    "malware-0",
    "malware-1",
    "spam404-0",
    "adguard-annoyance",
    "fanboy-cookiemonster",
    "fanboy-annoyance",
    "ublock-annoyances",
    "dpollock-0",
    "mvps-0",
    "plowe-0",
    "IRN-0",
    "https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/adservers-and-trackers.txt",
    "https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/unwanted-iranian.txt",
    "https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt",
    "https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt",
    "https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt"
</pre>
</details><br/>

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 1903
Browser:                               | Chrome 81
AdGuard version:                       | N/A
Filters enabled:                       | Please read above
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | N/A
Simplified filters (iOS only)          | N/A
AdGuard DNS:                           | N/A
Stealth mode options (Windows only)    | N/A
Helpdesk ID (if exists):               | N/A

**Comment by AdamWr** [comment]
Hi,
Are you sure that this issue is caused by mentioned rule?
On my end this rule blocks only these images:
```
https://cdn01.zoomit.ir/2020/5/da8e382a-78eb-4dd0-85d9-a8a74b5b99dd.gif
https://cdn01.zoomit.ir/2020/5/722247a4-bba0-4dd9-9c88-ce957dae5bf8.gif
https://cdn01.zoomit.ir/2020/4/a0666e4e-9954-4fce-a86f-0365dab50692.gif
https://cdn01.zoomit.ir/2020/2/905189a6-7753-43ff-8808-68a9ba993aef.gif
https://cdn01.zoomit.ir/2020/4/33fd142b-55af-44c4-8514-a3b7256aeb71.gif
https://cdn01.zoomit.ir/2020/4/386c0136-641a-4c3c-acfd-df9bb58667cf.gif
https://cdn01.zoomit.ir/2020/5/f4ffa36a-ba84-4d55-8910-3cfce71772b2.gif
https://cdn01.zoomit.ir/2020/4/78e117e2-0826-402c-a48b-0e689bbc077b.gif
```
Seems that all of them are ads.

It looks like that website is broken by this rule from `Adblock-Iran` filter:
`zoomit.ir##+js(abort-on-property-read, setHeightOfAd)`

**Comment by DRSDavidSoft** [comment]
@AdamWr You're right, the main article image is a `.jpg` file, not a `.gif` file:
```
https://cdn01.zoomit.ir/2020/4/82e20554-009a-4a1f-88ba-6f576918dda6.jpg
```

Sorry for opening this invalid issue, I should've opened it at [`Adblock-Iran`](https://github.com/farrokhi/adblock-iran) instead. I'll close this now.

**Comment by AdamWr** [comment]
Ok, thank you for your answer.
