### ISSUE TITLE
Adguard blocks www.bezeq.co.il 

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5544]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Adguard blocks www.bezeq.co.il althought it is added to the whitelist  (@@||bezeq.co.il^)
Assistant icon is also not displayed on this webpage.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screen shot 2017-07-02 at 1 11 43 am](https://user-images.githubusercontent.com/29478021/27765784-e9e7b298-5ec3-11e7-94ed-d14cd68a9e16.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | English, Spyware, Social, Annoyances, Russian
Ticket ID (if exists): | 1308202

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
bezeq.co.il#@#.cookieAlert
```
Please check.

**Comment by kbahlyk** [comment]
Forwarded to the customer.
