### ISSUE TITLE
Ads on www.stereogum.com

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5545]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Ads on the webpage http://www.stereogum.com/1950105/warren-zevons-book-collection-along-with-mementos-from-his-career-going-up-for-auction/news/

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29478021/27766979-2c07650a-5eed-11e7-8620-87ebc0a769a9.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.2.1.71
Simplified filters(iOS) |  Off
Adguard DNS: |  Default 
Ticket ID (if exists): | 1142272
Adguard filters: | User filter, English, Spyware, Social media, Annoyances, Mobile Ads, Safari 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
