### ISSUE TITLE
watchfaces.be - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5546]
***Site***: https://www.watchfaces.be/watchfaces/hugo-boss/
***Description***: Adblock detection (popped up after some time)

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27769209-763b5ebe-5f25-11e7-9f47-52936988396e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.50
Spyware filter | 1.0.13.6
Social media filter | 1.0.20.81
Annoyances filter | 1.0.14.88
German filter | 1.0.35.27
Mobile ads filter | 1.0.8.82
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed in Annoyance

**Comment by danidoedel** [comment]
@seanl-adg There is some facebook overlay leftover now, I hope this can be removed as well: 

![image](https://user-images.githubusercontent.com/10995998/28014414-d266d02c-656c-11e7-8123-ce1d45699010.png)
