### ISSUE TITLE
online.sberbank.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#55463]
**1**. Баннер рекламирующий новую версию интерфейса (чуть выше есть дублирующая кнопка).

<details><summary>Screenshot:</summary>

![2020 05 13-1](https://user-images.githubusercontent.com/17948007/81994744-342b6d00-9651-11ea-8912-0f097e54a8fa.png)
</details>

`online.sberbank.ru###design30Banner`

___________________________________________________

 **2**. Реклама кредита.

<details><summary>Screenshot:</summary>

![2020 05 13-4](https://user-images.githubusercontent.com/17948007/81994761-3db4d500-9651-11ea-8184-cc4b0775f311.png)
</details>

 **2** и **3** скрываются одним правилом: `online.sberbank.ru##div:has(> .bunnerArea)`

 **1**, **2** и **4** относятся к первому аккаунту: [https://node5.online.sberbank.ru/PhizIC/private/accounts.do](https://href.li/?https://node5.online.sberbank.ru/PhizIC/private/accounts.do)

___________________________________________________

 **3**. Крутилятор с разными рекламами. Расположен во втором аккаунте на месте **2**-й рекламы.

<details><summary>Screenshot:</summary>

![2020 05 13-3](https://user-images.githubusercontent.com/17948007/81994795-5329ff00-9651-11ea-9b64-22fff7040dfc.png)
</details>

 **2** и **3** скрываются одним правилом: `online.sberbank.ru##div:has(> .bunnerArea)`

 **1** и **3** относятся ко второму аккаунту: [https://node6.online.sberbank.ru/PhizIC/private/accounts.do](https://href.li/?https://node6.online.sberbank.ru/PhizIC/private/accounts.do)

___________________________________________________

 **4**. Если по **2**-й рекламе ты не понял что тебе нужен кредит, то вот тебе напоминание, под списком карт.

<details><summary>Screenshot:</summary>

![2020 05 13-5](https://user-images.githubusercontent.com/17948007/81994771-45747980-9651-11ea-9ec8-57449e1e860f.png)
</details>

`online.sberbank.ru###offerBlock`

 **1**, **2** и **4** относятся к первому аккаунту: [https://node5.online.sberbank.ru/PhizIC/private/accounts.do](https://href.li/?https://node5.online.sberbank.ru/PhizIC/private/accounts.do)

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.4.19
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
Да их же сервисы. За что их?

**Comment by XX-J** [comment]
**1** - Большой НЕНУЖНЫЙ баннер, МЕШАЮЩИЙ нормально работать с сайтом.
 **2** - **4** - Банально просто - ЭТО **РЕКЛАМА!** Соответственно также ненужная и мешающая работе в интерфейсе сайта.

 Помоему это ВСЁ и так очевидно, разве Вы этого не видите?

**Comment by Alex-302** [comment]
Ну под таким предлогом можно половину любого сайта скрыть.

**Comment by XX-J** [comment]
Если на сайте производить какую-либо работу (взаимодействие) и делать это на регулярной основе, то, я считаю, нужно убирать любой мусор который так или иначе отвлекает внимание от непосредственной цели визита на сайт. Тем более если под этим мусором подразумевается **РАЗДРАЖИТЕЛЬ** (большой дублирующий баннер) и **РЕКЛАМА**.

 Конкретный пример относительно данного сайта: после логина я хочу СРАЗУ видеть список моих карт и сумм на них, а не пролистывать до этого списка КАЖДЫЙ РАЗ при логине, перезагрузке или переходе на начальную страницу личного кабинета.
