### ISSUE TITLE
underconsideration.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5549]
***Site***: http://www.underconsideration.com/brandnew/archives/2017_brand_new_conference_early-bird_ends_friday_night.php
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27770330-16d578de-5f3d-11e7-9666-d72938b7e87e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.50
Spyware filter | 1.0.13.6
Social media filter | 1.0.20.81
Annoyances filter | 1.0.14.88
German filter | 1.0.35.27
Mobile ads filter | 1.0.8.82
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
