### ISSUE TITLE
juraforum.de - Social widgets

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5550]
***Site***: http://www.juraforum.de/internetrecht/internetseite-wwwberlincom-wird-durch-betreiber-hinweis-gerettet-590192
***Description***: Social buttons/widgets

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27770397-5e8bde9c-5f3e-11e7-9bce-1274664bfbbc.png)

![image](https://user-images.githubusercontent.com/10995998/27770400-7b754de0-5f3e-11e7-82f6-4db7d20f71a1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.50
Spyware filter | 1.0.13.6
Social media filter | 1.0.20.81
Annoyances filter | 1.0.14.88
German filter | 1.0.35.27
Mobile ads filter | 1.0.8.82
Safari filter | 1.0.3.52

**Comment by danidoedel** [comment]
`juraforum.de##.social-media-bar`

**Comment by AdamWr** [comment]
Fixed.
