### ISSUE TITLE
Ads in the app RU-ES Translator on Android

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5551]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Ads in the app RU-ES Translator on Android - https://play.google.com/store/apps/details?id=com.vertaler.rues

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29478021/27771726-8438aab6-5f5d-11e7-8b39-bbb3c1aca8d8.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
App: | RU-ES Translator
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard filters: | 2, 3, 4, 14, 1, 9, 11
Ticket ID (if exists): | 1534099

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Google ads. They are blocked even without https filtering.
I need web-requests log.

**Comment by kbahlyk** [comment]
https://qcrm.supportyourapp.com/message/attachment/1399162/debug.txt
https://qcrm.supportyourapp.com/message/attachment/1399163/license.tx
https://qcrm.supportyourapp.com/message/attachment/1399164/state.txtt

**Comment by Bohdan-SUP** [comment]
@Alex-302 
14:10:
[debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/1120483/debug.3.txt)

**Comment by Alex-302** [comment]
@Bohdan-SUP it is wrong log. I need web-requests(HTTP) log.

**Comment by kbahlyk** [comment]
Asked customer to send new logs.

**Comment by Alex-302** [comment]
Any news?

**Comment by Alex-302** [comment]
@kbahlyk

**Comment by ypetruk** [comment]
@Alex-302 still no response from the customer

**Comment by Alex-302** [comment]
Ok.
