### ISSUE TITLE
Пропущенный баннер http://fanserials.tv

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#5552]
Сайт http://fanserials.tv/913-doktor-haus-6-sezon-6-seriya-izvestnye-neizvestnye.html внизу появляется баннер при входе. Adguard 2.9.70, фильтры по-умолчанию, фильтрация качественная, HTTP вкл, HTTPS вкл
На этом сайте точно такой же баннер, логи делать не стал 
http://moiserialy.net/doktor-haus-smotret-onlajn/6-sezon/8-seriya
![screenshot_2017-07-02-20-13-51](https://user-images.githubusercontent.com/22351242/27772010-255d9dde-5f63-11e7-90ff-6cf759a3b0a9.png)
Логи сделать не получается: ( Я не знаю почему, но не выходит у меня,  что лог запросов, что har. Их просто нет в папке

**Comment by ministr91** [comment]
Странно, перезагрузил телефон и снова заработало. Кажется, я нашел баг, но об этом потом.
Вот логи. 20:34 июль 2 число сделал 2 сайта, которые выше

**Comment by ministr91** [comment]
http://my-files.ru/ifqhf2

**Comment by ministr91** [comment]
![screenshot_2017-07-02-20-34-44](https://user-images.githubusercontent.com/22351242/27772229-9476dc8c-5f66-11e7-8407-5c2635e5b3b7.png)

**Comment by ministr91** [comment]
Можешь название темы изменить? Вставь туда еще сайт moyserialy.net. Баннер то один и тот же, решил не создавать еще 1 тему

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||d-ughwashes.ru^$third-party
```

**Comment by ministr91** [comment]
Проблема осталась, фильтры обновил

**Comment by ministr91** [comment]
Еше раз обновил фильтры, проблемы нет
