### ISSUE TITLE
Пропущенная реклама http://www.rambler.ru

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#5553]
При входе с телефона на полную версию сайта http://www.rambler.ru появляется реклама Яндекс. Директ. Раньше ее не было, в последнее время появилась. Adguard 2.9.70, фильтры по-умолчанию, HTTP вкл, HTTPS вкл, Фильтрация качественная. Время 20:35 июль 2 число http://my-files.ru/ifqhf2
![screenshot_2017-07-02-20-35-36](https://user-images.githubusercontent.com/22351242/27772255-eda4035c-5f66-11e7-8401-b51282910da1.png)

**Comment by Alex-302** [comment]
Повторяется ещё?

**Comment by ministr91** [comment]
Да

**Comment by Alex-302** [comment]
Проверь такое правило:
```
||redsquare.rambler.ru^
```

**Comment by ministr91** [comment]
Реклама исчезла, но пропала часть картинок. Грузится без рекламы с картинками, потом частично картинки пропадают

**Comment by ministr91** [comment]
![screenshot_2017-07-03-21-09-36](https://user-images.githubusercontent.com/22351242/27803803-14ba98f2-6034-11e7-982f-991633f4f808.png)
![screenshot_2017-07-03-21-10-14](https://user-images.githubusercontent.com/22351242/27803810-1a693e2a-6034-11e7-9b18-288df8594b9c.png)

**Comment by evgeniy-ADG** [comment]
Вот тут 1153494 еще жалоба, описание проблемы и скриншоты.

**Comment by ministr91** [comment]
Кинь ссылку, искать долго. У меня логи есть и скрины

**Comment by ministr91** [comment]
@evgeniy-ADG

**Comment by Alex-302** [comment]
Удали правило и обновись минут через 20, не раньше.

**Comment by ministr91** [comment]
Глухо все. Вечером проверю еще

**Comment by Alex-302** [comment]
ок. Фильтры не пересобрались ещё.

**Comment by ministr91** [comment]
Проблема осталась

**Comment by ministr91** [comment]
![screenshot_2017-07-04-20-36-16](https://user-images.githubusercontent.com/22351242/27839233-80ba5afa-60f8-11e7-9f4f-847138099995.png)

**Comment by ministr91** [comment]
Еще раз обновил - проблема не исчезла. Есть варианты решения проблемы? С этим Яндекс Директ стало в последнее время как-то слишком много проблем и не только у меня

**Comment by ministr91** [comment]
Здесь что-то писали про Яндекс. Транспорт https://4pda.ru/forum/index.php?showtopic=601691&view=findpost&p=62909745

**Comment by Alex-302** [comment]
> Еще раз обновил - проблема не исчезла. Есть варианты решения проблемы? С этим Яндекс Директ стало в последнее время как-то слишком много проблем и не только у меня

У меня чисто, реклама пропала после вчерашнего обновления.

**Comment by ministr91** [comment]
@Alex-302 , ты мне не веришь? :(
![screenshot_2017-07-05-12-52-54](https://user-images.githubusercontent.com/22351242/27859323-0a8d6140-6181-11e7-9026-ae9643d549eb.png)
![screenshot_2017-07-05-12-53-25](https://user-images.githubusercontent.com/22351242/27859326-0f8023cc-6181-11e7-9c95-8988f5c7c221.png)

**Comment by ministr91** [comment]
Я обычно не расписываю какие фильтры у меня стоят, сразу пишу по-умолчанию, но раз тут такое, то напишу: английский, фильтр счетчиков и системы аналитики, фильтр виджетов социальных сетей, фильтр раздражителей, русский фильтр, фильтр мобильной рекламы

**Comment by Alex-302** [comment]
Проверь обновления. Пару дней назад исправили.

**Comment by ministr91** [comment]
@Alex-302, неужели ответил? @ameshkov даже забил на эту тему. Рамблер сменил сайт и теперь там все по-другому отображается, так что эта проблема неактуальна

**Comment by ministr91** [comment]
Закрывай тему

**Comment by ministr91** [comment]
Реклама МТС появляется на мобильной версии, @Alex-302 можешь проверить?

**Comment by ministr91** [comment]
И еще видео реклама машины, во время чтения новости наверху

**Comment by ministr91** [comment]
И еще Яндекс. Директ

**Comment by ministr91** [comment]
@ameshkov ты тут?

**Comment by evgeniy-ADG** [comment]
упс, случайно удалил :/ @ameshkov тебя просили.

**Comment by ministr91** [comment]
@evgeniy-ADG, хоть ты рекламу видишь?

**Comment by ameshkov** [comment]
@ministr91 ну я потыкался немного, разные новости почитал там, не вылезло

**Comment by ministr91** [comment]
@ameshkov, вечером кину логи и видео

**Comment by ministr91** [comment]
Странно, ее нет. Реклама может быть при московском wifi сети, с в домашних условиях нет?

**Comment by Alex-302** [comment]
Нет. Там скрипт из кода вырезается, + есть правило JS.

**Comment by ministr91** [comment]
Она опять появилась!!! Я вошел на сайт и тут баннер на весь экран. Я сразу закрыл вкладку, приготовился записывать видео и логи, но потом она опять пропала, как-будто ничего и не было

**Comment by ministr91** [comment]
Я уже и перезагружал телефон и кэш чистил - реклама появляется рандомно, не могу вовремя логи включить и видео. Она появляется, а потом пропадает

**Comment by ministr91** [comment]
Попробую снять видео и логи, когда опять это повторится

**Comment by ministr91** [comment]
Вот этот баннер появляется иногда на весь экран https://ads.adfox.ru/171817/goLink?eid2=6275079&eid1=00000046598461701F9967A08EC38201&puid57=7078%3A2323%3A9572%3A6933%3A7120%3A7104&puid54=2&p5=etnbv&puid4=8&p1=bsxdj&pr=ofjj&rand=exlqofh&rqs=kXLZAA4AAAC7xIlZJ_cPSTHavUZU14hp&eid3=254B1923559702E2&puid63=1&puid11=14&hash=f7a2445cb427ad8d&p2=etsa&puid3=5

**Comment by ministr91** [comment]
Я ее нашел. Записал логи и видео скинул в архив. Суббота, 0:19 время московское. На видео видно, что после перехода появляется баннер. В прошлый раз я нажал на него и перешел по ссылке, которая выше. В этот раз он сам исчез, но проблема существует. http://my-files.ru/76pq12
@Alex-302 , @ameshkov и молчаливый @evgeniy-ADG гляньте что там

**Comment by Alex-302** [comment]
Я вижу там только за воскресенье и свежее. Субботнего нет.

**Comment by ministr91** [comment]
Ошибся со временем. Это было сегодня ночью, среда.

**Comment by ministr91** [comment]
Но в любом случае это неважно, проблема на видео есть, логи тоже

**Comment by ministr91** [comment]
Тему откроешь? @Alex-302

**Comment by ministr91** [comment]
@ameshkov , кто-нибудь...

**Comment by ameshkov** [comment]
@Alex-302 har-файл я не смотрел, но посмотрел правила для рамблера.

$replace-правило очень хреновое, оно ко всем файлам применяется. Ты сделай хотя бы `~script,~stylesheet,~xmlhttprequest`, чтобы только к HTML применять.

И по видео - там не яндекс директ, а видимо попап какой-то пролезть пытается

**Comment by ministr91** [comment]
Пытается пролезть баннер, который ведет на этот сайт https://ads.adfox.ru/171817/goLink?eid2=6275079&eid1=00000046598461701F9967A08EC38201&puid57=7078%3A2323%3A9572%3A6933%3A7120%3A7104&puid54=2&p5=etnbv&puid4=8&p1=bsxdj&pr=ofjj&rand=exlqofh&rqs=kXLZAA4AAAC7xIlZJ_cPSTHavUZU14hp&eid3=254B1923559702E2&puid63=1&puid11=14&hash=f7a2445cb427ad8d&p2=etsa&puid3=5

**Comment by ameshkov** [comment]
Может https-фильтрация отрубилась для этого домена и так пролез код с него? Не похоже это на системную проблему с фильтрами

**Comment by ameshkov** [comment]
Рестарт адгарда помогал?

**Comment by Alex-302** [comment]
> $replace-правило очень хреновое

изменил.

**Comment by ministr91** [comment]
@ameshkov Конечно же рестарт не помогал, проблема давно уже. 
@Alex-302 изменил там что-то, я протестирую сайт и скажу что да как

**Comment by ministr91** [comment]
А с этим что скажете? https://github.com/AdguardTeam/AdguardFilters/issues/6199#issuecomment-322009206

**Comment by ministr91** [comment]
Проблема не решена. Теперь это появляется. Да и хорошо бы открыть тему, а то ждать ответа придется мне долго
![screenshot_2017-08-15-16-09-25](https://user-images.githubusercontent.com/22351242/29317407-7c355384-81d4-11e7-86dc-effaa08271cb.png)

**Comment by ameshkov** [comment]
Да елки почему только у тебя это происходит не могу понять:(

**Comment by ameshkov** [comment]
Если проверить сертификат у rambler.ru - там Adguard Personal CA или нет? Кликом по "замку" в адресной строке

**Comment by ministr91** [comment]
Да, рамблер сертификат и adguard

**Comment by ministr91** [comment]
![screenshot_2017-08-22-01-45-20](https://user-images.githubusercontent.com/22351242/29541316-ed622c9c-86db-11e7-9a46-dfe6649b581f.png)

**Comment by ministr91** [comment]
@Alex-302 и @ameshkov

**Comment by ameshkov** [comment]
Я короче попользуюсь рамблером, попытаюсь поймать. Пока мы не поймаем сами, не сможем ничего сделать.

**Comment by ministr91** [comment]
Не стоит, она пропала на днях. Теперь все чисто.
@ameshkov глянь что тут с логом HAR https://github.com/AdguardTeam/AdguardFilters/issues/6199#issuecomment-324058997
