### ISSUE TITLE
RU Adlist: Counters blocks button "Поделиться" in Яндекс.Фотки

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5554]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
RU Adlist: Counters blocks button "Поделиться" in Яндекс.Фотки

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29478021/27772248-dc453e5a-5f66-11e7-81a5-256725596c75.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29478021/27772241-c7100efc-5f66-11e7-98af-eb1e94905cb8.png)

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

</details>

***System configuration***

</details>

Information | value
--- | ---
Operating system: | Windows
Browser: | Firefox v42
Adguard version: | 6.2
Adguard driver (Windows): | WFP 
Stealth mode options(Windows) | ON
Adguard filters: | Russian, English, Spyware, Social media, Filter unblocking useful ads, EasyList, RU AdList, RU AdList: Counters 
Ticket ID (if exists): | 1018433

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Автор фильтра уже починил.
