### ISSUE TITLE
Ads in the app TIViewer on Android

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5555]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Ads in the TIViewer app https://play.google.com/store/apps/details?id=com.jiwoosoft.tiviewer&amp;hl=ko

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29478021/27783389-afc82612-5fde-11e7-92ef-eaac3ce0a0c6.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Android
Adguard version: | 2.8.76
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard filters: | English, Social media, Annoyances, Russian, Mobile ads
Ticket ID (if exists): | 1584519

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce even without HTTPS filtering.

**Comment by Alex-302** [comment]
I need HTTP log.

**Comment by Alex-302** [comment]
@kbahlyk

**Comment by ypetruk** [comment]
we sent the request for logs to the customer, but still haven`t got a response from him

**Comment by Alex-302** [comment]
Ok.
