### ISSUE TITLE
Ads in the app "Instant Email Address" on Android

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5556]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Ads in the app "Instant Email Address" on Android - https://play.google.com/store/apps/details?id=air.kukulive.mailnow

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29478021/27784190-f49e6b5e-5fe1-11e7-835f-d71e1e167928.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

</details>

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.111
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard filters: | English, Socail media, Spyware, Annoyances, Russian, Mobile ads
Ticket ID (if exists): | 1502461

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by hal109** [comment]
Adguard beta was updated, and now I'm using Adguard version 2.9.133. I'm using Adguard filters off except mobile filter, cause I'm using 280 blocker [https://280blocker.net/files/280blocker_adblock.txt]
as the user filter.

Please help me in removing Amazon ads in the mailbox.

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||m.kuku.lu/smphone.footer.blockspecial.php
```

**Comment by hal109** [comment]
Sorry. The ads don't remove.
What should I do?

2017/07/03 21:21 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment]
Maybe HTTPS filtering is not enabled. I can reproduce this ad only when HTTPS filtering is disabled.

**Comment by hal109** [comment]
HTTPS filtering is enabled. but ads don't remove.

2017/07/04 1:22 "Alex" <notifications@github.com>:

**Comment by hal109** [comment]
I send the filtering log. Please help me.

2017/07/04 1:22 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment]
@hal109 I don't see filtering log in `1502461`

**Comment by hal109** [comment]
Sorry. I have tried uninstalling and re-installing Adguard twice. Maybe
that's the reason.

Adguard ver. 2.9.133
HTTPS Filtering enabled
Ad blocker: Moble Filter
User Filter: 280 blocker
[https://280blocker.net/files/280blocker_adblock.txt]

In fact ads don't remove. And then I tryed blocking the app from the
Filtering Log. At first it looks that the ads remved, but can't connect.
net::ERR_CONNECTION_REFISED

Then checked
'Apply to 捨てメアド request only' or
'Give a higher priority to the rule', the app can connect but the amazon
ads shows.

Please tell me what I'm able to do next.




2017/07/04 20:05 "Alex" <notifications@github.com>:

**Comment by hal109** [comment]
Sorry. I made a mistake. I have uninstalled Adguard and re-installed again.

Adguard ver. 2.9.135
HTTPS Filtering enabled
Ad blocer: Mobile Filter
User Filter: 280 blocker
[https://280blocker.net/files/280blocker_adblock.txt]


In fact ads don't remove. And then I tryed blocking the app from the
Filtering Log. At first it looks that the ads remved, but can't connect.
net::ERR_CONNECTION_REFISED

Then checked
'Apply to 捨てメアド request only' or
'Give a higher priority to the rule', the app can connect but the amazon
ads shows.

Please tell me what I'm able to do next.

2017/07/04 20:49 "Hal Oyama" <noir.mont.blanc@gmail.com>:

**Comment by Alex-302** [comment]
Sorry, I don't know. That ad must be blocked by mobile filter when https filtering(white list mode) is enabled.

**Comment by Alex-302** [comment]
Please capture HAR file and send me
https://kb.adguard.com/en/android/solving-problems/har

**Comment by hal109** [comment]
2017/07/10 18:37 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment]
@hal109 what is it?

**Comment by hal109** [comment]
I don't know how to capture Adguard har then I've sent Adguard har itself.
Please open this file by text.

2017/07/10 20:28 "Alex" <notifications@github.com>:

**Comment by Alex-302** [comment]
How to capture:
https://kb.adguard.com/en/android/solving-problems/har

**Comment by hal109** [comment]
2017/07/10 21:05 "Alex" <notifications@github.com>:
