### ISSUE TITLE
Please add rules to block RevenueStripe tracking and ads

### ISSUE THREAD

**Issue by stvrly** [AdguardTeam/AdguardFilters#55563]
Seen in the HTML email newsletter from the Seattle Times. It contains a 1x1 tracking pixel from **rs-stripe.seattletimes.com** and an ugly animated image ad from **tr.rev-stripe.com** (redirected from a generic **seattletimes.com** URL).

Adding these rules blocks both:
`||rs-stripe.seattletimes.com^`
`||rev-stripe.com^`

Could the first one be made more generic like this:
`||rs-stripe.*^`

The goal would be to block the **rs-stripe** tracking pixel from all domains, but I'm not exactly sure how to create a rule to block every domain that starts with a certain string.

**Comment by Alex-302** [comment]
@stvrly Could you please forward sample email to filters@adguard.com(+ link to this issue)

**Comment by stvrly** [comment]
Sample email sent.

**Comment by Alex-302** [comment]
@stvrly It seems I removed it:) Too much emails every day. Could you please send it again?

**Comment by stvrly** [comment]
@Alex-302 Of course. Sending momentarily.

**Comment by Alex-302** [comment]
> ||rs-stripe.seattletimes.com^

It seems this rule will break content
![image](https://user-images.githubusercontent.com/8361299/82650939-23b45d00-9c24-11ea-87da-7d2c0ebfb4b1.png)

On another email services it is proxified:
![image](https://user-images.githubusercontent.com/8361299/82651090-5a8a7300-9c24-11ea-859b-ed8990e4943f.png)
