### ISSUE TITLE
ip-api.com

### ISSUE THREAD

**Issue by vladc** [AdguardTeam/AdguardFilters#55571]
We kindly ask that you remove ip-api.com from the tracking_servers and mobile lists. 

It's a simple IP Geolocation API, which does not log or track API calls, and it has a very strict privacy policy. 

ip-api.com being on your lists is an annoyance for our users (the developers), since they usually have to implement the lookup directly on their servers.

We also don't understand why similar websites, such as ipinfo.io, ipstack.com, ipdata.co and many others that have been operating for years are not on the same list.

**Comment by Alex-302** [comment]
EasyPrivacy filter also containt blocking rule for this domain.
