### ISSUE TITLE
firstone.tv - antiadblock script

### ISSUE THREAD

**Issue by vishchakl** [AdguardTeam/AdguardFilters#5559]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
As reported by user:
Adguard detected FirstOne TV is financed by advertising. You need to disable your Adblocker to watch this stream:
https://www.firstone.tv/Live/United-States-(USA)/CNN-USA-33

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Adblocking detected (screenshot):</summary>

![screen shot 2017-07-03 at 10 54 43 pm](https://user-images.githubusercontent.com/29872276/27806361-ce359986-6042-11e7-83cc-d6af60f60cf8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None
Adguard filters: | English, Spyware, Social media, Russian, Experimental, Annoyances
Ticket ID (if exists): | 1406620

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
