### ISSUE TITLE
punisoku.blogo.jp

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#55614]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[NSFW] URL: `http://punisoku.blogo.jp/archives/16981426.html`
1. random ads injected via inline-script (marked by a red line on the SS below)
2. affiliate links to a shopping site (dlsite.com) with tons of images (blue lines)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot1 (nsfw):</summary>

![punisoku](https://user-images.githubusercontent.com/58900598/82154295-c927a380-98a7-11ea-8a82-b763e53b00e2.png)
</details>
<details><summary>Screenshot2 (nsfw):</summary>

![punisoku1](https://user-images.githubusercontent.com/58900598/82154290-c462ef80-98a7-11ea-8521-13ed44666629.png)

</details><br/>

***Steps to reproduce the problem***:

Just visit the site.

***System configuration***

**Filters:**

Base, Tracking, & Japanese

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Brave 1.8.96
AdGuard version:                       | Ext 3.4.19
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Default

**Notes**
While
`punisoku.blogo.jp##a[href^="https://www.dlsite"] + div + div`
can hide the 1., adding
`punisoku.blogo.jp#%#//scriptlet('abort-current-inline-script', 'url', 'Math.random')`
to prevent these large images from being loaded will be a good trade-off for those platforms supporting scriptlets.
`punisoku.blogo.jp##.main-column-inner > a[href^="https://www.dlsite"]`
can also be added to hide an image above the 1.

For 2., maybe `punisoku.blogo.jp#?#.plugin-memo:has(a[href^="https://www.dlsite"])`

**Comment by Alex-302** [comment]
Added the rule for `1-red`.
Is whole block with `1-blue` is ad or only 12-14?

**Comment by Yuki2718** [comment]
> 
> 
> Added the rule for `1-red`.
> Is whole block with `1-blue` is ad or only 12-14?

Not only 12-14, it was just a limitation of SS. Well, now I found there are also those include 'href = "http://www.dlsite' so anything selected by `#?#.plugin-memo:has(a[href*="www.dlsite"])` can be blocked. And `##.main-column-inner > a[href^="https://www.dlsite"]` too.

**Comment by Alex-302** [comment]
Ok, added:
```
punisoku.blogo.jp#?#.plugin-memo:has(a[href*="www.dlsite"])
punisoku.blogo.jp##.main-column-inner > a[href^="https://www.dlsite"]
```
