### ISSUE TITLE
http://batona.net/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5561]
http://batona.net/93031-podb.html

With Adguard

![image](https://user-images.githubusercontent.com/15856304/27821624-96b004d8-60ab-11e7-99e4-4750e308499a.png)

W/o Adguard:

![image](https://user-images.githubusercontent.com/15856304/27821614-8c1f364c-60ab-11e7-9450-3298ddc2db06.png)

***System configuration***

Information | value
--- | ---
Operating system: | all
Browser: | all
Adguard version: | any
Adguard filters: | Russian
Ticket ID: | 1516094

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
