### ISSUE TITLE
Anti-adblocker on beritauaja.com

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5562]
***Description***:
* **Current behaviour**: 

Anti-adblocker on http://www.beritauaja.com/?m=1

![screen shot 2017-07-04 at 5 37 31 pm](https://user-images.githubusercontent.com/27874000/27834388-7e72bcb0-60df-11e7-8d0a-fe8ccb1866f9.png)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.133
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On 
Ticket ID: | 1551511

**Comment by Alex-302** [comment]
Fixed
