### ISSUE TITLE
Anti-adblocker on onet.pl 

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5563]
***Description***:
* **Current behaviour**: 

Anti-adblocker on onet.pl 

![screen shot 2017-07-04 at 6 21 37 pm](https://user-images.githubusercontent.com/27874000/27835907-a9845318-60e5-11e7-87bc-3eec63b1e4bd.png)

Ticket ID: | 1585603

**Comment by Alex-302** [comment]
Not reproduced with Polish filter.
