### ISSUE TITLE
Ads on: wp.pl

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5564]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Ads on: wp.pl

![screen shot 2017-07-04 at 6 25 54 pm](https://user-images.githubusercontent.com/27874000/27836015-3de64bba-60e6-11e7-96b1-440f21cc60f5.png)

Ticket ID: | 1585603

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
