### ISSUE TITLE
seedoff.tv - ads

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5565]
Missed ad block.

 URL:

http://www.seedoff.tv/

<details><summary>Screenshot:</summary>

![screen shot 2017-07-04 at 20 50 20](https://user-images.githubusercontent.com/28726429/27839540-b3b31882-60fa-11e7-9f8c-f2228fc838e5.png)

</details>

<br>
***System configuration***

Information | value
--- | ---
Operating system: | macOS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 12, 14

**Comment by Alex-302** [comment]
Fixed
