### ISSUE TITLE
robotbike.co

### ISSUE THREAD

**Issue by kulfoon** [AdguardTeam/AdguardFilters#55672]
***Description***:

AdGuard Base Filter causes breakage - blur, perhaps incorrectly blocked anti-adblock, the issue is gone after disabling AdGuard Base filter.

* **Current behaviour**: 

Breakage / blur

<details><summary>Screenshot:</summary>

![capture_086_18-05-2020_19-22-39](https://user-images.githubusercontent.com/43844449/82242365-03dc1b00-993e-11ea-9401-dec75412df10.gif)

</details><br/>

* **Expected behaviour**: 

No breakage / blur

<details><summary>Screenshot:</summary>

![capture_087_18-05-2020_19-22-49](https://user-images.githubusercontent.com/43844449/82242377-08083880-993e-11ea-9077-e9d8212e9a54.gif)

</details><br/>

***Steps to reproduce the problem***:

Visit the website

***System configuration***

**Filters:**

<details>
<summary>spoiler</summary>

`uBlock filters`
`uBlock filters – Badware risks`
`uBlock filters – Privacy`
`uBlock filters – Resource abuse`
`uBlock filters – Unbreak`
`AdGuard Base`
`EasyList`
`AdGuard Tracking Protection`
`EasyPrivacy`
`Fanboy’s Enhanced Tracking List`
`uBlock filters – Annoyances`
`Peter Lowe’s Ad and tracking server list`
`Adblock Warning Removal List`

</details>

Information                            | Value
---                                    | ---
Operating system:                      | Win 7 Pro SP1 64bit
Browser:                               | Firefox 76 64bit
AdGuard version:                       | uBlock Origin 1.27.2

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
