### ISSUE TITLE
wormaxio.org

### ISSUE THREAD

**Issue by kulfoon** [AdguardTeam/AdguardFilters#55674]
***Description***:

AdGuard Base Filter causes breakage - red blur, perhaps incorrectly blocked anti-adblock, the issue is gone after disabling AdGuard Base filter.

* **Current behaviour**: 

Breakage / red blur

<details><summary>Screenshot:</summary>

![capture_088_18-05-2020_19-37-51](https://user-images.githubusercontent.com/43844449/82243076-3fc3b000-993f-11ea-9a18-8981bf81ea24.gif)

</details><br/>

* **Expected behaviour**: 

No breakage / red blur

<details><summary>Screenshot:</summary>

![capture_089_18-05-2020_19-37-54](https://user-images.githubusercontent.com/43844449/82243086-43efcd80-993f-11ea-977e-b9176c74bffb.gif)

</details><br/>

***Steps to reproduce the problem***:

Visit the website

***System configuration***

**Filters:**

<details>
<summary>spoiler</summary>

`uBlock filters`
`uBlock filters – Badware risks`
`uBlock filters – Privacy`
`uBlock filters – Resource abuse`
`uBlock filters – Unbreak`
`AdGuard Base`
`EasyList`
`AdGuard Tracking Protection`
`EasyPrivacy`
`Fanboy’s Enhanced Tracking List`
`uBlock filters – Annoyances`
`Peter Lowe’s Ad and tracking server list`
`Adblock Warning Removal List`

</details>

Information                            | Value
---                                    | ---
Operating system:                      | Win 7 Pro SP1 64bit
Browser:                               | Firefox 76 64bit
AdGuard version:                       | uBlock Origin 1.27.2

**Comment by AdamWr** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/13c79c629ecf900adc74c0201be9fae44f1f99a7
