### ISSUE TITLE
worldfreeware.com

### ISSUE THREAD

**Issue by kulfoon** [AdguardTeam/AdguardFilters#55677]
Anti-adblock, I wasn't sure whether to comment in the old issue  or to make a new issue, so [I did comment in the old issue](https://github.com/AdguardTeam/AdguardFilters/issues/15839#issuecomment-630343192) and opened a new issue as well, to provide the link for sure, coz the AdGuard bot didn't reopen the old issue.

**Comment by AdamWr** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/13c79c629ecf900adc74c0201be9fae44f1f99a7
