### ISSUE TITLE
pesprofessionals.com

### ISSUE THREAD

**Issue by kulfoon** [AdguardTeam/AdguardFilters#55675]
***Description***:

AdGuard Base Filter causes breakage - blur, perhaps incorrectly blocked anti-adblock, enabling regional ARA list in uBO doesn't fix the issue, the issue is gone after disabling AdGuard Base filter,

* **Current behaviour**: 

Breakage / blur

<details><summary>Screenshot:</summary>

![capture_090_18-05-2020_19-41-12](https://user-images.githubusercontent.com/43844449/82243408-d7290300-993f-11ea-8a82-1b7b501a0b31.gif)

</details><br/>

* **Expected behaviour**: 

No breakage / blur

<details><summary>Screenshot:</summary>

![capture_091_18-05-2020_19-41-21](https://user-images.githubusercontent.com/43844449/82243419-dabc8a00-993f-11ea-8504-8b125e0690a1.gif)

</details><br/>

***Steps to reproduce the problem***:

Visit the website

***System configuration***

**Filters:**

<details>
<summary>spoiler</summary>

`uBlock filters`
`uBlock filters – Badware risks`
`uBlock filters – Privacy`
`uBlock filters – Resource abuse`
`uBlock filters – Unbreak`
`AdGuard Base`
`EasyList`
`AdGuard Tracking Protection`
`EasyPrivacy`
`Fanboy’s Enhanced Tracking List`
`uBlock filters – Annoyances`
`Peter Lowe’s Ad and tracking server list`
`Adblock Warning Removal List`

</details>

Information                            | Value
---                                    | ---
Operating system:                      | Win 7 Pro SP1 64bit
Browser:                               | Firefox 76 64bit
AdGuard version:                       | uBlock Origin 1.27.2

**Comment by AdamWr** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/13c79c629ecf900adc74c0201be9fae44f1f99a7
