### ISSUE TITLE
BlockAdblocker script on http://adpop.me/URKT

### ISSUE THREAD

**Issue by Mav3r1x** [AdguardTeam/AdguardFilters#5567]
Website: http://adpop.me/URKT

Tried Methods: Following rules doesn't work:
`adpop.me$$script[tag-content="eval(function (p, a, c, k, e, d)"][max-length="16000"] `
`@@||adpop.me^$generichide`

Comment: Using the second rule ( the one with generichide ) actually doesn't the redirect the site to "BlockAdblock" page but still you can't go next on the site.

Please post a solution.

**Comment by Alex-302** [comment]
Not reproduced. I need screenshot.
Please check:
```
@@||adpop.me^$domain=adpop.me
||s3.amazonaws.com^$domain=adpop.me
||pushresponse.net^$third-party
```

**Comment by Mav3r1x** [comment]
Screenshot: http://prntscr.com/fskran

I have applied following rules:

```
@@||adpop.me^$domain=adpop.me
||s3.amazonaws.com^$domain=adpop.me
||pushresponse.net^$third-party
@@||adpop.me^$generichide
```

**Comment by Alex-302** [comment]
Do you use only one ad blocker?

**Comment by Alex-302** [comment]
Please check for updates after 1-1.5 hours.

**Comment by Mav3r1x** [comment]
@Alex-302 thanks man. It is working fine now.
