### ISSUE TITLE
stau.info - Social widget - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5568]
***Site***: https://stau.info/
***Description***: Social widgets and social widget leftover. Ad in sidebar. Whatsapp share button on mobile devices.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27909134-8477dd68-624f-11e7-96a4-c95a49223277.png)

![image](https://user-images.githubusercontent.com/10995998/27909180-b8756fe0-624f-11e7-9c43-d594ed287feb.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.85
Spyware filter | 1.0.13.17
Social media filter | 1.0.20.89
Annoyances filter | 1.0.15.7
German filter | 1.0.35.32
Mobile ads filter | 1.0.8.86
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
