### ISSUE TITLE
spicytrannyhd.com [NSFW]

### ISSUE THREAD

**Issue by kulfoon** [AdguardTeam/AdguardFilters#55680]
***Description***:

AdGuard Enhanced Tracking Filter causes breakage - missing images, images start loading after disabling AdGuard Enhanced Tracking Filter.

* **Current behaviour**: 

breakage - missing images

<details><summary>Screenshot NSFW:</summary>

![capture_097_18-05-2020_20-12-08](https://user-images.githubusercontent.com/43844449/82246075-57516780-9944-11ea-9c09-9e055caff00a.gif)

</details><br/>

* **Expected behaviour**: 

No breakage - no missing images

<details><summary>Screenshot NSFW:</summary>

![capture_096_18-05-2020_20-11-58](https://user-images.githubusercontent.com/43844449/82246089-5caeb200-9944-11ea-98cd-1bebe8f66be5.gif)

</details><br/>

***Steps to reproduce the problem***:

Visit the website

***System configuration***

**Filters:**

<details>
<summary>spoiler</summary>

`uBlock filters`
`uBlock filters – Badware risks`
`uBlock filters – Privacy`
`uBlock filters – Resource abuse`
`uBlock filters – Unbreak`
`AdGuard Base`
`EasyList`
`AdGuard Tracking Protection`
`EasyPrivacy`
`Fanboy’s Enhanced Tracking List`
`uBlock filters – Annoyances`
`Peter Lowe’s Ad and tracking server list`
`Adblock Warning Removal List`

</details>

Information                            | Value
---                                    | ---
Operating system:                      | Win 7 Pro SP1 64bit
Browser:                               | Firefox 76 64bit
AdGuard version:                       | uBlock Origin 1.27.2

**Comment by kulfoon** [comment]
I've been on the website to check the fix, have been clicking on videos to see whether they work until it redirected me to twin / sister page: `spicytranny.com` which suffers the same issue, so the fix have to include the new domain as well.

**Comment by AdamWr** [comment]
Fixed.

**Comment by kulfoon** [comment]
Funny, it has escalated to a critical issue, I've searched deeper and discovered over [200 broken pornsites](https://publicwww.com/websites/%3Cdiv+class%3D%5C%22tbookshare%5C%22%3E/) which suffers the same issue, so either remove `||webclicks24.com^$third-party` filter or....add over 200 domains to the whitelist filter, this will become the longest filter in the whole AdGuard Tracking Protection list - 2x longer than the actual leader: 
https://github.com/AdguardTeam/AdguardFilters/blob/4ed095572d8e37812feda508f222023ef409fa93/SpywareFilter/sections/whitelist.txt#L1689

But having a free account on publicwww.com reveals only a half of the search results (domains) in this case, so unless someone from the AdGuard Filters team has a paid premium account with full acccess,  the bad filter should be removed from the list.

**Comment by AdamWr** [comment]
Ok, I removed problematic rule.
Thank you.
