### ISSUE TITLE
verkehrsinformation.de - Ad leftover - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5569]
***Site***: http://verkehrsinformation.de/
***Description***: Ads and ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27909214-f06ba540-624f-11e7-8650-c4c8967770e5.png)

![image](https://user-images.githubusercontent.com/10995998/27909223-facc0bb0-624f-11e7-8e95-f03cd99a60f9.png)

![image](https://user-images.githubusercontent.com/10995998/27909263-2c6bf07c-6250-11e7-8dbd-17bb41e1d4af.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.85
Spyware filter | 1.0.13.17
Social media filter | 1.0.20.89
Annoyances filter | 1.0.15.7
German filter | 1.0.35.32
Mobile ads filter | 1.0.8.86
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
