### ISSUE TITLE
Блокировка cookies

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#55709]
Здравствуйте,

Задача №1:
Нужно полностю заблокировать все файлы cookie КРОМЕ определённых сайтов.

Например cookies этих сайтов мне НУЖНЫ (то-есть блокировать cookies нижеперечисленных сайтов НЕ нужно):
*.yandex.* (все домены Яндекс)
ficbook.net
aura.top

Cookies остальных сайтов мне нужно полностью заблокировать. Есть ли такая возможность? Если да, то какие правила я должен добавить? Про модификатор $stealth знаю, он не подходит, так как выключает не только блокировку cookies, но и функционал антитрекинга для конкретного сайта.

Задача №2:
Нужно заблокировать турбо страницы Яндекса. Есть ли такая возможность? Я перерыл уже весь интернет, но решения так и не нашёл. Скрипт с Greasy Fork пробовал не помогает (вернее раньше помогал, а сейчас перестал)
Вот ссылка на тот ссылка на тот скрипт, который уже не работает:
https://greasyfork.org/ru/scripts/396403-%D1%83%D0%B4%D0%B0%D0%BB%D0%B8%D1%82%D1%8C-%D1%8F%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D1%82%D1%83%D1%80%D0%B1%D0%BE

Техническая информация:
ОС: Андроид
Версия Adguard: 3.3.2
Браузер: Яндекс

**Comment by Alex-302** [comment]
1. По шаблону 
`$cookie,domain=~domain1.com|~domain2.com|~domain_n.com`
Домены с авторизацией могут отличаться, их самому искать надо в случае проблем.
2. Для этого юзерскрипт в дроидовом Адгарде есть.
