### ISSUE TITLE
primefreeporn.com - Missed ad - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5570]
http://www.primefreeporn.com/zenci-osa-lovelyin-hd-brazzers-pornosu/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/27912124-6d8882be-6264-11e7-8e92-26295213493e.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.23.45 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.6 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.81 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.14.87 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.7.87 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.81 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.52 Enabled=YES

Ticket ID: 1487333

**Comment by Alex-302** [comment]
Added to Turkish filter
```
||urbanfasion.com/ban*.gif
urbanfasion.com##.watch_video > p[style*="text-align: center;"]

```
