### ISSUE TITLE
Блокировка конкретного элемента

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#55711]
Здравствуйте,
С этой проблемой мне посоветовали обратиться к вам. Надеюсь, что вы мне поможете:

Как заблокировать элемент (обведён в кружёчек на скриншоте)? Возможно ли заблокировать его при помощи пользовательского фильтра?
![20200519_124615](https://user-images.githubusercontent.com/65596308/82311841-eacf7a80-99ce-11ea-9fe7-333fe6faaae1.jpg)

**Comment by Sergey-Lyapin** [comment]
Добрый день, @ghost
Если это не приложение, то можно, добавьте пожалуйста в пользовательский фильтр
`passport.yandex.ru##.passp-social-block`
