### ISSUE TITLE
Where's My Head? app - ads

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5571]
In-app missed ads.

URL:

https://itunes.apple.com/ru/app/wheres-my-head-free-by-top-free-games/id510134396

<details><summary>Screenshot:</summary>

![img_0030](https://user-images.githubusercontent.com/28726429/27912455-abcda224-6265-11e7-87db-d0d9d7ebbd23.PNG)

</details>

<br>
***System configuration***

Information | value
--- | ---
Operating system: | iOS
Adguard version: | 1.2.1
Adguard filters: | 1, 2, 3, 4, 11, 12, 14
Ticket ID (if exists): | 1138152

**Comment by Alex-302** [comment]
Not reproduced. Try this rule:
```
graph.facebook.com
```

**Comment by altokarev** [comment]
Didn't help.

**Comment by Alex-302** [comment]
Capture it's traffic by Fiddler.
