### ISSUE TITLE
Блокировка конкретного домена

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#55714]
Здравствуйте,
Возможно ли полностью заблокировать все домены Гугла и Фейсбука? Если да, то какое пользовательское правило я для этого должен добавить? С последствиями блокировки данных доменов ознакомлен.

**Comment by Alex-302** [comment]
Смотря какой Адгард.
Можно используя подобные правила, в зависимости от Адгарда:
`||example.org^$document` - расширение;
`||example.org^$empty,important` - программа;
`||example.org^` - для контент-блокера.
