### ISSUE TITLE
Yandex.Metro - ads

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5572]
In-app missed ads. Tiny pizza stuff in the corner.

URL:

[https://itunes.apple.com/ru/app/яндекс-метро-схема-метро-и-расчёт-времени-в-пути/id392589075](https://itunes.apple.com/ru/app/%D1%8F%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D0%BC%D0%B5%D1%82%D1%80%D0%BE-%D1%81%D1%85%D0%B5%D0%BC%D0%B0-%D0%BC%D0%B5%D1%82%D1%80%D0%BE-%D0%B8-%D1%80%D0%B0%D1%81%D1%87%D1%91%D1%82-%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%B8-%D0%B2-%D0%BF%D1%83%D1%82%D0%B8/id392589075)

<details><summary>Screenshot:</summary>

![img_0029](https://user-images.githubusercontent.com/28726429/27912773-ad2e06bc-6266-11e7-9638-178978498047.PNG)

</details>

<br>
***System configuration***

Information | value
--- | ---
Operating system: | iOS
Adguard version: | 1.2.1
Adguard filters: | 1, 2, 3, 4, 11, 12, 14
Ticket ID (if exists): | 1138152

**Comment by Alex-302** [comment]
I can't reproduce it. Could you capture traffic by Fiddler?
