### ISSUE TITLE
Ads in musixmatch app

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5573]
***Description***:
* **Current behaviour**: 

Ads in musixmatch app on Android

![screenshot_20170706-174150](https://user-images.githubusercontent.com/27874000/27917167-e505c31a-6273-11e7-9343-876e07167903.png)

***Steps to reproduce the problem***:

Link on Play Store:
https://play.google.com/store/apps/details?id=com.musixmatch.android.lyrify&hl=en

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On
Adguard filters: | English, Spyware, Social media, Annoyances, Russian, Experimental, mobile ads 
Ticket ID: | 1134913

**Comment by Alex-302** [comment]
It is a builtin self promo.
