### ISSUE TITLE
zeit.de (Google AMP)  - Social widgets - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5574]
***Site***: https://www.google.de/amp/www.zeit.de/amp/politik/deutschland/2017-07/bundeswehr-g20-gipfel-hamburg-verbietet-uniformen-soldaten
***Description***: Social sharing buttons. Ad.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27918063-1e2b9828-626e-11e7-9193-95c2918dc2ba.png)

![image](https://user-images.githubusercontent.com/10995998/27918079-2910dc1c-626e-11e7-8da7-80eacae6d0ee.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.87
Spyware filter | 1.0.13.18
Social media filter | 1.0.20.90
Annoyances filter | 1.0.15.7
German filter | 1.0.35.33
Mobile ads filter | 1.0.8.86
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed

**Comment by Bohdan-SUP** [comment]
It's back:
![image](https://user-images.githubusercontent.com/14153331/28920724-af3968c4-785b-11e7-9e49-3ef5e64444f9.png)

**Comment by seanl-adg** [comment]
Not reproduced

**Comment by Alex-302** [comment]
Added to Social filter
```
~facebook.com##a[href^="fb-messenger://share/"]
```
