### ISSUE TITLE
pcgames.de/pcgameshardware.de (Google AMP) - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5575]
***Site***: https://www.google.de/amp/www.pcgames.de/AMD-Firma-238123/News/AMD-RX-Vega-geleakte-Benchmarks-zeigen-einen-Leistungsvorsprung-zur-Nvidia-GTX-1080-1232404/amp/
***Description***: Social bar at the bottom.

**Same for pcgameshardware.de:** https://www.google.de/amp/www.pcgameshardware.de/Casecon-Hardware-255515/News/Doggycat-baut-um-Schreibtisch-PC-erhaelt-Ryzen-und-Hardtubes-1232388/amp/

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27918208-848bce9e-626e-11e7-97be-67b94ca5cf7e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.87
Spyware filter | 1.0.13.18
Social media filter | 1.0.20.90
Annoyances filter | 1.0.15.7
German filter | 1.0.35.33
Mobile ads filter | 1.0.8.86
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
