### ISSUE TITLE
chip.de (Google AMP) - Ad leftover - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5576]
***Site***: https://www.google.de/amp/www.chip.de/news/Android-Apps-des-Monats-Die-besten-Apps-im-Juli_87807104.html%3Flayout%3Damp
***Description***: Ad leftover. App banner at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27918379-17cc4454-626f-11e7-9c1b-11a44b977e29.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.87
Spyware filter | 1.0.13.18
Social media filter | 1.0.20.90
Annoyances filter | 1.0.15.7
German filter | 1.0.35.33
Mobile ads filter | 1.0.8.86
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
