### ISSUE TITLE
t-online.de (Google AMP) - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5577]
***Site***: https://www.google.de/amp/www.t-online.de/nachrichten/deutschland/innenpolitik/id_81573018/tid_amp/ehe-fuer-alle-bayern-prueft-verfassungsklage.html
***Description***: Ad leftover

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27918515-79c11a40-626f-11e7-8613-750f9468f742.png)

![image](https://user-images.githubusercontent.com/10995998/27918524-82468218-626f-11e7-810f-4736ee5be7a0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.87
Spyware filter | 1.0.13.18
Social media filter | 1.0.20.90
Annoyances filter | 1.0.15.7
German filter | 1.0.35.33
Mobile ads filter | 1.0.8.86
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
