### ISSUE TITLE
stuttgarter-nachrichten.de (Google AMP) - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5578]
***Site***: https://www.google.de/amp/www.stuttgarter-nachrichten.de/inhalt.bayern-achtjaehriger-wohl-von-grossvater-erschossen.cdadf13f-27df-402c-a2c4-744918640c97._amp.html
***Description***: Ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27918951-c05553e4-6270-11e7-93fb-2eb7d97f2b6b.png)

![image](https://user-images.githubusercontent.com/10995998/27918967-c87c3970-6270-11e7-8298-9a3b4e8e1088.png)

![image](https://user-images.githubusercontent.com/10995998/27918997-d34116e6-6270-11e7-8cbd-3e3d2cb1cd59.png)

![image](https://user-images.githubusercontent.com/10995998/27919014-de412590-6270-11e7-961e-d630e87351c9.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.87
Spyware filter | 1.0.13.18
Social media filter | 1.0.20.90
Annoyances filter | 1.0.15.7
German filter | 1.0.35.33
Mobile ads filter | 1.0.8.86
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Not reproduced, but please check if a rule
```
##.amp-ad
```
helps.

**Comment by danidoedel** [comment]
Couldn't reproduce it anymore as well 👍
