### ISSUE TITLE
Greatist.com / Healthline.com / MedicalNewsToday.com - Broken pages (AdGuard Annoyances filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#55796]
### Affected sites:
```
https://greatist.com/
https://www.healthline.com/
https://www.medicalnewstoday.com/
```

### Issue:
The pages doesn't load properly (no images).
This is caused by a blocked GDPR popup, which needs to be accepted in non-Chromium browsers (tested with Pale Moon and SeaMonkey).

### Screenshots:
Not needed, as the problem is obvious.

### Problem filter:
* AdGuard Annoyances filter

### Problem rules:
```
greatist.com,medicalnewstoday.com#$##modal-host { display: none !important; }
healthline.com#$##modal-host { display: none !important; }
```

### Note:
Apparently, these other rules (also found in **AdGuard Annoyances filter**) are supposed to circumvent the issue, but doesn't seem to have the desired effect in non-Chromium browsers:
```
greatist.com,medicalnewstoday.com#$#body { overflow: visible !important; }
healthline.com#$#body { overflow: visible !important; }
```

### Possible fix:
Preferably, the problem rules should be modified to work for all browsers.
Otherwise, the GDPR popup will have to be allowed.

### Other problem filters:
* uBlock filters - Annoyances (`greatist.com###modal-host`)
https://github.com/uBlockOrigin/uAssets/issues/7440/

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.9.3 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.20 (XUL)

**Comment by AdamWr** [comment]
I can't reproduce it in Firefox with AdGuard extension.

@AdguardTeam/filters-maintainers Could you please check it?

**Comment by zloyden** [comment]
> I can't reproduce it in Firefox with AdGuard extension.

Also not reproduced on my end in Firefox.

**Comment by THEtomaso** [comment]
The issue can be reproduced in the following browsers:
* Basilisk
* Pale Moon
* SeaMonkey
* Waterfox Classic

**Comment by Alex-302** [comment]
Not reproduced in Pale Moon and US IP.
I can check remotely.

**Comment by THEtomaso** [comment]
I can confirm that the issue isn't reproducable, when connecthing from the US.
This is because it triggers a comletely different cookie popup!

**Comment by Alex-302** [comment]
I don't know where are you from.

**Comment by THEtomaso** [comment]
Norway

**Comment by Alex-302** [comment]
Ok, reproduced. But I am not sure if these rules must be disabled for FF, because vintage versions of FF are not so popular. And it seems this issue is related to specific countries only.

Could you please check these rules?
```
! Exclusions
greatist.com#@$##modal-host { display: none !important; }
greatist.com#@$#body { overflow: visible !important; }
healthline.com#@$##modal-host { display: none !important; }
greatist.com,medicalnewstoday.com#@$##modal-host { display: none !important; }
greatist.com,medicalnewstoday.com#@$#body { overflow: visible !important; }

! The same CSS rules, but with Extended CSS
greatist.com#$?##modal-host { display: none !important; }
greatist.com#$?#body { overflow: visible !important; }
healthline.com#$?##modal-host { display: none !important; }
greatist.com,medicalnewstoday.com#$?##modal-host { display: none !important; }
greatist.com,medicalnewstoday.com#$?#body { overflow: visible !important; }
```

**Comment by THEtomaso** [comment]
Extended CSS didn't help.
Only the exclusions fixes the problem, allowing me to accept the GDPR popup.

**Comment by krystian3w** [comment]
Maybe AdGuard need:

`!#if (!cap_html_filtering && cap_user_stylesheet)`
_`should detect Firefox 56 and older, maybe also PaleMoon.`_
`!#endif`

**Comment by THEtomaso** [comment]
> Maybe AdGuard need add detect suport "userCSS" (user stylesheet rules) and "HTML Filtering"

Or simply provide a additional "Legacy" filter, like uBO does:
https://github.com/uBlockOrigin/uAssets/blob/master/filters/legacy.txt
Although, I'm not a big fan of its name.
Something like "XUL" filter would sound better, IMO.

..and speaking of uBO's Legacy filter:
A fix for these specific AdGuard Annoyances issues was just added to it:
https://github.com/uBlockOrigin/uAssets/commit/5e2795457eb615c9fa37c04278ec0383c85e67a0
