### ISSUE TITLE
handelsblatt.com (Google AMP) - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5580]
***Site***: https://www.google.de/amp/amp.handelsblatt.com/finanzen/boerse-maerkte/boerse-new-york-us-gesundheitsreform-treibt-pharma-aktien-an/19969430.html#scso=uid_WV7CsQACXH8KwAvmLAhQjw_20:0
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27936424-f98548aa-62b0-11e7-9db8-e3ecb1d655d5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.90
Spyware filter | 1.0.13.18
Social media filter | 1.0.20.92
Annoyances filter | 1.0.15.7
German filter | 1.0.35.35
Mobile ads filter | 1.0.8.86
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
