### ISSUE TITLE
faz.net (Google AMP) - Ad leftover - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5581]
***Site***: https://www.google.de/amp/m.faz.net/aktuell/feuilleton/buecher/themen/amazon-eroeffnet-in-new-york-einen-bookstore-15054272.amp.html
***Description***: Ad leftover. E-paper ad.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27936508-4c4a9216-62b1-11e7-9976-f800b0e415ea.png)

![image](https://user-images.githubusercontent.com/10995998/27936519-5531971c-62b1-11e7-9706-fd5fd9c6d11a.png)

![image](https://user-images.githubusercontent.com/10995998/27936538-7138c4da-62b1-11e7-9d33-f182e1c7cbab.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.90
Spyware filter | 1.0.13.18
Social media filter | 1.0.20.92
Annoyances filter | 1.0.15.7
German filter | 1.0.35.35
Mobile ads filter | 1.0.8.86
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
