### ISSUE TITLE
gizmodo.com (Google AMP) - Annoyance - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5582]
***Site***: https://www.google.de/amp/gizmodo.com/new-york-times-falls-for-that-fake-north-korea-twitter-1796634858/amp
***Description***: Newsletter box. Ad leftover. Social bar at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27936605-d415e01a-62b1-11e7-9016-d8e6d10dee43.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.23.90
Spyware filter | 1.0.13.18
Social media filter | 1.0.20.92
Annoyances filter | 1.0.15.7
German filter | 1.0.35.35
Mobile ads filter | 1.0.8.86
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed

**Comment by danidoedel** [comment]
@seanl-adg That sharing footer at the bottom of the page is still there:

![image](https://user-images.githubusercontent.com/10995998/27983905-b0d99f0c-63c8-11e7-858c-f19c5a6db209.png)
