### ISSUE TITLE
http://m.bild.de/ - Anti-Adlock script

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5583]
***Description***:
* **Current behaviour**: 

The web-site is blocked until the Adguard is turned off.
Reproduced on our side.

<details><summary>Screenshot:</summary>

![screen shot 2017-07-07 at 2 35 12 am](https://user-images.githubusercontent.com/28784344/27937050-0ae5d900-62bd-11e7-9deb-828b7a3c2d34.png)

![image](%url_of_screenshot%)

</details>

Information | value
--- | ---
Operating system: | Mac OS 
Adguard version: | 1.4.1.
Adguard DNS: | None 
Adguard filters: | 0, 1, 2, 3, 4, 11, 14
Ticket ID (if exists): | 1588247

**Comment by Alex-302** [comment]
Not reproduced on iOS, MacOS, Windows and Android.

> Reproduced on our side.
> Adguard filters: | 0, 1, 2, 3, 4, 11, 14

I don't see German filter here.
