### ISSUE TITLE
solopizza.ua - pop-up

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5584]
***Description***:
* **Current behavior**: 

There is a pop-up when you go on https://solopizza.ua/
The thing is that when you block it manually the screen still gets darker as if there is an ad(or pop-up)
Is it self-promotion or does it have to be blocked?

<details><summary>Screenshot:</summary>

![screen shot 2017-07-05 at 7 35 19 pm](https://user-images.githubusercontent.com/28784344/27942014-84226b2a-62dc-11e7-9883-3df2172b89dc.png)

</details>

<details><summary>Screenshot:</summary>

![screen shot 2017-07-05 at 7 35 56 pm](https://user-images.githubusercontent.com/28784344/27942024-9b1a794e-62dc-11e7-812e-727ea31b5a89.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 0, 1, 2, 3, 4, 11, 14
Ticket ID (if exists): | 1588190

**Comment by Alex-302** [comment]
For user filter:
```
solopizza.ua#$#body { overflow: visible!important; }
solopizza.ua#$##promomodal { display: none!important; }
```
