### ISSUE TITLE
Adblock Detected

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardFilters#55854]
@stralpt commented on [Thu May 21 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3321)

cant visit this site "https://mac-torrent-download.net/" because of anti adblock i dont know how to fix it,i've already installing fuck fuck adblock filter and anti adblock killer thats all not working, i hope there's a solution for me

**Comment by slavaleleka** [comment]
@stralpt 
fixed! update filters in a few hours please
