### ISSUE TITLE
http://www.energyfm.ru - the video cannot be played 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5585]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://www.energyfm.ru/?an=nrj_online_video - with Stealth mode enabled, the video cannot be played 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/23372054/27949721-62ccc65c-6307-11e7-807c-7aa75a674392.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Firefox
Adguard version: | 6.2.369.1938
Adguard driver: |TDI
Stealth mode options | enabled
Adguard filters: | English, Spyware, Social, Russian 
Ticket ID: | 1570320

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||rutube.ru/play/embed/$stealth
```
