### ISSUE TITLE
Adblock-Persian list - incorrect blocking

### ISSUE THREAD

**Issue by vishchakl** [AdguardTeam/AdguardFilters#5586]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

as reported by user:

Персидский лист несовместим с сайтом
https://minecraft-ru.gamepedia.com/ (возможно и с
другими проектами на платформе
GamePedia) и крушит разметку.
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screen shot 2017-07-07 at 11 39 22 am](https://user-images.githubusercontent.com/29872276/27953851-0b73cd74-6316-11e7-88e2-51314a78ec31.png)
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![screen shot 2017-07-07 at 11 40 04 am](https://user-images.githubusercontent.com/29872276/27954816-6985290e-631a-11e7-8fe9-62813162f8f1.png)

</details>

***Steps to reproduce the problem***:

https://minecraft-ru.gamepedia.com/ 

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: Mac OS
Browser: Chrome
Adguard version: 1.4.1
Adguard DNS: None 
Adguard filters: English, Spyware, Social media, Russian, German, Adblock-Persian list
Ticket ID (if exists): 1411250

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Возможно фильтр очень старый. У меня не повторилось. Мы со своей стороны удалили проблемное правило довольно давно(точнее, знак "минус", который был использован в качестве разделителя строк).
Нужен журнал заблокированных запросов при включенном только одном персидском фильтре(или сработавшие правила)

**Comment by Xottab-DUTY** [comment]
Сейчас временно не у компьютера. Помню писало что-то про AdVer. Правилом заблокировало load.php. Возможно поможет.

Сейчас на Android 4.4.2, AdGuard 2.9.70. Проблема не воспроизводится.
Проблема была на Яндекс.Браузере, на браузерном Adguard.

**Comment by Alex-302** [comment]
Может фильтр был старый. Он вообще, похоже, не обновляется. Если иранские сайты не посещяете, лучше выключить.

**Comment by Xottab-DUTY** [comment]
Я их как раз не посещаю. Он сам включился, когда я на один сайт зашёл. Предлагал в техподдержке (в тикете, номер которого сверху), предложу и здесь: было бы неплохо оповещение (всплывашку какую-нибудь) вида: "Вы посетили сайт такой-то и мы включили вам фильтр такой-то" и к нему две кнопки: "Хорошо, спасибо" и "Нет, выключить фильтр".

**Comment by Alex-302** [comment]
Уведомление есть. По кнопкам можете озвучить предложение в репозитории продукта, который используете.
Для MacOS, например, можно здесь:
https://github.com/AdguardTeam/AdguardForMac/issues
