### ISSUE TITLE
Telly Reviews - Ad Leftover

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardFilters#5587]
**System Setup:-**
Windows 10 Ent. LTSB x64(2016 - updated)
Adguard 6.2.369.1938
WFP driver is enabled.
Filter Lists: English, Spyware.
Firefox stable 54.0.1 x64
Https filtering is enabled.
Stealth Mode disabled.

**Site:-**
http://tellyreviews.com/

**Problem:-**
There are ad leftover empty blank white spaces on the homepage and any article you click from the homepage.

**Screenshot:-**
http://i.imgur.com/8av40a8.jpg

Point to be noted: uBlock with the same filter lists, doesn't leave out any blank space or ad leftover.

**Comment by Alex-302** [comment]
Not reproduced. I need direct link.

**Comment by The-Commissioner** [comment]
Hey @Alex-302 Hope you are doing fine.

http://tellyreviews.com/2017/07/10/roshni-gets-suspicious-sameer-sasural-simar-ka/
http://tellyreviews.com/2017/07/03/naren-pooja-take-decision-piyaa-albela/
http://tellyreviews.com/2017/07/10/omru-plan-surprise-date-shivika-ishqbaaz/

You can click any article from site homepage and see the white spaces in between article.

**Comment by Alex-302** [comment]
Added to English filter
```
tellyreviews.com#$#.ezoic-ad { position: absolute!important; left: -3000px!important; }
tellyreviews.com##.td-post-content > div[adunitname]

```

**Comment by The-Commissioner** [comment]
@Alex-302 I updated the filter list English filter:1.1.24.31

The links in between the articles have now gone.

It still have white empty box at top of page:-
http://tellyreviews.com/2017/07/08/high-five-spoilers-254/
http://tellyreviews.com/2017/07/10/star-plus-mini-spoilers-130/
http://tellyreviews.com/2017/07/10/anika-raginis-drama-catches-shivay-ishqbaaz/

**Comment by Alex-302** [comment]
Not reproduced.

**Comment by The-Commissioner** [comment]
Yeah thanx looks like a later filter update fixed this.
