### ISSUE TITLE
e.mail.ru/messages/inbox - ads (extension only)

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5588]
Missed ads. Appears only with the browser extension.

URL:

https://e.mail.ru/messages/inbox

<details><summary>Screenshot:</summary>

![screen-shot-2017-07-07-at-16 28 04](https://user-images.githubusercontent.com/28726429/27960418-e63c7fa6-6333-11e7-9798-33ef262e5cde.png)

</details>

<br>
***System configuration***

Information | value
--- | ---
Operating system: | macOS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 12, 14

**Comment by Alex-302** [comment]
Can you reproduce it?

**Comment by altokarev** [comment]
Of course. That's my own screenshot above.

**Comment by Alex-302** [comment]
Is it on MacOS only?

**Comment by altokarev** [comment]
Yep, macOS + browser extension indeed.

**Comment by altokarev** [comment]
Added `||e.mail.ru/api/v1$domain=e.mail.ru`. At first glance it helped.

**Comment by Alex-302** [comment]
Still not reproduced

<details>

![image](http://imagizer.imageshack.com/img923/5517/Is8HEL.png)
</details>

That rule breaks the site.

**Comment by altokarev** [comment]
<details><summary>My filters:</summary>

![screen shot 2017-07-11 at 17 08 29](https://user-images.githubusercontent.com/28726429/28072698-78d8a63e-665c-11e7-9639-63cdb4a54291.png)

</details>

<details><summary>Filtering log:</summary>

![screen shot 2017-07-11 at 17 12 56](https://user-images.githubusercontent.com/28726429/28072720-8f35fada-665c-11e7-825b-922d57e38f87.png)

</details>

<details><summary>Missed ad expamle:</summary>

![screen shot 2017-07-11 at 17 13 11](https://user-images.githubusercontent.com/28726429/28072732-961c937c-665c-11e7-8492-2a3ff359899f.png)

</details>
