### ISSUE TITLE
Anti-adblocker ad on sweclockers.com

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5589]
***Description***:
* **Current behaviour**: 

![screen shot 2017-07-07 at 5 47 15 pm](https://user-images.githubusercontent.com/27874000/27963029-5dd65ffc-633c-11e7-9d01-2b6f3606ead5.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
Adguard filters: |  English, Spyware, Social media, Annoyances, Fanboy's Swedish, Simplified domain names filter  
Ticket ID: | 1456058

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Fixed
