### ISSUE TITLE
Anti-adblocker ad on fz.se 

### ISSUE THREAD

**Issue by aksyonova** [AdguardTeam/AdguardFilters#5590]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

![screen shot 2017-07-07 at 5 53 02 pm](https://user-images.githubusercontent.com/27874000/27963272-28672760-633d-11e7-92e1-dfe399c416b6.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
Adguard filters: | English, Spyware, Social media, Annoyances, Fanboy's Swedish, Simplified domain names filter
Ticket ID: | 1456058

**Comment by seanl-adg** [comment]
Fixed
