### ISSUE TITLE
Ad leftover moyateplica.ru 

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5591]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Ad leftover on the page - http://moyateplica.ru/raznovidnosti-rastenii/teplichnoe-vyrashchivanie-arbuzov-i-dyn-v-sibirskom-regione
It appears after a couple of seconds. 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screen shot 2017-07-08 at 1 20 31 am](https://user-images.githubusercontent.com/29478021/27979045-d8b48ac0-637b-11e7-9953-d1dd6fda8d72.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Chrome
Adguard version: |  1.4.1
Adguard filters: | English, Russian, Annoyances, Social media, Spyware
Ticket ID (if exists): | 1498653

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
