### ISSUE TITLE
Facebook tracker on startpage.com

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5592]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Facebook tracker on startpage.com in Safari detected by Bitfender. 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29478021/27981954-eb2c4dbe-639e-11e7-8591-5239c1de4130.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

</details>

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Safari
Adguard version: | Extension v2.5.12
Adguard filters: | English, Spyware, Social media, Annoyances, Safari
Ticket ID (if exists): | 1581414

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. Which script was found by this extension? Please ask user about it.

**Comment by evgeniy-ADG** [comment]
That tool does not allow seeing the actual code, it just says that the tracker is detected. I've caught one on another site (adguard turned off) and could not find how to check what's detected. If there's another way we can see the script, let us know how.

**Comment by Alex-302** [comment]
Just ignore it. That extension parses HTML and shows warning when tracking script is found. Browser extensions can't change HTML like the apps.
