### ISSUE TITLE
morgenpost.de (Google AMP) - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5594]
***Site***: https://www.google.de/amp/s/www.morgenpost.de/berlin/article211159495/DWD-Gewitter-mit-Starkregen-und-Hagel-wahrscheinlich.html%3Fservice%3Damp
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27984125-aaf1e05e-63cd-11e7-8444-b3b9377aa7af.png)

![image](https://user-images.githubusercontent.com/10995998/27984129-b6b565d2-63cd-11e7-9cef-2eecd43c66f1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.5
Spyware filter | 1.0.13.19
Social media filter | 1.0.20.95
Annoyances filter | 1.0.15.11
German filter | 1.0.35.38
Mobile ads filter | 1.0.8.86
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed

**Comment by danidoedel** [comment]
@seanl-adg Doesn't seem to work for me. Ad leftover stuff is still there.

**Comment by seanl-adg** [comment]
Fixed again
