### ISSUE TITLE
op-online.de (Google AMP) - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5595]
***Site***: https://www.google.de/amp/s/www.op-online.de/hessen/floersheim-treibendes-kanu-loest-einsatz-8468588.amp.html
***Description***: Social widget leftover. Ad leftover title.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27984153-56b9109c-63ce-11e7-8c26-52e9e0be14f3.png)

![image](https://user-images.githubusercontent.com/10995998/27984156-617ffc0c-63ce-11e7-9789-83f1f16c1e81.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.5
Spyware filter | 1.0.13.19
Social media filter | 1.0.20.95
Annoyances filter | 1.0.15.11
German filter | 1.0.35.38
Mobile ads filter | 1.0.8.86
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
