### ISSUE TITLE
derwesten.de (Google AMP) - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5596]
***Site***: https://www.google.de/amp/s/www.derwesten.de/sport/fussball/bvb/starkes-signal-dortmund-hat-sich-gegen-uefa-und-dfb-gewehrt-id211169771.html%3Fservice%3Damp
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27984181-44c8938e-63cf-11e7-941f-e6aad28e717c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.5
Spyware filter | 1.0.13.19
Social media filter | 1.0.20.95
Annoyances filter | 1.0.15.11
German filter | 1.0.35.38
Mobile ads filter | 1.0.8.86
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed

**Comment by BlazDT** [comment]
Ad left-overs at https://www.derwesten.de/staedte/essen/hooligans-patrouillieren-auf-dem-essener-weihnachtsmarkt-das-sagt-die-polizei-zu-der-gruppe-id212907855.html
