### ISSUE TITLE
vox.de (Google AMP) - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5597]
***Site***: https://www.google.de/amp/amp.vox.de/cms/shopping-queen-trina-aus-hannover-im-style-check-4118780.html
***Description***: Ad leftover. Social share leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27984193-9d82033e-63cf-11e7-820f-5f2eb8998f5c.png)

![image](https://user-images.githubusercontent.com/10995998/27984194-abfe269a-63cf-11e7-83b4-183e53217067.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.5
Spyware filter | 1.0.13.19
Social media filter | 1.0.20.95
Annoyances filter | 1.0.15.11
German filter | 1.0.35.38
Mobile ads filter | 1.0.8.86
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
