### ISSUE TITLE
Why is Ubuntu launchpad.net blocked

### ISSUE THREAD

**Issue by muzena** [AdguardTeam/AdguardFilters#55988]
This is link to problem: https://launchpadlibrarian.net/480969025/transmission_3.00-1ubuntu1~18.04.1ubuntu1_3.00-1ubuntu1~18.04.1ubuntu2.diff.gz

**Comment by Alex-302** [comment]
@Chinaski1 please take a look.

**Comment by Chinaski1** [comment]
launchpadlibrarian.net - is already added to the blacklist.

**Comment by sbutcher** [comment]
I am still seeing this issue on Adguard home appliance. The version reported on the web interface is 0.103.3

**Comment by Alex-302** [comment]
Please show `nslookup` or `dig` output.

**Comment by sbutcher** [comment]
nslookup launchpadlibrarian.net
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	launchpadlibrarian.net
Address: 91.189.89.228
Name:	launchpadlibrarian.net
Address: 91.189.89.229
Name:	launchpadlibrarian.net
Address: 2001:67c:1560:8003::8008
Name:	launchpadlibrarian.net
Address: 2001:67c:1560:8003::8007

![image](https://user-images.githubusercontent.com/4619907/114563031-f4a54080-9c66-11eb-90ed-7b5c6f4ed765.png)

**Comment by timkgh** [comment]
This is broken again, parental control.

**Comment by Alex-302** [comment]
@timkgh I can't reproduce. Please write to support@adguard.com because not related to filters.

@NaylyaM Please take a look.
