### ISSUE TITLE
infranken.de (Google AMP) - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5598]
***Site***: https://www.google.de/amp/s/bc.marfeel.com/www.infranken.de/regional/nuernberg/Kilometerlanger-Stau-auf-A3-bei-Nuernberg-Zwei-Unfaelle-legen-Verkehr-lahm;art88523,2757911%3Fmarfeeltn%3Damp
***Description***: Ad leftover at the end of the page.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/27984223-13e1426a-63d0-11e7-810f-c601d4198eeb.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.5
Spyware filter | 1.0.13.19
Social media filter | 1.0.20.95
Annoyances filter | 1.0.15.11
German filter | 1.0.35.38
Mobile ads filter | 1.0.8.86
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
The link is not working.

**Comment by danidoedel** [comment]
@seanl-adg It seems like you can‘t copy links of the AMP page of infranken.de
Try to search for „infranken.de“ on mobile google (https://www.google.de/search?as_q=infranken.de) and you should find some AMP results with the same issues:

![img_6243](https://user-images.githubusercontent.com/10995998/27986548-82a15304-6400-11e7-8f7a-580ec9382589.PNG)

**Comment by seanl-adg** [comment]
Fixed
