### ISSUE TITLE
anistar.me - ad blocking

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5600]
***Description***:
* **Current behavior**: 
The user wants to block manually ads that are on the video on the website (https://anistar.me/6264-povelitel-hronosa-chronos-ruler-jikan-no-shihaisha.html), 
but it is impossible because the whole video player is getting blocked (see the screenshots)
Reproduced on our side
the question is: is that ad a part of self-promotion and can`t be blocked or not? 

<details><summary>Screenshot1:</summary>

![screen shot 2017-07-08 at 4 42 50 pm](https://user-images.githubusercontent.com/28784344/27985860-a34bb56c-63fc-11e7-8c5f-13ce478ee801.png)

</details>

<details><summary>Screenshot2:</summary>

![screen shot 2017-07-08 at 4 44 21 pm](https://user-images.githubusercontent.com/28784344/27985868-c7988472-63fc-11e7-9236-ae5fbd74b4c3.png)

</details>

<details><summary>Screenshot3:</summary>

![screen shot 2017-07-08 at 4 44 41 pm](https://user-images.githubusercontent.com/28784344/27985871-cfdf999a-63fc-11e7-92b5-cb4ce45da5d0.png)

</details>

***Steps to reproduce the problem***:
1. Go on https://anistar.me/6264-povelitel-hronosa-chronos-ruler-jikan-no-shihaisha.html
2. Try to block ads (that are on the video player) manually using Adguard extension or Adguard Assistant icon
3. See what happens 
***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Adguard version: |  6.2.379.1984/ 1.4.1.
Adguard driver (Windows): | WFP 
Adguard DNS: | None 
Adguard filters: | 1,2,3,4,5,14,15,207,111,0
Ticket ID (if exists): | 1412565

**Comment by Alex-302** [comment]
It is not filters issue.
Blocked this ad.
