### ISSUE TITLE
hsdn.org - Incorrect blocking

### ISSUE THREAD

**Issue by Rostov114** [AdguardTeam/AdguardFilters#5602]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Здравствуйте.

hsdn.org - корневой сайт.
top.hsdn.org - основной сайт рейтинга ресурсов.
cX.top.hsdn.org - ноды по приему данных от счетчиков.

Никакие другие домены кроме top.hsdn.org - не участвуют в сборе статистики.

Возможно ли изменение фильтра?

Т.к. в данном виде он блокирует легитимные CSS с основного домена на поддоменах например: noc.hsdn.org

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | All
Browser: | All

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

tracking_servers.txt

**Comment by Alex-302** [comment]
Да, спасибо. Заменил.
Но на самом hsdn.org оно не должно было срабатывать, т.к. в правиле указано `$third-party`
