### ISSUE TITLE
anistar.me - Missed Ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5603]
***Description***: https://anistar.me/6087-sin-nanatsu-no-taiza.html

<details><summary>Screenshot:</summary>

![screen shot 2017-07-09 at 5 38 40 am](https://user-images.githubusercontent.com/27292111/27990730-f7908096-6468-11e7-8940-3beb5e8abda0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: |  Chrome extension 
Adguard filters: | 1 2 14 115
Ticket ID: | 1076701

**Comment by ypetruk** [comment]
Опять пропал выбор качества видео
Ticket ID: 1412565

**Comment by ypetruk** [comment]
Реклама Терры на сайте https://anistar.me/ не блокируется. Попытка вырезать рекламу через помошник ведет к вылету помошника и перезагрузке сайта. Реклама при этом остается

Ticker ID: 1589473

**Comment by Alex-302** [comment]
C выключенной блокировкой переключателя качества у меня нет.

**Comment by FlamingApelsin** [comment]
Есть. 
![2017-07-11_001633](https://user-images.githubusercontent.com/28679191/28040386-4c1a82fe-65ce-11e7-9f13-ac7c740d9336.png)

**Comment by Alex-302** [comment]
Поправил. Через полтора часа будет обновление.
