### ISSUE TITLE
123moviesfreez.com - Ad leftover

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5604]
***Description***:
* **Current behavior**: 
There is an ad leftover on http://123moviesfreez.com/
reproduced on our side
<details><summary>Screenshot:</summary>

![screen shot 2017-07-09 at 8 10 52 am](https://user-images.githubusercontent.com/28784344/27991399-35278b60-647e-11e7-84ff-6649f9d730f7.png)

</details>

***Steps to reproduce the problem***:

Go on: http://123moviesfreez.com/watch/sherlock-holmes-2009-online-free-123movies.html

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS
Adguard version: | 6.1.331.1732 - 1.4.1.
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Adguard filters: | 0,1, 2, 3 ,4,11, 14
Ticket ID (if exists): | 1589106

**Comment by Alex-302** [comment]
Fixed
