### ISSUE TITLE
Tapatalk app - Ad leftover - iOS

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5605]
***Description***:
* **Current behaviour**: 

https://play.google.com/store/apps/details?id=com.quoord.tapatalkpro.activity&hl=en
Used Tapatalk to browse MacRumors forum and many ads have appeared between posts.
Not reproduced.

<details><summary>Screenshot1:</summary>
 
![image1](https://user-images.githubusercontent.com/28784344/27993022-8a7875cc-64a9-11e7-80ff-bf221e99a87e.png)

</details>

<details><summary>Screenshot2:</summary>

![image2](https://user-images.githubusercontent.com/28784344/27993025-9db82e34-64a9-11e7-847a-dd36da34fb5a.png)

</details>

<details><summary>Screenshot3:</summary>

![image3](https://user-images.githubusercontent.com/28784344/27993026-ac964bde-64a9-11e7-8972-78c8e087959a.png)

</details>

***System configuration***

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3.2
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.23.84 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.17 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.52 Enabled=YES
Ticket ID:  1587622

[com.adguard.AdguardPro.gz](https://github.com/AdguardTeam/AdguardFilters/files/1133670/com.adguard.AdguardPro.gz)
[com.adguard.AdguardPro.ActionExtension.gz](https://github.com/AdguardTeam/AdguardFilters/files/1133671/com.adguard.AdguardPro.ActionExtension.gz)
[com.adguard.AdguardPro.tunnel (1).gz](https://github.com/AdguardTeam/AdguardFilters/files/1133673/com.adguard.AdguardPro.tunnel.1.gz)

**Comment by Alex-302** [comment]
Also not reproduced, but it is possible. Adguard for iOS can't filter ads in apps like Adguard for Android.
