### ISSUE TITLE
 kinotut.tv - ads - Android 

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5606]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

There is an ad of the website ( Подпишись!Мы ВКонтакте!) that directs to vk.com site on  kinotut.tv
reproduced on our side
(please, don`t mind the big ads from the screenshot - because they are blocked - we recommended user to enable Https filtration)

<details><summary>Screenshot:</summary>

![screenshot_2017-07-09-12-19-11](https://user-images.githubusercontent.com/28784344/27993522-453c40d6-64b5-11e7-9ba2-7addde192eb7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Adguard version: | 2.9.135
Adguard mode (Android): | Proxy(manual)
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default) 
Adguard DNS: | None
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1560071

**Comment by Alex-302** [comment]
This site without HTTPS.
We don't block the links of social blogs.
For user filter:
```
kinotut.tv##a[href="https://vk.com/kinotut_tv?from=kinotut.su"]
```
