### ISSUE TITLE
Ads in the stream https://goodgame.ru/channel/ZeRG/

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardFilters#5607]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Ads in the stream https://goodgame.ru/channel/ZeRG/

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screen shot 2017-07-09 at 5 16 52 pm](https://user-images.githubusercontent.com/29478021/27994651-c2d5eed8-64ca-11e7-87a9-32bd327aafa4.png)

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

</details>***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | English, Spyware, Social media, Annoyances, Russian
Ticket ID (if exists): | 1564103

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed

**Comment by veronikasav** [comment]
Ad is back on the website. Could you, please, fix it again? Thank you!

<details><summary>Screenshot:</summary>

![screen shot 2017-07-21 at 5 13 24 pm](https://user-images.githubusercontent.com/27292111/28467313-31bc05d2-6e38-11e7-9078-3404343e1a50.png)

</details>

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by Alex-302** [comment]
Please check:
```
@@||storage2.goodgame.ru/clips/*.mp4|$domain=goodgame.ru
||goodgame.ru/del/*.php?
||storage2.goodgame.ru/$other,media,~image
```

**Comment by Alex-302** [comment]
@veronikasav

**Comment by veronikasav** [comment]
Unable to check since that stream is offline for now.

**Comment by Alex-302** [comment]
Ok then.

**Comment by Alex-302** [comment]
Please ask user about it.
