### ISSUE TITLE
kinotut.tv - missed ads

### ISSUE THREAD

**Issue by vishchakl** [AdguardTeam/AdguardFilters#5608]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

missed ads on kinotut.tv

* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![kinotut2](https://user-images.githubusercontent.com/29872276/27999495-795a9b3a-6526-11e7-8ff4-9551b6f4ccf8.png)
![kinotut1](https://user-images.githubusercontent.com/29872276/27999496-797434e6-6526-11e7-9c66-461029db8471.png)

***System configuration***

Information | value
--- | ---
Operating system: |  Android 6.0.1
Browser: | Chrome
Adguard version: | 2.9.70
Adguard mode: | VPN 
Filtering quality: | High-quality 
HTTPS filtering: |  On (Default) 
Adguard DNS: | None 
Adguard filters: | English, Spyware, Social media, Annoyances, Russian, Mobile Ads
Ticket ID: | 1560071

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.

**Comment by vishchakl** [comment]
reproduced yesterday, but today it seems to work fine. checked on different devices
