### ISSUE TITLE
prohardver.hu - incorrect filtering

### ISSUE THREAD

**Issue by vishchakl** [AdguardTeam/AdguardFilters#5609]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:

after you add prohardver.hu to exceptions, Adguard still filters it leaving a frame where the ad is supposed to be
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screen shot 2017-07-10 at 2 31 55 am](https://user-images.githubusercontent.com/29872276/28000646-bbb5ba74-652f-11e7-80c8-ef5b14ba9a6d.png)

</details>

* **Expected behaviour**: 

This is how the website looks like with Adguard disabled
<details><summary>Screenshot:</summary>

![screen shot 2017-07-10 at 5 23 28 am](https://user-images.githubusercontent.com/29872276/28000678-f9e7276a-652f-11e7-8d21-f3f534b69203.png)

</details>

***Steps to reproduce the problem***:

https://prohardver.hu

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | English, Spyware, Social media, Annoyances, hufilter, Malware domains
Ticket ID (if exists): | 859481

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is not incorrect blocking.
Added to English filter
```
prohardver.hu##.xabre-responsive-970px-90px
prohardver.hu##.xabre-responsive-300px-60px

```

**Comment by vishchakl** [comment]
Please check the issue again. The thing is the user ads this website to exceptions, but Adguard still filters it not showing the ad properly and leaving the frame. With Adguard disabled the ad shows perfectly.

We were able to reproduce the issue, sometimes the ad is showing correctly, but most of the time all you can see is the frame.

Thanks!

**Comment by Alex-302** [comment]
I need two screenshots - with actual end expected results.

**Comment by vishchakl** [comment]
Those are attached it the description: 
the first screenshot is how the website looks like when added to exceptions (the ad is not showing properly), and the second one is how it is supposed to look (I disabled Adguard completely to take that one).

**Comment by ypetruk** [comment]
comment from the user: Accidentally I came across the solution. The problem page is linked to the https protocol through the browser. I added the https exception to the page and now it's okay to show the ads.

**Comment by Alex-302** [comment]
Ok.

**Comment by evgeniy-ADG** [comment]
Unfortunately, the joy was early Today, the ads on the site have again become problematic
See the attached picture (Adguard ON and Adguard OFF).

<details><summary> on </summary>

![adguard_ph_filter_07-24](https://user-images.githubusercontent.com/15856304/28563852-ec5934c4-712f-11e7-9151-d8fecfca47f7.jpg)

</details>

<details><summary> off </summary>

![adguard_ph_disabled_adguard_07-24](https://user-images.githubusercontent.com/15856304/28563861-f21e257c-712f-11e7-9b8c-05e20cf7006f.jpg)

</details>

**Comment by AtHoS-HUN** [comment]
I reinstalled the program (I did not keep the settings)
# prohardver.hu added to the exceptions (so it would not have to filter at all)

see the filter log (refresh the prohardver.hu page):
![adguard_ph_filternaplo](https://user-images.githubusercontent.com/30474584/28744194-ecc0b3fe-745b-11e7-8f6c-c1292167c976.jpg)

and the displayed website (the advertisement is not visible)
![adguard_ph_filter_07-24](https://user-images.githubusercontent.com/30474584/28744210-460b5f0e-745c-11e7-9f3b-160081d4940e.jpg)

I disabled globally adfilter in adguard, see the filter log (refresh the prohardver.hu page):
![adguard_ph_filter_disabled_adfiltering](https://user-images.githubusercontent.com/30474584/28744206-1bc4d086-745c-11e7-86e2-6d762d09c52d.jpg)

and the displayed website (the advertisement can be seen)
![adguard_ph_disabled_adguard_07-24](https://user-images.githubusercontent.com/30474584/28744218-6c00931e-745c-11e7-88c3-be99a2128e21.jpg)

I think something does not work well

**Comment by Alex-302** [comment]
Please add this domain to HTTPS exclusions and add this rule:
```
@@||prohardver.hu^$document
```
some requests will be blocked because they have referer different than prohardver.hu

**Comment by AtHoS-HUN** [comment]
HTTPS exclusions and rule already added, but the adblocking so it works

![ph_adguard_disabled_filtering_dont_work](https://user-images.githubusercontent.com/30474584/28788801-ba1e0e56-7622-11e7-91c7-ea25327b6a7e.jpg)

the filter log (after refresh prohardver.hu):

![adguard_ph_filter_log](https://user-images.githubusercontent.com/30474584/28789241-d54294b6-7624-11e7-8987-5d2f9008831c.jpg)

**Comment by Alex-302** [comment]
Please make screenshot of HTTPS exclusion. Maybe something is wrong.

**Comment by AtHoS-HUN** [comment]
In the previous post, the top right corner of the first image: HTTPS Kivételek = HTTPS exclusion
Unfortunately, this window can not be resized
