### ISSUE TITLE
themeisle.com (Google AMP) - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5612]
***Site***: https://www.google.de/amp/s/themeisle.com/blog/amp
***Description***: Cookie notice at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28013325-f2b84efe-6568-11e7-9d1c-fce91e72d8d7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.28
Spyware filter | 1.0.13.20
Social media filter | 1.0.20.98
Annoyances filter | 1.0.15.19
German filter | 1.0.35.39
Mobile ads filter | 1.0.8.88
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
