### ISSUE TITLE
technologyreview.com (Google AMP) - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5613]
***Site***: https://www.google.de/amp/s/www.technologyreview.com/s/608231/by-2040-more-than-half-of-all-new-cars-could-be-electric/amp/
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28013402-2f9316f6-6569-11e7-8058-748deab9940a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.28
Spyware filter | 1.0.13.20
Social media filter | 1.0.20.98
Annoyances filter | 1.0.15.19
German filter | 1.0.35.39
Mobile ads filter | 1.0.8.88
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
