### ISSUE TITLE
inverse.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#56171]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Multiple empty ads placeholders thought the page.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![adg](https://user-images.githubusercontent.com/29574622/82947931-a8a3cb80-9fc2-11ea-84c9-4da0e1e5059a.jpg)

</details><br/>

* **Expected behaviour**: 

No empty placeholders

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

Visit: https://www.inverse.com/entertainment/snowpiercer-star-steven-ogg-interview

***System configuration***

**Filters:**

Adguard Base, AdGuard Mobile Ads, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 1909
Browser:                               | Chromium Edge 83
AdGuard version:                       | Adguard extension 3.4.19

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
