### ISSUE TITLE
toolslib.net - Ads - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5618]
***Site***: https://toolslib.net/downloads/finish/1 (download of the program will start immediately)
***Description***: Ad and some misplacing of elements. Also green forums button is missing. Check the screenshot how it should look like.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28017702-a955d120-657a-11e7-82c0-e1052921bfc8.png)

![image](https://user-images.githubusercontent.com/10995998/28017711-b7457574-657a-11e7-8855-e364c63d5828.png)

**That's how it should look like:**

![image](https://user-images.githubusercontent.com/10995998/28017932-8158c0aa-657b-11e7-854f-fb04d68806f8.png)

![image](https://user-images.githubusercontent.com/10995998/28017944-90875460-657b-11e7-956b-1e94ae4c0167.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.28
Spyware filter | 1.0.13.20
Social media filter | 1.0.20.98
Annoyances filter | 1.0.15.19
German filter | 1.0.35.39
Mobile ads filter | 1.0.8.88
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr Ads are back:

![image](https://user-images.githubusercontent.com/10995998/28898752-e97a018e-77e7-11e7-85a0-c772010c5a02.png)

**Comment by AdamWr** [comment]
Fixed.
