### ISSUE TITLE
gravatar.com - custom rule request 

### ISSUE THREAD

**Issue by vishchakl** [AdguardTeam/AdguardFilters#5619]
User asks for rules which could block all avatars which come from gravatar.com on his Mac:
Example: https://teamtreehouse.com/community/is-there-money-in-creating-wordpress-themes

Ticket ID: 1588753

**Comment by jonbeebe** [comment]
I've tried all of these rules to no avail:

```
||gravatar.com/avatar/*
||gravatar.com^$image
||https://secure.gravatar.com/avatar/*
||*.gravatar.com/avatar/*
```

**Comment by Alex-302** [comment]
You can try
```
||secure.gravatar.com^$third-party
```
or
```
||gravatar.com^$third-party
```
also you can remove `$third-party` from the rule.

**Comment by jonbeebe** [comment]
@Alex-302 Did you try that on the website example provided in the description? It's not working for me, neither is removing the `$third-party` portion. Is it working for you?

**Comment by Alex-302** [comment]
```
||secure.gravatar.com^$third-party,important
```
this rule works

**Comment by jonbeebe** [comment]
@Alex-302 Confirmed, that last rule you posted works for me. Thanks!
