### ISSUE TITLE
servicebox.ru crashes with Adguard enabled 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5620]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: servicebox.ru - crashes with Adguard enabled, totally disabling Adguard fixes the issue.
reproduced on Mac/Windows 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screen shot 2017-07-10 at 4 05 33 pm](https://user-images.githubusercontent.com/23372054/28019513-e0841c74-6589-11e7-902f-6f6a663b8e62.png)

</details>

***Expected behavior***:

<details>

![screen shot 2017-07-10 at 4 08 18 pm](https://user-images.githubusercontent.com/23372054/28019593-23130d66-658a-11e7-9141-0a39bc4468b7.png)

</details>

Ticket ID: 1589956

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
> Нашли людей с аналогичной проблемой.
> https://forum.adguard.com/index.php?threads/%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B0-%D0%9E%D0%BF%D0%B0%D0%BD%D1%8C%D0%BA%D0%B8-%D0%B2-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B5-google-chrome.21452/
> 
> Пишут что крашится страница со статистикой групп ВК. Проверил в chrome - у
> меня аналогично. Без Adguard открывается, после включенения Adguard
> вылетела в ошибку, за одно захватив с собой несколько открытых вкладок
> других сайтов.
> У менеджеров сайта проблема тоже замечена.
> 
> Попробовал в анонимной вкладке где нет куки, почти все расширения отключены
> - тоже крашится наш сайт и статистика вк https://vk.com/stats?gid=32014334 .
> На форуме рекомендуют удалить пользователя Chrome - возможно вы тестировали
> на чистом браузере? Без авторизации в хроме?

**Comment by Alex-302** [comment]
У меня крашится и без Адгарда(выключал полностью).

**Comment by Alex-302** [comment]
Крашится только в Хроме и Опере(которая на основана наХроме) с расширением.
