### ISSUE TITLE
Convert ABP #?# syntax

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardFilters#5621]
According to https://adblockplus.org/development-builds/new-syntax-for-advanced-element-hiding-rules, ABP will use `#?#` instead of `##` to distinguish element hiding rules which make use of `-abp-has` and `-abp-properties` pseudo classes.

We need to convert `#?#` to `##`, `-abp-has(...)` to `[-ext-has='...']`, and discard if `-abp-properties` is used.

**Comment by Alex-302** [comment]
Can we close it?

**Comment by ameshkov** [comment]
@Alex-302 nope, we'd better do it

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersCompiler #4](https://github.com/AdguardTeam/FiltersCompiler/issues/4) via [**ZenHub**](https://www.zenhub.com/)
