### ISSUE TITLE
wunderground.com - incorrect blocking

### ISSUE THREAD

**Issue by vishchakl** [AdguardTeam/AdguardFilters#5622]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
Incorrect blocking when using Adguard Browser Extension on https://www.wunderground.com/cgi-bin/findweather/getForecast?query=zmw:30189.1.99999&MR=1

Reproduced on Mac with Chrome Browser Extension
Ticket ID: 1154975
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screen shot 2017-07-10 at 4 42 11 pm](https://user-images.githubusercontent.com/29872276/28021983-68501fce-6592-11e7-82c0-2929091ca9f4.png)

</details>

**Comment by Alex-302** [comment]
Fixed.
