### ISSUE TITLE
adtorque.in [N: AdGuard Home] [T: Ads]

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#56225]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

A sponsored app row near the top is currently not blocked inside the `https://play.google.com/store/apps/details?id=com.sm.volte` app. I propose that `||adtorque.in^` be added to AdGuard Mobile Filter.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/83039664-bac34f80-a03e-11ea-9d43-e2022aab4eb7.png)

</details><br/>

* **Expected behaviour**: 

The sponsored app row is blocked.

***Steps to reproduce the problem***:

1) Download `https://play.google.com/store/apps/details?id=com.sm.volte`.
2) Open it.
3) Choose "No, give me less relevant ads" when prompted.
4) When reaching the main menu, the sponsor row shows up.

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/83039939-0249db80-a03f-11ea-9ed1-a447b2d76a47.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android 9
Operating system version (Android/iOS) | Motorola stock firmware
Browser:                               | N/A
AdGuard version:                       | AdGuard Home 0.102.0
Filters enabled:                       | See sceenshot above
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | N/A
Helpdesk ID (if exists):               | N/A

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Done.
