### ISSUE TITLE
bild.de - antiadblock script

### ISSUE THREAD

**Issue by vishchakl** [AdguardTeam/AdguardFilters#5624]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screen shot 2017-07-10 at 6 38 23 pm](https://user-images.githubusercontent.com/29872276/28026515-0282dd78-659f-11e7-8ffa-9c0682cb2238.png)

</details>

***Steps to reproduce the problem***:

http://www.bild.de/

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | English, Spyware, Social media, Annoyances, Russian, German
Ticket ID: | 1483141

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Please check for updates.

**Comment by vishchakl** [comment]
works fine. thanks!

**Comment by ypetruk** [comment]
@Alex-302 anti-adblock script is present on bild.de again on Windows
Ticket ID: 1605114

**Comment by Alex-302** [comment]
Can't reproduce.
Please try to clear site data

<details>

![image](http://imagizer.imageshack.com/img923/9845/0hvH7Z.png)
</details>

**Comment by ypetruk** [comment]
@Alex still have it on Mac OS and on iOS

Ticket ID: 1608425

**Comment by Alex-302** [comment]
Still can't reproduce.

**Comment by Alex-302** [comment]
Unnecessary filters```
ID=101 Name="EasyList" Version=1.0.70 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.62.93 Enabled=YES
```
try to disable
```
ID=237 Name="AdBlock Protector List" Version=1.0.0.7 Enabled=YES
```
