### ISSUE TITLE
pokehunter.co - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5627]
***Site***: https://pokehunter.co/
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28029507-94a518a0-65a0-11e7-834c-25484953cd2b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.28
Spyware filter | 1.0.13.20
Social media filter | 1.0.20.98
Annoyances filter | 1.0.15.19
German filter | 1.0.35.39
Mobile ads filter | 1.0.8.88
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
