### ISSUE TITLE
soundcloud.com - Ad/Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5628]
***Site***: https://soundcloud.com/stream
***Description***: Soundcloug Go+ ad

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28042571-2a1364be-65ce-11e7-97e5-d5e21c691157.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.38
Spyware filter | 1.0.13.23
Social media filter | 1.0.21.4
Annoyances filter | 1.0.15.27
German filter | 1.0.35.45
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by danidoedel** [comment]
`soundcloud.com##.streamHTUpsell`

**Comment by AdamWr** [comment]
I can't reproduce.

**Comment by danidoedel** [comment]
@AdamWr Still there for me:

![image](https://user-images.githubusercontent.com/10995998/32134346-ed54c35a-bbeb-11e7-9f38-a3e618f93f65.png)

**Comment by AdamWr** [comment]
Yes, I think html will be useful :)

By the way, does this rule still works - `soundcloud.com##.streamHTUpsell`?

**Comment by danidoedel** [comment]
@AdamWr Yep that rule is still the same. There is one more annoyance at the top right:

![image](https://user-images.githubusercontent.com/10995998/32404789-e25d2b7e-c157-11e7-8937-3c6edf8449f9.png)

Here are the files:

[soundcloud.zip](https://github.com/AdguardTeam/AdguardFilters/files/1443154/soundcloud.zip)

**Comment by AdamWr** [comment]
Thank you.

Adde to Annoyances filter:
`soundcloud.com##.activity > .streamHTUpsell`
`soundcloud.com##.dashbox > .dashbox__wrapper > a[href="/go#feature-chart"] > img`
