### ISSUE TITLE
circa.com - Ad leftover - Incorrect Blocking - Social widgets

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5629]
***Site***: https://www.circa.com/
***Description***: Ad leftover at the top. Social icons missing. Share icons not removed.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28042630-6e128c30-65ce-11e7-9fe2-20c97ece1e86.png)

![image](https://user-images.githubusercontent.com/10995998/28042664-8ff9dd4e-65ce-11e7-94b0-3bcea34d058f.png)

**https://www.circa.com/story/2017/07/10/politics/harvards-head-of-its-international-negotiation-program-shows-us-how-to-discuss-politics:**

![image](https://user-images.githubusercontent.com/10995998/28042690-abfb96f4-65ce-11e7-971e-e24a4c62c007.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.38
Spyware filter | 1.0.13.23
Social media filter | 1.0.21.4
Annoyances filter | 1.0.15.27
German filter | 1.0.35.45
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by danidoedel** [comment]
```
circa.com##.Page-ad
circa.com#@#.icon-facebook
circa.com#@#.icon-twitter
circa.com##.ShareBar
```

**Comment by AdamWr** [comment]
Fixed.
