### ISSUE TITLE
mein-mmo.de (Google AMP) - Ads - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5630]
***Site***: https://www.google.de/amp/mein-mmo.de/warframe-open-world/amp/
***Description***: Ads. Ad and social icons leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28042757-f3145152-65ce-11e7-9759-7c683e45e5ef.png)

![image](https://user-images.githubusercontent.com/10995998/28042766-fda2786a-65ce-11e7-8794-8cd2d925d4fd.png)

Ad leftover and social icons leftover:

![image](https://user-images.githubusercontent.com/10995998/28042783-1a13c9cc-65cf-11e7-9572-080eee622dc1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.38
Spyware filter | 1.0.13.23
Social media filter | 1.0.21.4
Annoyances filter | 1.0.15.27
German filter | 1.0.35.45
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
