### ISSUE TITLE
nwzonline.de - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5632]
***Site***: https://mobil.nwzonline.de/
***Description***: Whatsapp newsletter. Annoying share bar at the top of articles. Ad leftover after article.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28043002-2deb2872-65d0-11e7-9d23-6d50d2485222.png)

**https://mobil.nwzonline.de/fussball/nationalspieler-ruediger-von-rom-nach-chelsea_a_31,3,1943858483.html:**

![image](https://user-images.githubusercontent.com/10995998/28043024-45b12eac-65d0-11e7-80b4-887f897e5b50.png)

![image](https://user-images.githubusercontent.com/10995998/28043058-63592f68-65d0-11e7-93e7-719e1409dddd.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.38
Spyware filter | 1.0.13.23
Social media filter | 1.0.21.4
Annoyances filter | 1.0.15.27
German filter | 1.0.35.45
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
