### ISSUE TITLE
mz-web.de - Annoyance - Ad - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5633]
***Site***: http://mobil.mz-web.de/
***Description***: Newsletter stuff and Ad on main page. Social share leftover at the top of an article and share icon leftover when scrolling down.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28043215-2aa45afc-65d1-11e7-9453-513b7565f45e.png)

**http://mobil.mz-web.de/wirtschaft/deutscher-aussenhandel-deutsche-exporte-steigen-kraeftig--27947158:**

![image](https://user-images.githubusercontent.com/10995998/28043230-3dc59b82-65d1-11e7-8147-583080496c8e.png)

![image](https://user-images.githubusercontent.com/10995998/28043311-9e7a15de-65d1-11e7-9ef9-083e55502370.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.38
Spyware filter | 1.0.13.23
Social media filter | 1.0.21.4
Annoyances filter | 1.0.15.27
German filter | 1.0.35.45
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
I can not reproduce ad.
 Other elements fixed.
