### ISSUE TITLE
Pakistani Tv app - Missed ad - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5635]
***Description***:  
Pakistani Tv by S3Technology
https://appsto.re/us/dEv_D.i

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28048748-954e8e70-65fb-11e7-8ec9-c93b36c90a96.png)

![screen shot 2017-07-11 at 5 41 41 am](https://user-images.githubusercontent.com/27292111/28048757-af07ac5c-65fb-11e7-91e0-7bf28cae35ac.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.23.70 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.12 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.83 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.7.97 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.52 Enabled=YES
Annoyances filter = YES

Ticket ID: 1496245

**Comment by Alex-302** [comment]
Please check this rule:
```
||graph.facebook.com^
```
Facebook will be broken.
