### ISSUE TITLE
music.yandex.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5636]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: There's a banner which we fail to block in multiple browsers

The link: https://music.yandex.ru/album/3799688

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28055356-3b6ab872-6621-11e7-8c47-66cfd36fa179.png)
</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Vivaldi, Edge
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
HTTPS filtering: |  On 
Stealth mode options(Windows) | see below
Adguard filters: | 1 2 3 4 207 24
Ticket ID: | 1099770

<details><summary>Stealth mode:</summary>

Stealth Mode enabled: StealthModeSettings: {

-   "BlockThirdPartyCookies": true,
-   "BlockThirdPartyCookiesPeriodMin": 30,
-   "BlockFirstPartyCookies": false,
-   "BlockFirstPartyCookiesMin": 2880,
-   "DisableThirdPartyCache": true,
-   "BlockWebRtc": false,
-   "BlockBrowserPushApi": false,
-   "BlockBrowserLocationApi": true,
-   "RemoveXClientDataHeader": true,
-   "HideSearchQueries": true,
-   "SendDoNotTrackHeader": false,
-   "RemoveRefererFromThirdPartyRequests": false,
-   "HideUserAgent": false,
-   "CustomUserAgent": null,
-   "CustomReferer": null,
-   "HideIp": false,
-   "CustomIp": "209.141.53.254"

</details>

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. I need screenshot of HTML code of this banner.

**Comment by TemaZosin** [comment]
<div class="bar__megafon-container"><a target="_blank" href="http://ads.adfox.ru/256152/goLink?p1=bwvvu&amp;p2=foom&amp;p5=ertgz&amp;pr=11192@http://www.megafon.ru/ad/join?utm_source=yandex-music&amp;utm_medium=ag-media_media_playlist_none_branding_day&amp;utm_campaign=b2c_flight_www-b2c_vklychaysya-may-jun-2017_rf&amp;utm_term=creative-listen" class="bar__megafon-image"></a></div>



![image](https://user-images.githubusercontent.com/17345756/28076259-c08ec602-6666-11e7-9271-9a74f8c30718.png)

**Comment by Alex-302** [comment]
Please check for updates.

**Comment by TemaZosin** [comment]
Can't check now, coz Yandex removed the banner (promotion has been ended and even doesn't show without adguard).
