### ISSUE TITLE
chop-druzhina.ru - false positive

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#5637]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
Elements get blocked by mistake. 
* **Current behaviour**: 
Can't see some of the pictures with English filter enabled. Could be because of elements containing "adv" in their source. `<div class="adv_item"></div>`

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](http://i.imgur.com/XMLPpsh.png)
</details>

* **Expected behaviour**: 
We should be able to see those pictures. 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](http://i.imgur.com/4phS10E.png)
</details>

***Steps to reproduce the problem***:
Visit [chop-druzhina.ru](https://www.chop-druzhina.ru/)
Try disabling/enabling English filter. 

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
Adguard filters: | English, Spyware, Social media, Unblocking useful ads, Russian. 
Ticket ID (if exists): | 1583689

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
