### ISSUE TITLE
WPCP annoyance on over 70000 websites

### ISSUE THREAD

**Issue by kulfoon** [AdguardTeam/AdguardFilters#56382]
https://github.com/uBlockOrigin/uAssets/issues/7468

**Comment by Alex-302** [comment]
I agree with the last comment.

**Comment by Alex-302** [comment]
In some cases it does not simple to remove duplicates(for example platform relater rules)

**Comment by Alex-302** [comment]
Filters Compiler make sorting of filters and removes duplicates for each plathorm.
