### ISSUE TITLE
rtl.de (Google AMP) - Ad leftover - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5638]
***Site***: https://www.google.de/amp/amp.rtl.de/cms/dance-dance-dance-2017-diese-sieben-promi-teams-schwingen-das-tanzbein-4119475.html
***Description***: Ad leftover in article. Social share leftover and ad leftover after article.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28067187-7c746d3a-6640-11e7-9d74-945ea92a9b86.png)

![image](https://user-images.githubusercontent.com/10995998/28067250-b58883e0-6640-11e7-913e-33486a2daa13.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.42
Spyware filter | 1.0.13.23
Social media filter | 1.0.21.5
Annoyances filter | 1.0.15.28
German filter | 1.0.35.46
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
