### ISSUE TITLE
vip.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5639]
***Site***: http://www.vip.de/cms/endlich-michael-schumacher-in-der-hall-of-fame-des-deutschen-sports-4119567.html
***Description***: Ad leftover in article and after article.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28067361-43c7a7d0-6641-11e7-8a39-76d7625120b2.png)

![image](https://user-images.githubusercontent.com/10995998/28067373-4fa842f8-6641-11e7-8ec9-cfc612512f8d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.42
Spyware filter | 1.0.13.23
Social media filter | 1.0.21.5
Annoyances filter | 1.0.15.28
German filter | 1.0.35.46
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
