### ISSUE TITLE
http://streamsport.org/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#564]
Реклама при просмотре видео.

https://qcrm.cc/#/customer/1040148

**Comment by Alex-302** [comment]
Как там смотреть-то? Жму Плей - играет ролик НТВ и на этом всё. Пусть прямые ссылки даст.

**Comment by vbagirov** [comment]
Я так понял там в некоторых плеерах реклама, правда поди найди, в каких именно.

**Comment by Alex-302** [comment]
Блин, похоже это псевдо-плеер. Там ниже если прокрутить действительно трансляция (когда смотрел - плеер с livesportstreams.watch)
Уточни у юзера, везде ли так, наверное то что сверху выпилить надо
