### ISSUE TITLE
mein-wahres-ich.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5640]
***Site***: http://www.mein-wahres-ich.de/bist-du-ein-echtes-genie.html
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28067603-2ef310dc-6642-11e7-94a4-44334ae96bb8.png)

![image](https://user-images.githubusercontent.com/10995998/28067540-0430f06c-6642-11e7-9bd1-ec10015eb904.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.42
Spyware filter | 1.0.13.23
Social media filter | 1.0.21.5
Annoyances filter | 1.0.15.28
German filter | 1.0.35.46
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
