### ISSUE TITLE
otakarablog.com

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#56409]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Bad site, you'll get some random redirect and will reach browser hijacker or other scam sites.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![otakarablog](https://user-images.githubusercontent.com/58900598/83282589-c5374200-a214-11ea-9039-dc85232aa17d.png)

</details><br/>

* **Expected behaviour**: 

Such sites should be blocked by Browsing security.

***Steps to reproduce the problem***:

Visit the site.

***System configuration***

**Filters:**

Base, Tracking, & Japanese

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox 76.0.1
AdGuard version:                       | 3.4.19
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Disabled

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Yuki2718** [comment]
@Chinaski1 @zzebrum

**Comment by Chinaski1** [comment]
Blacklisted!
