### ISSUE TITLE
pcmag.com - the ad - iOS

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5641]
***Description***:
* **Current behaviour**: 

Before entering the web-site there is the ad, which makes you unable to read the article unless you press on it. It redirects you to itunes.
Reproduce on our side.

The web-site is:
http://www.pcmag.com/prestitial/pcmde.html?referrer=https%3A%2F%2Fwww.pcmag.com%2Fnews%2F345570%2Fapple-removes-encryption-from-ios-10-kernel-which-could-pay#

<details><summary>Screenshot:</summary>

![screen shot 2017-07-11 at 3 51 04 pm](https://user-images.githubusercontent.com/28784344/28069094-d84d3294-6650-11e7-96a6-e8e0384547d0.png)

</details>

<details><summary>Screenshot:</summary>

![screen shot 2017-07-11 at 3 51 22 pm](https://user-images.githubusercontent.com/28784344/28069099-de3ecf78-6650-11e7-8568-25d091906fca.png)

</details>

<details><summary>Screenshot:</summary>

![screen shot 2017-07-11 at 3 51 12 pm](https://user-images.githubusercontent.com/28784344/28069102-e1dab296-6650-11e7-8a3c-89ab70772f62.png)

</details>

***Steps to reproduce the problem***:

Just go on:
http://www.pcmag.com/prestitial/pcmde.html?referrer=https%3A%2F%2Fwww.pcmag.com%2Fnews%2F345570%2Fapple-removes-encryption-from-ios-10-kernel-which-could-pay#

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS / iOS
Adguard version: | 1.4.1 /  1.2.1.71
Adguard DNS: | None
Adguard filters: | 0, 2, 3, 4, 14, 1 , 11, 12, 103, 207, 211
Ticket ID (if exists): | 1147641

**Comment by Alex-302** [comment]
It is just redirecting URL. When it happens?
