### ISSUE TITLE
businessinsider.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#56422]
[https://www.businessinsider.com/how-to-get-subtitles-on-amazon-prime](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.businessinsider.com/how-to-get-subtitles-on-amazon-prime)

These affiliate links have been added to many articles: https://www.google.com/search?client=firefox-b-d&q=site%3Abusinessinsider.com++Check+out+the+products+mentioned

![affiliate links](https://user-images.githubusercontent.com/35470489/83302188-40770480-a1d1-11ea-8a42-4f7b1e0d490c.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
In general these links are not ads - you see approximate price of mentioned items.

**Comment by adranger** [comment]
These are third-party ads based on random keywords.  The words "the products mentioned" tricked you, but if you see the articles, they aren't product reviews. They are tutorials about websites and apps.

In the first example I gave you, readers open the page to read about Amazon Prime, but then get ads for specific computers and phones just because the author typed out the words "Mac or PC" in the text. 

Here's another example: [https://www.businessinsider.com/how-to-repost-instagram-story](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.businessinsider.com/how-to-repost-instagram-story). You open it to read about Instagram, but then get automated ads for specific phones. This is the same as any other keyword-based ad system.

Their system is also adding larger ad sections with pictures:


![ad banners](https://user-images.githubusercontent.com/35470489/83802890-ef0fbf00-a681-11ea-8544-dad6080b1348.png)
