### ISSUE TITLE
dn.se - Anti AdBlock pop-up - Android 

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5642]
***Description***:
* **Current behaviour**: 

There is the Anti AdBlock pop-up on : http://www.dn.se/
Reproduced on our side

<details><summary>Screenshot:</summary>

![screen shot 2017-07-11 at 4 21 22 pm](https://user-images.githubusercontent.com/28784344/28070573-1082fbd0-6656-11e7-8cc5-6d269303a7c1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS / Android 
Adguard version: | 1.4.1. /  2.9.135
Adguard mode (Android): | Proxy(manual)
Filtering quality (Android): |  high-speed (advise to enable high - quality)
HTTPS filtering (Android): |  On (Default) 
Adguard DNS: | None 
Adguard filters: | 0, 2, 3, 4, 14, 11, 223 
Ticket ID (if exists): | 1456058

**Comment by Alex-302** [comment]
It is paywall. We don't block them.
For user filter:
```
dn.se###pwOverlay
```
