### ISSUE TITLE
tivitot.net - Ad Leftover - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5643]
***Description***:
* **Current behaviour**: 

Ads on tivitot.net
Reproduced on our side

<details><summary>Screenshot:</summary>

![20170710_172258](https://user-images.githubusercontent.com/28784344/28071594-0f24a5b0-6659-11e7-9ede-feefa2a9b7b7.jpg)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS/ Android 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 0, 1, 2, 3, 4, 11, 14
Ticket ID (if exists): | 1589451

**Comment by Alex-302** [comment]
Added to English filter
```
||tivitot.net/qc/babilon-trai.php
tivitot.net##div[class^="ads"]
tivitot.net##div[id^="Ads_"]

```
