### ISSUE TITLE
com.internet.speedtest.check.wifi.meter

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#56444]
***Description***:
* **Current behaviour**: 

Has a few missed ads.

<details><summary>Screenshot:</summary>

![stads1](https://user-images.githubusercontent.com/33634917/83320559-7c51ae80-a251-11ea-911f-565a16fd4f6b.png)
![stads2](https://user-images.githubusercontent.com/33634917/83320562-7fe53580-a251-11ea-9e47-a0dad1fabb3b.png)

</details><br/>

***Steps to reproduce the problem***:

Just install the app. Ads will be there.

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 10
Browser:                               | N/A
AdGuard version:                       | 3.4.120
Filters enabled:                       | "Polish Anti Adblock Filters", "YousList", "hufilter", "Adblock Warning Removal List", "AdGuard Dutch filter", "Frellwit's Swedish Filter", "AdGuard Mobile Ads filter", "xinggsf", "(Obsolete) Schacks Adblock Plus liste", "EasyList Hebrew", "NoCoin Filter List", "road-block", "Fanboy's Vietnamese", "RU AdList: BitBlock", "Peter Lowe's Blocklist", "AdGuard Russian filter", "AdGuard Turkish filter", "Official Polish filters for AdBlock, uBlock Origin & AdGuard", "AdGuard Experimental filter", "I don't care about cookies", "AdGuard Tracking Protection filter", "Fanboy's Social Blocking List", "Polskie Filtry Wewnętrzne", "ABP Japanese Filters", "EasyList China", "EasyList Italy", "Fanboy Anti-Facebook List", "Liste AR", "EasyList", "ROList", "Bulgarian list", "CJX's Annoyance List", "BarbBlock", "AlleBlock", "AdGuard Annoyances filter", "AdGuard Safari filter", "(Obsolete) Anti-Adblock Killer | Reek", "Polskie Filtry Społecznościowe", "AdGuard German filter", "Dandelion Sprout's Nordic Filters", "Polskie Filtry Ciasteczkowe", "Iranian filter", "gressyfork", "AdGuard Simplified domain names filter", "Adblock List for Finland", "AdGuard French filter", "Filter unblocking search ads and self-promotion", "EasyList Dutch", "Web Annoyances Ultralist", "Estonian List", "(Obsolete) Korean Adblock List", "uBlock filters", "Adblock-Persian list", "(Obsolete) Wiltteri", "Fanboy's Enhanced Tracking List", "ROLIST2", "Xfiles", "Spam404", "Easylist Spanish", "ABPVN List", "AdGuard Social Media filter", "EasyList Polish", "Malware Domains Blocklist", "Icelandic ABP List", "Polskie Filtry Elementów Irytujących", "AdGuard Japanese filter", "(Obsolete) Prebake", "RU AdList: Counters", "List-KR", "AdGuard Spanish/Portuguese filter", "EasyList Czech and Slovak", "Fanboy's Anti-thirdparty Fonts", "Polski Antyirytujący Dodatek Specjalny", "EasyPrivacy", "Fanboy's Spanish/Portuguese", "EasyList Germany", "ABPindo", "KAD - Przekręty", "EasyList Lithuania", "Greek AdBlock Filter", "Liste FR", "Fanboy's Swedish", "Fanboy's Annoyances", "ChinaList+EasyList", "EasyList Cookie List", "RU AdList", "Thai Ads Filters", "AdBlockID", "AdGuard Base filter", "Latvian List"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On, default mode
AdGuard DNS:                           |  Default, DoH
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | 2430393

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Cannot be blocked, they are built-in.
