### ISSUE TITLE
clashofclansforum.de - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5646]
***Site***: https://clashofclansforum.de/index.php/Thread/12910-Warbase-Engi-d/
***Description***: Facebook leftover and ad leftover in left sidebar. Ad post in forum and ad leftovers between forum posts.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28077412-ff69f7ca-6661-11e7-85b0-3fb2ddf43d82.png)

![image](https://user-images.githubusercontent.com/10995998/28077336-ccd4fbe8-6661-11e7-94e3-d3ac2f17baeb.png)

![image](https://user-images.githubusercontent.com/10995998/28077360-e006d600-6661-11e7-9317-94e1efb7af21.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.44
Spyware filter | 1.0.13.23
Social media filter | 1.0.21.7
Annoyances filter | 1.0.15.30
German filter | 1.0.35.47
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by danidoedel** [comment]
```
clashofclansforum.de##.fbLikeCounter
clashofclansforum.de##.wcfAdLocation
clashofclansforum.de###main > div > div > aside.sidebarMenu:first-child > nav.mainMenu.sidebarCustomBox:last-child
```

Not sure about the last one for the small leftover in the sidebar though. Maybe there is some simpler rule I'm not aware of ;)

**Comment by AdamWr** [comment]
Thank you.
Added:
`clashofclansforum.de##.fbLikeCounter`
`clashofclansforum.de##.wcfAdLocation`
`clashofclansforum.de##.sidebarMenu > [class="mainMenu sidebarCustomBox"][style="margin-top:10px"]:last-child`
