### ISSUE TITLE
catve.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#56493]
[https://www.catve.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.catve.com/)

Banners of different sizes being loaded from these URLs, including huge ones (parceiros = partners):
```
||catve.com/portal/img/parceiros/
||catve.akamaized.net/portal/img/parceiros/
```

![giant banner](https://user-images.githubusercontent.com/35470489/83342215-f53d1e80-a2c2-11ea-93ca-79c40c679a33.png)

----

[https://www.catve.com/noticia/8/290794/motociclista-fica-ferido-apos-bater-contra-carro-no-bairro-universitario](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.catve.com/noticia/8/290794/motociclista-fica-ferido-apos-bater-contra-carro-no-bairro-universitario)

Social icons:

![social sharing](https://user-images.githubusercontent.com/35470489/83342230-36cdc980-a2c3-11ea-9b7a-c54cf6b047aa.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
Fixed
