### ISSUE TITLE
[android] apkmirror.com - missed ads

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/AdguardFilters#565]

**Comment by Alex-302** [comment]
Добавил в английский(остатки рекламы заметны)
```
apkmirror.com##.google-ad-leaderboard
apkmirror.com##.google-ad-leaderboard-injected
apkmirror.com##.google-ad-square
```

**Comment by vgavrish** [comment]
Остатки рекламы
Фильтры: 1,2,3,4,11,14
http://www.apkmirror.com/apk/google-inc/pixel-launcher/pixel-launcher-7-1-3231428-release/pixel-launcher-7-1-3231428-android-apk-download/#notes
<details>
![image](https://cloud.githubusercontent.com/assets/18548949/19321698/b58eb2ea-90be-11e6-8b26-e0ecea754fe7.png)
![image](https://cloud.githubusercontent.com/assets/18548949/19321755/ee40c83a-90be-11e6-985f-15b5c5decbba.png)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
apkmirror.com##.OUTBRAIN
||widgets.outbrain.com^$domain=apkmirror.com
```
