### ISSUE TITLE
cannot input url / website

### ISSUE THREAD

**Issue by 3xploiton3** [AdguardTeam/AdguardFilters#56502]
I cannot input this url 

https://m.bukalapak.com/products?source=navbar&from=omnisearch&search%5Bkeywords%5D=earphone&search[sort_by]=weekly_sales_ratio:desc

![Screenshot_2020-05-31-16-12-46-951_org mozilla firefox](https://user-images.githubusercontent.com/19517680/83348754-7941e580-a359-11ea-888a-80415ead40d2.jpg)

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/ReportsWebApp #237](https://github.com/AdguardTeam/ReportsWebApp/issues/237) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
@3xploiton3 What should we do on this site?
