### ISSUE TITLE
rzcracks.com [Fake Buttons]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#56506]
https://rzcracks.com/hitman-pro-build-crack-product-key-free-download/

Please remove the two fake buttons on the page. Checked with AG for Chrome.

https://i.imgur.com/agnZV75.png

**Comment by AdamWr** [comment]
I'm not sure about these two buttons from screenshot. First one doesn't work, second open `rzcracks.com` in the new tab.
Fixed two other buttons.
