### ISSUE TITLE
sat1.de - Social widget - Ad leftover - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5650]
***Site***: https://www.sat1.de/tv/hochzeit-auf-den-ersten-blick/playlisten/alle-ganzen-folgen
***Description***: Ads before video starts. Facebook leftover and ad leftover in sidebar.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28084668-9e6f3de6-6679-11e7-9bf8-3bc6f66e4883.png)

![image](https://user-images.githubusercontent.com/10995998/28084744-e7df1b04-6679-11e7-9f20-b415932bdca8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.44
Spyware filter | 1.0.13.23
Social media filter | 1.0.21.7
Annoyances filter | 1.0.15.30
German filter | 1.0.35.47
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
