### ISSUE TITLE
Блокировка лишних элементов на Яндекс

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#56512]
Здравствуйте, требуется заблокировать лишние элементы на Яндексе (обведены в КРАСНЫЙ кружок или на них указывает КРАСНАЯ стрелка). Какие-то мешают, какие-то отвлекают, а какие-то нарушают конфиденциальность. Возможно ли это сделать? Возможно ли добиться результата используя пользовательский фильтр? Если да, то какое правило я должен добавить?
Платформа - расширение.
Заранее спасибо! Скриншоты приведены ниже.

![20200531_150152](https://user-images.githubusercontent.com/66206443/83352010-3419b580-a351-11ea-9e06-46a2a0fbc284.jpg)
![20200531_145610](https://user-images.githubusercontent.com/66206443/83352011-35e37900-a351-11ea-932e-282ec19bcb4c.jpg)
![Screenshot_20200531-145719](https://user-images.githubusercontent.com/66206443/83352012-367c0f80-a351-11ea-9e87-3d09b13ab1ef.jpg)
![Screenshot_20200531-145810](https://user-images.githubusercontent.com/66206443/83352013-37ad3c80-a351-11ea-8676-1ab94a6bacad.jpg)

И это:
![Screenshot_20200531-152434](https://user-images.githubusercontent.com/66206443/83352412-ccb13500-a353-11ea-987a-ae5d15731e4b.jpg)

**Comment by temp-account-123** [comment]
Также, требуется заблокировать выделенные элементы здесь:

![Screenshot_20200531-152712](https://user-images.githubusercontent.com/66206443/83352351-7c39d780-a353-11ea-819f-8f0f4bfc5d4f.jpg)

А здесь заблокировать вообще всё:
![Screenshot_20200531-152744](https://user-images.githubusercontent.com/66206443/83352378-9f648700-a353-11ea-85e6-a6c2c639bc70.jpg)

**Comment by Alex-302** [comment]
Не проще использовать ya.ru?

Удалить ненужные элементы можно исследовав элементы страницы. 
Как это сделать на Android используя ПК
https://developers.google.com/web/tools/chrome-devtools/remote-debugging
Описание селекторов CSS
https://code.tutsplus.com/ru/tutorials/the-30-css-selectors-you-must-memorize--net-16048
Синтаксис AdGuard
https://kb.adguard.com/ru/general/how-to-create-your-own-ad-filters
