### ISSUE TITLE
sat1gold.de - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5651]
***Site***: https://www.sat1gold.de/tv/k-11-kommissare-im-einsatz/video/524-staffel-5-episode-24-toedlicher-vaterschaftstest-ganze-folge
***Description***: Ads before video starts.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28084805-1671bddc-667a-11e7-8d50-27ff00e3e8e4.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.44
Spyware filter | 1.0.13.23
Social media filter | 1.0.21.7
Annoyances filter | 1.0.15.30
German filter | 1.0.35.47
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
