### ISSUE TITLE
prosiebenmaxx.de - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5654]
***Site***: https://www.prosiebenmaxx.de/tv/wwe-raw/video/201726-raw-vom-05-juli-ganze-folge
***Description***: Ads before video starts.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28085113-f781b5de-667a-11e7-8edd-c044e4c91a6a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.369.1938
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.44
Spyware filter | 1.0.13.23
Social media filter | 1.0.21.7
Annoyances filter | 1.0.15.30
German filter | 1.0.35.47
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
