### ISSUE TITLE
greenbayphoenix.com - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5657]
***Site***: http://greenbayphoenix.com/
***Description***: Site content is blocked. Works fine without Adguard.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28093445-94fa67c2-6697-11e7-8e76-99fde23be1af.png)

**Without Adguard:**

![image](https://user-images.githubusercontent.com/10995998/28093485-c315aa54-6697-11e7-9de9-ce3a279a62e0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.44
Spyware filter | 1.0.13.23
Social media filter | 1.0.21.7
Annoyances filter | 1.0.15.30
German filter | 1.0.35.47
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.
