### ISSUE TITLE
elcorreo.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5658]
***Site***: http://www.elcorreo.com/
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28093619-6d8be282-6698-11e7-94f2-55a34e4f4847.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.44
Spyware filter | 1.0.13.23
Social media filter | 1.0.21.7
Annoyances filter | 1.0.15.30
German filter | 1.0.35.47
Spanish/Portuguese filter | 1.0.86.72
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Resolved with https://github.com/AdguardTeam/AdguardFilters/commit/9d8cb30eb73cc4bd470c1d5896b0a2fc45ecf2c1
