### ISSUE TITLE
http://mobile.1haza.com/ - ads

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5659]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://mobile.1haza.com/vod-detail-id-3930.html - missed ad on page 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/23372054/28098125-2730c99a-66bd-11e7-8dc8-f425e8fddf89.png)

</details>

***System configuration***

Application version: 1.2.1.71
Device: iPhone
OS: 10.3.1
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.23.92 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.18 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.92 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.52 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.92 Enabled=NO
ID=104 Name="EasyList China" Version=1.0.83.49 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.3.34 Enabled=YES
Ticket ID: 1461742

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
mobile.1haza.com##.main > a:not([href*="1haza.com"]) > img[width="100%"]
mobile.1haza.com##.wrapper > a:not([href*="1haza.com"]) > img[width="100%"]

```
