### ISSUE TITLE
https://www.gazeta.ru/ - yandex direct

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5660]
Ads on the gazeta.ru main page.

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28104226-a3f7f622-66e2-11e7-80e0-50473daedfaf.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | FF, Chrome
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP or TDI
Adguard DNS: | None
Stealth mode options(Windows) | off
Adguard filters: | Russian, English, German, 
Ticket ID: | 1590922 1591247 1527855

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
> Добрый день установил на компьютер
> программу, купил пожизненную лицензию
> захожу на сайт gazeta.ru, захожу в любое
> сообщение-новость и реклама
> появляется.

**Comment by Alex-302** [comment]
Поправил. Через час-полтора можно будет проверять обновления.
