### ISSUE TITLE
cinesift.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5661]
***Site***: https://cinesift.com/
***Description***: Adblock detection. No results will load with Adguard enabled.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28110608-3dc4fd6c-66f3-11e7-9db8-289e94633bc3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.51
Spyware filter | 1.0.13.24
Social media filter | 1.0.21.9
Annoyances filter | 1.0.15.35
German filter | 1.0.35.50
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
I can not reproduce, but please check this rule:
`@@||cinesift.com/js/ads.js`

**Comment by danidoedel** [comment]
Also couldn't reproduce it anymore. Will try again later or tomorrow.

**Comment by AdamWr** [comment]
Fixed.
