### ISSUE TITLE
moviefone.com - Ad leftover - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5662]
***Site***: https://www.moviefone.com/new-movie-releases/
***Description***: Ad leftover bar at the top. Adblock detection at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28113015-4a8d035c-66fb-11e7-8624-4f0e2bcbc449.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.51
Spyware filter | 1.0.13.24
Social media filter | 1.0.21.9
Annoyances filter | 1.0.15.35
German filter | 1.0.35.50
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by seanl-adg** [comment]
Fixed
