### ISSUE TITLE
csgostash.com - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5663]
***Site***: https://csgostash.com/
***Description***: Ad at the left.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28113964-05c77834-66ff-11e7-831b-9d6870dead63.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.52
Spyware filter | 1.0.13.25
Social media filter | 1.0.21.10
Annoyances filter | 1.0.15.36
German filter | 1.0.35.50
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr There are again some ads/ad leftover:

**https://csgostash.com/item/10276/Krakow-2017-Mirage-Souvenir-Package:**

![image](https://user-images.githubusercontent.com/10995998/28264180-148ebbb8-6aea-11e7-9767-700cf736b5ed.png)

**https://csgostash.com/:**

![image](https://user-images.githubusercontent.com/10995998/28264199-2b7c5858-6aea-11e7-92a3-8d1c0f3f8560.png)

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr Aaaaand again:

![image](https://user-images.githubusercontent.com/10995998/28308693-51d9a74a-6ba7-11e7-91ab-9f5caaa833b5.png)

`csgostash.com##.adv-footer`

**Comment by AdamWr** [comment]
Added:
`csgostash.com##a[href^="https://goo.gl/"][target="_blank"].hypercase-button > img`
`csgostash.com##.adv-footer`
I hope this time all ads be hidden.

**Comment by danidoedel** [comment]
@AdamWr 
Some new ad leftover and ad ;)

![image](https://user-images.githubusercontent.com/10995998/28646000-cefc943a-725f-11e7-8738-30d10d2842a7.png)

**Comment by AdamWr** [comment]
Ok, fixed.
