### ISSUE TITLE
gamer.ru

### ISSUE THREAD

**Issue by dtitbd** [AdguardTeam/AdguardFilters#5664]
Фоновая реклама снизу доверху.

<details>

![image](https://user-images.githubusercontent.com/17032471/28116364-49139b4a-6722-11e7-80ae-803e9180ed3f.png)

</details>
Большой скрин с ПК:
<details>

![screencapture-gamer-ru-1499860650241](https://user-images.githubusercontent.com/17032471/28116637-532a6860-6723-11e7-8979-39a50d17231a.png)

</details>

Information | value
--- | ---
Operating system: |  Android 
Browser: | Chrome
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard DNS: | None
Adguard filters: | [аналогично этим](https://camo.githubusercontent.com/2e4ffa92acc5f1ab3b96fd490f4974c950be8863/687474703a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f66393931333262656136656334313134626631616238653235303831313563662e706e67)  (обновлены)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
gamer.ru##.alarmalarm-backtop
gamer.ru##.under-back

```

**Comment by dtitbd** [comment]
А разве это не брендинг?
![111](https://user-images.githubusercontent.com/17032471/28134214-ba606312-675b-11e7-8fcf-65d0ef17be16.png)
Да и на других страницах цвет скачет: 
![1](https://user-images.githubusercontent.com/17032471/28134252-d9a11226-675b-11e7-9556-21e0ed9e0a31.png)
![2](https://user-images.githubusercontent.com/17032471/28134253-db638b52-675b-11e7-86a5-14855590b88a.png)
Просто у них во всех class'ах есть цвет `background: #C8BEA3;` (бежевый цвет), но как правило он перебивается цветом под картинку, но все равно везде в коде остается.
Если это не реклама, то можно личное правило, чтобы цвет всегда был #C8BEA3?

**Comment by dtitbd** [comment]
А, все, дошло, что эти фоновые картинки - чисто их блажь.
Можно тогда личное(-ые) правило(-а), чтобы убрать все картинки и цвет фона поменять на #C8BEA3.

**Comment by Alex-302** [comment]
Наверное лучше удалю правила.

> Можно тогда личное(-ые) правило(-а), чтобы убрать все картинки и цвет фона поменять на #C8BEA3.

```
gamer.ru#$#body > div.index { background: #C8BEA3!important; }
gamer.ru##.alarmalarm-backtop
gamer.ru##.under-back
gamer.ru#$#.center-top { background: #C8BEA3!important; }
```

**Comment by dtitbd** [comment]
> Наверное лучше удалю правила. 

Ну да.

Спасибо за личные правила, но еще пришлось добавить
```
gamer.ru##.part-2
gamer.ru##.part-1
gamer.ru##.under-under
gamer.ru##.under-under-under
```
Иначе в середине цвет остается и внизу картинка. А объединить их никак не получится?

**Comment by Alex-302** [comment]
Желательно как отдельные правила.
