### ISSUE TITLE
kicker.de shows ads again: locally hosted, possibly fallback

### ISSUE THREAD

**Issue by JayBrown** [AdguardTeam/AdguardFilters#5666]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
Adguard worked fine on kicker.de for ages, but now ads are popping up again.
* **Current behaviour**: 
on http://www.kicker.de they now seem to be using (fallback?) ads hosted locally on the kicker.de server, currently under the path ./image/U/950835064275/[FileName].gif, e.g. http://www.kicker.de/image/U/950835064275/9EvNDgob4qwMuTOJ4ISgiYXlUCsMu1.gif (*Note*: image only; javascript only on the site's primary pages)

[//]: # (Tell us what happens)

<details><summary>Screenshot:</summary>

![image](http://i.imgur.com/2OeRuJN.png)
</details>

* **Expected behaviour**: 
No ads, including local ads hosted on kicker.de servers

***Steps to reproduce the problem***:
the usual; should show ads for any user accessing kicker.de

***System configuration***

Information | value
--- | ---
Operating system: | OS X (10.11.6)
Browser: | Safari 10.1.1
Adguard version: | 1.4.1
Adguard DNS: | — 
Adguard filters: | Adguard: English, Spyware, Social media, Annoyances, Russian, German, French, Mobile Ads, Safari; EasyList: Easy List, EasyPrivacy, Fanboy's Social Blocking, Fanboy's Annoyances, Czech & Slovak, Germany, Fanboy's Enhanced Tracking; Other: Adblock Warning Removal, Anti-Adblock Killer (Reek), CJX's Annoyance, I don't care about cookies, Malware Domains, Peter Lowe's list, Prebake, Spam404
Ticket ID (if exists): | —

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Please chech this rule:
```
@@/ad_bomb/*$image,domain=kicker.de
```

**Comment by JayBrown** [comment]
Thank you, seems to work. (Emptied the cache beforehand.)

**Comment by danidoedel** [comment]
Seems to work on iOS/macOS, but still some ad on Windows (Chrome):

![image](https://user-images.githubusercontent.com/10995998/28127645-8f5d79a8-672d-11e7-8c4c-902f9529cb93.png)

**Comment by JayBrown** [comment]
Front page was fine; subpage had some ads again: http://www.kicker.de/news/fussball/bundesliga/startseite/701487/artikel_bosz-bilanziert_das-war-schlecht-von-uns.html

![grab](http://i.imgur.com/NioXfDj.jpg)

Moreover, video playback seems to be broken; will look at it further.

**Comment by JayBrown** [comment]
Broken video: http://www.kicker.de/news/video/2017989/video_grosse-enttaeuschung_misslungenes-bosz-debuet-beim-bvb.html … will check more videos.

**Comment by Alex-302** [comment]
Please check this rule 
```
kicker.de#%#window.trckd = true;
```

**Comment by danidoedel** [comment]
I don't have any ads there today. Will try again later or tomorrow...

**Comment by danidoedel** [comment]
But there is also some issue with the mobile site: 

![image](https://user-images.githubusercontent.com/10995998/28164755-19125832-67d1-11e7-9f25-6d98c6f9edb9.png)

![image](https://user-images.githubusercontent.com/10995998/28164739-07684038-67d1-11e7-92dc-8993da1d1f49.png)

**Comment by Alex-302** [comment]
fixed
