### ISSUE TITLE
Rules you can remove

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdguardFilters#56678]
For tripadvisor you can remove this outdated Cookie rule: https://github.com/AdguardTeam/AdguardFilters/commit/781fb24d4e3c90a0dea71d3dd7fe74549b329bb1
If you check for example tripadvisor.ie it won't be affect anymore.

A recent fix is made here for tripadvisor.de https://github.com/AdguardTeam/AdguardFilters/commit/260f5a1d8cb4ceb77bdd16de816adadcd09fe030
But other pages still needs to be added.

For Interpals.net you can remove these changes: https://github.com/AdguardTeam/AdguardFilters/commit/d457fb48559a9ebf6b021dbb6b5d178d70de2dc0
They made some changes on the page and after disabling these rule and reloading the page, clicking through photos still works fine. They are not necessary anymore.

Regards

**Comment by Alex-302** [comment]
Thanks, fixed.
