### ISSUE TITLE
mehr-tanken.de - Ads - iOS

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5668]
***Site***: http://mehr-tanken.de/
***Description***: Ads, rule: `@@/ad_bomb/*$image,domain=mehr-tanken.de` does fix it.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28128103-ee61edb6-672e-11e7-89ed-189afbb388c3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS 11
Browser: | Safari
Adguard version: | 1.2.2(95)
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.52
Spyware filter | 1.0.13.25
Social media filter | 1.0.21.10
Annoyances filter | 1.0.15.36
German filter | 1.0.35.50
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by AdamWr** [comment]
Added.
