### ISSUE TITLE
Ad blocking and DNS protection not working on IOS.

### ISSUE THREAD

**Issue by jws555** [AdguardTeam/AdguardFilters#56698]
For several days now ad blocking and DNS protection have not been working at all.  It started happening around the time the new ad guard ios interface was rolled out.  Nothing seems to be blocked any longer.  Before the update both were working great.

**Comment by jws555** [comment]
Hi Alex,

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jws555** [comment]
Hi Alex,

It seems like nothing is being blocked whether it is from a website in a browser or ads in an app.  Having Safari and DNS protection enabled or disabled doesn't seem to make a difference.  For instance I have an app PCH Slots that now none of the ads are being blocked.  Before all the ads used to be blocked.

Thanks,

Jeff

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Alex-302** [comment]
@jws555 Some ads are loaded by app directly(it requests images from their own CDN server)
Please try to open these addresses:
google-analytics.com
an.yandex.ru
an.yandex.net

Expected result - `DNS_PROBE_FINISHED_NXDOMAIN` message.
