### ISSUE TITLE
add to firefox addon: adblock & ublock polish filter 

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardFilters#5669]
I want this filter, why can't I see it in adguard filterlist, in my firefox adguard addon?

Can this be added?

Also what is the difference between:

adblock & ublock polish filter
and 
adblock & ublock polish filter - adguard

**Comment by worldsdream** [comment]
@Alex-302 @ameshkov I don't know if I should have posted it here or in the adguard extension repo on github. Can you forward it or add the right person to this post, so he is able to add it. Thanks!

**Comment by AdamWr** [comment]
It seems that in Adguard Extension for Firefox `Adblock & uBlock polish filters` has different name, it is `Adblock polskie reguły`.

> Also what is the difference between
adblock & ublock polish filter
and
adblock & ublock polish filter - adguard

First is general/main filter list for Polish websites, second is additional/supplement with only CSS rules.

![image](https://user-images.githubusercontent.com/29142494/28134956-f5c3ec1a-6744-11e7-85a8-57e5bf11b240.png)

**Comment by worldsdream** [comment]
I have enabled adblock polskie regurly. When I go to wp.pl, i see ads in the top.

**Comment by AdamWr** [comment]
It is beacuse, Adguard Extension for Firefox can not update JS rules.
To block these ads you need to add this rule to user filter:
`www.wp.pl#%#Object.defineProperty(window, 'testMess', { get: function() { return; }, set: function() {} });`

**Comment by worldsdream** [comment]
Thanks. Is there another rule that can be added instead of this js rule, so all users on firefox can get it automatically.

**Comment by AdamWr** [comment]
I can try hide these ads by cosmetic filters.
Please, check these rules:
```
www.wp.pl##[class^="_"] > div[style^="display: block; min-height: 0px;"]
www.wp.pl##[id^="sgwp_screening_"]
www.wp.pl###glonews > div[style^="display: block; min-height: 0px;"]
www.wp.pl##[class^="_"] > div > div[style^="display: block; min-height: 0px;"]
www.wp.pl##[class^="_"] > [class^="_"] > [class^="_"] > a[href][target="_blank"] > img
www.wp.pl##[class^="_"] > [class^="_"] > [class^="_"] > a[href][target="_blank"] + span
```

**Comment by worldsdream** [comment]
That worked thanks. Please push that to the filterlist. 

There is also a text ad when you scroll in the blue bar. On the right side. Can you remove it too?

**Comment by AdamWr** [comment]
Ok, I added these rules.

> There is also a text ad when you scroll in the blue bar.

You mean this?
![image](https://user-images.githubusercontent.com/29142494/28189770-b65707ea-6827-11e7-81f8-fdff93e82b04.png)
If yes, I added rule to hide this, but if you mean another element, please make a screenshot.

**Comment by worldsdream** [comment]
Yes thafs what I meant. Thank you!

**Comment by worldsdream** [comment]
@adamwr what is the best place to report polish ads, so you can fix and push it through the filterlist. Any github?

**Comment by AdamWr** [comment]
I think the best place to report Polish ads is here - https://github.com/MajkiIT/polish-ads-filter/issues
I have access to this filterlist (with my another github account), so I am able to add rules to this filterlist too.
