### ISSUE TITLE
roblox.com - Ad leftover - Ad - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5670]
***Site***: https://www.roblox.com/games/912766436/unnamed#!/about
***Description***: Ad leftover at the top. Ad at the right. Smartbanner at the bottom on mobile site.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28139828-038ffc10-6756-11e7-84c1-b27c76a2bdc1.png)

![image](https://user-images.githubusercontent.com/10995998/28139881-377f5f7a-6756-11e7-9ac8-ba9acaffde90.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.60
Spyware filter | 1.0.13.26
Social media filter | 1.0.21.11
Annoyances filter | 1.0.15.42
German filter | 1.0.35.53

**Comment by danidoedel** [comment]
```
roblox.com###Leaderboard-Abp
roblox.com###Skyscraper-Abp-Right
roblox.com##.ad-annotations
roblox.com##.app-bumper-container
```

**Comment by AdamWr** [comment]
Fixed.
