### ISSUE TITLE
post-gazette.com - Ad leftover - Annoyance - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5672]
***Site***: http://www.post-gazette.com/
***Description***: Many "Advertisement" label ad leftovers. Facebook logo in header blocked. Ad leftovers. Social share buttons on article page. Share bar on mobile page.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28140070-156f3b5c-6757-11e7-8d95-a1fda57261f6.png)

![image](https://user-images.githubusercontent.com/10995998/28140025-ebb0b16a-6756-11e7-8e8d-a6acae875400.png)

![image](https://user-images.githubusercontent.com/10995998/28140047-00e305e2-6757-11e7-83f8-11fd2c662aca.png)

**http://www.post-gazette.com/local/washington/2017/07/12/building-collapse-Washington-police-pennsylvania/stories/201707120156:**

![image](https://user-images.githubusercontent.com/10995998/28140269-f50b5caa-6757-11e7-99db-727a76384b15.png)

![image](https://user-images.githubusercontent.com/10995998/28140288-08fbbb7e-6758-11e7-8229-4a2a1942f397.png)

![image](https://user-images.githubusercontent.com/10995998/28140309-1b1e942a-6758-11e7-9d6e-d1ec308d1270.png)

![image](https://user-images.githubusercontent.com/10995998/28140335-3d41f420-6758-11e7-8788-7cd59eab3db8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.60
Spyware filter | 1.0.13.26
Social media filter | 1.0.21.11
Annoyances filter | 1.0.15.42
German filter | 1.0.35.53

**Comment by AdamWr** [comment]
Fixed.
