### ISSUE TITLE
bournemouthecho.co.uk - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5673]
***Site***: http://www.bournemouthecho.co.uk/
***Description***: Cookie notice at the bottom. Newsletter form. Outbrain and plista leftover after article.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28140413-8de6cb26-6758-11e7-9417-80188ae3a3bb.png)

**http://www.bournemouthecho.co.uk/news/15404872.VIDEO__Welcome_to_Operation_Close_Pass__undercover_police_on_bikes_ready_to_catch_careless_drivers/:**

![image](https://user-images.githubusercontent.com/10995998/28140471-bebf6ec4-6758-11e7-862a-f7ffa3959556.png)

![image](https://user-images.githubusercontent.com/10995998/28140489-cf984586-6758-11e7-9ced-ab9159d5ead5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.60
Spyware filter | 1.0.13.26
Social media filter | 1.0.21.11
Annoyances filter | 1.0.15.42
German filter | 1.0.35.53

**Comment by danidoedel** [comment]
```
bournemouthecho.co.uk###cookieWarningR
bournemouthecho.co.uk###cta1
bournemouthecho.co.uk##.cta-component-full-width
```

**Comment by AdamWr** [comment]
Added.
