### ISSUE TITLE
shz.de - Annoyance - Social widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5674]
***Site***: https://www.shz.de/regionales/schleswig-holstein/verkehr/hans-joern-arp-zu-a20-weiterbau-jahrelang-belogen-worden-id17284771.html
***Description***: Whatsapp newsletter leftover. Social share leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28140581-23dd3160-6759-11e7-97fc-dd36eb1f760b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.60
Spyware filter | 1.0.13.26
Social media filter | 1.0.21.11
Annoyances filter | 1.0.15.42
German filter | 1.0.35.53
Mobile ads filter | 1.0.8.89
Safari filter | 1.0.3.52

**Comment by danidoedel** [comment]
```
shz.de###whatsapp
shz.de###actions-fwid3
```

**Comment by AdamWr** [comment]
Fixed.
