### ISSUE TITLE
http://sarnovosti.ru/ - Ad leftover

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5675]
***Description***:
* **Current behavior**: 

There is the ad leftover on http://sarnovosti.ru/ (Android)
Reproduced on our side (Mac OS)

<details><summary>Screenshot:</summary>

![screen shot 2017-07-13 at 8 06 49 am](https://user-images.githubusercontent.com/28784344/28151308-8671a074-67a2-11e7-8f5c-f2c86857df00.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS / Android 
Browser: | chrome
Adguard version: | 1.4.1 / 2.9.135
Adguard mode (Android): | Proxy(manual)
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None
Adguard filters: | 3, 4, 14, 1, 5, 11, 211 
Ticket ID (if exists): | 1162662

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
