### ISSUE TITLE
"Obozrevatel" + "Football.ua" apps - Ad leftover - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5676]
***Description***:
* **Current behaviour**: 

There is an emply slot between the articles (on the place where the ad used to be) in the app "Obozrevatel". (https://play.google.com/store/apps/details?id=com.obozrevatel&hl=uk)

The same issue takes place for "Football.ua" app (https://play.google.com/store/apps/details?id=ua.football&hl=ru)

<details><summary>Screenshot:</summary>

![screenshot_20170712-084005](https://user-images.githubusercontent.com/28784344/28157552-8c5f2d0e-67bf-11e7-8568-88f3a1a0f8cc.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Adguard version: | 2.9.70
Adguard mode (Android): | Proxy(manual)
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default) 
Adguard DNS: | None 
Adguard filters: | 1,2,3,4,11,14, 0
Ticket ID (if exists): | 1543367

**Comment by Alex-302** [comment]
It is impossible to remove leftover in Obozrevatel app, only in Football.ua.
