### ISSUE TITLE
oddreaders.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5678]
***Site***: http://oddreaders.com/
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28159951-f80e5620-67be-11e7-8e53-1bcea068612e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.62
Spyware filter | 1.0.13.26
Social media filter | 1.0.21.11
Annoyances filter | 1.0.15.42
German filter | 1.0.35.54

**Comment by seanl-adg** [comment]
Fixed
