### ISSUE TITLE
https://m.dimonvideo.ru/ - ad leftover - iOS

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5679]
***Description***:
* **Current behaviour**: 
There is an ad leftover on https://m.dimonvideo.ru/vuploader.html on iOS. Has Adguard DNS enabled.

not reproduced on our side

<details><summary>Screenshot:</summary>

![image1](https://user-images.githubusercontent.com/28784344/28164174-cefc4ee6-67d6-11e7-8131-b9fea58c7571.jpeg)

</details>

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3.2
Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.22.74 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.92 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.72 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.52.99 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.51 Enabled=YES
+he added experimental filter, and annoyances filter

Ticket ID: 1315267

[com.adguard.AdguardPro.gz](https://github.com/AdguardTeam/AdguardFilters/files/1144949/com.adguard.AdguardPro.gz)
[com.adguard.AdguardPro.ActionExtension.gz](https://github.com/AdguardTeam/AdguardFilters/files/1144952/com.adguard.AdguardPro.ActionExtension.gz)
[com.adguard.AdguardPro.tunnel.gz](https://github.com/AdguardTeam/AdguardFilters/files/1144953/com.adguard.AdguardPro.tunnel.gz)

Problem Replay Time 07.25.

**Comment by Alex-302** [comment]
Also not reproduced, even without ad blocking(I see another ad in this case)
