### ISSUE TITLE
[android] Adguard-Avast-AnyBalance compatibility

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/AdguardFilters#568]
http://forum.adguard.com/showthread.php?5550-%D0%9D%D0%B5%D1%81%D0%BE%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%B8%D0%BC-%D1%81-Avast-Mobile-Security-Premium&p=51669#post51669

**Comment by Alex-302** [comment]
с обычной версией не повторилось, с Premium нет возможности проверить.
Отписал, чтоб настройки брандмауэра проверил.
