### ISSUE TITLE
https://www.macwelt.de - missed ad on page 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5680]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://www.macwelt.de/galerien/Die-iOS-Games-des-Jahres-2013-8367394.html?bild=1 - missed ad on page 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/23372054/28167613-d2e94988-67e4-11e7-978c-b5d530a1716a.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***
Application version: 1.2.1.71
Device: iPad
OS: 10.3.2
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.23.67 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.10 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.83 Enabled=YES
ID=6 Name="German filter" Version=1.0.35.27 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.52 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.88 Enabled=NO
ID=101 Name="EasyList" Version=1.0.73.43 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.63.78 Enabled=YES
ID=229 Name="I don't care about cookies" Version=1.0.0.13 Enabled=YES

Ticket ID: 1591766 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce.
