### ISSUE TITLE
HDSector.com - Popup

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardFilters#5681]
W10 x64
AGW 6.2.379.1984
FF 54.0.1 x64
Https filtering is enabled.
WFP driver

English & Spyware
Stealth,browsing Sec, parental control,extension - all disabled.

http://www.hdsector.com/
There are popups on the aforementioned site.

**Comment by AdamWr** [comment]
Fixed.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/5793
can't reproduce.

**Comment by The-Commissioner** [comment]
Third party script is causing it, the second one on the list:-

![1](http://i.imgur.com/v2dy61f.jpg)

**Comment by AdamWr** [comment]
It looks like a PopAds script - `http://tummiarunzpf.com/ues.js`
I was able to reproduce this only when I disabled this rule - `||popads.net/pop.js^$empty,important`
Do you have any other extensions or maybe you opened this website in private window?
Could you please check this rule?
`hdsector.com#%#Object.defineProperty(window, '_pop', { get: function() { return {}; } });`

**Comment by The-Commissioner** [comment]
@AdamWr 

`||popads.net/pop.js^$empty,important` - This rule is enabled in my Adguard.

I opened the site in normal browser window and not in a private one. Also there is no extension which should interfere with Adguard's working.

`hdsector.com#%#Object.defineProperty(window, '_pop', { get: function() { return {}; } });`  -  This rule fixes it for me.

**Comment by AdamWr** [comment]
Ok, added.
I really do not know why this rule `||popads.net/pop.js^$empty,important` does not work in this case at your end.
Thank you for your answer.
