### ISSUE TITLE
iTDMusic.com - Popup

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardFilters#5682]
W10 x64
AGW 6.2.379.1984
FF 54.0.1 x64
Https filtering is enabled.
WFP driver

English & Spyware
Stealth,browsing Sec, parental control,extension - all disabled.

http://www.itdmusic.com/
 There are popups on the aforementioned site.

**Comment by AdamWr** [comment]
Fixed.

**Comment by The-Commissioner** [comment]
@AdamWr Same issue on this site like the previous site, popunders/popups coming.

![1](http://i.imgur.com/MzlJRzm.jpg)

**Comment by AdamWr** [comment]
I think it is the same situation as here https://github.com/AdguardTeam/AdguardFilters/issues/5681
Could you please check this rule:
`itdmusic.com#%#Object.defineProperty(window, '_pop', { get: function() { return {}; } });`

**Comment by The-Commissioner** [comment]
@AdamWr That fixes it. DUnno why it's failing to block these popad scripts at my end, although I have the rule enabled. Maybe popads script made some changes at their end to circumvent the block.

Another issue : https://github.com/AdguardTeam/AdguardFilters/issues/5803

**Comment by AdamWr** [comment]
Added.
