### ISSUE TITLE
wetter.com (breakage)

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#56822]
`https://www.wetter.com/hd-live-webcams/deutschland/cologne-media-park/5977288734b55/`

[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: broken player because the site `usercentrics.eu` is blocked (AdGuard Annoyances)

***Steps to reproduce the problem***:

try to play the video

***System configuration***

**Filters:**
see https://github.com/ryanbr/fanboy-adblock/issues/1366

**Comment by BlazDT** [comment]
Fixed, you need to accept cookies in order to play the livecam. Currently do not have access to main device for auto-accept JS rule, please add one @AdamWr

**Comment by Morku** [comment]
@AdamWr 
Is the new rule meant for auto accept Cookie Pop-up? Because for myself, it doesn't. I have to accept manually.
Regards

**Comment by AdamWr** [comment]
This rule is not available yet.
Did you add it to user filter?

**Comment by Morku** [comment]
Oh damn, you are right. I was to quick. Thought 35 minutes is already a lot time.
Filter is working fine! I checked.
Sorry for the interruption :)

**Comment by AdamWr** [comment]
Ok, I'm glad that it works :)

**Comment by JobcenterTycoon** [comment]
hello i want to say i get breakage again:

`https://www.wetter.com/hd-live-webcams/deutschland/bu-sum-hauptstrand/5be95c70a5b4b9063e0b2112/`

livestream can’t load

**Comment by Alex-302** [comment]
@JobcenterTycoon please check with these rules
```
@@||api.usercentrics.eu/consent-templates/$domain=wetter.com
@@||api.usercentrics.eu/tcf2/*.json$domain=wetter.com
```
@AdamWr it seems your JS for cookie must be changed(I see another button `button[id="cmp-btn-accept"]`).

**Comment by JobcenterTycoon** [comment]
It works thanks

**Comment by AdamWr** [comment]
Ok, added these rules.
Thank you for your answer.

>@AdamWr it seems your JS for cookie must be changed(I see another button button[id="cmp-btn-accept"]).

This also should be fixed.
