### ISSUE TITLE
DJmaza.com - Popup

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardFilters#5683]
W10 x64
AGW 6.2.379.1984
FF 54.0.1 x64
Https filtering is enabled.
WFP driver

English & Spyware
Stealth,browsing Sec, parental control,extension - all disabled.

https://www.djmaza.life/

You may have to move in the site to receive popups

https://www.djmaza.life/butterfly-srk-full-song.html
https://www.djmaza.life/toilet-ek-prem-katha.html
https://www.djmaza.life/tseries-mixtape-full-songs.html
There are popups on the aforementioned site.

**Comment by AdamWr** [comment]
Fixed.
