### ISSUE TITLE
hltv.org - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5684]
***Site***: https://www.hltv.org/
***Description***: Ads.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28184599-4947358e-6814-11e7-94dc-c3772744c521.png)

![image](https://user-images.githubusercontent.com/10995998/28184616-59e0c39c-6814-11e7-92c3-f2040c44db17.png)

![image](https://user-images.githubusercontent.com/10995998/28184623-640c5bba-6814-11e7-8226-2d360c3cceb3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.62
Spyware filter | 1.0.13.26
Social media filter | 1.0.21.11
Annoyances filter | 1.0.15.42
German filter | 1.0.35.54

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr Ads are back again :(

**Comment by AdamWr** [comment]
Ok, fixed.
