### ISSUE TITLE
jkanime.co - Ad leftover - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5687]
***Site***: http://jkanime.co/Ver/73199/youkai-apartment-no-yuuga-na-nichijou-2017/episodio-2/
***Description***: Adblock detection (video can't be played). Ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28185100-56525112-6816-11e7-93c0-ed528b043d3e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.70
Spyware filter | 1.0.13.29
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.49
German filter | 1.0.35.56

**Comment by seanl-adg** [comment]
Fixed
