### ISSUE TITLE
baskino.co - Ad leftover - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5689]
http://baskino.co/new/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28191531-85347320-6839-11e7-991d-483af0bdc88c.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.1

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.24.59 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.26 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.11 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.15.41 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.53.91 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.91 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.52 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.83.66 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
 
Ticket ID:  1450398

**Comment by Alex-302** [comment]
На iOS отступ не убрать.
