### ISSUE TITLE
m.calcalist.co.il - Pop ups with ads - iOS

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5690]
https://m.calcalist.co.il/main.aspx

calcalist.co.il site shows blank white page while Adguard is enabled. Tried to enable filters one by one.
When our customer enabled only the English filter on the first load of the page it was blank. When reloading it, everything was ok. 

Not reproduced at my end. Only a bunch of ads on the website.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28192059-83c295b4-683c-11e7-8854-73e3a601ae25.png)

![image](https://user-images.githubusercontent.com/27292111/28192065-8a2cf4da-683c-11e7-9989-948224fde686.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 11.0

Optimazed enabled: NO

Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.24.25 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.19 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.98 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.15.19 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.88 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.52 Enabled=YES
ID=108 Name="EasyList Hebrew" Version=1.0.4.73 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.83.49 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES

Ticket ID:  1423882

**Comment by Alex-302** [comment]
Not reproduced.
