### ISSUE TITLE
currentaffairs.gktoday.in - Anti-Adblock Script

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#5691]
http://currentaffairs.gktoday.in/

![image](https://user-images.githubusercontent.com/22892774/28206653-660aaf36-688f-11e7-8e7a-d1dc4cea3615.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.331.1732
Adguard filters: | 1 2 4 5 14
Ticket ID: | 1354655

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
