### ISSUE TITLE
"Authorisation server not responding" on seasonvar.ru

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#5692]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/26434103/28207757-84a3535e-6893-11e7-8a07-fdf807a0bae8.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Register on seasonvar.ru and open "Меню - Настройки". Reproduced on our side.

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None
Adguard filters: | English, Russian, Annoyances, Spyware, Social media
Ticket ID: | 1531542

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||ulogin.ru/js/ulogin.js$domain=seasonvar.ru
```
