### ISSUE TITLE
http://kaztorka.org/ - Ad Leftover

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#5693]
![image](https://user-images.githubusercontent.com/22892774/28209862-312d6dae-689d-11e7-932f-3eed8881939d.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard filters: | 1 2 3 4 5 14
Ticket ID: | 637640

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
