### ISSUE TITLE
bild.de (breakage)

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#56944]
`https://www.bild.de/`

***Description***: Video player doesn't work
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="982" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/83971373-668c5b00-a8db-11ea-8ebd-0c04ea589208.PNG">

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

<img width="933" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/83971366-5d9b8980-a8db-11ea-9dbc-507af1883487.PNG">

</details><br/>

***Steps to reproduce the problem***: try to play a video 

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**
<img width="391" alt="settings" src="https://user-images.githubusercontent.com/48647394/83971496-b834e580-a8db-11ea-94e1-01a587aa684b.PNG">

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox 67.0.1
Adblocker:                       | uBlock Origin v1.27.10
Filters enabled:                       | see above

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

looks like the bad filter is `bild.de###outerWrapper ~ .cover` from Adguard Annoyances

**Comment by BlazDT** [comment]
Thank you, removed the rule. Update available in about 3 hours.
