### ISSUE TITLE
steamcustomizer.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5694]
***Site***: http://community.steamcustomizer.com/explore
***Description***: Adblock detection when scrolling down.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28216516-490d9e98-68b2-11e7-8ffd-f7175766141a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.76
Spyware filter | 1.0.13.30
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.59

**Comment by AdamWr** [comment]
Fixed.
