### ISSUE TITLE
hackinformer.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5695]
***Site***: https://hackinformer.com/
***Description***: Adblock detection. Site redirects to: https://hackinformer.com/?alobaidi_detect_adblock=true

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28216797-24cfef4e-68b3-11e7-965c-d072bf11e3d5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.76
Spyware filter | 1.0.13.30
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.59

**Comment by danidoedel** [comment]
`@@||hackinformer.com/wp-content/plugins/detect-adblock/js/ads.js`

**Comment by AdamWr** [comment]
Thank you.
Added.
