### ISSUE TITLE
satechi.net - Unblocked pop-up

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5696]
https://satechi.net/

***Description***:
* **Current behaviour**: 

Unable to block this pop-up. After clicking "Don't show this pop-up again" it apears again.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28215440-b15c837a-68b6-11e7-9488-c44301424908.png)

![image](https://user-images.githubusercontent.com/27292111/28217263-386d4fc4-68bd-11e7-9f94-cb0ae00f84ac.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPad
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.24.61 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.26 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.91 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.52 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.83.51 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.63.84 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.4.54 Enabled=YES
Annoyances filter=YES

Ticket ID: 1591874

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by danidoedel** [comment]
`satechi.net###popup-newsletter`

**Comment by AdamWr** [comment]
Added to Annoyances filter:
`satechi.net###popup-newsletter`
