### ISSUE TITLE
eurosport.de (Google AMP) - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5697]
***Site***: https://www.google.de/amp/www.eurosport.de/tennis/wimbledon/2017/wimbledon-2017-der-9.-turniertag-im-liveticker-mit-federer-djokovic-murray-raonic-berdych_sto6253056/story-amp.shtml
***Description***: Ad leftover at the end of the site.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28219765-681f7ac6-68bd-11e7-8de7-935cf7c58270.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.76
Spyware filter | 1.0.13.30
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.59
Mobile ads filter | 1.0.8.94
Safari filter | 1.0.3.52

**Comment by danidoedel** [comment]
```
www-eurosport-de.cdn.ampproject.org##.related-content-story--sponsored
www-eurosport-de.cdn.ampproject.org##.related-content-story--organic
```

**Comment by AdamWr** [comment]
Thank you.
Added.
