### ISSUE TITLE
Redirecting to other link on first touch on a webpage in google chrome

### ISSUE THREAD

**Issue by Avinsxkmbla** [AdguardTeam/AdguardFilters#56986]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ yes ] I am running the latest version
- [ yes ] I checked the documentation and found no answer
- [ yes ] I checked to make sure that this issue has not already been filed

### Issue Details

<On few webpages, on. First tap in google redirects to unknown link >

- **AdGuard version:**
  - <v3.5 nightly 2>
- **Filtering mode:**
  - <HTTP Proxy (auto) >
- **Device:**
  - <XIAOMI Redmi note 5 pro>
- **Operating system and version:**
  - <MIUI 11.0.3>
- **Root access:**
  - < No>

### Expected Behavior

< No ads to be displayed or no redirecting to unknown pages and block all ads and trackers >

### Actual Behavior

< On kissanime.si , all ads and pop ups were successfully blocked, but on certain times after the page is completely loaded, the first touch /input redirects to a link on a new tab >
 
Link of the webpage - 
< https://kissanime.nz/Anime/mob-psycho-100-2nd-season-dub.52611/Episode-012?id=156424>

Link of the redirected page -
< https://rybystalfracted.fun/?tid=756729&red=1&cs=T1EyWHN%2BZwNtSi1kUWAXeGNXOUN%2F&abt=0&v=1.34.13.1&sm=16&k=more%20high%20quality%20without%20downloading%20psycho%20season%20episode%20kissanime%20anime%20watch%20online%20free&sts=0&prn=0&emb=0&fs=1&ref=https%3A%2F%2Fkissanime.nz%2FAnime%2Fmob-psycho-100-2nd-season-dub.52611%2FEpisode-011%3Fid%3D156212&osr=kissanime.nz&jst=0&enr=0&lcua=mozilla%2F5.0%20(linux%3B%20android%209%3B%20redmi%20note%205%20pro)%20applewebkit%2F537.36%20(khtml%2C%20like%20gecko)%20chrome%2F83.0.4103.83%20mobile%20safari%2F537.36&tzd=5.5&uloc=&if=0&ct=3&ctc=7&_u6wU=1591348871608 >

**Comment by BlazDT** [comment]
Please list your filters. Does it also happen in VPN mode?

**Comment by Avinsxkmbla** [comment]
The filter which was being used is " Adguard simplified DNS " and the other one was "DNS user filter (which had no rules ) "

**Comment by Avinsxkmbla** [comment]
# These filters (only enabled) which I forgot to mention earlier :-
Ad blocking -
1) Adguard Base filter
2) Adguard Mobile ads filter
Privacy - 
1) Adguard tracking potential filter
Social - 
1) Adguard social media filter 
Annoyances -
1) Adguard annoyances filter

**Comment by Avinsxkmbla** [comment]
Good morning
I m sorry for explaining the things improperly,
I had few screenshots shots to share but couldn't do it in GitHub apk, as
it's my first time working on it,
I m attaching the screenshot if it could help u better

**Comment by Avinsxkmbla** [comment]
> Please list your filters. Does it also happen in VPN mode?

Yes, The it's was in Local VPN, while local HTTPS VPN is not available as my device is not rooted

**Comment by BlazDT** [comment]
Cannot reproduce. I was asking about local VPN as in initial post you wrote "HTTP Proxy (auto)".

HTTPS certificate is enabled? Else javascript rules cannot be applied.

Please check @AdguardTeam/filters-maintainers

**Comment by Avinsxkmbla** [comment]
I re-tried even now, even I m not able to reproduce it but at times, it
redirects to a another link .. everytime the application is closed the next
time when this happens, it takes to a different link. It might take time to
resolve this but I will keep posting the links which the page will redirect
to.

**Comment by Avinsxkmbla** [comment]
> I can't reproduce it either.
> Could you please update filters and check if you still can reproduce these popups?

I just updatedthe filters, next time this happens, I will report asap.

**Comment by AdamWr** [comment]
From what I can see, these popups was caused by "ad server" which has been blocked yesterday, so popups shouldn't appear now.
I added additional rule to block them, if they will change the "ad server".
Update should be available in 1-2 hours.
