### ISSUE TITLE
Obsolete/no-more-needed rules; dead domains in Japanese filter

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#57004]
### Probably obselote rules
- Base
```
9ketsuki.info#%#//scriptlet("prevent-bab")
audioreview.m1001.coreserver.jp,h5games.success-corp.co.jp#$#.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links { display: block !important; }
cowboy.blog.jp,halchim.jp#%#//scriptlet('abort-current-inline-script', 'document.addEventListener', '/google_ad_client/')
h5games.success-corp.co.jp,vidoza.net,yamareco.com#%#//scriptlet("prevent-fab-3.2.0")
shorten.sh#%#//scriptlet("prevent-setTimeout", "I8P.")
```

(Already in or covered by EasyList)
```
||d1qggq1at2gusn.cloudfront.net^
||fingahvf.top^
@@||foxnewsplayer-a.akamaihd.net/player/*/akamai/amp/prebid/*.js$domain=foxnews.com
extremetube.com##.noPopunder
```

- Tracking
(There's `||online-metrix.net^`)
`||online-metrix.net^$third-party`

### Dead domains in JP filter
```
adlantis.jp
ads.nikkeibp.co.jp
himarin.net
```

**Comment by Alex-302** [comment]
borh online-metrix.net are necessary

`@@||foxnewsplayer-a.akamaihd.net/player/*/akamai/amp/prebid/*.js$domain=foxnews.com`  I don't see it in Easylist

**Comment by Alex-302** [comment]
The first 5 rules will check later.

**Comment by Alex-302** [comment]
This is Easylist rule. It seems it fixes player.

**Comment by Alex-302** [comment]
Removed really unnecessary rules.

**Comment by Yuki2718** [comment]
> This is Easylist rule. It seems it fixes player.

Right, and when EL has it is `@@||foxnewsplayer-a.akamaihd.net/player/*/akamai/amp/prebid/*.js$domain=foxnews.com` in Base still needed? Anyway thx for double-checking.

**Comment by Alex-302** [comment]
Got it. Removed.
