### ISSUE TITLE
africam.com - Anti AdBlock Script

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5701]
***Description***:
* **Current behaviour**: 

There is an Anti AdBlock script on http://www.africam.com/wildlife/tembe_webcam on Windows.
Reproduced on our side

<details><summary>Screenshot:</summary>

![screen shot 2017-07-15 at 5 25 05 am](https://user-images.githubusercontent.com/28784344/28235796-4896fc0e-691e-11e7-804b-502ef30686e9.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | chrome
Adguard version: | 6.1.331.1732 
Adguard driver (Windows): | WFP 
Adguard DNS: | None 
Stealth mode options(Windows) | "BlockThirdPartyCookies": true,BlockThirdPartyCookiesPeriodMin": 30,  "BlockFirstPartyCookiesMin": 2880,  "BlockBrowserLocationApi": true, "RemoveXClientDataHeader": true,  "HideSearchQueries": true, "SendDoNotTrackHeader": true"
Adguard filters: | 1,2,6,7,0
Ticket ID (if exists): | 1592803

**Comment by danidoedel** [comment]
```
africam.com#%#!function(a,c,b){a&&(Promise=function(e){if('function'!=typeof e)throw new TypeError(e+' is not a function');for(var f=c.call(e),d=0,g=b.length;d<g;d++)if(b[d][0].test(f))return b[d][1]?a.reject(b[d][2]):a.resolve(b[d][2]);return new a(e)},Object.getOwnPropertyNames(a).forEach(function(b){Object.defineProperty(Promise,b,Object.getOwnPropertyDescriptor(a,b))}),a.prototype.constructor=Promise)}(window.Promise,Function.prototype.toString,[[/\.MozBinding\.indexOf\(["']abp-/],[/\.parentNode\.removeChild\([\s\S]*?\.removeEventListener\("error"[\s\S]*?\.createElement\([\s\S]*?\.getElementsByTagName\("head"/,,1],[/\.createElement\("iframe"[\s\S]*?URL\.createObjectURL\(new Blob\(\[""/],[/\.getPropertyValue\("display"\)[\s\S]*?\/tpc\.googlesyndication[\s\S]*?\.addEventListener\(["']message["']/,1]]);
```

**Comment by AdamWr** [comment]
Fixed.
