### ISSUE TITLE
mic.com - Social widgets - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5702]
***Site***: https://mic.com/articles/182184/report-donald-and-ivanka-trump-companies-use-law-firm-run-by-philippine-government-official#.I9dKhzXwU
***Description***: Various newsletter forms. Social share stuff. Incorrect blocked facebook icons etc. Newsletter overlay (you might have to click through the site a bit until it shows up).

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28238657-c53d4044-6958-11e7-8230-17b8316f4fa8.png)

![image](https://user-images.githubusercontent.com/10995998/28238661-d4fad74e-6958-11e7-85d6-0c3f12be9ba1.png)

![image](https://user-images.githubusercontent.com/10995998/28238663-e2fe29e0-6958-11e7-9a6f-5969f468e1b1.png)

![image](https://user-images.githubusercontent.com/10995998/28238666-f068a682-6958-11e7-8fa4-c93d6d3ad5a6.png)

![image](https://user-images.githubusercontent.com/10995998/28238671-fa3a47b0-6958-11e7-8d6e-cf623a326630.png)

![image](https://user-images.githubusercontent.com/10995998/28238672-03701f62-6959-11e7-98c9-e944af8fca2b.png)

![image](https://user-images.githubusercontent.com/10995998/28238678-11dda8b2-6959-11e7-98f0-1b51ff0c8337.png)

![image](https://user-images.githubusercontent.com/10995998/28238682-1e23df24-6959-11e7-9321-a748576fa7d8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.76
Spyware filter | 1.0.13.30
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.59

**Comment by danidoedel** [comment]
```
mic.com##.newsletter-signup
mic.com##.footer__newsletter
mic.com##.article-page__mobile-newsletter

mic.com#@#.social-icon
mic.com##.social-actions
mic.com##.article-page-share-buttons
```

Not sure how to properly block the overlay though...

**Comment by AdamWr** [comment]
Fixed.
