### ISSUE TITLE
techcrunch.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5703]
***Site***: https://techcrunch.com/2016/12/30/iran-has-banned-clash-of-clans-for-promoting-violence-and-tribal-conflict/
***Description***: Newsletter signup.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28238804-e60bd15c-695b-11e7-8258-5483cf83144a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.76
Spyware filter | 1.0.13.30
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.59

**Comment by danidoedel** [comment]
`techcrunch.com##.newsletters-signup`

**Comment by AdamWr** [comment]
Fixed.
