### ISSUE TITLE
clashofclans.com - Social widgets

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5704]
***Site***: https://clashofclans.com/blog/news/bh6-follow-up
***Description***: Missing social icons. Social share leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28238836-de47af44-695c-11e7-98ba-8603757dd2bc.png)

![image](https://user-images.githubusercontent.com/10995998/28238841-00c3bf54-695d-11e7-8dc4-13a2506b538d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.76
Spyware filter | 1.0.13.30
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.59

**Comment by danidoedel** [comment]
```
clashofclans.com#@#.icon-facebook
clashofclans.com#@#.icon-reddit
clashofclans.com#@#.icon-twitter
clashofclans.com##.BlogDetail-Footer-share
```

**Comment by AdamWr** [comment]
Added.
