### ISSUE TITLE
Not working for Crunchyroll on website with assistant enabled as well.

### ISSUE THREAD

**Issue by SHJordan** [AdguardTeam/AdguardFilters#57049]
### Steps to reproduce

1. go to https://www.crunchyroll.com/pt-br/a-destructive-god-sits-next-to-me/episode-2-eyes-on-me-792676
2. hit play
3. become angry
4. post issue

### Expected behavior

1. go to https://www.crunchyroll.com/pt-br/a-destructive-god-sits-next-to-me/episode-2-eyes-on-me-792676
2. hit play
3. enjoy 24 min of pure animation with no ads rather than 6 min of pure repetitive ads.
### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/884602/83898623-8e3dc080-a72d-11ea-97fe-42bc93c6521f.png)

</details>

### Your environment

* Environment name and version: Edge 83.0.478.44
* Operating system and version: Microsoft Windows [10.0.19635.1]

**Comment by BlazDT** [comment]
Ads were fixed about 3 hours ago, please update.

https://github.com/AdguardTeam/AdguardFilters/commit/dcc0f40dd296a133e1d2af5dadad1bf5169f2fc0
