### ISSUE TITLE
fuw.ch - Social widget - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5705]
***Site***: https://www.fuw.ch/article/volle-kraft-voraus-in-die-berichtssaison/
***Description***: Ad leftover at the top. Social bar on mobile device.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28239251-0f1c60b4-6968-11e7-8015-ab554f414453.png)

![image](https://user-images.githubusercontent.com/10995998/28239256-247d9a90-6968-11e7-83d1-7254b903677d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.83
Spyware filter | 1.0.13.30
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.60

**Comment by danidoedel** [comment]
```
fuw.ch##.ad
fuw.ch###js-icon-list
```

**Comment by AdamWr** [comment]
Fixed.
