### ISSUE TITLE
viz.com antiadblock

### ISSUE THREAD

**Issue by ghajini** [AdguardTeam/AdguardFilters#5706]
***Description***:
* **Current behaviour**: 

[//]: # there is antiadblock here

url=
`https://www.viz.com/watch/streaming/bleach-episode-366/4380/dub`

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](%
![chrome_2017-07-15_18-53-41](https://user-images.githubusercontent.com/20338483/28239775-1c816956-6991-11e7-982f-50439daefd3a.png)
%)
</details>

* **Expected behaviour**: 

[//]: #website should be visible without antiadblock

***Steps to reproduce the problem***:

[//]: # going here 
https://www.viz.com/watch/streaming/bleach-episode-366/4380/dub
triggers antiadblock

***also it detects vpn if trying to use***

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | chrome 59
Adguard version: | 2.6.7

[//]: # (***Filters list - default)

more info found here 
`https://github.com/jspenguin2017/uBlockProtector/issues/398`

**Comment by AdamWr** [comment]
@ghajini could you please check these rules:
`@@||viz.com^$generichide`
`viz.com#%#Object.defineProperty(window,'show_dfp_preroll',{value:false});`

**Comment by ghajini** [comment]
Sorry I can't check,iam geolocked.....site operable in usa only....when trying to use VPN, it ***detects VPN***

**Comment by AdamWr** [comment]
Fixed.

**Comment by ghajini** [comment]
hi sir @AdamWr 
i have to wait 30sec or more in order to start playback(much like unblocked preroll/midroll video ads)....
what i see is this?
![chrome_2017-09-15_23-01-03](https://user-images.githubusercontent.com/20338483/30495645-71b329aa-9a6a-11e7-90f6-cdc565c576aa.png)

**Comment by AdamWr** [comment]
Hi :)
Yes, I know.
It is fixed in Adguard for Windows, unfortunately Adguard Extension doesn't support all rules and in this case I don't know how to "fix" it in other way than allowing ads.
