### ISSUE TITLE
ran.de - Social widget - Annoyance - Ad leftover - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5707]
***Site***: http://www.ran.de/
***Description***: Ad leftover at the top. Whatsapp newsletter in sidebar. Facebook leftover in sidebar. Social share icons. Ads before video.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28240098-0edd44ac-697b-11e7-841e-bbbf3de28c9d.png)

![image](https://user-images.githubusercontent.com/10995998/28240142-fd9060ca-697b-11e7-841c-c871813110cc.png)

**http://www.ran.de/datenbank/fussball/pe144993/james-rodriguez/:**

![image](https://user-images.githubusercontent.com/10995998/28240161-592c29d2-697c-11e7-945e-bf7012121106.png)

![image](https://user-images.githubusercontent.com/10995998/28240163-60993516-697c-11e7-8486-d2f7cf21713f.png)

**http://www.ran.de/fussball/video/telekom-cup-highlights-bremen-erster-finalist-dank-kruse-clip (Ads before video):**

![image](https://user-images.githubusercontent.com/10995998/28240174-87a4f67c-697c-11e7-8f1e-ac0b00d83d79.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.83
Spyware filter | 1.0.13.30
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.60

**Comment by AdamWr** [comment]
Fixed.
