### ISSUE TITLE
netzpolitik.org - Social widgets

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5708]
***Site***: https://netzpolitik.org/2017/interview-mit-frank-pasquale-wie-facebook-und-google-die-digitale-oeffentlichkeit-dominieren/
***Description***: Share icon leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28240211-36a33148-697d-11e7-9c41-063905965830.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.83
Spyware filter | 1.0.13.30
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.60

**Comment by danidoedel** [comment]
`netzpolitik.org###share`

**Comment by AdamWr** [comment]
Added.
