### ISSUE TITLE
statsroyale.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5710]
***Site***: https://statsroyale.com/
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28240270-f9474328-697e-11e7-82eb-42215958e418.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.83
Spyware filter | 1.0.13.30
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.60

**Comment by AdamWr** [comment]
Fixed.
