### ISSUE TITLE
/m.txxx.com - Ad Letfover -iOS

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5711]
***Description***:
* **Current behavior**: 

Missed ad on a porn website: 
http://m.txxx.com/videos/3156069/hottest-pornstar-in-exotic-redhead-cunnilingus-porn-scene/
reproduced on our side (Windows)

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3.1
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.24.81 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.30 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.16 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.52 Enabled=YES
ID=214 Name="ABPVN List" Version=1.0.4.17 Enabled=YES
Ticket ID: 1593404

**Comment by Alex-302** [comment]
Fixed
