### ISSUE TITLE
www.obozrevatel.com - Social widgets - iOS

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5712]
***Description***:
* **Current behavior**: 
Social widgets on https://www.obozrevatel.com/life/people/72593-smert-dzhanni-versache-chto-izvestno-o-zagadochnom-ubijstve-kultovogo-kutyure.htm
 reproduced on our side (Windows)

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.24.25 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.19 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.98 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.15.19 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.53.72 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.88 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.52 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.83.33 Enabled=YES

Ticket ID:1518078

**Comment by Alex-302** [comment]
Fixed
