### ISSUE TITLE
http://ruero.com - Pop-up

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5713]
***Description***:
* **Current behaviour**: 

http://ruero.com - Pop-up from HELLO BAR
reproduced on our side (windows)
since the user hasn`t provided us with his/her system info - I will describe ours
***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | chrome
Adguard version: | 6.1.314.1628
Adguard driver (Windows): | tdi
Adguard DNS: | None 
Adguard filters: | 1,2,3,4,0,11,14
Ticket ID (if exists): | 1593432

**Comment by Alex-302** [comment]
Fixed.
