### ISSUE TITLE
digital-photography-school.com - Social widgets

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5714]
***Site***: https://digital-photography-school.com/3-reasons-to-keep-your-old-photoshop-version/
***Description***: Social bar leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28243551-c85c0c1c-69ce-11e7-8f3a-7b24ac7491de.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.83
Spyware filter | 1.0.13.30
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.60

**Comment by danidoedel** [comment]
`digital-photography-school.com##.share-bar`

**Comment by AdamWr** [comment]
Added.
