### ISSUE TITLE
praxistipps.chip.de (Google AMP) - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5716]
***Site***: https://www.google.de/amp/praxistipps.chip.de/microsoft-edge-werbung-blockieren-so-klappts_42804%3Flayout%3Damp
***Description***: App banner at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28246519-16a6ac54-6a1c-11e7-8a9f-e5e6ef521eab.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.93
Spyware filter | 1.0.13.32
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.62
Mobile ads filter | 1.0.8.98
Safari filter | 1.0.3.53

**Comment by danidoedel** [comment]
`praxistipps-chip-de.cdn.ampproject.org###chip-app-banner`

**Comment by AdamWr** [comment]
Fixed.
