### ISSUE TITLE
New type of youtube ads?

### ISSUE THREAD

**Issue by ScienceDiscoverer** [AdguardTeam/AdguardFilters#57176]
### Steps to reproduce

1. You should be able to see this new ad on any monetized video.
2. It appears at the start of video and blocks video from playing until skipped or auto-skipped after few seconds.

### Expected behavior
AdGuard should prevent this ad from blocking video. I suspect that JavaScript could be involved here...

### Actual behavior
It looks like some text on white background with image inside it.
It could be skipped but it is extremely annoying because appears almost on every video I load.

<details><summary>Screenshot:</summary>
Ad looks like this.
There is timer in the bottom left corner that indicates autoskip.

I snapshoted some source code states for this ad:
![Знімок екрана 2020-06-09 22 32 43](https://user-images.githubusercontent.com/29157485/84197293-5bd3f080-aaaa-11ea-806c-453006c68da8.png)

Then I tried to add custom rules to AdGuard like www.youtube.com##.video-ads
www.youtube.com##.ytp-ad-module. However this just hid ad itself, video underneath him showed playback error: An error occurred, please try again later. (Playback ID:....) until ad skips itself after a few seconds...
![Знімок екрана 2020-06-09 22 51 06](https://user-images.githubusercontent.com/29157485/84197457-9f2e5f00-aaaa-11ea-9c7e-799c8a4a341a.png)
Also here you can see that video has classes:  ad-interrupting playing-mode unstarted-mode
So, youtube actually blocks video from playing completely until ad is skipped...

Is this known ad and there is some problem on my end, or AdBlock just can't block ads like this for now? And is it possible to block it in the future?

</details>

### Your environment

* Environment name and version: Firefox 77.0.1
* Operating system and version: Windows 10 1909 build 18363.418

**Comment by gitguys** [comment]
Same problem with YouTube in Adguard for Mac.

Ad loads up with blank white window and I have to click skip to get past it.

**Comment by Alex-302** [comment]
Known issue. They are still testing it. We wait when it will be shown on our end.

**Comment by Alex-302** [comment]
Could you please provide few links with these ads?

**Comment by Alex-302** [comment]
> I suspect that JavaScript could be involved here...

Yep. This is only one way to fix it(also we  can patch JS and html by `$replace` rules)

**Comment by strafe** [comment]
@Alex-302 is there any news or another thread to follow on this? Just curious what the situation is at the moment

**Comment by Alex-302** [comment]
No. Every day I am trying to catch these ads. It seems they still testing them.
*Duplicate*

**Comment by ScienceDiscoverer** [comment]
I assume this ads was finally removed, but update is not rolled out yet? Last update was 04.06 for me.

**Comment by Alex-302** [comment]
@ScienceDiscoverer I cannot even reproduce this ad.
You can try to test with `Experimental Filter`.

**Comment by ScienceDiscoverer** [comment]
@Alex-302 I can confirm that experimental filter works perfectly! No more of this annoying ads. IDK what you did there, but seems to work, for now. To be sure, I disabled this filter again and tried to load few videos. And yep, ads where back. So it's not like Youtube stopped targeting me with them.

If you can't reproduce them, this probably means that Youtube don't target everybody with this adds, but gradually adds new people.

**Comment by gitguys** [comment]
> @Alex-302 I can confirm that experimental filter works perfectly! No more of this annoying ads. IDK what you did there, but seems to work, for now. To be sure, I disabled this filter again and tried to load few videos. And yep, ads where back. So it's not like Youtube stopped targeting me with them.
> 
> If you can't reproduce them, this probably means that Youtube don't target everybody with this adds, but gradually adds new people.

 The experimental filter worked for me as well in Safari for aw while but the white screen with skip button came back again yesterday.  Is it still working for you?

![85480780-cc384280-b57d-11ea-978d-507240444c48](https://user-images.githubusercontent.com/11050768/85624914-e4649c00-b627-11ea-835e-4c478475be85.png)

**Comment by ScienceDiscoverer** [comment]
> The experimental filter worked for me as well in Safari for maybe about a week but the white screen with skip button came back again yesterday. Is it still working for you?

Yes, it seems to still work fine. Maybe youtube is testing new tactics on you?
