### ISSUE TITLE
clashroyaleforum.de - Social widgets - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5719]
***Site***: https://clashroyaleforum.de/
***Description***: Ad leftover. Cookie notice at the bottom. Ad post in forums. Social share buttons at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28246715-b02e07a6-6a20-11e7-9a16-4308996ec295.png)

![image](https://user-images.githubusercontent.com/10995998/28246720-c1a30784-6a20-11e7-938c-1552db78bb72.png)

**https://clashroyaleforum.de/thread/3211-eure-hasskarte/:**

![image](https://user-images.githubusercontent.com/10995998/28246724-d5872adc-6a20-11e7-9e22-4214f81c9241.png)

![image](https://user-images.githubusercontent.com/10995998/28246727-f26adcf2-6a20-11e7-93dc-17c7fa230f8f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.93
Spyware filter | 1.0.13.32
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.62

**Comment by AdamWr** [comment]
Fixed.
