### ISSUE TITLE
[android] Adguard incompatibility with MX Player

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/AdguardFilters#572]
http://forum.xda-developers.com/showpost.php?p=60970537&postcount=102
http://forum.xda-developers.com/showpost.php?p=60971495&postcount=104

**Comment by Alex-302** [comment]
не пойму при каких условиях глючит у него - при проигрывании видео в МХ из интернетов? С ютубом в браузере вроде всё норм, но воспроизведение не передаётся в МХ Плеер.

**Comment by adguard** [comment]
Он говорит что с перемоткой проблемы в MX с других сайтов
