### ISSUE TITLE
androidpit.de - Annoyance - Social widgets

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5721]
***Site***: https://www.androidpit.de/
***Description***: Newsletter box. Facebook share stuff.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28246788-6017f57c-6a22-11e7-8955-a8146f2bd74a.png)

**https://www.androidpit.de/lenovo-im-interview-von-moto-zu-motorola:**

![image](https://user-images.githubusercontent.com/10995998/28246789-66710e9a-6a22-11e7-8965-3f8571caa964.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.93
Spyware filter | 1.0.13.32
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.62

**Comment by danidoedel** [comment]
```
androidpit.de##.tile_newsletterSubscription
androidpit.de###sticky-share-bar
androidpit.de##.articleSocial
```

**Comment by AdamWr** [comment]
Added:
```
androidpit.com,androidpit.com.br,androidpit.de,androidpit.es,androidpit.fr,androidpit.it##.tile_newsletterSubscription
androidpit.com,androidpit.com.br,androidpit.de,androidpit.es,androidpit.fr,androidpit.it##.sticky-share-bar
androidpit.com,androidpit.com.br,androidpit.de,androidpit.es,androidpit.fr,androidpit.it##.articleSocial
||tracking-opi.fonpit.de/tracking/
@@||google-analytics.com/analytics.js$domain=androidpit.com|androidpit.com.br|androidpit.de|androidpit.es|androidpit.fr|androidpit.it
@@||google-analytics.com/plugins/ua/linkid.js$domain=androidpit.com|androidpit.com.br|androidpit.de|androidpit.es|androidpit.fr|androidpit.it
```
The two last rules was added, becuase website was empty/grey for few seconds, similar issue was here - https://forum.adguard.com/index.php?threads/resolved-piriform-com.23539/
