### ISSUE TITLE
pcgamer.com - Social widgets

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5722]
***Site***: http://www.pcgamer.com/we-asked-for-your-best-stories-about-scamming-and-wow-youre-bad-people/
***Description***: Social widget leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28248642-179456b2-6a48-11e7-8393-b32d86abc637.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.93
Spyware filter | 1.0.13.32
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.62

**Comment by danidoedel** [comment]
`pcgamer.com##.socialite-widget`

**Comment by AdamWr** [comment]
Added.
