### ISSUE TITLE
http://endlessflix.co.uk/ - anti adblock

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#5723]
Hey
have anti adblock in site: http://endlessflix.co.uk/
Operating system: Windows 10 x64
Screenshot: http://prntscr.com/fwebs4
Browser: Chrome
Adguard version: 6.1.331.1732

filter:
English filter
Annoyances filter
EasyLIstHebrew
adblock warning removal list
adblock protector list

**Comment by AdamWr** [comment]
Fixed.
