### ISSUE TITLE
https://www.sadeempc.com

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#5724]
Hey
have anti Popup in site: https://www.sadeempc.com
Operating system: Windows 10 x64
Screenshot: http://prntscr.com/fwebs4
Browser: Chrome
Adguard version: 6.1.331.1732

filter:
English filter
Annoyances filter
EasyLIstHebrew
adblock warning removal list
adblock protector list

**Comment by Alex-302** [comment]
Not reproduced.
Added to English filter
```
||sadeemapk.com/wp-content/uploads/2016/06/SadeemAPK-Banner.gif
||sadeempc.com/wp-content/uploads/*-468-
sadeempc.com##center > a[onclick][rel="nofollow"]
sadeempc.com##center > div[style="text-align:center;"] > img
```
Added to Spyware filter
```
||doomna.com^$third-party

```

**Comment by Alex-302** [comment]
@AdamWr please check on your side.

**Comment by AdamWr** [comment]
@Alex-302 I can not reproduce.

**Comment by Alex-302** [comment]
Ok then.
