### ISSUE TITLE
Adguard settings reset in Firefox after closing

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardFilters#57268]
Hi there,

I have Adguard addon in Firefox browser. It used to be working just fine until recently, but since Firefox update to version 77 or so something strange is happening. Every time I close Firefox all Adguard settings are gone, so at next startup of Firefox Adguard shows that it is loading something (see 1st picture below), it never showed something like this before. But once I go Adguard Options, all the settings are reset by their default values, all filters are gone, so I have to set it up all over again, which is a bit of pain.. So I wonder if this can be fixed any time soon..

Operating system: Windows 10 Home
Browser: Firefox 77.0.1 (64-bit)
AdGuard version for Firefox: Version 3.4.31
Filters enabled: AdGuard Base filter, AdGuard Tracking Protection filter, EasyPrivacy, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter
Stealth mode options (Windows only) Enabled
![111](https://user-images.githubusercontent.com/23212486/84536843-55868400-acf7-11ea-9c19-ededddd4cd2f.jpg)
![222](https://user-images.githubusercontent.com/23212486/84536845-56b7b100-acf7-11ea-8d94-894948c50979.jpg)
![333](https://user-images.githubusercontent.com/23212486/84536847-56b7b100-acf7-11ea-863f-cf7f057dc148.jpg)
![444](https://user-images.githubusercontent.com/23212486/84536848-57e8de00-acf7-11ea-8bdb-062106ce752c.jpg)

**Comment by BlazDT** [comment]
@TheHasagi @Chinaski1

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardBrowserExtension #1646](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1646) via [**ZenHub**](https://www.zenhub.com/)
