### ISSUE TITLE
[NSFW] ksidhsiy942erk3.fun

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#57261]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

URL: `https://ksidhsiy942erk3.fun/kjasdjhqwud.php`

Scam site, after several clicks you'll be threatened to pay 250,000 JPY.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![ksidhsiy942erk3-2](https://user-images.githubusercontent.com/58900598/84528028-dd7d8580-ad19-11ea-887e-be978acf6c58.png)

</details><br/>

* **Expected behaviour**: 

Blocked by Browsing security

***Steps to reproduce the problem***:

Click on sth looks player, if the same page is loaded with # attached repeat the same step. Possibly you get another page before the first SS page (I thought at first I got, not on the second trial) then just click something.

<details><summary>Screenshot:</summary>

![ksidhsiy942erk3-1](https://user-images.githubusercontent.com/58900598/84528455-ae1b4880-ad1a-11ea-80f4-e360b9c8f8a2.png)

</details><br/>

***System configuration***

**Filters:**

Base, Tracking, & Japanese

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |Windows 10
Browser:                               | Firefox 77.0.1
AdGuard version:                       |3.4.31
Simplified
AdGuard DNS:                           | None
Stealth mode options (Windows only)    |Enabled - default

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Yuki2718** [comment]
@Chinaski1

**Comment by krystian3w** [comment]
What help `Chinaski1` if you not use DNS od AdGuard Home.

**Comment by Yuki2718** [comment]
Browsing security. It's independent from contents filtering, no need to use AG DNS.

**Comment by krystian3w** [comment]
Not enough people turn on additional protection (malware/phishing protetection), AdGuard has it turned off by default.

**Comment by Yuki2718** [comment]
Probably so, but those who turned on should be protected from scam sites. IDK why it's turned off by default.

**Comment by Chinaski1** [comment]
Blacklisted!
