### ISSUE TITLE
izbavsa.ru + stop-klopam.ru - Ads - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5726]
***Description***:
* **Current behaviour**: 

There ads on:
http://izbavsa.ru/ogorod/kak-navsegda-izbavitsya-muravev-ogorode
http://stop-klopam.ru/muravi/kak-izbavitsya-ot-muravev-pri-pomoshchi-bornoi-kisloty
Reproduced on our side
<details><summary>Screenshot1:</summary>

![screen shot 2017-07-17 at 1 02 10 am](https://user-images.githubusercontent.com/28784344/28251711-afc3c0a6-6a8b-11e7-9d97-cf9e0b45f566.png)

</details>

<details><summary>Screenshot2:</summary>

![screen shot 2017-07-17 at 1 01 57 am](https://user-images.githubusercontent.com/28784344/28251710-aa48946c-6a8b-11e7-98ff-c195704d49a3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | TDI
Adguard filters: | 0,1,2,3,4,14,101,118,123,122,115
Ticket ID (if exists): | 1498653

**Comment by Alex-302** [comment]
Fixed.
