### ISSUE TITLE
manager.co.th - missed ad on page 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5727]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: manager.co.th - missed ad on page 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/23372054/28255567-4a8d9a50-6ac1-11e7-8048-cc2b4ede4473.png)

</details>

***System configuration***
Application version: 1.2.1.71
Device: iPad
OS: 10.3.2
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.24.84 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.30 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.16 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.15.51 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.96 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.52 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.95 Enabled=NO
Ticket ID 1593858

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't open this site. @seanl-adg could you please check it?
