### ISSUE TITLE
http://m.biqugeg.com - missed ad on page 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5728]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://m.biqugeg.com/wapbook/15595_15602295.html - missed ad on page 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/23372054/28259940-75749960-6ae1-11e7-9fa6-11e7de5308e8.png)

</details>

***System configuration***
Application version: 1.2.1.71
Platform: iOS
OS: 10.3.2
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.23.53 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.13.32 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.16 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.15.51 Enabled=YES
ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.9 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.65 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.98 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.95 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.84.1 Enabled=YES

Ticket ID: 1593788

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
||s.gg0376.com^$third-party
```
