### ISSUE TITLE
wikipedia.org - Ad leftover/Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5729]
***Site***: https://de.wikipedia.org/wiki/Schweizer_System
***Description***: Ad leftover or annoyance or whatever that is...

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28266087-601dee06-6af3-11e7-9e3d-c92a37e84234.png)

**Without Adguard:**

![image](https://user-images.githubusercontent.com/10995998/28266151-a3be2130-6af3-11e7-9324-71cec62fd8db.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.93
Spyware filter | 1.0.13.32
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.62

**Comment by AdamWr** [comment]
I can't reproduce.
Could you please check this again?

**Comment by danidoedel** [comment]
@AdamWr Can't reproduce it anymore as well. I think that banner was just temporarily, but something similar might come back at some point.
I saved two HARs (without Adguard and with Adguard enabled) maybe that helps:

[HAR.zip](https://github.com/AdguardTeam/AdguardFilters/files/1180162/HAR.zip)
