### ISSUE TITLE
bilan.ch - Social widgets - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5730]
***Site***: http://www.bilan.ch/economie/salaires-cadres-hausse-de-11-moyenne-cette-annee
***Description***: Social share leftover. Newsletter box.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28271569-2e668a42-6b09-11e7-8bdf-d7b87e4111fb.png)

![image](https://user-images.githubusercontent.com/10995998/28271544-20991c18-6b09-11e7-95b6-cfa41ae9fa1e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.24.93
Spyware filter | 1.0.13.32
Social media filter | 1.0.21.16
Annoyances filter | 1.0.15.51
German filter | 1.0.35.62

**Comment by AdamWr** [comment]
Fixed.
