### ISSUE TITLE
https://www.gazeta.ru/ - yandex direct

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5732]
https://www.gazeta.ru/auto/news/2017/07/17/n_10312688.shtml

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28302751-f0c47afc-6b97-11e7-94e0-b96204c96b9f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: |   IE 11
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | below
Adguard filters: | 1 2 3 4
Ticket ID: | 1527855

- "BlockThirdPartyCookies": true,
-   "BlockThirdPartyCookiesPeriodMin": 30,
-   "BlockFirstPartyCookies": false,
-   "BlockFirstPartyCookiesMin": 2880,
-   "DisableThirdPartyCache": false,
-   "BlockWebRtc": false,
-   "BlockBrowserPushApi": false,
-   "BlockBrowserLocationApi": true,
-   "RemoveXClientDataHeader": true,
-   "HideSearchQueries": true,
-   "SendDoNotTrackHeader": true,
-   "RemoveRefererFromThirdPartyRequests": false,
-   "HideUserAgent": false,
-   "CustomUserAgent": null,
-   "CustomReferer": null,
-   "HideIp": false,
-   "CustomIp": "209.141.53.254"
- 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
не повторется вообще, делали - все.

**Comment by Alex-302** [comment]
@evgeniy-ADG а с 6.1 проверяли?

**Comment by Alex-302** [comment]
Ну что там?

**Comment by evgeniy-ADG** [comment]
Только что проверили на 6.1 и 6.2 в IE - все чисто у нас.

**Comment by Alex-302** [comment]
Ок.
