### ISSUE TITLE
Counter-Strike Source app - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5733]
В программе Counter-Strike Source при входе в окошке написано, что надо добавить в
AdGuard исключение для: motd.motdgd.com; Заблокировано правилом фильтрации: .com/ads?$popup

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28303018-7ef2f762-6b99-11e7-80f1-ac9d2f812475.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows NT 10.0.15063.0
Browser: | -
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | 
Adguard filters: | 1 2 3 4 8 10
Ticket ID: | 1591723

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Нужно описание. Что там без блокировки? Попроси открыть журнал, отметить `Blocked` и повторить проблему.

**Comment by Alex-302** [comment]
На проверку:
```
@@||motd.motdgd.com^$app=hl.exe
```
hl.exe - исполняемый файл. Может быть другим.

**Comment by Alex-302** [comment]
Есть новости?

**Comment by Alex-302** [comment]
Ещё такое можно проверить
```
@@||motd.motdgd.com^
```

**Comment by ypetruk** [comment]
Ответ: "Да я вообще не пробовал что-то делать с вашей программой, Фильтр был пуст, я
попытался ввести эту информацию @@||motd.motdgd.com^$app=hl.exe
И вышла ошибка, тогда я ввел с полным путем к файлу и ничего не произошло"

**Comment by Alex-302** [comment]
А предыдущий мой комментарий передали?

**Comment by evgeniy-ADG** [comment]
да, все передавали. ответа пока нет.

**Comment by Alex-302** [comment]
Молчит?

**Comment by ypetruk** [comment]
@Alex-302 еще раз спросила, ждем ответа
