### ISSUE TITLE
blocking ads on youtube.com - question

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5734]
> Передайте пожалуйста разработчикам, что блокировать на ютуб финальные заставки не стоит. Это не аннотации, что раздражали раньше. Это полезные кнопки для перехода, которые можно добавлять в видео только в самом конце. Раньше их не блокировало.
> 
> Недавно заметил это, думал, что блогер не добавляет их и было неудобно - переходы на нужные видео, которые он добавляет не видно.
> 
> https://www.youtube.com/watch?v=Suwg2w-fzsc пример
> https://yadi.sk/i/igoB81JD3L92BU - вот о чем я говорю.
> 
> Они нужны. А вот при паузе список который ютуб добавляет теперь снизу - раздражает, т.к. перекрывает часть видео, а паузу обычно ставят, чтобы лучше что-то разглядеть, а эта часть мешает. К сожалению скрин не могу сделать, т.к. не понимаю когда это происходит. Вчера постоянно было, сегодня нет. Возможно это на определенных видео.

ID: 1099770

**Comment by Alex-302** [comment]
Все аннотации с одного адреса загружаются.
Передай на пробу:
```
youtube.com#@#.video-annotations
youtube.com#@#.ytp-ce-element
@@||youtube.com/annotations_invideo?$object-subrequest
```

**Comment by evgeniy-ADG** [comment]
передал.

**Comment by evgeniy-ADG** [comment]
> Спасибо, помогло.
> 
> Передайте разработчикам, что ютуб
> запретил встраивать старые аннотации,
> что мешали раньше. Теперь у них с мая
> только конечные заставки возможны.
> Вероятно, блокировать смысла их
> больше нет.

**Comment by Alex-302** [comment]
Ок, внёс изменения. Через час-полтора можно будет проверять.

**Comment by a-ladanov** [comment]
Ах, вот почему на ютубе все повылазило...
Спорить не хочется, устал уже. Подобная история случается регулярно, то удаляем, то возвращаем.
Повылазили логотипы каналов, и вот такие подобные аннотации "подписувайся"...
На мой взгляд это и есть раздражители, и такое нужно блокировать.
Но спорные ситуации возникают постоянно, поэтому нужно что-то придумывать. Может сделать отдельную подписку для аннотаций?
![default](https://user-images.githubusercontent.com/18179397/28611505-6eb17992-7205-11e7-8514-d4e770c84dbb.png)
![2](https://user-images.githubusercontent.com/18179397/28611506-6f8a6bc6-7205-11e7-9200-867a585a2bd6.png)

**Comment by a-ladanov** [comment]
![3](https://user-images.githubusercontent.com/18179397/28611663-00c4dd1a-7206-11e7-933b-cbc25dfda3fe.png)

**Comment by Alex-302** [comment]
@a-ladanov 
дайте ссылки, где вылазит.

> Может сделать отдельную подписку для аннотаций?

она есть
https://youtube.adblockplus.me/

**Comment by a-ladanov** [comment]
Логотип и инфо: https://www.youtube.com/watch?v=XbGs_qK2PQA
"подписувайся": https://www.youtube.com/watch?v=ffH-j_oIMeE
Логотип: https://www.youtube.com/watch?v=CxXADkHLWK4

Кстати по подписке выше никаких аннотаций нет, но о чем говорил топикстартер - остается. Довольно неплохо. Возможно и вам следует немножко изменить правила, чтобы что-то оставалось.

**Comment by Alex-302** [comment]
Повторился только логотив в правом нижнем углу
```
youtube.com##.annotation.iv-branding
```

**Comment by a-ladanov** [comment]
"подписувайся" с 47 секунды...
Инфо в правом верхнем углу
![2](https://user-images.githubusercontent.com/18179397/28620423-4d4eab6e-7226-11e7-9b8a-8c667cb82b60.png)

**Comment by Alex-302** [comment]
> "подписувайся" с 47 секунды появляется...

не появляется.

> Инфо в правом верхнем углу

она отображается только при наведении курсора.
