### ISSUE TITLE
Podcast Addict: In-app ads

### ISSUE THREAD

**Issue by dcptcon** [AdguardTeam/AdguardFilters#57346]
Podcast Additct In-app ads are not blocked

*Adguard v3.4 (120)
*Adguard filters are updated 
*User rules are disabled

Package name: com.bambuna.podcastaddict
Uid: 10241
App type: User
Version: 2020.8.2 (20194)
Target SDK: 28
First install time: 6/13/20 12:18 PM
Last update time: 6/13/20 12:18 PM

**Comment by BlazDT** [comment]
Please follow guidelines, thank you.

**Comment by Alex-302** [comment]
@dcptcon Please add screenshot at least.

**Comment by dcptcon** [comment]
> @dcptcon Please add screenshot at least.
I reported the issue directly from the adguard app and ended up here because the submission process requires the web address the non-blocked ad is being displayed on. However this non-blocked ad appears within an application as described in my original report.
If users are to "follow the guidelines" a recommendation could be made for adjusting the adguard In-app reporting so it can account for ads appearing within an app for which getting the web address is not an option.
The time it took to post the first two comments could have easily been spent installing the app in question and seeing the issue first hand.

**Comment by zero77** [comment]
Possibly related: https://github.com/AdguardTeam/AdguardFilters/issues/80414
