### ISSUE TITLE
naver gestures issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5735]
One problem is here. It seems an important matter for Korean user. 

1. Naver (like Google in Korea) webtoon is very popular in Korea. 
2. Gesture extensions (Pig toolbox and others) in Chrome don't work on the
webtoon page of Naver (http://comic.naver.com/index.nhn). 
3. The corresponding filters are shown below. 

```
comic.naver.com,ptware.net#%#AG_onLoad( function() { (function(w){ var
arr =
['contextmenu','copy','cut','paste','mousedown','mouseup','beforeunload','beforeprint','dragstart','selectstart']; for(var i = 0, x; x = arr[i]; i++){ if(w['on' + x])w['on' + x] = null;
w.addEventListener(x, function(e){e.stopPropagation()}, true); };
for(var j = 0, f; f = w.frames[j]; j++){try{arguments.callee(f)}catch(e){}}})(window); } ); 
```

If deactivating this line in List-KR, gesture works fine.

***System configuration***

Information | value
--- | ---
Operating system: | Windows NT 10.0.15063.0
Browser: | 
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
Adguard filters: |   List-KR
Ticket ID (if exists): | 1593959

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
This is a compatibility issue with a JS rule and a third-party browser extension, we have nothing to do with it.
