### ISSUE TITLE
I cannot acess the website, when Adguard filters on

### ISSUE THREAD

**Issue by vicphos** [AdguardTeam/AdguardFilters#57379]
https://ue.flipboard.com/usage?data=%7B"prod_type"%3A"notification"%2C"event_category"%3A"email"%2C"event_action"%3A"click"%2C"event_data"%3A%7B"type"%3A""%2C"target_id"%3A""%2C"url"%3A"http%3A%2F%2Fit.chosun.com%2Fsite%2Fdata%2Fhtml_dir%2F2020%2F06%2F14%2F2020061401660.html"%2C"method"%3A"externalweb"%2C"redirect_url"%3A"http%3A%2F%2Fit.chosun.com%2Fsite%2Fdata%2Fhtml_dir%2F2020%2F06%2F14%2F2020061401660.html%3Futm_medium%3D%26utm_source%3Dbixby%26utm_content%3D%26utm_campaign%3D"%7D%2C"properties"%3A%7B"uid"%3A"0"%2C"unique_id"%3A"0"%2C"time"%3A1592131575957%2C"ab_tests"%3A""%7D%7D

**Comment by Alex-302** [comment]
@vicphos Hi. Which AdGuard and filters are you using?

**Comment by vicphos** [comment]
Im using under list 😃
Adguard base filter
Adguarf Mobile ads filter

[Privacy]
Adguard  Tracking Protection filter
Easy Privacy

Adguard Social media filter

Adguard Annoyances filter

Litst KR
Easylist china


Adguard Simplified domain names filter
Adguard Experimental filter

**Comment by Alex-302** [comment]
> Which AdGuard?

Please test with disabled Easy Privacy

**Comment by vicphos** [comment]
It didn't works, same 😓
- Android 10, Galaxy note 9

**Comment by Alex-302** [comment]
Ok, please try to disable filters one by one.

**Comment by Alex-302** [comment]
It seems caused by `Adguard Simplified domain names filter` + DNS filtering(or AdGuard DNS)

**Comment by vicphos** [comment]
Oh thanks! It solved. This caused by Adguard DNS
