### ISSUE TITLE
cbsnews.com - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5737]
***Site***: http://www.cbsnews.com/live/
***Description***: Incorrect blocking. Timeline on the left incomplete. Logo below video missing. Social share icons leftover. Follow icons on the right should be unblocked.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28314076-751f1cf0-6bb9-11e7-8bbf-f78ae50e016a.png)

**That's how it should look like:**

![image](https://user-images.githubusercontent.com/10995998/28314057-65cde556-6bb9-11e7-8446-3dd1483d1310.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.25.15
Spyware filter | 1.0.13.34
Social media filter | 1.0.21.20
Annoyances filter | 1.0.15.60
German filter | 1.0.35.67

**Comment by AdamWr** [comment]
Fixed.
