### ISSUE TITLE
Блокировка элемента

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#57375]
Здравствуйте,
Есть ли возможность заблокировать объект (всё поле наград целиком (НЕ только кнопу, но и ВСЕ поле наград)) (выделенный на скриншоте) на всех фиках? Если да, то что для этого нужно сделать? Возможно ли решить эту проблему методом пользовательского фильтра?
Заранее спасибо!

![Screenshot_20200614-122257](https://user-images.githubusercontent.com/66902440/84589859-4f4cf080-ae3a-11ea-9dbb-3f6c777f9e72.jpg)

**Comment by Alex-302** [comment]
> Возможно ли решить эту проблему методом пользовательского фильтра?

Возможно.
https://kb.adguard.com/ru/general/how-to-create-your-own-ad-filters
