### ISSUE TITLE
Запрос удаления устаревших фильтров

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#57373]
Здравствуйте, прошу удалить устаревшие фильтры из приложения Adguard для андроид и расширения Adguard. Толку от этих фильтров нет никакого, они только занимают место в памяти и тормозят обработку страниц, если их включить. Ниже будут приведены скриншоты тех фильтров, которые по моему скромному мнению подлежат немедленному удалению.
Заранее спасибо!

Приложение Адгуард Андроид:
![Screenshot_20200614-120916](https://user-images.githubusercontent.com/66902440/84589594-6e4a8300-ae38-11ea-8487-b08841e11f73.jpg)
![Screenshot_20200614-120947](https://user-images.githubusercontent.com/66902440/84589597-70144680-ae38-11ea-9c02-05ac979a7045.jpg)
![Screenshot_20200614-121117](https://user-images.githubusercontent.com/66902440/84589598-70acdd00-ae38-11ea-8ec2-c005f9eac6e0.jpg)
![Screenshot_20200614-121154](https://user-images.githubusercontent.com/66902440/84589599-71457380-ae38-11ea-94e1-d2b4dbee0132.jpg)
![Screenshot_20200614-121014](https://user-images.githubusercontent.com/66902440/84589600-71457380-ae38-11ea-99c4-9dce49a15ceb.jpg)
![Screenshot_20200614-121043](https://user-images.githubusercontent.com/66902440/84589601-71de0a00-ae38-11ea-9459-6fdd6127f598.jpg)

Расширение Adguard:
![Screenshot_20200614-121430](https://user-images.githubusercontent.com/66902440/84589732-460f5400-ae39-11ea-9fb7-67fcf62b207c.jpg)
![Screenshot_20200614-121558](https://user-images.githubusercontent.com/66902440/84589733-47408100-ae39-11ea-9ca7-7fcdc2b00ddd.jpg)

**Comment by Alex-302** [comment]
Уберём, даже для разных платформ будут отличия.  Не всё так просто с ними. Старые версии могут поломаться.
