### ISSUE TITLE
swfchan.com - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5739]
***Site***: http://eye.swfchan.com/flash.asp?id=2773&n=CP.swf
***Description***: Captcha not displayed.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28314659-c2e394d2-6bbb-11e7-9d74-872c82930654.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.25.15
Spyware filter | 1.0.13.34
Social media filter | 1.0.21.20
Annoyances filter | 1.0.15.60
German filter | 1.0.35.67

**Comment by AdamWr** [comment]
Fixed.
