### ISSUE TITLE
Delay in website loading while in simplified domains filter

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#5742]
@bendingtime commented on [Tue Jul 18 2017](https://github.com/AdguardTeam/AdguardForAndroid/issues/1329)

Hi while loading any link from gazeta.pl website on chrome there is a few seconds delay between tap and actual website loading.

### Steps to reproduce

1. Set adblock to simplified domain filter,
2. Set it to block all apps,
3. Enable https filtering,
4. Open website. www.gazeta.pl
5. Tap any link on that website.

### Expected behavior

I expect that browser would go immediately to link I tapped.
### Actual behaviour

I have to wait few second which look like browser hanged.

<details><summary>Screenshot:</summary>

</details>

### Customer ID 

1273363
### Your environment

* Adguard version: 2.9.135
* Adguard filtering mode: VPN/ Simplified domain filter with battery saving tweaks enabled in advanced settings
* Device model: OnePlus3T
* Operating system and version: Android 7.1.2
* Rooted or not? NOT
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? NOPE

**Comment by altokarev** [comment]
Hi! I reproduced this issue with Simplified domain names filter only enabled but seems everything is OK with no filters enabled.

**Comment by bendingtime** [comment]
Have you enabled low power mode in advanced settings?

**Comment by bendingtime** [comment]
Please enable pref.vpn. ipv4 and ipv6 bypass. Those settings are needed to have battery saving.

**Comment by Alex-302** [comment]
@altokarev 
I see no difference with that filter and without Adguard.

**Comment by altokarev** [comment]
I've tested with the more powerful device once more. There is no issue in that case.

Quite a quick reaction on the tap with Simplified filter and without.

**Comment by bendingtime** [comment]
Yep,

Close the ticket please. Everything settled up after restarting the Adguard
and chrome few times.
Maybe it is device specific issue.

Thank you for support.

**Comment by bendingtime** [comment]
One last thing,

@altokarev can you check it on mobile data not on wifi please?

**Comment by Alex-302** [comment]
@bendingtime please check this rule
```
@@||gazeta.pl^$urlblock
```
Has the behavior changed?

**Comment by bendingtime** [comment]
Hi Alex,

How to do that when I am using only DNS blocking and no other filter is
enabled?

**Comment by altokarev** [comment]
@bendingtime There is no difference between mobile data and Wi-Fi on a weaker device. 6-7 seconds delay on a tap is still present and no delay without the Simplified filter.

**Comment by Alex-302** [comment]
@bendingtime 

> Adguard filtering mode: VPN/ Simplified domain filter with battery saving tweaks enabled in advanced settings

Is not you reported the issue?

**Comment by bendingtime** [comment]
@Alex-302 Yes it was me.

**Comment by Alex-302** [comment]
So what are you using - just Adguard DNS or Adguard for Android + DNS?

**Comment by bendingtime** [comment]
Adguard for Android with Simplified domain filtering

**Comment by Alex-302** [comment]
Is DNS filering option enabled?

**Comment by bendingtime** [comment]
Yes

**Comment by Alex-302** [comment]
Ok. Please capture ***web*** requests log with time stamp
https://kb.adguard.com/en/android/solving-problems/log
but `Set "Logging level" to "Record everything".` -> `Record web(http) requests `
