### ISSUE TITLE
https://www.solidfiles.com/ - incorrect blocking

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5743]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: https://www.solidfiles.com/ - the upload button on solidfiles is not working.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/23372054/28326311-1d748136-6be9-11e7-91da-aea8a18816c2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Firefox 54.0.1 x64
Adguard version: | 6.2.379.1984
Adguard driver: | WFP 
Adguard DNS: | None / Default / Family Protection
Stealth mode | disabled
Adguard filters: | English,Spyware
Ticket ID: | 1023133

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
@Alex-302 please take a look, it's sort of important.

**Comment by Alex-302** [comment]
Fixed
