### ISSUE TITLE
Lost Kingdom app issue- Android

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#5744]
@ypetruk commented on [Tue Jul 18 2017](https://github.com/AdguardTeam/AdguardForAndroid/issues/1330)

When Adguard enabled the app Lost Kingdom (https://play.google.com/store/apps/details?id=com.ftt.lostkaos&hl=ko) doesn't work properly - it doesn't let the user login
when https filtration for this app disabled- still doesn't work properly
but when the app is whitelisted - it works properly ( login process )
Adguard for Android
version: 2.9.135
enabled filters : 2, 3, 4, 14, 10, 11, 102, 211
filtering quality: full
Ticket ID: 1597829

---

@vozersky commented on [Tue Jul 18 2017](https://github.com/AdguardTeam/AdguardForAndroid/issues/1330#issuecomment-316088728)

@ypetruk does it work if you disable all the filters but keep protection enabled?  

---

@vozersky commented on [Tue Jul 18 2017](https://github.com/AdguardTeam/AdguardForAndroid/issues/1330#issuecomment-316093088)

filtering issue most likely

---

@ypetruk commented on [Tue Jul 18 2017](https://github.com/AdguardTeam/AdguardForAndroid/issues/1330#issuecomment-316123120)

it works well when all filters are disabled but having protection still enabled ( but I couldn't log out of the application to log in once more - because of the language hindrances)

**Comment by vozersky** [comment]
@ypetruk  have to figure out what filter causes the issue

**Comment by seanl-adg** [comment]
Strangely logging in with Google account does not work even with Adguard disabled on my end
