### ISSUE TITLE
Namesilo.com live chat support issue

### ISSUE THREAD

**Issue by ChiyoOsaka** [AdguardTeam/AdguardFilters#57458]
***Description***:
On the domain registrar website `namesilo.com`, they have a livechat funtion to contact their support team, which is provided by `intercom.io`/`intercom.com`.

* **Current behaviour**: 

The filter `||widget.intercom.io^$3p,domain=~intercom.com` appears to currently block the livechat's popup window from appearing.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

These were taken from the uBlock Origin logger.
![image](https://i.imgur.com/c39pV8Y.png)
![image](https://i.imgur.com/DlSQwvc.png)
![image](https://i.imgur.com/tB6Bivv.png)

Clicking the buttons below does nothing.
![image](https://i.imgur.com/sfoTCu3.png)
![image](https://i.imgur.com/0ZXM3Fv.png)
</details><br/>

* **Expected behaviour**: 

The support window should appear.

<details><summary>Screenshot:</summary>

Taken with uBlock Origin turned off.
![image](https://i.imgur.com/8fD7Nvo.png)
</details><br/>

***Steps to reproduce the problem***:

* Have the filter enabled.
* Navigate to either https://www.namesilo.com/help.php or https://www.namesilo.com/support/v2/services-faq/domain and scroll down to the bottom. 
* Click "chat with us".

***System configuration***

**Filters:**

uBlock filters, uBlock filters – Badware risks, uBlock filters – Privacy, uBlock filters – Resource abuse, uBlock filters – Unbreak, EasyList, AdGuard Tracking Protection, EasyPrivacy, Fanboy’s Enhanced Tracking List, Malware Domain List, Malware domains, Spam404, AdGuard Annoyances, AdGuard Social Media, Anti-Facebook, EasyList Cookie, Fanboy’s Annoyance, Fanboy’s Social, uBlock filters – Annoyances, Peter Lowe’s Ad and tracking server list, Malvertising filter list by Disconnect.

The uBlock Origin logger said that `AdGuard Annoyances` was the one causing the block here.

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  Windows 10 Home and Ubuntu 19.10 (tested on both)
Operating system version (Android/iOS) | N/a
Browser:                               | Firefox 77.0.1 (64-bit) (for both)
AdGuard version:                       | Version: 2.0.50.22 (for both)
Filters enabled:                       | All the filters I have enabled are listed above.
AdGuard mode (Android only):           | N/a
Filtering quality (Android only):      | N/a
HTTPS filtering (Android only):        | N/a
Simplified filters (iOS only)          | N/a
AdGuard DNS:                           | None 
Stealth mode options (Windows only)    | N/a
Helpdesk ID (if exists):               | N/a

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Annoyances filter is supposed to block chat widgets.
@Alex-302 can we make exclusions for at least support chats?

**Comment by Alex-302** [comment]
Not sure.
