### ISSUE TITLE
aliexpress.com

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#57457]
Приклеенная слева реклама мобильного приложения.

<details><summary>Screenshot:</summary>

![2020 06 15-1](https://user-images.githubusercontent.com/17948007/84691004-18ff9600-af4c-11ea-8479-b358587e9032.png)
</details>

`aliexpress.*##.left-affix:has(.mobile-app)`

[https://www.aliexpress.com/wholesale?trafficChannel=main&d=y&CatId=0&SearchText=2jx8ihrtp10&ltype=wholesale&SortType=default&g=n](https://href.li/?https://www.aliexpress.com/wholesale?trafficChannel=main&d=y&CatId=0&SearchText=2jx8ihrtp10&ltype=wholesale&SortType=default&g=n)

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.4.31
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
Не мешает же.

**Comment by XX-J** [comment]
> Не мешает же.

 При скролле списка товаров всё время остаётся на виду, двигаясь прикреплённой - маячит как бельмо на глазу.

**Comment by Alex-302** [comment]
`aliexpress.com##.mobile-app`
Будет белый прямоугольник маячить. Если скрыть, то может что-нибудь сломаться - есть очень похожие элементы.

**Comment by XX-J** [comment]
С моим правилом (`aliexpress.*##.left-affix:has(.mobile-app)`) не должно ломаться. Оно, как и Ваше, использует `.mobile-app`. У меня пока всё нормально :)

**Comment by Alex-302** [comment]
Будут.

**Comment by XX-J** [comment]
> С моим правилом (`aliexpress.*##.left-affix:has(.mobile-app)`) не должно ломаться.

 Я ошибся. Скрываются 'категории', находящиеся в `.left-affix`.

 **1**. Но там же, а точнее в подклассе `.ams-region`, на ряду с рекламой мобильного приложения появляется и обычная реклама.

<details><summary>Screenshot:</summary>

![2020 06 25-2](https://user-images.githubusercontent.com/17948007/85719330-00377300-b6f8-11ea-9434-deb85b472b10.png)
</details>

 Посему предлагаю изменить правило на одно из:
`aliexpress.*##.ams-region`
`aliexpress.*##.ams-region:has(> .mobile-app)`
`aliexpress.*##.ams-region:has(> .rus-mall-img)`

 И добавить правило подгонки блока под высоту содержимого ('категорий'):
`aliexpress.*#$#.left-affix { min-height: unset!important; }`

[https://aliexpress.ru/af/2xled.html?d=y&origin=n&SearchText=2xled&catId=0&initiative_id=SB_20200623235942](https://href.li/?https://aliexpress.ru/af/2xled.html?d=y&origin=n&SearchText=2xled&catId=0&initiative_id=SB_20200623235942)

___________________________________________________

 **2**. Рекламные товары в начале поисковой выдачи (первые 8 шт.). Все маркируются ярлыком 'Реклама' в правом нижнем углу.

<details><summary>Screenshot:</summary>

![2020 06 24-1](https://user-images.githubusercontent.com/17948007/85722831-5d80f380-b6fb-11ea-86cf-a1ae772a8dae.png)
</details>

`aliexpress.*##.list-item:has(.item-ad-tag)`

 Есть одно 'Но' - из-за 'ленивой' подгрузки товаров, после совершения поиска, в начале поисковой выдачи отображается белое, пустое поле. Достаточно чуть-чуть скрольнуть и вся выдача появляется, и без рекламы. Как бы 'пнуть этого ёжика', чтобы всё прогружалось автоматически (или отключить 'lazy loading')?

[https://aliexpress.ru/af/esr-meter.html?d=y&af=259050&aff_platform=link-c-tool&origin=n&afref=https%3A%2F%2Fali.pub&cn=45qcf4fxr2bo36xgr5o5n6oz0rf0xngh&dp=v5_45qcf4fxr2bo36xgr5o5n6oz0rf0xngh&SearchText=esr+meter&catId=0&cv=3620522&aff_request_id=7135299f5f9d45458415539dcb528816-1592981571351-02615-DlUAQI6c&initiative_id=AS_20160821040041&sk=DlUAQI6c&aff_trace_key=7135299f5f9d45458415539dcb528816-1592981571351-02615-DlUAQI6c&terminal_id=de147dd4013245a3bb514e2f56378838](https://href.li/?https://aliexpress.ru/af/esr-meter.html?d=y&af=259050&aff_platform=link-c-tool&origin=n&afref=https%3A%2F%2Fali.pub&cn=45qcf4fxr2bo36xgr5o5n6oz0rf0xngh&dp=v5_45qcf4fxr2bo36xgr5o5n6oz0rf0xngh&SearchText=esr+meter&catId=0&cv=3620522&aff_request_id=7135299f5f9d45458415539dcb528816-1592981571351-02615-DlUAQI6c&initiative_id=AS_20160821040041&sk=DlUAQI6c&aff_trace_key=7135299f5f9d45458415539dcb528816-1592981571351-02615-DlUAQI6c&terminal_id=de147dd4013245a3bb514e2f56378838)

**Comment by Alex-302** [comment]
Всё равно не добавлю. Часто меняют дизайн.

**Comment by XX-J** [comment]
Первое или второе?

**Comment by XX-J** [comment]
@Alex-302 

 Вы скрывать рекламу и в первом и во втором случае не намерены?
