### ISSUE TITLE
Вредоносные сайты

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#57466]
Здравствуйте,
Предоставляю список вредоносных (и потенциально нежелательных) сайтов для блокировки.

http://brevis.by/billy%20mail.ru/mail.ru/index.html  (фишинг)
moneyatphone.top  (фишинг)

на этих ресурсах (ниже) пользователю предлагается пройти "лотерею", "опрос" или стать "продавцом покинутых сайтов", выигрыш/прибыль от которых якобы будет перечислен на указанный номер банковской карты (или оформленной и активированной за деньги, которые нужно перечислить неизвестно кому), при этом пользователя просят указать подробную персональную информацию по карте - как результат, пользователь не только не получит "выигрыш" или "прибыль", но и потеряет все деньги с баланса карты

https://fastrefund.website
https://hmail1009.blogspot.nl
https://prizeme.com.ua
https://spleth.icu

на этих ресурсах (ниже), при попытке скачать искомые файлы, пользователям предлагается либо указать номер мобильного, либо отослать СМС на некий короткий номер - якобы для проверки, что пользователь реальный человек, а не бот; в результате такой "проверки" пользователь рискует либо стать жертвой массовых СМС спам-рассылок, либо потерять со своего мобильного счёта кругленькую сумму - и естественно, что никакого "секретного пароля" ему на мобильный не придёт

http://###.jugem.jp  (вместо решёток - произвольные комбинации из латинских букв и цифр)
http://100linksdvgpn.avafedors.freedomain.thehost.com.ua
http://6gyf.sionas.homelinux.org
http://driveron.ru
http://drivers.byethost16.com
http://files.truetds.icu/rutr/
http://forum.jokke.ru
http://fqevj.kolomnatrud.ru
http://fsfll.fgawudownsyfuf.info
http://geforcesh.preumnoj.ru
http://gsmsignal.ru/common.php?frl=###  (вместо решёток - имя искомого файла)
http://hit-kino.com
http://hjpzt.rtk-sales.ru
http://ikbsk.bear-hunt.ru
http://maksiko.ru
http://msaav.radiofaiz.ru
http://opendrivers.ru
http://orav.info
http://pravoholding.ru
http://qsiub.atomproduction.ru
http://qwcxp.elcoleso.ru
http://vernaconsco.rutopik.ru/?gmdl&keyword=###  (вместо решёток - название искомого файла)
http://vihce.wilgood63.ru
http://xagoc.geo-meter.ru

на этих ресурсах (ниже), при попытке скачать искомые файлы, пользователям подсовываются для скачивания программы-симуляторы самораспаковывающихся архивов, которые просят отослать СМС на короткий номер для якобы получения секретного пароля к скаченному архиву; также программные файлы, содержащие эдварные или вредоносные программы

https://###.apponic.com  (вместо решёток - название искомой программы)
http://###.blogspot.com  (вместо решёток - произвольный фрагмент из латинских букв или цифр; программа поисковика-установщика драйверов, файл которой скачивается по любой из ссылок группы данных сайтов, может устанавливать в систему - помимо драйверов - и прочие легальные и эдварные программы, не требуя разрешения у пользователя)
http://###.download-windows.org  (вместо решёток - название искомой программы; данный сайт содержит оригинальные дистрибутивы программ, но среди всех встречаются и фальшивые, содержащие потенциально опасные или даже вредоносные программы)
http://###.downloadastro.com  (вместо решёток - название искомой программы, или же просто фрагмент "ru", или "en")
https://1progs.ru  (этот сайт не содержит ссылок на вредоносное ПО, но по ссылкам на скачивание якобы разных программ в реальности загружается один и тот же программный загрузчик для установки какого-то топового софта - т.е. сайт рекламирует и предоставляет ссылку на одну и ту же программу, а все описания якобы других программ и ссылки на их дистрибутивы - просто липа)
https://advanced-systemcare-com.ru
http://aktiv-windows.ucoz.com
https://andyroid.net  (сайт содержит софт сомнительного характера)
https://antikeys.org
https://bandicam-pro.ru
https://botdilofce.bandcamp.com
https://boxprograms.ru  (этот сайт содержит оригинальные дистрибутивы программ, но среди всех встречается потенциально опасная эдварная программа-загрузчик под названием InstallPack_###.exe, где вместо решёток - название искомой программы + случайный набор символов)
http://chelcenter.ru/hat?charset=utf-8&keyword=###  (вместо решёток - название искомой программы)
https://computta.com
http://crackheaps.com
https://crackpluskeygen.org
https://doublegames.ru  (игры для Windows скачиваются посредством потенциально опасных мини-загрузчиков)
https://downloadelements.com
https://driveridentifier.com  (сайт содержит софт сомнительного характера)
http://drivers.org.ru
http://driverunpaid.ru
https://drp.su  (программа поисковика-установщика драйверов, файл которой скачивается по любой из ссылок данного сайта, может устанавливать в систему - помимо драйверов - и прочие легальные и эдварные программы, не требуя разрешения у пользователя)
http://filesdatabase4u.com  (программа поисковика-установщика драйверов, файл которой скачивается по любой из ссылок данного сайта, может устанавливать в систему - помимо драйверов - и прочие легальные и эдварные программы, не требуя разрешения у пользователя)
https://filehorse.com  (этот сайт содержит оригинальные дистрибутивы программ, но среди всех встречаются и фальшивые, содержащие потенциально опасные или даже вредоносные программы)
https://freecrackpatch.com
http://fsm-portal.net  (этот сайт содержит оригинальные дистрибутивы программ, но среди всех встречаются и фальшивые, содержащие потенциально опасные или даже вредоносные программы)
https://get.cryptobrowser.site  (использование скачиваемого браузера со встроенным майнером - на Ваш собственный страх и риск)
https://installpack.net  (программа поисковика-установщика драйверов, файл которой скачивается по любой из ссылок данного сайта, может устанавливать в систему - помимо драйверов - и прочие легальные и эдварные программы, не требуя разрешения у пользователя)
https://jeweell.com
https://kichkas.biz
https://kryptex.org
http://listid.ru
http://mediagetsite.com
https://mirsofta.ru  (этот сайт содержит оригинальные дистрибутивы программ, но среди всех встречаются и фальшивые, содержащие потенциально опасные или даже вредоносные программы)
http://moiprogrammy.com  (искомые программы скачиваются посредством потенциально опасных мини-загрузчиков)
https://mwfix.ru  (программа поисковика-установщика драйверов, файл которой скачивается по любой из ссылок данного сайта, может устанавливать в систему - помимо драйверов - и прочие легальные и эдварные программы, не требуя разрешения у пользователя)
http://nikask.ru
https://nullthemedownload.com
http://nvidiadrivers.net  (программа поисковика-установщика драйверов, файл которой скачивается по любой из ссылок данного сайта, может устанавливать в систему - помимо драйверов - и прочие легальные и эдварные программы, не требуя разрешения у пользователя)
https://oneindir.com  (сайт содержит загрузочный софт сомнительного характера)
https://oneprogs.ru
http://removal-virusguide.com  (сайт содержит софт сомнительного характера)
http://savow.com
http://serialms.com
http://smojem.ru
http://softkumir.ru
https://softportal.com  (этот сайт содержит оригинальные дистрибутивы программ, но среди всех встречаются и фальшивые, содержащие потенциально опасные или даже вредоносные программы)
http://solvusoft.com/ru/update/ драйверы  (программа поисковика-установщика драйверов, файл которой скачивается по любой из ссылок данного сайта, может устанавливать в систему - помимо драйверов - и прочие легальные и эдварные программы, не требуя разрешения у пользователя)
https://teramissu-hom.com
https://top-best-browser.ru  (этот сайт содержит оригинальные дистрибутивы программ по всем ссылкам за исключением того, который скачивается при нажатии на кнопку "Скачать программу с помощью MSetup" - это потенциально опасный загрузчик, скачивающий ПО сомнительного характера)
https://tvoiprogrammy.ru  (этот сайт содержит оригинальные дистрибутивы программ, но среди всех встречаются и фальшивые, содержащие потенциально опасные или даже вредоносные программы)
https://ubar-pro4.ru
http://upantool.com
http://updatestar.com/ru  (этот сайт содержит оригинальные дистрибутивы программ, но среди всех встречаются и фальшивые, содержащие потенциально опасные или даже вредоносные программы)
https://vipmolik.net
http://virus4remove.com
https://w10-digital-activation-program.ru
http://winxpsoft.com  (этот сайт содержит оригинальные дистрибутивы программ, но среди всех встречаются и потенциально опасные мини-загрузчики софта)
http://xeplayer.com  (этот сайт содержит оригинальный дистрибутив программы-эмулятора Android для Windows, но также по некоторым ссылкам скачивается и мини-программа для загрузки эдварного софта)
http://youtube.net.ua  (сайт содержит софт сомнительного характера)

Вирусы:
https://imei-poisk.ru/
https://programmi-dlya-vzloma.com/sms-shpionu/85-imei-poisk-20-programma-dlya-poiska-mobilnyh-telefonov-po-imei-ili-po-nomeru-telefona.html
17ebook.com
aladel.net
bpwhamburgorchardpark.org 
clicnews.com 
dfwdiesel.net 
divineenterprises.net 
fantasticfilms.ru 
gardensrestaurantandcatering.com 
ginedis.com 
gncr.org 
hdvideoforums.org 
hihanin.com 
kingfamilyphotoalbum.com 
likaraoke.com 
mactep.org 
magic4you.nu 
marbling.pe.kr 
nacjalneg.info 
pronline.ru 
purplehoodie.com 
qsng.cn 
seksburada.net 
sportsmansclub.net 
stock888.cn 
tathli.com 
teamclouds.com 
texaswhitetailfever.com 
wadefamilytree.org 
xnescat.info 
yt118.com

Подозрительный:
https://unvesouver39238.weebly.com/blog/imei-poisk-20

Прошу внести эти сайты в черные списки в **_СРОЧНОМ_** порядке
Заранее спасибо!

Пы.Сы.: Вероятнее всего часть этих доменов уже есть в ваших базах, но большей части скорее всего нет

**Comment by Chinaski1** [comment]
Практически все домены уже внесены в нашу базу.

**Comment by arGI-uchi8786o** [comment]
ммм
