### ISSUE TITLE
http://nashaplaneta.su - Ads leftover 

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5746]
***Description***:
* **Current behavior**: 

Ads leftover on http://nashaplaneta.su on Windows
Reproduced on our side (Mac OS)

<details><summary>Screenshot:</summary>

![screen shot 2017-07-18 at 9 31 05 pm](https://user-images.githubusercontent.com/28784344/28333381-7006910c-6c00-11e7-9b3b-8b1254a868ab.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: |  6.1.331.1732
Adguard driver (Windows): |TDI
Adguard DNS: | None 
Adguard filters: | 2, 3,4, 14, 1, 6, 105, 0 
Ticket ID (if exists): | 851529

**Comment by Alex-302** [comment]
Fixed
