### ISSUE TITLE
http://www.hdfulldiziler.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5747]
Site: http://www.hdfulldiziler.com/tatli-bela-130-bolum-izle-final-16-temmuz-2017-pazar-hd-full-tek-parca/
Screenshot: http://s4.postimg.org/rkybkul6l/screenshot_2.png

**Comment by Alex-302** [comment]
Added to Turkish filter
```
hdfulldiziler.com#$##rk-content { display: none!important; }
hdfulldiziler.com#$##cn-content { display: block!important; }
```
