### ISSUE TITLE
http://www.diziizlendi.org/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5748]
Site: http://www.diziizlendi.org/ruya-1-bolum-izle-18-temmuz-2017-hd-tek-parca.html
Screenshot: http://s4.postimg.org/otjn7zc1p/screenshot_4.png

**Comment by Alex-302** [comment]
Added to Turkish filter
```
diziizlendi.org#$#.iframe { display: block!important; }
diziizlendi.org#$#.ad { display: none!important; }

```
