### ISSUE TITLE
lenta.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#57494]
Видео с ren.tv не подгружается из-за заблокированного Referrer'a.

<details><summary>Screenshot:</summary>

![изображение](https://user-images.githubusercontent.com/17948007/84805174-870b9200-b00c-11ea-9a12-3dedbd2efb3d.png)
</details>

```
! https://github.com/AdguardTeam/AdguardFilters/issues/57494 [Stealth Mode - Referrer]
@@||ren.tv/*video/embed/$stealth
```

[https://lenta.ru/news/2020/06/15/drunk/](https://href.li/?https://lenta.ru/news/2020/06/15/drunk/)

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.4.31
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
Ок

**Comment by XX-J** [comment]
Нее, там вместе с плеером надо, иначе плеер тоже не подгружается.
 Из:
`@@||ren.tv/video/embed/$stealth`
`@@||ren.tv/player/video/embed/$stealth`
 Получаем:
`@@||ren.tv/*video/embed/$stealth`
