### ISSUE TITLE
https://www.google.com/chromebook/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5755]
We're blocking images on https://www.google.com/chromebook/

![screenshot_2](https://user-images.githubusercontent.com/15856304/28334224-23fcded0-6c03-11e7-8198-ca871ec5cd91.png)

**Expected behaviour**: 

![screenshot_3](https://user-images.githubusercontent.com/15856304/28334236-2f42539c-6c03-11e7-9672-22919e871699.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10
Browser: | Chrome
Adguard version: | the latest release
Adguard driver (Windows): | WFP
Adguard DNS: | Default
Stealth mode options(Windows) | on
Adguard filters: | English is the culprit (also I use russian annoyances, malware domains, spam 404)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added
```
!+ PLATFORM(windows)
@@||google.com/chromebook/$generichide
```
