### ISSUE TITLE
Missed ads in Imgur app

### ISSUE THREAD

**Issue by VuickB6** [AdguardTeam/AdguardFilters#57554]
Tried submitting this in the app but it had me manually submit it here. 

Imgur looks the have a new ad system where it looks likes a post from another user. This is on Android and Adguard is up to date. I have no user rules and all filters are updated.

Here is a screenshot of the ad. 
![Screenshot_20200617-110834](https://user-images.githubusercontent.com/36720253/84923980-9252d200-b08d-11ea-9ca9-7a195ad74866.png)

Thank you.

**Comment by Alex-302** [comment]
Hi. This is impossible to block ads in some apps(traffic cannot be filtered because SSL pinning)

**Comment by VuickB6** [comment]
It always has blocked all the other ads in this app. Is that still normal that this one isn't blocked?

**Comment by Alex-302** [comment]
Probably they did not show ads to you before. In some apps we cannot block ads(FB, Twitter)

**Comment by VuickB6** [comment]
That's not the case here, Adguard has always blocked ads. At least as long as I can remember. Here is what normally happens to ads. Look at the bottom of the screenshot 
![Screenshot_20200620-172542](https://user-images.githubusercontent.com/36720253/85212735-474dee80-b31b-11ea-95e6-f46f03377d9f.png)

**Comment by Alex-302** [comment]
Please record HAR file and send it + the issue number to filters@adguard.com
https://kb.adguard.com/en/android/solving-problems/har

**Comment by VuickB6** [comment]
So it looks like these new style ads have been removed from the app. I haven't seen it in a couple of days. The only ones are like the second picture.

Thank you anyways.
