### ISSUE TITLE
cellmapper.net - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5764]
***Site***: https://www.cellmapper.net/map?MCC=262&MNC=2&type=LTE&latitude=52.51394298962866&longitude=13.356180787085805&zoom=14&showTowers=true&clusterEnabled=true&tilesEnabled=true&heatMapEnabled=false&showOrphans=false&showNoFrequencyOnly=false&showFrequencyOnly=false&showBandwidthOnly=false&DateFilterType=FirstSeen&showHex=false&bands=0,3,7,20&showVerifiedOnly=false&showUnverifiedOnly=false&showLTECAOnly=false&showBand=0
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28344661-4af9f49c-6c25-11e7-94db-618837f3be0e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.25.15
Spyware filter | 1.0.13.34
Social media filter | 1.0.21.20
Annoyances filter | 1.0.15.60
German filter | 1.0.35.67

**Comment by AdamWr** [comment]
Fixed.
