### ISSUE TITLE
http://dreamfilmhd.sh/ - pop ups when clicking on the player

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5765]
http://dreamfilmhd.sh/movies/details/683245755-back-in-the-day/

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28363411-232d17b4-6c89-11e7-9b23-90ea2b4378b7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows and Mac
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | Default
Adguard filters: | english, spyware, fanboy swedish
Ticket ID: | 1590594

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
