### ISSUE TITLE
能不能添加adgk规则

### ISSUE THREAD

**Issue by biange200** [AdguardTeam/AdguardFilters#57661]
adguard自带规则对中国的APP支持不怎么好 能不能加入这个
https://gitee.com/banbendalao/adguard/raw/master/ADgk.txt
规则到adguard规则里 好丰富adguard对中国APP的广告过滤

**Comment by Alex-302** [comment]
@biange200 Hi. Please take a look)
https://github.com/AdguardTeam/FiltersRegistry/pull/343
