### ISSUE TITLE
yiv.com - Ad leftover - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5766]
***Site***: https://www.yiv.com/Stickman-Archer-Online
***Description***: Adblock detection and ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28394288-28d6758a-6cec-11e7-9090-c41ff0f83af6.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.25.35
Spyware filter | 1.0.13.38
Social media filter | 1.0.21.31
Annoyances filter | 1.0.15.76
German filter | 1.0.35.70

**Comment by AdamWr** [comment]
Fixed.
