### ISSUE TITLE
WallpapersCraft app- Incorrect blocking- Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5767]
***Description***:
* **Current behavior**: 

There is a black dark space on the place where the ad used to be (lower part see the screenshots) in the app WallpapersCraft. 
https://play.google.com/store/apps/details?id=com.wallpaperscraft.wallpaper

Is that possible to remove the blank space? Thank you!

<details><summary>Screenshot:</summary>

![754ca185af802e0b7089f4d9667fdbeb](https://user-images.githubusercontent.com/28784344/28395096-472a0192-6cfa-11e7-9b7b-74ee6b04e00b.png)

</details>

<details><summary>Screenshot:</summary>

![a69418853c3f2e46b50d94d7e3b888d6](https://user-images.githubusercontent.com/28784344/28395098-4ba7c0f6-6cfa-11e7-9162-b87e6a6f1387.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.135
Filtering quality (Android): | high-speed 
HTTPS filtering (Android): |  On (Default) 
Adguard DNS: | None 
Adguard filters: | 2, 3, 4, 1, 11 
Ticket ID (if exists): | 1489066

**Comment by Alex-302** [comment]
It is builtin placeholder.
