### ISSUE TITLE
Сайты мошенники

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#57672]
**_Главные кандидаты на блокировку:_**
Причина блокировки - это то, что этот сайт занимаеться мошенничеством ставками на спорт. Он запрещен на территории РФ (и не только). Даже Ютуб банит эти ссылки!!! Оградите хотябы своих пользователей от этого сайта с мошенниками!
Ниже перечислены домены этого сайта:
https://1xstavka.ru
https://ua-1x-bet.com
http://1xbet.top
https://1xbet.mobi/
https://1xbet.business/official-site/
https://1xbet-vxod.ru/skachat-1xbet-na-android-ios/
https://x-bettor.com/sloty-kazino-zerkalo-1xbet/
https://b-kreslo.ru/  (дада, это тоже хбет)
https://freetibet.ru/  (да, и это тоже хбет)
https://ru-1xbet.com/
https://ru-1x-bet.com/
https://ua-1xbet.com/
https://ua-1x-bet.com
http://1xbet-online.com/1xbet-kazino/
https://teaandcoffeeuk.ru/  (и да, это тоже хбет)

Это всё сайты, на которых можно получить зеркало икс бета (они все ведут на 1хбет (тоже мошенники):
https://bookmaker-ratings.com.ua/ru/review/obzor-i-otzyvy-bukmekerskoy-kontory-1xbet-com/amp/
https://sport.ua/amp/betting/bookmakers/1xbet
https://m.ua.tribuna.com/betting/ratings/1xbet_ua/
https://primfootball.com/maps/aktualnie-zerkala-1xbet/1xbet-aktualnoe-zerkalo-pryamo-seychas.html
https://www.footboom.com/amp/betting/bookmaker/1xbet
https://m.sports.ru/betting/ratings/1xstavka/feedbacks/
https://sectorbet.com/
https://bookmaker-ratings.ru/review/obzor-i-otzyvy-bukmekerskoy-kontory-1xbet-com/
http://bet-rate.com/1xbet-overview/
https://eldo0xwin.com/?ref=fap_w12357p112_bonus_freespin&path=/promos/l7773/  (вредоносный сайт, ведёт на 1хбет и распространяет вирусы)

Мошенники:
Этот сайт также как и икс бет занимается левыми, мошенническими ставками. Прошу заблокировать.
https://favbet.com/

Реклама мошеннических сайтов:
Эти сайты ведут на хбет, тем самым продвигая мошенников
https://www.ua-football.com/betting/bookmakers/8-bukmeker-1xbet
https://sport.ua/amp/betting/bookmakers/1xbet

Сомнительные сайты (якобы ставки, подозреваю в мошенничестве (уверен 99,9%))
https://legalbet.ru/
https://m.favorit.com.ua/
https://m.parimatch.com/

Мошенники (вероятность 90%):
http://hyperx-alloy.ru
http://cloud-mix.ru
http://alloy-rgb.ru
http://hyperx-predator.ru
http://hyper-x.top
http://predator-operativ.top
http://hx-fpspro.top
http://hyperx.ru.com
http://shop-technic.ru
http://rgb-furyssd.vse-dar0m.ru
http://skidk1-tut.ru

Все эти сайты предоставляют угрозу для пользователей, прошу оградить от них хотя бы ваших юзеров

**Comment by Chinaski1** [comment]
1xstavka.ru
ua-1x-bet.com
1xbet.top
1xbet.mobi
1xbet.businessofficial-site
1xbet-vxod.ruskachat-1xbet-na-android-ios
x-bettor.comsloty-kazino-zerkalo-1xbet
b-kreslo.ru 
freetibet.ru 
ru-1xbet.com
ru-1x-bet.com
ua-1xbet.com
ua-1x-bet.com
1xbet-online.com1xbet-kazino
teaandcoffeeuk.ru
favbet.com
hyperx-alloy.ru
cloud-mix.ru
alloy-rgb.ru
hyperx-predator.ru
hyper-x.top
predator-operativ.top
hx-fpspro.top
hyperx.ru.com
shop-technic.ru
rgb-furyssd.vse-dar0m.ru
skidk1-tut.ru

Добавлены к черному списку.
Насчет остальных нет 100% уверенности. Поэтому пока остаются под наблюдением.
