### ISSUE TITLE
eizvestia.com - Ads leftover 

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5768]
***Description***:
* **Current behaviour**: 

There are ads on eizvestia.com (Android)
Please, go on http://photo-nedeli.eizvestia.com/full/photo-gallery?album=1&gallery=388&pid=8642
Reproduced on our side (Mac OS)

<details><summary>Screenshot1:</summary>

![screen shot 2017-07-20 at 3 38 04 am](https://user-images.githubusercontent.com/28784344/28395452-dc81f072-6cfc-11e7-9439-21994374b91d.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.70
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard DNS: | None
Adguard filters: | 2, 3, 14, 1, 5, 11 
Ticket ID (if exists): | 1598602

**Comment by Alex-302** [comment]
Fixed.
