### ISSUE TITLE
Fruugo sites - Broken (AdGuard Annoyances filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#57682]
### Affected sites:
```
https://www.fruugo.ae/
https://www.fruugo.at/
https://www.fruugo.be/
https://www.fruugo.ca/
https://www.fruugo.ch/
https://www.fruugo.co.il/
https://www.fruugo.co.nz/
https://www.fruugo.co.uk/
https://www.fruugo.co.za/
https://www.fruugo.com.tr/
https://www.fruugo.cz/
https://www.fruugo.de/
https://www.fruugo.eg/
https://www.fruugo.dk/
https://www.fruugo.es/
https://www.fruugo.fi/
https://www.fruugo.fr/
https://www.fruugo.gr/
https://www.fruugo.hu/
https://www.fruugo.it/
https://www.fruugo.ie/
https://www.fruugo.jp/
https://www.fruugo.kr/
https://www.fruugo.lu/
https://www.fruugo.my/
https://www.fruugo.nl/
https://www.fruugo.no/
https://www.fruugo.ph/
https://www.fruugo.pl/
https://www.fruugo.pt/
https://www.fruugo.qa/
https://www.fruugo.ro/
https://www.fruugo.ru/
https://www.fruugo.se/
https://www.fruugo.sg/
https://www.fruugo.sk/
https://www.fruugo.us/
https://www.fruugoaustralia.com/
https://www.fruugobahrain.com/
https://www.fruugochina.com/
https://www.fruugoindia.com/
https://www.fruugosaudiarabia.com/
```

### Issue:
Lots of elements and functions won't load, rendering the sites useless!

### Screenshot:
Not needed, as the the problem is obvious.

### Problem filter:
* AdGuard Annoyances filter

### Problem rule:
`/cookie-banner$domain=~bbc.com`

### Blocked script (example from the `.co.uk` domain):
`https://www.fruugo.co.uk/marketplace/js/c3a6909c4548bdfdc35c514c9719d0b4a01ce304/modules/cookie-banner.js`

### Possible fix:
`@@/cookie-banner.js$domain=fruugo.ae|fruugo.at|fruugo.be|fruugo.ca|fruugo.ch|fruugo.co.il|fruugo.co.nz|fruugo.co.uk|fruugo.co.za|fruugo.com.tr|fruugo.cz|fruugo.de|fruugo.eg|fruugo.dk|fruugo.es|fruugo.fi|fruugo.fr|fruugo.gr|fruugo.hu|fruugo.it|fruugo.ie|fruugo.jp|fruugo.kr|fruugo.lu|fruugo.my|fruugo.nl|fruugo.no|fruugo.ph|fruugo.pl|fruugo.pt|fruugo.qa|fruugo.ro|fruugo.ru|fruugo.se|fruugo.sg|fruugo.sk|fruugo.us|fruugoaustralia.com|fruugobahrain.com|fruugochina.com|fruugoindia.com|fruugosaudiarabia.com`

### Other problem filters:
* EasyList Cookie List / Fanboy's Annoyance List (`/cookie-banner`)
https://github.com/ryanbr/fanboy-adblock/issues/1372/

* I don't care about cookies (`/cookie-banner.js$domain=~labs.strava.com`) _Notified_

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.10.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.21b3 (XUL)

**Comment by krystian3w** [comment]
`@@||*cookie-banner.js` why not `@@/cookie-banner.js`?

**Comment by THEtomaso** [comment]
> `@@||*cookie-banner.js` why not `@@/cookie-banner.js`?

Both works for me!
But OK.. first post edited :)

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
