### ISSUE TITLE
sockshare.net - Page blocking by a content blocker 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5769]
***Description***:
* **Current behaviour**: 

http://sockshare.net/cinema-movies.html
Clicking on the search bar on the website leads to a new popup window.

<details><summary>Screenshot:</summary>

![screen shot 2017-07-20 at 8 35 32 am](https://user-images.githubusercontent.com/27292111/28402101-af96be9c-6d26-11e7-9d20-b093f6c5f0c7.png)

![screen shot 2017-07-20 at 8 35 57 am](https://user-images.githubusercontent.com/27292111/28402102-b16f1606-6d26-11e7-8879-3e301d1866f7.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.25.32 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.38 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.30 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.15.74 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.3 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.95 Enabled=YES

Ticket ID: 1590438

GMT +8:00 (1:46 AM)

[com.adguard.AdguardPro.gz](https://github.com/AdguardTeam/AdguardFilters/files/1161259/com.adguard.AdguardPro.gz)
[com.adguard.AdguardPro.tunnel.gz](https://github.com/AdguardTeam/AdguardFilters/files/1161260/com.adguard.AdguardPro.tunnel.gz)
[filter.gz](https://github.com/AdguardTeam/AdguardFilters/files/1161261/filter.gz)

**Comment by Alex-302** [comment]
Added
```
||play.entretenimientolz.com^
1062804$domain=sockshare.net
```
