### ISSUE TITLE
http://www.fulldiziizleyelim2.com/ (ADBLOCK + EMPTY SPACE)

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5770]
Site: http://www.fulldiziizleyelim2.com/dolunay-3bolum-hd-720p-18-temmuz-2017-sali.html
Screenshot: http://s4.postimg.org/ndw0papx9/screenshot_5.png

**Comment by AdamWr** [comment]
Added:
`@@||tune.pk/js/ads.js^`
`||stats1.tune.pk^`
In my opinion these empty spaces all too small to hide them, but if you want you can add this rule to user filter:
`fulldiziizleyelim2.com###body-video > .video-box[-ext-has='center > g\:plusone']`
