### ISSUE TITLE
http://www.canlihddizi.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5771]
Site: http://www.canlihddizi.com/atesbocegi-3-bolum-izle.html
Screen: http://s4.postimg.org/yrn5e8ptp/screenshot_6.png

**Comment by AdamWr** [comment]
Added to Turkish filter:
`canlihddizi.com##.footer-sticky`
`canlihddizi.com#%#Object.defineProperty(window, 'puShown', { get: function() { return true; } });`
