### ISSUE TITLE
http://www.abcdizi.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5773]
Site: http://www.abcdizi.com/kanatsiz-kuslar-6-bolum-izle.html
Screen: http://s4.postimg.org/3oibql7el/screenshot_8.png

**Comment by AdamWr** [comment]
Added:
`abcdizi.com##.safirShare`
`abcdizi.com#%#Object.defineProperty(window, 'puShown', { get: function() { return true; } });`
