### ISSUE TITLE
databor.ru - Chat blocking 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5774]
https://databor.ru/

***Description***:
* **Current behaviour**: 

One of the customers is wondering whether it is possible to add any exception to the Annoyances filter since this filter blocks chatra.io online chat on this website so his potential clients are not able to ask anything really quick. 

Ticket ID: 1598283

**Comment by Alex-302** [comment]
No. It is for people who understand the purpose of the annoyances filter.

**Comment by Alex-302** [comment]
Also it is disabled by default.

**Comment by veronikasav** [comment]
Thank you!
