### ISSUE TITLE
msn.com / Edge [Ads] [AdGuard Browser Extension]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#57754]
**Edge Version**: 83.0.478.54 (Official build) (64-bit)

**AdGuard Browser Extension**: Version 3.4.31 (from Chrome Store)

**Filters Enabled**: AdGuard Base filter, AdGuard Mobile Ads filter, Peter Lowe's Blocklist, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, Adblock Warning Removal List, Malware Domains Blocklist, Spam404, NoCoin Filter List

**Stealth Mode Settings**: https://i.imgur.com/HXvg4SY.png

**Issue**: Ads seen when Edge is launched. After opening, scroll down and the news feed from msn.com will load. Among the news articles (tiles), you will also see ads.

**Screenshot**: https://i.imgur.com/4H3QfjS.png

Opening msn.com directly in browser (Chrome/Edge) too shows ads (https://i.imgur.com/Es4svDS.png). Please fix

**Comment by krystian3w** [comment]
New tab need AdGuard for Windows / macOS?

https://github.com/AdguardTeam/AdguardFilters/issues/48484

**Comment by Alex-302** [comment]
I can't reproduce. Do you see ads after refresh?

**Comment by Nzzyme** [comment]
> I can't reproduce. Do you see ads after refresh?

Yes, I do

**Comment by Nzzyme** [comment]
Seeing ads even on Chrome

https://i.imgur.com/qcf6yEx.png

**Comment by Nzzyme** [comment]
Is anyone checking this? Why was this issue closed?

I just checked and still seeing ads

https://i.imgur.com/ex1DyWN.png

Please fix this.

**Comment by krystian3w** [comment]
Microsoft A/B test on small people range, also try with disabled your added filters or without stealth mode.

**Comment by Alex-302** [comment]
Cannot fix if not reproduced.
