### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#57795]
**1** 

https://github.com/AdguardTeam/AdguardFilters/blob/70c58ae94a1be73a38845c9b102deac18104a2a0/TurkishFilter/sections/specific.txt#L2741

Please move this to the `general_url.txt` folder.

---

**2**

Duplicate rule.

https://github.com/AdguardTeam/AdguardFilters/blob/70c58ae94a1be73a38845c9b102deac18104a2a0/TurkishFilter/sections/adservers.txt#L4

Base rule - `||basvformu*.xyz^$third-party`

---

**3**

I don't know if this is valid, but there seems to be an extra space here.

https://github.com/AdguardTeam/AdguardFilters/blob/70c58ae94a1be73a38845c9b102deac18104a2a0/TurkishFilter/sections/specific.txt#L3641

---

**4**

Dead rule.

`donanimhaber.com###pnlNoSmTakip`

**Comment by krystian3w** [comment]
3 - valid and still should hide `fixedLeftAd`:

[Screenshot_2020-06-22 Büyükşehir’in Kaldırım İhalesi Sonuçlandı](https://user-images.githubusercontent.com/35370833/85260920-bc303e00-b46b-11ea-8327-833a3c389fc1.png)

```html
<div class="fixedAd fixedLeftAd" style="display: block; left: 102.5px;"><br>
<br>
    <a href="http://www.finalegitim.com.tr/" target="_blank">
        <img src="http://malatyahaber.com/wp-content/uploads/2019/09/final-17-eylul.gif" alt="Final">
    </a>
<br>
<br>
    <a href="https://www.instagram.com/melitagumus/?igshid=8ry4h2btswge" target="_blank">
        <img src="http://malatyahaber.com/wp-content/uploads/2019/12/melita-gumus-malatya.gif" alt="Fuat">
    </a>
<br>
</div>
```
