### ISSUE TITLE
http://sinemapol.org/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5786]
Site: http://sinemapol.org/savas-vadisi-turkce-izle/
Screen: http://s4.postimg.org/xj8x3gtkt/screenshot_20.png (Enter site, play video and in the corner of plyer, you can see a link, plz remove that

**Comment by Alex-302** [comment]
Added to Turkish filter
```
dizipas.org##.jw-controlbar-right-group > a
```
