### ISSUE TITLE
discord.com [N: Nano Adblocker] [T: Incorrect Blocking]

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#57879]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

If 4:5 screen ratio Twitter videos are embedded in a Discord channel, the embed becomes blank when clicked on, although the embed's sound can be heard.

The chat and GUI functions on `discordapp.com` was changed into `discord.com` roughly 1½ months ago, meaning that the existing whitelisting should be updated accordingly into `~discord.com##iframe[width="240"][height="300"]`.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/85378364-c2412000-b53a-11ea-9c2d-e953b954d9d1.png)
</details><br/>

* **Expected behaviour**: 

The video is visible.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/85378458-e00e8500-b53a-11ea-8f88-873b637be226.png)
</details><br/>

***Steps to reproduce the problem***:

1) Have access to a Discord server/channel that allows embed previews of posted links.
2) Post https://twitter.com/StrangestMp4/status/1272946576600649728 into it.
3) Try to play the embed with AdGuard Base turned on in some way.
4) See that the video and video controls are blanked out.

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/85378745-44314900-b53b-11ea-980d-3a12913c0a56.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | May 2020 Update
Browser:                               | Chrome 83.0.4103.106 x64
AdGuard version:                       | Nano Adblocker 1.0.0.149 + Nano Defender 15.0.0.200
Filters enabled:                       | See screenshot above
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | N/A
Helpdesk ID (if exists):               | N/A

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Thank you, added discord.com to rule in case they may switch back.
