### ISSUE TITLE
http://www.ilkfullfilmizle.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5791]
Site: http://www.ilkfullfilmizle.com/preacher-2-sezon-4-bolum-turkce-altyazi-hd-full-izle.html
Screen: http://s4.postimg.org/ofai30rzx/screenshot_23.png

**Comment by Alex-302** [comment]
It can't be hidden,

**Comment by The-Commissioner** [comment]
@thislife81 Can you try this rule:-

`ilkfullfilmizle.com##.sidebarborder:first-child + .sidebarborder`

**Comment by Alex-302** [comment]
It is not safely. I din't want to add rules like that.
