### ISSUE TITLE
HDSector.com - Popup flash

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardFilters#5793]
W10 x64
AGW 6.2.379.1984
FF 54.0.1 x64
Adguard DNS
Https filtering is enabled.
WFP driver

English & Spyware
Stealth,browsing Sec, parental control,extension - all disabled.

http://www.hdsector.com/
There are popups  flashing on the aforementioned site.

**Comment by The-Commissioner** [comment]
@AdamWr I'm quoting you, since you also dealt with the previous issue from same site.

https://github.com/AdguardTeam/AdguardFilters/issues/5681

**Comment by Alex-302** [comment]
You can reopen existing your issue.
