### ISSUE TITLE
clashroyalepedia.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5794]
***Site***: https://www.clashroyalepedia.com/Deck_Strategies/Meta_Decks
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28411823-5b82e670-6d42-11e7-80aa-602d53c14912.png)

![image](https://user-images.githubusercontent.com/10995998/28411810-5146f49e-6d42-11e7-88f1-c09187515e74.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.25.35
Spyware filter | 1.0.13.38
Social media filter | 1.0.21.31
Annoyances filter | 1.0.15.76
German filter | 1.0.35.70

**Comment by AdamWr** [comment]
Fixed.
