### ISSUE TITLE
com.HealthFitnessAndTutorials.UnixTutorial

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#57945]
***Description***:
* **Current behaviour**: 

Displays quite a lot of ads.

<details><summary>Screenshots:</summary>
[AzScreenShots.zip](https://github.com/AdguardTeam/AdguardFilters/files/4822441/AzScreenShots.zip)
</details><br/>

***Steps to reproduce the problem***:

1. Just install and run the app.

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 9
Browser:                               | n/a
AdGuard version:                       | 3.4 release
Filters enabled:                       | Base, English, Greek, Mobile Ads
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default mode)
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | 2745894

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Please let the user try this rule in User filter
`||graph.facebook.com^$app=com.HealthFitnessAndTutorials.UnixTutorial`

I did not see a Facebook login button on quick reviewing the page, but if there is one hidden, it will not work with that rule.
