### ISSUE TITLE
clashroyale.news - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5795]
***Site***: http://clashroyale.news/
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28411877-8d1eb024-6d42-11e7-88c4-88bccb3b256b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.25.35
Spyware filter | 1.0.13.38
Social media filter | 1.0.21.31
Annoyances filter | 1.0.15.76
German filter | 1.0.35.70

**Comment by danidoedel** [comment]
`clashroyale.news##.adsense_colonne`

**Comment by AdamWr** [comment]
Added.
