### ISSUE TITLE
BUG in English Filter List

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardFilters#5796]
A comment was published as a rule because somebody forgot to add the exclamation mark before it.

Open English Filter > Search for:-

`https://github.com/AdguardTeam/AdguardFilters/issues/5669`

This is marked as a rule rather than a comment.

**Comment by danidoedel** [comment]
You could also just link to the respective line:

https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/foreign.txt#L949

**Comment by AdamWr** [comment]
Thank you 👍 
Fixed.
