### ISSUE TITLE
beltehno.by - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5797]
На сайте beltehno.by не убирается кнопка "написать письмо" справа внизу
страницы. Браузер опера мобайл.

[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screenshot_2017-07-19-07-20-53](https://user-images.githubusercontent.com/15856304/28412007-795cd080-6d4b-11e7-8700-1d65c7de64aa.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: |
Adguard version: | 2.9.70
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On 
Adguard filters: | 2, 3, 4, 14, 1, 11
Ticket ID (if exists): | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не повторилось. Может сжатие включено? Если в другом браузере убирается, то закрывай.

**Comment by evgeniy-ADG** [comment]
в другом - чисто, но, говорят, красная трубка сверху есть везде.

**Comment by Alex-302** [comment]
Трубку убрал.
