### ISSUE TITLE
onlinefanatic.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5798]
***Site***: http://onlinefanatic.com/clash-royale-decks-for-climbing-arena/
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28412096-6a5b9c86-6d43-11e7-8206-556f4c565479.png)

![image](https://user-images.githubusercontent.com/10995998/28412173-9d7e8808-6d43-11e7-938d-665615d5efa8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.25.35
Spyware filter | 1.0.13.38
Social media filter | 1.0.21.31
Annoyances filter | 1.0.15.76
German filter | 1.0.35.70

**Comment by AdamWr** [comment]
Fixed.
