### ISSUE TITLE
NOT_OPTIMIZED typo

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5799]
Should be NOT_OPTIMIZED not NOT_OPTIMZED:

https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/general_elemhide.txt#L9
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/foreign.txt#L648
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/foreign.txt#L650
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/foreign.txt#L689

**Comment by Alex-302** [comment]
Thanks, fixed.
