### ISSUE TITLE
PLATFORM syntax issue

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5800]
There should be no whitespace after PLATFORM and NOT_PLATFORM before the parenthesis:

https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/foreign.txt#L736
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/antiadblock.txt#L123
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/antiadblock.txt#L125
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/antiadblock.txt#L127
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/antiadblock.txt#L161
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/antiadblock.txt#L163
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/antiadblock.txt#L165
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/antiadblock.txt#L167
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/antiadblock.txt#L233
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/antiadblock.txt#L255
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/css_extended.txt#L19
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/specific.txt#L68
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/specific.txt#L70
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/specific.txt#L72
https://github.com/AdguardTeam/AdguardFilters/blob/master/RussianFilter/sections/specific.txt#L21
https://github.com/AdguardTeam/AdguardFilters/blob/master/RussianFilter/sections/specific.txt#L23
https://github.com/AdguardTeam/AdguardFilters/blob/master/RussianFilter/sections/specific.txt#L25

**Comment by Alex-302** [comment]
Fixed.
