### ISSUE TITLE
rustorka.com - incorrect blocking

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5801]
Русским фильтром заблокирован блок "Новые поступления". Видно только для зарегистрированных пользователей.

URL:

http://rustorka.com/forum/index.php

<details><summary>Screenshot:</summary>

![64f6rgbupde](https://user-images.githubusercontent.com/28726429/28430641-ed73ac62-6d89-11e7-91c3-b40ae840455a.jpg)

</details>

<br>
***System configuration***

Information | value
--- | ---
Operating system: | macOS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 12, 14

**Comment by Alex-302** [comment]
У меня всё на месте. Какой фильтр ломает?

**Comment by altokarev** [comment]
Русский же. Стоит его отключить - появляется блок.

**Comment by Alex-302** [comment]
проверь
@@||rustorka.com^$elemhide,important

**Comment by altokarev** [comment]
Помогло.

**Comment by Alex-302** [comment]
Посмотри в Хроме, какое правило скрывает. Сначала без русского фильтра найди какой-нибудь уникальный элемент в этом блоке, а потом с блокировкой пройдись от того элемента вверх по дереву и найди самый верхний скрытый элемент. Справа будет применённый стиль, и применённое правило будет выделено жирным.
