### ISSUE TITLE
300mbfilms.co - Popups

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardFilters#5804]
W10 x64
AGW 6.2.379.1984
FF 54.0.1 x64
Https filtering is enabled.
WFP driver

English & Spyware
Stealth,browsing Sec, parental control,extension - all disabled.

https://www.300mbfilms.co/
There are popups on the aforementioned site.

![1](http://i.imgur.com/8RHHXeo.jpg)

**Comment by Alex-302** [comment]
I can't reproduce.
@AdamWr @seanl-adg please check on your end.

**Comment by AdamWr** [comment]
I can only reproduce if I disable this rule - `||popads.net/pop.js^$empty,important`
Added:
`300mbfilms.co#%#Object.defineProperty(window, '_pop', { get: function() { return {}; } });`
