### ISSUE TITLE
24video.adult

### ISSUE THREAD

**Issue by AdguardHelper** [AdguardTeam/AdguardFilters#5806]
Я Золотой Парень, если помните (ZP, Daddy...)
Решил обойти косарь популярных сайтов (HotlOG TOP 1000).
Где нахожу рекламу - отписываюсь. Вот эта тема как раз старт.
Ссылка: http://www.24video.adult/video/view/2439982
Скриншот: http://prntscr.com/fydu7u

**Comment by Alex-302** [comment]
Помню. И помню как в августе 2014 года на https://code.google.com/ruadlist/ матом покрывал пользователей Адгарда:)

Реклама не повторилась.
