### ISSUE TITLE
money.yandex.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#58069]
Промо-попап.

<details><summary>Screenshot:</summary>

![2020 06 26-1](https://user-images.githubusercontent.com/17948007/85837117-5102a680-b7a0-11ea-8289-330c7e1b1740.png)
</details>

`money.yandex.ru##.promo-popup`

[https://money.yandex.ru/actions?nav=autopay](https://href.li/?https://money.yandex.ru/actions?nav=autopay)

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.4.31
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
Скопируй `class` текстом. 
Прокрутка не блокируестя?

**Comment by XX-J** [comment]
> Скопируй `class` текстом.

```
<div class="modal modal_theme_normal popup2 promo-popup i-bem popup2_js_inited modal_js_inited popup2_visible_yes modal_has-animation_yes modal_visible_yes promo-popup_js_inited" style="z-index: 21001;">
  <div class="modal__table">
    <div class="modal__cell">
      <div class="modal__content">
        <div class="promo-popup__content">
          <span class="promo-popup__icon promo-popup__icon_name_close promo-popup__close"></span>
          <img class="image promo-popup__image" src="/i/moneyland_supergame_2906.png" alt="">
          <h1 class="title promo-popup__title">Мы продлили суперигру «Манилэндии» до&nbsp;15&nbsp;июля</h1>
</div></div></div></div></div>
```

<details><summary>Screenshot:</summary>

![2020 07 01-2](https://user-images.githubusercontent.com/17948007/86205103-be804f80-bb71-11ea-85f7-a46e66022c7d.png)
</details>

> Прокрутка не блокируестя?

 До этого не блокировалась/не замечал. Сейчас, прописавши принудительно в `.promo-popup` `display: none!important;`, она оказалась скрыта. Скрывается она в `body` (что на 1 уровень выше `.promo-popup`) `.b-page_hide-scroll_yes { overflow: hidden; }`. Соответственно показывается также: `money.yandex.ru#$#body { overflow: auto!important; }`

**Comment by Alex-302** [comment]
Проверь такие в приватной вкладке
```
money.yandex.ru#$#.promo-popup_js_inite { display: none !important; }
money.yandex.ru#$#body { overflow: visible !important; }
```

**Comment by XX-J** [comment]
Работают! Но...

 Во-первых: Вы ошиблись в первом правиле, не дописав в классе букву **d**: `money.yandex.ru#$#.promo-popup_js_inite`**d**` { display: none !important; }`.

 Во-вторых: Нах.. такие сложности? Можно же просто - `money.yandex.ru##.promo-popup_js_inited` (проверил - работает).

**Comment by Alex-302** [comment]
Ты же писал что прокрутка не работает. Если первое сделать без CSS, то сломается сайт на платформах без поддержки правил CSS.

**Comment by XX-J** [comment]
> ...на платформах без поддержки правил CSS.

 Это где правила CSS не поддерживаются? Не знал что есть такое... 0_0

> Ты же писал что прокрутка не работает.

 Но если щёлкнуть средней кнопкой мышки и водить ею вверх и вниз, то всё скроллится.

 Вопрос в догонку: зачем пишут правила с вопросом `#?#` и чем они отличаются от обычных `##`?

**Comment by Alex-302** [comment]
> Это где правила CSS не поддерживаются? Не знал что есть такое... 0_0

iOS, кондент-блокер для Android.
