### ISSUE TITLE
 http://www.myscore.ru/ - Unable to log in

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#5810]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

When Adguard enabled it's impossible to log in on  http://www.myscore.ru/

Log In window disappears on any mouse click.

Reproduced on my side.

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/26434103/28461472-668f0926-6e1f-11e7-82ce-c10ef0c2f6ae.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/26434103/28461496-89318f4e-6e1f-11e7-9407-372f50ba4a62.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1.331
Adguard driver (Windows): | WFP
Adguard DNS: | None
Stealth mode options(Windows) | Disabled
Adguard filters: | Russian, English, Annoyances, Spyware, Social media
Ticket ID (if exists): | 1075539

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. Show me HTML code like on my screenshot

<details>

![image](http://imagizer.imageshack.com/img923/1252/Cp6gHH.png)
</details>

**Comment by OlegSUP** [comment]
HTML
<details>

![image](https://user-images.githubusercontent.com/26434103/28463667-40c947b4-6e2a-11e7-88a2-ee2b31e6b955.png)

</details>

**Comment by Alex-302** [comment]
Ok, got it. They are using the same z-index for popup message and overlay.
It is their own issue.
Added to Russian filter
```
myscore.com.ua#$##lsid-window.registration { z-index: 3147483647!important; }
```
