### ISSUE TITLE
expressodaspraias.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#58103]
[https://www.expressodaspraias.com.br/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.expressodaspraias.com.br/)

Ads loaded from `||expressodaspraias.com.br/images/banners` and overlay:

![overlay banner](https://user-images.githubusercontent.com/35470489/85890171-3beb3f00-b7c3-11ea-945f-c1413d8d2645.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
Popup not reproduced.

**Comment by adranger** [comment]
@uBlock-user please check if you get this overlay (gafancybox). It takes a few seconds to appear.

**Comment by uBlock-user** [comment]
@adranger fixed in Spanish filterlist -https://github.com/AdguardTeam/AdguardFilters/commit/a2c3b47da2bd7fe706c82123237c5e7fb170407d ???

**Comment by Alex-302** [comment]
Not yet. Fixed.
