### ISSUE TITLE
reports.agduard.com

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#58125]
Предлагаю на сайте reports.adguard.com :
1. _**Добавить пункт "вредоносный/мошеннический сайт"**_
Зачем:
Очень не удобно отсылать заявки на блокировку вредоносных сайтов

2. **_Заменить ReCaptcha на hCaptcha_**
Зачем:
Я, например, не могу отправлять вам репорты через программу, так как у меня заблокированы все домены Гугла (я думаю, что я не один такой), а включать впн для этих целей не желаю.

Плюсов переезда с ReCaptcha на hCaptcha уйма:
* За нё не надо платить, в отличии от гугловской версии
* Надёжность. Сам Cloudflare на нё переехал.
Вот пруфы: https://blog.cloudflare.com/moving-from-recaptcha-to-hcaptcha/amp/
* Доступность. Пользователи, у которых заблокирован гугл (будь то работодателем или правительством) смогут ничего не нарушая отсылать вам репорты.
* hCaptcha платит вам.
Вот пруфы: https://www.hcaptcha.com/
* Конфиденциальность. hCapcha не собирает личные данные.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/ReportsWebApp #239](https://github.com/AdguardTeam/ReportsWebApp/issues/239) via [**ZenHub**](https://www.zenhub.com/)
