### ISSUE TITLE
Уязвимость!!!

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#58158]
Платформа - расширение.
Проблема:
Возможна поддела настоящей страницы адгуард.

Вот ссылка для проверки:
chrome-extension://gfggjaccafhcbfogfkogggoepomehbjl/pages/blocking-pages/safebrowsing.html?host=!!!%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D1%8F%D1%8F%20%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%20%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%20%22host%22%20%D1%8F%20%D0%BC%D0%BE%D0%B3%D1%83%20%D0%B2%D1%8B%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D1%8C%20%D0%BD%D0%B0%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%20%D0%BB%D0%B5%D0%B2%D1%8B%D0%B5%20%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F.%20%D0%A2%D0%B0%D0%BA%D0%B6%D0%B5,%20%D1%81%D0%BA%D0%BE%D0%BF%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%B2%20%D1%82%D0%B5%D0%BA%D1%83%D1%89%D1%83%D1%8E%20%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D1%83%20%D0%B8%20%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D0%BB%D0%B0%D0%B2%20%D0%B5%D1%91%20%D0%BA%D0%BE%D0%BC%D1%83-%D0%BD%D0%B8%D0%B1%D1%83%D0%B4%D1%8C%20%D1%83%20%D0%BA%D0%BE%D0%B3%D0%BE%20%D0%B5%D1%81%D1%82%D1%8C%20%D0%B0%D0%B4%D0%B3%D1%83%D0%B0%D1%80%D0%B4%20%D0%B2%D1%8B%D1%81%D0%B2%D0%B5%D1%82%D0%B8%D1%82%D1%81%D1%8F%20%D1%8D%D1%82%D0%BE%20%D0%BE%D0%BA%D0%BD%D0%BE.%20%D0%B0%20%D1%82%D0%B5%D0%BF%D0%B5%D1%80%D1%8C%20%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D1%82%D0%B5,%20%D1%87%D1%82%D0%BE%20%D0%B1%D1%83%D0%B4%D0%B5%D1%82%20%D0%B5%D1%81%D0%BB%D0%B8%20%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C,%20%D0%BD%D0%B0%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%20%D1%81%D0%BB%D0%B5%D0%B4%D1%83%D1%8E%D1%89%D0%B5%D0%B5:%20%22%D0%BC%D1%8B%20%D0%BE%D1%87%D0%B5%D0%BD%D1%8C%20%D1%81%D1%82%D0%B0%D1%80%D0%B0%D0%B5%D0%BC%D1%81%D1%8F%20%D0%B4%D0%BB%D1%8F%20%D0%B2%D0%B0%D1%81.%20%D0%96%D0%B4%D1%91%D0%BC%20%D0%B2%D0%BE%D0%B7%D0%BD%D0%B0%D0%B3%D1%80%D0%B0%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F%20********!!!

Открыв эту ссылку вы увидите сообщение от адгуард, якобы ссылка заблокирована. Дело в том, что если менять значение после "host=" то можно заставить адгуард показать то, что мне хочется. Скрины ниже.
![Screenshot_20200627-181225](https://user-images.githubusercontent.com/67512843/85925836-d0c56980-b8a3-11ea-8ee7-844f1002bf7b.jpg)
![Screenshot_20200627-180906](https://user-images.githubusercontent.com/67512843/85925838-d327c380-b8a3-11ea-9553-1a419a28b83f.jpg)

Прошу пофиксить

**Comment by Alex-302** [comment]
Здесь закрываю.
