### ISSUE TITLE
http://www.diziizleb.net/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5816]
Site: http://www.diziizleb.net/dolunay-son-bolum/dolunay-3-bolum-izle-18-temmuz-2017-full/
Screen: http://s4.postimg.org/gx1gomda5/screenshot_31.png (Click here, you will get a popup)

**Comment by AdamWr** [comment]
I can't reproduce.
Could you please check this again?

**Comment by thislife81** [comment]
I checked and popup is already removed :)

Please, look at here: http://s3.postimg.org/3msxwql9v/screenshot_55.png 

Is there any need to block this?

**Comment by AdamWr** [comment]
Ok, thank you.

> Is there any need to block this?

Yes, added to Spyware filter:
`||dmx.sync.yume.com/tracker/`
