### ISSUE TITLE
Hide your IP feature breaks http://kinogo.club/

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5819]
The customer reported that using aforementioned feature causes inability to watch a movie ("File not found" error).

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28474314-d99d755c-6e50-11e7-925f-7f5d2dab0a7d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows NT 6.1.7601 Service Pack 1
Browser: | IE11
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | TDI
Adguard filters: | 1, 2
<details><summary>Stealth mode options:</summary>

- >   "BlockThirdPartyCookies": true,
- >   "BlockThirdPartyCookiesPeriodMin": 30,
- >   "BlockFirstPartyCookies": false,
- >   "BlockFirstPartyCookiesMin": 2880,
- >   "DisableThirdPartyCache": true,
- >   "BlockWebRtc": true,
- >   "BlockBrowserPushApi": true,
- >   "BlockBrowserLocationApi": true,
- >   "RemoveXClientDataHeader": true,
- >   "HideSearchQueries": true,
- >   "SendDoNotTrackHeader": true,
- >   "RemoveRefererFromThirdPartyRequests": true,
- >   "HideUserAgent": true,
- >   "CustomUserAgent": null,
- >   "CustomReferer": null,
- >   "HideIp": true,
- >   "CustomIp": "209.141.53.254"

</details>

**Comment by Alex-302** [comment]
Can't reproduce. I need that IP.

**Comment by evgeniy-ADG** [comment]
Попрошен, обновлю, как ответят.

**Comment by evgeniy-ADG** [comment]
> В настройках программы IP 209.141.53.254. В основном это происходит с сереалами и многосерийными фильмами. С односерийными фильмами вроде работает.

**Comment by Alex-302** [comment]
Added to English filter
```
@@||kinogo.*/*.flv$stealth
```
