### ISSUE TITLE
[Default DNS] Why AliDNS blocked?

### ISSUE THREAD

**Issue by mHatsune** [AdguardTeam/AdguardFilters#58208]

**Comment by Alex-302** [comment]
Hi. Please provide domain name.

**Comment by mHatsune** [comment]
Domain `alidns.com`
Now it seems working with default DNS but yesterday it didn't work (and past weeks randomly, it's the reason closed the issue 12days ago) however when the problem occur, adguardhome logs show A: 0.0.0.0 (ttl=3259) as response
But at same time if check with adguard unfiltered DNS then able to visit to the site.

**Comment by mHatsune** [comment]
@Alex-302 Right now again unable to visit using default and why adguard DNS acting mad like that with chinese domains?

**Comment by Alex-302** [comment]
Hi. We do not block alidns.com.
Is alidns.com - full domain name, or with sub-domain?

**Comment by mHatsune** [comment]
`www.alidns.com`

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/392
