### ISSUE TITLE
http://ren.tv/ - ads on the start page and in articles

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5820]
Not blocking ads on the site.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28475471-0223216c-6e55-11e7-8a56-18874f046c63.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows NT 10.0.15063.0
Browser: | Chrome
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP 
Adguard filters: | 1 2 3 4 6 8 14
Ticket ID (if exists): | 1243747

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
