### ISSUE TITLE
https://m.lenta.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5821]
Missed ads on https://m.lenta.ru, on the start page and probably in articles.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28479839-d70262b0-6e66-11e7-8425-c4e423e5c3e6.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Chrome
Adguard version: | 2.9.70
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On default
Adguard DNS: | None
Adguard filters: | 2, 3, 4, 1, 11
Ticket ID (if exists): | 848229

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can you reproduce it? I don't see ads.

**Comment by evgeniy-ADG** [comment]
I was able when filing the task. Will check again soon.

**Comment by Alex-302** [comment]
Please let me know about result.

**Comment by evgeniy-ADG** [comment]
They say "ее нет".
