### ISSUE TITLE
linkneverdie.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5823]
***Site***: https://linkneverdie.com/
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28486713-58ef4e14-6e85-11e7-8bda-cb20136ff8a6.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.25.54
Spyware filter | 1.0.13.41
Social media filter | 1.0.21.37
Annoyances filter | 1.0.15.83
German filter | 1.0.35.71

**Comment by AdamWr** [comment]
Fixed.
