### ISSUE TITLE
Anti-adlbock banner on The Hill

### ISSUE THREAD

**Issue by yokoffing** [AdguardTeam/AdguardFilters#58258]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: The Hill displays anti-adblock message. Both AdGuard's and Fanboy's Annoyances list are enabled in AdGuard. Sample url: `https://thehill.com/homenews/administration/504974-trump-shares-video-of-homeowners-pointing-guns-at-protesters-in-st`. 

I don't see this using NanoAdblocker with Chromium browsers becauseI have many more filter lists enabled on my Chromium browsers. I really can't pinpoint if another filter list covers this without a lot of testing.

* **Current behaviour**: Browsable but banner at the bottom needs blocking.
* **Screenshot**: https://postimg.cc/VJDHP7Ch

* **Expected behaviour**: No banner

***System configuration***

**Filters:**
* **Screenshot**: https://postimg.cc/nXPY1N7n

Information                            | Value
---                                    | ---
Operating system:                      | macOS 11.0 Beta
Operating system version (Android/iOS) | ?
Browser:                               | Safari 14
AdGuard version:                       | Stable
Filters enabled:                       | see screenshot

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Sadly not reproduced on Windows, maybe Safari only issue.

Please try these rules:
```
thehill.com#@#.ADBox
thehill.com#@#.AD_area
thehill.com#@#.AdsRec
thehill.com#@#.Ads_4
```

**Comment by Alex-302** [comment]
Also not reproduced, in Safari.

**Comment by yokoffing** [comment]
This occurred in the new Safari 14, macOS Big Sur developer beta. I was having other issues getting AdGuard to work.

I acknowledge y’all haven’t had time to push a release for the new OS yet. So we may just disregard this and revisit once AdGuard is updated and stable.
