### ISSUE TITLE
livetracklist.com - Social widgets - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5826]
***Site***: http://www.livetracklist.com/hardwell-off-the-record-009/
***Description***: Social share button. Ads.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28490360-7989bcec-6ed8-11e7-8be3-e8cc2313dc75.png)

![image](https://user-images.githubusercontent.com/10995998/28490363-8affff7c-6ed8-11e7-9405-5854bce499f8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter | Version
--- | ---
English filter | 1.1.25.54
Spyware filter | 1.0.13.41
Social media filter | 1.0.21.37
Annoyances filter | 1.0.15.83
German filter | 1.0.35.71

**Comment by AdamWr** [comment]
Fixed.
