### ISSUE TITLE
Missed ad at "Офлайновые словари" app

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardFilters#5827]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

https://play.google.com/store/apps/details?id=fr.nghs.android.dictionnaires&hl=ru

Reproduced on my side.

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/26434103/28493903-3706d080-6f28-11e7-925f-15d22b9df9df.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Install dictionary and try to translate any word.

***System configuration***

Information | value
--- | ---
Operating system: |Android 
Adguard version: | 2.9.135
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None 
Adguard filters: | English, Russian, Spyware, Annoyances, Social media, Mobile
Ticket ID: | 1599889

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Banners are also `offline` :(
