### ISSUE TITLE
linuxandubuntu.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#58287]
[http://www.linuxandubuntu.com/home/10-best-free-photo-editors-for-linux](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://www.linuxandubuntu.com/home/10-best-free-photo-editors-for-linux)

Unrelated video overlay:

<details><summary>Screenshot:</summary>

![overlay](https://user-images.githubusercontent.com/35470489/86068642-571daf00-ba4e-11ea-9239-604ae7bbbbb0.png)
</details><br/>

Banner at the end of the article:

<details><summary>Screenshot:</summary>

![banner](https://user-images.githubusercontent.com/35470489/86068655-5edd5380-ba4e-11ea-814c-9573834713fc.png)
</details><br/>

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
