### ISSUE TITLE
Be focused app - missed ad

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5829]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:  missed ad in Be focused app 
https://itunes.apple.com/us/app/be-focused-focus-timer-goal-tracker-for-work/id973130201?mt=8

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details>

![image](https://user-images.githubusercontent.com/23372054/28495044-b2c2bd4e-6f49-11e7-9b3f-677fc268fc41.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Adguard version: | 1.4.1
Adguard filters: | English, Spyware, Social media, Annoyances, Safari
Ticket ID: | 1597358

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Where can I see this ad? Can't find.

**Comment by BernardL66** [comment]
Hello, the ads is in ther OSX version : 
https://itunes.apple.com/fr/app/be-focused-minuterie-de-mise-au-point/id973134470?mt=12

**Comment by Alex-302** [comment]
Please describe, where I can see this ad.

**Comment by BernardL66** [comment]
The ads is in the bottom : 
http://prntscr.com/fzqh6r

**Comment by Alex-302** [comment]
it seems that ad(self-promo) is builtin to the app:(
