### ISSUE TITLE
Блокировка Яндекс.Турбо

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#58300]
Здравствуйте,
Ранее существовал очень хороший скрипт (ссылка ниже) предназначенный для блокировки турбо страниц. Увы, сейчас но не работает. Так как он настроен на работу со ссылками https://yandex.ru/turbo/s/ а сейчас турбо страницы Яндекса выглядят так https://domain.turbopages.org. Это можно проверить в Яндекс дзен. Например, нажав на эту ссылку:
https://yandex.ru/turbo/s/novate.ru/blogs/130420/54127/
Вас перекинет на эту:
https://novate-ru.turbopages.org/s/novate.ru/blogs/130420/54127
Из-за чего скрипт не может работать.  Есть ли способ на данный момент заблокировать Яндекс.Турбо?

Вот ссылка на уже не работающий скрипт:
https://greasyfork.org/ru/scripts/396403-%D1%83%D0%B4%D0%B0%D0%BB%D0%B8%D1%82%D1%8C-%D1%8F%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D1%82%D1%83%D1%80%D0%B1%D0%BE

_**ОС: Андроид 7
Версия адгуард: последняя, релиз**_

**Comment by cutekartoshka** [comment]
Здравствуйте!
Вот скрипт, решающий эту проблему.

`// ==UserScript==
// @name         Удалить Яндекс-Турбо
// @description  Переадресация с турбо-страниц яндекса на целевую страницу.
// @run-at       document_start
// @include      https://yandex.ru/*
// ==/UserScript==

function getUrlVar() {
    var urlVar = window.location.search;
    var arrayVar = [];
    var valueAndKey = [];
    var resultArray = [];
    arrayVar = (urlVar.substr(1)).split('&');
    if (arrayVar[0] == "") return false;
    for (i = 0; i < arrayVar.length; i++) {
        valueAndKey = arrayVar[i].split('=');
        resultArray[valueAndKey[0]] = valueAndKey[1];
    }
    return resultArray;
}

var urlLandingPage = getUrlVar();
var urlPathname = window.location.pathname;

if (urlPathname == '/turbo') {
    top.location.replace(decodeURIComponent(urlLandingPage['text']));
} else if (urlPathname.indexOf('/turbo/s/') != -1) {
    top.location.replace('https://' + urlPathname.substr(urlPathname.indexOf('/turbo/s/') + 9));
} else if (urlPathname == '/search/touch/') {
    $('a[data-sc-host]').each(function() {
        var urlYaTurbo = $(this).attr('href');
        var dataCounter = JSON.parse($(this).attr('data-counter'));
        if ((urlYaTurbo.indexOf('https://yandex.ru/turbo/s/') != -1) || (urlYaTurbo.indexOf('https://yandex.ru/turbo?text=') != -1)) {
            $(this).attr('data-bem', '{"link":{}}');
            if (dataCounter[0] == 'b') {
                $(this).attr('href', dataCounter[1]);
            } else if (dataCounter[0] == 'w') {
                $(this).attr('href', dataCounter[3]);
            }
        }
    });
}`

**Comment by cutekartoshka** [comment]
@adguard
@adguard-bot

Предлагаю добавить этот скрипт в ваши базы. (Безвозмездно)
https://greasyfork.org/ru/scripts/406340-%D1%83%D0%B4%D0%B0%D0%BB%D0%B8%D1%82%D1%8C-%D1%8F%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D1%82%D1%83%D1%80%D0%B1%D0%BE

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/DisableAMP #30](https://github.com/AdguardTeam/DisableAMP/issues/30) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
Перенёс в более подходящее место.
