### ISSUE TITLE
Зайцев.net — музыка - Ad leftover - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5831]
***Description***:
* **Current behavior**: 
There are ads in Android app:
https://play.google.com/store/apps/details?id=com.rumuz.app
Reproduced on our side
- Ads have a periodical character: it sometimes appears, sometimes disappears. 

<details><summary>Screenshot:</summary>

![screenshot_2017-07-22-13-00-32](https://user-images.githubusercontent.com/28784344/28496858-1d5f2644-6f7f-11e7-8669-f597728bc4f9.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.70
Adguard mode (Android): | Proxy(manual)
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None 
Adguard filters: | 2, 3, 4, 14, 1, 11, 15
Ticket ID (if exists): | 1572619

**Comment by Alex-302** [comment]
Can't reproduce. I see only empty placeholder.
I need http(web) requests log with time stamp. Clear cache before it.
