### ISSUE TITLE
http://m.biqugetw.com - missed ad on page 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5833]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://m.biqugetw.com/book/20387/ - missed ad on page 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/23372054/28501917-4a8408f4-6fef-11e7-8d38-e40c8258700e.png)

</details>

***System configuration***

Application version: 1.2.1.71
Device: iPhone
OS: 10.3.3
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.23.53 Enabled=NO
ID=3 Name="Spyware filter" Version=1.0.13.41 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.37 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.15.83 Enabled=YES
ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.10 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.65 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.6 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.95 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.84.45 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.3.42 Enabled=YES
Ticket ID 1593788

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed in English filter.
