### ISSUE TITLE
it-like.ru - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5834]
http://it-like.ru/kak-uskorit-android/

<details><summary>Screenshot:</summary>

![screen shot 2017-07-23 at 11 47 01 pm](https://user-images.githubusercontent.com/27292111/28502727-51feecfe-7001-11e7-9d8c-2ba3f2b30bc8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1 2 3 4 14
Ticket ID: | 1142657

**Comment by Alex-302** [comment]
Fixed
