### ISSUE TITLE
theverge.com -Ad Leftover - iOS

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5837]
***Description***:
* **Current behaviour**: 

Missed ad (from vox media) on the page: [Adguard Pro for iOS]
https://www.theverge.com/

Reproduced on our side (Mac OS)
<details><summary>Screenshot:</summary>

![screen shot 2017-07-24 at 11 35 09 am](https://user-images.githubusercontent.com/28784344/28514946-83bf2cd2-7064-11e7-820f-0add8cb39450.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  iOS
Adguard version: | 1.2.1.71
Simplified filters(iOS) |Off
Adguard filters: | 0, 2, 3, 4, 14, 10, 11,12
Ticket ID (if exists): | 1601617

**Comment by Alex-302** [comment]
Fixed.
