### ISSUE TITLE
Consider using DuckDuckGo tracker radar data sets to include new trackers to AdGuard filters

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#58396]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ✅ ] I checked the documentation and found no answer
- [ ✅ ] I checked to make sure that this issue has not already been filed

### Problem Description

Some trackers are not in AdGuard lists but they appear on DuckDuckGo tracker radar

### Proposed Solution

Check DuckDuckGo tracker radar data sets to find entries that are not included in AdGuard tracking protection filter

### Additional Information

DDG data sets ( https://github.com/duckduckgo/tracker-radar ) are crawled automatically once per month ( https://spreadprivacy.com/duckduckgo-tracker-radar/ ) and that level of finding new trackers (specially fingerprinters https://github.com/duckduckgo/tracker-radar/blob/master/docs/DATA_MODEL.md ) at scale is quite uncommon (I do not know if AdGuard has that capability or relies on community finding news trackers)

**Comment by a-privacy-conscious-user** [comment]
This screenshots shows some of the fingerprinters that were not blocked by other lists (EasyList and AdGuard did not block some of them) but that appeared on DuckDuckGo tracker radar data sets. Maybe there are more that could be added to more lists

![Captura de Pantalla 2020-07-01 a la(s) 11 09 41](https://user-images.githubusercontent.com/67610240/86254045-b03f2d00-bb8b-11ea-89eb-007c5b73ecfa.png)

**Comment by llacb47** [comment]
many domains included in duckduckgo tracker radar data are not trackers. Discussion here: https://github.com/uBlockOrigin/uAssets/issues/7073

**Comment by ryanbr** [comment]
Given list development is completely separate between each company, just a wholesale import yet another list could seem an overkill and just bloat the list

**Comment by ameshkov** [comment]
I'd just like to take a closer look at their methodology and maybe pick up something useful from it. Blindly importing a list that was automatically created by a bot does not seem a sane idea to me, sure.

**Comment by a-privacy-conscious-user** [comment]
of course, I agree with everything that has been said. What I had in mind was trying to crawl the data set and import perhaps only the ones that are undoubtedly trackers (for example those that use lots of apis or set many cookies and have high site prevalande). The data set allows you to filter what you want. Of course, exclude CDN and other elements that may cause site breakage. I am not saying DDG list is perfect but maybe there is some useful info that can be pulled from it

**Comment by ryanbr** [comment]
There is a few instances where lists can `/akam/11/*` specific folders, without being specific.
