### ISSUE TITLE
http://tap.az/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5840]
Site: http://tap.az/
Screen1: http://postimg.org/image/os9u1bdbj/ (Now it is site's background.)
Screen2: http://s3.postimg.org/xm0qif0ab/screenshot_47.png (But background has to like this/ So, remove black sections)

This rule helped me to remove that: tap.az##.bg-bnr, .bg-bnr_left, .fix

**Comment by Alex-302** [comment]
Fixed
