### ISSUE TITLE
Прокушенная реклама и троян!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/AdguardFilters#58414]
### Issue URL (Ads)
http://babulya-gaming.ru/iceload.php?title=uTorrent%20Pro%203.5.5.45672%20[Rus%20+%20Crack]&size=16.8%20%D0%9C%D0%91&count=4551&link=aHR0cDovL2JhYnVseWEtZ2FtaW5nLnJ1L3Byb2dzLzIvdVRvcnJlbnQgUHJvIDMuNS41LjQ1NjcyLnJhcg==

### Comment
Username: @Spok1

### Screenshots
<details><summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/34476664/86273815-785ed680-bbd9-11ea-8b06-4625def5cfd2.png)

</details>

### System configuration

Information                            | Value
---                                          | ---
Platform:	|Ext
AdGuard version:	|3.0.11
Browser:	|Chrome
Stealth mode options:	|Hide your search queries, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Hide your Referrer from third-parties
Filters:	|AdGuard Russian,</br>AdGuard Annoyances,</br>AdGuard Base,</br>AdGuard Tracking Protection,</br>AdGuard Social Media

**Comment by Chinaski1** [comment]
Blacklisted!
