### ISSUE TITLE
Mensenlinq.nl - Broken search functionality in Safari

### ISSUE THREAD

**Issue by RobynScore** [AdguardTeam/AdguardFilters#5841]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
When using Safari (on both iOS and MacOS), searching for obituaries on [mensenlinq.nl](http://www.mensenlinq.nl) (leading Dutch obituary website) results in WebKitErrorDomain:104: URL blocked by content blocking. 

* This is probably caused by too aggressive filtering for the word 'advertentie' (Dutch for advetisement) or 'adv'. An obituary is called a "mourning advertisement" in Dutch, hence the usage of the words 'advertentie' and 'adv' in the search query links. Problem does not occur in Firefox with same filters.

* **Expected behaviour**: 
The search query should execute and a list of obituaries should be displayed.

***Steps to reproduce the problem***:
Use the search box on mensenlinq.nl and hit 'zoeken'.

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS / iOS
Browser: | Safari 10.1.2
Adguard version: | Adguard browser extension 2.6.5 / Adguard for iOS 1.2.1
Simplified filters (iOS) | Off

Filter name | Version | Update
--- | --- | ---
English filter | Version 1.1.25.70. | Updated 24 july 2017
Spyware filter | Version 1.0.13.43. | Updated 23 july 2017
Dutch filter | Version 1.0.9.29. | Updated 10 july 2017
Safari filter | Version 1.0.3.53. | Updated 15 july 2017
Fanboy Anti-Facebook List | Version 1.0.0.13. | Updated 19 july 2017

**Comment by Alex-302** [comment]
Please check this rule in user filter:
```
@@||mensenlinq.nl/site/advertentie/$domain=mensenlinq.nl
```

**Comment by RobynScore** [comment]
Rule fixes the functionality on both iOS and MacOS. Thanks.

**Comment by Alex-302** [comment]
Ok, added.
