### ISSUE TITLE
http://itavisen.no/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5843]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image1](https://user-images.githubusercontent.com/15856304/28561926-f86070a4-7128-11e7-8ba9-443d2bd0fc40.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari (works fine in Chrome)
Adguard version: | 1.2.1.71
Simplified filters(iOS) | Off
Adguard DNS: | Default 
Adguard filters: | 2 3 4 12 15 120
Ticket ID (if exists): | 1602033

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
itavisen.no##cloudflare-app[app-id="no-adblock"]
```
