### ISSUE TITLE
Блокировка cookies

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#58434]
Здравствуйте,
Есть ли возможность заблокировать cookies на всех сайтах, кроме example.com?
Дано:
Adguard 3.4
Режим фильтрации: локальный ВПН
Вышестоящий прокси: Orbot
Задача:
Заблокировать все cookies на всех сайтах, кроме example.com

Возможно ли это? Если да, то какое правило я должен добавить и куда? В исключения Https или в обычный пользовательский фильтр?

**Comment by zloyden** [comment]
Добавьте в пользовательские `$cookie,domain=~example.com`
