### ISSUE TITLE
Пользовательские правила

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#58433]
Здравствуйте,
Есть ли возможность исключить домен из передачи через прокси?

Дано:
Adguard 3.4
Режим фильтрации: локальный ВПН
Вышестоящий прокси: Orbot
Задача:
Сделать так, чтобы я заходил на сайт ficbook.net в обход прокси.

Возможно ли это? Если да, то какое правило я должен добавить и куда? В исключения Https или в обычный пользовательский фильтр?

**Comment by Alex-302** [comment]
Нельзя.
