### ISSUE TITLE
Annoyance Request: Pop-ups on AliExpress

### ISSUE THREAD

**Issue by yokoffing** [AdguardTeam/AdguardFilters#58448]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: AliExpress shows the same pop-up offering a coupon no matter despite viewing multiple product pages on their site.
* **Current behaviour**:  https://postimg.cc/GHtwVfpB

**Comment by BlazDT** [comment]
It only showed once when I visited the site, also not sure if we should block it as it contains a coupon code for the user, opinions @AdguardTeam/filters-maintainers ?

```
aliexpress.com##div[data-widget-cid="widget-20"]
aliexpress.com##.ui-mask
```

**Comment by yokoffing** [comment]
I think there was a conflict with another extension I was running.

**Comment by Alex-302** [comment]
@yokoffing please check these rules one by one in new private tabs:
`aliexpress.ru,aliexpress.com#$?##newuser-activity-config { remove: true; }`
or
`is.alicdn.com#%#if (typeof localStorage != 'undefined' && localStorage.setItem) { localStorage.setItem('2', '"{\"2USD_coupon_popup\":1}"'); }`

**Comment by yokoffing** [comment]
I think this was a bug in my content blocker or browser. Issue seems to be resolved now.

**Comment by Alex-302** [comment]
@yokoffing the first rule was added to Annoyances filter after your previous comment.

**Comment by yokoffing** [comment]
> the first rule was added to Annoyances filter after your previous comment.

Thank you for clarifying!
