### ISSUE TITLE
prohardver.hu - ad leftovers

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5844]
Today, the ads on the site have again become problematic
See the attached picture (Adguard ON and Adguard OFF).

<details><summary> on </summary>

![adguard_ph_filter_07-24](https://user-images.githubusercontent.com/15856304/28563852-ec5934c4-712f-11e7-9151-d8fecfca47f7.jpg)

</details>

<details><summary> off </summary>

![adguard_ph_disabled_adguard_07-24](https://user-images.githubusercontent.com/15856304/28563861-f21e257c-712f-11e7-9b8c-05e20cf7006f.jpg)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | English, Spyware, Social media, Annoyances, hufilter, Malware domains
Ticket ID (if exists): | 859481

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/5609

**Comment by Alex-302** [comment]
That leftover is hidden by hufilter
```
prohardver.hu##[class*="xabre"]
```
@evgeniy-ADG недельной давности таски того же юзера можно переоткрывыть..

**Comment by evgeniy-ADG** [comment]
А чего не работает у него тогда? Обновить хуфильтр?

**Comment by Alex-302** [comment]
Не знаю. Может фильтр старый. У меня он от 12 июля. Пусть обновиться попробует.

**Comment by evgeniy-ADG** [comment]
Ок.

**Comment by AtHoS-HUN** [comment]
Hello!

The first problem:
I disabled complete filtering in this site and added prohardver.hu to https exclusion
However, it filters the page on the adguard

Theoretically, no filter should apply for this site. In reality this is not the case
