### ISSUE TITLE
fastpic.ru - ads in Firefox

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5845]
We fail to block ads in Firefox only, works fine in other browsers. No Assistant in the FF.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28570872-cd683600-7148-11e7-9dd0-0050026d94e0.png)

</details>

Information | value
--- | ---
Operating system: | Windows 10
Browser: | Firefox
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
Adguard DNS: | None
Stealth mode options(Windows) | default
Adguard filters: | 1 2 3 6 14
Ticket ID (if exists): | 1602006

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. Is FF portable?

**Comment by evgeniy-ADG** [comment]
No, it's a regular one. We checked in the office on the Windows machine and managed to reproduce. We'll try again today.

**Comment by Alex-302** [comment]
Any news?
