### ISSUE TITLE
Исключение домена из фильтрации

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#58465]
Здравствуйте,
Дано:
Adguard premium 3.4 (android) + Orbot (в режиме прокси)
Вопрос:
Возможно ли исключить домен из фильтрации совсем? То есть сделать так, чтоб он (домен) шёл в обход адгуарда и прокси?

Вашу базу знаний читал, по поводу конкретно этого решения я не нашёл.

Если всм не сложно, то напишите, пожалуйста, правило, которое я должен добавить. Домен, который я хочу исключить у себя из фильтрации ficbook.net.

P.S: в белый список добавлял, правила исключений создавал, фильтрацию https отключал, но он все равно идёт через прокси, а мне нужно, чтобы он шёл напрямую (в обход прокси)...

**Comment by Alex-302** [comment]
В настройках фильтрации HTTPS есть белый список. Добавьте домен в него(рез `https://` и `/` в конце)
