### ISSUE TITLE
Сайты сомнительного характера

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#58471]
Здравствуйте,
Мошеннические сайты! Прошу заблокировать!

http://wulcan-igrat-besplatno.com/bonus-za-registraciyu-10000-rubley/

https://777originals.net/bonuses/no-deposit/

https://monoslot.com/

https://onlinecasino.kiev.ua/

https://goxbet1.com/

**Comment by Chinaski1** [comment]
Добавили в категорию Gambling.
