### ISSUE TITLE
https://cmacapps.com - Anti-adblock script

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5847]
***Description***:
* **Current behavior**: 

There is anti-Adblock pop-up on https://cmacapps.com
Reproduced on our side (Mac OS)

<details><summary>Screenshot:</summary>

<img width="1105" alt="screen shot 2017-07-25 at 20 40 18" src="https://user-images.githubusercontent.com/28784344/28596448-40a4b050-71a1-11e7-9875-1619f5aa54a3.png">

</details>

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 0, 1, 2, 3, 4, 11, 14

**Comment by Alex-302** [comment]
Added to English filter
```
cmacapps.com##cloudflare-app[app-id="no-adblock"]
```
