### ISSUE TITLE
Mail.ru - ad leftover  - Windows OS

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5848]
***Description***:
* **Current behaviour**: 

There are ads on mail.ru (see the screenshot)
(not reproduced)
When adding filters, the message pop-ups : "Unable to resolve the remote name: 909090909090 ..."

<details><summary>Screenshot:</summary>

![adguard](https://user-images.githubusercontent.com/28784344/28646726-d90e81f2-726b-11e7-979c-ec7902d757b1.jpg)

</details>

<details><summary>Screenshot2:</summary>

![adguard 1](https://user-images.githubusercontent.com/28784344/28646911-d8a7c2d6-726c-11e7-92a8-b811a1914493.jpg)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP 
Adguard filters: | 0, 1, 2, 3, 10, 14, 11
Ticket ID (if exists): | 1601243

**Comment by Alex-302** [comment]
Нужны версии фильтров и скрины сетевых настроек.

**Comment by ypetruk** [comment]
@Alex-302  
Сначала перепроверил все фильтры. Не было фильтра раздражителей, при попытке его добавить выходило уже знакомая ошибка 90909090...
Зашел в настройки сети, там был выставлен ручной прокси 90909090... который видно на приложенном скрине. После того как убрал его, фильтр добавился, но реклама на почте по-прежнему есть.

<details><summary>Screenshot:</summary>

![adg](https://user-images.githubusercontent.com/28784344/28768721-618c2aa2-75e1-11e7-9be5-34d9f83a86b2.jpg)

</details>

<details><summary>Screenshot:</summary>

![adguard](https://user-images.githubusercontent.com/28784344/28768734-72084118-75e1-11e7-8507-dcc6eae071fe.jpg)


</details>

<details><summary>Screenshot:</summary>

![adguard2](https://user-images.githubusercontent.com/28784344/28768746-83314e4e-75e1-11e7-9383-fe9d0cb800cc.jpg)

</details>

**Comment by Alex-302** [comment]
Судя по всему это остатки кряка. Нужно полностью удалить вместе с настройками(если останутся эти каталоги - удалить их вручную `C:\Program Files (x86)\Adguard`  `C:\ProgramData\Adguard` ) и установить заново с официального сайта.

**Comment by Alex-302** [comment]
@ypetruk Нет новостей?

**Comment by ypetruk** [comment]
@Alex-302 переустановил программу, все заработало, спасибо!
