### ISSUE TITLE
smotri.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#585]
@@||ads.adfox.ru/crossdomain.xml$domain=smotri.com
@@||ads.adfox.ru/*/getCode$domain=smotri.com

Добавить в фильтры.

**Comment by Alex-302** [comment]
добавил

**Comment by vbagirov** [comment]
Чел говорит у него снова повторяется через раз. Надо бы проверить.

**Comment by vbagirov** [comment]
smotri.com/live/garey

**Comment by Alex-302** [comment]
Чёто не повторяется. Спроси у него, может ли он при удалённом доступе продемонстрировать?
