### ISSUE TITLE
m.focus.de - Social media widget - iOS

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5851]
***Description***:
* **Current behaviour**: 

Social share buttons and annoyance in bottom left corner: [Adguard Pro for iOS]
http://m.focus.de/finanzen/recht/telefonabzocke-betrueger-prellen-vodafone-kunden-mit-neuer-masche-ein-betroffener-erzaehlt_id_7400821.html

<details><summary>Screenshot:</summary>

![image1](https://user-images.githubusercontent.com/28784344/28649033-9d157570-727a-11e7-9a93-2512111cf851.jpeg)

</details>

***System configuration***

Application version: 1.3.0.100
Device: iPhone
Platform: iOS
OS: 11.0
Optimized enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.25.96 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.48 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.58 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.5 Enabled=YES
ID=6 Name="German filter" Version=1.0.35.81 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.10 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID: 1480792

**Comment by AdamWr** [comment]
Fixed.
