### ISSUE TITLE
nwzonline.de - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5852]
https://www.nwzonline.de/edewecht/friedrichsfehn-wohnen-haus-mit-familiaerer-handschrift_a_32,0,841931451.html

<details><summary>Screenshot:</summary>

![screen shot 2017-07-27 at 8 10 51 am](https://user-images.githubusercontent.com/27292111/28655254-261e2a10-72a3-11e7-9236-4989d49921ee.png)

</details>

***System configuration***

Application version: 1.2.1.71
Device: iPad
Platform: iOS
OS: 10.3.3
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.25.55 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.41 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.37 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.15.83 Enabled=YES
ID=6 Name="German filter" Version=1.0.35.71 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.6 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.63.94 Enabled=YES

Ticket ID: 1577528

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Added:
`@@/ad_bomb/*$image,domain=nwzonline.de`
Please, check the result.
