### ISSUE TITLE
abireg.ru - Missed Ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5853]
https://abireg.ru/

<details><summary>Screenshot:</summary>

![screen shot 2017-07-27 at 10 19 59 am](https://user-images.githubusercontent.com/27292111/28658783-8bdf7310-72b5-11e7-8249-6a03fa560d10.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.2 / 1.4.1
Adguard driver (Windows): | WFP 
Adguard filters: | 1 2 3 4 14 

Ticket ID: 1134321

**Comment by Alex-302** [comment]
Fixed

**Comment by veronikasav** [comment]
Sorry for the reopening.
Two banners are still there.
<details><summary>Screenshot:</summary>

![screen shot 2017-07-27 at 2 54 29 pm](https://user-images.githubusercontent.com/27292111/28669117-8676941e-72db-11e7-8570-6aa5f611f7ee.png)

</details>

**Comment by Alex-302** [comment]
Thanks, fixed.
