### ISSUE TITLE
uol.com.br

### ISSUE THREAD

**Issue by johnmathew2** [AdguardTeam/AdguardFilters#58548]
***Description***:
* **Issue URL**
`https://www.uol.com.br/universa/noticias/redacao/2020/05/24/movel-em-lugar-errado-atrapalha-sono-mas-cristais-e-cores-ajudam-aprenda.htm`

* **Current behaviour**:
Hide ads space on mobile page?
below the word 'publicidade'
also reported in: https://github.com/uBlockOrigin/uAssets/issues/7630

* **Screenshot**:
![image](https://i.imgur.com/Bf07E09.png)
<br/>

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 7.1.1
Browser:                               | Firefox 78.0.1
AdGuard version:                       | uBlock Origin 1.27.10
Filters enabled:                       | AdGuard Mobile Ads, default uBlock, EasyList​​​​​, EasyPrivacy, ​​​​​Fanboy’s Enhanced Tracking List, Peter Lowe’s Ad and tracking server list, FRA: EasyList Liste FR, ​​​spa, por: AdGuard Spanish/Portuguese​.

**Comment by Alex-302** [comment]
Please check for filters update.
