### ISSUE TITLE
https://www.extremetech.com/ - ads, assistant is missing

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5854]
https://www.extremetech.com/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28660227-db6cfd12-72ba-11e7-9fe5-f13c16dfbb08.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS, Windows
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 2 3 6 7 16 104 116

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
