### ISSUE TITLE
maketecheasier.com - Social widgets - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5856]
***Site***: https://www.maketecheasier.com/best-context-menu-editors/
***Description***: Ad leftover. Newsletter box in sidebar and bottom right. Missing social site links in footer.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28666714-dccd5298-72c8-11e7-9ad4-c56ca5d3b4fe.png)

![image](https://user-images.githubusercontent.com/10995998/28666756-0259e97c-72c9-11e7-89e4-2ad4c8ac26d1.png)

![image](https://user-images.githubusercontent.com/10995998/28666768-114fdd6a-72c9-11e7-8e0f-d6ceba46e476.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
