### ISSUE TITLE
gamejolt.com - Anti Adblock Script/Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5858]
***Site***: http://gamejolt.com/games/sevenphotos/271217
***Description***: After click on "Play" the game does not start. Adblock detection or incorrect blocking, not sure though.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28667473-f199d9e6-72cb-11e7-9fc5-85e864b32433.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
