### ISSUE TITLE
tlz.de (and other sites of this news network) - Social widgets - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5859]
***Site***: http://www.tlz.de/startseite/detail/-/specific/Annette-Projahn-erweckt-Modepassage-am-Markt-in-Weimar-zu-neuem-Leben-1882067036
***Description***: Ad leftover and social share leftover. Same for other sites of this network:

http://www.otz.de/startseite/detail/-/specific/3-jaehriges-Kind-wird-bei-Unfall-durch-Autoscheibe-geschleudert-625630886

http://www.thueringer-allgemeine.de/startseite/detail/-/specific/Annette-Projahn-erweckt-Modepassage-am-Markt-in-Weimar-zu-neuem-Leben-1882067027

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28669020-b253e784-72d2-11e7-8880-a98bf1da4c48.png)

![image](https://user-images.githubusercontent.com/10995998/28669032-c1b1ac66-72d2-11e7-9848-82ba6aae9bc3.png)

![image](https://user-images.githubusercontent.com/10995998/28669051-d0f08b52-72d2-11e7-83fb-ae5ef5a6bd23.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
