### ISSUE TITLE
meinanzeiger.de - Social widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5862]
***Site***: http://www.meinanzeiger.de/muehlhausen/kultur/orgelwerke-von-bach-und-dupr-in-der-marienkirche-d71798.html
***Description***: Ad leftover at the top and in right sidebar. Social share after article.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28672240-78c50b6c-72df-11e7-8e2d-4c54fda28b98.png)

![image](https://user-images.githubusercontent.com/10995998/28672257-8c73fcea-72df-11e7-9bd3-a95cf6de9397.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
