### ISSUE TITLE
9monate.de - Social widgets - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5865]
***Site***: https://www.9monate.de/schwangerschaft-geburt/gesund-fit/schwanger-im-sommer-id146848.html
***Description***: Ads and social share widgets at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28673328-88ffa336-72e2-11e7-8b6b-d41503418be4.png)

![image](https://user-images.githubusercontent.com/10995998/28673350-91479c06-72e2-11e7-9710-6a8a9137fafe.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by danidoedel** [comment]
```
@@/ad_bomb/*$image,domain=9monate.de
9monate.de##.socialbar
```

**Comment by AdamWr** [comment]
Fixed.
