### ISSUE TITLE
menshealth.de - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5866]
***Site***: http://www.menshealth.de/
***Description***: Ads.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28673650-63d9fcf4-72e3-11e7-8913-43d1dde8dd08.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by danidoedel** [comment]
`@@/ad_bomb/*$image,domain=menshealth.de`

**Comment by AdamWr** [comment]
Added.
