### ISSUE TITLE
http://www.techadvisor.co.uk/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5867]
Site: http://www.techadvisor.co.uk/how-to/internet/how-stop-flash-crashing-in-chrome-3332967/
Screen: http://s3.postimg.org/ib2glp6wj/screenshot_1.png

**Comment by AdamWr** [comment]
Added to English filter:
`techadvisor.co.uk##.criteo-div`
`@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$domain=techadvisor.co.uk`
The second rule has been added to "unblock" video player.
