### ISSUE TITLE
onwebchange.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#58689]
[https://onwebchange.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://onwebchange.com/)

![cookies](https://user-images.githubusercontent.com/35470489/86545892-1fa87a00-bf08-11ea-90d8-985d2a2cd498.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
Too few visitors.
