### ISSUE TITLE
http://www.akfilmizle.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5872]
Site: http://www.akfilmizle.com/
Note: Click something, you will get a popup.

**Comment by Alex-302** [comment]
Not reproduced.
@AdamWr please check it.

**Comment by AdamWr** [comment]
I also can not reproduce.

**Comment by thislife81** [comment]
Look at here: http://s2.postimg.org/ekgoi2grd/screenshot_35.png
