### ISSUE TITLE
samsung.com

### ISSUE THREAD

**Issue by P0Rtvine** [AdguardTeam/AdguardFilters#58725]
`https://www.samsung.com/ru/support/chat/`

**AdGuard Tracking Protection** - блокирует загрузку чата.

![2020-07-06_164011](https://user-images.githubusercontent.com/57287308/86599499-626d5f00-bfa7-11ea-8165-c15814c95fb0.png)

![2020-07-06_161414](https://user-images.githubusercontent.com/57287308/86599371-39e56500-bfa7-11ea-959a-aa7f9c093514.png)

**uBO 1.28.0
Opera|Stable
Win 10**

**Comment by BlazDT** [comment]
Fixed, update available in about 3 hours.
