### ISSUE TITLE
filmizletekparca.com

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5873]
These rules are same: http://s3.postimg.org/g4c0305rn/screenshot_5.png
Source: https://github.com/AdguardTeam/AdguardFilters/blob/master/TurkishFilter/sections/general_extensions.txt

And I couldn't acces this site. Isn't this site working?

**Comment by AdamWr** [comment]
This website works today.
Removed duplicate rule, thank you.
