### ISSUE TITLE
http://turbo.az/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5874]
Site: http://turbo.az/
Screen1: http://s3.postimg.org/h9628ds8j/screenshot_6.png/ (Now it is site's background.)
Screen2: http://s3.postimg.org/rgt6yj3ub/screenshot_7.png/ (But background has to like this/ So, remove black sections)

This rule helped me to remove that: turbo.az##.bg-bnr, .bg-bnr_left, .abs

**Comment by AdamWr** [comment]
Ok, added to English filter:
`turbo.az##.bg-bnr`
