### ISSUE TITLE
http://www.baliperek.com/ - anti adblock

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#5877]
Hey
have anti anti adblcok site: http://www.baliperek.com/
Operating system: Windows 10 x64
Screenshot:  http://prntscr.com/g18fwy
Browser: Chrome
Adguard version: 6.1.331.1732

filter:
English filter
Annoyances filter
EasyLIstHebrew
adblock warning removal list

**Comment by AdamWr** [comment]
Added to English filter:
`baliperek.com###popup1`
Added to Annoyances and Social media filter:
`baliperek.com#%#AG_onLoad(function() { window.bizpanda = {}; });`
