### ISSUE TITLE
http://shidurim.me/ - Annoyances

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#5878]
Hey
have in site: http://shidurim.me/ http://shidurim.me/ 
all time in the site have  this message: http://prntscr.com/g18jg2
Operating system: Windows 10 x64
Screenshot:  http://prntscr.com/g18jg2
Browser: Chrome
Adguard version: 6.1.331.1732

filter:
English filter
Annoyances filter
EasyLIstHebrew
adblock warning removal list

**Comment by Alex-302** [comment]
http://shidurim.me/ or http://www.baliperek.com/ ?

**Comment by Alex-302** [comment]
I don't understand where it is. I need ***screen*** shot.

**Comment by MrTal** [comment]
scrren shot: http://prntscr.com/g4uogi

**Comment by Alex-302** [comment]
Reproduced. Fixed.
