### ISSUE TITLE
http://www.tvnetil.net/ - Annoyances

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#5879]
Hey
have in site: http://www.tvnetil.net/
all time in the site have  this message: http://prntscr.com/g18kwl
Operating system: Windows 10 x64
Screenshot: http://prntscr.com/g18kwl
Browser: Chrome
Adguard version: 6.1.331.1732

filter:
English filter
Annoyances filter
EasyLIstHebrew
adblock warning removal list

**Comment by Alex-302** [comment]
Please make ***screen*** shot, not only annoying element.
Added to Annoyances filter
```
tvnetil.net##.warnpop
tvnetil.net###backgroundPopup

```
