### ISSUE TITLE
edition.cnn.com - Incorrect blocking - iOS

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5880]
***Description***:
* **Current behavior**: 

Incorrect blocking on iOS:
http://edition.cnn.com/2017/07/27/politics/scaramucci-lizza-quotes-ranked/index.html
Adguard blocks the parts of the website like "news&buzz", "stories and you"
reproduced on our side (Mac OS)
<details><summary>Screenshot with Adguard:</summary>

![screen shot 2017-07-28 at 4 19 50 pm](https://user-images.githubusercontent.com/28784344/28718919-a78fca78-73b0-11e7-90a1-2729293abd5b.png)

</details>

<details><summary>Screenshot without Adguard:</summary>

![screen shot 2017-07-28 at 4 20 03 pm](https://user-images.githubusercontent.com/28784344/28718923-afff3edc-73b0-11e7-92c8-4acfc08f6fb3.png)

</details>

***System configuration***
Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3.2
Optimized enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.25.93 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.47 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.55 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.2 Enabled=YES
ID=6 Name="German filter" Version=1.0.35.81 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.73 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.10 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Information | value
--- | ---
Ticket ID: | 1603995

**Comment by Alex-302** [comment]
outbrain.com widget is blocked as analytics.
User can add:
```
@@||odb.outbrain.com/utils/get?url=$domain=edition.cnn.com
```
