### ISSUE TITLE
Crossword with friends app - Ad leftover - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5882]
***Description***:
* **Current behaviour**: 
There is ad leftover in the Crossword with friends app
https://play.google.com/store/apps/details?id=com.zynga.crosswordswithfriends&hl=ru

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Adguard version: | 2.9.135
Adguard mode (Android): | Proxy(manual)
Filtering quality (Android): | high-speed 
HTTPS filtering (Android): |  On (Default 
Adguard DNS: | None 
Adguard filters: | 2, 3, 4, 14, 11, 15, 211 
Ticket ID (if exists): | 1603947

**Comment by Alex-302** [comment]
I don't see ads
![photo_2017-07-28_21-28-28](https://user-images.githubusercontent.com/8361299/28731223-c0e6c460-73db-11e7-9b9b-ee91412dee98.jpg)

**Comment by ypetruk** [comment]
<details><summary>Screenshot:</summary>

![img_20170728_220452](https://user-images.githubusercontent.com/28784344/28732574-fb4f1f8a-73e0-11e7-96e6-c5478e205c84.jpg)

</details>

**Comment by Alex-302** [comment]
Added
```
||graph.facebook.com^$app=com.zynga.crosswordswithfriends
```
