### ISSUE TITLE
http://www.gktoday.in - Anti AdBlock script - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5883]
***Description***:
* **Current behaviour**: 

Anti AdBlock script on http://www.gktoday.in 
Reproduced on our side (Mac OS)
<details><summary>Screenshot:</summary>

![screen shot 2017-07-28 at 10 07 57 pm](https://user-images.githubusercontent.com/28784344/28732638-3c129268-73e1-11e7-80db-e6b3f947851b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.135
Adguard mode (Android): | Proxy(manua)
Filtering quality (Android): | high-speed
HTTPS filtering (Android): |  On (Default) 
Adguard DNS: | None
Adguard filters: | 2, 3, 4, 11 
Ticket ID (if exists): | 1354655

**Comment by AdamWr** [comment]
Fixed.

**Comment by Alex-302** [comment]
Fixed
