### ISSUE TITLE
stereogum.com - Ad leftover

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5884]
http://www.stereogum.com/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28737884-48dacf02-73f9-11e7-8cd5-55f9df16105c.png)

![image](https://user-images.githubusercontent.com/27292111/28737887-4fc8217a-73f9-11e7-8d3c-95ab5b01672d.png)

</details>

***System configuration***

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3.3
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.10 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.49 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.62 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.12 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID: 1142272

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
