### ISSUE TITLE
appgefahren.de - Social share leftover

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5885]
http://www.appgefahren.de/tests-steam-panic-puzzle-iphone-204847.html

<details><summary>Screenshot:</summary>

![screen shot 2017-07-29 at 5 40 59 am](https://user-images.githubusercontent.com/27292111/28741522-89b9ecca-7420-11e7-81fe-5eff972c649a.png)

</details>

***System configuration***

Device: iPhone
Platform: iOS
OS: 11.0
Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.19 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.54 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.67 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.21 Enabled=YES
ID=6 Name="German filter" Version=1.0.35.84 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID: 1480792

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
