### ISSUE TITLE
itopnews.de - Social share leftover

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5886]
http://www.itopnews.de/2017/07/homepod-erste-firmware-liefert-details-zur-funktionsweise/

<details><summary>Screenshot:</summary>

![screen shot 2017-07-29 at 5 45 45 am](https://user-images.githubusercontent.com/27292111/28741557-3418e068-7421-11e7-860e-f359dc673828.png)

</details>

***System configuration***

Device: iPhone
Platform: iOS
OS: 11.0
Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.19 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.54 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.67 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.21 Enabled=YES
ID=6 Name="German filter" Version=1.0.35.84 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID: 1480792

**Comment by AdamWr** [comment]
Fixed.
