### ISSUE TITLE
sports.betway.com - App banner at the top

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5888]
https://sports.betway.com/de/sports/#page=1

<details><summary>Screenshot:</summary>

![screen shot 2017-07-29 at 5 55 21 am](https://user-images.githubusercontent.com/27292111/28741598-8ad0c7c6-7422-11e7-9eda-dee38b374dd3.png)

</details>

***System configuration***

Device: iPhone
Platform: iOS
OS: 11.0
Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.19 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.54 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.67 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.21 Enabled=YES
ID=6 Name="German filter" Version=1.0.35.84 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/5918#issuecomment-319405566

**Comment by theBeautifier** [comment]
Also a custom app banner and not Apples https://github.com/AdguardTeam/AdguardFilters/issues/5918#issuecomment-319406847

**Comment by Alex-302** [comment]
check
```
sports.betway.com###smartAppBanner
```

**Comment by theBeautifier** [comment]
@Alex-302 Hmm still there with that rule.

**Comment by Alex-302** [comment]
Maybe they are using apple's banner
