### ISSUE TITLE
Вредоносы!

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#58893]
Здравствуйте, 
Прошу заблокировать
http://100linksdvgpn.avafedors.freedomain.thehost.com.ua
http://6gyf.sionas.homelinux.org
http://driveron.ru
http://drivers.byethost16.com
http://files.truetds.icu/rutr/
http://forum.jokke.ru
http://fqevj.kolomnatrud.ru
http://fsfll.fgawudownsyfuf.info
http://geforcesh.preumnoj.ru
http://gsmsignal.ru/common.php

**Comment by Chinaski1** [comment]
Blacklisted!
