### ISSUE TITLE
Сомнительно-опасные сайты

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#58897]
Здравствуйте,
Прошу заблокировать:
http://moiprogrammy.com
https://mwfix.ru
http://nvidiadrivers.net
http://nikask.ru
https://nullthemedownload.com
https://oneindir.com
https://oneprogs.ru/
http://removal-virusguide.com/
http://savow.com/
http://serialms.com/
http://smojem.ru/
http://softkumir.ru/
https://softportal.com (сомнительный)

**Comment by Chinaski1** [comment]
Blacklisted!
