### ISSUE TITLE
Вредоносные сайты!

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#58890]
Здравствуйте,
Мошенники!
https://bookmaker-ratings.com.ua/ru/review/obzor-i-otzyvy-bukmekerskoy-kontory-1xbet-com/ex-bet.ru/
https://1xbet.com.zm/ru/
https://ua1xbet1967.com/
https://1xbet.cr/allgamesentrance/
https://24-bet.ru/bukmekerskaya-kontora-1xbet/
https://1x-bet15590.com/ru/registration/?tag=s_576665m_355c_
https://www.1xbetrevus4.top/
https://1x-bet15590.com/ru/?whn=desctop
https://1xbet.co.nz/ru/
https://1xbet.kz/
https://1xmob1pl.top/
https://1x-bet15390.com/ru/
https://bk.1xbeter.club/?status=accept/

**Comment by Chinaski1** [comment]
Добрый день!

Добавили указанные сайты в ЧС!
