### ISSUE TITLE
4 Same Ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5893]
1.Site: http://www.hdfilmizlebe.net/dursun-cavus-izle.html
Screen: http://s2.postimg.org/h81jeokex/screenshot_32.png

2.Site: http://www.hdizlefilmi.org/riddick-gunlukleri-3-karanliga-hukmet-izle.html
Screen: http://s2.postimg.org/57g3dyd09/screenshot_33.png

3.Site: http://www.fullhdfilmizlebe.net/kostebekgiller-2-golgenin-tilsimi-izle.html
Screen: http://s2.postimg.org/9ypnude1l/screenshot_45.png

4.Site: http://www.hdfilmsaati.com.tr/cilgin-ikili-1-izle.html
Screen: http://s2.postimg.org/d8430u255/screenshot_46.png

**Comment by AdamWr** [comment]
Fixed.

**Comment by thislife81** [comment]
@AdamWr  Please remove these sections totally: http://s1.postimg.org/fhua27g3z/screenshot_95.png

**Comment by thislife81** [comment]
@AdamWr   Please remove these sections totally: http://s1.postimg.org/fhua27g3z/screenshot_95.png

**Comment by AdamWr** [comment]
Ok, added to Turkish filter:
`hdfilmizlebe.net,hdizlefilmi.org,fullhdfilmizlebe.net,hdfilmcehennemi1.org##.leftC + #sidebar > div.sidebarborder:first-child`
Please, check the result.
