### ISSUE TITLE
[AdGuard Home] Ads aren't blocked on Youtube TV

### ISSUE THREAD

**Issue by the4anoni** [AdguardTeam/AdguardFilters#58932]
Hi
Like in topic
Ads aren't blocked on Youtube TV
Samsung Tizen TV
TV is using my AdGuard Home DNS hosted on Raspberry Pi.
I only use AdGuard DNS filter list.
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

One, maybe two months ago with that combo there wasn't single ad on TV.
Now ads are showing up just like without AdGuard Home.

**Comment by Alex-302** [comment]
Hi. Youtube ads cannot be blocked using DNS filtering only.

**Comment by the4anoni** [comment]
> Hi. Youtube ads cannot be blocked using DNS filtering only.
> 
> > One, maybe two months ago with that combo there wasn't single ad on TV.
> 
> Probably you have fresh device, and they do not show ads first time.

No, that TV has 5 years now.

Also Adguard home still works for my chromecast (I've blocked 8.8.8.8 and 8.8.4.4 so it uses router default dns which is my adguard home).
