### ISSUE TITLE
http://hintfilmiizle.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5897]
Site: http://hintfilmiizle.com/
Note: Click something, you will get a popup.

**Comment by AdamWr** [comment]
I can't reproduce.

**Comment by thislife81** [comment]
Look at here: https://app.hyfy.io/v/abwA3Ly8v2U/

**Comment by AdamWr** [comment]
I still can't reproduce.
@Alex-302 could you please check this?

**Comment by Alex-302** [comment]
Reproduced, but I can't block it.
http://hintfilmiizle.com/tema/Yildiz/js/icerik.js
@seanl-adg could you please help?
