### ISSUE TITLE
bing.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#59012]
[https://www.bing.com/images/search?q=aurora&scope=images&form=QBIR](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.bing.com/images/search?q=aurora&scope=images&form=QBIR)

Annoyance after scrolling down a little:

![annoyance](https://user-images.githubusercontent.com/35470489/87169359-3e12ca80-c2a6-11ea-8e1f-ba976a71666f.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
Not reproduced without AdGuard. Please chow HTML code of this popup.

**Comment by adranger** [comment]
>#b_notificationContainer_bop:has(a[href*="microsoft.com/edge"])

![bing](https://user-images.githubusercontent.com/35470489/87200329-ad061880-c2d2-11ea-82f9-1a689d2e9aab.png)

[bing.zip](https://github.com/AdguardTeam/AdguardFilters/files/4905215/bing.zip)

**Comment by Alex-302** [comment]
Ok, added
`bing.com###b_notificationContainer_bop`
