### ISSUE TITLE
alternate.de - Annoyance - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5905]
***Site***: https://www.alternate.de/
***Description***: Cookie notice incorrectly blocked at the top. Newsletter background.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28744681-7178bdf8-7466-11e7-9452-af00d668a4c5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by Alex-302** [comment]
fixed
