### ISSUE TITLE
mindfactory.de - Social widgets

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5906]
***Site***: https://www.mindfactory.de/product_info.php/Intel-Core-i7-7700K-4x-4-20GHz-So-1151-WOF_1132469.html
***Description***: Social sharing.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28744710-ef4a03ea-7466-11e7-9161-1ce44d179b67.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by danidoedel** [comment]
@Alex-302 Seems to have moved:

![image](https://user-images.githubusercontent.com/10995998/28899931-e61bc8dc-77ed-11e7-93ca-03b239472ad1.png)

`mindfactory.de###privacy_social`
