### ISSUE TITLE
gamestar.de - Ad leftover - Ad/Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5908]
***Site***: http://www.gamestar.de/artikel/core-i7-7740x-kaby-lake-x-gegen-core-i7-7700k-und-ryzen,3316257.html
***Description***: Ad leftover and ad/annoyance/self-promo in sidebar

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28744823-73290df8-7469-11e7-97ee-8ba8c89a34e3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Added:
`gamestar.de###rectangle-container-desktop`
but unfortunately I can't reproduce this Morrowind ad.

**Comment by danidoedel** [comment]
Same here. Maybe they removed it or EasyList did fix it. Thank you!
