### ISSUE TITLE
computerbild.de - Social widgets

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5911]
***Site***: http://www.computerbild.de/artikel/cb-News-Panorama-Aldi-Plastiktuete-18593399.html
***Description***: Social widgets.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28748155-c054c5da-74b0-11e7-883d-4f053614e5b9.png)

![image](https://user-images.githubusercontent.com/10995998/28748156-c90d7f3c-74b0-11e7-8686-913bd096cec6.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
