### ISSUE TITLE
heise.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5912]
***Site***: https://www.heise.de/download/product/magical-jelly-bean-keyfinder-36531
***Description***: Newsletter signup.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28748163-feb89bd0-74b0-11e7-9f10-0e5f4c570de2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.

**Comment by BlazDT** [comment]
New ad:

heise.de##.news-teaser-wrapper > .us_hbs

Will add it later.
