### ISSUE TITLE
gamekeyfinder.de - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5913]
***Site***: https://www.gamekeyfinder.de/
***Description***: Ad leftover at the top.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28748174-339eb1c2-74b1-11e7-9bed-091eeb5fb280.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
