### ISSUE TITLE
mk.ru - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5914]
http://www.mk.ru/

Adguard Assistant is missing on this website.

<details><summary>Screenshot:</summary>

![screen shot 2017-07-30 at 6 22 52 pm](https://user-images.githubusercontent.com/27292111/28754721-37db319a-7554-11e7-8368-b4b9f047f47b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.1 / 1.4.1
Adguard driver (Windows): |  TDI
Adguard filters: | 1 2 3 4 14
Ticket ID: | 647089

**Comment by Alex-302** [comment]
Fixed.

> Adguard Assistant is missing on this website.

because I see only browser extension on screensot.
