### ISSUE TITLE
refoweb.nl [anti-adblock]

### ISSUE THREAD

**Issue by kulfoon** [AdguardTeam/AdguardFilters#59147]
https://github.com/easylist/easylist/issues/5707

**Comment by BlazDT** [comment]
Fixed broken cookie in Annoyances filter, sadly I do not see the adblock detection (when I manually add it, it has height of 29 and therefore not triggering it).
AdGuard filters also do not have this generic rule which could trigger it:
`##.adsbox`

Broken cookie message when initially visiting the site, please fix @ryanbr 
Fanboy's Annoyances:
`refoweb.nl#@#.cookieconsent`

**Comment by kulfoon** [comment]
> I do not see the adblock detection

Nor I do anymore, because it was:
- reported in Nano: https://github.com/NanoAdblocker/NanoFilters/issues/530 30 mins earlier,
 - and then fixed in uAssets 20 mins eariler, 

than my issue was created in EasyList: https://github.com/easylist/easylist/issues/5707 

Which means my issue was a duplicate, and now after filters lists updated, the fix got applied and hence no anti-adblock anymore.

But, before I reported my issue in EasyList https://github.com/easylist/easylist/issues/5707 I mistakenly reported it in:
- https://github.com/DandelionSprout/adfilt/issues/82 and
- https://github.com/DandelionSprout/adfilt/issues/83

21 mins eariler than his issue https://github.com/NanoAdblocker/NanoFilters/issues/530 was created.

So it seems that @DandelionSprout read my closed issues and "stole" my anti-adblock report and reported it to Nano, without consulting it with me first, and by such way he put me in an uncomfortable situation - me making a duplicate without knowing it being a duplicate....
