### ISSUE TITLE
samara.rt.ru - Website is blocked

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5915]
***Description***:
* **Current behaviour**: 

http://samara.rt.ru

The website is blocked when Adguard is enabled. 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28754777-4aa47092-7555-11e7-8433-59899f8933b0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1 / 6.2
Adguard driver (Windows): | WFP / TDI
Adguard filters: | 1 2 3 4 14
Ticket ID: | 1531542

**Comment by dzamyshlyayeva** [comment]
the user says the website is working for now, but it some parts are still blocked 

<details>

![image](https://user-images.githubusercontent.com/23372054/28757691-37979dbc-7591-11e7-96a4-35362e7d51a5.png)

</details>

**Comment by Alex-302** [comment]
fixed both

**Comment by Klimfedyakin** [comment]
не вига не работает 
![default](https://user-images.githubusercontent.com/30592575/28773128-0591bb94-75f1-11e7-9036-8e3166bb1c60.png)

**Comment by Alex-302** [comment]
Рано ещё. Правила в фильтры через час попадают.
