### ISSUE TITLE
mobile2.tagesanzeiger.ch - App banner at the top

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5916]
https://mobile2.tagesanzeiger.ch/articles/597c9fcfab5c373061000001

<details><summary>Screenshot:</summary>

![screen shot 2017-07-30 at 8 45 28 pm](https://user-images.githubusercontent.com/27292111/28755640-122cdef8-7568-11e7-8d90-8a0f0853a5d4.png)

</details>

***System configuration***

Application version: 1.3.0.100
Device: iPhone
Platform: iOS
OS: 11.0
Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.27 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.55 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.67 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.21 Enabled=YES
ID=6 Name="German filter" Version=1.0.35.84 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID: 1480792

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is rendered by Safari. It is impossible to hide it at the moment.
