### ISSUE TITLE
mobile2.derbund.ch - App banner at the top and social share bar at the bottom

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5918]
http://mobile2.derbund.ch/articles/597b32a2ab5c3755d5000001

<details><summary>Screenshot:</summary>

![screen shot 2017-07-30 at 8 51 33 pm](https://user-images.githubusercontent.com/27292111/28755685-f7cb5e94-7568-11e7-92bc-cf87469ba1c8.png)

</details>

***System configuration***

Application version: 1.3.0.100
Device: iPhone
Platform: iOS
OS: 11.0
Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.27 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.55 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.67 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.21 Enabled=YES
ID=6 Name="German filter" Version=1.0.35.84 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
Fixed

**Comment by theBeautifier** [comment]
@Alex-302 App banner not fixed?

**Comment by Alex-302** [comment]
We can't hide it. It is not an element of the page.
https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html

**Comment by theBeautifier** [comment]
That's not the app banner. It's a custom one:

```html
<div id="smartAppBanner">
   <div class="iconClose">
      <a href="javascript:void(0);">
      ×
      </a>
   </div>
   <div class="customerLogo">
      <img src="http://is4.mzstatic.com/image/thumb/Purple127/v4/09/e8/73/09e8739e-edbb-cafa-d8be-a0fbcf856c93/source/512x512bb.jpg">
   </div>
   <div class="description">
      <p>Der Bund</p>
      <div class="starRating">
         <span class="NnIcon starIcon "></span>
         <span class="NnIcon starIcon "></span>
         <span class="NnIcon starIcon "></span>
      </div>
      <div class="price">Preis - Gratis</div>
   </div>
   <div class="linkStore">
      <a href="https://itunes.apple.com/ch/app/der-bund/id327212452?mt=8&amp;uo=4" target="_blank">Öffnen</a>
   </div>
</div>
```

**Comment by Alex-302** [comment]
Check
```
mobile2.derbund.ch###smartAppBanner
```

**Comment by theBeautifier** [comment]
@Alex-302 There is then some white leftover at the top: 

![image](https://user-images.githubusercontent.com/28259813/28852314-809c44f2-7728-11e7-9a31-37d41df22107.png)

**Comment by Alex-302** [comment]
Is it possible to select that space as element?
