### ISSUE TITLE
webtoon.bamtoki.com - Missed Ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5920]
https://webtoon.bamtoki.com/%EB%A0%88%EB%93%9C%EC%8A%A4%ED%86%B0

<details><summary>Screenshot:</summary>

![image uploaded from ios](https://user-images.githubusercontent.com/27292111/28755748-770fe5b6-756a-11e7-8be6-3a7de4bae138.jpg)

![image uploaded from ios 1](https://user-images.githubusercontent.com/27292111/28755749-7e5d76d0-756a-11e7-9649-16d7274cb08a.jpg)

</details>

***System configuration***

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3.3

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.24 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.55 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.95 Enabled=YES
ID=101 Name="EasyList" Version=1.0.74.17 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.84.34 Enabled=YES
Annoyances filter

Ticket ID: 1604703

**Comment by Alex-302** [comment]
@seanl-adg 
to Liste-KR
```
webtoon.bamtoki.com##.banners
||webtoon.bamtoki.com/assets/banner/*.gif
```
