### ISSUE TITLE
Yandex.direct - Feature request

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5921]
***Description***:
* **Current behaviour**: 

Пользователь просматривал сегодня код одного сайта и подумал, а почему не фильтровать яндекс по самому слову - яндекс?

Вот, например, код:

<div id="17gfJVR.paFrk"></div>

Взять и заблочить весь блок DIV по маске  
<div id="*">*</div>

Или вот, скажем, такой код:

<script type="text/javascript">
if (DEVICE_TYPE === 'mobile' || (scrwidth > 1058 || (scrwidth < 875 && scrwidth > 728))) { // no vertical tablets and narrow desktops
(function (w, d, n, s, t) {
w[n] = w[n] || ;
var options = {
blockId: (typeof DEVICE_TYPE !== 'undefined' && DEVICE_TYPE === 'mobile') ? "R-65055-17" : "R-A-65055-94",
renderTo: "billboard-896419",
pageNumber: (typeof DEVICE_TYPE !== 'undefined' && DEVICE_TYPE === 'mobile') ? 0 : 0,
async: true
};
if ("number" == typeof w.yaStatId) {
options['statId'] = w.yaStatId;
}
w[n].push(function () {
Ya.Context. AdvManager .render(options);
});
t = d.getElementsByTagName("script")[0];
s = d.createElement("script");
 s.type = "text/javascript";
 s.src = "https://www.kakprosto.ru/2f448fS8cmAVCEQQ-GYKdvf4KYtnpaoO4EZlJQ9Y8OwZeDX3gPcCNRPTRgduHw/";
 s.async = true;
t.parentNode.insertBefore(s, t);
})(this, this.document, "yandexContextAsyncCallbacks");
}
</script> Явно этот скрипт от яндекса не полезен.

Продумать правила, обкатать на бете...

P.S.: кстати, для большей оперативности можно пользовательские правила собирать в облако и по ним делать дополнения к имеющимся правилам (как у антивирусов доверенные файлы)

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Ticket ID (if exists): | 1065108

**Comment by Alex-302** [comment]
Ну можно так попробовать
```
$$script[tag-content="Ya.Context. AdvManager"][max-length="1100"]
```

**Comment by dreamresh** [comment]
Alex-302, спасибо - всё работает прекрасно!
