### ISSUE TITLE
bazr.ru

### ISSUE THREAD

**Issue by MisterAugust** [AdguardTeam/AdguardFilters#5922]
Это я, снова Золотой Парень, снова решил обойти сотни популярных сайтов в Рунете.
Расширение в Google Chrome 60, RU & EN Filters
Тип: Ложноположительное
URL: http://bazr.ru/programmy/znamenitosti/desyatka-luchshih/sezon-1/seriya-1-9
Скриншоты:  http://prntscr.com/g2dl59 / инкогнито режим http://prntscr.com/g2dltn

**Comment by Alex-302** [comment]
У меня не работает из-за региональных ограничений. Нужен рабочий прокси/VPN.

**Comment by Alex-302** [comment]
Проверь снова.
