### ISSUE TITLE
pogoda.yandex.ru

### ISSUE THREAD

**Issue by MisterAugust** [AdguardTeam/AdguardFilters#5923]
# (***You can leave the strings with "[//]:" They will not be added to the issue text)
# (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

# (Опишите проблему)
https://yandex.ru/pogoda/biysk/month?lat=52.5429818&lon=85.2099654
Реклама есть, но не контент
(%url_of_screenshot%)

http://prntscr.com/g2dssq
https://image.prntscr.com/image/6L8XCma_S1aSEHeawUIXcA.png (инкогнито)

**Comment by Alex-302** [comment]
поправил
