### ISSUE TITLE
http://tophotels.ru/

### ISSUE THREAD

**Issue by MisterAugust** [AdguardTeam/AdguardFilters#5924]
URL: http://tophotels.ru/
Cкрин: https://image.prntscr.com/image/DWeMeuasSq6O0qVXULTcXg.png
Тип: пропущенное
По: хром 60 расширение с англ/рус фильтрами

не нравится форма обычная
так лучше для меня

**Comment by Alex-302** [comment]
Поправил. Обновления доступны через час после добавления правил.
