### ISSUE TITLE
Мошеннические домены

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#59246]
Здравствуйте,
Прошу заблокировать
https://1xbet-regs4.top/
https://1xbetlink5.top/
https://1x-bet11530.com/ru/registration?tag=s_576665m_355c_
https://1x-bet11530.com/ru/registration?tag=s_53606m_1234c_
https://1x-allsport.com/
https://1xbet-05.online/

**Comment by Chinaski1** [comment]
Blacklisted!
