### ISSUE TITLE
Мошеннические ресурсы!

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#59252]
Здравствуйте,
Прошу заблокировать
https://1x-bet.com/
https://1x-bet11530.com/ru/registration?tag=s_442341m_1234c_
https://1xbet-bonuses.com/
https://1x-bet11530.com/ru/registration?tag=s_442341m_1234c_
https://1bet.su/
https://1x-bet11530.com/ru/registration?tag=s_442341m_1234c_

**Comment by Chinaski1** [comment]
Blacklisted!
