### ISSUE TITLE
Мошеннические домены!

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#59254]
Здравствуйте,
Прошу заблокировать
https://1xbkbet5.com/
https://1xbet-xbeth.top
https://1xbkbet-4.com/ru/
https://1xbetjap.com/ru/
https://sportstavki.online/1xbet-bukmekerskaya-kontora-mobile
https://1x-bet11530.com/ru/registration?tag=s_442341m_1234c_

**Comment by Chinaski1** [comment]
Blacklisted!
