### ISSUE TITLE
Мошеннические ресурсы!

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#59250]
Здравствуйте,
Прошу заблокировать
https://1xbet-b.club/
https://1x-bet93432.world/ru/
https://1x-bet11530.com/ru/registration?tag=s_53606m_1234c_
https://1xbetmart4.top/
https://1xbet-4m.site/
https://1x-bet11530.com/ru/registration?tag=s_442341m_1234c_

**Comment by Chinaski1** [comment]
Blacklisted!
