### ISSUE TITLE
Google/FB account Blocking - iOS

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#5925]
The user can not enter facebook and google accounts in order to log in to Trustpilot 

The user found that "English filter" and "useful advertising filter" may have some problems.
1. turned off the English filter, the site appeared on the ad, open the English filter, refresh, advertising gone, and then turn off the English filter, refresh, advertising and out. I do not know why I see the Chinese fiction website, advertising will be related to the English filter.
2. opened the "useful ad filter", the original no advertising site (at this time the English filter is open), there has been advertising. I turn off the useful ad filter, refresh, the ad is gone.
3. Several other filters I tried, temporarily did not find any problems.

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3.3
Optimazed enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.23.53 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.54 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.67 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.20 Enabled=YES
ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.10 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.65 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.95 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.84.77 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.3.47 Enabled=YES

Ticket ID: 1593788

**Comment by Alex-302** [comment]
I need detailed description with example of the site, with screenshots.

**Comment by Alex-302** [comment]
Checked Trustpilot - not reproduced.

**Comment by veronikasav** [comment]
Steps to reproduce the issue:

1. First, close the English filter
This time, the Chinese fiction website appeared advertising
It is obvious that the ad appears below the page.
Then I opened the English filter.
And then open the same page
Look, the ad is gone! So I also wonder why I opened the Chinese fiction website, advertising will be related to the English filter.
2. On the "useful advertising filter" problem, I just tried, can not reproduce the problem, do not know the specific reasons.

<details>

<img width="430" alt="screen shot 2017-08-03 at 5 28 03 am" src="https://user-images.githubusercontent.com/27292111/28903300-d20ee9b8-780c-11e7-9078-64898137a945.png">
<img width="422" alt="screen shot 2017-08-03 at 5 28 13 am" src="https://user-images.githubusercontent.com/27292111/28903312-da7f975a-780c-11e7-8bde-d66ca6a282c3.png">
<img width="422" alt="screen shot 2017-08-03 at 5 28 24 am" src="https://user-images.githubusercontent.com/27292111/28903316-e373b71a-780c-11e7-9fe0-1970be9b0a70.png">
<img width="425" alt="screen shot 2017-08-03 at 5 28 34 am" src="https://user-images.githubusercontent.com/27292111/28903320-e7e8892e-780c-11e7-9c9c-9a4eb2693865.png">
<img width="425" alt="screen shot 2017-08-03 at 5 28 45 am" src="https://user-images.githubusercontent.com/27292111/28903324-ec454a5c-780c-11e7-8954-c6ca2599dec2.png">
<img width="426" alt="screen shot 2017-08-03 at 5 28 55 am" src="https://user-images.githubusercontent.com/27292111/28903329-f0e129c8-780c-11e7-854a-f1b2f97bb10e.png">

</details>

**Comment by Alex-302** [comment]
English filter is the main filter, required in all cases.
