### ISSUE TITLE
Premium ADS/BANNERS on almost 700 pornsites NSFW

### ISSUE THREAD

**Issue by kulfoon** [AdguardTeam/AdguardFilters#59269]
https://github.com/easylist/easylist/issues/5391 maybe AdGuard will fix it before world ends.

**Comment by Alex-302** [comment]
Where these sites can be found except publicwww? Similar sites I saw in clickunder ads.

**Comment by Alex-302** [comment]
Also all these sites have few visitors.

**Comment by kulfoon** [comment]
> Where these sites can be found except publicwww?

Just where most of all other sites...in google and in other porn sites, doing typical google search for porn phrases like every human do searching for any content in google, for example, following google porn phrases:
- `https://www.google.pl/search?q=forced+femdom` shows `http://www.forcedfemdomtgp.com/` (from https://github.com/easylist/easylist/issues/5391#issue-623671222) at 15th place (2nd page of the google results)
- `https://www.google.pl/search?q=shemale+models` shows `http://www.allshemalemodels.com/` (from https://github.com/easylist/easylist/issues/5391#issuecomment-633199856)  at 22th place (3rd page of google results)

Then after I found some of them, I checked publicwww too see how many of them exist.

Also apart from google, they can be found on some other porn sites (including higher ranked porn sites) as well :

<details not-open>
<summary>screenshoot</summary>


`https://ahrefs.com/backlink-checker`
![all](https://user-images.githubusercontent.com/43844449/87556994-abb06380-c6b7-11ea-91b4-3da7b9eb48ef.gif)
</details>

> Also all these sites have few visitors.

Perhaps, however how did you measured that, could you provide your link to a page rank / visitors measurement website (like `https://checkpagerank.net/check-page-rank.php`) with which you checked it, also what is the limit / number of the page rank / visitors result, below which a website will not be added to AdGuard filters.

**Comment by Alex-302** [comment]
> following google porn phrases:

Not sure, if users will skip world famous sites and will choose random site. If `the site's domain` = `your detailed search request`, it is a content farm in ~100% cases. They can have high rank because not all users using ad blockers.

> they can be found on some other porn sites

as ads? Or on the similar sites?

> Perhaps, however how did you measured that,

https://www.similarweb.com/
https://a.pr-cy.ru/
and alexa.com

**Comment by kulfoon** [comment]
1 ████████████████████████████████████████████████████████████████████████

> Not sure, if users will skip world famous sites and will choose random site.

Such farm pornsites, apart from being farm pornsites, often lead to unique valid legitimate porn pics galleries, so I just don't know what is AdGuard's policy regarding such farm pornsites, so just filled an issue.

> If `the site's domain` = `your detailed search request`, it is a content farm in ~100% cases. They can have high rank because not all users using ad blockers.

I don't deny that they are links farm, yes they are, I myself already wrote about it in my original comment https://github.com/easylist/easylist/issues/5391#issue-623671222:

> ### Premium ADS/BANNERS on almost 300 link farm pornsites

> By the way all the websites are [LINK FARMS](https://en.wikipedia.org/wiki/Link_farm).

I just don't know what is AdGuard policy regarding such farm websites or not, especially given the fact such farm pornsites also lead to unique valid legitimate porn pics galleries.

2 ████████████████████████████████████████████████████████████████████████

> > they can be found on some other porn sites
>
> as ads? Or on the similar sites?

As links (for ex.- in the footer), on the similiar sites, you can check it yourself - for example:
`http://www.allshemalemodels.com/` in https://ahrefs.com/backlink-checker
From the referring sites, one of them `http://trannyxxxvids.com/` have a link to 
`www.allshemalemodels.com/movies.shtml` in the footer:
![111](https://user-images.githubusercontent.com/43844449/87666977-e2df4d00-c769-11ea-9053-99f172059147.gif)

Haven't look too much so far, so I don't know whether some links are in form of ads, but you can check it yourself in https://ahrefs.com/backlink-checker.

3 ████████████████████████████████████████████████████████████████████████


> > Perhaps, however how did you measured that,

> https://www.similarweb.com/

It says both websites not found in database:
https://www.similarweb.com/website/forcedfemdomtgp.com/
https://www.similarweb.com/website/allshemalemodels.com/

> https://a.pr-cy.ru/

Unable to check coz it requires to login.

> and alexa.com

Worked:
https://www.alexa.com/siteinfo/allshemalemodels.com#section_traffic ==> This site ranks:....#`3,118,886` 
https://www.alexa.com/siteinfo/forcedfemdomtgp.com#section_traffic ==>  This site ranks: #`10,689,102`

So it seems when a website is below 3 000 000 alexa rank, then AdGuard considers whether it's worth adding to AdGuard filters, however how this relate to AdGuard advertised as:
https://github.com/AdguardTeam/AdguardFilters#the-place-where-ads-are-actually-blocked

> The place where ads are actually blocked

**Comment by Alex-302** [comment]
> As links (for ex.- in the footer), on the similiar sites, you can check it yourself - for example:
http://www.allshemalemodels.com/ in https://ahrefs.com/backlink-checker
From the referring sites, example one of them http://trannyxxxvids.com/ have a link to
www.allshemalemodels.com/movies.shtml in the footer:

one farm has a link to another farm. I checked some sites - usually you need visit few redirects to another site before you will be able to see content(not related to initial search request)


> So it seems when a website is below 3 000 000 alexa rank, then AdGuard considers whether it's worth adding to AdGuard filters, however how this relate to AdGuard advertised as:

Rank and visitors number are not the main criterion, and sometimes we add the rules for useful sites. Porn farms are useless. I'm sure no one user uses these sites for searching of content.

**Comment by Alex-302** [comment]
Ok, I will add three that rules, but not more.

**Comment by kulfoon** [comment]
> usually you need visit few redirects to another site before you will be able to see content(not related to initial search request) Porn farms are useless. I'm sure no one user uses these sites for searching of content.

Bullshit, but this is what it looks like when someone has no knowledge / experience in something but speaks about it...there are addons to easily skip redirects, like this one https://addons.mozilla.org/pl/firefox/addon/skip-redirect/ which make browsing such pornsites like browsing normal pornsites, you click at thumbnail image and you directly land onto the gallery, therefore with such addon installed, they are useful like regular pornsites, especially given the fact of being reasonably high placed in google search results, so one can visit them just like all other regular pornsites.

> Rank and visitors number are not the main criterion

I have nowhere written that they are, but they still are one of them.

**Comment by kulfoon** [comment]
@AdamWr

**Comment by Alex-302** [comment]
> someone has no knowledge / experience in something (eg. porn browsing)

they using pornhub etc for their 15 seconds
