### ISSUE TITLE
nordvpn.com - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5927]
***Site***: https://nordvpn.com/de/
***Description***: Links to their facebook and twitter page are blocked. Live chat not working.

<details>
<summary>Screenshot</summary>

**https://nordvpn.com/de/:**

![image](https://user-images.githubusercontent.com/10995998/28776245-19a8c406-75f6-11e7-942a-a8ac2c92b4bc.png)

**https://nordvpn.com/de/contact-us/:**

![image](https://user-images.githubusercontent.com/10995998/28776299-56aee420-75f6-11e7-958b-818f4076a08c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
