### ISSUE TITLE
Остатки элементов

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#59284]
Здравствуйте,
Проблемный сайт:
https://sdelaysam-svoimirukami.ru/
Скриншот (исчезнет через месяц):
https://i.ibb.co/xzTnb2V/Screenshot-20200714-144723.jpg
Фильтры:
AdGuard Base, AdGuard Mobile Ads, Peter Lowe's Blocklist, EasyList, AdGuard Russian, AdGuard Tracking Protection, AdGuard Social Media, I don't care about cookies, NoCoin Filter List, Spam404, Malware Domains Blocklist

**Comment by Sergey-Lyapin** [comment]
Добрый день,

Проверил на 3х разных устройствах - проблема не воспроизводится, у меня этот элемент не блокируется (и не должен, так как это ссылки на их собственные соцсети)
