### ISSUE TITLE
themeslide.com - Ad leftover - Social widgets - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5929]
***Site***: https://www.themeslide.com/
***Description***: Adblock detection. Ad leftover. Social share widget blocks download links

<details>
<summary>Screenshot</summary>

**https://www.themeslide.com/:**

![image](https://user-images.githubusercontent.com/10995998/28776586-80fdd8a2-75f7-11e7-9c6e-3277ed6f27a8.png)

![image](https://user-images.githubusercontent.com/10995998/28776720-1b49aa4e-75f8-11e7-9602-bf2765c26453.png)

**https://www.themeslide.com/zox-news-professional-wordpress-news-magazine-theme/:**

![image](https://user-images.githubusercontent.com/10995998/28776725-253642c4-75f8-11e7-9061-88db54f8be4c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by Alex-302** [comment]
Fixed
