### ISSUE TITLE
am-play.de - Ad leftover - Social widgets - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5930]
***Site***: http://www.am-play.de/castleclash/
***Description***: Ad leftover. Social widget leftover. Links to their facebook, twitter page etc. incorrectly blocked.

<details>
<summary>Screenshot</summary>

**http://www.am-play.de/castleclash/:**

![image](https://user-images.githubusercontent.com/10995998/28778606-575f166a-7600-11e7-9e51-5b3fcba3fbab.png)

**http://www.am-play.de/rudolph/:**

![image](https://user-images.githubusercontent.com/10995998/28778688-b6ff8578-7600-11e7-87a9-4066533fd850.png)

![image](https://user-images.githubusercontent.com/10995998/28778737-e7dddc80-7600-11e7-919b-a772c52b7dcf.png)

**These links are missing:**

![image](https://user-images.githubusercontent.com/10995998/28779169-7f6a9790-7602-11e7-8b82-a65a167a2af0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by Alex-302** [comment]
Fixed
