### ISSUE TITLE
http://www.speedrun.com/ - Ad leftover 

### ISSUE THREAD

**Issue by dzamyshlyayeva** [AdguardTeam/AdguardFilters#5933]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: http://www.speedrun.com/ - Ad leftover 

<details>

![image](https://user-images.githubusercontent.com/23372054/28782244-4ada04da-7615-11e7-949e-07dbf4f6e629.png)

</details>

***System configuration***

Application version: 1.3.0.100
Device: iPhone
Platform: iOS
OS: 11.0
Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.27 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.55 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.67 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.21 Enabled=YES
ID=6 Name="German filter" Version=1.0.35.84 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
Fixed.
