### ISSUE TITLE
Missed ad in the app Hornet

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5936]
https://appsto.re/ru/NL-KB.i

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28783486-26b066d6-7619-11e7-8daf-f0bc0900adf7.png)

</details>

***System configuration***

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 11.0
Optimazed enabled: YES

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.37 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.55 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.67 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.22 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.54.68 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.65 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.11 Enabled=YES
ID=101 Name="EasyList" Version=1.0.74.34 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES
ID=213 Name="RU AdList: BitBlock" Version=1.0.81.52 Enabled=YES

Ticket ID: 1605415

**Comment by Alex-302** [comment]
For user's black list:
```
graph.facebook.com
```
It will break Facebook.
