### ISSUE TITLE
phonearena.com -- anti-adblock script

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#5938]
It seems to be using an AD reinjection technique both on desktop and on Android.

Reinjects a banner on the main page.

**Comment by AdamWr** [comment]
It seems they use `PanamaClient WebRTC`, added to English filter:
`phonearena.com#%#Object.defineProperty(window,'adonisConnType',{get:function(){},set:function(){throw'Adguard: stopped a script execution.'}});`
