### ISSUE TITLE
podimo.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#59403]
[https://podimo.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://podimo.com/)

![cookies](https://user-images.githubusercontent.com/35470489/87622427-7dec0e80-c6f9-11ea-8bfe-bae385072eb2.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
Required a lot of CSS rules.
