### ISSUE TITLE
Shazam app ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#5942]
Source report:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=63686667

Blocking `||graph.facebook.com` didn't help, there should be something else.

**Comment by AdamWr** [comment]
I understand correctly that this ads are only sometimes?
I installed this app, configured, but I can't reproduce these ads yet, I see only ad leftover which I guess is built in app.
Any steps/hints to reproduce?
<details><summary>Screenshots</summary>

![screenshot_2017-08-01-14-10-41](https://user-images.githubusercontent.com/29142494/28828820-38b31518-76d2-11e7-89ba-b715b283c564.png)
![screenshot_2017-08-01-15-52-35](https://user-images.githubusercontent.com/29142494/28828828-3b8addfc-76d2-11e7-81ac-ba41982d7ad3.png)

</details>

**Comment by Alex-302** [comment]
I don't see that ad, even without https filtering with added `||graph.facebook.com`

**Comment by ameshkov** [comment]
Hm, what ad networks do you see in the filtering log? I wonder, maybe ads are simply cached in the case of that user?

**Comment by Alex-302** [comment]
Google and FB ads.

**Comment by ameshkov** [comment]
Can we add `||graph.facebook.com^$app=...` rule without breaking the app functionality?

**Comment by Alex-302** [comment]
FB auth will be broken.

**Comment by ameshkov** [comment]
Meh, let's keep it as is then..
