### ISSUE TITLE
https://dailyuploads.net/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5945]
Site: https://dailyuploads.net/vabte9ctwk8t

Screen1: http://postimg.org/image/axxblbfij/ (Choose this section)
Screen2: http://s1.postimg.org/p71jh4jf3/screenshot_85.png (Then choose this)
Screen3: http://s1.postimg.org/527zbnplb/screenshot_86.png (Remove this)

**Comment by AdamWr** [comment]
Fixed.
