### ISSUE TITLE
fox-fan.ru - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#5946]
![image](https://user-images.githubusercontent.com/22892774/28824797-737c9468-76cc-11e7-9168-103ba6013be1.png)

***Steps to reproduce the problem***:

go to fox-fan.ru and its subdomains

familyguy.fox-fan.ru
americandad.fox-fan.ru 
simpsons.fox-fan.ru etc.

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1....1732
Adguard filters: | 1 2 3 4 5 14
Ticket ID: | 1335772

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added
```
bobsburgers.fox-fan.ru##.adb
@@-fan.ru/images/ad.jpg$image,domain=cc-fan.ru|cn-fan.ru|fox-fan.ru
```

**Comment by veronikasav** [comment]
Sorry for the reopening. Is it possible to block this banner under the video player too?

<details>

<img width="664" alt="screen shot 2017-08-03 at 3 05 24 am" src="https://user-images.githubusercontent.com/27292111/28900266-aa2dc8ce-77f8-11e7-80d3-a855fbb607e3.png">

</details>

**Comment by Alex-302** [comment]
Sure

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
cc-fan.ru,cn-fan.ru,fox-fan.ru###Shop
```
