### ISSUE TITLE
https://www.softonic.com/ is broken with several filters

### ISSUE THREAD

**Issue by Jose1971AB** [AdguardTeam/AdguardFilters#59462]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
Hey, guys, good afternoon.

First of all excuse my English level, I'm with the help of the google translator. I am a basic user, I exposed my problem in https://github.com/uBlockOrigin/uAssets/issues/ and they sent me here, so here I am, to see who can help me. I would also like to apologize if I don't use correctly the template that you indicate in the text box of the message.

**If this isn't where I should be exposing my problem, I would beg you to tell me where I should do it**

***Description***:

After several tests I have verified that **https://www.softonic.com/** breaks with several filters.

* **Current behaviour**: 
The filters that break **https://www.softonic.com** are:

```
AdGuard Annoyances
Peter Lowe´s Ad and tracking server list
https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
Fanboy+Easylist-Merged Complete List
I don´t care about cookies
StevenBlack/hosts
```

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

**With the full settings it looks like this -->**
![image](https://user-images.githubusercontent.com/44229110/87713174-1346db80-c7aa-11ea-9fc5-8935039f0151.png)
</details><br/>

* **Expected behaviour**: 

Well, basically I was deactivating the filters that I have mentioned one by one, refreshing the page and testing until I checked that those are the ones that break [https://www.softonic.com/]. I mean...

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

**If I turn off the filters I describe, it looks like this -->**
![image](https://user-images.githubusercontent.com/44229110/87714036-7422e380-c7ab-11ea-9eda-1a4539de7f5b.png)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**
Note: Sorry to put a screenshot, but I don't know how to write down the filters enabled in the box below

![image](https://user-images.githubusercontent.com/44229110/87717074-1fce3280-c7b0-11ea-86cc-afc484d459c2.PNG)

![image](https://user-images.githubusercontent.com/44229110/87717318-7b98bb80-c7b0-11ea-97c6-5346b40a6ee8.PNG)

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | ?
Browser:                               | Firefox 64-bit 78.0.2
AdGuard version:                       | uBlock Origin
Filters enabled:                       | 
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
**Note:** **I don't want to get rid of any of them**, since they work well in most of the pages I visit. **So would it be possible to fix it without modifying my uBlock settings?... I would appreciate it.**

Greetings and thanks in advance.

**Comment by BlazDT** [comment]
Not reproduced on AdGuard Chrome Extension. Please check @AdguardTeam/filters-maintainers

**Comment by Jose1971AB** [comment]
Hello @BlazDT buenas tardes
> 
> Not reproduced on AdGuard Chrome Extension. Please check @AdguardTeam/filters-maintainers

It gives error the page friend ... sorry but I do not understand well what you mean, what I have to check?...

I have Firefox, not Chrome and I use uBlock Origins

Greetings

**Comment by zloyden** [comment]
> sorry but I do not understand well what you mean, what I have to check?...

This mention is for our team only. Are you sure about `AdGuard Annoyances`? I don't see incorect blocking with our filters and US IP (this screenshot from other browser but on Firefox I have the same).
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/87781173-df66c700-c838-11ea-9858-8f66cb57e79d.png)
</details><br/>

**Comment by Alex-302** [comment]
Also not reproduced in AdGuard and uBO(without custom filters).

**Comment by Jose1971AB** [comment]
NOOOO... SORRY!!!... I DIDN'T CLOSE, IT WAS A CONFUSION, SORRY...

**Comment by Jose1971AB** [comment]
Hello @zloyden @Alex-302 good afternoon

> Are you sure about `AdGuard Annoyances`? I don't see incorrect blocking with our filters and US IP (this screenshot from other browser but on Firefox I have the same).
> Also try to disable third-party filters and your own rules, then enable them one by one to find a conflict.

**Still failing friends**.

I'm not from the US, I'm from Spain, **maybe that's why not?... no idea**

I'm a very basic user so I can only subscribe filters and block an item with the context menu, so I don't have any added rules (I don't know how to do it).

The only thing I have done is to disable the third party filters and the ones in the My filters tab, nothing else. **I send screenshots**.

**uBlock (with the third party filters disabled and without the filters of the My filters tab)**

![1](https://user-images.githubusercontent.com/44229110/87857095-50cf7400-c924-11ea-80d1-1e474b43d63a.PNG)

![6](https://user-images.githubusercontent.com/44229110/87857125-870cf380-c924-11ea-9c47-e31fcd7555d5.PNG)

![5](https://user-images.githubusercontent.com/44229110/87857116-752b5080-c924-11ea-9a3b-8107daae6552.PNG)

**Capture from https://www.softonic.com/ (with third party filters turned off and without the My Filters tab)**
![4](https://user-images.githubusercontent.com/44229110/87857158-d6532400-c924-11ea-8e86-4db9334a99e3.png)

**Capture from https://www.softonic.com/ (with AdGuard Annoyances turned off, third party filters turned off, and without the My Filters tab)**

![X](https://user-images.githubusercontent.com/44229110/87857812-da357500-c929-11ea-8515-3b2894228b20.PNG)

If @Alex-302 doesn't fail, I don't know what can happen.

According to what you say that could prove conflicts with other filters, in the exposition of my problem I indicated all the filters that proved the failure.

However, if I disable all the filters I have cited and leave AdGuard Annoyances, it also proves the fault. This is why I don't really understand what is happening.

Greetings friends

**Comment by BlazDT** [comment]
Reproduced with Spanish VPN, fixed. Update available in about 3 hours.
