### ISSUE TITLE
psd-tutorials.de - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5947]
***Site***: https://www.psd-tutorials.de/
***Description***: Newsletter overlay (opens after some time on the site). Ad leftover in log in sidebar. Newsletter box. Ad leftover at the end of the site.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28829685-e283390e-76d4-11e7-99e5-50b46c33ab12.png)

![image](https://user-images.githubusercontent.com/10995998/28829759-29c179c0-76d5-11e7-9f38-838b568a1cfe.png)

![image](https://user-images.githubusercontent.com/10995998/28829783-3a1ad60e-76d5-11e7-9872-72b9f4989fb1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
