### ISSUE TITLE
Questions about teletoonplus.pl

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#5949]
When will fix be ? With DNS/without DNS Android and Browser Extension, AG is detected and blocked by teletoonplus.pl . I added rules @@||s1-player5.cdntvn.pl and @@||tvn.adocean.pl - work with miniminiplus.pl but don't work with teletoonplus.pl (base the same rules). I added this rules, because sometimes video was unavaible on miniminiplus.pl . But any working with teletoonplus.pl . If I add all site on whitelist, I unblock all ads.

**Comment by Alex-302** [comment]
Please provide direct link.

**Comment by seba2282** [comment]
Example : https://www.teletoonplus.pl/filmy/pokaz/idealny-dzien-na-zabawe-my-little-pony-equestria-girls-rainbow-rocks

**Comment by Alex-302** [comment]
Filters, platform, browser?
Please fill the template.

**Comment by seba2282** [comment]
Browsers : MS Edge with extension and Android Chrome Mobile + Adguard apk (DNS and HTTPS Filtering. 
Filters : all without (reek, adblock protector and acceptable ads)
Rules : @@||s1-player5.cdntvn.pl and @@||tvn.adocean.pl

**Comment by Alex-302** [comment]
Do you use 75 filters?

**Comment by Alex-302** [comment]
Please check:
```
@@||teletoonplus.pl^$generichide
@@||tvn.adocean.pl^$domain=teletoonplus.pl
```
Which rule blocks `s1-player5.cdntvn.pl`?

**Comment by seba2282** [comment]
I don't know how many filters are in AG products. I have only turn off acceptable ads, reek killer and adblock protector (not supported AG). But I tried too with only default filters after instalation AG and had the same.

**Comment by seba2282** [comment]
s1-player5.cdntvn.pl - I have as allowed.

**Comment by seba2282** [comment]
Now works. How long. I will test and will inform. Thank you.

**Comment by Alex-302** [comment]
Added
```
@@||teletoonplus.pl^$generichide
@@||tvn.adocean.pl^$domain=teletoonplus.pl
```

**Comment by Alex-302** [comment]
@AdamWr 
please add these rules:
```
@@||teletoonplus.pl^$generichide
@@||tvn.adocean.pl^$domain=teletoonplus.pl
```

**Comment by AdamWr** [comment]
Done.
