### ISSUE TITLE
windscribe.com

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#5950]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
As reported by user from our forum:

> В русском фильтре есть ##.affiliate
> который скрывает полезную информацию на этих страницах:
> https://windscribe.com/referafriend
> https://windscribe.com/affiliate

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/14153331/28844319-ebb3ae0e-770c-11e7-8ff3-b95f2c9e8b19.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/14153331/28844309-dd2be612-770c-11e7-8fc4-8e9a30011a92.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome/FF
Adguard version: | 6.2.379
Adguard driver (Windows): | WFP
Adguard DNS: | None 
Stealth mode options(Windows) | none
Adguard filters: | Russian
Ticket ID (if exists): | 1241781

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Поправил.
