### ISSUE TITLE
prevention.com - Annoyance - Ad leftover - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5951]
***Site***: http://www.prevention.com/
***Description***: Banner leftover at the top. Newsletter subscription. Ad.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28848626-f9606810-7713-11e7-9d45-53d0dd16d89f.png)

![image](https://user-images.githubusercontent.com/10995998/28848647-094dba3e-7714-11e7-9a85-7a9703fed1e7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by Alex-302** [comment]
Fixed.
