### ISSUE TITLE
womenshealthmag.com - Annoyance - Ad leftover - Social widgets

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5952]
***Site***: http://www.womenshealthmag.com/
***Description***: Banner leftover at the top. Newsletter subscription. Social widgets.

<details>
<summary>Screenshot</summary>

**http://www.womenshealthmag.com/beauty/best-lipstick-according-to-your-zodiac-sign:**

![image](https://user-images.githubusercontent.com/10995998/28848716-48979e62-7714-11e7-96a9-29c5917b3ece.png)

**http://www.womenshealthmag.com/:**

![image](https://user-images.githubusercontent.com/10995998/28848748-6946d1be-7714-11e7-914c-72f46294613c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by seanl-adg** [comment]
Fixed

**Comment by danidoedel** [comment]
@seanl-adg Banner at the top not fixed...
