### ISSUE TITLE
menshealth.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5953]
***Site***: http://www.menshealth.com/
***Description***: Banner leftover at the top. Ad leftover.

<details>
<summary>Screenshot</summary>

**http://www.menshealth.com/:**

![image](https://user-images.githubusercontent.com/10995998/28848821-abc95232-7714-11e7-8939-b77a9cb6fbaf.png)

![image](https://user-images.githubusercontent.com/10995998/28848842-b9da218a-7714-11e7-94e9-38b860dd4f01.png)

**http://www.menshealth.com/guy-wisdom/survival-skills-tips-bear-attack-lightning-tornado:**

![image](https://user-images.githubusercontent.com/10995998/28848876-d8a6d4be-7714-11e7-965c-5c0489d45ae1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
