### ISSUE TITLE
generatorlinkpremium.com - Ad leftover - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5957]
***Site***: https://generatorlinkpremium.com/
***Description***: Download link not working because of adblock detection (Test with: https://mega.nz/#!1K430Bia!MKdpptHqDMQPuHcL5Ch9z3MNfDeDnlM5sSvgmKieIU0). Ad leftovers at the sides.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28849392-1a3db5f8-7717-11e7-8a15-0f5be407f02c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
