### ISSUE TITLE
seasonvar.ru - Incorrect blocking

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5958]
http://seasonvar.ru/?mod=pause

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28851232-e37f0db0-7729-11e7-9be6-e254f5bf55b0.png)

</details>

***System configuration***

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 11.0
Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.21.80 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.55 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.67 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.21 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.54.68 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.49 Enabled=YES

Ticket ID: 1104812

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
На ios отступ не убрать, если речь про него.
