### ISSUE TITLE
pinetools.com - Cookie notice at the bottom

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5959]
http://pinetools.com/invert-image-colors

<details><summary>Screenshot:</summary>

![screen shot 2017-08-02 at 3 45 36 am](https://user-images.githubusercontent.com/27292111/28852877-2658f384-7735-11e7-9914-39a1654ddf8a.png)

</details>

***System configuration***

Application version: 1.3.0.100
Device: iPhone
Platform: iOS
OS: 11.0
Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.49 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.60 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.70 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.29 Enabled=YES
ID=6 Name="German filter" Version=1.0.35.89 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.15 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID: 1480792

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
