### ISSUE TITLE
https://www.radugaskidok.ru/ - ads, annoyances

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5960]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

 **Current behavior**: a few banners on the [site ](https://www.radugaskidok.ru/)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28865233-dc22778e-7777-11e7-8a77-13fcc7f9ac80.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Adguard version: | The latest release
Adguard driver (Windows): | WFP 
Adguard DNS: |  Default
Stealth mode options(Windows) | default
Adguard filters: | Russian, English, Annoyances, Spyware, Social
Ticket ID (if exists): | 1597303

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
