### ISSUE TITLE
https://kino.mail.ru/ - myTarget ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5961]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behavior**: 
Banners from [myTarget](https://sales.mail.ru/en/mytarget/) on the right side. Basic filters, nothing exotic. Not reproduced on our side.
 
[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28865515-db1a37ae-7778-11e7-92d1-e12706a5763e.png)

![image](https://user-images.githubusercontent.com/15856304/28865861-fc9e40fe-7779-11e7-958a-37500c892c7a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Microsoft Windows NT 6.1.7601 Service Pack 1
Browser: | 
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | TDI
Adguard DNS: | None
Stealth mode options(Windows) | basic options
Adguard filters: | 1 2 3 4 14
Ticket ID (if exists): | 630452

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. Please ask for the saved page with resources or HAR.

**Comment by Alex-302** [comment]
@evgeniy-ADG
