### ISSUE TITLE
Блокировка раздражающего элемента

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#59622]
Здравствуйте,
Никак не могу заблокировать этот объект (на картинке снизу)
https://i.ibb.co/RSmHQbM/20200719-002912.jpg
Есть ли возможность его заблокировать так, чтобы он мне ни на каких сайтах не появлялся. Объект мешает. Какое я должен добавить правило для блокировки?

Пы. Сы: искусственно эту страницу можно вызвать тут http://captcha.website/

### Я имею ввиду заблокировать этот объект на ВСЕХ сайтах, если это возможно.

Заранее спасибо.

**Comment by zloyden** [comment]
Это не раздражитель, а часть функционала сайта. Можно таким в пользовательские `captcha.website#?#.cf-columns > div.cf-column:has(> h2[data-translate="resolve_captcha_headline"])`.
Для остальных сайтов нужно смотреть индивидуально. По составлению правил у нас есть полезная [статья](https://kb.adguard.com/ru/general/how-to-create-your-own-ad-filters).
