### ISSUE TITLE
turbobit.net - cannot download file

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5962]
https://github.com/AdguardTeam/AdguardFilters/issues/1265 - the same problem again

> В браузере (Яндекс.Браузер 17.7.1.532 Beta) блокируется (бесплатная) загрузка с Turbobit.net, при отключении расширения, загрузка происходит нормально.
> 
> Подключённые фильтры:
> 
> Английский фильтрВерсия 1.1.26.13. Обновлено 28 июля 2017 в 03:00.
> Фильтр счетчиков и системы аналитикиВерсия 1.0.13.50. Обновлено 28 июля 2017 в 02:00.
> Фильтр раздражителейВерсия 1.0.16.14. Обновлено 28 июля 2017 в 04:02.
> Русский фильтрВерсия 1.0.54.61. Обновлено 28 июля 2017 в 04:00.

ID: 871860

**Comment by Alex-302** [comment]
Что подразумевается под "блокируется"?

**Comment by Alex-302** [comment]
@evgeniy-ADG
