### ISSUE TITLE
tomsguide.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5963]
***Site***: https://downloads.tomsguide.com/Illustrator-CS5,0301-27756.html
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28871129-7fa23b5a-7783-11e7-906b-99355895e3c4.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
