### ISSUE TITLE
softonic.com - Social widgets - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5964]
***Site***: https://adobe-illustrator.de.softonic.com/
***Description***: Social share icons. Newsletter popup.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28871197-d5f0c7f6-7783-11e7-8b76-d7a11cfa144b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by seanl-adg** [comment]
Fixed

**Comment by danidoedel** [comment]
@seanl-adg Why not `softonic.com##.app-list-share` to remove the leftover as well?

![image](https://user-images.githubusercontent.com/10995998/28945294-32aca460-78a6-11e7-8799-cd855705254e.png)
