### ISSUE TITLE
 https://music.yandex.ru/ - hiding an element

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5965]
I want to hide element on page https://music.yandex.ru/

Here is how it looks

![image](https://user-images.githubusercontent.com/15856304/28871639-25f685ba-778e-11e7-903c-1f465d46ca48.png)

its selector is: `*div.bar__new-pay*`

my custom filter is: 
```
*music.yandex.ua##.bar__new-pay
<http://music.yandex.ua##.bar__new-pay>*
```

I'm using latest Google Chrome, Windows 10 and Adguard extension (without
Windows desktop app)

I know that I can right click on the element and block it from there, it
works, but it is not the reason I'm asking for support, I want to make
custom filter by my own, moreover such example is in your documentation
right here:
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#elemhide-examples

**Comment by Senpos** [comment]
![image](https://user-images.githubusercontent.com/9695470/28877734-eb48956c-77a5-11e7-96d6-48bc0eea32a5.png)
It seems like Yandex has changed their banner to the one illustrated above

**Selector:**
![image](https://user-images.githubusercontent.com/9695470/28878001-b0305a72-77a6-11e7-99d0-33b08c5ca68f.png)

**Rule:**
`music.yandex.ua##div.bar__new-pay`

And after page restart element is still there

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
music.yandex.ru,music.yandex.ua,music.yandex.by,music.yandex.kz##$#.bar__new-pay { position: absolute!important; left: -3000px!important; }
```
