### ISSUE TITLE
Freevpn.net

### ISSUE THREAD

**Issue by shinelin472** [AdguardTeam/AdguardFilters#59671]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/88029753-1394fd00-cb43-11ea-84e9-bf65497b596c.png)
