### ISSUE TITLE
http://www.filmionlineizle.net/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5969]
Site: http://www.filmionlineizle.net/
Note: I can't scroll down with AG enabled. Screen: http://s1.postimg.org/h0bw1yij3/screenshot_100.png
Screen: http://s1.postimg.org/vm7i3y4pb/screenshot_101.png (Without AG, I can scroll down)

**Comment by AdamWr** [comment]
Fixed.
