### ISSUE TITLE
outlook.com status issue

### ISSUE THREAD

**Issue by adguard** [AdguardTeam/AdguardFilters#597]
From wilders:
One issue that I have noticed since enabling SSL filtering recently is that on Outlook.com/Hotmail/Live platform of web-based email, it automatically switches your status to Available. I have always had my status as Invisible for many years now as a preference. But everytime I log back in it goes straight to Available as long as Adguard has SSL filtering enabled.

Latest stable Chrome.

**Comment by Alex-302** [comment]
у меня невидимость сохранилась после выхода. Чел наверное куки чистит.
