### ISSUE TITLE
news.goo.ne.jp [N: Nano Adblocker] [T: Ads]

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#59736]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Three placeholders on article pages. I propose adding `news.goo.ne.jp##.gn-partition:not(.topstories-widget)` to AdGuard Japanese Filter to remove them.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/87970198-ad1cca00-cac3-11ea-8a29-aa2e97671359.png)
</details><br/>

* **Expected behaviour**: 

The placeholders are blocked. 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/87970426-0684f900-cac4-11ea-9593-a866280703fe.png)
</details><br/>

***Steps to reproduce the problem***:

1) Visit `https://news.goo.ne.jp/article/asahi/nation/ASN7N71Y8N7NUTIL027.html`.

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/87970523-287e7b80-cac4-11ea-8366-d2a6d369444f.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | May 2020 Update
Browser:                               | Chrome 84.0.4147.89 x64
AdGuard version:                       | Nano Adblocker 1.0.0.152 + Nano Defender 15.0.0.201
Filters enabled:                       | See screenshot above
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I don't like `:not()` on complicated sites. 
![image](https://user-images.githubusercontent.com/8361299/88052053-55816b80-cb62-11ea-9770-772d75af5367.png)
Added another rule.
