### ISSUE TITLE
https://www.filmsonu.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#5976]
Site: https://www.filmsonu.com/
Screen1: http://s1.postimg.org/olok8a98v/screenshot_108.png
Screen2: http://s1.postimg.org/dalwjx2dr/screenshot_109.png

Site: https://www.filmsonu.com/cilgin-kolej-izle-2017/
Note: Remove skip ad.

And... + Click something, you get a new popup.

**Comment by AdamWr** [comment]
Fixed.
