### ISSUE TITLE
tutsplus.com - Social widget - Ads - Ad leftover - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5977]
***Site***: https://webdesign.tutsplus.com/articles/10-examples-of-animation-on-codepen-you-can-learn-from--cms-28244
***Description***: Ad at the top. Ad leftovers. Newsletter sign up. Social share icon in article header. Ad in sidebar.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28897717-397c9850-77e2-11e7-9509-2492b84b627d.png)

![image](https://user-images.githubusercontent.com/10995998/28897735-593bd99e-77e2-11e7-930c-052d683b56ba.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
