### ISSUE TITLE
Some rules block NSFW sites

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#59780]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

* **Current behaviour**: 

in the Adguard Base Filter there are now several rules that block porn
sites from loading altogether. example: ||xnxx.com$third-party - while
this is well-intentioned, when you click on a link to a specific video
from Duckduckgo search Adguard blocks it with the Adguard notice.
clicking on Proceed anyway doesn't work - it never has. Same thing
happens when clicking a direct link to a youporn.com video.

<details><summary>Screenshot:</summary>

Not provided.
</details><br/>

***Steps to reproduce the problem***:

1, Attempt to open a link to NSFW video from a third-party website (e.g. Google or Duckduckgo)

***System configuration***

**Filters:**

"AdGuard Base filter", "AdGuard Mobile Ads filter", "EasyList", "Peter Lowe's Blocklist", "AdGuard Tracking Protection filter", "EasyPrivacy", "Fanboy's Enhanced Tracking List", "Fanboy Anti-Facebook List", "Fanboy's Anti-thirdparty Fonts", "AdGuard Social Media filter", "Fanboy's Social Blocking List", "AdGuard Annoyances filter", "Web Annoyances Ultralist", "Fanboy's Annoyances", "Adblock Warning Removal List", "I don't care about cookies", "EasyList Cookie List", "Malware Domains Blocklist", "Spam404", "NoCoin Filter List", "AdGuard French filter", "AdGuard Russian filter", "AdGuard Chinese filter", "AdGuard Dutch filter", "AdGuard German filter", "AdGuard Turkish filter", "AdGuard Spanish/Portuguese filter", "AdGuard Japanese filter", "EasyList Czech and Slovak", "Adblock List for Finland", "List-KR", "Polish Anti Adblock Filters", "Frellwit's Swedish Filter", "EasyList Italy", "Official Polish filters for AdBlock, uBlock Origin & AdGuard", "EasyList Lithuania", "Bulgarian list", "EasyList Hebrew", "Latvian List", "Liste AR", "Icelandic ABP List", "Dandelion Sprout's Nordic Filters", "KAD - Przekręty", "RU AdList: Counters", "EasyList Dutch", "Xfiles", "CJX's Annoyance List", "Fanboy's Vietnamese", "Fanboy's Spanish/Portuguese", "Easylist Spanish", "ABPVN List", "EasyList Germany", "Fanboy's Swedish", "Polskie Filtry Ciasteczkowe", "ROList", "YousList", "RU AdList", "Polski Antyirytujący Dodatek Specjalny", "Polskie Filtry Społecznościowe", "road-block", "ABPindo", "Estonian List", "EasyList Polish", "Polskie Filtry Elementów Irytujących", "RU AdList: BitBlock", "EasyList China", "Polskie Filtry Wewnętrzne", "ChinaList+EasyList", "AdGuard DNS filter", "AdGuard Experimental filter", "BarbBlock"

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 8
Browser:                               | N/A
AdGuard version:                       | 3.4.120
Filters enabled:                       | See above
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | Default DOH
Helpdesk ID (if exists):               | 1968599

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@akmLaVx we need sample links and screenshots.

**Comment by akmLaVx** [comment]
I've requested a few couple links. User is very concerned about their privacy, though, and they refuse to send us any screenshots.

**Comment by Alex-302** [comment]
@akmLaVx User can send anonymous from AdGuard.

**Comment by akmLaVx** [comment]
@Alex-302 We've already tried suggesting that before. They're adamant on not sending any screenshots, ever.

**Comment by Alex-302** [comment]
Ok then.
