### ISSUE TITLE
Popup ad started appearing

### ISSUE THREAD

**Issue by IamMaris** [AdguardTeam/AdguardFilters#59805]
I have the Samsung Music app on my Note 10+ that started showing an annoying popup as for Serius Music subscription. I made sure the app was included in the apps list for ad blocked apps. Hopefully someone knows how to fix this and include it in a filter.

**Comment by Alex-302** [comment]
@IamMaris Hi. Which AdGuard? Please make screenshot.

**Comment by IamMaris** [comment]
Thanks for responding. I will get back to you in a few days because the ad had a "Do not show for 7 days" checkbox that I clicked.

I have AdGuard 3.4 (120), the new VPN one. My Samsung Music app is 16.2.22.20. My phone is a Samsung Galaxy Note 10+ SM-975U. I'll screenshot the popup as soon as it appears again.

Maris
![Capture](https://user-images.githubusercontent.com/45048882/88226139-a31cd780-cc39-11ea-8d84-2620c5b85c6f.PNG)

**Comment by Alex-302** [comment]
Ok, thanks.

**Comment by IamMaris** [comment]
Today the ad reappeared. Screenshot attached.
![Screenshot_20200729-082610_Samsung Music](https://user-images.githubusercontent.com/45048882/88800301-ee714180-d175-11ea-84d9-cdc0c9163860.jpg)

**Comment by Alex-302** [comment]
It seems this is built in to the app and not loaded from network.
