### ISSUE TITLE
catchcoin.pw - Ad leftover - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5982]
***Site***: https://catchcoin.pw/u_peer/
***Description***: Adblock detection. Just click on "Get reward!" and solve the captcha. Also some ads and ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28898201-db4fddac-77e4-11e7-9a4b-ff8ebd415ebb.png)

![image](https://user-images.githubusercontent.com/10995998/28898228-ffcf00ae-77e4-11e7-9257-ac7e11c1e8cd.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
