### ISSUE TITLE
tomsguide.com - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5985]
https://www.tomsguide.com/us/pictures-story/565-best-adblockers-privacy-extensions.html

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28901595-ea85b5ae-7801-11e7-8423-d53319fd512f.png)

</details>

***System configuration***

pplication version: 1.3.0.100
Device: iPad
Platform: iOS
OS: 10.3.3
Optimized enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.59 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.62 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.75 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.35 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.17 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID : 1593858

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
