### ISSUE TITLE
hanfan.cc - Missed add

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5986]
http://www.hanfan.cc/variety/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28903603-7c55a2d0-780e-11e7-9455-8ff8e2fa3fa2.png)

</details>

***System configuration***

Application version: 1.3.0.81
Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.69 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.64 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.79 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.41 Enabled=YES
ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.10 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.65 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.18 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.95 Enabled=YES
ID=101 Name="EasyList" Version=1.0.74.41 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.85.8 Enabled=YES

Ticket ID: 1607048

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
