### ISSUE TITLE
https://rostov.rt.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5987]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**:  Слайдер с полезными баннерами заблокирован.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28914324-ef9af74c-7843-11e7-998a-c1a6fadca5c0.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28914360-0b17b1fe-7844-11e7-86fc-e3ef0c577b5e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10
Browser: | Хром
Adguard version: | 1732
Adguard driver (Windows): | WFP
Adguard DNS: | None 
Stealth mode options(Windows) |  default
Adguard filters: | 1 2 3 4 5 14
Ticket ID (if exists): | 1603741

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It was fixed yesterday. Check for updates.
