### ISSUE TITLE
anistar.me - missed counter

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#5988]
Is it possible to get rid of that counter?

![image](https://user-images.githubusercontent.com/15856304/28917166-66509b22-784d-11e7-84e0-a0cac020982d.png)

SRT:

1. Go to https://anistar.me/6240-kvest-sakury-sakura-quest-priklyuchenie-sakury.html
2. Choose "HDGO" player
3. Start the video
4. See the counter as on the screenshot.

Details:

1. MacOS, Adguard 1.4.1
2. Chrome and Safari
3. English, Russian, Spyware, Social media, Annoyances, Safari filters
4. ID: 1412565

**Comment by Alex-302** [comment]
Fixed.
