### ISSUE TITLE
nytimes.com - English + Spyware filters hide some necessary content

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#5989]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: English + Spyware filters hide some necessary content

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из бефера обмена. Оно будет автоматически загружено. )

<details><summary>Screenshot:</summary>

![screen shot 2017-08-03 at 12 45 16](https://user-images.githubusercontent.com/28726429/28917833-af5065d0-784f-11e7-857b-65482ddbbe17.png)

</details>
<br>

* **Expected behaviour**: English + Spyware filters shouldn't block comments section, opinions, related coverage and other.

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![screen shot 2017-08-03 at 12 46 18](https://user-images.githubusercontent.com/28726429/28917850-bbf5b48e-784f-11e7-8340-cc98c4fce2d4.png)

</details>
<br>

***Steps to reproduce the problem***:

1. Follow - https://www.nytimes.com/2017/08/02/opinion/donald-trump-russia-collusion-cia.html with English and Spyware filters enabled

***System configuration***

Information | value
--- | ---
Operating system: | macOS
Browser: | Safari
Adguard version: | 1.4.1
Adguard DNS: | None
Adguard filters: | 2, 3

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.
Which filter breaks it?

**Comment by altokarev** [comment]
I mentioned them in the topic and description (three times) - English filter + Spyware filter.

**Comment by Alex-302** [comment]
Try to disable on of them.

**Comment by altokarev** [comment]
Tried to disable English first, empty cache and reload the page few times. Those sections appeared. Disabling Spyware filter (while English filter enabled back) did the same.

**Comment by danidoedel** [comment]
No issues here as well...

**Comment by altokarev** [comment]
It reproduced on the several devices on the office for sure.
