### ISSUE TITLE
sitepoint.com - Ad leftover - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5990]
***Site***: https://www.sitepoint.com/callbacks-javascript/
***Description***: Ad leftover in sidebar. Newsletter banner.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28919132-69f08af4-784c-11e7-9d28-2e8d8c4a8843.png)

![image](https://user-images.githubusercontent.com/10995998/28919154-880c5de2-784c-11e7-8710-544e8b29245f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
