### ISSUE TITLE
bradsknutson.com - Ad leftover - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5991]
***Site***: http://bradsknutson.com/blog/css-sliding-underline/
***Description***: Ad leftover and ad after article.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28919462-db9620f0-784d-11e7-8633-ae3bbc90acda.png)

![image](https://user-images.githubusercontent.com/10995998/28919475-ee006f0c-784d-11e7-87b8-a945fcc4a1f8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
