### ISSUE TITLE
dn.se - Unblocked pop-up

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5992]
www.dn.se
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28922821-535af85c-7864-11e7-8dda-407fb6d3c573.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Chrome
Adguard version: | 2.9.136
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | 2 4 14 11 15 223
Ticket ID: | 1456058 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Xophile** [comment]
Hi! 

This has already been addressed previously. 

The annoyance occurs when you scroll down on the page on Android. Then you see a top bar which asks you to pay or login. Can that top bar be removed? 

Thanks!

**Comment by Xophile** [comment]
Here is a screenshot. See the annoying static top bar. When you scroll it is always on top asking you to login etc. 
![screenshot_20170804-100038](https://user-images.githubusercontent.com/24722383/28959711-ec0d123c-78fb-11e7-808d-fd1a2e54cf97.png)

**Comment by Alex-302** [comment]
Hi
I can't reproduce. Is it reproducible with Fanboy's Swedish only? Do you see that popup on desktop?

**Comment by Xophile** [comment]
Hi! 

Running Firefox on Android (Galaxy S7 Edge) I can see the top bar all the time when scrolling the page. 

Now I only have Fanboy's Swedish filter active

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
dn.se###pwOverlay
```
Please check.

**Comment by Xophile** [comment]
Hi!

Sorry, that filters deletes a big pop-up stating I'm using an Adblocker but it does not remove the bar that says (In Swedish):
"Prenumerera" och "Logga in"

**Comment by Alex-302** [comment]
That bar is not useless.

**Comment by Xophile** [comment]
Useless? I don't really understand?

It's an annoyance.

You can login on the very top of the page. But the top bar is eating up screen space when you scroll down, that's why I was looking for a way to remove it.

**Comment by Alex-302** [comment]
I don't understand what do you mean.
Please make screenshot and select the element which you want to hide.

**Comment by Xophile** [comment]
Hi again!

I made a picture of it (I know it looks like a 3-year old did it...)
![dn](https://user-images.githubusercontent.com/24722383/28982762-3e024426-7957-11e7-8054-7906671ac961.jpg)

Do you see what I mean now?

Many thanks!

**Comment by Alex-302** [comment]
Got it)
Added to Annoyances filter
```
dn.se##.navigation__top-container
```

**Comment by Xophile** [comment]
Alex:

Much appreciated! 

Thanks a lot!
