### ISSUE TITLE
swedroid.se - Anti adblock

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#5993]
http://www.swedroid.se/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28923907-5815f1ea-7868-11e7-9f4e-44fc6299d235.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Chrome
Adguard version: | 2.9.136
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On 
Adguard filters: | 2 4 14 11 15 223
Ticket ID: | 1456058 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by seanl-adg** [comment]
Fixed
