### ISSUE TITLE
https://yume551.com/japanesefilm/105704.html

### ISSUE THREAD

**Issue by horyu501** [AdguardTeam/AdguardFilters#59962]
***Issue URL (Ads)***
https://yume551.com/japanesefilm/105704.html

***Description***:
https://yume551.com/japanesefilm/105704.html

- widget-view.dmm.co.jp
- widget-view.dmm.com

これらは要素が非表示指定になっているため、画面上では表示されていない。
These are not displayed on the screen because the elements are designated as hidden.

しかし、ブラウザはデータを読み込んでしまっている。
However, the browser has loaded the data.

---- Japanese to English translation by DeepL ( https://www.deepl.com/en/translator ).

Information                            | Value
---                                    | ---
Operating system:                      | Android
Browser:                               | Chrome
AdGuard version:                       | v3.5 nightly 4 (29-1.5.271cl)
Filters enabled:                       | AdGuard Base filter , AdGuard Mobile Ads filter , AdGuard Tracking Protection filter , AdGuard Social Media filter , AdGuard Annoyances filter , AdGuard Japanese filter , AdGuard DNS filter
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by horyu501** [comment]
Element is hidden by AdGuard Base filter, `##iframe[width="300"][height="250"]`
<details><summary>source</summary>
`<iframe id="239ee256ca792a11e0aff79346c97f6d" src="https://widget-view.dmm.com/item_list/?adid=239ee256ca792a11e0aff79346c97f6d&affiliate_id=cinemavideo-004&site=DMM.com&service=pcsoft&sort=rank&size=300_250&content=image&effect=slide&auto_play=1&show_price=1&show_border=1&target_blank=1&image_size=small&algo=ranking" width="300" height="250" frameborder="0" scrolling="no">`
</details>

**Comment by Alex-302** [comment]
Is not it an ad? As I see, it is blocked by `豆腐フィルタ`(we cannot include it to AdGuard because of license)
`||dmm.co*/js/placement.js`

@Yuki2718 what we must to do?

**Comment by horyu501** [comment]
As far as I know, there are only two URLs covered.  
- `https://widget-view.dmm.com/js/placement.js`
- `https://widget-view.dmm.co.jp/js/placement.js`

> As I see, it is blocked by 豆腐フィルタ(we cannot include it to AdGuard because of license)
> ||dmm.co*/js/placement.js

Oh! I'm surprised. Does the license extend to these piecemeal rules? There's no way around it, so here's my suggestion.  
`||widget-view.dmm.*/js/placement.js`

<details><summary>日本語原文 / Original Japanese text

</summary>

私が知る限り、対象のURLは二点のみ。  
- `https://widget-view.dmm.com/js/placement.js`
- `https://widget-view.dmm.co.jp/js/placement.js`

> As I see, it is blocked by 豆腐フィルタ(we cannot include it to AdGuard because of license)
> ||dmm.co*/js/placement.js

おお！びっくりしてる。このような断片的ルールにまでライセンスが及ぶのですか。しかたがありませんので私の提案はこちらになります。  
`||widget-view.dmm.*/js/placement.js`

---- Japanese to English translation by [DeepL](https://www.deepl.com/en/translator).
</details>

**Comment by Yuki2718** [comment]
@Alex-302 That's an ad, just add these two which are equivalent to the rules in 豆腐フィルタ but comaptible with DNS too.
`||widget-view.dmm.co.jp^`
`||widget-view.dmm.com^`
Apparently OP thought some ads are just hidden and not blocked, but the fact is it's not even hidden as you see. I'll explain to him.

@horyu501 ご報告ありがとうございます。失礼ながら、widget-view.dmm.comの対象は当初より非表示されておりません。`##iframe[width="300"][height="250"]`が非表示にしているのは忍者Admax広告であり、これは既存のルールでブロックされております。
なお、豆腐フィルタはライセンスが設定されていないため、著作権上AdGuardのフィルタに採用できないというのがAlexの意味したところです。個々のルールについても、フィルタ作者が常識的・必然的に到達する内容以上であれば侵害になる可能性があります。

**Comment by horyu501** [comment]
@Yuki2718 ライセンスについて了解しました。ご対応ありがとうございます。
