### ISSUE TITLE
kitguru.net - Social widgets - Ad leftover - Ad - Annoyance - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5998]
***Site***: https://www.kitguru.net/gaming/matthew-wilson/gta-v-flooded-with-negative-reviews-on-steam-following-openiv-shutdown/
***Description***: Adblock detection. Ad background. Ad leftover and facebook leftover in sidebar. Social share stuff after article. Annoying box slides in while scrolling down.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28937669-e40070d6-788b-11e7-9b16-24e93d420d40.png)

![image](https://user-images.githubusercontent.com/10995998/28937817-60377726-788c-11e7-8ee5-ec4a30299e58.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
