### ISSUE TITLE
stackoverflow.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#5999]
***Site***: https://stackoverflow.com/questions/12347701/why-transitions-for-some-css-properties-are-slow-and-none-fluent
***Description***: Newsletter sign ups. Sometimes in main content and sometimes in sidebar, you may have to reload the page a few times to reproduce it.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28938086-3bba8658-788d-11e7-8443-964f19399254.png)

![image](https://user-images.githubusercontent.com/10995998/28938173-8cbaf786-788d-11e7-9a19-55de5f667647.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
