### ISSUE TITLE
learn.shayhowe.com - Social widgets

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6000]
***Site***: http://learn.shayhowe.com/advanced-html-css/performance-organization/
***Description***: Share leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28944814-4007201a-78a4-11e7-8b09-146ad11ffcb0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
