### ISSUE TITLE
www.gocomics.com - Ads - iOS

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6002]
***Description***:
* **Current behavior**: 

There is Ad leftover on http://www.gocomics.com/pearlsbeforeswine on iOS
Reproduced on our side (Mac OS)

<details><summary>Screenshot:</summary>

![screen shot 2017-08-04 at 12 55 39 am](https://user-images.githubusercontent.com/28784344/28947010-66af8326-78b6-11e7-9e95-998d0869b4d2.png)

</details>

Application version: 1.3.0.81
Device: iPhone
Platform: iPhone OS
OS: 9.3.4
Optimized enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.39 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.31 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.5 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES
ID=101 Name="EasyList" Version=1.0.73.99 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.83.96 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.74.20 Enabled=YES

Ticket ID (if exists): | 1259288

**Comment by Alex-302** [comment]
Added to English filter
```
gocomics.com##.amu-container-ad-wrapper
gocomics.com##.group-item-ad

```
