### ISSUE TITLE
mp4mania.rocks - AdLeftover - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6008]
***Description***:
* **Current behaviour**: 

Adleftover on mp4mania.rocks on Android (reproduced on our side)
***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Chrome
Adguard version: | 2.9.136
Adguard mode (Android): | VPN 
Filtering quality (Android): | high-speed 
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None 
Adguard filters: | 2, 3, 4, 14, 11, 15, 211
Ticket ID (if exists): | 1607298, 1518164

**Comment by Alex-302** [comment]
Fixed
