### ISSUE TITLE
gamesradar.com- Anti-Adblock script- Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6009]
***Description***:
* **Current behaviour**: 

Anti-Adblock script on http://www.gamesradar.com/ on Windows OS
Reproduced on our side (Mac OS)
<details><summary>Screenshot:</summary>

![screen shot 2017-08-04 at 5 04 27 am](https://user-images.githubusercontent.com/28784344/28951406-7ff52e36-78d3-11e7-9d8d-7373b04d7f4d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP 
Adguard DNS: | None 
Adguard filters: | 1,2,3,4,11,10,14 (told the user to disable others)
Ticket ID (if exists): | 1492862

**Comment by danidoedel** [comment]
#6005 ...

**Comment by Alex-302** [comment]
Fixed for the apps.
Check with extensions:
```
gamesradar.com##body > div[id][class][style="display: block;"]
gamesradar.com##body > div[class][style="display: block;"]:empty
gamesradar.com#$#html { overflow: visible!important; overflow-y: visible!important; }
gamesradar.com#$#body { overflow: visible!important; overflow-y: visible!important; }
gamesradar.com#$#html[-ext-has="body"] { overflow: visible!important; overflow-y: visible!important; }
gamesradar.com#$#body[-ext-has="div"] { overflow: visible!important; overflow-y: visible!important; }
```
