### ISSUE TITLE
lenfilm.tv - Missed ads

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6010]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Does not block ads in CM browser. 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

Make sure to switch to mobile version (by clicking 'Mobile'). May be hard to reproduce at once. Try refreshing a few times or visiting different pages. 
Screenshots were made at [http://lenfilm.tv/filmcat/view/id/5](http://lenfilm.tv/filmcat/view/id/5)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)

[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screenshot_20170804-094746](https://user-images.githubusercontent.com/30041399/28957474-b1a39392-78fa-11e7-92ca-0f9a911d6688.png)
![screenshot_20170804-094806](https://user-images.githubusercontent.com/30041399/28957477-b4958b0a-78fa-11e7-939f-31b69386655f.png)

</details>

* **Expected behaviour**: Should block the ads.  

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | CM Browser (up-to-date)
Adguard version: | 2.9.135 and 2.9.136
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality and Speedy
HTTPS filtering (Android): |  On and Off
Ticket ID (if exists): | 1536403

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
This browser causes reboot of my phone.
Not reproduced in Chrome and Opera.
Please capture HAR file.

**Comment by vitbortnik** [comment]
Please find HAR file attached. It's user-made one. 
[adguard.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1199658/adguard.har.zip)

**Comment by Alex-302** [comment]
http://imagizer.imageshack.com/img923/3867/4Xnpyj.png
that page is loaded bypassing Adguard. Maybe compression or browser's ad blocker is enabled.

**Comment by vitbortnik** [comment]
CM Browser's own Adblocker is disabled. 
User states that this is a problem with the latest Adguard release, it worked just fine before. 

As well I was able to reproduce this issue in Chrome. 
As I mentioned, it doesn't show ads at once, I had to refresh the page for a few times.

**Comment by Alex-302** [comment]
@vitbortnik 
> As well I was able to reproduce this issue in Chrome.

please try to capture HAR file.

**Comment by vitbortnik** [comment]
@Alex-302 
[adguard (1).har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1200111/adguard.1.har.zip)

**Comment by Alex-302** [comment]
Strange. I don't see resources of the page.
Please open the page in private tab when you are recording HAR file. Also attach the screenshot of ad. I need it to search ad.

**Comment by vitbortnik** [comment]
[adguard (2).har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1200201/adguard.2.har.zip)



<details><summary>Screenshots:</summary>

![screenshot_20170804-142735](https://user-images.githubusercontent.com/30041399/28967051-0e4570bc-7922-11e7-8ed4-5e9e7a79bc7e.png)
![screenshot_20170804-142745](https://user-images.githubusercontent.com/30041399/28967053-0e515490-7922-11e7-8119-33c2fa58b186.png)

</details>

**Comment by Alex-302** [comment]
Thanks. Added:
```
lenfilm.tv##.rek
```

**Comment by ypetruk** [comment]
After Aupdating flters
<details><summary>Screenshot:</summary>

![screenshot_2017-08-04-21-29-45-852_com ksmobile cb](https://user-images.githubusercontent.com/28784344/28992056-5451151a-799b-11e7-9edc-e00f1ea5e3a5.png)

</details>

<details><summary>Screenshot:</summary>

![screenshot_2017-08-04-21-29-58-373_com ksmobile cb](https://user-images.githubusercontent.com/28784344/28992061-63eb1700-799b-11e7-901b-6f283551cce7.png)

</details>

**Comment by Alex-302** [comment]
Please capture new HAR.

**Comment by vitbortnik** [comment]
[adguard (3).har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1202372/adguard.3.har.zip)

**Comment by vitbortnik** [comment]
As well user's one (probably made using CM Browser): 

[adguard (4).har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1202428/adguard.4.har.zip)

**Comment by Alex-302** [comment]
I need a screenshot. I see only this banner, which is hidden
![image](https://user-images.githubusercontent.com/8361299/29016166-efb22d7c-7b59-11e7-9161-00f197eaf501.png)

**Comment by vitbortnik** [comment]
Appeared only after refreshing the page for a few times. Make sure to enable mobile version. 

<details><summary>Screenshots:</summary>

![screenshot_20170810-075951](https://user-images.githubusercontent.com/30041399/29155120-725de852-7da2-11e7-8c8d-a8d80b616ba6.png)

![screenshot_20170810-080031](https://user-images.githubusercontent.com/30041399/29155121-7264479c-7da2-11e7-86cf-0849084bb055.png)

</details>

**Comment by Alex-302** [comment]
I mean I need HAR+screenshot. I can't find ad in HTML without ad text.

**Comment by vitbortnik** [comment]
[adguard.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1213963/adguard.har.zip)

**Comment by ypetruk** [comment]
<details><summary>Screenshot:</summary>

![screenshot_20170810-075951](https://user-images.githubusercontent.com/28784344/29182560-108f3796-7e08-11e7-993a-abdbcf7ae309.png)

</details>

<details><summary>Screenshot:</summary>

![screenshot_20170810-080031](https://user-images.githubusercontent.com/28784344/29182582-2644614c-7e08-11e7-9769-2a998408449d.png)

</details>

**Comment by Alex-302** [comment]
Ёлки. Да не может она не быть не скрытой. Там два правила её скрывают
```
lenfilm.tv##.rek
lenfilm.tv##body > div.rek[-ext-has="div"]
```
Точно мобильный фильтр включен?

**Comment by veronikasav** [comment]
Screenshots from our customer:

<details><summary>Screenshot:</summary>

<img width="382" alt="screen shot 2017-08-11 at 4 50 53 pm" src="https://user-images.githubusercontent.com/27292111/29215924-980c7cee-7eb5-11e7-9ec3-c729573c6b42.png">

<img width="390" alt="screen shot 2017-08-11 at 4 51 05 pm" src="https://user-images.githubusercontent.com/27292111/29215929-9bfe1e2a-7eb5-11e7-88bc-3dfdc7552563.png">

</details>

**Comment by veronikasav** [comment]
When I reload the page several times in a row this ad appears and disappears randomly.

<details><summary>Screenshot:</summary>

<img width="418" alt="screen shot 2017-08-11 at 5 00 50 pm" src="https://user-images.githubusercontent.com/27292111/29216281-d825a43a-7eb6-11e7-8d6f-518b87cb0b57.png">

<img width="418" alt="screen shot 2017-08-11 at 5 01 12 pm" src="https://user-images.githubusercontent.com/27292111/29216283-da557a46-7eb6-11e7-9e7c-8f1bb8420d5f.png">

</details>

**Comment by Alex-302** [comment]
> ad appears for 1 second and then disappears

It is a correct behavior in this case(Extended CSS)

**Comment by vitbortnik** [comment]
@Alex-302 
У нас проблема не повторяется больше, но пользователь все еще жалуется на нее.
Он прислал логи, посмотрите, пожалуйста по тикетам 1536403 и 1426828
Также, он не включает HTTPS фильтрацию по личным предпочтениям, может это и есть причиной проблемы?

**Comment by Alex-302** [comment]
У него китайский браузер. Может какое-то сжатие или VPN включен.
В его логах ничего нет, потому что в дефолтном режиме записаны.

**Comment by evgeniy-ADG** [comment]
Там еще одни логи прислали, говорят, что в этот раз - нужные. посмотри, может...
Тут: 1536403, последнее обращение. @Alex-302

**Comment by Alex-302** [comment]
Это дефолтный лог.

**Comment by darkulish** [comment]
Прислали новый лог веб-запросов и скриншот с рекламой на rg.ru.
Ticket: 1536403
![screenshot_2017-09-07-14-11-17-648_com yandex browser](https://user-images.githubusercontent.com/30834067/30237554-3baa66e8-953d-11e7-911c-6b3a4bb4b4e4.png)

![screenshot_2017-09-07-14-13-31-103_com yandex browser](https://user-images.githubusercontent.com/30834067/30237552-37c6f442-953d-11e7-8c91-cbc604c3c8b0.png)

**Comment by Alex-302** [comment]
> рекламой на rg.ru.

Фильтрация HTTPS не включена.

Для lenfilm.tv записан дефолтный лог. Мне он не нужен.
