### ISSUE TITLE
https://mobile.twitter.com/ - popups

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6011]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behavior**: You see the popup asking to register an account when browsing twitter and not being logged in

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28960644-297516ea-7908-11e7-9109-aacd40497086.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

1. Go to  https://mobile.twitter.com/ring_uk
2. Scroll down until you see the pop-up 

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.3
Simplified filters(iOS) | Off
Adguard DNS: | Default
Adguard filters: | English, Spyware, Annoyances, Safari, Mobile ads etc
Ticket ID (if exists): | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Added to Annoyances filter:
`mobile.twitter.com##header[role="banner"] + ._2FU3NGw4 > [class="kHlKyFGV _1363jyKz thXr_Z-z"]`

**Comment by Alex-302** [comment]
Are not that names random?

**Comment by AdamWr** [comment]
I think not. I refreshed website few times and it always was the same.
I also added this rule to my iPad and it worked.

**Comment by Alex-302** [comment]
Ok then. 
I can't reproduce that message.

**Comment by iverkhohliad** [comment]
Guys, the user writes about the same problem again. I checked on my side and I get the same message

**Comment by AdamWr** [comment]
Ok, fixed.
Added to Annoyances filter:
`mobile.twitter.com##header[role="banner"] + ._2FU3NGw4 > ._1363jyKz.thXr_Z-z`
