### ISSUE TITLE
TIViewer app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6013]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: The [app](https://play.google.com/store/apps/details?id=com.jiwoosoft.tiviewer&hl) contains ads and 0 mb of filtered ads in statistics

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28962956-0e5ba272-7910-11e7-8216-08263dd50b58.png)

![image](https://user-images.githubusercontent.com/15856304/28963093-8bfcfb0e-7910-11e7-836a-f422a300540a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 6, Xiaomi Redmi Note 4
Browser: | 
Adguard version: | 2.9.136
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default)
Adguard DNS: |  "dnsFilteringEnabled" : true
Adguard filters: | 2, 3, 4, 11, 15, 224, 227
Ticket ID (if exists): | 1584519, HTTP requests log available

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
This ad is blocked on Android 5.11.
Does user see requests from this app in the filtering log?(in the app)

**Comment by Alex-302** [comment]
@evgeniy-ADG
