### ISSUE TITLE
http://www.seedoff.tv/ - ad leftover

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6014]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: The blank space on top: http://www.seedoff.tv/

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28965891-0dd97142-791c-11e7-8dfc-cf8d40b64ae8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS
Browser: | Chrome
Adguard version: | the current ones
Adguard driver (Windows): | WFP
Adguard DNS: | None 
Adguard filters: | 1 2 3 4 5 14
Ticket ID (if exists): | 1607292

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
