### ISSUE TITLE
reddit.com - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6015]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behavior**: The cookie notification on top

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/28966849-0f0a9be0-7921-11e7-9f31-be6964ed1cb1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: |  1.3.0.81ff
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: |  2 3 4 6 11 12 14 107
Ticket ID (if exists): | 1607211

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I don't see that notification.

**Comment by uysct** [comment]
If Safari is completely terminated and reddit.com will reload the cookie's note immediately back.

`reddit.com###container > div.App > div.AppMainPage:first-child > div.NavFrame > div > div.NavFrame__below-top-nav:last-child > div.EUCookieNotice:first-child > div.EUCookieNotice__content`

**Comment by Alex-302** [comment]
Thanks, useful string.
Please check this rule
```
reddit.com##.EUCookieNotice
```

**Comment by uysct** [comment]
Thank you.
Unfortunately, with the same result.

**Comment by Alex-302** [comment]
`reddit.com##.NavFrame__below-top-nav`
try this

**Comment by uysct** [comment]
Sorry! Even that doesn't work. As soon as I switch from another Web page to reddit.com the cookie appears message again.

**Comment by AdamWr** [comment]
I can reproduce this on my iPad and I really do not know why this rule does not work - `reddit.com##.EUCookieNotice`, because I think it should.

Could you please check this:
`reddit.com##[class="EUCookieNotice"]`
On my end it works.

**Comment by uysct** [comment]
Wow ... Magic... Finally!
This works: 
reddit.com## [class = "EUCookieNotice"]

**Comment by AdamWr** [comment]
Ok, thank you.
Added to Annoyances filter.
`reddit.com##[class="EUCookieNotice"]`
