### ISSUE TITLE
bythom.com - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6016]
http://www.bythom.com/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28974945-e793d318-7940-11e7-9f4f-90472490b92b.png)

![image](https://user-images.githubusercontent.com/27292111/28974952-ee1c0e1c-7940-11e7-9ce3-aee6bc29e012.png)

</details>

***System configuration***

Application version: 1.3.0.100
Device: iPad
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.59 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.62 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.75 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.35 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.9.30 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.84.90 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.68 Enabled=YES

Ticket ID: 1607509

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added
```
||bhphotovideo.com/bimages/photodeals-do.gif
||bythom.com/_Media/pastedimage_med_hr.png
bythom.com###sidebar-content div.pagelet.titled[-ext-has="> h4 > span:contains(Social Links)"]
bythom.com###sidebar-content div.pagelet.titled[-ext-has="> h4 > span:contains(Advertisement)"]

```
