### ISSUE TITLE
m.news.bigmir.net -Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6020]
http://m.news.bigmir.net/ukraine/1093133-V-Zaporozh-e-ograbili-muzhchinu--kotoryj-nes-v-bank-krupnuju-summu-deneg

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28978490-d83cab7a-794e-11e7-88d9-cf1c8f80159a.png)

</details>

***System configuration***

Application version: 1.3.0.81
Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.78 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.66 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.84 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.47 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.54.89 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.18 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.95 Enabled=YES

Ticket ID: 1607842

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. It is blocked on my side.

**Comment by veronikasav** [comment]
How can I help you in this case?

**Comment by Alex-302** [comment]
I need MacOS, Safari for desktop with connected iPhone.

**Comment by Alex-302** [comment]
@zebrum could you, please, check this site?

**Comment by zebrum** [comment]
@Alex-302 can not reproduce
btw @veronikasav it is too many rules with those filters. ask user to turn off Simplified domain names filter and check
