### ISSUE TITLE
gruenderszene.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#60212]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:  1x1 tracking pixel. see https://github.com/easylist/easylist/issues/5681

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Opera
AdGuard version:                       | 3.4.31
Filters enabled:                       | default + Adguard germany + AdGuard Tracking Protection
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Why is it a tracker?
