### ISSUE TITLE
poebuilds.net - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6021]
***Site***: https://www.poebuilds.net/
***Description***: Ad banners.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/28981935-25bc4b26-7954-11e7-9cb0-fa33dc6d70e3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
