### ISSUE TITLE
ourusababy.com - Missed Ad

### ISSUE THREAD

**Issue by cicku** [AdguardTeam/AdguardFilters#6023]
`http://www.ourusababy.com/thread-166-1-1.html`

![www bf88 com](https://user-images.githubusercontent.com/686438/28995122-bd1088c0-7a12-11e7-9a33-e33b4e5e1c29.png)

**Comment by Alex-302** [comment]
Added to English filter
```
||ourusababy.com/bsj.js
.com/ad_js/
```
