### ISSUE TITLE
http://burdanhdfilmizle.net/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6025]
Site: http://burdanhdfilmizle.net/the-dark-tower-kara-kule-izle.html
Screen: http://s1.postimg.org/g5lrg085r/screenshot_7.png

**Comment by FadeMind** [comment]
This is social share buttons place holder. Try
```
burdanhdfilmizle.net###alt
```

**Comment by AdamWr** [comment]
Fixed.
