### ISSUE TITLE
Idealo.de

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdguardFilters#60264]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

I use AdGuardHome 0.103.3 on my RaspberryPi 4B with AdGuard SDNS filter.

***Description***: 
**Idealo.de** is an price comparsion website, once you search for a product it list all aviable shop & price.
* **Current behaviour**: 
Many of the listed shops cant be open because the AdGuardHome blocks the redirection.

* **Expected behaviour**: 
Redirection to shop website should work correct.

***Steps to reproduce the problem***:
Go to [Idealo.de](https://www.idealo.de/preisvergleich/OffersOfProduct/6765233_-iphone-11-64gb-black-apple.html) and choose one of this shops:

_example search for "Apple iPhone 11 64GB Black" the text below shop adress is the block massage/url that appears after choosing a shop_ 

**Please note: those are ".de" websites because im from germany, your results may be diffrent**

clevertronic.de 

> https://marketing.net.idealo-partner.com/ts/i5623540/tsc?amc=pricecomp.idealo.210455.220402.104507.1&smc2=ba6xjXvgfmhAUL1Lc0dOgw&smc3=19116&smc4=273154&smc5=oesg&rmd=3&trg=http%3A%2F%2Fwww.clevertronic.de%2Fkaufen%2Fhandy-kaufen%2Fauswahl%2F13504%2FApple%2BiPhone%2B11%2B64GB%2BSchwarz%3Fok%3D0%26utm_source%3Didealo%26utm_medium%3Dcpc%26utm_term%3DiPhone%2B11%2B64GB%2BSchwarz%26utm_campaign%3Dpreissuchmaschine%26utm_id%3D13504

talkthisway.de

> https://click.cptrack.de/?rd=true&k=AJcDhbqulN_Nt2YPEuHUAe2MBDOpzng73NJQI74N3K0

galaxus.de

> https://marketing.net.idealo-partner.com/ts/i5542909/tsc?amc=pricecomp.idealo.210455.220402.9041948.1&smc2=BkTn-vJSyGNRkrgc0mNLFQ&smc3=19116&smc4=317105&smc5=oesg&rmd=3&trg=https%3A%2F%2Fwww.galaxus.de%2Fde%2Fs1%2FProduct%2F11872012%3FpcscpId%3D26%26utm_content%3D11872012%26utm_medium%3Dcpc%26utm_campaign%3Dpreisvergleich%26utm_source%3Didealo

berlet.de

> https://marketing.net.idealo-partner.com/ts/i5117141/tsc?amc=pricecomp.idealo.210455.220402.88342.1&smc2=UZCImItMbkxGZ81XM4Mf1g&smc3=19116&smc4=10401&smc5=oesg&rmd=3&trg=https%3A%2F%2Fwww.berlet.de%2Fproduct%2Fapple-iphone-11-64gb-schwarz-277401%2F%3F%3Fet_cid%3D90%26et_lid%3D343

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android and Windows
Operating system version (Android/iOS) | -
Browser:                               | Opera 59.1 on Android and 69.0 on Windows
AdGuard version:                       | AdGuardHome 0.103.3
Filters enabled:                       | AdGuardSDNSFilter
AdGuard mode (Android only):           | -
Filtering quality (Android only):      | -
HTTPS filtering (Android only):        | -
Simplified filters (iOS only)          | -
AdGuard DNS:                           | -
Stealth mode options (Windows only)    | -
Helpdesk ID (if exists):               | -

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@uservictor Hi. Which rules triggered in filtering log? Please clear log, reproduce an issue and copy applied rules(some rules can be applied by CNAME)

**Comment by uservictor** [comment]
Filter:
AdGuard DNS filter

www.econda-monitor.de
click.cptrack.de
tracking.lengow.com
marketing.net.idealo-partner.com

those i found in querylog

**Comment by Alex-302** [comment]
Please check in user rules:
```
@@||cptrack.de^$important
@@marketing.net.idealo-partner.com^$important
```

**Comment by Sergey-Lyapin** [comment]
@uservictor, hello
These domains are common tracking services, so we can't just remove them from filters.
You can whitelist domains that causing problem in query log
<details>
<summary>Whitelisting in query log</summary>
<img src="https://user-images.githubusercontent.com/18536328/88899750-1dabaf80-d257-11ea-933f-98529c2c8383.png">
</details>

@@||marketing.net.idealo-partner.com^$important

**Comment by Sergey-Lyapin** [comment]
@uservictor, hello
These domains are common tracking services, so we can't just remove them from filters.
You can whitelist domains that causing problem in query log
<details>
<summary>Whitelisting in query log</summary>
<img src="https://user-images.githubusercontent.com/18536328/88899750-1dabaf80-d257-11ea-933f-98529c2c8383.png">
</details>

For example for clevertronic.de this rule will be added in custom filtering rules
@@||marketing.net.idealo-partner.com^$important

**Comment by Morku** [comment]
I tried to report something similiar here: https://github.com/AdguardTeam/AdguardFilters/issues/48633
Not knowing that it was caused by DNS filter.

Yeah, there is a tracking/Ad link betwen click and destination. A feature to bypass this kind of tracking without unblock them would be nice... 🤷‍♀️

**Comment by uservictor** [comment]
@Morku ad.doubleclick.net is also one of url used to redirect in idealo.de like you mention in your issue report.
Can you explain what AGfW is and how it works?

@Alex-302 @Sergey-Lyapin yes thats the way i usually solve such isues, thanks 
I just thought there would be an diffrent solution and i opened an ticket.

**Comment by Morku** [comment]
@uservictor 
AGfW = AdGuard for Windows
But the Client version do not fix the issue. It is just an idea I have in mind, because there are much more possibilitys then a simple DNS blocker. I don't know if it is a topic.

**Comment by uservictor** [comment]
> Please check in user rules:
> 
> ```
> @@||cptrack.de^$important
> @@marketing.net.idealo-partner.com^$important
> ```

This works thanks

**Comment by Morku** [comment]
@uservictor 
If you like to know, I found a nice Add-on which solve the problem: Skip Redirect: https://addons.mozilla.org/de/firefox/addon/skip-redirect/
Also available for Chrome/Edge.
Visiting Shops from idealo works just fine without allow to visit marketing.net.idealo-partner.com
So, block it again, install the extension and check if it is fine for you :)
