### ISSUE TITLE
http://www.fullhdfilmizledim.org/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6028]
Site: http://www.fullhdfilmizledim.org/sessiz-bir-tutku-izle-2016-full-hd-720p.html

***Description***: When I enter this site, a sound plays in background. Link of this player is this: http://www.haber4saat.com/tt.mp4

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Google Chrome
Adguard version: | Browser Extension 2.6.7 (Stable)
Adguard driver (Windows): | 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): | 
Simplified filters(iOS) | 
Adguard DNS: | None | 
Adguard filters: | English filter, Russian filter, Turksih filter, Spyware filter, Annoyances filter, Social media filter
Ticket ID (if exists): |

**Comment by AdamWr** [comment]
Fixed.
