### ISSUE TITLE
https://fullonlinefilmizle.net/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6031]
Site: https://fullonlinefilmizle.net/tarzan-efsanesi-the-legend-of-tarzan-2016-turkce-dublaj-izle.html

***Description***: Remove empty space

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
http://s1.postimg.org/z2y61n1an/screenshot_8.png

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Google Chrome
Adguard version: | Browser Extension 2.6.7 (Stable)
Adguard driver (Windows): | 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): | 
Simplified filters(iOS) | 
Adguard DNS: | None | 
Adguard filters: | English filter, Russian filter, Turksih filter, Spyware filter, Annoyances filter, Social media filter
Ticket ID (if exists): |

**Comment by AdamWr** [comment]
I can't reproduce.

**Comment by thislife81** [comment]
@AdamWr  Look at here: http://s1.postimg.org/vl5k7zsun/screenshot_34.png

**Comment by Alex-302** [comment]
Can't reproduce.
