### ISSUE TITLE
http://hdfilmevreni.co/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6033]
Site: http://hdfilmevreni.co/

***Description***: Click something, you will get a popup. 

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Google Chrome
Adguard version: | Browser Extension 2.6.7 (Stable)
Adguard driver (Windows): | 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): | 
Simplified filters(iOS) | 
Adguard DNS: | None | 
Adguard filters: | English filter, Russian filter, Turksih filter, Spyware filter, Annoyances filter, Social media filter
Ticket ID (if exists): |

**Comment by AdamWr** [comment]
Fixed.
