### ISSUE TITLE
http://www.hdfilmseli.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6036]
Site: http://www.hdfilmseli.com/sniper-duvar-film-izle-turkce-altyazili-2017/

***Description***: Remove close button

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
http://s1.postimg.org/batg3uonj/screenshot_11.png

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Google Chrome
Adguard version: | Browser Extension 2.6.7 (Stable)
Adguard driver (Windows): | 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): | 
Simplified filters(iOS) | 
Adguard DNS: | None | 
Adguard filters: | English filter, Russian filter, Turksih filter, Spyware filter, Annoyances filter, Social media filter
Ticket ID (if exists): |

**Comment by AdamWr** [comment]
Fixed.
