### ISSUE TITLE
 http://noktafilmizle.net/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6040]
Site: http://noktafilmizle.net/osmanli-tegmen-izle.html

***Description***: Remove background ad; skip ad

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
![screenshot_15](https://user-images.githubusercontent.com/19608513/29002099-d8ee9516-7aab-11e7-9b2f-54b340f660df.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Google Chrome
Adguard version: | Browser Extension 2.6.7 (Stable)
Adguard driver (Windows): | 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): | 
Simplified filters(iOS) | 
Adguard DNS: | None | 
Adguard filters: | English filter, Russian filter, Turksih filter, Spyware filter, Annoyances filter, Social media filter
Ticket ID (if exists): |

**Comment by Alex-302** [comment]
Fill the provided template.

**Comment by thislife81** [comment]
It's already.

**Comment by thislife81** [comment]
@Alex-302 I filled all issues. But why didnt you close them not resolving?

**Comment by Alex-302** [comment]
I will close all issues without decsription as `invalid`.

**Comment by AdamWr** [comment]
Fixed.
