### ISSUE TITLE
Web Service blocked as tracker but is not tracker

### ISSUE THREAD

**Issue by rsingel** [AdguardTeam/AdguardFilters#60406]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Currently all subdomains and the main domain for Contextly.com are blocked. Contextly is a recommendation service used by publishers to show readers contextual recommendations to more of that publisher's content. Contextly does *NO* reader tracking and does not use cookies.

* **Current behaviour**: If a reader visits one of our publisher sites and is using the AdGuard Tracking Protection filter, they will not see the recommendations. For example: https://www.ci.apartmentguide.com/blog/home-office-organization-tips/

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
![image](https://user-images.githubusercontent.com/1848439/88856453-5db45900-d1a9-11ea-9de1-bd0a84276fc6.png)

</details><br/>

* **Expected behaviour**: Readers who visit that site should be able to see our recommendations.

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/1848439/88856633-ad932000-d1a9-11ea-97f3-b68811dbc09c.png)

</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # AdGuard Tracking Protection filter

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Rule exchanged.
Unsure if we should use ||geoip-js.com^$domain=ci.apartmentguide.com as on right side they show apartments based on IP, what do you think @AdguardTeam/filters-maintainers

**Comment by Alex-302** [comment]
> geoip-js.com

not a tracker(look at requests).

**Comment by BlazDT** [comment]
Yep, but additional request is made to get IP address and location which technically they can do themselves.
