### ISSUE TITLE
http://www.sinefan.co/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6041]
Site: http://www.sinefan.co/
Site: http://www.sinefan.co/kabuktaki-hayalet-izle.html

***Description***: Remove Big ad, skip ad

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
1) http://s1.postimg.org/6v3q63hsf/screenshot_16.png
2) http://s1.postimg.org/5hc3asij3/screenshot_17.png

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Google Chrome
Adguard version: | Browser Extension 2.6.7 (Stable)
Adguard driver (Windows): | 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): | 
Simplified filters(iOS) | 
Adguard DNS: | None | 
Adguard filters: | English filter, Russian filter, Turksih filter, Spyware filter, Annoyances filter, Social media filter
Ticket ID (if exists): |

**Comment by AdamWr** [comment]
Fixed.
