### ISSUE TITLE
RU AdList: BitBlock - Incorrect blocking

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6042]
***Description***:
* **Current behaviour**: 
The filter RU AdList: BitBlock incorrectly filters the website https://animakura.ru/shop/dakimakury/
Reproduced on our side

<details><summary>Screenshot with filter:</summary>

![screenshot_9](https://user-images.githubusercontent.com/28784344/29003845-062e69b4-7ac7-11e7-99e2-315a24b75e14.jpg)

</details>

<details><summary>Screenshot without filter:</summary>

![screenshot_8](https://user-images.githubusercontent.com/28784344/29003849-0f634d7e-7ac7-11e7-9856-80fc8228890b.jpg)

</details>

Information | value
--- | ---
Operating system: |  Mac OS
Browser: | chrome
Adguard version: | 1.4.1.
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1608116

**Comment by dimisa-RUAdList** [comment]
https://hg.adblockplus.org/ruadlist/rev/af6d57fec2c0#l1.13
