### ISSUE TITLE
https://www.shabdkosh.com -Sponsored Ad

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6043]
***Description***:
* **Current behaviour**: 

Sponsored Ads on https://www.shabdkosh.com/
Reproduced on our side (Mac OS)
<details><summary>Screenshot:</summary>

![screen shot 2017-08-06 at 6 22 09 pm](https://user-images.githubusercontent.com/28784344/29004676-2dc1a15a-7ad4-11e7-8fe2-70c13b083574.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1518164

**Comment by Alex-302** [comment]
fixed
