### ISSUE TITLE
xhamster5.desi [NSFW] [Pop-ups & Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#60434]
https://xhamster5.desi/videos/desi-long-hair-mom-ko-nokar-ne-choda-xhKHRV3?pb=#

Seeing pop-ups and ads on AG for Chrome and Android. Please fix

**Comment by zloyden** [comment]
It's better to report via this [link](https://agrd.io/report), there will be more information.
Not reproduced on my end, @AdguardTeam/filters-maintainers please take a look.

**Comment by BlazDT** [comment]
Ads not seen, please make screenshot.
Fixed popunder when pressing on small play button.

**Comment by Nzzyme** [comment]
Cookie notice and x symbol seen on the video player when pausing the video
https://xhamster5.desi/videos/jane-doe-private-dick-xhrDSRs
https://i.imgur.com/cfjNcxo.png

**Comment by BlazDT** [comment]
Fixed
