### ISSUE TITLE
voot.com - Incorrect blocking

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6044]
***Description***:
* **Current behaviour**: 

Not loading video when Adguard enabled on https://www.voot.com (opened using VPN app, as it is available only to Indian residents) on Windows.
When Adguard filtering is disabled - the video can be loaded

Reproduced on our side (Mac OS)

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1518164

**Comment by Alex-302** [comment]
I can't access. Which VPN are you using?

**Comment by im3or** [comment]
I am using Windscribe VPN. Set it to India. I think free version also has India server.

**Comment by AdamWr** [comment]
Unfortunately I can't reproduce.
It works on my end.

![image](https://user-images.githubusercontent.com/29142494/29026645-1b00eb8a-7b7d-11e7-880b-b5a2459b91f9.png)

**Comment by im3or** [comment]
Not here.

Not opening the homepage. But after adding some exclusions

I can open the webpage fine. 
![screenshot00550](https://user-images.githubusercontent.com/30718972/29030692-98c732b4-7ba9-11e7-9863-69a20f88c8e8.jpg)
![Uploading ScreenShot00553.jpg…]()

**Comment by AdamWr** [comment]
Could you tell me what you must add to exclusions and which filter lists do you use?

**Comment by im3or** [comment]
I use these - 
English
Spyware
Annoyance
Fanboy Annoyance
Fanboy Enhanced Tracking
Anti-Adblock Killer Reek
Adblock Warning Removal
I dont care about cookies

**Comment by AdamWr** [comment]
Ok, thank you.
I will try to reproduce this with these filters list.

**Comment by im3or** [comment]
If it helps, these are things showing in filtering log when blocking - 
![screenshot00555](https://user-images.githubusercontent.com/30718972/29031346-91a1a940-7bab-11e7-861b-c117c04009ff.jpg)

**Comment by AdamWr** [comment]
It seems that problem is with `Fanboy's Annoyances`.
Could you check this rule:
`@@||loginradius.com^$domain=voot.com`

**Comment by im3or** [comment]
Yes, working now after adding this in user filter.

**Comment by AdamWr** [comment]
Ok, I added it to English filter and reported this issue on EasyList forum - https://forums.lanik.us/viewtopic.php?f=64&t=37759
