### ISSUE TITLE
http://www.animespirit.ru/ and https://anistar.me/ - youtube playcont cheating

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6045]
Adguard включен , но не блокирует воспроизведение скрытого блока:

<details> <summary> screnshots </summary>

![image](https://pp.userapi.com/c836522/v836522186/569ef/6d-DMdbJK0w.jpg)

![image](https://user-images.githubusercontent.com/15856304/29005190-403aea9e-7ade-11e7-80ba-28f9a3f99ef2.png)

</details>

Я же заблокировав доступ к воспроизведению youtube (googlevideo.com) через расширение для Opera Adguard вижу вот подобное 

<details> <summary> screnshot </summary>

![image](https://i.paste.pics/74df1bf5173482ffe0baae4bff3bb1cb.png)

</details>

Если захожу просто через Chrome какобычно (включен Adguard для PC) у меня
в истории начинают появляться вотподобные записи :

<details> <summary> screnshots before and after </summary>
Без захода на сайт -

![image](https://i.paste.pics/f03e412fdcf017ae9a947de660a39999.png)

После захода -
![image](https://i.paste.pics/3d84dfb17b49e45404576cb39e59aec3.png)

</details>

Это что касается сайта Anistar.me. Теперь по поводу сайта animespirit.ru. Проблема
точно такая же, только блок рекламы не могу найти.

Information | value
--- | ---
Operating system: |  Windows NT 6.1.7601 Service Pack 1
Browser: | Chrome
Adguard version: | 6.1.331.1732
Adguard DNS: | None 
Adguard filters: | 2 3 4 1 14 6 7
Driver: | TDI
Ticket ID (if exists): | 1518164

**Comment by Alex-302** [comment]
Добавил:
*
```
||animespirit.ru/banners/
||uioopnblobble.ru^$third-party
```
*
```
||mujuclaster.ru^$third-party
```
