### ISSUE TITLE
stopgripp.ru - Missed ads

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6046]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: does not block ads
* **Current behaviour**: Tested at the following link:
[http://stopgripp.ru/bolezn/rheum/zalozhennost-nosa-lezha-po-utram.html](http://stopgripp.ru/bolezn/rheum/zalozhennost-nosa-lezha-po-utram.html)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29005199-8688b22e-7ade-11e7-819c-7ccbbefbfafa.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29005197-7aa0b8b2-7ade-11e7-8929-c4b20c3ce0eb.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS and Android
Browser: | Chrome
Adguard version: | 1.4.1 and 2.9.136
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On
Ticket ID (if exists): | 1150428

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
