### ISSUE TITLE
http://rustorka.com - redirects to random sites

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6047]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

### Current behavior

When navigating the site, it redirects you to random blank pages

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29006826-1de2ecea-7b00-11e7-8953-55de1ef7c0f9.png)

</details>

### Expected behavior

The issue does not occur.

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29006830-2e144ab4-7b00-11e7-973d-49bac15d9acf.png)

</details>

### Steps to reproduce the problem

1. Go to http://rustorka.com
2. LOG IN!!!
3. Go to the forum or somewhere else on the site
4. Redirects to http://lol.rumedia.ws/p/e7f64b8924/  or http://utarget.ru/ranging/18a7c76811/click/ or ...

### System configuration

Information | value
--- | ---
Operating system: | Windows
Browser: | Edge
Adguard version: | the current beta 
Adguard driver (Windows): | WFP
Adguard DNS: | Default
Stealth mode options(Windows) | Off
Adguard filters: | Russian, English, Spyware, SM, Annoyances
Ticket ID (if exists): | 1305364

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
We can't prevent this redirect.
