### ISSUE TITLE
http://ex-fs.com/ - pop-ups when clicking buttons in the player

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6048]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

### Current behavior

Opens other sites when pausing/resuming playback

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29007111-3496c60a-7b05-11e7-8c12-df22c4d9904c.png)

</details>

### Expected behavior

The issue does not occur.

### Steps to reproduce the problem

1. Go to http://ex-fs.com/ex_filmy/14761-.html
2. Start playing video
3. Pause it
4. Wait for some time and resume, should be opening malicious pages

### System configuration

Information | value
--- | ---
Operating system: | Windows
Browser: | Edge
Adguard version: | the current beta 
Adguard driver (Windows): | WFP
Adguard DNS: | Default
Stealth mode options(Windows) | Off
Adguard filters: | Russian, English, Spyware, SM, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It does not work on my side.

**Comment by evgeniy-ADG** [comment]
Works here, weird. It also needs some attention, a lot of banners and some fake 'download' button.

**Comment by Alex-302** [comment]
> a lot of banners

I need screenshot. I see onlu one banner under the player, no clickunders.

**Comment by evgeniy-ADG** [comment]
yep, confused it with the ex-fs.net. on this one there's a green button that downloads malware.
