### ISSUE TITLE
diariodemallorca.es - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6052]
***Site***: http://www.diariodemallorca.es/ -> http://micuenta.diariodemallorca.es/prok/info1/
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29008505-80318650-7b18-11e7-8e1d-902d09b6174d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
Spanish/Portuguese filter

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr The site takes over a minute to load (http://www.diariodemallorca.es/mallorca/2017/08/09/asociacion-alquiler-turistico-aconseja/1239085.html)
Maybe you can look into that as well?

[HAR.zip](https://github.com/AdguardTeam/AdguardFilters/files/1211094/HAR.zip)
