### ISSUE TITLE
kvn.ipb.su - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#6057]
http://kvn.ipb.su/

![image](https://user-images.githubusercontent.com/22892774/29024690-ed28bc3e-7b7b-11e7-8bfa-b8ed37ff2892.png)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard filters: | 1 2 3 4 5 14
Ticket ID: | 1498653

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
