### ISSUE TITLE
chowhound.com - Ad leftover - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6058]
***Site***: https://www.chowhound.com/food-news/186626/must-have-kitchen-gadgets-for-anyone-who-loves-bread
***Description***: Pinterest pictures missing. Ad leftovers in sidebar.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29025193-e49307f6-7b75-11e7-939f-7101bf06ad0b.png)

![image](https://user-images.githubusercontent.com/10995998/29025231-0a6dbaca-7b76-11e7-9d98-a5bdc99f715d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
