### ISSUE TITLE
Site detect I'm using an adblocker and I can't see the content inside

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#6062]
@Snake87r commented on [Mon Aug 07 2017](https://github.com/AdguardTeam/AdguardForAndroid/issues/1362)

When visiting this site:
http://www.kuronotranslations.com

I receive the message "It looks like you're using an ad blocker" and I have to disable adguard to see the site (they use this script to block adguard https://blockadblock.com/blockadblock_basic_script.php)

When visiting this other site:
https://lesyt.xyz/post/376

I receive this message: "Adblock detected!", I can see the content but they see i use Adblock and spamming to become a pro user and pay..
I think they use this script https://blockadblock.com/blockadblock_basic_script.php

### Your environment
* Adguard version: 2.9.136
* Adguard filtering mode: VPN
* Device model: Sony Xperia Z4 Tablet
* Operating system and version (e.g. Android 7.0)
* Not Rooted

---

@vozersky commented on [Mon Aug 07 2017](https://github.com/AdguardTeam/AdguardForAndroid/issues/1362#issuecomment-320724579)

@Snake87r have you tried our Annoyances filter?

**Comment by vozersky** [comment]
@Snake87r what filters do you use?

**Comment by Snake87r** [comment]
Hello, this is my filter setup:

- English Filter
- Spyware Filter
- Social Media Filter
- Annoyances Filter
- Mobile ads filter
- Simplified domain names filter
- EasyList Italy
- Anti-adblock killer | Reek

I've tried with and without "experimental filter"

**Comment by ghajini** [comment]
why not make solutions against blockadblock/fuckadblock  ***the generic*** without need to add each site to logic?

**Comment by AdamWr** [comment]
Added to English filter:
```
kuronotranslations.com#%#(function() { var sto = window.setTimeout, re = /\.bab_elementid.$/; window.setTimeout = function(a, b) { if ( typeof a !== 'string' || !re.test(a) ) { return sto(a, b); } }.bind(window); var signatures = [ ['blockadblock'], ['babasbm'], [/getItem\('babn'\)/], ['getElementById','String.fromCharCode','ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789','charAt','DOMContentLoaded','AdBlock','addEventListener','doScroll','fromCharCode','<<2|r>>4','sessionStorage','clientWidth','localStorage','Math','random'] ]; var check = function(s) { var tokens, match, j, token, pos; for ( var i = 0; i < signatures.length; i++ ) { tokens = signatures[i]; match = 0; for ( j = 0, pos = 0; j < tokens.length; j++ ) { token = tokens[j]; pos = token instanceof RegExp ? s.search(token) : s.indexOf(token); if ( pos !== -1 ) { match += 1; } } if ( (match / tokens.length) >= 0.8 ) { return true; } } return false; }; var realEval = window.eval; window.eval = function(a) { if ( !check(a) ) { return realEval(a); } var el = document.body; if ( el ) { el.style.removeProperty('visibility'); } el = document.getElementById('babasbmsgx'); if ( el ) { el.parentNode.removeChild(el); } }.bind(window); })();
kuronotranslations.com#@##banner_ad
@@||lesyt.xyz/themes/darkness/assets/js/ads.js
lesyt.xyz##.sb > .sb-item-group > .sb-item.island[-ext-has='.sb-item-title.bgc:contains(Advertisement)']
```
Please, check the result.

**Comment by Snake87r** [comment]
Ok, perfect, now everything works..
