### ISSUE TITLE
vgtv.no - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6064]
***Site***: http://www.vgtv.no/#!/video/144699/her-er-amalie-iuels-tre-beste-instagram-tips
***Description***: Ad before video.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29051641-7745f4a0-7be4-11e7-845a-e48804569ece.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
