### ISSUE TITLE
picturetopeople.org - Anti Ad blocker

### ISSUE THREAD

**Issue by cicku** [AdguardTeam/AdguardFilters#6066]
Use [this link](http://www.picturetopeople.org/image_utilities/watermark/online_digital_watermark_text.html) to generate watermarked pictures, failed with error.

![something went wrong](https://user-images.githubusercontent.com/686438/29054186-1c74702c-7c27-11e7-9d0e-1722cf7bf988.png)

**Comment by Alex-302** [comment]
Please fill the template.

**Comment by Alex-302** [comment]
Added to English filter
```
picturetopeople.org#@#.adsbox
```

**Comment by cicku** [comment]
thx.
