### ISSUE TITLE
https://www.xnxx.com/ (NSFW)

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6067]
Site: https://www.xnxx.com/video-h15f59e/glamcore_stepdaughter_creampied_after_fucking

***Description***: Remove ad space.

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
![screenshot_49](https://user-images.githubusercontent.com/19608513/29060054-38d5793a-7c29-11e7-806e-c9531e96642d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Google Chrome
Adguard version: | Browser Extension 2.6.7 (Stable)
Adguard driver (Windows): | 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): | 
Simplified filters(iOS) | 
Adguard DNS: | None | 
Adguard filters: | English filter, Russian filter, Turkish filter, Spyware filter, Annoyances filter, Social media filter
Ticket ID (if exists): |

**Comment by FadeMind** [comment]
```
xnxx.com##.mobile-only-hide
```

**Comment by Alex-302** [comment]
Added.
