### ISSUE TITLE
http://www.txxx.com/ (NSFW)

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6068]
Site: http://www.txxx.com/videos/4263457/exotic-japanese-girl-marika-2-in-horny-hairy-small-tits-jav-movie45585/

***Description***: Remove empty space.

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
![screenshot_52](https://user-images.githubusercontent.com/19608513/29060274-21d6ecf4-7c2a-11e7-8bbf-8add582fe207.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Google Chrome
Adguard version: | Browser Extension 2.6.7 (Stable)
Adguard driver (Windows): | 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): | 
Simplified filters(iOS) | 
Adguard DNS: | None | 
Adguard filters: | English filter, Russian filter, Turksih filter, Spyware filter, Annoyances filter, Social media filter
Ticket ID (if exists): |

**Comment by AdamWr** [comment]
Fixed.
