### ISSUE TITLE
http://vpondo.com/ (NSFW)

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6070]
Site: http://vpondo.com/Movie/heyzo-1465-hikari-asagiri-school-nurses-immoral-checkup-hikari-asagiri-9979?extepisode=1

***Description***: Click on play button, you will get a popup.

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Google Chrome
Adguard version: | Browser Extension 2.6.7 (Stable)
Adguard driver (Windows): | 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): | 
Simplified filters(iOS) | 
Adguard DNS: | None | 
Adguard filters: | English filter, Russian filter, Turksih filter, Spyware filter, Annoyances filter, Social media filter
Ticket ID (if exists): |

**Comment by AdamWr** [comment]
I can't reproduce.

**Comment by Alex-302** [comment]
Also not reproduced.
