### ISSUE TITLE
http://www.sexoasis.com/ (NSFW)

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6071]
Site: http://www.sexoasis.com/video/tight-wet-pussy-of-brunette-coed-gets-drilled-by-officers-huge-cock-from-behind-SQ2Lo8Mv98s.html

***Description***: Remove empty ad spaces.
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
![screenshot_58](https://user-images.githubusercontent.com/19608513/29060673-d0a4034c-7c2b-11e7-9191-77448a64b6d1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Google Chrome
Adguard version: | Browser Extension 2.6.7 (Stable)
Adguard driver (Windows): | 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): | 
Simplified filters(iOS) | 
Adguard DNS: | None | 
Adguard filters: | English filter, Russian filter, Turksih filter, Spyware filter, Annoyances filter, Social media filter
Ticket ID (if exists): |

**Comment by Alex-302** [comment]
fixed

**Comment by thislife81** [comment]
Site: http://www.sexoasis.com/video/tight-wet-pussy-of-brunette-coed-gets-drilled-by-officers-huge-cock-from-behind-SQ2Lo8Mv98s.html
Please remove this empty space.

![screenshot_129](https://user-images.githubusercontent.com/19608513/29210117-f97161ce-7ea2-11e7-8748-772952f5c8b6.png)
