### ISSUE TITLE
Meizu M6 Note: ads in system apps "Загрузка" and "Безопасность"

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#60725]
Reported by 1680926:

> В июле обновились 2 системных приложения на телефоне Meizu M6 Note (прошивка 7.1.1.0G) - "Загрузка" и "Безопасность" и стали показывать рекламу, которую, к сожалению, AdGuard пока ещё не блокирует. Сделал экспорт логов и сохранил apk-файлы этих приложений.

<details> <summary> Скриншоты </summary>

![image](https://user-images.githubusercontent.com/15856304/89147843-9c0e9700-d560-11ea-8c5d-148f7255b2a5.png)

![image](https://user-images.githubusercontent.com/15856304/89147848-a335a500-d560-11ea-9555-1b7aab82c19b.png)

</details>

**Comment by Eugene-Savenko** [comment]
Логи, настройки и файлы apk в crm.

**Comment by Alex-302** [comment]
@Eugene-Savenko Ничего нужного в логе не нашёл. Можно попробовать запретить этим приложениям доступ в сеть, и/или посмотреть через помощника куда они ломятся.

**Comment by Alex-302** [comment]
Приложения из архива у меня не устанавливаются.

**Comment by Alexei-Baciurin** [comment]
приветствую! отправил на почту ещё 1 лог, на этот раз в режиме "записывать всё".
теперь по вашим замечаниям:
-запрет на доступ в сеть не помогает,
-приложухи могут не устанавливаться из-за того, что наверное есть привязка к вендору,
в каждой из этих прог нашёл такую бяку "com.meizu.advertise.plugin.apk", в новом логе видно, что она (видимо) динамически устанавливается/удаляется и при этом ей выдаются дефолтные права - ну то есть по сути доступ в сеть... если эту бяку установить отдельно (у неё при этом интересное название - AppCenterSdk) и запретить этому приложения доступ в сеть - тоже почему-то не помогает...

**Comment by Alex-302** [comment]
@Alexei-Baciurin Привет.

> запрет на доступ в сеть не помогает,

попробуйте поэкспериментировать с запретом для других приложений. Предварительно экспортируйте настройки, чтоб потом не мучаться с возвратом "как было".

Также попробуйте в Адгарде добавить заведомо нерабочий прокси, и проверить что будет в этом случает. Важно при этом использовать режим локального VPN.

**Comment by Alexei-Baciurin** [comment]
1. пробовал выставлять запрет для других прог - всё работает как надо - проги жалуются на отсутствие инета...
2. на эти 2 прожки запрет инета (вифи/моб.) не действует.
3. попробовал добавить "заведомо нерабочий прокси" - у всех програм пропал инет, а у этих - нет!
прикладываю скрины и лог.
[adguard_logs_3.4.120_0608_074917.zip](https://github.com/AdguardTeam/AdguardFilters/files/5032643/adguard_logs_3.4.120_0608_074917.zip)
![S00806-07414536](https://user-images.githubusercontent.com/69235990/89492494-5f3ddc80-d7ba-11ea-9307-005af470628a.jpg)
![S00806-07415208](https://user-images.githubusercontent.com/69235990/89492498-606f0980-d7ba-11ea-92a6-b37435ebe560.jpg)

**Comment by Alex-302** [comment]
@Alexei-Baciurin отправьте любую жалобу через меню Адгарда и получившуюся ссылку добавьте сюда, чтоб увидеть ваши настройки.

**Comment by Alexei-Baciurin** [comment]
> 
> 
> @Alexei-Baciurin отправьте любую жалобу через меню Адгарда и получившуюся ссылку добавьте сюда, чтоб увидеть ваши настройки.

минуту назад отправил, надеюсь поможет! ;)

**Comment by Alex-302** [comment]
А ссылка где?

**Comment by Alexei-Baciurin** [comment]
я прошу прощения, это вы про эту? - https://github.com/AdguardTeam/AdguardFilters/issues/61342 - только такую смог получить...

**Comment by Alex-302** [comment]
Да, оно. При создании отчёта настройки автоматом прикрепляются. И с ними вроде всё нормально.
Остаётся только вручную запрещать-разрешать доступ в сеть и проверять результат. Подозреваю что какое-то из приложений часто обновляется, и заодно загружает рекламу.

**Comment by Alexei-Baciurin** [comment]
позволю себе указать ссылочку - [мой пост](https://4pda.ru/forum/index.php?showtopic=839339&st=27260#entry98795905) на известном всем нам форуме, где я попытался что-то где-то покопаться самостоятельно... может с теми линками, которые  на скринах, получится что-то сделать? ммм? иначе я не представляю, как с этим бороться.... =((

**Comment by Alex-302** [comment]
Какие именно линки? Вижу, что у других рекламы нет.

**Comment by Alexei-Baciurin** [comment]
1. на вышеуказанных скриншотах подсвечены ссылки на какие-то веб-сервисы, с которыми работает приложение "com.meizu.advertise.plugin", которое впихнуто в системные приложения "Загрузка" and "Безопасность".


2. к сожалению, у других тоже есть реклама: [https://4pda.ru/forum/index.php?act=search&query=%F0%E5%EA%EB%E0%EC%E0&username=&forums%5B%5D=746&topics=839339&source=pst&sort=rel&result=posts](url)

**Comment by Alex-302** [comment]
Ну по одному блокируйте доступ, или всем подозрительным сразу(в помощнике или журнале можно посмотреть что ломится в сеть).
com.meizu.advertise.plugin пробовали запретить доступ?
Также учтите, что реклама скорее всего ещё кэшируется, и просто так не пропадёт.

**Comment by Alexei-Baciurin** [comment]
так, по пунктам поехали:

**Comment by Alexei-Baciurin** [comment]
так, по пунктам поехали:
1. в журнале фильтрации ничего похожего не видно, и с включённым интернетом и с отключённым...
2. импортировал в пользовательские фильтры файл со всеми 19-ю линками из вышеуказанных скриншотов...
3. приложениям "Загрузка" and "Безопасность" запретил доступ к интеренту (в adguard-е)...
4. пакет com.meizu.advertise.plugin нигде не светится, поэтому что-либо запретить ему сложновато...
5. может она и кэшируется, но подтягивается с инета постоянно и это видно и по монитору трафика, и по свежим предложениям увеличить кхм-кхм понятно что ))) ...
6. в общем - полное впечатление, что adguard-а для этой бяки ПРОСТО НЕ СУЩЕСТВУЕТ - он ей игнорируется - будто его нет совсем!!!

в общем, я в большой-пребольшой печали, но готов к любому содействию, чем могу - логи там всякие и т.д. потому что боюсь, скоро многие будут так спокойно перепрыгивать защиту и мир опять погрузится в хаос...

**Comment by Alex-302** [comment]
Загружать рекламу может и системное приложение, для которого из-за проблем отключена фильтрация. Для пробы можно с помощью какого-нибудь файервола проделать то же самое, но с выкл. Адгардом, т.к. доступен только один VPN. Ну и рекламу могут загружать при обновлении приложений, или пачку рекламы в архиве, и показывать разную ничего не загружая.

**Comment by Alexei-Baciurin** [comment]
"пачку рекламы в архиве, и показывать разную ничего не загружая" - нет, в нашем случае всё качается онлайн...
" какого-нибудь файервола проделать то же самое, но с выкл. Адгардом, т.к. доступен только один VPN" - они тоже все работают через VPN, я попробовал Mobiwol Firewall - эффекта ноль...
"Загружать рекламу может и системное приложение, для которого из-за проблем отключена фильтрация" - значит, внедряя в обновления стоковых прог вот такие рекламные плагины, можно не парится по поводу установленных блокировщиков рекламы? это же фиаско!?! =(((

**Comment by Alex-302** [comment]
> "пачку рекламы в архиве, и показывать разную ничего не загружая" - нет, в нашем случае всё качается онлайн..

это не доказано. Как и обратное.

> они тоже все работают через VPN, я попробовал Mobiwol Firewall - эффекта ноль...
> это же фиаско!?! =(((

Если вы запретили другой программой, авторам которой про совместимость переживать не нужно, доступ в сеть, а реклама есть, значит более вероятно, что рекламу они загружают при обновлении каких-то приложений, или попросту реклама загружается с одного из основных доменов вместе с полезной информацией.

**Comment by Alexei-Baciurin** [comment]
> 
> 
> > "пачку рекламы в архиве, и показывать разную ничего не загружая" - нет, в нашем случае всё качается онлайн..
> 
> это не доказано. Как и обратное.
> 
> > они тоже все работают через VPN, я попробовал Mobiwol Firewall - эффекта ноль...
> > это же фиаско!?! =(((
> 
> Если вы запретили другой программой, авторам которой про совместимость переживать не нужно, доступ в сеть, а реклама есть, значит более вероятно, что рекламу они загружают при обновлении каких-то приложений, или попросту реклама загружается с одного из основных доменов вместе с полезной информацией.

кстати, вот перечитал этот тред, и заметил, что вы советовали только режим впн использовать, т.к. "режим локального прокси без рута приложения могут обходить(игнорировать).", так вот докладываю - с учётом того, что рут есть, попробовал переключить режим с локального впн на локальный прокси - и... реклама МОМЕНТАЛЬНО прекратилась! больше ничего не менял! те проги, которые её показывали - в адгуарде так и не фиксируются, всё по нулям... так что думаю, что реклама качается сразу, а не архивами и подгружает её тот самый "плагин", который встроен в эти приложения, так что хорошо, что выход нашёлся, но всё же жаль, что у прог уже есть действенная технология обхода файрволов...

**Comment by Alex-302** [comment]
Это не технология обхода. Могут банально загружать в удобные моменты - при подключении по WiFi или при иных условиях, либо пачкой, чтоб показывать разную рекламу независимо от подключения.
