### ISSUE TITLE
http://www.iceporn.com/ (NSFW)

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6072]
Site: http://www.iceporn.com/
***Description***: Click somehting, you will get a popup.

Site: http://www.iceporn.com/video/2070539/blonde-whores-share-big-cock
***Description***: Remove close and play button, and ad spaces.

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
![screenshot_64](https://user-images.githubusercontent.com/19608513/29060950-edee459c-7c2c-11e7-91de-23bf9089d479.png)

![screenshot_66](https://user-images.githubusercontent.com/19608513/29060964-fc98e408-7c2c-11e7-9576-cb2a256f647b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Google Chrome
Adguard version: | Browser Extension 2.6.7 (Stable)
Adguard driver (Windows): | 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): | 
Simplified filters(iOS) | 
Adguard DNS: | None | 
Adguard filters: | English filter, Russian filter, Turksih filter, Spyware filter, Annoyances filter, Social media filter
Ticket ID (if exists): |

**Comment by Alex-302** [comment]
fixed

**Comment by thislife81** [comment]
Site: http://www.iceporn.com/video/2070539/blonde-whores-share-big-cock
Please remove this adversiting place. 

![screenshot_127](https://user-images.githubusercontent.com/19608513/29210022-915f1c52-7ea2-11e7-856c-3e7c5d520174.png)
