### ISSUE TITLE
http://xpornotubes.com/ (NSFW)

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6073]
Site: http://xpornotubes.com/movies/xhamster/190479/german-granny-fuck/

***Description***: Remove empty space, and close button

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
![screenshot_68](https://user-images.githubusercontent.com/19608513/29061100-758a7fe8-7c2d-11e7-96a2-d9da1202b904.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Google Chrome
Adguard version: | Browser Extension 2.6.7 (Stable)
Adguard driver (Windows): | 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): | 
Simplified filters(iOS) | 
Adguard DNS: | None | 
Adguard filters: | English filter, Russian filter, Turksih filter, Spyware filter, Annoyances filter, Social media filter
Ticket ID (if exists): |

**Comment by Alex-302** [comment]
Fixed
