### ISSUE TITLE
http://hdxxnxx.com/ (NSFW)

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6076]
Site: http://hdxxnxx.com/reindeer-and-polar-bears-in-the-frozen-north-20533022.html?cat=Thai

***Description***: Remove close button

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
![screenshot_70](https://user-images.githubusercontent.com/19608513/29061647-c9c205a2-7c2f-11e7-84bd-c017b99d914b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Google Chrome
Adguard version: | Browser Extension 2.6.7 (Stable)
Adguard driver (Windows): | 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): | 
Simplified filters(iOS) | 
Adguard DNS: | None | 
Adguard filters: | English filter, Russian filter, Turksih filter, Spyware filter, Annoyances filter, Social media filter
Ticket ID (if exists): |

**Comment by Alex-302** [comment]
Fixed
