### ISSUE TITLE
http://xxxtubeset.com/ (NSFW)

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6077]
Site: http://xxxtubeset.com/?group=mov&go=best&category=thai&page=1&from=th.com#.WYls7tWCzIU

***Description***: Remove EMPTY spaces.

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
![screenshot_72](https://user-images.githubusercontent.com/19608513/29061778-43412dae-7c30-11e7-96c1-c6b21b216889.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Google Chrome
Adguard version: | Browser Extension 2.6.7 (Stable)
Adguard driver (Windows): | 
Adguard mode (Android): | 
Filtering quality (Android): | 
HTTPS filtering (Android): | 
Simplified filters(iOS) | 
Adguard DNS: | None | 
Adguard filters: | English filter, Russian filter, Turksih filter, Spyware filter, Annoyances filter, Social media filter
Ticket ID (if exists): |

**Comment by Alex-302** [comment]
Fixed
