### ISSUE TITLE
gmail.com is damaged. cannot display mails contents at all

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6078]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 
Gmail Web Mail cannot display messages contents at all.
![image-20170808-004](https://user-images.githubusercontent.com/9846948/29080874-462cd97e-7c61-11e7-9bc0-80068ffeac10.png)
<details><summary>Screenshot:</summary>

![image-20170808-003](https://user-images.githubusercontent.com/9846948/29080892-5689d060-7c61-11e7-93e2-e78c46e65f02.png)
</details>

* **Expected behaviour** (with disabled adguard on gmail.com site): 

![image-20170808-003](https://user-images.githubusercontent.com/9846948/29081032-bae0de1e-7c61-11e7-9268-af9694e6d2d5.png)

<details><summary>Screenshot:</summary>

</details>

***Steps to reproduce the problem***:

Open https://mail.google.com/ and random mail.

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome/60.0.3112.90
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP / TDI
Stealth mode options(Windows) | 
Adguard filters: | English, Spyware, Annoyances, Polish Lang Filters (inc. suplement), KAD, IDCAC (cookies)
Ticket ID (if exists): |

**Comment by AdamWr** [comment]
To był problem z polską listą - https://github.com/MajkiIT/polish-ads-filter/commit/50e0f031bceccc195cb97252c87b9d9d92a448a2#commitcomment-23532263
Spróbuj zaktualizować filtry, powinno rozwiązać problem.

**Comment by FadeMind** [comment]
@AdamWr  dziękuję ;)
