### ISSUE TITLE
minhaconexao.com.br - Anti AdBlock script

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6079]
***Description***:
* **Current behaviour**: 

Anti AdBlock Script on: 
http://www.minhaconexao.com.br/ 
Reproduced on our side

<details><summary>Screenshot:</summary>

![screen shot 2017-08-09 at 12 36 10 am](https://user-images.githubusercontent.com/28784344/29095770-c23fd7ee-7c9a-11e7-8746-9c20d8de9e94.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1.
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1476762

**Comment by ypetruk** [comment]
created the same issue on Adguard Extension depositary (sorry for this)
plz delete this issue

**Comment by AdamWr** [comment]
Maybe I misunderstood something, but in my opinion this is filter list issue, so I think it should be closed in Adguard Extension repository - https://github.com/AdguardTeam/AdguardBrowserExtension/issues/813
Added to Spanish filter:
`@@||minhaconexao.com.br/js/ads_detect.js`
`minhaconexao.com.br#%#window.canRunAds = true;`
