### ISSUE TITLE
minhaconexao.com.br - Anti AdBlock script

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#6080]
@ypetruk commented on [Wed Aug 09 2017](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/813)

***Description***:
* **Current behaviour**: 

Anti AdBlock Script on: 
http://www.minhaconexao.com.br/ 
Reproduced on our side

<details><summary>Screenshot:</summary>

![screen shot 2017-08-09 at 12 36 10 am](https://user-images.githubusercontent.com/28784344/29095770-c23fd7ee-7c9a-11e7-8746-9c20d8de9e94.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1476762

Active filters: English, spyware, annoyances, Spanish / Portuguese, Adblock alert installed, anti-adblock, malware and spam.
Other functions ACTIVATES: protection against phishing and malware And activate the most appropriate filters automatically

**Comment by AdamWr** [comment]
It should be fixed - https://github.com/AdguardTeam/AdguardFilters/issues/6079
