### ISSUE TITLE
нашбийск.рф

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6082]
Суть: третий обход тысячи сайтов
Отправитель: Забаненный по IP (разбаньте) Золотой Парень
Тип: пропущенная реклама
ПО: Хром+расширение+руИнгл фильтры
Скриншот: https://image.prntscr.com/image/QLVSgD-zTEq-KRYCYWItrA.png
Полный URL: главная http://нашбийск.рф/
Далее буду кидать по две ссылки в тему и указывать тип, когда неочевидно
СУТЬ: Заблокировать только баннеры (сибсоц)Банка и 2гис ибо проплаченные, а остальные ссылки либо на камеры либо на баланс проездного, либо ссылки на самих себя

**Comment by Adguarder** [comment]
Английский фильтр Версия 1.1.27.52. Обновлено 10 августа 2017 в 05:00.
Русский фильтр Версия 1.0.55.15. Обновлено 10 августа 2017 в 00:00.
Windows 10 x64
Chrome 60
Расширение

**Comment by Adguarder** [comment]
What is Cannot Reproduce?

**Comment by Alex-302** [comment]
![image](http://imagizer.imageshack.com/img924/6601/s8vcyp.png)
