### ISSUE TITLE
https://pikabu.ru/

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6085]
https://pikabu.ru/
https://image.prntscr.com/image/TZwRYRqdQPqmI-G0zkcKyQ.png

**Comment by Adguarder** [comment]
Английский фильтр Версия 1.1.27.52. Обновлено 10 августа 2017 в 05:00.
Русский фильтр Версия 1.0.55.15. Обновлено 10 августа 2017 в 00:00.
Windows 10 x64
Chrome 60
Расширение

**Comment by Adguarder** [comment]
То же самое, как и на ЯПлакал? Если скрыть одно, то и все пропадут?

**Comment by Alex-302** [comment]
Да. Можно скрыть только нижнюю, часть.

**Comment by Alex-302** [comment]
Не, здесь можно скрыть.
