### ISSUE TITLE
Bing Incorrect Blocking [AG Tracking Protection]

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardFilters#60897]
### List the website(s) you're having issues:

`https://www.bing.com/images/search`

### What happens?

Blank (black) page searching for an image:
https://streamable.com/dtpiez

### List Subscriptions you're using:

- AG Base
- AG Tracking Protection
- EasyList Italy

### Your settings

- OS/version: macOS
- Browser/version: Firefox
- Adblock Extension/version: uBlock0 - AdGuard Ext

### Problematic rule: 
`||bing.com/fd/ls/`

### Possible fix:
`@@||bing.com/fd/ls/$xmlhttprequest`

**Comment by Alex-302** [comment]
Not reproduced.
@AdguardTeam/filters-maintainers  please take a look.

**Comment by zloyden** [comment]
I can't check it on macOS, but on Windows with the config above on Firefox not reproduced.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/89516804-907dd300-d7e1-11ea-8a47-3d72edc5e10f.png)

</details><br/>

**Comment by superlex** [comment]
The issue is reproduced by another user on Windows, while other users cannot.
The problem for us is
`bing.com/fd/ls/lsp.aspx`

**Comment by Sergey-Lyapin** [comment]
I can't reproduce it with Mac OS and uBlock Origin with these filters

**Comment by superlex** [comment]
Ok guys, thanks anyway 👍
