### ISSUE TITLE
m.fishki.net - yandex direct

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6097]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

### Current behavior

Missed yandex direct ads on the site http://m.fishki.net/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29106995-b60911b6-7ce0-11e7-80f7-cfd760dc8dee.png)

![img_0830](https://user-images.githubusercontent.com/15856304/29107011-c807ae2c-7ce0-11e7-8e42-a3b323e18d2e.PNG)

</details>

### Expected behavior

The issue does not occur.

### Steps to reproduce the problem

1. Go to http://m.fishki.net/
2. Choose any article
3. Scroll down
4. See an ad

### System configuration

Information | value
--- | ---
Operating system: | iOS, Android
Browser: | Yandex, Chrome, Safari
Adguard version: | the current ones
Filtering method: | FULL
Filtering mode: | VPN
Adguard DNS: | Default
Adguard filters: | Russian, English, Spyware, SM, Annoyances
Ticket ID (if exists): | 1609220

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
