### ISSUE TITLE
https://vse.fm/

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6101]
https://vse.fm/station_119
Надо перейти на страницу и нажать на кнопку плей
получаем (скрин)
http://prntscr.com/g67j0k - "Отключите блокировщик рекламы и обновите страницу!"

гугл хром 60 расширение рус+инг фильтры

**Comment by Adguarder** [comment]
Просто надо нажать

**Comment by Adguarder** [comment]
Английский фильтр Версия 1.1.27.52. Обновлено 10 августа 2017 в 05:00.
Русский фильтр Версия 1.0.55.15. Обновлено 10 августа 2017 в 00:00.
Windows 10 x64
Chrome 60
Расширение

**Comment by Alex-302** [comment]
поправил
