### ISSUE TITLE
http://goldenshara.net/

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6102]
http://goldenshara.net/viewtopic.php?t=16122023
http://prntscr.com/g67lff

**Comment by Adguarder** [comment]
Английский фильтр Версия 1.1.27.52. Обновлено 10 августа 2017 в 05:00.
Русский фильтр Версия 1.0.55.15. Обновлено 10 августа 2017 в 00:00.
Windows 10 x64
Chrome 60
Расширение

**Comment by Alex-302** [comment]
поправил
