### ISSUE TITLE
http://miytvideo.ru/

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6104]
http://miytvideo.ru/
http://prntscr.com/g67myg
На*бное оповещение вк

**Comment by Adguarder** [comment]
Английский фильтр Версия 1.1.27.52. Обновлено 10 августа 2017 в 05:00.
Русский фильтр Версия 1.0.55.15. Обновлено 10 августа 2017 в 00:00.
Windows 10 x64
Chrome 60
Расширение

**Comment by Alex-302** [comment]
поправил

**Comment by Alex-302** [comment]
поправил
