### ISSUE TITLE
kinogo-x.net

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6105]
http://kinogo-x.net/704-adaptaciya.html
http://prntscr.com/g67nkx

**Comment by Adguarder** [comment]
Английский фильтр Версия 1.1.27.52. Обновлено 10 августа 2017 в 05:00.
Русский фильтр Версия 1.0.55.15. Обновлено 10 августа 2017 в 00:00.
Windows 10 x64
Chrome 60
Расширение

**Comment by Adguarder** [comment]
Кстати, можно ли сделать подпись как на форуме где я забанен?
Нудно копипастить

**Comment by Adguarder** [comment]
Появяется и с актуальными обновлениями

**Comment by Alex-302** [comment]
У меня чисто.
