### ISSUE TITLE
Duplicate rules

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#61064]
https://github.com/AdguardTeam/AdguardFilters/blob/6d81d9a3a48be554b3ef9b06970c5b4d3b87c123/TurkishFilter/sections/specific.txt#L579

https://github.com/AdguardTeam/AdguardFilters/blob/6d81d9a3a48be554b3ef9b06970c5b4d3b87c123/TurkishFilter/sections/specific.txt#L840

---

https://github.com/AdguardTeam/AdguardFilters/blob/6d81d9a3a48be554b3ef9b06970c5b4d3b87c123/TurkishFilter/sections/specific.txt#L2961

https://github.com/AdguardTeam/AdguardFilters/blob/6d81d9a3a48be554b3ef9b06970c5b4d3b87c123/TurkishFilter/sections/general_url.txt#L1

**Comment by AdamWr** [comment]
Fixed, thank you.
