### ISSUE TITLE
Question about filters

### ISSUE THREAD

**Issue by a-privacy-conscious-user** [AdguardTeam/AdguardFilters#61075]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed

### Problem Description

It's not really a request for a feature but a question. If I use an ad blocker that uses EasyList and I find an ad that is not blocked then I report it and EasyList adds rules to their dataset, will you guys see that change in EasyList and add it to your lists? AdGuard does not use EasyList directly but your filters mention that they are based on EasyList. I ask this question for efficiency when reporting missing ads. Since the vast majority of adblocker rely on EasyList I wanted to know if reporting an issue to them directly would also benefits AdGuard users. I use adguard too and I like it, but its not really convenient to report the same issue to EasyList and to you guys if I can do it just once. So, if I find an ad that is neither blocked by EasyList nor AdGuard, can I just report it to them and be sure that you guys somehow will also find that report and fix it too? Like do you keep in touch with EasyList rules additions?

### Proposed Solution

If adguard is not in synced with easylist rules I would recommend to do so, and if it is, please let me know so I just report issues to easylist instead of double reports

### Alternatives Considered

N/A

### Additional Information

N/A

**Comment by llacb47** [comment]
> I use adguard

"Adblock Extension/version: AdBlock Plus"


https://github.com/easylist/easylist/issues/5921

**Comment by a-privacy-conscious-user** [comment]
I use multiple adblockers. I also said "I use adguard TOO" I open issues on multiple products to help make them better. What I am asking here is exactly related to that, if I open issues on easylist (which is used by adblock plus among others) is it necessary to open them on adguard as well?

**Comment by a-privacy-conscious-user** [comment]
the whole goal is to reach as many products (and hence help as many users as possible) with just one report. For example, adblock,adblock plus,ghostery,ubloc,ublock origin,brave,opera, etc they all use easylist so with 1 report I cover all of them. If adguard confirms that they keep tabs on easylist rules to improve their, then by reporting to easylist I am also helping improve adguard

**Comment by llacb47** [comment]
To answer your question, the main adblocking filter in adguard is a combination of Adguard base and easylist. 

However, many sites cannot be fixed elegantly by easylist since EL cannot use scriptlet rules. Therefore, you should also report unblocked popups to uAssets and this repo so they can add scriptlet rules.

**Comment by a-privacy-conscious-user** [comment]
So for regular domain blocking its okay to just report it to EasyList and AdGuard will catch up?

But for popup blocking or other complex situations I should also report it here https://github.com/uBlockOrigin/uAssets and here https://github.com/AdguardTeam/AdguardFilters 

Thanks

**Comment by Yuki2718** [comment]
Yes, EasyList is basically synced so if you reported to EL no need to report that to AG too. Basically means there are some exception that AG has disabled some rules on EL.

> So for regular domain blocking its okay to just report it to EasyList and AdGuard will catch up?
> 
> But for popup blocking or other complex situations I should also report it here https://github.com/uBlockOrigin/uAssets and here https://github.com/AdguardTeam/AdguardFilters
> 

Not 100% correct, as many popups can be blocked by simple rules. It's solely if the issue requires advanced syntax. If you can't determine it someone will forward the issue to a responsible place.

**Comment by a-privacy-conscious-user** [comment]
Excellent! Thanks for the explanation. This saves me some time when reporting issues. I will proceed to close this issue now.
