### ISSUE TITLE
http://simpsonsua.com.ua/

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6108]
http://simpsonsua.com.ua/sezon-11/307-11-sezon-16-seriia.html
http://prntscr.com/g67r3h
купить вроде бы не релевантная реклама

**Comment by Adguarder** [comment]
Английский фильтр Версия 1.1.27.52. Обновлено 10 августа 2017 в 05:00.
Русский фильтр Версия 1.0.55.15. Обновлено 10 августа 2017 в 00:00.
Windows 10 x64
Chrome 60
Расширение

**Comment by Alex-302** [comment]
поправил
