### ISSUE TITLE
http://imageban.ru/

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6110]
http://imageban.ru/
https://image.prntscr.com/image/ThbcbrnyQuezYo_J0m4SKw.png

**Comment by Adguarder** [comment]
Английский фильтр Версия 1.1.27.52. Обновлено 10 августа 2017 в 05:00.
Русский фильтр Версия 1.0.55.15. Обновлено 10 августа 2017 в 00:00.
Windows 10 x64
Chrome 60
Расширение

**Comment by Alex-302** [comment]
Чисто.

**Comment by Adguarder** [comment]
Зайди с русским IP, видно у меня

**Comment by Adguarder** [comment]
Через прокси, расширение, 11 числа в 00:00 обновлены те же фильтры
http://nfwwcz3fmjqw4ltsou.cmle.ru/ с зарубежным айпи появляется

**Comment by Alex-302** [comment]
> http://nfwwcz3fmjqw4ltsou.cmle.ru/

этот поправил

**Comment by Adguarder** [comment]
да зачем прокси поправлять
imageban надо было поправить
прокси просто скинул чтобы проверить как будет с зарубежного айпи

**Comment by Alex-302** [comment]
http://imageban.ru/ и так чист

**Comment by Adguarder** [comment]
ну я вижу все равно

Антибаннер Количество правил фильтрации: 36879
Английский фильтрВерсия 1.1.27.69. Обновлено 11 августа 2017 в 22:00.
Русский фильтрВерсия 1.0.55.24. Обновлено 11 августа 2017 в 22:00.

http://imageban.ru/template/img/alkov.jpg вот адрес баннера

**Comment by Alex-302** [comment]
проверь
```
imageban.ru##noindex a[rel="nofollow"] > img
||imageban.ru/template/img/alkov.jpg
```

**Comment by Adguarder** [comment]
Да уже проверял заранее работает
