### ISSUE TITLE
chatovod.ru

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6111]
Удалить тему во имя их Админа после решения проблемы
Пора бы снова прибрать рекламу
http://chatovod.ru/chats/
https://image.prntscr.com/image/wDVBezJNTrCpSONa2TG4XA.png

http://chatovod.ru/
http://prntscr.com/g67szu
На главной точно два баннера можно убрать, хостинг и форум отношения к партнерам не имеют

**Comment by Adguarder** [comment]
Английский фильтр Версия 1.1.27.52. Обновлено 10 августа 2017 в 05:00.
Русский фильтр Версия 1.0.55.15. Обновлено 10 августа 2017 в 00:00.
Windows 10 x64
Chrome 60
Расширение

**Comment by Alex-302** [comment]
поправил.

**Comment by Adguarder** [comment]
В каталоге чатов не заблокировано с последними фильтрами, на главной всё так же висит большой баннер и проплаченные партнёры
