### ISSUE TITLE
http://hitfm.ru/

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6113]
https://image.prntscr.com/image/abmIK_2TQjSk4fz6BLrUmA.png
http://hitfm.ru/

**Comment by Adguarder** [comment]
Английский фильтр Версия 1.1.27.52. Обновлено 10 августа 2017 в 05:00.
Русский фильтр Версия 1.0.55.15. Обновлено 10 августа 2017 в 00:00.
Windows 10 x64
Chrome 60
Расширение

**Comment by Alex-302** [comment]
Без Адгарда так же.

**Comment by Adguarder** [comment]
Неправда

**Comment by Adguarder** [comment]
Без расширения-то как раз не так же, есть там картинки

Даже обновив до Английский фильтрВерсия 1.1.27.63. Обновлено 11 августа 2017 в 06:00.
Русский фильтрВерсия 1.0.55.22. Обновлено 11 августа 2017 в 00:00.

не появляется, как на скрине

**Comment by Alex-302** [comment]
Повторилось.
