### ISSUE TITLE
tvc.ru

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6116]
Хром60,руИнгФильтры,Расширение

http://www.tvc.ru/channel/onair/
Плеер не стартует, вечно крутится
Размеры плеера позволяют не скидывать скрин

**Comment by Alex-302** [comment]
Пока всё закрою. Обработаю правильно оформленное - переоткрою.

**Comment by Adguarder** [comment]
Английский фильтр Версия 1.1.27.52. Обновлено 10 августа 2017 в 05:00.
Русский фильтр Версия 1.0.55.15. Обновлено 10 августа 2017 в 00:00.
Windows 10 x64
Chrome 60
Расширение

**Comment by Alex-302** [comment]
Не повторяется.

**Comment by Adguarder** [comment]
Повторяется, пока ВРУЧНУЮ не нажмёшь два раза на кнопку плей

**Comment by Alex-302** [comment]
У меня он автоматом стартует. Точно не используешь никаких расширений для предотвращения автозапуска?

**Comment by Adguarder** [comment]
Нет. У конкурентов такая же проблема https://forums.lanik.us/viewtopic.php?f=102&t=32218 - так же делаю - проходит

**Comment by Alex-302** [comment]
Ну не повторяется никак.
