### ISSUE TITLE
http://m.biquzi.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6117]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behavior**: Missed ads here: http://m.biquzi.com/wapbook/16588_8510951.html

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29111223-0e8e4200-7cf2-11e7-9bf2-c105ec4127c5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | ios
Browser: | safari
Adguard version: | 1.3.0.81
Simplified filters(iOS) | Off
Adguard DNS: | None
Ticket ID (if exists): | 1473214

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.26.59 Enabled=YES
- ID=3 Name="Spyare filter" Version=1.0.13.62 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.21.75 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.16.31 Enabled=NO
- ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.10 Enabled=NO
- ID=11 Name="Mobile Ads filter" Version=1.0.9.17 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES
- ID=101 Name="EasyList" Version=1.0.74.39 Enabled=YES
- ID=118 Name="EasyPrivacy" Version=1.0.84.72 Enabled=YES
- ID=104 Name="EasyList China" Version=1.0.85.3 Enabled=YEs

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
