### ISSUE TITLE
telecinco.es - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6118]
***Site***: http://www.telecinco.es/ -> http://www.telecinco.es/informacionPublicidad.html
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29115367-b40ee414-7cf7-11e7-98a5-0400eea7a9e4.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
Spanish/Portuguese filter

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr Other sites of the same company (Mediaset España) use the exact same adblock detection:

- http://www.cuatro.com/
- http://www.mtmad.es/
- http://www.eltiempohoy.es/
- http://www.factoriadeficcion.com/
- http://www.energytv.es/
- http://www.bemad.es/
- http://www.divinity.es/

If you want me to open separate issues for each site that's fine, but I thought it would just be easier that way.

**Comment by AdamWr** [comment]
Fixed.
