### ISSUE TITLE
fdesouche.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6119]
***Site***: http://www.fdesouche.com/875737-hauts-de-seine-vehicule-recherche-apres-renverse-groupe-de-militaires-de-loperation-sentinelle-a-levallois-perret
***Description***: 

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29115470-1797ce7e-7cf8-11e7-9602-21f593e8bede.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
French filter

**Comment by AdamWr** [comment]
Fixed.
