### ISSUE TITLE
https://ebonus.gg/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6120]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

### Current behavior

The site detects ad blockers, here: https://ebonus.gg/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29115576-cbb9eb6e-7d00-11e7-9730-e3b22a184e65.png)

![image](https://user-images.githubusercontent.com/15856304/29115809-89b3b758-7d01-11e7-9354-ce7fb0785b72.png)

</details>

### Expected behavior

The issue does not occur.

### Steps to reproduce the problem

1. Go to https://ebonus.gg
2. Choose a task, for instance, click on AdGateRewards option
3. See what is on the second screenshot above

### System configuration

Information | value
--- | ---
Operating system: | Windows
Browser: | Edge and Chrome
Adguard version: | the current beta 
Adguard driver (Windows): | WFP
Adguard DNS: | Default
Stealth mode options(Windows) | Off
Adguard filters: | Russian, English, Spyware, SM, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Added to English filter:
`adgaterewards.com#%#Object.defineProperty(window,'adblockIsEnabled',{value:false});`
`@@||adgaterewards.com/assets/js/vc/advertisement.js|$~third-party`
`@@||asmwall.com/js/ads.js|$~third-party`
`ebonus.gg#@#.adsbox
`
