### ISSUE TITLE
gutefrage.net cookie banner

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#61248]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Cookie banner with scroll blocked
`https://www.gutefrage.net`
`https://www.autofrage.net`
`https://www.computerfrage.net`
`https://www.finanzfrage.net`
`https://www.gesundheitsfrage.net`
`https://www.motorradfrage.net`
`https://www.reisefrage.net`
`https://www.sportlerfrage.net`
the gutefrage cookie banner coming from `consent.gutefrage.net`

<img width="673" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/89785998-862e4280-db1b-11ea-9817-59f4970ac9e3.PNG">

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | win 10
Browser:                               | Opera
AdGuard version:                       |  3.4.31
Filters enabled:                       | default + Adgaurd Tracking protection + AdGuard germany + AdGuard Annoyances
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Removed. This rule breaks scrolling(UK IP)
@stanislav-atr better make CSS rules.
