### ISSUE TITLE
visitnorway.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6124]
***Site***: https://www.visitnorway.com/about/photos-videos/
***Description***: Cookie notice at the bottom right.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29116926-c15d031c-7cfc-11e7-90fa-8d6b70586b98.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.379.1984
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by FadeMind** [comment]
I don't see cookies msg. But I found empty boxes ads:
```
visitnorway.com##div.contentRender_name_plugins_dtn_ad
```

For blocking Cookies see List **I don't care about cookies** (available in adguard)

**Comment by danidoedel** [comment]
@FadeMind Annoyance filter is for cookie stuff, not some 3rd party crap

**Comment by FadeMind** [comment]
@danidoedel  So, annoyance should adopt whole IDCAC code and fix up all mess.

**Comment by danidoedel** [comment]
@FadeMind Not sure why you are telling me that tbh

**Comment by AdamWr** [comment]
Fixed.
