### ISSUE TITLE
filehippo.com - Annoyance - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6125]
***Site***: http://filehippo.com/de/download_ccleaner
***Description***: Something is weird with the video button ;)

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29117281-ede6e8e8-7cfd-11e7-8c50-1dc4bf41ef57.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by FadeMind** [comment]
Please try
```
@@||vzaar.com^$domain=filehippo.com
```

**Comment by AdamWr** [comment]
Fixed.
