### ISSUE TITLE
http://inews.ifeng.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6126]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behavior**: Missed ads here: http://inews.ifeng.com/51580912/news.shtml?&back

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29118543-0489f9c0-7d0b-11e7-9124-b19b8dd7d4eb.png)

![image](https://user-images.githubusercontent.com/15856304/29118547-0f5fd3c4-7d0b-11e7-8b38-91b910813ac4.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | ios
Browser: | safari
Adguard version: | 1.3.0.81
Simplified filters(iOS) | Off
Adguard DNS: | None
Ticket ID (if exists): | 1609456

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.27.32 Enabled=NO
- ID=3 Name="Spyware filter" Version=1.0.13.70 Enabled=NO
- ID=4 Name="ocial media filter" Version=1.0.21.95 Enabled=NO
- ID=14 Name="Annoyances filter" Version=1.0.16.65 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.21 Enabled=NO
- ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES
- ID=15 Name="Simplified domain names filter" Version=1.0.1.95 Enabled=YES
- ID=104 Name="EasyList China" Version=1.0.85.39 Enabled=YES
- ID=238 Name="Adblock & uBlock polish filter - Adguard supplement" Version=1.0.0.4 Enabled=YES

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
The last ad is not reproduced.
Added to Annoyances filter
```
inews.ifeng.com##.openApp[onclick^="loadOpen.init(download"]
```
Added to English filter
```
inews.ifeng.com##.luckybag
```
Please check.
