### ISSUE TITLE
http://www.focus.de/ - ads are not blocked in the desktop version

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6127]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behavior**: Blocked in the mobile version, missed in the desktop one. The link: http://www.focus.de/regional/erfurt/facebook-post-aus-erfurt-frau-spricht-obdachlosen-an-was-sie-von-ihm-erfaehrt-sollte-uns-zu-denken-geben_id_7449268.html

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29118951-df13bc88-7d0c-11e7-8edb-b67be095aae5.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

1. Go [here](http://www.focus.de/regional/erfurt/facebook-post-aus-erfurt-frau-spricht-obdachlosen-an-was-sie-von-ihm-erfaehrt-sollte-uns-zu-denken-geben_id_7449268.html)
2. Request the desktop view
3. Scroll down and see the banner

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.3.0.100
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | 2 3 4 6 11 12 14 15
Ticket ID (if exists): | 1609733

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
