### ISSUE TITLE
[nsfw] [adblock detect][overlay] extremetube.com  mofosex.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6128]
1.  Removing shadow on player when pause video with advertisment places.

```
extremetube.com##.vjs-inplayer-overlay
```

2. Adblock Detected @ mofosex.com

![image-20170809-008](https://user-images.githubusercontent.com/9846948/29121299-48546f84-7d0e-11e7-8c57-9b35e47997dc.png)

Hiding msg:
```
mofosex.com##.attentionMsg
```
Setup:
Lastest Google Chrome Stable + Adguard For Windows Beta + Adguard Chrome Extension (lastest)

![image-20170809-009](https://user-images.githubusercontent.com/9846948/29121415-c028143e-7d0e-11e7-8915-38141be72a1b.png)

**Comment by AdamWr** [comment]
Added to English filter:
```
extremetube.com##.vjs-inplayer-overlay
extremetube.com##.underplayer-wrapper > p[style="text-align: center"]
mofosex.com##.thumb-list-5 > .auto[style="width: 950px; margin: 20px auto;"] > div[style="clear:both; text-align:center;"]
||soska.us/api/get_link?$domain=mofosex.com
||cdn1-static-extremetube.spankcdn.net/js/pht2/pht2.js
extremetube.com#%#document.cookie = "popundr=1";
mofosex.com#%#document.cookie = "popundr=1";
```
Added to Annoyances filter:
`mofosex.com##.attentionMsg`
