### ISSUE TITLE
gidonline.club - Missed Ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6129]
http://gidonline.club/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29124571-f5f42fe0-7d21-11e7-95c2-04ec92c6c957.png)

</details>

***System configuration***

Application version: 1.3.0.81
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.17.73 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.1 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.19.41 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.12.68 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.51.5 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.8.34 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.11 Enabled=YES
 
Ticket ID: 1610009

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
На iOS не убрать, правила CSS не поддерживаются.
