### ISSUE TITLE
cnnturk.com

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#61305]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

Anti adblock

https://www.cnnturk.com/teknoloji/karantinadaki-insanlar-mobil-uygulama-ile-izlenecek

<details><summary>Screenshot:</summary>

![www cnnturk com](https://user-images.githubusercontent.com/69504642/89879363-82f28f80-dbcb-11ea-8f22-e5d65714bbb6.png)

</details>

<details><summary>Screenshot:</summary>

![www cnnturk com (1)](https://user-images.githubusercontent.com/69504642/89879386-8d148e00-dbcb-11ea-8a73-8524eb33fa7e.png)

</details>

**Filters:**

```
AdGuard Base
Adguard Tracking Protection
AdGuard Annoyances
AdGuard Social Media
AdGuard Turkish
```

Information                            | Value
---                                    | ---
Browser:                               | Chrome 84
AdGuard version:                       | 3.4.31 Browser extension

---

This rule seems to work :

`||hit.duhnet.tv/event$domain=cnnturk.com`

**Comment by Sergey-Lyapin** [comment]
can't reproduce
@AdguardTeam/filters-maintainers please take a look

**Comment by AdamWr** [comment]
Blocked trackers, but I couldn't reproduce anti-adblock.
