### ISSUE TITLE
bysp.pw - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6131]
http://www.bysp.pw/?m=vod-type-id-1-pg-85.html

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29127041-99296e36-7d28-11e7-8267-7b3f7165bbfb.png)

</details>

***System configuration***

Application version: 1.3.0.100

Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.42 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.70 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.97 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.67 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.85.45 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.3.53 Enabled=YES

PRO:
Pro feature DISABLED.
Tunnel mode SPLIT
DNS server: System Default

Ticket ID: 1609942

**Comment by Alex-302** [comment]
Can't open it on my end via VPN.
@adam Can you check it?(or find the rules, which block ads on desktop or Android)

**Comment by AdamWr** [comment]
Added to English filter:
`bysp.pw##a[href^="http://xz.98qr.cn/"] > img`
`bysp.pw##a[href^="http://t1.ugg66.com/"][target="_blank"]`
`||ugg66.com/*/*.gif$domain=bysp.pw`
`||yezilm.com/vs.php$domain=bysp.pw`
`||sinaimg.cn/*/*.gif$domain=bysp.pw`
`||bysp.pw/template/baoyusp-wap/js/wapad.js`
