### ISSUE TITLE
youtube.com whitelist rule

### ISSUE THREAD

**Issue by ArenaL5** [AdguardTeam/AdguardFilters#61314]
***Description***: Youtube watchtime rule (which is probably unnecesary) is undiscriminately overruled by an exception.

***Disclaimer.*** I am using [uBlock Origin](https://github.com/gorhill/uBlock/). Maybe this filter is working as intended in AdGuard; if so, both programs are interpeting the `domain=` attribute differently, and new unambiguous attributes should be chosen for all URL-based blockers.

* **Current behaviour**: 

Currently, YouTube videos are embedded via an iframe. This can be embedded inside _another_ iframe (to collect user statistics, I presume). In my example, the iframe's target is
```
https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F_d5VyQdgVWQ%3Ffeature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D_d5VyQdgVWQ&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F_d5VyQdgVWQ%2Fhqdefault.jpg&key=fb41a818ac2c11e1a3424040aae4d8c9&type=text%2Fhtml&schema=youtube
```
which itself generates an iframe to `https://www.youtube.com/embed/_d5VyQdgVWQ?wmode=opaque&enablejsapi=1&origin=https%3A%2F%2Fcdn.embedly.com&widgetid=1`

This situation confuses uBlock Origin, who determine the domain of the request in the screenshots as `youtube.com`, thus activating the whitelist rule in the screenshots.

<details><summary>Screenshot:</summary>

![filter](https://user-images.githubusercontent.com/37388405/89896715-73744600-dbcd-11ea-8409-9ad55c4acac7.png)
Long strings of alphanumeric characters censored. For some reason, YouTube misreports my OS (possibly the default Firefox fingerprinting defenses)
![filter_detail](https://user-images.githubusercontent.com/37388405/89896724-74a57300-dbcd-11ea-9b3c-f429886f30e2.png)

</details><br/>

* **Expected behaviour**: 

I expect that request to be blocked in any other sites outside YouTube. The easiest way to do this is probably to replace the domain attribute by a match on substring `c=WEB_EMBEDDED_PLAYER`.

Or, if possible, to be blocked everywhere. Before disabling it for test purposes, I browsed the internet using an experimental filter for [Request Control](https://github.com/tumpio/requestcontrol), which redirected that request to `https://www.youtube.com/api/stats/watchtime?c=WEB_EMBEDDED_PLAYER` without losing any functionality, suggesting the whitelist rule is not really necessary.

(Before deciding on that, run some tests while logged in a Google account. I most often watch videos without logging in.)

***Steps to reproduce the problem***:

1. Open `https://knowyourmeme.com/videos/223296-dogs`.
2. Open uBlock Origin's request logger in another tab and point it to that page (title is "Bogey losing his mind to be outside. | Dogs | Know Your Meme").
3. Go back to the tab in step 1, and click the embedded video to watch it.

***System configuration***

**Filters:** uBlock filters, uBlock filters – Badware risks, uBlock filters – Privacy, uBlock filters – Resource abuse, uBlock filters – Unbreak, EasyList, AdGuard Tracking Protection, EasyPrivacy, Fanboy’s Enhanced Tracking List, Online Malicious URL Blocklist, uBlock filters – Annoyances, spa, por: AdGuard Spanish/Portuguese, spa: EasyList Spanish

Information                            | Value
---                                    | ---
Operating system:                      | GNU/Linux Debian
Operating system version (Android/iOS) | 10.5 "Buster"
Browser:                               | Firefox Quantum 68.11.0esr (64-bit)
uBlock Origin version:                       | v1.28.4

**Comment by Yuki2718** [comment]
EasyPrivacy very recently removed the blocking rule due to an issue: https://github.com/easylist/easylist/commit/4630b99c4dcfa8a8732a1a59ff352094571188ef

**Comment by Alex-302** [comment]
Removed blocking and whitelist rule.
