### ISSUE TITLE
paraphrasing-tool.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6132]
***Site***: http://paraphrasing-tool.com/
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29127230-cd700a36-7d20-11e7-9ef8-cd2b3d57f842.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
