### ISSUE TITLE
istories.media

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdguardFilters#61321]
Поделиться в двух местах + подписка.  
https://istories.media/investigations/2020/08/03/tselevaya-auditoriya-kak-chinovniki-otpravlyayut-svoikh-detei-uchitsya-v-prestizhnie-vuzi-bez-konkursa/

<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/50718960/89926301-58c1c180-dc0d-11ea-9840-6458c29e3d6e.png)
![2](https://user-images.githubusercontent.com/50718960/89926311-5bbcb200-dc0d-11ea-80ae-113347feab3f.png)

</details><br/>

**Comment by zubrRB** [comment]
На главной ещё подписка https://istories.media

<details><summary>Screenshot:</summary>

![-](https://user-images.githubusercontent.com/50718960/89984393-01116d80-dc82-11ea-9c70-d59d94b62fa0.png)
</details><br/>

**Comment by Alex-302** [comment]
ок
