### ISSUE TITLE
beIN SPORTS TR app - doesn't show videos

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#6133]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: App doesn't show videos with a Mobile Ads filter enabled
* **Current behaviour**: App doesn't show videos - black screen

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screenshot_20170809-184252](https://user-images.githubusercontent.com/28726429/29131068-53088458-7d34-11e7-87db-a37a28b72e6a.png)

</details>
<br>

* **Expected behaviour**: Videos should play with no issues

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

***Steps to reproduce the problem***:

1. Install [beIN SPORTS TR app](https://play.google.com/store/apps/details?id=com.digiturk.ligtv)
2. Turn Adguard only with a Mobile Ads filter enabled
3. Find any videos in an app and play

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android
Adguard version: | 2.9.136
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default)
Adguard DNS: | None
Adguard filters: | 11

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
@@||imasdk.googleapis.com/native/core/*/native_bridge__en.js$app=com.digiturk.ligtv
```
