### ISSUE TITLE
webnovel.com - Annoyance - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6135]
***Site***: https://www.webnovel.com/
***Description***: Cookie notice at the bottom.

Also adblock detection (https://www.webnovel.com/book/6831839002000405/21635291458627841). Sroll down and click watch ad for next chapter.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29145138-1c8911a4-7d5c-11e7-87cd-9e482da35da2.png)

![image](https://user-images.githubusercontent.com/10995998/29145200-66923212-7d5c-11e7-9107-3eb7a451543a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Cookie notice fixed.
I need more time for antiadblock.

**Comment by AdamWr** [comment]
Temporary solution:
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=webnovel.com`
`@@||pagead2.googlesyndication.com/pagead/js/r*/show_ads_impl.js$domain=webnovel.com`
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=webnovel.com`
`||yueimg.com/c/=/*/js/chapter/index*.js$replace=/r\.initSkipTimer\(o\,(.|..)\)/r\.initSkipTimer\(o\,3\)/,important`
Maybe later I find something better.

**Comment by ghajini** [comment]
@AdamWr

Something like this

script=
https://pastebin.com/DSMJN8m3

source=
http://forum.novelupdates.com/threads/qidian-adblock.43828/

**Comment by Alex-302** [comment]
@AdamWr can we close it?

**Comment by AdamWr** [comment]
I think yes, this rule can be added to user filter:
<details>

`webnovel.com#%#if('function'==typeof fetch){setInterval(function main(){[].forEach.call(document.querySelectorAll('.cha-content._lock'),function(a){a.classList.remove('_lock');var b=a.closest('.chapter_content').querySelector('.lock-video');b&&b.remove();var c=a.querySelector('.cha-words');c.style.opacity='0.1';var d=window.location.href.split('/book/')[1].split('/')[0],e=a.querySelector('[data-cid]').dataset.cid;return d&&e?fetch('https://www.webnovel.com/apiajax/chapter/GetChapterContentToken?bookId='+d+'&chapterId='+e).then(function(f){return f.json()}).then(function(f){return f.data.token}).then(function(f){return encodeURIComponent(f)}).then(function(f){return new Promise(function(g){function h(){fetch('https://www.webnovel.com/apiajax/chapter/GetChapterContentByToken?token='+f).then(function(k){return k.json()}).then(function(k){i=k.data.content.trim(),i?g(i):setTimeout(h,1e3)}).catch(function(k){console.error(k.stack),h()})}var i='';h()})}).then(function(f){var g=f.split('\n').map(function(h){return h.trim()}).filter(function(h){return!!h}).map(function(h){return'<p>'+h+'</p>'}).join('');c.innerHTML=g,c.style.opacity='1'}).catch(function(f){console.error(f.stack)}):void 0})},1e3)}`

</details>
