### ISSUE TITLE
ebookdz.com

### ISSUE THREAD

**Issue by Zardangus** [AdguardTeam/AdguardFilters#61355]
Hi, all.

I had the same issue mounths ago and @zloyden and @Alex-302 had fixed it. See the issue number
ebookdz.com # 57547 at : 
https://github.com/AdguardTeam/AdguardFilters/issues/57547#issuecomment-645966121

When i go to www.ebookdz.com, Adguard is detected and i have to disable it. If i don't want to,  i can't go on the website.

That's the Screenshot :
![Screenshot_20200812_122445_com kiwibrowser browser](https://user-images.githubusercontent.com/67057008/90005871-290bcb80-dc98-11ea-9570-528fb4cd928d.jpg)

Thank you for your help to Fix it again :) 
Regards.

**Comment by AdamWr** [comment]
Hi,
Do you have an account on this website and are you logged in?
If so, could you please log out and then check if you still see this anti-adblock notice?

**Comment by Zardangus** [comment]
> Hi,
> Do you have an account on this website and are you logged in?
> If so, could you please log out and then check if you still see this anti-adblock notice?

Hi, 
Yes i have and i am. 
I will try and come back.

**Comment by AdamWr** [comment]
I'm asking about that, because I can't reproduce this issue and as I recall, in the past this anti-adblock notice was displayed only for logged users. Unfortunately creating an account is disabled now.

**Comment by Zardangus** [comment]
> I'm asking about that, because I can't reproduce this issue and as I recall, in the past this anti-adblock notice was displayed only for logged users. Unfortunately creating an account is disabled now.

I did what you asked me (logg out, try, log in) and it works well, i don't have the anti-adblock notice. Thank you.
I will relember this way next time.  😁

**Comment by AdamWr** [comment]
To be honest, I would like to fix in a better way, but unfortunately I can't reproduce it.
I'm glad that re-logging fixed the problem.
Please reopen this issue if it will be needed.

**Comment by Zardangus** [comment]
> To be honest, I would like to fix in a better way, but unfortunately I can't reproduce it.
> I'm glad that re-logging fixed the problem.
> Please reopen this issue if it will be needed.

Sure, i understand. What do you need to reproduce it? You must have an account on this website?

**Comment by AdamWr** [comment]
I think that they display this anti-adblock message only for logged users, so I guess that account is needed, but if I understand correctly, creating new accounts is disabled at the moment.

**Comment by Zardangus** [comment]
> I think that they display this anti-adblock message only for logged users, so I guess that account is needed, but if I understand correctly, creating new accounts is disabled at the moment.

Yes, creating New account is disabled now. But if you want, i can get you my logins. Whats thé way to send them to you in private?

**Comment by AdamWr** [comment]
Ok, if you want I can try to check it with an account.
You can send it in private message on forum https://forum.adguard.com/index.php?members/adam.3968/ or via e-mail to `adam@adguard.com`

**Comment by Zardangus** [comment]
> Ok, si tu veux, je peux essayer de le vérifier avec un compte.
> Vous pouvez l'envoyer en message privé sur le forum https://forum.adguard.com/index.php?members/adam.3968/ ou par e-mail à`adam@adguard.com`

I sent you an email. I hope it will be usefull for you.

**Comment by AdamWr** [comment]
Ok, I received the message and I will check it.
Thank you.

**Comment by AdamWr** [comment]
Hmm, it seems that rule which is already in AdGuard Base filter should blocks this anti-adblock notice.
Could you please check if in AdGuard's settings you have `AdGuard Base filter`, `HTTPS filtering` and `High quality filtering method` enabled?

**Comment by Zardangus** [comment]
> Ok, j'ai reçu le message et je vais le vérifier.
> Je vous remercie.

You're welcome 😊

**Comment by Zardangus** [comment]
> Hmm, it seems that rule which is already in AdGuard Base filter should blocks this anti-adblock notice.
> Could you please check if in AdGuard's settings you have `AdGuard Base filter`, `HTTPS filtering` and `High quality filtering method` enabled?

I don't find "high quality filtering method" in "HTTPS filtering. 

Here are two screens, you can see what i have :

![Screenshot_20200812_200443_com adguard android](https://user-images.githubusercontent.com/67057008/90051015-4e6bfa00-dcd7-11ea-8ff7-9d70c1d69f5e.jpg)


![Screenshot_20200812_200503_com adguard android](https://user-images.githubusercontent.com/67057008/90051032-562b9e80-dcd7-11ea-99e9-8de1141e852c.jpg)


Is it OK ? 🤔

**Comment by AdamWr** [comment]
Yes, it's OK.
So if you don't see this anti-adblock notice anymore then I guess that it was one time issue.

**Comment by Zardangus** [comment]
> Oui c'est OK.
> Donc, si vous ne voyez plus cet avis anti-adblock, je suppose que c'était un problème ponctuel.

OK, thank you. 
I hope so. 
If i have again this issue i will come back here to ask help. 
Thank a lot 🙏
Be safe.
