### ISSUE TITLE
Pruffme.com - can't access content 

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6136]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Не заходит в вебинарную комнату 
* **Current behaviour**: У пользователей сайта pruffme.com возникла проблемка со
входом в вебинарную комнату и возможностью создавать и проводить вебинары,
участвовать в них, загружать презентацию, включать видео и звука, поскольку
добавлено у многих ваше расширение в браузере.
Можно вас попросить добавить наш сайт (https://pruffme.com) в список
надёжных?

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Information | value
--- | ---
Ticket ID: | 1610035

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Нужно подробное описание как повторить, скриншот и список фильтров.

**Comment by vitbortnik** [comment]
Ответа от пользователя нет. 
Откроем, если будет дополнительная информация.
