### ISSUE TITLE
parlament.ch - incorrect blocking

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6137]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: page gets damaged by Russian Filter. 
* **Current behaviour**: enabling Russian Filter breaks the page. 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29156592-68e4862e-7dab-11e7-81c7-1bdae1c73ab9.png)
</details>

* **Expected behaviour**: Should be working just fine. 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![screen shot 2017-08-10 at 9 12 18 am](https://user-images.githubusercontent.com/30041399/29156731-174e5302-7dac-11e7-8e94-c8fc79f854b3.png)

</details>

***Steps to reproduce the problem***: visit parlament.ch having Russian filter enabled. 

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Ticket ID (if exists): | 1609615

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Added to Russian filter:
`@@||parlament.ch/_layouts/*/Branding/`
