### ISSUE TITLE
Flightradar24 - missed ads/incorrect blocking

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6139]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: При нажатии на какой то самолет сверху выскакивает черный баннер
https://appsto.re/ru/7ZgYw.i 

* **Current behaviour**: Проблема воспроизводиться при нажатии на любой самолет в программе. 
DNS логи прикреплены к тикету. 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29162213-702e7e38-7dc1-11e7-8c08-e49746756717.png)

</details>

***System configuration***

Information | value
--- | ---
OS: | iOS
Adguard DNS: | Default 
Ticket ID: | 1602225

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
На айпаде не повторяется.
Время появления не указано. Но подозреваю, что это высовывается встроенная заглушка. Что на её месте без Адгарда?
@zebrum можешь глянуть?

**Comment by vitbortnik** [comment]
@Alex-302 
Пользователь прикрепил к тикету дополнительные скриншоты и новые логи с указанным временем воспроизведения.

**Comment by Alex-302** [comment]
Сложно по иосному логу проверить.
Какая там реклама без Адгарда?
Если фейсбучная, то можно прпробовать добавить в чёрный список `graph.facebook.com`, но это сломает сам FB.

**Comment by Alex-302** [comment]
Встроенная заглушка для гугловой рекламы.
