### ISSUE TITLE
[Android] No crop for Instagram

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#614]
https://play.google.com/store/apps/details?id=com.rcplatform.nocrop&hl=en

Реклама в приложении.

https://qcrm.cc/#/customer/1017542

**Comment by Alex-302** [comment]
Сейчас мы не можем полноценно блокировать рекламу.
Если не пользуется фейсбуком, пусть попробует в пользовательский фильтр добавить:
||fbexternal-a.akamaihd.net^$empty
||graph.facebook.com^$empty
