### ISSUE TITLE
google.de - Ad leftover

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6140]
https://www.google.de/amp/m.oe24.at/oesterreich/chronik/oberoesterreich/Prostituierte-betrog-Opfer-um-400-000-Euro/294281253/amp

<details><summary>Screenshot:</summary>

![screen shot 2017-08-10 at 3 21 08 pm](https://user-images.githubusercontent.com/27292111/29170089-b0a0cb06-7ddf-11e7-9661-9c92bba9a30e.png)

</details>

***System configuration***

Application version: 1.3.0.100
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.52 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.72 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.98 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.71 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.4 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.23 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID: 1480792

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
