### ISSUE TITLE
kurier.at - Social share widgets and ad leftover

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6141]
https://www.google.de/amp/s/m.kurier.at/amp/politik/ausland/fluechtlinge-im-wahlkampf-schnappatmung-in-oesterreich-scheuklappen-in-deutschland/278.774.120

<details><summary>Screenshot:</summary>

![screen shot 2017-08-10 at 3 27 24 pm](https://user-images.githubusercontent.com/27292111/29170283-7fb61644-7de0-11e7-91f3-8ab1c0bc9951.png)
![screen shot 2017-08-10 at 3 27 35 pm](https://user-images.githubusercontent.com/27292111/29170284-8114b5ea-7de0-11e7-8c0f-5bae71e27702.png)
![screen shot 2017-08-10 at 3 27 45 pm](https://user-images.githubusercontent.com/27292111/29170287-82838e1a-7de0-11e7-9b08-13dc9c3a6792.png)

</details>

***System configuration***

Application version: 1.3.0.100
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.52 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.72 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.98 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.71 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.4 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.23 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID: 1480792

**Comment by AdamWr** [comment]
Added:
`m-kurier-at.cdn.ampproject.org##.c-adcontainer`
`m-kurier-at.cdn.ampproject.org##.c-share `
