### ISSUE TITLE
mobil.news.at - Ad leftover and ads

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6143]
https://mobil.news.at/a/fiaker-verbot-8259095
https://mobil.news.at/

<details><summary>Screenshot:</summary>

![screen shot 2017-08-10 at 3 44 04 pm](https://user-images.githubusercontent.com/27292111/29170797-d7299994-7de2-11e7-913a-6ff2951fe7a0.png)
![screen shot 2017-08-10 at 3 44 11 pm](https://user-images.githubusercontent.com/27292111/29170802-d99c08ce-7de2-11e7-8586-6fc555082bbf.png)
![screen shot 2017-08-10 at 3 44 21 pm](https://user-images.githubusercontent.com/27292111/29170803-d9b6a29c-7de2-11e7-9f3b-7a25fe5e2eaa.png)
![screen shot 2017-08-10 at 3 44 29 pm](https://user-images.githubusercontent.com/27292111/29170804-d9d241be-7de2-11e7-8218-50f9b2e35648.png)

</details>

***System configuration***

Application version: 1.3.0.100
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.52 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.72 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.98 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.71 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.4 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.23 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID: 1480792

**Comment by AdamWr** [comment]
Fixed.
