### ISSUE TITLE
mail.yahoo.com

### ISSUE THREAD

**Issue by emberweave** [AdguardTeam/AdguardFilters#61441]
There was an issue with these ads appearing at the top of my yahoo mail. They disappeared for quite a while after my first report, but they returned again yesterday. I don't know what has happened or what is different, but they're still here today.
I wrote a message on the old report, but it's closed, so I don't know if that message will get through, so I am writing here as well.

[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by emberweave** [comment]
![ads have returned on yahoo mail](https://user-images.githubusercontent.com/66972118/90156959-1d350d80-dd5b-11ea-8a93-59a6e18e2cae.jpg)

**Comment by Alex-302** [comment]
@emberweave Hi. Please post the link to your previous report.

**Comment by krystian3w** [comment]
this: https://github.com/AdguardTeam/AdguardFilters/issues/57666

**Comment by krystian3w** [comment]
### Possible:

Leftover `div` with: `Watch the most popular movies on Yahoo`

```
! new interface "mail.yahoo.com/d/folders/2"
mail.yahoo.com#?#div[data-test-id="efv-header"]:has(~ div[data-test-id="video-container"]) > div[data-test-id="efv-subheader"]
```
```
! legacy interface "mail.yahoo.com/b/folders/2"
mail.yahoo.com#?##messageListContainer div[class]:has(~ div#video-player > iframe)
```

---

### Possible

jumping mails on list due hide ads after ~30 sec. by Yahoo script:

```
mail.yahoo.com#$#div[data-test-id="virtual-list"] > ul > li.p_a { position: static !important; }
```

**Comment by Alex-302** [comment]
Probably need remote access to fix it.



> ! new interface

How to enable it?

**Comment by krystian3w** [comment]
For my enough after logon use:

`https://mail.yahoo.com/d/`

* `/b/` - legacy

* `/d/` - new/latest layout.

**Comment by Alex-302** [comment]
I don't see that button:(
![image](https://user-images.githubusercontent.com/8361299/90689152-3f0d2380-e278-11ea-832a-6ce5d5636b99.png)

**Comment by Alex-302** [comment]
Found in https://mail.yahoo.com/b/

**Comment by Alex-302** [comment]
I see leftovers only. Blocked them.

**Comment by krystian3w** [comment]
IMO you have ad leftover here:

![obraz](https://user-images.githubusercontent.com/35370833/90689513-7d9ee000-e270-11ea-90df-a6e58ee3be14.png) |
--- |

I don't insist on forcing static positioning - the gap itself disappears after ~30 seconds, if someone doesn't scroll quickly the list jump won't be annoying.

With me, it can only be eliminated faster by repositioning (like `position: static`).

---


> `:contains(popular videos on Yahoo)`

Sad = only with an English-interface so far.

**Comment by Alex-302** [comment]
Hm. I don't see that leftover with $elemhide exclusion. 
How to switch lang here?

**Comment by krystian3w** [comment]
Change language can be found on "Yahoo account **preferences**":

`https://login.yahoo.com/account/preferences`


After change refresh webmail interface and will be have e.g. German language.

>`Die beliebtesten Videos auf Yahoo ansehen`

---

webmail may no support `?lang=` atrrib in URL.

**Comment by Alex-302** [comment]
Thanks, replaced rules.
