### ISSUE TITLE
mobil.vol.at - Cookie message at the bottom

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6144]
http://mobil.vol.at/#!dashboard

<details><summary>Screenshot:</summary>

![screen shot 2017-08-10 at 3 49 05 pm](https://user-images.githubusercontent.com/27292111/29170977-8161f05a-7de3-11e7-92e9-d8bf3b86e69d.png)

</details>

***System configuration***

Application version: 1.3.0.100
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.52 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.72 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.98 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.71 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.4 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.23 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
Fixed
