### ISSUE TITLE
young-pussy.com [NSFW] [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#61492]
http://www.young-pussy.com/video/amazing-nadia-ali-just-loves-to-play-with-black-cocks-1029.html

Ads seen on the page. Please also check for pop-ups. Checked with AG extension for Chrome

https://i.imgur.com/iTgLrgg.png

**Comment by Alex-302** [comment]
Indian porn-farm.

**Comment by Nzzyme** [comment]
> Indian porn-farm.

?
