### ISSUE TITLE
http://tree.tv/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#615]
Антиадблок на сайте.

https://qcrm.cc/#/customer/836093

**Comment by Alex-302** [comment]
Добавил
tree.tv#%#function checkAddBlock() {};

**Comment by shaurmanchic** [comment]
They have implemented new scripts
![4a36a0f2cf37](https://cloud.githubusercontent.com/assets/14258460/17026929/813659c0-4f6a-11e6-9327-ec34aba050a6.jpg)
![script](https://cloud.githubusercontent.com/assets/14258460/17026933/86c83ad4-4f6a-11e6-9e53-e80b2986edce.PNG)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||player.3tv.im/js/vast/video.ads.js
@@||tree.tv/imgs/reklama.png
@@||actionrtb.com/static/bc.js$domain=tree.tv
@@||ssp.c8.net.ua/getcode.php$domain=player.3tv.im
@@||ua2cdn.admixer.net/test1/*.mp4$domain=player.3tv.im
@@||inv-nets.admixer.net/*.aspx?$domain=player.3tv.im
||actionrtb.com^$third-party
||api.tree.tv/getreklama?$replace=/\[([\s\S])+]/[]

```

**Comment by vgavrish** [comment]
Расширение. Антиадблок в видео
http://tree.tv/film/23749-dva-ottsa-i-dva-syina-sezon-3
Фильтры: 1,2,3,4,5,14
![screenshot_77](https://cloud.githubusercontent.com/assets/18548949/17641716/819f352c-6134-11e6-9c47-0a0b4845a475.jpg)

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||c8.net.ua/b/*$domain=player.3tv.im
```

**Comment by altokarev** [comment]
С расширением показывает анти-adblock сообщение. С приложением всё ОК.

URL:

http://tree.tv/film/25136-ostatki-ostavlennyie-sezon-3

<details><summary>Screenshot:</summary>

![screen shot 2017-06-01 at 17 40 52](https://cloud.githubusercontent.com/assets/28726429/26685572/3298808c-46f3-11e7-896c-50171b3698f8.png)

</details>

<br>
***System configuration***

Information | Value
--- | ---
Operating system: | MacOS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard filters: | 1, 2, 3, 4, 12, 14

**Comment by Alex-302** [comment]
Added to Russian filter
```
@@||inv-nets.admixer.net/dsp.aspx$domain=player.tree.tv
@@||ua2cdn.admixer.net^$domain=player.tree.tv,media
```
video preroll will be unblocked

**Comment by altokarev** [comment]
The problem is still here. @Alex-302 please take a look. Anti-adblock thingey appears only with extension.

**Comment by Alex-302** [comment]
fixed

**Comment by wormax1** [comment]
hello. message about blovking not show, but with adguard video not load...
![xvt](https://user-images.githubusercontent.com/29804924/27752773-6592e3ec-5deb-11e7-904e-5061daafbedb.jpg)

**Comment by Alex-302** [comment]
@wormax1 Adguard for Windows or browser extension?

**Comment by wormax1** [comment]
@Alex-302 browser. but in firefox work with latest updated lists. in chrome not work. try reinstall exstension in chrome - nothing changed. in slimjet work, in SWiron-not work. maybe problem at my pc...

**Comment by wormax1** [comment]
@Alex-302 idk what happened. but at chrome work too. sorry for disturb.

**Comment by wormax1** [comment]
@Alex-302 hello agaim :) rec video. in chrome not work
http://www.dailymotion.com/video/x5tg98p
