### ISSUE TITLE
http://8ch.net/ - Incorrect Blocking - Mac

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6150]
***Description***:
* **Current behaviour**: 

Adguard breaks the website http://8ch.net/index.html
Disabling protection- hepls to open the website correctly, please take a look at the screenshots:
Reproduced on our side

<details><summary>Screenshot with Adguard enabled:</summary>

![screen shot 2017-08-10 at 4 50 55 pm](https://user-images.githubusercontent.com/28784344/29173888-5176e0a8-7ded-11e7-8a89-7b1db7dc6c1f.png)

</details>

<details><summary>Screenshot with Adguard disabled:</summary>

![screen shot 2017-08-10 at 4 51 14 pm](https://user-images.githubusercontent.com/28784344/29173913-638993da-7ded-11e7-9eb0-2dc9cf54196c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 497927

**Comment by AdamWr** [comment]
Unfortunately I can't reproduce this on Windows.
@Alex-302 could you please check it?

**Comment by Alex-302** [comment]
Added
```
!+ PLATFORM(mac)
@@||8ch.net^$elemhide,jsinject,content
```
it is not caused by filters. Maybe a bug.

**Comment by Alex-302** [comment]
@altokarev
