### ISSUE TITLE
dybee.cn -Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6151]
http://www.dybee.cn/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29175982-38cfecce-7df3-11e7-8dda-5825a48d8bc5.png)

</details>

***System configuration***

Application version: 1.3.0.81
Device: iPad
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.53 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.72 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.98 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.71 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.1.95 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.85.53 Enabled=YES

Ticket ID: 1610726

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce.
@zebrum blease check on iPhone with the same filters.

**Comment by Alex-302** [comment]
Added
```
||js.69lm.com.cn^$third-party
||dd.70yst.com^$third-party
```
