### ISSUE TITLE
http://hdfilmevreni.co/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6154]
**Site**: http://hdfilmevreni.co/wtf-2017-izle.html/

***Description***: Remove **EMPTY** space and **Sidebar** ad.

<details><summary>Screenshot:</summary>

![screenshot_111](https://user-images.githubusercontent.com/19608513/29207650-11214fe2-7e98-11e7-893b-fdb371e3f015.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
Fixed.
