### ISSUE TITLE
missed ads in search engines

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6155]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Смотрите, пожалуйста, всю информацию в тикете. Там достаточно много приложенных отчетов, логов и скриншотов. 
"реклама в гугл Гугл и Яндекс поиске"

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29206346-3d19af4e-7e8a-11e7-80d6-2d5645c933e1.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29206359-4d76e744-7e8a-11e7-822b-37d6a3673848.png)

</details>

***Steps to reproduce the problem***:
"написал в Гугл курту , Мтс банк и выдал маршруты с рекламой"
"в яндекс поиск вбиваете : куда сходить в москве с ребенком и выдает кучу рекламы , почему?"

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android
Adguard version: | 2.9.136
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On
Adguard filters: | 2, 3, 4, 14, 1, 11
Ticket ID (if exists): | 1150428

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня не повторяется.
В нашем чате отписался.

**Comment by vitbortnik** [comment]
@Alex-302 
Пользовател уточнил ситуацию: 
Проблема именно в Яндекс и Гугл поисках (приложениях) и стандартном браузере на Samsung j5 2016. 
Просит решения этих проблем, если это возможно конечно.

**Comment by Alex-302** [comment]
именно в приложениях не выйдет, по крайней мере с гуглом точго.
Дай ссылку на приложение Яндекса, гляну.

**Comment by vitbortnik** [comment]
https://play.google.com/store/apps/details?id=ru.yandex.searchplugin&hl=en

**Comment by Alex-302** [comment]
Что-то выловить рекламу не выходит. Попроси HAR. Может получится JSON подправить.

**Comment by vitbortnik** [comment]
[adguard.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1224745/adguard.har.zip)


<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/30041399/29311376-70325ff6-81ba-11e7-8bf2-0a3ba70c5933.png)

</details>

<details><summary>Screenshot:</summary>

![2](https://user-images.githubusercontent.com/30041399/29311389-7d2b80c0-81ba-11e7-8560-d013c1922dde.png)

</details>

<details><summary>Screenshot:</summary>

![3](https://user-images.githubusercontent.com/30041399/29311399-8a64e088-81ba-11e7-9b66-0102603d6b31.png)

</details>

<details><summary>Screenshot:</summary>

![4](https://user-images.githubusercontent.com/30041399/29311408-906efe5a-81ba-11e7-8774-9770979ca4e9.png)

</details>

**Comment by Alex-302** [comment]
@vitbortnik

**Comment by vitbortnik** [comment]
@Alex-302 
Пользователь сообщил, что "добавил, но реклама все равно проскакивает"
Приложены свежие скриншоты

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29370196-5422aa20-82ad-11e7-8369-d880e4de0950.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29370216-5bf431f6-82ad-11e7-8581-cfe7e0d91f30.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29370219-5f84f378-82ad-11e7-9660-8ebf5719fb56.png)

</details>

**Comment by Alex-302** [comment]
@vitbortnik 
ещё попытка)
```
||yandex.*/searchapp?$important,replace=/<div\sclass="serp-item\st-construct-adapter__adv.*<\/span><\/div><\/div><\/div><\/div><\/div>/
```

**Comment by vitbortnik** [comment]
@Alex-302 
"Результат плачевный . Пропуски." 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29461341-0ef48f6c-8434-11e7-85c6-cc14c50ef5a8.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29461350-12a70a18-8434-11e7-97ea-5eacafb553ce.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29461358-16fe18fe-8434-11e7-9b5e-254e6b8000d4.png)

</details>

**Comment by Alex-302** [comment]
А есть новый HAR? Старое правило было удалено? Это обязательно с текущей версией.

**Comment by vitbortnik** [comment]
Да, я просил пользователя заменить старое правило этим. 
Запросить у него новый HAR?

**Comment by Alex-302** [comment]
Да, нужен новый HAR с одним только этим правилом.

**Comment by vitbortnik** [comment]
[adguard.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1234833/adguard.har.zip)

"Два образовалось почему то...оба прикрепил"

Также свежие скриншоты: 
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29465814-3eda3268-8443-11e7-93dd-dbe259438416.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29465828-44cda1be-8443-11e7-97ee-d39bf9e58654.png)

</details>

**Comment by Alex-302** [comment]
Вот ещё вариант:
```
||yandex.ru/searchapp?app_version_name=$important,replace=/<div\sclass="serp-item\st-construct-adapter__adv\sserp-adv-item"/<div style="display: none;"/
```
предыдущие правила нужно удалить

**Comment by Alex-302** [comment]
@vitbortnik ну что?

**Comment by vitbortnik** [comment]
@Alex-302 
Пользователь молчит после последнего предложения добавить правило (21 августа). 
Дам знать, если сообщит что-то.

**Comment by Alex-302** [comment]
Ладно, закрываю тогда. У меня адрес, к которому применяется правило, не отображается, проверить не могу.
