### ISSUE TITLE
http://www.limitsizdayi.org/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6156]
**_Site_**: http://www.limitsizdayi.org/pc-aksiyon-oyunlari/1714-just-cause-3-cpy-torrent-oyun-indir.html/

***Description***: Remove **BANNERS** and **BOX** for facebook.

<details><summary>Screenshot:</summary>

![screenshot_114](https://user-images.githubusercontent.com/19608513/29207060-bd34f8ae-7e95-11e7-8f20-2f06dfd09e18.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
Fixed.
