### ISSUE TITLE
Yahoo Finance app on Android shows adds

### ISSUE THREAD

**Issue by Dummyxl** [AdguardTeam/AdguardFilters#61578]
Hi there.
I use adguard on android and working great.

But 2 weeks or so yahoo finance is showing adds. Can you fix that please?

https://play.google.com/store/apps/details?id=com.yahoo.mobile.client.android.finance

Greetings
Ralph

**Comment by Alex-302** [comment]
Hi. Please send report from AdGuard menu and attach resulting link here.

**Comment by Dummyxl** [comment]
I'm not really sure what you mean. Can you help a bit more what steps to take?

**Comment by Alex-302** [comment]
@Dummyxl Hi.
Menu -> Support -> Send Feedback
![image](https://user-images.githubusercontent.com/8361299/90540997-aa78c780-e18a-11ea-9964-25bda57fc941.png)
settings will be attached automatically.

**Comment by Dummyxl** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/61793

**Comment by Alex-302** [comment]
Please add this rule `||m.yap.yahoo.com^` to User Rules and restart Yahoo app. This is for test.

**Comment by Dummyxl** [comment]
I add it, and will test it. The problem is that re entering the beta takes time. The next app update will push the beta.. So I report back when yahoo finance beta is installed again. 

![Screenshot_20200819-235042](https://user-images.githubusercontent.com/69516716/90694252-9f03ca00-e278-11ea-921d-eca25571945a.jpg)

**Comment by Alex-302** [comment]
It is already in filters)
