### ISSUE TITLE
https://zamundatorrentr.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6157]
**_Site_**: https://zamundatorrentr.com/index.php

***Description***: Remove this **BANNER**

<details><summary>Screenshot:</summary>

![screenshot_118](https://user-images.githubusercontent.com/19608513/29208855-d2385618-7e9c-11e7-8a71-24bf68f9a57e.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
Fixed.
