### ISSUE TITLE
history.com - Social widgets - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6161]
***Site***: http://www.history.com/news/newly-discovered-blueprints-may-allow-legendary-wwii-plane-to-fly-again
***Description***: Social share icons and newsletter banners.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29212723-50ea99c8-7ea0-11e7-8530-38fd573b31af.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr Thanks! There is now some ad leftover at the top:

![image](https://user-images.githubusercontent.com/10995998/29466729-4b53c216-843e-11e7-80e2-03821a303dbb.png)

**Comment by AdamWr** [comment]
Ok, fixed.
