### ISSUE TITLE
m.sweclockers.com - Ad leftover

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6162]
http://m.sweclockers.com

<details><summary>Screenshot:</summary>

<img width="386" alt="screen shot 2017-08-11 at 6 34 32 pm" src="https://user-images.githubusercontent.com/27292111/29220458-c2c1df70-7ec3-11e7-9575-272f901d5f63.png">

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Chrome / FireFox
Adguard version: | 2.9.136
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): | ON (whitelist)
Adguard filters: | 2, 4, 14, 11, 15, 211, 223
Ticket ID: | 1456058

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Added to Mobile filter list:
`m.sweclockers.com##.header > .container > #topBanner`
