### ISSUE TITLE
cutwin.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6163]
***Site***: http://cutwin.com/9O50Jby
***Description***: Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29222117-7a53621a-7ec1-11e7-80d3-0e6a614aee14.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr There is now adblock detection, this rule seems to work here as well: `@@/js/ads.js$~third-party,domain=cutwin.com`

**Comment by AdamWr** [comment]
Ok, added to English filter:
`@@||cutwin.com/js/ads.js`
