### ISSUE TITLE
aetv.com - Social Widgets - Annoyance - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6164]
***Site***: http://www.aetv.com/shows/leah-remini-scientology-and-the-aftermath/season-1/episode-9
***Description***: Adblock detection. Social share icons. Newsletter sign up.

Adblock detection may apply for other sites of the A+E network as well (couldn't test because of geo restriction or account needed exept mylifetime.com and fyi.tv):

http://www.mylifetime.com/shows/date-night-live/season-1/episode-3
http://www.fyi.tv/shows/in-bed-with-simon/season-1/episode-13
https://www.viceland.com/en_us/video/nuts-and-bolts-stop-motion/596fd4350b478b9271f01f8d?playlist=57a204a28cb727dec795136b
http://www.history.com/shows/alone/season-4/episode-9

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29222185-c872c936-7ec1-11e7-84a9-bbe6b9bb72ab.png)

![image](https://user-images.githubusercontent.com/10995998/29222235-f6238da2-7ec1-11e7-8fc8-a3cd4cfac7b6.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
