### ISSUE TITLE
linkvertise.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#61650]
***Description***: Anti Adblock on `https://linkvertise.com/24388/SpotifyAccount?o=sharing`
<img width="763" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/90338788-6a7bde00-dfec-11ea-986e-41ddf8b2766f.PNG">

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Opera
AdGuard version:                       | 3.4.31
Filters enabled:                       | default + tracking protection + Adguard germany + Adguard annonyances
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Hi
I see this popup only
![image](https://user-images.githubusercontent.com/8361299/90507060-f06b6680-e15d-11ea-84bc-0a591cc5175b.png)

**Comment by JobcenterTycoon** [comment]
Where the black background coming from? Looks like we need another person to check

**Comment by Alex-302** [comment]
That's because they show dozens of dark overlays:) 
@AdguardTeam/filters-maintainers please take a look.

**Comment by BlazDT** [comment]
Also only seeing that overlay.

Please try this rule:

`@@||linkvertise.com/assets/ads.js`

**Comment by JobcenterTycoon** [comment]
it works

**Comment by BlazDT** [comment]
Added
