### ISSUE TITLE
Конфликт с DDoS protection by Cloudflare

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/AdguardFilters#61657]
Циклическая перезагрузка страницы о перенаправлении. Уже ранее встречалось и описывалось здесь #61089
Новый https://ont.by. Если временно отключить фильтрацию, то после её включения сайт начинает открываться штатно. 
<details><summary>Screenshot:</summary>

![-](https://user-images.githubusercontent.com/50718960/90341778-12a09f80-e00b-11ea-84ff-3572e6e8ceaf.png)
</details><br/>

**Comment by Alex-302** [comment]
Меня вообще никак не пускает. Гео-блокировка видимо.
