### ISSUE TITLE
Space Frontier app - missed app

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6167]
This ad appears when the game starts.

<details><summary>Screenshot:</summary>

<img width="386" alt="screen shot 2017-08-11 at 9 47 14 pm" src="https://user-images.githubusercontent.com/27292111/29227533-d7227716-7ede-11e7-93fd-165f17454ce4.png">
<img width="402" alt="screen shot 2017-08-11 at 9 49 30 pm" src="https://user-images.githubusercontent.com/27292111/29227570-010d61bc-7edf-11e7-8552-d66a886eab10.png">

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Adguard version: | 2.9.136
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Whitelist)
Adguard filters: | 2, 3, 4, 14, 1, 5, 11, 15, 211
Ticket ID: | 1029341

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
