### ISSUE TITLE
http://clashroyalearena.com/ - Ads - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6168]
***Description***:
* **Current behaviour**: 
There are ads on http://clashroyalearena.com/ 
Reproduced on our side Mac OS

<details><summary>Screenshot:</summary>

![screen shot 2017-08-12 at 12 48 18 am](https://user-images.githubusercontent.com/28784344/29233113-f69936f2-7ef7-11e7-8a49-65f4271ede34.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1.
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14,
Ticket ID (if exists): | 1604535

**Comment by Alex-302** [comment]
fixed
