### ISSUE TITLE
9anime.to - Redirections - Android 

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6169]
***Description***:
* **Current behaviour**: 
Redirections from 9anime.to on Android
Reproduced on our side.

<details><summary>Screenshot:</summary>

![screenshot_20170812-003849](https://user-images.githubusercontent.com/28784344/29233564-4fae1468-7efa-11e7-8eb6-dd0e29f19d96.png)

</details>

<details><summary>Screenshot:</summary>

![screenshot_20170812-003930](https://user-images.githubusercontent.com/28784344/29233570-5e700c04-7efa-11e7-9738-3acf76ad151c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Adguard version: | 2.9.136 - beta
Adguard mode (Android): | Proxy(manual)
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard filters: | 2, 3, 14, 11
Ticket ID (if exists): | 1604535

**Comment by Alex-302** [comment]
Fixed.
Please check after filters update.
