### ISSUE TITLE
OfferUp Android App

### ISSUE THREAD

**Issue by dmraymond** [AdguardTeam/AdguardFilters#61705]
AdGuard v3.5 beta 1 (48)
Android App: OfferUp version 3.81.0
Android: 10
Knox: 3.4.1
Model: Galaxy S10+

![Screenshot_20200817-080211_OfferUp](https://user-images.githubusercontent.com/12863807/90411099-1dd1ea80-e060-11ea-9417-847b8069b817.jpg)

**Comment by Alex-302** [comment]
Hi. Promoted items cannot be blocked in the app.

**Comment by OJ7** [comment]
You can block `||bing.com^` which will show blank images for ads in OfferUp, but it won't get rid of the item in the list.

**Comment by Alex-302** [comment]
@OJ7 Cannot check now - app does not load resources even with VPN and without AG.
Please test 
`||bing.com^$app=com.offerup`
and show screenshot, if ad images blocked.

**Comment by OJ7** [comment]
@Alex-302 I added that filter and it works fine.

![image](https://user-images.githubusercontent.com/5333243/126537842-4ce22106-a737-409a-a3cd-28964dea146f.png)

**Comment by Alex-302** [comment]
Ok, added. Thanks.
