### ISSUE TITLE
Tech News app - pop-up - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6170]
***Description***:
* **Current behavior**: 

 The black full-screen popup appears again in the Tech News app for Android
https://play.google.com/store/apps/details?id=it.pinenuts.technews

couldn't reproduce the problem

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | beta 2.9.136
Adguard mode (Android): | Proxy(manual)
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard filters: |  2, 3, 4, 14, 16, 15, 211 
Ticket ID (if exists): | 1063185

logs attached to the message for Thu, 10 Aug 2017 20:32:13 GMT

**Comment by whynotnow2** [comment]
if you want to reproduce the popup you need to choose within application parameter ads type = after reading

**Comment by Alex-302** [comment]
@whynotnow2 
> choose within application parameter ads type = after reading

where can I do it? Can't find.

**Comment by whynotnow2** [comment]
Here attached you have to select ads display = after reading
![screenshot_20170814-162807](https://user-images.githubusercontent.com/30954799/29276105-cead81e4-810d-11e7-93f0-817f8d7cd986.png)

**Comment by Alex-302** [comment]
Nothing.

**Comment by whynotnow2** [comment]
I use that application on both my s7 edge and galaxy tab s2 and ads are there on both of them.

**Comment by Alex-302** [comment]
Please record HAR file
https://kb.adguard.com/en/android/solving-problems/har

**Comment by whynotnow2** [comment]
Remove zip extansion 
[adguard.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1223209/adguard.har.zip)

**Comment by Alex-302** [comment]
Try VPN mode and clear app's cache.

**Comment by whynotnow2** [comment]
i ve disabled dns filtering and it seems that ads are gone.
