### ISSUE TITLE
yummyanime.com - Ad leftover - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6171]
***Description***:
* **Current behaviour**: 

Ad leftover (no actual image of an ad,but just "Осталось 15 сек" before the video on
http://yummyanime.com/catalog/item/boruto-novoe-pokolenie

Reproduced on our side (Mac OS)

<details><summary>Screenshot:</summary>

![screen shot 2017-08-12 at 3 43 59 am](https://user-images.githubusercontent.com/28784344/29236250-cedca342-7f10-11e7-9dd4-36402bee3970.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1.
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1611197

**Comment by Alex-302** [comment]
Fixed.
