### ISSUE TITLE
Typo issue

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardFilters#61726]
A comma is forgotten

https://github.com/AdguardTeam/AdguardFilters/blob/8af23009b03fc30b739e74b960dbe21a640cd42a/EnglishFilter/sections/general_extensions.txt#L185

<details><summary>Screenshot:</summary>

![github com (2)](https://user-images.githubusercontent.com/34379403/90431060-2282b700-e0d1-11ea-8bae-b8112848f130.png)

</details>

**Comment by BlazDT** [comment]
Thank you :)
