### ISSUE TITLE
ncaa.com - Ad leftover - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6174]
***Site***: http://www.ncaa.com/march-madness-live/watch
***Description***: Adblock detection (Just click on a video or stream). Ad banner at the top and bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29236428-aa7282b6-7f0a-11e7-848d-5ca17a38790c.png)

![image](https://user-images.githubusercontent.com/10995998/29236448-c6b7db42-7f0a-11e7-9084-ba76c9d4393f.png)

![image](https://user-images.githubusercontent.com/10995998/29236450-d0a9453c-7f0a-11e7-8f40-6e320c167fd6.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
