### ISSUE TITLE
http://old.fishki.net/ - Ads - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6176]
***Description***:
* **Current behaviour**: 

Ads as a part of articles on http://old.fishki.net/
Can it be blocked by Adguard, because when you press on it- it redirects you to another website

Reproduced on our side
<details><summary>Screenshot:</summary>

![screen shot 2017-08-12 at 6 24 18 am](https://user-images.githubusercontent.com/28784344/29237469-5b07c2dc-7f27-11e7-810e-a41f61d30ded.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | chrome
Adguard version: | 1.4.1.
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1038309

**Comment by Alex-302** [comment]
Fixed.
