### ISSUE TITLE
https://javfinder.to/ (NSFW)

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6184]
**_Site_**: https://javfinder.to/movie/watch/alicejapan-dvaj-246-mii-kurii-miyuki-cutie.html

***Description***: Remove **SKIP AD**

<details><summary>Screenshot:</summary>

![screenshot_135](https://user-images.githubusercontent.com/19608513/29238866-e635bcb6-7f4e-11e7-9d8c-a10ccdeecf3c.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
Fixed.
