### ISSUE TITLE
laptopmag.com

### ISSUE THREAD

**Issue by nu8** [AdguardTeam/AdguardFilters#61859]
> AD BLOCKER INTERFERENCE DETECTED

https://laptopmag.com

I tried this with no luck:

1. Dashboard
2. Filter lists
3. Annoyances
4. AdGuard Annoyances

**Comment by Alex-302** [comment]
Hi. Do you use another ad blockers?

**Comment by nu8** [comment]
I use uBlock Origin

**Comment by Alex-302** [comment]
I need more details. Which filters and own rules?

**Comment by nu8** [comment]
AdGuard Annoyances

**Comment by llacb47** [comment]
You were already given multiple fixes: https://github.com/uBlockOrigin/uAssets/issues/7794

You are responsible for fixing breakage and anti-adblock you cause with `* * 3p-script block`.
