### ISSUE TITLE
http://hpjav.com/ (NSFW)

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6185]
**_Site_**: http://hpjav.com/

***Description***: Click something, you will get a new **POPUP**

</details>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
I can't reproduce, but please check this rule:
`hpjav.com#%#Object.defineProperty(window, '_pop', { get: function() { return {}; } });`

**Comment by thislife81** [comment]
I also couldn't reproduce this popup now. Maybe they removed it. I closed this issue.

**Comment by Alex-302** [comment]
also not reproduced
