### ISSUE TITLE
billiger-telefonieren.de (breakage)

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#61874]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: unblocked background on `https://www.billiger-telefonieren.de/mobiles-internet-ausland/`
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="528" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/90691169-323a0100-e273-11ea-9aad-7894d5da9346.PNG">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox developer edition
AdGuard version:                       |  3.4.31
Filters enabled:                       | default + Adguard tracking protection + Adguard annoyances + Adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Morku** [comment]
@Alex-302 
The page still have a unusable grey overlay. Filterlists are current.
