### ISSUE TITLE
https://www.javdoe.com/ (NSFW)

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6187]
**_Site_**: https://www.javdoe.com/movie/fc2-ppv-525098-18-years-old-orthodox-black-hair-sexy-face-as-soon-as-i-immediately-faked-up-the-beautiful-woman.html

***Description***: Remove **SKIP AD**

<details><summary>Screenshot:</summary>

![screenshot_139](https://user-images.githubusercontent.com/19608513/29238904-0702eba2-7f50-11e7-8162-0c3caef29877.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
Fixed.
