### ISSUE TITLE
https://www.technopat.net/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6188]
**_Site_**: https://www.technopat.net/

***Description***: Turkish filter causes to change this site's background color from white to black. Without turkish filter background is white.

<details><summary>Screenshot:</summary>

![screenshot_141](https://user-images.githubusercontent.com/19608513/29238964-840da69e-7f52-11e7-98c7-a2a9c74beaba.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
Fixed.
