### ISSUE TITLE
http://diziay.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6189]
**_Site_**: http://diziay.com/izle/poldark-3-sezon-9-bolum/

***Description***: 1) Remove **AD** ; 2) Video plays late.

<details><summary>Screenshot:</summary>

![screenshot_143](https://user-images.githubusercontent.com/19608513/29239018-d4b5a9f6-7f53-11e7-825e-f1deb5355dc8.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
1# fixed
2# I can't reproduce, on my end video loads normally
