### ISSUE TITLE
http://www.filmionlineizle.net/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6190]
**_Site_**: http://www.filmionlineizle.net/sniper-duvar-izle.html

***Description***: Remove this **BANNER**

<details><summary>Screenshot:</summary>

![screenshot_145](https://user-images.githubusercontent.com/19608513/29239069-6af96384-7f55-11e7-8086-26c35fad723f.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
Fixed.
