### ISSUE TITLE
chip.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#61907]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
Example link: `https://www.chip.de/downloads/CCleaner_16317939.html`

***Description***: Chip.de use 2 buttons the blue one is the chip installer (with Adware) and the small black link is the original link with direct download. A script override the original link with adware so its possible to defuse the script (see uBlock Origin fix below)
Chip installer Virustotal scan: `https://www.virustotal.com/gui/file/d782f2a6aba6366200a3df63fe8a334809354ed715d87254d0204c1c9e33928c/detection`
I think the adware need to be blocked
<img width="445" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/90752256-73fc9300-e2d7-11ea-8d15-1a6ec05c62a7.PNG">

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer edition
AdGuard version:                       | 3.4.31
Filters enabled:                       | default + Adguard germany + Adguard tracking protection + Adguard annonyances
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

uBlock Origin fix: `https://github.com/uBlockOrigin/uAssets/commit/47c199df9cc9c2a87e0dbaee3bd2344f9f895b60`

**Comment by Morku** [comment]
Page also containes Commercial placeholder

<details><summary>Screenshot-1:</summary>

![chip](https://user-images.githubusercontent.com/6276915/90764879-5b957400-e2e9-11ea-850c-3b2d5c5d8c9c.png)


</details><br/>

**Comment by krystian3w** [comment]
> https://github.com/AdguardTeam/AdguardFilters/issues/61907#issue-682565448

AdGuard can use pur JS to change UA into GNU/Linux (IMO website no detect best software for used now OS).

These can fast down:

```
#?#.download_button:has(~ div:matches-css(display: block) span:contains(Manuelle Installation))
```

**Comment by JobcenterTycoon** [comment]
The filter doesn’t work anymore we need a new one

**Comment by Morku** [comment]
@JobcenterTycoon 
You'll probably need a new ticket. This is closed days ago...

**Comment by AdamWr** [comment]
Could you please check this rule:
`chip.de#%#//scriptlet("set-constant", "serveTheDownloader", "false")`

**Comment by JobcenterTycoon** [comment]
Good it works

**Comment by AdamWr** [comment]
Okay, thank you for checking it.
Added, update should be available in 1-2 hours.

**Comment by JobcenterTycoon** [comment]
The filter doesn’t work anymore

**Comment by AdamWr** [comment]
>The filter doesn’t work anymore

Could you please check this rule:
`chip.de#%#//scriptlet("set-constant", "DSpid", "")`

**Comment by JobcenterTycoon** [comment]
it works but i can’t exclude breakage because videos are broken again but not by this filter

see https://github.com/AdguardTeam/AdguardFilters/issues/61906

**Comment by JobcenterTycoon** [comment]
The chip installer is back

`||chip.de/installer/` will block this

**Comment by AdamWr** [comment]
Added, thank you.

**Comment by JobcenterTycoon** [comment]
The chip installer is back again now its coming from `chip.de/securedownload`

**Comment by JobcenterTycoon** [comment]
A possible filter (taken from uBlock Origin): `||chip.de/*&$script,1p`

**Comment by AdamWr** [comment]
Added a bit different rule, thank you.

**Comment by JobcenterTycoon** [comment]
@AdamWr the chip installer is back again

**Comment by AdamWr** [comment]
Okay, fixed.
