### ISSUE TITLE
chip.de breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#61906]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: I can’t play the video.

***Steps to reproduce the problem***: try to play the video
 `https://www.chip.de/news/Google-Maps-noch-besser-Kartendienst-bekommt-ein-tolles-Update_182924597.html` 

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | win 10
Browser:                               | Firefox developer edition
AdGuard version:                       |  3.4.31
Filters enabled:                       | default + Adguard germany + Adguard tracking protection + Adguard annoyances
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

I can’t play the Video without cookie accept so i need to whitelist the cookie banner with:

`@@/wrappermessagingwithoutdetection.js$script,domain=chip.de`
`@@||cdn.privacy-mgmt.com/consent^$domain=chip.de`

**Comment by JobcenterTycoon** [comment]
i still can’t play the video

**Comment by Alex-302** [comment]
@JobcenterTycoon it works on my end. Filters are updated?
@BlazDT please take a look.

**Comment by JobcenterTycoon** [comment]
Yes i updated. Cookie accept is needed to play the video on my end

**Comment by BlazDT** [comment]
Reproduced, had to add an additional rule and remove previous ones. Will add javascript rule later which adds required cookies.

**Comment by BlazDT** [comment]
Added JS rule.

**Comment by BlazDT** [comment]
Working for me. Please check @AdguardTeam/filters-maintainers

**Comment by AdamWr** [comment]
I can reproduce it with extension for Firefox and this rule fixes it:
`@@||cdn.privacy-mgmt.com/consent/$domain=chip.de`

It seems that this request happens when "accept" button is clicked, so I wonder if we should add this rule as a generic one (I mean without domain modifier).

**Comment by BlazDT** [comment]
I agree with generic as this request only happens when previous elements are unblocked.

**Comment by AdamWr** [comment]
Okay, added and also fixed this - https://github.com/AdguardTeam/AdguardFilters/issues/61907#issuecomment-693361135

**Comment by Morku** [comment]
@AdamWr @BlazDT 
https://www.golem.de/ Cookie bypass is broke now :'(

![2020-09-16 18-43-00](https://user-images.githubusercontent.com/6276915/93367816-50ccf100-f84d-11ea-8baa-b4471e199c25.gif)

**Comment by JobcenterTycoon** [comment]
`@@/setconsentcookie.$domain=golem.de` will fix that

**Comment by AdamWr** [comment]
>https://www.golem.de/ Cookie bypass is broke now :'(

Fixed, update should be available in 1-2 hours.

**Comment by krystian3w** [comment]
AdGuard click in blue button or bake needed cookies?

**Comment by BlazDT** [comment]
AdGuard clicks the required buttons.
