### ISSUE TITLE
http://www.hddizifullizle.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6191]
**_Site_**: http://www.hddizifullizle.com/

***Description***: Click something, you will get a new **POPUP**

</details>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
Fixed.
