### ISSUE TITLE
http://dizilab.net/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6193]
**_Site_**: http://dizilab.net/
***Description***: Click something, you will get a **POPUP**

**_Site_**: http://dizilab.net/atypical/sezon-1/bolum-8
***Description***: Remove **SKIP AD**

<details><summary>Screenshot:</summary>

![screenshot_149](https://user-images.githubusercontent.com/19608513/29239184-ff1b46b0-7f58-11e7-9851-077c8d1d8723.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
Fixed.
