### ISSUE TITLE
[nsfw] [popups] [redirect links adware] bravoerotica.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6194]
[NSFW] [ADULT CONTENTS] bravoerotica.com

Popups, click on some pics opening random sites with adware (blocked by adguard sometimes). 
![image-20170812-005](https://user-images.githubusercontent.com/9846948/29239995-18901c94-7f5c-11e7-8d8f-e758c6ab0587.png)

**Comment by Alex-302** [comment]
fixed
