### ISSUE TITLE
[nsfw] [popups] golderotica.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6195]
[NSFW] [ADULT CONTENTS] golderotica.com

Popups, click on some pics opening random sites with adware (blocked by adguard sometimes).

**Comment by Alex-302** [comment]
Not reproduced.
I need URL of the pics which causes popups.

**Comment by FadeMind** [comment]
empty box with X, now I cannot reproduce issue about adware. (some pics open new random nsfw sites)
![image-20170814-001](https://user-images.githubusercontent.com/9846948/29272473-83ba9fe4-8100-11e7-8cc4-846e4cce7a01.png)

**Comment by Alex-302** [comment]
Added
```
golderotica.com##body > div#topbar
```
