### ISSUE TITLE
[nsfw] [overlay adv on videos during pause] sex.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6196]
[NSFW] [ADULT CONTENTS] sex.com

ADV layer after pause videos. 
![image-20170812-006](https://user-images.githubusercontent.com/9846948/29240937-9c873dd0-7f6f-11e7-8d35-33f5e4208206.png)

Should be enough:
```
sex.com###ad-div
```

**Comment by Alex-302** [comment]
Added
