### ISSUE TITLE
dtf.ru - Incorrect blocking - iOS

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6197]
***Description***:
* **Current behaviour**: 

Incorrect blocking on https://dtf.ru/9145-na-ios-i-android-vyshla-strategiya-vo-vselennoy-titanfall
When Adguard is enabled, there is a delay before the content of the site appears.
Just compare the speed (not the page load, namely the display of content) with a blocker and without.
Disabling spyware filter- helps

***System configuration***
Application version: 1.3.0.81
Device: iPhone
Platform: iOS
OS: 10.3.3
Optimized enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.55 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.73 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.55.19 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.54 Enabled=YES
Ticket ID: 1066573

**Comment by Alex-302** [comment]
fixed
