### ISSUE TITLE
animeid.io

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6198]
![image-20170812-007](https://user-images.githubusercontent.com/9846948/29241558-6df67190-7f7c-11e7-9d50-bdf20f15224d.png)

- adblock detect
- adv space left

**Comment by Alex-302** [comment]
Please fill the template.

**Comment by BioBrayan** [comment]
Program name or blocker extension

**Comment by FadeMind** [comment]
`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.90`
`Windows 10`

Adguard filter lists:
![image-20170814-002](https://user-images.githubusercontent.com/9846948/29275076-365128fe-810a-11e7-90b1-f3c08e49f2aa.png)

**Comment by Alex-302** [comment]
It is a Spanish site.Turn on the appropriate filter.

**Comment by FadeMind** [comment]
After turn on spanish filter nothing was changed.

**Comment by Alex-302** [comment]
```
@@||player.animeid.io/static/ads.js
animeid.io##.banner_center
animeid.io###divFloatRight
```
