### ISSUE TITLE
Блокировка рекламы youtube

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#6199]
У меня adguard 2.9.136, фильтры по-умолчанию, HTTP, HTTPS, качественная Фильтрация. И так, я думаю, что всех мучает реклама в YouTube. Проблема найдена. Во время просмотра ролика, внизу появляется баннер. Вот способ как его убрать.

||googleadservices.com^$important
||www.youtube.com/ptracking^
||yt3.ggpht.com/proxy^

(первое отвечает за прероллы, причем это правило исключается Adguard; второе отвечает за банеры; третье (опционально, покрывается вторым) за картинки к этим банерам).
Можно добавить в конце каждого правила (чтобы блочились эти адреса только в ютубе):
|$app=com.google.android.youtube

![screenshot_2017-08-13-01-10-09](https://user-images.githubusercontent.com/22351242/29244586-45152436-7fc4-11e7-8b2f-41709e7d32be.png)

**Comment by ministr91** [comment]
@ameshkov, @Alex-302 гляньте

**Comment by Alex-302** [comment]
Не ловится.

**Comment by ministr91** [comment]
@Alex-302 и что ты предлагаешь? У меня ловится, скрин есть, показал что стоит, даже решение есть выше

**Comment by ministr91** [comment]
надо обязательно ограничение на "app" добавить, googleadservices для всех приложений нельзя -- частично поиск ломает гуглу.

**Comment by Alex-302** [comment]
```
||googleadservices.com^$important,app=com.google.android.youtube
||www.youtube.com/ptracking^$app=com.google.android.youtube
||yt3.ggpht.com/proxy^$app=com.google.android.youtube
```
Точно блокирует баннер?

**Comment by ministr91** [comment]
Я не пробовал, а только лишь подкинул идею. Надо протестировать, у меня то реклама есть, то ее нет. Я не могу сказать на 100%

**Comment by ministr91** [comment]
Но то, что реклама в этих баннерах есть, это 100%, скрин выше. Другое дело, что я не всегда ее ловлю. Она то появляется, то исчезает и сложно протестировать

**Comment by Alex-302** [comment]
У меня она после обновления Ютуба не появилась.

**Comment by ministr91** [comment]
Не веришь мне? Вот видос http://my-files.ru/uyz5xq
Версия ютуба последняя с маркета

**Comment by ministr91** [comment]
http://my-files.ru/87c7em
Логи 1:39 ночи август 22

**Comment by ministr91** [comment]
@Alex-302 и @ameshkov

**Comment by Alex-302** [comment]
HAR как всегда не открывается.
Из незаблокированного в логе вижу только `googleadservices.com`
Проверь такое:
```
||googleadservices.com^$important,app=com.google.android.youtube
```

**Comment by ministr91** [comment]
Что значит HAR не открывается? Почему как всегда? Я сделал все по инструкции, может стоит в новой версии изменить архитектуру har файла?
Правило попробую, о результатах напишу

**Comment by Alex-302** [comment]
Ну пишется он так. Не знаю почему. Вроде исправить должны были, но не знаю, есть ли исправление в текущей версии.

**Comment by Alex-302** [comment]
Будешь о результате отписываться - приложи лог запросов.

**Comment by ministr91** [comment]
@ameshkov, исправили в новой версии HAR лог?
@Alex-302, какой лог? Когда его приложить? Показать, что реклама исчезла? Я же выше кидал HAR и лог веб. запросов

**Comment by Alex-302** [comment]
ну погоняй день, а потом лог пришли.

**Comment by ministr91** [comment]
http://my-files.ru/0ec74s
Здесь видео, лог запросов, HAR лог. Правило новое ее работает. Решил потом еще остальные 2 включить, но уже не на видео - все равно баннер появляется. Что касается HAR файла, попробуй его сейчас отправить, я там исправил одну вещь, получится или нет у тебя

**Comment by ministr91** [comment]
Правило новое НЕ работает

**Comment by ministr91** [comment]
Время логов 2 часа ночи примерно август 23

**Comment by Alex-302** [comment]
Эти правила не помогут. Все незаблокированные запросы приложения Ютуба - нужные.

**Comment by ministr91** [comment]
@Alex-302, ты проблему с этим баннером как-то решить можешь? Если нет, то тогда закроем тему и забудем про это. 
Хотелось бы только, чтобы @ameshkov решил проблему в будущем с нечитаемым HAR логом

**Comment by Alex-302** [comment]
Я сейчас не могу, т.к. повторить не получается.
Попробуй через комп записать Фидлером по этой инструкции
https://forum.adguard.com/index.php?threads/missed-ads-submission-rules.1879/

**Comment by ministr91** [comment]
Не, это слишком долго. Скачивать программу, потом настраивать ее еще, это того не стоит .

**Comment by ministr91** [comment]
Частота YouTube сидишь? Она каждый вечер у меня, я в YouTube 30 минут видео смотрю и появляется, но появляется на каждое видео

**Comment by Alex-302** [comment]
Вообще никогда им не пользуюсь на телефоне, он у меня был отключен.
Попробуй данные очистить.

**Comment by ministr91** [comment]
Пробовал, кэш тоже чистил

**Comment by ministr91** [comment]
Я так понимаю проблема решить не удается? Закрывай тогда тему
@Alex-302, @ameshkov
