### ISSUE TITLE
pcgameshardware.de - Social share bar leftover at the bottom

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6200]
https://www.google.de/amp/www.pcgameshardware.de/CPU-Hardware-154106/News/Intel-Coffee-Lake-Details-Core-i3-8100-Core-i3-8350K-1235576/amp/

<details><summary>Screenshot:</summary>

<img width="405" alt="screen shot 2017-08-13 at 2 27 39 am" src="https://user-images.githubusercontent.com/27292111/29244908-866d694c-7fcf-11e7-90ff-6e9dc53a8e11.png">

</details>

***System configuration***

Application version: 1.3.0.100
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.78 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.78 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.8 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.81 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.8 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.26 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.54 Enabled=YES

Ticket ID: 1480792

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
I can't reproduce on my Android.
It should be hidden by this rule:
`www-pcgameshardware-de.cdn.ampproject.org##.socialbar`

**Comment by Alex-302** [comment]
Reproduced. Added.

**Comment by danidoedel** [comment]
@Alex-302 Still there for me: 

![1e110599-ed81-49c7-a5f1-10cff48c264c](https://user-images.githubusercontent.com/10995998/29508534-31b3653c-8655-11e7-9bc9-bd88818eefda.jpeg)

**Comment by Alex-302** [comment]
Maybe a bug
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/852
