### ISSUE TITLE
chip.de - Ad leftover and app banner at the bottom

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6201]
https://www.google.de/amp/www.chip.de/news/Intel-lueftet-das-Geheimnis-Coffee-Lake-CPU-bald-auf-Facebook_120460820.html%3flayout=amp

<details><summary>Screenshot:</summary>

<img width="405" alt="screen shot 2017-08-13 at 2 34 42 am" src="https://user-images.githubusercontent.com/27292111/29244925-0aac1a32-7fd0-11e7-8808-e685b843b04c.png">

</details>

***System configuration***

Application version: 1.3.0.100
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.78 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.78 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.8 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.81 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.8 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.26 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.54 Enabled=YES

Ticket ID: 1480792

**Comment by Alex-302** [comment]
We should not add the rules for third-party sites to Google domains.

**Comment by Alex-302** [comment]
Correct URL:
http://www.chip.de/news/Intel-lueftet-das-Geheimnis-Coffee-Lake-CPU-bald-auf-Facebook_120460820.html?layout=amp
Added
```
chip.de##amp-app-banner
chip.de##.amp-article-ad
chip.de##.amp-outbrain
```
