### ISSUE TITLE
trustedreviews.com -Ad leftover breaks top bar and several „Article continues below“ ad leftovers

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6202]
http://www.trustedreviews.com/news/intel-8th-gen-core-specs-technology-explained-2952599

<details><summary>Screenshot:</summary>

<img width="414" alt="screen shot 2017-08-13 at 2 37 56 am" src="https://user-images.githubusercontent.com/27292111/29244932-71607b2e-7fd0-11e7-9611-efd32d35fbd4.png">

</details>

***System configuration***

Application version: 1.3.0.100
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.78 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.78 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.8 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.81 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.8 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.26 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.54 Enabled=YES

Ticket ID: 1480792

**Comment by danidoedel** [comment]
@Alex-302 Top bar still broken
