### ISSUE TITLE
bigcinema.to - Missed ad in the video

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6208]
https://bigcinema.to/series/univer-sasha-i-tanya-serial.html

<details><summary>Screenshot:</summary>

<img width="1450" alt="screen shot 2017-08-13 at 6 12 20 am" src="https://user-images.githubusercontent.com/27292111/29245818-6d00d646-7fee-11e7-81b0-804875f1182a.png">

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.2 / 1.4.1
Adguard driver (Windows): | WFP 
Adguard filters: | 1 2 3 4 14
Ticket ID : | 1449704

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
I can't reproduce.
@Alex-302 could you please check it?

**Comment by Alex-302** [comment]
Oh, it is Russian site)
Added:
```
||n1219adserv.xyz^
```
