### ISSUE TITLE
videoframe.space

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#62090]
https://videoframe.space/serial/169f040papu/iframe
С включенным AdGuard не работает выбор качества.. также надпись на красном фоне отключить блокировщик для возможности выбора качества..

![image](https://user-images.githubusercontent.com/19754243/90953201-b0f88f00-e469-11ea-9d77-23d39ffdc745.png)

**Comment by Alex-302** [comment]
Не повторяется. Нужен отчёт из Адгарда.
