### ISSUE TITLE
advinci not blocked

### ISSUE THREAD

**Issue by mi8u** [AdguardTeam/AdguardFilters#62106]
Information                            | Value
---                                    | ---
Operating system:                      | Windows
Browser:                               | Chrome
AdGuard version:                       | 3.5.12
Filters enabled:                       | Base/Spyware
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | None

https://www.advinci.net/how-it-works.php

Necessary rule: **||advinci.life^$third-party**

**Comment by Alex-302** [comment]
Where is it used?

**Comment by Sergey-Lyapin** [comment]
@mi8u
