### ISSUE TITLE
http://economictimes.indiatimes.com/ - Incorrect Blocking - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6210]
***Description***:
* **Current behaviour**: 

www.economictimes.com is not displayed correctly when using Adguard. Disabling the software enables the browser to render the site correctly.
 Reproduced on our side (Mac OS)
<details><summary>Screenshot with Adguard:</summary>

![with adblocker](https://user-images.githubusercontent.com/28784344/29251402-b49a2458-805c-11e7-9037-4e84bb115b8d.png)

</details>

<details><summary>Screenshot without Adguard:</summary>
 
![without adblocker](https://user-images.githubusercontent.com/28784344/29251408-c49dc9a4-805c-11e7-94b7-dd760dbaee1a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1.
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1607702

**Comment by Alex-302** [comment]
Fixed.
