### ISSUE TITLE
http://www.aftonbladet.se - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6211]
> On the Swedish newspaper site www.aftonbladet.se there is an annoyance on top of the page. When you scroll down it is always on top asking you to login etc. I'm talking about the top bar that says "Aftonbladet" and "Logga in". When you scroll down it's always on top taking up screen space. 

Example
http://www.aftonbladet.se/nyheter/a/GVdzl/tagkrasch-i-egypten--minst-20-doda

<details><summary> the screenshot </summary>

![image](https://user-images.githubusercontent.com/15856304/29251496-5725ff48-805e-11e7-98b9-b86d5f07c649.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 7
Browser: | Firefox
Adguard version: | 2.9.136
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On Default
Adguard DNS: | true
Adguard filters: | 2, 4, 14, 11, 15, 211, 223
Ticket ID (if exists): | 1456058

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
It's rather a question, I think. @Alex-302 do we consider such elements like floating bars asking to log in as annoyances?

**Comment by Alex-302** [comment]
Yes, but it is not possible always.
