### ISSUE TITLE
tamiltunes.live - asks to disable Adguard

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6212]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: asks to disable Adguard

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29251979-1c12f838-802d-11e7-98e6-8ecd4ba8c316.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10
Browser: | Chrome 60
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | WFP
Adguard filters: | 2, 3, 4, 10, 112
Ticket ID (if exists): | 1553535

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BioBrayan** [comment]
Settings /Ad Blocker / User Filter / Edit / Add a new rule / 

##body > cf-div

**Comment by Alex-302** [comment]
Fixed.
