### ISSUE TITLE
https://forums.overclockers.co.uk

### ISSUE THREAD

**Issue by GigabitEthernet** [AdguardTeam/AdguardFilters#6214]
This ad isn't blocked. It is on the top right of the [page](https://forums.overclockers.co.uk).

<img width="550" alt="screen shot 2017-08-13 at 22 03 47" src="https://user-images.githubusercontent.com/4457688/29253389-5e07ffa4-8073-11e7-8522-0a397a34c303.png">

Safari 10.1.2, Adguard extension 2.6.5.

**Comment by Alex-302** [comment]
Please fill the template.

**Comment by GigabitEthernet** [comment]
As requested.

[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: ad not blocked. Ad is on top right of the page, when logged into the forums.
* **Current behaviour**:  ad shows on the top right of the page
<details><summary>Screenshot:</summary>
<img width="550" alt="screen shot 2017-08-13 at 22 03 47" src="https://user-images.githubusercontent.com/4457688/29253389-5e07ffa4-8073-11e7-8522-0a397a34c303.png">
</details>

* **Expected behaviour**:  ad should be blocked and so should not show up.

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Load forums.overclockers.co.uk, login, ad is displayed on the top right when the window is large enough. Full screen window always shows the ad.

***System configuration***

Information | value
--- | ---
Operating system: | macOS 10.12.6
Browser: | Safari 10.1.2
Adguard version: | 2.6.5
Adguard driver (Windows): | N/A
Adguard mode (Android): | N/A
Filtering quality (Android): | N/A
HTTPS filtering (Android): |  N/A
Simplified filters(iOS) | N/A
Adguard DNS: | None
Stealth mode options(Windows) | N/A
Adguard filters: | English filter, Safari filter
Ticket ID (if exists): | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)



[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't reproduce

<details>

![image](http://imagizer.imageshack.com/img924/7518/3E1pUW.png)
</details>

**Comment by GigabitEthernet** [comment]
As I said, you need to be logged into the forums for the ad to show.

**Comment by Alex-302** [comment]
It is clean
http://imagizer.imageshack.com/img922/7308/Tj8S2X.png

**Comment by GigabitEthernet** [comment]
Try making the window full screen and the ad might show up. It seems to depend on the size of the window as to whether it shows up.

**Comment by GigabitEthernet** [comment]
@Alex-302 just wondering if you've missed this as it is still marked as closed.

**Comment by Alex-302** [comment]
Please, wait your turn.

**Comment by Alex-302** [comment]
I need saved HTML+resources.

**Comment by GigabitEthernet** [comment]
@Alex-302 On Safari I don't know how to save a page like that as I explained before.

This correctly blocks the ad on Safari:

`forums.overclockers.co.uk###Offer`

Also, I posted the issue here for the EasyList devs and they made this filter for uBlock Origin:

```
##.samBannerUnit > .SamLink
##.samBannerUnit .SamLink
/data/Siropu/images/*
/xenforo/banner/*
```

This blocks the ad on all xenforo CMS forums. I hope this is useful.

**Comment by Alex-302** [comment]
> forums.overclockers.co.uk###Offer

added


> Also, I posted the issue here for the EasyList devs and they made this filter for uBlock Origin:

I need more examples of these ads.
