### ISSUE TITLE
i.ifeng.com - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6215]
http://i.ifeng.com/

<details><summary>Screenshot:</summary>

<img width="428" alt="screen shot 2017-08-14 at 5 57 01 am" src="https://user-images.githubusercontent.com/27292111/29256757-6fbb900c-80b5-11e7-8f68-ef0344648d16.png">

</details>

***System configuration***

Application version: 1.3.0.81
Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.79 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.78 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.8 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.83 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.26 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.54 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.85.68 Enabled=YES

Ticket ID: 1611827

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
The bottom element is not an ad. Oк ad?

Added:
```
||ifeng.com^*/wapifeng
```

**Comment by Alex-302** [comment]
@veronikasav
