### ISSUE TITLE
Miss Blocked www.blogger.com as adult site in Parental Control

### ISSUE THREAD

**Issue by DavidTai780** [AdguardTeam/AdguardFilters#62156]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 
The www.blogger.com webpage has been marked as adult site and blocked by AdGuardHome's AdGuard parental control web service 

[//]: # (Substitute this line with a description of the problem) 

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![Screenshot (114)](https://user-images.githubusercontent.com/26398101/90970680-99d5a200-e53a-11ea-992f-3fae6553fc30.png)

</details><br/>

* **Expected behaviour**: 
Should able to visit www.blogger.com as normal and not blocked by AdGuard Parental Control Web Service

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![Screenshot (115)](https://user-images.githubusercontent.com/26398101/90970692-af4acc00-e53a-11ea-825b-32c7367d6c40.png)

</details><br/>

***Steps to reproduce the problem***:
Use the AdGuardHome with AdGuard Parental Control Web Service

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows
Operating system version (Android/iOS) | Windows 10 v1909 x64
Browser:                               |  Google Chrome 84.0.4147.135
AdGuardHome version:                       |  v0.103.3
AdGuard DNS:                           | Un-Filtered
Stealth mode options (Windows only)    |  No
Helpdesk ID (if exists):               | No

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by lolka4toli** [comment]
Removed from adult.
