### ISSUE TITLE
hsbc.com.au - The website is blocked 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6216]
https://www.hsbc.com.au/

<details><summary>Screenshot:</summary>

<img width="427" alt="screen shot 2017-08-14 at 6 32 54 am" src="https://user-images.githubusercontent.com/27292111/29257409-706e8b26-80ba-11e7-9f2f-d98c2387508b.png">

</details>

***System configuration***

Application version: 1.3.0.81
Device: iPad
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.6 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.67 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.89 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.56 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.21 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID: 1611909

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
