### ISSUE TITLE
http://shink.in anti adblock

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#6217]
Hey
have anti anti adblcok site: http://shink.in
link exmple: http://shink.in/4rajN
Operating system: Windows 10 x64
Screenshot:  http://prntscr.com/g18fwy
Browser: Chrome
Adguard version: 6.1.331.1732

filter:
English filter
Annoyances filter
EasyLIstHebrew
Social media filter
fanboys social blocking list
adblock warning removal list

**Comment by BioBrayan** [comment]
Extension Installation / Install

https://xuhaiyang1234.gitlab.io/AAK-Cont/dist/aak-cont-script-ubo.user.js

**Comment by Alex-302** [comment]
Fixed
