### ISSUE TITLE
animevost.org - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6218]
http://animevost.org/

<details><summary>Screenshot:</summary>

<img width="1368" alt="screen shot 2017-08-14 at 6 55 23 am" src="https://user-images.githubusercontent.com/27292111/29257823-aa6712f0-80bd-11e7-9294-0bddda9763aa.png">

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS 
Browser: | Chrome
Adguard version: | 6.2 / 1.4.1
Adguard driver (Windows): | WFP 
Adguard filters: | 1 2 3 4 14
Ticket ID: | 1335772

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
