### ISSUE TITLE
aptekamos.ru - missed ads

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6219]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: ads on the right site of the page: 
[https://aptekamos.ru/apteka/price.html?id=4007&r=1](https://aptekamos.ru/apteka/price.html?id=4007&r=1)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screen shot 2017-08-14 at 10 17 33 am](https://user-images.githubusercontent.com/30041399/29261741-d03de4c4-80d9-11e7-917e-c371c756ece0.png)
</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | TDI
Ticket ID (if exists): | 1523504

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
