### ISSUE TITLE
http://www.vizyonfilmizle.com.tr/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6221]
**_Site_**: http://www.vizyonfilmizle.com.tr/43739-angels-of-revolution-angely-revolyutsii-rus-filmi-izle.html

***Description***: Remove this **BANNER**.

<details><summary>Screenshot:</summary>

![screenshot_163](https://user-images.githubusercontent.com/19608513/29266818-29c1beae-80f7-11e7-824c-868fa608520d.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
I can't reproduce.

**Comment by thislife81** [comment]
Interesting. Now also not reproduced on my end. I close this issue. Thanks)
