### ISSUE TITLE
Adguard not working

### ISSUE THREAD

**Issue by adguard1122** [AdguardTeam/AdguardFilters#62218]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***adguard is not working even when enabled and also not showing legacy browser assistant
i have the latest version of adguard version 7.5 please refer the screenshot attached***:
* **Current behavior**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://i.ibb.co/vd5f2fw/adguard.png)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (adguard base filter, easylist, adguard tracking protection filter, easy privacy, fanboys enhanced tracking list, fanboy anti-facebook list, adguard social media filter, fanboy's social blocking list, adguard annoyances filter)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:    | windows 10 home version 2004 os build 19041.450
Operating system version (Android/iOS) | ?
Browser:            | edge , chrome
AdGuard version:         | 7.5
Filters enabled:              | adguard base filter, easylist, adguard tracking protection filter, easy privacy, fanboys enhanced tracking list, fanboy anti-facebook list, adguard social media filter, fanboy's social blocking list, adguard annoyances filter
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | hide your search queries, send do-not-track header, strip URLs of tracking parameters, self-destruction of third-party cookies, Remoce X-Client-Data header from HTTP requests
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Please ensure HTTPS filtering is active.
