### ISSUE TITLE
http://www.tekparthdkeyfi.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6224]
**_Site_**: http://www.tekparthdkeyfi.com/kafesteki-kadin-full-izle.html

***Description***: Remove these sections for  **SOCIAL SHARING**.

<details><summary>Screenshot:</summary>

![screenshot_165](https://user-images.githubusercontent.com/19608513/29267187-a7848654-80f8-11e7-8bb3-202546ff0ef0.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by Alex-302** [comment]
fixed
