### ISSUE TITLE
http://www.sinemaizlefullhd.org/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6225]
**_Site_**: http://www.sinemaizlefullhd.org/recep-ivedik-5-izle-2017-full-hd-tek-parca/

***Description***: Click **PLAY** button, you will get a new POPUP.

<details><summary>Screenshot:</summary>

![screenshot_167](https://user-images.githubusercontent.com/19608513/29267377-7b5abd18-80f9-11e7-80b1-742fe98f75be.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
I can't reproduce.
