### ISSUE TITLE
otvet.mail.ru some avatats blocked

### ISSUE THREAD

**Issue by vitalkanev** [AdguardTeam/AdguardFilters#6226]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Some avatars are blocked on otvet.mail.ru service. See example in the screenshot. I guess the root of cause is English Filter ([Source](https://otvet.mail.ru/question/202540113/cid-263347453/))
* **Current behaviour**: No avatars

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можно вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot Captured yesterday:</summary>

![2017-08-13 18_04_44- mail ru](https://user-images.githubusercontent.com/18398761/29269978-18a44c62-80fd-11e7-9078-98f3010f1452.jpg)

</details>

* **Expected behaviour**: Avatars _will be proably_ shown

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

***Steps to reproduce the problem***: Simple. Just open otvet.mail.ru and/or any question

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows XP, also was reporduced on Windows 10 Enterprise 2015 LTSB
Browser: | Yandex 17.4.1 on Windows XP and 17.7.1(?) on Windows 10
Adguard version: | 2.6.7 Browser Extension
Adguard filters: | [Gist from Windows XP](https://gist.github.com/vitalkanev/32e7704db2a81ed2e96b25b464bbd8ab)
Ticket ID (if exists): | `undefined`

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Попробуйте обновить фильтры. В английский фильтр пару дней закралось корявое правило.

**Comment by vitalkanev** [comment]
Помогло @Alex-302
