### ISSUE TITLE
Inswall wallpaper app - Ads - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6232]
***Description***:
* **Current behaviour**: 

There are ads on inswall wallpaper app on Android:
https://play.google.com/store/apps/details?id=com.inswall.wallpaper
Reproduced from our side

<details><summary>Screenshot:</summary>

![screenshot_20170815-002040](https://user-images.githubusercontent.com/28784344/29292826-5663592c-8151-11e7-9976-3e73d8529fe9.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Adguard version: | 2.9.136
Adguard mode (Android): | Proxy(manual)
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default)
Adguard filters: |  2, 3, 4, 1, 11 
Ticket ID (if exists): | 801865

**Comment by Alex-302** [comment]
Maybe FB ads.

**Comment by AdamWr** [comment]
I see these ads when I disable Adguard, but with Adguard enabled I can't reproduce.
On my end these ads are blocked by this rule:
`||graph.facebook.com/network_ads`

**Comment by Alex-302** [comment]
If this app does not use FB, add 
```
||graph.facebook.com^$app=
```

**Comment by AdamWr** [comment]
I should add this rule even if ads are blocked by current rule (`||graph.facebook.com/network_ads`) from mobile filter?

**Comment by Alex-302** [comment]
If it does not break auth or something else.

**Comment by AdamWr** [comment]
Ok, added.
