### ISSUE TITLE
hessenschau.de - incorrect blocking 

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6233]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: pictures are missing

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29304091-e73250f0-8199-11e7-87dd-44053eda6c7d.png)
</details>

***Steps to reproduce the problem***:
[http://hessenschau.de/index.html](http://hessenschau.de/index.html)

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Adguard version: | 1.3.0.81
Adguard filters: | 2, 3, 4, 6, 12, 229
Ticket ID (if exists): | 1612403

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by wolfissimo** [comment]
Same issue on http://www.tagesschau.de.

**Comment by vitbortnik** [comment]
@wolfissimo 
there is a separate ticket https://github.com/AdguardTeam/AdguardFilters/issues/6234

**Comment by danidoedel** [comment]
@wolfissimo Can't reproduce it. Meanwhile you could try to enable annoyance filter and mobile ads filter and disable "I don't care about cookies".

**Comment by Alex-302** [comment]
Please check for filters update.

**Comment by wolfissimo** [comment]
Thank you. Now it works for me like expected. Both hessenschau.de and tagesschau.de.
