### ISSUE TITLE
Удаление лишних элементов

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#62342]
Здравствуйте,
Какое пользовательское правило я должен добавить, чтобы избавиться от этой раздражающей плашки (скрин ниже)?
![IMG_20200825_223650_400](https://user-images.githubusercontent.com/70233974/91219670-acf79600-e723-11ea-8d6e-8159371a64a0.jpg)

**Comment by Alex-302** [comment]
Надёжнее всего почитать про простейшие селекторы
https://code.tutsplus.com/ru/tutorials/the-30-css-selectors-you-must-memorize--net-16048
и с помощью инструментов разработчика попробовать составить правила
https://kb.adguard.com/ru/general/how-to-create-your-own-ad-filters
