### ISSUE TITLE
The Ultimate Adblock Detector for Bootstrap - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6236]
***Site***: https://codecanyon.net/item/the-ultimate-adblock-detector-for-bootstrap/20284439
***Description***: Anti adblock script. Testpage detects Adguard.

Testpage: http://preview.codecanyon.net/item/the-ultimate-adblock-detector-for-bootstrap/full_screen_preview/20284439

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29309129-b7a9861e-81a8-11e7-9b4b-d9ad937165f8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
