### ISSUE TITLE
avtoto.ru - incorrect blocking

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6237]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Расширение блокирует поиск на сайте [avtoto.ru](avtoto.ru)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29312187-ede59d4e-81bc-11e7-8172-c6c02e2b2746.png)
</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29312436-fa02ecac-81bd-11e7-81b6-c2ae2ef836fe.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29312452-0af4654a-81be-11e7-8f5f-17a5c023af74.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29312463-17d51cd2-81be-11e7-9af1-597c947924a1.png)

</details>

***Steps to reproduce the problem***:
Повторить ошибку можно: зайти на сайт avtoto.ru, консоли написать
AjaxGo('page=index&par=/par1~par2')

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Яндекс.Браузер
AdBlocker version: | 2.6.7
Adguard filters: | 1, 2, 13
Ticket ID (if exists): | 1612333

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It was fixed few days ago.
