### ISSUE TITLE
Quora [Android App] [Ads]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#62373]
**App Name**: Quora — Ask Questions, Get Answers
**PlayStore Link**: https://play.google.com/store/apps/details?id=com.quora.android
**Issue**: Seeing ad & sponsor posts occasionally while browsing various random questions
**Screenshots**:
**Sponsored**: https://i.ibb.co/t4wLD5R/Screenshot-20200826100154.jpg
**Ad**: https://i.ibb.co/DzC8cPd/Screenshot-20200826100115.jpg

**Settings & Filters:**
**AdGuard Version**: 3.4 (120)

**Filters**:
Adblocking: AdGuard Base filter
AdGuard Mobile Ads filter
Peter Lowe's Blocklist
AdGuard Tracking Protection
AdGuard Social Media filter
Online Malicious URL Blocklist
Spam404
NoCoin Filter List
AdGuard Annoyances filter
Adblock Warning Removal List

**User Filters**: Yes

**Settings**:
High quality filtering method: Enabled
Block ads in all apps: Enabled

**Stealth Mode**: Enabled (Custom)
**DNS Filtering**: Enabled
**DNS Server**: AdGuard DNS
**DNS Requests Blocking**: Enabled (2 Filters: DNS User Filter & AdGuard Simplified domain names filter)

**Extensions**: Enabled (AdGuard Extra)
**HTTPS Filtering**: Enabled
**Filtering Method**: Local VPN

**Comment by Alex-302** [comment]
Cannot be blocked in app.

**Comment by Nzzyme** [comment]
> Cannot be blocked in app.

And why is that? Is this one of those apps where AdGuard fails to block ads? I checked the list of apps where AG can't filter and don't see this one there.

**Comment by Alex-302** [comment]
Without root access this is impossible.
