### ISSUE TITLE
gallup.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#62374]
[https://www.gallup.com/home.aspx](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.gallup.com/home.aspx)

![cookie](https://user-images.githubusercontent.com/35470489/91264040-e392d800-e746-11ea-83ab-7d816f082921.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by AdamWr** [comment]
Hmm, it has been fixed yesterday - https://github.com/AdguardTeam/AdguardFilters/commit/0957b0f123bd190fe3a35e1284ff85044567d61c and I can't reproduce it.

Please update filters and then check again.
