### ISSUE TITLE
[NFSW] xhamster.com - missed ads

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6238]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
[https://de.m.xhamster.com/videos/teens-like-it-big-the-best-distraction-scene-starring-ale-7964224](https://de.m.xhamster.com/videos/teens-like-it-big-the-best-distraction-scene-starring-ale-7964224)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29313228-8f359e16-81c1-11e7-8710-b6f1c2867b37.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Adguard version: | 1.3.0.100
Adguard filters: | 2, 3, 4, 14, 6, 11, 12, 
Ticket ID (if exists): | 1480792

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce.
