### ISSUE TITLE
baike.com - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6239]
http://www.baike.com/wiki/%E8%BF%9E%E6%9E%B7%E8%83%B8

<details><summary>Screenshot:</summary>

<img width="963" alt="screen shot 2017-08-15 at 4 56 52 pm" src="https://user-images.githubusercontent.com/27292111/29318988-f58bb4c0-81da-11e7-8c93-af6c310382f7.png">

</details>

***System configuration***

Application version: 1.3.0.81
Device: iPad
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.93 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.80 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.9 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.85 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.66 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.28 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.55 Enabled=YES
ID=101 Name="EasyList" Version=1.0.74.77 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.85.47 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.85.78 Enabled=YES

Ticket ID: 1612521

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
