### ISSUE TITLE
mintmanga.com - Doesn't block the opening of another website.

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6240]
http://mintmanga.com/gunsmith_cats_burst/vol1/2?mtr=1#page=2

Clicking any button on this website leads to the opening of another website.

<details><summary>Screenshot:</summary>

<img width="545" alt="screen shot 2017-08-15 at 5 35 14 pm" src="https://user-images.githubusercontent.com/27292111/29320550-38223fd4-81e0-11e7-9bcd-b974993181f6.png">
<img width="547" alt="screen shot 2017-08-15 at 5 35 27 pm" src="https://user-images.githubusercontent.com/27292111/29320553-3c7d614e-81e0-11e7-81a8-7c46b7398e6f.png">
<img width="541" alt="screen shot 2017-08-15 at 5 35 37 pm" src="https://user-images.githubusercontent.com/27292111/29320557-3feb9df0-81e0-11e7-8c97-e7f59649e20a.png">

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS / iPad
Browser: | Safari
Adguard version: | 1.4.1 / 1.3.0.81
Adguard driver (Windows): | WFP / TDI
Simplified filters(iOS) | Offn
Adguard filters: | 1 2 3 4 14 12 11
Ticket ID: | 1612636

**Comment by Alex-302** [comment]
fixed
