### ISSUE TITLE
AdGuard Annoyances blocks chat in dash.cloudflare.com

### ISSUE THREAD

**Issue by alex-mayorga** [AdguardTeam/AdguardFilters#62412]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

AdGuard Annoyances blocks chat on dash.cloudflare.com

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

Filter||zopim.com^$3p,domain=~help.ubnt.com|~nordvpn.com|~egb.com|~amaysim.com.au|~endclothing.com
Filter listAdGuard Annoyances 
Contextdash.cloudflare.com
Partyness(3) cloudflare.com ⇒ zopim.com
Typexhr
URLhttps://id.zopim.com/authenticated/web/jwt

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

It is possible to chat with Cloudflare.

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  Windows 10
Operating system version (Android/iOS) | ?
Browser:                               | Firefox Nightly
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I don't see this request on my end
![image](https://user-images.githubusercontent.com/8361299/91555449-b78b7880-e939-11ea-8b50-740b105f7bf6.png)

An any case this is expected behavior.
