### ISSUE TITLE
Aztec Pyramid - Ad banner

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6243]
https://play.google.com/store/apps/details?id=com.noobmakers.aztecpyramid_free

This banner appears when you hit "Play" button.

<details><summary>Screenshot:</summary>

<img width="640" alt="screen shot 2017-08-15 at 9 25 07 pm" src="https://user-images.githubusercontent.com/27292111/29329965-45f07bf6-8200-11e7-9363-41c73779838e.png">

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.136
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (whitelist)
Adguard filters: | 2 3 4 14 11
Ticket ID: | 1604717

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Ad is builtin.
I see it when launch the app the first time without Internet.
