### ISSUE TITLE
acquavivalive.it - Annoyance - Ad leftover - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6244]
***Site***: http://www.acquavivalive.it/news/attualita/515428/marco-piconio-trasferito-presso-lufficio-tecnico
***Description***: Adblock detection. Cookie message at the top. Ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29330372-40e1220c-81f9-11e7-8f8a-0ea2292ec782.png)

![image](https://user-images.githubusercontent.com/10995998/29330359-37c9fbe4-81f9-11e7-9813-76de79b8d7dd.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
