### ISSUE TITLE
http://www.hepmacizle.net/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6245]
**_Site_1_**: http://www.hepmacizle.net/
***Description_1***: 1) Remove these  **ADS**. ; 2) Click background, you will get a new **POPUP**.

<details><summary>Screenshot_1:</summary>

![screenshot_187](https://user-images.githubusercontent.com/19608513/29330924-d6856cb6-820b-11e7-9954-be894e63cadc.png)

</details>

</br>

**_Site_2_**: http://www.hepmacizle.net/2017/08/beltinci-aluminij-macini-canli-izle-2/
***Description_2***: Remove **SKIP AD**. 

<details><summary>Screenshot_2:</summary>

![screenshot_189](https://user-images.githubusercontent.com/19608513/29331123-78d1e71a-820c-11e7-99dc-788ef8c346f9.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
Ads removed, but I can't reproduce popup.
