### ISSUE TITLE
http://metbuat.az/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6246]
**_Site_**: http://metbuat.az/news/777877/hindistanda-olenlerin-sayi-110-neferi-otdu.html

***Description***: Remove this **3rd party site**

<details><summary>Screenshot:</summary>

![screenshot_191](https://user-images.githubusercontent.com/19608513/29332177-2f6323d8-8210-11e7-932a-d2af2b784667.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
Fixed.
