### ISSUE TITLE
https://news.milli.az/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6247]
**_Site_**: https://news.milli.az/society/572890.html

***Description***: Remove this **3rd party site**; and 2) Remove **empty space**

<details><summary>Screenshot:</summary>

![screenshot_193](https://user-images.githubusercontent.com/19608513/29332411-ffa23570-8210-11e7-96f8-a8ffb1226b89.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by Alex-302** [comment]
Fixed

**Comment by thislife81** [comment]
Please Remove empty space
