### ISSUE TITLE
http://qan.az/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6249]
**_Site_**: http://qan.az/

***Description***: Remove this **AD**

<details><summary>Screenshot:</summary>

![screenshot_197](https://user-images.githubusercontent.com/19608513/29333328-6d7838c6-8214-11e7-9597-099157f6c113.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by Alex-302** [comment]
Fixed.
