### ISSUE TITLE
https://www.hizlihdfullfilmizle.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6250]
**_Site_**: https://www.hizlihdfullfilmizle.com/baahubali-2-izle-the-conclusion-full-turkce-dublaj/

***Description***: Remove this **SKIP AD**

<details><summary>Screenshot:</summary>

![screenshot_199](https://user-images.githubusercontent.com/19608513/29333602-6b14faa0-8215-11e7-9fad-14e055004fcf.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
Fixed.
