### ISSUE TITLE
tv.yandex.ru - Ads- iOS

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6251]
***Description***:
* **Current behaviour**: 

Ads on https://tv.yandex.ru/2?grid=all&period=now

<details><summary>Screenshot:</summary>

![image1](https://user-images.githubusercontent.com/28784344/29336068-5b3c815c-8215-11e7-9bd9-cab08ab34163.png)

</details>

***System configuration***

Application version: 1.3.0.81
Device: iPhone
Platform: iOS
OS: 10.3.3
Optimized enabled: NO
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.97 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.83 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.12 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.90 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.55.35 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.28 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.55 Enabled=YES

Ticket ID:1612741

**Comment by Alex-302** [comment]
Fixed
