### ISSUE TITLE
ssl.bblck.me

### ISSUE THREAD

**Issue by BullShark** [AdguardTeam/AdguardFilters#62515]
# whois ssl.bblck.me     
NOT FOUND

This domain is used by generate-domains-blacklist from dnscrypt-proxy to get a list of domains to be blocked.

Loading data from [https://ssl.bblck.me/blacklists/domain-list.txt]
[https://ssl.bblck.me/blacklists/domain-list.txt] could not be loaded: <urlopen error [Errno 111] Connection refused>

Why is it being blocked by Adguard?

**Comment by Alex-302** [comment]
We do not block it
![image](https://user-images.githubusercontent.com/8361299/91603322-7618be80-e975-11ea-91c9-61bbf28ae8c1.png)
Which AdGuard do you use?
