### ISSUE TITLE
www.filmeonline2013.biz - Ads - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6252]
***Description***:
* **Current behaviour**: 

Redirections from www.filmeonline2013.biz
Reproduced on our side (Mac OS)
<details><summary>Screenshot:</summary>

![screen shot 2017-08-15 at 11 59 37 pm](https://user-images.githubusercontent.com/28784344/29336407-52eb31be-8216-11e7-8d9e-a3feef03fe88.png)

</details>

<details><summary>Screenshot:</summary>

![screen shot 2017-08-15 at 11 59 50 pm](https://user-images.githubusercontent.com/28784344/29336420-5b34cdbc-8216-11e7-8fe4-cdbbe74c37ed.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1612418

**Comment by Alex-302** [comment]
I see only fake player.
Added
```
filmeonline2013.biz##center > a[rel="nofollow"] > img
```

**Comment by Alex-302** [comment]
@ypetruk what about redirect?
