### ISSUE TITLE
Google.com (Chrome promotion Ad in Maps)

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdguardFilters#62534]
Since idiots always spam in google.com and my report not getting respected at all and ticket gets closed unfixed, I will report this way for my own ticket (probably the best for common pages).

**Issue URL (Ads)**

https://www.google.de/maps/@58.0772605,-30.35722,3z

**Comment**

Username: **@Morku**

**The Chrome Ad is back in Edge Chromium and Edge Legacy.
Same goes for google.com and probably all others Google domains.
Changes of https://github.com/AdguardTeam/AdguardFilters/commit/6999963e0c6adfd56ccc5611ed807422b88e0504 not work anymore.
Same goes for Satelite view beside map view.**

Die folgenden Informationen werden automatisch generiert. Bitte löschen Sie sie nicht.

Custom userscripts:
https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js

<details><summary>Screenshot-1:</summary>

![68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f4e5a643774394b2e706e67](https://user-images.githubusercontent.com/6276915/91497620-946fb300-e8be-11ea-96fb-ed1f41e5589d.png)

</details><br/>

System configuration

Information | value
-- | --
AdGuard product: | AdGuard for Windows v7.5.1
Browser: | Edge
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters
Filters: | **Ad Blocking:** AdGuard Mobile Ads, AdGuard Base **Privacy:** AdGuard Tracking Protection **Social Widgets:** AdGuard Social **MediaAnnoyances:** AdGuard Annoyances **Language-specific:** AdGuard Russian, AdGuard German

**Comment by krystian3w** [comment]
I can reproduce.

```diff
-##.gb_0a.gb_Pg.gb_i.gb_Og > div[style*="z-index: "][style*="overflow: hidden;"][style*="margin-right: 25px;"]
+##.gb_Pg.gb_i.gb_Og > div[style*="z-index: "][style*="overflow: hidden;"][style*="margin-right: 25px;"]
```

`.gb_0a` gone from attrib class @Alex-302 .

**Comment by Yuki2718** [comment]
https://forums.lanik.us/viewtopic.php?p=156263#p156263

**Comment by krystian3w** [comment]
Callout can load useful pop-up about use Google maps (I remember one - about some changes with google maps in 2019)?

But then it sticks with hiding the pop-up in the google translation about changes in saving translations.

**Comment by Yuki2718** [comment]
> Callout can load useful pop-up about use Google maps (I remember one - about some changes with google maps in 2019)?
> 

Thanks, I'll probably need to narrow down the rule in query parameters.

**Comment by krystian3w** [comment]
> Thanks, I'll probably need to narrow down the rule in query parameters.

It's a shame that I can't help giving the whole address of that message, probably to help determine if it's possible to narrow things down.

**Comment by Yuki2718** [comment]
> > Thanks, I'll probably need to narrow down the rule in query parameters.
> 
> It's a shame that I can't help giving the whole address of that message, probably to help determine if it's possible to narrow things down.

Well, remembering such strings would be impossible to human being ;) I'll investigate the current one to see if there's something "looks to be unique", but if not found better to go to cosmetic filters.

**Comment by Alex-302** [comment]
I don't see this popup and ogs.google.com request. 
@AdguardTeam/filters-maintainers please take a look.

**Comment by zloyden** [comment]
I was able to reproduce it.
Fixed, update should be available in 1-2 hours.

**Comment by krystian3w** [comment]
@Yuki2718 restaurant version: 
```
||ogs.google.com/widget/callout?prid=19020106&pgid=19020105&puid=fb6e964fecf1855&origin=https%3A%2F%2Fwww.google.com&cn=callout&pid=1&spid=113&hl=pl
```

also hidden by new https://github.com/AdguardTeam/AdguardFilters/commit/26b7d6ff33cf8f3113b4a46ff2f87bee035ced7c

So may no worth try exclude other as chrome promotion (need collect ID imo).

**Comment by Yuki2718** [comment]
@krystian3w So it's "Discover the best restaurants nearby", looks to me a marginal case between useful and annoying. I'll move
`||ogs.google.com/widget/callout?`
from my ad-block list to annoyances list, but won't switch to cosmetic until I see a more serious problem. Thank you for informing!
