### ISSUE TITLE
http://mywatchseries.to - Redirection - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6254]
***Description***:
* **Current behaviour**: 

Redirections from http://mywatchseries.to, when pressing and choosing any TV show and playing it
reproduced on our side (Mac OS)

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1.
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,10,11,14
Ticket ID (if exists): | 1560974

**Comment by Alex-302** [comment]
fixed
