### ISSUE TITLE
chatovod.ru

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6255]
**Ссылка:** http://chatovod.ru/chats/ и http://chatovod.ru/
**Скриншот:** https://image.prntscr.com/image/wDVBezJNTrCpSONa2TG4XA.png и https://image.prntscr.com/image/rnfQSnGvQ7aP9Sp9C_4pEQ.png
***Системная конфигурация***

Информация | Значение
--- | ---
Операционка: | Windows 10
Браузер: | Chrome 60
Adguard версия: | Adguard Антибаннер 2.6.7
Adguard фильтры: | Английский фильтр Версия 1.1.28.11 / Русский фильтр Версия 1.0.55.42

**Comment by Alex-302** [comment]
Мешают нам. Завёл дефект
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/829
