### ISSUE TITLE
kinogo-x.net

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#6256]
**Ссылка:** http://kinogo-x.net/704-adaptaciya.html
**Скриншот:** http://prntscr.com/g67nkx
***Системная конфигурация***

Информация | Значение
--- | ---
Операционка: | Windows 10
Браузер: | Chrome 60
Adguard версия: | Adguard Антибаннер 2.6.7
Adguard фильтры: | Английский фильтр Версия 1.1.28.11 / Русский фильтр Версия 1.0.55.42

**Comment by Adguarder** [comment]
test
