### ISSUE TITLE
нашбийск.рф

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6257]
**Ссылка:** нашбийск.рф
**Скриншот:**  https://image.prntscr.com/image/QLVSgD-zTEq-KRYCYWItrA.png
Есть и рекламные баннеры, есть и не такие - заблокируйте аккуратно, обойдя саморекламу и социальную рекламу
***Системная конфигурация***

Информация | Значение
--- | ---
Операционка: | Windows 10
Браузер: | Chrome 60
Adguard версия: | Adguard Антибаннер 2.6.7
Adguard фильтры: | Английский фильтр Версия 1.1.28.11 / Русский фильтр Версия 1.0.55.42

**Comment by Alex-302** [comment]
Вроде всё постороннее убрано.
