### ISSUE TITLE
[Not Safe For Work] p*rn*lab.net

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6258]
**Ссылка:** http://pornolab.net/forum/viewtopic.php?t=2157718
**Скриншот:** http://i91.fastpic.ru/big/2017/0816/8d/3e64239e2e4c2320482802ecdab42d8d.png
Есть и рекламные баннеры, есть и не такие - заблокируйте аккуратно, обойдя саморекламу и социальную рекламу
***Системная конфигурация***

Информация | Значение
--- | ---
Операционка: | Windows 10
Браузер: | Chrome 60
Adguard версия: | Adguard Антибаннер 2.6.7
Adguard фильтры: | Английский фильтр Версия 1.1.28.11 / Русский фильтр Версия 1.0.55.42

**Comment by Alex-302** [comment]
поправил
