### ISSUE TITLE
nwcod.com

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6259]
**Ссылка:** nwcod.com
**Скриншот:** http://i94.fastpic.ru/big/2017/0816/1e/6b35e44d9582dfcd77f2b8688127cc1e.png
||nwcod.com/rikkom_znayka.swf
***Системная конфигурация***

Информация | Значение
--- | ---
Операционка: | Windows 10
Браузер: | Chrome 60
Adguard версия: | Adguard Антибаннер 2.6.7
Adguard фильтры: | Английский фильтр Версия 1.1.28.11 / Русский фильтр Версия 1.0.55.42

**Comment by Alex-302** [comment]
Добавил.
