### ISSUE TITLE
[NSFW] pornreactor.cc

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6260]
**Ссылка:** pornreactor.cc
**Скриншот:** http://fastpic.ru/view/95/2017/0816/b74400e41c942314feececb712ffe24e.png.html
***Системная конфигурация***

Информация | Значение
--- | ---
Операционка: | Windows 10
Браузер: | Chrome 60
Adguard версия: | Adguard Антибаннер 2.6.7
Adguard фильтры: | Английский фильтр Версия 1.1.28.11 / Русский фильтр Версия 1.0.55.42

**Comment by Alex-302** [comment]
поправил
