### ISSUE TITLE
kinobal.ru

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6261]
**Ссылка:** kinobal.ru
**Скриншот:** http://i92.fastpic.ru/big/2017/0816/f7/1a42e79ad702cd596854d02c5f73c4f7.png
***Системная конфигурация***

Информация | Значение
--- | ---
Операционка: | Windows 10
Браузер: | Chrome 60
Adguard версия: | Adguard Антибаннер 2.6.7
Adguard фильтры: | Английский фильтр Версия 1.1.28.11 / Русский фильтр Версия 1.0.55.42

**Comment by Alex-302** [comment]
поправил
