### ISSUE TITLE
3 Missed Ads in {NSFW} Websites

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6264]
**_Site1_**: http://hotmovs.com/

***Description1***: Remove this **EMPTY SPACE** AT THE BOTTOM OF THE SITE.

<details><summary>Screenshot1:</summary>

![screenshot_205](https://user-images.githubusercontent.com/19608513/29351516-1568ccd0-8274-11e7-91f4-0edbe6923d53.png)

</details>

</br>
</br>

**_Site2_**: http://imzog.com/en/hd/

***Description2***: Remove this **EMPTY SPACE**

<details><summary>Screenshot2:</summary>

![screenshot_207](https://user-images.githubusercontent.com/19608513/29351621-8a2b2978-8274-11e7-80c7-77faaad352e4.png)

</details>

</br>
</br>

**_Site3_**: http://www.hdzog.com/videos/97917/massive-tits-amateur-bangs-after-shower/?source=99&subid=&ad_tags=hd

***Description3***: Remove this **ADBLOCK MESSAGE** 

<details><summary>Screenshot3:</summary>

![screenshot_203](https://user-images.githubusercontent.com/19608513/29351092-41d60208-8272-11e7-9d2a-177bf68adce6.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by Alex-302** [comment]
These sites are not working on my side.
I thins these sites are fake - they have a lot of visitors, but they are referal and from seach results.

**Comment by thislife81** [comment]
@AdamWr  And what do you think?
