### ISSUE TITLE
Yandex direct ads in Opera

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#62659]
We keep receiving complaints that AdGuard fails to block Yandex direct ads in Opera default tab:

<details> <summary> Screenshots: </summary>

![image](https://user-images.githubusercontent.com/15856304/91634586-14e6fe80-e9fa-11ea-8133-8d716835ee36.png)

![image](https://user-images.githubusercontent.com/15856304/91634595-2f20dc80-e9fa-11ea-9c0f-8e992e717821.png)

</details>

Browser: Opera 70.0.3728.106
AppVersion: 7.5
Windows NT 6.3.9600.0
Driver mode: WFP
HTTPS filtering: on
Subscriptions: 

FilterId:14 Name: AdGuard Annoyances filter Url: https://filters.adtidy.org/windows/filters/14.txt
FilterId:1 Name: AdGuard Russian filter Url: https://filters.adtidy.org/windows/filters/1.txt
FilterId:2 Name: AdGuard Base filter Url: https://filters.adtidy.org/windows/filters/2.txt
FilterId:3 Name: AdGuard Tracking Protection filter Url: https://filters.adtidy.org/windows/filters/3.txt
FilterId:4 Name: AdGuard Social Media filter Url: https://filters.adtidy.org/windows/filters/4.txt
FilterId:6 Name: AdGuard German filter Url: https://filters.adtidy.org/windows/filters/6.txt

AdGuard Extra Version: 1.0.137 
DNS enabled: DNS server: Cloudflare DNS doh, (https://dns.cloudflare.com/dns-query; 13), type: 13

**Comment by Eugene-Savenko** [comment]
A similar problem in Yandex Browser v. 20.8.0.903.

<details> <summary> Screenshots: </summary>

![image](https://user-images.githubusercontent.com/15856304/91744952-eec08a80-ebc2-11ea-8aca-ae5450a5c5d8.png)

</details>

AppVersion: 7.5
Windows NT 6.1.7600.0
Driver mode: TDI
HTTPS filtering: on
Subscriptions: 

FilterId:1 Name: AdGuard Russian filter Url: https://filters.adtidy.org/windows/filters/1.txt
FilterId:2 Name: AdGuard Base filter Url: https://filters.adtidy.org/windows/filters/2.txt
FilterId:3 Name: AdGuard Tracking Protection filter Url: https://filters.adtidy.org/windows/filters/3.txt
FilterId:4 Name: AdGuard Social Media filter Url: https://filters.adtidy.org/windows/filters/4.txt

AdGuard Extra Version: 1.0.140
DNS disabled

**Comment by Alex-302** [comment]
У меня не повторяется с прокси.
@stanislav-atr @Sergey-Lyapin @zloyden гляньте что там.

**Comment by stanislav-atr** [comment]
Не повторяется в Опере и Яндекс.браузере
![image](https://user-images.githubusercontent.com/68852737/91982432-e71ff380-ed32-11ea-92ee-9920c7fe3d73.png)

**Comment by Sergey-Lyapin** [comment]
На маке в опере нет рекламы даже без Адгарда

**Comment by zloyden** [comment]
Не наблюдаю рекламы.
