### ISSUE TITLE
http://kinotut.tv/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6266]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

### Current behavior

The banner on the start page, originally reported on Android, reproduced on iOS

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29353954-99fd8706-8274-11e7-88a0-80a2e9b8e3d9.png)

</details>

### Expected behavior

The issue does not occur.

### Steps to reproduce the problem

1. Go to http://kinotut.tv/
2. See a banner

### System configuration

Information | value
--- | ---
Operating system: | iOS, Android
Browser: | Opera, Safari
Adguard version: | the current releases
Android: | VPN, HQ mode, no DNS, no HTTPS, 2, 3, 4, 14, 10, 1, 5, 11, 15
iOS: | no simplified filters, no DNS, Russian, English, safari, mobile ads, annoyances, and spyware

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
