### ISSUE TITLE
http://ex-fs.net/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6267]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

### Current behavior

Missed banners

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29355488-e96c91d8-8279-11e7-80c5-1e744c76aa00.png)

![image](https://user-images.githubusercontent.com/15856304/29355490-ee066e94-8279-11e7-8fa3-66c40d125126.png)

![image](https://user-images.githubusercontent.com/15856304/29355531-17964c84-827a-11e7-95da-d8eaafc86f78.png)

</details>

### Expected behavior

The issue does not occur.

### Steps to reproduce the problem

1. Go to http://ex-fs.net/genre/%D0%BA%D0%BE%D0%BC%D0%B5%D0%B4%D0%B8%D1%8F
2. Wait until the page finishes loading
3. See ads

### System configuration

Information | value
--- | ---
Operating system: | Windows
Browser: | Edge
Adguard version: | the current beta 
Adguard driver (Windows): | WFP
Adguard DNS: | Default
Stealth mode options(Windows) | Off
Adguard filters: | Russian, English, Spyware, SM, Annoyances

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
