### ISSUE TITLE
ukit.com - blocks site constructor

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#6269]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Adguard blocks site contructor - https://ukit.com/sites/url/%websitename%/pages/id/index/constructor

_*%websitename% - your custom site at [ukit.com](https://ukit.com)_
* **Current behaviour**: Site constructor (editor) infinite loading

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )

Screen recording: [ukit.mov](https://performix.slack.com/files/atokarev/F6Q8G4SK0/ukit.mov)

* **Expected behaviour**: Site constructor (editor) loads with now issues

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)

***Steps to reproduce the problem***: [ukit.mov](https://performix.slack.com/files/atokarev/F6Q8G4SK0/ukit.mov)

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | macOS 10.12.6
Browser: | Chrome 60.0.3112.90 (Official Build) (64-bit)
Adguard version: | 1.4.1
Adguard DNS: | None
Adguard filters: | 1, 2, 3, 4, 12, 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
