### ISSUE TITLE
nu.nl - doesn't play videos

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#6270]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: The Annoyances filter breaks all videos on one of the biggest news sites in the Netherlands.

* **Current behaviour**: http://www.nu.nl/150575/video/hulpverleners-bergen-honderden-lichamen-in-sierra-leone-na-modderstroom.html blocks videos with some cookie-related message.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![screen shot 2017-08-16 at 18 07 43](https://user-images.githubusercontent.com/28726429/29370361-c9714e62-82ad-11e7-99dc-cfec0c537457.png)

</details>
<br>

* **Expected behaviour**: Videos should play with no issues.

***System configuration***

Information | value
--- | ---
Operating system: | macOS 10.12.6
Browser: | Chrome 60.0.3112.90 (Official Build) (64-bit)
Adguard version: | 1.4.1
Adguard DNS: | None
Adguard filters: | 1, 2, 3, 4, 12, 14

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
url is invalid

**Comment by altokarev** [comment]
Fixed. Sry.

**Comment by Alex-302** [comment]
Fixed.
