### ISSUE TITLE
http://www.teknokulis.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6271]
**_Site_**: http://www.teknokulis.com/galeri/ipucu/youtubedaki-reklamlari-kapatmak

***Description***: Incorrect blocking with Turkish filter.

<details><summary>Screenshot1 (Turkish filter is not enabled):</summary>

![screenshot_209](https://user-images.githubusercontent.com/19608513/29374172-8ebd456e-82c1-11e7-8e24-8e338fb50200.png)

</details>

<details><summary>Screenshot2 (Turkish filter is enabled):</summary>

![screenshot_208](https://user-images.githubusercontent.com/19608513/29374236-b39d11f2-82c1-11e7-8e41-b62bbaa91adf.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by Alex-302** [comment]
fixed
