### ISSUE TITLE
http://www.androidapksfree.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6272]
**_Site_**: http://www.androidapksfree.com/apk/google-play-store-apk-latest-version-download/

***Description***: 1)Remove these **Advertisement words**

<details><summary>Screenshot:</summary>

![screenshot_211](https://user-images.githubusercontent.com/19608513/29375737-1919ee9c-82c7-11e7-9f1d-b3e78a92becb.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by Alex-302** [comment]
group your issues by 5 in one. Or write to the forum.

**Comment by Alex-302** [comment]
fixed
