### ISSUE TITLE
gamersclub.com.br - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6276]
***Site***: https://gamersclub.com.br/ -> https://gamersclub.com.br/adblock
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29378793-acd05da8-82c0-11e7-8f69-9a06d2ec081e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
Spanish/Portuguese filter

**Comment by AdamWr** [comment]
Fixed.

**Comment by ronildo66** [comment]
Could you fix it again? adblock was detected again.

**Comment by AdamWr** [comment]
Could you please report it via AdGuard report tool - https://reports.adguard.com/en/new_issue.html
or add aditional information like browser, AdGuard version, AdGuard filter and steps to reproduce a problem?

I can't reproduce it here - https://gamersclub.com.br/auth
Do I need to log in?

**Comment by GUiHKX** [comment]
@AdamWr Yes, you have to be logged in to be redirected.

Here's how they do the adblock detection, plus a fix:

1. All pages are loading this script: https://gamersclub.com.br/assets/js/trackings/ads.js
2. That script creates a `<div>` element with a random `id` (I'm not sure how often the random id is changed though)
3. There's a inline script in each page checking for the existence of the element created in step 2.
4. If the element is not found, then they redirect you to https://gamersclub.com.br/adblock

The solution filter is quite simple, we just have to whitelist the script mentioned in step 1:

`@@||gamersclub.com.br/assets/js/trackings/ads.js$script,first-party`
