### ISSUE TITLE
http://vol.az/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6281]
**_Site_**: http://vol.az/

***Description***: Remove these "**REKLAM, FACEBOOK, SAYGAC**" WORDS

<details><summary>Screenshot1 (**REKLAM- RIGHT COLUMN**):</summary>

![screenshot_227](https://user-images.githubusercontent.com/19608513/29409134-f0195eb6-835b-11e7-87c7-6f23ddbb2485.png)

</details>

<details><summary>Screenshot2  (**REKLAM- LEFT COLUMN**)  :</summary>

![screenshot_229](https://user-images.githubusercontent.com/19608513/29409150-046464e2-835c-11e7-8c6c-705702283962.png)

</details>

<details><summary>Screenshot3 (**FACEBOOK, SAYGAC- AT THE BOTTOM**)::</summary>

![screenshot_231](https://user-images.githubusercontent.com/19608513/29409157-097a0748-835c-11e7-86ca-b82ec53b8662.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
Fixed.

**Comment by thislife81** [comment]
Not worked

**Comment by AdamWr** [comment]
It seems that Adguard extension does not support regular expression in extended CSS rules yet.
Fixed.
