### ISSUE TITLE
nontonanime.org - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6283]
***Site***: http://www.nontonanime.org/
***Description***: Ad banner below navbar.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29412898-d9874592-835a-11e7-8f6d-99d60167c92c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
I can't reproduce, on my end it is hidden by this rule from English filter:
`nontonanime.org##.banner`

**Comment by danidoedel** [comment]
Can't reproduce it anymore as well.
