### ISSUE TITLE
Can you make The Washington Post think they are displaying ads while blocking the ads?

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardFilters#62859]
@TimRyanAA commented on [Thu Aug 27 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3515)

There are a number of websites that will tell me to unblock my adblocker as that is how the site is supported.  I feel they should not be able to see what I am doing on my computer in regards to my choice to block or not.   Can you make these type of sites think not I am not blocking ads while blocking the ads?
Could that behavior come from some other adblocker I may (invisible to me) be running?

### Expected behavior
I should be able to read their content without them knowing if I am blocking or not.

### Actual behavior
I get a pop-up telling me the above and greying out the content

### Your environment
Windows 10

---

@DandelionSprout commented on [Sun Aug 30 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3515#issuecomment-683379664)

Typically things like this would be done with `#%#//scriptlet`-type entries, but it's exceedingly difficult to do well.

**Comment by krystian3w** [comment]
Maybe better for you is AdNauseam - that addon click in any ads and you no see that ads.

https://adnauseam.io/
https://github.com/dhowe/AdNauseam/
