### ISSUE TITLE
startclass.com - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6287]
***Site***: http://colleges.startclass.com/l/1929/Harvard-University
***Description***: Video won't load with Adguard enabled.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29413527-ef8f8a82-835c-11e7-81db-f73a87f56185.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
