### ISSUE TITLE
versus.com - Ad - Social Widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6289]
***Site***: https://versus.com/de/hasselblad-x1d-50c
***Description***: Amazon badge and share buttons.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29418465-a8e2fc44-836c-11e7-97f7-514798337c94.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Share buttons "removed", but I can't reproduce this Amazon badge.

**Comment by danidoedel** [comment]
@AdamWr That badge is still there for me:

![image](https://user-images.githubusercontent.com/10995998/29523401-3736eb0e-868d-11e7-81b0-12734bf6cdff.png)

`versus.com##.PrimeBadge__root___1mHM7`

**Comment by AdamWr** [comment]
Ok, thank you.
Added to English filter.
