### ISSUE TITLE
head-fi.org - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6290]
***Site***: https://www.head-fi.org/
***Description***: Ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29418647-3e26a468-836d-11e7-9aa2-308c2972ac54.png)

![image](https://user-images.githubusercontent.com/10995998/29418687-55603324-836d-11e7-8e72-4c6869a27e6a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
