### ISSUE TITLE
pdfdrive.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#62905]
[https://www.pdfdrive.com/the-official-ubuntu-book-e5061009.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.pdfdrive.com/the-official-ubuntu-book-e5061009.html)

This appears after a few seconds/scrolling up and down:

![overlay](https://user-images.githubusercontent.com/35470489/91913053-0e22ea80-ec8b-11ea-87c7-71e9091890e7.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
