### ISSUE TITLE
darkwebs.biz - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6291]
https://darkwebs.biz/

<details><summary>Screenshot:</summary>

![screenshot_2](https://user-images.githubusercontent.com/27292111/29422282-69aa5cc0-8380-11e7-84eb-5572ccbfa60e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.1
Adguard driver (Windows): | WFP  
Adguard filters: | 1 2 3 4 14 
Ticket ID: | 1614005

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
