### ISSUE TITLE
last.fm

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardFilters#6292]
***Description***: Anti-Adblock notification at the top of the page

<details><summary>Screenshot:</summary>

![screen shot 2017-08-17 at 20 17 39](https://user-images.githubusercontent.com/28726429/29424728-7852b67e-8389-11e7-9c78-33a09819c333.png)

</details>

<br>

Information | value
--- | ---
Operating system: | macOS 10.12.6
Browser: | Chrome 60.0.3112.90 (64-bit)
Adguard version: | 1.4.1
Adguard DNS: | None
Adguard filters: | 1, 2, 3, 4, 12, 14

**Comment by Alex-302** [comment]
Maybe this rule will fix it
```
@@||last.fm/*?args=$domain=last.fm
```

**Comment by altokarev** [comment]
Yep, that helps.

**Comment by Alex-302** [comment]
added
