### ISSUE TITLE
freetvall.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6294]
***Site***: http://freetvall.com/video/9kb116rwshsb/motors-tv
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29431698-2618a976-8399-11e7-9065-ccb51cbdf722.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.

**Comment by AdamWr** [comment]
Ok, fixed.

**Comment by danidoedel** [comment]
@AdamWr Doesn't seem to work for me.

**Comment by AdamWr** [comment]
I can't reproduce anti adblock but I see ads, so maybe they change video player.
Added to English filter:
`saracatunga.bid###contenido > .close`
`||notkodi.science/468.html`
`||notkodi.science/adcric.html`
