### ISSUE TITLE
musiker-board.de - Ad - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6295]
***Site***: https://www.musiker-board.de/forum/
***Description***: Adblock detection. Ad at the end of the site.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29437638-1064ae54-83b2-11e7-95b7-e39f919cc093.png)

![image](https://user-images.githubusercontent.com/10995998/29437645-23eeb294-83b2-11e7-9f94-5593fe0c4c07.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
