### ISSUE TITLE
ancient-origins.net

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#62950]
[https://www.ancient-origins.net/about-us](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.ancient-origins.net/about-us)

<details><summary>Screenshot:</summary>

![anti-adblock message](https://user-images.githubusercontent.com/35470489/92002762-99958d80-ed16-11ea-98ff-53ae41753804.png)
</details><br/>

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by stanislav-atr** [comment]
Not reproduced on my end.
@AdguardTeam/filters-maintainers please take a look.

**Comment by zloyden** [comment]
Also not reproduced on my end.

**Comment by adranger** [comment]
Thanks.

@mapx- Please check if you get this.

**Comment by mapx-** [comment]
I cannot reproduce, try:
`ancient-origins.net##+js(nostif, offsetHeight)`
