### ISSUE TITLE
thomann.de - Social Widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6296]
***Site***: https://www.thomann.de/de/akg_k_872.htm?ref=search_rslt_akg_396180_33
***Description***: Social share leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29437717-b060d860-83b2-11e7-8a07-5d32f3743681.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
