### ISSUE TITLE
https://www.gazeta.ru - yandex direct

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6298]
Mac, Safari

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29450784-ccc92164-8408-11e7-9155-5b2417a26f90.png)

![image](https://user-images.githubusercontent.com/15856304/29450792-d575b5c0-8408-11e7-90a9-71da1fc8269a.png)

</details>

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | OSX
Browser: | Safari
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | English, Russian, Social Media, Experimental, Spyware, German
Ticket ID (if exists): | 1612080

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
I could not reproduce.

**Comment by highglossy** [comment]
Sometimes, AdGuard icon in footer doesn't appear, in this case ad doesn't blocked.
If this case will repeats, I'll send you screenshot.

**Comment by Alex-302** [comment]
Да можно по-русски писать)
Похоже, что проблема с фильтрацией HTTPS. Фильтры в этом случае(отсутствие этой фильтрации) не помогут.
Используете какие либо сетевые фильтры?

**Comment by highglossy** [comment]
Нет, ничего больше не использую, то то и удивительно.
Те блокираторы что были, выключены давно, как только вашу программу купил.

P.S.
Не знал, что это русскоязычные такой отличный софт сделали, хотя, мог бы и догадаться 😄
И много ли вас, если не секрет над ним трудится? 

<img width="879" alt="2017-08-18 09 44 34 pm" src="https://user-images.githubusercontent.com/1279696/29472949-728618e6-845e-11e7-9ffb-b03b22dff5b2.png">

**Comment by Alex-302** [comment]
Антвируса тоже нет?

> И много ли вас, если не секрет над ним трудится?

коллектив)

**Comment by altokarev** [comment]
@evgeniy-ADG Попробуйте поставить свежую бету: https://github.com/AdguardTeam/AdguardForMac/releases/download/v1.4.2.390/Adguard-1.4.2.beta.dmg

@highglossy Вам тот же совет :)

**Comment by highglossy** [comment]
Нет, антивируса нет.

Спасибо, поставлю бету, отпишусь
