### ISSUE TITLE
Reconsider a popin rule in JP filter

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#62998]
Please read this EL issue: https://github.com/easylist/easylist/issues/6009
In essence, whole blocking of popin (`||popin.cc^$third-party`) causes many troubles. I think we have two options:

1: Block all popin recommend while leaving popin search intact
In this case, the rule will be replaced by
```
||popin.cc/searchbox
@@||popin.cc/searchbox/action_$script
```
and the same tracking rules below.

2. Block only popin ads and trackers
This is actually more difficult. At least these rules will be needed:
```
||imageaws.popin.cc/discovery/
||popin.cc/searchbox/popin_ad_
##._popIn_recommend_article_ad
##._popIn_recommend_article_ad_reserved
```
```
.cc/s.gif?
/logs/discovery?
||log.popin.cc^
```
However, they make many websites' popin-recommend boxes bit ugly.
Ex. at `https://animeanime.jp/article/2020/08/31/56005.html`

![animeanime](https://user-images.githubusercontent.com/58900598/92114226-76a8cd80-ee2b-11ea-8f6a-11f134e91656.png)

In some cases they can be sorted out by extended syntax (if you need, happy to help this - juts copy from my list) but other cases require CSS and I haven't gone that way.

**Comment by Alex-302** [comment]
Hi
I don't see these requests end elements:
```
||imageaws.popin.cc/discovery/
||popin.cc/searchbox/popin_ad_
##._popIn_recommend_article_ad
##._popIn_recommend_article_ad_reserved
```

Could you please post full URLs?
```
.cc/s.gif?
/logs/discovery?
```

`||log.popin.cc^` is already in tracking protection.

**Comment by Yuki2718** [comment]
@Alex-302 E.g. 
```
https://animeanime.jp/article/2020/09/05/56103.html
https://www.fnn.jp/articles/-/23588
https://getnavi.jp/world/528525/
```

You need to badfilter `||popin.cc^$third-party` to see them as I'm talking about what to do AFTER removing the rule.

**Comment by Alex-302** [comment]
@Yuki2718 removed `||popin.cc^$third-party`
added 
```
||popin.cc/searchbox/popin_ad_
##._popIn_recommend_article_ad
##._popIn_recommend_article_ad_reserved
```
Not sure about `||imageaws.popin.cc/discovery/`. Does it block ads only?

**Comment by Yuki2718** [comment]
> 
> Not sure about `||imageaws.popin.cc/discovery/`. Does it block ads only?
> 

Yes AFAIK. See this:

![fnn](https://user-images.githubusercontent.com/58900598/92923576-a29f0100-f472-11ea-801b-386623f6ab2f.png)

Only images labelled as AD uses that path. Please keep this issue opened, I'll come back later with a few additional filters for suggestion.

**Comment by Yuki2718** [comment]
So this is the set of rules for better aesthetics for some websites which can be done within extended syntax (:has ):
```
animeanime.jp,cinemacafe.net,gamespark.jp,getnavi.jp,gow.asia,iionna.tokyo,inside-games.jp,macaro-ni.jp,mag.digle.tokyo,media.mamatenna.jp,moneyforward.com,mirror.asahi.com,realsound.jp,saitama-np.co.jp,the-uranai.jp,yamahack.com,yukawanet.com#?#._popIn_infinite_page > li:has(._popIn_recommend_article_ad)
animeanime.jp,getnavi.jp,the-uranai.jp#?#._popIn_infinite_page > li:has(._popIn_recommend_article_ad_reserved)
chosunonline.com,taishu.jp#?##_popIn_recommend li:has(._popIn_recommend_article_ad)
cinemacafe.net#?#._popIn_infinite_page:has(._popIn_recommend_article_ad_reserved)
```
Before (n*2 or n*3 matrix with random spaces):
<details>

![fnn1](https://user-images.githubusercontent.com/58900598/92943201-76dd4480-f48d-11ea-9127-0a1568481a99.png)

</details>
After (always 2*3 matrix without space):
<details>

![fnn2](https://user-images.githubusercontent.com/58900598/92943428-b4da6880-f48d-11ea-967c-d1aa8f446d54.png)
</details>

There are still bunch of websites where CSS needed, but I just ignore them - not a serious matter anyway. Sorry I now found some websites in the rules such as animeanime.jp now falls into this group, but the rules don't make looking bad, they're just not enough.

**Comment by Alex-302** [comment]
Great, thanks!
