### ISSUE TITLE
Newsify app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6299]
Ads in the [Newsify app](https://itunes.apple.com/us/app/newsify-your-news-blog-rss-feed-reader/id510153374?mt=8).

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29451182-5cd94328-840a-11e7-87ca-f3fec6ee7174.png)

</details>

***Steps to reproduce the problem***:

1. Install the app
2. Add a subscription
3. Go to unread posts
4. Tap a post to open in full screen
5. See an ad

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | none
Adguard version: | 1.3.0
Simplified filters(iOS) | Off
Adguard DNS: | Default
Adguard filters: | English, Russian and others
Ticket ID (if exists): | none

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
Here's the DNS log I recorded - 1079300, an app popped up ~ 11:35-40 local time

**Comment by highglossy** [comment]
A lot of ad on Championat.com and www.the-village.ru pages.

![img_1177](https://user-images.githubusercontent.com/1279696/29451730-64b8f550-840c-11e7-9e79-7c46fd080d4c.PNG)
![img_1178](https://user-images.githubusercontent.com/1279696/29451732-65010796-840c-11e7-869a-c2340fa33d27.PNG)
![img_1179](https://user-images.githubusercontent.com/1279696/29451733-65048100-840c-11e7-834e-66973cbca7a9.PNG)

**Comment by Alex-302** [comment]
@highglossy please open separate issue.

**Comment by Alex-302** [comment]
@evgeniy-ADG  I can't reproduce, but I am using beta version. Which tunnel mode is selected?

**Comment by highglossy** [comment]
Если AdGuard фильтрует рекламу в Newsify, то я незамедлительно его куплю.

**Comment by Alex-302** [comment]
@highglossy iOS не предоставляет таких возможностей как настольные ОС или Android, но рекламу Google Adguard для iOS блокирует(с помощью DNS). В приложениях iOS реклама блокируется только с помощью DNS, поэтому некоторую рекламу, расположенную на основном домене заблокировать невозможно(без поломки какого-либо функционала).

**Comment by highglossy** [comment]
Спасибо, попробую.
За хороший продукт денег не жалко

**Comment by Alex-302** [comment]
@evgeniy-ADG 

> I can't reproduce, but I am using beta version. Which tunnel mode is selected?

**Comment by highglossy** [comment]
Купил PRO-версию, погонял и понял, что в Newsify Adguard пропускает рекламу. Может я что-то настроил не так?
Хотя я включил VPN и Системный DNS.

Давайте вместе одолеем эту заразу! 😉

**Comment by Alex-302** [comment]
@highglossy покажите скриншот.
Какой режим туннеля выбран в расширенных настройках?

**Comment by highglossy** [comment]
![img_1257](https://user-images.githubusercontent.com/1279696/29893474-e0bcfbf6-8dda-11e7-8db8-d23ccc1a8e1e.PNG)
![img_1258](https://user-images.githubusercontent.com/1279696/29893477-e0d19d2c-8dda-11e7-99ef-ae1d7ba1c7e1.PNG)
![img_1259](https://user-images.githubusercontent.com/1279696/29893475-e0bd4b7e-8dda-11e7-855f-3179e5b43eab.PNG)
![img_1260](https://user-images.githubusercontent.com/1279696/29893476-e0c35cee-8dda-11e7-9c6e-e319d0db861e.PNG)

**Comment by highglossy** [comment]
Ну что, что я сделал не так?

**Comment by Alex-302** [comment]
Нужно вместо системного DNS указать свой. В данном случае - DNS Adguard
```
По умолчанию
Блокирует рекламу, счетчики и фишинговые сайты
176.103.130.130
176.103.130.131
```
```
Семейный
"По умолчанию" + блокировка взрослых сайтов + безопасный поиск
176.103.130.132
176.103.130.134
```
потом выкл/вкл режим полёта, чтоб сбросился кэш DNS.
Если не поможет, попробуйте режим Full-Tunnel.
