### ISSUE TITLE
https://mail.yandex.ru - yandex direct

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6300]
Missed Yandex Direct ads in Opera. No native ad blockers and VPN.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29452393-e88a726c-840e-11e7-9bbf-418f3afd394e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows NT 6.1.7601 Service Pack 1
Browser: | Opera
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | TDI
Adguard DNS: | None 
Adguard filters: | 1 and 2
Ticket ID (if exists): | 1218594

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
Pleas check after 1-1.5 hours.
