### ISSUE TITLE
bitvid.sx - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6306]
***Site***: http://www.bitvid.sx/file/d1552f5e21a68 (Click on "Continue to video")
***Description***: Ads.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29454885-342d9320-840f-11e7-9f1e-64621f1bdb9a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
