### ISSUE TITLE
heidelberg24.de - Social Widget - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6307]
***Site***: https://www.heidelberg24.de/
***Description***: Ad leftovers. Whatsapp share button.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29456185-e95df820-8414-11e7-8ff4-853a4f17fbf6.png)

![image](https://user-images.githubusercontent.com/10995998/29456201-f9417460-8414-11e7-8c32-8e369b343a45.png)

**https://www.heidelberg24.de/heidelberg/heidelberg-plattform-dogsharing-deutschland-verbindet-hunde-besitzer-und-neue-freunde-8605734.html:**

![image](https://user-images.githubusercontent.com/10995998/29456221-0eae3068-8415-11e7-90c4-8b8c9f0871bc.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
