### ISSUE TITLE
youtube.com cookie banner and annoyance

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#63081]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Annoyance. After i clicked on "nein danke" a cookie banner appears. Only appears on non logged in users.
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="336" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/92238674-fda48700-eeb9-11ea-8db0-afda218eb1b7.PNG">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.12
Filters enabled:                       | default + Adguard Germany + Adguard Tracking Protetion + Adguard Annoyances
AdGuard DNS:                           | None

**Comment by BlazDT** [comment]
Added Ext-CSS rule to hide that specific popup, so cookie message should not show anymore. Update available in about 3 hours.

**Comment by THEtomaso** [comment]
Even when blocked, the new sign in popup still causes the videos to stop, and no one seems to have found a way around it yet. :(

Here are links to the relevant uAssets reports, in case someone eventually comes up with a working solution:
https://github.com/uBlockOrigin/uAssets/issues/7636/
https://github.com/uBlockOrigin/uAssets/issues/7842/
