### ISSUE TITLE
brookecormier.com

### ISSUE THREAD

**Issue by betterwebleon** [AdguardTeam/AdguardFilters#6309]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: The filter rule `~` blocks background image on the webpage:
https://www.brookecormier.com/
The following exception rule solves the problem:
`@@||static.wixstatic.com/media`

***Steps to reproduce the problem***: Enable Adguard English Filter.

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | Value
--- | ---
Operating system: | Windows 10 32-bit
Browser: |  Mozilla Firefox
Adguard filter: | English Filter (added to uBlock Origin)

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
This "rule" was removed from our filter few days ago.

**Comment by betterwebleon** [comment]
Sorry, I forgot to update filter lists.
