### ISSUE TITLE
1337x.to [popup]

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6310]
- Download Magnet or Download Torrent Button open random popup in first click.
- Direct download/anon = scam.

**Comment by Alex-302** [comment]
Fill the template, please.

**Comment by FadeMind** [comment]
`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Adguard filter lists:
![image-20170818-002](https://user-images.githubusercontent.com/9846948/29465558-fee2cb56-8439-11e7-89f0-313d82c9170f.png)

**Comment by AdamWr** [comment]
Fixed.
