### ISSUE TITLE
dropgalaxy.in, dropgalaxy.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#63102]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Anti Adblock overlay after the countdown and fake button on final page
`https://dropgalaxy.in/nuxd85nycfdz`
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="771" alt="Unbenannt2" src="https://user-images.githubusercontent.com/48647394/92246117-98569300-eec5-11ea-9f3a-8a13593e1329.PNG">
<img width="424" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/92246183-b15f4400-eec5-11ea-9149-a2e06890dea8.PNG">

</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.12
Filters enabled:                       | default + Adguard Germany + Adguard Tracking Protetion + Adguard Annoyances
AdGuard DNS:                           | None

**Comment by JobcenterTycoon** [comment]
Again Anti Adblock overlay

**Comment by JobcenterTycoon** [comment]
The fake button is back now they use the link shortener `rb.gy`
<img width="346" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/96726468-4e146d00-13b2-11eb-92e9-55cd761d50ac.PNG">

**Comment by AdamWr** [comment]
Unfortunately I can't reproduce it.
Does something like this:
`dropgalaxy.com##a[href^="https://rb.gy/"]`
work?

**Comment by JobcenterTycoon** [comment]
hmm they changed the Link back to `bit.ly` really fast so my issue is pointless now

**Comment by AdamWr** [comment]
Okay, thank you for your reply.

**Comment by JobcenterTycoon** [comment]
Now they use `http://tiny.cc`
<img width="647" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/97593026-90b4f580-1a01-11eb-9db0-dd17fbb206c1.PNG">

**Comment by AdamWr** [comment]
Ok, fixed.
Update should be available in 1-2 hours.

**Comment by JobcenterTycoon** [comment]
Now they open Popups `https://dropgalaxy.in/23uhfmy8ynj7`

**Comment by AdamWr** [comment]
I can't reproduce any popups.
Could you please check these rules:
```
dropgalaxy.com#%#//scriptlet("abort-on-property-write", "_pop")
dropgalaxy.com$$script[data-cfasync="false"][wildcard="*['push']*['shift']*decodeURIComponent*"][min-length="1000"][max-length="4000"]
```

**Comment by JobcenterTycoon** [comment]
Yes it works

**Comment by AdamWr** [comment]
Okay, added.
Thank you for your reply.
