### ISSUE TITLE
channel4 antiadblock

### ISSUE THREAD

**Issue by ghajini** [AdguardTeam/AdguardFilters#6312]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: antiadblock
* **Current behaviour**: 
there is antiadblock in playing video

<details><summary>Screenshot:</summary>

![image](https://image.prntscr.com/image/wSBwAnuxQP_IO-7pY31zMg.png)
</details>

* **Expected behaviour**:
video should play without ads/antiadblock

***Steps to reproduce the problem***:
url=
http://www.channel4.com/programmes/britain-at-low-tide/on-demand/64335-001

2.geolock -***uk***
3.you will need login that you can grab at 
http://bugmenot.com/view/channel4.com
1st account works......

4.once logon, antiadblock kicks in
***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: |  chrome 60
Adguard version: |  browser extension 2.6.7
Adguard filters: | english filter, spyware filter
Ticket ID (if exists): | 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It does not work vith TunnelBear and disabled filters

<details>

![image](http://imagizer.imageshack.com/img922/3433/MPHZ1p.png)
</details>
@AdamWr could you check it?

**Comment by ghajini** [comment]
@alex-302 use either browsec VPN or modheader app with UK ip

**Comment by AdamWr** [comment]
Could you please check these rules?
`@@||cf.http.anno.channel4.com^$domain=channel4.com`
`@@||ak.http.anno.channel4.com^$domain=channel4.com`

**Comment by ghajini** [comment]
Working except for some interstitial ads ....video has 4 bars at which ad starts for moment .....

**Comment by AdamWr** [comment]
I know about this, I have solution, but only for Adguard for Windows, unfortunately I do not know how to block/remove this with Adguard extension.

**Comment by ghajini** [comment]
Above rules not working for a ***NEW*** video to be watched......you will get antiadblock....then reload the page ...antiadblock notice on this URL gone......now proceed further towards unwatched video(they remember watch history), it will produce antiadblock....what is just happening?
Is it possible to replace player....or any other solution

**Comment by AdamWr** [comment]
On my end it happens randomly and very rarely and this does not have to be a "new" video, on watched video it also happens.

> Is it possible to replace player....or any other solution

I don't know.
@Alex-302 could you please help?

**Comment by ghajini** [comment]
@Alex-302

**Comment by Alex-302** [comment]
@ghajini what do you mean? Do these rules help you?

**Comment by ghajini** [comment]
As far as tested, its currently working

**Comment by Alex-302** [comment]
ok, added
