### ISSUE TITLE
idnes.cz

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardFilters#6315]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
Annoyance at the bottom:

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/14153331/29466655-5a16339e-8446-11e7-8c41-145d4f30c523.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.3.0.81
Simplified filters(iOS) | Off
Adguard DNS: | None

Adguard filters:
```
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.87 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.79 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.8 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.84 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.54 Enabled=YES
ID=105 Name="EasyList Czech and Slovak" Version=1.0.2.8 Enabled=YES
```
Ticket ID (if exists): | 1614392

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
In `EasyList Czech and Slovak` is this rule - `@@||idnes.cz$elemhide`, so it disable cosmetic rules.
I "overrided" it with `@@||idnes.cz^$generichide,important` and added this rule - `idnes.cz##[id^="r98."].r-box` to hide ad leftovers.
Unfortunately I do not see this element from screenshot, so please check if these rules fixed issue.

**Comment by Alex-302** [comment]
@Bohdan-SUP

**Comment by Bohdan-SUP** [comment]
Seems to works fine in Safari and iOS user-agent. Asked the user to check as well.

**Comment by veronikasav** [comment]
No, it didn't help.

**Comment by Alex-302** [comment]
@AdamWr

**Comment by AdamWr** [comment]
Added to English filter:
`idnes.cz##div[id^="r98."][class*="touch"]`
`idnes.cz##.art-full > #text-out-box + div:not([class]):not([id]) > .r-head`
Unfortunately I do not see this ad leftover from screenshot from first post, so if it still does not work, please ask user about new screenshot and link.
