### ISSUE TITLE
get.u-stream.in, ustore.bz

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#63158]
https://jsfiddle.net/Smorvel/4zon1web/2/embedded/#Result
Не работает переключение качества из за AdGuard

**Comment by Alex-302** [comment]
Не вижу переключателей качества.

**Comment by Smorvel** [comment]
@Alex-302 
![test](https://user-images.githubusercontent.com/19754243/92501211-8430cf80-f1fe-11ea-80da-73fcc546a9f0.gif)

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/92590068-3ff80a80-f2a4-11ea-8d61-9cb6cba081f9.png)
Там нет кода с плеером.

**Comment by Smorvel** [comment]
@Alex-302 Просто перейди на вкладку Result как на моей гифке)

**Comment by Alex-302** [comment]
Да обпереходился уже, не грузилось ничего.
Сейчас наблюдаю такое:
![image](https://user-images.githubusercontent.com/8361299/92786646-17aa0200-f3b1-11ea-8959-489b2ef018fc.png)

**Comment by Smorvel** [comment]
@Alex-302 У меня грузится и грузилось без проблем с самого начала) Как я понял у тебя переключает качество, сейчас проверил, у меня все еще не переключает происходит это из за фильтра AdGuard Base Filter (использую приложение а не расширение), могу сейчас методом тыка поискать из за какого конкретно правила блокируется переключение.. Когда найду дополню этот ответ.

**Comment by Alex-302** [comment]
Программа ведёт себя корректно - что в фильтрах добавлено, то и применяется. С расширением тоже не должно было работать переключение, как в случае с ubo.
