### ISSUE TITLE
thescore.com - Ad leftover - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6316]
***Site***: https://www.thescore.com/news/1341961
***Description***: Ad leftover and newsletter stuff and cookie notice.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29467101-80c19292-843f-11e7-9261-e7f4f0d72dad.png)

![image](https://user-images.githubusercontent.com/10995998/29467094-7b399cc0-843f-11e7-911e-05e9692b21ae.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr There is some newsletter stuff when scrolling down:

![image](https://user-images.githubusercontent.com/10995998/29539319-a22f9adc-86c9-11e7-9035-090142fb3598.png)
