### ISSUE TITLE
gamesradar.com - Social Widget - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6319]
***Site***: http://www.gamesradar.com/
***Description***: Social leftover and newsletter stuff.

<details>
<summary>Screenshot</summary>

**http://www.gamesradar.com/create-your-own-original-it-artwork-to-win-the-ultimate-stephen-king-fan-experience/:**

![image](https://user-images.githubusercontent.com/10995998/29473675-eb8a4dd0-8458-11e7-9c52-21e00c0a7d3b.png)

![image](https://user-images.githubusercontent.com/10995998/29473686-f63001a8-8458-11e7-88b3-da8ba0f41adf.png)

**It takes really long until this part is removed, not sure if that is intended or an issue? (http://www.gamesradar.com/sony-ps5-release-date-news-specs-features/):**

![image](https://user-images.githubusercontent.com/10995998/29473733-30727418-8459-11e7-8cad-4308e3218132.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
