### ISSUE TITLE
swindonadvertiser.co.uk - Annoyance - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6320]
***Site***: http://www.swindonadvertiser.co.uk/news/15479723.Police_appeal_for_Mannington_Recreation_Ground_stabbing_witness/
***Description***: Ad top left. Cookie notice at the bottom. Newsletter sign up.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29473856-a76e82be-8459-11e7-92dc-c8a00a949612.png)

![image](https://user-images.githubusercontent.com/10995998/29473880-b924bcb2-8459-11e7-8ac3-1a81a5c766d2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
