### ISSUE TITLE
support.microsoft.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#63201]
[https://support.microsoft.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://support.microsoft.com/ru-ru/office/%d0%bf%d0%be%d0%b4%d0%b4%d0%b5%d1%80%d0%b6%d0%ba%d0%b0-%d1%81%d0%bf%d0%b5%d1%86%d0%b8%d0%b0%d0%bb%d1%8c%d0%bd%d1%8b%d1%85-%d0%b2%d0%be%d0%b7%d0%bc%d0%be%d0%b6%d0%bd%d0%be%d1%81%d1%82%d0%b5%d0%b9-%d0%b2-word-c014d8b8-4ef3-4a7a-935d-295663f3343c?ui=ru-ru&rs=ru-ru&ad=ru)

![sharing icons](https://user-images.githubusercontent.com/35470489/92313235-df18bb80-ef9f-11ea-9d00-8960bf94c257.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by krystian3w** [comment]
IMO mail is not social media.

**Comment by BlazDT** [comment]
Not seeing "in" button, please check @AdguardTeam/filters-maintainers
