### ISSUE TITLE
langenscheidt.com - Ad - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6321]
***Site***: https://de.langenscheidt.com/englisch-deutsch/advertisement?term=advertisement&q_cat=%2Fenglisch-deutsch%2F
***Description***: Ad button at the bottom right. Search bar/header overlaps with the logo.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29474031-3ff4714c-845a-11e7-8942-486418c82deb.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
