### ISSUE TITLE
medicalnewstoday.com - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6327]
***Site***: http://www.medicalnewstoday.com/articles/153188.php
***Description***: Newsletter overlay and newsletter sign up on mobile site. Ad leftovers. Cookie message at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29486950-122f6738-84f2-11e7-9fdf-ef412d524490.png)

![image](https://user-images.githubusercontent.com/10995998/29486952-22fa8930-84f2-11e7-8c32-c090543cdf1b.png)

![image](https://user-images.githubusercontent.com/10995998/29486967-6754a5d4-84f2-11e7-8890-8d79573487dc.png)

![image](https://user-images.githubusercontent.com/10995998/29486980-7c573f5a-84f2-11e7-9742-331412bb54d7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr There is still some ad leftover on the mobile page:

Rule: `medicalnewstoday.com##.sticky_ad_container`

![image](https://user-images.githubusercontent.com/10995998/30248361-c2c3a13c-9626-11e7-8f77-fe27a5f84dc1.png)

**Comment by AdamWr** [comment]
Thank you, added.
