### ISSUE TITLE
eveningtimes.co.uk - Annoyance - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6328]
***Site***: http://www.eveningtimes.co.uk/
***Description***: Ad at the top right. Cookie notice at the bottom. Newsletter sign ups.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29486997-cc56d5b0-84f2-11e7-97b7-d51bb653a38c.png)

![image](https://user-images.githubusercontent.com/10995998/29487001-e7e4918c-84f2-11e7-85e4-31e1ff83ea92.png)

**http://www.eveningtimes.co.uk/news/15482970.World_famous_celeb_hangout_The_Ivy_set_to_open_in_Glasgow/:**

![image](https://user-images.githubusercontent.com/10995998/29487007-f359f976-84f2-11e7-92a7-855d1e06fa62.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
