### ISSUE TITLE
warringtonguardian.co.uk - Annoyance - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6329]
***Site***: http://www.warringtonguardian.co.uk/
***Description***: Ad at the top right. Cookie notice at the bottom. Newsletter sign ups.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29487028-3a6fdefc-84f3-11e7-8d85-ba255988803a.png)

![image](https://user-images.githubusercontent.com/10995998/29487031-437de3a4-84f3-11e7-954e-fa2c631cc666.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
