### ISSUE TITLE
linkdrop.net - Ad leftover - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6330]
***Site***: http://linkdrop.net/xarI0
***Description***: Ad leftovers. Captcha blocked.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29487085-3f3bf8c0-84f4-11e7-8617-76db0abaa77e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
