### ISSUE TITLE
Tradera app is not working 

### ISSUE THREAD

**Issue by cabban** [AdguardTeam/AdguardFilters#63314]
Hello the app is not working with blocking ads 
app:Tradera
package:com.tradera
Launcher:com.tradera.tradera.screens.home.HomeActivity
![Screenshot_20200906-112242_Tradera](https://user-images.githubusercontent.com/19514493/92355626-e72e4380-f0e4-11ea-9f36-71ca83ee4649.jpg)
![Screenshot_20200906-112238_Tradera](https://user-images.githubusercontent.com/19514493/92355627-e85f7080-f0e4-11ea-8109-322e96770aec.jpg)
![Screenshot_20200906-112248_Tradera](https://user-images.githubusercontent.com/19514493/92355628-e8f80700-f0e4-11ea-84da-a39810607836.jpg)
![Screenshot_20200906-112251_Tradera](https://user-images.githubusercontent.com/19514493/92355630-e9909d80-f0e4-11ea-8733-a6eacc4c64af.jpg)

Hope it can be fixed

**Comment by Alex-302** [comment]
@cabban what is wrong?

**Comment by cabban** [comment]
> @cabban what is wrong?

You see screenshots is ads they not vanished . When tapping the x then the banner who should been there appears

**Comment by Alex-302** [comment]
But ads are blocked
![image](https://user-images.githubusercontent.com/8361299/92518354-e00c5000-f220-11ea-8eea-98a79a8804f2.png)
You see built-in part of ads.

**Comment by cabban** [comment]
> But ads are blocked
> ![image](https://user-images.githubusercontent.com/8361299/92518354-e00c5000-f220-11ea-8eea-98a79a8804f2.png)
> You see built-in part of ads.

Yes but they are moving and down ticking and then I tap x they are being a black box. But it should have info under which is not ads 😀

**Comment by Alex-302** [comment]
This a part of the app. Cannot be blocked by network filtering.
