### ISSUE TITLE
www.pch.com/ - missed ads + anti adblock

### ISSUE THREAD

**Issue by windseery** [AdguardTeam/AdguardFilters#6333]
This issue is back... https://github.com/AdguardTeam/AdguardFilters/issues/1509

**Comment by AdamWr** [comment]
How to reproduce this issue?
When I go to this website I see this notice:

> WE APPRECIATE YOUR INTEREST IN PUBLISHERS CLEARING HOUSE.
Unfortunately at this time we are unable to process international online transactions. Please keep in mind that under the official rules for Publishers Clearing House there are geographic limitations to entry into our promotions, contests and giveaways.

Is it geolocked?

![image](https://user-images.githubusercontent.com/29142494/29560233-a1095dd8-8731-11e7-9eb7-ade534f1a443.png)

**Comment by windseery** [comment]
The website knows when adblock is being used and shows this image https://github.com/AdguardTeam/AdguardFilters/issues/1509 in till you disable it, preventing any activity on the website while adblock is active. As for the geo block you got, there is not too much I can do about that. You can try a USA VPN, that might help.

**Comment by AdamWr** [comment]
Could you please check this rule:
`pch.comt#$#.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links {display:block!important;}`
