### ISSUE TITLE
http://www.163.com/ - missing Assistant

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6334]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behavior**: 

The Assistant does not appear with the EasyLish China filter. 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29489781-65a671e2-8531-11e7-9616-c23269c1b360.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29489791-9416ad44-8531-11e7-9f04-b7a396811149.png)

</details>

***Steps to reproduce the problem***:

1. Enable EasyList China
2. Visit the site

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | the latst beta
Adguard driver (Windows): | WFP
Adguard DNS: | Default
Stealth mode options(Windows) | off
Adguard filters: | EasyList China, English, Social media, Annoyances
Ticket ID (if exists): | 1496188

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced
http://imagizer.imageshack.com/img923/4192/eUSJfY.png
write here: https://github.com/AdguardTeam/AdguardAssistant
