### ISSUE TITLE
streamcloud.eu - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6337]
***Site***: http://streamcloud.eu/uo7w1t2acw6f/LiNkMaN_Th3.Y0ung.P0p3-VOSE-m720p_1x10.mkv.html
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29490346-7ee00f12-8539-11e7-94e7-596af6c68fe6.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
I can't reproduce.
Could you please check it again?

**Comment by danidoedel** [comment]
Yep I can't reproduce it anymore too.
