### ISSUE TITLE
Independent.co.uk - Embedded videos blocked (AdGuard Annoyances filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#63403]
### Affected site:
`https://www.independent.co.uk/`

### Issue:
Embedded videos are missing, because of a blocked cookie consent, which needs to be accepted!

### Example:
`https://www.independent.co.uk/arts-entertainment/films/news/godfather-iii-edit-francis-ford-coppola-mario-puzo-al-pacino-a9704361.html`

### Problem filter:
* AdGuard Annoyances filter

### Problem rules:
```
||consensu.org^$third-party
||quantcast.mgr.consensu.org^$third-party
```

### Screenshot:
Not needed, as the problem is obvious.

### Blocked assets:
```
https://quantcast.mgr.consensu.org/GVL-v2/vendor-list.json
https://quantcast.mgr.consensu.org/tcfv2/12/cmp2ui.js
```

### Possible fix:
```
@@||quantcast.mgr.consensu.org/*/cmp2ui.js$domain=independent.co.uk
@@||quantcast.mgr.consensu.org/*/vendor-list.json$domain=independent.co.uk
```

### Note:
You might also want to add something like this to **AdGuard Base filter** (to get rid of the big, empty top banner space):
`independent.co.uk##[data-tile-name="top_banner"]:upward(2)`

### Other problem filters:
* **EasyList Cookie List** / **Fanboy's Annoyance List** https://github.com/ryanbr/fanboy-adblock/issues/1407/
`||quantcast.mgr.consensu.org/choice/$script`
`||quantcast.mgr.consensu.org^*/choice.js$third-party`

* ~~**Frellwit's Swedish Filter** https://github.com/lassekongo83/Frellwits-filter-lists/issues/86/~~ _(FIXED)_
~~`||consensu.org^$third-party,domain=~crfashionbook.com|~joe.ie|~mirror.co.uk|~sourceforge.net|~sportsjoe.ie|~vi.nl`~~

* **I don't care about cookies** _(NOTIFIED)_
`quantcast.mgr.consensu.org$domain=~sourceforge.net|~vi.nl|~joe.ie|~cnews.fr`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.13.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.25 (XUL)

**Comment by Alex-302** [comment]
Thanks, fixed.
