### ISSUE TITLE
https://free-windows-cleanup-tool.en.softonic.com/? - Ads- Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6340]
***Description***:

The user is wondering why these kinds of pop-ups are not blocked by Adguard on the website https://free-windows-cleanup-tool.en.softonic.com/? on Windows beta 6.2.390.2018
Reproduced on our side (Mac OS, attaching the system details of Mac)
 

<details><summary>Screenshot:</summary>

![screen shot 2017-08-20 at 1 59 35 am](https://user-images.githubusercontent.com/28784344/29490679-e2cc9aba-854b-11e7-8ab3-6e74339f8cd7.png)

</details>

<details><summary>Screenshot:</summary>

![screen shot 2017-08-20 at 2 00 22 am](https://user-images.githubusercontent.com/28784344/29490682-e81f864e-854b-11e7-9a41-0686cc0e0c61.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14,
Ticket ID (if exists): | 553706

**Comment by AdamWr** [comment]
Fixed.
