### ISSUE TITLE
fossbytes.com -Ads - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6341]
***Description***:
* **Current behavior**: 
Why aren`t the ads automatically blocked by Adguard on: (Windows, beta version 6.2.390.2018) 
https://fossbytes.com/top-10-free-registry-cleaners-for-microsoft-windows/

Are they considered to be the integrated part of the website?
<details><summary>Screenshot:</summary>

![screen shot 2017-08-20 at 2 07 53 am](https://user-images.githubusercontent.com/28784344/29490727-41ba5610-854d-11e7-8994-666774831ac4.png)

</details>

Reproduced on our side (Mac OS)

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14,
Ticket ID (if exists): | 553706

**Comment by AdamWr** [comment]
Added to Annoyances filter:
`fossbytes.com##.td-ss-main-sidebar > .widget_execphp`
