### ISSUE TITLE
www.onegoodthingbyjillee.com - Ad - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6342]
***Description***:
* **Current behavior**: 

Why isn't the app redirecting to Amazon blocked by Adguard on: (Windows, beta version 6.2.390.2018) 
https://fossbytes.com/top-10-free-registry-cleaners-for-microsoft-windows/

Is it considered to be the integrated part of the website?

<details><summary>Screenshot:</summary>

![screen shot 2017-08-20 at 2 22 09 am](https://user-images.githubusercontent.com/28784344/29490767-dcf5a23c-854e-11e7-83ba-db9d8cf8ceda.png)

</details>

Reproduced on our side (Mac OS)

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14,
Ticket ID (if exists): | 553706

**Comment by AdamWr** [comment]
Added to English filter:
`onegoodthingbyjillee.com##.textwidget > a[href^="http://amzn.to/"] > img`
