### ISSUE TITLE
tenorshare.com, oceanofgames.com -Ads- Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6343]
***Description***:
* **Current behavior**: 
Windows beta (6.2.390.2018) 
Why isn`t the pop-up blocked by Adguard?

(1) http://www.tenorshare.com/windows-care/free-windows-8-cleaner-to-clean-up-junk-files-on-windows-8.html

(2)http://oceanofgames.com/ipl-6-pc-game-free-download/

<details><summary>Screenshot1:</summary>

![screen shot 2017-08-20 at 2 29 39 am](https://user-images.githubusercontent.com/28784344/29490784-9dace846-854f-11e7-9e6d-ad1af113438e.png)

</details>

<details><summary>Screenshot2:</summary>

![screen shot 2017-08-20 at 2 50 04 am](https://user-images.githubusercontent.com/28784344/29490863-545a5afe-8552-11e7-9737-a5853f85a849.png)

</details>

Reproduced on our side (Mac OS)

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14,
Ticket ID (if exists): | 553706

**Comment by AdamWr** [comment]
For `tenorshare.com` added to Annoyances filter:
`tenorshare.com##.wz-ads`

Could you please tell me what should I block on `oceanofgames.com`?

**Comment by ypetruk** [comment]
@AdamWr  asked the customer

**Comment by AdamWr** [comment]
@ypetruk Ok, thank you.

**Comment by AdamWr** [comment]
@ypetruk any response from user?

**Comment by Bohdan-SUP** [comment]
The user can't reproduce the issue anymore, he'll report if any.

**Comment by AdamWr** [comment]
Ok, thank you.
