### ISSUE TITLE
google.* EU consent popup rule breaks settings link in search results

### ISSUE THREAD

**Issue by terr72** [AdguardTeam/AdguardFilters#63440]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

Google recently introdcued a consent popup for users from within EU countries.
You seem to have tackled it with...
`google.*##html:style(overflow: visible !important;)`

* **Current behaviour**: 

...which doesn't allow to edit the search settings within the search results.
Clicking on settings is now non-functional.

* **Expected behaviour**: 

Settings should be accesseable.

***Steps to reproduce the problem***:

Search Google with a IP from a EU member state and try to click on the settings link in the search results.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

I'm on FF80 with uBlockOrigin using your Annoyance list.

**Comment by BlazDT** [comment]
Please ensure your filters are up2date. We do not have such rule anymore as we switched to a JS rule.

`google.*,youtube.com#%#(function(){try{var b=(new Date).getTime(),c=new Date(b+1314E6),a=location.host;a.startsWith("google.")||a.startsWith("youtube.")||(locSubString=a.substring(a.indexOf(".")+1));loc=locSubString||a;document.cookie="CONSENT=YES+; domain="+loc+"; path=/; expires="+c.toUTCString()}catch(d){}})();`

**Comment by terr72** [comment]
Your lists were indeed outdated (2 days old).
I updated all of them manually, but now the consent popup is back in it's full glory.
I also restarted Firefox and cleaned the browser cache, same result, the popup is back now.

**Comment by BlazDT** [comment]
Please add the rule I posted to user filter. FF can't get JS rules until a new extension version (API restriction).

**Comment by krystian3w** [comment]
> I'm on FF80 with **uBlockOrigin** using your Annoyance list.

Can you test this in uBlock Origin:



> `CSS`:
> 
> > ```
> > www.google.*##body.QVCmK:style(position: static !important; overflow-y: visible !important;)
> > www.google.*##html.QVCmK:style(overflow-y: visible !important;)
> > www.google.*###main #lb > div[id^="_"] > div[class*=" "]:not([id]):empty:matches-css(opacity: 0.7)
> > www.google.*###main #lb > div[id^="_"] > div[class*=" "]:not([id]):has( > span > div[role="dialog"] > #cnsw > iframe[src*="://consent.google.com"])
> > ```
> 

> `remove()`:
> 
> > ```
> > www.google.*###main #lb > div[id^="_"] > div[class*=" "]:not([id]):empty:matches-css(opacity: 0.7):remove()
> > www.google.*###main #lb > div[id^="_"] > div[class*=" "]:not([id]):has( > span > div[role="dialog"] > #cnsw > iframe[src*="://consent.google.com"]):remove()
> > ```


I suppose also break "Search settings" (but I can use "more"  / "settings"  / "tools" buttons - so you have other options)?

**Comment by terr72** [comment]
This works fine for me, I haven't experienced any problems so far, "Settings/Advanced search" does work.
