### ISSUE TITLE
[nsfw] hdzog.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6345]
Adblock detect popup:
![image-20170820-001](https://user-images.githubusercontent.com/9846948/29492827-dfcc3464-8588-11e7-851b-1bfd238f471f.png)

```
hdzog.com##.msg-adblock
```

Missing player buttons:
![image-20170820-003](https://user-images.githubusercontent.com/9846948/29492835-62b7fee4-8589-11e7-84bf-47a1a1af160e.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
Fixed.
