### ISSUE TITLE
kakprosto.ru CSS broken

### ISSUE THREAD

**Issue by vitalkanev** [AdguardTeam/AdguardFilters#6346]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: There is something going wrong with CSS on kakprosto.ru with Adgaurd enabled
* **Current behaviour**: CSS is broken (showing the top of the page)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можно вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/YInejSW.png)
</details>

* **Expected behaviour**: CSS should not be broken

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot (turned off):</summary>

![image](https://i.imgur.com/BDjV24T.png)
</details>

***Steps to reproduce the problem***: Just visit something like https://www.kakprosto.ru/kak-7686-kak-nabrat-dobavochnyy-nomer

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 Enterprise 2015 LTSB
Browser: | Yandex 17.7.1
Adguard Version | 2.6.7 Browser Extension
Adguard filters: | [Screenshot](https://i.imgur.com/4TCs16Q.png)
Ticket ID (if exists): | `undefined`

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
