### ISSUE TITLE
 propolski.com - Anti AdBlock Script - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6347]
***Description***:
* **Current behavior**: 

AntiAdBlock Script on  propolski.com on Android (reproduced on our side on Windows.)

***System configuration***

Information | value
--- | ---
Operating system: | Windows
Browser: | Chrome
Adguard version: | 6.1.298.1564
Adguard driver (Windows): | WFP 
Adguard DNS: | None 
Adguard filters: |   0, 2, 3, 4, 1, 11, 14
Ticket ID (if exists): | 1615010

**Comment by Alex-302** [comment]
fixed
