### ISSUE TITLE
[nsfw] tnaflix.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6348]
With enabled adguard videos are not loaded:
![image-20170821-003](https://user-images.githubusercontent.com/9846948/29514682-ade0f5a2-8669-11e7-84d1-3332616429c4.png)

With disabled adguard video is loaded fine.

**SETUP**
`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
Can't reproduce.
Add screenshot and replace filters list image by text.

**Comment by Alex-302** [comment]
@AdamWr please check on your side.

**Comment by FadeMind** [comment]
@Alex-302  I edited and fixed first post.

**Comment by Alex-302** [comment]
Try to disable all filters.
Is Stealth Mode enabled? Which options?

**Comment by FadeMind** [comment]
> Is Stealth Mode enabled? Which options?
YES. with these options:
```
Do-Not-Track
Removing X-Client Data header
Removing Tracking Data from URL
Self destroying third party cookies after 30 s 
Blocked WebRTC
Blocked Loc. API
```

After DISABLE whole  Stealth Mode video is loaded fine. Sorry for delayed response.

**Comment by Alex-302** [comment]
@FadeMind try to find an option(s), which breaks the video.

**Comment by FadeMind** [comment]
@Alex-302 
All options breaks video except `Do-Not-Track`. This option can be enabled and video works.

**Comment by Alex-302** [comment]
Added to English filter
```
@@||cdn-fck.tnaflix.com^$stealth
```
