### ISSUE TITLE
[nsfw] vivud.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6349]
http://vivud.com
Advertisment overlays on player, popups on click and boxes with adv.

**SETUP**
`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Adguard filter lists:
![image-20170818-002](https://user-images.githubusercontent.com/9846948/29465558-fee2cb56-8439-11e7-89f0-313d82c9170f.png)

**Comment by Alex-302** [comment]
fixed

**Comment by FadeMind** [comment]
@Alex-302  you have missed:
![image-20170821-005](https://user-images.githubusercontent.com/9846948/29515112-5535ee92-866b-11e7-97f9-93f38e0c127c.png)

```
vivud.com##.adv
```

regards

**Comment by Alex-302** [comment]
ok

**Comment by FadeMind** [comment]
I found two more fixes. (banners)
```
vivud.com##.hidden-xs, .tc-col-sm-offset-7, .player-aside-banners
vivud.com##div.im-b.show
```
Regards

NOTE: I noticed random popup after clicking on random video even after adding your new blocking rules. Please investigate. Thanks

**Comment by Alex-302** [comment]
I need the link to the page and screenshot of ads.

**Comment by FadeMind** [comment]
SAMPLE `http://vivud.com/video/12622/`



**CENSORED**

https://user-images.githubusercontent.com/9846948/29532856-7d183e76-86af-11e7-90f0-82808c0bad18.png

https://user-images.githubusercontent.com/9846948/29532858-8197a46e-86af-11e7-8fef-bb8c900346a9.png

**Comment by Alex-302** [comment]
I see only the first.
