### ISSUE TITLE
[nsfw] tryboobs.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6350]
Advertisment overlays on player,

```
tryboobs.com###videoContainer_pop
```

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
Fixed.

**Comment by Nzzyme** [comment]
Ad text string & pop-ups seen on this page:
https://www.tryboobs.com/videos/80937/indian-fat-girl-ass-fuck-video/

http://prntscr.com/nrofmj

Checked with AG for Chrome

**Comment by FadeMind** [comment]
@Nzzyme 
```
tryboobs.com##.two-rcol
```

**Comment by Alex-302** [comment]
Fixed
