### ISSUE TITLE
[nsfw] pervclips.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6351]
Advertisment overlays on player, popups on click and boxes with adv.

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
Added to English filter
```
||pervclips.com/tube/plugin.js
pervclips.com##.advertising-player

```

**Comment by Nzzyme** [comment]
Ad text string seen on AG for Chrome

https://www.pervclips.com/tube/videos/passionate-hugs-for-two-indian-lovers-fordreamers-com/

http://prntscr.com/nni8el

**Comment by FadeMind** [comment]
@Nzzyme 
```
pervclips.com##.thumb_spots
```

**Comment by Nzzyme** [comment]
https://www.pervclips.com/tube/videos/asian-porn-star-with-massive-tits-tittyfucked/

Pop-up seen when maximising the video player. Seen on AG for Chrome

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
