### ISSUE TITLE
ohmymag.de - Ad leftover - Annoyance - Social Widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6353]
***Site***: http://www.ohmymag.de/reisen/die-buntesten-orte-der-welt-hier-kannst-du-farbfilter-und-photoshop-vergessen_art7727.html
***Description***: Ad leftovers. Newsletter button. Twitter share button. Newsletter sign up banner. Facebook like in bottom right corner. Whatsapp share buttons on mobile. Facebook already liked question on mobile.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29497063-841157a4-85e1-11e7-9787-7dbb4cf2a3e6.png)

![image](https://user-images.githubusercontent.com/10995998/29497065-95483984-85e1-11e7-960d-86d682fc8c9d.png)

![image](https://user-images.githubusercontent.com/10995998/29497075-e1fc94e6-85e1-11e7-9cb7-e9f663197f5f.png)

![image](https://user-images.githubusercontent.com/10995998/29497078-f1c4f3fa-85e1-11e7-811d-20bfc1f97e2e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
