### ISSUE TITLE
pokemongopocket.com - Social Widget - Annoyance - Ad leftover - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6358]
***Site***: https://pokemongopocket.com/three-new-official-pokemon-go-events-confirmed-ohio-california-pennsylvania/
***Description***: Facebook leftover. Ad leftover. Newsletter sign up. Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29497221-a647ea38-85e4-11e7-89b7-e32119a70f35.png)

![image](https://user-images.githubusercontent.com/10995998/29497222-bba0dcdc-85e4-11e7-99cd-df30e9046078.png)

![image](https://user-images.githubusercontent.com/10995998/29497226-cc89bfbe-85e4-11e7-86fb-652dcaa38bc1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
