### ISSUE TITLE
dotesports.com - Annoyance - Ad leftover - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6359]
***Site***: https://dotesports.com/
***Description***: Ad background. Ad leftover. Newsletter bar at the bottom. Newsletter sign up box.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29497237-1a73ce72-85e5-11e7-907c-7beb5be7a193.png)

![image](https://user-images.githubusercontent.com/10995998/29497242-243fead0-85e5-11e7-87dd-9c4910fb93eb.png)

![image](https://user-images.githubusercontent.com/10995998/29497245-2d60cdf0-85e5-11e7-8589-119e79d1058d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
