### ISSUE TITLE
https://olx.com.eg/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6360]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: Adguard blocks the search bar on the site

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29497246-94211038-85ed-11e7-8d44-7923c7bf839d.png)

</details>

* **Expected behaviour**: Should not block it, see the screenshot

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29497249-a5e8a5ba-85ed-11e7-981a-d31105cb77ce.png)

</details>

***Steps to reproduce the problem***:

1. Go to the site
2. Search for smth
3. See no search bar when tapping on the magnifying glass in the top right-hand corner

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.3.0
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | 2 3 4 10 11 12 14 15 112
Ticket ID (if exists): | 1611645

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't reproduce. Please try to clear user filter.
