### ISSUE TITLE
http://www.jktfb.com.cn/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6361]
http://www.jktfb.com.cn/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29497277-217c550a-85ee-11e7-8ac8-7c9e86eae8b5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.3.0.81
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options(Windows) | 
Adguard filters: | 2 3 4 11 12 101 118 104
Ticket ID (if exists): | 1613956

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced on my side.

**Comment by Alex-302** [comment]
It is blocked by `||qhdop.com^`
