### ISSUE TITLE
espn.com - Social Widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6364]
***Site***: http://www.espn.com/fantasy/football/story/_/id/20323005/ultimate-fantasy-football-draft-board-does-perfect-draft-look-like
***Description***: Share button.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29499212-828a76a6-860c-11e7-8dbd-1785582a181b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
