### ISSUE TITLE
latimes.com - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6366]
***Site***: http://www.latimes.com/local/obituaries/la-me-jerry-lewis-20170820-story.html
***Description***: Newsletter sign up. "Article continues below" ad leftovers on mobile.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29499254-aa990e2c-860d-11e7-89cd-53559aaffc92.png)

![image](https://user-images.githubusercontent.com/10995998/29499266-d2a59bec-860d-11e7-91f6-ea68e1cb80f6.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
