### ISSUE TITLE
flashx.tv - Ad - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6368]
***Site***: https://www.flashx.tv/
***Description***: Page reloads all the time so the countdown can't go down (just choose a video on the main page). Also clicking on the logo for the first time leads to an ad page (e.g. https://dsf4t5jfds34j.com/893525.html)

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29499338-f7d3a372-860e-11e7-8f3f-3684b2e9cf1c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
> Also clicking on the logo for the first time leads to an ad page

Unfortunately I can't reproduce.

Page reloading fixed.
