### ISSUE TITLE
barstoolsports.com - Social Widget - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6370]
***Site***: http://www.barstoolsports.com/newyork/the-pacers-have-reportedly-filed-charges-against-the-lakers-for-tampering-with-paul-george
***Description***: Facebook share button. Newsletter sign up.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29499370-cd89e08a-860f-11e7-8153-d607e61607d4.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
