### ISSUE TITLE
thetimes.co.uk - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6371]
***Site***: https://www.thetimes.co.uk/edition/news/children-exposed-to-huge-rise-in-gambling-adverts-brw78dqgc
***Description***: Sign up overlay pops up after few seconds.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29499387-261b6160-8610-11e7-955d-c3f03fcf7bb1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
