### ISSUE TITLE
magicvalley.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6372]
***Site***: http://magicvalley.com/news/local/these-idahoans-are-living-with-a-serious-disease-you-could/article_64cbfbbb-58e7-5210-92c8-4ccca3020142.html
***Description***: Newsletter sign up in article.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29499396-6960b61e-8610-11e7-8e3e-a9daff598f65.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
