### ISSUE TITLE
nytimes.com - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6373]
***Site***: https://www.nytimes.com/2017/08/20/movies/jerry-lewis-dead-celebrated-comedian-and-filmmaker.html?hp&action=click&pgtype=Homepage&clickSource=story-heading&module=photo-spot-region&region=top-news&WT.nav=top-news
***Description***: Newsletter sign up. Ad leftover after article.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29499416-1469f516-8611-11e7-8dd3-359c692f560c.png)

![image](https://user-images.githubusercontent.com/10995998/29499433-631bdfb2-8611-11e7-86a6-b09a6ef64da5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
