### ISSUE TITLE
moviefone.com - Annoyances - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6374]
***Description***:
* **Current behavior**: 

Self-promotion on https://www.moviefone.com/ on Android
reproduced on our side

<details><summary>Screenshot:</summary>

![screenshot_20170821-094520](https://user-images.githubusercontent.com/28784344/29506918-92b538c8-8656-11e7-9deb-6c9d4f55974f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Chrome
Adguard version: | 2.10 beta
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard DNS: | None 
Adguard filters: | 0,1,2,3, 4,5,11,14
Ticket ID (if exists): | 1334439

**Comment by AdamWr** [comment]
I added two exceptions, because website didn't work properly and removed ad leftover.
Could you please tell me what element from screenshot I should block?
