### ISSUE TITLE
m.townhall.com - Social media widgets - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6375]
***Description***:
* **Current behavior**: 

Social media widgets aren`t blocked on https://m.townhall.com/ on Android
reproduced on our side

<details><summary>Screenshot:</summary>

![screenshot_20170821-095104](https://user-images.githubusercontent.com/28784344/29507018-01486738-8657-11e7-8832-eeb18c7d60ef.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Chrome
Adguard version: | 2.10 beta
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard DNS: | None 
Adguard filters: | 0,1,2,3, 4,5,11,14
Ticket ID (if exists): | 1334439

**Comment by Alex-302** [comment]
Fixed
