### ISSUE TITLE
vse.fm

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6376]
BOT: оповещение: новое сообщение в основной (закрытой) теме
https://github.com/AdguardTeam/AdguardFilters/issues/4846#issuecomment-323665180

**Comment by Alex-302** [comment]
Какое оповещение? Оформляй по шаблону.

**Comment by Adguarder** [comment]
новое сообщение в старой теме
https://github.com/AdguardTeam/AdguardFilters/issues/4846#issuecomment-323665180
Английский фильтр Версия 1.1.28.59.
Русский фильтр Версия 1.0.55.72.

**Comment by Alex-302** [comment]
В чужие, давно закрытые, задачи писать не нужно.
Если открываешь новую - описывай должным образом.

**Comment by Adguarder** [comment]
перекопировал все в новую тему
