### ISSUE TITLE
windowscentral.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6377]
https://www.windowscentral.com/

![image-20170821-001](https://user-images.githubusercontent.com/9846948/29509834-dca503ac-8659-11e7-825a-9d6b7d17c279.png)

```
windowscentral.com##.visor-breaker-ad
```

**SETUP**
`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
Added
