### ISSUE TITLE
askvg.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6378]
http://www.askvg.com/download-microsoft-net-framework-3-5-offline-installer-for-windows-8/

![image-20170821-002](https://user-images.githubusercontent.com/9846948/29511211-c2a08616-865e-11e7-841f-f5ff690cfe7b.png)

**SETUP**
`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Adguard filter lists:
![image-20170818-002](https://user-images.githubusercontent.com/9846948/29465558-fee2cb56-8439-11e7-89f0-313d82c9170f.png)

**Comment by Alex-302** [comment]
fixed

**Comment by The-Commissioner** [comment]
@FadeMind Is it solved at your side?

**Comment by FadeMind** [comment]
Yes, why you ask? :>

**Comment by The-Commissioner** [comment]
@FadeMind I asked because on the homepage of that site [askvg.com](http://www.askvg.com/), the 'Advertisements' tag is still there on top of sidebar. How is it on your side?

**Comment by FadeMind** [comment]
@The-Commissioner  @Alex-302 static
![image-20170905-006](https://user-images.githubusercontent.com/9846948/30064027-d840a50c-9250-11e7-95e8-3919a8d90b5e.png)

![image-20170905-007](https://user-images.githubusercontent.com/9846948/30064061-efb10c0e-9250-11e7-8b14-c79d4880d406.png)

**Comment by The-Commissioner** [comment]
So you do have it too?

**Comment by Alex-302** [comment]
fixed

**Comment by The-Commissioner** [comment]
@FadeMind Is it solved at your side?

**Comment by FadeMind** [comment]
@The-Commissioner  Yes.
![image-20170906-001](https://user-images.githubusercontent.com/9846948/30097103-426a5870-92dc-11e7-8d39-12396e99665a.png)

**Comment by The-Commissioner** [comment]
@FadeMind I asked because on the category/section pages of that site askvg.com like http://www.askvg.com/category/windows-10/ , the 'Advertisements' tag is still there on top of sidebar. How is it on your side?

**Comment by FadeMind** [comment]
@Alex-302  😁 
![image-20170906-002](https://user-images.githubusercontent.com/9846948/30098780-ad069570-92e3-11e7-8c0e-c4d5a12f28ba.png)
![image-20170906-003](https://user-images.githubusercontent.com/9846948/30098802-c77cd84c-92e3-11e7-86ec-e4726ce8132b.png)

**Comment by The-Commissioner** [comment]
What's more, it is possible to fix all these with just one rule instead of the three that we will now be having.
