### ISSUE TITLE
s3-ap-northeast-1.amazonaws.com & dldir1.qq.com

### ISSUE THREAD

**Issue by DavidTai780** [AdguardTeam/AdguardFilters#63794]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

s3-ap-northeast-1.amazonaws.com(Amazon Storage Services)

dldir1.qq.com(Tencent Server for hosting some of the file needed by some game(eg. PUBG Mobile China Version) or wechat or QQ Social App)

* **Current behaviour**: 

This two domain marked as adult content in parent control.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

The 2 domain above should not blocked by the parent control and able to access it.

<br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

Use any services of AdGuard that enabled with parent control such as Adguard Home with parent control enabled.

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 19041.508
Browser:                               | Google Chrome
AdGuard version:                       | 7.5.1
Filters enabled:                       | ?
AdGuard DNS:                           | Family Protection

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.
About Family Protection please write to support@adguard.com
