### ISSUE TITLE
ignboards.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#63803]
[https://www.ignboards.com/threads/its-not-looking-too-good-for-gamestop.455602111/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.ignboards.com/threads/its-not-looking-too-good-for-gamestop.455602111/)

![share bar](https://user-images.githubusercontent.com/35470489/93024170-d1c88600-f5ca-11ea-9911-3c4fa41d5793.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by AdamWr** [comment]
I can't reproduce it.
It seems that there is a `generichide` rule in uBO filters which is causing it.
