### ISSUE TITLE
turn-on.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6381]
***Site***: https://www.turn-on.de/work/ratgeber/pdf-dateien-komprimieren-nuetzliche-tipps-und-tools-15668
***Description***: Newsletter widget.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29516268-10beb6a4-8670-11e7-9a59-cef5465dfbbc.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
