### ISSUE TITLE
Skipped tracker on theknot.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#63818]
***Description***:
* **Current behaviour**: 

The website theknot.com connects to a tracking server to log user
engagement events. The event tracking address is a POST connection to:
https://event-gateway.dataintel.xogrp.com/event/track Blocking either
the server via DNS or the address above works and doesn't break any
features on the site.

<details><summary>Screenshot:</summary>

Not applicable.

</details><br/>

* **Expected behaviour**: 

We should block the tracker.

***Steps to reproduce the problem***:

n/a

***System configuration***

**Filters:**

"RU AdList", "Xfiles", "Fanboy's Annoyances", "Adblock Warning Removal List", "Polish Anti Adblock Filters", "EasyList Dutch", "Liste AR", "EasyList China", "List-KR", "Latvian List", "AdGuard Dutch filter", "ABPindo", "AdGuard Social Media filter", "EasyPrivacy", "AdGuard Tracking Protection filter", "I don't care about cookies", "CJX's Annoyance List", "road-block", "ChinaList+EasyList", "Fanboy's Social Blocking List", "EasyList Germany", "KAD - Przekręty", "Spam404", "Fanboy's Anti-thirdparty Fonts", "Polski Antyirytujący Dodatek Specjalny", "Fanboy's Enhanced Tracking List", "Fanboy's Swedish", "AdGuard Experimental filter", "EasyList Cookie List", "AdGuard Base filter", "BarbBlock", "EasyList Lithuania", "RU AdList: BitBlock", "ROList", "Fanboy's Spanish/Portuguese", "Polskie Filtry Ciasteczkowe", "Icelandic ABP List", "Polskie Filtry Społecznościowe", "AdGuard Japanese filter", "Polskie Filtry Elementów Irytujących", "AdGuard Mobile Ads filter", "AdGuard Annoyances filter", "Official Polish filters for AdBlock, uBlock Origin & AdGuard", "EasyList Hebrew", "Bulgarian list", "AdGuard German filter", "Fanboy Anti-Facebook List", "NoCoin Filter List", "EasyList Italy", "ABPVN List", "Adblock List for Finland", "Dandelion Sprout's Nordic Filters", "Estonian List", "Polskie Filtry Wewnętrzne", "YousList", "AdGuard DNS filter", "AdGuard Turkish filter", "AdGuard French filter", "EasyList Czech and Slovak", "AdGuard Spanish/Portuguese filter", "AdGuard Russian filter", "EasyList", "AdGuard Chinese filter", "Fanboy's Vietnamese", "RU AdList: Counters", "Online Malicious URL Blocklist", "EasyList Polish", "Peter Lowe's Blocklist", "Easylist Spanish", "Frellwit's Swedish Filter", "Web Annoyances Ultralist"

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 7.0
Browser:                               | Chrome
AdGuard version:                       | 3.5 RC 1
Filters enabled:                       | See above; list too long
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default mode)
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | Cloudflare, DoH
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | Block location API, Block push, Block WebRTC, Disable authorization third-party requests, Disable cache third-party requests, Self-destructing 1st-party cookies (60), Self-destructing 3rd-party cookies (5), Hide IP, Hide referrer, Hide search query, Hide User-Agent, Remove X-Client-Data, Send DNT header, Strip tracking parameters

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I don't see this request.
