### ISSUE TITLE
sat-universe.com - Anti-AdBlock Script - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6382]
***Description***:
* **Current behavior**: 

Anti- AdBlock Script on http://www.sat-universe.com/showthread.php?t=249958&page=385 on Windows
reproduced on our side (Mac OS)
you need to register and wait for a couple of seconds to reproduce the issue

<details><summary>Screenshot:</summary>

![screen shot 2017-08-21 at 1 53 13 pm](https://user-images.githubusercontent.com/28784344/29516318-a407bb92-8678-11e7-902b-8dc4961fdbc1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1.
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,5,11,14
Ticket ID (if exists): | 1059796

**Comment by Alex-302** [comment]
fixed
