### ISSUE TITLE
creative-tools.de - Social Widget - Ad leftover - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6383]
***Site***: https://www.creative-tools.de/internet/pdf-dateien-verkleinern/
***Description***: Social widget leftover and ads in sidebar. Ad leftover in article.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29516337-4ff0b23c-8670-11e7-8850-983819be38c1.png)

![image](https://user-images.githubusercontent.com/10995998/29516380-71370680-8670-11e7-9d2d-2364e8bb2a4b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
