### ISSUE TITLE
ru.cam4.com - ads Windows

### ISSUE THREAD

**Issue by inna13** [AdguardTeam/AdguardFilters#6384]
***Description***:
* **Current behaviour**: 

ads on ru.cam4.com  on Windows
reproduced on our side (Mac OS)

<details><summary>Screenshot:</summary>

![screen shot 2017-08-21 at 2 27 43 pm](https://user-images.githubusercontent.com/31209487/29517264-fbc688b4-867c-11e7-9a70-0faf7c18a613.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | chrome
Adguard version: | 1.4.1
Adguard DNS: | None 
Adguard filters: | 0, 1, 2, 3, 4, 11, 14
Ticket ID (if exists): | 754134

**Comment by Alex-302** [comment]
Fixed
