### ISSUE TITLE
Transform rules for Samsung Browser compatibility

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#6385]
The problem is that Samsung cannot handle `^` symbol when it means the end of URL:

For instance:
`||google-analytics.com/analytics.js^` won't match `https://google-analytics.com/analytics.js`

To fix this issue we should add a duplicate rule with `|` instead of `^` for every rule matching this regexp:
`^(@@)?\|\|.+?/.+?\^(\$.*)?$`

For instance, this rule:
```
`||google-analytics.com/analytics.js^$third-party`
```

Should be replaced with two:
```
`||google-analytics.com/analytics.js^$third-party`
`||google-analytics.com/analytics.js|$third-party`
```

**It should be done for Content Blocker filters only**

**Comment by Mizzick** [comment]
>It should be done for Content Blocker filters only
But what is Content FIlter? How to define it?

**Comment by ameshkov** [comment]
> But what is Content FIlter? How to define it?

I mean rules for iOS and for Android Content Blocker

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersCompiler #2](https://github.com/AdguardTeam/FiltersCompiler/issues/2) via [**ZenHub**](https://www.zenhub.com/)
