### ISSUE TITLE
Gordon app - Ad leftover 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6386]
https://play.google.com/store/apps/details?id=com.gordon

<details><summary>Screenshot:</summary>

![screen shot 2017-08-21 at 5 24 19 pm](https://user-images.githubusercontent.com/27292111/29523439-bed03720-8695-11e7-8751-ad5b150d1cc7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Adguard version: | 2.9.136
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (whitelist)
Adguard filters: | 1, 2, 3, 4, 14, 1, 11
Ticket ID: | 1543367

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is builtin.
