### ISSUE TITLE
n-tv.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#63868]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: I can’t play the video it only show a blank screen.
`https://www.n-tv.de/mediathek/videos/panorama/Attentat-auf-zwei-Polizisten-schockt-die-USA-article22036122.html`

I accepted cookies but still can’t play the Video
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="803" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/93113333-5a255480-f6b9-11ea-8bc5-945e25e0c452.PNG">

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

<img width="783" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/93113404-71fcd880-f6b9-11ea-8871-c478f6df8fe5.PNG">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.12
Filters enabled:                       | default + Adguard Germany + Adguard Tracking Protetion + Adguard Annoyances
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Video plays fine for me, please check @AdguardTeam/filters-maintainers

**Comment by AdamWr** [comment]
@JobcenterTycoon Could you please check this rule:
`@@||cdn.privacy-mgmt.com/consent/$domain=n-tv.de`

**Comment by JobcenterTycoon** [comment]
It works

**Comment by AdamWr** [comment]
Okay, added.
Thank you for your answer.

**Comment by JobcenterTycoon** [comment]
Video breakage again because anyone added this filter https://github.com/AdguardTeam/AdguardFilters/commit/11ceb41b6566b23ae5ae9831c1db25c2d9272f27

**Comment by zloyden** [comment]
Thanks, removed it, The update should be available in 1-2 hours.
