### ISSUE TITLE
Backgrounds app - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6387]
https://play.google.com/store/apps/details?id=com.ogqcorp.bgh

<details><summary>Screenshot:</summary>

![screen shot 2017-08-21 at 5 24 37 pm](https://user-images.githubusercontent.com/27292111/29523648-59e44742-8696-11e7-93c5-54567a4bd773.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.136
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (whitelist)
Adguard filters: | 1, 2, 3, 4, 14, 1, 11
Ticket ID: | 1543367

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't reproduce.

**Comment by AdamWr** [comment]
I can't reproduce this too.
I see these ads only if I disable Adguard.

**Comment by ypetruk** [comment]
комментарий(Ticket ID: 1543367)
В комментариях почему-то написано, что проблему не могут воссоздать или что проблема существует только с отключенным приложением. Высылаю повторно скриншот, на котором видно, что в момент обнаружения рекламы Adguard у меня активен. Это видно по знаку vpn на панели задач
<details><summary>Screenshot:</summary>

![screenshot_20170902-201333](https://user-images.githubusercontent.com/28784344/29999647-b41ad222-9059-11e7-943a-383cd332dc64.png)

</details><br/>

**Comment by Alex-302** [comment]
@ypetruk проси логи запросв с указанием вредени. Перед записью лога нужно остановить приложение и очистить его кэш.

**Comment by ypetruk** [comment]
@Alex-302 спросила
