### ISSUE TITLE
Typo in filters [Base] [Annoyance]

### ISSUE THREAD

**Issue by krystian3w** [AdguardTeam/AdguardFilters#63873]
<ul><li>

### `oberflow` - `overflow`:

https://github.com/AdguardTeam/AdguardFilters/blob/aed4e49079b81c31c7f31f0a7c3874a42214ceb7/AnnoyancesFilter/sections/popups.txt#L1067-L1068

`itemci.com#$#body { overflow: visible!important; }`
`itemci.com#$#html { overflow: visible!important; }`

---

<li>

### `#$##.`  - empty ID (?):

https://github.com/AdguardTeam/AdguardFilters/blob/a7933cdf878d3d5aac704be1b85573f140c3034b/AnnoyancesFilter/sections/cookies_specific.txt#L1758

 `511tactical.com#$#.modal-backdrop { display:none!important; } `

---

<li>

 ### double `{ display: none!important; } { display: none!important; }`:

https://github.com/AdguardTeam/AdguardFilters/blob/46d85cb981332da56bb3d85246a388a992c8959d/AnnoyancesFilter/sections/self-promo.txt#L739

`protanki.tv#$#.ant-modal-mask { display: none!important; }`
 
</ul>

---

related: https://github.com/uBlockOrigin/uBlock-issues/issues/382#issuecomment-692198617

**Comment by BlazDT** [comment]
Thank you, fixed.
