### ISSUE TITLE
http://silentall.com/

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6388]
**_Site_**: http://silentall.com/katilimsiz-programlar/23725-aome-partition-assistant-professional-650-turkce-katilimsiz.html

***Description***: 1)Remove these **ADLEFTOVERS**

<details><summary>Screenshot:</summary>

![screenshot_29](https://user-images.githubusercontent.com/19608513/29527741-d0f8ccd6-86aa-11e7-8674-55fc0689cffe.png)

</details>

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by AdamWr** [comment]
Social widget and ad leftover (Sponsor) removed, but other two elements are too small and have similar name to others, so I leave it.
