### ISSUE TITLE
focus.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#63883]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Unable to play Videos. 
`https://www.focus.de/politik/videos/bekanntes-gang-mitglied-stirbt-aufstand-im-gefaengnis-100-insassen-attackieren-sich-mit-selbstgemachten-waffen_id_4882332.html`

***Steps to reproduce the problem***: accept cookies and try to play the video

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.12
Filters enabled:                       | default + Adguard Germany + Adguard Tracking Protetion + Adguard Annoyances
AdGuard DNS:                           | None

**Comment by BlazDT** [comment]
Working fine here, please check @AdguardTeam/filters-maintainers

**Comment by AdamWr** [comment]
`@@||cdn.privacy-mgmt.com/consent/$domain=focus.de`
