### ISSUE TITLE
Yahoo mail - Ads

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6389]
<details><summary>Screenshot:</summary>

![screen shot 2017-08-21 at 7 52 58 pm](https://user-images.githubusercontent.com/27292111/29532045-f7bc96c8-86b3-11e7-88c2-9f93e8e66194.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Edge
Adguard version: | 6.1
Adguard driver (Windows): | TDI
Stealth mode options(Windows) | disabled
Adguard filters: | 2, 3, 4, 5, 14, 15
Ticket ID: | 1310381

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce in Chrome.

**Comment by Alex-302** [comment]
@veronikasav that's because of TDI driver.

**Comment by altokarev** [comment]
@veronikasav  You can offer to try the latest beta and WFP driver.

**Comment by ypetruk** [comment]
@altokarev  the user told that it didn`t help
what should we suggest next?

**Comment by altokarev** [comment]
@Alex-302 It reproduced at our side even in Chrome, but only email-like ad ("Another banner was right here" in the screenshot above). Btw a user complains about ads in the Edge. Maybe should check there?
