### ISSUE TITLE
songmeanings.com - Site gets stuck in spinning wheel

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6390]
http://songmeanings.com/m/songs/view/3530822107858772489/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29532455-ec35cbba-86b5-11e7-9661-8b65c0a40da2.png)

</details>

***System configuration***

Application version: 1.3.0.100
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.59 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.62 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.75 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.35 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.86.76 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.17 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.53 Enabled=YES

Ticket ID: | 1574318

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce with the same filters on iOS 10.

**Comment by danidoedel** [comment]
Same here on iOS 11. Spyware filter seems to cause this issue.

**Comment by zebrum** [comment]
@danidoedel try to update Adguard to 1.3.1 
I can not reproduce the issue now not on iOS 10, nor iOS 11
