### ISSUE TITLE
Ad Guard doesn't work properly on Google News App

### ISSUE THREAD

**Issue by alenin99** [AdguardTeam/AdguardFilters#63910]
So on the Google News app, there's full of adds when you open the website, if I open the same link on a browser, it blocks, but it doesn't block in the app. I turned on the Https filtering, that has reduced a significant amount, but it still is not as good as opening the link in the browser. Sometimes instead of removing the add space, it shows an error in ad space. Also sometimes the link doesn't even load from the app.

**Comment by BlazDT** [comment]
The app does not trust user certificates.
