### ISSUE TITLE
uptobox update rules

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [AdguardTeam/AdguardFilters#63914]
uptobox , uptostream rules update for pop-up website , and ads media bitcoins

uptobox.com##a[href*="https://arwa.app/o/uptostream"]
uptostream.com##a[href*="b-w-charms-and-gems.fr"]
||uptostream.com/assets/coins.php^$important

**Comment by Alex-302** [comment]
URLs +  screenshots, please.
