### ISSUE TITLE
trustedreviews.com

### ISSUE THREAD

**Issue by GigabitEthernet** [AdguardTeam/AdguardFilters#6391]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Whitespace is visible at the top of the page.

<img width="1440" alt="screen shot 2017-08-21 at 19 22 49" src="https://user-images.githubusercontent.com/4457688/29532683-2738fcb0-86a6-11e7-9a51-0a242fd59d7c.png">
</details>

* **Expected behaviour**: 

Whitespace should not be shown.

</details>

***Steps to reproduce the problem***:

Open trustedreviews.com, whitespace will be visible at the top of the page.

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Safari 10.1.2
Adguard version: | 2.6.7
Adguard driver (Windows): | N/A
Adguard mode (Android): | N/A
Filtering quality (Android): | N/A
HTTPS filtering (Android): |  N/A
Simplified filters(iOS) | N/A
Adguard DNS: | None
Stealth mode options(Windows) | N/A
Adguard filters: | English filter, Safari filter
Ticket ID (if exists): | N/A

**Comment by AdamWr** [comment]
Added to English filter:
`trustedreviews.com#$#body.has-adverts > #wrapper { padding-top: 0px!important; }`
`trustedreviews.com#$#body.has-adverts > .header-advert { display: none!important; }`
