### ISSUE TITLE
bildungsspender.de - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6392]
***Site***: https://www.bildungsspender.de/bildungsspender/shopping?shop=4f055b00f537dad976c5c4c34c3745ad&org_id=999999999&from_topshops=1 -> https://www.bildungsspender.de/bildungsspender/werbeblocker
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29537974-0a0d48e4-86c4-11e7-8c4e-dd37ec0be390.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
