### ISSUE TITLE
Korben.info

### ISSUE THREAD

**Issue by Kcchouette** [AdguardTeam/AdguardFilters#63960]
## Issue URL (Ads)

https://korben.info/
https://korben.info/slate-flickr-ipfs-filecoin.html

## Comment

Username: @kcchouette

You can use filter below:
```
korben.info##article>div:has-text(/Article sponsorisé/)
korben.info##div.page-divider:has-text(/Article sponsorisé/)
```

**Comment by Alex-302** [comment]
Fixed.
