### ISSUE TITLE
0calc.com, 0rechner.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#63972]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Cookie banner on `https://web2.0rechner.de/` and anti adblock on `https://web2.0calc.com/` (use the calculator to get the anti adblock overlay). When the user decline cookies ads appear
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="572" alt="ai" src="https://user-images.githubusercontent.com/48647394/93291278-e7b09380-f7e2-11ea-8d4d-e9ee43b942e3.PNG">

<img width="716" alt="pic54" src="https://user-images.githubusercontent.com/48647394/93291296-f008ce80-f7e2-11ea-8c28-7586b84120d3.PNG">

</details><br/>

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.12
Filters enabled:                       | default + Adguard Germany + Adguard Tracking Protetion + Adguard Annoyances
AdGuard DNS:                           | None

**Comment by JobcenterTycoon** [comment]
Cookie banner is back again

<img width="634" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/104445682-b29e2d00-5599-11eb-9041-fb6de82936e3.PNG">

**Comment by BlazDT** [comment]
Not showing here. Please check @AdamWr

**Comment by AdamWr** [comment]
I can't reproduce it (it's hidden by AdGuard on my end).
Maybe try to update filters or clear website data.

**Comment by JobcenterTycoon** [comment]
i did but the cookie banner still appears after 5 seconds. The site use the class `.modal-content`

**Comment by AdamWr** [comment]
Okay, so it's loaded after few seconds, I can reproduce it.
Could you please check this rule:
`||web2.0rechner.de/cmp/alternative/dialog`

**Comment by JobcenterTycoon** [comment]
This filter works. Same is needed for `web2.0calc.com`

**Comment by AdamWr** [comment]
Added:
```
0calc.com,0rechner.de###cmploadingnotify
/cmp/alternative/dialog$domain=0calc.com|0rechner.de
```
Thank you for your reply.
