### ISSUE TITLE
compare.techtudo.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#63999]
[https://compare.techtudo.com.br/produto/camera-digital-canon-preto-24-2mp-eos-80d-18-55mm-569862](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://compare.techtudo.com.br/produto/camera-digital-canon-preto-24-2mp-eos-80d-18-55mm-569862)

![celular](https://user-images.githubusercontent.com/35470489/93334843-f0fa2a00-f7fb-11ea-829f-335be0acbf4f.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
I see the banner with the link to coupons page only(cannot find another way to open that page).
