### ISSUE TITLE
aptoide.com

### ISSUE THREAD

**Issue by RedDragonWebDesign** [AdguardTeam/AdguardFilters#64002]
***Description***:

AdGuard Annoyances list blocks a cookie modal with filter `aptoide.com##div[class^="cookie-notice_"]`, but does not fix the disabled y scroll bar.

https://blokada-dns.en.aptoide.com/app

***Suggested Fix***:

Add this filter to AdGuard Annoyances list:

`aptoide.com##html:style(overflow: auto !important;)`

***Original Reddit Thread***

https://www.reddit.com/r/uBlockOrigin/comments/i24wjz/ubo_blocks_modal_windows_and_leaves_sites_without/g5gm1bu/

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
Thank you.
