### ISSUE TITLE
vse.fm

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6400]
Архив вечно грузится теперь
Либо есть невидимая плашка "отключите адблок", либо невидимый рекламный блок не исчезает и не запускает запись
Работает только в режиме инкогнито без расширений
Прямой эфир работает его никогда не трогали

Английский фильтр Версия 1.1.28.59.
Русский фильтр Версия 1.0.55.72.

https://vse.fm/station_66 пример

**Comment by Alex-302** [comment]
У меня оно и без блокировщика висит.
