### ISSUE TITLE
mobile.donanimhaber.com - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6401]
https://mobile.donanimhaber.com/forumid_462/p_2/tt.htm

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29552123-a2d66cf4-871e-11e7-94ba-163c501d4f8a.png)

</details>

***System configuration***

Application version: 1.3.0.81
Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.26.35 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.97 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.29 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.12 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.8.84 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.38 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.56 Enabled=YES
ID=101 Name="EasyList" Version=1.0.74.93 Enabled=YES

Ticket ID: 1454552

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce.
`ID=101 Name="EasyList" Version=1.0.74.93 Enabled=YES`
this filter is unnecessary when Eng filter is enabled.

@AdamWr please check on your device.

**Comment by AdamWr** [comment]
Ok, I can reproduce.
Added to Mobile filter:
`mobile.donanimhaber.com##.reklamiatla`
