### ISSUE TITLE
tutknow.ru - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6402]
http://tutknow.ru/cookery/second_dishes/7360-grechka-v-mikrovolnovke.html

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29557992-730f3a22-8733-11e7-89f8-dfbec211f830.png)

</details>

***System configuration***

Application version: 1.3.0.81
Device: iPad
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.28.30 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.93 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.25 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.55.59 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.55 Enabled=YES
Mobile ads
Annoyances

Ticket ID: 1464479

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Partially fixed. The most of ads has code like useful elements.
