### ISSUE TITLE
Блокировка лишнего элемента

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#64032]
Здравствуйте!
Какое пользовательское правило нужно добавить для блокировки данного элемента?
Заранее спасибо за ответ!
![Screenshot_20200917-002804](https://user-images.githubusercontent.com/71411107/93396773-dae27d00-f880-11ea-9331-1dd50af9e95d.jpg)

**Comment by Alex-302** [comment]
Нужен адрес страницы.
