### ISSUE TITLE
wallpapersite.com - Anti adblock 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6404]
https://wallpapersite.com/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29562981-5120d1ee-8744-11e7-896a-517663250ce1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1
Adguard driver (Windows): | WFP 
Adguard filters: |  2 3 4 14
Ticket ID: | 1456343 

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
