### ISSUE TITLE
onetwotrip.com - does not show widget

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6406]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: "partner.onetwotrip.com это сервис по генерации собственных виджетов по
поиску авиабилетов, жд билет и отелей. вставляются на сайт пользователей посредствам скрипта или iframe. У пользователей с установленной вашей программой, наши виджеты не загружаются."

[Filter page on GitHub](https://github.com/AdguardTeam/AdguardFilters/blob/476369b4eb83674bcb215071480d46c5ee039769/RussianFilter/sections/specific.txt)

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![677ba8f63f](https://user-images.githubusercontent.com/30041399/29566085-30873380-8751-11e7-81d2-f21cb482f969.png)

</details>

***Pages containing widget***:
[https://xn--90afebms4aw5f.xn--80aswg/](https://xn--90afebms4aw5f.xn--80aswg/)
[http://kudarf.ru/kavkaz/krasnodarskij-kraj/kak-dobratsya-do-gelendzhika-na-poezde-iz-moskvy.html](http://kudarf.ru/kavkaz/krasnodarskij-kraj/kak-dobratsya-do-gelendzhika-na-poezde-iz-moskvy.html)

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Ticket ID: 1616117

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
