### ISSUE TITLE
duplichecker.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#64060]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Many ad pictures
`https://www.duplichecker.com/domain-age-checker.php`

* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="913" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/93449477-173fc880-f8d5-11ea-9fcd-ea99018ade24.PNG">

</details><br/>

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.12
Filters enabled:                       | default + Adguard Germany + Adguard Tracking Protetion + Adguard Annoyances
AdGuard DNS:                           | None 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Top left-over has some strange class name like it could have useful content in some cases, therefore did not remove left-over yet.

**Comment by JobcenterTycoon** [comment]
Ads are back

**Comment by JobcenterTycoon** [comment]
Ads are back

**Comment by BlazDT** [comment]
Not seeing any. Please check @AdguardTeam/filters-maintainers

**Comment by JobcenterTycoon** [comment]
They use `spannn` now insead of `spann` thats why the old filter doesn’t work

**Comment by zloyden** [comment]
Fixed, update should be available in 1-2 hours.
@JobcenterTycoon please don't bring up old topics.
