### ISSUE TITLE
forum.kitz.co.uk

### ISSUE THREAD

**Issue by GigabitEthernet** [AdguardTeam/AdguardFilters#6407]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

Ad is shown at the top of the page but not on every refresh. A few refreshes and you will see an ad. PayPal donate button is also visible.

<img width="1039" alt="screen shot 2017-08-22 at 14 03 32" src="https://user-images.githubusercontent.com/4457688/29566750-cc5ec17e-8742-11e7-9272-4b27678f23ae.png">
</details>

* **Expected behaviour**: 

Ad should never be shown and neither should PayPal donate button.

</details>

***Steps to reproduce the problem***:

Go to forum.kitz.co.uk, if ad isn't shown, make sure window is fullscreen and refresh page until ad is shown. PayPal button is always visible.

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Safari 10.1.2
Adguard version: | 2.6.7
Adguard DNS: | None
Adguard filters: | English filter, Safari filter

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

Adguard filter |
--- |
English filter |
Safari filter |

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Nothing.
Please save the page and upload it.

**Comment by GigabitEthernet** [comment]
[Kitz Forum - Index.zip](https://github.com/AdguardTeam/AdguardFilters/files/1242175/Kitz.Forum.-.Index.zip)

**Comment by Alex-302** [comment]
Can't open it. Save as HTML+resources.

**Comment by GigabitEthernet** [comment]
@Alex-302 In Safari I only have the option of Web Archive or Page Source. It only affects the Safari browser.

**Comment by Alex-302** [comment]
That banner must be blocked by the rule from English filter
```
||kitz.co.uk/files/jump2/
```
Please check it in user filter.

**Comment by GigabitEthernet** [comment]
@Alex-302 Adding that rule to the user filter blocks the ad yes.

**Comment by Alex-302** [comment]
Ok, added with special mark.
Please check it tomorrow after removing the rule from user filter.

**Comment by GigabitEthernet** [comment]
@Alex-302 The ad is still showing up today.

**Comment by Alex-302** [comment]
I don't know why that rule is absent in the filters on your device.
Please ask in https://github.com/AdguardTeam/AdguardForiOS/issues

**Comment by GigabitEthernet** [comment]
I'm on Safari on a Mac, not iOS.

**Comment by Alex-302** [comment]
Then https://github.com/AdguardTeam/AdguardBrowserExtension/issues/new

**Comment by GigabitEthernet** [comment]
@Alex-302 It's not showing up anymore which is odd but issue seems to be resolved. Many thanks.
