### ISSUE TITLE
Missed audio ads on vk.com

### ISSUE THREAD

**Issue by DOOMGABR** [AdguardTeam/AdguardFilters#64076]
### Steps to reproduce

1. Войти на сайт https://vk.com/
2. Перейти в раздел "Музыка"
3. Включить любую дорожку и прослушать её до конца, не перематывая
4. Затем активируется аудио-реклама

### Expected behavior
Аудио-реклама на сайте VK.COM ранее блокировалась

### Actual behavior
На данный момент аудио-реклама на сайте VK.COM не блокируется

<details><summary>
Screenshot:
![image](https://user-images.githubusercontent.com/25430999/93388250-1a09d180-f873-11ea-977d-c1e8b5eb0620.png)

</summary>

![image](https://user-images.githubusercontent.com/25430999/93369138-9a223e00-f857-11ea-8179-f98ffa4798b7.png)

</details>

### Your environment

* Environment name and version: **Chrome 85.0.4183.102**
* Operating system and version: 
![image](https://user-images.githubusercontent.com/25430999/93369372-f8e7b780-f857-11ea-9de0-d6b23bc64dd5.png)

**Comment by Chinaski1** [comment]
Добрый день!

Для начала вам следует обновить фильтры вручную, очистить кэш браузера и попробовать повторить проблему в режиме инконито.
Если реклама все еще воспроизводится, тогда желательно отправить отчет разработчикам фильтров.
Возможно проблема кроется в использовании сторонних фильтров или расширений.
Отправить жалобу можно используя [помощник AdGuard](https://uploads.adguard.com/Chinaskihchne.png), или по [прямой ссылке.](agrd.io/report)

**Comment by DOOMGABR** [comment]
Фильтры обновлены
Кэш — чист
В режиме "Инкогнито" всё работает. Неужели из-за расширений?
P.S.: И да, смысл тогда создавать Issues если есть техподдержка?

**Comment by Alex-302** [comment]
> P.S.: И да, смысл тогда создавать Issues если есть техподдержка?

Отправив отчёт из Адгарда сэкономите время, т.к. вся нужная информация добавится автоматически. Вручную добавить нужно лишь скриншот(ы) и адрес страницы/приложения.

**Comment by zloyden** [comment]
Не наблюдаю аудио рекламы.


> В режиме "Инкогнито" всё работает. Неужели из-за расширений?

Это вполне возможно. Как говорили @Chinaski1 @Alex-302, лучше отправьте репорт через [помощник AdGuard](https://uploads.adguard.com/Chinaskihchne.png) или по [прямой ссылке](https://reports.adguard.com/ru/new_issue.html), если реклама все еще повторяется.
