### ISSUE TITLE
palemoon.org - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6408]
***Site***: http://www.palemoon.org/
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29575082-bec2655e-8763-11e7-8ef7-a11eec327007.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.

**Comment by XX-J** [comment]
На https://addons.palemoon.org/ сообщение антиадблока всё равно видно. И лучше его блокировать не исключением `@@||palemoon.org/*ads.js` (которое подходит и под главную страницу), а блокировкой скрипта, отвечающего за показ сообщения:

`||palemoon.org/*/abfunctions.js` - для addons.palemoon.org
`||palemoon.org/pagefunctions.js` - для palemoon.org (вместо `@@||palemoon.org/ads.js`)

<details><summary>Screenshot:</summary>

![palemoon org](https://user-images.githubusercontent.com/17948007/36414654-14826e12-1634-11e8-8ef3-f758449a3f21.png)
</details>

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.8.5 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики
