### ISSUE TITLE
haaretz.com - Social widget - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6409]
***Site***: http://www.haaretz.com/israel-news/1.808335
***Description***: Social share icons. Newsletter sign up. Huge newsletter sign up at the bottom after I reloaded the page a few times. Overlay after hovering over the chrome address bar. Annoying share bar on mobile. 

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29575540-19b737fe-8765-11e7-94a1-d041496c1363.png)

![image](https://user-images.githubusercontent.com/10995998/29575564-27b4d69a-8765-11e7-8741-2f1f9af36d37.png)

![image](https://user-images.githubusercontent.com/10995998/29575650-748577e0-8765-11e7-8781-760ea4548967.png)

![image](https://user-images.githubusercontent.com/10995998/29575684-94766924-8765-11e7-8bcc-8379cabf1f10.png)

![image](https://user-images.githubusercontent.com/10995998/29575604-4a2d4d7e-8765-11e7-9d39-7ebd1af98f43.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
