### ISSUE TITLE
Блокировка лишнего элемента (с ссылкой)

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#64104]
Здравствуйте!
Какое пользовательское правило нужно добавить для блокировки данного элемента?
Заранее спасибо за ответ!

Ссылка (вернее ссылки), запрошенная вами в этом issue:
https://github.com/AdguardTeam/AdguardFilters/issues/64032
Сами ссылки:
https://passport.yandex.ua
https://passport.yandex.ru
https://passport.yandex.com

На всех вышеперечисленных ссылках хотелось бы блокнуть эту бяку (скрин ниже)

Платформы:
Приложение под андроид и расширение адгуард.

Заранее спасибо за помощь!

![93396773-dae27d00-f880-11ea-9331-1dd50af9e95d](https://user-images.githubusercontent.com/71467644/93525622-0330b100-f93f-11ea-94e9-9a3a520cbdc8.jpg)

**Comment by stanislav-atr** [comment]
Добрый день!
Попробуйте `passport.yandex.ua,passport.yandex.ru,passport.yandex.com##.AuthSocialBlock` .

**Comment by ghost1295** [comment]
@stanislav-atr
> Добрый день!
> Попробуйте `passport.yandex.ua,passport.yandex.ru,passport.yandex.com##.AuthSocialBlock` .

Большое спасибо! Помогло!
