### ISSUE TITLE
tampermonkey.net - Annoyance - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6410]
***Site***: http://tampermonkey.net/
***Description***: Cookie notice at the top and ads.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29575923-4f03eb36-8766-11e7-897b-8ca20212086d.png)

![image](https://user-images.githubusercontent.com/10995998/29575928-577b3f6c-8766-11e7-8e27-d364d86fbfca.png)

![image](https://user-images.githubusercontent.com/10995998/29575932-5ede05aa-8766-11e7-8b2f-d63175cfbe3f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS 11
Browser: | Safari
Adguard version: | 1.3.1(106)
Simplified filters(iOS) | Off
Adguard DNS: | None

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
Mobile ads filter
Safari filter

**Comment by AdamWr** [comment]
Fixed.
