### ISSUE TITLE
Конфликт с Cloudflare

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#64139]
Здравствуйте!
При включённом Адгуард невозможно попасть на страницу. Станица либо циклически перезагружается, стопорясь на этом моменте **(скрин и техническая информация ниже)**, либо выскакивает капча и ПОСЛЕ прохождения онной страница снова перезагружается и всё по новой. Adguard отключал, когда он выключен проблем не наблюдается. Проблемная ссылка: https://www.iphones.ru/iNotes/kak-facebook-google-i-melkie-kompanii-sledyat-za-vami-cherez-prilozheniya-07-22-2020

Аналогичная проблема наблюдается не только на этой ссылке но и на любых других (почти на всех, за исключением некоторых) сайтах с Cloudflare. Вот список сайтов на которых наблюдается аналогичная проблема:
https://apps.evozi.com/apk-downloader/
https://tempail.com/ru/
https://www.crazymailing.com/ru/
https://temp-mail.io/
https://apkpure.com/
И так далее.

![Screenshot_20200918-125054](https://user-images.githubusercontent.com/71494627/93584718-5d1c8f80-f9ae-11ea-9f86-077ad4e37ca8.jpg)

**Платформа:** Андроид 7
**Прокси:** Включён. Интеграция с Orbot.
**Версия:** AdGuard for Android v3.4 (120)
**Фильтры:**
**Ad Blocking:**
AdGuard Base,
AdGuard Mobile Ads,
EasyList,
Peter Lowe's Blocklist
**Privacy:**
AdGuard Tracking Protection,
EasyPrivacy,
Fanboy's Enhanced Tracking List,
Fanboy Anti-Facebook List,
Fanboy's Anti-thirdparty Fonts
**Social Widgets:**
AdGuard Social Media,
Fanboy's Social Blocking List
**Annoyances:**
AdGuard Annoyances,
Fanboy's Annoyances,
Web Annoyances Ultralist,
Adblock Warning Removal List,
I don't care about cookies,
EasyList Cookie List
**Security:**
Online Malicious URL Blocklist,
Spam404,
NoCoin Filter List
**Language-specific:**
AdGuard Russian,
RU AdList,
RU AdList: Counters,
RU AdList: BitBlock

**Антитрекинг:**
Hide your search queries,
Send Do-Not-Track header,
Strip URLs from tracking parameters,
Self-destructing first-party cookies (4320),
Self-destructing third-party cookies (0),
Block WebRTC,
Hide your Referrer from third-parties

**Браузер:**
Яндекс

**Comment by Alex-302** [comment]
Ни один сайт капчу не выдал. Что ломает - фильтры или антитрекинг?
