### ISSUE TITLE
Пользовательский фильтр

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#64138]
Здравствуйте!
Есть ли способ заблокировать элемент на который указывает ссылка на скриншоте (ниже)? Если да, то какое пользовательское правило я должен добавить?
![Screenshot_20200918-123829](https://user-images.githubusercontent.com/71494627/93583380-73295080-f9ac-11ea-918c-58fd4a608232.jpg)

//////////////
Так же я хочу начать составлять фильтры, но я уже перерыл весь Яндекс и перегуглил весь гугл, но нормальной и расширенной информации по составлению правил для скрытия элементов не нашёл. Н. Эту статью изучил https://kb.adguard.com/ru/general/how-to-create-your-own-ad-filters но правила скрытия элементов, указанные в ней не всегда подходят под мои задачи. Может быть у кого-нибудь будет ссылка на подробную статью которая поможет мне со скрытием объектов с веб страницы? Буду премного благодарен.

**Comment by ghost1295** [comment]
>Так же я хочу начать составлять фильтры, но я уже перерыл весь Яндекс и перегуглил весь гугл, но нормальной и расширенной информации по составлению правил для скрытия элементов не нашёл. Н. Эту статью изучил https://kb.adguard.com/ru/general/how-to-create-your-own-ad-filters но правила скрытия элементов, указанные в ней не всегда подходят под мои задачи. Может быть у кого-нибудь будет ссылка на подробную статью которая поможет мне со скрытием объектов с веб страницы? Буду премного благодарен.
Если что, то это только для моих личных целей. Я не буду использовать эту информацию в коммерческих целях 🤗.

Просто чтоб не мучить постоянно техподдержку, хотелось бы научиться простые правила составлять самостоятельно, а то на сайтах имеется такая тенденция, что уйма левых элементов, какие не являются рекламой (и поэтому не числятся в общих правилах), но мешают либо раздражают...

**Comment by krystian3w** [comment]
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters - good luck!
