### ISSUE TITLE
bank-codes.com - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6414]
***Site***: https://www.bank-codes.com/
***Description***: Ads.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29576685-0aea30f6-8769-11e7-85cb-e2f4f460b556.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
