### ISSUE TITLE
gpro.net - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6416]
***Site***: https://www.gpro.net/it/forum/index.asp
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29587464-63242dce-878e-11e7-9ded-0adb684b2867.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr It's back again.

**Comment by AdamWr** [comment]
This notice should be hidden by cosmetic rule, but it seems that for some reason HTTPS filtering doesn't work on this website.

@danidoedel could you please check, if you go to http version of this website, do you still see this anti adblock notice? - http://www.gpro.net/it/forum/index.asp

**Comment by danidoedel** [comment]
@AdamWr Yep that's true. No detection on HTTP site, but on HTTPS :(

**Comment by AdamWr** [comment]
@danidoedel thank you for checking it, reported here - https://github.com/AdguardTeam/AdguardForWindows/issues/1902
