### ISSUE TITLE
rus-linux.net - pop ups - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6417]
***Description***:
* **Current behaviour**: 

There are pop-ups on rus-linux.net on Android
reproduced on our side!

<details><summary>Screenshot:</summary>

![18322632](https://user-images.githubusercontent.com/28784344/29588409-12c463a6-879a-11e7-8163-b3cc2f77dfbd.png)

</details>

<details><summary>Screenshot:</summary>

![18322650](https://user-images.githubusercontent.com/28784344/29588419-1d39f706-879a-11e7-96aa-a65c22a07a7c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android
Browser: | Chrome
Adguard version: | 2.9.136
Adguard mode (Android): | VPN 
Filtering quality (Android): | high-speed 
HTTPS filtering (Android): |  On (Default) 
Adguard DNS: | None
Adguard filters: |  2, 3, 4, 14, 1, 11
Ticket ID (if exists): | 1616249

**Comment by Alex-302** [comment]
Fixed
