### ISSUE TITLE
Realm667.com - Page won't load properly (AdGuard Annoyances filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#64179]
### Affected site:
`https://www.realm667.com/`

### Issue:
The page won't load properly, because of a blocked cookie consent, which needs to be accepted!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **AdGuard Annoyances filter**

### Problem rule:
`###redim-cookiehint:not(body):not(html)`

### Possible fix:
`realm667.com#@##redim-cookiehint:not(body):not(html)`

### Note:
In some browsers, the page first appears to work without whitelisting the cookie consent.
But if you simply refresh the page, it will break right away!

### Other problem filters:
* **EasyList Cookie List** / **Fanboy's Annoyance List** https://github.com/ryanbr/fanboy-adblock/issues/1409/
`##.cookiecontent`
`###redim-cookiehint`

* ~~**Frellwit's Swedish Filter** https://github.com/lassekongo83/Frellwits-filter-lists/issues/88/~~ _(FIXED)_
~~`###redim-cookiehint`~~

* **I don't care about cookies** _(NOTIFIED)_
`###redim-cookiehint`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.13.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.25 (XUL)

**Comment by krystian3w** [comment]
Recommend test with PaleMoon and Chromium.

Let's not close that the bug is not playable in Firefox or Safari (iOS/iPadOS/macOS)
