### ISSUE TITLE
 https://audioknigi.club - Anti AdBlock script - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6419]
***Description***:
* **Current behaviour**: 

 https://audioknigi.club - anti AdBlock Script on Windows

reproduced on our side (Mac OS)

<details><summary>Screenshot:</summary>

![screen shot 2017-08-23 at 1 09 15 am](https://user-images.githubusercontent.com/28784344/29589938-28bf0eb2-87a0-11e7-88d8-1ec8eaa963c3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1.
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1616463

**Comment by Alex-302** [comment]
Fixed
