### ISSUE TITLE
https://matchtv.ru/on-air - Anti AdBlock script - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6420]
***Description***:
* **Current behaviour**: 

https://matchtv.ru/on-air - anti AdBlock Script on Windows
reproduced on our side (Mac OS)

<details><summary>Screenshot:</summary>

![default](https://user-images.githubusercontent.com/28784344/29591631-4bb04ff0-87a8-11e7-8999-b06349411a9a.jpg)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1.
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1397622

**Comment by Alex-302** [comment]
fixed
