### ISSUE TITLE
heraldscotland.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6421]
***Site***: http://www.heraldscotland.com/
***Description***: Cookie notice at the bottom. Newsletter sign up stuff.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29592612-76f873c0-87a5-11e7-9785-67b722225795.png)

![image](https://user-images.githubusercontent.com/10995998/29592576-4be752a0-87a5-11e7-833e-4ff2478ee08d.png)

**http://www.heraldscotland.com/news/15488815.Private_schools_attack_moves_to_make_them_pay___5m_in_business_rates/:**

![image](https://user-images.githubusercontent.com/10995998/29592589-5d72eac0-87a5-11e7-921a-e3fb0a12da66.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
