### ISSUE TITLE
nordiskradio.se

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#64215]
[https://nordiskradio.se/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://nordiskradio.se/)

Cookie overlay:

![cookie](https://user-images.githubusercontent.com/35470489/93667601-a1b33400-fa5d-11ea-8074-68a5aa439008.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by THEtomaso** [comment]
@lassekongo83:
`nordiskradio.se###cookieWindow`
