### ISSUE TITLE
zo.ee - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6422]
***Site***: http://zo.ee/3IV
***Description***: Adblock detection (adf.ly like site)

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29592656-c0bcc7a4-87a5-11e7-9759-49d5521d81d0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr It's back again / not working.

**Comment by AdamWr** [comment]
Thank you for checking it.
It should be fixed now.
