### ISSUE TITLE
Youtube gets blocked by AdGuard Annoyances filter

### ISSUE THREAD

**Issue by RiccardoP** [AdguardTeam/AdguardFilters#64226]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: 
* **Current behaviour**: 

When the Annoyances filter is active on uBlock Origin Youtube does not load and I get a blank page.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Youtube homepage:</summary>

![image](https://i.imgur.com/iwHtVJq.png)
</details><br/>

<details><summary>Content blocked by AdGuard:</summary>

![image](https://user-images.githubusercontent.com/11669324/93670799-47869300-fa9e-11ea-971f-b5048dcb9d2b.png)

</details><br/>

* **Expected behaviour**: 

I noticed the problem for the first time today. Usually I can normally use Youtube without ads.

***Steps to reproduce the problem***:

Just activating the AdGuard Annoyances filter generates the problem.

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Chrome 85.0.4183.102

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Cannot reproduce.

Please try to add these rules one by one:
youtube.com#@%#//scriptlet('set-constant', 'playerResponse.adPlacements', 'undefined')
`youtube.com#@%#//scriptlet('set-constant', 'ytInitialPlayerResponse.adPlacements', 'undefined')`

**Comment by ToadKing** [comment]
Do you happen to have BlockTube installed as well? I'm noticing when the AdGuard filter is enabled it's messing with its injected script somehow and causing an error in the dev console.

**Comment by RiccardoP** [comment]
> Do you happen to have BlockTube installed as well? I'm noticing when the AdGuard filter is enabled it's messing with its injected script somehow and causing an error in the dev console.

That seems to be the problem: I uninstalled BlockTube and now I can leave the filter active.
I had the extension installed for quite some time but the problem only appeared yesterday. Maybe one of the extensions or Chrome itself updated and broke something.

**Comment by Alex-302** [comment]
some rules was removed
