### ISSUE TITLE
iptvultra.com - Social Widget - Ad leftover - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6424]
***Site***: http://www.iptvultra.com/2016/11/canada-iptv-list-54-channels-19-11-2016.html
***Description***: Facebook overlay leftover. Adblock detection (blocks download buttons). Ad leftovers. Share button.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29592743-515aec28-87a6-11e7-81f2-6444aa5a4998.png)

![image](https://user-images.githubusercontent.com/10995998/29592846-de3f2410-87a6-11e7-8548-b7b095ab0da2.png)

![image](https://user-images.githubusercontent.com/10995998/29592776-8898d812-87a6-11e7-8fa3-344ae99ad002.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
