### ISSUE TITLE
https://games.mail.ru/pc/games/balda/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6426]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: 
* **Current behaviour**: See the screenshots

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29601458-52411868-87e4-11e7-875f-cde22d822a9d.png)

![image](https://user-images.githubusercontent.com/15856304/29601600-06fbf28c-87e5-11e7-8fda-1da3a275c80f.png)
</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

1. Visit mail.ru
2. Head to minigames section
3. Search for a game, say, балда
4. See an ad, screenshot 1
5. Start playing
6. See other banners (the 2d picture)

***System configuration***

Information | value
--- | ---
Operating system: | Windows NT 10.0.15063.0
Browser: | FF
Adguard version: |  6.1.331.1732
Adguard driver (Windows): | TDI
Adguard DNS: | None
Stealth mode options(Windows) | 
Adguard filters: | 1 2 6
Ticket ID (if exists): | 631188

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Partially fixed. Don't close it.

**Comment by ypetruk** [comment]
комментарий (Ticket ID:631188)
Проблема не только в Mozilla Firefox ,но и  Опере, а также и в Win 10 и в Win.7

**Comment by ypetruk** [comment]
Ticket ID: 1139388
<details><summary>Screenshot:</summary>

![2017-08-20_13-17-14](https://user-images.githubusercontent.com/28784344/29629820-d03e71b2-8842-11e7-99b0-314d7f342b3e.png)

</details>

**Comment by darkulish** [comment]
problem remains 

![](https://qcrm.supportyourapp.com/message/attachment/1513025/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20(26).png)

**Comment by Alex-302** [comment]
Не тот домен, к тому же дубль.
