### ISSUE TITLE
Can‘t access Linksnappy

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardFilters#64277]
I can't access linksnappy.com with AdGuard DNS (no family protection) enabled on iOS and MacOS. It works fine as soon as I disable it.

Screen recording: https://we.tl/t-Oi8WcUbM8z

**Comment by Alex-302** [comment]
It is blocked as analytics. Where is it used?

**Comment by iDjay** [comment]
Mac:
macOS 10.15.6 
Safari 14.0
AdGuard DNS settings

iPhone:
iOS 14.0
AdGuard 4.0.3 beta
AdGuard DNS over HTTPS Full Tunnel.

Or what do you exactly mean?

**Comment by Alex-302** [comment]
I am asking about linksnappy.com
How/where is it used?

**Comment by iDjay** [comment]
It's a premium link file Generator for file Hosters like uploaded, rapidgator etc. but it also lets you download files from YouTube oder SoundCloud f.e. Or what do you mean?

**Comment by iDjay** [comment]
This is what's happening after changing my DNS settings on Mac to the ones from AdGuard DNS:

<img width="1552" alt="Bildschirmfoto 2020-09-22 um 10 59 01" src="https://user-images.githubusercontent.com/4127356/93862698-b9d7bd00-fcc2-11ea-82db-d152cfe5d262.png">

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #455](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/455) via [**ZenHub**](https://www.zenhub.com/)
