### ISSUE TITLE
https://www.testufo.com/#test

### ISSUE THREAD

**Issue by Alexey71** [AdguardTeam/AdguardFilters#6428]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)
Блокируются все тесты. Если выключить гвард, нормально
[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![2017-08-23 11_32_50](https://user-images.githubusercontent.com/10572914/29606532-3df51c16-87f7-11e7-95ce-d65f4be6470b.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![2017-08-23 11_31_59](https://user-images.githubusercontent.com/10572914/29606539-43ab001c-87f7-11e7-9b71-efe8c6243f4c.png)

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)
Открыть сайт и выбирать любой тест
***System configuration***

Information | value
--- | ---
Operating system: | Windows / Mac OS / Android / Linux
Browser: | Firefox 56
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP / TDI
Adguard DNS: | None 
Stealth mode options(Windows) | None

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)
Английский 
Русский
Эксперементальный
Раздражители
Соц сети
Счетчики и система аналитики
[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||testufo.com/*.html$jsinject,elemhide,extension
```
