### ISSUE TITLE
eurogamer.net - AdGuard Annoyances exception filter #@# is protecting a cookie modal

### ISSUE THREAD

**Issue by RedDragonWebDesign** [AdguardTeam/AdguardFilters#64284]
I went to write a cookie filter for this page.

https://www.eurogamer.net/articles/2020-02-07-blizzard-begins-warcraft-3-reforgeds-road-to-recovery-with-2gb-patch

I wrote this filter

`eurogamer.net###onetrust-consent-sdk`

The filter I wrote didn't work. The following AdGuard Annoyances exception filter is overriding my filter.

````
! https://github.com/AdguardTeam/AdguardFilters/issues/56372
@@||cdn.cookielaw.org^$domain=comicbook.com|metabomb.net|usgamer.net|eurogamer.net|eurogamer.it|eurogamer.pl|eurogamer.pt|rtlnieuws.nl
metabomb.net,usgamer.net,eurogamer.it,eurogamer.net,eurogamer.pl,eurogamer.pt,rtlnieuws.nl#@##onetrust-consent-sdk
````

Related #56372. I guess this exception filter was originally written to fix a video player? Strange that a video player is included in a "consent SDK". Consent makes it sound like it's purely used for cookie notices.

If you keep the exception filter for `#onetrust-consent-sdk`, and want to block the cookie notice, it has 2 children that need to be blocked: `.onetrust-pc-dark-filter` and `#onetrust-banner-sdk`

Thanks for your help

**Comment by krystian3w** [comment]
> If you keep the exception filter for `#onetrust-consent-sdk`, and want to block the cookie notice, it has 2 children that need to be blocked: `.onetrust-pc-dark-filter` and `#onetrust-banner-sdk`

Another workarounds:

`eurogamer.net###onetrust-consent-sdk#onetrust-consent-sdk`

`eurogamer.net###onetrust-consent-sdk[id]`

`eurogamer.net##[id="onetrust-consent-sdk"]`

`eurogamer.net##div[id="onetrust-consent-sdk"]`

`eurogamer.net##body #onetrust-consent-sdk`

`eurogamer.net##body > #onetrust-consent-sdk`

**Comment by Alex-302** [comment]
@RedDragonWebDesign Hi. Cannot reproduce. Please send report from AdGuard with screenshot.

**Comment by krystian3w** [comment]
@Alex-302 try test without AdGuard script rule or with **uBlock Origin**: https://github.com/AdguardTeam/AdguardFilters/blob/978c13b7d64f5212c7056ebbcbe20f6fb2ee89d4/AnnoyancesFilter/sections/cookies_specific.txt#L4354

?

We try hide this pop-up in **uBO**. uBO no have clicker.

**Comment by RedDragonWebDesign** [comment]
Sorry, I should have mentioned I am using uBlock Origin. Here are some screenshots.

<img width="960" alt="2020-09-21_080551" src="https://user-images.githubusercontent.com/43397938/93784362-cb956380-fbe1-11ea-9029-63e9ab2f5de2.png">
<img width="960" alt="2020-09-21_080602" src="https://user-images.githubusercontent.com/43397938/93784369-cdf7bd80-fbe1-11ea-9091-54c638dbce35.png">
<img width="960" alt="2020-09-21_080608" src="https://user-images.githubusercontent.com/43397938/93784380-d05a1780-fbe1-11ea-9e64-178e62b1bf62.png">
<img width="960" alt="2020-09-21_080719" src="https://user-images.githubusercontent.com/43397938/93784393-d2bc7180-fbe1-11ea-9a02-34536fb5f2e2.png">
<img width="960" alt="2020-09-21_080729" src="https://user-images.githubusercontent.com/43397938/93784400-d5b76200-fbe1-11ea-8844-e5d93f527688.png">
<img width="201" alt="2020-09-21_080854" src="https://user-images.githubusercontent.com/43397938/93784406-d819bc00-fbe1-11ea-80ba-b2838e6bc0dd.png">

**Comment by krystian3w** [comment]
This is good exception, video section is empty without manually accept or via AdGuard js clicker rule.


`eurogamer.net/videos`

**Comment by RedDragonWebDesign** [comment]
Ok. May I suggest adding this to AdGuard Annoyances? To hopefully block the cookie modal without breaking videos.

`eurogamer.net##.onetrust-pc-dark-filter, #onetrust-banner-sdk`

**Comment by RedDragonWebDesign** [comment]
Alright, I'm comfortable recommending the above filter (`eurogamer.net##.onetrust-pc-dark-filter, #onetrust-banner-sdk`). It blocks the cookie modal.

The videos are still "blocked", in the sense that the website requires you to accept cookies before it will display them. But you can just click "Cookies Settings", then "Allow All Cookies", and that activates the videos just fine. It is not affected by the above filter.

If somebody wants to look into writing a `##+js(set, )` type filter, that could be a good workaround too.

![2020-09-21_113420](https://user-images.githubusercontent.com/43397938/93806903-bbd84800-fbfe-11ea-9196-73bb5d83b3fb.png)
![2020-09-21_113415](https://user-images.githubusercontent.com/43397938/93806910-bda20b80-fbfe-11ea-8e69-be051088aca7.png)
![2020-09-21_113459](https://user-images.githubusercontent.com/43397938/93806918-bf6bcf00-fbfe-11ea-87cf-871be2f1317e.png)

**Comment by Alex-302** [comment]
Checked. Without exclusions video is broken.
If JS rule is disabled, I see cookie notification(NL IP).
