### ISSUE TITLE
shutterdowner.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6429]
***Site***: https://www.shutterdowner.com/
***Description***: Adblock detection. Just enter any random link and mail address.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29606835-b642287e-87ef-11e7-8de5-8e30c7ea7e9e.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr They shut down the website, so I think the rules can be removed.
