### ISSUE TITLE
http://www.ok.ru/game/rules_of_war

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#643]
В игре в ОК оповещение вылезает

https://qcrm.cc/#/customer/1058936

**Comment by Alex-302** [comment]
Не пойму какое оповещение.

**Comment by vbagirov** [comment]
Всё что осталось от скриншота: http://clip2net.com/404.html?url=%2Fs%2F3kmCAe7

**Comment by Alex-302** [comment]
Если всплывает в самой игре, то ничего не сделаем. Пусть на нормальный хостинг зальёт.
