### ISSUE TITLE
bild.de

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdguardFilters#64303]
### Issue URL (Annoyance)
 
 https://www.bild.de/

 ### Comment
 
 Username: @Morku
 
 > ## Cookie Pop-up
 > Die folgenden Informationen werden automatisch generiert. Bitte löschen Sie sie nicht.
 > Custom userscripts:
 > https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
 
 ### Screenshots
<details><summary>Screenshot-1:</summary>

![bild](https://user-images.githubusercontent.com/6276915/93723257-69b30a80-fb9d-11ea-91d3-de15ed14e4a1.png)

</details><br/>

 ### System configuration
 Information 	value
 AdGuard product: 	AdGuard for Windows v7.5.1
 Browser: 	Firefox
 AdGuard driver: 	WFP
 Stealth mode options: 	Hide your search queries,
 Send Do-Not-Track header,
 Remove X-Client-Data header from HTTP requests,
 Strip URLs from tracking parameters
 Filters: 	Ad Blocking:
 AdGuard Mobile Ads,
 AdGuard Base
 
 Privacy:
 AdGuard Tracking Protection
 
 Social Widgets:
 AdGuard Social Media
 
 Annoyances:
 AdGuard Annoyances
 
 Language-specific:
 AdGuard Russian,
 AdGuard German

**Comment by Alex-302** [comment]
@BlazDT please take a look.
`||cmp2.bild.de/wrapperMessagingWithoutDetection.js` is whitelisted, but I cannot understand why.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/26aac99f8cb9665a54ee60608813385078f1bd34

**Comment by BlazDT** [comment]
Adam explained in Slack. Added JS rule to hide it.
