### ISSUE TITLE
linternaute.com - Annoyance - Ads - Ad leftover - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6433]
***Site***: http://www.linternaute.com/actualite/politique/1357555-election-presidentielle-2017-resultat-macron-lepen-2eme-tour-direct/
***Description***: Video won't load with french filter enabled. Newsletter sign up in right sidebar and after article. Ads and ad leftover after article.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29607579-eeafdad8-87f1-11e7-8d78-45064396ac10.png)

![image](https://user-images.githubusercontent.com/10995998/29607613-0dcc683c-87f2-11e7-9143-c7820fb70a81.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
French filter

**Comment by AdamWr** [comment]
Fixed.
