### ISSUE TITLE
badenertagblatt.ch (and related) - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6435]
***Site***: https://www.badenertagblatt.ch/sport/aargau/weiterhin-ohne-sieg-der-fc-aarau-verliert-nach-einer-schwachen-leistung-gegen-vaduz-mit-02-131629524
***Description***: Adblock detection. Same detection on related sites:

- https://www.basellandschaftlichezeitung.ch/sport/basel/nach-spaetem-gegentor-der-fc-basel-spielt-zu-hause-gegen-lugano-nur-11-unentschieden-131629557
- https://www.limmattalerzeitung.ch/limmattal/zuerich/unbekannte-beschaedigen-in-zuerich-altstetten-rund-40-gartenhaeuschen-131630481
- https://www.solothurnerzeitung.ch/solothurn/thal-gaeu/anno-1375-soeldner-unter-franzoesischer-fahne-auf-verwuestungstour-im-gaeu-131624739
- https://www.grenchnertagblatt.ch/solothurn/thal-gaeu/anno-1375-soeldner-unter-franzoesischer-fahne-auf-verwuestungstour-im-gaeu-131624739
- https://www.oltnertagblatt.ch/solothurn/thal-gaeu/anno-1375-soeldner-unter-franzoesischer-fahne-auf-verwuestungstour-im-gaeu-131624739
- https://www.aargauerzeitung.ch/aargau/kanton-aargau/die-letzten-157-telefonkabinen-im-aargau-viele-von-ihnen-verschwinden-bald-131635719

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29607951-068be434-87f3-11e7-8e9e-94df6390ec07.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
