### ISSUE TITLE
Блокировка ненужного элемента.

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#64364]
Здравствуйте!
Буду очень признателен, если вы поможете заблокировать элементы обведённый в красный кружёчек. Они мне сильно мешают. Вместо того, чтобы ткнуть по нужной мне кнопке, я машинально тыкаю на эти ненужные элементы. Какие пользовательские правила я должен добавить, чтобы заблокировать эту гадость **_ВЕЗДЕ_** (так, чтобы оно не появлялось ни на одной работе)?

1
![20200921_223126](https://user-images.githubusercontent.com/71668168/93812870-de984a00-fc5a-11ea-8227-cf1ae29d0450.jpg)
2
![Screenshot_20200921-222611](https://user-images.githubusercontent.com/71668168/93812876-e1933a80-fc5a-11ea-8b66-9386d6e7a846.jpg)
3
![Screenshot_20200921-223226](https://user-images.githubusercontent.com/71668168/93812903-eeb02980-fc5a-11ea-97e6-adcfd4c4f02f.jpg)

Ссылки на разделы публикую ниже:
1
https://ficbook.net/home/myfics
2
https://ficbook.net/home/my_requests
3
https://ficbook.net/requests/536772

### Очень надеюсь на вашу помощь!
Заранее спасибо!

**Comment by Alex-302** [comment]
`ficbook.net##a[href$="/premium"]`
