### ISSUE TITLE
gelbooru.com - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6437]
***Site***: https://gelbooru.com/index.php?page=post&s=view&id=3787796
***Description***: Blue bar is missing.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29611975-ff135b58-87ff-11e7-936a-4e707af46296.png)

How it should look like:

![image](https://user-images.githubusercontent.com/10995998/29612007-1087edcc-8800-11e7-93cf-2d3f587d8926.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
