### ISSUE TITLE
radiojavan.com - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6438]
***Site***: https://www.radiojavan.com/videos/video/mojan-yz-saman-pi-chalim-2-(ft-ho3ein)
***Description***: Video won't start unless you click on 480p/720p. Comments section is blocked too.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29612604-5ac96c92-8802-11e7-93c4-0a84be878342.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
