### ISSUE TITLE
Mobile ADS Filter obsolete?

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardFilters#64398]
I disabled the mobile ads filter since a while now on my iPhone and iPad and I can't see any differences. Is the filter still necessary? Or maybe include him in the base filter?

**Comment by Alex-302** [comment]
This filter is required for blocking ads and fixing issues on mobile versions of sites and mobile apps.
A lot of ads just blocked by Base filter(Google ads etc.).
