### ISSUE TITLE
aljazeera.com - title is partly hidden on mobile

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#6439]
Here is how it looks like:
<details>

![unnamed 1](https://user-images.githubusercontent.com/5947035/29614850-73c7184a-8814-11e7-81da-dc9a6b98cbe3.png)
</details>

The issue is easy to reproduce even with desktop AG (the website has responsive layout).

**Comment by AdamWr** [comment]
Fixed.
