### ISSUE TITLE
http://www.macdigger.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6440]
http://www.macdigger.ru/ - missed ads

![image](https://user-images.githubusercontent.com/15856304/29614966-dd74d3a4-8814-11e7-9741-2b56f357d4a0.png)

***System configuration***

Information | value
--- | ---
Operating system: | iOS 10.3.3/11 beta 6
Browser: | Safari
Adguard version: | 1.3.0.81
Simplified filters(iOS) | Off
Adguard DNS: | None
Adguard filters: | 1 2 3 4 12
Ticket ID (if exists): | 1591319

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed, but not for a long time(because iOS)
