### ISSUE TITLE
bieber.com [NSFW]

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#6441]
#Вроде на форуме Adguard ГДЕ Я ЗАБАНЕН, есть тема о расширениях которые суют рекламу. Так вот очень редко на Яндекс.Музыке и ВК проскакивает от расширения
FastProxy - обход блокировки сайтов реклама своего даунлоадера, очеьнь редко
Скрин https://pp.userapi.com/c837536/v837536682/67c8e/KzzBRGnIY_w.jpg
Разместите сообщение там в теме, предупредив всех, и можно тему прикрывать эту
Могу скинуть айпи если надо разбаньте и активируйте на форуме, кстати, а то система думает я спамер и х*чит по айпи

Скоро фура отчётов приедет (сайты которые осматриваю на рекламу ворую отсюда https://hg.adblockplus.org/ruadlist/) (где bitblock.txt это у нас фильтры соцсетей и раздражителей, где cntblock счётчики, остальное аналог русского фильтра)
(рекомендую перенести некоторые счётчики прямо оттуда к нам если таковые найдутся)

**Comment by Alex-302** [comment]
Дай ссылку на расширение.

> форуме Adguard ГДЕ Я ЗАБАНЕН

не безосновательно. Изначально я был против этого.

**Comment by Adguarder** [comment]
https://chrome.google.com/webstore/detail/fastproxy-%D0%BE%D0%B1%D1%85%D0%BE%D0%B4-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA/mkelkmkgljeohnaeehnnkmdpocfmkmmf?hl=ru

кстати добавьте сайт репозитория адблока в закладки туда тоже смотрите и будьте лучшими

**Comment by Alex-302** [comment]
Не повторилось. С каких доменов загружает?
