### ISSUE TITLE
lesfrontaliers.lu

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#64411]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Various adticles, ads, and placeholders. I propose adding the following entries to AdGuard French Filter:
```
||lesfrontaliers.lu/wp-content/uploads/lesfrontaliers/habillage^$image
lesfrontaliers.lu##.fake-topper
lesfrontaliers.lu###header-wrapper + div[class="row "]
lesfrontaliers.lu##article[id^=post-]:has(.sponsored-indicator)
lesfrontaliers.lu##.ad-listing
||mmannis.spinforge.com^
||lesfrontaliers.lu/iframe-cv^
```

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/93952410-0bc32600-fd49-11ea-8e50-90a0b9fcc271.png)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/93952459-2d241200-fd49-11ea-92cd-76b979692a0c.png)
</details><br/>

***Steps to reproduce the problem***:

1) Visit `https://www.lesfrontaliers.lu/`.

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/93952506-49c04a00-fd49-11ea-9bd3-09263a7bf89e.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 May 2020 Update
Operating system version (Android/iOS) | ?
Browser:                               | Chrome 85.0.4183.121 x64
AdGuard version:                       | Nano Adblocker 1.0.0.153 + Nano Defender 15.0.0.205
Filters enabled:                       | See screenshot above.
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | N/A
Helpdesk ID (if exists):               | N/A

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by zloyden** [comment]
Thanks for your report, removed ads with annoyances and share.
But I don't see those requests on my end with French IP. Why did you block them?
```
mmannis.spinforge.com
lesfrontaliers.lu/iframe-cv
```

**Comment by DandelionSprout** [comment]
I loosely recall that `||mmannis.spinforge.com^` was supposed to block a Hyundai car ad near the top, but in its spot I now only get either a much bigger wine expo ad, or nothing at all.

**Comment by zloyden** [comment]
@DandelionSprout thanks for your explanation, but I still can't see those requests on my end with French IP.
