### ISSUE TITLE
Blocking ads in youtube.com site on iOS

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6442]
We have a report and we cannot replicate the issue. What rule in which filter blocks this type of ads?

![image](https://user-images.githubusercontent.com/15856304/29616059-c6fe41ba-8818-11e7-83a1-ca5731b5071a.png)

<details> <summary> state.txt </summary>

Application version: 1.3.0.81
Application lifetime: 2017-07-01 07:21:05 +0000

Device: iPhone
Platform: iOS
OS: 10.3.3
ID: 9043620B-8F9E-448A-BE6F-D5A9E36D55BD

Locale: ru
Region: ax

Optimized enabled: NO
Rules converted: 36210 from: 36210.

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.23.50 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.6 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.81 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.53.38 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.52 Enabled=YES

</details>

**Comment by Alex-302** [comment]
I can't reoroduce it without AG.
I need access to MacOS with connected iPhone.

**Comment by Alex-302** [comment]
@zebrum could you check it?

**Comment by evgeniy-ADG** [comment]
I can't replicate on two iOS devices I have

**Comment by zebrum** [comment]
reproduced

**Comment by Alex-302** [comment]
It can't be hidden on iOS.
