### ISSUE TITLE
Russian filter hangs the vk.com site in Firefox

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6443]
> AdGuard вызывает проблемы связанные с зависанием/задержками на сайте vk.com после скроллинга некоторого количества записей на странице. Отключаю AdGuard - всё становится нормально.

<details> <summary >Список подключённых фильтров прикрепил к сообщению</summary>

![image](https://user-images.githubusercontent.com/15856304/29616390-01985b7a-881a-11e7-8a38-bef7ffe9b6ef.png)

</details>

FF 54.0.1(x64); Win7(x64)
ID: 1493043

**Comment by Alex-302** [comment]
У меня не повторяется. Пусть попробует выключить RuAdList.
@zebrum можешь у себя в Фоксе глянуть?

**Comment by evgeniy-ADG** [comment]
Он говорит, что проблема уходит только с выключением Русского фильтра. Других жалоб нет, у нас тоже все отлично.

**Comment by Alex-302** [comment]
Теоретически такое может быть из-за правил с Extended CSS.
Передай на проверку исключения:
```
vk.com#@##page_wall_posts > div[id^="post-"][-ext-has='> div._post_content > div.post_content > div.post_info > div.wall_text > div.wall_post_cont > div.wall_marked_as_ads']
vk.com#@#.wall_wrap div[id^="post-"][-ext-has='div.post_content > div.post_info > div.wall_text > div.wall_post_cont > div.wall_marked_as_ads']
vk.com#@##feed_rows > div[class="feed_row "] > div[class^="feed_repost-"][-ext-has='div[class="wall_marked_as_ads"]']
vk.com#@##page_wall_posts > div[id^="post-"][-ext-has='div._post_content > div.post_content > div.post_info > div.wall_text > div.wall_marked_as_ads']
```

**Comment by evgeniy-ADG** [comment]
Отписал. Ждем.

**Comment by pro100Hub** [comment]
С правилами, которые указал Alex-302 вроде стало лучше. Раньше, после скрола некоторого количества записей на странице начинались задержки отклика. Например наведение курсора мышки на ссылку, видео, изображение, задержки открытия/закрытия мультимедии. И проблема наблюдалась именно из-за Русского фильтра.
Пока вроде работает с правилами, дальше посмотрим. Спасибо.

**Comment by Alex-302** [comment]
@pro100Hub а какой процессор у вас? На vk.com для скрытия рекламных постов применяется расширенный CSS, на старых компьютерах может подтормаживать на некоторых сайтах.

**Comment by pro100Hub** [comment]
i7 920 3.8Ghz, ОЗУ 6Gb, GPU GTX 275
Только интересен момент с Русским фильтром. Почему задержки пропадают, когда его отключал?

**Comment by Alex-302** [comment]
Вроде не слабый процессор. 
А можете более подробно описать действия, при которых начинает тормозить?(адрес страницы, последовательность действий)

> Только интересен момент с Русским фильтром. Почему задержки пропадают, когда его отключал?

выше ж написал. Расширенный CSS достаточно ресурсоёмкий.

**Comment by pro100Hub** [comment]
Адрес страницы как я понимаю не имеет значения. Последовательность действий простая, заходите на страницу, листаете с десяток записей. И далее будет заметно как начинают возникать задержки:
1. Начинает тормозить скроллинг. Как буд-то FPS 15-20 или менее.
2. Хочешь зайти в тему обсуждения, наводишь на ссылку, а она не выделается, т.е нет фокуса, приходит с задержкой, опозданием. Соответственно перейти к этой теме можно только когда выждешь эту задержку. 
3. Практически тоже самое с мультимедийным контентом. Видео и изображения открываются/закрываются с задержкой. С аудио практически тоже самое, нажимаешь на паузу, но срабыватывает с задержкой.
В общем все действия замедляются/задерживаются.

> выше ж написал. Расширенный CSS достаточно ресурсоёмкий.
Не совсем понимаю что это. Расширенный css находится в Русском фильтре?

**Comment by Alex-302** [comment]
> Адрес страницы как я понимаю не имеет значения.

Имеет. Специально это указал в сообщении.

> Не совсем понимаю что это. Расширенный css находится в Русском фильтре?

https://ru.wikipedia.org/wiki/CSS - это обычный CSS, поддерживаемый браузерами и работающий быстро. Расширенный CSS - это надстройка, реализованная в Адгарде для расширения возможностей по сокрытию элементов страницы. Применяется в виде правил.

**Comment by pro100Hub** [comment]
> Имеет. Специально это указал в сообщении.

Не имеет) Можете открыть абсолютно любое сообщество/группу с большим количеством записей, где есть фото, видео, аудио.
Ссылку на конкретное сообщество приводить не имеет смысла, т.к будет рекламой да и смысла как я уже сказал ранее, нет.

**Comment by Alex-302** [comment]
Смысл есть всегда, рекламой не будет. Я вк не пользуюсь, популярных сообществ не знаю.

**Comment by pro100Hub** [comment]
Первые попавшиеся: 
https://vk.com/best_of_mma
https://vk.com/vinevinevine

**Comment by zebrum** [comment]
@pro100Hub а версия AdGuard какая? Как будто-бы есть немного разница с включенным и отключенным русским фильтром, но она не настолько значительна.

**Comment by Alex-302** [comment]
У себя на ноуте разницы не ощутил, но у меня i7, хоть и старый.
Постоянной загруженности процессора тоже нет.

**Comment by Alex-302** [comment]
Да облистался уже) Никак не повторяется. А можете сравнить работу с Хромом?

**Comment by pro100Hub** [comment]
> А можете сравнить работу с Хромом?

В Хроме проблем нет.

**Comment by pro100Hub** [comment]
@Alex-302 правила не используете?

> vk.com#@##page_wall_posts > div[id^="post-"][-ext-has='> div._post_content > div.post_content > div.post_info > div.wall_text > div.wall_post_cont > div.wall_marked_as_ads']
vk.com#@#.wall_wrap div[id^="post-"][-ext-has='div.post_content > div.post_info > div.wall_text > div.wall_post_cont > div.wall_marked_as_ads']
vk.com#@##feed_rows > div[class="feed_row "] > div[class^="feed_repost-"][-ext-has='div[class="wall_marked_as_ads"]']
vk.com#@##page_wall_posts > div[id^="post-"][-ext-has='div._post_content > div.post_content > div.post_info > div.wall_text > div.wall_marked_as_ads']

**Comment by Alex-302** [comment]
нет.
@vozersky можешь у себя глянуть?

**Comment by vozersky** [comment]
@Alex-302 не воспроизводится,  FF 55.0.3 последний stable
