### ISSUE TITLE
twitch.tv - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6446]
***Site***: https://www.twitch.tv/imaqtpie
***Description***: Ads while watching the stream (not logged in).

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29618116-52cf9a6a-8817-11e7-98e5-2839fae9b6f2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by danidoedel** [comment]
That's a segment of an ad (not sure if that will help and if it's possible to block these ads, I really hope so though):

```
/* SUMMARY REQUEST INFO */

Request URL: https://video-edge-c2aeac.fra02.hls.ttvnw.net/v1/segment/CuYCSDZGGBgC_F6etKDStIucR4CE5NwA4fesy9SeCPsEoO_x0IGGc7M6a-7ZEeL2ySkz72e8_GWFJazlqaTaKLnSUsLZ8HuxbBWdopJUKvjYIVwE9JuCQa2JZ8Wbx1OrIndhmkJtAX0E-0nYO3I-SN8Mb_pbNA3YCEMstg8O7YgqBGnUDX5dT--_3oDi5krdmeedX8YvE4Pc8LH8zuoKh3m4uxK13wWLFq_f3Q1kCHzY5fAmOnaKvNFkpBCEjnUXSj0kFc29_fj3GJxRY4Sa2wuP8sZlR8W5IXscPuoTNodx8Si8FU3m62Ie6tPvRohnUJJdpgfu_2kPo_yX0HTCz-rPg2DatyPofgmMqNQsZpDR78QxV_KPiav0Idfz3WSDhgglhCgAvHnrUKflFiu3_uKz6pOm0DcgZdJP12IOuTg5Z3QZYzszoN4UQoNLNHV8gwOHZy7L6SksvDFUSDW2z9KcSso24ENCNxIQdBotJtskw5v34_KyY_V_5xoME3C55-lngRSVDwap.ts
Remote Address: 52.223.196.178:443
Source URL: https://www.twitch.tv/imaqtpie
Process name: chrome.exe
Process ID: 16656
Connection ID: 23980
Status: Bypassed
Content type: Ajax
Protocol type: Tcp
Start time: 15:40:58.4399
Time: 284 ms
Size: 1377,0 KB
Request Method: GET
Status code: 200 OK

```

**Comment by AdamWr** [comment]
On forum is a topic about ads on twitch.tv  - https://forum.adguard.com/index.php?threads/twitch-tv.24617/

You can try this rule:
`||ttvnw.net/v*/playlist/*.m3u8$replace=/#EXT-X-DISCONTINUITY([\s\S]*?#EXT-X-DISCONTINUITY|[\s\S]*)/,important,domain=twitch.tv`
Unfortunately I don't know if this works, because I can't reproduce these ads.

**Comment by iverkhohliad** [comment]
Helpdesk ID 1646025

User tried adding the suggested rule but ads are still there.

**Comment by AdamWr** [comment]
@iverkhohliad Could you please ask user to check this rule:
`||player.twitch.tv/js/player.*js$replace=/adblock/NOadblock/,important`

**Comment by evgeniy-ADG** [comment]
Asked here: 781832

**Comment by iverkhohliad** [comment]
Asked: 1646025

**Comment by Alex-302** [comment]
@AdamWr

**Comment by AdamWr** [comment]
I can't reproduce ads on twitch.tv

**Comment by danidoedel** [comment]
Same, can't reproduce ads right now.
