### ISSUE TITLE
Add BarbBlock filter list

### ISSUE THREAD

**Issue by justinmayer** [AdguardTeam/AdguardFilters#6447]
[BarbBlock](https://ssl.bblck.me) is a content blocking list that blacklists sites that have used spurious and invalid DMCA takedowns to force removal from other content blocking lists. Originally a Chrome extension, it has [recently been made available as a block list](https://github.com/paulgb/BarbBlock/issues/5).

This list is available in [both ABP and uBlock Origin formats](https://ssl.bblck.me/install). Would you please add this list so it is available in the AdGuard configuration UI and can be enabled by users via a checkbox in the usual filter selection settings screen?

I am not certain if this is the appropriate place to request filter list additions, but I could not locate a more appropriate repository. If there is a better place to make this request, please let me know. Thank you!

**Comment by Alex-302** [comment]
@ameshkov should we add this filter?

**Comment by ameshkov** [comment]
Hi @justinmayer 

Sure, we will, thank you!

**Comment by ameshkov** [comment]
**Metadata**

Title: `BarbBlock`
Description: `BarbBlock is a content blocking list with standalone browser extensions for Chrome and Firefox. It blacklists sites which have used DMCA takedowns to force removal from other content blocking lists. Such takedowns are categorically invalid, but they can be effective at intimidating small open-source projects into compliance.'
Homepage: https://ssl.bblck.me/

**Comment by ameshkov** [comment]
@justinmayer 
would you like to change the proposed metadata?

**Comment by mmigi** [comment]
The BarbBlock filter in our db now and available for apps.
