### ISSUE TITLE
http://anime47.com -AntiAdBlock Script - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6448]
***Description***:
* **Current behaviour**: 
http://anime47.com up on the screen there is AntiAdBlock message
***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 
Adguard driver (Windows): | WFP 
Adguard DNS: | None
Adguard filters: | 0,,2,3,4,14,7,207 211,210,226
Ticket ID (if exists): | 1617180

**Comment by Alex-302** [comment]
Not reproduced with ABPVN list.
