### ISSUE TITLE
smallnetbuilder.com

### ISSUE THREAD

**Issue by GigabitEthernet** [AdguardTeam/AdguardFilters#6450]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

There is whitespace visible at the top of the page.

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

<img width="1085" alt="screen shot 2017-08-23 at 23 43 55" src="https://user-images.githubusercontent.com/4457688/29641753-03fa4746-885d-11e7-80b7-5268583fbaf6.png">
</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

There should be no whitespace visible.

</details>

***Steps to reproduce the problem***:

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

Go to website (fullscreen browser to be sure) and the whitespace will be visible. Tested on Safari on macOS.

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Safari 10.1.2
Adguard version: | 2.6.7
Adguard DNS: | None
Adguard filters: | English filter, Safari filter

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
https://github.com/AdguardTeam/AdguardFilters/issues/6450
```
