### ISSUE TITLE
youtube.com - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6451]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: 

1. https://www.youtube.com/watch?v=XhhH5sWI8vM
2. https://www.youtube.com/watch?v=-BAs7CI6ICw

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>1:</summary>

![image](https://user-images.githubusercontent.com/15856304/29656773-239cf3c6-88be-11e7-9261-871d7a5b9925.png)

</details>

<details><summary>2:</summary>

![image](https://user-images.githubusercontent.com/15856304/29656753-13b4413a-88be-11e7-91a7-5f4af094f35b.png)

</details>

[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Windows NT 6.1.7601 Service Pack 1
Browser: | Chrome
Adguard version: | 6.1.331.1732
Adguard driver (Windows): | TDI
Adguard DNS: | None
Stealth mode options(Windows) | below the table
Adguard filters: | 1, 2, 3, 14
Ticket ID (if exists): | 1611437
<details><summary>Stealth Mode :</summary>
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 0,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": false,
  "BlockWebRtc": false,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": true,
  "CustomIp": "209.141.53.254"

</details>

**Comment by evgeniy-ADG** [comment]
I have no idea what to do with this, it works with no ads on my Mac and on a Windows machine.

**Comment by Alex-302** [comment]
I don't see ads on these screenshots.
Annotations are not reproduced,

**Comment by evgeniy-ADG** [comment]
So what do we do? ) The customer is interested in blocking those annotations.

**Comment by Alex-302** [comment]
I don't know. Ask for annoying element's code.
