### ISSUE TITLE
ramendb.supleks.jp

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#64521]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

URL: `https://ramendb.supleks.jp/review/1351766.html`
[Update] the same issue on other subdomains: `https://gyouzadb.supleks.jp/`

Issue: unblocked Rakuten ads/promotion

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![ramendb](https://user-images.githubusercontent.com/58900598/94167253-4226af80-fec7-11ea-8b5b-094d62f08948.png)

</details>

***Steps to reproduce the problem***:

Go around the site (visit each store, view reviews etc.) - may be non-trivial to reproduce. At first I didn't see them.

***System configuration***

**Filters:**

Base, Mobile, TPL, and Japanese

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android 10
Browser:                               | Firefox 81.1.1
AdGuard version:                       | 3.5(63)
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On
AdGuard DNS:                           | None

**Notes:**

Mobile-only issue

Unrelated to the issue but something like these can be added to Mobile filters to hide placeholders (you prefer to specify style a bit more, I know )
```
supleks.jp###footer-banner
supleks.jp###index > .more + div[style]
supleks.jp###shop-body > #btn-post + div[style]
```
And for Spyware:
`||supleks.jp/action/log/`

Regarding the issue for Android:
`supleks.jp#%#//scriptlet('abort-current-inline-script', 'document.getElementsByClassName', 'adBlocked')` 

For iOS:
`supleks.jp##div[style][data-height]`

**Comment by zloyden** [comment]
Unfortunately, I can only reproduce one left-over and I'm not sure about blocking `supleks.jp/action/log/`.
@AdguardTeam/filters-maintainers please take a look.

**Comment by AdamWr** [comment]
It seems that this website shows these ads only in mobile view when there is a cookie `adblocked=1` which is created when localStorage key `adblocked_count` is `>= 5`.

Added:
```
||supleks.jp/action/log/
supleks.jp##div[class*="_"][style][data-height]
supleks.jp#%#//scriptlet('abort-current-inline-script', 'document.getElementsByClassName', 'adBlocked')
```

>`supleks.jp###footer-banner`

It should be already hidden by `###footer-banner`

>`supleks.jp###shop-body > #btn-post + div[style]`

Seems to be covered by `supleks.jp##div[class*="_"][style][data-height]`

**Comment by Yuki2718** [comment]
@AdamWr This placeholder at the top page is not covered:

<details>

![ramendb](https://user-images.githubusercontent.com/58900598/94432544-e499a800-01d1-11eb-9a81-38ce8dc8dd8c.png)

</details>

You can just remove the style attribute to cover this too.

**Comment by AdamWr** [comment]
Okay, removed `[style]` from this rule `supleks.jp##div[class*="_"][style][data-height]`
Thank you.
