### ISSUE TITLE
saturn.de - Social Widget

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6452]
***Site***: http://www.saturn.de/de/product/_samsung-ue78ku6509-2109880.html
***Description***: Social share icons.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29660767-6413f3ce-88c2-11e7-80f5-15eda56b38ed.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
