### ISSUE TITLE
Saavn.com is not working

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#6458]
@Anoop2609 commented on [Wed Aug 23 2017](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/833)

### Steps to reproduce

1.Goto https://www.saavn.com/
2.Try to play any song 
3.Unable to play any song or list of songs

### Expected behavior
Play song and list of songs smoothly
### Actual behavior

<details><summary>Screenshot:</summary>

</details>

<details><summary>Screenshot of the browser console:</summary>

</details>

### Your environment

* Adguard AdBlocker extension version: 2.7.0 beta
* Environment name and version: FF Nightly 57
* Filters you use in Adguard: English filter, Spyware filter, Social media filter, Annoyances filter, EasyPrivacy,  Fanboy's Annoyances, Fanboy's Enhanced Tracking List
* Any other browser extensions you have installed: Disconnect

**Comment by XX-J** [comment]
Виновник - Фильтр счётчиков и систем аналитики,  Правила:
`||saavn.com/stats.php^
/fingerprint2.min.js`

Решение - Добавить исключения:
`@@||saavn.com/stats.php
@@||cloudflare.com/*/fingerprint2.min.js$domain=saavn.com`

**Comment by Alex-302** [comment]
Спасибо, поправил.

**Comment by Anoop2609** [comment]
Still not resolved

**Comment by Alex-302** [comment]
It works on my end. Please check for filter updates.

**Comment by Anoop2609** [comment]
Fine, Fanboy's Enhanced Tracking List creating problem

**Comment by Alex-302** [comment]
Strange. This filter does not block anything on my side

<details>

![image](http://imagizer.imageshack.com/img923/1783/IQ37Ph.png)
</details>
