### ISSUE TITLE
viafree.no - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6460]
***Site***: https://www.viafree.no/programmer/livsstil/luksusfellen/
***Description***: Cookie notice leftover breaks navbar.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29662353-4fc6fd80-88c7-11e7-9ff1-ffb1490cdc1b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
