### ISSUE TITLE
susutinv2.com - Anti AdBlock Script- Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6461]
***Description***:
* **Current behaviour**: 

Anti AdBlock Script on Windows on:
https://susutinv2.com/5BCsN
Reproduced on our side (Mac OS)
<details><summary>Screenshot:</summary>

![0yyhjix8tro6dnjn0zkqhw](https://user-images.githubusercontent.com/28784344/29666840-b2afc54c-88e2-11e7-8676-290a75b73ce2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Mac OS
Browser: | Chrome
Adguard version: | 1.4.1.
Adguard DNS: | None /
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1551511

**Comment by Alex-302** [comment]
Fixed.
