### ISSUE TITLE
MoneyKat.com - Incorrect blocking -Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6462]
***Description***:
* **Current behavior**: 

The user has a website that contains a video set to autoplay when the website is opened. The video is served from the user`s website server and is embedded in the website via html5. Adguard on android prevents the video from playing even when the website is whitelisted. The only way that allows the web page video to autoplay is to completely disable Adguard. The website is http://moneykat.com. The video in question is in the website header. 

FYI The user changed the domain where the video is hosted and it works now. So there seems to be something about my MoneyKat.com domain that Adguard does not like. Any ideas?

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Adguard version: | 2.9.136
Adguard mode (Android): | Proxy(manual)
Filtering quality (Android): | high-speed 
HTTPS filtering (Android): |  Off
Adguard DNS: | None 
Adguard filters: | 2, 3, 4, 14, 1, 11
Ticket ID (if exists): | 1616751

**Comment by Alex-302** [comment]
Where can I find these videos?

**Comment by ypetruk** [comment]
@Alex-302 As I understood, it should be in the background

**Comment by jefrey1f** [comment]
I made a short video showing how the site header looks with adguard both disabled and enabled on my dropbox 
[here](https://www.dropbox.com/s/frkxucbsqtf4nyc/moneykat%20adguard%20issue.mp4?dl=0)

When adguard is enabled and the video fails to play, the webserver falls back to displaying a static image (header-img.png). The fallback is programmed using the "onerror" attribute on the `<source>` element which you can see in the html code snippet from the website header here:

```
<div id="wp-custom-header" class="wp-custom-header">
    <video  id="wp-custom-header-video" playsinline autoplay loop muted preload="metadata" width="2000" height="1200" poster="http://moneykat.com/wp-content/uploads/moneykat-poster2-600px-200c.gif">
        <source src="http://moneykat.com/wp-content/uploads/moneykat-header2f.mp4" type="video/mp4" onerror="fallback(parentNode)" />
        <img src="http://moneykat.com/wp-content/uploads/header-img.png" style="width: 100%;" />
    </video>
</div>
```

The `<source>` element is currently pointing to a video file on moneykat.com. FYI if I move the source file to jeffreyer.com it works fine. I use this as a workaround.

Any ideas would be most appreciated. Thanks for your help.

**Comment by jefrey1f** [comment]
BTW is this anything interesting? I noticed that when using Google's DNS to resolve moneykat.com, it's returning a DNSSEC validation failure. You can check this yourself by using the following link: 

https://dns.google.com/resolve?name=moneykat.com

**Comment by Alex-302** [comment]
@jefrey1f 
> When adguard is enabled and the video fails to play, the webserver falls back to displaying a static image

could you please check with disabled all filters?

**Comment by Alex-302** [comment]
> I made a short video

dropbox is extremely slow, I can't download from it. Please upload on mega.nz, for example.

**Comment by jefrey1f** [comment]
@alex-302 I can do that or I can just email it to you - it's 18MB. Which would you prefer?

**Comment by jefrey1f** [comment]
@alex-302 Or even youtube...

**Comment by jefrey1f** [comment]
OK I put it on Mega. Here is the link 
https://mega.nz/#!9C4SQL4S

**Comment by jefrey1f** [comment]
https://mega.nz/#!9C4SQL4S!-f7rp8-ShUYNNum3JIYOTMwrXvW8PMqFt-3X6exyuA0

**Comment by Alex-302** [comment]
Strange. It plays only 1 second on my side without Adguard.
Please describe in text that steps.
And check these rules one **by one**:
* `@@||moneykat.com^$urlblock`
* `@@||moneykat.com^$jsinject,elemhide,content`
* `@@||moneykat.com^$document`

**Comment by jefrey1f** [comment]
"It only plays 1 second...". Which video do you mean? The one I posted on Mega or the MoneyKat header vid?

"Check these rules" - how do I check rules!

Thanks

**Comment by Alex-302** [comment]
> . Which video do you mean? The one I posted on Mega or the MoneyKat header vid?

I saw. It plays on your device.



> how do I check rules!

Add the rule to custom filter and check the issue. But don't add three rules at the same time.

**Comment by jefrey1f** [comment]
STEPS TO REPRODUCE:

_Using Chrome on Windows desktop to show expected behavior:_
1. Open MoneyKat.com
2. Notice the header background first displays a 2 second .gif poster image (attached), then plays a 16 second .mp4 video on continuous loop (attached)

_Now using Chrome on Android:_
3. Clear browser data cache 
4. Disable Adguard
5. Open/refresh MoneyKat.com
6. Notice the header background should look like it does in the above step 2
STEPS TO REPRODUCE:

_Now enabling Adguard on Android:_
7. Clear browser data cache 
8. ENable Adguard
9. Open/refresh MoneyKat.com
10. Notice the header background falls back to the static .jpg image (attached) and does not play the video
 
_Now disabling all ad blocker filters:_
11. Clear browser data cache 
12. Open Adguard, go to Ad Blocker section and disable all filters
13. Open/refresh MoneyKat.com
14. Notice the header background falls back to the static .jpg  image and does not play the video

2 second animated GIF:
![moneykat-poster2-200](https://user-images.githubusercontent.com/31324447/29792916-fb7708b4-8c0f-11e7-9c94-bce7b28ea203.gif)

static fallback JPG image:
![header-img](https://user-images.githubusercontent.com/31324447/29792915-fb6e9012-8c0f-11e7-8778-72dbadd9bc97.png)

16 second MP4 video:
http://moneykat.com/wp-content/uploads/moneykat-header2f.mp4

**Comment by jefrey1f** [comment]
> Add the rule to custom filter and check the issue. But don't add three rules at the same time.

I dont know how to check the issue. I'm assuming I enable filter logging, refresh the website, but then what? I see some entries in the log, some are white and some are in green. If I click on the green ones, I see more detail but I dont know what I'm looking for. Is there some way to export the log and send it to you? Please advise. Thanks

**Comment by Alex-302** [comment]
It seems that caused by a bug
https://github.com/AdguardTeam/AdguardForWindows/issues/1905

**Comment by jefrey1f** [comment]
Hey @Alex-302 
I'm happy you found the bug. Nice work! 

I didnt realize you guys were running Adguard on Windows but that makes sense now. So my step #2 above was actually failing!

Thanks again

**Comment by Alex-302** [comment]
Closed here.

**Comment by jefrey1f** [comment]
One more piece of information for you guys. If I change the server on which the 16 sec MP4 video is hosted (i.e., from moneykat.com to jeffreyer.com), it displays fine on my Android! So this tells me there are possibly 2 bugs we're seeing.
