### ISSUE TITLE
ad/trackers from ios dns log (simplified domain list)

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#64624]
here is a list of some trackers/ad networks the past few weeks i have gathered from my dns log on ios app to contribute. some might be duplicates or have been removed from the list before but thought id help contribute. the list should be double checked just to make sure.

events.mapbox.com
log2.spotify.com
analytics.twitter.com
ad.particlenews.com
ad-particlenews-com-2-1579123584.us-west-2.elb.amazonaws.com
elb-logproxy-963550089.us-west-2.elb.amazonaws.com
log.particlenews.com
us-central1-amp-error-reporting.cloudfunctions.net
inputs.alooma.com
solutions.invocacdn.com (same as invoca.net tracker)
launches.appsflyer.com
inapps.appsflyer.com
gcdsdk.appsflyer.com
crashlytics2.l.google.com
sb.scorecardresearch.com.edgekey.net
analytics.a-f.io
analytics-api.a-f.io
crashlyticsreports-pa.googleapis.com
events.textme-app.com
textme-kpi-events-1574143683.us-east-1.elb.amazonaws.com
events.split.io
events-prod-1-1033355748.us-east-1.elb.amazonaws.com
launches.appsflyer.com
firebaselogging-pa.googleapis.com
api.mixpanel.com
bid.g.doubleclick.net
aa.online-metrix.net
h-sdk.online-metrix.net
sessions.bugsnag.com
notify.bugsnag.com
app.adjust.com
crashlytics2.l.google.com
gcdsdk.appsflyer.com
ads.mopub.com
analytics.chase.com
sb.scorecardresearch.com
www.googletagmanager.com
www-googletagmanager.l.google.com
mads.amazon-adsystem.com
s.amazon-adsystem.com
unityads.unity3d.com
mboxedge35.tt.omtrdc.net
s.go-mpulse.net
attservicesinc.tt.omtrdc.net
fls.doubleclick.net
s2.go-mpulse.net
smetrics.att.com
assets.adobedtm.com
dpm.demdex.net
mediation.adnxs.com
d.agkn.com
s.skimresources.com
global.px.quantserve.com
static.scroll.com
secure.quantserve.com
h-intuit.online-metrix.net
pagead.l.doubleclick.net
www.googleadservices.com
client-analytics.braintreegateway.com
bugly.qcloud.com (crash reporter)
api.rollbar.com
cdn.quantummetric.com (https://cloud.google.com/customers/quantum-metric/)

**Comment by jordanelliott23** [comment]
@ameshkov

**Comment by Alex-302** [comment]
As I see, your list contains many already blocked domains.

**Comment by Alex-302** [comment]
Checked part of the list - it contains a lot of domains, which blocking will break a half of Internet and which used for bug trackers(marked them) 
```
-analytics.twitter.com
-aa.online-metrix.net
-h-sdk.online-metrix.net
-app.adjust.com
-crashlytics2.l.google.com
-crashlyticsreports-pa.googleapis.com
-launches.appsflyer.com
-sb.scorecardresearch.com.edgekey.net
-sb.scorecardresearch.com
-firebaselogging-pa.googleapis.com
-mboxedge35.tt.omtrdc.net
-attservicesinc.tt.omtrdc.net
-api.mixpanel.com
-www.googletagmanager.com
-www-googletagmanager.l.google.com

events.mapbox.com
log2.spotify.com
ad.particlenews.com
ad-particlenews-com-2-1579123584.us-west-2.elb.amazonaws.com
elb-logproxy-963550089.us-west-2.elb.amazonaws.com
log.particlenews.com
us-central1-amp-error-reporting.cloudfunctions.net
inputs.alooma.com
solutions.invocacdn.com (same as invoca.net tracker)
inapps.appsflyer.com

analytics.a-f.io
analytics-api.a-f.io
events.textme-app.com
textme-kpi-events-1574143683.us-east-1.elb.amazonaws.com
events.split.io
events-prod-1-1033355748.us-east-1.elb.amazonaws.com
analytics.chase.com

s.go-mpulse.net
fls.doubleclick.net
s2.go-mpulse.net
smetrics.att.com
assets.adobedtm.com
mediation.adnxs.com
d.agkn.com
s.skimresources.com
global.px.quantserve.com
static.scroll.com
secure.quantserve.com
h-intuit.online-metrix.net
pagead.l.doubleclick.net
www.googleadservices.com
client-analytics.braintreegateway.com
bugly.qcloud.com (crash reporter)
api.rollbar.com
cdn.quantummetric.com (https://cloud.google.com/customers/quantum-metric/)
```

**Comment by jordanelliott23** [comment]
@Alex-302 ok, understandable. so the ones without the - sign in front of them can be added though right?

**Comment by Alex-302** [comment]
@jordanelliott23 They will be checked. Some domains are already in the filters.

**Comment by jordanelliott23** [comment]
||admob-app-id-*.firebaseapp.com^$important
||promoted.sndcdn.com^$important

here is two more.

**Comment by Alex-302** [comment]
@jordanelliott23 Checked. Need more details about domains marked with `?`

**Comment by jordanelliott23** [comment]
hi im sorry i forgot to get back to you alex this got lost in my emails @Alex-302

**Comment by Alex-302** [comment]
@jordanelliott23 so you can provide more info about marked by `?` ?:)

**Comment by jordanelliott23** [comment]
> @jordanelliott23 so you can provide more info about marked by `?` ?:)

sorry i dont know which app produced alot of them. the only ones i can have you reproduce are the chase banking app is the analytics.chase.com and the the text me ones are an app called text me. but i dont see the textme ones in my log anymore. so idk if they removed those with an update recently or if it was just on first install of the app. sorry i couldn't be more of assistance about the other ones

**Comment by jordanelliott23** [comment]
also : 
app-measurement.com
pro.ip-api.com
pubnative.info

are located in an app called musi https://apps.apple.com/us/app/musi-simple-music-streaming/id591560124

i cant figure out if pubnative.info and pro.ip-api.com are trackers as i dont have littlesnitch program to check the url its requesting but they sound like ad and tracking domains. but app-measurement is literally in every app ive used. is there a reason why we dont block that one? @Alex-302

**Comment by jordanelliott23** [comment]
firebaselogging.googleapis.com
iad-01.braze.com:(https://whotracks.me/trackers/braze.html)
appboy-images.com (same as braze)

these are domains found in soundcloud app

**Comment by ip-api** [comment]
> pro.ip-api.com

> i cant figure out if pubnative.info and pro.ip-api.com are trackers as i dont have littlesnitch program to check the url its requesting but they sound like ad and tracking domains. but app-measurement is literally in every app ive used. is there a reason why we dont block that one? @Alex-302

pro.ip-api.com is not a "tracker", it returns the approximate geolocation and other ISP information for IP addresses, privacy policy: https://members.ip-api.com/legal

**Comment by jordanelliott23** [comment]
> > pro.ip-api.com
> 
> > i cant figure out if pubnative.info and pro.ip-api.com are trackers as i dont have littlesnitch program to check the url its requesting but they sound like ad and tracking domains. but app-measurement is literally in every app ive used. is there a reason why we dont block that one? @Alex-302
> 
> pro.ip-api.com is not a "tracker", it returns the approximate geolocation and other ISP information for IP addresses, privacy policy: https://members.ip-api.com/legal

hmm. thats still basically ip tracking tho. wouldn't that be considered as block worthy? :)

**Comment by ip-api** [comment]
> hmm. thats still basically ip tracking tho. wouldn't that be considered as block worthy? :) it says they store access logs so basically tracking us still

We're not tracking users, the endpoint you mentioned is an API that returns information about IP addresses, from a database. There are many such APIs with databases that can return information about IP addresses, businesses, weather and such.

Additionally, our domain was previously removed from the Adguard list: https://github.com/AdguardTeam/AdguardFilters/commit/08541083000d9628f35c364d52b179e236df7408

**Comment by jordanelliott23** [comment]
> > hmm. thats still basically ip tracking tho. wouldn't that be considered as block worthy? :) it says they store access logs so basically tracking us still
> 
> We're not tracking users, the endpoint you mentioned is an API that returns information about IP addresses, from a database. There are many such APIs with databases that can return information about IP addresses, businesses, weather and such.
> 
> Additionally, our domain was previously removed from the Adguard list: [0854108](https://github.com/AdguardTeam/AdguardFilters/commit/08541083000d9628f35c364d52b179e236df7408)

ok. sorry about that.
