### ISSUE TITLE
Sony Liv app - Incorrect Blocking - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6463]
***Description***:
* **Current behavior**: 
In Sony Liv App on Android, the Mobile Adds filter blocks the videos from loading 
https://play.google.com/store/apps/details?id=com.sonyliv&hl=en

From our side: Used the VPN app to browse the Sony Liv app (having Adguard manually configured)

***System configuration***

Information | value
--- | ---
Operating system: |Android 
Adguard version: | 2.9.136
Adguard mode (Android): | Proxy(manual)
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard DNS: | None 
Adguard filters: | in our test Android (1,2,3,4,11,14)
Ticket ID (if exists): | 642514

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
HTTP log is in `642514`

**Comment by ypetruk** [comment]
sorry for reopening but there another issue regarding this app
ticket id:1621675

**Comment by Alex-302** [comment]
@AdamWr

**Comment by AdamWr** [comment]
I checked again and video works fine on my end.

<details><summary>Screenshot</summary>

![sonyliv](https://user-images.githubusercontent.com/29142494/32331683-d12b1f34-bfe3-11e7-9a19-f94f6b32b7e5.png)

</details>

**Comment by Alex-302** [comment]
So close it.
