### ISSUE TITLE
http://tv.yandex.ru/ - Incorrect blocking - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6464]
***Description***:
* **Current behavior**: 

Incorrect blocking of pictures on http://tv.yandex.ru/ on Windows.
Reproduced on our side (Mac OS)

<details><summary>Screenshot(without Adguard):</summary>

![screen shot 2017-08-24 at 8 20 52 pm](https://user-images.githubusercontent.com/28784344/29679202-d57d01f8-8909-11e7-971d-e7b671017e7d.png)

</details>

<details><summary>Screenshot(with Adguard):</summary>

![screen shot 2017-08-24 at 8 21 37 pm](https://user-images.githubusercontent.com/28784344/29679241-e98c4d16-8909-11e7-8b71-f6e4b92272f4.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |Mac OS
Browser: | Chrome
Adguard version: | 1.4.1.
Adguard DNS: | None
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1200294

**Comment by Alex-302** [comment]
In other case ads will be shown.
