### ISSUE TITLE
www.idealo.de - Incorrect Blocking - Windows 

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6465]
***Description***:
* **Current behavior**: 

Annoyances filter (checked on our site - Mac OS) seems to break the website www.idealo.de 
When disabled website is loaded, when enabled - it`s a blank webpage

<details><summary>Screenshot:</summary>

![screenshot](https://user-images.githubusercontent.com/28784344/29682864-329d911c-8915-11e7-9e42-db7b2e7df6a9.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Mac OS 
Browser: | Chrome
Adguard version: | 1.4.1.
Adguard DNS: | None 
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1105236

**Comment by Alex-302** [comment]
Fixed
