### ISSUE TITLE
Samsung lockscreen wallpaper does not work

### ISSUE THREAD

**Issue by techIndia-hacker** [AdguardTeam/AdguardFilters#64666]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**:  Samsung lockscreen wallpaper does not refresh with new images due to blocking of in.api.glance.inmobi.com at DNS level and other filters. This domain is not a ad domain but provides client authorisation ids. Request to unblock it.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:   10 
Operating system version (Android/iOS) | ? Android
Browser:                               | ?
AdGuard version:   3.5 stable
Filters enabled:   adguard base, mobile ads, tracking protection, easy privacy, fanboy enhanced tracking, adguard social, annoyance filter, fanboy annoyance, adblock warning
AdGuard mode (Android only): Vpn          | VPN / Proxy (manual/auto)
Filtering quality (Android only):     High-quality
HTTPS filtering (Android only):      On
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
How to check it?

**Comment by techIndia-hacker** [comment]
Well u need a Samsung phone to check it. But I already tested it and found issue. Just whitelist in.api.glance.inmobi.com

**Comment by Alex-302** [comment]
Ok. Could you please write `package_name` of this app? 
If you unblock that domain using Assistant, suggested rule will looks like that:
`@@||in.api.glance.inmobi.com^$app=com.package.name`

**Comment by techIndia-hacker** [comment]
The package name is com.samsung.android.keyguardmgsupdator

**Comment by Alex-302** [comment]
Ok. Please chick with this exclusion only:
`@@||in.api.glance.inmobi.com^$app=com.samsung.android.keyguardmgsupdator`

**Comment by techIndia-hacker** [comment]
in.api.glance.inmobi.com will get blocked at DNS level probably. Will check

**Comment by techIndia-hacker** [comment]
Would like Mr cto @ameshkov to intervene in this matter as according to @Alex-302  "in.api.glance.inmobi.com" cannot be unblocked at dns level which is understandable as it's been marked as ad domain. But I can assure u that it's a false positive, no ads break in if whitelisted manually. More importantly Samsung lockscreen wallpaper will not work correctly ever if not unblocked in all Samsung users of adguard

**Comment by ameshkov** [comment]
@Alex-302 yeah, we'd better not block it by AdGuard DNS filter.

**Comment by Alex-302** [comment]
Added app-specific exclusion to mobile ads filter.
