### ISSUE TITLE
spiegel.de: anti-adblock overlay

### ISSUE THREAD

**Issue by JayBrown** [AdguardTeam/AdguardFilters#6466]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: on http://www.spiegel.de some articles (randomly selected? randomly inserted?) display an anti-adblocking overlay, which you can click away, but it returns every 10 seconds or so. One of the current articles is the following: http://www.spiegel.de/sport/fussball/ousmane-dembele-wechselt-angeblich-zum-fc-barcelona-a-1164440.html

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](http://i.imgur.com/oTHqyvc.jpg)
</details>

* **Expected behaviour**: there should be no anti-adblock overlay on the relevant webpages

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](http://i.imgur.com/LA8DazD.jpg)
</details>

***Steps to reproduce the problem***: go to the above mentioned webpage; might not work, if the anti-adblock code is randomly inserted into webpages

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | OS X 10.11.6
Browser: | Safari (latest)
Adguard version: | Adguard Desktop (latest)
Adguard DNS: | None
Adguard filters: | Adguard: English, Spyware, Social Media, Annoyances, Russian, German, Japanese, French, Dutch, Mobile Ads, Safari / EasyList: EasyList, EasyPrivacy, Fanboy's Social Blocking, Fanboy's Annoyances, Czech & Slovak, Germany, Italy, Icelandic ABP, void.gr, Fanboy's Enhanced Tracking / Other: Adblock Warning Removal, Anti-Adblock Killer (Reek), CJX's Annoyance, I don't care about cookies, Malware Domains, Peter Lowe's list, Prebake, Spam404
Ticket ID (if exists): | n/a

***ADDITIONAL NOTE***: also tested on Windows 7 with Firefox using Adguard freeware browser addon; same anti-adblock overlay behavior

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by JayBrown** [comment]
`spiegel.de###rVFtmFSlmG` removed the overlay on the above page, but other overlays keep popping up, e.g. on this page: http://www.spiegel.de/sport/fussball/champions-league-auslosung-reaktionen-vom-bvb-dem-fc-bayern-und-rb-leipzig-a-1164451.html … in this case `spiegel.de###NGWVPlqBXY` did the trick, but it might only work for that specific page.

**Comment by JayBrown** [comment]
Blocking also "similar elements" with `spiegel.de##.ua-detected,.ua-webkit` seems to work for now, but I don't know if it'll break something elsewhere. Will report back.

**Comment by XX-J** [comment]
Правило, для снятия антиадблока:
`spiegel.de/xml/xml-*.json`
`spiegel.de/*/spaab-*.js`   - на всякий случай

Удаление дополнительной рекламы:
`||adition.com/js/srp.js$important,third-party`  или удалить  `@@||imagesrv.adition.com/js/srp.js$domain=spiegel.de`
     или
`||adition.com/s?$script,important,third-party`  или удалить  `@@||adition.com/s?$script,domain=spiegel.de`

А вообще, я не понимаю, зачем нужны все ЭТИ исключения:
`@@||imagesrv.adition.com/js/srp.js$domain=spiegel.de`
`@@||adition.com/s?$script,domain=spiegel.de`
`@@||static.adfarm1.adition.com/ci.html$subdocument,domain=spiegel.de`
`@@||imagesrv.adition.com/banners/1337/files/$image,domain=spiegel.de`
`@@||imagesrv.adition.com/js/adition.js$domain=spiegel.de`
касающиеся НЕМЕЦКОГО домена Spiegel.de ?
И ещё больше не понимаю, почему ОНИ находятся в АНГЛИЙСКОМ фильтре?
(кстати, вот ещё одно: `@@||ad.yieldlab.net^$script,domain=spiegel.de`)

**Comment by Alex-302** [comment]
> Правило, для снятия антиадблока:

Спасибо, добавил.

> ||adition.com/js/srp.js$important,third-party

Добавил.

> А вообще, я не понимаю, зачем нужны все ЭТИ исключения:

Они из Изилиста подгружаются. Там иногда встречается дичь.
