### ISSUE TITLE
https://www.baidu.com/ - ads 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6467]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: Ads show up when searching with Baidu on iOS

The direct link to searxh resilts: [link](https://www.baidu.com/from=844b/s?word=%E6%81%92%E5%A4%A7%E5%9C%B0%E4%BA%A7&sa=ts_6&ts=6116834&t_kt=0&ie=utf-8&rsv_t=5ce6o4%252F2JxEeHOUsRdDRGkEsuDz5GKaYabb81vHirQEoJzGunu6F%252B3sp4A&ms=1&rsv_pq=2390985350955726548&ss=101&rq=heng%E2%80%86da&rqlang=zh&rsv_sug4=14889&inputT=14282&oq=%E8%82%A1%E9%AA%A8%E5%A4%B4%E5%9D%8F%E6%AD%BB
)

The last two entries are ads as they are signed with “广告”

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29703621-ee4467a6-897e-11e7-9eb9-89a933c6674a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.3.0.81
Simplified filters(iOS) | Off
Adguard DNS: | None 
Adguard filters: | 2 3 4 12 104 + mobile ads
Ticket ID (if exists): | 1614529

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@evgeniy-ADG please check this rule(ask user)
```
baidu.com##.ec_wise_ad
```

**Comment by evgeniy-ADG** [comment]
ok, done

**Comment by evgeniy-ADG** [comment]
It worked.

**Comment by Alex-302** [comment]
Ok. Added.
