### ISSUE TITLE
https://www.meleklermekani.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6469]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: Missed floating banner which I could not close + missed SM buttons here: https://www.meleklermekani.com/forums/

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29706890-07127144-898c-11e7-987e-e45d194dbfab.png)

![image](https://user-images.githubusercontent.com/15856304/29706903-0f8cf48e-898c-11e7-9527-a41b0c0d3d43.png)

</details>

***Steps to reproduce the problem***:

1. Go to https://www.meleklermekani.com/forums/
2. See the pop-up, scroll down to the very bottom to see the missed facebook button

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.3.0.81
Simplified filters(iOS) | Off
Adguard DNS: | None 
Adguard filters: | 2 3 4 11 12 13
Ticket ID (if exists): | 1395769

**Comment by Alex-302** [comment]
We don't block the `links` to the blogs.
Added to Annoyances filter
```
meleklermekani.com##.FloatingContainer

```
