### ISSUE TITLE
welt.de broken due to fix from #64461

### ISSUE THREAD

**Issue by terr72** [AdguardTeam/AdguardFilters#64699]
See https://github.com/AdguardTeam/AdguardFilters/issues/64461

**Comment by Alex-302** [comment]
answered

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/64744

https://github.com/AdguardTeam/AdguardFilters/issues/64461

https://github.com/AdguardTeam/AdguardFilters/issues/64699
