### ISSUE TITLE
http://torrent-games.net/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6471]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behaviour**: The link: http://torrent-games.net/news/rpg/2-0-15

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29707918-a6158576-898f-11e7-9cc1-f17f8ecd596b.png)

</details>

***System configuration***

Information | value
--- | ---
OS | Windows 7 x64
ADGUARD VERSION | Adguard в виде расширения у Chrome
FILTERS | Используемые фильтры: Русский фильтр, Английский фильтр, RU AdList, Фильтр раздражителей
AV | Dr.Web
ID | 1076701

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Background contains parts of design.
