### ISSUE TITLE
https://help.letyshops.ru/hc/ru - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6473]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behavior**: Clicking онлайн-чат link does nothing

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29709068-a9580f66-8993-11e7-8ef4-2e22b50d7163.png)

</details>

* **Expected behavior**: 

It opens the helper, see the screenshot

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29709249-519f6854-8994-11e7-8d8b-019d1d4de9d7.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | MacOS X
Browser: | Chrome
Adguard version: | 1.4.1
Adguard DNS: | None
Adguard filters: | Ru, En, De, social media, annoyances, safari, and mobile ads
Ticket ID (if exists): | 939612

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
In general we don't unblock these widgets, which are blocked by annoyances filter. But in this case we can do it, for help.letyshops.ru only.
