### ISSUE TITLE
welt.de breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#64744]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: I can’t play the video
`https://www.welt.de/wirtschaft/article216761868/Angela-Merkel-Wie-realistisch-sind-19-200-Infektionen-an-Weihnachten.html`

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.12
Filters enabled:                       | default + Adguard tracking protection + Adguard germany + Adguard Annoyances
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by krystian3w** [comment]
Force update AdGuard Annoyance: https://github.com/AdguardTeam/AdguardFilters/commit/07e7bc2269e530cdce79f79715dadf93df6de3d3 + https://github.com/AdguardTeam/AdguardFilters/commit/31ae521d0e3e2589bab793e2c2b58c3ea3b0ff45

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/64461#issuecomment-700067635

**Comment by krystian3w** [comment]
#64699

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/64744

https://github.com/AdguardTeam/AdguardFilters/issues/64461

https://github.com/AdguardTeam/AdguardFilters/issues/64699
