### ISSUE TITLE
gamepedia.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6475]
***Site***: https://pathofexile.gamepedia.com/index.php?title=The_Encroaching_Darkness&mobileaction=toggle_view_mobile
***Description***: Ad leftover on mobile.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29716058-2d4d0af4-89aa-11e7-9d0e-7104d4b6b974.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
