### ISSUE TITLE
No Filtering on URLs with German Umlaut

### ISSUE THREAD

**Issue by Berovowilare** [AdguardTeam/AdguardFilters#64751]
Hello 

Since a few years German Umlauts are possible for URLs. But your AdGuard doesn't filter it. Nor I can send a report over the normal way. It writes: The URL you entered is invalid or can't be parsed. You can submit your report manually here. And the URL is https://xn--zrimech-n2a.ch/. You see the ü in Züri missing .

The URL is https://zürimech.ch See the ü in Züri.

**Comment by krystian3w** [comment]
> You see the ü in Züri missing

converted to Punycode: https://en.wikipedia.org/wiki/Punycode / https://de.wikipedia.org/wiki/Punycode

for domain names you can't use punycode?

`xn--zrimech-n2a.ch##someting`


`||xn--zrimech-n2a.ch/someting$image`


---

or some like this is also broken:

`||github.com/*ü*/$all`

filter should block any repository/profile with `ü` in URL if GitHub support character in URL without simplify (delete Umlaut).

**Comment by BlazDT** [comment]
Working fine using xn--zrimech-n2a.ch
Not a filters issue anyway.
