### ISSUE TITLE
nontonanime.org - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6481]
***Site***: http://www.nontonanime.org/
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/29726380-c75e4ade-89cf-11e7-96f0-898d7aa925c5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
I can't reproduce, but please check this rule:
`@@||nontonanime.org/template/nontonanime.org/js/ads.js`

**Comment by danidoedel** [comment]
@AdamWr No more adblock detection for me as well...
