### ISSUE TITLE
legend.az -popups-

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6482]
**_Site_**: legend.az

***Description***: 1)Click something, you will get a new **POPUP**, This rule helps me to remove that: ||odbabo.info^$third-party

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by Alex-302** [comment]
Fixed,
