### ISSUE TITLE
Question about blocking ads

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardFilters#6483]
**_Site_**: http://www.harikadizi7.com/

***Description***: About 20 days ago the name of this site was: harikadizi6.com, and now they changed to: harikadizi7.com. And because of this current filters are not working for harikadizi7.com. If you change rules in the filterlist, they will work again, But there is an issue. The owner of this site will change the name of site from harikadizi7.com to harikadizi8.com after about 15-20 days. And in this case again you have to change rules. But can you do anything for automatic apply rules to a new harikadizi 8-X .com?

</br>

***System configuration:***

Information | value
--- | ---
Operating system: | **_Windows 10 (x64)_**
Browser: | **_Google Chrome (DEV)_**
Adguard version: | **_Adguard Browser Extension (BETA)_**
Adguard DNS: | **_None_** | 
Adguard filters: | **_English_**/ **_Russian_**/ **_Turkish_**/ **_Spyware_**/ **_Easy Privacy_**/ **_Annoyances_**/ **_Social media_**

**Comment by XX-J** [comment]
May be anything from this:
`harikadizi6.com,harikadizi7.com,harikadizi8.com,harikadizi9.com,harikadizi10.com,harikadizi11.com,harikadizi12.com,harikadizi13.com,harikadizi14.com##ANY_RULE`

**Comment by Alex-302** [comment]
> can you do anything for automatic apply rules to a new harikadizi 8-X .com?

no
