### ISSUE TITLE
https://www.gsmvezde.ru - false blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6484]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***:
* **Current behavior**: The slider is broken

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29743740-4e563440-8aa0-11e7-90d5-de0b1f0b903f.png)

</details>

* **Expected behaviour**: 

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29743742-56699b72-8aa0-11e7-9f1d-6fffab68c6cd.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: Android
Browser: | Chrome
Adguard version: | 2.9.136
Adguard mode (Android): | proxy, root
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On Default
Adguard DNS: | None
Adguard filters: | 2, 3, 4, 14, 1, 11
Ticket ID (if exists): | 1034043

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
