### ISSUE TITLE
http://www.sberbank.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6486]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

> Захожу на [сайт Сбербанка](http://www.sberbank.ru/ru/person) и нажимаю на картинку ипотека под 7.4%, начинает перекидывать на сайт и выдаёт ошибку загрузки страницы, так с включённым dns, если просто включён блокиратор в сафари то все открывается нормально, на андроид с включённым vpn, все открывается.

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29744741-1052df5e-8ab4-11e7-85ff-ec69739bd21a.png)

![image](https://user-images.githubusercontent.com/15856304/29744742-1846b88e-8ab4-11e7-8734-7774becad1ab.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | iOS
Browser: | Safari
Adguard version: | 1.3.1 
Simplified filters(iOS) | Off
Adguard DNS: | Default 
Adguard filters: | 1 2 3 4 12 15 116
Ticket ID (if exists): | 1474323

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в фильтр DNS:
`@@||track.rutarget.ru^`
