### ISSUE TITLE
mobile.donanimhaber.com

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardFilters#64870]
@nri82 commented on [Sun Sep 27 2020](https://github.com/AdguardTeam/AdguardForAndroid/issues/3600)

While use this [forum](mobile.donanimhaber.com) page shows a advertisement page and gives you 8 seconds and after redirect you to the page. If you don't want to wait 8 seconds you should click to the skipping button. But it's only works with firefox but not works with chrome or other chromium based browsers (Samsung internet, edge etc)

I have record a screen video

https://streamable.com/r2ro4q

Forum address mobile.donanimhaber.com

Android 10
Adguard 3.5

**Comment by zzebrum** [comment]
Base filter most probably

**Comment by AdamWr** [comment]
@nri82
Hi,
Added rule to fix this problem (update should be available in 1-2 hours), but that "advertisement page" with countdown shouldn't display at all with Turkish filter enabled.
Do you have `Turkish filter` and `AdGuard Mobile Ads` filter enabled?

By the way, I think that it would be better if you will report this issue using reporting tool - https://reports.adguard.com/new_issue.html

**Comment by nri82** [comment]
Thank you for your answer and solution. Turkish filter solved the problem.
I wasn't sure to open an bug here, my fault, sorry for the inconvenience,
thank you.

**Comment by AdamWr** [comment]
Ok, I'm glad that it works fine now.
Thank you for your answer.
