### ISSUE TITLE
 krsk.au.ru - Missed ads

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6490]
https://krsk.au.ru/

<details><summary>Screenshot:</summary>

<img width="434" alt="screen shot 2017-08-27 at 12 35 46 am" src="https://user-images.githubusercontent.com/27292111/29745307-d2cfc87a-8abf-11e7-810a-b85a87a5154a.png">

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Android 
Browser: | Chrome
Adguard version: | 2.9.136
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): | On (whitelist) 
Adguard filters: | 2, 3, 4, 14, 1, 11
Ticket ID: | 1332420

**Comment by Alex-302** [comment]
It seems that HTTPS filtering is not working on user's device. Please check cert name when you tap on green lock in the address bar.

**Comment by veronikasav** [comment]
Asked the user to specify whether the issue still persists.
