### ISSUE TITLE
saydiabetu.net - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6491]
http://saydiabetu.net/kontrol/zachem-nuzhen-dnevnik-samokontrolya-pri-saxarnom-diabete/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29745540-33fe76a4-8ac6-11e7-9aef-dd0bc8760153.png)

</details>

***System configuration***

Application version: 1.3.0.81
Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.28.49 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.97 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.29 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.11 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.55.66 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.38 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.56 Enabled=YES

Ticket ID: 1171353

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
