### ISSUE TITLE
http://www.jzrputtbut.net - Popup and anti adblcok

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#6493]
Hey
have anti anti adblcok abd Popup in site: http://www.jzrputtbut.net
no can Click in SKIP THIS AD with adgurd and have anti adblock
link exmple: http://www.jzrputtbut.net/A1JFs
Operating system: Windows 10 x64
Screenshot:  http://prntscr.com/g18fwy
Browser: Chrome
Adguard version: 6.1.331.1732

filter:
English filter
Annoyances filter
fanboys social blocking list
EasyLIstHebrew
adblock warning removal list
Anti-adblock Killer | reek

**Comment by AdamWr** [comment]
I can't reproduce antiadblock, but I was able to reproduce popups.
Added to English filter:
`jzrputtbut.net#%#var _initLbjs; Object.defineProperty(window, 'initLbjs', { get: function() { return _initLbjs; }, set: function(i) { _initLbjs = function(a, b) { b.AdPop = false; return i(a, b); }; } });`
Please, check the result.
