### ISSUE TITLE
Twitch ads not being blocked

### ISSUE THREAD

**Issue by Greigh** [AdguardTeam/AdguardFilters#64937]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Twitch ads are not being blocked by any filter

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<img width="1552" alt="Screen Shot 2020-10-02 at 11 02 48 AM" src="https://user-images.githubusercontent.com/57759540/94938455-d92ed100-049e-11eb-8df2-5a324a3ed650.png">

***Steps to reproduce the problem***:
Launch a stream at https://twitch.tv/silent

**Filters:**
[//]: # (Please enter the correct values for your case to the table below)
Information                            | Value
Operating system:                     | macOS Big Sur Beta 9 (20A5384c)
Browser:                               | Brave Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)
AdGuard version:                       | Version 2.5.0.896 nightly (CL-1.7.116)
Filters enabled:                       | Adguard Base, EasyList, Fanboy Anti-Facebook list, Adguard Annoyances, Adguard Warning Removal, NoCoin Filter. 
AdGuard DNS:                           | Default

**Comment by zloyden** [comment]
I don't see ads on Windows. @AdamWr @BlazDT please take a look.

**Comment by AdamWr** [comment]
Could you please update filters and then check again?

**Comment by Greigh** [comment]
<img width="1496" alt="Screen Shot 2020-10-05 at 8 17 01 AM" src="https://user-images.githubusercontent.com/57759540/95078519-4468e500-06e3-11eb-8c84-0f4e38843ef3.png">

Just updated filters with no luck.

**Comment by Greigh** [comment]
Ah just found the issue. It looks like Brave browser's ad blocking is somehow causing the ads to show. If I turn off the "Brave shields", AdGuard seems to successfully block ads. Not sure if this is something you can fix, but if not you are welcome to close this issue.

**Comment by AdamWr** [comment]
It's rather not easy.
As a workaround you could add this rule to user filter:
`||api.twitch.tv/api/*/access_token$removeparam=platform|player_type`
but I'm not sure if it will helps.

**Comment by Greigh** [comment]
I just removed "Brave Shields" from Twitch and it seems to be working. I'm perfectly fine with AdGuard's Privacy and Ad protection. I like Brave for the extra protection. But AdGuard will work :)

**Comment by AdamWr** [comment]
Okay, I'm glad that it works fine now :)
Thank you for your answer.

By the way, this rule `||api.twitch.tv/api/*/access_token$removeparam=platform|player_type` seems to works fine with Brave Shields enabled, at least on my end (with AdGuard for Windows).
