### ISSUE TITLE
Assistant disappears on adding exception rule

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6494]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Steps to reproduce the problem***: 
Open the AdGuard Assistant, click the "Add Exception" than "Advanced Settings", 
Disable the "Disable element hiding rules", click "Add exception". 
Page refreshes having applied the new rule and Assistant is gone. 
Reproduced on both Windows and Mac (6.1.331.1732 and 1.4.1) in Chrome. 

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )

***System configuration***

Information | value
--- | ---
Operating system: | Windows, MacOS
Browser: | Chrome
Adguard version: | 6.1.331.1732, 1.4.1
Ticket ID (if exists): | 1549411

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is not a filter's issue.
Write to https://github.com/AdguardTeam/AdguardAssistant
or wait for new version in AdGuard 6.2
