### ISSUE TITLE
greatdaygames.com - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6495]
http://www.greatdaygames.com/games/play/word-craft/word-craft.aspx

There is an ad in the player and the game doesn't load. When I turn off WFP driver Adguard Assistant icon disappears.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29750169-c2904474-8b43-11e7-9436-4529031e87f0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 
Browser: | Chrome
Adguard version: | 6.1
Adguard driver (Windows): | WFP
Stealth mode options(Windows) | disabled
Adguard filters: | 1, 2, 3, 4, 14
Ticket ID: | 1619413

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
