### ISSUE TITLE
[nsfw] imgskull.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6496]
Reproduce:
Open http://imgskull.com/explore and click on random image. 
Click on **ENTER**
![image-20170827-004](https://user-images.githubusercontent.com/9846948/29750359-bc46e0c8-8b3e-11e7-901b-1c67fc9a967b.png)
ADS [censored]
![image-20170827-005](https://user-images.githubusercontent.com/9846948/29750390-4cdeaeb8-8b3f-11e7-8500-3789cb40af13.png)
![image-20170827-006](https://user-images.githubusercontent.com/9846948/29750391-4ce39ba8-8b3f-11e7-8783-0348028546e6.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by AdamWr** [comment]
Fixed.
