### ISSUE TITLE
sport.mail.ru - blocked subscription modal

### ISSUE THREAD

**Issue by vitalkanev** [AdguardTeam/AdguardFilters#6497]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: Adguard blocks the subscription modal from `sport.mail.ru` with Adgaurd Enabled, 
 authorized as my account
* **Current behaviour**: The modal blocked and only a `X` button shown

[//]: # (Tell us what happens)
[//]: # (Опишите проблему)

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можно вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![2017-08-27-171050_1366x768_scrot](https://user-images.githubusercontent.com/18398761/29750584-d694987e-8b4a-11e7-8fb8-2b73a833d1c0.png)

</details>

* **Expected behaviour**: They should be...

[//]: # (Tell us what should happen instead)
[//]: # (Опишите ожидаемый результат)
<details><summary>Screenshot:</summary>

![2017-08-27-170806_1366x768_scrot](https://user-images.githubusercontent.com/18398761/29750556-56cf028c-8b4a-11e7-8afd-340a419df5f4.png)

</details>

***Steps to reproduce the problem***:

1. Open `sports.mail.ru` and scroll down
2. Click the `Подписка` link
3. There we go...

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Linux - Lubuntu Zesty
Browser: | Yandex 17.6.1 *Beta*
Adguard version: | 2.6.7 Browser Extension
Adguard filters: | See bellow
Ticket ID (if exists): | `undefined`

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

<details><summary>Filters Screenshot from Lubuntu Zesty:</summary>

![Filters](https://user-images.githubusercontent.com/18398761/29750538-0826e140-8b4a-11e7-842c-34da294664ad.png)

</details>

**Comment by Alex-302** [comment]
Fixed.
