### ISSUE TITLE
https://pikabu.ru/ - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6498]
https://pikabu.ru/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29751451-312885ce-8b56-11e7-8059-7380614ed596.png)

</details>

***System configuration***

Information | value
--- | ---
OS | Windows 7 x64
ADGUARD VERSION | Adguard в виде расширения у Chrome
FILTERS | Используемые фильтры: Русский фильтр, Английский фильтр, RU AdList, Фильтр раздражителей
AV | Dr.Web
ID | 1076701

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce.
Is HTTPS filtering works?
Try to disable RU AdList for test.

**Comment by XX-J** [comment]
1:   `pikabu.ru##a:has(#branding_ad_header)`
2:   `pikabu.ru##a:has(#branding_ad_comment)`
3:   `pikabu.ru##a:has(#branding_ad_footer)`

![123](https://user-images.githubusercontent.com/17948007/29773528-8ea6c458-8c06-11e7-8bd5-66cda499e373.jpg)
___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard legacy v2.7
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Поправил.
