### ISSUE TITLE
[nsfw] [popup] shooshtime.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6499]
Reproduce:
Open shooshtime.com and click on random video. 
Sample: `http://shooshtime.com/videos/babe/another-slam-fest-with-that-perfect-amateur_156600/`
Play video. Popup will show up.

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by AdamWr** [comment]
Fixed.

**Comment by FadeMind** [comment]
@AdamWr  @Alex-302 please reopen. Ads box return on right side of site.
Sample site http://shooshtime.com/galleries/shooshtime-s-dirty-30-october-10th_157366/35d260/

**Comment by AdamWr** [comment]
Fixed.
