### ISSUE TITLE
letras.mus.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#65005]
[https://www.letras.mus.br/caetano-veloso/44716/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.letras.mus.br/caetano-veloso/44716/)

![cookie](https://user-images.githubusercontent.com/35470489/95004407-feb3fb80-05c0-11eb-9717-13d69e72c57b.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by adranger** [comment]
@AdamWr They have another domain with the same layout: [https://www.letras.com/caetano-veloso/44716/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.letras.com/caetano-veloso/44716/)

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
