### ISSUE TITLE
www.typetopia.com - Audio file URL blocked

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6500]
http://www.typetopia.com/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29751547-793b89dc-8b57-11e7-8c3d-e7e1bafab3c2.png)

![image](https://user-images.githubusercontent.com/27292111/29751554-92b572e2-8b57-11e7-9a0c-8b5222711d10.png)

</details>

***Steps to reproduce the problem***:

If I try to open the URL directly (https://app.typetopia.com/media/ad/14/77fa883630c0d6a59872401eabfc/ad1477fa883630c0d6a59872401eabfc.mp3), it will first show a little in-browser player. But I can’t actually play the file.

Ticket ID: 1617772

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by florisvlasveld** [comment]
Could I suggest changing the title to 'Audio file URL blocked' to clarify that not the entire site is blocked but just certain audio file URLs?

**Comment by Alex-302** [comment]
@florisvlasveld Hi. Is it a part of advertising or just background music in the game?

**Comment by florisvlasveld** [comment]
Just background music.

**Comment by Alex-302** [comment]
ok
Added to English filter
```
@@||app.typetopia.com/media/ad/*.mp3|
```
