### ISSUE TITLE
How to block ads in Google Search widget? 

### ISSUE THREAD

**Issue by Zardangus** [AdguardTeam/AdguardFilters#65014]
Hi all,

I use a new launcher on my Android device, and I have set the Google Search widget, so it is not an app, i can't find it it the app's setting in Adguard's setting.
When I use this widget, I have ads on the internet pages. What's the way to block them ?

Thank you,
regards.

**Comment by BlazDT** [comment]
I guess you are talking about the search bar at bottom of Android. I cannot see any ads in search when I searched for different elements.

The used app is called "com.google.android.googlequicksearchbox" aka Google.
