### ISSUE TITLE
How to blacklist a link with Adguard? 

### ISSUE THREAD

**Issue by Zardangus** [AdguardTeam/AdguardFilters#65015]
Hi again,

When i use Firefox or Kiwi browser on my Android device, I have sometimes ads who oppen a new tab (Adguard is On but doesn't block them).

Is there a way to add those link in a blacklist with Adguard ?

Merci.

**Comment by BlazDT** [comment]
You can try these rules, but better report the sites with popunders (please note iOS is very restricted):

||url.com^$popup

**Comment by Zardangus** [comment]
> You can try these rules, but better report the sites with popunders (please note iOS is very restricted):
> 
> `||url.com^$popup`

Hi, thank you for Reply.

What's the way to report those sites ?

Regards.

**Comment by BlazDT** [comment]
https://reports.adguard.com/new_issue.html

**Comment by Zardangus** [comment]
> https://reports.adguard.com/new_issue.html

Thank you.

I have installed Google news. When I read news with this app, adds are blocked but I have à message saying "we can't display this link..."
Here is à Screenshot.
![Uploading Screenshot_20201010_230506_com.google.android.apps.magazines.jpg…]()

How to fixe that? It is very ugly :(

**Comment by BlazDT** [comment]
Not fixable.
