### ISSUE TITLE
Questions about filtering baidu.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6503]
> When I use the rule: `@@*$third-party,domain=~baidu.com` , it does not work. But, when I use the rule: `@@/.*/$third-party,domain=~baidu.com`, it does work. I think this is not normal, please check it.

and 

> When I use the `||baidu.com^$replace` rules, I must think about if it can make a breach on the defence wall, eg. it can affect the block rules, for example: `||baidu.com^`, after "replace", these block rules become not work. I think it is the problem of Priority. I come from China, in our country, there is a soft do better on this which named "adbyby", for example: when I use `||baidu.com^$S@/.*/@@` , I do not need to think about if it can affect other rules.

The ID of the requester: 1570163

**Comment by Alex-302** [comment]
> @@*$third-party,domain=~baidu.com

This rule is too wide. Adguard ignores them, but can't cover all cases.
User can use `@@|http$third-party,domain=~baidu.com`

> When I use the ||baidu.com^$replace rules

User can try 6.2 beta.

**Comment by vitbortnik** [comment]
@Alex-302 Any comments on this? Thanks in advance! 

> when i use "baidu.com##.ec_wise_ad", it do not work any more . after i
check it again , i discovery that because this site used "!important"
css , it can make adguard's rules to be invalid . please check it.

> the "!important" which writed as style can make adguard's css rule to
be invalid.

**Comment by Alex-302** [comment]
I don't understand what does he mean.
