### ISSUE TITLE
vpn-anbieter-vergleich-test.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#65041]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Overlay. When i close this overlay a small window popup appears
`https://vpn-anbieter-vergleich-test.de`
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="826" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/95022517-25813900-0678-11eb-929c-cb589439f9e8.PNG">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.12
Filters enabled:                       | default + Adguard tracking protection + Adguard germany + Adguard Annoyances
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by JobcenterTycoon** [comment]
The overlay is back

**Comment by zloyden** [comment]
Not reproduced on my end with German IP. @AdguardTeam/filters-maintainers please take a look.

**Comment by BlazDT** [comment]
Same.

**Comment by JobcenterTycoon** [comment]
ok i can’t reproduce too ... it got fixed without adding new filters very good
