### ISSUE TITLE
distrowatch.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6504]
https://distrowatch.com/
![image-20170827-008](https://user-images.githubusercontent.com/9846948/29752394-5040a44e-8b5d-11e7-9795-d8a8f95005e9.png)

https://distrowatch.com/weekly.php?issue=20170807
![image-20170827-009](https://user-images.githubusercontent.com/9846948/29752401-71feb922-8b5d-11e7-97ec-f602a12bf1b4.png)
![image-20170827-010](https://user-images.githubusercontent.com/9846948/29752419-dbc76a70-8b5d-11e7-8c20-f247c0198c07.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
distrowatch.com##td[style="width: 19%; vertical-align: top; border: none"] > table[class="News"]+br+table[width="100%"]
distrowatch.com##td[style^="width: 20%; vertical-align: top; border: none;"] > table[class="News"]+br+table[class="Info"]
```
