### ISSUE TITLE
 [adblock detect] di.fm

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6506]
https://www.di.fm
![image-20170828-002](https://user-images.githubusercontent.com/9846948/29767763-f6f281dc-8be3-11e7-94d7-51a300124ef6.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by AdamWr** [comment]
Could you please check this rule:
`di.fm#$#.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links {display:block!important;}`

**Comment by FadeMind** [comment]
Seems working fine. IF this will be not working I will report feedback ASAP (need some more time of listening). Thank you @AdamWr

**Comment by Alex-302** [comment]
Added + JS rule for FuckAdBlock
