### ISSUE TITLE
Stocks, Forex, Futures & News app - big popup

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6507]
[//]: # (***You can leave the strings with "[//]:" They will not be added to the issue text)
[//]: # (***Строки, которые начинаются с "[//]:" можно не удалять. Они не будут видны)

***Description***: "Big fullscreen popup when opening investing app."

[//]: # (use the following code. Replace exciting URL by your. Also, you can paste image from clipboard. It will be automatically loaded.)
[//]: # (используйте данный код. Замените существующий адрес адресом вашего скриншота. Также изображение можено вставить из буфера обмена. Оно будет автоматически загружено. )
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/29773142-bb92adf8-8c04-11e7-8d17-9d7e4a736394.png)
</details>

***Steps to reproduce the problem***:
[https://play.google.com/store/apps/details?id=com.fusionmedia.investing](https://play.google.com/store/apps/details?id=com.fusionmedia.investing)

[//]: # (Describe, how to reproduce the issue)
[//]: # (Перечислите шаги для воспроизведения проблемы)

***System configuration***

Information | value
--- | ---
Operating system: | Android
Adguard version: | 2.10.16
Adguard mode (Android): | VPN
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On
Adguard filters: | 2, 3, 4, 14, 16, 5, 11, 113, 211
Ticket ID (if exists): | 1063185

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. Please ask for HAR file.
