### ISSUE TITLE
makeuseof.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6508]
http://www.makeuseof.com/tag/oneplus-5-review/

Scroll down to second article. Sometimes youtube player is not loaded at all (BLACK), sometimes next article is not loaded too.

![image-20170828-011](https://user-images.githubusercontent.com/9846948/29784081-fd2a1738-8c22-11e7-9cdd-37b4274ec87c.png)
![image-20170828-012](https://user-images.githubusercontent.com/9846948/29784085-01749cf0-8c23-11e7-8257-5a9f5d2bc528.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
It works on my side.
@AdamWr please check it.

**Comment by FadeMind** [comment]
First Video thumbnail from YT is loaded fine:
![image-20170829-004](https://user-images.githubusercontent.com/9846948/29825200-edab0054-8cd3-11e7-803e-d16c5e7c6458.png)
Video thumbnail in second article under is not loaded - black box
![image-20170829-003](https://user-images.githubusercontent.com/9846948/29825227-090a25e6-8cd4-11e7-8690-5ce0e2b5cd22.png)

**Comment by AdamWr** [comment]
Ok, I can reproduce.
Added to English filter:
`@@||static.h-bid.com/prebid/*/prebid.js$domain=makeuseof.com`
`@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$domain=makeuseof.com`
