### ISSUE TITLE
[nsfw] pornhub.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6510]
![image-20170828-015](https://user-images.githubusercontent.com/9846948/29786993-881848f6-8c2d-11e7-853e-0610d6d9927f.png)

Open any video on site. Empty banner is under Player. 

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
Added to English filter
```
pornhub.com##.video-wrapper > div#player~div[class$=" hd clear"]
```

**Comment by FadeMind** [comment]
Please reopen.

Start play any video on pornhub.com - you can skip to lastest seconds. Wait until video will stop playing. Banner:
![image-20170830-012](https://user-images.githubusercontent.com/9846948/29874943-9e846cac-8d98-11e7-9298-6fff682dd54a.png)

![image-20170830-013](https://user-images.githubusercontent.com/9846948/29875117-315a1766-8d99-11e7-9cbf-b44ffdf6a61b.png)


CC @Alex-302  @AdamWr

**Comment by Alex-302** [comment]
Added fix for the app.
