### ISSUE TITLE
Подозрение на рекламу https://24smi.org/celebrity/4134-konor-makgregor.html

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#6511]
Реклама блокируется, но мешается вот эти вот окна, которые занимают всю страницу. Их несколько. С этим можно что-то сделать? @Alex-302, попробуй перейти на сайт, проблема у тебя должна тоже быть. https://24smi.org/celebrity/4134-konor-makgregor.html

**Comment by ministr91** [comment]
![screenshot_2017-08-28-21-21-57](https://user-images.githubusercontent.com/22351242/29787329-2a8baec6-8c37-11e7-8eaf-aff2a3496f76.png)
![screenshot_2017-08-28-21-22-01](https://user-images.githubusercontent.com/22351242/29787336-2f9ef5e4-8c37-11e7-8185-31d1ce5b156a.png)

**Comment by Alex-302** [comment]
Поправил.
Скрины масштабируй перед загрузкой, или под спойлер прячь

```
<details>

![image]()
</details>
```

**Comment by ministr91** [comment]
ок
