### ISSUE TITLE
"CastBox" and "RadioBox" apps - Ads - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6512]
***Description***:
* **Current behavior**: 
There are ads in the "CastBox" and "RadioBox" apps on Android, we couldn`t reproduce it from our end.

<details><summary>Screenshot:</summary>

![screenshot_20170827-002402](https://user-images.githubusercontent.com/28784344/29792492-40279044-8c49-11e7-8af4-a3bc162aa18d.png)

</details>

<details><summary>Screenshot:</summary>

![screenshot_20170827-002103](https://user-images.githubusercontent.com/28784344/29792508-4469131c-8c49-11e7-91d5-c62bf301c879.png)

</details>
***System configuration***

Information | value
--- | ---
Operating system: | Android 
Adguard version: | 2.9.136
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality 
HTTPS filtering (Android): |  On (Default) 
Adguard filters: | 2, 3, 4, 14, 10, 1, 11
Ticket ID (if exists): | 1617682

logs:
[debug (1).txt](https://github.com/AdguardTeam/AdguardFilters/files/1258301/debug.1.txt)

**Comment by Alex-302** [comment]
HTTPS filtering is not enabled.
Please check these rules:
`||graph.facebook.com^$app=fm.castbox.radio.music|com.adguard.android.FilteringLog`
