### ISSUE TITLE
http://www.doctorate.ru/chicory-benefits-harms/ - Ads - Android

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6513]
***Description***:
* **Current behavior**: 

There is ad on http://www.doctorate.ru/chicory-benefits-harms/ on Android
reproduced on our side
<details><summary>Screenshot:</summary>

![s70828-101809](https://user-images.githubusercontent.com/28784344/29793272-ef39a124-8c4b-11e7-999d-e7db3e8a0e99.jpg)

</details>

***System configuration***

Information | value
--- | ---
Operating system: |  Android 
Browser: | Chrome
Adguard version: | 2.10- beta
Adguard mode (Android): | VPN 
Filtering quality (Android): | High-quality
HTTPS filtering (Android): |  On (Default) 
Adguard filters: | 0,1,2,3,4,11,14
Ticket ID (if exists): | 1617753

**Comment by Alex-302** [comment]
fixed
