### ISSUE TITLE
electrek.co - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6514]
https://electrek.co/2017/08/26/a-look-at-teslas-latest-autopilot-2-0-software-update/

<details><summary>Screenshot:</summary>

<img width="364" alt="screen shot 2017-08-29 at 8 38 29 am" src="https://user-images.githubusercontent.com/27292111/29805986-78c7a5be-8c95-11e7-9f2f-8a52a89844e8.png">

</details>

***System configuration***

Application version: 1.3.0.81
Device: iPhone
Platform: iOS
OS: 10.3.2

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.29.7 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.13 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.56 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.48 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.33 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.49 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.58 Enabled=YES

Ticket ID: 1619441

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Also can't reproduce(iPad).
@zebrum please check it on iphone

**Comment by zebrum** [comment]
@veronikasav update user AdGuard app to 1.3.1 please
can not reproduce
