### ISSUE TITLE
Make this repo Hacktoberfest-compatible according to its new rules

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#65152]
### Prerequisites

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

In the past 3-ish years, the Hacktoberfest has been an event where GitHub and DigitalOcean got together to nominally celebrate open-source and its contributors from all walks of life, though in practice it has been a giveaway of free T-shirts and stickers to the ~75,000 first GitHub users to submit 4 PRs to almost any repo.

However, Hacktoberfest in 2020 has been a colossal mess of proportions, with its rules being changed *twice* mid-event in the past 4 days, the most recent of which stipulated that PRs did not count towards the user's tally unless 1) the GitHub repo was tagged with `hacktoberfest`, or 2) every single pull request that did not seem like spam was labelled by the repo owners with `hacktoberfest-approved`, as per https://hacktoberfest.digitalocean.com/hacktoberfest-update

So if we as an adblocker community were to want to give contributors the chance to win free T-shirts, either of the 2 approaches above would have to be implemented by you guys. №1 would take ~20sec, presuming we find it to be worth the effort to continue to support Hacktoberfest after these very huge changes they've done now.

### Proposed Solution

In the repo tags, which currently show `adguard`, `adblock`, `ublock`, `filter-list` and `open-source`, an additional tag named `hacktoberfest` should be added.

### Alternatives Considered

Either label all non-spam PRs you receive until mid-November as `hacktoberfest-approved`, or decide that Hacktoberfest can go fly a kite due to the confusing 2020 edition of it.

### Additional Information

I mostly only need the T-shirt reward so I can give it as an annual holiday gift to one of my siblings. I've never wanted to use branded T-shits with words on them myself.

This request also applies to the repos of AdGuard Home and AdGuard DNS Filter.

**Comment by ameshkov** [comment]
Done, thank you!

@Alex-302 let's not forget to remove it in November
