### ISSUE TITLE
healthline.com - Missed ad placeholders

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6516]
http://www.healthline.com/health/allergies/gluten-food-list#overview1

To hide those elements user uses:

healthline.com##div.mlb
healthline.com##div.mmr.row

<details><summary>Screenshot:</summary>

<img width="397" alt="screen shot 2017-08-29 at 9 16 13 am" src="https://user-images.githubusercontent.com/27292111/29807031-bca14be6-8c9a-11e7-8d6d-4f720598eca4.png">

</details>

***System configuration***

IApplication version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.29.7 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.56 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.48 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.49 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.58 Enabled=YES
Ticket ID : 1608099

[//]: # (***Filters list - comma separated list, or filter names outside the table)
[//]: # (***Список фильтров - названия через запятую, или список вне таблицы)

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added
