### ISSUE TITLE
majesy.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#65172]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Anti Adblock
`https://majesy.com` `https://magesy.eu/` `https://magesy.blog/` `https://magesy.pw/`
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="784" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/95246664-184d8100-0815-11eb-8370-e3009c167dd8.PNG">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.12
Filters enabled:                       | default + Adguard tracking protection + Adguard germany + Adguard Annoyances
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back

**Comment by AdamWr** [comment]
This time I can't reproduce it.
Could you please write steps how to reproduce it and provide direct link?

**Comment by JobcenterTycoon** [comment]
oh i see its not listed here `https://majesy.org/`

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
Thank you.

**Comment by JobcenterTycoon** [comment]
Anti Adblock back on

`https://magesy.blog`
`https://majesy.org`
`https://magesy.eu`
`https://magesy.fr`
`https://magesy.pw`
`https://majesy.com`
`https://magesy.eu`

**Comment by AdamWr** [comment]
Fixed.

**Comment by JobcenterTycoon** [comment]
I get Anti Adblock again on

`https://majesy.org/`
`https://magesy.eu`
`https://magesy.fr`
`https://magesy.pw`
