### ISSUE TITLE
http://tvarticles.me/ - anti-adblock script

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardFilters#6520]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**:  http://tvarticles.me/vid.php?id=655632

[//]: # (Substitute this line with a description of the problem)

[//]: #
![image](https://user-images.githubusercontent.com/30834067/29848396-f4591030-8d28-11e7-81ed-2bee6e99c6c8.png)

<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Mac OS
Browser:                            | Chrome
AdGuard version:                    | 1.4.1
Filters enabled:                    | 1 2 3 4 5 14
Stealth mode options (Windows only) | ?
Helpdesk ID (if exists):            | 1531498
[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce.  Please provide link to the page.

**Comment by evgeniy-ADG** [comment]
http://tvarticles.me/vid.php?id=655632

**Comment by Alex-302** [comment]
Fixed.
