### ISSUE TITLE
https://www.macbed.com/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6521]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behavior**: The link: https://www.macbed.com/download/30631.html

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29861140-ef5a7d1a-8d70-11e7-9d5c-95e9cc95e56e.png)

</details>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   |  Windows
Browser:                            | Chrome
AdGuard version:                    | the latest release
Filters enabled:                    |  English, Russian, social media, spyware, annoyances
AdGuard DNS:                        | Default
Stealth mode options (Windows only) | Off
Helpdesk ID (if exists):            | none

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
