### ISSUE TITLE
www.unilad.co.uk

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6522]
Missing RECOMMENDED box entries

https://www.unilad.co.uk/tv/bran-may-have-just-confirmed-a-popular-game-of-thrones-theory/

![image-20170830-001](https://user-images.githubusercontent.com/9846948/29863843-242ce924-8d71-11e7-9d98-aa8352b9ab37.png)

**WITHOUT** adguard looking:
![image-20170830-002](https://user-images.githubusercontent.com/9846948/29863894-58acc2d2-8d71-11e7-9fd1-9bd20ef2a90c.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by AdamWr** [comment]
This content is loaded by outbrain script, so from what I know it is intentionally blocked by Spyware filter.
Added to Spyware filter:
`unilad.co.uk###sidebar > #text-64 > .block-title`
to hide this RECOMMENDED box.
