### ISSUE TITLE
https://www.jazzradio.com/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6524]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: the link: https://www.jazzradio.com

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29868887-5e246734-8d89-11e7-8594-5ca4003767c3.png)

</details><br/>

***Steps to reproduce the problem***:

1. Go to https://www.jazzradio.com/
2. Register (it's quick and does not require an email confirmation)
3. Start playing
4. When a composition ends, the banner pops up asking to disable the ad blocker

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10
Browser:                            | Chrome
AdGuard version:                    | the latest beta
Filters enabled:                    | Russian, English, Social media, Annoyances, Reek, Spyware
AdGuard DNS:                        |  Default
Stealth mode options (Windows only) | off
Helpdesk ID (if exists):            | 1395913

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce
http://imagizer.imageshack.com/img922/8479/IlkR3P.png
@AdamWr

**Comment by AdamWr** [comment]
I registered and listened 4 songs and I can't reproduce.

**Comment by AdamWr** [comment]
Nevermind, reproduced after two more songs.

**Comment by AdamWr** [comment]
Could you please ask user if this rule help?
`jazzradio.com#$#.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links {display:block!important;}`

**Comment by vitbortnik** [comment]
@AdamWr 
It worked just fine for the user. 

> Здравствуйте!
Тестировал в течение 4 часов, правило работает.
Большое спасибо!

**Comment by AdamWr** [comment]
Thank you.
Added to English filter.
