### ISSUE TITLE
English filter blocks comments in the official Reddit app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6525]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

* **Current behavior**: Adguard sometimes blocks the comment section of the official Reddit
app. As you can see on the screenshot, it keeps loading. Not even after 5 min, it loads! Sometimes it does, sometimes it does, but when I disable Adguard, it loads the comment section immediately, always! The English filter and simplified domain name filter cause the issue. Most likely because the simplified filter has the English filter. 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29869974-f75960fe-8d8d-11e7-84c8-a27370dd738c.png)

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Android
Browser:                            | none
AdGuard version:                    | 2.9.70
Filters enabled:                    | 2, 3, 4, 14, 16, 8, 11
AdGuard mode (Android only):        | VPN
Filtering quality (Android only):   | Speedy
HTTPS filtering (Android only):     | On (Default/)
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1619430

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Reproduced without Adguard
![image](https://user-images.githubusercontent.com/8361299/29872086-c2700c86-8d96-11e7-92e5-0bc463554a55.png)
