### ISSUE TITLE
google video blocked by bad filter

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#65268]
shows filter is com^ which is blocking googlevideo
![E96AEACB-BF4C-4AB5-8237-A2C1EEA4F8A6](https://user-images.githubusercontent.com/71462072/95424442-4069dc80-0908-11eb-9d64-1ab979c2ef85.png)

**Comment by DandelionSprout** [comment]
The entry doesn't seem to be in AdGuard DNS Filter as of its v2.0.11.65. Normally I'd have recommended a simple list refresh sync, which I however know is sadly not a trivial thing to do on brand-new installations of AdGuard for Android, especially if the 🔁 symbol on the upper right of the dashboard frontpage doesn't sync them properly.

**Comment by Yuki2718** [comment]
Matched rule is `com^`?? Something must be wrong.

**Comment by jordanelliott23** [comment]
it must have been a glitch. it doesn't block it now.  hmm. that was odd though.

**Comment by DandelionSprout** [comment]
There have been cases where EasyList, EasyPrivacy or EasyList-owned regional lists have had problems with their auto-fetching of new domains (Case in point: https://github.com/easylist/easylist/commit/e743258656e35c2369b0f3bd155472c973dbe544), and those lists are where AdGuard DNS Filter gets ~97% of its entries from.

It got to the point where uBlock Origin had to introduce some "anti-'Really bad accidental entries'" measures a couple months ago.

**Comment by zloyden** [comment]
> it must have been a glitch. it doesn't block it now. hmm. that was odd though.

Not reproduced on my end, but that was strange. I'll close it for now.
