### ISSUE TITLE
http://postimage.co.nr/ - anti-adblock scrypt

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6526]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: Go to http://postimage.co.nr/2017/8/samsung/8.html and click Next several time

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29870889-56d819f4-8d92-11e7-9abd-8f428e63f5eb.png)

</details><br/>

***System configuration***

**Filters:**

- Subscriptions: FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
- FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt
- FilterId:14 Name: Annoyances filter Url: https://filters.adtidy.org/extension/chromium/filters/14.txt
- FilterId:207 Name: Adblock Warning Removal List Url: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
- FilterId:211 Name: Anti-Adblock Killer | Reek Url: https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
- FilterId:215 Name: Fanboy's Enhanced Tracking List Url: https://secure.fanboy.co.nz/enhancedstats.txt
- FilterId:229 Name: I don't care about cookies Url: http://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/
- FilterId:0 Name: User filter Url: no_url

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | windows
Browser:                            | chrome
AdGuard version:                    | the latest beta
AdGuard DNS:                        | Default 
Helpdesk ID (if exists):            | 1518164

**Comment by Alex-302** [comment]
It seems that this site is fake postimg.org. Image is located on postimg.org, but loaded in IFRAME, which is loaded from third-party site - extraimago.atwebpages.com

**Comment by Alex-302** [comment]
You can send these rules to user
```
@@||postimage.co.nr^$generichide
@@||extraimago.atwebpages.com^$generichide
```

**Comment by im3or** [comment]
Thanks, this works.
