### ISSUE TITLE
b-shooter.com (N: uBlock Origin) (T: Ads) (NSFW)

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#65275]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

A pretty large amount of third-party-hosted advertising banners, possibly even malvertising ones. (While the site itself is NSFW, the screenshot below is not.)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/95434206-4637e000-0951-11eb-961b-24c61ba07f7e.png)
</details><br/>

* **Expected behaviour**: 

The banners are blocked.

***Steps to reproduce the problem***:

1) Visit `b-shooter.com`.

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/95434491-9adb5b00-0951-11eb-89a8-ea7309673995.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | May 2020 Update
Browser:                               | Chrome x64
AdGuard version:                       | uBlock Origin 1.30.1b7 + uBlock Origin Extra 2.88 + IDCAC 3.2.2
Filters enabled:                       | See screenshot above.
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Yuki2718** [comment]
It'll be best if can be fixed in upstream i.e. EL China. @cjx82630 Can you take a look? Scripts starting from (IP)/acc*.

**Comment by cjx82630** [comment]
Fixed.Please manually update in 30 minutes

**Comment by Yuki2718** [comment]
@cjx82630 Thanks!
