### ISSUE TITLE
http://www.gsmarena.com/ - Ads - Windows 

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6527]
***Description***:
* **Current behaviour**: 

Ads on http://www.gsmarena.com/ on Windows
Reproduced on our side ( Mac OS)

<details><summary>Screenshot:</summary>

![screen shot 2017-08-30 at 4 08 05 pm](https://user-images.githubusercontent.com/28784344/29873860-917fa210-8d9d-11e7-845d-20257f75f70c.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | MAC OS
Browser:                            | CHROME
AdGuard version:                    | 1.4.1.
Filters enabled:                    | 0,1,2,3,4,14
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1618911

**Comment by Alex-302** [comment]
Not reproduced.
Added to English filter
```
gsmarena.com###topAdv
```
Please check.

**Comment by Alex-302** [comment]
@ypetruk

**Comment by ypetruk** [comment]
@Alex-302 I checked for the filter updates - and the ad comes through from time to time
try reloading the page for several times

**Comment by FadeMind** [comment]
@Alex-302 `gsmarena.com###topAdv` did not fix this (on my side box with polish language - green)
![image-20170830-018](https://user-images.githubusercontent.com/9846948/29881998-14535660-8dac-11e7-8d6f-c00cc4812f58.png)

**Comment by AdamWr** [comment]
I can reproduce.
Added to English filter:
`||cdn.gsmarena.com/vv/assets*/js/_pf-*.js`
`gsmarena.com#%#Object.defineProperty(window,'adonisConnType',{get:function(){},set:function(){throw'Adguard: stopped a script execution.'}});`
