### ISSUE TITLE
http://7tor.download - redirects - Windows

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6528]
***Description***:
* **Current behaviour**: 

user asks to add browser protection
http://7tor.download/ This site shares not friendly code, if you allow
javascript.. browser redirects without user permission to
http://adplexmedia.adk2x.com..

***System configuration***

**Filters:**

Information                         | Value
---                                 | ---
Operating system:                   | Windows
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 2,4,208,233,0
Stealth mode options (Windows only) | enabled
Helpdesk ID (if exists):            | 1621209

**Comment by Alex-302** [comment]
Fixed
