### ISSUE TITLE
http://file.up09.com - Popup

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#6529]
Hey
have Popup in site: http://file.up09.com
in click on "free download" / "download" and in all button in site.
link exmple: http://file.up09.com/w0dq88k3b5ro
Operating system: Windows 10 x64
Screenshot:  http://prntscr.com/gf6nny
Browser: Chrome
Adguard version: 6.1.331.1732

filter:
English filter
Annoyances filter
fanboys social blocking list
EasyLIstHebrew
adblock warning removal list
Anti-adblock Killer | reek

**Comment by Alex-302** [comment]
Fixed

**Comment by MrTal** [comment]
@Alex-302 
now no can click on "free download" / "Premium Download"

**Comment by Alex-302** [comment]
Fixed.
