### ISSUE TITLE
stromseite.de breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#65302]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: unblocked cookie banner background
`https://www.stromseite.de/nachtstromtarife/`
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="184" alt="Unbenannt3" src="https://user-images.githubusercontent.com/48647394/95495991-7c508080-09a0-11eb-9983-30d13ad958b5.PNG">

</details><br/>

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.12
Filters enabled:                       | default + Adguard tracking protection + Adguard germany + Adguard Annoyances
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@JobcenterTycoon Hi. Please check for updates after one hour.
