### ISSUE TITLE
http://linkkawy.com - anti adblcok

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#6530]
Hey
have  anti adblock in site: http://linkkawy.com
link exmple: http://linkkawy.com/OJBQ
Operating system: Windows 10 x64
Screenshot:  http://prntscr.com/gf6pi3
Browser: Chrome
Adguard version: 6.1.331.1732

filter:
English filter
Annoyances filter
fanboys social blocking list
EasyLIstHebrew
adblock warning removal list
Anti-adblock Killer | reek

**Comment by Alex-302** [comment]
fixed
