### ISSUE TITLE
http://m.news.naver.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6531]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

* **Current behavior**: The link: http://m.news.naver.com/memoRankingRead.nhn?oid=001&aid=0009500647&sid1=102&date=20170828&ntype=MEMORANKING

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29910238-d262ffe0-8e31-11e7-9906-43c41eef910a.png)

</details><br/>

***System configuration***

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.29.9 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.13 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.22.57 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.17.49 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.50 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.58 Enabled=YES
- ID=101 Name="EasyList" Version=1.0.75.7 Enabled=YES
- ID=118 Name="EasyPrivacy" Version=1.0.86.28 Enabled=YES
- ID=224 Name="Korean Adblock List" Version=1.0.0.5 Enabled=YES
- ID=227 Name="List-KR" Version=1.0.3.25 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Chrome
AdGuard version:                    | 1.3.0.81
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1619786

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.
These ads are hidden by the rules from English filter:
```
##.ad_area
##.ad_box
```
Try to add them to user filter.
