### ISSUE TITLE
https://sinoptik.com.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6532]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behavior**: We can't reproduce. The link: https://sinoptik.com.ru/%D0%BF%D0%BE%D0%B3%D0%BE%D0%B4%D0%B0-%D1%83%D0%BB%D0%B0%D0%BD-%D1%83%D0%B4%D1%8D

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29912126-40aba9d2-8e39-11e7-9746-2c8092842d90.png)

</details><br/>

The customer has no other ad blockers, tried clearing the cache and deleted all customer filtering rules. States that the issue persists for 1-2 weeks and it was fine before.

The code: [HTML-pogoda.zip](https://github.com/AdguardTeam/AdguardFilters/files/1266238/HTML-pogoda.zip)

***System configuration***

**Filters:** 

![image](https://user-images.githubusercontent.com/15856304/29912138-4e19da3a-8e39-11e7-8e64-cb5301491596.png)

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows7 64 Home Premium
Browser:                            | SlimJet
AdGuard version:                    | unknown, the latest one I assume
Helpdesk ID (if exists):            | 1516094

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce.

Open dev tools, reproduce the issue and save HAR
https://toolbox.googleapps.com/apps/har_analyzer/?lang=ru
