### ISSUE TITLE
https://zfilm-hd.club/ - pre-roll ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6533]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behavior**: The link: https://zfilm-hd.club/19832-propavednik.html

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29913425-d6ce6d42-8e3d-11e7-9d9c-26092450cb67.png)

</details><br/>

***System configuration***

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.17.94 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.12.6 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.12.74 Enabled=YES
- ID=1 Name="Russian filter" Version=1.0.51.11 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.12 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.0
Simplified filters (iOS only)       |Off
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | 1559717

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is impossible to bypass the timer on iOS.
