### ISSUE TITLE
http://btdigg.fyi/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6534]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: The full link: http://btdigg.fyi/search/5pWm5Yi75bCU5YWL/1/0/0.html

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29914226-6afd1598-8e40-11e7-8e47-d597880f2acd.png)

</details><br/>

***System configuration***

**Filters:**

Rules converted: 41931 from: 41931.

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.29.35 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.22.68 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.17.62 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.51 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
- ID=122 Name="Fanboy's Annoyances" Version=1.0.75.30 Enabled=YES
- ID=104 Name="EasyList China" Version=1.0.86.76 Enabled=YES
- ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES
- ID=220 Name="CJX's Annoyance List" Version=1.0.1.48 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.1.82
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | 1621439

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
