### ISSUE TITLE
genfb.com - missed ad

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#6535]
https://forums.lanik.us/viewtopic.php?f=62&t=38005

![i3owk4j](https://user-images.githubusercontent.com/5947035/29912688-35376666-8e3b-11e7-825b-d44973ddf87e.png)

Seem to be using websockets and webrtc to avoid blocking (`a.niklesrov.com`). Also, we should either block the webrtc connection with a $network rule or remove the uponit script from the page code.

What for the extension, it's tricky. They manage to circumvent the webrtc wrapper, and we'd better take a better look into it.

Meanwhile, @seanl-adg is there any temporary solution for uponit?

**Comment by AdamWr** [comment]
I think for Chrome Extension we can use this rule:
`genfb.com#%#(function(a){Object.defineProperty(window,"upManager",{get:function(){return{push:a,register:a,fireNow:a,start:a}},set:function(a){if(!(a instanceof Error))throw Error();}})})(function(){});`
How I can get IP for `$network` rule(s)?

**Comment by Alex-302** [comment]
@AdamWr 

> How I can get IP for $network rule(s)?

chrome://webrtc-internals

but be careful with IP blocking.

**Comment by AdamWr** [comment]
Ok, I will check it, thank you.

**Comment by AdamWr** [comment]
Fixed.
