### ISSUE TITLE
https://www.lyft.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6536]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: The site is getting blocked by the content blocker, see the screenshot

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29914909-cefedec6-8e42-11e7-85e7-106a3bd5ed8f.png)

</details><br/>

***Steps to reproduce the problem***:

1. Go to https://lyft.com/ici/SIMONE573
2. Tap on Download and claim

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

Rules converted: 47208 from: 47208.

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.21.4 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.12.69 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.20.30 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.13.90 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.8.71 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.47 Enabled=YES
- ID=101 Name="EasyList" Version=1.0.72.45 Enabled=YES
- ID=118 Name="EasyPrivacy" Version=1.0.81.50 Enabled=YES
- ID=123 Name="Fanboy's Social Blocking List" Version=1.0.72.45 Enabled=YES
- ID=122 Name="Fanboy's Annoyances" Version=1.0.72.65 Enabled=YES
- ID=109 Name="EasyList Italy" Version=1.0.81.51 Enabled=YES
- ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.3.96 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari 
AdGuard version:                    | 1.3.1.82
Simplified filters (iOS only)       | ff
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1034383

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. I need full blocked URL.

**Comment by evgeniy-ADG** [comment]
https://www.lyft.com/click/invite_t1

**Comment by veronikasav** [comment]
An update from our customer. Please use this link:
https://lyft.com/ici/SIMONE573

**Comment by evgeniy-ADG** [comment]
Awesome update, thanks, please read the report first. 

When you open that link and hit Confirm, it redirects you to https://www.lyft.com/click/invite_t1 which is Blocked by the content blocker.

**Comment by Alex-302** [comment]
Please check this rule with disabled DNS
```
@@||hastrk1.com^
```

**Comment by evgeniy-ADG** [comment]
Works fine now, redirects to the app store.

**Comment by Alex-302** [comment]
Ok.
