### ISSUE TITLE
[nsfw] fetishshrine.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6537]
https://www.fetishshrine.com/videos/1864832/sexy-cheating-wife-is-horny-and-fucks-her-neighbor/
https://www.fetishshrine.com/albums/4192/sexy-babe-big-hot-tits/

Overlay popup on player

![image-20170831-004](https://user-images.githubusercontent.com/9846948/29916008-c8ed6b38-8e3d-11e7-8b12-4597b8d63f51.png)

Advertisment box on right side
![image-20170831-005](https://user-images.githubusercontent.com/9846948/29916183-4f9b7166-8e3e-11e7-9274-85261b13cd6e.png)

Advertisment box at the end of site
![image-20170831-006](https://user-images.githubusercontent.com/9846948/29916260-87ca3306-8e3e-11e7-855b-b15fd5ddfce1.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by AdamWr** [comment]
Fixed.

**Comment by Nzzyme** [comment]
Site: https://www.fetishshrine.com/videos/1822192/brunette-massage-girl-teased-spa-owner-husband-for-shower-quick-sex-service/?utm_source=pbw&utm_medium=cpc&utm_campaign=shrine


Screenshot: http://prntscr.com/mp0vce

**OS**:
> `Windows 7 (64 bit)`

**Browser**: 
>` Chrome 72.0.3626.81 (Official Build) (64-bit)`

**AG Version**:
> `AG for Chrome Browser Extension 2.10.14 `

**Filters**:
> `Base Filter, Spyware, Social Media, Annoyances, Mobile Ads, Adblock Warning Removal List, Malware Domains, Sapm404
[No user filter used | Phishing & Malware Protection Enabled] `

**Comment by FadeMind** [comment]
@Nzzyme try
```
fetishshrine.com##.advertising
```

**Comment by Nzzyme** [comment]
Hi @AdamWr Please fix

**Comment by AdamWr** [comment]
Added:
`fetishshrine.com##.advertising`

**Comment by Nzzyme** [comment]
Seeing pop-up when clicking on the seek bar on player.
https://www.fetishshrine.com/videos/722886/extremely-unbelievable-mature-fucking-hard/

Using AG for Chrome

**Comment by Nzzyme** [comment]
A Reminder. Still seeing this

**Comment by AdamWr** [comment]
Ok, added:
```
fetishshrine.com#%#//scriptlet("abort-on-property-read", "customScript")
||fetishshrine.com/js/customscript.js
```
