### ISSUE TITLE
[nsfw] pornclipsxxx.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6539]
https://pornclipsxxx.com/
https://pornclipsxxx.com/video/as-she-promised-12792.html

- Overlay popup on player
- popups
- boxes with ads

![image-20170831-001](https://user-images.githubusercontent.com/9846948/29916835-49667b04-8e40-11e7-840b-1a06438f8c11.png)

![image-20170831-002](https://user-images.githubusercontent.com/9846948/29916844-507db240-8e40-11e7-89aa-7cd99f79fedf.png)
![image-20170831-003](https://user-images.githubusercontent.com/9846948/29916999-c844b472-8e40-11e7-891a-e45a31fd8e6a.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by AdamWr** [comment]
Fixed.

**Comment by Nzzyme** [comment]
Seeings ad text strings on the page

https://pornclipsxxx.com/video/hot-mom-jerks-off-step-son-48802.html

Seen on AG for chrome

**Comment by Alex-302** [comment]
fixed
