### ISSUE TITLE
hltv.org

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#654]
Реклама g2a.com на сайте

**Comment by Alex-302** [comment]
Добавил
hltv.org##.topHolder > span > a > img
hltv.org##embed[style="width:120px;height:240px;"]

**Comment by vgavrish** [comment]
hltv.org реклама вверху
ф: 1,2,3,4,11,14
Фильтрация качественная
Браузер встроенный:
http://prntscr.com/d1rb3l

**Comment by Alex-302** [comment]
Added to English filter
```
||static.hltv.org//images/drakemoon_
```
