### ISSUE TITLE
[nsfw] fantasti.cc

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6540]
fantasti.cc

http://fantasti.cc/user/emothumbteen822/videos/upload/Oiled-brunette-dildo-They-gave-pursue-in-their-truck-and-when-th/1476768/

- Overlay popup on player
- redirecting to another sites after click on logo site
- popups
- boxes with ads

![image-20170831-004](https://user-images.githubusercontent.com/9846948/29917224-93b5ee46-8e41-11e7-9629-ba016d2a3bd5.png)
![image-20170831-005](https://user-images.githubusercontent.com/9846948/29917227-9979d798-8e41-11e7-8875-02b380bf42d6.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by AdamWr** [comment]
Fixed.
