### ISSUE TITLE
[nsfw] https://www.katestube.com/

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6541]
https://www.katestube.com/
https://www.katestube.com/videos/1753855/teen-fucked-by-photographer-at-casting-audition-fake-agent4/
Empty box ad
![image-20170831-001](https://user-images.githubusercontent.com/9846948/29917305-da853e4e-8e41-11e7-9d58-b7c1e6a388ad.png)
![image-20170831-002](https://user-images.githubusercontent.com/9846948/29917324-eb74b612-8e41-11e7-912d-3986c8a9412f.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by AdamWr** [comment]
Fixed.
