### ISSUE TITLE
false positive on wikicharlie.cl

### ISSUE THREAD

**Issue by confor** [AdguardTeam/AdguardFilters#65425]
***Description***: The spanish/portuguese list is blocking legitimate page content on wikicharlie.cl, a wiki focused on preserving historical content. Some pages contain "historical" ads, as in old propaganda posters ([example: bed ad from 1948](https://wikicharlie.cl/w/Archivo:CIC_aviso_de_1948.jpg)), and they're being blocked because they have "publicidad" ("ad" in spanish) in the image url. They're not modern web advertisements.

According to uBlock origin's logger, the "spa, por: AdGuard Spanish/Portuguese" list is blocking `_publicidad.` ([general_url.txt line 87, 89](https://github.com/AdguardTeam/AdguardFilters/blob/master/SpanishFilter/sections/general_url.txt#L87-L89) i think)

I think this can be solved by whitelisting `img.wikicharlie.cl`, although it might be too broad.

* **Current behaviour**: Images are blocked by adguard

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/38121691/95672200-34368700-0b75-11eb-9e37-a316d8697787.png)

</details><br/>

* **Expected behaviour**: Images load

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/38121691/95672167-f8032680-0b74-11eb-8d69-622aa7146570.png)
</details><br/>

***Steps to reproduce the problem***:

Open any of the pages with "publicidad" on it:
* https://wikicharlie.cl/w/Archivo:Publicidad_de_Radio_O_higgins_CB-144.jpg
* https://wikicharlie.cl/w/Archivo:Radio_La_Ciudad_publicidad.jpg

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | windows
Operating system version (Android/iOS) | 7
Browser:                               | chrome
AdGuard version:                       | ?
Filters enabled:                       | uBlock's "AdGuard Spanish/Portuguese filter 2.0.7.26"
AdGuard mode (Android only):           | -
Filtering quality (Android only):      | -
HTTPS filtering (Android only):        | -
Simplified filters (iOS only)          | -
AdGuard DNS:                           | -
Stealth mode options (Windows only)    | -
Helpdesk ID (if exists):               | -

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.

Thank you for reporting it.
