### ISSUE TITLE
[nsfw] https://pervclips.com/tube/

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6542]
Missing ad box
![image-20170831-003](https://user-images.githubusercontent.com/9846948/29917420-40022264-8e42-11e7-8736-0f05ec446662.png)
At the end of site with video:
![image-20170831-006](https://user-images.githubusercontent.com/9846948/29917424-45280cfe-8e42-11e7-92ac-1f8daa72a242.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by AdamWr** [comment]
Fixed.

**Comment by Nzzyme** [comment]
https://www.pervclips.com/tube/videos/tiffany-mynx-loves-anal-with-big-black-cock/

Ad text string seen on the page.

http://prntscr.com/myzr4k

@AdamWr Please check
