### ISSUE TITLE
Ads On Edge New Page/New Tab Page

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#65424]
After running Edge (version: 86.0.622.38) and cleared all cache, cookies & history. Now, the new tab page shows ad tiles as seen in screenshot.

https://i.imgur.com/107IJhD.png

Checking the logs, the ad domain responsible is taboola

The actual image ad domain is:

`https://img.img-taboola.com/taboola/image/fetch/f_jpg%2Cq_auto%2Ch_175%2Cw_300%2Cc_fill%2Cg_faces:auto%2Ce_sharpen/https%3A%2F%2Fgallery-pl.go-game.io%2Fuploads%2F2020%2F08%2FRAD_Gameplay_Girl_6_B85038_1000x600_NoOS_NoLanguage%26IMG%3D1TM6.jpg`

Screenshot: https://i.imgur.com/9gZpHfG.png

In the screenshot, you will see other domains related to taboola too like api.taboola.com and others. It is better to block this one too.

Checked with AG extension for Edge

**Comment by krystian3w** [comment]
Needed install AdGuard for Windows.

---

I suppose AG no support this @slavaleleka:

`edge://flags/#extensions-on-edge-urls`

**Comment by Nzzyme** [comment]
Can it be added to AG DNS filter list?

**Comment by Alex-302** [comment]
Browser extension cannot block it.


> Can it be added to AG DNS filter list?

![image](https://user-images.githubusercontent.com/8361299/95972632-5c471400-0e1b-11eb-9450-ac09c43f1f90.png)

**Comment by krystian3w** [comment]
DNS no need add sub-domains and sister domains:

> **img.img-**taboola.com

so block from nslookup may no match.
