### ISSUE TITLE
[nsfw] http://zmovs.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6543]
http://zmovs.com/video/lRBmEWLk/?sid=12111
Empty ads box on right and between list of clips during slide down:
![image-20170831-007](https://user-images.githubusercontent.com/9846948/29917635-d74e63d0-8e42-11e7-9680-77b505528f7d.png)
![image-20170831-008](https://user-images.githubusercontent.com/9846948/29917652-dff00854-8e42-11e7-83ff-a2522c36aca2.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
fixed
