### ISSUE TITLE
[nsfw] http://www.txxx.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6544]
http://www.txxx.com/videos/3920873/karlee-grey-tyler-nixon-in-why-men-cheat-nurumassage

Overlay
![image-20170831-001](https://user-images.githubusercontent.com/9846948/29917819-6de26b52-8e43-11e7-806f-2a7d1ed5c606.png)
`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
Fixed
