### ISSUE TITLE
Annoyance

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardFilters#65466]
AdGuard Product:	AdGuard/AdGuard Pro for iOS version 4.0.3

Browser:	Safari

Problem URL:	https://ioccasion.fr/annonce/apple-watch-s4-alu-silver/

Problem Type:	Annoyance (Pop-ups, notifications, etc.)

Filters:	
Ad Blocking:
AdGuard Base filter
AdGuard Mobile Ads filter
Peter Lowe's Blocklist
Privacy:
AdGuard Tracking Protection filter
EasyPrivacy
Fanboy's Enhanced Tracking List
Fanboy Anti-Facebook List
Fanboy's Anti-thirdparty Fonts
Social Widgets:
AdGuard Social Media filter
Annoyances:
AdGuard Annoyances filter
Fanboy's Annoyances
Web Annoyances Ultralist
Adblock Warning Removal List
I don't care about cookies
Security:
Spam404
NoCoin Filter List

Other:
AdGuard Experimental filter
AdGuard DNS filter
BarbBlock

Language-specific:
AdGuard French filter

User Comment:	Can't remove yellow bottom pop up even with custom rule: ioccasion.fr##div.ynp4g6xm1fvn:nth-child(132)

![image](https://user-images.githubusercontent.com/49731083/95692865-3d812b80-0c29-11eb-92b4-767255464f63.jpeg)

**Comment by krystian3w** [comment]
iOS maybe need add some legacy exceptions:

`@@` / `#@#`

or disable problematic lists - maybe guilty: `Fanboy's Enhanced Tracking List`

**Comment by Alex-302** [comment]
Please disable `I don't care about cookies`

**Comment by Alex-302** [comment]
Or add `@@||fundingchoicesmessages.google.com^$domain=ioccasion.fr`

**Comment by krystian3w** [comment]
@kiboke fyi

**Comment by kiboke** [comment]
@krystian3w on my side the bottom warning goes away if I fisable EasyList and keep IDCAC active.

**Comment by kiboke** [comment]
Maybe this could help? Is it too generic?
`##body > div[class]:not([id])[style^="bottom: 0px"][style*="left: 0px"][style*="position: fixed"][style*="Roboto"][style*="display: flex"][style*="justify-content: center"]`

**Comment by krystian3w** [comment]
This for cookie bars or try hide Google Contributor Anti-Adblock bar?

**Comment by kiboke** [comment]
For the anti-adblock bar.

**Comment by krystian3w** [comment]
OK, your list is not sorted by some like [`FOP.py`](https://github.com/AdguardTeam/AdguardFilters/blob/master/FOP.py) (Filter Orderer and Preener)?

When possible test:

```
!#if !ext_ublock
##body > div[class]:not([id])[style^="bottom: 0px"][style*="left: 0px"][style*="position: fixed"][style*="Roboto"][style*="display: flex"][style*="justify-content: center"]
!#endif
```

Because uBlock Origin disabled use `##div[class^="div-gpt-ad"]` and `##.div-gpt-ad`
