### ISSUE TITLE
[nsfw] wankoz.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6547]
https://www.wankoz.com/videos/246634/pussy-to-pussy-action-video-with-holly-michaels-and-sophia/
- ads box
- leftover
- redirection when click on player
- popups

![image-20170831-001](https://user-images.githubusercontent.com/9846948/29920354-6bd90d98-8e4d-11e7-8632-08f25d8bed06.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by AdamWr** [comment]
Fixed.
