### ISSUE TITLE
[nsfw] porndoe.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6548]
https://porndoe.com/video/650533/stunning-busty-czech-babe-lucy-li-delights-in-hot-sensual-sex
![image-20170831-002](https://user-images.githubusercontent.com/9846948/29920546-338fdbb4-8e4e-11e7-9260-bdabcdb2715e.png)

- ads box
- popups

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
Fixed
