### ISSUE TITLE
[nsfw] pornoxo.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6549]
https://www.pornoxo.com/videos/2005391/delicious-filly-has-her-moist-pussy-penetrated/

- ad leftover

![image-20170831-003](https://user-images.githubusercontent.com/9846948/29920660-ae37d42a-8e4e-11e7-9f23-7fc931ddb14e.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
Fixed
