### ISSUE TITLE
[nsfw] iceporn.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6550]
http://www.iceporn.com
- Launch any video clip. Video will be not loaded at all.
- ad box
![image-20170831-004](https://user-images.githubusercontent.com/9846948/29920740-25482916-8e4f-11e7-92cb-a951e71187cd.png)

Video cannot be played at all. Tested without **Stealth Mode** - no change.

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
Not reproduced.
