### ISSUE TITLE
[nsfw] https://smutty.com/

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6551]
https://smutty.com/
Push  @ https://smutty.com/videos/

![image-20170831-005](https://user-images.githubusercontent.com/9846948/29920913-f76b1c50-8e4f-11e7-8905-685461f8e3f3.png)

adv 
https://smutty.com/p/1082121/
![image-20170831-006](https://user-images.githubusercontent.com/9846948/29920989-49ff5558-8e50-11e7-859f-126e713f70cf.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
1 - not reproduced
2 - fixed
