### ISSUE TITLE
thingiverse.com (N: uBlock Origin) (T: Incorrect Blocking)

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#65519]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

The scriplet entry for `thingiverse.com` in AdGuard Base, seems to conflict with those 2 that are in uBlock Filters Main, resulting in page breakage if both lists are turned on at the same time. 

I propose applying `!#if !ext_ublock` to `thingiverse.com#%#//scriptlet("set-constant", "blockedElement.className", "undefined")`; or to change `"undefined"` to `"null"` to make it identical to uBlock Filters' entry for `"blockedElement.className"`.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/95809416-04bb8200-0d0f-11eb-9fb1-629ee82079ac.png)
</details><br/>

* **Expected behaviour**: 

The page loads normally.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/95809663-9d520200-0d0f-11eb-812d-dd1cc20a00f4.png)
</details><br/>

***Steps to reproduce the problem***:

1) Use uBlock Origin.
2) Turn on uBlock Filters and AdGuard Base at the same time.
3) Go to `https://www.thingiverse.com/thing:2873324`
4) Receive an error page saying "Something went wrong".

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/95809750-d5594500-0d0f-11eb-8926-e6e48138c77b.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | May 2020 Update
Browser:                               | Chrome 86.0.4240.75 x64
AdGuard version:                       | uBO 1.30.3b6 + uBO Extra 2.88 + IDCAC 3.2.2
Filters enabled:                       | See screenshot above
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by krystian3w** [comment]
So:

```diff
!+ NOT_PLATFORM(ext_ublock)
thingiverse.com#%#//scriptlet("set-constant", "blockedElement.className", "undefined")
!+ PLATFORM(ext_ublock)
thingiverse.com#%#//scriptlet("set-constant", "blockedElement.className", "null")
```

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/156

**Comment by Alex-302** [comment]
I cannot reproduce adblock detection at the moment. Please check with disabled scriptlets.

**Comment by DandelionSprout** [comment]
Using these whitelistings:
```
! uBlock Filters
thingiverse.com#@#+js(set-constant, blockedElement.className, null)
thingiverse.com#@#+js(nano-setInterval-booster)
! AdGuard Base
thingiverse.com#@#+js(set-constant, blockedElement.className, undefined)
```

It appears that they indeed aren't using anti-adblock that I'd be able to see, at least.

**Comment by Alex-302** [comment]
removed our scriptlet
