### ISSUE TITLE
[nsfw] pornicom.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6552]
pornicom.com
- ad on player pause
- ad leftover

![image-20170831-007](https://user-images.githubusercontent.com/9846948/29921154-d6d6cc36-8e50-11e7-89b4-69cd14b23b02.png)

![image-20170831-008](https://user-images.githubusercontent.com/9846948/29921157-da35210c-8e50-11e7-9108-dd8b8ecbdc2c.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
Fixed
