### ISSUE TITLE
[nsfw, adblock detect] http://www.yeptube.com/

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6553]
http://www.yeptube.com/video/170900/brunette-gal-solo

![image-20170831-009](https://user-images.githubusercontent.com/9846948/29921234-2cccce92-8e51-11e7-84bb-271c99c850a1.png)

![image-20170831-010](https://user-images.githubusercontent.com/9846948/29921239-301eadea-8e51-11e7-82ef-14bbbde36227.png)

- video play does not working (adblock detect?) - stealth mode does not matter
- adblock detect
- ads leftover

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
fixed
