### ISSUE TITLE
webnovel.com - Annoyances - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6554]
***Description***:
* **Current behavior**: 

https://www.webnovel.com/book/7834185605001405/22564339844171966/True-Martial-World/Sea-of-Flames
Ad window isn`t blocked and cannot be manually blocked ad as the content won't show up without watching the ad in Windows.

Reproduced on our side (Mac OS)
<details><summary>Screenshot:</summary>

![screen shot 2017-08-31 at 6 22 59 pm](https://user-images.githubusercontent.com/28784344/29931287-7c402050-8e79-11e7-8fae-c826a70aa1bb.png)

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | MAC OS
Browser:                            | CHROME
AdGuard version:                    | 1.4.1
Filters enabled:                    | 0,1,2,3,4,14
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1494620

**Comment by ghajini** [comment]
Related
https://github.com/AdguardTeam/AdguardFilters/issues/6135
