### ISSUE TITLE
https://www.hotcleaner.com/cookie-wiper.html

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6555]
https://www.hotcleaner.com/cookie-wiper.html

Ad leftover `Advertisments`
![image-20170831-004](https://user-images.githubusercontent.com/9846948/29941036-57c6671c-8e91-11e7-8147-ecba4102d691.png)

![image-20170831-005](https://user-images.githubusercontent.com/9846948/29941088-98ce9e8c-8e91-11e7-867d-c339ca81f716.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
Fixed
