### ISSUE TITLE
[nsfw] http://donkparty.com/

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6556]
http://donkparty.com/
- Banners (right side and top)
- popups
![image-20170831-006](https://user-images.githubusercontent.com/9846948/29942204-5a3f62c4-8e95-11e7-97e6-6cc0beab653e.png)

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
fixed
