### ISSUE TITLE
m.spiegel.de - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6557]
http://m.spiegel.de/netzwelt/games/a-1164564.html

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29949129-4c4afa9a-8ebb-11e7-83aa-6ce94d9493f2.png)

</details><br/>

***System configuration***

Application version: 1.3.1.107
Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.29.25 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.19 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.64 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.58 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.39 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.66 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.51 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES
ID=240 Name="BarbBlock" Version=1.0.0.1 Enabled=YES

Helpdesk ID: 1610467

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
