### ISSUE TITLE
https://yandex.ru/pogoda - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6558]
https://yandex.ru/pogoda

<details><summary>Screenshot:</summary>

![screen shot 2017-09-01 at 5 02 34 am](https://user-images.githubusercontent.com/27292111/29952805-6e12e0e8-8ed4-11e7-9a24-ab2d9400f264.png)

</details><br/>

***System configuration***

Information | value
--- | ---
OS | Windows 7 x64
ADGUARD VERSION | Adguard в виде расширения у Chrome
FILTERS | Используемые фильтры: Русский фильтр, Английский фильтр, RU AdList, Фильтр раздражителей
AV | Dr.Web
ID | 1076701

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Поправил.
