### ISSUE TITLE
tagesspiegel.de - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6559]
http://www.tagesspiegel.de/

<details><summary>Screenshot:</summary>

![screen shot 2017-09-01 at 6 37 00 am](https://user-images.githubusercontent.com/27292111/29954390-3224e250-8ee0-11e7-963c-0927bbabc464.png)

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPad
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.29.20 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.17 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.64 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.37 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
Mobile ads
Annoyances

ID | 1076701

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Also not reproduced.
Try to switch full/optimized filters.
