### ISSUE TITLE
https://naver.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6560]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

네이버 검색 창에서 노래를 검색하고 가사버튼을 누르면 새 창에서 열리는 것 뿐만 아니라 노래를 검색했던 가사버튼이 있는 창도 자동으로 넘어가버립니다. 불편해요

From what I understand, when you search for lyrics, it does not open lyrics in a pop-up window.

***Steps to reproduce the problem***:

1. Go to https://naver.com/
2. Search for a song, [this link](https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=shape+of+you+ed+sheeran&oquery=shape+of+you+sheeran&tqi=TjBJrwpVuE4ssty4irsssssss4K-071921), for instance
3. See the screenshot
 <details><summary>  the screenshot </summary>

![image](https://user-images.githubusercontent.com/15856304/29957623-26f8ad3c-8ef7-11e7-8797-3e030535d8c6.png)

</details>

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

1. FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
2. FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt
3. FilterId:4 Name: Social media filter Url: https://filters.adtidy.org/extension/chromium/filters/4.txt
4. FilterId:14 Name: Annoyances filter Url: https://filters.adtidy.org/extension/chromium/filters/14.txt
5. FilterId:10 Name: Filter unblocking search ads and self-promotion Url: https://filters.adtidy.org/extension/chromium/filters/10.txt
6. FilterId:227 Name: List-KR Url: https://raw.githubusercontent.com/SlowMemory/List-KR/master/filter.txt

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   |  Windows NT 10.0.15063.0
Browser:                            | Chrome
AdGuard version:                    | 6.1.331.1732
AdGuard DNS:                        | None 
Stealth mode options (Windows only) | on
Helpdesk ID (if exists):            | 1621563

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@seanl-adg it is caused by the rule in List-KR
```
search.naver.com#%#AG_onLoad( function() { window.goCR = window.tCR = function() { }; });
```
Click on 
![image](https://user-images.githubusercontent.com/8361299/29995779-ed816df6-8ff9-11e7-8d8e-657e5083ff53.png)
and the main page will be redirected to the address as popup window.

**Comment by seanl-adg** [comment]
The problematic rule in List-KR is updated now. Please let the user check after updating filters.
