### ISSUE TITLE
[adblock detect, nsfw] pornbraze.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6561]
http://pornbraze.com/40670/snis-809-every-day-flirting-cohabitation-of-active/
![image-20170901-001](https://user-images.githubusercontent.com/9846948/29959388-5c5d27fa-8ef7-11e7-9cf9-b2119588b11e.png)
`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

**Comment by Alex-302** [comment]
Fixed
