### ISSUE TITLE
tracking.epicgames.com #DNS #Tracking Servers

### ISSUE THREAD

**Issue by privacy-advo** [AdguardTeam/AdguardFilters#65620]
***Description***:
* **tracking.epicgames.com is not blocked by https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/SpywareFilter/sections/tracking_servers.txt**:

**Comment by Alex-302** [comment]
Hi. That's because of an issue:
https://forum.adguard.com/index.php?threads/epicgames-for-windows-not-loading.35325/

**Comment by privacy-advo** [comment]
Thank you @Alex-302 for the fast response.
Right now I'm blocking this domain with my local dnscrypt-proxy and Epic Games Launcher works fine. I just would like to have it included and not manually blacklisted.

I *don't want* to accuse someone, but sometimes I wonder about really active users who only ask for whitlistings of obvious domains as adjust.com etc. [https://github.com/EnergizedProtection/block/issues/313]
The person in the forum post just posted this single post.

What is your opinion on this and or experience?

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #475](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/475) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
Ok, we will try to block it again.

**Comment by privacy-advo** [comment]
Thanks for the removal from the exclusions. But ||epicgames.com^ or ||tracking.epicgames.com^ ist not yet part of the filter.

**Comment by Alex-302** [comment]
please write to the link above
