### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6564]
Login is not possible when Stealth Mode is enabled in Adguard. 

https://player.pl/moj-player.html

`Adguard for Windows Beta 6.2.390.2018`
`Adguard Chrome Extension 2.6.7`
`Google Chrome Stable 60.0.3112.101`
`Windows 10 X64`

Filters:
- Polish - main
- Polish  - Adguard suplement
- KAD - fraud/scam, mostly polish lang.
- Adguard Spy
- Adguard English
- Adguard Annoyances
- I Don't care about cookies

cc @AdamWr

**Comment by AdamWr** [comment]
Niestety nie jestem w stanie tego odtworzyć.
Mógłbyś proszę napisać jakie opcje masz włączone w "trybie niewidzialności"?

Sprawdź proszę tę regułę, powinna pomóc:
`@@||player.pl^$stealth`

**Comment by FadeMind** [comment]
@AdamWr `@@||player.pl^$stealth` załatwił sprawę - można się zalogować. Proszę dodać regułę tutaj albo do polskiej listy. Dziękuję. 

Mam aktywne wszystko oprócz:
- samoniszczące się ciasteczka
- cache dla thirdparty (są problemy z video na interii jak to jest aktywne)

**Comment by AdamWr** [comment]
Dziękuję za odpowiedź.
Odnośnie strony interia.pl to udało mi się odtworzyć problem.
Dodałem odpowiednie reguły dla obu stron.
