### ISSUE TITLE
appsgames.ru - missed ads

### ISSUE THREAD

**Issue by vitalkanev** [AdguardTeam/AdguardFilters#6565]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: There is some *"bad advertising"* on the website
* **Current behaviour**: There is an ad

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/18398761/29976694-85cf2042-8f43-11e7-8701-98b4eb60a20d.png)

</details><br/>

* **Expected behaviour**: Should be blocked

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

```json
"content": "Cannot be shown",
"reason": "I don't even know :-D"
```
</details><br/>

***Steps to reproduce the problem***: Open something like [this](http://appsgames.ru/poleznoe-dlya-android/kak-sozdat-prolojenie/).

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**
![2017-08-27 17-05-56](https://user-images.githubusercontent.com/18398761/29976596-36792330-8f43-11e7-9f75-26629b7566fc.png)

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Linux - Lubuntu Zesty
Browser:                            | Yandex 17.7.1 *Beta*
AdGuard version:                    | 2.6.7 Browser Extension
Filters enabled:                    | See above!
Helpdesk ID (if exists):            | `undefined`

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
