### ISSUE TITLE
www.work.ua - banner - Windows

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6566]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # The user asks to add the banner, given in the following screenshot, to our database which appears on the website www.work.ua

[//]: # http://radikal.ru/lfp/s019.radikal.ru/i637/1709/c0/6b388b241852.png/htm

![image](%screenshot_url%)
</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | Microsoft Windows NT 10.0.15063.0
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 1,2,3,4,10,11,0,14
Stealth mode options (Windows only) | enabled
Helpdesk ID (if exists):            | 1449704

**Comment by Alex-302** [comment]
У себя этот баннер не наблюдаю.
