### ISSUE TITLE
m.bild.de - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6567]
http://m.bild.de/politik/inland/bundestagswahl2017/schulz-interview-53057564.bildMobile.html

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29993171-879955f4-8fb7-11e7-873b-dde5d417548a.png)

</details><br/>

***System configuration***

Application version: 1.3.1.107
Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.29.48 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.26 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.70 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.69 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.47 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.51 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES
ID=229 Name="I don't care about cookies" Version=1.0.0.15 Enabled=YES
ID=204 Name="Peter Lowe's list" Version=1.0.3.36 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.15 Enabled=YES
ID=240 Name="BarbBlock" Version=1.0.0.1 Enabled=YES

Helpdesk ID:   1610467

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. Please send to user:
```
m.bild.de##.socialbar
```
