### ISSUE TITLE
kinox.to

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#65675]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: ads on `https://www.kinox.*` and `https://www.kinos.*/`
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="677" alt="Unbenannt4" src="https://user-images.githubusercontent.com/48647394/96221384-ce8a3680-0f8a-11eb-8f47-51c4bd788593.PNG">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.12
Filters enabled:                       | default + Adguard tracking protection + Adguard germany + Adguard Annoyances
AdGuard DNS:                           | None

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/96248380-28ebbd00-0fb4-11eb-9075-66f873282dd2.png)

**Comment by JobcenterTycoon** [comment]
i can’t explain why you get this error

**Comment by Sergey-Lyapin** [comment]
@JobcenterTycoon I see clickunder only, can't reproduce ads like on your screenshot.
Please specify the url where your saw it.

`kinos.to,kinox.to##a[href^="//pocrowpush.com"]` fixes the clickunder

**Comment by JobcenterTycoon** [comment]
example link: `https://www.kinox.to/Stream/SpongeBob_Schwammkopf.html`

**Comment by Sergey-Lyapin** [comment]
I can't reproduce ads there
@AdamWr @BlazDT please take a look

**Comment by BlazDT** [comment]
Ads not shown.

**Comment by JobcenterTycoon** [comment]
I see EasyList blocked all ad domains a day ago and Adguard block all Domains too thats why nobody can reproduce now... ok now its fixed.
