### ISSUE TITLE
youmath.it - Anti adblock

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6568]
http://www.youmath.it/lezioni/analisi-matematica/derivate/212-derivate-di-funzioni-elementari.html

1. The home page appears for some seconds.
2. Then, after some seconds, the site shows an adblocker-kill message.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29993445-ccb50dc4-8fbf-11e7-8d34-8c60e5fc1d7a.png)

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.29.48 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.26 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.70 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
ID=109 Name="EasyList Italy" Version=1.0.86.55 Enabled=YES

Helpdesk ID:         1622239

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
||youmath.it/plugins/system/CssJsCompress/js.php^
```
