### ISSUE TITLE
Ad banner in Gmail

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6569]
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/29994901-180cf966-8fe4-11e7-848d-5dbba943a9e4.png)

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | 6.1
Filters enabled:                    | 1 2 3 4 14
Helpdesk ID (if exists):            | 1591247

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by vitalkanev** [comment]
I can't reproduce on Lubuntu Zesty with Yandex 17.7.1 *Beta* with 2.6.7 Browser Extension.  :woman_shrugging: 
![2017-09-02 15-15-32](https://user-images.githubusercontent.com/18398761/29995430-d855ab98-8ff1-11e7-80b1-2f3b0412e7e0.png)

**Comment by Alex-302** [comment]
Not reproduced. It is blocked by `&view=ad&`

**Comment by Alex-302** [comment]
@AdamWr

**Comment by rnr222** [comment]
Here is a screenshot of some code, responsible for these ads.
https://yadi.sk/i/1SgcKd9C3MYims

**Comment by Alex-302** [comment]
It is useless.

**Comment by AdamWr** [comment]
I can't reproduce.
