### ISSUE TITLE
http://m.imbc.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6570]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: Can't play the video: http://m.imbc.com/program/mboard_view.aspx?progCode=1003535100000100000&objid=bws017_sketch&listid=2596360&title=7JiB7IOB7Iqk7LyA7LmY

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29996379-3851a9ca-9006-11e7-8dcb-b076126cfd43.png)

</details><br/>

* **Expected behaviour**: It plays as expected, after an advert, of course

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29996391-3f3cfbd6-9006-11e7-881c-bdc2acbce40f.png)

</details><br/>

***System configuration***

**Filters:**

1. ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
2. ID=2 Name="English filter" Version=1.1.29.35 Enabled=YES
3. ID=3 Name="Spyware filter" Version=1.0.14.23 Enabled=YES
4. ID=4 Name="Social media filter" Version=1.0.22.68 Enabled=YES
5. ID=14 Name="Annoyances filter" Version=1.0.17.62 Enabled=YES
6. ID=7 Name="Japanese filter" Version=1.0.93.8 Enabled=NO
7. ID=11 Name="Mobile Ads filter" Version=1.0.9.51 Enabled=YES
8. ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
9. ID=15 Name="Simplified domain names filter" Version=1.0.2.13 Enabled=YES
10. ID=207 Name="Adblock Warning Removal List" Version=1.0.86.63 Enabled=YES
11. ID=224 Name="Korean Adblock List" Version=1.0.0.5 Enabled=YES
12. ID=227 Name="List-KR" Version=1.0.3.26 Enabled=YES
13. ID=208 Name="Malware Domains" Version=1.0.86.51 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Simplified filters (iOS only)       | Off
AdGuard DNS:                        |  Default 
Helpdesk ID (if exists):            | 1622633

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It does not work on my side without Adguard.
@seanl-adg @AdamWr please check it.

**Comment by seanl-adg** [comment]
I couldn't reproduce the issue with browser extension with `$jsinject` rule applied to the site and a user agent set to iPhone 6.

**Comment by Alex-302** [comment]
@evgeniy-ADG please ask for disabling filters one-by-one with checking.

**Comment by evgeniy-ADG** [comment]
It's reproducible for me, Liste KR makes video unresponsive. Here's the screenrec: https://youtu.be/ntaHqzYGc9c

The screen is not just black like before but I still can't play the video.

**Comment by seanl-adg** [comment]
reproduced on my end, will investigate

**Comment by Alex-302** [comment]
@seanl-adg any news?
