### ISSUE TITLE
https://www.duolingo.com/ - leftovers

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6571]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: Ad leftovers, the full link: https://www.duolingo.com/?from_email=welcome_url

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29996430-e53c6e86-9006-11e7-9972-579fc4dc3fcf.png)

</details><br/>

***Steps to reproduce the problem***:

1. Go to https://www.duolingo.com/?from_email=welcome_url
2. Finish a lesson and see the blank leftover on the right side

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

1. FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
2. FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt
3. FilterId:4 Name: Social media filter Url: https://filters.adtidy.org/extension/chromium/filters/4.txt
4. FilterId:14 Name: Annoyances filter Url: https://filters.adtidy.org/extension/chromium/filters/14.txt
5. FilterId:1 Name: Russian filter Url: https://filters.adtidy.org/extension/chromium/filters/1.txt

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
Driver: | TDI
HTTPS: ON
AdGuard version:                    | The current release version
AdGuard DNS:                        | None
Stealth mode options (Windows only) | on
Helpdesk ID (if exists):            | 630452

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не попадаю на ту страницу. Нужно пошаговое описание.

**Comment by evgeniy-ADG** [comment]
Все просто: идешь логинишься через, допустим, гугл, начинаешь любой урок, проходишь, видишь в конце вместе с поздравлениями:

![image](https://user-images.githubusercontent.com/15856304/29998272-77314794-902f-11e7-97ef-d602f19a9923.png)

Затем ждешь дальше, снова дальше, тебе предлагают новый урок и там тоже:

![image](https://user-images.githubusercontent.com/15856304/29998280-94b0d37a-902f-11e7-8315-f7e8bc9c392b.png)

**Comment by Alex-302** [comment]
У меня чисто. Покажи код элемента.
http://imagizer.imageshack.com/img922/4195/LcrqPJ.png

**Comment by evgeniy-ADG** [comment]
![image](https://user-images.githubusercontent.com/15856304/30120695-45c683c6-9332-11e7-8ba6-9bae8e2f4518.png)

![image](https://user-images.githubusercontent.com/15856304/30120915-d96d8354-9332-11e7-90bb-57fb7e258e20.png)

**Comment by Alex-302** [comment]
Странные названия. Возможно периодически меняются. Пришли завтра в наш чат сохранённую страницу, попробую правило сделать.

**Comment by evgeniy-ADG** [comment]
ok
