### ISSUE TITLE
https://www.bitfinex.com/ - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6572]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: There's a floating half-transparent sort of a banner on the graph, the link: https://www.bitfinex.com/trading

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/29998298-f5d86622-902f-11e7-840c-574966ded8fa.png)

</details><br/>

***Steps to reproduce the problem***:

1. Go to https://www.bitfinex.com/trading
2. Register
3. Confirm email
4. Go there again: https://www.bitfinex.com/trading
5. Refresh the graph, wait until it's fully loaded
6. See the banner / annoyance

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

1. ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
2. ID=2 Name="English filter" Version=1.1.29.47 Enabled=YES
3. ID=3 Name="Spyware filter" Version=1.0.14.26 Enabled=YES
4. ID=4 Name="Social media filter" Version=1.0.22.70 Enabled=YES
5. ID=14 Name="Annoyances filter" Version=1.0.17.69 Enabled=YES
6. ID=1 Name="Russian filter" Version=1.0.56.29 Enabled=YES
7. ID=11 Name="Mobile Ads filter" Version=1.0.9.51 Enabled=YES
8. ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS 10 3 3
Browser:                            | Safari
AdGuard version:                    | 1.3.1.107
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | Default 
Helpdesk ID (if exists):            | 1580328

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
