### ISSUE TITLE
https://www.momox.de/ - false blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6573]
https://www.momox.de/

Prebake filter does that:

![image](https://user-images.githubusercontent.com/15856304/29998511-4650ef7a-9035-11e7-9be3-775e1a6ec9ac.png)

The full list:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.29.59 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.26 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.74 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.73 Enabled=YES
ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.13 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.48 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.51 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.86.66 Enabled=YES
ID=204 Name="Peter Lowe's list" Version=1.0.3.37 Enabled=YES
ID=209 Name="Prebake" Version=1.0.1.15 Enabled=YES
ID=240 Name="BarbBlock" Version=1.0.0.1 Enabled=YES

iOS, Adguard 1.3,1, no DNS, no optimized rules. Reproduced on iPad.

**Comment by Alex-302** [comment]
fixed
