### ISSUE TITLE
Blank page on https://community.nothingmore.net/

### ISSUE THREAD

**Issue by mykeb** [AdguardTeam/AdguardFilters#65730]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: Blank page

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

![Screenshot_2020-10-17 NOTHING MORE THE FEW Community](https://user-images.githubusercontent.com/59161287/96326433-1d0b0400-1063-11eb-9b2e-f5a973db03ce.png)

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)
Go to https://community.nothingmore.net/ with Adguard Annoyances enabled.

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Arch Linux
Operating system version (Android/iOS) | ?
Browser:                               | Firefox
AdGuard version:                       | ?
Filters enabled:                       | Adguard Annoyances
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by gwarser** [comment]
Filter ##.cookie_popup
	Filter list AdGuard Annoyances

**Comment by mykeb** [comment]
I just found out that it only happens when ClearURLs is enabled. Disabling it then restarting the browser doesn't have the issue.

**Comment by AdamWr** [comment]
Fixed, please update filters.

Thank you for your report.
