### ISSUE TITLE
yahoo.com - ads- Android 

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6574]
***Description***:
* **Current behaviour**: 

Yahoo ads on Android. Not reproduced 

<details><summary>Screenshot:</summary>

![screenshot_2017-09-01-20-40-46](https://user-images.githubusercontent.com/28784344/29999004-afd9b9c0-9041-11e7-9be9-3bf9417559d5.png)

</details><br/>

***System configuration***

**Filters:**

Information                         | Value
---                                 | ---
Operating system:                   | Android
AdGuard version:                    | 2.10.16
Filters enabled:                    | 2, 3, 4, 14, 11 
Filtering quality (Android only):   | High-quality
HTTPS filtering (Android only):     | On (Default/) 
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1574702

logs are attaches in the ticket

**Comment by Alex-302** [comment]
Please ask for HAR file.
***Don't*** upload it to GitHub.

**Comment by ypetruk** [comment]
@Alex-302 asked for the har files

**Comment by veronikasav** [comment]
@Alex-302 asked for the har files again if the issue still persists

**Comment by evgeniy-ADG** [comment]
> Проблема решилась - после обновления iOS по какой-то причине отключился AdGuard в настройках Safari.
