### ISSUE TITLE
business-standard.com - Anti-Adblock script - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6575]
***Description***:
* **Current behaviour**: 
http://www.business-standard.com/article/politics/why-modi-is-keen-on-3rd-final-cabinet-reshuffle-before-2019-polls-117090100348_1.html 
Reproduced on our side (Mac OS)

<details><summary>Screenshot:</summary>

![screen shot 2017-09-03 at 12 56 44 am](https://user-images.githubusercontent.com/28784344/29999050-148fcf16-9043-11e7-8c2b-30ecc7d1eea4.png)

</details><br/>

***System configuration***

**Filters:**

Information                         | Value
---                                 | ---
Operating system:                   | Mac os
Browser:                            | chrome
AdGuard version:                    | 1.4.1
Filters enabled:                    | 1,2,3,4,14
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1354655

**Comment by Alex-302** [comment]
Fixed
