### ISSUE TITLE
corneey.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6578]
***Site***: http://corneey.com/q4IlcS
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30001810-70638840-9099-11e7-93dd-580dcc2c9098.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by XX-J** [comment]
АнтиАдблок:
`corneey.com##.information-container`

**Comment by Alex-302** [comment]
не надо это делать, лишние уведомления почту заваливают. Всё равно не добавлю в обозримом будущем.

**Comment by XX-J** [comment]
Что не надо делать? Что не так с этим челом?

**Comment by Alex-302** [comment]
В задачах отвечать. Хотя бы в тех, где всё просто)
Очереди ждёт.

**Comment by AdamWr** [comment]
Fixed.
