### ISSUE TITLE
adshorte.com - Annoyance - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6579]
***Site***: http://adshorte.com/Xau4fP
***Description***: Adblock detection and annoyance video.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30001825-f01bb396-9099-11e7-92c1-dc31323db941.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Annoyance video fixed.
I can't reproduce adblock detection, but please check this rule:
`@@||adshorte.com/js/ads.js`

**Comment by Alex-302** [comment]
@AdamWr it works.

**Comment by AdamWr** [comment]
Ok, thank you for checking it.
