### ISSUE TITLE
karanpc.com - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6580]
***Site***: http://karanpc.com/syncios/
***Description***: Fake download button.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30001839-39f93c2c-909a-11e7-86fd-a813c1f8c8a5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by XX-J** [comment]
Скрытие кнопки:
`karanpc.com##center`

Я-бы ещё блок "FOLLOW US" скрыл:
`karanpc.com##.zoom-social-icons-widget`
и поместил-бы это правило в "Фильтр виджетов социальных сетей".

**Comment by Alex-302** [comment]
That button is blocked by English filter.

@XX-J простые ссылки на блоги не блокируем.
