### ISSUE TITLE
Prensa Ibérica news sites - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6586]
***Description***: Adblock detection of Prensa Ibérica news sites (https://www.epi.es/)

- http://www.diariodeibiza.es/
- http://www.diaridegirona.cat/
- http://www.emporda.info/
- http://www.lne.es/
- http://www.mallorcazeitung.es/
- http://www.superdeporte.es/
- http://www.laopinion.es/
- http://www.laopiniondezamora.es/
- http://www.laopinioncoruna.es/
- http://www.laopiniondemalaga.es/
- http://www.laopiniondemurcia.es/
- http://www.regio7.cat/
- http://www.laprovincia.es/
- http://www.diarioinformacion.com/

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30001891-f0dbf60e-909b-11e7-95c5-7e43d08134bd.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
Adguard version: | 6.2.390.2018
Adguard driver (Windows): | WFP
Simplified filters(iOS) | Off
Adguard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

Adguard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
Spanish/Portuguese filter

**Comment by AdamWr** [comment]
Fixed.
