### ISSUE TITLE
Search ads in play store

### ISSUE THREAD

**Issue by techIndia-hacker** [AdguardTeam/AdguardFilters#65880]
### Issue URL (Ads)
https://play.google.com/store/search?q=music%20player
### Comment
Username: @techIndia-hacker
> I have root access and https quality filtering is active system wide. How does these ads break in play store. 😏
> --
> The information below is automatically generated. Do not delete it.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/BnzZXSS.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v3.5.1 (65)
Browser: | Play store
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Strip URLs from tracking parameters, <br/>Block third-party Authorization header, <br/>Self-destructing first-party cookies (4320), <br/>Self-destructing third-party cookies (180), <br/>Disable cache for third-party requests, <br/>Block WebRTC, <br/>Block Push API, <br/>Block Location API, <br/>Hide your Referrer from third-parties (), <br/>Hide your Referrer from third-parties, <br/>Hide your User-Agent ()
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> Fanboy's Enhanced Tracking List, <br/>AdGuard Tracking Protection, <br/>EasyPrivacy<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Fanboy's Annoyances, <br/>Adblock Warning Removal List, <br/>AdGuard Annoyances
Custom filter subscriptions: |

_Originally posted by @adguard-bot in https://github.com/AdguardTeam/AdguardFilters/issue_comments/711534490_

**Comment by Alex-302** [comment]
Hi
Please record HAR file + actual screenshots with ads
https://kb.adguard.com/ru/android/solving-problems/har
and send to `filters@adguard.com`

**Comment by techIndia-hacker** [comment]
Sent

**Comment by Alex-302** [comment]
Ok, will check.

**Comment by Alex-302** [comment]
Cannot be blocked. They use protobuf:(
