### ISSUE TITLE
Continuation of mapquest.com #65369

### ISSUE THREAD

**Issue by tecumsa** [AdguardTeam/AdguardFilters#65903]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
Read the prior report for background, it was closed without verifying that it was fixed.

* **Current behaviour**: 
Under 65369 not blocking (see image) the Your Route section of the screen (left sidebar) was fixed. However, in doing so it is allowing ads to be shown both in the sidebar and on the main map, see the attached image.

![image](https://user-images.githubusercontent.com/58710687/96470144-f7653280-11fb-11eb-9e4b-2e5078a05152.png)
</details><br/>

* **Expected behaviour**: 

The Your Route should remain, but the ads should be removed.

<details><summary>Screenshot:</summary>

</details><br/>

***Steps to reproduce the problem***:

Go to 

https://www.mapquest.com

To see the ads. To get the Your Route you will have to have an account, create a map, then view the directions, that is when Your Route appears.

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)
![image](https://user-images.githubusercontent.com/58710687/96470572-6f335d00-11fc-11eb-86c7-04d3f28528c9.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Mac Catalina
Operating system version (Android/iOS) | 10.15.7
Browser:                               | Safari
AdGuard version:                       | 1.8.2
Filters enabled:                       | Ad Blocking, Privacy
AdGuard DNS:                           | None / Default / Family Protection - Not sure where to find this.

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@tecumsa Hi. I cannot reproduce with your settings win EU and US VPN.
Do you live in USA? Could you please copy full URL from address bar?

**Comment by tecumsa** [comment]
Yes, I am in the US.

Okay, here is the URL of the main site where you can see ads on the sidebar and main map.

https://www.mapquest.com

![image](https://user-images.githubusercontent.com/58710687/96584196-e1af4600-12ab-11eb-8bef-b87b5a427d3a.png)


Here is the URL showing the Your Maps

https://www.mapquest.com/directions/from/us/pa/pittsburgh/15239-2416/210-fiesta-dr-40.474446,-79.708577/to/us/pennsylvania/swatara-state-park-304146065/to/us/pennsylvania/nockamixon-state-park-swimming-pool-346397420/to/us/pennsylvania/jacobsburg-state-park-and-environmental-education-center-265815664/to/us/pa/swiftwater/18370-7746/2174-route-611-a-41.080419,-75.327597/to/us/pa/pittsburgh/15239-2416/210-fiesta-dr-40.474446,-79.708577?unit=m&routeType=fastest

If that is too large of a URL here is a tiny one

https://tinyurl.com/y3wo9w5v

![image](https://user-images.githubusercontent.com/58710687/96584399-29ce6880-12ac-11eb-84c9-b681109a6eac.png)

**Comment by Alex-302** [comment]
Weird. Still not reproduced, with US IP, your settings and account on the site.

Do you see ads when logged out? If "yes", please save page and send to filters@adguard.com

Also you can try to disable-enable content blockers in Safari settings and restart Safari, and check for filters update.
Do not close AdGuard window 30-60 seconds.

**Comment by Alex-302** [comment]
Also please test these rules in user filter:
```
mapquest.com##.directions-ad
mapquest.com##.main-ad-728x90-container
```
Also please wait 30 seconds after add.

**Comment by tecumsa** [comment]
Yes, I do see the ads when I am logged out, see attached.

Mike

The universal aptitude for ineptitude makes any human accomplishment an incredible miracle. - Stapp’s Law

**Comment by tecumsa** [comment]
I do not understand these instructions:

> Also you can try to disable-enable content blockers in Safari settings and restart Safari, and check for filters update.
> Do not close AdGuard window 30-60 seconds.
> 
Do not close AG window 30-60 seconds?


Mike

It is by going down into the abyss that we recover the treasures of life.— Joseph Campbell

**Comment by tecumsa** [comment]
Okay, all is working down. The disable/enable of the content blocker worked. Thanks.

Mike

"When I'm good, I'm very good, but when I'm bad, I'm better. ” - Mae West

**Comment by Alex-302** [comment]
So ads are blocked now?



> Do not close AG window 30-60 seconds?

I mean AdGard settings window.

**Comment by tecumsa** [comment]
Yes, and the Your Route shows as it should. Many thanks.

Mike

“The way I see it, if you want the rainbow, you gotta put up with the rain.” - Dolly Parton

**Comment by Alex-302** [comment]
Great)
