### ISSUE TITLE
nova.cz - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6591]
***Site***: http://tn.nova.cz/clanek/tabor-kde-mel-nekdo-osahavat-deti-vypsal-na-pachatele-odmenu.html
***Description***: Video won't load. Same for every *.nova.cz site

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30002046-2ae369b4-90a0-11e7-9cf8-0958795c010a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
