### ISSUE TITLE
braze.com

### ISSUE THREAD

**Issue by privacy-advo** [AdguardTeam/AdguardFilters#65920]
Issue: Tracking
braze.com is only to be found in the "Annonyances" filter.
https://github.com/AdguardTeam/AdguardFilters/search?q=braze.com

But it's a powerful Tracking-Service. Espcially on mobile devices.

**Comment by Alex-302** [comment]
Where exactly is it used? Need real examples.

**Comment by privacy-advo** [comment]
Hi Alex,
see my dns log.
https://ibb.co/6vCXDSb
The domain in my log is pretty straight forward:
sdk.iad-03.braze.com

Energized.pro lists also list:
sdk.iad-01.braze.com
sdk.iad-02.braze.com
[0-9] ...

And many other *.iad-[0-9].braze.com

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/f91728ce8a5c00175bbd2b5cff80b01b0fd7b7fd
it used for popups

**Comment by privacy-advo** [comment]
> 
> 
> [f91728c](https://github.com/AdguardTeam/AdguardFilters/commit/f91728ce8a5c00175bbd2b5cff80b01b0fd7b7fd)
> it used for popups

Thanks for the additional info.
