### ISSUE TITLE
anistar.me - Missed Ad

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardFilters#6592]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 
ads of Hunter rpg and video ads while playing from the videoplayer

[//]: # (Substitute this line with a description of the problem)

[//]: # 
![image](https://user-images.githubusercontent.com/30834067/30002209-26bea536-90ac-11e7-9da1-644f6d76cb5a.png)
![image](https://user-images.githubusercontent.com/30834067/30002210-2f05afbe-90ac-11e7-890e-cdffb71774de.png)

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome extension
AdGuard version:                    | 
AdGuard mode (Android only):        | VPN / Proxy (manual/auto)
Filtering quality (Android only):   | High-quality / High-speed / Simplified
HTTPS filtering (Android only):     | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)       | On / Off
AdGuard DNS:                        | None / Default / Family Protection
Stealth mode options (Windows only) | ?
Helpdesk ID (if exists):            | 1622805

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed,
