### ISSUE TITLE
Amazon Embeds being hidden on kinjadeals.theinventory.com

### ISSUE THREAD

**Issue by sdschramm** [AdguardTeam/AdguardFilters#65933]
***Steps to reproduce the problem***:
With only AdGuard Base enabled and all other filters and lists disabled, the Amazon embeds are being hidden on kinjadeals.theinventory.com

I narrowed it down to this: 

> ! https://github.com/AdguardTeam/AdguardFilters/issues/52236
> theinventory.com,thetakeout.com,theonion.com,splinternews.com,clickhole.com,avclub.com,deadspin.com,gizmodo.com,jalopnik.com,jezebel.com,kotaku.com,lifehacker.com,theroot.com##+js(abort-on-property-read, _mNDetails)

***Screenshots***:
Before and after:  https://imgur.com/a/j6S9VmK

***Steps to reproduce the problem***:
Visit any page on kinjadeals.theinventory.com/ such as [this one.](https://kinjadeals.theinventory.com/sundays-best-deals-bio-bidet-seats-asos-fall-apparel-1845406281)

***System configuration***
Firefox 81.0.2
macOS Mojave 10.14.6

**Filters:**
Only occurs when AdGuard Base is enabled.

**Comment by AdamWr** [comment]
Hi,

Are you sure that it's caused by mentioned rule?
On my end these elements are hidden by this rule:
```
avclub.com,clickhole.com,deadspin.com,gizmodo.com,jalopnik.com,jezebel.com,kotaku.com,lifehacker.com,splinternews.com,theinventory.com,theonion.com,theroot.com,thetakeout.com##a[data-ga*='Commerce Inset']
```

**Comment by sdschramm** [comment]
I know 100% that AdGuard Base is causing the issue, but I am not 100% sure it is the particular rule I mentioned, I just know that one came up in the logs over and over again. 

To narrow it down, is there any way I can disable that particular rule but leave the rest enabled?

**Comment by AdamWr** [comment]
You can add this exception rule in uBO to "my filters":
```
avclub.com,clickhole.com,deadspin.com,gizmodo.com,jalopnik.com,jezebel.com,kotaku.com,lifehacker.com,splinternews.com,theinventory.com,theonion.com,theroot.com,thetakeout.com#@#a[data-ga*='Commerce Inset']
```
and then check if you can still reproduce this issue.

**Comment by sdschramm** [comment]
I re-enabled AdGuard Base and refreshed the page, and the embeds were broken. 
I then added the line you provided above into my filters, saved it, refreshed the page, and the embeds displayed correctly again. 
So now I am 100% confident that is the filter causing the issue.

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
Thank you for your answer.

**Comment by sdschramm** [comment]
Confirmed fixed. Thank you for the fast response and action!
