### ISSUE TITLE
 https://mamahd.tv/ - AdBlock Script - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6593]
***Description***:
* **Current behaviour**: 

https://mamahd.in/p/mama.php?id=17816 - AdBlock script on windows 
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/28784344/30003618-e1c25f1e-90c8-11e7-9009-581641e07565.png)

</details><br/>

***System configuration***

**Filters:**

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 1,2,3,4,5,14
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1622733

**Comment by FadeMind** [comment]
![image-20170903-002](https://user-images.githubusercontent.com/9846948/30003805-dfa8099a-90c3-11e7-8a7c-8d54d4043a5f.png)

WARNING This LINK is danger. Blocked with ESET.

**Comment by Alex-302** [comment]
Fixed.

**Comment by evgeniy-ADG** [comment]
It's back, the English filter is up to date.

**Comment by Alex-302** [comment]
fixed
