### ISSUE TITLE
https://www.google.de/amp/t3n.de/news/ - ad leftover

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6595]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://www.google.de/amp/t3n.de/news/samsung-gear-sport-2017-852461/amp/

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30004335-daf4e316-90d5-11e7-97be-5e732b7f6ef8.png)

</details><br/>

***Steps to reproduce the problem***:

1. Follow the link: https://www.google.de/amp/t3n.de/news/samsung-gear-sport-2017-852461/amp/
2. Scroll down
3. See the grayed placeholder

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.29.63 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.26 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.22.74 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.17.74 Enabled=YES
- ID=6 Name="German filter" Version=1.0.36.49 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.51 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
- ID=238 Name="Adblock & uBlock polish filter - Adguard supplement" Version=1.0.0.3 

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | 1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I need a source link. Where user found this URL?

**Comment by evgeniy-ADG** [comment]
I think this is the news service google provides in certain countries, no? The link I specified in the description, it is not what you need? I can replicate the issue with that link on iPhone.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
>I think 
please ask for the source. I don't want to duplicate the rules for all sites on google domains.

**Comment by evgeniy-ADG** [comment]
What do you mean "the source"? I don't understand.

**Comment by evgeniy-ADG** [comment]
It redirects to http://t3n.de/news/samsung-gear-sport-2017-852461/ if you open this on desktops, is this what you need?

**Comment by Alex-302** [comment]
No. Where user found that link?

**Comment by evgeniy-ADG** [comment]
Ok, I'll ask about that.

**Comment by theBeautifier** [comment]
@Alex-302 You could just google „t3n news“ and you will find plenty Google AMP sites:

![55728f72-d22f-497b-804d-499cf9c22fcd](https://user-images.githubusercontent.com/28259813/30231942-a5a089b0-94ed-11e7-8881-1e7f63af47e3.jpeg)

**Comment by Alex-302** [comment]
Temporary rule - for custom filter
```
google.de##amp-iframe
```
