### ISSUE TITLE
http://www.sport.de/ - missed ad, incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6597]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: The link: http://www.sport.de/

Missed self-advertising, some pictures do not load properly

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30004429-aaa3e070-90d7-11e7-9506-b54eaa95e65e.png)

</details><br/>

***System configuration***

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.29.63 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.26 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.22.74 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.17.74 Enabled=YES
- ID=6 Name="German filter" Version=1.0.36.49 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.51 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
- ID=238 Name="Adblock & uBlock polish filter - Adguard supplement" Version=1.0.0.3 

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | 1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by XX-J** [comment]
Неподгружающиеся картинки. Причина: Английский фильтр, правило:
`||cdnjs.cloudflare.com/ajax/libs/postscribe/*/postscribe.min.js`
Исправление:
`@@||cdnjs.cloudflare.com/ajax/libs/postscribe/*/postscribe.min.js$domain=sport.de`

 Пропущенная самореклама:
`||sport.de##[data-key="138"]`
Лучше-бы, конечно, `||sport.de##div:has(.hs-app)` (не привязано к цифрам, которые могут меняться), но НЕ работает, скрывая ВСЮ страницу (может это БАГ в Adguard'e?). `||sport.de##.hs-app` скрывает саморекламу оставляя после себя пустой квадрат DIV'a. Вот кусок кода, для анализа "почему НЕ работает `||sport.de##div:has(.hs-app)` ?":
`<div class="hs-col hs-col-l-4 hs-col-m-6 hs-col-s-12" data-key="138"><a class="hs-app" href="/app" title="sport.de-app für iOS & Android"><img src="http://s.weltsport.net/comon/prj/isdc/v2/sportde/static/gfx/app/app-box.png" width="320" height="320" alt="sport.de-app für iOS & Android" title="sport.de-app für iOS & Android" /></a></div>`

**Comment by Alex-302** [comment]
> скрывая ВСЮ страницу (может это БАГ в Adguard'e?)

оно скрывает первый DIV, внутри которого есть указанный в HAS элемент. Надо так:
```
sport.de##.hs-top-news+.hs-kachelliste > div.hs-col.hs-col-s-12[-ext-has='> a.hs-app']
```
т.е. сперва указать селектор для элемента, который нужно скрыть, а потом уже в HAS - селектор для элемента, который должен находиться внутри искомого. Но на iOS это не работает.
`||` в правилах сокрытия не нужны.

Добавил первое и `sport.de##.hs-app`
