### ISSUE TITLE
http://m.spox.com/ - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6599]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: The full link: http://m.spox.com/de/sport/mehrsport/basketball/1706/Artikel/basketball-em-2017-alle-infos-spielplan-termine-favoriten-tv-sender-nowitzki.html

The highlighted banner redirects to some other site.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30004484-87c0f060-90d8-11e7-819a-accefe36c687.png)

</details><br/>

***System configuration***

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.29.63 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.26 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.22.74 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.17.74 Enabled=YES
- ID=6 Name="German filter" Version=1.0.36.49 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.51 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
- ID=238 Name="Adblock & uBlock polish filter - Adguard supplement" Version=1.0.0.3 

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | 1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added
```
spox.com##.fullrow > div.cmp
spox.com##.rc > div[class="cmp"]
spox.com##.stick > div[class="cmp"]
spox.com##.daznhm.maxwidth
```
