### ISSUE TITLE
msn.com - Ad leftover - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6600]
***Description***:
* **Current behavior**: 

As shown, when google chrome is first opened, ads are blocked as they are supposed to be.
 When I click on anything and then use the back button to return to the previous page, ads are no longer blocked. It does happen every time without fail. In the event you are not sure what ads I am talking about, if you look at the top right part of the first and last screen shot, you will see an ad that says, "sponsored".
Reproduced on our side

<details><summary>Screenshot1:</summary>

![new page 1](https://user-images.githubusercontent.com/28784344/30005363-a5c1e0d6-90e9-11e7-81d2-05d3e09c0d81.jpg)

</details><br/>

<details><summary>Screenshot2:</summary>

![opened page 2](https://user-images.githubusercontent.com/28784344/30005365-b009b910-90e9-11e7-9305-a7f019a9c16b.jpg)

</details><br/>

<details><summary>Screenshot3:</summary>

![back button used 3](https://user-images.githubusercontent.com/28784344/30005369-c5ae977c-90e9-11e7-9e6d-7acb3cac1f99.png)

</details><br/>

***System configuration***

**Filters:**

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | chrome
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 1,2,3,4,5,10,14
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | 1543949

**Comment by Alex-302** [comment]
Please check this rule:
```
msn.com##.mediumcard-placeholder
```

**Comment by evgeniy-ADG** [comment]
sent to the customer

**Comment by vitbortnik** [comment]
> Thank you for the solution, however it has not completely fixed the problems that I am having. While yes, it has removed the front page sponsor of MSN ads, if you look in my screenshots that I have provided, I am now having issues with other things now. When opening my browser, under the search bar it shows my recent searches (see Pg.1). When I click into any link on the page, (see Pg.2) a sponsored link still appears. Now if you see pg.3, the back button is pressed to return to pg.1 where also my recent searches have disappeared. I would really appreciate a solution which solves all these issues, and makes your program Ad Guard work the way that its suppose to.

<details><summary>Screenshot (pg1):</summary>

![image](https://user-images.githubusercontent.com/30041399/30247135-5b63fe62-9615-11e7-9422-67592314daa3.png)

</details>


<details><summary>Screenshot (pg2):</summary>

![image](https://user-images.githubusercontent.com/30041399/30247136-6345ff86-9615-11e7-92ca-98677f488372.png)

</details>

<details><summary>Screenshot (pg3):</summary>

![image](https://user-images.githubusercontent.com/30041399/30247139-6db7221a-9615-11e7-8142-4531a13f58fc.png)

</details>

**Comment by Alex-302** [comment]
I can't reproduce the second issue.
@AdamWr please check on your end.

**Comment by AdamWr** [comment]
I can't reproduce, but this website use IL script, so if I'm not wrong, in stable version of AdGuard we can't remove this script, because there is a limit. And it is probably because of this, user see these ads.
