### ISSUE TITLE
streamplay.gdn - Anti adblock

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6601]
https://streamplay.gdn/xp1l2j32srxf

<details><summary>Screenshot:</summary>

<img width="397" alt="screen shot 2017-09-04 at 1 41 09 am" src="https://user-images.githubusercontent.com/27292111/30007212-2c8b1984-9112-11e7-8f3c-13fceab9e986.png">

</details><br/>

***System configuration***

Application version: 1.2.1.71
Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.29.48 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.26 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.69 Enabled=YES
ID=9 Name="Spanish/Portuguese filter" Version=1.0.87.3 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.51 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.2.13 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.86.71 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES

If I disable 207/211 filters I still can not reproduce the issue.

Helpdesk ID:   1612401

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. Please try
```
@@||streamplay.gdn^$generichide
```

**Comment by veronikasav** [comment]
Forwarded to the customer.
