### ISSUE TITLE
sgxnifty.org - Anti Adblock

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6602]
https://sgxnifty.org/

<details><summary>Screenshot:</summary>

<img width="399" alt="screen shot 2017-09-04 at 1 58 29 am" src="https://user-images.githubusercontent.com/27292111/30007315-9eddb3fa-9114-11e7-90a9-42f644f20563.png">

</details><br/>

***System configuration***

OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.29.66 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.27 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.74 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.75 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES

Helpdesk ID: 1623193

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
