### ISSUE TITLE
jeanmarcmorandini.com - Video blocking 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6603]
http://www.jeanmarcmorandini.com/article-372208-catherine-et-liliane-briefent-yves-calvi-avant-son-arrivee-demain-a-19h00-sur-canal-plus-avec-sa-nouvelle-emission-regardez.html

French filter blocks the video on this website.

<details><summary>Screenshot:</summary>

<img width="361" alt="screen shot 2017-09-04 at 4 59 26 am" src="https://user-images.githubusercontent.com/27292111/30009048-e6fc2c0c-912d-11e7-90d9-e49b00b611a2.png">

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPad
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.29.16 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.58 Enabled=NO
ID=4 Name="Social media filter" Version=1.0.20.4 Enabled=NO
ID=16 Name="French filter" Version=1.0.7.13 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES

Helpdesk ID:    1623162

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by XX-J** [comment]
Причина блокировки видео: Французский фильтр, правило:
`||videostep.com^$third-party`
Соответственно разблокировка:
`@@||kweb.videostep.com^$domain=jeanmarcmorandini.com`

**Comment by Alex-302** [comment]
Добавил.
