### ISSUE TITLE
koronapay.com - Tracking

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#6604]
Добавить в "Фильтр счетчиков и системы аналитики":
`||koronapay.com/*/metrika_rus.js`

А заодно можно и в "Фильтр раздражителей" добавить правило, убирающее проверку на минимальную версию браузера, с показыванием предупреждения вверху страницы:
`||koronapay.com/*/detect.min.js`
___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard legacy v2.7.1
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Первое добавил, второе не стоит, т.к. сайт финансовый, и в старом браузере может случиться какой-нибудь конфуз.
