### ISSUE TITLE
r10.net 

### ISSUE THREAD

**Issue by FOXIY** [AdguardTeam/AdguardFilters#66051]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Issue URL (Ads)***:
https://www.r10.net

<details><summary>Screenshot:</summary>

https://prnt.sc/v3uwtx
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

https://prnt.sc/v3uwtx
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Which AdGuard?

**Comment by 0xbkt** [comment]
Can't reproduce this with latest AdGuard Android and Turkish language filter.

**Comment by FOXIY** [comment]
Hello

still have r10.net with adguard.

Berkant Ipek <notifications@github.com>, 21 Eki 2020 Çar, 18:55 tarihinde
şunu yazdı:

**Comment by FOXIY** [comment]
> Which AdGuard?
Adguard Chrome Mac

**Comment by FOXIY** [comment]
version : 3.5.12

**Comment by 0xbkt** [comment]
@FOXIY Is **AdGuard Turkish filter** enabled in your AdGuard settings?

You can go to extension settings and follow **Filters > Language-specific** there.

Alternatively, paste the link below to your address bar and enable the Turkish filter there.

`chrome-extension://bgnkhhnnamicmpeenaelnjfhikgbkllg/pages/options.html#antibanner7`

**Comment by FOXIY** [comment]
Berkant evet etkin

ama r10 üzerinde hala o uyarı çıkıyor

Berkant Ipek <notifications@github.com>, 21 Eki 2020 Çar, 20:13 tarihinde
şunu yazdı:

**Comment by 0xbkt** [comment]
Reach me at berkant.ipek@gmail.com and I will have a look.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: FOXIY <notifications@github.com> Date: 10/21/20  20:17  (GMT+03:00) To: AdguardTeam/AdguardFilters <AdguardFilters@noreply.github.com> Cc: Berkant Ipek <berkant.ipek@hotmail.com>, Comment <comment@noreply.github.com> Subject: Re: [AdguardTeam/AdguardFilters] r10.net  (#66051) 

Berkant evet etkin



ama r10 üzerinde hala o uyarı çıkıyor



Berkant Ipek <notifications@github.com>, 21 Eki 2020 Çar, 20:13 tarihinde

şunu yazdı:

**Comment by YngwieMalmsteen** [comment]
@FOXIY 
Uzantıdaki raporlama aracı üzerinden rapor gönderin bir dahaki sefere. Sorunların çözümü için ayarlarınız, uzantı türü ve filtreleriniz gerekli.

https://kb.adguard.com/en/technical-support/reporting-tool

<details><summary>Screenshot:</summary>

![github com](https://user-images.githubusercontent.com/34379403/96774740-2099e480-13ef-11eb-8794-cfb4cce65a5b.png)


</details>
