### ISSUE TITLE
css filter's bug

### ISSUE THREAD

**Issue by wellser** [AdguardTeam/AdguardFilters#6605]
when i visit this site :

https://m.baidu.com/s?word=linux&ts=4033925&t_kt=0&ie=utf-8&rsv_iqid=2019498619&rsv_t=ba70n286S+Wx7jAFOouS1fG2QyW+Lp7YE3m/k4HwUeGaDbLtO2L2&sa=ib&rsv_pq=2019498619&rsv_sug4=6107&inputT=895&ss=100

you can see a advertisment named "广告", after i recheck the code , i find it contains a div which has a css named "ec_ad_results".
next step , i use this rule "||baidu.com^##.ec_ad_results" to block it , but i find it does not work.
i find some answer about this on the internet , it seems that ,beacuse of the div using a style named "!important" , so it can take the rule to be invalid .

please , fix this bug.

**Comment by Alex-302** [comment]
Answered in your first issue.
