### ISSUE TITLE
[nsfw] http://www.pictoa.com/ - ads boxes, popups

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6606]
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Google Chrome 60.0.3112.113
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
AdGuard DNS:                        | N/A
Stealth mode options (Windows only) | Enabled (only self deleting cookies is disabled)
Helpdesk ID (if exists):            | N/A
**Site with ad sample 1**|  http://www.pictoa.com/albums/sexy-wives-and-girlfriends-15-2117067/39825674.html
**Site with ad sample 2**|  http://www.pictoa.com/albums/grannies-matures-milf-housewives-amateurs-34-578201/9738473.html

### Screenshoot:
![image-20170904-001](https://user-images.githubusercontent.com/9846948/30031307-1dd9a93a-9191-11e7-8ebd-5714cbf5f2e3.png)

NOTE: On right side are 2 boxes for ads. sometimes filled up is one box.

**Comment by AdamWr** [comment]
Fixed.

**Comment by FadeMind** [comment]
@AdamWr  @Alex-302  please reopen, same issue (box on right after open random image)

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Opera Stable
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
Stealth mode options (Windows only) | Enabled (only self deleting cookies is disabled)
Site Sample | http://www.pictoa.com/albums/amateur-milf-402-1489978/27026764.html

![2017-09-19 11_55_39-sklep](https://user-images.githubusercontent.com/9846948/30586866-a4e8403e-9d31-11e7-9c08-015cb4ece7f6.png)

**Comment by AdamWr** [comment]
Fixed.
