### ISSUE TITLE
SoundCloud app trackers ios

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#66061]
app-measurement.com (seen in multiple apps)
iad-01.braze.com
firebaselogging.googleapis.com
delivery-cdn-cf.adswizz.com
appboy-images.com (braze.com ad domain)

I figured I’d post this in the right section. Some appear in log right away some take a while of listening to music in app.

**Comment by Alex-302** [comment]
> braze.com
> firebaselogging.googleapis.com 

not trackers

> delivery-cdn-cf.adswizz.com
> appboy-images.com

added

**Comment by jordanelliott23** [comment]
sorry to be so persistent but could we add app-measurement.com it is a tracker. i see it in like every app. 😅 @Alex-302

**Comment by jordanelliott23** [comment]
@Alex-302 also sorry i guess adswizz is in the exclusions list. i will start checking these before i post my bad. https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/Filters/exclusions.txt
