### ISSUE TITLE
Подозрительные домены

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#66075]
Здравствуйте!
Прошу заблокировать вредоносные сайты приведённые ниже:

https://m.parimatch.net/ (мошенничество)
https://m.parimatch.site/ (мошенничество)
https://m.parimatch.online/ (мошенничество)
https://m.parimatch.kz/ (мошенничество)
https://m.parimatch.en/ (мошенничество)
https://m.parimatch.co/ (мошенничество)
https://m.parimatch.ru/
(Мошенничество)
https://m.parimatch.org/ (мошенничество)
https://m.parimatch.xyz/ (мошенничество)

**Comment by lolka4toli** [comment]
Blacklisted.
