### ISSUE TITLE
Вредоносные домены

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#66074]
Здравствуйте!
Прошу заблокировать вредоносные сайты приведённые ниже:

https://pm.com.ua/ (мошенничество)
https://m.sports.ru/betting/ratings/parimatch/ (мошенничество)
https://m.pm.by/#registration/2 (фишинг личных данных для спама в смс)
https://m.parimatch.com/ (мошенничество)
https://m.parimatch.top/ (мошенничество)

**Comment by lolka4toli** [comment]
sports.ru is ok, other ones are blocked for now.
