### ISSUE TITLE
Развод!!!!

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#66079]
Здравствуйте!
Прошу принять меры!

https://bookmakerbets.com.ua/melbet
https://www.vl.ru/melbet
https://transense.com/2020/05/06/%D1%82%D0%B5%D0%BA%D1%83%D1%89%D0%B5%D0%B5-%D0%B7%D0%B5%D1%80%D0%BA%D0%B0%D0%BB%D0%BE-melbet-%D0%B2-%D0%BD%D0%B0%D1%81%D1%82%D0%BE%D1%8F%D1%89%D0%B5%D0%B5-%D0%B2%D1%80%D0%B5%D0%BC%D1%8F/
https://betonmobile.com.ua/ru/bukmekerskaya-kontora-melbet
https://social.bet/bookmakers/melbet/
https://albouroapartments.com/2020/06/01/%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE-%D0%BA%D0%B0%D0%BA-%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C%D1%81%D1%8F-%D0%BD%D0%B0-melbet/
https://melbet.com.ua/amp/
https://turnir.ua/1024-melbet/
https://melbet.mobi/ru/
https://m.ua.tribuna.com/tribuna/blogs/melbet/
https://ua1.com.ua/bookmakers/melbet
https://prognozy-bk.ru/bookmakers/melbet/amp/
https://ratingbet.com/amp/bookmaker/myelbyet-obzor-bukmyekyerskoy-kontory-melbet.html

**Comment by lolka4toli** [comment]
vl.ru, albouroapartments.com and transense.com are ok, other are blocked for now.
