### ISSUE TITLE
Вредоносные сайты!!!

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#66072]
Здравствуйте!
Прошу заблокировать вредоносные сайты приведённые ниже:

https://bet1x2.club/bukmekery/obzor-bukmekerskoj-kontory-pari-match/
https://www.strategya.com/parimatch/ (распространение вирусов)
https://pokermatch.com/ru (мошенничество)
http://parimatch.ua/ (мошенничество)
https://parimatch.global/ (мошенничество)

**Comment by lolka4toli** [comment]
strategya.com is ok, other ones are blocked for now.
