### ISSUE TITLE
Мошенничество!

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#66076]
Здравствуйте!
Прошу заблокировать вредоносные сайты приведённые ниже:

https://m.parimatch.pro/ (мошенничество)
https://m.parimatch.mobi/ (мошенничество)
https://m.parimatch.info/ (мошенничество)
https://m.parimatch.biz/ (мошенничество)
https://m.parimatch.com/ (мошенничество)

**Comment by lolka4toli** [comment]
Blacklisted.
