### ISSUE TITLE
Развод на бабки!

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#66078]
Здравствуйте!
Прошу заблокировать!

https://freesoft.ru/android/melbet
https://tennis-bet.ru/bets/igry-melbet-obzor-biblioteki/
https://melbet-partners.com/ru/
https://www.tcpgrp.com/melbet-%D0%BE%D0%B1%D0%B7%D0%BE%D1%80-%D0%B1%D1%83%D0%BA%D0%BC%D0%B5%D0%BA%D0%B5%D1%80%D1%81%D0%BA%D0%BE%D0%B9-%D0%BA%D0%BE%D0%BD%D1%82%D0%BE%D1%80%D1%8B-melbet/
https://bonus-betting.ru/bukmekery/melbet/
https://www.footboom.by/betting/bookmaker/melbet
https://melbet.pro/
https://topbet.ru/melbet/

**Comment by lolka4toli** [comment]
freesoft.ru and tcpgrp.com are ok, other ones are blocked for now.
