### ISSUE TITLE
[nsfw] [ad overlay on player] javfinder.to

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6607]
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Google Chrome 60.0.3112.113
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
AdGuard DNS:                        | N/A
Stealth mode options (Windows only) | Enabled (only self deleting cookies is disabled)
Helpdesk ID (if exists):            | N/A
**Site with ad sample 1**|  https://javfinder.to/movie/watch/skyushiroto-saba-285-jav-beautiful-girl-newborn-first-shot-high-school-level-ochi.html

Skip Ad/Continue box on player right down

### Screenshoot:
![image-20170904-003](https://user-images.githubusercontent.com/9846948/30032401-04bd1f68-9196-11e7-94ab-8808ee302b65.png)

**Comment by AdamWr** [comment]
Fixed.

**Comment by FadeMind** [comment]
@AdamWr  domain was changed
`javfinder.is`

Sample >> https://javfinder.is/movie/watch/10musume-101417-01-miki-nakaya-amateur-gachinanpa-i-lost-to-the-temptation-of-rewards-and-followed-it.html

**Comment by AdamWr** [comment]
Ok, thank you, added.

**Comment by FadeMind** [comment]
@AdamWr new domain `javfinder.sh`

**Comment by Alex-302** [comment]
fixed
