### ISSUE TITLE
Мошеннические домены

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#66081]
Здравствуйте!
Прошу заблокировать!

https://bukmeker-expert.info/bukmakers/melbet/
https://melbet-bk.ru/
https://melbet-affiliate.com/ru/
https://www.footboom.com/amp/betting/bookmaker/melbet
https://www.ua-football.com/betting/bookmakers/9-bukmeker-melbet/registratsiya
https://m.melbet.ru/
http://www.telemetr.me/content/pmpoker/7
https://3snet.co/poker/pokermatch/
http://ukrfootball.com.ua/blogs/admin/kak-igrat-na-pokermatch-na-grivny
http://ngo.lviv.ua/amp/
https://poker-royal777.com/poker/pokermatch/
https://pokerbroz.ru/room/pokermatch
https://poker.by/poker-match/
https://pokeronlinerus.com/rooms/pokermatch/
https://pokermatch.today/
https://betting.team/ru/wiki/pokermatch-wiki
https://www.uapoker.info/otzyvy/pokermatch
https://ua1.com.ua/pokerrooms/pokermatch
https://ru.worldpokerdeals.com/rakeback-deals/pokermatch-review

**Comment by lolka4toli** [comment]
ukrfootball.com.ua and telemetr.me are ok, other ones blocked now.
