### ISSUE TITLE
Обман!

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#66080]
Здравствуйте!
Прошу заблокировать!

https://zhitomir.life/17973-promokod-melbet-bonus-na-depozit-ot-bk-melbet.html
https://betslive.ru/obzor-bk/melbet/
https://favoritsport.com.ua/melbet/
https://legalbet.ru/shkola-bettinga/registratciya-v-bk-melbet/

**Comment by lolka4toli** [comment]
betslive.ru and zhitomir.life are ok, other ones blocked for now.
