### ISSUE TITLE
[nsfw] [overlay] homemoviestube.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6608]
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Google Chrome 60.0.3112.113
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
AdGuard DNS:                        | N/A
Stealth mode options (Windows only) | Enabled (only self deleting cookies is disabled)
Helpdesk ID (if exists):            | N/A
**Site with ad sample 1**|  http://www.homemoviestube.com/videos/385878/japanese-amazing-big-tits-fuck-and-facial.html

### Screenshoot:
![image-20170904-005](https://user-images.githubusercontent.com/9846948/30035517-49f520fc-91ab-11e7-9634-5f726834a87d.png)

**Comment by AdamWr** [comment]
Fixed.
