### ISSUE TITLE
Вредоносные сайты!!!

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#66082]
Здравствуйте!
Прошу принять меры!

https://www.pokeroff.ru/pokermatch
https://pekarstas.com/rooms/pokermatch/
https://poker-play.com.ua/room/pokermatch/
https://poker.24tv.ua/ru/poker_match_tag7316/
https://poker.ua/pokermatch/
https://ru.mirpokera.com/pokermatch
https://ua-poker.com.ua/
https://m.melbet.com/

**Comment by lolka4toli** [comment]
Blacklisted.
