### ISSUE TITLE
[nsfw][ad leftover box] www.freepornhq.xxx

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6609]
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Google Chrome 60.0.3112.113
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
AdGuard DNS:                        | N/A
Stealth mode options (Windows only) | Enabled (only self deleting cookies is disabled)
Helpdesk ID (if exists):            | N/A
**Site with ad sample 1**|  https://www.freepornhq.xxx/

### Screenshoot:
![image-20170904-006](https://user-images.githubusercontent.com/9846948/30035579-fc01a2ac-91ab-11e7-9fff-ef44d710630c.png)

**Comment by AdamWr** [comment]
Fixed.
