### ISSUE TITLE
[nsfw] [popups, ads boxes, redirect click] www.pornfapr.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6610]
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Google Chrome 60.0.3112.113
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
AdGuard DNS:                        | N/A
Stealth mode options (Windows only) | Enabled (only self deleting cookies is disabled)
Helpdesk ID (if exists):            | N/A
**Site with ad sample 1**|  http://www.pornfapr.com/
**Site with ad sample 2**|  http://www.pornfapr.com/videos/12013/allison-parker-sucking-cock/

ISSUE: 
- Boxes with ads on right side and at end of sites.
- Opening new site after pause video.
- Popups, banners.

**Comment by AdamWr** [comment]
Fixed.
