### ISSUE TITLE
Swagbucks.com detected ad blocker banner

### ISSUE THREAD

**Issue by miguedevel** [AdguardTeam/AdguardFilters#6611]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Swagbucks.com shows a banner on top saying an ad blocker has been detected.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/26647325/30038287-be1fc1d2-9190-11e7-8b6c-25cd9d0683ef.png)

</details><br/>

* **Expected behaviour**: 

Banner shouldn't show.

<details><summary>Screenshot:</summary>

</details><br/>

***Steps to reproduce the problem***:
1. Visit http://www.Swagbucks.com while logged in with Adguard enabled.

***System configuration***

**Filters:**

English, Spyware, Annoyances, Experimental 

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 16281
Browser:                            | Edge 41.16281.1000.0
AdGuard version:                    | 6.2 beta
Filters enabled:                    | English, Spyware, Annoyances, Experimental 
AdGuard DNS:                        | None
Stealth mode options (Windows only) | None
Helpdesk ID (if exists):            | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by miguedevel** [comment]
`swagbucks.com###disabledSB` seems to fix it.

**Comment by Alex-302** [comment]
I can't register on this site.

**Comment by XX-J** [comment]
АнтиАдблок:
`||sbx-cdn.com/*/no-SB-banner.pmin.js`

> I can't register on this site.

Потому, что сайт не пускает к себе из России и неприемлет русских почтовиков.

**Comment by Alex-302** [comment]
Ок, добавил.
