### ISSUE TITLE
sergeistrelec.ru - Ads - Widnows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6612]
***Description***:
* **Current behaviour**: 

http://sergeistrelec.ru/winpe_10_8/119-winpe-10-8-sergei-strelec-x86-x64-native-x86-20170830-russkaya-versiya.html

ads on the website on Windows
reproduced on our side (Mac OS)
<details><summary>Screenshot:</summary>

![screen shot 2017-09-05 at 12 51 46 am](https://user-images.githubusercontent.com/28784344/30039047-692252be-91d4-11e7-949e-514af3c71e28.png)

</details><br/>

***System configuration***

**Filters:**

Information                         | Value
---                                 | ---
Operating system:                   | Mac os
Browser:                            | chrome
AdGuard version:                    | 1.4.1.
Filters enabled:                    | 0,1,2,3,4,14
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1449704

**Comment by Alex-302** [comment]
It was fixed yesterday.
