### ISSUE TITLE
https://www.hotcleaner.com/cookies.html

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6613]
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Google Chrome 60.0.3112.113
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
AdGuard DNS:                        | N/A
Stealth mode options (Windows only) | Enabled (only self deleting cookies is disabled)
Helpdesk ID (if exists):            | N/A
**Site with ad sample 1**|  https://www.hotcleaner.com/cookies.html

ISSUE: 
- Site is blank

![image-20170905-001](https://user-images.githubusercontent.com/9846948/30049123-a031df32-9219-11e7-8590-7c316141ef8b.png)

Compare without adguard:
![image-20170905-002](https://user-images.githubusercontent.com/9846948/30049219-0f4bf060-921a-11e7-8bd9-94b5b8fdc282.png)

**Comment by Alex-302** [comment]
Reported to `I Don't care about cookies`
