### ISSUE TITLE
Increase the functionality that redirects the current link

### ISSUE THREAD

**Issue by wellser** [AdguardTeam/AdguardFilters#6614]
i have used some soft like adguard or adblock , they ara named "adbyby" or "adm".
what is more advanced than adguard is they can redirects the current link.
like proxy's redirect, for example ：
when i use adbyby , i can use the rule "C$f@s@A@B@",
it means that when i visite the url which match C , it can replace the A in the url with B.
So , when soft visit the site C , it actually redirect to url which i want .

please develop adguard's redirect rules. That would be very useful·

**Comment by Alex-302** [comment]
duplicate.
