### ISSUE TITLE
adguard blocks on localhost

### ISSUE THREAD

**Issue by mkborregaard** [AdguardTeam/AdguardFilters#66175]
Which means I can't run apps that use the browser for display (firefox 0.81.2 in this case).
Using AdGuard 3.5.12. In this case it's this app that won't run: https://github.com/fonsp/Pluto.jl

**Comment by Alex-302** [comment]
@mkborregaard Hi. Could you please make screenshot?
Is an app broken if `IP` used instead of `localhost`?

**Comment by mkborregaard** [comment]
The sreen is just completely blank:
![Skærmbillede 2020-10-23 kl  13 30 47](https://user-images.githubusercontent.com/8429802/96998603-01f13600-1534-11eb-9fc0-644dae0959af.png)
(the url shown is http://localhost:1234/edit?id=17b59230-1523-11eb-05f0-2b661897f01f , the id is a unique code generated for the document). Using IP instead just leads to "page not found".

**Comment by krystian3w** [comment]
so maybe need add

```
@@||localhost$document
```

**Comment by Alex-302** [comment]
@mkborregaard Do you see something blocked in the filtering log?
