### ISSUE TITLE
Overclockers.ru - Ad

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#6617]
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/17948007/30069550-ad2d780e-9269-11e7-9f5a-48db42b79549.jpg)
</details><br/>

Баннер - https://www.overclockers.ru/lab/71088_5/obzor-i-testirovanie-materinskoj-platy-asrock-z170-extreme6.html

Лечение:
`||overclockers.ru/images/MSI`

Сначала хотел скрыть следующим правилом:
`overclockers.ru###contentplace > .over-hiddenlink-html`
Но баннер всё равно появлялся. Тогда я подумал на какой-нибудь java-скрипт, восстанавливающий этот баннер, и нашёл таковой:
`||overclockers.ru/_js/app.js`
При блокировке скрипта и применении вышенаписанного правила скрытия - баннер исчезал, но некоторые ссылки переставали вести себя как ссылки, т.е. при их нажатии ничего не происходило.
Оказывается эти ссылки, как и сам баннер, помещены в объекты "span", а этот скрипт преобразовывает эти объекты "span" с классом "over-hiddenlink-html" в "a href", а ссылку берёт из данных объекта "span" с тегом "data-link".
Вот-бы написать скрипт, или взять его часть из `overclockers.ru/_js/app.js`, который-бы преобразовывал эти объекты в нужный вид, и поместить его во что-то типа `overclockers.ru#%#СКРИПТ`. Тогда-бы вышестоящее правило скрытия можно было бы использовать, т.к. оно более УНИВЕРСАЛЬНО, ну и, возможно, в будущем пригодится, относительно этого, неровно дышащего к блокировкам, сайта.
___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard legacy v2.7.1
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
https://www.overclockers.ru/lab/71088_5/obzor-i-testirovanie-materinskoj-platy-asrock-z170-extreme6.html
```
Явление с нескрываемым баннером не повторяется.

**Comment by Alex-302** [comment]
Попробуй так:
```
overclockers.ru#$#a[href^="http://microstar.ru/event/"] > img { position: absolute!important; left: -3000px!important; }
```

**Comment by XX-J** [comment]
> Явление с нескрываемым баннером не повторяется.

Он не скрывается, если использовать следующее правило (которое должно его скрывать):
`overclockers.ru###contentplace > .over-hiddenlink-html`

> Попробуй так:

Теперь уже всё нормально, с Вашим первым правилом, добавленным в "Русский фильтр". Спасибо.
