### ISSUE TITLE
majesy.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#66184]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Cookie banner
`https://majesy.com` `https://magesy.eu` `https://magesy.blog` `https://magesy.pw`
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="946" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/96928398-cbc2a080-14b8-11eb-8750-86ac3c140a6d.PNG">

</details><br/>

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.12
Filters enabled:                       | default + Adguard Germany + Adguard Tracking Protetion + Adguard Annoyances
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Hi. Cannot reproduce with EU VPNs even without AdGuard.
Please show HTML code of element(in developer tools)

**Comment by JobcenterTycoon** [comment]
ok they removed the banner very quickly.

**Comment by JobcenterTycoon** [comment]
Anti Adblock back on
`https://magesy.blog`
`https://majesy.org`
`https://magesy.eu`
`https://magesy.fr`
`https://magesy.pw`
`https://majesy.com`
`https://magesy.eu`
