### ISSUE TITLE
[Extension] https://my-hit.fm/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6619]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: The [link](https://my-hit.fm/%D0%BF%D1%80%D0%B5%D0%BC%D0%B8%D1%8F-ru-tv). This is being blocked with the app, not with extensions.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30101844-78116f6c-92f6-11e7-9146-2196be18ccfe.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30101897-9dd841e4-92f6-11e7-9e43-4bdf046db23c.png)

</details><br/>

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/15856304/30101911-a8d0b9f0-92f6-11e7-9638-149a8f9ea2ae.png)

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | Extension, the current version
Helpdesk ID (if exists):            | 741799

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.

**Comment by evgeniy-ADG** [comment]
У меня и у пользователя проблема осталась.

**Comment by Alex-302** [comment]
Переделал.
