### ISSUE TITLE
https://m.avito.ru/ - content won't load

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6620]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: The user reports that he no longer can use the site as the messages won't load.

>Проблема с мобильным сайтом Авито , не прогружаются сообщения, написанные в Личный кабинет, скриншот прилогаю, время 10 - 55

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30108794-6ec0884c-930c-11e7-83a9-daf7ba19d67a.png)

</details>

***Steps to reproduce the problem***:

1. Login to avito mobile version
2. You need to have some communication history with other users, I assume. It won't load.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Android
Browser:                            | Samsung Internet
AdGuard version:                    | 2.9.136
Filters enabled:                    | 2, 3, 4, 14, 1, 11
AdGuard mode (Android only):        | VPN
Filtering quality (Android only):   | High-quality 
HTTPS filtering (Android only):     | On Default
AdGuard DNS:                        | true
Helpdesk ID (if exists):            | 1150428

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
Please check the log. It might be due to other issues the customer has and custom rules he's been provided with.

**Comment by Alex-302** [comment]
У меня не повторилось. Передай на проверку:
```
@@||googletagmanager.com/gtm.js^$domain=m.avito.ru
@@||static.criteo.net/js/ld/ld.js$domain=m.avito.ru
```
Если поможет - попроси проверить с каждым отдельно.

**Comment by evgeniy-ADG** [comment]
> Нет не помогло, бесконечно крутится загрузка сообщений , если отключаю адгуард, то все грузится сразу. Забыл сказать, проблема воспроизводится в браузере от Самсунг (стандартный браузер , другие не использую)

**Comment by Alex-302** [comment]
А какой фильтр ломает? Пусть выключит все, проверит, а потом по одному включает.

**Comment by evgeniy-ADG** [comment]
> Я отключать все фильтры , и проблема
> оставалась ..так что проблема не в
> фильтрах 

Там еще один лог прислали зачем-то.

**Comment by Alex-302** [comment]
А у тебя не повторяется? Продублируй наверное в раздел Android, может в некоторых ситуациях ломается фильтрацией HTTPS.
