### ISSUE TITLE
https://cashbox.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6621]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: The banner in the left-hand bottom, can't hide with the rules assistant creates to block it. The link: https://cashbox.ru/customize/personaldata

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30109846-828025dc-9310-11e7-9877-a38588cb97a4.png)

</details><br/>

***Steps to reproduce the problem***:

1. Go to the site
2. Login or create a profile with a social network
3. See the banner

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

Russian, English, Annoyances

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | The latest release
AdGuard DNS:                        | None 
Stealth mode options (Windows only) | default options
Helpdesk ID (if exists):            | 1208293

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed

**Comment by aiv3006** [comment]
Фильтры обновил кеш почистил банер висит как висел ! в 3-х браузерах пробовал

**Comment by Alex-302** [comment]
Нужно хотя бы час выждать до обновления.

**Comment by aiv3006** [comment]
Хм.. Не знал Алекс . А что правило которое создали через час в базе фильтров  очутится ?

**Comment by Alex-302** [comment]
да, через час после добавления оно будет доступно для загрузки.
