### ISSUE TITLE
https://gohub.pw/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6622]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behavior**: NSFW, the link: https://gohub.pw/

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30111670-3eddc616-9317-11e7-9a6f-41b5e03ac051.png)

</details><br/>

***Steps to reproduce the problem***:

1. Go to the site
2. Wait
3. See the anti-adblocker

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Wind
Browser:                            | Chrome
AdGuard version:                    | release
Filters enabled:                    | English, Russian, Social media, Spyware, Annoyances
AdGuard DNS:                        | None
Stealth mode options (Windows only) | off
Helpdesk ID (if exists):            | 1573765

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
