### ISSUE TITLE
new snapchat tracker

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#66236]
app-analytics-v2.snapchat.com

**Comment by jordanelliott23** [comment]
@Alex-302 not 100 percent sure but think that this might be breaking stuff. i got failed snaps and posting to story. might just be me but idk

**Comment by jordanelliott23** [comment]
@Alex-302 srry i think is a bad filter, i added it to my allowlist and things are working again. my bad

**Comment by Alex-302** [comment]
Removed.
