### ISSUE TITLE
http://lostfilm-online.ru - Missed Ad - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6625]
***Description***:
* **Current behaviour**: 

[//]: # Missed Ad on the website when playing video http://lostfilm-online.ru/foreign-series/detective/183-tvin-piks-smotret-onlayn.html

[//]: # 
![image1](https://user-images.githubusercontent.com/31481372/30152286-503c6152-93bb-11e7-96f5-6d36cefb5684.png)

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Browser:                            | Safari
AdGuard version:                    | 1.3.1.82
Simplified filters:                 | Yes
Filters enabled:                    | 0,2,3,4,14,1,11,12

Helpdesk ID (if exists):            | 1624450

**Comment by Alex-302** [comment]
It seems we can't block this banner on iOS. Also it is impossible to bypass the timer on iOS.
