### ISSUE TITLE
https://readovka.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6626]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: Can't read articles, tapping on an article does nothing. The link: https://readovka.ru/

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30154308-6476d456-936e-11e7-8b7a-ab047277368e.png)

</details><br/>

***System configuration***

**Filters:**

English, Russian, Annoyances, Spyware, Social media

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Android 6
Browser:                            | Chrome
AdGuard version:                    | 2.9
Filters enabled:                    | English, Russian, Annoyances, Spyware, Social media
AdGuard mode (Android only):        | VPN
Filtering quality (Android only):   | High-quality
HTTPS filtering (Android only):     | On (Default)
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1624606

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
