### ISSUE TITLE
AdGuard is blocking Spotify redirects in Instagram

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#66272]
Ошибка сайта при запуске на свайп рекламного видео с музыкой с редиректом на Spotify (редиректа не происходит). Если выключить adguard, то всё работает. Пользовательских фильтров нет. Все фильтры обновлены. Adguard в режиме http с рут правами.

Прикрепил видео - первые 8 секунд adguard отключен, редирект работает, а далее не работает при включении защиты.

<details> <summary> скриншот </summary>

![image](https://user-images.githubusercontent.com/15856304/97078383-99b65900-15f4-11eb-9a42-904b1a3e5e6c.png)

</details>

Видео и логи веб-запросов в тикете **1151790**.

**Comment by Alex-302** [comment]
@Eugene-Savenko передай на проверку
`@@||app.adjust.com^$app=com.instagram.android`
