### ISSUE TITLE
[Leftovers] computerworld.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6627]
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Google Chrome (Stable)
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
Stealth mode options (Windows only) | Enabled (only self deleting cookies is disabled)
**Site sample**| https://www.computerworld.com/article/3199373/windows-pcs/windows-by-the-numbers-windows-7-falls-further-behind-xps-march-to-retirement-pace.html

### Issue:

Leftovers `You might like` and `Shop tech products at amazon` 

### Screenshoot:
![image-20170907-001](https://user-images.githubusercontent.com/9846948/30156120-13270098-93bf-11e7-8c20-5dbc844ab7cb.png)

### Fix
```
computerworld.com###content-recommender
computerworld.com##.amzn-custom-header
```

**Comment by Alex-302** [comment]
Fixed.
