### ISSUE TITLE
reddit.com - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6629]
https://www.reddit.com

<details><summary>Screenshot:</summary>

<img width="602" alt="screen shot 2017-09-07 at 3 54 29 pm" src="https://user-images.githubusercontent.com/27292111/30164354-e6df8930-93e4-11e7-9087-1eb4cd69f174.png">

</details><br/>

***System configuration***

Application version: 1.3.1.107
Device: iPad
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.29.88 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.30 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.83 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.85 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.9.32 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
ID=223 Name="Fanboy's Swedish" Version=1.0.0.6 Enabled=YES

Helpdesk ID:    1284514

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. The site looks differently

<details>

![image](https://user-images.githubusercontent.com/8361299/30165801-05d24e0e-93ea-11e7-888c-f1faa73e89ac.png)
</details>

**Comment by veronikasav** [comment]
Is there anything we can do?

**Comment by Alex-302** [comment]
A direct link. Maybe it is some sub-reddit.

**Comment by veronikasav** [comment]
https://www.reddit.com/r/svenskpolitik/comments/6y6c2l/skjutningarna_%C3%B6kar_dramatiskt_i_sverige/

**Comment by AdamWr** [comment]
This website from screenshot looks like https://www.reddit.com/r/sweden/ but I can't reproduce this too.
I see ads only when I disable AdGuard.

**Comment by Alex-302** [comment]
Also not reproduced on iPad on this page.
@veronikasav please try to switch full/optimized filters.

**Comment by magnuswd** [comment]
I'm having this problem - try in "request desktop site" mode!

**Comment by AdamWr** [comment]
I tried it with desktop mode and I can't reproduce.

<details><summary>Screenshot</summary>

![zdjecie 07 09 2017 15 48 26](https://user-images.githubusercontent.com/29142494/30170977-e26af7f2-93f0-11e7-88b8-e0cfd30fd3d1.png)

</details>

**Comment by magnuswd** [comment]
Still seeing it... 

Restarted iPad, force updated filters... looks like a google ad

![img_2846](https://user-images.githubusercontent.com/31737888/30172813-1ed6b910-93f6-11e7-804d-cbe769774b26.PNG)
![img_2844](https://user-images.githubusercontent.com/31737888/30172814-1ef6220a-93f6-11e7-8824-0448244d5cc4.PNG)

**Comment by Alex-302** [comment]
@magnuswd 
> looks like a google ad

Google ads must be blocked. Try to lease English filter only.

**Comment by veronikasav** [comment]
Asked to leave English filter only.

**Comment by evgeniy-ADG** [comment]
> I just tested this - unfortunately the ads still appear with only english
> filter enabled
