### ISSUE TITLE
[adblock detect] iitv.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6630]
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Google Chrome (Stable)
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
Stealth mode options (Windows only) | Enabled (only self deleting cookies is disabled)
**Site sample**| http://iiv.pl/ZEffW

@AdamWr 
Reproduce 

Go to http://iitv.pl/w-garniturach/s07e09-shame 
Click on any link (openload LOGO on left for example) 
![image-20170907-006](https://user-images.githubusercontent.com/9846948/30165745-6a320992-93e1-11e7-9770-3b3545b8c9ff.png) and this will open `http://iiv.pl/ZEffW` link with:
![image-20170907-007](https://user-images.githubusercontent.com/9846948/30165788-922dc3a0-93e1-11e7-8612-7f7bda51813d.png)

Text (from polish language - shortly) `Ads are not so bad. Please unblock ads on this site and reload.`

**Comment by AdamWr** [comment]
Anty adblock naprawiony.
Jeśli chodzi o to pięciosekundowe odliczanie, to możesz dodać sobie tę regułę:
`iiv.pl#%#AG_onLoad(function() { setTimeout(function() { var el = document.getElementById("counting"); if(el) { el.setAttribute("data-time", "0"); } }, 300); }); AG_onLoad(function() { setTimeout(function() { var el1 = document.getElementById("link"); if(el1) { el1.click(); } }, 2000); });`
Powinno być trochę szybciej :)
