### ISSUE TITLE
spiegel.de - Incorrect blocking

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6632]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: won't show elements with Adg. 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/30168775-0fc2a40a-93f3-11e7-9604-f1c9e3775bd1.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/30168834-38355ae0-93f3-11e7-898b-d97fb02811be.png)

</details><br/>

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:** 2, 3, 4, 6, 12, 14, 107, 207

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
AdGuard version:                    | 1.3.1.82
Helpdesk ID (if exists):            | 1623813

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce with these filters. Try without 107, 207

**Comment by vitbortnik** [comment]
The first screenshot shows what I get with EasyList Germany and Adblock Warning Removal List disabled.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/30183812-6df047fe-9424-11e7-9079-f97f96dcb21b.png)

</details>
Then I tried something different, disabling the 'Deutscher Filter'. This is what I get:

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/30183820-76802998-9424-11e7-9805-8048e89d810a.png)

</summary>

**Comment by Alex-302** [comment]
Is it main page?

**Comment by vitbortnik** [comment]
@Alex-302 

My bad, didn't include the link
http://m.spiegel.de/wirtschaft/service/a-1166198.html

Also, I've updated my previous comment with a proper screenshot. 
Take a look please.

**Comment by Alex-302** [comment]
Fixed.
