### ISSUE TITLE
Как убрать уведомление на Wordreference.com

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardFilters#66337]
Проблема с уведомлением на сайте wordreference.com. Скриншот прикрепляю
[https://thumbsnap.com/i/eKGuPctu.jpg](https://thumbsnap.com/i/eKGuPctu.jpg)

Operating system: Windows 10 Home
Browser: Chrome Version 86.0.4240.111 (Official Build) (64-bit)
AdGuard version for Chrome: Version 3.5.12
Filters enabled: AdGuard Base filter, AdGuard Tracking Protection filter, EasyPrivacy, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter
Stealth mode options (Windows only) Enabled

**Comment by Alex-302** [comment]
Не повторяется. Какой фильтр блокирует `fundingchoicesmessages.google.com`?

**Comment by jbionic2016** [comment]
> Не повторяется. Какой фильтр блокирует `fundingchoicesmessages.google.com`?

Как узнать какой блокирует, я не знаю.

[https://thumbsnap.com/i/bHoWyoG1.gif](https://thumbsnap.com/i/bHoWyoG1.gif)

**Comment by Alex-302** [comment]
В журнале можно посмотреть. Но это предположение.
Ещё можно проверить без личных и сторонних фильтров.

**Comment by jbionic2016** [comment]
> В журнале можно посмотреть. Но это предположение.
> Ещё можно проверить без личных и сторонних фильтров.

Filter log прикрепляю
https://drive.google.com/file/d/1TLkV3-XxjdOm1LTpNR1VbHhN_SS9ysZ2/view?usp=sharing

**Comment by Alex-302** [comment]
В логе заблокированного не вижу.


> Ещё можно проверить без личных и сторонних фильтров.

это не проверяли?

**Comment by jbionic2016** [comment]
> В логе заблокированного не вижу.
> 
> > Ещё можно проверить без личных и сторонних фильтров.
> 
> это не проверяли?

Проверял на наличие среди заблокированного fundingchoicesmessages - не обнаружилось, ваша гипотеза не подтвердилась..

**Comment by Alex-302** [comment]
Без Адгарда повторяется?
Какой статус у запроса `fundingchoicesmessages` в инструментах разработчика?

**Comment by jbionic2016** [comment]
> `fundingchoicesmessages`

Обалдеть. С выключенным Adguard не показывает:
[https://thumbsnap.com/i/VtWhmGDp.gif](https://thumbsnap.com/i/VtWhmGDp.gif)

А с включенным генерирует
[https://thumbsnap.com/i/MAaXqAJP.jpg](https://thumbsnap.com/i/MAaXqAJP.jpg)

**Comment by Alex-302** [comment]
Ну блокируешь же чем-то. Смотри в журнал. Может какое-то расширение блокирует.

**Comment by jbionic2016** [comment]
> Ну блокируешь же чем-то. Смотри в журнал. Может какое-то расширение блокирует.

Мы ж вроде определили уже каким расширением блокируется, или нет?

**Comment by Alex-302** [comment]
Посмотри в журнал.

**Comment by jbionic2016** [comment]
> Посмотри в журнал.

Только тыкать не надо, я с Вами на брудершафт не пил и, берусь поспорить, лет на 20 старше Вас. Сообщение исчезло так же неожиданно как и появилось при включенном Adguard. Благодарю за решение.
