### ISSUE TITLE
sdamgia.ru - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6634]
https://mathb-ege.sdamgia.ru/ and other branches of sdamgia.ru

<details><summary>Screenshot:</summary>

<img width="1715" alt="screen shot 2017-09-07 at 6 12 18 pm" src="https://user-images.githubusercontent.com/27292111/30170604-45c2bc84-93f8-11e7-9a80-a364af2e55d2.png">

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Mac OS
Browser:                            | Chrome
AdGuard version:                    | 1.4.1
Filters enabled:                    | 1 2 3 4 14
Helpdesk ID:           | 1342881

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. Is HTTPS filtering works on this site?

**Comment by evgeniy-ADG** [comment]
Там периодами при обновлении страницы выскакивает https://an.yandex.ru/mapuid/reshuege/48b6243c51838f7e?jsredir=1&location=https%3A%2F%2Fgeo-ege.sdamgia.ru%2Ftest%3Fid%3D323504&sign=1759613885

![image](https://user-images.githubusercontent.com/15856304/30199375-261b3b44-947b-11e7-991c-8d6666dcb593.png)

У меня рекламы нет, но я не могу нормально тестировать из-за этого ad.yandex.ru. Уточню про HTTPS и остальное, директ сложноповторяемый.

**Comment by evgeniy-ADG** [comment]
Там куча расширений, попробуем в других браузерах.

**Comment by Alex-302** [comment]
У меня сейчас вообще он не открывается.

**Comment by veronikasav** [comment]
@Alex-302 Проверила еще в firefox. Все работает, рекламы нет. Что попросить у пользователя?

**Comment by Alex-302** [comment]
Это может быть антиадблк яндекса. На иос его не одолеть, но после обновления вкладки ссылки должны открываться.

**Comment by Alex-302** [comment]
Сам сайт у меня не открывается.
