### ISSUE TITLE
http://getvera.com/ - Incorrect blocking - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6635]
***Description***:
* **Current behaviour**: 

Website: http://getvera.com/

Website with AG running:

1. Hover over “Products” menu and nothing happens (should be mouse-over menu)
2. There is a carousel banner removed directly underneath the menu bar (screenshot #1)

The Same website without AG running(screenshot #2)
Reproduced on our side (Mac OS)

<details><summary>Screenshot with Adguard enabled :</summary>

![image003 1](https://user-images.githubusercontent.com/28784344/30170788-b9aa8e92-93f8-11e7-946d-d7bad4f8b472.jpg)

</details><br/>

<details><summary>Screenshot without Adguard :</summary>

![image004](https://user-images.githubusercontent.com/28784344/30170802-c20ddc42-93f8-11e7-98af-5b1addb75a71.jpg)

</details><br/>

***System configuration***

**Filters:**

Information                         | Value
---                                 | ---
Operating system:                   | Mac OS
Browser:                            | chrome
AdGuard version:                    | 1.4.1.
Filters enabled:                    | 1,2,3,4,10,14
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 983289

**Comment by Alex-302** [comment]
Fixed,
