### ISSUE TITLE
TheDailyBeast.com - Login broken (AdGuard Annoyances filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#66358]
### Affected site:
`https://www.thedailybeast.com/`

### Issue:
Login is blocked.

### How to reproduce:
Click on the **LOG IN** button (in the top right corner).
Result: nothing happens!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **AdGuard Annoyances filter**

### Problem rule:
`thedailybeast.com#$#.tp-modal { display: none!important; }`

### Possible fix:
Delete the problem rule

### Temporary fix:
`thedailybeast.com#@$#.tp-modal { display: none!important; }`

### Other problem filters:
* **Fanboy's Enhanced Tracking List** https://github.com/ryanbr/fanboy-adblock/issues/1423/
`||tinypass.com^$third-party`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.14.2 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.26b9 (XUL)

**Comment by AdamWr** [comment]
Thank you.
