### ISSUE TITLE
newsbreak app trackers

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#66370]
ampcid.google.com (used for analytics: https://github.com/google/amp-client-id-library)
adservice.google.com (appeared in log when i clicked on on of the articles)

**Comment by Alex-302** [comment]
Need real examples where ampcid.google.com is used.

**Comment by jordanelliott23** [comment]
try clicking this: https://www.newsbreakapp.com/n/0XQiG5X2?pd=07GVMA5s&lang=en_US&s=i0


then when the app opens click the blue hyperlink part. you should see ampcid appear in your log. @Alex-302

**Comment by jordanelliott23** [comment]
were you able to reproduce adservice domain? @Alex-302

**Comment by jordanelliott23** [comment]
i was able to reproduce adservice domain by following these steps.

click this https://www.newsbreakapp.com/n/0XQVuPLE?pd=07GVMA5s&lang=en_US&s=i0


then click the blue hyperlink above the thumbs up button

**Comment by jordanelliott23** [comment]
also another tracker. click this:

https://www.newsbreakapp.com/n/0XQhZfzl?pd=07GVMA5s&lang=en_US&s=i0


then click blue hyperlink above thumbs up button and pixel.patch.com will appear in your log. @Alex-302

**Comment by Alex-302** [comment]
> try clicking this: https://www.newsbreakapp.com/n/0XQiG5X2?pd=07GVMA5s&lang=en_US&s=i0

nothing.
Added `||newsbreak.com/_api/stat/`

**Comment by Alex-302** [comment]
You can try to record the HAR file:
https://toolbox.googleapps.com/apps/har_analyzer/

**Comment by jordanelliott23** [comment]
> You can try to record the HAR file:
> https://toolbox.googleapps.com/apps/har_analyzer/

thats odd that you arent seeing the trackers. how do i do a har file?

**Comment by jordanelliott23** [comment]
you're doing this through iphone correct? not a computer? @Alex-302

**Comment by jordanelliott23** [comment]
i took a screen recording for you; both trackers actually appeared on same article. https://ufile.io/dgaajk56

**Comment by jordanelliott23** [comment]
> i took a screen recording for you; both trackers actually appeared on same article. https://ufile.io/dgaajk56

@Alex-302

**Comment by Alex-302** [comment]
adservice.google.com should not be blocked.
Not sure about ampcid.google.com

**Comment by cmcquade288** [comment]
https://www.newsbreakapp.com/n/0YGErFv?shre_id=eyJ1c2VyaWQiOjEyMDUyNjk3NiwiZG9jX2lkIjoiMFlOR0VyRnYiLCJ0aW1lc3RhbXAiOjE2MTEyNTE1MDkwNDh9&s=a7&pd=089iZUf9&hl=en_UShttps://raw.githubusercontent.com/vmware/stig-compliance/master/LICENSE?token=AKkZN6yWYjDCjBMgkWVhxgNv2YFWNbfiks5XMRA2wA%3D%3Dmatthewmcquade9@gmail.com why is this on my Facebook
