### ISSUE TITLE
rarbg.to unblocked ad

### ISSUE THREAD

**Issue by zero77** [AdguardTeam/AdguardFilters#6638]
Example URL: rarbg.to/torrent/tnvz4r2 and any other torrent enterys.

Annoying unblocked  vpn advert at the top of every torrent entry page.

It appears on the rarbg.to and on all proxy domains rarbg-to.proxydude.xyz and rarbg.unblocked.lol.

Possible rule suggestion “rarbg.to##tr:nth-of-type(2) > td > div > .lista > tbody > tr:nth-of-type(2)” although, this only works for the main domain not the proxies.

Before Rule:
![](https://user-images.githubusercontent.com/16563034/30170307-aeb35c56-93e6-11e7-8004-d59043f9c1a4.JPG)

After Rule:
![](https://user-images.githubusercontent.com/16563034/30170343-c4032848-93e6-11e7-916c-2a07d882611f.JPG)

Information                         | Value
---                                 | ---
Operating system:                   |Same result for all / Desktop - Mobile
Browser:                            | Same result for all 
AdGuard version:                    | Newest
Filters enabled:                    |  All
AdGuard mode (Android only):        | VPN / auto
Filtering quality (Android only):   | High-quality
HTTPS filtering (Android only):     | On
AdGuard DNS:                        | Default

**Comment by Alex-302** [comment]
Please use provided template.

**Comment by Alex-302** [comment]
It is hidden by
```
rarbg.to,rarbg.unblocked.kim,rarbgmirror.com,rarbgproxy.com##tr > td + td[style*="height:"]
```

**Comment by zero77** [comment]
Thanks, but it only partially blocks it, just the text not the hole element.
Also it doesn’t work under the proxy domain just the main one.

**Comment by Alex-302** [comment]
Added
```
rarbg.to##td[align="justify"] > div > table[width="100%"][class="lista"] > tbody > tr[-ext-has='tr > td + td[style*="height:"]']
```

**Comment by zero77** [comment]
Yes thanks, that works well on their main domain but not proxies although, that may not be fixable.

**Comment by Alex-302** [comment]
@zero77 
>but not proxies although,

what do you mean?

**Comment by zero77** [comment]
For example, rarbg-to.proxydude.xyz and rarbg.unblocked.lol and others some from proxybunker.online and torrents.me/proxy and others around the internet.

These allow access to rarbg.to and other torrent websites, because some ISPs block them.

**Comment by Alex-302** [comment]
Please provide more domains.
And check this rule(without domain restriction)
```
##td[align="justify"] > div > table[width="100%"][class="lista"] > tbody > tr[-ext-has='tr > td + td[style*="height:"]']
```

**Comment by zero77** [comment]
Here’s some but they are dynamic as they change when they get blocked, this is the same with most big torrent sites.:
rarbg.pbproxy2.co
rarbg.unblocked.lol
rarbg-to.pbproxy.red
rarbg-to.proxydude.xyz

Also its not working so far but I am trying different things.

**Comment by Alex-302** [comment]
Thanks, fixed.

**Comment by zero77** [comment]
thanks

**Comment by adranger** [comment]
@Alex-302 Same issue with their new domain: `https://rarbgproxied.org/torrent/yz5oik9`

**Comment by Alex-302** [comment]
ok
