### ISSUE TITLE
deepdotweb.com Unblocked ad

### ISSUE THREAD

**Issue by zero77** [AdguardTeam/AdguardFilters#6639]
This rule suggestion blocks annoying adds on the right side of the page (both top and bottom).
Example URL:
deepdotweb.com

deepdotweb.com###text-5
deepdotweb.com##a[href="http://energycontrol-international.org/"]
deepdotweb.com###google-widget-2

**Comment by Alex-302** [comment]
Fixed

**Comment by zero77** [comment]
thanks
