### ISSUE TITLE
laravel-news.com - Ad leftovers

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6642]
https://laravel-news.com/php-7-2-deprecations

<details><summary>Screenshot:</summary>

Ad leftover:
<img width="451" alt="screen shot 2017-09-07 at 10 21 59 pm" src="https://user-images.githubusercontent.com/27292111/30181154-03d1c4e6-941b-11e7-8bce-ce36f03f2f96.png">

Social share leftover:
<img width="451" alt="screen shot 2017-09-07 at 10 23 27 pm" src="https://user-images.githubusercontent.com/27292111/30181233-42a5d586-941b-11e7-89b2-63902cb012ea.png">

Ad leftover and newsletter signup:
<img width="453" alt="screen shot 2017-09-07 at 10 23 39 pm" src="https://user-images.githubusercontent.com/27292111/30181239-44a6766a-941b-11e7-9a8c-b2741359b97f.png">

Links to social media sites are missing (note: these are no share buttons!):
<img width="446" alt="screen shot 2017-09-07 at 10 23 52 pm" src="https://user-images.githubusercontent.com/27292111/30181241-46780026-941b-11e7-8fa3-e2c758d191f9.png">

</details><br/>

***System configuration***

Application version: 1.3.2.108
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.29.91 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.30 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.85 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.87 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.51 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
Helpdesk ID:          1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
