### ISSUE TITLE
Placeholder removals that have been rejected by EasyList (N: uBlock Origin) (T: Ads)

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#66446]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

As part of my probably-several-months-long plan to move entries from *Nano Placeholder Buster* over to major international lists, entries that have been rejected by EasyList are currently something I plan to submit to AdGuard Filter. In this first batch:

• https://github.com/easylist/easylist/issues/6313
• https://github.com/easylist/easylist/issues/6311
• https://github.com/easylist/easylist/issues/6307

* **Expected behaviour**: 

N/A

***Steps to reproduce the problem***:

Hopefully explained within the threads that are linked to above.

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/97106456-0a777700-16c2-11eb-8ca9-35a00cc94985.png)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | October 2020 Update
Browser:                               | Chrome 86.0.4240.111 x64
AdGuard version:                       | uBO 1.30.7b3 + IDCAC 3.2.3
Filters enabled:                       | See screenshot above
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by krystian3w** [comment]
If no needed compatiblity with Android Content Blocker or iOS / iPad OS:


`droidwin.com#?#.widget_custom_html:has(>h3:contains(/^Advertisements$/i))`

`androidexplained.com#?#article + div[class^="astra-advanced-hook"]:has(> .adsbygoogle)`

* `planetf1` - now right column should be 'empty' (without "`CrowdyNews`").

`planetf1.com#?#.custom-html-widget:empty`
`planetf1.com#?#.custom-html-widget:has(>div:empty+br)`

**Comment by Alex-302** [comment]
> from _Nano Placeholder Buster_

I suggest to not doing this. Maybe except really popular site.

**Comment by DandelionSprout** [comment]
I'm going through the sites again prior to each EasyList report, if that's what you're concerned about.

**Comment by Alex-302** [comment]
I understand, but some sites can be never visited by AdGuard users)

**Comment by DandelionSprout** [comment]
Ah. I was unaware that site popularity was still a criteria in AdGuard Base to this day.

**Comment by krystian3w** [comment]
#68902 - https://github.com/AdguardTeam/AdguardFilters/commit/99d3d0ceafe878543bd857a9877fc0eb61f05a63#diff-8e737f6429801c4aac12f0a8ddb7b4ab3173f39642bfe56004e22dede37edd6dR249 maybe too wide.
