### ISSUE TITLE
Youtube ads won't be blocked, HTTPS filtering error

### ISSUE THREAD

**Issue by simon3h** [AdguardTeam/AdguardFilters#66458]
Hi,

I have a problem with the ads in youtube android app. During the videos, I got ads but I read they cannot blocked. But adguard could block those ads that were inserted between the listed videos at home page and lists of videos that a search gave me.
I resetted my phone, installed and activated my licence but I can see all the ads in youtube app. Adguard also notes about a HTTPS filtering error: wwe.googleadservice.com, www.gstatic.com, ade.googlesyndicat.com, suggestqueries.google.com and firebaseinstallations.googleapis.com cerifications are not accepted by Youtube.

Could you help me with this kind of problem?

Simon

**Comment by BlazDT** [comment]
It is not possible as the app does not trust HTTPS certificates except their own.
Please Install YouTube Vanced App.
