### ISSUE TITLE
ray-ban.com - Newsletter sign up

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6645]
https://www.ray-ban.com/germany/mobile

<details><summary>Screenshot:</summary>

<img width="454" alt="screen shot 2017-09-07 at 10 33 32 pm" src="https://user-images.githubusercontent.com/27292111/30181663-9eea1054-941c-11e7-9d57-70ee77f566a2.png">

</details><br/>

***System configuration***

Application version: 1.3.2.108
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.29.91 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.30 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.85 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.87 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.51 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
Helpdesk ID: 1480792

**Comment by Alex-302** [comment]
Can't reproduce.
@AdamWr

**Comment by AdamWr** [comment]
Added to Annoyances filter:
`ray-ban.com##.header-newsletter-signup`
`ray-ban.com###wcs-newsletter-footer-signup`
