### ISSUE TITLE
PopSugar.co.uk - Various breakage (AdGuard Annoyances filter / AdGuard Tracking Protection filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#66480]
### Affected site:
`https://www.popsugar.co.uk/
`
### Issue:
Various breakage, because of a blocked cookie consent, and a geolocation asset.

### Examples:
* Blocked images:
`https://www.popsugar.co.uk/fashion/photo-gallery/43208082/embed/43300186/Emma-Vintage-YSL-Suit/`

* Also, the site's hamburger menu, and the search bar (located in the page header) doesn't work.

### Screenshots:
Not needed, as the problem is obvious.

### Problem filters / rules:
* **AdGuard Annoyances filter**
`###onetrust-consent-sdk`
`||cookielaw.org^$third-party`

* **AdGuard Tracking Protection filter**
`||geolocation.onetrust.com^`

### Possible fix:
`popsugar.co.uk#@##onetrust-consent-sdk`
`@@||cookielaw.org^$third-party,domain=popsugar.co.uk`

`@@||geolocation.onetrust.com^$domain=popsugar.co.uk`

### Other problem filters:
* **EasyList Cookie List** / **Fanboy's Annoyance List** / **Fanboy's Enhanced Tracking List** https://github.com/ryanbr/fanboy-adblock/issues/1425/
`###cookie-preferences`
`###onetrust-consent-sdk`
`||cookielaw.org^$third-party`
`-omniture.js`

* ~~**Frellwit's Swedish Filter** https://github.com/lassekongo83/Frellwits-filter-lists/issues/91/~~ _(FIXED)_
~~`||cookielaw.org/scripttemplates$script,domain=~crfashionbook.com|~eurogamer.net|~eurogamer.pl|~rockpapershotgun.com|~usgamer.net|~vg247.com|~zdnet.com`~~

* **I don't care about cookies** _(NOTIFIED)_
```
~msn.com,~nu.nl,~crfashionbook.com,~usgamer.net,~rockpapershotgun.com,~eurogamer.net,~eurogamer.pl,~zdnet.com,~vg247.com,~mensjournal.com,~autoweek.nl,~cbsnews.com,~assetstore.unity.com,~gmx.com,~gmx.es,~gmx.fr,~gmx.co.uk,~mail.com,~kruidvat.nl,~tvn24.pl###cookie-preferences

~msn.com,~nu.nl,~crfashionbook.com,~usgamer.net,~rockpapershotgun.com,~eurogamer.net,~eurogamer.pl,~zdnet.com,~vg247.com,~mensjournal.com,~autoweek.nl,~cbsnews.com,~assetstore.unity.com,~gmx.com,~gmx.es,~gmx.fr,~gmx.co.uk,~mail.com,~kruidvat.nl,~tvn24.pl###onetrust-consent-sdk
```

* **MVPS HOSTS**
`geolocation.onetrust.com`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.15.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.26 (XUL)

**Comment by Alex-302** [comment]
Thanks, fixed.
