### ISSUE TITLE
starbucks app trackers

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#66483]
mpsnare.iesnare.com (https://caanberry.com/what-is-iesnare-how-to-block-it/)
remote-data.urbanairship.com(https://whotracks.me/trackers/urban_airship.html)
device-api.urbanairship.com

**Comment by jordanelliott23** [comment]
https://apps.apple.com/us/app/starbucks/id331177714 @Alex-302

**Comment by jordanelliott23** [comment]
i am sorry i guess these are bad filters. they are located in exclusions list my bad: https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/Filters/exclusions.txt

@Sergey-Lyapin

**Comment by Sergey-Lyapin** [comment]
@jordanelliott23 No problem, thanks for reply. It is exclusions for DNS filters, I'll check it later and add more narrow exceptions in tracking's filter (if it necessary).
