### ISSUE TITLE
NSFW celebjihad.com

### ISSUE THREAD

**Issue by pjgufqgs** [AdguardTeam/AdguardFilters#6651]
Ads at the bottom on the right side and some along the very bottom all related to cams
url celebjihad.com

**Comment by Alex-302** [comment]
Fixed.
Please fill template next time.

**Comment by pjgufqgs** [comment]
It may work better if you replace celebjihad.com##.crp_related rule with 
###crp_related > div:nth-of-type(3)

Because the first rule blocks parts of the website that aren’t adverts.
Thanks
Also, sorry yes I will next time.

**Comment by Alex-302** [comment]
replaced by
```
celebjihad.com##.crp_related td[align="center"] > a[href^="https://www.celebjihad.com/widget/out/"][rel="nofollow"]
```

**Comment by pjgufqgs** [comment]
thanks
