### ISSUE TITLE
bttiantangs.com - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6652]
http://www.bttiantangs.com/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/30216468-c269e78a-94bb-11e7-88b5-8fd00aa1ef19.png)

</details><br/>

***System configuration***

Application version: 1.3.1.107
Device: iPhone
Platform: iOS
OS: 10.3.3
Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.99 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.87.26 Enabled=YES
ID=220 Name="CJX's Annoyance List" Version=1.0.1.48 Enabled=YES

Helpdesk ID :      1625630

**Comment by Alex-302** [comment]
fixed
