### ISSUE TITLE
coub.com

### ISSUE THREAD

**Issue by Numerok** [AdguardTeam/AdguardFilters#66537]
***Description***: 

Just hiding .timeline-banner is messing up coub's timeline scrolling with arrow keys
`coub.com#$#.timeline-banner { position: absolute!important; left: -3000px!important; } `
You just hiding ad coub which messes up timeline indexes

You should instead remove them fully with
`coub.com##.timeline-banner:remove()`
tried this with user filter and it works as expected.

* **Current behaviour**: 

if you press arrow down after scrolling through timeline you will end up skipping a bunch of coubs or even not be able to go anywhere because coub indexes are too far away

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
* **Screenshot**:

Not needed

* **Expected behaviour**: 

Press arrow down - next coub, arrow up - previous coub

***Steps to reproduce the problem***:

Scroll down with mouse scroll wheel about 30 coubs, after that press arrow up or down. Site will skip some coubs

**Filters:** Adguard base filter

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Google Chrome
AdGuard version:                       | latest chrome version

**Comment by Alex-302** [comment]
Ok, added.
