### ISSUE TITLE
m.fmhua.com - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6653]
http://m.fmhua.com/manhua/5800/752841.html

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/30217781-da675526-94bf-11e7-8878-fa7a03eeabc1.png)

</details><br/>

***System configuration***

Application version: 1.3.1.107
Device: iPad
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.11 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.34 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.94 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.99 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.87.25 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.3.79 Enabled=YES

Helpdesk ID :         1625580  

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
