### ISSUE TITLE
lieferando.de - Cookie notice

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6654]
https://www.lieferando.de/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/30218150-f69e31d2-94c0-11e7-8558-d46aa5ca841d.png)

</details><br/>

***System configuration***

Application version: 1.3.1.107
Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.29.81 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.29 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.81 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.80 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.51 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.53 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES

Helpdesk ID:           1609733

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
