### ISSUE TITLE
nzherald.co.nz - incorrect blocking of video ads in NZ

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6655]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: user can't play video because of incorrectly blocked video ads. 
As they state, those ads can be reproduced only from NZ. 
<details><summary>Current behaviour: </summary>

> Please find attached a screenshot showing what happens in NZ with Adguard 
running. The same happens using Adblock Browser (with Adguard disabled).
I have tried nzherald.co.nz videos while using ExpressVPN (UK & USA) which 
means Adguard vpn can not be running. The videos display without the 
advertisement but all the other ads appear. So it looks as though the video 
ads aren't displayed outside NZ.
I suggest you try a vpn to NZ and see what happens.
YouTube ads are blanked out by various apps including TubeCast, BubbleUPnP 
where there is a blank period until the ad is finished after which the 
video/music plays. The leading video ad disappears into a black hole. This 
is what I suggest for Adguard. I don't think it would be possible to jump 
past the ad. I tested nzherald videos by sharing videos or even complete 
web pages to BubbleUPnP where the videos ran after a delay while the advert 
ran unseen.

</details>

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/30225137-0fb6b84c-94da-11e7-8545-08c16f6ba899.png)

</details><br/>

***System configuration***:
**Filters:** 2, 3, 4, 14, 11, 15

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Android
AdGuard version:                    | 2.9.136
AdGuard mode (Android only):        | VPN
Filtering quality (Android only):   | High-quality
HTTPS filtering (Android only):     | On
Helpdesk ID (if exists):            | 1117961

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Seems to be a bug
https://github.com/AdguardTeam/AdguardForAndroid/issues/1435
