### ISSUE TITLE
Две проблемы которые очень долго никто не решал. otvet.mail.ru и kinopoisk.ru

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#6656]
Эти проблемы кажется годами пылятся у меня в пользовательских правилах, сейчас проверил и до сих пор они не решены.
И так - на ответах в самом низу страницы есть 4 громадных рекламных блока (ну или один разделен на 4), если вот это правило в "русский фильтр" включено:

> @@||ad.mail.ru/adq/?callback=jQuery$domain=realty.mail.ru|pogoda.mail.ru|otvet.mail.ru|horo.mail.ru|sport.mail.ru|auto.mail.ru|hi-tech.mail.ru|news.mail.ru|deti.mail.ru|health.mail.ru|afisha.mail.ru|lady.mail.ru|realty.mail.ru|cars.mail.ru|my.mail.ru

Вторая проблема со "скрытыми" комментариями на кинопоиске:
Открываете [эту](https://www.kinopoisk.ru/interview/3039768/) страницу, крутите в низ к комментам, находите "свернутый", нажимаете "раскрыть" и вас бросает в верх страницы, а коммент при этом все равно остается не раскрытым. Эта проблема связана с фильтром "виджетов и соц. сетей", а точнее с этим правилом:
> ||yastatic.net/*/share.js$third-party,domain=~alexey-osipov.ru|~avtodispetcher.ru|~fanserials.tv|~yandex.by|~yandex.kz|~yandex.ru|~yandex.ua

**Comment by Alex-302** [comment]
1 - у меня чисто. Исключение - для предотвращения исполнения скрипта замены рекламы.
2 - поправил.

**Comment by Smorvel** [comment]
Ну я же это не выдумал)
P.S. Проверять обязательно нужно с десктопной программой а не с расширение, так как она всегда работала хуже расширения почему-то, всегда то тут, то там пропускает что-то.

Вот скрин http://take.ms/yiQMv

**Comment by Alex-302** [comment]
У меня тех блоков и без блокировщика нет. Да и не рекламные они, похоже.
> ответа в пользу adguard не получил ни одного
программа может больше чем любое расширение. Фильтры не указаны, так что отзыв ни о чём.

**Comment by Smorvel** [comment]
Ну у других же есть, включая меня. При чем на телефоне оно тоже есть, и потом спрашиваете зачем мне ruadlist и easylist на мобильной версии приложения...
Нужно как-то решить.

**Comment by Alex-302** [comment]
Где написано, что те блоки - реклама?

**Comment by Smorvel** [comment]
Они ведут на другие проекты мыла.ру, да и одно то что вас их нет у меня есть уже не нормально... и другие блокировщики их блочат.
Никогда раньше там такого не было, когда появилось решил не писать, думал сами исправите, паралельно решил проблему у себя на время, но время шло а это так и не исчезало.

**Comment by Alex-302** [comment]
> Они ведут на другие проекты мыла.ру
такое не блокируем
> одно то что вас их нет у меня есть уже не нормально
дайте точный адрес страницы, может там появится.

**Comment by Smorvel** [comment]
Не появится... они как то определяют кому показывать, а кому не показывать.
Я подключился с другого компа, в другой стране, и там их тоже не оказалось, у себя я пробовал менять IP, менять useragent, запускать с чистого браузера, и во всех случаях они у меня были... почему? Я немогу понять...
![image](https://monosnap.com/file/Wf1UaqBgND05oNjIkQ8xXCVeky7PIy.png)

**Comment by Smorvel** [comment]
Если что, они должны быть на любой странице с вопросом. https://otvet.mail.ru/question/203118969

**Comment by Smorvel** [comment]
Короче вообще жесть) Смог наконец разобраться.. Если хотя бы на одном из браузеров выполнен вход в аккаунт, то эти блоки отображаются ВО ВСЕХ браузерах на компьютере))
Вот, зарегистрировал аккауннт, по идеи под моим аккаунтом должно отображать этот блок.
Логин napg6@mail.ru
Пароль 123qwe123

**Comment by Smorvel** [comment]
@Alex-302 удалось увидеть? Какие будут действия?

**Comment by Alex-302** [comment]
завтра буду смотреть.

**Comment by Alex-302** [comment]
Повторилось. Рекламных ссылок там нет.
Для пользовательского фильтра:
```
otvet.mail.ru##.block-portal-footer
```

**Comment by vitalkanev** [comment]
Firefox 55 на Xubuntu Zesty - блокнулся даже Footer с такими ссылками, как "Помощь", "Для бизнеса", "О Mail.ru"... @Alex-302

![Crashers](http://i.imgur.com/BbAs9YD.png)

**Comment by Smorvel** [comment]
@vitalkanev можешь просто выключить то правило о котором я написал в самом начале..
@Alex-302 все же зря вы решили это не блокировать, это явно реклама, хоть и внутренняя, да и другие блочат ее. Кстати, а что нужно вписать в пользовательские фильтры что бы деактивировать то правило которое вызывает эту проблему? **@@||**

**Comment by Alex-302** [comment]
А так?
```
otvet.mail.ru##.block-portal-footer > div:not([class="w-portal-footer"])
```

**Comment by Smorvel** [comment]
@Alex-302 Как деактивировать? (через свой фильтр)

> @@||ad.mail.ru/adq/?callback=jQuery$domain=realty.mail.ru|pogoda.mail.ru|otvet.mail.ru|horo.mail.ru|sport.mail.ru|auto.mail.ru|hi-tech.mail.ru|news.mail.ru|deti.mail.ru|health.mail.ru|afisha.mail.ru|lady.mail.ru|realty.mail.ru|cars.mail.ru|my.mail.ru

**Comment by vitalkanev** [comment]
@Alex-302 Это правило *тоже не сработало* - Footer ещё "пустой"

**Comment by Alex-302** [comment]
а предыдущее удалено?

**Comment by Smorvel** [comment]
@Alex-302 Может можно сунуть этот мусор хотя бы в фильтр раздражителей? Оно меня очень раздражает) этого не должно быть там.. да и хотелось бы очистить пользовательский фильтр от этого..

Использую такое правило:
`otvet.mail.ru##[id^="mailru"][class$="footer-slots-active"]`

**Comment by Smorvel** [comment]
@Alex-302 Уже годы прошли а adguard так и не хочет блочить эту фигню, при том ruadlist ее блокирует.
![image](https://user-images.githubusercontent.com/19754243/56512965-3811bc00-6531-11e9-8660-0a089001f1cc.png)
Может хотя бы в фильтр раздражителей ее занесете?

И вот еще какая проблема, с недавних пор появилась такая вот рекламка
![image](https://user-images.githubusercontent.com/19754243/56513026-6c857800-6531-11e9-9935-af12c463e255.png)

**Comment by Alex-302** [comment]
> Уже годы прошли а adguard так и не хочет блочить эту фигню, при том ruadlist ее блокирует.

это не реклама. У меня только баннер справа. Недавнее решение меньше суток продержалось.
