### ISSUE TITLE
https://thepiratebay.org/ - anti adblcok in captcha

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#6657]
Hey
have  anti adblock in site: https://thepiratebay.org/  in captcha
no see "I DONT ROOBOT" with adgurd
link exmple: https://thepiratebay.org/
Operating system: Windows 10 x64
Screenshot:  http://prntscr.com/giw7v2
Browser: Chrome
Adguard version: 6.1.331.1732

filter:
English filter
Annoyances filter
fanboys social blocking list
EasyLIstHebrew
adblock warning removal list
Anti-adblock Killer | reek

**Comment by Alex-302** [comment]
Can't reproduce. Please open filtering log, reproduce the issue and make screenshot of blocked requests.

**Comment by MrTal** [comment]
@Alex-302 
http://prntscr.com/gj1bwu

**Comment by Alex-302** [comment]
It is too wide.

**Comment by Alex-302** [comment]
Make screenshot of blocked requests in filtering log,

**Comment by MrTal** [comment]
@Alex-302 
http://prntscr.com/gjx7q8

**Comment by MrTal** [comment]
@Alex-302 
and It happens too site:
http://shink.in
exmple: http://shink.in/uymoY
Screenshot: http://prntscr.com/gjx9br
Screenshot filtering log: http://prntscr.com/gjx9pi
http://prntscr.com/gjx9y3

**Comment by Alex-302** [comment]
Try to disable the rule in Eng filter
```
||shink.in^$script
```

**Comment by MrTal** [comment]
@Alex-302 
yes thiw work with i  disable filter:
||shink.in^$script
||thepiratebay.org^$script,domain=thepiratebay.org

**Comment by Alex-302** [comment]
Please show me blocked requests
http://imagizer.imageshack.com/img924/3958/0hmZaU.png
or export it if you are using 6.2b.
