### ISSUE TITLE
more sites with Outbrain ads

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#66586]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: like https://github.com/AdguardTeam/AdguardFilters/issues/66555 (ad pictures)

`https://www.meine-anzeigenzeitung.de/lokales/muenchen-nord/nachbarschaftshilfe-garching-asa-gless-spendet-3000-euro-an-die-nachbarskinder-90083450.html`

`https://www.fehmarn24.de/fehmarn/guenther-zieht-notbremse-13928302.html`

`https://www.kreisbote.de/lokales/landsberg/alternative-zum-diessener-ortsbus-flexibles-nahverkehrssystem-auf-dem-pruefstand-90083945.html`

`https://www.dasgelbeblatt.de/lokales/bad-toelz-wolfratshausen/wolfratshausen-weltladen-nimmt-alte-handys-entgegen-90081544.html`

`https://www.kurierverlag.de/memmingen/deutschland-waehlt-den-vogel-des-jahres-2021-90081593.html`

`https://www.leinetal24.de/lokales/elze/mit-kluepfel-und-faeustel-90084237.html`

`https://www.deichstube.de/news/werder-bremen-ludwig-augustinsson-verletzt-eintracht-frankfurt-ausfall-davie-selke-niclas-fuellkrug-patrick-erras-felix-agu-personal-kader-bundesliga-90074595.html`

`https://www.lokalo24.de/lokales/fulda/bischof-fulda-hygiene-abstandsregeln-gottesdiensten-haben-sich-bewaehrt-13928854.html`

Information                            | Value
---                                    | ---
Operating system:                      | win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.12
Filters enabled:                       | default + Adguard Germany + Adguard Tracking Protetion + Adguard Annoyances
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by JobcenterTycoon** [comment]
One more: `https://www.frankfurter-wochenblatt.de/frankfurt/frankfurter-wochenblatt-mitte/ruhestand-nach-12874-tagen-dienst-13825095.html`

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.

**Comment by JobcenterTycoon** [comment]
Hi i have one more domain: `https://www.heidelberg24.de/baden-wuerttemberg/emmendingen-stuttgart-straftaeter-ausbruch-psychiatrie-flucht-fahndung-wolfgang-polizei-gericht-zr-90122105.html`

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.

**Comment by wout-codes** [comment]
@AdamWr `https://osthessen-news.de/n1243890/fulda-ich-pinkle-wenn-ich-das-m%C3%B6chte-wie-weit-d%C3%BCrfen-polizeibeamte-gehen.html`

**Comment by AdamWr** [comment]
Hello,
Fixed, update should be available in 1-2 hours.
