### ISSUE TITLE
https://yandex.ru/pogoda/tula/details - ads 

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardFilters#6658]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

ads on yandex.ru, yandex.pogoda. Adguard assistant is not showing on websites. 

**_System configuration_**

Information                         | Value
---                                 | ---
Operating system:                   | Microsoft Windows NT 6.1.7601
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | English, Annoyances, Russian, German
Helpdesk ID (if exists):            | 1018240

**Comment by evgeniy-ADG** [comment]
![image](https://user-images.githubusercontent.com/15856304/30249623-50bee4c6-9648-11e7-9726-c19035bf78a6.png)

В C:\ProgramData\Adguard\NetworkTemp\SSL два файла -  adguard perconal ca  и  cert.
Пользовательский пуст, кеш чищен, расширений нет (фильтрацю в касперском выключили). Фильтры 1 и 2, HTTPS включен, повторяется в Опере, Хроме и ИЭ. 

Тикет: 1625386

**Comment by evgeniy-ADG** [comment]
![image](https://user-images.githubusercontent.com/15856304/30249752-32c8f3f0-964b-11e7-844e-0a61bf97c173.png)

Тоже нет Помощника, пользователь 1018240.

**Comment by darkulish** [comment]
никаких пользовательских фильтров не задано, значок не отображается.
тикет - 16263

Screenshot:<https://user-images.githubusercontent.com/30834067/30250378-f79b6064-9655-11e7-8539-c35a65b0f258.JPG>

**Comment by Alex-302** [comment]
Нужен доступ. У нас не повторяется.

**Comment by ypetruk** [comment]
ticket id: 1625386
И еще одна интересная особенность, связанная с кэшем во всех трех  (IE, Opera, Google) браузерах. 
Если удалить весь кэш целиком, включая все cookie, то сразу после этого в Погоде рекламы нет, значок помощника есть (1-й скриншот, 22:34), но стоит только перезапустить браузер и снова зайти в погоду, то реклама появляется, а значок снова пропадает (2-й скриншот, 22:36).

<details><summary>1:</summary>

![100](https://user-images.githubusercontent.com/28784344/30282514-2e719ce8-971e-11e7-800a-3fa1f36dd3b0.png)

</details><br/>

<details><summary>2:</summary>

![200](https://user-images.githubusercontent.com/28784344/30282536-3d78ff74-971e-11e7-857a-664644a9ae20.png)

</details><br/>

**Comment by Alex-302** [comment]
Попроси кого-нибудь проверить с бетой 6.2.

**Comment by evgeniy-ADG** [comment]
> Добрый день!После обновления до последней бета-версии на сайте  https://yandex.ru/pogoda/petropavlovsk/details?lat=53.0721613&lon=158.6539368  перестала появляться реклама яндекс директ.

**Comment by Alex-302** [comment]
Ну тогда ждём релиза.
