### ISSUE TITLE
List without network filter

### ISSUE THREAD

**Issue by michaelb-ae** [AdguardTeam/AdguardFilters#66599]
### Prerequisites

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

- I want to know if it's possible to have a version of the list without the network filter since i already use adguard at the DNS level on my own network, and i would reduce the size of the list used.

### Proposed Solution

- Have a liste generated without network filter and only have esthetic filter.

### Alternatives Considered

- None.

### Additional Information

- N/A.

**Comment by Alex-302** [comment]
Hi. No. Filtering quality will worse.
You can download filters, and remove everything, except the lines with `#` symbol.
