### ISSUE TITLE
[leftovers] makeuseof.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6659]
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Google Chrome (Stable)
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
AdGuard DNS:                        | N/A
Stealth mode options (Windows only) | Enabled (only self deleting cookies is disabled)
Helpdesk ID (if exists):            | N/A
**Site with ad sample 1**|  http://www.makeuseof.com/tag/windows-10-features-changing/

![image-20170909-001](https://user-images.githubusercontent.com/9846948/30239133-28d012ca-9556-11e7-82dd-55139fbaeb95.png)

### Fix
```
makeuseof.com##.new-offers
```

**Comment by Alex-302** [comment]
Added
