### ISSUE TITLE
cbs.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6661]
***Site***: http://www.cbs.com/watch/
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30240348-2c7d9c6c-956f-11e7-88ac-edca7cc80e73.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by evgeniy-ADG** [comment]
@Alex-302 have a look, it's reproducible and people are complaining, too

**Comment by Alex-302** [comment]
It does not work with German VPN
`GeoLocationBlocked`
Check
```
@@||0914.global.ssl.fastly.net/ads/*/x.
@@cbs.com^$elemhide
@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$domain=cbs.com
@@||static.ads-twitter.com^$domain=www.cbs.com,third-party
@@moatads
@@||dw.cbsi.com/levt/video/e.gif
```

**Comment by Alex-302** [comment]
@AdamWr please check on you end.

**Comment by AdamWr** [comment]
It works with US VPN.
On my end these two rules are enough for Adguard for Windows:
`@@||cbs.com^$elemhide`
`@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$domain=cbs.com`

For Adguard Extension these three rules are needed:
`@@||cbs.com^$elemhide`
`@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$domain=cbs.com`
`@@||0914.global.ssl.fastly.net/ads/*/x.$domain=cbs.com`

By the way, if I'm not wrong, they use Sourcepoint script.
http://www.cbs.com/assets/build/js/video/jscbsplayer.min.js?20170914-001750

**Comment by Alex-302** [comment]
Thanks, added
```
@@||cbs.com^$elemhide
@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$domain=cbs.com
@@||0914.global.ssl.fastly.net/ads/*/x.$domain=cbs.com
```
@danidoedel check it

**Comment by danidoedel** [comment]
That seems to work. Thank you!
