### ISSUE TITLE
youdictionary.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#66641]
***Description***:
* **Current behaviour**: 

Shows ads on pages with word definitions. Cannot reproduce on my end.

<details><summary>Screenshot:</summary>

Screenshots available under helpdesk ticket 1934524.
</details><br/>

***Steps to reproduce the problem***:

1. Visit the site on either Edge Legacy or Firefox

***System configuration***

**Filters:**

EasyList Italy, Web Annoyances Ultralist, AdGuard Annoyances, AdGuard Base, AdGuard Tracking Protection, AdGuard Social Media

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows
Operating system version (Android/iOS) | Windows 10 19H1 (build 19362)
Browser:                               | Firefox Release / Edge Legacy
AdGuard version:                       | 7.5.2
Filters enabled:                       | EasyList Italy, Web Annoyances Ultralist, AdGuard Annoyances, AdGuard Base, AdGuard Tracking Protection, AdGuard Social Media
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | 1934524

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't open URLs like on screenshots.
Please ask user to export filtering log after reproducing an issue.

**Comment by akmLaVx** [comment]
@Alex-302 We've received logs from the customer.

**Comment by Alex-302** [comment]
@akmLaVx It seems `@@||www.yourdictionary.com^$important,document` enabled in user rules.
