### ISSUE TITLE
androidsage.com - Ad leftover - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6668]
***Site***: https://www.androidsage.com/2017/09/09/android-8-0-oreo-aosp-rom-for-nexus-6/
***Description***: Ad leftovers in right sidebar and at the beginning of the article. Newsletter sign up in right sidebar.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30240764-907b2480-9576-11e7-8146-345052c86593.png)

![image](https://user-images.githubusercontent.com/10995998/30240777-c9b3894a-9576-11e7-9e24-a65d5e4b0b74.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
