### ISSUE TITLE
lolskinlistgenerator.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6669]
***Site***: http://www.lolskinlistgenerator.com/
***Description***: Adblock detection (pops up a few seconds after you closed it again)

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30240802-89071ece-9577-11e7-84ad-e04b8240e37d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
