### ISSUE TITLE
http://bezopasnik.org/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6671]
http://bezopasnik.org/info/38.htm

![image](https://user-images.githubusercontent.com/15856304/30243282-f10cef12-95ae-11e7-8af8-28f18cf15f87.png)

***System configuration***

**Filters:** 

Russian, English, social media, Spyware, Annoyances

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Win 10
Browser:                            | Chrome
AdGuard version:                    | beta
AdGuard DNS:                        | Default 
Stealth mode options (Windows only) | Off
Helpdesk ID (if exists):            | 1449704

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
