### ISSUE TITLE
http://leeva.net.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6672]
http://chto-luchshe-reg-organizer-ili-ccleaner.leeva.net.ru/

![image](https://user-images.githubusercontent.com/15856304/30243312-639b6d42-95af-11e7-9829-a1b1eded8b1a.png)

***System configuration***

**Filters:** 

Russian, English, social media, Spyware, Annoyances

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Win 10
Browser:                            | Chrome
AdGuard version:                    | beta
AdGuard DNS:                        | Default 
Stealth mode options (Windows only) | Off
Helpdesk ID (if exists):            | 1449704

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Это чей-то умерший в зародыше сайт
http://imagizer.imageshack.com/img924/7117/cyLvWi.png
