### ISSUE TITLE
isale.su - Incorrect blocking 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6676]
https://isale.su/

<details><summary>Screenshot:</summary>

<img width="1443" alt="screen shot 2017-09-09 at 11 32 59 pm" src="https://user-images.githubusercontent.com/27292111/30243745-0980cbf4-95b9-11e7-97fb-28b7b5d1f219.png">

<img width="1440" alt="screen shot 2017-09-09 at 11 34 27 pm" src="https://user-images.githubusercontent.com/27292111/30243746-0e36cb62-95b9-11e7-8c06-29f141d2fdaa.png">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Mac 
Browser:                            | Chrome
AdGuard version:                    | 1.4.1
Filters enabled:                    | 1 2 3 4 14
Helpdesk ID:            | 1625421

**Comment by Alex-302** [comment]
fixed
