### ISSUE TITLE
chip.de - Ad leftover (Google browser app)

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6677]
http://www.chip.de/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/30244078-78fb882e-95bf-11e7-8f4f-0829687e4cba.png)

</details><br/>

***System configuration***

Application version: 1.3.1.107
Device: iPhone
Platform: iPhone OS
OS: 9.3.2

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.26 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.37 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.1 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.8 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.49 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.58 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.60 Enabled=YES

PRO:
Pro feature ENABLED.
Tunnel mode SPLIT
DNS server: Adguard DNS
176.103.130.130
176.103.130.131

Helpdesk ID: 1483141          

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
I can't reproduce it on iPad with Safari.
This screenshot is from Chrome for iOS and from what I know, on iOS cosmetic rules works only in Safari, so we can't block it.
