### ISSUE TITLE
golem.de - Ad leftover (Google browser app)

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6678]
https://www.golem.de/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/30244108-1ebb242c-95c0-11e7-8e66-aaf501b2f124.png)

</details><br/>

***System configuration***

Application version: 1.3.1.107
Device: iPhone
Platform: iPhone OS
OS: 9.3.2

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.26 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.37 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.1 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.8 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.49 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.58 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.60 Enabled=YES

PRO:
Pro feature ENABLED.
Tunnel mode SPLIT
DNS server: Adguard DNS
176.103.130.130
176.103.130.131

Helpdesk ID: 1483141

**Comment by veronikasav** [comment]
https://www.golem.de/ticker/

<details><summary>Screenshot:</summary>

<img width="592" alt="screen shot 2017-09-10 at 2 05 43 am" src="https://user-images.githubusercontent.com/27292111/30244725-9d132476-95cc-11e7-8d79-5bcd598231e5.png">

</details><br/>

[state (2).txt](https://github.com/AdguardTeam/AdguardFilters/files/1290147/state.2.txt)

Ticket ID: 1625676

**Comment by AdamWr** [comment]
I can't block this ad leftover and cookie notice in Google browser on iOS.

Ads in Safari fixed.
