### ISSUE TITLE
tz.de - Missed ad, social leftover

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6679]
https://www.tz.de/

<details><summary>Screenshot:</summary>

Ad:
<img width="450" alt="screen shot 2017-09-10 at 12 46 54 am" src="https://user-images.githubusercontent.com/27292111/30244175-a60aea4c-95c1-11e7-94a7-41389e6d076b.png">

Social leftover:
<img width="449" alt="screen shot 2017-09-10 at 12 47 15 am" src="https://user-images.githubusercontent.com/27292111/30244177-a74b8448-95c1-11e7-9b7e-3b79fb50c158.png">

Newsletter sign up:
<img width="442" alt="screen shot 2017-09-10 at 12 47 30 am" src="https://user-images.githubusercontent.com/27292111/30244178-a89fdc72-95c1-11e7-9070-280ba5a0943b.png">

</details><br/>

***System configuration***

Application version: 1.3.2.108
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.19 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.37 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.99 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.3 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.55 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.58 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES

Helpdesk ID:           1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Ads and social leftover fixed, but I can't hide newsletter, because it has the same name like weather widget.
