### ISSUE TITLE
jav380.com NSFW

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#66815]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

URL: `https://www.jav380.com/wanz-332-uncensored-leaked-%e5%ad%95%e3%81%be%e3%81%9b%e7%97%b4%e6%bc%a2%e9%9b%bb%e8%bb%8a-%e9%ba%bb%e5%80%89%e6%86%82.html`

Issue: popup when you click the blue "今すぐダウンロード" button. (`||realsrv.com^$popup` in EL China mitigates this.)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![jav380](https://user-images.githubusercontent.com/58900598/97864031-502fe180-1d4b-11eb-95cb-c57f513e0587.png)

</details><br/>

***System configuration***

**Filters:**

Base, Tracking, & Japanese (+ Chinese)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Brave 1.16.68
AdGuard version:                       | 3.5.20
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Disabled
Helpdesk ID (if exists):               | ?

**Notes**

`jav380.com#%#//scriptlet('abort-current-inline-script', 'document.querySelectorAll', 'popMagic')` works but IDK which file to add it (Base or JP). Also if Chinese is not enabled, you see anti-adb in the destination page `dl.520cc.cc`, not sure if it should be fixed though (the destination appears to be a Chinese site).

**Comment by Alex-302** [comment]
Cannot reproduce clickunder/popup and adblock detection. Blocked ad.

**Comment by Yuki2718** [comment]
`##.exopopclass` is not ad, it's required to download the video. I should have said auto-redirect than popup, but still getting the issue.

**Comment by Alex-302** [comment]
Ok, remoded my rule and added your.

**Comment by Yuki2718** [comment]
@Alex-302 Add `jav380.com#%#//scriptlet('abort-current-inline-script', 'document.querySelectorAll', 'popMagic')` too to prevent auto-redirect.

**Comment by Alex-302** [comment]
Done.
