### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by Barticf** [AdguardTeam/AdguardFilters#66813]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)
When AdGuard Base list is on, there is no youtube link in google result.

<details><summary>Screenshot:</summary>
![obraz](https://user-images.githubusercontent.com/32641928/97863800-de827400-1d07-11eb-99f3-d1c349a1fae4.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>
![obraz](https://user-images.githubusercontent.com/32641928/97863458-4d130200-1d07-11eb-9146-5d8512ffa34b.png)

</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:    Win                  | ?
Operating system version (Android/iOS) | ?
Browser:           Firefox                    | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Dziękuję za zgłoszenie.
Naprawione, aktualizacja filtrów powinna być dostępna za około 1-2 godziny.

Następnym razem podaj proszę konkretny link do strony :)
