### ISSUE TITLE
coca-cola-deutschland.de - Cookie notice

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6682]
http://www.coca-cola-deutschland.de/marken/apollinaris

<details><summary>Screenshot:</summary>

<img width="449" alt="screen shot 2017-09-10 at 12 55 59 am" src="https://user-images.githubusercontent.com/27292111/30244225-da1b2a9e-95c2-11e7-833b-5970d7c55956.png">

</details><br/>

***System configuration***

Application version: 1.3.2.108
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.19 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.37 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.99 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.3 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.55 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.58 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES

Helpdesk ID: 1480792

**Comment by AdamWr** [comment]
Fixed.
