### ISSUE TITLE
ruhrbarone.de - Cookie notice - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6683]
www.ruhrbarone.de

Information                         | Value
---                                 | ---
Operating system:                   | 10.3.3
Device:                                      |   iPhone
AdGuard version:                    | 1.3.1.107
Filters enabled:                    | 0,2,3,4,14,6,11,12,15
Helpdesk ID (if exists):            | 1609733

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
