### ISSUE TITLE
www.xxxlshop.de - Incorrect ad blocking - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6688]
***Description***:
* **Current behaviour**: 

[//]: # When going to the website www.xxxlshop.de with Adguard enabled, blank page opens 

Information                         | Value
---                                 | ---
Operating system:                   | 10.3.3
Device:                              | iPad
AdGuard version:                    | 1.3.1.82
Filters enabled:                    | 0,2,3,4,10,14,6,5,11,12,101,118,107,207,211,208,204,209,210,240
Helpdesk ID (if exists):            | 1610467

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Too many filters.
Try to disable `101,118,107,207,211,208,204,209,210,240`

**Comment by Alex-302** [comment]
@iverkhohliad

**Comment by iverkhohliad** [comment]
awaiting for the reply
