### ISSUE TITLE
m.imomoe.com - Missed ad 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6689]
http://m.imomoe.com/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/30244607-2a11fefe-95ca-11e7-8263-b5d3703385b2.png)

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.27.83 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.79 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.8 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.16.84 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.26 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.54 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.85.70 Enabled=YES

Helpdesk ID :          1625638

**Comment by Alex-302** [comment]
Fixed.
