### ISSUE TITLE
streamlive.to - Unblocked content under the video

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6690]
https://www.streamlive.to

Is it possible to add a rule to the filters which can block this content under the video? It is not possible to block it using element blocking tool.

<details><summary>Screenshot:</summary>

<img width="1197" alt="screen shot 2017-09-10 at 3 28 43 am" src="https://user-images.githubusercontent.com/27292111/30245107-391f9d26-95d8-11e7-9872-9e3ad9cd94d1.png">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Mac
Browser:                            | Safari
AdGuard version:                    | Adguard extension for Safari 
Filters enabled:                    | 1 2 3 4 14
Helpdesk ID:            | 1626067

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I need a direct link. Always for all issues.

**Comment by veronikasav** [comment]
Asked for the direct link.

**Comment by evgeniy-ADG** [comment]
https://www.streamlive.to/view/71632/Cartoon-Network


> as mentioned in my initial email to you, it is possible to successfully block the unwanted element but it reappears again with a different number each time the page is refreshed eg. streamlive.to##div:nth-child(52) streamlive.to##div:nth-child(61) streamlive.to##div:nth-child(53) etc.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
```
streamlive.to##div[style="font-size:x-large;padding-left:60px;"]
```
