### ISSUE TITLE
putlockers.fm - Doesn't block redirect to another website after clicking "play"

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6691]
http://putlockers.fm/watch/vMppyAJd-the-walking-dead-season-3/episode-4.html

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/30245417-761ad07a-95e1-11e7-84c0-b488fe48704c.png)

Redirect
![image](https://user-images.githubusercontent.com/27292111/30245419-7e5be698-95e1-11e7-9dc5-c5240d48fd12.png)

</details><br/>

***System configuration***

Application version: 1.3.1.107
Device: iPhone
Platform: iOS
OS: 10.3.2

Filters subscriptions:

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.22.91 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.12.95 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.20.74 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.51 Enabled=YES
Mobile ads filter
Annoyances filter

Helpdesk ID:          1626312

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Added `||3ba87e4828c5a95.com^` it should block redirect, but popup still will be opened.
