### ISSUE TITLE
Просьба купить VIP на trakt.tv

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#6692]
Такая вот фигня (см. скрин), на каждой странице, да еще и целых 3 штуки.. они довольно сильно мешают, было бы не плохо их внести в "Английский фильтр".
Я использую такое правило:

> trakt.tv###huckster-desktop-wrapper

Страница для примера https://trakt.tv/shows/rick-and-morty
<details><summary>Скрин:</summary>

![image](https://monosnap.com/file/cDTLojAZNRqTmaibI7gfWcm0P6CvlM.png)
</details><br/>

**Comment by Alex-302** [comment]
Оно фильтром раздражителей скрыто.
