### ISSUE TITLE
peperonity.net - Anti adblock

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6693]
https://peperonity.net/;jsessionid=D82E4B14CBCAFBC6577B380D5C8935BD.cdb01

<details><summary>Screenshot:</summary>

<img width="1385" alt="screen shot 2017-09-10 at 6 44 35 am" src="https://user-images.githubusercontent.com/27292111/30245963-ac51a4e0-95f3-11e7-9e15-e94607a1dd4f.png">

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Mac
Browser:                            | Chrome
AdGuard version:                    | 1.4.1
Filters enabled:                    | 1 2 3 4 14
Helpdesk ID:            | 1625001

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
