### ISSUE TITLE
olx.ro - Incorrect blocking

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6694]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: 
Adg blocks the images of objects that are for
sale
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/30247911-8d0a825e-9626-11e7-9059-57f3a819c2b1.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/30247912-9591adf8-9626-11e7-95bf-e31372d056c3.png)

</details><br/>

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Android
AdGuard version:                    | 2.9.136
Filters enabled:                    | 2, 3, 14, 11, 15, 114
AdGuard mode (Android only):        | VPN
Filtering quality (Android only):   | SPEEDY
HTTPS filtering (Android only):     | On
Helpdesk ID (if exists):            | 1625781

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
