### ISSUE TITLE
cnet.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6695]
***Site***: https://www.cnet.com/
***Description***: Ad leftovers.

*Rules:*
```
cnet.com##.ad-nav-ad
cnet.com##div[class^="ad-incontent-ad-plus-billboard-"]
cnet.com##.leadWrap
```

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30248038-d3735a3c-9620-11e7-8008-4dae86bccded.png)

![image](https://user-images.githubusercontent.com/10995998/30248049-123ac71e-9621-11e7-986e-1eca369b6476.png)

![image](https://user-images.githubusercontent.com/10995998/30248051-1c4d84da-9621-11e7-930d-169cf2151654.png)

![image](https://user-images.githubusercontent.com/10995998/30248054-25548024-9621-11e7-87da-3b153d426564.png)

![image](https://user-images.githubusercontent.com/10995998/30248055-309be88c-9621-11e7-8b45-32998b8365d9.png)

**https://www.cnet.com/news/iphone-x-iphone-8-iphone-8-plus-new-iphone-names-leak/:**

![image](https://user-images.githubusercontent.com/10995998/30248075-a582472c-9621-11e7-823d-02b8079f2892.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
