### ISSUE TITLE
freedomoutpost.com - Ad leftover - Anti Adblock Script - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6696]
***Site***: http://freedomoutpost.com/
***Description***: Adblock detection at the top. Logo above nav is missing. Pictures are missing. Ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30248175-3e013af2-9623-11e7-9d30-aa46f31371f6.png)

**Ad leftovers (http://freedomoutpost.com/court-sheriffs-conducted-unconstitutional-search-arrest-based-anonymous-source/):**

![image](https://user-images.githubusercontent.com/10995998/30248199-9bb17630-9623-11e7-97d9-a83d30b5fd03.png)

**How the main page should look like:**

![image](https://user-images.githubusercontent.com/10995998/30248196-7ed4c3c8-9623-11e7-865c-57cdb13ed969.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
