### ISSUE TITLE
libertyunyielding.com - Annoyance - Ad leftover - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6697]
***Site***: http://libertyunyielding.com/
***Description***: Adblock detection at the top. Ad leftover. Newsletter sign up.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30248232-09e0fc98-9624-11e7-97da-b478a19e675b.png)

![image](https://user-images.githubusercontent.com/10995998/30248242-25bd5f2e-9624-11e7-8a0f-0ebf921b1104.png)

![image](https://user-images.githubusercontent.com/10995998/30248244-31cf2e00-9624-11e7-8482-a5d06ba96abe.png)

**http://libertyunyielding.com/2017/09/09/ceo-hispanic-chamber-commerce-resigns-trump-council-live-tv-just-one-problem/:**

![image](https://user-images.githubusercontent.com/10995998/30248250-4e6ac178-9624-11e7-99e2-ad2f29ab0d7f.png)

![image](https://user-images.githubusercontent.com/10995998/30248254-60d12c3a-9624-11e7-8475-bac061f11cf8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
