### ISSUE TITLE
http://m.ok.ru/ - self-adverts

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6699]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: http://m.ok.ru/

> При входе с браузера на сайт одоклассники - стала мучать страничка с предложением скачать их приложение на телефон, а я не хочу его скачивать.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30249556-7338eb60-9647-11e7-8841-dc01bb676bc3.png)

</details><br/>

***Steps to reproduce the problem***:

> Когда в браузере перехожу по адресу ok.ru, то сайт Одноклассники открывается где-то на 1 секунду и с него сразу же происходит перенаправление на другой адрес (страницу), где  предлагается установить приложение.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Android 7
Browser:                            | Samsung Internet
AdGuard version:                    | 2.9.136
Filters enabled:                    | 2, 3, 14, 1, 11
AdGuard mode (Android only):        | both VPN and Proxy (manual)
Filtering quality (Android only):   | High-speed
HTTPS filtering (Android only):     | On (Default)
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | 1315829 - logs in the September 9 email

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня не повторяется. Но если происходит перенаправление, то в Samsung Internet это не исправить.

**Comment by evgeniy-ADG** [comment]
А что не так, чем особенный он? Можно нам подробностей, на будущее?

**Comment by Alex-302** [comment]
Блокировщик в Samsung Internet, как и в YB и iOS обладает скыдными возможностями, в частности не поддерживает JS-правила.
