### ISSUE TITLE
Ads in Google search, can't open the search results

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6700]
Originally been reported on Android: https://github.com/AdguardTeam/AdguardFilters/issues/2302

Added @@||googleadservices.com rule, to no avail. Is it possible to fix? Useful ads filter is disabled.

> Some of the links work some don't.. the one circled is one that didn't work... usually, when I search a product to buy some of the sites give me errors but link changes to googleleadservices.com and basically the ad block prevents that from loading up

I can't reproduce as our local google works a bit different and does not offer goods when I search them.

<details><summary>screenshots</summary>

![image](https://user-images.githubusercontent.com/15856304/30250344-497c1dd4-9655-11e7-81bd-760955f6519f.png)

![image](https://user-images.githubusercontent.com/15856304/30250346-4fc8897a-9655-11e7-950b-ce4c10570d84.png)

</details>

***System configuration***

**Filters:** 

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.29.18 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.16 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.22.63 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.1.82
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1395769

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Also can't reproduce.
Fixed some links in shopping section.
@AdamWr

**Comment by AdamWr** [comment]
How to reproduce this issue?
Should I enable useful ads filter(?), disable AdGuard DNS and then search something in Google and try to click on ads similar to these from screenshot?

**Comment by Alex-302** [comment]
> Should I enable useful ads filter(?)

yes.

Make some request and go to shopping section like on screenshot and press on results.

**Comment by Alex-302** [comment]
@AdamWr

**Comment by Alex-302** [comment]
@AdamWr
