### ISSUE TITLE
modapkfile.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#67000]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Looks like fake and they open popups
`https://modapkfile.com/`
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.20
Filters enabled:                       | default + Adguard Germany + Adguard Tracking Protection + Adguard Annoyances
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by lolka4toli** [comment]
Nothing to block – under construction.
