### ISSUE TITLE
Не запускается плеер на biqle.ru

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#6701]
Из за фильтра RU AdList не запускается плеер на сайте biqle.ru. Помогает вот такое правило:

> @@||daxab.com/player/^$domain=biqle.ru,third-party

Ссылка для теста https://biqle.ru/watch/-36621543_456242944

**Comment by Alex-302** [comment]
У нас поправил в фильтре аналитики. Сообщал автору фильтра.
