### ISSUE TITLE
mitele.es - anti-adblock

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#6702]
Original report:
https://forums.macrumors.com/threads/adguard-pro.2039619/page-2#post-24973228

There are some rules to fix it in the post.

**Comment by AdamWr** [comment]
It is related to this issue - https://github.com/AdguardTeam/AdguardFilters/issues/6051
This website works on Windows, but I can reproduce this anti adblock on my iPad.
How can I check what was blocked by AdGuard on iOS?

**Comment by ameshkov** [comment]
> How can I check what was blocked by AdGuard on iOS?

Huh, this is tricky. The thing is that to check what's blocked you need to get to the Safari console, here's how:
https://blog.idrsolutions.com/2015/02/remote-debugging-ios-safari-on-os-x-windows-and-linux/

**Comment by Alex-302** [comment]
Fixed.
