### ISSUE TITLE
spiegel.de

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdguardFilters#67029]
### Issue URL (Ads)
 
 https://www.spiegel.de/wirtschaft/unternehmen/corona-hilfen-fuer-november-wer-sie-bekommt-und-warum-gatronomen-besonders-profitieren-a-2a22896a-c40d-4a04-9397-30482ab140da

 ### Comment
 
 Username: @Morku
 
 > ## Spiegel introduced a new sliding bottom Adbanner to promote for S+
 > Die folgenden Informationen werden automatisch generiert. Bitte löschen Sie sie nicht.
 > Custom userscripts:
 > https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
 
 ### Screenshots
<details><summary>Screenshot-1:</summary>

![spiegel](https://user-images.githubusercontent.com/6276915/98248732-a1231e00-1f75-11eb-9573-951e4d70ef2d.png)

</details><br/>

 ### System configuration
 Information 	value
 AdGuard product: 	AdGuard for Windows v7.5.2
 Browser: 	Firefox
 AdGuard driver: 	WFP
 Stealth mode options: 	Hide your search queries,
 Send Do-Not-Track header,
 Remove X-Client-Data header from HTTP requests,
 Strip URLs from tracking parameters
 Filters: 	Ad Blocking:
 AdGuard Mobile Ads,
 AdGuard Base
 
 Privacy:
 AdGuard Tracking Protection
 
 Social Widgets:
 AdGuard Social Media
 
 Annoyances:
 AdGuard Annoyances
 
 Language-specific:
 AdGuard Russian,
 AdGuard German

**Comment by BlazDT** [comment]
Not seeing self-promo. Please check @AdguardTeam/filters-maintainers

**Comment by Morku** [comment]
I think worth to notice is:

I only can reproduce the Banner, when I open an article from the homepage.

Opening the article directly (like it is linked here) -> no Banner will appear.
So something redirecting like?

Follow the steps as I show her:

![2020-11-06 10-31-05](https://user-images.githubusercontent.com/6276915/98350482-b2266a80-201b-11eb-98db-1397a6c0daab.gif)

And no, I did not open a S+ exclusiv article.

**Comment by AdamWr** [comment]
@Morku Could you please check this rule:
```
spiegel.de###spPlusBanner
```

**Comment by Morku** [comment]
@AdamWr 
It's working fine!

**Comment by AdamWr** [comment]
Okay, added.
Thank you for your reply.
