### ISSUE TITLE
strunz.com - Cookie notice

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6704]
https://www.strunz.com/de/news/gibt-es-zu-viel-glueck-1.html

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/30254659-83ea9654-96a4-11e7-8053-11979553d9c4.png)

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.6 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.33 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.92 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.17.96 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.53 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.56 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES

Helpdesk ID: 1108721

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
