### ISSUE TITLE
shazam app bad filter fills log on iphone

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#67063]
im thinking blocking this maybe causing the log to fill up it keeps trying to reach beacon.shazam.com multiple times even when app is not in use. it stops once it is unblocked though
![107BB01B-0DCA-4DA3-A9EC-FB9274B2B70A](https://user-images.githubusercontent.com/71462072/98304064-dc791900-1f84-11eb-8247-d8f025a7bfc7.jpeg)

**Comment by Alex-302** [comment]
Not sure if tracker unblocking is a good solution.

**Comment by jordanelliott23** [comment]
> Not sure if tracker unblocking is a good solution.

yeah i agree. idk why it keeps trying to reach it in the background.
