### ISSUE TITLE
de.ecco.com - Cookie notice

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6706]
https://de.ecco.com/de-DE

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/30256099-d4e1cbca-96b0-11e7-8934-5c4de8024948.png)

</details><br/>

***System configuration***

Application version: 1.3.1.107
Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.27 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.37 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.1 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.8 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.55 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.58 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.60 Enabled=YES

Helpdesk ID:          1609733

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
