### ISSUE TITLE
Кнопка зоны на torrentino.me

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#6707]
Не знаю блокируете ли вы такое.. Мое дело сообщить.
Здесь http://www.torrentino.me/movie/891017-ghost-house при нажатии на любую **зеленую** кнопку "скачать" выскакивает попап, на котором есть громадная зеленая кнопка "Скачать торрент" которая ведет на скачку зоны.
Избавляюсь от нее таким правилом:
> torrentino.me##.z-mobi.button.rounded.middle.start-download

Еще эта кнопка проявляется на страницах с книгами, музыкой и т.д. тут уже без попапа http://www.torrentino.me/torrent/1127271
> torrentino.me##a.button.download.rounded.middle.zona-link-check.start-download

**Comment by Alex-302** [comment]
Поправил.
