### ISSUE TITLE
www.turbobit.net - Banner - Windows

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6708]
***Description***:
* **Current behaviour**: 

[//]: # Ad banner on the page http://turbobit.net/download/free/2qu8hiv2btds

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](http://radikal.ru/lfp/s013.radikal.ru/i322/1709/bf/c591025209b5.png/htm)
</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10.0
Browser:                            | Chrome
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 1,2,3,4,10,11,0,14
Stealth mode options (Windows only) | enabled
Helpdesk ID (if exists):            | 1449704

**Comment by Alex-302** [comment]
Fixed.
