### ISSUE TITLE
www.elderland.de - AdBlocker not accepted  on the web page - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6709]
***Description***:
* **Current behaviour**: 

[//]: # https://elderland.de/

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30264617-f37095ea-96e1-11e7-8072-657ae7561ded.png)
)
</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Device:                               | iPhone
Browser:                            | Safari
AdGuard version:                    | 1.3.2.108
Filters enabled:                    | 0,2,3,4,14,6,11,12
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1480792

**Comment by AdamWr** [comment]
Fixed.
