### ISSUE TITLE
www.briefwahl-beantragen.de - Missed ad -iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6710]
***Description***:
* **Current behaviour**: 
https://www.briefwahl-beantragen.de/Hessen/Frankfurt-am-Main

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30265148-f0f709e6-96e3-11e7-8e4a-f1be94493882.png)

![image](https://user-images.githubusercontent.com/31481372/30265162-0073c008-96e4-11e7-9adb-ef9b442b21b5.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Device:                               | iPhone
Browser:                            | Safari
AdGuard version:                    | 1.3.2.108
Filters enabled:                    | 0,2,3,4,14,6,11,12
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1480792

**Comment by AdamWr** [comment]
Fixed.
