### ISSUE TITLE
Slingplayer - ads - Mac

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6711]
***Description***:
* **Current behaviour**: 

[//]: # Ads in Slingplayer. Similar issue was resolved a while ago  -- Helpdesk ID 1024471. At that time User filter rules were added to dropbox but are gone now. New solution needed.

Information                         | Value
---                                 | ---
Platform:                                   |Mac OS X
Operating system:                   | 1012
AdGuard version:                    | 1.5.0 beta
Filters enabled:                    | 0,2,3,4,10,1,6,7,16,8,109,111,216
Helpdesk ID (if exists):            | 1043390

**Comment by Alex-302** [comment]
What is Slingplayer? I need detailed description how to reproduce and screenshot.

**Comment by Alex-302** [comment]
@iverkhohliad

**Comment by iverkhohliad** [comment]
http://www.slingbox.com/Products/Slingplayerapps.aspx
no screen yet

**Comment by Alex-302** [comment]
> I need detailed description

**Comment by iverkhohliad** [comment]
User has not replied yet. I asked for a screenshot
