### ISSUE TITLE
Rambler and Yandex ads - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6712]
***Description***:
* **Current behavior**: 

Nothing helps when trying to filter ads on Yandex and rambler. 
Not reproduced on our side
<details><summary>Screenshot:</summary>

![screen shot 2017-09-11 at 4 31 53 pm](https://user-images.githubusercontent.com/28784344/30276847-c665bbde-970e-11e7-8f56-3b973ae48582.png)

</details><br/>

<details><summary>Screenshot:</summary>

![screen shot 2017-09-11 at 4 33 01 pm](https://user-images.githubusercontent.com/28784344/30276888-f080bea0-970e-11e7-97af-f5ec909cb5e6.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser                                   | Explorer
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 1,2,3,4,8,0, 14 
Helpdesk ID (if exists):            | 648896

**Comment by Alex-302** [comment]
URLs?

**Comment by Alex-302** [comment]
@ypetruk

**Comment by veronikasav** [comment]
Asked for URLs.
