### ISSUE TITLE
otpusk.com - Incorrect blocking

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6713]
https://www.otpusk.com/hotel/57736-grand_nar_hotel#c=2017-09-13&v=2017-09-19&l=7&n=0&g=1&st=1%2C2%2C3%2C4%2C5&pf=0&pt=0&rt=0%2C10&e=&sr=&r=air%2Cbus%2Ctrain%2Cship&w=false&ex=1&tab=tour-options&d=1544&t=Grand%20Nar%20Hotel&i=57736&y=hotel&p=2&tc=&oid=30614532225&ol=7&od=2017-09-13&f=1&o=ob%2Cbb%2Chb%2Cfb%2Cai%2Cuai

Adguard blocks the price for the tour.

<details><summary>Screenshot:</summary>

Adguard disabled
![image](https://user-images.githubusercontent.com/27292111/30281532-5f469998-971b-11e7-8717-8df91a38c0cf.png)

Adguard enabled
![image](https://user-images.githubusercontent.com/27292111/30281603-8b1c272c-971b-11e7-9c4e-f2e2a4523645.png)

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | 6.1
Filters enabled:                    | 1 2 3 4 14
Helpdesk ID:            | 1626972

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
