### ISSUE TITLE
dropbox.com

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardFilters#67139]
Issue:
Dropbox stays blank while trying to access a file.

Steps to reproduce:
1. make sure you're not logged in to Dropbox.com
2. try to access a file someone sent you
3. the page does not load with AdGuard enabled.

I'm having this issue since a few months now on both MacOS and iOS, sometimes it helps to clear the cache, but a 100% solution is to disable AdGuard on Dropbox.

Filters:
Adguard Base, Tracking, Annoyances, Social Media, German.

Screenshots with AdGuard enabled / disabled:

[image](https://user-images.githubusercontent.com/4127356/98440804-2ab02880-20fb-11eb-9739-30bdf161558c.png)

[image](https://user-images.githubusercontent.com/4127356/98440855-8a0e3880-20fb-11eb-9334-710114506a48.jpeg)

**Comment by Alex-302** [comment]
Cannot reproduce. Which filter causes it?

**Comment by iDjay** [comment]
@Alex-302 sorry for the late response, it's the base filter. Could be an issue with the cookie notification blocking.

**Comment by Alex-302** [comment]
But Base filter does not block cookie notifications.
Please test these rules one by one:
`@@||dropbox.com^$`
`@@||dropbox.com^$`
`@@||dropbox.com^$`
`@@||dropbox.com^$`

**Comment by Alex-302** [comment]
But Base filter does not block cookie notifications.
Please test these rules one by one:
`@@||dropbox.com^$content`
`@@||dropbox.com^$urlblock`
`@@||dropbox.com^$elemhide,jsinject,extension`
`@@||dropbox.com^$document`

**Comment by Alex-302** [comment]
@iDjay Any news?

**Comment by iDjay** [comment]
No time to test yet. The weird thing is that it's only happening sometimes.

**Comment by Alex-302** [comment]
Ok, closed. But will look for your replies.
