### ISSUE TITLE
Help for scriptlet

### ISSUE THREAD

**Issue by BSboysan** [AdguardTeam/AdguardFilters#67136]
How can I speed up the countdown? And I want to go to the link automatically.
Could you create a scriptlet my user filter?
Thank you.

---

Click on the ntv.com.tr link below for the countdown.

https://forum.donanimhaber.com//mesaj/yonlen/146080859

![forum donanimhaber com (3)](https://user-images.githubusercontent.com/74098460/98439608-145a9a80-2104-11eb-8a85-4a9947763ab2.png)

![forum donanimhaber com (4)](https://user-images.githubusercontent.com/74098460/98439634-305e3c00-2104-11eb-82a6-9aedbde203ea.png)

**Comment by BSboysan** [comment]
It's not necessary anymore

**Comment by BSboysan** [comment]
It started again. Please help

https://forum.donanimhaber.com/turkiye-ye-yatirim-yapmaktan-vazgecen-volkswagen-slovakya-yi-secti--146412722

<details>
 <summary>IMG</summary>
 
![forum donanimhaber com](https://user-images.githubusercontent.com/74098460/98682620-2e4ee400-2375-11eb-96d0-607187ac7daf.png)


</details>

<details>
 <summary>IMG2</summary>

![dh2](https://user-images.githubusercontent.com/74098460/98682650-36a71f00-2375-11eb-99dd-2b373d668a9e.png)

</details>

**Comment by zloyden** [comment]
Try this `forum.donanimhaber.com#%#//scriptlet("set-constant", "remainingTime", "0")`

**Comment by BSboysan** [comment]
I tried your solution, and it does work. 
Thank you
@zloyden

**Comment by zloyden** [comment]
That's nice.

**Comment by BSboysan** [comment]
@zloyden 
Please remove this rule because it prevents opening some links.

https://streamable.com/vze5vq

thanks for your help

**Comment by zloyden** [comment]
Ok, I removed it from our filters. Thanks for you response.
