### ISSUE TITLE
Ads on Mako TV

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#6714]
@darkulish commented on [Sun Sep 10 2017](https://github.com/AdguardTeam/AdguardForAndroid/issues/1437)

Ads in Mako TV, logs attached

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/17472907/30283456-db438af6-9720-11e7-9dc4-3734a032ba6a.png)

![image](https://user-images.githubusercontent.com/17472907/30283465-de2a3f58-9720-11e7-978a-a4df7b3e29d6.png)

</details>

### Customer ID 
1455606

### Your environment

* Android version: 7.1.1 (sdk=25)
* Adguard version: 2.9.136
* Device model: OnePlus ONEPLUS A5000

**Comment by AdamWr** [comment]
Could you please ask user for a link to app/website?
I guess, it is this app - https://play.google.com/store/apps/details?id=com.keshet.mako.VOD
Yes?

**Comment by vitbortnik** [comment]
@AdamWr Yes, this is the right app.

**Comment by AdamWr** [comment]
Ok, thank you.
I will check it later.

**Comment by AdamWr** [comment]
This app is incompatible with my device.
@Alex-302 could you please check it?

**Comment by Alex-302** [comment]
Try this
https://apkpure.com/makotv/com.keshet.mako.VOD

**Comment by Ezmez** [comment]
Hi guys
Thank you for this. 
Any progress?

**Comment by AdamWr** [comment]
Hi,
I installed this app and if I understand correctly most of videos are paid.
I found few free videos, but I couldn't reproduce ads.
In some videos I see this message:

<details><summary>Screenshot</summary>

![mako](https://user-images.githubusercontent.com/29142494/30830282-c1a2b206-a243-11e7-9bf0-9ee3e1a2b3d4.png)


</details>
<br>

Could you please translate it and tell me how to reproduce these ads?

**Comment by Ezmez** [comment]
OK so what is says is : this is not available in your region.
Can you change your region to Israel? Mabey use VPN or something...

**Comment by Alex-302** [comment]
@AdamWr

**Comment by AdamWr** [comment]
I'm sorry, but I missed your answer.
I still can't reproduce ads, I see them only if I disable AdGuard.
If you still see ads, please make a HAR file and reproduce the issue - https://kb.adguard.com/en/android/solving-problems/har and then please send it to AdGuard support and write ticket number here.

**Comment by Alex-302** [comment]
@AdamWr 
> Android version: 7.1.1 (sdk=25)
AdGuard certificate may be moved to system storage for filtering HTTPS in the most of apps on Android 6 and 7

**Comment by Alex-302** [comment]
Try to create specific rules to block ads for this app without HTTPS filtering.

**Comment by AdamWr** [comment]
I couldn't reproduce ads even with HTTPS filtering disabled.
