### ISSUE TITLE
[nsfw] nude-share.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6715]
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Google Chrome (Stable)
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
Stealth mode options (Windows only) | Enabled (only self deleting cookies is disabled)
**Site with ad sample**|  http://nude-share.com/photo.php?id=386601&cat=nipples

### Issue

- Ads box banners on right sample 2 site. Sometimes is loaded one box, but are two.

### Screenshoot:
![image-20170911-002](https://user-images.githubusercontent.com/9846948/30283731-2785099c-9719-11e7-8b96-dfcf1a0743a1.png)

**Comment by AdamWr** [comment]
Fixed.
