### ISSUE TITLE
[bug] ipla.tv

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6716]
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Google Chrome (Stable)
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
Stealth mode options (Windows only) | - disabled here but not resolved issue
**Site with ad sample 1**| https://www.ipla.tv/Twoja-twarz-brzmi-znajomo-8-odcinek-1/vod-10167423

### Isssue

Cannot play any video on ipla.tv CC @AdamWr 

### Screenshoot:
![image-20170911-003](https://user-images.githubusercontent.com/9846948/30289654-2b9cb340-972d-11e7-8885-ff6ba3514039.png)

**Comment by AdamWr** [comment]
Wygląda na to, że to jakiś błąd, zgłoszone tutaj - https://github.com/AdguardTeam/AdguardForWindows/issues/1928
