### ISSUE TITLE
https://coinlink.us - anti adblock

### ISSUE THREAD

**Issue by MrTal** [AdguardTeam/AdguardFilters#6717]
Hey
have  anti adblock in site: https://coinlink.us
link exmple: https://coinlink.us/9apxD
Operating system: Windows 10 x64
Screenshot:  http://prntscr.com/gjxcoe
Browser: Chrome
Adguard version: 6.1.331.1732

filter:
English filter
Annoyances filter
fanboys social blocking list
EasyLIstHebrew
adblock warning removal list
Anti-adblock Killer | reek

**Comment by Alex-302** [comment]
Fixed
