### ISSUE TITLE
CBS news app cant watch live videos

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#67171]
I removed all my custom filters and am using only simplified domain filter for dns blocking cant figure out what’s breaking the videos. They only play if I disable dns filtering

https://apps.apple.com/us/app/cbs-news-live-breaking-news/id334256223

**Comment by Sergey-Lyapin** [comment]
@jordanelliott23 
Hello, this app is unavailable in my country.
If you want you can install AdGuard Home (which uses same DNS filter) and in its filtering log you will see blocked requests and you will be able to whitelist them one by one to find out which rule causes the problem. 
https://github.com/AdguardTeam/AdGuardHome/wiki/Getting-Started#installation

@BlazDT @AdamWr Is this app available to you?

**Comment by BlazDT** [comment]
Also not available.

**Comment by Sergey-Lyapin** [comment]
@jordanelliott23

I was able to install this app and reproduce the problem. Hope that I will find solution soon.

**Comment by Sergey-Lyapin** [comment]
@jordanelliott23

Please add this rule to DNS protection > DNS filtering > Blocklist
`@@||pubads.g.doubleclick.net^$important`

Unfortunately we can't unblock this domain because it is being often used for advertising.
