### ISSUE TITLE
viz.com - Anti AdBlock script - Windows

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6718]
***Description***:
* **Current behaviour**: 
https://www.viz.com/watch/streaming/media/naruto-shippuden-episode-176/2437/sub

Anti AdBlock script on Windows
is reproduced on our side (Mac OS)(used VPN extension to enter the web-site)

<details><summary>Screenshot:</summary>

![screen shot 2017-09-11 at 10 35 52 pm](https://user-images.githubusercontent.com/28784344/30293377-eebb7ece-9741-11e7-84f0-6186e18a9750.png)

</details><br/>

***System configuration***

**Filters:**

Information                         | Value
---                                 | ---
Operating system:                   | Mac os
Browser:                            | Chrome, Edge
AdGuard version:                    | 1.4.1.
Filters enabled:                    | 1,2,3,4,5,14
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1612341

**Comment by AdamWr** [comment]
It is related to this issue - https://github.com/AdguardTeam/AdguardFilters/issues/5706
It works fine with AdGuard for Windows on my end.

**Comment by ghajini** [comment]
@alex-302 viz tries to detect anonymous software so use this VPN, vyprvpn with chameleon technology and San franscico server.....
![img_20171008_235040](https://user-images.githubusercontent.com/20338483/31319651-f808fc38-ac84-11e7-8db1-99f396c266da.JPG)


Current implementation of adguard works only who use adgaurd for windows and not browser extension users....may be you come with new solution for browser extension users.....

**Comment by Alex-302** [comment]
> solution for browser extension users.

do you mean $mp4 modifier?

**Comment by ghajini** [comment]
Yep.... $mp4 modifier not available for browser extension users?, I think

**Comment by Alex-302** [comment]
Yes, it can be used by standalone apps only.
@ameshkov is it possible in our extension?

**Comment by ameshkov** [comment]
In theory -- yes, it's possible, just like it's done for $empty
