### ISSUE TITLE
sanarmed.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#67184]
[https://www.sanarmed.com/aprenda-plexos-de-uma-vez-por-todas-anatomia-por-metodo-mnemonico-e-de-agrupamento-colunistas](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.sanarmed.com/aprenda-plexos-de-uma-vez-por-todas-anatomia-por-metodo-mnemonico-e-de-agrupamento-colunistas)

![sanar](https://user-images.githubusercontent.com/35470489/98452500-a1b2e480-212e-11eb-9175-5f903c9f9a3c.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by debmaj2** [comment]
Those are not official social media embeds. They are custom buttons.

**Comment by adranger** [comment]
@debmaj2 You don't seem to be familiar with the contents and scope of this project, so please refrain from leaving comments that generate meaningless notifications.

**Comment by debmaj2** [comment]
> @debmaj2 `AdGuard Social Media` hides sharing buttons in general. It doesn't matter if they are "official" or not.

Let the Maintainer comment on this.

You may check: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_4_Social/filter.txt

Most official Sharing Buttons contain tracking scripts which tracks you even if you don't use the buttons (such as Facebook Like, Tweet, Disqus, etc.)

However, the one on the site is merely a button with a hyperlink which isn't an annoyance or actively tracking you.

**Comment by adranger** [comment]
@debmaj2 I've already reported over 400 issues to this repository. The link you told me to check contains several social buttons that I've reported myself.  As I've already said,[ it doesn't matter if they use official scripts or are just images](https://kb.adguard.com/en/general/adguard-ad-filters):

>Social media filter — removes numerous "Like" and "Tweet" buttons and other social media integrations on popular websites.

Please stop creating comments on repositories you don't really know much about. They generate meaningless notifications and make people waste their time correcting you.
