### ISSUE TITLE
fb.ru - Banners, Assistant is missing

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6719]
http://fb.ru/article/173829/luchshaya-programma-dlya-optimizatsii-kompyutera-obzor

Adguard assistant is missing.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/30293557-aa4686ca-9742-11e7-9046-d562742592f7.png)

![image](https://user-images.githubusercontent.com/27292111/30293591-c64f24d0-9742-11e7-80fe-b7347ff88907.png)

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | 6.1
Filters enabled:                    | 1 2 3 4 10 11 14
Helpdesk ID:            | 1449704

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. Try beta 6.2

**Comment by veronikasav** [comment]
Asked our customer to try beta 6.2
