### ISSUE TITLE
Правила войны

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#672]
http://plarium.com/ru/igri-strategii/pravila-voyni/igra/

Данные по аккаунту: 
fclmfan13@yandex.ru
sir_douchebag / comawhite13

Реклама в верхней части в самой игре: https://yadi.sk/i/9Y-n5L8Ni5b69

ZIS-229-69476

**Comment by Alex-302** [comment]
чисто у меня. Возможно какое-то расширение срёт. Пусть в IE проверит
