### ISSUE TITLE
www.allmusic.com  -  Ad leftover and bookmark banner - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6720]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # Ad leftover and bookmark banner, social bar.
http://www.allmusic.com/blog/post/rex-brown-interview

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30309772-c40b2158-9795-11e7-8b2a-c93638efea52.png)

![image](https://user-images.githubusercontent.com/31481372/30309790-d79602ec-9795-11e7-95a0-141c5f316817.png)

![image](https://user-images.githubusercontent.com/31481372/30309795-e06c7824-9795-11e7-9e76-eb5e9e0cea08.png)

![image](https://user-images.githubusercontent.com/31481372/30309806-eb882aa0-9795-11e7-9b1f-586cbc56dacd.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Device: | iPhone
Browser:                            | Safari
AdGuard version:                    | 1.3.2.108
Filters enabled:                    | 0,2,3,4,14,6,11,12
AdGuard DNS:                     | None
Helpdesk ID (if exists):            | 1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
I can't reproduce bookmark banner.
For ad leftover and social, please check these rules:
`allmusic.com##.advertising`
`allmusic.com##.promo > [title="Newsletter banner"]`
`allmusic.com###ctoolbar`
