### ISSUE TITLE
www.greenocktelegraph.co.uk - Ads - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6721]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Adblock detection and newsletter sign up

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30310111-7eee8c66-9797-11e7-8a25-3cfef2bb0f77.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Device: | iPhone
Browser:                            | Safari
AdGuard version:                    | 1.3.2.108
Filters enabled:                    | 0,2,3,4,14,6,11,12
AdGuard DNS:                     | None
Helpdesk ID (if exists):            | 1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.

**Comment by theBeautifier** [comment]
@AdamWr There is also a cookie banner at the bottom:

![image](https://user-images.githubusercontent.com/28259813/30516069-addd1344-9b34-11e7-8487-50197ab69671.png)

**Comment by AdamWr** [comment]
Ok, fixed.
