### ISSUE TITLE
www.gp.se - Adblock detection - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6722]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

http://www.gp.se/nyheter/ekonomi/zlatan-bes%C3%B6ker-volvo-i-g%C3%B6teborg-1.4622442

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30310209-f5f6b4f0-9797-11e7-8216-becc4dc540c1.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Device: | iPhone
Browser:                            | Safari
AdGuard version:                    | 1.3.2.108
Filters enabled:                    | 0,2,3,4,14,6,11,12
AdGuard DNS:                     | None
Helpdesk ID (if exists):            | 1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
