### ISSUE TITLE
NSFW - http://stream-mydirtyhobby.biz/ - pop up - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6723]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Pop under when clicking on the video (most videos on the site are fine):
http://stream-mydirtyhobby.biz/view/fitness-maus-skandal-nackt-beim-sport/G361p

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30310373-ed811fee-9798-11e7-966a-22acb4bc5da0.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Device: | iPhone
Browser:                            | Safari
AdGuard version:                    | 1.3.2.108
Filters enabled:                    | 0,2,3,4,14,6,11,12
AdGuard DNS:                     | None
Helpdesk ID (if exists):            | 1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added for Safari
`||u1trkqf.com^`
