### ISSUE TITLE
NSFW - www.tubous.com - Ad leftovers - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6724]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Ad leftovers 
https://www.tubous.com/videos/971500/fucking-while-talking-on-cell-phone-to-boyfriend-german-aische-pervers

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30310580-c78749e8-9799-11e7-9524-992c0a989955.png)

![image](https://user-images.githubusercontent.com/31481372/30310590-d6df09e4-9799-11e7-8e57-969307277851.png)

![image](https://user-images.githubusercontent.com/31481372/30310594-dffad4d6-9799-11e7-82e3-74dad11d37a9.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Device: | iPhone
Browser:                            | Safari
AdGuard version:                    | 1.3.2.108
Filters enabled:                    | 0,2,3,4,14,6,11,12
AdGuard DNS:                     | None
Helpdesk ID (if exists):            | 1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
