### ISSUE TITLE
NSFW - m.tubewolf.com - Incorrect ad blocking - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6725]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

http://m.tubewolf.com/movies/blonde-milf-shaved-pussy/?promoid=AlexZ

Clicking on the video doesn’t play the video and does only direct to a black page: 

--->  http://m.tubewolf.com/play/blonde-milf-shaved-pussy/

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30310668-4aa49ec0-979a-11e7-9ea5-1dd898996bee.png)

![image](https://user-images.githubusercontent.com/31481372/30310680-546585f0-979a-11e7-8d05-608f8234011a.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Device: | iPhone
Browser:                            | Safari
AdGuard version:                    | 1.3.2.108
Filters enabled:                    | 0,2,3,4,14,6,11,12
AdGuard DNS:                     | None
Helpdesk ID (if exists):            | 1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
