### ISSUE TITLE
NSFW - vivud.com - Ad leftovers and pop up - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6726]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Ad leftovers and pop up when clicking on a video on the main page:
http://vivud.com/video/23875/

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30310743-a50d1fc2-979a-11e7-9df2-2639bf7dd19b.png)

![image](https://user-images.githubusercontent.com/31481372/30310753-acf99918-979a-11e7-94ee-f7746e1d1631.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Device: | iPhone
Browser:                            | Safari
AdGuard version:                    | 1.3.2.108
Filters enabled:                    | 0,2,3,4,14,6,11,12
AdGuard DNS:                     | None
Helpdesk ID (if exists):            | 1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed

**Comment by theBeautifier** [comment]
@Alex-302 Ad leftovers still there...
