### ISSUE TITLE
[bug][stealth] opera.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6727]
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Opera Stable x64
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
Stealth mode options (Windows only) | Enabled (only self deleting cookies is disabled)
Site sample | https://addons.opera.com

Please add
```
@@||opera.com^$stealth
```
cause when Stealth mode is enabled opera.com site cannot recognize Opera Browser at all.

**Comment by Alex-302** [comment]
You can use another user-agent.
