### ISSUE TITLE
securitytrails.com (N: uBlock Origin) (N: AdGuard for Windows) (T: Incorrect Blocking)

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#67279]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

I use (and rely heavily on) this site from time to time during my filterlist writing, such as to check which domains that belong an IP address.

This makes it unfortunate that on many of the ad-hosting domains I'm searching for on that site, either the domain's icon fails to load, an error page saying *"Something went wrong while connecting to server, please try again later."* shows up, or both.

The fix in https://github.com/easylist/easylist/issues/5696 seemed to fail to realise how wide the scope of the problem was, thus I'm submitting this to you guys instead now, having begun to think it's time for me to not just have the following fix in my personal-only entries anymore:

```
@@||securitytrails.com/domain^
@@||securitytrails.com/app/api/v1/domain^
@@||logo.clearbit.com^$domain=securitytrails.com
```

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/98535333-32500880-2286-11eb-8bc8-7a7d6e2a8d56.png)
</details><br/>

* **Expected behaviour**: 

All pages load normally, and the site icons load correctly every time.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/98535434-6297a700-2286-11eb-822d-61c01e6db269.png)
</details><br/>

***Steps to reproduce the problem***:

1) Go to `https://securitytrails.com/domain/advert.vg.no/dns`
2) Most likely (but not guaranteed), the error page will show up.
3) If you don't receive the error page on initial load, click on one of the two IPv4 address buttons, and from there click on any of the domains starting with `advert.` or `advertising.`

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/98535796-fff2db00-2286-11eb-8759-bec81f6aae3d.png)

![image](https://user-images.githubusercontent.com/22780683/98535851-1731c880-2287-11eb-99d9-6a5c843e76a1.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | October 2020 Update
Browser:                               | Chrome 86.0.4240.183 x64
AdGuard version:                       | uBlock Origin 1.30.9b12 + AdGuard for Windows 7.5.2 + IDCAC 3.2.4
Filters enabled:                       | See screenshots above.
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | URL tracking parameter removal only
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
