### ISSUE TITLE
eBay Kleinanzeigen for Germany app - Ads - Android 

### ISSUE THREAD

**Issue by ypetruk** [AdguardTeam/AdguardFilters#6728]
***Description***:
* **Current behaviour**: 

Ads in the app eBay Kleinanzeigen for Germany 
https://play.google.com/store/apps/details?id=com.ebay.kleinanzeigen&hl=en

<details><summary>Screenshot:</summary>

![screenshot_20170908-150146](https://user-images.githubusercontent.com/28784344/30355373-bdc2ab44-983b-11e7-9b1c-bd9134153ac6.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | android
AdGuard version:                    | 2.9.136
Filters enabled:                    |  2, 3, 4, 14, 6, 11
Filtering quality (Android only):   | High-quality 
HTTPS filtering (Android only):     | On (Default) 
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1105236

**Comment by Alex-302** [comment]
It is broken on my side. Fixed, but ads are blocked on my end. Please ask for HAR file(don't upload it here)

**Comment by Alex-302** [comment]
@AdamWr please check on your device.

**Comment by AdamWr** [comment]
I can't reproduce these ads.
