### ISSUE TITLE
http://webclick.megalabs.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6729]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: This is where Megafon redirects you to when you're trying to access a site blocked by Russian authorities. The full link: http://webclick.megalabs.ru:9009/partner/webclick/16c4690d29362bf164ba7c2172782d4d

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30373357-b5577b30-9889-11e7-927d-1bd2e6bf3b13.png)

</details><br/>

***Steps to reproduce the problem***:

1. Connect to internet with Megafon network
2. Go to smth that is blocked, rutracker for instance
3. The dummy page contains ads 

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***:

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows NT 6.1.7601 Service Pack 1
Browser:                            | Yandex
AdGuard version:                    | Release
Filters enabled:                    | User, English, Russian, Spyware, Social media, Annoyances
AdGuard DNS:                        | None 
Stealth mode options (Windows only) | default
Helpdesk ID (if exists):            | 1076746

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
Do you need har, web requests log or anything else?

**Comment by Alex-302** [comment]
Yes, both files.

**Comment by evgeniy-ADG** [comment]
Прислали, см. в тикете.

**Comment by Alex-302** [comment]
На проверку:
```
webclick.megalabs.ru##body > section.intro
webclick.megalabs.ru##body > section.info
||mobilebanner.ru^$third-party
```

**Comment by evgeniy-ADG** [comment]
Передал.

**Comment by Alex-302** [comment]
Спроси о результате.

**Comment by evgeniy-ADG** [comment]
Вроде как помогло.

**Comment by evgeniy-ADG** [comment]
> Здравствуйте, Adguard.
> 
> Мегафон, вероятно, изменил алгоритм, сегодня перестала блокироваться реклама с предложением платного контента.
> высылаю har файл со смартфона. 
> 
> В журнале фильтрации на компьютере:
> /* SUMMARY REQUEST INFO */
> 
> Request URL: http://webclick.megalabs.ru:9009/partner/webclick/dd6a50f0078fc2546b63557c49611a15
> Remote Address: 83.149.14.51:9009
> 
> Если нажать обновить страницу, то уже другую мелодию предлагает
> 
> Request URL: http://webclick.megalabs.ru:9009/partner/webclick/dd6a50f0078fc2546b63557c49611a15
> Remote Address: 83.149.14.51:9009
> 
> Прошу Вас посмотреть и по-возможности прислать новые правила.

Новый HAR в тикете.

**Comment by Alex-302** [comment]
@evgeniy-ADG попроси сохранённую страницу(полностью). Из HAR не понятно что блокировать, уже не дают из чужой сети загрузить изображения.
