### ISSUE TITLE
http://blackhole.beeline.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6730]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: This is where Beeline Russia redirects you to when you're trying to access a site blocked by Russian authorities. The full link: http://blackhole.beeline.ru/?url=http%3A%2F%2Frutracker%2Eorg%2F&dstip=195%2E82%2E146%2E214

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30373602-8e2976b6-988a-11e7-92d3-8a88d37c7bfc.png)

</details><br/>

***Steps to reproduce the problem***:

1. Connect to internet with Beeline network
2. Go to smth that is blocked, rutracker for instance
3. The dummy page advertises Beeline's paid services

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***:

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows NT 6.1.7601 Service Pack 1, Android
Browser:                            | Yandex, Samsung Internet
AdGuard version:                    | Release
Filters enabled:                    | User, English, Russian, Spyware, Social media, Annoyances
AdGuard DNS:                        | None 
Stealth mode options (Windows only) | default
Helpdesk ID (if exists):            | 1076746

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I need HAR+log

**Comment by evgeniy-ADG** [comment]
Прислали, см. в тикете.

**Comment by Alex-302** [comment]
На пробу:
```
blackhole.beeline.ru##.wrap > div#root > a > img[role]
```
или 
```
||static.beeline.ru/upload/images/$domain=blackhole.beeline.ru
```

**Comment by evgeniy-ADG** [comment]
Передал.

**Comment by Alex-302** [comment]
@evgeniy-ADG 
есть ответ?

**Comment by evgeniy-ADG** [comment]
Вроде как помогло.

**Comment by Alex-302** [comment]
@evgeniy-ADG

**Comment by Alex-302** [comment]
@evgeniy-ADG
