### ISSUE TITLE
[NFSW] xmoviesforyou.com - Incorrect blocking

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6731]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
> Appears that the English filter keeps the videos from playing.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

***Steps to reproduce the problem***: 
[http://www.xmoviesforyou.com/2017/09/dirtymasseur-nicolette-shea-massage-mirage.html
](http://www.xmoviesforyou.com/2017/09/dirtymasseur-nicolette-shea-massage-mirage.html)

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:** 2, 3, 4, 14, 11, 12, 122, 215, 207, 204

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
AdGuard version:                    | 1.3.1.82
Helpdesk ID (if exists):            | 1627942

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Please check these rules:
```
@@||cdnjs.cloudflare.com/ajax/libs/$domain=xmoviesforyou.com
@@||dato.porn/assets/js/mobile-detection.js
@@||dato.porn/cdn-cgi/apps/head/*.js$domain=xmoviesforyou.com
@@||dato.porn/hls/*.m3u8
@@||dato.porn/js/jquery.cookie.js
@@||dato.porn/js/jquery.min.js
@@||dato.porn/js/pop.js
@@||dato.porn/js/xupload.js
@@||dato.porn/player7may/jw-logo-bar.js
@@||dato.porn/player7may/jwplayer.js
@@||easylist.club/ados.js
@@||fruithosted.net/dl/*.mp4
@@||oloadcdn.net/dl/*.mp4
@@||streamcherry.com/assets/js/license
@@||streamcherry.com/assets/js/script.*.js$domain=xmoviesforyou.com
@@||streamcherry.com/assets/js/video-js/
@@||streamcherry.com/googlead.js
@@||streamcherry.com/popunder2.js
@@||streamcherry.com/v/*~*/$domain=xmoviesforyou.com
||dato.porn/*.php?
||pebadu.com^
||602d76e204c032.com^
```

**Comment by Alex-302** [comment]
@AdamWr please check this also on your end.

**Comment by AdamWr** [comment]
@Alex-302 first video player does not work on my end.
Second and third video player works correctly.

**Comment by Alex-302** [comment]
1,2 works on my end, 3 - not:)
