### ISSUE TITLE
studio.youtube.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#67311]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: editor for credits has a visual bug.
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="466" alt="player1" src="https://user-images.githubusercontent.com/48647394/98607836-3c0b5780-22ea-11eb-87c7-ef3d35429b54.PNG">

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

<img width="417" alt="player 2" src="https://user-images.githubusercontent.com/48647394/98607846-3f064800-22ea-11eb-9c19-2fdcd75d0dff.PNG">

</details><br/>

***Steps to reproduce the problem***:

For people with a channel and a video: Open youtube studio --> select a Video --> try to create credits

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.20
Filters enabled:                       | default + Adguard Germany + Adguard Tracking Protection + Adguard Annoyances
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

possible fix: `studio.youtube.com#@#.ytp-ce-element`

**Comment by Alex-302** [comment]
Please provide more screenshots or a video. Cannot find "create credits"

**Comment by JobcenterTycoon** [comment]
Must be named Endcard in english

**Comment by Alex-302** [comment]
Please show on screenshot.

**Comment by JobcenterTycoon** [comment]
<details><summary>Steps</summary>

1.
![step 1](https://user-images.githubusercontent.com/48647394/98858174-74cd3d00-2460-11eb-869d-3beca24d16aa.PNG)
2.
![step2](https://user-images.githubusercontent.com/48647394/98858184-77c82d80-2460-11eb-9c75-cfb834326177.PNG)
3.
![step3](https://user-images.githubusercontent.com/48647394/98858192-7a2a8780-2460-11eb-9b43-112c74f6ce68.PNG)



</details><br/>

**Comment by Alex-302** [comment]
Thanks, fixed)
