### ISSUE TITLE
adservice.tohsoft.com

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#67329]
adservice.tohsoft.com is an ad server that the app "Voice Recorder" (com.media.bestrecorder.audiorecorder) connects to. Please add it to your lists.

Reported by 2576359.

**Comment by DandelionSprout** [comment]
On all AdGuard tools that I know of except AdGuard Home and AdGuard DNS, AdGuard Base Filter is presumably blocking it already with `/adservice.$domain=~adservice.io`

An AdGuard Home-specific fix would be `/adservice.` + `@@/adservice.io^`, which'd presumably have to be added to AdGuard DNS Filter. I have no first-hand knowledge if such a fix also works on AdGuard DNS.
