### ISSUE TITLE
chimica-online.it - Adleftover, cookie notice

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6732]
http://www.chimica-online.it/test/esercizi-tamponi.htm

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/30396335-f6d0e95a-98d1-11e7-8258-0f0f2d9107ec.png)

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPad
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.58 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.44 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.11 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.66 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.60 Enabled=YES
Annoyance 

Helpdesk ID:  1628299

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
