### ISSUE TITLE
howsolve.ru - Banners - Windows

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6733]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 
http://howsolve.ru/drugie-yazyki-i-texnologii/kakoj-po-vashemu-mneniyu-samyj-luchshij-optimizator-sistemy/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30408925-949529de-990a-11e7-8ed4-a65e74aba907.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system: | Windows
Browser: | Chrome
AdGuard version: | 6.1
Filters enabled: | 1 2 3 4 10 11 14
Helpdesk ID: | 1449704

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
