### ISSUE TITLE
[Turkish filter] eksisozluk.com

### ISSUE THREAD

**Issue by fenopa** [AdguardTeam/AdguardFilters#67360]
![image](https://user-images.githubusercontent.com/62562166/98715513-52bdb700-239b-11eb-980f-cd6f312f11a9.png)
![image](https://user-images.githubusercontent.com/62562166/98715569-66691d80-239b-11eb-90c4-0cb4d69b8ca6.png)

Hi, can we get rid of these "sponsorlu" ads please?

Thanks.

**Comment by Alex-302** [comment]
Hi
I don't see it
![image](https://user-images.githubusercontent.com/8361299/98848442-6714b900-245a-11eb-87cb-04541675b230.png)

**Comment by fenopa** [comment]
Hi, they removed that ad now, closing the issue, thanks for the response.
