### ISSUE TITLE
Пропущенная реклама в приложении 4pda

### ISSUE THREAD

**Issue by them1212** [AdguardTeam/AdguardFilters#67410]
![Screenshot_20201111-180707_4PDA](https://user-images.githubusercontent.com/38691051/98804977-81926680-2449-11eb-87e1-e680b97a5240.jpg)

**Comment by Sergey-Lyapin** [comment]
На скриншоте рекламу не вижу, в приложении вижу только нативную рекламу алиэкспресса, которую мы не блокируем согласно нашей политике. (и которую технически невозможно заблокировать, т.к. она вшита в приложение)
