### ISSUE TITLE
||bing.com/fd/ls/ on AdGuard Tracking Protection filter breaks Bing image search

### ISSUE THREAD

**Issue by jawz101** [AdguardTeam/AdguardFilters#67423]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
||bing.com/fd/ls/ on AdGuard Tracking Protection filter breaks Bing image search
* **Current behaviour**: 
go to bing.com and do an image search, click on an image to bring up the preview screen, after about 10 seconds the screen goes white.  On Firefox using the AdGuard filter within uBlock Origin.

[//]: # (Substitute this line with a description of the problem)

* **Expected behaviour**: 

Preview screen remains visible

https://user-images.githubusercontent.com/14151703/98830850-c8289680-2432-11eb-8f39-5067d38ff187.png

https://user-images.githubusercontent.com/14151703/98831046-f7d79e80-2432-11eb-8d41-7ae1881b41bf.png

***Steps to reproduce the problem***:

https://www.bing.com/images/search?q=apple&first=1&scenario=ImageBasicHover
click on any of the images w/ Firefox + uBlock Origin + AdGuard Tracking Protection list (I don't know if other setups would do the same but this is mine.
Wait about 10 seconds.  Screen blanks

https://www.bing.com/fd/ls/lsp.aspx blocked breaks the page

***System configuration***

**Filters:**

https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows/Linux
Operating system version (Android/iOS) | ? Windows 10, Ubuntu 20.10
Browser:                               | Firefox
AdGuard version:                       | n/a uBlock Origin
Filters enabled:                       | yes

**Comment by Yuki2718** [comment]
Can't reproduce but I remember https://github.com/easylist/easylist/issues/5898

**Comment by Alex-302** [comment]
Not reproduced in AdGuard or uBO in Firefox 82.
