### ISSUE TITLE
dhakatribune.com, winaero.com, androidheadlines.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdguardFilters#67433]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Social Media bar

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/98860136-69443b00-248d-11eb-8f1e-060169e59101.png)
![1](https://user-images.githubusercontent.com/29574622/98899781-84896780-24da-11eb-8db7-1b9a650eaee6.png)
![1](https://user-images.githubusercontent.com/29574622/98900853-d7fcb500-24dc-11eb-9aed-a24b149a9b24.png)

</details><br/>

* **Expected behaviour**: 

No social icons

***Steps to reproduce the problem***:

Visit: 
`https://www.dhakatribune.com/bangladesh/2020/06/20/ring-of-fire-solar-eclipse-how-and-when-to-watch-in-bangladesh`
`https://winaero.com/download-winaero-tweaker/`
`https://www.androidheadlines.com/2020/07/bluemail-app-removed-from-play-store-without-notice-from-google.html`

***System configuration***

**Filters:**

Adguard Base, Adguard Tracking Protection, Adguard Annoyances, Adguard Social Media

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 20H2
Browser:                               | Chromium Edge 86
AdGuard version:                       | 3.5.20

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Just links to blogs.

**Comment by Alex-302** [comment]
For user rules:
```
androidheadlines.com##.widget-ahsocial
winaero.com###custom_html-7
dhakatribune.com##.left-panel-social-icon
```

**Comment by Alex-302** [comment]
Blocked some annoyances and ad.
