### ISSUE TITLE
http://www.handelszeitung.ch/ - leftover

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6746]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

* **Current behaviour**: http://m.azonline.de/NRW/2980745-Prozesse-Steuererklaerung-verspaetet-abgegeben-Berater-verurteilt

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30414564-ea7726be-992c-11e7-99ed-503075e8c024.png)

![image](https://user-images.githubusercontent.com/15856304/30414569-eeefcf16-992c-11e7-9506-288dad8fb224.png)

</details><br/>

***System configuration***

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.30.47 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.42 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.23.9 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.18.20 Enabled=YES
- ID=6 Name="German filter" Version=1.0.36.61 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.64 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.60 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | 1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
