### ISSUE TITLE
https://m.donanimhaber.com/ - ads leftover

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6750]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://m.donanimhaber.com/haberler/iPhone-8-Turkce-Canli-Yayin--Lansmani-simultane-tercume-ile-Turkce-izle.htm

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

<details>

![image](https://user-images.githubusercontent.com/15856304/30421284-f19efe54-9944-11e7-82c8-aad17f045132.png)

</details><br/>

***System configuration***

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.30.55 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.44 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.23.11 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.18.25 Enabled=YES
- ID=13 Name="Turkish filter" Version=1.0.9.16 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.65 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.60 Enabled=YES
- ID=15 Name="Simplified domain names filter" Version=1.0.2.24 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS 10.3.3
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Filters enabled:                    | see above
Simplified filters (iOS only)       |0ff
AdGuard DNS:                        | Default 
Helpdesk ID (if exists):            | 1628137

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
