### ISSUE TITLE
https://lenta.ru/ - yandex direct

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6751]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://lenta.ru/ 

I cannot reproduce. We disabled all 3-d party filters, it didn't help.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30421497-9b021378-9945-11e7-99dd-b8ce2b8178eb.png)

</details><br/>

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Filters enabled:                    | English, Russian, Social, Spyware, Mobile, Safari, Useful ads (tried disabling, didn't help), RuAd list filters (tried turning them off, too)
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | 1625906

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is impossible to block ads here on iOS.
Try these rules:
```
@@||lenta.ru^$generichide
@@|http$domain=lenta.ru
```
maybe ads will be smaller.

**Comment by evgeniy-ADG** [comment]
передал

**Comment by evgeniy-ADG** [comment]
Говорят, стало хуже и появилось еще несколько рекламных блоков.

**Comment by Alex-302** [comment]
Тогда без вариантов.
У меня с этими правилами реклама не такая пёстрая, без картинок.
