### ISSUE TITLE
latino-serialo.tv пропуск рекламы

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#6752]
Реклама сбоку слева и на плеере секундомер...
http://latino-serialo.tv/brazilskie_seriali_online_rus/10442-sovershenno-bespodobnaya-1-200-seriya-na-russkom-yazyke.html

http://great-tv.ru/brazilskie/sovershenno-bespodobnaya-totalmente-demais еще тут при при выборе серии нужно постоянно нажимать "пропустить рекламу"

**Comment by Alex-302** [comment]
поправил
