### ISSUE TITLE
Ads in programs - Zynga

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardFilters#6754]
Does not block ads in apps on Samsung SM-T580, https filtering is enabled.
Logs attached.

<details><summary>Screenshot:</summary>

![screenshot_20170822-153710](https://user-images.githubusercontent.com/30834067/30460503-f28e8110-99bf-11e7-9195-74843ea72c57.png)
![screenshot_20170822-153721](https://user-images.githubusercontent.com/30834067/30460504-f2ab5c2c-99bf-11e7-8f7e-3f775448228b.png)

Operating system:                   | Android 7.0 (sdk=24)
AdGuard version:                    | 2.9.136
Filtering quality (Android only):   | High-quality 
HTTPS filtering (Android only):     | On 
Helpdesk ID (if exists):            | 1601075

**Comment by zebrum** [comment]
There is the instruction how to move cert. In some cases it's required on android 7 to filter ads in apps:
 [Enable+HTTPS+Filtering+on+Android+Nougat (1).pdf](https://github.com/AdguardTeam/AdguardFilters/files/1306390/Enable.HTTPS.Filtering.on.Android.Nougat.1.pdf)

**Comment by Alex-302** [comment]
@darkulish
