### ISSUE TITLE
Ads on Yandex.ru

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardFilters#6755]
Ads on https://tv.yandex.ru/213?grid=my

Screenshot
![2017-09-13_195228 1](https://user-images.githubusercontent.com/30834067/30462347-a69fe1fa-99cd-11e7-8e2e-8db056c2fc5d.png)

![2017-09-13_195316](https://user-images.githubusercontent.com/30834067/30462348-a6a0c91c-99cd-11e7-8e62-14115565f11b.png)

Operating system:                   |  Microsoft Windows NT 6.1.7601 Service Pack 1
Browser:                            | Mozilla Firefox ( last update)
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | 2 3 4 14 0 
Helpdesk ID (if exists):            | 1331755

**Comment by Alex-302** [comment]
Fixed for app and for next version for browser extension(2.7.2).
