### ISSUE TITLE
https://www.pornhub.com/signup - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6756]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://www.pornhub.com/signup

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30478816-47f18494-9a1b-11e7-8bda-15024e34cb94.png)

</details><br/>

***Steps to reproduce the problem***:

1. Go to https://www.pornhub.com
2. Try to register an account

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | 6.2 beta
Filters enabled:                    | Englisn, Russian, Spyware, Social media, Annoyances, Mobile
AdGuard DNS:                        | Default
Stealth mode options (Windows only) | off

**Comment by Alex-302** [comment]
Can't reproduce. Try to find a filter, which causes it, and make screenshot of blocked requests.

**Comment by Alex-302** [comment]
@AdamWr please check on your end.

**Comment by AdamWr** [comment]
@Alex-302 I can reproduce.
I think, this rule is a problem: `|https://$image,xmlhttprequest,domain=pornhub.com|redtube.com|redtube.com.br|tube8.com|tube8.es|tube8.fr|youporn.com|youporngay.com`
![image](https://user-images.githubusercontent.com/29142494/30480640-17981d62-9a1b-11e7-839b-c480c86fe98e.png)
It works if I add for example this rule:
`@@||pornhub.com/signup|$~third-party`

**Comment by Alex-302** [comment]
Ok. Could you register and check logout also?

**Comment by Alex-302** [comment]
forgot)

**Comment by AdamWr** [comment]
Added to English filter:
`@@||pornhub.com/signup`
