### ISSUE TITLE
Edge Browser view MSN

### ISSUE THREAD

**Issue by jdpg2** [AdguardTeam/AdguardFilters#6757]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:  Adguard appears to block all normal ads on the MSN.com website, but when they are blocked it appears Microsoft is injecting their own placeholder adds for their own products.  So far I have found no way of blocking them
* **Current behaviour**: MSN on Edge without Adguard you see normal vender ads.  MSN with Adguard you see only Mircosoft ads

[//]: # Adgaurd not blocking Microsoft ads in Edge Browser 

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31988280/30480546-42866c78-99e8-11e7-9c21-f424e3107670.png)

</details><br/>

* **Expected behaviour**: 

[//]: # No add should show

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

Access MSN.com and try to view any video content

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 Pro 15063.608
Browser:                            | Edge	40.15063.0.0
AdGuard version:                    |  6.2
Filters enabled:                    |  English, Easy, Easy Privacy, Anti Adblock Killler, Malware Domains
AdGuard mode (Android only):        | VPN / Proxy (manual/auto)
Filtering quality (Android only):   | High-quality / High-speed / Simplified
HTTPS filtering (Android only):     | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)       | On / Off
AdGuard DNS:                        | None / Default / Family Protection
Stealth mode options (Windows only) | ?
Helpdesk ID (if exists):            | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Please provide the direct URL and screenshot.

**Comment by AdamWr** [comment]
If I understand correctly you have problem with video ads?
If so, I added to English filter these rules, they should block these ads:
`||v.fwmrm.net/ad/g/1?$replace=/(tv\.freewheel\.SDK\._instanceQueue\['Context_[\s\S]*?'\][\s\S]*?\.requestComplete\(\{)[\s\S]*\}\);/\$1\}\);/,domain=msn.com,important`
`||msavideo-a.akamaihd.net/srcx300/*.mp4$domain=msn.com`
Please, check the result.
