### ISSUE TITLE
vodafone.com.au - The website is blocked 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6758]
http://www.vodafone.com.au/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/30496265-8602feac-9a57-11e7-807b-f3fafeb02e00.png)

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPhone
Platform: iOS
OS: 10.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.70 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.46 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.19 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.61 Enabled=YES

Helpdesk ID:   1629306

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by veronikasav** [comment]
Ticked ID: 1628150
[state.txt](https://github.com/AdguardTeam/AdguardFilters/files/1307418/state.txt)

**Comment by Alex-302** [comment]
Added to Spyware filter
```
@@||dpm.demdex.net/id$domain=vodafone.com.au
```
