### ISSUE TITLE
https://xhamster.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6760]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://xhamster.com/videos/fucking-some-girls-8250086
Unable to play videos, spinning wheel unless you whitelist the site

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30501828-8ed1a1c2-9a6c-11e7-9b66-170a28001008.png)

</details><br/>

***System configuration***

**Filters:**

Filters subscriptions:

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.30.70 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.46 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.23.19 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.18.35 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.67 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.61 Enabled=YES
- ID=122 Name="Fanboy's Annoyances" Version=1.0.75.57 Enabled=YES
- ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.5.7 Enabled=YES
- ID=207 Name="Adblock Warning Removal List" Version=1.0.87.52 Enabled=YES
- ID=204 Name="Peter Lowe's list" Version=1.0.3.41 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce.
Try to disable
ID=122 Name="Fanboy's Annoyances" Version=1.0.75.57 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.5.7 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.87.52 Enabled=YES
ID=204 Name="Peter Lowe's list" Version=1.0.3.41 Enabled=YES

**Comment by danidoedel** [comment]
I could reproduce it. Does not happen with every video though. Disabling English filter solved the issue...

**Comment by Alex-302** [comment]
@AdamWr

**Comment by AdamWr** [comment]
Fixed.

**Comment by LaxusiC** [comment]
I want to report pop ads aswell when click view the video

**Comment by AdamWr** [comment]
@LaxusiC on iOS?
If so, could you please check this rule:
`||etfyguytdr.com^`
The new tab will be opened, but content should be blocked.
At this moment I don't see any way to block new opened tab, because iOS doesn't support `JS` rules and `$important` modifier.
