### ISSUE TITLE
http://mediametrics.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6761]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: http://mediametrics.ru/rating/ru/online.html

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30502237-0800d3aa-9a6e-11e7-9394-3501e6f9a586.png)

</details><br/>

***System configuration***

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.30.65 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.44 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.23.14 Enabled=YES
- ID=1 Name="Russian filter" Version=1.0.56.75 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.61 Enabled=YES
- ID=101 Name="EasyList" Version=1.0.75.35 Enabled=YES
- ID=115 Name="RU AdList" Version=1.0.87.48 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduce.
Is DNS and/or simplified domains filter disabled?

**Comment by evgeniy-ADG** [comment]
Ничего такого нет. Повторется, см. рекординг: https://youtu.be/J-_rdxjJ_N0

**Comment by Alex-302** [comment]
А какой фильтр гасит?

**Comment by Alex-302** [comment]
Правило
```
||mediametrics.ru^$third-party
```
не блокирует загрузку самой страницы, только сторонние запросы к mediametrics.ru
