### ISSUE TITLE
www.reddit.com - Pop-up - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6762]
***Description***:
* **Current behaviour**: 

Pop-up at bottom of page remains, despite adding custom rule to try and block that element
https://www.reddit.com/r/ringdoorbell/

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30508452-2c8f55e8-9aa0-11e7-882c-3d5ced3502da.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | 10.3.3
AdGuard version:                    | 1.3.1.82
Filters enabled:                    | 0,2,3,14,11,101,118,207,211
Simplified filters (iOS only)       | Off
Helpdesk ID (if exists):            | 1607212

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is hidden on my device by
```
reddit.com##.NavFrame > .DualPartInterstitial
```
Try it.

**Comment by Alex-302** [comment]
@AdamWr please check on your device.

**Comment by AdamWr** [comment]
I don't see this pop-up.
