### ISSUE TITLE
Compilation error message on AdGuard for Safari

### ISSUE THREAD

**Issue by FaresKi** [AdguardTeam/AdguardFilters#67634]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Compilation error message on AdGuard for Safari***:
* **Not blocking everything it's supposed to**: 

Installed AdGuard for Safari, and went to see "content blockers", and noticed that "AdGuard General" was displaying a red error "Compilation error/failure")

<details><summary>Screenshot: <img width="1136" alt="image" src="https://user-images.githubusercontent.com/46092308/99158389-81f16280-26d2-11eb-977f-6858fc9462c3.png"> </summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

I suppose it's expected to be green. 

<details><summary>Screenshot: I don't have a "expected behavior" screenshot</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

1. Install AdGuard for Safari on App Store
2. Enable all features.

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | MacOS 
Operating system version (Android/iOS) | Big Sur 11.0
Browser:                               | Safari
AdGuard version:                       | 1.8.5
Filters enabled:                       |  General, Advanced Blocking, Custom, Privacy, Security, Social, Others
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None 
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[Settings if helpful](https://gist.github.com/FaresKi/db550ba8810983b04106aa752e5e13cc)

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardForSafari #418](https://github.com/AdguardTeam/AdGuardForSafari/issues/418) via [**ZenHub**](https://www.zenhub.com/)
