### ISSUE TITLE
zoneofgames.ru - Ads

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#6764]
<details><summary>Screenshot:</summary>

![zoneofgames](https://user-images.githubusercontent.com/17948007/30510369-19f585ee-9acb-11e7-96fd-362db8cc6ab5.jpg)
</details><br/>

 Два баннера: http://www.zoneofgames.ru/gamebase/file/604/

Скрытие первого: `zoneofgames.ru##table[width="100%"] + [align="center"]`
Скрытие второго: `zoneofgames.ru##table[width="368"] > tbody > tr:first-child`
___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard legacy v2.7.1
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Поправил.

**Comment by XX-J** [comment]
<details><summary>Screenshot:</summary>

![zoneofgames](https://user-images.githubusercontent.com/17948007/30514402-c147c432-9b1c-11e7-8847-ba8a0293f2d8.jpg)
</details><br/>

Ваши правки скрыли только часть второго баннера и не затронули первый.

___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard legacy v2.7.1
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Переделал.

**Comment by XX-J** [comment]
<details><summary>Screenshot:</summary>

![zoneofgames](https://user-images.githubusercontent.com/17948007/30515367-cd6da274-9b2e-11e7-98f1-5f260f56075f.jpg)
</details><br/>

Нуу, почти...

___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard legacy v2.7.1
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
По-моему можно оставить. Ссылки на обменники тоже - сторонние сайты, с обилием рекламы, их же не блокируем.

**Comment by XX-J** [comment]
Так реклама-ж, в явном виде...

**Comment by Alex-302** [comment]
Баннер с акциями на игры. Не трусы же рекламируют)

**Comment by XX-J** [comment]
Какая разница что рекламируют, если есть реклама, то её надо убрать. А для некоторых особо изощрённых фетишистов и реклама трусов будет в радость :)

**Comment by Alex-302** [comment]
Акция видать закончилась, баннер пропал.

**Comment by XX-J** [comment]
Комментарии с баннера сняли - он опять виден.

**Comment by Alex-302** [comment]
ок
