### ISSUE TITLE
otvet.mail.ru - Ad button

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#6765]
<details><summary>Screenshot:</summary>

![otvet mail ru](https://user-images.githubusercontent.com/17948007/30515486-2d5b1f34-9b31-11e7-8cbb-e00f44564e1f.jpg)
</details><br/>

Рекламная кнопка: https://otvet.mail.ru/question/26756216

Правило скрытия: `mail.ru##.js-banner`

___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard legacy v2.7.1
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Поправил.
