### ISSUE TITLE
uol.com.br - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6766]
***Site***: https://esporte.uol.com.br/f1/ultimas-noticias/2017/09/08/mclaren-estuda-aproveitar-novas-regras-para-fazer-motor-proprio-em-2021.htm
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30515633-3aacf64e-9b2c-11e7-959a-93eec89dc23c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
Spanish/Portuguese filter

**Comment by mapx-** [comment]
`@@||jsuol.com.br/*ad$script`

**Comment by AdamWr** [comment]
Fixed.
