### ISSUE TITLE
iprima.cz - Annoyance - Ad leftover - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6767]
***Site***: http://play.iprima.cz/modry-kod/modry-kod-36-prepadeni
***Description***: Cookie notice at the top. Ad leftover above nav. Ads before video.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30515679-dc9a4ace-9b2c-11e7-9604-7ca1f6db47c0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
