### ISSUE TITLE
ads in the GG application for windows

### ISSUE THREAD

**Issue by gzenio22** [AdguardTeam/AdguardFilters#67681]
There are ads in the GG application on windows. I leave screenshots below

![Screenshot_1](https://user-images.githubusercontent.com/21177361/99190061-ba418100-2764-11eb-95a4-35431a753970.png)
![Screenshot_2](https://user-images.githubusercontent.com/21177361/99190065-c0376200-2764-11eb-9328-847aa884fd9c.png)

**Comment by krystian3w** [comment]
`adsads` - remove one `ads` from title 😉.

**Comment by gzenio22** [comment]
done sorry

**Comment by AdamWr** [comment]
@gzenio22 Próbowałeś dodać aplikację GG do filtrowanych aplikacji w ustawieniach AdGuarda?
AdGuard -> Ustawienia -> Sieć - Lista filtrowanych aplikacji, a potem przycisk `+` (tak jak na obrazkach poniżej).

<details><summary>Obrazki</summary>

![image](https://user-images.githubusercontent.com/29142494/99268611-add12d00-2825-11eb-975f-a7371425209f.png)

![image](https://user-images.githubusercontent.com/29142494/99268692-cc372880-2825-11eb-8391-011135b1b117.png)

</details>

**Comment by gzenio22** [comment]
Dziękuje za odpowiedź po polsku szczerze nie nie probowalem nawet nie dokopalem sie do tej opcji mialem 3 dniowego triala akurat dzis rano mi sie skonczyl :/ na swieta planuje kupic klucz na stałe

**Comment by AdamWr** [comment]
>Dziękuje za odpowiedź po polsku szczerze nie nie probowalem nawet nie dokopalem sie do tej opcji mialem 3 dniowego triala akurat dzis rano mi sie skonczyl :/ na swieta planuje kupic klucz na stałe

Rozumiem :)

Odnośnie reklam w GG.
Z tego co widzę, to po dodaniu aplikacji do filtrowania konieczne jest wyłączenie filtrowania HTTPS (tak jak na obrazku poniżej).
<details><summary>Obrazek</summary>

![image](https://user-images.githubusercontent.com/29142494/99289994-04e2fc00-283e-11eb-9e5a-fd36b756b46e.png)

</details>

Reklamy powinny być zablokowane, ale będą widoczne pozostałości po reklamach, których niestety w przypadku aplikacji nie da się zablokować.
<details><summary>Obrazek</summary>

![image](https://user-images.githubusercontent.com/29142494/99290037-13c9ae80-283e-11eb-95e8-7efdc17e759f.png)

</details>
