### ISSUE TITLE
Visible GDPR in the Bittorent application for Windows

### ISSUE THREAD

**Issue by bug-rules** [AdguardTeam/AdguardFilters#67682]
***Description***:
* **Current behaviour**:  Cookie-GRPR policy in bittorrent client is no accepted or blocked by network rule.

App can be downloaded from:

```
https://www.bittorrent.com/ru/products/win/bittorrent-classic-free/
```

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/66819865/99190517-42288a80-2767-11eb-9155-bc300737596a.png)
</details><br/>

* **Expected behaviour**: AdGuard 7.5 for Windows should hide GDRP pop-up. [](https://github.com/AdguardTeam/AdguardFilters/issues/62127)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/66819865/99190700-705a9a00-2768-11eb-96d6-5ea220bfd3f3.png)
</details><br/>

***Steps to reproduce the problem***:

1. install bittorrent app on Windows
2. open installed app
3. in UE should be loaded pop-up with cookies/GDPR policy.

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 Pro
Operating system version (Android/iOS) | 20H2
Browser:                               | Bittorrent Client App
AdGuard version:                       | 7.5
Filters enabled:                       | AdGuard Base,<br> AdGuard Tracking Protection,<br> AdGuard Annoyance
AdGuard mode (Android only):           | --
Filtering quality (Android only):      | --
HTTPS filtering (Android only):        | --
Simplified filters (iOS only)          | --
AdGuard DNS:                           |  None 
Stealth mode options (Windows only)    | No
Helpdesk ID (if exists):               | No

**Comment by Alex-302** [comment]
App is not a site, and cannot be filtered as site.
