### ISSUE TITLE
moat.com - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6770]
***Site***: https://moat.com/advertiser/nvidia?utm_source=try-these
***Description***: Search does not work with AdGuard enabled.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30515760-2d534bea-9b2e-11e7-8deb-c42c38fa30a8.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
