### ISSUE TITLE
observalgerie.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6771]
***Site***: https://observalgerie.com/actualite-algerie/sport/jsk-dos-au-mur-hannachi-dans-sa-derniere-tentative-video/
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30515771-6ed31730-9b2e-11e7-8117-d2c0aae42f1d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
French filter

**Comment by mapx-** [comment]
`observalgerie.com#@##adsense`

**Comment by AdamWr** [comment]
Fixed.
