### ISSUE TITLE
desatcabletntsof.blogspot.de - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6773]
***Site***: https://desatcabletntsof.blogspot.de/2017/09/itv-fight-updates.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed:+Aklsoftk-SitesDeMiseJourDesDmodulateurs+(aklsof+Television+news)
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30515799-e016a966-9b2e-11e7-9714-ec65218f5b6f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
French filter

**Comment by AdamWr** [comment]
Fixed.
