### ISSUE TITLE
videa.hu anti adblock

### ISSUE THREAD

**Issue by scripthunter7** [AdguardTeam/AdguardFilters#67741]
Hello!

videa.hu blocks video player, when adblock is enabled.

Screenshot:
![image](https://user-images.githubusercontent.com/6667211/99184731-5e1b3480-2745-11eb-92f1-631f132ad480.png)

Example link: 
[https://videa.hu/videok/film-animacio/a-halal-5o-oraja-1965..mp4-JlWoDETXbJ69qkl5](https://videa.hu/videok/film-animacio/a-halal-5o-oraja-1965..mp4-JlWoDETXbJ69qkl5)

Workaround:
- In the page source, search for "detect adblock" (it seems blocking this inline script is not enough)
- In [VideaPlayerClasses.min.js](https://videa.hu/static/uis/videojs_player/js/VideaPlayerClasses.min.js?_rc=2020111201) search for VideaPlayerAdblockPanel or adBlockDetected.

Reference:
https://github.com/hufilter/hufilter/issues/209

Thank you in the advance!

**Comment by krystian3w** [comment]
For my works:
```css
videa.hu#%#//scriptlet("abort-current-inline-script", "window.addEventListener", "ad_test")
```

So remove *by HTML filtering) or abort *inline-js* is **enough**.

**Comment by AdamWr** [comment]
Hi,

Fixed, update should be available in 1-2 hours.
