### ISSUE TITLE
kisscartoon.es - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6775]
***Site***: https://kisscartoon.es/Cartoon/HarmonQuest-Season-2/Episode-002-Demon-Realm-Devilry?id=76232
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30515819-59d78c8e-9b2f-11e7-81e0-72ef3a4ae10b.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
Spanish/Portuguese filter

**Comment by AdamWr** [comment]
Fixed.
