### ISSUE TITLE
||kappacdn.net^$third-party

### ISSUE THREAD

**Issue by clavelc** [AdguardTeam/AdguardFilters#67776]
Hi,
`||kappacdn.net^$third-party `
blocks [Air France site](https://www.airfranceklm.com/fr/groupe/gouvernance/comite-executif)

**Comment by krystian3w** [comment]
@smed79 a little breakage - images gone.

**Comment by smed79** [comment]
No images blocked for me https://i.ibb.co/Zmz56ct/kappacdn-net.png

Please help me with an ABP issue report or screenshots with urls of the blocked requests

**Comment by llacb47** [comment]
@smed79 cname issue, test with ubo

**Comment by clavelc** [comment]
> @smed79 CNAME issue, test with ubo

Yes, same here;

**Comment by smed79** [comment]
Removed https://github.com/easylist/listefr/commit/95fee6122ccc82398ac7a6c6a5381ac97d62cc75

Thank you.
