### ISSUE TITLE
kakprosto.ru - Banners - Windows

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6781]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

http://radikal.ru/lfp/i013.radikal.ru/1709/62/4a3972c1f65a.png%20%D0%A1%D1%81%D1%8B%D0%BB%D0%BA%D0%B0%20%D0%B4%D0%BB%D1%8F/htm

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30517084-d803f6de-9b5b-11e7-8575-3c3cb93c3f0b.png)

</details><br/>

Information | Value
-- | --
Operating system: | Windows
Browser: | Chrome
AdGuard version: | 6.1
Filters enabled: | 1 2 3 4 10 11 14
Helpdesk ID: | 1449704

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It was fixed today.
