### ISSUE TITLE
cuturlink.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6786]
***Site***: http://cuturlink.com/SX2Fz
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30519335-1faf8a9c-9b94-11e7-8224-b13c912a36d2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by mapx-** [comment]
```
@@||cuturlink.com/js/ads.js
||cloudfront.net/$script,domain=cuturlink.com
```

**Comment by AdamWr** [comment]
Fixed.
