### ISSUE TITLE
image.google / Google Image

### ISSUE THREAD

**Issue by FinderID** [AdguardTeam/AdguardFilters#67869]
https://www.google.com/search?q=fb&sxsrf=ALeKk01-8dPKlYKVAngZqDqDsiJ4xiTSfA:1605634581645&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiz5IL3jortAhUHb30KHVMaAm8Q_AUoAXoECAcQAw&biw=1600&bih=757#imgrc=nAOBPDum0sb1XM

problem : 
can't scroll down for other image at preview mode
![1](https://user-images.githubusercontent.com/57831066/99426373-f4ff1100-293e-11eb-9691-c2302639de14.png)

**Comment by BlazDT** [comment]
Please post required information as outlined in template.
