### ISSUE TITLE
lavozdealmeria.es - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6788]
***Site***: http://www.lavozdealmeria.es/ -> http://www.lavozdealmeria.es/aviso.php
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30519351-9952678e-9b94-11e7-9cd9-5c411b5d9342.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
Spanish/Portuguese filter

**Comment by mapx-** [comment]
`||lavozdealmeria.es/js/addblock.js`

**Comment by AdamWr** [comment]
Fixed.
