### ISSUE TITLE
mycinema.pro - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6790]
***Site***: https://www.mycinema.pro/index.html
***Description***: Ad leftover. Cookie notice at the top.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30519592-a2fe47b6-9b9a-11e7-90a8-59350983848b.png)

![image](https://user-images.githubusercontent.com/10995998/30519595-ad4faeee-9b9a-11e7-8dd6-3059598d1577.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
This website doesn't work on my end.

**Comment by danidoedel** [comment]
@AdamWr Not sure if that will help, but here is the HAR:


[www.mycinema.pro.zip](https://github.com/AdguardTeam/AdguardFilters/files/1369153/www.mycinema.pro.zip)

If you need anything else, just tell me ;)

**Comment by AdamWr** [comment]
Thank you for HAR file.
I also checked it with US IP and I can open this website.

I can't reproduce cookie notice even with your HAR. Do you still see this?

For ad leftovers added these rules:
`mycinema.pro##[class][-ext-has=">ins.adsbygoogle"]`
`mycinema.pro##div[class]:contains(Advertisement):not([-ext-has="> *"])`

**Comment by danidoedel** [comment]
Yeah cookie notice is still there, but somehow not reproduceable in incognito mode (cleared cache etc.)

That's the element in question, not sure if that helps though:

```html
<div class="Cjz np"><span class="JtOX np">Cookies help us deliver our services. By using our services, you agree to our use of cookies.</span><a class="SB2p np" href="https://www.mycinema.pro/privacy.html" target="_blank">Learn more</a>
	<input class="H9R5 CQ i np" type="button" value="Got it">
</div>
```

**Comment by AdamWr** [comment]
Thank you for answer.
Could you please check this rule:
`mycinema.pro##.JtOX`

**Comment by danidoedel** [comment]
That removes the text only. `mycinema.pro##.Cjz` removes the whole banner.

**Comment by AdamWr** [comment]
Oh, you are right :)
If you go here - https://www.mycinema.pro/features.html is it still hidden or maybe there isn't cookie notice here?
I mean this rule `mycinema.pro##.Cjz`

**Comment by danidoedel** [comment]
There is no cookie notice, even without that rule.

**Comment by AdamWr** [comment]
Ok, thank you for help.
Added.

**Comment by danidoedel** [comment]
Well it seems that div classes change from time to time...I don't think there is any reliable method to block this stuff? Cookie notice now is:

```html
<div class="RN H3J">
	<span class="QIOG H3J">Cookies help us deliver our services. By using our services, you agree to our use of cookies.</span>
	<a class="MCC H3J" href="https://www.mycinema.pro/privacy.html" target="_blank">Learn more</a>
	<input class="lH C fkXc H3J" type="button" value="Got it">
</div>
```

**Comment by AdamWr** [comment]
Could you please check this rule:
`mycinema.pro##[class][-ext-has=">span:contains(Cookies help us deliver our services. By using our services, you agree to our use of cookies.)"]`
If it won't work or it will hide to much, please save this website as html and upload it here.

**Comment by danidoedel** [comment]
Yep that rule works and it doesn't look like it hides anything else ;)

**Comment by AdamWr** [comment]
Ok, added.
Thank you for checking it :)
