### ISSUE TITLE
brigitte.de - Annoyance - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6791]
***Site***: http://www.brigitte.de/liebe/beziehung/schwiegermutter--das-solltest-du-niemals-zu-ihr-sagen-10961156.html
***Description***: Adblock detection. Newsletter banner.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30519710-55ffc5a4-9b9d-11e7-9559-f65cc19ce0f9.png)

Newsletter banners on the front page (http://www.brigitte.de/):

![image](https://user-images.githubusercontent.com/10995998/30519730-b60a2e9e-9b9d-11e7-9433-5cadafcb3fbf.png)

![image](https://user-images.githubusercontent.com/10995998/30519733-c673c902-9b9d-11e7-9f15-ee5638532e81.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
