### ISSUE TITLE
AdGuard DNS blocks Lord of the Rings Online updates

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#67915]
Reported by 3024574:

Использую Adguard DNS через роутер Keenetic KN1810 Ultra (политика No Ads). При включенном Adguard DNS не работает обновление Lord of the Rings Online через их лаунчер (Используется некий сервис Akami или что-то такое). При этом лаунчер подключается к серверам нормально и игра также нормально запускается, если нет обновлений. Проблема проявляется только при попытке обновления игры. В логе лаунчера следующее:

```
2020.11.15 16:20:55[W] Data Center URL:   QUrl( "http://moria.gls.lotro.com/GLS.DataCenterServer/Service.asmx" )  
 2020.11.15 16:21:00[C] RawDownloadFlow::AdmitFailure >  "Network request failed, communication error [1]!"
2020.11.15 16:21:00[C] Patcher::OnRawDownloadFailure>  "Network request failed, communication error [1]!"
2020.11.15 16:21:02[C] RawDownloadFlow::AdmitFailure >  "Network request failed, reason [Connection refused][1]!"
2020.11.15 16:21:02[C] Patcher::OnRawDownloadFailure>  "Network request failed, reason [Connection refused][1]!"
2020.11.15 16:21:06[W] PatchFlow::OnPatchProductResult - failure!
2020.11.15 16:21:06[C]  
2020.11.15 16:21:06[C] PatchFlow::AdmitFailure
2020.11.15 16:21:06[C] PatchFlow::AdmitFailure  [ "Unknown error: 0xffffffff80043007" ]
```
К сожалению не совсем понятно, к какому серверу идет обращение и что блокируется, поскольку упомянутый в логе  http://moria.gls.lotro.com/GLS.DataCenterServer/Service.asmx остается доступен, если открыть его через браузер.

**Comment by Alex-302** [comment]
@Eugene-Savenko если настроить DNS в системе, а не в роутере, проблема остаётся?

**Comment by Eugene-Savenko** [comment]
21 ноября писали, пока не отвечают.
