### ISSUE TITLE
rimondo.com - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6793]
***Site***: https://de.rimondo.com/
***Description***: Ads.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30519772-6cae821c-9b9e-11e7-84e8-524ce8d4e1c4.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
