### ISSUE TITLE
Ads in Myfitness, Textra

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardFilters#6794]
Ads in Myfitness and Textra using mobile data

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![screenshot_20170830-145002](https://user-images.githubusercontent.com/30834067/30521094-22b4d99e-9bc2-11e7-87a9-cbb1a0fd097a.png)

![screenshot_20170912-094707](https://user-images.githubusercontent.com/30834067/30521101-448664de-9bc2-11e7-9dfb-db8f0a84b473.jpg)

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Android 7.0 (sdk=24)
AdGuard version:                    | 2.9.136
Device:                                 | samsung SM-G955F
Filters enabled:                    | 2,3,4,11
Filtering quality (Android only):   |Full
HTTPS filtering (Android only):     | On
Simplified filters (iOS only)       | On / Off
Helpdesk ID (if exists):            | 1608209

**Comment by Alex-302** [comment]
Textra is excluded from filtering(MMS are broken). User can enable filtering.
Myfitness  - I need download link.
