### ISSUE TITLE
http://hdrezka.ag - missed ads

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardFilters#6795]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
Реклама на сайте, значок помощника пропадает при наведении на него курсора.
http://hdrezka.ag/films/best/horror/2016/

![hdrezka_1](https://user-images.githubusercontent.com/30834067/30521463-9a3ac964-9bc8-11e7-9d97-05bc0a558db9.jpg)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Microsoft Windows NT 6.1.7601 Service Pack 1
Browser:                            | Opera
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | Russian, English, Dutch, French, User filter
Helpdesk ID (if exists):            | 1017382

**Comment by Alex-302** [comment]
Этот сайт и не должен блокироваться, вредоносного на нём нет.
Новая версия ромощьника пропадать не будет. Если хочет, юзер может обновиться до беты 6,2.

**Comment by evgeniy-ADG** [comment]
@darkulish говорит о рекламе, насколько я понял. там справа виднеется. @darkulish добавляй ссылки и офорляй нормально, пожалуйста.

**Comment by Alex-302** [comment]
Реклама не повторяется с версией 6.1
Может в пользовательском фильтре есть исключения?

**Comment by evgeniy-ADG** [comment]
Если бы сайт исключили, то с версией 6.1 и помощник пропал бы. Там адблок плюч или что-то такое краснеет в расширениях, проверим без него.

**Comment by Alex-302** [comment]
Исключить можно по разному, например блокировку адресов.
