### ISSUE TITLE
http://www.tutuapp.vip/ios/?udid=00008020-001335891106002E&device_name=&phone_model=iPhone%20XS

### ISSUE THREAD

**Issue by alannzi** [AdguardTeam/AdguardFilters#67956]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

**Comment by BlazDT** [comment]
What's the issue? Please provide required information.
