### ISSUE TITLE
https://tubitv.com/ - redirects to app store

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6796]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://tubitv.com/
Redirects to the app store when trying to play a video in Safari. Is it smth that can be blocked by AdGuard? Whitelisting doesn't help (first I thought it's sort of an incorrect blocking).

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30521630-298c176a-9bcb-11e7-9da4-27d9d02a79d8.png)

</details><br/>

* **Expected behaviour**: 

It plays in a browser, works in Chrome:

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30521640-6399ee8c-9bcb-11e7-89c4-2c80e687a47d.png)

</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

**Filters:**

- ID=2 Name="English filter" Version=1.1.30.64 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.44 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.23.14 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.60 Enabled=YES
- ID=15 Name="Simplified domain names filter" Version=1.0.2.25 Enabled=YES
- ID=207 Name="Adblock Warning Removal List" Version=1.0.87.46 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | 1628604

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced, but it seems Safari parsed some tag and show this popup(like mobile app banners).

**Comment by evgeniy-ADG** [comment]
It's easily reproducible at my end, so you're able to play videos in Safari w/o it asking you to install the app?

**Comment by Alex-302** [comment]
I don't have an account. Is it required?

**Comment by evgeniy-ADG** [comment]
yes, you can register with facebook, it's free and no email confirmation required

**Comment by Alex-302** [comment]
It is impossible to remove this popup.

---

Fixed adblock detection.
