### ISSUE TITLE
feedly.com Ads not blocked

### ISSUE THREAD

**Issue by HollywoodPalmz** [AdguardTeam/AdguardFilters#67967]
For example:

https://feedly.com/i/subscription/feed%2Fhttp%3A%2F%2Fwww.laist.com%2Findex.rdf

Has an ad in the third column, at the top of the feed

**Comment by BlazDT** [comment]
Please post all required information as outlined in template.

**Comment by HollywoodPalmz** [comment]
![Screen Shot 2020-11-18 at 17 58 59](https://user-images.githubusercontent.com/43592533/99611166-06d8c680-29c8-11eb-881f-b825b7dd97cd.png)

**Comment by HollywoodPalmz** [comment]
Sorry - not sure what template you are speaking of. Please see attached screenshot.

**Comment by BlazDT** [comment]
When you created the issue, the required template was shown, you can see it here again:

https://github.com/AdguardTeam/AdguardFilters/issues/new?template=Ad_report.md

**Comment by HollywoodPalmz** [comment]
Description:

    Current behaviour:

//: # Feedly.com shows ad on top row, third column
Screenshot:

    Expected behaviour:

//: ad should not be shown
Screenshot:

Steps to reproduce the problem:

//: Log into Feedly and authenticate credentials.

System configuration


Information | Value
-- | --
Operating system: | 11.0.1
Operating system version (Android/iOS) | ?
Browser: | Safari Version 14.0.1 (16610.2.11.51.8)
AdGuard version: | Version 1.8.6
Filters enabled: | Yes
AdGuard mode (Android only): | VPN / Proxy (manual/auto)
Filtering quality (Android only): | High-quality / High-speed / Simplified
HTTPS filtering (Android only): | On (Default/Blacklist mode) / Off
Simplified filters (iOS only) | On / **Off**
AdGuard DNS: | None / Default / Family Protection
Stealth mode options (Windows only) | ?
Helpdesk ID (if exists): | 67967

**Comment by BlazDT** [comment]
Created account and new feed, added some sources and not reproduced. Please provide more information. In the box "Filters enabled" you should put the names of the enabled filters.

**Comment by Alex-302** [comment]
@BlazDT
