### ISSUE TITLE
famitsu.com (N: uBlock Origin) (N: AdGuard for Windows) (T: Ads)

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#67965]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Placeholders on top. I propose `##.banner-top-header` for the frontpage, and `##.banner-article-video` for article-pages.

Additionally there is a mid-article placeholder on article-pages. I propose `famitsu.com##.article-body__contents-pr-primary`

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/99602859-7ec3e280-2a02-11eb-9669-92657d4d0205.png)
—————————————————
![image](https://user-images.githubusercontent.com/22780683/99603273-407af300-2a03-11eb-955b-990e07bfb63d.png)
</details><br/>

* **Expected behaviour**: 

No placeholders on top.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/99602974-b7fc5280-2a02-11eb-9e3b-4fecf9dab74a.png)
—————————————————
![image](https://user-images.githubusercontent.com/22780683/99603149-0578bf80-2a03-11eb-8084-1b2ac259b8ba.png)

</details><br/>

***Steps to reproduce the problem***:

1) Go to `https://www.famitsu.com/` and `https://www.famitsu.com/news/202011/19209372.html`

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/99603317-54265980-2a03-11eb-851f-5b516f96ccda.png)
![image](https://user-images.githubusercontent.com/22780683/99603490-b0897900-2a03-11eb-8e38-de321da91f9c.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | October 2020 Update
Browser:                               | Chrome x64
AdGuard version:                       | uBO 1.31.1b0 + AdGuard for Windows 7.5.2 + IDCAC 3.2.4
Filters enabled:                       | See screenshots above.
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Yuki2718** [comment]
I see the placeholder in the second SS `##.article-body__contents-pr-primary` but not the first one `##.banner-top-header` or `##.banner-article-video`. However, `famitsu.com##.banner-top-header` is in my personal list so they may be conditional. Can you reproduce them on AdGuard Extension with stock lists too?

**Comment by DandelionSprout** [comment]
Now I can't reproduce them with any kind of setup or extension either. Those two placeholders have completely vanished overnight.

Thankfully I did at least find two new and different placeholders:
```
##.banner-lg-rect-haf-page
##.banner-footer-rect-container
```
