### ISSUE TITLE
Add "Fanboy's Cookiemonster List" to the list of known subscriptions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#6797]
URL: https://www.fanboy.co.nz/fanboy-cookiemonster.txt
Title: `Fanboy's Cookiemonster List`

Description: 
```
This will remove cookie and privacy warnings (List already included in Annoyances List, don't add list if you're using the Annoyances List)
```

Tags:
`purpose:cookies`
`reference:122` (new tag, references Fanboy's Annoyances List).

We should also add tag `reference:122` to Fanboy's Social List

**Comment by Alex-302** [comment]
@mmigi added to Filters directory.

**Comment by mmigi** [comment]
I've added the Fanboy's _Cookiemonster List_ filter (now it is available for applications) and new  `reference:122` tag.
