### ISSUE TITLE
Do not block `generate_204` pages

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#6798]
There are two rules blocking it:

https://github.com/AdguardTeam/AdguardFilters/blob/55cede31c1dba5d157e3690900bf5f7eb1b739ca/ExperimentalFilter/sections/Spyware/filter.txt#L4
https://github.com/AdguardTeam/AdguardFilters/blob/8ff6368b158135fa608c51b6f7a6ddc9d7e7c592/SpywareFilter/sections/tracking_servers.txt#L1303

This is not a tracker, but an URL used to check connectivity. Blocking it may cause issues:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1440

**Comment by AdamWr** [comment]
Removed.
