### ISSUE TITLE
https://www.firstone.tv/ - counter

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6801]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://www.firstone.tv/Live/United-States-(USA)/AMC-25
Is it possible to block the counter so the video starts playing right when you click play?

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30522548-8c349874-9bda-11e7-8cb6-2ca9aff68d3b.png)

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | ?Chrome
AdGuard version:                    | 6.2 beta
Filters enabled:                    | English, Russian, Social, Annoyances, Spyware
AdGuard DNS:                        | None
Stealth mode options (Windows only) | Off
Helpdesk ID (if exists):            | 1626067

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
