### ISSUE TITLE
grammarly.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#68030]
[https://www.grammarly.com/blog/until-till-til/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.grammarly.com/blog/until-till-til/)

Overlay annoyance. There are already other download buttons on the page:

![overlay](https://user-images.githubusercontent.com/35470489/99725812-66040d00-2a94-11eb-8e6f-5458f23a68a6.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
Please check:
```
grammarly.com#$#div[class="_1X8pZ-src-shared-components-popup--popup-overlay"] { display: none !important; }
grammarly.com#$#body { overflow: auto !important; }
```

**Comment by adranger** [comment]
Works for me.

**Comment by Alex-302** [comment]
Added
