### ISSUE TITLE
com.teamsnap.teamsnap

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#68159]
***Description***:
* **Current behaviour**: 

Breaks chat functionality.

<details><summary>Screen recording:</summary>

See helpdesk ticket 1438320.
</details><br/>

* **Expected behaviour**: 

Shouldn't break chats when protection is enabled.

***Steps to reproduce the problem***:

1. Install the app, enable protection
2. Try to chat with someone

***System configuration***

**Filters:**

**DEVICE IS ROOTED**

"Spam404", "AdGuard Tracking Protection filter", "Online Malicious URL Blocklist", "AdGuard Social Media filter", "AdGuard Base filter", "AdGuard Mobile Ads filter", "EasyList Cookie List", "I don't care about cookies", "AdGuard Annoyances filter", "NoCoin Filter List"

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 10
Browser:                               | n/a
AdGuard version:                       | 3.5.1
Filters enabled:                       | "Spam404", "AdGuard Tracking Protection filter", "Online Malicious URL Blocklist", "AdGuard Social Media filter", "AdGuard Base filter", "AdGuard Mobile Ads filter", "EasyList Cookie List", "I don't care about cookies", "AdGuard Annoyances filter", "NoCoin Filter List"
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | Default, DoH
Helpdesk ID (if exists):               | 1438320

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@akmLaVx I don't see chat button(see reply in our support chat). Need more details. And please ask to check with disabled filters groups.
