### ISSUE TITLE
https://www.purepc.pl/ - Anti Adblock Script

### ISSUE THREAD

**Issue by Camis** [AdguardTeam/AdguardFilters#6816]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

Anti Adblock on https://www.purepc.pl

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/YEuA3OI.png)
</details><br/>

**Comment by mapx-** [comment]
`@@||purepc.pl^$generichide`

**Comment by Camis** [comment]
@mapx- 

Not working, still i have Anti Adblock:


![image](https://i.imgur.com/QBcnJpb.png)


Link: https://www.purepc.pl/procesory/procesory_intel_kaby_lake_nie_zadzialaja_z_plytami_z370

**Comment by Camis** [comment]
@mapx- 

Not working, still i have blocked page:

![image](https://i.imgur.com/gE8xOHx.png)


![image](https://i.imgur.com/PwdkdFe.png)

**Comment by AdamWr** [comment]
Could you please tell me what version of Adguard you have and which filter lists do you use?/Mógłbyś napisać z jakiej wersji Adguarda korzystasz oraz które filtry masz włączone?

**Comment by Camis** [comment]
Adguard v: 6.2.390.2018

Filters:

![image](https://i.imgur.com/M1B0lmj.png)

**Comment by AdamWr** [comment]
@Camis jeśli wyłączysz listę `Adblock Polska`, która swoją drogą jest stara i nieaktualizowana, to działa?
Ewentualnie jeśli chcesz nadal korzystać z tej listy, to sprawdź proszę tę regułę:
`purepc.pl#@#[class$="reklama"]`
