### ISSUE TITLE
razlozhi.ru - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6817]
https://razlozhi.ru/spider-millennium

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/30548425-c69e170e-9c9a-11e7-9e6c-18e28e2d1b62.png)

![image](https://user-images.githubusercontent.com/27292111/30548514-0926181a-9c9b-11e7-9c32-57e24271a333.png)

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | 6.1
Filters enabled:                    | 1 2 3 14
Helpdesk ID (if exists):            | 1084030

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
> https://razlozhi.ru

fixed

**Comment by darkulish** [comment]
У юзера снова повторилась проблема. 
![default](https://user-images.githubusercontent.com/30834067/31054732-18642138-a6c2-11e7-90a3-a6797caa1e63.png)

**Comment by Alex-302** [comment]
Не повторяется.
Убрал пустой блок, в котором у юзера реклама
```
razlozhi.ru##div[class="_n_0 "] > div[class="_1w _10 "]
```
