### ISSUE TITLE
Майнер на онлайн кинотеатре.

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#6818]
https://films-now.ru/
https://serials-now.ru/
При входе на эти сайты, идет ужасная нагрузка компьютера... судя по всему какой-то майнер встроили что ли... идет отсюда https://coin-hive.com/lib/cryptonight.wasm

Заблокировал ||coin-hive.com^*
Кстати подскажите как блокировать ***.wasm** на всех сайтах? Пробовал `||*/*.wasm` но почему-то не сработало.

**Comment by Alex-302** [comment]
Я бы принципиально перестал посещать эти сайты. Никаких сообщений они не показывают, и с выключенным блокировщиком тоже майнят.

> ||*/*.wasm

`/cryptonight.wasm`

**Comment by Alex-302** [comment]
Можешь ещё такое правило добавить:
```
#%#var _jobThread; window.CoinHive = Object.defineProperty({}, 'JobThread', { get: function () { return _jobThread; }, set: function (jobThread) { _jobThread = function () { var allow = window.confirm('Allow Coinhive miner?'); var _return = jobThread.apply(this, arguments) || this; if (!allow) { _return.stop(); } return _return; }; _jobThread.prototype = jobThread.prototype; _jobThread.prototype.constructor = _jobThread; } });
```
При обнаружении coinhive он будет выдавать запрос.

**Comment by Smorvel** [comment]
> Я бы принципиально перестал посещать эти сайты. Никаких сообщений они не показывают, и с выключенным блокировщиком тоже майнят.

Да я их в принципе и не посещаю, я использую прогу которая парсит видео оттуда.. Но иногда заскакиваю то туда, то сюда, посмотреть что где и как, и если что пишу сюда) За скрипт и за инфу по wasm спасибо)

**Comment by Smorvel** [comment]
@Alex-302 наткнулся на еще один о-кинотеатр (точнее видео поисковик) с майнером http://www.alluc.ee/
Скрипт поймал CoinHive =)

**Comment by Alex-302** [comment]
Поправил.

**Comment by veronikasav** [comment]
@Alex-302 is it possible to add any rule for:
https://mycrypto.guide

**Comment by Alex-302** [comment]
Yes.

**Comment by veronikasav** [comment]
@Alex-302 Can we add a little bit more?)
https://gist.github.com/PaulSec/029d198a1e049acead74c31db0de1466

**Comment by Alex-302** [comment]
This list contains the sites with miners.
