### ISSUE TITLE
usanetwork.com - Safari can't open the page

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6819]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: 
> Using Safari 11 on macOS Sierra, Adguard is blocking the ability to sign-in to DIRECTV NOW with streaming apps. 

> The solution for me is to manually add sso-idp.evergent.com to the whitelist, but it should not be blocked in the first place. 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

<details><summary>Screenshot1</summary>

![steps 1-2](https://user-images.githubusercontent.com/30041399/30578443-94c77c3e-9d1c-11e7-88b1-c54d8272bb04.png)

</details><br/>

<details><summary>Screenshot2</summary>

![image](https://user-images.githubusercontent.com/30041399/30578461-b0c5e0ce-9d1c-11e7-8f4b-70d4f821e9a6.png)

</details><br/>

<details><summary>Screenshot3</summary>

![image](https://user-images.githubusercontent.com/30041399/30578470-ccc20d48-9d1c-11e7-8333-613019f0b2c5.png)

</details><br/>

***Steps to reproduce the problem***:
> Go to http://www.usanetwork.com/appletv
Enter activation code.
Choose DIRECTV NOW as the provider.
Redirection to sso-idp.evergent.com fails because it is blocked by Adguard.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Sierra
Browser:                            | Safari 11
AdGuard version:                    | ?
Filters enabled:                    | ?
Helpdesk ID (if exists):            | 1128596

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

I've asked for their 'Diagnostic report'. Additional information is to be updated later.

**Comment by Alex-302** [comment]
I don't have Apple tv.

Try this rule:
```
@@.com/ad/$~image,~script,third-party,domain=sso-idp.evergent.com
```
or provide me remote access.

**Comment by vitbortnik** [comment]
> Either of the two rules you suggest fixes the problem, as does just whitelisting sso-idp.evergent.com. However, these are not ads and should not require users to add rules for the functionality. Can this be added to your rules?

> I came across another TV provider sign-in issue. Screen shots are attached. This one pops up an iframe instead of redirecting to another page. Steps to recreate:
Go to http://www.history.com/activate
Select APPLE TV.
Select DIRECTV NOW.
Press CONTINUE.
A blank iframe pops up.
I got around this by whitelisting history.com, but there should be a better solution. This also affects aetv.com 
I am attaching the page source, in case it may help. After whitelisting, the page looks like the third screen shot. Upon making the selections, the iframe element changes to:

I've removed the iframe element source code since it included 'reg codes' and could expose user's private info. 

> I am attaching the iframe source too. 

<details><summary>Screenshot 1</summary>

![steps 1-4](https://user-images.githubusercontent.com/30041399/30666574-75c2cd88-9e5d-11e7-88ec-dffc5689a72b.png)

</details>

<details><summary>Screenshot2</summary>

![image](https://user-images.githubusercontent.com/30041399/30666525-45a803c0-9e5d-11e7-98b8-b6bf3ddca1ed.png)

</details>

<details><summary>Screenshot3 (Correct page)</summary>

![image](https://user-images.githubusercontent.com/30041399/30666535-4d6f122e-9e5d-11e7-8f53-f2e95e6b7fc3.png)

</details>

Those attachments (html files) are attached to the ticket in our Helpdesk. 
Let me know if you need them here. Also please let me know if I should submit each issue with apple tv (history.com and aetv.com) as separate issues here, at GitHub. 

Btw, user has included his Apple TV activation code on his screeshots, which I, obviously, can't post here. I don't know if that's gonna work for you, but I suggest you try.

**Comment by Alex-302** [comment]
Please check again.

**Comment by vitbortnik** [comment]
Asked the user to test how it works and to let us know about it. 
They didn't reply to the previous suggestion of the same kind though.

**Comment by vitbortnik** [comment]
Received a message: 
> I can confirm that after updating to the latest filters the SSO issue for sso-idp.evergent.com has been fixed.
