### ISSUE TITLE
https://diakov.net/ - ad

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6820]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://diakov.net/10162-visual-c-runtime-installer-all-in-one-v50.html

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30578662-c1c87e9e-9d1d-11e7-8f92-bec85c1bac3d.png)

</details><br/>

***System configuration***

**Filters:** 

Rusian, English, RuAdlist

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | Extension
Helpdesk ID (if exists):            | 741799

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
