### ISSUE TITLE
duckduckgo.com - link cannot be opened

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6821]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: 
> When “Allow search ads and websites’ self-promotion” is enabled, search ads show but do not necessarily work.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot1:</summary>

![image](https://user-images.githubusercontent.com/30041399/30578652-ab6cc9e8-9d1d-11e7-970c-5720d53717bd.png)

</details><br/>

<details><summary>Screenshot2:</summary>

![image](https://user-images.githubusercontent.com/30041399/30578656-b494ba30-9d1d-11e7-8400-d5c97dbdafaa.png)

</details><br/>

***Steps to reproduce the problem***:

> Search for something on duckduckgo.com.  In my case, I searched for “adguard.”
Click an advertisement. Link cannot be opened because is it blocked by Adguard.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Sierra
Browser:                            | Safari 11
AdGuard version:                    | ?
Filters enabled:                    | ?
Helpdesk ID (if exists):            | 1128596

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

I've asked for their 'Diagnostic report'. Additional information is to be updated later.

**Comment by Alex-302** [comment]
Fixed.
