### ISSUE TITLE
tiktok app trackers ios

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#68239]
||xlog*-normal-*.tiktokv.com^

||log*-normal-*.tiktokv.com^

||whoami.akamai.net^

**Comment by llacb47** [comment]
https://github.com/llacb47/mischosts/blob/master/tiktok-hosts

**Comment by Alex-302** [comment]
Is an app works fine when they are blocked?

**Comment by jordanelliott23** [comment]
> Is an app works fine when they are blocked?

yeah. been using for a couple days now with them blocked

**Comment by jordanelliott23** [comment]
||client_monitor.isnssdk.com^ can be added too. it appeared yesterday in log @Alex-302

**Comment by Alex-302** [comment]
It is dangerous.
