### ISSUE TITLE
mobile.twitter.com - Annoyance 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6824]
https://github.com/AdguardTeam/AdguardFilters/issues/4436

![image](https://user-images.githubusercontent.com/15856304/30579530-c400e12a-9d21-11e7-8f73-cf8493b29c87.png)

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.79 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.50 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.22 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.39 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.67 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.61 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.2.28 Enabled=NO

**Comment by AdamWr** [comment]
Fixed.
