### ISSUE TITLE
https://www.macerkopf.de/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6825]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://www.macerkopf.de/

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30579877-34ebf50e-9d23-11e7-8ff7-974a2a897c5f.png)

</details><br/>

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Win
Browser:                            | Chrome
AdGuard version:                    | 6.2 beta
Filters enabled:                    | Russian English Social Spyware Annoyances German
AdGuard DNS:                        | None
Stealth mode options (Windows only) | Off
Helpdesk ID (if exists):            | 1630100

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
