### ISSUE TITLE
digiland.tw - anti-adblock

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#6826]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: shows some kind of an anti-adblock message. 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/30580891-e02d14d6-9d26-11e7-9146-3939cbbff20a.png)

</details><br/>

***Steps to reproduce the problem***:
[digiland.tw](digiland.tw)

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | MacOS
Browser:                            | Chrome
AdGuard version:                    | 1.4.1
Filters enabled:                    | Eng, Rus, Ger
Helpdesk ID (if exists):            | 1588135

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by mapx-** [comment]
`@@||digiland.tw/advert.js$script`

**Comment by AdamWr** [comment]
Fixed.
Thank you @mapx-

**Comment by veronikasav** [comment]
Sorry for reopening. That pop-up is still there.

<details><summary>Screenshot:</summary>

<img width="1312" alt="screen shot 2017-09-24 at 1 01 16 pm" src="https://user-images.githubusercontent.com/27292111/30781504-928511ba-a128-11e7-9006-c67e707c865d.png">

</details><br/>

**Comment by Alex-302** [comment]
Not reproduced on my side.

**Comment by veronikasav** [comment]
What should we ask to send us?

**Comment by Alex-302** [comment]
Ask for screenshots of `blocked` requests in the filtering log with English filter only, or with a filter which causes it.

**Comment by veronikasav** [comment]
Asked for a screenshot.

**Comment by vitbortnik** [comment]
<details><summary>Screenshot1:</summary>

![image](https://user-images.githubusercontent.com/30041399/31141276-98f21666-a87f-11e7-9afc-80389b0f65f4.png)

</details><br/>

<details><summary>Screenshot2:</summary>

![image](https://user-images.githubusercontent.com/30041399/31141285-9f269354-a87f-11e7-8a83-09130ef77f6f.png)


</details><br/>

<details><summary>Screenshot3:</summary>

![image](https://user-images.githubusercontent.com/30041399/31141293-a52535ee-a87f-11e7-8202-147ba25f499a.png)

</details><br/>

<details><summary>Screenshot4:</summary>

![image](https://user-images.githubusercontent.com/30041399/31141303-aa6e743e-a87f-11e7-819a-60b0b08f8322.png)

</details><br/>

**Comment by Alex-302** [comment]
Try 
```
@@||pagead2.googlesyndication.com/pagead/show_ads.js$domain=digiland.tw
```

**Comment by vitbortnik** [comment]
> still not working , even i had already close my browser and reopen again ,
the " digiland.tw " website still jump out a warring windows .

**Comment by Alex-302** [comment]
@AdamWr

**Comment by AdamWr** [comment]
I can't reproduce.
I don't have idea why this happens.

**Comment by iverkhohliad** [comment]
Unfortunately, the user reported that the rule does not work.
Is there any other possible solution?

**Comment by Alex-302** [comment]
We can do nothing. Ask for remote access.

**Comment by iverkhohliad** [comment]
I asked him. Waiting for a reply

**Comment by Alex-302** [comment]
Caused by another ad blocker(VPN)
