### ISSUE TITLE
https://www.promotionbasis.de/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6827]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://www.promotionbasis.de/jobs_list1.php?ca=10&cou_id=7&zip_id=1&ind_id=1&act_id=1&ad_ds=&ad_ms=&ad_ys=&ad_s=&ad_de=&ad_me=&ad_ye=&ad_e=&pref_activities_only=&other_activities=&gender_only=&age_group_only=&size_only=&jobtype_id=999&joker=

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30581677-a0509de4-9d29-11e7-91b9-15da5c018281.png)

</details><br/>

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Win
Browser:                            | Chrome
AdGuard version:                    | 6.2 beta
Filters enabled:                    | Russian English Social Spyware Annoyances German
AdGuard DNS:                        | None
Stealth mode options (Windows only) | Off
Helpdesk ID (if exists):            | 1630768

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
