### ISSUE TITLE
http://simptomy-lechenie.net/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6828]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: http://simptomy-lechenie.net/sinusit-u-vzroslyx/

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30585559-f0e9409c-9d35-11e7-997c-e03604488540.png)

</details><br/>

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Win
Browser:                            | Chrome
AdGuard version:                    | 6.2 beta
Filters enabled:                    | Russian English Social Spyware Annoyances German
AdGuard DNS:                        | None
Stealth mode options (Windows only) | Off
Helpdesk ID (if exists):            | 1150428

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
