### ISSUE TITLE
Refersion Service invalid block

### ISSUE THREAD

**Issue by DenyDarko** [AdguardTeam/AdguardFilters#68289]
Adguard DNS is blocking refersion.com (and related subs I guess).

It prevents me from logging in to https://www.refersion.com/base/login and it also prevents people from using their referral ID.

It's not malware/adware, please remove it from being blocked. Thank you :)

**Comment by Alex-302** [comment]
Hi. It is blocked as analytics.
Where is it used?

**Comment by DenyDarko** [comment]
> Hi. It is blocked as analytics.
> Where is it used?

Hey  @Alex-302 
It is used as referral tracker. Users can give out their own personal URL and get paid for purchases made based on their link.
Basically it's an affiliate platform

**Comment by Alex-302** [comment]
I need the real example.

**Comment by DenyDarko** [comment]
> I need the real example.

https://www.hellasdigital.gr/networking-el/4g-lte-3g/tp-link-tl-wr902ac-v1.0-ac750-mini-pocket-3g-4g-wi-fi-router**?rfsn=91757.1771a**

An affiliate needs to give his own links with this part at the end so the referrals can be tracked.

The seller then will login using https://www.refersion.com/base/login and payout all the referrals.

That's about it

**Comment by Alex-302** [comment]
Checked few sites(https://www.pushengage.com/, https://inkfrog.com/ etc) this service also used for tracking. So we cannot unblock it.

**Comment by DenyDarko** [comment]
@Alex-302 they don't do tracking. I'm explicitly talking about this service they provide:

https://www.refersion.com/tracking

Not sure what those two are.

You're kinda wrong here.
