### ISSUE TITLE
http://onlineradiobox.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6829]
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Opera Stable
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
Stealth mode options (Windows only) | Enabled (only self deleting cookies is disabled)
**Site with ad sample**| http://onlineradiobox.com/pl/tokfm/?cs=pl.tokfm&played=1&lang=en

![2017-09-19 11_35_10-sklep](https://user-images.githubusercontent.com/9846948/30585938-a357bfc2-9d2e-11e7-976c-4f386416872b.png)

### Fix
hide gray box (leftover ad)
```
onlineradiobox.com##.banner--vertical
```

**Comment by AdamWr** [comment]
Fixed.

**Comment by FadeMind** [comment]
@AdamWr new
LAUNCH http://onlineradiobox.com/pl/tokfm/player/?cs=pl.tokfm&played=1
Results:
![20200220-1582214724-001](https://user-images.githubusercontent.com/9846948/74954424-638c5e00-5403-11ea-8394-c8a92ca6718b.png)
![20200220-1582214690-001](https://user-images.githubusercontent.com/9846948/74954434-69823f00-5403-11ea-8028-ec8cd375645f.png)

**Comment by AdamWr** [comment]
@FadeMind Mógłbyś proszę napisać w jaki sposób to odtworzyć?
U mnie ten odtwarzacz nie pojawia się w nowym oknie.

**Comment by FadeMind** [comment]
Kilka dni temu tak tam działo, teraz jest już "normalnie" - to znaczy nie ma Popup z odtwarzaczem tylko PLAY odtwarza dźwięk. Jakby się pojawiło ponownie dam znać.

**Comment by AdamWr** [comment]
Ok, dziękuję za odpowiedź :)
