### ISSUE TITLE
Пропущена реклама от рекламной сети recreativ.ru

### ISSUE THREAD

**Issue by Europanda** [AdguardTeam/AdguardFilters#6830]
http://fanserials.tv/12819-family-guy-3-sezon-22-seriya.html
Скриншот
https://cloud.mail.ru/public/3mjo/PGp3djH9t
https://cloud.mail.ru/public/7EX5/yGtkjZtMZ

**Comment by Alex-302** [comment]
Чисто.
Заполните щаблон.
