### ISSUE TITLE
m.sportbild.bild.de - Missed Ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6831]
http://m.sportbild.bild.de/fussball/2017/fussball/struth-interview-dembele-goetze-kroos-hoewedes-berater-53198182.sportMobile.html

Unable to reproduce with the same filters.

<details><summary>Screenshot:</summary>

<img width="438" alt="screen shot 2017-09-20 at 3 24 24 am" src="https://user-images.githubusercontent.com/27292111/30621412-9a768f5c-9db3-11e7-8f2b-9735cb0cabb8.png">

</details><br/>

***System configuration***

Application version: 1.3.1.107
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.79 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.50 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.40 Enabled=YES
ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.16 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.67 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.69 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.61 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.64.15 Enabled=YES

Helpdesk ID :   1267266

**Comment by Alex-302** [comment]
@veronikasav Also not reproduced. Try to switch full/optimized filters.

@AdamWr  please check.

**Comment by AdamWr** [comment]
I can't reproduce.

**Comment by danidoedel** [comment]
Same for me, but there is an app banner when scrolling down:

![2aed5b29-b83a-49c2-a062-ea02e9235025](https://user-images.githubusercontent.com/10995998/30667982-8f9f89e8-9e59-11e7-9bb0-6ca529f98dae.jpeg)

**Comment by Alex-302** [comment]
Added to Annoyances filter
```
m.sportbild.bild.de##.js-flyin
```
