### ISSUE TITLE
Fruit Block Legends, Android app

### ISSUE THREAD

**Issue by digging4roots** [AdguardTeam/AdguardFilters#68324]
Was blocking all ads, but video adds now running. 

Not looking for response, just trying to submit report per email instructions I received.

**Comment by Alex-302** [comment]
@digging4roots please send report using AdGuard menu(all settings will be filled automatically)
https://kb.adguard.com/en/technical-support/reporting-tool#android

**Comment by digging4roots** [comment]
I did submit via AdGuard menu. One of the screens will not proceed if you don't have a valid URL in the field. Which is what happened here. I was then redirected to post the problem on this site.

**Comment by Alex-302** [comment]
@digging4roots please select this in feedback menu
![image](https://user-images.githubusercontent.com/8361299/100368204-f64dcf00-300b-11eb-8bad-cab944a7d6a7.png)

URL - download link of an app or game.

**Comment by digging4roots** [comment]
See screen shots. I am not being permitted to submit using the standard AdGuard method since this is an application and not URL. On the last screen, I am presented a link, when selected, brings me to this site.

![1 Feedback Type](https://user-images.githubusercontent.com/60913974/100683118-88b3e280-332c-11eb-99a2-6d254810acac.png)
![2 What Type](https://user-images.githubusercontent.com/60913974/100683120-894c7900-332c-11eb-8e3f-3bd713cdcff3.png)
![3 Where - Enter URL](https://user-images.githubusercontent.com/60913974/100683122-89e50f80-332c-11eb-9fe5-b56a4643cbe3.png)
![3 Where - URL](https://user-images.githubusercontent.com/60913974/100683125-89e50f80-332c-11eb-8dce-a0fd43f09839.png)

**Comment by Alex-302** [comment]
URL = address of the page of an app. For example, google play link.

**Comment by digging4roots** [comment]
I am well aware of that. There is NO URL as this is an application that 
is displaying the ads.

Alex wrote on 12/2/2020 4:54 AM:
