### ISSUE TITLE
Ge.tt - leftovers + incorrect blocking

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#6832]
1. Остатки: http://ge.tt/9D5oLbm2

<details><summary>Screenshot:</summary>

![ge tt1](https://user-images.githubusercontent.com/17948007/30620880-b2a367f6-9db0-11e7-817e-3152999fc334.jpg)
</details><br/>

Убрать остатки: `ge.tt##gett-ads-taboola-above-banners-set`

 2. Неправильная блокировка: http://ge.tt
После загрузки файла и переходе на главную страницу.

<details><summary>Должно быть:</summary>

![ge tt2](https://user-images.githubusercontent.com/17948007/30621247-b6dcc5d6-9db2-11e7-9375-be36db14c2c2.jpg)
</details><br/>

<details><summary>Имеем:</summary>

![ge tt3](https://user-images.githubusercontent.com/17948007/30621268-dc7aa074-9db2-11e7-8a86-51930640d4fb.jpg)
</details><br/>

Виновник: "Фильтр виджетов социальных сетей", правило: `##.share-box`
Исправление: `~ge.tt##.share-box`

___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard legacy v2.7.1
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Поправил.
