### ISSUE TITLE
streamcloud.eu - Anti adblock

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6833]
http://streamcloud.eu/2figq8tc61x1/Girls__Night_Out_TS_LIne.mp4.html

At my end, the issue was reproduced only if AdGuard program was disabled and extension enabled.

<details><summary>Screenshot:</summary>

<img width="1384" alt="screen shot 2017-09-20 at 6 46 05 am" src="https://user-images.githubusercontent.com/27292111/30626048-0fc6c0ee-9dd0-11e7-9d6f-b438cab9c283.png">

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Mac / Windows
Browser:                            | Chrome
AdGuard version:                    | 1.4.1 / 6.1
Filters enabled:                    | 1 6
Helpdesk ID:            | 1623191

**Comment by Alex-302** [comment]
Fixed.
