### ISSUE TITLE
http://hdrezka.ag/ & http://gidonline.club/ - ошибка манифеста

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6834]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: due to "hide user agent" feature

http://gidonline.club/2011/04/piraty-karibskogo-morya-proklyatie-chernoj-zhemchuzhiny/
http://hdrezka.ag/films/fantasy/325-piraty-karibskogo-morya-proklyatie-chernoy-zhemchuzhiny.html

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30634346-7a3efece-9df7-11e7-9e18-faa927118fea.png)

![image](https://user-images.githubusercontent.com/15856304/30634358-81eef642-9df7-11e7-9e7d-2d7a6c682404.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30634368-8aa12396-9df7-11e7-97fb-50a4ed06aa61.png)

</details><br/>

***Steps to reproduce the problem***:

1. Enable Stealth mode and Hide user-agent in it
2. Visit aforementioned sites
3. Try to play a video
4. See the error

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

- English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
- FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt
- FilterId:14 Name: Annoyances filter Url: https://filters.adtidy.org/extension/chromium/filters/14.txt
- FilterId:1 Name: Russian filter Url: https://filters.adtidy.org/extension/chromium/filters/1.txt
- FilterId:5 Name: Experimental filter Url: https://filters.adtidy.org/extension/chromium/filters/5.txt

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | W10
Browser:                            | Yandex
AdGuard version:                    | 6.1.331.1732
AdGuard DNS:                        | None 
Stealth mode options (Windows only) | enabled, hide user-agent, hide user-agent from 3d parties
Helpdesk ID (if exists):            | 1129133

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
not reproduced. Try
```
@@||cdnapponline.com/video/*/iframe?$stealth
@@||pandastream.cc/video/*/iframe?$stealth
```
and separately 
```
@@/video/*/iframe?$stealth
```

**Comment by ManGravityR** [comment]
These rules do not solve the problem.
I should add that when the "Hide IP-address" the problem also manifests itself.

**Comment by Alex-302** [comment]
Try to enter another IP.

**Comment by ManGravityR** [comment]
The following methods are tested:
1) UA & IP - disable // Player is running
2) UA - disable & IP-enable // Player is running
3) UA & IP - enable // Player does not work

PS1: the address is specified 192.168.14.31.
In the case of an empty field, it works fine. The problem is still not related to the function "Hide IP address".

PS2: when the "Hide User-Agent" field is empty or filled, the player does not work.

With each method, I cleaned the cookies gidonline.club and pandastream.cc

Therefore, when the "Hide User-Agent" function is turned on and when the gidonline.club cookie is deleted / reloaded and the page reboots, the player stops working.

**Comment by Alex-302** [comment]
да можно по-русски)
Добавил такое:
```
@@/video/*/index.m3u8?*&frame_commit=*&mw_pid=*&signature=$stealth
```
мне помогло.
