### ISSUE TITLE
https://www.gog.com/ - social media buttons

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6835]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://www.gog.com/

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30635291-9e8f3250-9dfa-11e7-9510-5ba00b5e22b1.png)

</details><br/>

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Win10
Browser:                            | Chrome
AdGuard version:                    | 6.2 beta
Filters enabled:                    | Russian, English, Social media, Spyware, Annoyances
AdGuard DNS:                        | None 
Stealth mode options (Windows only) | Off
Helpdesk ID (if exists):            | 939612

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
we don't block the links to the blogs. Please remember.

**Comment by evgeniy-ADG** [comment]
Ok, we misunderstood a bit. It appears that the problem is that we block _icons_ in those buttons, Twitter, Reddit and Facebook icons are missing.

**Comment by Alex-302** [comment]
Fixed.
