### ISSUE TITLE
JavaScript в московском метро

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#6838]
Версия 2.9.136, фильтры по-умолчанию, HTTPS  вкл, HTTP вкл, качественная фильтрация. 
И так, проблема такая. Я вхожу в интернет через браузер Google chrome, dolphin, Firefox. При попытке входа появляется сообщение - для продолжения работы включите JavaScript в браузере. Он у меня включен в настройках во всех 3-х браузерах по-умолчанию, если что. Отключаю защиту adguard и все спокойно входит через просмотр рекламы

**Comment by Alex-302** [comment]
Без фильтров повторяется? Попробуй выключить, и после проверки включать по одному.

**Comment by ministr91** [comment]
Без фильтров все работает, заходит в инет. Я скажу сразу, я не тестировал все фильтры, я отключил все фильтры и потом включал 1, выключал этот же и включал другой. 
Виноват фильтр счетчиков и системы аналитики. Другие не тестировал! , так что может быть еще какой-нибудь тоже крашит.

**Comment by Alex-302** [comment]
Фильтр аналитики вечером исправлял. Проверь обновления.

**Comment by ministr91** [comment]
Ну не знаю, у меня на авто обновлении все стоит и фильтры были обновлены, проверю в понедельник

**Comment by ministr91** [comment]
@evgeniy-ADG у тебя работает?

**Comment by ministr91** [comment]
@Alex-302, проблема возникает периодически, то есть это окно, то его нет. Надо тестировать

**Comment by Alex-302** [comment]
Прочитай предыдущий мой коммент.

**Comment by ministr91** [comment]
Вечером это вчера? Я сегодня обновлял и ничего не исправилось

**Comment by ministr91** [comment]
Все работает

**Comment by ministr91** [comment]
@Alex-302, проблема частично решилась, но я понимаю, что лучше все равно не будет, так что и так сойдет. Проблема в следующем: захожу в инет, нажимаю кнопку войти, потом появляется жто окно с требованием включить JavaScript и после этого автоматически переходит в инет. Было бы здорово убрать это окно, но ладно, так тоже хорошо
