### ISSUE TITLE
m.bild.de - Banner - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6839]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Instagram banner at the bottom when scrolling down http://m.bild.de/unterhaltung/leute/oktoberfest/200-gaeste-feiern-auf-der-bild-wiesn-53252196.bildMobile.html

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
![image](https://user-images.githubusercontent.com/31481372/30649693-95901de8-9e29-11e7-8f4f-08cacf1a716b.png)

</details><br/>

Information | Value
-- | --
Operating system: | iOS
Browser: | Safari
AdGuard version: | 1.3.1
Simplified filters (iOS only) | Off
AdGuard DNS: | None
Helpdesk ID (if exists): | 1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. Select it by Adguard's tool and copy the rule

**Comment by Alex-302** [comment]
@iverkhohliad

**Comment by Bohdan-SUP** [comment]
User can't reproduce anymore.
