### ISSUE TITLE
m.focus.de - Pop up - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6840]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Newsletter pop up
http://m.focus.de/regional/muenchen/oktoberfest/nach-nur-vier-tagen-oktoberfest-wiesn-schausteller-klagen-ueber-besucher-flaute_id_7611912.html

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
![image](https://user-images.githubusercontent.com/31481372/30655305-304e4dfa-9e39-11e7-98a7-4cf5a4dc1a8a.png)

</details><br/>

Information | Value
-- | --
Operating system: | iOS
Browser: | Safari
AdGuard version: | 1.3.1
Simplified filters (iOS only) | Off
AdGuard DNS: | None
Helpdesk ID (if exists): | 1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed,
