### ISSUE TITLE
hackingwithphp.com - Ad - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6841]
***Site***: http://www.hackingwithphp.com/10/3/6/checking-session-data
***Description***: Adblock detection. Red ad banner and ad after article.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30656868-d3db7640-9e35-11e7-8baa-872d4e2e528b.png)

![image](https://user-images.githubusercontent.com/10995998/30656936-0d08bcca-9e36-11e7-8c87-3ea8fdac5f40.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
