### ISSUE TITLE
https://diamongs.com/bkZDTnhBeTcnHFNwc3tPXHNlPB0Ke3JoGx17JxgqPQtwGDwjAhEYLDwAKgAPHgIFJBwJBxYHXg8kN3NJSDB+f1Zfdm14QUB0ZT0VU3d1aBNTNio8GRojZnxIGikzf0heY3F+DAE0MSsWGmNxfhwHNCYtDEt0cyMZCSgmOl1cdichDwAqLC8cSDU3PUVeYDM8FlN2ZSsVDHtzaA1TIyEvTFdyJXsdDCNxeUkMJHUtGl9+eyhNDCBwKB5YdyBoHh17cmgRCHtzaAoLIH4mDBo2MGtLL2NxCF1cADMnCg8yJj4KAT46YBsPK2Z8PhopM2gXHTR+PhEcJzcrCBwpOzdWDScuaBwdMi9zCAc0IjodHjQsNgFAJSIjXgQ1N3NISCMtPEVeYCA6RV9gIDobU3c

### ISSUE THREAD

**Issue by PappanDin** [AdguardTeam/AdguardFilters#6843]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | ?
Browser:                            | ?
AdGuard version:                    | ?
Filters enabled:                    | ?
AdGuard mode (Android only):        | VPN / Proxy (manual/auto)
Filtering quality (Android only):   | High-quality / High-speed / Simplified
HTTPS filtering (Android only):     | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)       | On / Off
AdGuard DNS:                        | None / Default / Family Protection
Stealth mode options (Windows only) | ?
Helpdesk ID (if exists):            | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I need a source.
Next time please fill the template.
