### ISSUE TITLE
Twitch app for Windows - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6845]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://app.twitch.tv/download

The customer has tried adding `.exe` files to the list of filtered, it didn't help.

> Если добавить Curse.Companion.FriendsHelper.exe, то реклама, по-видимому, не показывается, но вместо неё трансляция начинает прерываться на доли секунды или в течение нескольких секунд воспроизводится замедленно

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30683777-68374874-9eb7-11e7-8bd3-d3056de320bd.png)

</details><br/>

***Steps to reproduce the problem***:

1. Install, create a profile, login
2. While using the app, you'll see video labeled as "Advertisement"

> нужно просто смотреть каналы и рано или поздно (по 
> ощущениям примерно раз в полчаса-час) реклама появится. Правда, я не 
> уверен, на всех ли каналах есть реклама, но, скорее всего, на всех, так 
> как у меня есть информация от владельца одного канала, что он рекламу 
> себе не подключал, но по инициативе Twitch'а реклама там всё-таки была

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

- Name: Russian filter Url: https://filters.adtidy.org/extension/chromium/filters/1.txt
- FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
- FilterId:6 Name: German filter Url: https://filters.adtidy.org/extension/chromium/filters/6.txt
- FilterId:9 Name: Spanish/Portuguese filter Url: https://filters.adtidy.org/extension/chromium/filters/9.txt
- FilterId:216 Name: Adblock polskie reguły Url: https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows NT 10.0.15063.0
Browser:                            | none
AdGuard version:                    | 6.1.331.1732
AdGuard DNS:                        | None 
Stealth mode options (Windows only) | 
Helpdesk ID (if exists):            | 1562793, 1632305

<details><summary>STEALTH MODE OPTIONS </summary>
StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": true,
  "BlockWebRtc": true,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254"
}
</details>

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
> Если добавить Curse.Companion.FriendsHelper.exe, то реклама, по-видимому, не показывается, но вместо неё трансляция начинает прерываться на доли секунды или в течение нескольких секунд воспроизводится замедленно

больше похоже на проблемы совместимости. Скорости я тут не прибавлю.

@zebrum @vozersky можете проверить?

**Comment by Alex-302** [comment]
@zebrum

**Comment by zebrum** [comment]
@evgeniy-ADG какие именно exe файлы добавлены в фильтруемые приложения?

**Comment by evgeniy-ADG** [comment]
> Здравствуйте, был добавлен изначально только Twitch.exe, добавил как вы
> подсказали "Curse.Companion.FriendsHelper.exe", но это не помогло, реклама
> все равно просачивается.

**Comment by Alex-302** [comment]
@evgeniy-ADG в журнале фильтрации видны запросы приложения?
