### ISSUE TITLE
wi-fi.ru - asking to enable javascript though it's enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6846]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: Please check the screenshots. Works fine if you disable AdGuard.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30690993-d4139004-9ece-11e7-8ad2-0ee3915f0dfe.png)

![image](https://user-images.githubusercontent.com/15856304/30691005-df213a82-9ece-11e7-9eea-2a5c04e8c6cb.png)

</details><br/>

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS 11
Browser:                            | Safari
AdGuard version:                    | 1.3.1.107
Filters enabled:                    | 1 2 3 4 12 15
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 577712

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/6838

**Comment by ministr91** [comment]
@evgeniy-ADG проблема частично решилась, но я понимаю, что лучше все равно не будет, так что и так сойдет. Проблема в следующем: захожу в инет, нажимаю кнопку войти, потом появляется жто окно с требованием включить JavaScript и после этого автоматически переходит в инет. Было бы здорово убрать это окно, но ладно, так тоже хорошо

**Comment by ministr91** [comment]
@evgeniy-ADG можешь ее отвечать, я привык, что ты постоянно игнорируешь сообщения
