### ISSUE TITLE
[NSFW] xkeezmovies.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6847]
Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Opera Stable
AdGuard version:                    | 6.2.400.2059
Filters enabled:                    | Polish/Polish - Adguard suplement/KAD/Adguard Spy/Adguard English/Adguard Annoyances/I Don't care about cookies
Stealth mode options (Windows only) | Enabled (only self deleting cookies is disabled)
Site Sample | http://xkeezmovies.com

- popups (click on random clip site)
- popups click on twitter link (at end of site)

**Comment by AdamWr** [comment]
Fixed.
