### ISSUE TITLE
facebook.com

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdguardFilters#68470]
### Issue URL (Annoyance)
 
 https://www.facebook.com/groups/anbernic/

 ### Comment
 
 Username: @Morku
 
 > ## Cookie Banner at bottom (sporadically)
 > Die folgenden Informationen werden automatisch generiert. Bitte löschen Sie sie nicht.
 > Custom userscripts:
 > https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
 
 ### Screenshots
<details><summary>Screenshot-1:</summary>

![facebook](https://user-images.githubusercontent.com/6276915/100286673-825fe800-2f73-11eb-85a3-9dc88db94517.png)

</details><br/>

 ### System configuration
 Information 	value
 AdGuard product: 	AdGuard for Windows v7.5.3
 Browser: 	Firefox
 AdGuard driver: 	WFP
 Stealth mode options: 	Hide your search queries,
 Send Do-Not-Track header,
 Remove X-Client-Data header from HTTP requests,
 Strip URLs from tracking parameters
 Filters: 	Ad Blocking:
 AdGuard Mobile Ads,
 AdGuard Base
 
 Privacy:
 AdGuard Tracking Protection
 
 Social Widgets:
 AdGuard Social Media
 
 Annoyances:
 AdGuard Annoyances
 
 Language-specific:
 AdGuard Russian,
 AdGuard German

**Comment by Morku** [comment]
Why you always close tickets for no reason!? The banner is still present. (@ameshkov )

@AdamWr 
Can you please have a look again? Thank you.

**Comment by AdamWr** [comment]
@Morku Could you please check this rule:
`facebook.com##div[data-cookiebanner="banner"]`

**Comment by Morku** [comment]
@AdamWr 
THANK YOU for taking care again.

I can confirm, it is working.

PROOF:
[2020-12-01_13-04-49.zip](https://github.com/AdguardTeam/AdguardFilters/files/5622458/2020-12-01_13-04-49.zip)

The reason why you might can't reproduce, it is probably related to IP address.
When I use AdGuard VPN with german IP address, there is for some reason no Cookie Banner.
When I am browsing with my directly ISP IP, I get the Cookie Banner. Thats why I wrote sporadically.

Please do not just close the tickets.

**Comment by AdamWr** [comment]
Okay, I added this rule.
Thank you for your reply.

By the way, I was able to reproduce it.
