### ISSUE TITLE
http://professorweb.ru/ - майнер

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6848]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: http://professorweb.ru/my/csharp/assembly/level5/5_2.php
Мы такое блокируем? Если да, то каким фильтром?

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30731188-88ea17e6-9f74-11e7-8c28-256e97821e12.png)

</details><br/>

***Steps to reproduce the problem***:

1. Перейти на сайт по ссылке
2. Есть предупреждение о том, что сайт будет использовать браузер для майнинга

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows 7
Browser:                            | Chrome,  Yandex
AdGuard version:                    | 6.2.390.2018
Filters enabled:                    | 1, 2, 120
AdGuard DNS:                        | None 
Stealth mode options (Windows only) | On
Helpdesk ID (if exists):            | 1093966

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
https://pikabu.ru/story/mayner_na_professorwebru_5353785

**Comment by Alex-302** [comment]
У нас добавлено правило для обнаружения майнера. Оно справшивает ращрешения пользователя.
На iOS подоменно блокируем.
