### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by Mysteerion** [AdguardTeam/AdguardFilters#68506]
Hello,

Autoplay doesn't work with Youtube videos with AdGuard Annoyances filter enabled.
Seen from France on Chrome 86.0.4240.198 x64 for Windows 10, with uBlock Origin extension.

This issue is dued to blocking the middle screen popup inviting to connect to Youtube/Google account.
It may be related to this rule :
`youtube.com##ytd-popup-container > paper-dialog:has(:scope > yt-upsell-dialog-renderer > #dialog > #content > yt-formatted-string > a[href^="https://support.google.com/youtube/?p=sign_in"])`

Thanks for all your work!

**Comment by krystian3w** [comment]
Pop-up "Sign into YouTube" should be manually closed.

Now no works options with `:remove()` and simple `json-prune`/`set-constant` glitch load homepage or comments.

**Comment by BlazDT** [comment]
Sadly I cannot reproduce.

**Comment by krystian3w** [comment]
Need view as guest, maybe Google disable A/B test for you?

**Comment by BlazDT** [comment]
Maybe. Removed the rule though now.
