### ISSUE TITLE
timeanddate.com

### ISSUE THREAD

**Issue by hadjisoteriou** [AdguardTeam/AdguardFilters#68525]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

Issue URL (Incorrect Blocking)

https://www.timeanddate.com/time/change/vietnam

Comment

gap at the top of the page ✌🏼

Username: @hadjisoteriou

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information | value
-- | --
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.0.3
Browser: | Safari
System wide filtering: | disabled
Simplified filters: | disabled
AdGuard DNS: | None
Filters: | Ad Blocking:AdGuard Base, AdGuard Mobile AdsPrivacy:AdGuard Tracking ProtectionSocial Widgets:AdGuard Social MediaAnnoyances:AdGuard Annoyances, I don't care about cookies

**Comment by Alex-302** [comment]
For user rules:
```
timeanddate.com#$#.header__wrapper { height: 40px !important; }
timeanddate.com##.banner--lunar-penumbral
```

**Comment by hadjisoteriou** [comment]
> For user rules:
> 
> ```
> timeanddate.com#$#.header__wrapper { height: 40px !important; }
> timeanddate.com##.banner--lunar-penumbral
> ```

hmm, I added those rules but there’s still a gap. appreciate it either way
