### ISSUE TITLE
NataliePortman.com - blocked

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#6852]
Using uBlock Origin, this site is prevented from loading by 'Adguard's Annoyance List'​​​​​​​​​:
https://www.natalieportman.com/

The site can't load, and only a spinning loading wheel is shown.

(Pale Moon v27.4.2,x64 / Win8.1Pro)

**Comment by Alex-302** [comment]
Fixed.

**Comment by THEtomaso** [comment]
That was fast! :)
