### ISSUE TITLE
www.engadget.com - Ad - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6853]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Missed ad on page: "sponsored content" stories  www.engadget.com

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30755892-f8a0a0ee-9fd0-11e7-86eb-59d059dd329b.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | 10.3.3
AdGuard version:                    | 1.3.1.82
Filters enabled:                    | 0,2,3,4,14,11,12,118,207
Simplified filters (iOS only)       | On
Helpdesk ID (if exists):            | 1444380

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't reproduce without Adguard.
@AdamWr please check on your device.

**Comment by Alex-302** [comment]
@AdamWr

**Comment by AdamWr** [comment]
I can't reproduce.
