### ISSUE TITLE
www.gismeteo.ru - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6854]
https://www.gismeteo.ru/weather-kamyshin-5064/

<details><summary>Screenshot:</summary>

<img width="1318" alt="screen shot 2017-09-23 at 5 38 02 am" src="https://user-images.githubusercontent.com/27292111/30769459-698e72cc-a021-11e7-9983-dc0323638679.png">

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | 6.1
Filters enabled:                    | 1 2 119
Helpdesk ID :            | 1450547

**Comment by veronikasav** [comment]
The same issue but on a different device.

https://www.gismeteo.ru/weather-moscow-4368/tomorrow/

<details><summary>Screenshot:</summary>

<img width="508" alt="screen shot 2017-09-23 at 5 43 24 am" src="https://user-images.githubusercontent.com/27292111/30769496-3e6be146-a022-11e7-9ed7-417d14ea8c0f.png">

</details><br/>

[debug (21).txt](https://github.com/AdguardTeam/AdguardFilters/files/1326233/debug.21.txt)
[state (99).txt](https://github.com/AdguardTeam/AdguardFilters/files/1326234/state.99.txt)

**Comment by Alex-302** [comment]
Please check again. It was fixed yesterday.

**Comment by vitalkanev** [comment]
Can't reproduce for some cases in Firefox 55 - Xubuntu Zesty with 2.6.7 browser extension. Site: https://www.gismeteo.ru/weather-syktyvkar-3989/
![noads-gismeteo](https://user-images.githubusercontent.com/18398761/30773578-0f9c3aaa-a07c-11e7-83ab-fa9692b2aa23.png)

**Comment by vitalkanev** [comment]
На текущий момент опять появилась. Последние версии фильров на 17:39. То же самое что и на посту вверху (ссылка, браузер, версия) @Alex-302

**Comment by Alex-302** [comment]
HTTPS фильтруется?
У меня даже с расширением чисто.

**Comment by vitalkanev** [comment]
У меня нет такой опции в настройках

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/new
нужен полностью заполненный шаблон
