### ISSUE TITLE
facebook app tracker.

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#68552]
if i go to a post in this group i am in and then click the link. has to be done through the actual facebook app tho not the website. 

apptrace.com  appears in my log. i blocked it and havent had any issues

**Comment by jordanelliott23** [comment]
this is the link i clicked through the facebook app. to reproduce you could find the post through the group in the app then click it 

https://www.facebook.com/groups/738933136238587/permalink/2154513788013841/

**Comment by Alex-302** [comment]
This is a but trackeк - service for devs.
