### ISSUE TITLE
amalgama-lab.com - Annoyances

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#6855]
"Печать" внизу страницы перекрывает часть текста, мешая, тем самым, нормальному восприятию информации. Сама "печать" никакой смысловой нагрузки не несёт: https://www.amalgama-lab.com/songs/b/bonnie_tyler/total_eclipse_of_the_heart.html

<details><summary>Screenshot:</summary>

![amalgama-lab com](https://user-images.githubusercontent.com/17948007/30769708-522c2420-a027-11e7-804c-efc316a266de.jpg)
</details><br/>

 Думаю стоит её убрать в "раздражителях": `amalgama-lab.com###quality`
___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard legacy v2.7.1
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Добавил.
