### ISSUE TITLE
www.overclockers.ru - Missed Ad

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardFilters#6856]
Missed ad on https://www.overclockers.ru/ .
Logs attached. 

![default](https://user-images.githubusercontent.com/30834067/30773181-0bae4058-a074-11e7-836d-229ca35b5ad3.jpg)

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10
Browser:                            | Chrome 61
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 1,2,3,4
Helpdesk ID (if exists):            | 1630721

**Comment by Alex-302** [comment]
Check SSL certificate on this site. I don't see assistant icon.
