### ISSUE TITLE
mail.yandex.ru -  пропущена реклама 

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardFilters#6857]
https://mail.yandex.ru/?ncrnd=291307&uid=16620841&login=sibfoto#inbox  

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![default](https://user-images.githubusercontent.com/30834067/30773215-04e1b7ae-a075-11e7-9280-4a8c6fd9d5e8.JPG)

</details>

**Filters:**

Operating system:                   | Microsoft Windows NT 6.1.7601 Service Pack 1
Browser:                            | Chromium  50.0.2645.0 (64-bit)
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 1,2,3,4
Helpdesk ID (if exists):            | 1144675

**Comment by Alex-302** [comment]
Не повторяется.
Пусть в настройках отключит

<details>

![image](http://imagizer.imageshack.com/img923/7820/jZ2hUk.png)
</details>
