### ISSUE TITLE
Facebook Pixel

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#68573]
https://avrupayakasi.com/

Actually I don't know what it does. It looks like some kind of tracking script.

`https://avrupayakasi.com/catalog/view/javascript/facebook/facebook_pixel_3_1_0.js`

<details>
 <summary>IMG</summary>

 
![image](https://user-images.githubusercontent.com/74098460/100399457-f7aae600-3063-11eb-9c76-893450bf16ed.png)

</details>

Chrome/Win10/Browser Extension
Base,Tracker Protection,Social,Turkish,Annoyance

**Comment by Alex-302** [comment]
Not sure if it can be blocked safely. It is related to shopping process.
