### ISSUE TITLE
gpone.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6860]
***Site***: https://www.gpone.com/en
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30773585-df29e9ce-a073-11e7-9649-83cb4afc0e7c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by ameshkov** [comment]
CloudFlare's noadblock app

**Comment by ameshkov** [comment]
```
||gpone.com/cdn-cgi/apps/head/*.js
```

**Comment by Alex-302** [comment]
Added
