### ISSUE TITLE
channel4.com - Ad - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6861]
***Site***: http://www.channel4.com/programmes/gogglebox/on-demand/62777-003
***Description***: Ad leftover at the top and ad background.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30773640-cc5bf9bc-a074-11e7-8241-80a697d18edf.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
