### ISSUE TITLE
yemeksepeti.com

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#68636]
https://www.yemeksepeti.com/bolu/merkez-yasamkent-mah

Could you please create a rule for my user filter?
Thanks

<details>
 <summary>IMG</summary>

 
![www yemeksepeti com (4)](https://user-images.githubusercontent.com/74098460/100472431-46e92900-30ed-11eb-9374-e443b9449cb9.png)

</details>

<details>
 <summary>IMG</summary>

 
![www yemeksepeti com (3)](https://user-images.githubusercontent.com/74098460/100472379-32a52c00-30ed-11eb-9bee-00044daa9117.png)

</details>

Chrome/Win10/Browser Extension
Base,Tracking Protection,Social,Annoyance,Turkish filter

**Comment by RadicalNoise** [comment]
`yemeksepeti.com##div.ys-promoted-reslist-items`

This rule works, but I don't know if it valid

**Comment by Alex-302** [comment]
Hi. It is valid.
You can use AdGuard tab in dev tools for creating some basic rules
![image](https://user-images.githubusercontent.com/8361299/100519627-da7c3180-31a1-11eb-915a-d434594928ea.png)
