### ISSUE TITLE
m.joemonster.org gallery filtering "Thumbs Up"/"Okejka" button

### ISSUE THREAD

**Issue by Rutodor** [AdguardTeam/AdguardFilters#68648]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

Writing post in English, let me know if Polish translation is needed.

***Description***:
I can't see "Thumbs Up"/"Okejka" button in gallery of mobile joemonster.org page.

***Current behaviour**: 
It only happens in gallery or when choose any picture within that gallery, example:
https://m.joemonster.org/mg/lastup/list#pic-259944
I can't see the "Thumbs Up"/"Okejka" button.
It's being filtered out with Facebook share button only in gallery. On articles or videos it works fine.
On the images I will show the difference. It doesn't matter if it's on the scrolling view or when entered any particular picture page.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>
![Screenshot_20201127-214304_Chrome](https://user-images.githubusercontent.com/75142586/100483704-1e1b6080-30fa-11eb-99e9-7dcb0013a48d.jpg)
![Screenshot_20201127-214414_Chrome](https://user-images.githubusercontent.com/75142586/100483711-24a9d800-30fa-11eb-9180-f745a796194e.jpg)
</Details>
<Br/>

* **Expected behaviour**: 
I see "Thumbs Up"/"Okejka" button while Facebook share button is gone.

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

Just open the following link on the social media filters on on Android Chrome:
https://m.joemonster.org/mg/lastup/list#pic-259944
Then turn it off and see the difference :).

***System configuration***

**Filters:**
default, Fanboy's
[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android 9
Operating system version (Android/iOS) | Android
Browser:                               | Chrome
AdGuard version:                       |  3.5.2
Filters enabled:                       |  Yes
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality but not sure where to check it (I have Polish version and i use this app for the first day -super satisfied atm :) )
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off - don't know
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | Default
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Rutodor** [comment]
![Uploading Screenshot_20201127-214304_Chrome.jpg…]()

**Comment by Rutodor** [comment]
https://ibb.co/K7sQgzx
https://ibb.co/9b2psg5
Uploading pictures on Android failed so they are available in above links. Sorry for that.

**Comment by krystian3w** [comment]
Wyłącz listę Fanoby social / fanboy annoyance? Oni mają generyk.

```
##.socialContainer
```

**Comment by Rutodor** [comment]
Na wyłączonych przycisk 'łapki w górę' jest wraz z buttonami fejsbuka,
których nie chcemy :).
Niestety przycisk ten też znika na defaultowym filtrze mediów
społecznościowych AdGuarda.


pt., 27 lis 2020, 22:17 użytkownik krystian3w <notifications@github.com>
napisał:

**Comment by krystian3w** [comment]
No niby mają taki sam filtr: https://github.com/AdguardTeam/AdguardFilters/blob/102c17e714c46b8a708fde0a10c424bd91db1416/SocialFilter/sections/general_elemhide.txt#L771

**Comment by Rutodor** [comment]
Hmm, laickie pytanie:
A jak wyglądałaby regułka dla whitelisty, by włączyć od filtr tylko na
danej stronie? W tym wypadku w domenie m.joemonster.org?

Dziękin

pt., 27 lis 2020, 23:05 użytkownik krystian3w <notifications@github.com>
napisał:

**Comment by krystian3w** [comment]
`joemonster.org#@#.socialContainer`

i dodajesz do filtrów własnych w aplikacji AdGuard.

`m.` można śmiało pominąć, bo wersja PC ma ten sam bug.

**Comment by Rutodor** [comment]
Dzięki wielkie, Krystian, za zaangażowanie i pomoc! Bardzo doceniam. Wyjątek działa poprawnie :).

Powiedz mi jeszcze - zamknąć wątek, czy zostawić licząc, że może jeszcze kiedyś wyodrębnione zostaną button fejsbuka od buttonu łapki w górę?

**Comment by krystian3w** [comment]
Najlepiej zostaw otwarty.

**Comment by AdamWr** [comment]
> joemonster.org#@#.socialContainer

Dodałem tę regułę do listy `Filtr mediów społecznościowych AdGuard`, aktualizacja filtrów powinna być dostępna za około 1-2 godziny.

Dziękuję za pomoc i za zgłoszenie.
