### ISSUE TITLE
nextdoor app ios

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#68653]
||us-tracking.nextdoor.com^
||datadoghq-browser-agent.com^

https://apps.apple.com/us/app/nextdoor-local-neighborhood/id640360962

**Comment by Alex-302** [comment]
Cannot install. Did you check these rules?

**Comment by jordanelliott23** [comment]
yes. app works fine with blocked

**Comment by jordanelliott23** [comment]
datadoghq-browser-agent.com is already in third party tracking list but the third party part stops it from working so we can just change it to ||datadoghq-browser-agent.com^

**Comment by jordanelliott23** [comment]
https://github.com/AdguardTeam/AdguardFilters/blob/19d5729c361ab8455df877afbcabffdc1718764a/SpywareFilter/sections/tracking_servers.txt#L54

**Comment by Alex-302** [comment]
> ||datadoghq-browser-agent.com^

It breaks some popular serviced.
