### ISSUE TITLE
promobit.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#68675]
[https://www.promobit.com.br/blog/cooktop-vitroceramico-o-que-e-e-como-funciona-663/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.promobit.com.br/blog/cooktop-vitroceramico-o-que-e-e-como-funciona-663/)

Overlay when you move the mouse cursor to another tab, and cookie notice:

![cookies](https://user-images.githubusercontent.com/35470489/100494754-7adf4100-3123-11eb-883a-2d9f7c7c9477.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by adranger** [comment]
@Alex-302 I think that you accidentally added the same mobile banner rule twice instead of hiding the cookie notice.

**Comment by Alex-302** [comment]
Thanks, fixed.
