### ISSUE TITLE
indy100.com (N: uBlock Origin) (T: Ads)

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#68679]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Placeholder on top. I propose `indy100.com#?#div[data-size-key=TOP_BANNER]:upward(2)`

This was originally submitted to EasyList at https://github.com/easylist/easylist/issues/6536, and was promptly completely ignored in everyone's fixes of it.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/100470915-72621880-30d9-11eb-87c2-280569f23bb6.png)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

1) Visit `https://www.indy100.com/news/rudy-giuliani-hugo-chavez-us-election-b1759195`

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/100470842-51012c80-30d9-11eb-8de2-4529c74b1ca3.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | October 2020 Update
Browser:                               | Chrome 87.0.4280.66 x64
AdGuard version:                       | uBO 1.31.1b6 + IDCAC 3.2.5
Filters enabled:                       | See screenshot above
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by THEtomaso** [comment]
@Alex-302:
I pinged BlazDT here, a week ago, but he didn't respond:
https://github.com/easylist/easylist/issues/6536#issuecomment-734950467
Perhaps you could take a look at it?
