### ISSUE TITLE
slideshare.net - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6868]
***Site***: https://www.slideshare.net/
***Description***: Cookie notice. Ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30774110-e1cebf9c-a07d-11e7-8eb6-922b7b10c90e.png)

![image](https://user-images.githubusercontent.com/10995998/30774121-f0a52722-a07d-11e7-8a82-0822a2d38e1a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Can't reproduce cookie notice, ad leftover fixed.

**Comment by danidoedel** [comment]
@AdamWr Cookie notice is still there for me. This rule would fix it:

`slideshare.net##.tos-update-banner`

**Comment by AdamWr** [comment]
Added.
Thank you.
