### ISSUE TITLE
freiepresse.de - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6869]
***Site***: https://www.freiepresse.de/
***Description***: Cookie notice leftover at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30774151-2fb9bb08-a07e-11e7-9d8a-5da4888e0ed5.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by ameshkov** [comment]
```
freiepresse.de###cookie_note
freiepresse.de###x750
```

**Comment by Alex-302** [comment]
added
```
freiepresse.de###cookie_note
freiepresse.de##body > div[id][style^="z-index:"]

```
