### ISSUE TITLE
ign.com - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6870]
***Site***: http://www.ign.com/wikis/battlefield-1/Avanti_Savoia
***Description***: Ad leftover. Cookie notice.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30774576-fcf70c46-a084-11e7-87b9-4d2edf701c4f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by ameshkov** [comment]
Annoyances:
```
ign.com###policyNotice
```

Regarding the leftover, we shouldn't do it for every website. Although, for ign.com we can make an exception as it has 150M daily visitors:
```
ign.com#$##king { height: 100px!important; min-height: 100px!important; }
ign.com#$#body>.preShell {  margin-top:0px!important; }
```

These two rules should be thoroughly tested.

**Comment by AdamWr** [comment]
Added:
`ign.com###king`
`ign.com###policyNotice`
