### ISSUE TITLE
beinsports.com - Annoyance - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6871]
***Site***: https://connect.beinsports.com/us/
***Description***: Adblock detection. Cookie notice at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30777136-a1c55cd0-a0b4-11e7-8950-d3a67ebbd77a.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by ameshkov** [comment]
Shows this message if `fuckAdBlock` is not defined:
```
    "undefined" == typeof fuckAdBlock && (console.log(t()),
    t() && swal({
        title: "Ad Blocker Detected",
        text: "Please disable your ad blocker",
        type: "warning",
        confirmButtonText: "OK",
        closeOnConfirm: !1
    }))
```

We should simply define it on the page:
```
#%#window.fuckAdBlock = {};
```

Or maybe we already have a script for it?

**Comment by Alex-302** [comment]
Added
```
@@||beinsports.com/wp-content/themes/bein/dist/scripts/fuckadblock.js
```
