### ISSUE TITLE
mivo.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6872]
***Site***: https://www.mivo.com/video/41729
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30777186-8496d534-a0b5-11e7-9b68-468c608cef3f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by ameshkov** [comment]
`initRmpAdBlock` function is what we need to remove

**Comment by ameshkov** [comment]
The rules:
```
mivo.com#%#window.initRmpAdBlock = function() {};
/rmp-blockadblock.js$domain=mivo.com
```

**Comment by Alex-302** [comment]
added + solution for platform without JS
