### ISSUE TITLE
runnersworld.com - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6874]
***Site***: https://www.runnersworld.com/
***Description***: Ad leftovers. Newsletter sign up.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30777214-0d9dc3d8-a0b6-11e7-8856-c27a2c6ebf84.png)

![image](https://user-images.githubusercontent.com/10995998/30777219-194d883a-a0b6-11e7-88e1-8f61d9f7c7ad.png)

![image](https://user-images.githubusercontent.com/10995998/30777227-2c58fb08-a0b6-11e7-869b-5d905961dbbf.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
