### ISSUE TITLE
alphr.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6875]
***Site***: http://www.alphr.com/cars/1006596/mercedes-c-class-2017-review-a-compact-saloon-that-punches-well-above-its-weight
***Description***: Cookie notice at the top. Newsletter sign up slides in.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30777239-6a2f97d4-a0b6-11e7-9db7-ee4416f7dfdf.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
