### ISSUE TITLE
bicycling.com - Annoyance - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6876]
***Site***: https://www.bicycling.com/
***Description***: Ad leftover at the top. Newsletter sign up.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30777255-b366bdce-a0b6-11e7-81a6-d7a3b375e6a9.png)

![image](https://user-images.githubusercontent.com/10995998/30777261-bf58426a-a0b6-11e7-84e7-20ad38d3515f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
