### ISSUE TITLE
10co.* - Social widgets - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6877]
***Sites***: 

- http://10co.biz/aYp 
- http://10co.xyz/aYQ 
- http://10co.co/aYq 
- http://10co.me/aYr

***Description***: Adblock detection (countdown is set to 500s with AdGuard enabled). Social share icon leftover (only 10co.co and 10co.me)

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30777311-047116fa-a0b8-11e7-9c03-6d2865e74608.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
