### ISSUE TITLE
tribunavalladolid.com - Ads - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6879]
***Site***: https://www.tribunavalladolid.com/
***Description***: Ads and ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30777385-b82fb06a-a0b9-11e7-802f-3fe878f4b09e.png)

![image](https://user-images.githubusercontent.com/10995998/30777387-c7607312-a0b9-11e7-8f3b-98b35d689813.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
