### ISSUE TITLE
muyinteresante.es - Annoyance - Ad leftover - Ad - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6881]
***Site***: https://www.muyinteresante.es/naturaleza/articulo/esta-gigantesca-rana-era-capaz-de-comer-dinosaurios-121506067950
***Description***: Adblock detection. Ad leftovers. Newsletter sign up. Ad video plays after view seconds on the site.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30777422-6a29cf94-a0ba-11e7-8a11-acdfe6f6bb24.png)

![image](https://user-images.githubusercontent.com/10995998/30777424-80ec468a-a0ba-11e7-8d4d-0a08ccc70940.png)

![image](https://user-images.githubusercontent.com/10995998/30777429-90b6764e-a0ba-11e7-9b30-2a8c4513b6b0.png)

![image](https://user-images.githubusercontent.com/10995998/30777432-9d585b10-a0ba-11e7-9e94-578acde03be2.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
Spanish/Portuguese filter

**Comment by AdamWr** [comment]
Adblock detection, ad leftover and newsletter fixed.
I can't reproduce video ad.
