### ISSUE TITLE
mob.hr - Missed ad - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6882]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Missed ad 

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30777706-5d15d8ca-a0c9-11e7-84d4-acd2f40ebfe0.png)

![image](https://user-images.githubusercontent.com/31481372/30777710-7e32ee58-a0c9-11e7-9d51-9d36e7d5c163.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | 10.3.3
AdGuard version:                    | 1.3.1.82
Filters enabled:                    | 0,2,3,4,11,12
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None / Default / Family Protection
Helpdesk ID (if exists):            | 1632278

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
fixed
