### ISSUE TITLE
www.gpone.com - Adblock detection - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6884]
***Description***:
* **Current behaviour**: 

Adblock detection: https://www.gpone.com/en

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30777963-2aed6410-a0d0-11e7-9edf-24e03126f29f.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.47 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.42 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.9 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.20 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.61 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.64 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.60 Enabled=YES

Information | Value
-- | --
Operating system: | iOS
Browser: | Safari
AdGuard version: | 1.3.1
Simplified filters (iOS only) | Off
AdGuard DNS: | None
Helpdesk ID (if exists): | 1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
seems to be NoAdBlock

**Comment by AdamWr** [comment]
I think it was fixed here - https://github.com/AdguardTeam/AdguardFilters/issues/6860
