### ISSUE TITLE
m.ranker.com - Ad leftovers - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6885]
***Description***:
* **Current behaviour**: 

Ad leftovers and annoying share bar at the bottom: 
http://m.ranker.com/list/weird-celebrity-middle-names/amylindorff?ref=hp_list&l=1

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30777982-d6aa3f94-a0d0-11e7-8be8-151961de4e0a.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.47 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.42 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.9 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.20 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.61 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.64 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.60 Enabled=YES

Information | Value
-- | --
Operating system: | iOS
Browser: | Safari
AdGuard version: | 1.3.1
Simplified filters (iOS only) | Off
AdGuard DNS: | None
Helpdesk ID (if exists): | 1480792

**Comment by AdamWr** [comment]
Ad leftover fixed.
I can't reproduce share bar.
