### ISSUE TITLE
AdGuard Security Filter

### ISSUE THREAD

**Issue by BranchS** [AdguardTeam/AdguardFilters#68868]
### Problem Description

There are native AdGuard Base, Tracking Prevention, Annoyances, and Social Media filters. Why no AdGuard Security filter? It would be nice to have a "one stop shop" for that category as we do for all the others.

### Proposed Solution

Create an AdGuard Security filter.

**Comment by annoying-anonim** [comment]
Идея хорошая, но труднореализуемая. Сомневаюсь, что разработчики за это возьмутся. Увы.

Да и к тому же. Встроенное подобие фильтра безопасности уже есть. Адгард и так блокирует вредоносные сайты, поэтому необходимости создания данного фильтра (в пределах экосистемы адгарда) нет. А создавать и разрабатывать целый фильтр для иных экосистем нецелесообразно.

Надеюсь, я ответил на ваш вопрос)

**Comment by Alex-302** [comment]
We have own safe browsing module.
