### ISSUE TITLE
Huawei

### ISSUE THREAD

**Issue by mariusz689** [AdguardTeam/AdguardFilters#68862]
I have the default AdGuard DNS filters on Mikrotik.
AdGuard DNS IP: 94.140.14.14
The problem is that the connection for the Huawei Inverter is blocked and the connection for the Fusionsolar application is blocked.
The problem does not occur when logging in to the account via the browser: https://eu5.fusionsolar.huawei.com/

I tried to solve the problem in this thread (but still the problem is not resolved): https://github.com/MajkiIT/polish-ads-filter/issues/17875

You can test it for yourself by downloading the FusionSolar application from the google store. In the application, enter a random username and password. A message about a problem with internet connection will be displayed if the AdGuard DNS filter is active. Otherwise, when the application works properly, a message with an incorrect username or password will be returned.

Could you please investigate the problem?

**Comment by zaba-monika** [comment]
Poprawka z mojej strony: tutaj jest issue tracker od DNS https://github.com/AdguardTeam/AdGuardSDNSFilter/issues

**Comment by krystian3w** [comment]
This is performacne issue with AdGuard DNS; generate lag - ping 20-60k ms (20-60 seconds) for comeback request from `103.235.46.39:443` (Baidu / `shifen.com`)

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardDNS #124](https://github.com/AdguardTeam/AdGuardDNS/issues/124) via [**ZenHub**](https://www.zenhub.com/)
