### ISSUE TITLE
Не работает штатный сервис issue 

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#68875]
Здравствуйте!
Не могу отправить issue через штатный сервис.
Такое появляется без использования VPN:
![Screenshot_20201129-185619](https://user-images.githubusercontent.com/75215990/100548861-ecc89f00-3277-11eb-912b-c1e878c12ca5.jpg)
А такое с VPN:
![Screenshot_20201129-185024](https://user-images.githubusercontent.com/75215990/100548889-429d4700-3278-11eb-9e16-7ccf823b7c71.jpg)

Все фильтры отключал. Даже адгард отключал. Не помогает...

**Comment by annoying-anonim** [comment]
Раньше VPN помогал отобразить капчу, а сейчас капча вообще не работает. Попробовал 3 VPN (Turbo VPN, Touch VPN, Betternet).

**Comment by krystian3w** [comment]
Maybe an overloaded site - it happens.

**Comment by krystian3w** [comment]
If some software blocks for you loading Google captcha, you have to clean your computers from malware and check if the routers have been hacked on your home network.

**Comment by annoying-anonim** [comment]
> If some software blocks for you loading Google captcha, you have to clean your computers from malware and check if the routers have been hacked on your home network.

Не, специально проверял на вирусы. Мало того, что у меня операционная система Linux, так еще и я проверял на разных сетях и на виртуалке. Может быть дело в том, что китайский фаервол снова химичит?

**Comment by annoying-anonim** [comment]
И на мобильных гаджетах тоже не работает reCAPTCHA. А остальные работают нормально. Хотя на моих андроидах стоит антивирус + я сижу через мобильный интернет + все скачиваемые файлы я проверяю на VIRUSTOTAL. Наверное региональный блок...

**Comment by annoying-anonim** [comment]
Хотя при использовании Tor через мосты всё отлично работает...

Хивр

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/ReportsWebApp #254](https://github.com/AdguardTeam/ReportsWebApp/issues/254) via [**ZenHub**](https://www.zenhub.com/)
