### ISSUE TITLE
Astra pro scripts get blocked by Adgaurd.

### ISSUE THREAD

**Issue by shubhw12** [AdguardTeam/AdguardFilters#68902]
Hello,

Greetings for the day!

I am Shubham from the Astra theme development team.

[Astra](https://wordpress.org/themes/astra/) is a WordPress theme and has more than 1 million active installations.

Astra Pro is our addon plugin which provides premium features to our pro customers.

We have been receiving queries from the users regarding the modules/functionality that we provide. These features do not work at all in case if the Adgaurd is active.

This is because to implement these features we use Javascript and it gets blocked by the Adgaurd.

Please see here: https://share.getcloudapp.com/BluQp0e7

Could you please let us know why the script is being blocked by Adgaurd?

This affects a lot of Astra users and we are receiving queries for the same.

Let us know if we can assist you to resolve this as soon as possible.

Looking forward to hearing back from you soon.

**Comment by murshed** [comment]
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_English/filter.txt
Need to remove this:
`astra-advanced-hook-`

TIA

**Comment by krystian3w** [comment]
https://share.getcloudapp.com/BluQp0e7 - EasyList: https://github.com/easylist/easylist/issues/6509

**Comment by Alex-302** [comment]
That rule was automatically removed from Base filter after one hour after changes in Easylist.
