### ISSUE TITLE
www.infranken.de - Newsletter - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6891]
***Description***:
* **Current behaviour**: 

Newsletter sign up:
http://www.infranken.de/ueberregional/nach-unfall-freund-von-unfallopfer-schlaegt-ersthelfer-zusammen-und-verletzt-ihn-schwer;art55462,2914961

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30778155-de688a3c-a0d6-11e7-89ea-81e352774cbc.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.47 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.42 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.9 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.20 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.61 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.64 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.60 Enabled=YES

Information | Value
-- | --
Operating system: | iOS
Browser: | Safari
AdGuard version: | 1.3.1
Simplified filters (iOS only) | Off
AdGuard DNS: | None
Helpdesk ID (if exists): | 1480792

**Comment by AdamWr** [comment]
Fixed.
