### ISSUE TITLE
drtuber.desi [Ads] [Pop-ups]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#68928]
https://www.drtuber.desi/video/4736574/big-ass-pornstar-hardcore-and-cumshot

Ads, pop-ups and ad text strings seen on the page. Please fix.

**Comment by Nzzyme** [comment]
Not fixed. Still seeing ad text on the player
![image](https://user-images.githubusercontent.com/6959116/101279722-2f472a00-37ea-11eb-8a99-cb63c19a66be.png)

**Comment by Alex-302** [comment]
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/101369898-7b10d680-38b1-11eb-9ef6-079df68bff87.png)

</details>
