### ISSUE TITLE
NSFW - free-sex-video.net - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6892]
***Description***:
* **Current behaviour**: 

Ad leftovers:
http://free-sex-video.net/video/omg-mums-kumpel-nimmt-alle-loecher-28892.html?utm_source=PB&utm_medium=CPC&utm_campaign=pbweb

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30778171-51e6ac78-a0d7-11e7-8831-489c83c423d3.png)

![image](https://user-images.githubusercontent.com/31481372/30778172-5ac77214-a0d7-11e7-89ff-8c531fca8ca7.png)

![image](https://user-images.githubusercontent.com/31481372/30778173-60dc8f5e-a0d7-11e7-95d6-5a9f0b6b5a80.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.47 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.42 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.9 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.20 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.61 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.64 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.60 Enabled=YES

Information | Value
-- | --
Operating system: | iOS
Browser: | Safari
AdGuard version: | 1.3.1
Simplified filters (iOS only) | Off
AdGuard DNS: | None
Helpdesk ID (if exists): | 1480792

**Comment by AdamWr** [comment]
Fixed.

**Comment by ashvets-sup** [comment]
The issue recurs. 
![image1](https://user-images.githubusercontent.com/32528702/31369349-7f549b22-ad8c-11e7-8a2f-04020d118bc1.jpeg)

**Comment by Alex-302** [comment]
Fixed.
