### ISSUE TITLE
Android 11 - App Gmail: no mail receipt and dispatch with strato servers when Adguard is active

### ISSUE THREAD

**Issue by RastoDE** [AdguardTeam/AdguardFilters#68937]
Hello,
I have a problem with the Gmail-App (Google) on Android 11.
With gmail-account no problems to receive and send mails.

But I use the Gmail-App also for mails of my own domains (on provider Strato). These accounts are using the Server imap.strato.de and Port 993 and SSL/TLS for receiving and Server smtp.strato.de and Port 465 and SSL/TLS for sending.
What could I do, that I Adguard can stay active while using the strato servers?

**Comment by Alex-302** [comment]
Could you please check with disabled filters and DNS filtering, but with enabled protection?
What status of HTTPS filtering for this app?(in Apps Managenent)

**Comment by RastoDE** [comment]
With disabled filters and DNS and also with disabled HTTPS (normally activated) I can't reveice/send mails.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #3679](https://github.com/AdguardTeam/AdguardForAndroid/issues/3679) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
@RastoDE Moved issue to Android repository.  The link is above.
