### ISSUE TITLE
NSFW - m.iceporn.com - Ads - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6895]
***Description***:
* **Current behaviour**: 

Ad leftover:
http://m.iceporn.com/video/2219439/young-german-blonde-amateur-filled-with-cum-at-home-pov

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30778224-b165ce44-a0d8-11e7-8fc9-d5119d6f65ad.png)

![image](https://user-images.githubusercontent.com/31481372/30778228-bf3f4888-a0d8-11e7-9171-e6654c2e5e7f.png)

![image](https://user-images.githubusercontent.com/31481372/30778230-c820b90a-a0d8-11e7-9266-8265157d48b6.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.47 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.42 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.9 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.20 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.61 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.64 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.60 Enabled=YES

Information | Value
-- | --
Operating system: | iOS
Browser: | Safari
AdGuard version: | 1.3.1
Simplified filters (iOS only) | Off
AdGuard DNS: | None
Helpdesk ID (if exists): | 1480792

**Comment by Alex-302** [comment]
@AdamWr

**Comment by AdamWr** [comment]
Fixed.
