### ISSUE TITLE
azcentral.com

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#68959]
||geolocation.1trust.app^

https://www.azcentral.com/story/news/politics/elections/2020/11/30/arizona-secretary-state-certify-election-results-monday/6444577002/

opened through facebook app and saw the tracker

**Comment by adranger** [comment]
Please don't paste direct links, or [site owners can see](https://en.wikipedia.org/wiki/HTTP_referer#Details) that people are accessing their pages through this repository and then change their code to break the Adguard filters.

You can use this to report issues instead: https://reports.adguard.com/en/new_issue.html

Or, if you prefer to keep opening issues manually on Github, add this as a [saved reply](https://github.com/settings/replies):

`[](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=)`

Then you can click on this icon to paste it:

![reply](https://user-images.githubusercontent.com/35470489/100677891-c162b480-334a-11eb-8759-01bfbf7f34af.png)

And add the URL you're reporting: `[https://www.example.org/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.example.org/)`. 

After doing this for the first time, it will take you just 1 extra second when you create new issues.

**Comment by jordanelliott23** [comment]
@adranger i wasn't aware of this. my apologies

**Comment by Alex-302** [comment]
Not tracking. But blocking can break sites.
