### ISSUE TITLE
chavesnamao.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#68972]
[https://www.chavesnamao.com.br/coberturas/pr-curitiba/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.chavesnamao.com.br/coberturas/pr-curitiba/)

![cookies](https://user-images.githubusercontent.com/35470489/100689887-1fe85c80-3364-11eb-99d0-248145f9d8c9.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by adranger** [comment]
@AdamWr  this annoyance is back. Changing the rule to `chavesnamao.com.br##div[class^="lgpd"]` fixes it.

**Comment by Alex-302** [comment]
Replaced.
