### ISSUE TITLE
Filter overreach - AdGuard Francais

### ISSUE THREAD

**Issue by Sphax84** [AdguardTeam/AdguardFilters#68985]
We detected that a rule in "AdGuard Francais" is overreach, blocking entirely YouTube from BDcraft.net

As shown here:
https://i.gyazo.com/fe03471b7a49d5f82eb1382a501a8380.png

Disabling the AdGuard Francais list makes it work again:
https://i.gyazo.com/6ec0b3315d5a5e20f50085227e6fa650.png

The rule is not blocking Ad but YouTube videos integrated in the BDcraft.net website...

The rule is:
`||www.youtube.com/iframe_api$script,domain=bdcraft.net`

**Comment by krystian3w** [comment]
Maybe autoplay is annoying, so blocked for all :fr: community.

**Comment by Sphax84** [comment]
BDcraft doesn't have autoplay videos and such (bad) filter is not present on english lists...

**Comment by smed79** [comment]
Added previously because of the use of revolving ad servers on download pages.

... removed now > https://github.com/easylist/listefr/commit/ba27e255b4079afea24d024a16e334921ae7f99a

**Comment by krystian3w** [comment]
@Sphax84 force update list after 1-3 hours in AdGuard.
