### ISSUE TITLE
www.freevintageposters.com - Incorrect ad blocking - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6900]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Incorrect blocking on page:
http://www.freevintageposters.com/p/poster-categories.html?m=1

Vintage advertising posters here are content, not ads.

Also, Adguard blocks that entire section of the site (URL for this screenshot is http://www.freevintageposters.com/search/label/advertising):

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30779209-fbefa222-a0f2-11e7-9af1-bb97b2ae9112.png)

![image](https://user-images.githubusercontent.com/31481372/30779210-08478c06-a0f3-11e7-9fd3-42eb6c05a961.png)

![image](https://user-images.githubusercontent.com/31481372/30779213-0e5de388-a0f3-11e7-8277-df452b00ca7a.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Browser:                            | Safari
AdGuard version:                    | 1.3.1.82
Filters enabled:                    | 0,2,3,4,12
Simplified filters (iOS only)       | Off
Helpdesk ID (if exists):            | 1446112

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added
```
@@||freevintageposters.com/search/label/advertising
```
