### ISSUE TITLE
youtube.com - tracking pixels

### ISSUE THREAD

**Issue by kfur** [AdguardTeam/AdguardFilters#6902]
***Description***:
YouTube load tracking pixels.
* **Current behaviour**: 
Loading pixels with such url:  https://www.youtube.com/yts/img/pixel-*.gif

***Steps to reproduce the problem***:
Load any youtube video.

***System configuration***
**Filters:**
English filter
Spyware filter
Social media filter
Annoyances filter
Russian filter
Safari filter

Information                         | Value
---                                 | ---
Operating system:                   |  macOS 10.13
Browser:                            | Safari
AdGuard version:                    | 2.6.5
Filters enabled:                    | 6

**Comment by Alex-302** [comment]
Not a tracker.
