### ISSUE TITLE
m.facebook.com - Missed pop-up

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6903]
https://m.facebook.com/facebook

Is it possible to block this pop-up?
The customer tried to use these rules to block it:
m.facebook.com###u_0_* (instead of m.facebook.com###u_0_x), but that doesn’t seem to work.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/30781039-a0c21410-a120-11e7-8cdc-24684e85c89e.png)

</details><br/>

***System configuration***

Application version: 1.3.1.107
Device: iPhone
Platform: iOS
OS: 11.0
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.31.32 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.62 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.42 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.66 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.79 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES

Helpdesk ID:          1609733

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Replaced by:
```
m.facebook.com###msite-pages-header-contents > div[class="_4b-b"][style]
```
