### ISSUE TITLE
www.youtube.com - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6904]
The user sees an ad in this video at a different time. No ads in incognito mode. The last time the ad appeared around 18:08-18:09.

https://www.youtube.com/watch?v=wPPVAeA4o5g&t=3s 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/30781291-2a65ad5e-a125-11e7-9066-4ba4a830f0eb.png)

</details><br/>

***System configuration***
  
[debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/1327180/debug.txt)
[state.txt](https://github.com/AdguardTeam/AdguardFilters/files/1327181/state.txt)

 Helpdesk ID: 1517203

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. Ask for HAR file
https://toolbox.googleapps.com/apps/har_analyzer/?lang=en

**Comment by veronikasav** [comment]
How can we get the HAR file from Safari?

**Comment by Alex-302** [comment]
I don't know. Maybe Safari can't do it.

**Comment by veronikasav** [comment]
What about this instruction?

http://help.catchsoftware.com/display/ET/Collecting+Browser+Performance+Information

**Comment by Alex-302** [comment]
Try it) I have no access to Safari at the moment.

**Comment by Alex-302** [comment]
@veronikasav
