### ISSUE TITLE
socketloop.com annoyance

### ISSUE THREAD

**Issue by ghajini** [AdguardTeam/AdguardFilters#6905]
***Description***: 
i see different behaviour of website when adguard is enabled and disabled on this website
* **Current behaviour**: 
content is hidden when adguard is enabled

* **Expected behaviour**: 
site should load content normally without ads

* **Screenshot with adguard enabled**:

https://image.prntscr.com/image/Y7qnfdzuRZer7YoAHfBLHQ.png

***Steps to reproduce the problem***:

going to 
https://www.socketloop.com/tutorials/how-to-show-different-content-from-website-server-when-adblock-is-detected
content is hidden

* **with adguard disabled webpage lookup like this normally**:

 https://image.prntscr.com/image/eqIsyY12TlC6kF8DqINhnw.png
 
 https://image.prntscr.com/image/qfW4zbjyTPql_CJL9K73Yw.png

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | windows 7
Browser:                            | chrome
AdGuard version:                    | Adguard AdBlocker 2.6.7
Filters enabled:                    | english filter,spyware filter

**Comment by Alex-302** [comment]
Remove ` from URLs

**Comment by vitalkanev** [comment]
And yeah I can reproduce in Xubuntu Zesty - Firefox 55 with the *same version(?)* of browser extension

**Comment by Alex-302** [comment]
@AdamWr

**Comment by AdamWr** [comment]
Fixed.
