### ISSUE TITLE
https://mail.ru/ - won't fully load on iOS11 with Adguard Pro DNS

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6906]
> Вчера обновился на ios11 и теперь некоторые сайты не загружаются, полоса загрузки начинает идти и останавливается, как пример сайт mail.ru. Только что проверил на другом айвон, где ios 10, проблемы нет вообще, все идеально, проблема на телефоне iPhone 6 plus.
> 
> Если vpn выключить и оставить только блокировку в сафари все летает мгновенно как и раньше, проблема именно тогда, когда включён vpn adguard.

![image](https://user-images.githubusercontent.com/15856304/30783099-4d9eea12-a146-11e7-9354-bd0e8473f21a.png)

***System configuration***

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.31.49 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.63 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.23.49 Enabled=YES
- ID=1 Name="Russian filter" Version=1.0.57.25 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES
- ID=15 Name="Simplified domain names filter" Version=1.0.2.34 Enabled=NO
- ID=116 Name="Wiltteri" Version=1.0.1.71 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS11
Browser:                            | Yandex, Safari
AdGuard version:                    | 1.3.1.107
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | Default
Helpdesk ID (if exists):            | 1474323 (with DNS logs)

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не повторяется.
@zebrum проверь на iOS 11

**Comment by evgeniy-ADG** [comment]
> Обновил свой второй телефон до ios 11(iPhone 6) и та же картина как и на моем телефоне, это не смертельно конечно и все же до обновления оба телефона работали идеально! Видимо проблема именно в dns.

- тот же пользователь. @zebrum

**Comment by Alex-302** [comment]
> Обновил свой второй телефон до ios 11
> Видимо проблема именно в dns.

странный вывод.

**Comment by zebrum** [comment]
в сафари все нормально

**Comment by veronikasav** [comment]
@Alex-302 на чем вы проверяли?

> попробуйте именно на iPhone 6 или 6 plus, я не думаю, что у меня телефоны особенные. В сафари конечно с включённым именно внутренним блокиратором все летает а вот если выключить его и оставить только фильтрацию по dns то та же картина как и в остальных без исключения браузерах, переставил все подряд и та же картина.

**Comment by Alex-302** [comment]
iPad, Safari в макоси.
