### ISSUE TITLE
https://metrika.yandex.by/ - unable to whitelist

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6907]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://metrika.yandex.by

> Столкнулся с проблемой в Яндекс метрике, добавление в белый список не помогает приходится полностью отключать расширение

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30783236-12558266-a148-11e7-8ad2-21b1887e0d13.png)

</details><br/>

***Steps to reproduce the problem***:

1. Через личный кабинет зохожу, https://metrika.yandex.by/dashboard?group=day&period=week&id=42962454
2. Включаю ваше расширение во вкладке расширения https://yadi.sk/i/Fla2RfEB3N93Vr 
3. Adguard Антибаннер 2.6.7 Хром Версия 61.0.3163.100 

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome 
AdGuard version:                    | 2.6.7 
Filters enabled:                    | English, Russian, Spyware, Social media
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1632165

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Ничего подобного на сайте метрики не вижу. У тебя повторяется?

**Comment by evgeniy-ADG** [comment]
Нет, у меня нет сайтов и нет счетчиков, чтобы воспроизвести. Просить доступ?

**Comment by Alex-302** [comment]
Доступ, или хотя бы нормальное описание.
