### ISSUE TITLE
openload.co - Missed ad - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6908]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Missed ad on page:
https://openload.co/f/Tlk3fCN5OhI/Agatha.Christie.Poirot.S12E01.HDTV.XviD-SFM.mp4

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://uploads.adguard.com/dzruq.png)
</details><br/>

**Filters:**
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.31.52 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.63 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.50 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.72 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.57.26 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.79 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES
ID=103 Name="Bulgarian list" Version=1.0.0.17 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.88.7 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
AdGuard version:                    | 1.3.1.107
Simplified filters (iOS only)       | Off
Helpdesk ID (if exists):            | 1147641

**Comment by Alex-302** [comment]
Not reproduced on my device with iOS 10.
@zebrum please check on 10 and 11

**Comment by zebrum** [comment]
reproduced on iOS 10

**Comment by Alex-302** [comment]
On my device it is hidden by
```
openload.co###mgiframe
```
and blocked by
```
||mg.mgid.com^$domain=openload.co
```

**Comment by AdamWr** [comment]
I can't reproduce on iOS 11.

**Comment by zebrum** [comment]
me neither
