### ISSUE TITLE
Antiadblock in yasss.es and uppers.es

### ISSUE THREAD

**Issue by PIZZA90** [AdguardTeam/AdguardFilters#69084]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

Anti-Adblock in:

```
https://www.uppers.es/
https://www.yasss.es/
```

[//]: # (Substitute this line with a description of the problem)

This filter in **spa, por: AdGuard Spanish/Portuguese**: 

`radioset.es,bemad.es,cuatro.com,divinity.es,eltiempohoy.es,energytv.es,factoriadeficcion.com,mtmad.es,telecinco.es##div[class^="adsInfo__container"]`

**Updating filter with two new domains**:

`uppers.es,yasss.es,radioset.es,bemad.es,cuatro.com,divinity.es,eltiempohoy.es,energytv.es,factoriadeficcion.com,mtmad.es,telecinco.es##div[class^="adsInfo__container"]`

**Comment by AdamWr** [comment]
Added, but to be honest I couldn't reproduce it.
Update should be available in 1-2 hours.

Thank you.
