### ISSUE TITLE
http://bash.im/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6909]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: http://bash.im/

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30783810-f0019d58-a151-11e7-8e49-97adf321f3d6.png)

</details><br/>

***System configuration***

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.31.50 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.63 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.23.50 Enabled=YES
- ID=1 Name="Russian filter" Version=1.0.57.26 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.79 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS11
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1633999

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Проверь на ios 10. У меня чисто.

**Comment by evgeniy-ADG** [comment]
У меня нет iOS 10.

**Comment by zebrum** [comment]
на iOS 10 не повторяется.
