### ISSUE TITLE
[nsfw] paradisehill.cc

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6910]
**Site Sample** | 
----|
http://en.paradisehill.cc/irresistible_silvie/

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Opera Stable
AdGuard version:                    | **6.2.400.2059**
Stealth mode: | **enabled**

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

Stealth mode options enabled |
---------------------|
`hide search passwords ** send Do-Not-Track header ** remove X-Client-Data header ** remove tracking data from urls ** self-destroying third-party cookies  ** disable third-party request cache  ** block API browser (except flash) ** hide refferer against third-party ** hide user-agent header ** hide IP address`

### Screenshot
![2017-09-24 17_27_10-porn film online _ irresistible silvie opera](https://user-images.githubusercontent.com/9846948/30784040-a2109bd4-a14d-11e7-8251-82b7705a39e9.png)

### Fix
Blocking whole main ad domain
```
||webcampromo.com^
```

**Comment by Alex-302** [comment]
fixed.
