### ISSUE TITLE
http://fanfics.me - unable to whitelist

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6911]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: http://fanfics.me
Shows placeholders instead of actual ads.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30784291-39059e38-a15b-11e7-83b3-69dadc92c2b6.png)

</details>

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10
Browser:                            | chrome 61
AdGuard version:                    | beta 6.2
Filters enabled:                    | English, Russian, Social media, Annoyances, Apyware
AdGuard DNS:                        | None 
Stealth mode options (Windows only) | Off
Helpdesk ID (if exists):            | 1633190

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
not reproduced. Try to select it bu blocking tool

**Comment by evgeniy-ADG** [comment]
I can't select it by the blocking tool as there's no such option when the site is whitelisted. If it's not whitelisted, I can't see the placeholder.

**Comment by Alex-302** [comment]
I see ads when the site is in exclusions

<details>

![image](http://imagizer.imageshack.com/img924/8534/ZN6pVB.jpg)
</details>
