### ISSUE TITLE
mathwarehouse.com - uponit circumvention

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#6912]
Here is the website:
http://www.mathwarehouse.com/trigonometry/radians/s=r-theta-formula-equation.php

It seems we need more $network rules:
```
138.68.69.59$network
138.197.183.69$network
```

**Comment by AdamWr** [comment]
Fixed in https://github.com/AdguardTeam/AdguardFilters/commit/a0e019407bc8dba9f47b9669d5d89d1132d2cb5f
