### ISSUE TITLE
kinogo.life - Реклама  - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6913]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Некорректная блокировка на странице:
http://kinogo.life/smotret-online/igra_prestolov_sezon_3_2013_720_hd/2016-10-21-58

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![screen shot 2017-09-24 at 8 41 05 pm](https://user-images.githubusercontent.com/31481372/30785052-d9b1f8ec-a168-11e7-95d0-fcdc03822d13.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.31.53 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.63 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.50 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.57.26 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
AdGuard version:                    | 1.3.1.82
Simplified filters (iOS only)       | Off
Helpdesk ID (if exists):            | 1634198

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Баг iOS. Пока не исправят - баннер не убрать. Таймер на iOS не убрать в принципе.
