### ISSUE TITLE
m.pikabu.ru - Блокирует страницу - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6914]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Блокирует страницу https://m.pikabu.ru/story/naruzhnaya_reklama_5361880

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

 
![image](https://user-images.githubusercontent.com/31481372/30785638-99d78408-a172-11e7-9c44-70d337481c39.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.31.49 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.63 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.49 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.57.25 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Browser:                            | Safari
AdGuard version:                    | 1.3.1.107
Simplified filters (iOS only)       | On / Off
AdGuard DNS:                        | Default 
Helpdesk ID (if exists):            | 1609609

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
added
```
@@||m.pikabu.ru/story/*_reklama_
```

**Comment by iverkhohliad** [comment]
Пользователь пишет, что страница все ещё недоступна. С той же ошибкой.

**Comment by Alex-302** [comment]
У тебя повторяется?

**Comment by evgeniy-ADG** [comment]
У меня - не повторяется. iOS 11 тоже. Попросил фильтр вручную добавить.

**Comment by Bohdan-SUP** [comment]
@Alex-302 
>Не помогло. Только ручное внесение не приводит к блокировке. Сейчас обнаружил ситуацию, когда не происходит блокировки при отсутствии в собственном фильтре. После попытки обновления - блок.

<details>

![pikabu](https://user-images.githubusercontent.com/14153331/31025172-32a47c7e-a54a-11e7-8860-5f5ebe462bb3.gif)

</details>

**Comment by zebrum** [comment]
reproduced

**Comment by Alex-302** [comment]
@zebrum please make screenshot of iOS console(remote debugging)

**Comment by zebrum** [comment]
that's it: ![screenshot 2017-10-04 13 52 56](https://user-images.githubusercontent.com/23637588/31172213-5c9c49de-a90b-11e7-9798-4782d9c8e8f3.png)

**Comment by Alex-302** [comment]
The rule moved from mobile to Eng filter.
