### ISSUE TITLE
novy.tv - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#6915]
http://topmodel.novy.tv/ru/videos/episode/top-model-po-ukrainski-smotret-onlayn-vyipusk-1-chast-1/

Missed video ads

![image](https://user-images.githubusercontent.com/22892774/30815726-b2db6cda-a21c-11e7-9946-b93994d1efc5.png)

Information                         | Value
---                                 | ---
Operating system:                   | Mac
Browser:                            | Chrome
AdGuard version:                    | 1.5.0
Filters enabled:                    | 1 2 3 4 14

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
