### ISSUE TITLE
gismeteo.ru - Missed ads

### ISSUE THREAD

**Issue by vitalkanev** [AdguardTeam/AdguardFilters#6916]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:  Вся реклама не блокируется  на этом сайте
* **Current behaviour**: Пока что есть реклама

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![adsidei](https://user-images.githubusercontent.com/18398761/30817174-c37868f0-a220-11e7-8f26-75101bde1c3c.png)

</details><br/>
Сайт, где это увидел: https://www.gismeteo.ru/weather-syktyvkar-3989/

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Linux - Xubuntu Zesty
Browser:                            | Firefox 55
AdGuard version:                    | 2.6.7 Browser Extension
Filters enabled:                    | English, Annoyances, Russian, German, EasyList,<br/>Ru ADList
Helpdesk ID (if exists):            | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Поправил. Обновление будет доступно через час.
