### ISSUE TITLE
Реклама http://poisk-istini.com/filosofija-prava/metodi-filosofii-prava

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#6917]
Фильтры по-умолчанию, версия последняя стабильная, HTTPS, HTTP вкл, качественная.
Логи не делал, глянь так. При переходе появляется баннер http://poisk-istini.com/filosofija-prava/metodi-filosofii-prava

**Comment by ministr91** [comment]
Если не найдешь баннер, пришлю логи

**Comment by Alex-302** [comment]
Скриншот.

**Comment by ministr91** [comment]
Не могу, проблема пропала( , но я точно помню, что она была вчера вечером

**Comment by ministr91** [comment]
Закрою тему временно

**Comment by ministr91** [comment]
Короче, я не понимаю что происходит, но через вай фай рекламы нет, через 4g полезла. 18:22 вторник @Alex-302 и @ameshkov http://my-files.ru/ckeg2j
![screenshot_2017-10-10-18-22-20](https://user-images.githubusercontent.com/22351242/31395000-fd6852c6-addf-11e7-85cf-53c6e17e4aa3.png)

**Comment by ministr91** [comment]
Версия 2.9.136

**Comment by Alex-302** [comment]
HAR пиши.

**Comment by ministr91** [comment]
я писал

**Comment by ministr91** [comment]
я скинул тебе хар лог

**Comment by ministr91** [comment]
будь внимательнее
![default](https://user-images.githubusercontent.com/22351242/31401868-e53780ec-adfc-11e7-92ea-0a3a1e4ca916.jpg)

**Comment by ministr91** [comment]
можешь метку поменять? Инвалид как-то не очень

**Comment by ministr91** [comment]
что вообще эта метка означает?

**Comment by ministr91** [comment]
@Alex-302 что случилось? Зачем закрыл и открыл?

**Comment by ministr91** [comment]
Я тоже так могу : D

**Comment by ameshkov** [comment]
> Короче, я не понимаю что происходит, но через вай фай рекламы нет, через 4g полезла

Потому что они детектят мобильную связь и автоматически редиректят на подписки. Вряд ли это получится заблокировать
