### ISSUE TITLE
livejournal.com - Missed Add on iOS

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardFilters#6918]
missed ads on livejournal.com

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image1](https://user-images.githubusercontent.com/30834067/30832133-ae71c17c-a252-11e7-85e2-1b1056eda731.png)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                              | Safari
Filters enabled:                    | 1,11,12,14
Helpdesk ID (if exists):            | 1634151

**Comment by Alex-302** [comment]
Can't reproduce. Is it on the main page?
