### ISSUE TITLE
yushuwu.com

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardFilters#6919]
https://m.yushuwu.com/novel/54057/7007551.html

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image1 1](https://user-images.githubusercontent.com/30834067/30833452-c86864b4-a257-11e7-804f-4ac668de17bf.png)

Information                         | Value
---                                 | ---
Operating system:                   | iOS 10.3.3
Browser:                            | Safari
AdGuard version:                    | 1.3.1.82
Filters enabled:                    | 1,2,3,5,10,11,12,14,15,104,219
Helpdesk ID (if exists):            | 1633616

**Comment by Alex-302** [comment]
Added:
```
||wxbdfm.com^$third-party
||htyfmm.com^$third-party
||ruifeng99.com^$third-party
||97kuaixiu.com^$third-party
||70yst.com^$third-party
```
