### ISSUE TITLE
Mobile version of https://swgoh.gg/ 

### ISSUE THREAD

**Issue by Mizzick** [AdguardTeam/AdguardFilters#6921]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
Mobile version of https://swgoh.gg/ has huge white block in place of removed ads.

<details><summary>Screenshot:</summary>

![2017-09-26 20 45 02](https://user-images.githubusercontent.com/13855288/30875438-34e31b80-a2fc-11e7-86cf-4eaa9c83aeb3.png)

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)
English, Spyware, Social ads, Russian, Mobile Ads

[//]: # (Please enter the correct values for your case to the table below)

AG for Android 2.9

**Comment by Alex-302** [comment]
Added to English filter
```
swgoh.gg##.ad-item
swgoh.gg##.sw-ad-mrec
swgoh.gg##.sw-ad-row
```

**Comment by Mizzick** [comment]
Thanks guys, my fried will appreciate :)
