### ISSUE TITLE
http://soft-web-free-sub.site/ - Missed ad - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6924]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Missed ad on page:

https://soft-web-free-sub.site/36caad8a-3790-4fc7-abf7-6cec47e29b6f/308fdf5c-c4e6-4fcd-a6f3-31b7833a4aa4/?contype=BROADBAND&device=MOBILE&osversion=IOS%2010.2&os=IOS&browser=Mobile%20Safari&lang=&isp=Qwest%20Communications%20Company%20Llc&country=US&city=Los%20Angeles&useragent=Mozilla%2F5.0%20%28iPhone%3B%20CPU%20iPhone%20OS%2010_2_1%20like%20Mac%20OS%20X%29%20AppleWebKit%2F602.4.6%20%28KHTML%2C%20like%20Gecko%29%20Version%2F10.0%20Mobile%2F14D27%20Safari%2F602.1&ip=67.128.243.131&brand=Apple&model=iPhone&voluumdata=BASE64dmlkLi4wMDAwMDAwNy03OGYxLTQ1NzQtODAwMC0wMDAwMDAwMDAwMDBfX3ZwaWQuLjQxZTQxODAwLWEyNDUtMTFlNy04NGRlLWE5YzdiODg5NDE1Y19fY2FpZC4uZTE2NjZhZjMtMjVkNi00OWVhLThlNDEtZDljOTllMmQ0ZTI2X19ydC4uREpfX2xpZC4uMjk2NDZmYzgtODE4Mi00OGJlLTllY2EtNDEyMGI2MjdlNmJjX19vaWQxLi5jMmFhMWMyOS03NGQzLTQ1MmEtODc5Ni1lYzdiZDU4MjRmN2VfX3ZhcjEuLjE1Mzc1X19yZC4uX19haWQuLl9fYWIuLl9fc2lkLi5fX3NwaWQuLl9fY3JpLi5fX3B1Yi4uX19kaWQuLl9fZGl0Li5fX3BpZC4uX19wZWlkLi5fX2l0Li5fX3Z0Li4xNTA2MzgzNTI2Mjc2&subid=22d90e41c7269e0e1a6392d3b08c16da&siteid=15375

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![screen shot 2017-09-27 at 1 33 45 am](https://user-images.githubusercontent.com/31481372/30888547-be9f498e-a329-11e7-9ba4-a0b92f93f604.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.31.72 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.66 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.55 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 10.2.1
AdGuard version:                    | 1.3.1.82
Simplified filters (iOS only)       | Off
Helpdesk ID (if exists):            | 1635440

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I need a source page.
