### ISSUE TITLE
www.ouest-france.fr - Missed ad - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6925]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

1) Auto play video ad 
2) « sponsored content »

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30888718-b8ac3b76-a32a-11e7-851c-d536f6604404.png)

![image](https://user-images.githubusercontent.com/31481372/30888724-bda5039c-a32a-11e7-8fb6-9fe7ed831e20.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.21 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.37 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.99 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.4 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.58 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES
ID=101 Name="EasyList" Version=1.0.75.26 Enabled=YES
ID=113 Name="Liste FR" Version=1.0.87.20 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.87.17 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Browser:                            | Safari
AdGuard version:                    | 1.3.1.82
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None / Default / Family Protection
Helpdesk ID : | 1635257

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. I need a direct url of that page.
User can disable `EasyList` and replace `Liste FR` by AdGuard's `French filter`

**Comment by Coldorak** [comment]
Hello 

URL was https://www.ouest-france.fr/leditiondusoir/data/9468/reader/reader.html?t=1506356415948#!preferred/1/package/9468/pub/13343/page/12/phone/

I’ve applied the changes you suggested and tried again: page is clean now, thank you!

Best regards,

Christophe

**Comment by Alex-302** [comment]
Ok, thanks)
