### ISSUE TITLE
miniwebtool.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#69268]
[https://miniwebtool.com/remove-lines-containing/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://miniwebtool.com/remove-lines-containing/)

`#adsbottom,#btop`
`.icon-bar`

![sharing](https://user-images.githubusercontent.com/35470489/101203449-6df1ae80-3649-11eb-9c41-85a739610e4c.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by Alex-302** [comment]
@adranger In uBO Easylist must me enabled, because it is not included to uBO version of Base filter.
