### ISSUE TITLE
http://dlisted.com/ - Pop up - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6926]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Pop up in the bottom right corner

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30889247-c1b9f084-a32d-11e7-938e-48200dd3959a.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.31.75 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.66 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.56 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.83 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Browser:                            | Safari
AdGuard version:                    | 1.3.1.82
Simplified filters (iOS only)       | Off
Helpdesk ID (if exists):            | 1635784

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
We can't do it. Main video will be hidden.
