### ISSUE TITLE
https://m.lenta.ru/ - Missed ad - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6927]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Missed ad on page

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30889314-3ef5fc1e-a32e-11e7-8d27-45d337aaf9bc.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.31.51 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.63 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.50 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.57.26 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Browser:                            | Safari
AdGuard version:                    | 1.3.1.107
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | Default 
Helpdesk ID (if exists):            | 1593418

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. URL?

**Comment by syabro** [comment]
@Alex-302 урл в заголовке
Проблема в том что я вижу рекламу везде, не только на ленте.
Я отправил штук 5 багрепортов — тут вижу только один

**Comment by Alex-302** [comment]
На главной такого баннера не вижу. Но на iOS тут ничего особо не поделаешь, без правил JS не обойтись, блокировщик в Сафари для iOS - ущербный и не сравним даже с браузерными расширениями для десктопных браузеров(Адгард для Сафари всего лишь скармливает ему готовые фильтры, а блокировкой занимается сам браузер).

**Comment by Alex-302** [comment]
Описанные трудности - не на всех сайтах.

**Comment by syabro** [comment]
У меня на всех сайтах реклама. Т.е. официальное заявление — мы не работаем под iOS?

**Comment by Alex-302** [comment]
Если на всех - то проблема локальна, нужно настройки проверить. Может из-за iOS 11. У меня только 10.
> Т.е. официальное заявление — мы не работаем под iOS?

на iOS некоторую рекламу просто невозможно заблокировать, т.к. имена элементов шифруются. Apple предоставляет возможности двадцатилетней давности - скрыть и заблокировать. Применить CSS, JS, правила замены контента и вырезания здесь невозможно. На десктопном сафари получше.

**Comment by syabro** [comment]
окей :(

**Comment by Alex-302** [comment]
Попробуйте выключить все фильтры и включить их снова, переключить в расширенных настройках `Оптимизированные фильтры`. Может что-то заклинило и фильтры не собрались как следует.
