### ISSUE TITLE
thepiratebay.org - Domain blocked - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6928]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Domain https://thepiratebay.org/ blocked on both iOS and Safari extensions

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30889911-30352c6e-a332-11e7-81f1-a41cf918ea2f.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.31.49 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.63 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Browser:                            | Safari
AdGuard version:                    | 1.3.1.82
Simplified filters (iOS only)       | Off
Helpdesk ID (if exists):            | 1633875

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed,
