### ISSUE TITLE
market.yandex.ru - Ads - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6929]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Некорректная блокировка на странице:
https://market.yandex.ru/?lr=0&rtr=213
https://market.yandex.ru/catalog/54778?hid=90607&lr=0&track=menuleaf

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/30890432-99096856-a335-11e7-9bd7-565ff7dc7611.png)

![image](https://user-images.githubusercontent.com/31481372/30890440-a091f5b6-a335-11e7-84f1-4e645f9fa80f.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.31.52 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.63 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.50 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.72 Enabled=YES
ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.17 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.57.26 Enabled=YES
ID=5 Name="Experimental filter" Version=1.0.26.67 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.79 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 9.0.2
AdGuard version:                    | 1.3.1.107
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | 1611923

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. All images are loaded.
