### ISSUE TITLE
Коспетенуия

### ISSUE THREAD

**Issue by Adguarder** [AdguardTeam/AdguardFilters#6931]
Ваше по блокирует только рекламу и счетчики и кнопки соцсетей

А как насчёт добавления в основной фильтр всяких майнеров? Чтобы не загружали систему
Пока не нашёл таких сайтов но на pirate bay и правда начинает жужжать

**Comment by Alex-302** [comment]
блокируем их, но не везде, т.к. не реклмама,  и сценарий приличного использования у них есть в документации

**Comment by Adguarder** [comment]
vse.fm
тут майнер сейчас нашёл

**Comment by Alex-302** [comment]
поправил
