### ISSUE TITLE
hk.mobi.yahoo.com -- unable to load next page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#6933]
Only the first page is loaded, auto-loading of the next pages are broken:
https://hk.mobi.yahoo.com/news

<details><summary>Screenshot:</summary>

![image](https://uploads.adguard.com/up04_3eabc_Yahoo_.png)
</details><br/>

* **Expected behaviour**: 
Next page should be automatically loaded when you scroll it down.

**Comment by AdamWr** [comment]
Added:
`@@||yimg.com/ud/fp/*/js/Ads.*.min.js$domain=hk.mobi.yahoo.com`
