### ISSUE TITLE
rg.ru - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6934]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behavior**: The customer states that 2.9 blocks ads, 2.10.x beta, in contrary, does not. The logs and HAR are available in the support ticket. Refuses to enable the HTTPS filter as "it doesn't help". 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30906097-74fdf05e-a37f-11e7-8b75-e88eeeb1c3c5.png)

![image](https://user-images.githubusercontent.com/15856304/30906102-7903df06-a37f-11e7-9795-89bc151e8a43.png)

</details><br/>

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Android
Browser:                            | Yandex
HTTPS filtering: | Off
Filtering method: | HQ
Filtering mode: | VPN
AdGuard version:                    |  2.10.94
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1630774

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by evgeniy-ADG** [comment]
too fast, will reopen if needed.

**Comment by altokarev** [comment]
@evgeniy-ADG Check this checkmark pls:
<details><summary>Screenshot:</summary>

![screenshot_20170927-151657](https://user-images.githubusercontent.com/28726429/30913146-ccbcbbbe-a397-11e7-8fd7-71a8b36365c7.png)

</details>

**Comment by altokarev** [comment]
And tell user that **rg.ru** uses `https://` so we can't filter it without enabling HTTPS filtering.

Offer him to use DNS filtering in case he refuses to use HTTPS filtering, but it works with lesser efficiency though.

**Comment by evgeniy-ADG** [comment]
We've already been through all this. Thanks anyway.
