### ISSUE TITLE
https://eksisozluk.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6935]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://eksisozluk.com/

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30913537-40b1a60a-a399-11e7-8073-dba178d39932.png)

</details><br/>

***System configuration***

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.31.47 Enabled=YES
**- ID=3 Name="Spyware filter" Version=1.0.14.63 Enabled=YES - most likely this one is the culprit**
- ID=14 Name="Annoyances filter" Version=1.0.18.70 Enabled=YES
- ID=13 Name="Turkish filter" Version=1.0.9.46 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.79 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES
- ID=101 Name="EasyList" Version=1.0.75.58 Enabled=YES
- ID=118 Name="EasyPrivacy" Version=1.0.87.81 Enabled=YES
- ID=123 Name="Fanboy's Social Blocking List" Version=1.0.75.58 Enabled=YES
- ID=122 Name="Fanboy's Annoyances" Version=1.0.75.78 Enabled=YES
- ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.5.9 Enabled=YES
- ID=207 Name="Adblock Warning Removal List" Version=1.0.88.2 Enabled=YES
- ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | Default 
Helpdesk ID (if exists):            | 1632531

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't reproduce.
Try to disable
```
ID=101 Name="EasyList" Version=1.0.75.58 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.87.81 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.75.58 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.75.78 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.5.9 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.88.2 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES
```
EasyList is unnecessary, when English filter is enabled.

**Comment by evgeniy-ADG** [comment]
I can't, too. This has already been suggested, the customer replied that he tried turning them off one by one and came to the conclusion that it's the Spyware filter causing the issue.

**Comment by Alex-302** [comment]
Does user have MacOS?
