### ISSUE TITLE
chroniclelive.co.uk - Annoyance - Social widgets - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6939]
***Site***: http://www.chroniclelive.co.uk/news/north-east-news/scary-watch-confused-driver-go-13682053
***Description***: Social share buttons, ad leftover, cookie notice at the bottom and newsletter sign up.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/30919853-dfcc2428-a3a2-11e7-91eb-ff48438a0bb4.png)

![image](https://user-images.githubusercontent.com/10995998/30919945-1109aed4-a3a3-11e7-8844-699a387f4f65.png)

![image](https://user-images.githubusercontent.com/10995998/30920013-3a08db98-a3a3-11e7-8623-7f135354487b.png)

![image](https://user-images.githubusercontent.com/10995998/30920033-47837210-a3a3-11e7-8dc8-2120cfefd1ee.png)

![image](https://user-images.githubusercontent.com/10995998/30920060-55b80f62-a3a3-11e7-8913-433f1e930bd2.png)

![image](https://user-images.githubusercontent.com/10995998/30920100-716eb3fa-a3a3-11e7-8e70-7f755d661c97.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
