### ISSUE TITLE
Discord typing indicator is blocked by the Spyware filter; poses risk to account on the service.

### ISSUE THREAD

**Issue by KJP12** [AdguardTeam/AdguardFilters#69407]
***Description***: Discord typing indicator is blocked, posing a risk for those who legitimately uses Discord along with any in-browser or proxy adblocker with the AdGuard Tracking Protection/Spyware filter enabled.

* **The risk for those using this filter**:
Client modifications are banned by [Discord's Terms of Service § Rights to use the service](https://discord.com/terms#app-mount:~:text=You%20agree%20not%20to%20%28and%20not,as%20expressly%20permitted%20in%20these%20Terms). (If that link breaks, try https://dis.gd/terms and scroll down.)
As such, by having AdGuard-Spyware present, one risks their account getting banned from any server, or from the service itself, for reason of client modding just by unknowingly having this filter present.
*This filter is different from other cosmetic or 'science endpoint' filters that may be present here, as this one blocks an endpoint that fires an event that may be seen by Discord, and any user and bot viewing the channel at the time. This event never being fired before any messages consistently may mark the account as suspicious for potential client modding.*

* **Current behaviour**: 
The typing indicator is never sent to Discord when one types a message.

<details><summary>Screenshot:</summary>

![uBlock Origin Logger](https://user-images.githubusercontent.com/8528256/101284237-d51b7a00-3793-11eb-8ba2-84abe2bdf0d9.png)
![Chromium DevTools](https://user-images.githubusercontent.com/8528256/101284277-01cf9180-3794-11eb-9223-ce186b0f30e8.png)
*By nature, there isn't one that can be presented from within Discord itself.*
</details><br/>

* **Expected behaviour**: 
The typing endpoint to be fired and sent to Discord.

<details><summary>Screenshot:</summary>

![Expected](https://user-images.githubusercontent.com/8528256/101284201-a4d3db80-3793-11eb-8e2f-8bac7c1db910.png)
</details><br/>

***Steps to reproduce the problem***:
With any adblockers compatible with the Adblock Plus 2.0 syntax...
1. Enable AdGuard Tracking Protection / AdGuard Spyware / Manually import the spyware text file from https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/specific.txt.
2. Visit Discord in browser in either the [stable](https://discord.com/app), [PTB](https://ptb.discord.com/app), or [canary](https://canary.discord.com/app) channels.
3. Go to any text channel and start typing.
Note how in DevTools or your adblocker's logger that the endpoint fails, usually for 'blocked by client'.
If you're on another account in the channel you've typed in, you may also observe that the typing indicator was never sent.

***Extra Details***:
This issue has been introduced in commit 061ed5a4cc94486a0ae61fa253565fe98d41f178 to fix #67934.
The offending line still resides in the filter at [line 36 of specific.txt for the spyware filter.](https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/specific.txt#L36)

***System configuration***

**Filters:**
At time of discovery: uBlock filters, uBlock filters - Badware risks, uBlock filters - Privacy, uBlock filters - Resource abuse, uBlock filters - Unbreak, AdGuard Base, Adguard Mobile Ads, EasyList, AdGuard Tracking Protection, EasyPrivacy, Fanboy's Enhanced Tracking List, Online Malicious URL Blocklist, Spam404, AdGuard Annoyances, AdGuard Social Media, Anti-Facebook, EasyList Cookie, Fanboy's Annoyance, Fanboy's Social, uBlock filters - Annoyances, Dan Pollock's hosts file, MVPS HOSTS, Peter Lowe's Ad and tracking server list, manually added filters and rules.

Isolated to AdGuard Tracking Protection, as seen by the logger built into uBlock Origin.

Information                            | Value
---                                    | ---
Operating system:                      | Arch Linux
Operating system version (Android/iOS) | Rolling release Linux distribution; there is no version.
Browser:                               | Chromium 87.0.4280.66 (Official Build) Arch Linux (64-bit)
AdGuard version:                       | uBlock Origin 1.30.6 with AdGuard-Spyware 2.0.18.92
Filters enabled:                       | See the Filters section above.
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | None

**Comment by Alex-302** [comment]
Hi. That was a mistake. Removed.
