### ISSUE TITLE
nrk.no

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#69425]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

A scorebox widget fails to load due to `||js.pusher.com^$third-party` in [AdGuard Annoyances Filter's anti-push-notification section](https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/sections/push-notifications.txt).

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/101290361-fd41c200-3801-11eb-8202-1046c8fbd876.png)
</details><br/>

* **Expected behaviour**: 

The scorebox widget is loaded properly.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/101290384-29f5d980-3802-11eb-8e27-ac016172664e.png)
</details><br/>

***Steps to reproduce the problem***:

1) Add https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/sections/push-notifications.txt as a custom list.
2) Turn Dandelion Sprout's Nordic Filters off, because it contains a temporary fix.
2) Go to `https://www.nrk.no/sport/norge-og-mork-bottet-inn-mal-mot-tyskland_-_-ingen-andre-er-i-naerheten-1.15276045`

***System configuration***

**Filters:**

![image](https://user-images.githubusercontent.com/22780683/101290393-3c701300-3802-11eb-9bbb-7cf1995986b4.png)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 20H2
Browser:                               | Chrome 87.0.4280.88 x64
AdGuard version:                       | uBO 1.31.2b2 + IDCAC 3.2.6
Filters enabled:                       | See screenshot above
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by THEtomaso** [comment]
### Additional issue:
NRK's analytics scripts should be blocked.
Besides `https://www.nrk.no/`, their scripts are also present on other sites, like `https://www.yr.no/`.

### Examples:
`https://static.nrk.no/core-analytics/major/4/statistics/analytics.min.js`
`https://static.nrk.no/core-analytics/major/5/core-analytics.min.js`

### Possible fix:
`||nrk.no^*analytics*$script`
