### ISSUE TITLE
overclockers.ru -  Missed ad, no assisatant

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6943]
https://www.overclockers.ru/
<details><summary>Screenshot:</summary>

<img width="1340" alt="screen shot 2017-09-28 at 1 51 21 am" src="https://user-images.githubusercontent.com/27292111/30941720-91d89a4c-a3ef-11e7-919a-b267ea2b6097.png">

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | 6.1
Filters enabled:                    | 2 3 4 1
Helpdesk ID (if exists):            | 1633678

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Check HTTPS filtering on this site.
