### ISSUE TITLE
mercola.com false positive

### ISSUE THREAD

**Issue by shape55** [AdguardTeam/AdguardFilters#69442]
The entire top section of Mercola.com which contains the logo, search bar, and Sign In & Join buttons is being blocked.  Disabling AdGuard allows it to load normally.  This happens with the Firefox add-on, but there is no issue w/ the Safari extension using the same filters.  If you can’t reproduce it I’ll upload a screenshot.

• Enabled filters: AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, EasyPrivacy, Fanboy's Enhanced Tracking List, AdGuard Social Media filter, AdGuard Annoyances filter, Fanboy's Annoyances, Web Annoyances Ultralist, Adblock Warning Removal List, I don't care about cookies, Online Malicious URL Blocklist, Spam404, NoCoin Filter List, Filter unblocking search ads and self-promotion, AdGuard German filter, AdGuard Spanish/Portuguese filter

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | macOS Catalina
Operating system version: | 10.15.7
Browser:                               | Firefox 83.0
AdGuard version:                       | 3.5.23
AdGuard DNS:                           | Default

**Comment by Alex-302** [comment]
@shape55 Screenshot, please. 
Try to disable Web Annoyances Ultralist

**Comment by Alex-302** [comment]
@yourduskquibbles 
`mercola.com#@$#.mm-slideout.header { position: relative !important; top: 0 !important; }`

![image](https://user-images.githubusercontent.com/8361299/101395985-5a597880-38d3-11eb-8a05-11a9ba5e0dfe.png)

**Comment by yourduskquibbles** [comment]
@Alex-302 Thx for tagging, should be fixed now.

**Comment by shape55** [comment]
Yes, it loads normally after disabling the Web Annoyances Ultralist.  However, I tried disabling all the Annoyances before reporting this and it was still blocked.  It seems I have to wait a bit after changing filter settings before reloading the web page.  Is this the case or should the changes take place immediately?

**Comment by Alex-302** [comment]
@shape55 Just check for filters update after 1-2 hours after message about fixing.
