### ISSUE TITLE
pandora app ios

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#69440]
||campaign.adobe.com^ (used for ads)

works fine when blocked

(https://www.adobe.com/marketing/campaign.html)

**Comment by Alex-302** [comment]
Not sure if it can be blocked
https://docs.campaign.adobe.com/doc/AC6.1/en/Technotes/AdobeCampaign_Deliverability_Configuring_Security_Zones.pdf
used as documents storage
