### ISSUE TITLE
Adguard Annoyances Filter undesired behaviour Youtube

### ISSUE THREAD

**Issue by sdfasdfgawe456h4356** [AdguardTeam/AdguardFilters#6944]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: with adguard annoyances enabled and NOT having gone through the accept cookies etc process go to youtube and start any video (might have to delelte cookies or make new profile)
* **Current behaviour**: a small part of the video is hidden behind the search bar because some kind of a placeholder/white bar is collapsed

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

![adguard annoyances youtube](https://user-images.githubusercontent.com/23087597/30941918-1b24364c-a3e8-11e7-9afa-15c17d7b14e6.png)

* **Expected behaviour**: 

i want to see the whole video

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:

with adguard annoyances enabled and NOT having gone through the accept cookies etc process go to youtube and start any video (might have to delelte cookies or make new profile)

***System configuration***

**Filters:**

adguard annoyances
[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10
Browser:                            | Firefox 55
AdGuard version:                    | 2.7.2
Filters enabled:                    | Adguard Annoyances
AdGuard mode (Android only):        | VPN / Proxy (manual/auto)
Filtering quality (Android only):   | High-quality / High-speed / Simplified
HTTPS filtering (Android only):     | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)       | On / Off
AdGuard DNS:                        | Default
Stealth mode options (Windows only) | ?
Helpdesk ID (if exists):            | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
