### ISSUE TITLE
soundcloud app ios

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#69441]
||soundcloud-pax.pandora.com^ 

(What is PAX?
The Pandora Audience Exchange (or "PAX") is the marketplace of audio publishers reachable through a Pandora media buy, including Pandora, SoundCloud, and AdWave. The base fee for your audio ad includes a license to run it anywhere within the PAX ecosystem) source: https://www.pandora.co/faq/

||promoted.sndcdn.com^ (similar to the promoted.soundcloud.com filter already in dns list)

**Comment by Alex-302** [comment]
Better block it on your device and use app few days. I don't see this domain in any ad/hosts blocking list.

**Comment by jordanelliott23** [comment]
i been using ||soundcloud-pax.pandora.com^ in my list for the past couple days with no issues.

**Comment by Alex-302** [comment]
Ok, added.
