### ISSUE TITLE
moviechat.org - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6945]
https://moviechat.org

<details><summary>Screenshot:</summary>

<img width="422" alt="screen shot 2017-09-28 at 4 58 38 am" src="https://user-images.githubusercontent.com/27292111/30945941-b9a43bf2-a409-11e7-8af1-61049aaa5b3f.png">

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Android
Browser:                            | Chrome
AdGuard version:                    | 2.9
Filters enabled:                    | 1 2 3 4 14 11
AdGuard mode (Android only):        | VPN
Filtering quality (Android only):   | High-quality 
HTTPS filtering (Android only):     | On (Whitelist)
Helpdesk ID:            | 1635871

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed

**Comment by anewuser** [comment]
You've added `moviechat.org/images/affiliates/` but it currently uses `moviechat.org/images/aff/` to load ads (see https://moviechat.org/).

Please keep the existing filter and add this new pattern.
