### ISSUE TITLE
WSP Office app - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6946]
https://play.google.com/store/apps/details?id=cn.wps.moffice_eng

<details><summary>Screenshot:</summary>

<img width="417" alt="screen shot 2017-09-28 at 6 49 10 am" src="https://user-images.githubusercontent.com/27292111/30948525-2b198648-a419-11e7-8d87-a1402465ca55.png">

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Android
AdGuard version:                    | 2.10.56
Filters enabled:                    | 2, 3, 14, 1, 5, 11, 211
AdGuard mode (Android only):        | VPN 
Filtering quality (Android only):   | High-quality 
HTTPS filtering (Android only):     | On (Whitelist)
Helpdesk ID:            | 1065108

**Comment by Alex-302** [comment]
Can't reproduce. Ask for HAR file.

**Comment by AdamWr** [comment]
I can't reproduce.
I see ads only if I disable AdGuard.

**Comment by veronikasav** [comment]
[adguard.har.1506706307627.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1353940/adguard.har.1506706307627.har.zip)
[adguard.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1353941/adguard.har.zip)
