### ISSUE TITLE
http://www.theage.com.au/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6947]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: http://www.theage.com.au/world/otto-warmbier-american-student-held-in-north-korea-died-of-oxygen-starved-brain-20170928-gyqdy3.html

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30953682-9ec3a116-a435-11e7-8266-818fe9c6a1ab.png)
</details><br/>

***System configuration***

**Filters:** English, Russian, Spyware, Social media, Annoyances

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | W10
Browser:                            | Chrome
AdGuard version:                    | 6.2, happens with the extension, too
AdGuard DNS:                        | None 
Stealth mode options (Windows only) | Off
Helpdesk ID (if exists):            | 1633710

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by XX-J** [comment]
АнтиАдблок скрипт: `fairfaxstatic.com.au/dtm/7d5ea80d054b96730162d0905d59678c4d2bf30c/satelliteLib-fc35eab6559a121532bab25bb77b90e6a30892b9.js`
Думаю достаточно в "Английский фильтр": `||fairfaxstatic.com.au/dtm/`

**Comment by Alex-302** [comment]
Добавил и подчистил.
