### ISSUE TITLE
[Предложение] Блокировка "Читайте также" через фильтр раздражителей.

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#6948]
На многих новостных сайтах посреди текста новости суют всякий мусор, типа "Читайте также". Нашел для примера один такой сайт http://24tv.ua/ru/twitter_vdvoe_uvelichil_kolichestvo_znakov_v_zametkah_n869589
Здесь только одна вставка "Читайте также", но я видел когда подобный мусор совали и по 5 штук.

Я считаю это бесполезным и даже мешающим.. как на счет того что бы добавлять подобное в фильтр раздражителей? Если "ок", позже поищу еще немного сайтов с подобными вставками.

Одна из причин по которой это мешает, это то что я выделяю новость мышкой, и заставляю компьютер читать ее вместо меня, но когда встречаются такие вставки, приходится выделять новости частями.

**Comment by Alex-302** [comment]
Да вряд ли стоит это блокировать. Так задуман дизайн. Ссылки ж не посторонние.
