### ISSUE TITLE
реклама пропущена

### ISSUE THREAD

**Issue by slonopotam-ura** [AdguardTeam/AdguardFilters#69493]
Добрый день! На yandex.ru и в его почтовом ящике вылезает реклама.

Кроме того, на почте в rambler.ru вылезает реклама okko.tv хоть я не ходил туда.

Все это не убирается обычными средствами Адгард, а также с помощью присланной от поддержки инструкцией, предусматривающей сброс всех куков и т.п. Используется Опера и Мозила, причем на Мозиле это появилось позднее. На Опере производил полный сброс установок браузера с удалением всей истории, паролей и панелей. Но при этом реклама с Яндекса появилась немедленно, как вошел на сайт.  
По старой памяти использовал визуальные панели Яндекса. От них это вылезло?

На почте Яндекса идет реакция на то, что я искал на Авито.

![Opera Снимок_2020-11-25_133101_mail rambler ru](https://user-images.githubusercontent.com/75627200/101368462-3b99b880-38b8-11eb-9150-ff6dfc621d30.png)
![Opera Снимок_2020-11-25_132717_startpage](https://user-images.githubusercontent.com/75627200/101368591-61bf5880-38b8-11eb-8079-af39d8287fba.png)
![Opera Снимок_2020-12-07_182020_mail yandex ru](https://user-images.githubusercontent.com/75627200/101368894-ba8ef100-38b8-11eb-9623-bb9f0f512786.png)

**Comment by Alex-302** [comment]
@slonopotam-ura Попробуйте это:


### ВНИМАНИЕ

Пользователям программы для `Windows`, `macOS` или `Android` нужно включить расширение `AdGuard Extra` в настройках программы.

---

Пользователям браузерного расширения нужно установить [расширение AdGuard Extra](https://github.com/AdguardTeam/AdGuardExtra#how-to-install-adguard-extra) либо скрипт `AdGuard Extra`. 

<details><summary>Установка скрипта  "AdGuard Extra" в расширение "Tampermonkey"  :</summary>

Для установки скрипта понадобится браузерное расширение-скриптоприёмник `Tampermonkey`

Ссылка на `AdGuard Extra`
https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js

После установки скрипта нужно будет зайти в настройки `Tampermonkey`, включить режим эксперта, переключить режим встраивания на `мгновенный` и перезапустить расширение:
![image](https://user-images.githubusercontent.com/8361299/62641343-07248e00-b94c-11e9-9775-9854a7922889.png)

![image](https://user-images.githubusercontent.com/8361299/62641299-f7a54500-b94b-11e9-8a83-885d89abbeec.png)

</details>

**Comment by slonopotam-ura** [comment]
Ваш скрипт или что там не помог: реклама на Яндексе вновь появилась. Впрочем, в
Морде обезьяны, когда я выполнил то, что вы написали, стоит, что скрипты не
установлены в левой опции. Так и надо? Внутри Адгарда дополнительное расширение
стало. эффекта нет.

  08.12.2020, 14:41, Alex <notifications@github.com>

  @slonopotam-ura Попробуйте это:


  ВНИМАНИЕ

  Пользователям программы для Windows, macOS или Android нужно включить
  расширение AdGuard Extra в настройках программы.

  ----------------------------------------------------------------------------

  Пользователям браузерного расширения нужно установить расширение AdGuard
  Extra либо скрипт AdGuard Extra.

  Установка скрипта "AdGuard Extra" в расширение "Tampermonkey" :

  Для установки скрипта понадобится браузерное расширение-скриптоприёмник
  Tampermonkey

  Ссылка на AdGuard Extra
  https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js

  После установки скрипта нужно будет зайти в настройки Tampermonkey, включить
  режим эксперта, переключить режим встраивания на мгновенный и перезапустить
  расширение:
  image

  image

**Comment by slonopotam-ura** [comment]
Ваш скрипт или что там не помог: реклама на Яндексе вновь появилась. Впрочем, в
Морде обезьяны, когда я выполнил то, что вы написали, стоит, что скрипты не
установлены в левой опции. Так и надо? Внутри Адгарда дополнительное расширение
стало. эффекта нет.
Это и на Опере, и на Мазиле.

  08.12.2020, 14:41, Alex <notifications@github.com>


  @slonopotam-ura Попробуйте это:


  ВНИМАНИЕ

  Пользователям программы для Windows, macOS или Android нужно включить
  расширение AdGuard Extra в настройках программы.

  ----------------------------------------------------------------------------

  Пользователям браузерного расширения нужно установить расширение AdGuard
  Extra либо скрипт AdGuard Extra.

  Установка скрипта "AdGuard Extra" в расширение "Tampermonkey" :

  Для установки скрипта понадобится браузерное расширение-скриптоприёмник
  Tampermonkey

  Ссылка на AdGuard Extra
  https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js

  После установки скрипта нужно будет зайти в настройки Tampermonkey, включить
  режим эксперта, переключить режим встраивания на мгновенный и перезапустить
  расширение:
  image

  image

**Comment by Alex-302** [comment]
@slonopotam-ura Можете отправить отчёт из самого Адгарда? В него автоматом добавятся все настройки, будет понятнее что к чему. Нужно будет лишь ввести адрес страницы с рекламой и добавить скриншот, и ссылку на эту задачу, чтоб знать что отчёт ваш.
https://kb.adguard.com/ru/technical-support/reporting-tool
