### ISSUE TITLE
yandex.ru/pogoda - Missed ad

### ISSUE THREAD

**Issue by Hawkrus** [AdguardTeam/AdguardFilters#6949]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

Не режется реклама с постзагрузкой по адресу https://yandex.ru/pogoda/moscow

![pogoda-mos](https://user-images.githubusercontent.com/19652388/30956242-5a49ea72-a43f-11e7-95ed-a1afea174450.PNG)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows 7 / Windows 10
Browser:                            | Google Chrome Версия 61.0.3163.100 (Официальная сборка)
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | Русский фильтр 1.0.57.45
AdGuard DNS:                        | Default
Stealth mode options (Windows only) | ------
Helpdesk ID (if exists):            | ------

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Если будут проблемы с воспроизведением, готов предоставить удалённый доступ.**

**Comment by evgeniy-ADG** [comment]
До 6.2 беты обновитесь, там вроде бы решено.

**Comment by Hawkrus** [comment]
Поставил бету, не помогло.

**Comment by Alex-302** [comment]
Для проги подправил.

**Comment by Hawkrus** [comment]
Действительно, реклама ушла.
