### ISSUE TITLE
Реклама в фейсбуке... 

### ISSUE THREAD

**Issue by Smorvel** [AdguardTeam/AdguardFilters#6950]
Страна Италия.
Блокировка через программу.
Фильтр easy list italy подключен
![image](https://monosnap.com/file/55N0S1Akd177Stj5gMeNqJ0iu0B8hF.png)

**Comment by Alex-302** [comment]
Программу фильтровать не можем.

**Comment by Smorvel** [comment]
@Alex-302 В смысле? Под программой имеется ввиду Adguard (не расширение а программа)

**Comment by Alex-302** [comment]
Шаблон нужно заполнять...

**Comment by Smorvel** [comment]
@Alex-302 зачем и так же все понятно... Так что делать? А то я ставлю всем adguard, говорю что он лучше, а оказывается что юблок блочит рекламу на фейсбуке а adguard нет.
Проблема не у меня. Я фейсбуком вообще не пользуюсь.

**Comment by Alex-302** [comment]
У меня фейсбук абсолютно чист. Не зная конфигурации помочь в этом случае сложно.

**Comment by Alex-302** [comment]
> юблок блочит рекламу на фейсбуке 
а какой фильтр блокирует?

**Comment by Smorvel** [comment]
@Alex-302, какой фильтр был в юблоке я не знаю... Я восстановил свой аккаунт для проверки, у меня тоже оказалось чистым, хоть и тоже нахожусь в Италии. Видимо еще и сам фейсбук должен быть на итальянском, или еще что влияет, пока не проверял все варианты.

**Comment by Alex-302** [comment]
> какой фильтр был в юблоке я не знаю

можно по одному выключать с проверкой.

**Comment by Smorvel** [comment]
Короче, чуть позже (возможно завтра) дам знать все что смогу выяснить...

**Comment by Smorvel** [comment]
@Alex-302 И так, вошел я в тот аккаунт со своего компа, у меня тоже реклама появилась, на своем пробовал менять язык и прочее, ничего не вызвало ее, видимо от аккаунта зависит.
Вот она https://monosnap.com/file/YzBT6keGuYGIqJHQJT4tFhtbcYieEw.png
Установил юблок ориджин, она сразу исчезла. Исчезла на столько, что даже отключение юблока ее не смогло вернуть. Поэтому какой фильтр ее блокирует вияснить не могу... сейчас пытаюсь ее вернуть, возможно придется браузер перезапустить, если появится, отпишусь.

**Comment by Smorvel** [comment]
Короче после юблока она исчезла и не помогает ни перезапуск браузера, ни удаление юблока, ни запуск в другом браузере, и даже на компьютере у владельца она пропала... **(вот это я понимаю блокировщик XD)**
Но мне сказали, что в прошлый раз после установки юблока было то же самое, но примерно через день после удаления, она снова появилась.

До установки юблока, я перезагружал страницу по 100 раз, реклама не исчезала.

**Comment by Alex-302** [comment]
У меня бы тогда вылезла.
Судя по отсутствию других жалоб, явление зависит от каких-то факторов(регион, активность, интересы)
