### ISSUE TITLE
turbobit.net - Ad + Incorrect Blocking

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#6951]
1. Реклама в фоне: http://turbobit.net/download/free/ini7v60aaqa2

<details><summary>Screenshot:</summary>

![turbobit](https://user-images.githubusercontent.com/17948007/30960985-63b1ec82-a44d-11e7-8f0e-abcd37bbb894.jpg)
</details><br/>

Ссылка на рекламную картинку: http://turbobit.net/opnauz/V2.jpg
Моя версия правила: `||turbobit.net/*/V2.jpg`

2. Блокировка мешающая скачке. При нажатии на окончательную ссылку "Скачать" - ничего не происходит.
Всему виной - "Фильтр счетчиков и систем аналитики", а точнее правило - `||turbobit.net/platform/js/fdlogger/fdlogger.js` , посему: `@@||turbobit.net/platform/js/fdlogger/fdlogger.js`

___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard v2.7.2 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
поправил

**Comment by XX-J** [comment]
Картинка не убралась.

**Comment by Alex-302** [comment]
У меня чисто
http://imagizer.imageshack.com/img922/912/fFtqHB.jpg

**Comment by XX-J** [comment]
У меня всё также, как и на скриншоте из первого сообщения.

Может поможет код страницы, отдаваемый моему браузеру сайтом: [turbobit.net.txt](https://github.com/AdguardTeam/AdguardFilters/files/1346639/turbobit.net.txt)

Вы добавили правило: `turbobit.net##a[href*="&campaign="] > img` . Как я понимаю оно должно блокировать следующие картинки: http://turbobit.net/opnauz/el24green40.png   и   http://turbobit.net/opnauz/am24green40.gif . Та картинка, которую имею ввиду я, другая: http://turbobit.net/opnauz/V2.jpg . И находится в коде страницы, выложенным мной выше, по этому же адресу: http://turbobit.net/opnauz/V2.jpg

**Comment by Alex-302** [comment]
Фонового изображения не вижу. Нужна сохранённая страница.

**Comment by XX-J** [comment]
Код страницы прикреплял в предыдущем сообщении, но если нужна целиком, то вот: [Turbobit.net.zip](https://github.com/AdguardTeam/AdguardFilters/files/1347480/Turbobit.net.zip)

 При сохранении браузер сообщил что некоторые файлы не могут быть загружены. Как я выяснил позже и та, фоновая картинка тоже. Но, при открытии сохранённой страницы, она показывается всё равно.

**Comment by Alex-302** [comment]
Проверь такое
```
turbobit.net#$#html[-ext-has="> body"] { background: none!important; }
```

**Comment by XX-J** [comment]
> `turbobit.net#$#html[-ext-has="> body"] { background: none!important; }`

 Работает.

**Comment by Alex-302** [comment]
Добавил
