### ISSUE TITLE
http://m.baby-und-familie.de/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6952]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: http://m.baby-und-familie.de/
The text is pale grey, looks like we block a pop-up banner but its leftovers are still there

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30962624-2e3887fe-a453-11e7-9b1a-f2f03a81104a.png)

</details><br/>

***System configuration***

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.30.6 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.33 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.22.92 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.17.96 Enabled=YES
- ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.14 Enabled=YES
- ID=6 Name="German filter" Version=1.0.36.53 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.56 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.59 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by marco-sorich** [comment]
Same behavior at http://www.diabetes-ratgeber.net/

**Comment by Alex-302** [comment]
Fixed
