### ISSUE TITLE
http://m.aiyousheng.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6953]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: http://m.aiyousheng.com/54560/30585052.html

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/30962909-42599970-a454-11e7-8fb4-3f353137031e.png)

![image](https://user-images.githubusercontent.com/15856304/30962918-4784f980-a454-11e7-96bb-4d0bcb449d07.png)

![image](https://user-images.githubusercontent.com/15856304/30962924-4c25ead0-a454-11e7-8e05-5e9e2bb1846d.png)

</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.31.58 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.64 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.23.51 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.18.74 Enabled=YES
- ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.17 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.79 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES
- ID=104 Name="EasyList China" Version=1.0.88.27 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | 1635461

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
not reproduced. URL or screenshots are invalid.
