### ISSUE TITLE
kinozal-tv.appspot.com

### ISSUE THREAD

**Issue by Yulia-ADG** [AdguardTeam/AdguardFilters#6954]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: https://kinozal-tv.appspot.com/
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/32357008/30964235-283be37c-a459-11e7-9c7c-c9cd29743326.png)

</details><br/>

***System configuration***

**Filters:** English, Spyware, Annoyances, Russian filter

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | Extension 2.7.2
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | reported at vk.com

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не повторяется. 
На проверку:
```
kinozal-tv.appspot.com##.rb_new
```
