### ISSUE TITLE
real-vin.com

### ISSUE THREAD

**Issue by Yulia-ADG** [AdguardTeam/AdguardFilters#6955]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:  http://real-vin.com/
* **Current behaviour**:  Blank page with Adguard enabled

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/32357008/30964923-0af75fe6-a45c-11e7-8a2b-d0737566757f.png)

</details><br/>

* **Expected behaviour**: Page loads normally

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/32357008/30964965-32f4a8be-a45c-11e7-8b8b-7ecfd95ea0d4.png)

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   |Windows
Browser:                            | Chrome 
AdGuard version:                    | Extension 2.7.2
Filters enabled:                    | English, Spyware, Annoyances, Russian filter
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | Reported at vk.com

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
