### ISSUE TITLE
dlisted.com - missed ad on iOS

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardFilters#6956]
[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image1 2](https://user-images.githubusercontent.com/30834067/30998465-64554852-a4d7-11e7-9009-2178aa49f0fe.png)
![](https://qcrm.supportyourapp.com/message/attachment/1503946/image1.png)
![image](%screenshot_url%)
</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | iOS 11
Browser:                            | Safari
AdGuard version:                    | 1.3.1.82
Filters enabled:                    | 2,3,4,11,12,14,101,118,122,207
Helpdesk ID (if exists):            | 436382

**Comment by Alex-302** [comment]
It is not ad, just floating video player.
