### ISSUE TITLE
theage.com.au - Anti adblock 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6958]
http://www.theage.com.au/

<details><summary>Screenshot:</summary>

<img width="1342" alt="screen shot 2017-09-29 at 12 59 20 pm" src="https://user-images.githubusercontent.com/27292111/31011260-49d468ac-a516-11e7-8444-7ecbcac4113e.png">

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Mac OS
Browser:                            | Chrome
AdGuard version:                    | 1.4.1
Filters enabled:                    | 2 3 4 14
Helpdesk ID:            | 1633491

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed today.
