### ISSUE TITLE
Avast app - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6959]
https://www.google.lk/url?sa=t&source=web&rct=j&url=https://play.google.com/store/apps/details%3Fid%3Dcom.avast.android.mobilesecurity%26hl%3Den%26referrer%3Dutm_source%253Dgoogle%2526utm_medium%253Dorganic%2526utm_term%253Davast%2Bmobile%2Bsecurity%26pcampaignid%3DAPPU_1_qMnAWZrUOsTbvATLg5KQDQ&ved=0ahUKEwiayNmo37DWAhXELY8KHcuBBNIQ5IQBCCQwAA&usg=AFQjCNESukqSxT-Cd8vHuwPD8FcmfwAbiw

Our customer bilieves it's a regional ad (Sri Lanka).
<details><summary>Screenshot:</summary>

<img width="405" alt="screen shot 2017-09-29 at 1 08 29 pm" src="https://user-images.githubusercontent.com/27292111/31011552-5f679882-a517-11e7-88fd-6a4384ced502.png">
<img width="409" alt="screen shot 2017-09-29 at 1 08 50 pm" src="https://user-images.githubusercontent.com/27292111/31011551-5f66e3d8-a517-11e7-8aa7-cd055797f786.png">

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Android
AdGuard version:                    | 2.9.136
Filters enabled:                    | 2 3 11 14 
AdGuard mode (Android only):        | VPN 
Filtering quality (Android only):   | High-quality 
HTTPS filtering (Android only):     | On (Whitelist)
Helpdesk ID:            | 1345133

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Droid version?
Ads are blocked on my device with https filtering enabled.
Try
```
||graph.facebook.com^$app=com.avast.android.mobilesecurity
```
