### ISSUE TITLE
Shazam - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6960]
https://play.google.com/store/apps/details?id=com.shazam.android

<details><summary>Screenshot:</summary>

<img width="405" alt="screen shot 2017-09-29 at 1 15 35 pm" src="https://user-images.githubusercontent.com/27292111/31011825-524e5856-a518-11e7-8085-eaf75a997392.png">

</details><br/>

***System configuration***

IInformation                         | Value
---                                 | ---
Operating system:                   | Android
AdGuard version:                    | 2.9.136
Filters enabled:                    | 2 3 11 14 
AdGuard mode (Android only):        | VPN 
Filtering quality (Android only):   | High-quality 
HTTPS filtering (Android only):     | On (Whitelist)
Helpdesk ID:            | 1345133

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. Ask for ***HTTP*** log

**Comment by Alex-302** [comment]
@AdamWr

**Comment by AdamWr** [comment]
I can't reproduce.
By the way, there was similiar issue before - https://github.com/AdguardTeam/AdguardFilters/issues/5942

**Comment by Alex-302** [comment]
Ask for HAR then.
