### ISSUE TITLE
Add Polish language filters

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#6961]
Request from user to add this filters: 

`Polish filters - social`  https://github.com/MajkiIT/polish-ads-filter/blob/master/adblock_social_filters/adblock_social_list.txt

`Adblock & uBlock polish filters - Adguard supplement`  https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock_adguard.txt

**Comment by FadeMind** [comment]
**notice: these filters are available in Adguard For Windows (and browser self extension), but they are not listed in Adguard Android app.**

**Comment by AdamWr** [comment]
`Adblock & uBlock polish filters - Adguard supplement` this list is in AdGuard for Android, it is at the very end of the filter lists.

**Comment by FadeMind** [comment]
@AdamWr `Adblock & uBlock polish filters - Adguard supplement` is the last option on the list 😮 Why is not near other Polish filters?? 😈 

Thanks for TIP ;)
