### ISSUE TITLE
AdGuard Pro DNS blocks calls on FaceTime

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6963]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behavior**: It blocks calls. When you call someone via FaceTime, the person picks up and the call fails. On your end, it ends up with "No answer" message.

***Steps to reproduce the problem***:

1. Enable AdGuard Standard DNS
2. Call someone via FaceTime

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS11
Browser:                            | -
AdGuard version:                    | 1.3.1
Filters enabled:                    | -
AdGuard DNS:                        | Standard DNS
Helpdesk ID (if exists):            | 1079300

[com.adguard.AdguardPro.tunnel.gz](https://github.com/AdguardTeam/AdguardFilters/files/1346633/com.adguard.AdguardPro.tunnel.gz) - capured with log, happened between 20:11-20:14

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I see no blocked domains at this time.
Enable filtering log, disable and enable Internet, reproduce the issue and make screenshot of blocked domains.

**Comment by ameshkov** [comment]
Could be the known issue with custom DNS and Apple CDN:
http://joemaller.com/2577/itunes-slowdowns-with-google-dns/

**Comment by zebrum** [comment]
it works fine in split-tunnel
the issue is reproducible in full-tunnel

**Comment by zebrum** [comment]
moved to https://github.com/AdguardTeam/AdguardForiOS/issues/501
