### ISSUE TITLE
tracking.hermesworld.com - Blank page - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6965]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Incorrect blocking - page becomes blank.
https://tracking.hermesworld.com/?TrackID=60265149307539

Screenshots attached: before & after

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/31052814-61c1c374-a697-11e7-808e-ad163465a962.png)

![image](https://user-images.githubusercontent.com/31481372/31052815-68122502-a697-11e7-80e7-75c9805bfe0f.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.34 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.39 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.4 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.10 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.55 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.61 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.60 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 10.3.2
Browser:                            | Safari
AdGuard version:                    | 1.3.1.107
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1636283

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't access to this site.
Can you reproduce the issue?

**Comment by iverkhohliad** [comment]
Sorry, somehow missed adding the whole url
https://tracking.hermesworld.com/?TrackID=60265149307539

**Comment by Alex-302** [comment]
Fixed.
