### ISSUE TITLE
https://music.yandex.ru/ - hiding an element

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6967]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: We block the banner but the placeholder remains, is it possible to block it as well? A similar case: https://github.com/AdguardTeam/AdguardFilters/issues/5965

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

Banner unblocked:

![image](https://user-images.githubusercontent.com/15856304/31057197-58181df0-a6e7-11e7-9e33-d52b55cce4ba.png)

A leftover:

![image](https://user-images.githubusercontent.com/15856304/31057199-60250e54-a6e7-11e7-90b1-b775650d34b3.png)

</details><br/>

* **Expected behaviour**: See the screenshot

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31057201-67b9289e-a6e7-11e7-8ad3-2c22dc005818.png)

</details><br/>

***System configuration***

**Filters:**

- FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
- FilterId:4 Name: Social media filter Url: https://filters.adtidy.org/extension/chromium/filters/4.txt
- FilterId:14 Name: Annoyances filter Url: https://filters.adtidy.org/extension/chromium/filters/14.txt
- FilterId:1 Name: Russian filter Url: https://filters.adtidy.org/extension/chromium/filters/1.txt
- FilterId:207 Name: Adblock Warning Removal List Url: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
- FilterId:211 Name: Anti-Adblock Killer | Reek Url: https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
- FilterId:237 Name: AdBlock Protector List (Incompatible with Adguard) 

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 10
Browser:                            | Chrome
AdGuard version:                    |  6.2.390.2018
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1099770

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by vitalkanev** [comment]
Browser extension 2.6.7 on Yandex 17.4.1 - Windows XP  includes an empty banner...

**Comment by Alex-302** [comment]
Не повторяется даже без Адгарда.
Пустоту можно выделить инструментами разработчика?

**Comment by Alex-302** [comment]
@evgeniy-ADG
