### ISSUE TITLE
Incorrect Blocking Russian Filter

### ISSUE THREAD

**Issue by ajax-zoom** [AdguardTeam/AdguardFilters#69683]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

A rule from "Russian filter" to block content that contains "_120_600" is too unspecific.
It may block innocent images, which are likely to have that string in their file names.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 
Do not block images that happen to contain _120_600 in their file names.

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:
1. Enable russian filter.
2. Open this page:
https://prestashop.ajax-zoom.com/fr/home/8-augustepinkdiamant.html

3. Open developer tools in Chrome (F12) and switch to console.
4. Click on the left thumbnail with the 360 icon below the main image. A 360 view loads.
5. Watch a resource failing to be loaded.

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM22:1 /modules/ajaxzoom/pic/zoomthumb/8/_/8_412_Auguste_Pink_Diamant_120_600x600.jpg not loaded

Image /modules/ajaxzoom/pic/zoomthumb/8/_/8_412_Auguste_Pink_Diamant_120_600x600.jpg that loads via JavaScript is blocked by the russian filter because of "_120_600" rule.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

Return from AdGuard Protocol (blocked)
URL: https://prestashop.ajax-zoom.com/modules/ajaxzoom/pic/zoomthumb/8/_/8_412_Auguste_Pink_Diamant_120_600x600.jpg
Typ: Image
Quelle: prestashop.ajax-zoom.com
Rule: _120_600
Filter: AdGuard Russian Filter

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | ?
Browser:                               | ?
AdGuard version:                       | ?
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Sergey-Lyapin** [comment]
Picture was whitelisted.

**Comment by ajax-zoom** [comment]
Sergey.
Whitelisting the specific domain mentioned in the description of the issue does NOT make any sense because it is a demo of a [360 spin software](https://www.ajax-zoom.com) that is installed on thousands of websites, and which may have the same but also other patterns to the directory with resized and cached images.

The purpose of the "_120_600" rule in general_url.txt is to remove banners where you have 120 as height and 600 as width. In this case, 120 is the number of the image preceding _119 and following by _121, and that is how a webmaster would typically name them before uploading. The software automatically creates smaller versions of the original files by adding "_600x600" to the base of the filename. However, it may also contain other "parameters" that follow "_600x600", whereby "_600x600" (the size of the bigger thumbnail) could also be "600x400".

A sustainable solution would be to change the "_120_600" rule by adding a dot after it if you expect the size of the banner being appended to the base filename. Alternatively, exclude "_120_600" when followed by "x" (or "x4", "x6"). I am not familiar with your regex syntax or possibly other solutions that allow a more precise filtering. Anyways, excluding a specific domain is unfortunately not a sustainable solution and does not solve this issue. Thank you.
