### ISSUE TITLE
mangachan.me - Реклама - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6969]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Пропущена реклама на странице:
http://mangachan.me/online/337319-cartoon-hero_v1_ch2.html#page=4

У меня повторилось.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/31066230-10911668-a754-11e7-8d79-c8f0259ec0fc.png)

</details><br/>

**Filters:**

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.32.12 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.73 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.71 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.1 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.57.53 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.88 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.63 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.88.18 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.88.40 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Device:                          | iPad
Operating system:                   | 11.0.1
Browser:                            | Safari
AdGuard version:                    | 1.3.1.82
Simplified filters (iOS only)       | Off
Helpdesk ID (if exists):            | 1634134

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
