### ISSUE TITLE
foodnetwork.com - anti-adblock script

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#6970]
http://www.foodnetwork.com/ 

<details><summary>Screenshot:</summary>

![screenshot 2017-10-02 12 59 53](https://user-images.githubusercontent.com/23637588/31072801-1e040f6c-a772-11e7-9998-ad3b71303382.png)

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | El Capitan
Browser:                            |Chrome
AdGuard version:                    | 1.5.0
Filters enabled:                    | En RU spyware social media annoyances

**Comment by Alex-302** [comment]
Fixed.
