### ISSUE TITLE
Skype for Business and Adobe Creative Cloud are blocked when "Automatic filter applications" is ticked

### ISSUE THREAD

**Issue by keewawa** [AdguardTeam/AdguardFilters#69715]
As the title described, I cannot log on  either Skype for Business or Adobe Creative Cloud when "Automatic filter applications" is enabled. Once this setting is unticked, no issue with the apps.

**Comment by Alex-302** [comment]
Hi. Which AdGuard?

**Comment by keewawa** [comment]
Sorry, it is Application version 2.5.1.928 release (CL-1.7.150) on Mac. Actually only started behaving like this after updating to Big Sur

**Comment by Alex-302** [comment]
Please open AdGuard's filtering log and restart Skype. And make screenshot. Is Skype  added to filtered apps?

**Comment by keewawa** [comment]
Nothing was captured in the log windows (see below). The issue is so reproducible that once "Automatic filter applications" is disabled in Settings Skype for Business can connect. So can Adobe Creative Cloud. By the way, there is no issue with ordinary Skype.

<img width="1098" alt="Screenshot 2020-12-14 at 4 29 42 PM" src="https://user-images.githubusercontent.com/4408568/102143545-b703e880-3e29-11eb-845f-0e2f7350e525.png">

**Comment by Alex-302** [comment]
Weird. Please check when all filters, AdGuard extensions and stealth mode are disabled, but protection is enabled.
Which DNS is used?

**Comment by keewawa** [comment]
Disabling all filters, extensions and stealth mode doesn't help. However, if the Filtering Mode under "Automatically filter applications" is changed "Automatic Proxy" from "Network Extension", then everything works again. As said before, this issue only started after updating to Big Sur, perhaps it has something to do with its Network Extension. 

I didn't set any DNS particularly on the machine

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardForMac #804](https://github.com/AdguardTeam/AdguardForMac/issues/804) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
Ok. Moved to AdguardForMac repository.
