### ISSUE TITLE
sportbox.ru - Video not playing - Android

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6971]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Когда заходит на сайт sportbox.ru видео не играет. Просто картинка и треугольничек
Например в разделе "Лучшие моменты" (футбольные голы). С отключенным Adguard видео показывает.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![download 1](https://user-images.githubusercontent.com/31481372/31075978-ccea54c4-a780-11e7-9d84-908dab13be52.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | Android
Helpdesk ID (if exists):            | 1592809

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
У меня работает.
Оформи как следует, есть же шаблон.

**Comment by iverkhohliad** [comment]
больше не было инфы, к сожалению((

@altokarev was able to reproduce.

**Comment by altokarev** [comment]
Это не на Andorid было ж.

Вот тут проверял, к примеру: https://news.sportbox.ru/Vidy_sporta/Futbol/Liga_Chempionov/spbvideo_NI784112_clip_Sevilja___Maribor___30_Goly_i_luchshije_momenty

В тот день было много жалоб на спортбокс. Может уже исправили. По идее пользователю нужно только фильтры обновить.
