### ISSUE TITLE
https://mail.google.com - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6973]
https://mail.google.com

<details><summary>Screenshot:</summary>

![screen shot 2017-10-02 at 9 36 08 pm](https://user-images.githubusercontent.com/27292111/31093325-094ea3be-a7ba-11e7-95db-8eb2bec3f508.png)

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | 6.1
Filters enabled:                    | 2 3 4
Helpdesk ID:            | 1624243

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Нужен доступ. У меня не повторяется.
