### ISSUE TITLE
Times Of India app - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#6974]
https://play.google.com/store/apps/details?id=com.toi.reader.activities&hl=en

<details><summary>Screenshot:</summary>

![screen shot 2017-10-02 at 10 57 33 pm](https://user-images.githubusercontent.com/27292111/31096590-1ae9df48-a7c5-11e7-8d90-b6e2c45965e5.png)

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Android
AdGuard version:                    | 2.10
Filters enabled:                    | 2 3 4 11
AdGuard mode (Android only):        | VPN 
Filtering quality (Android only):   | High-quality
HTTPS filtering (Android only):     | On Whitelist
Helpdesk ID :            | 1601831

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
This placeholder is builtin
