### ISSUE TITLE
[stealth - issue] www.rmfon.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#6975]
**Site Sample** | 
----|
http://www.rmfon.pl/play,5

### Issue

When stealth mode is enabled for this domain player did not working properly. 

### Fix
```
@@||rmfon.pl^$stealth
```

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Opera Stable x64
AdGuard version:                    | **6.2.419.2110**
Stealth mode: | **enabled**

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

Stealth mode options enabled |
---------------------|
`hide search passwords ** send Do-Not-Track header ** remove X-Client-Data header ** remove tracking data from urls ** self-destroying third-party cookies  ** disable third-party request cache  ** block API browser (except flash) ** hide refferer against third-party ** hide user-agent header ** hide IP address`

**Comment by AdamWr** [comment]
Mógłbyś proszę napisać co konkretnie nie działa?
Sprawdziłem u siebie i muzyka normalnie się odtwarza.

**Comment by FadeMind** [comment]
Bardzo długo czeka się na stream, a kiedy się zacznie odtwarzanie to jest ono przerywane. Nie jest płynne.

**Comment by AdamWr** [comment]
Dodane.
