### ISSUE TITLE
marinetraffic.com -- top and left banners

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#6976]
Here is how it looks like:
https://uploads.adguard.com/up04_gq777_MarineTraffic_Global_Ship_Tracking_Intelligence__AIS_Marine_Traffic.png

Falls under self-promo, though, so I suggest adding it to the Annoyances filter.

**Comment by AdamWr** [comment]
Any steps to reproduce?
On my end it looks ok.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/31128697-d5dca262-a852-11e7-9c0c-a6752bd9dfe1.png)

</details>

**Comment by Alex-302** [comment]
Also not reproduced.

**Comment by ameshkov** [comment]
Hm, that's weird guys, I can easily reproduce it:(

Two different configurations:

AG for Mac + Chrome (English, Social, Spyware, Russian)
Firefox Nightly + extension (same filters0

**Comment by ameshkov** [comment]
Rules to block it:
```
marinetraffic.com##.top-banner
marinetraffic.com###skyscrapper_container
```

**Comment by AdamWr** [comment]
Today I also see this.
Added to Annoyances filter:
`marinetraffic.com##.top-banner`
`marinetraffic.com##div.hidden-print`
`marinetraffic.com#$#body[style^="padding-top: 144px;"] { padding-top: 47px!important; }`
`marinetraffic.com#$#.banner > div > nav.navbar-fixed-top[style="padding-top: 97px;"] { padding-top: 0px!important; }`
