### ISSUE TITLE
ovgorskiy.ru - Missed ad 

### ISSUE THREAD

**Issue by Yulia-ADG** [AdguardTeam/AdguardFilters#6977]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: http://ovgorskiy.ru/
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
![image](https://user-images.githubusercontent.com/32357008/31115241-3adc1d10-a82a-11e7-986d-81e65fb7b233.png)

</details><br/>

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10
Browser:                            | Chrome
AdGuard version:                    | Adguard AdBlocker 2.7.2
Filters enabled:                    | English, Spyware, Annoyances, Russian, Experimental
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | Reported at reports.adguard.com

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. Try to update filters.
