### ISSUE TITLE
winrar_64_bit.en.downloadastro.com

### ISSUE THREAD

**Issue by 3xploiton3** [AdguardTeam/AdguardFilters#69787]
![image](https://user-images.githubusercontent.com/19517680/101959023-1d74e500-3c37-11eb-94d8-7dad131d4594.png)

![image](https://user-images.githubusercontent.com/19517680/101959000-0df59c00-3c37-11eb-8b9e-b87b224c2439.png)

source: 
https://winrar_64_bit.en.downloadastro.com/

contain malware

**Comment by lolka4toli** [comment]
Blacklisted.
