### ISSUE TITLE
bento.de - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6978]
***Site***: http://www.bento.de/
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31119818-8f3f56b2-a832-11e7-99f0-00476b207980.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.

**Comment by JayBrown** [comment]
This has apparently not been resolved. See current screenshot below. Tested on macOS with Adguard Desktop, and on Windows 7 with Firefox and the Adguard FF extension. All the above filters mentioned by the OP (and many more; see below) are enabled. An additional annoying bonus is that when on Windows 7 in Firefox you click one of the buttons, e.g. "Weiter mit Adblocker", "continue with adblocker" (but also the other one), the anti-adblock overlay is not removed, only the buttons are gone, thereby rendering the page useless.

![snap](https://i.imgur.com/cpBNWNU.jpg)

Filters used in Adguard Desktop (macOS):
**Adguard Filters:** English, Spyware, Social media, Annoyances, Russian, German, Japanese, French, Dutch, Spanish/Portuguese, Mobile Ads, Safari
**EasyList:** EasyList, EasyPrivacy, Fanboy's Social Blocking List, Fanboy's Annoyances, EsayList Czech and Slovak, EasyList Germany, EasyList Italy, Icelandic ABP List, Norsk adblockliste, void.gr, Fanboy's Enhanced Tracking List
**Other:** Adblock Warning Removal List, Anti-Adblock Killer (Reek), CJX's Annoyance List, Fanboy Anti-Facebook List, I don't care about cookies, Malware Domains, Peter Lowe's list, Prebake, Spam404, BarbBlock

**Comment by AdamWr** [comment]
Ok, I could reproduce this issue, fixed.
Update will be available after 1-2 hours, so if you do not want to wait, you can add this rule to user filter and check the result:
`bento.de#%#(function(o){function a(a){return{get:function(){return a},set:b}}function b(){}function c(){throw"Adguard: stopped a script execution.";}var d={},e=a(function(a){a(!1)}),f={},g=EventTarget.prototype.addEventListener;o(d,{spid_control_callback:a(b),content_control_callback:a(b),vid_control_callback:a(b)});o(f,{config:a(d),_setSpKey:{get:c,set:c},checkState:e,isAdBlocking:e,getSafeUri:a(function(a){return a}),pageChange:a(b),setupSmartBeacons:a(b)});Object.defineProperty(window,"_sp_",a(f));EventTarget.prototype.addEventListener=function(a){"sp.blocking"!=a&&"sp.not_blocking"!=a&&g.apply(this,arguments)}})(Object.defineProperties);`

**Comment by JayBrown** [comment]
It's fine. The Mac is my main machine, and as long as clicking one of the buttons still works to remove the block, I'm fine with waiting a couple of hours. Thank you!
