### ISSUE TITLE
citytv.com - Annoyance - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#6980]
***Site***: https://www.citytv.com/toronto/?video=5589014843001 -> https://www.citytv.com/toronto/blocker/?referer=https%3A%2F%2Fwww.citytv.com%2Ftoronto%2F&video_param=video&video=5589014843001
***Description***: Adblock detection when trying to play a video. Cookie notice at the bottom.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31119944-10599e60-a833-11e7-8cf7-5ac2ae354020.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
