### ISSUE TITLE
thequestion.ru - Не открываются комментарии - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6987]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Не открываются комментарии и остальные ответы в мобильной версии при включённом Adguard

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.28.18 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.91 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.21 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.55.50 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.34 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.55 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Device                            |  iPad
Operating system:                   |  10.3.3
AdGuard version:                    | 1.3.1.107
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1569561

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Добавил в фильтр соц сетей
```
@@||yastatic.net/share2/share.js$domain=thequestion.ru
```
