### ISSUE TITLE
www.psypost.org - Ad Blocker detected - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#6988]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Large “Beware Ad Blocker detected!” notice, complete with overlay appears persistently on the screen.

http://www.psypost.org/2017/10/drug-addiction-isnt-bad-habits-fear-withdrawal-selfish-search-pleasure-brain-49771

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.31.85 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.68 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.63 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.89 Enabled=YES
ID=16 Name="French filter" Version=1.0.8.29 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.81 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES

Information                         | Value
---                                 | ---
Device:                               |iPad
Operating system:                   | 11.0.1
AdGuard version:                    | 1.3.1.82
Simplified filters (iOS only)       |  Off
Helpdesk ID (if exists):            | 1636935

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
