### ISSUE TITLE
https://arstechnica.com/ - leftovers

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6989]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: https://arstechnica.com/tech-policy/2017/09/isps-want-supreme-court-to-kill-title-ii-net-neutrality-rules-now-and-forever/

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31165089-58ee5034-a8f2-11e7-9cb1-4443cde3c9f2.png)

</details><br/>

***System configuration***

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.31.99 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.71 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.23.67 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.18.97 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.85 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 11
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | 1142272

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Please check after next filters update.
