### ISSUE TITLE
http://www.unitedincompassion.com.au/contact.html

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#699]
Невозможно отправить сообщение через форму контактов, выдается сообщение:

form.jotform.co has been blocked

https://qcrm.cc/#/customer/1073747

**Comment by Alex-302** [comment]
Нужен список фильтров. Подозреваю easy privacy
Также из фишинга нужно убрать http://www.i-m.co/
С выключенным фильтром всё работает.

**Comment by vbagirov** [comment]
Из фишинга убрал, про фильтр спросил.
