### ISSUE TITLE
http://masseffect.wikia.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6990]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: http://masseffect.wikia.com/wiki/Sha'ira
Search suggestions are non-clickable

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31165264-1427adbe-a8f3-11e7-82a8-f44ccd0c67a1.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31165273-1c666eac-a8f3-11e7-94b8-fdfa9399b364.png)

</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.1.31.99 Enabled=YES
- ID=3 Name="Spyware filter" Version=1.0.14.71 Enabled=YES
- ID=4 Name="Social media filter" Version=1.0.23.67 Enabled=YES
- ID=14 Name="Annoyances filter" Version=1.0.18.97 Enabled=YES
- ID=11 Name="Mobile Ads filter" Version=1.0.9.85 Enabled=YES
- ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 11
Browser:                            | Safari
AdGuard version:                    | 1.3.1
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None
Helpdesk ID (if exists):            | 1637838

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$domain=wikia.com
```
please check on mobile device
