### ISSUE TITLE
cdek.ru

### ISSUE THREAD

**Issue by NUser2018** [AdguardTeam/AdguardFilters#69921]
### Issue URL 
[https://www.cdek.ru/](https://www.cdek.ru/)
### Comment
Username: @NUser2018
> 
> --
> Информация ниже сгенерирована автоматически. Не удаляйте ее.
> 
> 
> 
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> 
> При активном Adguard не работает\ломается сайт службы доставки СДЭК

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://user-images.githubusercontent.com/43743908/102203433-060d5480-3ee2-11eb-9a56-483e033ab57b.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.3
Browser: | Firefox
AdGuard driver: | WFP
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian
Other extensions used: | Kaspersky Total Security 2021 (21 MR2) (21.2.16.590)

При активном Adguard не работает\ломается сайт службы доставки СДЭК [https://www.cdek.ru/](https://www.cdek.ru/)

**_UPDATE 14.12.2020: При многократных повторных заходах воспроизводится не всегда стабильно, но хорошо воспроизводится при первом заходе на сайт и\или после очистки кэша и кук в браузере._**

**_UPDATE 15.12.2020: Воспроизводится только при первой попытке захода на сайт и\или после очистки кэша и кук в браузере. Если перезапустить браузер и снова открыть сайт, то проблема уже не воспроизводится, до следующей очистки браузера._**

**Comment by NUser2018** [comment]
**_UPDATE 15.12.2020: При многократных повторных заходах воспроизводится не всегда стабильно, но хорошо воспроизводится при первом заходе на сайт и\или после очистки кэша и кук в браузере._**

**Comment by NUser2018** [comment]
**_UPDATE 15.12.2020: Воспроизводится только при первой попытке захода на сайт после очистки кэша и кук в браузере. Если перезапустить браузер и снова открыть сайт, то проблема уже не воспроизводится, до следующей очистки браузера._**

**Comment by Alex-302** [comment]
Это их антиддос не пускает.
https://variti.com/ru-ru/services/ddos-protection/
Как-то писал им, но ничего дельного они не ответили.

**Comment by NUser2018** [comment]
> 
> 
> Это их антиддос не пускает.
> https://variti.com/ru-ru/services/ddos-protection/
> Как-то писал им, но ничего дельного они не ответили.

Ну не знаю. Я в августе уже получал и отслеживал посылку через СДЭК и такой проблемы не было, а сейчас есть и только когда запущен Adguard. Когда Adguard выгружен такой проблемы нет.

Может Вы все-таки попробуете ещё раз что-то посмотреть и проверить?

Заранее спасибо. С уважением Александр (**NUser2018**).

**Comment by Alex-302** [comment]
Мы тут ничего не поделаем. Они со своей стороны видимо помогать не будут.

**Comment by NUser2018** [comment]
Похожие симптомы как на сайте СДЭК (подробнее смотрите ранее) на днях стали наблюдатся и на сайте сети аптек Вита ([https://vitaexpress.ru/)](https://vitaexpress.ru/)
Причина та же что и на сайте СДЭК или другая?
Что-то можно с этим сделать или нет также как и со СДЭК?

Я вот только не пойму (как со СДЭК также теперь и с сайтом сети аптек видимо), я что ли один с такой пробkемой столкнулся и она волнует только меня, а сотрудников и других пользователей Adguard нет!?

Если эти проблемы невозможно решить при помощи внесения каких-то изменений в фильтры Adguard так может быть просто чтобы решить эту проблему тогда эти сайты просто исключить из фильтрации Adguard внести их в список HTTPS-искючений Adguard?

Опять же я конечно могу сделать это самостоятельно только для себя, но ведь хочется решить проблемы и улучшить работу Adguard не только для себя но и для других пользователей, которые пользуются одновременно и этими сервисами (СДЭК и Аптеки Вита) и также Adguard. Неужели таких пользователей мало? Неужели эти проблемы волнуют только меня и не волнуют других пользователей Adguard?

В любом случае заранее спасибо хотя бы за ответ.
С уважением **NUser2018**.

**Comment by Alex-302** [comment]
Это безумный анти-ддос так реагирует на Адгард. Пишите в их поддержку.
