### ISSUE TITLE
flashx.net

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#69941]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: many popups and anti Adblock
`https://www.flashx.net/486723dd802ad8bf582bfca90926909a.jsp`
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="780" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/102024560-09de9100-3d93-11eb-9f42-b13c7334046c.PNG">

</details><br/>

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.23
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by JobcenterTycoon** [comment]
I still get Popups `https://www.flashx.net/1ca1b3d24b5f608f73656ae17660607c.jsp`

**Comment by Alex-302** [comment]
Obsolete link.
