### ISSUE TITLE
Adguard Tracking Protection Filter 2.0.19.9 blocks Metamask functions

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardFilters#69987]
@menhammer commented on [Fri Dec 11 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3633)

Hello, 
Adguard Tracking Protection Filter 2.0.19.9 blocks Metamask functions, cannot use the buttons in the Metamask extension Chrome.
When i disable the Adguard Tracking Protection filter everything is ok.

In the older version Adguard Tracking Protection Filter 2.0.18.96 everything works fine.

Does anybody know what to do?
Or how can i replace the newer filter for the older one so Metamask works again?

Thanks!

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59)
* Operating system and version: (e.g. Windows 10, v.1703, build 15063.413)

**Comment by Alex-302** [comment]
@menhammer Please describe where and how to check this issue.
