### ISSUE TITLE
https://onvix.tv/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#6999]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: Can't access the site with AdGuard DNS
The link: https://onvix.tv

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31169632-f34aca5e-a901-11e7-9f60-c59e82bba2c7.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

With Google DNS:

![image](https://user-images.githubusercontent.com/15856304/31169640-f9e083fe-a901-11e7-9c64-38e1ea6a1c8a.png)

</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 11.0.1
Browser:                            | Safari
AdGuard version:                    | 1.3.1
AdGuard DNS:                        | Default 
Helpdesk ID (if exists):            | 1636509

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
What is the purpose of this site?

**Comment by evgeniy-ADG** [comment]
Вот в сети пишут: ONVIX.TV. Тысячи фильмов и сериалов без рекламы.
ТВ по подписке, думаю.

**Comment by Alex-302** [comment]
Исключил из фильтрации DNS
