### ISSUE TITLE
http://www.southpark.de/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7000]
http://www.southpark.de/alle-episoden/s21e01-white-people-renovating-houses#

The German filter blocks the video player. You'll need to have a German IP to reproduce this.

<details><summary> with german filter </summary>

![image](https://user-images.githubusercontent.com/15856304/31170174-cb2e4ed6-a903-11e7-8e51-50980efaadb9.png)

</details>

<details><summary> without german filter </summary>

![image](https://user-images.githubusercontent.com/15856304/31170184-d5de46c4-a903-11e7-8a75-84ac505616bb.png)

</details>

**Comment by Alex-302** [comment]
Fixed.
Please check after filters update.

**Comment by danidoedel** [comment]
Works for me
