### ISSUE TITLE
[Bad Rules] ||verify.snssdk.com^$xmlhttprequest,redirect-rule=noop.txt

### ISSUE THREAD

**Issue by KazamaSion** [AdguardTeam/AdguardFilters#70014]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: This is a reCAPTCHA similar product but get blocked.
* **Current behaviour**: Website cannot load the captcha.

<details><summary>Screenshot:</summary>

![image](https://vip2.loli.net/2020/12/15/z2UKPwIB9auCOvN.png)
</details><br/>

* **Expected behaviour**: Load the captcha

<details><summary>Screenshot:</summary>

![image](https://vip1.loli.net/2020/12/15/MYB3nyNXIQ2VzHb.png)
</details><br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:** https://github.com/AdguardTeam/AdguardFilters/blob/3c64890ea15ed76bf7cccdb3ead627c1f3558639/SpywareFilter/sections/specific.txt#L156

**Comment by krystian3w** [comment]
test:

`@@||verify.snssdk.com^$xmlhttprequest,redirect-rule`

Older uBO maybe need this:

`||verify.snssdk.com^$xmlhttprequest,redirect-rule=noop.txt,badfilter`

**Comment by KazamaSion** [comment]
`@@||verify.snssdk.com^$xmlhttprequest,redirect-rule`: Working

Add both: also working.

**Comment by Alex-302** [comment]
Removed.
