### ISSUE TITLE
[bad-rule] ||embed.mystream.to^$popup

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdguardFilters#70012]
***Description***:  The rule is recent and breaks the web player
* **Current behaviour**: 
 Breaks the web player also there are plenty of existing rules that eliminate popups from happening:

![Capture](https://user-images.githubusercontent.com/34774426/102125577-831bc980-3e0f-11eb-8e93-b0d28bdbc9bb.PNG)

**Testing Link:** https://mystream.to/watch/hbv6sabkh7ul

* **Expected behaviour**: 
Web Player showing up,not just a grey box.

***System configuration***

**Filters:**
Rule is located in **AdGuard Base filter**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:  **Windows 10, v.1607 LTSB, build 14393.4046**
Browser:  **Slimjet Version 28.0.3.0 (based on Chromium 85.0.4183.69) (Official Build) (64-bit)**
AdGuard version:  **7.5.3**

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.

**Comment by dnmTX** [comment]
Thank you Adam @AdamWr  👍
