### ISSUE TITLE
http://www.bild.de/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7001]
http://bild.de

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/28191233-d03646fc-6837-11e7-8f23-e91c0a621dfd.png)

</details>

***System configuration***

Application version: 1.2.1.71

Device: iPhone
Platform: iOS
OS: 10.3.2

Optimazed enabled: NO

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.24.64 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.27 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.21.13 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.15.44 Enabled=YES
ID=6 Name="German filter" Version=1.0.35.55 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.52 Enabled=YES

Ticket ID :  1636998

**Comment by danidoedel** [comment]
I hope this one gets fixed real quick... :worried:

**Comment by AdamWr** [comment]
Added:
`@@||acdn.adnxs.com/as/*/pages/bild.js$domain=bild.de`

@danidoedel Could you please check it?

**Comment by danidoedel** [comment]
@AdamWr Awesome, seems to work! Thank you :)

**Comment by AdamWr** [comment]
Ok, thank you for checking this.
