### ISSUE TITLE
www.ukr.net 

### ISSUE THREAD

**Issue by Yulia-ADG** [AdguardTeam/AdguardFilters#7002]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Ad elements don't get blocked

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
![image](https://user-images.githubusercontent.com/32357008/31171030-131719f0-a907-11e7-8637-a3c64d27e8db.png)

</details><br/>

* **Expected behaviour**: 

Ad elements on the sides are removed

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
![image](https://user-images.githubusercontent.com/32357008/31171341-f6204956-a907-11e7-935d-f9fc5c18e1f8.png)

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10
Browser:                            | Chrome
AdGuard version:                    | 6.1
Filters enabled:                    | English, Spyware, Annoyances, Russian, Experimental
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | reported at vk.com

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
That column is not an ad.
