### ISSUE TITLE
Lenfilm.tv - Missed ad

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardFilters#7004]
Missed Ads on lenfilm.tv.
Logs attached. 

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
![screen shot 2017-10-02 at 10 57 33 pm](https://user-images.githubusercontent.com/30834067/31176573-f891f568-a91b-11e7-9e50-976190d78d42.png)

![screenshot_2017-09-24-20-49-48-815_com yandex browser](https://user-images.githubusercontent.com/30834067/31176585-01c31db0-a91c-11e7-895d-079ac0b108ed.png)
</details>

Information                         | Value
---                                 | ---
Operating system:                   | Android 7.0
AdGuard version:                    | 2.10.106
Filters enabled:                    | English, Spyware, Social Media, Russian, Mobile Ads
Filtering quality (Android only):   | High-quality
HTTPS filtering (Android only):     | On 
AdGuard DNS:                        | Default
Helpdesk ID (if exists):            | 1630774

**Comment by Alex-302** [comment]
Not reproduced.
Which browser?
