### ISSUE TITLE
Anwap.org - Missed Ad

### ISSUE THREAD

**Issue by darkulish** [AdguardTeam/AdguardFilters#7005]
Missed Ads on Anwap.org.
Logs attached.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![screenshot_2017-09-24-20-50-43-305_com yandex browser](https://user-images.githubusercontent.com/30834067/31176682-5e8a6f62-a91c-11e7-8d78-91efa79d72a6.png)

![screenshot_2017-09-24-20-50-59-042_com yandex browser](https://user-images.githubusercontent.com/30834067/31176696-6887d478-a91c-11e7-8626-edee8015fcd0.png)

Information                         | Value
---                                 | ---
Operating system:                   | Android 7.0
AdGuard version:                    | 2.10.106
Filters enabled:                    | English, Spyware, Social Media, Russian, Mobile Ads
Filtering quality (Android only):   | High-quality
HTTPS filtering (Android only):     | On 
AdGuard DNS:                        | Default
Helpdesk ID (if exists):            | 1630774

**Comment by Alex-302** [comment]
Which browser?

**Comment by vitalkanev** [comment]
Yandex (I can see the bottom bar; I guess latest @darkulish ?)
