### ISSUE TITLE
vezi-online.com - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7010]
***Site***: https://vezi-online.com/episod/american-horror-story-s07e05-holes
***Description***: Ads and ad pop up when clicking on any link.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31183537-29a1d276-a927-11e7-9b54-bb81a3898dd9.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
