### ISSUE TITLE
tribunavalladolid.com - Ad leftover - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7011]
***Site***: https://www.tribunavalladolid.com/
***Description***: Ads and ad leftovers.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31184865-de25c0e2-a92a-11e7-8b17-527582ad7441.png)

![image](https://user-images.githubusercontent.com/10995998/31184906-f744e06c-a92a-11e7-8dbc-245163a935e7.png)

![image](https://user-images.githubusercontent.com/10995998/31184950-148d1f5e-a92b-11e7-8d9d-2cfdcc5cf20b.png)

and so on...

***https://www.tribunavalladolid.com/noticias/la-cruz-laureada-se-queda-en-valladolid/1507116449:***

![image](https://user-images.githubusercontent.com/10995998/31184980-23a0f736-a92b-11e7-9398-97da15063413.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.390.2018
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
Spanish/Portuguese filter

**Comment by AdamWr** [comment]
It was fixed here - https://github.com/AdguardTeam/AdguardFilters/issues/6879
