### ISSUE TITLE
theage.com.au - anti adblock

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#7014]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![31193953-435146d0-a94e-11e7-979f-93b20cd5a31f](https://user-images.githubusercontent.com/30041399/31194017-79de35be-a94e-11e7-9f0a-8abadbcf2295.png)

</details><br/>

***Steps to reproduce the problem***:
[theage.com.au](theage.com.au)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Win
Browser:                            | Edge
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 2, 3, 4, 10
Helpdesk ID (if exists):            | 1634417

<details><summary>Stealth mode options: </summary>

> Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": false,
  "BlockWebRtc": false,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "RemoveXClientDataHeader": true,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveRefererFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferer": null,
  "HideIp": false,
  "CustomIp": _HIDDEN FOR PRIVACY REASONS_
   }

</details>

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by vitbortnik** [comment]
>  I have a broadband ethernet connection to desktop and had set up wireless via dongle as well. By turning that WiFi off I can now access that site

**Comment by vitbortnik** [comment]
Take a look, have your conclusions and probably close the issue:)
Seems to be not AdGuard related.

**Comment by Alex-302** [comment]
Maybe.
