### ISSUE TITLE
http://www.areadvd.de - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7016]
http://www.areadvd.de

<details><summary>Screenshot:</summary>

<img width="1573" alt="screen shot 2017-10-05 at 5 39 44 am" src="https://user-images.githubusercontent.com/27292111/31209656-397a7414-a995-11e7-961a-90ed86cef7e1.png">

</details><br/>

***System configuration***

Operating system:                   | Mac OS
Browser:                            | Chrome
AdGuard version:                    | 1.4.1
Filters enabled:                    | 2 3 4 6 
Helpdesk ID:            | 1441210

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by AdamWr** [comment]
I can't reproduce.
