### ISSUE TITLE
http://tushkan.club/ Ads

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7017]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
***Site***: http://tushkan.club/news/nevskiy_2016_smotret_serial_onlayn_vse_serii_5/2017-10-04-17885
***Description***: Missed ads.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%
![image](https://user-images.githubusercontent.com/32528702/31209753-f45d1f84-a995-11e7-8321-8e0fb299c6d7.png)
)
</details><br/>

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | MacOS
Browser:                            | Chrome
AdGuard version:                    | 1.5.0
Filters enabled:                    | 2 3 4 14 1 6 12 15 101
Helpdesk ID (if exists):            | 1110466

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
