### ISSUE TITLE
http://www.seedoff.tv/ Ads

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7018]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
http://www.seedoff.tv/
***Description***: Missed ads.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%
![image](https://user-images.githubusercontent.com/32528702/31210333-1f2f5688-a99a-11e7-93b3-62899e128586.png)
)
</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | MacOS
Browser:                            | Chrome
AdGuard version:                    | 1.5.0
Filters enabled:                    | 2 3 4 14 1 6 12 15 101
Helpdesk ID (if exists):            | 1630607 1641358

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced on my end.

**Comment by zebrum** [comment]
can not reproduce.
@ashvets-sup did users check in incognito mode?
