### ISSUE TITLE
There is no way to remove the advertisement of iqiyi children's column

### ISSUE THREAD

**Issue by kelejichi1989** [AdguardTeam/AdguardFilters#70199]
There is no way to get rid of the ads on iqiyi children's channel

Please update the rules

Website attached

https://www.iqiyi.com/v_ 19rykzce94.html#curid=15429656900_ 615cfbb026eabd2343b237245a912bd2

**Comment by Alex-302** [comment]
Please try to enable AdGuard Annoyances filter.
