### ISSUE TITLE
http://seasonvar.ru/ Ads

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7019]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
http://seasonvar.ru/serial-13913-Ochen__strannye_dela.html
***Description***: Missed ads.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%
![image](https://user-images.githubusercontent.com/32528702/31210682-a41ef644-a99c-11e7-87b3-c16e8a7d0a06.png)
)
</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | MacOS
Browser:                            | Chrome
AdGuard version:                    | 1.5.0
Filters enabled:                    | 2 3 4 14 1 6 12 15 101
Helpdesk ID (if exists):            | 1641575

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
