### ISSUE TITLE
http://anime-free.net/

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#702]
Рекламы много на сайте.

**Comment by Alex-302** [comment]
добавил
||gaman.anime-free.net^$third-party

**Comment by vgavrish** [comment]
Вин. Прога. Баннеры по сайту: http://prntscr.com/diftc4
Ф: 1,2,3,4,14
Хром

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
anime-free.net##body > div#toolbar  > div#Comm
://*.anime-free.net^$script

```
