### ISSUE TITLE
http://www.rappers.in/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7020]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: It won't let you download samples and plays something else instead of an actual sample. The link: http://www.rappers.in/en/beat-125314.html

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31222820-3511e9ac-a9d1-11e7-8cd3-923b69ce5814.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31222756-ea9fd99c-a9d0-11e7-8dc2-ea4300b1f42f.png)

</details><br/>

***System configuration***

**Filters:**

- FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
- FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt
- FilterId:4 Name: Social media filter Url: https://filters.adtidy.org/extension/chromium/filters/4.txt
- FilterId:10 Name: Filter unblocking search ads and self-promotion Url: https://filters.adtidy.org/extension/chromium/filters/10.txt
- FilterId:1 Name: Russian filter Url: https://filters.adtidy.org/extension/chromium/filters/1.txt
- FilterId:6 Name: German filter Url: https://filters.adtidy.org/extension/chromium/filters/6.txt
- FilterId:9 Name: Spanish/Portuguese filter Url: https://filters.adtidy.org/extension/chromium/filters/9.txt
- FilterId:16 Name: French filter Url: https://filters.adtidy.org/extension/chromium/filters/16.txt
- FilterId:104 Name: EasyList China Url: https://easylist-downloads.adblockplus.org/easylistchina.txt
- FilterId:105 Name: EasyList Czech and Slovak Url: https://raw.github.com/tomasko126/easylistczechandslovak/master/filters.txt
- FilterId:109 Name: EasyList Italy Url: https://easylist-downloads.adblockplus.org/easylistitaly.txt
- FilterId:216 Name: Adblock & uBlock polish filter Url: https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Mac, Win
Browser:                            | Chrome
AdGuard version:                    | 6.2 beta, 1.5.0
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1641468

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
