### ISSUE TITLE
torren.eu

### ISSUE THREAD

**Issue by lioner2020** [AdguardTeam/AdguardFilters#70205]
на странице
https://torren.eu/opentorrent/d.php?var=//torren.eu/torrent/files/id313156.torrent&var2=https://lovetorrent.net/290313156-onlyfanscom-mei-kou-solo-posing-big-tits-2019-2020-180-foto-290x320---3840x3167.html&var3=[OnlyFans.com]%20Mei%20Kou%20[Solo,%20Posing,%20Big%20Tits]%20[2019-2020,%20180%20%D1%84%D0%BE%D1%82%D0%BE,%20290x320%20-%203840x3167]&var4=116%20MB

я вижу банер

**Comment by krystian3w** [comment]
Test:

`torren.eu##section.section > center`
