### ISSUE TITLE
enisey.tv - Ad Leftover

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#7021]
Пустая, полупрозрачная полоса внизу страницы (прилеплена), которая осталась от кнопок соц. сетей: https://socmedia.enisey.tv/news/post-4878/

<details><summary>Screenshot:</summary>

![enisey tv](https://user-images.githubusercontent.com/17948007/31225179-82986d2e-a9d9-11e7-83a2-c43d370df39c.jpg)
</details><br/>

Правило исправления в "Фильтр виджетов социальных сетей": `socmedia.enisey.tv###js-share-links`

___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard v2.7.2 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Добавил.
