### ISSUE TITLE
my.dazn.com - Cookie notice

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7023]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Cookie-note at the bottom: https://my.dazn.com/help/DE-en/FAQ

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/31238071-63d4932c-aa01-11e7-8bdf-75f00e35fc7d.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.32.61 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.82 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.90 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.24 Enabled=YES
ID=6 Name="German filter" Version=1.0.37.7 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.67 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Device:| iPhone
Operating system:                   |  11.0.2
Browser:                            | Safari
AdGuard version:                    | 1.3.1.107
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1609733

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
