### ISSUE TITLE
chefonefoods.com (N: AdGuard for Windows) (T: Incorrect Blocking)

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardFilters#70248]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

The site is blocked by AdGuard's anti-malware module, despite it just being a combined foodbrand and recipe website from what I can tell: https://reports.adguard.com/en/chefonefoods.com/report.html

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/102542477-27249f80-40b2-11eb-9500-0c4cc15d955d.png)

</details><br/>

* **Expected behaviour**: 

Either the site becomes unblocked by default, or a better explanation for its blocking has to be provided.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/102542335-edec2f80-40b1-11eb-8add-7e2aa0932130.png)
</details><br/>

***Steps to reproduce the problem***:

1) Turn on Browsing Security in *AdGuard for Windows*.
2) Visit `https://chefonefoods.com/how-to-cook-frozen-dumplings/`

***System configuration***

**Filters:**

N/A (Issue is about closed-source AdGuard filter modules.)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | 20H2
Browser:                               | Chrome x64
AdGuard version:                       | AdGuard for Windows 7.5.3
Filters enabled:                       | N/A
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by lolka4toli** [comment]
Unblocked.
