### ISSUE TITLE
http://www.finanzen.net/ - Ad leftover

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7024]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/31238291-34e04704-aa02-11e7-877d-5da66c8e8731.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.32.59 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.81 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.90 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.22 Enabled=YES
ID=6 Name="German filter" Version=1.0.37.5 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.92 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.67 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Devise: | iPhone
Operating system:                   | 11.1
Browser:                            | Safari
AdGuard version:                    | 1.3.2.108
Simplified filters (iOS only)       | Off
AdGuard DNS:                       |    Default 
Helpdesk ID (if exists):            | 1322540

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added
```
finanzen.net##.bs-wrapper
@@/ad_data/*$image,domain=finanzen.net
```
