### ISSUE TITLE
toptipstricks.net - Social widgets

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7025]
***Site***: https://toptipstricks.net/threads/x5-netflix-premium-account-s-2k17.1488/
***Description***: Share icons.

Rule: `toptipstricks.net##.rnsocial`

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31241341-eb9da152-aa03-11e7-9aec-41e155b06554.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.424.2123
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
