### ISSUE TITLE
golfchannel.com - Ad leftover - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7026]
***Site***: http://www.golfchannel.com/news/ryan-lavner/ready-or-not-here-comes-new-tour-season
***Description***: Adblock detection when trying to play videos. Ad leftover at the top (desktop and mobile).

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31241579-90f0f32a-aa04-11e7-82b7-c3ecf8624887.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.424.2123
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
