### ISSUE TITLE
libelletv.nl - Incorrect Blocking (page completely broken)

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7028]
***Site***: https://www.libelletv.nl/
***Description***: Page is completely broken! Videos won't start also...

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31241924-acc81e92-aa05-11e7-8b9e-55f4da88dbce.png)

***https://www.libelletv.nl/serie/een-bosje-liefde/bosjeliefde_myrthe/:***

![image](https://user-images.githubusercontent.com/10995998/31241981-dc4df9a2-aa05-11e7-9122-2a9ef4eab73d.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.424.2123
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
Dutch filter

**Comment by AdamWr** [comment]
Fixed.
