### ISSUE TITLE
marca.com - Social widgets - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7029]
***Site***: http://www.marca.com/futbol/2017/10/05/59d66797468aeb5a5e8b45c3.html
***Description***: Ad leftovers. Social share buttons.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31242168-728614f4-aa06-11e7-9b01-1cb38e9d7988.png)

![image](https://user-images.githubusercontent.com/10995998/31242209-9388537e-aa06-11e7-8dee-dde8d525e1b4.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.424.2123
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
Spanish/Portuguese filter

**Comment by AdamWr** [comment]
Fixed.
