### ISSUE TITLE
46.166.167.16 - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7033]
***Site***: http://46.166.167.16/
***Description***: Ads all over the place.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31242804-7c0a8396-aa08-11e7-865c-05d2d0c74e48.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.424.2123
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
