### ISSUE TITLE
auto-motor-und-sport.de - Annoyance - Ad

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7035]
***Site***: http://www.auto-motor-und-sport.de/formel-1/fotos-gp-japan-2017-bilder-donnerstag-suzuka-12702859.html
***Description***: Ad and newsletter sign up in sidebar.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31243087-6c5b0fa0-aa09-11e7-88ef-6531fdb94929.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.424.2123
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by danidoedel** [comment]
And another ad (https://www.auto-motor-und-sport.de/):

![image](https://user-images.githubusercontent.com/10995998/31583683-2639ed86-b1a0-11e7-9374-447b0fceb3ab.png)

**Comment by AdamWr** [comment]
Fixed.

**Comment by danidoedel** [comment]
@AdamWr Some more ad leftover:

![image](https://user-images.githubusercontent.com/10995998/32134325-871ec162-bbeb-11e7-852a-6473908c79ee.png)

**Comment by AdamWr** [comment]
Ok, fixed.
