### ISSUE TITLE
thefreedictionary.com - Social widgets - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7036]
***Site***: http://www.thefreedictionary.com/
***Description***: Ad leftover. Social share buttons.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31243190-c2e47744-aa09-11e7-9156-de4121725472.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.424.2123
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
