### ISSUE TITLE
m.biqugezw.com - Missed ad - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7039]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Missed ad on page:
http://m.biqugezw.com/10_10718/8979861.html

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/31248316-09ccbc68-aa1c-11e7-988b-618a5baa2982.png)

![image](https://user-images.githubusercontent.com/31481372/31248355-21aa5b10-aa1c-11e7-97e1-dd7cbd20f005.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.32.39 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.77 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.82 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.13 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.91 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.64 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.88.73 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.3.96 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Device:  | iPhone
Operating system:                   | 11.0.1
Browser:                            | Safari
AdGuard version:                    | 1.3.1.107
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1457423

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
