### ISSUE TITLE
https://www.equestriadaily.com/ - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7040]
"You're using AdBlocker" notice.

### Steps to reproduce

1. Go to https://www.equestriadaily.com/
2. See the banner

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31264958-ed023096-aa74-11e7-9891-67ec694ae45a.png)

</details>

### Your environment

* Adguard version: AdGuard for Mac 1.5.0
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off
* HTTPS filtering: On

**Comment by seba2282** [comment]
This problem with all. Adguard for firefox, chrome, etc./Android, PC/apk with and without filtering DNS. Example I turn on all filters (without reek, adblock protector and potencial usually ads) in FF on PC. And Android apk with all filters (without reek and usually ads) with DNS filtering and https filtering.

**Comment by evgeniy-ADG** [comment]
Yes, looks like we simply don't have a rule for that banner yet.

**Comment by Alex-302** [comment]
Fixed.

**Comment by seba2282** [comment]
Ok. Thanks 😊
