### ISSUE TITLE
http://www.tmz.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7041]
The whole site is blocked

### Steps to reproduce

1. Go to http://www.tmz.com/
2. See what is on the screenshot below
3. Whitelist
4. Works fine

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31265657-9ea20062-aa78-11e7-830c-c668b89e84fe.png)

</details>

### Expected behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31265669-aa925322-aa78-11e7-8f67-87180593643c.png)

![image](https://user-images.githubusercontent.com/15856304/31265675-afd8ab7e-aa78-11e7-8ed7-bcad395c9b1f.png)

</details>

### Your environment

* Adguard version: 1.3.1 for iOS
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off
* Optimized filters: Off

**Comment by Alex-302** [comment]
Fixed.
