### ISSUE TITLE
player.pl anti adblock script.

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#7042]
Videos are blocked and it is monit about disable adblock.
Example link : 
https://player.pl/programy-online/kuchenne-rewolucje-odcinki,114/
Firefox/MS Edge + Adguard browser extension
Windows 7/10 
All filters (without reek/aak, adblock/ublock protector and usually ads).

Screenshoot : 
![bez tytulu](https://user-images.githubusercontent.com/16944478/31297466-5d7038d4-aae6-11e7-91f1-26965df5e077.png)

**Comment by seba2282** [comment]
@AdamWr Any fix ?

**Comment by AdamWr** [comment]
Niestety w tej chwili, w przypadku rozszerzenia nie widzę możliwości ominięcia tego.
Mogę jedynie odblokować reklamy, co zresztą zostało [zrobione wcześniej](https://forum.adguard.com/index.php?threads/resolved-video-not-playing-at-all-on-www-player-pl.10376/), ale po zmianie jednej reguły przestało działać.

**Comment by seba2282** [comment]
Ok. @AdamWr dziękuję za jakiekolwiek informacje.
