### ISSUE TITLE
www.mamba.ru - message popup on click (RUS)

### ISSUE THREAD

**Issue by webstudia** [AdguardTeam/AdguardFilters#7043]
Здравствуйте.
Перестали открываться всплывающие окошки с сообщениями на сайте https://www.mamba.ru
Т.е. когда хочешь написать пользователю, нажимаешь на кнопку "Написать сообщениее" в анкете пользователя.
То должно появляться окно с чатом. Но оно перестало появляться.
Вчера работало нормально.
Если отключить Adguard, то всё работает.
--- | ---
Operating system:                   |  win 10 x64 rus
Browser:                            | firefox, chrome, IE
AdGuard version:                    | 6.2.424.2123 beta

**Comment by Alex-302** [comment]
Нужен должным образом заполненный шаблон.
