### ISSUE TITLE
http://tvojlor.com - Missed ad + Leftovers

### ISSUE THREAD

**Issue by vitalkanev** [AdguardTeam/AdguardFilters#7044]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: They are some ad left at the left + banner at the bottom
* **Current behaviour**: Ads + leftover are exists. See the screenshot

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![_2017-10-06_14-29-44](https://user-images.githubusercontent.com/18398761/31280007-a38f14c6-aab3-11e7-93e9-220749e4fa41.png)
</details><br/>

* **Expected behaviour**: Should be no ads

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

Example page for testing: http://tvojlor.com/lekarstva/poloskat-gorlo-nastojkoj-kalenduly.html

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Linux - Xubuntu Zesty
Browser:                            | Firefox 56
AdGuard version:                    | 2.7.2 Browser Extension
Filters enabled:                    | English, Annoyance, Russian, German,<br/>EasyList, RuAdList
Helpdesk ID (if exists):            | `undefined`

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Как ты на эту помойку попал? mail.ru?

**Comment by vitalkanev** [comment]
Нет. Просто один человек попросил туда зайти. Из Яндекса.
<details><summary>Запрос:</summary>

```zsh
календула спиртовой раствор для полоскания горла
```

После этого выбрал результат №2
</details>

**Comment by Alex-302** [comment]
Угу. Выдачу заполонили подобные сайты. Почищу.

**Comment by Alex-302** [comment]
А нет, этот вроде не такой, как которые я имел в виду.
