### ISSUE TITLE
Ads on mail.ru

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7045]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
Customer reports ads on mail.ru site. Screenshot provided.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/32528702/31292653-f2af0fec-aadc-11e7-82ef-d790dea78f3d.png)

</details><br/>

***System configuration***

**Filters:**
English filter
Spyware filter
Social media filter
Annoyances filter
Russian filter

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows NT 10.0
Browser:                            | Opera
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 2 3 4 14 1
Helpdesk ID (if exists):            | 671346

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed

**Comment by Alex-302** [comment]
Чисто у меня.

**Comment by vitbortnik** [comment]
> Здравствуйте, спасибо большое, реклама пропала
