### ISSUE TITLE
After you turn on the adguard annuities filter, the ads come out

### ISSUE THREAD

**Issue by kelejichi1989** [AdguardTeam/AdguardFilters#70458]
Issue URL (Anti Adblock Script)
https://www.iqiyi.com/v_19rt6imhq8.html#curid=4975417900_7fc73d426803d3370e3e0577f4ea7ce9

After you turn on the adguard annuities filter, the ads come out

If the adguard annuities filter is turned off, the ad will disappear, but it will take a long time. Waiting time is advertising time.

**Comment by Sergey-Lyapin** [comment]
I can't check the issue, because I see the error that video is not available in my area
@AdguardTeam/filters-maintainers please take a look

**Comment by stanislav-atr** [comment]
@Sergey-Lyapin, same with different IPs.
