### ISSUE TITLE
dilidili.wang - Anti adblock

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7046]
http://www.dilidili.wang/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/31294955-77a03264-aae5-11e7-806e-ca68095a593a.png)

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPad
Platform: iOS
OS: 11.0.1

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.28.48 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.13.97 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.22.29 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.56 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.86.11 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.85.97 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.3.65 Enabled=YES

Helpdesk ID:           1639538

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
