### ISSUE TITLE
sovets.net - Missed Ad - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7047]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Пропущена реклама на странице:
http://sovets.net/2429-massazher-dlya-nog.html

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/31300196-164a2270-aafb-11e7-9c57-52387d0dab9b.png)

</details><br/>

* **Expected behaviour**: 

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.32.49 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.80 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.87 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.20 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.57.77 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.92 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.64 Enabled=YES
ID=101 Name="EasyList" Version=1.0.75.94 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.88.41 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 11.0
Browser:                            | Safari
AdGuard version:                    | 1.3.1.82
Simplified filters (iOS only)       | Off
Helpdesk ID (if exists):            | 1640921

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed
