### ISSUE TITLE
m.bild.de - Ad leftover - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7048]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Ad leftover
http://m.bild.de/news/inland/wetter/warnung-orkan-53421264.bildMobile.html

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/31301920-6717e10a-ab06-11e7-87cb-791646779171.png)

![image](https://user-images.githubusercontent.com/31481372/31301923-6ca66ac4-ab06-11e7-9c89-51f66cc20777.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.32.58 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.81 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.89 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.22 Enabled=YES
ID=6 Name="German filter" Version=1.0.37.5 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.92 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.67 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 11.1
Browser:                            | Safari
AdGuard version:                    | 1.3.2.108
Simplified filters (iOS only)       | Off
AdGuard DNS:                        | None 
Helpdesk ID (if exists):            | 1322540

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
It is difficult to hide it on iOS, because this element has the same name as normal elements, so I won't fix this.
Added for Android users:
`m.bild.de##.txt > .element[-ext-has=">.tsr-info > h3:contains(Auch Interessant)"]`
