### ISSUE TITLE
https://allegro.pl - AdGuard blocks login in this site.

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#7050]
Mozilla Firefox/Microsoft Edge
Windows 7/10
AdGuard Browser Extension
Filters : all (without adblock/ublock protector, reek/aak and usually ads)
Site : https://allegro.pl

I can't sign in on https://allegro.pl. I have it after click button sign in :
![adguardbug2](https://user-images.githubusercontent.com/16944478/31307139-f1949b1e-ab5d-11e7-95f9-86ce32d983b4.PNG)

If I add this sites on whitelist AdGuard : 
![adguardbug1](https://user-images.githubusercontent.com/16944478/31307205-22f2e8d6-ab5f-11e7-8a4f-ef4efc4ae711.PNG)

Can I sign in and see ads : 
![adguardbug](https://user-images.githubusercontent.com/16944478/31307208-390438be-ab5f-11e7-93a2-03f4a5783cfb.PNG)

Can you help in it ?

**Comment by AdamWr** [comment]
Masz za dużo list włączonych.
Zgaduję, że problem sprawia japoński filtr (ABP Japanese Filters).
Sprawdź proszę tę regułę:
`@@||cdn.allegrostatic.com/login-frontend-static/$domain=allegro.pl`

Jeśli to nie pomoże, to proszę wyłącz każdą listę po kolei i napisz, która sprawia problem.

**Comment by seba2282** [comment]
@@||cdn.allegrostatic.com/login-frontend-static/$domain=allegro.pl

Na razie, jakby działało. Ciekaw jestem, dlaczego na mobilnym z tym nie ma problemu, nawet z włączonym DNS.

**Comment by AdamWr** [comment]
Prawdopodobnie dlatego, że tam nie ma dostępnej listy `ABP Japanese Filters`.

**Comment by seba2282** [comment]
:) Możliwe.
