### ISSUE TITLE
[Android] dropsync - banner in home screen

### ISSUE THREAD

**Issue by ArnaudB88** [AdguardTeam/AdguardFilters#7058]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

When opening the app 'Dropsync' (v2.9.11, free version), ads are displayed in the home screen ('Status' tab)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://www.dropbox.com/s/hm40mncc45lwutu/dropsync_screen.png?dl=0)
</details>

![dropsync_screen](https://user-images.githubusercontent.com/29403668/31316624-36a83b56-ac31-11e7-9dbd-b893e308b0b0.png)

<br/>

* **Expected behaviour**: 

I expect this advertisement area should be blocked.

***Steps to reproduce the problem***:
- install 'dropsync' free version to an android phone
- open the app (and possibly link to a dropbox account)
- the ad area is located on the 'status' tab

***System configuration***

**Filters:**

english, spyware, social media, annoyances, dutch, mobile ads, 

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Android 7.0
Browser:                            | -
AdGuard version:                    | 2.10.108 (beta versions)
Filters enabled:                    | yes (see above)
AdGuard mode (Android only):        | VPN
Filtering quality (Android only):   | High-quality
HTTPS filtering (Android only):     | Off
Simplified filters (iOS only)       | -
AdGuard DNS:                        | None
Stealth mode options (Windows only) | -
Helpdesk ID (if exists):            | -

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||graph.facebook.com^$app=com.ttxapps.dropsync
```
