### ISSUE TITLE
https://www.youtube.com - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7059]
Likes and view count are blocked by english / easylist filters

### Steps to reproduce

1. Go to https://www.youtube.com
2. No likes and play counts 
3. Disable the said filters 
4. Works fine

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31318724-3b53c48a-ac5f-11e7-8046-a6e2a78354d4.png)

</details>

### Expected behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31318730-46792940-ac5f-11e7-88e3-a1afbdf97368.png)

</details>

### Your environment

* Adguard version: 1.3.1 for iOS
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German, EasyList
* DNS: Off
* Optimized filters: Off

**Comment by Alex-302** [comment]
Fixed.
