### ISSUE TITLE
seanthurstonphotography.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#70605]
***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

Site is blanked out when opened with AdGuard protection enabled.

<details><summary>Screen Recording:</summary>

https://www.berrycast.com/conversations/70077824-0204-5c93-b7e6-ef0f28b9a9e3
</details><br/>

***Steps to reproduce the problem***:

Launch protection and open the website.

Filtering log journal available in helpdesk ID 1041989.

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox, Edge (Release)
AdGuard version:                       | 7.5.3
Filters enabled:                       | Base, Annoyances, French, Tracking Protection, Social media, German, Dutch
AdGuard DNS:                           | Default IPv4, no encryption
Stealth mode options (Windows only)    | Block 3rd-party cookies (180), Remove X-Client-Data header, Hide search queries, Send Do-Not-Track header
Helpdesk ID (if exists):               | 1041989

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Will check later on Windows app. Looks like no filters issue as with Chrome Extension I cannot reproduce with given config above (also indicated by exclusion rule in video).

**Comment by BlazDT** [comment]
Cannot reproduce on latest nightly. Can you please tell the user to export his settings, install nightly and then check again.
