### ISSUE TITLE
mixpanel.com - blocked by DNS

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#7061]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

The fact that you have a DNS running in AdGuard breaks the site. Works fine without DNS, doesn't work with Google DNS, AdGuard DNS, and others.

### Steps to reproduce

1. Go to https://mixpanel.com/blog/2017/09/13/ios-11-adoption/
2. See it blocked
3. Disable DNS
4. It works as expected

### Expected behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31169298-d11e9542-a900-11e7-9858-18c806246908.png)

</details>

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31169284-c7620f48-a900-11e7-995f-003fbf35af21.png)

</details>

### Your environment

* Operating system and version: 11.0.1
* Browser: Safari
* Wi-fi or mobile internet connection: Both I would guess
* AdGuard version: 1.3.1.107
* DNS: AdGuard Public DNS, Google Public DNS

**Comment by zebrum** [comment]
reproduced on android and mac with our DNS.

**Comment by Alex-302** [comment]
mixpanel.com - excluded from DNS filter.

**Comment by opav** [comment]
Please reinstate and continue to block mixpanel.com.  They are in the business of tracking - its front page clearly state : 

> "Understand every user's journey
> Follow the digital footprint of every user across mobile and web devices. Know precisely what happens inside your product. "

**Comment by Alex-302** [comment]
A lot of popular sites will be broken without this exclusion.
