### ISSUE TITLE
TubeMate ads

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#70626]
***Description***:
* **Current behaviour**: 

After the latest TubeMate update, AdGuard is no longer able to block ads in this application.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

Available in helpdesk id 1106547.
</details><br/>

***Steps to reproduce the problem***:

1. Download the app from https://tubemate-youtube-downloader.en.uptodown.com/android

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 10
Browser:                               | -
AdGuard version:                       | 3.6.1
Filters enabled:                       | "Tracking protection", "Experimental", "RU AdList: BitBlock", "NoCoin Filter List", "Russian", "Annoynces", "DNS filter", "Mobile ads", "Online Malicious URL Blocklist", "Spam404", "AdGuard base filter", "Useful ads", "Social media"
AdGuard mode (Android only):           | VPN 
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | Default
Helpdesk ID (if exists):               | 1106547

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Здесь не отфильтровать, т.к. фильтрация HTTPS не работает с этим приложением.
