### ISSUE TITLE
Ads on mail.ru

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7063]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: According to the customer, ads on mail.ru keep showing up.
Last filters update didn't help.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/14153331/31378602-8bcc43be-adb4-11e7-8be1-c441e1d022e3.png)

</details><br/>

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows NT 10.0
Browser:                            | Yandex
AdGuard version:                    | 6.2.424.2123
Filters enabled:                    | 2 3 1
Helpdesk ID (if exists):            | 1531542

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Поправил.

**Comment by Klimfedyakin** [comment]
не не исправно вновь реклама появляется
![default](https://user-images.githubusercontent.com/30592575/31382311-e3238504-adbf-11e7-851c-8342dd82ce61.png)

**Comment by Alex-302** [comment]
Обновление фильтров становится доступным через час после добавления. Обычно на 15-20й минуте следующего часа.

**Comment by Klimfedyakin** [comment]
ну вот типерь в полне в порядке работает как по маслу а вы классно потрудились спасибо а то первый вчера плохо пороботал над этим тяп ляп и готово

**Comment by Alex-302** [comment]
Вчера для этого сайта правил не добавлял.

**Comment by Klimfedyakin** [comment]
какие еще правил

**Comment by Klimfedyakin** [comment]
![default](https://user-images.githubusercontent.com/30592575/31613361-8c501758-b28b-11e7-975c-38cc67b6b8ce.png)
что ха фигня

**Comment by Klimfedyakin** [comment]
уберите рекламму

**Comment by Alex-302** [comment]
Не повторяется.
@zebrum проверь у себя.

**Comment by Klimfedyakin** [comment]
каким образом проверить если уменя показывает реклама дату и время посматрите а на скришоте

**Comment by Klimfedyakin** [comment]
![default](https://user-images.githubusercontent.com/30592575/31625102-89abba26-b2ad-11e7-89dc-0202782a07fa.png)

**Comment by Alex-302** [comment]
завтра на другом компе проверю.

**Comment by Klimfedyakin** [comment]
проверяйте

**Comment by Klimfedyakin** [comment]
только на яндекс браузере тоже проверте

**Comment by Klimfedyakin** [comment]
![default](https://user-images.githubusercontent.com/30592575/31664746-656a2ca4-b34f-11e7-9ea8-4c8fce5464b2.png)
в браузере edge тоже реклама

**Comment by Alex-302** [comment]
Не повторяется даже с расширением. Можете сохранённую страницу(HTML с ресурсами) выложить? Только не авторизуйтесь на сайте.

**Comment by Klimfedyakin** [comment]
а как это делается и что такое HTML

**Comment by Klimfedyakin** [comment]
и может такое быть что у меня еще подкдючин adguard dns в роутере установлен может быть такое проверте сами

**Comment by Klimfedyakin** [comment]
потому что у меня два подключино один dns другой приложения

**Comment by Klimfedyakin** [comment]
как это делается

**Comment by Alex-302** [comment]
в браузере нажмите сочетание клавиш `Ctrl+S`. Появится окно сохранения.

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/31684829-a6373512-b389-11e7-9a7b-f6ee4159fc12.png)

**Comment by Klimfedyakin** [comment]
а тут написано не подерживает формат как отправить вам

**Comment by Alex-302** [comment]
на любой файлообменник
можно upload.ee

**Comment by Klimfedyakin** [comment]
https://cloud.mail.ru/public/9fzG/vGqn88UUb

**Comment by Klimfedyakin** [comment]
а вторую папку тоже отправлять вам

**Comment by Alex-302** [comment]
Там файл и папка. Заархивируйте и залейте на обменник.

**Comment by Klimfedyakin** [comment]
https://cloud.mail.ru/public/2W3v/Rd5hpF81U

**Comment by Klimfedyakin** [comment]
отправил надеюсь мои данные там нету случайно ато пока я вам отправляю а кто то другой скачивает

**Comment by Alex-302** [comment]
Скачал. Можете удалить.

**Comment by Klimfedyakin** [comment]
спасибо

**Comment by Klimfedyakin** [comment]
удалил

**Comment by Klimfedyakin** [comment]
![png1](https://user-images.githubusercontent.com/30592575/31691747-ceec6192-b39f-11e7-8c83-2793f5ef1e33.png)
что за фигня что происходит с adguard что не так что делает я не понимаю переустановил его больше нечего ниделал удалил 6.2 установил 6.1 гдета реклама выползают а где то  белое почему происходит так что за глюки у меня происходит в чем причина

**Comment by Klimfedyakin** [comment]
это что издевательсто

**Comment by Alex-302** [comment]
Яндекс борется с блокировщиками рекламы.

**Comment by Klimfedyakin** [comment]
ну не датокой степени  удалять там небыло сроду рекламы аткудва реклама там быть вот между прочим если они борятся с  блокировщиками рекламы онибы не встраивали в свой браузер ваш приложение а ваш приложение не возможно удалить так встроенный 
![default](https://user-images.githubusercontent.com/30592575/31692731-b92e1c8e-b3a3-11e7-9bb4-1c75756aff3a.png)

**Comment by Klimfedyakin** [comment]
я переустановил виндовс все заново скачал реклама на майл ру . попрежнему а яндекс востановился  работает коректно

**Comment by Alex-302** [comment]
> онибы не встраивали в свой браузер ваш приложение
кроме Адгарда существует множество других блокировщиков. Им без разницы с кем бороться.

**Comment by Alex-302** [comment]
Попробуйте добавить это правило в пользовательский фильтр
`mail.ru##.layout__centercol > .layout__centercol__wrap div[class][id] >div[class][-ext-has="> span[class]+span[class]:contains(Реклама)"]`
![image](https://user-images.githubusercontent.com/8361299/31712840-ec2af5ec-b404-11e7-89a3-e20c251fcdde.png)

**Comment by Klimfedyakin** [comment]
тоже самое

**Comment by Alex-302** [comment]
Тогда удалённо нужно смотреть.

**Comment by Klimfedyakin** [comment]
согласен я знаю что такое удаеленое есть у меня уже установил

**Comment by Klimfedyakin** [comment]
169 568 000 ид  7916

**Comment by Klimfedyakin** [comment]
уже подключон

**Comment by Klimfedyakin** [comment]
жду

**Comment by Klimfedyakin** [comment]
зто наверное не яндекс а майл ру занимается ерундой это майл против блокировщиков

**Comment by Klimfedyakin** [comment]
на всех других сайтах впорядке у меня

**Comment by Alex-302** [comment]
да, mail.ru и яндекс в последнее время зверствуют

**Comment by Klimfedyakin** [comment]
да но вы это вопрос решите надеюсь

**Comment by aadguard** [comment]
уберите чертовую рекламу

**Comment by aadguard** [comment]
эй ау уснули что ли

**Comment by Klimfedyakin** [comment]
ты еще откудва взялся

**Comment by Klimfedyakin** [comment]
Алекс-302 я незнаю как но у меня рекламы исчезли просто ну если вы нечего ни делали то я сам русский фильт отключил и реклама исчезла а потом сам автоматический включился но некоторые фильтры не фключились все перепробывал ну 10 раз перезагрузить браузер 10 перезагружал комп все равно не появляются рекламы проблемы наверное с руским фильтром было и стабильно работает

**Comment by Klimfedyakin** [comment]
@@||chaosroad.com^$document вот этот филтр мешал скарей всего мешал он у меня просто отключил и рекламы исчезли

**Comment by Alex-302** [comment]
Ну ок тогда. Хотя странно, это правило для другого сайта.

**Comment by Klimfedyakin** [comment]
Алекс-302 нет я ошибся  я потом включил все равно нет рекламмы просто надо атключить фильты и заново вклучится автоматический и тогда рекламы сразу у берутся если какойто реклама не убрался просто потом повторно надо нажать заблокировать рекламу на сайте выбрать метку где максимально и минимальный 2 галочки поставить тогда полнастью исчезнут

**Comment by Klimfedyakin** [comment]
скриншот пришлю

**Comment by Klimfedyakin** [comment]
![default](https://user-images.githubusercontent.com/30592575/31886285-5f365f7c-b7fc-11e7-851e-0e58667898d0.png)

**Comment by Klimfedyakin** [comment]
это пример но это надо на mail.ru делать

**Comment by Klimfedyakin** [comment]
у меня так заработал еще яндекс хитрый способ придумал уних новый способ абманывать но его не надо одновремено включать если влючон вскрыть мешающю рекламу то появятся реклама вновь и замочик должен закрыт если открыт то вновь появится реклама я вчера целых три часа ттрудился и устранил проблему

**Comment by Klimfedyakin** [comment]
![1](https://user-images.githubusercontent.com/30592575/31886585-9b891e8c-b7fd-11e7-8b41-ae901f2eeb89.png)

**Comment by Klimfedyakin** [comment]
ну вот как совчерашнего дня нет рекламы ну вот на этом все спасибо за внимание всего доброва
![default](https://user-images.githubusercontent.com/30592575/31886925-13d0b6ec-b7ff-11e7-9f09-26fdf25155de.png)

**Comment by Klimfedyakin** [comment]
красиво правдо

**Comment by aadguard** [comment]
о круто спасибо Klimfedyakin  тоже получилось, может  попросишся к ним на работу

**Comment by Klimfedyakin** [comment]
aadguard ты не настоящий верно я говарю я еще раз гаварю откудва ты взялся

**Comment by Klimfedyakin** [comment]
![png1](https://user-images.githubusercontent.com/30592575/31968023-7556bcc6-b918-11e7-9a2a-8909f481276f.png)
здраствуй Алекс-302 прошу прощения за бесапокойства я в прошлый раз ошибся но я нашол доказательство можеш сам проверить он у меня в новь реклама появился на браузерах но я тибе помог найти а тибе только решить броблему сам можеш проверить и скринщот посмотри обезатель когда галочки стаят рекламы появляютя на майл ру когда снимаеш реклама исчезает в прошлый раз чистый случайно у меня так получился исправь или удали пожалуста тибе все благодарны будут
![default](https://user-images.githubusercontent.com/30592575/31968018-702a77e2-b918-11e7-8dac-cadcf4e7cdac.png)

**Comment by Klimfedyakin** [comment]
это находится в руском фильтре

**Comment by Alex-302** [comment]
Проблема в том, что повторить не удаётся, ни мне ни коллегам. Пока придердите правила выключенными. Скоро будет релиз версии 6.2, там уже посмотрим.

**Comment by Klimfedyakin** [comment]
у меня уже установлен 6.2  ано какрас и выдает ошибку но я покачто так буду пользоватся но другие люди могут мучится мне как то без разните  но уц меня вот так ошибка выевил сперва набрал в поисковике mail потом со всех начил снимать галочки и по одному начил устанавливать галочки и выдал три штуки первый выдает рикламу в торой замочик открыввает и закрывает а трети я не помню но я долго работал над ошибками  вчера весь день  я вам передал вам и решать  без обид

**Comment by Klimfedyakin** [comment]
хорошо, это я только на яндекс браузере проверял на других браузерах не проверял потому что я пользуюсь только этим браузером а другие браузера меня не интересуют и огромное спасибо что откликнулись

**Comment by Klimfedyakin** [comment]
![default](https://user-images.githubusercontent.com/30592575/32115992-e6fef0d0-bb59-11e7-8c7d-0f72209a0c06.png)
в майл ру обращался спрашивал почему у вас много рекламы уних обновление оказывается происходили вот и реклама было у них был такой а типерь такой стал 
![31886925-13d0b6ec-b7ff-11e7-9f09-26fdf25155de](https://user-images.githubusercontent.com/30592575/32115956-c3ba515a-bb59-11e7-800e-36fa51b7ed28.png)

**Comment by Klimfedyakin** [comment]
фильтры ваши не причем уже я включил уже и рекламы больше не идут
