### ISSUE TITLE
https://ipleer.fm/ - Missed Ads

### ISSUE THREAD

**Issue by Yana-SUP** [AdguardTeam/AdguardFilters#7064]
Go to: https://ipleer.fm/q/dj+smash+dj+smash+moscow+never+slips+%D1%8F+%D0%BB%D1%8E%D0%B1%D0%BB%D1%8E+%D1%82%D0%B5%D0%B1%D1%8F+%D0%BC%D0%BE%D1%81%D0%BA%D0%B2%D0%B0/

![image](https://user-images.githubusercontent.com/22892774/31385141-b9d78ab4-adca-11e7-9d99-196c17059ac6.png)

Information                         | Value
---                                 | ---
Operating system:                   | Android
Browser:                            | Chrome
AdGuard version:                    | 2.10.108
Filters enabled:                    | 1 2 3 4 5 14
AdGuard mode (Android only):        | VPN 
Filtering quality (Android only):   | High-quality
HTTPS filtering (Android only):     | On 
Helpdesk ID (if exists):            | 1643608

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
