### ISSUE TITLE
hardwareluxx.de - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7065]
https://www.hardwareluxx.de/index.php/news/software/anwendungprogramme/44566-pixelmator-bekommt-unterstuetzung-fuer-heif-bildformat-in-macos-high-sierra.html

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/31389108-b8dac7c6-add8-11e7-81c0-61f14ea90d5c.png)

</details><br/>

***System configuration***
Application version: 1.3.1.107
Device: iPad
Platform: iOS
OS: 11.0.2

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.32.36 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.77 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.80 Enabled=YES
ID=6 Name="German filter" Version=1.0.37.2 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.64 Enabled=YES
 Mobile ads filter
Helpdesk ID:            1643810

**Comment by Alex-302** [comment]
Can't reproduce. Please check:
@@||hardwareluxx.de/images/temp/ad_dir/

**Comment by ministr91** [comment]
У меня тоже нет рекламы сверху

**Comment by danidoedel** [comment]
@Alex-302 Still able to reproduce these ads on this site and most of the sites in this rule (seem to be the same ads? maybe the rule needs some tweaking?): https://github.com/AdguardTeam/AdguardFilters/blob/c4d4da4425d0765a155ab6e7b0930ebb2121fad5/GermanFilter/sections/antiadblock.txt#L5

**Comment by Alex-302** [comment]
@veronikasav

**Comment by veronikasav** [comment]
@Alex-302 уже нет рекламы сверху.

**Comment by Alex-302** [comment]
ok
