### ISSUE TITLE
golem.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#70666]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Anti Adblock
`https://www.golem.de/news/gaming-kfc-stellt-konsole-mit-haehnchen-warmhaltekammer-vor-2012-153016.html`
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="747" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/102998993-8bb78280-4528-11eb-8203-1cd927b6f8ac.PNG">

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.25
Filters enabled:                       | default + Adguard Germany + Adguard Tracking Protetion + Adguard Annoyances
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Can only reproduce if I disable Annoyances filter which whitelists this url:
https://www.golem.de/bannertest/iqdigital/dist/show_ad.js

Please check @AdguardTeam/filters-maintainers

**Comment by stanislav-atr** [comment]
@BlazDT, not reproduced with Annoyance filters both on and off, german IPs.

**Comment by zloyden** [comment]
Also not reproduced on my end with German IP.

**Comment by JobcenterTycoon** [comment]
Yes whitelisting `golem.de/bannertest/iqdigital/dist/show_ad.js?` works for me 

And i see there are ads at the bottom
<details>
<summary> screenshot: </summary>
<img width="775" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/103007953-9a0b9b80-4534-11eb-9f44-783cd2873404.PNG">
</details>

**Comment by BlazDT** [comment]
Rule to whitelist is in Annoyances filter, as mentioned. So either installed filter is outdated or is not getting applied correctly for you.

I also do not see those ads.

**Comment by JobcenterTycoon** [comment]
ok looks like a bug. Im reinstalled Firefox now its fixed
