### ISSUE TITLE
Danish Adblock list for Android app

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7066]
Could you please add the most used Danish Adblock list? Would be nice
not to have to update manually :) URL: https://adblock.dk/block.csv
Info (in Danish though): https://henrik.schack.dk/adblock/

Ticket ID: 1615231

**Comment by Alex-302** [comment]
Filter name: `Schacks Adblock Plus liste`
![image](https://user-images.githubusercontent.com/8361299/31397289-48c37f12-adee-11e7-92e9-527952a0359e.png)

**Comment by andreastjerry** [comment]
This is the second time I've posted this. It's not in the android app, I've looked through the list close to a 100 times now (yes, I'm a bit obsessive). 

It might be on Windows, not sure as I don't use it.
