### ISSUE TITLE
Kate mobile

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#7067]
Фильтры по-умолчанию, версия последняя стабильная, HTTPS, HTTP вкл, качественная.
Kate Mobile Android 4.4.4 http://my-files.ru/ckeg2j 18:22 вторник 
![screenshot_2017-10-10-18-22-58](https://user-images.githubusercontent.com/22351242/31395201-7c8eaee2-ade0-11e7-8eef-540f6f0e4db5.png)

**Comment by ministr91** [comment]
@Alex-302 @ameshkov

**Comment by Alex-302** [comment]
Без интернета после очистки кэша появляется?

**Comment by ministr91** [comment]
Без интернета баннера нет. Кэш чистил

**Comment by Alex-302** [comment]
У меня блокируется. У тебя, судя по логу, тоже должно.
Проверь такое:
```
||ad.mail.ru^$app=com.perm.kate|com.perm.kate_new_6
```

**Comment by ministr91** [comment]
Само прошло
