### ISSUE TITLE
Unblocked analytic script

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#70681]
https://www.dunya.com/sektorler/turizm
<details>
 <summary>IMG</summary>

 
![Adsız](https://user-images.githubusercontent.com/74098460/103019602-2e3b2a00-4558-11eb-8b07-3727ebfca907.png)

</details>

```
Filters: Base-Annoyance-Social-Tracking Protection-Turkish 
Browser: Chrome 87  
AdGuard Browser Extension 3.5.31 
Win 10
```

**Comment by Alex-302** [comment]
Cannot reproduce. It is blocked by blocking of initial script from google-analytics.com
