### ISSUE TITLE
https://touch.otvet.mail.ru/answer/68615914

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#7068]
Фильтры по-умолчанию, версия 2.9.7.0, HTTPS вкл, HTTP вкл, качественная Фильтрация.
18:59 вылезла нижняя, а на 19:00 верхняя. 10 октября
http://my-files.ru/hrz1j8

**Comment by ministr91** [comment]
![screenshot_2017-10-10-19-00-22](https://user-images.githubusercontent.com/22351242/31397221-bc596634-ade5-11e7-9f91-39a443c825c0.png)

**Comment by ministr91** [comment]
@Alex-302 @ameshkov

**Comment by Alex-302** [comment]
Проверь через час обновление.

**Comment by ministr91** [comment]
Хорошо, в этот раз тебе повезло, проблема решилась
