### ISSUE TITLE
mybank.oplata.kykyryza.ru - Blank page - iOS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7069]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Верхний пустой экран это с включённой программой.
Добавил сайт в белый список но ничего не меняется
Нижний экран это как должно быть

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/31417737-346b249c-ae3a-11e7-97cd-5c1c1e885c0a.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/31417745-4598427c-ae3a-11e7-9e7d-c6a480c4cce4.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.32.99 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.87 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.58.1 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.1 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.67 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Device:  | iPad
Operating system:                   | 11.0.2
Browser:                            | Safari
AdGuard version:                    | 1.3.1.82
Simplified filters (iOS only)       | Off
Helpdesk ID (if exists):            | 1643940

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
@iverkhohliad 
передай на проверку
```
@@||mybank.oplata.kykyryza.ru^$document
```

**Comment by veronikasav** [comment]
Передали

**Comment by Alex-302** [comment]
Добавил.
