### ISSUE TITLE
https://www.womenshealth.de/ - Ad leftover/Cookie notice

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7074]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Ad leftover. Cookie notice at the bottom

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

 
![image](https://user-images.githubusercontent.com/31481372/31418351-3f968240-ae3e-11e7-9911-11acd9e97be2.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.33.22 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.89 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.9 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.51 Enabled=YES
ID=6 Name="German filter" Version=1.0.37.18 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.3 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.68 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information | Value
-- | --
Operating system: | iOS
Browser: | Safari
AdGuard version: | 1.3.2.108
Simplified filters (iOS only) | Off
AdGuard DNS: | Default
Helpdesk ID (if exists): | 1480792

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Cookie notice fixed, but I can't hide this ad leftover on iOS, because this element has the same name like others.
