### ISSUE TITLE
http://www.internethaber.com/ iOS Incorrect Blocking 

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7076]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Site:*** http://www.internethaber.com/

***Description***: Adguard blocks all news in slider
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image1](https://user-images.githubusercontent.com/32528702/31423427-63bb76de-ae5d-11e7-8571-ac151c5b38a6.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image2](https://user-images.githubusercontent.com/32528702/31423452-991cb87e-ae5d-11e7-94a6-fa7792aca29f.png)

</details><br/>

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**
User filter
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
Turkish filter
Mobile Ads filter
Safari filter

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS 11.0.2
Browser:                            | probably, Safari
AdGuard version:                    | 1.3.1.82
Filters enabled:                    | 0 2 3 4 14 6 13 11 12
Simplified filters (iOS only)       | ?
Helpdesk ID (if exists):            | 1638014

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
