### ISSUE TITLE
is.gd

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#70768]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Scam site (fake Amazon)
URL: `https://is.gd/amaznSUPROT` => `https://www-amzaon-create-address.world-page-back-stage-asia.buzz/pc/`

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![scam1](https://user-images.githubusercontent.com/58900598/103098743-3e820080-464f-11eb-8a07-21f17cecd7fb.png)

</details><br/>

***Steps to reproduce the problem***:

Visit the site

***System configuration***

**Filters:**

Base + Tracking

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win 10
Browser:                               | Brave 1.18.75
AdGuard version:                       | 3.5.31
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Disabled
Helpdesk ID (if exists):               | ?

**Comment by Yuki2718** [comment]
@lolka4toli

**Comment by Sergey-Lyapin** [comment]
@Yuki2718
looks like this site is dead
