### ISSUE TITLE
Missed ad on jeuxvideo.com

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7079]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
http://www.jeuxvideo.com/forums/42-1000021-53411843-1-0-1-0-arrivee-d-un-nouveau-stagiaire-presentation-rapide.htm

***Description***: Missed ad

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image2](https://user-images.githubusercontent.com/32528702/31427226-3506a52c-ae6f-11e7-812b-d5160070eb9a.jpeg)

</details><br/>

***System configuration***

**Filters:**
User filter
English filter
Spyware filter
Social media filter
French filter
Safari filter

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS 11.0.2
Browser:                            | Safari
AdGuard version:                    | 1.3.1.107
Filters enabled:                    | 0 2 3 4 16 12
Simplified filters (iOS only)       | Off
Helpdesk ID (if exists):            | 1641340

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to Mobile filter
```
jeuxvideo.com##.conteneur-messages-pagi > div[style]:not([class^="bloc-"]):not([id^="bloc-"])
jeuxvideo.com##.conteneur-messages-pagi > a[style*="position: relative; margin:"]
```
