### ISSUE TITLE
http://dugtor.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7082]
Missed ads.

### Steps to reproduce

1. Turn on the extension
2. Make sure to have filters specified below
3. Go to http://dugtor.ru/programmy/os/windows-10/47261-windows-10-enterprise-ltsb-2016-v1607-x86-x64-by-lex_6000-17092017-ru.html
4. See banners on the right side of the main view

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31435353-f0490e52-ae87-11e7-991f-a04c9c535117.png)

</details>

### Your environment

* Adguard version: Extension for Chrome, both updated to the most recent versions
* Subscriptions: English, Russian, Social media, Annoyances,
* DNS: Off

**Comment by Alex-302** [comment]
Fixed.
