### ISSUE TITLE
http://kino-sayt.net/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7083]
Missed ads.

### Steps to reproduce

1. Turn on the extension
2. Make sure to have filters specified below
3. Go to http://kino-sayt.net/dir/trillery/igra_dzheralda_2017/1-1-0-13734
4. See banners on the right side of the main view

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31435422-253d613a-ae88-11e7-9ece-ad508a8b0500.png)

</details>

### Your environment

* Adguard version: Extension for Chrome, both updated to the most recent versions
* Subscriptions: English, Russian, Social media, Annoyances,
* DNS: Off

**Comment by Alex-302** [comment]
Not reproduced.
Browser? Extension version?

**Comment by evgeniy-ADG** [comment]
Хром Version 61.0.3163.100
AdGuard 2.7.2

**Comment by Alex-302** [comment]
А можешь HAR прислать?
https://toolbox.googleapps.com/apps/har_analyzer/?lang=ru
сперва повтори проблему с открытими dev tools перед сохранением.
