### ISSUE TITLE
http://only-tv.org/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7084]
Missed ads.

### Steps to reproduce

1. Turn on the extension
2. Make sure to have filters specified below
3. Go to http://only-tv.org/
4. See banners on the right side of the main view

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31435487-5beb627c-ae88-11e7-8e58-dcb7f1fdeb44.png)

</details>

### Your environment

* Adguard version: Extension for Chrome, both updated to the most recent versions
* Subscriptions: English, Russian, Social media, Annoyances,
* DNS: Off

**Comment by Alex-302** [comment]
Пусть попробует переустановить. Поможет - закрой задачи.
