### ISSUE TITLE
github.com (False positive)

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#70876]
I want to whitelist the rule because it is blocking access to the `antiadblock.txt `file. I'm not sure how to create the valid rule.

<details>
 <summary>IMG</summary>

 
![image](https://user-images.githubusercontent.com/74098460/103142754-27f4ab80-471a-11eb-9706-8ce639fe0ee6.png)

</details>

```
Filters: Base-Tracking Protection-Social-Annoyance-Turkish 
Browser: Chrome 87  
AdGuard Browser Extension 3.5.31 
Win 10
```

Video:

https://streamable.com/vt47oa

**Comment by Alex-302** [comment]
Thanks, fixed.

**Comment by DandelionSprout** [comment]
https://github.com/AdguardTeam/AdguardForWindows/issues/3570 is closely related, but would require a whitelisting of `raw.githubusercontent.com` instead of just `github.com`
