### ISSUE TITLE
Why is Adguard Spyware Filters whitelisting google-analytics.com/ga.js ?!!

### ISSUE THREAD

**Issue by AdKiller** [AdguardTeam/AdguardFilters#7089]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
I always block google-analytics.com in uBlock but noticed that after enabling Adguard Spyware Filters, google-analytics.com is whitelisted! why is that?

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>google-analytics should not be whitelisted</summary>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   |  Win 10 
Browser:                            |  Firefox 52.4.0
AdGuard version:                    |  Title: Spyware filter
**Description: The most comprehensive list of various online counters and web analytics tools. If you do not want your actions on the Internet to be tracked, use this filter.**
Version: 1.0.14.89
TimeUpdated: 2017-10-10T03:00:31.750+04:00

**Comment by Alex-302** [comment]
/ga.js is whitelisted on some sites to prevent breaking the site(for example, buttons). But requests from this stript are blocked.
