### ISSUE TITLE
gsbal.ru - incorrect blocking

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#7090]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
> При использовании adguard таблица для передачи данных не загружается, приходится останавливать фильтрацию всех сайтов. При этом просто добавить сайт в исключение не спасает ситуацию.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/31502047-9ce8f892-af74-11e7-80ae-2eecf1cee59c.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/31502078-b8b51cf4-af74-11e7-8387-05a5b775736f.png)

</details><br/>

***Steps to reproduce the problem***:
[http://gsbal.ru/meters/](http://gsbal.ru/meters/)

***System configuration:***
Ticked id: 1644876

User's diagnostic report has been requested. Will be added as soon as available.

**Comment by Alex-302** [comment]
Похоже на баг проги.
