### ISSUE TITLE
Missed ads in mail.yandex.ru

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7092]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Ads in http://mail.yandex.ru/

* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/32528702/31536487-7361594a-b007-11e7-8e97-e2bc7684d88b.png)
![2](https://user-images.githubusercontent.com/32528702/31536485-7327c91e-b007-11e7-8433-86561993ef2d.png)
![3](https://user-images.githubusercontent.com/32528702/31536486-7343333e-b007-11e7-94a4-f65c33a06d27.png)
</details><br/>

**Filters:**
English filter
Russian filter
Spyware filter 
Annoyances filter 

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows NT 10.0
Browser:                            | Vivaldi / IE
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 1 2 3 14
Helpdesk ID (if exists):            | 1374004

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не повторяется. Пусть 6.2 попробует. Но и 6.1 тоже должна блокировать.
Нужен скриншот с настройками вида почты, может от этого что-то зависит.

**Comment by ashvets-sup** [comment]
[customer]:
К сожалению, ни бета, ни другая тема не
помогли.

 
Не то чтобы проблема была совсем
неприемлемой - на всех (!) остальных
сайтах, включая главную Яндекса,
блочит - если не сам, то хоть после
ручной блокировки. Но я не понимаю что
творится и почему один сайт при любых
настройках суёт мне эту гадость.

![4](https://user-images.githubusercontent.com/32528702/31799321-148b0c46-b542-11e7-808f-3a564fc4afea.png)

**Comment by Alex-302** [comment]
Прога точно должна блокировать эту рекламу(т.е. удалять физически). Попробуйте в настройках почты -> Прочее отключить рекламу. Или воспользуйтесь другим адресом - mail.yandex.com - здесь у меня нет рекламы даже без Адгарда.

**Comment by Alex-302** [comment]
@ashvets-sup

**Comment by ashvets-sup** [comment]
[customer]:
Отключил. А так можно было?
