### ISSUE TITLE
Pioneer.eu - Broken (AdGuard Tracking Protection filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#70941]
### Affected site:
`https://www.pioneer.eu/`

### Issue:
No matter what you click on, nothing happens!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **AdGuard Tracking Protection filter**

### Problem rule:
`||googletagmanager.com/gtm.js?$third-party`

### Blocked script:
`https://www.googletagmanager.com/gtm.js`

### Possible fix:
`@@||googletagmanager.com/gtm.js$domain=pioneer.eu`

### Other problem filters:
* ~~**EasyPrivacy** https://github.com/easylist/easylist/issues/6845/~~ _(FIXED)_
~~`/gtm.js`~~

* **hpHosts - Ad and Tracking servers only** _(DISCONTINUED)_
`googletagmanager.com`
`www.googletagmanager.com`

* **Peter Lowe's Ad and tracking server list** _(NOTIFIED)_
`googletagmanager.com`

* ~~**uBlock filters - Privacy** https://github.com/uBlockOrigin/uAssets/issues/8408/~~ _(FIXED)_
~~`||googletagmanager.com/gtm.js$script,redirect=googletagmanager.com/gtm.js`~~

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.17.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.27 (XUL)

**Comment by krystian3w** [comment]
Possible use scriptlet:

```
pioneer.eu#%#//scriptlet('remove-attr', 'onclick', 'a[href][onclick^="trackOutboundLink"]')
```

and allow load file for only:

- iOS / iPadOS ("content blocker")
- Android Content Blocker
- maybe AdGuard Safari addon (to avoid problems like "race-condition" or fail run scriptlet)
