### ISSUE TITLE
Adguard+Firefox Android\PC+Yandex search

### ISSUE THREAD

**Issue by Alexey71** [AdguardTeam/AdguardFilters#7095]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: В поисковых запросах, рядом с найденными ссылками, нету стрелочки

<details><summary>Screenshot:</summary>

![2017-10-14 13_58_07](https://user-images.githubusercontent.com/10572914/31575165-0466199e-b0e9-11e7-8bc2-80f1d3c9f71d.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![2017-10-14 13_58_30](https://user-images.githubusercontent.com/10572914/31575173-1d16ace2-b0e9-11e7-8bce-4fe647921764.png)

</details><br/>

***Steps to reproduce the problem***:

Установить Firefox на android или PC

***System configuration***

**Filters:**

Английский-Русский-Фильтр счетчиков и аналитики-Фильтр виджетов и сетей-Фильтр раздражителей-Экспериментальный фильтр

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Firefox 56 x64
AdGuard version:                    | 6.2.424.2123
Filters enabled:                    | Английский-Русский-Фильтр счетчиков и аналитики-Фильтр виджетов и сетей-Фильтр раздражителей-Экспериментальный фильтр

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Передай на пробу
```
||yastatic.net/web4/_/*.js$replace=/probeClass:".+"\,probeId:".+"\,probeStyle:".+"\,/probeClass:null\,probeId:null\,probeStyle:null\,/,domain=yandex.by|yandex.com.tr|yandex.kz|yandex.ru|yandex.ua
```

**Comment by Alexey71** [comment]
Не помогло

**Comment by Alex-302** [comment]
Вкладку несколько раз обновлял? Они в куки метку пишут.
А так?
```
@@||yandex.ru^$generichide
```

**Comment by Alexey71** [comment]
Второе не помогает. Первое еще раз проверил, через приватное окно с чистыми куками. Стрелочки есть, но не жмутся.
Должно быть при нажатии такое 
![2017-10-16 19_46_20](https://user-images.githubusercontent.com/10572914/31624268-ca711324-b2aa-11e7-88a0-9d85d0d2efeb.png)

**Comment by Alex-302** [comment]
Там, похоже, только два варианта - либо созерцать рекламу и кнопку, либо отсутствие рекламы и кнопки.

**Comment by Alexey71** [comment]
Тогда за отсутствие рекламы и кнопки.

**Comment by Alexey71** [comment]
Еще один баг
https://yandex.ru/search/?lr=10827&msid=1508406661.89486.22880.2357&text=%D0%B4%D0%BE%D0%BB%D0%BB%D0%B0%D1%80&suggest_reqid=66008213224864808666648025764217
При вводе любого числа не считает автоматом курс
![2017-10-19 12_52_33](https://user-images.githubusercontent.com/10572914/31765246-6ea68244-b4cc-11e7-9430-d26ec8533df3.png)

**Comment by Alex-302** [comment]
А у меня переводит. Странно.

**Comment by Alexey71** [comment]
Ах, у меня правило было включено из твоего первого поста. Теперь нормально. Так значит закрывать тему то?. Если не получается стрелочки)

**Comment by Alexey71** [comment]
Поставил Firefox 57, проблема решена, есть стрелочки и менюшки
