### ISSUE TITLE
https://pb.wtf/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7096]
Missed ads.

### Steps to reproduce

1. Go to https://pb.wtf/
2. See ads

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31578197-08e2c3dc-b125-11e7-8331-d80bbd4c44cd.png)

</details>

### Your environment

* Adguard version: 1.5.0 for macOS
* Reproduced also with the Extension for Chrome with the same filters set
* Subscriptions: English, Russian, Social media, Annoyances,
* DNS: Off

**Comment by Alex-302** [comment]
Fixed.
