### ISSUE TITLE
http://viks.tv/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7097]
Missed ads.

### Steps to reproduce

1. Go http://viks.tv/523-discovery-science.html
2. See ads

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31578231-a43247ae-b125-11e7-9a5b-5cdbb355ed43.png)

</details>

### Your environment

* Adguard version: 1.5.0 for macOS
* Reproduced also with the Extension for Chrome with the same filters set
* Subscriptions: English, Russian, Social media, Annoyances,
* DNS: Off

**Comment by Alex-302** [comment]
fixed
