### ISSUE TITLE
app.adjust.com - Anti Adblock

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7099]
https://app.adjust.com/43kdm7?fallback=https://itunes.apple.com/us/app/stormbound-kingdom-wars/id1234446615&campaign=2017_09_22-Stormbound-Free-All-S&adgroup=MobileWeb_FeaturedGame

<details><summary>Screenshot:</summary>

<img width="457" alt="screen shot 2017-10-15 at 4 51 05 am" src="https://user-images.githubusercontent.com/27292111/31580872-82d5bb60-b164-11e7-9dec-65bfb374cc17.png">

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPhone
Platform: iOS
OS: 11.0

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.31.52 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.63 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.50 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.72 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.79 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.62 Enabled=YES
ID=101 Name="EasyList" Version=1.0.75.63 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.75.83 Enabled=YES
ID=215 Name="Fanboy's Enhanced Tracking List" Version=1.0.5.10 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.88.7 Enabled=YES
ID=214 Name="ABPVN List" Version=1.0.4.74 Enabled=YES
ID=226 Name="Fanboy's Vietnamese" Version=1.0.0.4 Enabled=YES

Helpdesk ID:           1634113

**Comment by Alex-302** [comment]
Fixed.
