### ISSUE TITLE
snopes.com - Anti Adblock

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7100]
http://www.snopes.com/photos/advertisements/wd40ad.asp

<details><summary>Screenshot:</summary>

<img width="1050" alt="screen shot 2017-10-15 at 5 45 14 am" src="https://user-images.githubusercontent.com/27292111/31581154-0ff85398-b16c-11e7-80dd-dd315e11b868.png">

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPad
Platform: iOS
OS: 11.0.2

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.32.20 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.73 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.74 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.3 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.88 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.63 Enabled=YES
ID=101 Name="EasyList" Version=1.0.75.87 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.88.23 Enabled=YES
ID=123 Name="Fanboy's Social Blocking List" Version=1.0.75.86 Enabled=YES
ID=122 Name="Fanboy's Annoyances" Version=1.0.76.6 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.88.45 Enabled=YES

Helpdesk ID:           1642779

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to English filter
```
@@||snopes.com/photos/advert*/*.asp
```
