### ISSUE TITLE
sueddeutsche.de - Anti Adblock

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7101]
http://www.sueddeutsche.de/adblock

<details><summary>Screenshot:</summary>

<img width="1162" alt="screen shot 2017-10-15 at 6 50 51 am" src="https://user-images.githubusercontent.com/27292111/31581457-542b6ec0-b175-11e7-9a6b-4d5f2cfd4031.png">

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPad
Platform: iOS
OS: 11.1

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.32.91 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.87 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.35 Enabled=YES
ID=6 Name="German filter" Version=1.0.37.14 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.67 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.64.34 Enabled=YES

Helpdesk ID:        1644629

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
I can't reproduce.

**Comment by veronikasav** [comment]
@AdamWr I will ask for another link

**Comment by veronikasav** [comment]
Another customer has the same issue, asked for the link

Ticket ID: 1657377

**Comment by Alex-302** [comment]
@AdamWr

**Comment by AdamWr** [comment]
I still can't reproduce with German filter enabled. I see that anti adblock message if I disable German filter.
