### ISSUE TITLE
Won't show video http://www.filma24.tv/

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7102]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

http://www.filma24.tv/finds-friend-finds-treasure-1981/

***Description***: Adblock warning

* **Current behaviour**: 
The window where the video should be is blank, showing the following text:
 **The publisher of this file doesnt allow adblock, please disable and reload !**

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![screen shot 2017-10-15 at 7 33 08 am](https://user-images.githubusercontent.com/32528702/31581820-2614fe78-b17c-11e7-9e7b-cf5726b891e7.png)

</details><br/>

***System configuration***

**Filters:**
English filter
Russian filter
Spyware filter
Social media filter
Annoyances filter
Adblock warning removal list

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | MacOS
Browser:                            | Chrome
AdGuard version:                    | 1.5.0
Helpdesk ID (if exists):            | 1616615

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced.

**Comment by AdamWr** [comment]
I can't reproduce.
I think it was fixed here - `https://github.com/easylist/easylist/commit/4725f61b64259edaa2be4fca5ffae44ee3fa8308`
