### ISSUE TITLE
Spotify Mac Client missed ads. 

### ISSUE THREAD

**Issue by jimmysofat6864** [AdguardTeam/AdguardFilters#71036]
Spotify for mac has missed ads. All filters are updated and using latest version of both client and of adguard. 
![Screen Shot 2020-12-27 at 5 01 25 PM](https://user-images.githubusercontent.com/69532417/103183129-719ddd00-4865-11eb-9a53-af2baa09635d.png)

**Comment by Alex-302** [comment]
@jimmysofat6864 Hi. Could you please open filtering log, restart this app and reproduce ad, and make screenshot of the filtering log?

**Comment by jimmysofat6864** [comment]
![Screen Shot 2021-01-19 at 7 43 21 PM](https://user-images.githubusercontent.com/69532417/105124262-a41aae80-5a8e-11eb-841e-533208a23e81.png)
I am not sure if I captured it at the right time but here it is.

**Comment by jimmysofat6864** [comment]
![Screen Shot 2021-01-19 at 7 43 21 PM](https://user-images.githubusercontent.com/69532417/105125236-c0b7e600-5a90-11eb-8d83-0ff5f44d02dc.png)
![Screen Shot 2021-01-19 at 7 57 42 PM](https://user-images.githubusercontent.com/69532417/105125242-c3b2d680-5a90-11eb-85c5-98fdc7a54d34.png)
![Screen Shot 2021-01-19 at 7 58 22 PM](https://user-images.githubusercontent.com/69532417/105125246-c44b6d00-5a90-11eb-8008-cb008f35cc1f.png)
![Screen Shot 2021-01-19 at 7 58 35 PM](https://user-images.githubusercontent.com/69532417/105125249-c4e40380-5a90-11eb-8f18-95b1de7217c8.png)

**Comment by Alex-302** [comment]
@jimmysofat6864 Hi. Please copy full selected URL
![image](https://user-images.githubusercontent.com/8361299/105741164-aa9f9f00-5f42-11eb-9f98-b47acb1d9d7f.png)

Also please add this rule to user filter and check again after restart Spotify:
`||bloodhound.spotify.com/ad_server_`

**Comment by jimmysofat6864** [comment]
I will try that then. Also, I notice that the issue also happens more often when I wake my mac from sleep and resume playing from spotify. When I wake my mac from sleep and go to the next song, ads start playing. I have more photos attached. 
![Screen Shot 2021-01-25 at 10 16 37 PM](https://user-images.githubusercontent.com/69532417/105807628-40dfbf00-5f5b-11eb-9a21-d48575398b1a.png)atta
![Uploading Screen Shot 2021-01-25 at 10.16.42 PM.png…
![Screen Shot 2021-01-25 at 10 16 48 PM](https://user-images.githubusercontent.com/69532417/105807635-4210ec00-5f5b-11eb-8c74-c1456280b9e8.png)
![Screen Shot 2021-01-25 at 10 16 57 PM](https://user-images.githubusercontent.com/69532417/105807637-42a98280-5f5b-11eb-934a-7cd42ac67e13.png)
![Screen Shot 2021-01-25 at 10 17 04 PM](https://user-images.githubusercontent.com/69532417/105807639-43421900-5f5b-11eb-93b1-c220723c8436.png)





![Screen Shot 2021-01-25 at 10 16 28 PM](https://user-images.githubusercontent.com/69532417/105807624-3d4c3800-5f5b-11eb-89fc-1de02ddc8bdf.png)

**Comment by jimmysofat6864** [comment]
Some ads leaked in again while on sleep on mac. However, after adding in that line you told me to, after waking from sleep, the ad went through and now there is high cpu usage on my mac. 
![Screen Shot 2021-01-25 at 11 48 30 PM](https://user-images.githubusercontent.com/69532417/105815613-0cbecb00-5f68-11eb-994f-d6b3c09d9216.png)

**Comment by Alex-302** [comment]
> Also please add this rule to user filter and check again after restart Spotify:
> `||bloodhound.spotify.com/ad_server_`

**Comment by jimmysofat6864** [comment]
> > Also please add this rule to user filter and check again after restart Spotify:
> > `||bloodhound.spotify.com/ad_server_`
> 
> I need full url, which contains the part above.

Sorry the logs keep automatically clearing every time I go to open it and check. I will see if I can get it again. Also here are some more logs as it happened again. 

![Screen Shot 2021-01-26 at 8 55 34 PM](https://user-images.githubusercontent.com/69532417/105945333-f4a78400-6019-11eb-9f30-ccccdd921b7e.png)
![Screen Shot 2021-01-26 at 8 55 40 PM](https://user-images.githubusercontent.com/69532417/105945335-f6714780-6019-11eb-8d2a-bfb2dc2c6cc0.png)
![Screen Shot 2021-01-26 at 8 57 05 PM](https://user-images.githubusercontent.com/69532417/105945336-f6714780-6019-11eb-8539-ffa5b21a5725.png)
![Screen Shot 2021-01-26 at 8 57 11 PM](https://user-images.githubusercontent.com/69532417/105945339-f7a27480-6019-11eb-89c0-feef6c4041ca.png)
![Screen Shot 2021-01-26 at 8 57 17 PM](https://user-images.githubusercontent.com/69532417/105945342-f83b0b00-6019-11eb-94b9-cd5c34a4d482.png)
![Screen Shot 2021-01-26 at 8 57 22 PM](https://user-images.githubusercontent.com/69532417/105945343-f8d3a180-6019-11eb-8c30-f44e6024591b.png)
![Screen Shot 2021-01-26 at 8 57 27 PM](https://user-images.githubusercontent.com/69532417/105945347-f96c3800-6019-11eb-9460-566fcc84c881.png)
![Screen Shot 2021-01-26 at 8 57 32 PM](https://user-images.githubusercontent.com/69532417/105945349-fa04ce80-6019-11eb-96fc-71b756dc0d98.png)
![Screen Shot 2021-01-26 at 8 58 39 PM](https://user-images.githubusercontent.com/69532417/105945350-fa9d6500-6019-11eb-90e0-95cd0992958b.png)
![Screen Shot 2021-01-26 at 8 58 47 PM](https://user-images.githubusercontent.com/69532417/105945352-fb35fb80-6019-11eb-923e-b6f6831757d3.png)
![Screen Shot 2021-01-26 at 8 58 51 PM](https://user-images.githubusercontent.com/69532417/105945355-fbce9200-6019-11eb-88fd-f56a103cfd67.png)
![Screen Shot 2021-01-26 at 9 01 13 PM](https://user-images.githubusercontent.com/69532417/105945357-fbce9200-6019-11eb-96c8-6b1ddf6cd637.png)
![Screen Shot 2021-01-26 at 9 01 20 PM](https://user-images.githubusercontent.com/69532417/105945358-fc672880-6019-11eb-9fa6-6ccb644d08cd.png)

**Comment by bogachenko** [comment]
@alex-302 it has xmlhttprequest unlocked `/ad-logic/`

**Comment by Alex-302** [comment]
@bogachenko where?

**Comment by bogachenko** [comment]
@Alex-302 everywhere, in all screenshots.

`https://spclient.wg.spotify.com/ad-logic/prefetch`

**Comment by Alex-302** [comment]
It is not unlocked, it is - not blocked)

@jimmysofat6864 
there are two rules for test:
```
||bloodhound.spotify.com/ad_server_
||spclient.wg.spotify.com/ad-logic/
```

**Comment by jimmysofat6864** [comment]
I tried this and ads still leak in occasionally. Seems to happen more when waking from sleep. 
![Screen Shot 2021-01-28 at 9 19 46 PM](https://user-images.githubusercontent.com/69532417/106234990-a5df2300-61ae-11eb-9411-c5bc913d6a0a.png)
![Screen Shot 2021-01-28 at 9 19 53 PM](https://user-images.githubusercontent.com/69532417/106235001-a972aa00-61ae-11eb-96e3-2ca54450fd00.png)
![Screen Shot 2021-01-28 at 9 19 58 PM](https://user-images.githubusercontent.com/69532417/106235003-aa0b4080-61ae-11eb-840d-cfb2e383a157.png)
![Screen Shot 2021-01-28 at 9 20 01 PM](https://user-images.githubusercontent.com/69532417/106235006-aaa3d700-61ae-11eb-9e72-1b255ce75393.png)

**Comment by jimmysofat6864** [comment]
More logs again it leaked again. 
![Screen Shot 2021-01-31 at 11 58 46 AM](https://user-images.githubusercontent.com/69532417/106396290-d942cd00-63bb-11eb-9a24-29ffeb1bc19d.png)
![Screen Shot 2021-01-31 at 11 58 36 AM](https://user-images.githubusercontent.com/69532417/106396292-dc3dbd80-63bb-11eb-89f8-1047da935458.png)

**Comment by jimmysofat6864** [comment]
Audio ads and banner ads are sometimes experienced. Pictures are from after waking from sleep and when banner ads are seen. 
![Screen Shot 2021-01-31 at 4 23 29 PM](https://user-images.githubusercontent.com/69532417/106402911-d4444480-63e0-11eb-89b9-84180c7f2edc.png)
![Screen Shot 2021-01-31 at 4 23 23 PM](https://user-images.githubusercontent.com/69532417/106402913-d73f3500-63e0-11eb-8d2b-55119eb251f6.png)
![Screen Shot 2021-01-31 at 4 23 16 PM](https://user-images.githubusercontent.com/69532417/106402914-d8706200-63e0-11eb-985b-83e2ca4b2d44.png)
![Screen Shot 2021-01-31 at 4 23 10 PM](https://user-images.githubusercontent.com/69532417/106402916-d908f880-63e0-11eb-82ca-1f2a0245a8f3.png)
![Screen Shot 2021-01-31 at 4 22 49 PM](https://user-images.githubusercontent.com/69532417/106402917-d9a18f00-63e0-11eb-8334-5830fd7186b2.png)

**Comment by Alex-302** [comment]
@jimmysofat6864 It seems this ad cannot be blocked by URL blocking rule.
