### ISSUE TITLE
Phishing 28122020

### ISSUE THREAD

**Issue by bogachenko** [AdguardTeam/AdguardFilters#71063]
`https://ofqk.cn/`
`https://voproska.site/`
`https://www.bmne.cn/`
`https://www.jztwq.cn/`
`http://www.sxysgs.cn/`
`http://www.jdznsz.cn/`
`http://www.huxike.cn/`
`http://www.sf168.com.cn/`
`http://www.dpenbszn.cn/`
`http://www.dqz7j2.top/`
`http://www.f2jjht.top/`
`http://www.wkuvak.top/`
`http://www.rqwops.top/`
`http://www.bwiwb.cn/`

@Chinaski1 Проверь это.

**Comment by bogachenko** [comment]
`https://www.bjsyhx.cn/`

**Comment by gork7777** [comment]
@lolka4toli

**Comment by bogachenko** [comment]
`http://www.btake.cn/`
`http://www.sbur.cn/`
`http://www.psnbq5.cn/`
`http://www.xndzpt.cn/`
`http://www.29c03.cn/`
`http://www.g93od.cn/`

**Comment by lolka4toli** [comment]
Blocked.
