### ISSUE TITLE
[Windows] www.stern.de - anti adblock script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#7111]
![](https://i.imgur.com/D2ydTjW.png)
http://www.stern.de/kultur/musik/us-saengerin-pink-mit-neuem-album--beautiful-trauma---hits-von-ganz-unten-7656366.html

Workround for me:
```
||static.stern.de/resources/*/mms-client.js
```
**Adguard version**: 6.2.424.2123
**Operating system**: Windows 10
**Browser**: Vivaldi 1.13.971.8

**Comment by AdamWr** [comment]
Fixed.
