### ISSUE TITLE
ekranka.tv - Incorrect blocking

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7112]
http://ekranka.tv/

<details><summary>Screenshot:</summary>

Russian filter is disabled
![image](https://user-images.githubusercontent.com/27292111/31585233-4567d57a-b1c7-11e7-97a0-5fa8269e633a.png)

Russian filter is enabled
![image](https://user-images.githubusercontent.com/27292111/31585243-63c74ed8-b1c7-11e7-9a91-8a5a6f0774b1.png)

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | 6.2
Filters enabled:                    | 1 2 3 4 14
Helpdesk ID :            | 1642739

**Comment by veronikasav** [comment]
Nope, it doesn't work

**Comment by Alex-302** [comment]
How did you test?

**Comment by veronikasav** [comment]
@Alex-302 
Added that rule to the User filter and checked on MacOS (it doesn't work):
<details><summary>Screenshot:</summary>

<img width="1203" alt="screen shot 2017-10-16 at 8 07 50 pm" src="https://user-images.githubusercontent.com/27292111/31625318-5067e126-b2ae-11e7-9406-08d8ef1c2d21.png">

</details><br/>

On Windows OS it works even without added rule but Assistant is missing now:
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/31625349-69b42324-b2ae-11e7-93c0-3d8c251135eb.png)

</details><br/>

**Comment by Alex-302** [comment]
@veronikasav 
Это не исключение. Я удалил домен из правила. Нужно подождать обновления фильтров.
