### ISSUE TITLE
dybee.cn - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7113]
http://www.dybee.cn/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/31585402-85639748-b1c9-11e7-952f-a0f36843818a.png)

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPhone
Platform: iOS
OS: 10.1
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.32.99 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.87 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.1 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.38 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.1 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.67 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.89.7 Enabled=YES

Helpdesk ID:         1644120

**Comment by AdamWr** [comment]
Fixed.
