### ISSUE TITLE
http://www.autohome.com.cn - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7114]
Missed ads.

### Steps to reproduce

1. Go here http://www.autohome.com.cn/news/201710/907789.html#pvareaid=102624
2. See ads

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31585806-9d717e2a-b1d0-11e7-9c88-2a9fd067a292.png)

</details>

### Your environment

* Adguard version: 1.3.1 for iOS
* DNS: Off
* Optimized filters: Off
* Subscriptions: 

- ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
- ID=2 Name="English filter" Version=1.0.84.64 Enabled=NO
- ID=3 Name="Spyware filter" Version=1.0.5.85 Enabled=NO
- ID=4 Name="Social media filter" Version=1.0.9.34 Enabled=NO
- ID=10 Name="Filter for useful ads" Version=1.0.0.89 Enabled=NO
- ID=12 Name="Safari filter" Version=1.0.3.67 Enabled=YES
- ID=11 Name="Mobile ads filter" Version=1.0.3.54 Enabled=NO
- ID=101 Name="EasyList" Version=1.0.76.2 Enabled=YES
- ID=118 Name="EasyPrivacy" Version=1.0.88.56 Enabled=YES
- ID=104 Name="EasyList China" Version=1.0.88.91 Enabled=YES
- ID=207 Name="Adblock Warning Removal List" Version=1.0.88.78 Enabled=YES
- ID=208 Name="Malware Domains" Version=1.0.58.33 Enabled=NO
- ID=219 Name="ChinaList+EasyList" Version=1.0.0.72 Enabled=NO
- ID=204 Name="Peter Lowe's list" Version=1.0.3.52 Enabled=YES

**Comment by AdamWr** [comment]
Added:
`m.autohome.com.cn##.recommend-envelope`
`m.autohome.com.cn##body > section[class]:nth-child(4) > .assist`
`m.autohome.com.cn##body > section[class]:nth-child(4) > .assist + i.icon-cross`
`m.autohome.com.cn##body > div[class]:first-child:not(.wrapper):not(.nav):not([id]):not([style])`
