### ISSUE TITLE
europapress.es

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#71159]
[https://m.europapress.es/comunitat-valenciana/noticia-sucesos-desarticulados-12-puntos-venta-droga-marina-alta-operacion-detenidos-20200819111737.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://m.europapress.es/comunitat-valenciana/noticia-sucesos-desarticulados-12-puntos-venta-droga-marina-alta-operacion-detenidos-20200819111737.html)

Sharing buttons at the top. The links to the official social media pages at the bottom of the page are incorrectly hidden by `.social-icon`.

![sharing](https://user-images.githubusercontent.com/35470489/103279764-54742600-49ad-11eb-9c30-80182d2df098.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by seyoon20087** [comment]
Sorry, this item cannot be easily added to our filters.

If you would like to block those you need to do it manually.

Assuming you're using AdGuard for Windows, you can use AdGuard Browser Assistant to do so.

1. Open AdGuard Browser Assistant
2. Select "Block ads on the website"
![Screen Shot 2020-12-30 at 9 56 52 AM](https://user-images.githubusercontent.com/24852454/103323313-b011e280-4a85-11eb-88b6-67d67a70be01.png)
3. Choose an element
4. Click "Block"

If you do not have access to AdGuard Browser Assistant you can add this rule in Adguard Filtering Preferences:
```
m.europapress.es###noticia_det > div.ComparteContainer:nth-child(4)
```

Hope this helps.
