### ISSUE TITLE
delcastellano.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#71158]
[https://www.delcastellano.com/participio-futuro-espanol/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.delcastellano.com/participio-futuro-espanol/)

Subscription annoyances all over the page. People interested in this can use the `Apúntate` menu:

![subscribe](https://user-images.githubusercontent.com/35470489/103279508-b97b4c00-49ac-11eb-8ec0-e166f910fffc.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by seyoon20087** [comment]
Sorry, this item cannot be easily added to our filters.

If you would like to block those you need to do it manually.

Assuming you're using AdGuard for Windows, you can use AdGuard Browser Assistant to do so.

1. Open AdGuard Browser Assistant
2. Select "Block ads on the website"
![Screen Shot 2020-12-30 at 9 56 52 AM](https://user-images.githubusercontent.com/24852454/103323313-b011e280-4a85-11eb-88b6-67d67a70be01.png)
3. Choose any elements you want to block
4. Click "Block"

If you do not have access to AdGuard Browser Assistant you can add these rules in Adguard Filtering Preferences:
```
delcastellano.com###genesis-content > article.post-675.post.type-post.status-publish.format-standard.has-post-thumbnail.category-morfosintaxis-historica.tag-analogia.tag-diatesis.tag-espanol.tag-futuro.tag-indoeuropeo.tag-latin.tag-oscoumbro.tag-lexicalizacion.tag-participio-de-futuro.tag-participios.tag-productividad.tag-rotacismo.tag-sufijacion.tag-verboides.tag-verbos.entry:nth-child(2) > div.entry-content:nth-child(2) > div.aviso-global.publi-inpost:nth-child(8)
delcastellano.com###genesis-content > article.post-675.post.type-post.status-publish.format-standard.has-post-thumbnail.category-morfosintaxis-historica.tag-analogia.tag-diatesis.tag-espanol.tag-futuro.tag-indoeuropeo.tag-latin.tag-oscoumbro.tag-lexicalizacion.tag-participio-de-futuro.tag-participios.tag-productividad.tag-rotacismo.tag-sufijacion.tag-verboides.tag-verbos.entry:nth-child(2) > footer.entry-footer:last-child > div.footer-post-cta:last-child
delcastellano.com###text-14 > div.widget-wrap > h4.widget-title.widgettitle:first-child
delcastellano.com###text-14 > div.widget-wrap > div.textwidget:last-child
```

Hope this helps.

**Comment by wout-codes** [comment]
Hi again, @AdamWr 
1. https://github.com/AdguardTeam/AdguardFilters/issues/69756#issuecomment-754043257
2. https://github.com/AdguardTeam/AdguardFilters/issues/71605
3. https://github.com/AdguardTeam/AdguardFilters/issues/71388
4. agar.red
5. https://nashaplaneta.net/
6. https://manga1001.com/%E3%80%90%E7%AC%AC29%E8%A9%B1%E3%80%91%E3%81%8D%E3%82%87%E3%81%86%E3%82%82%E9%BB%92%E5%92%B2%E3%81%95%E3%82%93%E3%81%AE%E3%82%BF%E3%83%BC%E3%83%B3%EF%BC%81-raw/

All of these contain Anti-Adblock Script. I believe you can fix all these. 
Thanks,
Wout

**Comment by AdamWr** [comment]
First issue has been fixed and update should be available in 1-2 hours.
2,3,4,5 probably will be fixed soon, but there is many other opened issues, so please be patient.
`manga1001.com` is already fixed in `AdGuard Japanese filter`.

Please also do not write comments not related to the current issue.

**Comment by wout-codes** [comment]
> Hi again, @AdamWr
> 
> 1. [#69756 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/69756#issuecomment-754043257)
> 2. #71605
> 3. #71388
> 4. https://agar.red/adblock
> 5. https://nashaplaneta.net/
> 6. https://manga1001.com/%E3%80%90%E7%AC%AC29%E8%A9%B1%E3%80%91%E3%81%8D%E3%82%87%E3%81%86%E3%82%82%E9%BB%92%E5%92%B2%E3%81%95%E3%82%93%E3%81%AE%E3%82%BF%E3%83%BC%E3%83%B3%EF%BC%81-raw/
> 
> All of these contain Anti-Adblock Script. I believe you can fix all these.
> Thanks,
> Wout

I can't communicate with you without commenting. So, that's why.

**Comment by wout-codes** [comment]
Hi again, @AdamWr

1. #71605
2. #71388
3. https://agar.red/adblock
4. https://nashaplaneta.net/
5. https://yesmangas1.com/
6. https://kusonime.com/

Some more has been added. I can't communicate with you without commenting, that's why. 
All of these contain Anti-Adblock Script. I believe you can fix all these.
Thanks,
Wout

**Comment by AdamWr** [comment]
If website is not already reported then please use reporting tool to report them - https://reports.adguard.com/en/new_issue.html

**Comment by wout-codes** [comment]
@AdamWr 
I am sorry, I do not have much time. Please solve from here. 

> Hi again, @AdamWr
> 
> 1. #71605
> 2. #71388
> 3. https://agar.red/adblock
> 4. https://nashaplaneta.net/
> 5. https://yesmangas1.com/
> 6. https://kusonime.com/
> 
> Some more has been added. I can't communicate with you without commenting, that's why.
> All of these contain Anti-Adblock Script. I believe you can fix all these.
> Thanks,
> Wout

**Comment by wout-codes** [comment]
Hi again, @AdamWr

#71605
#71388
#71498
https://github.com/AdguardTeam/AdguardFilters/issues/71568#issuecomment-754321504
#69878
#71623

Here you @AdamWr I reported all. Please fix all these now for a better AdGuard Annoyances. 
Some more has been added. I can't communicate with you without commenting, that's why.
All of these contain Anti-Adblock Script. I believe you can fix all these.
Thanks,
Wout

**Comment by wout-codes** [comment]
Hi, @AdamWr

#71605
#71388
#71498
#71568 (comment)
#69878
#71623
#71651
#71650
#71686

Here you go @AdamWr I reported all. Please fix all these now for a better AdGuard Annoyances.
Some more has been added. All of these contain Anti-Adblock Script. I believe you can fix all these.
Thanks,
Wout
