### ISSUE TITLE
twitch.tv - not working with Yandex browser

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#7116]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Twitch.tv won't open in Yandex browser
* **Current behaviour**: 

<details><summary>Helpdesk id 1647083</summary>

Использую Яндекс Браузер, при
переходе на twitch.tv страница не
загружается. Появляется ошибка
"ERR_EMPTY_RESPONSE", "Сайт ru.twitch.tv не отправил
данные". Если отключить защиту, сайт
загружается нормально, даже при
включённом браузерном расширении.
Проблема возникает именно в Яндекс
Браузере, с Microsoft Edge, при включённой
защите, сайт загружается нормально.
Расширенные диагностические данные:
https://yadi.sk/d/gYoEfs-y3NjehP

</details><br/>

<details><summary>Helpdesk id 1647986</summary>

Здравствуйт е. Пользуюсь программой  AdGuard, и яндекс браузером. В последнее время перестал загружаться сайт twitch.tv. Поискав какое-то время в чем проблема, понял, что при отключении защиты  AdGuard сайт загружается без проблем, а с включенной защитой не загружается совсем. Причем такая проблема только у ЯБ, например через гугл хром сайт загружается и при активной защите.

</details><br/>

<details><summary>Helpdesk id 1137087</summary>

При включенном adguard невозможно зайти
на twitch, проблема началась пару дней
назад, также иногда вместо открытия
страницы предлагается её сохранить.
Версия 6.1.331.1732 .Переустанавливал adguard с
удалением настроек. Переустанавливал
сертификат. Проблема
воспроизводиться на двух компьютерах.
Видео с иллюстрацией проблемы.
https://www.youtube.com/watch?v=HQEtyGAnU34
https://www.youtube.com/watch?v=MnAs6TKeLG8
https://www.youtube.com/watch?v=zn1dGo0JZs0

</details><br/>

<details><summary>Helpdesk id 1647501</summary>

Здравствуйте, я уже 2 дня не могу войти
на сайт twitch.tv если включен AdGuard для
Windows. Проблема появляется только если
я захожу на сайт через Яндекс Браузер.
Если отключить защиту AdGuard сайт
загружается нормально. Моя проблема
уже описана на форуме:
https://forum.adguard.com/index.php?threads/adguard-Яндекс-Браузер-и-twitch-tv.25930/
Так же не работают переходы со
сторонних сайтов на twitch.tv, при нажатии
на ссылку, ведущую на сайт, браузер
предлагает сохранить странный файл.
Если отключить AdGuard, по ссылкам идет
нормальный переход.

</details><br/>

<details><summary>Helpdesk id 1502423</summary>

https://go.twitch.tv/ САЙТ НЕ РАБОТАЕТ ПРИ
ВКЛЮЧЕНОМ ADGUARD ИСПРАВТЕ

</details><br/>

<details><summary>Helpdesk id 1647401</summary>

возникла проблема при переходе на
новый браузер "Яндекс" (до этого
использовался Google Chrome). Проблема
заключается в следующем, сайт
"https://go.twitch.tv/" при включенной защите
Adguard попросту не работает (на сайте
прогружается лишь "шапка" и то
неактивная), однако стоит отключить
защиту, сайт приходит в полностью
рабочее состояние. Не уверен можно ли
считать это ошибкой работы программы,
однако хотелось бы узнать, возможно ли
это как то испрвить?

</details><br/>

<details><summary>Helpdesk id 1647119</summary>

При использовании Яндекс Браузера и
AdGuard для Windows, не загружается
стрим-сервис Twitch

</details><br/>

<details><summary>Helpdesk id 1502508</summary>

Здравствуйте. С недавнего времени
появились проблемы с доступом к сайту
twitch.tv или go.twitch.tv. В интернете есть
информация, что это направленная
борьба с блокировкой рекламы.
Подскажите пожалуйста, как решить эту
проблему, кроме как отлючением Adguard'a.

</details><br/>

<details><summary>Forum topic</summary>

[https://forum.adguard.com/index.php?threads/adguard-%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D0%91%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80-%D0%B8-twitch-tv.25930/](https://forum.adguard.com/index.php?threads/adguard-%D0%AF%D0%BD%D0%B4%D0%B5%D0%BA%D1%81-%D0%91%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80-%D0%B8-twitch-tv.25930/)

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Win
Browser:                            | Yandex
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 1, 2, 3, 4, 14

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
не повторяется.

**Comment by vozersky** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #1968](https://github.com/AdguardTeam/AdguardForWindows/issues/1968) via [**ZenHub**](https://www.zenhub.com/)
