### ISSUE TITLE
migalki.pw - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7117]
http://migalki.pw/showthread.php?t=3489

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/31586805-2ff2ef6e-b1df-11e7-92d4-29725576a147.png)

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Windows
Browser:                            | Chrome
AdGuard version:                    | 6.2
Filters enabled:                    | 1 2 3 4 5 14
Helpdesk ID:            | 1643928

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.

**Comment by Alex-302** [comment]
:(
