### ISSUE TITLE
http://forum.na-svyazi.ru/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7118]
В правилах фильтрации форума forum.na-svyazi.ru есть как минимум одно лишнее - forum.na-svyazi.ru###userlinks
Оно убивает для зарегистрированных пользователей важную панель. Но при его отключении появляется неприятный пробел. Это конечно мелочь, но неприятная мелочь. Точно такой же пробел есть и на соседнем форуме forum.zarulem.ws

### Expected behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31586949-5b43989c-b1e1-11e7-9ff6-96544deb00fd.png)

</details>

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31586953-6a8676e4-b1e1-11e7-92db-38ed42da12cd.png)

</details>

**Comment by Alex-302** [comment]
Поправил и убрал баннеры. Отступ не повторяется.
