### ISSUE TITLE
9anime.to - Incorrect blocking

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7125]
https://9anime.to/watch/gosick.5210/yjy391

The player is blocked on this website when Adguard is enabled.

<details><summary>Screenshot:</summary>

AdGuard is enabled on the website video player is blocked. It works only when Adguard is 

<img width="1566" alt="screen shot 2017-10-16 at 8 01 11 pm" src="https://user-images.githubusercontent.com/27292111/31624879-cf3beefe-b2ac-11e7-91ce-0fdf2f06293b.png">

Adguard is enabled
<img width="1567" alt="screen shot 2017-10-16 at 6 42 22 pm" src="https://user-images.githubusercontent.com/27292111/31621183-ca3e569a-b2a1-11e7-9268-f06dd8350a92.png">

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | MacOS/iOS
Browser:                            | Safari
AdGuard version:                    | 1.4.1/1.3.1.107
Filters enabled:                    | 2 3 4 12 101
Helpdesk ID:            | 1643371

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
