### ISSUE TITLE
[Windows] www.bild.de - anti adblock script

### ISSUE THREAD

**Issue by Vincent-Michael** [AdguardTeam/AdguardFilters#7126]
![](https://i.imgur.com/GRu3jQr.png)
http://www.bild.de/

**Adguard version**: 6.2.424.2123
**Operating system**: Windows 10
**Browser**: Vivaldi 1.13.971.8

**Comment by Alex-302** [comment]
https://forum.adguard.com/index.php?threads/policy-on-adblock-walls.26022/

```
bild.de#%#(function(){var __de,__bild,__cmsKonfig;try{var b=function(a){a&&__bild!=a&&(__bild=a,__cmsKonfig=a.cmsKonfig,Object.defineProperty(a,"cmsKonfig",{get:function(){return __cmsKonfig},set:function(a){a&&a.system&&a.system.ad_smart_site_id&&(a.a={a:0,b:1},a.system.ad_smart_site_id=void 0);__cmsKonfig=a}}))},c=function(a){__de!=a&&(__de=a,b(__de.bild),Object.defineProperty(__de,"bild",{get:function(){return __bild},set:function(a){b(a)}}))};Object.defineProperty(window,"de",{get:function(){return __de},set:function(a){c(a)}})}catch(a){console&&console.error&&console.error(a)}})();
@@||smartadserver.com/diff/251/*$domain=bild.de 
@@||smartadserver.com/diff/251/verify.js$domain=bild.de 
bild.de#@#.ads
bild.de#@#.cbErotikContentbar15
bild.de#@#.contentbar
bild.de#@#.eyecatcher
bild.de#@#.footerbar
bild.de#@#.fullbanner
bild.de#@#.jetzt_aufnehmen
bild.de#@#.rectangle
bild.de#@#.servicelinks
bild.de#@#.tea-rectangle
bild.de#@#.txe
bild.de#@#.yield
@@||acdn.adnxs.com/as/*/pages/bild.js$domain=bild.de
@@||bild.de^$generichide
@@||cdn1.smartadserver.com/diff/251/divscripte/adplayer.css$domain=bild.de
@@||smartadserver.com/diff/*/partners/$domain=bild.de
@@||smartadserver.com/diff/*/smartad.js$domain=bild.de
@@||sascdn.com^$domain=bild.de,script
```

**Comment by Vincent-Michael** [comment]
wtf, ty

**Comment by Alex-302** [comment]
:(

**Comment by ameshkov** [comment]
@Vincent-Michael yep, all the details + the list of affected websites and the discussion is there on our forum

**Comment by JayBrown** [comment]
I'm pretty sure you will eventually be able to block the ads on that bild site with another third-party filter list. Too bad Adguard doesn't allow users subscribing to filter lists of their own choosing. Instead we must rely on the third-party lists provided by Adguard through the app, at least on the Mac Desktop version. Why is that? You should extend the functionality, *especially* in light of this new development.

PS: the faz website is working fine so far, i.e. there's already an anti-adblock block in place in one of the third-party filters.

**Comment by ameshkov** [comment]
@JayBrown why so, you can actually add any third party subscription by its URL

**Comment by ameshkov** [comment]
@JayBrown oh, I missed the "Mac" point, sorry. Actually, in the very next update, there will be an option to add a custom subscription.
