### ISSUE TITLE
abcvideo.cc

### ISSUE THREAD

**Issue by gzenio22** [AdguardTeam/AdguardFilters#71280]
https://abcvideo.cc/embed-fh443s8inbdn.html

![Screenshot_1](https://user-images.githubusercontent.com/21177361/103386529-89908d80-4aff-11eb-8859-3c51f6839e11.png)

My English is poor so I use google translator. The Adguard browser assistant blocks some ad, but I don't know how to check what exactly it is. below will paste a list of my active filters

![Screenshot_1](https://user-images.githubusercontent.com/21177361/103313207-a8b7ee00-4a1f-11eb-9cd5-f194328db8f2.png)
![Screenshot_2](https://user-images.githubusercontent.com/21177361/103313220-afdefc00-4a1f-11eb-9f0a-0d2c82fe31a7.png)

I am using adguard PC ver 7.5.3 stable application from screen 1 pops up in the chrome browser. I did not check on others

**Comment by AdamWr** [comment]
Ten komunikat w prawym górnym rogu to jest "bloker wyskakujących okienek", jak klikniesz w przycisk "Opcje", to powinien pojawić się adres strony, która została zablokowana.
Dodałem regułę, żeby zablokować wyskakujące okienka i ten komunikat nie powinien się już w ogóle pokazywać.
Aktualizacja filtrów będzie dostępna za około 1-2 godziny.
