### ISSUE TITLE
http://www.avtovzglyad.ru/gai/korrupciya/2017-05-29-gibdd-zakryvaet-vse-avtoshkoly-strany/

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#7129]
Фильтры по-умолчанию, версия 2.9.136, HTTPS, HTTP вкл, качественная, Android 4.4.4
Баннер сверху
http://my-files.ru/na3nzh

**Comment by ministr91** [comment]
![screenshot_2017-10-17-10-36-20](https://user-images.githubusercontent.com/22351242/31652393-3572cdc4-b31f-11e7-9622-8234dd545bb1.png)

**Comment by Alex-302** [comment]
Поправил.
