### ISSUE TITLE
godlikeproductions.com site banner blocked

### ISSUE THREAD

**Issue by GitCartel** [AdguardTeam/AdguardFilters#7131]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

site banner blocked by base list
banner is gone

![2017089](https://user-images.githubusercontent.com/30365972/31659923-8ed88a14-b2ea-11e7-8830-18fe1576030e.jpg)
![2017090](https://user-images.githubusercontent.com/30365972/31659924-8ef05cb6-b2ea-11e7-9cbd-e9ecb327d557.jpg)

Static filter ##img[width="468"][height="60"] found in:

    Adguard Base Filters

UBO, PMx64, W7 x64

**Comment by Alex-302** [comment]
Thanks, fixed.

**Comment by GitCartel** [comment]
awesome thank you
