### ISSUE TITLE
www.goibibo.com Cannot view all the hotels

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7132]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
https://www.goibibo.com/hotels/find-hotels-in-Darjeeling/4863087815102631912/4863087815102631912/%7B%22ci%22:%2220171116%22,%22co%22:%2220171119%22,%22r%22:%221-2-0%22%7D/?{}&sec=dom

***Description***: [customer's description]:
Cannot view all the hotels unless i disable adguard. Scrolling down is
just blank, adguard enabled - shows only 4-5 hotels.

* **Current behaviour**: 

the page shows only several items, won't scroll down.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![before](https://user-images.githubusercontent.com/32528702/31665081-696ca9f2-b350-11e7-995a-f0418754c88a.jpg)

</details><br/>

* **Expected behaviour**: 

showing full list of items corresponding to the search criteria, scrolling down the page is possible. 

<details><summary>Screenshot:</summary>

![after](https://user-images.githubusercontent.com/32528702/31665114-8920208a-b350-11e7-9094-dde75d47e6a4.jpg)

</details><br/>

**Filters:**
English filter
Spyware filter
Social media filter
Annoyances filter
Anti-Adblock Killer
Fanboy's Enhanced Tracking List
I don't care about cookies

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows NT 6.1.7601 Service Pack 1
Browser:                            | ?
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 2, 3, 4, 14, 211, 215, 229
Stealth mode options (Windows only) | enabled
Helpdesk ID (if exists):            | 1518164

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Posted the rule in your issue in Fanboy's repo.
