### ISSUE TITLE
Ads on mail.ru and yandex

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7133]
***Description***: Ads on http://mail.ru/ and http://yandex.ru/
No user rules for these websites.
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![20](https://user-images.githubusercontent.com/32528702/31702561-6545d746-b3e0-11e7-8e96-a25e66bd590c.png)
![19](https://user-images.githubusercontent.com/32528702/31702567-68b4a7fe-b3e0-11e7-8a95-acddd386e531.png)

![image](%screenshot_url%)
</details><br/>

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows NT 6.3.9600.0
Browser:                            | Yandex
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 2, 3, 4, 14, 1
Helpdesk ID (if exists):            | 671346

**Comment by Alex-302** [comment]
Попроси 6.2 установить. В 6.1 многое не доступно.

**Comment by evgeniy-ADG** [comment]
AppVersion: 6.2.390.2018
Filters: English, Russian

![image](https://user-images.githubusercontent.com/15856304/31758968-4e2987c8-b4b8-11e7-890a-245a8aa9445c.png)

**Comment by evgeniy-ADG** [comment]
AppVersion: 6.2.346.1819
ID: 1261473
Filters: english, russian, polskie reguly

<details>
![image](https://user-images.githubusercontent.com/15856304/31760093-35f510a6-b4bc-11e7-85d1-2531919fd3b5.png)

**Comment by evgeniy-ADG** [comment]
@Alex-302 Есть какая-то инфа, может?

**Comment by Alex-302** [comment]
по яндексу исправляли. На mail.ru не повторяется.
