### ISSUE TITLE
Missed ad on https://diakov.net/

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7134]
***Description***: Missed ad on https://diakov.net/
Also reproduced with browser extension for Chrome.
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/32528702/31703100-a154c668-b3e3-11e7-9600-f8bfe13ffb51.jpg)

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10
Browser:                            | Chrome
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 2, 3, 4, 10, 1
Helpdesk ID (if exists):            | 741799

**Comment by Alex-302** [comment]
fixed.
