### ISSUE TITLE
http://www.sncmedia.ru/# - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7135]
Unable to load more news posts

### Steps to reproduce

1. Go to http://www.sncmedia.ru/#
2. Click on Ещё новости
3. The focus jumps upwards and no new posts are loaded

### Your environment

* OS: Windows 10
* Adguard version: AdGuard for Windows 6.2
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* HTTPS: On
* Driver: WFP
* Stealth mode: OFf
* DNS: Off

**Comment by Alex-302** [comment]
Fixed.
