### ISSUE TITLE
http://auth.wi-fi.ru - the Connect button doesn't work

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7136]
Tapping "Connect" does nothing. Works fine only if AdGuard is disabled.

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31711460-e5efd2b4-b400-11e7-840c-4cab3071a31d.png)

</details>

### Your environment

* OS: Android 7
* Adguard version: 2.10.108
* Subscriptions: "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Filter unblocking useful ads", "Russian filter", "Experimental filter", "Mobile Ads filter", "Simplified domain names filter", "Anti-Adblock Killer | Reek"
* DNS: Off
* HTTPS: Whitelist mode
* Filtering method: HQ
* Filtering mode: VPN

**Comment by Alex-302** [comment]
Нужен журнал **HTTP** запросов с временной отметкой.

**Comment by evgeniy-ADG** [comment]
Пока не прислали. На iOS это решается?

<details>

Details: 1487270

![image](https://user-images.githubusercontent.com/15856304/31758560-9df1db9a-b4b6-11e7-9b7a-3237c02f3c21.png)

**Comment by Alex-302** [comment]
На иос должно было решиться. Один юзер проверял мои правила, и ему помогло.
```
@@||auth.wi-fi.ru^$urlblock
```

**Comment by evgeniy-ADG** [comment]
Есть лог отсюда: 1645337

**Comment by Alex-302** [comment]
Передай на проверку:
```
@@||googleads.g.doubleclick.net$domain=auth.wi-fi.ru
@@||googletagmanager.com/gtm.js$domain=auth.wi-fi.ru
@@||ads.adfox.ru/*/getCode?$domain=auth.wi-fi.ru
@@||cstream.wi-fi.ru/csc-event$domain=auth.wi-fi.ru
@@||mc.yandex.ru/clmap/$domain=auth.wi-fi.ru
@@||mc.yandex.ru/webvisor/$domain=auth.wi-fi.ru
@@||mc.yandex.ru/watch/$domain=auth.wi-fi.ru
```
или по URL пусть импортирует
https://gist.githubusercontent.com/Alex-302/fa0987d1777ee60b3d3d563d007a7eae/raw/metro.txt

**Comment by evgeniy-ADG** [comment]
> Не помогло, таже беда(
> С отключенным adguard работает.

**Comment by Alex-302** [comment]
а это?
```
@@||auth.wi-fi.ru^$urlblock
```

**Comment by evgeniy-ADG** [comment]
> Добавил эту строку. Теперь кнопка Войти активна, но взамен приходится 
> смотреть две видеорекламы. И смысл? Можно просто перед входом в вайфай от 
> метро выключать Adguard, а после появления кнопки Войти снова включать. Так 
> хоть рекламы не будет.

**Comment by Alex-302** [comment]
> И смысл?

Есть такой метод - метод половинного деления.

Пусть добавит только эти правила и запишит новых лог запросов с временной отметкой
```
@@||googleads.g.doubleclick.net$domain=auth.wi-fi.ru
@@||googletagmanager.com/gtm.js$domain=auth.wi-fi.ru
@@||ads.adfox.ru/*/getCode?$domain=auth.wi-fi.ru
@@||cstream.wi-fi.ru/csc-event$domain=auth.wi-fi.ru
@@||mc.yandex.ru/clmap/$domain=auth.wi-fi.ru
@@||mc.yandex.ru/webvisor/$domain=auth.wi-fi.ru
@@||mc.yandex.ru/watch/$domain=auth.wi-fi.ru
```

**Comment by evgeniy-ADG** [comment]
1214655 - есть лог
1283234 - молчат

На iOS с правилом @@||auth.wi-fi.ru^$urlblock реклама не блокируется?

**Comment by Alex-302** [comment]
Нашёл подозрительный запрос.
Передай на проверку нескольким юзерам
```
@@||static.wi-fi.ru/banners/maximatelecom/advert/adblock.js
```

**Comment by evgeniy-ADG** [comment]
> Помогло! Огромное спасибо за ваш труд, очень облегчаете жизнь!

1214655

**Comment by iverkhohliad** [comment]
1641948

При добавлении правил реклама все равно не блокируется
@@||auth.wi-fi.ru^$urlblock
@@||static.wi-fi.ru/banners/maximatelecom/advert/adblock.js

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/32897610-c8041ee0-caee-11e7-9007-af8c87a004ad.png)

![image](https://user-images.githubusercontent.com/31481372/32897652-dfa245ea-caee-11e7-88c6-ea9ebd6aa638.png)

</details><br/>

**Comment by evgeniy-ADG** [comment]
http://auth.wi-fi.ru - the Connect button doesn't workhttp://auth.wi-fi.ru - the Connect button doesn't work

**Comment by Alex-302** [comment]
Какого правила? Какая система?

**Comment by evgeniy-ADG** [comment]
@@||static.wi-fi.ru/banners/maximatelecom/advert/adblock.js
android

**Comment by Alex-302** [comment]
оно на показ рекламы не влияет. Это маркер, по которому они блокировку детектят.
Попроси у кого нибудь HAR. Только запись нужно включить ДО включения wifi.

**Comment by evgeniy-ADG** [comment]
окей, попрошу

**Comment by evgeniy-ADG** [comment]
> Добрый день, уважаемая команда,
> 
> Высылаю файл har. Получается для того чтобы, войти в метро wi-fi, нужно сначала выключить
> Эдгард, подключиться к сети, потом включить Adguard

  ID: 1443393 @Alex-302 что с этим метро делать?

**Comment by Alex-302** [comment]
Что юзер под этим подразумевает?

**Comment by evgeniy-ADG** [comment]
Не работает кнопка входа.

**Comment by Alex-302** [comment]
Слишком много логов. Запишите себе, что всегда перед записью логов/HAR старые нужно удалять, а при записи запоминать время начала процедуры.
HAR нужен с выключенными фильтрами, чтоб видеть всё содержимое.

**Comment by vozersky** [comment]
Android

id1678179

[har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1555882/har.zip)

**Comment by altokarev** [comment]
Ещё жалоба (ID #1636196):
>При включенном dns и сервере adguard. Не заходит в московское wi-fi. После смены сервера dns на сервер провайдера. заходит на главную страницу, но кнопка зайти в интернет не активна.

**Comment by Alex-302** [comment]
со сторонним DNS и не зайдёт.
