### ISSUE TITLE
http://bt.kubyshka.org/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7137]
The site is dimmed, links can't be clicked on:

![image](https://user-images.githubusercontent.com/15856304/31714575-7a111f72-b409-11e7-83b7-b4c298e1994e.png)

### Steps to reproduce

1. Go to http://bt.kubyshka.org/
2. See what's on the screenshot

### Your environment

* OS: Windows 10
* Adguard version: AdGuard for Windows 6.2
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* HTTPS: On
* Driver: WFP
* Stealth mode: OFf
* DNS: Off

**Comment by Alex-302** [comment]
С этими фильтрами не повторяется.

**Comment by evgeniy-ADG** [comment]
WoT включен? Он на этот сайт ругается, может, как-то связано?

**Comment by Alex-302** [comment]
C WoT тоже не повторилось. Попроси помощником выбрать этот оверлей и скинуть получившееся правило.

**Comment by evgeniy-ADG** [comment]
не повторяется уже никак и нигде тоже.
