### ISSUE TITLE
CBC News (Android App) has blank advertisement boxes - Android

### ISSUE THREAD

**Issue by WorldIRC** [AdguardTeam/AdguardFilters#71381]
![cbc screenshot](https://user-images.githubusercontent.com/69649971/103441102-9e614400-4c19-11eb-97dd-232e50ad96e0.jpeg)
AdGuard for Android 3.6
As per screenshot, the ad is blocked, but the ad box is not removed.

**Comment by Alex-302** [comment]
Hi. These boxes are part of app, and cannot be blocked.
