### ISSUE TITLE
https://www.giveaway-club.com/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7138]
Missed ads.

### Steps to reproduce

1. https://www.giveaway-club.com/
2. See what's on the screenshot

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31715739-a5c98218-b40d-11e7-84b8-fa9afcc153d6.png)

</details>

### Your environment

* OS: Windows 10
* Adguard version: 6.2
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* Driver: WFP
* Stealth: Off
* HTTPS: On

**Comment by Alex-302** [comment]
Can't reproduce. Ask for saved page.

**Comment by Alex-302** [comment]
@AdamWr

**Comment by AdamWr** [comment]
I can reproduce.
Added:
`||giveaway-club.com/includes/js/blk-trh.js`
