### ISSUE TITLE
elektroda.pl

### ISSUE THREAD

**Issue by mat41997** [AdguardTeam/AdguardFilters#7139]
https://github.com/MajkiIT/polish-ads-filter/issues/4026#issuecomment-337550943
![31701608-d32a5980-b3d1-11e7-9a30-49d3a112860e](https://user-images.githubusercontent.com/5884000/31716418-f23e24f6-b407-11e7-9d39-711b4b070bdb.png)

my filters
https://gist.github.com/mat41997/d049ba53dd0fca8c3dad404ac58c701f

ubo 1.14.12 & ubo-pe 12.16
chrome 62.0.3202.62
win10 x64

**Comment by AdamWr** [comment]
Zrobione.
Aktualizacja będzie dostępna za około godzinę.
