### ISSUE TITLE
poznamka.ru - Anti Adblock

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7142]
https://poznamka.ru/belarus/paryzh

<details><summary>Screenshot:</summary>

<img width="1619" alt="screen shot 2017-10-19 at 1 20 38 am" src="https://user-images.githubusercontent.com/27292111/31745674-73577952-b46c-11e7-9c8c-27e2d7bb37b3.png">

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Windows OS
Browser:                            | Chrome
AdGuard version:                    | 6.1
Filters enabled:                    | 1 2 3 4 14
Helpdesk ID:            | 1498653

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed in annoyances
