### ISSUE TITLE
lowyat.net - Incorrect blocking 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7143]
https://www.lowyat.net/2017/144633/report-apple-to-ditch-touch-id-in-favour-of-face-id-in-all-2018-iphones/

Article under the picture is blocked when AdGuard is enabled.
<details><summary>Screenshot:</summary>
AdGuard is enabled
<img width="417" alt="screen shot 2017-10-19 at 4 21 39 am" src="https://user-images.githubusercontent.com/27292111/31749858-28b22ff0-b485-11e7-8df3-bacbfab839b7.png">
Adguard is disabled
<img width="411" alt="screen shot 2017-10-19 at 4 21 54 am" src="https://user-images.githubusercontent.com/27292111/31749859-29f032f4-b485-11e7-88ac-8e491b76026f.png">

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPhone
Platform: iOS
OS: 10.2

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.33.39 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.89 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.15 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.68 Enabled=YES

Helpdesk ID:           1646844

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
