### ISSUE TITLE
AdGuard blocks Yandex.Transoprt

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7144]
AdGuad reportedly interferes with Yandex.Transport app so the information about available means of transportation doesn't load.

Reproduced at 8:40 - [debug (1).txt](https://github.com/AdguardTeam/AdguardFilters/files/1397688/debug.1.txt)

### Your environment

* AdGuard version: 2.10.108
* Device and OS: Xiaomi, Android 5.1.1
* Filtering mode: VPN
* Filtering method: FULL
* Icon: Low priority
* HTTPS: Whitelist mode
* Filters: "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Experimental filter", "Mobile Ads filter", "Simplified domain names filter"
* DNS: False

**Comment by Alex-302** [comment]
@zebrum @altokarev @vozersky please check it.
It seems HTTPS filtering issue.

**Comment by Alex-302** [comment]
It does not work on my device without filters.

**Comment by Alex-302** [comment]
Full log:
[adguard.log](https://github.com/AdguardTeam/AdguardFilters/files/1398064/adguard.log)
[dnscrypt.log](https://github.com/AdguardTeam/AdguardFilters/files/1398065/dnscrypt.log)

**Comment by Alex-302** [comment]
Filed a bug
https://github.com/AdguardTeam/AdguardForAndroid/issues/1549

**Comment by Alex-302** [comment]
@evgeniy-ADG please ask to reset all settings to default.
