### ISSUE TITLE
TechMedia app - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7145]
Missed ads in HabraHabr client from TechMedia: https://play.google.com/store/apps/details?id=ru.habrahabr

### Steps to reproduce

1. Install the app
2. Browse around for 10 minutes
3. See ads appearing in the feed
4. If you clean the cache this would help until you restart the client

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31763327-a107fef8-b4c6-11e7-9425-1223d6648749.png)

</details>

### Your environment

* AdGuard version: 2.10.108
* Device and OS: Xiaomi, Android 7.0
* Filtering mode: VPN
* Filtering method: FULL
* Icon: Low priority
* HTTPS: Whitelist mode
* Filters: "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter"
* DNS: False

**Comment by Alex-302** [comment]
AdGuard cert must be moved to the system storage on Androin 6+
 
[Enable+HTTPS+Filtering+on+Android+Nougat.pdf](https://github.com/AdguardTeam/AdguardFilters/files/1398016/Enable.HTTPS.Filtering.on.Android.Nougat.pdf)

User can try this rule 
```
||graph.facebook.com^$app=ru.habrahabr
```
Facebook auth will be broken.

**Comment by evgeniy-ADG** [comment]
What if it's not in the system storage? No HTTPS filtering at all?

**Comment by Globulopolis** [comment]
Same issue with Facebook and Youtube app.

**Comment by evgeniy-ADG** [comment]
@Globulopolis Facebook uses SSL pinning, it's whitelisted in the HTTPS filtering. You can enable it in AdGuard > Settings > Apps settings > Facebook and restart protection, it won't work at all. That's why it's partially whitelisted. Regarding youtube, please see this: https://kb.adguard.com/en/android/solving-problems/youtube-ads
