### ISSUE TITLE
https://www.sammobile.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7146]
**Site Sample** | 
----|
https://www.sammobile.com

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Opera Stable x64
AdGuard version:                    | **6.2.424.2123**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Screenshoot
![image-20171019-002](https://user-images.githubusercontent.com/9846948/31765372-75c56d22-b4c4-11e7-9266-af93be1fec7d.png)

### Fix
```
sammobile.com###topbar-ad-wrapper
```

**Comment by Alex-302** [comment]
Added to Annoyances filter
