### ISSUE TITLE
Pop ups on couple sites

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#71474]
These pop ups/pop unders appear for me when I click or go to different links on the site. I am using iOS safari 

sites:

gamepciso: 
(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url= gamepciso.com)

downloadgamepsp: 
(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url= downloadgamepsp.com)

downloadgameps3:
(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url= downloadgameps3.com)

[downloadgamexbox: 
(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url= downloadgamexbox.com)

**Comment by Alex-302** [comment]
Cannot reproduce. Blocked one ad server.
