### ISSUE TITLE
blick.ch

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdguardFilters#71500]
### Issue URL (Ads)
 
 https://www.blick.ch/schweiz/bern/video-zeigt-gefaehrliche-silvester-aktion-in-bosnien-schweizer-autotuner-schiesst-mit-feuerwerk-auf-gegenfahrbahn-id16272964.html

 ### Comment
 
 Username: @Morku
 
 > ## Ad placeholder
 > Die folgenden Informationen werden automatisch generiert. Bitte löschen Sie sie nicht.
 > Custom userscripts:
 > https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
 
 ### Screenshots
<details><summary>Screenshot-1:</summary>

![blick](https://user-images.githubusercontent.com/6276915/103468501-d96a9100-4d59-11eb-99c4-1f0d21c72834.png)

</details><br/>

 ### System configuration
 Information 	value
 AdGuard product: 	AdGuard for Windows v7.5.3
 Browser: 	Firefox
 AdGuard driver: 	WFP
 Stealth mode options: 	Hide your search queries,
 Send Do-Not-Track header,
 Remove X-Client-Data header from HTTP requests,
 Strip URLs from tracking parameters
 Filters: 	Ad Blocking:
 AdGuard Mobile Ads,
 AdGuard Base
 
 Privacy:
 AdGuard Tracking Protection
 
 Social Widgets:
 AdGuard Social Media
 
 Annoyances:
 AdGuard Annoyances
 
 Language-specific:
 AdGuard Russian,
 AdGuard German

**Comment by BlazDT** [comment]
Fixed alongside some cleanup on main page.
