### ISSUE TITLE
mtoo.kr - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7151]
https://www.mtoo.kr/index.php?mid=webtoon&category=780067&document_srl=782074

A lot of banners and ads on the page.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/31778539-94cde8cc-b4f9-11e7-9349-99675f3b031d.png)

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPhone
Platform: iOS
OS: 11.0.2

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.33.39 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.68 Enabled=YES
ID=227 Name="List-KR" Version=1.0.3.37 Enabled=YES
Mobile ads filter

Helpdesk ID:         1645252

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
```
mtoo.kr#%#Object.defineProperty(window, 'banners', { get: function() { return []; } });
!+ PLATFORM(ios, ext_android_cb, ext_opera, ext_ublock, ext_ff)
mtoo.kr##.gpe_contents_box > a > img
mtoo.kr##div[class^="scban_"]
```
@seanl-adg please take a look
