### ISSUE TITLE
pc-magazin.de - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7152]
http://www.pc-magazin.de/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/31785937-7542ae14-b50f-11e7-9322-3ed00c9ee1ef.png)

</details><br/>

***System configuration***

Application version: 1.3.2.108
Device: iPhone
Platform: iOS
OS: 11.1.

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.33.50 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.92 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.17 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.60 Enabled=YES
ID=6 Name="German filter" Version=1.0.37.25 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.10 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.68 Enabled=YES

Helpdesk ID: 1322540

**Comment by AdamWr** [comment]
Fixed.
