### ISSUE TITLE
pietsmiet.de - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7153]
http://www.pietsmiet.de/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/31786327-c6b37ef8-b510-11e7-8828-f64f31385b7c.png)

</details><br/>

***System configuration***

Application version: 1.3.2.108
Device: iPhone
Platform: iOS
OS: 11.1.

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.33.50 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.92 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.17 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.60 Enabled=YES
ID=6 Name="German filter" Version=1.0.37.25 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.10 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.68 Enabled=YES

Helpdesk ID: 1322540

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce with German VPN.
@AdamWr

**Comment by AdamWr** [comment]
I can reproduce.
Added:
`@@/ad_dir/*$image,domain=pietsmiet.de`
