### ISSUE TITLE
"Trending products" on Microsoft Edge default page

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#71534]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

The "Trending products" (products are ranked based on relevance to your search) is not blocked

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/103475849-8aecdf00-4db9-11eb-8ba9-833e8c668142.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

The "Trending products" section is removed 

***Steps to reproduce the problem***:

1. Install Edge
2. Gear > Advanced > Language and content > English
3. Scroll down until the Trending products appear

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

Base, Tracking protection, Annoyances, Social media, Russian

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  macOS 11.1 or Win 10
Browser:                               | Edge 87.0
AdGuard version:                       | 2.5.2.939
Filters enabled:                       | Base, Tracking protection, Annoyances, Social media, Russian
AdGuard DNS:                           | Default
Helpdesk ID (if exists):               | 2997028

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by BlazDT** [comment]
Not seeing that section, please check @AdguardTeam/filters-maintainers

**Comment by stanislav-atr** [comment]
I was only able to reproduce native ad blocks, could you please try to disable Edge Tracking Prevention? 
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68852737/104168628-61fac880-540f-11eb-8bf9-8a6b013dc52b.png)
</details><br/>

**Comment by Eugene-Savenko** [comment]
I disabled that, restarted Edge, but the trending product block is still there.
