### ISSUE TITLE
faz.net

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdguardFilters#71539]
### Issue URL ((Incorrect Blocking))
 
 https://www.faz.net/aktuell/gesellschaft/gesundheit/coronavirus/mediziner-im-gespraech-ueber-die-corona-impfung-17127857.html

 ### Comment
 
 Username: @Morku
 
 > ## You can't allow (Zustimmen) the external content to load the embedded Youtube video. You need to disable Annoyance filter first, deny all Cookies and it will work.
 > Die folgenden Informationen werden automatisch generiert. Bitte löschen Sie sie nicht.
 > Custom userscripts:
 > https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
 
 ### Screenshots
<details><summary>Screenshot-1:</summary>

![faz1](https://user-images.githubusercontent.com/6276915/103477254-5bd86c80-4dbd-11eb-9fbb-dc804231c782.png)

</details><br/>

<details><summary>Screenshot-2:</summary>

![faz2](https://user-images.githubusercontent.com/6276915/103477257-63981100-4dbd-11eb-82f2-33fc599e0279.png)

</details><br/>

 ### System configuration
 Information 	value
 AdGuard product: 	AdGuard for Windows v7.5.3
 Browser: 	Firefox
 AdGuard driver: 	WFP
 Stealth mode options: 	Hide your search queries,
 Send Do-Not-Track header,
 Remove X-Client-Data header from HTTP requests,
 Strip URLs from tracking parameters
 Filters: 	Ad Blocking:
 AdGuard Mobile Ads,
 AdGuard Base
 
 Privacy:
 AdGuard Tracking Protection
 
 Social Widgets:
 AdGuard Social Media
 
 Annoyances:
 AdGuard Annoyances
 
 Language-specific:
 AdGuard Russian,
 AdGuard German

**Comment by BlazDT** [comment]
Free article: https://www.faz.net/aktuell/politik/ausland/warum-die-eu-nicht-mehr-impfdosen-bestellt-hat-17128800.html

Site is not showing cookie message for me even after disabling AdGuard. Please check these two rules:
```
@@||cdn.privacy-mgmt.com/wrapperMessagingWithoutDetection.js$domain=faz.net
@@||consent.faz.net/Notice.*.js$domain=consent.faz.net
```

**Comment by Morku** [comment]
There is.

<details><summary>Screenshot-1:</summary>

![faz](https://user-images.githubusercontent.com/6276915/103484776-a4aa1880-4df1-11eb-98b0-80d47ce8658b.png)

</details><br/>

Is it me or did the article turned now into FAZ+ one? Oo Weird.

I managed to get a new article with external content: https://www.faz.net/aktuell/politik/inland/kritik-an-impfstrategie-der-bundesregierung-waechst-17127774-p2.html

I can confirm, after adding this rules, now getting the Cookie Pop-up,refuse every unnecessary Cookie, I can load the Youtube video.

Interestingly, they have external content you must allow which do not show up when you refused all unnecessary Cookies: https://www.faz.net/aktuell/politik/inland/lockdown-bis-31-januar-bundeslaender-uneins-ueber-oeffnung-von-schulen-und-kitas-17128252.html
When I accept all Cookies, it will show. It's not an AG issue, but interesting for the automatic rule.

<details><summary>Video-1:</summary>

https://user-images.githubusercontent.com/6276915/103485109-5e09ed80-4df4-11eb-8f5f-63a441fd4473.mp4


</details><br/>

**Comment by BlazDT** [comment]
Please check for JS rule @AdamWr

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
