### ISSUE TITLE
the-voice-of-germany.de - Anti adblock 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7154]
https://www.the-voice-of-germany.de/first-look

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/31786644-dfea8e88-b511-11e7-8019-10efaf46b9e3.png)

</details><br/>

***System configuration***

Application version: 1.3.2.108
Device: iPhone
Platform: iOS
OS: 11.1.

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.33.50 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.92 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.17 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.60 Enabled=YES
ID=6 Name="German filter" Version=1.0.37.25 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.10 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.68 Enabled=YES

Helpdesk ID: 1322540

**Comment by Alex-302** [comment]
Added to German filter
```
@@||the-voice-of-germany.de^$generichide
```
