### ISSUE TITLE
http://comp-doctor.ru/ Ads

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7157]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

http://comp-doctor.ru/

***Description***: Missed ads on http://comp-doctor.ru/zoj/temperatura.php
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![screen shot 2017-10-20 at 3 03 04 am](https://user-images.githubusercontent.com/32528702/31799664-1b0e8000-b544-11e7-9d0b-e6a1b7634e43.png)

</details><br/>

**Filters:**
English, Spyware, Social media, Annoyances, Russian, Japanese

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows NT 10.0
Browser:                            | ?
AdGuard version:                    | 6.2.424.2123
Filters enabled:                    | 2, 3, 4, 14, 1, 7
Helpdesk ID (if exists):            | 1374004

**Comment by Alex-302** [comment]
Fixed.
