### ISSUE TITLE
Missed ads on hoerzu.de

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7158]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

https://www.hoerzu.de/radio-programm/das-radioprogramm-als-download

***Description***: Missed ads reported by customer using iPhone, reproduced on our Mac as well.
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

1.
![image1](https://user-images.githubusercontent.com/32528702/31800714-75145ece-b54b-11e7-9b5c-f32cc1e0b0d3.jpeg)

2.
![screen shot 2017-10-20 at 1 53 43 am](https://user-images.githubusercontent.com/32528702/31800745-a6f43662-b54b-11e7-8f5c-04569c9a46db.png)

</details><br/>

**Filters:**
User filter, English, Spyware, Social media, Annoyances, German, Safari

Information                         | Value
---                                 | ---
Operating system:                   | iOS 11.0.3
Browser:                            | Safari
AdGuard version:                    | 1.3.2.108
Filters enabled:                    | 2, 3, 4, 14, 6, 12
Simplified filters (iOS only)       | Off
Helpdesk ID (if exists):            | 1609733

**Comment by AdamWr** [comment]
Fixed.
