### ISSUE TITLE
Pop ups when clicking Top right

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#71598]
@ghost commented on [Sun Jan 03 2021](https://github.com/AdguardTeam/PopupBlocker/issues/228)

URL:  https://dizigang.com/

Steps to solve the problem:
Add this: dizigang.com##.pageskin

**Comment by AdamWr** [comment]
It seems that it's the same issue as here - https://github.com/AdguardTeam/AdguardFilters/issues/71403#issuecomment-753579271
