### ISSUE TITLE
Promods.net adblock detect

### ISSUE THREAD

**Issue by ullortnaci** [AdguardTeam/AdguardFilters#71597]
When I try to download files on Promods.net I see AdBlock detection. Example URL: https://www.promods.net/extra.php?mod=cap
![Przechwytywanie](https://user-images.githubusercontent.com/74502405/103519155-53dc0380-4e75-11eb-9aa0-8cddfe27eb8f.PNG)

**Comment by AdamWr** [comment]
Fixed, filters update should be available in 1-2 hours.
Please next time fill the template.
