### ISSUE TITLE
www.israelnetz.com - Annoyance

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7160]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Cookie notice
https://www.israelnetz.com/politik-wirtschaft/sicherheit/2017/10/17/niemals-kann-ich-das-vergessen/

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/31804669-7807bcf8-b563-11e7-8322-cec9d21786ac.png)

</details><br/>

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.30.79 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.50 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.22 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.18.39 Enabled=YES
ID=6 Name="German filter" Version=1.0.36.67 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.61 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.2.28 Enabled=NO

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS
Adguard version  :  | 1.2.1.71
Simplified filters (iOS only)       | Off
Helpdesk ID (if exists):            | 1630615

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
