### ISSUE TITLE
Add visilabs.com and visilabs.net domains to full whitelist

### ISSUE THREAD

**Issue by BasakRelated** [AdguardTeam/AdguardFilters#71603]
We are all-in-one marketing automation service providing company (like marketo, hubspot) which is located in İstanbul. We have more than 600 customers local and global. www.relateddigital.com

We develop segmented campaign scenarios using custom js on the websites of our customers. Our domain names are visilabs.com and visilabs.net. Our domain seems blocked by the Adguard blocker. This causes our product not to work properly on the customer page and we receive customer complaints. 
Sample site: marieclaire.com.tr, www.boyner.com.tr, www.englishhome.com

We are not the owner of www.marieclaire.com.tr website. Marie Claire is a cosmetics and fashion magazine company.
As I mentioned before we are a B2B company which has companies as our customers. Marie Claire is our customer company.

Custom js codes make service calls to our platform to show a custom popup and similar actions. To reach our platform js codes make call to visilabs domains.

So when we are listed as a blacklist in Adguard filters our scenarios do not work on our customer's website. For example in www.marieclaire website our product domain is listed in blacklist. As our javascript codes are blocked and our customers (Marie Claire in this case) cannot show their own B2C customers our popups to sell more products or collect more data. 

Lately we got information from your teams as following:
Our script is blocked with /visilabs.min.js and other related rules from the Tracking protection filter as it's being used for tracking purposes. 

So is it possible to become eligible or whitelisted for adguard filters?

![image (5) (1)](https://user-images.githubusercontent.com/76945096/103526191-93b0e400-4e91-11eb-9f91-222892ec8055.png)
![image (6) (1)](https://user-images.githubusercontent.com/76945096/103526195-957aa780-4e91-11eb-8e8d-072d318ecb45.png)
![image (7) (1)](https://user-images.githubusercontent.com/76945096/103526199-97446b00-4e91-11eb-8302-9261afd23b6c.png)

**Comment by gork7777** [comment]
@Yuki2718 Hi, what can we do for this? The rule on the Boyner site: || visilabs.net^$third-party and I don't see any error on english home site

**Comment by Yuki2718** [comment]
I'll leave the decision to the official AG member.

**Comment by Alex-302** [comment]
@BasakRelated Hi. Could you please write steps to reproduce with video?

**Comment by BasakRelated** [comment]
Hi AdguardTeam,

Andrey Meshkov helped us to solve the problem.

Thank you for your support 🙏


*Başak ACAR YILMAZ*

VP - Product

*t.*   +902123430739
*f.*   +902123430742
*m.* +905322106617

*email: *basak.acar@relateddigital.com <%23>
*web: *relateddigital.com <http://www.relateddigital.com/>
Maslak Mah. Büyükdere Cd. No:249 Sarıyer - İstanbul / Türkiye

<https://www.linkedin.com/company/related-digital/>
<https://www.facebook.com/relateddigital>
<https://twitter.com/relateddigital> <http://blog.relateddigital.com/>

<http://www.relateddigital.com/?utm_source=email-signature&utm_medium=email>

Bu e-posta içeriği, mesajın alıcı kısmında belirtilmiş olan kişi/kurum
içindir ve sadece gönderilen kişiye/kuruma yöneliktir. Mesajın gönderilmek
istendiği kişi/kurum değilseniz, lütfen doğrudan veya dolaylı olarak mesajı
kullanmayınız ve mesajın tüm kopyalarını sisteminizden derhal siliniz. Bu
mesaj kişisel veri içerebilir, böyle bir durumda mesajın muhatabı
değilseniz, ilgili mevzuat kapsamında kişisel veri içeren mesajı tüm
sistemlerinizden derhal kaldırın. Related Digital, bu e-postada yer alan
hatalardan veya eksikliklerden sorumlu değildir ve e-posta kullanımından
kaynaklanan zararlardan sorumlu tutulamaz. Bu mesajda yer alan herhangi bir
görüş ve beyan ya da herhangi bir ek yalnızca yazarına aittir ve Related
Digital’i mutlak anlamda temsil etmemektedir.


This e-mail content is solely for the individual/entity who has been
mentioned specifically in the recipient section of the e- mail and intended
solely for the addressee. If you are not the intended addressee, please do
not use the message directly or indirectly and delete the message and all
its copies immediately. This message may contain personal data, if you are
not the recipient of the message remove the message immediately from all
your systems under the relevant legislation within the scope of personal
data. Related Digital is not responsible for errors or omissions in this
message and cannot be held responsible for any damage arising from the use
of e-mail. Any opinion and other statement contained in this message and
any attachment are solely those of the author and do not necessarily
represent Related Digital.
