### ISSUE TITLE
macwelt.de - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7164]
https://www.macwelt.de/

Please, open a desktop version of this website to reproduce the issue.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/31847252-75c70d72-b621-11e7-82db-44e01bdd6ac1.png)

</details><br/>

***System configuration***

Application version: 1.3.2.108
Device: iPhone
Platform: iOS
OS: 11.0.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.33.63 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.96 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.20 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.67 Enabled=YES
ID=6 Name="German filter" Version=1.0.37.28 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.68 Enabled=YES

Helpdesk ID:           1609733

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
