### ISSUE TITLE
Adguard doesn't adequately filter ads in Apple's News app in Big Sur 11.1

### ISSUE THREAD

**Issue by odysseus90210** [AdguardTeam/AdguardFilters#71642]
I find that, unlike Adguard for iOS, Adguard for Mac OS (even the latest nightly) does not adequately block ads in Apple's News app running under Big Sur 11.1 on an M1 MacBook Pro. I have, of course, added News to the list of apps under Preferences > Automatically Filter Applications. I have also, FWIW, selected the Adguard DNS filter. Finally, at the suggestion of Adguard tech support, I have added the following domain to the User Rules section:

||adplatform.apple.com^$important,document

This made no difference.

**Comment by Alex-302** [comment]
@odysseus90210 Hi. Do you see related to this app requests in AdGuard's filtering log?

**Comment by odysseus90210** [comment]
Yes, but ads still appear.

**Comment by Alex-302** [comment]
Ok. Could you please make screenshots of filtering log? Don't forget to clear it before reproducing(and close an app before it).

**Comment by odysseus90210** [comment]
Can you respond a little more quickly? This is taking forever.

Best,
Marc

**Comment by odysseus90210** [comment]
Here you go.

Best,
Marc

**Comment by Alex-302** [comment]
@odysseus90210 Hi. Sorry for delay. You can write to [Telegram ](https://t.me/Alex302) or write to filters@adguard.com

**Comment by odysseus90210** [comment]
See GitHub bug #72492.

Best,
Marc

**Comment by odysseus90210** [comment]
GitHub #72492

Best,
Marc

**Comment by Alex-302** [comment]
Ok.
