### ISSUE TITLE
NNMClub не загружает скриншоты при открытии любой раздачи

### ISSUE THREAD

**Issue by thunderresistant** [AdguardTeam/AdguardFilters#71641]
Настройки сток, (добавление собственного фильтра ничего не меняет), Android 11, Adguard VPN в режиме совместимости.
При посещении сайта nnmclub.to не загружаются скриншоты и другие картинки в раздачах.
Гирлянда наверху вообще обрезана))

![Screenshot_20210104-190456](https://user-images.githubusercontent.com/45038010/103554417-f1f4bb80-4ebf-11eb-8b02-4d0e6cc8adfe.png)

**Comment by Alex-302** [comment]
@thunderresistant Добрый день.
У меня проблем со скринами нет(дроид/десктоп):
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/104216099-4ceb5d00-5442-11eb-9076-ca2d0e2675ed.png)

</details>

Лучше отправьте отчёт, все настройки будут заполнены автоматически. Нужно указать только адрес и скриншот.
