### ISSUE TITLE
click popup ads site(and its sub-domains): k26fe9xhuzm.com

### ISSUE THREAD

**Issue by catshitz** [AdguardTeam/AdguardFilters#7166]
http://k26fe9xhuzm.com/921851.html?q

**Comment by Alex-302** [comment]
We need a source page where it happens.

**Comment by catshitz** [comment]
Forgotten, sorry, NSFW: 
http://rule34hentai.net/post/view/273991 (example)
Actually all the sub-domain of this site rule34hentai.net after your first open of its sub pages.

**Comment by Alex-302** [comment]
Please add these rules and check in private tab
```
rule34hentai.net#%#window.zfgloadedpopup = true;
rule34hentai.net###main > div.blockbody
```

**Comment by catshitz** [comment]
Doesn't work.
