### ISSUE TITLE
arenavision.ru - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7168]
***Site***: http://arenavision.ru/
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31851775-172a1600-b66d-11e7-8c21-1dabd5a65258.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.431.2165
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter
Russian filter

**Comment by AdamWr** [comment]
Fixed.
