### ISSUE TITLE
fandom.com (mobile)

### ISSUE THREAD

**Issue by cwyc** [AdguardTeam/AdguardFilters#71681]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
All subdomains of fandom.com show a video ad overlay on the mobile site. The screenshotted page is https://gta.fandom.com/wiki/Mail.eyefind.info

A cosmetic filter that blocks it is: `fandom.com##.article-featured-video__player`

![image](https://user-images.githubusercontent.com/16950437/103618317-bbd62c80-4efd-11eb-9d35-b3d013b1e1b5.png)

***System configuration***
Can be seen on Firefox for Android 84.1.2, and Firefox desktop 84.0 with the Responsive Design Mode. Using uBlock Origin.

**Filters:**

AdGuard Base, AdGuard Mobile Ads, AdGuard Annoyances, uBlock filters, EasyList, EasyPrivacy, Online Malicious URL Blocklist, Anti-Facebook, Fanboy's Annoyance, Fanboy's Social, Peter Lowe’s Ad and tracking server list

Information                            | Value
---                                    | ---
Operating system version (Android/iOS) | Android 10
Browser:                               | Firefox 84.1.2

**Comment by krystian3w** [comment]
Test with Fanboy Annoyance or uBlock Annoyances.

* https://subscribe.adblockplus.org/?location=https://secure.fanboy.co.nz/fanboy-annoyance.txt&title=Fanboy-Annoyance
* https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances.txt&title=uBO-Annoyance

**Comment by cwyc** [comment]
I actually had uBlock annoyances enabled, but I can see that it's in the list. I'll have to see what's wrong on my end.
