### ISSUE TITLE
adsurl.xyz - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7171]
***Site***: http://adsurl.xyz/zaPOI
***Description***: Adblock detection.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31851835-0bfa54ce-b66e-11e7-82d1-c3be8d6000fd.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.431.2165
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
It seems, that this website is "dead".

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/32180447-4dcf7fe8-bd92-11e7-93cf-2cc9bc35c9e2.png)

</details>
