### ISSUE TITLE
cdn.shortpixel.ai (false positive)

### ISSUE THREAD

**Issue by 3xploiton3** [AdguardTeam/AdguardFilters#71720]
![image](https://user-images.githubusercontent.com/19517680/103697093-02955680-4fd2-11eb-8438-c83d146976c4.png)

cdn.shortpixel.ai

it's break images on
https://www.expressvpn.com/blog/expressvpn-wireguard-update/

**Comment by 3xploiton3** [comment]
@nextdns

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/66846

**Comment by Alex-302** [comment]
I cannot reproduce.
