### ISSUE TITLE
thetelegraphandargus.co.uk - Ad - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7173]
***Site***: http://www.thetelegraphandargus.co.uk/
***Description***: Ad and newsletter form.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31851886-e85c8dd8-b66e-11e7-8ab0-bd240d5dd191.png)

![image](https://user-images.githubusercontent.com/10995998/31851890-f63abb96-b66e-11e7-8fe1-4eaa8598fb58.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.431.2165
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
