### ISSUE TITLE
onitube.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7174]
***Site***: https://www.onitube.com/video/50147/supergirl-s03e02-triggers
***Description***: Ad leftover

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31851940-f9cfad7e-b66f-11e7-8dba-8775a99d4905.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.431.2165
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
