### ISSUE TITLE
simply-debrid.com - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7175]
***Site***: https://simply-debrid.com/generate
***Description***: Adblock detection (enter this link: http://www75.zippyshare.com/v/u4weZ846/file.html)

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/31852029-fa2fbc90-b670-11e7-82af-9c94eb821dcf.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.431.2165
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
