### ISSUE TITLE
https://myaccount.ingramspark.com - the site opens slowly with AdGuard

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7178]
It takes about 30 seconds for it to fully open, works fine when AdGuard is disabled. The customer states that adding @@||myaccount.ingramspark.com to the user filter doesn't help.

> I can make a cup of tea between pages, with many often timing out. Tried the usual culprits of firewalls, antivirus & antimalware, but it was only when I fully disabled Adguard via the start-up tab in task manager (I'm using Windows 10) that the site worked normally. Have tried adding the site to the user filter @@||myaccount.ingramspark.com, but this doesn't seem to have any effect. 

### Steps to reproduce

1. Go to https://myaccount.ingramspark.com and try to set up an account
2. Should be working really slow
3. Open it with AdGuard shut down > works fast

### Your environment

* OS: Windows 10
* Adguard version: AdGuard for Windows 6.2
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* HTTPS: On
* Driver: WFP
* Stealth mode: OFf
* DNS: Off

**Comment by Alex-302** [comment]
filed a bug
