### ISSUE TITLE
gizmodo.com - Anti-Adblocker

### ISSUE THREAD

**Issue by vitalkanev** [AdguardTeam/AdguardFilters#7179]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: gizmodo.com warns user about adblocker

**Screenshot**: [Hosted on Firefox Screenshots](https://screenshots.firefox.com/LigwxP0q5FM2O137/gizmodo.com)

**Page**: https://gizmodo.com/adobe-flash-fans-want-a-chance-to-fix-its-one-million-b-1797284544

***System configuration***

**Filters:** English, Annoyances, Russian, German, EasyList, RUAdList

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Xubuntu Zesty
Browser:                            | Firefox 56
AdGuard version:                    | 2.7.1 Extension
Helpdesk ID (if exists):            | ?

**Comment by Alex-302** [comment]
Fixed in annoyances.
