### ISSUE TITLE
http://www.crazyhd.com/index.php - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7180]
They're using an anti-adblocker :)

![image](https://user-images.githubusercontent.com/15856304/31854794-dfaaeae8-b6a7-11e7-85b7-3a59b3e580a6.png)

### Steps to reproduce

1. Go to http://www.crazyhd.com/index.php
2. Log in, you can find test acc info in the support ticket

### Your environment

* OS: Windows 10
* Adguard version: AdGuard for Windows 6.2
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* HTTPS: On
* Driver: WFP
* Stealth mode: OFf
* DNS: Off

**Comment by Alex-302** [comment]
Not reproduced on my end.

**Comment by AdamWr** [comment]
I can reproduce.
Fixed.
