### ISSUE TITLE
Adblock script issue on www.ebookdz.com

### ISSUE THREAD

**Issue by Zardangus** [AdguardTeam/AdguardFilters#71803]
Hi all,

Happy new year !

Hi, all.

I had the same issue mounths ago and @zloyden and @Alex-302 and @AdamWr helped me fixed it, thank to them. The issue number is
ebookdz.com # 57547 at :
#57547 (comment)

When i go to www.ebookdz.com, Adguard is detected and i have to disable it. If i don't want to, i can't go on the website.

I tried to logg out and logg in, but I have thé same problem.

Here is a screenshot :

![Screenshot_20210107_082605_com kiwibrowser browser](https://user-images.githubusercontent.com/67057008/103865038-dd811080-50c3-11eb-981a-e1b2ab024937.jpg)

How my I fixe it again?

Thank you for your help.

**Comment by krystian3w** [comment]
Maybe `race-condition`?

Test these:

```
ebookdz.com#%#//scriptlet('abort-on-property-read', 'AaDetector')
ebookdz.com#%#//scriptlet('prevent-setTimeout', 'nextFunction', '2000')
```

**Comment by Zardangus** [comment]
Hi,
Thank you for your réponse.
How to do for testing that?

**Comment by krystian3w** [comment]
Copy rules into a "custom" in AdGuard for Android app.

> Settings ➡️  "block content" ➡️ "User Filters" ➡️ activate "User Filters" ➡️  paste both by "+" button.

**Comment by Zardangus** [comment]
Thank you,
I tested, it doesn't work. ☹️

**Comment by Zardangus** [comment]
![Screenshot_20210107_091218_com adguard android](https://user-images.githubusercontent.com/67057008/103867942-6c902780-50c8-11eb-876d-57427efe9e19.jpg)

**Comment by krystian3w** [comment]
I see, try copy manually 1 by 1 = you should have two rules with checkmark:

- [X] `ebookdz.com#%#//scriptlet('abort-on-property-read', 'AaDetector')`
- [X] `ebookdz.com#%#//scriptlet('prevent-setTimeout', 'nextFunction', '2000')`

**Comment by wout-codes** [comment]
Hi @krystian3w, 
There is an Ad even after enabling AdGuard French Filter.
![image](https://user-images.githubusercontent.com/76908410/103869596-800db380-5105-11eb-9760-918b87c6569a.png)

**Comment by Zardangus** [comment]
> I see, try copy manually 1 by 1 = you should have two rules with checkmark:
> 
>     * [x]  `ebookdz.com#%#//scriptlet('abort-on-property-read', 'AaDetector')`
> 
>     * [x]  `ebookdz.com#%#//scriptlet('prevent-setTimeout', 'nextFunction', '2000')`

Thank you, but it doesn't work 😢

**Comment by krystian3w** [comment]
To hide red button possible use:

`ebookdz.com##center > a[href*="//see.kmisln"] > img`

**Comment by wout-codes** [comment]
Yes, I could reproduce it. I reported so that it will be added to the Filters. 

> To hide red button possible use:
> 
> `ebookdz.com##center > a[href*="//see.kmisln"] > img`

**Comment by wout-codes** [comment]
@Zardangus Try this. I am not sure if this works, but try. 

Add: [code] ebookdz.com#%#//scriptlet("abort-on-property-write", "adBlockDetected")

**Comment by wout-codes** [comment]
@Zardangus Try this, I am not sure if this works, but try. 

Code: ebookdz.com#%#//scriptlet("abort-on-property-write", "adBlockDetected")

*Add the same way as how @krystian3w told you to. *

**Comment by krystian3w** [comment]
May no works, this is old code from 2018 and no longer exist in AdGuard repository.

**Comment by wout-codes** [comment]
But try, it might work.

**Comment by wout-codes** [comment]
You can still try. It still might work.

**Comment by Zardangus** [comment]
> @Zardangus Try this, I am not sure if this works, but try.
> 
> ` ebookdz.com#%#//scriptlet("abort-on-property-write", "adBlockDetected") `
> 
> *Add the same way as how @krystian3w told you to. *

Thank you,
I will try.
so i will have 3 rules, correct ?

**Comment by wout-codes** [comment]
> > @Zardangus Try this, I am not sure if this works, but try.
> > `ebookdz.com#%#//scriptlet("abort-on-property-write", "adBlockDetected")`
> > *Add the same way as how @krystian3w told you to. *
> 
> Thank you,
> I will try.
> so i will have 3 rules, correct ?

Nope, only this rule: <code>ebookdz.com#%#//scriptlet("abort-on-property-write", "adBlockDetected")</code>

**Comment by Zardangus** [comment]
> @Zardangus Try this, I am not sure if this works, but try.
> 
> ` ebookdz.com#%#//scriptlet("abort-on-property-write", "adBlockDetected") `
> 
> *Add the same way as how @krystian3w told you to. *

![Screenshot_20210107_120514_com adguard android](https://user-images.githubusercontent.com/67057008/103885684-ab31dc00-50e0-11eb-8f89-0cc027591f72.jpg)

It doesn't work 😶

**Comment by wout-codes** [comment]
Nope, only this rule: ebookdz.com#%#//scriptlet("abort-on-property-write", "adBlockDetected")

**Comment by Zardangus** [comment]
> Nope, only this rule: ` ebookdz.com#%#//scriptlet("abort-on-property-write", "adBlockDetected") `
> Only add this rule, remove all the others.

I did, it doesn't work 🤷‍♂️🤔

**Comment by wout-codes** [comment]
Hmm. interesting, worked for me though. @AdamWr take a look please.

**Comment by wout-codes** [comment]
Interesting

**Comment by krystian3w** [comment]
You tried use solutions from older topics? Maybe again is glitched TLS AdGuard certyficate.

**Comment by Zardangus** [comment]
> You tried use solutions from older topics? Maybe again is glitched TLS AdGuard certificate.

Which solutions ?

**Comment by Zardangus** [comment]
Hi again,
there is now way to fixe this issue please ?

🙏

**Comment by wout-codes** [comment]
@BlazDT Take a look please. I can’t reproduce any fix.

**Comment by BlazDT** [comment]
Sadly I cannot reproduce the issue on my Android 11 with given config in linked old issue.

Please try this rule for testing:

`@@||ebookdz.com^$important,elemhide`
If working, then please remove previous rule and try this one:
`@@||ebookdz.com^$important,generichide`
If not working, please remove previous rule and try this one:
`@@||ebookdz.com^$important,elemhide,urlblock`
If working, then please remove previous rule and try this one:
`@@||ebookdz.com^$important,elemhide,genericblock`

If still failing, please try to reproduce in Chrome browser instead of Kiwi.

**Comment by Zardangus** [comment]
> Sadly I cannot reproduce the issue on my Android 11 with given config in linked old issue.
> 
> Please try this rule for testing:
> 
> `@@||ebookdz.com^$important,elemhide`
> If working, then please remove previous rule and try this one:
> `@@||ebookdz.com^$important,generichide`
> If not working, please remove previous rule and try this one:
> `@@||ebookdz.com^$important,elemhide,urlblock`
> If working, then please remove previous rule and try this one:
> `@@||ebookdz.com^$important,elemhide,genericblock`
> 
> If still failing, please try to reproduce in Chrome browser instead of Kiwi.

Thank you.
I tried, it doesn't work.
What's is the good way ?
For each try i have to restart adguard and my browser and empty the cash or it is OK, just I add the rule and i refresh my browser?

Sorry my english is bad 😅

**Comment by BlazDT** [comment]
You add the rule, wait a bit (until the key symbol next to the clock comes back) and then refresh the site.

One last rule for you to try:

`@@||ebookdz.com^$important,document`

**Comment by Zardangus** [comment]
> You add the rule, wait a bit (until the key symbol next to the clock comes back) and then refresh the site.
> 
> One last rule for you to try:
> 
> `@@||ebookdz.com^$important,document`
> 
> If you have a forum account (https://forum.adguard.com/index.php), please PM me (Blaz) login.

I sent you a PM on the forum but I am not sure if i did it correctly. Please confirm if you got my PM.
Thanks. 🙏

**Comment by BlazDT** [comment]
Yes, received it.

**Comment by BlazDT** [comment]
Should be working after update in about 3 hours (unless you use some DNS server which is blocking the domain.

**Comment by Zardangus** [comment]
> Should be working after update in about 3 hours (unless you use some DNS server which is blocking the domain.

I tried but it doesn't work.
I dont have DSN adblocking. I have to wait 3 hours?

**Comment by BlazDT** [comment]
Please manually add the rules which you can find in the commit.

**Comment by Zardangus** [comment]
> Please manually add the rules which you can find in the commit.

I did it, as you asked me to do in your MP but it doesn't work.

I tried with Chrome and wiki.
![Screenshot_20210109_175745_com android chrome](https://user-images.githubusercontent.com/67057008/104103988-8c307700-52a5-11eb-872d-0d539757df91.jpg)

**Comment by BlazDT** [comment]
Please try this rule in user filter:

`ebookdz.com#%#//scriptlet("abort-current-inline-script", "document.createElement", "adblockInfo")`

Looks like something else in your network is blocking pagead2.googlesyndication.com/pagead/js/adsbygoogle.js then.

**Comment by Zardangus** [comment]
> Please try this rule in user filter:
> 
> `ebookdz.com#%#//scriptlet("abort-current-inline-script", "document.createElement", "adblockInfo")`
> 
> Looks like something else in your network is blocking pagead2.googlesyndication.com/pagead/js/adsbygoogle.js then.
> 
> In case someone wants to see the adblock script which only shows when logged in:
> 
> ```
> !function(){function f(){var a=document.createElement("div");a.id="kamujahat";a.innerHTML='<div class="inner"> <div class="header"><h2>&#1578;&#1605; &#1575;&#1604;&#1603;&#1588;&#1601; &#1593;&#1606; &#1605;&#1575;&#1606;&#1593; &#1575;&#1604;&#1573;&#1593;&#1604;&#1575;&#1606;&#1575;&#1578; ! &#9940; </h2></div> <div class="isi">  <div class="tutorial"><div class="adblockInfo__container"><div class="adblockInfo__cover"><img class="adblockInfo__cover__img" src="https://www.icone-png.com/png/52/52335.png"/></div><h3 class="adblockInfo__title">Bloqueur de publicite active  !!!!</h3><p class="adblockInfo__text">Veuillez desactiver votre bloqueur de publicite sur ce site et actualisez la page</p><a href="http://www.ebookdz.com/index.php" rel="nofollow" ><span style="color: darkslategray;"><span style="display : inline-block; font-weight:bold ;font-size: 1rem; line-height: 1rem ; padding: 1rem !important;background-color:#0099CC ; border : 1px solid #0099CC; border-radius: 5px">Veuillez cliquer ici apres avoir desactive votre bloqueur de publicité sur ce site.</span></span></a></div><div id="don"><img src="https://www.animatedimages.org/data/media/1096/animated-click-here-sign-and-button-image-0014.gif" alt=""><a href="https://don-desactive.netlify.app/"  target="_blank">les pubs vous ennuient ? Cliquez ici pour faire un don et avoir une navigation sans pub </a><img src="https://www.animatedimages.org/data/media/1096/animated-click-here-sign-and-button-image-0019.gif" alt=""></div></div> </div>';
> > document.body.append(a);document.body.style.overflow="hidden";var b=a.querySelectorAll("button");a.querySelector(".close");var d=a.querySelectorAll(".tutorial > div");for(a=0;a<b.length;a++)b[a].addEventListener("click",function(a){a.preventDefault();a=this.getAttribute("class").split(" ")[0];for(var c=0;c<d.length;c++)d[c].classList.remove("active"),b[c].classList.remove("active");b[a-1].classList.add("active");d[a-1].classList.add("active")})}var b=document.createElement("script");b.type="text/javascript";
> > b.async=!0;b.src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js";b.onerror=function(){f();window.adblock=!0};var e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(b,e)}();
> ```

Ohhhh yesssss! It works 🤩😍🤩

Thank you ! Very good job ! Thanks !

How to Know what is the anything else on my network is  blocking something?

**Comment by BlazDT** [comment]
When you open AdGuard for Android, open the settings and then "DNS Filtering". If it is set to "On" then we likely have the culprit.
Else some other person on your private network may have installed a custom DNS server on the router or may have installed pi-hole, AdGuard Home or different appliances to block ads on network level.

**Comment by Zardangus** [comment]
> I am glad it works with the #%# rule I posted now :)
> 
> When you open AdGuard for Android, open the settings and then "DNS Filtering". If it is set to "On" then we likely have the culprit.
> Else some other person on your private network may have installed a custom DNS server on the router or may have installed pi-hole, AdGuard Home or different appliances to block ads on network level.
> 
> Do not forget to change your password there (though I already forgot it).

DSN is off in adguard. It is Better to turn it on ?
And When I turn htpps blocking on, Firefox doesn't work. I tried to install the Firefox certificate but it is very hard for me with lot of rules... Is there a easy way to do ? Should I turn HTTPS blocking off?

**Comment by BlazDT** [comment]
Imho better to not turn it on. I personally do not use FireFox, so cannot say something for it.

**Comment by Zardangus** [comment]
> Imho better to not turn it on. I personally do not use FireFox, so cannot say something for it.

May i Know which browser do you use? I will use the same. 🤩

**Comment by BlazDT** [comment]
Chrome.

**Comment by Zardangus** [comment]
> Chrome.

OK, thank you 🙏😁
