### ISSUE TITLE
Incorrect blocking on http://freerutor.org/

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7183]
***Description***:  http://freerutor.org/
Adguard blocks the needed images along with ads.
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![default](https://user-images.githubusercontent.com/32528702/31857106-927799ac-b6dd-11e7-99cb-e417fea9bb59.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![screen shot 2017-10-22 at 4 08 27 am](https://user-images.githubusercontent.com/32528702/31857154-d4f72fbc-b6de-11e7-8196-8f23e1697bed.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | Windows, MacOs as well
Browser:                            | Chrome
AdGuard version:                    | 6.1 / 1.5.0
Filters enabled:                    | ?
Helpdesk ID (if exists):            | 1641358

**Comment by Alex-302** [comment]
Fixed.
