### ISSUE TITLE
123Movies Inspect Element issue

### ISSUE THREAD

**Issue by 123movies707** [AdguardTeam/AdguardFilters#71836]
Hello, 
When I want to check my embedded video codes on my website but when I try to check them by Inspect Element i never shows any code. 

123Movies is an free Movies and TV Shows streaming platform like FMovies, GoMovies and GoStream. Now you can play online movies and tv shows.

Website: [123movies](https://123moviesfd.net)

**Comment by BarhamBasha** [comment]
@123movies707 The aforementioned link points to a site that sells program and game accounts, not to stream movies and TV shows.
