### ISSUE TITLE
Problem with blocking ads (ads server TVN on subdomains redcdn.pl).

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/AdguardFilters#7184]
Details about problem : 

I have not typical problem after update Windows 10 to Fall Creators Update. I tried Adguard and Ublock Origin on www.miniminiplus.pl/filmy and www.teletoonplus.pl/filmy and the both have the same problem as extensions for MS Edge. After watching few videos I will see ads video before normal video in player. This ads have 30 s and I know, they are from redcdn.pl subdomain.

System Windows 10 FCU 1709
MS Edge + Adguard Extension
Filters all (without usuable ads, reek and adblock/ublock protector).

**Comment by seba2282** [comment]
@AdamWr Can you help?

**Comment by AdamWr** [comment]
@seba2282 tak się dzieje tylko w Edge, prawda?
Jeśli się nie mylę, to wygląda na to, że z jakiegoś powodu `media` nie są blokowane (przynajmniej na stronach korzystających z odtwarzacza TVNu).
Mógłbyś sprawdzić tę regułę?
`||redcdn.pl/*Adserver/*.mp4$media,empty,important`

**Comment by seba2282** [comment]
Sprawdzę, jak będę na komputerze. Przy okazji, masz reguły, aby zablokować te reklamy z nc+ i itp na wspomnianych stronach? Dodam jeszcze, że mobilny AG android z DNS pomija redcdn, ale ręcznie musiałem dodać reguły, które rozwiazaly moje problemy w wątku "question about teletoonplus.pl". Z kolei po ostatniej aktualizacji ublock origin dla Edge, problem jakby z redcdn zniknął. Przepraszam, że tyle piszę, ale może ta informacja ułatwi pracę nie tylko tobie, ale też innym deweloperom. :)

**Comment by seba2282** [comment]
@AdamWr Ta reguła pomogła, jak na razie. Nie wiem co się stało, ale nie tylko Edge ma problem, ale też na FF Android z AG miałem ten sam problem (jako rozszerzenie). To wygląda tak, jakby ktoś zdjął celowo tak ważną regułę. Teraz w historii filtrowania widzę zablokowano redcdn (filtry użytkownika).

**Comment by AdamWr** [comment]
Dodałem tę regułę do filtrów.
Tej reguły nigdy nie było w filtrach.
Te reklamy powinny być blokowane przez tę regułę `-adserver/` z angielskiego filtra, ale z jakiegoś powodu to nie działa w Edge, pomimo, że raport filtrowania pokazuje, że to zablokował.

<details><summary>Obrazek</summary>

![image](https://user-images.githubusercontent.com/29142494/32030397-eaa6c88a-b9fa-11e7-8c4c-bbce3d70bc7e.png)

</details>
<br>

Zgłoszę to w odpowiednim miejscu.

**Comment by seba2282** [comment]
@AdamWr A taka jeszcze mała prośba. Spójrz na teletoonplus.pl , tam jest reklamowanie się nc+. To nawet zakrywa opcje na Android z AG apk. Czy mógłbyś dodać jeszcze jakąś regułę, aby to schować? Będę wdzięczny. :)

**Comment by AdamWr** [comment]
Oczywiście, dodałem odpowiednie reguły żeby to ukryć :)

**Comment by seba2282** [comment]
To co powiesz o tym, @AdamWr : 
![screenshot_2017-10-27-08-26-30](https://user-images.githubusercontent.com/16944478/32090678-dca44f04-baf0-11e7-980e-2dffeb196b16.png)

**Comment by AdamWr** [comment]
Nie wiem, może nie zaktualizowałeś filtrów albo aktualizacja nie była jeszcze dostępna.
U mnie z włączonym AdGuardem to jest ukryte.

<details><summary>Obrazek</summary>

![teletoonplus](https://user-images.githubusercontent.com/29142494/32100109-24535e54-bb13-11e7-8c27-b22ae7d8574f.png)

</details>

**Comment by seba2282** [comment]
@AdamWr Ok. Teraz ukryte. Na razie dziękuję za pomoc.
