### ISSUE TITLE
profi-rus.narod.ru - Incorrect blocking

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7185]
http://profi-rus.narod.ru/share42/days.html

<details><summary>Screenshot:</summary>

When Adguard is disabled
![image](https://user-images.githubusercontent.com/27292111/31861315-eff28c3a-b733-11e7-9949-d76486a2fe95.png)

When Adguard is enabled.
![image](https://user-images.githubusercontent.com/27292111/31861324-fc4fc9c0-b733-11e7-9e02-f1b7fc3ae27b.png)

</details><br/>

***Steps to reproduce the problem***:

https://yadi.sk/mail/?hash=L3yqZHktoMhOwggirij%2BcX6a2KxAt6Z2aSSvtJYUwjg%3D&uid=23077022

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Android
Browser:                            | Yandex/Chrome
AdGuard version:                    | 2.10.108
Filters enabled:                    | 1 2 3 4 11
AdGuard mode (Android only):        | VPN
Filtering quality (Android only):   | High-quality
HTTPS filtering (Android only):     | On whitelist
Simplified filters (iOS only)       | On / Off
Helpdesk ID:            | 1642854

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce.

**Comment by sergii333** [comment]
Enable HTTPS!! and non show...

**Comment by Alex-302** [comment]
Можно по-русски, а то не понял, что сказать хотели.

**Comment by sergii333** [comment]
При включении https в настройках, режет этот скрипт <script language="Javascript" src="http://script.pravoslavie.ru/icon.php"></script>
 отсюда http://days.pravoslavie.ru/script/icon.htm 

кэш обязательно чистить и вкл/выкл AG 

при выключении https нормально показывает скрипт...

**Comment by sergii333** [comment]
![screenshot_20171023-200247](https://user-images.githubusercontent.com/33029128/31902484-bd1129ac-b82d-11e7-90c5-a6e17c61d0b9.png)

**Comment by Alex-302** [comment]
Странно. Этот сайт и источник скрипта не используют HTTPS.
Пришлите лог HTTP запросов
https://kb.adguard.com/ru/android/solving-problems/log
Пункт 3 `"Уровень логгирования" переключите в режим "Записывать всё".`  - нужно выбрать `записывать  веб-запросы`(или HTTP)

**Comment by sergii333** [comment]
[adguard_logs_2.10.108_2410_0846.zip](https://github.com/AdguardTeam/AdguardFilters/files/1409693/adguard_logs_2.10.108_2410_0846.zip)

скрипт после выполнения, берёт данные отсюда https://script.pravoslavie.ru/cache_icon/advanced=1.ls

**Comment by Alex-302** [comment]
Вы записали полный лог, а не лог запросов. Но и в нём я не вижу, чтобы  этот скрипт блокировался.
Какой фильтр ломает? Выключите все, проверьте без фильтров, а затем включайте по одному с проверкой.

**Comment by sergii333** [comment]
Выключил все фильтры и все равно не показывает при https

При чем этот показывает http://script.days.ru/calendar.php?advanced=1&life=1&para=1&images=1&vek=1&tipikon=1&bold=1&feofan=1&css=1&encoding=u
а этот нет, странно... http://script.days.ru/icon.php?advanced=1

![screenshot_20171024-152310](https://user-images.githubusercontent.com/33029128/31943117-5196817e-b8d0-11e7-8175-24333d78daec.png)

**Comment by Alex-302** [comment]
> а этот нет, странно... http://script.days.ru/icon.php?advanced=1

его сервер видать отдавать не хочет. Я вижу там закомментированный скрипт
```

  | <!--
-- | --
  | daysi=document;
  | function print_podpis()
  | {
  | daysi.write("Собор преподобных старцев Оптинских. ");
  | }
  | function print_img()
  | {
  | daysi.write("<a href=\'http://days.pravoslavie.ru/Images/im3332.htm\' target=\'_blank\'><IMG border=0 src=\'https://days.pravoslavie.ru/jpg/is3332.jpg\' width=115 height=160 alt=\'Собор преподобных старцев Оптинских. \'></a>");
  | }
  | //-->


```

**Comment by sergii333** [comment]
и во втором скрипте тоже закоментированный...

может дело в кодировке...

**Comment by Alex-302** [comment]
Вряд ли. Текст ведь читаемый. Скорее всего проблема на их сервере.
@zebrum можешь у себя проверить?

**Comment by sergii333** [comment]
Да дело в кодировке, AG кириллицу режет...

убрал в строчке скрипта параметр UTF и не показывает второй скрипи "&encoding=u"

![screenshot_20171024-154147](https://user-images.githubusercontent.com/33029128/31943686-223a1e8e-b8d2-11e7-84de-2a2269bf5f8e.png)

**Comment by Alex-302** [comment]
Попробуйте обновиться до беты.

**Comment by sergii333** [comment]
В бете тоже, если скрипт в кириллицы, то не показывает...

**Comment by Alex-302** [comment]
Может баг. Лучше сюда напишите
https://github.com/AdguardTeam/AdguardForAndroid/issues
Можно по-русски, только вкратце опишите происходящее.
