### ISSUE TITLE
http://www.otohaber.com.tr/ - Ad

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7190]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

I have a problem here. I use safari and Firefox with same filter list. I have still same problem. 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

1 is without Adguard:

![image](https://user-images.githubusercontent.com/31481372/31871194-49b9583e-b7bb-11e7-838d-fd55885c6029.png)

2 is with Adguard:

![image](https://user-images.githubusercontent.com/31481372/31871202-53c3f456-b7bb-11e7-9901-61aec7e90989.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.34.3 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.32 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.83 Enabled=YES
ID=6 Name="German filter" Version=1.0.37.34 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.9.89 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.16 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.68 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | 11.0.3
Browser:                            | Safari
AdGuard version:                    | 1.3.1.82
Simplified filters (iOS only)       | Off
Helpdesk ID (if exists):            | 1638014

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by wang8850** [comment]
on issue

**Comment by AdamWr** [comment]
Fixed.
