### ISSUE TITLE
dns.adguard.com blocking some podcast downloads

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#71931]
https://www.reddit.com/r/Adguard/comments/kr2ko8/dnsadguardcom_blocking_some_podcast_downloads/
https://www.reddit.com/r/pocketcasts/comments/krsiqe/fyi_if_you_use_a_private_dns_server_on_mobile/

Reported by: 1403048, 3130231

**Comment by BlazDT** [comment]
Should be fixed in a few hours.
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/533#issuecomment-757129663
