### ISSUE TITLE
cpu-world.com - Anti Adblock Script

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#7193]
Анти Адблок: http://www.cpu-world.com/Glossary/S/SSE4a.html

<details><summary>Screenshot:</summary>

![cpu-world com](https://user-images.githubusercontent.com/17948007/31885227-6f87aaba-b7f8-11e7-9f69-a18ddd9ea583.png)
</details><br/>

Правило исправления : `||cpu-world.com/cpu_world*.js`

PS:
 Можно писать на счёт добавки cookie-предупреждений в "Фильтр раздражителей"?
<details><summary>Например:</summary>

![cookie](https://user-images.githubusercontent.com/17948007/31884816-1142e1e6-b7f7-11e7-8639-0073c4f042a5.png)
</details><br/>

 И на счёт строки Google-перевода на некоторых сайтах, тоже в раздражители?
<details><summary>Например:</summary>

![google](https://user-images.githubusercontent.com/17948007/31884980-a99da8b8-b7f7-11e7-85ab-008b488a7e13.png)
</details><br/>

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.7.2 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Всё описанное у меня убралось фильтром раздражителей.

**Comment by XX-J** [comment]
На http://www.cpu-world.com бывает появляется не сразу, надо понажимать на разные ссылки из ихней шапки.
 <details><summary>Например:</summary>

![cpu-world](https://user-images.githubusercontent.com/17948007/31917264-3235f77c-b85f-11e7-8cf9-aaf4e2719dd5.png)
</details><br/>

На https://virusscan.jotti.org/ru у меня всегда вылезают cookie, в обоих браузерах. Может, чтобы вылезли у Вас, Вам нужно стереть их cookie? Или они у Вас в пользовательских фильтрах, как были до этого у меня?
 <details><summary>А так, вот что у меня в этом браузере:</summary>

![jotti org](https://user-images.githubusercontent.com/17948007/31917777-0a29ba86-b862-11e7-87ba-c1ff329192ad.PNG)
</details><br/>

___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard v2.7.2 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Повторилось, поправил.
