### ISSUE TITLE
[popup, nsfw] https://www.4tube.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7196]
**Site Sample** | 
----|
https://www.4tube.com/videos/444309/kinky-samanthas-strip-club-scenes?cid=401&SID=noredirect

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Opera Stable x64
AdGuard version:                    | **6.2.431.2165**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Screenshoot
https://i.imgur.com/yGehXmK.png

- Popup redirect after click on play video.

**Comment by Alex-302** [comment]
I can't reproduce.

**Comment by XX-J** [comment]
Перенаправление происходит при первом нажатии на проигрывание или после стирания cookie этого сайта. В редиректе учавствуют два скрипта:
`||4tube.com/c9a215dd11/dynamic_js_en.js`
`||4tube.com/mojon.js`
 Но, при их блокировке, пропадают картинки предпросмотра остальных видео на странице.

**Comment by Alex-302** [comment]
Добавил
```
||4tube.com/mojon.js
||4tube.com/assets/padb-*.js
||4tube.com/*_*.php?z=
```
