### ISSUE TITLE
[nsfw, adsleftover] hdzog.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7197]
**Site Sample** | 
----|
http://www.hdzog.com/videos/2726/club-of-hardcore/?promo=10306

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Opera Stable x64
AdGuard version:                    | **6.2.431.2165**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Screenshoot
![image-20171023-004](https://user-images.githubusercontent.com/9846948/31895699-302bee0c-b812-11e7-92c6-cc1aacba42dc.png)

- adleftover
```
hdzog.com##.player-showtime-two
```

**Comment by AdamWr** [comment]
Fixed.
