### ISSUE TITLE
thepiratebay.org - Rule blocks torrent file list preview

### ISSUE THREAD

**Issue by gagabs** [AdguardTeam/AdguardFilters#7198]
***Description***: 
* **Current behavior**: 

In the torrent details page, the English filter blocks the file list preview, showed when you click in the number of files.

The rule in question is `||thepiratebay.org/*.php?`

* **Expected behavior**: 

A list of files should appear at the bottom of the page. Resolved with:

`@@||thepiratebay.org/ajax_details_filelist.php$xmlhttprequest,first-party`

***Steps to reproduce the problem***:

Go to TBP, open any torrent details page, then click in the number of files.

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Linux
Browser:                            | Firefox
AdGuard version:                    | uBlock
Filters enabled:                    | English Filters

**Comment by gagabs** [comment]
Is:

![image](https://user-images.githubusercontent.com/22453509/31909779-9747880e-b811-11e7-8386-5ec9d9f02cdf.png)

Should be:

![image](https://user-images.githubusercontent.com/22453509/31909816-b17ed42a-b811-11e7-8c5d-b6564b26c8b9.png)

**Comment by Alex-302** [comment]
Nothing
https://thepiratebay.org/torrent/18803275/Malwarebytes_Premium_3.1.2.1733

**Comment by XX-J** [comment]
Подтверждаю.

Например, если пройти по https://thepiratebay.org/torrent/18471471/[LINUX]_[FULL]_[NO-STEAM]_Factorio_0.15.34_(experimental) и нажать на кол-во файлов, то получим пустое поле.

<details><summary>Screenshot:</summary>

![thepiratebay org](https://user-images.githubusercontent.com/17948007/32089308-e0a63634-baf1-11e7-9790-bba04ef765b9.png)
</details><br/>

Чтобы получить список файлов как на картинке выше, нужно добавить в исключения: `@@||thepiratebay.org/ajax_details_filelist.php` . Т.к. его блокирует правило: `||thepiratebay.org/*.php?` из "Английского фильтра".

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.7.2 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Вот так повторилось)
Поправил.
