### ISSUE TITLE
ZippyBus app

### ISSUE THREAD

**Issue by thunderresistant** [AdguardTeam/AdguardFilters#72034]
Misses ads in ZippyBus app.
Android 11

**Comment by krystian3w** [comment]
Maybe ads hidden by encrypt conections similar to YouTube/Facebook/Instagram apps.

**Comment by Alex-302** [comment]
@thunderresistant Please provide screenshot and download link.

**Comment by thunderresistant** [comment]
https://play.google.com/store/apps/details?id=com.zippybus.zippybus&hl=ru&gl=US&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dzippybus&pcampaignid=APPU_1_igL_X8u8M-rLrgS2qoagAQ

![Screenshot_20210113-141909~2](https://user-images.githubusercontent.com/45038010/104464620-3240f180-55c4-11eb-849c-83dec5939e05.png)
![Screenshot_20210113-141917~2](https://user-images.githubusercontent.com/45038010/104464632-35d47880-55c4-11eb-8f4e-fad54f213736.png)

**Comment by thunderresistant** [comment]
Any ideas?

**Comment by Alex-302** [comment]
Looks like Google ad, which must be blocked. 
Please send report from Feedback menu(all settings will be added automatically, just add screenshot, URL and the link of this issue to the comment).

**Comment by thunderresistant** [comment]
So you closed and then reopened?
Cannot reproduce, really???
