### ISSUE TITLE
e-katalog.ru - Ad Leftover

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#7203]
Остатки вверху: http://www.e-katalog.ru/TITAN-TTC-NK45TZ.htm
 <details><summary>ScreenShot:</summary>

![e-katalog](https://user-images.githubusercontent.com/17948007/31939266-7ec4a56c-b8c2-11e7-87fd-b39dbf2f900d.jpg)
</details><br/>

 Правило исправления: `e-katalog.ru##.banner-topline`

PS: Кстати, у кого есть такой кулер или крепления для него - напишите, куплю в С-Пб.

___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard v2.7.2 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
||e-katalog.ru/gb.php?idb_=
```

**Comment by XX-J** [comment]
Не сработало.

**Comment by Alex-302** [comment]
Вчера работало полноценно. Скрыл блок.
