### ISSUE TITLE
digianalytics.airtel.in

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardFilters#72066]
@cantunborn commented on [Mon Jan 11 2021](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/536)

`digianalytics.airtel.in` not blocked while using  https://play.google.com/store/apps/details?id=com.myairtelapp.

**Comment by Alex-302** [comment]
@cantunborn Hi. Cannot register and login.
Please check in user filter if you have AdGuard for Android:
`||digianalytics.airtel.in^`

**Comment by cantunborn** [comment]
Checked already, app works fine with it.
