### ISSUE TITLE
https://forums.overclockers.ru - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7207]
Happens on Android only

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/31988869-3564d8e4-b979-11e7-9193-cf5bea142b50.png)

</details>

### Your environment

* Adguard version: 2.10
* HQ method
* VPN mode
* Filters: English, Russian, Social media, Spyware, German, Mobile ads
* HTTPs filtering: No
* DNS: No

**Comment by Alex-302** [comment]
Нужно либо включить фильтрацию HTTPS, либо добавить исключение в пользовательский фильтр:
```
@@||adservice.google.ru
```
