### ISSUE TITLE
Youtube ad - Mac

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7212]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Initially blocks Youtube video ads. But after about 2 or 3 hours of
Youtube videos, the HTML5 player starts playing video ads before the
actual video begins.

(logs attached in the ticket )

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/32024451-443a93ba-b9e5-11e7-8316-2bb0192b287e.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0
ID=2 Name="English filter" Version=1.1.34.51
ID=3 Name="Spyware filter" Version=1.0.15.7
ID=12 Name="Safari filter" Version=1.0.3.70

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Mac OS X
Browser:                            | Safari
AdGuard version:                    | 1.5.0
Helpdesk ID (if exists):            | 566538

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Ask for URL with ads.

**Comment by iverkhohliad** [comment]
I asked. Will wait for a reply

**Comment by veronikasav** [comment]
https://www.youtube.com/watch?v=d3zTfXvYZ9s
https://www.youtube.com/watch?v=GbGEimY3Mu8
https://www.youtube.com/watch?v=0oYex3dfj8E

**Comment by Alex-302** [comment]
Not reproduced.
@AdamWr please check with UK VPN

**Comment by AdamWr** [comment]
I can't reproduce.
