### ISSUE TITLE
Яндекс Почта - реклама -  Mac OS

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7215]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Программа уже совсем не вырезает рекламу в почте яндекса. ни баннеры слева, ни рекламное место над письмами. 
Cкриншот от 22 октября, сделанный в 17-44, стоит
последняя версия программы и фильтры обновлены. Если обновить фильтры, то
реклама может уйти с главной страницы яндекса. Но она обязательно появится
сразу же в почте, очистка кеша браузера, перезагрузка - не помогают. Фильтр
полезной рекламы отключен. Самостоятельных фильтров для яндекса не
создавалось.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/32032699-2285d5c8-ba11-11e7-8d51-3eee284b5685.png)

![image](https://user-images.githubusercontent.com/31481372/32032704-2d979636-ba11-11e7-8e67-d653222843ba.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0
ID=2 Name="English filter" Version=1.1.34.3
ID=3 Name="Spyware filter" Version=1.0.15
ID=10 Name="Filter unblocking useful ads" Version=1.0.1
ID=1 Name="Russian filter" Version=1.0.58.51

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Mac OS X 1012
Browser:                            | Safari
AdGuard version:                    | 1.5.0
Helpdesk ID (if exists):            | 1634403

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Юзер пишет 
>  сейчас проблемы нет.
