### ISSUE TITLE
temp-mails.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#72161]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Private mode detectiom
https://www.temp-mails.com/number

[//]: # (Substitute this line with a description of the problem)
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

<img width="543" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/104416158-97b8c200-5573-11eb-93d2-cc0c2b52c29c.PNG">

</details><br/>

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.31
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. Please write steps to reproduce.
Also please check with disabled FF privacy settings.

**Comment by JobcenterTycoon** [comment]
Just open the site in a private tab. I disabled the build in firefox tracking protection but it still happens.

**Comment by Alex-302** [comment]
Fixed.
