### ISSUE TITLE
Nextdoor app - missed ads / sponsored conent

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7217]
Missed ads.

### Steps to reproduce

1. https://play.google.com/store/apps/details?id=com.nextdoor install it
2. Create an account
3. Start browsing

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32039572-015afab0-ba37-11e7-9bbb-7a566fb6b29d.png)

</details>

### Customer ID 1558874
Check the support ticket for logs

### Your environment

Settings | Value
---------- | ----
Adguard version | 2.10.108
Subscriptions | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Mobile Ads filter", "Simplified domain names filter", "Anti-Adblock Killer | Reek"
DNS | On, Norton ConnectSafe
DNS encryption | False
Filtering mode | VPN
Filtering method | HQ
HTTPS filtering, mode | On, Whitelist

**Comment by AdamWr** [comment]
I installed that app, but I can't verify my account, so could you please ask user for HAR file?

**Comment by ashvets-sup** [comment]
sent the user a reminder.

**Comment by Alex-302** [comment]
@ashvets-sup @Bohdan-SUP any news?
