### ISSUE TITLE
https://www.bccard.com and https://local.gosi.go.kr - not accessible with the HTTPS filtering enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7221]
Can't reach https://www.bccard.com and https://local.gosi.go.kr when the HTTPS filtering is on. Reproduced on Mac, originally reported with Android app.

### Expected behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32049804-1f310d70-ba57-11e7-9029-147735791b60.png)

</details>

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32049780-05c5cf24-ba57-11e7-921f-454643c0e9de.png)

</details>

### Your environment

* Adguard version: AdGuard for Mac 1.5.0
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off
* HTTPS: ON

**Comment by Alex-302** [comment]
It is not caused by filters.
Filed a bugs in app's repositories.

**Comment by Alex-302** [comment]
Another one site:
https://tensor.ru/
