### ISSUE TITLE
http://mobiltelefon.ru/ - leftovers

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7222]
See here: http://mobiltelefon.ru/post_1509009623.html

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32050797-cfbab940-ba5a-11e7-97d8-cf6e979a76c7.png)

</details>

### Your environment

* Adguard version: 1.3.1 for iOS
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off
* Optimized filters: Off

**Comment by Alex-302** [comment]
Поправил, но не для iOS, т.к. не поддерживает CSS правила.
