### ISSUE TITLE
lasvegassun.com - Anti Adblock - Windows

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7224]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

I am being asked to disable AdGuard.
The main page is fine, but once I click on a specific article within the site, I get that annoying request to turn off AdGuard.

https://lasvegassun.com/news/2017/oct/19/jovan-mooring-wants-to-lead-unlv-to-season-to-reme/

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/32072646-f2a79eaa-ba9b-11e7-8411-327a6489ddcd.png)

</details><br/>

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows 7
Browser:                            | Opera
AdGuard version:                    | Opera Extension
Helpdesk ID (if exists):            | 1638714

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by iverkhohliad** [comment]
The user uses Opera extension only. But I have checked on my side, both with extension and with Adoguard app - and I get the Anti Adblock message.

**Comment by Alex-302** [comment]
I can't reproduce in any browser.

**Comment by AdamWr** [comment]
Fixed.
