### ISSUE TITLE
espn.com 

### ISSUE THREAD

**Issue by P0Rtvine** [AdguardTeam/AdguardFilters#72247]
### List the website(s) you're having issues:

`https://www.espn.com/radio/play/_/id/30707260`

### What happens?

tracking image

### Screenshot(s)
<details>
<summary>Screen</summary>

![2021-01-14_144831](https://user-images.githubusercontent.com/57287308/104592873-91ac0980-5677-11eb-8058-4c391dc17fca.png)
</details>

### List Subscriptions you're using:

<details>
<summary>Screen</summary>

![image](https://user-images.githubusercontent.com/57287308/104311922-8ffb0e00-54de-11eb-9ba9-c9217d860aa3.png)
</details>

### Your settings

- OS/version:  Windows 8.1 embedded industry enterprise
- Browser/version:  Google Chrome
- Adblock Extension/version:  uBO 1.32.4

**Comment by Alex-302** [comment]
Blocked.
