### ISSUE TITLE
https://bytescout.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7226]
The site won't scroll unless you turn the protection off.

### Steps to reproduce

1. Go to https://bytescout.com/products/developer/barcodesdk/bytescoutbarcodesdk.html
2. Try to scroll down
3. Disable AdGuard for 30 seconds and try again

### Actual behavior

It won't scroll down

### Your environment

* Adguard version: AdGuard for Mac 1.5.0
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off
* HTTPS filtering: On

**Comment by Alex-302** [comment]
Fixed.
