### ISSUE TITLE
https://meteomodel.pl/BLOG/

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7230]
**Site Sample** | 
----|
https://meteomodel.pl/BLOG/

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.433.2167**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Screenshoot
![image-20171027-004](https://user-images.githubusercontent.com/9846948/32114272-52f6448a-bb43-11e7-8137-8c6d462ad21d.png)

Adblock Detect @AdamWr

**Comment by AdamWr** [comment]
Fixed.
