### ISSUE TITLE
Incorrect blocking on http://xgames-tv.com/

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7231]
http://xgames-tv.com/news/pervye_ocenki_assassin_39_s_creed_origins/2017-10-26-10189

***Description***:
блокирует не только рекламу , исключение в антибанере не помогает .

* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![default](https://user-images.githubusercontent.com/32528702/32121143-00e66898-bb64-11e7-9ca1-bb9653bebf38.png)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![30](https://user-images.githubusercontent.com/32528702/32121160-123880cc-bb64-11e7-9adb-1c57526676f9.png)
</details><br/>

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows, Mac as well
Browser:                            | Yandex, Chrome
Helpdesk ID (if exists):            | 1641358

**Comment by Alex-302** [comment]
Поправил.
