### ISSUE TITLE
iz.ru - Incorrect Blocking

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#7233]
Видео ставится на паузу через пол секунды проигрывания: https://iz.ru/video/embed/662327 (с этой страницы: https://iz.ru/662327/video/golkiper-propustil-penalti-ubezhav-prazdnovat-promakh-sopernika).
Если быстро-быстро нажимать на участок с видео, то создаётся ощущение что видео проигрывается, только с тормозами :)

 Виновник сему "Английский фильтр" и правило `||imasdk.googleapis.com^$third-party`
Если в исключения добавить `@@||imasdk.googleapis.com/js/sdkloader/ima3.js` , то видео проигрывается нормально.

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.7.2 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Добавил.
