### ISSUE TITLE
cloudpengu.in - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7239]
***Site***: https://cloudpengu.in/
***Description***: Adblock detection

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/32134451-074a0c00-bbee-11e7-9691-afe91c512d51.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.433.2167
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
