### ISSUE TITLE
news.mynavi.jp

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardFilters#72416]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

URL: `https://news.mynavi.jp/article/20210116-1647168/`
Placeholders:

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshots:</summary>

![mynavi](https://user-images.githubusercontent.com/58900598/104810311-07120880-5837-11eb-8691-e5901bc5181a.png)

![mynavi1](https://user-images.githubusercontent.com/58900598/104810667-8bfe2180-5839-11eb-8702-6d1ea3eff91d.png)

![mynavi3](https://user-images.githubusercontent.com/58900598/104810626-4e999400-5839-11eb-8faf-05704ba50ef6.png)

</details><br/>

* **Expected behaviour**: 

See Note below.

<details><summary>Screenshot:</summary>

![mynavi2](https://user-images.githubusercontent.com/58900598/104810682-9c160100-5839-11eb-9eaa-5c01a3fa6ebc.png)

</details><br/>

***Steps to reproduce the problem***:

Visit the site.

***System configuration***

**Filters:**

Base, TPL, and Japanese

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Brave 1.18.78
AdGuard version:                       | 3.5.31
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | Disabled
Helpdesk ID (if exists):               | ?

**Note:**
```
news.mynavi.jp##.headerBillboard
news.mynavi.jp##.c-sidePickup
```
can safely be added, but `news.mynavi.jp##.articleList-attention` is arguable. As I disucussed in Slack in past, EasyList started to block `||popin.cc/popin_discovery/`. I still think it should have been stayed in EasyPrivacy. AG Japanese has been blocking popin ads, but the EL filter blocks whole popIn recommends including *non-ads*.
@ameshkov I tend to suggest to exclude the filter from Base. We will sooner or later see user complaints. popin_discovery can still be added to TPL or Annoyances, it just should not be blocked by ad-blocking list. If you agree, `news.mynavi.jp#$#.articleList-attention[style^="min-height"] { min-height: auto !important; }` shall be added instead.

**Comment by ameshkov** [comment]
Yeah, I think it makes sense. @Alex-302 your call.

**Comment by Alex-302** [comment]
@Yuki2718 added 
- the first two rules;
- badfiltered easylist rule and added to TPF  and to JP `news.mynavi.jp#$#.articleList-attention[style^="min-height"] { min-height: auto !important; }`
