### ISSUE TITLE
7tv.de - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7241]
***Site***: https://www.7tv.de/genial-daneben/28-hugo-egon-balder-laedt-ein-die-comedy-arena-mit-den-besten-fragen-ganze-folge
***Description***: Ads before video.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/32134496-c05aa92a-bbee-11e7-92d8-a02163d3ab2c.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.433.2167
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
