### ISSUE TITLE
TCM.com - Search function broken (AdGuard Base filter)

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#72443]
### Affected site:
`https://www.tcm.com/`

### Issue:
The site's search function is broken (never ending loading spinner).

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **AdGuard Base filter**

### Problem rule:
`||i.cdn.turner.com/ads/`

### Blocked script:
`https://i.cdn.turner.com/ads/adfuel/ais/tcm-ais.js`

### Possible fix:
```
- ||i.cdn.turner.com/ads/
+ ||i.cdn.turner.com/ads/$domain=~tcm.com
```

### Temporary fix:
`@@||i.cdn.turner.com/ads/adfuel/ais/tcm-ais.js$domain=tcm.com`

### Other problem filters:
* ~~**Lunar Blocklist by Moonchild** https://repo.palemoon.org/Moonchild/lunarblocklist/issues/16/~~ _(FIXED)_
~~`.com/ads/`~~

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.17.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.27 (XUL)

**Comment by THEtomaso** [comment]
@Alex-302:

> https://github.com/AdguardTeam/AdguardFilters/commit/17bbc6880bdbec372ba408922f4424e54deaa4e4/

Why did you add that whitelisting to the French filter?
It should be in **AdGuard Base filter**!

**Comment by Alex-302** [comment]
Moved.
