### ISSUE TITLE
Annoyance Filter blocking customer service on Rezi

### ISSUE THREAD

**Issue by yokoffing** [AdguardTeam/AdguardFilters#72452]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:  `https://app.rezi.io/dashboard/resumes`
The only way to contact the company is through the Intercom widget (to change payment plans, etc.).  The Annoyances filter is blocking the widget.
* **Current behaviour**:  The filter `||widget.intercom.io^$3p,domain=~intercom.com|~backerclub.co|~quidco.com|~green.energy` blocks the widget on `https://app.rezi.io`. It needs to be added as an exception as a third-party domain.

**In the future**, if they have an alternate way for customers to contact them (especially regarding financial transaction), we can remove it as an exception. But if we don't add it as a third-party exception, less tech-savy users will be left with no way to contact them without completely disabling their content blocking.

[//]: # (Substitute this line with a description of the problem)

![intercom annoyance 2](https://user-images.githubusercontent.com/11689349/104823458-29e0f480-5818-11eb-8515-4d73a5a49659.jpg)

**Comment by BlazDT** [comment]
Added app.rezi.io to list.

**Comment by yokoffing** [comment]
@BlazDT, good news. You can remove `app.rezi.io` as an exception. A user may now go to `https://app.rezi.ai/profile/account` to change their subscription.
