### ISSUE TITLE
viahold.com (adf.ly) - Anti Adblock Script

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7249]
***Site***: http://viahold.com/2rrc
***Description***: Adblock detection

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/32134578-fa7c94c8-bbef-11e7-9e6a-b6361a1e1d21.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.433.2167
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed- https://github.com/AdguardTeam/AdguardFilters/commit/7bca277801b7b8310725f804a5fdb451e5a44202
