### ISSUE TITLE
m.toutiao.com - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7250]
https://m.toutiao.com/?

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/32135744-bb5ba6cc-bc0c-11e7-9b93-6df0917e3148.png)

</details><br/>

***System configuration***

Application version: 1.3.2.108
Device: iPhone
Platform: iOS
OS: 11.0.2

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.96 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.20 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.67 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.11 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.68 Enabled=YES
ID=101 Name="EasyList" Version=1.0.76.40 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.89.7 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.89.43 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.89.32 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.4 Enabled=YES

Helpdesk ID:            1653373

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
What is purpose of these elements?
We can't hide it on iOS, because elemetns have random names.

**Comment by veronikasav** [comment]
Asked about the purpose.

**Comment by ashvets-sup** [comment]
still no reply from user.
