### ISSUE TITLE
https://www.firstonetv.net/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7251]
https://www.firstonetv.net/Live/United-Kingdom/BBC-News-2

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32136005-b9e65770-bc10-11e7-9f5a-4daf8c12f197.png)

</details>

### Your environment

* Adguard version: AdGuard for Mac 1.5.0
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off

**Comment by Alex-302** [comment]
Fixed.
