### ISSUE TITLE
똑똑가계부 - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7252]
Missed ads, the app in question: https://play.google.com/store/apps/details?id=com.dencreak.spbook&hl=ko

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32136541-0db8d650-bc18-11e7-9026-46d4889b8b96.png)

![image](https://user-images.githubusercontent.com/15856304/32136542-147ef2bc-bc18-11e7-9da9-ba05e09a01b2.png)

</details>

### Customer ID 
1607772, check for logs and the filtering log screenshot

### Your environment

Settings | Value
---------- | ----
Adguard version | 2.10.108
Subscriptions | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Japanese filter", "Mobile Ads filter", "Simplified domain names filter", "EasyList China", "Korean Adblock List", "List-KR"
DNS | Off
Filtering mode | VPN
Filtering method | HQ
HTTPS filtering, mode | On, Whitelist

**Comment by Alex-302** [comment]
`"androidVersion" : "7.1.2`
user should to move certificate to system storage.

**Comment by Alex-302** [comment]
Please check this rule
`||graph.facebook.com^$app=com.dencreak.spbook`
Please ask user if this app uses Facebook auth.

**Comment by veronikasav** [comment]
It worked

**Comment by Alex-302** [comment]
> Please ask user if this app uses Facebook auth.

**Comment by Alex-302** [comment]
@veronikasav

**Comment by ashvets-sup** [comment]
no answer from the user, reminder sent.

**Comment by ashvets-sup** [comment]
>The app is an application that does not support Facebook authentication or Facebook login.
There is currently no sign of advertisement in switching lte and WIFI. 
Later, I will contact you if this symtoms are appear future updates after that app update. 
Developers, very thank you always.

**Comment by Alex-302** [comment]
Ok, added
https://github.com/AdguardTeam/AdguardFilters/issues/7252#issuecomment-340433980
