### ISSUE TITLE
spb.tele2.ru - Incorrect blocking

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7253]
https://spb.tele2.ru/help

On this website support chat doesn't work when Adguard is enabled.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/32136708-0a10839c-bc1b-11e7-8533-84b9c66c4480.png)

</details><br/>

***System configuration***

Information                         | Value
---                                 | ---
Operating system:                   | Android
AdGuard version:                    | 2.10.108
Filters enabled:                    | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter"
AdGuard mode (Android only):        | VPN 
Filtering quality (Android only):   | High-quality
HTTPS filtering (Android only):     | On whitelist
Helpdesk ID:            | 939612

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Подобные виждеты блокируем фильтром раздражителей. Исключение можно было бы сделать только для их собственного виджета, но он сторонний.
Можешь передать юзеру исключение:
```
@@||livetex.ru^$domain=tele2.ru
```
Если этот виджет нужен на всех сайтах, то нужно удалить `$domain=tele2.ru`

**Comment by XX-J** [comment]
Возникла такая-же проблема. Дело в том, что, да, такие виджеты раздражают своим поведением в большинстве случаев, но НЕ с tele2.ru .
 На Tele2.ru этот виджет надо разблокировать, и на это есть пара причин:
1. У них этот виджет не появляется сам собой (не раздражает), а только по требованию (нажатие пользователя кнопки "Написать")
2. Это действенный способ связаться со службой поддержки и решить ту или иную проблему.
___________________________________________________
<details><summary>Screenshot:</summary>

![tele2](https://user-images.githubusercontent.com/17948007/34452675-2a7d481a-ed56-11e7-92fd-e5c0aad4be4f.PNG)
</details><br/>

 Пояснение: При нажатии 1 не появляется 2.

 Виновник: "Фильтр раздражителей"; правило: `||livetex.ru/js/client.js$third-party`
 Думаю, будет достаточно небольшой добавки к правилу: `||livetex.ru/js/client.js$third-party,domain=~tele2.ru` , т.к. мне помогло исключение: `@@||livetex.ru/js/client.js$domain=tele2.ru`
___________________________________________________
Pale Moon v26.5 (Win7) - Adguard v2.8.1 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Одного правила достаточно? Ответ приходит?

**Comment by XX-J** [comment]
Да, чат у меня был полноценен.

**Comment by Alex-302** [comment]
ок
