### ISSUE TITLE
meitui.org - Missed banner

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7254]
http://www.meitui.org/meixiu/201703/13431_3.html

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/32136771-8ef1ff86-bc1c-11e7-901a-9a53be9e1c28.png)

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPhone
Platform: iPhone OS
OS: 9.3.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.14.39 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.17 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.69 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.78.35 Enabled=YES
Annoyances

Ticket ID: 1150440

**Comment by Alex-302** [comment]
Not reproduced with EasyList China. Added
```
/meitui.org\/[a-z][a-z].js/$domain=meitui.org
/meitui.org\/[a-z].js/$domain=meitui.org
```
