### ISSUE TITLE
list `xinggsf` moved

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#72574]
list `xinggsf` moved

https://gitee.com/xinggsf/Adblock-Rule/

https://gitee.com/xinggsf/Adblock-Rule/raw/master/rule.txt

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #419](https://github.com/AdguardTeam/FiltersRegistry/issues/419) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #420](https://github.com/AdguardTeam/FiltersRegistry/issues/420) via [**ZenHub**](https://www.zenhub.com/)
