### ISSUE TITLE
AdGuard is now blocking Gmail Attachments

### ISSUE THREAD

**Issue by XtremeMaC** [AdguardTeam/AdguardFilters#72612]
Hi, don't know the exact date/time issue started, but at least for the past 1-2 days I open an email with Gmail App and it doesn't preview or download any attachments.
Turned off AdGuard. Killed Gmail. Works.

I thought culprit was AdGuard DNS filter, but turns out it's not. Still going thru log to find out. 

Edit: I belive the screenshot below is the culprit. Created an exception and attachments are working now..
![Screenshot_20210119-000446_AdGuard](https://user-images.githubusercontent.com/11046475/104990476-b4794d80-59ea-11eb-86dc-4669d5000149.png)

Edit. Maybe not.. I'll hunt this in the morning... 

FYI

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #3724](https://github.com/AdguardTeam/AdguardForAndroid/issues/3724) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
It seems it is not related to filters. Moved to AdguardForAndroid repository.

**Comment by ScratMan** [comment]
Hello, I'm facing the same issue. Can't read mail attachment, except those downloaded with Adguard off.

**Comment by Alex-302** [comment]
@ScratMan Hi. This is not log file.
Please read here: https://github.com/AdguardTeam/AdguardForAndroid/issues/3724
