### ISSUE TITLE
karsolay.com

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#72634]
https://www.karsolay.com/cilt-sarkmasini-onlemenin-puf-noktalari_6318.html

`###tam-ekran-reklam` means `full screen advert`. Is it OK for the generic rule?

<details><summary>Image</summary>

 
![www karsolay com](https://user-images.githubusercontent.com/74098460/105019231-ec1ddf00-5a56-11eb-898f-f8a93755cc5b.png)

</details>

```

Filters: Base-Tracking Protection-Social-Annoyances-Turkish 
Browser: Chrome 87  
AdGuard Browser Extension 3.5.31 
Win 10

```

**Comment by gork7777** [comment]
Wrong link.
