### ISSUE TITLE
droetker.com.tr

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#72709]
https://www.droetker.com.tr/tr-tr/tarifler/r/bicak-arasi-pide
<details><summary>Image</summary>

 
![www droetker com tr](https://user-images.githubusercontent.com/74098460/105149210-59dc1080-5b14-11eb-8ad3-2bc3e4218d8e.png)

</details>

```

Filters: Base-Tracking Protection-Social-Annoyances-Turkish 
Browser: Chrome 87  
AdGuard Browser Extension 3.5.31 
Win 10

```

**Comment by wout-codes** [comment]
Here is the fix: `droetker.com.tr##.pd-main, .js-pd-main`

**Comment by RadicalNoise** [comment]
@wout-codes Don't write any rules under my reports. Official Adguard members must fix reports.
