### ISSUE TITLE
Not blocking ads in specific apps

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardFilters#72717]
@rtsaab commented on [Tue Jan 19 2021](https://github.com/AdguardTeam/AdguardForiOS/issues/1702)

### Issue Details

- **AdGuard version:** Latest
  
- **Device model and storage size:** iPhone 12 64gb
  
- **Operating system and version:** 14.3
  
- **Browser or App:** Apps by Ketchapp
-(Ex. Dunk Shot)
  
### Expected Behavior
There are pop-ups and panel ads that advertise their other games that should be blocked.

### Actual Behavior
They still show up and are annoying since if you miss tapping the X, the app opens the App Store.

### Screenshots

![CDD3EE51-C73D-485F-982D-5AD766B52A5E](https://user-images.githubusercontent.com/59858550/105075930-66029800-5a58-11eb-879c-44c772ceaf29.jpeg)
![7BACFEEF-5AD4-4267-97B5-64223338C1C2](https://user-images.githubusercontent.com/59858550/105075932-6733c500-5a58-11eb-993a-95ea7d7c3647.jpeg)

### Additional Information
I know these ads aren’t google ads (or other traditional types of ads), however NordVPN and using AirPlane mode blocks them so I believe Ad Guard should be able to block them as well.

**Comment by wout-codes** [comment]
@Alex-302 Ads or self promotions appears sporadically.
