### ISSUE TITLE
1.1.1.1 cloudflare DNS service homepage is blocked

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#72733]
Guys, why your self defense blocked `1.1.1.1` Cloudflare DNS homepage???
![20210120-1611144403-001](https://user-images.githubusercontent.com/9846948/105172734-5b133a80-5b20-11eb-864e-33ec3d53647a.png)
![20210120-1611144429-001](https://user-images.githubusercontent.com/9846948/105172780-69f9ed00-5b20-11eb-9968-9a65b9eeb3b5.png)

![20210120-1611144474-001](https://user-images.githubusercontent.com/9846948/105172870-872ebb80-5b20-11eb-85f6-633172fc35d0.png)

CC @ameshkov @AdamWr  @Alex-302

**Comment by ameshkov** [comment]
Uh,  fixed this: https://reports.adguard.com/en/1.1.1.1/report.html
