### ISSUE TITLE
amd.com - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7274]
***Site***: http://www.amd.com/de
***Description***: Page is blank for a few seconds with AdGuard enabled.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/32142913-b32cca22-bca1-11e7-9d20-65c5437a86b0.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.433.2167
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
I can't reproduce.
