### ISSUE TITLE
ЯндексДирект на rambler.ru

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7282]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

1.
![screenshot-2017-10-29](https://user-images.githubusercontent.com/32528702/32148309-92670df0-bcfd-11e7-86f2-2bdedc853468.png)
2.
![2017-10-27_20-00-58](https://user-images.githubusercontent.com/32528702/32148310-9282fd30-bcfd-11e7-9d73-df3acc97e7dd.png)

</details><br/>

Information                         | Value
---                                 | ---
Operating system:                   | Windows NT 6.1
Browser:                            | ?
AdGuard version:                    | 6.1.331.1732
Filters enabled:                    | 2, 10, 1
Helpdesk ID (if exists):            | 1654099

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
