### ISSUE TITLE
AliExpress.com - Annoyance

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#7284]
Баннер висящий сверху уменьшает полезную площадь экрана: https://www.aliexpress.com
Особенно актуально на мониторах с небольшим разрешением.

<details><summary>Screenshot:</summary>

![aliexpress com](https://user-images.githubusercontent.com/17948007/32159657-6d459cf0-bd5f-11e7-9a55-5878c824b37f.png)
</details><br/>

Правило исправления : `aliexpress.com##.top-banner-container`

___________________________________________________
Mozilla Firefox v50.0.2 (Win7SP1) - Adguard v2.7.2 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Я бы магазины особо не трогал. Этот баннер уберу.
Сайт можно ещё подчистить. Вот мои правила(там и ненужные категории на главной скрываются)
https://gist.githubusercontent.com/Alex-302/6014b2b3df13ce3bd89bbd3fb79b0e6d/raw/13bf6e8bbd402deca7d365eeb3e6921d4e7de010/AG_Custom_rules

**Comment by XX-J** [comment]
`aliexpress.com###ae-top-banner` скрывает только на главной странице сайта.

![ali1](https://user-images.githubusercontent.com/17948007/32600342-604f1960-c550-11e7-89f8-cadac9fa8830.PNG)

 Если перейти на страницу с любым товаром, то баннер становится виден снова. Поэтому лучше скрывать его `aliexpress.com##.top-banner-container` - так более универсально.

![ali2](https://user-images.githubusercontent.com/17948007/32600457-bcc31610-c550-11e7-81a0-4dfee2e051b1.PNG)
<br/>

 Спасибо что поделились своими правилами, есть интересные, например NNM-Club. Почему-бы некоторые не перенести в основные фильтры?

**Comment by Alex-302** [comment]
Заменил.
