### ISSUE TITLE
Incorrect blocking in Zaycev.net music app

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#7286]
@ashvets-sup commented on [Sun Oct 29 2017](https://github.com/AdguardTeam/AdguardForAndroid/issues/1573)

The app in PlayStore:
https://play.google.com/store/apps/details?id=com.p74.player
Там реклама как бы скрыта, но всё равно остаётся активной.

### Steps to reproduce

1. Install app from PlayStore https://play.google.com/store/apps/details?id=com.p74.player
2. Open app
3. notice ad leftover above the Genres tabs (empty area with an "X" button)
4. When tapping the "X" button trying to close the ad,it redirects to the 
<details><summary>following page:</summary>

![screenshot_20171029-154952](https://user-images.githubusercontent.com/32528702/32144545-f2e8fe9e-bcc2-11e7-8ff5-2889d2576a58.png)

</details>

### Actual behavior

<details><summary>Screenshot:</summary>

![screenshot_20171029-102804](https://user-images.githubusercontent.com/32528702/32144494-51ded190-bcc2-11e7-9189-823e0ac104ac.png)

</details>

### Your environment

* Adguard version: 2.10.108
* Adguard filtering mode: VPN
* Device model: Sony E5333
* Operating system and version Android 6.0
* filters: "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter"

**Comment by vozersky** [comment]
@ashvets-sup filters?

**Comment by ashvets-sup** [comment]
added filters list.

**Comment by Alex-302** [comment]
It is impossible to remove this ad leftover even with enabled HTTPS filtering.
