### ISSUE TITLE
Incorrect blocking in Football.ua app

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#7287]
@ashvets-sup commented on [Sun Oct 29 2017](https://github.com/AdguardTeam/AdguardForAndroid/issues/1572)

The app in PlayStore:
https://play.google.com/store/apps/details?id=ua.football

В приложении Football.ua при нажатии на пустое место между новостями перекидывает на страницу с рекламой. 

### Steps to reproduce
1. Install app from PlayStore https://play.google.com/store/apps/details?id=ua.football
2. Open the app
3. right after the app is launched, scroll down the news feed.
4. notice the empty area below the first new article in the feed.

### Actual behavior

<details><summary>Screenshot:</summary>

![screenshot_20171022-112654](https://user-images.githubusercontent.com/32528702/32140818-f4efe316-bc76-11e7-9962-0b01f5ff8232.png)

</details>

### Your environment

* Adguard version: 2.10.108
* Adguard filtering mode: VPN
* Device model: Sony E5333
* Operating system and version  Android 6.0

**Comment by vozersky** [comment]
@ashvets-sup filters?

**Comment by ashvets-sup** [comment]
filters: "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter"

**Comment by Alex-302** [comment]
Added to Mobile filter
```
||football.ua/hnd/Android/*.ashx$replace=/<item\stype="banner">.*?(<\/item>)/
```

**Comment by ashvets-sup** [comment]
issue reproduced again, please check. https://prnt.sc/hbjiwh

**Comment by Alex-302** [comment]
fixed
