### ISSUE TITLE
openload.co - free download option is broken

### ISSUE THREAD

**Issue by THEtomaso** [AdguardTeam/AdguardFilters#7288]
***Description***:
The free download option is broken @ openload.co, because of this filter in Adguard’s Annoyance List:
**openload.co#$##downloadTimer {display:none!important;}**

* **Current behaviour**: 
The countdown timer doesn't appear, and there's no way to download files.

* **Expected behaviour**: 
The countdown timer should appear, and the user should be allowed to download files.

***Steps to reproduce the problem***:
1) Open this link:
https://openload.co/f/kUEfGclsU9o
2) Try to download the file, using the free download alternative

***System configuration***:
Windows 8.1 Pro, x64
Pale Moon v27.5.1, x64
uBlock Origin v1.14.16

**Filter:**
Adguard’s Annoyance List
openload.co#$##downloadTimer {display:none!important;}

**Comment by Alex-302** [comment]
Thanks. Removed.
