### ISSUE TITLE
samsunbulten.com

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#72934]
http://www.samsunbulten.com/

<details><summary>Image</summary>

![www samsunbulten com](https://user-images.githubusercontent.com/74098460/105551158-7003ef80-5d13-11eb-8bd6-5eb02ccd43a9.png)

 
</details>

<details><summary>Image</summary>

 
![www samsunbulten com (1)](https://user-images.githubusercontent.com/74098460/105551195-785c2a80-5d13-11eb-92b3-e4b1ce18a066.png)

</details>

```

Filters: Base-Tracking Protection-Social-Annoyances-Turkish 
Browser: Chrome 88  
AdGuard Browser Extension 3.5.31 
Win 10

```

**Comment by Sergey-Lyapin** [comment]
1760 visitors/month, >30000 needed
