### ISSUE TITLE
Scam german sites and hijacked domains

### ISSUE THREAD

**Issue by Jammie1143** [AdguardTeam/AdguardFilters#72950]
All of these are snakeoils. Should be blocked as whole domain.

1. https://antiker-steintrog.de/blut-abnehmen-ohnmacht/
2. https://augstburger-foto.de/blut-abnehmen-ohnmacht/
3. https://axel-erfurt.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
4. https://baufirma-wegert.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
5. https://beschichtung-beton.de/blut-abnehmen-ohnmacht/
6. https://beschichtung-beton.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
7. https://cadanse.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
8. https://der-weber-freiburg.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
9. https://derkellermann.de/blut-abnehmen-ohnmacht/
10. https://doubletriplechance.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
11. https://dresdner-walzernacht.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
12. https://einfallsinsel.de/blut-abnehmen-ohnmacht/
13. https://einfallsinsel.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
14. https://ekirmes.de/blut-abnehmen-ohnmacht/
15. https://electrixx-lan.de/blut-abnehmen-ohnmacht/
16. https://electrixx-lan.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
17. https://engel-emanuel.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
18. https://erlebnispfadfinder.de/blut-abnehmen-ohnmacht/
19. https://eu-dienstleistungen.de/blut-abnehmen-ohnmacht/
20. https://fahrschule-carstensen.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
21. https://fahrschule-eckert.de/blut-abnehmen-ohnmacht/
22. https://fahrschule-eckert.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
23. https://farbenhof-mayer.de/blut-abnehmen-ohnmacht/
24. https://fellbacher-gebaeudereinigung.de/blut-abnehmen-ohnmacht/
25. https://ferienwohnungen-heidemarie.de/blut-abnehmen-ohnmacht/
26. https://fischerhude-tipps.de/blut-abnehmen-ohnmacht/
27. https://fischerhude-tipps.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
28. https://fsp-metallbau.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
29. https://gebaeudereinigung-wintermeyer.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
30. https://goettinger-blaetter.de/blut-abnehmen-ohnmacht/
31. https://gottesdienste-online.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
32. https://heilpraktiker-pfeiffer.de/blut-abnehmen-ohnmacht/
33. https://heilungdurchliebe.de/blut-abnehmen-ohnmacht/
34. https://heilungdurchliebe.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
35. https://ju-nm.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
36. https://katzen-auetaler-land.de/blut-abnehmen-ohnmacht/
37. https://kegelfreunde-obernburg.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
38. https://kijubobo.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
39. https://konrad-hardes.de/blut-abnehmen-ohnmacht/
40. https://konrad-hardes.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
41. https://kurtisautopflege.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
42. https://lousiana.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
43. https://lsv-hegenscheid.de/blut-abnehmen-ohnmacht/
44. https://mutternatur-shop.de/blut-abnehmen-ohnmacht/
45. https://mv-adp-pflege.de/blut-abnehmen-ohnmacht/
46. https://next-architecture.de/blut-abnehmen-ohnmacht/
47. https://nordfriesland-datenbank.de/blut-abnehmen-ohnmacht/
48. https://olympia-bewegt-alle.de/blut-abnehmen-ohnmacht/
49. https://raidrush.info/frage/warum-ohnmacht-fallen-blutabnehmen/
50. https://restaurant-resi.de/blut-abnehmen-ohnmacht/
51. https://restaurant-resi.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
52. https://rudis-kuenstlerwerkstatt.de/blut-abnehmen-ohnmacht/
53. https://schaarschmidt-ahr.de/blut-abnehmen-ohnmacht/
54. https://schaarschmidt-ahr.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
55. https://sehnsucht-limited.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
56. https://simonis-serviceagentur.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
57. https://socken-fuer-fast-nichts.de/blut-abnehmen-ohnmacht/
58. https://socken-fuer-fast-nichts.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
59. https://tattoomesse-wuerzburg.de/blut-abnehmen-ohnmacht/
60. https://tattoomesse-wuerzburg.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
61. https://thewoodennerd.de/blut-abnehmen-ohnmacht/
62. https://thom-blog.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
63. https://tierkinesiologieundco.de/blut-abnehmen-ohnmacht/
64. https://tierkinesiologieundco.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
65. https://titus-reinmuth.de/blut-abnehmen-ohnmacht/
66. https://tr-ex.me/übersetzung/deutsch-spanisch/ich+in+ohnmacht+falle
67. https://trebbinevent.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
68. https://tui-vital.de/blut-abnehmen-ohnmacht/
69. https://ubwestermann.de/blut-abnehmen-ohnmacht/
70. https://ubwestermann.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
71. https://uranische-astrologie.de/blut-abnehmen-ohnmacht/
72. https://uranische-astrologie.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
73. https://veldenzeraufgebot1462.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
74. https://veltenfranzjakoby.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
75. https://waatched.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
76. https://wasserschadenrheinmain24.de/blut-abnehmen-ohnmacht/
77. https://winterberger-blitz.de/blut-abnehmen-ohnmacht/
78. https://winterberger-blitz.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
79. https://www.aerztepfusch-psychiatrie.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
80. https://www.bioregional-berlin.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
81. https://www.cdu-coswig-anhalt.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
82. https://www.galerie-schneider-sato.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
83. https://www.heikosohn.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
84. https://www.igem-hannover.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
85. https://z-classic-cars.de/blut-abnehmen-ohnmacht/
86. https://zahnarzt-neuweiler.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
87. https://zvk-sachsen-anhalt.de/nach-blut-abnehmen-in-ohnmacht-gefallen/
88. antiker-steintrog.de
89. augstburger-foto.de
90. axel-erfurt.de
91. baufirma-wegert.de
92. beschichtung-beton.de
93. cadanse.de
94. der-weber-freiburg.de
95. derkellermann.de
96. doubletriplechance.de
97. dresdner-walzernacht.de
98. einfallsinsel.de
99. ekirmes.de
100. electrixx-lan.de
101. engel-emanuel.de
102. erlebnispfadfinder.de
103. eu-dienstleistungen.de
104. fahrschule-carstensen.de
105. fahrschule-eckert.de
106. farbenhof-mayer.de
107. fellbacher-gebaeudereinigung.de
108. ferienwohnungen-heidemarie.de
109. fischerhude-tipps.de
110. fsp-metallbau.de
111. gebaeudereinigung-wintermeyer.de
112. goettinger-blaetter.de
113. gottesdienste-online.de
114. heilpraktiker-pfeiffer.de
115. heilungdurchliebe.de
116. ju-nm.de
117. katzen-auetaler-land.de
118. kegelfreunde-obernburg.de
119. kijubobo.de
120. konrad-hardes.de
121. kurtisautopflege.de
122. lousiana.de
123. lsv-hegenscheid.de
124. mutternatur-shop.de
125. mv-adp-pflege.de
126. next-architecture.de
127. nordfriesland-datenbank.de
128. olympia-bewegt-alle.de
129. raidrush.info
130. restaurant-resi.de
131. rudis-kuenstlerwerkstatt.de
132. schaarschmidt-ahr.de
133. sehnsucht-limited.de
134. simonis-serviceagentur.de
135. socken-fuer-fast-nichts.de
136. tattoomesse-wuerzburg.de
137. thewoodennerd.de
138. thom-blog.de
139. tierkinesiologieundco.de
140. titus-reinmuth.de
141. tr-ex.me
142. trebbinevent.de
143. tui-vital.de
144. ubwestermann.de
145. uranische-astrologie.de
146. veldenzeraufgebot1462.de
147. veltenfranzjakoby.de
148. waatched.de
149. wasserschadenrheinmain24.de
150. winterberger-blitz.de
151. www.aerztepfusch-psychiatrie.de
152. www.bioregional-berlin.de
153. www.cdu-coswig-anhalt.de
154. www.galerie-schneider-sato.de
155. www.heikosohn.de
156. www.igem-hannover.de
157. z-classic-cars.de
158. zahnarzt-neuweiler.de
159. zvk-sachsen-anhalt.de

**Comment by wout-codes** [comment]
@lolka4toli

**Comment by DandelionSprout** [comment]
On paper, these two entries could've fixed the problem:
```
/blut-abnehmen-$doc
/nach-blut-abnehmen-$doc
```

But at least I would've needed more details on what type of snakeoil (presumably the "Fake health product" meaning) scams they are. I'm less sure what the AdGuard team's criteria for this are.

**Comment by lolka4toli** [comment]
Blocked.
