### ISSUE TITLE
mobil.blocket.se - Incorrect blocking

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardFilters#7295]
https://mobil.blocket.se/newad.html
The page doesn't load at all, it says the URL is blocked by a content blocker:
When AdGuard is disabled, the page loads just fine.

### Actual behavior

<details><summary>Screenshot:</summary>

![image1](https://user-images.githubusercontent.com/32528702/32148050-87910c40-bcf9-11e7-8fc8-a0c71bb154ac.png)

</details>

### Your environment

* Device model and storage size: iPhone
AdGuard version:    1.3.1.82
* Operating system and version: 10.3.2
* Browser Safari
Filters enabled:   2,3, 14, 6, 12, 207, 211, 225, 209

original: https://github.com/AdguardTeam/AdguardForiOS/issues/508

**Comment by zebrum** [comment]
can not reproduce  on iOS 10.3.3 and AdGuard 1.3.1.82

**Comment by Superkloton** [comment]
Page is https://mobil.blocket.se/newad.html, not https://mobil.blocket.se. Problem might be the word "newad" it the URL but this is a page were you can lay out your own ads like on eBay.

The page can be reached from the start page (blocket.se) by clicking on the blue "Lägg in annons" (add advertisement) in the top bar.

**Comment by Alex-302** [comment]
Added
```
@@||mobil.blocket.se/newad.html
```
@Superkloton is it only one issue?

**Comment by Superkloton** [comment]
For this site, this was the only problem, yes. Thanks!

**Comment by Alex-302** [comment]
ok
