### ISSUE TITLE
Missed ads in ES File Explorer File Manager app

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7296]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

Application in PlayStore:
https://play.google.com/store/apps/details?id=com.estrongs.android.pop

### Steps to reproduce
1. Install app from PlayStore
2. Open the app
3. Click "Logger" icon ("журнал" )
4. scroll down

### Actual behavior

<details><summary>Screenshot:</summary>

1. 
![screenshot_20171022-112901](https://user-images.githubusercontent.com/32528702/32179807-01ff0cd0-bd99-11e7-9f64-7c47980c55d1.png)

2. 
![screenshot_20171022-112733](https://user-images.githubusercontent.com/32528702/32179821-092e579a-bd99-11e7-9a77-c79ae80296e1.png)

3. (screenshot from another device, issue reproduced)
![screenshot_20171030-172414](https://user-images.githubusercontent.com/32528702/32179834-11ba5954-bd99-11e7-91f5-8ec5543defad.png)

</details>

### Your environment

* Adguard version: 2.10.108
* Adguard filtering mode: VPN
* Device model: Sony E5333
* Operating system and version  Android 6.0
filters: "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter"

**Comment by Alex-302** [comment]
It is their own self promo. It seems that resources are built in the app.
Please ask for HAR file(stop the app and clear cache before this).

**Comment by veronikasav** [comment]
Asked for HAR file again.

**Comment by ashvets-sup** [comment]
The HAR file submitted by the customer:
[1543367.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1464548/1543367.har.zip)

**Comment by Alex-302** [comment]
It seems that ad is builtin to the app.
