### ISSUE TITLE
CricBuzz iOS app

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardFilters#7297]
https://itunes.apple.com/hk/app/cricbuzz-cricket-scores-news/id360466413?l=en&mt=8

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://uploads.adguard.com/vbagirov7sbnm.png)
</details><br/>

**Filters:**

not relevant

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system version (Android/iOS) | iOS
Browser:                               | not relevant
AdGuard version:                       | 1.3.2
Filters enabled:                       | not relevant
Simplified filters (iOS only)          | Off
AdGuard DNS:                           |  Default 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added to mobile filter:
```
||adops.cricbuzz.com^
```

**Comment by vbagirov** [comment]
Ads are still present in the same palce.

**Comment by Alex-302** [comment]
Fixed.
