### ISSUE TITLE
muzikotek.com.tr

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#73026]
https://muzikotek.com.tr/tr/banka/haber/muz074-sci-fi-elements-bilim-kurgu-elementleri-mama-da

<details><summary>Image</summary>

![muzikotek com tr](https://user-images.githubusercontent.com/74098460/105609532-017a6c80-5dbb-11eb-8efc-3e8c9e5edf62.png)

 
</details>

```

Filters: Base-Tracking Protection-Social-Annoyances-Turkish 
Browser: Chrome 88  
AdGuard Browser Extension 3.5.31 
Win 10

```

**Comment by Sergey-Lyapin** [comment]
Too few visitors (6 660/month)
Please add to user rules `muzikotek.com.tr##.sharebuttons`
