### ISSUE TITLE
youtube.com - Ad

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7305]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Ads are always displayed all over YouTube. That doesn’t happen in the
desktop versions.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/32202654-ded3edd6-bde6-11e7-995c-4e9f9eacd054.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES

ID=2 Name="English filter" Version=1.1.34.6 Enabled=YES

ID=3 Name="Spyware filter" Version=1.0.15.1 Enabled=YES

ID=4 Name="Social media filter" Version=1.0.24.32 Enabled=YES

ID=12 Name="Safari filter" Version=1.0.3.68 Enabled=YES

ID=207 Name="Adblock Warning Removal List" Version=1.0.89.55 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Device: | iPhone
Operating system:                      | 11.0.3
AdGuard version:                       | 1.3.2.108
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None 
Helpdesk ID (if exists):               | 1652088

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
It seems that it is related to this issue - https://github.com/AdguardTeam/AdguardFilters/issues/7228
Could you please ask user to update filters and check?

**Comment by Alex-302** [comment]
It is impossible to hide it on iOS.
For Android this rule works
```
m.youtube.com###koya_child_5 > div._mdnb > div._mab > div[id^="koya_child_"]:has(a[href^="/watch?v="] > span > span:contains(/AD|Реклама/))
```
@AdamWr could you check it on your device with GB VPN?

**Comment by AdamWr** [comment]
It works, but I need to add "REKLAMA" to this rule.

`m.youtube.com###koya_child_5 > div._mdnb > div._mab > div[id^="koya_child_"]:has(a[href^="/watch?v="] > span > span:contains(/AD|Реклама|REKLAMA/))`

**Comment by iverkhohliad** [comment]
I contacted the user. Waiting for the reply
