### ISSUE TITLE
www.01net.com - Adblock

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7306]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Video is booked with message « switch off your Adblock 
http://www.01net.com/actualites/freebox-free-mobile-surveillance-des-reseaux-quand-xavier-niel-se-confie-1284205.html

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/32203631-3d5e07aa-bded-11e7-8107-24f56a47a1c6.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.34.34 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.70 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.89.73 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES
ID=229 Name="I don't care about cookies" Version=1.0.0.20 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Device: | iPad 
Operating system:                      | 11.0.3
AdGuard version:                       | 1.3.2.108
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None 
Helpdesk ID (if exists):               | 1614614

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed.
