### ISSUE TITLE
AdGuard "collides" with the public log-in procedures is by almost everyone in Norway

### ISSUE THREAD

**Issue by tbleken** [AdguardTeam/AdguardFilters#73074]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Problem with Adguard and public log-in system***:
* **AdGuard causes log-infailure**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:  The problem can only be reproduced if you have a legal Norwegian "social security number"

I have already communicated with your support department, and they asked me to create a bug report. 

They also suggested to help me via TeamViewer, which I have accepted.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  Windows 10 64-bit
Operating system version (Android/iOS) | ? Both Pro and Home gives the same error
Browser:                               | Chrome and Edge
AdGuard version:                       | 7.5.3
Filters enabled:                       | ?
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None as far as I know
Stealth mode options (Windows only)    | ? 
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by krystian3w** [comment]
@DandelionSprout are you using "social security number"?

**Comment by tbleken** [comment]
The Norwegian "version" of Social Security Number is called "personnummer". Every Norwegian has one, and it's guaranteed to be unique, meaning that two Norwegians can't have the same.

Unfortunately I am not allowed to share mine, since it's considered as a secret. If I share it, people with bad intentions can cause a lot of problems.

If we have a TeamViewer session, I am willing to expose it under the condition that you can guarantee that it won't be stored in any way, and that it will not be exposed to anyone else.

Tore Bleken

**Comment by krystian3w** [comment]
@DandelionSprout He  compiling the Noroves/Nordic **filter rules** for **AdGuard** / uBlock Origin / AdBlock+ABP.

The only thing I don't know is whether he was born in Norway, because maybe **outlanders** don't get a "personnummer" at all, and then he won't be able to test whether some filter rules spoil the login pages of **banks** / **goverment offices** / "**hospitals**" (medical pages).

In my country we have NIP ./ REGON / PESEL:

https://en.wikipedia.org/wiki/PESEL / https://en.wikipedia.org/wiki/PESEL#Other_identifiers

**Comment by tbleken** [comment]
Yes, I was born in Norway. You need to be a Norwegian citizen to have a "personnummer". You don't have to be born in Norway, but you have to be eligible to get for instance a Norwegian passport. So if you come from another country, you can apply for Norwegian citizenship after having lived in Norway for many years, or if you get asylum her.

**Comment by DandelionSprout** [comment]
I am confused with a capital C here. I presume this is about BankID and not the personnummer itself, but I can't help out without knowing of an example page/site, which lists you are using, **and** which adblocker extension you're using.

**Comment by tbleken** [comment]
DandelionSprout is correct in that it's not about this "personnummer", it's about BankId. BankId uses a combination of Personnummer, a mobile phone number, a mobile app with face recognition (or finger print or a few more options) and a password. Adguard makes the process fail at the point when the mobile app is supposed to be activated. 

The problem happens when I try to log into my bank, into my doctor (pasientsky.no), my government account (altinn.no) and several other sites which uses the same log in procedure.

I have tried several computers and on several networks, and the problem happens always when AdGuard is enabled. Disabling AdGuard stops the problem.

**Comment by DandelionSprout** [comment]
In that case, the most probable cause is that one of the paid versions of AdGuard is having problems with `difi.no` and (specific to PasientSky) `bankidnorge.no` and `bankidapis.no`. Having now added the latter two to the pull request above, I give the green light to its merging.

**Comment by krystian3w** [comment]
You can add a few HTTPS exclusions?

- Go to "Setttings" (in AdGuard)
- Go to "network" in left column
- Go to "HTTPS" filtering in right column
- click into button "Exclusions"
- use the "+" button to add domains:

   ```
   difi.no
   bankidnorge.no
   bankidapis.no
   ```
- save changes and maybe restart filtering on home screen in AdGuard app for Windows.

**Comment by DandelionSprout** [comment]
For AdGuard for Windows 7.5.3's (mostly) Norwegian language setting, krystian3w's filepath would be Innstillinger → Nettverk → HTTPS filtering → Administrer unntak…

**Comment by tbleken** [comment]
Exclusions added, and computer restarted. Unfortunately those changes didn't help...  The problem persists. 

Btw., although I'm Norwegian, I always prefer English language in Windows and in the applications I install. The reason? Usually English versions are released more frequently than Norwegian versions. Plus as a programmer, I do most of my work in English anyway. 😭

**Comment by akmLaVx** [comment]
Issue doesn't look like fixed; customer has reported that the problem persists. Reopening and pinging @DandelionSprout.

**Comment by ameshkov** [comment]
@akmLaVx updating default HTTPS exclusions list requires an app update.

**Comment by akmLaVx** [comment]
They have added the exclusions manually. Didn't help.

**Comment by ameshkov** [comment]
@akmLaVx 
What websites are problematic? Can we repro this on our side?

**Comment by krystian3w** [comment]
> They have added the exclusions manually. Didn't help.

The 2 from 3 domains fixed by manually exceptions from accepted PR.

> What websites are problematic?

`sparebank1.no` - but maybe need retest with upgrade app to beta/alpha channel (lastest https exception list should be embeded).

**Comment by Chinaski1** [comment]
I have added the specified bank domains to the default exclusion list.

@tbleken 
Could you try adding this `sparebank1.no` bank to the allowlist, then open the browser in incognito mode and check if the issue persists?
You can also open the filtering log (AdGuard icon in tray -> Tools -> Filtering log) before you log in to the bank personal account and try to find out which domain is being requested.

**Comment by tbleken** [comment]
These entries were added manually by me earlier:

bankidapis.no
login.sparebank1.no
sparebank1.no/bv

These changes made it possible to log into my bank, and I reported that the issue was fixed. However, at that time I did **not** make any payment.
So the procedure is as follows:
1. I go to https://www.sparebank1.no/nb/bv/privat/innlogging.html
2. Enter my "fødselsnummer"
3. App starts on my phone, which recognizes my face (or a few other options)
4. App accepts my face
5. I enter my personal code
6. Now I am logged into my bank. 
Success so far

Now to make a payment, 
7. I enter data for paying an invoice, with recipients account no., amount and due date.
8. Press "Neste"
9. Caption "Godkjenn betaling", I press "Neste"
10. Check box "Innholdet er ....", meaning that I accept the payment
11. Press "Start signering"
12. Error "BID-2033" happens...

It's this last points 7 to 12 that I didn't test earlier. Sorry for that.

I hope you find a solution.

**Comment by ameshkov** [comment]
Please note that `sparebank1.no/bv` won't exclude anything, you need to add `sparebank1.no`

**Comment by tbleken** [comment]
@ameshkov 
Thanks, removing /bv did the trick. Looking over the earlier entries in this thread, I realize that the /bv was a typo or a misunderstanding. Anyway, it looks like you have succeeded,, and can close this issue.
😊

**Comment by ameshkov** [comment]
Awesome, I am glad we could help!
