### ISSUE TITLE
www.turkiyegazetesi.com.tr

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7308]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

I see grey area when I use Adguard. 
See pictures 

Browser: Firefox 56.0.2

Without Adguard:

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

Without Adguard:

![image](https://user-images.githubusercontent.com/31481372/32207811-1d5efc92-be07-11e7-9837-772decdda4c4.png)

With Adguard

![image](https://user-images.githubusercontent.com/31481372/32207816-254198c0-be07-11e7-9414-fca5e0284f45.png)

</details><br/>

**Filters:**
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.34.75 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.11 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.49 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.20.14 Enabled=YES
ID=6 Name="German filter" Version=1.0.37.53 Enabled=YES
ID=13 Name="Turkish filter" Version=1.0.10.1 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.19 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.72 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | 11.0.3
Browser:  |Firefox 56.0.2
AdGuard version:                       | 1.3.1.82
Simplified filters (iOS only)          |  Off
Helpdesk ID (if exists):               | 1638014

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. Which filter causes it?

**Comment by AdamWr** [comment]
Fixed.
