### ISSUE TITLE
https://www.delfi.lt/ -ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7309]
Missed ads.

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32213297-54c8aee6-be23-11e7-84a3-cc4bf1d4d394.png)

</details>

### Customer ID 
1591247

### Your environment

* Adguard version: AdGuard for Mac 1.5.0
* HTTPS On
* DNS None
 <details><summary>Subscriptions:</summary> 

Subscriptions: FilterId:2 Name: English filter Url: 

- https://filters.adtidy.org/extension/chromium/filters/2.txt
- FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt
- FilterId:4 Name: Social media filter Url: https://filters.adtidy.org/extension/chromium/filters/4.txt
- FilterId:14 Name: Annoyances filter Url: https://filters.adtidy.org/extension/chromium/filters/14.txt
- FilterId:10 Name: Filter unblocking search ads and self-promotion Url: https://filters.adtidy.org/extension/chromium/filters/10.txt
- FilterId:1 Name: Russian filter Url: https://filters.adtidy.org/extension/chromium/filters/1.txt
- FilterId:6 Name: German filter Url: https://filters.adtidy.org/extension/chromium/filters/6.txt
- FilterId:110 Name: EasyList Lithuania Url: http://margevicius.lt/easylistlithuania.txt
- FilterId:114 Name: ROList Url: http://www.zoso.ro/pages/rolist.txt
- FilterId:0 Name: User filter Url: no_url
- FilterId:238 Name: Adblock & uBlock polish filter - Adguard supplement Url: https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/

</details>

**Comment by Alex-302** [comment]
Not reproduced on my end.
@AdamWr please take a look

**Comment by AdamWr** [comment]
Fixed.
