### ISSUE TITLE
ytvideoindir.com

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#73120]
https://www.ytvideoindir.com/

<details><summary>Image</summary>

![ytvideoindir com](https://user-images.githubusercontent.com/74098460/105643598-d4ed5000-5ea1-11eb-8bbc-e26933dd54db.png)

 
</details>

```

Filters: Base-Tracking Protection-Social-Annoyances-Turkish 
Browser: Chrome 88  
AdGuard Browser Extension 3.5.31 
Win 10

```

**Comment by RadicalNoise** [comment]
and `miner` script


<details><summary>Image</summary>

 
![Adsız](https://user-images.githubusercontent.com/74098460/106218168-e1e2aa00-61e7-11eb-9415-cf192663728a.png)


</details>

**Comment by wout-codes** [comment]
What are the problems in this site? Coin Miner and pop-ups right?

**Comment by Alex-302** [comment]
Not miner, just Avira is stupid/paranoid.
It is clean on VirusTotal https://www.virustotal.com/gui/url/56519fbc4cd2e557489d47c9e82ac10345ab729d33af379d883614360216e7dd/detection
