### ISSUE TITLE
gazetesok.com

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#73140]
https://m.gazetesok.com/haber/magazin-merve-oflazin-aracina-saldiri_351614

**Issue** : Missing image

<details><summary>Image</summary>

![github com](https://user-images.githubusercontent.com/74098460/105654576-57403900-5ecf-11eb-912c-1e187c8019c5.png)

 
</details>

<details><summary>Image</summary>

 
![adg](https://user-images.githubusercontent.com/74098460/105654493-2d871200-5ecf-11eb-8543-1a5517f5b4b5.png)

</details>

---

https://m.gazetesok.com/haber/magazin-reklam-teklifi-alan-aleyna-tilki-gozunu-yukseklere-dikti-tarkan-ya-da-ajda-pekkan-oynarsa-dusunurum_351560

<details><summary>Image</summary>

 
![s1](https://user-images.githubusercontent.com/74098460/105655239-beaab880-5ed0-11eb-966b-c108035113a1.png)

</details>

```

Filters: Base-Tracking Protection-Social-Annoyances-Turkish 
Browser: Chrome 88  
AdGuard Browser Extension 3.5.31 
Win 10

```

**Comment by Alex-302** [comment]
This is site's issue.
Every second refresh - with broken image, even without ad blocker.
![image](https://user-images.githubusercontent.com/8361299/106329391-01caaa00-628a-11eb-9ce9-226f6855809b.png)

Added exclusion for that image.
