### ISSUE TITLE
spaces.ru - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7317]
https://spaces.ru/sz/?link_id=1378960

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/32230840-b37c9bbc-be5c-11e7-8e55-f8970dc985bf.png)

</details><br/>

***System configuration***

Application version: 1.3.2.108
Device: iPhone
Platform: iOS
OS: 11.0.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.34.85 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.12 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.54 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.20.18 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.58.99 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.19 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.73 Enabled=YES
ID=101 Name="EasyList" Version=1.0.76.75 Enabled=YES

Helpdesk ID:         1655273

**Comment by Alex-302** [comment]
На iOS не скрыть, т.к. названия элементов генерируются случайным образом.
Поправил для Android.
