### ISSUE TITLE
mtonews.com - Missed pop-up

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7318]
http://mtonews.com/mto-nicki-minaj-firing0shots-cardi-b/

Is it possible to block this pop-up? It appears even with Pro feature enabled and Adguard DNS server.

<details><summary>Screenshot:</summary>

![screen shot 2017-10-31 at 5 01 29 pm](https://user-images.githubusercontent.com/27292111/32231018-2ca80116-be5d-11e7-8ac5-8db6a26481d4.png)

</details><br/>

***System configuration***

Application version: 1.3.2.108
Device: iPhone
Platform: iOS
OS: 11.0.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.34.69 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.12 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.20.17 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.19 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.72 Enabled=YES
ID=15 Name="Simplified domain names filter" Version=1.0.2.64 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.89.98 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES
ID=208 Name="Malware Domains" Version=1.0.89.85 Enabled=YES
ID=210 Name="Spam404" Version=1.0.2.26 Enabled=YES

Helpdesk ID:             1655034

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
It is not ad. The rule for custom filter:
```
||platform.tout.com/live_channel.json
```
