### ISSUE TITLE
m.chinabyte.com - Missed pop-up

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7319]
http://m.chinabyte.com/427/14321927_m.shtml

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/32232613-1b5213a8-be61-11e7-8907-168f5bd97650.png)

</details><br/>

***System configuration***

Application version: 1.3.2.108
Device: iPhone
Platform: iOS
OS: 11.0.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.32.56 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.81 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.23.88 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.9.92 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.67 Enabled=YES
ID=118 Name="EasyPrivacy" Version=1.0.88.44 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.88.79 Enabled=YES
Annoyances

Helpdesk ID:            1655254

**Comment by Alex-302** [comment]
Fixed.
