### ISSUE TITLE
m.news.yandex.ua - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7323]
https://m.news.yandex.ua/yandsearch?lr=143&cl4url=https%3A%2F%2Frealist.online%2Fnews%2Fpervogo-glavu-naftogaza-arestovali&lang=ruuk&stid=A6bnu_SM_PT-P_JQ7moA&rubric=index&from=index

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/32234719-38fad8c2-be66-11e7-94e4-b669b0f2192e.png)

![image](https://user-images.githubusercontent.com/27292111/32234501-aa4bffb6-be65-11e7-8bf3-3ea158b74e11.png)

</details><br/>

***System configuration***

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version  | 6.0.1
Browser:                               | Yandex
AdGuard version:                       | 2.10
Filters enabled:                       | 1 2 3 4 11
AdGuard mode (Android only):           | VPN 
Filtering quality (Android only):      | High-quality 
HTTPS filtering (Android only):        | On (whitelist)
Helpdesk ID:               | 1529202

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Не повторяется. Сертификат подменился на сайте?
