### ISSUE TITLE
Page scrolling lags, A content blocking issue.

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardFilters#73257]
@Adguarduser9 commented on [Sun Jan 24 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/3726)

- [x] I am running adguard v3.6.1
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

I have added and enabled two user rules in content blocking section and as expected they block the mentined contents.  But the issue is that page scrolling lags whenever I scroll through a page in which the contents are blocked. Page scrolling does not happen normally. Page scrolling lags around the area of a page where the contents are blocked and sometimes on the entire page whenever I scroll through the pages.

Here are the rules I added :  
Rule 1: translate.google.com/translate_a/element.js?cb=googleTranslateElementInit
Rule 2:  translate.googleapis.com

I need to block google translate so I added these rules.

Here is a sample URL :  https://www.mathsisfun.com/sets/function.html

Please fix the issue as soon as possible.

- **AdGuard version:**
  v3.6.1

- **Filtering mode:**
  Local VPN

- **Device:**
  Samsung Galaxy A6 plus

- **Operating system and version:**
  Android 10

- **Root access:**
   No

### Expected Behavior

Page scrolling should happen normally just like the other pages in which the page contents are not necessarily blocked.  In this matter the content is 'Google translate'

### Actual Behavior

Page scrolling lags on a page in which the page contents are blocked by user rules.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

---

@Chinaski1 commented on [Mon Jan 25 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/3726#issuecomment-766794880)

Hello there!

Could you please specify which custom rules you have added to the filters?

As these rules are not correct:
- Rule 1: translate.google.com/translate_a/element.js?cb=googleTranslateElementInit
- Rule 2: translate.googleapis.com

Our knowledge base describes the syntax for writing custom rules, you can read it [here](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters)

---

@Adguarduser9 commented on [Mon Jan 25 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/3726#issuecomment-766935917)

> Hello there!
> 
> Could you please specify which custom rules you have added to the filters?
> 
> As these rules are not correct:
> 
> * Rule 1: translate.google.com/translate_a/element.js?cb=googleTranslateElementInit
> * Rule 2: translate.googleapis.com
> 
> Our knowledge base describes the syntax for writing custom rules, you can read it [here](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters)

Could you please suggest me the syntax to block the 'Google translate' thing on websites ?   I have wasted a lot of my valuable time trying to figure it out but I couldn't do that. So could you please ?

Edit  :   I have added this syntax but the result is the same.

||translate.google.com^$~image,~script,~stylesheet

**Comment by slavaleleka** [comment]
I see no difference with or without AdGuard, the scrolling is not really smooth anyway

**Comment by Adguarduser9** [comment]
> I see no difference with or without AdGuard, the scrolling is not really smooth anyway

I am sorry, I think it is the website's problem. I think thread can be closed now. I am really sorry to bother you but before I learned how to add user rules, this problem occurred with the websites which have the element I had to block.
