### ISSUE TITLE
Facebook Pixel tracker

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardFilters#73265]
I cannot get any answer from the support on this matter. 

**Does AG Pro blocks Facebook Pixel?**

As a reminder Facebook Pixel tracker is not related to Facebbok app.
It can be found in any emails or on internet websites not related to FB. It is a technology uses by third parties to track users:

https://developers.facebook.com/docs/facebook-pixel

Application like Airmail does block Facebook Pixel for emails, but I was wondering if AG was doing it in Safari filters or/and DNS level.

Thanks

**Comment by Alex-302** [comment]
We block pixel.facebook.com

**Comment by Quorum75** [comment]
Thanks @Alex-302
