### ISSUE TITLE
http://www.faz.net/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7329]
The site detects ad blockers.

### Steps to reproduce

1. Go to http://www.faz.net/
2. Wait until it's fully loaded

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32266190-10ac3102-beef-11e7-90e2-e3499e91bc27.png)

</details>

### Customer ID 
1655295

### Your environment

* Adguard version: AdGuard for Mac 1.5.0
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off

**Comment by danidoedel** [comment]
You should be aware of this: https://forum.adguard.com/index.php?threads/policy-on-adblock-walls.26022/

**Comment by Alex-302** [comment]
It is paywall
![image](https://user-images.githubusercontent.com/8361299/32266613-b14193ae-bef0-11e7-8182-20a01959b9d9.png)
according to new policy we don't block them
https://forum.adguard.com/index.php?threads/policy-on-adblock-walls.26022/

**Comment by evgeniy-ADG** [comment]
Well, I was not aware of this.
