### ISSUE TITLE
forum.donanimhaber.com

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#73303]
https://forum.donanimhaber.com/forumid_604/tt.htm

**Issue**: Incorrect Blocking

I think this rule should be removed because it also blocks topics that contain important information.
These topics are usually guideline topics on how to fix bugs that occur in the forum. Useful for new users.

`forum.donanimhaber.com##.sabit-konu`

<details><summary>Image</summary>

 
![user-images githubusercontent com](https://user-images.githubusercontent.com/74098460/105927294-c3987500-6054-11eb-8a78-f05d3732d525.png)

</details>

```

Filters: Base-Tracking Protection-Social-Annoyances-Turkish 
Browser: Chrome 88  
AdGuard Browser Extension 3.5.31 
Win 10

```

**Comment by Alex-302** [comment]
Removed that rule.
