### ISSUE TITLE
winaero.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7331]
**Site Sample** | 
----|
https://winaero.com

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.433.2167**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Screenshoot
![20171101-110732-001](https://user-images.githubusercontent.com/9846948/32270118-e16f7196-bef4-11e7-85c4-da86c6ded9b6.png)

**Comment by Alex-302** [comment]
Fixed.
