### ISSUE TITLE
wallhalla.com - Anti-AdBlocker

### ISSUE THREAD

**Issue by vitalkanev** [AdguardTeam/AdguardFilters#7332]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: wallhalla.com shows Anti-AdBlocker message
***Screenshot***: https://screenshots.firefox.com/U1IeN7GC8vaCFm7P/wallhalla.com

***Steps to reproduce the problem***:

1. On the homepage, type something like this in the search flied: `nature`.
2. Scroll down until you see the 'black box' with the content of `PSST!`

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:** English, Russian, Annoyances, German, Spanish-Portuguese, EasyList, RUAdList 

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Linux - Xubuntu Zesty
Browser:                               | Firefox 56
AdGuard version:                       | 2.7.3
Helpdesk ID (if exists):               | `undefined`

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
