### ISSUE TITLE
pikabu.ru

### ISSUE THREAD

**Issue by dtitbd** [AdguardTeam/AdguardFilters#7334]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

Рекламные посты. Разные. Необходимо полистать ленту, попадаются раз в 15-25 постов.

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![screenshot_2017-11-01-22-24-19](https://user-images.githubusercontent.com/17032471/32288169-e695b6a2-bf54-11e7-8506-1584365a7659.png)
![screenshot_2017-11-01-22-30-27](https://user-images.githubusercontent.com/17032471/32288170-e87c5656-bf54-11e7-9697-4a6137037fe7.png)

</details><br/>

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android) | 5.1, 7.0
Browser:                               | Chrome
AdGuard version:                       | 2.10.155 (/108)
Filters enabled:                       | Английсикий фильтр, Фильтр счетчиков и систем аналитики, Фильтр виджетов социальных сетей,  Фильтр раздражителей, Русский фильтр, Экспериментальный фильтр, Фильтр мобильной рекламы
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality 
HTTPS filtering (Android only):        | On (Default) 
AdGuard DNS:                           | None 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Поправил.
