### ISSUE TITLE
Omni.se/NA.se - Missed ad

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7340]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

two Swedish apps I still get a lot
of ads. The apps are NA and Omni.

Please find 3 screenshots.
2 from the app NA.se
1 from Omni.se app.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/32296894-25b595ea-bf56-11e7-99d4-80522d867193.png)

![image](https://user-images.githubusercontent.com/31481372/32296898-2bf293cc-bf56-11e7-9e70-4d6f00c7df75.png)

![image](https://user-images.githubusercontent.com/31481372/32296903-321b6594-bf56-11e7-9c69-5661b6d2697b.png)

</details><br/>

**Filters:**

"English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Mobile Ads filter", "Simplified domain names filter", "Anti-Adblock Killer | Reek", "Fanboy's Swedish"

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android 
Operating system version (Android) | 7.0
AdGuard version:                       | 2.10.108  
AdGuard mode (Android only):           | VPN 
Filtering quality (Android only):      | High-quality 
HTTPS filtering (Android only):        | Off
Helpdesk ID (if exists):               | 1649302

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Please provide download links for the apps.

**Comment by iverkhohliad** [comment]
https://play.google.com/store/apps/details?id=se.promedia.NA&hl=en
https://play.google.com/store/apps/details?id=se.omni&hl=en

**Comment by Alex-302** [comment]
1 - we can't block this ad at the moment.
2 - not reproduced, only builtin ad placeholder.
