### ISSUE TITLE
overclockers.ru - Anti adblock

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7349]
https://www.overclockers.ru/

<details><summary>Screenshot:</summary>

<img width="934" alt="screen shot 2017-11-02 at 4 49 44 am" src="https://user-images.githubusercontent.com/27292111/32307485-4c11857c-bf89-11e7-8413-064da280314d.png">

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPhone
Platform: iOS
OS: 10.3.3
Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.34.93 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.14 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.56 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.20.23 Enabled=YES
ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.20 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.59.2 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.73 Enabled=YES

Helpdesk ID:              1655932

**Comment by Alex-302** [comment]
Добавил в русский фильтр
```
@@||loader.adrelayer.com/load.js$domain=overclockers.ru
```
