### ISSUE TITLE
[enhancement] alleblock.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7351]
Please consider adding AlleBlock rules to Adguard For Windows/Adguard For Android Filters List. 

https://github.com/maciejtarmas/AlleBlock

RAW file:  https://raw.githubusercontent.com/maciejtarmas/AlleBlock/master/alleblock.txt
`AlleBlock - Remove annoying elements from polish e-commerce sites`

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersRegistry #11](https://github.com/AdguardTeam/FiltersRegistry/issues/11) via [**ZenHub**](https://www.zenhub.com/)
