### ISSUE TITLE
CM Locker app - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7352]
Missed ads in t[his app](https://play.google.com/store/apps/details?id=com.cmcm.locker)

### Steps to reproduce

1. Install from here https://play.google.com/store/apps/details?id=com.cmcm.locker
2. Launch the app
3. Lock the phone

### Actual behavior

Ads on the lock screen are not blocked

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32313744-0f664db4-bfad-11e7-94b8-16d7608f2fec.png)

</details>

### Customer ID 
1657230 - please check for logs, hars, and more screenshots with the description in French.

### Your environment

* Adguard version: 2.10.108
* OS: Android 7.0, Samsung SM-G935F
* Filtering mode: VPN
* DNS: On, AdGuard Standard, no encryption
* HTTPS: On, whitelist
* Filtering method: HQ
* Subscriptions: "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "German filter", "French filter", "Japanese filter", "Dutch filter", "Spanish/Portuguese filter", "Turkish filter", "Experimental filter", "Mobile Ads filter", "Simplified domain names filter", "ABPindo", "Bulgarian list", "EasyList China", "EasyList Czech and Slovak", "EasyList Hebrew", "EasyList Italy", "Latvian List", "Liste AR", "Liste FR", "ROList", "void.gr", "ABPVN List", "Adblock-Persian list", "Adblock & uBlock polish filter", "Adblock & uBlock polish cookies filter", "Anti-Adblock Killer | Reek", "Estonian List", "Fanboy's Swedish", "hufilter", "Korean Adblock List", "List-KR", "Juvander's Adblock List for Finland", "Adblock & uBlock polish filter - Adguard supplement"
* DNS: Off
* Optimized filters: Off

**Comment by AdamWr** [comment]
Could you please ask user to check these rules:
`||batmobil.net^$app=com.cmcm.locker`
`||graph.facebook.com^$app=com.cmcm.locker`

**Comment by AdamWr** [comment]
As I understand, these rules fixed issue
Added them.
