### ISSUE TITLE
ipla.tv

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7357]
**Site Sample** | 
----|
https://www.ipla.tv/Ustawienia

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.433.2167**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

![20171102-183855-001](https://user-images.githubusercontent.com/9846948/32341208-2092cf90-bffd-11e7-9c6e-bd4e4c5eeda3.png)

Nie można skutecznie połączyć konta Ipla z Facebook. Odświeża stronę, ale nie odświeża stanu połączenia konta i w sumie nie wiadomo, czy to działa czy nie @AdamWr  możesz proszę sprawdzić?

![20171102-184416-001](https://user-images.githubusercontent.com/9846948/32341468-dab0aac8-bffd-11e7-856f-1874237ce8f7.png)

**Comment by AdamWr** [comment]
Nie wiem, czy dobrze rozumiem problem, ale u mnie po zalogowaniu się przez Facebooka jest informacja o powiązanym koncie.

<details><summary>Screenshot</summary>

![ipla](https://user-images.githubusercontent.com/29142494/32349077-28787cd2-c016-11e7-99c8-4560e764cc15.JPG)

</details>

**Comment by FadeMind** [comment]
NOT A BUG. Muszę napisać do redefine.
