### ISSUE TITLE
http://dieta-prosto.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7361]
Missed ads here: http://dieta-prosto.ru/1839/Tvorozhnyee_maffiny_s_kofejnym_kremom_po_Dyukanu_bez_muki_bez_masla_bez_sahara/

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32364253-7b86aece-c07c-11e7-8c39-6498f3edb07c.png)

</details>

### Customer ID 
917200

### Your environment

* Adguard version: AdGuard for Mac 1.5.0
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off

**Comment by evgeniy-ADG** [comment]
Btw, I could not block it with the Assistant, upon launch it selects some other element before I have a chance to select the one I want to block, then it hangs for a second and gets closed.

**Comment by Alex-302** [comment]
Fixed.
