### ISSUE TITLE
https://www.nu.nl/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7364]
Videos won't play, blocked on both content blocker and the DNS level I guess.

### Steps to reproduce

1. Go to https://www.nu.nl/158654/video/vliegtuigje-maakt-noodlanding-op-colombiaans-vliegveld.html
2. Click on a video
3. Confirm you're ok with their cookies policy
4. The page will reload, a video won't play
5. Whitelist and disabled the DNS - it works now

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32364821-c7fa537a-c07f-11e7-9309-c06662b35b59.png)

</details>

### Expected behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32364822-caa69dea-c07f-11e7-9776-983a8e52e357.png)

</details>

### Customer ID 

1659165

### Your environment

* Adguard version: 1.3.1 for iOS
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: On, Standard
* Optimized filters: Off

**Comment by AdamWr** [comment]
Fixed.

**Comment by AdamWr** [comment]
Fixed.
