### ISSUE TITLE
https://www.abw.by/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7370]
https://www.abw.by/

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32371177-92c3b750-c098-11e7-937f-6730cd76209f.png)

</details>

### Your environment

* Adguard version: AdGuard for Mac 1.5.0
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off

**Comment by Alex-302** [comment]
Fixed.
