### ISSUE TITLE
pre-roll ad videos on idnes.cz 

### ISSUE THREAD

**Issue by kao-was-here** [AdguardTeam/AdguardFilters#7371]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: 
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)
Pre-roll ad appears on idnes.cz. According to AdGuard log, problem is caused by exception rule "@@||idnes.cz$generichide,genericblock"

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image]https://i.imgur.com/xVRe4XU.png
</details><br/>

* **Expected behaviour**: 
Pre-roll ads being blocked. 

![image]https://i.imgur.com/e3szTlV.png
<br/>

***Steps to reproduce the problem***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)
1. Go to https://usti.idnes.cz/zlodej-parkoviste-obchodni-centrum-teplice-otevreny-kufr-auta-pvo-/usti-zpravy.aspx?c=A171101_102650_usti-zpravy_vac2
2. Play the video.
3. Pre-roll ad appears.

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)
English, Social media, Russian, Mobile Ads, EasyList Czech and Slovak.

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 6.0
Browser:                               | Chrome 61.0
AdGuard version:                       | 2.10.108
Filters enabled:                       | English, Social media, Russian, Mobile Ads, EasyList Czech and Slovak.
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On
Simplified filters (iOS only)          | N/A
AdGuard DNS:                           | Off
Stealth mode options (Windows only)    | N/A
Helpdesk ID (if exists):               | N/A

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Yes, problem is caused by `@@||idnes.cz$generichide,genericblock` and this rule is from `EasyList Czech and Slovak`, so unfortunately I can't delete/modify/disable it.

Could you please, check these rules:
`||bbelements.com^$domain=idnes.cz`
`||ibillboard.com^$domain=idnes.cz`
`||gemius.pl^$domain=idnes.cz`
`||googleadservices.com^$domain=idnes.cz`
`||doubleclick.net^$domain=idnes.cz`

**Comment by kao-was-here** [comment]
I thought that the entire point of serving filter lists from Adguard servers was to be able to fix filter lists for compatibility? See comments on https://github.com/AdguardTeam/AdguardForAndroid/issues/13. 

Your workaround works well, thank you! :)

**Comment by Alex-302** [comment]
`@@||idnes.cz$generichide,genericblock`
removed on our side
