### ISSUE TITLE
Add these sites to the scam / fraud list

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdguardFilters#73711]
https://ww.login-caixa.com and parceriacaixa.com.br

*parceriacaixa.com.br redirects to https://ww.login-caixa.com

The sites are trying to get through with the Caixa.gov.br do Brasil bank

(Site used to attempt to steal bank details or credit / debit card falsifying the identity of Caixa Econômica Federal)

**Comment by gork7777** [comment]
@lolka4toli

**Comment by lolka4toli** [comment]
Done.
