### ISSUE TITLE
http://www.yaplakal.com/ - broken links

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7372]
Not sure how to name that properly, but here's an original description:

> Сейчас на сайте http://www.yaplakal.com/ обрезка рекламы работает неверно. При запросе "активных тем" - большинство тем начинают указывать на адрес обрезанной рекламы. Самой рекламы нет, но ссылки - испорчены.

> На одном - ссылка на первую тему (Если нынешний у бывшей мент) - она дает правильную ссылку, на тему.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32372499-bd0168c8-c09d-11e7-83b4-bb67e51c18dd.png)

</details>

-------

> На втором - та же страничка, однако, курсор наведен на четвертую тему (Женщинам, желающим иметь много детей...), и видно, что она ведет на рекламу "Суточно.Ру" - это та самая реклама, которая должна была быть обрезана. 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32372511-cd83e9a0-c09d-11e7-9a54-daca4f42924e.png)

</details>

### Customer ID 
1652073

### Your environment

* Adguard version: 6.1.331.1732, update has been requested
* Windows NT 6.1.7601 Service Pack 1
* Browser - IE
* Subscriptions: English, Russian, German, Japanese, Dutch, Spyware
* DNS: Off
* TDI
* HTTPS on

**Comment by Alex-302** [comment]
Как эти "активные" темы запросить-то?

**Comment by Alex-302** [comment]
У меня не повторилось. Нужна сохранённая страница. Желательно разлогинившись, либо в наш чат запароленным архивом.

**Comment by veronikasav** [comment]
Попросили.

**Comment by ashvets-sup** [comment]
> Некоторое время ошибка не появлялась. 
Однако, сегодня [20.11] она снова появилась - на том же сайте ЯПлакал ссылки на темы после запроса - ведут на рекламы (которые должны были быть вырезаны)

file provided:
[Результаты поиска.zip](https://github.com/AdguardTeam/AdguardFilters/files/1498263/default.zip)

**Comment by Alex-302** [comment]
добавил
```
yaplakal.com###footer > a[href^="//www.yaplakal.com/go/"]
```
