### ISSUE TITLE
blog.notebooksbilliger.de breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#73734]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Article is blocked
`https://blog.notebooksbilliger.de/monitore-das-bedeuten-die-verschiedenen-paneltypen/`
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![104088904-6fc31900-526a-11eb-8585-78c3743449ef](https://user-images.githubusercontent.com/48647394/106397036-c3f58f00-640b-11eb-9a08-a6a2270fae6f.PNG)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![104088905-705baf80-526a-11eb-99c9-9817a6ea823f](https://user-images.githubusercontent.com/48647394/106397038-c657e900-640b-11eb-9489-25d11e4b36fc.PNG)

</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.31
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

The filter `blog.notebooksbilliger.de#@#.category-advertorial` works for me

**Comment by Alex-302** [comment]
Reported to EasyList.
