### ISSUE TITLE
Проверка Авто ГИБДД, VIN, ОСАГО, штрафы, залоги app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7373]
https://play.google.com/store/apps/details?id=ru.bloodsoft.gibddchecker

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32372808-18e32cfc-c09f-11e7-930b-9bd7239fedb4.png)

![image](https://user-images.githubusercontent.com/15856304/32372814-1e36729a-c09f-11e7-934a-0bb6f1a75b88.png)

![image](https://user-images.githubusercontent.com/15856304/32372823-25e40c50-c09f-11e7-8aa8-1616502ff8e9.png)

</details>

### Customer ID 
1474275

### Your environment

Settings | Value
---------- | ----
Adguard version | 2.10.108
Android version | 7.0
Subscriptions | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Experimental filter", "Mobile Ads filter", "Simplified domain names filter", "Anti-Adblock Killer | Reek" 
DNS | Off
Filtering mode | VPN
Filtering method | HQ
HTTPS filtering, mode | On, Whitelist

**Comment by Alex-302** [comment]
> Android version  7.0

нужно сертификат в системное хранилище переносить. Для этого нужен рут доступ.

Передай на проверку:
```
||googleads.g.doubleclick.net^$app=ru.bloodsoft.gibddchecker
```

**Comment by Alex-302** [comment]
@evgeniy-ADG

**Comment by veronikasav** [comment]
Передали.

**Comment by Alex-302** [comment]
@veronikasav нет ответа?
