### ISSUE TITLE
Ads on nashaplaneta.su

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7379]
***Issue URL***: http://nashaplaneta.su/

Ads on both the left-hand and the right-hand side panels of the page.

<details><summary>Screenshot:</summary>

![nashaplaneta- opera1](https://user-images.githubusercontent.com/32528702/32401267-3091a836-c114-11e7-8e8a-53ba65c91676.jpg)

</details><br/>

***System configuration***

Information | value
--- | ---
Platform: | Windows NT 6.1
Adguard version: | 6.1.331.1732
Browser: | Opera
Filters enabled: |  Russian , English. 
Helpdesk ID : | 693528

**Comment by Alex-302** [comment]
fixed
