### ISSUE TITLE
com.vsct.vsc.mobile.horaireetresa.android

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#73831]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

App link: https://play.google.com/store/apps/details?id=com.vsct.vsc.mobile.horaireetresa.android&hl=en&gl=US

* **Current behaviour**: 

App throws an "internet connection error" when protection is on.

<details><summary>Screen recording:</summary>

https://mega.nz/file/9Pwg3TJJ#FV-49ZnZK0gIXY0xHhiHsLavgGceG7emNTkt24__mN8

</details><br/>

***Steps to reproduce the problem***:

1. Launch the app and try to reserve a ticket

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 8
Browser:                               | n/a
AdGuard version:                       | 3.6.1
Filters enabled:                       | "Filtre AdGuard Anti nuisances", "Online Malicious URL Blocklist", "Filtre AdGuard des publicités pour mobile", "Filtre AdGuard Anti espionnage", "Fanboy's Social Blocking List", "Filtre AdGuard pour médias sociaux", "Je ne m'intéresse pas aux cookies", "Filtre AdGuard Français", "Filtre Anglais AdGuard"
AdGuard mode (Android only):           | VPN 
Filtering quality (Android only):      | High-quality 
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | Default DoH
Stealth mode options (Windows only)    | none
Helpdesk ID (if exists):               | 1941291

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by aranud87** [comment]
Hi,

I do 2 screenshot with log, i don't found how export

Thank you

![Screenshot_20210201-230340_AdGuard](https://user-images.githubusercontent.com/2754191/106523875-12755d00-64e2-11eb-9399-fdd6a73eabf8.jpg)

![Screenshot_20210201-230323_AdGuard](https://user-images.githubusercontent.com/2754191/106523869-10ab9980-64e2-11eb-91f1-86a87bd8aae6.jpg)

**Comment by Alex-302** [comment]
@aranud87 Hi. Could you please test when all filters and DNS filtering are disabled, but protection is enabled?

**Comment by aranud87** [comment]
> @aranud87 Hi. Could you please test when all filters and DNS filtering are disabled, but protection is enabled?

Hi,

I do video with disable all and activate Adguard and it is not run as you ask : 
https://mega.nz/file/9TQTVaZa#UHn1bnpGIYwPxANUdAkrM0q-wwjnlANy8u7M6j36fjc

**Comment by Alex-302** [comment]
Great, thanks. It seems AdGuard's bug. I will move this issue to another repository.
Could you please collect debug logs and sent to support@adguard.com?(attach link of the issue to email)
How to collect logs:
https://kb.adguard.com/en/android/solving-problems/log

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/CoreLibs #1407](https://github.com/AdguardTeam/CoreLibs/issues/1407) via [**ZenHub**](https://www.zenhub.com/)
