### ISSUE TITLE
email.elitedangerous.com

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#73964]
email.elitedangerous.com is unreachable when using AdGuard DNS:

```
nslookup email.elitedangerous.com
Server:		176.103.130.130
Address:	176.103.130.130#53

Non-authoritative answer:
Name:	email.elitedangerous.com
Address: 0.0.0.0
```
Is it because of the ||heals.msgfocus.com^ rule from the DNS filter?

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #568](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/568) via [**ZenHub**](https://www.zenhub.com/)
