### ISSUE TITLE
tagesanzeiger.ch - Ad leftover - Incorrect Blocking

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7399]
***Site***: https://www.tagesanzeiger.ch/
***Description***: Video missing and ad leftover.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/32404483-96396cd2-c150-11e7-9622-e499f3b55f73.png)

(https://www.tagesanzeiger.ch/ausland/europa/comeback-des-fantasten/story/26333891):

![image](https://user-images.githubusercontent.com/10995998/32404495-af4aed90-c150-11e7-9bd9-8145662d1296.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.433.2167
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
