### ISSUE TITLE
ouo.press

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#74004]
some popup asking to add the page to calendar. can this be blocked?

![703C1026-5C47-4D88-ADD1-3E59034E3D2E](https://user-images.githubusercontent.com/71462072/106805775-b703b600-662c-11eb-874f-889522b54892.png)

(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://ouo.press/yIqyns)

**Comment by Sergey-Lyapin** [comment]
This is Safari/iOS own popup so AdGuard can not block it.
