### ISSUE TITLE
megaup.net

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#74003]
megaup.net###ics

blocks overlay. it asks to add something to calendar app. think this would be considered an ad maybe?

(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://megaup.net/2h8os/CUSA07842-Jak_X_Combat_Racing_PS4-CAF.pkg)

**Comment by Alex-302** [comment]
I don't see any requests. Please make screenshot.

**Comment by jordanelliott23** [comment]
![B8E37296-972B-4A81-B3F1-BD4E61F0E904](https://user-images.githubusercontent.com/71462072/107089164-c701ce00-67c3-11eb-9811-3cf2c2407e37.png)

probably only appears on iphone

**Comment by Alex-302** [comment]
Reproduced, fixed.
