### ISSUE TITLE
bitcointalk.org - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7404]
***Site***: https://bitcointalk.org/index.php?topic=208506.0
***Description***: Ads

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/32404643-cb68d674-c153-11e7-9c93-d505f58fa72f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.433.2167
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
