### ISSUE TITLE
codingforums.com - Ads

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7405]
***Site***: http://www.codingforums.com/javascript-programming/387394-get-page-scroll-back-forth.html
***Description***: Ads.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/32404651-01bef2a8-c154-11e7-99ed-612ef8a000f1.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.433.2167
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed.
