### ISSUE TITLE
arcor.de - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7412]
https://www.arcor.de/

<details><summary>Screenshot:</summary>

![screen shot 2017-11-04 at 1 52 12 pm](https://user-images.githubusercontent.com/27292111/32405116-8dc40ffa-c167-11e7-8cc4-49489726829b.png)

</details><br/>

***System configuration***

Application version: 1.3.1.82
Device: iPad
Platform: iOS
OS: 11.0.3

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.33.65 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.14.96 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.20 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.19.67 Enabled=YES
ID=6 Name="German filter" Version=1.0.37.28 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.68 Enabled=YES
ID=101 Name="EasyList" Version=1.0.76.39 Enabled=YES
ID=107 Name="EasyList Germany" Version=1.0.64.38 Enabled=YES
Mobile ads
Helpdesk ID:             1647870

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
I can't reproduce on iPad

**Comment by AdamWr** [comment]
I can't reproduce, I guess it was fixed here - https://github.com/AdguardTeam/AdguardFilters/commit/ccd7780321b579a07b3871992b993961fa752ada
