### ISSUE TITLE
twitch.tv app chat stops loading messages

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#7413]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: 
* **Current behaviour**: 

<details><summary>Ticket id 1459260:</summary>

> Чат в приложении Twitch не работает совсем либо с перебоями, т.е. показано, что я подключен, а чат не загружается и мои сообщения тоже никто не видит! Я сразу подумал на Адгуард и это подтвердилось - при отключении защиты всё ок, после включения как и прежде. Пробовал отключать фильтры, оставил только английский и русский, не помогло. 
</details>

<details><summary>Ticket id 1639515:</summary>

> I seem to be having problems with the Twitch app. Did you guys change something within Adguard that may be making Twitch act up? It seems as though something breaks the chat within Twitch. New comments don't load at all. This didn't start until after I updated Adguard and I thought it was Twitch, but there has been no issues reported by Twitch.
</details>

<details><summary>Ticket id 1641468:</summary>

> Having adguard turned on causes to lose connection to the Twitch chat of a channel after roughly 2 minutes.
</details><br/>

App logs were collected in the corresponding tickets. 
Screen recording of the issue: [https://www.youtube.com/watch?v=EJ4oEKa1zpY](https://www.youtube.com/watch?v=EJ4oEKa1zpY)

***System configuration***

**Filters:**
1. "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "Mobile Ads filter" 

2. "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Experimental filter", "Mobile Ads filter", "Simplified domain names filter", "Liste AR", "Anti-Adblock Killer | Reek", "List-KR" 

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android (6.0.1 and 7.1.1) 
AdGuard version:                       | 2.10.108
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | Full
HTTPS filtering (Android only):        | On

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Please check one-by-one
```
@@twitch.tv$urlblock
```
or
```
@@twitch.tv^
```
or
```
@@twitch.tv$urlblock
```

**Comment by vitbortnik** [comment]
Sent to users. Will provide you with their feedback asap.

**Comment by vitbortnik** [comment]
> I tried the user filter rules that were on the open ticket about Adguard breaking Twitch on GitHub and it's still happening. I tried them one by one and each time it was the same result. New comments wouldn't load at all after 1 minute or so.

**Comment by Alex-302** [comment]
Maybe app's bug, or something else.
Does it work without AdGuard?

**Comment by vitbortnik** [comment]
Users say that it works without AdGuard. 
I will keep you updated in case new details come up.

**Comment by vitbortnik** [comment]
> If I use any of the provided rules the chat isn't working at all and yes it is fully working if and only if Adguard is turned off.

**Comment by altokarev** [comment]
Try to add `api.twitch.tv` to HTTPS whitelist. That should help.

**Comment by vitbortnik** [comment]
id 1639515

> So, I added 'api.twitch.tv' in the HTTPS whitelist like someone on the
Github page had said and it seems to have resolved the problem where
Adguard would block comments from coming through when the Twitch app is
filtered through Adguard. I have the Twitch app filtering through Adguard now and the comments are
coming through like they should when I go on the app.

**Comment by vozersky** [comment]
what about ads after whitelisting  ` api.twitch.tv`? all is well?

**Comment by vozersky** [comment]
try `@@||api.twitch.tv^$domain=twitch.tv` instead of HTTPS exclusion

**Comment by Alex-302** [comment]
@vitbortnik

**Comment by vitbortnik** [comment]
Asked id 1639515
