### ISSUE TITLE
Unable to upgrade AVG Cleaner Pro

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7414]
При попытке приобрести версию AVG Cleaner Pro из приложения AVG Cleaner Free происходит
блокировка : 

> Запрос к mobile-campaigns.avast.com был заблокирован рекламным фильтром Adguard. Если вам необходимо перейти по этой ссылке, добавьте домен mobile-campaigns.avast.com в исключения. Заблокировано правилом фильтрации:  ||mobile-campaigns.avast.com^ 

Пользователь внес это в оба исключения (см state), но пишет, что не помогло. Как правильно исключить для com.avg.cleaner;version=4.2.0;system=false ?

ID: 1656714
[state (84).txt](https://github.com/AdguardTeam/AdguardFilters/files/1443316/state.84.txt)

**Comment by Alex-302** [comment]
Не понятно куда он домен добавил и в каком виде.

**Comment by Alex-302** [comment]
У меня переход в гугломаркет работает и без исключений.

**Comment by evgeniy-ADG** [comment]
Я там стейт подргузил, посмотри, там видно, что домен в обычном вайтлисте и в хттпс.

**Comment by Alex-302** [comment]
Попроси проверить без мобильного фильтра. Если поможет, пусть выключит все фильтры и оставит мобильный, потом запишет лог запросов(полный не нужен) с временной отметкой.

**Comment by Alex-302** [comment]
И ещё - ДНС он какой использует?

**Comment by ashvets-sup** [comment]
> проблема решилась на следующий день после обращения, возможно
произошло обновление фильтров.
