### ISSUE TITLE
Verizon Voicemail app is not working

### ISSUE THREAD

**Issue by divisionparzero** [AdguardTeam/AdguardFilters#74140]
Hello.

Recently Adguard started blocking the Verizon voicemail app from reaching its servers. I don't get a lot of calls so I'm not exactly sure how long it started. when I pause adguard it works again. I've whitelisted the app for now but just thought y'all would want to address it. I believe the myverizon app was also affected but I've already whitelisted it and don't feel like testing again.

Thanks!

**Comment by Alex-302** [comment]
Probably filtering bug.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/CoreLibs #1410](https://github.com/AdguardTeam/CoreLibs/issues/1410) via [**ZenHub**](https://www.zenhub.com/)
