### ISSUE TITLE
Transparent weather clock app - missed ads 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7426]
Missed ads in https://play.google.com/store/apps/details?id=com.droid27.transparentclockweather

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32407403-034ca9ac-c191-11e7-9215-90954934e536.png)

![image](https://user-images.githubusercontent.com/15856304/32407405-0ca19d00-c191-11e7-8ea5-4fdae0034ca0.png)

</details>

### Customer ID  920270
Check for logs and har

### Your environment

* Adguard version: 2.10.108
* OS: Android 6
* Subscriptions: "English filter", "Spyware filter", "Social media filter", "Russian filter", "Mobile Ads filter"
* DNS: Off
* VPN or Proxy: VPN
* HTTPS: Whitelist

**Comment by AdamWr** [comment]
I don't see ads in this app on my end (even without AdGuard).
Unfortunately this shared HAR file is not helpful, because it contains only blocked requests.
Could you please ask user to create new HAR file?
