### ISSUE TITLE
https filter does not work for google ad

### ISSUE THREAD

**Issue by KamiyaMinoru** [AdguardTeam/AdguardFilters#74324]
https://play.google.com/store/apps/details?id=com.bloodyluna.TaipeiMetroTimeAndFare

this app use google ad
https flter is turned on
but doesnot work

**Comment by Alex-302** [comment]
@KamiyaMinoru Hi. Please send report using AdGuard feedback menu(all settings will be auto-filled)
https://kb.adguard.com/en/technical-support/reporting-tool#Android
