### ISSUE TITLE
google ad supposed not blocked...

### ISSUE THREAD

**Issue by KamiyaMinoru** [AdguardTeam/AdguardFilters#74321]
https://play.google.com/store/apps/details?id=com.creativetrends.simple.app

I am using this app
and it shows  google ad
I open https filter but it pop up
error msg says this app refuses https filter

and ad are not blocked

**Comment by KamiyaMinoru** [comment]
Also, if I turn on the filter, I can not use it
beacuse it wont allow me to upload picture in messenger etc

**Comment by Alex-302** [comment]
Please read here: https://github.com/AdguardTeam/AdguardFilters/issues/74324
