### ISSUE TITLE
adv.vn.ua

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardFilters#74357]
Helpdesk ID 3187975:

>Есть в распоряжении сайт/домен adv.vn.ua, Ваш блокировщик блокирует все скрипты на сайте. Насколько нашёл информацию в интернете, то данное происходит из за наличия в домене сочетания "adv" поскольку блокировщик считает все скрипты сайта за рекламу.  
Уточните, пожалуйста как можно обойти это? Необходимо чтобы клиенты с Вашим блокировщиком не страдали при заходе на сайт или как-то убрать домен с

**Comment by Alex-302** [comment]
Сообщил в Easylist.
