### ISSUE TITLE
pure-t.ru - Missed ad

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardFilters#7438]
http://www.pure-t.ru

<details><summary>Screenshot:</summary>

<img width="396" alt="screen shot 2017-11-05 at 9 09 08 am" src="https://user-images.githubusercontent.com/27292111/32412714-04f9a6d8-c209-11e7-9ca9-02c696877175.png">

</details><br/>

***System configuration***

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version | 6.0.1
Browser:                               | Chrome
AdGuard version:                       | 2.10
Filters enabled:                       | 1 2 3 4 11
AdGuard mode (Android only):           | VPN 
Filtering quality (Android only):      | High-quality 
HTTPS filtering (Android only):        | On whitelist
Helpdesk ID:               | 1162662

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
ашчув

**Comment by paskardv** [comment]
Здравствуйте, обновил фильтры АГ, почистил кэш - рекламный баннер все равно появляется. Такое ощущение, что подгружается с какого-то "зеркала", т.к. появляться он стал не вначале загрузки страницы, как раньше, а в конце.

**Comment by Alex-302** [comment]
Попробуйте вручную добавить в собственный фильтр
```
pure-t.ru##.mobile-banner > img
```

**Comment by paskardv** [comment]
К сожалению, не помогло - также подгружается в самом конце

**Comment by paskardv** [comment]
Как на скриншоте при создании этой темы -
 "самый простой способ путешествовать в 2 раза дешевле"

**Comment by Alex-302** [comment]
А так?
```
pure-t.ru##.mobile-banner
```
Если не поможет, для пробы выключите все фильтры и проверьте только с отим правилом(или предыдущим).
Есть свои правила, кроме этого?

**Comment by paskardv** [comment]
Удалил все собственные правила, отключил все фильтры - помогает предыдущее правило, баннер пропадает.

Если включить любой из следующих фильтров:
- русский фильтр
- фильтр раздражителей
- фильтр виджетов соцсетей
- фильтр счетчиков и систем аналитики

Баннер снова появляется.

Остальные используемые мной фильтры АГ влияния НЕ оказывают (экспериментальный, фильтр мобильной рекламы, anti ad-block killer), с ними баннер не появляется.

**Comment by Alex-302** [comment]
Странности.
Попробуйте оставить только фильтр аналитики, и добавьте
```
pure-t.ru##.mobile-banner
pure-t.ru#@#img[width="88"][height="31"]
pure-t.ru#@#img[src^="http://c.bigmir.net/"]
pure-t.ru#@#img[src*="counter.yadro.ru"]
pure-t.ru#@#a[href^="https://top.mail.ru/jump"]
pure-t.ru#@#a[href^="https://metrika.yandex.ru/stat/"]
pure-t.ru#@#a[href^="http://www.liveinternet.ru/stat/"]
pure-t.ru#@#a[href^="http://top100.rambler.ru/"]
pure-t.ru#@#a[href^="http://top.mail.ru/jump"]
pure-t.ru#@#a[href^="http://metrika.yandex.ru/stat/"]
pure-t.ru#@#a[href^="http://hitcounter.ru/top/stat.php"]
pure-t.ru#@#a[href^="http://click.hotlog.ru/"]
pure-t.ru#@##top100counter
pure-t.ru#@##ramblerCounter
pure-t.ru#@##qoo-counter
```

**Comment by paskardv** [comment]
К сожалению, баннер остался на месте

**Comment by Alex-302** [comment]
@zebrum можешь у себя на айфоне проверить?

**Comment by Alex-302** [comment]
Понял) Был уверен, что речь про iOS:)
Такое правило скроет
```
pure-t.ru#$#.mobile-banner { position: absolute!important; left: -3000px!important; }
```
добавил

**Comment by paskardv** [comment]
Если включить любой из следующих фильтров:
- фильтр виджетов соцсетей
- фильтр счетчиков и систем аналитики
Баннер снова появляется :(

С остальными используемыми мной фильтрами такого нет.

**Comment by paskardv** [comment]
Спасибо, теперь всё отлично!
