### ISSUE TITLE
Новая пропущенная реклама на Facebook

### ISSUE THREAD

**Issue by jbionic2016** [AdguardTeam/AdguardFilters#74428]
Приветствую.

Очень много пропущенной рекламы наблюдается в последние недели на facebook. Добавляется новая в новых местах. Прикрепляю сегодняшний замеченный пример
https://i114.fastpic.ru/big/2021/0209/72/a413a13f5f1382073c5977991cd18372.jpg

Это в дополнение к моему другому недавнему запросу про рекламу на Фейсбуке:
https://github.com/AdguardTeam/AdGuardExtra/issues/159

С уважением.

===========
Operating system: Windows 10 Home
Browser: Chrome Version  88.0.4324.150 (Official Build) (64-bit)
AdGuard version for Chrome: Version 3.5.31
Filters enabled: AdGuard Base filter, AdGuard Tracking Protection filter, EasyPrivacy, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter
Stealth mode options (Windows only) Enabled
AdGuard Extra 1.0.211

**Comment by Alex-302** [comment]
Скопировал сообщение в Экстру. У меня не повторяется, и фильтрами там не очень удобно блокировать.
