### ISSUE TITLE
blocking third-party authorization header breaks aws console

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardFilters#74518]
@kaznovac commented on [Sat Feb 06 2021](https://github.com/AdguardTeam/AdguardForMac/issues/829)

this is not a bug report, it's an unexpected behaviour (took me some network digging to see what's wrong) that has a workaround (maybe the whitelist should be distributed with application)

### Steps to reproduce
1. turn on the third-party authorization header blocking in stealth mode tracking methods
2. visit some pages in aws console requiring user roles e.g. https://console.aws.amazon.com/codesuite/codestar/projects

### Expected behavior
page opens as expected

### Actual behavior
error message is displayed

### Workaround
whitelist the `console.aws.amazon.com`

**Comment by Alex-302** [comment]
@kaznovac Hi. I cannot reproduce with recently created account.
Which error do you see?
Please check this rule(disables stealth mode only):
`@@||console.aws.amazon.com^$stealth`

**Comment by kaznovac** [comment]
Hi @Alex-302.

i'm getting the 400 bad request on [codestar/projects](https://console.aws.amazon.com/codesuite/codestar/projects) (not all the aws service pages require immediate authentication, this one does) with following exception (see attached image)
```xml
<MissingAuthenticationTokenException>
  <Message>Missing Authentication Token</Message>
</MissingAuthenticationTokenException>
```

<img width="1680" alt="console 400 with stealth filters" src="https://user-images.githubusercontent.com/203604/107766172-5f073680-6d33-11eb-934c-eb64e2510cc4.png">

i've tried the suggested rule, and it didn't work for me - same error;
but you gave me a nudge in the right direction:
`@@||amazonaws.com^$stealth,domain=console.aws.amazon.com`
this rule works and it's less allowing than the default whitelist one (`@@||console.aws.amazon.com^$important,document`)

thanks,
k

**Comment by Alex-302** [comment]
@kaznovac Ok, added your rule.
