### ISSUE TITLE
AdGuard blocking anything with id="cookie" (even when disabled on a site)

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardFilters#74521]
@cal-zone commented on [Sat Feb 06 2021](https://github.com/AdguardTeam/AdguardForMac/issues/828)

### Steps to reproduce

1. Running AdGuard, visit this link: https://book.cakephp.org/4/en/controllers/request-response.html#cookies
2. Near the top of the page, there is a list of links on the right hand side. One says "Cookies" — click it and notice nothing happens.
2. Turn off AdGuard and try again (may take a few force-refresh tries)
3. Section that was not visible with AdGuard running is now visible. Cookies link now works.
4. Inspect Element while AdGuard is running and notice that <div class="section" id="cookies"> has display:none set under User Agent Stylesheet. While element is being inspected, change id to something other than cookies. Notice it shows up in the browser now.
5. Uncheck 'Enabled on this website' on the AdGuard button
6. Visit link again (again, force-refresh and/or waiting some time may be required a few times)
7. Notice that even though AdGuard is not 'Enabled on this website' it is still blocking the content

### Expected behavior

1. AdGuard should not be blocking content just because it has an id of "cookies"
2. {{{ AdGuard should not be blocking anything when 'Enabled on this website' is unchecked }}} **<— I was wrong on this one.**

### Actual behavior

1. AdGuard is blocking content just because it has an id of "cookies"
2. {{{ AdGuard is blocking something when 'Enabled on this website' is unchecked }}}  **<— I was wrong on this one.**

<details><summary>Screenshot:</summary>

<img width="922" alt="AdGuard Bug" src="https://user-images.githubusercontent.com/73723061/107089882-35d72b00-67b4-11eb-8e43-9c38ce939eef.png">
</details>

### Customer ID 

I was unable to find a support link in the application.

### Your environment

* MacOS 11.1 (20C69) — Safari 14.0.2 (16610.3.7.1.9) 

---

@evasilis commented on [Sun Feb 07 2021](https://github.com/AdguardTeam/AdguardForMac/issues/828#issuecomment-774659791)

I am running adguard 2.5.2.942 nightly with macos 11.2. I cannot reproduce this behaviour.

---

@cal-zone commented on [Mon Feb 08 2021](https://github.com/AdguardTeam/AdguardForMac/issues/828#issuecomment-774784832)

Ok, I just went back and noticed that the section in question was showing this time. I still had "Enabled on this website" unchecked.

SO: the second issue turns out to be wrong / moot. Unchecking "Enabled on this website" works as expected.

That still leaves the first issue. It's definitely AdGuard causing it. The only other extension I have is Ghostery Lite, and I disabled that completely for two days now. So that's not it.

Reviewing my AdGuard settings, I'm attaching a screen capture which may be relevant to the issue. I also do have _some_ User Rules set up, but it's a short list — and none are for the site in question. I'm tempted to create another site and add a div with an id="cookies" to see if it triggers there as well.
<img width="988" alt="AdGuard Settings" src="https://user-images.githubusercontent.com/73723061/107162117-edf00980-6955-11eb-8883-aa63492c9137.png">

---

@cal-zone commented on [Mon Feb 08 2021](https://github.com/AdguardTeam/AdguardForMac/issues/828#issuecomment-774785240)

>  adguard 2.5.2.942 nightly 

Huh??

In my AdGuard's About, I see: Version 1.8.10. As far as I know, it's been keeping itself up to date automatically since I first installed it. 

---

@Chinaski1 commented on [Wed Feb 10 2021](https://github.com/AdguardTeam/AdguardForMac/issues/828#issuecomment-776704676)

Hello there!

@cal-zone 

This issue appears to be caused by the use of the **AdGuard Annoyances filter**, try to switch it off and check again.

Please take a look @Alex-302

**Comment by Alex-302** [comment]
@cal-zone Fixed.
