### ISSUE TITLE
ria.ru - anti adblock

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardFilters#746]

**Comment by Alex-302** [comment]
Added
ria.ru##.antiblock

**Comment by Bohdan-SUP** [comment]
Снова появилось:
![screen shot 2016-02-12 at 5 21 52 am](https://cloud.githubusercontent.com/assets/14153331/12998244/de35f508-d149-11e5-8a10-aeddb12ff01b.png)

Также, блокирует колонку с новостями внизу страницы перед комментариями:
![2](https://cloud.githubusercontent.com/assets/14153331/12998256/fe6412f6-d149-11e5-9823-15e3d07f2c00.PNG)

**Comment by Alex-302** [comment]
Сообщения о блокировке не вижу.
Чтоб вернуть "Популярное", нужно добавить исключения:
```
@@||relap.io/api/v6/head.js
@@||relap.io/api/v6/similar_pages.js
@@||amscdn.relap.io^$domain=ria.ru
@@||relap.io/css/api/v6/ria_ru.css$domain=ria.ru
ria.ru##a[href^="https://relap.io/r?"]
```
@ameshkov Стоит добавлять в фильтр?

**Comment by vgavrish** [comment]
@Alex-302 
с фильтрами не до конца правильно показывается раздел "Популярное".
![8f057a29abc24668bfcc23ba3a991060](https://cloud.githubusercontent.com/assets/18548949/15989497/b1559f7a-3080-11e6-8758-0b5d09fb4fd4.png)

**Comment by Alex-302** [comment]
@@||relap.io^$domain=ria.ru
такое поможет точно
