### ISSUE TITLE
Blocked OfficeDepot.com's blue "Check another store" link to show me a pop-up lists.

### ISSUE THREAD

**Issue by antdude** [AdguardTeam/AdguardFilters#7468]
Hello.

Example: https://www.officedepot.com/a/products/440520/HP-96-Black-Ink-Cartridge-C8767WN/
Can't get its "Pick Up In 1 Hour"'s blue "Check another store" link to show me a pop-up list of stores because of:

odcdn.com filter with https://secure.www.odcdn.com/N2109404685/bundles/
static filter /tealeaf.js found in these two subscriptions in UO v1.13.8:
EasyPrivacy
Adguard Spyware Filters (yours)

Thank you in advance. :)

**Comment by Alex-302** [comment]
Hi
It does not work on my end without AdGuard
![image](https://user-images.githubusercontent.com/8361299/32434834-e1b17bf8-c2e7-11e7-9581-1cac55442df3.png)

**Comment by Alex-302** [comment]
@antdude

**Comment by antdude** [comment]
https://www.officedepot.com/a/products/440520/HP-96-Black-Ink-Cartridge-C8767WN/ works for me. :/

**Comment by Alex-302** [comment]
Ok, opened it with US VPN. But I can select "Pick Up In 1 Hour"
Could you describe wrong behavior?

**Comment by antdude** [comment]
Did you click on its blue "Check another store" link? That part doesn't work. It is supposed to show up a pop-up window with gr(e/a)yed out background to show a list of local stores to pick up in person.

**Comment by Alex-302** [comment]
please mark that button on screenshot

**Comment by antdude** [comment]
Here it is:
![screenshotwouo](https://user-images.githubusercontent.com/998681/32684079-10ad54a4-c635-11e7-904b-6d24559fcb2a.gif)

**Comment by Alex-302** [comment]
I see another
![image](https://user-images.githubusercontent.com/8361299/32732402-1e4b3bf0-c895-11e7-8dc7-fc21a04bdafb.png)

**Comment by antdude** [comment]
Were you using uBlock Origin, Alex?

**Comment by Alex-302** [comment]
Yes. Also using uBO. Look at my screenshot - it is different then your.
