### ISSUE TITLE
https://kresy.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7471]
**Site Sample** | 
----|
https://kresy.pl

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.433.2167**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Screenshoot
![20171106-111235-001](https://user-images.githubusercontent.com/9846948/32436227-a491a2ec-c2e3-11e7-83a4-6c6853dce52b.png)

**Comment by AdamWr** [comment]
Fixed.
