### ISSUE TITLE
http://greatamericandaily.com - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7473]
AdGuard blocks articles.

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32442972-10b3de50-c306-11e7-88b8-1b7f2fb31f76.png)

</details>

### Expected behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32442979-1562f13e-c306-11e7-97d5-8c0bec95a611.png)

</details>

### Customer ID 
1654004

### Your environment

* Adguard version: 1.3.1.82
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off
* Optimized filters: Off

**Comment by Alex-302** [comment]
Fixed.
