### ISSUE TITLE
Матрешка News - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7474]
https://play.google.com/store/apps/details?id=com.news.topstory&hl=ru

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32443319-4274cb24-c307-11e7-87e5-2ca05f28a15e.png)

</details>

### Customer ID 
1258198

### Your environment

* OS: Android 7.0
* AdGuard: 2.10.150
* Filtrerin mode: VPN
* Method: HQ
* HTTPS: On, whitelist
* DNS: Off
* Subscriptions: "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "German filter", "Experimental filter"

**Comment by Alex-302** [comment]
`OS: Android 7.0`
Нужен рут для переноса сертификата в системное хранилище.
Если пользователь не использует авторизацию через FB, то поможет такое правило:
```
||graph.facebook.com^$app=com.news.topstory
```
