### ISSUE TITLE
Block Sponsor Domains

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#74758]
Please block the following domains as they are scam/sponsor domains

amoviemedia.com
bookereads.com
elibrarigo.com
elibrarylist.com
epdflibrary.com
esmartpdf.com
kelvinlogger.com
libraryubook.com
loadepdf.com
moviemediaz.com
myebooke.com
mylovelibrabry.com
ndukdigital.com
pdf-filez.com
amiantesolutions.fr
bensonheating.co.uk
darrigues.fr
discount-fendi-bags.org
fairchildblog.nl
i5mpdf.0pe.kr
lesailesdemoname.fr
sacburberry-pascher.fr
taxi-christine.fr
thegoodolddayz.fr
vision-unit.fr
87150-cussac.fr
acbrindisiostuni.it
binzbleibtbinz.ch
cafesfactorerie.fr
cftcpolice.fr
crepsucette.fr
hamfest2018.ch
jesorsenville-agence.fr
librairiehautetension.fr
mcdolure-luxeuil.fr
michelfrancaix.fr
nanakuma.fr
oltrefrontieranews.it
pineroloindialogo.it
plexushub.co.uk
shoys.fr

pleasant-viewfire.org
texasbaptistcollege.org
pdfbookbay.tamarabolte.com
old.hurrareykjavik.is
my-ebooks.club
books-online.club
amemovideos.com
findsbooks.online
taifdlcin.ddns.net
zhcctapqgdmo.ddns.net
detached.pharmacie-rosult.fr
metropenge.dk
radiovalentinletelier.cl
shoptomlinsons.com
emission.pharmacie-rosult.fr
pdfbookusa.shortstackentertainment.com
pleasant-viewfire.org
texasbaptistcollege.org
dyonbooks.com
bookz.epicamble.com
ezypdf.ezyro.com
hoqaferivy.walkingshops.com
peltmedia.com
joheqejutukyvyz.lestisserandsduquebec.com
nesasukodame.supportselschools.com
c29b7ebeeaebbd98349b106bdb94e02b.jusdados.com.br
edubooks.site
view-read.com
ebookunlimited.space
pdf-files.xyz
ebookoffer.us
filesebookpdf.xyz
booklibraryunlimited.com
bukufreedownloadmurah.club
clickheres.com
ebookmarket.pro
firstmagazine.biz
ebookstop.site
ebookexprees.com
ebooklibrary.pw
specialrecommendations.space

**Comment by Alex-302** [comment]
Why they are must be blocked? `sponsor` is not equal to `scam`

**Comment by Nzzyme** [comment]
Well, these are scam.

**Comment by lolka4toli** [comment]
Blacklisted.
