### ISSUE TITLE
ipla.tv

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7477]
@AdamWr 

**Site Sample** | 
----|
https://www.ipla.tv/Miodowe-lata-zbyszek/vod-10537598

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.433.2167**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue
- ads audio stream is playing but player is not visible - static thumbnail.
- main player is visible 3 seconds and it is gone.

### HAR file: 
[www.ipla.tv.zip](https://github.com/AdguardTeam/AdguardFilters/files/1446620/www.ipla.tv.zip)

### Screenshoot
![20171106-155602-001](https://user-images.githubusercontent.com/9846948/32447013-08c772f6-c30b-11e7-8bd6-d3f032dd9aa1.png)

**Comment by AdamWr** [comment]
Mógłbyś proszę sprawdzić, czy po dodaniu tej reguły jest w porządku?
`||ipla.hit.stat24.com/*ad.xml$empty,important`

**Comment by FadeMind** [comment]
@AdamWr po dodaniu reguły filmy się odtwarzają. 
![20171107-061809-1](https://user-images.githubusercontent.com/9846948/32478173-7c763796-c383-11e7-8e87-d686542f2068.png)

**Comment by AdamWr** [comment]
Ok, dodane.
