### ISSUE TITLE
Add mobile ad servers to the DNS block list

### ISSUE THREAD

**Issue by rodaimi** [AdguardTeam/AdguardFilters#74772]
The following ad servers bypassed adguard DNS on my iPhone.

s.mopub.com

Description: mopub is a known mobile advertising company now owned by Twitter. Although I only noticed the above specified domain in my DNS logs was not blocked, I believe the whole domain should be blocked.

adcolony.xyz
Description: alias to adcolony.com, which is already blocked

vungle.akadns.net
Description: CDN for vungle.com

These domains were some of many found from the OvpnSpider app, which provides free OpenVpn servers. 

US appstore link: https://apps.apple.com/us/app/id928941628

**Comment by rodaimi** [comment]
Additional server:

applovin.com.edgekey.net

Description: CDN for applovin.com

**Comment by Alex-302** [comment]
> s.mopub.com

where is it used?

**Comment by rodaimi** [comment]
s.mopub.com is used in various mobile apps to show in-app advertisements.

This is related to
ads.mopub.com which is already blocked by the mobile ads filter.

**Comment by Alex-302** [comment]
> used in various mobile apps

I need example, which make request to this domain and ads are loaded.

**Comment by rodaimi** [comment]
The OvpnSpider app made requests to this domain and caused ads to be loaded however, I can no longer reproduce this.

https://apps.apple.com/us/app/id928941628

**Comment by rodaimi** [comment]
This app still makes requests to s.mopub.com that appear to be causing ads to load

https://apps.apple.com/us/app/police-scanner-radio-fire/id498405045

**Comment by Alex-302** [comment]
I don't see requests to mopub.com or sub-domains from these apps.

**Comment by rodaimi** [comment]
Try using Cloudflare DNS with a VPN server near New York City and adding the FDNY scanner to the police scanner radio app. This is what triggered requests to mopub.

**Comment by Alex-302** [comment]
Still nothing. Which ad do you see?

**Comment by rodaimi** [comment]
As of a few days ago, I'm not seeing ads anymore.
