### ISSUE TITLE
Hide 'N seek app

### ISSUE THREAD

**Issue by happygagarara12** [AdguardTeam/AdguardFilters#74790]
- [ ] ![image](https://user-images.githubusercontent.com/46888825/107845243-af9e9280-6e0c-11eb-87fd-226dea0cf056.png)

It suppose to block the ad in the game Hide 'N seek

I have no user list rules thingy and the DNS is turned on and is using adguard DNS and is full tunnel mode incompatible with other VPN apps and I'm on WIFI

**Comment by Alex-302** [comment]
Download link, please.

**Comment by wout-codes** [comment]
@Alex-302 `https://play.google.com/store/apps/details?id=com.seenax.HideAndSeek&hl=en&gl=US`

**Comment by stanislav-atr** [comment]
Ads were not reproduced on my device with different IPs.

@happygagarara12, could you please send us screenshot of your filtering log on the moment ads appear?
