### ISSUE TITLE
User rules doesn't work

### ISSUE THREAD

**Issue by tulik** [AdguardTeam/AdguardFilters#74811]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 
When selecting a site element to block the element is visible after reloading the page.

* **Expected behavior**: 
When selecting a site element to block it shouldn't be visible after reloading the page. (The user filter is created but it doesn't apply).

***Steps to reproduce the problem***:

[//]: #

- Go to any Website
- Click Block Element from the Safari AdGuard menu
- Select Site element to block
- Confirm blocking the element
- See the element disappears
- Reload page see element is not blocked
- See the user rule was created, but seems to be ignored

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | MacOS
Operating system version (Android/iOS) | 11.3 Beta (20E5172i)
Browser:                               | Safari Version 14.1 (16611.1.10.1.5)
AdGuard version:                       | 2.5.1.928 release (CL-1.7.150
Filters enabled:                       | Default
AdGuard DNS:                           | Default

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardForSafari #534](https://github.com/AdguardTeam/AdGuardForSafari/issues/534) via [**ZenHub**](https://www.zenhub.com/)
