### ISSUE TITLE
zfilm-hd.club - No video with filters on

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7481]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

https://zfilm-hd.club/23037-igra-prestolov.html
При включение фильтров не воспроизводит видео

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.35.41 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.26 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.20.52 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.59.34 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.33 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.73 Enabled=YES
ID=115 Name="RU AdList" Version=1.0.90.40 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Device: | iPad
Operating system:                      | 10.3.1
Browser:                               | Safari
AdGuard version:                       | 1.3.1.82
Simplified filters (iOS only)          | Off
Helpdesk ID (if exists):               | 1586159

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Поправил.
