### ISSUE TITLE
horo.mail.ru Missed ads

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7483]
***Description***:
Пропущена реклама на странице:
https://horo.mail.ru/prediction/leo/today/

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image1](https://user-images.githubusercontent.com/32528702/32465292-abe052ec-c34b-11e7-926c-d938135f3469.png)

</details><br/>

***System configuration***

**Filters:**
English, Spyware, Annoyances, Russian, Mobile Ads, Safari, RU AdList, RU AdList: Counters

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | iOS 11.1
Browser:                            | Safari
AdGuard version:                    | 1.3.2.108
Filters enabled:                    | 0, 2, 3, 14, 1, 11, 12, 115, 212
Simplified filters (iOS only)       | YES
Helpdesk ID (if exists):            | 1519015

PRO:
Pro feature DISABLED.
Tunnel mode SPLIT
DNS server: (null)
(null)

**Comment by Alex-302** [comment]
У меня не повторяется.
Попроси выключить сторонние фильтры для пробы и переключиться на полные фильтры и обратно.

**Comment by veronikasav** [comment]
Передали.

**Comment by ashvets-sup** [comment]
напомнили.

**Comment by Alex-302** [comment]
Пока закрываю. Если что - переоткройте(только для этого тикета).
