### ISSUE TITLE
AdGuard blocks notifications on Yandex mail in pinned tabs

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7486]
Notifications are reportedly blocked in pinned tabs with Yandex mail, occurs in Safari.

### Steps to reproduce

1. Go to https://mail.yandex.ru
2. Pin a tab
3. Send yourself an email from another account
4. For better understanding check the scree rec in comments to the support ticket: 1656180

### Customer ID
1656180 

### Your environment

* Adguard version: AdGuard for Mac 1.5.0
* OS: 1012
* Browser: Safari
* Subscriptions: English, Russian, Spyware, Filter unblocking search ads and self-promotion
* DNS: Off

**Comment by Alex-302** [comment]
Записи экрана не вижу.
Что он имеет в виду - push-уведомления от браузера?

**Comment by veronikasav** [comment]
Запись экрана в заметках (1656180)

**Comment by Alex-302** [comment]
у нас никак не повторяется. Попроси выключать фильтры по одному с проверкой. Например, для начала - фильтр аналитики.

**Comment by Alex-302** [comment]
Повторилось.

**Comment by Alex-302** [comment]
Возможно баг. Я пользуюсь mail.yandex.com, и с такими исключениями проблема повторяется
```
@@||mail.yandex.com^$document
@@||push.yandex.com^$document
@@||yastatic.net^$document
```

**Comment by Alex-302** [comment]
App's bug. Please wain for new version.
