### ISSUE TITLE
Missed ad.

### ISSUE THREAD

**Issue by Jammie1143** [AdguardTeam/AdguardFilters#74964]
1. Download this App on Android: `https://play.google.com/store/apps/details?id=com.unicostudio.whois`
2. Play the first two riddles. 
3. When continuing to the third level you should see this (it's an ad):
![Screenshot_20210215_165535](https://user-images.githubusercontent.com/77138531/107926492-bfef7280-6fb0-11eb-9f43-65d2a93312cf.jpg)
4. I hope this can be fixed

**Comment by Alex-302** [comment]
It seems this banner is hardcoded.
