### ISSUE TITLE
Browser Miner Papoto

### ISSUE THREAD

**Issue by YoKoGFX** [AdguardTeam/AdguardFilters#7503]
I just saw a tweet about a new browser miner Papoto:
https://twitter.com/GossiTheDog/status/927969196671107072

is it possible to get this Blocked? Because they even have a script (according to the E-Mail in the Tweet) that runs 10 hours after the Visit.
More infos on https://papoto.com/

**Comment by Alex-302** [comment]
Sure. It can be blocked
```
||papoto.com/lib/papoto.js$third-party
```
or
```
||papoto.com^
```

**Comment by Alex-302** [comment]
Blocked it completely.
