### ISSUE TITLE
Pochta.ru - Annoyance

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#7508]
При отслеживании посылок на сайте "Почты России" между треками вставляется самопиарящий баннер с изменяемым содержимым и, вроде, изменяемым местом вставки, но одинаковым указателем: `pochta.ru##a.tracking-card.tracking-card--banner`

<details><summary>Screenshot:</summary>

![pochta ru - tracking](https://user-images.githubusercontent.com/17948007/32539172-a484c5f8-c479-11e7-9f6c-74e726238a87.PNG)
</details><br/>

 Чтобы воспроизвести проблему, нужно перейти на страницу отслеживания посылок: https://www.pochta.ru/tracking - баннер уже там. Затем, по мере добавления "Номеров отслеживания" через поиск, баннер будет появляться между отслеженными треками и прикидываться одним из них, что в общем-то мешает, да и не нужно.

___________________________________________________
Pale Moon v26.5 (WinXP) - Adguard v2.7.2 (legacy)
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by Alex-302** [comment]
Поправил.
