### ISSUE TITLE
美剧鸟的广告无法过滤

### ISSUE THREAD

**Issue by biange200** [AdguardTeam/AdguardFilters#75113]
#75112

https://user-images.githubusercontent.com/37582806/108158818-b38a2780-7120-11eb-8a79-30c9185a3f76.mp4

https://officecommunity-my.sharepoint.cn/:u:/p/chenwei/EVcHxpJ_zzZLix2rO7G1KdcBjoqdK6qdp5cgo18TmnLt3w?e=2SuYcR
adguard官方能不能过滤这个美剧鸟广告

**Comment by Alex-302** [comment]
Hi. How this is related to https://github.com/AdguardTeam/AdguardFilters/issues/75112 ?

**Comment by Alex-302** [comment]
Ad not reproduced. Blocked trackers.
