### ISSUE TITLE
http://southpark.cc.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7527]
**Site Sample** | 
----|
http://southpark.cc.com/full-episodes/s21e06-sons-a-witches#source=5d49f083-1596-41fb-a585-87db5e245668&position=5&sort=airdate

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.433.2167**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue
- main player missing

### HAR files and screenshoots

1. DISABLED ADGUARD >>> [disabled.adg,southpark.cc.zip](https://github.com/AdguardTeam/AdguardFilters/files/1460360/disabled.adg.southpark.cc.zip)
![20171110-080511-001](https://user-images.githubusercontent.com/9846948/32646718-311e9992-c5ee-11e7-8ddd-9eeec1897a9c.png)
![20171110-080528-001](https://user-images.githubusercontent.com/9846948/32646719-3143b4c0-c5ee-11e7-944d-4bac9d30a55c.png)

2. ENABLED ADGUARD >>> [enabled.adg.southpark.cc.zip](https://github.com/AdguardTeam/AdguardFilters/files/1460362/enabled.adg.southpark.cc.zip)
![20171110-075647-001](https://user-images.githubusercontent.com/9846948/32646572-6fc86de0-c5ed-11e7-8e38-c39097907620.png)

**Comment by Alex-302** [comment]
I can reproduce only on the first open in private tab, without AdGuard.

**Comment by AdamWr** [comment]
On my end it happens for first visit even when AdGuard is disabled, so I think it isn't a filter list problem.

**Comment by FadeMind** [comment]
Main issue is not visible main player and welcome popup.

**Comment by FadeMind** [comment]
Chrome Cache issue.
