### ISSUE TITLE
http://lrfreelander.ru/ - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7528]
Missed ads here: http://lrfreelander.ru/

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32647218-dd59c934-c5f8-11e7-851a-a3f09f862175.png)

</details>

### Customer ID 
1658135

### Your environment

* Adguard version: AdGuard for Mac 1.5.0
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off

**Comment by Alex-302** [comment]
fixed.
