### ISSUE TITLE
Женский Календарь app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7529]
Missed ads in Женский Календарь app.

### Steps to reproduce

1. Install from here: https://play.google.com/store/apps/details?id=com.popularapp.periodcalendar
2. See the screenshot

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32647276-0c1951d6-c5f9-11e7-8127-1a8c3320f748.png)

</details>

### Customer ID 
1658135

### Your environment

* Adguard version: 2.10
* Android 7.1.1
* HTTPS: On
* DNS Off
* VPN mode
* HQ method
* "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Russian filter", "French filter", "Mobile Ads filter"

**Comment by Alex-302** [comment]
У меня чисто. Попроси лог запросов.
Про фильтрацию HTTPS в приложениях на дроиде 6+ ты в курсе.
Можно поробовать запретить приложению доступ в сеть.
