### ISSUE TITLE
Is this rule correct?

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#75306]
`haberturizm.com###detailBody > .img_position_left`

https://www.haberturizm.com/bodrum-da-gezilecek-yerleri-paylasiyoruz/25460/

<details><summary>Image</summary>

 
![www haberturizm com](https://user-images.githubusercontent.com/74098460/108505081-ee7a8f80-72c7-11eb-82a9-9b37ad3e2928.png)

</details>

**Comment by gork7777** [comment]
Evet doğru dostum. Ayrıyeten `haberturizm.com##.img_position_left` bunu da kullanabilirsiniz.

**Comment by Sergey-Lyapin** [comment]
@RadicalNoise 
I've added the domain to the existing rule
`##.detailp > .img_position_left`

**Comment by RadicalNoise** [comment]
There are too many sites with the same design. So I'll open a pull request soon.
