### ISSUE TITLE
Missed Ads in Apps

### ISSUE THREAD

**Issue by Jammie1143** [AdguardTeam/AdguardFilters#75307]
1. Install this app on Android: `https://play.google.com/store/apps/details?id=com.crazylabs.light.it.up&hl=en_US&gl=US`
2. Open the app, lose at the first try.
3. You should see this (ads): 
![Screenshot_20210219_204036](https://user-images.githubusercontent.com/77138531/108506175-598d8b80-72f3-11eb-905e-3769cee4fac2.jpg)
4. In the picture there are two ads, I hope this can be fixed.

**Comment by Jammie1143** [comment]
@Alex-302 @Sergey-Lyapin

**Comment by Alex-302** [comment]
This is hardcoded dummy.
