### ISSUE TITLE
Another missed ad in app.

### ISSUE THREAD

**Issue by Jammie1143** [AdguardTeam/AdguardFilters#75309]
1. Download this App on Android: `https://play.google.com/store/apps/details?id=com.time.trigger&hl=en_US&gl=US`
2. Play like 1 or 2 rounds.
3. You should see this (an ad):
![Screenshot_20210219_213145](https://user-images.githubusercontent.com/77138531/108511120-6792da80-72fa-11eb-830c-02894d056ed9.jpg)
4. I hope this can be fixed soon.

**Comment by Jammie1143** [comment]
@Alex-302 @Sergey-Lyapin

**Comment by Alex-302** [comment]
Same as here https://github.com/AdguardTeam/AdguardFilters/issues/75307
