### ISSUE TITLE
AdGuard social media filter blocks external links in GitHub discussions

### ISSUE THREAD

**Issue by SebastianRasch** [AdguardTeam/AdguardFilters#75305]
For example in this discussion, I link to my sports feed on feedly.com:

https://github.com/darkreader/darkreader/pull/5093#issuecomment-782029235

Link is hidden with the social media filter active.

**Comment by Alex-302** [comment]
Hi. This is because URL starts with `a[href^="https://feedly.com/i/subscription/"]`
and it is hidden by `~feedly.com##a[href^="https://feedly.com/i/subscription/"]`
Fixed.
