### ISSUE TITLE
gazeta.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7530]
**Site Sample** | 
----|
http://www.gazeta.pl/0,0.html

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.433.2167**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue
- player ads

### screenshoots
![20171110-095752-001](https://user-images.githubusercontent.com/9846948/32650412-f3e6418c-c5fd-11e7-906f-5a44952d742e.png)

**Comment by AdamWr** [comment]
Fixed.
