### ISSUE TITLE
Проблема с сайтом

### ISSUE THREAD

**Issue by ministr91** [AdguardTeam/AdguardFilters#7531]
Захожу на сайт и экран полностью белый. При выключенном adguard информация появляется. Все дело в баннере. На компьютере Касперский стоит и при переходе на сайт тоже экран белый, но если в браузере отключить анти-баннер, то появляется информация на сайте. Я конечно могу добавить его в белый список, но хотелось бы автоматически в базу adguard внести https://files.msal.ru/HTCOMNET/
Сделал har и log web запросов http://my-files.ru/e6u8rv
Adguard 2.9.136, фильтры по-умолчанию, фильтрация качественная, HTTPS, HTTP, Android 4.4.4

**Comment by Alex-302** [comment]
какой сайт?

**Comment by ministr91** [comment]
я же скинул ссылку 
https://files.msal.ru/HTCOMNET/

**Comment by ministr91** [comment]
ты даже логи не загрузил, которые я скинул

**Comment by Alex-302** [comment]
есть шаблон и есть репортилка. Ими пользуйся.

**Comment by ministr91** [comment]
Насчет шаблона - я перечислил все необходимое, что было в шаблоне. Насчет репорта, это что? На почту писать?

**Comment by Alex-302** [comment]
Есть правила. Если хочешь результат - соблюдай их.
Репорты создаются здесь:
https://reports.adguard.com/en/new_issue.html

**Comment by ministr91** [comment]
@Alex-302  какие репорты? Я же все подробно написал, раньше всегда так создавал issue. Что сейчас не так? Я же все правильно написал

**Comment by ministr91** [comment]
в последнее время ты меня расстраиваешь(

**Comment by ministr91** [comment]
Как же раньше хорошо было, я завел тему, кинул логи спустя какое-то время проблема решилась

**Comment by Alex-302** [comment]
у меня он никак не открывается
![image](https://user-images.githubusercontent.com/8361299/32958406-0f6cd10e-cbc7-11e7-9656-3f6c51f6ce92.png)

**Comment by ministr91** [comment]
что же тогда делать? Почему у меня открывается автоматически?

**Comment by Alex-302** [comment]
Не знаю. Пароль нужен.

**Comment by vitalkanev** [comment]
@Alex-302 Попытался ввести мои данные из операционки (Ubuntu Artful) - всё ещё требует пароль

**Comment by ministr91** [comment]
Ясно

**Comment by ministr91** [comment]
Может видос запилить?

**Comment by ministr91** [comment]
@Alex-302?

**Comment by Alex-302** [comment]
Что это вообще за сайт?

**Comment by ministr91** [comment]
Там публикуются разные статьи, материалы. У меня вход автоматически стоит, не могу сказать, почему логин и пароль просит

**Comment by ministr91** [comment]
@Alex-302

**Comment by Alex-302** [comment]
Этот сайт даже в поиске не упоминается. Исключи в HTTPS и всё.

**Comment by ministr91** [comment]
я его в белый список кинул, все работает

**Comment by ministr91** [comment]
Фильтры обновил, проблема осталась

**Comment by Alex-302** [comment]
Новой сборки нужно ждать. Добавь сам в настройках.

**Comment by vitalkanev** [comment]
Ничем :-)

**Comment by ministr91** [comment]
@Alex-302 не понимаю, зачем надо было оставлять v2.10.176 как окончательный вариант? 29 ноября было же все нормально, была обнова, ты внес исправления, так и выпустили бы новую версию с этими исправлениями

**Comment by Alex-302** [comment]
Не знаю, не смотрел. Прочитай её описение.

**Comment by ministr91** [comment]
в описании нет ничего про мою проблему

**Comment by ameshkov** [comment]
Если ты хочешь, чтобы что-то было исправлено, нужно нормально описывать проблему.

Вот хорошая статья об этом от Mozilla, но это применимо и к нам:
https://developer.mozilla.org/ru/docs/QA/%D0%A0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%8F%D1%89%D0%B8%D0%B5_%D0%BF%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF%D1%8B_%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D1%8F_%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0

А теперь смотрим на твой репорт:

* "Проблема с сайтом" -- **не подходит**. 

    Никак не описывает проблему. С каким сайтом? Какая проблема?

* Твое описание -- **не подходит**. 
    
    **Нет шагов для повторения проблемы, нет описания ожидаемого результата**
    Мы должны суметь повторить проблему. Нам совершенно не помогает то, что она повторяется у тебя. Нам надо ее **увидеть своими глазами**.

    Вот явно же говорят в комментариях, что сайт требует ввода логина и пароля. Что это за логин/пароль? Откуда нам его взять? Как нам повторить это?

    > Просто необходимо добавить этот сайт в белый список в вашу базу данных

    С чего бы это было необходимо? А завтра с него реклама будет грузиться. 

* Логи и хар прицеплены -- это очень хорошо. Но если бы мы могли его сами повторить, это было бы во много раз лучше.

Половину этих проблем решит за тебя использование репортилки: https://reports.adguard.com/ru/new_issue.html

**Comment by ministr91** [comment]
@ameshkov хорошо, в следующий раз учту

**Comment by ameshkov** [comment]
@ministr91 ну вот, что нам с этим репортом делать? Как нам самим повторить проблему? Что там за логин и пароль?

**Comment by ministr91** [comment]
@ameshkov не всегда удается повторить проблему, это я в целом. У некоторых пользователей может идти реклама, а воспроизвести повторно у вас не получается. Такое тоже бывает, @Alex-302 подтвердит и поэтому логи помогают выявить проблему.

**Comment by ameshkov** [comment]
Да я понимаю, но тут мы даже посмотреть не можем о чем речь
