### ISSUE TITLE
Typo issue

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#75337]
https://github.com/AdguardTeam/AdguardFilters/blob/7a3b8cda43751557f9f775ff3379cfe92dbadc69/TurkishFilter/sections/specific.txt#L2847

`haber-sanliurfa.com` 
Please delete `.com` extension and add `.net`  It should be `habersanliurfa.net`

---

`haberrtv.com.tr `
Remove .`tr` extesion. It should be `haberrtv.com`

**Comment by Alex-302** [comment]
Done
