### ISSUE TITLE
http://www.seahawks.com/ - incorrect blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7533]
http://www.seahawks.com/news/2017/10/30/pete-carroll-provides-update-safety-earl-thomas-710-espn-seattle

### Actual behavior

<details><summary>Screenshot:</summary>

![img_127debdb4c04-1](https://user-images.githubusercontent.com/15856304/32655828-fbd1fe58-c617-11e7-97d2-f5d076db7824.jpeg)

</details>

### Customer ID 
1418175

### Your environment

* Adguard version: 1.3.1 for iOS
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: On, Standard
* Optimized filters: Off

**Comment by Alex-302** [comment]
Fixed.
