### ISSUE TITLE
Network error Airvisual App

### ISSUE THREAD

**Issue by mircealinux** [AdguardTeam/AdguardFilters#75350]
Hello,

I have made this video adguard brakes connection to this app Airvisual false positive..

https://drive.google.com/file/d/1J79TSqpbacE-4-HstwP6jujmkCD04k6q/view?usp=drivesdk

Please fix

**Comment by Alex-302** [comment]
Hi. Please disable ad blocking for this app in apps management. We cannot unblock ads and analytics in filter.

**Comment by mircealinux** [comment]
So you cannot fix this issue ? does not look like and add

**Comment by Alex-302** [comment]
We can, but fix will unblock ads. That page is not their main coontent(promo)
