### ISSUE TITLE
Github app login error  android 11

### ISSUE THREAD

**Issue by mircealinux** [AdguardTeam/AdguardFilters#75371]
Hello,

With adguard enabled (app defaults settings) you cannot login to app Github

steps to reproduce issue
1.install github
2.try to login with adguard enabled default settings

we need a fix on this

**Comment by Alex-302** [comment]
Hi. I use GitHub on Android and cannot reproduce.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #3769](https://github.com/AdguardTeam/AdguardForAndroid/issues/3769) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alex-302** [comment]
This issue was moved, please look at the link above.
