### ISSUE TITLE
www.youtube.com

### ISSUE THREAD

**Issue by sc0rp10** [AdguardTeam/AdguardFilters#7539]
***Issue URL***: http://www.youtube.com/ — ***Ads***
***Issue Type***: Ads
***Comment***: 
***Screenshot***: 
[Screenshot 1](https://cdn.weblab.pro/v74de.png)

***System configuration***

Information | value
--- | ---
Platform: | Mac
Adguard version: | 123
Browser: | Chrome
Filters: | Spyware

**Comment by danidoedel** [comment]
@sc0rp10 Normally P1 would be the highest priority and P4 the lowest... not sure who made the labels though... https://github.com/AdguardTeam/AdguardBrowserExtension/labels

**Comment by evgeniy-ADG** [comment]
https://github.com/AdguardTeam/AdguardForMac/issues/248
