### ISSUE TITLE
Dead domains

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#75397]
These sites seem dead.

```
hdmacyayinlari.org
kahtamanset.com
kanala.com.tr
karikaturname.com
teknoprogram.org
tekpartizlefullhd.net
sanliurfa.net
sarkisozlugu.com
mt2dosyalar.com
paraticlube.com
paroketfilms.com
pasgol4.tv
pasizle5.com
```

**Comment by Yuki2718** [comment]
Double-checked and anything other than
```
karikaturname.com
paraticlube.com
pasizle25.com
```
seem to be really dead.
`karikaturname.com` returns Cloudflare error 521 and `pasizle25.com` redirection error, maybe can be removed.
`paraticlube.com` is not entirely dead.

@RadicalNoise Please note, parent domain being dead doesn't mean all  its subdomain dead too.

**Comment by Alex-302** [comment]
> paraticlube.com

It has new content(site has new owners)
https://web.archive.org/web/20180106110336/http://www.paraticlube.com/
