### ISSUE TITLE
cdn234.weblab.pro

### ISSUE THREAD

**Issue by sc0rp10** [AdguardTeam/AdguardFilters#7541]
***Issue URL***: https://cdn234.weblab.pro/qi270.png — ***Ads***
***Issue Type***: Ads
***Comment***: 
***Screenshot***: 
[Screenshot 1](https://cdn.weblab.pro/qi270.png)

***System configuration***

Information | value
--- | ---
Platform: | Mac
Adguard version: | 124
Browser: | Chrome
Filters: | English

**Comment by vbagirov** [comment]
test ticket
