### ISSUE TITLE
online.sberbank.ru - Ads

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7547]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

Не блокируется реклама на странице
сбербанка.
https://node1.online.sberbank.ru/PhizIC/private/accounts.do

[debug (2).txt]
(https://github.com/AdguardTeam/AdguardFilters/files/1463207/debug.2.txt)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

</details><br/>

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 7 
AdGuard version:                       | 6.2.433.2167
Filters enabled:                       | 0,1,2
Stealth mode options (Windows only)    | enabled
Helpdesk ID (if exists):               | 1144675

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Сайт в исключениях HTTPS в целях безопасности, как и прочие банки.
Исключение можно удалить
http://s2.1pic.org/files/2017/11/13/ffa16b04158770980cae.jpg
и перезапустить браузер, и далее помощником, т.к. у  меня нет сбербанковской карты.

**Comment by xapdkop** [comment]
@Alex-302 у сбера есть свой скрипт, который грузит "персональные предложения". Вот этот скрипт
stat.online.sberbank.ru/PhizIC-res/27.0/scripts/jquery.ifixpng.js . Для блока скрипта использовал такое правило:
`||stat.online.sberbank.ru/PhizIC-res/27.0/scripts/jquery.ifixpng.js$domain=node1.online.sberbank.ru,important,empty`
после этого "персонального предложения" больше нет. Ниже скрин этого "предложения".

![_](https://user-images.githubusercontent.com/30960705/33088152-dcc35112-cefd-11e7-9cf2-32ff1679e66e.png)

**Comment by Alex-302** [comment]
sberbank.ru в исключениях HTTPS.

**Comment by xapdkop** [comment]
@Alex-302 не думаю, по крайней мере в расширениях (2.7.2 из магазина хрома, как в Вивальди, так и в я.браузере). Только что поставил расширение Adguard начисто - на сбербанке реклама блочится (именно реклама, а не персональные предложения; настройки по дефолту).
