### ISSUE TITLE
http://m.800xs.net/ - Ad

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7548]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

Missed ad on page:
http://m.800xs.net/book_38100/

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/32685826-cdb2d81e-c6a1-11e7-997f-e6c7f663ec87.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.35.73 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.30 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.24.95 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.20.71 Enabled=YES
ID=8 Name="Dutch filter" Version=1.0.9.38 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.39 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.74 Enabled=YES
ID=104 Name="EasyList China" Version=1.0.90.79 Enabled=YES
ID=106 Name="EasyList Dutch" Version=1.0.90.66 Enabled=YES
ID=219 Name="ChinaList+EasyList" Version=1.0.4.12 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | 11.1
Browser:                               | Safari
AdGuard version:                       | 1.3.2.108
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | Default 
Helpdesk ID (if exists):               | 1615221

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
