### ISSUE TITLE
adrenaline.com.br

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#75515]
[https://adrenaline.com.br/artigos/v/67784/the-medium-na-rtx-3080-rx-6800-xt-e-no-series-x-ray-tracing-dlss-e-fidelity-fx](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://adrenaline.com.br/artigos/v/67784/the-medium-na-rtx-3080-rx-6800-xt-e-no-series-x-ray-tracing-dlss-e-fidelity-fx)

Top banner and "Continua após a publicidade" leftovers:

`##.main>.d-lg-block , center>small`

![banner](https://user-images.githubusercontent.com/35470489/108636463-1bfc4000-7464-11eb-9b35-721f66b685a9.png)

![center-small](https://user-images.githubusercontent.com/35470489/108636432-ec4d3800-7463-11eb-8982-a084041cf99c.png)

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin
Firefox

**Comment by AdamWr** [comment]
Fixed "Continua após a publicidade", but I couldn't reproduce top banner (first screenshot).
Do you still can reproduce it?

**Comment by adranger** [comment]
No. I think it was about a limited-time offer.

**Comment by AdamWr** [comment]
Okay, thank you for your reply.
