### ISSUE TITLE
Breaks Firebase apps 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7553]
AdGuard (with default setting) breaks all Firebase web apps because Firebase SDK (a very popular app development platform by Google, if you didn’t already know) is being blocked from this URL among others (https://www.gstatic.com/firebasejs/4.6.0/firebase.js)

Of course, I could whitelist it on my end or host the SDK myself, but it still breaks any app built on Firebase (including official documentation examples and tutorials all over the web) for a vast majority of users who use the hosted SDK from Google

Also, while you’re at it, please consider removing OneSignal SDK (https://cdn.onesignal.com/sdks/OneSignalSDK.js) from your filters since it’s a very legitimate push notification service used by thousands of websites that needs the user’s consent to allow and manage push notifications

ID: 1659762

**Comment by Alex-302** [comment]
@evgeniy-ADG I need example of the app and description how to reproduce and what is broken.

**Comment by Alex-302** [comment]
> a very legitimate push notification service used by thousands of websites

It is blocked by Annoyances filter only(disabled by default)

**Comment by ameshkov** [comment]
Guys, I don't get it, we do not block firebase SDK.

Here's an example of a web app using it:
https://fir-ui-demo-84a6c.firebaseapp.com/

**Comment by nitishraj** [comment]
Save an .html file with the following, open it in browser (I'm on Safari 11.0.1/macOS 10.13.1). Check console

`<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
    </head>
    <body>
    <script src="https://www.gstatic.com/firebasejs/4.6.0/firebase.js"></script>
    <script src="https://www.gstatic.com/firebasejs/4.6.0/firebase-firestore.js"></script>
    </body>
</html>`

<img width="1267" alt="screenshot 2017-12-03 11 02 45" src="https://user-images.githubusercontent.com/1530142/33522757-1deba778-d81a-11e7-803a-213a3f31e9c4.png">

**Comment by nitishraj** [comment]
Here's my Adguard settings
[Adguard Settings.pdf](https://github.com/AdguardTeam/AdguardFilters/files/1524521/Adguard.Settings.pdf)

**Comment by ameshkov** [comment]
`Adblock & uBlock polish filter` is the one to blame.

@AdamWr could you please report it to them? Please close this issue when they take care of it.

**Comment by AdamWr** [comment]
Ok, I reported it and it was fixed - https://github.com/MajkiIT/polish-ads-filter/commit/e18bf1dcc9f9f69f960701db556d89f1b333eb0e#diff-711027ed0794992ae3b8710d874f3df7R2894
