### ISSUE TITLE
https://www.veeam.com/ - false blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7558]
https://www.veeam.com/ru/support.html?ad=menu-support

### Actual behavior

<details><summary>Screenshot:</summary>

![img_1531](https://user-images.githubusercontent.com/15856304/32689117-0ac22364-c6e7-11e7-936a-63e5e07a46f1.PNG)

</details>

### Your environment
1485790

* Adguard version: 1.3.1 for iOS
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off
* Optimized filters: Off

**Comment by Alex-302** [comment]
I can't reproduce. Please try
```
@@.html?ad=$domain=veeam.com
```
