### ISSUE TITLE
Is it possible to block Instant Apps with AdGuard? 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7562]
Is it possible to block Instant Apps with AdGuard? 

> Этот "подарок" от Google сам себя обновляет, да еще плюс к тому может исполнять приложения без установки. Это не радует, особенно при том что антивирус проверяет новые и устанавливающиеся приложения. Как брандмауэром можно запретить этому зловреду доступ к интернет?

ID: **1066754**

**Comment by Alex-302** [comment]
Нужно собрать лог запросов и подождать, пока явление повторится. Желательно с временным штампом.
