### ISSUE TITLE
www.xinnet.com

### ISSUE THREAD

**Issue by Hill-98** [AdguardTeam/AdguardFilters#75675]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: The domain name resolution page cannot be displayed normally

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ffrqB6b.png)
</details><br/>

* **Expected behaviour**: The domain name resolution page is displayed normally

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/vgg9yDN.png)
</details><br/>

***Steps to reproduce the problem***: Enter the domain name resolution page of xinnet.com

I am using uBlock and this problem is caused by AdGuard Tracking Protection rules:
`||www.xinnet.com/dcp/javascript/fingerprint2.min.js$script,domain=www.xinnet.com`

**Comment by Alex-302** [comment]
@Hill-98 Hi. Is account required? I don't see this request.

**Comment by Hill-98** [comment]
@Alex-302 Yes, it requires an account. I have used uBlock logger to check and only fingerprint2.min.js is blocked.

**Comment by Hill-98** [comment]
uBlock logger Screenshot:
![Screenshot](https://i.imgur.com/7Mv5N6I.png)

**Comment by Alex-302** [comment]
Ok, added.
