### ISSUE TITLE
False Positive: digital.mashreqbank.com

### ISSUE THREAD

**Issue by mujtabamir** [AdguardTeam/AdguardFilters#75719]
digital.mashreqbank.com is being blocked by AdGuard. I use NextDNS and can see that the traffic is being blocked. 

**digital.mashreqbank.com (→ star-azurefd-prod.trafficmanager.net) is being blocked by AdGuard DNS filter.**

Needless to say, that URL is the NetBanking URL for a leading bank in UAE.

**Comment by mujtabamir** [comment]
This is also stopping some LinkedIn pages from loading.

**Comment by mujtabamir** [comment]
outlook.office365.com is also being blocked incorrectly now.

**Comment by mujtabamir** [comment]
MS Teams is affected as well and blocked incorrectly.

**Comment by AdamWr** [comment]
It should works correctly now - https://github.com/AdguardTeam/AdGuardSDNSFilter/commit/1ac16b7ff542bcb45b9a1d2f62fec291b91b2dd0
Thank you for reporting it.
