### ISSUE TITLE
incorrect blocking login.microsoftonline.com

### ISSUE THREAD

**Issue by jiri001meitner** [AdguardTeam/AdguardFilters#75728]
***incorrect blocking login.microsoftonline.com***:
* **Current behaviour**: 
Adguard DNS is blocking login.microsoftonline.com

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>
![obrazek](https://user-images.githubusercontent.com/1045987/108973354-87bcf380-7684-11eb-977c-57b9ff704f37.png)
![obrazek](https://user-images.githubusercontent.com/1045987/108973831-1c275600-7685-11eb-905a-29cfe34d980e.png)
</details><br/>

* **Expected behaviour**: 

I expect the correct resolving for domain login.microsoftonline.com. This is important for using Microsoft Teams, etc. 

<details><summary>Screenshot:</summary>

![obrazek](https://user-images.githubusercontent.com/1045987/108974177-80e2b080-7685-11eb-8942-58d6eb1fcac7.png)

</details><br/>

***Steps to reproduce the problem***:

# dig a login.microsoftonline.com @94.140.14.14

; <<>> DiG 9.16.6-Ubuntu <<>> a login.microsoftonline.com @94.140.14.14
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1236
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 05151e0a8d8c3382 (echoed)
;; QUESTION SECTION:
;login.microsoftonline.com.	IN	A

;; ANSWER SECTION:
login.microsoftonline.com. 3600	IN	A	0.0.0.0

;; Query time: 95 msec
;; SERVER: 94.140.14.14#53(94.140.14.14)
;; WHEN: St úno 24 09:54:02 CET 2021
;; MSG SIZE  rcvd: 82

# dig a login.microsoftonline.com @94.140.15.15

; <<>> DiG 9.16.6-Ubuntu <<>> a login.microsoftonline.com @94.140.15.15
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30528
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 9a00cb6cc699fcec (echoed)
;; QUESTION SECTION:
;login.microsoftonline.com.	IN	A

;; ANSWER SECTION:
login.microsoftonline.com. 3600	IN	A	0.0.0.0

;; Query time: 27 msec
;; SERVER: 94.140.15.15#53(94.140.15.15)
;; WHEN: St úno 24 09:54:47 CET 2021
;; MSG SIZE  rcvd: 82

***System configuration***

**Filters:**
None
[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Ubuntu 20.10
Operating system version (Android/iOS) | None
Browser:                               | Firefox
AdGuard version:                       | Adguard DNS servers (dns.adguard.com)
Filters enabled:                       | None
AdGuard mode (Android only):           | None
Filtering quality (Android only):      | None
HTTPS filtering (Android only):        | None
Simplified filters (iOS only)          | None
AdGuard DNS:                           | Default
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | None

**Comment by neoKushan** [comment]
yup, this broke my work machine this morning rather suddenly

**Comment by Alex-302** [comment]
Already fixed.
