### ISSUE TITLE
规则不正确冲突

### ISSUE THREAD

**Issue by wolaikk** [AdguardTeam/AdguardFilters#75734]
如图，图中的2条规则同时生效了，造成过滤问题，@@规则生效的情况下拦截规则不应该生效
@@||tracker.namitiyu.com^$script
||tracker.$xhr,websocket,script,ping
网页是https://live.leisu.com/detail-3491048
![捕获](https://user-images.githubusercontent.com/63185523/108986746-6f24fb80-76cd-11eb-95d9-34062b8ba20a.PNG)
![捕获1](https://user-images.githubusercontent.com/63185523/108986758-70eebf00-76cd-11eb-86b3-721ecc800352.PNG)
![捕获2](https://user-images.githubusercontent.com/63185523/108986760-71875580-76cd-11eb-925a-b99e2af89434.PNG)
![捕获4](https://user-images.githubusercontent.com/63185523/108986764-721fec00-76cd-11eb-95dc-7d5a1919078a.PNG)

**Comment by wolaikk** [comment]
https://halflife.coding.net/p/list/d/list/git/raw/master/ad-pc.txt
filters

**Comment by c2xusnpq6** [comment]
https://github.com/privacy-protection-tools/anti-AD/

**Comment by Alex-302** [comment]
@wolaikk Hi. Please look at content type of blocked requests - your exclusion does not cover CSS requests `$stylesheet`.
