### ISSUE TITLE
dcard.tw

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#75745]
`贊助` = `sponsor`

![image](https://user-images.githubusercontent.com/75058881/109000111-38a3ac80-76de-11eb-8877-79f30feba44b.png)

**Comment by Alex-302** [comment]
@c2xusnpq6 Hi. Cannot find this element. Is account required?

**Comment by wout-codes** [comment]
@Alex-302 Can you simplify this? `dcard.tw##div#__next > div.bvk29r-0.bpvGjj > div.bvk29r-2.hRYgdl > div.sc-10tqbnq-0.LctwW > div.sc-10tqbnq-1.kDeEqR > div.d4ydwz-0.eQRUQs > div.sc-1kb03aj-0.qnXGt > div.sc-1wisey8-0.hjnOql > div.sc-1db29sy-0.dhzTzT > div > div > article.tgn9uw-0.jkVXTH > div.tgn9uw-1.eXUTCj > div.euk31c-0.duRTie > div.euk31c-1.ftfqQP > div.euk31c-7.gSSFmf`. I am not that good with Advanced syntax.

**Comment by c2xusnpq6** [comment]
> @c2xusnpq6 Hi. Cannot find this element. Is account required?

no

**Comment by c2xusnpq6** [comment]
taiwan ip only? 🤔 @Alex-302

**Comment by wout-codes** [comment]
@c2xusnpq6  I could reproduce it and fix it. Please add this to User Rules and test for breakage, `dcard.tw##article[role*="article"]:contains(贊助活動)`. Let me know the result.
CC @Alex-302

**Comment by c2xusnpq6** [comment]
> @c2xusnpq6 I could reproduce it and fix it. Please add this to User Rules and test for breakage, `dcard.tw##article[role*="article"]:contains(贊助活動)`. Let me know the result.
> CC @Alex-302

It works!

**Comment by wout-codes** [comment]
> > @c2xusnpq6 I could reproduce it and fix it. Please add this to User Rules and test for breakage, `dcard.tw##article[role*="article"]:contains(贊助活動)`. Let me know the result.
> > CC @Alex-302
> 
> It works!

Added already by @Alex-302. Update your filters in 3 hours.

**Comment by c2xusnpq6** [comment]
@Alex-302 pls edit `贊助活動小` --> `贊助活動` ^^'' thx

**Comment by Alex-302** [comment]
ok

**Comment by c2xusnpq6** [comment]
NICE~

![image](https://user-images.githubusercontent.com/75058881/109494304-a9750b00-7ac8-11eb-8b0e-15de8912b0de.png)
