### ISSUE TITLE
bilanx.dcard.tw

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#75747]
https://bilanx.dcard.tw/v1/sessions

tracking? (not so sure~... pls help~

![image](https://user-images.githubusercontent.com/75058881/109000996-54f41900-76df-11eb-9ffc-3cc355b81e44.png)

![image](https://user-images.githubusercontent.com/75058881/109001227-aa302a80-76df-11eb-80e3-472bfe10a33f.png)

**Comment by Alex-302** [comment]
Cannot open bilanx.dcard.tw

**Comment by c2xusnpq6** [comment]
> Cannot open bilanx.dcard.tw

`referer: https://www.dcard.tw/`

https://www.dcard.tw/
