### ISSUE TITLE
masalaseen.net [NSFW] [Pop-ups]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#75796]
https://masalaseen.net

Pop-ups seen on this domain on Windows and Android. Please check

**Comment by Nzzyme** [comment]
Hi, I am seeing a message "Pop-up Blocked" on Chrome (Android) on almost all the pages and I need to close that box and it comes up again and again which is very annoying. Can you please fix this?

**Comment by wout-codes** [comment]
It's fixed. Please update filters.

**Comment by Nzzyme** [comment]
Thanks. Just observed this empty box on all the pages. Can you please add a rule to remove this?

Example URL: https://masalaseen.net/today-exclusive-sexy-call-girl-blowjob-4/

https://prnt.sc/10kfz2g

**Comment by wout-codes** [comment]
@Nzzyme Can you open the developer tools (CTRL + Shift + l) on the element?

**Comment by Nzzyme** [comment]
I right-clicked on the element and selected "Inspect" and this comes up

https://prnt.sc/10kg8ax

**Comment by wout-codes** [comment]
@Nzzyme Can you try this rule? Check for breakages.
`masalaseen.net##a[href][target="_blank"] > img[width="300"][height="100"]`

**Comment by Nzzyme** [comment]
Works fine with AG & uBlock entension for Chrome. Thanks

**Comment by Yuki2718** [comment]
Fixed by EasyList

**Comment by Nzzyme** [comment]
Can you please check and fix the ads seen on all domains:

Example:
https://masalaseen.net/today-exclusive-desi-boudi-showing-her-boobs-and-pussy/

Screenshot:
https://prnt.sc/11fegfn
