### ISSUE TITLE
Any chance block ads from this sites?

### ISSUE THREAD

**Issue by anastenko** [AdguardTeam/AdguardFilters#75815]
@kotoricon commented on [Mon Feb 22 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/3766)

Those ads really suck.
![Screenshot_20210223-012843_Samsung Internet](https://user-images.githubusercontent.com/8659834/108746210-fca20780-7576-11eb-86bf-49493cfa9efe.jpg)

example:
http://m.feijisu7.com/acg/60525/8.html

Tried to block 'm.feijisu7.com' but look like there ads servers always change, dont really works well. chrome and samsung self browser dont work for this site.

---

@Chinaski1 commented on [Thu Feb 25 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/3766#issuecomment-785761242)

Hello there!

I will move this task to the filters section.
But first, I recommend that you check for filter updates and clear your browser cache.

**Comment by Yuki2718** [comment]
@kotoricon That ad in the screenshot is called from `hnjls.com.cn` which is blocked by the Chinese filters. Please enable Chinese filter and check again.

**Comment by Sergey-Lyapin** [comment]
@kotoricon 
I can't reproduce these ads with AdGuard for Android and Content Blocker
Please use these filters:

```
AdGuard Base
AdGuard Tracking protection
AdGuard Social Media
AdGuard Annoyances
and language-specific filters:
AdGuard Chinese or EasyList China (in Content Blocker)
```
