### ISSUE TITLE
BSNL blocking isnt working as intended?

### ISSUE THREAD

**Issue by para994** [AdguardTeam/AdguardFilters#75836]
117.254.84.212:3000 
This is the server that the Indian ISP BSNL uses to inject ads
I got adguard just because i saw how it added a script to block the ad
but instead of blocking the ad from popping up, all thats happening is the ad doesnt show up and i get a blank page without redirecting to my actual intended webpage.
This issue also affects many games i play, where the dns request to the game server is overridden by the adware injection, thereby disconnecting me from online sessions.

**Comment by Alex-302** [comment]
Hi. Does it happen on desktop? Only HTTP sites are affected, HTTPS without that ads?

**Comment by para994** [comment]
> Hi. Does it happen on desktop? Only HTTP sites are affected, HTTPS without that ads?

it redirects https sites too
 google.com for example
Here's an example
[example.pdf](https://github.com/AdguardTeam/AdguardFilters/files/6051398/example.pdf)

**Comment by para994** [comment]
> Hi. mouse-sensitivity.com has HTTPS version - https://www.mouse-sensitivity.com/ Berrer install `HTTPS Everywhere` browser extension. Ads cannot be injected to HTTPS traffic by provider.
> Added
> `||117.254.84.212:3000^`

I actually filed a consumer grievance to the government and got the ISP to remove ads from my connection. Seems like they have a DND list
