### ISSUE TITLE
can't play video [ ani.gamer.com.tw ]

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#75837]
https://ani.gamer.com.tw/animeVideo.php?sn=12560

`影片因格式不支援或者伺服器或網路的問題無法載入。`
google translate: `The video cannot be loaded due to unsupported format or server or network issues.`
bing: `The movie could not be loaded because the format is not supported or because of a server or network problem.`

![image](https://user-images.githubusercontent.com/75058881/109173732-23eb1580-77bf-11eb-9dc4-901ffcf9f5dc.png)

![image](https://user-images.githubusercontent.com/75058881/109173864-47ae5b80-77bf-11eb-9522-c22c636a3563.png)

**Comment by Alex-302** [comment]
Not reproduced. Which AdGuard is used?
