### ISSUE TITLE
lookmovie.top [Fake Links] 

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#75858]
https://lookmovie.top/movies/hostage-to-the-devil-2016/

Seeing fake links (See screenshot). Checked on Chrome on Android. Please also check for possible popups. Please fix

https://ibb.co/3cBgMK2

**Comment by wout-codes** [comment]
@zloyden You forgot to fix the fake buttons.

**Comment by zloyden** [comment]
Nope, I separated the commits, but thanks for your participation.

**Comment by Nzzyme** [comment]
I am still seeing the fake links. Can you check please?

**Comment by wout-codes** [comment]
@Nzzyme Hi! Please update your filters.

**Comment by Nzzyme** [comment]
I check for filter updates every hour. I checked last night and was able to see the fake links. I will check again and let you know on my mobile.
In the meantime, I was checking on Chrome (Windows) with uBlock Origin extension with AG filters and was able to see the fake links. Can you please add the relevant filters?

My Filters: https://prnt.sc/1093nq8

Fake Links seen: https://prnt.sc/1093n80

**Comment by wout-codes** [comment]
@Nzzyme Can you try purging the cache and update the lists again? Or try to install AdGuard Extension, it's working fine on my end.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/76908410/109410334-b7496400-79d4-11eb-9bdb-2fc6b4125928.png)
</details><br/>

**Comment by Nzzyme** [comment]
Ok, thanks that worked in Chrome (Windows). Not sure if it is an issue with the extension itself? I had checked after updating the filters and had seen the fake links. However, purging the cache and later updating the filters worked.

**Comment by Nzzyme** [comment]
Just checked in Chrome (Android) and I see a pop-up when tapping on the play button. Updated the filters and cleared the cache, cookies & browsing history but still see the pop-up. 

Ex:

lookmovie.top/movies/avatar-2009

**Comment by wout-codes** [comment]
Break;case `mstream.xyz.

**Comment by wout-codes** [comment]
@zloyden Please take a look.

@Nzzyme 
`||tkxiavegstgq.com^$third-party`
`mstream.xyz#%#//scriptlet("abort-current-inline-script", "String.fromCharCode", "/emZnbG9hZGVk|break;case \$\.|break;case \d{1}/")`

**Comment by zloyden** [comment]
Not reproduced on my end with the last filter update, but I can see that they have this script. Added rules for this site, please check the filters update manually in 1-2 hours. Also please visit the website in the private mode to check it, ofc.

**Comment by wout-codes** [comment]
@zloyden Player button has disappeared.

**Comment by zloyden** [comment]
It seems those rules caused this. Removed them, but https://github.com/AdguardTeam/AdguardFilters/issues/75858#issuecomment-787977179 not reproduced on my end. @AdguardTeam/filters-maintainers please take a look.

**Comment by AdamWr** [comment]
I can't reproduce popups on Android/Windows.
