### ISSUE TITLE
Remove consent layer from annoyance filter

### ISSUE THREAD

**Issue by janwinkler** [AdguardTeam/AdguardFilters#75865]
***Description***:
* **Current behaviour**: 

GDPR consent tool is blocked by annoyance filter. Therefore no consent can be given and features on multiple sites do not work or only partially work.

* **Expected behaviour**: 

Remove consentmanager.mgr.consensu.org and similar *.mgr.consensu.org domains from filter in order to allow users to give/reject consent.

**Filters:**

Annoyances filter 

Information                            | Value
---                                    | ---
Operating system:                      | all
Operating system version (Android/iOS) | not tested
Browser:                               | all
AdGuard version:                       | all
Filters enabled:                       | Annoyances filter

**Comment by ameshkov** [comment]
Using (or not using) a content blocker and the lists that block trackers and cookie notices is de facto rejecting (or granting) access. However, if blocking the consent manager breaks any website functionality, please provide examples, we'll fix it. 

Note, that Annoyances filter is not enabled by default in any AdGuard products, the only way people can enable it is if they find it, read the description (that mentions cookie notices) and enable it.
