### ISSUE TITLE
video player broken on website

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdguardFilters#75867]
if i disable adguard base and adguard mobile ads the video player works. but without both disabled video player wont work

(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.baltimoresun.com/news/nation-world/ct-aud-nw-stimulus-check-updates-20210225-mnfsy2zmszgdhosglolq67x75i-story.html)

**Comment by BlazDT** [comment]
iOS or Android?

**Comment by jordanelliott23** [comment]
ios sorry

**Comment by BlazDT** [comment]
Update available in about 3-4 hours.
