### ISSUE TITLE
yoomoney.ru

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#75898]
Т.к. Яндекс.Деньги [переехали](https://money.yandex.ru/main), то можно смело прибить все правила относящиеся к ним, и перенести в [ЮMoney](https://yoomoney.ru/actions) только 2:

1. Блокировка всякого всплывающего мусора и рекламы на правой панели: `||yoomoney.ru/offerwall/`

2. Блокировка рекламы мобильного приложения внизу страницы: `yoomoney.ru##.money-app-promo2` [отсюда](https://github.com/AdguardTeam/AdguardFilters/issues/7225#issuecomment-357163203).

___________________________________________________
 Adguard v3.5.31 - FireFox v53.0.3 - Win7SP1
Базовый фильтр AdGuard | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и систем аналитики

**Comment by Alex-302** [comment]
Новые правила пока не добавляю, посмотрим на репорты.

**Comment by XX-J** [comment]
Мой "репорт" не считается?

**Comment by Alex-302** [comment]
Покажи хоть скрины.
Всё подряд блокировать тоже не стоит.

**Comment by XX-J** [comment]
**1**.
     а) Баннер поверх страницы с затемнением.

<details><summary>Screenshot:</summary>

(https://funkyimg.com/i/3bgwB.png)
</details>

<details><summary>Код:</summary>

<div data-react-widget-id="AppPromo">
	<div id="app-promo-container">
		<div style="">
			<div class="promo-popup svelte-1in8xty promo-popup_desktop">
				<div class="promo-popup__background svelte-1in8xty"></div>
				<div class="promo-popup__details svelte-1in8xty">
					<div class="details__title svelte-1in8xty">8 Марта уже рядом — порадуйте близких</div>
					<div class="details__description svelte-1in8xty">А мы поможем выбрать подарки. Посмотрите подборку предложений, которые идеально подойдут в качестве подарка к 8 Марта. И для себя можно что-нибудь найти.</div>
					<div class="details__image-background svelte-1in8xty" style="background-color: #8B3FFD;"></div>
					<div class="details__image svelte-1in8xty" style="background-image: url(https://yoomoney.ru/i/shop/popup_23vs8_2021.png);"></div>
					<div class="details__buttons svelte-1in8xty"><a class="promo-popup__action svelte-1in8xty" style="background: #8B3FFD; border-color: #8B3FFD; color: #FFFFFF;" href="https://yoomoney.ru/promo/category/february23-march8?utm_source=money&amp;utm_campaign=gender_holiday2021&amp;utm_medium=banner&amp;utm_content=popup" target="_blank" rel="noopener">Выбрать подарок</a>
						<button class="promo-popup__button promo-popup__button_type_ghost svelte-1in8xty">Не сейчас</button>
					</div>
					<button class="details__close-button svelte-1in8xty" style="background-image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHZpZXdCb3g9IjAgMCAxNiAxNiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB4PSIxIiB3aWR0aD0iMjEuMjEzIiBoZWlnaHQ9IjEuNDE0IiByeD0iLjcwNyIgdHJhbnNmb3JtPSJyb3RhdGUoNDUgMSAwKSIgZmlsbD0iI2ZmZiIvPjxyZWN0IHk9IjE1IiB3aWR0aD0iMjEuMjEzIiBoZWlnaHQ9IjEuNDE0IiByeD0iLjcwNyIgdHJhbnNmb3JtPSJyb3RhdGUoLTQ1IDAgMTUpIiBmaWxsPSIjZmZmIi8+PC9zdmc+);"></button>
				</div>
			</div>
		</div>
	</div>
</div>
</details>


     б) Правая колонка со "скидками" и "кэшбэками" - Промо.

<details><summary>Screenshot:</summary>

(https://funkyimg.com/i/3bgAd.png)
</details>

<details><summary>Код:</summary>

<div class="page-layout__right-column">
  <div class="offerwall-banner" data-offer-block-id="actions_marketing">
    <div class="tile svelte-m362sv">
      <div class="tile svelte-509piy tileEffects" style="--shadow-color: rgba(193,1,48,0.05); --hover-shadow-color: rgba(193,1,48,0.4);">
        <div class="bgImage svelte-509piy" style="background-color: #C10130; background-image: url(https://yoomoney.ru/i/shop/electronics2_bc8c5a.png);"></div>
        <div class="bgFill svelte-509piy" style="background-image: linear-gradient(to bottom, rgba(193,1,48,0), rgba(193,1,48,0.4) 50%, #C10130 70%);"></div>
        <a class="content svelte-1nswcju contentEffects" href="/promo/offer/18929-eldorado?viewId=35ed027c-603f-c56b-74e1-1cba00140000" target="_blank" rel="noopener"><img class="logo svelte-1nswcju" src="https://yoomoney.ru/i/shop/eldorado.ru_logo_r.svg" alt="Эльдорадо">
          <div class="contentText svelte-1nswcju" style="color: #FFFFFF">
            <div class="merchantName svelte-1nswcju">Эльдорадо</div>
            <div class="discount svelte-1nswcju" style=" font-size: 18px; line-height: 25px;">Скидки до 50%</div>
            <div class="description svelte-1nswcju">На электронику и бытовую технику</div>
          </div>
        </a>
      </div>
    </div>
  </div>
  <script>
  (function(d, w, c) {
    (w[c] = w[c] || []).push(function() {
      try {
        var params = {
          "targetBlock": "offerwall-banner",
          "blockId": "actions_marketing",
          "blockURL": "/offerwall/static/block/block-banner.js",
          "platform": "desktop"
        };

        if (params.targetBlock) {
          params.mountElement = document.getElementsByClassName('offerwall-banner')[0];
        }
        YMOfferwall.blockBanner(params);
      } catch (e) {}
    });
  })(document, window, 'ymOfferwallCallbacksBanner');
  </script>
  <script src="/offerwall/static/block/block-banner.js" async=""></script>
  <div class="offerwall-actions" data-offer-block-id="actions">
    <section class="ActionsBlock__StyledWrapper-rch0l3-0 gfuWKH">
      <div class="TileMiniGrid__StyledWrapper-sc-9xv1h1-0 HrgGo">
        <div class="TileMiniGrid__StyledHeading-sc-9xv1h1-1 fkwdUS">
          <div class="TileMiniGrid__StyledBoldText-sc-9xv1h1-2 bMdPQp">Ловите новые скидки</div>
          <div class="TileMiniGrid__StyledBadge-sc-9xv1h1-3 jueQYt">+20</div>
        </div>
        <a href="/promo/offer/19328-tui.ru?viewId=35ed027c-603f-c56b-8e67-683e000f0000" target="_blank" rel="noopener" class="TileMiniWide__StyledTileMiniWide-sc-1b8enp5-0 bBsRqg TileMiniGrid__StyledTileMiniContainerWide-sc-9xv1h1-5 jEHomN" draggable="false">
          <div class="TileMiniWide__StyledLeftColumn-sc-1b8enp5-1 dSXPMe" style="">
            <div class="TileMiniWide__StyledMerchantName-sc-1b8enp5-3 dhINjk">TUI.ru</div>
            <div class="TileMiniWide__StyledDiscount-sc-1b8enp5-4 fvgVPr">Кэшбэк 1,95%</div><span class="TileMiniWide__StyledText-sc-1b8enp5-2 isGEJd">За бронирование туров</span></div><img src="https://yoomoney.ru/i/shop/tui.ri_logo_r.svg" class="TileMiniWide__StyledLogo-sc-1b8enp5-5 ijLXPQ"></a>
        <div class="TileMiniGrid__StyledBottomRow-sc-9xv1h1-4 iuVHRq">
          <a href="/promo/offer/7980-ashan?viewId=35ed027c-603f-c56b-8e67-683e000f0000" target="_blank" rel="noopener" class="TileMiniSmall__StyledTileMini-sc-6fg19m-0 ewnZPQ TileMiniGrid__StyledTileMiniContainerSmall-sc-9xv1h1-6 eyMXBv" draggable="false"><img src="https://yoomoney.ru/i/shop/auchan.ru_logo_r.svg" class="TileMiniSmall__StyledLogo-sc-6fg19m-1 hChyUf">
            <div class="TileMiniSmall__StyledText-sc-6fg19m-2 kciJnu">
              <div class="TileMiniSmall__StyledDiscount-sc-6fg19m-3 lazuQC">Кэшбэк 3%</div>
              <div class="TileMiniSmall__StyledMerchantName-sc-6fg19m-4 gIffMw">Ашан</div>
            </div>
          </a>
          <a href="/promo/offer/9291-perekrestok?viewId=35ed027c-603f-c56b-8e67-683e000f0000" target="_blank" rel="noopener" class="TileMiniSmall__StyledTileMini-sc-6fg19m-0 cCwjtC TileMiniGrid__StyledTileMiniContainerSmall-sc-9xv1h1-6 eyMVEA" draggable="false"><img src="https://yoomoney.ru/i/shop/perekrestok.ru_logo_r.svg" class="TileMiniSmall__StyledLogo-sc-6fg19m-1 hChyUf">
            <div class="TileMiniSmall__StyledText-sc-6fg19m-2 kciJnu">
              <div class="TileMiniSmall__StyledDiscount-sc-6fg19m-3 lazuQC">Кэшбэк до 8%</div>
              <div class="TileMiniSmall__StyledMerchantName-sc-6fg19m-4 gIffMw">Перекресток</div>
            </div>
          </a>
        </div><a href="/promo?utm_source=yoomoney.ru&amp;utm_campaign=actions_more_button_new" draggable="false" class="DefaultButton__StyledButton-sc-15humzk-0 ezmnFh DefaultButtonGrey-sc-1xbu9nd-0 TileMiniGrid__StyledButton-sc-9xv1h1-7 jbLUnd cLCBFq">Показать все</a></div>
    </section>
  </div>
  <script>
  (function(d, w, c) {
    (w[c] = w[c] || []).push(function() {
      try {
        var params = {
          "blockId": "actions",
          "blockURL": "/offerwall/static/block/block-actions.js",
          "platform": "desktop"
        };

        if (params.targetBlock) {
          params.mountElement = document.getElementsByClassName('undefined')[0];
        }
        YMOfferwall.blockActions(params);
      } catch (e) {}
    });
  })(document, window, 'ymOfferwallCallbacksActions');
  </script>
  <script src="/offerwall/static/block/block-actions.js" async=""></script>
</div>
</details>


     Всё вместе блокируется одним правилом:
`||yoomoney.ru/offerwall/`

___________________________________________________

 **2**. Блокировка рекламы мобильного приложения внизу страницы.
     [Идентично этому посту.](https://github.com/AdguardTeam/AdguardFilters/issues/7225#issuecomment-357163203)

`yoomoney.ru##.money-app-promo2`

**Comment by Alex-302** [comment]
Добавлю от попапа `yoomoney.ru##div[data-react-widget-id="AppPromo"]`
и `yoomoney.ru##.money-app-promo2`

**Comment by XX-J** [comment]
OK. 'A: In progress' можно убрать.
