### ISSUE TITLE
Fixed, update shouldplz remove grafixfather.com from ur filter list 

### ISSUE THREAD

**Issue by vpnbrothers2019** [AdguardTeam/AdguardFilters#75912]
Fixed, update should be available in 1-2 hours.

_Originally posted by @AdamWr in https://github.com/AdguardTeam/AdguardFilters/issues/51255#issuecomment-597478500_

**Comment by Jammie1143** [comment]
brother, they will never remove from their filter list. it's their job to remove ads and circumvent anitadblock script.
