### ISSUE TITLE
tkmftc.aotter.net, tktracker.aotter.net and so on.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardFilters#7593]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
@ameshkov
@AdamWr

Issue URL: tkmftc.aotter.net, tktracker.aotter.net and so on — Missed Ad & Trackers
Issue Type: Ads & Trackers
Comment:
Screenshot: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/fVTBxsk.png)
</details><br/>

***Steps to reproduce the problem***:
Mo PTT: A mobile BBS app.
for iOS:
https://itunes.apple.com/tw/app/mo-ptt/id804745434?l=zh&mt=8

for Android:
https://play.google.com/store/apps/details?id=mong.moptt&hl=zh_TW

The DNS requests log of AdGuard Pro for iOS with AdGuard DNS server:
tkmftc.aotter.net and the associated domains are not blocked by AdGuard DNS server.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Wd1ESXv.png)
</details><br/>

The filtering log of AdGuard for Android:
Only tkmftc.aotter.net is blocked by Mobile ads filter.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/R7ruZI6.png)
</details><br/>

> If you add ||aotter.net^$third-party ads are blocked?

Sorry AdamWr, the rule is useless.
After adding ||aotter.net^$third-party in my user filter, ads are Not blocked.
Before you added tkmftc.aotter.net in Mobile ads filter, the ad was not blocked.
I didn't notice that although I cancelled to tick aotter.net in advance in my user filter at that time, the rule (||aotter.net^) was still ticked after I reopened AdGuard.
A bug.
I saw the ad was blocked because aotter.net is blocked in my user filter.
It was not because the rule "||aotter.net^$third-party" was working.

The associated domains are:
tkmftc.aotter.net
tktracker.aotter.net
tkmedia.aotter.net
tkrecorder.aotter.net

MO PTT app's ad domains:
flurry.com
doubleclick.net
aotter.net

tkmftc.aotter.net is the one of ad domains in Mo PTT app.
It causes the ad.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/fVTBxsk.png)
</details><br/>

tkmftc.aotter.net is added in AdGuard's Mobile ads filter, but not in Simplified domain names filter.

I read the content of Mobile ads filter.
> https://github.com/AdguardTeam/AdguardForAndroid/issues/1520#issuecomment-336207580
> ||tkmftc.aotter.net^

Well, my article.
But only adding tkmftc.aotter.net in Mobile ads filter is NOT enough.
When using Mo PTT app for Android, the ad is blocked because tkmftc.aotter.net is in Mobile ads filter.
When using Mo PTT app for iOS, the ad is NOT blocked because tkmftc.aotter.net is NOT in Simplified domain names filter.
AdGuard Pro for iOS only can use AdGuard DNS server for blocking ads.
The ad filter of AdGuard DNS server is similar to Simplified domain names filter.

In that article, I suggested blocking aotter.net.
But AdamWr said, 
> I mean that they have "normal" website, for example - https://agirls.aotter.net/post/51953 which will be broken if I add this rule.

https://aotter.net/
This is a company which analyzes network data and sells ads.
However, it provides general websites as what AdamWr said.
For example:
https://agirls.aotter.net/

Since we can't block the whole aotter.net, we can just block the under domains in both Mobile ads filter and Simplified domain names filter.
tkmftc.aotter.net <- a sure ad domain
tktracker.aotter.net <- a tracker?
tkmedia.aotter.net <- I am not sure what it is. But it's found in the filtering log.
tkrecorder.aotter.net <- I am not sure what it is. But it's found in the filtering log.

For iOS users, they feel that some ads are not blocked by AdGuard Pro v1.3.0 and the after versions. 
It's because system-wide ad blocking is removed after AdGuard Pro v1.2.1.
AdGuard Pro has no default filter, and then using AdGuard DNS server is the way.
Simplified domain names filter used by AdGuard DNS server has fewer contents, compared with the total of English filter, Social media filter, Spyware filter, Mobile ads filter, EasyList and EasyPrivacy.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | Android/iOS
Browser:                               | ?
AdGuard version:                       | AdGuard for Android v.2.10.164 RC / AdGuard Pro for iOS v1.3.2
Filters enabled:                       | English filter, Spyware filter, Social media filter, Annoyances filter, Mobile ads filter and EasyList China filter
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default/Blacklist mode)
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | Default Protection, AdGuard Pro for iOS with AdGuard DNS server
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Ok, I moved `||tkmftc.aotter.net^` to adservers section in Mobile filter, so this rule will be also in Simplified domain names filter.

`||tktracker.aotter.net^` and `||tkrecorder.aotter.net^` added to Spyware section in Mobile filter, so it will be also in Simplified domain names filter.

Something else should be also added?

**Comment by lancelot-moon** [comment]
Hi,
Do you think tkmedia.aotter.net is a general domain?
Eh, I don't have other else about aotter.net.
Thanks for your great help!

**Comment by AdamWr** [comment]
Hi,
I found some images on `tkmedia.aotter.net` which looks like ads, but I'm not sure that this is only ads domain, so I don't want to block it.

Thank you for your answer.
