### ISSUE TITLE
outbrain.com - one of facebook/instagram app's sponsored ad domains

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardFilters#7595]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)
@ameshkov
@AdamWr

Issue URL: outbrain.com — Missed Ad
Issue Type: Ads
Comment: one of facebook app's sponsored ad domains
Screenshot: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

The 1st ad is originally blocked by AdGuard's filter.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/bKUdVVi.jpg)
</details><br/>

The other ads on that page.
<details><summary>Screenshots:</summary>

The 2nd ad:
![image](https://i.imgur.com/ghta45q.jpg)

The 3rd ad:
![image](https://i.imgur.com/6LSpxIA.jpg)

The 4th ad:
![image](http://i.imgur.com/xV2e6RV.jpg)

The 5th and 6th ads:
![image](https://i.imgur.com/2mUDASs.jpg)
</details><br/>

***Steps to reproduce the problem***:
We ever discussed about it in the article.
https://github.com/AdguardTeam/AdguardFilters/issues/6703

Directly search "https://www.ettoday.net/dalemon/post/29790?from=fb_et_news" on facebook app.
I don't believe what AdGuard told that it's impossible to block facebook app's sponsored ads.
Finally, I found it's valid if blocking outbrain.com.
Those sponsored ads have different ad domains on facebook app.

The 1st ad is originally blocked by AdGuard's filter.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/eQfWd6p.jpg)
</details><br/>

If outbrain.com is only just the ad domain at this time, there is no ad on facebook app.
However, outbrain.com is just one of ad domains on facebook app.
If facebook app uses other sponsored ad domains on that page, ads appear.

The other ads on that page were disappeared if blocking outbrain.com.
<details><summary>Screenshots:</summary>

No ad.
![image](https://i.imgur.com/TqFBXrJ.jpg)

No ad.
![image](https://i.imgur.com/LC7M9iU.jpg)

No ad.
![image](https://i.imgur.com/2MXUf2i.jpg)

No ad.
![image](https://i.imgur.com/CIOvIMy.jpg)

No ad.
![image](https://i.imgur.com/2JN21ny.jpg)

No ad.
![image](https://i.imgur.com/tHhazBO.jpg)

No ad.
![image](https://i.imgur.com/FGTMhMc.jpg)

No ad.
![image](https://i.imgur.com/7YEO1oG.jpg)

No ad.
![image](https://i.imgur.com/Xj4xggj.jpg)

No ad.
![image](https://i.imgur.com/tINmi7q.jpg)
</details><br/>

1 month ago, I already found that outbrain.com is one of facebook/instagram app's sponsored ad domains by myself.
From v4.0, adblock by FutureMind started to also provide DNS requests log.
I'm surprised that outbrain.com is in adblock's filter.
visualrevenue.com is under the group of outbrain.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/bufhg6o.png)
</details><br/>

It detected amplifypixel.outbrain.com.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/rxnYggk.png)
</details><br/>

www.googletagservices.com is in adblock's filter.
DNS requests logs of AdGuard Pro for iOS:
In the past, I already manually added outbrain.com in my blacklist.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/8ZCvhQM.png)
</details><br/>

www.googletagservices.com is not blocked by AdGuard DNS server (Simplified domain names filter).
Is it also not in other AdGuard's filters (English filter and so on)?
Is adservice.google.com an ad domain?

May you check them?
outbrain.com
visualrevenue.com <- It's in Spyware filter and Simplified domain names filter.
www.googletagservices.com
adservice.google.com
eyeviewads.com <- I forget where I found this. It's in English filter and Simplified domain names filter.

Thanks a lot!

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | ?
Operating system version (Android/iOS) | Android/iOS
Browser:                               | ?
AdGuard version:                       | AdGuard for Android v.2.10.164 RC / AdGuard Pro for iOS v1.3.2
Filters enabled:                       | English filter, Spyware filter, Social media filter, Annoyances filter, Mobile ads filter and EasyList China filter
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default/Blacklist mode)
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | Default Protection, AdGuard Pro for iOS with AdGuard DNS server
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by ameshkov** [comment]
As I recall, blocking `outbrain.com` completely may break quite a lot of websites

**Comment by lancelot-moon** [comment]
Hi,

May you let StevenBlack's hosts file as one of AdGuard's filters?
It has about 43000 entries.

https://github.com/StevenBlack/hosts/blob/master/readme.md

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

You can see that some domains about outbrain.com are blocked in StevenBlack's hosts file.
0.0.0.0 amplifypixel.outbrain.com
0.0.0.0 odb.outbrain.com
0.0.0.0 traffic.outbrain.com
0.0.0.0 images.outbrain.com
0.0.0.0 storage.outbrain.com
0.0.0.0 widgets.outbrain.com
0.0.0.0 hpr.outbrain.com
0.0.0.0 log.outbrain.com

0.0.0.0 vrp.outbrain.com
# [Server Central Network][AS23352][66.225.192.0/18]

0.0.0.0 paid.outbrain.com
0.0.0.0 outbrain.com

**Comment by lancelot-moon** [comment]
For your reference.

https://github.com/StevenBlack/hosts/issues/434
https://github.com/oznu/dns-zone-blacklist/blob/master/README.md

Thanks.

**Comment by Alex-302** [comment]
the necessary domains are already blocked
