### ISSUE TITLE
the videos on ani.gamer.com.tw - Anti Adblock Script

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardFilters#7596]
@ameshkov 
@AdamWr

Issue URL: https://ani.gamer.com.tw/index.php — Anti Adblock
Issue Type: Anti Adblock Script
Comment:
The website detected AdGuard.
It asked to add gamer.com.tw in the whitelist or disable adblockers.
Otherwise, we are unable to watch anime online.
I tried to add gamer.com.tw in HTTPS exclusions.
But it's useless.
I was still unable to watch anime.
The only way is disabling AdGuard.

Screenshot:

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/g7FAKnH.png)
</details><br/>

***Steps to reproduce the problem***:
May AdGuard solve it?
Let us watch anime there with AdGuard enabled and no ad.
Thanks a lot!

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Adguard driver: | WFP
Browser:                               | Google Chrome v61.0.3163.100
AdGuard version:                       | AdGuard for Windows v6.2.433.2167
Filters enabled:                       | English filter, Spyware filter, Social media filter, Annoyances filter, Mobile ads filter and EasyList China filter
Stealth mode options (Windows only)    | Enable Stealth mode, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Self-destructing third-party cookies, Disable cache for third-party requests, Block WebRTC, Block Location API
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
`本服務授權範圍僅限台灣地區，如果您為外國用戶或使用變更IP的插件或軟體，將無法正常使用本服務。`
I can't access with Chinese IP.

**Comment by lancelot-moon** [comment]
Hi,

Not Chinese ip.
Taiwan and China are different countries.
I first disabled AdGuard for Windows and use a foreign ip by VPN.
For example, Russian and Hong Kong ip.
You are right.
It only allows Taiwan ip for watching anime online.
Is it possible that you get a Taiwan ip by VPN?

Thanks.

**Comment by Alex-302** [comment]
> Taiwan and China are different countries.

I know it:) I have no Taiwan ip.

Could you, please, try to enable `xinggsf`(乘风 广告过滤规则) filter?

**Comment by lancelot-moon** [comment]
Hi,

I already enabled xinggsf filter, but it's useless.
It's still anti-adblock.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/pfwnUXS.png)
</details><br/>

**Comment by Alex-302** [comment]
> Microsoft Edge can't be filtered by AdGuard.

It can. Just enable WFP driver in AdGuard network sessings.
Please check these test rules one-by-one:
```
@@||ani.gamer.com.tw^$urlblock
```
and
```
@@||ani.gamer.com.tw^$elemhide
```

**Comment by lancelot-moon** [comment]
Hi,

"@@||ani.gamer.com.tw^$elemhide" is useless.

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/JRjIPcU.png)
</details><br/>

Only "@@||ani.gamer.com.tw^$urlblock" or "@@||gamer.com.tw^$urlblock" is valid.
No anti-adblock message on the video.
The anti-adblock message is shown in a window.
I can manually close the anti-adblock message window and watch anime at least.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/rEc0ZG1.png)
</details><br/>

As what I said, there is an ad video from the beginning.
Need to wait until the counting backwards is finished.
The ad video has 2 types.
Ad anime or general ad video.

Ad anime:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/iZi5V2c.jpg)
</details><br/>

General ad video:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/CUuEMO0.png)
</details><br/>

Great!
You solved the direct anti-adblock on videos.

1. May you hide the anti-adblock message window?
2. May you block an ad video from the beginning?

Thanks.

**Comment by Alex-302** [comment]
> Only "@@||ani.gamer.com.tw^$urlblock" 

ok. Please disable the rule and check with English filter only. If ad blocking will be detected, open filtering log, enable `Blocked` check-box and reproduce the issue, and make screenshot(s)

**Comment by lancelot-moon** [comment]
Hi,

I did a test about the association between filters and anti-adblock on ani.gamer.com.tw.

If we ONLY enable English filter, the website detects a adblocker.
It shows 2 anti-adblock messages on ani.gamer.com.tw.
But no anti-adblock message is on the video.
We can watch anime.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/7EvPbMj.png)
</details><br/>

If you ONLY enable Annoyances filter or EasyList China filter, it doesn't block ads on ani.gamer.com.tw.
So there is no anti-adblock message.
If you ONLY enable Annoyances filter and English filter (or EasyList China filter and English filter), it shows 1 anti-adblock message on ani.gamer.com.tw.
The 2nd anti-adblock message is hidden by Annoyances filter or EasyList China filter.
We can watch anime.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/aHCZv64.png)
</details><br/>

If you ONLY enable Simplified domain names filter, the ads on ani.gamer.com.tw are blocked.
However, there is no anti-adblock message!
We can watch anime.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/C29fcK1.png)
</details><br/>

If you ONLY enable Mobile Ads filter, the ads on ani.gamer.com.tw are blocked.
The 2 anti-adblock messages are hidden.
Additionally, there is an direct anti-adblock messages on the video.
We are unable to watch anime.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Q3lDU2e.png)
</details><br/>

Do you have any thought to let me try?

Thanks!

**Comment by lancelot-moon** [comment]
Hi,

Anti anti-adblock.
How about AAK-Cont?
https://xuhaiyang1234.gitlab.io/AAK-Cont/

Can you let it be compatible with AdGuard?

**Comment by Alex-302** [comment]
What about TeamViewer session?

**Comment by lancelot-moon** [comment]
Do you want to do remote control?
We are in different time zone.

Do you have any thought?

> We have 3 problems.

> 1. Mobile Ads filter causes the direct anti-adblock message on the video, which lets us not watch anime.
For using mobile devices, it means that we are unable to watch anime on ani.gamer.com.tw if we enable Mobile Ads filter on Android devices or we enable Mobile Ads filter in Safari's content blocker on iOS devices.

> 2. English filter causes the 2 anti-adblock messages windows although we can normally watch anime.
May you solve them although Annoyances filter or EasyList China filter can hide the 2nd anti-adblock message?
The 1st anti-adblock message is still not hidden.

> 3. We must wait until the counting backwards of an ad video is finished, and then it starts to play what we want to watch.
May you block an ad video when playing anime from the beginning?
I think this is difficult such as youtube.

B/R

**Comment by Alex-302** [comment]
> We are in different time zone.

do you live in HK?

> Do you have any thought?

I got it.

**Comment by lancelot-moon** [comment]
No, I live in Taiwan.
Is it necessary to do remote control?
I don't wish...

**Comment by Alex-302** [comment]
Do you know fast Taiwan VPN/proxyes?

**Comment by lancelot-moon** [comment]
Can you not try this?
http://www.vpngate.net/en/

It has  free Taiwan server.

Or you can try Hide My IP app.
Every Friday, it allows all users to free use all servers via android app.
You can use its Taiwan server every Friday.
https://play.google.com/store/apps/details?id=com.hidemyip.hideme&hl=zh_HK

Windscribe has fast Taiwan servers, but need to pay for using all servers.
Free users can't use its Taiwan servers.
https://windscribe.com/

https://malwaretips.com/threads/windscribe-pro-lifetime-subscription-39-20.76391/

**Comment by lancelot-moon** [comment]
Hi,

I found that Hide My IP provides Free Proxy.
You can try its free Taiwan proxy.
https://www.hide-my-ip.com/proxylist.shtml

And then today is Friday.
Only Hide My IP for Android allows all servers for free users every Friday.
https://play.google.com/store/apps/details?id=com.hidemyip.hideme&hl=zh_HK

You can try to enable Mobile Ads filter on Android devices.
You'll find that anime on ani.gamer.com.tw can't be played if Mobile Ads filter is enabled.

Thanks.

**Comment by Alex-302** [comment]
> Only Hide My IP for Android allows all servers for free users every Friday.

It want full license:(

Please open filtering log in AdGuard for Windows, reproduce the issue in private tab with Emg filter only end make screenshot 
![image](https://user-images.githubusercontent.com/8361299/32937595-df9cd216-cb81-11e7-8f1c-ed65c5619d52.png)
also you can export log.

**Comment by lancelot-moon** [comment]
Can you not use free Taiwan proxy which are provided by Hide My IP?
https://www.hide-my-ip.com/proxylist.shtml

> It want full license:(

Maybe its all servers are only allowed to be free used for users on some limited countries' google play.

I'll export the log later.
Thanks.

**Comment by Alex-302** [comment]
> Can you not use free Taiwan proxy which are provided by Hide My IP?

tried, but connection is not working.

**Comment by lancelot-moon** [comment]
Hi, sorry for the delay.
I only enabled Mobile ads filter because only Mobile ads filter caused the direct anti-adblock on videos.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/g7FAKnH.png)
</details><br/>

The filtering log: (blocked)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/sD5hCPE.png)
</details><br/>

The link is the log file.
https://app.box.com/s/49x28wnhw497hhwr3oyn34ijh09y5mho

Thank you.

**Comment by Alex-302** [comment]
> Alex-302, I maybe will lend you a temporary VPN account for only Taiwan ip.

it will be useful for me. Please send it by private message on our forum.

**Comment by lancelot-moon** [comment]
How can I send a private message to you on github?
Or do you mean this?
https://forum.adguard.com/index.php
I don't have that forum account.
Do you not have an AdGuard staff email address?

**Comment by Alex-302** [comment]
> Or do you mean this?

yes.



> Is the under information not enough?

Please export it(green button).

**Comment by Alex-302** [comment]
Please check these rules:
```
@@||i2.bahamut.com.tw/JS/ad/animeBanner.js$domain=ani.gamer.com.tw
@@||i2.bahamut.com.tw/JS/ad/animeVideo.js$domain=ani.gamer.com.tw
```

**Comment by lancelot-moon** [comment]
Your rules are useless.
The direct anti-adblock message on the video
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/3AmrBgY.png) 
</details><br/>

The screenshot of blocked log:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/rc4QiRU.png) 
</details><br/>

The link is the log file.
https://app.box.com/s/kxnw916vz3sg385dj1pi7d8hl4dq5lea

**Comment by Alex-302** [comment]
I can do nothing without access to the site.

**Comment by lancelot-moon** [comment]
MY little brother is busy in work recently.
Maybe you need to wait for several days for a temporary VPN account.
Do you have another convenient method to lend you VPN?
I don't have that forum's account.
I more like github...

**Comment by Alex-302** [comment]
> Do you have another convenient method to lend you VPN?

Telegram, Skype, ICQ?

**Comment by lancelot-moon** [comment]
We can contact with each other on VK.
What's your VK?
Are you a Russian? ^^

**Comment by Alex-302** [comment]
`skype` - `alxbrv` But I prefer Telegram.

> Are you a Russian?

yes.

**Comment by lancelot-moon** [comment]
Хорошо, я уже добавил вас в skype. Спасибо.
I use google translate. XDD

**Comment by Alex-302** [comment]
ok)

**Comment by lancelot-moon** [comment]
Hi, I found this script for bahamut.com.tw.

https://pastebin.com/aBy2YfF2

**Comment by Alex-302** [comment]
And?

**Comment by lancelot-moon** [comment]
3 problems.
> 1. Mobile Ads filter causes the direct anti-adblock message on the video, which lets us not watch anime.
For using mobile devices, it means that we are unable to watch anime on ani.gamer.com.tw if we enable Mobile Ads filter on Android devices or we enable Mobile Ads filter in Safari's content blocker on iOS devices.

Well, today I found that this 1st issue can be solved if adding "@@||i2.bahamut.com.tw/JS/ad/animeVideo2.js$domain=ani.gamer.com.tw" in Mobile ads filter.

We try to solve the below 2 problems.
> 2. English filter causes the 2 anti-adblock messages windows although we can normally watch anime.
May you solve them although Annoyances filter or EasyList China filter can hide the 2nd anti-adblock message?
The 1st anti-adblock message is still not hidden.

It's strange that the 1st anti-adblock message was hidden or disappeared by the latest English filter on Windows's Google chrome, but was not hidden on Android's Google chrome.
Only enable English filter on AdGuard for Windows.
The 1st anti-adblock message was hidden.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/alVdiXv.png)
</details><br/>

Only enable English filter on AdGuard for Android.
The 1st anti-adblock message was not hidden.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ybOkwLz.png)
</details><br/>

Originally, the 2nd anti-adblock message below the website can be hidden by Annoyances filter or EasyList China filter.

> 3. We must wait until the counting backwards of an ad video is finished, and then it starts to play what we want to watch.
May you block an ad video when playing anime from the beginning?

**Comment by lancelot-moon** [comment]
@ameshkov 
Hi,
Have you find Taiwan VPN for the test?
1. May you first add the both 2 rules in Mobile ads filter?
@@||i2.bahamut.com.tw/JS/ad/animeVideo.js$domain=ani.gamer.com.tw @@||i2.bahamut.com.tw/JS/ad/animeVideo2.js$domain=ani.gamer.com.tw

2. The 1st anti-adblock message was caused by English filter.
I have no idea how to hide it.
(The 2nd anti-adblock message can be hidden by Annoyances filter or EasyList China filter.)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ybOkwLz.png)
</details><br/>

3. We must wait until the counting backwards of an ad video is finished, and then it starts to play what we want to watch.
May you block an ad video and pass it when playing anime from the beginning?
I have no idea.

**Comment by lancelot-moon** [comment]
I searched "bahamut.com.tw" in filters and then I found these.

In Mobile ads filter:
! https://github.com/AdguardTeam/ExperimentalFilter/issues/1742
||bahamut.com.tw/JS/ad/

In English filter:
!---------------------------------------------------------------------
!------------------------------ Taiwan -------------------------------
!---------------------------------------------------------------------
! https://github.com/AdguardTeam/AdguardFilters/issues/6826
@@||digiland.tw/advert.js
! https://github.com/AdguardTeam/ExperimentalFilter/issues/1240
@@||m.gamer.com.tw^$elemhide
!
gamer.com.tw#$##BH-bigbanner { position: absolute!important; left: -3000px!important; }
gamer.com.tw#$#img[onload="AntiAd.check(this)"] { position: absolute!important; left: -3000px!important; }
||bahamut.com.tw/JS/ad/insideAD.js
||bahamut.com.tw/js/ad.js
||gamer.com.tw/adcounter.php

**Comment by lancelot-moon** [comment]
@seanl-adg 

Hi,
Thanks that you did the changes in English filter.
I supposed that you would did the changes in Mobile ads filter.
But you didn't clearly read my report.

> If adding "@@||i2.bahamut.com.tw/JS/ad/animeVideo2.js$domain=ani.gamer.com.tw" in Mobile ads filter, anime can be played on PC's browser, but not on mobile browser.

> If adding "@@||i2.bahamut.com.tw/JS/ad/animeVideo.js$domain=ani.gamer.com.tw" in Mobile ads filter, anime can be played on mobile browser, but not on PC's browser.

> We should add both of them.

You only added "@@||i2.bahamut.com.tw/JS/ad/animeVideo2.js^$domain=ani.gamer.com.tw" in English filter, which lets anime on ani.gamer.com.tw be ONLY played on browsers on Windows PC if enabling Mobile ads filter.

But anime on ani.gamer.com.tw still can NOT be played on browsers on Android if enabling Mobile ads filter.
Did you ever try to play anime on ani.gamer.com.tw on Chrome on Android if enabling Mobile ads filter?
You should also add "@@||i2.bahamut.com.tw/JS/ad/animeVideo.js$domain=ani.gamer.com.tw" in  English filter.

And then the 1st anti-adblock message was caused by English filter.
It isn't hidden on Google Chrome on Android.
(The 2nd anti-adblock message can be hidden by Annoyances filter or EasyList China filter.)

Google Chrome on Android:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ybOkwLz.png)
</details><br/>

Thanks a lot!

**Comment by Alex-302** [comment]
> "@@||i2.bahamut.com.tw/JS/ad/animeVideo.js^$domain=ani.gamer.com.tw"

added. It's enough?

**Comment by lancelot-moon** [comment]
Hi,
"@@||i2.bahamut.com.tw/JS/ad/animeVideo.js^$domain=ani.gamer.com.tw" was just added in English filter v1.1.39.9.

Now, the anime can be normally played on Mobile browser.
Google Chrome on Android:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/9es0GWj.png)
</details><br/>


I already enabled Annoyances filter or EasyList China filter for hiding the 2nd anti-adblock message.
The 1st anti-adblock message was hidden on Google chrome on Windows PC.
But it's strange that it still appears on  Google chrome on Android.
Is it possible to solve it?
Google Chrome on Android:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/CUQJOdJ.png)
</details><br/>

**Comment by Alex-302** [comment]
> Is it possible to hide it?

please upload saved page. I will try to make a rule.

**Comment by lancelot-moon** [comment]
Here, thanks!
https://app.box.com/s/13tfp5gdwdj8i7fg1xfok3penhrl3gzc

**Comment by Alex-302** [comment]
please check
`bahamut.com.tw#@#.afs_ads`

**Comment by lancelot-moon** [comment]
> bahamut.com.tw#@#.afs_ads

It's useless.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/N3jl5Q3.png)
</details><br/>

**Comment by Alex-302** [comment]
strange. It should prevent `alert` message. Try
`ani.gamer.com.tw#@#.afs_ads`
or
`@@||ani.gamer.com.tw^$generichide`

**Comment by lancelot-moon** [comment]
You got it!!!
You're the superman. <3
I suggest that you add the rule "@@||ani.gamer.com.tw^$generichide" in filter.
Will you add it in English filter or Annoyances filter?

The below are the results with different conditions.

English filter + Annoyances filter:
1st anti-adblock message.
No 2nd anti-adblock message.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/sYWhuMg.png)
</details><br/>

But the 2nd anti-adblock message is NOT hidden in the page.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/izanvbz.png)
</details><br/>

English filter + EasyList China filter:
1st anti-adblock message.
No 2nd anti-adblock message.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ScHwMgw.png)
</details><br/>

No 2nd anti-adblock message.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/9V3AK5k.png)
</details><br/>

English filter + ani.gamer.com.tw#@#.afs_ads:
No 1st anti-adblock message!
2nd anti-adblock message.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/iutT2L3.png)
</details><br/>

2nd anti-adblock message.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/qnR7w60.png)
</details><br/>

English filter + @@||ani.gamer.com.tw^$generichide:
No 1st and 2nd anti-adblock message!
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/IoFqpWB.png)
</details><br/>

No 2nd anti-adblock message!
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/YkpVHtX.png)
</details><br/>

**Comment by lancelot-moon** [comment]
We have solved the 1st and 2nd problem.
Can you solve the 3rd problem?
But this is maybe very difficult...
> We must wait until the counting backwards of an ad video is finished, and then it starts to play what we want to watch.
May you block an ad video and pass it when playing anime from the beginning?

<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/9kMA2aF.png)
</details><br/>

**Comment by Alex-302** [comment]
Which rule should be added `ani.gamer.com.tw#@#.afs_ads` or `@@||ani.gamer.com.tw^$generichide`?

**Comment by lancelot-moon** [comment]
@@||ani.gamer.com.tw^$generichide

**Comment by Alex-302** [comment]
added to English

**Comment by lancelot-moon** [comment]
@ameshkov 
@Alex-302 

Hi,
ani.gamer.com.tw recently knew that AdGuard updated the rules for solving anti-adblock.
Anime on ani.gamer.com.tw can't be played again if enabling Mobile ads filter.
https://github.com/AdguardTeam/AdguardFilters/issues/1742
This rule, ||bahamut.com.tw/JS/ad/, affects too much, which blocks everything under the path.
I don't know if it's better to remove ||bahamut.com.tw/JS/ad/ from Mobile ads filter.

Now, we need to additionally add the new rule for normally watching anime on ani.gamer.com.tw:
@@||i2.bahamut.com.tw/JS/ad/animeLogo.js^$domain=ani.gamer.com.tw

**Comment by Alex-302** [comment]
Added
`@@||i2.bahamut.com.tw/JS/ad/animeLogo.js^$domain=ani.gamer.com.tw`

**Comment by lancelot-moon** [comment]
Hi, thanks!
Although we can add new rules for unblocking some anti-adblock JS,  the rule, ||bahamut.com.tw/JS/ad/, in Mobile ads filter blocks everything under that ad path.
This time, we solved the anti-adblock on ani.gamer.com.tw.
However, next time, ani.gamer.com.tw maybe uses other anti-adblock JS under that ad path, which lets us need to frequently add new rules.

The ads in 巴哈姆特 app can be blocked by the rule syntax in English filter.
https://github.com/AdguardTeam/AdguardFilters/issues/8000#issuecomment-349012184
This rule, ||bahamut.com.tw/JS/ad/, is unnecessary.
So I think that removing ||bahamut.com.tw/JS/ad/ from Mobile ads filter is better.

**Comment by Alex-302** [comment]
> ||bahamut.com.tw/JS/ad/

removed
