### ISSUE TITLE
soundcloud.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7598]
**Site Sample** | 
----|
https://soundcloud.com/anjunadeep/sets/the-anjunadeep-edition

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.433.2167**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue
- player playlist entries are missing 

![20171112-133850-001](https://user-images.githubusercontent.com/9846948/32699005-04283f0c-c7af-11e7-94d9-85fadff162fb.png)
![20171112-133905-001](https://user-images.githubusercontent.com/9846948/32699006-044862d2-c7af-11e7-88d4-bbe7c32346e7.png)

**Comment by Alex-302** [comment]
can't reproduce

**Comment by FadeMind** [comment]
Chrome Cache issue.
