### ISSUE TITLE
[adblock detect, popup] player.pl

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7602]
**Site Sample** | 
----|
https://player.pl/programy-online/mam-talent-odcinki,50/odcinek-10,S10E10,81193.html

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.433.2167**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

![20171112-164934-001](https://user-images.githubusercontent.com/9846948/32700740-809a727a-c7c9-11e7-92e3-a902541fd20c.png)

@AdamWr

**Comment by AdamWr** [comment]
U mnie działa.
Może jakieś inne rozszerzenie powoduje problem?

**Comment by FadeMind** [comment]
@AdamWr dodałem do białej listy, uruchomiłem odtwarzanie (reklamy), zamknąłem kartę w przeglądarce, usunąłem regułę z białej listy i odtwarza się teraz normalnie bez reklamy, Nie mam pojęcia o co chodzi :D 
Chrome dostaje czasami zadyszki widocznie. Pozdrawiam.
