### ISSUE TITLE
Frogwares.com broken if AdGuard Annoyances is enabled

### ISSUE THREAD

**Issue by WizardShotTheFood** [AdguardTeam/AdguardFilters#76062]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: Frogwares.com CSS is broken due to GDPR filter entry
* **Current behaviour**: 

The "/cookie-law-$stylesheet" part of the AdGuard Annoyances filter is causing Frogwares.com to render incorrectly. It appears that this due to the site using the Better WordPress Minify WordPress plugin to combine multiple CSS files into one: one of those files is named "cookie-law-info-public.css", as shown in the following screenshots.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshost:</summary>

![image](https://user-images.githubusercontent.com/4625609/109406235-81a96a00-7945-11eb-88da-3d9689355865.png)

![image](https://user-images.githubusercontent.com/4625609/109406319-08f6dd80-7946-11eb-9fc5-9d2ee752187c.png)

</details><br/>

* **Expected behaviour**: 

See screenshot.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/4625609/109406254-aa316400-7945-11eb-8a99-2337fe1e64f0.png)
</details><br/>

***Steps to reproduce the problem***:

1: Load frogwares.com in Chrome with the uBlock Origin browser extension enabled and configured to use the AdGuard Annoyances filter.

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      |  Windows 10
Browser:                               |  Chrome
Filters enabled:                       |  AdGuard Annoyances

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
