### ISSUE TITLE
remont-shvejnyh-mashin.com - Anti-Adblock script

### ISSUE THREAD

**Issue by vitalkanev** [AdguardTeam/AdguardFilters#7610]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Page***: www.remont-shvejnyh-mashin.com/швейная-машина-чайка-142-м-чайка-143-подольск-142-подольск-144-а-пмз
***Description***: The Anti-Adblock banner shown at the top of the page

<details><summary>Screenshot:</summary>

![default](https://user-images.githubusercontent.com/18398761/32736936-c501525e-c8a9-11e7-963d-e565d7b7dbb3.png)

</details><br/>

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Ubuntu Artful
Browser:                               | Firefox 56
AdGuard version:                       | 2.7.3
Filters enabled:                       | English, Russian, Annoyances, German, RU AdList
Helpdesk ID (if exists):               | `undefined`

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
