### ISSUE TITLE
66.ru - won't open with Adg running

### ISSUE THREAD

**Issue by vitbortnik** [AdguardTeam/AdguardFilters#7611]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/30041399/32741532-33dc4b48-c8af-11e7-8bfc-6468a96b6524.png)

</details><br/>

***Steps to reproduce the problem***:

[https://66.ru/](https://66.ru/l)

***System configuration***

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Win/Mac
Browser:                               | Chrome
AdGuard version:                       | 6.2.433.2167/1.5
Filters enabled:                       | 1, 2, 3, 4, 14
Helpdesk ID:               | 1066943

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Temporary solution - add this domain to https exclusions and restart browser.
