### ISSUE TITLE
[NSFW] its.porn

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#76110]
NOTE: Your creator does not accept this URL in report wizard. @ameshkov 

![20210228-1614512378-001](https://user-images.githubusercontent.com/9846948/109417013-09cd5500-79c2-11eb-8ebb-f62a47de207d.png)

### Issue URL (Ads)
[NSFW]https://www.its.porn/video/uncensored-amateur-jav-hardcore-sex-action/

### Comment
POPUP AD goes to FULL SCREEN automatically before main video. Click play on player for start. 

### [NSFW] Screenshots
[20210228-1614511991-001](https://user-images.githubusercontent.com/9846948/109416982-e0acc480-79c1-11eb-8a6c-1c5991d3a77a.png)

### System configuration
Information	value
AdGuard product:	AdGuard Browser extension v3.5.31
Browser:	Chrome
Filters:	Ad Blocking:
AdGuard Base,
Peter Lowe's Blocklist

Privacy:
AdGuard Tracking Protection

Social Widgets:
AdGuard Social Media

Annoyances:
AdGuard Annoyances,
Adblock Warning Removal List,
I don't care about cookies

Security:
Online Malicious URL Blocklist

Language-specific:
Official Polish filters for AdBlock, uBlock Origin & AdGuard,
Polish GDPR-Cookies Filters,
KAD - Anti-Scam,
Polish Anti Adblock Filters,
AlleBlock

**Comment by FadeMind** [comment]
@Alex-302

**Comment by ameshkov** [comment]
@slavaleleka could you please check if this issue fixed with the new server-side validation code? In theory, it should be.

**Comment by FadeMind** [comment]
@ameshkov URL validation seems to be fixed. Checked while ago.
