### ISSUE TITLE
AfreecaTV issues

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardFilters#76143]
***Description***:
App: https://apps.apple.com/us/app/afreecatv-%EC%95%84%ED%94%84%EB%A6%AC%EC%B9%B4tv/id334185830

* **Current behaviour**: 

Ads are not blocked. Chat is not working.

<details><summary>Screenshot:</summary>

available in ticket 3226045</details><br/>

***Steps to reproduce the problem***:

Install the app and try to open a stream
***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | iOS
Operating system version (Android/iOS) | 14.4
Browser:                               | n/a
AdGuard version:                       | AdGuard DNS only 
AdGuard DNS:                           | Default (iOS 14 encrypted configuration)
Helpdesk ID (if exists):               | 3226045

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Cannot be blocked on iOS.
