### ISSUE TITLE
[nsfw] https://frprn.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7619]
**Site Sample** | 
----|
https://frprn.com/videos/12317/

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.433.2167**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`
### Issue:

Blue overlaybox ad leftover:

![20171114-111822-001](https://user-images.githubusercontent.com/9846948/32774743-8dfee2e2-c92d-11e7-8b2b-6eba2922832f.png)

### Fix
```
frprn.com##.spot-player-holder
```

**Comment by Alex-302** [comment]
Added

**Comment by Nzzyme** [comment]
https://frprn.com/videos/4115/

Fake links

https://prnt.sc/qcl0xb

**Comment by Alex-302** [comment]
ok
