### ISSUE TITLE
Login Option is missing and removed from  http://www.G2A.com

### ISSUE THREAD

**Issue by confessor-adguard** [AdguardTeam/AdguardFilters#762]
http://forum.adguard.com/showthread.php?6873-Adguard-for-Windows-Beta-version-6-0-67-364&p=60753&viewfull=1#post60753

**Comment by Alex-302** [comment]
Broken by Adguard injections. With disabled all filters and extension only this rule helps
@@||g2a.com^$elemhide,jsinject
