### ISSUE TITLE
puzzceworkdistkebur.tk badware

### ISSUE THREAD

**Issue by JobcenterTycoon** [AdguardTeam/AdguardFilters#76201]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: click on the yellow button it redirects to badware crap `http://mediazlez.pp.ua/d/nEDt2mkU17`

For me the badware is coming from `puzzceworkdistkebur.tk` so this domain need to be blocked. I think the domain `walhalagame.fun` need to be blocked too because its only provide fake downloads
* **Current behaviour**:  

[//]: # (Substitute this line with a description of the problem)

***Steps to reproduce the problem***:

click on the yellow button. Now you will get redirected to a download link with malware download.

Virustotal scan: `https://www.virustotal.com/gui/file/afa45ed317b277c3a16b4f47c48c20a370089b8187d9cdcadfcea1baf9933a03/detection`

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Firefox developer
AdGuard version:                       | 3.5.31
Filters enabled:                       | Default + Adguard tracking protection + Adguard annoyances + Adguard germany + phishing and malware protection enabled
AdGuard DNS:                           | None

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by JobcenterTycoon** [comment]
More: `http://failsame.ru/file/7b289e` redirects to `suzamense.com` and `sevenonex.space` with badware

**Comment by Alex-302** [comment]
Never visit sites, hosted on `pp.ua`:) It is like bulletproof hosthing.

**Comment by JobcenterTycoon** [comment]
Yes now i know the domains are random (changed daily)

But `mediazlez.pp.ua` and `walhalagame.fun` are not random and its effective to block this. Im tried a few downloads but all redirect to the same badware files. Im searched but i don't saw any legitimate link on these 2 sites.

**Comment by lolka4toli** [comment]
Blacklisted.

**Comment by JobcenterTycoon** [comment]
I have more very suspect domains (stable - exist over multiply weeks).

`https://zhirhacks.pro/fortnite` or `https://zhirhacks.pro/csgo` or `https://zhirhacks.pro/overwatch` redirect to mega.nz sites with malware downloads. I already reportet many domains to mega.nz but they get nearly every day a new mega.nz domain. They protect the zip with a password to avoid antivirus detection and putting the password (simple passwords like 1234 or 1111) under the download link

`https://nemosiau.icu/wCKsn5` same as above ... this site have no main site (just redirect to google) so its looks like they just use the domain to redirect to malware crap

`https://fortniteswapper.fun` link to malware downloads. First they used mega.nz but now they use another file hoster without fast malware file deletion

`http://injectx.online/` redirector

`https://app-inject.com/` just redirect to ads and scam (the complete spectrum ... fake captchas, fake giveaway, hundrets of redirects, ...)
