### ISSUE TITLE
facebook ads ( l9j0dhe7 )

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#76330]
![image](https://user-images.githubusercontent.com/75058881/109622005-96207900-7b76-11eb-81d1-06366c11624b.png)

`facebook.com###mount_0_0_v0 > div:nth-child(2) > div:first-child > div.rq0escxv.l9j0dhe7.du4w35lb > div.rq0escxv.l9j0dhe7.du4w35lb:nth-child(6) > div.du4w35lb.l9j0dhe7.cbu4d94t.j83agx80 > div.j83agx80.cbu4d94t.l9j0dhe7.jgljxmt5.be9z9djy > div.j83agx80.cbu4d94t.d6urw2fd.dp1hu0rb.l9j0dhe7.du4w35lb:first-child > div.rq0escxv.l9j0dhe7.du4w35lb.j83agx80.pfnyh3mw.taijpn5t.gs1a9yip.owycx6da.btwxx1t3.dp1hu0rb.p01isnhg:first-child > div.rq0escxv.l9j0dhe7.du4w35lb.j83agx80.g5gj957u.rj1gh0hx.buofh1pr.hpfvmrgz.i1fnvgqd.ll8tlv6m.owycx6da.btwxx1t3.ho3ac9xt.dp1hu0rb.msh19ytf > div.rq0escxv.lpgh02oy.du4w35lb.o387gat7.qbu88020.pad24vr5.rirtxc74.dp1hu0rb.fer614ym.ni8dbmo4.stjgntxs.be9z9djy.hlyrhctz:last-child > div.rq0escxv.l9j0dhe7.du4w35lb.j83agx80.cbu4d94t.qowsmv63.dp1hu0rb > div.q5bimw55.rpm2j7zs.k7i0oixp.gvuykj2m.j83agx80.cbu4d94t.ni8dbmo4.eg9m0zos.l9j0dhe7.du4w35lb.ofs802cu.pohlnb88.dkue75c7.mb9wzai9.d8ncny3e.buofh1pr.g5gj957u.tgvbjcpo.l56l04vs.r57mb794.kh7kg01d.c3g1iek1.k4xni2cv > div.j83agx80.cbu4d94t.buofh1pr.l9j0dhe7:first-child > div.cxgpxx05:nth-child(2) > div:first-child > span:first-child > div`

**Comment by krystian3w** [comment]
Maybe this is outdated: https://github.com/AdguardTeam/AdguardFilters/blob/e5a002e5b2273d38268e753b0db030455b5876e5/EnglishFilter/sections/css_extended.txt#L184

**Comment by Yuki2718** [comment]
@c2xusnpq6  Auto-generated code of "Block ads" like this doesn't help, but capturing DOM nodes i.e. right-click on the ads and choose Inspect may help.
