### ISSUE TITLE
http://www.walking-dead.ru - false blocking

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7635]
Unable to play movies, playback won't start unless you turn AdGuard off. The site: http://www.walking-dead.ru/download/8-sezon-3-seriya.html

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32853448-017678c2-ca44-11e7-9dd6-23ef39348c3c.png)

</details>

### Customer ID 
1066666

### Your environment

* Adguard version: AdGuard for Mac 1.5.0
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off

**Comment by Alex-302** [comment]
Does it work without AdGuard? On my end - not.
