### ISSUE TITLE
BlockAdblock 

### ISSUE THREAD

**Issue by 89z** [AdguardTeam/AdguardFilters#76365]
> Hey!
>
> So... you're blocking ads. We don't work for free. And we work hard to make this place awesome.
>
> This site is ad supported. Please understand that we need your help to keep us around. Please whitelist us.
>
> Cool with me. You're white-listed. Let's go!

https://www.yogurk.com/2018/11/pizzicato-five-on-her-majesty-request_9.html

**Comment by 89z** [comment]
looks like this fixes it

~~~
yogurk.com##+js(nosiif, visibility, 1000)
~~~

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/76375
