### ISSUE TITLE
E*TRADE mobile app

### ISSUE THREAD

**Issue by BlackNet** [AdguardTeam/AdguardFilters#76374]
E*TRADE mobile app crashes with AdGuard and vpn enabled. 

Should have some method to exclude apps and not just the silly “exclude url” method.

**Comment by Alex-302** [comment]
Please provide download link.

**Comment by BlackNet** [comment]
What download link?  

__________________
Ed Street
Street-Tek, INC

Cell: (706) 718-3883
ed@street-tek.com

**Comment by krystian3w** [comment]
to app `E*TRADE mobile app` in Google Play Store / AppGallery / iOS store / Samsung Galaxy Store.

**Comment by Alex-302** [comment]
@BlackNet When it crashes? On my devise it works.


> Should have some method to exclude apps and not just the silly “exclude url” method.

You can disable filtering for this app in Apps Management.
