### ISSUE TITLE
reverse image search on bing.com breakage due to ||bing.com/fd/ls/ in Adguard Tracking Protection

### ISSUE THREAD

**Issue by crssi** [AdguardTeam/AdguardFilters#76395]
Steps to reproduce:

1. Visit `https://www.bing.com/visualsearch`
2. Click any sample image or upload image of your choice
3. Scroll a bit the right side of the results page.
4. Stop scrolling and wait for about 8-10 seconds

Result: Almost the whole page goes blank.

The culprit is the rule `||bing.com/fd/ls/` in `Adguard Tracking Protection` filterlist.

Cheers

**Comment by Alex-302** [comment]
@crssi Which broser and AdGuard? I cannot reproduce in Chrome with app or extension.

**Comment by crssi** [comment]
Oh. Sorry that I have not been thorough.
It is Firefox 86, Windows 10, and uBlock Origin 1.33.2.
The list is included in uBO distibution with the name `AdGuard Tracking Protection`.

Let me know if more info is needed.
Maybe I missed something and this is not the place to report such. In that case, please, take my apologies.

Cheers

**Comment by Alex-302** [comment]
@crssi Hi. I cannot reproduce with the same settings
![image](https://user-images.githubusercontent.com/8361299/110341349-e85c1100-8032-11eb-9f92-25f4fe4ec248.png)


Do you see any new errors in console, when that rule is enabled?

**Comment by Alex-302** [comment]
@AdguardTeam/filters-maintainers please take a look.

**Comment by zloyden** [comment]
> Hi. I cannot reproduce with the same settings

Also not reproduced on my end.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/110439372-6dddd080-80c8-11eb-957b-1cef3cd4f9fb.png)

</details><br/>

**Comment by crssi** [comment]
I am sorry I haven't responded before, I had no means for testing (computer malfunction).
I have retested now... the missing piece of info is that in my profile I have disabled `beacons`.
In Firefox visit the `about:config`, search for `beacon.enabled` and switch it to `false`.

Repeat the STR in original posting and you will for sure reproduce the problem.

Once again, I am sorry to respond lately.

Cheers

**Comment by zloyden** [comment]
> In Firefox visit the `about:config`, search for `beacon.enabled` and switch it to `false`

Thanks for the explanation, but I don't think that we should add rules in this case - it's not a default state of browser.
Add `@@||bing.com/fd/ls/lsp.aspx$xhr,domain=bing.com` to `My filters`.

**Comment by crssi** [comment]
I did that exactly when opened the ticket.

But anyway, thank you for all your work. <3

**Comment by Yuki2718** [comment]
I fixed this by https://github.com/AdguardTeam/AdguardFilters/commit/fed92d8bcecf7d59481863eb88903fc3ebdf24df as can be fixed without whitelist. See https://github.com/easylist/easylist/issues/7240#issuecomment-798908299

**Comment by crssi** [comment]
Thank you 😄
