### ISSUE TITLE
True caller app

### ISSUE THREAD

**Issue by balaaje** [AdguardTeam/AdguardFilters#76397]
Ads in true caller is not blocked especially during overlay after the call

**Comment by Alex-302** [comment]
Which OS, AdGuard? Please make screenshot.

**Comment by balaaje** [comment]
This is the filtering rule I applied and it blocked the ads in true caller
overlay

||graph.facebook.com^$app=com.truecaller

Os: Android 11 oxygen os

**Comment by balaaje** [comment]
Here is the attachment

**Comment by Alex-302** [comment]
Ok, added.
