### ISSUE TITLE
valenciaplaza.com

### ISSUE THREAD

**Issue by logos88** [AdguardTeam/AdguardFilters#76399]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***: [https://valenciaplaza.com](https://valenciaplaza.com)
* **Current behaviour**: 

There is still an ad at the top of the webpage with AdGuard Spanish/Portuguese activated in uBlock in firefox.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/nfdL8Y7.png)
</details><br/>

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
