### ISSUE TITLE
Adguard problem with premid

### ISSUE THREAD

**Issue by Aushro** [AdguardTeam/AdguardFilters#76407]
https://shinden.pl/episode/11-naruto/view/507#column-one-inner
When I click show (pokaż) nothing happen. But when I disable adguard or premid everything work correctly.

**Comment by krystian3w** [comment]
What tribe of instalation you using for AdGuard and  PreMiD:

- AdGuard Addon + PreMiD addon
   - AdGuard Addon + PreMiD App
- AdGuard App + PreMiD App
   - AdGuard App + PreMiD addon

> addon = extension for browser

---

I suppose AdamWr no use json-prune do defuse anti-adblock on `shinden.pl` (EasyTube can break use `json-prune` on YouTube).

**Comment by Alex-302** [comment]
@AdamWr please take a look.

**Comment by AdamWr** [comment]
What exactly is "premid"?
Please write steps how to reproduce this issue.

**Comment by Aushro** [comment]
> What mode of instalation you using for AdGuard and PreMiD:
> 
> * AdGuard Addon + PreMiD addon
>   
>   * AdGuard Addon + PreMiD App
> * AdGuard App + PreMiD App
>   
>   * AdGuard App + PreMiD addon
> 
> > addon = extension for browser
> 
> I suppose AdamWr no use json-prune do defuse anti-adblock on `shinden.pl` (EasyTube can break use `json-prune` on YouTube).

Sorry for late ressponse. I'm using AdGuard addon not app. 



> What exactly is "premid"?
> Please write steps how to reproduce this issue.

By "premid" I mean this application: https://premid.app. 
Sometimes it work when I refresh page about 3-5 times but in other case I can't use page correctly.

**Comment by AdamWr** [comment]
Okay, I installed this app and extension, but unfortunately I can't reproduce this issue ("Pokaż" button works fine every time on my side).
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/110454249-4d614680-80c7-11eb-9962-8459f567a30d.png)

</details>

Do I need to configure this app somehow?
By the way, what filter lists you have enabled in AdGuard settings?

**Comment by Aushro** [comment]
![image](https://user-images.githubusercontent.com/45536666/110457240-b72f1f80-80ca-11eb-9ac4-7196b893cec9.png)

**Comment by krystian3w** [comment]
So this need use AnyDesk to test?

**Comment by AdamWr** [comment]
Could you please disable all filter lists and then check if issue still occurs?

**Comment by Aushro** [comment]
No, without any filter everything work correct.

**Comment by AdamWr** [comment]
Could you please enable filters again, one by one and check which one causes that issue?

**Comment by Aushro** [comment]
### ![image](https://user-images.githubusercontent.com/45536666/110460004-f317b400-80cd-11eb-9f94-c0f0281e5ced.png)

**Comment by krystian3w** [comment]
Spróbuj może z uruchomioną tylko listą "podstawowy filtr AdGuard" (sekcja blokowanie reklam).

Jak masz tam jakieś dodatkowe to one może magicznie wchodzą w interakcje z dodatkiem/aplikacją PreMiD?

---

Niby opisywanie problemu po polsku jest dozwolone jak ma to uławić walkę z barierami w języku angielskim.

**Comment by Aushro** [comment]
Wciąż nie działa poprawnie.

**Comment by AdamWr** [comment]
Nie mam pojęcia dlaczego tak się dzieje, u mnie z tymi samymi listami filtrów problem nie występuje.
Jeśli problem sprawia "Podstawowy filtr AdGuard", to możesz go włączyć, wyłączyć inne filtry, otworzyć dziennik filtrowania (ikonka AdGuarda > otwórz dziennik filtrowania, jak na obrazku poniżej) i spróbować wyłączyć ("odblokować") każdą regułę.

<details><summary>Obrazek dziennik filtrowania</summary>

![image](https://user-images.githubusercontent.com/29142494/110461463-c06ebb00-80cf-11eb-8021-3d2316f234d2.png)

</details>

Najpierw kliknij na jakieś żądanie/regułę, a potem przycisk odblokuj.
<details><summary>Obrazek</summary>

![image](https://user-images.githubusercontent.com/29142494/110461833-3e32c680-80d0-11eb-9e96-4f6f60a20820.png)

</details>
