### ISSUE TITLE
thesopranos.legio.in - Pre-roll Ad

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7646]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

http://thesopranos.legio.in/semya-soprano-5-sezon-6-seriya/

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/32867367-704a3a96-ca75-11e7-889b-8c3d73b7d375.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.36.21 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.38 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.25.9 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.20.94 Enabled=YES
ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.22 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.59.73 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.75 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.90.92 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | iOS
Browser:                               | Safari
AdGuard version:                       | 1.3.1.82
Simplified filters (iOS only)          | Off
Helpdesk ID (if exists):               | 1666811

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce on iOS 10.3.3

**Comment by Alex-302** [comment]
Please check these rules:
```
||moonwalk.cc/*.xml|
||moonwalk.center/*.xml|
moonwalk.cc,moonwalk.center##div[id^="adv_player"]
/vast.xml$domain=moonwalk.cc|moonwalk.center
```
