### ISSUE TITLE
Trivia Crack - Malicious website pop-up

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7647]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

False malware alerts on game Trivia Crack
URL to the pop up
http://us.3zs0.date/amz/amz.php?brand=Apple&model=iPhone&ip=208.73.102.53&city=Minneapolis&browser=Mobile%20Safari&os=IOS&osversion=IOS%2011.1&browserversion=Mobile%20Safari%2011&isp=US%20Internet%20Corp#
 

Game here --> https://itunes.apple.com/us/app/trivia-crack/id651510680?mt=8

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/32872454-76215cdc-ca8f-11e7-9689-b7d1b70e21c8.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.35.91 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.35 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.25.2 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.20.84 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.75 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | iOS
Operating system version | 11.1.1
AdGuard version:                       | 1.3.1.82
Simplified filters (iOS only)          | On 
Helpdesk ID (if exists):               | 1665816

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Can't reproduce. When it happens?
Blocked
```
us.3zs0.date
```

**Comment by Alex-302** [comment]
@altokarev

**Comment by evgeniy-ADG** [comment]
Our glitch, he's on a free version, does not use the system-wide ad blocking. Will contact the customer.
