### ISSUE TITLE
korrespondent.net

### ISSUE THREAD

**Issue by alvussar** [AdguardTeam/AdguardFilters#7648]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![photo_2017-11-15_13-51-17](https://user-images.githubusercontent.com/26434853/32877278-63f755b0-caa9-11e7-9838-719abcabba29.jpg)
</details><br/>

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 8.0.0
Browser:                               | Chrome 62.0.3202.84
AdGuard version:                       | 2.10.164
Filters enabled:                       | "English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Filter unblocking useful ads", "Russian filter", "Mobile Ads filter"
AdGuard mode (Android only):           | VPN 
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default) 

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by altokarev** [comment]
Confirm:
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/28726429/32886255-2fd779cc-cad1-11e7-8718-603d3fe48a2f.png)

</details>

**Comment by Alex-302** [comment]
This rule is not working
```
||piguiqproxy.com^$third-party,xmlhttprequest
```
AdGuard can't recognize xmlhttprequest
Changed to `||piguiqproxy.com^$third-party`
