### ISSUE TITLE
[NSFW] https://xkeezmovies.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7650]
**Site Sample** | 
----|
https://xkeezmovies.com

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.433.2167**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Popups, redirect after click on random category/video etc.

<details><summary><b>Screenshot:</b></summary>

![20171116-144040-001](https://user-images.githubusercontent.com/9846948/32894130-2dad2bbe-cadc-11e7-83be-593bfa7c0cf5.png)
</details><br/>

**Comment by Alex-302** [comment]
fixed.
