### ISSUE TITLE
otzovik.com - Missed Ad

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7652]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

http://otzovik.com/reviews/gotoviy_obed_rossiyskaya_korona_zharkoe_po-domashnemu/

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/32895555-1ec258f6-cae9-11e7-8949-271131296676.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.36.33 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.40 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.25.9 Enabled=YES
ID=14 Name="Annoyances filter" Version=1.0.20.94 Enabled=YES
ID=10 Name="Filter unblocking search ads and self-promotion" Version=1.0.1.22 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.59.77 Enabled=YES
ID=11 Name="Mobile Ads filter" Version=1.0.10.46 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.76 Enabled=YES
ID=207 Name="Adblock Warning Removal List" Version=1.0.91.4 Enabled=YES
ID=211 Name="Anti-Adblock Killer | Reek" Version=1.0.1.69 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | iOS 
Operating system version (Android/iOS) | 11.1
Browser:                               | Safari
AdGuard version:                       | 1.3.1.82
Simplified filters (iOS only)          | Off
Helpdesk ID (if exists):               | 1633647

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
На iOS с ней ничего особо не поделаешь. Но вроде поправил.
