### ISSUE TITLE
ads in yandex search

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7654]
> В Chrome в режиме инкогнито задал запрос «услуги бухгалтера» рекламы нет. Появилось окно с вопросом от «Яндекса». Яндекс запрашивает ваше местоположение я согласился. После этого появилась реклама и если вновь запускаешь окно инкогнито от рекламы отделаться невозможно.

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32896274-3cb08d7c-caeb-11e7-818d-dcc262ad04e5.png)

</details>

### Your environment

* Os version: Microsoft Windows NT 6.1.7601 Service Pack 1
* AdGuard 6.2.433.2167
* TDI
* Yandex and Chrome browsers, reproducible in the Incognito
* HTTPS: True
* Subscriptions: Russian, English, Spyware, Social media
* Stealth mode

<details> 
Stealth Mode enabled: StealthModeSettings: {
  "BlockThirdPartyCookies": true,
  "BlockThirdPartyCookiesPeriodMin": 30,
  "BlockFirstPartyCookies": false,
  "BlockFirstPartyCookiesMin": 2880,
  "DisableThirdPartyCache": false,
  "BlockWebRtc": false,
  "BlockBrowserPushApi": false,
  "BlockBrowserLocationApi": true,
  "BlockBrowserFlash": false,
  "BlockBrowserJava": false,
  "RemoveXClientDataHeader": true,
  "StripUrl": false,
  "HideSearchQueries": true,
  "SendDoNotTrackHeader": true,
  "RemoveReferrerFromThirdPartyRequests": false,
  "HideUserAgent": false,
  "CustomUserAgent": null,
  "CustomReferrer": null,
  "HideIp": false,
  "CustomIp": "209.141.53.254",
  "BlockThirdPartyAuthorization": false
</details>

**Comment by Alex-302** [comment]
здесь закрою.
