### ISSUE TITLE
NSFW - pejnya.net - Missed Ad

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7655]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Missed Ad
http://pejnya.net/content/photo.php?news=podb_chastnih_ero_photo_653

После добавления в правила... прозрачное плавающее по всему экрану окно

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/32898452-e02f4a56-caf0-11e7-8da9-8a1714e3aa82.png)

</details><br/>

**Filters:**

ID=0 Name="User filter" Version=1.0.0.0 Enabled=YES
ID=2 Name="English filter" Version=1.1.36.38 Enabled=YES
ID=3 Name="Spyware filter" Version=1.0.15.41 Enabled=YES
ID=4 Name="Social media filter" Version=1.0.25.10 Enabled=YES
ID=1 Name="Russian filter" Version=1.0.59.82 Enabled=YES
ID=12 Name="Safari filter" Version=1.0.3.76 Enabled=YES

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | iOS
Operating system version (Android/iOS) | 11.0.2
Browser:                               | Safari
AdGuard version:                       | 1.3.2.108 
Simplified filters (iOS only)          | Off
AdGuard DNS:                           | None 
Helpdesk ID (if exists):               | 1668222

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Fixed.
