### ISSUE TITLE
Google Hangouts - not loading

### ISSUE THREAD

**Issue by iverkhohliad** [AdguardTeam/AdguardFilters#7657]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

 Hangouts loads in a pop-up window & never goes past the
loading page. Disable Adguard popup blocker extension, Hangouts loads
normally. 

Steps to reproduce:

Launch Chrome with Hangouts extension installed, it does not load. Hangouts runs as a background app. 
Completely exit Chrome as to unload Hangouts. Disable all Adblocking, Stealth Mode, & all Extensions/Filters except Popup Blocker. 
Launch Chrome, Hangouts is still broken. Disable Popup Blocker. 
Completely exit Chrome as to unload Hangouts. Launch Chrome, Hangouts works

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/31481372/32905140-d044c11e-cb01-11e7-8b38-3522ce90a271.png)

![image](https://user-images.githubusercontent.com/31481372/32905149-d4a03af4-cb01-11e7-83d8-d6d950c40637.png)

![image](https://user-images.githubusercontent.com/31481372/32905156-d9567ab8-cb01-11e7-8b98-82c4599a213c.png)

![image](https://user-images.githubusercontent.com/31481372/32905168-df499d7e-cb01-11e7-86b7-d02463afafa6.png)

![image](https://user-images.githubusercontent.com/31481372/32905177-e9330f96-cb01-11e7-8095-dcca9c2fc793.png)

</details><br/>

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Browser:                               | Chrome
AdGuard version:                       | 6.2.431.2165
Stealth mode options (Windows only)    | enabled
Helpdesk ID (if exists):               | 1496574

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by iverkhohliad** [comment]
The same issue here 1446772
It was noticed that the problem is coming up when there is Pop up blocker extension enabled in Adguard extension.

**Comment by lazyb5** [comment]
I also notice the chrome extension connects when you start chrome. It's greyed out till it connects and has a blue connecting bar. THe takes much longer to complete and connect then usual. But also second that disabling pop blocker lets the page load.

**Comment by Alex-302** [comment]
It is PopupBlocker issue. Moved to https://github.com/AdguardTeam/PopupBlocker/issues/63

**Comment by ameshkov** [comment]
Guys, could you please re-test it now? We've just published popup blocker hotfix
