### ISSUE TITLE
www.dmhy.org

### ISSUE THREAD

**Issue by escape0707** [AdguardTeam/AdguardFilters#76580]
### Issue URL (Incorrect Blocking)

https://www.dmhy.org

Captcha can't be loaded.

### Screenshots

![image](https://user-images.githubusercontent.com/11014745/110047920-b7a57e80-7d89-11eb-83d3-8b025e09ddaa.png)

### How to reproduce

Go to the [login page](https://dmhy.org/user/login) and this can be easily reproduced.

Click on “換一張” hyperlink next to the last input field to trigger this blockage again.

Commenting on this site also requires passing a Captcha, so not only the login process is affected.

**Comment by Alex-302** [comment]
@escape0707 How to reproduce it?

**Comment by escape0707** [comment]
Thanks for your quick reply!

https://dmhy.org/user/login
Go to the login page and this will easily be reproduced.

**Comment by cjx82630** [comment]
Fixed 6ce9459d28a795f62e2bd7b1912304ef86018fd1

**Comment by Alex-302** [comment]
@escape0707 Synchronization is not instantaneous. You had to wait a couple(1-3) of hours before check for updates.
