### ISSUE TITLE
Incorrect blocking in geekland.eu

### ISSUE THREAD

**Issue by jccall80** [AdguardTeam/AdguardFilters#7660]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **The filter is looking images. The images are not adds. Are just standards images. The images are locked because contain the word "publicidad".**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details><br/>

* **Check the image to see that blocks incorrect URL  http://i.imgur.com/tDxgVWC.png**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***​​​​​When you active the filter Adguard Spanish/Portuguese in Ublock origin then Wrong URL are blocked***:

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | All, Windows, Linux, Mac OS X
Operating system version (Android/iOS) | All the versions
Browser:                               | All the browsers
AdGuard version:                       | ?
Filters enabled:                       | Adguard Spanish/Portuguese
AdGuard mode (Android only):           | VPN / Proxy (manual/auto)
Filtering quality (Android only):      | High-quality / High-speed / Simplified
HTTPS filtering (Android only):        | On (Default/Blacklist mode) / Off
Simplified filters (iOS only)          | On / Off
AdGuard DNS:                           | None / Default / Family Protection
Stealth mode options (Windows only)    | ?
Helpdesk ID (if exists):               | ?

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Added
`@@||geekland.eu/wp-content/uploads/*-publicidad-$image`
