### ISSUE TITLE
imasdk.googleapis.com (breaking rai.tv live)

### ISSUE THREAD

**Issue by FabioEight** [AdguardTeam/AdguardFilters#76648]
* **Expected behaviour**: 

Rai.Tv live tv streaming working properly on Android/Fire TV

***Steps to reproduce the problem***:

1. Install Rai.tv App from GStore/Amazon Store (https://www.raiplay.it/)

***System configuration***
Fire TV OS (FireStick)
**Filters:**
AdGuard Mobile Ads filter (via NextDNS)

Information                            | Value
---                                    | ---
Operating system:                      |  Fire OS
Operating system version (Android/iOS) | -
Browser:                               | None, Rai Play app
AdGuard version:                       | None, filter enabled on NextDNS
Filters enabled:                       | -
AdGuard DNS:                           | None 

I've been looking through the DNS queries executed by the Fire Stick while accessing the service (i.e. Rai 1 live streaming through Rai Play app), trying to whitelist all the hosts blocked one by one.
Once I whitelisted: imasdk.googleapis.com, immediately the Fire Stick was able to play the stream. Removing it from the whitelist cause the inability to start the stream. This is affecting only the Android app/service, since using the same app (same network/filters) on iOS doesn't cause any issue.

**Comment by krystian3w** [comment]
Maybe:

https://github.com/AdguardTeam/AdguardFilters/blob/075651a3a81e49e653198cea37892b4ddb652b28/MobileFilter/sections/adservers.txt#L786

But NextDNS should consider don't convert this into DNS rule - own NextDNS script also ban domains with used `$pop-up` and `$third-party`, when DNS can't detect pop-ups and what page generate request to load `third-party` resource.

**Comment by FabioEight** [comment]
> Maybe:
> 
> https://github.com/AdguardTeam/AdguardFilters/blob/075651a3a81e49e653198cea37892b4ddb652b28/MobileFilter/sections/adservers.txt#L786
> 
> But NextDNS should consider "don't convert this into DNS rule" - own NextDNS script also ban domains with used `$popup` and `$third-party`, then DNS can't detect pop-ups and what page generated request to load `third-party` resource.

Do you suggest to raise an issue to NextDNS as well?

**Comment by krystian3w** [comment]
Just as AdGuard states it will not fix this at the `FiltersRegistry` repository level (disable copy 1 rule from EasyList) and in `/MobileFilter/sections/adservers.txt` (if NextDNS also convert Filter "list" AdGuard Mobile Ads to DNS rules).

Origin rule is from EasyList project copied: https://github.com/easylist/easylist/blob/533bbecef6cbed74672031d79072eb05620ee0dc/easylist/easylist_adservers.txt#L12087 (I thing are not likely to remove it or rewrite it so that the NextDNS script no longer converts it).

**Comment by Alex-302** [comment]
Hi. We cannot remove this domain from DNS filter. It blocks ads on many sites.

**Comment by Alex-302** [comment]
But you can try AdGuard Home - it has filtering log and user filter, and you can block/unblock anything you want)
