### ISSUE TITLE
Ads in application Appy Geek – Tech news

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7664]
***Description***: Customer claims ads at startup of the application Appy Geek – Tech news

The app in PlayStore: https://play.google.com/store/apps/details?id=com.mobilesrepublic.appygeek

> Despite the update of the filters very regularly. AT
each opening of the application, an advertisement opens before the
full start of the application (at the beginning) The android application: Appy Geek.

* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![screenshot_20171028-140632](https://user-images.githubusercontent.com/32528702/32933567-0a1750de-cb73-11e7-9e66-68b4c21edd40.png)
![screenshot_20171028-140629](https://user-images.githubusercontent.com/32528702/32933568-0a322f94-cb73-11e7-8b9c-b48cb3f25464.png)

</details><br/>

***System configuration***
samsung SM-G950F

**Filters:**
"English filter", "Spyware filter", "Social media filter", "Annoyances filter", "Filter unblocking useful ads", "French filter", "Experimental filter", "Mobile Ads filter", "Liste FR"

[//]: # (Substitute this line with the list of your active filters, separated by commas)

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 7.0
AdGuard version:                       | 2.10.108
AdGuard mode (Android only):           | VPN
Filtering quality (Android only):      | High-quality
HTTPS filtering (Android only):        | On (Default)
Helpdesk ID (if exists):               | 1076052

**Comment by Alex-302** [comment]
Can't reproduce without AdGuard. Please ask for web-requests log.
@AdamWr please check on your end.

**Comment by AdamWr** [comment]
I also can't reproduce that ad (even without AdGuard).

**Comment by ashvets-sup** [comment]
web requests log provided
[1076052.txt](https://github.com/AdguardTeam/AdguardFilters/files/1496151/1076052.txt)

**Comment by Alex-302** [comment]
Send to user:
```
||itecdn.com/*/formats/recommandation/index.html$app=com.mobilesrepublic.appygeek
```

**Comment by ashvets-sup** [comment]
according to the user, adding  this rule to the user filter does not solve the issue.

**Comment by Alex-302** [comment]
Please ask for new log+HAR and actual screenshot.

**Comment by dzamyshlyayeva** [comment]
here are the screenshots, log+HAR
<details>

![image](https://user-images.githubusercontent.com/23372054/34100043-e6041756-e3e9-11e7-896f-7253fb82b851.png)

![image](https://user-images.githubusercontent.com/23372054/34100062-f75f961a-e3e9-11e7-945d-a678a24d4229.png)

</details>
[adguard (1).zip](https://github.com/AdguardTeam/AdguardFilters/files/1567364/adguard.1.zip)
[adguard.zip](https://github.com/AdguardTeam/AdguardFilters/files/1567365/adguard.zip)

**Comment by Alex-302** [comment]
I don't see useful information in HAR. Maybe it is too short.
Please close the app and record new HAR. Disable protection before you upload the file.

**Comment by veronikasav** [comment]
[adguard.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1573979/adguard.har.zip)
[adguard.har.1513701374082.har.zip](https://github.com/AdguardTeam/AdguardFilters/files/1573980/adguard.har.1513701374082.har.zip)

**Comment by Alex-302** [comment]
'Operating system version (Android/iOS) | 7.0`

user should to move cert to the system storage. Root access it required.
