### ISSUE TITLE
Update to Adguard Dutch / Sites doesn't exist

### ISSUE THREAD

**Issue by BPower0036** [AdguardTeam/AdguardFilters#76647]
https://github.com/AdguardTeam/AdguardFilters/blob/c546c714eb67ab4d4428c21761700315d0d464c8/DutchFilter/sections/adservers.txt#L5
This site doesn't exist. So it can delete from the list

And https://github.com/AdguardTeam/AdguardFilters/blob/c546c714eb67ab4d4428c21761700315d0d464c8/DutchFilter/sections/adservers.txt#L6
Is for sale so doesn't do anything and can also be deleted

**Comment by Yuki2718** [comment]
Confirmed.

**Comment by ameshkov** [comment]
Yep, can confirm
