### ISSUE TITLE
https://lanka.ru/ - anti-adblocker

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7665]
https://lanka.ru/sri-lanka/city/kandy/

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32935584-7c394734-cb79-11e7-95c3-21a8fe744f07.png)

</details>

### Customer ID 
1576150

### Your environment

* Adguard version: AdGuard for Mac 1.5.0
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off

**Comment by Alex-302** [comment]
fixed
