### ISSUE TITLE
Video ads on Naver TV

### ISSUE THREAD

**Issue by ashvets-sup** [AdguardTeam/AdguardFilters#7666]
***Description***: This site http://tv.naver.com has pre-rolls and mid-rolls
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![capt](https://user-images.githubusercontent.com/32528702/32935575-7255ab54-cb79-11e7-893b-315fad85cc2a.png)

</details><br/>

***Steps to reproduce the problem***:

Visit http://tv.naver.com/v/1797268
When video starts playing, there is a pre-roll not blocked by AdGuard.

[//]: # (Substitute this line with a step-by-step instruction how to reproduce the issue)

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10
Browser:                            | Chrome
AdGuard version:                    | 6.2.433.2167
Filters enabled:                    | 2, 3, 4, 5, 10, 11, 101, 104, 109, 118, 121, 203, 207, 208, 211, 214, 215, 216, 14, 224, 225, 227, 229
Helpdesk ID (if exists):            | 1663986

**Comment by Alex-302** [comment]
Can't reproduce with `List-KR` enabled.
@AdamWr  please check on your end.

**Comment by AdamWr** [comment]
I do not see ads with `List-KR` enabled.
