### ISSUE TITLE
Wrong priority labels

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7667]
Priority labels are wrong. P1 (Priority 1) is the highest priority and not the lowest... for reference: https://github.com/AdguardTeam/AdguardForAndroid/labels

**Comment by danidoedel** [comment]
@Alex-302 No response at all? Very customer-friendly 👍

**Comment by Alex-302** [comment]
wrong reposotory
https://github.com/AdguardTeam/ReportsWebApp/issues/97#issuecomment-349703737
just wait. It is not critical issue.

**Comment by danidoedel** [comment]
Well didn‘t know it‘s already on the list there so sorry about that. You could have referenced it though ;)
