### ISSUE TITLE
Ace Stream app - missed ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7668]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

> Сейчас при запуске файлов появляется. Как и до этого. Хотя файл ace `engine.exe` добавлен в фильтруемые.

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32935695-e7d9d8b4-cb79-11e7-965a-d9a557a93d5d.png)

![image](https://user-images.githubusercontent.com/15856304/32935760-24ef68c2-cb7a-11e7-9323-6c68ee73d70c.png)

</details><br/>

***System configuration***

**Filters:**

- FilterId:1 Name: Russian filter Url: https://filters.adtidy.org/extension/chromium/filters/1.txt
- FilterId:2 Name: English filter Url: https://filters.adtidy.org/extension/chromium/filters/2.txt
- FilterId:3 Name: Spyware filter Url: https://filters.adtidy.org/extension/chromium/filters/3.txt
- FilterId:4 Name: Social media filter Url: https://filters.adtidy.org/extension/chromium/filters/4.txt
- FilterId:14 Name: Annoyances filter Url: https://filters.adtidy.org/extension/chromium/filters/14.txt
- FilterId:108 Name: EasyList Hebrew Url: https://raw.githubusercontent.com/AdBlockPlusIsrael/EasyListHebrew/master/EasyListHebrew.txt
- FilterId:119 Name: Icelandic ABP List Url: http://adblock.gardar.net/is.abp.txt

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows
Browser:                               | -
AdGuard version:                       | 6.1.331.1732 (update requestsed)
AdGuard DNS:                           | None
Helpdesk ID (if exists):               | 728879

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
где её увидеть-то? На скрине какой-то сайт, похоже.
