### ISSUE TITLE
Norwegian Site in Dutch Filter List

### ISSUE THREAD

**Issue by BPower0036** [AdguardTeam/AdguardFilters#76695]
https://github.com/AdguardTeam/AdguardFilters/blob/becba2e1164db76e47f75e2c4c007cda381aa657/DutchFilter/sections/replace.txt#L7

This is a **norwegian** site (www.tv2.no). I don't know if this filter have to be remove from the Dutch Filter List and placed in the Norwegian Filter list?

**Comment by krystian3w** [comment]
@DandelionSprout no have privileges to use `replace`: https://github.com/AdguardTeam/FiltersRegistry/blob/f8c123f086b8df9b8691992e1bfb693de096694e/filters/ThirdParty/filter_249_NorwegianList/metadata.json#L20 - `high` no enough, possible use replace need change to `full` (may no possible for recommended `/ThirdParty/` projects).

 I know nothing about AdGuard planning to launch a Filter list catalog "`/AdguardFilters/NorwayFilter/sections/`" based on Kristof's project.

**Comment by Alex-302** [comment]
Moved.
