### ISSUE TITLE
Яндекс навигатоp - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7672]
***Issue URL***: https://play.google.com/store/apps/details?id=ru.yandex.yandexnavi&hl=ru — ***Ads***
***Issue Type***: Ads
***Comment***: Приложение Яндекс навигатоp. Все указания выполнил. Время 13:50, лог в 1658583
***Screenshot***: 
[Screenshot 1](https://image.prntscr.com/image/MKzjPgqqQS6erDksnYKwNA.png)

***System configuration***

Information | value
--- | ---
Platform: | And
Adguard version: | 2.10.108
Adguard mode: | VPN
Filtering quality: | High-quality
Filters: | Russian,<br>English,<br>Spyware,<br>Social media,<br>Mobile Ads,<br>Annoyances,<br>Simplified domain names

**Comment by Alex-302** [comment]
ответил в оригинальном таске
