### ISSUE TITLE
Друг вокруг app - ads

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7673]
***Issue URL***: https://play.google.com/store/apps/details?id=drug.vokrug — ***Ads***
***Issue Type***: Ads
***Comment***: Здравствуйте! После обновления, стала "просачиваться" реклама в приложении. В частности "друг вокруг"
***Screenshot***: 
[Screenshot 1](https://image.prntscr.com/image/Nc-1krfhSJKhh8ERggvFOQ.png)

***System configuration***

Information | value
--- | ---
Platform: | And
Adguard version: | 2.10
Adguard mode: | VPN
Filtering quality: | High-quality
Filters: | Russian,<br>English,<br>Spyware,<br>Social media,<br>Japanese,<br>Mobile Ads,<br>Annoyances

**Comment by Alex-302** [comment]
ответил в оригинальном таске
