### ISSUE TITLE
http://vuzyinfo.ru - annoyance

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardFilters#7675]
http://vuzyinfo.ru/ekzameny/dlitelnost-dejstviya-rezultatov-ege-za-2014-2015-2016-god.html

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/32942475-d8f1cdda-cb91-11e7-8d99-e0341d5898a0.png)

</details>

### Your environment
1641689

* Adguard version: AdGuard for Mac 1.5.0
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off

**Comment by Alex-302** [comment]
fixed
