### ISSUE TITLE
Captcha Issue.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#7677]
@redirectr00t commented on [Wed Nov 08 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/2000)

Latest Adguard, with Stealth mode Enabled, **cannot bypass the Captcha verification** on this domain
http://whois.domaintools.com and almost on any domain with enabled Captcha verification.

{"ProtocolVersion":"1","LogRecords":[{"ConnectionId":2856,"RequestId":4424,"ProcessId":4976,"Url":"https://www.google.com/recaptcha/api2/replaceimage?k=6Lf1LxETAAAAACx7vcORxcc3x_Cl405B24nMHNhg","AppName":"firefox.exe","Type":1,"ProtocolType":"Tcp","Method":"POST","StatusDescription":"OK","StatusCode":200,"RemoteIpAddress":"172.217.18.202:443","Rule":null,"Source":"https://www.google.com/recaptcha/api2/bframe?hl=cn&v=r20171031153338&k=6Lf1LxETAAAAACx7vcORxcc3x_Cl405B24nMHNhg","IsThirdParty":false,"LogRecordType":3,"BlockType":0,"FiredContentRules":null,"RequestHeaders":{"Host":"www.google.com","User-Agent":"Mozilla/5.0 Gecko/20100101  #Firefox/55.0","Accept":"*/*","Accept-Language":"cn-CN,cn;q=0.8,en-US;q=0.5,en;q=0.3","Accept-Encoding":"gzip, deflate, br","Content-Type":"application/x-www-form-urlencoded;charset=utf-8","Referer":"https://www.google.com/recaptcha/api2/bframe?hl=cn&v=r20171031153338&k=6Lf1LxETAAAAACx7vcORxcc3x_Cl405B24nMHNhg","Content-Length":"2093","DNT":"1","Connection":"keep-alive"},"ResponseHeaders":{"Content-Type":"application/json; charset=utf-8","Content-Encoding":"gzip","Date":"Wed, 08 Nov 2017 20:42:16 GMT","Expires":"Wed, 08 Nov 2017 20:42:16 GMT","Cache-Control":"private, max-age=0","X-Content-Type-Options":"nosniff","X-Frame-Options":"SAMEORIGIN","X-XSS-Protection":"1; mode=block","Server":"GSE","Alt-Svc":"quic=\":443\"; ma=2592000; v=\"41,39,38,37,35\"","Transfer-Encoding":"chunked","X-Adguard-Filtered":"AdGuard for Windows; version=6.2.433.2167"},"FiredFilterId":0,"Time":"2017-11-08T20:42:19.9872958+01:00","ResponseSizeBytes":520,"StartProcessRequestTicks":636457489395654149,"ProcessRequestElapsedTicks":3593818}]}

Resulting in first image selection, and then go away, to able to complete need to disable AdGuard.

---

@redirectr00t commented on [Wed Nov 08 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/2000#issuecomment-342826546)

The cause is the **Hide your User-Agent**, if Unticked, can proceed, wasn't happening some weeks ago.

The issue is the generic User-Agent used by AdGuard, infact I leave that space always empty, need to repro if entering a useragent string change results.

Using a custom useragent as: AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.92 Mobile Safari/537.36

result in the ReCaptcha working, **maybe the default AdGuard User-Agent is blacklisted** server side.

![2017-11-08_14-58-26](https://user-images.githubusercontent.com/7214961/32553250-9675486c-c496-11e7-81b9-a2411ec491b9.png)

To add that the default UserAgent site suggested, **useragentstring.com** is down
, maybe could insert a function to update the User-Agent lists from a source like Github distro and use something like explained here updated daily, or update the default AdGuard User-Agent but won't be a solution long term, because will be blacklisted again, instead reworking the User-Agent with real ones will solve definitively.

https://techblog.willshouse.com/2012/01/03/most-common-user-agents/

**Comment by Alex-302** [comment]
Use another user agent with the same browser type.
