### ISSUE TITLE
Blocks important content

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardFilters#7678]
@Xellor commented on [Tue Nov 14 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/2004)

### Steps to reproduce

1. console.firebase.google.com
2. create/open project
3. go to section "Database"
3. service offers to test a new technology, it is necessary to open/create a "Cloud Firestore" database
4. add collection with any data (or select an existing one)

### Expected behavior

1. The structure of the database consists of 3 tables, the contents of the right table (the contents of the document) should be displayed.
2. When you add a collection with any data, it is added to the table.

### Actual behavior

1. When you select a collection and document, the contents of the document are not displayed, instead, there is an endless download process.
2. When adding a new collection or document, they are not added.
3. If you turn off filtering on this site, the above problems are not eliminated, only the full exit from the program helps.

<details><summary>Screenshot: </summary>

![bug](https://user-images.githubusercontent.com/17848973/32752665-184c769c-c8db-11e7-8a95-62fa64a1bdab.png)
</details>

### Your environment

* Google Chrome 62.0.3202.89 (Official Build) (64-bit), Firefox 56.0.2 (64-бит)
* Windows 10 (v1709 build 16299.19)
* AdGuard 6.2.433.2167

---

@Xellor commented on [Wed Nov 15 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/2004#issuecomment-344603083)

http://www.radiorecord.ru/radio/charts/
music on this page does not play, the same problem, it can not loading.

**Comment by vozersky** [comment]
там консоль надо в исключения добавить

**Comment by Alex-302** [comment]
какую консоль?

**Comment by vozersky** [comment]
console.firebase.google.com

**Comment by Alex-302** [comment]
ты проверял исключение?

**Comment by Xellor** [comment]
@vozersky, да в том и загвоздка, не работают правила
1) Пробовал отключать фильтрацию через асистент (снять флажок)
2) Прописывал правило собственно ручно (@@||console.firebase.google.com)
Помогает только полное завершение программы (вместе с сервисом).

**Comment by Alex-302** [comment]
@Xellor 
> @@||console.firebase.google.com

это не полное исключение.
Проверьте по одному
```
@@||console.firebase.google.com^$extension
```
```
@@||console.firebase.google.com^$urlblock
```
```
@@||console.firebase.google.com^$document
```

**Comment by Xellor** [comment]
@Alex-302, Ни отдельно ни вместе не работает.
Пропадает асистент, но на console.firebase.google.com все все по прежнему.
Повторюсь на всякий случай, на данный момент единственный выход это полное завершение AG.

**Comment by Alex-302** [comment]
Отключение всех фильтров и модуля расширений на главном экране программы тоже ничего не меняет?

> полное завершение AG.

**Comment by Alex-302** [comment]
вот ещё одно правило, вдруг поможет
```
@@||console.firebase.google.com^$document,extension
```

**Comment by Xellor** [comment]
1) Отключение модуля расширений никак не влияет на проблему.
2) Отключение всех фильтров (включая пользовательский) никак не влияет
3) @@||console.firebase.google.com^$document,extension - это правило никак не влияет

**Comment by Xellor** [comment]
Попробовал отключить все модули, доступные с главного жкрана, это тоже не помогает.
![image](https://user-images.githubusercontent.com/17848973/33231067-e156aea4-d1ff-11e7-8a9e-e74da5585e1b.png)

**Comment by Alex-302** [comment]
Ок. Передал куда следует.

**Comment by vozersky** [comment]
@Xellor 
я не могу воспроизвести проблему
она еще актуальна?
добавьте console.firebase.google.com в https-исключения в разделе network в настройках

**Comment by Xellor** [comment]
@vozersky 
Должно работать, но почему то это не так.

**Comment by Alex-302** [comment]
Браузер перезапускали после добавления домена в https-исключения?

**Comment by Xellor** [comment]
Перезапускал и AG и браузер.

**Comment by Xellor** [comment]
Я систему переустановил (не по этой причине), чистая система, проблема осталась.

**Comment by Alex-302** [comment]
А можно удалённо подключиться(к виртуалке, например)?

**Comment by Xellor** [comment]
можно к рабочей системе, TeamViwer, напиши мне на почту xellor.me@gmail.com

**Comment by Alex-302** [comment]
написал

**Comment by Xellor** [comment]
Скинул данные

**Comment by Alex-302** [comment]
Ок, подключаюсь.

**Comment by Alex-302** [comment]
`firestore.clients6.google.com`
@vozersky этот домен нужно исключить.

**Comment by elmateo487** [comment]
How do I add these to my filters? On OS X I don't see a way to specify HTTPS filters. I tried all combination of these. What do I need to do? @Alex-302 

@@||firestore.clients6.google.com$document,extension,urlblock
@@||firestore.clients6.google.com^$document,extension,urlblock
@@||firestore.clients6.google.com

**Comment by ameshkov** [comment]
> How do I add these to my filters? On OS X I don't see a way to specify HTTPS filters. I tried all combination of these. What do I need to do? @Alex-302

Here you are:
https://uploads.adguard.com/up04_iza6t_AdGuard_Preferences_-_Network.png

**Comment by elmateo487** [comment]
Thank you, I don't know how I missed that.
