### ISSUE TITLE
androidauthority.com

### ISSUE THREAD

**Issue by KatoriYuu** [AdguardTeam/AdguardFilters#76802]
[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:
* **Current behaviour**: 

Images are movable.

[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>

![Screenshot_20210306-180331](https://user-images.githubusercontent.com/42930110/110204648-c59cf180-7ea6-11eb-8996-b39497c6925b.png)
![Screenshot_20210306-180159](https://user-images.githubusercontent.com/42930110/110204650-c766b500-7ea6-11eb-9167-4cd827c752d7.png)

</details><br/>

* **Expected behaviour**: 

[//]: # (Substitute this line with a description of what should happen normally. If needed, provide a screenshot below, same as above)
They must be unmovable.
<details><summary>Screenshot:</summary>

![image](%url_of_screenshot%)
</details><br/>

***Steps to reproduce the problem***:
Go to: https://www.androidauthority.com/android-11-rollout-1201648/
Pull an image and you will see it's movable.
[//]: # (Substitute this lineh a step-by-step instruction how to reproduce the issue)

***System configuration***

**Filters:**
![Screenshot_20210306-181216](https://user-images.githubusercontent.com/42930110/110204821-b9656400-7ea7-11eb-8553-5d46eaffb2cc.png)
![Screenshot_20210306-181228](https://user-images.githubusercontent.com/42930110/110204825-ba969100-7ea7-11eb-824d-350bc9eb0c75.png)

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Android 
Operating system version (Android/iOS) | 10
Browser:                               | Fennec 86.1.1

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
Not reproduced. What causes this issue?

**Comment by Alex-302** [comment]
Yes, I can move after changing zoom. Even without AdGuard. It seems this is by design.
