### ISSUE TITLE
commit f7750faed3647bd882e1b950bffe94041199a2a1 bilanx.dcard.tw

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/AdguardFilters#76897]
who did this?... 

bruh...

![image](https://user-images.githubusercontent.com/75058881/110241377-65cc4680-7f8b-11eb-804e-f331784930b9.png)

https://github.com/AdguardTeam/AdguardFilters/issues/70254#issuecomment-760941292

https://github.com/AdguardTeam/AdguardFilters/commit/f7750faed3647bd882e1b950bffe94041199a2a1#r47958579

**Comment by Yuki2718** [comment]
I can't reproduce as I don't have an account, but `https://bilanx.dcard.tw/v1/sessions` is not sending too much info, just 1 cookie. I'll revert the change. Can you check if adding `||bilanx.dcard.tw/*/configs` to User rules causes breakage? This is sending more user data.

**Comment by Yuki2718** [comment]
@bestpika @tasi788 Sorry for bothering you again, but could you check if
`||bilanx.dcard.tw^`
causes the reported issue?

**Comment by tasi788** [comment]
> @bestpika @tasi788 Sorry for bothering you again, but could you check if
> `||bilanx.dcard.tw^`
> causes the reported issue?

kind of user behavior analysis I guess, I've block them for a while works fine as usual.

**Comment by krystian3w** [comment]
Maybe this need use VPN or walkthrough (step by step).

**Comment by Yuki2718** [comment]
@tasi788 Thank you for your help! If @bestpika also doesn't have the issue I'll re-add `||bilanx.dcard.tw^`.

**Comment by Yuki2718** [comment]
@krystian3w I can probably create an account, but this is SNS so better to ask those who actually use the service - so did I.

**Comment by tasi788** [comment]
now I remember that. This is used to track users' reading of articles and recommend relevant articles to them. 
so i added to [FutaFilter](https://github.com/FutaGuard/FutaFilter)

https://github.com/FutaGuard/FutaFilter/commit/40d704969b270f7d7384360a63052a60b6867551#diff-2b332613793173c8760f7c21faa3b9e3543b3a2329b1a51108993345ded05dbf
`! Dcard
||bilanx.dcard.tw/v1/events^$document`

**Comment by Yuki2718** [comment]
Off topic but do you mind if AG includes FutaFilter by  default?

**Comment by tasi788** [comment]
> Off topic but do you mind if AG includes FutaFilter by default (user still need to enable it)?

ok, that's cool.
don't forget AGH version `hosts.txt` ☺️

**Comment by Yuki2718** [comment]
I'll open an issue ticket in https://github.com/AdguardTeam/FiltersRegistry.

**Comment by c2xusnpq6** [comment]
Even if you block the whole `bilanx.dcard.tw`, the `tag` function of their android app will not be affected

**Comment by Yuki2718** [comment]
@c2xusnpq6 Do you still have the issue?

**Comment by c2xusnpq6** [comment]
dcard.tw web version can't block whole `bilanx.dcard.tw`, that's all I can tell you...

IT **WILL** BREAK

**Comment by Yuki2718** [comment]
@c2xusnpq6 Assuming `||bilanx.dcard.tw/*/events` is okay, can you identify what exactly is causing the trouble? (The network path which should not be blocked)

**Comment by Alex-302** [comment]
I am not sure about it. Which data is collected by this request?

**Comment by tasi788** [comment]
- collect user device, browser info
![image](https://user-images.githubusercontent.com/11913223/110440253-6ed82780-80f3-11eb-8db7-0c3515cffec6.png)
`||bilanx.dcard.tw/*/configs*`

- log user reading article
```{"events":[{"bannerId":"0a9b0abf-0141-438b-81bb-xxxxxxxxxxxxxxx","action":"view","button":"neutral","label":"OK","event":"carouselBannerClicked","createdAt":"2021-03-09T08:17:14.385Z"},{"bannerType":"floating","action":"view","target":"login_signup","forumId":"all","event":"conversionBannerClicked","createdAt":"2021-03-09T08:17:14.698Z"},{"list":"hot","listDetail":"all","itemType":"post","itemId":23550xxxx,"cellNo":2,"itemPosition":0,"event":"widgetItemViewed","createdAt":"2021-03-09T08:17:15.167Z"},{"list":"hot","listDetail":"all","itemType":"post","itemId":23550xxxx,"cellNo":3,"itemPosition":0,"event":"widgetItemViewed","createdAt":"2021-03-09T08:17:15.167Z"},{"list":"hot","forumId":"all","maxCellNo":2,"source":"hot","sourceDetail":"all","event":"postListViewed","createdAt":"2021-03-09T08:17:15.942Z"}]}```
`||bilanx.dcard.tw/*/events` (OPTIONS, POST)

according on the above two points, I think there are good reasons to add two new rules.
