### ISSUE TITLE
UStream.to Adblock Detected

### ISSUE THREAD

**Issue by Vaskiemaia** [AdguardTeam/AdguardFilters#76928]
When opening any channel on UStream it will detect Ublock Origin and it won't work until it's disabled.

Upon disabling the page will be filled with redirects, popups and ads

Checking the logger, UStream will change the key for the stream.

For example:
https://www.ustream.to/live?id=sic-portugale&program=2b44bd0096f425813299c2b1539b90cc

UBlock Disabled:
https://hls.ustream.to/SIC-Portugal.m3u8?token=dec-4f3-99d-e6c-bce-aef-c6f-c94-c5e-ab7-1d9-b0e-d2c-853-5f6-70f-f78-797-256-eef-85c-9-a5d-d1c-e8t-f6c

UBlock Enabled:
https://hls.ustream.to/SIC-Portugal.m3u8?token=adblocker-a5d-d1c-e8t-f6c

uBlock Origin solved it by doing the following:

*$script,redirect-rule=noopjs,domain=beef1999.blogspot.com
@@||bestdisplayformats.com^$script,domain=beef1999.blogspot.com
beef1999.blogspot.com##+js(aopr, console.clear)
beef1999.blogspot.com##+js(aopr, LieDetector)
beef1999.blogspot.com##.popup

**Comment by krystian3w** [comment]
https://github.com/search?q=org%3AAdguardTeam+redirect-rule&type=issues

or wait for fix with allow load few script files.

**Comment by Vaskiemaia** [comment]
Do i need to do anything or will it be added to the AdGuard filters ?

I am not sure i follow

**Comment by wout-codes** [comment]
Aww nasty site.

**Comment by wout-codes** [comment]
Fixed, update filters in about an (1) hour.

**Comment by wout-codes** [comment]
Fixed, update your filters in about an (1) hour.
