### ISSUE TITLE
geniuskitchen.com - Ad leftover

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7700]
***Site***: http://www.geniuskitchen.com/ideas/muffin-tin-friendsgiving-6630?c=562949
***Description***: Ad leftover

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/32981667-d57bda6e-cc78-11e7-87b6-8c84c7967e7f.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.433.2167
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
Fixed here - https://github.com/AdguardTeam/AdguardFilters/commit/64305ceb72df9d26f8b7da3f8a8011e8d2f4a2e3
