### ISSUE TITLE
amd.com - Annoyance

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardFilters#7706]
***Site***: http://www.amd.com/de
***Description***: Annoying overlay

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10995998/32981987-3bf2301e-cc7d-11e7-9787-4bed095091f3.png)

</details>

***System configuration***

Information | value
--- | ---
Operating system: | Windows 10 x64
Browser: | Chrome
AdGuard version: | 6.2.433.2167
AdGuard driver (Windows): | WFP
Simplified filters(iOS) | Off
AdGuard DNS: | None
Stealth mode options (Windows) | Enabled, Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header, Disable cache for third party requests, Block WebRTC, Block Location API

AdGuard filter
--- |
English filter
Spyware filter
Social media filter
Annoyances filter
German filter

**Comment by AdamWr** [comment]
I can't reproduce.
Does it works?
`amd.com##.__acs`

**Comment by BlazDT** [comment]
Can't reproduce too. Probably they discontinued that feedback element.

@danidoedel
Can you still reproduce?
