### ISSUE TITLE
Truecaller, Facebook, Facebook Messenger

### ISSUE THREAD

**Issue by Dvirf8969** [AdguardTeam/AdguardFilters#77136]
Hello
Ads are still shown in Android apps: Truecaller, Facebook and Facebook Messenger.
Please review. 
Thanks

**Comment by gork7777** [comment]
Please indicate which filters you are using

**Comment by Dvirf8969** [comment]
Hi
1. Ad Blocking (AdGuard Base filter)
2. Social (AdGuard Social Media filter)
3. Security (Online Malicious URL Blocklist)
4. Language-specific (EasyList Hebrew)

**Comment by krystian3w** [comment]
Unreadable metod to read ads in this apps (e.g. facebook sponsored ads)?

**Comment by BlazDT** [comment]
Facebook not fixable. Please post a link to Truecaller.

On an unrelated note please enable Mobile Ads filter on your Android device.

**Comment by Dvirf8969** [comment]
Truecaller application, can be download from Play Store  :)

**Comment by BlazDT** [comment]
I see ad rule for that App ist in mobile ads filter:
||graph.facebook.com^$app=com.truecaller
