### ISSUE TITLE
[Tracker] log.strm.yandex.*

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardFilters#77181]
Здравствуйте!
Домен log.strm.yandex.* является техническим и нужен для сбора всякого рода телеметрии. Блокировка онного не влияет на работоспособность ресурсов Яндекса. Прошу добавить его в **фильтр счетчиков и систем аналитики**

**Comment by Alex-302** [comment]
Не уверен про блокировку домена. Где вы его увидели?
