### ISSUE TITLE
Cookie script

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#77256]
https://www.lezzet.com.tr/yemek-tarifleri/sizden-lezzetler/sizden-tatli-tarifleri/hindistan-cevizi-dolgulu-tart

<details><summary>Image</summary>

![www lezzet com tr](https://user-images.githubusercontent.com/74098460/110827059-c1a61080-82a6-11eb-8d34-1feb6e33e7c4.png)

 
</details>

<details><summary>Image</summary>

 
![image](https://user-images.githubusercontent.com/74098460/110827174-de424880-82a6-11eb-98c1-1122bea33371.png)

</details>

```

Filters: Base-Tracking Protection-Social-Annoyances-Turkish 
Browser: Chrome 89
AdGuard Browser Extension 3.5.31 
Win 10

```

**Comment by krystian3w** [comment]
Similar on homepage:

`https://efilli.com/`

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/77260

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/77260
