### ISSUE TITLE
Obsolete cookie rule

### ISSUE THREAD

**Issue by RadicalNoise** [AdguardTeam/AdguardFilters#77260]
They no longer use `CookieMsgBox`

`elle.com.tr,capital.com.tr,elele.com.tr,lezzet.com.tr###CookieMsgBox`

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/77260

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/77256 d
