### ISSUE TITLE
2kspecialist.com AdBlock problem

### ISSUE THREAD

**Issue by SUSWRLD** [AdguardTeam/AdguardFilters#77304]
I turn AdBlock off and I refresh it but it still says I need to turn it off! 

![Screenshot_5](https://user-images.githubusercontent.com/80512976/110914627-3a738f80-82dc-11eb-8e73-6a9dc5322187.png)

**Comment by wout-codes** [comment]
@SUSWRLD Add this to AdBlock Plus in the My Rules section. `||cdn.jsdelivr.net/gh/Arlina-Design/quasar@master/arlinablock.js`.

**Comment by SUSWRLD** [comment]
@wout-codes my rules? where is that at?

**Comment by wout-codes** [comment]
@SUSWRLD Go to AdBlock Plus' Settings > Advanced > Scroll a little down > You should see `MY FILTER LIST` > Paste this `|cdn.jsdelivr.net/gh/Arlina-Design/quasar@master/arlinablock.js` and click Add.

**Comment by SUSWRLD** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/80512976/110917354-6f351600-82df-11eb-9b7d-7bc78eac0e12.png)
added it and went to the website, still same issue!

**Comment by wout-codes** [comment]
Clear cache and cookies, then restart browser.

**Comment by SUSWRLD** [comment]
still doesn't work @wout-codes

**Comment by wout-codes** [comment]
It works on my end. Check with AdGuard Extension, I think it will fix your problem. https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg?hl=en

**Comment by SUSWRLD** [comment]
thank you! it works now!
