### ISSUE TITLE
[NSFW] http://tubepornclassic.com

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/AdguardFilters#7731]
**Site Sample** | 
----|
http://tubepornclassic.com/videos/992794/italian-classic19/

Information                         | Value
---                                 | ---
Operating system:                   | Windows 10 x64
Browser:                            | Chrome x64
AdGuard version:                    | **6.2.436.2170**
Stealth mode: | disabled

Filters enabled |
----------------|
`adguard english ** adguard spy ** adguard annoyances ** polish main ** polish adguard suplement ** polish cookies filter ** KAD (fraud/scam) ** I don't care about cookies`

### Issue:

Player ad overlay, popup after click on LOGO site.

<details><summary><b>Screenshot:</b></summary>

![20171119-124713-001](https://goo.gl/bpKH3N)</details><br/>

**Comment by Alex-302** [comment]
added
```
tubepornclassic.com##.pupen-vupen
tubepornclassic.com##.tpcadv
||tubepornclassic.com/js/1.js
||tubepornclassic.com/assets/js/noname.js
||tubepornclassic.com/ups/*?z=
```
