### ISSUE TITLE
Unresolved issue

### ISSUE THREAD

**Issue by Erengit** [AdguardTeam/AdguardFilters#77352]
My case was closed unresolved. #76744 I can still see the ad there. The issue still remains...

https://forum.donanimhaber.com/24-ekim-1997-karapinar-trafik-kazasi--113564689-2

<details><summary>Screenshot</summary>
 
![dh222](https://user-images.githubusercontent.com/79805068/110973127-e3b69600-836d-11eb-9d1e-b262eb4dca7b.png)

</details>

---

Also `###trend-link` widget is not an ad. There is an option in the user settings to close the widget. I suggest you remove this.

@Alex-302  Please double check.
Thank you.

**Comment by Alex-302** [comment]
Added `forum.donanimhaber.com##div[id^="dha_"]`
