### ISSUE TITLE
quora.com [Sponsored Posts]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#77417]
Are you able to remove the sponsored posts seen on almost all quora pages?

Ex: https://www.quora.com/Do-you-spray-plants-or-just-water-in-soil

Screenshot: https://prnt.sc/10kg37y

Checked with uBlock Origin extension for Chrome with AG & other filters enabled on Windows PC.

**Comment by wout-codes** [comment]
@Nzzyme Can you try with the AdGuard Extension? There are some rules in AdGuard Base (JS Rules) which are not supported in uBlock Origin.

**Comment by Nzzyme** [comment]
Works fine with AG extension. Which rules from all the filter subscriptions are not compatible with uBlock Origin and how can I identify all such rules?

**Comment by wout-codes** [comment]
Open the filtering log and see. It should be something like this:
<details>

![image](https://user-images.githubusercontent.com/76908410/111029251-b255cd00-8436-11eb-810c-b14a6d935bb2.png)
</details>

If you want to try in uBlock Origin, copy and paste the rule in `My Filters` in uBO.

**Comment by Nzzyme** [comment]
I am sorry, I did not understand. I think you misunderstood the question. If we consider AG Base Filter as an example, it has many thousands of rules as seen here:

https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_English/filter.txt

My question is that is there a way to identify that a particular rule is not compatible with uBO in the list?

**Comment by wout-codes** [comment]
I am not sure how. Maybe @okiehsch @gorhill can help you with it.

**Comment by okiehsch** [comment]
> My question is that is there a way to identify that a particular rule is not compatible with uBO in the list?

If you use `uBO` open the logger, then update or enable `Adguard Base`.
It will show all filters discarded as invalid.
![image](https://user-images.githubusercontent.com/16838044/111030216-5755b300-8401-11eb-8c06-2fddc2a7890c.png)

**Comment by Yuki2718** [comment]
I don't see the sponsored post at least by just visiting the URL with uBO default list. BTW all custom script rules i.e. `#%#` with javascript written in it - not predefined ones in https://github.com/AdguardTeam/Scriptlets - are not compatible not only with uBO but also with Firefox and Opera extension of AG.

**Comment by wout-codes** [comment]
> 
> 
> I don't see the sponsored post at least by just visiting the URL with uBO default list. BTW all custom script rules i.e. `#%#` with javascript written in it - not predefined ones in https://github.com/AdguardTeam/Scriptlets - are incompatible not only with uBO but also with Firefox and Opera extension of AG. Hence they're excluded in uBO version of AG lists.

Why though? Not supported by Firefox?

**Comment by Yuki2718** [comment]
Firefox doesn't allow that, probably for security reason.

**Comment by wout-codes** [comment]
I really like Firefox, but it has a major problem, the texts are quite blurry or not so comfortable if compared with Chrome.

**Comment by AdamWr** [comment]
>BTW all custom script rules i.e. #%# with javascript written in it - not predefined ones in https://github.com/AdguardTeam/Scriptlets - are incompatible not only with uBO but also with Firefox and Opera extension of AG.

>By the way, even if you see a JavaScript rule in the filtering log (for example from Base filter), it doesn't mean that it works with Firefox/Opera extension

To make it clear, I meant that "new" added `#%#` rules (not scriptlets) are not available in extension for Firefox/Opera until new version of extension will be released. "Old" rules (added before current release) works fine in extension for Firefox/Opera, also rules added to "user rules" works too.

**Comment by Yuki2718** [comment]
Yeah, as they comes with the extension itself - my comment was bit wrong.

**Comment by krystian3w** [comment]
How will works pure js filters when start Manifest v3 for Chrome/Edge? Also need bump addon version?

**Comment by whyiswhen** [comment]
> How will works pure js filters when start Manifest v3 for Chrome/Edge? Also need bump addon version?

i think manifest v3 got released already .
